### ISSUE TITLE
fluid.layers.generate_proposals的clip问题

### ISSUE THREAD

**Issue by BBT007** [PaddlePaddle/PaddleDetection#1000]
rpn中调用的fluid.layers.generate_proposals默认会对每个bbox进行clip,请问怎样取消clip操作呢？

**Comment by jerrywgz** [comment]
clip的操作是在generate_proposals 这个op的实现当中，具体代码可以参考：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/generate_proposals_op.cu#L136 
这里暂时还不能通过api指定是否进行clip，如果想取消clip操作的话需要修改下源码

**Comment by BBT007** [comment]
> clip的操作是在generate_proposals 这个op的实现当中，具体代码可以参考：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/generate_proposals_op.cu#L136
> 这里暂时还不能通过api指定是否进行clip，如果想取消clip操作的话需要修改下源码

已解决，感谢
