### ISSUE TITLE
【已解决】运行eval.py时报错-使用单个GPU即可

### ISSUE THREAD

**Issue by rock4you** [PaddlePaddle/PaddleDetection#1002]
**python -u tools/eval.py -c configs/faster_rcnn_r50_1x.yml -o weights=output/faster_rcnn_r50_1x/10000**

loading annotations into memory...
Done (t=0.80s)
creating index...
index created!
2020-07-01 14:46:20,078-INFO: places would be ommited when DataLoader is not iterable
W0701 14:46:20.105726 15768 device_context.cc:265] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W0701 14:46:20.110918 15768 device_context.cc:273] device: 0, cuDNN Version: 7.6.
2020-07-01 14:46:38,766-INFO: Test iter 0

python3.7-matrixnms/lib/python3.7/site-packages/paddle/fluid/executor.py:1078: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")

paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::LoDTensor::MergeLoDTensor(std::vector<paddle::framework::LoDTensor const*, std::allocator<paddle::framework::LoDTensor const*> > const&, paddle::platform::Place)
3   paddle::framework::details::ParallelSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, bool)
4   paddle::framework::details::ScopeBufferedMonitor::Apply(std::function<void ()> const&, bool)
5   paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, bool)
6   paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, bool)

----------------------
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information
  [Hint: Expected framework::product(new_dim) / new_dim[0] == framework::product(t->dims()) / t->dims()[0], but received framework::product(new_dim) / new_dim[0]:6 != framework::product(t->dims()) / t->dims()[0]:1.] at (/paddle/nms_rebase/paddle/fluid/framework/lod_tensor.cc:401)

terminate called without an active exception
W0701 14:46:40.562016 16541 init.cc:219] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0701 14:46:40.562042 16541 init.cc:221] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0701 14:46:40.562047 16541 init.cc:224] The detail failure signal is:

W0701 14:46:40.562054 16541 init.cc:227] *** Aborted at 1593586000 (unix time) try "date -d @1593586000" if you are using GNU date ***
W0701 14:46:40.564046 16541 init.cc:227] PC: @                0x0 (unknown)
W0701 14:46:40.564141 16541 init.cc:227] *** SIGABRT (@0x1f400003d98) received by PID 15768 (TID 0x7fe6cf698700) from PID 15768; stack trace: ***
W0701 14:46:40.564260 16541 init.cc:227]     @       0x38c040f130 (unknown)
W0701 14:46:40.564345 16541 init.cc:227]     @       0x38bfc359d9 (unknown)
W0701 14:46:40.564426 16541 init.cc:227]     @       0x38bfc370e8 (unknown)
W0701 14:46:40.565521 16541 init.cc:227]     @     0x7fe67f6c24a5 __gnu_cxx::__verbose_terminate_handler()
W0701 14:46:40.566450 16541 init.cc:227]     @     0x7fe67f6c0646 __cxxabiv1::__terminate()
W0701 14:46:40.567451 16541 init.cc:227]     @     0x7fe67f6c0673 std::terminate()
W0701 14:46:40.568454 16541 init.cc:227]     @     0x7fe67f6c02c7 __gxx_personality_v0
W0701 14:46:40.569490 16541 init.cc:227]     @     0x7fe6bb5aa924 _Unwind_ForcedUnwind_Phase2
W0701 14:46:40.570482 16541 init.cc:227]     @     0x7fe6bb5aac74 _Unwind_ForcedUnwind
W0701 14:46:40.570596 16541 init.cc:227]     @       0x38c040dd90 (unknown)
W0701 14:46:40.570708 16541 init.cc:227]     @       0x38c0408e15 (unknown)
W0701 14:46:40.572278 16541 init.cc:227]     @     0x7fe70f180b8f PyThread_exit_thread
W0701 14:46:40.573817 16541 init.cc:227]     @     0x7fe70f138e25 PyEval_RestoreThread
W0701 14:46:40.575562 16541 init.cc:227]     @     0x7fe63de47d99 pybind11::gil_scoped_release::~gil_scoped_release()
W0701 14:46:40.576179 16541 init.cc:227]     @     0x7fe63df9bb55 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybind10BindReaderEPNS_6moduleEEUlRNS2_9operators6reader40OrderedMultiDeviceLoDTensorBlockingQueueERKSt6vectorINS2_9framework9LoDTensorESaISC_EEE2_bIS9_SG_EINS_4nameENS_9is_methodENS_7siblingENS_10call_guardIINS_18gil_scoped_releaseEEEEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNES11_
W0701 14:46:40.577836 16541 init.cc:227]     @     0x7fe63de66581 pybind11::cpp_function::dispatcher()
W0701 14:46:40.579569 16541 init.cc:227]     @     0x7fe70f04e85b _PyMethodDef_RawFastCallKeywords
W0701 14:46:40.581125 16541 init.cc:227]     @     0x7fe70f04e8d5 _PyCFunction_FastCallKeywords
W0701 14:46:40.582660 16541 init.cc:227]     @     0x7fe70f026cc8 _PyEval_EvalFrameDefault
W0701 14:46:40.584195 16541 init.cc:227]     @     0x7fe70f139c0b _PyEval_EvalCodeWithName
W0701 14:46:40.585676 16541 init.cc:227]     @     0x7fe70f04e107 _PyFunction_FastCallDict
W0701 14:46:40.587195 16541 init.cc:227]     @     0x7fe70f021c96 _PyEval_EvalFrameDefault
W0701 14:46:40.588739 16541 init.cc:227]     @     0x7fe70f01f500 (unknown)
W0701 14:46:40.590277 16541 init.cc:227]     @     0x7fe70f027ace _PyEval_EvalFrameDefault
W0701 14:46:40.591816 16541 init.cc:227]     @     0x7fe70f01f500 (unknown)
W0701 14:46:40.593359 16541 init.cc:227]     @     0x7fe70f027ace _PyEval_EvalFrameDefault
W0701 14:46:40.594900 16541 init.cc:227]     @     0x7fe70f01f500 (unknown)
W0701 14:46:40.596377 16541 init.cc:227]     @     0x7fe70f04e266 _PyFunction_FastCallDict
W0701 14:46:40.597915 16541 init.cc:227]     @     0x7fe70f04f3de _PyObject_Call_Prepend
W0701 14:46:40.599437 16541 init.cc:227]     @     0x7fe70f0508e7 PyObject_Call
W0701 14:46:40.600991 16541 init.cc:227]     @     0x7fe70f1cfc23 (unknown)
W0701 14:46:40.601111 16541 init.cc:227]     @       0x38c0407df3 (unknown)
Aborted

**Comment by willthefrog** [comment]
未合入的feature建议内部沟通。

**Comment by rock4you** [comment]
已解决，使用单卡即可。
