### ISSUE TITLE
paddledetection官方文档特色垂类检测模型

### ISSUE THREAD

**Issue by aooee** [PaddlePaddle/PaddleDetection#1005]
paddledetection官方文档中特色垂类检测模型有行人检测和车辆检测两类，两个模型。现在如果想将其合并成一个模型，同时检测车辆和行人的话，请问能不能提供官方文档中行人检测和车辆检测训练所使用的数据集呢？官方有没有同时检测车辆和行人的模型呢？谢谢！  邮箱：a13879978496@163.com

**Comment by willthefrog** [comment]
是内部业务数据，不太方便提供。目前没有同时检测的模型。
