### ISSUE TITLE
cpp运行出错

### ISSUE THREAD

**Issue by hhh5446** [PaddlePaddle/PaddleDetection#1007]
cpp编译成功后运行不了

./main --model_dir=~/software/PaddleDetection/inference_model/yolov3_darknet/ --image_path=~/software/person.jpg 
terminate called after throwing an instance of 'YAML::BadFile'
  what():  bad file
已放弃 (核心已转储)

**Comment by Channingss** [comment]
麻烦把yaml里面的内容截图贴一下， 另外使用的是release/0.3的分支开发吗

**Comment by hhh5446** [comment]
@Channingss
use_python_inference: false
mode: fluid
draw_threshold: 0.5
metric: COCO
arch: YOLO
min_subgraph_size: 3
with_background: false
Preprocess:
- image_shape:
  - 608
  - 608
  interp: 2
  max_size: 0
  target_size: 608
  type: Resize
  use_cv2: true
- is_channel_first: false
  is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: Normalize
- channel_first: true
  to_bgr: false
  type: Permute
label_list:
- person
- bicycle
剩下的类别就不写了，是用的0.3版本
位于分支 release/0.3
您的分支与上游分支 'origin/release/0.3' 一致。

**Comment by hhh5446** [comment]
> 麻烦把yaml里面的内容截图贴一下， 另外使用的是release/0.3的分支开发吗

已贴，谢谢
