### ISSUE TITLE
ValueError: Model pretrain path output/blazeface/model_final does not exists.

### ISSUE THREAD

**Issue by colorjam** [PaddlePaddle/PaddleDetection#1009]
Hi, when I run the code
```
python -u tools/face_eval.py -c configs/face_detection/blazeface_nas.yml \
       -o weights=output/blazeface/model_final \
       --eval_mode=widerface
```
I encountered the  following error:
```
ValueError: Model pretrain path output/blazeface/model_final does not exists.
```
The pretrained model is download from https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/featured_model/FACE_DETECTION.md

**Comment by still-wait** [comment]
@colorjam 请确认`output/blazeface/`是否有model_final文件夹或者`model_final.pdparams`文件

**Comment by colorjam** [comment]
@still-wait 你好，载下来的文件夹中是以下文件，似乎是比较分散的权重：
```
batch_norm_0.b_0
batch_norm_0.w_0
...
double_blaze_22_sep_weights
shortcutblaze_1_weights
...
```

**Comment by still-wait** [comment]
@colorjam 这个报错由于权重文件夹不存在，你将这些下载解压后的权重文件放到`output/blazeface/model_final`目录下，或者 `-o weights=path/to/weights` 请指定一个你权重实际存放路径，再试一下呢？

**Comment by colorjam** [comment]
@still-wait 感谢！模型可以load了，但是跑的时候出现:
```
----------------------
Error Message Summary:
----------------------
ExternalError:  Cudnn error, CUDNN_STATUS_BAD_PARAM  at (/paddle/paddle/fluid/operators/batch_norm_op.cu:198)
  [operator < batch_norm > error]
```
请问是什么原因呢？

**Comment by still-wait** [comment]
@colorjam 请检查cuDNN安装是否正确，GPU 版本的 PaddlePaddle 需要使用 cuDNN 7.3+ 版本。

**Comment by colorjam** [comment]
@still-wait 你好，我查看cuDNN版本为7.6.0，但是PaddlePaddle检测到的是7.4.0
![image](https://user-images.githubusercontent.com/23700012/86526385-22827b00-bec6-11ea-8b8d-e6e5b15e7972.png)
![image](https://user-images.githubusercontent.com/23700012/86526389-3928d200-bec6-11ea-9578-7052d866e3dd.png)

**Comment by still-wait** [comment]
@colorjam 请检查一下cuDNN7.6是否export到当前环境中了呢？一般`cudnn.h`存放至`**/cuda/include/`目录中。

**Comment by colorjam** [comment]
可以咯~感谢
