### ISSUE TITLE
BlazeFace landmark detection

### ISSUE THREAD

**Issue by rose-jinyang** [PaddlePaddle/PaddleDetection#1010]
Hello
How are you?
Thanks for contributing this project.
I have a question.
Everyone hopes to implement a joint face and landmark detection network with BlazeFace.
Did u implement the landmark detection part of BlazeFace in this project?
if not so, could u implement it too?
Thanks

**Comment by still-wait** [comment]
@rose-jinyang Thanks for following our work.  The face landmark detection part of the code is released, and model weights will be released soon. You can refer to [face detection document](https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/featured_model/FACE_DETECTION_en.md#face-key-point-detection).

**Comment by rose-jinyang** [comment]
Hello
We need the entire project for re-training own BlazeFace model for joint face and landmark detection.
Thanks.

**Comment by still-wait** [comment]
@rose-jinyang Now We support five points landmark detection, if you want increase the number of points, please modify [Reader of WiderFace](https://github.com/PaddlePaddle/PaddleDetection/blob/master/ppdet/data/source/widerface.py) and [ssd_with_lmk_loss function](https://github.com/PaddlePaddle/PaddleDetection/blob/master/ppdet/modeling/losses/ssd_with_lmk_loss.py#L220).
