### ISSUE TITLE
yolov4无法导出模型

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleDetection#1012]
!python tools/export_model.py -c myconfigs/yolov4_cspdarknet_voc.yml --output_dir=export_model/v1 -o weights=output/yolov4_cspdarknet_voc/best_model TestReader.inputs_def.image_shape=[3,608,608]

/home/aistudio/work/PaddleDetection
Traceback (most recent call last):
  File "tools/export_model.py", line 215, in <module>
    main()
  File "tools/export_model.py", line 196, in main
    test_fetches = model.test(feed_vars)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 162, in test
    return self.build(feed_vars, mode='test')
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 90, in build
    im_size = feed_vars['im_size']
KeyError: 'im_size'

不知道这个im_size该怎么配置

**Comment by heavengate** [comment]
请问你是修改了什么配置么，我本地测试了下是可以导出的
是否修改了模型里面和`im_size`相关的或者
https://github.com/PaddlePaddle/PaddleDetection/blob/db5f0d70daba3e40ba4a54b47350c0bf5f0292a1/configs/yolov4/yolov4_cspdarknet_voc.yml#L130

**Comment by thunder95** [comment]
> 请问你是修改了什么配置么，我本地测试了下是可以导出的
> 是否修改了模型里面和`im_size`相关的或者
> https://github.com/PaddlePaddle/PaddleDetection/blob/db5f0d70daba3e40ba4a54b47350c0bf5f0292a1/configs/yolov4/yolov4_cspdarknet_voc.yml#L130

您好， 我应该是没改相关配置，我只是用自己的数据做了个迁移学习。下面是yml文件， 我改了格式txt，因为上传不了yml。

[yolov4_cspdarknet_voc.txt](https://github.com/PaddlePaddle/PaddleDetection/files/4867550/yolov4_cspdarknet_voc.txt)

**Comment by heavengate** [comment]
PaddleDetection用的哪个分支呢？

**Comment by thunder95** [comment]
release/0.3

> PaddleDetection用的哪个分支呢？

**Comment by heavengate** [comment]
![屏幕快照 2020-07-03 下午2 49 09](https://user-images.githubusercontent.com/12605721/86440074-6ba6c380-bd3c-11ea-848f-f6d0792cce2e.png)
试了一下release/0.3分支上能成功导出，请问你有修改啥么

**Comment by thunder95** [comment]
> ![屏幕快照 2020-07-03 下午2 49 09](https://user-images.githubusercontent.com/12605721/86440074-6ba6c380-bd3c-11ea-848f-f6d0792cce2e.png)
> 试了一下release/0.3分支上能成功导出，请问你有修改啥么

只是修改了yml配置，我刚刚重新从gitee上拉了个全新的代码并切换到这分支，使用之前的配置和训练的模型，export时报的是同样的错。

**Comment by heavengate** [comment]
建议从github拉，gitee上版本比较老

**Comment by thunder95** [comment]
我从github重新拉了一遍 包括又训练了一次，再次export_model还是会报同样的错

**Comment by thunder95** [comment]
发现官方提供的yml，在test_reader里缺少了im_size, 我加上之后就可以了：
inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
