### ISSUE TITLE
WIN10系统安装cocoapi遇到问题

### ISSUE THREAD

**Issue by wdywsq** [PaddlePaddle/PaddleDetection#1016]
报错信息e:\learn\anaconda\include\pyconfig.h(203): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
error: command 'E:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Bin\amd64\cl.exe' failed with exit status 2。网上搜索要重新下载了一个visual studio 2019将win10sdk 和生成工具都重新安装了，但仍然出这两条报警。
按照这篇文档也进行过尝试，但也不成功。https://www.cnblogs.com/yihe/p/8467984.html
感觉是环境设置上的问题。

**Comment by wdywsq** [comment]
(base) E:\learn\paddledemo\PaddleDetection\cocoapi\PythonAPI>python setup.py install
running install
running bdist_egg
running egg_info
writing pycocotools.egg-info\PKG-INFO
writing dependency_links to pycocotools.egg-info\dependency_links.txt
writing requirements to pycocotools.egg-info\requires.txt
writing top-level names to pycocotools.egg-info\top_level.txt
reading manifest file 'pycocotools.egg-info\SOURCES.txt'
writing manifest file 'pycocotools.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
skipping 'pycocotools\_mask.c' Cython extension (up-to-date)
building 'pycocotools._mask' extension
b'dk\xf6e\rN\x94^\tg \x00\\\x00M\x00i\x00c\x00r\x00o\x00s\x00o\x00f\x00t\x00\x020\r\x00\n\x00'
E:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IE:\learn\anaconda\lib\site-packages\numpy\core\include -I../common -IE:\learn\anaconda\include -IE:\learn\anaconda\include "-IE:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Include" "-IE:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\Include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IE:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include" "-IE:\Windows Kits\10\Include\10.0.10240.0\ucrt" "-IE:\Windows Kits\10\Include\10.0.18362.0\km\crt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.7\Release\../common/maskApi.obj -std=c99
cl: 命令行 warning D9002 :忽略未知选项“-std=c99”
maskApi.c
E:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IE:\learn\anaconda\lib\site-packages\numpy\core\include -I../common -IE:\learn\anaconda\include -IE:\learn\anaconda\include "-IE:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Include" "-IE:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\Include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IE:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include" "-IE:\Windows Kits\10\Include\10.0.10240.0\ucrt" "-IE:\Windows Kits\10\Include\10.0.18362.0\km\crt" /Tcpycocotools\_mask.c /Fobuild\temp.win-amd64-3.7\Release\pycocotools\_mask.obj -std=c99
cl: 命令行 warning D9002 :忽略未知选项“-std=c99”
_mask.c
e:\learn\anaconda\include\pyconfig.h(203): fatal error C1083: 无法打开包括文件: “basetsd.h”: No such file or directory
error: command 'E:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

**Comment by JiaXiao243** [comment]
![image](https://user-images.githubusercontent.com/37854899/86552101-96ca2680-bf79-11ea-85ae-0bf861592987.png)
这个对应的是visual studio 2015的编译器，不是visual studio 2019。默认加载的编译器是报错的这个路径的，需要修改一下PATH环境变量为你新安装visual studio 2015对应的编译器。之前你应该有安装过visual studio 2015，这个安装的应该有些问题

**Comment by JiaXiao243** [comment]
windows上安装的visual studio没有问题，环境变量配置没有问题的前提下，执行pip install Cython，pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI，即可在windows上安装cocoAPI

**Comment by wdywsq** [comment]
> ![image](https://user-images.githubusercontent.com/37854899/86552101-96ca2680-bf79-11ea-85ae-0bf861592987.png)
> 这个对应的是visual studio 2015的编译器，不是visual studio 2019。默认加载的编译器是报错的这个路径的，需要修改一下PATH环境变量为你新安装visual studio 2015对应的编译器。之前你应该有安装过visual studio 2015，这个安装的应该有些问题

**Comment by wdywsq** [comment]
这个的确有可能，现在我就是用的2019 visual studio install 安装的MSVC v140 - VS 2015 C++ 生成工具(v14.00)，Windows 10 SDK (10.0.16299.0)，环境变量也设置了E:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin。就是还是出现此报错。

**Comment by wdywsq** [comment]
![1594010181(1)](https://user-images.githubusercontent.com/67862511/86556300-80c26300-bf85-11ea-8d5a-c3ddf4033693.png)
我这个安装位置是这样的，环境变量设置了也没有用。

**Comment by wdywsq** [comment]
![1594010557(1)](https://user-images.githubusercontent.com/67862511/86556646-7bb1e380-bf86-11ea-88c7-911c87c59027.png)
环境变量设置如下，我不知道这个照片格式您是否能打开我不太会上传截图。

**Comment by wdywsq** [comment]
![1594011132(1)](https://user-images.githubusercontent.com/67862511/86557041-933d9c00-bf87-11ea-819b-c6167d7e4df2.png)
bin下面的文件

**Comment by JiaXiao243** [comment]
E:Program Files(x86)\Microsoft Microsoft Visual Studio 14.2\VC\bin\cl.exe, vc 14.2也安装了是吧？把Path里面的vc版本号14.0都替换成14.2试一下？

**Comment by wdywsq** [comment]
(base) E:\learn\paddledemo\PaddleDetection\cocoapi\PythonAPI>pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\mechrevo\appdata\local\temp\pip-req-build-huq26ulg
  Running command git clone -q https://github.com/philferriere/cocoapi.git 'C:\Users\MECHREVO\AppData\Local\Temp\pip-req-build-huq26ulg'
  fatal: early EOF
  fatal: the remote end hung up unexpectedly
  fatal: index-pack failed
  error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
ERROR: Command errored out with exit status 128: git clone -q https://github.com/philferriere/cocoapi.git 'C:\Users\MECHREVO\AppData\Local\Temp\pip-req-build-huq26ulg' Check the logs for full command output.

**Comment by wdywsq** [comment]
上面是用pip安装尝试的，环境14.0改成14.2后，python setup.py install进行安装，报错跟原来一样，e:\learn\anaconda\include\pyconfig.h(203): fatal error C1083: 无法打开包括文件: “basetsd.h”: No such file or directory
error: command 'E:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

**Comment by wdywsq** [comment]
请问目前还有处理此错误的办法吗？或者我如果不用cocoapi是否可以正常使用paddledet？

**Comment by JiaXiao243** [comment]
1. error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054, 网上搜一下应该可以解决；
2. 环境14.0改成14.2不生效，我觉得还是某些环境变量没有配置对，导致默认加载的vc 14.0；
3.  使用Microsoft Visual Studio 14.0\VC\Bin\amd64\cl.exe报错，我觉得是安装的有问题，可以重新安装VS2015；

**Comment by JiaXiao243** [comment]
可以不用cocoapi，正常使用paddledet，不使用coco数据集即可，可以使用其他数据集
![image](https://user-images.githubusercontent.com/37854899/86990696-bbb7d700-c1cf-11ea-9054-8d579fe9c0b5.png)

**Comment by wdywsq** [comment]
(base) E:\learn\paddledemo\PaddleDetection\cocoapi\PythonAPI>python setup.py install
running install
running bdist_egg
running egg_info
writing pycocotools.egg-info\PKG-INFO
writing dependency_links to pycocotools.egg-info\dependency_links.txt
writing requirements to pycocotools.egg-info\requires.txt
writing top-level names to pycocotools.egg-info\top_level.txt
reading manifest file 'pycocotools.egg-info\SOURCES.txt'
writing manifest file 'pycocotools.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
skipping 'pycocotools\_mask.c' Cython extension (up-to-date)
building 'pycocotools._mask' extension
E:\learn\pythonfujia\c\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IE:\learn\anaconda\lib\site-packages\numpy\core\include -I../common -IE:\learn\anaconda\include -IE:\learn\anaconda\include -IE:\learn\pythonfujia\c\VC\Tools\MSVC\14.26.28801\ATLMFC\include -IE:\learn\pythonfujia\c\VC\Tools\MSVC\14.26.28801\include -IE:\learn\pythonfujia\c\VC\Redist\MSVC "-IE:\Windows Kits\10\Include\10.0.10240.0\ucrt" "-IE:\Windows Kits\10\Include\10.0.18362.0\km\crt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.7\Release\../common/maskApi.obj
maskApi.c
E:\learn\pythonfujia\c\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IE:\learn\anaconda\lib\site-packages\numpy\core\include -I../common -IE:\learn\anaconda\include -IE:\learn\anaconda\include -IE:\learn\pythonfujia\c\VC\Tools\MSVC\14.26.28801\ATLMFC\include -IE:\learn\pythonfujia\c\VC\Tools\MSVC\14.26.28801\include -IE:\learn\pythonfujia\c\VC\Redist\MSVC "-IE:\Windows Kits\10\Include\10.0.10240.0\ucrt" "-IE:\Windows Kits\10\Include\10.0.18362.0\km\crt" /Tcpycocotools\_mask.c /Fobuild\temp.win-amd64-3.7\Release\pycocotools\_mask.obj
_mask.c
E:\learn\anaconda\include\pyconfig.h(203): fatal error C1083: 无法打开包括文件: “basetsd.h”: No such file or directoryerror: command 'E:\\learn\\pythonfujia\\c\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
vs2015重新安装过了，把环境变量也重新设置了，报错会有变化，但是还是不成功，basetsd.h文件找到了，也设置了环境变量，还是不可。

**Comment by wdywsq** [comment]
(base) E:\learn\paddledemo\PaddleDetection\cocoapi\PythonAPI>python setup.py install
running install
running bdist_egg
running egg_info
writing pycocotools.egg-info\PKG-INFO
writing dependency_links to pycocotools.egg-info\dependency_links.txt
writing requirements to pycocotools.egg-info\requires.txt
writing top-level names to pycocotools.egg-info\top_level.txt
reading manifest file 'pycocotools.egg-info\SOURCES.txt'
writing manifest file 'pycocotools.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
skipping 'pycocotools\_mask.c' Cython extension (up-to-date)
building 'pycocotools._mask' extension
E:\learn\pythonfujia\visual studio\community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IE:\learn\anaconda\lib\site-packages\numpy\core\include -I../common -IE:\learn\anaconda\include -IE:\learn\anaconda\include "-IE:\learn\pythonfujia\visual studio\community\VC\Tools\MSVC\14.26.28801\ATLMFC\include" "-IE:\learn\pythonfujia\visual studio\community\VC\Tools\MSVC\14.26.28801\include" -IE:\learn\pythonfujia\c\VC\Redist\MSVC "-IE:\Windows Kits\10\Include\10.0.10240.0\ucrt" "-IE:\Windows Kits\10\Include\10.0.18362.0\km\crt" "-IE:\Windows Kits\10\Include\10.0.18362.0\shared" "-IE:\Windows Kits\10\Include\10.0.10240.0\shared" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.7\Release\../common/maskApi.obj
maskApi.c
E:\learn\pythonfujia\visual studio\community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IE:\learn\anaconda\lib\site-packages\numpy\core\include -I../common -IE:\learn\anaconda\include -IE:\learn\anaconda\include "-IE:\learn\pythonfujia\visual studio\community\VC\Tools\MSVC\14.26.28801\ATLMFC\include" "-IE:\learn\pythonfujia\visual studio\community\VC\Tools\MSVC\14.26.28801\include" -IE:\learn\pythonfujia\c\VC\Redist\MSVC "-IE:\Windows Kits\10\Include\10.0.10240.0\ucrt" "-IE:\Windows Kits\10\Include\10.0.18362.0\km\crt" "-IE:\Windows Kits\10\Include\10.0.18362.0\shared" "-IE:\Windows Kits\10\Include\10.0.10240.0\shared" /Tcpycocotools\_mask.c /Fobuild\temp.win-amd64-3.7\Release\pycocotools\_mask.obj
_mask.c
E:\learn\anaconda\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
pycocotools\_mask.c(3302): warning C4244: “=”: 从“Py_ssize_t”转换到“siz”，可能丢失数据
pycocotools\_mask.c(3712): warning C4244: “函数”: 从“npy_intp”转换到“siz”，可能丢失数据
pycocotools\_mask.c(3712): warning C4244: “函数”: 从“npy_intp”转换到“siz”，可能丢失数据
pycocotools\_mask.c(3712): warning C4244: “函数”: 从“npy_intp”转换到“siz”，可能丢失数据
pycocotools\_mask.c(6719): warning C4244: “=”: 从“npy_intp”转换到“siz”，可能丢失数据
pycocotools\_mask.c(7477): warning C4244: “=”: 从“Py_ssize_t”转换到“siz”，可能丢失数据
E:\learn\pythonfujia\visual studio\community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:E:\learn\anaconda\libs /LIBPATH:E:\learn\anaconda\PCbuild\amd64 "/LIBPATH:E:\learn\pythonfujia\visual studio\community\VC\Tools\MSVC\14.26.28801\ATLMFC\lib\x64" "/LIBPATH:E:\learn\pythonfujia\visual studio\community\VC\Tools\MSVC\14.26.28801\lib\x64" /LIBPATH:E:\learn\pythonfujia\c\VC\Redist\MSVC "/LIBPATH:E:\Windows Kits\10\Lib\10.0.10240.0\ucrt" "/LIBPATH:E:\Windows Kits\10\Lib\winv6.3\km\x86" "/LIBPATH:E:\Windows Kits\10\Include\10.0.18362.0\km\crt" "/LIBPATH:E:\Windows Kits\10\Include\10.0.18362.0\shared" "/LIBPATH:E:\Windows Kits\10\Include\10.0.10240.0\shared" /EXPORT:PyInit__mask build\temp.win-amd64-3.7\Release\../common/maskApi.obj build\temp.win-amd64-3.7\Release\pycocotools\_mask.obj /OUT:build\lib.win-amd64-3.7\pycocotools\_mask.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\../common\_mask.cp37-win_amd64.lib
LINK : fatal error LNK1181: 无法打开输入文件“ucrt.lib”
error: command 'E:\\learn\\pythonfujia\\visual studio\\community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
把整个VS文件删除重新安装之后出现了如下报警。

**Comment by wdywsq** [comment]
成功了感谢老师支撑。
总结有三点：第一visual studio 2019按安装一个版本就好了，文件夹不要中文，不要有空格。
第二：报错的ucrd.lib rc.exe等打不开文件，就把最内层的文件夹设置成环境变量，我是include path lib 全都设置了。

**Comment by wdywsq** [comment]
更正一下刚才那个是ucrt.lib。
第三点是：如果出现找不到basetsd.h，就要 visual studio重新安装，要完全卸载之后安装。
