### ISSUE TITLE
paddledetection的使用疑问

### ISSUE THREAD

**Issue by AIpioneer** [PaddlePaddle/PaddleDetection#1018]
我回忆了一下大致的训练过程：
1) 安装paddleDetection(可能版本有些老，暂时没查版本号，或许后面再尝试一下装最新版本)
 （想起来了，装最新版本一直在提示 paddle 版本需要>2.0.0,  不知道是什么意思？）
2) 把样本集按照Voc的目录分配好，并生成相应的trainval.txt / test.txt / label_list.txt
 2-1) 根据事先的 训练集、验证集 划分，生成 2个照片列表文件 a_trainval.txt  a_test.txt (原始版本)；
 放在VOCdevkit/VOC2007/ImageSets/Main目录下
 注意，此处txt文件名和说明文档中并不完全一致。
 2-2) 用命令行生成 正式版本的 trainval.txt / test.txt, 和VOCdevkit 同一个目录下
 2-3) 在VOCdevkit 同一个目录下，放置 label_list.txt
3) 选择模型，faster_rcnn_se154_vd_fpn_s1x， 复制  configs/faster_rcnn_se154_vd_fpn_s1x.yml
 新文件  configs/jy_faster_rcnn_se154_vd_fpn_s1x.yml
 3-1) 修改  configs/jy_faster_rcnn_se154_vd_fpn_s1x.yml，把TrainReader 等设置好。
 3-2) 
4) 训练
 python -u tools/train.py -c configs/jy_faster_rcnn_se154_vd_fpn_s1x.yml 
 -o pretrain_weights=https://paddlemodels.bj.bcebos.com/object_detection/faster_rcnn_se154_vd_fpn_s1x.tar
 finetune_exclude_pretrained_params=['cls_score','bbox_pred']   
 --eval --output_eval output/output_eval --use_tb
5) 导出模型
 python -u tools/export_model.py -c configs/jy_faster_rcnn_se154_vd_fpn_s1x.yml \
  --output_dir=./inference_model
6) 用训练所得模型进行照片检测
 python -u tools/infer.py -c configs/jy_faster_rcnn_se154_vd_fpn_s1x.yml \
  --infer_img=demo/201902120932250104.jpg

目前有以下问题:
1) 最新版本paddleDetection的安装失败，好像提示 paddle 版本需要>2.0.0，不知是什么问题？
 更具体的出错信息，等有空我再试一次时，把出错信息copy出来。
2) 训练后，我用 export_model.py  确实生成了模型文件。但是后面我 infer.py 时没法把这个模型用起来，不知道应该用什么命令
 来用这个训练得到的模型进行预测？
3) 我现在还是使用训练的config文件来进行 一个照片的检测，能否用什么命令，对一个目录下的文件进行批量预测，
 最好 输出 预测的框、各框得分、在图上画框；
4) 我在训练时，用输出的日志目录，用tensorboard看到了训练中的 各loss曲线变化，但是没看到 阶段性的eval产生的 验证集上的
 检测结果（图像方式）。因为在tensorflow上训练是能看到，感觉很直观，所以希望这次也能通过配置看到。

**Comment by still-wait** [comment]
@AIpioneer 
（1）在master分支下对yolo系列算法做了升级，需要paddlepaddle-2.0.0版本才能运行，如果对新功能没有需求可以切换至release/0.3的稳定分支，或更新至paddle-2.0.0也可。
（2）模型直接预测使用`tools/infer.py`，模型预测部署需要使用`deploy/python/infer.py`，参考[https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/python](https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/python), 具体训练评估流程，请参照[自定义数据集文档](https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/tutorials/Custom_DataSet.md#%E9%99%84%E4%B8%80%E4%B8%AA%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86demo)
（3）`python tools/infer.py -c xxx  --infer_dir path/to/image_list` 可以使用`--infer_dir`指定图片文件夹，可进行批量预测。
（4）训练时携带`--eval`会边训练边评估模型，可以使用VisualDL对训练评估可视化，携带 `--use_vdl`参数即可，参考[开始训练教程]（https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/tutorials/QUICK_STARTED_cn.md#%E5%BC%80%E5%A7%8B%E8%AE%AD%E7%BB%83）
