### ISSUE TITLE
How to specify batch size

### ISSUE THREAD

**Issue by gfilipekint** [PaddlePaddle/PaddleDetection#102]
Hi guys, sorry if this is obvious but how do I specify what batch size to use in order to run for example mask rcnn on GPU? I don't see that flag anywhere.

**Comment by qingqing01** [comment]
@gfilipekint 

Batch size is set in YAML config, see 

https://github.com/PaddlePaddle/PaddleDetection/blob/b5b4dc8f60a19b8fea6ee3bbe8ceca60dca60a20/configs/mask_rcnn_r50_1x.yml#L105-L123
