### ISSUE TITLE
Model Parameters of NAS_v2

### ISSUE THREAD

**Issue by colorjam** [PaddlePaddle/PaddleDetection#1024]
Can you provide the Model Size of BlazeFace NAS_V2?

**Comment by still-wait** [comment]
@colorjam 已经在master分支发布[docs](https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/featured_model/FACE_DETECTION.md#%E6%8E%A8%E7%90%86%E6%97%B6%E9%97%B4%E5%92%8C%E6%A8%A1%E5%9E%8B%E5%A4%A7%E5%B0%8F%E6%AF%94%E8%BE%83)

**Comment by colorjam** [comment]
@still-wait 请问这个model_size是如何获取的呢？可以计算模型的FLOPs吗？

**Comment by still-wait** [comment]
@colorjam 在nas搜索过程中通过PaddleSlim的`flops`接口对FLOPs进行计算，[代码位置](https://github.com/PaddlePaddle/PaddleDetection/blob/master/slim/nas/train_nas.py#L71)，PaddleDetection中暂无计算FLOPs的脚本。

**Comment by qingqing01** [comment]
@colorjam 如果仅仅是看下模型的体积，参考： https://github.com/PaddlePaddle/PaddleDetection/issues/989#issuecomment-650681847

**Comment by colorjam** [comment]
@qingqing01 模型参数没有.pdparams这个文件，参数文件是下面这样：
![image](https://user-images.githubusercontent.com/23700012/86743897-cc4f3c80-c06b-11ea-9984-916498d94aab.png)
用`du -h output/blazeface/model_final`查看的话大小是1.5M, 和 [FACE_DETECTION](https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/featured_model/FACE_DETECTION.md)
里提到的模型大小为 0.777M似乎不太一致？

**Comment by qingqing01** [comment]
@colorjam 


```
python tools/export_model.py -c configs/face_detection/blazeface_nas_v2.yml \
        --output_dir=inference_model \
        -o weights=https://paddlemodels.bj.bcebos.com/object_detection/blazeface_nas2.tar \
        TestReader.inputs_def.image_shape=[3,640,640]
```

然后:

```
ls -l inference_model/blazeface_nas_v2/__params__
-rw-r--r-- 1 root root 397972 Jul  7 10:39 inference_model/blazeface_nas_v2/__params__
```

或 `du -h inference_model/blazeface_nas_v2/__params__`

可以看下磁盘体积。建议查看模型导出之后的大小。单个文件的存储的模型，每个文件里除了模型外，还存了一些其他信息。
