### ISSUE TITLE
paddle出现W0706异常

### ISSUE THREAD

**Issue by vinceyzw** [PaddlePaddle/PaddleDetection#1025]
报错情况：
Connected to pydev debugger (build 201.7846.77)
W0706 10:48:51.948972 5980 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0706 10:48:51.948985 5980 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0706 10:48:51.948987 5980 init.cc:214] The detail failure signal is:
W0706 10:48:51.948990 5980 init.cc:217] *** Aborted at 1594003731 (unix time) try "date -d @1594003731" if you are using GNU date 
W0706 10:48:51.949749 5980 init.cc:217] PC: @ 0x0 (unknown)
W0706 10:48:51.949796 5980 init.cc:217] *** SIGSEGV (@0x0) received by PID 5980 (TID 0x7f725de04700) from PID 0; stack trace: 
W0706 10:48:51.950470 5980 init.cc:217] @ 0x7f725d9f7390 (unknown)
W0706 10:48:51.951126 5980 init.cc:217] @ 0x0 (unknown)

版本、环境信息：
PaddlePaddle版本：1.7.2 （其他版本我也试了，1.7.0和1.8.2都不行）
GPU：RTX2070 cuda10.0 cudnn 7.6.5
系统环境：ubuntu16.04

使用人脸blazeface预训练模型进行预测，出现报错：
python -u tools/infer.py -c configs/face_detection/blazeface.yml --infer_img=demo/000000570688.jpg --output_dir=infer_output/ --draw_threshold=0.5 -o weights=/root/PaddleDetection_release/paddlemodels.bj.bcebos.com/object_detection/blazeface_original
请大神帮忙看下什么问题

**Comment by jerrywgz** [comment]
请问具体的paddle安装命令是什么呢

**Comment by vinceyzw** [comment]
pip install paddlepaddle-gpu==1.7.2.post107 -i https://mirror.baidu.com/pypi/simple  @jerrywgz

**Comment by jerrywgz** [comment]
想确认下这个错误是稳定复现的吗，现在paddle不支持cuda8了，所以在cuda8环境下会出现这个问题，但是cuda10目前我们这边还没有报过这个错

**Comment by xiegegege** [comment]
@vinceyzw hi~我这里试了下paddle1.7.2运行正常的，感觉可能你的环境有问题~
<img width="891" alt="2f0fe37348fea4cc417bbf664278b1e0" src="https://user-images.githubusercontent.com/46314656/86878849-6bcc0800-c11c-11ea-9ff0-25154153cbf0.png">

**Comment by vinceyzw** [comment]
> 想确认下这个错误是稳定复现的吗，现在paddle不支持cuda8了，所以在cuda8环境下会出现这个问题，但是cuda10目前我们这边还没有报过这个错

非常稳定，每次都是这个错误。我原来是内核是4.15，担心是不是内核要匹配4.4，所以降了内核，最后把系统给弄崩了 @jerrywgz

**Comment by vinceyzw** [comment]
> @vinceyzw hi~ 我这里试了下paddle1.7.2运行正常的，感觉可能你的环境有问题
> <img alt="2f0fe37348fea4cc417bbf664278b1e0" width="891" src="https://user-images.githubusercontent.com/46314656/86878849-6bcc0800-c11c-11ea-9ff0-25154153cbf0.png">

恩，这个命令我在其他服务器上试成功过。关键是环境问题不知道怎么排查

**Comment by xiegegege** [comment]
@vinceyzw 那输入cat /usr/local/cuda/version.txt 的结果显示的也是cuda10吗？

**Comment by vinceyzw** [comment]
> @vinceyzw 那输入cat /usr/local/cuda/version.txt 的结果显示的也是cuda10吗？

conda安装可以了，conda虚拟环境里下载了cuda、cudnn
