### ISSUE TITLE
detection训练内存泄漏

### ISSUE THREAD

**Issue by aixier** [PaddlePaddle/PaddleDetection#1027]
![image](https://user-images.githubusercontent.com/7700464/86691378-57fca500-c03b-11ea-864a-eb4428347c7a.png)
用百度的aisudio训练的时候（用的yolov3_mobilev1).内存占用一直在涨
感觉内存泄漏了

**Comment by jerrywgz** [comment]
我这边测试了下内存基本是保持不变的，可以提供下你那边的paddle版本，cuda，cudnn版本以及检测库的版本吗？我们再追查下，另外可以尝试下将yolov3_reader.yml中的use_process设置为False，以及worker_num设置为-1

**Comment by aixier** [comment]
好的，谢谢
