### ISSUE TITLE
COCO & VOC数据格式下的配置文件修改

### ISSUE THREAD

**Issue by yyqgood** [PaddlePaddle/PaddleDetection#1028]
你好: 我想使用这个cascade_rcnn_mobilenetv3_fpn_640.yml配置文件训练网络, 但此配置文件默认使用COCO数据格式; 我现在有制作好的VOC数据格式, 请问需要修改此配置文件的那些属性来适配(我不想把VOC转换为COCO数据格式)? 谢谢!

**Comment by still-wait** [comment]
@yyqgood 请参考[自定义数据集demo的教程文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/tutorials/Custom_DataSet.md#%E9%99%84%E4%B8%80%E4%B8%AA%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86demo)，其中使用faster-rcnn作为demo来进行适配，cascade_rcnn的参数设置与faster-rcnn大部分相同。

**Comment by jerrywgz** [comment]
主要的修改位置就是类别数，数据路径，以及测试是要将inputs_def中的fields做调整，具体改动可以参考上面的文档还有配置文件 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/configs/faster_reader.yml#L35

**Comment by yyqgood** [comment]
@still-wait @jerrywgz 我这边修改了下,可以正常训练了,谢谢!
