### ISSUE TITLE
下载的yolov3_mobilenet_v3/model.nb在object_detetion_demo错误

### ISSUE THREAD

**Issue by zhang-gang** [PaddlePaddle/PaddleDetection#1029]
将官方https://paddlemodels.bj.bcebos.com/object_detection/mobile_models/lite/yolov3_mobilenet_v3.tar 的model.nb文件放到android_demo/yolo_detection_demo工程中，可以正确运行和识别；
但是将该modle.nb放到android_demo/object_detetion_demo中，运行会出现下面的错误：
lite.demo.object_detection I/Paddle-Lite: [I  8/ 7 14: 7:38.537 .../Paddle-Lite/lite/operators/concat_op.cc:53 InferShapeImpl] out_dims[j] == input_dims_i[j] check failed!
08-07 14:07:38.537 26604-26618/com.baidu.paddle.lite.demo.object_detection I/Paddle-Lite: [I  8/ 7 14: 7:38.537 .../Paddle-Lite/lite/operators/concat_op.cc:53 InferShapeImpl] 20 != 19

有什么办法可以修复object_detetion_demo的错误吗？

**Comment by jerrywgz** [comment]
从报错信息看是纬度不匹配导致的，配置的num_class是多少呢，是否包含了背景类？

**Comment by zhang-gang** [comment]
@jerrywgz  你好，不包含背景类，num_classes: 80，采用的是paddle官方的model.nb和label文件。 问题是同样的model.nb和label文件在yolo_detection_demo可以正常运行；但是在object_detetion_demo出现上面的错误。 难道object_detetion_demo有hard code class吗？代码中好像没有看到。

**Comment by jerrywgz** [comment]
请问下yolo_detection_demo和object_detetion_demo是paddle提供的官方代码吗

**Comment by zhang-gang** [comment]
@jerrywgz 是的，从https://github.com/PaddlePaddle/Paddle-Lite-Demo/下载的，没有做代码改动。只是替换了modle.nb和label文件。 目的是想验证下不同paddle-lite model在真机上的效果。

**Comment by jerrywgz** [comment]
刚确认了下，lite-demo中的object_detetion_demo是针对ssd_mobilenet_v1模型提供的demo版本，yolo_detection_demo是针对yolov3_mobilenetv3模型的，这两个模型本身在类别设置上是不同的，ssd需要增加背景类而yolo不需要，另外ssd需要的image信息和ssd也不完全相同，所以object_detetion_demo这个demo应该是不能用来预测yolo模型的。

**Comment by zhang-gang** [comment]
@jerrywgz  了解，谢谢！
