### ISSUE TITLE
导出模型与原训练产生的模型结果差异

### ISSUE THREAD

**Issue by AN-ZE** [PaddlePaddle/PaddleDetection#1036]
导出模型与原训练产生的模型结果是不是存在一点差异？在testreader不变情况下，结果不同。

**Comment by willthefrog** [comment]
能否具体描述下问题？

**Comment by AN-ZE** [comment]
![图片](https://user-images.githubusercontent.com/29450812/86910400-3b9c5d80-c14c-11ea-83ca-a0e96b456da9.png)

@willthefrog 左侧为导出模型预测结果，右侧是tool/infer.py 预测结果。另外发现，导出模型的c++和python版预测，预处理会将图片固定到固定尺寸，不是说不使用rt预测是不需要固定尺寸吗。

**Comment by willthefrog** [comment]
能否描述下 "左侧为导出模型预测结果" 具体是如何运行的？

**Comment by AN-ZE** [comment]
@willthefrog 使用tool/export_model.py导出模型 ，使用deploy/python/infer.py 预测生成预测结果。使用自制voc，使用网络cascade dcn。之前怀疑是没有添加image_shape造成的，经过测试，发现添加之后也会有异常框。

![图片](https://user-images.githubusercontent.com/29450812/86989836-d9843c80-c1cd-11ea-8e81-dbe97b053f3c.png)

这里输出的结果已经不对了。

**Comment by willthefrog** [comment]
检查下参数的数值及输入顺序吧，看上去像是 `im_info` 和 `im_shape` 没设对

**Comment by AN-ZE** [comment]
@walloollaw 找到问题了，这条代码存在问题，按照代码逻辑，不应该进行padding的。造成两次的输入图像是不一样的。
![图片](https://user-images.githubusercontent.com/29450812/86995997-09870c00-c1dd-11ea-9e66-116173f21241.png)

![图片](https://user-images.githubusercontent.com/29450812/86996022-1e639f80-c1dd-11ea-8f18-f71a08685097.png)

**Comment by AN-ZE** [comment]
好像infer都存在这个问题

**Comment by willthefrog** [comment]
好的，如果解决了请关闭下issue吧，谢谢。
