### ISSUE TITLE
yolov3在Coco数据集上的预训练模型

### ISSUE THREAD

**Issue by kk-zhang-my** [PaddlePaddle/PaddleDetection#1037]
yoyov3在coco数据集上在线量化的时候使用预训练模型，mAP变化不正常，然后调用预训练模型，进行非量化训练的时候，mAP还是很小，想问下有没有正确的预训练模型

**Comment by heavengate** [comment]
用的是哪个配置文件怎么训练的呢

**Comment by kk-zhang-my** [comment]
> 用的是哪个配置文件怎么训练的呢

配置文件是yolov3_darknet.yml，yolov3_reader.yml，训练是使用paddle的在线量化，量化训练指令为python slim/quantization/train.py  --eval -c ./configs/yolov3_darknet.yml -o max_iters=500000\ save_dir=./output/coco_v3  LearningRate.base_lr=0.00001\  LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [10000]}]"\
pretrain_weights=https://paddle-imagenet-models-name.bj.bcebos.com/DarkNet53_pretrained.tar

**Comment by qingqing01** [comment]
@kk-zhang-my 在线量化，需要对训练好的模型进行训练。您需要设置 -o weights加载已经训练好的模型，如果还有问题，可以提新的issue。
