### ISSUE TITLE
蒸馏报错has no is_crowd field

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleDetection#1043]
我训练了个faster-rcnn目标检测模型，想用它蒸馏yolov3_mobilenet_v1

运行命令如下：
!python slim/distillation/distill.py \
    -c myconfigs/yolov3_mobilenet_v1_voc_distill.yml \
    -t myconfigs/faster_rcnn_dcn_r50_fpn_1x.yml \
    -o YOLOv3Loss.batch_size=32 \
    --teacher_pretrained output/faster_rcnn_dcn_r50_fpn_1x/model_final

报错如下：
Traceback (most recent call last):
  File "slim/distillation/distill.py", line 401, in <module>
    main()
  File "slim/distillation/distill.py", line 211, in main
    train_fetches = model.train(teacher_feed_vars)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 241, in train
    return self.build(feed_vars, 'train')
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 73, in build
    self._input_check(required_fields, feed_vars)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 190, in _input_check
    "{} has no {} field".format(feed_vars, var)
AssertionError: OrderedDict([('image', name: "image

**Comment by qingqing01** [comment]
@thunder95   

这个错误可能是FasterRCNN的输入和YOLOv3输入字段不一样导致的，可以看TrainReader的'fields'字段。 我们其实没做过 不同构 检测的蒸馏，也没看到过paper里这样做过，FasterRCNN和YOLOv3的loss也不相同。 感觉还是选择同构的蒸馏，用较大的yolov3_r34/r50/darknet_v1蒸馏yolov3_mobilenet_v1。

**Comment by thunder95** [comment]
> @thunder95
> 
> 这个错误可能是FasterRCNN的输入和YOLOv3输入字段不一样导致的，可以看TrainReader的'fields'字段。 我们其实没做过 不同构 检测的蒸馏，也没看到过paper里这样做过，FasterRCNN和YOLOv3的loss也不相同。 感觉还是选择同构的蒸馏，用较大的yolov3_r34/r50/darknet_v1蒸馏yolov3_mobilenet_v1。

好的， 谢谢， 我试过在yml里直接加上is_crowd也会报keyerror。
那我直接试试用训练好的yolov3_r101来蒸馏

**Comment by qingqing01** [comment]
@thunder95  如果是COCO/VOC数据训练的yolov3_r101 ，也欢迎共享到PaddleDetection里。 :)

**Comment by thunder95** [comment]
我是在训练自己的数据集 效果很差。只是训练yolov3_mobilnet，map可以达到96左右，只训练yolov3_r101 达到98+，但是经过蒸馏mobilnet，只有39.9%， 请问这么训练的时候有什么需要注意的吗，总感觉自己哪里没弄对。蒸馏的时候教师学生都加载了我之前训练过的模型。

> @thunder95 如果是COCO/VOC数据训练的yolov3_r101 ，也欢迎贡献到PaddleDetection里。 :)

**Comment by qingqing01** [comment]
@thunder95 感觉蒸馏过程不太正常。详细说下你有没有什么改动，以及贴下使用命令吧

**Comment by thunder95** [comment]
@qingqing01 您好，感谢回复。 我用了yolov3_r34去蒸，效果也很差。执行的命令如下：

```
# !python slim/distillation/distill.py \
#     -c myconfigs/yolov3_mobilenet_v1_voc_distill.yml \
#     -t myconfigs/yolov3_r101_voc.yml \
#     -o YOLOv3Loss.batch_size=64 \
#     --teacher_pretrained output/yolov3_r101_voc_trained/best_model

#yolov3_r34 ---> yolov3_mobilenet_v1 
!python slim/distillation/distill.py \
    -c myconfigs/yolov3_mobilenet_v1_voc_distill.yml \
    -t myconfigs/yolov3_r34_voc.yml \
    -o YOLOv3Loss.batch_size=64 \
    --teacher_pretrained output/yolov3_r34_voc/best_model
```

yml配置方面没有做什么印象深刻的改动，单独各自训练的时候效果都非常不错。另外我贴上所用到的配置在附件里
[yolov3_.zip](https://github.com/PaddlePaddle/PaddleDetection/files/4951459/yolov3_.zip)

**Comment by baiyfbupt** [comment]
> @qingqing01 您好，感谢回复。 我用了yolov3_r34去蒸，效果也很差。执行的命令如下：
> 
> ```
> # !python slim/distillation/distill.py \
> #     -c myconfigs/yolov3_mobilenet_v1_voc_distill.yml \
> #     -t myconfigs/yolov3_r101_voc.yml \
> #     -o YOLOv3Loss.batch_size=64 \
> #     --teacher_pretrained output/yolov3_r101_voc_trained/best_model
> 
> #yolov3_r34 ---> yolov3_mobilenet_v1 
> !python slim/distillation/distill.py \
>     -c myconfigs/yolov3_mobilenet_v1_voc_distill.yml \
>     -t myconfigs/yolov3_r34_voc.yml \
>     -o YOLOv3Loss.batch_size=64 \
>     --teacher_pretrained output/yolov3_r34_voc/best_model
> ```
> 
> yml配置方面没有做什么印象深刻的改动，单独各自训练的时候效果都非常不错。另外我贴上所用到的配置在附件里
> [yolov3_.zip](https://github.com/PaddlePaddle/PaddleDetection/files/4951459/yolov3_.zip)

你好，单独训效果不错，蒸馏训效果反而变差了可以排查下这两点：
1.  在蒸馏的流程中评估一下teacher的loss和MAP，排除是否存在蒸馏过程teacher参数load不正确的问题。这一点也可以通过去掉蒸馏loss来训练观察下，正常情况是能达到student单独训的效果的
2. 观察下蒸馏loss和真实label loss的比重，使其大致达到1:1同尺度的比例，避免学偏
