### ISSUE TITLE
How about  the  time cost of per image inferring  for this project?

### ISSUE THREAD

**Issue by lyw615** [PaddlePaddle/PaddleDetection#105]
Could you provide your time cost  details when inferring? Just like which  model used, average  per image inferring time , average  image size ,and Gpu type. If it's convenient for you, i will be appreciate a lot.

**Comment by willthefrog** [comment]
our [model zoo doc](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/docs/MODEL_ZOO_cn.md) has pretty detailed benchmark results, you can check it out.

**Comment by lyw615** [comment]
Face detection in this project  faster than face detection in this link ?https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/face_detection. I don't see any  detailed benchmark results of  the links.  Where can i find it?

**Comment by willthefrog** [comment]
please refer to the [face detection doc](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/configs/face_detection/README.md#infer-time-and-model-size-comparison)

**Comment by lyw615** [comment]
But i don't see anything about blazeFace and baceBoxes mentioned in the Readme.md  here https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/face_detection.

**Comment by lyw615** [comment]
My model  is downloaded from  Pyramidbox-v1-SSD 640x640  link, and  with the pretrained model  VGG. All the knowledges getting from the Readme.md of the model are above .

**Comment by willthefrog** [comment]
> But i don't see anything about blazeFace and baceBoxes mentioned in the Readme.md here https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/face_detection.

please see the link I provided.

**Comment by lyw615** [comment]
但是我真的是不知道我发你链接里那个人脸检测项目用的哪个architecture啊，我在人脸检测的时候都没有用过这个链接里的blazeface  和faceboxes 相关的yml文件https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.1/configs/face_detection

**Comment by willthefrog** [comment]
pyramidbox is a different model, which is not included in paddledetection, since it's using VGG as backbnone, my guess is that the runtime speed will be **much** slower than blazeface. But if you really need **detailed** benchmark of pyramidbox, please submit an issue in models repo. Hope this clears it up for you.

**Comment by lyw615** [comment]
Does the prediction time include pre-processing of the image and post-processing time of the prediction result?

**Comment by willthefrog** [comment]
yes
