### ISSUE TITLE
yolov3 anchor_masks 和 downsample_ratios 支持设置么

### ISSUE THREAD

**Issue by linghaolu** [PaddlePaddle/PaddleDetection#1052]
自己的识别任务物体大小比较固定，图片中不存在大的物体。可以设置不要32采样么。
比如
anchor_masks: [[3, 4, 5], [0, 1, 2]]
downsample_ratios: [16, 8]

简单试了一些训练会报错。

**Comment by heavengate** [comment]
跑的哪个模型，具体报什么错呢

**Comment by linghaolu** [comment]
yolov3    configs/dcn/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco.xml
具体报错我这目前还不方便弄，别任务在进行。 你修改写对应reader yolov3_enhance_reader.yml 中
anchor_masks: [[3, 4, 5], [0, 1, 2]]
downsample_ratios: [16, 8]
可以复现
