### ISSUE TITLE
PaddleDetection 2 mmdet?

### ISSUE THREAD

**Issue by linyangsdu** [PaddlePaddle/PaddleDetection#1056]
I want to use model pretrained PaddleDetection weight in mmdetection, but I don't know how to use.

**Comment by qingqing01** [comment]
@linyangsdu Sorry,  we don't have tools to convert models to PyTorch.   Why don't you choose to use PaddleDetection?

**Comment by linyangsdu** [comment]
Because I just have ROCM platform, but I can't run PaddlePaddle successfully in this platform

**Comment by flishwnag** [comment]
> Because I just have ROCM platform, but I can't run PaddlePaddle successfully in this platform

I think you can try https://github.com/PaddlePaddle/X2Paddle to convert paddle models to onnx, then convert the onnx weights to PyTorch. But maybe there are some bugs. Paddle won't officially encourage us to convert their models to other dl framework.
