### ISSUE TITLE
实例分割模型

### ISSUE THREAD

**Issue by sllf77** [PaddlePaddle/PaddleDetection#1057]
我想问一下paddle detection 有没有提供轻量级的实例分割模型，谢谢

**Comment by still-wait** [comment]
@sllf77 实时实例分割模型我们正在开发中，不久就会开源。

**Comment by qingqing01** [comment]
@sllf77 SOLOv2在0.5分支已开源  https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/configs/solov2/README.md
