### ISSUE TITLE
paddle detection 调用训练好的模型作为预训练模型时报错。

### ISSUE THREAD

**Issue by sllf77** [PaddlePaddle/PaddleDetection#1058]
为什么使用-o 参数加载已经训练好的模型作为预训练模型时会报模型路径不存在的错误。
代码：! python -u tools/train.py -c ../cascade_mask_rcnn_r50_fpn_1x.yml\
-o pretrain_weights=output/cascade_mask_rcnn_r50_fpn_1x/model_final

ValueError: Model path output/cascade_mask_rcnn_r50_fpn_1x/model_final does not exists.

**Comment by still-wait** [comment]
@sllf77 你先check一下这个路径下是否有文件，改成`output/cascade_mask_rcnn_r50_fpn_1x/model_final.pdparams`再试下呢

**Comment by sllf77** [comment]
改成output/cascade_mask_rcnn_r50_fpn_1x/model_final.pdparams 后可以运行了，谢谢
