### ISSUE TITLE
cascade_mask_rcnn的C++推理部署问题

### ISSUE THREAD

**Issue by cyanjustice** [PaddlePaddle/PaddleDetection#1060]
用cascade_mask_rcnn训练好的模型，在python端推理均正常，使用export_model.py导出模型后，在C++端推理，bbox分支结果正常，mask分支没有结果。
![image](https://user-images.githubusercontent.com/46018705/87306407-8eaa5200-c54a-11ea-9a92-bc3a4e949eb9.png)
如上图所示，outputnames两个分支正常显示
![image](https://user-images.githubusercontent.com/46018705/87306543-bef1f080-c54a-11ea-82dc-649bd96ef957.png)
bbox分支shape大小正常
![image](https://user-images.githubusercontent.com/46018705/87306619-dc26bf00-c54a-11ea-97e4-e049e33aa46a.png)
mask分支shape大小为0

**Comment by cyanjustice** [comment]
好像发现问题了，把mask分支最后的cond去掉，C++输出shape就正常了，结果是否一致还在验证，我再试一下
![image](https://user-images.githubusercontent.com/46018705/87378383-4168c780-c5c0-11ea-8275-2c60339ad036.png)

**Comment by jerrywgz** [comment]
可以提供下export model导出的infer_cfg.yml吗，mask rcnn这个cond是为了方式bbox_head得到的box为空做的处理

**Comment by cyanjustice** [comment]
C++推理那边我重写的，没有用到yml文件，用的ANALYSIS模式，还需要其他参数吗？

**Comment by cyanjustice** [comment]
是指cascade_mask_rcnn_r50_fpn_1x.yml这个yml吗？

**Comment by jerrywgz** [comment]
我这边测试了下，现在deploy/cpp下暂时还不支持mask的可视化，deploy/python下的python推理部署是可以正常进行mask可视化的，同时对cascade_mask_rcnn_r50_fpn_1x 模型推理结果符合预期；deploy/cpp下是能够得到mask分支的结果，增加了如下代码，shape也是符合预期的
![image](https://user-images.githubusercontent.com/22989727/87507123-654f0a80-c69f-11ea-9d5f-f14906660260.png)
![image](https://user-images.githubusercontent.com/22989727/87507184-857ec980-c69f-11ea-93bb-09b8a9fe2163.png)

测试图片是demo/000000014439.jpg

**Comment by cyanjustice** [comment]
很奇怪，我加了这一句，使用原来的模型代码，出来的shape总是0。
我对原来的python代码做了以下修改：
![image](https://user-images.githubusercontent.com/46018705/87517157-14481200-c6b1-11ea-9685-ceaf05b6ce00.png)
export模型后CPP推理shape以及mask结果一切正常了。
问题是解决了，没想明白原因，assign和return效果应该是一样的啊。。。

**Comment by jerrywgz** [comment]
想问下你的paddle版本还有export_model的命令是什么呢？另外你的代码除了上面截图的部分还改了哪些呢？

我这边用paddle 1.8版本+PaddleDetection master分支是能跑出mask分支的shape的

**Comment by cyanjustice** [comment]
paddle版本用的1.7，代码除了上面部分，模型部分没改过，dataloader部分改的比较多，这个应该不影响推理。
export_model.py文件没改，直接运行就导出模型了。

**Comment by jerrywgz** [comment]
建议换成1.8版本先试下

**Comment by cyanjustice** [comment]
换成1.8就好了，看来还是paddle版本问题
