### ISSUE TITLE
怎么可视化模型结构

### ISSUE THREAD

**Issue by linyangsdu** [PaddlePaddle/PaddleDetection#1062]
我用 VisualDL可视化 官网上放出来的 model(.tar)，结果报错了
![image](https://user-images.githubusercontent.com/62864040/87388784-07a3bb00-c5d8-11ea-9bb5-00b136f2c5eb.png)

启动命令是 visualdl --model ~/cascade_rcnn_dcnv2_se154_vd_fpnn_cas_obj365.tar

**Comment by ShenYuhan** [comment]
您好，关于graph的使用说明您可以参照这里[VisualDL-Graph](https://github.com/PaddlePaddle/VisualDL/blob/develop/docs/components/README.md#graph--%E7%BD%91%E7%BB%9C%E7%BB%93%E6%9E%84%E7%BB%84%E4%BB%B6)
使用的文件可以是保存出的_model_文件
