### ISSUE TITLE
提取预训练权重

### ISSUE THREAD

**Issue by linyangsdu** [PaddlePaddle/PaddleDetection#1066]
我想通过 numpy 提取预训练文件(.tar)中的权重,我首先通过解压，再通过 np.fromfile 读取对应键值的权重，发现都是一维的数据,同时数据也不太对，没办法还原到本来的shape。

**Comment by qingqing01** [comment]
@linyangsdu 

预训练模型文件(.tar)中的每个文件是Paddle的格式，里面包含Paddle相关的数据结构(Tensor)等很多信息，二进制存储的，无法直接通过numpy读取。


如果想保存成numpy格式，需要改动 tools/train.py (或 eval.py 或 infer.py)，加载模型后，然后通过以下操作:

大致的代码如下：

```
params = fluid.io.get_program_parameter(train_prog) # 对应的program

for p in params:
    p_array = np.array(fluid.global_scope().find_var(p.name).get_tensor())

```

**Comment by linyangsdu** [comment]
您好，我通过 export_model.py 在 checkpoint.load_params后面添加

checkpoint.save,得到对应的 .pdparams,再通过 pickle.load，这样做可以吗

**Comment by willthefrog** [comment]
可以的

**Comment by linyangsdu** [comment]
您好，我已经提取出来权重了，并且成功在 pytroch里面实现了相应的结构，但是我发现跑出来的结果在小数点后面几位会有一些不一样，是不是会对效果有一些影响？还有就是想问一下造成这种问题可能的原因？
![image](https://user-images.githubusercontent.com/62864040/87703325-3cc52e80-c7cd-11ea-8c92-0ccfbb843915.png)
![image](https://user-images.githubusercontent.com/62864040/87703347-48b0f080-c7cd-11ea-9f07-db35c0244762.png)

**Comment by linyangsdu** [comment]
我觉得可能的问题: PaddlePaddle  Conv2d的操作中配置 bias_attr = False, 这个和 bias = 0 是一个意思吗？

**Comment by willthefrog** [comment]
> 我觉得可能的问题: PaddlePaddle Conv2d的操作中配置 bias_attr = False, 这个和 bias = 0 是一个意思吗？

是的。不同框架之间op实现会有些差别，少量diff是正常现象。

**Comment by linyangsdu** [comment]
好的，十分感谢！
