### ISSUE TITLE
多个模型pipeline问题

### ISSUE THREAD

**Issue by legendxty** [PaddlePaddle/PaddleDetection#1067]
目前我的项目需要用到多个模型，一张图片采集进来以后，需要经过以下几个步骤得出结果：
1、原图采集
2、角度分类模型(PaddleClass)
3、旋转操作
4、区域检测模型(PaddleDetection)
5、裁剪、切割操作
6、切图分类模型(PaddleClass)
7、合成结果(sklearn)

**问题1：**目前PaddleClass和PaddleDetection套件提供的infer文件都是模型加载、读取、推断在一起操作的。
有没有类似model.load()，model.predict()这样的接口，可以把所有模型都预先加载，等图片来了再依次推断？

**问题2：**目前PaddleClass和PaddleDetection套件读取图片时，都是给定文件路径去读取，这种操作在我的项目中会产生大量的中间过程文件和不必要的写磁盘读磁盘的过程。
请问套件的reader有没有支持传入内存中的图片格式，例如数组或np.array的方式呢？

**Comment by qingqing01** [comment]
@legendxty 多谢反馈，很好的问题。

问题1和2，关于检测:

检测可以参考:  https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/deploy/python/infer.py#L466


大概的伪代码可以这样，可以脱离PaddleDetection的代码，只用infer.py相关的代码即可:

```
from deploy.python.infer import Detector

image_array # np.array
detector = Detector(model_dir, use_gpu=use_gpu, run_mode='fluid')
results = detector.predict(image_array, threshold=0.5)

```

分类也可以类似的方式。



此外，后续我们考虑做成可安装，提供类似非常简洁的接口，感谢反馈。
