### ISSUE TITLE
Faster Rcnn与Faster Rcnn+FPN的区别

### ISSUE THREAD

**Issue by flishwnag** [PaddlePaddle/PaddleDetection#1068]
Model zoo（https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/MODEL_ZOO_cn.md）中，
ResNet101与ResNet101-FPN的介绍如下：
ResNet101 | Faster | 1 | 1x | 9.316 | 38.3 | - | 下载链接 | 配置文件
ResNet101-FPN | Faster | 1 | 1x | 17.297 | 38.7 | - | 下载链接 | 配置文件

为何FPN的Inference fps比Faster版本的要高？我看配置文件中，它们的backbone相同，test proposal都是1000，理论上FPN因为有额外的conv, upsampling层，proposal的数量也更多，应该更慢才对。但是无论是ResNet101还是ResNet50，FPN的速度都比不带FPN的速度快。请问是什么原因导致的？

**Comment by jerrywgz** [comment]
在不带fpn的结构中，主干网络会引出res4的feature到rpn阶段，然后得到proposal进行roi_align，测试的feature map是较大的，会有较大的耗时；而FPN结构中是对res5的feature进行roi_align，相对feature map会缩小。同时两者在进行roi align时的box_resolution参数也不相同，不带FPN结构的box_resolution为14而FPN结构的box_resolution为7，这对速度也有一定影响。这些影响会大于FPN中额外引入的卷积，上采样等操作

**Comment by flishwnag** [comment]
明白了。感谢！
