### ISSUE TITLE
'VOCDataSet' object has no attribute 'set_images'

### ISSUE THREAD

**Issue by amazingzby** [PaddlePaddle/PaddleDetection#1069]
使用VOC格式数据集训练模型，预测时运行tools/infer.py 出现错误：
Traceback (most recent call last):
  File "tools/infer.py", line 256, in <module>
    main()
  File "tools/infer.py", line 105, in main
    dataset.set_images(test_images)
AttributeError: 'VOCDataSet' object has no attribute 'set_images'

**Comment by FDInSky** [comment]
看下你的配置文件TestReader部分，麻烦截下图

**Comment by amazingzby** [comment]
> 看下你的配置文件TestReader部分，麻烦截下图

已找到问题原因，yml文件里TestReader不应该用VOCDataSet，换为ImageFolder解决。
