### ISSUE TITLE
导出的yolov3_mobilenet_v1_voc模型。使用paddle-opt时出错

### ISSUE THREAD

**Issue by martinou** [PaddlePaddle/PaddleDetection#1075]
同过paddledetection训练的导出模型。在使用opt的过程中，出现以下错误：
[I  7/17  8:43:54.916 ...t/github/Paddle-Lite/lite/api/cxx_api.cc:256 Build] Load model from file.
[libprotobuf ERROR /opt/github/Paddle-Lite/third-party/protobuf-host/src/google/protobuf/message_lite.cc:119] Can't parse message of type "paddle.framework.proto.VarType.TensorDesc" because it is missing required fields: data_type
[F  7/17  8:43:54.926 ...e-Lite/lite/model_parser/model_parser.cc:73 TensorFromStream] Check failed: desc.ParseFromArray(buf.get(), size): Cannot parse tensor desc
Aborted

Paddle 版本 1.8.2
paddle-lite 版本 develop
paddle-detection 版本 develop

**Comment by DannyIsFunny** [comment]
你好，从错误提示上看，是转化前的模型有些问题。opt不能正常解析。缺少了一个模型关键参数`data_type `.

**Comment by DannyIsFunny** [comment]
请问模型来源是哪里，可以检查模型来源是否正确

**Comment by martinou** [comment]
> 你好当前develop分支是开发分支，建议使用最近发布的稳定版本 v2.6.1测试模型转化
> 可以直接从预编译结果下载 [opt](https://paddle-lite.readthedocs.io/zh/latest/user_guides/release_lib.html)或者pip install paddlelite安装opt的python 版本

我使用了2.6.1opt编译还是同样的错误

**Comment by qingqing01** [comment]
@martinou 如果还有问题，可以提新的issue，暂且关闭了此issue
