### ISSUE TITLE
关于RPN源码

### ISSUE THREAD

**Issue by linyangsdu** [PaddlePaddle/PaddleDetection#1076]
我看到 rpn_head  GenerateProposals 和 AnchorGenerator 里面有fluid.layers.generate_proposals 和 fluid.layers.anchor_generator，但是进去只能看到 helper.append_op这个操作，想知道具体的源码在哪里找

**Comment by still-wait** [comment]
@linyangsdu [generate_proposals_op.cc](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/generate_proposals_op.cc)和[generate_proposals_op.cu](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/generate_proposals_op.cu)文件是`fluid.layers.generate_proposals`的源码。
[anchor_generator源码](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/)，该目录下有`anchor_generator_op.h`、`anchor_generator_op.cc`和`anchor_generator_op.cu`源文件。每个op可在[Paddle github的repo中](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle)点击`Go to file`进行搜索。

**Comment by linyangsdu** [comment]
好的，谢谢，对于 anchor generator 这块我还是有些疑问，就是 我发现在 rpn_head.py 355行 anchor 这里，没有以(0,0)为中心的anchor，好像有一些 offset?

**Comment by linyangsdu** [comment]
我的相关配置是这个
FPNRPNHead:
  anchor_generator:
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 32

**Comment by still-wait** [comment]
@linyangsdu anchor_generator运算是保持默认的`offset=0.5`。如需修改，可在[AnchorGenerator](https://github.com/PaddlePaddle/PaddleDetection/blob/499dafa8e8f5f8eeb149f2fb3a3ea0e1f747ca13/ppdet/modeling/ops.py#L313)中添加。

**Comment by linyangsdu** [comment]
好的，谢谢！
