### ISSUE TITLE
导出模型问题

### ISSUE THREAD

**Issue by StarryDing** [PaddlePaddle/PaddleDetection#1077]
想问问怎么直接导出model和params文件啊
而不是__model__和__params__文件

**Comment by still-wait** [comment]
@StarryDing 目前使用Paddle 1.7以上训练保存模型使用`fluid.save`，会保存成`name.pdparams`,`name.pdmodel`和`name.pdopt`三个文件,其中pdparams后缀的是权重文件。请使用PaddleDetection release/0.3训练保存模型就行。使用`export_model.py`导出的是`__model__和__params__`文件。

**Comment by StarryDing** [comment]
@still-wait 啊 那拿1.5版本的paddle静态图保存的那种不带下划线的model 和params文件和paddledection导出的带下划线的__model__文件是没什么区别的吗

**Comment by still-wait** [comment]
是一致的，你描述的应该都是使用`fluid.io.save_inference_model`保存的模型

**Comment by StarryDing** [comment]
@still-wait 谢谢啦
