### ISSUE TITLE
关于generate proposal的问题

### ISSUE THREAD

**Issue by linyangsdu** [PaddlePaddle/PaddleDetection#1078]
我想确认一下 nms 的位置，是在每个 feature level 之后得到的 rpn_bbox 对这些 rpn_bbox 进行 nms，再collect 所有 level 的rpn_bbox,进行一个topK的取值，得到最后的结果吗？

**Comment by linyangsdu** [comment]
我自己 nms 的结果(指框的数量和少量框)和 PaddleDetection 跑出来的结果有一些差别，但是大部分框还是一样的，这个是正常现象吗？

**Comment by jerrywgz** [comment]
> 我想确认一下 nms 的位置，是在每个 feature level 之后得到的 rpn_bbox 对这些 rpn_bbox 进行 nms，再collect 所有 level 的rpn_bbox,进行一个topK的取值，得到最后的结果吗？

是这样的；你自己的nms结果是指的rpn阶段还是最终输出阶段呢

**Comment by linyangsdu** [comment]
RPN阶段，我找到问题所在了，是因为5个 feature level的后两个level 生成的 proposal 在 center_y 和 height 有一点点偏差，想问一下这两个level 在 generate proposal 的和别的有什么不同？

**Comment by linyangsdu** [comment]
问题解决
