### ISSUE TITLE
cpp运行出错

### ISSUE THREAD

**Issue by hhh5446** [PaddlePaddle/PaddleDetection#1079]
cpp编译成功后运行不了

./main --model_dir=/software/PaddleDetection/inference_model/yolov3_darknet/ --image_path=/software/person.jpg
terminate called after throwing an instance of 'YAML::BadFile'
what(): bad file
已放弃 (核心已转储)

yml文件：
use_python_inference: false
mode: fluid
draw_threshold: 0.5
metric: COCO
arch: YOLO
min_subgraph_size: 3
with_background: false
Preprocess:

image_shape:
608
608
interp: 2
max_size: 0
target_size: 608
type: Resize
use_cv2: true
is_channel_first: false
is_scale: true
mean:
0.485
0.456
0.406
std:
0.229
0.224
0.225
type: Normalize
channel_first: true
to_bgr: false
type: Permute
label_list:
person
bicycle
剩下的类别就不写了

用的0.3版本
位于分支 release/0.3
您的分支与上游分支 'origin/release/0.3' 一致。

**Comment by jerrywgz** [comment]
c++预测需要先进行编译，然后执行类似如下命令 ./build/main --model_dir=output/blazeface_nas/ --image_path=000000014439.jpg ，编译方法可以参考文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/deploy/cpp/docs/linux_build.md

**Comment by hhh5446** [comment]
> c++预测需要先进行编译，然后执行类似如下命令 ./build/main --model_dir=output/blazeface_nas/ --image_path=000000014439.jpg ，编译方法可以参考文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/deploy/cpp/docs/linux_build.md

是用paddledetection里面的cpp模块编译成功后运行报错

**Comment by jerrywgz** [comment]
具体报错是什么呢

**Comment by hhh5446** [comment]
> 具体报错是什么呢

./main --model_dir=/software/PaddleDetection/inference_model/yolov3_darknet/ --image_path=/software/person.jpg
terminate called after throwing an instance of 'YAML::BadFile'
what(): bad file
已放弃 (核心已转储)

**Comment by jerrywgz** [comment]
请问下paddle版本是什么呢？建议使用1.8之后的版本

看配置文件本身是没问题的，可以再确认下infer_cfg.yml是否在/software/PaddleDetection/inference_model/yolov3_darknet/ 这个路径下

**Comment by hhh5446** [comment]
@jerrywgz 
> 请问下paddle版本是什么呢？建议使用1.8之后的版本
> 看配置文件本身是没问题的，可以再确认下infer_cfg.yml是否在/software/PaddleDetection/inference_model/yolov3_darknet/ 这个路径下


是1.8版本的，文件路径也没问题

**Comment by jerrywgz** [comment]
我这边测试如果infer_cfg.yml这个文件没有找到是会报这个错的，具体报错位置是在include/config_parser.h中的
![image](https://user-images.githubusercontent.com/22989727/87897415-d4e93f00-ca7d-11ea-8512-8cb64d9eb3e5.png)

**Comment by hhh5446** [comment]
@jerrywgz 
> 我这边测试如果infer_cfg.yml这个文件没有找到是会报这个错的，具体报错位置是在include/config_parser.h中的
> ![image](https://user-images.githubusercontent.com/22989727/87897415-d4e93f00-ca7d-11ea-8512-8cb64d9eb3e5.png)

好的，我再试试

**Comment by jerrywgz** [comment]
issue先关闭了，如果还有新的问题可以再提issue，我们会及时跟进
