### ISSUE TITLE
用RetinaNet训练自己的数据集报错求助

### ISSUE THREAD

**Issue by zwf1234** [PaddlePaddle/PaddleDetection#1080]
各位RD同学、老师，我用RetinaNet训练自己的数据集运行时出现以下问题，麻烦帮忙看一下，非常感谢！
（我将retinanet_r101_fpn_1x.yml中的数据集的路径换成了自己的数据集的路径）

InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [-1, 256, 100, 167] and the shape of Y = [-1, 256, 100, 168]. Received [167] in X is not equal to [168] in Y at i:3.
[Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:157)
[operator < elementwise_add > error]

**Comment by qingqing01** [comment]
@zwf1234  请问换成自己数据集之后：

PadBatch的操作还是在？

https://github.com/PaddlePaddle/PaddleDetection/blob/499dafa8e8f5f8eeb149f2fb3a3ea0e1f747ca13/configs/retinanet_r101_fpn_1x.yml#L76-L78

**Comment by zwf1234** [comment]
PadBatch的操作还在：
FasterRCNNTrainFeed:
  batch_size: 2
  batch_transforms:
  - !PadBatch
    pad_to_stride: 128
  dataset:
    #dataset_dir: dataset/coco
    #annotation: annotations/instances_train2017.json
    #image_dir: train2017
    dataset_dir: dataset/fruit/fruit-detection
    annotation: train.txt
  num_workers: 2

FasterRCNNEvalFeed:
  batch_size: 2
  batch_transforms:
  - !PadBatch
    pad_to_stride: 128
  dataset:
    #dataset_dir: dataset/coco
    #annotation: annotations/instances_val2017.json
    #image_dir: val2017
    dataset_dir: dataset/fruit/fruit-detection
    annotation: test.txt
  num_workers: 2

**Comment by zwf1234** [comment]
还在，另外我想问一下release/0.3 或 master分支怎么使用啊？感谢感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月20日(星期一) 中午1:38
收件人:&nbsp;"PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送:&nbsp;"839009829"<839009829@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 用RetinaNet训练自己的数据集报错求助 (#1080)





 
@zwf1234  请问换成自己数据集之后：
 
PadBatch的操作还是在？
 
https://github.com/PaddlePaddle/PaddleDetection/blob/499dafa8e8f5f8eeb149f2fb3a3ea0e1f747ca13/configs/retinanet_r101_fpn_1x.yml#L76-L78

**Comment by qingqing01** [comment]
@zwf1234 

```
FasterRCNNTrainFeed:
batch_size: 2
batch_transforms:
```

从你发的配置中`FasterRCNNTrainFeed`这个是比较老的配置了。建议拉取新的代码:


git clone https://github.com/PaddlePaddle/PaddleDetection.git

直接clone默认就是release/0.3分支。

git branch 是可以看到你使用的分支的。

**Comment by zwf1234** [comment]
您好，我拉取了最新的代码，在训练的时候出现以下问题，望解答，感谢！
2020-07-21 11:22:57,100-INFO: iter: 180, lr: 0.005733, 'loss_cls': '0.994304', 'loss_bbox': '0.445244', 'loss': '1.440329', time: 0.246, eta: 6:07:54
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/lib/function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
2020-07-21 11:23:01,797-INFO: iter: 200, lr: 0.006000, 'loss_cls': 'nan', 'loss_bbox': 'nan', 'loss': 'nan', time: 0.235, eta: 5:51:00
2020-07-21 11:23:06,696-INFO: iter: 220, lr: 0.006267, 'loss_cls': 'nan', 'loss_bbox': 'nan', 'loss': 'nan', time: 0.245, eta: 6:06:42

**Comment by zwf1234** [comment]
您好，我拉取了最新的代码，出现以下问题，麻烦帮忙看下，谢谢
2020-07-21 14:50:54,318-INFO: Test iter 2900
2020-07-21 14:50:57,486-INFO: Test finish iter 2932
2020-07-21 14:50:57,487-INFO: Total number of images: 5863, inference time: 19.275215719800666 fps.
2020-07-21 14:50:57,487-INFO: Start evaluate...
Traceback (most recent call last):
  File "tools/train.py", line 368, in <module>
    main()
  File "tools/train.py", line 290, in main
    cfg['EvalReader']['dataset'])
  File "/home/aistudio/PaddleDetection/ppdet/utils/eval_utils.py", line 236, in eval_results
    map_type=map_type)
  File "/home/aistudio/PaddleDetection/ppdet/utils/voc_eval.py", line 103, in bbox_eval
    detection_map.update(bbox, gt_box, gt_label, difficult)
  File "/home/aistudio/PaddleDetection/ppdet/utils/map_utils.py", line 124, in update
    int(np.array(difficult[max_idx])) == 0:
IndexError: index 0 is out of bounds for axis 0 with size 0
terminate called without an active exception
W0721 14:50:57.782747   676 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0721 14:50:57.782840   676 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0721 14:50:57.782847   676 init.cc:221] The detail failure signal is:

W0721 14:50:57.782860   676 init.cc:224] *** Aborted at 1595314257 (unix time) try "date -d @1595314257" if you are using GNU date ***
W0721 14:50:57.785039   676 init.cc:224] PC: @                0x0 (unknown)
W0721 14:50:57.785149   676 init.cc:224] *** SIGABRT (@0x3e80000026b) received by PID 619 (TID 0x7f919224a700) from PID 619; stack trace: ***
W0721 14:50:57.786913   676 init.cc:224]     @     0x7f91c11f3390 (unknown)
W0721 14:50:57.788589   676 init.cc:224]     @     0x7f91c0e4d428 gsignal
W0721 14:50:57.790238   676 init.cc:224]     @     0x7f91c0e4f02a abort
W0721 14:50:57.791348   676 init.cc:224]     @     0x7f9181bc584a __gnu_cxx::__verbose_terminate_handler()
W0721 14:50:57.792222   676 init.cc:224]     @     0x7f9181bc3f47 __cxxabiv1::__terminate()
W0721 14:50:57.793262   676 init.cc:224]     @     0x7f9181bc3f7d std::terminate()
W0721 14:50:57.794188   676 init.cc:224]     @     0x7f9181bc3c5a __gxx_personality_v0
W0721 14:50:57.795032   676 init.cc:224]     @     0x7f9181ef6b97 _Unwind_ForcedUnwind_Phase2
W0721 14:50:57.795862   676 init.cc:224]     @     0x7f9181ef6e7d _Unwind_ForcedUnwind
W0721 14:50:57.797559   676 init.cc:224]     @     0x7f91c11f2070 __GI___pthread_unwind
W0721 14:50:57.799238   676 init.cc:224]     @     0x7f91c11ea845 __pthread_exit
W0721 14:50:57.799690   676 init.cc:224]     @     0x55f7c7ff9e59 PyThread_exit_thread
W0721 14:50:57.799842   676 init.cc:224]     @     0x55f7c7e7fc17 PyEval_RestoreThread.cold.798
W0721 14:50:57.802119   676 init.cc:224]     @     0x7f914866b959 pybind11::gil_scoped_release::~gil_scoped_release()
W0721 14:50:57.802570   676 init.cc:224]     @     0x7f9148753ed5 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybind10BindReaderEPNS_6moduleEEUlRNS2_9operators6reader40OrderedMultiDeviceLoDTensorBlockingQueueERKSt6vectorINS2_9framework9LoDTensorESaISC_EEE2_bIS9_SG_EINS_4nameENS_9is_methodENS_7siblingENS_10call_guardIINS_18gil_scoped_releaseEEEEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNES11_
W0721 14:50:57.804654   676 init.cc:224]     @     0x7f9148689139 pybind11::cpp_function::dispatcher()
W0721 14:50:57.805194   676 init.cc:224]     @     0x55f7c7f7b744 _PyMethodDef_RawFastCallKeywords
W0721 14:50:57.805647   676 init.cc:224]     @     0x55f7c7f7b861 _PyCFunction_FastCallKeywords

**Comment by qingqing01** [comment]
@zwf1234 

看错误代码，实用的是VOC的评估方式和数据格式， 注意VOC 输入的fields字段 和 COCO不同，可以参考文档: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/tutorials/Custom_DataSet.md#%E7%AC%AC%E4%BA%8C%E6%AD%A5%E9%80%89%E6%8B%A9%E6%A8%A1%E5%9E%8B%E5%B9%B6%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6  

注意有'is_difficult' 等字段。
