### ISSUE TITLE
yolov3_mobilenet_v1_voc模型剪裁参数如何确定

### ISSUE THREAD

**Issue by L-lei** [PaddlePaddle/PaddleDetection#1082]
根据文档使用yolov3_mobilenet_v1_voc模型我最后裁剪成功了，大小为23M。在使用过程中yolov3_mobilenet_v1_voc模型中只要yolo_block参数开头的才可以裁剪，不然在运行时出现输入维度不匹配错误。conv1_weights,yolo_output开头都会有这个错误，但是模型剪裁是剪裁卷积层参数达到缩减卷积层通道数的目的，照理说所有卷积都可以，其它的如果也剪裁需要修改相关输入维度代码？在选择‘剪裁参数确定’有什么技巧没，还是只有一个一直尝试

**Comment by heavengate** [comment]
需要裁剪哪些参数是通过`--prune_params`指定的，对应的裁剪率是通过`--prune_ratios`指定的，跟什么开头应该是没有关系的，没太理解你的意思

**Comment by L-lei** [comment]
错误1：Error: ShapeError: The number of input channels should be equal to filter channels * groups for Op(conv). But received: the input's channels is [256], the shape of input is [-1, 256, -1, -1], the filter's channel is [1], the shape of filter is [203, 1, 3, 3], the groups is [203], the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:256 != filter_dims[1] * groups:203.] at (/paddle/paddle/fluid/operators/conv_op.cc:94)
  [operator < depthwise_conv2d > error]
错误2：
Error: Input(X) dim[1] should be equal to (anchor_mask_number * (5 + class_num)).
  [Hint: Expected dim_x[1] == mask_num * (5 + class_num), but received dim_x[1]:17 != mask_num * (5 + class_num):27.] at (/paddle/paddle/fluid/operators/detection/yolov3_loss_op.cc:55)
  [operator < yolov3_loss > error]

**Comment by L-lei** [comment]
这是我选出来的卷积层参数：conv1_weights,conv2_1_dw_weights,conv2_1_sep_weights,conv2_2_dw_weights,conv2_2_sep_weights,conv3_1_dw_weights,conv3_1_sep_weights,conv3_2_dw_weights,
conv3_2_sep_weights,conv4_1_dw_weights,conv4_1_sep_weights,conv4_2_dw_weights,conv4_2_sep_weights,conv5_1_dw_weights,conv5_1_sep_weights,conv5_2_dw_weights,
conv5_2_sep_weights,conv5_3_dw_weights,conv5_3_sep_weights,conv5_4_dw_weights,conv5_4_sep_weights,conv5_5_dw_weights,conv5_5_sep_weights,conv5_6_dw_weights,
conv5_6_sep_weights,conv6_dw_weights,conv6_sep_weights,yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights,
yolo_block.0.1.1.conv.weights,yolo_block.0.2.conv.weights,yolo_block.0.tip.conv.weights,yolo_output.0.conv.weights,yolo_transition.0.conv.weights,
yolo_block.1.0.0.conv.weights,yolo_block.1.0.1.conv.weights,yolo_block.1.1.0.conv.weights,yolo_block.1.1.1.conv.weights,yolo_block.1.2.conv.weights,
yolo_block.1.tip.conv.weights,yolo_output.1.conv.weights,yolo_transition.1.conv.weights,yolo_block.2.0.0.conv.weights,yolo_block.2.0.1.conv.weights,
yolo_block.2.1.0.conv.weights,yolo_block.2.1.1.conv.weights,yolo_block.2.2.conv.weights,yolo_block.2.tip.conv.weights,yolo_output.2.conv.weights

**Comment by wanghaoshuang** [comment]
在指定待剪裁的卷积参数时，不能直接指定`depthwise_conv2d`的参数。在对其它层卷积剪裁时，会向前将搜索到的`depthwise_conv2d`剪了。

**Comment by L-lei** [comment]
根据您说的我验证了，是这样的。yolo_output开头的参数呢

**Comment by heavengate** [comment]
yolo_output这层卷积是和类别数num_classes相关的，anhcor number * （5 + class numer) 不能裁剪

**Comment by L-lei** [comment]
感谢明白了
