### ISSUE TITLE
deploy/python/infer.py不执行也不报错

### ISSUE THREAD

**Issue by SangerY** [PaddlePaddle/PaddleDetection#1083]
win7+cuda10+cudnn7.6，模型为faster_rcnn_r101_vd_fpn_1x，导出模型预测，执行中断也不报错。
使用如下代码导出模型：
python tools/export_model.py -c configs/faster_rcnn/faster_rcnn_r101_vd_fpn_1x.yml \
        --output_dir=./inference_model \
        -o weights=output/faster_rcnn_r101_vd_fpn_1x/best_model
再使用python deploy/python/infer.py测试视频，结果如下，也不报错，就自动退了。
  Running Arguments 
image_file:
model_dir: models/
output_dir: I:/results/
run_benchmark: False
run_mode: fluid
threshold: 0.3
use_gpu: True
video_file: I:/0001.mp4

  Model Configuration 
Model Arch: RCNN
Use Padddle Executor: False
Transform Order:
--transform op: Normalize
--transform op: Resize
--transform op: Permute
--transform op: PadStride

detect frame:1

将infer_cfg.yml中的use_python_inference改为true后，也是直接跳出来了，不报错。
  Running Arguments 
image_file:
model_dir: models/
output_dir: I:/results/
run_benchmark: False
run_mode: fluid
threshold: 0.3
use_gpu: True
video_file: I:/0001.mp4

  Model Configuration 
Model Arch: RCNN
Use Padddle Executor: True
Transform Order:
--transform op: Normalize
--transform op: Resize
--transform op: Permute
--transform op: PadStride

W0721 14:08:58.003999 19100 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.0, Runtime API Version: 10.0
W0721 14:08:58.016000 19100 device_context.cc:260] device: 0, cuDNN Version: 7.6.

**Comment by jerrywgz** [comment]
请问下deploy/python/infer.py的具体命令是什么呢，model_dir需要指定inference_model所在路径

**Comment by SangerY** [comment]
> 请问下deploy/python/infer.py的具体命令是什么呢，model_dir需要指定inference_model所在路径

models文件夹下就是__model__、__params__、infer_cfg.yml，命令是下面这样
python deploy/python/infer.py --model_dir=models \
                              --video_file="I:/0001.mp4" \
                              --use_gpu=True \
                              --threshold=0.3 \
                              --output_dir="I:/results/"

**Comment by SangerY** [comment]
> 请问下deploy/python/infer.py的具体命令是什么呢，model_dir需要指定inference_model所在路径

电脑重启后，可以跑了，可能是本机环境的问题吧。谢谢了。

**Comment by SangerY** [comment]
@jerrywgz 您好，在export_model中，最后输出的label_list是通过label_list = [str(cat) for cat in catid2name.values()]输出的，虽然background的id是0，但是生成list的时候是background在后面，这样导致在deploy/python/infer.py时，结果框标签错误。是不是要按key值排序下标签？

**Comment by lyf6** [comment]
@SangerY 我也遇到这样的疑惑，是不是应该修改一下才对
