### ISSUE TITLE
关于在配置中添加更多的数据增强方式导致训练错误以及训练卡住的问题

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#110]
使用mask rcnn 模型的resnet50+fpn  训练卡死不动   控制台输出：

> Done (t=0.07s)
creating index...
index created!
{1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6}
{'sky': 1, 'building': 2, 'terrain': 3, 'person': 4, 'vegetation': 5, 'car': 6}
2019-12-12 11:44:38,129-INFO: 139 samples in file /home/aistudio/data/data17467/cococo/annotations/instance_train.json
2019-12-12 11:44:38,131-INFO: places would be ommited when DataLoader is not iterable
I1212 11:44:38.156224  4327 parallel_executor.cc:421] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I1212 11:44:38.196641  4327 graph_pattern_detector.cc:96] ---  detected 28 subgraphs
I1212 11:44:38.215721  4327 graph_pattern_detector.cc:96] ---  detected 25 subgraphs
I1212 11:44:38.257105  4327 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I1212 11:44:38.307612  4327 parallel_executor.cc:285] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I1212 11:44:38.331254  4327 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0

**Comment by shuxsu** [comment]
数据增强部分配置如下：

sample_transforms:
  # Transform the image data to numpy format.
  - !DecodeImage
    to_rgb: true  # default: true
    with_mixup: false  # default: false
  # Flip images randomly
  # Transform the x coordinates of bboxes and segmentations
  - !RandomFlipImage
    is_mask_flip: true  # default: false
    # Whether bbox is normalized
    is_normalized: false  # default: false
    prob: 0.5  # default: 0.5
  # Normalize the image
  - !NormalizeImage
    # The format of image, [H, W, C]/[C, H, W], true by default
    is_channel_first: false
    # Whether divide by 255, true by default
    is_scale: true
    # default: [0.485, 0.456, 0.406]
    mean:
    - 0.485
    - 0.456
    - 0.406
    # default: [1, 1, 1]
    std:
    - 0.229
    - 0.224
    - 0.225
#   - !ExpandImage
#     # max_ratio (float): the ratio of expanding
#     max_ratio: 3
#     # mean (list): the pixel mean
#     mean: [104, 117, 123]
#     # prob (float): the probability of expanding image
#     prob: 0.5
  - !CropImage
    # avoid_no_bbox (bool): whether to to avoid the
    # situation where the box does not appear.
    avoid_no_bbox: false
    # batch_sampler (list): Multiple sets of different parameters for cropping.
    batch_sampler:
    - [1, 1, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0]
    - [1, 50, 0.3, 1.0, 0.5, 2.0, 0.1, 0.0]
    - [1, 50, 0.3, 1.0, 0.5, 2.0, 0.3, 0.0]
    - [1, 50, 0.3, 1.0, 0.5, 2.0, 0.5, 0.0]
    - [1, 50, 0.3, 1.0, 0.5, 2.0, 0.7, 0.0]
    - [1, 50, 0.3, 1.0, 0.5, 2.0, 0.9, 0.0]
    - [1, 50, 0.3, 1.0, 0.5, 2.0, 0.0, 1.0]
    # satisfy_all (bool): whether all boxes must satisfy.
    satisfy_all: false
  # Rescale image to the specified target size, and capped at max_size if max_size != 0.
  # If target_size is list, selected a scale randomly as the specified target size.
  
  # Rescale image to the specified target size, and capped at max_size

  - !ResizeImage
    # Resize method, cv2.INTER_LINEAR(1) by default
    interp: 1
    max_size: 1333
    target_size: 800
    use_cv2: true  # default: true
  # Change the channel
  - !Permute
    # The format of image, [H, W, C]/[C, H, W], true by default
    channel_first: true
    to_bgr: false  # default: true
  # List of batch transformations to use
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  num_workers: 2

**Comment by FDInSky** [comment]
一个iter都没跑通嘛？你可以在reader里面，用print打一下，看看哪个位置出错了

**Comment by shuxsu** [comment]
> 一个iter都没跑通嘛？你可以在reader里面，用print打一下，看看哪个位置出错了

本地可以正常跑通  用ai studio 就不行

**Comment by shuxsu** [comment]
自查解决
