### ISSUE TITLE
How fast in Jetson TX2 using PP-YOLO

### ISSUE THREAD

**Issue by zhucheng725** [PaddlePaddle/PaddleDetection#1100]
How fast in Jetson TX2 using PP-YOLO?
Can anyone tell me how fast deploying in TX2?
Many thanks~!

**Comment by heavengate** [comment]
We are also exploring the PPYOLO-tiny model and PaddleLite-based mobile deployment. Test results will be issued as soon as possible.
In addition, we also provide a series of mobile terminal models to see if they meet your needs.
https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/configs/mobile
