### ISSUE TITLE
PP-YOLO 已开源！！！精度及预测速度优于YOLOv4 ！！！

### ISSUE THREAD

**Issue by heavengate** [PaddlePaddle/PaddleDetection#1103]
**PP-YOLO**

**Paddle 1.8.4版本已发布到pip，可以通过pip安装Paddle 1.8.4版本运行PP-YOLO模型**

[PP-YOLO](https://arxiv.org/abs/2007.12099)已开源，COCO test-dev精度达到45.2%，单卡V100 FP32推理速度达到72.9 FPS，开启TensorRT下FP16推理速度达到155.6FPS, 详细信息见[PP-YOLO模型](https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/configs/ppyolo)

<img src="https://user-images.githubusercontent.com/12605721/88396284-e8393900-cdf4-11ea-81a2-9368b65b4812.png" width="800" />

精度和预测速度如下表

|          模型            | GPU个数 | 每GPU图片个数 |  骨干网络  | 输入尺寸 | Box AP | V100 FP32(FPS) | V100 TensorRT FP16(FPS) | 模型下载 | 配置文件 |
|:------------------------:|:-------:|:-------------:|:----------:| :-------:| :----: | :------------: | :---------------------: | :------: | :------: |
| YOLOv4(AlexyAB)          |    -    |       -       | CSPDarknet |   608    |  43.5  |       62       |          105.5           | [下载链接](https://paddlemodels.bj.bcebos.com/object_detection/yolov4_cspdarknet.pdparams) |  [配置文件](https://github.com/PaddlePaddle/PaddleDetection/tree/master/configs/yolov4/yolov4_csdarknet.yml)                   |
| YOLOv4(AlexyAB)          |    -    |       -       | CSPDarknet |   512    |  43.0  |       83       |          138.4           | [下载链接](https://paddlemodels.bj.bcebos.com/object_detection/yolov4_cspdarknet.pdparams) |  [配置文件](https://github.com/PaddlePaddle/PaddleDetection/tree/master/configs/yolov4/yolov4_csdarknet.yml)                   |
| YOLOv4(AlexyAB)          |    -    |       -       | CSPDarknet |   416    |  41.2  |       96       |          164.0           | [下载链接](https://paddlemodels.bj.bcebos.com/object_detection/yolov4_cspdarknet.pdparams) |  [配置文件](https://github.com/PaddlePaddle/PaddleDetection/tree/master/configs/yolov4/yolov4_csdarknet.yml)                   |
| YOLOv4(AlexyAB)          |    -    |       -       | CSPDarknet |   320    |  38.0  |      123       |          199.0           | [下载链接](https://paddlemodels.bj.bcebos.com/object_detection/yolov4_cspdarknet.pdparams) |  [配置文件](https://github.com/PaddlePaddle/PaddleDetection/tree/master/configs/yolov4/yolov4_csdarknet.yml)                   |
| PP-YOLO                   |    8    |      24       | ResNet50vd |   608    |  45.2  |      72.9      |          155.6          | [下载链接](https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams) |  [配置文件](https://github.com/PaddlePaddle/PaddleDetection/tree/master/configs/ppyolo/ppyolo.yml)                   |
| PP-YOLO                   |    8    |      24       | ResNet50vd |   512    |  44.4  |      89.9      |          188.4          | [下载链接](https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams) |  [配置文件](https://github.com/PaddlePaddle/PaddleDetection/tree/master/configs/ppyolo/ppyolo.yml)                   |
| PP-YOLO                   |    8    |      24       | ResNet50vd |   416    |  42.5  |     109.1      |          215.4          | [下载链接](https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams) |  [配置文件](https://github.com/PaddlePaddle/PaddleDetection/tree/master/configs/ppyolo/ppyolo.yml)                   |
| PP-YOLO                   |    8    |      24       | ResNet50vd |   320    |  39.3  |     132.2      |          242.2          | [下载链接](https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams) |  [配置文件](https://github.com/PaddlePaddle/PaddleDetection/tree/master/configs/ppyolo/ppyolo.yml)                   |

**Comment by hanshumin001** [comment]
赞

**Comment by heavengate** [comment]
PP-YOLO模型的优化项有些涉及了paddle框架的改动，需要安装每日版本，whl包获取地址如下
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev
我们会在8月中旬发布1.8.4版本，1.8.4版本发布之前只能用每日版本了，我们也会尽快跟进新版本paddle whl包的发布。

**Comment by heavengate** [comment]
**PP-YOLO**

PP-YOLO模型文档及配置文件见 [PP-YOLO模型](https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/configs/ppyolo)

想要阅读代码的可以参考下面链接~

PP-YOLO模型backbone为`ResNet50vd-DCN`，代码见 [resnet.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/backbones/resnet.py)
PP-YOLO模型head部分代码见 [yolo_head.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/anchor_heads/yolo_head.py)
PP-YOLO模型loss部分代码见 [yolo_loss.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/losses/yolo_loss.py)

DropBlock 代码见
https://github.com/PaddlePaddle/PaddleDetection/blob/934266ffb21a24ed7aa82cd7e76fa4a12132a337/ppdet/modeling/ops.py#L277

EMA为Paddle框架支持训练方法，见
https://github.com/PaddlePaddle/PaddleDetection/blob/934266ffb21a24ed7aa82cd7e76fa4a12132a337/tools/train.py#L127

IoU Loss 代码见 [iou_loss](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/losses/iou_loss.py)

IoU Aware 代码见 [iou_aware_loss.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/losses/iou_aware_loss.py)和[iou_aware.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/anchor_heads/iou_aware.py)

Grid Sensitive 见 
https://github.com/PaddlePaddle/PaddleDetection/blob/934266ffb21a24ed7aa82cd7e76fa4a12132a337/ppdet/modeling/losses/iou_loss.py#L184

CoordConv 见
https://github.com/PaddlePaddle/PaddleDetection/blob/934266ffb21a24ed7aa82cd7e76fa4a12132a337/ppdet/modeling/anchor_heads/yolo_head.py#L107

SPP 见
https://github.com/PaddlePaddle/PaddleDetection/blob/934266ffb21a24ed7aa82cd7e76fa4a12132a337/ppdet/modeling/anchor_heads/yolo_head.py#L186

**Comment by superkevingit** [comment]
请问默认配置的PP-YOLO需要训练多久呢？我测试的时候发现需要15*4GPU days，是什么地方出错了么？

**Comment by heavengate** [comment]
> 请问默认配置的PP-YOLO需要训练多久呢？我测试的时候发现需要15*4GPU days，是什么地方出错了么？

你的GPU是哪个型号呢，机器上CPU型号和核数是多少呢

**Comment by superkevingit** [comment]
@heavengate 感谢回复！
1. 我的GPU是4*2080Ti/11G，CPU为Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz，16核
由于GPU数量以及显存容量限制问题，我按照[FAQ](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/FAQ.md)调整max_iters, lr, milestones，并把batchsize减小到8
2. 是想在self-design的数据集上做finetune。对于Epoch数这里我有一个疑问，在PaddleDetection里面没有Epoch的概念，那在不同的配置中，snapshot_iter和max_iters差异很大，这个应该怎么调整呢？对于比较小的数据集，大致计算每一个Epoch迭代全量数据的量级这样吗？
3. 对于finetune是直接把pretrain_weights改成对应的模型吗？在训练文件好像没有看到类似mmdetection里面的load_from以及resume_from的选项。

**Comment by heavengate** [comment]
> @heavengate 感谢回复！
> 
> 1. 我的GPU是4*2080Ti/11G，CPU为Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz，16核
>    由于GPU数量以及显存容量限制问题，我按照[FAQ](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/FAQ.md)调整max_iters, lr, milestones，并把batchsize减小到8
> 2. 是想在self-design的数据集上做finetune。对于Epoch数这里我有一个疑问，在PaddleDetection里面没有Epoch的概念，那在不同的配置中，snapshot_iter和max_iters差异很大，这个应该怎么调整呢？对于比较小的数据集，大致计算每一个Epoch迭代全量数据的量级这样吗？
> 3. 对于finetune是直接把pretrain_weights改成对应的模型吗？在训练文件好像没有看到类似mmdetection里面的load_from以及resume_from的选项。

1. 根据你的配置我理解max_iters应该调到了200~300w左右，那么15天可能是正常现象了
2. PaddleDetection没有显式的epoch概念，底层是将reader做成了一个无限循环的迭代器，通过max_iters控制训练结束，如果是小数据集，比如说你的数据集sample数是10000，你是四卡每卡batch_size=8总batch_size=32, 那差不多就是300个iter一个epoch，可以将max_ites设置成300epoch * 300 = 90000(如果数据集很小，比如说只有几千个sample，也可以适当把epoch数调高一些）,至于snapshot_iter只是一个表征多久保存一次checkpoint，其实是一个和epoch无关的概念，根据你的实际需求调整就可以了
3. load pretrain_weights的代码在

**Comment by superkevingit** [comment]
> > @heavengate 感谢回复！
> > 
> > 1. 我的GPU是4*2080Ti/11G，CPU为Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz，16核
> >    由于GPU数量以及显存容量限制问题，我按照[FAQ](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/FAQ.md)调整max_iters, lr, milestones，并把batchsize减小到8
> > 2. 是想在self-design的数据集上做finetune。对于Epoch数这里我有一个疑问，在PaddleDetection里面没有Epoch的概念，那在不同的配置中，snapshot_iter和max_iters差异很大，这个应该怎么调整呢？对于比较小的数据集，大致计算每一个Epoch迭代全量数据的量级这样吗？
> > 3. 对于finetune是直接把pretrain_weights改成对应的模型吗？在训练文件好像没有看到类似mmdetection里面的load_from以及resume_from的选项。
> 
> 1. 根据你的配置我理解max_iters应该调到了200~300w左右，那么15天可能是正常现象了
> 2. PaddleDetection没有显式的epoch概念，底层是将reader做成了一个无限循环的迭代器，通过max_iters控制训练结束，如果是小数据集，比如说你的数据集sample数是10000，你是四卡每卡batch_size=8总batch_size=32, 那差不多就是300个iter一个epoch，可以将max_ites设置成300epoch * 300 = 90000(如果数据集很小，比如说只有几千个sample，也可以适当把epoch数调高一些）,至于snapshot_iter只是一个表征多久保存一次checkpoint，其实是一个和epoch无关的概念，根据你的实际需求调整就可以了。另外对于你是finetune的场景，理论上来说epoch数可以少一些，300 epoch是对于从backbone pretrain开始训练的场景而言的，可以根据你们训练资源和训练时间的需求适当减少。
> 3. load pretrain_weights的代码在
>    https://github.com/PaddlePaddle/PaddleDetection/blob/c2bf0803946eec511f752fad2573a3e1f345ce32/tools/train.py#L195

感谢回复！我在[PaddleDetection文档](https://paddledetection.readthedocs.io/tutorials/Custom_DataSet.html#id6)里也找到了一些描述～

**Comment by superkevingit** [comment]
你好，请问多尺度测试的配置方式修改了吗？我在PP-YOLO的配置中按照 #1110 的方式配置，在infer时出现
`TypeError: build_inputs() got an unexpected keyword argument 'multi_scale'`

**Comment by heavengate** [comment]
> 你好，请问多尺度测试的配置方式修改了吗？我在PP-YOLO的配置中按照 #1110 的方式配置，在infer时出现
> `TypeError: build_inputs() got an unexpected keyword argument 'multi_scale'`

你好，目前PaddleDetection里面的multi_scale测试只有RCNN系列的模型支持，YOLO系列模型还不支持多尺度测试，PPYOLO的测试也都是单尺度测试的，多尺度测试的需求我们再调研评估下~

**Comment by superkevingit** [comment]
好的，那如果想自己添加TTA的话，我发现infer中图片的接入方式都是传递一个地址，而TTA一般在Tensor级别做的。
我看 #48 里面提到使用传入numpy的方式，这个传入的是原始图像还是经过transform的呢？
除此之外，还有什么好的方式可以自定义TTA吗？

**Comment by y0un5** [comment]
@heavengate
Did you use `configs/ppyolo/ppyolo.yml`  for training PP-YOLO paper model?

I think settings in `configs/ppyolo/ppyolo.yml` are different from hyper parameters shown on the paper. 
Could you explain about this?

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/ppyolo/ppyolo.yml

```yaml
...
max_iters: 500000
...
LearningRate:
  base_lr: 0.00333
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 400000
    - 450000
  - !LinearWarmup
    start_factor: 0.
    steps: 4000
...
```


In PP-YOLO paper

> Under larger batch size setting, the entire detection network is trained with stochastic gradient descent
(SGD) for 25K iterations with the initial learning rate being 0.01 and a minibatch of 192 images distributed on 8 GPUs.
The learning rate is divided by 10 at iteration 15K and 20K, respectively. Weight decay is set as 0.0005, and momentum
is set as 0.9. Multi-scale training from 320 to 608 pixels is applied. MixUp[43] is adopted for data augmentation.

* 25K iterations (different from `max_iters: 500000`)
* initial learning rate being 0.01 (different from `base_lr: 0.00333`)
* learning rate is divided by 10 at iteration 15K and 20K (different from `milestones: 400000, 450000`)

**Comment by heavengate** [comment]
> @heavengate
> Did you use `configs/ppyolo/ppyolo.yml` for training PP-YOLO paper model?
> 
> I think settings in `configs/ppyolo/ppyolo.yml` are different from hyper parameters shown on the paper.
> Could you explain about this?
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/ppyolo/ppyolo.yml
> 
> ```yaml
> ...
> max_iters: 500000
> ...
> LearningRate:
>   base_lr: 0.00333
>   schedulers:
>   - !PiecewiseDecay
>     gamma: 0.1
>     milestones:
>     - 400000
>     - 450000
>   - !LinearWarmup
>     start_factor: 0.
>     steps: 4000
> ...
> ```
> 
> In PP-YOLO paper
> 
> > Under larger batch size setting, the entire detection network is trained with stochastic gradient descent
> > (SGD) for 25K iterations with the initial learning rate being 0.01 and a minibatch of 192 images distributed on 8 GPUs.
> > The learning rate is divided by 10 at iteration 15K and 20K, respectively. Weight decay is set as 0.0005, and momentum
> > is set as 0.9. Multi-scale training from 320 to 608 pixels is applied. MixUp[43] is adopted for data augmentation.
> 
> * 25K iterations (different from `max_iters: 500000`)
> * initial learning rate being 0.01 (different from `base_lr: 0.00333`)
> * learning rate is divided by 10 at iteration 15K and 20K (different from `milestones: 400000, 450000`)

Sorry for that we pushed the wrong version, thank you for reminding, it has been modified by https://github.com/PaddlePaddle/PaddleDetection/pull/1139， please pull the branch again~

**Comment by y0un5** [comment]
@heavengate
Thanks for your quick response! Could you fix typos in the PP-YOLO paper later, please?
* 25K => 250K
* 15K and 20K => 150K and 200K

**Comment by heavengate** [comment]
> @heavengate
> Thanks for your quick response! Could you fix typos in the PP-YOLO paper later, please?
> 
> * 25K => 250K
> * 15K and 20K => 150K and 200K

Thank you for reminding, it will be fixed as soon as possible~

**Comment by atomrun39** [comment]
请问除了下载日常版获取地址“多版本whl包列表-dev”这个里面的whl，还需要下载什么吗？训练出现了这个错是什么问题呀？
----------------------
Error Message Summary:
----------------------
Error: op slice does not have kernel for data_type[float]:data_layout[ANY_LAYOUT]:place[CUDAPinnedPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1090)
  [operator < slice > error]

**Comment by atomrun39** [comment]
请问除了下载日常版获取地址“多版本whl包列表-dev”这个里面的whl，还需要下载什么吗？训练出现了这个错是什么问题呀？
----------------------
Error Message Summary:
----------------------
Error: op slice does not have kernel for data_type[float]:data_layout[ANY_LAYOUT]:place[CUDAPinnedPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1090)
  [operator < slice > error]

**Comment by tianyuluan** [comment]
> ## 请问除了下载日常版获取地址“多版本whl包列表-dev”这个里面的whl，还需要下载什么吗？训练出现了这个错是什么问题呀？
> ## Error Message Summary:
> Error: op slice does not have kernel for data_type[float]:data_layout[ANY_LAYOUT]:place[CUDAPinnedPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1090)
> [operator < slice > error]

同问

**Comment by heavengate** [comment]
> ## 请问除了下载日常版获取地址“多版本whl包列表-dev”这个里面的whl，还需要下载什么吗？训练出现了这个错是什么问题呀？
> ## Error Message Summary:
> Error: op slice does not have kernel for data_type[float]:data_layout[ANY_LAYOUT]:place[CUDAPinnedPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1090)
> [operator < slice > error]

最近Paddle每日版本有修改，可以参考这个PR先规避一下，每日版本问题我们再跟进~ https://github.com/PaddlePaddle/PaddleDetection/pull/1176

**Comment by heavengate** [comment]
> > ## 请问除了下载日常版获取地址“多版本whl包列表-dev”这个里面的whl，还需要下载什么吗？训练出现了这个错是什么问题呀？
> > ## Error Message Summary:
> > Error: op slice does not have kernel for data_type[float]:data_layout[ANY_LAYOUT]:place[CUDAPinnedPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1090)
> > [operator < slice > error]
> 
> 同问

最近Paddle每日版本有修改，可以参考这个PR先规避一下，每日版本问题我们再跟进~ https://github.com/PaddlePaddle/PaddleDetection/pull/1176

**Comment by Jay9z** [comment]
为什么我在AIStudio上的FPS最高只有14，单卡推理608*608的彩色图像的极限是多少FPS？

**Comment by heavengate** [comment]
> 为什么我在AIStudio上的FPS最高只有14，单卡推理608*608的彩色图像的极限是多少FPS？

FPS测试需要将模型导出，以预测引擎部署的方式测试，跟服务器预测部署一个流程，可以参考README里的测试方法
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/ppyolo/README_cn.md#4-推理部署与benchmark

**Comment by biao321** [comment]
预测batch size设置为1可以正常预测，大于1出现报错：

 File "tools/infer.py", line 278, in <module>
    main()
  File "tools/infer.py", line 178, in main
    return_numpy=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1106, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1236, in _run_impl
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1326, in _run_program
    [fetch_var_name])
ValueError: In user code:

    File "tools/infer.py", line 278, in <module>
      main()
    File "tools/infer.py", line 120, in main
      test_fetches = model.test(feed_vars)
    File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 165, in test
      return self.build(feed_vars, mode='test', exclude_nms=exclude_nms)
    File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 93, in build
      body_feats, im_size, exclude_nms=exclude_nms)
    File "/home/aistudio/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 431, in get_prediction
      outputs = self._get_outputs(input, is_train=False)
    File "/home/aistudio/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 357, in _get_outputs
      name=self.prefix_name + "yolo_block.{}".format(i))
    File "/home/aistudio/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 235, in _detection_block
      conv = self._add_coord(conv, is_test=is_test)
    File "/home/aistudio/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 158, in _add_coord
      return fluid.layers.concat([input, x_range, y_range], axis=1)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/tensor.py", line 348, in concat
      type='concat', inputs=inputs, outputs={'Out': [out]}, attrs=attrs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2846, in append_op
      attrs=kwargs.get("attrs", None))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1931, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The 0-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [16, 2048, 19, 19], input[1]'s shape = [1, 1, 19, 19].
      [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:16 != inputs_dims[i][j]:1.] (at /paddle/paddle/fluid/operators/concat_op.h:63)
      [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
      [operator < concat > error]
terminate called without an active exception

**Comment by wanghaisheng** [comment]
>如何准备训练数据
如果是yolo格式的训练数据，如何加载到咱们这个上面进行训练

**Comment by jetteezhou** [comment]
> 
it is helpful
