### ISSUE TITLE
请问在paddledetection里用slim/train.py训练得到的量化后模型参数，怎么查看呢？？

### ISSUE THREAD

**Issue by nuaaceieyty** [PaddlePaddle/PaddleDetection#1104]
请问在paddledetection里用slim/train.py训练得到的量化后模型参数，怎么查看显示呢？？

**Comment by heavengate** [comment]
是需要查看什么呢，是指查看权重的具体数值么，可以通过权重的name通过`train_prog.global_block().var(var_name)`获取这个权重查看，也可以将权重名加到`exe.run`的`fetch_list`参数里面fetch出来查看
https://github.com/PaddlePaddle/PaddleDetection/blob/934266ffb21a24ed7aa82cd7e76fa4a12132a337/slim/quantization/train.py#L241
