### ISSUE TITLE
win10+cuda10+python3.6  test infer single image error

### ISSUE THREAD

**Issue by wangzhiming68** [PaddlePaddle/PaddleDetection#1105]
Error Message Summary:
----------------------
InvalidArgumentError: The 0-th dimension of input[0] and input[2] is expected to be equal.But received input[0]'s shape = [-1, 2048, 19, 19], input[2]'s shape = [1, 1, 19, 19].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:-1 != inputs_dims[i][j]:1.] at (D:\1.8.3\paddle\paddle/fluid/operators/concat_op.h:63)
  [operator < concat > error]

**Comment by still-wait** [comment]
@wangzhiming68 Which model is it and what is the running command?

**Comment by wangzhiming68** [comment]
ppyolo.pdparams( 512*512)
python3 tools/infer.py -c configs/ppyolo/ppyolo.yml -o weights=model/ppyolo.pdparams --infer_img=demo/000000014439_640x640.jpg
I had already downloaded model weights to 'model' directory

**Comment by heavengate** [comment]
您好，请问你使用的paddle是哪个版本，ppyolo的优化项有些设计了paddle框架的改动，需要安装每日版本，whl包获取地址如下
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev
我们会在8月中旬发布1.8.4版本，1.8.4版本发布之前只能用每日版本了，我们也会尽快跟进新版本paddle whl包的发布

**Comment by heavengate** [comment]
您好，刚确认了下每日版本暂时没有提供windows的，等周一我跟进一下先提供几个windows上每日版本的whl包

**Comment by heavengate** [comment]
您好，windows上的whl包我们再跟进，如果你现在想在windows上尝试的话，可以安装paddle 2.0.0a的版本，并将`configs/ppyolo/ppyolo.yml`中的`YOLOv3Head`段修改如下
```

```

**Comment by qingqing01** [comment]
1.8.4已经发布，可以使用新的版本，关闭此issue。
