### ISSUE TITLE
paddle serving 部署显存问题

### ISSUE THREAD

**Issue by weiaoliu** [PaddlePaddle/PaddleDetection#1106]
paddleDetection转serving部署运行测试文件，显存会增加，直到爆，请问这是什么情况

**Comment by still-wait** [comment]
@weiaoliu 请问是哪个模型，运行指令是什么？

**Comment by weiaoliu** [comment]
obj365下面的cascade_rcnn_cls那个模型，加下微信吧，18663258575




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Guanghua Yu"<notifications@github.com&gt;; 
发送时间: 2020年7月25日(星期六) 下午2:42
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 
抄送: "° 残酷っ"<2556010125@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] paddle serving 部署显存问题 (#1106)





 
@weiaoliu 请问是哪个模型，运行指令是什么？

**Comment by weiaoliu** [comment]
GLOG_v=2 python3 -m paddle_serving_server_gpu.serve --model /home/irecog/PaddleDetection/inference_model/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms/serving_client --port 8050 --gpu_ids 1 --mem_optim True&nbsp; 这是启动serving端的密令，在调用接口的时候，GPU的显存一直在增加，每运行一次，显存就增加




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Guanghua Yu"<notifications@github.com&gt;; 
发送时间: 2020年7月25日(星期六) 下午2:42
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 
抄送: "° 残酷っ"<2556010125@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] paddle serving 部署显存问题 (#1106)





 
@weiaoliu 请问是哪个模型，运行指令是什么？

**Comment by still-wait** [comment]
@weiaoliu 好的，我们排查下问题。

**Comment by weiaoliu** [comment]
好的👌
---原始邮件---
发件人:&quot;Guanghua Yu&quot;<notifications@github.com&gt;
发送时间:2020年7月25日 星期六 下午5:35
收件人:&quot;PaddlePaddle/PaddleDetection&quot;<PaddleDetection@noreply.github.com&gt;
抄送:&quot;weiaoliu&quot;<2556010125@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;
主题:Re: [PaddlePaddle/PaddleDetection] paddle serving 部署显存问题 (#1106)



@weiaoliu好的，我们排查下问题。

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;were&nbsp;mentioned.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by weiaoliu** [comment]
现在是重启后没问题，但是过段时间显存就会被撑爆

**Comment by wangjiawei04** [comment]
> obj365下面的cascade_rcnn_cls那个模型，加下微信吧，18663258575
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Guanghua Yu"<notifications@github.com&gt;; 发送时间: 2020年7月25日(星期六) 下午2:42 收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 抄送: "° 残酷っ"<2556010125@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [PaddlePaddle/PaddleDetection] paddle serving 部署显存问题 (#1106) @weiaoliu 请问是哪个模型，运行指令是什么？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

我是Serving的同学 我加下你
