### ISSUE TITLE
用mask_rcnn_r50_fpn_1x训练自己的数据集出错

### ISSUE THREAD

**Issue by zwf1234** [PaddlePaddle/PaddleDetection#1109]
用mask_rcnn_r50_fpn_1x训练自己的数据集出现以下错误：
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/readerocking_queue.h:141)
  [operator < read > error]

**Comment by still-wait** [comment]
@zwf1234 请问您自己数据集的格式是COCO格式吗？

**Comment by zwf1234** [comment]
VOC格式的

**Comment by still-wait** [comment]
@zwf1234 VOC数据格式不支持读取mask信息，如果只训练检测网络，请换faster-rcnn或者其他检测模型，如果要训练实例分割模型，请将数据集格式定义为COCO格式，并携带mask信息。

**Comment by zwf1234** [comment]
将数据集定义为COCO格式了，但是一直卡在下面这个地方：
Done (t=0.95s)
creating index...
index created!
2020-07-26 17:27:08,185-INFO: places would be ommited when DataLoader is not iterable
