### ISSUE TITLE
关于 Test Time Augmentation

### ISSUE THREAD

**Issue by linyangsdu** [PaddlePaddle/PaddleDetection#1110]
我想在config文件中配置 TTA，但是发现没有一个模板的config文件来查看，我添加了 
1.MultiScaleTEST:
  score_thresh: 0.05
  nms_thresh: 0.5
  detections_per_im: 100
  enable_voting: true
  vote_thresh: 0.9
2. EvalReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
    multi_scale: true
    num_scales: 8
    use_flip: true
3. MultiscaleTestResize
4. PadMultiScaleTest
是否需要添加别的后续处理？

**Comment by linyangsdu** [comment]
我的网络结构是 CascadeCARCNN

**Comment by still-wait** [comment]
@linyangsdu 您的配置是正确的，具体可参考[cascade_rcnn_cls_aware_r101_vd_fpn_ms_test.yml](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/cascade_rcnn_cls_aware_r101_vd_fpn_ms_test.yml)

**Comment by linyangsdu** [comment]
好的，谢谢
