### ISSUE TITLE
关于PP-YOLO的FPN实现

### ISSUE THREAD

**Issue by choodly** [PaddlePaddle/PaddleDetection#1113]
请教一下，0.4版本的PP-YOLO的FPN相关源码更新了吗？和arXiv上PP-YOLO论文对应的实现，目前没找到呢

**Comment by heavengate** [comment]
你好，PP-YOLO模型和配置文件已经开源，可见https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/configs/ppyolo

FPN实际上是YOLO head其中的部分，代码见
https://github.com/PaddlePaddle/PaddleDetection/blob/934266ffb21a24ed7aa82cd7e76fa4a12132a337/ppdet/modeling/anchor_heads/yolo_head.py#L313

此函数中`for i, block in enumerate(blocks):`即为FPN的三个分支，`_detection_block`即为图中红框表示内容
![yolo_fpn](https://user-images.githubusercontent.com/12605721/88499707-4171ba00-cff9-11ea-9545-189feba4fd16.png)
