### ISSUE TITLE
关于 generate_proposal 的问题

### ISSUE THREAD

**Issue by linyangsdu** [PaddlePaddle/PaddleDetection#1114]
我想知道你们在 generate_proposal 操作中的排序算法用的是什么算法，和 pytorch 里面的sort(descending=True)有什么区别？我发现我在 pytorch里面实现的地方，在 generate_proposal会产生少量不同的框，最后导致 mAP 结果差了3个点

**Comment by linyangsdu** [comment]
我想找出具体的问题所在，如果我想查看 fluid.layer.generate_proposal 这个层的中间输出，我应该怎么做

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/generate_proposals_op.cu#L289

generate proposals 的核心逻辑在这里可以参考，主要步骤为：1. 对score进行排序，排序方法为cub::DeviceRadixSort::SortPairsDescending，并取前pre_nms_num个score  2. 对这pre_nms_num个box进行解码并clip到原图范围内 3. 过滤掉clip后长度小于min_size的bbox 3. 对剩余的bbox再做nms，并取前post_nms_top_n个bbox作为op的输出

**Comment by linyangsdu** [comment]
好，我自己已经做了这些步骤了，想把 305行的scores_sort 返回回来，但是发现直接return std::make_pair(scores_sort, scores_sort); 得到的是一个 (1,6)的Tensor,怎么把这个Tensor全部返回回来呢

**Comment by linyangsdu** [comment]
这个代码的结果和test_generate_proposals_op.py这个的结果是一致的吗

**Comment by linyangsdu** [comment]
返回结果已经搞定了，是我代码问题，抱歉

**Comment by linyangsdu** [comment]
问题找到了，我在 test_generate_proposal.py里面一步一步调试，发现是 clip 的时候出的问题，问题解决，issue close
