### ISSUE TITLE
关于 Test 和 Eval 时候的batch size 对结果的影响

### ISSUE THREAD

**Issue by linyangsdu** [PaddlePaddle/PaddleDetection#1118]
我用同一个模型在不同 batch_size (1 和 3) 跑出来的结果，发现3的时候 mAP会高 0.1%,为什么会出现这种现象？

**Comment by jerrywgz** [comment]
如果测试数据不能被3整除的话，剩余数据会被舍弃掉，可能会产生0.1%的差距

**Comment by linyangsdu** [comment]
因为我的数据刚好是3w张，所以应该不会有这个问题吧...我是 bs = 3张 * 4 gpu = 12 张，总共2500个iter...

**Comment by qingqing01** [comment]
@linyangsdu 请问具体是那个模型，我们也验证下。

**Comment by linyangsdu** [comment]
是 Cascade R200vd 那个模型，我在 Obj365的val上跑的

**Comment by qingqing01** [comment]
@linyangsdu  是这样的，模型是FPN， 输入图片会做padding到定长，不同的组batch，不同图片padding的大小可能不同，这个也会引起结果的一些小差异。
