### ISSUE TITLE
自定义数据集如何重新训练所有参数？

### ISSUE THREAD

**Issue by lvweiwolf** [PaddlePaddle/PaddleDetection#1119]
我选用yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.yml, 但我不想使用预训练模型做迁移训练，我想直接训练所有参数，应该怎么调整？

[yolov3_enhance_reader.txt](https://github.com/PaddlePaddle/PaddleDetection/files/4986566/yolov3_enhance_reader.txt)
[yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.txt](https://github.com/PaddlePaddle/PaddleDetection/files/4986567/yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.txt)

**Comment by qingqing01** [comment]
@lvweiwolf   你默认的配置就是打开所有参数训练的。也就是 lr不等于0，backbone里也不设置`freeze_at`的话，默认是打开所有参数训练的。
