### ISSUE TITLE
Cutmix epoch number

### ISSUE THREAD

**Issue by superkevingit** [PaddlePaddle/PaddleDetection#1123]
https://github.com/PaddlePaddle/PaddleDetection/blob/8551de92b9c5bd355f1981dc984850fd69caab39/configs/anchor_free/fcos_dcn_r50_fpn_1x_cutmix.yml#L120

请问这里cutmix的epoch数设置为10，是指的最开始的10次iter的意思吗？

**Comment by willthefrog** [comment]
是10个epoch. 即数据集迭代10次。

**Comment by superkevingit** [comment]
原来是这样！Paddle里面不是没有显示设置epoch概念吗？那么后台是怎么根据iter转换到epoch的，是会统计数据集样本数以及batchsize吗？
另外，mixup_epoch的使用方法不是和这个对齐的吗，后面接的是iter数量吗？

**Comment by willthefrog** [comment]
应该就是样本数/batch_size，嗯，看了下是不一致，`mixup_epoch`应该转换下epoch，或者改成`mixup_step`

**Comment by superkevingit** [comment]
> 应该就是样本数/batch_size，嗯，看了下是不一致，`mixup_epoch`应该转换下epoch，或者改成`mixup_step`，这个问题后面我们会跟进下。

好的，感谢回复～
