### ISSUE TITLE
问题咨询：yolov3训练anchors size 设置的问题

### ISSUE THREAD

**Issue by linghaolu** [PaddlePaddle/PaddleDetection#1125]
你好，想咨询一下一个疑问
yolov3 训练的时候采用多输入尺寸进行训练 sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
但是 anchors 只设置了一个尺寸
anchors: [[10, 13], [16, 30], [33, 23],
[30, 61], [62, 45], [59, 119],
[116, 90], [156, 198], [373, 326]]

这个 anchros的size 跟图片输入尺寸是什么对应关系，我看这个默认size是对应416这个输入的？ 会对其他输入尺寸进行缩放么？

**Comment by willthefrog** [comment]
默认值是根据原文来的，应该是coco上做了k-means统计出来的，看实现代码是没有缩放的。anchor作为regression starting point来说，绝对数值本身可能也没那么大的影响，模型是可以学出对应关系的。
