### ISSUE TITLE
模型转换

### ISSUE THREAD

**Issue by AN-ZE** [PaddlePaddle/PaddleDetection#1126]
请问模型转换为其它框架模型(caffe/TF)，需要怎么进行转换，是否有相应示例

**Comment by willthefrog** [comment]
可以尝试使用[paddle2onnx](https://github.com/PaddlePaddle/paddle2onnx) 进行转换，也可以自己手动转换，`.pdparams`文件实际就是一个pickle文件，可以使用pickle读取得到一个dict [str -> numpy]，然后可以根据需要转换为其他框架格式。
