### ISSUE TITLE
关于 OVIDV5 报告中提到的模型

### ISSUE THREAD

**Issue by linyangsdu** [PaddlePaddle/PaddleDetection#1127]
我想知道有没有其他模型相关配置文件，我只看到了 Res200-vd 和 SE154-dcnv2,有没有 ResNext101 32x16d以及其他效果比较好的模型的config或者预训练模型呢

**Comment by qingqing01** [comment]
@linyangsdu  目前在OpenImage数据集只有这些模型。 你是想要OpenImage上ResNeXt101等预训练模型吗？

**Comment by linyangsdu** [comment]
其实我是想要他们在 objects365上的预训练模型...因为预训练模型太少了，只有 se154 和 res200vd两个 ，所以做 model ensemble 不太好做

**Comment by qingqing01** [comment]
@linyangsdu 感谢反馈，目前基于objects365的预训练确实还不是很多，我们后续会增加一些。

**Comment by linyangsdu** [comment]
如果能很快 post 出来 另外模型的配置文件也是可以的
