### ISSUE TITLE
voc 的数据集目录到底怎样设置，试了好久都不对 AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by vxgu86** [PaddlePaddle/PaddleDetection#1132]
python -u tools/train.py -c configs/yolov3_darknet_voc.yml                         --use_vdl=True                         --vdl_log_dir=vdl_dir/scalar                         --eval
/opt/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, defaultdict
2020-07-31 14:16:13,051-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
Traceback (most recent call last):
  File "tools/train.py", line 368, in <module>
    main()
  File "tools/train.py", line 145, in main
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
  File "/home/vxgu/PaddleDetection-release-0.3/ppdet/data/reader.py", line 410, in create_reader
    reader = Reader(**cfg)()
  File "/home/vxgu/PaddleDetection-release-0.3/ppdet/data/reader.py", line 204, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/home/vxgu/PaddleDetection-release-0.3/ppdet/data/source/dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "/home/vxgu/PaddleDetection-release-0.3/ppdet/data/source/voc.py", line 143, in load_roidb_and_cname2cid
    _difficult = int(obj.find('difficult').text)
AttributeError: 'NoneType' object has no attribute 'text'

architecture: YOLOv3
use_gpu: true
max_iters: 70000
log_smooth_window: 20
save_dir: output
snapshot_iter: 2000
metric: VOC
map_type: 11point
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/DarkNet53_pretrained.tar
weights: output/yolov3_darknet_voc/model_final
num_classes: 7
finetune_exclude_pretrained_params: ['yolo_output']
use_fine_grained_loss: false

YOLOv3:
  backbone: DarkNet
  yolo_head: YOLOv3Head

DarkNet:
  norm_type: sync_bn
  norm_decay: 0.
  depth: 53

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

YOLOv3Loss:
  # batch_size here is only used for fine grained loss, not used
  # for training batch_size setting, training batch_size setting
  # is in configs/yolov3_reader.yml TrainReader.batch_size, batch
  # size here should be set as same value as TrainReader.batch_size
  batch_size: 8
  ignore_thresh: 0.7
  label_smooth: false

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 55000
    - 62000
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'yolov3_reader.yml'
TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc/
    anno_path: trainval.txt
    use_default_label: false
    with_background: false

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc/
    anno_path: test.txt
    use_default_label: false
    with_background: false

TestReader:
  dataset:
    !ImageFolder
    use_default_label: false
    with_background: false

**Comment by heavengate** [comment]
你好，你是用的自定义的数据集么，看报错信息是数据集里找不到difficult字段，可以检查一下annotation里diffcult字段是否缺失
```
File "/home/vxgu/PaddleDetection-release-0.3/ppdet/data/source/voc.py", line 143, in load_roidb_and_cname2cid
_difficult = int(obj.find('difficult').text)
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by vxgu86** [comment]
谢谢 终于调到能运行，但是卡在这里就不动了。能不能帮忙看下怎么回事。
@heavengate 
~/PaddleDetection-release-0.3$ python -u tools/train.py -c configs/yolov3_darknet_voc.yml                         --use_vdl=True                         --vdl_log_dir=vdl_dir/scalar                         --eval
/opt/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, defaultdict
2020-07-31 16:28:48,392-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
2020-07-31 16:28:49,426-INFO: places would be ommited when DataLoader is not iterable
W0731 16:28:49.465682 23381 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 10.0
W0731 16:28:49.469887 23381 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2020-07-31 16:28:52,401-INFO: Downloading DarkNet53_pretrained.tar from https://paddle-imagenet-models-name.bj.bcebos.com/DarkNet53_pretrained.tar
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 158940/158940 [00:51<00:00, 3095.24KB/s]
2020-07-31 16:29:44,462-INFO: Decompressing /home/vxgu/.cache/paddle/weights/DarkNet53_pretrained.tar...
2020-07-31 16:29:44,740-WARNING: /home/vxgu/.cache/paddle/weights/DarkNet53_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-07-31 16:29:49,258-INFO: places would be ommited when DataLoader is not iterable
I0731 16:29:52.420028 23381 build_strategy.cc:361] set enable_sequential_execution:1
W0731 16:29:52.622957 23381 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 222. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 5.

**Comment by vxgu86** [comment]
GPU占用为0  没开始训练

**Comment by heavengate** [comment]
> 谢谢 终于调到能运行，但是卡在这里就不动了。能不能帮忙看下怎么回事。
> @heavengate
> ~/PaddleDetection-release-0.3$ python -u tools/train.py -c configs/yolov3_darknet_voc.yml --use_vdl=True --vdl_log_dir=vdl_dir/scalar --eval
> /opt/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
> from collections import Mapping, defaultdict
> 2020-07-31 16:28:48,392-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
> 2020-07-31 16:28:49,426-INFO: places would be ommited when DataLoader is not iterable
> W0731 16:28:49.465682 23381 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 10.0
> W0731 16:28:49.469887 23381 device_context.cc:260] device: 0, cuDNN Version: 7.6.
> 2020-07-31 16:28:52,401-INFO: Downloading DarkNet53_pretrained.tar from https://paddle-imagenet-models-name.bj.bcebos.com/DarkNet53_pretrained.tar
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 158940/158940 [00:51<00:00, 3095.24KB/s]
> 2020-07-31 16:29:44,462-INFO: Decompressing /home/vxgu/.cache/paddle/weights/DarkNet53_pretrained.tar...
> 2020-07-31 16:29:44,740-WARNING: /home/vxgu/.cache/paddle/weights/DarkNet53_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
> 2020-07-31 16:29:49,258-INFO: places would be ommited when DataLoader is not iterable
> I0731 16:29:52.420028 23381 build_strategy.cc:361] set enable_sequential_execution:1
> W0731 16:29:52.622957 23381 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 222. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 5.

数据集多大，几卡batch size多少训练的

**Comment by vxgu86** [comment]
数据集不大，我用100张测试的。
单卡，config如下
谢谢
@heavengate 
architecture: YOLOv3
use_gpu: true
max_iters: 70000
log_smooth_window: 20
save_dir: output
snapshot_iter: 2000
metric: VOC
map_type: 11point
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/DarkNet53_pretrained.tar
weights: output/yolov3_darknet_voc/model_final
num_classes: 7
finetune_exclude_pretrained_params: ['yolo_output']
use_fine_grained_loss: false

YOLOv3:
  backbone: DarkNet
  yolo_head: YOLOv3Head

DarkNet:
  norm_type: sync_bn
  norm_decay: 0.
  depth: 53

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

YOLOv3Loss:
  # batch_size here is only used for fine grained loss, not used
  # for training batch_size setting, training batch_size setting
  # is in configs/yolov3_reader.yml TrainReader.batch_size, batch
  # size here should be set as same value as TrainReader.batch_size
  batch_size: 8
  ignore_thresh: 0.7
  label_smooth: false

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 55000
    - 62000
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'yolov3_reader.yml'
TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc/
    anno_path: trainval.txt
    use_default_label: false
    with_background: false

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc/
    anno_path: test.txt
    use_default_label: false
    with_background: false

TestReader:
  dataset:
    !ImageFolder
    use_default_label: false
    with_background: false

**Comment by heavengate** [comment]
什么操作系统呢，可以把`configs/yolov3_reader.yml`里`worker_num`设小一点，或者`use_process: false`
https://github.com/PaddlePaddle/PaddleDetection/blob/911651ebd591184c8fb25c40ac6b9c6518613628/configs/yolov3_reader.yml#L53

**Comment by vxgu86** [comment]
改成4 ok
谢谢

**Comment by sukkyusun1** [comment]
> Thank you for finally adjusting it to run, but the card is stuck here and it doesn't move. Can you help me see what's going on.
> @heavengate
> ~/PaddleDetection-release-0.3$ python -u tools/train.py -c configs/yolov3_darknet_voc.yml --use_vdl=True --vdl_log_dir=vdl_dir/scalar --eval
> /opt/anaconda3/lib/python3.7 /site-packages/sklearn/feature_extraction/text.py:17: DeprecationWarning: Using or importing the ABCs from'collections' instead of from'collections.abc' is deprecated, and in 3.8 it will stop working
> from collections import Mapping, defaultdict
> 2020-07-31 16:28:48,392-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
> 2020-07-31 16:28:49,426-INFO: places would be ommited when DataLoader is not iterable
> W0731 16:28:49.465682 23381 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 10.0
> W0731 16:28:49.469887 23381 device_context.cc:260] device: 0, cuDNN Version: 7.6.
> 2020-07-31 16:28:52,401-INFO: Downloading DarkNet53_pretrained.tar from https://paddle-imagenet-models-name.bj.bcebos.com/DarkNet53_pretrained.tar
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 158940/158940 [00:51<00:00, 3095.24KB/s]
> 2020-07-31 16:29:44,462-INFO: Decompressing /home/vxgu/.cache/paddle/weights/DarkNet53_pretrained.tar...
> 2020-07-31 16:29:44,740-WARNING: /home/vxgu/.cache/paddle/weights/DarkNet53_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
> 2020-07-31 16:29:49,258-INFO: places would be ommited when DataLoader is not iterable
> I0731 16:29:52.420028 23381 build_strategy.cc:361] set enable_sequential_execution:1
> W0731 16:29:52.622957 23381 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 222. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 5.

File "/home/vxgu/PaddleDetection-release-0.3/ppdet/data/source/voc.py", line 143, in load_roidb_and_cname2cid
_difficult = int(obj.find('difficult').text)
AttributeError: 'NoneType' object has no attribute 'text'

same problem here
AttributeError: 'NoneType' object has no attribute 'text'
how did you solve this problem..

**Comment by wangbo-git** [comment]
请问您训练好模型后 测试图片时 能标出框框嘛？ 我最终的map是74.2% 但就是识别不出来类别

**Comment by wangbo-git** [comment]
配置文件跟您的类似 只是类别数不同 识别图片时 图片上没有框框

**Comment by qingqing01** [comment]
@wangbo-git  请问问题是否已经解决，如果还没解决，可以提新的issue。
