### ISSUE TITLE
有没有C++调用的接口？

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleDetection#1135]
我先在windows下面，使用C++调用，执行exe或者封装成dll，调用pp-yolo4。有没有C++的接口可以调用？

**Comment by heavengate** [comment]
你好，c++上预测不是的话需要先将模型导出，命令如下
```
python tools/export_model.py -c configs/ppyolo/ppyolo.yml -o weights=<path/to/weigts> --output=<output/dir>
```

然后参考我们提供好的c++部署方法集成到你需要的工程里去
https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/deploy/cpp
