### ISSUE TITLE
关于 ResNext101 32x16d wsl-FPN-Dcnv2

### ISSUE THREAD

**Issue by linyangsdu** [PaddlePaddle/PaddleDetection#1137]
我在 OIDV5 里面看到了这个模型，可以知道具体的技术细节吗

**Comment by littletomatodonkey** [comment]
你好，x101 32x16的模型指标可以参考这里：https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/zh_CN/models/EfficientNet_and_ResNeXt101_wsl.md
模型结构可以参考分类库中的实现：https://github.com/PaddlePaddle/PaddleClas/blob/master/ppcls/modeling/architectures/resnext101_wsl.py
和resnet一样，我们也是将C2~C5引出来，作为feature map，再接FPN以及dcnV2模块进行检测训练的

![image](https://user-images.githubusercontent.com/14270174/89036968-4a9fb580-d370-11ea-8a57-9ab361b10570.png)

**Comment by linyangsdu** [comment]
好的，谢谢~

**Comment by linyangsdu** [comment]
额，关于这个还有个问题，我想知道主体的 arch 是 faster-rcnn吗？就是 fpn 之后接的是什么

**Comment by qingqing01** [comment]
OIDv5的主体是FasterRCNN.
