### ISSUE TITLE
关于 MS test 的问题

### ISSUE THREAD

**Issue by linyangsdu** [PaddlePaddle/PaddleDetection#1140]
我想知道你们在 OIDV5 里面使用的 MS test 配置，我自己配置了一下发现结果比 single scale mAP指标还要低一些

**Comment by linyangsdu** [comment]
我是在 obj365的val集上进行的测试

**Comment by still-wait** [comment]
@linyangsdu OIDV5里没有使用ms test配置，请问改了哪个配置文件，请把ms test的配置发下。

**Comment by linyangsdu** [comment]
我修改的是 obj365 里面的cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.yml，ms test 我是在 OIDV5的技术报告里面看到的

**Comment by WuShuang1998** [comment]
OID5里ms test用的好像不是原始的nms，而是top-k voting-nms。
```
Using the original nms, the mAP of the ms testing result is 0.5926 in private dataset which is not promoted.
However, the top-k voting-nms with only refining the score has a better result, the mAP is achieved to 0.6131.
```

**Comment by linyangsdu** [comment]
是的，配置里面有
