### ISSUE TITLE
python tools/train.py 中 如果 yml 里的 use_process 为 True 时就报错

### ISSUE THREAD

**Issue by XiminLin** [PaddlePaddle/PaddleDetection#1144]
在本地 MacOS 10.15.5, CPU version, paddlepaddle=2.0.0a0.  python=3.7
在
`python tools/train.py --config=configs/efficientdet_d0.yml` 中, 
如果 use_process 是 False 则正常跑, 如果 use_process 为 True则报错:

`
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > paddle::platform::GetTraceBackString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int)
1   paddle::operators::reader::BlockingQueue<std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> > >::EnforceNotKilled()
2   paddle::operators::reader::BlockingQueue<std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> > >::Receive(std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> >*)
4   std::__1::__packaged_task_func<std::__1::__bind<paddle::operators::reader::BufferedReader::ReadAsync(unsigned long)::$_0>, std::__1::allocator<std::__1::__bind<paddle::operators::reader::BufferedReader::ReadAsync(unsigned long)::$_0> >, unsigned long ()>::operator()()
5   std::__1::packaged_task<unsigned long ()>::operator()()
6   ThreadPool::ThreadPool(unsigned long)::'lambda'()::operator()() const
7   void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPool::ThreadPool(unsigned long)::'lambda'()> >(void*)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/Users/ximinlin/Documents/AI-Insects-Challenge/env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2800, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Users/ximinlin/Documents/AI-Insects-Challenge/env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1078, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/Users/ximinlin/Documents/AI-Insects-Challenge/env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 976, in __init__
    self._init_non_iterable()
  File "/Users/ximinlin/Documents/AI-Insects-Challenge/env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 608, in from_generator
    iterable, return_list, drop_last)
  File "/Users/ximinlin/Documents/PaddleDetection/ppdet/modeling/architectures/efficientdet.py", line 146, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "tools/train.py", line 114, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "tools/train.py", line 369, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
`

我在 AI Studio 上面用基础版 CPU 且 use_process=True 也是能跑的, 用的环境和本地Mac上一样, 请问会是什么问题? 谢谢

**Comment by qingqing01** [comment]
@XiminLin  不确定是不是Mac上不支持共享内存的多进程reader，我们测试看下。可以换成非共享的试下， 参考 https://github.com/PaddlePaddle/PaddleDetection/issues/874#issuecomment-639229449

**Comment by xiegegege** [comment]
@XiminLin hi~ 我这里参考 https://github.com/PaddlePaddle/PaddleDetection/issues/874#issuecomment-639229449修改后试了下是可以跑的

**Comment by XiminLin** [comment]
好谢谢
