### ISSUE TITLE
pretrain_weights 设置问题

### ISSUE THREAD

**Issue by elvinest** [PaddlePaddle/PaddleDetection#1150]
大家好，

我使用yolov3_r34_voc预训练模型来训练自已数据集时，pretrain_weights如何引用本地预训练权重

我从 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/MODEL_ZOO_cn.md 下载了YOLO v3 基于Pasacl VOC数据集及配置文件，当我解压 yolov3_r34_voc 后 文件夹中并不存在 .pdparams,.pdmodel...等文件，而是接近300个未知文件

bn_conv1_mean
bn_conv1_offset
...
res2a_branch1_weights
...
yolo_block.0.0.0.conv.weights
yolo_block.0.0.1.conv.weights
yolo_block.0.0.1.bn.mean
yolo_block.0.0.1.bn.offset
yolo_block.0.0.1.bn.scale
yolo_block.0.0.1.bn.var

我该引用哪一个? 
也没有配置文件默认的 yolov3_r34_voc/model_final
另外我还尝试  pretrain_weights: pretrain_models/yolov3_r34_voc.tar   均不行。

谢谢大家!

**Comment by elvinest** [comment]
已解决，设置为文件夹名即可

**Comment by xwr96** [comment]
> 已解决，设置为文件夹名即可

大佬，啥意思？能详细说下吗
