### ISSUE TITLE
PPYOLO vs. YOLOv5

### ISSUE THREAD

**Issue by edwardnguyen1705** [PaddlePaddle/PaddleDetection#1151]
Dear contributors,
Thanks for sharing your excellent work.
It is shown that PPYOLO outperforms YOLOV4. It would be nice if you could make a comparison between PPYOLO and [YOLOv5?](https://github.com/ultralytics/yolov5)

**Comment by qingqing01** [comment]
@edwardnguyen1705  Thanks!  YOLOv5 is also great!


| Model | AP<sup>test</sup> |   Speed<sub>GPU</sub> | FPS<sub>GPU</sub> | params | FLOPS |
|---------- |------   | ------| ------ |------  |  :------: |
| YOLOv5x   | 49.0  | 6.1ms     | 164     | 89.0M  | 166.4B|
|PP-YOLO|  45.2| 30ms| 33.3FPS | 44.93M | 45.12B|


Note, speed and FPS are calculated by batch-size 32 in official [YOLOv5](https://github.com/ultralytics/yolov5). Above data we tested by batch-size 1.    From the data, you can see test AP of YOLOv5 is good. But the params and FPS of PPYOLO is good.


And, thanks for your feedback. We will update doc.

**Comment by edwardnguyen1705** [comment]
@qingqing01 ,
Thank you for your information. Keep up the good work!

**Comment by qingqing01** [comment]
@edwardnguyen1705 Sorry,  I update the data.
