### ISSUE TITLE
关于AnchorGenerator的问题

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#1153]
class AnchorGenerator(object):
    __op__ = fluid.layers.anchor_generator
    __append_doc__ = True

    def __init__(self,
                 stride=[16.0, 16.0],
                 anchor_sizes=[32, 64, 128, 256, 512],
                 aspect_ratios=[0.5, 1., 2.],
                 variance=[1., 1., 1., 1.]):
        super(AnchorGenerator, self).__init__()
        self.anchor_sizes = anchor_sizes
        self.aspect_ratios = aspect_ratios
        self.variance = variance
        self.stride = stride
根据官方API文档所示
为RCNN算法生成anchor，输入的每一位产生N个anchor，N=size(anchor_sizes)*size(aspect_ratios)。生成anchor的顺序首先是aspect_ratios循环，然后是anchor_sizes循环。  意思是当anchor_sizes为32，aspect_ratios=0.5时候，N=32*32*0.5=512个吗？
这些锚点的xmin，xmax，ymin，ymax是根据什么生成的呢？而且这512个是按照长宽比[0.5, 1., 2.] 这种分布的吗

**Comment by jerrywgz** [comment]
anchor的生成个数是和anchor_size的长度和aspect_ratios的长度相关，例如，如果anchor_size是[64,128,256], aspect_ratios是[0.5, 1, 2.0], 那么就会在输入feature map的每个位置上生成9个anchor，这九个anchor的面积分别是64**2, 128**2, 256**2，长宽比分别是0.5， 1， 2。这两个参数决定了anchor的长宽，而anchor的中心点则是由输入feature map上点的位置和stride来决定，具体可以参考这里的代码https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/anchor_generator_op.h#L55 有了中心点和长宽即可计算出xmin,xmax,ymin,ymax

**Comment by shuxsu** [comment]
> anchor的生成个数是和anchor_size的长度和aspect_ratios的长度相关，例如，如果anchor_size是[64,128,256], aspect_ratios是[0.5, 1, 2.0], 那么就会在输入feature map的每个位置上生成9个anchor，这九个anchor的面积分别是64**2, 128**2, 256**2，长宽比分别是0.5， 1， 2。这两个参数决定了anchor的长宽，而anchor的中心点则是由输入feature map上点的位置和stride来决定，具体可以参考这里的代码https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/anchor_generator_op.h#L55 有了中心点和长宽即可计算出xmin,xmax,ymin,ymax

在想咨询一下 如果我想要把通过FPN网络后的feature maps 进行直接的预测分类  是直接通过卷积进行操作吗？我是否可以将整个feature maps 通过一定的操作 设置为一个参考的特征图  在传入后续的RPN网络  使RPN的计算量更小   生成的anchors不需要9个 只需要3个比例不同的  或者只生成一个呢？

**Comment by shuxsu** [comment]
> https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/anchor_generator_op.h#L55

anchor的中心点则是由输入feature map上点的位置和stride来决定 这里是什么意思呢   中心店是通过feature map上点的位置？feature map上会产生很多的点  这些点是通过RPN网络进行择优选择吗？最后确定了一个object上对应了9个anchor？

**Comment by jerrywgz** [comment]
> > anchor的生成个数是和anchor_size的长度和aspect_ratios的长度相关，例如，如果anchor_size是[64,128,256], aspect_ratios是[0.5, 1, 2.0], 那么就会在输入feature map的每个位置上生成9个anchor，这九个anchor的面积分别是64**2, 128**2, 256**2，长宽比分别是0.5， 1， 2。这两个参数决定了anchor的长宽，而anchor的中心点则是由输入feature map上点的位置和stride来决定，具体可以参考这里的代码https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/anchor_generator_op.h#L55 有了中心点和长宽即可计算出xmin,xmax,ymin,ymax
> 
> 在想咨询一下 如果我想要把通过FPN网络后的feature maps 进行直接的预测分类 是直接通过卷积进行操作吗？我是否可以将整个feature maps 通过一定的操作 设置为一个参考的特征图 在传入后续的RPN网络 使RPN的计算量更小 生成的anchors不需要9个 只需要3个比例不同的 或者只生成一个呢？

这个目的是希望生成的anchor少一些吗？这个把anchor_size和aspect_ratios大小搞小些就可以吧。在FPN结构中，会在每个level的feature map都生成一部分anchor，其中anchor size的大小为1，aspect_ratios大小为3.

**Comment by jerrywgz** [comment]
> > https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/anchor_generator_op.h#L55
> 
> anchor的中心点则是由输入feature map上点的位置和stride来决定 这里是什么意思呢 中心店是通过feature map上点的位置？feature map上会产生很多的点 这些点是通过RPN网络进行择优选择吗？最后确定了一个object上对应了9个anchor？

feature map对应的H,W的每个点都会对应9个anchor，然后进rpn来筛选候选框

**Comment by shuxsu** [comment]
> > > anchor的生成个数是和anchor_size的长度和aspect_ratios的长度相关，例如，如果anchor_size是[64,128,256], aspect_ratios是[0.5, 1, 2.0], 那么就会在输入feature map的每个位置上生成9个anchor，这九个anchor的面积分别是64**2, 128**2, 256**2，长宽比分别是0.5， 1， 2。这两个参数决定了anchor的长宽，而anchor的中心点则是由输入feature map上点的位置和stride来决定，具体可以参考这里的代码https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/anchor_generator_op.h#L55 有了中心点和长宽即可计算出xmin,xmax,ymin,ymax
> > 
> > 
> > 在想咨询一下 如果我想要把通过FPN网络后的feature maps 进行直接的预测分类 是直接通过卷积进行操作吗？我是否可以将整个feature maps 通过一定的操作 设置为一个参考的特征图 在传入后续的RPN网络 使RPN的计算量更小 生成的anchors不需要9个 只需要3个比例不同的 或者只生成一个呢？
> 
> 这个目的是希望生成的anchor少一些吗？这个把anchor_size和aspect_ratios大小搞小些就可以吧。在FPN结构中，会在每个level的feature map都生成一部分anchor，其中anchor size的大小为1，aspect_ratios大小为3.

**RPN的Anchor机制相当于对暴力穷举，论文中，设置stride=16，那么1000x16的图片就生成大约60x40x9=20000个Anchor Boxes，如此多的Anchor Boxes，需要经过一定筛选机制，剔除重复和无效的Anchor Boxes，以得到更好的Region Proposal。**

这是我在网上找到的解释  


想要的目的是 通过参考一步法目标检测  FPN后直接得到一个带有mask粗略的图  然后通过这个粗略得到的mask 圈定一个bbox，后再进去RPN 减少RPN中的计算量，因为RPN网络里不是有为了这个建议区域做大量的计算么  想通过减少这个暴力穷举的这个时间消耗  以及计算量  通过粗略的mask 来选定bbox    这个该如何实现呢

**Comment by shuxsu** [comment]
> > > > anchor的生成个数是和anchor_size的长度和aspect_ratios的长度相关，例如，如果anchor_size是[64,128,256], aspect_ratios是[0.5, 1, 2.0], 那么就会在输入feature map的每个位置上生成9个anchor，这九个anchor的面积分别是64**2, 128**2, 256**2，长宽比分别是0.5， 1， 2。这两个参数决定了anchor的长宽，而anchor的中心点则是由输入feature map上点的位置和stride来决定，具体可以参考这里的代码https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/anchor_generator_op.h#L55 有了中心点和长宽即可计算出xmin,xmax,ymin,ymax
> > > 
> > > 
> > > 在想咨询一下 如果我想要把通过FPN网络后的feature maps 进行直接的预测分类 是直接通过卷积进行操作吗？我是否可以将整个feature maps 通过一定的操作 设置为一个参考的特征图 在传入后续的RPN网络 使RPN的计算量更小 生成的anchors不需要9个 只需要3个比例不同的 或者只生成一个呢？
> > 
> > 
> > 这个目的是希望生成的anchor少一些吗？这个把anchor_size和aspect_ratios大小搞小些就可以吧。在FPN结构中，会在每个level的feature map都生成一部分anchor，其中anchor size的大小为1，aspect_ratios大小为3.
> 
> **RPN的Anchor机制相当于对暴力穷举，论文中，设置stride=16，那么1000x16的图片就生成大约60x40x9=20000个Anchor Boxes，如此多的Anchor Boxes，需要经过一定筛选机制，剔除重复和无效的Anchor Boxes，以得到更好的Region Proposal。**
> 
> 这是我在网上找到的解释
> 
> 想要的目的是 通过参考一步法目标检测 FPN后直接得到一个带有mask粗略的图 然后通过这个粗略得到的mask 圈定一个bbox，后再进去RPN 减少RPN中的计算量，因为RPN网络里不是有为了这个建议区域做大量的计算么 想通过减少这个暴力穷举的这个时间消耗 以及计算量 通过粗略的mask 来选定bbox 这个该如何实现呢

大佬快来吧
