### ISSUE TITLE
执行 scripts/build.sh 卡住

### ISSUE THREAD

**Issue by xgyyao** [PaddlePaddle/PaddleDetection#1162]
我在执行Linux平台编译指南中的Step4: 编译步骤时，在执行sh ./scripts/build.sh命令后开始下载ext-yaml-cpp
一直卡在[ 16%] Performing download step (download, verify and extract) for 'ext-yaml-cpp'这一步，应该是网络问题，请问怎么通过下载离线包进行编译呢？谢谢！

**Comment by willthefrog** [comment]
下载解压到 `build/ext/yaml-cpp/`试试？

**Comment by xgyyao** [comment]
我下载解压到`build/ext/yaml-cpp/`后，再执行sh ./scripts/build.sh，还是会卡在[ 16%] Performing download step (download, verify and extract) for 'ext-yaml-cpp'这一步，之前解压好的build/ext/yaml-cpp/下的文件则被清空，又重新下了，但是还是下载不下来

**Comment by willthefrog** [comment]
删掉[这行](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/cpp/scripts/build.sh#L24)？

**Comment by willthefrog** [comment]
可能 [这行](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/cpp/CMakeLists.txt#L15)也得删掉

**Comment by xgyyao** [comment]
根据你的建议之后可以成功编译并跑通，谢谢！不过我在测试视频的时候，推理速度却较慢。
我计算了main.cc中 `det->Predict(frame, &result);`和绘制框的时间，差不多需要80-90ms/帧。
使用的模型：`yolov4_cspdarknet`，输入尺寸为608x608，显卡：1080ti 11g，未使用tensorrt
`build.sh`配置如下：
WITH_GPU=ON
WITH_MKL=ON
WITH_TENSORRT=OFF
TENSORRT_DIR=/path/to/TensorRT/
PADDLE_DIR=/paddle/project/fluid_inference/WITH_STATIC_LIB=OFF
CUDA_LIB=/usr/local/cuda/lib64
CUDNN_LIB=/usr/local/cuda/lib64

请问这个速度是正常的吗？

**Comment by willthefrog** [comment]
说明给出的性能指标都是在v100测试的，无法给出1080ti的预期性能，不过如果性能无法满足需求，可以尝试开启tensorrt，应该能提升不少。

**Comment by xgyyao** [comment]
之前在原版yolov4上测试大概在40-45ms，tensorrt7上测纯推理大概12ms，加上编解码预处理等大概24ms。所以感觉paddle上有点略慢，我再试试paddle的tensorrt加速吧。
再次感谢！！

**Comment by willthefrog** [comment]
不客气，如果问题解决了辛苦close下issue。多谢。

**Comment by Aming1998** [comment]
您好 为什么我删了这一行之后报错是
![Uploading 1645705379(1).png…]()



> 可能 [这行](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/cpp/CMakeLists.txt#L15)也得删掉
