### ISSUE TITLE
建议增加ppyolo 轻量级

### ISSUE THREAD

**Issue by Tim5Tang** [PaddlePaddle/PaddleDetection#1163]
1.建议增加一下ppyolo 轻量级网络，现在这ppyolo精度速度看起来比yolov4好，但是对于一些边缘设备，想要达到实时效果，这ppyolo-tiny也有50M太大了，建议使用mobilenet这一的基础网络，yolov5s 模型大小map值是36.1，模型大小只有28M的样子。
2.建议做lite版本或者轻量级版本的时候将yolo head中的conv 换成group conv减少参数量，感觉这里占好多参数

**Comment by heavengate** [comment]
感谢您的建议，我们这边也在探索mobilenet v3等骨干网络的tiny模型，有高性价比的模型会在第一时间发布。

**Comment by Tim5Tang** [comment]
好的了解
