### ISSUE TITLE
关于增强算子ResizeImage的疑惑

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/PaddleDetection#1166]
在调整数据增强顺序的时候，发现ResizeImage处理后没有更新sample的w，h，gt_bbox的信息，这可能会对之后数据处理产生影响（比如我想在resize之后做下crop）想知道下这边不去更新是出于其他的考虑吗

**Comment by willthefrog** [comment]
这个是之前遗留的设计，两阶段模型很多算子是使用原始维度信息+ scale来作为输入的。后续可能会重构。

**Comment by zhengzhe97** [comment]
@willthefrog 我把sample['im_info']改成[resize_h, resize_w, 1.]，然后把w，h，gt_bbox都改成resize后的数据，测试的时候出现全0的情况，想知道有其他办法吗，想在resize之后使用crop。

![image](https://user-images.githubusercontent.com/26462054/89483628-18a6ad00-d7cf-11ea-889f-9442b25f44e9.png)

**Comment by zhengzhe97** [comment]
好像在训练时修改，测试时保持不变就可以了
