### ISSUE TITLE
在使用kitti数据集（转为voc 格式）训练ppyolo时报错，，

### ISSUE THREAD

**Issue by tianyuluan** [PaddlePaddle/PaddleDetection#1169]
**Error: op slice does not have kernel for data_type[float]:data_layout[ANY_LAYOUT]:place[CUDAPinnedPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1090)
  [operator < slice > error]**

**整体报错如下：**（有点长）
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/ops.py:327
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:145
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:162
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:162
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:164
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:164
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:168
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:168
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:170
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:170
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/iou_loss.py:219
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/iou_loss.py:220
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/iou_loss.py:221
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/iou_loss.py:222
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/iou_loss.py:102
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/iou_loss.py:102
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/iou_loss.py:104
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/iou_loss.py:106
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/iou_loss.py:106
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/iou_loss.py:106
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/iou_loss.py:107
The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/iou_loss.py:84
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:176
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:184
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:370
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:372
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:197
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:198
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:200
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
2020-08-06 12:52:01,344-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/anchor_heads/iou_aware.py:64
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:276: UserWarning: /home/lty/PaddleDetection/ppdet/modeling/anchor_heads/iou_aware.py:40
The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
2020-08-06 12:52:03,376-INFO: places would be ommited when DataLoader is not iterable
W0806 12:52:03.421161  6741 device_context.cc:268] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.1
W0806 12:52:03.423032  6741 device_context.cc:276] device: 0, cuDNN Version: 7.6.
/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/io.py:2116: UserWarning: This list is not set, Because of Paramerter not found in program. There are: fc_0.b_0 fc_0.w_0
  format(" ".join(unused_para_list)))
2020-08-06 12:52:07,029-INFO: places would be ommited when DataLoader is not iterable
Traceback (most recent call last):
  File "tools/train.py", line 368, in <module>
    main()
  File "tools/train.py", line 241, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1082, in run
    six.reraise(*sys.exc_info())
  File "/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1080, in run
    return_merged=return_merged)
  File "/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1195, in _run_impl
    return_merged=return_merged)
  File "/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/executor.py", line 893, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

  Compile Traceback (most recent call last):
    File "tools/train.py", line 368, in <module>
      main()
    File "tools/train.py", line 114, in main
      train_fetches = model.train(feed_vars)
    File "/home/lty/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 159, in train
      return self.build(feed_vars, mode='train')
    File "/home/lty/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 85, in build
      gt_score, targets)
    File "/home/lty/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 401, in get_loss
      self.prefix_name)
    File "/home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 69, in __call__
      mask_anchors, self._ignore_thresh)
    File "/home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 143, in _get_fine_grained_loss
      tx, ty, tw, th, tscale, tobj, tcls = self._split_target(target)
    File "/home/lty/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 292, in _split_target
      tobj = target[:, :, 5, :, :]
    File "/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1672, in __getitem__
      return _getitem_impl_(self, item)
    File "/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/framework.py", line 801, in _getitem_impl_
      attrs=attrs)
    File "/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2803, in append_op
      attrs=kwargs.get("attrs", None))
    File "/home/lty/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1917, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
3   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
4   paddle::framework::details::ComputationOpHandle::RunImpl()
5   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
8   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
9   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
10  std::string paddle::platform::GetTraceBackString<std::string >(std::string&&, char const*, int)

----------------------
Error Message Summary:
----------------------
Error: op slice does not have kernel for data_type[float]:data_layout[ANY_LAYOUT]:place[CUDAPinnedPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1090)
  [operator < slice > 

> error]

**我的yaml文件如下**

architecture: YOLOv3
use_gpu: true
max_iters: 10000
log_smooth_window: 10
log_iter: 10
save_dir: output
snapshot_iter: 1000
metric: VOC
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_ssld_pretrained.tar
weights: output/ppyolo/model_final
num_classes: 3
use_fine_grained_loss: true
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head
  use_fine_grained_loss: true

ResNet:
  norm_type: sync_bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 50
  feature_maps: [3, 4, 5]
  variant: d
  dcn_v2_stages: [5]

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  coord_conv: true
  iou_aware: true
  iou_aware_factor: 0.4
  scale_x_y: 1.05
  spp: true
  yolo_loss: YOLOv3Loss
  nms: MatrixNMS
  drop_block: true

YOLOv3Loss:
  batch_size: 8
  ignore_thresh: 0.5
  scale_x_y: 1.05
  label_smooth: false
  use_fine_grained_loss: true
  iou_loss: IouLoss
  iou_aware_loss: IouAwareLoss

IouLoss:
  loss_weight: 2.5
  max_height: 608
  max_width: 608

IouAwareLoss:
  loss_weight: 1.0
  max_height: 608
  max_width: 608

MatrixNMS:
    background_label: -1
    keep_top_k: 100
    normalized: false
    score_threshold: 0.01
    post_threshold: 0.01

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 5000
    - 8000
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
      #image_dir: train2017
      dataset_dir: /home/lty/PaddleDetection/dataset/voc
      anno_path: trainval.txt
      with_background: false
      use_default_label: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: True
    - !MixupImage
      alpha: 1.5
      beta: 1.5
    - !ColorDistort {}
    - !RandomExpand
      fill_value: [123.675, 116.28, 103.53]
    - !RandomCrop {}
    - !RandomFlipImage
      is_normalized: false
    - !NormalizeBox {}
    - !PadBox
      num_max_boxes: 50
    - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
    random_inter: True
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: True
  # Gt2YoloTarget is only used when use_fine_grained_loss set as true,
  # this operator will be deleted automatically if use_fine_grained_loss
  # is set as false
  - !Gt2YoloTarget
    anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
    anchors: [[10, 13], [16, 30], [33, 23],
              [30, 61], [62, 45], [59, 119],
              [116, 90], [156, 198], [373, 326]]
    downsample_ratios: [32, 16, 8]
  batch_size: 8
  shuffle: true
  mixup_epoch: 25000
  drop_last: true
  worker_num: 4
  bufsize: 4
  use_process: true

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
      #image_dir: val2017
      anno_path: test.txt
      dataset_dir: /home/lty/PaddleDetection/dataset/voc
      with_background: false
      use_default_label: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !PadBox
      num_max_boxes: 50
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 8
  drop_empty: false
  worker_num: 8
  bufsize: 4

TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
  dataset:
    !ImageFolder
      anno_path: /home/lty/PaddleDetection/dataset/voc/label_list.txt
      with_background: false
      use_default_label: false
  ple_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1

已经按照您说的安装了develop的版本https://github.com/PaddlePaddle/PaddleDetection/issues/1103#issuecomment-663858241

**请问是我数据格式问题还是别的问题？？？**

**Comment by qingqing01** [comment]
@tianyuluan 请问是如何安装的，似乎安装的不是GPU版本。

**Comment by tianyuluan** [comment]
> @tianyuluan 请问是如何安装的，似乎安装的不是GPU版本。

谢谢您的回复
因为MatrixNMS报错的原因，我是在https://github.com/PaddlePaddle/PaddleDetection/issues/1103中提到的安装每日版本，下载paddlepaddle_gpu-0.0.0-cp37-cp37m-linux_x86_64.whl  然后pip install .....whl

**Comment by heavengate** [comment]
您好，最近框架有修改，存在一些不兼容，我们再跟进，确认好后第一时间通知你这边

**Comment by qingqing01** [comment]
可以使用最新已发布的1.8.4的whl包，关闭了此issue，有问题可以再新建新的issue.
