### ISSUE TITLE
按照训练自定义训练进行操作出现编码问题

### ISSUE THREAD

**Issue by renjiechao88** [PaddlePaddle/PaddleDetection#1173]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 315: illegal multibyte sequence

数据集布置格式：
dataset
     - voc
         - VOCdevkit
              //绝对路径   VOCdevkit\VOC2007\JPEGImages\20191115_143546_6.jpg 
              VOCdevkit\VOC2007\Annotations\20191115_143546_6.xml
              - test.txt 
              -trainval.txt
              -VOC2007
                   -Annotations
                  -ImageSets
                  -JPEGImages

修改的faster-fpn-reader.yml  一部分
TrainReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd']
  dataset:
#  - !COCODataSet
#    image_dir: train2017
#    anno_path: annotations/instances_train2017.json
#    dataset_dir: dataset/coco
  - !VOCDataSet
    dataset_dir: dataset/voc/VOCdevkit  # 数据集根目录
    anno_path: trainval.txt   # 训练集列表文件基于数据集根目录的相对路径
    use_default_label: false   # 是否使用默认标签，默认为true。
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !RandomFlipImage
    prob: 0.5
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    target_size: 800
    max_size: 1333
    interp: 1
    use_cv2: true
  - !Permute
    to_bgr: false
    channel_first: true
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
    use_padded_im_info: false
  batch_size: 1
  shuffle: true
  worker_num: 2
  use_process: false

**Comment by still-wait** [comment]
@renjiechao88 请问哪个py文件报错，具体报错信息麻烦发下吧。

**Comment by renjiechao88** [comment]
> @renjiechao88 请问哪个py文件报错，具体报错信息麻烦发下吧。

这是具体的报错信息，我是想用自己的数据集来训练网络，用的文档上写的VOC的组织形式

Traceback (most recent call last):
  File "tools/train.py", line 368, in <module>
    main()
  File "tools/train.py", line 67, in main
    cfg = load_config(FLAGS.config)
  File "C:\Users\rjc\Downloads\PaddleDetection-release-0.4\ppdet\core\workspace.py", line 96, in load_config
    merge_config(yaml.load(f, Loader=yaml.Loader))
  File "C:\Users\rjc\Anaconda3\envs\python3\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "C:\Users\rjc\Anaconda3\envs\python3\lib\site-packages\yaml\loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\rjc\Anaconda3\envs\python3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\rjc\Anaconda3\envs\python3\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\rjc\Anaconda3\envs\python3\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 315: illegal multibyte sequence

**Comment by still-wait** [comment]
@renjiechao88 请问路径中包含中文字符吗？如果包含中文字符，请将所有中文字符改成英文字符试下。

**Comment by renjiechao88** [comment]
> @renjiechao88 请问路径中包含中文字符吗？如果包含中文字符，请将所有中文字符改成英文字符试下。

这是代码的路径
C:\Users\rjc\Downloads\PaddleDetection-release-0.4  、
数据集图片就放在C:\Users\rjc\Downloads\PaddleDetection-release-0.4\dataset\voc\VOCdevkit\VOC2007\JPEGImages这个下面

**Comment by still-wait** [comment]
@renjiechao88 把yaml配置文件中所有中文字符都去掉，包括#后注释的内容。
