### ISSUE TITLE
训练结束之后，model已经保存，但是程序一直不退出

### ISSUE THREAD

**Issue by zhengkai15** [PaddlePaddle/PaddleDetection#1175]
请问一下这个是什么原因，怎么解决呢

**Comment by still-wait** [comment]
@zhengkai15 请问跑的哪个配置文件，在Windows下还是Linux下，单卡训练还是多卡训练，是否使用paddle.distributed.launch？

**Comment by AN-ZE** [comment]
@zhengkai15  是系统问题，重启机器就可以。之前遇到过
