### ISSUE TITLE
训练object365模型，有人遇到推理结果类别标签不准的问题吗

### ISSUE THREAD

**Issue by huxianhe0** [PaddlePaddle/PaddleDetection#1182]
![Image text](https://raw.githubusercontent.com/huxianhe0/Pictures/master/073.jpg)
如图，检测物很准，但标签明显全部对不上，各位大神有人遇到过吗？

**Comment by qingqing01** [comment]
@huxianhe0  参考这个issue: https://github.com/PaddlePaddle/PaddleDetection/issues/760#issuecomment-632986820  我们增加下文档吧

**Comment by huxianhe0** [comment]
> @huxianhe0 参考这个issue: [#760 (comment)](https://github.com/PaddlePaddle/PaddleDetection/issues/760#issuecomment-632986820) 我们增加下文档吧

感谢，同时也希望能提供train
