### ISSUE TITLE
用CPU训练正常，用GPU训练报错

### ISSUE THREAD

**Issue by pipishaw** [PaddlePaddle/PaddleDetection#1183]
用CPU训练正常，用GPU训练报如下错误：
ExternalError:  Cudnn error, CUDNN_STATUS_NOT_INITIALIZED  at (D:\1.8.3\paddle\paddle/fluid/platform/device_context.h:165)

试过装各种版本的CUDA，9.0,10.0都装过，都报错。

显卡是比较老的GeForce GT 720M，显卡驱动只能装到385.54，再高就显示找不到硬件。

谁遇到过这种情况，有什么好的解决办法吗？

**Comment by qingqing01** [comment]
@pipishaw 

<img width="706" alt="图片" src="https://user-images.githubusercontent.com/7845005/89751126-6db12e80-db01-11ea-9bec-d266dd81d45a.png">


依据您的driver版本，应该CUDA只能用9.0。 然后选择对应的Paddle安装包，以及使得本地cuDNN的版本和安装包的cuDNN版本对应。

**Comment by aze999** [comment]
怎么使用cpu训练呢

**Comment by jeychandar** [comment]
@wangxinxin08 Hi I have query regarding this. I am trying to run this command but it gives error like this. Could you help me out with this error. Thanks in advance.

CUDA_VISIBLE_DEVICES=0 python tools/infer.py -c configs/ppyoloe/ppyoloe_plus_crn_l_80e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_plus_crn_l_80e_coco.pdparams --infer_img=demo/000000014439_640x640.jpg

![image](https://github.com/PaddlePaddle/PaddleDetection/assets/48254471/74569e46-53c7-4956-9a5e-796a9ebcd1ab)

**my nvcc version and nvidia-smi Info:**
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/48254471/45a1306c-187e-4262-8eed-a8b9339ddc3f)

**In my bashrc I exported this also:**

export PATH="/usr/local/cuda-11.8/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-11.7/lib64:$LD_LIBRARY_PATH"
