### ISSUE TITLE
配置文件中使用finetune_exclude_pretrained_params参数控制忽略参数名

### ISSUE THREAD

**Issue by xiaolifeimianbao** [PaddlePaddle/PaddleDetection#1184]
比如finetune_exclude_pretrained_params=['cls_score','bbox_pred']
是对预训练模型加载时不加载预训练模型中的cls_score与bbox_pred这两个层的参数吗？
教程中只给了输出层的类别相关参数，如果想忽略其他层的参数应该怎么做？

**Comment by qingqing01** [comment]
@xiaolifeimianbao 

1.   默认不设置的情况，会不加载shape不匹配的参数。
2.  其次，如果想精细的控制，通过finetune_exclude_pretrained_params设置的参数，都不会加载。如果想其他层的参数，可以降对应的参数名字设置下。具体的名字，可以看下 保存的参数中的名字。 或者通过 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Program_cn.html#all-parameters 查看。

**Comment by jerrywgz** [comment]
issue先关闭了，如果还有新的问题可以再提issue，我们会及时跟进
