### ISSUE TITLE
ppyolo training error

### ISSUE THREAD

**Issue by snovire** [PaddlePaddle/PaddleDetection#1186]
您好，用自己的数据集训练ppyolo.yml时，出现TypeError: yolo_box() got an unexpected keyword argument 'scale_x_y'，请问怎么解决

**Comment by qingqing01** [comment]
@snovire  对于PPYOLO和YOLO系列模型，release/0.4分支需要develop版本的Paddle安装包，参考 https://github.com/PaddlePaddle/PaddleDetection/issues/1103#issuecomment-663858241 进行升级下吧。

**Comment by snovire** [comment]
> @snovire 对于PPYOLO和YOLO系列模型，release/0.4分支需要develop版本的Paddle安装包，参考 [#1103 (comment)](https://github.com/PaddlePaddle/PaddleDetection/issues/1103#issuecomment-663858241) 进行升级下吧。

谢谢您，升级是可行的 @qingqing01
