### ISSUE TITLE
yolov3训练时报错

### ISSUE THREAD

**Issue by cucuzg** [PaddlePaddle/PaddleDetection#1188]
表现是每轮训练model可以，evaluate就出错了，evaluate的数据是直接拷贝train数据列表里面的，如果有错前面train就出错；这个是yolov3的模型，也看了下数据集标注的没有问题，前几天还是能正常运行的，这次的区别只是多了一些数据
![image](https://user-images.githubusercontent.com/13131672/89853495-1fb12f00-dbc4-11ea-9a78-e4dc0ea3b42b.png)

**Comment by cucuzg** [comment]
one more figure
![image](https://user-images.githubusercontent.com/13131672/89853700-a0702b00-dbc4-11ea-8bb4-b8bc55c35f8c.png)

**Comment by jerrywgz** [comment]
可以检查下是不是gt_label中的label超出了num_classes的范围

**Comment by cucuzg** [comment]
是的 感谢@jerrywgz
