### ISSUE TITLE
paddledetection写这么复杂是为了人好用吗

### ISSUE THREAD

**Issue by zzchust** [PaddlePaddle/PaddleDetection#1190]
仔细看了paddledetection的代码，写的太复杂了，确定把所有模型所有配置融合再一起是为了大家好用吗？

工业上实际使用的就那几个backbone，搞的这么复杂，一点不适合二次开发啊。。
我只想改个reader都让我心力憔悴了。

**Comment by qingqing01** [comment]
@zzchust  感谢建议。


这里的模块划分一般分成了backbone和head， 为了灵活的更换不同的模块，比如更换backbone、更换不同FPN、不同的loss、不同的数据增强。这个在实际论文/research里、工业应用里也确实会长做。

另外，这里也提供了文档说明:  https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/advanced_tutorials/MODEL_TECHNICAL.md


关于reader， 这里也提供了文档: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/advanced_tutorials/READER.md

一般来说，更换数据源(主要是解析数据)可以参考: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/advanced_tutorials/READER.md#%E6%B7%BB%E5%8A%A0%E6%96%B0%E6%95%B0%E6%8D%AE%E6%BA%90

如果是增加数据增强操作： 参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/advanced_tutorials/READER.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA%E7%AE%97%E5%AD%90


我们也会持续改进。

**Comment by zzchust** [comment]
封装起来的结果就是使使用门槛大大增加。 可以单独新建典型的模块做快速使用。以前有yolov3和ssd，这两个模块挺好的，不知道怎么废弃了，也找不到了。

对新手要友好， 搞那么复杂，门槛太高。

**Comment by zzchust** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/advanced_tutorials/READER.md#%E6%B7%BB%E5%8A%A0%E6%96%B0%E6%95%B0%E6%8D%AE%E6%BA%90

这里把reader封装了几次，针对标准的coco/voc等本地存储数据好处理，但是几百万数据不太能存本地， 就需要较大修改重新开发了
