### ISSUE TITLE
配置文件中的预训练模型地址

### ISSUE THREAD

**Issue by xiaolifeimianbao** [PaddlePaddle/PaddleDetection#1192]
配置文件中部分预训练模型地址，比如https://paddlemodels.bj.bcebos.com/object_detection/yolov3_mobilenet_v1.tar
开头是https://paddlemodels.bj.bcebos.com/object_detection/
而有的部分预训练模型地址，比如http://paddle-imagenet-models-name.bj.bcebos.com/MobileNetV1_pretrained.tar开头是http://paddle-imagenet-models-name.bj.bcebos.com/，这两种地址的模型有什么区别？

**Comment by jerrywgz** [comment]
object_detection目录下的是在检测数据集（coco或voc）上训练得到的模型，imagenet目录下是backbone部分在imagenet训练的模型，通常用来作为检测的预训练模型
