### ISSUE TITLE
如何获取rpn_target_assign得到的pred_scores在每张图片上的均值？

### ISSUE THREAD

**Issue by flishwang** [PaddlePaddle/PaddleDetection#1193]
在faster_rcnn/cascade_rcnn中，我需要得到rpn_cls_loss在每张图片上的均值。应如何获取？

paddle中，fluid.layers.rpn_target_assign会得到维度为[F+B,1]的tensor （predicted_scores和target_labels）。但如何区分tensor中每一行对应哪张图片呢？

**Comment by jerrywgz** [comment]
rpn_target_assign返回的pred和target都是带有lod信息的，即shape为[N1+N2, ...]，N1为第一张图F+B的个数，N2为第二张图F+B的个数。目前还没有直接的方式可以得到每个图片的均值，可以尝试下使用sequence_pad得到pred的每张图片中样本的个数，具体可以参考文档https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sequence_pad_cn.html#cn-api-fluid-layers-sequence-pad  然后根据输出的样本个数来对pred做slice，然后取平均。

**Comment by flishwang** [comment]
> rpn_target_assign返回的pred和target都是带有lod信息的，即shape为[N1+N2, ...]，N1为第一张图F+B的个数，N2为第二张图F+B的个数。目前还没有直接的方式可以得到每个图片的均值，可以尝试下使用sequence_pad得到pred的每张图片中样本的个数，具体可以参考文档https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/sequence_pad_cn.html#cn-api-fluid-layers-sequence-pad 然后根据输出的样本个数来对pred做slice，然后取平均。

非常感谢！
通过layers.Print，我观察到：
C++ operator rpn_target_assign返回的结果ScoreIndex, TargetLabel是有lod信息的。
但detection.py中，predicted_cls_logits = nn.gather(cls_logits, score_index)后，返回的predicted_cls就不带lod信息了。
这导致我无法直接使用sequence_pool(type='average')获取均值。

有没有操作把TargetLabel的lod信息赋值给predicted_cls_logits呢？

**Comment by jerrywgz** [comment]
嗯由于后面直接进入loss计算因此没有再恢复lod的值。可以尝试使用lod_reset https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/lod_reset_cn.html#lod-reset

**Comment by flishwang** [comment]
> 嗯由于后面直接进入loss计算因此没有再恢复lod的值。可以尝试使用lod_reset https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/lod_reset_cn.html#lod-reset

谢谢！ lod_reset可以用。问题解决了。
