### ISSUE TITLE
配置文件中的reader的改写

### ISSUE THREAD

**Issue by xiaolifeimianbao** [PaddlePaddle/PaddleDetection#1194]
TrainReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd']
  dataset:
    !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: dataset/coco
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !RandomFlipImage
    prob: 0.5
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    target_size: 800
    max_size: 1333
    interp: 1
    use_cv2: true
  - !Permute
    to_bgr: false
    channel_first: true
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
    use_padded_im_info: false
  batch_size: 1
  shuffle: true
  worker_num: 2
  use_process: false
以上是一个单独的配置文件中写的TrainReader
而我在模型配置文件中TrainReader改写为
TrainReader:
  dataset:
    !VOCDataSet
    dataset_dir: dataset
    anno_path: trainval.txt
    use_default_label: false
  batch_size: 2

是覆盖前者TrainReader下的的全部，还是只覆盖模型配置文件中TrainReader下改写的部分

**Comment by willthefrog** [comment]
是按键值合并的，如果键值是一个object或者list，比如`dataset`或者`sample_transforms`，需要写全，因为会覆盖整个object或者list。

**Comment by xiaolifeimianbao** [comment]
> 是按键值合并的，如果键值是一个object或者list，比如`dataset`或者`sample_transforms`，需要写全，因为会覆盖整个object或者list。

那比如我在模型配置文件TrainReader中仅改写了dataset，那么会对它调用的reader配置文件中的TrainReader中的dataset下的内容进行覆盖，而reader配置文件中TrainReader下的sample_transforms依旧会执行是吗

**Comment by willthefrog** [comment]
是的。是按键值为单位覆盖的。
