### ISSUE TITLE
do not understand params 'post_nms_top_n' and 'pre_nms_top_n' in faster_rcnn_r50_fpn_1x.yml

### ISSUE THREAD

**Issue by IvyGongoogle** [PaddlePaddle/PaddleDetection#1202]
您好，我所理解的，对于faster_rcnn_r50_fpn模型 需要在每个level上对anchors分别进行nms，然后再把nms计算后的各个level的anchor再合起来，看到faster_rcnn_r50_fpn_1x.yml 中post_nms_top_n 和 pre_nms_top_n这两个参数，追踪代码到[fluid.layers.collect_fpn_proposals](https://github.com/PaddlePaddle/PaddleDetection/blob/release%2F0.4/ppdet/modeling/anchor_heads/rpn_head.py#L470)，再进collect_fpn_proposals这个函数里没有看到代码在各个level的anchor取多少 怎么算nms的， 麻烦可以给点解释吗？
Thanks

**Comment by jerrywgz** [comment]
pre_nms_top_n是在每个level筛选roi时输入的roi个数，post_nms_top_n是完成nms后保留的roi个数，这个逻辑是在generate_proposals_op中, 源码可以参考https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/generate_proposals_op.cc#L409 和 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/generate_proposals_op.cc#L448

关于collect_fpn_proposals这个op，是会将每个level筛选之后的所有roi集成在一起，然后按分数进行排序，保留post_nms_top_n个roi

**Comment by IvyGongoogle** [comment]
@jerrywgz 谢谢您的回复。 pre_nms_top_n和post_nms_top_n都是2000怎么理解呢？ post_nms_top_n是指每个level上nms后roi的最大保留数？ 那pre_nms_top_n呢？

**Comment by jerrywgz** [comment]
1. pre_nms_top_n是个上限值，如果一个level上没有产生足够的roi，那就保留所有的roi进入筛选
2. 是的

**Comment by IvyGongoogle** [comment]
@jerrywgz 
1.为什么 `pre_nms_top_n` 和 `post_nms_top_n`值是一样的呢

**Comment by jerrywgz** [comment]
这里pre_nms_top_n和post_nms_top_n首先是RPN阶段的generate_proposals中用于限制proposals的数量。这个过程post_nms_top_n可以理解为暂时不起作用，因为经过nms后的proposals数量一定小于pre_nms_top_n。
而在FPN结构中，由于每一层都会产生proposals，这样合计的proposals的数量就可能会远大于post_nms_top_n这个阈值。这个时候在collect_fpn_proposals中就会使用这个阈值来限制最终合计的proposals数量
