### ISSUE TITLE
把yolov3网络结构改成yolov5的，训练损失出现inf，跪求大佬指导,有可能是哪儿出了问题？

### ISSUE THREAD

**Issue by Zoom-kai** [PaddlePaddle/PaddleDetection#1203]
![image](https://user-images.githubusercontent.com/61818940/90089656-7f3e4480-dd54-11ea-8c08-fd1e32d1c467.png)

>

**Comment by jerrywgz** [comment]
这个可能导致的原因会比较多，可以提一些小意见参考下：
1. 如果使用新的网络结构，需要确认下loss计算等算法逻辑是否有疏漏，例如有没有考虑到正样本为空的情况
2. 是否使用预训练模型，预训练模型会让模型训练更稳定
3. 可以尝试使用梯度截断来确保不出现梯度过大的情况，使用方法可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/efficientdet_d0.yml#L64
4. yolov3_darknet的官网配置中的学习率是0.01，是对应8卡，每张卡batch_size为8（即一次迭代的总bs为64）设置的。如果只用单卡训练，那么理论上来说学习率应该是0.01/8 = 0.0125
请问使用几卡训练呢，

**Comment by Zoom-kai** [comment]
我用单张 RTX2070 显卡 训练的
