### ISSUE TITLE
Found an invalid bbox in annotations, but the bbox is normal in anno file

### ISSUE THREAD

**Issue by IvyGongoogle** [PaddlePaddle/PaddleDetection#1205]
Hello, I found one question. When I train model, some warnings show: 
`Found an invalid bbox in annotations: im_id: 89, area: -8902.439024390242 x1: 470.390243902439, y1: 826.0487804878048, x2: 470.390243902439, y2: 914.0731707317073.` Obviously, x1=x2. So I track this image's anno json file got by `labelme`, but find that the all bboxs in this json file is normal, x1≠x2. Like:

```
{
  "version": "4.5.6",
  "flags": {},
  "shapes": [
    {
      "label": "dog",
      "points": [
        [
          470.390243902439,
          826.0487804878048
        ],
        [
          370.390243902439,
          915.0731707317073
        ]
      ],
      "group_id": null,
      "shape_type": "rectangle",
      "flags": {}
    },
    {
      "label": "dog",
      "points": [
        [
          509.4146341463414,
          858.9756097560975
        ],
        [
          432.5853658536585,
          794.3414634146341
        ]
      ],
      "group_id": null,
      "shape_type": "rectangle",
      "flags": {}
    },
    {
      "label": "dog",
      "points": [
        [
          435.0243902439024,
          751.6585365853658
        ],
        [
          485.0243902439024,
          800.4390243902438
        ]
      ],
      "group_id": null,
      "shape_type": "rectangle",
      "flags": {}
    }
  ],
  "imagePath":xxx
  "imageData": xxx
  "imageHeight": 1080,
  "imageWidth": 1920
}

```
So what causes this problem.

Can you give some advises?
Thanks

**Comment by qingqing01** [comment]
Thanks your feedback.

In source code, the `area` is from the anno json file:

https://github.com/PaddlePaddle/PaddleDetection/blob/7ee64e96393abc9396c0ade18d5e871468c36b9c/ppdet/data/source/coco.py#L140-L147


Could you check wether there is `area` in anno json file?

**Comment by qingqing01** [comment]
@IvyGongoogle  Is there any question?

**Comment by IvyGongoogle** [comment]
@qingqing01 I check all labelme anno json file and find that there is no "area" item.

直接用中文吧，如果labelme的标注json文件都没有"area" item，那按照`if inst['area'] > 0 and x2 >= x1 and y2 >= y1: `这个逻辑，训练数据中一张图片都不应该找到啊。。。

**Comment by wangxinxin08** [comment]
fixed by https://github.com/PaddlePaddle/PaddleDetection/pull/1301

**Comment by simon-sxx** [comment]
请问解决了吗
