### ISSUE TITLE
YOLO v3 那个dataset起作用

### ISSUE THREAD

**Issue by CVdandelion** [PaddlePaddle/PaddleDetection#1208]
我看到yolov3_r34_voc.yml这个文件和yolov3_reader.yml这个文件都有关于dataset的配置，请问一下到底在数据集读取的时候哪个配置文件起作用阿，还是都起作用阿

**Comment by CVdandelion** [comment]
如果yolov3_reader.yml里的配置不起作用，那这句话     _READER_: 'yolov3_reader.yml'     的作用是什么，还有就是这个文件yolov3_reader.yml是干嘛用的，好像和yoloV3相关的模型，都有这句话。

**Comment by qingqing01** [comment]
`yolov3_reader.yml`  是一个base的预处理流程，可以被不同的config复用。  `yolov3_r34_voc.yml`重新定义的内容会覆盖base的内容。

**Comment by CVdandelion** [comment]
好的，谢谢
