### ISSUE TITLE
faster rcnn fpn系列网络可以用tensorrt加速吗 ?

### ISSUE THREAD

**Issue by IvyGongoogle** [PaddlePaddle/PaddleDetection#1212]
如题，请问faster rcnn fpn系列网络可以用tensorrt加速吗 ? 具体怎么操作呢？ 比如`faster_rcnn_r50_vd_fpn_2x.yml`，有相关文档吗？ 
Thanks

**Comment by qingqing01** [comment]
1. 这是预测的benchmark: 

    https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/advanced_tutorials/deploy/BENCHMARK_INFER_cn.md  

    之前V100 FP32效果不是很明显。FP16有些加速。

2.  预测用法参考deploy下面。

- C++预测使用TensorRT:
   需要自行编译或直接下载包含TensorRT的预测库： https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html#id1

   参考这里 https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/deploy 的C++预测文档测试。


- Python预测使用TensorRT:
   目前paddle发布的whl包不包含tensorrt，需要自行编译的whl包安装之后，才能参考 deploy下面的python预测文档。
