### ISSUE TITLE
可以提供基于resnet34等类似backbone的faster_rcnn_fpn系列coco预训练模型吗？

### ISSUE THREAD

**Issue by IvyGongoogle** [PaddlePaddle/PaddleDetection#1213]
您好，由于项目数据特点，目前使用faster_rcnn_r50_vd_fpn系列检测效果较好，但是速度很慢，请问可以提供基于restnet34等类似较小点的backbone在coco上的预训练模型吗？

Thanks.

**Comment by heavengate** [comment]
faster rcnn我们之前没在resnet34上训过，如果你需求模型快一些的话可以试下`yolov3_resnet34.yml`或者移动端模型https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/configs/mobile

**Comment by qingqing01** [comment]
@IvyGongoogle  从COCO上box AP的精度对比RCNN和YOLOv3模型： https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/MODEL_ZOO_cn.md  您确实可以选择YOLOv3系列模型。

当然基于R34的RCNN-FPN模型我们可以训练提供下。

**Comment by IvyGongoogle** [comment]
@qingqing01 我这边模型的目标都是小目标，yolo的模型检测的ap低很多。那麻烦您帮训练下R34的RCNN-FPN模型呀。感谢~
