### ISSUE TITLE
训练yolov3_mobilenet_v1报错

### ISSUE THREAD

**Issue by SangerY** [PaddlePaddle/PaddleDetection#1215]
aistudio上使用最新的PaddleDetection代码，训练yolov3_mobilenet_v1报错
File "/home/aistudio/work/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 88, in __call__
    name=prefix_name + "yolo_loss" + str(i))
TypeError: yolov3_loss() got an unexpected keyword argument 'scale_x_y'
使用2020年5月份那版代码，就没有问题

试了下训练pp_yolo也报错，框架版本是1.8.0，后来看说要安装1.8.4版本，就pip install paddlepaddle-gpu==1.8.4.post107，但报cudnn错误，目前aistudio上不支持训练ppyolo吗？
Error Message Summary:

ExternalError:  Cudnn error, CUDNN_STATUS_BAD_PARAM  at (/paddle/paddle/fluid/operators/batch_norm_op.cu:319)
  [operator < batch_norm > error]

**Comment by heavengate** [comment]
AIStudio上CUDNN版本比较低，你用这个whl包吧 https://paddlemodels.bj.bcebos.com/Paddle3D/paddlepaddle_gpu-0.0.0-cp37-cp37m-linux_x86_64.whl

**Comment by SangerY** [comment]
> AIStudio上CUDNN版本比较低，你用这个whl包吧 https://paddlemodels.bj.bcebos.com/Paddle3D/paddlepaddle_gpu-0.0.0-cp37-cp37m-linux_x86_64.whl

安装后，在aistudio终端训练，只出现了一次迭代信息，就卡着不动了

**Comment by SangerY** [comment]
好的，谢谢。安装了可用，就是有点慢。
