### ISSUE TITLE
Unable to download PP-YOLO_r18vd mobile

### ISSUE THREAD

**Issue by pritul2** [PaddlePaddle/PaddleDetection#1216]
https://paddlemodels.bj.bcebos.com/object_detection/ppyolo_r18vd.pdparams
{"code":"NoSuchKey","message":"The specified key does not exist.","requestId":"ecc13ff5-ceb1-4773-91f7-14d75b473052"}

**Comment by heavengate** [comment]
修复了，重新试下吧~
