### ISSUE TITLE
确定待分析的参数时。报错

### ISSUE THREAD

**Issue by CVdandelion** [PaddlePaddle/PaddleDetection#1217]
我在执行确定待分析参数指令时：python prune.py -c ../../configs/yolov3_r34_voc.yml --print_params
出现这样的报错，请问是什么原因阿

[08-15 16:37:25 MainThread @logger.py:224] Argv: prune.py -c ../../configs/yolov3_r34_voc.yml --print_params
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pandas/core/tools/datetimes.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
Traceback (most recent call last):
  File "prune.py", line 412, in <module>
    main()
  File "prune.py", line 99, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "/home/aistudio/PaddleDetection-release-0.3/ppdet/modeling/architectures/yolo.py", line 147, in build_inputs
    lod_level=inputs_def[key]['lod_level'])) for key in fields])
  File "/home/aistudio/PaddleDetection-release-0.3/ppdet/modeling/architectures/yolo.py", line 147, in <listcomp>
    lod_level=inputs_def[key]['lod_level'])) for key in fields])
KeyError: 'im_info'

**Comment by mmglove** [comment]
您好，麻烦提供下详细复现环境，我这边在paddle=1.8.4,slim=1.1.1,PaddleDetection-release-0.3上运行正常
