### ISSUE TITLE
按照教程训练自定义数据集出现问题

### ISSUE THREAD

**Issue by renjiechao88** [PaddlePaddle/PaddleDetection#1221]
2020-08-15 22:33:23,644-WARNING: paddle.fluid.layers.matrix_nms OP not found, maybe a newer version of paddle is required.
Traceback (most recent call last):
  File "tools/train.py", line 368, in <module>
    main()
  File "tools/train.py", line 69, in main
    check_config(cfg)
  File "C:\Users\rjc\Downloads\PaddleDetection-release-0.4\ppdet\utils\check.py", line 101, in check_config
    assert train_dataset.with_background == eval_dataset.with_background, \
AttributeError: 'list' object has no attribute 'with_background'

数据集布置格式：
dataset
- voc
- VOCdevkit
//绝对路径 VOCdevkit\VOC2007\JPEGImages\20191115_143546_6.jpg
VOCdevkit\VOC2007\Annotations\20191115_143546_6.xml
- test.txt
-trainval.txt
-VOC2007
-Annotations
-ImageSets
-JPEGImages

**Comment by still-wait** [comment]
@renjiechao88 请问是修改的配置文件中dataset配置是什么样的？看着是TrainReader或TestReader中dataset配置错误。

**Comment by renjiechao88** [comment]
> @renjiechao88 请问是修改的配置文件中dataset配置是什么样的？看着是TrainReader或TestReader中dataset配置错误。

这是faster_fpn_reader的配置

TrainReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd']
  dataset:
#  - !COCODataSet
#    image_dir: train2017
#    anno_path: annotations/instances_train2017.json
#    dataset_dir: dataset/coco
  - !VOCDataSet
    dataset_dir: dataset/voc/VOCdevkit
    anno_path: trainval.txt
    use_default_label: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !RandomFlipImage
    prob: 0.5
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    target_size: 800
    max_size: 1333
    interp: 1
    use_cv2: true
  - !Permute
    to_bgr: false
    channel_first: true
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
    use_padded_im_info: false
  batch_size: 1
  shuffle: true
  worker_num: 2
  use_process: false

EvalReader:
  inputs_def:
#    fields: ['image', 'im_info', 'im_id', 'im_shape']
    # for voc
    fields: ['image', 'im_info', 'im_id',  'im_shape', 'gt_bbox', 'gt_class', 'is_difficult']
  dataset:
#    !COCODataSet
#    image_dir: val2017
#    anno_path: annotations/instances_val2017.json
#    dataset_dir: dataset/coco
  - !VOCDataSet
    dataset_dir: dataset/voc/VOCdevkit
    anno_path: test.txt
    use_default_label: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    interp: 1
    max_size: 1333
    target_size: 800
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
    use_padded_im_info: true
  batch_size: 1
  shuffle: false
  drop_empty: false
  worker_num: 2

TestReader:
  inputs_def:
    # set image_shape if needed
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  dataset:
    !ImageFolder
    anno_path: dataset/voc/VOCdevkit/label_list.txt
    use_default_label: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    interp: 1
    max_size: 1333
    target_size: 800
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
    use_padded_im_info: true
  batch_size: 1
  shuffle: false

**Comment by still-wait** [comment]
@renjiechao88 你配置文件设置错误了，不是：
```yaml
dataset:
  - !VOCDataSet
    dataset_dir: dataset/voc/VOCdevkit
    anno_path: test.txt
    use_default_label: false
```
`!VOCDataSet`前面没有`-`。正确的格式如下：
```yaml
dataset:
    !VOCDataSet
    dataset_dir: dataset/voc/VOCdevkit
    anno_path: test.txt
    use_default_label: false
```
