### ISSUE TITLE
配置文件中的参数配置含义

### ISSUE THREAD

**Issue by 1094953403** [PaddlePaddle/PaddleDetection#1224]
配置文件中内容如下 :
 - !AutoAugmentImage
    autoaug_type: v1
这个v1代表的含义我如何查询，有文档方便查询吗，还是说这种配置文件中的参数只能进源码看

**Comment by qingqing01** [comment]
@1094953403   您好，目前只能看源码:  https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/data/transform/operators.py#L607
