### ISSUE TITLE
跑train时提示版本问题

### ISSUE THREAD

**Issue by liangruofei** [PaddlePaddle/PaddleDetection#1225]
12
%run tools/train.py -c configs/ppyolo/ppyolo_r18vd.yml \
                    --eval
运行时长: 92毫秒
结束时间: 2020-08-17 20:21:11
---------------------------------------------------------------------------Exception                                 Traceback (most recent call last)~/PaddleDetection-0.4/tools/train.py in <module>
    366         help='The profiler output file path. (used for benchmark)')
    367     FLAGS = parser.parse_args()
--> 368     main()
~/PaddleDetection-0.4/tools/train.py in main()
    102     with fluid.program_guard(train_prog, startup_prog):
    103         with fluid.unique_name.guard():
--> 104             model = create(main_arch)
    105             if FLAGS.fp16:
    106                 assert (getattr(model.backbone, 'norm_type', None)
~/PaddleDetection-0.4/ppdet/core/workspace.py in create(cls_or_name, **kwargs)
    248                 target = global_config[target_key]
    249                 if isinstance(target, SchemaDict):
--> 250                     kwargs[k] = create(target_key)
    251                 elif hasattr(target, '__dict__'):  # serialized object
    252                     kwargs[k] = target
~/PaddleDetection-0.4/ppdet/core/workspace.py in create(cls_or_name, **kwargs)
    256     # (e.g., list, dict) from within the created module instances
    257     kwargs = copy.deepcopy(kwargs)
--> 258     return cls(**kwargs)
~/PaddleDetection-0.4/ppdet/modeling/anchor_heads/yolo_head.py in __init__(self, conv_block_num, norm_decay, num_classes, anchors, anchor_masks, drop_block, coord_conv, iou_aware, iou_aware_factor, block_size, keep_prob, yolo_loss, spp, nms, weight_prefix_name, downsample, scale_x_y, clip_bbox)
     78                  scale_x_y=1.0,
     79                  clip_bbox=True):
---> 80         check_version("1.8.4")
     81         self.conv_block_num = conv_block_num
     82         self.norm_decay = norm_decay
~/PaddleDetection-0.4/ppdet/utils/check.py in check_version(version)
     75             return
     76         if version_installed[i] < version_split[i]:
---> 77             raise Exception(err)
     78 
     79 
Exception: PaddlePaddle version 1.8.4 or higher is required, or a suitable develop version is satisfied as well. 
Please make sure the version is good with your code.
而我用的aitudio的系统是1.8.0，新建也没有1.8.4的

**Comment by qingqing01** [comment]
@liangruofei 
AIStudio上自带的Paddle版本还没升级。 AiStudio建议fork这个项目 https://aistudio.baidu.com/aistudio/projectdetail/708923 ，参考安转一节：

```
! pip uninstall -y paddlepaddle-gpu
! pip install ~/work/paddlepaddle_gpu-0.0.0-cp37-cp37m-linux_x86_64.whl
```

**Comment by liangruofei** [comment]
ok，thank you


在2020年8月18日 10:59，qingqing01<notifications@github.com> 写道：

@liangruofei
AIStudio上自带的Paddle版本还没升级。 AiStudio建议fork这个项目 https://aistudio.baidu.com/aistudio/projectdetail/708923 ，参考安转一节：

! pip uninstall -y paddlepaddle-gpu

! pip install ~/work/paddlepaddle_gpu-0.0.0-cp37-cp37m-linux_x86_64.whl

**Comment by jerrywgz** [comment]
issue先关闭了，如果还有新的问题可以再提issue，我们会及时跟进
