### ISSUE TITLE
关于输入图片尺寸的问题

### ISSUE THREAD

**Issue by lky-bit** [PaddlePaddle/PaddleDetection#1226]
很多模型在输入的时候会把图片resize成正方的，比如512×512，300×300等等，但是从摄像头采集的图片往往是长方的，比如1920*1080的，resize之后的特征与预训练数据集里面的特征完全不同，训练下来精度会比较差。
我这边有两个想法不知道是否可行：1、将resize的方式改成1920×1080；2、将图片用滑动窗口的方式去输入检测器。
但存在着一些问题：对于1，resize变化后对网络的运行是否有影响？对于2，太过耗时，损失了RPN的优势。
想问下这种情况有什么思路呢？求大佬答疑解惑~~

**Comment by qingqing01** [comment]
@lky-bit  

如果用RCNN系列模型，输入是变长的，不是正方形，参考这里具体说明 https://github.com/PaddlePaddle/PaddleDetection/issues/802#issuecomment-636586448  

因此也是可以配置1920x1080的这个比例大小作为输入的，缺点就是输入的图片越大，需要的显存越大。 预测 大图片也会比较耗时。

如果是YOLO系列模型，后期我们支持下长方形输入吧。

**Comment by lky-bit** [comment]
感谢您的回复，期待早日更新。
