### ISSUE TITLE
两个GPU训练时显存被一下子占满并出现core dump

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleDetection#1231]
CentOS 7.6, Paddlepaddle 1.8.3.post107，PaddleDetection release 0.3, CUDA 10.2，在fine tune YoloV3增强版时，使用单张显卡，可以使用batchsize=6，但是使用两张显卡时（export CUDA_VISIBLE_DEVICES='0,1'），batchsize=8都core dump了，并且两张卡的显存都被一下子占满，提示显存不够，请问这个是什么原因，有没有什么FLAG可以设置，类似TF的allow_growth？

**Comment by jerrywgz** [comment]
paddle目前的显存优化策略是默认开启的，PaddleDetection中的batch_size表示每张卡上的batch_size，可以先尝试下两卡batchsize=6的情况下时候有问题

**Comment by nihuizhidao** [comment]
> paddle目前的显存优化策略是默认开启的，PaddleDetection中的batch_size表示每张卡上的batch_size，可以先尝试下两卡batchsize=6的情况下时候有问题

两张卡batchsize=6是可以的，原来这个参数是每张卡的batchsize，谢谢！
