### ISSUE TITLE
请问可以使用AIstudio的脚本任务模式运行Paddle Detection框架吗？

### ISSUE THREAD

**Issue by ZhengLeon** [PaddlePaddle/PaddleDetection#1247]
如题，notebook上会因为时间问题终端训练，请问脚本模式怎么使用呢，如何配置cocoapi和其他依赖环境？

**Comment by qingqing01** [comment]
@ZhengLeon  可以的。参考这里 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/tutorials/INSTALL_cn.md#%E5%85%B6%E4%BB%96%E4%BE%9D%E8%B5%96%E5%AE%89%E8%A3%85 安装即可。

**Comment by ZhengLeon** [comment]
脚本任务的主文件是py 怎么安装命令行呢?
通过os.system?

**Comment by qingqing01** [comment]
@ZhengLeon 

AIStudio的终端里Ubuntu系统，命令行式操作即可，比如:

<img width="986" alt="图片" src="https://user-images.githubusercontent.com/7845005/90634315-14ac6d80-e25a-11ea-9118-c3f2a96baa43.png">

**Comment by ZhengLeon** [comment]
@qingqing01 谢谢回复，您说的终端好像是notebook模式里才有的吧。
我想用多卡，所以选择的是脚本模式，这样也可以进入终端操作吗？

**Comment by weiexcelpro** [comment]
> 脚本任务的主文件是py 怎么安装命令行呢?
> 通过os.system?

对, os.system('pip install')
