### ISSUE TITLE
自定义训练集出现的问题：Not found annotation file label_list.txt, load voc2012 categories.

### ISSUE THREAD

**Issue by m271019725** [PaddlePaddle/PaddleDetection#1248]
自定义训练集训练了一个模型，但是发现最后预测的时候没有找到该标签文件label_list.txt，而是加载voc2012类别。
现在不知道该如何处理，faster_rcnn_r50_1x.yml中的部分配置如下：
....
_READER_: 'faster_fpn_reader.yml'
TrainReader:
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: trainval.txt
    use_default_label: false
    with_background: false
  batch_size: 1

EvalReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id',  'im_shape', 'gt_bbox', 'gt_class', 'is_difficult']
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: test.txt
    use_default_label: false
    with_background: false

TestReader:
  dataset:
    !ImageFolder
    anno_path: label_list.txt
    use_default_label: false
    with_background: false

文件夹的格式如下：
![image](https://user-images.githubusercontent.com/51936391/90587499-1d765280-e20c-11ea-8ae2-aab7fedb81f2.png)

**Comment by still-wait** [comment]
@m271019725 将`TestReader`中的`anno_path`设置为绝对路径试下。

**Comment by m271019725** [comment]
> @m271019725 将`TestReader`中的`anno_path`设置为绝对路径试下。

可以了，非常感谢
