### ISSUE TITLE
object365冠军模型mAP很低，好像类别没对上

### ISSUE THREAD

**Issue by ckx506772099** [PaddlePaddle/PaddleDetection#1253]
测试object365冠军模型，mAP，感觉是类别没对上，试了issues 760的那个val.json，也不对，image 0检测出类别164，标注是类别1

**Comment by willthefrog** [comment]
用 #760 里的mAP仍然低吗？ 单张image也可能是本来预测就不准啊。

**Comment by ckx506772099** [comment]
用infer结果看着还可以，但是用eval最后的mAP很低

**Comment by willthefrog** [comment]
能否发`TestReader`的配置

**Comment by ckx506772099** [comment]
TestReader?
TestReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  batch_size: 1
  dataset:
    !ImageFolder
    anno_path: ./val.json
  sample_transforms:
  - !DecodeImage
    to_rgb: True
  - !NormalizeImage
    is_channel_first: false
    is_scale: False
    mean:
    - 102.9801
    - 115.9465
    - 122.7717
    std:
    - 1.0
    - 1.0
    - 1.0
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  worker_num: 2

**Comment by ckx506772099** [comment]
我看好像是ppdet/utils/coco_eval.py:80 coco_gt.getCatIds()这里拿到的类别有点问题

**Comment by ckx506772099** [comment]
啊，我找到问题了，十分感谢，是因为json里面categories顺序的问题，我用之前跑出来的bbox.json用760的val.json去算mAP导致结果不行。需要重新跑一遍。

**Comment by ckx506772099** [comment]
因为ppdet/utils/coco_eval.py:80-86这里需要categories是按1-365的顺序排好的
`    cat_ids = coco_gt.getCatIds()

    # when with_background = True, mapping category to classid, like:
    #   background:0, first_class:1, second_class:2, ...
    clsid2catid = dict(
        {i + int(with_background): catid
         for i, catid in enumerate(cat_ids)})`

**Comment by ckx506772099** [comment]
因为ppdet/utils/coco_eval.py:80-86这里需要categories是按1-365的顺序排好的
` cat_ids = coco_gt.getCatIds()
# when with_background = True, mapping category to classid, like:
#   background:0, first_class:1, second_class:2, ...
clsid2catid = dict(
    {i + int(with_background): catid
     for i, catid in enumerate(cat_ids)})`

**Comment by ckx506772099** [comment]
因为ppdet/utils/coco_eval.py:80-86这里需要categories是按1-365的顺序排好的
cat_ids = coco_gt.getCatIds()
# when with_background = True, mapping category to classid, like:
#   background:0, first_class:1, second_class:2, ...
clsid2catid = dict(
    {i + int(with_background): catid
     for i, catid in enumerate(cat_ids)})

**Comment by ckx506772099** [comment]
因为ppdet/utils/coco_eval.py:80-86这里需要categories是按1-365的顺序排好的
` cat_ids = coco_gt.getCatIds()
clsid2catid = dict(
    {i + int(with_background): catid
     for i, catid in enumerate(cat_ids)})`

**Comment by ckx506772099** [comment]
因为ppdet/utils/coco_eval.py:80-86这里需要categories是按1-365的顺序排好的
cat_ids = coco_gt.getCatIds()
clsid2catid = dict(
    {i + int(with_background): catid
     for i, catid in enumerate(cat_ids)})

**Comment by willthefrog** [comment]
好的

**Comment by xiegegege** [comment]
@ckx506772099

**Comment by xiegegege** [comment]
![image](https://user-images.githubusercontent.com/46314656/90711994-a48efd80-e2d4-11ea-9d0d-95fb96435880.png)
@ckx506772099 我们这里测试了下，结果跟文档一样的～
