### ISSUE TITLE
在AISTUDIO上运行ppyolo出错

### ISSUE THREAD

**Issue by ZhengLeon** [PaddlePaddle/PaddleDetection#1259]
按照下面的网址更新了相关包之后
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev

运行：
!CUDA_VISIBLE_DEVICES=0 python tools/train.py -c configs/ppyolo/ppyolo.yml --eval

仍然出错
Error Message Summary:
ExternalError:  Cudnn error, CUDNN_STATUS_BAD_PARAM  (at /paddle/paddle/fluid/operators/batch_norm_op.cu:319)
  [operator < batch_norm > error]

请问现在aistudio上可以运行ppyolo吗，还是说要更新cudnn才行？

**Comment by willthefrog** [comment]
能否发下版本情况及完整报错信息？

**Comment by ZhengLeon** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/708923
和这个里面的相同 而且这个aistudio的repo怎么无法打开呢？
谢谢

**Comment by liuhuiCNN** [comment]
> https://aistudio.baidu.com/aistudio/projectdetail/708923
> 和这个里面的相同 而且这个aistudio的repo怎么无法打开呢？
> 谢谢
关于版本说明，pp-yolo需要使用MatrixNMS，需要Paddle>=1.8.4版本

**Comment by qingqing01** [comment]
@ZhengLeon  Paddle 1.8.4已经发布了，您如果是自己机器上使用，直接安装paddle 1.8.4版本即可，本地的cuDNN注意7.6+。  如果是AIStudio上使用，直接安装这个项目里提供的whl包。

**Comment by ZhengLeon** [comment]
@liuhuiCNN @qingqing01 
好的 谢谢回复！

**Comment by qingqing01** [comment]
@ZhengLeon 如果没问题，就暂且关闭
