### ISSUE TITLE
yolov3 的object365预训练模型可以直接用来预测吗

### ISSUE THREAD

**Issue by ckx506772099** [PaddlePaddle/PaddleDetection#1260]
yolov3 的object365预训练模型可以直接用来预测吗

**Comment by still-wait** [comment]
@ckx506772099 不可以，obj365预训练模型是backbone（ResNet50_vd_dcn）的权重，不包含yolov3的全部权重，所以不能直接用来预测。
可以使用训好的yolov3模型直接做预测：[YOLOv3_ENHANCEMENT.md](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/featured_model/YOLOv3_ENHANCEMENT.md)

**Comment by ckx506772099** [comment]
但是这里训练好的都是80类的，有没有365类的呀

**Comment by still-wait** [comment]
@ckx506772099 yolov3没有直接在obj365上训练过，cascade-rcnn系列模型有obj365上训好的模型：https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/configs/obj365

**Comment by still-wait** [comment]
@ckx506772099 更正一下，https://paddlemodels.bj.bcebos.com/object_detection/ResNet50_vd_dcn_db_obj365_pretrained.tar 这个预训练模型里面有yolo head部分的权重，可以直接拿来预测。

**Comment by ckx506772099** [comment]
> @ckx506772099 更正一下，https://paddlemodels.bj.bcebos.com/object_detection/ResNet50_vd_dcn_db_obj365_pretrained.tar 这个预训练模型里面有yolo head部分的权重，可以直接拿来预测。

我用的就是这个，我应该用那个配置文件呀，试了好几个画出来的都很乱。

**Comment by still-wait** [comment]
> 我用的就是这个，我应该用那个配置文件呀，试了好几个画出来的都很乱。
@ckx506772099 将配置文件中的num_classes改为365，然后测试时设置TestReader为：
```yaml
TestReader:
  batch_size: 1
  dataset:
    !ImageFolder
    anno_path: dataset/obj365/annotations/val.json
```

**Comment by ckx506772099** [comment]
> > 我用的就是这个，我应该用那个配置文件呀，试了好几个画出来的都很乱。
> > @ckx506772099 将配置文件中的num_classes改为365，然后测试时设置TestReader为：
> 
> ```yaml
> TestReader:
>   batch_size: 1
>   dataset:
>     !ImageFolder
>     anno_path: dataset/obj365/annotations/val.json
> ......
> ```

嗯嗯，这个我改了

**Comment by still-wait** [comment]
@ckx506772099 是指标签错乱还是预测box不对？

**Comment by ckx506772099** [comment]
> @ckx506772099 是指标签错乱还是预测box不对？在`TestReader `中设置`with_background: false`了吗

box不对，整张图都是框，标签应该也不对，我看配置文件本来就是，with_background: false

**Comment by still-wait** [comment]
@ckx506772099 是用的`yolov3_r50vd_dcn_obj365_pretrained_coco.yml`配置文件吧？box不正确应该是模型权重没有完全训好，可以试下`configs/obj365`下的模型检测是否正常。我们排查下yolov3在obj365上的训练模型情况。

**Comment by ckx506772099** [comment]
> @ckx506772099 是用的`yolov3_r50vd_dcn_obj365_pretrained_coco.yml`配置文件吧？box不正确应该是模型权重没有完全训好，可以试下`configs/obj365`下的模型检测是否正常。我们排查下yolov3在obj365上的训练模型情况。

嗯嗯，dcn下的几个yolo的配置文件我都试了，configs/obj365下的模型没问题

**Comment by heavengate** [comment]
你好，configs/dcn下面都是在COCO数据集下训练，如果你要尝试dcn目录下的权重，可以参考这个文档给出的配置文件和权重下载链接
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/featured_model/YOLOv3_ENHANCEMENT.md

比如说使用如下命令评估
```
python tools/eval.py -c configs/dcn/yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.yml -o weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.pdparams
```

**Comment by ckx506772099** [comment]
> 你好，configs/dcn下面都是在COCO数据集下训练，如果你要尝试dcn目录下的权重，可以参考这个文档给出的配置文件和权重下载链接
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/featured_model/YOLOv3_ENHANCEMENT.md
> 
> 比如说使用如下命令评估
> 
> ```
> python tools/eval.py -c configs/dcn/yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.yml -o weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.pdparams
> ```

这个应该是80类的吧，我想使用>https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/featured_model/YOLOv3_ENHANCEMENT.md
里面的object365 pretrain来做365类的检测，不知道可不可以。

**Comment by heavengate** [comment]
我们目前没有发布yolov3在obj365上训练的模型，dcn下面都是在COCO上训练的80类的，如果你要做365类的检测，可以到obj365上finetune训练之类的，如果直接检测的话估计只能检测出COCO数据集里包含的80类来

**Comment by ckx506772099** [comment]
> 我们目前没有发布yolov3在obj365上训练的模型，dcn下面都是在COCO上训练的80类的，如果你要做365类的检测，可以到obj365上finetune训练之类的，如果直接检测的话估计只能检测出COCO数据集里包含的80类来

好吧，十分感谢
