### ISSUE TITLE
deploy  python tensorrt 具体教程

### ISSUE THREAD

**Issue by ltm920716** [PaddlePaddle/PaddleDetection#1265]
你好，
在deploy/python路径下有如下使用tensorrt推理提示
![image](https://user-images.githubusercontent.com/12007227/90858810-7a633b80-e3b9-11ea-947d-611d62cc18e2.png)

按照预测库编译教程，直接下载
![image](https://user-images.githubusercontent.com/12007227/90859638-278a8380-e3bb-11ea-8758-85dba2a21f93.png)

下载后解压得到paddle编译好的库文件包含tensorrt的库文件，然后应该怎样做呢？
我把tensortrt的库文件路径添加到 LIBRARY_PATH和LD_LIBRARY_PATH，infer.py的run_mode修改为trt_fp32
运行报错如下：
![image](https://user-images.githubusercontent.com/12007227/90859960-bb5c4f80-e3bb-11ea-9a23-0cae8fe4277a.png)

paddle-gpu的库由pip安装：pip install paddlepaddle_gpu-0.0.0-cp36-cp36m-linux_x86_64.whl -i https://mirror.baidu.com/pypi/simple，且测试正常

请问是不是要源码paddle重新编译，且指定下载的编译好的tensorrt库路径么，源码编译经常卡住，很久不动

请问能麻烦更新一下关于deploy/python 使用tensorrt推理的全流程教程么，谢谢

**Comment by ltm920716** [comment]
@heavengate 好的，谢谢指导

**Comment by wanna-fly** [comment]
> 你好，你下载的预测库文件是用于C++部署预测，如果要使用那个里面的tensorrt版本，需要用`deploy/cpp`下面的方法，`deploy/python`下的是直接用的pip安装的whl包里的paddle，并不会使用你下载的预测库，我们发布的whl包目前是不带tensorrt版本，如果要用python端的tensort预测，需要下载TensorRT本机包含TensorRT编译一下Paddle，可以使用TensorRT5.1.2.2版本，编译命令如下
> 
> ```
> cmake .. \
>   -DWITH_GPU=ON \
>   -DCMAKE_BUILD_TYPE=Release \
>   -DCUDA_ARCH_NAME=Auto \
>   -DTENSORRT_ROOT=~/TensorRT-5.1.2.2
> 
> make -j20
> ```

请问一下docker安装的话有提供编译tensorRT后的paddle镜像文件吗？

**Comment by ltm920716** [comment]
关于python版本推理添加tensorrt环境支持的简单操作进行了简单的整体，可以参考如下链接：[https://polarai.cn/3811.html](url)

@heavengate 请问后期python版本支持int8么，还有可以有tensorrt模型的固化与加载功能集成么，推理时每次在线转换精度等待时间略久，谢谢
