### ISSUE TITLE
使用单卡训练PaddldeDetection中的yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco.yml，在COCO验证集上mAP始终低于1

### ISSUE THREAD

**Issue by nuaaceieyty** [PaddlePaddle/PaddleDetection#1269]
请问我用单卡训练网络，配置文件为yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco.yml，已经按照教程将做了学习率除以8等转换。但是训练了几十万个iter，在COCO验证集上的mAP始终没超过1？请问这是为什么？？

**Comment by nuaaceieyty** [comment]
> 您好，方便把环境信息，paddle，PaddleDetection版本，你修改的配置文件，还有日志这些发一下么

请问能帮我解决下这个问题吗，这个困扰我了一个星期了

**Comment by heavengate** [comment]
```
Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.259
Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.522
Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.225
Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.136
Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.283
Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.322
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.234
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.370
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.389
Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.229
Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.415
Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.469
```

你这个mAP就是25.9%，就是我们常说的`Box AP=25.9` 是一个正常的mAP，我们常说的那个30+，40+那种量级的mAP都是省略了说百分号的，你这个训练是正常的，你可以用你保存的权重做infer看下，效果应该是不错的

**Comment by nuaaceieyty** [comment]
> ```
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.259
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.522
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.225
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.136
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.283
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.322
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.234
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.370
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.389
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.229
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.415
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.469
> ```
> 
> 你这个mAP就是25.9%，就是我们常说的`Box AP=25.9` 是一个正常的mAP，我们常说的那个30+，40+那种量级的mAP都是省略了说百分号的，你这个训练是正常的，你可以用你保存的权重做infer看下，效果应该是不错的

好的，我看下，谢谢啦
