### ISSUE TITLE
车牌类识别训练使用哪种`pretrain_weights`比较合适/高效？

### ISSUE THREAD

**Issue by dklinzh** [PaddlePaddle/PaddleDetection#1270]
请问车牌类识别训练使用哪种模型作`pretrain_weights`比较合适/高效？如果想部署在移动端应该用什么模型训练呢？🙂 望高手指教，谢谢!

**Comment by qingqing01** [comment]
@dklinzh  

移动端模型可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/mobile/README.md

另外，您的移动端设备是哪种类型？

初步推荐，使用YOLOv3，可以使用小一些的backbone，如MobileNetv3。

**Comment by dklinzh** [comment]
移动端是Android和iOS设备，[模型列表](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/mobile/README.md#%E6%A8%A1%E5%9E%8B)中的`Small` `Large`代表什么意思，对模型训练有什么影响？另外能用类似FasterRCNN和MobileNet这样的组合来训练模型吗？非常感谢你的帮助 :)

**Comment by qingqing01** [comment]
@dklinzh  Small，Large是MobileNetv3 backbone的大小区分，精度可以COCO上的mAP、速度可以参考下面的评测结果，比如结合SSD-Lite模型，Large 精度高，速度稍慢。
用FasterRCNN+MobileNetv3也可以，即在: MobileNetV3 Large w/ FPN + Cascade RCNN这组中，使用FasterRCNN。 
但看你车牌类检测效果如何，你可以参考COCO上mAP对比，进行选择。 部署、优化上，单阶段的检测模型适合优化。

**Comment by dklinzh** [comment]
谢谢你的回复，请问COCO上的mAP在哪里可以查看？另外训练完成后的`best_model`和`model_final`有什么区别吗？我看教程里评估、优化等操作中`weights`都是用`model_final`，这是为什么？

**Comment by qingqing01** [comment]
不同小模型的COCO mAP参考链接中的表格 Box AP一栏：

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/mobile/README.md#%E6%A8%A1%E5%9E%8B

<img width="942" alt="图片" src="https://user-images.githubusercontent.com/7845005/91124659-3c745900-e6d2-11ea-8366-d5969026f2ab.png">

best_model是mAP最高的模型。
model_final是最后一个iter的模型。 
你可以看log两个模型的AP差异。

教程里是具体例子吧，可以用best_model。

**Comment by dklinzh** [comment]
模型的mAP是不是越高越好？`best_model`一般都要优于`model_final`，我理解的对吗？

**Comment by qingqing01** [comment]
@dklinzh  你理解的是对的。

**Comment by dklinzh** [comment]
@qingqing01 THX!
