### ISSUE TITLE
yolov3图像输入疑问

### ISSUE THREAD

**Issue by linghaolu** [PaddlePaddle/PaddleDetection#1271]
我看了下yolov3最终的输入到网络中的图像是把原图首先经过 sample_transforms 进行处理，然后通过 batch_transforms 进行处理，输入到网络。
在这里我对batch_transforms 中 RandomShape 的实现有点疑惑，这个实现是单纯的对 图像进行resize到某个尺寸比如 608 * 608，bbox在这里不进行处理。相当于目标尺寸在这一步会出现长宽比跟愿目标不一致。这样不会导致gt bbox 不匹配么？还是说 是由于在 sample_transforms 中 RandomCrop 操作中会对长宽比进行多种变化导致比较好的泛化能力？（我看文章说还有另外一种实现方式，按照图片最长边resize到 608，短边进行等比例变换，然后其余地方填充灰色，这两种实现有什么差异么？）

**Comment by qingqing01** [comment]
预处理流程中包含对gt bbox的normalize， normalize->RandomShape。bbox归一化表示之后，对图片做resize之后，不会影响bbox的归一化位置。

https://github.com/PaddlePaddle/PaddleDetection/blob/5fb219eb0d31c14b12a09009a087dc28d772a048/configs/yolov3_reader.yml#L24-L31



> 我看文章说还有另外一种实现方式，按照图片最长边resize到 608，短边进行等比例变换，然后其余地方填充灰色，这两种实现有什么差异么？

这种是等比例Resize，图片不会变形。在RCNN的模型里用的这种方式。YOLOv3里没有使用，觉得肯能也可以试下。

**Comment by heavengate** [comment]
由于yolov3训练过程中是直接将输入图像resize成比如说608*608来训练的，是非等比例的，我们之前复现基础版yolov3的时候测试非等比例的resize比等比例的resize评估精度高零点几的样子，就沿用的非等比例resize的评估方式，后面我们也测一下等比例resize和非等比例resize在ppyolo模型上的评估精度情况

**Comment by linghaolu** [comment]
> 预处理流程中包含对gt bbox的normalize， normalize->RandomShape。bbox归一化表示之后，对图片做resize之后，不会影响bbox的归一化位置。
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/5fb219eb0d31c14b12a09009a087dc28d772a048/configs/yolov3_reader.yml#L24-L31
> 
> > 我看文章说还有另外一种实现方式，按照图片最长边resize到 608，短边进行等比例变换，然后其余地方填充灰色，这两种实现有什么差异么？
> 
> 这种是等比例Resize，图片不会变形。在RCNN的模型里用的这种方式，但YOLOv3里没有使用。

明白了，之前没细看 gt bbox normalize。
