### ISSUE TITLE
安装与编译linux预测库，存在的问题

### ISSUE THREAD

**Issue by CVdandelion** [PaddlePaddle/PaddleDetection#1278]
git clone https://github.com/paddlepaddle/Paddle
cd Paddle
git clone https://github.com/NVIDIA/nccl.git
cd nccl
make -j4
make install
PADDLE_ROOT=/path/of/paddle
cd Paddle
mkdir build
cd build
cmake -DFLUID_INFERENCE_INSTALL_DIR=$PADDLE_ROOT \
      -DCMAKE_BUILD_TYPE=Release \
      -DWITH_PYTHON=OFF \
      -DWITH_MKL=OFF \
      -DWITH_GPU=OFF  \
      -DON_INFER=ON \
      -DWITH_NCCL=OFF \
      ..
前面的指令执行的都没有问题，可是在进行编译时，出现从github，文件下在不下来的问题，，有时候，一会之后
会出现这个提示，大部分时间都的卡死在Cloning into 'extern_protobuf'...，这句话的地方。
[  0%] Built target extern_zlib
[  0%] Performing download step (git clone) for 'extern_protobuf'
Cloning into 'extern_protobuf'...
Note: checking out '9f75c5aa851cd877fb0d93ccc31b8567a6706546'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 9f75c5aa8 Merge pull request #2337 from sergiocampama/deprecation
Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/benchmark'
Cloning into '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/third_party/protobuf/src/extern_protobuf/third_party/benchmark'...
Submodule path 'third_party/benchmark': checked out '360e66c1c4777c99402cf8cd535aa510fee16573'
查资料好像是什么游历状态，刚开始接触这个，请问是什么原因
之后在便宜的过程中，还会出现错误！

**Comment by qingqing01** [comment]
@CVdandelion 

编译过程会下载并编译很多第三方(third_party)依赖。 您机器上的网速咋样？ 

另外，请问您编译源码的目的是？

**Comment by CVdandelion** [comment]
这个是网速的原因吗？
在电脑端用C++推理部署。不是需要预测库吗？我的G++是7，你们提供的预测库不是G++ 4.8.2 ~ 4.9.4编译的吗？说可能不匹配，
需要自己编译

**Comment by qingqing01** [comment]
@CVdandelion    可以试下:

make VERBOSE=1

看下详细的log，是不是卡住了，或正在编译比较慢等。

**Comment by CVdandelion** [comment]
/usr/bin/cmake -H/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle -B/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/CMakeFiles /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make -f CMakeFiles/extern_zlib.dir/build.make CMakeFiles/extern_zlib.dir/depend
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/CMakeFiles/extern_zlib.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make -f CMakeFiles/extern_zlib.dir/build.make CMakeFiles/extern_zlib.dir/build
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make[2]: Nothing to be done for 'CMakeFiles/extern_zlib.dir/build'.
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
[  0%] Built target extern_zlib
make -f CMakeFiles/extern_protobuf.dir/build.make CMakeFiles/extern_protobuf.dir/depend
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/CMakeFiles/extern_protobuf.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make -f CMakeFiles/extern_protobuf.dir/build.make CMakeFiles/extern_protobuf.dir/build
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make[2]: Nothing to be done for 'CMakeFiles/extern_protobuf.dir/build'.
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
[  1%] Built target extern_protobuf
make -f CMakeFiles/extern_gflags.dir/build.make CMakeFiles/extern_gflags.dir/depend
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/CMakeFiles/extern_gflags.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make -f CMakeFiles/extern_gflags.dir/build.make CMakeFiles/extern_gflags.dir/build
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make[2]: Nothing to be done for 'CMakeFiles/extern_gflags.dir/build'.
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
[  2%] Built target extern_gflags
make -f paddle/fluid/operators/jit/CMakeFiles/copy_kernels_command.dir/build.make paddle/fluid/operators/jit/CMakeFiles/copy_kernels_command.dir/depend
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/paddle/fluid/operators/jit /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/operators/jit /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/operators/jit/CMakeFiles/copy_kernels_command.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make -f paddle/fluid/operators/jit/CMakeFiles/copy_kernels_command.dir/build.make paddle/fluid/operators/jit/CMakeFiles/copy_kernels_command.dir/build
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
[  2%] copy_if_different /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/operators/jit/kernels.h
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/operators/jit && /usr/bin/cmake -E copy_if_different /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/operators/jit/kernels.h.tmp /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/operators/jit/kernels.h
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
[  2%] Built target copy_kernels_command
make -f paddle/fluid/framework/ir/CMakeFiles/copy_paddle_inference_pass_command.dir/build.make paddle/fluid/framework/ir/CMakeFiles/copy_paddle_inference_pass_command.dir/depend
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/paddle/fluid/framework/ir /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/framework/ir /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/framework/ir/CMakeFiles/copy_paddle_inference_pass_command.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make -f paddle/fluid/framework/ir/CMakeFiles/copy_paddle_inference_pass_command.dir/build.make paddle/fluid/framework/ir/CMakeFiles/copy_paddle_inference_pass_command.dir/build
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
[  2%] copy_if_different /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/inference/api/paddle_inference_pass.h
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/framework/ir && /usr/bin/cmake -E copy_if_different /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/inference/api/paddle_inference_pass.h.tmp /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/inference/api/paddle_inference_pass.h
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
[  2%] Built target copy_paddle_inference_pass_command
make -f paddle/fluid/operators/CMakeFiles/copy_pybind_command.dir/build.make paddle/fluid/operators/CMakeFiles/copy_pybind_command.dir/depend
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/paddle/fluid/operators /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/operators /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/operators/CMakeFiles/copy_pybind_command.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make -f paddle/fluid/operators/CMakeFiles/copy_pybind_command.dir/build.make paddle/fluid/operators/CMakeFiles/copy_pybind_command.dir/build
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
[  2%] copy_if_different /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/pybind/pybind.h
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/operators && /usr/bin/cmake -E copy_if_different /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/pybind/pybind.h.tmp /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/pybind/pybind.h
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
[  2%] Built target copy_pybind_command
make -f CMakeFiles/extern_glog.dir/build.make CMakeFiles/extern_glog.dir/depend
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/CMakeFiles/extern_glog.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make -f CMakeFiles/extern_glog.dir/build.make CMakeFiles/extern_glog.dir/build
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make[2]: Nothing to be done for 'CMakeFiles/extern_glog.dir/build'.
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
[  2%] Built target extern_glog
make -f paddle/fluid/framework/CMakeFiles/framework_proto.dir/build.make paddle/fluid/framework/CMakeFiles/framework_proto.dir/depend
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/paddle/fluid/framework /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/framework /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/framework/CMakeFiles/framework_proto.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make -f paddle/fluid/framework/CMakeFiles/framework_proto.dir/build.make paddle/fluid/framework/CMakeFiles/framework_proto.dir/build
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make[2]: Nothing to be done for 'paddle/fluid/framework/CMakeFiles/framework_proto.dir/build'.
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
[  2%] Built target framework_proto
make -f paddle/fluid/platform/CMakeFiles/flags.dir/build.make paddle/fluid/platform/CMakeFiles/flags.dir/depend
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/paddle/fluid/platform /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/platform /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/platform/CMakeFiles/flags.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make -f paddle/fluid/platform/CMakeFiles/flags.dir/build.make paddle/fluid/platform/CMakeFiles/flags.dir/build
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make[2]: Nothing to be done for 'paddle/fluid/platform/CMakeFiles/flags.dir/build'.
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
[  2%] Built target flags
make -f paddle/fluid/string/CMakeFiles/stringpiece.dir/build.make paddle/fluid/string/CMakeFiles/stringpiece.dir/depend
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/paddle/fluid/string /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/string /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/paddle/fluid/string/CMakeFiles/stringpiece.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make -f paddle/fluid/string/CMakeFiles/stringpiece.dir/build.make paddle/fluid/string/CMakeFiles/stringpiece.dir/build
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make[2]: Nothing to be done for 'paddle/fluid/string/CMakeFiles/stringpiece.dir/build'.
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
[  2%] Built target stringpiece
make -f CMakeFiles/extern_eigen3.dir/build.make CMakeFiles/extern_eigen3.dir/depend
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/CMakeFiles/extern_eigen3.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
make -f CMakeFiles/extern_eigen3.dir/build.make CMakeFiles/extern_eigen3.dir/build
make[2]: Entering directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
[  2%] Performing download step (git clone) for 'extern_eigen3'
cd /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/third_party/eigen3/src && /usr/bin/cmake -P /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/third_party/eigen3/tmp/extern_eigen3-gitclone.cmake
Cloning into 'extern_eigen3'...
fatal: unable to access 'https://gitlab.com/libeigen/eigen.git/': gnutls_handshake() failed: Error in the pull function.
Cloning into 'extern_eigen3'...
fatal: unable to access 'https://gitlab.com/libeigen/eigen.git/': gnutls_handshake() failed: Error in the pull function.
Cloning into 'extern_eigen3'...
fatal: unable to access 'https://gitlab.com/libeigen/eigen.git/': gnutls_handshake() failed: Error in the pull function.
-- Had to git clone more than once:
          3 times.
CMake Error at /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/third_party/eigen3/tmp/extern_eigen3-gitclone.cmake:66 (message):
  Failed to clone repository: 'https://gitlab.com/libeigen/eigen.git'


CMakeFiles/extern_eigen3.dir/build.make:90: recipe for target 'third_party/eigen3/src/extern_eigen3-stamp/extern_eigen3-download' failed
make[2]: *** [third_party/eigen3/src/extern_eigen3-stamp/extern_eigen3-download] Error 1
make[2]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
CMakeFiles/Makefile2:194: recipe for target 'CMakeFiles/extern_eigen3.dir/all' failed
make[1]: *** [CMakeFiles/extern_eigen3.dir/all] Error 2
make[1]: Leaving directory '/home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build'
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
这个是输出，我不太懂，是不是连接不到那个网址阿？

**Comment by qingqing01** [comment]
>  Failed to clone repository: 'https://gitlab.com/libeigen/eigen.git'


看错误信息是 Eigen没有clone下来。 你要不手动  git clone  https://gitlab.com/libeigen/eigen.git 到 /home/robot/workspace/PaddleDetection-release-0.3/projects/Paddle/build/third_party/ 中试下

**Comment by CVdandelion** [comment]
$ git clone https://gitlab.com/libeigen/eigen.git 
Cloning into 'eigen'...
fatal: unable to access 'https://gitlab.com/libeigen/eigen.git/': gnutls_handshake() failed: Error in the pull function.
手动好像也不行
但是clone别的地方好像可以
比如：
git clone https://github.com/NVIDIA/nccl.git
这个就可以

**Comment by OliverLPH** [comment]
> $ git clone https://gitlab.com/libeigen/eigen.git
> Cloning into 'eigen'...
> fatal: unable to access 'https://gitlab.com/libeigen/eigen.git/': gnutls_handshake() failed: Error in the pull function.
> 手动好像也不行
> 但是clone别的地方好像可以
> 比如：
> git clone https://github.com/NVIDIA/nccl.git
> 这个就可以

@CVdandelion 看起来是连接gitlab的服务器有问题，可以试下把 [eigen.cmake](https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/external/eigen.cmake#L20) 换成一个可以clone的地址（比如gitee.com）再编译试下。
可以参考下这个issue [#26330](https://github.com/PaddlePaddle/Paddle/issues/26330)
