### ISSUE TITLE
TensorRT support

### ISSUE THREAD

**Issue by PiyalGeorge** [PaddlePaddle/PaddleDetection#1280]
Hi, Awesome work Guys!!!
Is there any TensorRT support available for PP-YOLO ?

**Comment by jerrywgz** [comment]
Sure, PP-YOLO has already supported. We release the inference speed on TensorRT5-FP16 here https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/configs/ppyolo#pp-yolo-1 

To use TensorRT on PP-YOLO, you need to compile PaddlePaddle with TensorRT at first
```
cmake .. \
  -DWITH_GPU=ON \
  -DCMAKE_BUILD_TYPE=Release \
  -DCUDA_ARCH_NAME=Auto \
  -DTENSORRT_ROOT=~/TensorRT-5.1.2.2

make -j20
```
more details you could refer to https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html#id1

Then you could follow the instruction from https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/deploy
