### ISSUE TITLE
0.3分支yolov2_loss

### ISSUE THREAD

**Issue by aboutmei** [PaddlePaddle/PaddleDetection#1288]
您好，
我们在使用自己制作的数据集进行开发任务，网络输出为（4+number_class）* num_anchors原始为（5+number_class），我们出于某种原因不能更改网络的输出维度，所以有想法重写loss和yolo_box以适应此种网络的输出形式，请问应该以什么方式实现这样的输出形式，我们尝试使用python实现静态图下两部分中的loss_function和yolo_box但是并没有work，请问应以怎样正确的思路来更改静态图中的loss与yolo_box，实现我们希望的loss和yolo_box功能来适配这种网络特殊的固定输出形式
十分期望得到你们的回复
祝好

**Comment by willthefrog** [comment]
可以去掉obj loss 的部分，但是工作量比较大，而且不确定最终精度会有多大损失，远比修改网络困难，建议还是修改网络重新训练。

**Comment by justinmeibi** [comment]
您好，
         十分感谢您的回复，这很有助于我们的工作。
         我们可以接受精度带来的损失，但是不可以更改网络，请问应该如何正确去掉这部分loss自己实现接受任意规格的output，以及适应的yolo_box使得可以在PP下训练和推理，使用python是否可以实现还是需要重写C++代码部分，以下是我个人邮箱182560453@st.usst.edu.cn 盼望您的支持与回复！

祝好

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/74410ff9f1e6d56bb962af3a0b5da7122e10d3ba/ppdet/modeling/losses/yolo_loss.py#L94
PaddleDetection里面实现了YOLOv3的拆分loss的，即用小op把yolov3_loss组出来，如果要去掉obj分支的话可以用这里的试下，需要修改一下loss的实现
训练的时候可以使用`-o use_fine_grained_loss=true`指定使用拆分loss训练，预测的时候可能需要参考这里的拆分yolo_box组一下bbox解码过程
https://github.com/PaddlePaddle/PaddleDetection/blob/74410ff9f1e6d56bb962af3a0b5da7122e10d3ba/ppdet/modeling/losses/iou_loss.py#L148
