### ISSUE TITLE
导出预测模型，精度下降

### ISSUE THREAD

**Issue by Eric-YLL** [PaddlePaddle/PaddleDetection#1291]
我用paddleDetection 训练了一个ppyolo模型。然后直接用训练保存的best_model通过tools/infer.py，结果是可以的。
然后我用export_model.py导出模型，使用deploy/python/infer.py调用导出的模型，同样的图，就没输出框了

请问这种情况应该怎么处理？

谢谢

**Comment by still-wait** [comment]
@Eric-YLL 输入图像宽高等长吗？

**Comment by Eric-YLL** [comment]
图像宽高是等长的，以下分别是： 使用保存的模型进行预测， 导出模型， 使用导出的模型预测， 大佬帮忙看下是不是有问题

python tools/infer.py -c ./ppyolo.yml --infer_img=dataset/swjc/JPEGImages/700.bmp -o weights=./output/best_model

python tools/export_model.py -c ./ppyolo.yml --output_dir=./inference_model -o weights=./output/best_model TestReader.inputs_def.image_shape=[3,1600,1600]

python deploy/python/infer.py --model_dir=./inference_model/ppyolo --image_file=dataset/swjc/JPEGImages/700.bmp --use_gpu=True

**Comment by Eric-YLL** [comment]
> @Eric-YLL 输入图像宽高等长吗？

是的[3,1600,1600]

**Comment by still-wait** [comment]
@Eric-YLL 你在`ppyolo_reader.yml`里改过`image_shape: [3, 608, 608]`的shape吗？1600的shape可能太大，试下导出模型不指定`TestReader.inputs_def.image_shape`，看下效果怎么样。

**Comment by Eric-YLL** [comment]
> @Eric-YLL 你在`ppyolo_reader.yml`里改过`image_shape: [3, 608, 608]`的shape吗？1600的shape可能太大，试下导出模型时不指定`TestReader.inputs_def.image_shape`，看下效果怎么样。

是的，的确是尺寸问题，谢谢大佬，赞

**Comment by still-wait** [comment]
@Eric-YLL 好的，先close了，有问题再提issue。

**Comment by Lucky-LR** [comment]
你好，我也是训练了一个ppyolo模型，但是用导出模型预测时会报错，我的指令跟你的是一样的，就是报错。
