### ISSUE TITLE
文档中的参数问题

### ISSUE THREAD

**Issue by AIpioneer** [PaddlePaddle/PaddleDetection#1293]
模型导出文档中的表格没有-o，这个参数。而且按照下图中的示例导出模型，-o这一行主要作用是什么呢，好像没有导出成功。
![image](https://user-images.githubusercontent.com/50724968/91378750-ca2b8200-e853-11ea-9799-ad96acf9a95d.png)

**Comment by still-wait** [comment]
@AIpioneer `-o`是用来在命令行下配置文件里的参数内容的，`-o`后跟着yaml配置文件中字段名，字段名的`=`之后是新的赋值的内容。一般`-o`放在执行命令最后。
你导出不成功是报什么错了吗？

**Comment by AIpioneer** [comment]
第一次执行命令的时候，会提示没有相关文件夹。
建好weights后面的文件夹之后，执行成功了。不过model_final里面是空的，不知道有什么作用

**Comment by still-wait** [comment]
@AIpioneer 
1.请确保`-o weights`指定的模型权重路径是正确的。
2.指定`--output_dir`后，执行完毕后，请检查这个路径下是否生成`__model__`,`__params__`,`infer_cfg.yml`这几个文件，如果有说明导出成功。

**Comment by AIpioneer** [comment]
执行成功了的。单就这个示例而言，感觉给出的 -o weights=output/faster_rcnn_r50_1x/model_final  没有什么作用啊，因为output/faster_rcnn_r50_1x/model_final文件夹是自己建的，里面什么也没有，所以不知道起到了什么作用？
另外你们给出的下面的梳理，weights后面跟的是具体的从云上下载下来的文件。所以两边的示例不太一样呢。
![image](https://user-images.githubusercontent.com/50724968/91380936-c0f0e400-e858-11ea-918e-1a67521e8907.png)

还有...            TestReader.inputs_def.image_shape=[3,300,300]的作用是什么呢？

**Comment by still-wait** [comment]
@AIpioneer 
1.你上面的示例是入门使用文档，包括完整的本地训练与评估，训练好的模型是存放在`output/faster_rcnn_r50_1x/model_final`下的，你这里说的`weights后面跟的是具体的从云上下载下来的文件`是直接使用我们提供的模型权重进行预测，不用重新训练，所以示例是不一样的呀。
2. image_shape是指定预测时，模型输入input的尺寸大小，一般在导出模型时保持默认即可。

**Comment by AIpioneer** [comment]
非常感谢解答！

1. 我并没有进行完整的训练和评估。只是自己建了个空的文件夹。但是好像也导出成功了呢？
2. python3 tools/export_model.py -c configs/ssd/ssd_mobilenet_v1_voc.yml \
        --output_dir=./inference_model \
        -o weights=https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_voc.tar  TestReader.inputs_def.image_shape=[3,300,300] 

zsh: no matches found: TestReader.inputs_def.image_shape=[3,300,300]

你看我执行的时候，加上最后一句，就执行失败了，no matches found。 后来把这一句去掉，就执行成功了。

**Comment by AIpioneer** [comment]
在执行当前页面的serving代码时也报错了
python3 tools/export_serving_model.py -c configs/faster_rcnn_r50_1x.yml \
        --output_dir=./inference_model_serving\
        -o weights=output/faster_rcnn_r50_1x/model_final
Traceback (most recent call last):
  File "tools/export_serving_model.py", line 23, in <module>
    from ppdet.core.workspace import load_config, merge_config, create
ModuleNotFoundError: No module named 'ppdet

**Comment by still-wait** [comment]
> 在执行当前页面的serving代码时也报错了
> python3 tools/export_serving_model.py -c configs/faster_rcnn_r50_1x.yml
> --output_dir=./inference_model_serving
> -o weights=output/faster_rcnn_r50_1x/model_final
> Traceback (most recent call last):
> File "tools/export_serving_model.py", line 23, in
> from ppdet.core.workspace import load_config, merge_config, create
> ModuleNotFoundError: No module named 'ppdet

在当前路径下将python路径加入环境变量中：`export PYTHONPATH=`pwd`:$PYTHONPATH`，再试下呢？
