### ISSUE TITLE
TypeError: Executor requires Program as its Parameter. But you passed in <type 'list'>

### ISSUE THREAD

**Issue by ellinyang** [PaddlePaddle/PaddleDetection#1297]
环境：官方docker ：paddlepaddle-gpu==1.8.4.post97
            paddledetection：release/0.2
背景：用paddle提供的性能分析工具timeline.py分析各阶段耗时
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/analysis_tools/timeline_cn.html
发现每个batch的fetch时间都挺长的
![image](https://user-images.githubusercontent.com/20673237/91400873-04584c00-e873-11ea-990a-b87843e3aceb.png)

想减少fetch的次数，参考paddle官网案例，但报错了：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/multinode_training_improving/dist_training_gpu.html
![image](https://user-images.githubusercontent.com/20673237/91401156-4e413200-e873-11ea-93de-9d7ecea1fffa.png)

错误复现：
将 outs = exe.run(compiled_train_prog, fetch_list=train_values)
改为 exe.run([]) 
试过去掉编译train_prog，也报错了
![image](https://user-images.githubusercontent.com/20673237/91401784-79c41c80-e873-11ea-8f9c-c1fadf1cc7c1.png)

**Comment by still-wait** [comment]
@ellinyang 请描述完整问题

**Comment by still-wait** [comment]
@ellinyang 很高兴您关注性能问题，在静态图模式下，fetch_list里存放每个iter的batch数据，是从Reader里来的，这部分耗时主要是数据预处理复杂，在CPU下比较慢，所以executer一直IO等待。
exe.run()不能设置空，需要添加program和fetch_list。

**Comment by ellinyang** [comment]
> @ellinyang 很高兴您关注性能问题，在静态图模式下，fetch_list里存放每个iter的batch数据，是从Reader里来的，这部分耗时主要是数据预处理复杂，在CPU下比较慢，所以executer一直IO等待。
> exe.run()不能设置空，需要添加program和fetch_list。

fetch_list我的理解是放模型output相关的，和reader相关的主要是feed_list？

**Comment by still-wait** [comment]
@ellinyang DropLocalExeScopes是释放不用的临时变量，减少显存消耗。
看着还是像数据预处理耗时，请再更新一下PaddleDetection到最新release/0.4，可使用多进程训练加速，训练速度会很加快。
