### ISSUE TITLE
Any doc about how to train custom dataset with VOC format ?

### ISSUE THREAD

**Issue by toplinuxsir** [PaddlePaddle/PaddleDetection#1300]
Any doc about how to train custom dataset with VOC format ?
Step by step tutorial ? 
The paddle poor documentation!

**Comment by still-wait** [comment]
@toplinuxsir https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/tutorials/Custom_DataSet.md

**Comment by qingqing01** [comment]
@toplinuxsir  above doc is Chinse.  You also can refer  this simple guide https://github.com/PaddlePaddle/PaddleDetection/issues/1266#issuecomment-678589198

**Comment by toplinuxsir** [comment]
@still-wait  @qingqing01  Thanks
I have read the doc , But my dataset is yolo format , I have converted to VOC Annotation xml format , 
Can you explain the trainval.txt and text.txt  file content meaning ?
Thanks !

**Comment by still-wait** [comment]
@toplinuxsir 
 trainval.txt : training image file list.
test.txt : test image file list.
with extension(relative path),such as:
```
./VOCdevkit/VOC2012/JPEGImages/2008_002069.jpg ./VOCdevkit/VOC2012/Annotations/2008_002069.xml
./VOCdevkit/VOC2012/JPEGImages/2010_005993.jpg ./VOCdevkit/VOC2012/Annotations/2010_005993.xml
./VOCdevkit/VOC2007/JPEGImages/003924.jpg ./VOCdevkit/VOC2007/Annotations/003924.xml
......
```

**Comment by toplinuxsir** [comment]
@still-wait 
Thanks ,!
