### ISSUE TITLE
train ppyolo errror for voc format

### ISSUE THREAD

**Issue by toplinuxsir** [PaddlePaddle/PaddleDetection#1307]
python tools/train.py -c ./configs/ppyolo/ppyolo.yml

The error below : 
```
2020-08-28 11:02:56,336-WARNING: The actual image width: 2304 is not equal to the width: 3456.0 in annotation, and update sample['w'] by actual image width.                            
2020-08-28 11:02:56,633-WARNING: recv endsignal from outq with errmsg[consumer[consumer-796-1] exits for reason[consumer[consumer-796-4] exits for reason[consumer[consumer-796-0] exits
 for reason[consumer[consumer-796-7] exits for reason[consumer[consumer-796-6] exits for reason[consumer[consumer-796-5] exits for reason[consumer[consumer-796-2] failed to map with er
ror:[index 61 is out of bounds for axis 3 with size 52]]]]]]]]                                                                                                                          
2020-08-28 11:02:58,517-WARNING: recv endsignal from outq with errmsg[consumer[consumer-796-3] exits for reason[consumer[consumer-796-1] exits for reason[consumer[consumer-796-4] exits
 for reason[consumer[consumer-796-0] exits for reason[consumer[consumer-796-7] exits for reason[consumer[consumer-796-6] exits for reason[consumer[consumer-796-5] exits for reason[cons
umer[consumer-796-2] failed to map with error:[index 61 is out of bounds for axis 3 with size 52]]]]]]]]]                                                                               
2020-08-28 11:02:58,517-WARNING: Your reader has raised an exception!                                                                                                                   
Exception in thread Thread-2:                                                                                                                                                           
Traceback (most recent call last):                                                                                                                                                      
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner                                                                                                                 
    self.run()                                                                                                                                                                          
  File "/usr/lib/python3.7/threading.py", line 870, in run     
```

**Comment by heavengate** [comment]
你是用的自己的数据集么，看报错信息是标注文件里有问题，标注的尺寸和图像实际尺寸不一样，这样可能导致标注的bbox超出图像范围，可以排查一下annotation里是否有问题
```
2020-08-28 11:02:56,336-WARNING: The actual image width: 2304 is not equal to the width: 3456.0 in annotation, and update sample['w'] by actual image width. 
```

**Comment by toplinuxsir** [comment]
是自己的数据集， 
Annotation：
![image](https://user-images.githubusercontent.com/1111353/91529508-01755e00-e93c-11ea-9572-f8c4f5bd04bc.png)
![image](https://user-images.githubusercontent.com/1111353/91529613-2cf84880-e93c-11ea-86ec-76a0dd766127.png)

**Comment by heavengate** [comment]
> @heavengate
> 是自己的数据集，
> Annotation：
> ![image](https://user-images.githubusercontent.com/1111353/91529508-01755e00-e93c-11ea-9572-f8c4f5bd04bc.png)
> ![image](https://user-images.githubusercontent.com/1111353/91529613-2cf84880-e93c-11ea-86ec-76a0dd766127.png)
> 实际的Width 和 Annotaion 里面的标注完全一样啊

你是不是宽度高度标反了

**Comment by toplinuxsir** [comment]
@heavengate , 没有标反，宽度和高度 和Annotaion里面的一样

**Comment by heavengate** [comment]
```
2020-08-28 11:02:56,336-WARNING: The actual image width: 2304 is not equal to the width: 3456.0 in annotation, and update sample['w'] by actual image width.
```
报错显示图像的真实宽度是2304，标注宽度是3456，你可以用cv2把图像读进来看一下真实宽度和高度，或者用下面的命令看
```
identify -format "%wx%h" photo.jpg
```

**Comment by toplinuxsir** [comment]
@heavengate 

![image](https://user-images.githubusercontent.com/1111353/91533954-510b5800-e943-11ea-8b6c-7a039a78b27c.png)

**Comment by heavengate** [comment]
是不是有其他图像的标反了，可以在下面这个代码里把具体报错的图片路径打印一下
https://github.com/PaddlePaddle/PaddleDetection/blob/bc453fb20086b9466fa052fe08e67b5b7b1fee4a/ppdet/data/transform/operators.py#L126

**Comment by toplinuxsir** [comment]
@heavengate 谢谢！
我找到了部分尺寸不匹配的xml 标注，这部分标注是从Yolo转换过来的。

**Comment by toplinuxsir** [comment]
@heavengate 
为什么identify 命令出来的 宽度和高度，
跟openv 
```
height, width, channel=cv2.imread(file).shape
```
正好相反 ？

**Comment by penghaoran** [comment]
我也遇到了同样的问题，请问你怎么解决的

**Comment by penghaoran** [comment]
为什么我的标注和图片的实际宽高是一样的，但是代码打印出来，程序把宽高都读成了宽。
'im_id': array([136]), 'h': 4032, 'w': 4032.0,

**Comment by toplinuxsir** [comment]
@penghaoran 
自己写了一个脚本，我是从yolo转到VOC 格式，如果你正好也是从yolo转换来的格式，我可以共享给你。

**Comment by penghaoran** [comment]
> @penghaoran
> 自己写了一个脚本，我是从yolo转到VOC 格式，如果你正好也是从yolo转换来的格式，我可以共享给你。

谢谢你的回复哦。我是直接用labelimg生成的VOC, 已经找到原因了，图片太大了，我把图片质量降低后就没出现这个问题。可能是他们源码对高清图处理上有点问题。

**Comment by qingqing01** [comment]
@penghaoran 请问图片多大，我们测试看下。

**Comment by penghaoran** [comment]
> @penghaoran 请问图片多大，我们测试看下。

4032*3024  5MB

**Comment by heavengate** [comment]
> > @penghaoran
> > 自己写了一个脚本，我是从yolo转到VOC 格式，如果你正好也是从yolo转换来的格式，我可以共享给你。
> 
> 谢谢你的回复哦。我是直接用labelimg生成的VOC, 已经找到原因了，图片太大了，我把图片质量降低后就没出现这个问题。可能是他们源码对高清图处理上有点问题。

标注文件里的height和width和python cv2.imead读入的height和width一致么

**Comment by penghaoran** [comment]
> > > @penghaoran
> > > 自己写了一个脚本，我是从yolo转到VOC 格式，如果你正好也是从yolo转换来的格式，我可以共享给你。
> > 
> > 
> > 谢谢你的回复哦。我是直接用labelimg生成的VOC, 已经找到原因了，图片太大了，我把图片质量降低后就没出现这个问题。可能是他们源码对高清图处理上有点问题。
> 
> 标注文件里的height和width和python cv2.imead读入的height和width一致么

是的，标注文件跟我直接用cv2读出来的大小一直，标注文件是labelimg生成的，不是自己转的，应该也没问题。而且，我什么都没改动，仅仅把图片质量降低，大小压缩到1000kb以内后就好了。

**Comment by wangxinxin08** [comment]
> > @penghaoran 请问图片多大，我们测试看下。
> 
> 4032*3024 5MB
使用6282*9000，大小为5.799MB的图片进行测试没有发现h和w读错的问题，代码里面也看过了，没有逻辑错误。我看你打印的
h和w，一个是int，一个是float，你是对代码进行了修改吗？

> 为什么我的标注和图片的实际宽高是一样的，但是代码打印出来，程序把宽高都读成了宽。
> 'im_id': array([136]), 'h': 4032, 'w': 4032.0,

**Comment by penghaoran** [comment]
> > > @penghaoran 请问图片多大，我们测试看下。
> > 
> > 
> > 4032*3024 5MB
> 
> 使用6282*9000，大小为5.799MB的图片进行测试没有发现h和w读错的问题，代码里面也看过了，没有逻辑错误。我看你打印的
> h和w，一个是int，一个是float，你是对代码进行了修改吗？
> 
> > 为什么我的标注和图片的实际宽高是一样的，但是代码打印出来，程序把宽高都读成了宽。
> > 'im_id': array([136]), 'h': 4032, 'w': 4032.0,


@wangxinxin08 没有修改过代码诶，我再试试

**Comment by wangxinxin08** [comment]
> > > > @penghaoran 请问图片多大，我们测试看下。
> > > 
> > > 
> > > 4032*3024 5MB
> > 
> > 
> > 使用6282*9000，大小为5.799MB的图片进行测试没有发现h和w读错的问题，代码里面也看过了，没有逻辑错误。我看你打印的h和w，一个是int，一个是float，你是对代码进行了修改吗？
> > > 为什么我的标注和图片的实际宽高是一样的，但是代码打印出来，程序把宽高都读成了宽。
> > > 'im_id': array([136]), 'h': 4032, 'w': 4032.0,
> 
> @wangxinxin08 没有修改过代码诶，我再试试

好的，如果还有问题的话，可以贴一下Paddle的版本号或者hash号，PaddleDetection的版本号或者hash号以及配置文件，便于定位错误

**Comment by Andy546** [comment]
我也遇到了类似的问题
我的问题原因是用mac的“色彩同步”软件旋转的图片，拷贝到windows做标注，发现看着是旋转的图片，用cv2.imread读时其实为旋转。
解决办法是用cv2把所有图片旋转后，再imwrite，再标注就OK了

**Comment by toplinuxsir** [comment]
I already completely give up, There is scaled-yolov4 more accurate and fast than ppyolo.

**Comment by wowowoll** [comment]
排查了一下问题，有一张图片旋转了， 在
https://github.com/PaddlePaddle/PaddleDetection/blob/59d4eef6dadf47b7405765200c44aaa9f2b3aa5a/ppdet/data/transform/operators.py#L124
增加一个判断 resize 就行了
        h, w, c = im.shape
        print(im.shape)
        if int(sample['h']) != im.shape[0]:
            im = cv2.resize(im, (h, w))
            h, w, c = im.shape
            print(im.shape)
        print(sample['h'], im.shape[0])
