### ISSUE TITLE
模型标签和模型识别的问题

### ISSUE THREAD

**Issue by Viktor-Paul** [PaddlePaddle/PaddleDetection#1309]
最近在做一个关于工业缺陷检测的demo，数据集是自定义的数据集，数据集只有100张，采用了voc编码格式，用了faster_rcnn_r50_fpn_1x.yml配置文件来进行的训练，训练集和测试集是一样的，打算训练一个过拟合的模型。但是训练完成之后，进行测试，发现label_list.txt的标签文件的第一个标签标注的数据识别不了，其他标签的图片都可以。如果把第一标签调换顺序，新的标签第一个识别不了，其他的都可以，不知道是什么原因？查看了label_list.txt的编码格式为utf-8,并不是带用bom的utf-8

**Comment by heavengate** [comment]
faster rcnn的`num_classes`设置需要加上一类背景类，即比如你要检测的缺陷类别是5类，`num_classses`需要设置成6

**Comment by Viktor-Paul** [comment]
> faster rcnn的`num_classes`设置需要加上一类背景类，即比如你要检测的缺陷类别是5类，`num_classses`需要设置成6

明白了，非常感谢，但是为什么要这样设计呢？

**Comment by heavengate** [comment]
faster rcnn的检测原理里分类类别需要设置背景类，最后输出的分类类别里面0也是标识背景类的不会可视化

**Comment by Viktor-Paul** [comment]
> faster rcnn的检测原理里分类类别需要设置背景类，最后输出的分类类别里面0也是标识背景类的不会可视化

明白了，非常感谢您的解答。
