### ISSUE TITLE
BlazeFace有把关键点检测也加入的计划吗？

### ISSUE THREAD

**Issue by yxchng** [PaddlePaddle/PaddleDetection#131]

**Comment by qingqing01** [comment]
@yxchng 感谢关注，后续有计划加~

**Comment by yxchng** [comment]
@qingqing01 大概什麼時候呢？

**Comment by qingqing01** [comment]
@yxchng 内部其实已经实现完成，代码整理之后，可以最近加入，看人力情况，多谢理解~

**Comment by yxchng** [comment]
@qingqing01 好的，我会持续关注的，你们的工作一直都很棒！

**Comment by qingqing01** [comment]
请关注: https://github.com/PaddlePaddle/PaddleDetection/pull/448
