### ISSUE TITLE
ttfnet训练报错

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/PaddleDetection#1314]
使用命令： python tools/train.py -c configs/anchor_free/ttfnet_darknet.yml，然后报错
pred_hm = paddle.tensor.clamp(
AttributeError: module 'paddle' has no attribute 'tensor'
paddle版本为1.8.4，cuda10.1
使用fcos等没有报错现象

**Comment by qingqing01** [comment]
@qiyuezhiguang 我们尽快修复下，可以先换成paddle.fluid.layers.clip

**Comment by qiyuezhiguang** [comment]
非常感谢您周末的高效回复，paddle的效率和便捷性一直让我很钦佩。
将相应代码更换为paddle.fluid.layers.clip后，又报错paddle.arange缺失。
建议您将ttfnet重新运行一遍，并将paddle的版本更新加入。感谢

**Comment by jerrywgz** [comment]
目前ttfnet需要在paddle2.0.0.a0版本下运行，像clamp和arange这两个api都时2.0之后新增的，我们看下能否使用和老版本的paddle兼容的api

**Comment by qiyuezhiguang** [comment]
感谢回复，可以按照官方教程安装的是1.8.4的版本的paddle，如何安装2.0的paddle呢？

**Comment by jerrywgz** [comment]
可以使用pip install paddlepaddle-gpu==2.0.0.a0

**Comment by qiyuezhiguang** [comment]
感谢回复，已经安装了paddle2，并且顺利运行了，但运行的时候有报警提示：
2020-09-02 20:47:58,498-WARNING: paddle.fluid.layers.matrix_nms OP not found, maybe a newer version of paddle is required.
以及：
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.

此外，当数据集选用coco格式时正常运行，但使用voc时训练和推理正常，但eval错误。这种情况同样发生在fcos代码中。错误提示如下：

Traceback (most recent call last):
  File "tools/train.py", line 370, in <module>
    main()
  File "tools/train.py", line 292, in main
    cfg['EvalReader']['dataset'])
  File "/home/zhuhuijie/D/lianxi/PaddleDetection/ppdet/utils/eval_utils.py", line 238, in eval_results
    map_type=map_type)
  File "/home/zhuhuijie/D/lianxi/PaddleDetection/ppdet/utils/voc_eval.py", line 71, in bbox_eval
    gt_boxes = t['gt_bbox'][0]
KeyError: 'gt_bbox'
通过断点跟踪，发现t中没有“gt_bbox”的关键字


yaml设置如下：
architecture: TTFNet
use_gpu: true
max_iters: 5000
log_smooth_window: 20
save_dir: output
snapshot_iter: 100
metric: VOC
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/DarkNet53_pretrained.tar
weights: output/ttfnet_darknet_zhu/best_model
num_classes: 3

TTFNet:
  backbone: DarkNet
  ttf_head: TTFHead

DarkNet:
  norm_type: bn
  norm_decay: 0.0004
  depth: 53
  freeze_at: 1

TTFHead:
  head_conv: 128
  wh_conv: 64
  hm_head_conv_num: 2
  wh_head_conv_num: 2
  wh_offset_base: 16
  wh_loss: GiouLoss

GiouLoss:
  loss_weight: 5.
  do_average: false
  use_class_weight: false

LearningRate:
  base_lr: 0.015
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 11250
    - 13750
  - !LinearWarmup
    start_factor: 0.2
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0004
    type: L2

TrainReader:
  inputs_def:
    fields: ['image', 'ttf_heatmap', 'ttf_box_target', 'ttf_reg_weight']
  dataset:
    !VOCDataSet
    dataset_dir: dataset/fruit
    anno_path: train.txt
    with_background: false
    use_default_label: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !Resize
    target_dim: 512
  - !RandomFlipImage
    prob: 0.5
  - !NormalizeImage
    is_channel_first: false
    is_scale: false
#    mean: [123.675, 116.28, 103.53]
#    std: [58.395, 57.12, 57.375]
  - !Permute
    to_bgr: false
    channel_first: true
  batch_transforms:
  - !Gt2TTFTarget
    num_classes: 3
    down_ratio: 4
  - !PadBatch
    pad_to_stride: 32
  batch_size: 8
  shuffle: true
  worker_num: 16
  bufsize: 4
  use_process: true

EvalReader:
  inputs_def:
    image_shape: [3, 512, 512]
    fields: ['image', 'im_id', 'scale_factor']
  dataset:
    !VOCDataSet
    dataset_dir: dataset/fruit
    anno_path: val.txt
    use_default_label: false
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !Resize
      target_dim: 512
    - !NormalizeImage
      mean: [123.675, 116.28, 103.53]
      std: [58.395, 57.12, 57.375]
      is_scale: false
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
  drop_empty: false
  worker_num: 16
  bufsize: 16

TestReader:
  inputs_def:
    image_shape: [3, 512, 512]
    fields: ['image', 'im_id', 'scale_factor']
  dataset:
    !ImageFolder
    anno_path: dataset/fruit/label_list.txt
    use_default_label: false
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !Resize
      interp: 1
      target_dim: 512
    - !NormalizeImage
      mean: [123.675, 116.28, 103.53]
      std: [58.395, 57.12, 57.375]
      is_scale: false
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1

**Comment by qiyuezhiguang** [comment]
使用 paddlepaddle-gpu==2.0.0.a0训练ttfnet时，使用的coco2017数据，以及官方的配置，因为本人只有2个2080ti显卡，所以将学习率中的base_lr调整为官方的1/4（官方一般使用8个显卡），训练结束后map只有0.2，所花时间为一个晚上。
类似地，训练fruit数据集转化而成的coco集，训练了一个小时，准确率为0，其中hm_loss下降正常，但wh_loss几乎没有下降。
但采用fcos训练fruit的coco类型数据集时，一个小时不到准确率达到了0.9以上。
所以请教一下，ttfnet代码现在是否正常？


使用 paddlepaddle-gpu==2.0.0.a0训练时会提示：
2020-09-03 21:10:19,696-WARNING: paddle.fluid.layers.matrix_nms OP not found, maybe a newer version of paddle is required.
2020-09-03 21:10:20,017-WARNING: /home/zhuhuijie/D/lianxi/PaddleDetection/ppdet/modeling/backbones/fpn.py:108
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
估计这个不影响训练，因为fcos训练很好
感谢！

**Comment by jerrywgz** [comment]
如果使用两卡，需要将训练的总iter数也扩大4倍，包括相应的学习率调整策略。先前在coco数据集上是验证过ttfnet效果的，fruit数据集的话我们验证下
关于下面的warning是paddle2.0版本对elementwise操作的对齐行为发生变化产生的，不会影响训练

**Comment by qiyuezhiguang** [comment]
感谢回复。
由于ttfnet使用voc数据会报错，使用coco数据集正常，下面是voc转coco数据集的脚本，实测 可用，可供参考。
# translate xml to coco_json
# 使用时仅需修改177、178行路径文件
import xml.etree.ElementTree as ET
import os
import json

coco = dict()
coco['images'] = []
coco['type'] = 'instances'
coco['annotations'] = []
coco['categories'] = []

category_set = dict()
image_set = set()

category_item_id = -1
image_id = 20180000000  # VOC中没有这个参数，随便取一个
annotation_id = 0


def addCatItem(name):
    global category_item_id
    category_item = dict()
    category_item['supercategory'] = 'none'
    category_item_id += 1
    category_item['id'] = category_item_id
    category_item['name'] = name
    coco['categories'].append(category_item)
    category_set[name] = category_item_id
    return category_item_id


def addImgItem(file_name, size):
    global image_id
    if file_name is None:
        raise Exception('Could not find filename tag in xml file.')
    if size['width'] is None:
        raise Exception('Could not find width tag in xml file.')
    if size['height'] is None:
        raise Exception('Could not find height tag in xml file.')
    image_id += 1
    image_item = dict()
    image_item['id'] = image_id
    image_item['file_name'] = file_name
    image_item['width'] = size['width']
    image_item['height'] = size['height']
    coco['images'].append(image_item)
    image_set.add(file_name)
    return image_id


def addAnnoItem(object_name, image_id, category_id, bbox):
    global annotation_id
    annotation_item = dict()
    annotation_item['segmentation'] = []
    seg = []
    # bbox[] is x,y,w,h
    # left_top
    seg.append(bbox[0])
    seg.append(bbox[1])
    # left_bottom
    seg.append(bbox[0])
    seg.append(bbox[1] + bbox[3])
    # right_bottom
    seg.append(bbox[0] + bbox[2])
    seg.append(bbox[1] + bbox[3])
    # right_top
    seg.append(bbox[0] + bbox[2])
    seg.append(bbox[1])

    annotation_item['segmentation'].append(seg)

    annotation_item['area'] = bbox[2] * bbox[3]
    annotation_item['iscrowd'] = 0
    annotation_item['ignore'] = 0
    annotation_item['image_id'] = image_id
    annotation_item['bbox'] = bbox
    annotation_item['category_id'] = category_id
    annotation_id += 1
    annotation_item['id'] = annotation_id
    coco['annotations'].append(annotation_item)


def parseXmlFiles(xml_path):
    for f in os.listdir(xml_path):
        if not f.endswith('.xml'):
            continue

        bndbox = dict()
        size = dict()
        current_image_id = None
        current_category_id = None
        file_name = None
        size['width'] = None
        size['height'] = None
        size['depth'] = None

        xml_file = os.path.join(xml_path, f)
        print(xml_file)

        tree = ET.parse(xml_file)
        root = tree.getroot()
        if root.tag != 'annotation':
            raise Exception('pascal voc xml root element should be annotation, rather than {}'.format(root.tag))

        # elem is <folder>, <filename>, <size>, <object>
        for elem in root:
            current_parent = elem.tag
            current_sub = None
            object_name = None

            if elem.tag == 'folder':
                continue

            if elem.tag == 'filename':
                file_name = elem.text
                if file_name in category_set:
                    raise Exception('file_name duplicated')

            # add img item only after parse <size> tag
            elif current_image_id is None and file_name is not None and size['width'] is not None:
                if file_name not in image_set:
                    current_image_id = addImgItem(file_name, size)
                    print('add image with {} and {}'.format(file_name, size))
                else:
                    raise Exception('duplicated image: {}'.format(file_name))
                    # subelem is <width>, <height>, <depth>, <name>, <bndbox>
            for subelem in elem:
                bndbox['xmin'] = None
                bndbox['xmax'] = None
                bndbox['ymin'] = None
                bndbox['ymax'] = None

                current_sub = subelem.tag
                if current_parent == 'object' and subelem.tag == 'name':
                    object_name = subelem.text
                    if object_name not in category_set:
                        current_category_id = addCatItem(object_name)
                    else:
                        current_category_id = category_set[object_name]

                elif current_parent == 'size':
                    if size[subelem.tag] is not None:
                        raise Exception('xml structure broken at size tag.')
                    size[subelem.tag] = int(subelem.text)

                # option is <xmin>, <ymin>, <xmax>, <ymax>, when subelem is <bndbox>
                for option in subelem:
                    if current_sub == 'bndbox':
                        if bndbox[option.tag] is not None:
                            raise Exception('xml structure corrupted at bndbox tag.')
                        bndbox[option.tag] = int(option.text)

                # only after parse the <object> tag
                if bndbox['xmin'] is not None:
                    if object_name is None:
                        raise Exception('xml structure broken at bndbox tag')
                    if current_image_id is None:
                        raise Exception('xml structure broken at bndbox tag')
                    if current_category_id is None:
                        raise Exception('xml structure broken at bndbox tag')
                    bbox = []
                    # x
                    bbox.append(bndbox['xmin'])
                    # y
                    bbox.append(bndbox['ymin'])
                    # w
                    bbox.append(bndbox['xmax'] - bndbox['xmin'])
                    # h
                    bbox.append(bndbox['ymax'] - bndbox['ymin'])
                    print('add annotation with {},{},{},{}'.format(object_name, current_image_id, current_category_id,
                                                                   bbox))
                    addAnnoItem(object_name, current_image_id, current_category_id, bbox)


if __name__ == '__main__':  # 程序入口
    xml_path = '/home/D/lianxi/PaddleDetection/dataset/fruit/Annotations'  # 这是xml文件所在的地址
    json_file = '/home/D/lianxi/PaddleDetection/dataset/fruit/voc.json'  # 这是要生成的json文件
    parseXmlFiles(xml_path)  # 
    json.dump(coco, open(json_file, 'w'))

**Comment by qiyuezhiguang** [comment]
感谢回复。
由于ttfnet使用voc数据会报错，使用coco数据集正常，下面是voc转coco数据集的脚本，实测 可用，可供参考。

translate xml to coco_json
使用时仅需修改177、178行路径文件


import xml.etree.ElementTree as ET
import os
import json

coco = dict()
coco['images'] = []
coco['type'] = 'instances'
coco['annotations'] = []
coco['categories'] = []

category_set = dict()
image_set = set()

category_item_id = -1
image_id = 20180000000  # VOC中没有这个参数，随便取一个
annotation_id = 0


def addCatItem(name):
    global category_item_id
    category_item = dict()
    category_item['supercategory'] = 'none'
    category_item_id += 1
    category_item['id'] = category_item_id
    category_item['name'] = name
    coco['categories'].append(category_item)
    category_set[name] = category_item_id
    return category_item_id


def addImgItem(file_name, size):
    global image_id
    if file_name is None:
        raise Exception('Could not find filename tag in xml file.')
    if size['width'] is None:
        raise Exception('Could not find width tag in xml file.')
    if size['height'] is None:
        raise Exception('Could not find height tag in xml file.')
    image_id += 1
    image_item = dict()
    image_item['id'] = image_id
    image_item['file_name'] = file_name
    image_item['width'] = size['width']
    image_item['height'] = size['height']
    coco['images'].append(image_item)
    image_set.add(file_name)
    return image_id


def addAnnoItem(object_name, image_id, category_id, bbox):
    global annotation_id
    annotation_item = dict()
    annotation_item['segmentation'] = []
    seg = []
    # bbox[] is x,y,w,h
    # left_top
    seg.append(bbox[0])
    seg.append(bbox[1])
    # left_bottom
    seg.append(bbox[0])
    seg.append(bbox[1] + bbox[3])
    # right_bottom
    seg.append(bbox[0] + bbox[2])
    seg.append(bbox[1] + bbox[3])
    # right_top
    seg.append(bbox[0] + bbox[2])
    seg.append(bbox[1])

    annotation_item['segmentation'].append(seg)

    annotation_item['area'] = bbox[2] * bbox[3]
    annotation_item['iscrowd'] = 0
    annotation_item['ignore'] = 0
    annotation_item['image_id'] = image_id
    annotation_item['bbox'] = bbox
    annotation_item['category_id'] = category_id
    annotation_id += 1
    annotation_item['id'] = annotation_id
    coco['annotations'].append(annotation_item)


def parseXmlFiles(xml_path):
    for f in os.listdir(xml_path):
        if not f.endswith('.xml'):
            continue

        bndbox = dict()
        size = dict()
        current_image_id = None
        current_category_id = None
        file_name = None
        size['width'] = None
        size['height'] = None
        size['depth'] = None

        xml_file = os.path.join(xml_path, f)
        print(xml_file)

        tree = ET.parse(xml_file)
        root = tree.getroot()
        if root.tag != 'annotation':
            raise Exception('pascal voc xml root element should be annotation, rather than {}'.format(root.tag))

        # elem is <folder>, <filename>, <size>, <object>
        for elem in root:
            current_parent = elem.tag
            current_sub = None
            object_name = None

            if elem.tag == 'folder':
                continue

            if elem.tag == 'filename':
                file_name = elem.text
                if file_name in category_set:
                    raise Exception('file_name duplicated')

            # add img item only after parse <size> tag
            elif current_image_id is None and file_name is not None and size['width'] is not None:
                if file_name not in image_set:
                    current_image_id = addImgItem(file_name, size)
                    print('add image with {} and {}'.format(file_name, size))
                else:
                    raise Exception('duplicated image: {}'.format(file_name))
                    # subelem is <width>, <height>, <depth>, <name>, <bndbox>
            for subelem in elem:
                bndbox['xmin'] = None
                bndbox['xmax'] = None
                bndbox['ymin'] = None
                bndbox['ymax'] = None

                current_sub = subelem.tag
                if current_parent == 'object' and subelem.tag == 'name':
                    object_name = subelem.text
                    if object_name not in category_set:
                        current_category_id = addCatItem(object_name)
                    else:
                        current_category_id = category_set[object_name]

                elif current_parent == 'size':
                    if size[subelem.tag] is not None:
                        raise Exception('xml structure broken at size tag.')
                    size[subelem.tag] = int(subelem.text)

                # option is <xmin>, <ymin>, <xmax>, <ymax>, when subelem is <bndbox>
                for option in subelem:
                    if current_sub == 'bndbox':
                        if bndbox[option.tag] is not None:
                            raise Exception('xml structure corrupted at bndbox tag.')
                        bndbox[option.tag] = int(option.text)

                # only after parse the <object> tag
                if bndbox['xmin'] is not None:
                    if object_name is None:
                        raise Exception('xml structure broken at bndbox tag')
                    if current_image_id is None:
                        raise Exception('xml structure broken at bndbox tag')
                    if current_category_id is None:
                        raise Exception('xml structure broken at bndbox tag')
                    bbox = []
                    # x
                    bbox.append(bndbox['xmin'])
                    # y
                    bbox.append(bndbox['ymin'])
                    # w
                    bbox.append(bndbox['xmax'] - bndbox['xmin'])
                    # h
                    bbox.append(bndbox['ymax'] - bndbox['ymin'])
                    print('add annotation with {},{},{},{}'.format(object_name, current_image_id, current_category_id,
                                                                   bbox))
                    addAnnoItem(object_name, current_image_id, current_category_id, bbox)


if __name__ == '__main__':  # 程序入口
    xml_path = '/home/zhuhuijie/D/lianxi/PaddleDetection/dataset/fruit/Annotations'  # 这是xml文件所在的地址
    json_file = '/home/zhuhuijie/D/lianxi/PaddleDetection/dataset/fruit/voc.json'  # 这是要生成的json文件
    parseXmlFiles(xml_path)  # 只需要改动这两个参数就行了
    json.dump(coco, open(json_file, 'w'))

**Comment by qingqing01** [comment]
@qiyuezhiguang 感谢~
