### ISSUE TITLE
PPYOLO训练自己的数据集问题

### ISSUE THREAD

**Issue by snovire** [PaddlePaddle/PaddleDetection#1315]
您好，dataset和yml配置按照说明和示例都设置好了，训练时出现unexpected keyword argument 'batch_size'，在ppyolo.yml和ppyolo_reader.yml里面都设置了batch_size=1，请问怎么解决呢？
运行环境python 3.6.5, paddle 1.8.4, cuda10.1, requirement.txt也全部最新安装了
![微信截图_20200830180628](https://user-images.githubusercontent.com/49724561/91656478-94a0c600-eaeb-11ea-986d-164ec5f13dd4.png)

**Comment by qingqing01** [comment]
@snovire  报错信息显示 VOCDataSet里配置有误，看下是否batch_size的缩进有点问题，也麻烦把reader相关配置贴到这里吧
