### ISSUE TITLE
yolo_loss.py 中 _calc_obj_loss() 下的 box_xywh2xyxy() 和 coco 格式不一样

### ISSUE THREAD

**Issue by XiminLin** [PaddlePaddle/PaddleDetection#1318]
`def box_xywh2xyxy(box):`
`    x = box[:, 0]`
`    y = box[:, 1]`
`    w = box[:, 2]`
`    h = box[:, 3]`
`    return fluid.layers.stack(`
`        [`
`            x - w / 2.,`
`            y - h / 2.,`
`            x + w / 2.,`
`            y + h / 2.,`
`        ], axis=1)`

之后在 _calc_obj_loss() 里面 
`gt = box_xywh2xyxy(fluid.layers.squeeze(gt, axes=[0]))`
`ious.append(fluid.layers.iou_similarity(pred, gt))`

这里好像理解 box 中 x,y 为 bounding box 的 中心 x y, 但是其实 coco 数据格式中 x,y 为 左上角 x,y. 在 visualizer.py 的 draw_bbox() 代码中发现确实是左上角 x,y:

`xmin, ymin, w, h = bbox`
`xmax = xmin + w`
`ymax = ymin + h`

这样是否导致 loss 计算不对? 

谢谢

**Comment by qingqing01** [comment]
@XiminLin 

1. COCO的数据格式是xyxy （xmin, ymin, xmax, ymax)没错，在YOLOv3的reader里有个BboxXYXY2XYWH的转换，将gt-box的格式转换为xywh格式。

    参考:

    https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/yolov3_reader.yml#L27-L27

2. loss这块:

   https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/losses/yolo_loss.py#L343

   预测的框是yolo_box的输出，这个输出的格式是 `xyxy （xmin, ymin, xmax, ymax)`，因此计算iou时需要将gt进行转换。

3. draw_bbox函数的问题:

   PaddleDetection里的检测输出一般是multiclassnms，这个输出是xmin, ymin, xmax, ymax格式。可视化之前，一般会经过 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/tools/infer.py#L188 转换，再调用visualize_results，这个函数中调用draw_bbox。

**Comment by XiminLin** [comment]
谢谢, 懂了
