### ISSUE TITLE
x2coco.py 里的逻辑错误

### ISSUE THREAD

**Issue by FibonacciSun** [PaddlePaddle/PaddleDetection#132]
version: release/0.1

遍历跑到 267行时候，如果test_proportion 为0.0，test目录没有创建过，copy会出错

255     count = 1
256     for img_name in os.listdir(args.image_input_dir):
257         if count <= train_num:
258             shutil.copyfile(
259                 osp.join(args.image_input_dir, img_name),
260                 osp.join(args.output_dir + '/train/', img_name))
261         else:
262             if count <= train_num + val_num:
263                 shutil.copyfile(
264                     osp.join(args.image_input_dir, img_name),
265                     osp.join(args.output_dir + '/val/', img_name))
266             else:
267                 shutil.copyfile(
268                     osp.join(args.image_input_dir, img_name),
269                     osp.join(args.output_dir + '/test/', img_name))
270         count = count + 1

**Comment by qingqing01** [comment]
@FibonacciSun 感谢反馈 :) 已在 https://github.com/PaddlePaddle/PaddleDetection/pull/134 修复
