### ISSUE TITLE
对yolov3 inference model输出三个output的feature

### ISSUE THREAD

**Issue by yuanyc06** [PaddlePaddle/PaddleDetection#1324]
我有一个比较古老的yolov3模型，是存好的model和params那种inference model。现在希望对一张输入的图，得到yolov3三个output对应的输出值用作校准用。我看了ppdet里边，如果是有存成的预训练模型（好多文件那种），可以用tools/infer.py配合ppdet/modeling/anchor_heads/yolo_head.py里如下位置，添加几行进行输出。但现在这个古老模型对应的预训练模型早就找不到了，不知用inference model，有什么办法可以达到同样的目的呢？

![图片](https://user-images.githubusercontent.com/14346915/91699544-068a1580-eba7-11ea-90cb-fa155187546b.png)

**Comment by yuanyc06** [comment]
> 我有一个比较古老的yolov3模型，是存好的model和params那种inference model。现在希望对一张输入的图，得到yolov3三个output对应的输出值用作校准用。我看了ppdet里边，如果是有存成的预训练模型（好多文件那种），可以用tools/infer.py配合ppdet/modeling/anchor_heads/yolo_head.py里如下位置，添加几行进行输出。但现在这个古老模型对应的预训练模型早就找不到了，不知用inference model，有什么办法可以达到同样的目的呢？

![图片](https://user-images.githubusercontent.com/14346915/91699373-cd51a580-eba6-11ea-8795-d258ddb3aed9.png)
补充上文提到的ppdet/modeling/anchor_heads/yolo_head.py中的实现方式

**Comment by qingqing01** [comment]
@yuanyc06  可以Python加载inference model，看下这个3个变量的名字，然后对load之后的inference program，找到这3个var，设置persistable=True, 然后通过

```
t  = np.array(fluid.global_scope().find_var(name).get_tensor())
```

试下，能否获取出来。
