### ISSUE TITLE
GPU 占用率问题

### ISSUE THREAD

**Issue by toplinuxsir** [PaddlePaddle/PaddleDetection#1327]
训练命令：
```
set -x CUDA_VISIBLE_DEVICES 0

python tools/train.py -c ./configs/ppyolo/ppyolo.yml

```
CPU 占用率100%
GPU  占用率偶尔100%
如何确认系统使用GPU在训练数据 ？ 
nvidia-smi :

![image](https://user-images.githubusercontent.com/1111353/91793524-04799280-ec4b-11ea-8097-76012fd0ff80.png)

**Comment by jerrywgz** [comment]
现在检测库的模型都是默认在gpu上进行训练的，一般如果gpu利用率为0说明这个时候模型正在等待reader部分做数据预处理，预处理是在cpu上做的，ppyolo中使用了大量预处理会产生一定耗时

**Comment by toplinuxsir** [comment]
@jerrywgz  谢谢！
