### ISSUE TITLE
C++部署预测问题

### ISSUE THREAD

**Issue by Zyttty** [PaddlePaddle/PaddleDetection#1332]
你好，想请教一下，训练完之后使用python接口调用导出的模型预测速度大概是78ms一张图片。但是之后使用封装好的C++接口预测的时候却需要5s一张图片，有碰到这种问题的吗？

**Comment by thunder95** [comment]
我也碰到这个问题了

**Comment by jerrywgz** [comment]
请问下调用python接口调用导出的模型预测速度 这个是用哪儿脚本测试的呢，https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/python 这里给出了通过deploy/python/infer.py测试的不同模型的速度，可以参考下

**Comment by Zyttty** [comment]
> 请问下调用python接口调用导出的模型预测速度 这个是用哪儿脚本测试的呢，https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/python 这里给出了通过deploy/python/infer.py测试的不同模型的速度，可以参考下

**Comment by Zyttty** [comment]
> 请问下调用python接口调用导出的模型预测速度 这个是用哪儿脚本测试的呢，https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/python 这里给出了通过deploy/python/infer.py测试的不同模型的速度，可以参考下

就是使用这个脚本预测的，这个应该是没啥问题的。昨晚发现应该是使用C++接口预测的时候没有调用GPU，在编译的时候已经写成了调用GPU，为啥调用不成功嘞？
