### ISSUE TITLE
【黄埔学院】c++预测库报错

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleDetection#1334]
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html
从这个地址下载的预测库， 希望不编译paddle直接预测

运行命令：
./deploy/cpp/build/main --model_dir=myfiles/yolov3_mobilenet_v1_voc --image_path=/f/myl/Six_Cate/JPEGImages/4_10_2_0003.jpg --use_gpu=True  --run_mode trt_fp16

然后报错：
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0902 00:23:20.161561  2900 analysis_predictor.cc:138] Profiler is deactivated, and no profiling report will be generated.
I0902 00:23:20.179107  2900 analysis_predictor.cc:875] MODEL VERSION: 1.7.2
I0902 00:23:20.179126  2900 analysis_predictor.cc:877] PREDICTOR VERSION: 1.8.4
I0902 00:23:20.179289  2900 analysis_predictor.cc:432] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::framework::ir::PassRegistry::Get(std::string const&) const
3   paddle::inference::analysis::IRPassManager::CreatePasses(paddle::inference::analysis::Argument*, std::vector<std::string, std::allocator<std::string> > const&)
4   paddle::inference::analysis::IRPassManager::IRPassManager(paddle::inference::analysis::Argument*)
5   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::AnalysisPredictor::OptimizeInferenceProgram()
8   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
9   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
10  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
11  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)

----------------------
Error Message Summary:
----------------------
Error: Pass tensorrt_subgraph_pass has not been registered at (/paddle/paddle/fluid/framework/ir/pass.h:201)

Aborted (core dumped)

**Comment by thunder95** [comment]
预测速度也很慢，在同样的fluid运行模式下，cpp是python推理的7倍多

**Comment by willthefrog** [comment]
看上去是编译时没开tensorrt吧，不支持tensorrt预测。

**Comment by thunder95** [comment]
我编译的时候有些tensorrt的路径， 这应该算是打开了吧，还需要其他配置操作吗？
![image](https://user-images.githubusercontent.com/22673612/91924733-0fddc400-ed06-11ea-841b-5a5758aa21e4.png)

**Comment by qingqing01** [comment]
@thunder95  注意从这里 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html 

下载时，需要下载trt编译产出的so。

**Comment by thunder95** [comment]
> @thunder95 注意从这里 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html
> 
> 下载时，需要下载trt编译产出的so。
> 
> 目前看有：
> 
> ubuntu14.04_cuda10.1_cudnn7.6_avx_mkl_trt6
> 
> 针对nv-jetson的:
> 
> nv-jetson-cuda10-cudnn7.5-trt5
> 
> 如果下载的so，不带trt时，不能使用trt模式。

感谢回复，确实是这样，因为我cuda是10.0的，所以优先选了另一个版本。
还有两个问题：
我使用同样的模型和测试图片，用cpp和py分别推理测试，cpp的要慢得非常显著，请问会是哪里有问题？
另外，jetson xavier上能直接pip安装paddle吗？

我等会也测测xavier上cpp的推理速度。

**Comment by thunder95** [comment]
xavier上编译的时候也会有下载失败的问题，我本地网络状态很好。

![image](https://user-images.githubusercontent.com/22673612/91927370-ea53b900-ed0b-11ea-95fa-fc093f551755.png)

**Comment by willthefrog** [comment]
>我使用同样的模型和测试图片，用cpp和py分别推理测试，cpp的要慢得非常显著，请问会是哪里有问题？

具体是怎么执行的呢？

>另外，jetson xavier上能直接pip安装paddle吗？

应该不能吧，pypi好像没有arm版本吧

**Comment by thunder95** [comment]
> > 我使用同样的模型和测试图片，用cpp和py分别推理测试，cpp的要慢得非常显著，请问会是哪里有问题？
> 
> 具体是怎么执行的呢？
> 
> > 另外，jetson xavier上能直接pip安装paddle吗？
> 
> 应该不能吧，pypi好像没有arm版本吧

就按照文档标准姿势执行的
./deploy/cpp/build/main --model_dir=myfiles/yolov3_mobilenet_v1_voc --image_path=/f/myl/Six_Cate/JPEGImages/4_10_2_0003.jpg --use_gpu=True  --run_mode fluid

python deploy/python/infer.py --model_dir=myfiles/yolov3_mobilenet_v1_voc --image_file=/f/myl/Six_Cate/JPEGImages/4_10_2_0003.jpg --use_gpu=True  --run_mode fluid --run_benchmark=True

按上面的命令， cpp:执行时间 65~70ms， python执行时间9~10ms
用了tensorrt fp16之后，cpp能提升到50ms左右

**Comment by willthefrog** [comment]
c++版本是完整执行一次的时间，包括可视化输出等，python 开了`--run_benchmark`的话是多次平均，不包括可视化等后处理，而且有warmup，所以初始化等的时间也不包含，可以不加`--run_benchmark`看看时间是否还有差距。

**Comment by thunder95** [comment]
关闭bench_mark之后11ms左右， @willthefrog 
![image](https://user-images.githubusercontent.com/22673612/91934330-b2ee0800-ed1d-11ea-84f0-fae8a7f2737e.png)

也麻烦看下这个问题：

> xavier上编译的时候也会有下载失败的问题，我本地网络状态很好。
> 
> ![image](https://user-images.githubusercontent.com/22673612/91927370-ea53b900-ed0b-11ea-95fa-fc093f551755.png)

**Comment by xiegegege** [comment]
@thunder95 那个ext-yaml-cpp-download-*.log里的内容具体是什么呢？还有我这里测试了tensorrt预测用 ubuntu14.04_cuda10.1_cudnn7.6_avx_mkl_trt6 这个预测包可以正常运行的，cuda10.0也是可以用这个包的

**Comment by willthefrog** [comment]
可以参考[这个 issue](https://github.com/PaddlePaddle/PaddleDetection/issues/1162)

**Comment by thunder95** [comment]
> 可以参考[这个 issue](https://github.com/PaddlePaddle/PaddleDetection/issues/1162)

对ext-yaml-cpp离线下载后，这一步跳过去了， 但是编译的时候仍然有错
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_dnn.so.3.4.6: error adding symbols: File in wrong format

是因为我的xavier上gcc版本太高了吗？
@willthefrog

**Comment by willthefrog** [comment]
确定依赖的这些类库是arm版本吗？

**Comment by thunder95** [comment]
> 确定依赖的这些类库是arm版本吗？ 自己编译的还是下载的呢？

下载的这个 nv-jetson-cuda10-cudnn7.5-trt5

**Comment by thunder95** [comment]
@willthefrog 
编译的问题解决了，直接用的自带的opencv，改了些源码。
在xavier上测试cpp，貌似要正常一些，python还没测试，因为需要编译很久

fluid模式: 1000-times-run consume time: 58319.5ms
trt_fp32模式: 1000-times-run consume time: 37433.8ms
trt_fp16模式: 1000-times-run consume time: 37353ms

始终还是不明白为啥pc上相比python测试cpp的推理耗时会多那么多

**Comment by willthefrog** [comment]
这个问题不是很好troubleshoot，可能是环境差异

**Comment by qingqing01** [comment]
@thunder95 我们测试看下，你是

模型: yolov3_mobilenet_v1_voc
环境: nv-jetson

问题是 Python测试比cpp的推理耗时慢，对吧？

**Comment by thunder95** [comment]
> @thunder95 我们测试看下，你是
> 
> 模型: yolov3_mobilenet_v1_voc
> 环境: nv-jetson
> 
> 问题是 Python测试比cpp的推理耗时慢，对吧？

不是的
模型是 yolov3_mobilenet_v1_voc
环境是普通的pc，显卡是RTX 2070super
fluid模式测试结果py(10ms左右)， cpp(70ms左右)
 
目前还在xavier上编译paddle，也遇到了问题，还在解决中，所以nv上还跑不了py代码
ps： 编译Built target jit_kernel_helper， 下载eigen的时候一直卡主

@qingqing01  辛苦，谢谢

**Comment by thunder95** [comment]
在xavier上对模型进行测试：
	cpp+fp32： 37781.8(略下降)
	cpp+fp16： 37025.6(只有很轻微的提升)
	py+fluid:  120.02673864364624 ms
	py+fp32: 112.50798225402832 ms
	py+fp16: 21.82523012161255 ms

可能确实paddle用py运行起来效率更高吧，而且挺显著的 @qingqing01

**Comment by thunder95** [comment]
@qingqing01  多谢青青大佬，已在pc和xavier测试，cpp比py快了很多，符合预期。给paddledetection团队点赞。
