### ISSUE TITLE
ssd_mobilenet_v1_voc对图片尺寸有限制吗？

### ISSUE THREAD

**Issue by penghaoran** [PaddlePaddle/PaddleDetection#1335]
为什么我用1080*1440的图片训练没问题，但是用4032*3024的图片训练时，就会出问题。

**Comment by willthefrog** [comment]
原则上是没限制的，预处理会resize到网络需要的大小，具体是什么问题呢？

**Comment by penghaoran** [comment]
> 原则上是没限制的，预处理会resize到网络需要的大小，具体是什么问题呢？


我把图片压缩小了就没问题了。
一开始我的图片差不多5MB一张，然后程序读出来的图片im_w 和im_h的值都是宽，后来把图片压缩到500kb就正常了。

**Comment by penghaoran** [comment]
> 原则上是没限制的，预处理会resize到网络需要的大小，具体是什么问题呢？

再请问下，每一个class大概采集多少张图片，能够训练出来比较好的模型。我目前每个class 拍了30张图片，但是训练出来的模型识别效果不是很好。

**Comment by willthefrog** [comment]
这个没有固定的规则，rule of thumb是1k左右吧
