### ISSUE TITLE
代码中怎么添加--config

### ISSUE THREAD

**Issue by 17695996717** [PaddlePaddle/PaddleDetection#1336]
报错：argparse.ArgumentError: argument --config: conflicting option string: --config

**Comment by 17695996717** [comment]
parser.add_argument(
        "-c",
        "--config",
        default=r"D:\studydemo\YOLO\PaddleDetection-release-0.4\configs\ppyolo\ppyolo.yml",
        type=str,
        help='configuration file to use')

这样在train.py立添加为什么不对

**Comment by willthefrog** [comment]
默认的arg parser已经有这个参数了，`argparse`不接受重复的参数名。

**Comment by 17695996717** [comment]
> 参数名重复了，默认的arg parser已经有这个参数了

那除了命令行就只能改代码了吗，太不友好了吧

**Comment by willthefrog** [comment]
你希望实现的是什么呢？这个功能已经支持了啊

**Comment by 17695996717** [comment]
> 你希望实现的是什么呢？这个功能已经支持了啊
不通过命令行在哪添加config路径呢？

**Comment by 17695996717** [comment]
> 你希望实现的是什么呢？这个功能已经支持了啊

**Comment by 17695996717** [comment]
> 你希望实现的是什么呢？这个功能已经支持了啊

不通过命令行在哪添加config路径呢？
