### ISSUE TITLE
训练速度非常慢，worker_num 无论多大只有一个cpu process在工作

### ISSUE THREAD

**Issue by penghaoran** [PaddlePaddle/PaddleDetection#1342]
use_process设置为true，worker_num 从2到24设置了一个遍，但是只看到一个process有cpu使用率。
硬件是AI studio的高级版，显存32G CPU：4  RAM :32GB
训练非常慢，而且GPU的使用率一直为0%，GPU的显存占用为12GB 也没有用满。
batch_size设置从32到256试了一个遍，都一样。

**Comment by penghaoran** [comment]
![image](https://user-images.githubusercontent.com/18494590/92018884-5b38b680-ed88-11ea-9d07-7804b8a43e1e.png)

**Comment by penghaoran** [comment]
![image](https://user-images.githubusercontent.com/18494590/92019052-96d38080-ed88-11ea-90e3-b7f06d8402e9.png)

**Comment by penghaoran** [comment]
感觉比我自己的1070，batch_size=32 还慢。。。

**Comment by still-wait** [comment]
@penghaoran 请问使用的是哪个模型？

**Comment by penghaoran** [comment]
> @penghaoran 请问使用的是哪个模型？

ssd_mobilenet_v1_voc

**Comment by qingqing01** [comment]
ssd_mobilenet_v1_voc本身GPU训练很快的。

>  训练非常慢，而且GPU的使用率一直为0%

一直是0%？ 麻烦确认下训练时，是否开启了GPU模式？是如何启动的？

**Comment by penghaoran** [comment]
启动的命令：python3 -u tools/train.py -c configs/ssd/ssd_mobilenet_v1_voc.yml --eval

![image](https://user-images.githubusercontent.com/18494590/92068215-e6419d00-edd8-11ea-8847-747959319e56.png)

**Comment by penghaoran** [comment]
> ssd_mobilenet_v1_voc本身GPU训练很快的。
> 
> > 训练非常慢，而且GPU的使用率一直为0%
> 
> 一直是0%？ 麻烦确认下训练时，是否开启了GPU模式？是如何启动的？

开启了的

**Comment by penghaoran** [comment]
> ssd_mobilenet_v1_voc本身GPU训练很快的。
> 
> > 训练非常慢，而且GPU的使用率一直为0%
> 
> 一直是0%？ 麻烦确认下训练时，是否开启了GPU模式？是如何启动的？

GPU只有显存占用，没有使用率，看起来像数据IO阻塞了，请问下数据IO的代码在哪个文件或者配置下，还有就是DataLoader的配置代码在哪里？因为源码文件太多了，没找到。

**Comment by qingqing01** [comment]
@penghaoran 

链接Paddle的DataLoader:

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/architectures/ssd.py#L124

数据预处理源码:

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/data/reader.py#L156


也可以尝试减少数据预处理看看会不会提高。训练打印的loss和s/step的日志能发下吗？

**Comment by penghaoran** [comment]
![wx_camera_1599053989343](https://user-images.githubusercontent.com/18494590/92072337-9f0cd980-ede3-11ea-9c2a-f7059c82e421.jpg)

**Comment by penghaoran** [comment]
> @penghaoran
> 
> 链接Paddle的DataLoader:
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/architectures/ssd.py#L124
> 
> 数据预处理源码:
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/data/reader.py#L156
> 
> 也可以尝试减少数据预处理看看会不会提高。训练打印的loss和s/step的日志能发下吗？

我忘记保存了，只找到一张手机拍的log

**Comment by penghaoran** [comment]
> @penghaoran
> 
> 链接Paddle的DataLoader:
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/architectures/ssd.py#L124
> 
> 数据预处理源码:
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/data/reader.py#L156
> 
> 也可以尝试减少数据预处理看看会不会提高。训练打印的loss和s/step的日志能发下吗？

![image](https://user-images.githubusercontent.com/18494590/92082031-970a6500-edf6-11ea-9baa-1d5e36d63f82.png)
最新跑的 2个小时才500 iter

**Comment by penghaoran** [comment]
> @penghaoran 请检查你的当前运行机器是否有问题，你本地速度正常吗？在P40单卡上测试如下：（配置文件没有改动）
> ![image](https://user-images.githubusercontent.com/15628872/92086092-48f86000-edfc-11ea-99a1-1f0e3557b3bc.png)

在我本地速度是正常的，请问下这个release0.4在paddle1.8.0上可以正常使用吗？因为AI studio提供的就是1.8.0+python3.7版本

**Comment by penghaoran** [comment]
> @penghaoran 请检查你的当前运行机器是否有问题，你本地速度正常吗？在P40单卡上测试如下：（配置文件没有改动）
> ![image](https://user-images.githubusercontent.com/15628872/92086092-48f86000-edfc-11ea-99a1-1f0e3557b3bc.png)

可以麻烦知道你当前的paddle版本，cuda版本，cuddn版本吗？

**Comment by penghaoran** [comment]
> @penghaoran 请检查你的当前运行机器是否有问题，你本地速度正常吗？在P40单卡上测试如下：（配置文件没有改动）
> ![image](https://user-images.githubusercontent.com/15628872/92086092-48f86000-edfc-11ea-99a1-1f0e3557b3bc.png)

还有一个问题，这个和我图片的大小有关吗？我一共451张图片，每张1.2Mb.

**Comment by still-wait** [comment]
@penghaoran 我在paddle 1.7.1，cuda 10.1，cudnn 7.6下实验是没问题的，你图片原始尺寸很大吗？这个是消耗内存的一个原因，多进程和batch_size大了之后耗时会增加很多。

**Comment by Charlie-Wilson0211** [comment]
问题解决了吗，遇到同样的问题了，
环境 : conda+cudatoolkit 10.0.130 + cudnn 7.6.5 + paddlepaddle-gpu 1.8.4.post107
使用paddledet自带的yolov4_cspdarknet_voc.yml数据集，数据为aistudio提供的VOC数据集

python tools/train.py -c configs/yolov4/yolov4_cspdarknet_voc.yml  --eval
运行时评估，训练1000次迭代后，开始评估
2020-09-27 06:14:16,811-INFO: Test iter 0
2020-09-27 06:42:16,672-INFO: Test iter 100
速度慢，GPU使用率为0却占着显存，仅仅是使用CPU

**Comment by jinxuan777** [comment]
同样的问题，单核CPU100%使用率，GPU0%，感觉是Data Loader卡住了
hub.baidubce.com/paddlepaddle/paddle:1.8.5-gpu-cuda10.0-cudnn7 
PaddleDetection {release/0.4}
试了PPYOLO、SSD都一样

**Comment by WenLinLliu** [comment]
一样的问题，CPU单核吃满了，多核不运行，GPU利用率低
