### ISSUE TITLE
pp-yolo剪枝的时候报通道错误

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleDetection#1346]
对已训练好的的模型进行剪枝，但是报错了卷积核通道数量不匹配的问题

python prune.py -c ../../myconfigs/my_ppyolo.yml --pruned_params "yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights" --pruned_ratios="0.2,0.3,0.4"

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2798, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1581, in conv2d
    "data_format": data_format,
  File "/home/aistudio/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 166, in _conv_bn
    bias_attr=False)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 241, in _detection_block
    name='{}.{}.spp.conv'.format(name, j))
  File "/home/aistudio/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 335, in _get_outputs
    name=self.prefix_name + "yolo_block.{}".format(i))
  File "/home/aistudio/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 389, in get_loss
    outputs = self._get_outputs(input, is_train=True)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 85, in build
    gt_score, targets)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 159, in train
    return self.build(feed_vars, mode='train')
  File "prune.py", line 100, in main
    train_fetches = model.train(feed_vars)
  File "prune.py", line 412, in <module>
    main()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 1228, the input's shape is [32, 1228, 13, 13]; the filter's channels is 1843, the filter's shape is [512, 1843, 1, 1]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:1228 != filter_dims[1] * groups:1843.] at (/paddle/paddle/fluid/operators/conv_op.cc:94)
  [operator < conv2d > error]

**Comment by thunder95** [comment]
使用量化时，也卡在这里:
2020-09-03 13:05:11,212-WARNING: recv endsignal from outq with errmsg[consumer[consumer-d84-5] failed to map with error:[target0 not in samples]]

**Comment by heavengate** [comment]
你好，配置文件有修改啥么，方便贴一下你的配置文件么

**Comment by thunder95** [comment]
@heavengate 
你要， 能正常训练，就是剪枝和量化都会有问题。配置请见附件：

[yml.zip](https://github.com/PaddlePaddle/PaddleDetection/files/5166485/yml.zip)

**Comment by heavengate** [comment]
> @heavengate
> 你要， 能正常训练，就是剪枝和量化都会有问题。配置请见附件：
> 
> [yml.zip](https://github.com/PaddlePaddle/PaddleDetection/files/5166485/yml.zip)

`yolo_block.0.1.0.conv.weights`这个权重前面有SPP模块，通道剪裁时候通道会匹配不上，不要裁剪这个权重就可以了，ppyolo里只有这个权重前面有SPP模块

**Comment by thunder95** [comment]
> > @heavengate
> > 你要， 能正常训练，就是剪枝和量化都会有问题。配置请见附件：
> > [yml.zip](https://github.com/PaddlePaddle/PaddleDetection/files/5166485/yml.zip)
> 
> `yolo_block.0.1.0.conv.weights`这个权重前面有SPP模块，通道剪裁时候通道会匹配不上，不要裁剪这个权重就可以了，ppyolo里只有这个权重前面有SPP模块

@heavengate 
我尝试去掉这一层，仍旧不成功， 也作了其他尝试，比如随便只剪裁其他任何一层： yolo_block.0.0.0.conv.weights， 或 yolo_block.2.1.1.conv.weights， 仍旧会报这个错误

```
----------------------
Error Message Summary:
----------------------
Error: The input's size along the split dimension must be evenly divisible by Attr(num_or_sections). But received Attr(num_or_sections) = 24, input(X)'s shape = [32, 50, 4], Attr(dim) = 0.
  [Hint: Expected input_axis_dim % num == 0, but received input_axis_dim % num:8 != 0:0.] at (/paddle/paddle/fluid/operators/split_op.h:41)
  [operator < split > error]
```

`!python prune.py -c ../../myconfigs/my_ppyolo_prune.yml --pruned_params \
    "yolo_block.0.0.0.conv.weights" \
    --pruned_ratios="0.3"`

**Comment by Fauny** [comment]
同样问题。+1

@thunder95 解决了吗？

**Comment by heavengate** [comment]
> ----------------------
> Error Message Summary:
> ----------------------
> Error: The input's size along the split dimension must be evenly divisible by Attr(num_or_sections). But received Attr(num_or_sections) = 24, input(X)'s shape = [32, 50, 4], Attr(dim) = 0.
>   [Hint: Expected input_axis_dim % num == 0, but received input_axis_dim % num:8 != 0:0.] at (/paddle/paddle/fluid/operators/split_op.h:41)
>   [operator < split > error]

这个错误不是剪枝的错误，是不是你修改了batch_size, `ppyolo.yml`里的`YOLOv3Loss.batch_size`和`ppyolo_reader.yml`里的`TrainReader.batch_size`不一致

**Comment by thunder95** [comment]
> > ## Error Message Summary:
> > Error: The input's size along the split dimension must be evenly divisible by Attr(num_or_sections). But received Attr(num_or_sections) = 24, input(X)'s shape = [32, 50, 4], Attr(dim) = 0.
> > [Hint: Expected input_axis_dim % num == 0, but received input_axis_dim % num:8 != 0:0.] at (/paddle/paddle/fluid/operators/split_op.h:41)
> > [operator < split > error]
> 
> 这个错误不是剪枝的错误，是不是你修改了batch_size, `ppyolo.yml`里的`YOLOv3Loss.batch_size`和`ppyolo_reader.yml`里的`TrainReader.batch_size`不一致

@heavengate 您说的没错， 剪枝训练的时候因为显存溢出之前改batch的时候忘改了reader里面， 现在可以正常训练了，非常感谢！
