### ISSUE TITLE
ppyolo训练配置文件问题

### ISSUE THREAD

**Issue by 17695996717** [PaddlePaddle/PaddleDetection#1349]
1.num_classes:  类别数必须+1个背景类吗？
2.  TrainReader:里的
    - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
    random_inter: True
这里是指训练时图片随机缩放到这些尺寸吗？
3.IouLoss:
  loss_weight: 2.5
  max_height: 608
  max_width: 608
这里的max_heigh指的是什么

**Comment by heavengate** [comment]
1. yolo不需要包含背景类，数据集多少类num_classes就设置为多少
2. 是的，这个是训练时的数据增强方法，不影响评估，预测这些
3. 这里的max_height和max_width就是RandomShape里面的最大值，用于处理计算IoULoss的时候初始化grid

**Comment by 17695996717** [comment]
> 1. yolo不需要包含背景类，数据集多少类num_classes就设置为多少
> 2. 是的，这个是训练时的数据增强方法，不影响评估，预测这些
> 3. 这里的max_height和max_width就是RandomShape里面的最大值，用于处理计算IoULoss的时候初始化grid

感谢！如果不希望训练时进行尺寸缩放，按原图尺寸进行训练，是屏蔽RandomShape吗，还是填一个固定值即可，这样改的话iouloss里面的w,h该怎么改呢？

**Comment by still-wait** [comment]
@17695996717 如果要按照原图尺寸进行训练，可删除RandomShape，但是长宽都要padding到32的倍数，可参考这个issue：https://github.com/PaddlePaddle/PaddleDetection/issues/1302#issuecomment-681967974

**Comment by 17695996717** [comment]
> @17695996717 如果要按照原图尺寸进行训练，可删除RandomShape，但是长宽都要padding到32的倍数，可参考这个issue：[#1302 (comment)](https://github.com/PaddlePaddle/PaddleDetection/issues/1302#issuecomment-681967974)

  batch_transforms:
  - !RandomShape
    sizes: [960]
    random_inter: True

这里直接填32的倍数960吗？
