### ISSUE TITLE
pp-yolo部署在jetson上失败

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleDetection#1350]
命令： ./deploy/cpp/build/main --model_dir=myfiles/my_ppyolo --image_path=/d/hl_files/4_10_2_0003.jpg --use_gpu=True  --run_mode fluid

在pc上运行正常
在xavier上运行paddledetection之前的yolo系列也正常

报错信息：
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0903 14:34:09.529490  1351 analysis_predictor.cc:88] Profiler is deactivated, and no profiling report will be generated.
I0903 14:34:09.581341  1351 analysis_predictor.cc:845] MODEL VERSION: 0.0.0
I0903 14:34:09.581487  1351 analysis_predictor.cc:847] PREDICTOR VERSION: 1.6.2

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > paddle::platform::GetTraceBackString<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int)
1   paddle::framework::OpRegistry::CreateOp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::variant<boost::blank, int, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::variant<boost::blank, int, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >)
2   paddle::framework::OpRegistry::CreateOp(paddle::framework::OpDesc const&)
3   paddle::framework::NaiveExecutor::CreateOps(paddle::framework::ProgramDesc const&, int, bool)
4   paddle::framework::NaiveExecutor::Prepare(paddle::framework::Scope*, paddle::framework::ProgramDesc const&, int, bool)
5   paddle::AnalysisPredictor::PrepareExecutor()
6   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
7   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
8   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)

----------------------
Error Message Summary:
----------------------
Error: Operator matrix_nms has not been registered
  [Hint: op_info_ptr should not be null.] at (/home/paddle/hg/paddle/paddle/fluid/framework/op_info.h:113)

Aborted (core dumped)

**Comment by thunder95** [comment]
直接从官网下载的fluid_inference包也不能解决
也尝试了从源码直接编译安装，也同样的错误

**Comment by still-wait** [comment]
@thunder95 请问下载的是1.8.4版本或develop版本的fluid_inference包吗？

**Comment by thunder95** [comment]
> @thunder95 请问下载的是1.8.4版本或develop版本的fluid_inference包吗？

fluid_inference我用的是这个nv-jetson-cuda10-cudnn7.5-trt5
paddle直接clone的最新版本然后编译安装的，clone下来之后没有切换分支
@still-wait

**Comment by still-wait** [comment]
@thunder95 感谢反馈，我们定位一下问题

**Comment by chalsliu** [comment]
有可能是因为nv-jetson-cuda10-cudnn7.5-trt5这个版本比较低，近期会发布新的版本

**Comment by thunder95** [comment]
> 有可能是因为nv-jetson-cuda10-cudnn7.5-trt5这个版本比较低，近期会发布新的版本

@chalsliu 
前面是用的nv-jetson-cuda10-cudnn7.5-trt5版本， 但是我后来也用了paddle的源码编译， 在build.sh把inference路径给改成这样：PADDLE_DIR=/d/hl_files/Paddle/build/fluid_inference_install_dir
然后报的同样的错，我编译源码时的参数不对吗难道？

**Comment by cryoco** [comment]
您好，这个问题是旧版本预测库尚不支持pp-yolo新增的算子matrix_nms导致的，您可以试一下[2.0.0-beta版本](https://paddle-inference-lib.bj.bcebos.com/2.0.0-beta0-nv-jetson-cuda10-cudnn7.5-trt5/fluid_inference.tgz)的预测库哈

**Comment by thunder95** [comment]
> 您好，这个问题是旧版本预测库尚不支持pp-yolo新增的算子matrix_nms导致的，您可以试一下[2.0.0-beta版本](https://paddle-inference-lib.bj.bcebos.com/2.0.0-beta0-nv-jetson-cuda10-cudnn7.5-trt5/fluid_inference.tgz)的预测库哈

@cryoco 您好，感谢回复， 刚测试了下这个算子可以使用了，只是推理预测时间非常慢（fp32: 77ms， fp16: 81ms），比py慢了很多， 可以看我提的这个issue，非pp_yolo目前已经解决了。 
[](https://github.com/PaddlePaddle/PaddleDetection/issues/1334)

**Comment by cryoco** [comment]
> > 您好，这个问题是旧版本预测库尚不支持pp-yolo新增的算子matrix_nms导致的，您可以试一下[2.0.0-beta版本](https://paddle-inference-lib.bj.bcebos.com/2.0.0-beta0-nv-jetson-cuda10-cudnn7.5-trt5/fluid_inference.tgz)的预测库哈
> 
> @cryoco 您好，感谢回复， 刚测试了下这个算子可以使用了，只是推理预测时间非常慢（fp32: 77ms， fp16: 81ms），比py慢了很多， 可以看我提的这个issue，非pp_yolo目前已经解决了。
> #1334

您可以测试一下不开TRT的性能

**Comment by thunder95** [comment]
> > > 您好，这个问题是旧版本预测库尚不支持pp-yolo新增的算子matrix_nms导致的，您可以试一下[2.0.0-beta版本](https://paddle-inference-lib.bj.bcebos.com/2.0.0-beta0-nv-jetson-cuda10-cudnn7.5-trt5/fluid_inference.tgz)的预测库哈
> > 
> > 
> > @cryoco 您好，感谢回复， 刚测试了下这个算子可以使用了，只是推理预测时间非常慢（fp32: 77ms， fp16: 81ms），比py慢了很多， 可以看我提的这个issue，非pp_yolo目前已经解决了。
> > #1334
> 
> 您可以测试一下不开TRT的性能

@cryoco 不开trt在40ms左右， 预期开了trt不应该超过40， 在30左右应该算正常

**Comment by JensenHJS** [comment]
给的这个预测库2.0.0-beta版本的预测库，是不是有问题？里面没有cmakelists.txt文件，有一个cmakecache文件。然后cmake报错了

**Comment by jiweibo** [comment]
使用2.0rc1的预测库

测试pp-yolo在xavier nx下的性能

`./build/main --model_dir /output/ppyolo/ --image_path ../../demo/000000014439_640x640.jpg --use_gpu=True --run_mode trt_fp32 -run_benchmark
`
trt_fp32 耗时为19.40ms


`./build/main --model_dir /output/ppyolo/ --image_path ../../demo/000000014439_640x640.jpg --use_gpu=True --run_mode trt_fp16 -run_benchmark
`
trt_fp16 耗时为18.32ms


`./build/main --model_dir /output/ppyolo/ --image_path ../../demo/000000014439_640x640.jpg --use_gpu=True --run_mode fluid -run_benchmark
`
fluid耗时为111.11ms
