### ISSUE TITLE
ppyolo训练报错

### ISSUE THREAD

**Issue by 17695996717** [PaddlePaddle/PaddleDetection#1352]
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Input(ImgSize) dim[0] and Input(X) dim[0] should be same.
  [Hint: Expected dim_imgsize[0] == dim_x[0], but received dim_imgsize[0]:8 != dim_x[0]:7.] at (D:\1.8.4\paddle\paddle\fluid\operators\detection\yolo_box_op.cc:56)
  [operator < yolo_box > error]

**Comment by still-wait** [comment]
@17695996717 如果要按照原图尺寸进行训练，长宽都要padding到32的倍数

**Comment by heavengate** [comment]
看报错是`ppyolo.yml`文件里的`YOLOv3Loss.batch_size`和`ppyolo_reader.yml`里的`TrainReader.batch_size`是一个配置的是8一个配置的是7
