### ISSUE TITLE
ppyolo模型恢复，停止后继续训练问题

### ISSUE THREAD

**Issue by 17695996717** [PaddlePaddle/PaddleDetection#1354]
恢复模型只需要改train.py这里的default成保存模型的路径就好了吗？

 parser.add_argument(
        "-r",
        "--resume_checkpoint",
        default=r'',
        type=str,
        help="Checkpoint path for resuming training.")

**Comment by still-wait** [comment]
@17695996717 
指定-r携带权重路径即可
```shell
python tools/train.py -c xxx -r output/xxx
```
参数解释在https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/tutorials/GETTING_STARTED_cn.md中可以找到。
另，我们为用户准备了一系列完整的文档，可阅读：https://paddledetection.readthedocs.io/

**Comment by 17695996717** [comment]
> @17695996717
> 指定-r携带权重路径即可
> 
> ```shell
> python tools/train.py -c xxx -r output/xxx
> ```
> 
> 参数解释在[https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/tutorials/GETTING_STARTED_cn.md中可以找到。](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/tutorials/GETTING_STARTED_cn.md%E4%B8%AD%E5%8F%AF%E4%BB%A5%E6%89%BE%E5%88%B0%E3%80%82)
> 另，我们为用户准备了一系列完整的文档，可阅读：https://paddledetection.readthedocs.io

第一个链接失效了亲

**Comment by still-wait** [comment]
@17695996717 重新点击一下

**Comment by 17695996717** [comment]
> @17695996717 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/tutorials/GETTING_STARTED_cn.md

如果我不想用命令行运行，在代码里怎么改呢？

**Comment by still-wait** [comment]
> > @17695996717 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/tutorials/GETTING_STARTED_cn.md
> 
> 如果我不想用命令行运行，在代码里怎么改呢？
```python
parser.add_argument(
        "-r",
        "--resume_checkpoint",
        default=None,
        type=str,
        help="Checkpoint path for resuming training.")
```
default改为resume的路径就行。
