### ISSUE TITLE
有可以可视化feature map的工具吗？

### ISSUE THREAD

**Issue by IvyGongoogle** [PaddlePaddle/PaddleDetection#1359]
如题，请问，咱们有可以可视化feature map的工具吗？我现在使用了paddleDet的gcb 但是想可视化下feature map看下gcb有没有学到attention的部分。

期待回复，
Thanks

**Comment by qingqing01** [comment]
@IvyGongoogle 目前没有可视化feature map的工具。如果想自己把feature map特征获取出来，做可视化的，是可以讲feature map对应的名字，tools/train.py中的exe.run的fetch_list中。

**Comment by IvyGongoogle** [comment]
谢谢，自己已经解决这个问题，参考https://zhuanlan.zhihu.com/p/89095411
