### ISSUE TITLE
x2coco.py转换得时候出现mixed_20.jpg.xml

### ISSUE THREAD

**Issue by 1084667371** [PaddlePaddle/PaddleDetection#1362]
将voc数据集转换为coco数据集的时候
python tools/x2coco.py --dataset_type voc --voc_anno_dir dataset/fruit/ --voc_anno_list dataset/fruit/train.txt --voc_label_list dataset/fruit/label_list.txt --voc_out_name voc_train.json
出现
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/fruit/JPEGImages/mixed_20.jpg.xml'
是多了个后缀吗？

**Comment by still-wait** [comment]
@1084667371 `--voc_anno_dir`路径指向的是只有xml标注文件的路径，如果train.txt里文件名不是以xml结尾，会自动填充`.xml`，所以请重新整理一遍`--voc_anno_dir`文件夹，使其只有xml文件。

**Comment by 1084667371** [comment]
好的，谢谢
