### ISSUE TITLE
是否有计划支持facenet?或者有同等替代模型？

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleDetection#1364]
想请教qingqing @qingqing01  老师一个问题，我们Paddledetection有计划支持facenet么？

目前我们人脸识别都是使用MTCNN+facenet，MTCNN可以换成pyramidbox，但是facenet好像没有对应的PD替代模型，其实也就是个face embedding的模型，不知道百度是否有自己的模型，或者有基于paddledetection的facenet实现？

谢谢

**Comment by qingqing01** [comment]
@nihuizhidao 在PaddleDetection中目前没有支持人脸识别的计划，可以参考: https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/slimfacenet  注意，这是一个人脸识别模型，不是压缩流程。当然，backbone也是可以替换的。

**Comment by nihuizhidao** [comment]
多谢，我们尝试下，但是这个readme里面的预训练模型，没有添加下载链接。。。
![image](https://user-images.githubusercontent.com/26674015/92344326-beb04480-f0f8-11ea-9619-a4da85840d10.png)

**Comment by qingqing01** [comment]
@nihuizhidao 预训练模型可以参考: https://github.com/PaddlePaddle/PaddleSlim/issues/440#issuecomment-688575542

**Comment by nihuizhidao** [comment]
多谢~
