### ISSUE TITLE
pp_yolo训练时的验证

### ISSUE THREAD

**Issue by 17695996717** [PaddlePaddle/PaddleDetection#1367]
我的test.txt有一千五百张图，但是训练期间的验证只验证了796张，是因为验证集中无标签的不参与计算吗？

2020-09-07 12:14:48,393-INFO: Save model to output\ppyolo\25000.
2020-09-07 12:15:06,457-INFO: Test iter 0
2020-09-07 12:15:17,167-INFO: Test iter 100
2020-09-07 12:15:28,024-INFO: Test iter 200
2020-09-07 12:15:37,472-INFO: Test iter 300
2020-09-07 12:15:44,973-INFO: Test iter 400
2020-09-07 12:15:51,961-INFO: Test iter 500
2020-09-07 12:15:58,941-INFO: Test iter 600
2020-09-07 12:16:05,893-INFO: Test iter 700
2020-09-07 12:16:12,416-INFO: Test finish iter 796
2020-09-07 12:16:12,417-INFO: Total number of images: 796, inference time: 11.913625020992773 fps.
2020-09-07 12:16:12,417-INFO: Start evaluate...
2020-09-07 12:16:13,406-INFO: Accumulating evaluatation results...
2020-09-07 12:16:13,564-INFO: mAP(0.50, 11point) = 9.47
2020-09-07 12:16:13,568-INFO: Save model to output\ppyolo\best_model.
2020-09-07 12:16:21,591-INFO: Best test box ap: 9.467123035476748, in iter: 25000

**Comment by qingqing01** [comment]
> Total number of images: 796

你的eval时batch-size是1吗？PPYOLO默认的drop_emty是False:

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/ppyolo/ppyolo_reader.yml#L84

您在加载eval数据时，有什么warning吗

**Comment by 17695996717** [comment]
> > Total number of images: 796
> 
> 你的eval时batch-size是1吗？PPYOLO默认的drop_emty是False:
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/ppyolo/ppyolo_reader.yml#L84
> 
> 您在加载eval数据时，有什么warning吗

没报错呀，这是我的eval配置文件：
EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id']
    num_max_boxes: 50
  dataset:
      !VOCDataSet
      anno_path: test.txt
      use_default_label: false
      dataset_dir: D:/data/PPdet/PaddleDetection-release-0.4/dataset/voc
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 960
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !PadBox
      num_max_boxes: 50
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
  drop_empty: false
  worker_num: 8
  bufsize: 4

**Comment by qingqing01** [comment]
@17695996717 

在计算总共测试了多少images时，有考虑此image的是否有检测的bbox， 

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/utils/eval_utils.py#L172

 也可能是一些图片没有bbox，输出是空的。您也可以在上述代码前面打印看下。

**Comment by 17695996717** [comment]
> @17695996717
> 
> 在计算总共测试了多少images时，有考虑此image的是否有检测的bbox，
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/utils/eval_utils.py#L172
> 
> 也可能是一些图片没有bbox，输出是空的。您也可以在上述代码前面打印看下。

谢谢，您这里指的是我的验证集数据没有gt吗，我的数据确实有很多空标签，这些数据不参与计算吗？

**Comment by qingqing01** [comment]
@17695996717 你上面是eval流程，是验证集。 这里指的不是gt，是检测的输出。这些数据参与计算，只是检测出来是空的。

**Comment by 17695996717** [comment]
> @17695996717 你上面是eval流程，是验证集。 这里指的不是gt，是检测的输出。这些数据参与计算，只是检测出来是空的。

就是说我1500张图，检测出来了796张吗？

**Comment by qingqing01** [comment]
@17695996717 

建议打印debug看下，

在下面代码附近，打印看下`res`，看下`res`中是否有`im_id`, im_id的shape是[batch_size, 1]，通过im_id算出来的图片总数，是否和`images_num`相等。

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/utils/eval_utils.py#L172

**Comment by 17695996717** [comment]
> @17695996717
> 
> 建议打印debug看下，
> 
> 在下面代码附近，打印看下`res`，看下`res`中是否有`im_id`, im_id的shape是[batch_size, 1]，通过im_id算出来的图片总数，是否和`images_num`相等。
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/utils/eval_utils.py#L172

好的谢谢

**Comment by 17695996717** [comment]
> > @17695996717
> > 建议打印debug看下，
> > 在下面代码附近，打印看下`res`，看下`res`中是否有`im_id`, im_id的shape是[batch_size, 1]，通过im_id算出来的图片总数，是否和`images_num`相等。
> > https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/utils/eval_utils.py#L172
> 
> 好的谢谢

        # parse eval fetches
        extra_keys = []
        if cfg.metric == 'COCO':
            extra_keys = ['im_info', 'im_id', 'im_shape']
        if cfg.metric == 'VOC':
            extra_keys = ['gt_bbox', 'gt_class', 'is_difficult']
        if cfg.metric == 'WIDERFACE':
            extra_keys = ['im_id', 'im_shape', 'gt_bbox']

亲，我是的VOC验证方式，米有im_id

**Comment by 17695996717** [comment]
> > > @17695996717
> > > 建议打印debug看下，
> > > 在下面代码附近，打印看下`res`，看下`res`中是否有`im_id`, im_id的shape是[batch_size, 1]，通过im_id算出来的图片总数，是否和`images_num`相等。
> > > https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/utils/eval_utils.py#L172
> > 
> > 
> > 好的谢谢
> 
> ```
>     # parse eval fetches
>     extra_keys = []
>     if cfg.metric == 'COCO':
>         extra_keys = ['im_info', 'im_id', 'im_shape']
>     if cfg.metric == 'VOC':
>         extra_keys = ['gt_bbox', 'gt_class', 'is_difficult']
>     if cfg.metric == 'WIDERFACE':
>         extra_keys = ['im_id', 'im_shape', 'gt_bbox']
> ```
> 
> 亲，我是的VOC验证方式，米有im_id

if len(res['bbox'][1]) == 0:
       has_bbox = False
images_num += len(res['bbox'][1][0]) if has_bbox else 1

这里res['bbox'][1][0]指的是检出的框的数量吗？那检出2个，Images_num不就加上了框的数量了吗？
