### ISSUE TITLE
安装paddleDetection运行环境时出错

### ISSUE THREAD

**Issue by liuzhongwei425** [PaddlePaddle/PaddleDetection#137]
1. 执行以下语句：
git clone https://github.com/cocodataset/cocoapi.git
cd cocoapi/PythonAPI
pip install Cython
make install

2. 报错：
............
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 44, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-NDVoIX/matplotlib-3.2.0rc1/setup.py", line 136
    raise IOError(f"Failed to download jquery-ui.  Please download "
                                                                   ^
SyntaxError: invalid syntax

3. 请问如何处理？

**Comment by qingqing01** [comment]
看错误像是安装python-matplotlib时出错，可以直接尝试先安装 `python -m pip install matplotlib` 试下。 或者直接 `pip install pycocotools` 试下。

**Comment by liuzhongwei425** [comment]
已用anaconda方式安装成功，谢谢

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=liuzhongwei425&uid=liuzhongwei425%40hotmail.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Aliuzhongwei425%40hotmail.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
liuzhongwei425
邮箱：liuzhongwei425@hotmail.com

签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制

在2019年12月28日 15:34，qingqing01<mailto:notifications@github.com> 写道：

看错误像是安装python-matplotlib时出错，可以直接尝试先安装 python -m pip install matplotlib 试下。 或者直接 pip install pycocotools 试下。
