### ISSUE TITLE
如何在ai studio上upgrade cudnn？

### ISSUE THREAD

**Issue by Juanal-Xu** [PaddlePaddle/PaddleDetection#1372]
在ai studio上使用ttfnet.yaml跑train.py，版本框架为paddlepaddle-gpu==2.0.0a0，报错显示cudnn为7.3，版本太低与paddle2.0不兼容，请问如何在ai studio上upgrade cudnn？

**Comment by jerrywgz** [comment]
和aistudio的负责人沟通了下，会在9.10号将cudnn版本升级到7.6.5版本

**Comment by Juanal-Xu** [comment]
> 和aistudio的负责人沟通了下，会在9.10号将cudnn版本升级到7.6.5版本

thanks a lot
