### ISSUE TITLE
How to label a single category with labelme and instance segmentation?

### ISSUE THREAD

**Issue by hande6688** [PaddlePaddle/PaddleDetection#1373]
How to label a single category with labelme and instance segmentation? There are cat, cat, cat, cat0, cat1, cat2 or cat-0, cat-1, cat-2, etc. which annotation method is used?thank you!

I use cat-0, cat-1, cat-2 for annotation, and use labelme2coco to convert annotations.json, where the annotation is [], what's the matter?

**Comment by jerrywgz** [comment]
Actually I guess if you want to use instance segmentation, you do not need to define cat1 or cat2 in the annotation and one class is enough.
Any way, the labelme2coco is update to https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/tools/x2coco.py . You could try it first and if there is still problem you could upload you annotation in labelme format and we will debug later.
