### ISSUE TITLE
ppyolo配置文件问题

### ISSUE THREAD

**Issue by 17695996717** [PaddlePaddle/PaddleDetection#1376]
你好小P，关于ppyolo配置文件我有以下几个问题
1.IouLoss:
  loss_weight: 2.5
  max_height: 608
  max_width: 608
IouAwareLoss:
  loss_weight: 1.0
  max_height: 608
  max_width: 608
这两个loss中的wh尺寸可以修改吗，修改更大有什么问题吗？
2.  batch_transforms:
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
    random_inter: True
这里的sizes是指输入图像进行随机缩放吗？我不想进行随机缩放，只想按原图尺寸输入网络，那这里可以固定某个尺寸吗，或者关闭随机缩放。我输入网络的尺寸在哪里修改呢？这里的最大尺寸与上面的loss中尺寸需要对应吗？

3.YOLOv3Loss:
  batch_size: 4
  ignore_thresh: 0.7
  scale_x_y: 1.05
  label_smooth: false
  use_fine_grained_loss: true
  iou_loss: IouLoss
  iou_aware_loss: IouAwareLoss
这里loss的batch size与下面TrainReader的batchsize必须保持一致吗？下面的worker_num与bufsize是什么意思与关系呢？
  batch_size: 4
  shuffle: true
  mixup_epoch: 120000
  drop_last: true
  worker_num: 8
  bufsize: 4

**Comment by willthefrog** [comment]
1. 同输入最大尺寸对应
2. 可以，但是会影响训练效果。需要对应
3. 必须一致， 多进程loader的进程数和缓存队列大小。

**Comment by 17695996717** [comment]
> 1. 同输入最大尺寸对应
> 2. 可以，但是会影响训练效果。需要对应
> 3. 必须一致， 多进程loader的进程数和缓存队列大小。

如何去掉随机尺寸输入呢？random_inter: True置成False吗？如果增大随机尺寸就在608后面增加就可以了吗？这几个尺寸的数量是固定的吗？
我要计算我自己数据集的anchors，ppyolo有计算anchors的代码吗？

**Comment by willthefrog** [comment]
可以使用`ResizeImage`，参考eval和test reader。尺寸是经验值，也可以根据需要修改。
目前ppdet使用的都是默认anchor，没有实现anchor计算的代码。

**Comment by 17695996717** [comment]
> 可以使用`ResizeImage`，参考eval和test reader。尺寸是经验值，也可以根据需要修改。
> 目前ppdet使用的都是默认anchor，没有实现anchor计算的代码。
!RandomShape
sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
random_inter: True
这里的random_inter是什么意思？开启或关闭吗

- !ResizeImage
   target_size: 608
   interp: 2
这里的interp是什么意思？

**Comment by willthefrog** [comment]
对的。
`interp`指定插值算法

**Comment by 17695996717** [comment]
> 对的。
> `interp`指定插值算法

好的谢谢您，不同数据集的anchors对模型精度影响还蛮大的

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen此issue
