### ISSUE TITLE
blazeface单次推理的ap是多少? 因为实际使用中不可能这样多尺度测试

### ISSUE THREAD

**Issue by luoqing94** [PaddlePaddle/PaddleDetection#138]

**Comment by qingqing01** [comment]
@luoqing94 

BlazeFace-Origina， 多尺度如文档 Easy/Medium/Hard:  0.915/0.892/0.797，单尺度: 0.845/0.847/0.735.

多谢关注，我们最近在文档里提供下单尺度结果吧。

**Comment by luoqing94** [comment]
> @luoqing94
> 
> BlazeFace-Origina， 多尺度如文档 Easy/Medium/Hard: 0.915/0.892/0.797，单尺度: 0.845/0.847/0.735.
> 
> 多谢关注，我们最近在文档里提供下单尺度结果吧。

如果能注明各个尺度的结果，就更好了， 比如原图单次推理结果， 长边640结果，320结果。 会更具有参考性， 感谢。

**Comment by qingqing01** [comment]
> 单尺度: 0.845/0.847/0.735.

训练使用的是640x640训练，这个单尺度也是640x640的评估结果。

**Comment by luoqing94** [comment]
> > 单尺度: 0.845/0.847/0.735.
> 
> 训练使用的是640x640训练，这个单尺度也是640x640的评估结果。

了解了，谢谢回复！
