### ISSUE TITLE
pp-yolo 剪枝参数选择问题

### ISSUE THREAD

**Issue by Fauny** [PaddlePaddle/PaddleDetection#1382]
模型：ppyolo
训练结果：Best test box ap: 0.7949662589940378 'loss': '26.862640' ,  导出模型大小：188.1M。经测试模型比较满意
敏感度分析：获得敏感度分析文件
确定参数：使用一下代码获得
```py
import math
from paddleslim.prune import load_sensitivities
from paddleslim.prune import get_ratios_by_loss 

sensitivities_file = "sstv.data"
sensitivities = load_sensitivities(sensitivities_file)
# print(sensitivities) 
ratios = get_ratios_by_loss(sensitivities, 0.1) 
print(ratios)
```
获得参数：
```js
{
'yolo_block.0.0.0.conv.weights': 0.5024404642823515, 
'yolo_block.0.0.1.conv.weights': 0.5806873814522566, 
// 'yolo_block.0.1.0.conv.weights': 0.4130713279785401, 
'yolo_block.0.1.1.conv.weights': 0.8445627084858831, 
'yolo_block.0.2.conv.weights': 0.7140574970525724, 
'yolo_block.0.tip.conv.weights': 0.8026657765827588,
'yolo_block.1.0.0.conv.weights': 0.9,
'yolo_block.1.0.1.conv.weights': 0.8590961280425866, 
'yolo_block.1.1.0.conv.weights': 0.7435697192868094, 
'yolo_block.1.1.1.conv.weights': 0.8933719407087457, 
'yolo_block.1.2.conv.weights': 0.796605418059164, 
'yolo_block.1.tip.conv.weights': 0.9, 
'yolo_block.2.0.0.conv.weights': 0.8641740135486591, 
'yolo_block.2.0.1.conv.weights': 0.7584828344125396,
'yolo_block.2.1.0.conv.weights': 0.7780280316817834,
'yolo_block.2.1.1.conv.weights': 0.8247591955828633, 
'yolo_block.2.2.conv.weights': 0.7763518811427775,
'yolo_block.2.tip.conv.weights': 0.8543156017782207
}
```

参考 #1346， 去掉 yolo_block.0.1.0.conv.weights 
最终参数： 
```
--pruned_params "yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.1.conv.weights,yolo_block.0.2.conv.weights,yolo_block.0.tip.conv.weights,yolo_block.1.0.0.conv.weights,yolo_block.1.0.1.conv.weights,yolo_block.1.1.0.conv.weights,yolo_block.1.1.1.conv.weights,yolo_block.1.2.conv.weights,yolo_block.1.tip.conv.weights,yolo_block.2.0.0.conv.weights,yolo_block.2.0.1.conv.weights,yolo_block.2.1.0.conv.weights,yolo_block.2.1.1.conv.weights,yolo_block.2.2.conv.weights,yolo_block.2.tip.conv.weights" \
--pruned_ratios="0.5,0.5,0.8,0.7,0.8,0.9,0.8,0.7,0.8,0.7,0.9,0.8,0.7,0.7,0.8,0.7,0.8" \
```

问题来了，训练中途，在box ap：0.7086416361742713 时测试，发现结果很不正常，与剪枝前结果大相径庭。
请教原因： 
1. get_ratios_by_loss 使用 0.1 参数是不是太大？
2. 使用参数中，除了yolo_block.0.1.0.conv.weights ，还有别的不能剪的吗？

**Comment by heavengate** [comment]
1. 看你敏感度的结果裁剪率比较大，get_ratio_by_loss 取0.1对于你的模型应该是偏大的，可以结合你的具体模型体积需求调整一下
2. 没有别的不能剪的了

看你裁剪后的box ap有0.7，结果应该是正常的，是不是预测的时候没有裁剪模型或者没有正确加载裁剪权重

**Comment by Fauny** [comment]
@heavengate 谢谢回复！
找到原因了：使用了`tools/infer.py`, 改成`slim/prune/infer.py` 就正常了

**Comment by heavengate** [comment]
好的，如果问题解决了，麻烦关闭一下issue~

**Comment by LLeeSG** [comment]
> 模型：ppyolo
> 训练结果：Best test box ap: 0.7949662589940378 'loss': '26.862640' , 导出模型大小：188.1M。经测试模型比较满意
> 敏感度分析：获得敏感度分析文件
> 确定参数：使用一下代码获得
> 
> ```python
> import math
> from paddleslim.prune import load_sensitivities
> from paddleslim.prune import get_ratios_by_loss 
> 
> sensitivities_file = "sstv.data"
> sensitivities = load_sensitivities(sensitivities_file)
> # print(sensitivities) 
> ratios = get_ratios_by_loss(sensitivities, 0.1) 
> print(ratios)
> ```
> 
> 获得参数：
> 
> ```js
> {
> 'yolo_block.0.0.0.conv.weights': 0.5024404642823515, 
> 'yolo_block.0.0.1.conv.weights': 0.5806873814522566, 
> // 'yolo_block.0.1.0.conv.weights': 0.4130713279785401, 
> 'yolo_block.0.1.1.conv.weights': 0.8445627084858831, 
> 'yolo_block.0.2.conv.weights': 0.7140574970525724, 
> 'yolo_block.0.tip.conv.weights': 0.8026657765827588,
> 'yolo_block.1.0.0.conv.weights': 0.9,
> 'yolo_block.1.0.1.conv.weights': 0.8590961280425866, 
> 'yolo_block.1.1.0.conv.weights': 0.7435697192868094, 
> 'yolo_block.1.1.1.conv.weights': 0.8933719407087457, 
> 'yolo_block.1.2.conv.weights': 0.796605418059164, 
> 'yolo_block.1.tip.conv.weights': 0.9, 
> 'yolo_block.2.0.0.conv.weights': 0.8641740135486591, 
> 'yolo_block.2.0.1.conv.weights': 0.7584828344125396,
> 'yolo_block.2.1.0.conv.weights': 0.7780280316817834,
> 'yolo_block.2.1.1.conv.weights': 0.8247591955828633, 
> 'yolo_block.2.2.conv.weights': 0.7763518811427775,
> 'yolo_block.2.tip.conv.weights': 0.8543156017782207
> }
> ```
> 
> 参考 #1346， 去掉 yolo_block.0.1.0.conv.weights
> 最终参数：
> 
> ```
> --pruned_params "yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.1.conv.weights,yolo_block.0.2.conv.weights,yolo_block.0.tip.conv.weights,yolo_block.1.0.0.conv.weights,yolo_block.1.0.1.conv.weights,yolo_block.1.1.0.conv.weights,yolo_block.1.1.1.conv.weights,yolo_block.1.2.conv.weights,yolo_block.1.tip.conv.weights,yolo_block.2.0.0.conv.weights,yolo_block.2.0.1.conv.weights,yolo_block.2.1.0.conv.weights,yolo_block.2.1.1.conv.weights,yolo_block.2.2.conv.weights,yolo_block.2.tip.conv.weights" \
> --pruned_ratios="0.5,0.5,0.8,0.7,0.8,0.9,0.8,0.7,0.8,0.7,0.9,0.8,0.7,0.7,0.8,0.7,0.8" \
> ```
> 
> 问题来了，训练中途，在box ap：0.7086416361742713 时测试，发现结果很不正常，与剪枝前结果大相径庭。
> 请教原因：
> 
> 1. get_ratios_by_loss 使用 0.1 参数是不是太大？
> 2. 使用参数中，除了yolo_block.0.1.0.conv.weights ，还有别的不能剪的吗？

你好，看到你剪枝的参数都集中在检测头，前边的ResNet骨干网一点都没裁剪么？

**Comment by Chen-Song** [comment]
@LLeeSG 在https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/slim/README.md里面提到“YOLOv3模型主要剪裁yolo_head部分”。但是我也不明白为什么不裁剪backbone。

**Comment by Chen-Song** [comment]
@LLeeSG [在](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/slim/README.md) 里面提到“YOLOv3模型主要剪裁yolo_head部分”。但是我也不明白为什么不裁剪backbone。

**Comment by Chen-Song** [comment]
@Fauny 请问你剪完之后，ppyolo模型还有多大呢？
