### ISSUE TITLE
PaddleSlim对应文档的图片丢失

### ISSUE THREAD

**Issue by Syencil** [PaddlePaddle/PaddleDetection#1386]
https://paddlepaddle.github.io/PaddleSlim/algo/algo/#3
文档中所有的表格和图片都无法加载显示

**Comment by still-wait** [comment]
@Syencil 感谢反馈，请先阅读https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/algo/algo.md ，图片加载不出来我们会尽快修复。
