### ISSUE TITLE
训练yolov4中，修改    num_max_boxes: 为90  ，遇到的问题

### ISSUE THREAD

**Issue by CVdandelion** [PaddlePaddle/PaddleDetection#1387]
由于我用的是visdrone数据集，有的图片中标注对象比较多，我想把这个每张图片中包含ground truth 的数目，调大到，100，或者90。当我把trainreader中的num_max_boxes: 为90 ，出现这样的错误是为什么阿？

Error Message Summary:
----------------------
InvalidArgumentError: The fed Variable gt_bbox should have dimensions = 3, shape = [-1, 90, 4], but received fed shape [4, 50, 4]
  [Hint: Expected DimensionIsCompatibleWith(shapes[i], in_dims) == true, but received DimensionIsCompatibleWith(shapes[i], in_dims):0 != true:1.] at (/paddle/paddle/fluid/operators/reader/read_op.cc:137)
  [operator < read > error]

还是说不应该不应该修改这个地方

**Comment by still-wait** [comment]
@CVdandelion 在TrainReader的PadBox中num_max_boxes改成90了吗？
```yaml
- !PadBox
      num_max_boxes: 50
```

**Comment by CVdandelion** [comment]
解决了，谢谢
