### ISSUE TITLE
AssertionError: Results do not correspond to current coco set  不知道什么问题

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleDetection#139]
环境：Python 3.7 PaddlePaddle 1.6.2

aistudio@jupyter-61916-232190:~/PaddleDetection$ python tools/eval.py -c configs/faster_rcnn_r50_1x.yml
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2019-12-29 21:32:29,197-INFO: 180 samples in file dataset/coco/annotations/instances_val2017.json
2019-12-29 21:32:29,198-INFO: places would be ommited when DataLoader is not iterable
W1229 21:32:30.190289  1413 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W1229 21:32:30.194048  1413 device_context.cc:244] device: 0, cuDNN Version: 7.3.
Traceback (most recent call last):
  File "tools/eval.py", line 188, in <module>
    main()
  File "tools/eval.py", line 108, in main
    checkpoint.load_params(exe, eval_prog, cfg.weights)
  File "/home/aistudio/PaddleDetection/ppdet/utils/checkpoint.py", line 98, in load_params
    "exists.".format(path))
ValueError: Model pretrain path output/faster_rcnn_r50_1x/model_final does not exists.
aistudio@jupyter-61916-232190:~/PaddleDetection$ python tools/eval.py -c configs/faster_rcnn_r50_1x.yml
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2019-12-29 21:40:25,572-INFO: 180 samples in file dataset/coco/annotations/instances_val2017.json
2019-12-29 21:40:25,573-INFO: places would be ommited when DataLoader is not iterable
W1229 21:40:26.565089  1507 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W1229 21:40:26.568838  1507 device_context.cc:244] device: 0, cuDNN Version: 7.3.
2019-12-29 21:40:27,966-INFO: Loading parameters from output/faster_rcnn_r50_1x/model_final...
I1229 21:40:28.223676  1507 parallel_executor.cc:421] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I1229 21:40:28.229634  1507 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I1229 21:40:28.234683  1507 parallel_executor.cc:285] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I1229 21:40:28.238572  1507 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
2019-12-29 21:40:28,435-INFO: Test iter 0
2019-12-29 21:40:33,650-INFO: Test iter 100
2019-12-29 21:40:37,655-INFO: Test finish iter 180
2019-12-29 21:40:37,655-INFO: Total number of images: 180, inference time: 19.07627173697089 fps.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2019-12-29 21:40:37,702-INFO: Start evaluate...
Loading and preparing results...
Traceback (most recent call last):
  File "tools/eval.py", line 188, in <module>
    main()
  File "tools/eval.py", line 165, in main
    is_bbox_normalized, FLAGS.output_eval, map_type)
  File "/home/aistudio/PaddleDetection/ppdet/utils/eval_utils.py", line 205, in eval_results
    is_bbox_normalized=is_bbox_normalized)
  File "/home/aistudio/PaddleDetection/ppdet/utils/coco_eval.py", line 96, in bbox_eval
    map_stats = cocoapi_eval(outfile, 'bbox', coco_gt=coco_gt)
  File "/home/aistudio/PaddleDetection/ppdet/utils/coco_eval.py", line 143, in cocoapi_eval
    coco_dt = coco_gt.loadRes(jsonfile)
  File "/home/aistudio/.local/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 317, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set

**Comment by littletomatodonkey** [comment]
您的标注文件加载是正确的嘛？标准的val2017数据集应该是5000张图片~下面是我运行eval的提示脚本

```
loading annotations into memory...
Done (t=1.05s)
creating index...
index created!
2019-12-29 14:05:36,451-INFO: 5000 samples in file dataset/coco/annotations/instances_val2017.json
```

**Comment by lxk767363331** [comment]
不是的 这是我自己的数据集 我把对应位置换成了我的数据




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "littletomatodonkey"<notifications@github.com&gt;; 
发送时间: 2019年12月29日(星期天) 晚上10:07
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 
抄送: "不要冲动保持心态"<767363331@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] AssertionError: Results do not correspond to current coco set  不知道什么问题 (#139)




您的标注文件加载是正确的嘛？标准的val2017数据集应该是5000张图片~下面是我运行eval的提示脚本
 loading annotations into memory... Done (t=1.05s) creating index... index created! 2019-12-29 14:05:36,451-INFO: 5000 samples in file dataset/coco/annotations/instances_val2017.json

**Comment by lxk767363331** [comment]
我的格式是没有问题的。我在进行object detection的时候，将我的数据集放在了dataset/coco的目录下了，预测的过程是没问题的，生成了对应的bbox.json文件，在算map值时出现的这个问题，应该是对应数量不匹配的问题。PaddleDetection未有如何训练自己的数据集这一教程 请问可否提供？

**Comment by lesonly** [comment]
@littletomatodonkey 您好大神，我也遇到了“Results do not correspond to current coco set”的问题。我的result.json和instances_val2017.json都没问题，在2014coco数据集可以得到eval结果，在2017数据集便会报错“Results do not correspond to current coco set”，晚学被这个问题困扰好久，可以帮忙看看问题吗？我的邮箱23006592@qq.com

**Comment by lxk767363331** [comment]
> @littletomatodonkey 您好大神，我也遇到了“Results do not correspond to current coco set”的问题。我的result.json和instances_val2017.json都没问题，在2014coco数据集可以得到eval结果，在2017数据集便会报错“Results do not correspond to current coco set”，晚学被这个问题困扰好久，可以帮忙看看问题吗？我的邮箱[23006592@qq.com](mailto:23006592@qq.com)

在2014可以完成eval在2017不可以么？ 我在2017下可以train；不可以eval，但是在eval过程中可以完成推理的过程，后续操作时不可以的；可以进行infer；

**Comment by lesonly** [comment]
> > @littletomatodonkey 您好大神，我也遇到了“Results do not correspond to current coco set”的问题。我的result.json和instances_val2017.json都没问题，在2014coco数据集可以得到eval结果，在2017数据集便会报错“Results do not correspond to current coco set”，晚学被这个问题困扰好久，可以帮忙看看问题吗？我的邮箱[23006592@qq.com](mailto:23006592@qq.com)
> 
> 在2014可以完成eval在2017不可以么？ 我在2017下可以train；不可以eval，但是在eval过程中可以完成推理的过程，后续操作时不可以的；可以进行infer；

是的，在2014下可以得到eval结果，在2017不可以。还有一个问题想请教您，论文中常说训练集是trainval35K，如果在2014下，train2014(82783张)和trainval35k（35504张)的标签是分开的，我不知道怎样将这118287张图片合并起来训练。

**Comment by lxk767363331** [comment]
> > > @littletomatodonkey 您好大神，我也遇到了“Results do not correspond to current coco set”的问题。我的result.json和instances_val2017.json都没问题，在2014coco数据集可以得到eval结果，在2017数据集便会报错“Results do not correspond to current coco set”，晚学被这个问题困扰好久，可以帮忙看看问题吗？我的邮箱[23006592@qq.com](mailto:23006592@qq.com)
> > 
> > 
> > 在2014可以完成eval在2017不可以么？ 我在2017下可以train；不可以eval，但是在eval过程中可以完成推理的过程，后续操作时不可以的；可以进行infer；
> 
> 是的，在2014下可以得到eval结果，在2017不可以。还有一个问题想请教您，论文中常说训练集是trainval35K，如果在2014下，train2014(82783张)和trainval35k（35504张)的标签是分开的，我不知道怎样将这118287张图片合并起来训练。

我也是跟你遇到同样问题，咱俩还是等待官方大神来解决一样吧

**Comment by qingqing01** [comment]
@lxk767363331   @lesonly  已在 https://github.com/PaddlePaddle/PaddleDetection/issues/141 中回复

**Comment by lesonly** [comment]
> @lxk767363331 @lesonly 已在 #141 中回复

您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢

**Comment by lesonly** [comment]
> @lxk767363331 @lesonly 已在 #141 中回复

您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢

**Comment by lxk767363331** [comment]
> > @lxk767363331 @lesonly 已在 #141 中回复
> 
> 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢



> > @lxk767363331 @lesonly 已在 #141 中回复
> 
> 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢

需要修改源码 PaddleDetection/ppdet/modeling/model_input.py 下 29行 {'name': 'im_id',         'shape': [1],  'dtype': 'int64',   'lod_level': 0},  int32改为64  最新的代码库已经修订

**Comment by lesonly** [comment]
> > > @lxk767363331 @lesonly 已在 #141 中回复
> > 
> > 
> > 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢
> 
> > > @lxk767363331 @lesonly 已在 #141 中回复
> > 
> > 
> > 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢
> 
> 需要修改源码 PaddleDetection/ppdet/modeling/model_input.py 下 29行 {'name': 'im_id', 'shape': [1], 'dtype': 'int64', 'lod_level': 0}, int32改为64 最新的代码库已经修订

非常感谢您的回复，请问您说的修改源码是指修改什么源码呢？我做的是目标检测，model_input.py是指？

**Comment by lxk767363331** [comment]
> > > > @lxk767363331 @lesonly 已在 #141 中回复
> > > 
> > > 
> > > 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢
> > 
> > 
> > > > @lxk767363331 @lesonly 已在 #141 中回复
> > > 
> > > 
> > > 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢
> > 
> > 
> > 需要修改源码 PaddleDetection/ppdet/modeling/model_input.py 下 29行 {'name': 'im_id', 'shape': [1], 'dtype': 'int64', 'lod_level': 0}, int32改为64 最新的代码库已经修订
> 
> 非常感谢您的回复，请问您说的修改源码是指修改什么源码呢？我做的是目标检测，model_input.py是指？

修改detection代码库下 PaddleDetection/ppdet/modeling/model_input.py  29行  {'name': 'im_id', 'shape': [1], 'dtype': 'int32', 'lod_level': 0} 改为int64 。 此模块在最新的detection代码库中已经修订

**Comment by lesonly** [comment]
感谢您的耐心回复，请问您所说的“detection代码库下 PaddleDetection/ppdet/modeling/model_input.py”是基于您自己的项目吗？我没有这个文件啊

> > > > > @lxk767363331 @lesonly 已在 #141 中回复
> > > > 
> > > > 
> > > > 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢
> > > 
> > > 
> > > > > @lxk767363331 @lesonly 已在 #141 中回复
> > > > 
> > > > 
> > > > 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢
> > > 
> > > 
> > > 需要修改源码 PaddleDetection/ppdet/modeling/model_input.py 下 29行 {'name': 'im_id', 'shape': [1], 'dtype': 'int64', 'lod_level': 0}, int32改为64 最新的代码库已经修订
> > 
> > 
> > 非常感谢您的回复，请问您说的修改源码是指修改什么源码呢？我做的是目标检测，model_input.py是指？
> 
> 修改detection代码库下 PaddleDetection/ppdet/modeling/model_input.py 29行 {'name': 'im_id', 'shape': [1], 'dtype': 'int32', 'lod_level': 0} 改为int64 。 此模块在最新的detection代码库中已经修订

感谢您的耐心回复，请问您所说的“detection代码库下 PaddleDetection/ppdet/modeling/model_input.py”是基于您自己的项目吗？我没有这个文件啊

**Comment by lxk767363331** [comment]
> 感谢您的耐心回复，请问您所说的“detection代码库下 PaddleDetection/ppdet/modeling/model_input.py”是基于您自己的项目吗？我没有这个文件啊
> 
> > > > > > @lxk767363331 @lesonly 已在 #141 中回复
> > > > > 
> > > > > 
> > > > > 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢
> > > > 
> > > > 
> > > > > > @lxk767363331 @lesonly 已在 #141 中回复
> > > > > 
> > > > > 
> > > > > 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢
> > > > 
> > > > 
> > > > 需要修改源码 PaddleDetection/ppdet/modeling/model_input.py 下 29行 {'name': 'im_id', 'shape': [1], 'dtype': 'int64', 'lod_level': 0}, int32改为64 最新的代码库已经修订
> > > 
> > > 
> > > 非常感谢您的回复，请问您说的修改源码是指修改什么源码呢？我做的是目标检测，model_input.py是指？
> > 
> > 
> > 修改detection代码库下 PaddleDetection/ppdet/modeling/model_input.py 29行 {'name': 'im_id', 'shape': [1], 'dtype': 'int32', 'lod_level': 0} 改为int64 。 此模块在最新的detection代码库中已经修订
> 
> 感谢您的耐心回复，请问您所说的“detection代码库下 PaddleDetection/ppdet/modeling/model_input.py”是基于您自己的项目吗？我没有这个文件啊

detection代码库是官方的目标检测代码库，不知道您使用的是什么代码库

**Comment by lesonly** [comment]
> > 感谢您的耐心回复，请问您所说的“detection代码库下 PaddleDetection/ppdet/modeling/model_input.py”是基于您自己的项目吗？我没有这个文件啊
> > > > > > > @lxk767363331 @lesonly 已在 #141 中回复
> > > > > > 
> > > > > > 
> > > > > > 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢
> > > > > 
> > > > > 
> > > > > > > @lxk767363331 @lesonly 已在 #141 中回复
> > > > > > 
> > > > > > 
> > > > > > 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢
> > > > > 
> > > > > 
> > > > > 需要修改源码 PaddleDetection/ppdet/modeling/model_input.py 下 29行 {'name': 'im_id', 'shape': [1], 'dtype': 'int64', 'lod_level': 0}, int32改为64 最新的代码库已经修订
> > > > 
> > > > 
> > > > 非常感谢您的回复，请问您说的修改源码是指修改什么源码呢？我做的是目标检测，model_input.py是指？
> > > 
> > > 
> > > 修改detection代码库下 PaddleDetection/ppdet/modeling/model_input.py 29行 {'name': 'im_id', 'shape': [1], 'dtype': 'int32', 'lod_level': 0} 改为int64 。 此模块在最新的detection代码库中已经修订
> > 
> > 
> > 感谢您的耐心回复，请问您所说的“detection代码库下 PaddleDetection/ppdet/modeling/model_input.py”是基于您自己的项目吗？我没有这个文件啊
> 
> detection代码库是官方的目标检测代码库，不知道您使用的是什么代码库
谢谢您耐心的回复与帮助，我用的是cocoapi评估，代码如下
#!/usr/bin/env python
# coding: utf-8

import json 
import matplotlib.pyplot as plt
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
import numpy as np
import skimage.io as io
import pylab

annType = ['segm','bbox','keypoints']
annType = annType[1]      #specify type here
prefix = 'person_keypoints' if annType=='keypoints' else 'instances'
print ('Running demo for *%s* results.'%(annType))

initialize COCO ground truth api
dataDir='../'
dataType='val2014'
annFile = '%s/annotations/%s_%s.json'%(dataDir,prefix,dataType)
cocoGt=COCO(annFile)
initialize COCO detections api
resFile='%s/results/%s_%s_fake%s100_results.json'
resFile = resFile%(dataDir, prefix, dataType, annType)
cocoDt=cocoGt.loadRes(resFile)
imgIds=sorted(cocoGt.getImgIds())
imgIds=imgIds[0:100]
imgId = imgIds[np.random.randint(100)]
# running evaluation
cocoEval = COCOeval(cocoGt,cocoDt,annType)
cocoEval.params.imgIds  = imgIds
cocoEval.evaluate()
cocoEval.accumulate()
cocoEval.summarize()

**Comment by lxk767363331** [comment]
> > > 感谢您的耐心回复，请问您所说的“detection代码库下 PaddleDetection/ppdet/modeling/model_input.py”是基于您自己的项目吗？我没有这个文件啊
> > > > > > > > @lxk767363331 @lesonly 已在 #141 中回复
> > > > > > > 
> > > > > > > 
> > > > > > > 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢
> > > > > > 
> > > > > > 
> > > > > > > > @lxk767363331 @lesonly 已在 #141 中回复
> > > > > > > 
> > > > > > > 
> > > > > > > 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢
> > > > > > 
> > > > > > 
> > > > > > 需要修改源码 PaddleDetection/ppdet/modeling/model_input.py 下 29行 {'name': 'im_id', 'shape': [1], 'dtype': 'int64', 'lod_level': 0}, int32改为64 最新的代码库已经修订
> > > > > 
> > > > > 
> > > > > 非常感谢您的回复，请问您说的修改源码是指修改什么源码呢？我做的是目标检测，model_input.py是指？
> > > > 
> > > > 
> > > > 修改detection代码库下 PaddleDetection/ppdet/modeling/model_input.py 29行 {'name': 'im_id', 'shape': [1], 'dtype': 'int32', 'lod_level': 0} 改为int64 。 此模块在最新的detection代码库中已经修订
> > > 
> > > 
> > > 感谢您的耐心回复，请问您所说的“detection代码库下 PaddleDetection/ppdet/modeling/model_input.py”是基于您自己的项目吗？我没有这个文件啊
> > 
> > 
> > detection代码库是官方的目标检测代码库，不知道您使用的是什么代码库
> > 谢谢您耐心的回复与帮助，我用的是cocoapi评估，代码如下
> > #!/usr/bin/env python
> 
> # coding: utf-8
> import json
> import matplotlib.pyplot as plt
> from pycocotools.coco import COCO
> from pycocotools.cocoeval import COCOeval
> import numpy as np
> import skimage.io as io
> import pylab
> 
> annType = ['segm','bbox','keypoints']
> annType = annType[1] #specify type here
> prefix = 'person_keypoints' if annType=='keypoints' else 'instances'
> print ('Running demo for _%s_ results.'%(annType))
> 
> initialize COCO ground truth api
> dataDir='../'
> dataType='val2014'
> annFile = '%s/annotations/%s_%s.json'%(dataDir,prefix,dataType)
> cocoGt=COCO(annFile)
> initialize COCO detections api
> resFile='%s/results/%s_%s_fake%s100_results.json'
> resFile = resFile%(dataDir, prefix, dataType, annType)
> cocoDt=cocoGt.loadRes(resFile)
> imgIds=sorted(cocoGt.getImgIds())
> imgIds=imgIds[0:100]
> imgId = imgIds[np.random.randint(100)]
> 
> # running evaluation
> cocoEval = COCOeval(cocoGt,cocoDt,annType)
> cocoEval.params.imgIds = imgIds
> cocoEval.evaluate()
> cocoEval.accumulate()
> cocoEval.summarize()

我使用的cocoapi评估也是paddle-detection代码库中的，标注的img_id 大小不对，超过int32的最大值，建议修改自己的img_id的数值

**Comment by lesonly** [comment]
> > > > 感谢您的耐心回复，请问您所说的“detection代码库下 PaddleDetection/ppdet/modeling/model_input.py”是基于您自己的项目吗？我没有这个文件啊
> > > > > > > > > @lxk767363331 @lesonly 已在 #141 中回复
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢
> > > > > > > 
> > > > > > > 
> > > > > > > > > @lxk767363331 @lesonly 已在 #141 中回复
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json，非常感谢
> > > > > > > 
> > > > > > > 
> > > > > > > 需要修改源码 PaddleDetection/ppdet/modeling/model_input.py 下 29行 {'name': 'im_id', 'shape': [1], 'dtype': 'int64', 'lod_level': 0}, int32改为64 最新的代码库已经修订
> > > > > > 
> > > > > > 
> > > > > > 非常感谢您的回复，请问您说的修改源码是指修改什么源码呢？我做的是目标检测，model_input.py是指？
> > > > > 
> > > > > 
> > > > > 修改detection代码库下 PaddleDetection/ppdet/modeling/model_input.py 29行 {'name': 'im_id', 'shape': [1], 'dtype': 'int32', 'lod_level': 0} 改为int64 。 此模块在最新的detection代码库中已经修订
> > > > 
> > > > 
> > > > 感谢您的耐心回复，请问您所说的“detection代码库下 PaddleDetection/ppdet/modeling/model_input.py”是基于您自己的项目吗？我没有这个文件啊
> > > 
> > > 
> > > detection代码库是官方的目标检测代码库，不知道您使用的是什么代码库
> > > 谢谢您耐心的回复与帮助，我用的是cocoapi评估，代码如下
> > > #!/usr/bin/env python
> > 
> > 
> > # coding: utf-8
> > import json
> > import matplotlib.pyplot as plt
> > from pycocotools.coco import COCO
> > from pycocotools.cocoeval import COCOeval
> > import numpy as np
> > import skimage.io as io
> > import pylab
> > annType = ['segm','bbox','keypoints']
> > annType = annType[1] #specify type here
> > prefix = 'person_keypoints' if annType=='keypoints' else 'instances'
> > print ('Running demo for _%s_ results.'%(annType))
> > initialize COCO ground truth api
> > dataDir='../'
> > dataType='val2014'
> > annFile = '%s/annotations/%s_%s.json'%(dataDir,prefix,dataType)
> > cocoGt=COCO(annFile)
> > initialize COCO detections api
> > resFile='%s/results/%s_%s_fake%s100_results.json'
> > resFile = resFile%(dataDir, prefix, dataType, annType)
> > cocoDt=cocoGt.loadRes(resFile)
> > imgIds=sorted(cocoGt.getImgIds())
> > imgIds=imgIds[0:100]
> > imgId = imgIds[np.random.randint(100)]
> > # running evaluation
> > cocoEval = COCOeval(cocoGt,cocoDt,annType)
> > cocoEval.params.imgIds = imgIds
> > cocoEval.evaluate()
> > cocoEval.accumulate()
> > cocoEval.summarize()
> 
> 我使用的cocoapi评估也是paddle-detection代码库中的，标注的img_id 大小不对，超过int32的最大值，建议修改自己的img_id的数值

再次感谢您耐心的回复与帮助！我明白了，您是在用统一的目标检测框架paddle-detection。我是用pytorch写的程序，然后利用cocoapi评估，嗯，是img_id的问题！请问我要修改标注的img_Id类型，还是修改自己生成的结果的img_id类型呢

**Comment by qingqing01** [comment]
@lesonly 已在 https://github.com/PaddlePaddle/PaddleDetection/issues/141 回复
