### ISSUE TITLE
剪枝后导出模型，缺失 infer_cfg.yml

### ISSUE THREAD

**Issue by Fauny** [PaddlePaddle/PaddleDetection#1390]
使用 `slim/prune/export_model.py` 导出剪裁后模型，导出目录中缺少 `infer_cfg.yml` 文件

**Comment by heavengate** [comment]
好的，感谢反馈，我们修复一下~

**Comment by jerrywgz** [comment]
issue先关闭了，如果还有新的问题可以再提issue，我们会及时跟进
