### ISSUE TITLE
pp-YOLO训练GPU和CPU利用率突然为零

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#1393]
运行时到5000轮时下面这些代码触发except捕获异常，但捕获之后GPU和CPU利用率就为0了
class Compose(object):
    def __init__(self, transforms, ctx=None):
        self.transforms = transforms
        self.ctx = ctx

    def __call__(self, data):
        ctx = self.ctx if self.ctx else {}
        for f in self.transforms:
            try:
                data = f(data, ctx)
            except Exception as e:
                stack_info = traceback.format_exc()
                logger.warn("fail to map op [{}] with error: {} and stack:\n{}".
                            format(f, e, str(stack_info)))
                raise e
        return data
然后找到具体触发的位置
        im = self._mixup_img(sample['image'], sample['mixup']['image'], factor)
        gt_bbox1 = sample['gt_bbox']
        gt_bbox2 = sample['mixup']['gt_bbox']
        gt_bbox = np.concatenate((gt_bbox1, gt_bbox2), axis=0)
        gt_class1 = sample['gt_class']
        gt_class2 = sample['mixup']['gt_class']
        gt_class = np.concatenate((gt_class1, gt_class2), axis=0)

        gt_score1 = sample['gt_score']
        gt_score2 = sample['mixup']['gt_score']
        gt_score = np.concatenate(
            (gt_score1 * factor, gt_score2 * (1. - factor)), axis=0)
是concatenate出错，具体是什么原因报错的，是我的数据问题吗？

**Comment by heavengate** [comment]
具体捕获到什么异常呢，麻烦发一下~

**Comment by qdd1234** [comment]
> 具体捕获到什么异常呢，麻烦发一下~

异常就是concatenate那个部分： gt_score = np.concatenate((gt_score1 * factor, gt_score2 * (1. - factor)), axis=0)说gt_score1 * factor 和gt_score2 * (1. - factor)维度不一样无法进行concatenate，可是我的数不应该是相同的输入大小吗

**Comment by heavengate** [comment]
> > 具体捕获到什么异常呢，麻烦发一下~
> 
> 异常就是concatenate那个部分： gt_score = np.concatenate((gt_score1 * factor, gt_score2 * (1. - factor)), axis=0)说gt_score1 * factor 和gt_score2 * (1. - factor)维度不一样无法进行concatenate，可是我的数不应该是相同的输入大小吗

是否输入数据里有gtbox为空的数据

**Comment by heavengate** [comment]
可以参考这个PR的修改试下，https://github.com/PaddlePaddle/PaddleDetection/pull/1404
