### ISSUE TITLE
无法导出模型

### ISSUE THREAD

**Issue by HelloAI-twj** [PaddlePaddle/PaddleDetection#1398]
我想请问一下，我在使用export_model时无法成功导出模型，报错显示Failed to load model file , please make sure model file is saved with the following APIs: save_params, save_persistables, save_vars。我的权重文件夹里面有三个后缀分别为.pdparams、.pdopt、.pdmodel的文件，想请教一下应该怎么解决这个问题

**Comment by qingqing01** [comment]
@HelloAI-twj 

模型后缀为".pdparams、.pdopt、.pdmodel"没有问题，您具体导出模型的命令是咋样的，麻烦详细贴下？以及使用的PaddleDetection的版本是多少？

**Comment by HelloAI-twj** [comment]
> @HelloAI-twj
> 
> 模型后缀为".pdparams、.pdopt、.pdmodel"没有问题，您具体导出模型的命令是咋样的，麻烦详细贴下？以及使用的PaddleDetection的版本是多少？

我用的命令是python tools/export_model.py -c configs/yolov4/yolov4_cspdarknet_voc.yml \
        -o weights=model/model_final \
        --output_dir=/home/aistudio/infer/ 
我是直接用git clone https://github.com/PaddlePaddle/PaddleDetection，应该是最新版本
