### ISSUE TITLE
Device id must be less than GPU count, but received id is: 0. GPU count is: 0

### ISSUE THREAD

**Issue by Viktor-Paul** [PaddlePaddle/PaddleDetection#1399]
您好，最近刚接触docker，想使用docker实现项目的快速交付，在官网也没有找到相关的资料，学习了一段时间，把python端的推理部署打成了docker镜像（python端的推理部署正常），运行该镜像后出现了下面的错误：
![error](https://user-images.githubusercontent.com/51936391/93012867-3210f500-f5d6-11ea-83b2-b1c86a1fec31.png)
硬件信息：
![yingjian](https://user-images.githubusercontent.com/51936391/93012901-7f8d6200-f5d6-11ea-9173-558cdafb3316.png)
Makefile文件内容：
![Makefile01](https://user-images.githubusercontent.com/51936391/93013078-be6fe780-f5d7-11ea-8c81-80eae7733051.png)
在ubuntu18.04中也安装了nvidia-docker，cuda10.2以及对应的cudnn，但是还是不能使镜像使用硬件的资源，这个问题已经困惑了好几周了，希望可以得到您的宝贵的意见，谢谢。

**Comment by qingqing01** [comment]
@Viktor-Paul  我理解可以直接使用 Paddle提供的docker镜像:

https://www.paddlepaddle.org.cn/documentation/docs/zh/install/install_Docker.html#docker

在此镜像中，包含PaddleDetection的部署，再保存成新的镜像。

报错的信息，应该是镜像内部没有CUDA相关环境。

**Comment by Viktor-Paul** [comment]
@qingqing01 非常谢谢您提供的意见，昨天在nvdia-docker找到了相关内容，在Makefile文件中配置了相关的环境变量，就没有之前的错误了，但是又出现了新的错误
![屏幕截图_3](https://user-images.githubusercontent.com/51936391/93154531-6a2f4980-f736-11ea-8fb1-eed3c693f338.png)
查看了相关的报相同错误的帖子，[https://github.com/PaddlePaddle/Paddle/issues/26719](https://github.com/PaddlePaddle/Paddle/issues/26719)和(https://github.com/PaddlePaddle/Paddle/issues/26801)
大致明白是cudnn的环境变量设置问题，以及进行了相应的软链接，建立其相应的关系
![屏幕截图_4](https://user-images.githubusercontent.com/51936391/93156132-11fa4680-f73a-11ea-902d-867b6c238ddf.png)
也进行了相关的环境变量的配置，但是还是不起作用，我不知道问题出在哪里了，下面是/etc/profile配置文件中cuda配置内容，也添加了cudnn的环境变量
![屏幕截图_5](https://user-images.githubusercontent.com/51936391/93156592-fe9bab00-f73a-11ea-90cf-569dd3eea881.png)
～/.bashrc配置文件中也是相同的内容，cuda的版本是V10.0.130，cudnn的版本是7.6.5

**Comment by qingqing01** [comment]
@Viktor-Paul   cuDNN的lib和Paddle包需要的版本号一致吗？Paddle你安装的是那个包？

**Comment by Viktor-Paul** [comment]
@qingqing01 安装的paddlepaddle-gpu==1.8.4.post107，之前是在window系统上跑通的，后来就把windows上面的环境生成了相应的requirements.txt，删除了conda相应的包，然后用docker在ubuntu18.04重新生成了镜像，因为nvidia-docker不支持window，我不知道这样是否正确，还是必须要在ubuntu18.04上重新下载相应的包，来支持paddle

**Comment by Viktor-Paul** [comment]
@qingqing01 您好，昨天在paddleocr中发现有人也遇到了相同的问题，[https://github.com/PaddlePaddle/PaddleOCR/issues/63](url) 
尝试用added the following path into /etc/profile:
PATH=/usr/local/cuda-10.0/lib64/libcudnn.so:$PATH
PATH=/usr/local/cuda-10.0/lib64/libcudnn.so.7:$PATH
PATH=/usr/local/cuda-10.0/lib64/libcudnn.so.7.6.5:$PATH
但是依旧发现不起作用，依旧报相同的错误Error: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion at (/paddle/paddle/fluid/platform/dynload/cudnn.cc:63)
用终端输出PATH和LD_LIBRARY_PATH结果如下：
![屏幕截图_6](https://user-images.githubusercontent.com/51936391/93296339-9673c480-f821-11ea-95d3-0f917fa0bb0b.png)
昨天那个paddle的包我查了一下是paddlepaddle-gpu==1.8.3.post107版本的，在csdn根据这个(https://blog.csdn.net/qq451882471/article/details/106967942)
也添加了libcudnn.so和libcublas.so到shared library,但是依旧不起作用，这个是shared library中的
![屏幕截图_8](https://user-images.githubusercontent.com/51936391/93297285-8eb51f80-f823-11ea-8507-5ee270dc4897.png)
还是不知道是自己的哪里设置有问题，希望可以得到您的帮助，谢谢。

**Comment by qingqing01** [comment]
如果cuDNN的lib在/usr/local/cuda-10.0/lib64里:

```
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH
```

这样设置下不行吗？

**Comment by Viktor-Paul** [comment]
@qingqing01 问题找到了，不是本地环境配置的问题，我尝试了安装了运行程序相应的包，程序在本地是可以跑起来的，而是nvidia/cuda:10.0-runtime-ubuntu18.04-cudnn7基础镜像虽然也有cudnn,但是可能缺少运行cudnn某些组件，导致无法加载cudnn shared library，后来把镜像换为nvidia/cuda:10.0-devel-ubuntu18.04-cudnn7，然后安装了相应的环境包程序就可以跑起来了。感谢您这几天提供的帮助，也希望这个帖子能为以后遇到这种问题的其他人带去点帮助。

**Comment by ALixuhui** [comment]
> @qingqing01不是找到本地环境配置的问题了，虽然我尝试了安装运行程序相应的包，程序在本地是可以跑的，只是nvidia/cuda:10.0-runtime-ubuntu18.04-cudnn7基础镜像也有cudnn，可能运行起来运行cudnn还有另外一个程序，无法加载cudnn共享库，然后将镜像上传为nvidia-cunn:10.0-devel-ubuntu18.04-就dnn7，然后可以安装相应的环境包。感谢您这几天提供的帮助，也希望这个帖子以后遇到这种问题的其他人带去点帮助。

你好，我现在也是使用的也是nvidiadocker，镜像为nvidia/cuda:11.2.0-cudnn8-devel-ubuntu18.04，目前容器中也是找不到GPU，请问您这个“**安装相应的环境包**“ 是指的什么意思，以及如何安装相应的环境包，期待您的回复~~

**Comment by yanyide123** [comment]
> > @qingqing01没有找到本地环境配置的问题了，虽然我尝试安装了运行程序相应的包，程序在本地是可以运行的，只要nvidia/cuda:10.0-runtime-ubuntu18.04-cudnn7基础镜像也有cudnn，就可以运行起来运行cudnn还有另外一个程序，无法加载cudnn共享库，然后将镜像上传为nvidia-cunn:10.0-devel-ubuntu18.04-就dnn7，然后安装相应的环境包。感谢您这几天提供的帮助，也希望这篇文章以后遇到此类问题的其他人能提供点帮助。
> 
> 你好，我现在也使用的也是nvidiadocker，镜像为nvidia/cuda:11.2.0-cudnn8-devel-ubuntu18.04，目前容器中也缺少GPU，请问您这个“**安装相应的环境包**”是指的意思，以及如何安装相应的环境包，期待您的回复~~

这个问题因该是docker里面没有对应的NVIDIA的驱动，nvidia给的一个解决方案是docker run -it --gpus all ，但需要安装NVIDIA Container Runtime这个包，可以网上下载nvidia-container-runtime-script.sh，进行安装就可以了，docker run的命令加上gpus这个属性，这样解决最为简单，上述解决方案我没有解决
