### ISSUE TITLE
PaddleDetection可否出一个关于如何训练自己数据集的教程？

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleDetection#140]

**Comment by qingqing01** [comment]
@lxk767363331 master分支，重新梳理、改进了预处理逻辑，这个文档正在写。

**Comment by qingqing01** [comment]
@lxk767363331   针对自定义数据新改进的教程，请参考: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/READER.md  

具体参考: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/READER.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E6%BA%90

即可以将数据格式转换为COCO/VOC格式，也可以添加自己定义的数据解析模块。
