### ISSUE TITLE
AssertionError: Results do not correspond to current coco set

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleDetection#141]
怎么训练自己的数据集 ，把数据集放在相应的位置可以么？？？？？？？？？？？？
PaddleDetection/dataset/neu-det 这样就可以么？？？？？？？？？

python tools/eval.py -c configs/faster_rcnn_r50_1x.yml
报错 AssertionError: Results do not correspond to current coco set

**Comment by qingqing01** [comment]
如果数据是COCO 、VOC数据格式，在yml配置文件配置`dataset_dir`, `annotation`, `image_dir`.

如果不是这2种数据格式，可以转换为COCO格式。可看下是否参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/ppdet/data/tools/x2coco.py 转换格式。

release/0.1分支的文档 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/docs/DATA_cn.md

master分支，我们简化了预处理逻辑，相应的文档也在增加。

**Comment by qingqing01** [comment]
如果数据是COCO 、VOC数据格式，在yml配置文件配置`dataset_dir`, `annotation`, `image_dir`.

如果不是这2种数据格式，可以转换为COCO格式。可看下是否参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/ppdet/data/tools/x2coco.py 转换格式。

release/0.1分支的文档 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/docs/DATA_cn.md

**Comment by lxk767363331** [comment]
> 如果数据是COCO 、VOC数据格式，在yml配置文件配置`dataset_dir`, `annotation`, `image_dir`.
> 
> 如果不是这2种数据格式，可以转换为COCO格式。可看下是否参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/ppdet/data/tools/x2coco.py 转换格式。
> 
> release/0.1分支的文档 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/docs/DATA_cn.md

https://aistudio.baidu.com/aistudio/projectDetail/233083这是项目，已公开 如方便希望可以帮忙看下。
使用的是coco2017格式，数据完成了转化
我已经转换成了coco数据集模式，并且可以进行train.py 与infer.py ，只有eval.py失败
xml文件配置如下：
FasterRCNNTrainFeed:
  # batch size per device
  batch_size: 1
  dataset:
    dataset_dir: dataset/neu-det
    annotation: annotations/instances_train2017.json
    image_dir: train2017
  drop_last: false
  num_workers: 2

FasterRCNNEvalFeed:
  batch_size: 1
  dataset:
    dataset_dir: dataset/neu-det
    annotation: annotations/instances_val2017.json
    image_dir: val2017
  num_workers: 2

FasterRCNNTestFeed:
  batch_size: 1
  dataset:
    annotation: dataset/neu-det/annotations/instances_val2017.json

**Comment by qingqing01** [comment]
@lxk767363331 问题已发现，通过

```
File "/home/aistudio/.local/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 317, in loadRes
```

317行打印:

print(annsImgIds)
print(self.getImgIds())

发现，不相等，出现了负数，
需要将 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/ppdet/modeling/model_input.py#L29

这行的 `im_id` 类型改成  int64.

int32的最大值 2147483647，而您的标注里img_id为 20190000148 . 我们会提PR修复下。

**Comment by lxk767363331** [comment]
> @lxk767363331 问题已发现，通过
> 
> ```
> File "/home/aistudio/.local/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 317, in loadRes
> ```
> 
> 317行打印:
> 
> print(annsImgIds)
> print(self.getImgIds())
> 
> 发现，不相等，出现了负数，
> 需要将 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/ppdet/modeling/model_input.py#L29
> 
> 这行的 `im_id` 类型改成 int64.
> 
> int32的最大值 2147483647，而您的标注里img_id为 20190000148 . 我们会提PR修复下。

问题已解决，运行成功， 谢谢

**Comment by lesonly** [comment]
@qingqing01 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json

**Comment by lesonly** [comment]
> @lxk767363331 问题已发现，通过
> 
> ```
> File "/home/aistudio/.local/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 317, in loadRes
> ```
> 
> 317行打印:
> 
> print(annsImgIds)
> print(self.getImgIds())
> 
> 发现，不相等，出现了负数，
> 需要将 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/ppdet/modeling/model_input.py#L29
> 
> 这行的 `im_id` 类型改成 int64.
> 
> int32的最大值 2147483647，而您的标注里img_id为 20190000148 . 我们会提PR修复下。

@qingqing01 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json

**Comment by qingqing01** [comment]
@lxk767363331 遇到的问题是annotation中的image_id 和 评估结果的image_id不匹配。你的问题，得针对的你的数据查看。

你可以仔细阅读COCO API评估的要求，也可以按照上述调试方法打印查看具体问题。

```
File "/home/aistudio/.local/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 317, in loadRes

317行打印:

print(annsImgIds)
print(self.getImgIds())
```

数据不同、问题不一定相同，需要依据你的问题查看。 另外如果是PyTorch问题，也可以去其issue下提问, 也欢迎使用PaddleDetection。 :)

**Comment by kuangxiaoye** [comment]
> > @lxk767363331 问题已发现，通过
> > ```
> > File "/home/aistudio/.local/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 317, in loadRes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 317行打印:
> > print(annsImgIds)
> > print(self.getImgIds())
> > 发现，不相等，出现了负数，
> > 需要将 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/ppdet/modeling/model_input.py#L29
> > 这行的 `im_id` 类型改成 int64.
> > int32的最大值 2147483647，而您的标注里img_id为 20190000148 . 我们会提PR修复下。
> 
> @qingqing01 您好，请问修改image_id数据类型，我是要在生成result.jons的评估文件中改吗？比如eval.py生成result.json

请问你现在解决了这个问题吗？
