### ISSUE TITLE
查看训练好的模型参数，需要怎么操作

### ISSUE THREAD

**Issue by CVdandelion** [PaddlePaddle/PaddleDetection#1410]
请问一下，我现在把模型训练好了，想要看模型的每一层的结构的数据，应该怎么做，比如说我想看某一卷积层，每个卷积核都是多少

**Comment by jerrywgz** [comment]
目前模型训练好的参数可以直接通过pickle加载，然后得到一个字典，字典里就是用numpy保存的每个参数
