### ISSUE TITLE
visualdl : browser does not show anything.

### ISSUE THREAD

**Issue by peerajak** [PaddlePaddle/PaddleDetection#1417]
I try to use visualdl for PaddleDetection. I follow exactly the Quick start guide. but my browswer shows blank page.
I then try visualdl demo, with command
vdl_create_scratch_log, vdl_scratch.py, vdl_scratch
all of them result in command not found.

My enviroment is virtualenv python3.6
Please help.

**Comment by jerrywgz** [comment]
we update the quick start document https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/tutorials/QUICK_STARTED_cn.md and you could try it

**Comment by liuhuiCNN** [comment]
we test on python3.7 and visualdl==2.0.0.
for more detial info please refer [https://github.com/PaddlePaddle/VisualDL](https://github.com/PaddlePaddle/VisualDL)

**Comment by peerajak** [comment]
How to checkout  Version 2.0.0?

**Comment by peerajak** [comment]
I was using 2.0.3 when I asked this question
I finally manage to check out Version 2.0.1, now it works. I see the loss value versus iteration graph. 
I guess 2.0.3 has something to do with my computer setting. Ubuntu 18.04, CUDA 11.0
