### ISSUE TITLE
请问config yml 里有哪些参数必须配置的，哪些是可选配的，哪些有默认值，该如何知道

### ISSUE THREAD

**Issue by FibonacciSun** [PaddlePaddle/PaddleDetection#142]

**Comment by willthefrog** [comment]
配置使用请参考[文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/docs/CONFIG_cn.md)，各模块的参数同它的构造函数参数是对应的。另外，`tools/configure.py` 提供了一些辅助功能。比如，想了解某个具体模块（如 BBoxHead）可以运行
```sh
python tools/configure.py help BBoxHead
```
如果要生成仅包含必填参数的配置文件(如FasterRCNN)，可以运行
```sh
python tools/configure.py generate --minimal  FasterRCNN BBoxHead
```
