### ISSUE TITLE
PP-YOLO一些理论问题

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#1426]
1.在ResNet50vd中加入可变形卷积，那么之前的预训练权重是怎么直接用上的，我看原来ResNet50vd里面没有DCN啊
2.设计团队在选择骨干网络的时候为何没像YOLOv4那样在ResNet50vd中加入CSPNet？难道是效果不好吗，还是没有尝试？
最近在写论文，希望设计团队的老师帮我解答一下

**Comment by still-wait** [comment]
@qdd1234 
1. DCN实际上就是多预测一个offset，这个部分参数可以用常数初始化，其他卷积的参数仍然可以用预训练权重做初始化。
2. CSPNet在resnet上的变化是相对较大的，基本是又是尝试一个全新的backbone，那样选择的空间是很大的，也可能需要重新进行预训练，后面的FPN等网络结构也不一定完全兼容，需要修改，这将花费更多的时间去训练和调参。所以PP-YOLO的设计阶段没有考虑在backbone上做大的变化。

**Comment by qdd1234** [comment]
> @qdd1234
> 
> 1. DCN实际上就是多预测一个offset，这个部分参数可以用常数初始化，其他卷积的参数仍然可以用预训练权重做初始化。
> 2. CSPNet在resnet上的变化是相对较大的，基本是又是尝试一个全新的backbone，那样选择的空间是很大的，也可能需要重新进行预训练，后面的FPN等网络结构也不一定完全兼容，需要修改，这将花费更多的时间去训练和调参。所以PP-YOLO的设计阶段没有考虑在backbone上做大的变化。

还有一个问题想请教一下，就是PP-YOLO的可变形卷积当时有没有考虑过用空洞卷积？是不是空洞卷积无法使用预训练？
