### ISSUE TITLE
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'get_cuda_device_count'

### ISSUE THREAD

**Issue by zgsxwsdxg** [PaddlePaddle/PaddleDetection#1433]
train.py 这行代码 devices_num = fluid.core.get_cuda_device_count()，显示没有get_cuda_device_count()这个接口

**Comment by heavengate** [comment]
你好，请问你使用的是Paddle哪个版本呢？

**Comment by qingqing01** [comment]
@zgsxwsdxg 如果您安装的是CPU版本的话，运行时需要设置为CPU运行。

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg 如果您安装的是CPU版本的话，运行时需要设置为CPU运行。

ok，明白了，我也是paddle 初学者，谢谢！
