### ISSUE TITLE
image_shape

### ISSUE THREAD

**Issue by zxz-cc** [PaddlePaddle/PaddleDetection#1435]
What's  the "image_shape" in the paddeldetection? What is it used for ??Can anyone tell me??

**Comment by heavengate** [comment]
> What's the "image_shape" in the paddeldetection? What is it used for ??Can anyone tell me??

In train/eval mode, `image_shape` is not needed, `image_shape` is used for infer mode to export model by `tools/export_model` to deploy model, for in same cases, like TensorRT, need a fixed input shape, so we given `image_shape` to make sure input shape is fixed.

**Comment by zxz-cc** [comment]
> 
> 
> > What's the "image_shape" in the paddeldetection? What is it used for ??Can anyone tell me??
> 
> In train/eval mode, `image_shape` is not needed, `image_shape` is used for infer mode to export model by `tools/export_model` to deploy model, for in same cases, like TensorRT, need a fixed input shape, so we given `image_shape` to make sure input shape is fixed.

Thank you !
