### ISSUE TITLE
How to generate Precision/Recall Curve?

### ISSUE THREAD

**Issue by peerajak** [PaddlePaddle/PaddleDetection#1451]
I wish to generate Precision/Recall Curves showing many experiments.
Is there anyway to automatically generate the curve?

**Comment by qingqing01** [comment]
@peerajak  Thanks for you sugestion. We will add this feature in the future.  Now need to modify voc_eval or coco_eval to calculate P/R.

**Comment by jerrywgz** [comment]
Now we have supported PR Curve in dygraph mode. You could use --classwise at the stage of evaluation.
