### ISSUE TITLE
训练pp-yolo，如何设置数据增强配置，我想加旋转90、180、270，在哪里设置

### ISSUE THREAD

**Issue by zgsxwsdxg** [PaddlePaddle/PaddleDetection#1453]
期待技术同仁的回复

**Comment by qingqing01** [comment]
PP-YOLO的预处理:

https://github.com/PaddlePaddle/PaddleDetection/blob/1420a1d92e76a73dfd54c7c404e37670c1542bb0/configs/ppyolo/ppyolo.yml#L92-L92

->

具体的预处理在这里:

https://github.com/PaddlePaddle/PaddleDetection/blob/1420a1d92e76a73dfd54c7c404e37670c1542bb0/configs/ppyolo/ppyolo_reader.yml#L11-L49

可以在sample_transforms中加，不过[transform的预处理中](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/data/transform/operators.py) 中还没有旋转，得自己手动加下，我们后续加下这个feature.

**Comment by zgsxwsdxg** [comment]
> PP-YOLO的预处理:
> 
>   
>     
>       PaddleDetection/configs/ppyolo/ppyolo.yml
>     
>     
>          Line 92
>       in
>       1420a1d
>     
>     
>     
>     
> 
>         
>           
>            _READER_: 'ppyolo_reader.yml' 
>         
>     
>   
> 
> 
> ->
> 具体的预处理在这里:
> 
>   
>     
>       PaddleDetection/configs/ppyolo/ppyolo_reader.yml
>     
>     
>         Lines 11 to 49
>       in
>       1420a1d
>     
>     
>     
>     
> 
>         
>           
>            sample_transforms: 
>         
> 
>         
>           
>              - !DecodeImage 
>         
> 
>         
>           
>                to_rgb: True 
>         
> 
>         
>           
>                with_mixup: True 
>         
> 
>         
>           
>              - !MixupImage 
>         
> 
>         
>           
>                alpha: 1.5 
>         
> 
>         
>           
>                beta: 1.5 
>         
> 
>         
>           
>              - !ColorDistort {} 
>         
> 
>         
>           
>              - !RandomExpand 
>         
> 
>         
>           
>                fill_value: [123.675, 116.28, 103.53] 
>         
> 
>         
>           
>              - !RandomCrop {} 
>         
> 
>         
>           
>              - !RandomFlipImage 
>         
> 
>         
>           
>                is_normalized: false 
>         
> 
>         
>           
>              - !NormalizeBox {} 
>         
> 
>         
>           
>              - !PadBox 
>         
> 
>         
>           
>                num_max_boxes: 50 
>         
> 
>         
>           
>              - !BboxXYXY2XYWH {} 
>         
> 
>         
>           
>            batch_transforms: 
>         
> 
>         
>           
>            - !RandomShape 
>         
> 
>         
>           
>              sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608] 
>         
> 
>         
>           
>              random_inter: True 
>         
> 
>         
>           
>            - !NormalizeImage 
>         
> 
>         
>           
>              mean: [0.485, 0.456, 0.406] 
>         
> 
>         
>           
>              std: [0.229, 0.224, 0.225] 
>         
> 
>         
>           
>              is_scale: True 
>         
> 
>         
>           
>              is_channel_first: false 
>         
> 
>         
>           
>            - !Permute 
>         
> 
>         
>           
>              to_bgr: false 
>         
> 
>         
>           
>              channel_first: True 
>         
> 
>         
>           
>            # Gt2YoloTarget is only used when use_fine_grained_loss set as true, 
>         
> 
>         
>           
>            # this operator will be deleted automatically if use_fine_grained_loss 
>         
> 
>         
>           
>            # is set as false 
>         
> 
>         
>           
>            - !Gt2YoloTarget 
>         
> 
>         
>           
>              anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]] 
>         
> 
>         
>           
>              anchors: [[10, 13], [16, 30], [33, 23], 
>         
> 
>         
>           
>                        [30, 61], [62, 45], [59, 119], 
>         
> 
>         
>           
>                        [116, 90], [156, 198], [373, 326]] 
>         
> 
>         
>           
>              downsample_ratios: [32, 16, 8] 
>         
> 
>         
>           
>            batch_size: 24 
>         
>     
>   
> 
> 
> 可以在sample_transforms中加，不过transform的预处理中 中还没有旋转，得自己手动加下，我们后续加下这个feature.

感谢您的回复，我想问如何在tranform中加自定义的旋转？有相关文档么？

**Comment by qingqing01** [comment]
@zgsxwsdxg 可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/advanced_tutorials/READER.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA%E7%AE%97%E5%AD%90

只需要在 transform/operators.py  中增加一个预处理，并且加上装饰器`@register_op`即可。

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg 可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/advanced_tutorials/READER.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA%E7%AE%97%E5%AD%90
> 只需要在 transform/operators.py  中增加一个预处理，并且加上装饰器@register_op即可。

谢谢您，非常感谢！
