### ISSUE TITLE
为什么结果只显示mAP 没单类AP

### ISSUE THREAD

**Issue by AndrewNoah** [PaddlePaddle/PaddleDetection#1460]
请问模型单类AP结果什么时候能做出来

**Comment by AndrewNoah** [comment]
训练出结果也不知道哪类AP高哪类低，没办法调整

**Comment by qingqing01** [comment]
@AndrewNoah  我们后续增加下这个功能，感谢建议！

**Comment by yghstill** [comment]
目前已经支持这个功能，欢迎试用最新develop分支的dygraph文件夹下的动态图模型，只需要在eval时加上`--classwise`即可。
