### ISSUE TITLE
 Extraneous param for class<YOLOv3Loss>: batch_size

### ISSUE THREAD

**Issue by Rosler175** [PaddlePaddle/PaddleDetection#1467]
! python -u tools/train.py -c configs/hw_configs/yolov3_mobilenet_v1_roadsign_coco_template.yml -o use_gpu=true --eval

anyone know the issue?

**Comment by qingqing01** [comment]
@Rosler175 

If you pull the latest code, you should remove batch_size in `YOLOv3Loss`

**Comment by Rosler175** [comment]
> @Rosler175
> 
> If you pull the latest code, you should remove batch_size in `YOLOv3Loss`

thank you

**Comment by Rosler175** [comment]
> @Rosler175
> 
> If you pull the latest code, you should remove batch_size in `YOLOv3Loss`
Traceback (most recent call last):
File “tools/eval.py”, line 180, in
FLAGS = parser.parse_args()
File “/home/aistudio/work/PaddleDetection/ppdet/utils/cli.py”, line 58, in parse_args
args.opt = self._parse_opt(args.opt)
File “/home/aistudio/work/PaddleDetection/ppdet/utils/cli.py”, line 67, in _parse_opt
k, v = s.split(’=’, 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by wangxinxin08** [comment]
> > @Rosler175
> > If you pull the latest code, you should remove batch_size in `YOLOv3Loss`
> > Traceback (most recent call last):
> > File “tools/eval.py”, line 180, in
> > FLAGS = parser.parse_args()
> > File “/home/aistudio/work/PaddleDetection/ppdet/utils/cli.py”, line 58, in parse_args
> > args.opt = self._parse_opt(args.opt)
> > File “/home/aistudio/work/PaddleDetection/ppdet/utils/cli.py”, line 67, in _parse_opt
> > k, v = s.split(’=’, 1)
> > ValueError: not enough values to unpack (expected 2, got 1)

使用-o 指定flag，必须要写成-o key=value，你看下是不是这个问题？

**Comment by Rosler175** [comment]
> > > @Rosler175
> > > If you pull the latest code, you should remove batch_size in `YOLOv3Loss`
> > > Traceback (most recent call last):
> > > File “tools/eval.py”, line 180, in
> > > FLAGS = parser.parse_args()
> > > File “/home/aistudio/work/PaddleDetection/ppdet/utils/cli.py”, line 58, in parse_args
> > > args.opt = self._parse_opt(args.opt)
> > > File “/home/aistudio/work/PaddleDetection/ppdet/utils/cli.py”, line 67, in _parse_opt
> > > k, v = s.split(’=’, 1)
> > > ValueError: not enough values to unpack (expected 2, got 1)
> 
> 使用-o 指定flag，必须要写成-o key=value，你看下是不是这个问题？
不行唉

**Comment by wangxinxin08** [comment]
> > > > @Rosler175
> > > > If you pull the latest code, you should remove batch_size in `YOLOv3Loss`
> > > > Traceback (most recent call last):
> > > > File “tools/eval.py”, line 180, in
> > > > FLAGS = parser.parse_args()
> > > > File “/home/aistudio/work/PaddleDetection/ppdet/utils/cli.py”, line 58, in parse_args
> > > > args.opt = self._parse_opt(args.opt)
> > > > File “/home/aistudio/work/PaddleDetection/ppdet/utils/cli.py”, line 67, in _parse_opt
> > > > k, v = s.split(’=’, 1)
> > > > ValueError: not enough values to unpack (expected 2, got 1)
> > 
> > 
> > 使用-o 指定flag，必须要写成-o key=value，你看下是不是这个问题？
> > 不行唉

可以贴一下运行的命令，我定位下问题？
