### ISSUE TITLE
为什么下载的SSD_vgg16_voc 模型拿来eval voc_2007test达不到baseline的分数？

### ISSUE THREAD

**Issue by UrlyBoy** [PaddlePaddle/PaddleDetection#1477]

**Comment by jerrywgz** [comment]
ssd_vgg16_voc的评测结果是基于voc_2017 validation这个数据集进行的，voc_2007test的话效果可能会有一些差别

**Comment by UrlyBoy** [comment]
请问ssd_vgg16_voc的训练集是什么？ 为什么我只跑到71.7连原论文中07+12的mAP都到不了

**Comment by still-wait** [comment]
@UrlyBoy voc数据集链接：https://github.com/PaddlePaddle/PaddleDetection/blob/8666e3f83397cb4787225fa6911fbe105e24c618/ppdet/utils/download.py#L55-L65
