### ISSUE TITLE
PP-YOLO一些理论问题

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#1479]
1.paddledetection是怎么开启多卡训练
2.PP-YOLO在构造时可变形卷积部分工程师有没有考虑用空洞卷积代替？
3.选择backbone时候为何没有考虑一下更加优越的resnext网络
最近写一些论文，希望设计团队老师帮我解答一下

**Comment by qingqing01** [comment]
1. 多卡训练:

   参考: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/tutorials/GETTING_STARTED_cn.md#%E8%AE%AD%E7%BB%83%E8%AF%84%E4%BC%B0%E9%A2%84%E6%B5%8B
    通过: `export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7`  设置卡的个数，然后启动即可。

2. 也可以尝试，但可变性卷积实际验证能有效提升精度。

3. ResNeXt的预测速度慢，可以参考 https://github.com/PaddlePaddle/PaddleClas 因此没有采用。


> 2020.09.21-27: 【目标检测7日打卡课】手把手教你从入门到进阶，深入了解目标检测算法的前世今生。立即加入课程QQ交流群(1136406895)一起学习吧 :)

另外，我们这个课程里也会讲解PP-YOLO，可以来听下。
