### ISSUE TITLE
导出裁剪模型

### ISSUE THREAD

**Issue by HelloAI-twj** [PaddlePaddle/PaddleDetection#1480]
我在使用导出裁剪模型命令的时候出现报错，我使用的命令是
!python slim/prune/eval.py \
-c configs/yolov4/yolov4_cspdarknet_voc.yml  \
--pruned_params "yolo_block.stack_conv.1.0.conv.weights,yolo_block.stack_conv.1.1.conv.weights,yolo_block.stack_conv.1.2.conv.weights,yolo_block.stack_conv.1.3.conv.weights,yolo_block.stack_conv.1.4.conv.weights,yolo_block.stack_conv.2.0.conv.weights,yolo_block.stack_conv.2.1.conv.weights,yolo_block.stack_conv.2.2.conv.weights,yolo_block.stack_conv.2.3.conv.weights,yolo_block.stack_conv.2.4.conv.weights" \
--pruned_ratios="0.8,0.8,0.8,0.8,0.8,0.6,0.6,0.6,0.6,0.7" \
-o weights= output/yolov4_cspdarknet_voc/model_final
报错提示为：
Traceback (most recent call last):
  File "slim/prune/eval.py", line 227, in <module>
    FLAGS = parser.parse_args()
  File "/home/aistudio/PaddleDetection/ppdet/utils/cli.py", line 58, in parse_args
    args.opt = self._parse_opt(args.opt)
  File "/home/aistudio/PaddleDetection/ppdet/utils/cli.py", line 67, in _parse_opt
    k, v = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
请问一下怎么解决呢

**Comment by willthefrog** [comment]
`weights= `多了个空格

**Comment by HelloAI-twj** [comment]
> `weights= `多了个空格

感谢

**Comment by HelloAI-twj** [comment]
> `weights= `多了个空格

感谢
