### ISSUE TITLE
visualdl

### ISSUE THREAD

**Issue by tangxiaochu123230** [PaddlePaddle/PaddleDetection#1485]
本地python==3.6.8
在tools目录的 powershell windows 输入如下命令
visualdl --logdir=./vdl_dir/scalar/ --port=8080
浏览器中输入http://localhost:8080，打不开啊（aw snap），尝试了chrome和microsoft edge
问下问题在哪

**Comment by willthefrog** [comment]
建议还是提到 visualdl 的 [repo](https://github.com/PaddlePaddle/VisualDL) 吧
