### ISSUE TITLE
训练自己数据集出问题

### ISSUE THREAD

**Issue by zjutlzt** [PaddlePaddle/PaddleDetection#150]
训练Cascade rcnn x101  数据格式是coco的格式  json文件格式是正确的
我在训练的时候 参数   num_classes: 50
自己的类 49+1

然后在tools\infer的时候用的 也是 训练的yaml
既然我设置了classes=50  那么推理过程会出现的种类ID只会在 1-49里面
那么我在推理的时候  把cocoeval.py的   catid2name 这个字典进行了修改,

把原来coco的  1-49改成了我自己的类型名

但是没想到    推理的时候出现了 56id的名字?
这是为什么?   是程序的错误吧?

**Comment by jerrywgz** [comment]
可以发下你的配置文件吗

**Comment by jerrywgz** [comment]
需要在配置中把anno_path设置为包含你50个类别的json路径
![image](https://user-images.githubusercontent.com/22989727/71614108-d6880e00-2be4-11ea-9ad5-5ceddad20962.png)

**Comment by zjutlzt** [comment]
你好 那我想问一下   要是训练自己的数据集  49+1 的   cooc的json里面有categrios    是不是然后只修改config.yaml 里面num_classes: 50   还是说要修改其他地方?   现在出现 训练和 infer 标签乱跳的情况

**Comment by zjutlzt** [comment]
architecture: CascadeRCNN
train_feed: FasterRCNNTrainFeed
eval_feed: FasterRCNNEvalFeed
test_feed: FasterRCNNTestFeed
max_iters: 180000
snapshot_iter: 10000
use_gpu: true
log_smooth_window: 20
save_dir: /home/a/disk/out
pretrain_weights: /home/a/disk/ResNeXt101_vd_64x4d_pretrained
weights: /home/a/disk/end
metric: COCO
num_classes: 50
CascadeRCNN:
  backbone: ResNeXt
  fpn: FPN
  rpn_head: FPNRPNHead
  roi_extractor: FPNRoIAlign
  bbox_head: CascadeBBoxHead
  bbox_assigner: CascadeBBoxAssigner
ResNeXt:
  depth: 101
  feature_maps: [2, 3, 4, 5]
  freeze_at: 2
  group_width: 4
  groups: 64
  norm_type: affine_channel
  variant: d
FPN:
  min_level: 2
  max_level: 6
  num_chan: 256
  spatial_scale: [0.03125, 0.0625, 0.125, 0.25]
FPNRPNHead:
  anchor_generator:
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 32
  min_level: 2
  max_level: 6
  num_chan: 256
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_positive_overlap: 0.7
    rpn_negative_overlap: 0.3
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 2000
    post_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 1000
    post_nms_top_n: 1000
  num_classes: 1


FPNRoIAlign:
  canconical_level: 4
  canonical_size: 224
  min_level: 2
  max_level: 5
  box_resolution: 7
  sampling_ratio: 2

CascadeBBoxAssigner:
  num_classes: 50
  batch_size_per_im: 512
  bbox_reg_weights: [10, 20, 30]
  bg_thresh_lo: [0.0, 0.0, 0.0]
  bg_thresh_hi: [0.5, 0.6, 0.7]
  fg_thresh: [0.5, 0.6, 0.7]
  fg_fraction: 0.25

CascadeBBoxHead:
  head: CascadeTwoFCHead
  num_classes: 50
  nms:
    keep_top_k: 200
    nms_threshold: 0.5
    score_threshold: 0.05

CascadeTwoFCHead:
  mlp_dim: 1024

LearningRate:
  base_lr: 0.0045
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [120000, 160000]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2
FasterRCNNTrainFeed:
  batch_size: 1
  dataset:
    dataset_dir: /media/c/50kinds
    annotation: 50kinds.json
    image_dir: img
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  shuffle: true
  drop_last: false
  num_workers: 2
FasterRCNNEvalFeed:
  batch_size: 1
  dataset:
    dataset_dir: dataset/coco
    annotation: annotations/instances_val2017.json
    image_dir: val2017
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32

FasterRCNNTestFeed:
  batch_size: 1
  dataset:
    annotation: dataset/coco/annotations/instances_val2017.json
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  drop_last: false
  num_workers: 2

**Comment by zjutlzt** [comment]
我说一下 为什么我会把配置文件除了总节点 以为的地方添加num_classes: 50
因为我在用上面训练的情况下   在infer的 时候在 draw_bbox 出现了 catid2name[catid]  这个catid大于50的情况   我认为是不可能的事情啊      cascade 头 只有classes50    那怎么可能出现50以上?

**Comment by zjutlzt** [comment]
我训练的过程是  1.配置yaml 各个节点设置50classes    2.直接训练
infer         1.利用训练结果infer          2.修改了coco_eval.py 里 coco17_category_info 函数的catid2name ={}  把1-49的id  对应的  标签替换成我自己的数据集   3.运行 tools\infer.py      但是出现 种类乱来的情况

**Comment by jerrywgz** [comment]
1. num_classes只需要最上面设置了就可以完成共享
2. 像我刚说的，不能只修改catid2name，因为预测的label是0-49，通过clsid2catid映射之后可能会超出50，在catid2name就会映射到不是你数据集的标签。
你可以在tools/infer.py中先打印下res看看结果是不是符合预期的，然后需要把clsid2catid改成{k:k for k in range(50)}

**Comment by zjutlzt** [comment]
好的   训练的时候  需要特意去更改   代码测试吗     还是 训练是直接读取  json里的 categories的?

**Comment by jerrywgz** [comment]
训练时会根据json来得到catid2clsid和cname2cid，只需要修改json路径和num_classes就可以

**Comment by zjutlzt** [comment]
好的想想  推理的问题已经解决了     还有 就是  默认配置里面 为什么没有 设置  训练  800*1333这个参数?    要是留空的话    尺寸是多少呢?

**Comment by jerrywgz** [comment]
训练默认的处理方式是：等比例将输入缩放至短边为800，如果此时长边大于1333，再等比例缩放至长边为1333

**Comment by zjutlzt** [comment]
感谢
