### ISSUE TITLE
Anchor重新聚类. kmeans貌似不执行

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#1501]
<img width="904" alt="WechatIMG98794" src="https://user-images.githubusercontent.com/45937014/94162928-d722ac00-feb9-11ea-9b6c-ca40d3ce9b2d.png">

标红区域就是0%  所以导致给的anchors 是不是都没有任何作用  或者可能会有副作用？

**Comment by wangxinxin08** [comment]
使用yolov2聚类的方法有两种终止条件：

1. 一种是anchor收敛，也就是kmeans当前的assignment不再发生改变，此时聚类的中心也不会再改变，聚类收敛

2. 一种达到设定迭代次数，此时聚类也会终止
看你上面的结果，应该是kmeans随机选取的结果直接收敛了

**Comment by zachary-zheng** [comment]
> 使用yolov2聚类的方法有两种终止条件：
> 
> 1. 一种是anchor收敛，也就是kmeans当前的assignment不再发生改变，此时聚类的中心也不会再改变，聚类收敛
> 2. 一种达到设定迭代次数，此时聚类也会终止
>    看你上面的结果，应该是kmeans随机选取的结果直接收敛了

原来如此，我也碰到这样疑问，别外avg_iou计算的是谁和谁的iou呢？谢谢解答！

**Comment by wangxinxin08** [comment]
> > 使用yolov2聚类的方法有两种终止条件：
> > 
> > 1. 一种是anchor收敛，也就是kmeans当前的assignment不再发生改变，此时聚类的中心也不会再改变，聚类收敛
> > 2. 一种达到设定迭代次数，此时聚类也会终止
> >    看你上面的结果，应该是kmeans随机选取的结果直接收敛了
> 
> 原来如此，我也碰到这样疑问，别外avg_iou计算的是谁和谁的iou呢？谢谢解答！

所有真是的bounding box与聚类中心(即anchor)的iou
