### ISSUE TITLE
pp-yolo的eval脚本运行非常慢

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleDetection#1503]
aistudio@jupyter-89442-1017193:~/work/PaddleDetection$ python -u tools/eval.py -c ../ppyolo.yml -o weights=output/ppyolo/100
True
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2020-09-25 10:59:23,602-INFO: places would be ommited when DataLoader is not iterable
W0925 10:59:23.772264   612 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0925 10:59:23.778043   612 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2020-09-25 11:00:35,269-INFO: 100 Test iter 0
imgs_num 1 True 1
imgs_num 2 True 1
imgs_num 3 True 1
imgs_num 4 True 1
imgs_num 5 True 1
imgs_num 6 True 1
imgs_num 7 True 1
^C^C^C2020-09-25 11:06:19,304-INFO: KeyboardInterrupt: main proc 612 exit, kill subprocess []

基本上一张图片eval需要1分钟，想知道什么原因
[ppyolo.txt](https://github.com/PaddlePaddle/PaddleDetection/files/5280385/ppyolo.txt)

**Comment by thunder95** [comment]
运行了一万多iter还这样:

2020-09-26 08:42:42,368-WARNING: The number of valid bbox detected is zero.
             Please use reasonable model and check input data.
             stop eval!

**Comment by qingqing01** [comment]
@thunder95 是不是模型没有训练好，模型比较差呢？直接预测COCO的模型慢吗？
