### ISSUE TITLE
where dose the std and mean value come from?

### ISSUE THREAD

**Issue by dongyu-HIT** [PaddlePaddle/PaddleDetection#1504]
where dose the std and mean value come from?
std [0.229,0.224,0.225]
mean [0.485, 0.456, 0.406]
This confuses me

**Comment by qingqing01** [comment]
@dongyu-HIT 

In the data agumentation, std and mean is used to normalize image, y =  (x - mean)/std, x is the input image, y is the normalized image.

Usually, if use the pretrained ImageNet classification models, the mean and std are same with them in classification task. Usually come from ImageNet.

**Comment by songyuc** [comment]
Hi, @qingqing01 , if I want to train the model from scratch, what `mean` and `std` should I set?
