### ISSUE TITLE
vs2019 cmake问题（预测框问题）

### ISSUE THREAD

**Issue by Viktor-Paul** [PaddlePaddle/PaddleDetection#1505]
初期也遇到了[https://github.com/PaddlePaddle/PaddleDetection/issues/987](url) 相同的问题，就是c++预测时在cmd中没有报错，但是也没有生成output.jpg，python端预测正常。
按照@xiegegege提供的方法，在导出模型的时候加个参数-o TestReader.inputs_def.image_shape=[3,640,640]（图片大小可以随意设），c++预测有输出结果，但是预测框不对，python端也不正常了。自定义的数据集，使用的模型是faster_rcnn_r50_fpn_1x。

**Comment by xiegegege** [comment]
这个已经修复了的，现在不用加-o TestReader.inputs_def.image_shape参数也能正常预测了的，你要不更新下检测库的代码？然后用最新的release/0.4分支

**Comment by Viktor-Paul** [comment]
好的，我试试，谢谢您

**Comment by Viktor-Paul** [comment]
@xiegegege 您好，预测正常了，但是并没有直接生成可视化结果output.jpg,需要添加output_dir路径才可以
![微信图片_20200925160808](https://user-images.githubusercontent.com/51936391/94242939-57dcb900-ff49-11ea-8ea0-a77d0b7ff57f.png)
官网[https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/cpp/docs/windows_vs2019_build.md](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/cpp/docs/windows_vs2019_build.md)这里还没有更新，建议可以修改一下。

**Comment by xiegegege** [comment]
好的，谢谢反馈～

**Comment by wangxinxin08** [comment]
> @xiegegege 您好，预测正常了，但是并没有直接生成可视化结果output.jpg,需要添加output_dir路径才可以
> ![微信图片_20200925160808](https://user-images.githubusercontent.com/51936391/94242939-57dcb900-ff49-11ea-8ea0-a77d0b7ff57f.png)
> 官网https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/cpp/docs/windows_vs2019_build.md这里还没有更新，建议可以修改一下。

多谢反馈，使用cpp预测，不指定保存图片的路径，预测图片不保存的原因是，保存图片的默认路径是output，需要保证这个文件夹已经被创建，后续会更新代码将图片保存在当前目录下，另外，官网文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/cpp/docs/windows_vs2019_build.md需要更新的地方是指哪里？

**Comment by Viktor-Paul** [comment]
嗯嗯，我明白，但是官网没有提及保存图片的默认路径是output，需要保证这个文件夹已经被创建，第一次使用官方文档肯定不懂，“图片文件可视化预测结果会保存在当前目录下output.jpeg文件中”这句话的意思。个人感觉需要说明一下，这样让大家易于理解。

**Comment by wangxinxin08** [comment]
> 嗯嗯，我明白，但是官网没有提及保存图片的默认路径是output，需要保证这个文件夹已经被创建，第一次使用官方文档肯定不懂，“图片文件可视化预测结果会保存在当前目录下output.jpeg文件中”这句话的意思。个人感觉需要说明一下，这样让大家易于理解。

好的
