### ISSUE TITLE
关于训练过程的map的疑惑

### ISSUE THREAD

**Issue by tangxiaochu123230** [PaddlePaddle/PaddleDetection#1506]
faster rcnn的map是没有除以100，但是mask rcnn是有除以100？
看到训练faster的map是大于1，mask的map是小于1

**Comment by qingqing01** [comment]
@tangxiaochu123230 

1. 如果是COCO格式的数据，yml中的metric设置一般都是coco，通过COCO API评估出来的，是小于1。
2. VOC格式数据，yml中的metric一般设置voc，最新的代码 https://github.com/PaddlePaddle/PaddleDetection/pull/1442/files 以修正成百分比 (小于1了)。

不知道，您是不是这个疑惑
