### ISSUE TITLE
关于如何把自己的模型参数封装成预训练模型格式的问题

### ISSUE THREAD

**Issue by hellobinker** [PaddlePaddle/PaddleDetection#1513]
目前我看到预训练的模型都是.tar格式的
但是自己训练出的模型参数都是pdparams，请问如何封装可以加载的预训练模型，以便在更换模型的时候，不浪费训练参数

**Comment by still-wait** [comment]
@hellobinker .tar格式是paddle 1.7之前保存模型的格式，将零散的文件放在一个文件夹中。现在paddle 1.7之后保存的模型都是存储在pdparams一个文件中。PaddleDetection同时都支持这两种格式，不必担心这个问题。

**Comment by wangshaobobetter** [comment]
> @hellobinker .tar格式是paddle 1.7之前保存模型的格式，将零散的文件放在一个文件夹中。现在paddle 1.7之后保存的模型都是存储在pdparams一个文件中。PaddleDetection同时都支持这两种格式加载，不必担心这个问题。

i直接进行预测是模型pdparams或者pdmodel都可以，可是训练的时候将以上的路径设置在pretrainweights就报错，提示格式有问题，还是得用之前tar格式的链接从头训练

**Comment by rolongohaolin** [comment]
请问这个问题已经有解决办法了吗？
