### ISSUE TITLE
训练自己的backbone

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#1519]
paddledetection中怎么训练自己的backbone

**Comment by qingqing01** [comment]
@qdd1234 




1. 如果是新的backbone，增加到 https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/ppdet/modeling/backbones 或 自己的一个文件夹也可以，并进行注册。 具体参考: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/advanced_tutorials/MODEL_TECHNICAL.md#backbone%E7%BC%96%E5%86%99

2. 在YML中配置backbone，同样参考上面的文档

**Comment by qdd1234** [comment]
那预训练权重那块呢，咋弄，我的backbone没有网址下载啊

**Comment by qingqing01** [comment]
@qdd1234  pretrained_weights 指定指定预训练权重的路径即可。 本身的设计是: 如果是网站就下载解压、如果是本地预训练权重路径直接读取。

**Comment by still-wait** [comment]
> 那预训练权重那块呢，咋弄，我的backbone没有网址下载啊

主流backbone在[PaddleClas](https://github.com/PaddlePaddle/PaddleClas)中都有预训练权重，都有下载链接了，可自行下载，如果是自定义的backbone，需要自己在imagenet数据集上训练。或者模型训练不加载预训练模型，从零开始训练，不过训练时间可能更长。

**Comment by qdd1234** [comment]
是直接将yaml文件中pretrained_weghted 直接注释掉

**Comment by qingqing01** [comment]
@qdd1234 直接注释掉的话，是随机初始化进行训练。比如人脸检测 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/face_detection/blazeface.yml 中也没有预训练，也是可以试下，不过就需要注意loss是否容易爆炸、能很好的训练起来。
