### ISSUE TITLE
cmakelists.txt编译不通

### ISSUE THREAD

**Issue by x12901** [PaddlePaddle/PaddleDetection#1521]
https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.6.0/deploy/cpp/docs/windows_vs2019_build.md
文档好像没有更新，我的配置
![image](https://user-images.githubusercontent.com/30824839/94390474-61eafb80-0185-11eb-9302-5f71ea1c9c2e.png)
报了一个错误
![image](https://user-images.githubusercontent.com/30824839/94390528-81822400-0185-11eb-8ebe-df4922697f52.png)
有个疑问PADDLE_DIR指的是哪个目录，指向下载的PaddlePaddle C++ 预测库 fluid_inference_dir也不行
![image](https://user-images.githubusercontent.com/30824839/94390743-1d139480-0186-11eb-9c9c-7928b81094d7.png)

**Comment by qingqing01** [comment]
@x12901 上面发的文档是在PaddleSeg里，看下 https://github.com/PaddlePaddle/PaddleDetection/blob/master/deploy/cpp/docs/windows_vs2019_build.md 这个文档呢

**Comment by x12901** [comment]
> @x12901 上面发的文档是在PaddleSeg里，看下 https://github.com/PaddlePaddle/PaddleDetection/blob/master/deploy/cpp/docs/windows_vs2019_build.md 这个文档呢

不好意思发错了，我就是看了这个才发现跟这个一样的，所以没有解决https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.6.0/deploy/cpp/docs/windows_vs2019_build.md
还有个问题
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/advanced_guide/inference_deployment/inference/windows_cpp_inference.html#id3
使用脚本编译运行demo的时候出现路径BUG该怎么解决

![image](https://user-images.githubusercontent.com/30824839/94398130-92d42c00-0197-11eb-8089-c280669038df.png)
