### ISSUE TITLE
用c++部署循环跑图片集时报错

### ISSUE THREAD

**Issue by Tinagao222** [PaddlePaddle/PaddleDetection#1522]
paddledetection版本是0.3，模型用的cascade mask rcnn，win10，vs2019

![捕获](https://user-images.githubusercontent.com/42574246/94394515-1f7aec00-0190-11eb-8e16-7368a7677cc3.JPG)

**Comment by Superjomn** [comment]
麻烦给出完整的预测代码，以便阅读和复现

另外，可以 debug 看看，栈挂到了哪里，是在预测库里还是外面的程序

**Comment by Tinagao222** [comment]
> 麻烦给出完整的预测代码，以便阅读和复现
> 
> 另外，可以 debug 看看，栈挂到了哪里，是在预测库里还是外面的程序

下面是main.cc的代码，栈挂到哪里是怎么调试啊，不太明白

#include <glog/logging.h>
#include <iostream>

#include <string>

#include <vector>



#include "include/object_detector.h"
#include <fstream>

using namespace cv;
using namespace std;
typedef unsigned char byte;

struct NN
{
    cv::Mat* src;
    int length;
    int* detect;
};

//extern "C" __declspec(dllexport) NN PredictImage(char* model_dir, byte *input, int height, int width);

char * model_dir = "D:\\tina\\NN\\BaiduAI\\model";
std::string image_path = "C:\\Users\\administered\\Desktop\\Test";


NN PredictImage(char * model_dir,byte* input, int height, int width) {
    // Load model and create a object detector  
    bool use_gpu = true;
    std::string run_mode = "fluid";
    //std::string model_dir = "D:\\tina\\NN\\BaiduAI\\model";
    PaddleDetection::ObjectDetector det(model_dir, use_gpu = true, run_mode = "fluid");
    // Store all detected result
    PaddleDetection::ObjectDetector* detect = &det;  
    std::vector<PaddleDetection::ObjectResult> result;
    cv::Mat im(height, width, CV_8UC3, input);
    cout << "1";
    cout << "rows" <<im.rows;
    cout << "cols" << im.cols;
    //cv::imwrite("out.jpeg",im);
    detect->Predict(im, &result);
    cout << "2";
    vector<int> label;
    for (const auto& item : result) {
        label.push_back(item.class_id);
        label.push_back((int)(item.confidence*100));
        label.push_back(item.rect[0]);
        label.push_back(item.rect[1]);
        label.push_back(item.rect[2]);
        label.push_back(item.rect[3]);
        
    }
    cout << "3";
    int length = label.size();
    //Visualization result
    auto labels = detect->GetLabelList();
    auto colormap = PaddleDetection::GenerateColorMap(length);
    cv::Mat vis_img = PaddleDetection::VisualizeResult(im, result, labels, colormap);
    //cv::Mat vis_img = PaddleDetection::VisualizeResult(im, result, labels, colormap);
    //return new cv::Mat(vis_img);
    cout << "4";
    int * p = new int[length];
    std::memcpy(p, &label[0], length * sizeof(label[0]));
    cout << "5";
    static NN res;
    res.src = new cv::Mat(vis_img);
    res.length = length;
    res.detect = p;
    result.clear();
    return res;
}

byte* matToBytes(cv::Mat image){
    int size = image.rows*image.cols* image.channels();
    byte* bytes = new byte[size];  // you will have to delete[] that later
    std::memcpy(bytes, image.data, size * sizeof(byte));
    return bytes;
}

//
int main(int argc, char** argv) {

    // parsing command-line

    //google::parsecommandlineflags(&argc, &argv, true);

    //绝对路径下  类型为.bmp的照片
    string pattern_jpg = "C:\\Users\\administered\\Desktop\\Test\\*.jpg";

    //创建一个String类型 名字为image_files的vector
    vector<String> image_files;

    //把pattern_bmp路径下所有文件名存在image_files中
    glob(pattern_jpg, image_files);

    for (int i = 0; i < image_files.size(); i++) {
        cv::Mat im = cv::imread(image_files[i], 1);
        cout << image_files[i] << endl;
        cv::Mat src;
        cv::resize(im, src, cv::Size(1333, 800));
        byte* pImg = matToBytes(src);
        NN result = PredictImage(model_dir, pImg, 800, 1333);
        cv::imwrite("out.jpeg", *result.src);
        
        //cout << result.detect[0] << endl;
        //cout << result.detect[1] << endl;
        //cout << result.detect[2] << endl;
        //cout << result.detect[3] << endl;
        //cout << result.detect[4] << endl;
        //cout << result.detect[5] << endl;
    }

    return 0;

}

**Comment by ysh329** [comment]
请问是什么预测库呀，是PaddleInference嘛还是Paddle-Lite呀

**Comment by Tinagao222** [comment]
> 请问是什么预测库呀，是PaddleInference嘛还是Paddle-Lite呀

paddledetection

**Comment by Tinagao222** [comment]
> 麻烦给出完整的预测代码，以便阅读和复现
> 
> 另外，可以 debug 看看，栈挂到了哪里，是在预测库里还是外面的程序

我发现是循环加载模型导致的，但是，PaddleDetection::ObjectDetector det(model_dir, use_gpu = true, run_mode = "fluid");

**Comment by x12901** [comment]
> > 麻烦给出完整的预测代码，以便阅读和复现
> > 另外，可以 debug 看看，栈挂到了哪里，是在预测库里还是外面的程序
> 
> 我发现是循环加载模型导致的，但是，PaddleDetection::ObjectDetector det(model_dir, use_gpu = true, run_mode = "fluid");

预测代码maskrcnn好像只有边框，不能输出mask啊，请问大佬有思路吗？
