### ISSUE TITLE
anchor_free/fcos预测无输出

### ISSUE THREAD

**Issue by ralph0813** [PaddlePaddle/PaddleDetection#1524]
使用fcos配置文件，将配置文件顶部 num_classes 和 FCOSHead 中 num_classes 改为1，并且重新训练之后，预测无结果输出，但是eval好像正常。

**Comment by jerrywgz** [comment]
可以发下你的配置文件吗

**Comment by ralph0813** [comment]
不支持上传.yml改成了.txt
[fcos_dcn_r50_fpn_1x.txt](https://github.com/PaddlePaddle/PaddleDetection/files/5296120/fcos_dcn_r50_fpn_1x.txt)

**Comment by jerrywgz** [comment]
需要确认下预测的时候anno_path有没有被正确加载，这里如果没有设置dataset_dir的话需要将anno_path设置为相对于PaddleDetection的路径，比如dataset/coco/annotations/instances_val2017.json

**Comment by ralph0813** [comment]
不设置的时候默认加载了coco80类的label，我尝试指定了也没用。

**Comment by ralph0813** [comment]
最开始没注意FCOSHead里也有num_classes，用了默认的80类，是可以有输出结果的，改成1类之后反而不行了。

**Comment by jerrywgz** [comment]
把testreader的anno_path改成dataset/coco/annotations/instances_val2017.json 试下呢，因为如果没有找到json的话testreader会默认使用coco数据集的标签，这样用80类的话反而是可以对上的

**Comment by ralph0813** [comment]
提issue之前就测试过了，不行。

**Comment by qingqing01** [comment]
可以试用下最新的动态图版本~
