### ISSUE TITLE
制作voc数据集出现错误

### ISSUE THREAD

**Issue by ww19960229** [PaddlePaddle/PaddleDetection#1525]
![1](https://user-images.githubusercontent.com/50479376/94446425-372b9200-01db-11eb-8c28-a1a71a087328.png)
![2](https://user-images.githubusercontent.com/50479376/94446432-385cbf00-01db-11eb-973e-98e5f6644ea2.png)
 我的数据集也是按照说明上弄好了，结果输入程序就出错了，这到底是哪里错了啊，数据集位置在work/PaddleDetection/dataset/VOCdevkit里

**Comment by jerrywgz** [comment]
上面的路径path/to/dataset/VOCdevkit/VOC2007需要改为你实际voc的数据路径，下面的path/to/dataset也是一个意思

**Comment by ww19960229** [comment]
我将voc转换成coco数据集格式，其中val.json文件这样，是不是不对啊
![1111](https://user-images.githubusercontent.com/50479376/94510386-3e898480-0249-11eb-8e1a-d2062cf599d7.png)

**Comment by jerrywgz** [comment]
这个看上去应该没问题，annotation里是每个box的标注信息
