### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#1526]
WARNING: The actual image width: 608 is not equal to the width: 0.0 in annotation, and update sample['w'] by actual image width.
这个警告具体是指我的数据哪里有问题？

**Comment by jerrywgz** [comment]
就是实际图片的宽度是608，但是在标注数据里对应的w是0，这里就自动把w更新成实际图片的宽度

**Comment by qingqing01** [comment]
@qdd1234 如果没问题，这个issue就关闭了。
