### ISSUE TITLE
PaddleDetection边训边导出模型报错

### ISSUE THREAD

**Issue by dmxj** [PaddlePaddle/PaddleDetection#1527]
使用PaddleDetection 最新的release/0.4的版本训练ppyolo，边训边导出模型（**只导出最优模型**），训练和导出模型的代码都是和tools/train.py tools/export_model.py保持一致，在第二次导出模型的时候，报了以下错误：
![image](https://user-images.githubusercontent.com/6835981/94514745-8feb4100-0254-11eb-916f-b8d5a640667a.png)

环境信息：
系统：Ubuntu 16.04
python: 3.6.3
显卡：Tesla V100
Cuda: 10.1.243
PaddlePaddle: 1.8.4
PaddleDetection: release/0.4
训练配置文件：
[config.yml.txt](https://github.com/PaddlePaddle/PaddleDetection/files/5296537/config.yml.txt)

tks!

**Comment by jerrywgz** [comment]
想确认下训练和导出模型会用到同一张卡吗，我们这边只验证过边训练边测试的情况。你那边是修改了训练逻辑吗

**Comment by dmxj** [comment]
> 想确认下训练和导出模型会用到同一张卡吗，我们这边只验证过边训练边测试的情况。你那边是修改了训练逻辑吗

@jerrywgz 
是的，会用到同一张卡，我的机器是单卡，我这边是修改训练逻辑，在评估的时候将当前模型导出，第一次导出没报错，第二次导出会报以上错。之前在release 0.3上同样的边训边导出的逻辑没出现过这个问题。导出的时候也会执行exe.run，我逐步定位了下，就是在导出的时候执行exe.run时报的错～

**Comment by dmxj** [comment]
有人可以帮忙看一下吗？？Paddle 1.8.4/PaddleDetection release0.4稳定复现-_-||

**Comment by qingqing01** [comment]
@dmxj 建议还是训练完之后，导出最好的预测模型。 这个问题，我们后续看下。

**Comment by qingqing01** [comment]
建议还是训练完后，选特定模型导出。
