### ISSUE TITLE
用c++部署循环加载模型时报错

### ISSUE THREAD

**Issue by Tinagao222** [PaddlePaddle/PaddleDetection#1528]
昨天提的问题不小心关了，重新发一下。现在测试下来发现，问题出现在将加载模型放到了函数里面，每遍历一张图片，就会加载一次模型，然后就会报如下的错误。如果将加载模型放在函数外，只加载一次，运行是正常的。但是我最终的目的是把c++的程序打包成.dll，给C#调用，所以目前想到的方法只能把加载模型放在函数里面。请各位大神看看，有没有解决方法。
![image](https://user-images.githubusercontent.com/42574246/94519703-9af69f00-025d-11eb-824f-1c602f15f2a8.png)

**Comment by x12901** [comment]
> 昨天提的问题不小心关了，重新发一下。现在测试下来发现，问题出现在将加载模型放到了函数里面，每遍历一张图片，就会加载一次模型，然后就会报如下的错误。如果将加载模型放在函数外，只加载一次，运行是正常的。但是我最终的目的是把c++的程序打包成.dll，给C#调用，所以目前想到的方法只能把加载模型放在函数里面。请各位大神看看，有没有解决方法。
> ![image](https://user-images.githubusercontent.com/42574246/94519703-9af69f00-025d-11eb-824f-1c602f15f2a8.png)

楼主成功部署了吗？想问下怎么操作的

**Comment by Tinagao222** [comment]
在大神的帮助下，最终解决了。可以将加载模型和预测写成两个函数，打包的.dll有这两个函数接口。加载模型这个函数的输出可定义成IntPtr，C#那边也是按指针接收。

**Comment by sannnyu** [comment]
也就是把LoadModel函数里的PaddleDetection::ObjectDetector det(model_dir, use_gpu,run_mode, gpu_id);拿出来，下次Predict的时候就不要再声明一个det了？
