### ISSUE TITLE
如何获取某个类别的Map值

### ISSUE THREAD

**Issue by gtfaiwxm** [PaddlePaddle/PaddleDetection#1529]
你好，在ppyolo进行验证时，想查看某个类别的map值，应该如何设置？

**Comment by jerrywgz** [comment]
这个功能我们暂时还没有支持，我们会记录下～

**Comment by liuhuiCNN** [comment]
动态图已支持，添加 `--classwise`参数即可。请参考文档： https://github.com/yghstill/PaddleDetection/blob/8d95156bcbfbbb12067f0418449bf3d9bb74d9f1/dygraph/docs/tutorials/GETTING_STARTED_cn.md
