### ISSUE TITLE
blazeface_keypoint 人脸关键点检测模型输出格式

### ISSUE THREAD

**Issue by dongsen112** [PaddlePaddle/PaddleDetection#1535]
请问blazeface_keypoint模型输出的含义都是什么，图片是使用Netron解析的截图。
不清楚红框出的四个输出含义是什么。
![image](https://user-images.githubusercontent.com/61857855/94663608-6efe1b00-033c-11eb-9edf-2ed92f806596.png)

**Comment by willthefrog** [comment]
应该分别是bbox, face_index, keypoints 和 prior_box

参考[这里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/architectures/blazeface.py#L121)

**Comment by dongsen112** [comment]
> 应该分别是bbox, face_index, keypoints 和 prior_box
> 参考这里

谢谢回答，bbox, face_index基本了解了。但是keypoints和prior_box的输出怎么转化成可用的信息呢。
调试时，prior_box的个数是2688，取值范围基本在【0，1】，如何判断哪些是有用的，哪些是没有用的数据呢？另外，prior_box[0] prior_box[1] prior_box[2] prior_box[3]具体的含义能不能告诉一下。谢谢

**Comment by willthefrog** [comment]
@still-wait  能否帮忙解释一下？

**Comment by still-wait** [comment]
@dongsen112

**Comment by still-wait** [comment]
@dongsen112 
1. prior_box会根据设置的`aspect_ratios `、`min_sizes `和`steps`等生成一系列anchor锚框，这些锚框是归一化的，所以取值在[0,1]之间，判断哪些有用是通过nms筛选得到检测质量较高的检测框，然后将这些归一化的框resize回原图中，这样就完成了检测流程。根据face_index输出每个检测框中的keypoints的信息。
2. 模型的backbone中输出不同尺度的feature map，依次输入到`fluid.layers.prior_box`得到不同尺度的锚框，生成prior_box[0], prior_box[1]...这些list，然后concat到一起，得到prior_box的总个数，如2688。
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/architectures/blazeface.py#L161

**Comment by dongsen112** [comment]
> @dongsen112
> 
> 1. prior_box会根据设置的`aspect_ratios `、`min_sizes `和`steps`等生成一系列anchor锚框，这些锚框是归一化的，所以取值在[0,1]之间，判断哪些有用是通过nms筛选得到检测质量较高的检测框，然后将这些归一化的框resize回原图中，这样就完成了检测流程。根据face_index输出每个检测框中的keypoints的信息。
> 2. 模型的backbone中输出不同尺度的feature map，依次输入到`fluid.layers.prior_box`得到不同尺度的锚框，生成prior_box[0], prior_box[1]...这些list，然后concat到一起，得到prior_box的总个数，如2688。
>    https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/architectures/blazeface.py#L161

感谢回答。但是还是没完全理解，麻烦帮忙再解答一下，谢谢。
1.keypoint的输出是【?,?,10】，这是个几乘几的三维数组呢，每个元素的含义是什么，根据哪个条件能筛选出来可用的元素。
2.prior_box是个四维数组，每个元素的含义是预测框的四个顶点吗？如果是的话，如何从 2688个预测框中筛选出可用的呢？
3.是否有demo可以参考？
4.有可以检测瞳孔的模型吗？

**Comment by yghstill** [comment]
@dongsen112

**Comment by yghstill** [comment]
@dongsen112 
1.keypoint的输出是[N, num_prior_box, 10]，N表示batch大小，num_prior_box表示prior_box输出的个数，10表示生成5个人脸关键点(x0,y0,x1,y1,x2,y2......)。其中每个检测框会有和它匹配的关键点。
2. prior_box四维分别是候选框左上顶点(x0,y0),右下坐标(x1,y1)。训练时通过和gt信息计算loss，收敛这些预测框坐标，预测时，通过nms滤除无效检测框。
3.https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/face_detection/blazeface_keypoint.yml  ppdet里有人脸关键点检测的模型，可直接使用。
4.目前还没有检测瞳孔的模型。

**Comment by dongsen112** [comment]
> @dongsen112
> 1.keypoint的输出是[N, num_prior_box, 10]，N表示batch大小，num_prior_box表示prior_box输出的个数，10表示生成5个人脸关键点(x0,y0,x1,y1,x2,y2......)。其中每个检测框会有和它匹配的关键点。
> 2. prior_box四维分别是候选框左上顶点(x0,y0),右下坐标(x1,y1)。训练时通过和gt信息计算loss，收敛这些预测框坐标，预测时，通过nms滤除无效检测框。
> 3.https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/face_detection/blazeface_keypoint.yml ppdet里有人脸关键点检测的模型，可直接使用。
> 4.目前还没有检测瞳孔的模型。

@yghstill 
谢谢回答，按照您的回复，就是说blazeface_keypoint只能检测人脸的五个关键点。
那目前有能检测68或78个关键点的模型吗？

**Comment by qingqing01** [comment]
PaddleDetection中还没有68、78个点关键点。
