### ISSUE TITLE
c++ 预测，copy_from_cpu报错

### ISSUE THREAD

**Issue by Fauny** [PaddlePaddle/PaddleDetection#1538]
# 环境：
1. cuda: v10.0
1. cudnn: v7.6
1. 使用预编译C++ 预测库[cuda10.0_cudnn7_avx_mkl (1.8.4-post107)](https://paddle-wheel.bj.bcebos.com/1.8.4/win-infer/mkl/post107/fluid_inference_install_dir.zip)
1. windows 10 家庭版
1. vs2019
1. GPU：mx230
1. 模型：pp-yolo

# 状况
1. python 版安装 paddlepaddle-gpu v1.8.5, 使用GPU或CPU均可正常工作
1. cpp版，CPU正常
1. cpp版， 使用GPU模式，抛出异常，定位于`in_tensor->copy_from_cpu(inputs_.ori_im_size_.data())`
异常信息：
```
0x00007FFAAE4DA719 处(位于 main.exe 中)有未经处理的异常: 
Microsoft C++ 异常: std::runtime_error，
位于内存位置 0x0000005357DCF4E0 处。
```
console：
```
...
W1003 13:18:52.731598  3000 device_context.cc:252] 
Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.0
```

**Comment by jerrywgz** [comment]
能否提供下模型导出是的log以及导出的配置文件呢，看起来可能是导出模型时没有ori_im_size导致的

**Comment by Fauny** [comment]
已经解决，是因为线程冲突
