### ISSUE TITLE
SSD 模型的C++推理部署

### ISSUE THREAD

**Issue by lianDaniel** [PaddlePaddle/PaddleDetection#154]
在C++推理部署中，配置中的FEEDS_SIZE表示    # 输入的tensor数量，其中3是faster rcnn
,2是yolo，并且指出了一般的模型这个值为1，但是在文件preprocessor/preprocessor_detection.cpp，在feeds_size为2的情况，却没有图像读取代码。
`    cv::Mat im1 = cv::imread(fname, -1);
    cv::Mat im;
    if (_config->_feeds_size == 3) {  // faster rcnn
        im1.convertTo(im, CV_32FC3, 1/255.0);
    } else if (_config->_feeds_size == 2) {  // yolo v3
        im = im1;
    }
    if (im.data == nullptr || im.empty()) {
    #ifdef _WIN32
        std::cerr << "Failed to open image: " << fname << std::endl;
    #else
        LOG(ERROR) << "Failed to open image: " << fname;
    #endif
        return false;
    }`
不知道是否是在别的地方有所设置？或者说是不是当前的C++推理代码并没有考虑SSD模型。

**Comment by jerrywgz** [comment]
ssd和yolo都是属于FEEDS_SIZE=2的情况，大部分预处理也是复用yolo的。不同点在于ssd不需要对图像做归一化处理而yolo需要，这里我们需要再完善下ssd的预处理情况，感谢反馈

**Comment by lianDaniel** [comment]
谢谢您的回复，我这边测试了以下FEEDS_SIZE=2，对于ssd模型的推理使用，会报错：
`E0102 10:58:00.411834 16840 api_impl.cc:191] wrong feed input size, need 1 but get 2
E0102 10:58:00.411834 16840 api_impl.cc:143] fail to set feed
Failed: NativePredictor->Run() return false at batch: 0`
上述ssd模型的导出命令为：
`python tools/export_model.py -c configs/ssd/ssd_mobilenet_v1_voc.yml \
        --output_dir=./inference_model \
        -o weights= https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_voc.tar`
在可视化的结构上，ssd模型只有image一个feed，并没有yolo对应的im_shape等feed。
![yolov3_mobilenet_v1](https://user-images.githubusercontent.com/22784030/71656384-f0a52600-2d75-11ea-85db-131f81ddc012.png)
期待您的回复~

附件附上，上述ssd模型和yolov3的经过Netron的可视化结果
ssd模型：
![ssd_mobilenet_v1_voc](https://user-images.githubusercontent.com/22784030/71656235-92784300-2d75-11ea-8eea-4b1c07b55cbc.png)
yolov3 模型：

**Comment by sjtubinlong** [comment]
@lianDaniel 现在的 C++预测只支持 faster_rcnn 和 yolov3，我近期会完成ssd 模型的适配，稍后完成后告知。

**Comment by qingqing01** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/deploy 已完成
