### ISSUE TITLE
用了paddle slim里面的剪枝策略r578，检测速度反而变慢是什么原因

### ISSUE THREAD

**Issue by luoyinTT** [PaddlePaddle/PaddleDetection#1540]
剪枝网络为：ppyolo_2x

**Comment by heavengate** [comment]
请问裁剪前后的检测速度是怎么测试的呢，建议用README中的benchmark测试方法测试，对齐部署环境，直接eval.py测试的话会有很多冗余时间开销

**Comment by heavengate** [comment]
鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen这个issue~
