### ISSUE TITLE
请问一下，如果用PaddleDetection训练自己的数据集的话，学习率该怎么设置呢？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleDetection#1541]
尊敬的开发者，你好！
请问一下，如果用PaddleDetection训练自己的数据集的话，学习率该怎么设置呢？
期待你的回复，十分感谢！

**Comment by still-wait** [comment]
学习率一般和GPU卡数和batch size有关，PaddleDetection中的模型配置文件大多数是在八卡GPU下训练得到的，如果GPU数量变化，学习率也要线性变换，具体可参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/FAQ.md ，batch size变化学习率也按照上述规则进行变换即可，如果模型还是训练不稳定或出nan，可凭经验再适当减小学习率。
