### ISSUE TITLE
训练轮数换算

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#1542]
为何有的程序50轮和另一个程序的100000轮训练时间差不多，这之间的换算关系是什么

**Comment by still-wait** [comment]
@qdd1234 每个模型的训练时间都不尽相同，类如SSD、YOLO系列模型加入很多数据预处理操作，并且batch size比较大，所以训练比较耗时。RCNN系列模型batch size小，数据预处理耗时较少，所以训练时间较少。

**Comment by qingqing01** [comment]
@qdd1234  

RCNN系列两阶段模型，一般收敛速度快，比如FasterRCNN 1x，在COCO上，总的训练样本约118287张，batch_size是8 (每个GPU上是1，总共8个GPU)，总共训练的轮数是180000， 总共的epoch 180000/(118287/8) = 12个epoch。

YOLO单阶段模型，一般收敛速度较慢，比如YOLOv3，在COCO上，batch_size是64 (每个GPU上是8， 总共8个GPU)，总共训练轮数是500000，总共的epoch是  500000/(118287/64) = 270 epoch。

SSD单阶段也类似，单阶段模型，训练的epoch数都相对较多。

对于自己的数据集，换算，可以按照总共的epoch数来换算。
