### ISSUE TITLE
提取某一层的特征图

### ISSUE THREAD

**Issue by CVdandelion** [PaddlePaddle/PaddleDetection#1544]
请问一下，将图片输入网络之后，我想查看一下，提取出来的特征图，应该怎么操作，或者修改哪个文件啊？

**Comment by jerrywgz** [comment]
有两种方式可以尝试，以faster rcnn为例：
1. 在ppdet/modeling/architectures/faster_rcnn.py的build中，将想查看的特征图放到result这个字典中，然后在tools/train.py中找到train_values中那个特征图的位置，然后在exe.run返回得到的outs中就可以找到对应的特征图了
2. 在每次exe.run之后运行如下代码，var_name为特征图对应的名称
··· 
var = fluid.global_scope().find_var(var_name)
var_tensor = var.get_tensor()
print(var_name, np.array(var_tensor))
···

目前PaddleDetection暂时还没有提供可视化的脚本
