### ISSUE TITLE
请问infer如何获得检测框的信息？

### ISSUE THREAD

**Issue by Siyi-Huang** [PaddlePaddle/PaddleDetection#1545]
请问使用PaddleDetection的infer进行可视化预测图片时，如何获得检测框的信息？比如坐标、置信度和标签？

 有什么参数嘛，或者需要修改infer的哪一部分代码？

看了一下tool/infer.py，实在没有找到，请教一下，感谢！

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/tools/infer.py#L192 这里就是box对应的坐标置信度和标签，通过字典的方式存储的

**Comment by Siyi-Huang** [comment]
哇，太棒了，感谢！
