### ISSUE TITLE
怎么让算力迅速提高

### ISSUE THREAD

**Issue by chenkongwu123** [PaddlePaddle/PaddleDetection#1546]

**Comment by jerrywgz** [comment]
可以从两方面考虑：
1. 用更好的显卡比如Tesla v100，在aistudio中有提供免费的单卡v100资源可以尝试
2. 提高GPU使用率，这个可以通过数据多进程的方式来加速CPU处理时间从而提升GPU使用率

**Comment by jerrywgz** [comment]
issue先关闭了，如果还有新的问题可以再提issue，我们会及时跟进
