### ISSUE TITLE
蒸馏通道剪裁训练时Eval报错

### ISSUE THREAD

**Issue by linglanfeng** [PaddlePaddle/PaddleDetection#1547]
\PaddleDetection\slim\extensions\distill_pruned_model\distill_pruned_model.py
缺少参数

错误:
`results = eval_run(exe, compiled_eval_prog, eval_loader, eval_keys, eval_values, eval_cls)`

正确: 
`results = eval_run(exe, compiled_eval_prog, eval_loader, eval_keys, eval_values, eval_cls, cfg)`

**Comment by heavengate** [comment]
感谢反馈，我们修复一下~

**Comment by heavengate** [comment]
fixed by https://github.com/PaddlePaddle/PaddleDetection/pull/1551
