### ISSUE TITLE
top-k voting nms

### ISSUE THREAD

**Issue by KooSung** [PaddlePaddle/PaddleDetection#155]
你好，想问一下在Open Images Object Detection Track 2019中的获得第二名方案（[2nd Place Solution in Google AI Open Images Object Detection Track 2019](https://arxiv.org/pdf/1911.07171.pdf)）中的top-k voting nms会开源吗？
谢谢。

**Comment by littletomatodonkey** [comment]
感谢您的关注，我们会开源该方案（具体时间待定），如果您也有意向先自己实现的话，对于voting-nms阈值以及k的取值，这两个超参可能需要重点注意一下~

**Comment by littletomatodonkey** [comment]
您好，您可以参考这个issue中的讨论，先实现下看下~：#452
