### ISSUE TITLE
如何能够评估每个类别的recall，precision和AP？

### ISSUE THREAD

**Issue by TuoniTuoni** [PaddlePaddle/PaddleDetection#1555]

**Comment by qingqing01** [comment]
@TuoniTuoni 目标还不支持，需要自己修改下评估相关的代码。我们会作为需求，后续支持。

**Comment by TuoniTuoni** [comment]
@qingqing01 好的，多谢

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/2346   develop上已支持
