### ISSUE TITLE
TrainReader 多数据集训练推荐做法

### ISSUE THREAD

**Issue by wuyuanyi135** [PaddlePaddle/PaddleDetection#1557]
Hello
我的数据集采用分批标记。因此会有分散在多个不同位置的coco数据集。由于TrainReader不支持提供dataset list，我打算用脚本合并多个数据集。请问开发者是否有推荐的方案

**Comment by qingqing01** [comment]
建议使用脚本合并下。多数据集列表的支持，我们后续作为功能增加下。

**Comment by wuyuanyi135** [comment]
@qingqing01 好的， 谢谢
