### ISSUE TITLE
训练自己数据集时候 训练完成无法进行验证

### ISSUE THREAD

**Issue by txssg** [PaddlePaddle/PaddleDetection#1558]
Traceback (most recent call last):
  File "tools/eval.py", line 180, in <module>
    main()
  File "tools/eval.py", line 100, in main
    "unknown metric type {}".format(cfg.metric)
AssertionError: unknown metric type voc

**Comment by qingqing01** [comment]
@txssg 

https://github.com/PaddlePaddle/PaddleDetection/blob/84dde59eaf0f2704ca971fa267b8b430c4e16837/tools/eval.py#L99-L100

你是那个模型？ 看下yml配置中的metric是啥？

**Comment by txssg** [comment]
> @txssg
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/84dde59eaf0f2704ca971fa267b8b430c4e16837/tools/eval.py#L99-L100
> 
> 你是那个模型？ 看下yml配置中的metric是啥？

我设置得为voc格式

**Comment by txssg** [comment]
> @txssg
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/84dde59eaf0f2704ca971fa267b8b430c4e16837/tools/eval.py#L99-L100
> 
> 你是那个模型？看下yml配置中的metric是啥？
模型是yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco，里面的metrtic已经改为voc 可以正常训练但不能进行验证。

**Comment by qingqing01** [comment]
需要大写的VOC。

**Comment by txssg** [comment]
> 需要大写的VOC。

谢谢，但是现在又有了新的问题 Traceback (most recent call last):
  File "tools/eval.py", line 180, in <module>
    main()
  File "tools/eval.py", line 163, in main
    save_only=save_only)
  File "/home/aistudio/PaddleDetection/ppdet/utils/eval_utils.py", line 238, in eval_results
    map_type=map_type)
  File "/home/aistudio/PaddleDetection/ppdet/utils/voc_eval.py", line 71, in bbox_eval
    gt_boxes = t['gt_bbox'][0]
KeyError: 'gt_bbox'，加入fields: ['image', 'im_info', 'im_id', 'im_shape', 'gt_bbox', 'gt_class', 'is_difficult']也不行，请问这又该怎么解决呢

**Comment by qingqing01** [comment]
是类似 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/yolov3_mobilenet_v1_voc.yml#L74  加在EvalReader吗？

**Comment by txssg** [comment]
> 是类似 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/yolov3_mobilenet_v1_voc.yml#L74 加在EvalReader吗？

对，将里面Coco的格式的fields改为了voc的，报错 im_info有错，方便留个联系方式吗，方便截图交流

**Comment by txssg** [comment]
> 是类似 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/yolov3_mobilenet_v1_voc.yml#L74 加在EvalReader吗？

问题已解决 是不是如果想要所有的模型都能支持voc和coco呢

**Comment by qingqing01** [comment]
@txssg  基本所有模型都支持VOC和COCO两种数据格式，只是COCO数据格式评估的时候，读取的json里有gt的标注，而VOC的是从reader里给的。所以EvalReader里多了一个字段。我们后续会提升这个易用性问题，使得这两种数据格式的用起来类似。

**Comment by gaofssvm** [comment]
@qingqing01 

###############################
配置文件：
##############################
EvalReader:
  batch_size: 8
  inputs_def:
    fields: ['image', 'im_size', 'im_id']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: trainval.txt
    use_default_label: false
    with_background: false
  sample_transforms:
  - !ResizeImage
    target_size: 608
    interp: 2
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
    is_channel_first: false
  - !PadBox
    num_max_boxes: 50
  - !Permute
    to_bgr: false
    channel_first: True
  worker_num: 4

###############################
eval.py的时候，出现的问题：
#############################
Traceback (most recent call last):
File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/reader.py", line 46, in call
data = f(data, ctx)
File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/transform/operators.py", line 305, in call
im = sample['image']
KeyError: 'image'

################################
这是什么问题？

**Comment by Yaoxingtian** [comment]
> > 是类似 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/yolov3_mobilenet_v1_voc.yml#L74 加在EvalReader吗？
> 
> 问题已解决 是不是如果想要所有的模型都能支持voc和coco呢

請問您是如何解決這個問題的？ 我也遇到了

**Comment by Weilongxin** [comment]
> > 是类似 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/yolov3_mobilenet_v1_voc.yml#L74 加在EvalReader吗？
> 
> 问题已解决 是不是如果想要所有的模型都能支持voc和coco呢

**Comment by Weilongxin** [comment]
> > 是类似 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/yolov3_mobilenet_v1_voc.yml#L74 加在EvalReader吗？
> 
> 问题已解决 是不是如果想要所有的模型都能支持voc和coco呢

怎么解决的，能教一下吗？
