### ISSUE TITLE
函数内调用本函数

### ISSUE THREAD

**Issue by liguoyu666** [PaddlePaddle/PaddleDetection#1563]
workspace.py的def create(cls_or_name, **kwargs)函数内部，也有调用create()的，这里怎么理解
https://github.com/PaddlePaddle/PaddleDetection/blob/84dde59eaf0f2704ca971fa267b8b430c4e16837/ppdet/core/workspace.py#L260

**Comment by willthefrog** [comment]
有些参数是需要传入class实例的，这里是创建了对应实例

**Comment by liguoyu666** [comment]
> 有些参数是需要传入class实例的，这里是创建了对应实例

谢谢，理解了，递归
