### ISSUE TITLE
自己创建的数据集mask_rcnn_r50_vd_fpn paddle1.8 训练出错，初步判定是mask_assigner有问题，求解答！

### ISSUE THREAD

**Issue by ruoxi1234** [PaddlePaddle/PaddleDetection#1570]
用paddledetection release0.4版本，paddle1.8的镜像，用mask_rcnn_r50_vd_fpn训练自己的数据集，标注是coco格式的，训练的时候出现错误如下：
W1015 16:51:48.758822   120 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1015 16:51:48.758874   120 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1015 16:51:48.758878   120 init.cc:231] The detail failure signal is:
W1015 16:51:48.758882   120 init.cc:234] *** Aborted at 1602751908 (unix time) try "date -d @1602751908" if you are using GNU date ***
W1015 16:51:48.760533   120 init.cc:234] PC: @                0x0 (unknown)
W1015 16:51:48.760835   120 init.cc:234] *** SIGSEGV (@0x100000029) received by PID 6 (TID 0x7f6f9ac3c700) from PID 41; stack trace: ***
W1015 16:51:48.762156   120 init.cc:234]     @     0x7f6fb301a390 (unknown)
W1015 16:51:48.763947   120 init.cc:234]     @     0x7f6f02a48ef8 paddle::memory::detail::MemoryBlock::Split()
W1015 16:51:48.766396   120 init.cc:234]     @     0x7f6f02a47422 _ZN6paddle6memory6detail14BuddyAllocator12SplitToAllocESt23_Rb_tree_const_iteratorISt5tupleIJmmPvEEEm
W1015 16:51:48.769347   120 init.cc:234]     @     0x7f6f02a47905 paddle::memory::detail::BuddyAllocator::Alloc()
W1015 16:51:48.771350   120 init.cc:234]     @     0x7f6f02a378f5 paddle::memory::legacy::Alloc<>()
W1015 16:51:48.773772   120 init.cc:234]     @     0x7f6f02a38895 paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl()
W1015 16:51:48.775621   120 init.cc:234]     @     0x7f6f02a303df paddle::memory::allocation::AllocatorFacade::Alloc()
W1015 16:51:48.777633   120 init.cc:234]     @     0x7f6f02a3062a paddle::memory::allocation::AllocatorFacade::AllocShared()
W1015 16:51:48.778833   120 init.cc:234]     @     0x7f6f02a2fdfc paddle::memory::AllocShared()
W1015 16:51:48.780174   120 init.cc:234]     @     0x7f6f02a1c5b2 paddle::framework::Tensor::mutable_data()
W1015 16:51:48.781620   120 init.cc:234]     @     0x7f6f02073633 paddle::operators::SampleMaskForOneImage<>()
W1015 16:51:48.784623   120 init.cc:234]     @     0x7f6f0207527f paddle::operators::GenerateMaskLabelsKernel<>::Compute()
W1015 16:51:48.785763   120 init.cc:234]     @     0x7f6f02076af3 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform8CPUPlaceELb0ELm0EINS0_9operators24GenerateMaskLabelsKernelIfEEEEclEPKcSE_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
W1015 16:51:48.787901   120 init.cc:234]     @     0x7f6f02994ac0 paddle::framework::OperatorWithKernel::RunImpl()
W1015 16:51:48.791158   120 init.cc:234]     @     0x7f6f029952b1 paddle::framework::OperatorWithKernel::RunImpl()
W1015 16:51:48.792850   120 init.cc:234]     @     0x7f6f0298e271 paddle::framework::OperatorBase::Run()
W1015 16:51:48.795308   120 init.cc:234]     @     0x7f6f0269db56 paddle::framework::details::ComputationOpHandle::RunImpl()
W1015 16:51:48.797773   120 init.cc:234]     @     0x7f6f02643d31 paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
W1015 16:51:48.800304   120 init.cc:234]     @     0x7f6f0264182f paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
W1015 16:51:48.801200   120 init.cc:234]     @     0x7f6f02641af4 _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
W1015 16:51:48.804121   120 init.cc:234]     @     0x7f6eff5bc603 std::_Function_handler<>::_M_invoke()
W1015 16:51:48.806828   120 init.cc:234]     @     0x7f6eff3b62f7 std::__future_base::_State_base::_M_do_set()
W1015 16:51:48.808185   120 init.cc:234]     @     0x7f6fb3017a99 __pthread_once_slow
W1015 16:51:48.808931   120 init.cc:234]     @     0x7f6f0263dcc2 _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
W1015 16:51:48.811609   120 init.cc:234]     @     0x7f6eff3b8754 _ZZN10ThreadPoolC1EmENKUlvE_clEv
W1015 16:51:48.812356   120 init.cc:234]     @     0x7f6f7217e421 execute_native_thread_routine_compat
W1015 16:51:48.813503   120 init.cc:234]     @     0x7f6fb30106ba start_thread
W1015 16:51:48.814564   120 init.cc:234]     @     0x7f6fb2d4641d clone
W1015 16:51:48.815654   120 init.cc:234]     @                0x0 (unknown)
Segmentation fault (core dumped)
请问这个是什么问题？

**Comment by yghstill** [comment]
@ruoxi1234 看报错栈，可能是显存不足导致的，GPU显存有多少呢？

**Comment by ruoxi1234** [comment]
显卡用的是v100，其他数据集在相同配置下是正常的

**Comment by ruoxi1234** [comment]
> @ruoxi1234 看报错栈，可能是显存不足导致的，GPU显存有多少呢？

显卡使用的是单卡v100，相同的配置下，其他数据集下是可运行的，我看到报错里有mask相关的字眼，怀疑是标注有问题，但是通过肉眼看不出标签的问题，希望帮忙定位一下，这个是对mask的什么操作出现的错误。

**Comment by yghstill** [comment]
@ruoxi1234 这个报错栈之前的报错信息可以发全一点吗？这个无法直接定位问题，我这边在coco数据集上测试了一下没有发现问题，你在coco上试过没有？

**Comment by ruoxi1234** [comment]
为了避免自定义代码引入的错误，在原始的paddledetection上运行，仍然出现相同报错，将batchsize改为1，初步定位是mask_assigner有问题，增加日志打印代码如下：
fluid.layers.Print(feed_vars['gt_class'])
fluid.layers.Print(feed_vars['is_crowd'])
fluid.layers.Print(feed_vars['gt_mask'])
fluid.layers.Print(feed_vars['im_info'])
fluid.layers.Print(labels_int32)
mask_rois, roi_has_mask_int32, mask_int32 = self.mask_assigner(
                rois=rois,
                gt_classes=feed_vars['gt_class'],
                is_crowd=feed_vars['is_crowd'],
                gt_segms=feed_vars['gt_mask'],
                im_info=feed_vars['im_info'],
                labels_int32=labels_int32)
出现了如下报错日志：
1602912582		The place is:CUDAPlace(0)
Tensor[is_crowd]
	shape: [1,1,]
	dtype: i
	LoD: [[ 0,1, ]]
	data: 0,
1602912582		The place is:CUDAPlace(0)
Tensor[im_info]
	shape: [1,3,]
	dtype: f
	data: 800,800,0.78125,
1602912582		The place is:CUDAPlace(0)
Tensor[gt_class]
	shape: [1,1,]
	dtype: i
	LoD: [[ 0,1, ]]
	data: 2,
1602912582		The place is:CUDAPlace(0)
Tensor[gt_mask]
	shape: [9,2,]
	dtype: f
	LoD: [[ 0,1, ][ 0,1, ][ 0,9, ]]
	data: 149,917.5,135,914.5,126.5,903,128.5,888,142,878.5,158,882.5,165.5,896,161.5,910,149,917.5,
1602912583		The place is:CUDAPlace(0)
Tensor[generate_proposal_labels_0.tmp_1]
	shape: [512,1,]
	dtype: i
	LoD: [[ 0,512, ]]
	data: 2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
W1017 13:29:43.016325 48934 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1017 13:29:43.016377 48934 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1017 13:29:43.016392 48934 init.cc:214] The detail failure signal is:

W1017 13:29:43.016404 48934 init.cc:217] *** Aborted at 1602912583 (unix time) try "date -d @1602912583" if you are using GNU date ***
W1017 13:29:43.017958 48934 init.cc:217] PC: @                0x0 (unknown)
W1017 13:29:43.018261 48934 init.cc:217] *** SIGSEGV (@0x100000028) received by PID 48845 (TID 0x7f1bdc2a0700) from PID 40; stack trace: ***
W1017 13:29:43.019598 48934 init.cc:217]     @     0x7f1c4696f390 (unknown)
W1017 13:29:43.023195 48934 init.cc:217]     @     0x7f1b5d5c0748 paddle::memory::detail::MemoryBlock::Split()
W1017 13:29:43.027732 48934 init.cc:217]     @     0x7f1b5d5bec72 _ZN6paddle6memory6detail14BuddyAllocator12SplitToAllocESt23_Rb_tree_const_iteratorISt5tupleIJmmPvEEEm
W1017 13:29:43.032904 48934 init.cc:217]     @     0x7f1b5d5bf155 paddle::memory::detail::BuddyAllocator::Alloc()
W1017 13:29:43.036540 48934 init.cc:217]     @     0x7f1b5d5aeaf5 paddle::memory::legacy::Alloc<>()
W1017 13:29:43.040678 48934 init.cc:217]     @     0x7f1b5d5afa95 paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl()
W1017 13:29:43.042999 48934 init.cc:217]     @     0x7f1b5d5a8e03 paddle::memory::allocation::AllocatorFacade::Alloc()
W1017 13:29:43.046264 48934 init.cc:217]     @     0x7f1b5d5a909e paddle::memory::allocation::AllocatorFacade::AllocShared()
W1017 13:29:43.049787 48934 init.cc:217]     @     0x7f1b5d5a881c paddle::memory::AllocShared()
W1017 13:29:43.052330 48934 init.cc:217]     @     0x7f1b5d5957b2 paddle::framework::Tensor::mutable_data()
W1017 13:29:43.054956 48934 init.cc:217]     @     0x7f1b5ccba843 paddle::operators::SampleMaskForOneImage<>()
W1017 13:29:43.060497 48934 init.cc:217]     @     0x7f1b5ccbc33f paddle::operators::GenerateMaskLabelsKernel<>::Compute()
W1017 13:29:43.062532 48934 init.cc:217]     @     0x7f1b5ccbda73 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform8CPUPlaceELb0ELm0EINS0_9operators24GenerateMaskLabelsKernelIfEEEEclEPKcSE_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
W1017 13:29:43.066545 48934 init.cc:217]     @     0x7f1b5d50db16 paddle::framework::OperatorWithKernel::RunImpl()
W1017 13:29:43.072247 48934 init.cc:217]     @     0x7f1b5d50e2e1 paddle::framework::OperatorWithKernel::RunImpl()
W1017 13:29:43.075242 48934 init.cc:217]     @     0x7f1b5d507430 paddle::framework::OperatorBase::Run()
W1017 13:29:43.079591 48934 init.cc:217]     @     0x7f1b5d28c0c6 paddle::framework::details::ComputationOpHandle::RunImpl()
W1017 13:29:43.083604 48934 init.cc:217]     @     0x7f1b5d243281 paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
W1017 13:29:43.088037 48934 init.cc:217]     @     0x7f1b5d241fef paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
W1017 13:29:43.089473 48934 init.cc:217]     @     0x7f1b5d2422b4 _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
W1017 13:29:43.094781 48934 init.cc:217]     @     0x7f1b5ad27b23 std::_Function_handler<>::_M_invoke()
W1017 13:29:43.100039 48934 init.cc:217]     @     0x7f1b5aab6407 std::__future_base::_State_base::_M_do_set()
W1017 13:29:43.101455 48934 init.cc:217]     @     0x7f1c4696ca99 __pthread_once_slow
W1017 13:29:43.102656 48934 init.cc:217]     @     0x7f1b5d23d7a2 _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
W1017 13:29:43.107699 48934 init.cc:217]     @     0x7f1b5aab8684 _ZZN10ThreadPoolC1EmENKUlvE_clEv
W1017 13:29:43.108347 48934 init.cc:217]     @     0x7f1b87596c80 (unknown)
W1017 13:29:43.109565 48934 init.cc:217]     @     0x7f1c469656ba start_thread
W1017 13:29:43.110741 48934 init.cc:217]     @     0x7f1c4669b41d clone
W1017 13:29:43.111888 48934 init.cc:217]     @                0x0 (unknown)
求解答！

**Comment by ruoxi1234** [comment]
查了一下paddle的api，mask_mask_assigner实质上是op：
paddle.fluid.layers.generate_mask_labels(im_info, gt_classes, is_crowd, gt_segms, rois, labels_int32, num_classes, resolution)
请问为什么在这里会触发错误，输入的参数可见楼上的日志。

**Comment by ruoxi1234** [comment]
是自己生成的coco标签有误，categoryid一定要从1开始，已解决，感谢！
