### ISSUE TITLE
关于配置文件中的used_padded_im_info

### ISSUE THREAD

**Issue by TuoniTuoni** [PaddlePaddle/PaddleDetection#1571]
在train的时候use_padded_im_info：false，eval和test的时候为true。在operator.py看到源码信息为if self.use_padded_im_info: data['im_info'][:2] = max_shape[1:3]。水平问题看不太懂源码，能麻烦解释一下为什么训练和验证时分别设置为false和true吗，代表什么意思？谢谢

**Comment by yghstill** [comment]
@TuoniTuoni 批处理PadBatch会将整个batch图像都统一padding到pad_to_stride的倍数，如32的倍数。在use_padded_im_info=True模式下，会将PadBatch后的im_info的image shape更新为pad之后的。在训练中计算不需要这个shape，但是在eval和test中，会将检测结果reszie到pad之后图像上，所以需要pad shape这个信息，所以就需要use_padded_im_info：True。

**Comment by TuoniTuoni** [comment]
@yghstill 谢谢，但是在多尺度训练的时候是不是就需要use_padded_im_info=True 了，比如cascade_mask_rcnn_dcnv2_se154_vd_fpn_gn_s1x.yml，cascade_rcnn_cbr200_vd_fpn_dcnv2_nonlocal_softnms.yml采用多尺度训练都没用声明为false，可以解释一下为什么吗（小白正在努力读懂源码和理解深层原理中呜呜）

**Comment by qingqing01** [comment]
@TuoniTuoni 这个参数影响的是im_info字段中的height和width，这个对最终结果影响不大，后面也会统一下。
