### ISSUE TITLE
PP-YOLO论文相关问题

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#1576]
作者您好，我想问一下PPYOLO论文上提到每一个创新点对应的准确度，我想问一下你们在实际操作的时候是加一个tricks然后重新训练吗？还是怎么操作将每个tricks对应的map得到的，谢谢

**Comment by jerrywgz** [comment]
是的，每个trick都会训练一版模型和对应的mAP

**Comment by qdd1234** [comment]
因为每一次训练会有随机不确定因素在里面，万一我加的tricks实际上是有效的，但因为随机因素反而map降下去 了，针对这种情况我想问一下你们是每个tricks都重新训练几次以确定其有效性吗，但这样会不会时间消耗太长了

**Comment by jerrywgz** [comment]
从以往的经验来看，相同模型结构和参数训练出来的模型精度一般会波动0.2个点，相对还是比较稳定的，所以我们这边不会一个trick去训练多次
