### ISSUE TITLE
请问如果想要看到网络的中间过程的变量，是否需要将网络转换为动态图？

### ISSUE THREAD

**Issue by a2824256** [PaddlePaddle/PaddleDetection#1577]
请问如果想要看到网络的中间过程的变量，是否需要将网络转换为动态图？ppdet目前支持动态图模式运行吗？

**Comment by jerrywgz** [comment]
如果只是想观察中间过程的变量，可以通过fluid.layers.Print, https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/Print_cn.html#print; 或者将变量放到fetch list中，每轮训练之后就可以看到对应的值。不需要转换为动态图。

关于ppdet的动态图模式目前还在开发中，预计年底会有一个完整版本

**Comment by a2824256** [comment]
好的，感谢，你们加油
