### ISSUE TITLE
怎样看召回率和精确度，Eval的结果只有mAP

### ISSUE THREAD

**Issue by xiaolifeimianbao** [PaddlePaddle/PaddleDetection#1585]

**Comment by jerrywgz** [comment]
请问你使用的是voc格式的数据还是coco格式的呢

**Comment by xiaolifeimianbao** [comment]
> 请问你使用的是voc格式的数据还是coco格式的呢

VOC

**Comment by jerrywgz** [comment]
嗯，VOC数据格式目前还只支持mAP的评估结果，我们后续新增下

**Comment by SixGodGG** [comment]
> 嗯，VOC数据格式目前还只支持mAP的评估结果，我们后续新增下

 你好 如果是COCO数据集呢？ 怎么得到mAP，我自己运行ppyolo等模型，得到的是各个面积下的AP，哪个才是像VOC数据集那样的mAP呢，COCO 数据集我也想看各个类别的召回率等。

**Comment by heavengate** [comment]
develop上已支持  https://github.com/PaddlePaddle/PaddleDetection/pull/2346
