### ISSUE TITLE
maskrcnn模型部署预测没有mask结果

### ISSUE THREAD

**Issue by ruoxi1234** [PaddlePaddle/PaddleDetection#1586]
训练了一个maskrcnn_r50_vd_fpn模型，对于同一张图片，用tools/infer.py可以预测出结果，但是用tools/export_model.py将模型转换导出后，再预测没有mask结果。这个很影响使用，求解决！

**Comment by jerrywgz** [comment]
已通过升级至release/0.4版本解决

**Comment by wangkan83** [comment]
升级至release/0.4仍无法解决！！
