### ISSUE TITLE
模型保存的相关问题

### ISSUE THREAD

**Issue by CVdandelion** [PaddlePaddle/PaddleDetection#1593]
我看到在tools/train.py文件中模型的保存用的是fliud.save进行模型的保存，且保存后的模型为3个，能够用pickle包打开
但是在slim/quantization/train.py文件中，用的是fluid.io.save.persisitables和fluid.io.save.vars进行的文件保存，
我的问题是：
这三个进行模型保存的API有什么区别？
是不是fluid.io.save.persisitables+fluid.io.save.vars=fliud.save？
fluid.io.save.persisitables+fluid.io.save.vars这两个API保存之后的文件，如果想里面的参数应该怎么做？我用了pickle包会报错

**Comment by willthefrog** [comment]
`save_persistable`和`save_vars`是旧版的API，保存的是二进制序列化后的数值，如果需要读取需要实用paddle OP。
`paddle.save`/`fluid.save`是pickle的字典，可以直接python读取。

**Comment by CVdandelion** [comment]
好的，那是不是fluid.io.save.persisitables+fluid.io.save.vars=fliud.save？
那么在旧版本中，在功能上模型参数（也就是fluid.save保存的 .pdparams文件）是不是通过fluid.io.save.vars保存的？
网络结构参数通过（也就是fluid.save保存的  .pdmodel文件）save_persistable保存的？

**Comment by willthefrog** [comment]
不是，不同的两套格式。
