### ISSUE TITLE
请问什么时候需要warmup，以及warmup的次数设置为多少合适？

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleDetection#1600]
你好，我想请教下，我看到deploy/python/infer.py下的预测图片部分有个warmup参数默认为0，想知道什么情况下需要warmup，以及warmup的次数设置为多少合适？

我的应用场景是想通过自己的方式作为web 服务，我的理解是在服务起来之前最好在构建Detector实例的时候warmup几次，然后再接受http的预测请求，我的理解对么？ @qingqing01

**Comment by qingqing01** [comment]
推理的warmup是为了测试benchmark，跳过前面启动时间(启动时间里，包括一些模型的加载、各个实例的初始化等启动时间)。
正常推理部署、web服务，正常不需要warmup。

**Comment by nihuizhidao** [comment]
谢谢！
