### ISSUE TITLE
深度学习目前可以让用户来标记样本进行训练来更新原有模型吗？

### ISSUE THREAD

**Issue by elvinest** [PaddlePaddle/PaddleDetection#1606]
在工业质检上，通常我们都会先采集大量的样本数据，例如某种零件的外观刮痕。然后进行异常点的标注，来训练调优模型，最后部署到生产环境中。 但是如果客户某一天需要对该零件增加一种异常检测，比如零件的某个孔有没有漏。按现在做法是重新采集新样本，结合原有的样本来重新来训练，这种方式更新成本和周期相对很高。
有没有一种解决方案，客户来进行标注，通过系统上传后自动训练新样本来更新原有的模型，或者是其它方案能优化目前这个问题的。谢谢大家

**Comment by x12901** [comment]
可以，要你自己写程序
