### ISSUE TITLE
c++部署maskrcnn没有合适的接口？

### ISSUE THREAD

**Issue by x12901** [PaddlePaddle/PaddleDetection#1609]
我在c++部署maskrcnn的时候发现好像只有目标检测的画框接口，有没有可以mask遮罩那种的，就像python检测效果那样。是不是导出模型的时候要特殊处理？我是直接导出的模型https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/advanced_tutorials/deploy/EXPORT_MODEL.md
```
python tools/export_model.py -c configs/mask_rcnn_r101_fpn_1x.yml \
        --output_dir=./inference_model \
        -o weights=output/mmask_rcnn_r101_fpn_1x/model_final
```
还有想问一下c++预测和python原版预测结果会有差距吗？用maskrcnn做物体位置预测和旋转角度预测是可能实现的吗？

**Comment by jerrywgz** [comment]
目前C++部署暂时还没有支持mask的预测，只支持在deploy/python 下的mask预测；
就box而言，c++预测和python预测的预测结果是一致的
关于旋转角度的预测，mask可能不一定能满足，我们这边现在还在开发专门用于旋转框检测的模型

**Comment by qingqing01** [comment]
最新动态图推理接口已支持MaskRCNN。 

旋转框预测，已提供新的模型。
