### ISSUE TITLE
关于修改网络结构

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#161]
现在想修改detection中的部分模型网络结构
例如 mask rcnn  我想把mask分支移到rpn网络前 让通过fpn出来的feature map先生成一个mask  把这个mask 喂入rpn  
我在代码中没找到mask 分支   mask_head.py是mask分支吗？
以及从fpn出来的数据输出在哪里呢

**Comment by FDInSky** [comment]
mask_head.py 就是mask分支；
fpn之后是RPN部分

**Comment by shuxsu** [comment]
> mask_head.py 就是mask分支；
> fpn之后是RPN部分；

那我如何将mask 移动到rpn之前呢？
就是在我的网络里使用2个mask  能否直接把mask head复用给rpn
