### ISSUE TITLE
paddle inference中使用trt_fp16提速不明显

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#1611]
mobilenetv1_yolov3剪枝后,使用trt_fp16只比fluid推理快了两帧,(硬件平台是tx2).为什么提速不明显?有没有可能是filter剪后个数不是32整数倍之类的原因?

**Comment by qingqing01** [comment]
@JensenHJS 请问裁剪的FLOPs比例是多少？如果裁剪FLOPs比例不高的话，对于GPU加速确实不如CPU高，如果计算小时，GPU的利用率也不高。

**Comment by JensenHJS** [comment]
我的意思是剪枝后用trt_fp16和同一个剪枝后模型用fluid推理比起来，只快了2帧

**Comment by JensenHJS** [comment]
因为之前用trt加速darknet训的模型，至少快一倍。这里缺只快了2帧

**Comment by jerrywgz** [comment]
我们这边用yolov3_mv1 测试了下，设置run_benchmark=True的情况下，基于敏感度剪裁34.27%之后的模型，在P40机器上trt_fp16的速度是6.41ms, 用fluid推理是8.83ms
关于速度这块还需要在结合tensorRT进一步优化

**Comment by jerrywgz** [comment]
上面的测试补充下，P40上是不支持tensor core的，如果使用像v100/tx2这样的设备应该会有进一步加速
