### ISSUE TITLE
VOC格式数据集利用x2coco.py转化为COCO格式数据集时，出现错误

### ISSUE THREAD

**Issue by Lxiaom123** [PaddlePaddle/PaddleDetection#1613]
请教大家，这个错误怎么处理？
![image](https://user-images.githubusercontent.com/66930694/97276156-ccb95080-1871-11eb-9613-dea26b52d2f7.png)
但是007611图片是存在的
![image](https://user-images.githubusercontent.com/66930694/97276330-fffbdf80-1871-11eb-88b2-789fe59c948a.png)

**Comment by jerrywgz** [comment]
可以确认下实际007611.jpg.xml的绝对路径是什么，test.txt里的是相对路径

**Comment by Lxiaom123** [comment]
冠冠老师，我把test.txt里面改成绝对路径了，没报那个错误了，但现在新的错误出现了
![image](https://user-images.githubusercontent.com/66930694/97297682-4f033e00-188d-11eb-9a57-3fdec2b55001.png)

**Comment by Lxiaom123** [comment]
冠冠老师，我把test.txt里面改成绝对路径了，没报那个错误了，但现在新的错误出现了
![image](https://user-images.githubusercontent.com/66930694/97304872-4e6fa500-1897-11eb-9f4a-63942606f317.png)

**Comment by jerrywgz** [comment]
这个看起来是python输入缩进的问题

**Comment by Lxiaom123** [comment]
嗯嗯，但是我还是找不到哪里缩进错误

**Comment by yghstill** [comment]
@Lxiaom123 换行执行python脚本不成功，可以再试下不换行。

**Comment by qingqing01** [comment]
related to https://github.com/PaddlePaddle/PaddleDetection/issues/1589
