### ISSUE TITLE
继承paddle的docker镜像run的时候报错，没有找到$PATH

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleDetection#1614]
环境：CentOS,
使用CPU版本的docker，Dockerfile如下：

> FROM hub.baidubce.com/paddlepaddle/paddle:1.8.4
> 
> COPY ./requirements.txt /requirements.txt
> 
> WORKDIR /
> 
> RUN pip3 install --no-cache-dir Cython -i https://pypi.douban.com/simple && pip3 install --no-cache-dir -r requirements.txt -i https://pypi.douban.com/simple --timeout 1000
> 
> COPY . /
> 
> CMD ["python", "model_serving.py"]

docker build成功后，使用命令启动docker：

>  docker run --name mymodelservice -d modelserving:v0.1 -p 127.0.0.1:5001:5001

报错：

> [root@localhost modelserving]# docker run --name mymodelservice -d modelserving:v0.1 -p 127.0.0.1:5001:5001
> 0f3f5da65eedc336a74a6b4f431455dd02fea346678c33cb028ccaa9c5bbe636
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"-p\": executable file not found in $PATH": unknown.

测试过`hub.baidubce.com/paddlepaddle/paddle:1.8.4` 这个镜像本身在服务器上跑是没有问题的，下面是验证：

> FROM hub.baidubce.com/paddlepaddle/paddle:1.8.4
> WORKDIR /
> COPY . /
> CMD ["python" "test.py"]

其中test.py:

> import paddle.fluid
> print(paddle.fluid.install_check.run_check())

请问这个可能是什么原因呢？谢谢 @qingqing01

**Comment by tianshuo78520a** [comment]
你应该把-p 命令加在镜像名前面，尝试下：
docker run --name mymodelservice -d -p 127.0.0.1:5001:5001 modelserving:v0.1

**Comment by nihuizhidao** [comment]
感谢，问题解决了
