### ISSUE TITLE
faster rcnn r50为什么取得特征图是featuremap 4 而不是顶层特征featuremap 5

### ISSUE THREAD

**Issue by xiaolifeimianbao** [PaddlePaddle/PaddleDetection#1615]
ResNet:
  norm_type: affine_channel
  depth: 50
  feature_maps: 4
  freeze_at: 2

**Comment by jerrywgz** [comment]
faster rcnn r50的逻辑就是通过res4计算rpn部分，然后在roi_align之后再使用res5 block
faster rcnn + fpn的逻辑是通过res5计算rpn部分，然后在roi_align之后使用两个fc
这里两种模型结构略有不同
