### ISSUE TITLE
利用yolov3_mobilenet_v1.yml训练自己数据的模型，loss一直在50~60.

### ISSUE THREAD

**Issue by leeburt** [PaddlePaddle/PaddleDetection#162]
所有的训练参数都没有改动，迭代了10W次，loss一直降不下来，也尝试了yolov3_darknet.yml，结果一样。

**Comment by heavengate** [comment]
YOLOv3模型各通道loss是加算的，显示的loss会比较大，是正常现象，可以看下篇README中的loss收敛曲线，yolov3_darknet最终收敛loss也有60+
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/yolov3
可以在训练过程中开`--eval`评估训练效果

**Comment by leeburt** [comment]
> YOLOv3模型各通道loss是加算的，显示的loss会比较大，是正常现象，可以看下篇README中的loss收敛曲线，yolov3_darknet最终收敛loss也有60+
> https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/yolov3
> 可以在训练过程中开`--eval`评估训练效果

有开这个参数，发现ap都是0.01左右。同时这是利用eval.py的评估结果。
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.006
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.012
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.006
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.020
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.076
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.003
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.006
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.009
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.005
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.029
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.096

**Comment by leeburt** [comment]
目前问题已经解决了，制作训练数据集时有bug导致，与本项目无关。

**Comment by wenjie-yuan** [comment]
> 目前问题已经解决了，制作训练数据集时有bug导致，与本项目无关。

你好，我也遇到一样的问题，你说的“制作数据集时有bug”具体是什么bug，我的数据是比赛方给的，难道有坏数据吗？
