### ISSUE TITLE
coco单类map

### ISSUE THREAD

**Issue by sunpeng1114** [PaddlePaddle/PaddleDetection#1620]
coco格式的评价结果bbox.json,有可以画出单类pr曲线的接口吗？就像paddlex中的draw_pr_curve类似的函数。

**Comment by willthefrog** [comment]
没有，但是看上去paddlex那个函数应该支持检测库的评估格式。

**Comment by sunpeng1114** [comment]
解决了，在这里发一下小教程。
coco格式（voc应该也可以）：需要PaddleDetection评估出来的bbox.json，和自己标注的真值文件test.json.
https://hub.fastgit.org/PaddlePaddle/PaddleX/blob/4f23faad985c360ae030e0032075376bf53dcc0b/docs/apis/visualize.md
这个链接里面有draw_pr_curve函数的用法，第一个参数eval_details_file是paddlex的评估结果，里面包含真值和预测结果，而bbox.json只有评估结果，所以第一个参数不用。用后面gt和pred_bbox的两个参数，需要list格式。所以需要先将bbox.json和test.json通过json库解析出来。
import json
coco_anno = json.load(open('./test.json'))
coco_pre = json.load(open('./bbox.json'))
然后将对应数据传给gt和pred_bbox参数即可。
pdx.det.draw_pr_curve(gt=coco_anno,pred_bbox=coco_pre)

后面有pred_mask，所以实例分割应该也可以用。

**Comment by sunpeng1114** [comment]
voc的标注是单个文件的，想了一下，应该不行。哈哈

**Comment by willthefrog** [comment]
:+1:  感谢贡献教程。

**Comment by sunpeng1114** [comment]
不客气👍

**Comment by sunpeng1114** [comment]
大佬们
可以送一些算力吗？需要准备中期答辩的实验
















在 2020-10-29 10:35:38，"Yang Zhang" <notifications@github.com> 写道：

感谢贡献教程。
