### ISSUE TITLE
Windows tools/infer.py 预测执行完成以后 报Python错误

### ISSUE THREAD

**Issue by SJLNNU** [PaddlePaddle/PaddleDetection#1625]
Win Server 2016  
python 3.7
paddlepaddle-gpu    1.8.4.post107
运行 infer.py 查看CascadeRCNN 训练效果的时候 ，使用正常文件夹中图片也完成预测并可视化保存。但是报 python停止工作。

pychram中报错为：Process finished with exit code -1073740791 (0xC0000409)

同样的代码在Ubuntu16中不报错。

**Comment by yghstill** [comment]
@SJLNNU 感谢反馈，我们排查下。

**Comment by liuhuiCNN** [comment]
您使用的是PaddleDetection release 0.4 版本吗？pychram的命令行是自己的线程，建议您在系统命令行中试一下。

**Comment by SJLNNU** [comment]
> 您使用的是PaddleDetection release 0.4 版本吗？pychram的命令行是自己的线程，建议您在系统命令行中试一下。

您好 是0.4版本 因为我在CMD环境下直接报 python 已停止运行 ，所以才在Pycharm中进行尝试的。
![image](https://user-images.githubusercontent.com/31751988/97524147-ea57f880-19de-11eb-9f9c-65f6ad8bed25.png)

**Comment by liuhuiCNN** [comment]
您好，在我们的windows机器上测试，没有出现这个问题，初步怀疑是跟您的环境有关系。建议您可以使用conda搭建一个新的环境试试看。

**Comment by hong3731** [comment]
一样的错误，是哪里的环境的问题吗？
