### ISSUE TITLE
iou_loss  loss 为nan

### ISSUE THREAD

**Issue by justinmeibi** [PaddlePaddle/PaddleDetection#1628]
INFO: iter: 0, lr: 0.000010, 'loss_xy': '1.828222', 'loss_wh': '5.254690', 'loss_obj': '130.993652', 'loss_cls': '30.401878', 'loss_iou': 'nan', 'loss': 'nan', time: 0.000, eta: 0:00:00

paddlepaddle 1.8.4，yolov3_darknet_voc_diouloss配置，LR 1e-1  -  1e-6都试过，使用  iou_loss ,dioulossyolo, diouloss   ciou_term: False, diouloss   ciou_term: True,  iou loss 均为nan ,偶尔第一个迭代不为nan，检查代码和配置均没发现问题，请问是什么原因导致的？

**Comment by justinmeibi** [comment]
补充：0.4分支代码

**Comment by justinmeibi** [comment]
请问有人回答这个问题吗?

**Comment by justinmeibi** [comment]
请问有人回答这个问题吗?

**Comment by yghstill** [comment]
@justinmeibi 代码是否有修改过？

**Comment by justinmeibi** [comment]
用yolo_mobilenet_v3.yml,0.4分支。
使用DioulossYolo
增加：pact
修改：
def quant_aware(program, place, config=None, scope=None, for_test=False,**args):
log_info：
INFO: iter: 0, lr: 0.002000, 'loss_xy': '8.381511', 'loss_wh': '12.267382', 'loss_obj': '8480.505859', 'loss_cls': '247.796356', 'loss_iou': 'nan', 'loss': 'nan', time: 0.003, eta: 0:01:00

**Comment by justinmeibi** [comment]
已解决，谢谢了
