### ISSUE TITLE
ResNeSt series detection models

### ISSUE THREAD

**Issue by yuanpengcheng** [PaddlePaddle/PaddleDetection#1633]
Do you have plan to release the detection models based on ResNeSt ?

**Comment by yghstill** [comment]
@yuanpengcheng We have this plan and we will train a pretrain model recently.

**Comment by qingqing01** [comment]
@yuanpengcheng  Now, we use  ResNet-vd-ssld,  the top-1 accuracy and inference speed is better than ResNeSt.  

https://github.com/PaddlePaddle/PaddleClas#resnet-and-vd-series
<img width="922" alt="图片" src="https://user-images.githubusercontent.com/7845005/97824030-c0ac1380-1cf5-11eb-9f16-3a8d972ecf80.png">


What scenario do you want to use ResNeSt as backbone?

**Comment by yuanpengcheng** [comment]
> @yuanpengcheng Now, we use ResNet-vd-ssld, the top-1 accuracy and inference speed is better than ResNeSt.
> 
> https://github.com/PaddlePaddle/PaddleClas#resnet-and-vd-series
> <img alt="图片" width="922" src="https://user-images.githubusercontent.com/7845005/97824030-c0ac1380-1cf5-11eb-9f16-3a8d972ecf80.png">
> 
> What scenario do you want to use ResNeSt as backbone?

For fair comparison in the experiment ResNeSt with ours backbone.
