### ISSUE TITLE
windows c++编译出错

### ISSUE THREAD

**Issue by XiaoWen-AI** [PaddlePaddle/PaddleDetection#1637]
![image](https://user-images.githubusercontent.com/38575973/97674707-f0c29f00-1ac8-11eb-80e5-e6f54edb16ab.png)
如图所示，直接打开就报这个错，根据教程改了几个目录也没有作用

**Comment by liuhuiCNN** [comment]
这个是由于PADDLE_DIR没有定义导致的，可能是Visual Studio 2019对CMake的支持性还不够。您可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/master/deploy/cpp/docs/windows_vs2019_build.md 里面的命令行的方式看看。

**Comment by XiaoWen-AI** [comment]
> 这个是由于PADDLE_DIR没有定义导致的，可能是Visual Studio 2019对CMake的支持性还不够。您可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/master/deploy/cpp/docs/windows_vs2019_build.md 里面的命令行的方式看看。

感谢解答，我换了台电脑就可以了，感觉可能和电脑环境有一定关系，失败的电脑装了vs15,17,19等很多东西，新的电脑重装的系统，只有vs2019，直接按教程就可以了
