### ISSUE TITLE
dataset is not valid

### ISSUE THREAD

**Issue by aben1919** [PaddlePaddle/PaddleDetection#1641]
:python tools/train.py -c configs/ppyolo/ppyolo.yml --eval -o use_gpu=true
2020-11-01 09:40:06,218-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
2020-11-01 09:40:10,711-INFO: Dataset /data/aben/PP-YOLO2/dataset\VOCdevkit is not valid for reason above, try searching /root/.cache/paddle/dataset or downloading dataset...
Traceback (most recent call last):
  File "tools/train.py", line 372, in <module>
    main()
  File "tools/train.py", line 148, in main
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
  File "/data/aben/PP-YOLO2/ppdet/data/reader.py", line 441, in create_reader
    reader = Reader(**cfg)()
  File "/data/aben/PP-YOLO2/ppdet/data/reader.py", line 210, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/data/aben/PP-YOLO2/ppdet/data/source/dataset.py", line 65, in get_roidb
    self.image_dir)
  File "/data/aben/PP-YOLO2/ppdet/utils/download.py", line 154, in get_dataset_path
    format(path, osp.split(path)[-1]))
ValueError: Dataset dataset\VOCdevkit is not valid and cannot parse dataset type 'dataset\VOCdevkit' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face', 'fruit' and 'roadsign_voc' currently

![image](https://user-images.githubusercontent.com/73775889/97799624-310d5300-1c6a-11eb-8cff-df3819f3482e.png)
以上是我路徑和reader裡的設置
請問這個報錯要怎麼解決?

**Comment by qingqing01** [comment]
@aben1919 


EvalReader的路径也需要设置下。

**Comment by aben1919** [comment]
![image](https://user-images.githubusercontent.com/73775889/97826821-9bbb9e80-1cfd-11eb-893f-b199302d24af.png)

不好意思沒有說明清楚
EvalReader和TestReader都在上次皆設置過了

**Comment by qingqing01** [comment]
@aben1919 

可以把 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/tools/train.py#L50

logging.INFO 改成 logging.DEBUG

看下还有没有其他错误信息。

**Comment by liuhuiCNN** [comment]
> :python tools/train.py -c configs/ppyolo/ppyolo.yml --eval -o use_gpu=true
> 2020-11-01 09:40:06,218-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
> 2020-11-01 09:40:10,711-INFO: Dataset /data/aben/PP-YOLO2/dataset\VOCdevkit is not valid for reason above, try searching /root/.cache/paddle/dataset or downloading dataset...
> Traceback (most recent call last):
> File "tools/train.py", line 372, in
> main()
> File "tools/train.py", line 148, in main
> eval_reader = create_reader(cfg.EvalReader, devices_num=1)
> File "/data/aben/PP-YOLO2/ppdet/data/reader.py", line 441, in create_reader
> reader = Reader(**cfg)()
> File "/data/aben/PP-YOLO2/ppdet/data/reader.py", line 210, in **init**
> self._roidbs = self._dataset.get_roidb()
> File "/data/aben/PP-YOLO2/ppdet/data/source/dataset.py", line 65, in get_roidb
> self.image_dir)
> File "/data/aben/PP-YOLO2/ppdet/utils/download.py", line 154, in get_dataset_path
> format(path, osp.split(path)[-1]))
> ValueError: Dataset dataset\VOCdevkit is not valid and cannot parse dataset type 'dataset\VOCdevkit' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face', 'fruit' and 'roadsign_voc' currently
> 
> ![image](https://user-images.githubusercontent.com/73775889/97799624-310d5300-1c6a-11eb-8cff-df3819f3482e.png)
> 以上是我路徑和reader裡的設置
> 請問這個報錯要怎麼解決?

建议路径用 `/` 进行设置尝试一下。

**Comment by aben1919** [comment]
我試著把路徑用 / 改了，可以跑成功，謝謝。

**Comment by XiaoWen-AI** [comment]
![image](https://user-images.githubusercontent.com/38575973/98058094-df89e180-1e7e-11eb-9f45-84414d837682.png)
我也是报了类似的错误，但是我路径是使用‘/’啊，知道是什么毛病吗
