### ISSUE TITLE
使用ppyolo训练自己的voc格式数据集，出现损失函数较大，精度比其他算法低

### ISSUE THREAD

**Issue by May52** [PaddlePaddle/PaddleDetection#1646]
使用ppyolo训练自己的单类 voc格式数据集，数据集含有小目标较多，只修改了ppyolovoc.yml文件的部分参数：
max_iters: 8000
num_classes: 1
LearningRate:
#base_lr: 0.00333
base_lr: 0.001
schedulers:

!PiecewiseDecay
gamma: 0.1
milestones:
3000
5000
!LinearWarmup
start_factor: 0.
steps: 1000
其中base_lr: 0.00333也试过，部分训练结果如下：
![image](https://user-images.githubusercontent.com/52195642/97945057-4fd22d80-1dc1-11eb-8b12-c93f93bdc8c7.png)

loss在iter: 6000左右就稳定在70左右，AP0.5在此也达到最高0.7419，精度比YOLOv3和二阶段算法都低。
loss_obj和loss_iou较大，请问该如何调整参数？

**Comment by jerrywgz** [comment]
有几个方向可以尝试：
1. 通过https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/tools/anchor_cluster.py 重新对数据集进行聚类得到更适合的anchor
2. 使用ppyolo在coco数据集上的权重作为预训练模型https://paddlemodels.bj.bcebos.com/object_detection/ppyolo_2x.pdparams

另外ppyolo使用了较多数据增强，因此需要比较长的训练时间来达到更好的效果

**Comment by May52** [comment]
> 有几个方向可以尝试：
> 
> 1. 通过https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/tools/anchor_cluster.py 重新对数据集进行聚类得到更适合的anchor
> 2. 使用ppyolo在coco数据集上的权重作为预训练模型https://paddlemodels.bj.bcebos.com/object_detection/ppyolo_2x.pdparams
> 
> 另外ppyolo使用了较多数据增强，因此需要比较长的训练时间来达到更好的效果

您好，非常感谢！我还想问下我的数据集只有一个类别，一共300张图片，含有目标4432个，训练集242张，设置batch_size=24，最大训练次数max_iters设置为8000应该是够的吧？还是要增大训练次数呢？

**Comment by jerrywgz** [comment]
这个训练轮数是足够的，你现在的训练图片比较少，确实可以尝试用下ppyolo在coco上训好的权重然后finetune 这样效果会比较好

**Comment by May52** [comment]
> 这个训练轮数是足够的，你现在的训练图片比较少，确实可以尝试用下ppyolo在coco上训好的权重然后finetune 这样效果会比较好

好的，谢谢！
