### ISSUE TITLE
模型压缩

### ISSUE THREAD

**Issue by wangning7149** [PaddlePaddle/PaddleDetection#1647]
请问自己设计的模型可以用本仓库的模型压缩api进行压缩吗？🙂🙂🙂

**Comment by jerrywgz** [comment]
可以尝试的，PaddleDetection提供了基于yolo的剪裁，量化，蒸馏的示例。更多技术细节也可以参考https://github.com/PaddlePaddle/PaddleSlim 这里

**Comment by wangning7149** [comment]
> 可以尝试的，PaddleDetection提供了基于yolo的剪裁，量化，蒸馏的示例。更多技术细节也可以参考https://github.com/PaddlePaddle/PaddleSlim 这里

谢谢您的解答！！，我再问一个比较偷懒的问题，有尝试成功的案例吗？

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/slim    这里有YOLOv3压缩模型库
