### ISSUE TITLE
faster_rcnn_r50_1x预测数据生成的问题

### ISSUE THREAD

**Issue by atczyh** [PaddlePaddle/PaddleDetection#165]
已使用faster_rcnn_r50_1x使用自定义数据集训练一只模型，在参考paddledetection infer.py文件生成预测数据时遇到了如下问题，我提取infer文件中关于数据生成的部分代码，做成数据生成的class，如下所示：

```
class getdata(object):
    def __init__(self, path, config):
        self.imgpath = path
        self.config=config
    def getinferdata(self):
        from ppdet.core.workspace import create,load_config
        from ppdet.modeling.model_input import create_feed
        from ppdet.data.data_feed import create_reader
        cfg = load_config(self.config)
        test_feed = create(cfg.test_feed)#FasterRCNNTestFeed
        #print('test_feed1',test_feed,cfg.test_feed)#<class 'ppdet.data.data_feed.FasterRCNNTestFeed'>
        #添加图片到test_feed ppdet.data.data_feed.FasterRCNNTestFeed
        #print(type(test_feed))
        test_images = get_test_images(None, self.imgpath)
        test_feed.dataset.add_images(test_images)
        loader, feed_vars = create_feed(test_feed, iterable=True)#ppdet.modeling.model_input
        #print('feed_vars',type(feed_vars),feed_vars)
        reader = create_reader(test_feed)
        #print(loader.feed_list)
        place =fluid.CPUPlace()
        loader.set_sample_list_generator(reader,place)
        for iter_id, data in enumerate(loader()):
            print('1',iter_id, type(data),data)
            del place,test_images,create,create_feed,create_reader,reader,loader,test_feed
            gc.collect()
            return data
        return None

john = getdata("ls/004186.jpg",'configs/faster_rcnn_r50_1x.yml')
data=john.getinferdata()
print(data)
del john,data
gc.collect()
json1 = getdata("PaddleDetection/000003.jpg",'configs/faster_rcnn_r50_1x.yml')
data=json1.getinferdata()
print(data)
```

这个类第一次调用可以成功生成预测数据，但是调用第二次就会报错，输出数据如下：

```
num_scale 1（第一次调用成功）
1 0 <class 'list'> [{'im_shape': <paddle.fluid.core_avx.LoDTensor object at 0x7fb1be48eed8>, 'im_id': <paddle.fluid.core_avx.LoDTensor object at 0x7fb1f7b85768>, 'im_info': <paddle.fluid.core_avx.LoDTensor object at 0x7fb1be88edf8>, 'image': <paddle.fluid.core_avx.LoDTensor object at 0x7fb1be4916f8>}]
[{'im_shape': <paddle.fluid.core_avx.LoDTensor object at 0x7fb1be48eed8>, 'im_id': <paddle.fluid.core_avx.LoDTensor object at 0x7fb1f7b85768>, 'im_info': <paddle.fluid.core_avx.LoDTensor object at 0x7fb1be88edf8>, 'image': <paddle.fluid.core_avx.LoDTensor object at 0x7fb1be4916f8>}]

num_scale 1（第二次调用失败）
2020-01-05 17:48:40,898-WARNING: fail to map op [ArrangeTestRCNN_f24b57] with error: 'tuple' object has no attribute 'keys' and stack:
Traceback (most recent call last):
  File "/home/zengyihui/Documents/PaddleDetection/ppdet/data/transform/__init__.py", line 77, in _mapper
    out = f(sample, ctx)
  File "/home/zengyihui/Documents/PaddleDetection/ppdet/data/transform/arrange_sample.py", line 159, in __call__
    keys = sorted(list(sample.keys()))
AttributeError: 'tuple' object has no attribute 'keys'

2020-01-05 17:48:40,898-WARNING: consumer failed with error: failed to map consumer[%s], error: 'tuple' object has no attribute 'keys'
2020-01-05 17:48:40,899-WARNING: consumer failed with error: failed to map consumer[%s], error: 'tuple' object has no attribute 'keys'[consumer[consumer-68e_1] exits]
2020-01-05 17:48:40,899-WARNING: Your reader has raised an exception!
```

请帮忙查看下什么原因。造成预测数据生成出错，预测数据该如何准备？能否提供一份fastRCNN预测数据生成的案例？

**Comment by qingqing01** [comment]
@atczyh  看你上述代码，是想从输入图片拿到预处理后的数据吧，

1.  当前tools/infer.py支持对多张图片进行预测，通过 `--infer_dir` 指定即可。
2.  如果要自己写:

基于relaese分支, 如下方式，创建一次Data Loader的, 再for循环:

```
import os
import glob

from paddle import fluid
from ppdet.core.workspace import create,load_config
from ppdet.modeling.model_input import create_feed
from ppdet.data.data_feed import create_reader

import logging
FORMAT = '%(asctime)s-%(levelname)s: %(message)s'
logging.basicConfig(level=logging.INFO, format=FORMAT)
logger = logging.getLogger(__name__)

def get_test_images(infer_dir, infer_img):
    """
    Get image path list in TEST mode
    """
    assert infer_img is not None or infer_dir is not None, \
        "--infer_img or --infer_dir should be set"
    assert infer_img is None or os.path.isfile(infer_img), \
            "{} is not a file".format(infer_img)
    assert infer_dir is None or os.path.isdir(infer_dir), \
            "{} is not a directory".format(infer_dir)
    images = []

    # infer_img has a higher priority
    if infer_img and os.path.isfile(infer_img):
        images.append(infer_img)
        return images

    infer_dir = os.path.abspath(infer_dir)
    assert os.path.isdir(infer_dir), \
        "infer_dir {} is not a directory".format(infer_dir)
    exts = ['jpg', 'jpeg', 'png', 'bmp']
    exts += [ext.upper() for ext in exts]
    for ext in exts:
        images.extend(glob.glob('{}/*.{}'.format(infer_dir, ext)))

    assert len(images) > 0, "no image found in {}".format(infer_dir)
    logger.info("Found {} inference images in total.".format(len(images)))
    return images



image_path = 'images'  # 设置图片路径。

cfg = load_config('configs/faster_rcnn_r50_1x.yml')
test_feed = create(cfg.test_feed)
test_images = get_test_images(image_path, None)
test_feed.dataset.add_images(test_images)
reader = create_reader(test_feed)

loader, feed_vars = create_feed(test_feed, iterable=True) #ppdet.modeling.model_input
place =fluid.CPUPlace()
loader.set_sample_list_generator(reader,place)

for iter_id, data in enumerate(loader()):
  print(iter_id, data)

```

3.  master分支，提供了 tools/cpp_infer.py，也可以参考

**Comment by atczyh** [comment]
@qingqing01 是的，我想使用这个paddleDetection的库+训练好的模型+infer的图片数据预处理代码 +flask架设一个图片识别服务 因此需要用到图片预处理的方法，我先试试您提供的方法。

**Comment by atczyh** [comment]
@qingqing01 通过flask接口的图片是一张张上传的，我需要数据处理过程封装成函数调用，但是这个函数只能成功调用一次，调用第二次就会报错，代码如下：
def getinferdata(image_path):
    cfg = load_config('configs/faster_rcnn_r50_1x.yml')
    test_feed = create(cfg.test_feed)
    test_images = get_test_images(None, image_path)
    test_feed.dataset.add_images(test_images)
    reader = create_reader(test_feed)
    loader, feed_vars = create_feed(test_feed, iterable=True) #ppdet.modeling.model_input
    place =fluid.CPUPlace()
    loader.set_sample_list_generator(reader,place)
    for iter_id, data in enumerate(loader()):
        print(iter_id, data)
        return data
    
path='/home/文档/yolov3L/testdata/ls/004186.jpg'
data=getinferdata(path)
print(data)
path='/home/Documents/PaddleDetection/000003.jpg'
data=getinferdata(path)
print(data)
报错信息如下：
num_scale 1
0 [{'im_shape': <paddle.fluid.core_avx.LoDTensor object at 0x7f81557987a0>, 'im_id': <paddle.fluid.core_avx.LoDTensor object at 0x7f8154b9d768>, 'im_info': <paddle.fluid.core_avx.LoDTensor object at 0x7f8154b9d848>, 'image': <paddle.fluid.core_avx.LoDTensor object at 0x7f8154b9d7a0>}]
[{'im_shape': <paddle.fluid.core_avx.LoDTensor object at 0x7f81557987a0>, 'im_id': <paddle.fluid.core_avx.LoDTensor object at 0x7f8154b9d768>, 'im_info': <paddle.fluid.core_avx.LoDTensor object at 0x7f8154b9d848>, 'image': <paddle.fluid.core_avx.LoDTensor object at 0x7f8154b9d7a0>}]
num_scale 1
2020-01-06 18:34:16,287-WARNING: fail to map op [ArrangeTestRCNN_aa4be2] with error: 'tuple' object has no attribute 'keys' and stack:
Traceback (most recent call last):
  File "/home/Documents/PaddleDetection/ppdet/data/transform/__init__.py", line 77, in _mapper
    out = f(sample, ctx)
  File "/home/zengyihui/Documents/PaddleDetection/ppdet/data/transform/arrange_sample.py", line 159, in __call__
    keys = sorted(list(sample.keys()))
AttributeError: 'tuple' object has no attribute 'keys'

2020-01-06 18:34:16,288-WARNING: consumer failed with error: failed to map consumer[%s], error: 'tuple' object has no attribute 'keys'
2020-01-06 18:34:16,289-WARNING: consumer failed with error: failed to map consumer[%s], error: 'tuple' object has no attribute 'keys'[consumer[consumer-0c2_1] exits]
2020-01-06 18:34:16,290-WARNING: Your reader has raised an exception!
None
请帮忙解决。。。

**Comment by qingqing01** [comment]
@atczyh 我试了下你上面代码是不太work，但为了搭建图片识别服务，建议预处理可以直接写，不采用"infer.py"中的reader。对于FasterRCNN系列预处理如下，输入需要 image和im_info 2个字段:

```
from __future__ import print_function
import paddle.fluid as fluid
import numpy as np
import cv2
from PIL import Image, ImageDraw
from ppdet.utils.coco_eval import get_category_info
import time

def Permute(im, channel_first=True, to_bgr=False):
    if channel_first:
        im = np.swapaxes(im, 1, 2)
        im = np.swapaxes(im, 1, 0)
    if to_bgr:
        im = im[[2, 1, 0], :, :]
    return im


def DecodeImage(im_path):
    with open(im_path, 'rb') as f:
        im = f.read()
    data = np.frombuffer(im, dtype='uint8')
    im = cv2.imdecode(data, 1)  # BGR mode, but need RGB mode
    im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
    print("DecodeImage shape ", im.shape)
    return im


def ResizeImage(im, target_size=608, max_size=0):
    if len(im.shape) != 3:
        raise ImageError('image is not 3-dimensional.')
    im_shape = im.shape
    im_size_min = np.min(im_shape[0:2])
    im_size_max = np.max(im_shape[0:2])
    if float(im_size_min) == 0:
        raise ZeroDivisionError('min size of image is 0')
    if max_size != 0:
        im_scale = float(target_size) / float(im_size_min)
        # Prevent the biggest axis from being more than max_size
        if np.round(im_scale * im_size_max) > max_size:
            im_scale = float(max_size) / float(im_size_max)
        im_scale_x = im_scale
        im_scale_y = im_scale
    else:
        im_scale_x = float(target_size) / float(im_shape[1])
        im_scale_y = float(target_size) / float(im_shape[0])

    im = cv2.resize(
             im,
             None,
             None,
             fx=im_scale_x,
             fy=im_scale_y,
             interpolation=2)
    h, w, c = im.shape
    im_info = np.array([h, w, im_scale_x]).astype(np.float32)
    return im, im_info


def NormalizeImage(im,mean = [0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], is_scale=True):
    im = im.astype(np.float32, copy=False)
    mean = np.array(mean)[np.newaxis, np.newaxis, :]
    std = np.array(std)[np.newaxis, np.newaxis, :]
    if is_scale:
        im = im / 255.0
    im -= mean
    im /= std
    return im


def Prepocess(img_path):
    test_img = DecodeImage(img_path)
    img_shape = test_img.shape[:2]
    test_img = NormalizeImage(test_img)
    test_img, im_info = ResizeImage(test_img, target_size=800, max_size=1333)
    test_img = Permute(test_img)
    test_img = test_img[np.newaxis,:]#.reshape(1, 3, 608, 608)
    return test_img, im_info

path='images/000000014439.jpg'
test_img, im_info = Prepocess(path)
print(test_img.shape, im_info)

path='images/000000087038.jpg'
test_img, im_info = Prepocess(path)
print(test_img.shape, im_info)
```

**Comment by atczyh** [comment]
@qingqing01 我使用代码对数据进行了封装
path='images/000000014439.jpg'
test_img, im_info = Prepocess(path)
list=[]
image={'im_shape': 23, 'im_id': 2,'im_info': 3, 'image': 3}
image['im_shape']=test_img.shape
image['im_info']=im_info
image['im_id']=1
image['image']=test_img
list.append(image)
print(list)

path='images/000000014439.jpg'
test_img, im_info = Prepocess(path)
image={'im_shape': 23, 'im_id': 2,'im_info': 3, 'image': 3}
image['im_shape']=test_img.shape
image['im_info']=im_info
image['im_id']=1
image['image']=test_img
list.append(image)
print(list)

outs = exe.run(infer_prog,feed=list,fetch_list=values,return_numpy=False)
预测过程中报错：
/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/infertest.py", line 355, in <module>
    main()
  File "tools/infertest.py", line 286, in main
    outs = exe.run(infer_prog,feed=list,fetch_list=values,return_numpy=False)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/home/zengyihui/.local/lib/python3.6/site-packages/six.py", line 696, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 822, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 899, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::SliceOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
5   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
6   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
7   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool)
Error: The index of dimension in axes must be less than the size of input shape.
  [Hint: Expected static_cast<int>(axes[i]) < in_dims.size(), but received static_cast<int>(axes[i]):1 >= in_dims.size():1.] at (/paddle/paddle/fluid/operators/slice_op.cc:83)
  [operator < slice > error]
是否需要将数据转换成：
<class 'list'> [{'im_shape': <paddle.fluid.core_avx.LoDTensor object at 0x7fb7cad51768>, 'im_id': <paddle.fluid.core_avx.LoDTensor object at 0x7fb7910beca8>, 'im_info': <paddle.fluid.core_avx.LoDTensor object at 0x7fb7910bef10>, 'image': <paddle.fluid.core_avx.LoDTensor object at 0x7fb7910beea0>}]
，如何将变量转换paddle.fluid.core_avx.LoDTensor  格式？

**Comment by qingqing01** [comment]
@atczyh 不需要转换成 "paddle.fluid.core_avx.LoDTensor" 格式，Executor接受numpy.array的数据格式。麻烦再检查下Run时的数据shape，是否是[N, C, H, W]格式，im_info格式是否是[N, 3].

**Comment by qingqing01** [comment]
@atczyh  https://github.com/PaddlePaddle/PaddleDetection/issues/98#issue-535660400 这个例子虽然是YOLOv3，对FasterRCNN类似，也是直接feed给 numpy.array的数据格式即可。

**Comment by atczyh** [comment]
@qingqing01 请问 paddle.fluid.core_avx.LoDTensor 内的数据如何打印出来 我想对比下数据间的差异，以下是转换后的数据：
{'im_shape': (1, 3, 800, 1333), 'im_id': 0, 'im_info': array([8.0000000e+02, 1.3330000e+03, 5.2070314e-01], dtype=float32), 'image': array([[[[ 0.6220568 ,  0.6220569 ,  0.6220568 , ...,  0.99880135,
           0.99880135,  0.9988013 ],
         [ 0.6220567 ,  0.6220568 ,  0.6220567 , ...,  0.99880135,
           0.99880135,  0.9988014 ],
         [ 0.6220567 ,  0.62205684,  0.6220567 , ...,  0.9988013 ,
           0.9988013 ,  0.9988013 ],
         ...,
         [-0.7107959 , -1.978642  , -1.0227453 , ..., -0.6129952 ,
          -0.60626346, -0.5948097 ],
         [-1.7116563 , -1.578725  , -1.4760184 , ..., -0.61358744,
          -0.60325986, -0.57555974],
         [-1.7958417 , -1.4656798 , -1.4094716 , ..., -0.6357252 ,
          -0.58273023, -0.55445844]],

        [[ 0.83543426,  0.83543426,  0.83543426, ...,  1.2205883 ,
           1.2205883 ,  1.2205883 ],
         [ 0.8354342 ,  0.8354342 ,  0.8354342 , ...,  1.2205883 ,
           1.2205883 ,  1.2205883 ],
         [ 0.8354343 ,  0.8354343 ,  0.8354343 , ...,  1.2205882 ,
           1.2205882 ,  1.2205882 ],
         ...,
         [-0.8072817 , -2.0739863 , -1.098069  , ..., -0.49721372,
          -0.49033198, -0.47862253],
         [-1.8304826 , -1.6973042 , -1.548091  , ..., -0.49781927,
          -0.4872612 , -0.45894283],
         [-1.9165473 , -1.5813727 , -1.4826764 , ..., -0.52045125,
          -0.46627334, -0.43737045]],

        [[ 1.106231  ,  1.106231  ,  1.106231  , ...,  1.4896734 ,
           1.4896734 ,  1.4896734 ],
         [ 1.106231  ,  1.106231  ,  1.106231  , ...,  1.4896734 ,
           1.4896734 ,  1.4896734 ],
         [ 1.1062311 ,  1.1062311 ,  1.1062311 , ...,  1.4896734 ,
           1.4896734 ,  1.4896734 ],
         ...,
         [-0.5466131 , -1.8245884 , -0.84787995, ..., -0.48193207,
          -0.47508076, -0.46342334],
         [-1.5652664 , -1.4313004 , -1.3031341 , ..., -0.4825349 ,
          -0.47202367, -0.4438311 ],
         [-1.6509485 , -1.3160906 , -1.2367007 , ..., -0.50506616,
          -0.45112914, -0.42235464]]]], dtype=float32)}

**Comment by qingqing01** [comment]
假如paddle.fluid.core_avx.LoDTensor的数据是t， np.array(t)即可转换为numpy数据格式

**Comment by atczyh** [comment]
@qingqing01 我通过变量转换发现相同的照片在paddledetection官方案例的infer的转换结果和以上代码的转换值不一样，paddledetection的具体如下：
im_shape 	lod: {}
	dim: 1, 3
	layout: NCHW
	dtype: float
	data: [1920 2560 1]
im_info 	lod: {}
	dim: 1, 3
	layout: NCHW
	dtype: float
	data: [800 1067 0.416667]
，通过上文代码转换的转换结果如下：
'im_shape': (1, 3, 800, 1333),  'im_info': array([8.0000000e+02, 1.3330000e+03, 5.2070314e-01], dtype=float32)，请帮忙确认。

**Comment by qingqing01** [comment]
@atczyh 请问分别打印的是什么？ 在哪里打印的？是否同一张图片？

**Comment by atczyh** [comment]
@qingqing01 我已将两份转换代码与结果上传了，两份转换代码输入的都是同一张图片，github
使用paddle自带infer 转换代码如链接 [https://github.com/atczyh/paddletest/blob/master/paddleinfer.py](url)
转换结果如下：
[https://github.com/atczyh/paddletest/blob/master/paddleinfer.txt](url)
使用您推荐的转换代码如下：
[https://github.com/atczyh/paddletest/blob/master/inferimage.py](url)
转换结果如下：
[https://github.com/atczyh/paddletest/blob/master/inferimage.txt](url)
两者转换值确实有少许差异，使用转换结果进行预测会报如下错误，无法成功预测，请帮忙查看：
----------------------
Error Message Summary:
----------------------
Error: The index of dimension in axes must be less than the size of input shape.
  [Hint: Expected static_cast<int>(axes[i]) < in_dims.size(), but received static_cast<int>(axes[i]):1 >= in_dims.size():1.] at (/paddle/paddle/fluid/operators/slice_op.cc:83)
  [operator < slice > error]

**Comment by qingqing01** [comment]
@atczyh 注意im_info的shape是(1, 3)，不是(3,)，` im_info=im_info[np.newaxis,:]` 看下

**Comment by atczyh** [comment]
@qingqing01 添加im_info=im_info[np.newaxis,:]之后'im_info': array([[7.5000000e+02, 1.3330000e+03, 5.2070314e-01]], dtype=float32)，但是报错
----------------------
Error Message Summary:
----------------------
Error: The rank of Input(Input) in BoxClipOp must be 2
  [Hint: Expected im_info_dims.size() == 2, but received im_info_dims.size():1 != 2:2.] at (/paddle/paddle/fluid/operators/detection/box_clip_op.cc:37)
  [operator < box_clip > error]

**Comment by qingqing01** [comment]
@atczyh 

你的错误是还是im_info，im_shape这些shape没搞对。注意都是2D的形状，[1,3] 这样。 我是用你的程序，加了部分代码如下，是能跑通的。

先导出模型:

```
python tools/export_model.py -c configs/faster_rcnn_r50_1x.yml \
        --output_dir=./inference_model \
        -o weights=https://paddlemodels.bj.bcebos.com/object_detection/faster_rcnn_r50_1x.tar # 你自己的模型
```

再使用下面程序预测:

```
from __future__ import print_function
import paddle.fluid as fluid
import numpy as np
import cv2
from PIL import Image, ImageDraw
from ppdet.utils.coco_eval import get_category_info
import time

def Permute(im, channel_first=True, to_bgr=False):
    if channel_first:
        im = np.swapaxes(im, 1, 2)
        im = np.swapaxes(im, 1, 0)
    if to_bgr:
        im = im[[2, 1, 0], :, :]
    return im


def DecodeImage(im_path):
    with open(im_path, 'rb') as f:
        im = f.read()
    data = np.frombuffer(im, dtype='uint8')
    im = cv2.imdecode(data, 1)  # BGR mode, but need RGB mode
    im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
    print("DecodeImage shape ", im.shape)
    return im


def ResizeImage(im, target_size=608, max_size=0):
    if len(im.shape) != 3:
        raise ImageError('image is not 3-dimensional.')
    im_shape = im.shape
    im_size_min = np.min(im_shape[0:2])
    im_size_max = np.max(im_shape[0:2])
    if float(im_size_min) == 0:
        raise ZeroDivisionError('min size of image is 0')
    if max_size != 0:
        im_scale = float(target_size) / float(im_size_min)
        # Prevent the biggest axis from being more than max_size
        if np.round(im_scale * im_size_max) > max_size:
            im_scale = float(max_size) / float(im_size_max)
        im_scale_x = im_scale
        im_scale_y = im_scale
    else:
        im_scale_x = float(target_size) / float(im_shape[1])
        im_scale_y = float(target_size) / float(im_shape[0])

    im = cv2.resize(
             im,
             None,
             None,
             fx=im_scale_x,
             fy=im_scale_y,
             interpolation=2)
    h, w, c = im.shape
    im_info = np.array([h, w, im_scale_x]).astype(np.float32)
    return im, im_info


def NormalizeImage(im,mean = [0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], is_scale=True):
    im = im.astype(np.float32, copy=False)
    mean = np.array(mean)[np.newaxis, np.newaxis, :]
    std = np.array(std)[np.newaxis, np.newaxis, :]
    if is_scale:
        im = im / 255.0
    im -= mean
    im /= std
    return im


def Prepocess(img_path):
    test_img = DecodeImage(img_path)
    #img_shape = test_img.shape[1:]
    test_img, im_info = ResizeImage(test_img, target_size=800, max_size=1333)
    test_img = NormalizeImage(test_img)
    test_img = Permute(test_img)
    test_img = test_img[np.newaxis, :]  # reshape, [1, C, H, W]
    print('1 ',im_info.shape)
    im_info=im_info[np.newaxis,:]
    #im_info=im_info.tolist()
    #im_info=[im_info]
    #im_info=np.array(im_info)
    print(im_info)
    print('2 ',im_info.shape)
    sp = test_img.shape[2:]
    print('3 ', sp)
    im_shape = np.array([test_img.shape[2:] + (1.,)]).astype('float32')
    print('3 ', im_shape)
    return im_shape, test_img, im_info

#img_path = "demo/000000014439.jpg"
path = "demo/000000014439.jpg"
#path='/home/Documents/PaddleDetection/004696.jpg'
img_shape, test_img, im_info = Prepocess(path)

#place = fluid.CUDAPlace(0)
place = fluid.CPUPlace()
exe = fluid.Executor(place)

path = "./inference_model/faster_rcnn_r50_1x"

[inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(
    dirname=path, executor=exe, model_filename='__model__', params_filename='__params__')
print(feed_target_names, test_img.shape, img_shape, fetch_targets)
print(test_img.shape, im_info.shape, img_shape.shape)
outs = exe.run(inference_program,
          feed={feed_target_names[0]: test_img, feed_target_names[1]: im_info, feed_target_names[2]: img_shape},
          fetch_list=fetch_targets,
          return_numpy=False)
print(np.array(outs))
```

**Comment by atczyh** [comment]
@qingqing01 问题已经解决了多谢了！

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/241 已经在docs/advanced_tutorials/inference/EXPORT_MODEL.md处添加详细的导出模型的输入输出描述，可供参考
