### ISSUE TITLE
官方docker镜像，运行时卡住不动

### ISSUE THREAD

**Issue by songfh** [PaddlePaddle/PaddleDetection#1651]
![image](https://user-images.githubusercontent.com/22196645/98081880-d9155d00-1eb2-11eb-8413-bbba7c114915.png)
尝试了官方1.8.4和1.8.5两个版本的镜像，运行install_check.run_check()都会卡着不动，训练的时候一样卡着不动。

**Comment by songfh** [comment]
export CUDA_VISIBLE_DEVIDES=0，使用单张GPU的时候可以正常训练

**Comment by willthefrog** [comment]
建议去[框架repo](https://github.com/PaddlePaddle/Paddle)里提下issue，可能镜像里的版本编译时没开启`WITH_DISTRIBUTE`

**Comment by songfh** [comment]
> 建议去[框架repo](https://github.com/PaddlePaddle/Paddle)里提下issue，可能镜像里的版本编译时没开启`WITH_DISTRIBUTE`

多谢，运行docker的时候加了--ipc=host已经运行正常了。

**Comment by willthefrog** [comment]
好的。
