### ISSUE TITLE
giou_loss_yolo

### ISSUE THREAD

**Issue by shisan695** [PaddlePaddle/PaddleDetection#1653]
请问paddledection里giou_loss_yolo应该怎么编写？

**Comment by yghstill** [comment]
@shisan695 GiouLoss目前只在ttfnet上使用了，如需在YOLO中使用，需要按照Iou_loss的输入，修改相应GiouLoss的输入内容并适配计算：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/losses/iou_loss.py#L54
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/losses/giou_loss.py#L86
