### ISSUE TITLE
mask rcnn 导出模型后预测没有mask 结果输出！！（tips :已升级至release/0.4版本）

### ISSUE THREAD

**Issue by wangkan83** [PaddlePaddle/PaddleDetection#1654]
tips :已升级至release/0.4版本。训练了一个mask_rcnn_r50模型，对于同一张图片，用tools/infer.py可以预测出结果，但是用tools/export_model.py将模型转换导出后，再预测没有mask结果。求解决！
![image](https://user-images.githubusercontent.com/63913709/98187950-0ca4c580-1f4d-11eb-890d-0c0888e6a7c3.png)

**Comment by wangkan83** [comment]
另外，将模型转换导出后用deploy/python/infer.py和用tools/infer.py预测出来的标签不一致，tools/infer.py预测出来是正确的，deploy/python/infer.py预测出来的是backgroud，求解决！！

**Comment by yghstill** [comment]
@wangkan83 我在release/0.4分支最新代码上测试没有任何问题，代码更新到最新了吗，重新下载最新代码再试下？

**Comment by wangkan83** [comment]
@yghstill 重新下载release/0.4，用其中deploy/python文件夹覆盖原来的，结果输出的result中显示有masks，求问：如何获得预测各种标签的中的masks坐标、Number of pixels，以便统计各种mask的大小。求解决！！

**Comment by yghstill** [comment]
@wangkan83 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/python/visualize.py#L131  这里结果就是最终输出的mask，可以获取并进行操作。

**Comment by wangkan83** [comment]
@yghstill ，thanks!
