### ISSUE TITLE
特征图显示问题

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#1656]
如何将某层卷积通道中的特征都显示出来，像下面这个图这样
![image](https://user-images.githubusercontent.com/68497831/98213748-7ee2cd80-1f80-11eb-8306-564e0046e14e.png)

**Comment by yghstill** [comment]
@qdd1234 目前静态图下无法直接保存特征图，需要将特征图根据block的名字加入fetch_list 中，然后根据key获取输出结果再可视化，https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/tools/infer.py#L174 。动态图模式下就比较方便了，只需要tensor.numpy()就可获取feture map，可随时可视化。
