### ISSUE TITLE
blazeface_keypoint 模型获取关键点信息问题

### ISSUE THREAD

**Issue by dongsen112** [PaddlePaddle/PaddleDetection#1657]
目前已知该模型的四个输出：
1.bbox[N,6]
2.faceindex[N,1]
3.keypoints[N,num_prior_box,10]
4.prior_box[num_prior_box,4]
现在是通过bbox的第二个元素值大于 0.9，判定是否是有效检测框，进而获得与这个检测框对应的faceindex。
通过faceindex，可以取得prior_box的四个元素，目前可以画出预测框。
但是目前不清楚如何获取有效的keypoints，尝试过使用faceindex获取与预测框对应的keypoints，但是获取的值看起来并不对，而且有负数。看了keypoints的输出，值的取值范围基本在-5到5之间。
请问如何取出预测框对应的keypoints，keypoints的取值范围是-5到5，如何转换成图像对应的坐标？

**Comment by yghstill** [comment]
@dongsen112 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/utils/widerface_eval_utils.py#L232  可以查看转换映射坐标的代码

**Comment by dongsen112** [comment]
> @dongsen112 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/utils/widerface_eval_utils.py#L232 可以查看转换映射坐标的代码

@yghstill 谢谢回复，试了一下，鼻子的关键点比较准，眼睛和两个嘴角不是特别准，经常晃动，是否有什么优化建议吗？

**Comment by yghstill** [comment]
@dongsen112 你是直接使用blazeface的预训练模型吗？建议在自己数据集上再重新训练一下，blazeface模型比较小，对于较大人脸检测效果较好。

**Comment by dongsen112** [comment]
> @dongsen112 你是直接使用blazeface的预训练模型吗？建议在自己数据集上再重新训练一下，blazeface模型比较小，对于较大人脸检测效果较好。

@yghstill 好的，谢谢
