### ISSUE TITLE
请教各位大佬，动态图中怎么实现ppyolo中的EMA呢？

### ISSUE THREAD

**Issue by miemie2013** [PaddlePaddle/PaddleDetection#1659]
完整代码请见

https://aistudio.baidu.com/aistudio/projectdetail/1156231

我本已经写了一些代码（如下），按照我自己对EMA的了解。在模型训练之前先调用init_ema_state_dict()函数，模型每训练完一步后都会调用update_ema_state_dict()函数更新参数。训练过程中在eval之前调用apply_ema_state_dict()使用ema字典里的参数来进行评测；eval之后调用restore_current_state_dict()恢复之前的参数。按照这样的代码来跑，mAP先上升再下降到0，并没有成功实现ema。请教各位大佬哪里出错了？不胜感激！

# ppyolo.py
import paddle
import os
import shutil
from collections import OrderedDict
from paddle.static import InputSpec

class PPYOLO(paddle.nn.Layer):
    def __init__(self, backbone, head, ema_decay=0.9998):
        super(PPYOLO, self).__init__()
        self.backbone = backbone
        self.head = head
        self.ema_decay = ema_decay
        self.ema_state_dict = OrderedDict()   # ema字典

    def forward(self, x, im_size):
        body_feats = self.backbone(x)
        out = self.head.get_prediction(body_feats, im_size)
        return out

    def train_model(self, x, gt_box, gt_label, gt_score, targets):
        body_feats = self.backbone(x)
        out = self.head.get_loss(body_feats, gt_box, gt_label, gt_score, targets)
        return out

    def init_ema_state_dict(self, thres_steps):
        exist = os.path.exists('./ema/ema.pdopt')
        if exist and thres_steps > 0:
            _, self.ema_state_dict = paddle.load('./ema/ema')   # ema存储成了.pdopt格式
        else:
            if thres_steps == 0:
                if os.path.exists('./ema/'): shutil.rmtree('./ema/')
            temp_dict = self.state_dict()
            for k, v in temp_dict.items():
                v2 = v * 0   # 参数用0初始化（包括可训练参数、bn层的均值、bn层的方差）
                self.ema_state_dict[k] = v2

    def update_ema_state_dict(self, thres_steps):
        decay2 = (1.0 + thres_steps) / (10.0 + thres_steps)
        ema_decay = min(self.ema_decay, decay2)  # 真实的衰减率
        temp_dict = self.state_dict()
        for k, v in temp_dict.items():    # bn层的均值、方差也受该全局ema管理（尽管它们有自己的滑动平均）
            v2 = self.ema_state_dict[k]   # ema中旧的值
            v2 = ema_decay * v2 + (1.0 - ema_decay) * v   # ema中新的值
            v2 = v2 / (1.0 - ema_decay ** (thres_steps + 1))   # 偏置校正
            v2.stop_gradient = True       # v2不需要更新。不写这句的话显存会爆炸。
            self.ema_state_dict[k] = v2   # ema写入新的值

    def apply_ema_state_dict(self):
        # 避免复杂的指针操作，直接写进硬盘
        paddle.save(self.state_dict(), './ema/current')
        paddle.save(self.ema_state_dict, './ema/ema')   # ema存储成了.pdopt格式
        self.set_state_dict(self.ema_state_dict)

    def restore_current_state_dict(self):
        _, self.ema_state_dict = paddle.load('./ema/ema')   # ema存储成了.pdopt格式
        current, _ = paddle.load('./ema/current')
        self.set_state_dict(current)
        temp_dict = self.ema_state_dict
        for k, v in temp_dict.items():
            if isinstance(v, dict):
                continue
            else:
                v2 = paddle.to_tensor(v)
                self.ema_state_dict[k] = v2

**Comment by yghstill** [comment]
@miemie2013 动态图下的EMA模块近期会添加，目前请参考以下实现形式吧：
```python
import paddle
import numpy as np


class ExponentialMovingAverage():
    def __init__(self, model, decay, thres_steps=True):
        self._model = model
        self._decay = decay
        self._thres_steps = thres_steps
        self._shadow = {}
        self._backup = {}

    def register(self):
        self._update_step = 0
        for name, param in self._model.named_parameters():
            if param.stop_gradient is False:
                self._shadow[name] = param.numpy().copy()

 
    def update(self):
        for name, param in self._model.named_parameters():
            if param.stop_gradient is False:
                assert name in self._shadow
                new_val = np.array(param.numpy().copy())
                old_val = np.array(self._shadow[name])
                decay = min(self._decay, (1+self._update_step)/(10+self._update_step)) if self._thres_steps else self._decay
                new_average = decay * old_val + (1 - decay) * new_val
                self._shadow[name] = new_average
        self._update_step += 1
        return decay

   
    def apply(self):
        for name, param in self._model.named_parameters():
            if param.stop_gradient is False:
                assert name in self._shadow
                self._backup[name] = np.array(param.numpy().copy())
                param.set_value(np.array(self._shadow[name]))


    
    def restore(self):
        for name, param in self._model.named_parameters():
            if param.stop_gradient is False:
                assert name in self._backup
                param.set_value(self._backup[name])
        self._backup = {}

```

**Comment by miemie2013** [comment]
> @miemie2013 动态图下的EMA模块近期会添加，目前请参考以下实现形式吧，在每一个mini batch训练结束后调用update()，比每个epoch后调用效果要好。
> 
> ```python
> import paddle
> import numpy as np
> 
> 
> class ExponentialMovingAverage():
>     def __init__(self, model, decay, thres_steps=True):
>         self._model = model
>         self._decay = decay
>         self._thres_steps = thres_steps
>         self._shadow = {}
>         self._backup = {}
> 
>     def register(self):
>         self._update_step = 0
>         for name, param in self._model.named_parameters():
>             if param.stop_gradient is False:
>                 self._shadow[name] = param.numpy().copy()
> 
>  
>     def update(self):
>         for name, param in self._model.named_parameters():
>             if param.stop_gradient is False:
>                 assert name in self._shadow
>                 new_val = np.array(param.numpy().copy())
>                 old_val = np.array(self._shadow[name])
>                 decay = min(self._decay, (1+self._update_step)/(10+self._update_step)) if self._thres_steps else self._decay
>                 new_average = decay * old_val + (1 - decay) * new_val
>                 self._shadow[name] = new_average
>         self._update_step += 1
>         return decay
> 
>    
>     def apply(self):
>         for name, param in self._model.named_parameters():
>             if param.stop_gradient is False:
>                 assert name in self._shadow
>                 self._backup[name] = np.array(param.numpy().copy())
>                 param.set_value(np.array(self._shadow[name]))
> 
> 
>     
>     def restore(self):
>         for name, param in self._model.named_parameters():
>             if param.stop_gradient is False:
>                 assert name in self._backup
>                 param.set_value(self._backup[name])
>         self._backup = {}
> ```

谢谢大佬指点！

**Comment by ruyijidan** [comment]
我之前是new两个模型，然后再将训练的权重更新到ema模型上去，这个也是搬运的。

```
def soft_update(target, source, decay):
    """
    Copies the parameters from source network (x) to target network (y)
    using the below update
    y = decay * source + (1 - decay) * target_param
    :param target: Target network (PaddleDynaGraphModel)
    :param source: Source network (PaddleDynaGraphModel)
    :decay: decay ratio should be super lower than 1, in range of [0,1]
    :return:
    https://paddlepaddle.org.cn/documentation/docs/zh/api_cn/fluid_cn/Variable_cn.html#set-value
    """
    target_model_map = dict(target.named_parameters())
    for param_name, source_param in source.named_parameters():
        target_param = target_model_map[param_name]
        target_param.set_value(decay * source_param +
                               (1.0 - decay) * target_param)

    # pytorch version
    # for target_param, param in zip(target.parameters(), source.parameters()):
    #     target_param.data.copy_(target_param.data * (1.0 - tau) +
    #                             param.data * tau)
```

**Comment by jerrywgz** [comment]
目前动态图下ppyolo已经实现ema，可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/engine/callbacks.py#L157 这里的实现方式
