### ISSUE TITLE
TensorRT预测问题

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleDetection#1665]
环境：
CentOS7.6
CUDA 10.0
Paddlepaddle-gpu==1.8.4.post107

在利用TensorRT推理时遇到如下错误：

> File "/home/dev/ds/modelserving/ppdet_infer.py", line 555, in load_predictor
>     predictor = fluid.core.create_paddle_predictor(config)
> paddle.fluid.core_avx.EnforceNotMet: 
> 
> --------------------------------------------
> C++ Call Stacks (More useful to developers):
> --------------------------------------------
> 0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
> 1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
> 2   paddle::framework::ir::PassRegistry::Get(std::string const&) const
> 3   paddle::inference::analysis::IRPassManager::CreatePasses(paddle::inference::analysis::Argument*, std::vector<std::string, std::allocator<std::string> > const&)
> 4   paddle::inference::analysis::IRPassManager::IRPassManager(paddle::inference::analysis::Argument*)
> 5   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
> 6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
> 7   paddle::AnalysisPredictor::OptimizeInferenceProgram()
> 8   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
> 9   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
> 10  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
> 11  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)
> 
> ----------------------
> Error Message Summary:
> ----------------------
> Error: Pass tensorrt_subgraph_pass has not been registered at (/paddle/paddle/fluid/framework/ir/pass.h:201)

在`run_mode = 'fluid'` 时预测正常，使用的是YOLOV3的增强版模型 `yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco`

请问这个可能是什么原因导致的呢？

**Comment by heavengate** [comment]
使用TensorRT预测需要Paddle编译的时候开启TensorRT，当前默认发布的pip包是不包含TensorRT的，如果需要TensorRT预测需要自己编译一下pip包
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/fromsource.html
编译的时候`cmake`命令加上`-D -DTENSORRT_ROOT=<path/to/TensorRT>`

**Comment by qingqing01** [comment]
@nihuizhidao 

默认安装Paddle的whl包，不包含TensorRT。使用TensorRT时，需要参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html#id1  这里进行下载，这里目前只有针对ubuntu14.04系统，  ubuntu14.04_cuda10.1_cudnn7.6_avx_mkl_trt6  或者自行编译。
