### ISSUE TITLE
jetson nano 使用CPU推理,获得结果正确,使用GPU却无法得到正常结果.

### ISSUE THREAD

**Issue by edimetia3d** [PaddlePaddle/PaddleDetection#1671]
转发自: https://github.com/PaddlePaddle/Paddle-Lite/issues/4680

设备:jetson nano
cuda:10.2.89
opencv 4.1.1
trt:7.1.3.0
cudnn:8.0.0.180
模型:PPYOLO
设置predictor代码:

             def create_(model, params): 

                      config = AnalysisConfig(model, params)  # 解析模型

                      config.enable_use_gpu(memory_pool_init_size_mb=100, device_id=0)

                      config.switch_ir_optim(True)   # IR优化(默认开启)

                        # 开启TensorRT预测，精度为fp32，开启int8离线量化
                         #config.enable_tensorrt_engine(
                         #                            workspace_size = 1<<30,
                         #                            max_batch_size=1, 
                         #                            min_subgraph_size=5,
                         #                            precision_mode=AnalysisConfig.Precision.Float32,
                         #                            use_static=True, 
                         #                            use_calib_mode=False)
                            
                     config.switch_use_feed_fetch_ops(False) # i

                     config.enable_memory_optim()

                     config.switch_specify_input_names(True)

                     predictor = create_paddle_predictor(config)

                      return predictor
将其中config.enable_use_gpu(memory_pool_init_size_mb=100, device_id=0)注释掉,可以获得正确结果.
但加入这段代码,结果就出错.
[array([[ -1.63043427, -3.0744288 , -4.28663301, -4.71060038,
-4.1004529 , -2.99704051],
[ -4.79013348, -3.88283634, -4.2329936 , -4.66976929,
-3.81956506, -3.18711162],
[ -4.39737701, -3.8674221 , -3.91665888, -5.47638226,
-3.82651567, -3.34574342],
[ -3.95786715, -4.37374449, -3.84336948, -3.07725167,
-4.58613205, -3.87052822],
[ -4.28033543, -7.14224482, -2.49949193, -3.78695631,
-7.14322472, -6.83057261],
[ -5.40062141, -6.24964476, -5.07910442, -4.62831116,
-5.8810463 , -7.24986172],
[ -6.87119818, -5.8572011 , -5.7911129 , -6.06267929,
-7.2432847 , -4.85457182],
[ -7.77882767, -7.88278437, -6.246068 , -6.76907158,
-6.85439444, -5.97704554],
[ -5.84663725, -5.77969265, -5.94738483, -5.8084774 ,
-1.50877953, -3.3424058 ],
[ -5.79145527, -6.69816017, -5.13526678, -6.32641315,
-6.5106802 , -4.98755836],
[ -5.40557051, -6.13990927, -5.24821615, -6.272645 ,
-7.73789597, -6.78180218],
[ -6.98717594, -5.49334431, -4.34010792, -5.07190943,
-5.52531338, -7.25481033],
[ -6.00555372, -4.93757534, -5.75581455, -5.84062815,
-6.34452677, -8.76577282],
[ -6.57651567, -6.87161303, -8.13422203, -8.348629 ,
-8.49406528, -8.31268787],
[ -7.52561903, -8.22769165, -8.15839291, -7.43507338,
-6.42833138, -7.78585196],
[ -8.11678791, -8.58690357, -8.02465534, -6.70363379,
-7.26227188, -7.00323105],
[ -7.6821146 , -7.30944586, -7.58168268, -6.50735044,
-7.08927917, -7.31332445],
[ -7.85414076, -4.88075495, -3.03333068, -6.42556047,
-7.62548065, -5.07736826],
[ -5.06301832, -6.67656898, -6.07352114, -6.91661739,
-7.56441927, -7.02177 ],
[ -6.67481756, -5.93885279, -5.84966183, -6.03695107,
-7.07688427, -6.04083729],
[ -5.65774488, -5.31725979, -4.39572573, -7.11769342,
-6.26221371, -4.70407009],
[ -7.51357603, -6.69953823, -6.48236609, -8.52565002,
-5.4656105 , -6.8910346 ],
[ -7.43745899, -7.39838791, -8.89735031, -7.9737649 ,
-7.36060429, -6.6881299 ],
[ -7.54480267, -8.32841396, -7.90175295, -7.87509298,
-6.90504885, -6.72156096],
[ -8.16718102, -6.7788825 , -7.1475153 , -8.16426754,
-7.81302595, -7.19576263],
[ -6.6133275 , -7.16348124, -8.18309879, -8.63716412,
-8.03920269, -6.21641636],
[ -2.36793923, -4.75107622, -7.67394733, -6.69684076,
-6.56558466, -8.40773582],
[ -7.26329279, -6.19085217, -7.9038806 , -7.28407383,
-5.97027588, -7.62232685],
[ -6.54433823, -8.69188976, -7.85568714, -7.46014309,
-5.76311302, -6.45889282],
[ -6.42501068, -8.7602129 , -7.97540045, -7.87911654,
-8.26405621, -7.27478933],
[ -7.55706978, -10.47489357, -7.46466541, -7.95408201,
-8.05955696, -9.05757809],
[ -8.32738018, -7.15997076, -8.98676109, -8.25866699,
-8.38563728, -8.28671741],
[ -8.47560215, -8.7546339 , -9.32433128, -7.91763163,
-8.32816505, -6.70918131],
[ -8.39279079, -8.61967373, -7.80093908, -7.58073092,
-6.90460587, -6.72086525],
[ -8.4329586 , -6.84736013, -7.90739775, -6.21071339,
-3.05865216, -7.27711248],
[ -8.32087612, -5.92885494, -7.85500669, -8.27669239,
-6.75668192, -7.36937571],
[ -7.46266747, -8.73140335, -7.18398142, -6.93823767,
-8.58938217, -9.1927557 ],
[-10.39824772, -8.79815674, -6.16387177, -7.23146248,
-7.41769552, -7.51232338],
[ -8.2676096 , -10.14317894, -10.86148643, -8.27086449,
-5.78243876, -10.26306152],
[ -5.35846424, -6.31164885, -6.94629765, -6.45891619,
-6.68801975, -6.65988588],
[ -6.5079236 , -7.53979301, -8.19980049, -7.90021372,
-7.65127754, -7.749578 ],
[ -9.05210018, -9.13391209, -8.21422672, -5.1073823 ,
-7.34081841, -7.45686722],
[ -6.93285894, -6.04899406, -6.06681538, -7.58833599,
-8.65594959, -7.16542768],
[ -5.80030155, -5.73282576, -1.22074461, -3.06383729,
-7.29622698, -8.04118824],
[ -8.11879253, -8.36537266, -6.65891743, -6.95407486,
-7.85741377, -8.11068821],
[ -9.1700182 , -8.55413628, -11.8705883 , -10.82264137,
-7.57174587, -6.70104361],
[ -5.71740866, -5.86036682, -6.56268215, -6.66196966,
-8.34544659, -8.49382019],
[ -7.1887908 , -7.17407465, -6.52292442, -9.21665764,
-7.4755373 , -7.70338202],
[ -9.77023888, -8.71272945, -6.29508495, -6.056077 ,
-7.66084337, -7.88191366],
[ -7.56117868, -6.84183598, -7.35162306, -8.40217495,
-9.59517384, -10.17312431],
[ -4.97934628, -5.34534454, -6.83217287, -7.38092709,
-7.05114174, -4.8691411 ],
[ -5.09307718, -6.52436495, -7.28420877, -5.41510201,
-5.38210535, -6.0263586 ],
[ -2.69841027, -5.52916145, -5.66091251, -5.28834534,
-7.37212706, -5.98938894],
[ -6.88273239, -7.82063437, -6.64130974, -6.80175829,
-6.36529589, -6.43385649],
[ -9.93610191, -9.96025848, -7.09129524, -7.12996817,
-6.96952152, -5.88449621],
[ -6.16396093, -6.02804756, -8.01624775, -8.09607887,
-6.97598791, -7.04356337],
[ -6.45812368, -7.39569092, -4.71323013, -6.76392365,
-7.14754581, -5.5717597 ],
[ -4.65412855, -5.29600906, -5.66666174, -6.62485504,
-7.67697859, -6.065938 ],
[ -5.27091169, -5.37104273, -5.9752202 , -5.62456274,
-3.64977145, -3.60556984],
[ -6.25487852, -4.88454008, -6.41235256, -5.15787745,
-5.56099892, -6.83935118],
[ -7.28861713, -6.42121983, -5.48826838, -6.40822506,
-0.73702419, -4.88643694],
[ -7.64941168, -7.82267618, -5.81451559, -5.82097673,
-6.17628241, -6.73605013],
[ -7.68667412, -7.31204462, -6.9039216 , -6.45543289,
-6.22700024, -5.32711267],
[ -5.24518204, -5.91584444, -6.03827286, -6.0908742 ,
-5.17556143, -5.31240034],
[ -6.7658782 , -6.97585392, -6.07373047, -6.70100498,
-7.62571049, -9.66361141],
[ -3.76170492, -4.95020533, -5.65309381, -6.65228605,
-3.34711003, -5.64666176],
[ -7.4204607 , -7.04593039, -6.56319857, -5.34201813,
-4.74734545, -5.30519104],
[ -5.64807987, -4.478971 , -4.92102098, -4.86726856,
-5.23807573, -6.08432198],
[ -4.83537769, -6.40741587, -5.36205626, -5.3698411 ,
-7.59917927, -5.58144379],
[ -6.57064533, -6.60967016, -1.4256537 , -4.67288446,
-6.55506086, -5.36282778],
[ -6.09708166, -6.9826088 , -7.04357243, -8.06102276,
-6.50307083, -6.9512701 ],
[ -6.68573332, -5.34667683, -6.43559647, -3.45535469,
-3.90702629, -5.84244204],
[ -5.97469091, -6.08933401, -6.33984327, -5.64053154,
-6.48646927, -6.63886404],
[ -6.26548576, -6.41477585, -6.60274839, -7.53726149,
-4.48729849, -4.92735577],
[ -4.22829294, -6.65296841, -5.80270386, -7.51827049,
-6.9274087 , -6.71021938],
[ -7.11719799, -6.23283768, -5.76521111, -5.48465061,
-5.01233053, -4.86229658],
[ -5.62460852, -5.15575981, -5.09085464, -5.54945993,
-6.36552429, -5.51709795],
[ -3.87644863, -4.37390137, -5.76722002, -5.59497976,
-4.80594683, -6.06980228],
[ -0.42962822, -4.07001543, -6.75137329, -4.58567953,
-5.46678209, -6.56742144],
[ -5.25005102, -5.93379736, -6.68290663, -7.07886076,
-3.93457985, -3.06017613],
[ -5.76476288, -5.19848633, -4.88805914, -7.05230379,
-6.29982471, -4.19192696],
[ -4.65876627, -4.6370163 , -5.6500206 , -5.84461117,
-6.08191061, -6.15114689],
[ -7.74420738, -9.82957554, -6.12923765, -6.39157963,
-7.63268042, -7.09611416],
[ -4.59993505, -7.68660879, -8.22811031, -7.42614937,
-7.29163408, -7.70169401],
[ -6.33089113, -7.00554276, -6.71176195, -7.14174366,
-6.14421177, -7.34445429],
[ -7.2369771 , -8.23961544, -7.33109903, -5.99234056,
-6.85985804, -6.9357214 ],
[ -6.80647087, -7.28453112, -6.80578423, -5.12966394,
-2.28464055, -4.86023808],
[ -6.90844536, -6.22558975, -6.15659714, -6.5420599 ,
-6.88994789, -8.25266743],
[ -7.72232008, -7.41123056, -6.69925022, -7.07544327,
-7.38541842, -6.77722406],
[ -6.80234528, -7.80681515, -9.13970661, -6.83084726,
-6.60920954, -5.39624882],
[ -4.99487543, -6.32429266, -6.72155476, -5.62199163,
-7.58542442, -7.99610949],
[ -7.00531912, -5.5574584 , -9.51231003, -6.90858269,
-6.600986 , -9.31153584],
[ -9.58336926, -8.46331882, -8.60241985, -7.60906887,
-7.40451241, -8.55171871],
[ -8.29571438, -8.17353916, -8.47504902, -7.41751003,
-6.7857399 , -7.00493717],
[ -7.29284763, -5.57825565, -5.80162334, -5.88837957,
-6.89937592, -7.22925758],
[ -6.08708763, -4.50695658, -1.32158935, -5.175107 ,
-7.96403933, -6.40470839],
[ -5.86457777, -7.23867226, -7.55784225, -8.05652237,
-9.29115582, -9.25224018],
[ -6.70065594, -7.6174283 , -7.82019949, -8.36585999,
-9.41876411, -8.39664745],
[ -7.63751936, -6.77315998, -6.993186 , -6.92551661,
-7.11629152, -7.74674892],
[ -9.080369 , -7.70216703, -9.78130722, -8.61892223,
-5.89099073, -4.87764692]], dtype=float32)]
以上是错误结果.
下面是注释掉后得到的结果

[array([[ 0.00000000e+00, 9.58394706e-01, 2.19225159e+02,
1.68318954e+02, 2.42677002e+02, 2.84810760e+02],
[ 1.00000000e+00, 9.06657815e-01, 2.24320068e+02,
1.23105614e+02, 2.49125793e+02, 2.55051910e+02],
[ 0.00000000e+00, 1.18093573e-01, 2.18439240e+02,
1.70467239e+02, 2.41556549e+02, 2.76585327e+02],
[ 0.00000000e+00, 7.41712078e-02, 2.24235855e+02,
1.21075081e+02, 2.50648239e+02, 2.56485931e+02],
[ 1.00000000e+00, 6.90196976e-02, 2.23370499e+02,
1.26582146e+02, 2.47621719e+02, 2.58748901e+02],
[ 0.00000000e+00, 6.46925867e-02, 2.18405121e+02,
1.68198090e+02, 2.44868103e+02, 2.91758026e+02],
[ 1.00000000e+00, 5.95510937e-02, 2.27292114e+02,
1.24899498e+02, 2.53302551e+02, 2.51766144e+02],
[ 1.00000000e+00, 5.25811054e-02, 2.24235855e+02,
1.21075081e+02, 2.50648239e+02, 2.56485931e+02],
[ 1.00000000e+00, 3.05438954e-02, 2.19225159e+02,
1.68318954e+02, 2.42677002e+02, 2.84810760e+02],
[ 0.00000000e+00, 2.31316015e-02, 2.07157669e+02,
1.71623947e+02, 2.17279068e+02, 2.39087997e+02],
[ 0.00000000e+00, 2.17541717e-02, 1.91173615e+02,
1.65746323e+02, 2.70337830e+02, 2.02156570e+02],
[ 1.00000000e+00, 1.93243586e-02, 1.91173615e+02,
1.65746323e+02, 2.70337830e+02, 2.02156570e+02],
[ 1.00000000e+00, 1.93111971e-02, 2.24180618e+02,
1.25466728e+02, 2.49173721e+02, 2.63774200e+02],
[ 1.00000000e+00, 1.81121249e-02, 2.27408493e+02,
1.26308357e+02, 2.54591232e+02, 2.61732941e+02],
[ 0.00000000e+00, 1.73063166e-02, 1.75141571e+02,
2.09608459e+02, 2.86063568e+02, 2.49058746e+02],
[ 1.00000000e+00, 1.62236951e-02, 2.26817749e+02,
1.24212349e+02, 2.53328918e+02, 2.53745453e+02],
[ 1.00000000e+00, 1.58035494e-02, 1.75141571e+02,
2.09608459e+02, 2.86063568e+02, 2.49058746e+02],
[ 0.00000000e+00, 1.13268569e-02, 2.12673859e+02,
1.71277390e+02, 2.35332336e+02, 2.84062988e+02]], dtype=float32)]

**Comment by watcheras** [comment]
使用的ppyolo模型

**Comment by liuhuiCNN** [comment]
（1）麻烦提供下paddle的版本号。
（2）jetson nano 的预测请您参考文档 https://github.com/PaddlePaddle/PaddleDetection/blob/master/deploy/cpp/docs/TX2_build.md。您是参考Paddle-Lite中哪个文档预测的呢？

**Comment by PiyalGeorge** [comment]
Hi @liuhuiCNN , 

I have some doubts regarding PP-Yolo deployment, Kindly help me on this: 
- Is it possible to deploy pp-yolo in Jetson Nano or Jetson Xavier-NX , If yes how much is the FPS for these cases

**Comment by LLeeSG** [comment]
> Hi @liuhuiCNN ,
> 
> I have some doubts regarding PP-Yolo deployment, Kindly help me on this:
> 
> * Is it possible to deploy pp-yolo in Jetson Nano or Jetson Xavier-NX , If yes how much is the FPS for these cases

Deployed PPYOLO in Jetson TX2 , FPS is about 1.7fps without TRT, and will soon deploy it in AGX Xavier...

**Comment by LLeeSG** [comment]
> config.enable_use_gpu

注释掉config.enable_use_gpu相当于使用CPU进行预测吧？这没有从根本上解决问题。怀疑是TRT编译时没整对。。

**Comment by GZHUZhao** [comment]
> 转发自: [PaddlePaddle/Paddle-Lite#4680](https://github.com/PaddlePaddle/Paddle-Lite/issues/4680)
> 
> 设备:jetson nano
> cuda:10.2.89
> opencv 4.1.1
> trt:7.1.3.0
> cudnn:8.0.0.180
> 模型:PPYOLO
> 设置predictor代码:
> 
> ```
>          def create_(model, params): 
> 
>                   config = AnalysisConfig(model, params)  # 解析模型
> 
>                   config.enable_use_gpu(memory_pool_init_size_mb=100, device_id=0)
> 
>                   config.switch_ir_optim(True)   # IR优化(默认开启)
> 
>                     # 开启TensorRT预测，精度为fp32，开启int8离线量化
>                      #config.enable_tensorrt_engine(
>                      #                            workspace_size = 1<<30,
>                      #                            max_batch_size=1, 
>                      #                            min_subgraph_size=5,
>                      #                            precision_mode=AnalysisConfig.Precision.Float32,
>                      #                            use_static=True, 
>                      #                            use_calib_mode=False)
>                         
>                  config.switch_use_feed_fetch_ops(False) # i
> 
>                  config.enable_memory_optim()
> 
>                  config.switch_specify_input_names(True)
> 
>                  predictor = create_paddle_predictor(config)
> 
>                   return predictor
> ```
> 
> 将其中config.enable_use_gpu(memory_pool_init_size_mb=100, device_id=0)注释掉,可以获得正确结果.
> 但加入这段代码,结果就出错.
> [array([[ -1.63043427, -3.0744288 , -4.28663301, -4.71060038,
> -4.1004529 , -2.99704051],
> [ -4.79013348, -3.88283634, -4.2329936 , -4.66976929,
> -3.81956506, -3.18711162],
> [ -4.39737701, -3.8674221 , -3.91665888, -5.47638226,
> -3.82651567, -3.34574342],
> [ -3.95786715, -4.37374449, -3.84336948, -3.07725167,
> -4.58613205, -3.87052822],
> [ -4.28033543, -7.14224482, -2.49949193, -3.78695631,
> -7.14322472, -6.83057261],
> [ -5.40062141, -6.24964476, -5.07910442, -4.62831116,
> -5.8810463 , -7.24986172],
> [ -6.87119818, -5.8572011 , -5.7911129 , -6.06267929,
> -7.2432847 , -4.85457182],
> [ -7.77882767, -7.88278437, -6.246068 , -6.76907158,
> -6.85439444, -5.97704554],
> [ -5.84663725, -5.77969265, -5.94738483, -5.8084774 ,
> -1.50877953, -3.3424058 ],
> [ -5.79145527, -6.69816017, -5.13526678, -6.32641315,
> -6.5106802 , -4.98755836],
> [ -5.40557051, -6.13990927, -5.24821615, -6.272645 ,
> -7.73789597, -6.78180218],
> [ -6.98717594, -5.49334431, -4.34010792, -5.07190943,
> -5.52531338, -7.25481033],
> [ -6.00555372, -4.93757534, -5.75581455, -5.84062815,
> -6.34452677, -8.76577282],
> [ -6.57651567, -6.87161303, -8.13422203, -8.348629 ,
> -8.49406528, -8.31268787],
> [ -7.52561903, -8.22769165, -8.15839291, -7.43507338,
> -6.42833138, -7.78585196],
> [ -8.11678791, -8.58690357, -8.02465534, -6.70363379,
> -7.26227188, -7.00323105],
> [ -7.6821146 , -7.30944586, -7.58168268, -6.50735044,
> -7.08927917, -7.31332445],
> [ -7.85414076, -4.88075495, -3.03333068, -6.42556047,
> -7.62548065, -5.07736826],
> [ -5.06301832, -6.67656898, -6.07352114, -6.91661739,
> -7.56441927, -7.02177 ],
> [ -6.67481756, -5.93885279, -5.84966183, -6.03695107,
> -7.07688427, -6.04083729],
> [ -5.65774488, -5.31725979, -4.39572573, -7.11769342,
> -6.26221371, -4.70407009],
> [ -7.51357603, -6.69953823, -6.48236609, -8.52565002,
> -5.4656105 , -6.8910346 ],
> [ -7.43745899, -7.39838791, -8.89735031, -7.9737649 ,
> -7.36060429, -6.6881299 ],
> [ -7.54480267, -8.32841396, -7.90175295, -7.87509298,
> -6.90504885, -6.72156096],
> [ -8.16718102, -6.7788825 , -7.1475153 , -8.16426754,
> -7.81302595, -7.19576263],
> [ -6.6133275 , -7.16348124, -8.18309879, -8.63716412,
> -8.03920269, -6.21641636],
> [ -2.36793923, -4.75107622, -7.67394733, -6.69684076,
> -6.56558466, -8.40773582],
> [ -7.26329279, -6.19085217, -7.9038806 , -7.28407383,
> -5.97027588, -7.62232685],
> [ -6.54433823, -8.69188976, -7.85568714, -7.46014309,
> -5.76311302, -6.45889282],
> [ -6.42501068, -8.7602129 , -7.97540045, -7.87911654,
> -8.26405621, -7.27478933],
> [ -7.55706978, -10.47489357, -7.46466541, -7.95408201,
> -8.05955696, -9.05757809],
> [ -8.32738018, -7.15997076, -8.98676109, -8.25866699,
> -8.38563728, -8.28671741],
> [ -8.47560215, -8.7546339 , -9.32433128, -7.91763163,
> -8.32816505, -6.70918131],
> [ -8.39279079, -8.61967373, -7.80093908, -7.58073092,
> -6.90460587, -6.72086525],
> [ -8.4329586 , -6.84736013, -7.90739775, -6.21071339,
> -3.05865216, -7.27711248],
> [ -8.32087612, -5.92885494, -7.85500669, -8.27669239,
> -6.75668192, -7.36937571],
> [ -7.46266747, -8.73140335, -7.18398142, -6.93823767,
> -8.58938217, -9.1927557 ],
> [-10.39824772, -8.79815674, -6.16387177, -7.23146248,
> -7.41769552, -7.51232338],
> [ -8.2676096 , -10.14317894, -10.86148643, -8.27086449,
> -5.78243876, -10.26306152],
> [ -5.35846424, -6.31164885, -6.94629765, -6.45891619,
> -6.68801975, -6.65988588],
> [ -6.5079236 , -7.53979301, -8.19980049, -7.90021372,
> -7.65127754, -7.749578 ],
> [ -9.05210018, -9.13391209, -8.21422672, -5.1073823 ,
> -7.34081841, -7.45686722],
> [ -6.93285894, -6.04899406, -6.06681538, -7.58833599,
> -8.65594959, -7.16542768],
> [ -5.80030155, -5.73282576, -1.22074461, -3.06383729,
> -7.29622698, -8.04118824],
> [ -8.11879253, -8.36537266, -6.65891743, -6.95407486,
> -7.85741377, -8.11068821],
> [ -9.1700182 , -8.55413628, -11.8705883 , -10.82264137,
> -7.57174587, -6.70104361],
> [ -5.71740866, -5.86036682, -6.56268215, -6.66196966,
> -8.34544659, -8.49382019],
> [ -7.1887908 , -7.17407465, -6.52292442, -9.21665764,
> -7.4755373 , -7.70338202],
> [ -9.77023888, -8.71272945, -6.29508495, -6.056077 ,
> -7.66084337, -7.88191366],
> [ -7.56117868, -6.84183598, -7.35162306, -8.40217495,
> -9.59517384, -10.17312431],
> [ -4.97934628, -5.34534454, -6.83217287, -7.38092709,
> -7.05114174, -4.8691411 ],
> [ -5.09307718, -6.52436495, -7.28420877, -5.41510201,
> -5.38210535, -6.0263586 ],
> [ -2.69841027, -5.52916145, -5.66091251, -5.28834534,
> -7.37212706, -5.98938894],
> [ -6.88273239, -7.82063437, -6.64130974, -6.80175829,
> -6.36529589, -6.43385649],
> [ -9.93610191, -9.96025848, -7.09129524, -7.12996817,
> -6.96952152, -5.88449621],
> [ -6.16396093, -6.02804756, -8.01624775, -8.09607887,
> -6.97598791, -7.04356337],
> [ -6.45812368, -7.39569092, -4.71323013, -6.76392365,
> -7.14754581, -5.5717597 ],
> [ -4.65412855, -5.29600906, -5.66666174, -6.62485504,
> -7.67697859, -6.065938 ],
> [ -5.27091169, -5.37104273, -5.9752202 , -5.62456274,
> -3.64977145, -3.60556984],
> [ -6.25487852, -4.88454008, -6.41235256, -5.15787745,
> -5.56099892, -6.83935118],
> [ -7.28861713, -6.42121983, -5.48826838, -6.40822506,
> -0.73702419, -4.88643694],
> [ -7.64941168, -7.82267618, -5.81451559, -5.82097673,
> -6.17628241, -6.73605013],
> [ -7.68667412, -7.31204462, -6.9039216 , -6.45543289,
> -6.22700024, -5.32711267],
> [ -5.24518204, -5.91584444, -6.03827286, -6.0908742 ,
> -5.17556143, -5.31240034],
> [ -6.7658782 , -6.97585392, -6.07373047, -6.70100498,
> -7.62571049, -9.66361141],
> [ -3.76170492, -4.95020533, -5.65309381, -6.65228605,
> -3.34711003, -5.64666176],
> [ -7.4204607 , -7.04593039, -6.56319857, -5.34201813,
> -4.74734545, -5.30519104],
> [ -5.64807987, -4.478971 , -4.92102098, -4.86726856,
> -5.23807573, -6.08432198],
> [ -4.83537769, -6.40741587, -5.36205626, -5.3698411 ,
> -7.59917927, -5.58144379],
> [ -6.57064533, -6.60967016, -1.4256537 , -4.67288446,
> -6.55506086, -5.36282778],
> [ -6.09708166, -6.9826088 , -7.04357243, -8.06102276,
> -6.50307083, -6.9512701 ],
> [ -6.68573332, -5.34667683, -6.43559647, -3.45535469,
> -3.90702629, -5.84244204],
> [ -5.97469091, -6.08933401, -6.33984327, -5.64053154,
> -6.48646927, -6.63886404],
> [ -6.26548576, -6.41477585, -6.60274839, -7.53726149,
> -4.48729849, -4.92735577],
> [ -4.22829294, -6.65296841, -5.80270386, -7.51827049,
> -6.9274087 , -6.71021938],
> [ -7.11719799, -6.23283768, -5.76521111, -5.48465061,
> -5.01233053, -4.86229658],
> [ -5.62460852, -5.15575981, -5.09085464, -5.54945993,
> -6.36552429, -5.51709795],
> [ -3.87644863, -4.37390137, -5.76722002, -5.59497976,
> -4.80594683, -6.06980228],
> [ -0.42962822, -4.07001543, -6.75137329, -4.58567953,
> -5.46678209, -6.56742144],
> [ -5.25005102, -5.93379736, -6.68290663, -7.07886076,
> -3.93457985, -3.06017613],
> [ -5.76476288, -5.19848633, -4.88805914, -7.05230379,
> -6.29982471, -4.19192696],
> [ -4.65876627, -4.6370163 , -5.6500206 , -5.84461117,
> -6.08191061, -6.15114689],
> [ -7.74420738, -9.82957554, -6.12923765, -6.39157963,
> -7.63268042, -7.09611416],
> [ -4.59993505, -7.68660879, -8.22811031, -7.42614937,
> -7.29163408, -7.70169401],
> [ -6.33089113, -7.00554276, -6.71176195, -7.14174366,
> -6.14421177, -7.34445429],
> [ -7.2369771 , -8.23961544, -7.33109903, -5.99234056,
> -6.85985804, -6.9357214 ],
> [ -6.80647087, -7.28453112, -6.80578423, -5.12966394,
> -2.28464055, -4.86023808],
> [ -6.90844536, -6.22558975, -6.15659714, -6.5420599 ,
> -6.88994789, -8.25266743],
> [ -7.72232008, -7.41123056, -6.69925022, -7.07544327,
> -7.38541842, -6.77722406],
> [ -6.80234528, -7.80681515, -9.13970661, -6.83084726,
> -6.60920954, -5.39624882],
> [ -4.99487543, -6.32429266, -6.72155476, -5.62199163,
> -7.58542442, -7.99610949],
> [ -7.00531912, -5.5574584 , -9.51231003, -6.90858269,
> -6.600986 , -9.31153584],
> [ -9.58336926, -8.46331882, -8.60241985, -7.60906887,
> -7.40451241, -8.55171871],
> [ -8.29571438, -8.17353916, -8.47504902, -7.41751003,
> -6.7857399 , -7.00493717],
> [ -7.29284763, -5.57825565, -5.80162334, -5.88837957,
> -6.89937592, -7.22925758],
> [ -6.08708763, -4.50695658, -1.32158935, -5.175107 ,
> -7.96403933, -6.40470839],
> [ -5.86457777, -7.23867226, -7.55784225, -8.05652237,
> -9.29115582, -9.25224018],
> [ -6.70065594, -7.6174283 , -7.82019949, -8.36585999,
> -9.41876411, -8.39664745],
> [ -7.63751936, -6.77315998, -6.993186 , -6.92551661,
> -7.11629152, -7.74674892],
> [ -9.080369 , -7.70216703, -9.78130722, -8.61892223,
> -5.89099073, -4.87764692]], dtype=float32)]
> 以上是错误结果.
> 下面是注释掉后得到的结果
> 
> [array([[ 0.00000000e+00, 9.58394706e-01, 2.19225159e+02,
> 1.68318954e+02, 2.42677002e+02, 2.84810760e+02],
> [ 1.00000000e+00, 9.06657815e-01, 2.24320068e+02,
> 1.23105614e+02, 2.49125793e+02, 2.55051910e+02],
> [ 0.00000000e+00, 1.18093573e-01, 2.18439240e+02,
> 1.70467239e+02, 2.41556549e+02, 2.76585327e+02],
> [ 0.00000000e+00, 7.41712078e-02, 2.24235855e+02,
> 1.21075081e+02, 2.50648239e+02, 2.56485931e+02],
> [ 1.00000000e+00, 6.90196976e-02, 2.23370499e+02,
> 1.26582146e+02, 2.47621719e+02, 2.58748901e+02],
> [ 0.00000000e+00, 6.46925867e-02, 2.18405121e+02,
> 1.68198090e+02, 2.44868103e+02, 2.91758026e+02],
> [ 1.00000000e+00, 5.95510937e-02, 2.27292114e+02,
> 1.24899498e+02, 2.53302551e+02, 2.51766144e+02],
> [ 1.00000000e+00, 5.25811054e-02, 2.24235855e+02,
> 1.21075081e+02, 2.50648239e+02, 2.56485931e+02],
> [ 1.00000000e+00, 3.05438954e-02, 2.19225159e+02,
> 1.68318954e+02, 2.42677002e+02, 2.84810760e+02],
> [ 0.00000000e+00, 2.31316015e-02, 2.07157669e+02,
> 1.71623947e+02, 2.17279068e+02, 2.39087997e+02],
> [ 0.00000000e+00, 2.17541717e-02, 1.91173615e+02,
> 1.65746323e+02, 2.70337830e+02, 2.02156570e+02],
> [ 1.00000000e+00, 1.93243586e-02, 1.91173615e+02,
> 1.65746323e+02, 2.70337830e+02, 2.02156570e+02],
> [ 1.00000000e+00, 1.93111971e-02, 2.24180618e+02,
> 1.25466728e+02, 2.49173721e+02, 2.63774200e+02],
> [ 1.00000000e+00, 1.81121249e-02, 2.27408493e+02,
> 1.26308357e+02, 2.54591232e+02, 2.61732941e+02],
> [ 0.00000000e+00, 1.73063166e-02, 1.75141571e+02,
> 2.09608459e+02, 2.86063568e+02, 2.49058746e+02],
> [ 1.00000000e+00, 1.62236951e-02, 2.26817749e+02,
> 1.24212349e+02, 2.53328918e+02, 2.53745453e+02],
> [ 1.00000000e+00, 1.58035494e-02, 1.75141571e+02,
> 2.09608459e+02, 2.86063568e+02, 2.49058746e+02],
> [ 0.00000000e+00, 1.13268569e-02, 2.12673859e+02,
> 1.71277390e+02, 2.35332336e+02, 2.84062988e+02]], dtype=float32)]

你好，请问解决了吗？
我的jetson nano使用deploy/python/infer.py 也是cpu行，gpu不行。
如果解决了，可以分享一下方法吗？感谢

**Comment by GZHUZhao** [comment]
@liuhuiCNN 
https://github.com/PaddlePaddle/PaddleDetection/issues/2293
我的也是部署的时候gpu不行，cpu可以，paddlepaddle2.0, paddledetection 2.0rc，能帮我看一下吗

**Comment by DragonGongY** [comment]
遇到了同样的问题，请问有人解决这个问题了吗

**Comment by DragonGongY** [comment]
该问题有人解决了吗？

**Comment by QQ39272490** [comment]
我也是碰上这问题了
