### ISSUE TITLE
KeyError:"orange"

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/PaddleDetection#1672]
![image](https://user-images.githubusercontent.com/57654726/98432767-93e46b80-20fc-11eb-8b2b-c91216691905.png)
在PaddleDection0.4中尝试运行水果训练出现错误，但是在之前0.3版主没有发送异常。

**Comment by dhao-island** [comment]
您好，请问您这个问题怎么解决，我也是训练自己的数据集出现一样的问题。
