### ISSUE TITLE
yolov3_darknet 预测结果重影

### ISSUE THREAD

**Issue by baiwei-yndx** [PaddlePaddle/PaddleDetection#1673]
![b4334cc6bc9a7efd68069fc5de13f3f](https://user-images.githubusercontent.com/55337927/98435858-766dcc80-2111-11eb-8531-4973a68e03c4.png)
环境：aistudio+win10+cuda10.0
模型：yolov3_darknet
数据集：coco格式
配置文件修改：max_iters: 3000，    milestones: - 2000 - 2700，num_classes=1 ,   reader.yml路径修改

问题：为什么预测结果框周围存在浅紫色重影框？？？？？？？（图像放大后可看到）

**Comment by qingqing01** [comment]
@baiwei-yndx  请问使用那个脚本进行预测？可以打印看下输出有几个框？看下是否调整输出score的过滤阈值 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/python/infer.py#L657

**Comment by heavengate** [comment]
你好，能给一下预测结果原图么，我们确认下

**Comment by baiwei-yndx** [comment]
> 你好，能给一下预测结果原图么，我们确认下
> 看着像是显示屏或者是预览软件的显示问题，预测结果里面应该是不包含那个浅紫色重影的吧，可以打印一下预测结果看下
原图：
![C_1](https://user-images.githubusercontent.com/55337927/98494620-63294100-2278-11eb-87ff-8546fbd93a22.jpg)
（有的说是jpg格式问题？？？）
打印预览结果还是有

**Comment by baiwei-yndx** [comment]
> @ baiwei-yndx请问 使用那个脚本进行预测？可以打印看下输出有几个框？看下是否调整输出score的过滤阈值[https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/ python / infer.py＃L657](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/python/infer.py#L657)
[my_yolo3_darknet.txt](https://github.com/PaddlePaddle/PaddleDetection/files/5507844/my_yolo3_darknet.txt)
[my_yolo3_reader.txt](https://github.com/PaddlePaddle/PaddleDetection/files/5507845/my_yolo3_reader.txt)





> @ baiwei-yndx请问 使用那个脚本进行预测？可以打印看下输出有几个框？看下是否调整输出score的过滤阈值[https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/ python / infer.py＃L657](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/python/infer.py#L657)

**Comment by heavengate** [comment]
看你配置的`num_classes=1` 预测结果里不同类别是用不同颜色标注的，现在只有一类，从预测图里看是黄色框，程序应该不会再画紫色框的，而且那个紫色框的颜色看着也不像是程序画出来的，可以在这里把预测框print出来看下
https://github.com/PaddlePaddle/PaddleDetection/blob/e74203cfa70c8fa5d1bc7bde68345f0bc8d7d16e/ppdet/utils/visualizer.py#L98

**Comment by baiwei-yndx** [comment]
> 看你配置的`num_classes=1` 预测结果里不同类别是用不同颜色标注的，现在只有一类，从预测图里看是黄色框，程序应该不会再画紫色框的，而且那个紫色框的颜色看着也不像是程序画出来的，可以在这里把预测框print出来看下
> https://github.com/PaddlePaddle/PaddleDetection/blob/e74203cfa70c8fa5d1bc7bde68345f0bc8d7d16e/ppdet/utils/visualizer.py#L98

刚接触，不知怎么写把预测框print出来，还有就是同一张图片每次预测结果框颜色都是不定的（例如：第一次预测框是黄色，在点一次预测框变成绿色）

**Comment by heavengate** [comment]
> > 看你配置的`num_classes=1` 预测结果里不同类别是用不同颜色标注的，现在只有一类，从预测图里看是黄色框，程序应该不会再画紫色框的，而且那个紫色框的颜色看着也不像是程序画出来的，可以在这里把预测框print出来看下
> > https://github.com/PaddlePaddle/PaddleDetection/blob/e74203cfa70c8fa5d1bc7bde68345f0bc8d7d16e/ppdet/utils/visualizer.py#L98
> 
> 刚接触，不知怎么写把预测框print出来，还有就是同一张图片每次预测结果框颜色都是不定的（例如：第一次预测框是黄色，在点一次预测框变成绿色）

每次预测颜色是随机的，但是单次预测内颜色是固定的，在上面那行代码下面加下面这行就可以打印
```
print(xmin, ymin, xmax, ymax, catid2name[catid])
```

**Comment by baiwei-yndx** [comment]
> > > 看你配置的`num_classes=1` 预测结果里不同类别是用不同颜色标注的，现在只有一类，从预测图里看是黄色框，程序应该不会再画紫色框的，而且那个紫色框的颜色看着也不像是程序画出来的，可以在这里把预测框print出来看下
> > > https://github.com/PaddlePaddle/PaddleDetection/blob/e74203cfa70c8fa5d1bc7bde68345f0bc8d7d16e/ppdet/utils/visualizer.py#L98
> > 
> > 
> > 刚接触，不知怎么写把预测框print出来，还有就是同一张图片每次预测结果框颜色都是不定的（例如：第一次预测框是黄色，在点一次预测框变成绿色）
> 
> 每次预测颜色是随机的，但是单次预测内颜色是固定的，在上面那行代码下面加下面这行就可以打印
> 
> ```
> print(xmin, ymin, xmax, ymax, catid2name[catid])
> ```

![image](https://user-images.githubusercontent.com/55337927/98497326-9a9aec00-227e-11eb-8e45-017af5cce75a.png)
![after_print](https://user-images.githubusercontent.com/55337927/98497403-d930a680-227e-11eb-8f66-b0521f456783.jpg)
打印出来的预测框，，但是预测结果图放大还是存在重影

**Comment by heavengate** [comment]
打印出来的预测框只有两个，就是图中两个红框，重影因该是显示问题

**Comment by baiwei-yndx** [comment]
> 打印出来的预测框只有两个，就是图中两个红框，重影因该是显示问题

好的，还有想请问一下，如果我想把真实标注的框和训练过程的产生框也显示在图片上应该怎么做呢？

**Comment by heavengate** [comment]
> > 打印出来的预测框只有两个，就是图中两个红框，重影因该是显示问题
> 
> 好的，还有想请问一下，如果我想把真实标注的框和训练过程的产生框也显示在图片上应该怎么做呢？

我们正在开发在图像上画gtbox的transform，可以关注一下最新的master

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen此issue
