### ISSUE TITLE
实时CPU人脸检测网络

### ISSUE THREAD

**Issue by yyqgood** [PaddlePaddle/PaddleDetection#1676]
你好， 我想确定以下问题：
1. BlazeFace和FaceBoxes是目前主流的实时CPU人脸检测网络吗？ 还有其他推荐的网络吗？
2. BlazeFace有6个关键点输出；FaceBoxes有计划输出关键点吗？
期待你的回复， 谢谢！

**Comment by qingqing01** [comment]
@yyqgood 

1. 在PaddleDetection中，我们目前只支持了BlazeFace和FaceBoxes，目前在WiderFace数据集的效果，BlazeFace还不错。
其他的网络，如https://github.com/Star-Clouds/CenterFace 也不错，但Paddle目前还不支持。  当然，也可以在BlazeFace/FaceBoxes的基础上优化，比如加FPN、更换backbone等。

2. FaceBoxes赞无计划支持关键点，也可以参考Blazeface自行加下。

**Comment by yyqgood** [comment]
感谢你的回复！
共享篇博文： https://blog.csdn.net/WZZ18191171661/article/details/102754281?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522160490546019725266931537%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=160490546019725266931537&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~baidu_landing_v2~default-1-102754281.first_rank_ecpm_v3_pc_rank_v2&utm_term=%E9%80%82%E5%90%88arm%E7%9A%84%E8%BD%BB%E9%87%8F%E7%BA%A7%E4%BA%BA%E8%84%B8%E6%A3%80%E6%B5%8B&spm=1018.2118.3001.4449#41__37
