### ISSUE TITLE
Python端预测部署

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleDetection#1681]
请问Python端预测部署具体应用于哪些场景，我想基于这个做websokcet的实时识别部署，怎么做？infer.py为啥那么多的代码，想请教一下目前的websocket服务部署用python怎么做

**Comment by liuhuiCNN** [comment]
您好，假如您想实现基于websokcet的实时识别部署，建议您参考 [PaddleServing部署](https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/serving)。infer.py 为本地python预测、benchmark测试代码。
