### ISSUE TITLE
autoaugment_utils.py在config中的使用！

### ISSUE THREAD

**Issue by wangkan83** [PaddlePaddle/PaddleDetection#1685]
想在faster_fpn_reader.yml中使用数据自动增强，如何加载autoaugment_utils.py中方法到配置文件中？？

**Comment by jerrywgz** [comment]
可以参考这里的配置 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/autoaugment/faster_rcnn_r50_vd_fpn_aa_3x.yml#L111

**Comment by wangkan83** [comment]
@jerrywgz ,thanks !
