### ISSUE TITLE
 Check failed: (idx < BlocksSize()): 0!<0 idx >= blocks.size() Aborted (core dumped)

### ISSUE THREAD

**Issue by maunzec** [PaddlePaddle/PaddleDetection#1689]
python D:/Work/Paddle/PaddleDetection/tools/export_model.py -c ppyolo_mobilenet_v3_large.yml -o weights=output/ppyolo_mobilenet_v3_large/model_final --output_dir=./inference_model
D:\Work\Paddle\PaddleDetection\ppdet\core\workspace.py:118: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  isinstance(merge_dct[k], collections.Mapping)):
D:\Python37\lib\site-packages\paddle\fluid\layers\math_op_patch.py:278: UserWarning: D:\Work\Paddle\PaddleDetection\ppdet\modeling\backbones\mobilenet_v3.py:228
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
2020-11-11 10:49:46,771-INFO: Load categories from D:/Work/CYY_glj/data/glj-number/label_list.txt
2020-11-11 10:49:46,774-INFO: Export inference config file to ./inference_model\ppyolo_mobilenet_v3_large\infer_cfg.yml
2020-11-11 10:49:46,881-INFO: save_inference_model pruned unused feed variables im_id
2020-11-11 10:49:46,882-INFO: Export inference model to ./inference_model\ppyolo_mobilenet_v3_large, input: ['image', 'im_size'], output: ['multiclass_nms_0.tmp_0']...

在arm上用编译好的paddllite,

root@orangepi3:~/work/ppyolo_mobilenet_v3_large# paddle_lite_opt --param_file=__model__ --model_file=__params__  --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=model
[I 11/11  4: 1:59.263 ...oot/paddle-lite/lite/core/device_info.cc:1065 Setup] ARM multiprocessors name:
[I 11/11  4: 1:59.263 ...oot/paddle-lite/lite/core/device_info.cc:1066 Setup] ARM multiprocessors number: 4
[I 11/11  4: 1:59.263 ...oot/paddle-lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 0, max freq: 1488, min freq: 1488, cluster ID: 0, CPU ARCH: A53
[I 11/11  4: 1:59.263 ...oot/paddle-lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 1, max freq: 1488, min freq: 1488, cluster ID: 0, CPU ARCH: A53
[I 11/11  4: 1:59.263 ...oot/paddle-lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 2, max freq: 1488, min freq: 1488, cluster ID: 0, CPU ARCH: A53
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 3, max freq: 1488, min freq: 1488, cluster ID: 0, CPU ARCH: A53
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1074 Setup] L1 DataCache size is:
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1076 Setup] 32 KB
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1076 Setup] 32 KB
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1076 Setup] 32 KB
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1076 Setup] 32 KB
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1078 Setup] L2 Cache size is:
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1080 Setup] 512 KB
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1080 Setup] 512 KB
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1080 Setup] 512 KB
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1080 Setup] 512 KB
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1082 Setup] L3 Cache size is:
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1084 Setup] 0 KB
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1084 Setup] 0 KB
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1084 Setup] 0 KB
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1084 Setup] 0 KB
[I 11/11  4: 1:59.264 ...oot/paddle-lite/lite/core/device_info.cc:1086 Setup] Total memory: 2027832KB
[I 11/11  4: 1:59.319 /root/paddle-lite/lite/api/cxx_api.cc Build:262] Load model from file.
[F 11/11  4: 1:59.361 ...ite/model_parser/general/program_desc.cc:29 GetBlock<paddle::lite::general::BlockDesc>] Check failed: (idx < BlocksSize()): 0!<0 idx >= blocks.size()
Aborted (core dumped)

**Comment by maunzec** [comment]
PaddleDetection 版本有要求吗还是Paddle有要求？lite 2.7 2.6我都试过了，都不行，Paddle用过1.72，1.8.5，1.8.4，2.0

**Comment by willthefrog** [comment]
用[lite转换工具](https://paddle-lite.readthedocs.io/zh/latest/user_guides/model_optimize_tool.html)转换是否报错？

**Comment by maunzec** [comment]
> 
> 
> 用[lite转换工具](https://paddle-lite.readthedocs.io/zh/latest/user_guides/model_optimize_tool.html)转换是否报错？


root@mazec-ubuntu:~/lite/ppyolo_mobilenet_v3_large# /root/lite/model_optimize_tool   --param_file=__model__ --model_file=__params__    --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=model
[W 11/11  6:18:29.348 ...dle-Lite/lite/api/model_optimize_tool.cc:135 RunOptimize] Load combined-param model. Option model_dir will be ignored
[I 11/11  6:18:29.348 ...odel_opt/Paddle-Lite/lite/api/cxx_api.cc:207 Build] Load model from file.
[F 11/11  6:18:29.356 ...te/lite/model_parser/cpp/program_desc.cc:23 GetBlock<paddle::lite::cpp::BlockDesc>] Check failed: idx < BlocksSize(): 0!<0 idx >= blocks.size()
Aborted (core dumped)


root@mazec-ubuntu:~/lite/ppyolo_mobilenet_v3_large# /root/lite/opt   --param_file=__model__ --model_file=__params__    --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=model
[W 11/11  6:20:40.212 /root/paddle-lite/lite/api/opt.cc RunOptimize:151] Load combined-param model. Option model_dir will be ignored
[I 11/11  6:20:40.212 /root/paddle-lite/lite/api/cxx_api.cc Build:262] Load model from file.
[F 11/11  6:20:40.220 ...ite/model_parser/general/program_desc.cc:29 GetBlock<paddle::lite::general::BlockDesc>] Check failed: (idx < BlocksSize()): 0!<0 idx >= blocks.size()
Aborted (core dumped)

model_optimize_tool   opt   都试过

**Comment by maunzec** [comment]
python D:/Work/Paddle/PaddleDetection/tools/infer.py -c ppyolo_mobilenet_v3_large.yml -o weights=output/ppyolo_mobilenet_v3_large/model_final.pdparams --infer_dir=test
D:\Work\Paddle\PaddleDetection\ppdet\core\workspace.py:118: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  isinstance(merge_dct[k], collections.Mapping)):
2020-11-11 14:31:53,230-INFO: Found 69 inference images in total.
D:\Python37\lib\site-packages\paddle\fluid\layers\math_op_patch.py:278: UserWarning: D:\Work\Paddle\PaddleDetection\ppdet\modeling\backbones\mobilenet_v3.py:228
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
W1111 14:31:53.969303 18888 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.2
W1111 14:31:53.978319 18888 device_context.cc:346] device: 0, cuDNN Version: 7.6.
2020-11-11 14:31:56,493-INFO: Load categories from D:/Work/CYY_glj/data/glj-number/label_list.txt
2020-11-11 14:31:56,646-INFO: Infer iter 0
2020-11-11 14:31:56,692-INFO: Detection bbox results save in output\2020_0000035.jpg
2020-11-11 14:31:56,763-INFO: Infer iter 1
2020-11-11 14:31:56,766-INFO: Detection bbox results save in output\2020_0000565.jpg
2020-11-11 14:31:56,829-INFO: Infer iter 2
2020-11-11 14:31:56,832-INFO: Detection bbox results save in output\2020_0000506.jpg
2020-11-11 14:31:56,901-INFO: Infer iter 3

**Comment by maunzec** [comment]
模型应该是正常的，用的2.0 cuda10.2跑的

**Comment by willthefrog** [comment]
库里提供的ppyolo能正常转换吗？

**Comment by maunzec** [comment]
> 
> 
> 库里提供的ppyolo能正常转换吗？

有链接吗?是paddlehub上的吗？哪里只看到有yolov3，我试过训练了yolov3版本也不行。所以我怀疑是paddle 版本问题？
lite-demo之前编译过是可以的，ssd那个检测可以跑，是c版本的

**Comment by willthefrog** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/configs/ppyolo

**Comment by maunzec** [comment]
> 
> 
> https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/configs/ppyolo

D:\Work\Paddle\model>python D:/Work/Paddle/PaddleDetection/tools/export_model.py -c ppyolo.yml -o weights=ppyolo --output_dir=./inference_model
D:\Work\Paddle\PaddleDetection\ppdet\core\workspace.py:118: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  isinstance(merge_dct[k], collections.Mapping)):
2020-11-11 15:39:04,479-INFO: Not found annotation file annotations/instances_val2017.json, load coco17 categories.
2020-11-11 15:39:04,487-INFO: Export inference config file to ./inference_model\ppyolo\infer_cfg.yml
2020-11-11 15:39:04,650-INFO: save_inference_model pruned unused feed variables im_id
2020-11-11 15:39:04,650-INFO: Export inference model to ./inference_model\ppyolo, input: ['image', 'im_size'], output: ['matrix_nms_0.tmp_0']...


root@mazec-ubuntu:~/lite# cd ppyolo
root@mazec-ubuntu:~/lite/ppyolo# /root/lite/model_optimize_tool   --param_file=__model__ --model_file=__params__    --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=model
[W 11/11  7:51:12.218 ...dle-Lite/lite/api/model_optimize_tool.cc:135 RunOptimize] Load combined-param model. Option model_dir will be ignored
[I 11/11  7:51:12.218 ...odel_opt/Paddle-Lite/lite/api/cxx_api.cc:207 Build] Load model from file.
[F 11/11  7:51:12.309 ...te/lite/model_parser/cpp/program_desc.cc:23 GetBlock<paddle::lite::cpp::BlockDesc>] Check failed: idx < BlocksSize(): 0!<0 idx >= blocks.size()
Aborted (core dumped)
root@mazec-ubuntu:~/lite/ppyolo# /root/lite/opt   --param_file=__model__ --model_file=__params__    --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=model
[W 11/11  7:51:15.978 /root/paddle-lite/lite/api/opt.cc RunOptimize:151] Load combined-param model. Option model_dir will be ignored
[I 11/11  7:51:15.978 /root/paddle-lite/lite/api/cxx_api.cc Build:262] Load model from file.
[F 11/11  7:51:16. 64 ...ite/model_parser/general/program_desc.cc:29 GetBlock<paddle::lite::general::BlockDesc>] Check failed: (idx < BlocksSize()): 0!<0 idx >= blocks.size()
Aborted (core dumped)


root@orangepi3:~/work/ppyolo# paddle_lite_opt --param_file=__model__ --model_file=__params__  --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=model
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1065 Setup] ARM multiprocessors name:
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1066 Setup] ARM multiprocessors number: 4
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 0, max freq: 1488, min freq: 1488, cluster ID: 0, CPU ARCH: A53
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 1, max freq: 1488, min freq: 1488, cluster ID: 0, CPU ARCH: A53
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 2, max freq: 1488, min freq: 1488, cluster ID: 0, CPU ARCH: A53
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 3, max freq: 1488, min freq: 1488, cluster ID: 0, CPU ARCH: A53
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1074 Setup] L1 DataCache size is:
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1076 Setup] 32 KB
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1076 Setup] 32 KB
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1076 Setup] 32 KB
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1076 Setup] 32 KB
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1078 Setup] L2 Cache size is:
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1080 Setup] 512 KB
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1080 Setup] 512 KB
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1080 Setup] 512 KB
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1080 Setup] 512 KB
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1082 Setup] L3 Cache size is:
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1084 Setup] 0 KB
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1084 Setup] 0 KB
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1084 Setup] 0 KB
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1084 Setup] 0 KB
[I 11/11  7:50:58. 70 ...oot/paddle-lite/lite/core/device_info.cc:1086 Setup] Total memory: 2027832KB
[I 11/11  7:50:58.565 /root/paddle-lite/lite/api/cxx_api.cc Build:262] Load model from file.
[F 11/11  7:50:59. 51 ...ite/model_parser/general/program_desc.cc:29 GetBlock<paddle::lite::general::BlockDesc>] Check failed: (idx < BlocksSize()): 0!<0 idx >= blocks.size()
Aborted (core dumped)

从连接上下载的

export_model.py -c ppyolo.yml -o weights=ppyolo --output_dir=./inference_model

root@orangepi3:~/work/ppyolo# paddle_lite_opt --param_file=__model__ --model_file=__params__  --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=model

root@mazec-ubuntu:~/lite# cd ppyolo
root@mazec-ubuntu:~/lite/ppyolo# /root/lite/model_optimize_tool   --param_file=__model__ --model_file=__params__    --valid_targets=arm --optimize_out_type=naive_buffer --optimize_out=model

**Comment by willthefrog** [comment]
建议去lite的[repo](https://github.com/PaddlePaddle/Paddle-Lite)提个issue，这个报错比较奇怪。。。

**Comment by xiaoninn** [comment]
提供一个思路，我在百度paddle上运行的，没有把paddle下载到系统里，也有这个错误，然后发现是模型保存的是用于预测而不是用于部署的。改了就可以生成.nb文件了
model.save('infer/zodiac')#模型用来预测
model_2.save('infer/zodiac', training=False)#模型用来部署
