### ISSUE TITLE
config配置文件解释

### ISSUE THREAD

**Issue by damon-10** [PaddlePaddle/PaddleDetection#169]
能否出一个完全版的关于config配置文件项的详细解释

**Comment by qingqing01** [comment]
@damon-10 

release分支 https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.1/docs/config_example  这里有完整版的英文解释，您期望还需要怎么改进更好？

**Comment by damon-10** [comment]
1希望能够解释的更详细些，比如某个配置项在什么场景下修改，修改后会产生什么影响？ 不单单只是标注某个配置项的专业词汇。
2比如我现在遇到的问题，测试图片上有100+个目标，但是结果只标出了图片前面的一少部分。这个问题是不是修改那个配置项就可以解决？

**Comment by qingqing01** [comment]
这里提供了一份参数文档： https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/advanced_tutorials/config_doc/RCNN_PARAMS_DOC.md

脚本入口参数： https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/tutorials/GETTING_STARTED_cn.md#%E5%8F%AF%E9%80%89%E5%8F%82%E6%95%B0%E5%88%97%E8%A1%A8
