### ISSUE TITLE
ppyolo + voc格式自制数据

### ISSUE THREAD

**Issue by lfs119** [PaddlePaddle/PaddleDetection#1690]
eval.py 评估计算 map=0.00%， eval_utils.py中eval_run返回值bbox与gt_box数值不在一个量级，box中字段值与目标在图片中的位置接近，gt_box中字段值小于1。  XML标签中检测框标签为对应物体在图片中的位置。
infer.py作图结果正常

**Comment by willthefrog** [comment]
能否给些示例？以及具体是如何操作的？

**Comment by lfs119** [comment]
![image](https://user-images.githubusercontent.com/23014201/98885811-ac260300-24cd-11eb-9272-1f61c30f48b2.png)
![gt_bbox](https://user-images.githubusercontent.com/23014201/98885885-d1b30c80-24cd-11eb-800b-50259e423871.png)

**Comment by lfs119** [comment]
运行tools/eval.py    打印eval_utils.py中eval_run返回值bbox与gt_box数值不在一个量级

**Comment by lfs119** [comment]
num_max_boxes统一设置为4

![image](https://user-images.githubusercontent.com/23014201/98886105-4e45eb00-24ce-11eb-87af-295500d8f16f.png)
![image](https://user-images.githubusercontent.com/23014201/98886133-6584d880-24ce-11eb-844d-75173ee142bb.png)

**Comment by lfs119** [comment]
标签格式如下：
![Uploading image.png…]()

**Comment by lfs119** [comment]
![image](https://user-images.githubusercontent.com/23014201/98886573-52bed380-24cf-11eb-9d1b-fc562669b11f.png)

**Comment by willthefrog** [comment]
gt是normalize过的，eval输出的应该是映射回原始大小的

**Comment by lfs119** [comment]
这种情况算的map是有问题的？有什么方法保证gt与eval输出数量级一致吗?

**Comment by willthefrog** [comment]
应该不是box的问题，看上去是class结果不对，基本都是1或者0

**Comment by lfs119** [comment]
标签值设置的0与1

**Comment by willthefrog** [comment]
注意yolo的标签是从0开始的，不是从1开始

**Comment by lfs119** [comment]
两个类别，0与1，不包括背景
