### ISSUE TITLE
多线程预测 出现检测结果错位

### ISSUE THREAD

**Issue by wanggp01** [PaddlePaddle/PaddleDetection#1693]
使用python的ThreadPoolExecutor开启4个线程，预测一批图像，最后的结果图像上，有几张出现将一张图的结果打印在另一张图上，代码如下：
![image](https://user-images.githubusercontent.com/62408936/98906659-764a4400-24f8-11eb-9134-0a9391859b76.png)

错位图片如下：
![image](https://user-images.githubusercontent.com/62408936/98906712-8c580480-24f8-11eb-9888-7f708f77d2f8.png)
![image](https://user-images.githubusercontent.com/62408936/98906730-967a0300-24f8-11eb-93ae-20c443e55259.png)

**Comment by yghstill** [comment]
@wanggp01 设置单个线程结果有打印到另一张图上吗？

**Comment by wanggp01** [comment]
> @wanggp01 设置单个线程结果有打印到另一张图上吗？

单线程结果正常，多线程测试一批2000多张的图集，会有10几张出现上述问题

**Comment by wanggp01** [comment]
@yghstill 单线程预测图片没有问题，多线程会有这种问题

**Comment by yghstill** [comment]
@wanggp01 好的，感谢反馈，我们跟进一下这个问题。

**Comment by heavengate** [comment]
现在的调用方式Detector是全局的，可以尝试一下把Detector创建放到子线程里面，每个子线程持有单独的Detector试下呢
