### ISSUE TITLE
训练时GPU利用率非常低，但是有在用（1-2%）

### ISSUE THREAD

**Issue by XiaoWen-AI** [PaddlePaddle/PaddleDetection#1698]
如题，2080s，训练maskrcnn，GPU利用率基本在1%，cpu利用率在20%， 试过加大batchsize和num_wordkers都没有效果，对GPU和CPU的利用率均没有影响。这样正常吗，训练时大概6.5images/second

**Comment by XiaoWen-AI** [comment]
任务管理器显示问题，实际利用率90+%

**Comment by Mesilenceki** [comment]
建议通过nvidia-smi驱动监控gpu使用率
