### ISSUE TITLE
deploy + vs2017 + cpp

### ISSUE THREAD

**Issue by lfs119** [PaddlePaddle/PaddleDetection#1703]
vs2017编译./main成功，cuda10.2,opencv3.46   运行报错
![image](https://user-images.githubusercontent.com/23014201/99241090-57211e80-2838-11eb-8593-a80b77712c9c.png)
![image](https://user-images.githubusercontent.com/23014201/99241177-76b84700-2838-11eb-9f26-d28c70fc2ebd.png)
![image](https://user-images.githubusercontent.com/23014201/99241289-9ea7aa80-2838-11eb-8f00-459617de8e45.png)

**Comment by qingqing01** [comment]
@lfs119 你测试的是那个模型？

**Comment by liuhuiCNN** [comment]
您使用的Paddle预测库是自己编译的吗？如果您使用官方预编译好的Paddle预测库，建议保持跟官方提供预测库使用CUDA版本一致。您可以参考：
[官方预编译预测库文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html)
[PaddleDetection部署文档]
(https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/cpp/docs/windows_vs2019_build.md)

**Comment by lfs119** [comment]
使用vs2017源码编译Paddle预测库提示这个错误
CMake Error at CMakeLists.txt:22 (project):
  Generator

    Visual Studio 15 2017

  could not find any instance of Visual Studio.

**Comment by liuhuiCNN** [comment]
> 使用vs2017源码编译Paddle预测库提示这个错误
> CMake Error at CMakeLists.txt:22 (project):
> Generator
> 
> ```
> Visual Studio 15 2017
> ```
> 
> could not find any instance of Visual Studio.

您检查线下 Visual Studio 的路径是否正确，Visual Studio 是否设置path环境？
