### ISSUE TITLE
导出的模型在agx部署python报错

### ISSUE THREAD

**Issue by liangruofei** [PaddlePaddle/PaddleDetection#1704]
各位大佬，请多多指教：

deploy的python在agx上部署时遇到问题；
在paddle1.8.5训练，用pp-yolo训练的resnet50
部署环境：agx，python3.6，cuda10.2，cudnn8.0运行infer.py
报错如下：
-----------  Configuration Arguments -----------
image_file: dataset/images/1590392775029.jpg
label_file: dataset/label_list.txt
model_dir: ./output/
run_mode: fluid
threshold: 0.5
use_gpu: True
------------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Use Padddle Executor: False
Transform Order: 
--transform op: Resize
--transform op: Normalize
--transform op: Permute
--------------------------------------------
W1116 05:28:15.623917 12725 analysis_predictor.cc:578] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I1116 05:28:15.624169 12725 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
I1116 05:28:15.710484 12725 analysis_predictor.cc:952] MODEL VERSION: 1.8.4
I1116 05:28:15.710736 12725 analysis_predictor.cc:954] PREDICTOR VERSION: 2.0.0
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I1116 05:28:16.478502 12725 graph_pattern_detector.cc:100] ---  detected 73 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
I1116 05:28:16.770416 12725 graph_pattern_detector.cc:100] ---  detected 32 subgraphs
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
I1116 05:28:16.830045 12725 graph_pattern_detector.cc:100] ---  detected 16 subgraphs
--- Running IR pass [conv_elementwise_add_fuse_pass]
I1116 05:28:16.861150 12725 graph_pattern_detector.cc:100] ---  detected 31 subgraphs
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I1116 05:28:16.939565 12725 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I1116 05:28:19.787103 12725 memory_optimize_pass.cc:223] Cluster name : im_size  size: 8
I1116 05:28:19.787250 12725 memory_optimize_pass.cc:223] Cluster name : transpose_0.tmp_0  size: 12996
I1116 05:28:19.787314 12725 memory_optimize_pass.cc:223] Cluster name : res2a.add.output.5.tmp_1  size: 23658496
I1116 05:28:19.787353 12725 memory_optimize_pass.cc:223] Cluster name : res2c.add.output.5.tmp_1  size: 23658496
I1116 05:28:19.787381 12725 memory_optimize_pass.cc:223] Cluster name : pool2d_6.tmp_0  size: 739328
I1116 05:28:19.787418 12725 memory_optimize_pass.cc:223] Cluster name : image  size: 4435968
I1116 05:28:19.787494 12725 memory_optimize_pass.cc:223] Cluster name : yolo_box0.tmp_0  size: 17328
I1116 05:28:19.787523 12725 memory_optimize_pass.cc:223] Cluster name : slice_40.tmp_0  size: 23104
I1116 05:28:19.787593 12725 memory_optimize_pass.cc:223] Cluster name : res2b.add.output.5.tmp_1  size: 23658496
I1116 05:28:19.787683 12725 memory_optimize_pass.cc:223] Cluster name : tmp_31  size: 23104
I1116 05:28:19.787716 12725 memory_optimize_pass.cc:223] Cluster name : bn2a_branch2b.output.1.tmp_3  size: 5914624
I1116 05:28:19.787737 12725 memory_optimize_pass.cc:223] Cluster name : clip_17.tmp_0  size: 23104
I1116 05:28:19.787755 12725 memory_optimize_pass.cc:223] Cluster name : leaky_relu_6.tmp_0  size: 1478656
I1116 05:28:19.787781 12725 memory_optimize_pass.cc:223] Cluster name : slice_37.tmp_0  size: 69312
I1116 05:28:19.787804 12725 memory_optimize_pass.cc:223] Cluster name : transpose_1.tmp_0  size: 51984
I1116 05:28:19.787822 12725 memory_optimize_pass.cc:223] Cluster name : pow_17.tmp_0  size: 23104
I1116 05:28:19.787850 12725 memory_optimize_pass.cc:223] Cluster name : leaky_relu_12.tmp_0  size: 1478656
I1116 05:28:19.787887 12725 memory_optimize_pass.cc:223] Cluster name : tmp_27  size: 23104
--- Running analysis [ir_graph_to_program_pass]
I1116 05:28:20.023169 12725 analysis_predictor.cc:513] ======= optimize end =======
I1116 05:28:20.023845 12725 naive_executor.cc:102] ---  skip [feed], feed -> im_size
I1116 05:28:20.023926 12725 naive_executor.cc:102] ---  skip [feed], feed -> image
I1116 05:28:20.037015 12725 naive_executor.cc:102] ---  skip [res2b.add.output.5.tmp_1], fetch -> fetch
W1116 05:28:20.133224 12725 device_context.cc:320] Please NOTE: device: 0, CUDA Capability: 72, Driver API Version: 10.2, Runtime API Version: 10.2
W1116 05:28:20.140355 12725 device_context.cc:328] device: 0, cuDNN Version: 8.0.
W1116 05:28:25.175592 12725 operator.cc:200] conv2d_fusion raises an exception std::logic_error, basic_string::_M_construct null not valid
Traceback (most recent call last):
  File "infer.py", line 556, in <module>
    result = predict_image(args.image_file)
  File "infer.py", line 517, in predict_image
    results = detector.predict(image_path, args.threshold)
  File "infer.py", line 496, in predict
    self.predictor.zero_copy_run()
RuntimeError: basic_string::_M_construct null not valid

**Comment by Mesilenceki** [comment]
看着像着是版本问题，你能确认下训练使用的版本和部署的版本一致吗

**Comment by liuhuiCNN** [comment]
请您确认下训练时使用的Paddle版本和预测时使用的Paddle版本是否一致。
您可以参考下这个文档：
[PaddleDetection部署文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy)

**Comment by liangruofei** [comment]
我是按这个文档操作的，唯一的区别就是训练的环境和部署的环境paddle版本不一样，训练的paddle是1.8.5，部署的是2.0-beta，后来我改了一下训练的用的2.0-rc，部署用的2.0-beta；这个paddle版本影响很大吗

**Comment by liuhuiCNN** [comment]
> 我是按这个文档操作的，唯一的区别就是训练的环境和部署的环境paddle版本不一样，训练的paddle是1.8.5，部署的是2.0-beta，后来我改了一下训练的用的2.0-rc，部署用的2.0-beta；这个paddle版本影响很大吗

这个是有影响的，尤其是嵌入式设备中，麻烦您使用相同的版本测试一下。
