### ISSUE TITLE
我想原图大小输入训练一直报错，麻烦大佬帮我看看有什么问题

### ISSUE THREAD

**Issue by liboshi33** [PaddlePaddle/PaddleDetection#1705]
# #```
TrainReader:
  dataset:
    !VOCDataSet
    dataset_dir: ./dataset/dibanluoshuan/dibanluoshuan
    anno_path: trainval.txt
    use_default_label: false
  sample_transforms:
  - !ResizeImage
    target_size: 1400
    max_size: 2048
    interp: 1
    use_cv2: true
  batch_size: 8
```

这个是我训练的代码，可是一直在报错
Traceback (most recent call last):
  File "/home/administrator/Projects/PaddleDetection-release-0.4/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/home/administrator/Projects/PaddleDetection-release-0.4/ppdet/data/transform/operators.py", line 305, in __call__
    im = sample['image']
KeyError: 'image'

2020-11-17 09:55:54,571-WARNING: fail to map op [ResizeImage_e1ba6e] with error: 'image' and stack:
Traceback (most recent call last):
  File "/home/administrator/Projects/PaddleDetection-release-0.4/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/home/administrator/Projects/PaddleDetection-release-0.4/ppdet/data/transform/operators.py", line 305, in __call__
    im = sample['image']
KeyError: 'image'

**Comment by jerrywgz** [comment]
这里需要在reader中增加inputs_def的配置
![image](https://user-images.githubusercontent.com/22989727/99341588-263afb00-28c5-11eb-9697-af1b02389811.png)

**Comment by liboshi33** [comment]
> 這裡需要在閱讀器中增加inputs_def的配置
> ![圖片](https://user-images.githubusercontent.com/22989727/99341588-263afb00-28c5-11eb-9697-af1b02389811.png)

**Comment by liboshi33** [comment]
![Uploading 1605593051(1).png…]()

**Comment by liboshi33** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 372, in <module>
    main()
  File "tools/train.py", line 117, in main
    train_fetches = model.train(feed_vars)
  File "/home/administrator/Projects/PaddleDetection-release-0.4/ppdet/modeling/architectures/faster_rcnn.py", line 240, in train
    return self.build(feed_vars, 'train')
  File "/home/administrator/Projects/PaddleDetection-release-0.4/ppdet/modeling/architectures/faster_rcnn.py", line 73, in build
    self._input_check(required_fields, feed_vars)
  File "/home/administrator/Projects/PaddleDetection-release-0.4/ppdet/modeling/architectures/faster_rcnn.py", line 189, in _input_check
    "{} has no {} field".format(feed_vars, var)
AssertionError: OrderedDict([('image', name: "image"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 3
      dims: -1
      dims: -1
    }
    lod_level: 0
  }
}
persistable: false
need_check_feed: true
), ('im_info', name: "im_info"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 3
    }
    lod_level: 0
  }
}
persistable: false
need_check_feed: true
), ('im_id', name: "im_id"

**Comment by jerrywgz** [comment]
抱歉上面给的是yolo模型在voc上的配置方式，如果是rcnn模型的话按如下方式配置：
![image](https://user-images.githubusercontent.com/22989727/99354186-eda91a80-28e0-11eb-9d7d-d93050b7f2c2.png)

**Comment by liboshi33** [comment]
> 抱歉上面给的是yolo模型在voc上的配置方式，如果是rcnn模型的话按如下方式配置：
> ![image](https://user-images.githubusercontent.com/22989727/99354186-eda91a80-28e0-11eb-9d7d-d93050b7f2c2.png)

![1605595906(1)](https://user-images.githubusercontent.com/69001886/99356174-ae7cc880-28e4-11eb-8044-bdfca08f0f2e.png)
![1605595980(1)](https://user-images.githubusercontent.com/69001886/99356175-afadf580-28e4-11eb-8715-0f11cb3e1889.png)

**Comment by liboshi33** [comment]
> 抱歉上面给的是yolo模型在voc上的配置方式，如果是rcnn模型的话按如下方式配置：
> ![image](https://user-images.githubusercontent.com/22989727/99354186-eda91a80-28e0-11eb-9d7d-d93050b7f2c2.png)

老哥在帮忙看一下谢谢了

**Comment by jerrywgz** [comment]
这里需要检查下你的paddle安装环境是否正确，从报错信息上来看是你没有的nccl安装有问题，可以看下这里https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/install/index_cn.html#paddlepaddle-nccl  然后通过如下方式验证下安装是否正确
![image](https://user-images.githubusercontent.com/22989727/99356547-4d092980-28e5-11eb-99e0-f49281328f9f.png)

**Comment by liboshi33** [comment]
> 这里需要检查下你的paddle安装环境是否正确，从报错信息上来看是你没有的nccl安装有问题，可以看下这里https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/install/index_cn.html#paddlepaddle-nccl 然后通过如下方式验证下安装是否正确
> ![image](https://user-images.githubusercontent.com/22989727/99356547-4d092980-28e5-11eb-99e0-f49281328f9f.png)

您好我装好了nccl了，但是还是不行您帮我再看下，
![1605602911](https://user-images.githubusercontent.com/69001886/99367379-d96f1880-28f4-11eb-960d-6e039386e9eb.png)
![1605602945(1)](https://user-images.githubusercontent.com/69001886/99367393-dbd17280-28f4-11eb-8f62-90261d45ccb9.png)

谢谢了

**Comment by jerrywgz** [comment]
看上去还是没有在fields里加rcnn的那些字段

**Comment by liboshi33** [comment]
> 看上去还是没有在fields里加rcnn的那些字段

![99356174-ae7cc880-28e4-11eb-8044-bdfca08f0f2e](https://user-images.githubusercontent.com/69001886/99399857-2ec11f00-2921-11eb-9d72-39deeb33d83e.png)
我加了呀，您看一看是不是我加错了，麻烦您了

**Comment by liboshi33** [comment]
> 看上去还是没有在fields里加rcnn的那些字段

我解决了，是因为它那个信息要都输进去，谢谢大佬了，大佬有时间帮我看看我又提了一个问题，faster-rcnn resnet101不知道为啥map一直是0，如果用resnet50就是正常的就很迷
