### ISSUE TITLE
FLOPs和参数量的计算

### ISSUE THREAD

**Issue by daiyuanm** [PaddlePaddle/PaddleDetection#1713]
你好，我利用自己的数据集训练了贵方的多个[移动端模型](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/mobile/README.md)以及PPYOLO的[移动版](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/ppyolo/README_cn.md)，现在想计算这些模型的FLOPs以及参数量，请问我该怎么计算呢？是不是我得另外写代码计算还是贵方提供这样的代码呢？十分感谢！另外，反馈一下，贵方提供的移动端模型训练简单易用，效果也十分不错！

**Comment by willthefrog** [comment]
参数量可以直接使用`paddle.summary`获得。 FLOPs计算需要自己实现。

**Comment by daiyuanm** [comment]
> 参数量可以直接使用`paddle.summary`获得。 FLOPs计算需要自己实现。

请问，paddeledetection里面好像模型都封装好了，我要怎么使用`paddle.summary`呢？

**Comment by willthefrog** [comment]
哦，好像是不行，`paddle.summary`是针对`nn.Layer`的模型，目前paddle detection还在迁移过程中。
