### ISSUE TITLE
c++部署时，在线程中执行检测函数中断

### ISSUE THREAD

**Issue by XiaoWen-AI** [PaddlePaddle/PaddleDetection#1714]
0x00007FFD484E3B29 处(位于 Color_Only.exe 中)引发的异常: Microsoft C++ 异常: std::runtime_error，位于内存位置 0x00000095A20FF330 处。
0x00007FFD484E3B29 处(位于 Color_Only.exe 中)引发的异常: Microsoft C++ 异常: std::runtime_error，位于内存位置 0x00000095A20FCB70 处。
0x00007FFD484E3B29 处(位于 Color_Only.exe 中)引发的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x00000095A20FF378 处。
0x00007FFD484E3B29 处(位于 Color_Only.exe 中)引发的异常: Microsoft C++ 异常: [rethrow]，位于内存位置 0x0000000000000000 处。
0x00007FFD484E3B29 处(位于 Color_Only.exe 中)引发的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x00000095A20FF378 处。
0x00007FFD484E3B29 处(位于 Color_Only.exe 中)有未经处理的异常: Microsoft C++ 异常: paddle::platform::EnforceNotMet，位于内存位置 0x00000095A20FF378 处。

报错如上，线程只开启一次，在线程中重复执行检测函数，每次执行间隔大概1秒，每次检测耗时50毫秒，应该不存在访问冲突才对
![image](https://user-images.githubusercontent.com/38575973/99499363-bce5e580-29b3-11eb-8287-c932d408e3d2.png)

**Comment by XiaoWen-AI** [comment]
补充一下：在GPU模式会出现这种问题，CPU模式不会

**Comment by XiaoWen-AI** [comment]
每次检测相同的图片则不会出错，换了图片就会出错

**Comment by liuhuiCNN** [comment]
请您确认下训练和预测使用的paddle版本是否一致。

**Comment by XiaoWen-AI** [comment]
> 请您确认下训练和预测使用的paddle版本是否一致。

版本是一致的，一样的电脑，一样的环境，同样的图片重复跑了好久都没中断，跑得过程中如果换了图片就会中断

**Comment by XiaoWen-AI** [comment]
总结一下出问题的规律：
1）检测的所有图片里如果都没用目标，一直重复检测，不会中断
2）检测的图片里一直有目标，一直重复检测，不会中断
3）先检测没目标的图片，再检查有目标的图片，不会中断
4）先检测有目标的图片，再检查没目标的图片，**会中断**
5）cpu上不会中断

报错如下：
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at D:\inference_cuda10.1\paddle\paddle\fluid\platform\gpu_info.cc:286)

**Comment by qingqing01** [comment]
可以试用下最新的部署示例~

**Comment by sdnusqy-art** [comment]
请问这个问题解决了吗？ 我也遇到了类似问题,C++部署gpu检测，用yolov3_mobilenet 训练的roadsign数据，单线程，初始化单个predictor,遍历检测多张不同图片，出现cuda error(700)错误；遍历检测同一张图片多次无错误。 paddle1.8.5无错误
PaddlePaddle:release/2.0
PaddleDetection: release/2.0
cuda：10.2
cudnn:7.6.5
os: centos7.8

**Comment by Shrinco** [comment]
您好，我也遇到了同样的问题，我在使用TesnsorRT加速时，在线程执行时，第一次会执行，再次执行时会出现这样的错误。
![image](https://user-images.githubusercontent.com/50402380/183328388-797f43ab-d115-4013-8162-493bdf889821.png)
