### ISSUE TITLE
在arm上部署paddledetection客户端失败

### ISSUE THREAD

**Issue by TongHengcheng** [PaddlePaddle/PaddleDetection#1717]
我已经安装好了paddle_serving_client以及paddle_serving_app，但是在在初始化client时，提示找不到serving_client.so这个文件
![image](https://user-images.githubusercontent.com/35362026/99515794-62a34f80-29c8-11eb-9d8d-695de718c052.png)，但是在指定的路径上，该文件是存在的
![image](https://user-images.githubusercontent.com/35362026/99515952-9a11fc00-29c8-11eb-9c2a-bce2a5d7dcb3.png)
q请问这是什么原因导致的，望解答。（我使用的平台的nvidia jetson tx2, paddle_serving_client是使用pip直接安装的，另外，在x86平台我测试过是没有这个问题的。）

**Comment by willthefrog** [comment]
你确定paddle_serving_client是arm的版本？x86的binary在arm上是无法运行的

试下 `file serving_client.so` 看看输出是什么？

**Comment by TongHengcheng** [comment]
nvidia@miivii-tegra:~/.local/lib/python3.6/site-packages/paddle_serving_client$ file serving_client.so 
serving_client.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=0c69de54d327e7ef3b08510ba47526ceb9714980, with debug_info, not stripped
这个是输出结果，如果要在arm上运行，需要使用源码安装paddle_serving_client 吗？

**Comment by TongHengcheng** [comment]
nvidia@miivii-tegra:~/.local/lib/python3.6/site-packages/paddle_serving_client$ file serving_client.so&nbsp;
serving_client.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=0c69de54d327e7ef3b08510ba47526ceb9714980, with debug_info, not stripped
是的，.so文件是x86的，如果想要在arm上运行，是要使用源码编译paddle_serving_client吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang Zhang"<notifications@github.com&gt;; 
发送时间: 2020年11月18日(星期三) 晚上6:42
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 
抄送: "2841799783"<2841799783@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] 在arm上部署paddledetection客户端失败 (#1717)





 
你确定paddle_serving_client是arm的版本？x86的binary在arm上是无法运行的
 
试下 file serving_client.so 看看输出是什么？

**Comment by willthefrog** [comment]
对

**Comment by TongHengcheng** [comment]
paddle_serving_client是在paddleserving下，是要编译整个库还是只要编译paddle_serving_client这个库就行了，请问有相关的教程吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月18日(星期三) 晚上9:48
收件人:&nbsp;"PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送:&nbsp;"2841799783"<2841799783@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 在arm上部署paddledetection客户端失败 (#1717)





 
对

**Comment by willthefrog** [comment]
建议去serving的repo提个issue问下吧。

**Comment by TongHengcheng** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 上午9:55
收件人:&nbsp;"PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送:&nbsp;"2841799783"<2841799783@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 在arm上部署paddledetection客户端失败 (#1717)





 
建议去serving的repo提个issue问下吧。
