### ISSUE TITLE
训练爆nan

### ISSUE THREAD

**Issue by txssg** [PaddlePaddle/PaddleDetection#1719]
![9E5FZ6LOFCKQ~$RWV{%PDE5](https://user-images.githubusercontent.com/61171287/99537042-1f57d980-29e6-11eb-9094-ac98621200e0.png)

**Comment by txssg** [comment]
![UUE($MBMLJ_ _1% OD`3{DS](https://user-images.githubusercontent.com/61171287/99537172-4a422d80-29e6-11eb-98b9-fb573e894566.png)
单卡

**Comment by willthefrog** [comment]
建议先尝试下 调低 warm up的 `start_factor`并增加`steps`吧，似乎也没有什么好办法。

**Comment by txssg** [comment]
> 建议先尝试下调低warm up的`start_factor`并增加`steps`吧，似乎也没有什么好办法。

前10000iter还比较正常，但是10000以后就疯狂爆nan

**Comment by txssg** [comment]
![JV`VTXU8YD2CESKH7J5 YV](https://user-images.githubusercontent.com/61171287/99676254-357f9b80-2ab3-11eb-8aed-3e8bd4231e70.png)
还有请问一下这个错是什么原因呢
数据集：pcb_dataset
模型配置文件：cascade_rcnn_r50_fpn_1x_ms_test.yml
配置信息：
![LI0W{H%Y{1S$Z(EXQ@80~ T](https://user-images.githubusercontent.com/61171287/99676488-88f1e980-2ab3-11eb-8896-7bdd489b7d32.png)

**Comment by yghstill** [comment]
@txssg PCB数据集较小，训练到1w轮的时候网络已经收敛的很好了，再使用大的学习率容易造成梯度爆炸，可以试着在1w轮调低学习率继续训练，训练36w轮有点太多了，调整到1-2w就足够了。
