### ISSUE TITLE
请问如何使用ppdet做迁移学习？

### ISSUE THREAD

**Issue by a2824256** [PaddlePaddle/PaddleDetection#1720]
想把预训练好的mask-rcnn模型冻结部分网络层，然后在新的数据集上再训练部分网络层，请问有什么方法吗？
是把可训练参数的trainable设置为False吗？

**Comment by heavengate** [comment]
需要冻结的那部分网络的输出加下 `out.stop_gradient = True` 就可以了

**Comment by a2824256** [comment]
好的感谢。
我还有一个问题想要请教一下，我们自己做了coco格式的数据集，但是mask-rcnn的label依旧是coco的。我需要怎么把label转变成自己的？我是通过下面教程用x2coco.py把labelme的数据集转换为coco的。
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/tutorials/Custom_DataSet.md

**Comment by yghstill** [comment]
@a2824256 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/mask_fpn_reader.yml#L79  测试时这个anno_path改成你自己数据集的json文件就行

**Comment by a2824256** [comment]
@yghstill 发现了一个问题，和coco2017的json文件对比，coco的json文件末尾有categories这个字段来储存分类id与分类的映射关系，但是x2coco.py转出来的文件没有这个。然后使用tools/infer.py对单张图片进行预测的时候就导致图片上面什么都没有。

**Comment by a2824256** [comment]
请问使用tools/infer.py对单张图片进行预测，在哪设置label？我就算使用了coco2017的val的json文件，infer还是没有东西出来

**Comment by a2824256** [comment]
不好意思，我看错文件了，已经解决。
