### ISSUE TITLE
预测时物体检测正确，但label名错误

### ISSUE THREAD

**Issue by IamDestiny** [PaddlePaddle/PaddleDetection#1736]
我的label里没有bicycle,但预测时出现了bicycle这个标签，在ppyolo.yml和ppyolo_reader.yml文件里找过了，没找到与label相关的参数

**Comment by yuloveli** [comment]
本来应该是car,结果预测成了bicycle,但是bbox的位置是正确的

**Comment by yuloveli** [comment]
![dog](https://user-images.githubusercontent.com/66876429/99871109-ea7c9a00-2c12-11eb-9a2d-6cbf0daf619a.jpg)

**Comment by yuloveli** [comment]
![dog (1)](https://user-images.githubusercontent.com/66876429/99871130-10a23a00-2c13-11eb-9929-447d3e300ac0.jpg)

**Comment by yuloveli** [comment]
use_default_label这个参数只有VOC数据集对应的文件里才有，COCO数据集里没有

**Comment by qingqing01** [comment]
@yuloveli  如果您是COCO数据集，在TestReader中指定下 `anno_path`吧，类似：


https://github.com/PaddlePaddle/PaddleDetection/blob/e74203cfa70c8fa5d1bc7bde68345f0bc8d7d16e/configs/yolov3_reader.yml#L89-L97

**Comment by yuloveli** [comment]
@qingqing01 那是不是改过之后需要重新训练？而且我也没有准备test数据集的json文件。。。
