### ISSUE TITLE
请问如何使用多核cpu进行训练

### ISSUE THREAD

**Issue by nuaaceieyty** [PaddlePaddle/PaddleDetection#1737]
我的cpu是12核的，请问怎么使用多核cpu进行训练？？

**Comment by qingqing01** [comment]
1.  tools/train.py 参数传入 --use_gpu=False
2. 设置环境变量 CPU_NUM=8，这样可以采用8个线程，并行训练。

**Comment by nuaaceieyty** [comment]
> 1. tools/train.py 参数传入 --use_gpu=False
> 2. 设置环境变量 CPU_NUM=8，这样可以采用8个线程，并行训练。

请问是直接将os.environ里的“CPU_NUM"赋值为8吗？？

**Comment by qingqing01** [comment]
静态图设置环境变量即可。命令行和os.environ都可以
