### ISSUE TITLE
实时rtsp流如何实时查看检测结果

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleDetection#1742]
PaddleDetection\deploy\python\infer.py 你好我用infer来做目标检测，检测mp4文件可以write一个新的mp4，如果我传一个rtsp流，如何可以cv.imshow实时查看检测结果呢，visualize_box_mask这个方法返回image类型如何转成cv2.imshow需要的mat类型？请教一下。

**Comment by Sunyingbin** [comment]
还有一个问题，用python调用的rtsp视频，会有10秒的延迟，这应该怎么办呢？

**Comment by qingqing01** [comment]
@Sunyingbin 

您设置 camera_id 为不等于-1的一个数字呢？

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/python/infer.py#L609

**Comment by Sunyingbin** [comment]
哦哦，明白了

**Comment by Sunyingbin** [comment]
那请问延迟怎么办呢

**Comment by rygf-chen** [comment]
请问mp4文件可以实时查看结果吗
