### ISSUE TITLE
缺少根据exif信息对图像进行旋转的操作

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/PaddleDetection#1747]
https://github.com/PaddlePaddle/PaddleDetection/blob/e74203cfa70c8fa5d1bc7bde68345f0bc8d7d16e/tools/infer.py#L204

使用PIL的Image对图像进行打开后，默认不会对图形进行根据EXIF中记录翻转角度的信息进行翻转，造成最后在该图片上进行mask和bbox标识时，发生index溢出。

在该行下面添加

```python
image = ImageOps.exif_transpose(image)
```

即可。

**Comment by qingqing01** [comment]
@mikeshi80  非常感谢指出问题，我们也尽快修复下~

**Comment by yghstill** [comment]
fixed, thanks feedback.
