### ISSUE TITLE
产品名拼写错误

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/PaddleDetection#1750]
https://github.com/PaddlePaddle/PaddleDetection/blob/8d4f12bc045077bb7d891242604582f68cd54cf9/deploy/python/infer.py#L344

这……好歹是自己产品，不要连名字也拼错啊

**Comment by qingqing01** [comment]
@mikeshi80 感谢指出~

**Comment by yghstill** [comment]
fixed, thanks feedback.
