### ISSUE TITLE
SOLOv2问题：

### ISSUE THREAD

**Issue by wangkan83** [PaddlePaddle/PaddleDetection#1756]
运行olov2_light_r50_vd_fpn_dcn_512_3x.yml，batch size :1,显存占用30%，显卡CUDA利用率0%，一直卡在这个位置，光标闪烁，求指导！！
![image](https://user-images.githubusercontent.com/63913709/100093295-499c1200-2e92-11eb-9469-acbe9c73b16c.png)

**Comment by wangkan83** [comment]
终端重启运行后，出现这样：一直卡在这个位置，光标闪烁，
![image](https://user-images.githubusercontent.com/63913709/100093774-f4143500-2e92-11eb-81b8-a524e245f702.png)

**Comment by yghstill** [comment]
@wangkan83 已经启动训练了，每隔20iter打印一次log

**Comment by wangkan83** [comment]
@yghstill ，一直停留在第0iter，没有进入后续训练！！

**Comment by yghstill** [comment]
你是CPU下训练吗？

**Comment by wangkan83** [comment]
GPU

**Comment by wangkan83** [comment]
@yghstill ，配置文件中只更改了：
1、#pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_ssld_pretrained.tar
pretrain_weights: configs/solov2/solov2_light_r50_vd_fpn_dcn_512_3x
2、num_classes: 5
3、base_lr: 0.00125
4、自己的COCO数据集（用mask_rcnn_dcn_r50_vd_fpn_aa_2x.yml训练OK）
多次重启终端，一直一直停留在第0iter，没有进入后续训练！！batch size :1,显存占用30%，显卡CUDA利用率0%！！
![image](https://user-images.githubusercontent.com/63913709/100095580-b1079100-2e95-11eb-9297-e34a3cd2ff6f.png)
![image](https://user-images.githubusercontent.com/63913709/100095701-dac0b800-2e95-11eb-88a6-b1d513ca3c8e.png)

**Comment by yghstill** [comment]
@wangkan83 可以将您一小部分数据上传吗，我们测下出了哪些问题，在coco原始数据集上没有遇到问题。

**Comment by wangkan83** [comment]
@yghstill ，百度网盘https://pan.baidu.com/s/1fdBArgNbRj609XPAPp9Jag ，提取吗：455q

**Comment by yghstill** [comment]
@wangkan83 您提供的是语义分割类型的数据集，无法训练实例分割模型，能否转换乘json标注文件的标准coco格式

**Comment by wangkan83** [comment]
@yghstill  https://pan.baidu.com/s/108dExnkZGVFlmss9AMzgxA 提取吗：n5qz

**Comment by yghstill** [comment]
@wangkan83 你试下solov2_r50_fpn_1x.yml这个模型吧，经测试，GPU利用率和训练都是正常的。
```shell
Evaluate annotation type *segm*
DONE (t=0.02s).
Accumulating evaluation results...
DONE (t=0.04s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.401
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.666
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.366
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.091
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.251
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.673
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.411
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.411
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.411
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.100
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.247
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.680
2020-11-26 13:05:58,846-INFO: Save model to output/solov2_r50_fpn_xiwa_1x/best_model.
2020-11-26 13:06:04,111-INFO: Best test box ap: 0.4014851485148515, in iter: 6000
```
![image](https://user-images.githubusercontent.com/15628872/100360997-961f5300-3034-11eb-849e-76c3eff2acd1.png)

**Comment by wangkan83** [comment]
@yghstill ，OK！

**Comment by wangkan83** [comment]
@yghstill ,可以把你修改的solov2_r50_fpn_1x.yml和solov2_reader.yml发一下参考？

**Comment by yghstill** [comment]
在4卡GPU下训练，如果单卡训练再适当调小base_lr
```yaml
max_iters: 30000
num_classes: 5
LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [18000, 26000]
  - !LinearWarmup
    start_factor: 0.
    steps: 1000
```

**Comment by wangkan83** [comment]
@yghstill  thanks!!

**Comment by wangkan83** [comment]
@yghstill ，出现这样的问题，当采用本机训练时，base_lr: 0.00025，iter不到1000就又停止了，显卡CUDA利用率降到0%！！
![image](https://user-images.githubusercontent.com/63913709/100406641-504ca400-30a1-11eb-9c87-41d5b428511a.png)
在aistudio上train，评估时出错。
![image](https://user-images.githubusercontent.com/63913709/100406909-01ebd500-30a2-11eb-8399-26a52801470d.png)

**Comment by yghstill** [comment]
@wangkan83 评估是因为没有预测出结果所以报错，可以训完之后再eval，你windows下将worker_num设为1再试下呢？ https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/configs/solov2/solov2_reader.yml#L3

**Comment by wangkan83** [comment]
@yghstill worker_num设为1还是不行。在aistudio上train完了，eval后还无法达到你的iter4000的效果！！

**Comment by yghstill** [comment]
@wangkan83 我是使用4卡GPU训练的，单卡训练可在适当调多训练轮数。

**Comment by yghstill** [comment]
@wangkan83 您好，可否将您这个demo作为一个案例，我们宣传一下实例分割的检测效果？
