### ISSUE TITLE
ppyolo训练问题：

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#1759]
运行PPYOLO.yml，batch size :4,显存占用20%，显卡CUDA利用率0%，一直卡在这个位置，光标闪烁，求指导！！
![image](https://user-images.githubusercontent.com/63913709/100103948-82db7e80-2ea0-11eb-9729-4bb0880332b0.png)

**Comment by jerrywgz** [comment]
这里可以先尝试下减小batch size，然后将trainreader中的work_num调至1看下；另外可以到ppdet/data/source/coco.py中打印下加载进来的数据records是不是符合预期的

**Comment by heavengate** [comment]
启动需要一段时间准备数据和子进程，有的机器上可能需要2-3min，你这边卡在这儿多久了呢

**Comment by wangkan83** [comment]
@heavengate ,一直卡这里，大概20分钟了

**Comment by heavengate** [comment]
> @heavengate ,一直卡这里，大概20分钟了
`top -c`看下呢，另外你数据集有多少个sample

**Comment by wangkan83** [comment]
@jerrywgz @heavengate ，数据集样本100个，batch size减小到1，work_num减小到1，仍然一直卡这里。同样的数据集用paddleX可以训练起来！！
![image](https://user-images.githubusercontent.com/63913709/100235983-090ec800-2f68-11eb-808b-17174d344f07.png)

**Comment by thinkthinking** [comment]
最新PaddleDetection版本已修复。
