### ISSUE TITLE
训练意外停止后，显存不释放

### ISSUE THREAD

**Issue by zhizunbao-y** [PaddlePaddle/PaddleDetection#176]

**Comment by littletomatodonkey** [comment]
1. 可以使用`top`命令看下是否有没有hang住的进程，有的话，根据对应的pid号，kill即可(`kill -9 ${pid_number}`)
2. 如果没有找到，或者kill之后仍然没有释放，可以使用`fuser -v /dev/nvidia*`命令，找到与显卡驱动相关进程，kill即可

**Comment by heavengate** [comment]
fixed by https://github.com/PaddlePaddle/PaddleDetection/pull/136
