### ISSUE TITLE
使用ttfnet_darknet模型训练时，提示AttributeError: module 'paddle' has no attribute 'tensor'

### ISSUE THREAD

**Issue by Lxiaom123** [PaddlePaddle/PaddleDetection#1763]
请教大家，问题如下图，谢谢！
![image](https://user-images.githubusercontent.com/66930694/100225029-95b18a00-2f58-11eb-8ccb-2853168710bd.png)

**Comment by jerrywgz** [comment]
建议使用release/0.5分支 + paddle2.0版本

**Comment by Lxiaom123** [comment]
使用release/0.5分支 + paddle2.0版本，不报错，但就一直停在这好久了，如图，不往下了
![image](https://user-images.githubusercontent.com/66930694/100233080-2b9ee200-2f64-11eb-9386-432e086f638e.png)

**Comment by jerrywgz** [comment]
可能是卡在reader处了，可以在运行时用top -c看下内存占用，然后可以尝试减小batch_size和worker_num

**Comment by Lxiaom123** [comment]
内存占用如图，batch_size和worker_num设置为1，还是卡在那里
![image](https://user-images.githubusercontent.com/66930694/100302641-bbc93f80-2fd5-11eb-80c4-b76284e65c78.png)

**Comment by jerrywgz** [comment]
这个我们这边还没有复现这种情况，再尝试下use_process设置成False呢，另外就是你这边是用多卡训练的吗？可以先使用paddle.fluid.install_check.run_check()确认下多卡安装环境是否正常

**Comment by Lxiaom123** [comment]
use_process是设置成的False，不是多卡训练，是在aistudio线上环境

**Comment by Fauny** [comment]
> use_process是设置成的False，不是多卡训练，是在aistudio线上环境

遇到同样问题，请问解决了吗
