### ISSUE TITLE
需要对模型评估时，可视化PR曲线、ROC曲线、想请问该如何读取TP、FP、FN、TN这几个的数值呢？

### ISSUE THREAD

**Issue by baiwei-yndx** [PaddlePaddle/PaddleDetection#1766]
使用环境 AI Studio
使用项目：目标检测paddledetection
使用yolov3_mobilenet_v3检测COCO数据集（1个类别）
cuda：10.0
paddle：1.84

需要对模型评估时，可视化PR曲线、ROC曲线、想请问该如何读取TP、FP、FN、TN这几个的数值呢？还是用的是其他形式？
   
![image](https://user-images.githubusercontent.com/55337927/100328154-2b0b5780-3007-11eb-9ff7-eb1af9308735.png)
这图片是VisualDL2.0--基于「手写数字识别」模型的全功能展示中的效果，显示有TP、FP、FN、TN这几个数值，但没能理解这几个数值是如何读取的？

希望回复感谢！

**Comment by yghstill** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/ppdet/utils/coco_eval.py#L247  在这个之后可以加如下代码，先供参考，近一周PaddleDetection会集成绘制PR曲线功能。
```python           
def draw_pr_curve(precision, recall, iou=0.5, out_dir='pr_curve', file_name='precision_recall_curve.jpg'):
    if not os.path.exists(out_dir):
        os.makedirs(out_dir)
    output_path = os.path.join(out_dir, file_name)
    try:
        import matplotlib.pyplot as plt
    except Exception as e:
        logger.warn('Matplotlib not found, plaese install matplotlib. for example: `pip install matplotlib`.')
        raise e
    plt.figure('P-R Curve')
    plt.title('Precision/Recall Curve(IoU={})'.format(iou))
    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.grid(True)
    plt.plot(recall, precision)
    plt.savefig(output_path)

coco_eval.evaluate()
coco_eval.accumulate()
coco_eval.summarize()
    # Compute per-category AP and PR curve
try:
    from terminaltables import AsciiTable
except Exception as e:
    logger.warn('terminaltables not found, plaese install terminaltables. for example: `pip install terminaltables`.')
    raise e
precisions = coco_eval.eval['precision']
# precision: (iou, recall, cls, area range, max dets)
assert len(self.cat_ids) == precisions.shape[2]

results_per_category = []
for idx, catId in enumerate(self.cat_ids):
nm = self.coco.loadCats(catId)[0]
precision = precisions[:, :, idx, 0, -1]
precision = precision[precision > -1]
if precision.size:
    ap = np.mean(precision)
    else:
        ap = float('nan')
    results_per_category.append(
        (f'{nm["name"]}', f'{float(ap):0.3f}'))
    pr_array = precisions[0, :, idx, 0, 2]
    draw_pr_curve(pr_array[1],
                    pr_array[0],
                    out_dir=style[i]+'_pr_curve',
                    file_name='{}_precision_recall_curve.jpg'.format(nm["name"])) 
```

**Comment by Lxiaom123** [comment]
@yghstill 加了您所写的代码后，问题如下：
![image](https://user-images.githubusercontent.com/66930694/102218714-5c49ba00-3f19-11eb-9599-3d0ed9dc5760.png)
这是加的代码的位置
![image](https://user-images.githubusercontent.com/66930694/102219004-d4b07b00-3f19-11eb-8d89-3ce34b17141a.png)
![image](https://user-images.githubusercontent.com/66930694/102219047-e2660080-3f19-11eb-95ce-4736d31f1c57.png)

**Comment by LLeeSG** [comment]
> @yghstill 加了您所写的代码后，问题如下：
> ![image](https://user-images.githubusercontent.com/66930694/102218714-5c49ba00-3f19-11eb-9599-3d0ed9dc5760.png)
> 这是加的代码的位置
> ![image](https://user-images.githubusercontent.com/66930694/102219004-d4b07b00-3f19-11eb-8d89-3ce34b17141a.png)
> ![image](https://user-images.githubusercontent.com/66930694/102219047-e2660080-3f19-11eb-95ce-4736d31f1c57.png)

u can try this：
`    try:
        import matplotlib.pyplot as plt
    except Exception as e:
        logger.warn('Matplotlib not found, plaese install matplotlib. for example: `pip install matplotlib`.')
        raise e

    precisions = coco_eval.eval['precision']
    assert len(coco_gt.cats) == precisions.shape[2]

    output_dir = root_dir+'\\pr_curve'
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)  

    results_per_category = []
    x = np.arange(0.0, 1.01, 0.01)
    for idx, catId in enumerate(coco_gt.cats):
        nm = coco_gt.loadCats(catId)[0]
        precision = precisions[:, :, idx, 0, -1]
        precision = precision[precision > -1]
        if precision.size:
            ap = np.mean(precision[0:100])
        else:
            ap = float('nan')
        results_per_category.append((f'{nm["name"]}', f'{float(ap):0.3f}'))

        pr_array_50 = precisions[0, :, idx, 0, 2]
        pr_array_70 = precisions[4, :, idx, 0, 2]
        pr_array_90 = precisions[8, :, idx, 0, 2]

        file_name='{}_precision_recall_curve.jpg'.format(nm["name"])
        plt.figure(os.path.splitext(file_name)[0])
        plt.title(os.path.splitext(file_name)[0])
        plt.xlabel('Recall')
        plt.ylabel('Precision')
        plt.grid(True)
        plt.plot(x, pr_array_50, 'b-', label='IoU=0.5')
        plt.plot(x, pr_array_70, 'c-', label='IoU=0.7')
        plt.plot(x, pr_array_90, 'y-', label='IoU=0.9')
        plt.legend(loc='upper right')
        
        output_path = os.path.join(output_dir, file_name)
        plt.savefig(output_path)`

**Comment by LLeeSG** [comment]
> @yghstill 加了您所写的代码后，问题如下：
> ![image](https://user-images.githubusercontent.com/66930694/102218714-5c49ba00-3f19-11eb-9599-3d0ed9dc5760.png)
> 这是加的代码的位置
> ![image](https://user-images.githubusercontent.com/66930694/102219004-d4b07b00-3f19-11eb-8d89-3ce34b17141a.png)
> ![image](https://user-images.githubusercontent.com/66930694/102219047-e2660080-3f19-11eb-95ce-4736d31f1c57.png)

for循环的结构体要缩进。
另外self的错误可用coco_gt代替

**Comment by qingqing01** [comment]
最新的动态图也已经提供支持~

**Comment by weiluonika** [comment]
我也想问下 怎末读取TP、FP、FN、TN这几个的数值  我使用的是PaddleDetection2.4版本 如何开启这几个数据 呢？
