### ISSUE TITLE
部署solov2服务端时，报 Operator bilinear_interp_v2 has not been registered错误

### ISSUE THREAD

**Issue by TongHengcheng** [PaddlePaddle/PaddleDetection#1767]
我在服务器上部署solov2模型时，启动服务时显示bilinear_interp_v2这个算子未被注册，请问这个该如何处理？

![image](https://user-images.githubusercontent.com/35362026/100332413-55134880-300c-11eb-9b96-0656c877cab8.png)

**Comment by yghstill** [comment]
@TongHengcheng 你的预测库是什么版本？

**Comment by TongHengcheng** [comment]
是这样的，我是在服务器上部署serving，使用的是paddle_serving_server, 我下载的是最新的paddledetection, 并将paddlepaddle更新到了2.0.0rc.环境配置如下：
![image](https://user-images.githubusercontent.com/35362026/100341498-96f5bc00-3017-11eb-8085-b1209d294846.png)

**Comment by wangjiawei04** [comment]
现在Serving用的还是1.8.4的预测库，我今晚推一个版本上去。
预计明天就可以用，如果测试没问题的话，我还会再更新一下。

**Comment by TongHengcheng** [comment]
好的，谢谢。

**Comment by wangjiawei04** [comment]
> 示bilinear

问下你的环境是什么样的 py2 py3 cuda9/10 还有cudnn7 大概是什么样的组合
我这里代码合入了 我单独编译一个包给你。

**Comment by TongHengcheng** [comment]
好的，我看下
python 3.6
CUDA 10.0
cudnn 7.6.5
