### ISSUE TITLE
在VOC数据集上的mAP问题

### ISSUE THREAD

**Issue by ppy2017** [PaddlePaddle/PaddleDetection#1771]
我想问一下有人测试过在VOC07上的mAP吗

**Comment by heavengate** [comment]
PaddleDetection里voc数据集就是选取的VOC2007 test，对应数据集文件`VOCtest_06-Nov-2007.tar`

**Comment by ppy2017** [comment]
> PaddleDetection里voc数据集就是选取的VOC2007 test，对应数据集文件`VOCtest_06-Nov-2007.tar`

但是我好像看到给出来的数据都是COCO数据集上的，不知有在VOC数据集上的map吗

**Comment by qingqing01** [comment]
有实现VOC的mAP计算，使用VOC数据格式即可
