### ISSUE TITLE
单机多卡训练报错

### ISSUE THREAD

**Issue by CoderChen01** [PaddlePaddle/PaddleDetection#1775]
W1128 08:53:27.593163 27220 init.cc:234] *** Aborted at 1606524807 (unix time) try "date -d @1606524807" if you are using GNU date ***
W1128 08:53:27.593166 27219 init.cc:234] *** Aborted at 1606524807 (unix time) try "date -d @1606524807" if you are using GNU date ***
W1128 08:53:27.594600 27220 init.cc:234] PC: @                0x0 (unknown)
W1128 08:53:27.594704 27219 init.cc:234] PC: @                0x0 (unknown)
W1128 08:53:27.594719 27220 init.cc:234] *** SIGBUS (@0x7f8261c6b000) received by PID 27220 (TID 0x7f844423e740) from PID 1640411136; stack trace: ***
W1128 08:53:27.594800 27219 init.cc:234] *** SIGBUS (@0x7f60a88fd000) received by PID 27219 (TID 0x7f62bf9dd740) from PID 18446744072242581504; stack trace: ***
W1128 08:53:27.595997 27220 init.cc:234]     @     0x7f8443e1a980 (unknown)
W1128 08:53:27.596196 27219 init.cc:234]     @     0x7f62bf5b9980 (unknown)
W1128 08:53:27.597309 27220 init.cc:234]     @     0x7f8443ba5e6d (unknown)
W1128 08:53:27.597599 27219 init.cc:234]     @     0x7f62bf344e6d (unknown)
W1128 08:53:27.598558 27220 init.cc:234]     @     0x7f8444058630 ffi_call_unix64
W1128 08:53:27.598954 27219 init.cc:234]     @     0x7f62bf7f7630 ffi_call_unix64
W1128 08:53:27.599799 27220 init.cc:234]     @     0x7f8444057fed ffi_call
W1128 08:53:27.600333 27219 init.cc:234]     @     0x7f62bf7f6fed ffi_call
W1128 08:53:27.601042 27220 init.cc:234]     @     0x7f8442e7201e _ctypes_callproc
W1128 08:53:27.601668 27219 init.cc:234]     @     0x7f62be61101e _ctypes_callproc
W1128 08:53:27.602280 27220 init.cc:234]     @     0x7f8442e72a54 PyCFuncPtr_call
W1128 08:53:27.602699 27220 init.cc:234]     @     0x55a2f4f512db _PyObject_FastCallKeywords
W1128 08:53:27.603013 27219 init.cc:234]     @     0x7f62be611a54 PyCFuncPtr_call
W1128 08:53:27.603127 27220 init.cc:234]     @     0x55a2f4fa3a39 _PyEval_EvalFrameDefault
W1128 08:53:27.603413 27219 init.cc:234]     @     0x55af52fb22db _PyObject_FastCallKeywords
W1128 08:53:27.603487 27220 init.cc:234]     @     0x55a2f4f3c02b _PyFunction_FastCallKeywords
W1128 08:53:27.603832 27219 init.cc:234]     @     0x55af53004a39 _PyEval_EvalFrameDefault
W1128 08:53:27.603901 27220 init.cc:234]     @     0x55a2f4f9eac6 _PyEval_EvalFrameDefault
W1128 08:53:27.604193 27219 init.cc:234]     @     0x55af52f9d02b _PyFunction_FastCallKeywords
W1128 08:53:27.604264 27220 init.cc:234]     @     0x55a2f4f3c02b _PyFunction_FastCallKeywords
W1128 08:53:27.604614 27219 init.cc:234]     @     0x55af52fffac6 _PyEval_EvalFrameDefault
W1128 08:53:27.604678 27220 init.cc:234]     @     0x55a2f4f9eac6 _PyEval_EvalFrameDefault
W1128 08:53:27.604976 27219 init.cc:234]     @     0x55af52f9d02b _PyFunction_FastCallKeywords
W1128 08:53:27.605036 27220 init.cc:234]     @     0x55a2f4f3c02b _PyFunction_FastCallKeywords
W1128 08:53:27.605391 27219 init.cc:234]     @     0x55af52fffac6 _PyEval_EvalFrameDefault
W1128 08:53:27.605449 27220 init.cc:234]     @     0x55a2f4f9ed40 _PyEval_EvalFrameDefault
W1128 08:53:27.605751 27219 init.cc:234]     @     0x55af52f9d02b _PyFunction_FastCallKeywords
W1128 08:53:27.605832 27220 init.cc:234]     @     0x55a2f4ee8389 _PyEval_EvalCodeWithName
W1128 08:53:27.606165 27219 init.cc:234]     @     0x55af52fffd40 _PyEval_EvalFrameDefault
W1128 08:53:27.606220 27220 init.cc:234]     @     0x55a2f4ee96ef _PyFunction_FastCallDict
W1128 08:53:27.606549 27219 init.cc:234]     @     0x55af52f49389 _PyEval_EvalCodeWithName
W1128 08:53:27.606596 27220 init.cc:234]     @     0x55a2f4f08a73 _PyObject_Call_Prepend
W1128 08:53:27.606806 27220 init.cc:234]     @     0x55a2f4f501ba slot_tp_init
W1128 08:53:27.606937 27219 init.cc:234]     @     0x55af52f4a6ef _PyFunction_FastCallDict
W1128 08:53:27.607197 27220 init.cc:234]     @     0x55a2f4f50f78 _PyObject_FastCallKeywords
W1128 08:53:27.607319 27219 init.cc:234]     @     0x55af52f69a73 _PyObject_Call_Prepend
W1128 08:53:27.607528 27219 init.cc:234]     @     0x55af52fb11ba slot_tp_init
W1128 08:53:27.607612 27220 init.cc:234]     @     0x55a2f4fa3ebb _PyEval_EvalFrameDefault
W1128 08:53:27.607915 27219 init.cc:234]     @     0x55af52fb1f78 _PyObject_FastCallKeywords
W1128 08:53:27.607995 27220 init.cc:234]     @     0x55a2f4ee866a _PyEval_EvalCodeWithName
W1128 08:53:27.608330 27219 init.cc:234]     @     0x55af53004ebb _PyEval_EvalFrameDefault
W1128 08:53:27.608381 27220 init.cc:234]     @     0x55a2f4ee96ef _PyFunction_FastCallDict
W1128 08:53:27.608713 27219 init.cc:234]     @     0x55af52f4966a _PyEval_EvalCodeWithName
W1128 08:53:27.608757 27220 init.cc:234]     @     0x55a2f4f08a73 _PyObject_Call_Prepend
W1128 08:53:27.608964 27220 init.cc:234]     @     0x55a2f4f501ba slot_tp_init
W1128 08:53:27.609103 27219 init.cc:234]     @     0x55af52f4a6ef _PyFunction_FastCallDict
W1128 08:53:27.609354 27220 init.cc:234]     @     0x55a2f4f50f78 _PyObject_FastCallKeywords
W1128 08:53:27.609483 27219 init.cc:234]     @     0x55af52f69a73 _PyObject_Call_Prepend
W1128 08:53:27.609691 27219 init.cc:234]     @     0x55af52fb11ba slot_tp_init
W1128 08:53:27.609768 27220 init.cc:234]     @     0x55a2f4fa3ebb _PyEval_EvalFrameDefault
W1128 08:53:27.610078 27219 init.cc:234]     @     0x55af52fb1f78 _PyObject_FastCallKeywords
W1128 08:53:27.610127 27220 init.cc:234]     @     0x55a2f4f3c02b _PyFunction_FastCallKeywords
W1128 08:53:27.610493 27219 init.cc:234]     @     0x55af53004ebb _PyEval_EvalFrameDefault
W1128 08:53:27.610543 27220 init.cc:234]     @     0x55a2f4f9ed40 _PyEval_EvalFrameDefault
W1128 08:53:27.610852 27219 init.cc:234]     @     0x55af52f9d02b _PyFunction_FastCallKeywords
W1128 08:53:27.610924 27220 init.cc:234]     @     0x55a2f4ee8389 _PyEval_EvalCodeWithName
W1128 08:53:27.611274 27219 init.cc:234]     @     0x55af52fffd40 _PyEval_EvalFrameDefault
W1128 08:53:27.611315 27220 init.cc:234]     @     0x55a2f4ee94c5 _PyFunction_FastCallDict
W1128 08:53:27.611658 27219 init.cc:234]     @     0x55af52f49389 _PyEval_EvalCodeWithName
W1128 08:53:27.611693 27220 init.cc:234]     @     0x55a2f4f08aee _PyObject_Call_Prepend
W1128 08:53:27.611901 27220 init.cc:234]     @     0x55a2f4f501ba slot_tp_init
W1128 08:53:27.612046 27219 init.cc:234]     @     0x55af52f4a4c5 _PyFunction_FastCallDict
W1128 08:53:27.612426 27219 init.cc:234]     @     0x55af52f69aee _PyObject_Call_Prepend
W1128 08:53:27.612641 27219 init.cc:234]     @     0x55af52fb11ba slot_tp_init
INFO 2020-11-28 08:53:31,753 utils.py:269] terminate all the procs
ERROR 2020-11-28 08:53:31,754 utils.py:413] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2020-11-28 08:53:34,757 utils.py:269] terminate all the procs

**Comment by CoderChen01** [comment]
python -m paddle.distributed.launch --selected_gpus 0,1 tools/train_multi_machine.py -c myconfigs/yolov3_mobilenet_v1_failure.yml

**Comment by wangxinxin08** [comment]
> python -m paddle.distributed.launch --selected_gpus 0,1 tools/train_multi_machine.py -c myconfigs/yolov3_mobilenet_v1_failure.yml

单机多卡请使用train.py就可以了
`python -m paddle.distributed.launch --selected_gpus 0,1 tools/train.py -c myconfigs/yolov3_mobilenet_v1_failure.yml`

**Comment by CoderChen01** [comment]
依然报错
-----------  Configuration Arguments -----------
cluster_node_ips: 127.0.0.1
log_dir: None
log_level: 20
node_ip: 127.0.0.1
print_config: True
selected_gpus: 0,1
started_port: None
training_script: tools/train.py
training_script_args: ['-c', 'myconfigs/yolov3_mobilenet_v1_failure.yml', '--eval', '--use_vdl', 'True', '--vdl_log_dir', 'vdl_log_dir/scalar/']
use_paddlecloud: False
------------------------------------------------
INFO 2020-11-30 13:01:37,964 launch.py:210] get cluster from args:job_server:None pods:["rank:0 id:None addr:127.0.0.1 port:None visible_gpu:[] trainers:['gpu:[0] endpoint:127.0.0.1:33413 rank:0', 'gpu:[1] endpoint:127.0.0.1:55183 rank:1']"] job_stage_flag:None hdfs:None
INFO 2020-11-30 13:01:37,964 utils.py:367] start trainer proc:['/home/xxx/.conda/envs/paddle-detection/bin/python', '-u', 'tools/train.py', '-c', 'myconfigs/yolov3_mobilenet_v1_failure.yml', '--eval', '--use_vdl', 'True', '--vdl_log_dir', 'vdl_log_dir/scalar/'] env:{'FLAGS_selected_gpus': '0', 'PADDLE_TRAINER_ID': '0', 'PADDLE_CURRENT_ENDPOINT': '127.0.0.1:33413', 'PADDLE_TRAINERS_NUM': '2', 'PADDLE_TRAINER_ENDPOINTS': '127.0.0.1:33413,127.0.0.1:55183'}
INFO 2020-11-30 13:01:37,970 utils.py:367] start trainer proc:['/home/xxx/.conda/envs/paddle-detection/bin/python', '-u', 'tools/train.py', '-c', 'myconfigs/yolov3_mobilenet_v1_failure.yml', '--eval', '--use_vdl', 'True', '--vdl_log_dir', 'vdl_log_dir/scalar/'] env:{'FLAGS_selected_gpus': '1', 'PADDLE_TRAINER_ID': '1', 'PADDLE_CURRENT_ENDPOINT': '127.0.0.1:55183', 'PADDLE_TRAINERS_NUM': '2', 'PADDLE_TRAINER_ENDPOINTS': '127.0.0.1:33413,127.0.0.1:55183'}
2020-11-30 13:01:39,196-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
2020-11-30 13:01:39,199-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
2020-11-30 13:01:39,653-INFO: places would be ommited when DataLoader is not iterable
2020-11-30 13:01:39,653-INFO: places would be ommited when DataLoader is not iterable


API is deprecated since 2.0.0 Please use FleetAPI instead.
WIKI: https://github.com/PaddlePaddle/Fleet/blob/develop/markdown_doc/transpiler

        


API is deprecated since 2.0.0 Please use FleetAPI instead.
WIKI: https://github.com/PaddlePaddle/Fleet/blob/develop/markdown_doc/transpiler

        
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:55183']
W1130 13:01:39.686645  4279 device_context.cc:252] Please NOTE: device: 1, CUDA Capability: 52, Driver API Version: 10.0, Runtime API Version: 10.0
W1130 13:01:39.689275  4279 device_context.cc:260] device: 1, cuDNN Version: 7.6.
I1130 13:01:40.842792  4303 grpc_server.cc:477] Server listening on 127.0.0.1:55183 successful, selected port: 55183
W1130 13:01:42.699640  4278 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 52, Driver API Version: 10.0, Runtime API Version: 10.0
W1130 13:01:42.702612  4278 device_context.cc:260] device: 0, cuDNN Version: 7.6.
W1130 13:01:46.056417  4278 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1130 13:01:46.056417  4279 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1130 13:01:46.056445  4278 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1130 13:01:46.056447  4279 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1130 13:01:46.056460  4278 init.cc:231] The detail failure signal is:

W1130 13:01:46.056461  4279 init.cc:231] The detail failure signal is:

W1130 13:01:46.056466  4278 init.cc:234] *** Aborted at 1606712506 (unix time) try "date -d @1606712506" if you are using GNU date ***
W1130 13:01:46.056468  4279 init.cc:234] *** Aborted at 1606712506 (unix time) try "date -d @1606712506" if you are using GNU date ***
W1130 13:01:46.057921  4279 init.cc:234] PC: @                0x0 (unknown)
W1130 13:01:46.058013  4278 init.cc:234] PC: @                0x0 (unknown)
W1130 13:01:46.058066  4279 init.cc:234] *** SIGBUS (@0x7f8f0142f000) received by PID 4279 (TID 0x7f90e8232740) from PID 21164032; stack trace: ***
W1130 13:01:46.058110  4278 init.cc:234] *** SIGBUS (@0x7f646d139000) received by PID 4278 (TID 0x7f66819db740) from PID 1829998592; stack trace: ***
W1130 13:01:46.059413  4279 init.cc:234]     @     0x7f90e7e0e980 (unknown)
W1130 13:01:46.059533  4278 init.cc:234]     @     0x7f66815b7980 (unknown)
W1130 13:01:46.060776  4279 init.cc:234]     @     0x7f90e7b99e6d (unknown)
W1130 13:01:46.060942  4278 init.cc:234]     @     0x7f6681342e6d (unknown)
W1130 13:01:46.062063  4279 init.cc:234]     @     0x7f90e804c630 ffi_call_unix64
W1130 13:01:46.062292  4278 init.cc:234]     @     0x7f66817f5630 ffi_call_unix64
W1130 13:01:46.063405  4279 init.cc:234]     @     0x7f90e804bfed ffi_call
W1130 13:01:46.063707  4278 init.cc:234]     @     0x7f66817f4fed ffi_call
W1130 13:01:46.064669  4279 init.cc:234]     @     0x7f90e6e6601e _ctypes_callproc
W1130 13:01:46.065032  4278 init.cc:234]     @     0x7f668060f01e _ctypes_callproc
W1130 13:01:46.065929  4279 init.cc:234]     @     0x7f90e6e66a54 PyCFuncPtr_call
W1130 13:01:46.066361  4278 init.cc:234]     @     0x7f668060fa54 PyCFuncPtr_call
W1130 13:01:46.066387  4279 init.cc:234]     @     0x55941db0f2db _PyObject_FastCallKeywords
W1130 13:01:46.066771  4278 init.cc:234]     @     0x55629a51b2db _PyObject_FastCallKeywords
W1130 13:01:46.066828  4279 init.cc:234]     @     0x55941db61a39 _PyEval_EvalFrameDefault
W1130 13:01:46.067193  4278 init.cc:234]     @     0x55629a56da39 _PyEval_EvalFrameDefault
W1130 13:01:46.067214  4279 init.cc:234]     @     0x55941dafa02b _PyFunction_FastCallKeywords
W1130 13:01:46.067555  4278 init.cc:234]     @     0x55629a50602b _PyFunction_FastCallKeywords
W1130 13:01:46.067659  4279 init.cc:234]     @     0x55941db5cac6 _PyEval_EvalFrameDefault
W1130 13:01:46.067970  4278 init.cc:234]     @     0x55629a568ac6 _PyEval_EvalFrameDefault
W1130 13:01:46.068048  4279 init.cc:234]     @     0x55941dafa02b _PyFunction_FastCallKeywords
W1130 13:01:46.068334  4278 init.cc:234]     @     0x55629a50602b _PyFunction_FastCallKeywords
W1130 13:01:46.068490  4279 init.cc:234]     @     0x55941db5cac6 _PyEval_EvalFrameDefault
W1130 13:01:46.068747  4278 init.cc:234]     @     0x55629a568ac6 _PyEval_EvalFrameDefault
W1130 13:01:46.068877  4279 init.cc:234]     @     0x55941dafa02b _PyFunction_FastCallKeywords
W1130 13:01:46.069108  4278 init.cc:234]     @     0x55629a50602b _PyFunction_FastCallKeywords
W1130 13:01:46.069321  4279 init.cc:234]     @     0x55941db5cd40 _PyEval_EvalFrameDefault
W1130 13:01:46.069521  4278 init.cc:234]     @     0x55629a568d40 _PyEval_EvalFrameDefault
W1130 13:01:46.069732  4279 init.cc:234]     @     0x55941daa6389 _PyEval_EvalCodeWithName
W1130 13:01:46.069905  4278 init.cc:234]     @     0x55629a4b2389 _PyEval_EvalCodeWithName
W1130 13:01:46.070148  4279 init.cc:234]     @     0x55941daa76ef _PyFunction_FastCallDict
W1130 13:01:46.070292  4278 init.cc:234]     @     0x55629a4b36ef _PyFunction_FastCallDict
W1130 13:01:46.070554  4279 init.cc:234]     @     0x55941dac6a73 _PyObject_Call_Prepend
W1130 13:01:46.070670  4278 init.cc:234]     @     0x55629a4d2a73 _PyObject_Call_Prepend
W1130 13:01:46.070791  4279 init.cc:234]     @     0x55941db0e1ba slot_tp_init
W1130 13:01:46.070878  4278 init.cc:234]     @     0x55629a51a1ba slot_tp_init
W1130 13:01:46.071209  4279 init.cc:234]     @     0x55941db0ef78 _PyObject_FastCallKeywords
W1130 13:01:46.071276  4278 init.cc:234]     @     0x55629a51af78 _PyObject_FastCallKeywords
W1130 13:01:46.071652  4279 init.cc:234]     @     0x55941db61ebb _PyEval_EvalFrameDefault
W1130 13:01:46.071697  4278 init.cc:234]     @     0x55629a56debb _PyEval_EvalFrameDefault
W1130 13:01:46.072064  4279 init.cc:234]     @     0x55941daa666a _PyEval_EvalCodeWithName
W1130 13:01:46.072082  4278 init.cc:234]     @     0x55629a4b266a _PyEval_EvalCodeWithName
W1130 13:01:46.072475  4279 init.cc:234]     @     0x55941daa76ef _PyFunction_FastCallDict
W1130 13:01:46.072481  4278 init.cc:234]     @     0x55629a4b36ef _PyFunction_FastCallDict
W1130 13:01:46.072862  4278 init.cc:234]     @     0x55629a4d2a73 _PyObject_Call_Prepend
W1130 13:01:46.072876  4279 init.cc:234]     @     0x55941dac6a73 _PyObject_Call_Prepend
W1130 13:01:46.073071  4278 init.cc:234]     @     0x55629a51a1ba slot_tp_init
W1130 13:01:46.073109  4279 init.cc:234]     @     0x55941db0e1ba slot_tp_init
W1130 13:01:46.073458  4278 init.cc:234]     @     0x55629a51af78 _PyObject_FastCallKeywords
W1130 13:01:46.073525  4279 init.cc:234]     @     0x55941db0ef78 _PyObject_FastCallKeywords
W1130 13:01:46.073873  4278 init.cc:234]     @     0x55629a56debb _PyEval_EvalFrameDefault
W1130 13:01:46.073968  4279 init.cc:234]     @     0x55941db61ebb _PyEval_EvalFrameDefault
W1130 13:01:46.074235  4278 init.cc:234]     @     0x55629a50602b _PyFunction_FastCallKeywords
W1130 13:01:46.074357  4279 init.cc:234]     @     0x55941dafa02b _PyFunction_FastCallKeywords
W1130 13:01:46.074651  4278 init.cc:234]     @     0x55629a568d40 _PyEval_EvalFrameDefault
W1130 13:01:46.074800  4279 init.cc:234]     @     0x55941db5cd40 _PyEval_EvalFrameDefault
W1130 13:01:46.075033  4278 init.cc:234]     @     0x55629a4b2389 _PyEval_EvalCodeWithName
W1130 13:01:46.075217  4279 init.cc:234]     @     0x55941daa6389 _PyEval_EvalCodeWithName
W1130 13:01:46.075424  4278 init.cc:234]     @     0x55629a4b34c5 _PyFunction_FastCallDict
W1130 13:01:46.075634  4279 init.cc:234]     @     0x55941daa74c5 _PyFunction_FastCallDict
W1130 13:01:46.075804  4278 init.cc:234]     @     0x55629a4d2aee _PyObject_Call_Prepend
W1130 13:01:46.076011  4278 init.cc:234]     @     0x55629a51a1ba slot_tp_init
W1130 13:01:46.076050  4279 init.cc:234]     @     0x55941dac6aee _PyObject_Call_Prepend
W1130 13:01:46.076319  4279 init.cc:234]     @     0x55941db0e1ba slot_tp_init
INFO 2020-11-30 13:01:49,988 utils.py:269] terminate all the procs
ERROR 2020-11-30 13:01:49,988 utils.py:413] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2020-11-30 13:01:52,991 utils.py:269] terminate all the procs

**Comment by MyGitHub-G** [comment]
请问这个问题解决了吗，我也报错ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.

**Comment by MyGitHub-G** [comment]
请问问题解决了吗，我也报错ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.

**Comment by GexLoong** [comment]
请问这个问题解决了吗，我也报错ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.

**Comment by LISIJIA0629** [comment]
> 请问这个问题解决了吗，我也报错ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
有解决吗！我也是兄弟
