### ISSUE TITLE
导出模型后运行PaddleDetection/deploy/python/infer.py后没有输出预测结果

### ISSUE THREAD

**Issue by May52** [PaddlePaddle/PaddleDetection#1776]
运行PaddleDetection-release-0.5/tools/infer.py 可以输出预测结果，但是使用tools/export_model.py导出模型后，运行deploy/python/infer.py后没有输出预测结果，请问是什么原因呢？部分程序运行结果如下：

![image](https://user-images.githubusercontent.com/52195642/100493436-cae4f480-3171-11eb-8485-8244c1b4b227.png)
![image](https://user-images.githubusercontent.com/52195642/100493441-d6382000-3171-11eb-9dc6-733584b2167f.png)
![image](https://user-images.githubusercontent.com/52195642/100493450-f071fe00-3171-11eb-9036-6dc34b2efd7d.png)
![image](https://user-images.githubusercontent.com/52195642/100493458-ff58b080-3171-11eb-9d44-dde3b787c77b.png)

!export CUDA_VISIBLE_DEVICES=0
!cd work/PaddleDetection &&  python deploy/python/infer.py --use_gpu=True --run_benchmark=True \
--image_file=dataset/voc/test/JPGImages/0650.jpg --model_dir=inference_model/yolov3_ghostnet_voc \
 --threshold=0.01   --output_dir=infer_outs
![image](https://user-images.githubusercontent.com/52195642/100493532-96256d00-3172-11eb-8176-e9e2e8cb68f7.png)

**Comment by jerrywgz** [comment]
run_benchmark开启是为了测试模型预测速度，不会对检测结果做可视化的后处理的。如果想看输出预测结果的话，不需要设置run_benchmark

**Comment by May52** [comment]
> run_benchmark开启是为了测试模型预测速度，不会对检测结果做可视化的后处理的。如果想看输出预测结果的话，不需要设置run_benchmark

您好，您说得对，不设置run_benchmark的话可以输出预测结果了，感谢您的回复！我还想问下，我用VOC数据集训练R-CNN模型(faster/cascade/libra_rcnn)后，使用tools/export_model.py导出R-CNN模型后，在分数阈值threshold相同的条件下预测同一张图片时，运行deploy/python/infer.py后输出的预测结果与运行tools/infer.py 输出的预测结果不一样，后者的预测结果更准确（测出目标个数更多），请问会是什么原因呢？

**Comment by qingqing01** [comment]
可以使用最新的版本测试看下
