### ISSUE TITLE
关于打印网络的输出Print的问题

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#178]
我在代码中加入mask_rcnn.py中加入

> spatial_scale = None
        if self.fpn is not None:
            body_feats, spatial_scale = self.fpn.get_output(body_feats)
        print("FPN网络输出的feature_map")
        fluid.layers.Print(body_feats)

出现错误信息

> FPN网络输出的feature_map
Traceback (most recent call last):
  File "train.py", line 342, in <module>
    main()
  File "train.py", line 130, in main
    train_fetches = model.train(feed_vars)
  File "/home/aistudio/work/ppdet/modeling/architectures/mask_rcnn.py", line 292, in train
    return self.build(feed_vars, 'train')
  File "/home/aistudio/work/ppdet/modeling/architectures/mask_rcnn.py", line 101, in build
    fluid.layers.Print(body_feats)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/control_flow.py", line 200, in Print
    helper = LayerHelper('print' + "_" + input.name, **locals())
AttributeError: 'collections.OrderedDict' object has no attribute 'name'

**Comment by shuxsu** [comment]
若直接使用print打印 则不报错 打印信息为

> FPN网络输出的feature_map
OrderedDict([('fpn_res5_sum_subsampled_2x', name: "fpn_res5_sum_subsampled_2x.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 256
      dims: -1
      dims: -1
    }
    lod_level: 0
  }
}
persistable: false
), ('fpn_res5_sum', name: "fpn_res5_sum.tmp_1"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 256
      dims: -1
      dims: -1
    }
    lod_level: 0
  }
}
persistable: false
), ('fpn_res4_sum', name: "fpn_res4_sum.tmp_1"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 256
      dims: -1
      dims: -1
    }
    lod_level: 0
  }
}
persistable: false
), ('fpn_res3_sum', name: "fpn_res3_sum.tmp_1"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 256
      dims: -1
      dims: -1
    }
    lod_level: 0
  }
}
persistable: false
), ('fpn_res2_sum', name: "fpn_res2_sum.tmp_1"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 256
      dims: -1
      dims: -1
    }
    lod_level: 0
  }
}
persistable: false
)])

**Comment by littletomatodonkey** [comment]
您好，body_feats是一个包含很多feature map的有序字典，不是一个Tensor，可以通过下面的方式查看body_feats中所有Tensor的信息：
```
for key in body_feats:
    fluid.layers.Print(body_feats[key], summarize=10)
```
summarize表示对于输入的Tensor，所打印的元素的数量（-1表示全部打印），也可以参考
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/Print_cn.html#print
