### ISSUE TITLE
ppyolo使用paddle-trt出现问题

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#1783]
ppyolo使用paddle-trt在jetson平台上cpp推理出现问题，没有框，全是标签。fluid模式检测正常。因为后面打算做一下量化，必须使用trt才能加速。

**Comment by qingqing01** [comment]
@liuhuiCNN  Please see this issue.

**Comment by liuhuiCNN** [comment]
您使用的paddle预测库是哪个版本呢？您可以从这里 [build_and_install_lib_cn](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html) 下载与您设备硬件软件环境一致的paddle预测库，再进行cpp部署。若环境不完全一样，您可以在您的环境上编译paddle，生成paddle预测库，再进行部署。
[Jetson_build](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/deploy/cpp/docs/Jetson_build.md) TX2 jetpack4.3 paddle 1.8.4预测库，预测ppyolo是正常的。

**Comment by JensenHJS** [comment]
1.8.4的预测库应该不支持MatrixNMS算子，我是jetpack4.2，paddle2.0预测库，然后fluid模式检测正常，trt模式检测有问题，如图所示。然后paddle-trt配置是没有问题的，因为之前mobilenet—yolo可以正常使用trt。
![0](https://user-images.githubusercontent.com/48740491/101602307-db7e5000-3a38-11eb-8ca8-8159f728ea94.jpg)
![1](https://user-images.githubusercontent.com/48740491/101602316-de794080-3a38-11eb-971a-d85bf6de9e66.jpg)

**Comment by thinkthinking** [comment]
你好，欢迎使用PaddleDetection v2.6，PP-YOLOE+支持trt推理，该issue暂时close，如果有需要可以reopen。
