### ISSUE TITLE
C++预测 检测框阈值传入

### ISSUE THREAD

**Issue by pele228** [PaddlePaddle/PaddleDetection#179]
你好，C++部署时通过配置文件.yaml来设置检测参数， 那么检测框阈值threshold该如何传入？现在给的yaml例子没有这个参数字段.

**Comment by qingqing01** [comment]
@pele228 C++部署数输出全量的bbox，用户可以拿到预测结果，再通过阈值过滤。

**Comment by pele228** [comment]
thx
