### ISSUE TITLE
Running on multiple CPU thread

### ISSUE THREAD

**Issue by athulvingt** [PaddlePaddle/PaddleDetection#1790]
While inferencing the models on a video it uses only 1 thread of my 16 thread CPU, Is there a way to make it utilise available threads.

**Comment by liuhuiCNN** [comment]
Thanks for your feedback.  Please refer  to [inference](https://www.paddlepaddle.org.cn/documentation/docs/en/advanced_guide/inference_deployment/inference/native_infer_en.html), and you can see this multi-thread infer [demo](https://paddle-inference-dist.bj.bcebos.com/tensorrt_test/paddle_inference_sample_v1.7.tar.gz).

**Comment by athulvingt** [comment]
I dont know c++, is there any python implementation for the same? @liuhuiCNN 
Thank you for your response

**Comment by athulvingt** [comment]
what changes can i make in this code to make the program use multiple CPU threads (without GPU)
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/deploy/python/infer.py

**Comment by jerrywgz** [comment]
Now you could set cpu_threads in v2.1 to enable multiple CPU threads https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/python/utils.py#L77
