### ISSUE TITLE
nanopc t4上（rk3399）部署mobilenetv3_yolov3遇到内存不足的问题

### ISSUE THREAD

**Issue by daiyuanm** [PaddlePaddle/PaddleDetection#1793]
在nano pc t4(rk3399)上用mobilenetv3_yolov3进行目标检测，在预测的时候会出现内存不足的情况，但是后台却显示内存没有用起来，有大佬碰到过这种问题吗。
代码是参照给的[安卓demo](https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/master/PaddleLite-android-demo/yolo_detection_demo/app/src/main/cpp/Pipeline.cc)写的用于arm的代码。
所用的mobilenetv3_yolov3的模型在PC上可以进行检测，之后用opt转换成nb格式，使用自己所写代码就会遇到下面的问题：
`[W 12/ 1 10:47:50.325 ...e-Lite/lite/model_parser/model_parser.cc:811 LoadModelNaiveFromFile] warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version. version of opt:v2.6.1 version of current Paddle-Lite:0d53f5af [F 12/ 1 10:47:50.970 ...odel_parser/naive_buffer/naive_buffer.cc:30 Consume] Check failed: bytes <= free_size(): 18874368!<=16687912 No free memory of 18874368, should Require the memory first ./run.sh: line 16: 29699 Aborted (core dumped)`

**Comment by willthefrog** [comment]
可能存在兼容性问题，建议先试试用相同版本的opt和benchmark工具跑下，如果能跑再试试运行你的代码

**Comment by daiyuanm** [comment]
> 可能存在兼容性问题，建议先试试用相同版本的opt和benchmark工具跑下，如果能跑再试试运行你的代码

你好，请问ARMLinux预测库最新的版本应该适配哪个版本的opt以及pplite（2.6.3？）？我们现在用的是v2.6.1的opt，刚刚尝试将ARMLinux预测库更新到最新遇到segmentation fault问题。这个问题我们之前在跑ssdlite_mobilenetv3的图像检测demo时遇到过，最后通过统一opt和pplite到2.6.1版本解决。

**Comment by willthefrog** [comment]
相同版本即可，可以先用lite的benchmark工具跑下，看下是lite版本的原因还是你自己的code的问题。

**Comment by daiyuanm** [comment]
> 相同版本即可，可以先用lite的benchmark工具跑下，看下是lite版本的原因还是你自己的code的问题。
目前能够使用mobilenetv3_yolov3在nanpct4上进行检测了，但是速度实在太慢...一张640的图需要大概8秒

**Comment by daiyuanm** [comment]
> 相同版本即可，可以先用lite的benchmark工具跑下，看下是lite版本的原因还是你自己的code的问题。



目前能够使用mobilenetv3_yolov3在nanpct4上进行检测了，但是速度实在太慢...一张640的图需要大概8秒
