### ISSUE TITLE
检测量化的模块找不到相关文档

### ISSUE THREAD

**Issue by Ricardozzf** [PaddlePaddle/PaddleDetection#1797]
我看检测量化的脚本里有QuantizationTransformPass，QuantizationFreezePass这些模块，但没有匹配的文档，这是老版本的接口吗？有对应的文档说明吗？
https://github.com/PaddlePaddle/PaddleDetection/blob/47741382cf15eda852fefdada6ce83ef86350af6/slim/quantization/freeze.py#L31

**Comment by willthefrog** [comment]
参看[这里](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/quantization/quantization_pass.py#L1043)

**Comment by Ricardozzf** [comment]
> 参看[这里](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/contrib/slim/quantization/quantization_pass.py#L1043)

这个接口是被弃用了吗，我在官方教程中没有看见类似的写法，一些旧code是这种写法

**Comment by willthefrog** [comment]
fluid的接口应该会逐步升级为新接口。以官方教程为准。
