### ISSUE TITLE
cpp部署配置都完成后，前向推理./build/main --mode_dir=xxxxx --image_path=xxx过程报错，file too short

### ISSUE THREAD

**Issue by michaelfu123** [PaddlePaddle/PaddleDetection#1799]
![image](https://user-images.githubusercontent.com/38556449/100852987-30aee480-34c2-11eb-9745-605c11b52ee6.png)

**Comment by willthefrog** [comment]
看样子是opencv的库有问题。

**Comment by michaelfu123** [comment]
@willthefrog 该怎么解决呢

**Comment by liuhuiCNN** [comment]
> @willthefrog 该怎么解决呢
您在使用Paddle C++预测库进行封装部署时，需要使用跟Paddle C++预测库使用的Opencv库版本保持一致。上述错误应该是Opencv库版本不一致导致的。

**Comment by heavengate** [comment]
鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen这个issue~
