### ISSUE TITLE
What's expected performance float32/float16?

### ISSUE THREAD

**Issue by gfilipekint** [PaddlePaddle/PaddleDetection#180]
Hi. I managed to run mask_rcnn_resnet50_1 with both fp32 and fp16. I run it on Nvidia V100 card, 16GB version. I'm running on a single card.

I get around 4 images per second using fp32, and when I switch to fp16 (by adding `--fp16`) the performance does not increase, it's still around 4 images per second.

Is this expected?

I do everything following your readmes, so using coco dataset you linked, your pretrained rn50 weights and so on...

For the sake of completeness, here is the command I used for fp32:
```
python3 train.py -c mask_rcnn_r50_1x.yml -o max_iters=200 use_gpu=True
```

and here is the version for fp16 (I changed affinity to bn in the config)
```
python3 train.py -c mask_rcnn_r50_1x.yml -o max_iters=200 use_gpu=True --fp16
```

**Comment by willthefrog** [comment]
Unfortunately this seems to be the case at present, especially for the non-FPN models (batch size 1), however PaddlePaddle has been working on FP16 optimizations for sometime and is expected to see some speed up in near future. Also you may wanna try models that allow training with larger batch size  (e.g., models with FPN), our benchmark showed 10-30% speed up  depending architecture used.

**Comment by gfilipekint** [comment]
Ok, I will try the FPN version, thanks.

Also, great profile picture :)

**Comment by willthefrog** [comment]
Always a pleasure to meet a "Rick and Morty" fan! 😉
