### ISSUE TITLE
0.5分支。yolov3_darknet_voc_diouloss.yml 未改动相关代码，只改了默认配置为MultiClassDiouNMS

### ISSUE THREAD

**Issue by aboutmei** [PaddlePaddle/PaddleDetection#1802]
改动配置如下：
  nms: MultiClassDiouNMS
MultiClassDiouNMS:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    score_threshold: 0.01

W1203 02:19:20.694010 26611 operator.cc:187] py_func raises an exception pybind11::error_already_set, ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

At:
  <__array_function__ internals>(6): concatenate
  ///anaconda3/envs//lib/python3./site-packages/numpy/core/shape_base.py(344): hstack
  <__array_function__ internals>(6): hstack
PaddleDetection/ppdet/modeling/ops.py(781): _diou_nms
  /home//anaconda3/envs//lib/python3.7/site-packages/paddle/fluid/layers/nn.py(14302): __call__
F1203 02:19:20.694087 26611 exception_holder.h:37] std::exception caught, ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

At:
  <__array_function__ internals>(6): concatenate
  ///anaconda3/envs//lib/python3./site-packages/numpy/core/shape_base.py(344): hstack
  <__array_function__ internals>(6): hstack
 PaddleDetection/ppdet/modeling/ops.py(781): _diou_nms
  ///anaconda3/envs//lib/python3./site-packages/paddle/fluid/layers/nn.py(14302): __call__
*** Check failure stack trace: ***
    @     0x7fb7d2a0d83d  google::LogMessage::Fail()
    @     0x7fb7d2a112ec  google::LogMessage::SendToLog()
    @     0x7fb7d2a0d363  google::LogMessage::Flush()
    @     0x7fb7d2a127fe  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb7d5bd95d8  paddle::framework::details::ExceptionHolder::Catch()
    @     0x7fb7d5c76bfe  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
    @     0x7fb7d5c7459f  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
    @     0x7fb7d5c74864  _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
    @     0x7fb7d2a6b413  std::_Function_handler<>::_M_invoke()
    @     0x7fb7d2865107  std::__future_base::_State_base::_M_do_set()
    @     0x7fb8400bb827  __pthread_once_slow
    @     0x7fb7d5c70a32  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7fb7d2867564  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7fb8276c7421  execute_native_thread_routine_compat
    @     0x7fb8400b36db  start_thread
    @     0x7fb83fddca3f  clone
    @              (nil)  (unknown)
已放弃 (核心已转储)

**Comment by yghstill** [comment]
@aboutmei MultiClassDiouNMS这个API目前只在rcnn算法里适配了，YOLO系列算法暂不可用。

**Comment by aboutmei** [comment]
ok,谢谢。那细粒度损失是只有dioulossyolo 这个类可以用是吗？还是别的loss 都可以使用，像giouloss等？
