### ISSUE TITLE
问一下有无在遥感方面应用的demo或者项目？

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleDetection#1809]
问一下有无在遥感方面应用的demo或者项目？想把 PaddleDetection 在遥感方面应用一下，之前还没用过PaddleDetection

**Comment by qingqing01** [comment]
@iceriver97 

PaddleDetection中目前还没提供遥感里的数据例子，理论上，Dataset里适配下遥感数据，只是做矩形框检测的话，就可以用了。

旋转矩形框检测， 正在建设中。
