### ISSUE TITLE
目前PaddleDetection是否支持任意四边形或任意方向的目标检测？

### ISSUE THREAD

**Issue by xiulianzw** [PaddlePaddle/PaddleDetection#1810]
我看了一下PaddleDetection的数据说明，目前支持的数据类型都是COCO、Pascal VOC 和WIDER-FACE数据源，如果是带旋转角度的box或者是四个点的box，目前支持吗？

**Comment by yghstill** [comment]
@xiulianzw 旋转框的检测算法我们正在开发中，不久就会开源出来。

**Comment by xiulianzw** [comment]
期待你们的开源，辛苦了。
