### ISSUE TITLE
PaddleDetection 与 VisualDL 的集成度

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleDetection#1818]
1.PaddleDetection 在训练开始前可以使用 VisualDL 查看增强后的图片吗？

2.在训练过程中只添加了 VisualDL-Scalar 功能吗？有无类似 PaddleSeg ，在每次eval时，会展示预测结果的功能？

3.是否只集成了训练时 Scalar 没有其他的更多功能？

**Comment by heavengate** [comment]
当前是只支持scaler功能，感谢反馈，我们确认一下需求支持下其他功能

**Comment by qingqing01** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/1842 @iceriver97 增加这个功能，后续会加下文档

**Comment by iceriver97** [comment]
> #1842 @iceriver97 增加这个功能，后续会加下文档

已经改好了是吧，太速度了；最近正准备用 PaddleDetection 与 VisualDL 结合起来做项目；给你们的效率点个赞

**Comment by iceriver97** [comment]
> #1842 @iceriver97 增加这个功能，后续会加下文档

您好，此文档出来了吗？

**Comment by iceriver97** [comment]
VDL 的 PR Curve 功能有没有集成呢？感觉好像跟VDL有些重复，那边画PR曲线也是要重新计算一遍，既然检测任务的指标就是mAP, 那应该如何把VDL的功能加进去呢？就简单的重复计算吗?

**Comment by jerrywgz** [comment]
目前vdl pr曲线的功能已经集成至PaddleDetection release/2.0版本，欢迎使用～
