### ISSUE TITLE
请问mask_rcnn 支持paddle-tensorRT吗

### ISSUE THREAD

**Issue by shikeno** [PaddlePaddle/PaddleDetection#1819]
使用tools/export_model.py 导出的mask_rcnn_r50_1x 用tensorRT加载 解析模型会出错
![image](https://user-images.githubusercontent.com/44427541/101133727-4b10cb80-3644-11eb-9256-0c64620c7b3f.png)
使用环境：
paddle:1.8
tensorRT: 6.0.1.8
PaddleDetection: release/v0.5

**Comment by shikeno** [comment]
导出模型用的命令：
python tools/export_model.py --config=configs/mask_rcnn_r50_1x.yml

**Comment by heavengate** [comment]
使用TensorRT预测需要自行编译Paddle，编译时使用`-DTENSORRT_ROOT=`指定TensorRT路径带TensorRT编译，另外TensorRT版本最好使用TensorRT5
编译方法参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/fromsource.html

**Comment by shikeno** [comment]
> 使用TensorRT预测需要自行编译Paddle，编译时使用`-DTENSORRT_ROOT=`指定TensorRT路径带TensorRT编译，另外TensorRT版本最好使用TensorRT5
> 编译方法参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/fromsource.html

感谢回复。
上面的截图是已经使用paddle-trt的，报错在infer network add input image failed，是不是导出的模型有问题

**Comment by qingqing01** [comment]
@shikeno 请看下导出的配置中 TRT_MIN_SUBGRAPH 是多少？
