### ISSUE TITLE
res2net训练异常停止

### ISSUE THREAD

**Issue by XiaoWen-AI** [PaddlePaddle/PaddleDetection#1832]
用的这个模型mask_rcnn_res2net50_vd_26w_4s_fpn_dcnv2_1x.yml，每次都能正常跑几步，好好的就停止了，没有任何错误提示

**Comment by qingqing01** [comment]
@XiaoWen-AI  停止时是否有其他信息？ 给下训练环境信息，Paddle版本信息吧~

**Comment by XiaoWen-AI** [comment]
没有报任何错误信息，paddle1.8.5, paddledetection0.4, cuda10.1, visual studio2019， 不用res2net版本可以正常训练

**Comment by qingqing01** [comment]
由于时间太久，关闭此issue，有问题可以新提issue。
