### ISSUE TITLE
inference的CMakeList指定引用的protobuffer头文件和inference里自己的proto文件版本不兼容

### ISSUE THREAD

**Issue by FibonacciSun** [PaddlePaddle/PaddleDetection#184]
CMakeList去包 paddle推理库的protobuf头文件，这里是protobuffer 3 
 include_directories("${PADDLE_DIR}/third_party/install/protobuf/include")

而
utils/detection_result.proto
是probobuffer 2

**Comment by qingqing01** [comment]
@sjtubinlong 会改进下这些问题，多谢提出~
