### ISSUE TITLE
if isinstance(item, collections.Sequence) and len(item) == 0:在这卡住了

### ISSUE THREAD

**Issue by yiyueming** [PaddlePaddle/PaddleDetection#1844]
(paddle) E:\PaddleDetection-release-0.5>python tools/train.py -c configs/faster_rcnn_r50_1x.yml
E:\PaddleDetection-release-0.5\ppdet\core\workspace.py:118: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  isinstance(merge_dct[k], collections.Mapping)):
2020-12-08 15:04:22,232-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
W1208 15:04:22.382612  5348 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.2
W1208 15:04:22.443642  5348 device_context.cc:346] device: 0, cuDNN Version: 7.6.
2020-12-08 15:04:26,455-WARNING: variable file [ pre_weight/ResNet50_cos_pretrained/fc_0.w_0 pre_weight/ResNet50_cos_pretrained/fc_0.b_0 ] not used
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
W1208 15:04:27.265903  5348 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
E:\PaddleDetection-release-0.5\ppdet\data\reader.py:89: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(item, collections.Sequence) and len(item) == 0:

卡在这好久就不动了，怎么解决

**Comment by jerrywgz** [comment]
你的cuda版本是11吗？建议使用cuda9或者cuda10的版本 另外卡住的时候可以看下内存占用情况

**Comment by yiyueming** [comment]
我的是10.1，我安装的是rc2.0，然后我换成cpu版本也是卡在这里

**Comment by jerrywgz** [comment]
你训的是coco数据集吗，可以看下ppdet/data/source/coco.py里records的长度

**Comment by yiyueming** [comment]
对了，我刚刚看了下nvcc --version和nvidia-smi显示的cuda版本不一样，nvcc --version显示的是10.1，nvidia-smi显示的是11.1，这有影响吗

**Comment by yiyueming** [comment]
用的是coco数据集，你说records的长度怎么看

**Comment by jerrywgz** [comment]
> 对了，我刚刚看了下nvcc --version和nvidia-smi显示的cuda版本不一样，nvcc --version显示的是10.1，nvidia-smi显示的是11.1，这有影响吗

这个可能是有影响的，建议统一到10.1

**Comment by Lxiaom123** [comment]
@yiyueming 请问你的问题解决了吗？我用的AIStudio线上环境，也出现了这个问题

**Comment by DeniJsonC** [comment]
同样的问题 cpu训练 gpu都是一样 records里面长度等于训练集个数
