### ISSUE TITLE
关于objects365 预训练模型在推理过程中出现的问题

### ISSUE THREAD

**Issue by tianlanshidai** [PaddlePaddle/PaddleDetection#1847]
我按照 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/docs/featured_model/champion_model/CACascadeRCNN.md
中的说明，下载了模型，并使用如下脚本：
python tools/infer.py -c configs/obj365/cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas.yml -o weights=output/cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas_obj365 --infer_img=demo/000000014439.jpg

结果出现如下错误：

TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;W1208 19:54:17.704043 115502 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 35, Driver API Version: 10.1, Runtime API Version: 10.0
W1208 19:54:17.709694 115502 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2020-12-08 19:54:19,215-WARNING: output/cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas_obj365.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-12-08 19:54:20,770-INFO: Not found annotation file dataset/obj365/annotations/val.json, load coco17 categories.
2020-12-08 19:54:22,391-INFO: Infer iter 0
Traceback (most recent call last):
  File "tools/infer.py", line 271, in <module>
    main()
  File "tools/infer.py", line 194, in main
    bbox_results = bbox2out([res], clsid2catid, is_bbox_normalized)
  File "/data/wenzongzheng/PaddleDetection/ppdet/utils/coco_eval.py", line 315, in bbox2out
    catid = (clsid2catid[int(clsid)])
KeyError: 110

有没有遇到这样的问题，请问该如何解决呀

**Comment by jerrywgz** [comment]
想问下配置文件有修改吗

**Comment by tianlanshidai** [comment]
没有修改，用的里面给的配置文件，



---原始邮件---
发件人: "wangguanzhong"<notifications@github.com&gt;
发送时间: 2020年12月9日(周三) 上午9:56
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送: "tianlanshidai"<www.ecbt.com@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] 关于objects365 预训练模型在推理过程中出现的问题 (#1847)




 
想问下配置文件有修改吗

**Comment by tianlanshidai** [comment]
配置文件需要修改嘛



---原始邮件---
发件人: "wangguanzhong"<notifications@github.com&gt;
发送时间: 2020年12月9日(周三) 上午9:56
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送: "tianlanshidai"<www.ecbt.com@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] 关于objects365 预训练模型在推理过程中出现的问题 (#1847)




 
想问下配置文件有修改吗

**Comment by jerrywgz** [comment]
这里确实存在问题，我们尽快修复下

**Comment by tianlanshidai** [comment]
> 这里确实存在问题，我们尽快修复下

感谢，我在ppdet/utils/coco_eval.py 里面，把coco的类别标号全部换成了objects365的，可以推理了，其他问题暂时还没发现，感觉你们可以单独写一个obj_eval.py的脚本
