### ISSUE TITLE
关于SOLOv2的FPS问题，我在V100上测试无TensorRT，处理一帧就要1s左右，还不加后处理，什么原因啊，太慢了

### ISSUE THREAD

**Issue by Fei-dong** [PaddlePaddle/PaddleDetection#1850]

**Comment by yghstill** [comment]
设置`--use_gpu=True`了吗

**Comment by Fei-dong** [comment]
> 设置`--use_gpu=True`了吗

加了

**Comment by yghstill** [comment]
@Fei-dong 如果要测FPS，把https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/deploy/python/infer.py#L256-L257 这两行注释掉，由于现在segm类型是int32，不是uint8，所以从GPU拷贝至CPU耗时特别严重。
Paddle下tensor从GPU拷贝至CPU刚支持uint8，近期在Paddle 2.0.0.rc1版本会发布，之后测试就可以不需要注释这两行了。

**Comment by Fei-dong** [comment]
> @Fei-dong 如果要测FPS，把https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/deploy/python/infer.py#L256-L257 这两行注释掉，由于现在segm类型是int32，不是uint8，所以从GPU拷贝至CPU耗时特别严重。
> Paddle下tensor从GPU拷贝至CPU刚支持uint8，近期在Paddle 2.0.0.rc1版本会发布，之后测试就可以不需要注释这两行了。

好的，非常感谢，注释这两行的话，segm信息便不能获取了，确实是gpu到cpu耗时严重。

**Comment by Fei-dong** [comment]
> @Fei-dong 如果要测FPS，把https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/deploy/python/infer.py#L256-L257 这两行注释掉，由于现在segm类型是int32，不是uint8，所以从GPU拷贝至CPU耗时特别严重。
> Paddle下tensor从GPU拷贝至CPU刚支持uint8，近期在Paddle 2.0.0.rc1版本会发布，之后测试就可以不需要注释这两行了。

在segm类型是int32转成uint8，能解决GPU拷贝至CPU耗时特别严重的问题麽，大概能提速多少啊。

**Comment by Fei-dong** [comment]
> > @Fei-dong 如果要测FPS，把https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/deploy/python/infer.py#L256-L257 这两行注释掉，由于现在segm类型是int32，不是uint8，所以从GPU拷贝至CPU耗时特别严重。
> > Paddle下tensor从GPU拷贝至CPU刚支持uint8，近期在Paddle 2.0.0.rc1版本会发布，之后测试就可以不需要注释这两行了。
> 
> 好的，非常感谢，注释这两行的话，segm信息便不能获取了，确实是gpu到cpu耗时严重。
