### ISSUE TITLE
deploy/python/infer.py

### ISSUE THREAD

**Issue by gpsherry** [PaddlePaddle/PaddleDetection#1854]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/deploy/python/preprocess.py:109-115
resize 将短边补齐到长边一样，不合理，实测发现检测错误率明显增加。

**Comment by jerrywgz** [comment]
这里的后处理是为了支持tensort，因为tensorrt5不支持变长输入，所以需要在模型导出时指定image_shape,这种预处理确定有可能影响精度。如果不使用tensorrt的话可以不指定image_shape
