### ISSUE TITLE
自定义数据训练问题

### ISSUE THREAD

**Issue by jinxuan777** [PaddlePaddle/PaddleDetection#1863]
GPU以及CPU使用率为0，训练一直挂着
![image](https://user-images.githubusercontent.com/23650957/101749556-dab4ef00-3b08-11eb-94a9-2831e4b2c1c3.png)

**Comment by yghstill** [comment]
请详细描述一下自定义数据是voc还是coco格式呢？

**Comment by jinxuan777** [comment]
coco格式

**Comment by jinxuan777** [comment]
采样了其中一张图片格式如下：

**Comment by jinxuan777** [comment]
采样了一张图片格式如下：

**Comment by jinxuan777** [comment]
采样了一张图片格式如下：
{"licenses": [], "info": {}, "categories": [{"id": 1, "name": "logo", "supercategory": "logo"}], "images": [{"coco_url": "", "date_captured": "", "file_name": "test.jpg", "flickr_url": "", "id": 1, "license": 1, "width": 600, "height": 600}], "annotations": [{"area": 5652, "bbox": [436, 15, 157, 36], "category_id": 1, "id": 1, "image_id": 1, "iscrowd": 0, "segmentation": [[]]}, {"area": 1504, "bbox": [389, 9, 47, 32], "category_id": 1, "id": 2, "image_id": 1, "iscrowd": 0, "segmentation": [[]]}, {"area": 425, "bbox": [502, 177, 25, 17], "category_id": 1, "id": 3, "image_id": 1, "iscrowd": 0, "segmentation": [[]]}, {"area": 120, "bbox": [562, 296, 10, 12], "category_id": 1, "id": 4, "image_id": 1, "iscrowd": 0, "segmentation": [[]]}, {"area": 391, "bbox": [467, 387, 23, 17], "category_id": 1, "id": 5, "image_id": 1, "iscrowd": 0, "segmentation": [[]]}, {"area": 875, "bbox": [220, 288, 35, 25], "category_id": 1, "id": 6, "image_id": 1, "iscrowd": 0, "segmentation": [[]]}, {"area": 156, "bbox": [213, 310, 13, 12], "category_id": 1, "id": 7, "image_id": 1, "iscrowd": 0, "segmentation": [[]]}, {"area": 144, "bbox": [525, 513, 9, 16], "category_id": 1, "id": 8, "image_id": 1, "iscrowd": 0, "segmentation": [[]]}, {"area": 264, "bbox": [275, 491, 12, 22], "category_id": 1, "id": 9, "image_id": 1, "iscrowd": 0, "segmentation": [[]]}]}

**Comment by jinxuan777** [comment]
Reader做了相应路径的更改，以及预设anchor的重计算：
TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  use_fine_grained_loss: true
  dataset:
    !COCODataSet
    image_dir: images
    #anno_path: trainval.json
    anno_path: snapshot.json
    dataset_dir: dataset/logo/
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !RandomCrop {}
    - !RandomFlipImage
      is_normalized: false
    - !NormalizeBox {}
    - !PadBox
      num_max_boxes: 50
    - !BboxXYXY2XYWH {}
  batch_transforms:
    - !RandomShape
      sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
      random_inter: True
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: False
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
    # Gt2YoloTarget is only used when use_fine_grained_loss set as true,
    # this operator will be deleted automatically if use_fine_grained_loss
    # is set as false
    - !Gt2YoloTarget
      anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
      #anchors: [[10, 13], [16, 30], [33, 23],
      #          [30, 61], [62, 45], [59, 119],
      #          [116, 90], [156, 198], [373, 326]]
      anchors: [[28, 21], [67, 24], [41, 48],
                [129, 35], [89, 66], [52, 121],
                [215, 64], [151, 143], [317, 272]]
      downsample_ratios: [32, 16, 8]
  batch_size: 1
  shuffle: true
  drop_last: true
  worker_num: 8
  bufsize: 1
  use_process: true

**Comment by yghstill** [comment]
@jinxuan777 在这一行前面打印一下coco_res的解析结果是否正确：https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/ppdet/data/source/coco.py#L180

**Comment by jinxuan777** [comment]
@yghstill 应该是segmentation的anno为空导致的，现在没问题了
