### ISSUE TITLE
配置完开始训练报错

### ISSUE THREAD

**Issue by JianJingGao** [PaddlePaddle/PaddleDetection#187]
ubuntu 18.04    gtx1066

Error Message Summary:
----------------------
Error: CUDNN_STATUS_BAD_PARAM at (/paddle/paddle/fluid/operators/batch_norm_op.cu:183)
  [operator < batch_norm > error]

**Comment by qingqing01** [comment]
@JianJingGao 可以先用下面程序测下安装是否成功:
  
```
import paddle.fluid as fluid
import numpy as np
x = fluid.layers.data(name='x', shape=[-1, 3], dtype='float32')
y = fluid.layers.data(name='y', shape=[-1, 3], dtype='float32')
z = x + y

#place = fluid.CPUPlace()
place = fluid.CUDAPlace(0)
exe = fluid.Executor(place)


np_x = np.random.random(size=(7, 3)).astype('float32')
np_y = np.random.random(size=(7, 3)).astype('float32')
output = exe.run(feed={"x": np_x, 'y':np_y}, fetch_list = [z])
print(output)
```

**Comment by mitsuix** [comment]
> 
> 
> @JianJingGao 可以先用下面程序测下安装是否成功:
> 
> ```
> import paddle.fluid as fluid
> import numpy as np
> x = fluid.layers.data(name='x', shape=[-1, 3], dtype='float32')
> y = fluid.layers.data(name='y', shape=[-1, 3], dtype='float32')
> z = x + y
> 
> #place = fluid.CPUPlace()
> place = fluid.CUDAPlace(0)
> exe = fluid.Executor(place)
> 
> 
> np_x = np.random.random(size=(7, 3)).astype('float32')
> np_y = np.random.random(size=(7, 3)).astype('float32')
> output = exe.run(feed={"x": np_x, 'y':np_y}, fetch_list = [z])
> print(output)
> ```

我也碰到过这个报错。安装是成功的。后来把paddle版本降到1.6.0就不报错，可以正常训练了。
请问要想在paddle1.7.1下可用， 怎么修改啊？谢谢啦~

**Comment by qingqing01** [comment]
@mitsuix 这个错误可以考虑升级下cuDNN版本，优于时间较久，关闭了此issue，有问题，可以再开issue。
