### ISSUE TITLE
blazeface迁移学习忽略参数问题

### ISSUE THREAD

**Issue by conan1024hao** [PaddlePaddle/PaddleDetection#1872]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md
迁移学习教程中并为给出blazeface应该忽略哪些参数，希望从人+background的2分类迁移学习成戴口罩+不戴口肇+background的3分类模型。
不忽略参数直接训练的话，loss会一直在3左右徘徊，最终模型精度很差无法使用。
请多指教。

**Comment by conan1024hao** [comment]
是按SSD的来吗？

**Comment by yghstill** [comment]
@conan1024hao 按照SSD的迁移学习策略就行
