### ISSUE TITLE
solov2训练出错

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/PaddleDetection#1873]
![image](https://user-images.githubusercontent.com/57654726/101866956-14dbca80-3bb5-11eb-98c5-9227819dd20a.png)
，训练时出现错误，使用paddle 2.0 cuda 10.0 ,配置文件修改了自己的数据集，其他都没改
![image](https://user-images.githubusercontent.com/57654726/101867075-553b4880-3bb5-11eb-914b-fda5b14e3f4e.png)

**Comment by yghstill** [comment]
@xialei2821212670 是偶发错误，还是这个错误一直出现？

**Comment by xialei2821212670** [comment]
> @ xialei2821212670是偶发错误，还是这个错误一直出现？

我尝试了多次，使用自己的数据集出现过这个错误。

**Comment by yghstill** [comment]
@xialei2821212670 应该是数据导致的，要不把数据shuffle关闭，定位一下训练到哪张图片出现问题，然后看下标注信息是否异常？
