### ISSUE TITLE
如果我有1000张图想用ppyolo训练，我的max_iters是不是应该是380000

### ISSUE THREAD

**Issue by pt1003482256** [PaddlePaddle/PaddleDetection#1875]

**Comment by qingqing01** [comment]
默认提供的配置都是8卡训练，总的batch-size是每个卡的batch-size乘以8.

1.  batch-size=192时:
 
先换算COCO的epoch数: 

以 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/configs/ppyolo/ppyolo.yml 这个为例子:

COCO训练数据: 118287
batch-size总数: 24*8=192
最大迭代轮数: 250000


换算成epoch数：
1一个epoch的step数：616 = 118287 / 192
最大迭代轮数约为:    405 = 250000 / 616


如果您是1000张图片，也按照400个(或405个)epoch训练， batch_size也是24:

最大的迭代轮数(max_iters)为: 1000/192 * 400 约2080个iter。

如果用其他的YML配置类似。

2. batch-size=192, 2x的配置

max_iters加倍。


3.  batch_size=96，ppyolo_2x_bs12.yml的配置:

对应的epoch数为 500000/(118287/96) 约为405epoch。

1000张图片时，1000/96 * 405大约4218个iter。


最后，如果您的卡数不是8卡，也换算时依据总的batch-size换算下(或者max_iters倍数增加)。 另外，在自己的数据集上，可以用COCO预训练模型，max_iters可以适当的调整，不一定严格按照这些换算。

**Comment by dengxinlong** [comment]
> 默认提供的配置都是8卡训练，总的batch-size是每个卡的batch-size乘以8.
> 
> 1. batch-size=192时:
> 
> 先换算COCO的epoch数:
> 
> 以 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/configs/ppyolo/ppyolo.yml 这个为例子:
> 
> COCO训练数据: 118287
> batch-size总数: 24*8=192
> 最大迭代轮数: 250000
> 
> ```
> 换算成epoch数：
> 一个epoch的step数：616 = 118287 / 192
> 最大迭代轮数约为:    405 = 250000 / 616
> 
> 如果您是1000张图片，也按照400个(或405个)epoch训练， batch_size也是24:
> ```
> 
> 最大的迭代轮数(max_iters)为: 1000/192 * 400 约2080个iter。
> 
> 如果用其他的YML配置类似。
> 
> 1. batch-size=192, 2x的配置
>    max_iters加倍。
> 2. batch_size=96，ppyolo_2x_bs12.yml的配置:
>    对应的epoch数为 500000/(118287/96) 约为405epoch。
> 
> 1000张图片时，1000/96 * 405大约4218个iter。
> 
> 最后，如果您的卡数不是8卡，也换算时依据总的batch-size换算下(或者max_iters倍数增加)。 另外，在自己的数据集上，可以用COCO预训练模型，max_iters可以适当的调整，不一定严格按照这些换算。

这里我提一下，其实关于这点我也不是很明白，关于训练的轮数、训练集大小、batchsize以及显卡个数的关系，贵方可以写一个文档说明清楚。不然后续其他人看的时候，还是一头雾水。
