### ISSUE TITLE
matrix nms，visualDL

### ISSUE THREAD

**Issue by Shanyaodedanshen** [PaddlePaddle/PaddleDetection#1876]
我使用solov2-mobilenetv3的模型，请问，我的matrix nms似乎不起作用，即使我将threshold of score定的很高，仍然存在许多重合的mask推理结果，能否帮助我，谢谢。另外，我训练好的模型在visualDL和netro里都打不开，大小只有6MB左右，它们均提示模型太大，能否帮助我，谢谢。

**Comment by iceriver97** [comment]
> 我使用solov2-mobilenetv3的模型，请问，我的matrix nms似乎不起作用，即使我将threshold of score定的很高，仍然存在许多重合的mask推理结果，能否帮助我，谢谢。另外，我训练好的模型在visualDL和netro里都打不开，大小只有6MB左右，它们均提示模型太大，能否帮助我，谢谢。

模型方便发一下吗？我可以帮你看看VisualDL的问题

**Comment by Shanyaodedanshen** [comment]
> > 我使用solov2-mobilenetv3的模型，请问，我的matrix nms似乎不起作用，即使我将threshold of score定的很高，仍然存在许多重合的mask推理结果，能否帮助我，谢谢。另外，我训练好的模型在visualDL和netro里都打不开，大小只有6MB左右，它们均提示模型太大，能否帮助我，谢谢。
> 
> 模型方便发一下吗？我可以帮你看看VisualDL的问题

谢谢，不用了，我大概等了几十分钟后，它能正常显示了。
