### ISSUE TITLE
rcnn：export_model问题

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#1885]
faster_rcnn_r50_dcn-vd_fpn训练完，通过infer.py结果标签是OK的，通过export_model.py到处模型后，基于deploy/python/infer.py预测出现问题：标签不对，包含了backgroud,该如何修改？？

**Comment by jerrywgz** [comment]
在导出模型的时候会在导出模型的文件夹下生成一个配置文件，里面包含了数据集对应的标签，可以check下这个label list时候正确

**Comment by jerrywgz** [comment]
另外rcnn模型中num_classes是包含背景类的，同时with_background也为True（默认值就是True）
