### ISSUE TITLE
【CPP deploy MKL&GPU 预测 内存增加问题】Paddle 版本1.8.4，电脑window10

### ISSUE THREAD

**Issue by Fire-Star** [PaddlePaddle/PaddleDetection#1886]
使用的原始预测cpp代码。经过多次for循环预测。
1.在MKL GPU 模式下 内存显著增加，且不释放。
2.在MKL 模式下内存增加不明显，但是上100次到上千次预测后会有大约40MB内存不释放，预测次数越多内存增加越多，且不释放。

**Comment by qingqing01** [comment]
@Fire-Star 确认下是内存增加？for循环，是只在 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/deploy/cpp/src/main.cc#L216  的PredictImage外加一层循环吗？
