### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by xiaowanzizz** [PaddlePaddle/PaddleDetection#1896]
请问飞度1.8.5版本支持30系列显卡的训练吗？

**Comment by xiaowanzizz** [comment]
Config use_gpu cannot be set as true while you are using paddlepaddle cpu version ! 
Please try: 
	1. Install paddlepaddle-gpu to run model on GPU 
	2. Set use_gpu as false in config file to run model on CPU

**Comment by xiaowanzizz** [comment]
python -c "import paddle; print(paddle.__version__)"
1.8.5

**Comment by jerrywgz** [comment]
30系列显卡需要cuda11，飞桨会在2.0rc1版本之后会支持cuda11，2.0rc1很快就会发布

**Comment by jerrywgz** [comment]
你安装的是paddle cpu版本，如果希望使用gpu的话需要安装gpu版本

**Comment by xiaowanzizz** [comment]
希望尽快推出新版本以便实验，对于代码解析和训练自己的数据集希望能出教学视频，Thanks♪(･ω･)ﾉ

**Comment by jerrywgz** [comment]
好的，相关视频的话在b站上有开发出来相关的课程，另外aistudio上也有很多开源项目
