### ISSUE TITLE
num_classes 大于实际类别数会发生什么？

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleDetection#1901]
我不小心将 num_classes 设置的大于了实际类别数，但是可以正常训练，我想问一下这会有影响吗？

**Comment by jerrywgz** [comment]
通常num_classes会影响head最后几个卷积的channel数，如果大于实际类别数的话是可以正常训练的，但是从以往的经验来看会对精度的影响比较大

**Comment by iceriver97** [comment]
> 通常num_classes会影响head最后几个卷积的channel数，如果大于实际类别数的话是可以正常训练的，但是从以往的经验来看会对精度的影响比较大

我改为正常的num_classes后 反而mAP下降了不少，是什么情况呢？
