### ISSUE TITLE
关于ppyolo的预测问题

### ISSUE THREAD

**Issue by tianlanshidai** [PaddlePaddle/PaddleDetection#1904]
我在我自己的数据集上进行训练（COCO格式），训练配置文件如下：

TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !COCODataSet
      image_dir: images
      anno_path: annotations/coco.json
      dataset_dir: dataset/202007_dataset
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: True
    - !MixupImage
      alpha: 1.5
      beta: 1.5
    - !ColorDistort {}
    - !RandomExpand
      ratio: 2.0
      fill_value: [123.675, 116.28, 103.53]
    - !RandomCrop {}
    - !RandomFlipImage
      is_normalized: false
    - !NormalizeBox {}
    - !PadBox
      num_max_boxes: 50
    - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
    random_inter: True
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: True
  - !Gt2YoloTarget
    anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
    anchors: [[10, 13], [16, 30], [33, 23],
              [30, 61], [62, 45], [59, 119],
              [116, 90], [156, 198], [373, 326]]
    downsample_ratios: [32, 16, 8]
  batch_size: 24
  shuffle: true
  mixup_epoch: 300
  drop_last: true
  worker_num: 2
  bufsize: 4
  use_process: false

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id']
    num_max_boxes: 50
  dataset:
    !COCODataSet
      image_dir: images
      anno_path: annotations/coco.json
      dataset_dir: /data/wenzongzheng/datasets/Terror_image_dataset/202007_bad_good
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !PadBox
      num_max_boxes: 50
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 8
  drop_empty: false
  worker_num: 8
  bufsize: 4

TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
  dataset:
    !ImageFolder
      anno_path: annotations/instances_val2017.json
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1

然后我使用训练了1000代的中间模型用于测试和推理，速度非常慢，是否是因为我的模型还没有训练完成，所以才这么慢？

**Comment by heavengate** [comment]
训练1000iter模型还没开始收敛，输出基本是乱码，而预测中nms的处理比较依赖数据有序性，所以比较慢，模型正常收敛之后就不会有这个问题了

**Comment by tianlanshidai** [comment]
> 训练1000iter模型还没开始收敛，输出基本是乱码，而预测中nms的处理比较依赖数据有序性，所以比较慢，模型正常收敛之后就不会有这个问题了

我也是这么想的，就是感觉ppyolo训起来很慢，等训完之后我再测试一下速度

**Comment by tianlanshidai** [comment]
> 训练1000iter模型还没开始收敛，输出基本是乱码，而预测中nms的处理比较依赖数据有序性，所以比较慢，模型正常收敛之后就不会有这个问题了

请问，我有1.2w训练集的数据，训练的总iter和学习率应当如何设置？配置是8卡V100，每张卡的batch=24
