### ISSUE TITLE
关于ppyolo的训练问题

### ISSUE THREAD

**Issue by tianlanshidai** [PaddlePaddle/PaddleDetection#1905]
使用8卡V100的配置进行训练，如果开启use_process（多线程），训练的时候就会出现异常终止：
W1215 13:11:30.621182   412 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1215 13:11:30.621199   410 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1215 13:11:30.621238   412 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1215 13:11:30.621248   412 init.cc:231] The detail failure signal is:

W1215 13:11:30.621249   410 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1215 13:11:30.621255   412 init.cc:234] *** Aborted at 1608009090 (unix time) try "date -d @1608009090" if you are using GNU date ***
W1215 13:11:30.621255   410 init.cc:231] The detail failure signal is:

W1215 13:11:30.621265   410 init.cc:234] *** Aborted at 1608009090 (unix time) try "date -d @1608009090" if you are using GNU date ***
W1215 13:11:30.621266   411 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1215 13:11:30.621326   411 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1215 13:11:30.621331   411 init.cc:231] The detail failure signal is:

W1215 13:11:30.621340   411 init.cc:234] *** Aborted at 1608009090 (unix time) try "date -d @1608009090" if you are using GNU date ***
W1215 13:11:30.622946   412 init.cc:234] PC: @                0x0 (unknown)
W1215 13:11:30.623087   410 init.cc:234] PC: @                0x0 (unknown)
W1215 13:11:30.623220   412 init.cc:234] *** SIGBUS (@0x7f1201d4c000) received by PID 412 (TID 0x7f134f872740) from PID 30720000; stack trace: ***
W1215 13:11:30.623220   410 init.cc:234] *** SIGBUS (@0x7fe804372000) received by PID 410 (TID 0x7fe981d65740) from PID 70721536; stack trace: ***
W1215 13:11:30.624645   412 init.cc:234]     @     0x7f134f257890 (unknown)
W1215 13:11:30.624686   411 init.cc:234] PC: @                0x0 (unknown)
W1215 13:11:30.624774   410 init.cc:234]     @     0x7fe98174a890 (unknown)
W1215 13:11:30.625000   411 init.cc:234] *** SIGBUS (@0x7f6c39f36000) received by PID 411 (TID 0x7f6d80725740) from PID 972251136; stack trace: ***
W1215 13:11:30.626011   412 init.cc:234]     @     0x7f134e635f2d (unknown)
W1215 13:11:30.626261   410 init.cc:234]     @     0x7fe980b28f2d (unknown)
W1215 13:11:30.626400   411 init.cc:234]     @     0x7f6d8010a890 (unknown)
W1215 13:11:30.627285   412 init.cc:234]     @     0x7f134e3899ed ffi_call_unix64
W1215 13:11:30.627704   410 init.cc:234]     @     0x7fe98087c9ed ffi_call_unix64
W1215 13:11:30.627754   411 init.cc:234]     @     0x7f6d7f4e8f2d (unknown)
W1215 13:11:30.628556   412 init.cc:234]     @     0x7f134e389077 ffi_call_int
W1215 13:11:30.629020   411 init.cc:234]     @     0x7f6d7f23c9ed ffi_call_unix64
W1215 13:11:30.629151   410 init.cc:234]     @     0x7fe98087c077 ffi_call_int
W1215 13:11:30.629801   412 init.cc:234]     @     0x7f134b9d6904 _ctypes_callproc
W1215 13:11:30.630270   411 init.cc:234]     @     0x7f6d7f23c077 ffi_call_int
W1215 13:11:30.630537   410 init.cc:234]     @     0x7fe97dec9904 _ctypes_callproc
W1215 13:11:30.630987   412 init.cc:234]     @     0x7f134b9d7168 PyCFuncPtr_call
W1215 13:11:30.631505   411 init.cc:234]     @     0x7f6d7c889904 _ctypes_callproc
W1215 13:11:30.631852   410 init.cc:234]     @     0x7fe97deca168 PyCFuncPtr_call
W1215 13:11:30.632462   412 init.cc:234]     @     0x55f7847d5adb _PyObject_FastCallKeywords
W1215 13:11:30.632663   412 init.cc:234]     @     0x55f7847d65d9 call_function
W1215 13:11:30.632688   411 init.cc:234]     @     0x7f6d7c88a168 PyCFuncPtr_call
W1215 13:11:30.633313   410 init.cc:234]     @     0x5633ee5f1adb _PyObject_FastCallKeywords
W1215 13:11:30.633546   410 init.cc:234]     @     0x5633ee5f25d9 call_function
W1215 13:11:30.634156   412 init.cc:234]     @     0x55f78484b2ea _PyEval_EvalFrameDefault
W1215 13:11:30.634578   411 init.cc:234]     @     0x55937a16cadb _PyObject_FastCallKeywords
W1215 13:11:30.634821   411 init.cc:234]     @     0x55937a16d5d9 call_function
W1215 13:11:30.635099   410 init.cc:234]     @     0x5633ee6672ea _PyEval_EvalFrameDefault
W1215 13:11:30.635613   412 init.cc:234]     @     0x55f7847d35d4 _PyFunction_FastCallKeywords
W1215 13:11:30.635810   412 init.cc:234]     @     0x55f7847d6448 call_function
W1215 13:11:30.636551   411 init.cc:234]     @     0x55937a1e22ea _PyEval_EvalFrameDefault
W1215 13:11:30.636600   410 init.cc:234]     @     0x5633ee5ef5d4 _PyFunction_FastCallKeywords
W1215 13:11:30.636806   410 init.cc:234]     @     0x5633ee5f2448 call_function
W1215 13:11:30.637292   412 init.cc:234]     @     0x55f784846ebd _PyEval_EvalFrameDefault
W1215 13:11:30.638216   411 init.cc:234]     @     0x55937a16a5d4 _PyFunction_FastCallKeywords
W1215 13:11:30.638332   410 init.cc:234]     @     0x5633ee662ebd _PyEval_EvalFrameDefault
W1215 13:11:30.638445   411 init.cc:234]     @     0x55937a16d448 call_function
W1215 13:11:30.638741   412 init.cc:234]     @     0x55f7847d35d4 _PyFunction_FastCallKeywords
W1215 13:11:30.638942   412 init.cc:234]     @     0x55f7847d6448 call_function
W1215 13:11:30.639799   410 init.cc:234]     @     0x5633ee5ef5d4 _PyFunction_FastCallKeywords
W1215 13:11:30.640000   410 init.cc:234]     @     0x5633ee5f2448 call_function
W1215 13:11:30.640151   411 init.cc:234]     @     0x55937a1ddebd _PyEval_EvalFrameDefault
W1215 13:11:30.640455   412 init.cc:234]     @     0x55f784846ebd _PyEval_EvalFrameDefault
W1215 13:11:30.641495   410 init.cc:234]     @     0x5633ee662ebd _PyEval_EvalFrameDefault
W1215 13:11:30.641795   411 init.cc:234]     @     0x55937a16a5d4 _PyFunction_FastCallKeywords
W1215 13:11:30.641938   412 init.cc:234]     @     0x55f7847d35d4 _PyFunction_FastCallKeywords
W1215 13:11:30.642016   411 init.cc:234]     @     0x55937a16d448 call_function
W1215 13:11:30.642133   412 init.cc:234]     @     0x55f7847d6448 call_function
W1215 13:11:30.642935   410 init.cc:234]     @     0x5633ee5ef5d4 _PyFunction_FastCallKeywords
W1215 13:11:30.643133   410 init.cc:234]     @     0x5633ee5f2448 call_function
W1215 13:11:30.643719   412 init.cc:234]     @     0x55f784846f53 _PyEval_EvalFrameDefault
W1215 13:11:30.643757   411 init.cc:234]     @     0x55937a1ddebd _PyEval_EvalFrameDefault
W1215 13:11:30.644630   410 init.cc:234]     @     0x5633ee662f53 _PyEval_EvalFrameDefault
W1215 13:11:30.645195   412 init.cc:234]     @     0x55f78478e5a2 _PyEval_EvalCodeWithName
W1215 13:11:30.645406   411 init.cc:234]     @     0x55937a16a5d4 _PyFunction_FastCallKeywords
W1215 13:11:30.645634   411 init.cc:234]     @     0x55937a16d448 call_function
W1215 13:11:30.646142   410 init.cc:234]     @     0x5633ee5aa5a2 _PyEval_EvalCodeWithName
W1215 13:11:30.646679   412 init.cc:234]     @     0x55f78478fe50 _PyFunction_FastCallDict
W1215 13:11:30.646915   412 init.cc:234]     @     0x55f78480827c slot_tp_init
W1215 13:11:30.647326   411 init.cc:234]     @     0x55937a1ddf53 _PyEval_EvalFrameDefault
W1215 13:11:30.647661   410 init.cc:234]     @     0x5633ee5abe50 _PyFunction_FastCallDict
W1215 13:11:30.647909   410 init.cc:234]     @     0x5633ee62427c slot_tp_init
W1215 13:11:30.648398   412 init.cc:234]     @     0x55f7847d57ec _PyObject_FastCallKeywords
W1215 13:11:30.648603   412 init.cc:234]     @     0x55f7847d65d9 call_function
W1215 13:11:30.649000   411 init.cc:234]     @     0x55937a1255a2 _PyEval_EvalCodeWithName
W1215 13:11:30.649405   410 init.cc:234]     @     0x5633ee5f17ec _PyObject_FastCallKeywords
W1215 13:11:30.649619   410 init.cc:234]     @     0x5633ee5f25d9 call_function
W1215 13:11:30.650094   412 init.cc:234]     @     0x55f784847b44 _PyEval_EvalFrameDefault
W1215 13:11:30.650681   411 init.cc:234]     @     0x55937a126e50 _PyFunction_FastCallDict
W1215 13:11:30.650954   411 init.cc:234]     @     0x55937a19f27c slot_tp_init
W1215 13:11:30.651134   410 init.cc:234]     @     0x5633ee663b44 _PyEval_EvalFrameDefault
W1215 13:11:30.651556   412 init.cc:234]     @     0x55f78478e5a2 _PyEval_EvalCodeWithName
W1215 13:11:30.652621   411 init.cc:234]     @     0x55937a16c7ec _PyObject_FastCallKeywords
W1215 13:11:30.652730   410 init.cc:234]     @     0x5633ee5aa5a2 _PyEval_EvalCodeWithName
W1215 13:11:30.652844   411 init.cc:234]     @     0x55937a16d5d9 call_function
W1215 13:11:30.653038   412 init.cc:234]     @     0x55f78478fe50 _PyFunction_FastCallDict
W1215 13:11:30.653285   412 init.cc:234]     @     0x55f78480827c slot_tp_init
W1215 13:11:30.654613   410 init.cc:234]     @     0x5633ee5abe50 _PyFunction_FastCallDict
W1215 13:11:30.654647   411 init.cc:234]     @     0x55937a1deb44 _PyEval_EvalFrameDefault
W1215 13:11:30.654772   412 init.cc:234]     @     0x55f7847d57ec _PyObject_FastCallKeywords
W1215 13:11:30.654964   410 init.cc:234]     @     0x5633ee62427c slot_tp_init
W1215 13:11:30.654975   412 init.cc:234]     @     0x55f7847d65d9 call_function
W1215 13:11:30.656316   411 init.cc:234]     @     0x55937a1255a2 _PyEval_EvalCodeWithName
W1215 13:11:30.656527   410 init.cc:234]     @     0x5633ee5f17ec _PyObject_FastCallKeywords
W1215 13:11:30.656529   412 init.cc:234]     @     0x55f784847b44 _PyEval_EvalFrameDefault
W1215 13:11:30.656751   410 init.cc:234]     @     0x5633ee5f25d9 call_function
W1215 13:11:30.657994   411 init.cc:234]     @     0x55937a126e50 _PyFunction_FastCallDict
W1215 13:11:30.658126   412 init.cc:234]     @     0x55f7847d35d4 _PyFunction_FastCallKeywords
W1215 13:11:30.658263   411 init.cc:234]     @     0x55937a19f27c slot_tp_init
W1215 13:11:30.658344   412 init.cc:234]     @     0x55f7847d6448 call_function
W1215 13:11:30.658721   410 init.cc:234]     @     0x5633ee663b44 _PyEval_EvalFrameDefault
W1215 13:11:30.659801   411 init.cc:234]     @     0x55937a16c7ec _PyObject_FastCallKeywords
W1215 13:11:30.660012   411 init.cc:234]     @     0x55937a16d5d9 call_function
W1215 13:11:30.660763   410 init.cc:234]     @     0x5633ee5ef5d4 _PyFunction_FastCallKeywords
W1215 13:11:30.661056   410 init.cc:234]     @     0x5633ee5f2448 call_function
W1215 13:11:30.661437   411 init.cc:234]     @     0x55937a1deb44 _PyEval_EvalFrameDefault
W1215 13:11:30.662643   411 init.cc:234]     @     0x55937a16a5d4 _PyFunction_FastCallKeywords
W1215 13:11:30.662813   411 init.cc:234]     @     0x55937a16d448 call_function
INFO 2020-12-15 13:11:44,729 utils.py:274] terminate all the procs
ERROR 2020-12-15 13:11:44,730 utils.py:418] ABORT!!! Out of all 3 trainers, the trainer process with rank=[0, 1, 2] was aborted. Please check its log.
INFO 2020-12-15 13:11:47,733 utils.py:274] terminate all the procs

所以只能关闭掉多线程，才能训练。这个问题有解决办法吗

**Comment by heavengate** [comment]
看报错像是内存不够的原因，`free -h`看下呢

**Comment by tianlanshidai** [comment]
内存申请到了70G，应该够用啊，



---原始邮件---
发件人: "Kaipeng Deng"<notifications@github.com&gt;
发送时间: 2020年12月16日(周三) 下午3:44
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送: "tianlanshidai"<www.ecbt.com@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] 关于ppyolo的训练问题 (#1905)




 
看报错像是内存不够的原因，free -h看下呢

**Comment by tianlanshidai** [comment]
Filesystem                     Size  Used Avail Use% Mounted on
overlay                        894G   50G  845G   6% /
tmpfs                           64M     0   64M   0% /dev
tmpfs                          252G     0  252G   0% /sys/fs/cgroup
/dev/sda1                       98G  9.9G   88G  11% /etc/hosts
shm                            8.0G     0  8.0G   0% /dev/shm
/dev/sdb                       894G   50G  845G   6% /etc/hostname
tmpfs                          252G   12K  252G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                          252G   12K  252G   1% /proc/driver/nvidia
/dev/sda3                      346G   11G  335G   4% /usr/bin/nvidia-smi
devtmpfs                       252G     0  252G   0% /dev/nvidia0
tmpfs                          252G     0  252G   0% /proc/acpi
tmpfs                          252G     0  252G   0% /proc/scsi
tmpfs                          252G     0  252G   0% /sys/firmware
jarvis-output-wenzongzheng_sx  1.0P     0  1.0P   0% /media/s3fs/output
jarvis-data-wenzongzheng_sx    1.0P     0  1.0P   0% /opt/ml/data
