### ISSUE TITLE
量化训练相关问题

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#1907]
问题1：
yolov3-mobilenetv1，训练集voc
量化训练刚开始前面几轮精度很低，不到10%。感觉是因为从第一个conv开始就多了量化反量化算子，量化训练代码里网络结构跟预训练模型不一致，就没有用上预训练模型。现在单卡训了几十万轮，精度40%多感觉精度很难到70%以上(正常训练)。但是文档里说量化的训练轮次比正常训练小很多。
问题2：
paddle inference预测
TX2
C++
量化训练的模型在下trt_fp16推理速度跟正常训练的模型在trt_fp16下相近，感觉量化提速只能在移动端使用paddle lite体现出来

**Comment by yghstill** [comment]
@JensenHJS 不用预训练模型的话，在线量化训练很难达到和原模型相近的效果，除非量化训练的轮数和原模型训练轮数相同（yolov3-mobilenetv1在8卡GPU下训练270epoch得到）。
量化模型需要使用paddle lite才可以取得提速效果。

**Comment by JensenHJS** [comment]
发现量化后网络结构就是每个卷积和深度可分离卷积前后多了量化反量化算子，从第一层卷积开始就跟预训练模型mobilenet不匹配，是不是因为这个原因，导致预训练模型没用上？所以一开始精度就很低

**Comment by qingqing01** [comment]
添加量化、反量化算子不会影响预训练模型的加载，参数名字是对应的。
