### ISSUE TITLE
solov2训练自己的数据集

### ISSUE THREAD

**Issue by hymanzhu1983** [PaddlePaddle/PaddleDetection#1913]
请问有没有相关的教程？

**Comment by yghstill** [comment]
@hymanzhu1983 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/docs/tutorials/Custom_DataSet.md
请参考这个教程，将自己的数据集转换成coco格式

**Comment by curryJ** [comment]
> @hymanzhu1983 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/docs/tutorials/Custom_DataSet.md
> 请参考这个教程，将自己的数据集转换成coco格式

您好，我也是按照这个教程，准备在自己的数据集上训练solov2，但是当我将xml格式转换成coco的json格式进行训练的时候，会出现问题。
https://github.com/PaddlePaddle/PaddleDetection/issues/1942#issuecomment-752397673
能帮我看一下吗，非常感谢！

**Comment by qingqing01** [comment]
由于时间较久，关闭历史issue
