### ISSUE TITLE
PP-YOLO矩形输入改怎样做修改？在新版本中ppyolo_2x_bs12中bs12代表什么意思？

### ISSUE THREAD

**Issue by chenweidu666** [PaddlePaddle/PaddleDetection#1915]

**Comment by yghstill** [comment]
（1）PP-YOLO网络输入矩形训练是已经支持了，但在代码中暂不支持直接矩形输入，需要修改https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/ppdet/data/transform/batch_operators.py#L105 RandomShape的resize过程。
（2）bs12表示batch size =12

**Comment by chenweidu666** [comment]
谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Guanghua Yu"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 晚上8:09
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 
抄送: "514351508"<514351508@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] PP-YOLO矩形输入改怎样做修改？在新版本中ppyolo_2x_bs12中bs12代表什么意思？ (#1915)





 
（1）PP-YOLO网络输入矩形训练是已经支持了，但在代码中暂不支持直接矩形输入，需要修改https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/ppdet/data/transform/batch_operators.py#L105 RandomShape的resize过程。
 （2）bs12表示batch size =12
