### ISSUE TITLE
多GPU评估问题

### ISSUE THREAD

**Issue by tianlanshidai** [PaddlePaddle/PaddleDetection#1925]
请问各位大佬，paddledetection支持多卡评估（eval.py）吗？我今天使用多卡评估的时候出现了如下问题:

[Hint: Expected framework::product(new_dim) / new_dim[0] == framework::product(t->dims()) / t->dims()[0], but received framework::product(new_dim) / new_dim[0]:6 != framework::product(t->dims()) / t->dims()[0]:1.] at (/paddle/paddle/fluid/framework/lod_tensor.cc:400)

数据集使用的是coco格式，faster_rcnn模型。请问有解决办法吗，什么时候能够支持多GPU评估？

**Comment by qingqing01** [comment]
@tianlanshidai 请问您试用的Paddle版本是哪个？

**Comment by tianlanshidai** [comment]
2.0rc



---原始邮件---
发件人: "qingqing01"<notifications@github.com&gt;
发送时间: 2020年12月21日(周一) 上午10:33
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"tianlanshidai"<www.ecbt.com@qq.com&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] 多GPU评估问题 (#1925)




 
@tianlanshidai 请问您试用的Paddle版本是哪个？

**Comment by qingqing01** [comment]
@tianlanshidai 

将一下代码改成：

https://github.com/PaddlePaddle/PaddleDetection/blob/46659c8bb2ce773bb05da78466d28015f570fc12/ppdet/modeling/ops.py#L494

->

```
__op__ = fluid.contrib.layers.multiclass_nms2
```

测试是可以的。
