### ISSUE TITLE
SOLOV2自定义数据集训练完后，评估的时候使用GPU预测结果为空，采用CPU可以的得到分割的图像

### ISSUE THREAD

**Issue by hong3731** [PaddlePaddle/PaddleDetection#1930]
有一个奇怪的问题，训练完成采用use_gpu=true得到的图像是没有mask的，但是use_gpu=false的时候就可以得到mask，请教一下这个是怎么回事的呢？
CPU跑的结果：
![image](https://user-images.githubusercontent.com/47878003/102610877-e20f7480-4168-11eb-805a-25e3d42d9c8e.png)
GPU跑的结果：
![image](https://user-images.githubusercontent.com/47878003/102611031-2a2e9700-4169-11eb-8d0c-8e63665c9b78.png)

**Comment by hong3731** [comment]
!python work/PaddleDetection/tools/infer.py -c work/PaddleDetection/configs/solov2/solov2_r101_vd_fpn_3x.yml -o use_gpu=true weights=output/solov2_r101_vd_fpn_3x/2000.pdparams --infer_img="work/PaddleDetection/data/images/8.jpg"
 打印infer的结果：
 ———————————CPU——————————————————
 'cate_label': (array([0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 1],dtype=int64), []), 
 'cate_score': (array([ 1.0045936 ,  0.7758367 ,  0.73693705,  0.5647144 ,  0.39347598,
        0.39265177,  0.33682826,  0.29663283,  0.29256168,  0.12292448,
        0.11185891,  0.10205004,  0.09240628,  0.08765446,  0.07578078,
        0.07286482,  0.06361085,  0.06293799,  0.05607685,  0.05399049,
       -0.577593  ], dtype=float32), []), 
'im_info': (array([[480. , 640. ,   0.8]], dtype=float32), []), 
'im_id': (array([[0]], dtype=int64), []), 
'im_shape': (array([[600., 800.,   1.]], dtype=float32), [])}	

 ——————————GPU———————————————————
 'cate_label': (array([0], dtype=int64), []), 
 'cate_score': (array([-0.00442139], dtype=float32), []), 
 'im_info': (array([[480. , 640. ,   0.8]], dtype=float32), []),
 'im_id': (array([[0]], dtype=int64), []),
 'im_shape': (array([[600., 800.,   1.]], dtype=float32), [])}

**Comment by hymanzhu1983** [comment]
遇到相同的问题，use_gpu=true结果为空，用cpu就没问题。同样的数据集尝试https://github.com/WXinlong/SOLO训练，在gpu跑是没有问题的。

**Comment by hong3731** [comment]
> 遇到相同的问题，use_gpu=true结果为空，用cpu就没问题。同样的数据集尝试[https://github.com/WXinlong/SOLO训练，在gpu跑是没有问题的。](https://github.com/WXinlong/SOLO%E8%AE%AD%E7%BB%83%EF%BC%8C%E5%9C%A8gpu%E8%B7%91%E6%98%AF%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98%E7%9A%84%E3%80%82)

你好，你解决了这个问题了吗？

**Comment by hong3731** [comment]
好像不能修改训练数据集的种类，必须要用coco的81类，不然训练不出来，而且训练后的结果也不正确，GPU 来infer出来的都是空的

**Comment by hymanzhu1983** [comment]
> 好像不能修改训练数据集的种类，必须要用coco的81类，不然训练不出来，而且训练后的结果也不正确，GPU 来infer出来的都是空的

用cpu跑结果是正确的，gpu跑就没有结果输出，应该和类别没有关系。

**Comment by hymanzhu1983** [comment]
有没有人知道解决方法？

**Comment by hong3731** [comment]
不修改训练的类别，好像能得到正确的训练模型的

**Comment by jerrywgz** [comment]
目前已经在最新的develop分支上修复了该问题 https://github.com/PaddlePaddle/PaddleDetection/pull/3193

**Comment by lingdu-xu** [comment]
楼主你好，迷茫之际看到了你的问题，是这样的，我也想跑solov2实例分割，但是没有找到相关的自定义数据准备教程，内心充满疑惑，实例分割怎么标？用什么工具标注，如何转coco等，可否指点一二，，有教程链接也行，，，我可以自己看
