### ISSUE TITLE
请问rcnn_enhance模型的训练环境

### ISSUE THREAD

**Issue by tianlanshidai** [PaddlePaddle/PaddleDetection#1939]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/configs/rcnn_enhance/README.md
请问这里面的模型训练环境是怎样的，用了几张卡呀

**Comment by qingqing01** [comment]
@tianlanshidai  一般情况都是8卡训练，不是8卡的都有特殊说明。
