### ISSUE TITLE
是否有已经用coco数据集训练好的mask rcnn模型

### ISSUE THREAD

**Issue by Wenxin-piggy** [PaddlePaddle/PaddleDetection#1948]

**Comment by jerrywgz** [comment]
有的，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/docs/MODEL_ZOO_cn.md#faster--mask-r-cnn 这个表格中可以看到

**Comment by Wenxin-piggy** [comment]
> 有的，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/docs/MODEL_ZOO_cn.md#faster--mask-r-cnn 这个表格中可以看到

您好，请问这些模型都是已经用coco数据集训练之后的嘛，是可以直接拿来做迁移训练了吗

**Comment by jerrywgz** [comment]
嗯嗯可以的

**Comment by Wenxin-piggy** [comment]
> 嗯嗯可以的

谢谢您
