### ISSUE TITLE
How to use this repo with paddlepaddle-gpu 2.0.0rc1.post110

### ISSUE THREAD

**Issue by bielu** [PaddlePaddle/PaddleDetection#1954]
Hi All,
I am working on research which compare all YOLO detectors accuracy based on thermal, depth and merged images and I wanted include also PP YOLO, but cant get that running with paddlepaddle-gpu 2.0.0rc1.post110, and sadly to run YoloV5 I was kinda force to upgrade to Cuda 11.2 and I am hitting issue with running pp-yolo, can you maybe guide me what I can do to help make that running :)

**Comment by yghstill** [comment]
We will configure a cuda11 environment to debug, and then we will give you the latest results.
