### ISSUE TITLE
模型转换成移动端需要的nb模型时，报错 These unsupported ops are: 'matrix_nms'

### ISSUE THREAD

**Issue by 772865705** [PaddlePaddle/PaddleDetection#1955]
![图片](https://user-images.githubusercontent.com/20854521/103057218-e1983300-45d9-11eb-8de6-1522d4a352a9.png)
用export_lite.py把模型转换成nb模型时报这个错误。在前面的issue中看到了一个类似的问题，于是去看了我的yml文件
Model: PPYOLO
Transforms:
- Resize:
    interp: CUBIC
    target_size: 608
- Normalize:
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
TransformsMode: RGB
_Attributes:
  eval_metrics:
    bbox_map: 63.63880029141469
  fixed_input_shape: null
  labels:
  - leconte
  - boerner
  - armandi
  - linnaeus
  - coleoptera
  - acuminatus
  model_type: detector
  num_classes: 6
_ModelInputsOutputs:
  test_inputs:
  - - image
    - image
  - - im_size
    - im_size
  test_outputs:
  - - bbox
    - matrix_nms_0.tmp_0
_init_params:
  anchor_masks: null
  anchors: null
  backbone: ResNet50_vd_ssld
  ignore_threshold: 0.7
  label_smooth: false
  nms_iou_threshold: 0.45
  nms_keep_topk: 100
  nms_score_threshold: 0.01
  nms_topk: 1000
  num_classes: 6
  scale_x_y: 1.05
  train_random_shapes:
  - 320
  - 352
  - 384
  - 416
  - 448
  - 480
  - 512
  - 544
  - 576
  - 608
  use_coord_conv: true
  use_drop_block: true
  use_iou_aware: true
  use_iou_loss: true
  use_matrix_nms: true
  use_spp: true
  with_dcn_v2: true
completed_epochs: 0
status: Infer
version: 1.2.8

看到里面确实有一个use_matrix_nms: true，可是就算把他改成false，或者把这一行直接删掉，完全不影响在模型转换时报这个错。然后训练的时候也看到没有这个相关的选项，这个应该是不用重新训练吧？我要怎么成功的导出nb模型呢

**Comment by yghstill** [comment]
请参考ppyolo_mobilenet_v3配置文件 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/configs/ppyolo/ppyolo_mobilenet_v3_large.yml#L40 修改nms，然后重新使用tools/export_model.py导出一下模型，再转nb模型。

**Comment by Jorsen0** [comment]
> 请参考ppyolo_mobilenet_v3配置文件 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/configs/ppyolo/ppyolo_mobilenet_v3_large.yml#L40 修改nms，然后重新使用tools/export_model.py导出一下模型，再转nb模型。

你好，我也遇到了相同的问题。
参照您上面的建议，重新导出模型，不再提示op不支持，但出现新的错误：
[W 12/25 13: 1:11.983 /root/Paddle-Lite/lite/api/opt.cc RunOptimize:151] Load combined-param model. Option model_dir will be ignored
[I 12/25 13: 1:11.984 /root/Paddle-Lite/lite/api/cxx_api.cc Build:262] Load model from file.
[I 12/25 13: 1:12.138 /root/Paddle-Lite/lite/core/optimizer.h RunPasses:259] == Running pass: lite_quant_dequant_fuse_pass
[I 12/25 13: 1:12.169 /root/Paddle-Lite/lite/core/optimizer.h RunPasses:283] == Finished running: lite_quant_dequant_fuse_pass
[I 12/25 13: 1:12.169 /root/Paddle-Lite/lite/core/optimizer.h RunPasses:259] == Running pass: weight_quantization_preprocess_pass
[I 12/25 13: 1:12.171 /root/Paddle-Lite/lite/core/optimizer.h RunPasses:283] == Finished running: weight_quantization_preprocess_pass
[I 12/25 13: 1:12.171 /root/Paddle-Lite/lite/core/optimizer.h RunPasses:259] == Running pass: lite_conv_elementwise_fuse_pass
[I 12/25 13: 1:12.185 ...le-Lite/lite/core/mir/pattern_matcher.cc:108 operator()] detected 19 subgraph
[I 12/25 13: 1:12.189 /root/Paddle-Lite/lite/core/optimizer.h RunPasses:283] == Finished running: lite_conv_elementwise_fuse_pass
[I 12/25 13: 1:12.189 /root/Paddle-Lite/lite/core/optimizer.h RunPasses:259] == Running pass: lite_conv_bn_fuse_pass
[I 12/25 13: 1:12.257 ...le-Lite/lite/core/mir/pattern_matcher.cc:108 operator()] detected 52 subgraph
[I 12/25 13: 1:12.282 ...le-Lite/lite/core/mir/pattern_matcher.cc:108 operator()] detected 15 subgraph
[I 12/25 13: 1:12.285 /root/Paddle-Lite/lite/core/optimizer.h RunPasses:283] == Finished running: lite_conv_bn_fuse_pass
[I 12/25 13: 1:12.285 /root/Paddle-Lite/lite/core/optimizer.h RunPasses:259] == Running pass: lite_conv_elementwise_fuse_pass
[I 12/25 13: 1:12.302 /root/Paddle-Lite/lite/core/optimizer.h RunPasses:283] == Finished running: lite_conv_elementwise_fuse_pass
[I 12/25 13: 1:12.302 /root/Paddle-Lite/lite/core/optimizer.h RunPasses:259] == Running pass: lite_conv_conv_fuse_pass
[F 12/25 13: 1:12.304 /root/Paddle-Lite/lite/core/mir/node.cc picked_kernel:32] Check failed: !valid_kernels_.empty(): no kernel for pow
Aborted (core dumped)
望解答☺

**Comment by yghstill** [comment]
@Jorsen0 请更新Paddle Lite版本到2.6.2以上再试一下
