### ISSUE TITLE
无法用mask_rcnn的模型进行图片预测

### ISSUE THREAD

**Issue by shen-wenxin** [PaddlePaddle/PaddleDetection#1956]
您好，我训练跟评估都结束了之后，想进行图片预测，但是报了error错误，能麻烦帮看一下吗？
以下为错误：

TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;Traceback (most recent call last):
  File "tools/infer.py", line 271, in <module>
    main()
  File "tools/infer.py", line 106, in main
    dataset.set_images(test_images)
AttributeError: 'COCODataSet' object has no attribute 'set_images'

**Comment by yghstill** [comment]
配置文件的TestReader麻烦发出来看下？

**Comment by Wenxin-piggy** [comment]
> 配置文件的TestReader麻烦发出来看下？

欸，发现了，是testReader的问题，谢谢。

不过还有一个问题，想问一下，迁移学习的时候label的名字需要自己更改吗。
我将num_classes改为自己的类别之后，进行训练。
之后用图片预测的时候图片上目标位置上框出来的lable还是coco的lable，不是我的lable。那么我改如何改预测的时候lable的名字呢

**Comment by yghstill** [comment]
@shen-wenxin 将anno_path改成你自己的标注json文件就可以解析label。
