### ISSUE TITLE
当返回的roidbs为空时，卡在if isinstance(item, collections.Sequence) and len(item) == 0

### ISSUE THREAD

**Issue by DeniJsonC** [PaddlePaddle/PaddleDetection#1957]
def _load_batch(self):
        batch = []
        bs = 0
        while bs != self._batch_size:
            if self._pos >= self.size():
                break
            pos = self.indexes[self._pos]
            sample = copy.deepcopy(self._roidbs[pos])
            sample["curr_iter"] = self._curr_iter
            self._pos += 1

            if self._drop_empty and self._fields and 'gt_bbox' in sample:
                if _has_empty(sample['gt_bbox']):

经自己测试 如果record有数据 但是roidbs里面bbox数据为[]，会一直循环 跳不出去 望加个判断修复下

**Comment by yghstill** [comment]
感谢反馈，我们修复一下，谢谢。
