### ISSUE TITLE
使用solov2预训练模型做推理，结果仍在在使用我自己训练的权重

### ISSUE THREAD

**Issue by xusufeng** [PaddlePaddle/PaddleDetection#1962]
我用自己的数据训练完solov2模型后发现效果很差，然后尝试用一样的预训练模型solov2_r50_fpn_3x.yml推理测试图片，过程中我把自己训练的模型挪到了别的盘，防止预训练的时候使用我自己训练的权重，结果报错了，预训练的时候在找我训练的权重没找到，请问到底要怎样设置才能用预训练模型来推理？配置文件及命令还有报错如图。
![报错截图](https://user-images.githubusercontent.com/44634287/103118017-14106180-46a8-11eb-99fe-f1e01a6ee82d.png)
![配置文件截图](https://user-images.githubusercontent.com/44634287/103118020-15418e80-46a8-11eb-8fe6-8664d6664916.png)

**Comment by yghstill** [comment]
@xusufeng 看你的配置文件，pretrain_weights是加载训练时的预训练模型，可以是网络链接，weights是训好的模型，在infer时加载。你确认一下到底加载哪个模型去infer，设置weights这个路径就行。

**Comment by xusufeng** [comment]
> @xusufeng 看你的配置文件，pretrain_weights是加载训练时的预训练模型，可以是网络链接，weights是训好的模型，在infer时加载。你确认一下到底加载哪个模型去infer，设置weights这个路径就行。

我在infer的命令里加上了pretrain_weights的路径： python tools/infer.py -c configs/solov2/solov2_r50_fpn_3x.yml -o pretrain_weights=https://paddle-imagenet-models-name.bj.bcebos.com/solov2_r50_fpn_3x_pretrained.tar --infer_img=im_path
还是一样的报错：ValueError: Model pretrain path output/solov2_r50_fpn_3x/model_final does not exists.  还是在找我训练的模型

**Comment by yghstill** [comment]
设置weights指向model_final.pdparams，问题已解决。
