### ISSUE TITLE
使用solov2预训练模型做推理，结果仍在在使用我自己训练的权重

### ISSUE THREAD

**Issue by xusufeng** [PaddlePaddle/PaddleDetection#1963]
我用自己的数据训练完solov2模型后发现效果很差，然后尝试用一样的预训练模型solov2_r50_fpn_3x.yml推理测试图片，过程中我把自己训练的模型挪到了别的盘，防止预训练的时候使用我自己训练的权重，结果报错了，预训练的时候在找我训练的权重没找到，请问到底要怎样设置才能用预训练模型来推理？

配置文件里的pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/solov2_r50_fpn_3x_pretrained.tar
用预训练模型推理的命令为：python tools/infer.py -c configs/solov2/solov2_r50_fpn_3x.yml --infer_img=im_path
报错为：ValueError: Model pretrain path output/solov2_r50_fpn_3x/model_final does not exists.

**Comment by heavengate** [comment]
和 https://github.com/PaddlePaddle/PaddleDetection/issues/1962 为同一问题，由 https://github.com/PaddlePaddle/PaddleDetection/issues/1962 跟进，本issue关闭
