### ISSUE TITLE
mask rcnn 图片预测的label问题

### ISSUE THREAD

**Issue by Wenxin-piggy** [PaddlePaddle/PaddleDetection#1965]
您好，我用预训练的mask rcnn的模型进行了迁移学习。
我的类别只有6类，所以将num_classes改成了6.
然后想用来做图片预测，但是我的预测出来目标位置框出来的label都是coco原先的label，不是我的label，该怎么修改呢。

**Comment by heavengate** [comment]
RCNN系列中分类有背景类，所以目标类别数为6的时候，需要把num_classes设置成7，即6类加上背景类
