### ISSUE TITLE
Memory leak caused the process to be killed while executing the deploy/ python /infer.py 

### ISSUE THREAD

**Issue by kritohyh** [PaddlePaddle/PaddleDetection#1966]
About 2 minutes of video detection takes up 20 G memory

this case will happen when I let use_python_inference: false

**Comment by kritohyh** [comment]
this case will happen when I let use_python_inference: false

**Comment by heavengate** [comment]
`deploy/python/infer.py` provide a demo for video inference and works by inferencing each frame of a video, read the whole video to memory and perform inference and save results in memory too.
If the frame rate of your video is a big value and there is not enough memory, memory leak may cause, please try to use video with shorter time or less frame rate

**Comment by kritohyh** [comment]
> `deploy/python/infer.py` provide a demo for video inference and works by inferencing each frame of a video, read the whole video to memory and perform inference and save results in memory too.
> If the frame rate of your video is a big value and there is not enough memory, memory leak may cause, please try to use video with shorter time or less frame rate

Thank you for your reply.  But I still have some questions.
When use deploy/python/infer.py and set use_python_inference: false on the aistudio, it can process video with fixed memory size.    The above problem only occurs when I use the local computer and the latest version of paddle and PaddleDetection. Is there some problem with the new version of paddle calls in the C++ underlying library?

**Comment by kritohyh** [comment]
> `deploy/python/infer.py` provide a demo for video inference and works by inferencing each frame of a video, read the whole video to memory and perform inference and save results in memory too.
> If the frame rate of your video is a big value and there is not enough memory, memory leak may cause, please try to use video with shorter time or less frame rate
I only have a  video of 200M, and I have 32 g of memory. Now is there any way I can solve this problem?
