### ISSUE TITLE
断点继续训练

### ISSUE THREAD

**Issue by Assnxy** [PaddlePaddle/PaddleDetection#1968]
文档里好像没有提到怎么断点继续训练，我应该怎么做。

**Comment by heavengate** [comment]
使用`-r` 或者`--resume_checkpoint`指定断点权重即可
参考训练脚本参数列表
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/docs/tutorials/GETTING_STARTED_cn.md#可选参数列表
