### ISSUE TITLE
win10,cuda 10.0 paddlepaddle-gpu 推理和评估出错AttributeError: module 'PIL.ImageOps' has no attribute 'exif_transpose'

### ISSUE THREAD

**Issue by gdxytim** [PaddlePaddle/PaddleDetection#1970]
Question as below,DAILAOS help me please.

(paddle) J:\PaddleDetection>python tools/infer.py -c configs/yolov3_mobilenet_v1-zj.yml --infer_dir=dataset/1206/test
2020-12-25 18:00:42,539-INFO: Found 176 inference images in total.
W1225 18:00:42.981472 17260 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W1225 18:00:42.992422 17260 device_context.cc:260] device: 0, cuDNN Version: 7.5.
2020-12-25 18:00:48,211-INFO: Load categories from dataset/1206/label_list.txt
2020-12-25 18:00:48,536-INFO: Infer iter 0
Traceback (most recent call last):
  File "tools/infer.py", line 271, in <module>
    main()
  File "tools/infer.py", line 208, in main
    image = ImageOps.exif_transpose(image)
AttributeError: module 'PIL.ImageOps' has no attribute 'exif_transpose'

**Comment by gdxytim** [comment]
anaconda python 3.7  paddlepaddle-gpu 1.85.  pip list as below:
...
numpy                              1.16.2
numpydoc                           0.8.0
nvidia-ml-py3                      7.352.0
objgraph                           3.5.0
olefile                            0.46
opencv-python                      3.4.2.16
openpyxl                           2.6.1
packaging                          19.0
paddle                             1.0.2
paddlepaddle-gpu                   1.8.5.post107
pandas                             0.24.2
...

**Comment by heavengate** [comment]
看着是PIL库版本的问题，试下这个命令
pip install --upgrade pillow
