### ISSUE TITLE
c++ infer 无法在GPU上训练模型

### ISSUE THREAD

**Issue by stefan-567** [PaddlePaddle/PaddleDetection#1973]
环境：Visual Studio 2017 + CMake 3.15.5 + Opencv-3.4.6-vc14_vc15
CPU可以正常运行，GPU在运行到此段代码处：config.EnableUseGpu(1000, gpu_id)；报错，错误提示Please compile with gpu to EnableGpu()，我在编译的时候“WITH_GPU”也勾选了，cuda的库也添加到属性里面了，这是什么原因造成的错误？

**Comment by qingqing01** [comment]
@stefan-567 您是用的预测库是哪个？请注意选择GPU的预测库

**Comment by stefan-567** [comment]
> @stefan-567 您是用的预测库是哪个？请注意选择GPU的预测库

从这个网站下载的c++预测库：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/windows_cpp_inference.html
下载的版本是cuda10.0_cudnn7_avx_mkl 2.0.0beta0版本

**Comment by qingqing01** [comment]
我们测试下。 @liuhuiCNN @xiegegege 辛苦测试看下

**Comment by xiegegege** [comment]
@stefan-567 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/windows_cpp_inference.html 这个网页上好像已经没有2.0.0beta0了，你方便用cuda10.0_cudnn7_avx_mkl 1.8.4版本试下吗？我测试了是正常的，编译选项可以参考这个图填下
![image](https://user-images.githubusercontent.com/46314656/103537269-1906b980-4ecf-11eb-8d3b-07fa48bad9ac.png)
![image](https://user-images.githubusercontent.com/46314656/103537342-350a5b00-4ecf-11eb-9253-70988bf7068d.png)

**Comment by stefan-567** [comment]
非常感谢您的回复，我去测试一下，有问题再向您请教。


---------------------
Best Regards！
郭   奇
电话：   +86 159 0650 0271

在2021年1月4日 20:57，xiegegege<notifications@github.com> 写道：

@stefan-567https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/windows_cpp_inference.html 这个网页上好像已经没有2.0.0beta0了，你方便用cuda10.0_cudnn7_avx_mkl 1.8.4版本试下吗？我测试了是正常的，编译选项可以参考这个图填下
