### ISSUE TITLE
mask rcnn 图片预测的label问题

### ISSUE THREAD

**Issue by Wenxin-piggy** [PaddlePaddle/PaddleDetection#1975]
还是label遇到的问题，一共是5个分类，但是已经将num_classes设置为6了。
训练完之后用其进行预测，是嘴巴的部位仍然识别为单车。
但是蒙版区域是准的，该怎么处理呢？

**Comment by qingqing01** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/6d67ffafcaae92e6b2877cf6977fbe6ad6f5c6ee/configs/mask_fpn_reader.yml#L79

您注意这里也正确设置下标签。

**Comment by Wenxin-piggy** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/6d67ffafcaae92e6b2877cf6977fbe6ad6f5c6ee/configs/mask_fpn_reader.yml#L79
> 
> 您注意这里也正确设置下标签。

已解决，感谢
