### ISSUE TITLE
量化训练和正常训练的预训练模型是一样的？

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#1976]
yolov3_mobilenetv1量化训练voc精度一开始低于10%，现在最高是72%，感觉不太能接近正常训练76.2%的精度。

**Comment by qingqing01** [comment]
@JensenHJS 可以参考 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-beta/slim/quantization ，MobileNetv1的COCO精度无损，VOC数据应该也接近无损。
