### ISSUE TITLE
fluid.install_check.run_check卡了

### ISSUE THREAD

**Issue by SangerY** [PaddlePaddle/PaddleDetection#1978]
本地ubuntu18.04，虚拟环境virtualenv，python3.6.9，双卡Titan rtx，在运行fluid.install_check.run_check时卡在检查双显卡的地方，卡着不动，电脑死机。
![image](https://user-images.githubusercontent.com/12136347/103251576-2fcf7c80-49b4-11eb-8f93-b6d33f12e4a3.png)

**Comment by jerrywgz** [comment]
从提供的环境来看，cuda10, unbuntu18.04 paddle是支持的，可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/install/pip/linux-pip.html#id4 这个链接里的安装文档check下你的nccl安装是否正确

**Comment by SangerY** [comment]
> 从提供的环境来看，cuda10, unbuntu18.04 paddle是支持的，可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/install/pip/linux-pip.html#id4 这个链接里的安装文档check下你的nccl安装是否正确

在官方下载的local deb，执行
sudo dpkg -i nccl-repo-ubuntu1804-2.6.4-ga-cuda10.0_1-1_amd64.deb
sudo apt install libnccl2=2.6.4-1+cuda10.0 libnccl-dev=2.6.4-1+cuda10.0
怎么检查nccl安装是否正确

**Comment by SangerY** [comment]
是因为check mutiple gpu这一步很慢很慢很慢，至少20min以上，我以为卡住了，这么慢是正常吗？

**Comment by jerrywgz** [comment]
可以先用https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/configs/yolov3_mobilenet_v1_roadsign.yml 这个配置跑下多卡训练看看能否正常运行

**Comment by SangerY** [comment]
训练ppyolo，在这一步一直卡着。
![image](https://user-images.githubusercontent.com/12136347/103391377-2a109d00-4b54-11eb-8fcf-d28591c42f09.png)

**Comment by SangerY** [comment]
使用的ppyolo.yml，train.py，训练batch size改为了16，在index created后，卡了40多分钟，后面可以正常训练。
这个不太正常吧，显卡也不是很弱，titan rtx 2块，一块24G显存。
另外，默认应该用了两块显卡，这个在哪里可以设置指定显卡？

**Comment by SangerY** [comment]
@jerrywgz

**Comment by kaixin-bai** [comment]
遇到一样的问题，单卡可正常训练，双卡就一直卡在`index created!`这里

训练的是`yolov4`

使用的命令是：
```bash
python3 -m paddle.distributed.launch --gpus 6,7 tools/train.py -c ./configs/yolov4/yolov4_cspdarknet_project_coco.yml --use_vdl=true --vdl_log_dir=vdl_dir/project_scalar
```

**Comment by kaixin-bai** [comment]
@SangerY 看了一下发现多卡的训练命令和单卡是不一样的，参考这个[issue](https://github.com/PaddlePaddle/PaddleDetection/issues/1534)

**Comment by kaixin-bai** [comment]
@SangerY 快一年了，你的问题解决了吗？

**Comment by kaixin-bai** [comment]
将paddledetection的branch由release2.2改成develop后可多卡训练
