### ISSUE TITLE
为什么rcnn_enhance里的模型速度这么快？

### ISSUE THREAD

**Issue by Mabinogiysk** [PaddlePaddle/PaddleDetection#1979]
ResNet50-vd-FPN速度大约为22fps，而rcnn_enhance里的baseline能达到43fps的速度，这是怎么做到的？两个模型的唯一区别似乎仅有图片尺寸（800 vs 640），仅通过调整图片大小就能提高一倍速度吗？

**Comment by jerrywgz** [comment]
rcnn_enhance调整了多个模块的参数，比如FPN模块的输入channel，预测阶段get_proposals的输出个数都有减小

**Comment by Mabinogiysk** [comment]
> rcnn_enhance调整了多个模块的参数，比如FPN模块的输入channel，预测阶段get_proposals的输出个数都有减小

感谢，已经确定是图片尺寸的问题。没想到800降到640能提速这么多
