### ISSUE TITLE
如何使用export_model导出自定义reader的模型

### ISSUE THREAD

**Issue by topxxuki** [PaddlePaddle/PaddleDetection#1980]
背景：需要将paddleDetection中的模型导出成paddle格式的模型

执行
python ../tools/export_model.py -c ../../model/params/conf.yaml --output_dir=./inference_model

![image](https://user-images.githubusercontent.com/18697846/103265374-658e5880-49e8-11eb-9a23-a16543268b04.png)

yml文件中在TrainReader自定义了MyVOCDataSet
![image](https://user-images.githubusercontent.com/18697846/103265441-85258100-49e8-11eb-8a6a-0f044dc9175f.png)

**Comment by qingqing01** [comment]
@topxxuki 

请问 MyVOCDataset, 是否类似VOCDataSet，

https://github.com/PaddlePaddle/PaddleDetection/blob/6d67ffafcaae92e6b2877cf6977fbe6ad6f5c6ee/ppdet/data/source/voc.py#L29

添加了register 。并在 data/source/__init__.py 中导出:

https://github.com/PaddlePaddle/PaddleDetection/blob/6d67ffafcaae92e6b2877cf6977fbe6ad6f5c6ee/ppdet/data/source/__init__.py#L16-L20


上面报错，不认识MyVOCDataSet

**Comment by topxxuki** [comment]
> @topxxuki
> 
> 请问 MyVOCDataset, 是否类似VOCDataSet，
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/6d67ffafcaae92e6b2877cf6977fbe6ad6f5c6ee/ppdet/data/source/voc.py#L29
> 
> 添加了register 。并在 data/source/**init**.py 中导出:
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/6d67ffafcaae92e6b2877cf6977fbe6ad6f5c6ee/ppdet/data/source/__init__.py#L16-L20
> 
> 上面报错，不认识MyVOCDataSet

在source里加上类的定义就可以正常转换类，感谢～
