### ISSUE TITLE
使用推理脚本 deploy/python/infer.py 检测视频流时发生内存溢出问题

### ISSUE THREAD

**Issue by kritohyh** [PaddlePaddle/PaddleDetection#1981]
本地环境：32G内存 ubuntu 18系统  30系显卡   paddlepaddle 2.0rc1官方编译版本
将infer_cfg.yml文件的use_python_inference设置为false时，部分内容如下：
use_python_inference: false
mode: fluid
draw_threshold: 0.5
metric: VOC
arch: YOLO
min_subgraph_size: 3
with_background: false
...
对视频流检测时会不断申请内存但不释放， 怀疑是新版paddle C++动态库的问题，因为使用aistudio上的paddle，不存在这个问题， 目前有什么办法快速解决吗？

**Comment by kritohyh** [comment]
> 本地环境：32G内存 ubuntu 18系统 30系显卡 paddlepaddle 2.0rc1官方编译版本
> 将infer_cfg.yml文件的use_python_inference设置为false时，部分内容如下：
> use_python_inference: false
> mode: fluid
> draw_threshold: 0.5
> metric: VOC
> arch: YOLO
> min_subgraph_size: 3
> with_background: false
> ...
> 对视频流检测时会不断申请内存但不释放， 怀疑是新版paddle C++动态库的问题，因为使用aistudio上的paddle，不存在这个问题， 目前有什么办法快速解决吗？

**Comment by jerrywgz** [comment]
请问下使用的预测代码是PaddleDetection中提供的deploy/python吗

**Comment by kritohyh** [comment]
> 请问下使用的预测代码是PaddleDetection中提供的deploy/python吗，我们用2.0rc1确认下

是的  是PaddleDetection项目里附带的推理工具

**Comment by liuhuiCNN** [comment]
感谢反馈问题，我们初步定位到是cudnn8.0.5和cudnn8.0.4 存在内存泄露问题， 切换cudnn8.0.3可以解决。麻烦您反馈一下使用的cudnn版本，建议切换到cudnn8.0.3试试，谢谢！

**Comment by kritohyh** [comment]
> 感谢反馈问题，我们初步定位到是cudnn8.0.5和cudnn8.0.4 存在内存泄露问题， 切换cudnn8.0.3可以解决。麻烦您反馈一下使用的cudnn版本，建议切换到cudnn8.0.3试试，谢谢！

感谢答复！  我的cudnn版本是cudnn-11.1-linux-x64-v8.0.4。

**Comment by liuhuiCNN** [comment]
> > 感谢反馈问题，我们初步定位到是cudnn8.0.5和cudnn8.0.4 存在内存泄露问题， 切换cudnn8.0.3可以解决。麻烦您反馈一下使用的cudnn版本，建议切换到cudnn8.0.3试试，谢谢！
> 
> 感谢答复！ 我的cudnn版本是cudnn-11.1-linux-x64-v8.0.4。

建议试一下cudnn8.0.3，我们其他同事测试了，cudnn8.0.3是没问题的。

**Comment by kritohyh** [comment]
> > > 感谢反馈问题，我们初步定位到是cudnn8.0.5和cudnn8.0.4 存在内存泄露问题， 切换cudnn8.0.3可以解决。麻烦您反馈一下使用的cudnn版本，建议切换到cudnn8.0.3试试，谢谢！
> > 
> > 
> > 感谢答复！ 我的cudnn版本是cudnn-11.1-linux-x64-v8.0.4。
> 
> 建议试一下cudnn8.0.3，我们其他同事测试了，cudnn8.0.3是没问题的。

我下载了cuda11.0 以及 复制了cudnn8.0.3到cuda11.0， 并且修改了/usr/local/cuda 软连接， 但是程序似乎仍然在搜寻cuda-11.1？？？
会报如下错误：
#Could not load library libcudnn_cnn_train.so.8. Error: /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8: ### #symbol _Z6logArgPKcPK21cudnnActivationStructPcPii version libcudnn_ops_infer.so.8 not defined in file #libcudnn_ops_infer.so.8 with link time reference
#Please make sure libcudnn_cnn_train.so.8 is in your library path!
#Please make sure libcudnn_cnn_train.so.8 is in your library path!
这个情况该如何解决， 我的显卡是3090， 驱动信息：Driver Version: 455.45.01    CUDA Version: 11.1

**Comment by kritohyh** [comment]
> > > 感谢反馈问题，我们初步定位到是cudnn8.0.5和cudnn8.0.4 存在内存泄露问题， 切换cudnn8.0.3可以解决。麻烦您反馈一下使用的cudnn版本，建议切换到cudnn8.0.3试试，谢谢！
> > 
> > 
> > 感谢答复！ 我的cudnn版本是cudnn-11.1-linux-x64-v8.0.4。
> 
> 建议试一下cudnn8.0.3，我们其他同事测试了，cudnn8.0.3是没问题的。

我改成使用cuda11.0 与 cudnn8.03   驱动信息：Driver Version: 455.45.01 CUDA Version: 11.1
仍然发生内存泄露。 您能详细一点告诉我，3090显卡该怎么解决这个问题吗， 该使用的具体cuda版本以及除了更换cudnn 还要修改什么？

**Comment by kritohyh** [comment]
> > > 感谢反馈问题，我们初步定位到是cudnn8.0.5和cudnn8.0.4 存在内存泄露问题， 切换cudnn8.0.3可以解决。麻烦您反馈一下使用的cudnn版本，建议切换到cudnn8.0.3试试，谢谢！
> > 
> > 
> > 感谢答复！ 我的cudnn版本是cudnn-11.1-linux-x64-v8.0.4。
> 
> 建议试一下cudnn8.0.3，我们其他同事测试了，cudnn8.0.3是没问题的。

发现一个问题噢  在cuda11.1 cudnn8.03.33环境下， 当我使用yolov4并且设置use_python_inference：false 的时候，就不存在内存泄露的问题， 但是ppyolo却会内存泄露。
