### ISSUE TITLE
关于使用coco预训练模型的问题

### ISSUE THREAD

**Issue by tianlanshidai** [PaddlePaddle/PaddleDetection#1982]
你好！请问，如果我想使用一个coco上预训练好的模型，在我自己的数据集上进行训练，学习率是否需要进行调整（调小）？

**Comment by tianlanshidai** [comment]
训练配置是8卡V100，与官方配置相同

**Comment by qingqing01** [comment]
@tianlanshidai 8卡训练可以先不调整。 最大迭代次数max_iters, lr decay的步长可以依据数据总量，调节下。

**Comment by tianlanshidai** [comment]
> @tianlanshidai 8卡训练可以先不调整。 最大迭代次数max_iters, lr decay的步长可以依据数据总量，调节下。

目前存在的问题是，使用imagenet预训练模型，效果要比coco预训练模型要好，不知道是为什么，
