### ISSUE TITLE
matrix nms的有效性，score值

### ISSUE THREAD

**Issue by Shanyaodedanshen** [PaddlePaddle/PaddleDetection#1983]
我训练了自己的数据集，matrix nms似乎没有太大用处。。。重合度很高的掩膜有很多。挑了pre和post top的两个参数效果不大。。
score为什么会小于0或者大于1呢，谢谢。

**Comment by willthefrog** [comment]
score 会经过 decay, (即 `score = score * decay`, `decay`在 `[0, 1]`范围内），确定score在没过nms之前是在[0, 1]范围内，然后经过nms之后范围变化的吗？
至于是否有效果，这本质上是"no free lunch"的问题了，没有哪个算法可以说在所有数据集都有收益的。
