### ISSUE TITLE
pascalvoc数据集格式是可以直接用的么？为什么将ssd的路径改了之后报错，读取不到数据集

### ISSUE THREAD

**Issue by weiwenxiao0** [PaddlePaddle/PaddleDetection#1986]

**Comment by willthefrog** [comment]
建议使用 [脚本](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-beta/dataset/voc) 下载处理，自己下载的直接解压是用不了的，需要创建对应的列表文件
