### ISSUE TITLE
Argument 'bb' has incorrect type (expected numpy.ndarray, got list)

### ISSUE THREAD

**Issue by PavoneB** [PaddlePaddle/PaddleDetection#1989]
solov2算法在训练模型时一直报错Argument 'bb' has incorrect type (expected numpy.ndarray, got list)，已经是最新版的coco包了，这与json文件标注点的个数不是偶数有关系吗？
    请问有什么解决办法吗？

**Comment by willthefrog** [comment]
@yghstill  能否看下？

**Comment by yghstill** [comment]
已建议使用PaddleDetection中SOLOv2模型https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-beta/configs/solov2
