### ISSUE TITLE
PaddeDetection C++ 预测编译错误（Ubuntu）

### ISSUE THREAD

**Issue by pele228** [PaddlePaddle/PaddleDetection#199]
你好，UBuntu16.04 ，按照给的链接下载编译的opencv3.4.6 编译C++预测接口 make时报错如下：

[ 53%] Built target ext-yaml-cpp
[ 86%] Built target libpaddleseg_inference
make[2]: *** No rule to make target '/home/work/PaddleDetection/opencv3/share/OpenCV/3rdparty/lib64/libIlmImf.a', needed by 'detection_demo'。 停止。
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/detection_demo.dir/all' failed
make[1]: *** [CMakeFiles/detection_demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

缺了一个库libIlmImf.a，是opencv版本不对吗？

**Comment by sjtubinlong** [comment]
@pele228 如果编译不通过，尝试注释掉这些opencv 3rdparty的依赖，后续我们会精简这些依赖，适配不同的 opencv 环境

**Comment by 1224wxwx** [comment]
我发现cmake opencv时候的参数可能给的不对，也导致有文件找不到，后来我去掉了-DCMAKE_INSTALL_LIBDIR=lib64这个参数就对了，但是我后面make的时候又有新的错误...

**Comment by pele228** [comment]
ubutun16.04环境下，编译指南里的opencv cmake缺少了两个选项-DBUILD_JASPER=ON -DBUILD_OPENEXR=ON 和对应的DWITH选项. 否则编译detection_demo会失败提示缺少库.
