### ISSUE TITLE
如何获取预测的数值

### ISSUE THREAD

**Issue by haixuan-2004** [PaddlePaddle/PaddleDetection#1999]
模型训练好后，需要进行预测，手册给的预测命令是：
python deploy/python/infer.py --model_dir=/path/to/models --image_file=/path/to/image
--use_gpu=(False/True)

上面的预测方法直接生成一张图片，但我们想获得预测的结果 ，以供程序作进下一步的逻辑处理，该如何预测。

**Comment by qingqing01** [comment]
@haixuan-2004 

https://github.com/PaddlePaddle/PaddleDetection/blob/90367227629cba535039f98b212b782eb9a2dc57/deploy/python/infer.py#L485

这里返回的结果既为预测得到数值。

**Comment by yghstill** [comment]
@haixuan-2004 由于您长时间未回复，此issue关闭，如还有问题可以重新open或新提issue，谢谢。
