### ISSUE TITLE
使用deploy/python/infer.py对ppyolo推理时发生内存泄漏

### ISSUE THREAD

**Issue by kritohyh** [PaddlePaddle/PaddleDetection#2001]
本地环境：32G内存 ubuntu 18系统 3090显卡 paddlepaddle 2.0rc1官方编译版本
在cuda11.0 与 cuda11.1 + cudnn8.03环境下， 使用ppyolo检测视频流，存在内存泄露的问题。
infer_cfg.yml默认设置如下：
use_python_inference: false
mode: fluid
draw_threshold: 0.5
metric: VOC
arch: YOLO
min_subgraph_size: 3
with_background: false
...

**Comment by liuhuiCNN** [comment]
感谢反馈，关于内存泄漏问题，我们定位到使用paddle 2.0rc1，cuda10.2+cudnn8.0.4、cudnn8.0.5能够复现内存泄漏问题，cuda10.2+cudnn8.0.3正常。有其他同学使用OCR模型预测时，使用paddle 2.0rc1， cuda11.0+cudnn8.0.3、cudnn8.0.4、cudnn8.0.5有内存泄漏，使用cpu正常。可参考 [OCR预测内存泄漏](https://github.com/PaddlePaddle/PaddleOCR/issues/1581)。可以初步定位可能是cuda或cudnn导致的内存泄漏。
建议您测试：（1）CPU下是否正常；（2）使用cuda10.2+cudnn8.0.3是否正常。

**Comment by rillzhang** [comment]
> 感谢反馈，关于内存泄漏问题，我们定位到使用paddle 2.0rc1，cuda10.2+cudnn8.0.4、cudnn8.0.5能够复现内存泄漏问题，cuda10.2+cudnn8.0.3正常。有其他同学使用OCR模型预测时，使用paddle 2.0rc1， cuda11.0+cudnn8.0.3、cudnn8.0.4、cudnn8.0.5有内存泄漏，使用cpu正常。可参考 [OCR预测内存泄漏](https://github.com/PaddlePaddle/PaddleOCR/issues/1581)。可以初步定位可能是cuda或cudnn导致的内存泄漏。
> 建议您测试：（1）CPU下是否正常；（2）使用cuda10.2+cudnn8.0.3是否正常。

3080、3090系列显卡最低支持11.0的cuda，所以第二种方式没法试。第一种cpu方式，验证过是正常的。

**Comment by kritohyh** [comment]
> > 感谢反馈，关于内存泄漏问题，我们定位到使用paddle 2.0rc1，cuda10.2+cudnn8.0.4、cudnn8.0.5能够复现内存泄漏问题，cuda10.2+cudnn8.0.3正常。有其他同学使用OCR模型预测时，使用paddle 2.0rc1， cuda11.0+cudnn8.0.3、cudnn8.0.4、cudnn8.0.5有内存泄漏，使用cpu正常。可参考 [OCR预测内存泄漏](https://github.com/PaddlePaddle/PaddleOCR/issues/1581)。可以初步定位可能是cuda或cudnn导致的内存泄漏。
> > 建议您测试：（1）CPU下是否正常；（2）使用cuda10.2+cudnn8.0.3是否正常。
> 
> 3080、3090系列显卡最低支持11.0的cuda，所以第二种方式没法试。第一种cpu方式，验证过是正常的。

那么自己编译新版的paddlepaddle 可以解决内存泄露的问题吗？

**Comment by liuhuiCNN** [comment]
> > > 感谢反馈，关于内存泄漏问题，我们定位到使用paddle 2.0rc1，cuda10.2+cudnn8.0.4、cudnn8.0.5能够复现内存泄漏问题，cuda10.2+cudnn8.0.3正常。有其他同学使用OCR模型预测时，使用paddle 2.0rc1， cuda11.0+cudnn8.0.3、cudnn8.0.4、cudnn8.0.5有内存泄漏，使用cpu正常。可参考 [OCR预测内存泄漏](https://github.com/PaddlePaddle/PaddleOCR/issues/1581)。可以初步定位可能是cuda或cudnn导致的内存泄漏。
> > > 建议您测试：（1）CPU下是否正常；（2）使用cuda10.2+cudnn8.0.3是否正常。
> > 
> > 
> > 3080、3090系列显卡最低支持11.0的cuda，所以第二种方式没法试。第一种cpu方式，验证过是正常的。
> 
> 那么现在编译哪个版本的paddlepaddle可以解决ppyolo内存泄露的问题，针对30系显卡？

通过QA同学测试，在使用特定OP组合后，cudnn8系列都有内存泄漏，目前确定的cudnn7.6.5是经过长期测试比较稳定且性能稳定的版本。 建议您使用paddle 2.0rc1 + cudnn7.6.5。预测库下载地址： https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/05_inference_deployment/inference/build_and_install_lib_cn.html

**Comment by lfxx** [comment]
> > > > 感谢反馈，关于内存泄漏问题，我们定位到使用paddle 2.0rc1，cuda10.2+cudnn8.0.4、cudnn8.0.5能够复现内存泄漏问题，cuda10.2+cudnn8.0.3正常。有其他同学使用OCR模型预测时，使用paddle 2.0rc1， cuda11.0+cudnn8.0.3、cudnn8.0.4、cudnn8.0.5有内存泄漏，使用cpu正常。可参考 [OCR预测内存泄漏](https://github.com/PaddlePaddle/PaddleOCR/issues/1581)。可以初步定位可能是cuda或cudnn导致的内存泄漏。
> > > > 建议您测试：（1）CPU下是否正常；（2）使用cuda10.2+cudnn8.0.3是否正常。
> > > 
> > > 
> > > 3080、3090系列显卡最低支持11.0的cuda，所以第二种方式没法试。第一种cpu方式，验证过是正常的。
> > 
> > 
> > 那么现在编译哪个版本的paddlepaddle可以解决ppyolo内存泄露的问题，针对30系显卡？
> 
> 通过QA同学测试，在使用特定OP组合后，cudnn8系列都有内存泄漏，目前确定的cudnn7.6.5是经过长期测试比较稳定且性能稳定的版本。 建议您使用paddle 2.0rc1 + cudnn7.6.5。预测库下载地址： [paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/05_inference_deployment/inference/build_and_install_lib_cn.html](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/05_inference_deployment/inference/build_and_install_lib_cn.html)

ppyolov2系列在cudnn8.0以上版本依然存在内存泄露问题
