### ISSUE TITLE
在跑dcn里面的faster rcnn 50网络的时候报维度错误

### ISSUE THREAD

**Issue by pt1003482256** [PaddlePaddle/PaddleDetection#2003]
`    InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 100, 147] and the shape of Y = [1, 256, 100, 148]. Received [147] in X is not equal to [148] in Y at i:3.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
      [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
      [operator < elementwise_add > error]
terminate called without an active exception

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1609816711 (unix time) try "date -d @1609816711" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e8000018fa) received by PID 6394 (TID 0x7fa8fffff700) from PID 6394 ***]

Aborted (core dumped)`

**Comment by jerrywgz** [comment]
这个模型要求在预处理中增加PadBatch，将图片padding成32的倍数

**Comment by wjplove8** [comment]
> 这个模型要求在预处理中增加PadBatch，将图片padding成32的倍数

这个是fasterrcnn模型的要求还是说是paddledetection这样要求的？在哪里查这些参数要求
