### ISSUE TITLE
运行paddledetection/slim/quantization压缩自己的模型报错

### ISSUE THREAD

**Issue by aixier** [PaddlePaddle/PaddleDetection#201]
环境：
![image](https://user-images.githubusercontent.com/7700464/73135652-74091d00-407f-11ea-8546-8a4ecb2ade73.png)

执行文件：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/slim/quantization/compress.py

运行命令：

```python
python compress.py  \
  -s yolov3_mobilenet_v1_slim.yaml \
  -c  ../../configs/yolov3_mobilenet_v1.yml  \
  -d "../../../../data/coco"  \
  -o max_iters=100  \
  LearningRate.base_lr=0.00005  \
  LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [516, 1012]}]" \  
  YoloTrainFeed.batch_size=2
```

出错信息：

```shell
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 593, in run
    self._eval(context)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 542, in _eval
    func(self.eval_graph.program, self.scope))
  File "compress.py", line 220, in eval_func
    FLAGS.output_eval)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/eval_utils.py", line 205, in eval_results
    is_bbox_normalized=is_bbox_normalized)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/coco_eval.py", line 86, in bbox_eval
    results, clsid2catid, is_bbox_normalized=is_bbox_normalized)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/coco_eval.py", line 215, in bbox2out
    im_id = int(im_ids[i][0])
```

**Comment by aixier** [comment]
@qingqing01

**Comment by ysh329** [comment]
没用过PaddleSlim对这个不了解，我看了下你的命令格式重新给你编辑了，希望在检查一下输入的命令是否正确。例如，加一些打印，看能否正常解析，符合自己设置的预期等等。

**Comment by qingqing01** [comment]
@aixier 请更新下代码试下，这个PR https://github.com/PaddlePaddle/PaddleDetection/pull/53/files 修复过。

**Comment by qingqing01** [comment]
@aixier 请问是否解决，另外，master分支了更新了最新的压缩示例。

**Comment by aixier** [comment]
paddledetection 版本：
release/0.1 
运行指令：
python compress.py     -s yolov3_mobilenet_v1_slim.yaml     -c ../../configs/mj_yolov3_darknet.yml     -d "../../../data/coco"     -o max_iters=1     LearningRate.base_lr=0.0001     LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [258, 516]}]"     YoloTrainFeed.batch_size=1
得到结果：
loading annotations into memory...
Done (t=127.32s)
creating index...
index created!
2020-02-07 15:03:08,873-INFO: Start evaluate...
Loading and preparing results...
Killed
aistudio弹窗提示内存溢出。
问题是：
如何减少内存占用？
普通训练没有问题，量化训练有问题。
硬件配置：
CPU
8
RAM
32GB
GPU
v100
显存
16GB
磁盘
100GB
@qingqing01

**Comment by qingqing01** [comment]
> python compress.py -s yolov3_mobilenet_v1_slim.yaml -c ../../configs/mj_yolov3_darknet.yml 
> 普通训练没有问题，量化训练有问题。


你这里跑的是量化吗？ 为什么有2个config呢？

**Comment by aixier** [comment]
按照readme说明跑的https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/slim/quantization/README.md

![image](https://user-images.githubusercontent.com/7700464/74116733-dae61480-4bef-11ea-8920-a2074f256a16.png)

**Comment by slf12** [comment]
> 按照readme说明跑的https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/slim/quantization/README.md
> 
> ![image](https://user-images.githubusercontent.com/7700464/74116733-dae61480-4bef-11ea-8920-a2074f256a16.png)
> step1: 设置gpu卡
> 
> export CUDA_VISIBLE_DEVICES=0
> step2: 开始训练 使用PaddleDetection提供的配置文件在用8卡进行训练：
> 
> python compress.py
> -s yolov3_mobilenet_v1_slim.yaml
> -c ../../configs/yolov3_mobilenet_v1_voc.yml
> -d "../../dataset/voc"
> -o max_iters=258
> LearningRate.base_lr=0.0001
> LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [258, 516]}]"
> pretrain_weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_mobilenet_v1_voc.tar
> YoloTrainFeed.batch_size=64
> 
> @qingqing01

设置1个gpu卡时，将batchsize设为8试下？

**Comment by aixier** [comment]
好

**Comment by aixier** [comment]
换成8没有问题了

**Comment by aixier** [comment]
换成8解决了上述问题。有了新问题：
说是Bad address。
读不到：/home/aistudio/.local/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py 这个文件

@qingqing01 
完整信息
Loading and preparing results...
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 593, in run
    self._eval(context)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 542, in _eval
    func(self.eval_graph.program, self.scope))
  File "compress.py", line 221, in eval_func
    FLAGS.output_eval)
  File "/home/aistudio/PaddleDetection/ppdet/utils/eval_utils.py", line 205, in eval_results
    is_bbox_normalized=is_bbox_normalized)
  File "/home/aistudio/PaddleDetection/ppdet/utils/coco_eval.py", line 96, in bbox_eval
    map_stats = cocoapi_eval(outfile, 'bbox', coco_gt=coco_gt)
  File "/home/aistudio/PaddleDetection/ppdet/utils/coco_eval.py", line 143, in cocoapi_eval
    coco_dt = coco_gt.loadRes(jsonfile)
  File "/home/aistudio/.local/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 309, in loadRes
    anns = json.load(open(resFile))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
OSError: [Errno 14] Bad address
2020-02-12 00:48:16,564-ERROR: None
2020-02-12 00:48:16,564-ERROR: None

**Comment by slf12** [comment]
> 换成8解决了上述问题。有了新问题：
> 说是Bad address。
> 读不到：/home/aistudio/.local/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py 这个文件
> 
> @qingqing01
> 完整信息
> Loading and preparing results...
> Traceback (most recent call last):
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 593, in run
> self._eval(context)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 542, in _eval
> func(self.eval_graph.program, self.scope))
> File "compress.py", line 221, in eval_func
> FLAGS.output_eval)
> File "/home/aistudio/PaddleDetection/ppdet/utils/eval_utils.py", line 205, in eval_results
> is_bbox_normalized=is_bbox_normalized)
> File "/home/aistudio/PaddleDetection/ppdet/utils/coco_eval.py", line 96, in bbox_eval
> map_stats = cocoapi_eval(outfile, 'bbox', coco_gt=coco_gt)
> File "/home/aistudio/PaddleDetection/ppdet/utils/coco_eval.py", line 143, in cocoapi_eval
> coco_dt = coco_gt.loadRes(jsonfile)
> File "/home/aistudio/.local/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 309, in loadRes
> anns = json.load(open(resFile))
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/**init**.py", line 293, in load
> return loads(fp.read(),
> OSError: [Errno 14] Bad address
> 2020-02-12 00:48:16,564-ERROR: None
> 2020-02-12 00:48:16,564-ERROR: None

需要先安装coco api, https://paddledetection.readthedocs.io/zh/latest/tutorials/INSTALL_cn.html

**Comment by aixier** [comment]
@qingqing01 开始以为漏装了cocoapi,后来确认装了，用过环境校验工具校验了。
还是出现这个
Done (t=110.11s)
creating index...
index created!
2020-02-14 19:22:21,444-INFO: Start evaluate...
Loading and preparing results...
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 593, in run
    self._eval(context)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 542, in _eval
    func(self.eval_graph.program, self.scope))
  File "compress.py", line 221, in eval_func
    FLAGS.output_eval)
  File "/home/aistudio/PaddleDetection/ppdet/utils/eval_utils.py", line 205, in eval_results
    is_bbox_normalized=is_bbox_normalized)
  File "/home/aistudio/PaddleDetection/ppdet/utils/coco_eval.py", line 96, in bbox_eval
    map_stats = cocoapi_eval(outfile, 'bbox', coco_gt=coco_gt)
  File "/home/aistudio/PaddleDetection/ppdet/utils/coco_eval.py", line 143, in cocoapi_eval
    coco_dt = coco_gt.loadRes(jsonfile)
  File "/home/aistudio/.local/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 309, in loadRes
    anns = json.load(open(resFile))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),

**Comment by slf12** [comment]
> ## @qingqing01 开始以为漏装了cocoapi,后来确认装了，用过环境校验工具校验了。
> aistudio@jupyter-27609-191357:~/PaddleDetection$ python ppdet/modeling/tests/test_architectures.py............
> Ran 12 tests in 3.888s
> 
> OK
> 还是出现这个
> Done (t=110.11s)
> creating index...
> index created!
> 2020-02-14 19:22:21,444-INFO: Start evaluate...
> Loading and preparing results...
> Traceback (most recent call last):
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 593, in run
> self._eval(context)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 542, in _eval
> func(self.eval_graph.program, self.scope))
> File "compress.py", line 221, in eval_func
> FLAGS.output_eval)
> File "/home/aistudio/PaddleDetection/ppdet/utils/eval_utils.py", line 205, in eval_results
> is_bbox_normalized=is_bbox_normalized)
> File "/home/aistudio/PaddleDetection/ppdet/utils/coco_eval.py", line 96, in bbox_eval
> map_stats = cocoapi_eval(outfile, 'bbox', coco_gt=coco_gt)
> File "/home/aistudio/PaddleDetection/ppdet/utils/coco_eval.py", line 143, in cocoapi_eval
> coco_dt = coco_gt.loadRes(jsonfile)
> File "/home/aistudio/.local/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 309, in loadRes
> anns = json.load(open(resFile))
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/**init**.py", line 293, in load
> return loads(fp.read(),

这个错误只出现在量化之后eval的时候吗？正常eval的时候出现吗？

**Comment by aixier** [comment]
是的

**Comment by slf12** [comment]
> 是的@slf12

看了下coco.py和 json/init.py这两个文件，是在加载coco的预测结果时出了问题，可先查看下运行compress.py时设置的output_eval文件夹下是否存在bbox.json，如果存在的话这个文件是否存在格式问题

**Comment by aixier** [comment]
仔细研究slim自己实现也量化吧

**Comment by slf12** [comment]
> 存在bbox.json，但是是你们的代码自动生成的。我没有修改任何代码。还是仔细研究slim自己实现也量化吧，谢谢

slim量化功能进行了重构，重构之后在paddledetection中的使用方法在这里，https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.2/slim/quantization，使用方法简单了很多，不需要改很多 paddledetection 代码， 有兴趣可以看下。

**Comment by TianyouChen** [comment]
我在V100上跑slim（release/0.2版本）量化任务，执行如下指令：
python3 slim/quantization/train.py --not_quant_pattern slim_output --eval --c ./configs/ssd/ssd_mobilenet_v1_voc.yml -o max_iters=30000 save_dir=./output/mobilenetv1_slim LearningRate.base_lr=0.0001 LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [10000]}]" pretrain_weights=https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_voc.tar
报错，报错信息如下：
Traceback (most recent call last):
  File "slim/quantization/train.py", line 314, in <module>
    main()
  File "slim/quantization/train.py", line 193, in main
    ignore_params=ignore_params)
  File "/home/chenchaocun/PaddleDetection_slim_branch/slim/quantization/ppdet/utils/checkpoint.py", line 125, in load_params
    fluid.load(prog, path, executor=exe)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/io.py", line 1577, in load
    "Parameter file [{}] not exits".format(parameter_file_name)
AssertionError: Parameter file [/home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc.pdparams] not exits
官方下载的预训练模型不是.pdparams后缀的文件，但是这个训练需要.pdparams文件，这个怎么解决呢？@qingqing01

**Comment by qingqing01** [comment]
@TianyouChen 不知道现在是否还有问题，0.2和0.3分支代码均支持加载非.pdparams结尾的模型。
