### ISSUE TITLE
请问yolo系列的模型有针对小目标的优化吗

### ISSUE THREAD

**Issue by ash12358** [PaddlePaddle/PaddleDetection#2013]
1. 请问yolo系列的模型有针对小目标的优化吗
2. 请问在pp-yolo、yolov3、yolov4中有没有yolo+fpn这种配置文件
3. 还有就是[yolov4](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-beta/configs/yolov4)中的PAN模块应该怎么使用呢

**Comment by wangxinxin08** [comment]
1. 目前yolo系列没有针对小目标做过特别的优化，不过ppyolo在coco上APs已经不低了
2. ppyolo, yolov3, yolov4都是存在fpn的，这一部分的结构存在于yolo_head中，现在静态图是把fpn写在head里面的
3. yolov4的pan模块是一种特征融合方式，你可以用它来替代其他的head中的特征融合模块，比如ppyolo和yolo中fpn，这一部分要写一下代码

**Comment by ash12358** [comment]
好的，谢谢

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen issue
