### ISSUE TITLE
使用自己的coco数据集除了路径还需要修改什么？

### ISSUE THREAD

**Issue by PavoneB** [PaddlePaddle/PaddleDetection#2014]
在yml文件中已经设置好路径了，但是在运行时还会从官网下载train2017.zip的官方数据集，怎样能取消使用默认数据集呢？

**Comment by yghstill** [comment]
@PavoneB 发下你的dataset配置，应该是路径解析不成功就会加载官方coco数据

**Comment by yyyssq** [comment]
@PavoneB 大佬，自动下载数据集这个问题有解决吗？
