### ISSUE TITLE
请问一下，“小bs+大backbone”跟“大bs+小backbone”在相同的iterations次数下哪一种效果更好呢？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleDetection#2017]
尊敬的开发者，你好，
请问一下，“小bs+大backbone”（比如：bs=4，resnet101），跟“大bs+小backbone”（比如：bs=32,resnet50），在相同的iterations次数下哪一种效果更好呢？

期待你的回复！

**Comment by yghstill** [comment]
- 在相同iterations数前提下，batch size越大epoch就越多，效果应该会更好。
- 比如一些模型使用bn或者sync bn，大的batch size有助于模型更好的收敛。大的batch size训练在模型梯度更新时也更有利找到全局最优。
- 至于backbone大小，一般根据显存占用来决定batch size大小，如果backbone小，在显存允许的情况下，就可以设置batch size大一点。
具体没有很严格的效果界定，需要根据原理去分析。

**Comment by songyuc** [comment]
好的，谢谢你！
