### ISSUE TITLE
我想在ppyolo里面训练还有gt为0的图片，需要设置什么么

### ISSUE THREAD

**Issue by pt1003482256** [PaddlePaddle/PaddleDetection#2018]

**Comment by yghstill** [comment]
ppyolo支持输入gt为空，
- 需要你修改数据解析https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/ppdet/data/source/coco.py#L149-L150  不过滤gt为零的情况
- 将reader中的drop_empty 设为false: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/ppdet/data/reader.py#L196

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题，请reopen这个issue~
