### ISSUE TITLE
EfficientDet做迁移学习的时候finetune_exclude_pretrained_params字段应该填什么参数

### ISSUE THREAD

**Issue by shen-wenxin** [PaddlePaddle/PaddleDetection#2019]
根据迁移学习的文档的指导，要修改finetune_exclude_pretrained_params的参数部分。
但是文档中没给出finetune_exclude_pretrained_params参数部分应该的修改值。
那么我应该填什么呢？

**Comment by yghstill** [comment]
@Wenxin-piggy 利用最新PaddleDetection的不再需要设置finetune_exclude_pretrained_params参数了，你直接加载训好的EfficientDet权重进行迁移学习即可，shape不匹配的权重不会加载进网络。

**Comment by Wenxin-piggy** [comment]
> @Wenxin-piggy 利用最新PaddleDetection的不再需要设置finetune_exclude_pretrained_params参数了，你直接加载训好的EfficientDet权重进行迁移学习即可，shape不匹配的权重不会加载进网络。

您好，您的意思是像mask rcnn这些的也不需要设置finetune_exclude_pretrained_params即可进行迁移学习了吗?那我之前训练这些的时候有设置finetune_exclude_pretrained_params，是否会有影响呢？

**Comment by yghstill** [comment]
是的，不需要设置了，设置了finetune_exclude_pretrained_params也没有影响
