### ISSUE TITLE
在新的2.0版本代码里，faster rcnn resnet50作为前置网络的算法比0.4版本的代码map显示低了30%左右，同样的数据集，学习率啥的也都一样

### ISSUE THREAD

**Issue by pt1003482256** [PaddlePaddle/PaddleDetection#2025]

**Comment by heavengate** [comment]
你好，faster rcnn的mAP应该一直是ok的，你0.4版本和2.0版本用的是同一个模型么？麻烦把用的Paddle和PaddleDetection版本和配置文件麻烦发一下，我们确认一下

**Comment by pt1003482256** [comment]
> 你好，faster rcnn的mAP应该一直是ok的，你0.4版本和2.0版本用的是同一个模型么？麻烦把用的Paddle和PaddleDetection版本和配置文件麻烦发一下，我们确认一下


[对比.zip](https://github.com/PaddlePaddle/PaddleDetection/files/5794707/default.zip)
paddle 版本是1.8.5.post107

**Comment by pt1003482256** [comment]
> 你好，faster rcnn的mAP应该一直是ok的，你0.4版本和2.0版本用的是同一个模型么？麻烦把用的Paddle和PaddleDetection版本和配置文件麻烦发一下，我们确认一下

后面测试的时候2.0 的结果是极差的，感觉怀疑是里面的代码动过了

**Comment by thinkthinking** [comment]
欢迎在最新版本测试，如有问题reopen该issue。
