### ISSUE TITLE
使用mask_rcnn_r50_1x时报错

### ISSUE THREAD

**Issue by Curry41** [PaddlePaddle/PaddleDetection#2026]
![image](https://user-images.githubusercontent.com/64341743/103980158-48ad0e80-51ba-11eb-8c39-75b0dd0b4ab5.png)
我用了ms coco，然后用coco manager处理了label，只保留了car类，按照其他的issues将categoryid改为从1开始还是报错

**Comment by Curry41** [comment]
升级到2.0版本的paddle后有报如下错误：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
3   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
4   paddle::framework::details::OpHandleBase::Run(bool)
5   paddle::framework::details::ComputationOpHandle::RunImpl()
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
9   std::vector<paddle::framework::Tensor, std::allocator<paddle::framework::Tensor> > paddle::operators::SampleMaskForOneImage<float>(paddle::platform::CPUDeviceContext const&, paddle::framework::Tensor const&, paddle::framework::Tensor const&, paddle::framework::Tensor const&, paddle::framework::Tensor const&, paddle::framework::Tensor const&, paddle::framework::Tensor const&, int, int, std::vector<paddle::framework::Vector<unsigned long>, std::allocator<paddle::framework::Vector<unsigned long> > > const&)
10  paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
11  paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
12  paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
13  paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
14  paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
15  void* paddle::memory::legacy::Alloc<paddle::platform::CPUPlace>(paddle::platform::CPUPlace const&, unsigned long)
16  paddle::memory::detail::BuddyAllocator::Alloc(unsigned long)
17  paddle::memory::detail::BuddyAllocator::SplitToAlloc(std::_Rb_tree_const_iterator<std::tuple<unsigned long, unsigned long, void*> >, unsigned long)
18  paddle::memory::detail::MemoryBlock::Split(paddle::memory::detail::MetadataCache*, unsigned long)
19  paddle::framework::SignalHandle(char const*, int)
20  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1610179530 (unix time) try "date -d @1610179530" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x100000029) received by PID 1134 (TID 0x7f04e9483700) from PID 41 ***]

Segmentation fault (core dumped)

**Comment by Curry41** [comment]
同样的指令有时也会报如下错误：
Traceback (most recent call last):
  File "tools/train.py", line 372, in <module>
    main()
  File "tools/train.py", line 245, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1106, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1249, in _run_impl
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 911, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
ValueError: In user code:

    File "tools/train.py", line 372, in <module>
      main()
    File "tools/train.py", line 118, in main
      train_fetches = model.train(feed_vars)
    File "/home/aistudio/PaddleDetection-release-0.4/ppdet/modeling/architectures/mask_rcnn.py", line 333, in train
      return self.build(feed_vars, 'train')
    File "/home/aistudio/PaddleDetection-release-0.4/ppdet/modeling/architectures/mask_rcnn.py", line 134, in build
      labels_int32=labels_int32)
    File "/home/aistudio/PaddleDetection-release-0.4/ppdet/core/workspace.py", line 164, in partial_apply
      return op(*args, **kwargs_)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/detection.py", line 2883, in generate_mask_labels
      'resolution': resolution})
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2846, in append_op
      attrs=kwargs.get("attrs", None))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1931, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The size of memory block (0) to split is not larger than size of request memory (4096)
      [Hint: Expected desc->total_size >= size, but received desc->total_size:0 < size:4096.] (at /paddle/paddle/fluid/memory/detail/memory_block.cc:46)
      [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
      [operator < generate_mask_labels > error]
terminate called without an active exception


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1610179435 (unix time) try "date -d @1610179435" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e8000003b8) received by PID 952 (TID 0x7f6672607700) from PID 952 ***]

Aborted (core dumped)

**Comment by Curry41** [comment]
麻烦官方回复一下，需要什么材料我再补

**Comment by yghstill** [comment]
@Curry41 你是不是将num_classes改成2了？

**Comment by Curry41** [comment]
> @Curry41 你是不是将num_classes改成2了？

改成了1，因为就一个类

**Comment by yghstill** [comment]
@Curry41 如果只有1类，num_classes需要设置成2，rcnn模型需要加上background背景类

**Comment by yghstill** [comment]
@Curry41 由于您长时间未回复，此issue关闭，如还有问题可以重新open或新提issue，谢谢。
