### ISSUE TITLE
我感觉你们文档写的有问题

### ISSUE THREAD

**Issue by wangzigongsi** [PaddlePaddle/PaddleDetection#203]
![image](https://user-images.githubusercontent.com/43198176/73635632-e17c0580-469e-11ea-915c-1bbfdab73422.png)
这个im_info中的scale应该是指图像卷积完后的尺寸/输入时图像resize的固定尺寸。
但是我看了paddledetection源码和aistu上的案例，im_info都是输入时图像resize的固定尺寸/图像原来的尺寸，举一个例子
图像原来的尺寸：1320
输入时图像resize的固定尺寸：1300
图像卷积完后的尺寸：1300/16=86.25
![image](https://user-images.githubusercontent.com/43198176/73636004-b47c2280-469f-11ea-836c-309c504f74eb.png)
![image](https://user-images.githubusercontent.com/43198176/73636111-0de45180-46a0-11ea-80f2-3a5c50eeaadf.png)

**Comment by wangzigongsi** [comment]
im_info文档中写的信息和你们实际的用法不一样

**Comment by wangzigongsi** [comment]
按理scale=86.25，但是按照你们样例代码看就是1300/1320
这样表示的

**Comment by wangzigongsi** [comment]
这让我很疑惑

**Comment by wangzigongsi** [comment]
还有一个案列螺母识别也是这个问题

**Comment by wangzigongsi** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/122275?qq-pf-to=pcqq.c2c

**Comment by wangzigongsi** [comment]
![image](https://user-images.githubusercontent.com/43198176/73707921-da550600-4737-11ea-9afd-cd584bbe4428.png)
![image](https://user-images.githubusercontent.com/43198176/73707937-e4770480-4737-11ea-9639-84edf8e4b706.png)

**Comment by wanghaoshuang** [comment]
@wangzigongsi 非常感谢反馈，我们先确认下，稍后回复您。

**Comment by qingqing01** [comment]
@wangzigongsi 非常感谢细致的反馈，文档确实有问题，实际代码没问题，是 "输入时图像resize的固定尺寸/图像原来的尺寸"。我们修改下文档，抱歉给您带来的困扰，再次感谢反馈~

**Comment by wangzigongsi** [comment]
> @wangzigongsi 非常感谢细致的反馈，文档确实有问题，实际代码没问题，是 "输入时图像resize的固定尺寸/图像原来的尺寸"。我们修改下文档，抱歉给您带来的困扰，再次感谢反馈~

请问你们仔细检查一下以下函数，这些都涉及到了im_info
fluid.layers.generate_proposals
fluid.layers.generate_proposal_labels
fluid.layers.rpn_target_assign
fluid.layers.box_coder
fluid.layers.box_clip

**Comment by wangzigongsi** [comment]
还有rpn网络本身比较复杂，你们文档写的不是很清晰，比如
![image](https://user-images.githubusercontent.com/43198176/73715457-f617d680-474e-11ea-894e-616630686d9c.png)
这个函数产生anchers，返回值的anchers(xmin,ymin,xmax,ymax)是基于featuremap像素点的映射，还是(xmin,ymin,xmax,ymax)已经是对于原图的映射框的大小？

**Comment by wangzigongsi** [comment]
我是一个paddle初学者，初学者对开发文档参考很重要，我也希望帮助paddle成长，如果有需要，我们可仔细讨论一些函数在文档中的注释写法，帮助初学者更好理解和学习paddle

**Comment by qingqing01** [comment]
> 我是一个paddle初学者，初学者对开发文档参考很重要，我也希望帮助paddle成长，如果有需要，我们可仔细讨论一些函数在文档中的注释写法，帮助初学者更好理解和学习paddle

没问题，完全可以，我们非常欢迎大家贡献。您提到文档点，我们已列到改进内容里了，多谢了~

**Comment by qingqing01** [comment]
添加了一个参数说明的文档: https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/advanced_tutorials/RCNN_PARAMS_DOC.md
