### ISSUE TITLE
YOLOv3设置正负样本IOU阈值是哪里设置吗

### ISSUE THREAD

**Issue by biao321** [PaddlePaddle/PaddleDetection#2030]

**Comment by heavengate** [comment]
YOLOv3的正负样本不是通过IoU阈值区分的，是通过是否有gtbox落在那个网格的那个anchor上来确定是否是正负样本，另外有一个ignore_thresh在YOLOv3Loss里配置，是指没有gtbox落在那个网格上但是这个anchor与任意一个gtbox的IoU > ignore_thresh，那么既不算正样本，也不算负样本

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen issue
