### ISSUE TITLE
coco类型数据自动加上segmention，以至过不了coco的审查

### ISSUE THREAD

**Issue by w867066886** [PaddlePaddle/PaddleDetection#2032]
自己生成的coco类型，没有segmentation属性，在运行程序读入时会自动加上，并且是空列表，在/PaddleDetection/ppdet/data/source/coco.py 文件的第169行处通过不了，建议更改为
  `if 'segmentation' in box and bos['segmentation']:`

**Comment by w867066886** [comment]
写错了，是  `if 'segmentation' in box and box['segmentation']:`

**Comment by qingqing01** [comment]
@w867066886 收到，感谢反馈
