### ISSUE TITLE
请问一下，现在主干网络resnet.py是默认就是resnext吗？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleDetection#2036]
尊敬的开发者，你好，
请问一下，现在主干网络resnet.py是默认就是resnext吗？
因为我看到这样的代码，感觉有点奇怪，
![image](https://user-images.githubusercontent.com/27288110/104150344-9b820280-5414-11eb-9810-f3167308d2a1.png)

期待你的回复！

**Comment by qingqing01** [comment]
@songyuc 

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/ppdet/modeling/backbones/resnet.py  默认是ResNet。 

ResNeXt是:  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/ppdet/modeling/backbones/resnext.py#L27

**Comment by songyuc** [comment]
@qingqing01 ，你好，请问一下，为什么`resnet.py`中会出现resnext的代码呢，
https://github.com/PaddlePaddle/PaddleDetection/blob/60526c1e29dc5a8780732ebd85923fc5996b6062/ppdet/modeling/backbones/resnet.py#L298-L307

**Comment by qingqing01** [comment]
@songyuc 

ResNeXt的源码继承了ResNet:

https://github.com/PaddlePaddle/PaddleDetection/blob/7c0abad45357265c303dfcbacfadf173e7893832/ppdet/modeling/backbones/resnext.py#L27

**Comment by songyuc** [comment]
@songyuc ，感觉有点奇怪，不是十分清晰，

**Comment by songyuc** [comment]
建议将resnet.py中关于ResNext的代码进行优化，免得容易产生混淆，
