### ISSUE TITLE
基于预训练模型进行微调 有没有教程可以参考？

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/PaddleDetection#2038]
基于预训练模型进行微调 有没有教程可以参考？ 
比如：
coco 80类别

我自己的数据集是类别都是vehicle

**Comment by habout632** [comment]
之前我用的是yolo v3 enhanced

**Comment by qingqing01** [comment]
@habout632 可以直接加载COCO的预训练模型，比如YOLOv3 Enhanced里选COCO模型 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/docs/featured_model/YOLOv3_ENHANCEMENT.md#%E6%A8%A1%E5%9E%8B%E6%95%88%E6%9E%9C  在YML中作为pretrained的weights即可。

会自动加载参数，shape不匹配的(因为类别数不匹配的)会自动过滤掉。

**Comment by habout632** [comment]
可以在YOLOv3 ResNet50_vd DCN DropBlock IoULoss.yml这个基础上 进行finetune么？
![Uploading 3e5c96bdf35b490faf9f6c6c054b4b6c_669b3de0203d4ca49f62969a5384f610.JPEG…]()

**Comment by habout632** [comment]
我改了一下配置文件 训练的图片 怎么变成这样子了？

**Comment by habout632** [comment]
![3a743ecc146c4f348c86fad2d86bdd96_7f1cb8ed9e6547a9885157cc731fb6bf](https://user-images.githubusercontent.com/3166070/104188175-c9d30280-5453-11eb-8730-88225213a913.jpg)
![5b2c821ddd7e4c0189f10359bb84844f_2327cc5b342841a38840f1510862db01](https://user-images.githubusercontent.com/3166070/104188191-cf304d00-5453-11eb-970d-64947db3417c.jpeg)

**Comment by habout632** [comment]
全是person 但是我的标签是vehicle

**Comment by qingqing01** [comment]
@habout632 标签的问题，请注意设置TestReader中的标注信息:

您如果是VOC数据，参考下面，设置anno_path:

https://github.com/PaddlePaddle/PaddleDetection/blob/60526c1e29dc5a8780732ebd85923fc5996b6062/configs/yolov3_mobilenet_v1_roadsign.yml#L152-L160

如果是COCO数据，参考下面，设置anno_path:


https://github.com/PaddlePaddle/PaddleDetection/blob/60526c1e29dc5a8780732ebd85923fc5996b6062/configs/dcn/yolov3_enhance_reader.yml#L83-L90

**Comment by heavengate** [comment]
鉴于当前问题已经解决，issue关闭，如果还有问题可以reopen这个issue~
