### ISSUE TITLE
C++部署 issue

### ISSUE THREAD

**Issue by LoverHaHa** [PaddlePaddle/PaddleDetection#2039]
release/2.0-beta代码分支
CPP打包部署时，cmake文件需要libpaddle_fluid.lib
但是Windows 预测库cuda10.0_cudnn7_avx_mkl
（paddle_inference.zip）没有这个文件导致无法编译，请帮忙fix

**Comment by qingqing01** [comment]
@LoverHaHa  您是否下载了 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc1/guides/05_inference_deployment/inference/windows_cpp_inference.html#id1  这里的预测库吗？

**Comment by liuhuiCNN** [comment]
> libpaddle_fluid.lib

将libpaddle_fluid.lib 改成paddle_fluid.lib。您可以参考下：https://github.com/PaddlePaddle/PaddleDetection/pull/2042

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题，请reopen这个issue~
