### ISSUE TITLE
训练ppyolo，loss出现nan

### ISSUE THREAD

**Issue by hotpeppeper** [PaddlePaddle/PaddleDetection#2040]
![image](https://user-images.githubusercontent.com/15924284/104177938-8d4bda80-5444-11eb-9b31-d26b352d86dd.png)
使用自己做的数据集，batch_size设置成8，设成32或16会出现内存溢出错误

**Comment by qingqing01** [comment]
@hong19860320 请问您是单卡训练，还是8卡训练？如果是单卡训练，请注意按照 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/docs/FAQ.md#faq%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98 调整lr。
