### ISSUE TITLE
yolov3 enhanced预训练模型对应的类别数是多少？

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/PaddleDetection#2045]
是object365的365个类别么 还是coco的80个类别

**Comment by qingqing01** [comment]
@habout632 

这个预训练模型是object365上训练的，类别是365类:

https://github.com/PaddlePaddle/PaddleDetection/blob/a633cd0e753e4f2a78675023c2f0f9d98d3e7488/configs/dcn/yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.yml#L8


[模型库提供的](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/docs/featured_model/YOLOv3_ENHANCEMENT.md#%E6%A8%A1%E5%9E%8B%E6%95%88%E6%9E%9C)模型，是用object365作为预训练，在COCO上训练得到的模型，类别是80, 链接是:

https://paddlemodels.bj.bcebos.com/object_detection/yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.pdparams

**Comment by habout632** [comment]
如何在上边进行finetune呢， 我想类别还是和coco一样 80个类别 就是增加一些自己的数据

**Comment by habout632** [comment]
我直接用configs默认的配置报错 我自己的数据 标注的时候 也是用coco 80的标签么 这个地方要怎么配置呢

**Comment by heavengate** [comment]
finetune训练的时候类别配置和你的数据集里的配置一致就可以了，程序会自动跳过输出层(类别数不匹配的层)的权重加载
