### ISSUE TITLE
现在只有总共的准确率，是否有对应label的准确率呢？

### ISSUE THREAD

**Issue by shen-wenxin** [PaddlePaddle/PaddleDetection#2047]
如果想显示对应label的准确率，该如何修改eval.py呢？

**Comment by jerrywgz** [comment]
tools/eval.py中经过eval_run得到的results里的'bbox'对应的是shape为[N,6]的检测结果，其中第一列表示预测标签，第二列就是对应的准确率

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/1779 如果是想获得单类的评估结果可以参考这个pr，这个功能后续会在动态图中集成

**Comment by yghstill** [comment]
已经在最新release 2.0分支中支持此功能。eval时指定--classwise即可
