### ISSUE TITLE
数据预处理中randomcrop参数

### ISSUE THREAD

**Issue by w867066886** [PaddlePaddle/PaddleDetection#2049]
想裁剪成 [3,224,224] 的图像应该怎么填？   在配置文件yml中

**Comment by willthefrog** [comment]
random crop 是按比例的，输出的size是不一定的，需要后面搭配其他resize步骤，比如random shape

**Comment by w867066886** [comment]
resizeimage是对原图是嘛，对crop图像不起作用，用randomshape  是将batch里面的图像随机放缩到 我们给的参数列表的大小吗？

**Comment by willthefrog** [comment]
放在后面的话就是resize crop后的图像了。 对。

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题，可以reopen这个issue~
