### ISSUE TITLE
faster_rcnn_r101_fpn_1x预测数据生成问题

### ISSUE THREAD

**Issue by atczyh** [PaddlePaddle/PaddleDetection#205]
我使用faster_rcnn_r101_fpn_1x训练了一只物体检测模型，使用了提问中已经通过的代码准备数据进行预测[https://github.com/PaddlePaddle/PaddleDetection/issues/165](url)（转换的数据可成功在faster_rcnn_r50_1x训练的模型下进行预测），可是遇到了报错，错误如下：
----------------------
Error Message Summary:
----------------------
Error: ShapeError: broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 47, 84] and the shape of Y = [1, 256, 48, 84]. Received [47] in X is not equal to [48] in Y
  [Hint: Expected y_dims[i] == 1, but received y_dims[i]:48 != 1:1.] at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:79)
  [operator < elementwise_add > error]
使用官方的infer.py文件进行预测，没有遇到上述问题。于是将官方文件转换的数据进行了打印，发现im_info转换出来的参数与我的代码不一致：
本人代码转换出来的：
'im_info': array([[7.5000000e+02, 1.3330000e+03, 5.2070314e-01]]）
官方文件转换为
'im_info': array([[7.6800000e+02 1.3440000e+03 5.2070314e-01]]）
这就奇怪了，大家的图片参数都是一样的，为何官方文件转换得到的图片im_info会不一致的？
  - !ResizeImage
    interp: 1
    max_size: 1333
    target_size: 800
    use_cv2: true
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
请高手指点，如何解决该问！

**Comment by atczyh** [comment]
resize部分的代码
def ResizeImage(im, target_size=608, max_size=0):
    if len(im.shape) != 3:
        raise ImageError('image is not 3-dimensional.')
    im_shape = im.shape
    im_size_min = np.min(im_shape[0:2])
    im_size_max = np.max(im_shape[0:2])
    if float(im_size_min) == 0:
        raise ZeroDivisionError('min size of image is 0')
    if max_size != 0:
        im_scale = float(target_size) / float(im_size_min)
        # Prevent the biggest axis from being more than max_size
        if np.round(im_scale * im_size_max) > max_size:
            im_scale = float(max_size) / float(im_size_max)
        im_scale_x = im_scale
        im_scale_y = im_scale
    else:
        im_scale_x = float(target_size) / float(im_shape[1])
        im_scale_y = float(target_size) / float(im_shape[0])

    im = cv2.resize(
             im,
             None,
             None,
             fx=im_scale_x,
             fy=im_scale_y,
             interpolation=2)
    h, w, c = im.shape
    im_info = np.array([h, w, im_scale_x]).astype(np.float32)
    return im, im_info

**Comment by qingqing01** [comment]
@atczyh  对于FPN的模型，由于FPN模块上采样时，奇/偶数Height/Width特征图上采样后取整导致差1问题。您看所有FPN相关的config里有有配置 `pad_to_stride: 32`，因此需要对输入数据进行到32整数倍的padding。

**Comment by atczyh** [comment]
@qingqing01 收到，多谢指导，代码插入问题下次会注意的

**Comment by atczyh** [comment]
@qingqing01 高手，琢磨半天没搞明白这段代码的用法。帮忙指导下，根据im_info的结果PadToStride 应是对resize后的图片进行了处理所以将PadToStride加入到了ResizeImage的末尾如下
`def ResizeImage(im, target_size=608, max_size=0):
    if len(im.shape) != 3:
        raise ImageError('image is not 3-dimensional.')
    im_shape = im.shape
    im_size_min = np.min(im_shape[0:2])
    im_size_max = np.max(im_shape[0:2])
    if float(im_size_min) == 0:
        raise ZeroDivisionError('min size of image is 0')
    if max_size != 0:
        im_scale = float(target_size) / float(im_size_min)
        # Prevent the biggest axis from being more than max_size
        if np.round(im_scale * im_size_max) > max_size:
            im_scale = float(max_size) / float(im_size_max)
        im_scale_x = im_scale
        im_scale_y = im_scale
    else:
        im_scale_x = float(target_size) / float(im_shape[1])
        im_scale_y = float(target_size) / float(im_shape[0])

    im = cv2.resize(
             im,
             None,
             None,
             fx=im_scale_x,
             fy=im_scale_y,
             interpolation=2)
    **im=PadToStride(im)**
    h, w, c = im.shape
    im_info = np.array([h, w, im_scale_x]).astype(np.float32)
    return im, im_info`
但是输出报错，转换后的im_info为 [7.500000e+02 1.344000e+03 2.436038e-01]
,得不到官方转换值'im_info': array([[7.6800000e+02 1.3440000e+03 5.2070314e-01]]），错误信息如下:
`Traceback (most recent call last):
  File "tools/infertest.py", line 374, in <module>
    main()
  File "tools/infertest.py", line 291, in main
    shape,test_img, im_info, im_id= Prepocess(path,0)
  File "tools/infertest.py", line 147, in Prepocess
    test_img = NormalizeImage(test_img)
  File "tools/infertest.py", line 135, in NormalizeImage
    im -= mean
ValueError: operands could not be broadcast together with shapes (750,1344,32) (1,1,3) (750,1344,32) `
能否指导下如何正确的使用PadToStride，以达到预期的效果，谢谢！

**Comment by qingqing01** [comment]
@atczyh 

其实可以看 https://github.com/PaddlePaddle/PaddleDetection/blob/master/configs/faster_fpn_reader.yml#L79

FPN模型预测是，图片处理顺序是: DecodeImage（读取图片）->NormalizeImage(减均值，除方差) -> ResizeImage （resize图片 ） -> PadToStride(做对stride整除的padding操作)


你上面错误是，是操作的顺序不对。

**Comment by qingqing01** [comment]
@atczyh 请问是否解决？

**Comment by qingqing01** [comment]
@atczyh 请问这个问题解决了？可否close了？
