### ISSUE TITLE
遗留物检测--》运动物体长时间滞留检测

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleDetection#2057]
请问针对遗留物检测，飞桨有没有一些好的解决方案？

**Comment by yghstill** [comment]
@Sunyingbin 利用Tracking跟踪的方法，判断物体在图像区域中滞留时间，这种是否可行？Tracking跟踪的模型我们正在开发中。

**Comment by Sunyingbin** [comment]
> @Sunyingbin 利用Tracking跟踪的方法，判断物体在图像区域中滞留时间，这种是否可行？Tracking跟踪的模型我们正在开发中。

可能也是一种解决方式吧

**Comment by Sunyingbin** [comment]
> @Sunyingbin 利用Tracking跟踪的方法，判断物体在图像区域中滞留时间，这种是否可行？Tracking跟踪的模型我们正在开发中。

请问Tracking跟踪的方法现在百度有没有提供一些相关的资料的demo呢

**Comment by jerrywgz** [comment]
目前在2.1版本下已经提供了多目标跟踪算法，包括deepsort，JDE，FairMot三种
