### ISSUE TITLE
我在安装paddle 2.0之后运行Demo 失败，请问要怎么修改一下呢？

### ISSUE THREAD

**Issue by JimXu1989** [PaddlePaddle/PaddleDetection#2060]
您好，我如何使用paddle 2.0来运行mrcnn的demo呢？
感谢！

**Comment by JimXu1989** [comment]
会报这个错误出来
AssertionError                            Traceback (most recent call last)
<ipython-input-5-ab39aac2d4fa> in <module>
     21     with fluid.unique_name.guard():
     22 #         paddle.enable_static()
---> 23         feed_vars = {
     24             var['name']: fluid.data(
     25                 name=var['name'],

<ipython-input-5-ab39aac2d4fa> in <dictcomp>(.0)
     22 #         paddle.enable_static()
     23         feed_vars = {
---> 24             var['name']: fluid.data(
     25                 name=var['name'],
     26                 shape=var['shape'],

<decorator-gen-141> in data(name, shape, dtype, lod_level)

~/.local/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     23     def __impl__(func, *args, **kwargs):
     24         wrapped_func = decorator_func(func)
---> 25         return wrapped_func(*args, **kwargs)
     26 
     27     return __impl__

~/.local/lib/python3.8/site-packages/paddle/fluid/framework.py in __impl__(*args, **kwargs)
    228 def _static_only_(func):
    229     def __impl__(*args, **kwargs):
--> 230         assert not in_dygraph_mode(
    231         ), "In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and '%s()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode." % func.__name__
    232         return func(*args, **kwargs)

AssertionError: In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and 'data()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode.

**Comment by JimXu1989** [comment]
我这样修改之后：
with fluid.program_guard(infer_prog, startup_prog):
    with fluid.unique_name.guard():
        paddle.enable_static()
        feed_vars = {
            var['name']: fluid.data(
                name=var['name'],
                shape=var['shape'],
                dtype='float32',
                lod_level=0) for var in feed_var_def
        }
        test_fetches = model.test(feed_vars)

会报这个错误：
ValueError                                Traceback (most recent call last)
<ipython-input-6-d035f1947b4a> in <module>
     28                 lod_level=0) for var in feed_var_def
     29         }
---> 30         test_fetches = model.test(feed_vars)
     31 infer_prog = infer_prog.clone(for_test=True)
     32 

~/paddlepaddle/PaddleDetection-release-2.0-beta/ppdet/modeling/architectures/mask_rcnn.py in test(self, feed_vars, exclude_nms)
    341         assert not exclude_nms, "exclude_nms for {} is not support currently".format(
    342             self.__class__.__name__)
--> 343         return self.build(feed_vars, 'test')

~/paddlepaddle/PaddleDetection-release-2.0-beta/ppdet/modeling/architectures/mask_rcnn.py in build(self, feed_vars, mode)
     89 
     90         # backbone
---> 91         body_feats = self.backbone(im)
     92 
     93         # cast features back to FP32

~/paddlepaddle/PaddleDetection-release-2.0-beta/ppdet/modeling/backbones/resnet.py in __call__(self, input)
    471         severed_head = getattr(self, 'severed_head', False)
    472         if not severed_head:
--> 473             res = self.c1_stage(res)
    474             feature_maps = range(2, max(self.feature_maps) + 1)
    475 

~/paddlepaddle/PaddleDetection-release-2.0-beta/ppdet/modeling/backbones/resnet.py in c1_stage(self, input)
    444 
    445         for (c, k, s, _name) in conv_def:
--> 446             input = self._conv_norm(
    447                 input=input,
    448                 num_filters=c,

~/paddlepaddle/PaddleDetection-release-2.0-beta/ppdet/modeling/backbones/resnet.py in _conv_norm(self, input, num_filters, filter_size, stride, groups, act, name, dcn_v2)
    168 
    169         if not dcn_v2:
--> 170             conv = fluid.layers.conv2d(
    171                 input=input,
    172                 num_filters=num_filters,

~/.local/lib/python3.8/site-packages/paddle/fluid/layers/nn.py in conv2d(input, num_filters, filter_size, stride, padding, dilation, groups, param_attr, bias_attr, use_cudnn, act, name, data_format)
   1590     pre_bias = helper.create_variable_for_type_inference(dtype)
   1591 
-> 1592     helper.append_op(
   1593         type=l_type,
   1594         inputs={

~/.local/lib/python3.8/site-packages/paddle/fluid/layer_helper.py in append_op(self, *args, **kwargs)
     41 
     42     def append_op(self, *args, **kwargs):
---> 43         return self.main_program.current_block().append_op(*args, **kwargs)
     44 
     45     def multiple_input(self, input_param_name='input'):

~/.local/lib/python3.8/site-packages/paddle/fluid/framework.py in append_op(self, *args, **kwargs)
   2838         else:
   2839             op_desc = self.desc.append_op()
-> 2840             op = Operator(
   2841                 block=self,
   2842                 desc=op_desc,

~/.local/lib/python3.8/site-packages/paddle/fluid/framework.py in __init__(***failed resolving arguments***)
   2044             if self._has_kernel(type):
   2045                 self.desc.infer_var_type(self.block.desc)
-> 2046                 self.desc.infer_shape(self.block.desc)
   2047 
   2048     def _has_kernel(self, op_type):

ValueError: (InvalidArgument) The input of Op(Conv) should be a 4-D or 5-D Tensor. But received: input's dimension is 3, input's shape is [480, 640, 3].
  [Hint: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.] (at /paddle/paddle/fluid/operators/conv_op.cc:61)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < conv2d > error]

**Comment by JimXu1989** [comment]
rgb图片不就是3通道么，为什么要求4或者5通道呢？

**Comment by yghstill** [comment]
@JimXu1989 感谢反馈，`mask_rcnn_demo.ipynb`有一段时间没维护了，我们近期更新一下，您可以通过快速开始教程来上手https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/docs/tutorials/QUICK_STARTED_cn.md

**Comment by heavengate** [comment]
鉴于当前问题已经解决，issue关闭，如果还有问题可以reopen这个issue~
