### ISSUE TITLE
paddledection训练过的模型以及权重再paddlehub、paddlex怎么调用，或者paddle有没有自己调用的API

### ISSUE THREAD

**Issue by CZDGitH** [PaddlePaddle/PaddleDetection#2062]
paddledection训练过的模型以及权重再paddlehub、paddlex怎么调用，或者paddledection有没有自己调用的API

**Comment by yghstill** [comment]
- 可使用`deploy/python/infer.py`部署 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-beta/deploy/python，
或者C++等方式部署https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-beta/deploy
- paddlehub调用也有demo：https://github.com/PaddlePaddle/PaddleDetection/tree/master/application/christmas

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题，可以reopen这个issue
