### ISSUE TITLE
我一运行训练的例程就死机请问要怎么做呀？

### ISSUE THREAD

**Issue by JimXu1989** [PaddlePaddle/PaddleDetection#2064]
您好，
我的系统是ubuntu 20.04 cuda 110 cudnn 8.0.4
我运行示例程序
python3 tools/train.py -c configs/yolov3_mobilenet_v1_roadsign.yml --eval -o use_gpu=true
在读取到我的cudnn版本之后，就死机了，请问要怎么做呢？

**Comment by JimXu1989** [comment]
我将batch_size修改为2，依然会死机

**Comment by yghstill** [comment]
将TrainReader中use_process 设为False，不使用多线程训练再试下，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/configs/yolov3_mobilenet_v1_roadsign.yml#L118

**Comment by JimXu1989** [comment]
> 将TrainReader中use_process 设为False，不使用多线程训练再试下，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/configs/yolov3_mobilenet_v1_roadsign.yml#L118

依然会死机呀

**Comment by yghstill** [comment]
@JimXu1989 死机是指程序hang住吗？paddle版本是2.0.0.rc1吗？

**Comment by JimXu1989** [comment]
> @JimXu1989 死机是指程序hang住吗？paddle版本是2.0.0.rc1吗？

整个电脑都没有反应，鼠标都不动啦，只能长按开机键重启，paddle是抢先版的2.0.0.rc1

**Comment by JimXu1989** [comment]
> @JimXu1989 死机是指程序hang住吗？paddle版本是2.0.0.rc1吗？

>>> import paddle
>>> paddle.__version__
'2.0.0-rc1'
>>>

**Comment by JimXu1989** [comment]
> @JimXu1989 死机是指程序hang住吗？paddle版本是2.0.0.rc1吗？

会不会是我cuda或者cudnn版本有点高？

**Comment by JimXu1989** [comment]
> @JimXu1989 死机是指程序hang住吗？paddle版本是2.0.0.rc1吗？

![2021-01-14 14-23-46 的屏幕截图](https://user-images.githubusercontent.com/7732706/104553053-edc15e80-5674-11eb-8d88-f66463b9af94.png)

**Comment by yghstill** [comment]
@JimXu1989 cudnn回退到8.0.3再试下是否可以，8.0.4有可能存在性能和内存泄露问题，-o use_gpu=False试下cpu能跑起来吗？

**Comment by JimXu1989** [comment]
> @JimXu1989 cudnn回退到8.0.3再试下是否可以，8.0.4有可能存在性能和内存泄露问题，-o use_gpu=False试下cpu能跑起来吗？

使用CPU也不行...
![2021-01-14 15-10-08 的屏幕截图](https://user-images.githubusercontent.com/7732706/104556582-d5ecd900-567a-11eb-83be-4400f9a2d71c.png)
报的这个警告是什么意思呀？

**Comment by yghstill** [comment]
这个warning可忽略，再测下infer预测是否可行，如果cpu也不行，那可能内存不足导致hang住。

**Comment by JimXu1989** [comment]
> 这个warning可忽略，再测下infer预测是否可行，如果cpu也不行，那可能内存不足导致hang住。

我的batch_size已经设置成2了呀，还需要怎么修改呢？

**Comment by JimXu1989** [comment]
> 这个warning可忽略，再测下infer预测是否可行，如果cpu也不行，那可能内存不足导致hang住。

infer是可以正常使用solov2的训练好的模型的。
我的batch_size已经设置成2了呀，还需要怎么修改呢？

**Comment by yghstill** [comment]
batch_size设为1再试下吧，roadsign数据集中图像比较大，加载到内存后可能会hang住，将RandomExpand这个删掉再试下https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/configs/yolov3_mobilenet_v1_roadsign.yml#L81-L83

**Comment by JimXu1989** [comment]
> @JimXu1989 cudnn回退到8.0.3再试下是否可以，8.0.4有可能存在性能和内存泄露问题，-o use_gpu=False试下cpu能跑起来吗？

您说的对，死机确实是因为内存满了，可是要怎么避免呢

**Comment by yghstill** [comment]
可从（1）将batch_size设为1，（2）将use_process设为False，（3）将RandomExpand删掉。

**Comment by JimXu1989** [comment]
> 可（1）将batch_size设为1，（2）将use_process设为False，（3）将RandomExpand删掉。

您好，感谢您的回复
我在Win 10 cuda 10.0 cudnn 7.6 下，paddle==1.8.5 ，不用修改config文件，直接可以运行 python3 tools/train.py -c configs/yolov3_mobilenet_v1_roadsign.yml --eval -o use_gpu=true 不报错可以正常训练，所以应该不是数据集的事儿。
