### ISSUE TITLE
文档命令格式一处错误，-o前加空格

### ISSUE THREAD

**Issue by long-Rookie** [PaddlePaddle/PaddleDetection#2067]
CUDA_VISIBLE_DEVICES=0 python tools/eval.py -c configs/yolov3_mobilenet_v1_roadsign.yml-o use_gpu=true
改为 CUDA_VISIBLE_DEVICES=0 python tools/eval.py -c configs/yolov3_mobilenet_v1_roadsign.yml -o use_gpu=true
文档中没有加空格

**Comment by heavengate** [comment]
感谢反馈，我们修改下~
