### ISSUE TITLE
请问.pdparams的文件内容结构是什么样的

### ISSUE THREAD

**Issue by nuaaceieyty** [PaddlePaddle/PaddleDetection#2072]
我手上有一批.txt格式的权重，我想用PaddleDetection在这些权重基础上训练。所以就需要将其重新转换为.pdparams文件，但不清楚.pdparams文件的内部结构，所以想请教下。

如果有类似的转换demo能提供下就太感谢了。

**Comment by heavengate** [comment]
是pickle保存的，可以用pickle.load(open('xxx.pdparams'))读取，读到的是一个dict，key是权重名字，value是权重的numpy array
