### ISSUE TITLE
请问为什么这个训练好的权重文件打不开？

### ISSUE THREAD

**Issue by Bq1207** [PaddlePaddle/PaddleDetection#2073]
[100%] Built target object_detection_demo
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1064 Setup] ARM multiprocessors name: MODEL NAME : ARMV7 PROCESSOR REV 3 (V7L)
HARDWARE : BCM2711

[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1065 Setup] ARM multiprocessors number: 4
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1067 Setup] ARM multiprocessors ID: 0, max freq: 1500, min freq: 1500, cluster ID: 0, CPU ARCH: A72
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1067 Setup] ARM multiprocessors ID: 1, max freq: 1500, min freq: 1500, cluster ID: 0, CPU ARCH: A72
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1067 Setup] ARM multiprocessors ID: 2, max freq: 1500, min freq: 1500, cluster ID: 0, CPU ARCH: A72
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1067 Setup] ARM multiprocessors ID: 3, max freq: 1500, min freq: 1500, cluster ID: 0, CPU ARCH: A72
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1073 Setup] L1 DataCache size is:
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1075 Setup] 32 KB
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1075 Setup] 32 KB
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1075 Setup] 32 KB
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1075 Setup] 32 KB
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1077 Setup] L2 Cache size is:
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1079 Setup] 512 KB
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1079 Setup] 512 KB
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1079 Setup] 512 KB
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1079 Setup] 512 KB
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1081 Setup] L3 Cache size is:
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1083 Setup] 0 KB
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1083 Setup] 0 KB
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1083 Setup] 0 KB
[I 1/16 13: 4:31.823 .../pi/Paddle-Lite/lite/core/device_info.cc:1083 Setup] 0 KB
[I 1/16 13: 4:31.824 .../pi/Paddle-Lite/lite/core/device_info.cc:1085 Setup] Total memory: 1911988KB
[I 1/16 13: 4:31.825 .../pi/Paddle-Lite/lite/core/device_info.cc:442 check_cpu_online] Failed to query the online statue of CPU id:3
[I 1/16 13: 4:31.825 .../pi/Paddle-Lite/lite/core/device_info.cc:447 check_cpu_online] CPU id:3 is offine
[I 1/16 13: 4:31.825 .../pi/Paddle-Lite/lite/core/device_info.cc:442 check_cpu_online] Failed to query the online statue of CPU id:2
[I 1/16 13: 4:31.825 .../pi/Paddle-Lite/lite/core/device_info.cc:447 check_cpu_online] CPU id:2 is offine
[W 1/16 13: 4:31.825 .../pi/Paddle-Lite/lite/core/device_info.cc:1177 SetRunMode] Some cores are offline, switch to NO BIND MODE
[F 1/16 13: 4:31.825 ...odel_parser/naive_buffer/naive_buffer.cc:62 LoadFromFile] Check failed: fp: Unable to open file: ./model.nb
./run.sh：行 19: 7854 已放弃 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${PADDLE_LITE_DIR}/libs/${TARGET_ARCH_ABI} ./object_detection_demo ./model.nb ../labels/pascalvoc_label_list

**Comment by heavengate** [comment]
权重是不是用export_model.py导出之后的？可以到Paddle-Lite库里问一下 https://github.com/PaddlePaddle/Paddle-Lite

**Comment by Bq1207** [comment]
> 权重是不是用export_model.py导出之后的？可以到Paddle-Lite库里问一下 https://github.com/PaddlePaddle/Paddle-Lite

不是，是自己训练后，用opt转化的
