### ISSUE TITLE
无法加入背景图片做抗干扰训练

### ISSUE THREAD

**Issue by jesen8** [PaddlePaddle/PaddleDetection#2074]
@qingqing01  release/2.0-beta 训练时，使用coco格式数据，训练ppyolo模型
 {
    "images": [],
    "categories": [],
    "annotations": []
}
只在images里面添加了图片信息，没有在annotations里面添加对应的框信息， 因为ie图片里面没有目标，训练时，查看加载coco数据集的代码部分，空白图片直接就被过滤了
https://github.com/PaddlePaddle/PaddleDetection/blob/59d4eef6dadf47b7405765200c44aaa9f2b3aa5a/ppdet/data/source/coco.py#L148
是我理解错了吗还是不支持空白图片，
谢谢回答

_Originally posted by @jesen8 in https://github.com/PaddlePaddle/PaddleDetection/issues/319#issuecomment-760068548_

**Comment by heavengate** [comment]
YOLO系列模型是支持没有目标的图片训练的，但是没有目标图片对精度并没有帮助，另外rcnn系列等不支持没有目标的图片，所以这里过滤掉了，如果你是训练PPYOLO并且想把没有目标的图片加入到训练集，可以注释掉这行

**Comment by jesen8** [comment]
好的谢谢，我试试

**Comment by jesen8** [comment]
加无目标背景图片，是因为误检率太高了

**Comment by lmk123568** [comment]
慢慢学习

**Comment by jackie8310** [comment]
@heavengate ，遇到同样问题，RCNN模型预测误识别率高，想把背景加入训练，可以无标记吗？

**Comment by heavengate** [comment]
> @heavengate ，遇到同样问题，RCNN模型预测误识别率高，想把背景加入训练，可以无标记吗？

RCNN检测原理上就不支持无标签的数据
