### ISSUE TITLE
配置模块设计与介绍的链接打不开

### ISSUE THREAD

**Issue by haixuan-2004** [PaddlePaddle/PaddleDetection#2075]
问题网址：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/docs/tutorials/DetectionPipeline.md#%E6%A8%A1%E5%9E%8B%E9%80%89%E6%8B%A9
内容中：配置模块设计与介绍的链接打不开：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/docs/tutorials/config_doc/CONFIG_cn.md

**Comment by qingqing01** [comment]
@liuhuiCNN please help to fix
