### ISSUE TITLE
如何只检测特定场景下的人？

### ISSUE THREAD

**Issue by zhaoyewei** [PaddlePaddle/PaddleDetection#2077]
比如行人检测的时候我看到是把所有行人检测出来，但是如果对于某些场景，只检测再场景中的人（比如街道和店铺内都有人时只检测街道上的行人，或者草坪里外都有人时只检测草坪中或者草坪外的人），这些有没有办法实现

**Comment by qingqing01** [comment]
@zhaoyewei  

或许可以将场景(比如街道，草坪)也检测，然后和行人框坐标比较。

**Comment by heavengate** [comment]
鉴于当前问题已经解决，issue关闭，如果还有问题可以reopen这个issue~
