### ISSUE TITLE
visualDL打开时发生错误

### ISSUE THREAD

**Issue by PavoneB** [PaddlePaddle/PaddleDetection#2080]
在可视化界面中输入了log日志所在的文件夹，但是打开时报错
<img width="796" alt="3bdced4778150d561fb1a5e1041d7e0" src="https://user-images.githubusercontent.com/76778582/104845634-6ba19600-5911-11eb-9b0d-960a4c33631f.png">

**Comment by PavoneB** [comment]
<img width="796" alt="微信图片_20210117221224" src="https://user-images.githubusercontent.com/76778582/104845704-c9ce7900-5911-11eb-9c35-88ecda430eb0.png">

**Comment by ShenYuhan** [comment]
用的什么版本的vdl呢

**Comment by BurrowsWang** [comment]
@jerrywgz 能看下这个问题么，我也遇到同样的问题了
paddlepaddle-gpu==2.1.0
visualdl==2.2.0
paddledetect==2.1
Chrome 74.0
如有必要，可以提供日志文件

**Comment by ShenYuhan** [comment]
Hi，可以尝试升级chrome浏览器到>=79的版本再试试是否满足需求，在这里可以看到VisualDL的所需环境https://github.com/PaddlePaddle/VisualDL#introduction

**Comment by BurrowsWang** [comment]
> Hi，可以尝试升级chrome浏览器到>=79的版本再试试是否满足需求，在这里可以看到VisualDL的所需环境https://github.com/PaddlePaddle/VisualDL#introduction

确实是浏览器版本问题，Chrome或Edge升级到79以上能正常显示，感谢。
