### ISSUE TITLE
fluid.layers.anchor_generat函数的疑问

### ISSUE THREAD

**Issue by wangzigongsi** [PaddlePaddle/PaddleDetection#209]
![image](https://user-images.githubusercontent.com/43198176/73806493-9976f300-4804-11ea-8b0c-663628579da3.png)
我写了一个测试代码，然后我在控制台上打印了这个结果
aspect_ratios=[0.5, 1, 2]，按照文档写的是宽高比
![image](https://user-images.githubusercontent.com/43198176/73806603-e8248d00-4804-11ea-9b14-5718ace7ba5b.png)
![image](https://user-images.githubusercontent.com/43198176/73806625-f4a8e580-4804-11ea-990f-91e87aff7a95.png)
按照文档写的顺序，和我在控制台上看到的不同， aspect_ratios=0.5和aspect_ratios=1产生的
ancher的宽高比都是1：1，请问0.5比例去哪里了

**Comment by willthefrog** [comment]
看了下代码，如果stride 是1的话，计算过程会有些问题，详情见[这里](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/anchor_generator_op.h#L66)。正常情况下stride是16的倍数，这个edge case实现时没有考虑到，该问题会反馈给相关负责人，同时，如果没有特殊需求建议可以先按照16倍数设置stride。

**Comment by wangzigongsi** [comment]
stride应该是根据原始图像大小与卷积后feature map图像大小的比例确定的，不一定是stride的倍数呀

**Comment by willthefrog** [comment]
是的，通常情况下backbone会有4-5次downsample的过程，那么feature map的stride就是 2^4 - 2^5。

**Comment by wangzigongsi** [comment]
大哥 ，不是我要求苛刻哈，封装一个函数要有普遍性，文档中也未提示"通常情况下backbone会有4-5次downsample",所以这个可能会给我们开发者带来误解，请尽快修改这个函数

**Comment by willthefrog** [comment]
嗯，已经反馈给相关OP负责人了
