### ISSUE TITLE
在v2.0-beta版本如何使用VisualDL可视化数据预处理图片

### ISSUE THREAD

**Issue by fanplanet** [PaddlePaddle/PaddleDetection#2094]
在v2.0-beta版本的版本信息中说支持VisualDL可视化数据预处理图片？这个功能是如何使用的？看了detection代码，没找到这个功能。

**Comment by jerrywgz** [comment]
可以使用operators.py中的DebugVisibleImage，设置use_vdl=True后，就可以可视化预处理中的图片了

**Comment by fanplanet** [comment]
> 可以使用operators.py中的DebugVisibleImage，设置use_vdl=True后，就可以可视化预处理中的图片了

我在yml配置DebugVisibleImage后，运行train.py会报错
![微信截图_20210120200606](https://user-images.githubusercontent.com/50946192/105173263-bca4ca80-5b5b-11eb-9489-a50ddedf9e09.png)

**Comment by thinkthinking** [comment]
欢迎在最新版本测试，如有问题reopen该issue。
