### ISSUE TITLE
【求助】ppyolo 训练，lose 下降，mAP 不增长反而下降

### ISSUE THREAD

**Issue by Fauny** [PaddlePaddle/PaddleDetection#2096]
环境： aistudio
PaddlePaddle: v1.8.4
PaddleDetection: v0.5

![下载 (3)](https://user-images.githubusercontent.com/12800439/104999084-373fee00-5a67-11eb-9911-0dae34964597.png)
![下载 (4)](https://user-images.githubusercontent.com/12800439/104999097-3c9d3880-5a67-11eb-8845-67efa75f3050.png)

**Comment by jerrywgz** [comment]
AIStudio上的为单卡环境，需要调整学习率为原配置文件中的1/8。PPYOLO本身的收敛速度也比较慢，需要训练较长的时间。另外看你的初始mAP就已经很高率，可能出现过拟合的情况

**Comment by Fauny** [comment]
@jerrywgz 谢谢回复！

1. 已经调整学习率和milestone到1/10以下（否则会出现nan错误）
2. 初始mAP已经很高是因为这个是继续之前的训练
3. 过拟合如何判定及防止？
4. ppyolo训练每次都是mAP到一个高点后还是水平运行（很快，大概2w iters之内或者更少），如果断掉再恢复，有一定几率会小幅上升，这是什么原理呢？
5. 断掉再恢复的时候，lose值一般会比断点时的高，也就是说并不是真正的“断点恢复”，是否正常？

**Comment by thinkthinking** [comment]
欢迎在最新版本测试，如有问题reopen该issue。
