### ISSUE TITLE
How can I change the batchsize

### ISSUE THREAD

**Issue by qrzeffort** [PaddlePaddle/PaddleDetection#2097]
Where can I change the batchsize of the training model? I want to train yolov3_mobilenet, but the graphics card memory is not enough.

**Comment by jerrywgz** [comment]
You could change the ```batch size``` of TrainReader in configs/yolov3_reader.yml

**Comment by qrzeffort** [comment]
> You could change the `batch size` of TrainReader in configs/yolov3_reader.yml

Thank you very much

**Comment by qrzeffort** [comment]
After inference,the evaluation reported the following error:
TypeError: 'numpy.float64' object cannot be interpreted as an integer
