### ISSUE TITLE
实例分割标签混乱的原因是？

### ISSUE THREAD

**Issue by PavoneB** [PaddlePaddle/PaddleDetection#2101]
solov2实例分割可以检测出物体，但是标签基本都不对，看官网的模型用coco数据集时不需要标签的txt文件，按理说都是json文件里面提供的标签，那么为什么会出现这样的问题呢？

**Comment by jerrywgz** [comment]
如果使用的是coco的数据集格式，类别信息会自动加载配置文件中anno_path 设置的路径，在log中会显示category加载的信息
