### ISSUE TITLE
ppyolo 训练问题

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/PaddleDetection#2104]
![image](https://user-images.githubusercontent.com/57654726/105292061-bd893b00-5bf3-11eb-8ead-f8b0c0de28cc.png)
![image](https://user-images.githubusercontent.com/57654726/105292286-cc6fed80-5bf3-11eb-8398-9205d0294796.png)
在aistudio上现存32g,训练过慢

**Comment by yghstill** [comment]
@xialei2821212670 PP-YOLO由于训练batch size很大，数据预处理复杂，训练确实会慢，加之AIStudio上单卡v100环境，内存等较小，资源更受限，训练速度会更慢一点，建议将batch size调小，mixup等数据预处理也视情况去掉，可加快训练速度。

**Comment by xialei2821212670** [comment]
> @ xialei2821212670 PP-YOLO由于训练批次大小很大，数据预先复杂，训练确实会慢，加之AIStudio上单卡v100环境，内存等较小，资源更容易，训练速度会更慢一点，建议将批次size调小，mixup等数据预先也视情况去掉，可加快训练速度。
我有大概1500左右的图片，但是尺寸有点大，我该如何设置？现在max_iters: 100000
log_iter: 1000
save_dir: output
snapshot_iter: 10000

**Comment by yghstill** [comment]
@xialei2821212670 能不能提前将图片离线resize到608大小，因为图片大加载会很耗时，1500张图片，batch size=24时，训练270epoch只需要max_iters设置16800就行，并且你可以加载pp-yolo在coco上训好的模型作为预训练模型，加快收敛速度。

**Comment by xialei2821212670** [comment]
> @ xialei2821212670 PP-YOLO由于训练批次大小很大，数据预先复杂，训练确实会慢，加之AIStudio上单卡v100环境，内存等较小，资源更容易，训练速度会更慢一点，建议将批次size调小，mixup等数据预先也视情况去掉，可加快训练速度。

预训练模型是哪个，图像暂时动不了

**Comment by yghstill** [comment]
@xialei2821212670  https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-beta/configs/ppyolo#pp-yolo-1
