### ISSUE TITLE
请问ohem支持吗

### ISSUE THREAD

**Issue by helloyongyang** [PaddlePaddle/PaddleDetection#2110]
比如我想在检测中使用ohem作为采样，请问paddle支持吗？如何修改？谢谢！

**Comment by heavengate** [comment]
SSD支持ohem，静态图是在`ssd_loss`里支持的，`neg_pos_ratio`参数指定采样出的负样本相比于正样本数目的比例
https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/ssd_loss_cn.html#ssd-loss
动态图里在`ssd_loss.py`里实现了负例难样本挖掘
https://github.com/PaddlePaddle/PaddleDetection/blob/de14eef07cb72b07b6260470f1f2b46d5907665d/dygraph/ppdet/modeling/losses/ssd_loss.py#L89

其余模型的话需要根据你的挖掘方法改变一下组网了
