### ISSUE TITLE
有Siamese的config吗？

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#2113]
有没有利用模板的 siamese 网络的config 文件，如果要将siamese RPN加入到faster RCNN_fpn_dcn用于检测config该如何构建？求指教

**Comment by qingqing01** [comment]
@jackie8310 如果是单目标跟踪   SiamRPN的话，可以参考这里

https://github.com/PaddlePaddle/models/tree/release/2.0-beta/PaddleCV/tracking
