### ISSUE TITLE
可以集成一下Recursive-FPN吗？

### ISSUE THREAD

**Issue by fanplanet** [PaddlePaddle/PaddleDetection#2115]
可以集成一下Recursive-FPN吗？

**Comment by qingqing01** [comment]
@fanplanet  感谢建议，我们会纳入后续的feature。如果您感兴趣，也可以先开发 具体的也可以参考 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-beta/ppdet/modeling/backbones 中的fpn开发

**Comment by fanplanet** [comment]
> 感谢建议，我们会纳入后续的feature。如果您感兴趣，也可以先开发 具体的也可以参考

好的，谢谢。
