### ISSUE TITLE
请问一下，PaddleDetection有提供关于模型配置yml文件参数的文档吗？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleDetection#2117]
尊敬的开发者，你好，
请问一下，PaddleDetection有提供关于模型配置yml文件参数的文档吗？

期待你的回复！

**Comment by qingqing01** [comment]
@songyuc 

https://github.com/PaddlePaddle/PaddleDetection#%E8%BF%9B%E9%98%B6%E6%95%99%E7%A8%8B

这块 参数配置 教程，提供了简单的设计、RCNN和YOLOv3的参数介绍。 每个模块参数和内部的代码Class接口一致。

**Comment by songyuc** [comment]
好的，感谢您的解答！
