### ISSUE TITLE
FPNRPNHead问题：

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#2118]
config文件中：
FPNRPNHead:
  anchor_generator:
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
问题1：anchor_sizes是在featuremapC2-C6上对应的pixels大小，还是对应到了原图？疑惑这个anchor_sizes尺寸在C2-C6上没有那么大
问题2： stride: [16.0, 16.0]是对应在原图？那么在P2-P6上对应的stride是一样还是可以设置5个不同的 strides？

**Comment by jerrywgz** [comment]
这里的anchor size是对应成输入图片的大小; stride对应的是每个特征图对应原始图片的下采样率，在FPNRPNHead中，stride的值会自动计算，配置文件中的stride实际上没有起作用，这个在最新代码里已经删除了。

**Comment by jackie8310** [comment]
@jerrywgz anchor size数量如果大于5，是否后面的就会被忽略，只默认前5个尺寸与P2-P6对应？

**Comment by jackie8310** [comment]
@jerrywgz 看到FPNRPNHead中anchor的计算：
num_anchors = len(self.anchor_generator.aspect_ratios)
        self.anchors, self.anchor_var = self.anchor_generator(
            input=conv_rpn_fpn,
            anchor_sizes=(self.anchor_start_size * 2.
                          **(feat_lvl - self.min_level), ),
            stride=(2.**feat_lvl, 2.**feat_lvl))

anchor_sizes仅仅与featuremap层数和anchor_start_size有关，anchor数量仅仅与anchor_ratios有关，config文件中：
anchor_sizes: [32, 64, 128, 256, 512]是否就没有意义了，可以直接通过anchor_start_size计算出来？？理解对吗？
