### ISSUE TITLE
Faster R-CNN FPN特征融合源代码的位置

### ISSUE THREAD

**Issue by ash12358** [PaddlePaddle/PaddleDetection#2120]
请问一下，Faster R-CNN里FPN特征融合的代码在哪里，是在ppdet/modeling/anchor_heads/rpn_head.py里吗，没看见对特征图上采样以及特征图相加的代码

**Comment by qingqing01** [comment]
@ash12358 

FPN源码在backbones文件夹:

https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-beta/ppdet/modeling/backbones

**Comment by ash12358** [comment]
@qingqing01 好的谢谢
