### ISSUE TITLE
如何加密部署使用paddledetection训练的模型文件与权重？

### ISSUE THREAD

**Issue by kritohyh** [PaddlePaddle/PaddleDetection#2122]
想请问官方是否有提供对于paddle2.0rc1 以及 PaddleDetection中模型权重的加密工具？ 如何集成到paddle inference？
如果没有的话， 有什么推荐的办法吗？

**Comment by jiangjiajun** [comment]
你好，PaddlePaddle作为开源的框架，没有提供加密的方式，但是用户可以自行集成加密的方案。

PaddlePaddle的模型保存，一般保存为1. 模型结构文件，如`__model__`或`xx.pdmodel`；2. 模型权重文件，如`__params__`或`xx.pdiparams`。
在加载模型时，通过读取模型结构文件恢复模型的前向预测网络，再读取模型权重文件恢复网络中的参数值。因此在加密时，只需要将模型结构文件和模型权重文件加密即可。

因此可参考的加密流程如下
1. 通过加密算法，如非对称加密算法，将`__model__`和`__params__`加密保存为`__model__.encrypted`和`__params__.encrypted`
2. 在加载模型前，先读取加密的两个文件成字符串流，再调用解密接口，得到解密后的明文字符串流
3. 通过调用Paddle的SetModelBuffer接口，使用字符串流初始化一个Paddle模型，参考[接口](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/native_infer.html#setmodelbuffer-const-char-prog-buffer-size-t-prog-buffer-size-const-char-params-buffer-size-t-params-buffer-size)

通过上述方式即可完成加密解密的过程，目前已经应用此方案加密的示例可以参考 [模型加密CPU/GPU部署](https://paddlex.readthedocs.io/zh_CN/develop/deploy/server/encryption.html)

**Comment by kritohyh** [comment]
> 你好，PaddlePaddle作为开源的框架，没有提供加密的方式，但是用户可以自行集成加密的方案。
> 
> PaddlePaddle的模型保存，一般保存为1. 模型结构文件，如`__model__`或`xx.pdmodel`；2. 模型权重文件，如`__params__`或`xx.pdiparams`。
> 在加载模型时，通过读取模型结构文件恢复模型的前向预测网络，再读取模型权重文件恢复网络中的参数值。因此在加密时，只需要将模型结构文件和模型权重文件加密即可。
> 
> 因此可参考的加密流程如下
> 
> 1. 通过加密算法，如非对称加密算法，将`__model__`和`__params__`加密保存为`__model__.encrypted`和`__params__.encrypted`
> 2. 在加载模型前，先读取加密的两个文件成字符串流，再调用解密接口，得到解密后的明文字符串流
> 3. 通过调用Paddle的SetModelBuffer接口，使用字符串流初始化一个Paddle模型，参考[接口](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/05_inference_deployment/inference/native_infer.html#setmodelbuffer-const-char-prog-buffer-size-t-prog-buffer-size-const-char-params-buffer-size-t-params-buffer-size)
> 
> 通过上述方式即可完成加密解密的过程，目前已经应用此方案加密的示例可以参考 [模型加密CPU/GPU部署](https://paddlex.readthedocs.io/zh_CN/develop/deploy/server/encryption.html)

加密这个是上级需求、业务需求害，十分感谢paddlepaddle的技术人员无私奉献！
