### ISSUE TITLE
Frcnn剪枝后再训练夯住

### ISSUE THREAD

**Issue by ellinyang** [PaddlePaddle/PaddleDetection#2124]
训练环境：
-paddleslim 1.1.1
-paddle1.8.4-gpu-post97
-GPU: Tesla V100, 16G, cuda 9, cudnn 7.6
-代码分支：release/0.4
复现步骤：
使用faster_rcnn_r50_fpn_2x，修改input_size=640，max_size=800,进行预训练；
再使用prune 均匀剪枝0.3的conv2d op后，训练夯住。此时查看该进程CPU/GPU利用率都为零，栈信息似乎卡在Executor；
剪枝op:
```
 for param in program.global_block().all_parameters():
            if "_weights" in param.name:
                params.append(param.name)
```
剪枝
夯住日志：
![image](https://user-images.githubusercontent.com/20673237/105827460-fca4fb00-5ffc-11eb-9a77-485c176616ca.png)

夯住部分的栈信息：
![image](https://user-images.githubusercontent.com/20673237/105827055-78527800-5ffc-11eb-8eef-e745d936c967.png)
![image](https://user-images.githubusercontent.com/20673237/105827082-80121c80-5ffc-11eb-99cb-4d25a9e167e1.png)
线程日志：
![image](https://user-images.githubusercontent.com/20673237/105827762-59081a80-5ffd-11eb-9fa1-a9c4ddbe6228.png)

**Comment by Joejiong** [comment]
好的，邀请slim同学和你一起看看

**Comment by ellinyang** [comment]
> 好的，邀请slim同学和你一起看看

看了栈信息，夯住在Executor中，并且数据读取的quene是空，这个是数据问题导致的夯住还是剪枝错误导致的Executor中止呢？
能从这些信息中分析出来一些可能原因吗？

**Comment by thinkthinking** [comment]
欢迎使用PaddleDetection，如有问题可以reopen。
