### ISSUE TITLE
请问有没有各个预训练模型推理的详细数据指标呢？

### ISSUE THREAD

**Issue by huzhe01** [PaddlePaddle/PaddleDetection#2127]
PaddleDetection的模型经过预训练之后，有没有在某个数据集上fine-tune进行指标的比较呢？能提供一个官方的数据吗？

**Comment by yghstill** [comment]
@huzhe01 我们只提供了coco或voc上的预训练模型，还没有迁移到其他数据集上进行finetune的指标。
