### ISSUE TITLE
ppyolo矩形训练问题和coco类型的数据集eval

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/PaddleDetection#2131]
1.ppyolo训练的时候选择图片矩形形状，比如输入图片原始尺寸为1920*1080，训练时要将其resize为512*288这个比例的大小，由于数据预处理中randomshape中的大小是多种尺寸的，这时就要将其变为多个尺寸相同比例即可。请问这时只需要修改random中的尺寸么，此时的cluster计算得到的fpn的尺寸也需要按照同比例进行缩小吧？
此外，train和eval reader中，image_shape也需要修改为[3,512,288]么，target size代码也需要修改使之能够适于512,288吧，如果target size不修改，图片会自动resize为输入图片大小image_shape的尺寸么？
如果理解不对，想要训练矩形的图像，需要修改哪些部分的代码呢，我来修改一个。
2.coco类型的模型进行评测时的输出为：
    " Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.461\n",
      " Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.877\n",
      " Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.399\n",
      " Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.276\n",
      " Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.399\n",
      " Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.585\n",
      " Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.251\n",
      " Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.608\n",
      " Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.625\n",
      " Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.316\n",
      " Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.527\n",
      " Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.745\n"
上面的结果该怎么理解呢，mAP是上面这些ap的平均么，IoU代表谁与谁之间的IoU，area指大目标还是小目标吗？maxDet是？

感谢回复

**Comment by yghstill** [comment]
1. ppyolo的训练，一般要resize成长宽等长，RandomShape中设置的值表示resize后是正方形，如果想resize成矩形，RandomShape这个操作目前不支持，需要修改一下RandomShape实现代码。eval的时候也要修改一下ResizeImage的target_size为图像最短边长度，max_size设置成图像最长边长度就行。
2. 上述AP值就是mAP，IoU为预测框与真实gt框的iou，area分为all、large、medium、small，maxDet为每张图选取的最多检测结果数量。
