### ISSUE TITLE
测试时如何进行数据增强?

### ISSUE THREAD

**Issue by oukohou** [PaddlePaddle/PaddleDetection#2139]
Great work!
但是我测试时想要进行数据增强,比如我用fastrcnn训了一个模型,测试时想要预测原图+翻转后的图,将两次的结果集成进行nms等操作,作为最终的结果,也就是目标检测时使用TTA,该怎么配置呢?谢谢

**Comment by heavengate** [comment]
你好，TTA我们正在开发过程中，近期会发布，如果你想自己尝试修改的话可以参考一下 multi scale test
https://github.com/PaddlePaddle/PaddleDetection/blob/de14eef07cb72b07b6260470f1f2b46d5907665d/tools/eval.py#L86

**Comment by heavengate** [comment]
鉴于当前问题已经解决，issue关闭，如果还有问题可以reopen这个issue~
