### ISSUE TITLE
请问PaddleDetection里有类似Darknet里的subdivision这样的设置吗

### ISSUE THREAD

**Issue by nuaaceieyty** [PaddlePaddle/PaddleDetection#2142]
Darknet里有subdivision设置。请问在PaddleDetion里怎么设置呢？？

**Comment by heavengate** [comment]
你好，darknet里的subvision配置实际上是把一个batch分为多次前向+一次反向来做，是一种节省显存但是会增加训练时间的做法，我们当前还在支持这种模式。
另外这种模型对训练结果，精度，预测速度等均没有影响，使用当前PaddleDetection提供的配置也是完全没有问题的

**Comment by nuaaceieyty** [comment]
> 你好，darknet里的subvision配置实际上是把一个batch分为多次前向+一次反向来做，是一种节省显存但是会增加训练时间的做法，我们当前还在支持这种模式。
> 另外这种模型对训练结果，精度，预测速度等均没有影响，使用当前PaddleDetection提供的配置也是完全没有问题的

感谢回复！请问我想这样做的话，应该怎么进行配置呢？？

**Comment by nuaaceieyty** [comment]
> 你好，darknet里的subvision配置实际上是把一个batch分为多次前向+一次反向来做，是一种节省显存但是会增加训练时间的做法，我们当前还在支持这种模式。
> 另外这种模型对训练结果，精度，预测速度等均没有影响，使用当前PaddleDetection提供的配置也是完全没有问题的

要是能提供一个简单的示例就好了

**Comment by heavengate** [comment]
可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/docs/tutorials/QUICK_STARTED_cn.md

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen这个issue~
