### ISSUE TITLE
打包进程无限增加

### ISSUE THREAD

**Issue by CheerMan1** [PaddlePaddle/PaddleDetection#2144]
windows下运行后进程无限增加

**Comment by heavengate** [comment]
你好，能麻烦提供一下你的配置文件么，还有在windows上PaddleDetection默认是不开启多进程的，是否对代码有所修改呢

**Comment by ANewAnonymous** [comment]
> 你好，能麻烦提供一下你的配置文件么，还有在windows上PaddleDetection默认是不开启多进程的，是否对代码有所修改呢

使用pyInstaller打包后出现大量进程，即使loadModel没有运行也会这样
![QQ图片20210610203448](https://user-images.githubusercontent.com/17308906/121529714-408a2100-ca2f-11eb-82c9-e86067a2cbac.png)
![QQ图片20210610203454](https://user-images.githubusercontent.com/17308906/121529727-4253e480-ca2f-11eb-858d-d398290a76ec.png)
![QQ图片20210610203459](https://user-images.githubusercontent.com/17308906/121529734-441da800-ca2f-11eb-9853-9960aa428806.png)
![QQ图片20210610210458](https://user-images.githubusercontent.com/17308906/121530011-8e068e00-ca2f-11eb-8202-c48e79035174.png)





![QQ图片20210610210502](https://user-images.githubusercontent.com/17308906/121530309-e3db3600-ca2f-11eb-8b92-53351bcc0fee.png)
