### ISSUE TITLE
导出模型错误：

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#2156]
训练时 nms: MultiClassSoftNMS，tools/export_model.py模型时，报错：
  op_type, op_type, EXPRESSION_MAP[method_name]))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py:13402: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  args = inspect.getargspec(self._func)
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection0.5beta/tools/export_model.py", line 89, in <module>
    main()
  File "/home/aistudio/PaddleDetection0.5beta/tools/export_model.py", line 65, in main
    check_py_func(infer_prog)
  File "/home/aistudio/PaddleDetection0.5beta/ppdet/utils/check.py", line 129, in check_py_func
    raise Exception(err)
Exception: The program contains py_func with input: ['box_clip_0.tmp_0', 'tmp_12'], output: ['softnms_pred_result']. It is not supported in Paddle inference engine. please replace it by paddle ops. For example, if you use MultiClassSoftNMS, better to replace it by MultiClassNMS.

**Comment by qingqing01** [comment]
@jackie8310 

MultiClassSoftNMS 采用Python实现，不支持模型导出。如果您要部署的化，可以考虑换成MultiClassNMS，看下对精度的影响，然后导出模型。

**Comment by qingqing01** [comment]
@jackie8310 

MultiClassSoftNMS 采用Python实现，不支持模型导出。如果您要部署的化，可以考虑换成MultiClassNMS，看下对精度的影响，然后导出模型。

**Comment by fanplanet** [comment]
> @jackie8310
> 
> MultiClassSoftNMS 采用Python实现，不支持模型导出。如果您要部署的化，可以考虑换成MultiClassNMS，看下对精度的影响，然后导出模型。

我试过使用MultiClassNMS替换MultiClassSoftNMS ，
MultiClassNMS:
  score_threshold: 0.01
  keep_top_k: 300
  nms_threshold: 0.5
精度损失严重，有的框会扩大，是我配置问题吗？能否推荐一个替换配置？

**Comment by fanplanet** [comment]
> @qingqing01
> 
> MultiClassSoftNMS 采用Python实现，不支持模型导出。如果您要部署的化，可以考虑换成MultiClassNMS，看下对精度的影响，然后导出模型。

我试过使用MultiClassNMS替换MultiClassSoftNMS ，
MultiClassNMS:
score_threshold: 0.01
keep_top_k: 300
nms_threshold: 0.5
精度损失严重，有的框会扩大，是我配置问题吗？能否推荐一个替换配置？

**Comment by qingqing01** [comment]
@fanplanet 

您是那个模型？如果是Cascade模型，可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/configs/cascade_mask_rcnn_r50_fpn_1x.yml#L87  nms参数设置。

**Comment by fanplanet** [comment]
> @qingqing01
> 
> 您是那个模型？如果是Cascade模型，可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/configs/cascade_mask_rcnn_r50_fpn_1x.yml#L87 nms参数设置。

我用的是librcnn，这个参数设置我也试过了，框也会扩大很多。
cascade之前我也试过，好像框没有扩大的这么严重。难道是librcnn这个模型的问题？

**Comment by qingqing01** [comment]
libra_rcnn默认是NMS，而非soft-nms。

https://github.com/PaddlePaddle/PaddleDetection/blob/da0e1eed6472d492abc9db1db324569f9be62a5f/configs/libra_rcnn/libra_rcnn_r50_vd_fpn_1x.yml#L82-L85


您精度差多少呢？

**Comment by littletomatodonkey** [comment]
nms和softnms的mAP应该只差1%左右，配置如下所示，可以先看下你那边的精度diff大概是多少

```
MultiClassNMS:
score_threshold: 0.05
keep_top_k: 300
nms_threshold: 0.5
```


```
MultiClassSoftNMS:
score_threshold: 0.01
keep_top_k: 300
nms_threshold: 0.5
```

**Comment by fanplanet** [comment]
> libra_rcnn默认是NMS，而非soft-nms。
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/da0e1eed6472d492abc9db1db324569f9be62a5f/configs/libra_rcnn/libra_rcnn_r50_vd_fpn_1x.yml#L82-L85
> 
> 您精度差多少呢？



> libra_rcnn默认是NMS，而非soft-nms。
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/da0e1eed6472d492abc9db1db324569f9be62a5f/configs/libra_rcnn/libra_rcnn_r50_vd_fpn_1x.yml#L82-L85
> 
> 您精度差多少呢？

librcnn是我改成了softnms，框挺离谱的，我就没有测试精度。
