### ISSUE TITLE
请问image mosaic什么时候能够支持？

### ISSUE THREAD

**Issue by AWDawson** [PaddlePaddle/PaddleDetection#2164]
![image](https://user-images.githubusercontent.com/44725729/106559279-265fa400-6560-11eb-9846-95a891e168de.png)
在TODO list里看到了mosaic数据预处理实现， 请问大概什么时候可以实现？

**Comment by jerrywgz** [comment]
目前我们正在对PPYOLO做进一步的优化，优化的过程中发现mosaic和我们已有的数据预处理综合在一起没有起到正向的效果，这个优化我们还在进行中
