### ISSUE TITLE
请问一下，如果不使用预训练模型，如何设置mean和std呢？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleDetection#2167]
尊敬的开发者，你好，
由于更改了模型的结构，我在训练模型时无法使用ImageNet上的预训练模型，想请问一下，这时该如何设置图像预处理时的mean和std呢？

期待你的回复！

**Comment by jerrywgz** [comment]
如果不使用预训练模型的话，mean和std也可以使用原先的值，PaddleDetection里不同模型的预处理也会使用不同的mean和std，主要保证训练预测行为一致，影响应该就不大

**Comment by songyuc** [comment]
好的，谢谢你的回复！

**Comment by songyuc** [comment]
你好，@jerrywgz，请问一下，可以使用训练集的mean和std吗？

**Comment by jerrywgz** [comment]
嗯嗯可以的

**Comment by songyuc** [comment]
@jerrywgz 谢谢您的解答！

**Comment by songyuc** [comment]
请问一下，PaddleDetection有开源计算数据集mean和std的代码吗？
