### ISSUE TITLE
目标识别以后通过哪个模型来追踪目标得到目标的唯一标识

### ISSUE THREAD

**Issue by zyingbo** [PaddlePaddle/PaddleDetection#218]
某一帧追踪到一个目标以后，在后续的帧里面如何追踪此目标，并判定目标合适离开

**Comment by zyingbo** [comment]
paddle有没有类似于deep_sort模型的优化的追踪器。目前用开源deep_sort效率比较低。

**Comment by qingqing01** [comment]
@zyingbo 请问您是单目标跟踪，还是多目标？ 我们最近会开源系列单目标跟踪的模型~

**Comment by zyingbo** [comment]
@qingqing01 您好，我还是想实现多目标的追踪，主要是想实现实时视频场景下的多目标结构化及追踪。
