### ISSUE TITLE
关于yolo部署到谷歌tpu上的可能性

### ISSUE THREAD

**Issue by dgl547437235** [PaddlePaddle/PaddleDetection#2182]
你好，我目前的项目使用darknet的yolo，部署到谷歌的edgetpu上，现在我想测试paddledetection的边缘部署效果，由于历史问题，无法使用paddle的硬件，所以是否可以将paddle的模型转换为tflite

**Comment by yghstill** [comment]
@dgl547437235 目前有paddle2onnx的支持，看是否能将paddle模型转成onnx的权重，然后再转为tflite，https://github.com/PaddlePaddle/paddle2onnx
