### ISSUE TITLE
多机多卡情况下，学习率如何设置

### ISSUE THREAD

**Issue by paulpaul91** [PaddlePaddle/PaddleDetection#2183]
![image](https://user-images.githubusercontent.com/22076188/106871181-ed186700-670c-11eb-987e-7b2076062eef.png)
多机多卡情况下，学习率如何设置
上述图片给出的是单机8卡的，如果我现在2机8卡应该如何设置学习率

**Comment by yghstill** [comment]
卡数如果翻倍，学习率增大两倍即可。
