### ISSUE TITLE
多机多卡一直等待卡住了

### ISSUE THREAD

**Issue by paulpaul91** [PaddlePaddle/PaddleDetection#2189]
使用公司paddlecloud k8s 集群提交，配置参数如下
./python3/bin/python3 -m paddle.distributed.launch \
    --use_paddlecloud \
    --log_dir $log_dir \
    ./tools/train_multi_machine.py \
    -c ./configs/mask_rcnn_r101_fpn_1x_doc.yml \
    --use_vdl=True \
    --vdl_log_dir=$visualdl_dir
看github 上说要设置    --cluster_node_ips --node_ip 这两个应该不用设置吧，有没有同学对接留下如流联系方式

**Comment by heavengate** [comment]
你好，麻烦提供一下卡住的日志还有Paddle及PaddleDetection版本信息

**Comment by heavengate** [comment]
> --cluster_node_ips --node_ip

这两个需要设置的，需要根据这个配置进行多机间通讯
