### ISSUE TITLE
VOC格式转换COCO格式时报错

### ISSUE THREAD

**Issue by thomas-yanxin** [PaddlePaddle/PaddleDetection#2194]
![D6~{F}63DB$ G }IOYQ 139](https://user-images.githubusercontent.com/58030051/107125599-e55fea80-68e5-11eb-8d61-84e41d2208da.png)
在使用x2coco.py    配置参数--voc_label_list 时， 路径下是存在label_list的，为什么会报这种错误（No such file or directory）？

**Comment by qingqing01** [comment]
@thomas-yanxin label_list在当前路径下? 您指定绝对路径呢？

**Comment by qingqing01** [comment]
@thomas-yanxin 请问这个问题解决了吗？

**Comment by thomas-yanxin** [comment]
解决了解决了，谢谢您！

**Comment by yzy913** [comment]
请问楼主最后是怎么解决的，感谢！
