### ISSUE TITLE
paddleDetection VOC 数据集

### ISSUE THREAD

**Issue by thomas-yanxin** [PaddlePaddle/PaddleDetection#2198]
在使用PaddleDetection训练VOC格式数据集的时候，出现如下报错，应当如何处理？

/home/aistudio/PaddleDetection
2021-02-07 23:48:15,625-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /home/aistudio/PaddleDetection/ppdet/modeling/roi_heads/cascade_head.py:199
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /home/aistudio/PaddleDetection/ppdet/modeling/roi_heads/cascade_head.py:206
The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /home/aistudio/PaddleDetection/ppdet/modeling/architectures/cascade_mask_rcnn.py:341
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 167, in main
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 442, in create_reader
    reader = Reader(**cfg)()
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 210, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/home/aistudio/PaddleDetection/ppdet/data/source/dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "/home/aistudio/PaddleDetection/ppdet/data/source/voc.py", line 112, in load_roidb_and_cname2cid
    for x in line.strip().split()[:2]]
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by AngZhai** [comment]
我遇到同样的错误，请问你是如何解决的

**Comment by yumeng88** [comment]
我也是这个错误，请问你是如何解决的？ @thomas-yanxin

**Comment by yumeng88** [comment]
@AngZhai
