### ISSUE TITLE
请问评估每个类别的ap, recall, precison 的功能是否已经实现

### ISSUE THREAD

**Issue by lao-xu** [PaddlePaddle/PaddleDetection#2204]
请问评估每个类别的ap, recall, precison 的功能是否已经实现？

**Comment by jerrywgz** [comment]
目前还没有，后续我们会在动态图模式下集成该功能

**Comment by lao-xu** [comment]
> 目前还没有，后续我们会在动态图模式下集成该功能

好的，请问detection的动态图版本何时能出来啊

**Comment by qingqing01** [comment]
@lao-xu  静态图 https://github.com/PaddlePaddle/PaddleDetection/pull/1779  这里有一个PR，由于代码的规范性等，后来没有合入。 也可以参考

**Comment by lao-xu** [comment]
@qingqing01 谢谢啊，看了下没怎么看懂，好像要改很多文件吗？

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/2346   动态图已支持此功能，已合入，可以使用develop试下
