### ISSUE TITLE
Cascade RCNN替换ciou？

### ISSUE THREAD

**Issue by zhongqiu1245** [PaddlePaddle/PaddleDetection#2207]
请问：我现在想把Cascade RCNN的loss换成ciou，那么替换哪个bbox_loss？是那三个bbox_loss都替换吗？（检测的目标属于中小目标居多型）

**Comment by qingqing01** [comment]
@zhongqiu1245 

设置CascadeBBoxHead的bbox_loss即可，bbox_loss接受设置其他loss:

https://github.com/PaddlePaddle/PaddleDetection/blob/da0e1eed6472d492abc9db1db324569f9be62a5f/ppdet/modeling/roi_heads/cascade_head.py#L49

例如，下面设置了BalancedL1Loss

https://github.com/PaddlePaddle/PaddleDetection/blob/da0e1eed6472d492abc9db1db324569f9be62a5f/configs/mobile/cascade_rcnn_mobilenetv3_fpn_320.yml#L82

设置CIoU，参考FasterRCNN的CIoU设置，注意，给CascadeBBoxHead设置。

https://github.com/PaddlePaddle/PaddleDetection/blob/5b6bebf23e223aef97e8a1f49f0e9e210ca981e4/configs/iou_loss/faster_rcnn_r50_vd_fpn_ciou_loss_1x.yml#L79-L89

**Comment by zhongqiu1245** [comment]
谢谢
