### ISSUE TITLE
Failed to run inference of SOLOv2 with 2.0.0.0 version. 2.0.0-rc0 or higher is required

### ISSUE THREAD

**Issue by platvlad** [PaddlePaddle/PaddleDetection#2213]
Hi!
I have just upgraded paddlepaddle via pip:
`pip install paddlepaddle --upgrade`
and now my version is 2.0.0. 
Then I run inference of SOLOv2 model:
`python tools/infer.py -c configs/solov2/solov2_light_r50_vd_fpn_dcn_512_3x.yml  -o weights=solov2_light_r50_vd_fpn_dcn_512_3x.pdparams --infer_dir=demo`
I get an exception:
`Exception: PaddlePaddle version 2.0.0-rc0 or higher is required, or a suitable develop version is satisfied as well. 
Please make sure the version is good with your code.`
When debugging, I see that my `version_installed` [here](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/ppdet/utils/check.py#L85) is `[2, 0, 0, 0]` which is less than required `[2, 0, 0-rc0]`.

Is it the correct behaviour or where can I get the required version?
Thanks in advance.

**Comment by yghstill** [comment]
@platvlad Please update and use code of `release/2.0-rc` or `master` branch, which fix in #2158

**Comment by platvlad** [comment]
@yghstill Thank you! It is working on `master` branch.
