### ISSUE TITLE
Bugs in RandomFlipImage func

### ISSUE THREAD

**Issue by ymmshi** [PaddlePaddle/PaddleDetection#2217]
First, the RandomFlipImage does not support Up and Down Flip,

https://github.com/PaddlePaddle/PaddleDetection/blob/da0e1eed6472d492abc9db1db324569f9be62a5f/ppdet/data/transform/operators.py#L401

Second, there are bugs in this line, although it has little effect on the results.
https://github.com/PaddlePaddle/PaddleDetection/blob/da0e1eed6472d492abc9db1db324569f9be62a5f/ppdet/data/transform/operators.py#L489-L490

I think '-1' is wrong for the transformation of  the bboxs's coordinates.

**Comment by qingqing01** [comment]
@ymmshi 

The  x1, y1, x2, y2 from source data are 0 to witdh/height - 1, see following code, x2 <= box_w-1, y2 <= box_h - 1 :

https://github.com/PaddlePaddle/PaddleDetection/blob/da0e1eed6472d492abc9db1db324569f9be62a5f/ppdet/data/source/coco.py#L138-L139


so, need to keep consistent whether to -1.

For example, if x coordinates are [0, 1, 2, 3, 4, 5, 6, 7], w = 8,  flipping x, 1 should put in 8 - 1 - 1 =6

**Comment by ymmshi** [comment]
Thank you for your reply. One question, does that mean the predict coordinates are also 0 to witdh/height - 1 using export model 
https://github.com/PaddlePaddle/PaddleDetection/blob/da0e1eed6472d492abc9db1db324569f9be62a5f/deploy/python/infer.py#L117-L132
