### ISSUE TITLE
paddledetection有没有办法直接对图片进行预测？

### ISSUE THREAD

**Issue by biao321** [PaddlePaddle/PaddleDetection#2222]
使用paddledetection在infer.py里面采用reader，loader的形式对图片进行预测，有没有简单的方式不调用infer.py直接处理图片进行预测？使用paddledetection参加比赛使用镜像数据流形式一次只给一张图片，实在不方便用infer.py

**Comment by qingqing01** [comment]
@biao321 

需要改下代码，几种方式:

- 方式1. 

下面预测代码接口支持直接给numpy的数据，可以更改 流形式 接受数据，直接给numpy数据:

https://github.com/PaddlePaddle/PaddleDetection/blob/da0e1eed6472d492abc9db1db324569f9be62a5f/tools/infer.py#L174


- 方式2:

当前infer采用ImageFloder，可以增加 数据流形式 的DataSet

https://github.com/PaddlePaddle/PaddleDetection/blob/da0e1eed6472d492abc9db1db324569f9be62a5f/ppdet/data/source/dataset.py#L105-L164
