### ISSUE TITLE
solov2训练自定义数据集，效果不好

### ISSUE THREAD

**Issue by hymanzhu1983** [PaddlePaddle/PaddleDetection#2232]
用solov2在自定义数据集上训练了一个模型，测试时出现两个或多个同类的不同实例被当成一个实例输出的情况，请问是什么原因？数据集大概有500张图片，是数据集规模太小了吗？

**Comment by qingqing01** [comment]
@hymanzhu1983 您的数据特点是怎样的？ 比如目标的大小、输入图片的大小呢？用MaskRCNN的效果如何？

**Comment by hymanzhu1983** [comment]
输入图片5500*3500，目标大小大概400*400，用maskRcnn效果挺好的

**Comment by yghstill** [comment]
solov2针对小目标实例分割表现不是很好，可以先使用Mask-RCNN，solov2的性能我们也在改进中。
