### ISSUE TITLE
图片预处理的时候， normalize这个操作有点慢 19ms

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/PaddleDetection#2235]
![Screenshot from 2021-02-20 14-47-14](https://user-images.githubusercontent.com/3166070/108586617-a1abbd00-738a-11eb-85e0-5ac1929598c9.png)

**Comment by habout632** [comment]
图片预处理的时候 使用numpy处理图片 paddleclas paddledetection都是使用numpy预处理的 有没有专门模块vision 将图片转成tensor统一处理的 这样速度会快一些 图片204*204 需要1ms 图片大小608 处理时间就需要19ms了

**Comment by habout632** [comment]
这些预处理操作 可以统一合并到一个模块当中么 类似torchvision这种 现在paddleclas paddledetection里面都有自己的预处理操作

**Comment by ghost** [comment]
请问您解决这个问题了吗，我最近也在进行相关部署，发现normalize等预处理操作耗时很久，但不知道该从何处下手

**Comment by nemonameless** [comment]
可以在导出的时候命令最后加上TestReader.fuse_normalize=true  , 将normalize部分放到网络里，这样的话预处理里面不需要做normalize
