### ISSUE TITLE
请问大概什么时候可以支持旋转的矩形框？

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleDetection#2236]
请问大概什么支持旋转的矩形框，有没有相关排期呢？

**Comment by liuhuiCNN** [comment]
感谢关注，旋转矩形框检测基本上ready，预计下个版本会发布，敬请关注，谢谢~

**Comment by Lie-huo** [comment]
> 感谢关注，旋转矩形框检测开发基本完成，预计下个版本会发布，敬请关注，谢谢~

你好，v2.0-rc版本今天已经发布，但是没有看到旋转框检测模型，是会在后面进行大的版本迭代时再发布吗？

**Comment by yghstill** [comment]
@Lie-huo 旋转框检测算法会在v2.0正式版中发布，预计下月月底。

**Comment by heavengate** [comment]
旋转框 S2ANet 已合入
