### ISSUE TITLE
pp-yolo模型loss_xy未收敛

### ISSUE THREAD

**Issue by L-lei** [PaddlePaddle/PaddleDetection#2249]
使用模型:dcn下yolov3_r50vd_dcn_db_iouloss_obj365
python版本:3.5
paddlepaddle-gpu:1.8.5
数据样本2000多张,4个类别,num_max_boxes在[1,100)以内

训练loss打印:
 iter: 84940, lr: 0.000001, 'loss_xy': '10.481256', 'loss_cls': '2.413956', 'loss_obj': '8.340335', 'loss_iou': '10.021211', 'loss': '34.471447', 'loss_wh': '2.534595', time: 0.365,
iter: 84960, lr: 0.000001, 'loss_xy': '10.845106', 'loss_cls': '1.855620', 'loss_obj': '6.957844', 'loss_iou': '10.018523', 'loss': '33.000320', 'loss_wh': '2.816422', time: 0.377
iter: 84980, lr: 0.000001, 'loss_xy': '11.083189', 'loss_cls': '1.922834', 'loss_obj': '7.545725', 'loss_iou': '10.382030', 'loss': '33.614746', 'loss_wh': '3.035978', time: 0.319

从最开始就是在[10-12]之间,训练那么多次了,都没下降,loss_xy又间距影响了loss_iou,其它的loss都在降,请问我可以怎样解决呢

**Comment by wangxinxin08** [comment]
随着训练的进行，总的loss有降低吗？模型的精度有上升吗？

**Comment by L-lei** [comment]
总损失是在降低,从几千降到了30多,因为定位都不准,iou计算也不对;
若x,y坐标都当做0,box框的大小与个数偏差不大;
那我可以先不管其它loss,只用loss_xy优化模型会有用处吗

**Comment by wangxinxin08** [comment]
> 总损失是在降低,从几千降到了30多,因为定位都不准,iou计算也不对;
> 若x,y坐标都当做0,box框的大小与个数偏差不大;
> 那我可以先不管其它loss,只用loss_xy优化模型会有用处吗

请问loss下降的同时精度有提升吗？另外，你用coco格式还是voc格式进行训练的啊，理论上来说，loss下降了这么多，如果你没有改动训练相关的代码的话，那就很有可能是标注有问题

**Comment by L-lei** [comment]
coco的数据格式，代码部分我改动过但不影响，用对比用具对比过的；
我也怀疑是数据问题，数据我检查过了，错标漏标的应该很少，数据有3个特点，场景复杂，不同类别重叠与小目标占比百分之十几；
开始只有几百张数据loss只有11左右，那会场景少；
这种情况我头一次遇到，没想明白x，y的权重没学到

**Comment by wangxinxin08** [comment]
> coco的数据格式，代码部分我改动过但不影响，用对比用具对比过的；
> 我也怀疑是数据问题，数据我检查过了，错标漏标的应该很少，数据有3个特点，场景复杂，不同类别重叠与小目标占比百分之十几；
> 开始只有几百张数据loss只有11左右，那会场景少；
> 这种情况我头一次遇到，没想明白x，y的权重没学到

所以loss下降的同时，精度有提升吗？

**Comment by L-lei** [comment]
精度也在提升,这会很奇怪呀,停止后重新训练iter 1W次,直接预测是对的,虽然map还是很低,只有0.03,我在多训练会和优化下呢
