### ISSUE TITLE
模型训练时的训练集大小与数据增强方式

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleDetection#2251]
您好，我打算用训练一个票据检测模型，如检测图片中的增值税发票、火车票、定额发票、通用发票、出租车票等，有几个问题需要请教？
1、请问各类票据的数量大概是多少就可以保证基本的检测效果？
2、如果要达到生产的水平，每类票据最少需要多少训练图片呢？
3、目前已有旋转、颜色变换、mixup等数据增强方法，但没有看到旋转以及多图组合，如Cutmix和Mosaic等，后面是否会实现这些数据增强方法呢？

**Comment by qingqing01** [comment]
可能也需要看下票据的图片质量，背景是否很脏乱等。您是检测票据上的文字，还是只检测票据大框？ 第3个问题，支持CutMix。Mosaic我们内部有实现，后续增加下。

**Comment by Lie-huo** [comment]
> 可能也需要看下票据的图片质量，背景是否很脏乱等。您是检测票据上的文字，还是只检测票据大框？ 第3个问题，支持CutMix。Mosaic我们内部有实现，后续增加下。

就是正常的财务票据报销场景，图像质量不会很差；不需要检测票据上的文字，只需要检测票据大框。还有一个问题，我的训练集的每张图片都是一种票据类型，在训练时需要选择哪种数据增强方式，mixup、CutMix或者Mosaic，还是需要有混贴票据的训练数据，才可以实现检测一张图片中有多张票据？

**Comment by qingqing01** [comment]
@Lie-huo  如果图片质量比较好，感觉可以每个类别100 - 500张看下效果。 数据增强，一张图构造多张票据，觉得可以用Mosaic吧。

**Comment by Lie-huo** [comment]
> @Lie-huo 如果图片质量比较好，感觉可以每个类别100 - 500张看下效果。 数据增强，一张图构造多张票据，觉得可以用Mosaic吧。

嗯嗯，好的。请问Mosaic的方式会在下一个版本里增加吗？

**Comment by qingqing01** [comment]
@Lie-huo 将要发布的是2.0rc版本。 @wangxinxin08 帮贴个下Mosaic的数据增强代码在这个issue里吧 :)

**Comment by wangxinxin08** [comment]
mosaic的代码：https://github.com/wangxinxin08/PaddleDetection/blob/yolo/ppdet/data/transform/operators.py#L3193，具体使用的话可以参考https://github.com/wangxinxin08/PaddleDetection/blob/yolo/configs/yolov5/yolov5_reader.yml

**Comment by hhxdestiny** [comment]
@qingqing01 请教一下opencv线性缩放对模型训练的影响有多大呢？比如手机拍的照片3000*3000像素的这种原图太大了，想预先缩放一下，比如缩放到800*800，然后标注好再传为数据集，用来训练。

**Comment by qingqing01** [comment]
@hhxdestiny  

看模型，两阶段模型应该不大，两阶段影响不大，默认的数据增强没有随机crop等。
YOLO的数据增强中有randomcrop, randshape等，可能有一些影响，不过精度可能不会差异特别大，也看实际目标的大小。

**Comment by hhxdestiny** [comment]
@qingqing01 好的。还有个问题请教一下，我发现模型是能学到一些角度信息的，如果数据集里都是方向比较正的图片，而真实场景各种方向都有的情况下，某些不正的方向上评分明显低于方向比较正的目标，这种情况对数据集做rotate能否解决问题呢？（鉴于rotate的图片可能需要重标，工作量较大，还没测试，偷懒问问大佬）
