### ISSUE TITLE
动态图版本

### ISSUE THREAD

**Issue by joordamn** [PaddlePaddle/PaddleDetection#2258]
请问动态图版本什么时候会发布

**Comment by heavengate** [comment]
您好，感谢关注，我们已经发布了动态图试用版本，在release/2.0-rc，现在已经作为默认分支发布了，可以pull一下最新代码在`dygraph`目录下体验，有什么问题可以反馈我们跟进~

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen issue
