### ISSUE TITLE
Failed to run PP-YOLO inference on exported model

### ISSUE THREAD

**Issue by platvlad** [PaddlePaddle/PaddleDetection#2265]
Hi!
I am trying to run inference on exported model as specified [here](https://github.com/PaddlePaddle/PaddleDetection/blob/master/configs/ppyolo/README.md#4-inferece-deployment-and-benchmark):

`python tools/export_model.py -c configs/ppyolo/ppyolo.yml -o weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams
CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output/ppyolo --image_file=demo/000000014439_640x640.jpg --use_gpu=True`

but get a segmentation fault.

This is the output of `python deploy/python/infer.py`:

<pre><code>-----------  Running Arguments -----------
camera_id: -1
image_file: demo/000000014439_640x640.jpg
model_dir: output/ppyolo
output_dir: output
run_benchmark: False
run_mode: fluid
threshold: 0.5
use_gpu: True
video_file: 
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Use Paddle Executor: False
Transform Order: 
--transform op: Resize
--transform op: Normalize
--transform op: Permute
--------------------------------------------
W0225 15:45:45.131456 2152937 analysis_predictor.cc:1059] Deprecated. Please use CreatePredictor instead.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: Segmentation fault is detected by the operating system.
  [TimeInfo: *** Aborted at 1614257147 (unix time) try "date -d @1614257147" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 2152937 (TID 0x7ff9347b6740) from PID 0 ***]

Segmentation fault (core dumped)
</code></pre>

When I remove flag `--use_gpu=True` it works fine.
Inference with specifying config and weights separately: 
`CUDA_VISIBLE_DEVICES=0 python tools/infer.py -c configs/ppyolo/ppyolo.yml -o weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams --infer_img=demo/000000014439_640x640.jpg`
is also working as expected.
My CUDA installation: `GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2`.

The problem looks like #1871 but may differ in details.
Thank you.

**Comment by heavengate** [comment]
确认一下机器上安装的CUDA版本，CUDNN版本和Paddle需求的版本是否一致呢

**Comment by platvlad** [comment]
@heavengate Thank you for your reply.
I have CUDA 11.0 and CUDNN 8.0.5, which are supported by Paddle according to [Paddle installation manuals](https://www.paddlepaddle.org.cn/documentation/docs/en/install/index_en.html#installation-manuals). 
However, my Ubuntu version is 20.04, which is not mentioned now in OS requirements.
