### ISSUE TITLE
VS 2019 cmake问题

### ISSUE THREAD

**Issue by berieo** [PaddlePaddle/PaddleDetection#2267]
![image](https://user-images.githubusercontent.com/34112784/109292361-3586f880-7865-11eb-8920-09a58cba9152.png)
在按照教程配置完cmake后，准备用vs生成解决方案时，出现这样的问题
第一个报错的位置
![image](https://user-images.githubusercontent.com/34112784/109292566-85fe5600-7865-11eb-8291-74bc71046e0c.png)

**Comment by heavengate** [comment]
看报错是CUDA的lib文件链接有问题，确认一下CUDA是否正确安装以及安装的CUDA版本和Paddle需求的版本是否一致呢

**Comment by liuhuiCNN** [comment]
看起来是CMake变量重定义了，强烈建议您用命令行试一下，使用命令行可以避免此类问题。

**Comment by berieo** [comment]
已经解决了，最后没有用VS编译，用了Cmake Gui编译，参考https://blog.csdn.net/yzl819819/article/details/106797234

**Comment by liuhuiCNN** [comment]
> 已经解决了，最后没有用VS编译，用了Cmake Gui编译，参考https://blog.csdn.net/yzl819819/article/details/106797234

感谢反馈，应该是VS对CmakeList支持不友好导致的，后续我们优化一下文档。

**Comment by yzl19940819** [comment]
> 已经解决了，最后没有用VS编译，用了Cmake Gui编译，参考https://blog.csdn.net/yzl819819/article/details/106797234

你好，我是该篇文章的作者，也是PaddleDetection的PM，关于部署的问题，方便的话，请加我微信17854262968，想根据您的场景一起来和我们优化在PaddleDetection的部署
