### ISSUE TITLE
best_model能否用于继续训练？

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleDetection#2269]
例如：`python3 train.py -c xxx.yml -r best_model`

**Comment by heavengate** [comment]
可以的，所有保存下来的模型都可以用来resume，resume的时候确保指定的checkpoint包含`.pdparams``.pdopt``.pdmodel`

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen issue
