### ISSUE TITLE
训练过程中途总是退出（killed），没任何错误提示

### ISSUE THREAD

**Issue by wjhtinger** [PaddlePaddle/PaddleDetection#2271]
ubuntu20系统，安装的CPU版本

wangjh@ubuntu:~/work/paddlepaddle/paddledetection/PaddleDetection$ python3 tools/train.py -c configs/yolov3_mobilenet_v1_roadsign.yml --eval -o use_gpu=false
/home/wangjh/.local/lib/python3.8/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/home/wangjh/.local/lib/python3.8/site-packages/paddle/fluid/framework.py:686: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
2021-02-27 18:57:22,403-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
2021-02-27 18:57:26,854-WARNING: variable yolo_output.1.conv.bias not used
2021-02-27 18:57:26,855-WARNING: variable yolo_output.0.conv.bias not used
2021-02-27 18:57:26,855-WARNING: variable yolo_output.1.conv.weights not used
2021-02-27 18:57:26,855-WARNING: variable yolo_output.2.conv.bias not used
2021-02-27 18:57:26,855-WARNING: variable yolo_output.0.conv.weights not used
2021-02-27 18:57:26,855-WARNING: variable yolo_output.2.conv.weights not used
W0227 18:57:43.968470  2491 build_strategy.cc:171] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
W0227 18:57:43.968658  2491 build_strategy.cc:430] fuse_bn_add_act_pass is only supported on GPU, skipped.
W0227 18:57:44.414002  2491 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 147. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 84.
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/reader.py:89: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  if isinstance(item, collections.Sequence) and len(item) == 0:
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py:253: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  header_str = self._base[0:self.s_allocator_header].tostring()
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py:299: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  status = self._base[start:end].tostring().decode()
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py:299: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  status = self._base[start:end].tostring().decode()
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py:253: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  header_str = self._base[0:self.s_allocator_header].tostring()
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py:299: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  status = self._base[start:end].tostring().decode()
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py:253: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  header_str = self._base[0:self.s_allocator_header].tostring()
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py:299: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  status = self._base[start:end].tostring().decode()
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py:253: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  header_str = self._base[0:self.s_allocator_header].tostring()
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py:299: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  status = self._base[start:end].tostring().decode()
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py:253: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  header_str = self._base[0:self.s_allocator_header].tostring()
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/reader.py:89: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  if isinstance(item, collections.Sequence) and len(item) == 0:
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/reader.py:89: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  if isinstance(item, collections.Sequence) and len(item) == 0:
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/reader.py:89: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  if isinstance(item, collections.Sequence) and len(item) == 0:
/home/wangjh/work/paddlepaddle/paddledetection/PaddleDetection/ppdet/data/reader.py:89: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  if isinstance(item, collections.Sequence) and len(item) == 0:
Killed

**Comment by heavengate** [comment]
`free -h`看你你机器上内存大小多少呢，看报错信息像是内存不够

**Comment by wjhtinger** [comment]
物理内存是8G的

**Comment by heavengate** [comment]
可以把`configs/yolov3_reader.yml`里`TrainReader.num_workers`设置成`-1`试下
