### ISSUE TITLE
base_lr如何设值？

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleDetection#2273]
服务器配置：8vCPU、32GiB、NVIDIA-V100、单卡
训练集：4826张
batch_size: 4
此时base_lr应当多少？

**Comment by qingqing01** [comment]
@670133189 

按照个教程， 依据总共的batch-size调整

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/docs/FAQ.md#faq%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
