### ISSUE TITLE
支持增量训练吗？

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#2274]
通过已有数据集训练出模型，上线后新增数据（标签与原数据集一致或者新增标签），不改变模型结构，paddleDetection支持增量训练吗？用原训练模型作为预训练模型加载，直接训练新增数据。请大神指教！！！！

**Comment by qingqing01** [comment]
@jackie8310 支持的

在YML中设置pretrain_weights字段的模型，或者命令通过 `-o pretrain_weights=` 设置即可，可以参考:


https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md#%E7%9B%B4%E6%8E%A5%E5%8A%A0%E8%BD%BD%E9%A2%84%E8%AE%AD%E7%BB%83%E6%9D%83%E9%87%8D%E6%8E%A8%E8%8D%90%E6%96%B9%E5%BC%8F

**Comment by jackie8310** [comment]
@qingqing01 , 采用这样方法训练新增数据集，发现对原数据集的预测精度下降（记忆力丢失部分）。同样的YML文件，增量训练时只是加载原模型为pretrain_weights。大神指教？难道要将新增数据与原数据一起重复训练？？

**Comment by qwzhuanghkclr** [comment]
同问~实际场景中有很大的需求喔~

**Comment by Alexhk01** [comment]
同问。
实际场景中有很大的需求喔~
