### ISSUE TITLE
怎么修改代码能够显示出测试每张图片所需要的时间？

### ISSUE THREAD

**Issue by yiyueming** [PaddlePaddle/PaddleDetection#2279]

**Comment by yghstill** [comment]
直接使用https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/deploy/python/infer.py 脚本进行预测就可以打印预测时间，同时支持batchmark模式，教程请参考推理部署教程：https://paddledetection.readthedocs.io/advanced_tutorials/deploy/index.html
