### ISSUE TITLE
建议增加一下ppyolo_2x_voc的配置说明

### ISSUE THREAD

**Issue by hhxdestiny** [PaddlePaddle/PaddleDetection#2280]
能否增加一下ppyolo_2x针对自定义voc格式数据集的配置说明，直接拷贝configs/ppyolo/ppyolo_roadsign_kunlun.yml中的内容（修改数据集路径）跑一会仍崩溃，看着说明改了一些参数也不行。配置文件这一块有点复杂了，有点望而生畏，issues中90%的问题都是配置问题。

**Comment by yghstill** [comment]
voc请参考这个配置文件：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/configs/ppyolo/ppyolo_voc.yml

可以进入dygraph文件夹体验最新动态图版本，我们重构了整体架构，dataset的配置文件更加简单不易出错，而且便于调试https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/dygraph
下个版本会将动态图作为默认结构，感谢提意见，关于issue中的问题我们也正在积极改进，提升易用性。
