### ISSUE TITLE
如何继续训练新一批的同类数据？

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleDetection#2281]
请教：比如昨天训练了1万张“篮球”，`max_iters`设了60,000；今天计划训练1千张新的“篮球”，该如何操作？

如果是添加【-r best_model】的话，`max_iters`如何设置？显然低于60,000是无法继续学习。那么意味着新训练的1千张“篮球”必须要设定高于60,000的`max_iters`？

还是说用迁移学习，学习同类的数据？

**Comment by yghstill** [comment]
直接使用迁移学习，不用resume，将学习率调低10倍及以上，max_iters根据数据量设置一个较小的范围即可

**Comment by 670133189** [comment]
迁移学习需要把上一次的训练集混淆在新训练集当中吗？



---原始邮件---
发件人: "Guanghua Yu"<notifications@github.com&gt;
发送时间: 2021年3月4日(周四) 中午1:43
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送: "670133189"<670133189@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] 如何继续训练新一批的同类数据？ (#2281)




 
直接使用迁移学习，不用resume，将学习率调低10倍及以上，max_iters根据数据量设置一个较小的范围即可

**Comment by yghstill** [comment]
不用，基于新数据继续finetune模型就行
