### ISSUE TITLE
测试部署的服务出错

### ISSUE THREAD

**Issue by wjhtinger** [PaddlePaddle/PaddleDetection#2283]
$python3 ../../deploy/serving/test_client.py ../../demo/road554.png
Traceback (most recent call last):
  File "../../deploy/serving/test_client.py", line 18, in <module>
    from paddle_serving_app.reader import *
ModuleNotFoundError: No module named 'paddle_serving_app'

Python 3.8.5

**Comment by lmk123568** [comment]
> $python3 ../../deploy/serving/test_client.py ../../demo/road554.png
> Traceback (most recent call last):
> File "../../deploy/serving/test_client.py", line 18, in
> from paddle_serving_app.reader import *
> ModuleNotFoundError: No module named 'paddle_serving_app'
> 
> Python 3.8.5

是不是包少了

**Comment by yghstill** [comment]
按照文档安装paddle-serving了吗：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/deploy/serving#2-%E5%AE%89%E8%A3%85-paddle-serving

**Comment by wjhtinger** [comment]
> 
> 
> 按照文档安装paddle-serving了吗：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/deploy/serving#2-%E5%AE%89%E8%A3%85-paddle-serving

都装了。
pip3 install paddle-serving-client -i https://mirror.baidu.com/pypi/simple
pip3 install paddle-serving-server -i https://mirror.baidu.com/pypi/simple

**Comment by liuhuiCNN** [comment]
> > 按照文档安装paddle-serving了吗：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/deploy/serving#2-%E5%AE%89%E8%A3%85-paddle-serving
> 
> 都装了。
> pip3 install paddle-serving-client -i https://mirror.baidu.com/pypi/simple
> pip install paddle-serving-server -i https://mirror.baidu.com/pypi/simple

请问都是用 pip3 安装的吗？ 请检查安装是否正确。

**Comment by wjhtinger** [comment]
> 
> 
> > > 按照文档安装paddle-serving了吗：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/deploy/serving#2-%E5%AE%89%E8%A3%85-paddle-serving
> > 
> > 
> > 都装了。
> > pip3 install paddle-serving-client -i https://mirror.baidu.com/pypi/simple
> > pip install paddle-serving-server -i https://mirror.baidu.com/pypi/simple
> 
> 请问都是用 pip3 安装的吗？ 请检查安装是否正确。

都是pip3装的，确认安装没问题

**Comment by liuhuiCNN** [comment]
建议使用python3.7试试。请参考 https://github.com/PaddlePaddle/Serving/blob/develop/README_CN.md 确认PaddleServing按照成功后，再部署。
