### ISSUE TITLE
faster rcnn配合文件参数问题

### ISSUE THREAD

**Issue by xiaolifeimianbao** [PaddlePaddle/PaddleDetection#2285]
faster rcnn配置文件中BBoxAssigner中的bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]是做什么用的，对哪有影响？

**Comment by yghstill** [comment]
Box回归loss的权重大小，只对训练时Box回归的loss权重有影响，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/generate_proposal_labels_cn.html#generate-proposal-labels

**Comment by xiaolifeimianbao** [comment]
> Box回归loss的权重大小，只对训练时Box回归的loss权重有影响，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/generate_proposal_labels_cn.html#generate-proposal-labels

和训练时候的Box的四个坐标的损失对应相乘的是吗

**Comment by yghstill** [comment]
> > Box回归loss的权重大小，只对训练时Box回归的loss权重有影响，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/generate_proposal_labels_cn.html#generate-proposal-labels
> 
> 和训练时候的Box的四个坐标的损失对应相乘的是吗

是的

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题你可以reopen此issue~
