### ISSUE TITLE
迁移学习需要把上一次的训练集混淆在新训练集当中吗？

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleDetection#2286]
请教：迁移学习需要把上一次的训练集混淆在新训练集当中吗？

**Comment by yghstill** [comment]
@670133189 可以不用的，模型如果已经上一次的训练集上收敛很好了，就不用加入新训练集中，直接将学习率调低，继续训练新数据即可。

**Comment by 670133189** [comment]
关于调低学习率：假设第一次训练=0.0001，第二次迁移学习降低=0.00001，那么第三次迁移学习呢？是相对第一次降低10%=0.0001还是相对第二次=0.000001 ？

**Comment by 670133189** [comment]
> @670133189 可以不用的，模型如果已经上一次的训练集上收敛很好了，就不用加入新训练集中，直接将学习率调低，继续训练新数据即可。

关于调低学习率：假设第一次训练=0.0001，第二次迁移学习降低=0.00001，那么第三次迁移学习呢？是相对第一次降低10%=0.0001还是相对第二次=0.000001 ？

**Comment by yghstill** [comment]
都相对于第一次调整即可，学习率太低，无法很好在新数据集上学习

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题你可以reopen此issue
