### ISSUE TITLE
paddle model转ONNX转engine

### ISSUE THREAD

**Issue by hjZhouGitHub** [PaddlePaddle/PaddleDetection#2288]
描述：
在使用export_model.py生成模型文件__model__和__params__后使用paddle2onnx或者paddle.onnx.export转换成ONNX (opset_version 11)文件后，再使用脚本转成TensorRT 的engine文件报错

环境：
paddle 2.0rc
tensorrt 7.1.3.4
onnx 1.8

目标检测模型：
ppyolo_2x
yolov3_r34
fast_rcnn_r50_1x

报错信息：
In node -1 (importRange): UNSUPPORTED_NODE: Assertion failed: inputs.at(0).isInt32() && "For range operator with dynamic inputs, this version of TensorRT only supports INT32!"

In node -1 (importResize): UNSUPPORTED_NODE: Assertion failed: (mode != "nearest" || nearest_mode == "floor") && "This version of TensorRT only supports floor nearest_mode!"

目前可能是节点不支持转换，请问是转的方法有问题还是目前paddle检测模型不支持转成engine文件？请问有方法将目标检测模型转换成engine文件吗？谢谢

**Comment by yghstill** [comment]
@hjZhouGitHub 检测方法里有些特定的OP在TensorRT里是不支持的，这个属于正常情况，建议您直接使用paddle下的TensorRT直接预测 ，导出模型后使用deploy下的cpp或python脚本设置`--run_mode=trt_fp32/trt_fp16`

**Comment by hjZhouGitHub** [comment]
> @yghstill 你好，paddle-tensorrt预测我之前了解过，但是我需要的是训练完的模型在deep stream中进行预测，所以需要导出engine文件。请问这些特定的OP可以自己修改吗？然后符合tensorRT，还有其它的方法吗？谢谢
