### ISSUE TITLE
您好，我出现了这个问题，同一个路径下的函数，有的可以找到，有的找不到，如下出现了：ModuleNotFoundError: No module named 'ppdet.utils.eval_utils'

### ISSUE THREAD

**Issue by zsffuture** [PaddlePaddle/PaddleDetection#2289]
![image](https://user-images.githubusercontent.com/39027951/109946154-e7656f80-7d12-11eb-8fba-fa55d08b96fd.png)

**Comment by zsffuture** [comment]
发生异常: ModuleNotFoundError
No module named 'ppdet.utils.eval_utils'
  File "D:\PaddleDetection\PaddleDetection\tools\infer.py", line 36, in <module>
    from ppdet.utils.eval_utils import parse_fetches

**Comment by zsffuture** [comment]
![image](https://user-images.githubusercontent.com/39027951/109946394-285d8400-7d13-11eb-97a6-d2662889ce63.png)
死活无法通过，怎么回事啊，但是通过vscode编辑器可以打开对应的函数的位置的，但是为什么老是报错啊

**Comment by yghstill** [comment]
@zsffuture 设置一下
```
export PYTHONPATH=`pwd`:$PYTHONPATH
```
再试下，然后确认一下ppdet.utils.eval_utils是否有parse_fetches函数.

**Comment by zsffuture** [comment]
我这里回答一下原因，我觉得是paddleDetection的一个bug，就是如果单独使用静态图，环境部署完成后是可以使用的，也不会出错，但是如果在进到动态图文件夹跑网络后，在返回回到静态文件夹后，就报了上面的错误，但是动态的环境是一直可以使用的，因此我觉得是个bug，官方能否看看，或者尝试一下，不用训练，直接跑你们的demo 的即可，一样会出错，我尝试了n次，最后发现了这个原因，因此想要不出问题，静态库开一个环境，千万不要跑动态图，否则在尝试静态图会报错，动态图单独开一个环境跑，这样两个就可以同时使用了 @yghstill

**Comment by yghstill** [comment]
@zsffuture 非常感谢调试与反馈，这个问题我们改进一下。

**Comment by heavengate** [comment]
> 我这里回答一下原因，我觉得是paddleDetection的一个bug，就是如果单独使用静态图，环境部署完成后是可以使用的，也不会出错，但是如果在进到动态图文件夹跑网络后，在返回回到静态文件夹后，就报了上面的错误，但是动态的环境是一直可以使用的，因此我觉得是个bug，官方能否看看，或者尝试一下，不用训练，直接跑你们的demo 的即可，一样会出错，我尝试了n次，最后发现了这个原因，因此想要不出问题，静态库开一个环境，千万不要跑动态图，否则在尝试静态图会报错，动态图单独开一个环境跑，这样两个就可以同时使用了 @yghstill

你好，你是在`dygraph`目录下使用了`python setup.py install`么

**Comment by zsffuture** [comment]
@heavengate 不是，官方给的教程，按照教程安装即可，和静态图差不多的，

**Comment by heavengate** [comment]
> @heavengate 不是，官方给的教程，按照教程安装即可，和静态图差不多的，

那应该是把动态图的目录加到PYTHONPATH里了，可以在根目录下试下
```
export PYTHONPATH=`pwd`:$PYTHONPATH
```

**Comment by zsffuture** [comment]
@heavengate 我用的是win10系统测试的，不知道我现在还不知道动态图下的python setup.py install有什么用，官方教程也没有提示啊，一般从github拉下来配置环境就可以进行运行了啊

**Comment by ilem777** [comment]
请问将develop分支上面的文件全部复制到dygraph文件夹里面，然后运行eval.py。然后我回到主目录继续训练其他模型，还会报错吗？

**Comment by PFloyd0** [comment]
@zsffuture 所以您最后是怎么运行静态图的模型的呢，我也遇到了这个问题不知道怎么解决
