### ISSUE TITLE
在COCO数据集训练ppYOLO，loss变nan

### ISSUE THREAD

**Issue by Sharpiless** [PaddlePaddle/PaddleDetection#2290]
训练中出现这个错误：
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/lib/function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)

学习率为0.005，其他配置如下：
LearningRate:
  base_lr: 0.00025
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 150000
    - 200000
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

**Comment by heavengate** [comment]
你好，配置文件里的`base_lr`是基于8卡训练，每卡batch_size=24的配置，如果你不是使用的8卡训练，或者修改了batch_size, 需要对应调整`base_lr`，参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/docs/FAQ.md#faq常见问题

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen issue
