### ISSUE TITLE
已解决（solved） ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by AndyTesla** [PaddlePaddle/PaddleDetection#2291]
python tools/infer.py -c configs/face_detection/blazeface.yml -o use_gpu=true weights= configs/weight/balzeface_original --infer_img=demo/4.jpg

weights参数后面多加了空格，把空格去掉就正常了：
python tools/infer.py -c configs/face_detection/blazeface.yml -o use_gpu=true weights=configs/weight/balzeface_original --infer_img=demo/4.jpg

**Comment by AndyTesla** [comment]
balzeface_original typo. 应该是blazeface_original

**Comment by heavengate** [comment]
命令行里`weights=`和`configs/weight/balzeface_original`中间多了个空格，被当成两个配置解析了，空格删掉就可以了
