### ISSUE TITLE
PaddleDetection在树莓派部署，预测时出现内存错误Check failed: bytes <= free_size():

### ISSUE THREAD

**Issue by Kiddo33** [PaddlePaddle/PaddleDetection#2292]
![error](https://user-images.githubusercontent.com/71620382/110099251-0ed43f00-7ddc-11eb-939e-fd021472a65b.png)

**Comment by heavengate** [comment]
看报错信息是机器上内存不够，用的是哪个模型呢，`free -h`看下机器内存多大

**Comment by Kiddo33** [comment]
> 看报错信息是机器上内存不够，用的是哪个模型呢，`free -h`看下机器内存多大

谢谢回复~
用的Yolov3-Mobilenetv1模型，
free-h的结果如下：
![free-h](https://user-images.githubusercontent.com/71620382/110264100-6e586780-7ff3-11eb-83f2-6a6fca63dc88.png)
换成更小的ppyolo模型后报错如下：
![屏幕截图 2021-03-08 095433](https://user-images.githubusercontent.com/71620382/110264495-5fbe8000-7ff4-11eb-96fb-d2e36cb2e8cd.jpg)
我是根据这个教程配置的：
https://github.com/PaddleCV-FAQ/PaddleDetection-FAQ/blob/main/Lite%E9%83%A8%E7%BD%B2/yolov3_for_raspi.md

**Comment by heavengate** [comment]
> > 看报错信息是机器上内存不够，用的是哪个模型呢，`free -h`看下机器内存多大
> 
> 谢谢回复~
> 用的Yolov3-Mobilenetv1模型，
> free-h的结果如下：
> ![free-h](https://user-images.githubusercontent.com/71620382/110264100-6e586780-7ff3-11eb-83f2-6a6fca63dc88.png)
> 换成更小的ppyolo模型后报错如下：
> ![屏幕截图 2021-03-08 095433](https://user-images.githubusercontent.com/71620382/110264495-5fbe8000-7ff4-11eb-96fb-d2e36cb2e8cd.jpg)
> 我是根据这个教程配置的：
> https://github.com/PaddleCV-FAQ/PaddleDetection-FAQ/blob/main/Lite%E9%83%A8%E7%BD%B2/yolov3_for_raspi.md

看你机器的内存是3.3G，教程里使用的输入图像尺寸是608*608，修改为320*320试下呢
![raspi](https://user-images.githubusercontent.com/12605721/110268840-5259c380-7ffd-11eb-9bb5-ad9d1c235116.png)

**Comment by Kiddo33** [comment]
> > > 看报错信息是机器上内存不够，用的是哪个模型呢，`free -h`看下机器内存多大
> > 
> > 
> > 谢谢回复~
> > 用的Yolov3-Mobilenetv1模型，
> > free-h的结果如下：
> > ![free-h](https://user-images.githubusercontent.com/71620382/110264100-6e586780-7ff3-11eb-83f2-6a6fca63dc88.png)
> > 换成更小的ppyolo模型后报错如下：
> > ![屏幕截图 2021-03-08 095433](https://user-images.githubusercontent.com/71620382/110264495-5fbe8000-7ff4-11eb-96fb-d2e36cb2e8cd.jpg)
> > 我是根据这个教程配置的：
> > https://github.com/PaddleCV-FAQ/PaddleDetection-FAQ/blob/main/Lite%E9%83%A8%E7%BD%B2/yolov3_for_raspi.md
> 
> 看你机器的内存是3.3G，教程里使用的输入图像尺寸是608_608，修改为320_320试下呢
> ![raspi](https://user-images.githubusercontent.com/12605721/110268840-5259c380-7ffd-11eb-9bb5-ad9d1c235116.png)

我已经改成320*320了，但不管这个参数设置多大，都报相同的错误

**Comment by heavengate** [comment]
> > > > 看报错信息是机器上内存不够，用的是哪个模型呢，`free -h`看下机器内存多大
> > > 
> > > 
> > > 谢谢回复~
> > > 用的Yolov3-Mobilenetv1模型，
> > > free-h的结果如下：
> > > ![free-h](https://user-images.githubusercontent.com/71620382/110264100-6e586780-7ff3-11eb-83f2-6a6fca63dc88.png)
> > > 换成更小的ppyolo模型后报错如下：
> > > ![屏幕截图 2021-03-08 095433](https://user-images.githubusercontent.com/71620382/110264495-5fbe8000-7ff4-11eb-96fb-d2e36cb2e8cd.jpg)
> > > 我是根据这个教程配置的：
> > > https://github.com/PaddleCV-FAQ/PaddleDetection-FAQ/blob/main/Lite%E9%83%A8%E7%BD%B2/yolov3_for_raspi.md
> > 
> > 
> > 看你机器的内存是3.3G，教程里使用的输入图像尺寸是608_608，修改为320_320试下呢
> > ![raspi](https://user-images.githubusercontent.com/12605721/110268840-5259c380-7ffd-11eb-9bb5-ad9d1c235116.png)
> 
> 我已经改成320*320了，但不管这个参数设置多大，都报相同的错误

如果确认不是输入图像太大内存不够的问题，看报错信息里面是opt模型的版本和PaddleLite版本不一致，可以确认一下PaddleLite版本问题
![Uploading paddlelite.png…]()

**Comment by Kiddo33** [comment]
> 看报错信息是机器上内存不够，用的是哪个模型呢，free -h看下机器内存多大
> 
> 谢谢回复~
> 用的Yolov3-Mobilenetv1模型，
> free-h的结果如下：
> 
> 换成更小的ppyolo模型后报错如下：
> 
> 我是根据这个教程配置的：
> https://github.com/PaddleCV-FAQ/PaddleDetection-FAQ/blob/main/Lite%E9%83%A8%E7%BD%B2/yolov3_for_raspi.md
> 
> 看你机器的内存是3.3G，教程里使用的输入图像尺寸是608_608，修改为320_320试下呢
> 
> 
> 我已经改成320*320了，但不管这个参数设置多大，都报相同的错误
> 
> 如果确认不是输入图像太大内存不够的问题，看报错信息里面是opt模型的版本和PaddleLite版本不一致，可以确认一下PaddleLite版本问题

opt版本问题，改为一致后解决。
