### ISSUE TITLE
快速开始：测试ppyolo不成功，output下生成的结果没有框和标注

### ISSUE THREAD

**Issue by GZHUZhao** [PaddlePaddle/PaddleDetection#2293]
1、环境：jetson nano   jetpack 4.3 cuda 10.0 cudnn 7.6

paddlepaddle-gpu: 2.0 使用的是官方提供的安装文件 ：2.0.0-nv-jetson-jetpack4.3-all(paddlepaddle_gpu-2.0.0-cp36-cp36m-linux_aarch64.whl) 地址：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html

paddledetection：release/0.5 和release/2.0-beta都存在这个问题
2、使用的命令
# 用PP-YOLO算法在COCO数据集上预训练模型预测一张图片
python tools/infer.py -c configs/ppyolo/ppyolo.yml -o use_gpu=true weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams --infer_img=demo/000000014439.jpg

3、提示信息
![提示](https://user-images.githubusercontent.com/78419361/110105631-9a050300-7de3-11eb-954c-2c7be46ccd05.png)

4、结果
在output文件夹下的图片是原图，没有框出目标和标注。
![结果](https://user-images.githubusercontent.com/78419361/110105667-a4270180-7de3-11eb-86d2-337f91bdc85a.png)

**Comment by heavengate** [comment]
看日志里预测的是`14439.jpg`，你查看的图片是`570688.jpg`是不是查看错文件了

**Comment by GZHUZhao** [comment]
> 看日志里预测的是`14439.jpg`，你查看的图片是`570688.jpg`是不是查看错文件了

没有看错，我测试了几个图片的，只是截图提示和查看图片不对应，都是在输出结果的output文件夹下查看的

**Comment by GZHUZhao** [comment]
在电脑win10环境下，使用paddle-gpu2.0 ,paddledetection=release/2.0-beta测试是没有问题的，但是jetson nano 中却没有结果（输出的结果是原图），求大佬帮忙解答一下！

**Comment by heavengate** [comment]
> 在电脑win10环境下，使用paddle-gpu2.0 ,paddledetection=release/2.0-beta测试是没有问题的，但是jetson nano 中却没有结果（输出的结果是原图），求大佬帮忙解答一下！

试下PaddleDetection最新发布的`release/2.0-rc`分支呢，这个分支之前验证过jetson的

**Comment by GZHUZhao** [comment]
> > 在电脑win10环境下，使用paddle-gpu2.0 ,paddledetection=release/2.0-beta测试是没有问题的，但是jetson nano 中却没有结果（输出的结果是原图），求大佬帮忙解答一下！
> 
> 试下PaddleDetection最新发布的`release/2.0-rc`分支呢，这个分支之前验证过jetson的

也不行，使用PaddleDetection release/2.0-rc也是同样的结果，用不了gpu。请问之前验证过的paddlepaddle-gpu是哪个版本的？

**Comment by GZHUZhao** [comment]
@liuhuiCNN 
@heavengate 
麻烦帮忙跟进一下，在deploy/python/infer.py下也是gpu不行，cpu可以。
感谢！！🙏

**Comment by DragonGongY** [comment]
遇到同样的问题，Nano的gpu不同框，但在台式机或者cpu上正常，请问有解决了这个问题的吗？

**Comment by lleesg** [comment]
> 遇到同样的问题，Nano的gpu不同框，但在台式机或者cpu上正常，请问有解决了这个问题的吗？

+1
