### ISSUE TITLE
建议更新文档

### ISSUE THREAD

**Issue by duohappy** [PaddlePaddle/PaddleDetection#2295]
[Linux平台编译指南](https://github.com/PaddlePaddle/PaddleDetection/blob/master/deploy/cpp/docs/linux_build.md)

里面的链接会重定向跳转到 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/index_cn.html

但是这不是正确的跳转内容

**Comment by qingqing01** [comment]
Fixed by https://github.com/PaddlePaddle/PaddleDetection/pull/2315

**Comment by duohappy** [comment]
> 
> 
> Fixed by #2315

ok, I close this issue
