### ISSUE TITLE
测试infer过程报错 IndexError: index 3052 is out of bounds for axis 0 with size 3000

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#2297]
```
2021-03-07 13:42:51,049-INFO: Infer iter 10
Traceback (most recent call last):
  File "infer.py", line 261, in <module>
    main()
  File "infer.py", line 211, in main
    mask_results, lmk_results)
  File "/home/shujisheng/download/PaddleDetection/ppdet/utils/visualizer.py", line 39, in visualize_results
    image = draw_mask(image, im_id, mask_results, threshold)
  File "/home/shujisheng/download/PaddleDetection/ppdet/utils/visualizer.py", line 68, in draw_mask
    img_array[idx[0], idx[1], :] *= 1.0 - alpha
IndexError: index 3052 is out of bounds for axis 0 with size 3000
```

**Comment by qingqing01** [comment]
@shuxsu 请问您是什么模型吗？ SOLOv2还是Mask-RCNN? 以及PaddleDetection是哪个版本？

**Comment by shuxsu** [comment]
> @shuxsu 请问您是什么模型吗？ SOLOv2还是Mask-RCNN? 以及PaddleDetection是哪个版本？

mask rcnn  paddle版本1.8.4  detection的版本不知道了  是去年下载的paddledetection  
![58696F1FD77C564CCAFC4B99D93E847D](https://user-images.githubusercontent.com/45937014/110279634-5c3af100-8014-11eb-88d1-a3b507ffc155.jpg)
除了这种方式还有其他方式能查看版本信息吗

**Comment by shuxsu** [comment]
> @shuxsu 请问您是什么模型吗？ SOLOv2还是Mask-RCNN? 以及PaddleDetection是哪个版本？

还有一个问题 我在训练通过 x2coco 转换的cityscape数据集过程中  loss在衰减 也不报错 但是评估指标都是0

**Comment by shuxsu** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/45937014/110272744-df087f80-8005-11eb-8947-1c475b611f7a.png">
不知道是不是这个预训练模型没有找到的原因 我下载到本地训练 -o weights加上地址还提示找不到  直接在配置yml里面的pre weights 加上地址也是找不到  不知道是不是这个原因导致迁移训练出现问题 导致评估指标为0

**Comment by qingqing01** [comment]
1. PaddleDetection版本查看

```
git status 
git log
```

和PaddlePaddle 1.8.4对应的 0.4分支和0.5分支都可以。


2. mAP一直评估是0，不太正常。

3. 下面WARNING是部分参数没加载，这些参数是class-num变了，weight的shape不匹配 不加载，是正常的。

**Comment by shuxsu** [comment]
> 1. PaddleDetection版本查看
> 
> ```
> git status 
> git log
> ```
> 
> 和PaddlePaddle 1.8.4对应的 0.4分支和0.5分支都可以。
> 
> 1. mAP一直评估是0，不太正常。
> 2. 下面WARNING是部分参数没加载，这些参数是class-num变了，weight的shape不匹配 不加载，是正常的。

我使用版本为最新的PaddleDetection 2.0的 还是出现这种情况 loss收敛但map=0
原因能不能是因为没有加载进来预训练模型 数据集2000张训练图像  只迭代9600轮  训练次数过少导致map=0？
以及上面的IndexError: index 3052 is out of bounds for axis 0 with size 3000  这个原因能是什么呢

**Comment by shuxsu** [comment]
现在就想知道如何能把预训练模型的权重用在我现在的训练上
不管是在配置yml里挂那个tar下载链接还是下到本地解压 都不行 
解压用绝对路径还是提示找不到 或者提示不是pdparams文件

**Comment by qingqing01** [comment]
@shuxsu

yml或命令里指定 pretrain_weights即可，例如:

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/configs/yolov3_darknet_roadsign.yml#L9

我看您关闭了issue，是问题已经解决了嘛？
