### ISSUE TITLE
RuntimeError: parallel_for failed: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Jusec** [PaddlePaddle/PaddleDetection#2298]
![image](https://user-images.githubusercontent.com/42871129/110241723-40d8d300-7f8d-11eb-830d-77823f66a3ba.png)
这个问题要怎么解决？

**Comment by qingqing01** [comment]
@Jusec  

> no kernel image is available for execution on the device

这个错误和安装环境有关。能描述下，您本地的CUDA环境，以及您安装的PaddlePaddle版本吗？

**Comment by Jusec** [comment]
> @Jusec
> 
> > 没有内核映像可用于在设备上执行
> 
> 这个错误和安装环境有关。能描述下，您本地的CUDA环境，以及您安装的PaddlePaddle版本吗？

我的cuda安装的是10.0版本，我安装的paddlepaddle版本是1.8.5
![image](https://user-images.githubusercontent.com/42871129/110285419-31559a80-801e-11eb-8a86-8c1a921e80c1.png)
![image](https://user-images.githubusercontent.com/42871129/110285460-3dd9f300-801e-11eb-865b-49adbe42e83d.png)

**Comment by qingqing01** [comment]
从上面错误信息看，感觉是环境有点问题，参数初始化时就挂了。 您使用下面代码测试下CUDA环境呢？ 另外，您GPU型号是多少？显存多大？

```
import paddle.fluid as fluid
import paddle
import numpy as np

# paddle.enable_static()  2.0需要


x = fluid.data(name='x', shape=[2, 32], dtype='float32')
y = fluid.data(name='y', shape=[2, 32], dtype='float32')

z = x + y


exe = fluid.Executor(paddle.CUDAPlace(0))

x_arr = np.random.rand(2, 32).astype('float32')
y_arr = np.random.rand(2, 32).astype('float32')
out = exe.run(feed={'x': x_arr, 'y': y_arr}, fetch_list=[z])
print(out)

```

**Comment by Jusec** [comment]
> 从上面错误信息看，感觉是环境有点问题，参数初始化时就挂了。 您使用下面代码测试下CUDA环境呢？ 另外，您GPU型号是多少？显存多大？
> 
> ```
> import paddle.fluid as fluid
> import paddle
> import numpy as np
> 
> # paddle.enable_static()  2.0需要
> 
> 
> x = fluid.data(name='x', shape=[2, 32], dtype='float32')
> y = fluid.data(name='y', shape=[2, 32], dtype='float32')
> 
> z = x + y
> 
> 
> exe = fluid.Executor(paddle.CUDAPlace(0))
> 
> x_arr = np.random.rand(2, 32).astype('float32')
> y_arr = np.random.rand(2, 32).astype('float32')
> out = exe.run(feed={'x': x_arr, 'y': y_arr}, fetch_list=[z])
> print(out)
> ```
显卡是3070，8g显存![image](https://user-images.githubusercontent.com/42871129/110310828-f2cfd800-803d-11eb-9447-40d974175ab0.png)
exe = fluid.Executor(paddle.CUDAPlace(0))这个是不是写错了？
是不是应该为这个 exe = fluid.Executor(fluid .CUDAPlace(0))，下面这个可以运行。

**Comment by qingqing01** [comment]
@Jusec 

是的，上面是针对2.0的，你用下面代码测试看下吧

```
import paddle.fluid as fluid
import paddle
import numpy as np

x = fluid.data(name='x', shape=[2, 3, 32, 32], dtype='float32')
y = fluid.data(name='y', shape=[2, 32, 32, 32], dtype='float32')
conv = fluid.layers.conv2d(x, 32, 1, param_attr=fluid.initializer.Normal())

z = conv + y

exe = fluid.Executor(fluid.CUDAPlace(0))

x_arr = np.random.rand(2, 3, 32, 32).astype('float32')
y_arr = np.random.rand(2, 32, 32, 32).astype('float32')

exe.run(fluid.default_startup_program())
out = exe.run(feed={'x': x_arr, 'y': y_arr}, fetch_list=[z])
print(out)
```

**Comment by Jusec** [comment]
> @Jusec
> 
> 是的，上面是针对2.0的，你用下面代码测试看下吧
> 
> ```
> import paddle.fluid as fluid
> import paddle
> import numpy as np
> 
> x = fluid.data(name='x', shape=[2, 3, 32, 32], dtype='float32')
> y = fluid.data(name='y', shape=[2, 32, 32, 32], dtype='float32')
> conv = fluid.layers.conv2d(x, 32, 1, param_attr=fluid.initializer.Normal())
> 
> z = conv + y
> 
> exe = fluid.Executor(fluid.CUDAPlace(0))
> 
> x_arr = np.random.rand(2, 3, 32, 32).astype('float32')
> y_arr = np.random.rand(2, 32, 32, 32).astype('float32')
> 
> exe.run(fluid.default_startup_program())
> out = exe.run(feed={'x': x_arr, 'y': y_arr}, fetch_list=[z])
> print(out)
> ```
运行不了
![image](https://user-images.githubusercontent.com/42871129/110443647-1acf4200-80f7-11eb-8731-7f8359970680.png)

**Comment by qingqing01** [comment]
@Jusec 如果上面测试代码无法运行的话，还是安装环境有问题。需要先确保安装的正常。注意CUDA的驱动等需要版本正确。依据PaddlePaddle的安装文档，检查下吧。
