### ISSUE TITLE
训练yolov3时设定图片大小的疑问

### ISSUE THREAD

**Issue by duohappy** [PaddlePaddle/PaddleDetection#2299]
我之前一直用darknet，训练yolov3时，第一步就是在cfg文件中，设定图片的大小。

查看PaddleDetection的config文件夹里面的**yolov3_reader.yml**，却没有关于图像大小的设定。

只找到了训练过程中，这样的设定，难道将320 ~ 608的图片尺寸都训练了？

``` bash
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
    random_inter: True
  - !NormalizeImage
```

**Comment by jerrywgz** [comment]
是的，yolov3的训练过程是在预处理阶段每个batch的图片随机选择一个尺寸进行reshape

**Comment by duohappy** [comment]
> 
> 
> 是的，yolov3的训练过程是在预处理阶段每个batch的图片随机选择一个尺寸进行reshape

假设我训练一个yolov3模型，使用darknet框架，配置cfg文件的图像大小为416×416，训练总次数为1000次
使用paddlepaddle框架，训练总次数多少合适呢？因为存在多个size **[320, 352, 384, 416, 448, 480, 512, 544, 576, 608]**，训练次数要翻倍么？

假设我训练一个yolov3模型，使用darknet框架，配置cfg文件的图像大小为1024×1024，那么对应的paddlepaddle配置文件怎么更改呢？是直接把1024添加到[320, 352, 384, 416, 448, 480, 512, 544, 576, 608]中？

**Comment by jerrywgz** [comment]
randomshape本身是多尺度训练策略，不需要对其他参数做改动，训练总次数也是不需要改的，如果原本的图像大小是1024，randomshape使用的尺度可以是1024附近的shape，比如[896, 928, 960, 992, 1024]这种

**Comment by duohappy** [comment]
> 
> 
> randomshape本身是多尺度训练策略，不需要对其他参数做改动，训练总次数也是不需要改的，如果原本的图像大小是1024，randomshape使用的尺度可以是1024附近的shape，比如[896, 928, 960, 992, 1024]这种


明白了，最后通过export_model.py，加上参数 TestReader.inputs_def.image_shape=[3,1024,1024]，导出这个1024模型

**Comment by jerrywgz** [comment]
嗯是的
