### ISSUE TITLE
导出paddleDetection中mask_rcnn为ONNX出错

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/PaddleDetection#2302]
先使用PaddleDetection 中自带export_model 代码导出为inference_model
![image](https://user-images.githubusercontent.com/52873355/110270680-4c65e180-8001-11eb-8c70-f599018101aa.png)

然后使用下面命令转onnx：

```
paddle2onnx --model_dir mask_rcnn_r50_fpn_2x --model_filename mask_rcnn_r50_fpn_2x/__model__ --params_filename mask_rcnn_r50_fpn_2x\__params__ --save_file onnx_file.onnx --opset_version 12 --enable_onnx_checker True

```

完整报错：

```
d:\softwarework\anaconda3\lib\site-packages\urllib3\util\selectors.py:14: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
from collections import namedtuple, Mapping
d:\softwarework\anaconda3\lib\site-packages\urllib3_collections.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
from collections import Mapping, MutableMapping
Traceback (most recent call last):
File "d:\softwarework\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "d:\softwarework\anaconda3\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "D:\SoftwareWork\Anaconda3\Scripts\paddle2onnx.exe_main.py", line 7, in
File "d:\softwarework\anaconda3\lib\site-packages\paddle2onnx\command.py", line 136, in main
program2onnx(
File "d:\softwarework\anaconda3\lib\site-packages\paddle2onnx\command.py", line 107, in program2onnx
p2o.program2onnx(
File "d:\softwarework\anaconda3\lib\site-packages\paddle2onnx\convert.py", line 74, in program2onnx
export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
File "d:\softwarework\anaconda3\lib\site-packages\paddle2onnx\convert.py", line 31, in export_onnx
onnx_graph = ONNXGraph.build(paddle_graph, opset_version, verbose)
File "d:\softwarework\anaconda3\lib\site-packages\paddle2onnx\graph\onnx_graph.py", line 208, in build
onnx_graph.build_op_nodes(paddle_graph.node_map)
File "d:\softwarework\anaconda3\lib\site-packages\paddle2onnx\graph\onnx_graph.py", line 162, in build_op_nodes
OpMapper.check_support_status(node_map, self.opset_version)
File "d:\softwarework\anaconda3\lib\site-packages\paddle2onnx\op_mapper\op_mapper.py", line 144, in check_support_status
raise NotImplementedError(error_info)
NotImplementedError:
There's 4 ops are not supported yet
=========== less_than ===========
=========== assign ===========
=========== conditional_block ===========
=========== logical_not ===========
```

**是我命令用的不对吗**

**Comment by qingqing01** [comment]
@PhilCuriosity 

由于两阶段的检测模型较复杂， 导出ONNX一些需要特殊适配，具体已经适配的模型参考 https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/model_zoo.md#%E5%9B%BE%E5%83%8F%E6%A3%80%E6%B5%8B-1

MaskRCNN的模型导出，我们请教下Paddle2ONNX的同事~

**Comment by PhilCuriosity** [comment]
好的，谢谢

**Comment by PhilCuriosity** [comment]
> @PhilCuriosity
> 
> 由于两阶段的检测模型较复杂， 导出ONNX一些需要特殊适配，具体已经适配的模型参考 https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/model_zoo.md#%E5%9B%BE%E5%83%8F%E6%A3%80%E6%B5%8B-1
> 
> MaskRCNN的模型导出，我们请教下Paddle2ONNX的同事~

好的，谢谢

**Comment by jiangjiajun** [comment]
> > @PhilCuriosity
> > 由于两阶段的检测模型较复杂， 导出ONNX一些需要特殊适配，具体已经适配的模型参考 https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/model_zoo.md#%E5%9B%BE%E5%83%8F%E6%A3%80%E6%B5%8B-1
> > MaskRCNN的模型导出，我们请教下Paddle2ONNX的同事~
> 
> 好的，谢谢

你好，当前maskrcnn中由于存在控制流，暂还无法支持，目前对于ppdet中的模型，支持的包括`FasterRCNN`、`SSD`、`YOLOv3`系列、`PPYOLO`系列

**Comment by bliu3650** [comment]
> > > @PhilCuriosity
> > > 由于两阶段的检测模型较复杂， 导出ONNX一些需要特殊适配，具体已经适配的模型参考 https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/model_zoo.md#%E5%9B%BE%E5%83%8F%E6%A3%80%E6%B5%8B-1
> > > MaskRCNN的模型导出，我们请教下Paddle2ONNX的同事~
> > 
> > 
> > 好的，谢谢
> 
> 你好，当前maskrcnn中由于存在控制流，暂还无法支持，当前对于ppdet中的模型，支持的包括`FasterRCNN`、`SSD`、`YOLOv3`系列、`PPYOLO`系列

在 release/2.0rc 的 dygraph 目录下，先 export YOLOv3 和 PPYOLO 到 inference model，然后调用 paddle.onnx.export，也出现了

There's 5 ops are not supported yet
=========== conditional_block ===========
=========== sync_batch_norm ===========
=========== logical_not ===========
=========== select_input ===========
=========== assign ===========

请确认！

另外，可以提供 PPYOLO 和 YOLOv3 的静态模型下载链接吗 （__model__ /__param__）？谢谢！

**Comment by PhilCuriosity** [comment]
> > > @PhilCuriosity
> > > 由于两阶段的检测模型较复杂， 导出ONNX一些需要特殊适配，具体已经适配的模型参考 https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/model_zoo.md#%E5%9B%BE%E5%83%8F%E6%A3%80%E6%B5%8B-1
> > > MaskRCNN的模型导出，我们请教下Paddle2ONNX的同事~
> > 
> > 
> > 好的，谢谢
> 
> 你好，当前maskrcnn中由于存在控制流，暂还无法支持，目前对于ppdet中的模型，支持的包括`FasterRCNN`、`SSD`、`YOLOv3`系列、`PPYOLO`系列
好的，谢谢

**Comment by jiangjiajun** [comment]
静态图版本中，直接在release 2.0分支中下载预训练模型，调用tools/export_model.py脚本导出即可

**Comment by bliu3650** [comment]
> 静态图版本中，直接在release 2.0分支中下载预训练模型，调用tools/export_model.py脚本导出即可

谢谢。这样得到的还是把在 paddle 2.0 上训练的动态图，转换成静态图。可能我刚才没有表述清楚。目前还能下载 paddle 2.0 版本以前的 （比如 paddle 1.8）PPYOLO / YOLOv3 预训练模型吗？

--------------------------------------------------------------------------------------------------

OK. 在 paddle2onnx 项目里，找到了代码 release 0.4 和静态模型库（检测）的对应关系了。
https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/en/model_zoo.md

**Comment by zlsh80826** [comment]
> > > @PhilCuriosity
> > > 由于两阶段的检测模型较复杂， 导出ONNX一些需要特殊适配，具体已经适配的模型参考 https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/model_zoo.md#%E5%9B%BE%E5%83%8F%E6%A3%80%E6%B5%8B-1
> > > MaskRCNN的模型导出，我们请教下Paddle2ONNX的同事~
> > 
> > 
> > 好的，谢谢
> 
> 你好，当前maskrcnn中由于存在控制流，暂还无法支持，目前对于ppdet中的模型，支持的包括`FasterRCNN`、`SSD`、`YOLOv3`系列、`PPYOLO`系列

請問一下 mask rcnn 的 control flow 是必須的嗎？
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/ppdet/modeling/architectures/mask_rcnn.py#L265
這邊的這個 `fluid.layers.cond(cond, noop, process_boxes)` 如果改成 `process_boxes()` 會有什麼影響呢？
我這邊嘗試這樣更改後再 export/deploy 結果似乎是一樣的

**Comment by qingqing01** [comment]
@zlsh80826 

正常图片可以不需要，一些图片，检测的bbox可能是空，后面就无法做mask分割了，因此这里加了判断。
