### ISSUE TITLE
根据https://paddlex.readthedocs.io/zh_CN/develop/deploy/server/cpp/windows.html编译报如下错误

### ISSUE THREAD

**Issue by hehu56** [PaddlePaddle/PaddleDetection#2306]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		'E:/paddlex_test/fluid_inference/paddle/lib/libpaddle_fluid.lib', needed by 'paddlex_inference/video_classifier.exe', missing and no known rule to make it	E:\paddlex_test\paddlex\PaddleX-develop\deploy\cpp\out\build\x64-Release\cpp	E:\paddlex_test\paddlex\PaddleX-develop\deploy\cpp\out\build\x64-Release\ninja	1

**Comment by qingqing01** [comment]
@liuhuiCNN please help to look

**Comment by liuhuiCNN** [comment]
（1）麻烦提供更加信息的错误提示。
（2）根据提示：no known rule to make it，建议请您检查makefile或CMakeList是否正确。

**Comment by qingqing01** [comment]
@hehu56  另外，如果是PaddleX的部署的话，可能需要 到 https://github.com/PaddlePaddle/PaddleX 这里提问哈
