### ISSUE TITLE
增量学习问题：

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#2307]
通过已有数据集训练出模型，上线后新增数据（标签数量和类别与原数据集一致），不改变模型结构，采用在YML中加载pretrain_weights已训练出的模型，发现对原数据集的预测精度下降（记忆力丢失部分），对新增数据集预测效果不好（打分低或者没有学习到）。其中，增量学习时，基于预训练模型将LR调小10倍了。求指教！！

**Comment by heavengate** [comment]
你好，增量训练的时候是只训练的新数据还是混在原来数据里一起训练的呢

**Comment by jackie8310** [comment]
@heavengate 只训练新数据，出线原始数据遗忘。如加入一起训练，可保留原始数据预测性能，但新加入数据拟合不好。

**Comment by heavengate** [comment]
> @heavengate 只训练新数据，出线原始数据遗忘。如加入一起训练，可保留原始数据预测性能，但新加入数据拟合不好。

尝试一下增加新数据的权重呢，比如新数据每张加入数据集时copy 10份之类的？
