### ISSUE TITLE
多个数据集训练的疑问

### ISSUE THREAD

**Issue by duohappy** [PaddlePaddle/PaddleDetection#2310]
我对[如何准备数据](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/docs/tutorials/PrepareDataSet.md)感到很困惑。在现实场景下，一般有多个数据集合，分布在服务器不同地方，而不仅仅是在特定的文件夹里。

**当有新的检测任务时，我们从不同的数据集合里，抽取合适的数据进行训练**

我读完了github上的帮助文档，并没有一个简单的方式做这件事情

+ 组成coco格式数据集

从多个数据集，抽取图片，组成一个json文件，json文件里的filename可以填写图像文件的绝对路径么？
``` html
'file_name': '000000391895.jpg',    # file_name
```
如果不能表示为绝对路径，那么训练时，怎么根据json文件的信息找到训练图片呢？

+ 组成voc格式数据集

voc格式的文件，可以在train.txt和val.txt中，填写图片和标注的绝对路径，这一点没有问题，根据绝对路径信息找到图片和标注。
其中又有一个问题，voc格式的数据集，metric不能使用coco，请问metric用voc和coco哪个好呢？官方是不是推荐使用coco格式的数据集进行训练？

**Comment by heavengate** [comment]
- 组成coco格式数据集

coco数据集一般是将图片整理在一个单独的文件夹里，这时候`file_name`直接填图片的文件名就可以了，在配置文件中，通过`image_dir`指向图片存储的文件夹，即`image_dir` + `file_name`即为图片的路径

- 组成coco格式数据集

VOC的metric只会计算mAP(0.5), 及COCO metric结果的第二条，具体看你们的任务要求，需要的mAP严不严格，一般业务场景用VOC和COCO的metric方式的都有，发paper之类的话现在主要用COCO

**Comment by duohappy** [comment]
> 
> 
>     * 组成coco格式数据集
> 
> 
> coco数据集一般是将图片整理在一个单独的文件夹里，这时候`file_name`直接填图片的文件名就可以了，在配置文件中，通过`image_dir`指向图片存储的文件夹，即`image_dir` + `file_name`即为图片的路径

通过coco格式来组成训练数据集，必须把所需的图片放在一个文件夹里，如果可能，这一点要改进一下，现在coco格式的数据集组织方式不太实用
https://github.com/PaddlePaddle/PaddleDetection/issues/1938
https://github.com/PaddlePaddle/PaddleDetection/issues/1557
https://github.com/PaddlePaddle/PaddleDetection/issues/493


>     * 组成coco格式数据集
> 
> 
> VOC的metric只会计算mAP(0.5), 及COCO metric结果的第二条，具体看你们的任务要求，需要的mAP严不严格，一般业务场景用VOC和COCO的metric方式的都有，发paper之类的话现在主要用COCO

voc格式数据集，能做到用coco的metric方式吗？

**Comment by heavengate** [comment]
> 通过coco格式来组成训练数据集，必须把所需的图片放在一个文件夹里，如果可能，这一点要改进一下，现在coco格式的数据集组织方式不太实用

嗯，如果不想放到一个文件家里，json里面的`file_name`可以带一下文件夹的名字，只要保证`image_dir`+`file_name`就是图片路径就可以了，多个数据集的方式我们评估支持一下~

> > * 组成coco格式数据集
> > ```
> > 
> > 
> > VOC的metric只会计算mAP(0.5), 及COCO metric结果的第二条，具体看你们的任务要求，需要的mAP严不严格，一般业务场景用VOC和COCO的metric方式的都有，发paper之类的话现在主要用COCO
> 
> 
> voc格式数据集，能做到用coco的metric方式吗？

voc格式的数据集不太能用coco的metric方式，coco的metric方式是将输出结果保存成一个json文件，然后共这个json文件和数据集的标注json文件(gt)去对比计算，而voc没有这种json文件，不太能走coco的metric方式，如果你是voc格式的数据集想使用coco的metric方式，可用通过`x2coco.py`脚本转换成coco格式
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/tools/x2coco.py

**Comment by duohappy** [comment]
> 
> 
> > 通过coco格式来组成训练数据集，必须把所需的图片放在一个文件夹里，如果可能，这一点要改进一下，现在coco格式的数据集组织方式不太实用
> 
> 嗯，如果不想放到一个文件家里，json里面的`file_name`可以带一下文件夹的名字，只要保证`image_dir`+`file_name`就是图片路径就可以了，多个数据集的方式我们评估支持一下~
> 
> > > * 组成coco格式数据集
> > > 
> > > ```
> > > 
> > > 
> > > VOC的metric只会计算mAP(0.5), 及COCO metric结果的第二条，具体看你们的任务要求，需要的mAP严不严格，一般业务场景用VOC和COCO的metric方式的都有，发paper之类的话现在主要用COCO
> > > ```
> > 
> > 
> > voc格式数据集，能做到用coco的metric方式吗？
> 
> voc格式的数据集不太能用coco的metric方式，coco的metric方式是将输出结果保存成一个json文件，然后共这个json文件和数据集的标注json文件(gt)去对比计算，而voc没有这种json文件，不太能走coco的metric方式，如果你是voc格式的数据集想使用coco的metric方式，可用通过`x2coco.py`脚本转换成coco格式
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/tools/x2coco.py

感谢解答，我关闭这个issue :smiley: 👍

**Comment by duohappy** [comment]
> 
> 
> > > 通过coco格式来组成训练数据集，必须把所需的图片放在一个文件夹里，如果可能，这一点要改进一下，现在coco格式的数据集组织方式不太实用
> > 
> > 
> > 嗯，如果不想放到一个文件家里，json里面的`file_name`可以带一下文件夹的名字，只要保证`image_dir`+`file_name`就是图片路径就可以了，多个数据集的方式我们评估支持一下~



https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/ppdet/data/source/coco.py#L109

我看了一下COCO数据集的解析源码，组成图片的绝对路径，有2种方法
1. `image_dir`+`file_name`是图像的绝对路径
2. **最简单的方法，可以把json里面的`file_name`直接写成图片的绝对路径 ，同样会有同样效果**

**数据准备**中filename，其实都可以填写绝对路径，可以跨过 `img_dir` `dataset_dir`的约束，当然了，不知道官方是否推荐使用`绝对路径`这种方式？
``` python
im_path = os.path.join(image_dir,
                  im_fname) if image_dir else im_fname
```
