### ISSUE TITLE
PaddleDetection在windows下的部署C++编译时提示4个位声明符号

### ISSUE THREAD

**Issue by caterwang13K73** [PaddlePaddle/PaddleDetection#2312]
VS2019 C++编译main.cc时提示以下几个未声明的符号：
#CV_CAP_PROP_FRAME_WIDTH 
#CV_CAP_PROP_FRAME_HEIGHT 
#CV_CAP_PROP_FPS 
#CV_IMWRITE_JPEG_QUALITY

**Comment by yzl19940819** [comment]
C++部署问题，方便的话，请加一下微信17854262968，具体看看问题

**Comment by caterwang13K73** [comment]
确认问题出在哪了，开始用的openCV版本是4.5的版本，按布蜀说明用3.6版本后正常了。

**Comment by caterwang13K73** [comment]
确认问题出在哪了，开始用的openCV版本是4.5的版本，按布蜀说明用3.6版本后正常了。

谢谢！



 
&nbsp;
 
================================================================
王凯&nbsp;&nbsp;&nbsp;&nbsp;
手机：13378852945
 
深圳辉锐天眼科技有限公司
ShenZhen&nbsp;Skyeyes&nbsp;Science&nbsp;&amp;&nbsp;Technology&nbsp;Co.,Ltd
网址：www.skyeyes.com.cn
电话：0755-86284818
传真：0755-86284811
客服热线：400-6626-833
公司地址：深圳市南山区科技园高新南一道万德莱大厦北座401
================================================================








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月10日(星期三) 上午10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] PaddleDetection在windows下的部署C++编译时提示4个位声明符号 (#2312)





 
C++部署问题，方便的话，请加一下微信17854262968，具体看看问题
