### ISSUE TITLE
PaddleDetection/deploy/python/infer.py部署时模型加载慢的问题

### ISSUE THREAD

**Issue by liangruofei** [PaddlePaddle/PaddleDetection#2314]
各位大佬：
    利用PaddleDetection export出的模型用 PaddleDetection/deploy/python/infer.py部署时，当run_mode选择trt_fp32/trt_fp16时，会进行模型转换，加载很慢，请问有什么方法，可以提前转换好或加速转换，更方便实际部署应用时重启系统又得加载一遍

**Comment by liuhuiCNN** [comment]
感谢反馈。请参考这里文档：https://paddle-inference.readthedocs.io/en/latest/optimize/paddle_trt.html。
将use_static设置为True，类型：bool, 默认值为False。如果指定为True，在初次运行程序的时候会将TRT的优化信息进行序列化到磁盘上（model_dir里面的文件中），下次运行时直接加载优化的序列化信息而不需要重新生成（按照原来命令执行既可）。

**Comment by liangruofei** [comment]
感谢，收到


在2021年3月10日 10:49，cnn<notifications@github.com> 写道：

感谢反馈。请参考这里文档：https://paddle-inference.readthedocs.io/en/latest/optimize/paddle_trt.html。
将use_static设置为True，类型：bool, 默认值为False。如果指定为True，在初次运行程序的时候会将TRT的优化信息进行序列化到磁盘上（model_dir里面的文件中），下次运行时直接加载优化的序列化信息而不需要重新生成（按照原来命令执行既可）。
