### ISSUE TITLE
我用paddledetection训练自己的数据集（coco格式），训练完之后检测出来的类别不是我的标签里，比如我的类别是:glass,book,检测出来却是car，bicycle是怎么回事呢

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2321]

**Comment by jerrywgz** [comment]
如果是自己的数据集，在test阶段，需要设置dataset下的use_default_label为false，同时anno_file是你预测实际使用的label对应的anno file, paddledetection会从anno_file中读取category并显示出来；如果anno_file不对，将会默认使用coco2017数据集对应的category

**Comment by guotongjian** [comment]
> 如果是自己的数据集，在test阶段，需要设置dataset下的use_default_label为false，同时anno_file是你预测实际使用的label对应的anno file, paddledetection会从anno_file中读取category并显示出来；如果anno_file不对，将会默认使用coco2017数据集对应的category
感谢！
