### ISSUE TITLE
inference结果不一致

### ISSUE THREAD

**Issue by yangsuhui** [PaddlePaddle/PaddleDetection#2323]
你好，我用mask-rcnn-r50-vd-fpn-2x.yml配置文件训练了一个mask-rcnn模型，并用tools/infer.py进行推理得到结果1
同时利用export将该模型导出并用deploy/python/infer.py推理得到结果2；
1和2的结果有很大差异(2相对1的结果有很多漏检)，请问是什么情况？
我用的是0.4分支的代码，代码我没有任何修改。
谢谢！！！

**Comment by jerrywgz** [comment]
能否提供下测试图片和模型呢？tools/infer.py和deploy/python/infer.py的结果基于coco数据集的模型效果是能对齐的

**Comment by yangsuhui** [comment]
@jerrywgz 我这边是不太方便提供图片和模型，我模型训练的时候主要只是修改了mask-rcnn-r50-vd-fpn-2x.yml的max_size和target_size，去掉了vd，其他超参数没什么改变，这个会影响吗？我看我转换后的模型的infer_cfg.yml中use_python_inference为false，应该是false还是true？

**Comment by jerrywgz** [comment]
训练过程的修改对tools/infer和deploy/python/infer的结果一致性不会有影响，use_python_inference只是影响deploy下的预测方式，对精度也不会有影响。可以确认下导出模型的配置和tools/infer使用的testreader配置是否一致。
