### ISSUE TITLE
推理测试的问题，求大佬解答

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2324]
一边train一边eval的时候，inference time是72FPS；训练完之后，单独用命令eval的时候inference time是47FPS，请问哪个FPS是准确的呢。PS：前面的72FPS是训练的时候的最后一个eval，用的是final_model；后面47FPS，用的是best_model，请问这个跟我用的模型参数有关吗，还是说有其他原因呢？感谢回答！

**Comment by yghstill** [comment]
理论上不应该有差别，可能和物理环境有关，在train完马上eval的时候，GPU等资源不释放没有IO等待，会快一点。可在单独eval的时候加上warm up预热，更加合理。
或者直接使用deploy/python/infer的banchmark模式，有预热，评估FPS更加合理。https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/python

**Comment by guotongjian** [comment]
感谢回答！
