### ISSUE TITLE
预训练模型not found 如何迁移训练？coco预训练模型都是tar格式，但是要pdparams格式如何迁移训练？

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#2325]
not found预训练权重参数的训练是从最基准的ResNet101_pretrained.tar开始训练还是什么？

2.0最新版本dete paddle版本1.8.4  低版本还是这样 跪求个解决方式 
群里也咨询了  一直没有得到帮助  哭了

**Comment by yghstill** [comment]
@shuxsu 已经解决了吗？
