### ISSUE TITLE
对x2coco.py的疑问

### ISSUE THREAD

**Issue by duohappy** [PaddlePaddle/PaddleDetection#2326]
针对 [x2coco.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/tools/x2coco.py)，我有几点疑问

+ [L230](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/tools/x2coco.py#L230)
``` python
xmin = float(bndbox.findtext('xmin')) - 1
ymin = float(bndbox.findtext('ymin')) - 1
```
为什么要 `-1`？
如果 voc文件中`xmin = 0` `ymin=0`，那么经过如上代码后，`xmin=-1` `ymin=-1`就没有意义了

+ [L263](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/tools/x2coco.py#L263)

```python
for a_path in tqdm(annotation_paths):
	# Read annotation xml
	ann_tree = ET.parse(a_path)
	ann_root = ann_tree.getroot()

	img_info = voc_get_image_info(ann_root, im_id)
	im_id += 1
	img_id = img_info['id']
	output_json_dict['images'].append(img_info)

	for obj in ann_root.findall('object'):
		ann = voc_get_coco_annotation(obj=obj, label2id=label2id)
		ann.update({'image_id': img_id, 'id': bnd_id})
		output_json_dict['annotations'].append(ann)
		bnd_id = bnd_id + 1
```

新建的`img_id`变量是多余的，可以把`im_id=1`放在循环的最后
```python
for a_path in tqdm(annotation_paths):
	# Read annotation xml
	ann_tree = ET.parse(a_path)
	ann_root = ann_tree.getroot()

	img_info = voc_get_image_info(ann_root, im_id)
	output_json_dict['images'].append(img_info)

	for obj in ann_root.findall('object'):
		ann = voc_get_coco_annotation(obj=obj, label2id=label2id)
		ann.update({'image_id': im_id, 'id': bnd_id})   # 直接用im_id
		output_json_dict['annotations'].append(ann)
		bnd_id = bnd_id + 1
		
	im_id += 1  # 放到最后
```

**Comment by yghstill** [comment]
@duohappy 感谢反馈，（1）中-1是参考开源主流voc转coco的解决方案，针对`xmin=0`和`ymin=0`这种情况确实考虑不周，实际应不-1。 （2）中的im_id代码逻辑确实有问题。我将根据您的建议，在下个PR中修复这两个问题。

**Comment by duohappy** [comment]
> 
> 
> @duohappy 感谢反馈，（1）中-1是参考开源主流voc转coco的解决方案，针对`xmin=0`和`ymin=0`这种情况确实考虑不周，实际应不-1。 （2）中的im_id代码逻辑确实有问题。我将根据您的建议，在下个PR中修复这两个问题。

我本来想提PR，但是想了想，还是先开个issue。那PR有你们提吧，:smile: :+1:
（代码尽量还是要内部review一下)
