### ISSUE TITLE
在显存有限的情况下如何更好的增大batch，提高泛化性

### ISSUE THREAD

**Issue by liangruofei** [PaddlePaddle/PaddleDetection#2335]
我见yolov5中有这么一个操作，用来在有限的gpu显存的情况下，增大batch，提高模型泛化性，

`# Optimizer
    nbs = 64  # nominal batch size
    accumulate = max(round(nbs / total_batch_size), 1)  # accumulate loss before optimizing
    hyp['weight_decay'] *= total_batch_size * accumulate / nbs  # scale weight_decay
    logger.info(f"Scaled weight_decay = {hyp['weight_decay']}")`

不知道，paddle这边有什么处理有类似的效果，或者有啥更好的处理方式吗

**Comment by liuhuiCNN** [comment]
感谢反馈，目前PaddleDetection中还不支持。
