### ISSUE TITLE
关于在jetson xavier nx上运行官方测试用例时的问题

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#2340]
![image](https://user-images.githubusercontent.com/32217129/110950746-30569d00-837f-11eb-8611-759402c2023e.png)
问题 截图如上：
运行的命令是：
python tools/infer.py -c configs/ppyolo/ppyolo.yml -o use_gpu=true weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams --infer_img=demo/000000014439.jpg
机器： jetson xavier nx
前面的测试都通过了，唯独这个，然后换配置文件，测试其他模型也是这个问题。

**Comment by dengxinlong** [comment]
会不会是我安装的CUDA版本太高了，
CUDA：10.2.89
python：3.6

**Comment by liuhuiCNN** [comment]
> 会不会是我安装的CUDA版本太高了，
> CUDA：10.2.89
> python：3.6

您是通过哪种方式安装的CUDA呢？请确认下安装的CUDA版本与nv jetson系统版本保持一致。

**Comment by dengxinlong** [comment]
我的cuda是英伟达官方镜像中自带的cuda。

**Comment by dengxinlong** [comment]
我想问一下，关于Jetson xavier NX的镜像，你们推荐的jetpack版本是4.4吗，还是最新的4.5

**Comment by dengxinlong** [comment]
因为我这个是官方自带的镜像，所以很多细节也不太清楚，想问的就是关于这个问题，你们那边有没有遇到过。
我查了一下，初步估计是算力不匹配的原因。

**Comment by liuhuiCNN** [comment]
> 因为我这个是官方自带的镜像，所以很多细节也不太清楚，想问的就是关于这个问题，你们那边有没有遇到过。
> 我查了一下，初步估计是算力不匹配的原因。

（1）官方自带的镜像的cuda版本，必须要跟使用的预测库版本保持一致。比如Jetson xavier NX上的CUDA=10.1，那么预测库版本的CUDA也必须是10.1。
（2）预测库：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html#linux

**Comment by dengxinlong** [comment]
官方自带的cuda就是 10.2的

**Comment by dengxinlong** [comment]
> > 因为我这个是官方自带的镜像，所以很多细节也不太清楚，想问的就是关于这个问题，你们那边有没有遇到过。
> > 我查了一下，初步估计是算力不匹配的原因。
> 
> （1）官方自带的镜像的cuda版本，必须要跟使用的预测库版本保持一致。比如Jetson xavier NX上的CUDA=10.1，那么预测库版本的CUDA也必须是10.1。
> （2）预测库：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html#linux

按照您的说法，我要在jetson nx上使用你们官方的示例教程，还需要安装 预测库是吗
