### ISSUE TITLE
PaddleDetection与Paddlepaddle的版本及GPU使用问题

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleDetection#2341]
OS： CentOS7.6
Paddlepaddle: 1.8.4
PaddleDetection: release0.4

在使用deploy/python/infer.py时出现如下错误：

> E0313 10:41:03.680306 19224 analysis_config.cc:73] Please compile with gpu to EnableGpu()
> Traceback (most recent call last):
>   File "/home/xxx/users/xxx/xxx/xxx/model_serving.py", line 135, in <module>
>     run_mode=project_config['model_run_mode'])
>   File "/home/xxx/users/xxx/xxx/xxx/model_serving.py", line 51, in __init__
>     super().__init__(model_dir, use_gpu=use_gpu, run_mode=run_mode)
>   File "/home/aas/users/xxx/xxx/xxx/ppdet_infer.py", line 612, in __init__
>     use_gpu=use_gpu)
>   File "/home/xxx/users/xxx/xxx/xxx/ppdet_infer.py", line 557, in load_predictor
>     predictor = fluid.core.create_paddle_predictor(config)
> paddle.fluid.core_avx.EnforceNotMet: 
> 
> --------------------------------------------
> C++ Call Stacks (More useful to developers):
> --------------------------------------------
> 0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
> 1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
> 2   paddle::AnalysisPredictor::LoadProgramDesc()
> 3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
> 4   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
> 5   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
> 6   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)
> 
> ----------------------
> Error Message Summary:
> ----------------------
> Error: Cannot open file inference_model/yolov3/__model__ at (/paddle/paddle/fluid/inference/api/analysis_predictor.cc:706)

其中run_mode为fluid，use_gpu为True，通过paddle.fluid.install_check.run_check()测试安装的GPU版本是可以使用的。

请问这个会是什么原因导致的呢？

**Comment by wangxinxin08** [comment]
可以贴一下运行的命令，看起来是没有正确的指定model_dir的路径

**Comment by nihuizhidao** [comment]
的确是，建议deploy/python/infer.py里用到model_dir的地方都先join `os.path.dirname(__file__)`，改成绝对路径
