### ISSUE TITLE
jetson nano 部署 路标检测 模型 ：GPU显示没有目标，CPU则正确显示目标。

### ISSUE THREAD

**Issue by GZHUZhao** [PaddlePaddle/PaddleDetection#2348]
paddlepaddle - gpu 版本2.0.0
PaddleDetection版本release 2.0 rc
硬件：jetson nano jetpack4.3
场景：
1、使用tools/train.py 对 路标检测模型（yolov3_mobilenet_v1_roadsign.yml）进行训练，得到best_model。
2、使用tools/export_model.py进行导出模型。
python tools/export_model.py -c configs/yolov3_mobilenet_v1_roadsign.yml  \
--output_dir=./export_model \
-o weights=./output/yolov3_mobilenet_v1_roadsign/best_model TestReader,input_def.image_shape=[3,320,320]
3、使用deploy/python/infer.py在jetson nano下进行部署。
（1）使用gpu预测：
![gpu](https://user-images.githubusercontent.com/78419361/111073366-5fa11180-8519-11eb-915f-9061bbed18ef.png)
(2)使用cpu预测正常显示。
![cpu](https://user-images.githubusercontent.com/78419361/111073782-0b972c80-851b-11eb-8511-b741bd676ce7.png)

麻烦跟进一下，后续需要提供什么信息请告知我就行，谢谢！

**Comment by qingqing01** [comment]
@GZHUZhao 

我在Linux V100上测试了下，是可以的。
```
-----------  Running Arguments -----------
camera_id: -1
image_file: road52.png
model_dir: export_model/yolov3_mobilenet_v1_roadsign/
output_dir: output
run_benchmark: False
run_mode: fluid
threshold: 0.5
use_gpu: 1
video_file:
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Use Paddle Executor: False
Transform Order:
--transform op: Resize
--transform op: Normalize
--transform op: Permute
--------------------------------------------
W0315 03:15:42.721149 62707 analysis_predictor.cc:1059] Deprecated. Please use CreatePredictor instead.
Inference: 9.780168533325195 ms per batch image
class_id:3, confidence:0.8269,left_top:[33.29,142.56], right_bottom:[258.45,380.97]
save result to: output/road52.png

```

您这个问题，是roadsign的原始数据的话，可以给一个模型，我们进一步查下问题。

**Comment by GZHUZhao** [comment]
@qingqing01 
链接：https://pan.baidu.com/s/18vnPHQ2KJO7Q4zg-r_Nv6g 
提取码：x256 
您好，用的是原始数据，模型是由tools/train.py生成的best_model，且由export_model.py导出的。
使用环境;
paddlepaddle-gpu 2.0（whl用的官网提供的nv_jetson_cp36_all）
系统：ubuntu 18.04
谢谢您！

**Comment by GZHUZhao** [comment]
@qingqing01 
cpu检测出来的class_id也是错的
![road52](https://user-images.githubusercontent.com/78419361/111105549-3373a800-858e-11eb-9379-f7eb7110a10b.png)

**Comment by qingqing01** [comment]
@GZHUZhao 我用的你模型在Linux GPU/CPU上测试有输出，Jetson NANO的问题，可能需要排查下，是否软件包问题，您开启了TensorRT，还是没有没有？

```
-----------  Running Arguments -----------
camera_id: -1
image_file: road52.png
model_dir: tmp/yolov3_mobilenet_v1_roadsign
output_dir: output
run_benchmark: False
run_mode: fluid
threshold: 0.5
use_gpu: 1
video_file:
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Use Paddle Executor: True
Transform Order:
--transform op: Resize
--transform op: Normalize
--transform op: Permute
--------------------------------------------
W0315 05:32:30.124871 63810 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0315 05:32:30.142894 63810 device_context.cc:372] device: 0, cuDNN Version: 7.6.
Inference: 30.387401580810547 ms per batch image
class_id:0, confidence:0.5586,left_top:[40.02,201.51], right_bottom:[252.06,327.50]
save result to: output/road52.png
```

不知道您是否训练充分，可以使用下面，我训练的模型试下，下面模型，我在Linux V100上测试正确:

链接: https://pan.baidu.com/s/15F_HrxXU_CwYLvVtmSLH8A  密码: dc1i

**Comment by liuhuiCNN** [comment]
（1）cpu classid 问题如qingqing01回复，请确认训练是否正常；
（2）jetson nano python预测时，请检查使用的python paddle包是否跟硬件平台一致。 您可以从这里下载预先编译好的nano 上paddle安装包：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html。您也可以自行编译paddle安装包。
（3）您也可以通过cpp预测看下是否正常。

**Comment by GZHUZhao** [comment]
> @GZHUZhao 我用的你模型在Linux GPU/CPU上测试有输出，Jetson NANO的问题，可能需要排查下，是否软件包问题，您开启了TensorRT，还是没有没有？
> 
> ```
> -----------  Running Arguments -----------
> camera_id: -1
> image_file: road52.png
> model_dir: tmp/yolov3_mobilenet_v1_roadsign
> output_dir: output
> run_benchmark: False
> run_mode: fluid
> threshold: 0.5
> use_gpu: 1
> video_file:
> ------------------------------------------
> -----------  Model Configuration -----------
> Model Arch: YOLO
> Use Paddle Executor: True
> Transform Order:
> --transform op: Resize
> --transform op: Normalize
> --transform op: Permute
> --------------------------------------------
> W0315 05:32:30.124871 63810 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
> W0315 05:32:30.142894 63810 device_context.cc:372] device: 0, cuDNN Version: 7.6.
> Inference: 30.387401580810547 ms per batch image
> class_id:0, confidence:0.5586,left_top:[40.02,201.51], right_bottom:[252.06,327.50]
> save result to: output/road52.png
> ```
> 
> 不知道您是否训练充分，可以使用下面，我训练的模型试下，下面模型，我在Linux V100上测试正确:
> 
> 链接: https://pan.baidu.com/s/15F_HrxXU_CwYLvVtmSLH8A 密码: dc1i

谢谢您！
（1）您的模型在我的win10电脑上 gpu能用，结果和您的一样，但是在jetson nano 上gpu仍然是没有检测到目标。
（2）检测时，run_mode是默认的fluid，我的jetson 上有tensorRT，但是whl是官网的，应该是没有开启tensorRT的。
（3）我训练的模型在win10-gpu上也是有结果的，但是class_id不对，模型是基于预训练参数的基础上进行的，按照模型配置文件，训练3600个迭代结束。如下图：
![模型](https://user-images.githubusercontent.com/78419361/111111956-412f2a80-859a-11eb-9958-c8c85bb09213.png)

**Comment by GZHUZhao** [comment]
> （1）cpu classid 问题如qingqing01回复，请确认训练是否正常；
> （2）jetson nano python预测时，请检查使用的python paddle包是否跟硬件平台一致。 您可以从这里下载预先编译好的nano 上paddle安装包：[https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html。您也可以自行编译paddle安装包。](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html%E3%80%82%E6%82%A8%E4%B9%9F%E5%8F%AF%E4%BB%A5%E8%87%AA%E8%A1%8C%E7%BC%96%E8%AF%91paddle%E5%AE%89%E8%A3%85%E5%8C%85%E3%80%82)
> （3）您也可以通过cpp预测看下是否正常。

谢谢您！
（1）安装的whl是官网的whl安装包：如下图
![whl](https://user-images.githubusercontent.com/78419361/111112412-15607480-859b-11eb-91cf-c7d051a7f822.png)
（2）我的jetson nano的python版本为3.6.9，jetpack4.3，应该和官网下载的是一致的。如下图：
![python](https://user-images.githubusercontent.com/78419361/111112585-59ec1000-859b-11eb-979d-814846325611.png)
![jetpack](https://user-images.githubusercontent.com/78419361/111112703-9586da00-859b-11eb-9055-5eec60748e74.png)
(3)关于源码编译：
我尝试过多次进行源码编译，但是由于可能是网络等原因编译不了。

**Comment by wangye707** [comment]
@GZHUZhao 你好，目前Jetson上的tx2和nano设备在开启GPU后会出现程序直接终止且不报错的情况，经过我们测试，agx xavier, nx设备下，该模型可以正常预测。如果您有其他jetson设备，可以暂时先用其他的设备，我们会尽快定位修复这个问题。这是参考回答：https://github.com/PaddlePaddle/Paddle/issues/31687。yolov3在其他设备上的推理请参考：https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/python/yolov3

**Comment by DragonGongY** [comment]
Jetson Nano上使用cpu能够正常运行，并给出目标框，但是gpu的话就没有框，这是为何？

**Comment by wangye707** [comment]
@DragonGongY  nano和tx2目前存在开启gpu后预测结果错误导致目标框无法标注的情况，所以看起来是没有框

**Comment by DragonGongY** [comment]
但是cpu预测又有结果输出，都是用的同一个模型

**Comment by DragonGongY** [comment]
> @DragonGongY nano和tx2目前存在开启gpu后预测结果错误导致目标框无法标注的情况，所以看起来是没有框

用源码编译paddle的推理库，是否能解决这个问题？

**Comment by wangye707** [comment]
@DragonGongY 目前这个bug还没有修复，源码编译也暂时不行，您可以更换为nx和agx这两款jetson设备，我们尽快修复这个bug。

**Comment by GZHUZhao** [comment]
> @DragonGongY 目前这个bug还没有修复，源码编译也暂时不行，您可以更换为nx和agx这两款jetson设备，我们尽快修复这个bug。

ssd_mobilenet_v1_voc的GPU和CPU都可以，就是这个yolo框架的不行。

**Comment by GZHUZhao** [comment]
> 我们测试，agx xavier, nx设备下，该模型可以正常预测。如果您有其他jetson设备，可以暂时先用其他的设备，我们会尽快定位修复这个问题。这是参考回答：[https://github.com/PaddlePaddle/Paddle/issues/31687。yolov3在其他设备上的推理请参考：](https://github.com/PaddlePaddle/Paddle/issues/31687%E3%80%82yolov3%E5%9C%A8%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E4%B8%8A%E7%9A%84%E6%8E%A8%E7%90%86%E8%AF%B7%E5%8F%82%E8%80%83%EF%BC%9Ahttps://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/python/yolov3)

好的，我这边暂时只有nano一个设备，bug修复后麻烦给一下链接，谢谢您！

**Comment by DragonGongY** [comment]
> > 我们测试，agx xavier, nx设备下，该模型可以正常预测。如果您有其他jetson设备，可以暂时先用其他的设备，我们会尽快定位修复这个问题。这是参考回答：[https://github.com/PaddlePaddle/Paddle/issues/31687。yolov3在其他设备上的推理请参考：](https://github.com/PaddlePaddle/Paddle/issues/31687%E3%80%82yolov3%E5%9C%A8%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E4%B8%8A%E7%9A%84%E6%8E%A8%E7%90%86%E8%AF%B7%E5%8F%82%E8%80%83%EF%BC%9Ahttps://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/python/yolov3)
> 
> 好的，我这边暂时只有nano一个设备，bug修复后麻烦给一下链接，谢谢您！

https://zhuanlan.zhihu.com/p/319371293这个是知乎上的一个教程，也是paddledetection推荐的部署方案，用的是tensorrt的部署方案，这个是否有验证过，是否可行？

**Comment by DragonGongY** [comment]
> > 我们测试，agx xavier, nx设备下，该模型可以正常预测。如果您有其他jetson设备，可以暂时先用其他的设备，我们会尽快定位修复这个问题。这是参考回答：[https://github.com/PaddlePaddle/Paddle/issues/31687。yolov3在其他设备上的推理请参考：](https://github.com/PaddlePaddle/Paddle/issues/31687%E3%80%82yolov3%E5%9C%A8%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E4%B8%8A%E7%9A%84%E6%8E%A8%E7%90%86%E8%AF%B7%E5%8F%82%E8%80%83%EF%BC%9Ahttps://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/python/yolov3)
> 
> 好的，我这边暂时只有nano一个设备，bug修复后麻烦给一下链接，谢谢您！

https://zhuanlan.zhihu.com/p/319371293这个是知乎上的一个教程，也是paddledetection推荐的部署方案，用的是tensorrt的部署方案，这个是否有验证过，是否可行？

**Comment by gsdust** [comment]
> > > 我们测试，agx xavier, nx设备下，该模型可以正常预测。如果您有其他jetson设备，可以暂时先用其他的设备，我们会尽快定位修复这个问题。这是参考回答：[https://github.com/PaddlePaddle/Paddle/issues/31687。yolov3在其他设备上的推理请参考：](https://github.com/PaddlePaddle/Paddle/issues/31687%E3%80%82yolov3%E5%9C%A8%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E4%B8%8A%E7%9A%84%E6%8E%A8%E7%90%86%E8%AF%B7%E5%8F%82%E8%80%83%EF%BC%9Ahttps://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/python/yolov3)
> > 
> > 
> > 好的，我这边暂时只有nano一个设备，bug修复后麻烦给一下链接，谢谢您！
> 
> [https://zhuanlan.zhihu.com/p/319371293这个是知乎上的一个教程，也是paddledetection推荐的部署方案，用的是tensorrt的部署方案，这个是否有验证过，是否可行？](https://zhuanlan.zhihu.com/p/319371293%E8%BF%99%E4%B8%AA%E6%98%AF%E7%9F%A5%E4%B9%8E%E4%B8%8A%E7%9A%84%E4%B8%80%E4%B8%AA%E6%95%99%E7%A8%8B%EF%BC%8C%E4%B9%9F%E6%98%AFpaddledetection%E6%8E%A8%E8%8D%90%E7%9A%84%E9%83%A8%E7%BD%B2%E6%96%B9%E6%A1%88%EF%BC%8C%E7%94%A8%E7%9A%84%E6%98%AFtensorrt%E7%9A%84%E9%83%A8%E7%BD%B2%E6%96%B9%E6%A1%88%EF%BC%8C%E8%BF%99%E4%B8%AA%E6%98%AF%E5%90%A6%E6%9C%89%E9%AA%8C%E8%AF%81%E8%BF%87%EF%BC%8C%E6%98%AF%E5%90%A6%E5%8F%AF%E8%A1%8C%EF%BC%9F)

我也按这个尝试了，目前还是不可以的。。。我也是放进去推出来为0

**Comment by lleesg** [comment]
> @DragonGongY 目前这个bug还没有修复，源码编译也暂时不行，您可以更换为nx和agx这两款jetson设备，我们尽快修复这个bug。

请问该bug修复了么？

**Comment by DragonGongY** [comment]
Nano上一直都有这个问题，建议使用pytorch->onnx，再转到tensorrt部署

**Comment by lleesg** [comment]
> Nano上一直都有这个问题，建议使用pytorch->onnx，再转到tensorrt部署

TX2上也一样，paddledetection更新到2.0问题依旧

**Comment by wwqgtxx** [comment]
在 https://github.com/PaddlePaddle/Paddle/pull/33442 这个提交后，Nano和TX2的检测应该是正常了

**Comment by wwqgtxx** [comment]
在 https://github.com/PaddlePaddle/Paddle/pull/33442 这个提交后，Nano和TX2的检测应该是正常了

**Comment by wangye707** [comment]
@LLeeSG @gsdust @GZHUZhao @DragonGongY 你好，这问题之前在v2.1.0版本已经修复了，现在最新已经到了v2.1.2版本。下载链接：https://paddle-inference-lib.bj.bcebos.com/2.1.2/nv-jetson-jetpack4.4-all/paddlepaddle_gpu-2.1.2-cp36-cp36m-linux_aarch64.whl
