### ISSUE TITLE
敏感度分析打印出来的参数名字是什么意思

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2353]
像这些
```
conv1_1_weights,conv1_2_weights,conv1_3_weights,
res2a_branch2a_weights,res2a_branch2b_weights,res2a_branch2c_weights
yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights
yolo_block.1.tip.conv.weights,yolo_output.1.conv.weights,yolo_transition.1.conv.weights
```
是什么意思呢，可否请大佬解答一下

**Comment by heavengate** [comment]
网络里面各层权重的名字，后面基于这些权重名进行敏感度分析和卷积通道剪裁

**Comment by guotongjian** [comment]
> 网络里面各层权重的名字，后面基于这些权重名进行敏感度分析和卷积通道剪裁

我想问下就是这些参数具体的对应到网络的哪个层该怎么看呢，后面那些1_1、2a、2b、tip、transition跟网络结构是怎么对应的

**Comment by heavengate** [comment]
```
conv1_1_weights,conv1_2_weights,conv1_3_weights,
res2a_branch2a_weights,res2a_branch2b_weights,res2a_branch2c_weights
```
这些是backbone部分的权重，对应关系可以参考
https://github.com/PaddlePaddle/PaddleDetection/blob/b1e2a8a5edec4817443cd792f9c6ab990167f123/ppdet/modeling/backbones/resnet.py#L349

```
yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights
yolo_block.1.tip.conv.weights,yolo_output.1.conv.weights,yolo_transition.1.conv.weights
```
这些是yolo head部分的权重，权重名和网络层对应关系可以参考
https://github.com/PaddlePaddle/PaddleDetection/blob/b1e2a8a5edec4817443cd792f9c6ab990167f123/ppdet/modeling/anchor_heads/yolo_head.py#L222

**Comment by guotongjian** [comment]
> ```
> conv1_1_weights,conv1_2_weights,conv1_3_weights,
> res2a_branch2a_weights,res2a_branch2b_weights,res2a_branch2c_weights
> ```
> 
> 这些是backbone部分的权重，对应关系可以参考
> https://github.com/PaddlePaddle/PaddleDetection/blob/b1e2a8a5edec4817443cd792f9c6ab990167f123/ppdet/modeling/backbones/resnet.py#L349
> 
> ```
> yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights
> yolo_block.1.tip.conv.weights,yolo_output.1.conv.weights,yolo_transition.1.conv.weights
> ```
> 
> 这些是yolo head部分的权重，权重名和网络层对应关系可以参考
> https://github.com/PaddlePaddle/PaddleDetection/blob/b1e2a8a5edec4817443cd792f9c6ab990167f123/ppdet/modeling/anchor_heads/yolo_head.py#L222

好的，谢谢
