### ISSUE TITLE
混贴票据切分

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleDetection#2360]
大佬，我需要做混贴票据切分，里面的票据是有正面的，也有倾斜的，请问是目标检测、分割、关键点检测这三种方式的效果比较好，需要知道切分后的各类票据具体位置和倾斜角度？

**Comment by jerrywgz** [comment]
目前PaddleDetection中可以使用分割的方式来完成这个任务，可以尝试使用solov2模型；我们在3月底会开源斜框检测模型，会更符合你的使用需求
