### ISSUE TITLE
用yolov4训练coco2017数据集，evel时内存溢出，用的是aistudio

### ISSUE THREAD

**Issue by red-hai** [PaddlePaddle/PaddleDetection#2363]
下面是TrainReader的相关配置
  batch_size: 8
  shuffle: true
  drop_last: true
  worker_num: 8
  bufsize: 16
  use_process: true
  drop_empty: false
可以正常训练没有问题

下面是EvelReader的改后的相关配置
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !PadBox
      num_max_boxes: 50
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
  drop_empty: false
  worker_num: 4
  bufsize: 4

单eval时，执行到下面的情形，过会就会提示内存溢出
......
2021-03-16 22:21:13,372 - INFO - Test iter 4900
[INFO 2021-03-16 22:21:13,372 eval_utils.py:189] Test iter 4900
2021-03-16 22:21:22,485 - INFO - Test finish iter 4952
[INFO 2021-03-16 22:21:22,485 eval_utils.py:196] Test finish iter 4952
2021-03-16 22:21:22,486 - INFO - Total number of images: 4952, inference time: 5.993771227630872 fps.
[INFO 2021-03-16 22:21:22,486 eval_utils.py:202] Total number of images: 4952, inference time: 5.993771227630872 fps.
loading annotations into memory...
Done (t=0.74s)
creating index...
index created!

然后网页就会提示
代码执行异常：内存溢出，执行已被中止。请检查相关代码。

**Comment by yghstill** [comment]
@red-hai 看log模型已经评估完了，是由于coco API对结果进行后处理输出mAP时内存溢出，你看是否有`bbox.json`文件生成，如果有，指定`--json_eval`对结果直接进行评估。或者将eval过程迁移到本地开发机进行，AIStudio上虚拟机的内存很小。
