### ISSUE TITLE
负样本标注疑问

### ISSUE THREAD

**Issue by duohappy** [PaddlePaddle/PaddleDetection#2368]
建立训练数据集时，分为含有目标的图片和完全不含有目标的图片，完全不含有目标的图片也非常的关键。

完全不含有目标的图片标注文件（voc格式），应该是怎样的呢？是不是只需要`<filename>`和`<size>`就可以了？

``` xml
<annotation>
	<filename>000127.jpg</filename>
	<size>
		<width>500</width>
		<height>375</height>
		<depth>3</depth>
	</size>
</annotation>
```

darknet框架中，对于完全不含有目标的图片，只需要建议一个空的txt文件就可以

**Comment by yghstill** [comment]
@duohappy 确实不含有目标的图片是非常的关键，在实际应用场景中有训练的必要性。目前PaddleDetection尚不支持无标注训练，如果遇到为空的标注文件就会直接跳过，实现无标注训练这个功能我们正在排期支持中，欢迎关注。

**Comment by duohappy** [comment]
> 
> 
> @duohappy 确实不含有目标的图片是非常的关键，在实际应用场景中有训练的必要性。目前PaddleDetection尚不支持无标注训练，如果遇到为空的标注文件就会直接跳过，实现无标注训练这个功能我们正在排期支持中，欢迎关注。

好的，这个是基础功能，感谢完善，:+1:
