### ISSUE TITLE
训练precision、recall

### ISSUE THREAD

**Issue by zxz-cc** [PaddlePaddle/PaddleDetection#2369]
请问训练结束怎么看看precision和recall??目前PaddleDetection有加这两个功能吗？？

**Comment by yghstill** [comment]
@zxz-cc 已经在develop下动态图模型中支持了的https://github.com/PaddlePaddle/PaddleDetection/pull/2346 ，只需要在eval的时候加上`--classwise`就会输出每类的AP和PR curve。
如果想要打印具体precision和recall的值，需要在https://github.com/PaddlePaddle/PaddleDetection/blob/develop/dygraph/ppdet/metrics/map_utils.py#L34  里打印即可。
