### ISSUE TITLE
faster 系列训练 loss一直为nan

### ISSUE THREAD

**Issue by zxz-cc** [PaddlePaddle/PaddleDetection#2370]
同一批训练数据，其他模型训练是正常的，但用faster系列训练的时候，模型从一开始就梯度爆炸，loss为nan，将batch_size和lr调小、调大都没用？是什么原因呢？？

**Comment by yghstill** [comment]
@zxz-cc 可能还是前期训练不稳定导致的，是在多少轮loss出现nan的，几卡训练，batch_size和lr分别设置的是多少？可以按照[FAQ](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/docs/FAQ.md)文档第一条，根据GPU卡数变化、batch size变化配置合适的学习率。

**Comment by zxz-cc** [comment]
一个GPU，在第一轮就出现了，batch_size从1增大16,lr从0.01减小到0.00001




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 晚上6:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] faster 系列训练 loss一直为nan (#2370)





 
@zxz-cc 是在多少轮loss出现nan的，几卡训练，batch_size和lr分别设置的是多少？

**Comment by zxz-cc** [comment]
之前已经按照文档所说配置batch_size和lr，都没用@yghstill

**Comment by liuhuiCNN** [comment]
建议检查一下数据，看看是不是数据问题。
（1）用官方配置文件，根据硬件修改 batch_size 和 lr，+ 官方数据；
（2）用官方配置文件，根据硬件修改 batch_size 和 lr，+ 自定义数据。
做一下对比试验，跑几轮比较一下看看。
