### ISSUE TITLE
关于检测时输出各个类别的precision和recall的问题

### ISSUE THREAD

**Issue by daiyuanm** [PaddlePaddle/PaddleDetection#2371]
你好，看到之前的问题#2204，里面提到会在动态图中集成，想请问下现在动态图开始试用了，这个功能什么时候能上线呢？之前有过 参考静态图的 #1779 ，但是现在用的paddledetection和这个PR版本里的代码变化了很多。希望能够尽快集成这个功能，谢谢！

**Comment by yghstill** [comment]
@daiyuanm 感谢关注，目前已经在https://github.com/PaddlePaddle/PaddleDetection/pull/2346 中支持这个功能了，更新最新develop下代码就可在动态图模型里体验了，在eval的时候设置`--classwise`即可。
