### ISSUE TITLE
使用YOLOv3_mobilenetv3_large 来进行验证，验证集：coco val2017，平台为：jetson xavier nx

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#2373]
![image](https://user-images.githubusercontent.com/32217129/111568551-ed138880-87db-11eb-8796-06411e01f910.png)
问题如上截图。测试的模型为：yolov3_mobilenet_v3_large, 测试其他的移动端模型是没有问题。估计可能是开的资源太多了，如何调整？

环境：jetson xavier nx
镜像：jetpack 4.5.1 
cuda: 10.2
cudnn: 8

**Comment by liuhuiCNN** [comment]
建议您将初始显存设置大点试试： enable_use_gpu(显存容量，device_ID)，参考文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/python_infer_cn.html#zhichifangfaliebiao

**Comment by dengxinlong** [comment]
> 建议您将初始显存设置大点试试： enable_use_gpu(显存容量，device_ID)，参考文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/python_infer_cn.html#zhichifangfaliebiao

您能稍微详细描述一下吗，就是具体在哪个文件里面修改？

**Comment by dengxinlong** [comment]
![image](https://user-images.githubusercontent.com/32217129/111644024-6641c880-883a-11eb-8f75-38ea2252c20b.png)
我 修改了 enable_use_gpu（我找到的文件是PaddleDetection/application/christmas/blazeface/data_feed.py文件，应该是这个），该显存为4096，但是内存的使用量就是上面的截图，非常高，导致内核直接将这个进程杀死。

**Comment by wangye707** [comment]
@dengxinlong 在指令后面加上 EvalReader.batch_size=1
