### ISSUE TITLE
ppyolo_2x训练需要多久？

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/PaddleDetection#2374]
![5R1}{%WJ`L@@V(OWHI{_NLF](https://user-images.githubusercontent.com/57654726/111583444-679dd180-87f7-11eb-81dd-ae194e302808.png)
![A}8VU}A6F0$63BM4P4(HD4O](https://user-images.githubusercontent.com/57654726/111583446-69679500-87f7-11eb-9763-defb29b4de95.png)

我是这么配置的，大约3天，一直保持这个状态，是哪里有啥问题？数据量2000左右，之前使用ppyolo.yml没遇到这个问题

**Comment by liuhuiCNN** [comment]
（1）请问您是用GPU训练吗？您可以通过每个iter的时间乘以总的iter数大概估算训练时间。
（2）如果是2000条数据的话，ppyolo大概训练400epoch，400*2000/batch_size=max_iters

**Comment by xialei2821212670** [comment]
那base_lr需要调整？batch_size为0.001

**Comment by liuhuiCNN** [comment]
> 那base_lr需要调整？batch_size为0.001

batch_size根据您的硬件显存设置，一般从小到大试。 base_lr 请参考文档：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/docs/FAQ.md 进行设置

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题，请reopen这个issue~
