### ISSUE TITLE
动态图模型

### ISSUE THREAD

**Issue by sxlyiyiyi** [PaddlePaddle/PaddleDetection#2390]
静态图的模型什么时候可以全部转到动态图？例如CenterNet等，可以暂时没有预训练模型

**Comment by heavengate** [comment]
您好，目前没有迁移CenterNet的计划，CenterNet的迁移我们再评估一下，现在已经迁移好的有精度速度优于CenterNet的FCOS和TTFNet，您可以试下这两个~
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/dygraph/configs/fcos
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/dygraph/configs/ttfnet
