### ISSUE TITLE
DIou、Ciou那些如何直接在mask rcnn或者其他网络中调用呢

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#2391]

**Comment by heavengate** [comment]
目前iou系列的loss已经验证的是在YOLO，Faster-RCNN， Cascade Faster-RCNN系列的模型中，Mask RCNN还没有验证改过，如果你要尝试在Mask RCNN里加iou loss，可以参考一下下面的配置
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/configs/rcnn_enhance
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/configs/iou_loss
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/configs/ppyolo
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/configs/yolov4

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题，请reopen这个issue
