### ISSUE TITLE
如何提高识别准确度和识别率？

### ISSUE THREAD

**Issue by Viktor-Paul** [PaddlePaddle/PaddleDetection#2408]
各位大佬：
请教一个问题，自己的数据集用数据增广把图片进行了旋转，颜色变换，以及随机裁剪，样本集1000张，训练了31000步，学习率为0.01，采用的是faster-rcnn-r50-fpn-1x网络，请问该如何解决这个问题？是不是因为图片的旋转导致目标函数无法收敛，虽然map值很大，但是预测出来的结果非常的差？

**Comment by yghstill** [comment]
@Viktor-Paul 几卡GPU训练，mAP测试是多少，使用的是val集还是train集评估的？

**Comment by Viktor-Paul** [comment]
> @Viktor-Paul 几卡GPU训练，mAP测试是多少，使用的是val集还是train集评估的？

单卡，map测试89.55，使用的是train集进行评估的

**Comment by yghstill** [comment]
@Viktor-Paul 
- 单卡训练学习率应该调低，如果batch size没变，学习率应该设置为0.1 / 8 = 0.00125，具体变化规则可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/docs/FAQ.md
- train集上评估没有意义，应该在不参与训练的val集上评估，才能确定该模型的泛化性好不好。
- 增加数据增强方法后，尽管收敛速度会变慢，但不影响faster rcnn的正常收敛，先调低学习率后再训一次看下效果如何。

**Comment by Viktor-Paul** [comment]
> @Viktor-Paul
> 
> * 单卡训练学习率应该调低，如果batch size没变，学习率应该设置为0.1 / 8 = 0.00125，具体变化规则可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/docs/FAQ.md
> * train集上评估没有意义，应该在不参与训练的val集上评估，才能确定该模型的泛化性好不好。
> * 增加数据增强方法后，尽管收敛速度会变慢，但不影响faster rcnn的正常收敛，先调低学习率后再训一次看下效果如何。
好的，我再试试，非常感谢您的建议。

**Comment by Viktor-Paul** [comment]
@yghstill 
好的，我再试试，非常感谢您的建议。

**Comment by Viktor-Paul** [comment]
@yghstill 
好的，我再试试，非常感谢您的建议。

**Comment by shuxsu** [comment]
> @Viktor-Paul
> 
> * 单卡训练学习率应该调低，如果batch size没变，学习率应该设置为0.1 / 8 = 0.00125，具体变化规则可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/docs/FAQ.md
> * train集上评估没有意义，应该在不参与训练的val集上评估，才能确定该模型的泛化性好不好。
> * 增加数据增强方法后，尽管收敛速度会变慢，但不影响faster rcnn的正常收敛，先调低学习率后再训一次看下效果如何。

我想咨询下 为什么之前在ai studio上跟着做项目  得到的迁移学习模型val map能达到80 90多 但是自定义的数据集迁移学习 也就40多map  mask rcnn和pp-yolo都是这样

**Comment by Viktor-Paul** [comment]
@shuxsu 我感觉是你自动定义的样本集样本分布和迁移模型采用的样本集差异比较大导致的，可以试试不用迁移学习，直接训练模型，应该效果会好点

**Comment by shuxsu** [comment]
他这个差异主要是怎么体现呢， &nbsp;我用预训练COCO的迁移学习cityscape数据集 效果比基准模型少5-10个点





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 下午3:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 如何提高识别准确度和识别率？ (#2408)





 
@shuxsu 我感觉是你自动定义的样本集样本分布和迁移模型采用的样本集差异比较大导致的，可以试试不用迁移学习，直接训练模型，应该效果会好点

**Comment by Viktor-Paul** [comment]
@yghstill 大佬，经过昨天您的建议，我尝试把学习率调低为0.0001，map值可以达到99，（没有使用预训练模型，单独训练的）但是用验证集进行检验之后，发现：
不同的样本但是预测的结果一样，都是class:id7，同时，预测中会出现多个复选框,这个是什么原因呢？（样本集，测试集图片比较大：长度大概在2000到4500像素,宽度大概和长度一样也在2000-4500像素范围之内）
![image](https://user-images.githubusercontent.com/51936391/112277992-518f8580-8cbd-11eb-8184-e5e8e2139e3b.png)

**Comment by Viktor-Paul** [comment]
> 他这个差异主要是怎么体现呢， &nbsp;我用预训练COCO的迁移学习cityscape数据集 效果比基准模型少5-10个点
@shuxsu 这个不是很懂，感觉城市景观场景类别和coco标注的类别还是有不小的差异的，然后导致迁移学习，模型参数fine-ture不太好容易确定，然后导致map值下降了不少。

**Comment by Viktor-Paul** [comment]
@yghstill  感谢大佬的帮助，找到问题，并解决了，还是自己太粗心了
