### ISSUE TITLE
在eval的时候设置--classwise可以查看每类的recall、precision，请问--classwise设置在哪里？

### ISSUE THREAD

**Issue by LDX17** [PaddlePaddle/PaddleDetection#2416]

**Comment by liuhuiCNN** [comment]
请使用develop分支代码，python tools/eval.py -c xxx --classwise
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/GETTING_STARTED_cn.md

**Comment by LDX17** [comment]
我按您的要求做了，出现如下错误，请问怎么解决？
![image](https://user-images.githubusercontent.com/66930694/112465766-0c904f80-8da0-11eb-8d69-f6dbeec2df1c.png)
