### ISSUE TITLE
关于C#使用GPU进行持续模型预测时内存不断上升的问题

### ISSUE THREAD

**Issue by zhouyuxixixi** [PaddlePaddle/PaddleDetection#2417]
ppdet版本-master，预测库版本2.0.0rc0
出现问题描述如下
1、使用官方的cpp，生成了dll，具体参考的是[c++部署](https://zhuanlan.zhihu.com/p/268657833?utm_source=wechat_session&utm_medium=social&utm_oi=692640605041340416&s_r=0)和[c++生成dll,c#调用](https://zhuanlan.zhihu.com/p/280206376?utm_source=wechat_session&utm_medium=social&utm_oi=692640605041340416&s_r=0)
2、所使用网络为SSD+VGG16，在实际应用过程中发现，当使用定时器，每隔100ms预测一次，每次预测大概耗时15ms
3、载入模型之后，程序内存为560M，第一次预测之后，程序内存为1668M
4、随着预测的不断进行，程序内存也随之不断上升，预测完3千次之后，程序内存达到2500M，且继续上升
5、GC.COLLECT无效果

**Comment by liuhuiCNN** [comment]
如微信语音沟通：
（1）cudnn 8.0.1 有内存泄漏问题，经沟通使用的是7.6.5，排除这个问题；
（2）建议在CPP代码中predict结束后调用：ClearIntermediateTensor 函数 和 TryShrinkMemory函数
（3）排查一下C#是否有内存泄漏问题。

**Comment by zhouyuxixixi** [comment]
已查找到问题，基本确定为，C#调用dll时的内存泄漏问题，基本描述如下
1. 原来

```
[DllImport("main.dll", EntryPoint = "_PredictImage", CharSet = CharSet.Ansi)]
public extern static void _PredictImage(int height, int width, int channels, byte[] srcImage, double threshold, ref int class_id, ref float confidence, ref int rect, ref byte image, out ulong size);
```
调用
```
int[] class_id = new int[100];
float[] confidence = new float[100];
int[] rect = new int[400];

byte[] imageData = new byte[1000 * 1000 * 3];
ulong size = new ulong();
PaddleDetectionClass._PredictImage(bmp.Height, bmp.Width, 3, source, 0.1, ref class_id[0], ref confidence[0], ref rect[0], ref imageData[0], out size);
```
这个时候会出现内存泄漏，主要是这种调用的内存需要手动释放

2. 修改后

调用
```
GCHandle gch_class_id = GCHandle.Alloc(class_id, GCHandleType.Pinned);
GCHandle gch_confidence = GCHandle.Alloc(confidence, GCHandleType.Pinned);
GCHandle gch_rect = GCHandle.Alloc(rect, GCHandleType.Pinned);
GCHandle gch_image = GCHandle.Alloc(imageData, GCHandleType.Pinned);
```
`PaddleDetectionClass._PredictImage(bmp.Height, bmp.Width, 3, source, 0.1, gch_class_id.AddrOfPinnedObject(), gch_confidence.AddrOfPinnedObject(), gch_rect.AddrOfPinnedObject(), gch_image.AddrOfPinnedObject(), out size);`
调用之后，清除
```
gch_class_id.Free();
gch_confidence.Free();
gch_rect.Free();
gch_image.Free();
```
这样子就可以了

3. 存在的问题
原来的也能运行，那个样子又该如何释放内存呢？

**Comment by zhouyuxixixi** [comment]
但是与此同时，又发现了另外一个问题，现描述如下

内存均为任务管理器中显示的内存

1. 有一个按钮用来加载模型
2. 有一个按钮负责用来开启定时器，定时器响应函数开启模型预测
那么问题就来了
加载模型可以分为三种加载模型，加载模型后直接先预测一次
1、主线程
2、task
3、new thread
定时器响应函数预测模型也可分为（定时器为system.timer.timer）
1、定时器响应函数线程
2、new thread
3、task

1、主线程 + 定时器响应函数线程，运行正常，内存也不会增加
2、主线程 + new thread，运行正常，但是内存会不断上升
3、主线程 + task，运行正常，内存也不会增加
4、task + 定时器响应函数，直接报错
5、task + new thread， 运行正常，但是内存会不断上升
6、task + task，直接报错
7、new thread + 定时器响应函数线程，运行正常，内存不会增加
8、new thread + new thread，运行正常，内存不断上升
9、new thread + task，运行正常，内存不会增加

所有报错均如下
尝试读取和写入受保护的内存，且经过查找，都是死在了这句话，in_tensor->copy_from_cpu(inputs_.im_data_.data());

总结如下，
1、无论如何加载模型，只要new thread执行预测，都正确，但是内存会不断上升，推测应该是thread的使用问题

请谨慎使用thread

2、要说是因为线程原因，那么问题又来了，以上所有情况，在使用CPU预测的情况下，均正常，且内存不会上升

3、以上并未考虑在程序中，嵌套使用Task和thread的情况，且经过验证，当程序在加载和使用模型时，当确实存在Task和thread嵌套使用，也可能是嵌套使用task，也可能是嵌套使用thread，程序最后预测的时候使用Task，均会报错

**Comment by zhouyuxixixi** [comment]
经过最终的查找，发现了下面这个问题
使用new thread调用dll进行模型预测
我让C++不执行完成就直接返回，每一行进行测试，最后发现，
predictor_->ZeroCopyRun();有问题
在这句话之前返回，内存不会有任何变化
在这句话之后返回，内存会不断上涨

**Comment by zhouyuxixixi** [comment]
同时也尝试了1.8.5版本的预测库，也是同样的问题
同时怀疑是剪枝的问题，我进行预测的模型是经过剪枝的，后经过验证，也不是这个原因

**Comment by zhouyuxixixi** [comment]
但是，要说是predictor_->ZeroCopyRun();有问题，我直接开一个任务，这个任务是死循环，不断去预测，内存也不会增加，前提是加载模型也必须在这个任务内，不然就会直接报错
```
            Task.Run(() => {
                PaddleDetectionClass._LoadModel(configpath, true, "fluid");
                while (true)
                {
                    Thread.Sleep(10);
                    _ImageProcessForTask(image);
                }         
            });
```
我在C++中是这么写的
```
extern "C" __declspec(dllexport) void  _LoadModel(char* model_dir, bool use_gpu, char* run_mode);
extern "C" __declspec(dllexport) void _PredictImage(int height, int width, int channels, uchar * frame_src, double threshold,
    int* class_id, float* confidence, int* rect,
    uchar * image, size_t & size);

PaddleDetection::ObjectDetector PublicDet;

void _LoadModel(char* model_dir, bool use_gpu, char* run_mode)
{
    PublicDet = PaddleDetection::ObjectDetector(model_dir, use_gpu, run_mode);
}

void _PredictImage(int height, int width, int channels, uchar* frame_src, double threshold,
    int* class_id, float* confidence, int* rect,
    uchar* image, size_t& size)
{
    int format;
    switch (channels)
    {
    case 1:
        format = CV_8UC1;
        break;
    case 2:
        format = CV_8UC2;
        break;
    case 3:
        format = CV_8UC3;//bgr
        break;
    default:
        format = CV_8UC4;
        break;
    }

    cv::Mat im(height, width, format, frame_src);
    std::vector<PaddleDetection::ObjectResult> result;

    PublicDet.Predict(im, threshold, 0, 1, false, &result);
    std::cout << "Predict" << std::endl;

    int a = 0;
    for (const auto& item : result) {
        class_id[a] = item.class_id;
        confidence[a] = item.confidence;
        rect[4 * a] = item.rect[0];
        rect[4 * a + 1] = item.rect[1];
        rect[4 * a + 2] = item.rect[2];
        rect[4 * a + 3] = item.rect[3];
        a = a + 1;
    }

    auto labels = PublicDet.GetLabelList();
    auto colormap = PaddleDetection::GenerateColorMap(labels.size());
    //std::cout << labels[0] << std::endl;
    cv::Mat vis_img = PaddleDetection::VisualizeResult(
        im, result, labels, colormap);
    std::vector<uchar>buf;
    cv::imencode(".bmp", vis_img, buf);

    size = buf.size();

    for each (uchar var in buf)    //将buf拷贝到C#的byte[]中
    {
        *image = var;
        image++;
    }
    //vis_img.release();
    //im.release();
    //buf.clear();

}

```
C#调用

```
        [DllImport("main.dll", EntryPoint = "_LoadModel", CharSet = CharSet.Ansi)]
        public extern static void _LoadModel(string configPath, bool use_gpu, string run_mode);

        [DllImport("main.dll", EntryPoint = "_PredictImage", CharSet = CharSet.Ansi,CallingConvention  = CallingConvention.Cdecl)]
        public extern static void _PredictImage(int height, int width, int channels, byte[] srcImage, double threshold, IntPtr class_id, IntPtr confidence, IntPtr rect, IntPtr image, out ulong size);
```


跪求各路大神帮忙解决这个问题

我在想，要是能解决为什么加载模型和预测模型为什么都要在一个task里面，也许问题就解决了
下面写法不会报错
```
            Task.Run(() => {
                PaddleDetectionClass._LoadModel(configpath, true, "fluid");
                while (true)
                {
                    Thread.Sleep(10);
                    _ImageProcessForTask(image);
                }         
            });
```
下面写法会直接报错，查找，是这句话报错的in_tensor->copy_from_cpu(inputs_.im_data_.data());

```
            Task.Run(() => {
                PaddleDetectionClass._LoadModel(configpath, true, "fluid");
                Task.Run(()=> {
                    while (true)
                    {
                        Thread.Sleep(10);
                        _ImageProcessForTask(image);

                    }
                });
            });
```
区别就只是在于加载模型和预测模型不是一个TASK

所以我又怀疑是多线程调用GPU的问题，但是这个实在是不懂啊，已经到paddle的api接口了，跪求各路大神指点啊

**Comment by zhouyuxixixi** [comment]
经过不断对比发现，终于找到原因了
先上最终结论
请不要直接使用定义`std::shared_ptr<Predictor> predictor_;`和初始化`predictor_ = std::move(CreatePredictor(config));`生成的predictor_，
如果重复使用这个变量执行此函数`predictor_->Run();`，将会导致内存不断上升，
具体是啥原因，咱不清楚。
但是可以通过一种方式规避这个问题，
那就是每次预测之前，从原始的predictor_克隆一个predictor_，称为predictor1_，然后，用predictor1_去进行预测，就不会再出现内存增长的问题了，`auto predictor1_ = predictor_->Clone();`

也许是因为他是std::shared_ptr类型，这是啥玩意，咱也不清楚，还有待研究

**Comment by zhouyuxixixi** [comment]
建议官方将cpp里面的object_detector.cc按照issue发现的原因进行修改

**Comment by zhouyuxixixi** [comment]
说一下是如何发现这个问题的
paddle提供了自己的编译demo，[Paddle-Inference-Demo](https://github.com/PaddlePaddle/Paddle-Inference-Demo)
这个demo包含了1.8和2.0两个版本，2.0提供了一个[多线程的版本](https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/release/v2.0/c%2B%2B/test/shrink_memory/multi_thread_test.cc)
代码是这样写的
```
int main(int argc, char **argv) {
  google::ParseCommandLineFlags(&argc, &argv, true);

  paddle_infer::Config config;
  paddle_infer::PrepareConfig(&config);
  auto main_predictor = paddle_infer::CreatePredictor(config);
  std::vector<decltype(main_predictor)> predictors;
  for (int i = 0; i < FLAGS_thread_num; ++i) {
    predictors.emplace_back(std::move(main_predictor->Clone()));
  }

  std::vector<std::thread> threads;
  for (int i = 0; i < FLAGS_thread_num; ++i) {
    threads.emplace_back(paddle_infer::Run, predictors[i], i);
  }
  for (int i = 0; i < FLAGS_thread_num; ++i) {
    threads[i].join();
  }
  LOG(INFO) << "Run done";
}
```
请看这句话`predictors.emplace_back(std::move(main_predictor->Clone()));`他给每一个线程单独搞了一个main_predictor，而不是使用同一个main_predictor，很鸡贼，他就避免了本issue的问题

**Comment by hnothing2016** [comment]
@zhouyuxixixi  按照这个方法还是内存泄漏，帮忙看一看。
