### ISSUE TITLE
C++预测库在CPU上推断时间太长

### ISSUE THREAD

**Issue by chenlong8507** [PaddlePaddle/PaddleDetection#2423]
按照文档推荐的教程用C++预测库推断https://zhuanlan.zhihu.com/p/268657833
PPYOLO时间为20秒左右，Faster Rcnn为100秒左右，是否可以优化？
其他推理方式，比如onnx，在同样的cpu上，yolo 1秒以内，Faster Rcnn 3秒左右。
![image](https://user-images.githubusercontent.com/33168936/112339937-10b66180-8cfb-11eb-8c91-79e0c73f50bf.png)
![image](https://user-images.githubusercontent.com/33168936/112340109-37749800-8cfb-11eb-8205-05de4eac147c.png)

**Comment by wangxinxin08** [comment]
收到，我们确认下
