### ISSUE TITLE
When will PaddleDetection based YOLOv4 be officialy released?

### ISSUE THREAD

**Issue by August0424** [PaddlePaddle/PaddleDetection#2424]
I found that YOLOv4 has been included in the model lists, but failed to find pretrained model and detailed description of it within the PaddleDetection framework.

**Comment by wangxinxin08** [comment]
YOLOv4 will not be officialy released! Why not use our PPYOLO, which is faster and more accuracy? Please refer to [PPYOLO](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/configs/ppyolo) for detailed information!
