### ISSUE TITLE
利用export_model导出模型，infer_cfg.yml参数有问题

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/PaddleDetection#2425]
利用自己制作的数据集进行训练，训练后保存的模型，通过export_model导出，生成`__model__`,`__params__`和`infer_cfg.yml`三个文件。但是是生成的`infer_cfg.yml`文件中`label_list`的值与我时间训练时的值不符，导致利用这个模型进行推理时，识别到的图片标识有误
```
label_list:
- person
- bicycle
- car
- motorcycle
- airplane
- bus
- train
- truck
- boat
- traffic light
- fire hydrant
- stop sign
- parking meter
- bench
- bird
- cat
- dog
- horse
- sheep
- cow
- elephant
- bear
- zebra
- giraffe
- backpack
- umbrella
- handbag
- tie
- suitcase
- frisbee
- skis
- snowboard
- sports ball
- kite
- baseball bat
- baseball glove
- skateboard
- surfboard
- tennis racket
- bottle
- wine glass
- cup
- fork
- knife
- spoon
- bowl
- banana
- apple
- sandwich
- orange
- broccoli
- carrot
- hot dog
- pizza
- donut
- cake
- chair
- couch
- potted plant
- bed
- dining table
- toilet
- tv
- laptop
- mouse
- remote
- keyboard
- cell phone
- microwave
- oven
- toaster
- sink
- refrigerator
- book
- clock
- vase
- scissors
- teddy bear
- hair drier
- toothbrush
```

**Comment by wangxinxin08** [comment]
应该是没有指定TestReader的anno_path导致加载了默认的coco的label_list

**Comment by Huihuihh** [comment]
> 应该是没有指定TestReader的anno_path导致加载了默认的coco的label_list

我TestReader的anno_path指定的是验证集的`annotations/valid.json`，这里是需要指定label_list吗。但是我看示例里面这里都是填的json文件

**Comment by wangxinxin08** [comment]
> > 应该是没有指定TestReader的anno_path导致加载了默认的coco的label_list
> 
> 我TestReader的anno_path指定的是验证集的`annotations/valid.json`，这里是需要指定label_list吗。但是我看示例里面这里都是填的json文件

你是coco格式的数据集，不需要指定label_lis，anno_path的路径没有写全，导致找不到文件，anno_path填写示例dataset/coco/annotations/valid.json

**Comment by Huihuihh** [comment]
> > > 应该是没有指定TestReader的anno_path导致加载了默认的coco的label_list
> > 
> > 
> > 我TestReader的anno_path指定的是验证集的`annotations/valid.json`，这里是需要指定label_list吗。但是我看示例里面这里都是填的json文件
> 
> 你是coco格式的数据集，不需要指定label_lis，anno_path的路径没有写全，导致找不到文件，anno_path填写示例dataset/coco/annotations/valid.json

确实是路径没写全，解决了

**Comment by akingyin1987** [comment]
我问下这个导出的模型，如何转成使用的model.nb 格式

**Comment by xiegegege** [comment]
@akingyin1987 可以参考 https://paddle-lite.readthedocs.io/zh/latest/user_guides/opt/opt_python.html 这个文档来转成.nb格式，在https://github.com/PaddlePaddle/Paddle-Lite 这个repo里

**Comment by 1220985305** [comment]
model.pdmodel，model.pdiparams如何转成nb模型？
