### ISSUE TITLE
请问下何时会发布旋转/倾斜目标检测

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/PaddleDetection#2437]
现在的标注框大都是正的矩形，
有些时候待检测的目标是倾斜的，所以想问下
有没有开发倾斜目标检测的计划？

**Comment by qingqing01** [comment]
@zouxiaoshi 旋转框检测代码在PR https://github.com/PaddlePaddle/PaddleDetection/pull/2432  中，目前还在做终版的评测。近期会发布。

**Comment by zouxiaoshi** [comment]
> @zouxiaoshi 旋转框检测代码在PR #2432 中，目前还在做终版的评测。近期会发布。

好的，多谢，我已经fork了你的repo，准备提前看下。感觉贡献与付出。

**Comment by 617475jordan** [comment]
请问现在进度如何？什么时候出旋转检测，谢谢
