### ISSUE TITLE
ttfnet_darknet.yml 训练voc数据集报错

### ISSUE THREAD

**Issue by liangruofei** [PaddlePaddle/PaddleDetection#2438]
ttfnet_darknet.yml在训练voc的时候报错，我见issue中有人说不支持voc格式的数据集训练，不知道是不是和我一样，还请大佬给看看，报错如下：

```
[INFO 2021-03-26 10:44:07,563 eval_utils.py:196] Test finish iter 10484
2021-03-26 10:44:07,563-INFO: Total number of images: 10484, inference time: 12.93599486415175 fps.
[INFO 2021-03-26 10:44:07,563 eval_utils.py:202] Total number of images: 10484, inference time: 12.93599486415175 fps.
2021-03-26 10:44:07,563-INFO: Start evaluate...
[INFO 2021-03-26 10:44:07,563 voc_eval.py:56] Start evaluate...
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 320, in main
    cfg['EvalReader']['dataset'])
  File "PaddleDetection-release-2.0-rc/ppdet/utils/eval_utils.py", line 267, in eval_results
    map_type=map_type)
  File "PaddleDetection-release-2.0-rc/ppdet/utils/voc_eval.py", line 71, in bbox_eval
    gt_boxes = t['gt_bbox'][0]
KeyError: 'gt_bbox'
terminate called without an active exception


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1616726648 (unix time) try "date -d @1616726648" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e8000010bb) received by PID 4283 (TID 0x7f8d729b6700) from PID 4283 ***]

段错误 (核心已转储)
```

**Comment by qingqing01** [comment]
@liangruofei 

VOC数据在 

EvalReader中增加下 'gt_bbox', 'gt_class', 'is_difficult' 字段吧。

https://github.com/PaddlePaddle/PaddleDetection/blob/abc2e7f3dd7c15b87831d75832389f1d706ddd48/configs/yolov3_darknet_voc_diouloss.yml#L80

**Comment by liangruofei** [comment]
> @liangruofei
> 
> VOC数据在
> 
> EvalReader中增加下 'gt_bbox', 'gt_class', 'is_difficult' 字段吧。
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/abc2e7f3dd7c15b87831d75832389f1d706ddd48/configs/yolov3_darknet_voc_diouloss.yml#L80

加了，还是会报错，我看了程序里面，他好像没有这几个字段输入，
我的配置如下：
TrainReader:
  inputs_def:
    fields: ['image', 'ttf_heatmap', 'ttf_box_target', 'ttf_reg_weight']

EvalReader:
  inputs_def:
    image_shape: [3, 512, 512]
    fields: ['image', 'im_id', 'scale_factor', 'gt_bbox', 'gt_class', 'is_difficult']
报错如下

`The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
2021-03-26 13:37:47,002-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000400] in Optimizer will not take effect, and it will only be applied to other Parameters!
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 163, in main
    feed_vars, eval_loader = model.build_inputs(**inputs_def)
  File "/home/liangruofei/paddle2.0/PaddleDetection-release-2.0-rc/ppdet/modeling/architectures/ttfnet.py", line 117, in build_inputs
    lod_level=inputs_def[key]['lod_level'])) for key in fields])
  File "/home/liangruofei/paddle2.0/PaddleDetection-release-2.0-rc/ppdet/modeling/architectures/ttfnet.py", line 117, in <listcomp>
    lod_level=inputs_def[key]['lod_level'])) for key in fields])
KeyError: 'gt_bbox'

`

**Comment by qingqing01** [comment]
@jerrywgz please have a look. Thanks!

**Comment by jerrywgz** [comment]
我在ttfnet_darknet.yml这个配置文件上做了修改，主要是几个位置：metric需要改为VOC；Reader中需要把COCODataSet修改为VOCDataSet，并正确设置dataset_dir和anno_path。我这边在roadsign数据集（voc格式）上测试是能跑通的

**Comment by liangruofei** [comment]
我就是这么改的，train没问题，就是eval报错，首先ttfne里面没有'gt_bbox', 'gt_class', 'is_difficult'这些参数


在2021年3月29日 ***@***.***> 写道：

我在ttfnet_darknet.yml这个配置文件上做了修改，主要是几个位置：metric需要改为VOC；Reader中需要把COCODataSet修改为VOCDataSet，并正确设置dataset_dir和anno_path。我这边在roadsign数据集（voc格式）上测试是能跑通的

**Comment by jerrywgz** [comment]
预测阶段，确实像上面说的，需要在配置文件中增加'gt_bbox', 'gt_class', 'is_difficult' 这三个字段，然后还需要调整下代码，在`ppdet/modeling/architectures/ttfnet.py`中增加如下代码
![image](https://user-images.githubusercontent.com/22989727/112784289-d85cad80-9083-11eb-8001-7232594b3d10.png)

**Comment by liangruofei** [comment]
哦哦，明白了，感谢感谢


在2021年3月29日 ***@***.***> 写道：

预测阶段，确实像上面说的，需要在配置文件中增加'gt_bbox', 'gt_class', 'is_difficult' 这三个字段，然后还需要调整下代码，在ppdet/modeling/architectures/ttfnet.py中增加如下代码
