### ISSUE TITLE
Xavier使用基于2.0.1的预测库发生错误

### ISSUE THREAD

**Issue by Eesenn** [PaddlePaddle/PaddleDetection#2442]
2.0.1的预测库在paddle/lib路径下文件为libpaddle_inference.so而不是libpaddle_fluid.so
在执行sh ./scripts/build.sh时会提示错误
![image](https://user-images.githubusercontent.com/81418502/112625000-4ed19380-8e69-11eb-9156-360a660e62b0.png)

**Comment by qingqing01** [comment]
PaddleDetection 2.0-rc版本建议先使用2.0的预测库。 PaddleDetection下个版本会升级预测库，支持2.0.1。

**Comment by Eesenn** [comment]
> PaddleDetection 2.0-rc版本建议先使用2.0的预测库。 PaddleDetection下个版本会升级预测库，支持2.0.1。

可是现在就算自行编译Paddle2.0产生的文件也是libpaddle_inference.so，而官方又没有基于2.0的最新jetpack4.4/4.5的预测库，所以现在想用PaddleDetection只能在老环境下运行吗

**Comment by qingqing01** [comment]
@Eesenn  develop分支我们针对动态图做了升级，我们也对静态图做下升级吧。

**Comment by sdnusqy-art** [comment]
> > PaddleDetection 2.0-rc版本建议先使用2.0的预测库。 PaddleDetection下个版本会升级预测库，支持2.0.1。
> 
> 可是现在就算自行编译Paddle2.0产生的文件也是libpaddle_inference.so，而官方又没有基于2.0的最新jetpack4.4/4.5的预测库，所以现在想用PaddleDetection只能在老环境下运行吗

我遇到了类似问题， 自行编译了Paddle2.0产生的文件也是libpaddle_inference.so，但是PaddleDetection的C++端部署需要链接libfuid_inference.so文件，目前的PaddleDetection不支持Paddle2.0吗，或者是稍微改一下链接就行， 如果改在哪改，未找到
