### ISSUE TITLE
c++多图推理问题

### ISSUE THREAD

**Issue by jesen8** [PaddlePaddle/PaddleDetection#2452]
您好， 感谢回复
使用版本 release/2.0-beta
在cpp推理时，batch不论是否大于1时，模型推理结果都为 n x 6的结果， 这是包含了 nms 后的结果，而且模型输出只有这一个tensor，因此目前认为无法区分这n个数据无法和batch个图片做对应关系
当然，知道n x 6经过 nms 后是按照 score 排序了的， 但是如果其中有一张图片一个框都没有，这时候就无法知道对应关系了。
比如 n为4 时， 结果如下， 此种情况是能找到相应的 box 与 图片的
class_id: 0 score: 0.0324232 box: 21 724, 516 953
class_id: 0 score: 0.0104396 box: 342 811, 543 955
class_id: 0 score: 0.0272704 box: 19 725, 517 952
class_id: 0 score: 0.0108353 box: 341 810, 543 956
class_id: 0 score: 0.0310878 box: 18 728, 519 952
class_id: 0 score: 0.0133587 box: 341 810, 543 956
class_id: 0 score: 0.0447556 box: 20 731, 514 952
class_id: 0 score: 0.0188732 box: 341 808, 543 956
但是当 n为4 时，结果可能如下，就没有办法了
class_id: 0 score: 0.0104558 box: 19 317, 522 942
因此是否可以在模型推理输出加一个维度信息 还是啥

而且目前发现使用轻量型网络在batch大于1时，速度有明显提高，但是在 ppyolo cpsdarknet上 推理时间是随batch大小线性增长的，是否表示暂时没有对此网络进行推理优化  还是说轻量型网络天生就适合多batch

**Comment by yghstill** [comment]
@jesen8 您好，感谢反馈，目前cpp推理暂不支持batch size>1，这个功能也正在开发中，下个版本会支持。关于速度问题，轻量化模型在batch size大时加速明显，大模型提升相对较少。

**Comment by jesen8** [comment]
@yghstill 您好，那有什么替代方案吗， 比如推荐我用同等精度速度更快的网络模型训练，目前只了解yolo系列，或者直接模型量化

**Comment by yghstill** [comment]
@jesen8  你是需要在服务端部署还是在移动端部署？
服务端还可以参考rcnn增强模型：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/configs/rcnn_enhance
移动端可参考：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/configs/mobile

**Comment by jesen8** [comment]
@yghstill 在服务端部署， 还有我的场景比较独特， 样本比较少，或者说样本分布比较单一，因为难以采集，需要大量背景图片用于抗干扰训练， 因此yolo系列支持无标签背景图像进行训练， 而不知道rcnn系列是否也支持，之前听说是不支持的
rcnn增强模型 Cascade Faster 确实快

**Comment by yghstill** [comment]
@jesen8 RCNN还不支持无标签训练，这个功能也是在排期开发中，可以先在yolo系列模型上尝试。

**Comment by jesen8** [comment]
@yghstill 好的 感谢

**Comment by thzyyx** [comment]
@yghstill  我在使用python接口推理时遇到相同的情况，是不是2.0版本的paddle-inference库不支持多batch推理
补充：eval.py脚本修改配置文件中的 EvalReader:下的batch_size:字段，fps始终无明显变化，是不是eval.py底层本身也调用inference接口，而inference接口本身无法支持多batch推理？

**Comment by jesen8** [comment]
@thzyyx c++肯定时可以的
