### ISSUE TITLE
连续训练与迁移学习的问题

### ISSUE THREAD

**Issue by yuchen02** [PaddlePaddle/PaddleDetection#2453]
1.连续训练：在我进行训练时，10个小时算力用完了，但是我的模型还没有达到要求，请问我该如何继续接着训练？
2.迁移学习：我使用个人数据集使用官方预训练模型训练出了参数，当我还需要训练同类的数据时，是否可以将我自己训练出的best_model作为预训练模型继续训练？还是必须通过官方预训练模型？
望了解的大佬帮小弟解答。

**Comment by yghstill** [comment]
@yuchen02 
1. 可以继续训练，-r 指定断点weights路径就可以resume。
2. 将你自己的best_model作为预训练权重加载继续训练即可，官方pretrain weight在你第一次训自定义数据集时帮助较大，再进行第2、3...次训练时加载上次训好的模型即可。
