### ISSUE TITLE
训练集全部都是黑色背景，是否会影响模型在复杂背景下的识别？

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleDetection#2454]
请教：如果训练集全部都是黑色背景，是否会影响模型在复杂背景下的识别？

**Comment by jesen8** [comment]
肯定的，样本需要多元化，覆盖范围广，这样才能在复杂背景下表现出色，想想coco的图片背景有多丰富

**Comment by yghstill** [comment]
嗯嗯，@jesen8 说的对，可利用一些数据预处理方法，填充背景（比如手动填充或GAN等）
