### ISSUE TITLE
请问如何导出“最优的”精确率precision和召回率recall呢？

### ISSUE THREAD

**Issue by zxsitu** [PaddlePaddle/PaddleDetection#2467]
您好，我看 #2346 已经实现了绘制PR曲线的功能了，我想问一下如何从PR曲线中选出一个能同时反映精确率和召回率两者平衡时“最优”（或者说最佳组合时）的点呢？请问 “develop”分支 可以导出这个“最优”的点 (precision, recall) 吗？
如果不能，请问我们该如何从PR曲线中选出这个点，您有什么好的建议呢？谢谢。

**Comment by liuhuiCNN** [comment]
（1）这里PR曲线是针对每个类别的。
（2）我的理解是，所谓“最优”需要根据您的需求来确定，您是注重准确率还是召回率呢？您也可以考虑根据曲线下面积来选择模型。

**Comment by zxsitu** [comment]
@liuhuiCNN 谢谢您很及时的回复。
我的自定义数据集（coco格式）类别有5类，所以eval程序运行 `--classwise` 会导出5条PR曲线吗？还是说导出一条总的PR曲线。
我希望这个点越来越靠近 (1, 1) 就可以了，因为我希望更看重的是F1分数（f1-score），所以希望是准确率和召回率两者的平衡，您有好的建议吗？

**Comment by liuhuiCNN** [comment]
（1）5条曲线 （2）您可以参考F1-score

**Comment by zxsitu** [comment]
@liuhuiCNN 程序好像没法直接计算出F1-score，看来要想想怎样将具体的precision和recall值输出，然后再计算取平均，作为整个模型的F1-score了。

**Comment by Dekadenc** [comment]
> @liuhuiCNN 程序好像没法直接计算出F1-score，看来要想想怎样将具体的precision和recall值输出，然后再计算取平均，作为整个模型的F1-score了。

请问现在这个问题您解决了嘛
