### ISSUE TITLE
圣诞写真缺少背景json文件，需要补充

### ISSUE THREAD

**Issue by leemengxing** [PaddlePaddle/PaddleDetection#2472]
如题，想要试一试应用，目前发现：
1.需要解压模型tar压缩包
2.缺少背景background对应的json文件。
麻烦补充下

**Comment by leemengxing** [comment]
FileNotFoundError: [Errno 2]  No such file or directory: 'element_source/background/1.json'

**Comment by liuhuiCNN** [comment]
感谢反馈，我们尽快补充。
