### ISSUE TITLE
训练一轮后自动退出了？

### ISSUE THREAD

**Issue by shenjun1994** [PaddlePaddle/PaddleDetection#2475]
安装的paddle2.0.1，训练maskrcnn，静态图训练10000次后自动退出了，没有任何错误，配置文件里面max_iter是180000，动态图训练的时候一轮结束后也自动退出了，配置文件里面epoch是12，也就是每次到了保存模型参数的时候，程序就自己退出了，配置文件里面只改了coco数据集路径，退出没有报任何错误，知道这是什么问题吗？（我都没有加载预训练的权重）

**Comment by shenjun1994** [comment]
> 安装的paddle2.0.1，训练maskrcnn，静态图训练10000次后自动退出了，没有任何错误，配置文件里面max_iter是180000，动态图训练的时候一轮结束后也自动退出了，配置文件里面epoch是12，也就是每次到了保存模型参数的时候，程序就自己退出了，配置文件均只改了coco数据集路径，其他没改，退出没有报任何错误知道这是什么问题吗？（我都没有加载预训练的权重）

**Comment by wangxinxin08** [comment]
请问PaddleDetection的版本是什么？以及运行的命令是什么？

**Comment by shenjun1994** [comment]
> 请问PaddleDetection的版本是什么？以及运行的命令是什么？
PaddleDetection版本是2.0-rc，命令python tools/train.py -c configs/mask_rcnn_r50_fpn_1x.yml --eval，静态图和动态图跑试了一下，发现每次到snapshot_iter后,在eval_run这个函数里面跑完验证集，就直接退出了，打印信息停留在Test iter 4900，也没进入except(StopIteration ....)这个异常处理。

**Comment by wangxinxin08** [comment]
麻烦发一下打印信息的截图

**Comment by shenjun1994** [comment]
> 麻烦发一下打印信息的截图
为了快速验证，我把snopshot_iter改成了1000，同时在eval_run里面把test iter的打印信息改成1000次打印一次，我也在except中加入了print()，但是没执行到这句。当把--eval设置为False的时候，是可以继续往下运行的。
![屏幕截图 2021-03-31 114205](https://user-images.githubusercontent.com/59006550/113087631-a465c180-9216-11eb-8111-057ff377d252.png)

**Comment by wangxinxin08** [comment]
我们这边测试是没有问题的，你可以使用终端再运行一下这个命令，并把except中的print改成logger.info试下，看看有没有问题

**Comment by shenjun1994** [comment]
> 我们这边测试是没有问题的，你可以使用终端再运行一下这个命令，并把except中的print改成logger.info试下，看看有没有问题
我的环境是win10，anaconda3,cuda10.2,在spyder里面运行和在终端里面都不行，我感觉是eval_run的函数问题，每次遍历完整个验证集都会出现这个问题，于是我加了两行代码，让他只遍历其中1000张图，目前发现可以正常往下走了，不知道您是在什么环境下测试的。
![屏幕截图 2021-03-31 161152](https://user-images.githubusercontent.com/59006550/113113752-354f9380-923d-11eb-951b-08f98a15aee0.png)
![屏幕截图 2021-03-31 161223](https://user-images.githubusercontent.com/59006550/113113764-37195700-923d-11eb-88e1-a32610af6c04.png)

**Comment by wangxinxin08** [comment]
windows环境，你把break去掉，在except把print换成logger.info试试，你这种情况可能是某一张图片有问题

**Comment by shenjun1994** [comment]
> windows环境，你把break去掉，在except把print换成logger.info试试，你这种情况可能是某一张图片有问题
我加了，也尝试了多种数据集，都是没有任何信息打印，甚至把那try-except注释掉了，也不报错，就是正常退出，有时候在训练过程中也会自动正常退出，看训练轮数应该已经把数据集遍历好几遍了，这些数据集我都是在pytorch框架下正常训练过多种不同模型的，应该是没有问题的，不知道会不会是windows环境和paddle不太兼容的问题。

**Comment by wangxinxin08** [comment]
由于wiondows环境也在本地测过，使用的是coco数据集，你可以换下coco数据集看看会不会有同样的问题

**Comment by shenjun1994** [comment]
> 由于wiondows环境也在本地测过，使用的是coco数据集，你可以换下coco数据集看看会不会有同样的问题
昨天一直拿的coco试的，今天拿自己的几个数据集试的，也下载了2.0和0.5版本的paddledetection，一样的问题，我再看看代码多试试吧，实在不行我就换ubuntu试试，麻烦你们了

**Comment by 923629877** [comment]
你好，请问解决了吗

**Comment by shenjun1994** [comment]
> 你好，请问解决了吗

没有，我的windows环境下，更新了PaddlePaddle和PaddleDetection，依旧是在第一轮的最后一个iter退出

**Comment by shenjun1994** [comment]
> 你好，请问解决了吗

没有，我的windows环境下，更新了PaddlePaddle和PaddleDetection，依旧是在第一轮的最后一个iter退出

**Comment by jwm111** [comment]
> > 你好，请问解决了吗
> 
> 没有，我的windows环境下，更新了PaddlePaddle和PaddleDetection，依旧是在第一轮的最后一个iter退出

我也出现了相同的问题。后来通过重新配置一个conda环境解决了。
