### ISSUE TITLE
多机多卡训练问题？

### ISSUE THREAD

**Issue by AN-ZE** [PaddlePaddle/PaddleDetection#2476]
请问，多机多卡训练，有没有详细的说明。

现在环境, 是使用conda 虚拟环境创建的paddle。如果是多机多卡，是不是就不能使用虚拟环境了。
环境：cuda 10.0 + paddle1.8+paddledetection 0.4。需要升级成2.0吗
机器为单机8卡，准备使用两个机器进行多机训练。
数据方面，是主机器存放数据，还是多个机器都需要存放数据。
snapshot_iter: 数据数值，是按单机的8个卡算，还是按照两个机器的16卡计算。

感谢！

**Comment by wangxinxin08** [comment]
目前多机多卡属于实验状态的功能，性能也在持续优化中，并且只支持动态图的运行方式，需要使用develop或者release/2.0-rc的PaddleDetection进行训练。多机多卡每台机器都需要存放数据，snapshot_iter是根据batch_size的大小设置的，在动态图模式下已经不存在这个配置，只需要修改学习率为原先的2倍即可。

**Comment by AN-ZE** [comment]
snapshot_iter: 这个值不是一个epoch的值么，看来这个我理解错了。我以为是这么算的
snapshot_iter = ( 1个epoch的数据总量 / batch_size ) / gpus_num 
max_iters = snapshot_iter * epoch_num

多机训练设置，是这样使用么

**机器1**
export PYTHONPATH=$PYTHONPATH:.
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

node_ip=`hostname -i`
python -m paddle.distributed.launch \
     --use_paddlecloud \
    --cluster_node_ips ${192.168.1.1},${192.168.1.2} \
    --node_ip ${192.168.1.1} \
    tools/train_multi_machine.py \
        -c configs/faster_rcnn_r50_fpn_1x.yml

**机器2**
export PYTHONPATH=$PYTHONPATH:.
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

node_ip=`hostname -i`
python -m paddle.distributed.launch \
     --use_paddlecloud \
    --cluster_node_ips ${192.168.1.1},${192.168.1.2} \
    --node_ip ${192.168.1.2} \
    tools/train_multi_machine.py \
        -c configs/faster_rcnn_r50_fpn_1x.yml

**Comment by wangxinxin08** [comment]
1. snapshot_iter和batch_size的关系基本和你所说的是一致的，只不过不一定每一个epoch都保存一次，你可以根据batch_size的变化来设置，比如你现在使用两机，总的batch_size变成了原先的2倍，snapshot_iter就只需要变成原来的1/2，max_iters也是一样的，同时学习率也变成原来的2倍
2. 可以使用conda创建的环境，但需要保证两台机器的环境和运行代码完全一致，另外运行的命令应该是：
    export PYTHONPATH=$PYTHONPATH:.
    export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
  
    node_ip=`hostname -i`
    python -m paddle.distributed.launch
    --cluster_node_ips 192.168.1.1,192.168.1.2
    --node_ip ${node_ip}
    tools/train_multi_machine.py
   -c configs/faster_rcnn_r50_fpn_1x.yml
${node_ip}是shell中取值的操作，表示取出变量node_ip的值, ${192.168.1.1},${192.168.1.2}应该改成192.168.1.1,192.168.1.2，https://github.com/PaddlePaddle/PaddleDetection/blob/develop/static/docs/tutorials/MULTI_MACHINE_TRAINING_cn.md  文档示例中的${}也是shell中取值的意思。不要使用--use_paddlecloud，因为你不是使用paddlecloud训练的

**Comment by AN-ZE** [comment]
感谢!  等机器训练空下来，立马进行试验。

**Comment by AN-ZE** [comment]
麻烦再问一下，两个机器的训练数据是一样的吗，还是各自放一半数据。

**Comment by AN-ZE** [comment]
麻烦再问一下，两个机器的训练数据是一样的吗，还是各自放一半数据。

**Comment by wangxinxin08** [comment]
数据是一样的

**Comment by WenLinLliu** [comment]
一样的问题，CPU单核吃满了，多核不运行，GPU利用率低
