### ISSUE TITLE
提个比较弱智的问题，如果不想使用预训练权重，应该如何指定命令行参数或者配置文件啊

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#2481]
提个比较弱智的问题，如果不想使用预训练权重，应该如何指定命令行参数或者配置文件啊

**Comment by wangxinxin08** [comment]
使用-o pretrain_weights=''，比如python tools/train.py xxx -o pretrain_weights=''

**Comment by dengxinlong** [comment]
> 使用-o pretrain_weights=''，比如python tools/train.py xxx -o pretrain_weights=''

你这好像是指定相应的预训练权重啊，我想的是指定不使用预训练权重。

**Comment by wangxinxin08** [comment]
-o pretrain_weights=''，把pretrain_weights设置成空字符就不使用预训练权重了

**Comment by dengxinlong** [comment]
> -o pretrain_weights=''，把pretrain_weights设置成空字符就不使用预训练权重了

哦哦哦， 原来您是这个意思啊，抱歉，没有理解到位。感谢您的回复！！！
