### ISSUE TITLE
PP YOLO inferring box color

### ISSUE THREAD

**Issue by sukkyusun** [PaddlePaddle/PaddleDetection#2486]
i trained ppyolo with my own set

and inferring with extra test sets

color of boxes are same in same image.(when class 1is green)

but test with other images class 1 box color is not green

how can i unify this box colors with each classes

**Comment by wangxinxin08** [comment]
There is a function named `draw_bbox`  in `ppdet/utils/visualizer.py`. You can modify the code below

`
    if catid not in catid2color:
        idx = np.random.randint(len(color_list))
        catid2color[catid] = color_list[idx]
`

to 

`
    if catid not in catid2color:
        catid2color[catid] = color_list[catid]
`
