### ISSUE TITLE
模型训练报错

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleDetection#2488]
在进行训练时报Segmentation fault (core dumped)的错误，我的环境如下：
操作系统：Ubuntu 16.04.6 LTS
python版本：3.6
paddle版本：paddlepaddle-gpu (2.0.1.post101)
cuda版本：10.1
cudnn版本：7.6.5

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&)
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 2ul, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, long>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, paddle::platform::complex64>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, paddle::platform::complex128> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   void paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, float>::SliceCompute<2ul>(paddle::framework::ExecutionContext const&) const
5   Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 0, Eigen::MakePointer>, Eigen::TensorSlicingOp<std::array<long, 2ul> const, std::array<long, 2ul> const, Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, long>, 0, Eigen::MakePointer> const> const> const, Eigen::DefaultDevice, true, (Eigen::internal::TiledEvaluation)1>::run(Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 0, Eigen::MakePointer>, Eigen::TensorSlicingOp<std::array<long, 2ul> const, std::array<long, 2ul> const, Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, long>, 0, Eigen::MakePointer> const> const> const&, Eigen::DefaultDevice const&)
6   paddle::framework::SignalHandle(char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1617198148 (unix time) try "date -d @1617198148" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x4) received by PID 16353 (TID 0x7f80bfba6700) from PID 4 ***]

Segmentation fault (core dumped)

**Comment by wangxinxin08** [comment]
请问运行的命令是什么？

**Comment by Williamlizl** [comment]
解决了吗

**Comment by Lie-huo** [comment]
> 解决了吗

已经解决了，谢谢

**Comment by Williamlizl** [comment]
> > 解决了吗
> 
> 已经解决了，谢谢

你好，请问怎么解决的，我也是同样问题

**Comment by jerry90** [comment]
同问 怎么解决的 一样问题

**Comment by cuesong** [comment]
同问
