### ISSUE TITLE
import paddle会警告

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleDetection#2491]
当import paddle时，会报“/opt/conda/lib/python3.6/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp”，python是3.6，paddle版本是paddlepaddle-gpu (2.0.1.post101)，系统是Ubuntu 16.04.6，请问这个怎么解决

**Comment by wangxinxin08** [comment]
可以忽略这个warning，不影响正常运行

**Comment by heavengate** [comment]
您好，这个warning是setuptools版本更新导致的，develop和release/2.0上已经将`requirement.txt`更新，重新`pip install -r requirement.txt`可以解决这个warning
