### ISSUE TITLE
关于模型格式

### ISSUE THREAD

**Issue by Sharpiless** [PaddlePaddle/PaddleDetection#2493]
cascade_mask_rcnn_dcnv2_se154_vd_fpn_gn_s1x 等模型给的权重并非pdparams或者__model__的格式，我用如下方法转换，导出的模型并不能产生任何预测结果，请问正确做法如何？

    checkpoint.load_params(
            exe, train_prog, cfg.pretrain_weights, ignore_params=[])

    cfg_name = os.path.basename(FLAGS.config).split('.')[0]
    save_dir = os.path.join(cfg.save_dir, cfg_name)
    time_stat = deque(maxlen=cfg.log_iter)
    save_name = "model_final"
    checkpoint.save(exe, train_prog, os.path.join(save_dir, save_name))

**Comment by qingqing01** [comment]
@Sharpiless 

您的方法看起来没错，我测试看下原因。

**Comment by qingqing01** [comment]
@Sharpiless 

您好，经过测试没有问题。具体测试方法如下:


step1: 修改tools/infer.py脚本，增加下面代码，保存合并的模型:

```
diff --git a/tools/infer.py b/tools/infer.py
index bd26650..1fb9fd6 100644
--- a/tools/infer.py
+++ b/tools/infer.py
@@ -127,6 +127,13 @@ def main():
     if cfg.weights:
         checkpoint.load_params(exe, infer_prog, cfg.weights)

+
+    save_dir = 'new_model'
+    save_name = "model_final"
+    checkpoint.save(exe, infer_prog, os.path.join(save_dir, save_name))
+    return
+
+
     # parse infer fetches
     assert cfg.metric in ['COCO', 'VOC', 'OID', 'WIDERFACE'], \
             "unknown metric type {}".format(cfg.metric)
```

step2: 运行tools/infer.py保存模型， 保存到 `new_model/model_final.xx`

```

python tools/infer.py -c configs/dcn/cascade_mask_rcnn_dcnv2_se154_vd_fpn_gn_s1x.yml \
    -o weights=https://paddlemodels.bj.bcebos.com/object_detection/cascade_mask_rcnn_dcnv2_se154_vd_fpn_gn_s1x.tar \
    --infer_img demo/000000014439.jpg
```

step3:  去掉上面`tools/infer.py`代码


step4: 删除`output/000000014439.jpg`，使用新模型，再次测试:

```
python tools/infer.py -c configs/dcn/cascade_mask_rcnn_dcnv2_se154_vd_fpn_gn_s1x.yml \
    -o weights=new_model/model_final \
    --infer_img demo/000000014439.jpg
```
结果没问题:


<img width="635" alt="图片" src="https://user-images.githubusercontent.com/7845005/113276013-fa6b5f80-9311-11eb-8dbf-a8b7e745436c.png">

**Comment by Sharpiless** [comment]
好的感谢
