### ISSUE TITLE
推理速度问题？

### ISSUE THREAD

**Issue by thugbobby** [PaddlePaddle/PaddleDetection#2494]
我在使用maskrcnn训练完自己的素材后，进行Python的推理部署后，在1660GPU的环境下推理一张图片只需要在500毫秒左右，而在CPU环境下需要的时间是40多秒，在降低图片的分辨率的情况下速度也没有明显的改善。目前的需求是想要进行CPU推理提速，请问有什么优化的方法或者思路吗？感谢。

**Comment by qingqing01** [comment]
@thugbobby 

> CPU环境下需要的时间是40多秒

您想CPU提升到多少呢？ 

> 在降低图片的分辨率的情况下速度也没有明显的改善

输入图片分辨率降低后，测试Resize的值是否修改？

**Comment by thugbobby** [comment]
> @thugbobby
> 
> > CPU环境下需要的时间是40多秒
> 
> 您想CPU提升到多少呢？
> 
> > 在降低图片的分辨率的情况下速度也没有明显的改善
> 
> 输入图片分辨率降低后，测试Resize的值是否修改？

你好，测试resize的值是有修改的。分辨率在1024 * 768和600 * 300的情况下，两种分辨率在CPU的推理时间是相差无几的，这种情况是正常的吗？

**Comment by qingqing01** [comment]
@thugbobby 

我自测了下, 1024 * 768和600 * 300的速度差异还是挺大的，我使用Mask-FPN, `deploy/python/infer.py`评测速度，本地CPU有其他任务也在用，但测试速度还是差异明显:

```
#python deploy/python/infer.py --model_dir=inference_model/mask_rcnn_r50_fpn_1x --image_file=test_1024_768.jpg --use_gpu=False --run_benchmark=True
python deploy/python/infer.py --model_dir=inference_model/mask_rcnn_r50_fpn_1x --image_file=test_600_300.jpg --use_gpu=False --run_benchmark=True
```

- test_1024_768.jpg, inference_model/mask_rcnn_r50_fpn_1x/infer_cfg.yml改动如下:

```
- interp: 1
  max_size: 1024
  resize_box: false
  target_size: 768
  type: Resize
  use_cv2: true
```

 Inference: 12568.659591674805 ms per batch image  


- test_600_300.jpg, inference_model/mask_rcnn_r50_fpn_1x/infer_cfg.yml改动如下:


```
- interp: 1
  max_size: 600
  resize_box: false
  target_size: 300
  type: Resize
  use_cv2: true
```

Inference: 4218.484878540039 ms per batch image


您必须使用CPU嘛？以及想提速到多少？ CPU的加速可以开启MKLDNN:

参考 

https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/native_infer.html#cpu

```
config->DisableGpu();          // 禁用GPU
config->EnableMKLDNN();            // 开启MKLDNN，可加速CPU预测
config->SetCpuMathLibraryNumThreads(10);        // 设置CPU Math库线程数，CPU核心数支持情况下可加速预测
```

需要下面代码后面开启:


https://github.com/PaddlePaddle/PaddleDetection/blob/abc2e7f3dd7c15b87831d75832389f1d706ddd48/deploy/python/infer.py#L413

**Comment by qingqing01** [comment]
@thugbobby  当然实例分割，您也可以考虑使用SOLOv2。
