### ISSUE TITLE
请问，如何把静态版本中的ACFPN模块加到动态版本中？动态版本中AutoAugment模块该如何正确引入？

### ISSUE THREAD

**Issue by LDX17** [PaddlePaddle/PaddleDetection#2503]
引入AutoAugment模块如下图：
![image](https://user-images.githubusercontent.com/66930694/113419389-f3b81780-93f9-11eb-8bd0-0a015c69cb19.png)
出现错误：
![image](https://user-images.githubusercontent.com/66930694/113419465-15190380-93fa-11eb-9e7f-4aac3afeb6dc.png)

**Comment by heavengate** [comment]
看报错信息是没找到`AutoAugment`，动态图的实现里这个transform叫`AutoAugmentImage`可以参考下 https://github.com/PaddlePaddle/PaddleDetection/blob/abc2e7f3dd7c15b87831d75832389f1d706ddd48/ppdet/data/transform/operators.py#L633
