### ISSUE TITLE
各位百度大佬们节日快乐，想问一下关于剪裁的问题

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2504]
1.我用敏感度分析的数据画出来的图片比较杂乱无章，看官方的给的图挺整齐的（conv层分布在上方，yolo层分布在下方），是否是我出现了错误，还是说跟数据集有关系呢？
2、在分析出来的敏感度数据里，发现在某些ratio下，map_loss出现了负数（敏感度的.data文件里是个嵌套字典，ratio对应的值应该是map_loss吧？），这是否正常呢？并且某些层增加了剪裁ratio，loss反而降低了，这是否正常呢？

**Comment by guotongjian** [comment]
还想问下，在剪裁方法里，是用Pruning Filters for Efficient Convnets的方法，进行逐层的剪枝吗，还是针对整体的一个剪枝呢。我看剪裁日志是在每个层下每一个ratio剪一下，评估一次，这个有考虑到前后层间的影响吗

**Comment by heavengate** [comment]
1. 可以发一下你画出来的图我们看下
2. 在有些裁剪率下精度反而有提升是正常现象，可以理解为传统机器学习里加了L1范数做了特征筛选，一定程度上有抑制过拟合的作用
3. 是逐层裁剪的，裁剪中可以通过`--prune_params`和`--prune_raitos`指定需要裁剪的层和裁剪率

**Comment by guotongjian** [comment]
> 1. 可以发一下你画出来的图我们看下
> 2. 在有些裁剪率下精度反而有提升是正常现象，可以理解为传统机器学习里加了L1范数做了特征筛选，一定程度上有抑制过拟合的作用
> 3. 是逐层裁剪的，裁剪中可以通过`--prune_params`和`--prune_raitos`指定需要裁剪的层和裁剪率

![Figure_2](https://user-images.githubusercontent.com/73452319/113501257-44448780-9556-11eb-9d85-0d4b7a3daa4d.png)
我剪的yolo3增强版的图，……
