### ISSUE TITLE
请问，为啥同一个模型，隔一段时间再评估，结果相差很大？

### ISSUE THREAD

**Issue by LDX17** [PaddlePaddle/PaddleDetection#2511]
这是年前的结果：
![image](https://user-images.githubusercontent.com/66930694/113574239-44c04980-964e-11eb-86b6-71a0cee4aae6.png)
这是今天得结果：
![image](https://user-images.githubusercontent.com/66930694/113574377-8d780280-964e-11eb-9424-53e39ffbe3b2.png)

**Comment by liuhuiCNN** [comment]
你好，由于paddle版本升级或PaddleDetection升级，可能会影响某些OP的计算，因此请您检查：
（1）请确认两次使用的paddle版本是否一致
（2）请确认两次使用的PaddleDetection版本是否一致

**Comment by LDX17** [comment]
你好，前后两次我没改动任何地方，都是线上环境。怎么会这样呢？
