### ISSUE TITLE
No module named 'paddle.fluid.dataloader.collate'

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleDetection#2520]
在运行develop下的模型时，出现下面的错误，但是运行release/2.0-rc时就没有报错，查看了一下出错的地方，是ppdet/data/reader.py中的数据读取方式发生了改变，请问这种情况怎么解决呢？
  File "/home/bml/storage/PaddleDetection/ppdet/data/reader.py", line 28, in <module>
    from paddle.fluid.dataloader.collate import default_collate_fn
ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'

**Comment by wangxinxin08** [comment]
目前运行PaddleDetection的develop分支需要安装PaddlePaddle develop版本
