### ISSUE TITLE
提个问题，如果想要基于你们的模型进行二次开发，应该怎么做？下面是具体信息。

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#2521]
比如：我之前评估的模型就是你们已经训练好的ssdlite_mobilenet_v3_large，现在想基于这个进行一些改进。能否直接基于 tools/train.py文件进行修改，还是说整个模型都需要自己重建构建？？

**Comment by wangxinxin08** [comment]
如果你需要创建自己的模型，静态图请参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/docs/advanced_tutorials/MODEL_TECHNICAL.md，动态图请参考：https://github.com/wangxinxin08/PaddleDetection/blob/docs/docs/advanced_tutorials/MODEL_TECHNICAL.md

**Comment by dengxinlong** [comment]
> 如果你需要创建自己的模型，静态图请参考：[https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/docs/advanced_tutorials/MODEL_TECHNICAL.md，动态图请参考：https://github.com/wangxinxin08/PaddleDetection/blob/docs/docs/advanced_tutorials/MODEL_TECHNICAL.md](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/docs/advanced_tutorials/MODEL_TECHNICAL.md%EF%BC%8C%E5%8A%A8%E6%80%81%E5%9B%BE%E8%AF%B7%E5%8F%82%E8%80%83%EF%BC%9Ahttps://github.com/wangxinxin08/PaddleDetection/blob/docs/docs/advanced_tutorials/MODEL_TECHNICAL.md)

你们的动态图和静态图的区别是啥啊，我看了半天没哟看出啥区别来！

**Comment by wangxinxin08** [comment]
基本没区别，一些细节需要注意下就行，比如基类

**Comment by dengxinlong** [comment]
> 基本没区别，一些细节需要注意下就行，比如基类

我大致对比了您发的两个链接里里面的内容，在内容上有一些区别。比如您发的动态图中（也就是docs分支），有heads目录。但是在静态图链接中（release-2.0/rc分支）中是没有这个目录的。我git的也是release分支，如果我想按照您发的动态图链接来构建网络模型，会不会出现问题？？

**Comment by dengxinlong** [comment]
> 基本没区别，一些细节需要注意下就行，比如基类

我说错了，在静态图链接中的ppdet/modeling是没有neck目录的。

**Comment by wangxinxin08** [comment]
> > 基本没区别，一些细节需要注意下就行，比如基类
> 
> 我大致对比了您发的两个链接里里面的内容，在内容上有一些区别。比如您发的动态图中（也就是docs分支），有heads目录。但是在静态图链接中（release-2.0/rc分支）中是没有这个目录的。我git的也是release分支，如果我想按照您发的动态图链接来构建网络模型，会不会出现问题？？

release/2.0-rc的主目录为静态图，dygraph目录下的结构基本和docs分支一致

**Comment by dengxinlong** [comment]
> > > 基本没区别，一些细节需要注意下就行，比如基类
> > 
> > 
> > 我大致对比了您发的两个链接里里面的内容，在内容上有一些区别。比如您发的动态图中（也就是docs分支），有heads目录。但是在静态图链接中（release-2.0/rc分支）中是没有这个目录的。我git的也是release分支，如果我想按照您发的动态图链接来构建网络模型，会不会出现问题？？
> 
> release/2.0-rc的主目录为静态图，dygraph目录下的结构基本和docs分支一致

那能否两种方式混用呢？？
