### ISSUE TITLE
请问一下，静态图版本中，想要打印每类具体的precision和recall值，该在哪里添加代码？谢谢！

### ISSUE THREAD

**Issue by LDX17** [PaddlePaddle/PaddleDetection#2529]

**Comment by zxsitu** [comment]
+1

**Comment by wangxinxin08** [comment]
请参考动态图中classwise的代码, COCO:https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/metrics/coco_utils.py#L62, VOC:https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/metrics/map_utils.py#L257
