### ISSUE TITLE
 python3 ppdet/modeling/tests/test_architectures.py运行不起来问题

### ISSUE THREAD

**Issue by liyungithub** [PaddlePaddle/PaddleDetection#254]
![image](https://user-images.githubusercontent.com/22513244/75109134-07704680-565c-11ea-9f97-4762367ae405.png)

**Comment by liyungithub** [comment]
![image](https://user-images.githubusercontent.com/22513244/75109249-ad23b580-565c-11ea-832e-ed4efe8779ca.png)

**Comment by willthefrog** [comment]
what PaddleDetection version  are you using? in recent version `doc_parse` call should have been wrapped in side a `try ... except` block. I suggest you update to latest version or remove the `docstring_parser` package, either way it should work.

**Comment by liyungithub** [comment]
更到最新，通过了，谢谢！
![image](https://user-images.githubusercontent.com/22513244/75150505-81c5c700-573f-11ea-9c6e-bdcbe0881208.png)
