### ISSUE TITLE
请教各位大佬一个问题

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2545]
请问paddledetection里面怎么把检测画出来的类别和置信度的字体放大呢

**Comment by qingqing01** [comment]
@guotongjian 

您如果是tools/infer.py入口的话，可以参考 https://github.com/PaddlePaddle/PaddleDetection/issues/2347#issuecomment-799098535

**Comment by guotongjian** [comment]
好的，谢谢
