### ISSUE TITLE
为什么还没有mobilenetv3_yolov3的模型或者mobilenetv2_yolov3的

### ISSUE THREAD

**Issue by jaffe-fly** [PaddlePaddle/PaddleDetection#255]
在paddle Detection中只看到mobilenetv1_yolov3的模型，没有其他两个，是经过测试其他两个模型的性能不好吗？还是后面会出来？

**Comment by qingqing01** [comment]
@jaffe-fly  暂且没加，后面会出来。当然，也可以参考 https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification MobileNetv2/v3 配置和预训练模型，尝试。

**Comment by jaffe-fly** [comment]
谢谢
