### ISSUE TITLE
编译deploy失败

### ISSUE THREAD

**Issue by Cristhine** [PaddlePaddle/PaddleDetection#2551]
![image](https://user-images.githubusercontent.com/26667855/113962547-7ad21900-985a-11eb-9221-b28e821af2ac.png)
直接使用ppdet deploy cpp编译服务 报错 麻烦看下报错问题

**Comment by qingqing01** [comment]
@Cristhine 是下载yaml失败，注意网络问题。

**Comment by Cristhine** [comment]
> @Cristhine 是下载yaml失败，注意网络问题。

我注意到了网络问题 重新换了服务器 并且直接wget ymal是可以下载zip的 但是依然是同样的错误 就很奇怪

**Comment by Cristhine** [comment]
> @Cristhine 是下载yaml失败，注意网络问题。

![image](https://user-images.githubusercontent.com/26667855/113971893-39e30000-986c-11eb-9ec5-a342a5569565.png)
 看build里面这个yaml_cpp.zip是下载下来了

**Comment by heavengate** [comment]
> > @Cristhine 是下载yaml失败，注意网络问题。
> 
> ![image](https://user-images.githubusercontent.com/26667855/113971893-39e30000-986c-11eb-9ec5-a342a5569565.png)
> 看build里面这个yaml_cpp.zip是下载下来了

ext/yaml文件夹删掉重新编译试下呢

**Comment by Cristhine** [comment]
> > > @Cristhine 是下载yaml失败，注意网络问题。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/26667855/113971893-39e30000-986c-11eb-9ec5-a342a5569565.png)
> > 看build里面这个yaml_cpp.zip是下载下来了
> 
> ext/yaml文件夹删掉重新编译试下呢

也没用 我自己指定了一个编译好的yaml 现在报错opencv的问题 这个是什么问题 并且 这个deploy编译的环境需要什么？
![image](https://user-images.githubusercontent.com/26667855/114136755-cf9a9000-993d-11eb-80c8-9babe156d58b.png)

**Comment by sdnusqy-art** [comment]
> > > > @Cristhine 是下载yaml失败，注意网络问题。
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/26667855/113971893-39e30000-986c-11eb-9ec5-a342a5569565.png)
> > > 看build里面这个yaml_cpp.zip是下载下来了
> > 
> > 
> > ext/yaml文件夹删掉重新编译试下呢
> 
> 也没用 我自己指定了一个编译好的yaml 现在报错opencv的问题 这个是什么问题 并且 这个deploy编译的环境需要什么？
> ![image](https://user-images.githubusercontent.com/26667855/114136755-cf9a9000-993d-11eb-80c8-9babe156d58b.png)

需要安装gtk，ffpmeg等包，这个问题你解决了吗， 我都编译安装之后还是有opencv的问题，如下，这个是什么问题？ffpmeg版本有问题？
![image](https://user-images.githubusercontent.com/73977336/115325570-6d078680-a1be-11eb-9736-84735d126923.png)

**Comment by sdnusqy-art** [comment]
> > > > > @Cristhine 是下载yaml失败，注意网络问题。
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/26667855/113971893-39e30000-986c-11eb-9ec5-a342a5569565.png)
> > > > 看build里面这个yaml_cpp.zip是下载下来了
> > > 
> > > 
> > > ext/yaml文件夹删掉重新编译试下呢
> > 
> > 
> > 也没用 我自己指定了一个编译好的yaml 现在报错opencv的问题 这个是什么问题 并且 这个deploy编译的环境需要什么？
> > ![image](https://user-images.githubusercontent.com/26667855/114136755-cf9a9000-993d-11eb-80c8-9babe156d58b.png)
> 
> 需要安装gtk，ffpmeg等包，这个问题你解决了吗， 我都编译安装之后还是有opencv的问题，如下，这个是什么问题？ffpmeg版本有问题？
> ![image](https://user-images.githubusercontent.com/73977336/115325570-6d078680-a1be-11eb-9736-84735d126923.png)

搞定了， 官方提供的opencv是ubuntu预编译版本，如果其他系统需要自己编译opencv，比如centos如果用了官方的opencv就会有以上错误
