### ISSUE TITLE
ppdet运行ssd报CUDA 错误？？

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2552]
求大神指点
![QQ图片20210408122220](https://user-images.githubusercontent.com/73452319/113968904-8deae600-9866-11eb-887e-a01d2e9a9512.png)
![X ~ZBIUZY2ZE~9QP28_) M0](https://user-images.githubusercontent.com/73452319/113968946-a824c400-9866-11eb-9af6-706a41eb24bf.png)
![JO2NSRF6XPO@~)HNV)L4T8C](https://user-images.githubusercontent.com/73452319/113968955-abb84b00-9866-11eb-8ce6-cf182ddb27df.png)

**Comment by qingqing01** [comment]
@guotongjian 报错信息提示，分类的label超过了0-4范围，是29724。注意数据标注正确性。

**Comment by guotongjian** [comment]
> @guotongjian 报错信息提示，分类的label超过了0-4范围，是29724。注意数据标注正确性。

我的数据标注应该没问题，用别的配置文件可以运行的，用的coco格式数据是不是background要设置为-1？

**Comment by guotongjian** [comment]
> @guotongjian 报错信息提示，分类的label超过了0-4范围，是29724。注意数据标注正确性。

已解决，谢谢老师
