### ISSUE TITLE
reader读取数据的时候报错No space left on device

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleDetection#2555]
环境：CentOS7.6
PaddlePaddle2.0
PaddleDetection release0.4
CUDA 10.2

在使用自己的数据集训练时出现如下错误：

> loading annotations into memory...
> Done (t=0.34s)
> creating index...
> index created!
> Traceback (most recent call last):
>   File "train.py", line 369, in <module>
>     main()
>   File "train.py", line 205, in main
>     num_trainers=num_trainers)
>   File "/home/xxxx/xxxx/modelTrainServing/ppdet/data/reader.py", line 441, in create_reader
>     reader = Reader(**cfg)()
>   File "/home/xxxx/xxxx/modelTrainServing/ppdet/data/reader.py", line 272, in __init__
>     use_process, memsize)
>   File "/home/xxxx/xxxx/modelTrainServing/ppdet/data/parallel_map.py", line 86, in __init__
>     self._setup()
>   File "/home/xxxx/xxxx/modelTrainServing/ppdet/data/parallel_map.py", line 106, in _setup
>     self._outq = Queue(bufsize, memsize=memsize)
>   File "/home/xxxx/xxxx/modelTrainServing/ppdet/data/shared_queue/queue.py", line 63, in __init__
>     capacity=memsize, pagesize=pagesize)
>   File "/home/xxxx/xxxx/modelTrainServing/ppdet/data/shared_queue/sharedmemory.py", line 415, in __init__
>     self._setup()
>   File "/home/xxxx/xxxx/modelTrainServing/ppdet/data/shared_queue/sharedmemory.py", line 418, in _setup
>     self._shared_mem = RawArray('c', self._cap)
>   File "/home/xxxx/.conda/envs/pp20/lib/python3.6/multiprocessing/context.py", line 129, in RawArray
>     return RawArray(typecode_or_type, size_or_initializer)
>   File "/home/xxxx/.conda/envs/pp20/lib/python3.6/multiprocessing/sharedctypes.py", line 60, in RawArray
>     obj = _new_value(type_)
>   File "/home/xxxx/.conda/envs/pp20/lib/python3.6/multiprocessing/sharedctypes.py", line 40, in _new_value
>     wrapper = heap.BufferWrapper(size)
>   File "/home/xxxx/.conda/envs/pp20/lib/python3.6/multiprocessing/heap.py", line 248, in __init__
>     block = BufferWrapper._heap.malloc(size)
>   File "/home/xxxx/.conda/envs/pp20/lib/python3.6/multiprocessing/heap.py", line 230, in malloc
>     (arena, start, stop) = self._malloc(size)
>   File "/home/xxxx/.conda/envs/pp20/lib/python3.6/multiprocessing/heap.py", line 128, in _malloc
>     arena = Arena(length)
>   File "/home/xxxx/.conda/envs/pp20/lib/python3.6/multiprocessing/heap.py", line 77, in __init__
>     f.write(zeros)
> OSError: [Errno 28] No space left on device
> Exception ignored in: <bound method SharedMemoryMgr.__del__ of <ppdet.data.shared_queue.sharedmemory.SharedMemoryMgr object at 0x7f83a6c37860>>
> Traceback (most recent call last):
>   File "/home/xxxx/xxxx/modelTrainServing/ppdet/data/shared_queue/sharedmemory.py", line 524, in __del__
>     if not self._released and not self._allocator.empty():
> AttributeError: 'SharedMemoryMgr' object has no attribute '_allocator'

请问这个是什么原因呢？

**Comment by heavengate** [comment]
哪个模型，`free -h`看下你机器上空闲内存多少呢

**Comment by nihuizhidao** [comment]
看了下，这个主要是多线程读取数据的时候，系统默认的/tmp文件夹空间不够了，在`train.py`的开头加入下面的设置，就可以在脚本里指定临时的缓存路径：

```
import tempfile
tempfile.tempdir = ‘/path/to/your/tmp’
```
