### ISSUE TITLE
关于静态图下怎么输出或记录Precision和Recall

### ISSUE THREAD

**Issue by Hanqingliu-radiology** [PaddlePaddle/PaddleDetection#2557]
请问一下如果我想在静态图下记录precison和recall应该怎么操作呢。develop分支中没有我想用的网络，谢谢大佬们的回复。

**Comment by heavengate** [comment]
你好，动态图的precision和recall记录已经支持了，可以通过这个参数开启
https://github.com/PaddlePaddle/PaddleDetection/blob/bc8b0d4411da695152bdea055cac61f859f7bf59/tools/eval.py#L64
静态图由于后续会统一到动态图里面，所以precision和recall的pr没有合入，可以参考下 
https://github.com/PaddlePaddle/PaddleDetection/pull/1779

**Comment by Hanqingliu-radiology** [comment]
期待，谢谢
