### ISSUE TITLE
关于检测的Bbox

### ISSUE THREAD

**Issue by JunLei01** [PaddlePaddle/PaddleDetection#2562]
我使用paddledetection进行预测，可是输出的Bbox有负数，这是怎么回事。

**Comment by heavengate** [comment]
你好，你这边用的那个模型呢，模型权重有没有正确加载呢

**Comment by JunLei01** [comment]
用的是YOLOv4的模型，正确加载了

**Comment by JunLei01** [comment]
> 你好，你这边用的那个模型呢，模型权重有没有正确加载呢

用的是YOLOv 4的模型，正确加载了

**Comment by xinliqingpi** [comment]
遇到了同样问题，bbox有一堆负数
