### ISSUE TITLE
ssd loss如何自定义

### ISSUE THREAD

**Issue by lao-xu** [PaddlePaddle/PaddleDetection#2573]
套件里ssdloss是直接调用paddle api的，没有直接的实现。里面只有ssd_with_mlk_loss的实现，请问这个loss是干什么用的？如果要自定义loss怎么办？把ssd_with_mlk_loss去掉mlk部分好像也不太对

**Comment by yghstill** [comment]
@lao-xu 可以直接看动态图模型中ssd_loss: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/ppdet/modeling/losses/ssd_loss.py
其中有具体的实现细节。
