### ISSUE TITLE
请问预训练的PPYOLO（经过通道裁剪和知识蒸馏后的轻量化裁剪模型）能在高通865上部署吗？

### ISSUE THREAD

**Issue by August0424** [PaddlePaddle/PaddleDetection#2579]
我看到https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/slim中提到，通过高通835/高通855/麒麟970测试YOLOv3的推理时延，用了CPU的4线程。请问PPYOLO可以在高通865的NPU上部署起来吗？我们比较关心NPU上能不能跑起来

**Comment by wangxinxin08** [comment]
PPYOLO在高通865的NPU上还没测试过，理论上应该能跑，但也可能存在有一些op不支持的情况，比如dcn

**Comment by tangjiuqi097** [comment]
@wangxinxin08 请问为什么DCN不支持呢？有没有相关的文档或者论文呢
