### ISSUE TITLE
剪裁总是夯住，啥原因呢

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2583]
![1618209937(1)](https://user-images.githubusercontent.com/73452319/114351913-cd367100-9b9d-11eb-8cf6-213b549f5139.jpg)
夯住不动，没反应，等了有20分钟以上，没反应就关了，试了好几次都这样，是什么原因呢
paddle是2.0.1，paddlesilm是2.0.0版本，剪裁的是paddledetection-2.0-rc这个里面的模型

**Comment by guotongjian** [comment]
我尝试只剪一个层，仍然是打印剪枝信息，然后夯住。

**Comment by wangxinxin08** [comment]
收到，我们定位一下
