### ISSUE TITLE
旋转框目标检测的coco数据怎么生成？

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleDetection#2591]
您好，可以分享一下dota的四点标注数据怎么转成旋转框目标检测的coco数据么？

**Comment by wangxinxin08** [comment]
可以参考tools/x2coco.py进行转换

**Comment by Lie-huo** [comment]
> 可以参考tools/x2coco.py进行转换

请问[xc, yc, bow_w, bow_h, angle]的bow_w与bow_h有无长度的顺序要求，我看有的旋转标注数据里要求bow_w是长宽中比较大的是bow_w；另外，角度是[-180,180]吗，顺时针为正？

**Comment by liuhuiCNN** [comment]
> > 可以参考tools/x2coco.py进行转换
> 
> 请问[xc, yc, bow_w, bow_h, angle]的bow_w与bow_h有无长度的顺序要求，我看有的旋转标注数据里要求bow_w是长宽中比较大的是bow_w；另外，角度是[-180,180]吗，顺时针为正？

这里是要求 bow_w >= bow_h，角度是 [-pi/4, 3/4pi]。4点坐标转旋转框坐标请参考：[poly_2_rbox](https://github.com/PaddlePaddle/PaddleDetection/blob/480c12d6fd16561fc3f2742d0dc0a29752a22857/ppdet/modeling/bbox_utils.py#L410)

**Comment by cristianoKaKa** [comment]
请问训练的时候怎样修改Yml文件才能支持旋转框的数据呢？我看好像都是默认为水平bbox的数据

**Comment by 617475jordan** [comment]
请问使用默认s2anet_conv_1x_dota.pdparams，其类型对应id在哪儿看到，代码中没有找到，网上找到的类型与id对应不上
