### ISSUE TITLE
在JetsonNano上使用cpu推理没问题，GPU没有预测框

### ISSUE THREAD

**Issue by DragonGongY** [PaddlePaddle/PaddleDetection#2597]
使用PaddleDetection的模型在JetsonNano开发板上进行推理时，不管是使用depoy文件夹下面的C++还是Python，在使用GPU的情况下均无预测框，但使用cpu或者X86的GPU时，能够正常预测并输出预测狂

**Comment by liuhuiCNN** [comment]
请问使用的 PaddleDetection 版本、Paddle版本，JetsonNano系统版本是什么呢？
提示错误是什么呢？

**Comment by DragonGongY** [comment]
> 请问使用的 PaddleDetection 版本、Paddle版本，JetsonNano系统版本是什么呢？
> 提示错误是什么呢？

PaddleDetection版本为2.0-rc，Paddle的推理库下载的是https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html里面nano的版本，jetpack刷了4.3的版本，4.4的版本，都有同样的问题，打开gpu预测的时候没有预测框，使用trt_fp32以及trt_fp16,均报错，使用cpu预测正常

**Comment by DragonGongY** [comment]
> > 请问使用的 PaddleDetection 版本、Paddle版本，JetsonNano系统版本是什么呢？
> > 提示错误是什么呢？
> 
> PaddleDetection版本为2.0-rc，Paddle的推理库下载的是[https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html里面nano的版本，jetpack刷了4.3的版本，4.4的版本，都有同样的问题，打开gpu预测的时候没有预测框，使用trt_fp32以及trt_fp16,均报错，使用cpu预测正常](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html%E9%87%8C%E9%9D%A2nano%E7%9A%84%E7%89%88%E6%9C%AC%EF%BC%8Cjetpack%E5%88%B7%E4%BA%864.3%E7%9A%84%E7%89%88%E6%9C%AC%EF%BC%8C4.4%E7%9A%84%E7%89%88%E6%9C%AC%EF%BC%8C%E9%83%BD%E6%9C%89%E5%90%8C%E6%A0%B7%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E6%89%93%E5%BC%80gpu%E9%A2%84%E6%B5%8B%E7%9A%84%E6%97%B6%E5%80%99%E6%B2%A1%E6%9C%89%E9%A2%84%E6%B5%8B%E6%A1%86%EF%BC%8C%E4%BD%BF%E7%94%A8trt_fp32%E4%BB%A5%E5%8F%8Atrt_fp16,%E5%9D%87%E6%8A%A5%E9%94%99%EF%BC%8C%E4%BD%BF%E7%94%A8cpu%E9%A2%84%E6%B5%8B%E6%AD%A3%E5%B8%B8)

![Screenshot from 2021-04-12 15-57-07](https://user-images.githubusercontent.com/29235462/114491138-a3865400-9c48-11eb-97d1-15d544598f39.png)
这个是使用GPU时，提示的信息

**Comment by liuhuiCNN** [comment]
建议您使用paddle2.0预测库试试。

**Comment by DragonGongY** [comment]
> 建议您使用paddle2.0预测库试试。

![DeepinScreenshot_select-area_20210414013618](https://user-images.githubusercontent.com/29235462/114531872-dea37a00-9c7e-11eb-96e7-5c61d626a9f8.png)
使用的是这两个版本的，jetpack也都是用的对应的版本，这个是paddle2.0.1的版本，而且我还在jetpack4.3下面，自行编译paddle release/2.0后，还是出现同样的问题

**Comment by liuhuiCNN** [comment]
> > 建议您使用paddle2.0预测库试试。
> 
> ![DeepinScreenshot_select-area_20210414013618](https://user-images.githubusercontent.com/29235462/114531872-dea37a00-9c7e-11eb-96e7-5c61d626a9f8.png)
> 使用的是这两个版本的，jetpack也都是用的对应的版本，这个是paddle2.0.1的版本，而且我还在jetpack4.3下面，自行编译paddle release/2.0后，还是出现同样的问题

建议用PaddleDetection release/2.0试下。

**Comment by lleesg** [comment]
> > > 建议您使用paddle2.0预测库试试。
> > 
> > 
> > ![DeepinScreenshot_select-area_20210414013618](https://user-images.githubusercontent.com/29235462/114531872-dea37a00-9c7e-11eb-96e7-5c61d626a9f8.png)
> > 使用的是这两个版本的，jetpack也都是用的对应的版本，这个是paddle2.0.1的版本，而且我还在jetpack4.3下面，自行编译paddle release/2.0后，还是出现同样的问题
> 
> 建议用PaddleDetection release/2.0试下。

试了下2.0，还是同样问题，这个问题很多issue提到一直没得到彻底解决。
