### ISSUE TITLE
关于IoU LOSS CIOU DIOU那里面的loss_weight是指什么，这个loss_weight是不是平衡Nreg的BBOX的λ平衡参数

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#2598]
这个关于iou部分的配置信息只在iou_loss里面有  并没有中文文档说明 希望解答一下

**Comment by qingqing01** [comment]
@shuxsu 


loss_weight仅仅是给IoU loss最后增加一个权重。 可以参考代码

https://github.com/PaddlePaddle/PaddleDetection/blob/78fdd43e48f91c0a5ed5c6f02820bfd75ec9dea3/ppdet/modeling/losses/diou_loss.py#L123

https://github.com/PaddlePaddle/PaddleDetection/blob/78fdd43e48f91c0a5ed5c6f02820bfd75ec9dea3/ppdet/modeling/losses/giou_loss.py#L147
