### ISSUE TITLE
模型剪裁问题

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2612]
我用paddleslim剪裁我训练的ppdet的模型，没有成功，总是打印剪枝信息然后夯住，
请问我的执行命令有问题吗
我的版本paddleslim2.0.0，paddledetection2.0beta，paddle2.0.1
我的命令：python slim/prune/prune.py -c ./configs/dcn/mymodel.yml --pruned_params "conv1_1_weights" --pruned_ratios="0.3"

**Comment by yghstill** [comment]
@guotongjian 剪裁启动比较慢，打印完下面的log后需要等一会儿，程序就会启动：
```
2021-04-14 02:04:24,972 - INFO - pruned params: ['conv1_1_weights']
2021-04-14 02:04:24,972 - INFO - pruned ratios: [0.3]
2021-04-14 02:04:25,049-INFO: pruning: conv1_1_weights
```
我在本地测试是没问题的。

**Comment by guotongjian** [comment]
> @guotongjian 剪裁启动比较慢，打印完下面的log后需要等一会儿，程序就会启动：
> 
> ```
> 2021-04-14 02:04:24,972 - INFO - pruned params: ['conv1_1_weights']
> 2021-04-14 02:04:24,972 - INFO - pruned ratios: [0.3]
> 2021-04-14 02:04:25,049-INFO: pruning: conv1_1_weights
> ```
> 
> 我在本地测试是没问题的。

我试了很多次  都是夯住，有次挂了一个小时都没反应，也不报错，这个大概什么原因呢

**Comment by guotongjian** [comment]
@wanghaoshuang my dear 大佬 能帮忙看看吗

**Comment by wanghaoshuang** [comment]
@guotongjian 请您参考这个PR：https://github.com/PaddlePaddle/PaddleSlim/pull/700/files

在本地修改下相关文件。

这个PR会在今天或明天合入，你到时安装develop分支也行。

**Comment by guotongjian** [comment]
> @guotongjian 请您参考这个PR：https://github.com/PaddlePaddle/PaddleSlim/pull/700/files
> 
> 在本地修改下相关文件。
> 
> 这个PR会在今天或明天合入，你到时安装develop分支也行。
好的谢谢

**Comment by guotongjian** [comment]
> @guotongjian 请您参考这个PR：https://github.com/PaddlePaddle/PaddleSlim/pull/700/files
> 
> 在本地修改下相关文件。
> 
> 这个PR会在今天或明天合入，你到时安装develop分支也行。

您好，本地的这个文件是指所装的paddleslim环境里的吗，我在本地的paddleslim环境里看了这个文件，里面的代码是跟您的这个一模一样的。
