### ISSUE TITLE
将SSD的ssd_loss移到ssd

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#2613]
将ssd的ssd_loss（原来是在paddle.fluid.layer.detection.py文件中）移动到ssd.py文件中
其实就是将detection.py文件中的ssd_loss函数移动到ssd.py文件的SSD类中，作为该类的一个成员函数，然后再计算loss的时候调用该ssdLoss函数就是，但是在该函数的LayerHelper类实例化的时候显示参数太多了。这不应该啊，我啥也没有改变，就是将ssd_loss移动到了SSD类中。下面是调用点的截图和ssdLoss成员函数的截图：
![image](https://user-images.githubusercontent.com/32217129/114648338-32f73a00-9d11-11eb-8dc0-3539be5c5e7d.png)

![image](https://user-images.githubusercontent.com/32217129/114648280-1fe46a00-9d11-11eb-9042-7fb63365a4fa.png)

这个是报错的截图：
![image](https://user-images.githubusercontent.com/32217129/114648874-1c9dae00-9d12-11eb-9e63-3af5b67565e7.png)

或者说贵方实现的LayerHelper类有一些其他的设定导致实例化失败？？？

**Comment by heavengate** [comment]
多了个`self`参数，不建议你把loss移出来，如果想移出来可以作为独立函数，不要作为类的成员函数

**Comment by dengxinlong** [comment]
> 多了个`self`参数，不建议你把loss移出来，如果想移出来可以作为独立函数，不要作为类的成员函数

嗯嗯，我知道，其实应该是移出来作为一个独立的模块的处理是比较好的；但我这里只是想做一个测试，所以就没有考虑那么多了，感谢您的回复！！！

**Comment by heavengate** [comment]
好的，如果问题解决了，当前issue就先关闭了~
