### ISSUE TITLE
PaddleServing部署服务时没反应？

### ISSUE THREAD

**Issue by Lie-huo** [PaddlePaddle/PaddleDetection#2624]
PaddleServing部署服务，在启动PaddleServing服务时，python -m paddle_serving_server_gpu.serve --model serving_server --port 9393 --gpu_ids 0，运行后一直没反应，请问这怎么解决？

**Comment by heavengate** [comment]
@liuhuiCNN 帮忙跟进一下吧~

**Comment by liuhuiCNN** [comment]
请问使用的PaddleServing版本是多少呢？哪个模型呢？PaddleServing 0.5.0 在主要检测模型上都是ok的，建议您试一下PaddleServing 0.5.0。

**Comment by Lie-huo** [comment]
> 请问使用的PaddleServing版本是多少呢？哪个模型呢？PaddleServing 0.5.0 在主要检测模型上都是ok的，建议您试一下PaddleServing 0.5.0。

就是PaddleServing 0.5.0 ，模型是自己训练的ppyolo模型

**Comment by Lie-huo** [comment]
> 请问使用的PaddleServing版本是多少呢？哪个模型呢？PaddleServing 0.5.0 在主要检测模型上都是ok的，建议您试一下PaddleServing 0.5.0。

**Comment by Lie-huo** [comment]
> > 请问使用的PaddleServing版本是多少呢？哪个模型呢？PaddleServing 0.5.0 在主要检测模型上都是ok的，建议您试一下PaddleServing 0.5.0。

0.5.0，模型是自己训练后导出的ppyolo模型
