### ISSUE TITLE
训练模型时，无限等待，GPU不跑

### ISSUE THREAD

**Issue by roy66ccff** [PaddlePaddle/PaddleDetection#2625]
项目代码地址：https://aistudio.baidu.com/aistudio/projectdetail/647591
不知道哪的问题，请大家fork一下试一试看行不行？

问题如下图，点击执行后，无限转圈，卡在箭头那一步不继续往下执行
![1](https://user-images.githubusercontent.com/33149893/114709220-e5092300-9d5e-11eb-9265-3a3b2b6c1b64.png)

CPU/GPU都不跑
![2](https://user-images.githubusercontent.com/33149893/114709232-e6d2e680-9d5e-11eb-82ed-29c5e21ba246.png)

环境信息：
![3](https://user-images.githubusercontent.com/33149893/114709234-e76b7d00-9d5e-11eb-89e1-a0578451e2f8.png)

**Comment by heavengate** [comment]
你好，PaddleDetection已经更新到release/2.0版本，可以试下最新版本的实现

**Comment by roy66ccff** [comment]
> 你好，PaddleDetection已经更新到release / 2.0版本，可以试下最新版本的实现

已经找到问题所在了，原因是数据集的样本太少了，试着增加到60张以上就可以正常训练了
