### ISSUE TITLE
比较PaddleDetection和paddleCV的训练速度，同样的配置和网络，PaddleDetection训练慢很多

### ISSUE THREAD

**Issue by FibonacciSun** [PaddlePaddle/PaddleDetection#264]
训练的网络是mobilenet-ssd
采用的是paddleDetection和paddleCV里提供的配置和代码，paddleDetection训练用的配置文件是，PaddleDetection/configs/ssd/ssd_mobilenet_v1_voc.yml
paddleCV跑的是 models/PaddleCV/ssd/train.py

我们只是把batchsize 统一成32，并配置采用单卡训练，不加载预训练模型，其他无变化，均采用仓库里的原始配置

在同一台机器上。初始学习率用的都是0.001
从迭代的速度来看，我们统计出来
PaddleDetection： 240 iter / min
PaddleCV 558 iter /min

之前就一直感觉paddleDetection训练慢（相比于其他框架）。是不是我们哪里使用方法不对？ 麻烦指点

**Comment by still-wait** [comment]
@FibonacciSun 
### 测试：
- 环境：P40单卡，num_work=8，batch size=32
- PaddleCV下ssd的repo训练：
![image](https://user-images.githubusercontent.com/15628872/75437921-f85a0300-5991-11ea-8d56-4ad844c463f4.png)
- PaddleDetection下训练：
![image](https://user-images.githubusercontent.com/15628872/75437961-0e67c380-5992-11ea-9113-76060a41af73.png)

### 结论：
PaddleDetection训练速度更快。PaddleDetection版本为release/0.2分支

**Comment by FibonacciSun** [comment]
哦，我还在release/0.1上
更新后快了
谢谢！
