### ISSUE TITLE
请问一下，anchor_free中所有的模型的训练配置都是使用的V100 8卡吗？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleDetection#2646]
尊敬的开发者，您好，
请问一下，[anchor_free](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/configs/anchor_free/README.md)中所有的模型的训练配置都是使用的V100 8卡吗？
![图片](https://user-images.githubusercontent.com/27288110/114856189-66bd8700-9e19-11eb-95ad-6f7bb126bc45.png)

期待你的回复！

**Comment by jerrywgz** [comment]
是的，都是基于8卡的配置

**Comment by songyuc** [comment]
@jerrywgz ，你好，对于cornernet_squeeze_hg104.yml来说，我看到这样的设置，
https://github.com/PaddlePaddle/PaddleDetection/blob/84e79e8760ba2ef7fbc3972d865316af9aade014/configs/anchor_free/cornernet_squeeze_hg104.yml#L85
也就是说，8卡训练的话，等价于`batch_size = 14*8 =  112`，是这样吗？

**Comment by jerrywgz** [comment]
是的

**Comment by songyuc** [comment]
@jerrywgz ，好的，谢谢您的解答！
