### ISSUE TITLE
develop最新的分支：2.0rc1导出的模型在这个分支deploy/python/infer.py出现问题

### ISSUE THREAD

**Issue by GZHUZhao** [PaddlePaddle/PaddleDetection#2652]
2.0rc1的ssd_mobilenet_v1_voc模型，配置文件直接拷贝的2.0rc1下con'figs/ssd/ssd_mobilenet_v1_voc.yml
想使用develop分支最新的trt_int8
paddlepaddle-gpu=2.0
命令：先试fliud模式
python deploy/python/infer.py --model_dir=./export_model/ssd_mobilenet_v1_voc/ --camera_id=0 --use_gpu=1
报错：
![2021_1](https://user-images.githubusercontent.com/78419361/114897351-ba44ca80-9e43-11eb-8857-7a3db01bff58.png)
经过export_model的模型是如下格式的，却提示无法打开model.pdmodel
![2021_2](https://user-images.githubusercontent.com/78419361/114897994-55d63b00-9e44-11eb-9634-376aa9183950.png)

问题：
请问需要如何修改？
还是需要用develop下的tools导出一遍？

**Comment by yghstill** [comment]
@GZHUZhao 你是使用的是https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/deploy/python/infer.py 吗？看报错你使用的是动态图下的脚本，你导出的是静态图模型，应该使用这个链接中的deploy/python/infer.py脚本预测。

**Comment by yghstill** [comment]
@GZHUZhao 你是使用的是https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/deploy/python/infer.py 吗？看报错你使用的是动态图下的脚本，你导出的是静态图模型，应该使用这个链接中的deploy/python/infer.py脚本预测。

**Comment by GZHUZhao** [comment]
> @GZHUZhao 你是使用的是https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/deploy/python/infer.py 吗？看报错你使用的是动态图下的脚本，你导出的是静态图模型，应该使用这个链接中的deploy/python/infer.py脚本预测。

![最新](https://user-images.githubusercontent.com/78419361/115051175-1d4f6380-9f0f-11eb-9de4-1db58a0e3b86.png)
我用的红色这个deploy，您的意思是用static下面的deploy吗？这个分支的文件结构和2.0r'c的不同，我可能搞错了

**Comment by yghstill** [comment]
嗯嗯，你进static文件夹进行预测吧，static文件夹下都是静态图模型
