### ISSUE TITLE
关于样本transform中ResizeImage的问题

### ISSUE THREAD

**Issue by scissorsf** [PaddlePaddle/PaddleDetection#2655]
使用PaddleDetection时，在数据增强ResizeImage算子中，有一个resize_box的bool选项，代码注释中含义为：
`whether resize ground truth bbox annotations.`
其默认值为Fasle。

实际运行时，发现图像进行了缩放，但sample 的gt_bbox属性的值并没有，因此想请问sample 的 gt_bbox属性在计算过程中是一直保持原有值，在计算loss时才进行换算吗？

**Comment by yghstill** [comment]
像rcnn等模型gt_bbox 保持原值，在计算loss时会处理，像yolo、ssd等模型会先将gt_bbox进行归一化，这样就不用再进行缩放。resize_box这个选项目前只在SOLOv2中用到了。
在最新release/2.0分支的动态图模型中，我们统一了数据预处理，resize时，所有GT信息都会进行缩放。

**Comment by yghstill** [comment]
像rcnn等模型gt_bbox 保持原值，在计算loss时会处理，像yolo、ssd等模型会先将gt_bbox进行归一化，这样就不用再进行缩放。resize_box这个选项目前只在SOLOv2中用到了。
在最新release/2.0分支的动态图模型中，我们统一了数据预处理，resize时，所有GT信息都会进行缩放。

**Comment by scissorsf** [comment]
谢谢🙂
