### ISSUE TITLE
可以请大佬帮忙复现一下问题吗

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2659]
用检测库的模型yolov3_resnet50vd_dcn_db_iouloss，训练自己的数据集，然后进行模型剪裁，无论剪裁哪个层，一个层或多个层，都是没反应，等了很久很久（我随便输入了几个层，随便输入的剪裁率），敲回车什么的都没反应，无奈ctrl+z退出了，不知道是不是只有我有这个问题啊，以上是基于AIstudio实验的。在我电脑本地，做同样的实验，也是等待很久，但有一次在终端敲回车，程序突然有反应，出现了 Done creating index等等，然后紧接着爆显存。希望大佬帮帮忙
![QQ图片20210416164202](https://user-images.githubusercontent.com/73452319/114997945-00953a80-9ed3-11eb-9692-e80ead3713fe.png)

**Comment by yghstill** [comment]
@guotongjian 欢迎反馈，静态图下模型剪裁启动比较慢，这个我们看下如何优化，欢迎体验最新release/2.0分支动态图slim功能，剪裁等启动都非常快：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/configs/slim

**Comment by guotongjian** [comment]
> @guotongjian 欢迎反馈，静态图下模型剪裁启动比较慢，这个我们看下如何优化，欢迎体验最新release/2.0分支动态图slim功能，剪裁等启动都非常快：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/configs/slim

好的谢谢
