### ISSUE TITLE
训练maskrcnn_res50_rpn时出错

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/PaddleDetection#266]
![image](https://user-images.githubusercontent.com/26462054/75330952-e2c6d980-58bc-11ea-8d91-42ac1de9942e.png)

loss出现nan的情况

**Comment by jerrywgz** [comment]
对loss出现nan的情况有如下几种方法可以尝试：
1. Paddle检测库中开源的模型配置是八卡对应的学习率，如果你使用的是单卡，对应学习率需要调整至原学习率的八分之一，其他卡数也需要按比例进行调整
2. 如果你使用的是非coco数据集，需要确认数据类别是否加上了背景类，例如，coco数据集的类别数为80，在mask-rcnn中使用的num_classes就是81（增加一类背景类）
3. 建议尝试使用coco数据集上训练好的开源模型对你的模型进行finetune，具体模型链接参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/MODEL_ZOO_cn.md； finetune的方法可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md 。这样能更快收敛并获得更好的效果
