### ISSUE TITLE
关于 autoaugment_util 中的 rotate 问题

### ISSUE THREAD

**Issue by scissorsf** [PaddlePaddle/PaddleDetection#2679]
在学习和使用 autoaugment 工具中的 rotate 时，发现其定义了"Rotate_bbox"策略，其过程如下：

1. 设定概率 prob 以及角度 degrees；
2. 通过 PIL 库的rotate函数直接对图像进行旋转；
3. 通过自定义的 _rotate_bbox 函数旋转 gt_bbox。

如果上述理解没有错误的话，想请问几个问题：

1. autoaugment_utils.py文件1473行定义的_apply_func_with_prob中，似乎没有使用到prob参数，而是默认为 0.5；
2. 使用PIL库的rotate函数不会对图像进行缩放，因此旋转后会剪裁而损失部分图像，若此时有gt_bbox 落在该被剪裁掉的区域内，该如何处理gt_bbox？

**Comment by liuhuiCNN** [comment]
感谢反馈，这个地方我们再确认一下，谢谢~
