### ISSUE TITLE
训练开始时，随机出现SIGSEGV，与opencv无关

### ISSUE THREAD

**Issue by barry2025** [PaddlePaddle/PaddleDetection#268]
版本：release/0.1；
commit id:  e5af23e7f1b64c9f8e6a9ddf3088d0c74595a13b
训练脚本：
![image](https://user-images.githubusercontent.com/20043808/75413397-5ff75a80-5960-11ea-98c4-4f5cf05eac9d.png)
运行100次，在第17次出现SIGSEGV，不稳定复现：
![image](https://user-images.githubusercontent.com/20043808/75413355-40603200-5960-11ea-9666-f859d20d4743.png)

**Comment by willthefrog** [comment]
could you please take a look at this? @heavengate

**Comment by heavengate** [comment]
您好，麻烦问下您那边的paddle版本是哪个版本，另外ppdet的release/0.2已经发布，后面可以切换release/0.2版本

**Comment by barry2025** [comment]
使用1.6.1和1.6.3目前都出现过。我先试下release/0.2，多谢

**Comment by heavengate** [comment]
1.6版本确实有cuDNN conv随机挂的问题，1.7.0已经发布到了PyPi，可以安装1.7.0试下

**Comment by barry2025** [comment]
1.7.0版本也会出现，请问下这个确定是跟paddle版本有关吗？

**Comment by barry2025** [comment]
![image](https://user-images.githubusercontent.com/20043808/75540001-2dc82480-5a56-11ea-9b92-8a6abfe44b62.png)
新的paddle给出来的错误信息添加了检查是否关闭paddle进程

**Comment by heavengate** [comment]
看着是conv cuDNN的问题，应该只会在训练中出现，如果不影响速度的话可以在调用`fluid.layers.conv2d`的接口设置参数`use_cudnn=False`，paddle原生实现的conv和cudnn实现速度应该相差不大

**Comment by heavengate** [comment]
> 看着是conv cuDNN的问题，应该只会在训练中出现，如果不影响速度的话可以在调用`fluid.layers.conv2d`的接口设置参数`use_cudnn=False`，paddle原生实现的conv和cudnn实现速度应该相差不大

模型构建代码集中在`ppdet/modeling`目录下，一般由`backbone`和`head`两部分构成，可在对应目录下找到构建脚本修改
conv cuDNN报错问题我们再跟进下

**Comment by barry2025** [comment]
目前测试cudnn关闭之后，没有中断了，但是目前性能差异明显。P4上 yolov3跑voc数据集，单卡batch_size=8，打开cudnn之后是0.6s/iter，关闭之后是1.s/iter
关闭：
![image](https://user-images.githubusercontent.com/20043808/75867497-aa397980-5e41-11ea-9b1f-99fb771f37fa.png)
打开：
![image](https://user-images.githubusercontent.com/20043808/75868367-e6b9a500-5e42-11ea-8e81-a99b10e78cc5.png)

请问下这个时间差异是正常的吗？

**Comment by heavengate** [comment]
> 目前测试cudnn关闭之后，没有中断了，但是目前性能差异明显。P4上 yolov3跑voc数据集，单卡batch_size=8，打开cudnn之后是0.6s/iter，关闭之后是1.s/iter
> 关闭：
> ![image](https://user-images.githubusercontent.com/20043808/75867497-aa397980-5e41-11ea-9b1f-99fb771f37fa.png)
> 打开：
> ![image](https://user-images.githubusercontent.com/20043808/75868367-e6b9a500-5e42-11ea-8e81-a99b10e78cc5.png)
> 
> 请问下这个时间差异是正常的吗？

应该不至于差别这么大，yolo模型模型速度瓶颈在CPU上数据预处理，可以试下`configs/yolov3_reader.py`里`TrainReader.worker_num`调大一些，比如说16试下。
