### ISSUE TITLE
剪裁问题

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2682]
想问下，剪裁报错The weights have been pruned once.
这是什么原因，如何解决呢

**Comment by liuhuiCNN** [comment]
请问您用的paddle版本，paddledeteciton版本是多少呢？

**Comment by guotongjian** [comment]
> 请问您用的paddle版本，paddledeteciton版本是多少呢？

paddle2.0.1，paddledetection2.0rc

**Comment by yghstill** [comment]
@guotongjian 麻烦发一下运行的命令

**Comment by guotongjian** [comment]
> @guotongjian 麻烦发一下运行的命令

`python slim/prune/prune.py -c configs/dcn/mymodel.yml  \
--pruned_params "conv1_1_weights,conv1_2_weights,res2a_branch2a_weights,res2a_branch2b_weights,res2b_branch2a_weights,res2b_branch2b_weights,res2c_branch2a_weights,res2c_branch2b_weights,res3a_branch2a_weights,res3a_branch2b_weights,res3b_branch2a_weights,res3b_branch2b_weights,res3c_branch2a_weights,res3c_branch2b_weights,res3d_branch2a_weights,res3d_branch2b_weights,res4a_branch2a_weights,res4a_branch2b_weights,res4b_branch2a_weights,res4b_branch2b_weights,res4c_branch2a_weights,res4c_branch2b_weights,res4d_branch2a_weights,res4d_branch2b_weights,res4e_branch2a_weights,res4e_branch2b_weights,res4f_branch2a_weights,res4f_branch2b_weights,yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights,yolo_block.0.1.1.conv.weights,yolo_block.0.2.conv.weights,yolo_block.0.tip.conv.weights,yolo_transition.0.conv.weights,yolo_block.1.0.0.conv.weights,yolo_block.1.0.1.conv.weights,yolo_block.1.1.0.conv.weights,yolo_block.1.1.1.conv.weights,yolo_block.1.2.conv.weights,yolo_block.1.tip.conv.weights,yolo_transition.1.conv.weights,yolo_block.2.0.0.conv.weights,yolo_block.2.0.1.conv.weights,yolo_block.2.1.0.conv.weights,yolo_block.2.2.conv.weights,yolo_block.2.tip.conv.weights  \
--pruned_ratios="0.3,0.3,0.3,0.5,0.6,0.4,0.8,0.8,0.9,0.9,0.7,0.9,0.4,0.5,0.8,0.8,0.9,0.8,0.6,0.5,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.7,0.2,0.5,0.2,0.2,0.3,0.1,0.6,0.1,0.4,0.4,0.5,0.5,0.8,0.7,0.1,0.5,0.4,0.6,0.5" \
 -o weights=output/mymodel/best_model \
--eval \
--prune_criterion=geometry_median`
这是我的命令，请大佬指教

**Comment by guotongjian** [comment]
@wanghaoshuang  @qingqing01 my dear大佬，能帮忙看看吗
