### ISSUE TITLE
infer with custom dataset - can i get a output file with json or xml

### ISSUE THREAD

**Issue by sukkyusun** [PaddlePaddle/PaddleDetection#2696]
python -u tools/infer.py -c configs/ppyolo/ppyolo.yml --infer_dir=paddle_test --output_dir=infer_output --draw_threshold=0.5 -o weights=output/ppyolo/best_model

following output contains only boxed labeled image.

can i get a output label  file with json or xml

**Comment by qingqing01** [comment]
@sukkyusun 

1. In release/2.0-rc branch (static graph traning/inference),  not support to output bbox into json or xml file, maybe you need to change code  in 

https://github.com/PaddlePaddle/PaddleDetection/blob/effbad5db4f1a046dd63cdf14ae49412ba4a836f/tools/infer.py#L217


2. In release/2.0 branch (dynamic graph training/inference) ， support to output bbox into txt file, 

https://github.com/PaddlePaddle/PaddleDetection/blob/372016552bb10f0459d0db80896ec71c333a01bd/tools/infer.py#L78


If you have used 2.0-rc branch well, better to follow 1 to change code by yourself.
