### ISSUE TITLE
Paddle大佬们，请教一下，Windows怎么指定infer时显卡，GPU-0是Intel，GPU-1是NVIDIA

### ISSUE THREAD

**Issue by guoyangji** [PaddlePaddle/PaddleDetection#2699]
官方代码启用GPU时，place = fluid.CUDAPlace(0) if cfg.use_gpu else fluid.CPUPlace()，我使用fluid.CUDAPlace(1)报错：
E0419 15:31:42.244616 11240 pybind.cc:1413] Invalid CUDAPlace(1), must inside [0, 1), because GPU number on your machine is 1

**Comment by guoyangji** [comment]
release/2.0-rc的代码

**Comment by qingqing01** [comment]
@kwok1993 报错信息是机器上只有一个GPU。"GPU-0是Intel" 是Intel的集成显卡还是啥？ 

```
nvidia-smi
```

显示几张卡呢？
