### ISSUE TITLE
在Windows10测试环境运行C++ inference失败

### ISSUE THREAD

**Issue by ff3141044702** [PaddlePaddle/PaddleDetection#27]
使用Windows10专业版+VS2015+cuda9.2+cudnn7.6.1+paddlepaddle 1.5.2的开发环境中，编译运行C++ inference程序，可以使用CPU模式（因为开发环境GPU安装失败）进行预测，但是在Windows10专业版+vc2015(update3)运行时库+.Net 4.5(4.6)运行时库的测试环境中，不管使用CPU还是GPU均报0xc000007b错误。

**Comment by joey12300** [comment]
请问一下你是不是把所有依赖的东西（cuda相关的运行库、预测库）都拷到新的测试环境中，并且保持新环境中库的路径与你编译时指定的路径保持一致呢？

**Comment by sjtubinlong** [comment]
能否提供一下，详细的错误栈信息 @ff3141044702

**Comment by ff3141044702** [comment]
你好：
&nbsp; &nbsp; &nbsp; 非常感谢你的回复。但是你说的错误栈信息怎么查？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Bin Long"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 下午4:33
收件人:&nbsp;"PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送:&nbsp;"ff"<3141044702@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 在Windows10测试环境运行C++ inference失败 (#27)




能否提供一下，详细的错误栈信息 @ff3141044702

**Comment by ff3141044702** [comment]
你好：
&nbsp; &nbsp; &nbsp; 感谢你的回复。我在测试机上新装的Windows 10系统，然后安装的和开发机上相同的cuda9.2+cudnn，路径都是默认的，和开发机相同；然后是VC2015 C++ 运行库，预测库使用的是相对路径，放在和主程序相同的位置，这个设置也是和开发机是一样的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jack Zhou"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 上午10:50
收件人:&nbsp;"PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送:&nbsp;"ff"<3141044702@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 在Windows10测试环境运行C++ inference失败 (#27)




请问一下你是不是把所有依赖的东西（cuda相关的运行库、预测库）都拷到新的测试环境中，并且保持新环境中库的路径与你编译时指定的路径保持一致呢？

**Comment by sjtubinlong** [comment]
@ff3141044702 `0xc000007b`这个错误通常是缺乏动态库dll文件引起的，这里猜测和cuda和cudnn的安装有关。麻烦提供一下这些信息做参考：
1. cuda和cudnn的lib文件的路径, 以及目录下的文件列表的一个截图
2. 你详细的编译和执行命令

非常感谢

**Comment by ff3141044702** [comment]
应该是缺msvcp140.dll、opencv_world346.dll等文件造成的，把这些文件复制过去以后能够运行CPU版本的代码。
