### ISSUE TITLE
develop版本训练报错

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleDetection#2701]
develop版本动态图报错，No module named 'paddle.fluid.dataloader.collate'，请问怎么解决？

**Comment by jerrywgz** [comment]
develop版本需要依赖paddle dev版本，可以从这里下载https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by qingqing01** [comment]
@lhy823436493 您可以使用 release/2.0分支，依赖Paddle 2.0版本

**Comment by Monday-Leo** [comment]
develop安装完了，Windows下面还是报错，release/2.0没有ppyolov2，所以想用develop完全的动态图框架

**Comment by qingqing01** [comment]
@lhy823436493 

release/2.0有 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/ppyolo/README_cn.md PP-YOLOv2的。

Windows下面什么问题？

**Comment by Monday-Leo** [comment]
Windows下面develop版本报错No module named 'paddle.fluid.dataloader.collate'

**Comment by Fly-hub** [comment]
报错解决方法是将paddle改成2.1版本，我使用2.0版本就报这个错改为2.1就好了

**Comment by Fly-hub** [comment]
我是在aistudio平台上运行的
