### ISSUE TITLE
C++端预测部署，linux编译问题

### ISSUE THREAD

**Issue by sdnusqy-art** [PaddlePaddle/PaddleDetection#2704]
C++端预测部署， 编译安装了各种库之后，还是有opencv找不到ffmpeg的相关接口问题， 是ffmpeg版本问题？ 还是其他问题

../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `avformat_close_input@LIBAVFORMAT_FFMPEG_56'
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `sws_scale@LIBSWSCALE_FFMPEG_3'
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `av_guess_codec@LIBAVFORMAT_FFMPEG_56'
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `av_guess_format@LIBAVFORMAT_FFMPEG_56'
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `av_guess_sample_aspect_ratio@LIBAVFORMAT_FFMPEG_56'
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `avcodec_get_context_defaults3@LIBAVCODEC_FFMPEG_56'
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `avcodec_flush_buffers@LIBAVCODEC_FFMPEG_56'
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `av_codec_get_tag@LIBAVFORMAT_FFMPEG_56'
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `avformat_get_mov_video_tags@LIBAVFORMAT_FFMPEG_56'
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `avformat_open_input@LIBAVFORMAT_FFMPEG_56'
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `avformat_alloc_context@LIBAVFORMAT_FFMPEG_56'
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `avcodec_decode_video2@LIBAVCODEC_FFMPEG_56'
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `av_image_fill_arrays@LIBAVUTIL_FFMPEG_54'
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `av_rescale_q@LIBAVUTIL_FFMPEG_54'
../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_videoio.so.3.4.6: undefined reference to `avcodec_find_decoder_by_name@LIBAVCODEC_FFMPEG_56'

![image](https://user-images.githubusercontent.com/73977336/115325788-d5eefe80-a1be-11eb-9aac-23ca5b6d2db6.png)

**Comment by sdnusqy-art** [comment]
搞定了， 官方提供的opencv是ubuntu预编译版本，如果其他系统需要自己编译opencv，比如centos如果用了官方的opencv就会有以上错误

**Comment by pphgood** [comment]
> 
我是ubuntu版本但是也遇到了和你一样的错误

**Comment by pphgood** [comment]
> 搞定了， 官方提供的opencv是ubuntu预编译版本，如果其他系统需要自己编译opencv，比如centos如果用了官方的opencv就会有以上错误
你好，请问怎么修改配置文件使用自己编译的opencv
