### ISSUE TITLE
SSD-MobileNet_v1量化动转静导出模型时出错

### ISSUE THREAD

**Issue by xry644854073** [PaddlePaddle/PaddleDetection#2715]
ValueError:
We don't support to define layer with parameters in the function decorated by @declarative.
Because that will re-defined parameters every time when you run the function.
But we found parameter(conv2d_47.tmp_0.scale_0) was created in the decorated function.
Please define the layer with parameters in __init__ function.
您好 我按照模型压缩里快速开始的教程对SSD-MobileNet_v1训练自己训练集进行量化，在动转静导出模型时报错
![image](https://user-images.githubusercontent.com/56854540/115401874-72e08480-a21d-11eb-9e00-f32e95b19da4.png)

**Comment by yghstill** [comment]
@xry644854073 请安装最新paddlepaddle develop版本再训练哦，量化导出的问题在develop下才修复好了：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html#anchor-0

**Comment by zhang-xufeng** [comment]
> @xry644854073 请安装最新paddlepaddle develop版本再训练哦，量化导出的问题在develop下才修复好了：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html#anchor-0

同样的问题，换了develop版本还是不行，windows环境 pip develop 安装，但是paddle版本还是2.0.2 linx版本应该是2.1，是否是windows给出的安装包没更新
