### ISSUE TITLE
mobilnet提高精度

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleDetection#2717]
请问Mobile net网络能否用DCV_v2来提高模型检测精度？

**Comment by jerrywgz** [comment]
这里不建议用dcn的方式来提升mobilenet的精度，这个backbone本身是基于移动端的轻量级网络，而dcn的计算对移动端来说并不友好；可以尝试其他提高精度的方式

**Comment by Monday-Leo** [comment]
请问有哪些方式可以提高精度，小白求教！

**Comment by jerrywgz** [comment]
可以尝试增加数据预处理，使用sync_bn，ema，增大batch size等方式提升精度
