### ISSUE TITLE
coco数据集格式如何检测特定类别的目标

### ISSUE THREAD

**Issue by hengai** [PaddlePaddle/PaddleDetection#272]
用飞桨提供的预训练模型，采用coco数据集，如何只检测特定类别的目标，而不是默认的80类？

**Comment by heavengate** [comment]
1. 如果不想重新训练，需要该类别是COCO的80lei之一，用已发布的模型预测后过滤结果保留你需要的那一类
2. 如果有那特定类别的数据，可以用该数据集重新训练迁移学习，参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/TRANSFER_LEARNING.md

**Comment by hengai** [comment]
用已发布的模型预测后过滤结果：能否以某一类为例，用代码进行示例呢？

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/eb7b0ddd7dc6901357c8fb9e92c9ef7bafd0b607/ppdet/utils/coco_eval.py#L215   这里`clsid`不是你指定的id的话continue就可以了

**Comment by hengai** [comment]
请问如何统计每一类的个数呢？

**Comment by heavengate** [comment]
您好，当前问题长时间没有回复，先关闭当前issue，如果还有问题，可以reopen此issue~
