### ISSUE TITLE
paddleslim

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2721]
`python slim/prune/prune.py -c configs/dcn/yolo3_r50vd_dcn_iou_loss.yml \ --pruned_params "conv1_1_weights,conv1_2_weights,res2a_branch2a_weights,res2a_branch2b_weights,res2b_branch2a_weights,res2b_branch2b_weights,res2c_branch2a_weights,res2c_branch2b_weights,res3a_branch2a_weights,res3a_branch2b_weights,res3b_branch2a_weights,res3b_branch2b_weights,res3c_branch2a_weights,res3c_branch2b_weights,res3d_branch2a_weights,res3d_branch2b_weights,res4a_branch2a_weights,res4a_branch2b_weights,res4b_branch2a_weights,res4b_branch2b_weights,res4c_branch2a_weights,res4c_branch2b_weights,res4d_branch2a_weights,res4d_branch2b_weights,res4e_branch2a_weights,res4e_branch2b_weights,res4f_branch2a_weights,res4f_branch2b_weights,yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights,yolo_block.0.1.1.conv.weights,yolo_block.0.2.conv.weights,yolo_block.0.tip.conv.weights,yolo_transition.0.conv.weights,yolo_block.1.0.0.conv.weights,yolo_block.1.0.1.conv.weights,yolo_block.1.1.0.conv.weights,yolo_block.1.1.1.conv.weights,yolo_block.1.2.conv.weights,yolo_block.1.tip.conv.weights,yolo_transition.1.conv.weights,yolo_block.2.0.0.conv.weights,yolo_block.2.0.1.conv.weights,yolo_block.2.1.0.conv.weights,yolo_block.2.2.conv.weights,yolo_block.2.tip.conv.weights \ --pruned_ratios="0.3,0.3,0.3,0.5,0.6,0.4,0.8,0.8,0.9,0.9,0.7,0.9,0.4,0.5,0.8,0.8,0.9,0.8,0.6,0.5,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.7,0.2,0.5,0.2,0.2,0.3,0.1,0.6,0.1,0.4,0.4,0.5,0.5,0.8,0.7,0.1,0.5,0.4,0.6,0.5" \ -o weights=output/mymodel/best_model \ --eval \ --prune_criterion=geometry_median`
这是我的运行命令，第一次试验：等了40分钟，剪裁启动，打印剪裁信息剪第一层conv1_1_weghts，接着报错`The weights have been pruned`。第二次试验：将con1_1_weights删掉，又等了40分钟，剪裁启动，打印剪裁信息剪第一个conv1_2_weights，接着报错`The weights have been pruned`。第三次试验：将前面骨干网络的参数都删掉，只剪yolo层，等40分钟剪裁启动，然后还是报错`The weights have been pruned`，翻了一下源码，这个报错的原因是权重里没有东西？跪求大佬啊、神啊，救救孩子吧

**Comment by yghstill** [comment]
@guotongjian 先加上--print_params参数打印网络中所有层的名称等信息，然后选择网络中存在的conv的name。yolo算法一般剪裁head部分，也可以进行敏感度分析，选择更合适的层：https://github.com/PaddlePaddle/PaddleDetection/blob/master/slim/sensitive/README.md
