### ISSUE TITLE
AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'sync_batch_norm'

### ISSUE THREAD

**Issue by nblib** [PaddlePaddle/PaddleDetection#2723]
# env
* Paddle >= 2.0.0
* PaddleDetection branch release/2.0
* Win10
* CPU
* model ppyolov2

**Comment by jerrywgz** [comment]
Now ppyolov2 is only supports on GPU and you could change norm_type to bn if you want to try ppyolov2 on CPU.

**Comment by baoxin1100** [comment]
I got the wrong output if I change norm_type to bn, I test the ppyolo and ppyolov2, the output is very confused, do you know why?

**Comment by baoxin1100** [comment]
> I got the wrong output if I change norm_type to bn, I test the ppyolo and ppyolov2, the output is very confused, do you know why?

I test the code in my macbookpro where no gpu, Paddle == 2.0.2

**Comment by baoxin1100** [comment]
> I got the wrong output if I change norm_type to bn, I test the ppyolo and ppyolov2, the output is very confused, do you know why?

I guess some other config need be modified except norm_type? beg your apply

**Comment by baoxin1100** [comment]
> Now ppyolov2 is only supports on GPU and you could change norm_type to bn if you want to try ppyolov2 on CPU.

I got the wrong output if I change norm_type to bn, I test the ppyolo and ppyolov2, the output is very confused, I guess some other config need be modified except norm_type? beg your apply

**Comment by kaikaizhu** [comment]
I have the same problem. Have you solved it？@baoxin1100  @nblib

**Comment by hablee** [comment]
我也有同样的问题，虽然我用的不是ppyolov2，用的是yolov3_mobilenet_v1_roadsign.yml
