### ISSUE TITLE
yolov3_enhance_reader.yml中的is_scale参数问题

### ISSUE THREAD

**Issue by thzyyx** [PaddlePaddle/PaddleDetection#2725]
configs/dcn/yolov3_enhance_reader.yml中使用is_scale为false会导致图像不会进行归一化，而使用的mean和std明显是归一化后的（mean: [0.485, 0.456, 0.406]      std: [0.229, 0.224, 0.225]），这种预处理方法处理过的图像像素值超过255，这种做法是否合理？还是说本身就这么设计的？

**Comment by jerrywgz** [comment]
yolov3_enhance_reader中的配置是为了对齐预训练模型中使用的预处理方式（本身确实存在问题，但是对结果没有影响）
另外可以尝试使用ppyolo模型，效果要优于yolov3_enhance模型

**Comment by thzyyx** [comment]
感谢@jerrywgz
