### ISSUE TITLE
关于新版本optimizer

### ISSUE THREAD

**Issue by lmk123568** [PaddlePaddle/PaddleDetection#2726]
optimizer_1x 代表什么意思，不同文件的base中1x epoch不一样，请问1x具体代表什么意思呢，如果能回复将不胜感激

**Comment by jerrywgz** [comment]
optimizer_1x通常表示为12epoch，ppyolo中1x对应的epoch为405，这里我们修改下名称以便于理解

**Comment by lmk123568** [comment]
> 
> 
> optimizer_1x通常表示为12epoch，ppyolo中1x对应的epoch为405，这里我们修改下名称以便于理解

thanks for your response

**Comment by lmk123568** [comment]
> 
> 
> optimizer_1x通常表示为12epoch，ppyolo中1x对应的epoch为405，这里我们修改下名称以便于理解

您好，请问ppyolov2论文什么时候出来

**Comment by heavengate** [comment]
你好，鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen此issue~
