### ISSUE TITLE
关于voc格式的yaml文件

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleDetection#2727]
你好，paddle detection支持voc和coco格式的数据集，但是voc的yaml配置文件却很少，请问如何coco格式yaml配置文件变成voc格式也能使用的呢？我现在使用动态图版的faster_rcnn，以faster_rcnn_r50_fpn_1x_coco.yaml为例，我修改了_BASE_中的'../datasets/coco_detection.yml'为'../datasets/voc.yml'，出现了如下错误：
![CI3NQ@%A D3LA_S4Z$Y3D5D](https://user-images.githubusercontent.com/71364549/115557585-6bd07980-a2e4-11eb-9d37-bbb1c2107fef.png)

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/2732
可以按照这里的pr进行修改

**Comment by netidol** [comment]
> 你好，paddle detection支持voc和coco格式的数据集，但是voc的yaml配置文件却很少，请问如何coco格式yaml配置文件变成voc格式也能使用的呢？我现在使用动态图版的faster_rcnn，以faster_rcnn_r50_fpn_1x_coco.yaml为例，我修改了_BASE_中的'../datasets/coco_detection.yml'为'../datasets/voc.yml'，出现了如下错误：
> ![CI3NQ@%A D3LA_S4Z$Y3D5D](https://user-images.githubusercontent.com/71364549/115557585-6bd07980-a2e4-11eb-9d37-bbb1c2107fef.png)

哈哈，我写了一个coco2voc的工具，需要可以交流
