### ISSUE TITLE
PaddlePaddle2.0.2版本，No module named 'paddle.fluid.dataloader.collate'问题

### ISSUE THREAD

**Issue by CharlesYXW** [PaddlePaddle/PaddleDetection#2728]
您好！我今天刚刚安装了PaddlePaddle2.0.2版本，PaddleDetection也是最新的版本，按照教程进行测试的时候报了如下错误，无论是在默认文件夹下还是static文件夹下都会出现 No module named 'paddle.fluid.dataloader.collate'，请问该如何解决呢？
 python tools/infer.py -c configs/ppyolo/ppyolo.yml -o use_gpu=true weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams --infer_img=demo/000000014439.jpg
/home/amax/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/utils/cpp_extension/extension_utils.py:461: UserWarning: Not found CUDA runtime, please use `export CUDA_HOME= XXX` to specific it.
  "Not found CUDA runtime, please use `export CUDA_HOME= XXX` to specific it."
Traceback (most recent call last):
  File "tools/infer.py", line 59, in <module>
    raise e
  File "tools/infer.py", line 39, in <module>
    from ppdet.core.workspace import load_config, merge_config, create
  File "/home/amax/anaconda3/envs/paddle/lib/python3.6/site-packages/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/home/amax/anaconda3/envs/paddle/lib/python3.6/site-packages/ppdet/data/__init__.py", line 17, in <module>
    from . import reader
  File "/home/amax/anaconda3/envs/paddle/lib/python3.6/site-packages/ppdet/data/reader.py", line 28, in <module>
    from paddle.fluid.dataloader.collate import default_collate_fn
ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'

**Comment by CharlesYXW** [comment]
PaddleDetection版本为2.0

**Comment by jerrywgz** [comment]
PaddleDetection develop分支需要依赖PaddlePaddle develop版本；可以切换PaddleDetection到release/2.0分支

**Comment by CharlesYXW** [comment]
我安装的就是
PaddleDetection release/2.0 版本呀





------------------ 原始邮件 ------------------
发件人: wangguanzhong ***@***.***&gt;
发送时间: 2021年4月22日 02:05
收件人: PaddlePaddle/PaddleDetection ***@***.***&gt;
抄送: CharlesYXW ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/PaddleDetection] PaddlePaddle2.0.2版本，No module named 'paddle.fluid.dataloader.collate'问题 (#2728)

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/ppdet/data/reader.py#L27
在2.0分支下是没有from paddle.fluid.dataloader.collate import default_collate_fn 的，你是不是在develop分支使用了setup.py install然后再切到了2.0分支

**Comment by CharlesYXW** [comment]
我是按照教程的第一种方法直接通过pip安装的
# pip安装paddledet pip install paddledet==2.0.0 -i https://pypi.tuna.tsinghua.edu.cn/simple # 下载使用源码中的配置文件和代码示例 git clone https://github.com/PaddlePaddle/PaddleDetection.git cd PaddleDetection






------------------ 原始邮件 ------------------
发件人: wangguanzhong ***@***.***&gt;
发送时间: 2021年4月22日 10:27
收件人: PaddlePaddle/PaddleDetection ***@***.***&gt;
抄送: CharlesYXW ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/PaddleDetection] PaddlePaddle2.0.2版本，No module named 'paddle.fluid.dataloader.collate'问题 (#2728)

**Comment by yghstill** [comment]
@CharlesYXW 从https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html  这里安装最新的develop PaddlePaddle版本再试下吧

**Comment by SovereignRemedy** [comment]
亲测 pip install paddledet==2.0.0 -i https://pypi.tuna.tsinghua.edu.cn/simple  源里上传的包不是release/2.0分支的  建议修复一下

**Comment by ilem777** [comment]
我建议您还是新建一个环境，按要求重新安装，不然你重装时卸载又不卸干净，反反复复安装都会失败的。

**Comment by heavengate** [comment]
您好，感谢反馈~ 之前发布版本包有问题，更新发布了2.0.1，自测通过并且安装文档也做了更新，您可以尝试一下`pip uninstall paddledet`然后重新`pip install paddledet==2.0.1`试下
修复PR： https://github.com/PaddlePaddle/PaddleDetection/pull/2755
