### ISSUE TITLE
关于新版本剪裁的问题

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2729]
新版本，剪裁命令为`python tools/train.py -c configs/{MODEL.yml} --slim_config configs/slim/{SLIM_CONFIG.yml}`
我想做的事：**训练自己的模型然后剪裁**。
流程：按理说，**先训练好我的模型**，得到一个权重文件，**然后再用剪裁命令剪裁**这个权重文件。
**Question**:1、现在这个命令的意思就是一步完成了，**直接得到剪裁后的权重吗**？
                2、还是说我需要**先训练好一个模型**，**然后再把训练得到的权重来当做剪裁的预训练权重**，**再运行这个命令**？
               3、因为我在看**slim里的配置文件**时，yml文件里需要填写**剪裁层的名字和剪裁率**，这个应当是先训练好一个模型，然后打印 
                    其中的名称得到的吧。想知道新版本的剪裁命令，中间蕴含的是怎样一个流程呢？
**谢谢百度大佬**

**Comment by yghstill** [comment]
@guotongjian 
1.是一步完成，直接得到剪裁后权重
2.先训好模型得到权重，然后再作为预训练模型进行剪裁
3.剪裁的层可以通过print_params: True来打印后选择要剪裁的层

**Comment by guotongjian** [comment]
> @guotongjian
> 1.是一步完成，直接得到剪裁后权重
> 2.先训好模型得到权重，然后再作为预训练模型进行剪裁
> 3.剪裁的层可以通过print_params: True来打印后选择要剪裁的层

好的谢谢
