### ISSUE TITLE
ppyolo_v2评估验证集出错，最新版本

### ISSUE THREAD

**Issue by ybc-ybc** [PaddlePaddle/PaddleDetection#2733]
```
2021-04-22 11:34:40,128 - ERROR - DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 137, in <module>
    main()
  File "tools/train.py", line 133, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/apdet/ppdet/engine/trainer.py", line 304, in train
    self._eval_with_loader(self._eval_loader)
  File "/apdet/ppdet/engine/trainer.py", line 312, in _eval_with_loader
    for step_id, data in enumerate(loader):
  File "/apdet/ppdet/data/reader.py", line 216, in __next__
    data = next(self.loader)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 779, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)
```

训练一轮后开始评估，出错；
 python tools/train.py -c configs/ayml/my.yml --eval
单独提取模型评估也是同样的错误；

只进行训练没有问题

**Comment by yghstill** [comment]
@ybc-ybc 是自定义数据集吗？是COCO格式吗？ 看报错信息是EvalReader或者EvalDataset设置错误，可以发下相关配置信息吗

**Comment by ybc-ybc** [comment]
> @ybc-ybc 是自定义数据集吗？是COCO格式吗？ 看报错信息是EvalReader或者EvalDataset设置错误，可以发下相关配置信息吗

voc格式自定义的训练集，把coco的yml换成voc的，其他的没动：
_BASE_: [
  './voc.yml',
  './runtime.yml',
  './ppyolov2_r50vd_dcn.yml',
  './optimizer_365e.yml',
  './ppyolov2_reader.yml',
]

worker_num: 4
TrainReader:
  inputs_def:
    num_max_boxes: 100
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 100}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]], downsample_ratios: [32, 16, 8]}
  batch_size: 8
  shuffle: true
  drop_last: true
  mixup_epoch: 25000
  use_shared_memory: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 8
  drop_empty: false

**Comment by yghstill** [comment]
@ybc-ybc fixed in #2720 ，再更新下代码试下吧

**Comment by ybc-ybc** [comment]
> @ybc-ybc fixed in #2720 ，再更新下代码试下吧

错误依旧，应该不是数据集问题，把训练集和验证集交换下，训练没问题，验证就出错

**Comment by yghstill** [comment]
@ybc-ybc 好的，之前修复的不全，这个是已知问题，修复后会告知你，谢谢反馈

**Comment by Simon-liusheng** [comment]
出现了同样的错误，静静等待

**Comment by hei898** [comment]
我也是，在训练的时候和你的错误一样

**Comment by heavengate** [comment]
`worker_num`设置为0看下会报错么

**Comment by wangxinxin08** [comment]
请参考这个PR:https://github.com/PaddlePaddle/PaddleDetection/pull/2731 进行修改
