### ISSUE TITLE
deformable conv layer?

### ISSUE THREAD

**Issue by 2hyes** [PaddlePaddle/PaddleDetection#2734]
I read pp-yolo paper. 

> we only replace 3 × 3 convolution layers in the last stage with DCNs. We denote this modified backbone as ResNet50-vd-dcn, and the output of stage 3, 4 and 5 as C3, C4, C5.

> we replace the 3×3 convolutional layer in the last stage of ResNet with deformable convolution layer.

This is what the paper said. And I wonder that you modified the last **_**one** 3x3 conv layer_** to deformable conv layer or the last **_**three** 3x3 conv layer_**(last stage)?

And In which source file can I check this?

**Comment by yghstill** [comment]
@2hyes last one 3x3 conv layer in C3-C5, three in total. Please refer:
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/ppdet/modeling/backbones/resnet.py#L334-L345
