### ISSUE TITLE
请教一个问题：ssd的aspect_ratios如何设置？

### ISSUE THREAD

**Issue by GZHUZhao** [PaddlePaddle/PaddleDetection#2739]
论文中的aspect_ratios = {1,2,3,1/2,1/3}，默认的ssd_mobilenet_v1_voc.yml里的是[[2.], [2., 3.], [2., 3.], [2., 3.], [2., 3.], [2., 3.]]，
我是用了自己的数据集，分析到数据集中的目标的宽/高主要集中于0.8左右，请问如何设置？
还有，配置文件中的2是宽/高 = 2，还是宽/高 = 2和高/宽 = 2两种？，宽/高 = 1:1的呢？
十分感谢您的耐心回答，谢谢！

**Comment by yghstill** [comment]
@GZHUZhao aspect_ratios是高/宽比，在prior_box中默认是1，在ssd只有`1, 2, 3, 1/2, 1/3`这五种，1是默认就包含的，如果aspect_ratios中有[2., 3.]，并且设置flip=True，那么候选框将会做翻转，长宽比就是[ 1/2, 1/3]，配置文件中这五种比例都包含的哈，具体API可以看文档了解下：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/prior_box_cn.html#prior-box

**Comment by GZHUZhao** [comment]
> @GZHUZhao aspect_ratios是高/宽比，在prior_box中默认是1，在ssd只有`1, 2, 3, 1/2, 1/3`这五种，1是默认就包含的，如果aspect_ratios中有[2., 3.]，并且设置flip=True，那么候选框将会做翻转，长宽比就是[ 1/2, 1/3]，配置文件中这五种比例都包含的哈，具体API可以看文档了解下：
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/prior_box_cn.html#prior-box

感谢您的回答，谢谢！
