### ISSUE TITLE
请教新版本问题

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2742]
1、为什么同样的数据，同样的配置文件，新版本跑出来的，map要比旧版本低（iou=0.5下低的太多），coco评价方式总体map低了两个点。而且训练同样的轮数，老版本loss最后降到2点几，新版本只能降到7点几，这是什么原因呢
2、旧版本训练的模型权重放到新版本测试还能用吗，我eval了一下出现一连串的 Redundant weight conv1_1_weights and ignore it。这种类似语句，map评价都是0，请问这是什么原因呢，模型都是一样的。
3、新版本训练好，用`python -u tools/eval.py -c configs/yolov3/model.yml -o weights=output/260.pdparams --classwise`预测，报错如下，网上查了一下，貌似是matplotlib的问题？不加--classwise是可以正常运行的，后又在本地测试，本地windows系统可以正常运行。
![1619140342(1)](https://user-images.githubusercontent.com/73452319/115803718-0b405a00-a414-11eb-8eb2-8e50701fb7c2.jpg)
4、还有个问题，同样的模型，新版本预测30ms，旧版本35ms，这个貌似差距不大哦，应该算正常吧。新版本用bench_mark的话就是30ms，不用bench_Mark要125ms，想问下我们一般评估这个模型推理速度怎么样，是以开启bench_mark的速度算，还是以不开启来算。

**Comment by guotongjian** [comment]
3、新版本训练好，用`python -u tools/eval.py -c configs/yolov3/model.yml -o weights=output/260.pdparams --classwise`预测，报错如下，网上查了一下，貌似是matplotlib的问题？不加--classwise是可以正常运行的
![1619140342(1)](https://user-images.githubusercontent.com/73452319/115803718-0b405a00-a414-11eb-8eb2-8e50701fb7c2.jpg)

**Comment by liuhuiCNN** [comment]
(1) 请问是哪个模型呢？yolo系列部分模型在评估时需要加bias参数，请参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/ppyolo/README_cn.md
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/configs/yolov3
(2) 旧版本、新版本分别是指哪个版本呢？
(3) 如果需要matplotlib画图的话，需要设置 matplotlib 的env，请参考：https://blog.csdn.net/ydyang1126/article/details/77247654
(4) 建议使用bench_mark结果作为速度评价指标

**Comment by guotongjian** [comment]
> (1) 请问是哪个模型呢？yolo系列部分模型在评估时需要加bias参数，请参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/ppyolo/README_cn.md
> https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/configs/yolov3
> (2) 旧版本、新版本分别是指哪个版本呢？
> (3) 如果需要matplotlib画图的话，需要设置 matplotlib 的env，请参考：https://blog.csdn.net/ydyang1126/article/details/77247654
> (4) 建议使用bench_mark结果作为速度评价指标

您好，（1）是yolov3_dcn的模型，未使用bias字段，是参考训练时的eval日志，得出的对比结果。另外，想问一下，loss比较高大概在7点几，这样应该如何去调参呢，loss_xy,loss_obj,loss_iou这三个在2.几，loss_wh，loss_cls在0.几
（2）旧版本是指之前的2.0-beta，2.0-rc的静态图版本，新版本是指刚刚发布的2.0动态图版本。
另外在剪裁时报错，看这个意思是必须用训练的最后一次的模型作为预训练模型？
![1619158796(1)](https://user-images.githubusercontent.com/73452319/115827985-a6025e00-a43f-11eb-8210-c05d3a97e8ab.jpg)
**感谢您的回答**。

**Comment by guotongjian** [comment]
@liuhuiCNN @
