### ISSUE TITLE
S2ANet模型 旋转目标 标注工具有吗

### ISSUE THREAD

**Issue by 1431241631** [PaddlePaddle/PaddleDetection#2746]
旋转目标标注工具

**Comment by liuhuiCNN** [comment]
增加了4点标注转旋转框标注的脚本，请参考PR： https://github.com/PaddlePaddle/PaddleDetection/pull/2724。

**Comment by zouxiaoshi** [comment]
开源免费的工具目前用的最广的是：rolabelimg
https://github.com/cgvict/roLabelImg
在https://github.com/cgvict/roLabelImg/blob/master/libs/pascal_voc_io.py 中有其相应的坐标格式，默认两种，
如果是横向的框，直接是 (xmin,ymin,xmax,ymax)
如果是旋转的框，会是（xc,yc,width,height,angel）
你可以改下这个文件，把坐标格式转换成 (x1,y1,x2,y2,x3,y3,x4,y4) ，【文件里面已经写好函数了，直接用就好了】
然后再利用官方提供的PASCALVOC转COCO的脚本就可以了。
