### ISSUE TITLE
ppyolo_v2 支持批量预测吗

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/PaddleDetection#2752]
ppyolo_v2 支持批量预测吗？

**Comment by qingqing01** [comment]
@zouxiaoshi 

是deploy下面的批量预测吗？ 模型本身支持，代码还没添加，后续会添加下。

**Comment by zouxiaoshi** [comment]
> @zouxiaoshi
> 
> 是deploy下面的批量预测吗？ 模型本身支持，代码还没添加，后续会添加下。

嗯。
好的，多谢。
