### ISSUE TITLE
请教新版本的问题

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2757]
旧版本：2.0beta静态图，新版本：2.0动态图版本
1、为什么同样的数据，同样的配置文件，新版本跑出来的，map要比旧版本低（iou=0.5下低的太多），coco评价方式总体map低了两个点。而且训练同样的轮数，老版本loss最后降到2点几，新版本只能降到7点几，这样应该如何去调参呢，loss_xy,loss_obj,loss_iou这三个在2.几，loss_wh，loss_cls在0.几。
2、旧版本训练的模型权重放到新版本测试还能用吗。
3、在剪裁时报错，看这个意思是必须用训练的最后一次的模型作为预训练模型？
![1619158796(1)](https://user-images.githubusercontent.com/73452319/115827985-a6025e00-a43f-11eb-8210-c05d3a97e8ab.jpg)

**Comment by qingqing01** [comment]
@guotongjian 

您具体是YOLO的那个模型？2.0动态图中是按照epoch数设置的。

> 旧版本训练的模型权重放到新版本测试还能用吗。

旧版本模型，放到新版动态图无法用。 放到2.0的静态图中可以用 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/static 


> 在剪裁时报错，看这个意思是必须用训练的最后一次的模型作为预训练模型？

不是最后一次的模型，任意中间的模型就可以。

**Comment by yghstill** [comment]
@guotongjian 看剪裁报错是没有根据name找到要剪裁的层，在剪裁时，先将slim_config中的print_params设为True打印网络中所有层信息，选取正确的名称。

**Comment by guotongjian** [comment]
> @guotongjian 看剪裁报错是没有根据name找到要剪裁的层，在剪裁时，先将slim_config中的print_params设为True打印网络中所有层信息，选取正确的名称。

您好，我就是先打印然后再选的名称，为什么还是报错呢

**Comment by guotongjian** [comment]
> @guotongjian
> 
> 您具体是YOLO的那个模型？2.0动态图中是按照epoch数设置的。
> 
> > 旧版本训练的模型权重放到新版本测试还能用吗。
> 
> 旧版本模型，放到新版动态图无法用。 放到2.0的静态图中可以用 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/static
> 
> > 在剪裁时报错，看这个意思是必须用训练的最后一次的模型作为预训练模型？
> 
> 不是最后一次的模型，任意中间的模型就可以。

您好，是yolo增强版的模型

**Comment by guotongjian** [comment]
> @guotongjian 看剪裁报错是没有根据name找到要剪裁的层，在剪裁时，先将slim_config中的print_params设为True打印网络中所有层信息，选取正确的名称。

您好，这个报错的意思是必须剪裁所有层吗，也就是必须把所有层的名字都打上去？

**Comment by guotongjian** [comment]
> @guotongjian 看剪裁报错是没有根据name找到要剪裁的层，在剪裁时，先将slim_config中的print_params设为True打印网络中所有层信息，选取正确的名称。

您好，这个报错的意思是必须剪裁所有层吗，也就是必须把所有层的名字都打上去？

**Comment by qingqing01** [comment]
@guotongjian 不是裁剪所有层。 您是参考 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/configs/slim 这里吗？

**Comment by guotongjian** [comment]
> @guotongjian 不是裁剪所有层。 您是参考 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/configs/slim 这里吗？

您好，我就是按着这个教程剪裁的，我有把slim_config中的print_params设为True打印网络中所有层信息，然后选取正确的名称。但是还是报错。

**Comment by yghstill** [comment]
@guotongjian 把你的slim_config发一下，我们复现下问题，谢谢

**Comment by guotongjian** [comment]
pretrain_weights: weights/260.pdparams#选取训练的第260个epoch的权重作为预训练
slim: Pruner

Pruner:
  criterion: fpgm
  pruned_params: ['conv2d_0.w_0', 'conv2d_1.w_0', 'conv2d_2.w_0',
                  'conv2d_3.w_0', 'conv2d_4.w_0', 'conv2d_5.w_0',
                  'conv2d_6.w_0', 'conv2d_7.w_0', 'conv2d_8.w_0',
                  'conv2d_9.w_0', 'conv2d_10.w_0', 'conv2d_11.w_0',
                  'conv2d_12.w_0', 'conv2d_13.w_0', 'conv2d_14.w_0',
                  'conv2d_15.w_0', 'conv2d_16.w_0', 'conv2d_17.w_0',
                  'conv2d_18.w_0', 'conv2d_19.w_0', 'conv2d_20.w_0',
                  'conv2d_21.w_0', 'conv2d_22.w_0', 'conv2d_23.w_0',
                  'conv2d_24.w_0', 'conv2d_25.w_0', 'conv2d_26.w_0',
                  'conv2d_27.w_0', 'conv2d_28.w_0', 'conv2d_29.w_0',
                  'conv2d_30.w_0', 'conv2d_31.w_0', 'conv2d_32.w_0',
                  'conv2d_33.w_0', 'conv2d_34.w_0', 'conv2d_35.w_0',
                  'conv2d_36.w_0', 'conv2d_37.w_0', 'conv2d_38.w_0',
                  'conv2d_39.w_0', 'conv2d_40.w_0', 'conv2d_41.w_0',
                  'conv2d_42.w_0', 'conv2d_43.w_0', 'conv2d_44.w_0',]
  pruned_ratios: [0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3]
  print_params: False

**Comment by guotongjian** [comment]
> @guotongjian 把你的slim_config发一下，我们复现下问题，谢谢

您好，以下是我的slim_config
pretrain_weights: weights/260.pdparams#选取训练的第260个epoch的权重作为预训练
slim: Pruner

Pruner:
criterion: fpgm
pruned_params: ['conv2d_0.w_0', 'conv2d_1.w_0', 'conv2d_2.w_0',
'conv2d_3.w_0', 'conv2d_4.w_0', 'conv2d_5.w_0',
'conv2d_6.w_0', 'conv2d_7.w_0', 'conv2d_8.w_0',
'conv2d_9.w_0', 'conv2d_10.w_0', 'conv2d_11.w_0',
'conv2d_12.w_0', 'conv2d_13.w_0', 'conv2d_14.w_0',
'conv2d_15.w_0', 'conv2d_16.w_0', 'conv2d_17.w_0',
'conv2d_18.w_0', 'conv2d_19.w_0', 'conv2d_20.w_0',
'conv2d_21.w_0', 'conv2d_22.w_0', 'conv2d_23.w_0',
'conv2d_24.w_0', 'conv2d_25.w_0', 'conv2d_26.w_0',
'conv2d_27.w_0', 'conv2d_28.w_0', 'conv2d_29.w_0',
'conv2d_30.w_0', 'conv2d_31.w_0', 'conv2d_32.w_0',
'conv2d_33.w_0', 'conv2d_34.w_0', 'conv2d_35.w_0',
'conv2d_36.w_0', 'conv2d_37.w_0', 'conv2d_38.w_0',
'conv2d_39.w_0', 'conv2d_40.w_0', 'conv2d_41.w_0',
'conv2d_42.w_0', 'conv2d_43.w_0', 'conv2d_44.w_0',]
pruned_ratios: [0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3]
print_params: False

**Comment by yghstill** [comment]
@guotongjian 网络输入第一层是不能裁剪的，将`conv2d_0.w_0`去掉，并且不是网络里所有层都要裁剪，一般像yolo系列模型，只裁剪head部分。改下pruned_params的参数再试下吧。之后我们会开源敏感度分析脚本，选取敏感度最低的一些层裁剪就行。

**Comment by guotongjian** [comment]
> @guotongjian 网络输入第一层是不能裁剪的，将`conv2d_0.w_0`去掉，并且不是网络里所有层都要裁剪，一般像yolo系列模型，只裁剪head部分。改下pruned_params的参数再试下吧。之后我们会开源敏感度分析脚本，选取敏感度最低的一些层裁剪就行。

去掉conv2d_0.w_0还是报同样的错误。。。。我只是想先试一下能不能跑起来，剪裁的层和剪裁率都是随便定的
