### ISSUE TITLE
模型导出错

### ISSUE THREAD

**Issue by ralph0813** [PaddlePaddle/PaddleDetection#276]
环境：
paddlepaddle版本：1.6/1.7
paddleDetection版本：release 0.2

问题描述：
更新到最新paddeldetection之后模型导出出错，换用使用示例也报相同的错误。
指定了weights仍然报错找不到文件。

python tools/export_model.py -c configs/yolov3_darknet.yml         --output_dir=./inference_model         -o weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet.tar            TestReader.inputs_def.image_shape=[3,320,320]

2020-02-29 13:30:10,281-INFO: Found /home/ralph/.cache/paddle/weights/yolov3_darknet
2020-02-29 13:30:10,281-INFO: Loading parameters from /home/ralph/.cache/paddle/weights/yolov3_darknet...
Traceback (most recent call last):
  File "tools/export_model.py", line 114, in <module>
    main()
  File "tools/export_model.py", line 101, in main
    checkpoint.load_params(exe, infer_prog, cfg.weights)
  File "/home/ralph/PycharmProjects/PaddleDetection/ppdet/utils/checkpoint.py", line 125, in load_params
    fluid.load(prog, path, executor=exe)
  File "/home/ralph/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/io.py", line 1577, in load
    "Parameter file [{}] not exits".format(parameter_file_name)
AssertionError: Parameter file [/home/ralph/.cache/paddle/weights/yolov3_darknet.pdparams] not exits

**Comment by willthefrog** [comment]
可否提供下 `/home/ralph/.cache/paddle/weights/`的文件列表？ 确认 `/home/ralph/.cache/paddle/weights/yolov3_darknet`文件夹存在并且可以正常读取？

**Comment by willthefrog** [comment]
测试了下描述里的命令，可以正常运行，能否提供版本及完整报错信息？

**Comment by willthefrog** [comment]
另外，请确认使用的是1.7版paddle, 感觉你这个报错大概率是paddle版本不对，可以参考[这里](https://github.com/PaddlePaddle/PaddleDetection/issues/252#issuecomment-590037809)回滚PaddleDetection的版本

**Comment by ralph0813** [comment]
你好我又尝试切换到paddle1.7拉取新的PaddleDetection，删除缓存文件，模型到处仍然失败：

(paddle1.7) ralph@ralph-2080:~/paddle/PaddleDetection$ python tools/export_model.py -c configs/yolov3_darknet.yml         --output_dir=./inference_model         -o weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet.tar            TestReader.inputs_def.image_shape=[3,320,320]
2020-03-02 12:54:39,615-INFO: Downloading yolov3_darknet.tar from https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet.tar
100%|█████████████████████████████████| 242560/242560 [00:25<00:00, 9478.28KB/s]
2020-03-02 12:55:06,168-INFO: Decompressing /home/ralph/.cache/paddle/weights/yolov3_darknet.tar...
2020-03-02 12:55:06,364-INFO: Loading parameters from /home/ralph/.cache/paddle/weights/yolov3_darknet...
Traceback (most recent call last):
  File "tools/export_model.py", line 114, in <module>
    main()
  File "tools/export_model.py", line 101, in main
    checkpoint.load_params(exe, infer_prog, cfg.weights)
  File "/home/ralph/paddle/PaddleDetection/ppdet/utils/checkpoint.py", line 125, in load_params
    fluid.load(prog, path, executor=exe)
  File "/home/ralph/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/io.py", line 1577, in load
    "Parameter file [{}] not exits".format(parameter_file_name)
AssertionError: Parameter file [/home/ralph/.cache/paddle/weights/yolov3_darknet.pdparams] not exits

**Comment by willthefrog** [comment]
你的paddle 1.7是怎么安装的？ [报错位置](https://github.com/PaddlePaddle/Paddle/blob/release/1.7/python/paddle/fluid/io.py#L1577)对不上啊？

**Comment by ralph0813** [comment]
通过conda安装的

**Comment by willthefrog** [comment]
确认下环境没问题吧，感觉运行的不是1.7，如果实在不行，建议先回滚PaddleDetection

**Comment by ralph0813** [comment]
环境没问题，1.6 1.7我都有，回滚paddle detection 到是可以用

**Comment by ralph0813** [comment]
>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0302 13:14:07.249513 13402 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.2, Runtime API Version: 10.0
W0302 13:14:07.304213 13402 device_context.cc:244] device: 0, cuDNN Version: 7.6.
Your Paddle Fluid works well on SINGLE GPU or CPU.
I0302 13:14:08.399482 13402 parallel_executor.cc:421] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I0302 13:14:08.399699 13402 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I0302 13:14:08.399858 13402 parallel_executor.cc:285] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0302 13:14:08.399958 13402 parallel_executor.cc:315] Cross op memory reuse strategy is enabled, when build_strategy.memory_optimize = True or garbage collection strategy is disabled, which is not recommended
I0302 13:14:08.400086 13402 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

**Comment by willthefrog** [comment]
你这个`io.py`的报错位置和1.7的代码对不上啊，是否需要切换venv之类的，执行 `python -c "import paddle; print(paddle.__version__)"`看下版本？

**Comment by ralph0813** [comment]
奇怪了，居然是1.6.2，我刚安装的时候看到conda下载的是1.7

**Comment by ralph0813** [comment]
paddlepaddle-gpu   anaconda/cloud/Paddle/linux-64::paddlepaddle-gpu-1.7.0-py37_gpu_cuda10.0_many_linux

**Comment by ralph0813** [comment]
我又试了一遍，还是1.6.2：

但是它安装的的是 ：paddlepaddle-gpu anaconda/cloud/Paddle/linux-64::paddlepaddle-gpu-1.7.0-py37_gpu_cuda10.0_many_linux

(paddle1.7) ralph@ralph-2080:~$ conda install paddlepaddle-gpu cudatoolkit=10.0
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ralph/anaconda3/envs/paddle1.7

  added / updated specs:
    - cudatoolkit=10.0
    - paddlepaddle-gpu


The following NEW packages will be INSTALLED:

  asn1crypto         anaconda/pkgs/main/linux-64::asn1crypto-1.3.0-py37_0
  blas               anaconda/pkgs/main/linux-64::blas-1.0-mkl
  cairo              anaconda/pkgs/main/linux-64::cairo-1.14.12-h8948797_3
  cffi               anaconda/pkgs/main/linux-64::cffi-1.14.0-py37h2e261b9_0
  chardet            anaconda/pkgs/main/linux-64::chardet-3.0.4-py37_1003
  cryptography       anaconda/pkgs/main/linux-64::cryptography-2.8-py37h1ba5d50_0
  cudatoolkit        anaconda/pkgs/main/linux-64::cudatoolkit-10.0.130-0
  cudnn              anaconda/pkgs/main/linux-64::cudnn-7.3.1-cuda10.0_0
  cycler             anaconda/pkgs/main/linux-64::cycler-0.10.0-py37_0
  dbus               anaconda/pkgs/main/linux-64::dbus-1.13.12-h746ee38_0
  decorator          anaconda/pkgs/main/noarch::decorator-4.4.1-py_0
  expat              anaconda/pkgs/main/linux-64::expat-2.2.6-he6710b0_0
  fontconfig         anaconda/pkgs/main/linux-64::fontconfig-2.13.0-h9420a91_0
  freetype           anaconda/pkgs/main/linux-64::freetype-2.9.1-h8a8886c_1
  fribidi            anaconda/pkgs/main/linux-64::fribidi-1.0.5-h7b6447c_0
  glib               anaconda/pkgs/main/linux-64::glib-2.63.1-h5a9c865_0
  graphite2          anaconda/pkgs/main/linux-64::graphite2-1.3.13-h23475e2_0
  graphviz           anaconda/pkgs/main/linux-64::graphviz-2.40.1-h21bd128_2
  gst-plugins-base   anaconda/pkgs/main/linux-64::gst-plugins-base-1.14.0-hbbd80ab_1
  gstreamer          anaconda/pkgs/main/linux-64::gstreamer-1.14.0-hb453b48_1
  harfbuzz           anaconda/pkgs/main/linux-64::harfbuzz-1.8.8-hffaf4a1_0
  icu                anaconda/pkgs/main/linux-64::icu-58.2-h9c2bf20_1
  idna               anaconda/pkgs/main/linux-64::idna-2.8-py37_0
  intel-openmp       anaconda/pkgs/main/linux-64::intel-openmp-2020.0-166
  jpeg               anaconda/pkgs/main/linux-64::jpeg-9b-h024ee3a_2
  kiwisolver         anaconda/pkgs/main/linux-64::kiwisolver-1.1.0-py37he6710b0_0
  libgfortran-ng     anaconda/pkgs/main/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  libpng             anaconda/pkgs/main/linux-64::libpng-1.6.37-hbc83047_0
  libprotobuf        anaconda/pkgs/main/linux-64::libprotobuf-3.11.4-hd408876_0
  libtiff            anaconda/pkgs/main/linux-64::libtiff-4.1.0-h2733197_0
  libuuid            anaconda/pkgs/main/linux-64::libuuid-1.0.3-h1bed415_2
  libxcb             anaconda/pkgs/main/linux-64::libxcb-1.13-h1bed415_1
  libxml2            anaconda/pkgs/main/linux-64::libxml2-2.9.9-hea5a465_1
  matplotlib         anaconda/pkgs/main/linux-64::matplotlib-3.1.3-py37_0
  matplotlib-base    anaconda/pkgs/main/linux-64::matplotlib-base-3.1.3-py37hef1b27d_0
  mkl                anaconda/pkgs/main/linux-64::mkl-2020.0-166
  mkl-service        anaconda/pkgs/main/linux-64::mkl-service-2.3.0-py37he904b0f_0
  mkl_fft            anaconda/pkgs/main/linux-64::mkl_fft-1.0.15-py37ha843d7b_0
  mkl_random         anaconda/pkgs/main/linux-64::mkl_random-1.1.0-py37hd6b4f25_0
  nltk               anaconda/pkgs/main/linux-64::nltk-3.4.5-py37_0
  numpy              anaconda/pkgs/main/linux-64::numpy-1.18.1-py37h4f9e942_0
  numpy-base         anaconda/pkgs/main/linux-64::numpy-base-1.18.1-py37hde5b4d6_1
  olefile            anaconda/pkgs/main/linux-64::olefile-0.46-py37_0
  paddlepaddle-gpu   anaconda/cloud/Paddle/linux-64::paddlepaddle-gpu-1.7.0-py37_gpu_cuda10.0_many_linux
  pango              anaconda/pkgs/main/linux-64::pango-1.42.4-h049681c_0
  pcre               anaconda/pkgs/main/linux-64::pcre-8.43-he6710b0_0
  pillow             anaconda/pkgs/main/linux-64::pillow-7.0.0-py37hb39fc2d_0
  pixman             anaconda/pkgs/main/linux-64::pixman-0.38.0-h7b6447c_0
  protobuf           anaconda/pkgs/main/linux-64::protobuf-3.11.4-py37he6710b0_0
  py-cpuinfo         anaconda/pkgs/main/noarch::py-cpuinfo-5.0.0-py_0
  pycparser          anaconda/pkgs/main/linux-64::pycparser-2.19-py37_0
  pyopenssl          anaconda/pkgs/main/linux-64::pyopenssl-19.1.0-py37_0
  pyparsing          anaconda/pkgs/main/noarch::pyparsing-2.4.6-py_0
  pyqt               anaconda/pkgs/main/linux-64::pyqt-5.9.2-py37h05f1152_2
  pysocks            anaconda/pkgs/main/linux-64::pysocks-1.7.1-py37_0
  python-dateutil    anaconda/pkgs/main/noarch::python-dateutil-2.8.1-py_0
  pyyaml             anaconda/pkgs/main/linux-64::pyyaml-5.3-py37h7b6447c_0
  qt                 anaconda/pkgs/main/linux-64::qt-5.9.7-h5867ecd_1
  requests           anaconda/pkgs/main/linux-64::requests-2.22.0-py37_1
  scipy              anaconda/pkgs/main/linux-64::scipy-1.4.1-py37h0b6359f_0
  sip                anaconda/pkgs/main/linux-64::sip-4.19.8-py37hf484d3e_0
  six                anaconda/pkgs/main/linux-64::six-1.14.0-py37_0
  tornado            anaconda/pkgs/main/linux-64::tornado-6.0.3-py37h7b6447c_3
  urllib3            anaconda/pkgs/main/linux-64::urllib3-1.25.8-py37_0
  yaml               anaconda/pkgs/main/linux-64::yaml-0.1.7-had09818_2
  zstd               anaconda/pkgs/main/linux-64::zstd-1.3.7-h0b5b093_0


Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(paddle1.7) ralph@ralph-2080:~$ python -c "import paddle; print(paddle.__version__)"
1.6.2

**Comment by willthefrog** [comment]
呃。。。这个我也不清楚了，建议去框架的repo提个issue。。。

**Comment by ralph0813** [comment]
我服了，这conda好像在逗我玩。

**Comment by ralph0813** [comment]
python -m pip install paddlepaddle-gpu==1.7.0.post107 之后正常了，就是paddle版本问题。

**Comment by willthefrog** [comment]
好的，如果没问题了的话请close issue吧，谢谢
