### ISSUE TITLE
输出结果不一致问题

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#2762]
训练用JPG格式图片，导出模型推理时用不同格式图片（BMP、JPG），但同一张图片，得出的结果不一样，分值和类别都不一样，请大神指教！！

**Comment by qingqing01** [comment]
@jackie8310 差异大吗？ 如果同一张JPG图片，输出结果一样吗？是GPU推理，还是CPU推理？

**Comment by jackie8310** [comment]
@qingqing01 ,GPU推理，同一张图片用JPG推理结果一样，如用原始图像BMP格式，结果就不一样，差别比较大的！

**Comment by heavengate** [comment]
cv2把两张图读进来看看有没有diff呢
