### ISSUE TITLE
yolov3训练

### ISSUE THREAD

**Issue by gunshi3** [PaddlePaddle/PaddleDetection#2763]
![image](https://user-images.githubusercontent.com/62952611/116021754-632cca00-a67b-11eb-9268-8876ba831a9f.png)
请问这个报错是为什么呢？
是在用yolov3训练自定义数据集是出现的。
命令行命令为python -u tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_car.yml --use_vdl=True --vdl_log_dir=tb_car_dir/scalar --eval
配置文件都已修改
car_voc.yml
![image](https://user-images.githubusercontent.com/62952611/116021996-e9491080-a67b-11eb-97ce-022654d53668.png)
voc.py
![image](https://user-images.githubusercontent.com/62952611/116022255-6aa0a300-a67c-11eb-83dc-844733fb73e0.png)

**Comment by heavengate** [comment]
是否是自定义数据集里的`label_list.txt`里的类别和数据集里的类别不匹配

**Comment by gunshi3** [comment]
匹配的呀

**Comment by heavengate** [comment]
报错是在数据集里面读到了`heavy truck`这个类，但是在`label_list.txt`里面没有找到

**Comment by gunshi3** [comment]
匹配的呀

**Comment by gunshi3** [comment]
已解决，非常感谢！
