### ISSUE TITLE
C++推理部署问题

### ISSUE THREAD

**Issue by Simonlyym** [PaddlePaddle/PaddleDetection#277]
在对预测库进行编译时遇到这个问题：
make[2]: *** No rule to make target '/home/aistudio/work/opencv-3.4.6/lib/libopencv_imgcodecs.a', needed by 'detection_demo'.  Stop.
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/detection_demo.dir/all' failed
make[1]: *** [CMakeFiles/detection_demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

我使用的编译命令：
%cd /home/aistudio/work/PaddleDetection/inference
!mkdir build
%cd build
!cmake .. -DWITH_GPU=OFF  -DPADDLE_DIR=/home/aistudio/work/PaddleDetection/fluid_inference -DOPENCV_DIR=/home/aistudio/work/opencv-3.4.6 -DWITH_STATIC_LIB=OFF
!make

**Comment by Channingss** [comment]
@Simonlyym  查看一下/home/aistudio/work/opencv-3.4.6/lib64/ 里面是不是有****.a静态库文件，全部拷贝到/home/aistudio/work/opencv-3.4.6/lib/目录下

**Comment by Simonlyym** [comment]
连续复制了四个文件后，又报了这个错：
CMakeFiles/detection_demo.dir/build.make:127: recipe for target 'detection_demo' failed
make[2]: *** [detection_demo] Error 1
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/detection_demo.dir/all' failed
make[1]: *** [CMakeFiles/detection_demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

复制了这些文件：
libopencv_imgcodecs.a
libopencv_imgproc.a
libopencv_core.a
libopencv_highgui.a

**Comment by Simonlyym** [comment]
拷贝了所有的****.a静态库文件到lib下之后，又报了这样的错误
collect2: error: ld returned 1 exit status
CMakeFiles/detection_demo.dir/build.make:127: recipe for target 'detection_demo' failed
make[2]: *** [detection_demo] Error 1
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/detection_demo.dir/all' failed
make[1]: *** [CMakeFiles/detection_demo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sjtubinlong** [comment]
@Simonlyym 请问下你的gcc版本是多少？另外能否提供下opencv目录下的一个结构，感谢

**Comment by Simonlyym** [comment]
我是在aistudio上使用的

**Comment by Simonlyym** [comment]
噢噢gcc要4.8.2 ~ 4.9.4哈
