### ISSUE TITLE
paddle2.0 开启enable_profile耗时统计不准问题

### ISSUE THREAD

**Issue by thzyyx** [PaddlePaddle/PaddleDetection#2771]
在利用进行性能评估时，我出现了一个问题，报告中的测试数据与我自己用time函数统计的耗时不一致。

测试说明：测试数据集coco val2017，其中包含5000张图片，测试耗时统计方法如下：
`start = time.time()
predictor.run()
end = time.time()
total_time += (end - start)`
统一到的平均耗时为26.76ms
推理一张图会调用 1次nms + 6次trt 
开启enable_profile接口，获得到的性能报告如下，通过分析，对可平均调用耗时求和（如：multiclass_nms + tensorrt_engine = 27.4ms），这个数值大于26.76ms。
想请教下这个报告怎么看，跟人工统计的时间有什么区别？
![image](https://user-images.githubusercontent.com/16400675/116052770-87ed6580-a6ac-11eb-846e-2dd74cf10e56.png)

**Comment by heavengate** [comment]
这个profile一般统计的是GPU kernel的计算时间，框架底层OP执行是可有可能并发的，数值大于26.76ms应该是正常现象。
这个报告主要用来看各个op kernel的耗时，分析性能瓶颈在哪

**Comment by thzyyx** [comment]
@heavengate  截图中有些API（Evnet）开头有空格，例如：
thread0::multiclass_nms
  GpuMemcpySync:GPU->CPU
这个表示multiclass_nms算子中调用了GpuMemcpySync:GPU->CPU接口，数据从GPU拷贝CPU。
这个说法是正确的吗？
截图中的：multiclass_nms、deformable_conv、yolo_box、concat、nearest_interp、transpose2和scale层实现在GPU上？
