### ISSUE TITLE
最新版本的paddledet安装后测试出问题

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/PaddleDetection#2772]
按照官方文档，安装都没有错误。环境是
unbuntu18.04
paddlepaddle-gpu==2.0.1
paddledet==2.0.1
安装后直接使用官方提供命令：
python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams --infer_img=demo/000000014439.jpg
提示结果保存在output中我打开图片，box乱七八糟，如下，尝试将paddlepaddle-gpu==2.0.2情况一样
![000000014439](https://user-images.githubusercontent.com/23259315/116059583-925f2d80-a6b3-11eb-8f70-1f7c2eb67898.jpg)
开始以为模型问题，删除.cache文件夹下模型文件，重新来情况依旧存在。第一次使用paddledet,就这样了，怎么解决哦

**Comment by heavengate** [comment]
看你使用的是动态图的代码版本和配置文件，权重指定的是静态图的权重，动态图的权重在  https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/configs/ppyolo   这个README里面有，你使用的配置文件对应的权重链接是  https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams
