### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleDetection#2779]
yolo算法backbone部分能使用paddleclas的预训练模型吗？paddledetection本身的预训练模型是在哪个数据集上训练的，预训练模型参数只包括backbone部分还是neck，head部分都会包括？

**Comment by jerrywgz** [comment]
目前PaddleDetection的算法是通过paddleclas的预训练模型转换来的，都是基于imagenet训练的

**Comment by Monday-Leo** [comment]
那neck部分，fpn部分，这些部分的参数都是不加载预训练模型里面的参数的吗？

**Comment by jerrywgz** [comment]
训练有两种方式吧，一个是基于imagenet的预训练模型，这样neck，head部分的参数不会加载；另一种是使用paddledetection基于coco/voc等检测数据集训练好的模型finetune，这样模型中的大部分参数都会被加载

**Comment by Monday-Leo** [comment]
好的，谢谢
