### ISSUE TITLE
yolo训练数据集的anchor生成

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleDetection#2786]
tools/anchor_cluster.py中指定的size是指训练集还是测试集，应该在哪里看输入的大小，数据增强随机缩放会影响这个anchor吗？

**Comment by wangxinxin08** [comment]
一般是指测试时的尺寸，比如你测试时期望的尺寸是320， 那你就用320作为anchor聚类的尺寸，这与TestReader中的image_shape或者EvalReader中Resize的target_size是一致的

**Comment by Monday-Leo** [comment]
修改config文件是修改yolov3head还是Gt2YoloTarget？

**Comment by wangxinxin08** [comment]
需要修改的是配置文件，包含配置文件中YOLOv3Head的anchor和Gt2YoloTarget中的anchor两处修改

**Comment by Monday-Leo** [comment]
请问怎么计算模型总的参数，包括backbone，neck，head，paddle.summary()怎么一下包括这三大部分？

**Comment by Monday-Leo** [comment]
@wangxinxin08

**Comment by wangxinxin08** [comment]
请直接尝试在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/tools/train.py#L102 这一行之后添加paddle.summary(trainer.model)试一试

**Comment by heavengate** [comment]
鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen此issue~
