### ISSUE TITLE
ssd_mobilenet模型训练问题

### ISSUE THREAD

**Issue by Simonlyym** [PaddlePaddle/PaddleDetection#279]
训练的时候经常在800~1000iter的时候就内存溢出报错了，我是在aistudio上用GPU运行的

**Comment by qingqing01** [comment]
@Simonlyym  是CPU内存溢出，还是显存不够用？ 使用的Paddle版本是哪个？

**Comment by qingqing01** [comment]
@Simonlyym 可以减少configs/ssd/中的config中的worker_num和bufsize看下。

**Comment by qingqing01** [comment]
@Simonlyym 请问问题还是否存在？
