### ISSUE TITLE
Out of memory error on GPU 0. Cannot allocate 4.000244MB memory on GPU 0, available memory is only 5.187500MB.

### ISSUE THREAD

**Issue by vulyon** [PaddlePaddle/PaddleDetection#2790]
单gpu训练设置   batchsize:4
会报如下错误：
/home/wuliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/home/wuliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/tensor/creation.py:143: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0428 09:30:21.009480 34997 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 10.2
W0428 09:30:21.011276 34997 device_context.cc:372] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File "tools/train.py", line 137, in <module>
    main()
  File "tools/train.py", line 133, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 102, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/wuliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 68, in __init__
    cfg['ema_decay'], self.model, use_thres_step=True)
  File "/home/wuliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/ppdet/optimizer.py", line 235, in __init__
    self.state_dict[k] = paddle.zeros_like(v)
  File "/home/wuliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/tensor/creation.py", line 387, in zeros_like
    return full_like(x=x, fill_value=0, dtype=dtype, name=name)
  File "/home/wuliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/tensor/creation.py", line 217, in full_like
    return core.ops.fill_any_like(x, 'value', fill_value, 'dtype', dtype)
SystemError: (Fatal) Operator fill_any_like raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 4.000244MB memory on GPU 0, available memory is only 5.187500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
. (at /paddle/paddle/fluid/imperative/tracer.cc:172)

**Comment by yghstill** [comment]
@kwuliang 显存还是不足，要将batch size设置的再小些，是哪个模型？显存大小多少？

**Comment by vulyon** [comment]
ppyolov2,batchsize最后设为了2

**Comment by yghstill** [comment]
> ppyolov2,batchsize最后设为了2

显存是多少呢？改完batch_size后同时需要将学习率按比例减小。

**Comment by vulyon** [comment]
模型是ppyolov2，显卡内存是12g，batchsize设置1，,我测试：python tools/eval.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml -o 
weights=/home/wuliang/weights/ppyolov2_r50vd_dcn_365e_coco.pdparams
报错，显卡
SystemError: (Fatal) Operator gaussian_random raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 4.000244MB memory on GPU 0, available memory is only 9.187500MB.

**Comment by Huihuihh** [comment]
这个ppyolo的训练，我也是修改了batch_size才能成功利用gpu训练。这个学习率按比例减小是指，原有的batch_size: 24，base_lr: 0.01。然后batch_size: 8，base_lr: 0.0033是吗
