### ISSUE TITLE
Error Message Summary:报错，程序运行一段时间后发生报错

### ISSUE THREAD

**Issue by HotCoCoC** [PaddlePaddle/PaddleDetection#280]
Error: When calling this method, the Tensor's numel must be equal or larger than
 zero. Please check Tensor::dims, or Tensor::Resize has been called first. The T
ensor's shape is [-1, 1024] now
  [Hint: Expected numel() >= 0, but received numel():-1024 < 0:0.] at (D:\1.7.0\
paddle\paddle\fluid\framework\tensor.cc:45)
  [operator < elementwise_add > error]
以上是报错内容，其已经开始训练了，但练着练着就会出现这个问题，想知道这是哪里错误了...是BOX标注有问题么？应该都大于0了吧

**Comment by qingqing01** [comment]
@HotCoCoC 请问使用哪个模型？什么数据？以及Paddle哪个版本？我们能怎样复现这个错误?

**Comment by HotCoCoC** [comment]
...哥...降低学习率就突然好了...︿(￣︶￣)︿

**Comment by qingqing01** [comment]
@HotCoCoC  嗯嗯，注意GPU个数、batch-size和学习率的关系，参考: https://paddledetection.readthedocs.io/zh/latest/tutorials/GETTING_STARTED_cn.html#faq
