### ISSUE TITLE
请问动态图版本还会出以前静态图版本上的组件吗？比如BiFPN，CIoU之类的？

### ISSUE THREAD

**Issue by MrWcy** [PaddlePaddle/PaddleDetection#2803]
如果出的话，大概是什么时候呢？

**Comment by yghstill** [comment]
CIoU目前在yolo系列中已经支持https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/ppdet/modeling/losses/iou_loss.py#L47
BiFPN我们会在下个版本支持，预计下个月。
