### ISSUE TITLE
在集群的环境下测试test_architectures.py

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#2806]
我这边的服务器是集群的，所以目前在集群的环境下安装paddle的，但是在测试官方的测试用例的时候出现了问题。
```
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 31, in <module>
    from ppdet.modeling.tests.decorator_helper import prog_scope
ModuleNotFoundError: No module named 'ppdet.modeling.tests.decorator_helper'

```
问题如上，提示没有一些模块，但是这是存在的啊，首先测试 paddle.utils.run_check()是成功的。

**Comment by yghstill** [comment]
@dengxinlong 目前安装了paddledet之后，这个test_architectures.py执行会有import路径问题，可以直接跑程序，这个问题我们修复下

**Comment by dengxinlong** [comment]
> @dengxinlong 目前安装了paddledet之后，这个test_architectures.py执行会有import路径问题，可以直接跑程序，这个问题我们修复下
我这边的确安装了paddledet，当时没有注意到分支不同，其他的模型是可以直接跑是吧。

**Comment by yghstill** [comment]
@dengxinlong 没有影响，其他可以正常跑

**Comment by dengxinlong** [comment]
> @dengxinlong 没有影响，其他可以正常跑

好的，谢谢了

**Comment by dengxinlong** [comment]
> @dengxinlong 没有影响，其他可以正常跑

不对啊，还是有问题。我现在跑ssdliteMobilenet_v3_large模型，导入模块还是失败。
```
Traceback (most recent call last):
  File "tools/train.py", line 38, in <module>
    from ppdet.experimental import mixed_precision_context
ModuleNotFoundError: No module named 'ppdet.experimental'
```

**Comment by dengxinlong** [comment]
> @dengxinlong 没有影响，其他可以正常跑

也就是说tools/train.py这个文件导入还是存在问题啊

**Comment by dengxinlong** [comment]
> > @dengxinlong 没有影响，其他可以正常跑
> 
> 也就是说tools/train.py这个文件导入还是存在问题啊



> @dengxinlong 没有影响，其他可以正常跑

我重新安装了paddlepaddle，没有安装paddledet，就没有问题了。粗暴解决吧

**Comment by heavengate** [comment]
你好，最新发布的release/2.1已经解决了此问题~
