### ISSUE TITLE
yolov3模型用infer.py预测正常，但是部署到Serving后报cannot reshape array of size 1 into shape (3,608,608)错

### ISSUE THREAD

**Issue by pipishaw** [PaddlePaddle/PaddleDetection#2808]
yolov3模型用infer.py预测正常，但是部署到Serving后报cannot reshape array of size 1 into shape (3,608,608)错

**Comment by liuhuiCNN** [comment]
部署到Serving后输入尺寸是否正确？根据提示，是说输入尺寸报错。
