### ISSUE TITLE
C++部署指定GPU

### ISSUE THREAD

**Issue by pele228** [PaddlePaddle/PaddleDetection#281]
你好，多卡服务器C++ 部署时，如何指定GPU？比如四卡服务器，指定只在卡1，卡2做Detection任务

**Comment by sjtubinlong** [comment]
@pele228 

如果使用NATIVE模式预测，请求改代码：

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/inference/predictor/detection_predictor.cpp#L137

`device`为指定的卡ID

如果使用`ANALYSIS`模式，请修改：

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/inference/predictor/detection_predictor.cpp#L142

```cpp
config.EnableUseGpu(100, 0);
```
第二个参数`0`为指定的设备id

**Comment by pele228** [comment]
好的，谢谢
