### ISSUE TITLE
如何查看模型基础结构和参数信息？

### ISSUE THREAD

**Issue by GZHUZhao** [PaddlePaddle/PaddleDetection#2812]
paddle.summary()报错。
![image](https://user-images.githubusercontent.com/78419361/116511579-38e84000-a8f9-11eb-9ef8-2fe5b6df5739.png)

请问使用paddle.summary()怎么查看模型的结构和参数信息？
或者有没有其他方法查看？

**Comment by liuhuiCNN** [comment]
（1）您是参考这个文档： [summary](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/hapi/model_summary/summary_cn.html#summary ) 写的吗？
（2）您可以通过 `tools/export_model.py` 导出模型，然后使用模型可视化工具（如 [PaddleVDL](https://github.com/PaddlePaddle/VisualDL)）查看模型结构。

**Comment by GZHUZhao** [comment]
> （1）您是参考这个文档： [summary](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/hapi/model_summary/summary_cn.html#summary) 写的吗？
> （2）您可以通过 `tools/export_model.py` 导出模型，然后使用模型可视化工具（如 [PaddleVDL](https://github.com/PaddlePaddle/VisualDL)）查看模型结构。

是用的paddle.summary()的。
paddleVDL显示的模型结构太复杂了，我需要的是每一层的尺寸和参数大小这些。

**Comment by dengxinlong** [comment]
> > （1）您是参考这个文档： [summary](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/hapi/model_summary/summary_cn.html#summary) 写的吗？
> > （2）您可以通过 `tools/export_model.py` 导出模型，然后使用模型可视化工具（如 [PaddleVDL](https://github.com/PaddlePaddle/VisualDL)）查看模型结构。
> 
> 是用的paddle.summary()的。
> paddleVDL显示的模型结构太复杂了，我需要的是每一层的尺寸和参数大小这些。

老哥，你是怎么看模型的参数大小的啊，就是比如你上面用的SSD，在哪里嵌入代码啊，我尝试了一下，和你一样的错误

**Comment by dengxinlong** [comment]
> paddle.summary()报错。
> ![image](https://user-images.githubusercontent.com/78419361/116511579-38e84000-a8f9-11eb-9ef8-2fe5b6df5739.png)
> 
> 请问使用paddle.summary()怎么查看模型的结构和参数信息？
> 或者有没有其他方法查看？

老哥，你是怎么看模型的参数大小的啊，就是比如你上面用的SSD，在哪里嵌入代码啊，我尝试了一下，和你一样的错误
