### ISSUE TITLE
使用自定义COCO数据集如何更改标签？

### ISSUE THREAD

**Issue by HotCoCoC** [PaddlePaddle/PaddleDetection#282]
哥，问一下。规定category_id对应的category名称配置文件在哪里...
COCO数据集
cascade_rcnn_r50_fpn_1x.yml 模型

**Comment by HotCoCoC** [comment]
Json文件中也有categories的节点... 

"categories": [{"supercategory": "none", "id": 0, "name": "holothurian"}, {"supercategory": "none", "id": 1, "name": "echinus"}, {"supercategory": "none", "id": 2, "name": "starfish"}, {"supercategory": "none", "id": 3, "name": "scallop"}, {"supercategory": "none", "id": 4, "name": "waterweeds"}]}

**Comment by qingqing01** [comment]
@HotCoCoC 

如果是预测，category名称获取代码是, ppdet/utils/coco_eval.py：

```
def get_category_info(anno_file=None,
                      with_background=True,
                      use_default_label=False):
    print(anno_file, use_default_label)
    if use_default_label or anno_file is None \
            or not os.path.exists(anno_file):
        logger.info("Not found annotation file {}, load "
                    "coco17 categories.".format(anno_file))
        return coco17_category_info(with_background)
    else:
        logger.info("Load categories from {}".format(anno_file))
        return get_category_info_from_anno(anno_file, with_background)
```

即当use_default_label是False，或者设置anno_file，并且文件存在的话，就从json的anno_file文件中load。

因此在reader的yml中https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/configs/faster_fpn_reader.yml#L78 

需要:

- 指定anno_path的完整路径：
```
TestReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  dataset:
    !ImageFolder
    anno_path: dataset/coco/annotations/instances_val2017.json
```

- 或者通过dataset_dir和anno_path指定:

TestReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  dataset:
    !ImageFolder
    anno_path: instances_val2017.json
    dataset_dir: dataset/coco/annotations/

能看到打印的信息:

```
2020-03-02 04:22:54,409-INFO: Load categories from dataset/coco/annotations/instances_val2017.json
```

**Comment by HotCoCoC** [comment]
哥，问题解决了...做检验的时候走的是test.json，在config中使用相对路径了，但test没有相对谁的路径，改用绝对路径后可以提取到categories了。哥，还有个问题，就是我怎样可以用infer输出图片路径下的所有图片的box和class呢，需要自己添加还是有参数可以直接输出

**Comment by qingqing01** [comment]
@HotCoCoC  不用以 “哥” 开头..   :)

默认脚本是直接可视化到图片上，如果想打印输入，在代码中打印`bbox_results`即可:

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/tools/infer.py#L215 

目前没有提供参数，如果觉得需求常见，到是可以增加供选项，保存到文件中。

**Comment by HotCoCoC** [comment]
谢谢
