### ISSUE TITLE
目前PPYOLO和PPYOLOV2不能在CPU上运行么？

### ISSUE THREAD

**Issue by kaikaizhu** [PaddlePaddle/PaddleDetection#2820]

**Comment by kaikaizhu** [comment]
会出现如下错误
AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'sync_batch_norm'

**Comment by qingqing01** [comment]
@kaikaizhu https://github.com/PaddlePaddle/PaddleDetection/issues/2819#issuecomment-829098871

可以参考这里，我们尽快修复下

**Comment by kaikaizhu** [comment]
@yghstill
非常感谢，但是我直接执行测试，不报错，满图框是什么原因？

**Comment by qingqing01** [comment]
@kaikaizhu 您是用什么模型测试？自己训练的，还是我们提供的COCO预训练。 满图框的原因还是模型没有训练好。

**Comment by kaikaizhu** [comment]
> @kaikaizhu您是用什么模型测试？自己训练的，还是我们提供的COCO预训练。

用的时网站提供的模型测试的

**Comment by kaikaizhu** [comment]
@qingqing01 
我下载的是release2.0的代码，配置如下
paddledet==2.0.1
device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2

执行指令python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams --infer_img=demo/000000014439.jpg
得到的结果图是满图的框

尝试了cpu运行，结果也是满图框。
到底是我哪里出了问题，求大佬指点一下

**Comment by kaikaizhu** [comment]
> @qingqing01
> 我下载的是release2.0的代码，配置如下
> paddledet==2.0.1
> device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
> 
> 执行指令python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams --infer_img=demo/000000014439.jpg
> 得到的结果图是满图的框
> 
> 尝试了cpu运行，结果也是满图框。
> 到底是我哪里出了问题，求大佬指点一下

readme里的命令weights地址可能不太对，我把命令按照model Zoo里面的地址改了一下，现在可以了

**Comment by heavengate** [comment]
你好，develop及新发布的release/2.0上已修复~
