### ISSUE TITLE
修改模型推理输出结果个数问题，num_max_boxes

### ISSUE THREAD

**Issue by ybc-ybc** [PaddlePaddle/PaddleDetection#2821]
使用PPYOLOv2训练，设置num_max_boxes: 200；推理时输出仍然是默认的100个。
训练设置：

```
worker_num: 8
TrainReader:
  inputs_def:
    num_max_boxes: 200
```

推理代码：

```
       inputs = self.preprocess(image)
        np_boxes, np_masks = None, None
        input_names = self.predictor.get_input_names()
        for i in range(len(input_names)):
            input_tensor = self.predictor.get_input_handle(input_names[i])
            input_tensor.copy_from_cpu(inputs[input_names[i]])

        for i in range(warmup):
            self.predictor.run()
            output_names = self.predictor.get_output_names()
            boxes_tensor = self.predictor.get_output_handle(output_names[0])
            np_boxes = boxes_tensor.copy_to_cpu()
            if self.mask:
                masks_tensor = self.predictor.get_output_handle(output_names[2])
                np_masks = masks_tensor.copy_to_cpu()

        t1 = time.time()
        for i in range(repeats):
            self.predictor.run()
            output_names = self.predictor.get_output_names()
            boxes_tensor = self.predictor.get_output_handle(output_names[0])
            np_boxes = boxes_tensor.copy_to_cpu()
            if self.mask:
                masks_tensor = self.predictor.get_output_handle(output_names[2])
                np_masks = masks_tensor.copy_to_cpu()
        t2 = time.time()
        ms = (t2 - t1) * 1000.0 / repeats
        print("Inference: {} ms per batch image".format(ms))

        # do not perform postprocess in benchmark mode
        res = []
        if not run_benchmark:
            if reduce(lambda x, y: x * y, np_boxes.shape) < 6:
                print('[WARNNING] No object detected.')
                res = {'boxes': np.array([])}
            else:
                res = self.postprocess(
                    np_boxes, np_masks, inputs, threshold=threshold)
```

**Comment by liuhuiCNN** [comment]
你好，TrainReader 里面的 num_max_boxes 是指训练的时候最大box个数。如果您需要推理时设置最多的bbox数，可以在结果中按score排序取前N个即可。

**Comment by qingqing01** [comment]
@ybc-ybc 

num_max_boxes 是训练时bbox的最大个数，不够的padding到这个长度。控制输出bbox个数的是nms处理的参数  https://github.com/PaddlePaddle/PaddleDetection/blob/34098ae445b982a529ae7912c1c26eee77096ca8/configs/ppyolo/_base_/ppyolov2_r50vd_dcn.yml#L61

**Comment by ybc-ybc** [comment]
> @ybc-ybc
> 
> num_max_boxes 是训练时bbox的最大个数，不够的padding到这个长度。控制输出bbox个数的是nms处理的参数
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/34098ae445b982a529ae7912c1c26eee77096ca8/configs/ppyolo/_base_/ppyolov2_r50vd_dcn.yml#L61

感谢！还有个问题，这两个参数要不要同步修改

**Comment by liuhuiCNN** [comment]
> > @ybc-ybc
> > num_max_boxes 是训练时bbox的最大个数，不够的padding到这个长度。控制输出bbox个数的是nms处理的参数
> > https://github.com/PaddlePaddle/PaddleDetection/blob/34098ae445b982a529ae7912c1c26eee77096ca8/configs/ppyolo/_base_/ppyolov2_r50vd_dcn.yml#L61
> 
> 感谢！还有个问题，这两个参数要不要同步修改

不需要的，num_max_boxes 是训练时候的参数，keep_top_k 是预测过程中NMS的参数。

**Comment by ANewAnonymous** [comment]
> > > @ybc-ybc
> > > num_max_boxes 是训练时bbox的最大个数，不够的padding到这个长度。控制输出bbox个数的是nms处理的参数
> > > https://github.com/PaddlePaddle/PaddleDetection/blob/34098ae445b982a529ae7912c1c26eee77096ca8/configs/ppyolo/_base_/ppyolov2_r50vd_dcn.yml#L61
> > 
> > 
> > 感谢！还有个问题，这两个参数要不要同步修改
> 
> 不需要的，num_max_boxes 是训练时候的参数，keep_top_k 是预测过程中NMS的参数。

如果训练时设置的
keep_top_k=100

预测时修改
keep_top_k=200
是否会有效果？还是说在训练时就要修改keep_top_k=200 非常感谢你的回答
