### ISSUE TITLE
不使用预训练模型

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleDetection#2822]
不使用预训练模型，冲头开始训练的话是否只要将yaml文件中的pretrain_weights去掉就好了呢？我将pretrain_weights的值去掉，然后进行训练，训练后进行评估，map值一直为0.16%，又进行预测，出现如下错误：
![`0 @2)$30RWM(2`BR9L$8 P](https://user-images.githubusercontent.com/71364549/116543075-ff76fb00-a91f-11eb-8c46-f37dc5a7a26d.png)

**Comment by liuhuiCNN** [comment]
（1）配置文件中去掉 pretrain_weights 字段就可以了；
（2）您也可以将加载预训练模型的代码注释掉： https://github.com/PaddlePaddle/PaddleDetection/blob/34098ae445b982a529ae7912c1c26eee77096ca8/tools/train.py#L108 
（3）shape 不匹配的问题，建议您检查一下模型设置是否正确，预测的时候加载的模型路径是否正确。
