### ISSUE TITLE
显存不足，请问有没有类似mmdetection的 gpu_assign_thr 的功能?

### ISSUE THREAD

**Issue by NicholasIrving** [PaddlePaddle/PaddleDetection#2827]
显存不足，请问有没有类似mmdetection的 gpu_assign_thr 的功能?

**Comment by liuhuiCNN** [comment]
您可以参考下： https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/train_cn.html#wenti-xunlianshibaocuotishixiancunbuzu-ruhejiejue
可以使用以下几个选项：
`#一旦不再使用即释放内存垃圾，=1.0 垃圾占用内存大小达到10G时，释放内存垃圾
export FLAGS_eager_delete_tensor_gb=0.0

#启用快速垃圾回收策略，不等待cuda kernel 结束，直接释放显存
export FLAGS_fast_eager_deletion_mode=1

#该环境变量设置只占用0%的显存
export FLAGS_fraction_of_gpu_memory_to_use=0`
