### ISSUE TITLE
readme错误

### ISSUE THREAD

**Issue by gengyanlei** [PaddlePaddle/PaddleDetection#2829]
![image](https://user-images.githubusercontent.com/22360785/116636410-d3955d00-a993-11eb-9170-3927406c7446.png)

**Comment by liuhuiCNN** [comment]
感谢反馈，这里镜像地址是正确的，您可以通过命令：`docker pull registry.baidubce.com/paddlepaddle/paddle:2.0.1-gpu-cuda10.1-cudnn7` 来下载镜像。

**Comment by gengyanlei** [comment]
哦，习惯性的点击打不开，我以为你们像docker.hub那样可以去网上查阅呢，知道如何安装了。tks
