### ISSUE TITLE
测试CascadeCA RCNN模型出错 Parameter file not exits

### ISSUE THREAD

**Issue by jiehui87** [PaddlePaddle/PaddleDetection#283]
AssertionError: Parameter file [./models/oidv5_cascade_rcnn_cls_aware_r200_vd_fp
n_dcnv2_nonlocal_softnms.pdparams] not exits

使用的paddlepaddle 1.6.3版本

**Comment by qingqing01** [comment]
@jiehui87 release/0.2分支升级了模型save/load接口，需要安装1.7.0的版本。

**Comment by jiehui87** [comment]
安装1.7.0版本，CascadeCA RCNN模型好像也不能使用。

2020-03-02 15:02:46,349-WARNING: variable file [ ./cascade_rcnn_cls_aware_r200_v
d_fpn_dcnv2_nonlocal_softnms/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_s
oftnms ] not used

**Comment by jiehui87** [comment]
> @jiehui87 release/0.2分支升级了模型save/load接口，需要安装1.7.0的版本。

安装1.7.0版本，CascadeCA RCNN模型好像也不能使用。

2020-03-02 15:02:46,349-WARNING: variable file [ ./cascade_rcnn_cls_aware_r200_v
d_fpn_dcnv2_nonlocal_softnms/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_s
oftnms ] not used
