### ISSUE TITLE
关于模型蒸馏策略精度问题

### ISSUE THREAD

**Issue by Sharpiless** [PaddlePaddle/PaddleDetection#2837]
我尝试在VOC上面使用PaddleDetection提供的蒸馏代码

实验环境如下：

数据集：VOC2012

GPU：V100*1

Batch Size：8

Epoches：70000

精度为：

教师模型 | 学生模型 | 蒸馏算法 | mAP on VOC
-- | -- | -- | --
Yolov3-R34 | Yolov3-MobileNetV1 | 无 | 52.07660724
Yolov3-R34 | Yolov3-MobileNetV2 | L2 | 55.30384024
Yolov3-R34 | Yolov3-MobileNetV3 | FineGained | 44.40395831

发现结果比原模型精度还低，请问这是复现问题吗？

项目连接：https://aistudio.baidu.com/aistudio/projectdetail/1878840

**Comment by wangxinxin08** [comment]
收到，这个问题我们定位下

**Comment by qingqing01** [comment]
@Sharpiless 看您的实验情况，L2损失蒸馏有优于原模型。

PaddleDetection中针对VOC和COCO确实使用了2种不同的蒸馏方法

https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/static/slim/distillation#%E8%92%B8%E9%A6%8F%E7%AD%96%E7%95%A5%E8%AF%B4%E6%98%8E

**Comment by Sharpiless** [comment]
好的，感谢。

**Comment by heavengate** [comment]
鉴于问题已经解决，当前issue就先关闭了，如果还有问题可以reopen此issue~
