### ISSUE TITLE
CACascade RCNN模型无法导入使用

### ISSUE THREAD

**Issue by jiehui87** [PaddlePaddle/PaddleDetection#284]
variable file [ ./cascade_rcnn_cls_aware_r200_v
d_fpn_dcnv2_nonlocal_softnms/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_s
oftnms ] not used

版本1.7.0

**Comment by xiegegege** [comment]
能麻烦问下你的运行命令是什么吗？我这里跑是能正常导入的～

**Comment by jiehui87** [comment]
> 能麻烦问下你的运行命令是什么吗？我这里跑是能正常导入的～

python -u tools/infer.py -c configs/oidv5/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.yml -o weights=./oidv5_cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms/ --infer_img=demo/000000570688.jpg

就是按照示例来跑的，下载的模型解压后 ，测试not used

**Comment by xiegegege** [comment]
我这里一样的命令试了下可以的，OIDV5的话模型地址是https://paddlemodels.bj.bcebos.com/object_detection/oidv5_cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.tar ，会不会是下错模型了？

**Comment by jiehui87** [comment]
> 我这里一样的命令试了下可以的，OIDV5的话模型地址是https://paddlemodels.bj.bcebos.com/object_detection/oidv5_cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.tar ，会不会是下错模型了？

模型不会下错，请教一下，是不是还要配置什么，直接目录根目录这么跑会，infer.py 会报找不到ppdet的包

**Comment by xiegegege** [comment]
要在PaddleDetection目录下运行export PYTHONPATH=$PYTHONPATH:.  https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/tutorials/GETTING_STARTED_cn.md

**Comment by jiehui87** [comment]
> 要在PaddleDetection目录下运行export PYTHONPATH=$PYTHONPATH:. https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/tutorials/GETTING_STARTED_cn.md

这个是python的运行路径，想请教下，模型解压后是一个没有后缀名的文件么？在windows和linux环境都测试了，还是报的 not used。

**Comment by xiegegege** [comment]
解压后是一个名字叫oidv5_cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms的文件夹，看你这个 [ ./cascade_rcnn_cls_aware_r200_v
d_fpn_dcnv2_nonlocal_softnms/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_s
oftnms ]  文件的名字不对呀，而且有两层嵌套，应该就一层的～

**Comment by jiehui87** [comment]
解压后就一个文件夹 这个是报的错误，报的是文件夹里面那个文件not used，完整的报错信息：

2020-03-03 14:58:40,481-INFO: Loading parameters from ./oidv5_cascade_rcnn_cls_a
ware_r200_vd_fpn_dcnv2_nonlocal_softnms/...
2020-03-03 14:58:40,482-WARNING: ./oidv5_cascade_rcnn_cls_aware_r200_vd_fpn_dcnv
2_nonlocal_softnms/.pdparams not found, try to load model file saved with [ save
_params, save_persistables, save_vars ]
2020-03-03 14:58:40,482-WARNING: ./oidv5_cascade_rcnn_cls_aware_r200_vd_fpn_dcnv
2_nonlocal_softnms/.pdparams not found, try to load model file saved with [ save
_params, save_persistables, save_vars ]
2020-03-03 14:58:40,500-WARNING: variable file [ ./oidv5_cascade_rcnn_cls_aware_
r200_vd_fpn_dcnv2_nonlocal_softnms/oidv5_cascade_rcnn_cls_aware_r200_vd_fpn_dcnv
2_nonlocal_softnms ] not used
2020-03-03 14:58:40,500-WARNING: variable file [ ./oidv5_cascade_rcnn_cls_aware_
r200_vd_fpn_dcnv2_nonlocal_softnms/oidv5_cascade_rcnn_cls_aware_r200_vd_fpn_dcnv
2_nonlocal_softnms ] not used
D:\Python36\lib\site-packages\paddle\fluid\executor.py:804: UserWarning: There a
re no operators in the program to be executed. If you pass Program manually, ple
ase use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)

**Comment by xiegegege** [comment]
嗯嗯，感觉你的解压有问题，oidv5_cascade_rcnn_cls_aware
r200_vd_fpn_dcnv2_nonlocal_softnms里面应该是没有同名的文件的，或者可以python -u tools/infer.py -c configs/oidv5/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.yml -o weights=https://paddlemodels.bj.bcebos.com/object_detection/oidv5_cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.tar --infer_img=demo/000000570688.jpg 这么运行

**Comment by cao1124** [comment]
您好，我想请教一下，我也是使用paddle detection中的tools/infer.py 进行OIDV5模型预测，配置文件中architecture是CascadeRCNNClsAware，但是预测图片的时候报错the module CascadeRCNNClsAware is not registered  这个怎么解决啊？还是我的使用方式有问题？您是怎么解决预测问题的？
