### ISSUE TITLE
关于训练

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleDetection#2842]
我想要一直训练同一个训练集，有什么办法可以做到呢？是否只能用导出模型将其作为预训练模型呢？

**Comment by qingqing01** [comment]
@553548793 没有明白您的意思。正常训练就是只训练一个数据集，比如COCO， VOC。 您是说说只训练一个样本呢？还是？

**Comment by DongChenwei2000** [comment]
> @553548793 没有明白您的意思。正常训练就是只训练一个数据集，比如COCO， VOC。 您是说说只训练一个样本呢？还是？

一般训练完一个训练集后，会获得一个model_final的模型，我想要在这个模型的基础上再使用同一个训练集进行训练，是否只能用导出模型将其作为预训练模型呢？

**Comment by qingqing01** [comment]
@553548793 

无需导出模型。您可以通过 -r 恢复训练 (也会加载优化器等状态参数，接着之前的训练继续训练) 

或

通过 -o pretrain_weights=xx/model_final.pdparams 加载模型参数继续训练即可 (不会加载优化器等状态参数，只会加载模型参数)。

**Comment by fly8764** [comment]
> @553548793
> 
> 无需导出模型。您可以通过 -r 恢复训练 (也会加载优化器等状态参数，接着之前的训练继续训练)
> 
> 或
> 
> 通过 -o pretrain_weights=xx/model_final.pdparams 加载模型参数继续训练即可 (不会加载优化器等状态参数，只会加载模型参数)。

您好，我想问一下冻结网络层进行训练的问题，能帮忙解答一下吗？
https://github.com/PaddlePaddle/PaddleDetection/issues/2943

**Comment by dzz416** [comment]
> @553548793
> 
> 无需导出模型。您可以通过 -r 恢复训练 (也会加载优化器等状态参数，接着之前的训练继续训练)
> 
> 或
> 
> 通过 -o pretrain_weights=xx/model_final.pdparams 加载模型参数继续训练即可 (不会加载优化器等状态参数，只会加载模型参数)。

为什么我试了没有用呢
