### ISSUE TITLE
请问一下在阿里云函数计算上部署提示version `GLIBCXX_3.4.22' not found 怎么解决

### ISSUE THREAD

**Issue by duolabmeng6** [PaddlePaddle/PaddleDetection#2845]
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /code/.fun/python/lib/python3.6/site-packages/paddle/fluid/core_avx.so)

**Comment by duolabmeng6** [comment]
···
python -m pip install paddlepaddle==2.0.2 -i https://mirror.baidu.com/pypi/simple
···

安装了以后无法运行~~~

**Comment by qingqing01** [comment]
@duolabmeng6 

阿里云上GCC版本是多少？您最好用GCC 8

**Comment by duolabmeng6** [comment]
![image](https://user-images.githubusercontent.com/59047063/116770371-f009c600-aa75-11eb-816b-88b14ecae493.png)

**Comment by duolabmeng6** [comment]
容器内看到版本是 3.4.20 
飞浆说要 3.4.22 不知道怎么办了~

**Comment by qingqing01** [comment]
GLIBC找不到的问题，一版都是GCC版本不对。您可以:

```
gcc --version
```

查看下GCC版本。

另外，如果有docker的话，可以使用飞桨docker镜像，进行安装:

https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html

**Comment by duolabmeng6** [comment]
```
$ gcc --version
gcc (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by duolabmeng6** [comment]
> GLIBC发现的问题，一版都是GCC版本不对。您可以：
> 
> ```
> gcc --version
> ```
> 
> 查看下GCC版本。
> 
> 另外，如果有docker的话，可以使用飞轮dockerdocker，进行安装：
> 
> https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html

没有docker 是 阿里云的函数计算 还有 腾讯云的云函数
都没成功

**Comment by duolabmeng6** [comment]
使用这个镜像安装了依赖可以用了 但是镜像文件 1.7G 太大了。请问有办法减小吗
```
docker run -itd --name testpy -p 2001:2001 -v /mnt/c/2021dl/dockertest:/test python:3.7.10-slim /bin/bash
docker exec -it testpy /bin/bash  


apt install g++
apt install libglib2.0-dev

pip install Pillow
pip install opencv-python==4.2.0.32
pip install onnxruntime
pip install paddlepaddle==2.0.2 -i https://mirror.baidu.com/pypi/simple
pip install imgaug
pip install pyclipper
pip install lmdb

```

**Comment by duolabmeng6** [comment]
解决了 不能使用阿里云函数计算的默认环境 需要自行配置 镜像大概 1.7gb
部署 ppocr 成功~
不知道有没有办法可以缩小一点这个镜像。太大了~

**Comment by qingqing01** [comment]
@duolabmeng6 您期望镜像多大？要缩小的话，需要重新对Paddle制作镜像，减少一些依赖。

**Comment by duolabmeng6** [comment]
> @duolabmeng6 您期望镜像多大？要缩小的话，需要重新对Paddle制作镜像，减少一些依赖。

镜像大小的开销主要是在 paddlepaddle 直接700mb 没了。还有opencv的依赖
···
pip install paddlepaddle==2.0.2 -i https://mirror.baidu.com/pypi/simple
pip install opencv-python==4.2.0.32
···
这两个安装好了以后。镜像大概 1gb 了。
不知道有什么办法可以减小

手把手教你使用ONNXRunTime部署PP-OCR
看了教程
https://aistudio.baidu.com/aistudio/projectdetail/1479970

我再研究一下怎么处理 我不是很熟悉飞浆部署推理的过程 还在看文档，希望有专业的建议~~

镜像大小如果能在500m以内最好了，函数计算上部署容器越大，冷启动时间越长

我部署在函数计算的ppocr冷启动时间大概在 50秒 时间应该都在下载镜像 解压docker镜像。所以小一点冷启动时间会大大减少

**Comment by duolabmeng6** [comment]
请问一下 onnx部署的话 可以脱离 import paddle 吗 因为不是特别熟悉 希望有大佬解答一下 图像预处理 输入 这一块 还有输出处理这一块

**Comment by duolabmeng6** [comment]
![image](https://user-images.githubusercontent.com/59047063/117165147-d19a2680-adf7-11eb-96f3-28637f8f927e.png)
关于阿里云函数计算和腾讯云云函数的部署PP-OCR性能数据 2021年5月5日
已经解决并且做了性能测试

**Comment by qingqing01** [comment]
@duolabmeng6 转成ONNX部署可以脱离Paddle。如果是OCR问题，也可以OCR的repo提问哈。
