### ISSUE TITLE
c++部署main.exe执行报错

### ISSUE THREAD

**Issue by claudehotline** [PaddlePaddle/PaddleDetection#2847]
paddlepaddle 2.0.1
paddleDetection 2.0
cmake version 3.20.0
Microsoft Visual Studio Community 2019
python 3.8

编译生成main.exe，在终端执行后报错：

```
PS E:\paddle_detect_project\cpp-2.0\Release> .\main.exe

You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.WARNING: Logging b
before InitGoogleLogging() is written to STDERR
E0501 17:04:42.732556 21968 port.h:50] Load symbol getPluginRegistry failed.
```

**Comment by qingqing01** [comment]
从错误信息看，您选择了TensorRT的推理库，但本地没有安装TensorRT，编译时您打开了TensorRT的开关吗？如果是，需要安装TensorRT的lib。

如果本地没有安装TensorRT, 请选择 下面推理库的前2行。

https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/windows_cpp_inference.html#windows

**Comment by claudehotline** [comment]
cmke编译的时候设置了-DWITH_TENSORRT=OFF，vs编译完运行main.exe还是报这个错

**Comment by claudehotline** [comment]
换了不带TensorRT的推理库就好了，看前一个推理库必须要装TensorRT。

**Comment by qingqing01** [comment]
@claudehotline 对的，推理库版本、环境需要正确安装。
