### ISSUE TITLE
在windows端运行代码

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleDetection#2850]
在windows端运行代码时，出现了如下错误，是什么原因呢？
![4EQLQ@82}HS P8OW )QR)J5](https://user-images.githubusercontent.com/71364549/116801594-f1062a80-ab3d-11eb-81d2-568892854392.png)

**Comment by qingqing01** [comment]
@553548793 

您安装的PaddlePaddle是CPU版本，如果您要CPU训练，需要设置  `-o use_gpu=False`  参考：

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/docs/tutorials/GETTING_STARTED_cn.md#%E5%8F%82%E6%95%B0%E5%88%97%E8%A1%A8
