### ISSUE TITLE
请问2.0版本的yolo_loss是否做过修改呢

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2851]
同样的数据集，同样的模型，2.0版本的yolo3的loss训练了400个epoch后还是比较高，在7-8左右。2.0-beta版本的loss在2左右，这是什么原因呢，
![image](https://user-images.githubusercontent.com/73452319/116807224-9502cc80-ab64-11eb-992d-97db32af041c.png)
![image](https://user-images.githubusercontent.com/73452319/116807229-98965380-ab64-11eb-97aa-a223b9be5b3c.png)
![image](https://user-images.githubusercontent.com/73452319/116807232-9b914400-ab64-11eb-9c3c-874a6e80b3a6.png)
这个是刚开始训练的时候，大约训练2个epoch，loss_obj就降到10左右，后面就降得非常慢了。我想让loss降低一点，这种情况如何调整呢

**Comment by guotongjian** [comment]
> 同样的数据集，同样的模型，2.0版本的yolo3的loss训练了400个epoch后还是比较高，在7-8左右。2.0-beta版本的loss在2左右，这是什么原因呢，
> ![image](https://user-images.githubusercontent.com/73452319/116807224-9502cc80-ab64-11eb-992d-97db32af041c.png)
> ![image](https://user-images.githubusercontent.com/73452319/116807229-98965380-ab64-11eb-97aa-a223b9be5b3c.png)
> ![image](https://user-images.githubusercontent.com/73452319/116807232-9b914400-ab64-11eb-9c3c-874a6e80b3a6.png)
> 这个是刚开始训练的时候，大约训练2个epoch，loss_obj就降到10左右，后面就降得非常慢了。我想让loss降低一点，这种情况如何调整呢

**Comment by qingqing01** [comment]
@guotongjian 

2.0动态图的yolo_loss和静态图是一致的，这个做过对齐。

您有调整过其他参数吗？ 
2.0版本用的是默认的动态图吗？如果是动态图，是以epoch数设置总共步长的。2.0-beta以及静态图是设置总共的step数，需要注意训练的步长差异。
