### ISSUE TITLE
关于ppyolov2

### ISSUE THREAD

**Issue by JunLei01** [PaddlePaddle/PaddleDetection#2853]
开发者你好，我最近在使用aistudio上使用ppyolov2，我在训练的过程中发现效果并不理想，由于我使用的是voc的数据集，我只修改了base中的coco为voc，训练可以正常进行，但无法进行评估，infer刚开始没有预测框，将执行度调低后才有，但接着训练，哪怕将置信度调低也没有预测框。github上关于ppyolo的问题也很多了，ppyolo是使用8卡训练的，不知百度官方能否出一个ppyolov2的单卡调整yaml文件呢？还有能否更新一下yolov4的动态图版本呢？

**Comment by qingqing01** [comment]
@JunLei01 

关于单卡，这里的lr可以除以8。 我们验证下单卡的VOC数据训练吧。

https://github.com/PaddlePaddle/PaddleDetection/blob/015c090dc4e8161f00269094d004e2953d38be4e/configs/yolov3/_base_/optimizer_270e.yml#L4

另外，您想使用YOLOv4的原因是？
