### ISSUE TITLE
PP-YOLO-Tiny系列配置需要 650 epoint这么多吗？

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleDetection#2855]
请教：
YOLO-MobileNet是12e或24e，再高容易过拟合，
而PP-YOLO-Tiny系列需要650e这么高吗？

**Comment by qingqing01** [comment]
@670133189 

单阶段模型在COCO上一版都是300 epoch以上。PP-YOLO Tiny的650 epoch也是实验中发现更多的epoch数，在COCO上效果还可以。如果是自己的数据集，epoch数可以适当的调整看。
