### ISSUE TITLE
训练和推理问题：

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#2858]
训练时考虑到数据量问题，图片均保存成JPG，模型train好了，上线实时推理时，相机直接输出为BMP，直接用BMP喂入模型预测，结果与保存成JPG不一致，请大神指导！

**Comment by jerrywgz** [comment]
这里的不一致是在可接受范围内吗，可以首先使用deploy/python 同时使用相同图片的jpg输入和bmp输入，分析下数据预处理的结果以及最终预测结果是否一致

**Comment by yzl19940819** [comment]
请问，这个是工业相机拍摄出的彩色图片不，可能是在进行格式转化的过程中，通道的顺序发生了变化把？

**Comment by jackie8310** [comment]
@jerrywgz , 使用deploy/python/infer.py预测，将相机保存的原始图片.BMP和通过cv2.imencode和cv2.imdecode转换成jpg同时进行预测后，前者得到 confidence:0.6640，后者：confidence:0.5808。

**Comment by jackie8310** [comment]
@syzl19940819 

> 请问，这个是工业相机拍摄出的彩色图片不，可能是在进行格式转化的过程中，通道的顺序发生了变化把？

是彩色图片， 使用deploy/python/infer.py预测，将相机保存的原始图片.BMP和通过cv2.imencode和cv2.imdecode转换成jpg同时进行预测后，前者得到 confidence:0.6640，后者：confidence:0.5808。

**Comment by yzl19940819** [comment]
好的，方便加一下微信，我们具体看看这个问题不？ yzl819819 余志良 paddledetection产品经理
