### ISSUE TITLE
关于voc的is_crowd

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleDetection#2859]
按照https://github.com/PaddlePaddle/PaddleDetection/pull/2732 进行了修改，在训练fcos的时候，仍然出现了同样的错误。
![VIBP MXXII@UC_TJO(%_{TF](https://user-images.githubusercontent.com/71364549/116873013-8b06c980-ac49-11eb-9869-28659ab53fc7.png)

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/2875 fcos原先没有支持voc数据格式的训练，可以参考这个pr的改动，本地测试是可以跑通的
