### ISSUE TITLE
visualdl不能正常显示

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleDetection#2860]
已经保存了可视化的文件，文件夹内也可以找到，命令行输入visualdl --logdir vdl_dir/scalar/，能够正常访问127.0.0.1，但是白屏，请问是什么原因？

**Comment by yghstill** [comment]
@lhy823436493 visualdl网页显示正常，没有找到可视化的视图吗？先确认下输出的log文件大小等是否正常。

**Comment by Monday-Leo** [comment]
![ZXKDA_MUN3{M`@K}`FE)4ZK](https://user-images.githubusercontent.com/53975909/117096925-f9a86c00-ad9c-11eb-9d38-6f558edcb193.png)
![2`S%QPT9}A40NST N6(_E12](https://user-images.githubusercontent.com/53975909/117096929-fc0ac600-ad9c-11eb-897f-724297f7b2c8.png)
![7@ X3@PKYENWJAY~_X}S@@3](https://user-images.githubusercontent.com/53975909/117096936-fdd48980-ad9c-11eb-8f26-e4b01fc40406.png)

**Comment by yghstill** [comment]
@lhy823436493 访问`127.0.0.1:8040`可以访问到吗？

**Comment by Monday-Leo** [comment]
上面的图片就是访问了127.0.0.1:8040，图标都出来了，只是没有读取到数据吧，显示白屏

**Comment by xiegegege** [comment]
@lhy823436493 是不是浏览器的问题，现在只支持chrome浏览器
