### ISSUE TITLE
量化相关文档跳转失败

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#2861]
直接看截图吧，用箭头指出的地方能提供足够的信息。
![image](https://user-images.githubusercontent.com/32217129/116883256-f9528880-ac57-11eb-93ed-02b1814d1431.png)
在release 2.0-rc分支下点击关于slim的链接都直接404？？？

**Comment by yghstill** [comment]
@dengxinlong 感谢反馈，这个链接我们修复下，您先参考最新的PaddleSlim文档吧：https://paddleslim.readthedocs.io/zh_CN/latest/
