### ISSUE TITLE
s2anet batch>1情况与--eval时报错

### ISSUE THREAD

**Issue by xjrelc** [PaddlePaddle/PaddleDetection#2862]
batch>1时
Hint: Expected killed_ != true, but received killed_:1 == true:1
似乎是训练数据得自行事先预处理统一成相同大小才行

训练 --eval时 
Exception: list input can be bounding box(Nx4) or RLEs([RLE])
似乎eval的[xc, yc, bow_w, bow_h, angle]还未适配

**Comment by liuhuiCNN** [comment]
您好，感谢反馈，bs>1和--eval的功能正在完善，请您继续关注我们的工作进展。

**Comment by soHardToHaveAName** [comment]
> 您好，感谢反馈，bs>1和--eval的功能正在完善，请您继续关注我们的工作进展。

bs>1 的功能现在有了吗？ 我这边bs>1时还是会报错 ValueError: all input arrays must have the same shape

**Comment by jackiezzq** [comment]
+1，bs=1 训练的太慢了，啥时候支持呀

**Comment by 939979325** [comment]
期待eval

**Comment by yujiaguo** [comment]
现在好像还是不支持eval...
