### ISSUE TITLE
请教一个问题：预测时需要一个延时操作，但是使用python多线程和多进程没有用

### ISSUE THREAD

**Issue by GZHUZhao** [PaddlePaddle/PaddleDetection#2863]
命令：
multiprocessing.Process(target=Alert()).start()
print("do main")
config = Config(FLAGS.model_dir)
detector = Detector(
        config, FLAGS.model_dir, use_gpu=FLAGS.use_gpu, run_mode=FLAGS.run_mode)

就是在预测进程中启动另一个进程进行其他操作，需要延时time.sleep(),但是实际是预测进程等待这个延时操作结束后才接着执行。查看了下图，发现只有一个CPU在工作，其他cpu不怎么动。
![image](https://user-images.githubusercontent.com/78419361/116964442-1cc01680-acde-11eb-8b92-f973cd8e7182.png)
请问有没有办法解决？
感谢！

**Comment by yghstill** [comment]
@GZHUZhao 可以看下使用PredictorPool 是否能解决你的问题：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/native_infer.html#a-name-predictorpool-predictorpool-a
