### ISSUE TITLE
请问介绍页中的足球视频检测是用的什么模型呢？是否能提供训练好的模型呢？

### ISSUE THREAD

**Issue by JIANG-CX** [PaddlePaddle/PaddleDetection#2864]
请问介绍页中的足球视频检测是用的什么模型呢？是否能提供训练好的模型呢？

**Comment by yghstill** [comment]
@JIANG-CX 使用的是ppyolo模型，有训练好的预训练模型：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/configs/ppyolo
