### ISSUE TITLE
不使用预训练模型

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleDetection#2868]
在使用静态图的faster rcnn中不使用预训练模型进行训练，按照 https://github.com/PaddlePaddle/PaddleDetection/issues/2822#issue-870902731  ，我将yaml文件中的pretrain_weights注释掉。
![)@3LKKJ$HKT 9R98@O6U{57](https://user-images.githubusercontent.com/71364549/117014507-7434a580-ad23-11eb-8ba8-62c89c1dfb5a.png)
然后进行训练，出现如下错误。
![}H3M%O6BM0_XPAU FPDF3H1](https://user-images.githubusercontent.com/71364549/117014676-9af2dc00-ad23-11eb-8ede-1a1037acb75d.png)

**Comment by yghstill** [comment]
@553548793 改成`pretrain_weights: None` ,注释掉报错的问题我们再修复下，感谢反馈

**Comment by DongChenwei2000** [comment]
> @553548793 改成`pretrain_weights: None` ,注释掉报错的问题我们再修复下，感谢反馈

改成None后出现如下错误。
![6@JB~0)V}RY(UF16Q{Q 9WK](https://user-images.githubusercontent.com/71364549/117091194-1341b780-ad8d-11eb-8b98-a878d18a7b95.png)
![C6WD9IIBS~H)8VR`YEILI69](https://user-images.githubusercontent.com/71364549/117091198-16d53e80-ad8d-11eb-8c1f-7f28c8dfa633.png)

**Comment by yghstill** [comment]
@553548793 参考blazeface的配置文件：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/static/configs/face_detection/blazeface.yml#L3
改成：
```yaml
pretrain_weights:
```
