### ISSUE TITLE
interpretDL可视化

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleDetection#2869]
训练好模型之后，如何使用paddle的interpretDL可视化，尝试之后，model(data)一直报错，应该是paddledetection和interpretDL的数据预处理不一致，paddle detection能不能直接输入tensor数据，如yolov3(data)，detection中data需要有['image_shape']等值，直接输入tensor导致报错？

**Comment by yghstill** [comment]
refer to https://github.com/PaddlePaddle/InterpretDL/issues/10
