### ISSUE TITLE
Paddle 2.0.2.rocm-post 和 PaddleDetection2.0rc

### ISSUE THREAD

**Issue by kali20gakki** [PaddlePaddle/PaddleDetection#2870]
Paddle 2.0.2.rocm-post版本不支持PaddleDetection2.0rc里面的静态图的模型吗

**Comment by qili93** [comment]
ROCM支持静态图，已经经过验证的PaddleDetection的静态图模型有3个：FaceBoxes, LibraRCNN, RetinaNet

具体可以查看这里的支持模型列表：

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/rocm_docs/paddle_rocm_cn.html

@kali20gakki 您说的静态图模型具体是指哪一个呢？

**Comment by kali20gakki** [comment]
> ROCM支持静态图，已经经过验证的PaddleDetection的静态图模型有3个：FaceBoxes, LibraRCNN, RetinaNet
> 
> 具体可以查看这里的支持模型列表：
> 
> https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/rocm_docs/paddle_rocm_cn.html
> 
> @kali20gakki 您说的静态图模型具体是指哪一个呢？

@qili93 感谢回复了解了，ROCM动态图里面的现在预训练模型太少（res2net等等还没有支持），所以去尝试静态图里面的模型结果计算都是nan。现在只能等对ROCM动态图模型的支持了。
