### ISSUE TITLE
如何输出预测数据集的bbox等信息？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleDetection#2871]
tools/infer.py似乎只有输出图片

**Comment by liuhuiCNN** [comment]
你好，tools/infer.py是只输出图片，如果您需要检测结果，可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/015c090dc4e8161f00269094d004e2953d38be4e/ppdet/utils/visualizer.py#L83
