### ISSUE TITLE
关于pp-yolov2一些问题

### ISSUE THREAD

**Issue by lmk123568** [PaddlePaddle/PaddleDetection#2872]
- fps是不包括后续nms处理吗
- 关于yolov5，论文测试的速度是在fp32下测试得吗，为什么和官方测试不一样

**Comment by liuhuiCNN** [comment]
您说的fps是指 benchmark 中的fps吗？

**Comment by lmk123568** [comment]
> 您说的fps是指 benchmark 中的fps吗？

是的，如图所示

![批注](https://user-images.githubusercontent.com/60082702/117169953-2770cd80-adfc-11eb-853b-a601aa5555fd.png)

在FPS(v100)下 非TensorRT，比如PPYOLOv2的FPS是68.9，这个数据请问是不是不包括NMS和decodebox？还有yolov5l官方测试的数据是3.8ms/img，折合FPS约为263，请问为什么和实验图不太一样

这问题困扰我了一天，如果能回复将不胜感激！！！

**Comment by Chen-Song** [comment]
@lmk123568 你好，请问你这个图是从哪里截过来的呢？

**Comment by qingqing01** [comment]
@lmk123568 

PPYOLOv2是不包括NMS和decode box。

YOLOv5l官方的数据是BatchSize=16，FP16测试。 

我们在论文里的数据是，利用YOLOv5官方测试代码，测试BatchSize=1，不包含NMS和decode box时间。

**Comment by lmk123568** [comment]
> @lmk123568
> 
> PPYOLOv2是不包括NMS和decode box。
> 
> YOLOv5l官方的数据是BatchSize=16，FP16测试。
> 
> 我们在论文里的数据是，利用YOLOv5官方测试代码，测试BatchSize=1，不包含NMS和decode box时间。

感谢回复，就是说论文给出yolov5数据是，在fps32下测试的batchsize=1的数据是吗，想问一下你们怎么测试fps32的，官方是fps16推理的，谢谢

**Comment by qingqing01** [comment]
@lmk123568  

是的，论文里YOLOv5是FP32, BS=1的测试数据，不包含nms和解码。
YOLOv5的FP32数据，这里不设置half即可:

https://github.com/ultralytics/yolov5/blob/b18ca31ff5412d30ee56eb9c4adbe731f9d2148e/test.py#L68

**Comment by lmk123568** [comment]
感谢回复，问题已解决
