### ISSUE TITLE
train和infer在创建reader后无法单步调试

### ISSUE THREAD

**Issue by ximitiejiang** [PaddlePaddle/PaddleDetection#2873]
你好，我在使用paddlepaddle跑算法的单步debug时，只要创建完reader，单步就会卡死无法进行下去。我尝试修改config设置worker_num=0来关闭dataloader的多进程但貌似也没有效果。

请问，这种单步调试卡死的原因是什么，如何解决？

**Comment by yghstill** [comment]
@ximitiejiang 你是基于哪个分支代码进行调试？最新release/2.0吗？

**Comment by ximitiejiang** [comment]
你好，我的paddle是2.0.1，paddledetection是2.0.0

**Comment by yghstill** [comment]
@ximitiejiang 是在哪个位置会卡住，是这里吗？https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/ppdet/engine/trainer.py#L73

**Comment by ximitiejiang** [comment]
在trian任务时，就是在你说的这里会卡住（debug模式卡住，run模式正常）；在infer任务时，是卡在
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/ppdet/engine/trainer.py#L362，都是create()函数

**Comment by yghstill** [comment]
@ximitiejiang 取消所有断点再使用debug模式试下看是否可以，另外推荐使用gdb断点调试工具。

**Comment by ximitiejiang** [comment]
依然不行。你这边能复现这个问题吗还是说已知暂不能解决？
我稍后试试gdb...

**Comment by 013292** [comment]
@ximitiejiang  @yghstill @QingshuChen In `/ppdet/reader.py` 
```
class BatchCompose(Compose):
    def __init__(self, transforms, num_classes=80):
        super(BatchCompose, self).__init__(transforms, num_classes)
        self.output_fields = mp.Manager().list([]) # <----------------- it breaks at this point, doesn't it?
        self.lock = mp.Lock()
```

**Comment by heavengate** [comment]
develop分支上对DataLoader部分的逻辑做了优化，需要使用Paddle 2.0.2版本，可以更新PaddleDetection代码和Paddle版本试下
