### ISSUE TITLE
ppyolo训练模型，使用paddlelite报错

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/PaddleDetection#2878]
利用ppyolo训练的模型，导出模型__model__和__params__文件，将其在paddlelite中使用推理，报错“Segmentation fault”
针对ppyolo训练的模型，进行推理时，是否和yolov3的处理代码一样，还是有其他改变，能否提供个实例。或者paddlelite是否支持ppyolo模型推理

**Comment by yghstill** [comment]
@Huihuihh Lite的demo已发布，目前支持动态图模型，欢迎使用：https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/lite

ppyolo支持paddlelite预测，静态图模型的lite demo可参考：https://github.com/PaddlePaddle/Paddle-Lite/tree/develop/lite/demo/cxx/yolov3_detection
