### ISSUE TITLE
关于ppyolo-tiny的训练时间

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleDetection#2894]
运行环境是ai studio的单卡环境，由于有要求因此不使用预训练模型，按文档将学习率将调小8倍。
![2~V3WF2)P8P5_UQ{P54B8NI](https://user-images.githubusercontent.com/71364549/117470269-320c9d80-af89-11eb-982b-64869fe1b646.png)
但是训练时间很长，需要6至7天，请问这是正常的吗。还有在学习率调下8倍并且不使用预训练模型的情况下拟合速度是否会很慢呢？
![H~ (2R@8`W@)}HS4(PJ`~~3](https://user-images.githubusercontent.com/71364549/117470657-9f203300-af89-11eb-9a50-ce6e8cb80fdc.png)

**Comment by qingqing01** [comment]
@553548793 

如果单卡训练，以及自己数据的话，可以考虑减少epoch数，以及适当减少预处理操作，提升速度。


https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/ppyolo/_base_/ppyolo_tiny_reader.yml
