### ISSUE TITLE
ppyolo使用voc数据在eval时报错

### ISSUE THREAD

**Issue by Cristhine** [PaddlePaddle/PaddleDetection#2895]
训练过程中报错，看起来是进行验证的时候报错，验证测试集当训练集也正常运行一个epoch，理论上没有脏数据才对，所以这个错误还有可能是什么呢
![image](https://user-images.githubusercontent.com/26667855/117521977-3fef0c80-afe3-11eb-87ce-fb324731d46b.png)

**Comment by Cristhine** [comment]
ppyolov2更换成官方voc数据报错同样错误 应该是ppyolov2代码不能适配voc

**Comment by yghstill** [comment]
@Cristhine 问题已在#2731 修复，更新最新develop代码再试下吧。
