### ISSUE TITLE
ppyolo_tiny 训练速度非常慢，gpu基本不动

### ISSUE THREAD

**Issue by gftd** [PaddlePaddle/PaddleDetection#2900]
![125769a44595c2e78d4ad2d6ebbb94a](https://user-images.githubusercontent.com/7836059/117530883-34ffa080-b012-11eb-88e0-27ab2e476ec5.png)
![dc58f117bb5557fd49fbffd69a17c2a](https://user-images.githubusercontent.com/7836059/117530884-36c96400-b012-11eb-8df1-35c67703feee.png)

使用单卡训练ppyolo，配置就改了worker_num: 32，其他默认的配置：

`worker_num: 32
TrainReader:
  inputs_def:
    num_max_boxes: 100
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [192, 224, 256, 288, 320, 352, 384, 416, 448, 480, 512], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 100}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[10, 15], [24, 36], [72, 42], [35, 87], [102, 96], [60, 170], [220, 125], [128, 222], [264, 266]], downsample_ratios: [32, 16, 8]}
  batch_size: 32
  shuffle: true
  drop_last: true
  mixup_epoch: 500
  use_shared_memory: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [320, 320], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 8
  drop_empty: false

TestReader:
  inputs_def:
    image_shape: [3, 320, 320]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [320, 320], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 8
`
gpu的使用率基本在10%以下，需要改动什么配置加速训练，让显卡跑起来。

**Comment by DongChenwei2000** [comment]
我也是单卡使用ppyolo_tiny，我把学习率除8，一共要训练5天，我是cpu拉满，gpu也是10%左右，现存拉到9G这样，不知道是不是正常情况

**Comment by gftd** [comment]
> 我也是使用ppyolo_tiny，一共要训练5天，我是cpu拉满，gpu也是10%左右，现存拉到9G这样，不知道是不是正常情况

我觉得不正常呀，要是这样，要gpu干嘛呢，直接cpu干就好了啊。

**Comment by DongChenwei2000** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/2894#issue-879186337   你可以看下我提的这个问题，虽然感觉没什么用

**Comment by gftd** [comment]
> [#2894 (comment)](https://github.com/PaddlePaddle/PaddleDetection/issues/2894#issue-879186337) 你可以看下我提的这个问题，虽然感觉没什么用

和我的问题差不多，刚才看过了的

**Comment by heavengate** [comment]
单卡上应该不至于这么慢，单卡的话`num_workers`设置到8-16就差不多了，另外如果还是比较慢的话可以试下不开mixup，即把`mixup_epoch`设置成-1

**Comment by gftd** [comment]
您好！您的邮件已收到！我查阅后，尽快回复您！
