### ISSUE TITLE
ppyolo_tiny模型量化

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleDetection#2905]
使用静态图的ppyolo_tiny，在ppyolo_tiny模型做量化后模型体积的确减小到1.3M左右，但是将其转为onnx后又变回原来的4M大小，是否有办法将其体积缩小呢？还是说onnx本来就是这个大小呢？

**Comment by heavengate** [comment]
模型原始大小是4M，通过后量化保存的的权重是量化后的int8的权重，压缩到1.3M，看情况像是你转onnx之后权重又回退到float32的权重，可以排查一下onnx的权重配置

**Comment by jiangjiajun** [comment]
目前Paddle2ONNX还不支持转换量化的模型，如有需求量化，建议使用Paddle2ONNX转ppyolo_tiny的非量化模型，然后使用目标推理引擎的离线量化工具对转换后的ONNX模型进行量化

**Comment by DongChenwei2000** [comment]
> 目前Paddle2ONNX还不支持转换量化的模型，如有需求量化，建议使用Paddle2ONNX转ppyolo_tiny的非量化模型，然后使用目标推理引擎的离线量化工具对转换后的ONNX模型进行量化

请问这个离线量化工具是什么？ 是类似于这种方法对onnx模型量化吗https://github.com/PaddlePaddle/PaddleDetection/issues/2810#issuecomment-829122895
还是说其他的离线量化工具？

**Comment by jiangjiajun** [comment]
例如TensorRT就有自己的量化工具
