### ISSUE TITLE
关于新版ppdet的pretrain_weights链接

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleDetection#2907]
旧版ppdet的obj365预训练模型链接是【https://paddlemodels.bj.bcebos.com/object_detection/ResNet50_vd_dcn_db_obj365_pretrained.tar】，即xxx.tar

新版是xxx.pdparams

请教：我如何在新版填写obj365预训练模型的链接？

**Comment by jerrywgz** [comment]
新版xxx.pdparams格式的权重也是可以被正常加载的，obj365这个预训练模型目前我们只提供了.tar的格式，而且在ppdet2.0版本中，该权重只能在静态图下使用
