### ISSUE TITLE
ppyolov2 评估时报错KeyError: 36

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleDetection#2908]
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/67897601/117564149-33e77580-b0dd-11eb-9445-a105b0706567.png">

**Comment by jerrywgz** [comment]
需要检查anno_file中对应的数据集类别和设置的数据集类别是否一致

**Comment by aishangmaxiaoming** [comment]
> 设置的数据集类别

设置的数据集类别在哪里设置

**Comment by jerrywgz** [comment]
在configs/dataset/coco_detection.yml下

**Comment by heavengate** [comment]
鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen此issue~
