### ISSUE TITLE
MASKrcnn 评估时爆粗

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleDetection#2909]
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/67897601/117564186-6e511280-b0dd-11eb-91e5-74c8e58b3423.png">

**Comment by jerrywgz** [comment]
请问下使用得到ppdet版本和paddle版本是什么呢，另外能否打印下对应位置（expand）的输入shape呢

**Comment by aishangmaxiaoming** [comment]
> 请问下使用得到ppdet版本和paddle版本是什么呢，另外能否打印下对应位置（expand）的输入shape呢

ppdet 2.0。paddle2.0.1

**Comment by jerrywgz** [comment]
使用的是自定义的数据集吗，有这么几种方法可以先试下：
1. 首先在对应报错位置，也就是ppdet/modeling/post_process.py 99行处看下expand对应的输入[bbox_num[i], 2]是否有异常，从log来看可能是某张输入图片的问题
2. 在eval过程中将batch size设置为1，在ppdet/modeling/architectures/mask_rcnn.py中打印下self.inputs['im_id']，然后可以通过这个im_id找到对应的输入图片信息

如果以上方法没有找到问题，可以提供下复现的模型和数据我们来看下
