### ISSUE TITLE
multi scale test for CascadeRCNNClsAware

### ISSUE THREAD

**Issue by sbl1996** [PaddlePaddle/PaddleDetection#291]
I have tried to replace CascadeRCNNClsAware with CascadeRCNN in test directly but got an error as below. The num_classes is 205, so shape in checkpoints is (1024, 820).
![QQ20200302-214633](https://user-images.githubusercontent.com/13728074/75682015-ab4a9980-5ccf-11ea-8851-31feceb38bff.png)

**Comment by qingqing01** [comment]
@sbl1996 Do you mean you use the mode of CascadeRCNNClsAware as pre-train?  If so, need to make sure whether needs to load some parameters, see https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/TRANSFER_LEARNING.md#transfer-learning-in-paddledetection

**Comment by sbl1996** [comment]
The problem is not well-stated. I will close this issue and start a new one.
