### ISSUE TITLE
目标检测CascadeRCNNClsAware现在支持转onnx了吗？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleDetection#2910]
看了下之前的帖子
“此外，转ONNX的模型支持中，对于检测模型目前只支持YOLOv3和SSD系列，RCNN暂不支持。”

现在是否可以，有示例吗?

**Comment by jerrywgz** [comment]
这个模型目前只在静态图模式下，同时也支持了转onnx
