### ISSUE TITLE
训练错误AttributeError: object has no attribute 'architecture'，请问这个怎么解决啊，我在anchor-cluster也遇到了这个错误。

### ISSUE THREAD

**Issue by w2020** [PaddlePaddle/PaddleDetection#2911]
(base) user@user-B404-2:/media/user/新加卷/吴子运1/PaddleDetection-release-2.0$ python tools/train.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml
/home/user/anaconda3/lib/python3.7/site-packages/socks.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Callable
configs/ppyolo/ppyolo_tiny_650e_coco.yml
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 102, in run
    trainer = Trainer(cfg, mode='train')
  File "/media/user/新加卷/吴子运1/PaddleDetection-release-2.0/ppdet/engine/trainer.py", line 60, in __init__
    self.model = create(cfg.architecture)
  File "/media/user/新加卷/吴子运1/PaddleDetection-release-2.0/ppdet/core/workspace.py", line 69, in __getattr__
    raise AttributeError("object has no attribute '{}'".format(key))
AttributeError: object has no attribute 'architecture'

**Comment by jerrywgz** [comment]
请问是否有修改过配置文件或ppdet代码呢，我这边测试ppdet 2.0分支是能正常训练的

**Comment by w2020** [comment]
改过配置文件中的numclass为12，因为改过数据集，换成了自己制作的coco的数据集，用过x2coco.py，然后就想生成自己的anchor，运行anchor-cluster，我用命令跑的时候它说找不到配置文件—c--config,然后在ppdet—utils-cli.py里面填的那个——config路径，然后在用命令也只能加载1000个iter的12%来计算新的anchor，还是会说没有architecture。
如果你没问题，那我再重新下一个代码，在试试。谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月10日(星期一) 上午10:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] 训练错误AttributeError: object has no attribute &#39;architecture&#39;，请问这个怎么解决啊，我在anchor-cluster也遇到了这个错误。 (#2911)





 
请问是否有修改过配置文件或ppdet代码呢，我这边测试ppdet 2.0分支是能正常训练的
