### ISSUE TITLE
请问用cco格式数据的话，paddledetecion里可以查看acc这个指标是多少吗

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2912]

**Comment by jerrywgz** [comment]
目前paddledetection里还只支持coco数据集格式和voc数据集格式的评估，指标的话是mAP，需要将cco格式数据转换为coco或voc数据格式

**Comment by guotongjian** [comment]
> 目前paddledetection里还只支持coco数据集格式和voc数据集格式的评估，指标的话是mAP，需要将cco格式数据转换为coco或voc数据格式

如果我要算acc的话，加代码要在哪个地方加呢

**Comment by jerrywgz** [comment]
我确认下，是希望看coco数据格式的准确率吗

**Comment by guotongjian** [comment]
> 我确认下，是希望看coco数据格式的准确率吗

您好，对的，就是准确率，具体的公式应该是TP+TN/ALL这样算的

**Comment by jerrywgz** [comment]
coco数据集可以使用cocoapi评测，测试结果中红框的部分就是不同IOU对应的准确率的值
![image](https://user-images.githubusercontent.com/22989727/117600251-2fbf6480-b17e-11eb-8fc6-ba32dcbf86f7.png)

**Comment by guotongjian** [comment]
> coco数据集可以使用cocoapi评测，测试结果中红框的部分就是不同IOU对应的准确率的值
> ![image](https://user-images.githubusercontent.com/22989727/117600251-2fbf6480-b17e-11eb-8fc6-ba32dcbf86f7.png)

您好，我想问的不是这个AP值，我想问的是Accuracy=（TP+TN）/（TP+FP+TN+FN），就是基本都是百分之90几，很高的那个值。

**Comment by yghstill** [comment]
@guotongjian 在eval的时候指定--classwise，可输出PR曲线，具体的值也可以在代码中打印https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/ppdet/metrics/coco_utils.py#L125

**Comment by heavengate** [comment]
鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen此issue~
