### ISSUE TITLE
如何找预训练模型

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleDetection#2913]
请问paddle detection有哪些预训练模型呢，有没有汇总呢，想要换backbone的预训练一直找不到！

**Comment by yghstill** [comment]
请问是哪个模型？现在backbone的预训练模型都写在config文件中了，比如faster rcnn：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/faster_rcnn/_base_/faster_rcnn_r50.yml#L2

这些backbone都可以在 https://github.com/PaddlePaddle/PaddleClas 中找到，PaddleDetection做了一些封装
