### ISSUE TITLE
关于TrainReader中sample['gt_class']字段问题

### ISSUE THREAD

**Issue by kali20gakki** [PaddlePaddle/PaddleDetection#2914]
请问sample['gt_class']中的类别序号是从0开始的吗，假设有3类，在BBoxAssigner阶段生成的512个target_label中[0,1,2,3,3,3,3,3,3......3],其中这个3是背景类吗？

**Comment by yghstill** [comment]
@kali20gakki  是的，目前背景类都在最后一维
