### ISSUE TITLE
怎么查看一个目标检测模型的计算量？？

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#2915]
paddle.summay()好像只能查看模型的参数量，如果我想看模型的所需计算量，该怎么查看啊？？

**Comment by yghstill** [comment]
@dengxinlong 如果想查看模型flops，安装paddleslim，使用flops接口可以打印，可以参考如下代码：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/ppdet/slim/prune.py#L68
