### ISSUE TITLE
s2anet 设置anchor

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/PaddleDetection#2917]
如何设置 s2anet中的anchor 配置
```bash
S2ANetHead:
  anchor_strides: [8, 16, 32, 64, 128]
  anchor_scales: [4]
  anchor_ratios: [1.0]
```
如何配置上述的  anchor_strides anchor_scales 以及 anchor_ratios，可否提供相应的脚本. [类似于yolo生成anchor配置那种]

**Comment by liuhuiCNN** [comment]
你好，感谢反馈，这个功能我们后续添加。S2ANet中anchor设置参数跟数据相关的是anchor_ratios，您可以通过对数据中物体框的长宽比进行聚类，根据聚类结果设置anchor_ratios这个参数即可。聚类您可以先参考下yolo生成anchor的代码。
