### ISSUE TITLE
请问近期会支持swin作为backbone吗

### ISSUE THREAD

**Issue by pixeli99** [PaddlePaddle/PaddleDetection#2918]
请问近期会支持swin作为backbone吗？

**Comment by yghstill** [comment]
@lpxgis 感谢关注，Swin Transformer网络正在PaddleClas中开发支持中，应该很快就能推出，之后在检测任务上我们会及时跟进支持这个backbone

**Comment by pixeli99** [comment]
> @lpxgis 感谢关注，Swin Transformer网络正在PaddleClas中开发支持中，应该很快就能推出，之后在检测任务上我们会及时跟进支持这个backbone

了解，感谢您的回复🙏
