### ISSUE TITLE
OSError: (External)  Cublas error, `CUBLAS_STATUS_INVALID_VALUE`. 测试推理出错

### ISSUE THREAD

**Issue by create-li** [PaddlePaddle/PaddleDetection#2922]
OSError: (External)  Cublas error, `CUBLAS_STATUS_INVALID_VALUE`. An unsupported value or parameter was passed to the function (a negative vector size, for example).  (at /paddle/paddle/fluid/platform/cuda_helper.h:93)
PaddleDetection安装成功
但是执行
python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddlemodels.bj.bcebos.com/object_detection/dygraph/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg

报以上错误。
是不是与CUDA环境有关系
CUDA 是11.1版本-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
|-------------------------------+----------------------+------------------
paddlepaddle是2.0.2

**Comment by yghstill** [comment]
@create-li 其他模型有问题吗？确认下在infer的时候显存有多少？可能和版本或显存有关，是否可以先换到cuda 11.0上？
