### ISSUE TITLE
Multi-scale testing for CascadeRCNNClsAware

### ISSUE THREAD

**Issue by sbl1996** [PaddlePaddle/PaddleDetection#293]
Multi-scale testing for CascadeRCNNClsAware is not supported. I think it is rather straightforward to implement it because of its similarity with CascadeRCNN which has support for multi-scale testing.
Is there any plan to support it?

**Comment by jerrywgz** [comment]
Yeah multi-scale test need to add in cascade_rcnn_cls_aware architecture, we will support it soon.

**Comment by littletomatodonkey** [comment]
Thanks for your attention, you can refer to #303  to use mstest on your cascade rcnn clsaware model.
