### ISSUE TITLE
trainer.py 添加打印代码无效阿

### ISSUE THREAD

**Issue by EdwardVincentMa** [PaddlePaddle/PaddleDetection#2930]
想调试 添加删除打印信息无效，为什么

**Comment by yghstill** [comment]
@EdwardVincentMa 具体想在哪里打印？ppdet中打印log等都使用callback的形式打印。

**Comment by EdwardVincentMa** [comment]
![Screenshot from 2021-05-11 12-38-48](https://user-images.githubusercontent.com/39480728/117759316-2acde400-b256-11eb-9742-4e191d8077ac.png)
您好，打印如图中第376行：

**Comment by yghstill** [comment]
@EdwardVincentMa 你执行的是tools/infer.py吗，理论上执行tools/infer.py这里print会打印出来

**Comment by EdwardVincentMa** [comment]
> @EdwardVincentMa 你执行的是tools/infer.py吗，理论上执行tools/infer.py这里print会打印出来

打印不出来的 @yghstill

**Comment by EdwardVincentMa** [comment]
> @EdwardVincentMa 你执行的是tools/infer.py吗，理论上执行tools/infer.py这里print会打印出来

是infer.py

**Comment by EdwardVincentMa** [comment]
您好，这个问题至今没有解决，后面即使build setup 也不行 @yghstill

**Comment by EdwardVincentMa** [comment]
任何paddle除了main函数之外的代码添加打印或者删除打印信息都没用，即便使用命令python setup.py build

**Comment by raymondchu-z** [comment]
同问，怎么调试？断点也无效 @yghstill
