### ISSUE TITLE
请问是否可以使用多个FPN的融合？

### ISSUE THREAD

**Issue by Hanqingliu-radiology** [PaddlePaddle/PaddleDetection#2931]
例如我想在libra rcnn中将BFP和HRFPN融合起来应该如何操作？

**Comment by yghstill** [comment]
@visionary0421 可以使用HRFPN的架构，然后在refine阶段使用non-local，做到两者的融合https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/static/ppdet/modeling/backbones/bfp.py#L113
