### ISSUE TITLE
mixup_epoch 训练报错

### ISSUE THREAD

**Issue by Dushuhui** [PaddlePaddle/PaddleDetection#2932]
![image](https://user-images.githubusercontent.com/33934457/117750869-bb9cc380-b246-11eb-9efb-a61ba172b830.png)
会报如下错误，和我设置的mixup_epoch的数值有关
![image](https://user-images.githubusercontent.com/33934457/117751010-f999e780-b246-11eb-8898-703ebc8139a1.png)

**Comment by wangxinxin08** [comment]
可以将worker_num设置成0看下具体的报错原因吧
