### ISSUE TITLE
快速体验报错

### ISSUE THREAD

**Issue by tatianna0** [PaddlePaddle/PaddleDetection#2938]
前面安装并没有报错，但在快速体验中最后结果如下图，请问可能因为哪些原因导致
![image](https://user-images.githubusercontent.com/38658920/117766059-8e114380-b261-11eb-916a-14c2d8195662.png)

**Comment by Apokar** [comment]
俺也一样,不知道咋回事

**Comment by Apokar** [comment]
@tatianna0 哥们我试出来原因了 你换个weights 比如:
`python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg`

**Comment by tatianna0** [comment]
谢谢哈~
