### ISSUE TITLE
SSD在coco上训练好的模型是不是没有啊？？

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#2941]
![image](https://user-images.githubusercontent.com/32217129/117777439-2e219980-b26f-11eb-8df6-7ac177149110.png)
在 上图的链接中下载的是关于SSD-VGG16的预训练模型，我想问一下有没有在coco数据集上训练好的模型啊？？

**Comment by liuhuiCNN** [comment]
你好，静态图下SSD有coco训练模型，请参考：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/static/configs/ssd

**Comment by yghstill** [comment]
@dengxinlong https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/static/docs/MODEL_ZOO_cn.md#ssd
您图中的预训练权重是在coco上训好的
