### ISSUE TITLE
训练问题：一开始训练应该是正常的，后面loss就全是nan

### ISSUE THREAD

**Issue by yuemengrui** [PaddlePaddle/PaddleDetection#2942]
![image](https://user-images.githubusercontent.com/24349763/117780371-244d6580-b272-11eb-9af2-89d192f394f9.png)

**Comment by DongChenwei2000** [comment]
+1，请问你是ppyolov2吗

**Comment by yuemengrui** [comment]
> +1，请问你是ppyolov2吗

是的

**Comment by ANewAnonymous** [comment]
> > +1，请问你是ppyolov2吗
> 
> 是的

你的初始学习率是多少？是否因为太高导致的？如果默认的学习率是为8卡GPU训练配置的，请尝试将学习率除以8

**Comment by liuhuiCNN** [comment]
请检查学习率是否正确，配置文件中默认是采用8卡训练，如果您用1卡的话，学习率需要除以8
