### ISSUE TITLE
voc数据集设置

### ISSUE THREAD

**Issue by tatianna0** [PaddlePaddle/PaddleDetection#2950]
请问use_default_label这个在哪
![image](https://user-images.githubusercontent.com/38658920/117806041-5966b180-b28c-11eb-8099-29243a546812.png)

**Comment by liuhuiCNN** [comment]
是的，use_default_label=True，使用默认的voc数据集label。use_default_label=False，从label_list.txt读取类别列表。自定义数据需要设置为False，并提供数据的 label_list.txt 文件。

**Comment by tatianna0** [comment]
> 是的，use_default_label=True，使用默认的voc数据集label。use_default_label=False，从label_list.txt读取类别列表。自定义数据需要设置为False，并提供数据的 label_list.txt 文件。

非常不好意思打扰一下，use_default_label这个属性是需要自己在reader中添加吗，还是在哪个文件里面

**Comment by tatianna0** [comment]
> > > 是的，use_default_label=True，使用默认的voc数据集label。use_default_label=False，从label_list.txt读取类别列表。自定义数据需要设置为False，并提供数据的 label_list.txt 文件。
> > 
> > 
> > 非常不好意思打扰一下，use_default_label这个属性是需要自己在reader中添加吗，还是在哪个文件里面
> 
> 如果你要用自己的label 需要自己在数据集的配置文件中添加 use_default_label=True并且添加label_list指向你的label_list.txt文件

那请问在数据配置中这个错误的原因是什么
![image](https://user-images.githubusercontent.com/38658920/117823395-01d24100-b2a0-11eb-80a8-e615f8818221.png)

**Comment by ANewAnonymous** [comment]
> > > > 是的，use_default_label=True，使用默认的voc数据集label。use_default_label=False，从label_list.txt读取类别列表。自定义数据需要设置为False，并提供数据的 label_list.txt 文件。
> > > 
> > > 
> > > 非常不好意思打扰一下，use_default_label这个属性是需要自己在reader中添加吗，还是在哪个文件里面
> > 
> > 
> > 如果你要用自己的label 需要自己在数据集的配置文件中添加 use_default_label=True并且添加label_list指向你的label_list.txt文件
> 
> 那请问在数据配置中这个错误的原因是什么
> ![image](https://user-images.githubusercontent.com/38658920/117823395-01d24100-b2a0-11eb-80a8-e615f8818221.png)

提供一下你的yml配置文件

**Comment by tatianna0** [comment]
> > > > > 是的，use_default_label=True，使用默认的voc数据集label。use_default_label=False，从label_list.txt读取类别列表。自定义数据需要设置为False，并提供数据的 label_list.txt 文件。
> > > > 
> > > > 
> > > > 非常不好意思打扰一下，use_default_label这个属性是需要自己在reader中添加吗，还是在哪个文件里面
> > > 
> > > 
> > > 如果你要用自己的label 需要自己在数据集的配置文件中添加 use_default_label=True并且添加label_list指向你的label_list.txt文件
> > 
> > 
> > 那请问在数据配置中这个错误的原因是什么
> > ![image](https://user-images.githubusercontent.com/38658920/117823395-01d24100-b2a0-11eb-80a8-e615f8818221.png)
> 
> 提供一下你的yml配置文件

我想要用ppyolo_r50vd_dcn_voc.yml做训练，然后可能做得不太对，ppyolo_reader.yml里面斜体加粗的dataset是我自己加的
ppyolo_reader.yml文件如下

worker_num: 2
TrainReader:
  inputs_def:
    num_max_boxes: 50
  _**dataset:
      !VOCDataSet
      anno_path: trainval.txt   
      dataset_dir: dataset/voc  
      use_default_label: false  
      with_background: false**_  
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 50}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]], downsample_ratios: [32, 16, 8]}
  batch_size: 15
  shuffle: true
  drop_last: true
  mixup_epoch: 20
  use_shared_memory: true

  

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [608, 608], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 8
  drop_empty: false

TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [608, 608], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1


谢谢！

**Comment by sannnyu** [comment]
@tatianna0 您好，解决了吗？
