### ISSUE TITLE
ppyolov2的评估问题

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleDetection#2951]
评估ppyolov2时出现如下错误。
![{ME`O QF~QS% OBW1VISIR1](https://user-images.githubusercontent.com/71364549/117808102-10642c80-b28f-11eb-950c-9558acc178a1.png)

**Comment by liuhuiCNN** [comment]
请您检查一下数据路径配置是否正确？

**Comment by DongChenwei2000** [comment]
> 请您检查一下数据路径配置是否正确？

是正确的，这个issue也是同样的问题。https://github.com/PaddlePaddle/PaddleDetection/issues/2733#issue-864508304 我看有人说develop版修复了，是release没修复吗？这个pr： https://github.com/PaddlePaddle/PaddleDetection/pull/2731#issue-620411685 中的文件和release中的完全不一样，我不大清楚如何修改。

**Comment by ANewAnonymous** [comment]
> > 请您检查一下数据路径配置是否正确？
> 
> 是正确的，这个issue也是同样的问题。[#2733 (comment)](https://github.com/PaddlePaddle/PaddleDetection/issues/2733#issue-864508304) 我看有人说develop版修复了，是release没修复吗？这个pr： [#2731 (comment)](https://github.com/PaddlePaddle/PaddleDetection/pull/2731#issue-620411685) 中的文件和release中的完全不一样，我不大清楚如何修改。

2.0版本存在着voc数据评估时的bug  建议使用develop版本
