### ISSUE TITLE
训练voc 数据集如何重置下载？

### ISSUE THREAD

**Issue by EdwardVincentMa** [PaddlePaddle/PaddleDetection#2952]
你好，我在训练ppyolo_tiny时，因为又开了一个训练，显示错误。然后voc 数据集下载一半报错了，我就把.cache文件夹下的voc图像删除了，想重新下载训练，只删除了一个。可以看到，一个数据集删除后确实从头下载了，但另一个数据集还是从81%开始。但我想全部都删除。
 1%|          | 15193/1952773 [00:32<2:30:55, 213.96KB/s]
 81%|████████▏ | 358091/440450 [14:31<11:37, 118.14KB/s]

我想问问下载的数据集如何全部删除并重新下载训练。

只删除.cache\VOC 文件夹会显示：
No such file or directory: '/home/mayc1/.cache/paddle/dataset/voc/VOCtest_06-Nov-2007.tar_tmp'

**Comment by liuhuiCNN** [comment]
(1) 等数据下载完后再开始训练

**Comment by EdwardVincentMa** [comment]
> (1) 等数据下载完后再开始训练

会出现找不到label_list.txt这样的错误:
base) mayc1@xt021pc2101001:~/PyProject/PaddleDetection$ python -m paddle.distributed.launch --log_dir=./ppyolo_dygraph/ --gpus 0 tools/train.py -c configs/ppyolo/ppyolo_tiny_650e_voc.yml |&tee train_ppyolo_tiny_voc_20210511.log
WARNING 2021-05-12 10:52:58,445 launch.py:315] Not found distinct arguments and compiled with cuda. Default use collective mode
INFO 2021-05-12 10:52:58,445 launch_utils.py:468] Local start 1 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:50313               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:50313               |
    |                     FLAGS_selected_gpus                        0                      |
    +=======================================================================================+

INFO 2021-05-12 10:52:58,445 launch_utils.py:473] details abouts PADDLE_TRAINER_ENDPOINTS can be found in ./ppyolo_dygraph//endpoints.log, and detail running logs maybe found in ./ppyolo_dygraph//workerlog.0
INFO 2021-05-12 10:53:04,453 launch_utils.py:307] terminate all the procs
ERROR 2021-05-12 10:53:04,454 launch_utils.py:543] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-05-12 10:53:07,457 launch_utils.py:307] terminate all the procs
-----------  Configuration Arguments -----------
gpus: 0
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: ./ppyolo_dygraph/
nproc_per_node: None
server_num: None
servers: 
training_script: tools/train.py
training_script_args: ['-c', 'configs/ppyolo/ppyolo_tiny_650e_voc.yml']
worker_num: None
workers: 
------------------------------------------------
launch train in GPU mode
W0512 10:52:59.492961 563731 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.0
W0512 10:52:59.494197 563731 device_context.cc:372] device: 0, cuDNN Version: 8.0.
[05/12 10:53:00] ppdet.utils.download INFO: Dataset /home/mayc1/PyProject/PaddleDetection/dataset/voc is not valid for reason above, try searching /home/mayc1/.cache/paddle/dataset or downloading dataset...
[05/12 10:53:00] ppdet.utils.download INFO: Found /home/mayc1/.cache/paddle/dataset/voc/VOCdevkit/VOC2012
[05/12 10:53:00] ppdet.utils.download INFO: Found /home/mayc1/.cache/paddle/dataset/voc/VOCdevkit/VOC2007
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 102, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/engine/trainer.py", line 73, in __init__
    self.loader = create('{}Reader'.format(self.mode.capitalize()))(
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/data/reader.py", line 170, in __call__
    self.dataset.parse_dataset()
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/data/source/voc.py", line 74, in parse_dataset
    raise ValueError("label_list {} does not exists".format(
ValueError: label_list /home/mayc1/.cache/paddle/dataset/voc/label_list.txt does not exists




如果把label_list.txt拷贝到.cache下，还会继续报错

**Comment by fash120** [comment]
@EdwardVincentMa 我想请问一下是怎么解决的呢
