### ISSUE TITLE
reader WARNING: fail to map op [Decode_6e15d6] with error: 'im_file' and stack:

### ISSUE THREAD

**Issue by a794133319** [PaddlePaddle/PaddleDetection#2956]
![image](https://user-images.githubusercontent.com/55074811/117833945-5928df00-b2a9-11eb-868e-933f16dee6c5.png)
如图，头秃死了

**Comment by a794133319** [comment]
这是使用ppyolo-tiny报的错，使用的是自己的voc数据集

**Comment by liuhuiCNN** [comment]
建议您参考这个配置文件进行修改：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/ppyolo/ppyolo_r50vd_dcn_voc.yml

**Comment by a794133319** [comment]
> 建议您参考这个配置文件进行修改：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/ppyolo/ppyolo_r50vd_dcn_voc.yml

我后来尝试使用路标voc数据集跑，配置改为roadsign_voc.yml,能够正常运行，发现是跟voc.yml中的map_type不同，后来改掉map_type跟roadsign的相同后，发现说数据集验证失败，那么map_type代表什么意思啊？

**Comment by a794133319** [comment]
> 建议您参考这个配置文件进行修改：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/ppyolo/ppyolo_r50vd_dcn_voc.yml

参照这个修改的话,voc.yml里的map_type需要更改吗

**Comment by liuhuiCNN** [comment]
> > 建议您参考这个配置文件进行修改：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/ppyolo/ppyolo_r50vd_dcn_voc.yml
> 
> 参照这个修改的话,voc.yml里的map_type需要更改吗

不需要了。

**Comment by a794133319** [comment]
> > > 建议您参考这个配置文件进行修改：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/ppyolo/ppyolo_r50vd_dcn_voc.yml
> > 
> > 
> > 参照这个修改的话,voc.yml里的map_type需要更改吗
> 
> 不需要了。

更改后又报了新的错误
Traceback (most recent call last):
  File "tools/anchor_cluster.py", line 363, in <module>
    main()
  File "tools/anchor_cluster.py", line 359, in main
    anchors = cluster()
  File "tools/anchor_cluster.py", line 95, in __call__
    self.get_whs()
  File "tools/anchor_cluster.py", line 73, in get_whs
    h, w = rec['h'], rec['w']
KeyError: 'h'

**Comment by a794133319** [comment]
> > > 建议您参考这个配置文件进行修改：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/ppyolo/ppyolo_r50vd_dcn_voc.yml
> > 
> > 
> > 参照这个修改的话,voc.yml里的map_type需要更改吗
> 
> 不需要了。
![image](https://user-images.githubusercontent.com/55074811/117912526-426aa280-b312-11eb-9c86-3bcf1d007d8d.png)
![image](https://user-images.githubusercontent.com/55074811/117912544-48f91a00-b312-11eb-8d18-5fc83a7180c0.png)
![image](https://user-images.githubusercontent.com/55074811/117912572-51e9eb80-b312-11eb-9081-fe9176914004.png)
更改后还是报错

**Comment by coderShenhy** [comment]
@a794133319 我也遇见了这个问题，最后怎么解决的呢，是因为配置文件的问题吗？

**Comment by coderShenhy** [comment]
解决了，voc.yml中的data_fields 不能改
