### ISSUE TITLE
retinanet

### ISSUE THREAD

**Issue by luuuyi** [PaddlePaddle/PaddleDetection#2961]
你好，问一下，目前动态图版本是不是还不支持retinanet

**Comment by wangxinxin08** [comment]
目前动态图中没有retinanet，你可以使用static目录下面静态图的retinanet

**Comment by luuuyi** [comment]
@wangxinxin08 
目前静态图里面所有的模型后续都会在动态图里面支持么

**Comment by wangxinxin08** [comment]
有些可能不会支持了，retinanet我们原先考虑的结论是不迁移到动态图

**Comment by luuuyi** [comment]
@wangxinxin08 啊 这样么 那些不考虑迁到动态图的方法是出于什么考量么 我理解paddlepaddle之后应该会主推动态了 按道理应该是都迁到动态才符合大方向才对？

**Comment by wangxinxin08** [comment]
主要看模型的需求情况，从issue上来看，retinanet的需求比较少，因此考虑不迁移到动态图，如果后续需求增加，也会考虑支持
