### ISSUE TITLE
关于PP-YOLOV2的TensorRT推理

### ISSUE THREAD

**Issue by DeathKnightChen** [PaddlePaddle/PaddleDetection#2962]
ppyolov2里有公开tensorrt的性能，似乎是paddle预测库跑的，但是我看了下tensorrt好像不支持deformable conv操作，那用paddle预测库跑ppyolov2的tensorrt是如何跑起来的呢，想请教下

**Comment by yghstill** [comment]
@DeathKnightChen paddle预测库在预测时遇到deformable conv会跳过，不会进trt中计算
