### ISSUE TITLE
Cublas error, `CUBLAS_STATUS_NOT_INITIALIZED`

### ISSUE THREAD

**Issue by ayicherry** [PaddlePaddle/PaddleDetection#2967]
电脑环境：乌班图，CUDA10.1  cudnn8.0  python3.8

在安装paddlePaddle时用的是 python -m pip install paddlepaddle-gpu==2.0.1.post101 -f https://mirror.baidu.com/pypi/simple
安装成功，但是在运行验证代码paddle.utils.run_check()时报错，错误信息是
OSError: (External)  Cublas error, `CUBLAS_STATUS_NOT_INITIALIZED`. The cuBLAS library was not initialized.  (at /paddle/paddle/fluid/platform/cuda_helper.h:84)

请问cuBlas是需要单独安装吗？

**Comment by ayicherry** [comment]
暂时搞定了

**Comment by zhaolz123** [comment]
> 暂时搞定了

请问是怎么解决的呢
