### ISSUE TITLE
自定奕数据集找不到

### ISSUE THREAD

**Issue by chuanfuye** [PaddlePaddle/PaddleDetection#2969]
系统：Ubuntu18.04
ppdet.utils.download INFO: Dataset /home/wt_yechuanfu/work_code/2weima is not valid for reason above, try searching /home/wt_yechuanfu/.cache/paddle/dataset or downloading dataset...
Traceback (most recent call last):
  File "tools/train.py", line 137, in <module>
    main()
  File "tools/train.py", line 133, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 102, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/wt_yechuanfu/work_code/PaddleDetection/ppdet/engine/trainer.py", line 74, in __init__
    self.dataset, cfg.worker_num)
  File "/home/wt_yechuanfu/work_code/PaddleDetection/ppdet/data/reader.py", line 171, in __call__
    self.dataset.check_or_download_dataset()
  File "/home/wt_yechuanfu/work_code/PaddleDetection/ppdet/data/source/dataset.py", line 91, in check_or_download_dataset
    self.image_dir)
  File "/home/wt_yechuanfu/work_code/PaddleDetection/ppdet/utils/download.py", line 210, in get_dataset_path
    format(path, osp.split(path)[-1]))
ValueError: Dataset /home/wt_yechuanfu/work_code/2weima is not valid and cannot parse dataset type '2weima' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face', 'fruit' and 'roadsign_voc' currently
改了多次路径还是不对，总是自动下载默认数据集，我的数据集名称为2weima，是哪里的环境变量没有设置么

**Comment by wangxinxin08** [comment]
自定义数据集需要修改configs/datasets/里面的配置文件，如果是voc数据集需要修改configs/datasets/voc.yml，如果是coco数据集，需要修改configs/datasets/coco_detection.yml或者configs/datasets/coco_instance.yml

**Comment by chuanfuye** [comment]
> 自定义数据集需要修改configs/datasets/里面的配置文件，如果是voc数据集需要修改configs/datasets/voc.yml，如果是coco数据集，需要修改configs/datasets/coco_detection.yml或者configs/datasets/coco_instance.yml
 
metric: COCO
num_classes: 4

TrainDataset:
  !COCODataSet
    image_dir: images
    anno_path: annotations/instances_train.json
    dataset_dir: /home/wt_yechuanfu/work_code/2weima/
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: images
    anno_path: annotations/instances_val.json
    dataset_dir: /home/wt_yechuanfu/work_code/2weima/

TestDataset:
  !ImageFolder
    anno_path: /home/wt_yechuanfu/work_code/2weima/annotations/val.json

在configs/datasets/coco_detection.yml配置文件修改自己的数据集路径还是会报错

**Comment by wangxinxin08** [comment]
这个格式好像有问题，有缩进的

**Comment by chuanfuye** [comment]
> 这个格式好像有问题，有缩进的

和下面的图一样，复制成文字会变成这样格式问题。
![image](https://user-images.githubusercontent.com/55446206/117949103-59c28380-b344-11eb-9b53-9009ff98b2d7.png)

**Comment by wangxinxin08** [comment]
可以贴一下 /home/wt_yechuanfu/work_code/2weima 文件下的文件可以贴个截图吗

**Comment by chuanfuye** [comment]
![image](https://user-images.githubusercontent.com/55446206/117950121-71e6d280-b345-11eb-901a-3d34d78c6c2e.png)
![image](https://user-images.githubusercontent.com/55446206/117950160-7ca16780-b345-11eb-8026-8022abe922ef.png)

**Comment by chuanfuye** [comment]
路径错了。打扰了。。。。

**Comment by chuanfuye** [comment]
instance--instances
