### ISSUE TITLE
ppyolo_tiny 如何调整训练图像输入尺寸

### ISSUE THREAD

**Issue by EdwardVincentMa** [PaddlePaddle/PaddleDetection#2972]
你好，我找到了测试图像输入尺寸，没找到训练尺寸：
worker_num: 4
TrainReader:
  inputs_def:
    num_max_boxes: 100
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [192, 224, 256, 288, 320, 352, 384, 416, 448, 480, 512], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 100}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[10, 15], [24, 36], [72, 42], [35, 87], [102, 96], [60, 170], [220, 125], [128, 222], [264, 266]], downsample_ratios: [32, 16, 8]}
  batch_size: 4
  shuffle: true
  drop_last: true
  mixup_epoch: 500
  use_shared_memory: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [416, 416], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 8
  drop_empty: false

TestReader:
  inputs_def:
    image_shape: [3, 800, 800]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [800, 800], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1

请问在那里修改训练图像尺寸。

**Comment by wangxinxin08** [comment]
训练时图像的尺寸是Random选取的，可以在BatchRandomResize里面设置，里面的每一个size都会被均匀采样

**Comment by raymondchu-z** [comment]
> 训练时图像的尺寸是Random选取的，可以在BatchRandomResize里面设置，里面的每一个size都会被均匀采样

那这样的话，设置anchor的大小时-s的参数应该怎么设置？

**Comment by wangxinxin08** [comment]
@raymondchu-z 根据推理时的尺寸进行选取

**Comment by raymondchu-z** [comment]
@wangxinxin08 好的 感谢回复
