### ISSUE TITLE
ppyolov2 Dygraph 训练极慢

### ISSUE THREAD

**Issue by syswyl** [PaddlePaddle/PaddleDetection#2974]
- 使用最新发布的动态图版本，针对ppyolov2在自定义数据集上训练，使用[ppyolov2](https://paddledet.bj.bcebos.com/models/ppyolov2_r101vd_dcn_365e_coco.pdparams)模型和对应config文件。
- 数据集参照readme准备为[VOC](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/docs/tutorials/PrepareDataSet.md#%E7%94%A8%E6%88%B7%E6%95%B0%E6%8D%AE%E8%BD%AC%E6%88%90voc%E6%95%B0%E6%8D%AE)格式。
- 集群配置： 因为我配置NCCL似乎没有成功，所以使用单卡训练
> 显卡： RTX2080TI 12G 
cpu 关键信息 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
CPU(s):              56
Core(s) per socket:  14
Model name:          Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.1, Runtime API Version: 10.0 cuDNN Version: 7.6.

- 文件配置：参考[FAQ](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/static/docs/FAQ.md) 进行了学习率修改，具体如下：
1. ppyolov2_r101vd_dcn_365e_coco.yml
> _BASE_: [
  '../datasets/voc.yml',
  '../runtime.yml',
  './_base_/ppyolov2_r50vd_dcn.yml',
  './_base_/optimizer_365e.yml',
  './_base_/ppyolov2_reader.yml',
]
>snapshot_epoch: 50
>weights: output/ppyolov2_res101_coco_640/0512/
>pretrain_weights: /opt/data/private/ss/local-cloud-file/PaddleDetection/weights/ppyolov2_res101_coco_640.pdparams(自己修改了文件名，不影响加载)
ResNet:
  depth: 101
  variant: d
  return_idx: [1, 2, 3]
  dcn_v2_stages: [3]
  freeze_at: -1
  freeze_norm: false
  norm_decay: 0.

2. optimizer_365e.yml
> **epoch: 250**
>LearningRate:
  **base_lr: 0.000125**
  schedulers:
> -!PiecewiseDecay
    gamma: 0.1
    milestones:
    - 243
 >-!LinearWarmup
    start_factor: 0.
    steps: 4000
>OptimizerBuilder:
  clip_grad_by_norm: 35.
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

3. ppyolov2_r50vd_dcn.yml
> architecture: YOLOv3
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_ssld_pretrained.pdparams
norm_type: sync_bn
use_ema: true
ema_decay: 0.9998
>YOLOv3:
  backbone: ResNet
  neck: PPYOLOPAN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess
>ResNet:
  depth: 50
  variant: d
  return_idx: [1, 2, 3]
  dcn_v2_stages: [3]
  freeze_at: -1
  freeze_norm: false
  norm_decay: 0.
>PPYOLOPAN:
  drop_block: true
  block_size: 3
  keep_prob: 0.9
  spp: true
>YOLOv3Head:
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  loss: YOLOv3Loss
  iou_aware: true
  iou_aware_factor: 0.5
>YOLOv3Loss:
  ignore_thresh: 0.7
  downsample: [32, 16, 8]
  label_smooth: false
  scale_x_y: 1.05
  iou_loss: IouLoss
  iou_aware_loss: IouAwareLoss
>IouLoss:
  loss_weight: 2.5
  loss_square: true
>IouAwareLoss:
  loss_weight: 1.0
>BBoxPostProcess:
  decode:
    name: YOLOBox
    conf_thresh: 0.01
    downsample_ratio: 32
    clip_bbox: true
    scale_x_y: 1.05
  nms:
    name: MatrixNMS
    keep_top_k: 100
    score_threshold: 0.01
    post_threshold: 0.01
    nms_top_k: -1
    background_label: -1
4. ppyolov2_reader.yml
> **worker_num: 4**
TrainReader:
  inputs_def:
    num_max_boxes: 100
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 100}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[15, 20], [13, 27], [27, 25], [19, 47], [34, 32], [41, 41], [78, 45], [74, 83], [121, 105]], downsample_ratios: [32, 16, 8]}
  **batch_size: 2**
  shuffle: true
  drop_last: true
  mixup_epoch: 25000
  use_shared_memory: true
>EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1
  drop_empty: false
>TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1

- 过程资源查看如下：nvidia-smi  top
![nvidia-smi](https://user-images.githubusercontent.com/29301581/117991039-47f6d580-b370-11eb-8455-616fc7bf6dd0.png)

![top](https://user-images.githubusercontent.com/29301581/117992174-4a0d6400-b371-11eb-9c32-9b2fd08f1863.png)

- **训练过程极其缓慢** epoch250 耗时11天，我想这个成本应该太大了， 不清楚是否是我哪一部分出问题了 
![训练过程](https://user-images.githubusercontent.com/29301581/117990545-d6b72280-b36f-11eb-9c70-69e5277f5c6a.png)

**希望得到回复~~ THX**

**Comment by syswyl** [comment]
补充：图像大概2W张，大小为1280*1080 或者640*360

**Comment by wangxinxin08** [comment]
建议使用多卡进行训练，ppyolov2模型默认使用8卡训练，另外可以尽可能地把worker_num开的大一些，ppyolo总的训练时长确实比较长，另外可以考虑使用ppyolov2_r50vd_dcn这个模型，这个会相对快一些，精度也不会下降多少，至于ppyolo训练时长的问题，后续会排期优化

**Comment by shyn** [comment]
希望早日优化，同样单卡，r50 也是很慢。

windows 10 环境，rtx 2080 8G，ppyolov2_r50vd_dcn
观察 cuda 使用情况，没有完全利用， 60% 左右，独立显存使用大概 6G。

cmd 有时似乎卡死，cuda 使用降到 0.

**Comment by raymondchu-z** [comment]
> 建议使用多卡进行训练，ppyolov2模型默认使用8卡训练，另外可以尽可能地把worker_num开的大一些，ppyolo总的训练时长确实比较长，另外可以考虑使用ppyolov2_r50vd_dcn这个模型，这个会相对快一些，精度也不会下降多少，至于ppyolo训练时长的问题，后续会排期优化

你好，默认的worker_num是2，请问这个参数和什么有关？推荐设置成多少？
