### ISSUE TITLE
ppyolo量化训练map一直为0

### ISSUE THREAD

**Issue by shendaw** [PaddlePaddle/PaddleDetection#2978]
release 0.5 版本
任务训练完成后，map为0.88。加载该模型进行量化感知训练：
```
python slim/quantization/train.py
-c quantize_train.yml
--eval
```
量化训练一万步，每2000步eval一次，每次eval的map都是0：
![e8452c2bf8386497cdf1d7ce8afa763](https://user-images.githubusercontent.com/68847312/118066458-59bc9500-b3d1-11eb-838a-766c7780bf2c.jpg)

加载产出的量化模型进行推理，debug发现维度本应该是[N*6]的输出，结果却是1维的，不论什么输入，值一直为-1。
求解答！

**Comment by yghstill** [comment]
@shendaw ppyolo量化要drop_block设为false，因为量化子图构建drop_block会对训练造成很大的干扰：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/static/configs/ppyolo/ppyolo.yml#L43

**Comment by shendaw** [comment]
> @shendaw ppyolo量化要drop_block设为false，因为量化子图构建drop_block会对训练造成很大的干扰：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/static/configs/ppyolo/ppyolo.yml#L43

我日，真解决了，跪谢大佬！
