### ISSUE TITLE
ppyolov2 keyerror

### ISSUE THREAD

**Issue by 255isWhite** [PaddlePaddle/PaddleDetection#2979]
```
zephyrus@billie:~/PaddleDetection$ python -u tools/train.py -c configs/ppyolo/ppyolov2.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar --eval -o use_gpu=true
/home/zephyrus/.local/lib/python3.8/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/home/zephyrus/.local/lib/python3.8/site-packages/paddle/tensor/creation.py:143: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0513 11:37:45.306433  9576 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.0
W0513 11:37:45.307940  9576 device_context.cc:372] device: 0, cuDNN Version: 8.1.
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 102, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/zephyrus/.local/lib/python3.8/site-packages/ppdet/engine/trainer.py", line 73, in __init__
    self.loader = create('{}Reader'.format(self.mode.capitalize()))(
  File "/home/zephyrus/.local/lib/python3.8/site-packages/ppdet/data/reader.py", line 170, in __call__
    self.dataset.parse_dataset()
  File "/home/zephyrus/.local/lib/python3.8/site-packages/ppdet/data/source/voc.py", line 136, in parse_dataset
    gt_class.append([cname2cid[cname]])
KeyError: 'r'
```

**Comment by qingqing01** [comment]
@billie7 您是自定义数据集吗？看起来是VOC格式，像是label格式不太对

**Comment by 255isWhite** [comment]
@qingqing01  检查了发现确实是label问题,但在跑完一个epoch后就会自动停止,并出现这个问题
[ERROR 2021-05-13 15:02:23,502 dataloader_iter.py:605] DataLoader reader thread raised an exception!
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

**Comment by syswyl** [comment]
> @qingqing01 检查了发现确实是label问题,但在跑完一个epoch后就会自动停止,并出现这个问题
> [ERROR 2021-05-13 15:02:23,502 dataloader_iter.py:605] DataLoader reader thread raised an exception!
> SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
> [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

这个问题在其他issue中有人提到过，可以搜索来参考着改改

**Comment by 255isWhite** [comment]
@syswyl 自己试了下去掉--eval就可以训练了,我去搜搜改进吧,感谢

**Comment by zhchma51** [comment]
你可以把ppyolov2_reader.yml里的batch_size改为1，我测试的也可以运行。

**Comment by zzzfo** [comment]
请问你解决这个问题了吗，我也遇到了这样的问题，我使用ppyolov2训练自己的数据集
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 102, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/wumei/anaconda3/envs/pp/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/engine/trainer.py", line 63, in __init__
    self.dataset, cfg.worker_num)
  File "/home/wumei/anaconda3/envs/pp/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/data/reader.py", line 165, in __call__
    self.dataset.parse_dataset()
  File "/home/wumei/anaconda3/envs/pp/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/data/source/voc.py", line 136, in parse_dataset
    gt_class.append([cname2cid[cname]])
KeyError: 'person'
