### ISSUE TITLE
infer时用image_dir，但是每个图片检测了两次

### ISSUE THREAD

**Issue by HotCoCoC** [PaddlePaddle/PaddleDetection#298]
![O 63N%A( 9 _)((ZNIQIK%8](https://user-images.githubusercontent.com/35756751/75776722-7d2c8e80-5d8f-11ea-8b68-62e115a302b9.png)
![3R0VUY L84$ QN~$Q$E1G@D](https://user-images.githubusercontent.com/35756751/75776743-8c134100-5d8f-11ea-81cf-b2abf08dd108.png)
我将image的路径打了出来确实是一个图片检验了两次
命令如下：python -u tools/infer.py -c configs/cascade_rcnn_r50_fpn_1x.yml -o weights=output\cascade_rcnn_r50_fpn_1x\40000 --infer_dir=demo/test --output_dir=infer_output/testout

**Comment by HotCoCoC** [comment]
![image](https://user-images.githubusercontent.com/35756751/75779277-4efd7d80-5d94-11ea-8f04-56fbffce3901.png)
据我推测，是这个地方出现了问题，exts加了它自己

**Comment by jerrywgz** [comment]
我这边在linux环境下是检验一次的，我在windows中在验证下，可能和环境有关

**Comment by qingqing01** [comment]
Fixed by #300
