### ISSUE TITLE
paddle paddle 编译tensorRT cmake 报错,cuda=10.0.3 paddle=2.0.2 cmake=3.16.8

### ISSUE THREAD

**Issue by Williamlizl** [PaddlePaddle/PaddleDetection#2988]
`CMake Error at cmake/configure.cmake:101 (message):
  Paddle needs CUDA >= 10.1 to compile
Call Stack (most recent call first):
  CMakeLists.txt:306 (include)`

**Comment by qingqing01** [comment]
首先这个问题，提示需要CUDA版本>=10.1，您需要检查CUDA版本。

您也可以不源码编译:

如果您是Paddle-Inference C++推理，可以 这里 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html#linux  下载TensorRT (trt)的包。

如果是Paddle-Inference Python推理，可以 这里  https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release 下载带trt的PaddlePaddle Python  whl安装包。

**Comment by Williamlizl** [comment]
> 首先这个问题，提示需要CUDA版本>=10.1，您需要检查CUDA版本。
> 
> 您也可以不源码编译:
> 
> 如果您是Paddle-Inference C++推理，可以 这里 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/build_and_install_lib_cn.html#linux 下载TensorRT (trt)的包。
> 
> 如果是Paddle-Inference Python推理，可以 这里 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release 下载带trt的PaddlePaddle Python whl安装包。

按照说明安装了cuda10.0-cudnn7.6-trt6.0.1.5，尝试后：
`FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1620979626 (unix time) try "date -d @1620979626" if you are using GNU date ***]`
--run_mode trt_fp16 报错；fluid 正常
cudnn: 7.5.0
cuda: 10.0.130

**Comment by qingqing01** [comment]
cuDNN的版本也需要对应
