### ISSUE TITLE
如果想使用tensorRT来对模型进行评估，有没有参考文档，我找了好几天都没有找到

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#2989]
详细描述：能不能使用官方的eval.py，然后使用tensorRT来对模型进行评估，也就是最终得出在tensorRT加速的情况下的mAP值和FPS？？

**Comment by qingqing01** [comment]
@dengxinlong 暂且没有提供，一个方法需要自己基于 deploy/infer.py进行改造，或者讲输出结果保存文件。 再加载文件、组织评估mAP的代码，进行。

您这样做的目的是？
