### ISSUE TITLE
关于PaddleDetection中anchor匹配部分的疑惑

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/PaddleDetection#299]
![PSVXN77Z7FP`K7 K}`5(K~S](https://user-images.githubusercontent.com/26462054/75840941-7a6d8000-5e07-11ea-9be3-cfd65fb54d39.png)

请问一下，这里anchor和gt_boxes做匹配有点不太理解。不应该是anchor匹配每一张图的gt_boxes，这里gt_boxes的第一维是G（表示批量内真值框的总数）是怎么做匹配的？

**Comment by willthefrog** [comment]
`G`是指一个batch内所有图片的bbox数量的和，tensor的lod信息需要记录每张图片对应的offset及bbox数量，例如：n张图片一共有G个bbox，但是每个图片对应的bbox数量 (假设是n) 是不定的，那么tensor的data是所有的bbox（[G,4]），通过lod信息计算每张图片对应的起始及结束index，可以获得其对应的n个bbox。

**Comment by willthefrog** [comment]
可以参考 [lod tensor 文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/lod_tensor.html)

**Comment by zhengzhe97** [comment]
感谢你的回答
@willthefrog 是否有办法把这个tensor lod转换成普通的tensor， 我尝试了文档中的LodTensor_to_Tensor（），出现  'Variable' object has no attribute 'lod' 的错误

**Comment by willthefrog** [comment]
你如果是需要导出一个variable的数据，可以使用以下代码
```python
def to_numpy(var):
    assert isinstance(var, (Variable, fluid.core.VarBase)), "not a variable"
    if isinstance(var, fluid.core.VarBase):
        return var.numpy()
    t = global_scope().find_var(var.name).get_tensor()
    return np.array(t)
```

**Comment by zhengzhe97** [comment]
@willthefrog  我在参加论文复现的比赛，想使用PaddleDetection中MaskRCNN加载数据的部分，但是看到加载的数据（比如bbox（[G,4]））不太熟悉，是否能把他还原成（batchsize，gtnum， 4）这种形式？

**Comment by willthefrog** [comment]
你还原后时要做什么用？ 如果是需要导出的话用我刚才提供的代码就可以了，mask rcnn的op目前还是只支持lod方式的。

**Comment by zhengzhe97** [comment]
源代码中anchor匹配有点不一样的地方，本来想重写下，现在想了下直接用mask rcnn的op也没太大问题。
谢了 @willthefrog

**Comment by willthefrog** [comment]
如果问题解决麻烦 close下issue吧，谢谢。 @zhengzhe97
