### ISSUE TITLE
模型库里没有yolov4吗？

### ISSUE THREAD

**Issue by RhythmF** [PaddlePaddle/PaddleDetection#2995]
介绍里写支持的套件里有v4，但是模型库里没有啊

**Comment by pixeli99** [comment]
应该是在静态图版本里

**Comment by RhythmF** [comment]
> 应该是在静态图版本里

没有找到啊

**Comment by qingqing01** [comment]
静态图里有，动态里没有，https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/static/configs/yolov4
