### ISSUE TITLE
ppyolo_tiny 训练，learning rate 不变

### ISSUE THREAD

**Issue by EdwardVincentMa** [PaddlePaddle/PaddleDetection#2998]
learning late初始值是0.001，起初慢慢增长到0.001， 训练迭代到81个epoch， 显示还是 0.001，没变化。

训练图像 16666张，batchsize: 4。

step: 4000
gamma：0.1

**Comment by heavengate** [comment]
你好，你使用的是静态图还是动态图的配置呢，麻烦贴一下你的配置文件我们确认一下
