### ISSUE TITLE
导出行人检测模型预测视频中途报错

### ISSUE THREAD

**Issue by usuixingyili** [PaddlePaddle/PaddleDetection#2999]
CUDA 10.2,  CUDNN 7.6.5， PaddlePaddle 2.0.2
预测时长为30 min左右的视频在第3帧报错，导出该帧图片预测没有报错。另外预测一个时长为4 h的视频在2 w多帧也报错。
![屏幕截图 2021-05-14 111149](https://user-images.githubusercontent.com/74706568/118216539-4a5b4b80-b4a6-11eb-9e5d-6220d895a06c.png)
![屏幕截图 2021-05-14 111243](https://user-images.githubusercontent.com/74706568/118216542-4b8c7880-b4a6-11eb-8e23-2ebdf7d466e4.png)
![屏幕截图 2021-05-14 102132](https://user-images.githubusercontent.com/74706568/118216543-4c250f00-b4a6-11eb-93f7-ad6d99473749.png)

**Comment by heavengate** [comment]
你好，批量预测先少量CUDA 显存泄漏问题，我们在紧急定位中，2w帧图像看报错是显存泄漏了，可以减小预测帧数试下，我们也会在第一时间修复这个问题

**Comment by usuixingyili** [comment]
> 你好，批量预测先少量CUDA 显存泄漏问题，我们在紧急定位中，2w帧图像看报错是显存泄漏了，可以减小预测帧数试下，我们也会在第一时间修复这个问题

谢谢。我这边在静态图模型下可以预测完所有帧。

**Comment by yghstill** [comment]
@usuixingyili 行人车辆检测YOLOv3模型cuda error的问题已定位解决，请利用release/2.1分支最新代码重新导出模型再进行测试吧，感谢反馈。
