### ISSUE TITLE
关于类间不平衡

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#3004]
请问PaddleDetection中有提供处理数据集类间不平衡的工具或者接口么？

**Comment by heavengate** [comment]
静态图里有个class aware sampling解决类间不平衡问题，可以参考下
https://github.com/PaddlePaddle/PaddleDetection/blob/8968a22fb06a8a7a313ee9b4bdde7d8a58e33f0d/static/configs/cascade_rcnn_cls_aware_r101_vd_fpn_1x_softnms.yml#L75

**Comment by shfsidh** [comment]
> 静态图里有个class aware sampling解决类间不平衡问题，可以参考下
> https://github.com/PaddlePaddle/PaddleDetection/blob/8968a22fb06a8a7a313ee9b4bdde7d8a58e33f0d/static/configs/cascade_rcnn_cls_aware_r101_vd_fpn_1x_softnms.yml#L75

谢谢，我去看一下，顺便问一下这个模型16G的卡可以跑的吧，如果bs=1的话

**Comment by ghost** [comment]
> 静态图里有个class aware sampling解决类间不平衡问题，可以参考下
> https://github.com/PaddlePaddle/PaddleDetection/blob/8968a22fb06a8a7a313ee9b4bdde7d8a58e33f0d/static/configs/cascade_rcnn_cls_aware_r101_vd_fpn_1x_softnms.yml#L75

非常感谢，已经开始训练了

**Comment by heavengate** [comment]
鉴于问题已经解决，当前issue就先关闭了，如果还有问题可以reopen此issue~
