### ISSUE TITLE
AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'sync_batch_norm'

### ISSUE THREAD

**Issue by hablee** [PaddlePaddle/PaddleDetection#3005]
在[这里](https://aistudio.baidu.com/aistudio/projectdetail/1261400)学习使用paddleDetection的时候，使用`python -u tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml -o use_g
pu=False --eval` 报错：
`AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'sync_batch_norm'` 请问是什么原因呢

**Comment by qingqing01** [comment]
@hablee 最新2.0分支代码已经修复。您可以参考 https://github.com/PaddlePaddle/PaddleDetection/commit/6af489978e1d26f845a65cb6ee14b534cabb07d5 这里改下
