### ISSUE TITLE
生成模型预测时报错KeyError: 'image_shape'

### ISSUE THREAD

**Issue by xiao-f-y** [PaddlePaddle/PaddleDetection#3011]
![image](https://user-images.githubusercontent.com/79433100/118275667-515f7980-b4f9-11eb-8add-e41047007ad9.png)

**Comment by heavengate** [comment]
模型导出的时候`TestReader`里面配置了`image_shape`么

**Comment by heavengate** [comment]
@liuhuiCNN 关注一下是否是动态`image_shape`导出引入的问题
