### ISSUE TITLE
使用源码编译，运行python setup.py install 报错ImportError: cannot import name 'cpp_extension' from 'paddle.utils' 

### ISSUE THREAD

**Issue by gzf11** [PaddlePaddle/PaddleDetection#3013]
查看安装的paddle.utils内没有cpp_extension，将cpp_extension注释后可成功运行，这是我漏安了cpp_extension还是，在setup.py中多写了一句from paddle.utils import cpp_extension

**Comment by heavengate** [comment]
我们提供的`setup.py`里面应该是没有`from paddle.utils import cpp_extension`，另外如果是`paddle.utils`内没有`cpp_extension`应该是Paddle版本比较老，可以安装最新的Paddle版本试试
