### ISSUE TITLE
关于文件格式问题

### ISSUE THREAD

**Issue by pixeli99** [PaddlePaddle/PaddleDetection#3018]
![image](https://user-images.githubusercontent.com/46072190/118351441-a7cac780-b58e-11eb-8411-024c8b345828.png)
请问一下，这个图片里MOT16-02.txt里面内容应该是什么格式的呀，这是develop分支里的。

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/source/mot.py#L209 在标注文件中需要以此给出类别，id，中心点坐标，w，h这几个信息，需要注意的是，MOT数据集中中心点坐标和w,h这几个信息是归一化到[0,1]之间的
