### ISSUE TITLE
anchor based VS anchor free

### ISSUE THREAD

**Issue by zhangming8** [PaddlePaddle/PaddleDetection#3019]
Hi，感谢百度研究人员的贡献。
我有两个问题请教一下：
    1. 这里改进的PAFnet的mAP是42.2(512x512, resnet50-vd)。目前的anchor free的mAp已经到50了，当然这里面会有输入尺寸、backbone大小、fpn等的影响。所以我想问一下PAF的最好结果是多少有试过吗？
    2. 从FCOS、ATSS中的结果看anchor based和anchor free结果相差不大。但是从你们的实验结果看似乎anchor based更好(ppyolov2)？

**Comment by jerrywgz** [comment]
目前PAFNet的效果是基于ResNet50的backbone做优化的，还没有使用更大的backbone实验
从算法上而言，anchor free的方法跟单阶段的方式本质上是类似的，目前看ppyolov2是优化效果最好的模型，我们目前也还在继续探索anchor free的算法
