### ISSUE TITLE
模型转换

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleDetection#3023]
动态图导出的模型，如何转成以前静态图的__model__和__params__?

**Comment by jerrywgz** [comment]
现在动态图导出模型均使用paddle.jit.save的方式导出，格式和原先静态图方式不同，在预测部署阶段，两种格式的导出模型都是可以被正确加载的

**Comment by lleesg** [comment]
> 现在动态图导出模型均使用paddle.jit.save的方式导出，格式和原先静态图方式不同，在预测部署阶段，两种格式的导出模型都是可以被正确加载的

在2.1下用__model__和__params__会报错
使用量化模型ppyolo_tiny_quant.tar，在2.1下用deploy/python/infer.py预测报错：
(NotFound) Cannot open file ..\model.pdmodel, please confirm whether the file is normal.[Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.]

model_dir参数指定新格式目录：model.pdmodel、model.pdiparams就没问题

**Comment by lazyn1997** [comment]
> > 现在动态图导出模型均使用paddle.jit.save的方式导出，格式和原先静态图方式不同，在预测部署阶段，两种格式的导出模型都是可以被正确加载的
> 
> 在2.1下用__model__和__params__会报错
> 使用量化模型ppyolo_tiny_quant.tar，在2.1下用deploy/python/infer.py预测报错：
> (NotFound) Cannot open file ..\model.pdmodel, please confirm whether the file is normal.[Hint: Expected static_cast(fin.is_open()) == true, but received static_cast(fin.is_open()):0 != true:1.]
> 
> model_dir参数指定新格式目录：model.pdmodel、model.pdiparams就没问题

我测试infer也是无法使用静态图模型的，请问一下你的问题现在有解决吗？
