### ISSUE TITLE
新版本怎么使用数据增强啊？

### ISSUE THREAD

**Issue by luqihui** [PaddlePaddle/PaddleDetection#3024]
以前的版本yml配置文件里都有sample_transforms和batch_transforms的，更新之后怎么没了，要自己写吗？

**Comment by yghstill** [comment]
@luqihui 还有的，每个配置文件会指定reader的配置，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml#L6 

在reader的配置文件里还有sample_transforms和batch_transforms： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/ppyolo/_base_/ppyolo_reader.yml#L5

**Comment by luqihui** [comment]
@yghstill 好的我看到了，谢谢您

**Comment by luqihui** [comment]
@yghstill 你好，我想将每种数据增强后的效果展示出来，需要自定义数据增强方法吗？

**Comment by yghstill** [comment]
@luqihui 使用DebugVisibleImage 看能不能满足你的需求：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/ppdet/data/transform/operators.py#L1743
