### ISSUE TITLE
ppyolov2效果很差，我聚类了锚效果也不好

### ISSUE THREAD

**Issue by Flyooofly** [PaddlePaddle/PaddleDetection#3026]
我用ppyolov2-101那个训练了200个epoch,为啥效果很差呀。。我其实是要框人。。但框出来一堆别的东西而且准确率都在0.2作用
还有个问题，
训练时候的输出，Epoch[199][0/7]后面的[0/7]是啥意思啊。。是根据batchsize算的吗？总以为接下来会出现Epoch[0][1/7]。。。

**Comment by yghstill** [comment]
@Flyooofly 
- 看你描述，你的数据集应该很小吧？Epoch[199]表示当前训练epoch数，[0/7]表示当前epoch下的`训练轮数/总轮数`。效果差可能是由于你数据集太小，不易收敛，将数据增强方法去掉再试下吧。
- 默认log_iter是20，即每隔20轮打印一次log：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/runtime.yml#L2 ，如果想要每轮都打印log，则将log_iter设为1即可。

**Comment by Flyooofly** [comment]
> @Flyooofly
> 
> * 看你描述，你的数据集应该很小吧？Epoch[199]表示当前训练epoch数，[0/7]表示当前epoch下的`训练轮数/总轮数`。效果差可能是由于你数据集太小，不易收敛，将数据增强方法去掉再试下吧。
> * 默认log_iter是20，即每隔20轮打印一次log：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/runtime.yml#L2 ，如果想要每轮都打印log，则将log_iter设为1即可。

好的谢谢回答
