### ISSUE TITLE
训练到中途会出现 cuda error 退出

### ISSUE THREAD

**Issue by shyn** [PaddlePaddle/PaddleDetection#3027]
两次训练两次复现。

环境：
Windows 10
cuda 10.0
paddledetection release/2.0 分支
自己准备的训练集，分布使用 ppyolo_r50vd_dcn_1x_coco 和 ppyolov2_r50vd_dcn_365e_coco 的配置，配置仅针对单卡修改了batch_size 和 lr

每次训练 GPU 使用率都基本不超过 60%，中途无人值守，没做任何操作。
错误信息(for SEO)：

OSError: (External) Cuda error(77), an illegal memory access was encountered.
paddle\fluid\platform\gpu_info.cc:301

![屏幕截图ppyolo 2021-05-15 181713](https://user-images.githubusercontent.com/899449/118389434-8c2df280-b65c-11eb-8250-bc1cf24b67ca.png)
![屏幕截图 2021-05-16 152456](https://user-images.githubusercontent.com/899449/118389437-8fc17980-b65c-11eb-830b-462b00bd83c4.png)

**Comment by JustinHuang1984** [comment]
我用1080ti和rtx2070显卡也会出现这个问题，换2080ti和1060没问题

**Comment by yghstill** [comment]
@shyn 你的显卡型号和cuda版本是多少，此前没有测试出cuda error的问题，我们定位复现下

**Comment by shyn** [comment]
> @shyn 你的显卡型号和cuda版本是多少，此前没有测试出cuda error的问题，我们定位复现下

工作站配置 GTX 2080 8GB，不是 Super 不是 Ti
CUDA 版本 10.0

**Comment by yghstill** [comment]
> > @shyn 你的显卡型号和cuda版本是多少，此前没有测试出cuda error的问题，我们定位复现下
> 
> 工作站配置 GTX 2080 8GB，不是 Super 不是 Ti
> CUDA 版本 10.0

好的，我们验证下。
@JustinHuang1984 你在2080ti上训练没问题的cuda版本是多少呢

**Comment by JustinHuang1984** [comment]
> > > @shyn 你的显卡型号和cuda版本是多少，此前没有测试出cuda error的问题，我们定位复现下
> > 
> > 
> > 工作站配置 GTX 2080 8GB，不是 Super 不是 Ti
> > CUDA 版本 10.0
> 
> 好的，我们验证下。
> @JustinHuang1984 你在2080ti上训练没问题的cuda版本是多少呢
也是10.0的
