### ISSUE TITLE
关于动态图中 MultiScaleTest 以及 MultiClassSoftNMS 的使用

### ISSUE THREAD

**Issue by linyangsdu** [PaddlePaddle/PaddleDetection#3029]
1.  MultiClassSoftNMS 只在静态图中，请问动态图中有无替代
2. MultiScaleTest 在动态图版本中有无示例
3. 动态图版本模型是否可以直接在静态图中使用

**Comment by yghstill** [comment]
@linyangsdu 
1. 动态图下只有MultiClassNMS，MultiClassSoftNMS还未做迁移，可以先使用MultiClassNMS
2. MultiScaleTest也还没来得及迁移至动态图中
3. 动态图模型和静态图模型组网设计完全不一致，不可以直接融合

**Comment by linyangsdu** [comment]
#3023 我看到这个有说“在预测部署阶段，两种格式的导出模型都是可以被正确加载的”，那是否说明可以在静态图inference阶段直接 load 动态图的模型

**Comment by yghstill** [comment]
@linyangsdu 动转静后模型是能够被正确加载的，只是现在动态图模型与静态图模型输入不一样，动态图模型输入有image, im_ahep和scale_factor，但是静态图模型只有image, im_ahep两个输入，这个需要适配一下二者才可兼容
