### ISSUE TITLE
动态图ssd的loss问题

### ISSUE THREAD

**Issue by lao-xu** [PaddlePaddle/PaddleDetection#3031]
ssd_loss文件更新后虽然比之前速度提升一倍，经测试仍然明显慢于静态图约25%，感觉还是有问题
此外2.0版本的静态图准确率似乎低于之前的静态图版本，但这没有测试，只是个大致感觉

**Comment by yghstill** [comment]
@lao-xu ssd_mobilenet_v1_300_120e_voc这个模型静态图训练稍快，ssdlite模型动态图优化后训练速度比静态图快，目前关于速度问题还在优化中，精度的话之前是对齐的，应该不会低于静态图版本。
