### ISSUE TITLE
tools/infer.py 中怎么修改代码，显示每张图片的预测时间，

### ISSUE THREAD

**Issue by Williamlizl** [PaddlePaddle/PaddleDetection#3041]

**Comment by liuhuiCNN** [comment]
（1） 调用的是这个函数，您在这个函数中增加计时代码即可。 https://github.com/PaddlePaddle/PaddleDetection/blob/f0a30f3ba6095ebfdc8fffb6d02766406afc438a/ppdet/engine/trainer.py#L356
（2）deploy/infer.py中带有预测时间benchmark的代码，请参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/deploy/python/README.md
