### ISSUE TITLE
PPdet release 2.0版本不支持多GPU吗？

### ISSUE THREAD

**Issue by KKIverson** [PaddlePaddle/PaddleDetection#3045]
RT.
gitee上下载下来的pppdet 2.0 版本，tools里面只有train.py没有multi版本，而且我参照教程https://aistudio.baidu.com/aistudio/projectdetail/1922155

训练ppyolov2，多卡指令CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python tools/train.py -c configs/ppyolo/ppyolo.yml --eval也没有用。。。

**Comment by liuhuiCNN** [comment]
你好，pppdet 2.0 版本多卡启动命令： `python3.7 -m paddle.distributed.launch --gpus 0,1,2,3 tools/train.py -c xxx.yml`

**Comment by KKIverson** [comment]
![image](https://user-images.githubusercontent.com/49222488/118502411-42c4cc80-b75c-11eb-870d-32c52fb10deb.png)
多谢，按照你说的方法跑起来了ppyolo（不是ppyolov2），但是gpu0多出来的几个进程，是跟其他卡进行通信的么。貌似还挺占显存的。因为我开4张卡是可以跑的，开8张卡就不行了。

还有，ppyolov2 r50在2080Ti上的建议batch size 和learning rate是多少呢？

**Comment by liuhuiCNN** [comment]
（1）是正常现象；（2）默认学习率是8卡的，如果您用1卡的，学习率除以8。batch size根据您的显存、内存合理设置，在硬件可承受范围内越大越好，batch size变化时，学习率同比例变化。

**Comment by KKIverson** [comment]
![image](https://user-images.githubusercontent.com/49222488/118574968-19398e80-b7b8-11eb-993c-05cbf46f3c45.png)

好的。不过程序一直卡在这里是咋回事啊？GPU还在用，但是很不正常
![image](https://user-images.githubusercontent.com/49222488/118575066-2fdfe580-b7b8-11eb-8cad-df4035d4865c.png)

**Comment by wangxinxin08** [comment]
@KKIverson 这个应该是第一个epoch之后进行eval的缘故，因为数据较少，模型尚未训练好，导致后处理过程非常慢，可以考虑将将训练时eval去掉
