### ISSUE TITLE
请问怎么修改单图数据增强的输入example数量呢，例如mixup输入是两张图

### ISSUE THREAD

**Issue by di-dii** [PaddlePaddle/PaddleDetection#3048]

**Comment by wangxinxin08** [comment]
可以参考这一部分的逻辑进行修改https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/ppdet/data/source/dataset.py#L66

**Comment by di-dii** [comment]
@wangxinxin08  知道了，感谢
