### ISSUE TITLE
PaddleDetection对自己训练的yolov3_mobilenet_v1模型进行剪枝报错

### ISSUE THREAD

**Issue by kim3352** [PaddlePaddle/PaddleDetection#305]
目前，我根据文档使用这段代码查看模型参数：
python3 slim_prune_prune.py \
-c ./configs/yolov3_mobilenet_v1_pig.yml \
--print_params
输出：
．．．
parameter name: yolo_block.0.0.0.conv.weights   shape: (512, 1024, 1, 1)
parameter name: yolo_block.0.0.0.bn.scale       shape: (512,)
parameter name: yolo_block.0.0.0.bn.offset      shape: (512,)
parameter name: yolo_block.0.0.0.bn.mean        shape: (512,)
．．．
执行这段代码进行裁剪：
python3 slim_prune_prune.py \
-c ./configs/yolov3_mobilenet_v1_pig.yml \
--pruned_params "yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights" \
--pruned_ratios="0.2,0.3,0.4"
裁剪完，执行下面这段代码进行验证：
python3 slim_prune_eval.py \
-c ./configs/yolov3_mobilenet_v1_pig.yml \
--pruned_params "yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights" \
--pruned_ratios="0.2,0.3,0.4" \
-o weights=output/yolov3_mobilenet_v1_pig/best_model
报如下错误：
AssertionError: Shape not matching: the Program requires a parameter with a shape of ((512,)), while the loaded parameter (namely [ yolo_block.0.0.0.bn.mean ]) has a shape of  ((410,)).

**Comment by heavengate** [comment]
paddleslim用的哪个版本，建议使用v1.0.0版本，新版本上prune实现有调整

**Comment by kim3352** [comment]
> paddleslim用的哪个版本，建议使用v1.0.0版本，新版本上prune实现有调整

用的是最新的版本

**Comment by lguowang** [comment]
现在历史版本只有1.0.1了，没有v1.0.0版本，希望：
1、能修改以下prune eval 的实现
2、配套一个导出模型的DEMO

**Comment by mitsuix** [comment]
> 
> 
> paddleslim用的哪个版本，建议使用v1.0.0版本，新版本上prune实现有调整

您好，我降到v1.0.0 重新prune之后eval还是报错呢~

**Comment by qingqing01** [comment]
@kim3352 由于时间较久，先关闭了此issue。有问题可以再开新的issue。
