### ISSUE TITLE
运行静态图遇到的问题

### ISSUE THREAD

**Issue by linyangsdu** [PaddlePaddle/PaddleDetection#3051]
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1621305939 (unix time) try "date -d @1621305939" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x2a300c) received by PID 974 (TID 0x7f07053f0700) from PID 2764812 ***]

我在运行静态图
python tools/train.py -c my_configs/cascade_rcnn_dcn_r50_fpn_1x.yml
中遇到了这样的问题，请问可能是关于什么的问题

这是 cascade_rcnn_dcn_r50_fpn_1x.yml的内容:

architecture: CascadeRCNN
max_iters: 20484
snapshot_iter: 1707
use_gpu: true
log_iter: 20
save_dir: output
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/cascade_rcnn_dcn_r50_fpn_1x.tar
weights: output/cascade_rcnn_dcn_r50_fpn_1x/model_final
metric: COCO
num_classes: 4

CascadeRCNN:
  backbone: ResNet
  fpn: FPN
  rpn_head: FPNRPNHead
  roi_extractor: FPNRoIAlign
  bbox_head: CascadeBBoxHead
  bbox_assigner: CascadeBBoxAssigner

ResNet:
  norm_type: bn
  depth: 50
  feature_maps: [2, 3, 4, 5]
  freeze_at: 2
  variant: b
  dcn_v2_stages: [3, 4, 5]

FPN:
  min_level: 2
  max_level: 6
  num_chan: 256
  spatial_scale: [0.03125, 0.0625, 0.125, 0.25]

FPNRPNHead:
  anchor_generator:
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 32
  min_level: 2
  max_level: 6
  num_chan: 256
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_positive_overlap: 0.7
    rpn_negative_overlap: 0.3
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 2000
    post_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 1000
    post_nms_top_n: 1000

FPNRoIAlign:
  canconical_level: 4
  canonical_size: 224
  min_level: 2
  max_level: 5
  box_resolution: 7
  sampling_ratio: 2

CascadeBBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [10, 20, 30]
  bg_thresh_lo: [0.0, 0.0, 0.0]
  bg_thresh_hi: [0.5, 0.6, 0.7]
  fg_thresh: [0.5, 0.6, 0.7]
  fg_fraction: 0.25

CascadeBBoxHead:
  head: CascadeTwoFCHead
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    score_threshold: 0.001

CascadeTwoFCHead:
  mlp_dim: 1024

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [13656, 18208]
  - !LinearWarmup
    start_factor: 0.1
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

_READER_: 'faster_fpn_reader.yml'
TrainReader:
  batch_size: 8
  worker_num: 16

**Comment by linyangsdu** [comment]
大部分情况下是多卡遇到的问题，命令如下:
python -m paddle.distributed.launch --selected_gpus 0,1,2,3 tools/train.py -c my_configs/cascade_rcnn_dcn_r50_fpn_1x.yml

这条命令也试了:
python -m paddle.distributed.launch --gpus 0,1,2,3 tools/train.py -c my_configs/cascade_rcnn_dcn_r50_fpn_1x.yml

**Comment by wangxinxin08** [comment]
可以考虑调小worker_num

**Comment by linyangsdu** [comment]
worker_num设为1解决
