### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/lbc/.local/lib/python3.6/site-packages/paddle/fluid/core_avx.so)

### ISSUE THREAD

**Issue by Williamlizl** [PaddlePaddle/PaddleDetection#3059]
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/lbc/.local/lib/python3.6/site-packages/paddle/fluid/core_avx.so)

**Comment by CC012118** [comment]
I follow this blog(https://blog.csdn.net/u011961856/article/details/79644342) and reinstall libstdc++6. problem solved! Hope it can help you.
