### ISSUE TITLE
VehicleDetection车辆检测官方预训练模型invalid.....没什么效果

### ISSUE THREAD

**Issue by lienxie** [PaddlePaddle/PaddleDetection#306]
车辆检测，按教程运行，结果为什么这样呢？用cpu运行的
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/docs/featured_model/CONTRIB_cn.md

用的是release 0.1版本

在yml设置 use_gpu:false 

python -u tools/infer.py -c contrib/VehicleDetection/vehicle_yolov3_darknet.yml \
                         -o weights=contrib/VehicleDetection/vehicle_yolov3_darknet.tar \
                         --infer_dir contrib/VehicleDetection/demo \
                         --draw_threshold 0.2 \
                         --output_dir contrib/VehicleDetection/demo/output

<img width="567" alt="image" src="https://user-images.githubusercontent.com/32634857/76042798-b6801c80-5f90-11ea-9697-2117bd17e3da.png">

测试结果如下

![001](https://user-images.githubusercontent.com/32634857/76042930-0bbc2e00-5f91-11ea-999f-5f097062feda.jpeg)

**Comment by heavengate** [comment]
`-o weights=contrib/VehicleDetection/vehicle_yolov3_darknet.tar `
不能直接加载tar文件，支持加载方式有如下两种：
- `-o weights=https://paddlemodels.bj.bcebos.com/object_detection/vehicle_yolov3_darknet.tar`
- 或下载tar文件并解压，`-o weights=/path/to/vehicle_yolov3_darknet`

**Comment by heavengate** [comment]
![001](https://user-images.githubusercontent.com/12605721/76063079-f3183c00-5fc1-11ea-9913-6e084f124110.jpeg)
用release/0.1将上述命令`weights`指定改成`-o weights=https://paddlemodels.bj.bcebos.com/object_detection/vehicle_yolov3_darknet.tar` 测试了下没有问题，另外release/0.2已经发布，建议使用release/0.2版本
