### ISSUE TITLE
静态图怎么打印出tensor的值，怎么create一个tensor

### ISSUE THREAD

**Issue by lao-xu** [PaddlePaddle/PaddleDetection#3062]
请问静态图怎么打印出tensor的值，怎么创造一个tensor?动态图用惯了，很不适应静态图

**Comment by wangxinxin08** [comment]
PaddlePaddle 2.0已经支持动态图，你可以使用PaddleDetection release/2.0版本，默认使用动态图

**Comment by wangxinxin08** [comment]
如果你仍有相关需要，可以考虑使用fluid.layers.Print(tensor)打印出tensor的名字，然后将其加入到fetch_list里面，参考https://github.com/wangxinxin08/PaddleDetection/blob/ppyolo_debug/tools/train.py#L288，创建一个tensor的话可以从numpy创建， 参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/static/ppdet/modeling/anchor_heads/yolo_head.py#L102

**Comment by lao-xu** [comment]
好的，谢谢
