### ISSUE TITLE
s2anet docker出错

### ISSUE THREAD

**Issue by gengyanlei** [PaddlePaddle/PaddleDetection#3065]
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.1 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 brand=tesla,driver>=418,driver<419 --pid=156489 /home/docker/overlay2/5d7aa3228bcb2dbdf4d32cba92ec64ffe0498539cc5b43c6e7457e0f6076ccb6/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: driver >= 418\\\\n\\\"\"": unknown.

```
搞不定，请教一下，我运行docker.hub上面的nvidia的都没问题；是显卡的型号问题么？

**Comment by qingqing01** [comment]
@gengyanlei 上面看起来是docker环境问题。您跑其他模型，比如快速开始的路标检测能跑起来吗？ 或者PaddlePaddle安装后能显示成功吗？

**Comment by gengyanlei** [comment]
哦，知道了，是显卡版本的问题，我的是Driver Version: 384.130；

**Comment by gengyanlei** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/docs/tutorials/INSTALL_cn.md
直接按照官方的安装好PaddleDetection后，能直接用s2anet么

**Comment by qingqing01** [comment]
@gengyanlei 理论上可以的。  也按照这个 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/dota/README.md 教程安装下自定义算子吧。

**Comment by gengyanlei** [comment]
@qingqing01 
请问你们实现的s2anet基于的DOTAv1.5？还是DOTAv1.0呢，能在readme中声名么，tks

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/118788324-42484500-b8c6-11eb-976f-e17b32afff6d.png)

paddleDetection的s2anet的测试效果，还报错，哎，感觉paddle体验不太好。

**Comment by gengyanlei** [comment]
哦，nms阈值啥的都在这里
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/dota/_base_/s2anet.yml
共15类，应该是DOTAv1.0

**Comment by qingqing01** [comment]
@gengyanlei 您上面报错指的是什么？是说label错了？ 您用的是DOTA数据吗？
