### ISSUE TITLE
使用deploy/python/infer.py，PAFNet模型推理时，报错，

### ISSUE THREAD

**Issue by Williamlizl** [PaddlePaddle/PaddleDetection#3068]
```
ValueError: (InvalidArgument) The input [deformable_conv_16.tmp_0] shape of trt subgraph is [-1,128,-1,-1], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at /paddle/paddle/fluid/inference/tensorrt/engine.h:103)

```

模型导出代码为：
```
python3.6 tools/export_model.py -c configs/ttfnet/pafnet_10x_coco.yml --output_dir=./output  -o weights=./output/pafnet_10x_coco.pdparams
```

**Comment by qingqing01** [comment]
您推理时打开了TensorRT是吗？ 试下打开 use_dynamic_shape参数呢？

https://github.com/PaddlePaddle/PaddleDetection/blob/3903e78c728b2afa40f813bad272a6a941db9a0d/deploy/python/infer.py#L529

**Comment by Williamlizl** [comment]
> 您推理时打开了TensorRT是吗？ 试下打开 use_dynamic_shape参数呢？
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/3903e78c728b2afa40f813bad272a6a941db9a0d/deploy/python/infer.py#L529

打开了trt_fp16, --use_dynamic_shape = True，还是报错

`use_dynamic_shape
trt set dynamic shape done!
Traceback (most recent call last):
  File "deploy/python/infer.py", line 552, in <module>
    main()
  File "deploy/python/infer.py", line 468, in main
    trt_opt_shape=FLAGS.trt_opt_shape)
  File "deploy/python/infer.py", line 76, in __init__
    trt_opt_shape=trt_opt_shape)
  File "deploy/python/infer.py", line 379, in load_predictor
    predictor = create_predictor(config)
ValueError: (InvalidArgument) some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:221)`

**Comment by liuhuiCNN** [comment]
（1）使用动态尺寸输入时，需要设置：--use_dynamic_shape=True --trt_max_shape=1280 --trt_min_shape=800 --trt_opt_shape=960
可以参考文档：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/deploy/TENSOR_RT.md
（2）如果设置之后还出错，请参考 TRT  FAQ文档：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/deploy/TENSOR_RT.md#4%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98qa ，增大配置文件中的min_subgraph_size试下。

**Comment by Williamlizl** [comment]
> （1）使用动态尺寸输入时，需要设置：--use_dynamic_shape=True --trt_max_shape=1280 --trt_min_shape=800 --trt_opt_shape=960
> 可以参考文档：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/deploy/TENSOR_RT.md
> （2）如果设置之后还出错，请参考 TRT FAQ文档：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/deploy/TENSOR_RT.md#4%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98qa ，增大配置文件中的min_subgraph_size试下。

https://github.com/PaddlePaddle/PaddleDetection/blob/3903e78c728b2afa40f813bad272a6a941db9a0d/deploy/python/infer.py#L315
这行改为10,20，还是报同样问题；导出模型命令没错误吧

**Comment by qingqing01** [comment]
@jerrywgz @liuhuiCNN 验证下这个模型的动转静推理吧

**Comment by jerrywgz** [comment]
目前验证python inference, 不使用tensorrt的情况下，pafnet_10x_coco的预测部署是正常的

**Comment by Williamlizl** [comment]
> 目前验证python inference, 不使用tensorrt的情况下，pafnet_10x_coco的预测部署是正常的

开了trt_fp16后就报错了，不开正常

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/3088 已修复
