### ISSUE TITLE
faster/cascade rcnn的每卡batch只能为1？

### ISSUE THREAD

**Issue by math-yyj** [PaddlePaddle/PaddleDetection#3072]
我在训练这个数据集的时候
https://aistudio.baidu.com/aistudio/datasetdetail/79834

使用ppdet2.0下，config/rcnn_enhance的原始配置进行训练

发现loss_bbox_reg完全为0，一点变化都没有，但是把配置里的batch从2改成1，lossboxreg就正常变化，不是0

这是什么原因

**Comment by qingqing01** [comment]
@mathyyj 默认的配置是 按照8卡的配置，每个卡的batch size是2。总共的batch size是16。

https://github.com/PaddlePaddle/PaddleDetection/blob/3903e78c728b2afa40f813bad272a6a941db9a0d/configs/rcnn_enhance/_base_/faster_rcnn_enhance_reader.yml#L12

如果卡数、batch size变化，比如总共的batch size减少到2，那学习率需要除以8。
