### ISSUE TITLE
s2anet bug

### ISSUE THREAD

**Issue by gengyanlei** [PaddlePaddle/PaddleDetection#3076]
按照教程搭建好镜像-容器，执行如下命令，下载paddle提供的s2anet模型为s2anet_conv_1x_dota.pdparams，并非是s2anet_1x_dota.pdparams，报错且标签错误

CUDA_VISIBLE_DEVICES=3 python3.7 tools/infer.py -c configs/dota/s2anet_conv_1x_dota.yml -o weights=/mnt/data/gengyanlei/Packages/s2anet_conv_1x_dota.pdparams --infer_dir=/mnt/data/gengyanlei/OBB_dataset/DOTA/val1/images --draw_threshold=0.45 --save_txt=True --output_dir=/mnt/data/gengyanlei/OBB_dataset/DOTA/val1/output_s2anet/result_txt/result_before_merge

![image](https://user-images.githubusercontent.com/22360785/118904303-29827280-b94c-11eb-9cca-5cfaf3f25648.png)
![image](https://user-images.githubusercontent.com/22360785/118904378-5afb3e00-b94c-11eb-9e7b-b012acf38f50.png)

**Comment by qingqing01** [comment]
@gengyanlei 关于标签的问题，您是DOTA官方数据吗？标签是从TestReader的anno_path里读取的。 需要注意正确设置

https://github.com/PaddlePaddle/PaddleDetection/blob/3903e78c728b2afa40f813bad272a6a941db9a0d/configs/datasets/dota.yml#L19

**Comment by gengyanlei** [comment]
好吧，你们居然不把这些参数单独传参，我只是想单纯的测试一下你们的模型，没想到还要处理dota数据，尴尬。

**Comment by qingqing01** [comment]
@gengyanlei 这个模型是用DOTA训练得到的，标签默认都是DOTA数据中的。

**Comment by gengyanlei** [comment]
嗯嗯，我把DOTA全下载下来了，然后跑个json文件，现在终于可以全解决了。
tks，本来想改你们的代码的，但有点不清楚具体怎么设计的，还是直接默认吧https://github.com/PaddlePaddle/PaddleDetection/blob/3903e78c728b2afa40f813bad272a6a941db9a0d/ppdet/engine/trainer.py#L367

**Comment by gengyanlei** [comment]
@qingqing01 
你们采用的是DOTAv1.0，期待v1.5版本的，因为v1.5增补了小目标；这个很重要；

**Comment by qingqing01** [comment]
@gengyanlei 您上述贴的代码确实是类别标签解析的。 感谢建议，我们会尽快补充的。
