### ISSUE TITLE
PaddleDetection 做水果检测检测结果不正确

### ISSUE THREAD

**Issue by 15711038932** [PaddlePaddle/PaddleDetection#308]
我实验步骤:
1)   训练模型
    python -u tools/train.py -c configs/yolov3_mobilenet_v1_fruit.yml --use_tb=True --tb_log_dir=tb_fruit_dir/scalar --eval

2)   训练完成后,我用下面命令 导出模型
      python tools/export_model.py -c configs/yolov3_mobilenet_v1_fruit.yml --output_dir=./inference_model -o weights=output/yolov3_mobilenet_v1_fruit/best_model
      导出成功了

3)      然后我又用下面的命令测试.结果不正确
         python -u tools/infer.py -c configs/yolov3_mobilenet_v1_fruit.yml -o weights=inference_model/yolov3_mobilenet_v1_fruit --infer_img=demo/orange_71.jpg --output_dir=infer_output

    出错信息如下:

   python -u tools/infer.py -c configs/yolov3_mobilenet_v1_fruit.yml -o weights=inference_model/yolov3_mobilenet_v1_fruit --infer_img=demo/orange_71.jpg --output_dir=infer_output

2020-03-05 08:17:38,665-INFO: Loading parameters from inference_model/yolov3_mobilenet_v1_fruit...
/home/coall/anaconda3/envs/wConda/lib/python3.7/site-packages/paddle/fluid/executor.py:804: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
2020-03-05 08:17:38,674-INFO: Not found annotation file None, load voc2012 categories.
2020-03-05 08:17:39,641-INFO: Infer iter 0
2020-03-05 08:17:39,964-INFO: Detection bbox results save in infer_output/orange_71.jpg

    4)  我查看输出文件,输出文件没有检测出桔子

**Comment by heavengate** [comment]
`tools/export_model.py`导出的是用于部署的模型，如果要用这个模型测试infer效果的话需要用`tools/cpp_infer.py`，如果使用`tools/infer.py`测试效果的话需要使用训练保存的权重，即
```
python -u tools/infer.py -c configs/yolov3_mobilenet_v1_fruit.yml -o weights=inference_model/yolov3_mobilenet_v1_fruit --infer_img=demo/orange_71.jpg --output_dir=output/yolov3_mobilenet_v1_fruit/best_model
```
