### ISSUE TITLE
ppyoloTensorrt deployment on Jetson nano 

### ISSUE THREAD

**Issue by LIU-FAYANG** [PaddlePaddle/PaddleDetection#3086]
Environment:
Jetpack 4.5 Cuda10.2 TensorRT 7.2.3

1.你好，在Jetson Nano上跑ppyolo tensorrt的时候卡在这里了，code在pc端跑速度和精度都是正常的，请问有什么解决办法吗？

2.请问

WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
/usr/local/lib/python3.6/dist-packages/paddle/utils/cpp_extension/extension_utils.py:461: UserWarning: Not found CUDA runtime, please use `export CUDA_HOME= XXX` to specific it.
  "Not found CUDA runtime, please use `export CUDA_HOME= XXX` to specific it."

这个是什么意思，不去管有影响吗？

3. 尝试跑ppyolo infernece的demo跑的非常慢而且几乎在nano上是卡死的，已经加了8个G的swapfile，请问正常不这种情况。

paul@paul-desktop:~/Desktop/PaddleDetection$ CUDA_VISIBLE_DEVICE=0 python3.6 deploy/python/infer.py --model_dir=output_inference/ppyolo_r50vd_dcn_1x_coco/ --infer_dir=/home/paul/Desktop/val2017_img/ --use_gpu=True --run_mode=trt_fp16 --threshold=0.001
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
/usr/local/lib/python3.6/dist-packages/paddle/utils/cpp_extension/extension_utils.py:461: UserWarning: Not found CUDA runtime, please use `export CUDA_HOME= XXX` to specific it.
  "Not found CUDA runtime, please use `export CUDA_HOME= XXX` to specific it."
-----------  Running Arguments -----------
camera_id: -1
image_file: 
infer_dir: /home/paul/Desktop/val2017_img/
model_dir: output_inference/ppyolo_r50vd_dcn_1x_coco/
output_dir: output
run_benchmark: False
run_mode: trt_fp16
threshold: 0.001
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dynamic_shape: False
use_gpu: True
video_file: 
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------

**Comment by heavengate** [comment]
你好，我们刚发布了PaddleDetection v2.1.0版本，优化了部署的代码，并且提供了Jetson上的部署指南，你可以参考一下这个部署文档 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/cpp/docs/Jetson_build.md
