### ISSUE TITLE
静态图的multiscale test

### ISSUE THREAD

**Issue by luuuyi** [PaddlePaddle/PaddleDetection#3087]
请问一下，在静态图下想用multiscale test的话应该怎么用，有例子么

**Comment by heavengate** [comment]
你好，静态图使用multiscale test只需要在配置文件中加上`MultiScaleTEST`配置段就可以了，可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/5e19955b011d47377a3f1443a6e592ddd9e5024a/static/configs/cascade_rcnn_r50_fpn_1x_ms_test.yml#L86

**Comment by luuuyi** [comment]
@heavengate 了解
