### ISSUE TITLE
怎样提高训练速度，提升cuda使用率

### ISSUE THREAD

**Issue by JustinHuang1984** [PaddlePaddle/PaddleDetection#3089]
PaddleDetection训练ppyolo_mobilenet_v3_large和ppyolov2_r50vd_dcn模型，ppyolov2_r50vd_dcn反倒训练速度快，ppyolo_mobilenet_v3_large反倒慢，看了下cuda利用率如图，想问下大神要怎么设定参数才能把cuda利用率提高，也就是把训练速度提高来
![ppyolo_mobilenet_v3_large](https://user-images.githubusercontent.com/59753769/118959908-5313bc00-b995-11eb-9656-99d6db27803e.png)
![ppyolov2_r50vd_dcn](https://user-images.githubusercontent.com/59753769/118959919-55761600-b995-11eb-87dc-d8c72bd74da0.png)

**Comment by heavengate** [comment]
你好，由于`ppyolo_mobilenet_v3_large`模型比较小，而YOLO系列模型的预处理数据增强比较复杂，所以一般是CPU是性能瓶颈，才出现了你上面的表现，如果你的CPU使用率还有余量，可以通过增大`num_workers`的方法来提升训练速度

**Comment by JustinHuang1984** [comment]
我的CPU是有富足的，但是感觉把workers_num改大一点效果也没有啊

**Comment by JustinHuang1984** [comment]
我发现把batch_size调到1，显存使用量会下降，但是cuda使用率就提高了，速度就起来了
