### ISSUE TITLE
使用ppyolov2和ppyolotiny训练模型，推理时图片中没有框

### ISSUE THREAD

**Issue by luqihui** [PaddlePaddle/PaddleDetection#3091]
使用ppyolov2和ppyolo tiny都训练了模型，推理时图片中都没有框，跟原图一样，可能是什么原因？

**Comment by heavengate** [comment]
你好，这个原因比较多，可以排查下：
1. 是不是训练轮数不够，模型还没有收敛，如果是训练自己的数据集，可以试下加载我们发布好的coco数据集上的预训练权重来finetune来加速收敛
2. 可以排查一下预测的时候加载权重是否正确
3. 可以把`--draw_threshold`设置小一点试下

**Comment by zhude233** [comment]
同样的模型，在不同的机子上，有的有框，有的没有，请问是什么原因？

**Comment by liuhuiCNN** [comment]
> 在不同的机子上

不同机器上环境是否一致？

**Comment by hhxdestiny** [comment]
> 你好，这个原因比较多，可以排查下：
> 
> 1. 是不是训练轮数不够，模型还没有收敛，如果是训练自己的数据集，可以试下加载我们发布好的coco数据集上的预训练权重来finetune来加速收敛
> 2. 可以排查一下预测的时候加载权重是否正确
> 3. 可以把`--draw_threshold`设置小一点试下

你好，我复现了同样的问题。我的流程是：使用x2coco.py把roadsign_voc转成了roadsign_coco，修改配置后开始训练（aistudio训练的，学习率降了1/8，未使用预训练模型，训练了365轮），loss后面降到25左右下不去了，loss_obj在13左右。

可以通过我aistudio的项目[【ppyolo_v2_test】](https://aistudio.baidu.com/aistudio/projectdetail/2031218?shared=1)复现此问题。

**Comment by chenxuezhao** [comment]
@heavengate 你好，我在训练ppyolo_tiny的时候也遇到了同样的问题，请问这个问题最后解决了吗？怎么解决的？[https://github.com/PaddlePaddle/PaddleDetection/issues/3588](url)

**Comment by hhxdestiny** [comment]
@chenxuezhao 
推理的时候带上这个参数，如果数据集比较发散或者训练轮数不够，就不能用默认值了，改小点试试
```
parser.add_argument(
        "--draw_threshold",
        type=float,
        default=0.5,
        help="Threshold to reserve the result for visualization.")
```

**Comment by chenxuezhao** [comment]
@hhxdestiny 改小了，识别的结果是这样的：
![test1](https://user-images.githubusercontent.com/42796059/124711817-1bef6f00-df31-11eb-8c5d-8def03cc6351.jpg)
不知道这个算不算正常？总感觉不太对
