### ISSUE TITLE
不同版本的预训练模型

### ISSUE THREAD

**Issue by quhaohao** [PaddlePaddle/PaddleDetection#3098]
您好，注意到2.1版本和2.0-rc版本里关于 solov2的预训练模型数量不一样https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/solov2/README.md
以及 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/configs/solov2/README.md
它们之间可以相互转化吗？
另外 ，我是2.0-rc版本里的solov2在cpu上推理时，为何只使用了一个线程，怎样改线程呢？

最后，PaddleDetection YYDS

**Comment by jerrywgz** [comment]
2.0-rc中的版本为静态图solov2，2.1版本中为动态图版本，两份权重不能直接转化，但是精度是等价的，也推荐使用2.1动态图版本～
在2.1版本中，可以设置--cpu_threads来改cpu推理线程

**Comment by quhaohao** [comment]
> 2.0-rc中的版本为静态图solov2，2.1版本中为动态图版本，两份权重不能直接转化，但是精度是等价的，也推荐使用2.1动态图版本～
> 在2.1版本中，可以设置--cpu_threads来改cpu推理线程

嗯嗯，我尝试了2.1版本，里边使用多线程可以进行加速。然而，2.0-rc版本中有公开了101的solov2模型，2.1版本还没公开。
请问101会在接下来更新吗

**Comment by jerrywgz** [comment]
嗯会的，我们后续会更新下solov2的动态图model zoo

**Comment by yghstill** [comment]
@quhaohao develop分支下solov2 r101模型已更新
