### ISSUE TITLE
数据输入上的提问

### ISSUE THREAD

**Issue by AN-ZE** [PaddlePaddle/PaddleDetection#3099]
使用cascade rcnn训练，我只能想修改输入数据的通道维度，在进入网络前进行修改。
例如 将图像预处理之后，将数据修改为1维数据或者四维数据，只修改NormalizeImage就可以把。bbox的信息是不会变化的，只是增加或减少一维图像数据。
感谢！

**Comment by jerrywgz** [comment]
在输入方面，还需要修改Permute，目前我们会在Permute中将图片做这种操作```im = im.transpose((2, 0, 1))```
另外backbone第一个卷积需要设置in_channels为实际输入图像的channel数

**Comment by AN-ZE** [comment]
![图片](https://user-images.githubusercontent.com/29450812/119091419-a0e4fe80-ba3f-11eb-8005-51db0c28307c.png)

是这里是吧，数据到这里应该是 [batch size, 3通道，h, w], 我修改成我需要的1通道，或者4通道就可以吧。

数据方面，我只是人工删除或添加了数据通道，数据 还是 (h,w,c) 只是c变了，Permute应该不用修改。

**Comment by AN-ZE** [comment]
另外，首页README中 推理部署，lite部署和server部署，超链接地址写反了

**Comment by jerrywgz** [comment]
> ![图片](https://user-images.githubusercontent.com/29450812/119091419-a0e4fe80-ba3f-11eb-8005-51db0c28307c.png)
> 
> 是这里是吧，数据到这里应该是 [batch size, 3通道，h, w], 我修改成我需要的1通道，或者4通道就可以吧。
> 
> 数据方面，我只是人工删除或添加了数据通道，数据 还是 (h,w,c) 只是c变了，Permute应该不用修改。

截图中的修改位置是对的，关于permute，这个op我们现在是统一放在normalize后面了，所以如果normalize的输出结果变了，permute也需要做相应调整的

**Comment by jerrywgz** [comment]
> 另外，首页README中 推理部署，lite部署和server部署，超链接地址写反了

感谢反馈，已经修复了

**Comment by AN-ZE** [comment]
感谢！
