### ISSUE TITLE
无法导入下载的预训练权重

### ISSUE THREAD

**Issue by XuanheLiu** [PaddlePaddle/PaddleDetection#310]
![image](https://user-images.githubusercontent.com/33046467/76078428-9cb8f680-5fdd-11ea-8a80-364cfca164a3.png)

**Comment by littletomatodonkey** [comment]
你好，我刚才也遇到这个问题了，我把Paddle版本切换到1.7就没问题了。
之前PaddleDetection使用的是load vars接口，可以导入每个参数的权重，
`fluid.io.load_vars(exe, path, prog, predicate=_if_exist)`
后来统一接口，全部调整为
`fluid.load(prog, path, executor=exe)`了。
可以参考release/0.1与release/0.2的load_params的不同写法。https://github.com/PaddlePaddle/PaddleDetection/blob/3aa5cbf7ddc80d3f5d7ff751a47bce64c81854b0/ppdet/utils/checkpoint.py#L95

**Comment by XuanheLiu** [comment]
@littletomatodonkey 好的 谢谢 我切换一下版本试试

**Comment by heavengate** [comment]
需要使用Paddle1.7版本，pypi上已经发布
