### ISSUE TITLE
ppyolov2训练异常

### ISSUE THREAD

**Issue by Cristhine** [PaddlePaddle/PaddleDetection#3106]
背景：使用ppyolov2 voc数据格式进行训练 训练到199epoch hang住 无进展(四卡训练) log无错误信息 只是卡住
![image](https://user-images.githubusercontent.com/26667855/119094472-a6dcde80-ba43-11eb-9ad5-45e98b7c4022.png)

**Comment by jerrywgz** [comment]
可以尝试将配置文件中的worker_num减少至0观察下是否出错
