### ISSUE TITLE
使用676类提供的yaml进行预测，yaml读取失败

### ISSUE THREAD

**Issue by jinhaoyang007** [PaddlePaddle/PaddleDetection#3107]
File "/opt/conda/envs/yolo5_py3.8/lib/python3.8/site-packages/yaml/constructor.py", line 412, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!DecodeImage'
  in "/676/cascade_rcnn_cbr101_vd_fpn_server_side.yml", line 123, column 5

**Comment by jerrywgz** [comment]
目前cascade_rcnn_cbr101_vd_fpn_server_side.yml只在静态图中集成，需要想要使用请在static目录下运行，https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/static

**Comment by jinhaoyang007** [comment]
谢谢，static中检测ok。

**Comment by lazyn1997** [comment]
> 目前cascade_rcnn_cbr101_vd_fpn_server_side.yml只在静态图中集成，需要想要使用请在static目录下运行，https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/static

请问一下这个模型有办法转换为动态图版本吗
