### ISSUE TITLE
reader.py中数据维度如何调整

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/PaddleDetection#311]
mask rcnn的model_inputs
![TF183D%3H 772VUWU374JE2](https://user-images.githubusercontent.com/26462054/76133359-c102ea80-6052-11ea-849f-22870c59b97a.png)

yolov3的model_inputs
![`%5@Y69JXBA3JQQ4~T_37E4](https://user-images.githubusercontent.com/26462054/76133355-b9dbdc80-6052-11ea-8b12-15472a8ae513.png)

需要怎么调整reader.py才能使mask rcnn中输出的
gt_mask变成 [ None, num_max_boxer, 2] 这种维度

**Comment by zhengzhe97** [comment]
以gt_bbox为例，我输出reader.py中next函数的返回值中bbox的维度
![T%X_O I~%LMC@N%P_JH2GY8](https://user-images.githubusercontent.com/26462054/76134204-8485bd80-6057-11ea-825e-ad82852ae9ca.png)

yolov3 为 [ batch_size, num_boxes, 4]
mask rcnn 为 [ batch_size, num_boxes, 4]
输出上维数没什么差别，为什么到输入模型时会出现差异

**Comment by heavengate** [comment]
mask_rcnn模型中接受到的gt_mask是lod_tensor,是会保留每个sample的全部mask的，yolo模型接受的是tensor，是会按`num_max_boxes`补0或截断的，理论上来说lod_tensor的效果会好一些，这些都不影响模型的训练和预测，并且模型输出格式都是一致的

**Comment by zhengzhe97** [comment]
reader.py中next函数来产生下个batch的训练数据，不太明白为什么next中返回数据的维度是一样的，但是输入到模型中，数据维度出现差异。yolo用的是tensor，mask_rcnn用的是lod_tensor，但是具体是哪部分代码使返回的数据出现了差异

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/a764cd1eeaf27212e563a975ef7183d319cfc25d/ppdet/data/transform/operators.py#L1407
这里处理的，yolo的sample_transfrom里面会注册这个，mask不会，另外mask里的组网是基于lod tensor的，不需要注册这个

**Comment by zhengzhe97** [comment]
应该不是这个产生的差异。
1.PadBox只是用来填充bbox的数量到最大设定值
2.这些sample_transfrom是在next之前进行的，next输出结果并没有差异，应该是后面某个部分产生的差异

**Comment by zhengzhe97** [comment]
这边的lod_level用什么作用

**Comment by qingqing01** [comment]
@zhengzhe97  LODTensor是表示边长数据， 比如对于分割坐标的标注，每张图片，标注的坐标点个数不一样，不做额外的填充，用变长的LoDTensor表示(一个Tensor+一个表示每张图片多少坐标点数的Tensor表示)。  关闭了此issue， 如果还有新的问题，可以新开issue。
