### ISSUE TITLE
更新后续训错误

### ISSUE THREAD

**Issue by Mr-ind1fferent** [PaddlePaddle/PaddleDetection#3118]
name 'item' is not defined

**Comment by 1429392157** [comment]
> name 'item' is not defined

![image](https://user-images.githubusercontent.com/74087260/119125131-0519b980-ba64-11eb-8162-3b1a0bce608c.png)

**Comment by zhude233** [comment]
使用2.0版本的ppYOLOv2权重无法在2.1版本的paddleDetection上继续训练

**Comment by 1429392157** [comment]
![Uploading image.png…]()

**Comment by Mr-ind1fferent** [comment]
![image](https://user-images.githubusercontent.com/74087260/119141067-6b5c0780-ba77-11eb-9e55-733eee53800f.png)

**Comment by Mr-ind1fferent** [comment]
need help !!!!!!!!!

**Comment by jerrywgz** [comment]
Please check the weight you want to resume has the same class num with your model. The error message actually means the shape of loaded weight and model weight is not same. And I verify that PPYOLOv2 is correct when resuming

**Comment by HelloSZS** [comment]
我也遇到这个问题，改了模型参数stride和anchor_ratio、还有需要训练的epoch数之后，续训出现这个问题
