### ISSUE TITLE
多目标跟踪预测报错AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by yunchangxiaoguan** [PaddlePaddle/PaddleDetection#3123]
CUDA_VISIBLE_DEVICES=0 python3 tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=models/fairmot_dla34_30e_1088x608.pdparams --video_file=docs/abc.mp4  --save_videos
W0522 11:01:55.408041 29704 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 10.2, Runtime API Version: 10.2
W0522 11:01:55.413640 29704 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[05/22 11:01:57] ppdet.utils.checkpoint INFO: Finish resuming model weights: models/fairmot_dla34_30e_1088x608.pdparams
[05/22 11:01:57] ppdet.engine.tracker INFO: Starting tracking docs/abc.mp4
[05/22 11:01:57] ppdet.data.source.mot INFO: Length of the video: 980 frames
i None
im None
sample 1080
/ailab/gx/PaddleDetection/ppdet/data/reader.py:61: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  f, e, str(stack_info)))
[05/22 11:02:14] reader WARNING: fail to map sample transform [Decode_5fadaa] with error: 'NoneType' object has no attribute 'shape' and stack:
Traceback (most recent call last):
  File "/ailab/gx/PaddleDetection/ppdet/data/reader.py", line 56, in __call__
    data = f(data)
  File "/ailab/gx/PaddleDetection/ppdet/data/transform/operators.py", line 101, in __call__
    sample = self.apply(sample, context)
  File "/ailab/gx/PaddleDetection/ppdet/data/transform/operators.py", line 138, in apply
    elif sample['h'] != im.shape[0]:
AttributeError: 'NoneType' object has no attribute 'shape'

WARNING:root:DataLoader reader thread raised an exception.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 199, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 167, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/fetcher.py", line 61, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/fetcher.py", line 61, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "/ailab/gx/PaddleDetection/ppdet/data/source/dataset.py", line 87, in __getitem__
    return self.transform(roidb)
  File "/ailab/gx/PaddleDetection/ppdet/data/reader.py", line 62, in __call__
    raise e
  File "/ailab/gx/PaddleDetection/ppdet/data/reader.py", line 56, in __call__
    data = f(data)
  File "/ailab/gx/PaddleDetection/ppdet/data/transform/operators.py", line 101, in __call__
    sample = self.apply(sample, context)
  File "/ailab/gx/PaddleDetection/ppdet/data/transform/operators.py", line 138, in apply
    elif sample['h'] != im.shape[0]:
AttributeError: 'NoneType' object has no attribute 'shape'

Traceback (most recent call last):
  File "tools/infer_mot.py", line 115, in <module>
    main()
  File "tools/infer_mot.py", line 111, in main
    run(FLAGS, cfg)
  File "tools/infer_mot.py", line 97, in run
    det_results_dir=FLAGS.det_results_dir)
  File "/ailab/gx/PaddleDetection/ppdet/engine/tracker.py", line 359, in mot_predict
    frame_rate=frame_rate)
  File "/ailab/gx/PaddleDetection/ppdet/engine/tracker.py", line 125, in _eval_seq_jde
    for step_id, data in enumerate(dataloader):
  File "/ailab/gx/PaddleDetection/ppdet/data/reader.py", line 211, in __next__
    return next(self.loader)
  File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 204, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

请问这个要怎么处理，sample里面是有图像的，到了im就变成none了

**Comment by ANewAnonymous** [comment]
> CUDA_VISIBLE_DEVICES=0 python3 tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=models/fairmot_dla34_30e_1088x608.pdparams --video_file=docs/abc.mp4 --save_videos
> W0522 11:01:55.408041 29704 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 10.2, Runtime API Version: 10.2
> W0522 11:01:55.413640 29704 device_context.cc:422] device: 0, cuDNN Version: 7.6.
> [05/22 11:01:57] ppdet.utils.checkpoint INFO: Finish resuming model weights: models/fairmot_dla34_30e_1088x608.pdparams
> [05/22 11:01:57] ppdet.engine.tracker INFO: Starting tracking docs/abc.mp4
> [05/22 11:01:57] ppdet.data.source.mot INFO: Length of the video: 980 frames
> i None
> im None
> sample 1080
> /ailab/gx/PaddleDetection/ppdet/data/reader.py:61: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
> f, e, str(stack_info)))
> [05/22 11:02:14] reader WARNING: fail to map sample transform [Decode_5fadaa] with error: 'NoneType' object has no attribute 'shape' and stack:
> Traceback (most recent call last):
> File "/ailab/gx/PaddleDetection/ppdet/data/reader.py", line 56, in **call**
> data = f(data)
> File "/ailab/gx/PaddleDetection/ppdet/data/transform/operators.py", line 101, in **call**
> sample = self.apply(sample, context)
> File "/ailab/gx/PaddleDetection/ppdet/data/transform/operators.py", line 138, in apply
> elif sample['h'] != im.shape[0]:
> AttributeError: 'NoneType' object has no attribute 'shape'
> 
> WARNING:root:DataLoader reader thread raised an exception.
> Exception in thread Thread-1:
> Traceback (most recent call last):
> File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
> self.run()
> File "/usr/lib64/python3.6/threading.py", line 864, in run
> self._target(*self._args, **self._kwargs)
> File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 199, in _thread_loop
> six.reraise(*sys.exc_info())
> File "/usr/local/lib/python3.6/site-packages/six.py", line 703, in reraise
> raise value
> File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 167, in _thread_loop
> batch = self._dataset_fetcher.fetch(indices)
> File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/fetcher.py", line 61, in fetch
> data = [self.dataset[idx] for idx in batch_indices]
> File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/fetcher.py", line 61, in
> data = [self.dataset[idx] for idx in batch_indices]
> File "/ailab/gx/PaddleDetection/ppdet/data/source/dataset.py", line 87, in **getitem**
> return self.transform(roidb)
> File "/ailab/gx/PaddleDetection/ppdet/data/reader.py", line 62, in **call**
> raise e
> File "/ailab/gx/PaddleDetection/ppdet/data/reader.py", line 56, in **call**
> data = f(data)
> File "/ailab/gx/PaddleDetection/ppdet/data/transform/operators.py", line 101, in **call**
> sample = self.apply(sample, context)
> File "/ailab/gx/PaddleDetection/ppdet/data/transform/operators.py", line 138, in apply
> elif sample['h'] != im.shape[0]:
> AttributeError: 'NoneType' object has no attribute 'shape'
> 
> Traceback (most recent call last):
> File "tools/infer_mot.py", line 115, in
> main()
> File "tools/infer_mot.py", line 111, in main
> run(FLAGS, cfg)
> File "tools/infer_mot.py", line 97, in run
> det_results_dir=FLAGS.det_results_dir)
> File "/ailab/gx/PaddleDetection/ppdet/engine/tracker.py", line 359, in mot_predict
> frame_rate=frame_rate)
> File "/ailab/gx/PaddleDetection/ppdet/engine/tracker.py", line 125, in _eval_seq_jde for step_id, data in enumerate(dataloader): File "/ailab/gx/PaddleDetection/ppdet/data/reader.py", line 211, in **next** return next(self.loader) File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 204, in **next** data = self._reader.read_next_var_list() SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception. [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
> 
> 请问这个要怎么处理，sample里面是有图像的，到了im就变成none了

和你一样的问题  应该是bug  我还没有解决方法

**Comment by yunchangxiaoguan** [comment]
> > CUDA_VISIBLE_DEVICES=0 python3 tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=models/fairmot_dla34_30e_1088x608.pdparams --video_file=docs/abc.mp4 --save_videos
> > W0522 11:01:55.408041 29704 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 10.2, Runtime API Version: 10.2
> > W0522 11:01:55.413640 29704 device_context.cc:422] device: 0, cuDNN Version: 7.6.
> > [05/22 11:01:57] ppdet.utils.checkpoint INFO: Finish resuming model weights: models/fairmot_dla34_30e_1088x608.pdparams
> > [05/22 11:01:57] ppdet.engine.tracker INFO: Starting tracking docs/abc.mp4
> > [05/22 11:01:57] ppdet.data.source.mot INFO: Length of the video: 980 frames
> > i None
> > im None
> > sample 1080
> > /ailab/gx/PaddleDetection/ppdet/data/reader.py:61: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
> > f, e, str(stack_info)))
> > [05/22 11:02:14] reader WARNING: fail to map sample transform [Decode_5fadaa] with error: 'NoneType' object has no attribute 'shape' and stack:
> > Traceback (most recent call last):
> > File "/ailab/gx/PaddleDetection/ppdet/data/reader.py", line 56, in **call**
> > data = f(data)
> > File "/ailab/gx/PaddleDetection/ppdet/data/transform/operators.py", line 101, in **call**
> > sample = self.apply(sample, context)
> > File "/ailab/gx/PaddleDetection/ppdet/data/transform/operators.py", line 138, in apply
> > elif sample['h'] != im.shape[0]:
> > AttributeError: 'NoneType' object has no attribute 'shape'
> > WARNING:root:DataLoader reader thread raised an exception.
> > Exception in thread Thread-1:
> > Traceback (most recent call last):
> > File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
> > self.run()
> > File "/usr/lib64/python3.6/threading.py", line 864, in run
> > self._target(*self._args, **self._kwargs)
> > File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 199, in _thread_loop
> > six.reraise(*sys.exc_info())
> > File "/usr/local/lib/python3.6/site-packages/six.py", line 703, in reraise
> > raise value
> > File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 167, in _thread_loop
> > batch = self._dataset_fetcher.fetch(indices)
> > File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/fetcher.py", line 61, in fetch
> > data = [self.dataset[idx] for idx in batch_indices]
> > File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/fetcher.py", line 61, in
> > data = [self.dataset[idx] for idx in batch_indices]
> > File "/ailab/gx/PaddleDetection/ppdet/data/source/dataset.py", line 87, in **getitem**
> > return self.transform(roidb)
> > File "/ailab/gx/PaddleDetection/ppdet/data/reader.py", line 62, in **call**
> > raise e
> > File "/ailab/gx/PaddleDetection/ppdet/data/reader.py", line 56, in **call**
> > data = f(data)
> > File "/ailab/gx/PaddleDetection/ppdet/data/transform/operators.py", line 101, in **call**
> > sample = self.apply(sample, context)
> > File "/ailab/gx/PaddleDetection/ppdet/data/transform/operators.py", line 138, in apply
> > elif sample['h'] != im.shape[0]:
> > AttributeError: 'NoneType' object has no attribute 'shape'
> > Traceback (most recent call last):
> > File "tools/infer_mot.py", line 115, in
> > main()
> > File "tools/infer_mot.py", line 111, in main
> > run(FLAGS, cfg)
> > File "tools/infer_mot.py", line 97, in run
> > det_results_dir=FLAGS.det_results_dir)
> > File "/ailab/gx/PaddleDetection/ppdet/engine/tracker.py", line 359, in mot_predict
> > frame_rate=frame_rate)
> > File "/ailab/gx/PaddleDetection/ppdet/engine/tracker.py", line 125, in _eval_seq_jde for step_id, data in enumerate(dataloader): File "/ailab/gx/PaddleDetection/ppdet/data/reader.py", line 211, in **next** return next(self.loader) File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 204, in **next** data = self._reader.read_next_var_list() SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception. [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
> > 请问这个要怎么处理，sample里面是有图像的，到了im就变成none了
> 
> 和你一样的问题 应该是bug 我还没有解决方法

原来是这样，我还搞了好半天，windows，linux都试了

**Comment by nemonameless** [comment]
@ANewAnonymous @yunchangxiaoguan   已修复了
