### ISSUE TITLE
使用自定义coco数据集训练，可以正常训练，但label list里的label不会变成自定义的label

### ISSUE THREAD

**Issue by JustinHuang1984** [PaddlePaddle/PaddleDetection#3133]
使用自定义coco数据集训练，可以正常训练，训练出来的模型也是能正常推理的，检查json文件也是没问题的，但infer_cfg.yml文件里的label list里的label不会变成自定义的label,想问下这样是正常吗？
![1621778620(1)](https://user-images.githubusercontent.com/59753769/119263864-5f0cb180-bc13-11eb-9581-5972c77dcc10.png)

**Comment by liuhuiCNN** [comment]
请您检查一下 config.yml 中的TestReader中数据路径配置是否正确。

**Comment by JustinHuang1984** [comment]
是的，这个地方的路径填写错了，感谢回复

**Comment by liuhuiCNN** [comment]
> 是的，这个地方的路径填写错了，感谢回复

好的，本issue先关闭了。
