### ISSUE TITLE
模型保存设置

### ISSUE THREAD

**Issue by FL77N** [PaddlePaddle/PaddleDetection#3136]
你好，请问关于模型保存的 epoch 在哪设置呢，比如我想10个epoch保存一次，而且只保存最好的，如果精度没提高就不保存，应该怎么设置呢？

**Comment by FL77N** [comment]
还有一个问题需要请教，就是随机种子在哪设置呢

**Comment by AN-ZE** [comment]
新版本的在runtime.yml中设置
snapshot_epoch: 1

旧版本在每个配置文件中设置
snapshot_iter: 29715

训练的时候加入验证集，就会自动生成应该base_model, 用来保存val集中mAP最高的一个。

**Comment by wangxinxin08** [comment]
> 还有一个问题需要请教，就是随机种子在哪设置呢

可以使用paddle.seed, random.seed设置随机种子，可以参考此处进行修改https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/engine/env.py#L33

**Comment by FL77N** [comment]
> > 还有一个问题需要请教，就是随机种子在哪设置呢
> 
> 可以使用paddle.seed, random.seed设置随机种子，可以参考此处进行修改https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/engine/env.py#L33

谢谢，我在使用 paddledetection 2.0.2 源码，在aistudio 脚本任务进行单机四卡训练一直出现以下错误

INFO 2021-05-24 17:17:14,611 launch_utils.py:307] terminate all the procs
ERROR 2021-05-24 17:17:14,611 launch_utils.py:545] ABORT!!! Out of all 4 trainers, the trainer process with rank=[3] was aborted. Please check its log.
INFO 2021-05-24 17:17:17,615 launch_utils.py:307] terminate all the procs
[INFO]: train job failed! train_ret: 1

使用的 python -m paddle.distributed.launch tools/train.py -c ../... .yml --eval 启动的，请问是哪没设置好吗

**Comment by wangxinxin08** [comment]
@FL77N 可以减小reader中的worker_num，猜测是由于共享内存不够导致的

**Comment by FL77N** [comment]
> @FL77N 可以减小reader中的worker_num，猜测是由于共享内存不够导致的

额，我已经由8减为了4仍会出错，还需要继续减小吗

**Comment by wangxinxin08** [comment]
可以继续减小下

**Comment by FL77N** [comment]
> 可以继续减小下

嗯嗯我直接设置为1试试

**Comment by FL77N** [comment]
> 可以继续减小下

依然会报错

**Comment by FL77N** [comment]
> 可以继续减小下

你好，我减小了batch_size 不会报错了，但是报了显存不够，请教一下，config设置的batch_size，比如4，在多卡训练的时候是每张卡都是4，还是每张卡为 4/num_gpu呢？

**Comment by wangxinxin08** [comment]
> > 可以继续减小下
> 
> 你好，我减小了batch_size 不会报错了，但是报了显存不够，请教一下，config设置的batch_size，比如4，在多卡训练的时候是每张卡都是4，还是每张卡为 4/num_gpu呢？

每张卡都是4

**Comment by wangxinxin08** [comment]
鉴于问题已经解决，此issue将被关闭

**Comment by FL77N** [comment]
> > > 可以继续减小下
> > 
> > 
> > 你好，我减小了batch_size 不会报错了，但是报了显存不够，请教一下，config设置的batch_size，比如4，在多卡训练的时候是每张卡都是4，还是每张卡为 4/num_gpu呢？
> 
> 每张卡都是4

谢谢你，提醒了我可能是显存不够，解决了问题

**Comment by gaorui999** [comment]
> > 还有一个问题需要请教，就是随机种子在哪设置呢
> 
> 可以使用paddle.seed, random.seed设置随机种子，可以参考此处进行修改https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/engine/env.py#L33
