### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TingquanGao** [PaddlePaddle/PaddleDetection#3137]
使用摄像头时报错，此时`image_list`似乎不是list类型。
https://github.com/PaddlePaddle/PaddleDetection/blob/653ebe9fa2a15d966797153fe47d5aa4af2604bc/deploy/python/infer.py#L101

**Comment by wangxinxin08** [comment]
感谢你的反馈，你可以在https://github.com/PaddlePaddle/PaddleDetection/blob/653ebe9fa2a15d966797153fe47d5aa4af2604bc/deploy/python/infer.py#L553 修改frame为[frame]，将其变为image_list，后续我们会修复这个bug

**Comment by wangxinxin08** [comment]
鉴于问题已经解决，此问题将被关闭
