### ISSUE TITLE
训练私有数据集，配置文件参数求指导

### ISSUE THREAD

**Issue by HaiLongEmb** [PaddlePaddle/PaddleDetection#314]
我想使用PaddleDetection中的yolov3_r50vd_dcn模型训练私有数据集，但配置文件中有地方不太懂，如果我想前1000epoch冻结ResNet后面再解冻，应该如何如何设置，freeze_at默认值是0代表什么含义。

**Comment by HaiLongEmb** [comment]
[yolov3_r50vd_dcn_voc_test.yml.txt](https://github.com/PaddlePaddle/PaddleDetection/files/4305296/yolov3_r50vd_dcn_voc_test.yml.txt)

**Comment by qingqing01** [comment]
@HaiLongEmb  ResNet有5个stage，通过`feature_maps`设置返回那个stage，默认是返回第5个stage (从1开始)，通过 `freeze_at `设置冻结到那个stage，不参与训练，例如RCNN模型中：

```
ResNet:
  depth: 50
  feature_maps: 4
  freeze_at: 2
```

`freeze_at默认值是0` 代表不冻结，都参与训练。 如果`想前1000epoch冻结ResNet后面再解冻`，目前看得分2步训练： 第一步设置freeze_at为5，训练1000 epoch结束。第二步，设置freeze_at为0，从第一步恢复训练。

**Comment by HaiLongEmb** [comment]
@qingqing01 感谢回答，清晰多了，还有个问题，配置文件中我只看到了max_iters参数，没有epoch参数，现在是epoch参数取消了吗？# ResNet variant, supports 'a', 'b', 'c', 'd' currently, b by default 这个参数是什么含义，都有什么区别

**Comment by qingqing01** [comment]
在PaddleDetection里去掉了epoch的概念，通过steps设置max_iters和学习率衰减策略等。但Mixup的数据增强里有epoch的概念。(实际上reader里还有epoch的概念)。

> ResNet variant, supports 'a', 'b', 'c', 'd

是ResNet的4种变种，2x2的下采样卷积的位置等有所调整，减少特征的损失。可以参考: http://ai.baidu.com/forum/topic/show/953135 

ResNet-vd的分类精度最高，我们提供的模型有基于ResNet-vb和ResNet-vd的。在RCNN模型上，精度普遍提升1%-2%，可以参考model-zoo。
