### ISSUE TITLE
PaddleDetection有没有提供导出为预训练模型的方法？

### ISSUE THREAD

**Issue by AlexDish** [PaddlePaddle/PaddleDetection#3143]
如题，PaddleDetection有没有提供导出为预训练模型的方法？

目前已经掌握PaddleDetecton导出推理模型。
现在想导出自己的预训练模型，以便以后直接使用。
不知道目前的PaddleDetection有没有提供？

**Comment by AN-ZE** [comment]
导出模型，作为预训练模型？
不需要导出，直接修改配置文件中 预训练模型权重
修改成自己训练生成的模型，作为预训练模型，也算是迁移学习了
```
#pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams
pretrain_weights: /home/an/save_model/fruit_cascade_frcnn_r50vd_dcn_fpn_0713/model_final
```

**Comment by AlexDish** [comment]
> 导出模型，作为预训练模型？
> 不需要导出，直接修改配置文件中 预训练模型权重
> 修改成自己训练生成的模型，作为预训练模型，也算是迁移学习了
> 
> ```
> #pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams
> pretrain_weights: /home/an/save_model/fruit_cascade_frcnn_r50vd_dcn_fpn_0713/model_final
> ```

了解，我先试试，不过目前尝试使用A数据集训练出的模型加载后，重新训练回A数据集本尊的，再到eval时，mAP只有0.1%，loss也是从很大开始。
我再研究研究。
