### ISSUE TITLE
怎么用训练模型接着训练？？？？？

### ISSUE THREAD

**Issue by dzz416** [PaddlePaddle/PaddleDetection#3149]
用paddledetection 中的pygraph中的config更改了预训练模型得地址:
pretrain_weights: ./output/faster_rcnn_x101_vd_64x4d_fpn_1x_coco/9
#pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNeXt101_vd_64x4d_pretrained.tar
为什么还是从头开始训练？

**Comment by wangxinxin08** [comment]
resume请参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/tools/train.py#L51，即指定-r /path/to/your/weights来resume

**Comment by dzz416** [comment]
> resume请参考[https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/tools/train.py#L51，即指定-r](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/tools/train.py#L51%EF%BC%8C%E5%8D%B3%E6%8C%87%E5%AE%9A-r) /path/to/your/weights来resume

train.py: error: unrecognized arguments: -r output/faster_rcnn_x101_vd_64x4d_fpn_1x_coco/9还是不行

**Comment by wangxinxin08** [comment]
你使用的应该是release/2.0-rc分支吧，可以参考tools/train.py里面的flag设置，如--weight_type=resume -o pretrain_weights=/path/to/weights
