### ISSUE TITLE
加载了自己训练的预训练模型为什么没有用？

### ISSUE THREAD

**Issue by dzz416** [PaddlePaddle/PaddleDetection#3150]

**Comment by wangxinxin08** [comment]
可能的原因为：
1.没有正确的指定预训练模型的路径
2.如果需要resume训练的话，需要使用--resume /path/to/your/weights来加载原先的模型

**Comment by dzz416** [comment]
> 可能的原因为：
> 1.没有正确的指定预训练模型的路径
> 2.如果需要resume训练的话，需要使用--resume /path/to/your/weights来加载原先的模型

train.py: error: unrecognized arguments: --resume output/faster_rcnn_x101_vd_64x4d_fpn_1x_coco/9还是不行

**Comment by wangxinxin08** [comment]
参考https://github.com/PaddlePaddle/PaddleDetection/issues/3149来解决
