### ISSUE TITLE
ValueError: (InvalidArgument) : yml配置None识别为str

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/PaddleDetection#3154]

**Comment by Darki-luo** [comment]
> 下载了paddledetection 2.1.0 想试试模型能不能跑起来，但是在验证预设的模型时候就没法运行。
> 具体代码如下：
> %cd PaddleDetection/
> from ppdet.core.workspace import load_config,create
> import paddle
> cfg = load_config("configs/cascade_rcnn/cascade_mask_rcnn_r50_fpn_1x_coco.yml")
> model = create(cfg.architecture)
> img1 = paddle.rand([1,3,512,512],dtype='float32')
> out_p = model(img1)
> 
> ---------------------------------------------------------------------------ValueError Traceback (most recent call last) in
> ----> 1 out_p = model(img1)
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in **call**(self, *inputs, **kwargs)
> 896 self._built = True
> 897
> --> 898 outputs = self.forward(*inputs, **kwargs)
> 899
> 900 for forward_post_hook in self._forward_post_hooks.values():
> ~/PaddleDetection/ppdet/modeling/architectures/meta_arch.py in forward(self, inputs)
> 25
> 26 if self.training:
> ---> 27 out = self.get_loss()
> 28 else:
> 29 out = self.get_pred()
> ~/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py in get_loss(self)
> 123
> 124 def get_loss(self, ):
> --> 125 rpn_loss, bbox_loss, mask_loss = self._forward()
> 126 loss = {}
> 127 loss.update(rpn_loss)
> ~/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py in _forward(self)
> 85
> 86 def _forward(self):
> ---> 87 body_feats = self.backbone(self.inputs)
> 88 if self.neck is not None:
> 89 body_feats = self.neck(body_feats)
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in **call**(self, *inputs, **kwargs)
> 896 self._built = True
> 897
> --> 898 outputs = self.forward(*inputs, __kwargs) 899 900 for forward_post_hook in self._forward_post_hooks.values(): ~/PaddleDetection/ppdet/modeling/backbones/resnet.py in forward(self, inputs) 570 571 def forward(self, inputs): --> 572 x = inputs['image'] 573 conv1 = self.conv1(x) 574 x = F.max_pool2d(conv1, kernel_size=3, stride=2, padding=1) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py in **getitem**(self, item) 558 else: 559 # 2. Call c++ func getitem_index_not_tensor to speedup. --> 560 return self._getitem_index_not_tensor(item) 561 562 for method_name, method in ( ValueError: (InvalidArgument) Currently, VarBase.**getitem**() only allows indexing by Integers, Slices, and tuples of these types, but received str in 1th slice item [Hint: Expected PyCheckInteger(slice_item) || ((((PyObject_)(slice_item))->ob_type) == &PySlice_Type) == true, but received PyCheckInteger(slice_item) || ((((PyObject_)(slice_item))->ob_type) == &PySlice_Type):0 != true:1.] (at /paddle/paddle/fluid/pybind/imperative.cc:430)

这个是套件里本身的yml，没有改动的

**Comment by lyuwenyu** [comment]
代码方便贴一下嘛，   （ 另外paddle版本是哪个， 2.1 Tensor/VarBase支持indexing包括Integers Slices tuples

**Comment by Darki-luo** [comment]
> 代码方便贴一下嘛， （ 另外paddle版本是哪个， 2.1 Tensor/VarBase支持indexing包括Integers Slices tuples


paddle版本2.1.0 det套件2.1.0

贴错代码了：
ValueError: (InvalidArgument) Cannot get attribute (value) by type float, its type is class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >. (at C:\home\workspace\Paddle_release\paddle/fluid/framework/attribute.h:164)

我在backbone添加了自定义的swintransformer, 单独测试backbone的时候是正常输出的，但是使用套件里大测试backbone就会出错。
已经初步确定了bug的地方：

网络结构windows attention 里有一个初始化参数 self.scale  = qk_scale or head_dim ** -0.5，qk_scale 默认值是None, 正常来说应该赋值 head_dim ** -0.5， 直接测试的时候打印这个都是有值的 0.17左右（self.scale: 0.1767766952966369），但是在det套件里值是None，

具体这个函数：
class WindowAttention(nn.Layer):
	""" Window based multi-head self attention (W-MSA) module with relative position bias.
	It supports both of shifted and non-shifted window.

	Args:
		dim (int): Number of input channels.
		window_size (tuple[int]): The height and width of the window.
		num_heads (int): Number of attention heads.
		qkv_bias (bool, optional):  If True, add a learnable bias to query, key, value. Default: True
		qk_scale (float | None, optional): Override default qk scale of head_dim ** -0.5 if set
		attn_drop (float, optional): Dropout ratio of attention weight. Default: 0.0
		proj_drop (float, optional): Dropout ratio of output. Default: 0.0
	"""
	
	def __init__(self, dim, window_size, num_heads, qkv_bias=True, qk_scale=None, attn_drop=0., proj_drop=0.):
		
		super().__init__()
		self.dim = dim
		head_dim = dim // num_heads
		self.scale = qk_scale or head_dim ** -0.5



——————————————————————————————————
用套件的函数测试代码：

from ppdet.core.workspace import load_config,create
import paddle
cfg = load_config("configs/cascade_rcnn/cascade_mask_rcnn_swin_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.yml")
model = create(cfg.architecture)

import numpy as np
img = np.ones([1,3,512,512]).astype("float32")
img1 =paddle.to_tensor(img)
input = {"image":img1}

out_p = model.backbone(input)

——————————

错误信息：
self.scale: None

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-3-2ad019cdd34c> in <module>
----> 1 out_p = model.backbone(input)
      2 
      3 

D:\conda\lib\site-packages\paddle\fluid\dygraph\layers.py in __call__(self, *inputs, **kwargs)
    896                 self._built = True
    897 
--> 898             outputs = self.forward(*inputs, **kwargs)
    899 
    900             for forward_post_hook in self._forward_post_hooks.values():

D:\python\PaddleDetection\ppdet\modeling\backbones\swin.py in forward(self, x)
    670                         layer = self.layers[i]
    671                         # print(x.shape)
--> 672                         x_out, H, W, x, Wh, Ww = layer(x, Wh, Ww)
    673 
    674                         if i in self.return_idx:

D:\conda\lib\site-packages\paddle\fluid\dygraph\layers.py in __call__(self, *inputs, **kwargs)
    896                 self._built = True
    897 
--> 898             outputs = self.forward(*inputs, **kwargs)
    899 
    900             for forward_post_hook in self._forward_post_hooks.values():

D:\python\PaddleDetection\ppdet\modeling\backbones\swin.py in forward(self, x, H, W)
    467                 for blk in self.blocks:
    468                         blk.H, blk.W = H, W
--> 469                         x = blk(x, attn_mask)
    470                 if self.downsample is not None:
    471                         x_down = self.downsample(x,H,W)

D:\conda\lib\site-packages\paddle\fluid\dygraph\layers.py in __call__(self, *inputs, **kwargs)
    896                 self._built = True
    897 
--> 898             outputs = self.forward(*inputs, **kwargs)
    899 
    900             for forward_post_hook in self._forward_post_hooks.values():

D:\python\PaddleDetection\ppdet\modeling\backbones\swin.py in forward(self, x, mask_matrix)
    318                 #print(x_windows.shape, mask_matrix.shape)
    319                 # W-MSA/SW-MSA
--> 320                 attn_windows = self.attn(x_windows, mask=attn_mask)  # nW*B, window_size*window_size, C
    321                 #print(attn_windows.shape, x_windows.shape)
    322                 # merge windows

D:\conda\lib\site-packages\paddle\fluid\dygraph\layers.py in __call__(self, *inputs, **kwargs)
    896                 self._built = True
    897 
--> 898             outputs = self.forward(*inputs, **kwargs)
    899 
    900             for forward_post_hook in self._forward_post_hooks.values():

D:\python\PaddleDetection\ppdet\modeling\backbones\swin.py in forward(self, x, mask)
    150                 # attn = paddle.matmul(q,k,transpose_y=True)
    151                 print('self.scale:',self.scale)
--> 152                 attn = attn * self.scale
    153 		relative_position_bias = paddle.index_select(self.relative_position_bias_table,
    154                                                                                                          self.relative_position_index.reshape((-1,)), axis=0).reshape(

D:\conda\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py in __impl__(self, other_var)
    217                 else:
    218                     # add fill_op
--> 219                     other_var = create_scalar(value=other_var, dtype=lhs_dtype)
    220 
    221             # 3. promote types or unify right var type to left var

D:\conda\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py in create_scalar(value, dtype)
     77 
     78     def create_scalar(value, dtype):
---> 79         return create_tensor(value, dtype, shape=[1])
     80 
     81     def astype(self, dtype):

<decorator-gen-244> in create_tensor(value, dtype, shape)

D:\conda\lib\site-packages\paddle\fluid\dygraph\base.py in __impl__(func, *args, **kwargs)
    259         def __impl__(func, *args, **kwargs):
    260             with _switch_tracer_mode_guard_(is_train=False):
--> 261                 return func(*args, **kwargs)
    262 
    263         return __impl__(func)

D:\conda\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py in create_tensor(value, dtype, shape)
     71     def create_tensor(value, dtype, shape):
     72         out = _varbase_creator(dtype=dtype)
---> 73         out = core.ops.fill_constant(out, 'dtype', dtype, 'shape', shape,
     74                                      'value', value, 'force_cpu', False)
     75         out.stop_gradient = True

ValueError: (InvalidArgument) Cannot get attribute (value) by type float, its type is class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >. (at C:\home\workspace\Paddle_release\paddle/fluid/framework/attribute.h:164)

**Comment by Darki-luo** [comment]
> > 代码方便贴一下嘛， （ 另外paddle版本是哪个， 2.1 Tensor/VarBase支持indexing包括Integers Slices tuples
> 
> paddle版本2.1.0 det套件2.1.0
> 
> 贴错代码了：
> ValueError: (InvalidArgument) Cannot get attribute (value) by type float, its type is class std::basic_string<char,struct std::char_traits,class std::allocator >. (at C:\home\workspace\Paddle_release\paddle/fluid/framework/attribute.h:164)
> 
> 我在backbone添加了自定义的swintransformer, 单独测试backbone的时候是正常输出的，但是使用套件里大测试backbone就会出错。
> 已经初步确定了bug的地方：
> 
> 网络结构windows attention 里有一个初始化参数 self.scale = qk_scale or head_dim ** -0.5，qk_scale 默认值是None, 正常来说应该赋值 head_dim ** -0.5， 直接测试的时候打印这个都是有值的 0.17左右（self.scale: 0.1767766952966369），但是在det套件里值是None，
> 
> 具体这个函数：
> class WindowAttention(nn.Layer):
> """ Window based multi-head self attention (W-MSA) module with relative position bias.
> It supports both of shifted and non-shifted window.
> 
> ```
> Args:
> 	dim (int): Number of input channels.
> 	window_size (tuple[int]): The height and width of the window.
> 	num_heads (int): Number of attention heads.
> 	qkv_bias (bool, optional):  If True, add a learnable bias to query, key, value. Default: True
> 	qk_scale (float | None, optional): Override default qk scale of head_dim ** -0.5 if set
> 	attn_drop (float, optional): Dropout ratio of attention weight. Default: 0.0
> 	proj_drop (float, optional): Dropout ratio of output. Default: 0.0
> """
> 
> def __init__(self, dim, window_size, num_heads, qkv_bias=True, qk_scale=None, attn_drop=0., proj_drop=0.):
> 	
> 	super().__init__()
> 	self.dim = dim
> 	head_dim = dim // num_heads
> 	self.scale = qk_scale or head_dim ** -0.5
> ```
> 
> ——————————————————————————————————
> 用套件的函数测试代码：
> 
> from ppdet.core.workspace import load_config,create
> import paddle
> cfg = load_config("configs/cascade_rcnn/cascade_mask_rcnn_swin_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.yml")
> model = create(cfg.architecture)
> 
> import numpy as np
> img = np.ones([1,3,512,512]).astype("float32")
> img1 =paddle.to_tensor(img)
> input = {"image":img1}
> 
> out_p = model.backbone(input)
> 
> ——————————
> 
> 错误信息：
> self.scale: None
> 
> ValueError Traceback (most recent call last)
> 
> in
> ----> 1 out_p = model.backbone(input)
> 2
> 3
> 
> D:\conda\lib\site-packages\paddle\fluid\dygraph\layers.py in **call**(self, *inputs, **kwargs)
> 896 self._built = True
> 897
> --> 898 outputs = self.forward(*inputs, **kwargs)
> 899
> 900 for forward_post_hook in self._forward_post_hooks.values():
> 
> D:\python\PaddleDetection\ppdet\modeling\backbones\swin.py in forward(self, x)
> 670 layer = self.layers[i]
> 671 # print(x.shape)
> --> 672 x_out, H, W, x, Wh, Ww = layer(x, Wh, Ww)
> 673
> 674 if i in self.return_idx:
> 
> D:\conda\lib\site-packages\paddle\fluid\dygraph\layers.py in **call**(self, *inputs, **kwargs)
> 896 self._built = True
> 897
> --> 898 outputs = self.forward(*inputs, **kwargs)
> 899
> 900 for forward_post_hook in self._forward_post_hooks.values():
> 
> D:\python\PaddleDetection\ppdet\modeling\backbones\swin.py in forward(self, x, H, W)
> 467 for blk in self.blocks:
> 468 blk.H, blk.W = H, W
> --> 469 x = blk(x, attn_mask)
> 470 if self.downsample is not None:
> 471 x_down = self.downsample(x,H,W)
> 
> D:\conda\lib\site-packages\paddle\fluid\dygraph\layers.py in **call**(self, *inputs, **kwargs)
> 896 self._built = True
> 897
> --> 898 outputs = self.forward(*inputs, **kwargs)
> 899
> 900 for forward_post_hook in self._forward_post_hooks.values():
> 
> D:\python\PaddleDetection\ppdet\modeling\backbones\swin.py in forward(self, x, mask_matrix)
> 318 #print(x_windows.shape, mask_matrix.shape)
> 319 # W-MSA/SW-MSA
> --> 320 attn_windows = self.attn(x_windows, mask=attn_mask) # nW_B, window_size_window_size, C
> 321 #print(attn_windows.shape, x_windows.shape)
> 322 # merge windows
> 
> D:\conda\lib\site-packages\paddle\fluid\dygraph\layers.py in **call**(self, *inputs, **kwargs)
> 896 self._built = True
> 897
> --> 898 outputs = self.forward(*inputs, **kwargs)
> 899
> 900 for forward_post_hook in self._forward_post_hooks.values():
> 
> D:\python\PaddleDetection\ppdet\modeling\backbones\swin.py in forward(self, x, mask)
> 150 # attn = paddle.matmul(q,k,transpose_y=True)
> 151 print('self.scale:',self.scale)
> --> 152 attn = attn * self.scale
> 153 relative_position_bias = paddle.index_select(self.relative_position_bias_table,
> 154 self.relative_position_index.reshape((-1,)), axis=0).reshape(
> 
> D:\conda\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py in **impl**(self, other_var)
> 217 else:
> 218 # add fill_op
> --> 219 other_var = create_scalar(value=other_var, dtype=lhs_dtype)
> 220
> 221 # 3. promote types or unify right var type to left var
> 
> D:\conda\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py in create_scalar(value, dtype)
> 77
> 78 def create_scalar(value, dtype):
> ---> 79 return create_tensor(value, dtype, shape=[1])
> 80
> 81 def astype(self, dtype):
> 
> in create_tensor(value, dtype, shape)
> 
> D:\conda\lib\site-packages\paddle\fluid\dygraph\base.py in **impl**(func, *args, **kwargs)
> 259 def **impl**(func, *args, **kwargs):
> 260 with _switch_tracer_mode_guard_(is_train=False):
> --> 261 return func(*args, **kwargs)
> 262
> 263 return **impl**(func)
> 
> D:\conda\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py in create_tensor(value, dtype, shape)
> 71 def create_tensor(value, dtype, shape):
> 72 out = _varbase_creator(dtype=dtype)
> ---> 73 out = core.ops.fill_constant(out, 'dtype', dtype, 'shape', shape,
> 74 'value', value, 'force_cpu', False)
> 75 out.stop_gradient = True
> 
> ValueError: (InvalidArgument) Cannot get attribute (value) by type float, its type is class std::basic_string<char,struct std::char_traits,class std::allocator >. (at C:\home\workspace\Paddle_release\paddle/fluid/framework/attribute.h:164)

我把 self.scale = qk_scale or head_dim ** -0.5 调换了一下顺序就正常了，就是self.scale =  head_dim ** -0.5  or qk_scale

**Comment by lyuwenyu** [comment]
好的, Python里 (a or b) 
- a等价True的时候  b就不执行了 返回a的结果,  or语句就结束了  
- a等价False的时候直接返回b执行的结果，
- or里等价False的一般都是 0 None []等

- 使用 if else直观点  -.-
> self.scale =  head_dim ** -0.5  if qk_scale is None else qk_scale

**Comment by Darki-luo** [comment]
> 好的, Python里 (a or b)
> 
> * a等价True的时候  b就不执行了 返回a的结果,  or语句就结束了
> * a等价False的时候直接返回b执行的结果，
> * or里等价False的一般都是 0 None []等
> * 使用 if else直观点  -.-
> 
> > self.scale =  head_dim ** -0.5  if qk_scale is None else qk_scale

我理解这个语法，我是觉得套件里存在bug，我单独运行测试模型的时候（a代指原代码里的self.qkv ,本来就没赋值，默认就是None）a=None(等价False）就是返回b（代指原代码的head_dim ** -0.5）的结果，就是原来测试的0.17左右的值，但是在det套件里运行就是返回的None(不等价False)

**Comment by lyuwenyu** [comment]
> > 好的, Python里 (a or b)
> > 
> > * a等价True的时候  b就不执行了 返回a的结果,  or语句就结束了
> > * a等价False的时候直接返回b执行的结果，
> > * or里等价False的一般都是 0 None []等
> > * 使用 if else直观点  -.-
> > 
> > > self.scale =  head_dim ** -0.5  if qk_scale is None else qk_scale
> 
> 我理解这个语法，我是觉得套件里存在bug，我单独运行测试模型的时候（a代指原代码里的self.qkv ,本来就没赋值，默认就是None）a=None(等价False）就是返回b（代指原代码的head_dim ** -0.5）的结果，就是原来测试的0.17左右的值，但是在det套件里运行就是返回的None(不等价False)

你有打印出来self.qkv是什么嘛

**Comment by Darki-luo** [comment]
> > > 好的, Python里 (a or b)
> > > 
> > > * a等价True的时候  b就不执行了 返回a的结果,  or语句就结束了
> > > * a等价False的时候直接返回b执行的结果，
> > > * or里等价False的一般都是 0 None []等
> > > * 使用 if else直观点  -.-
> > > 
> > > > self.scale =  head_dim ** -0.5  if qk_scale is None else qk_scale
> > 
> > 
> > 我理解这个语法，我是觉得套件里存在bug，我单独运行测试模型的时候（a代指原代码里的self.qkv ,本来就没赋值，默认就是None）a=None(等价False）就是返回b（代指原代码的head_dim ** -0.5）的结果，就是原来测试的0.17左右的值，但是在det套件里运行就是返回的None(不等价False)
> 
> 你有打印出来self.qkv是什么嘛

有啊，
单独测试模型的时候
self.scale: 0.1767766952966369

在套件里运行的时候：
错误信息：
self.scale: None

**Comment by lyuwenyu** [comment]
> > > > 好的, Python里 (a or b)
> > > > 
> > > > * a等价True的时候  b就不执行了 返回a的结果,  or语句就结束了
> > > > * a等价False的时候直接返回b执行的结果，
> > > > * or里等价False的一般都是 0 None []等
> > > > * 使用 if else直观点  -.-
> > > > 
> > > > > self.scale =  head_dim ** -0.5  if qk_scale is None else qk_scale
> > > 
> > > 
> > > 我理解这个语法，我是觉得套件里存在bug，我单独运行测试模型的时候（a代指原代码里的self.qkv ,本来就没赋值，默认就是None）a=None(等价False）就是返回b（代指原代码的head_dim ** -0.5）的结果，就是原来测试的0.17左右的值，但是在det套件里运行就是返回的None(不等价False)
> > 
> > 
> > 你有打印出来self.qkv是什么嘛
> 
> 有啊，
> 单独测试模型的时候
> self.scale: 0.1767766952966369
> 
> 在套件里运行的时候：
> 错误信息：
> self.scale: None

我测试了一下 结果时符合预期的啊
- https://github.com/lyuwenyu/PaddleDetection/blob/test_create_v1/tetst_swin.py

- 是不是有同样的名字 导致参数覆盖了

**Comment by Darki-luo** [comment]
> > > > > 好的, Python里 (a or b)
> > > > > 
> > > > > * a等价True的时候  b就不执行了 返回a的结果,  or语句就结束了
> > > > > * a等价False的时候直接返回b执行的结果，
> > > > > * or里等价False的一般都是 0 None []等
> > > > > * 使用 if else直观点  -.-
> > > > > 
> > > > > > self.scale =  head_dim ** -0.5  if qk_scale is None else qk_scale
> > > > 
> > > > 
> > > > 我理解这个语法，我是觉得套件里存在bug，我单独运行测试模型的时候（a代指原代码里的self.qkv ,本来就没赋值，默认就是None）a=None(等价False）就是返回b（代指原代码的head_dim ** -0.5）的结果，就是原来测试的0.17左右的值，但是在det套件里运行就是返回的None(不等价False)
> > > 
> > > 
> > > 你有打印出来self.qkv是什么嘛
> > 
> > 
> > 有啊，
> > 单独测试模型的时候
> > self.scale: 0.1767766952966369
> > 在套件里运行的时候：
> > 错误信息：
> > self.scale: None
> 
> 我测试了一下 结果时符合预期的啊
> 
> * https://github.com/lyuwenyu/PaddleDetection/blob/test_create_v1/tetst_swin.py
> * 是不是有同样的名字 导致参数覆盖了


实际的模型要比你仓库的要复杂一些，在windowsattention函数里没有覆盖的情况，这个是我在AS上的链接，打印会出现None。共享链接: https://aistudio.baidu.com/studio/project/partial/verify/1988508/187a27f615ae4a40b0ff8b4191830c56

**Comment by lyuwenyu** [comment]
- 跑你的config确实能够复现你说的问题

- 原因是  
  - `type(self.scale) == <class 'str'>` 也就是yml传进来的None是str

- yml语法中None  对应 ` `, `null`, `~`

- 参考下边配置
```
  # qk_scale: None
  qk_scale: 
  # qk_scale: null
  # qk_scale: ~

```

**Comment by lyuwenyu** [comment]
@Darki-luo 
另外辛苦改一下issue的名字啊 -.-  方便其他人遇到同样问题时候 找到相关的讨论

**Comment by Darki-luo** [comment]
> @Darki-luo
> 另外辛苦改一下issue的名字啊 -.- 方便其他人遇到同样问题时候 找到相关的讨论

好的
