### ISSUE TITLE
paddleDetection训练时，显存有占用，但是浮点计算一直是0%，而且训练速度很慢

### ISSUE THREAD

**Issue by GlennLoveZhen0124** [PaddlePaddle/PaddleDetection#3156]
请问这个问题怎么解决

**Comment by lyuwenyu** [comment]
1. 查看一下是哪些进程占用GPU资源
> fuser -v /dev/nvidia* 

2. 建议kill掉占用资源的程序 重新起一下训练过程  另外make-sure是GPU训练
