### ISSUE TITLE
保存模型用于预测

### ISSUE THREAD

**Issue by qjing666** [PaddlePaddle/PaddleDetection#3159]
请问训练PaddleDetection模型时使用 save_inference_model保存了模型后，要怎么用这个模型来做预测呢？有相关教程的链接么？

**Comment by lyuwenyu** [comment]
参考下边的脚本
- https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/python

```
python deploy/python/infer.py --model_dir=./inference/yolov3_mobilenet_v1_roadsign --image_file=./demo/road554.png --use_gpu=True
```
