### ISSUE TITLE
ppyolo tensorRT trt_fp16推理相比fluid模式未加速，yolov3加速明显，

### ISSUE THREAD

**Issue by Williamlizl** [PaddlePaddle/PaddleDetection#3162]

**Comment by lyuwenyu** [comment]
- ppyolo 有部分dcn模块不支持trt，会导致yolov3速度提升比ppyolo明显

- 具体trt对比参考benchmark
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/BENCHMARK_INFER.md

**Comment by liuhuiCNN** [comment]
请您确认以下几点：（1）硬件是否支持trt16；（2）ppyolo 和 yolov3测试命令是否一致？
如上回复，您可以参考下 ppdet benchmark： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/BENCHMARK_INFER.md
