### ISSUE TITLE
yaml.constructor.ConstructorError

### ISSUE THREAD

**Issue by ayicherry** [PaddlePaddle/PaddleDetection#3163]
我自定义了一个数据集，继承DetDataSet，也进行了注册和序列化，然后在windows环境下，用pycharm训练自己的数据没有问题。但是在linux端，我在Paddle根目录下，通过python tools/train.py 进行训练的时候，会出现无法解析我定义的数据集的错误yaml.constructor.ConstructorError: could not determine a constructor for the tag '!JsonDataSet'。
       怀疑是不是linux中还需要设置路径什么的？不知道有没有小伙伴知道怎么操作，求指导，谢谢。

**Comment by lyuwenyu** [comment]
建议check一下数据路径对不  
查考一下 
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/datasets/coco_detection.yml

另外数据软连或者放到 `PaddleDetection/dataset`下面

**Comment by ayicherry** [comment]
> 建议check一下数据路径对不

我检查过了，相对路径和绝对路径我都试过，还是报同样的错。而且如果是数据集路径问题，应该会报类似什么文件不存在这种错误吧，这个yaml的错误感觉是不是import的时候哪个路径有问题，导致这个DataSet类无法实例化？

**Comment by lyuwenyu** [comment]
Windows直接可以用  linux不可以用就很奇怪 -.-   
方便贴个代码啥的吗

**Comment by ayicherry** [comment]
> Windows直接可以用 linux不可以用就很奇怪 -.-
> 方便贴个代码啥的吗

其实代码端改动也不多，就是自己创建了一个数据集的类，大致如下：
@register
@serializable
class JsonDataSet(DetDataset):
    def __init__(self,
                 dataset_dir,
                 image_dir=None,
                 anno_path=None,
                 data_fields=None,
                 sample_num=-1,
                 label_list=None):
        super(JsonDataSet, self).__init__(dataset_dir, image_dir, anno_path,
                                          data_fields, sample_num)
        self.label_list = label_list
        self.roidbs = None
        self.cname2cid = None

    @staticmethod
    def parse_json(json_file):
        with open(json_file, 'r') as fid:
            json_obj = json.load(fid)
            image_info_list = list()
            for index, image_instance in enumerate(json_obj['image_instance']):
                defect_list = []
                for defect_index in range(image_instance['instance_num']):
                    defect = image_instance['defects'][defect_index]
                    defect_list.append(defect)
                image_path = image_instance['image_path']
                image_width = image_instance['width']
                image_height = image_instance['height']
                result_dict = {'im_file': image_path, 'im_id': index, 'h': image_height, 'w': image_width, 'defects': defect_list}
                image_info_list.append(result_dict)
            class_dict = json_obj['class_order']
        return image_info_list, class_dict

    def parse_dataset(self):
        json_path = os.path.join(self.dataset_dir, self.anno_path)
        image_info_list, class_dict = self.parse_json(json_path)
        count = 0
        records = list()
        for each_image in image_info_list:
            gt_bbox = list()
            gt_class = list()
            gt_score = list()
            difficult = list()
            for defect_info in each_image['defects']:
                x1 = float(defect_info['x1'])
                y1 = float(defect_info['y1'])
                x2 = float(defect_info['x2'])
                y2 = float(defect_info['y2'])
                if x2 > x1 and y2 > y1:
                    gt_bbox.append([x1, y1, x2, y2])
                    gt_class.append([defect_info['class_id']])
                    gt_score.append([1.0])
                    difficult.append([0])
                else:
                    print("some label is wrong in %s" % each_image['im_file'])
                    assert False
            gt_bbox = np.array(gt_bbox).astype('float32')
            gt_class = np.array(gt_class).astype('int32')
            gt_score = np.array(gt_score).astype('float32')
            difficult = np.array(difficult).astype('int32')
            json_rec = {'im_file': each_image['im_file'], 'im_id': count, 'h': int(each_image['h']),
                        'w': int(each_image['w'])} if 'image' in self.data_fields else {}
            gt_rec = {'gt_class': gt_class, 'gt_score': gt_score, 'gt_bbox': gt_bbox, 'difficult': difficult}
            for key, value in gt_rec.items():
                if key in self.data_fields:
                    json_rec[key] = value
            if len(defect_info) != 0:
                records.append(json_rec)
            count += 1
            if 0 < self.sample_num <= count:
                break
        assert len(records) > 0, "Not find any recors in %s" % json_path
        self.roidbs, self.cname2cid = records, class_dict

    def get_label_list(self):
        return os.path.join(self.dataset_dir, self.label_list)
然后就是在yaml中通!JsonDataSet进行实例化的时候报错，但是在windows中可以使用。
       同时还发现了一个比较奇怪的问题，就是代码自带的有个voc.py中定义了VOCDataSet，我把数据弄成VOC的格式，然后yaml中用这个VOCDataSet训练没有问题，但是我在voc.py中把VOCDataSet这个类的名字改掉，比如叫做TestDataSet，在yaml中用!TestDataSet实例化的时候就会报上面一样的那种错误。我搜索了整个工程，VOCDataSet只有在voc.py中定义了这个类，其他地方好像没有进行绑定什么的，不清楚为什么换个名字就不可以了。
       以上都是在linux端用命令行运行会出现的错误，在windows端用pycharm运行train.py的时候都是可以正常用的。

**Comment by lyuwenyu** [comment]
上边的两个问题在Linux机器上测试了一下 

1.  新增加数据集  
一般增加数据需要更改下边几个文件 简单测试了一下没有出现问题 可以参考看一下修改的文件
https://github.com/lyuwenyu/PaddleDetection/blob/test_dataset_create_v1/test_dataset.py
```
configs/datasets/testjson.yml 
configs/testdata/
ppdet/data/source/testjson.py 
test_dataset.py
``` 

2. 修改VOC名字问题
https://github.com/lyuwenyu/PaddleDetection/blob/test_dataset_create_v1/ppdet/data/source/voc.py
https://github.com/lyuwenyu/PaddleDetection/blob/test_dataset_create_v1/test_dataset.py
在Linux下同样没有出现你描述的问题

```
dataset/voc
<ppdet.data.source.testjson.JsonDataSet object at 0x7f5c22452820>
<ppdet.data.source.voc.VOCDataSetX object at 0x7f5c240b7280>
```

3. 建议
    - 检查一下格式问题 <linux 和 windows不match的地方>  比如 \tab  \whitespace  \file-encoding等
    - **新增的py文件** 需要在 ` __init__.py`中`import`一下  让模块注册（register）起作用

**Comment by ayicherry** [comment]
> 上边的两个问题在Linux机器上测试了一下
> 
> 1. 新增加数据集
>    一般增加数据需要更改下边几个文件 简单测试了一下没有出现问题 可以参考看一下修改的文件
>    https://github.com/lyuwenyu/PaddleDetection/blob/test_dataset_create_v1/test_dataset.py
> 
> ```
> configs/datasets/testjson.yml 
> configs/testdata/
> ppdet/data/source/testjson.py 
> test_dataset.py
> ```
> 
> 1. 修改VOC名字问题
>    https://github.com/lyuwenyu/PaddleDetection/blob/test_dataset_create_v1/ppdet/data/source/voc.py
>    https://github.com/lyuwenyu/PaddleDetection/blob/test_dataset_create_v1/test_dataset.py
>    在Linux下同样没有出现你描述的问题
> 
> ```
> dataset/voc
> <ppdet.data.source.testjson.JsonDataSet object at 0x7f5c22452820>
> <ppdet.data.source.voc.VOCDataSetX object at 0x7f5c240b7280>
> ```
> 
> 1. 建议
>    
>    * 检查一下格式问题 <linux 和 windows不match的地方>  比如 \tab  \whitespace  \file-encoding等
>    * **新增的py文件** 需要在 ` __init__.py`中`import`一下  让模块注册（register）起作用

你好，我找到问题点了，已经可以正常使用自定义数据接口了。谢谢帮忙分析和验证，十分感谢。
