### ISSUE TITLE
如果数据集的annotation只有bbox，没有segment，mask信息，是不是就不能用maskrcnn了？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleDetection#3168]
inputs_def:    
fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_mask']

相比其他模型会多一个gt_mask

这种情况下，不能默认用bbox当做mask吗？

**Comment by nemonameless** [comment]
相比于改检测库代码，改数据集标注制作可能更方便实用。在数据集COCO格式的json标注制作时，假设每个框annotation的bbox字段为[x0, y0, w, h]，则新加segmentation字段为[[x0, y0, x0+w, y0+h]]，检测库代码应该不用修改就可以训练Mask R-CNN。

**Comment by bbbxixixixi** [comment]
试了下根据bbox生成segment（四个点），也运行不了
配置文件和报错信息如下
paddle master， aistudio 2.1

architecture: CascadeMaskRCNN
max_iters: 300000
snapshot_iter: 10
use_gpu: true
log_iter: 20
save_dir: output
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/SENet154_vd_caffe_pretrained.tar
weights: output/cascade_mask_rcnn_dcn_se154_vd_fpn_gn_s1x/model_final
metric: COCO
num_classes: 9

CascadeMaskRCNN:
  backbone: SENet
  fpn: FPN
  rpn_head: FPNRPNHead
  roi_extractor: FPNRoIAlign
  bbox_head: CascadeBBoxHead
  bbox_assigner: CascadeBBoxAssigner
  mask_assigner: MaskAssigner
  mask_head: MaskHead

SENet:
  depth: 152
  feature_maps: [2, 3, 4, 5]
  freeze_at: 2
  group_width: 4
  groups: 64
  norm_type: bn
  freeze_norm: True
  variant: d
  dcn_v2_stages: [3, 4, 5]
  std_senet: True

FPN:
  max_level: 6
  min_level: 2
  num_chan: 256
  spatial_scale: [0.03125, 0.0625, 0.125, 0.25]
  freeze_norm: False
  norm_type: gn

FPNRPNHead:
  anchor_generator:
    aspect_ratios: [0.5, 1.0, 2., 3., 3.5, 4., 5.]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 32
  max_level: 6
  min_level: 2
  num_chan: 256
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 2000
    post_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 1000
    post_nms_top_n: 1000

FPNRoIAlign:
  canconical_level: 4
  canonical_size: 224
  max_level: 5
  min_level: 2
  box_resolution: 7
  sampling_ratio: 2
  mask_resolution: 14

MaskHead:
  dilation: 1
  conv_dim: 256
  num_convs: 4
  resolution: 28
  norm_type: gn

CascadeBBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [10, 20, 30]
  bg_thresh_hi: [0.5, 0.6, 0.7]
  bg_thresh_lo: [0.0, 0.0, 0.0]
  fg_fraction: 0.25
  fg_thresh: [0.5, 0.6, 0.7]

MaskAssigner:
  resolution: 28

CascadeBBoxHead:
  head: CascadeXConvNormHead
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    score_threshold: 0.05

CascadeXConvNormHead:
  norm_type: gn

LearningRate:
  base_lr: 0.00125
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [240000, 280000]
  - !LinearWarmup
    start_factor: 0.01
    steps: 2000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

TrainReader:
  # batch size per device
  batch_size: 1
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_mask']
  dataset:
    !COCODataSet
    image_dir: train/images
    anno_path: split_anno/train_f5_4.json
    dataset_dir: /home/aistudio/data
  sample_transforms:
  - !DecodeImage
    to_rgb: false
  - !RandomFlipImage
    is_mask_flip: true
    is_normalized: false
    prob: 0.5
  - !NormalizeImage
    is_channel_first: false
    is_scale: False
    mean:
    - 102.9801
    - 115.9465
    - 122.7717
    std:
    - 1.0
    - 1.0
    - 1.0
  - !ResizeImage
    interp: 1
    target_size:
    - 416
    - 448
    - 480
    - 512
    - 544
    - 576
    - 608
    - 640
    - 672
    - 704
    - 736
    - 768
    - 800
    - 832
    - 864
    - 896
    - 928
    - 960
    - 992
    - 1024
    - 1056
    - 1088
    - 1120
    - 1152
    - 1184
    - 1216
    - 1248
    - 1280
    - 1312
    - 1344
    - 1376
    - 1408
    max_size: 2400
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  worker_num: 1
  shuffle: true

EvalReader:
  batch_size: 1
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  dataset:
    !COCODataSet
    image_dir: train/images
    anno_path: split_anno/eval_f5_4.json
    dataset_dir: /home/aistudio/data
  sample_transforms:
  - !DecodeImage
    to_rgb: False
  - !NormalizeImage
    is_channel_first: false
    is_scale: False
    mean:
    - 102.9801
    - 115.9465
    - 122.7717
    std:
    - 1.0
    - 1.0
    - 1.0
  - !ResizeImage
    interp: 1
    target_size:
    - 800
    max_size: 2400
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  worker_num: 1
  drop_empty: false

TestReader:
  batch_size: 1
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  dataset:
    !ImageFolder
    anno_path: /home/aistudio/test_annn.json
  sample_transforms:
  - !DecodeImage
    to_rgb: False
  - !NormalizeImage
    is_channel_first: false
    is_scale: False
    mean:
    - 102.9801
    - 115.9465
    - 122.7717
    std:
    - 1.0
    - 1.0
    - 1.0
  - !ResizeImage
    interp: 1
    max_size: 2400
    target_size: 1248
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  worker_num: 1

**Comment by bbbxixixixi** [comment]
> 相比于改检测库代码，改数据集标注制作可能更方便实用。在数据集COCO格式的json标注制作时，假设每个框annotation的bbox字段为[x0, y0, w, h]，则新加segmentation字段为[[x0, y0, x0+w, y0+h]]，检测库代码应该不用修改就可以训练Mask R-CNN。

我照着这方法做了，能训练和评估，但是在生成结果的时候报异常了

Evaluate annotation type *segm*
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection-master/tools/train.py", line 405, in <module>
    main()
  File "/home/aistudio/PaddleDetection-master/tools/train.py", line 326, in main
    cfg['EvalReader']['dataset'])
  File "/home/aistudio/PaddleDetection-master/ppdet/utils/eval_utils.py", line 248, in eval_results
    results, anno_file, output, resolution, save_only=save_only)
  File "/home/aistudio/PaddleDetection-master/ppdet/utils/coco_eval.py", line 168, in mask_eval
    cocoapi_eval(outfile, 'segm', coco_gt=coco_gt)
  File "/home/aistudio/PaddleDetection-master/ppdet/utils/coco_eval.py", line 245, in cocoapi_eval
    coco_eval.evaluate()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 140, in evaluate
    self._prepare()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 104, in _prepare
    _toMask(gts, self.cocoGt)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 92, in _toMask
    rle = coco.annToRLE(ann)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pycocotools/coco.py", line 426, in annToRLE
    rles = maskUtils.frPyObjects(segm, h, w)
  File "pycocotools/_mask.pyx", line 293, in pycocotools._mask.frPyObjects
TypeError: Argument 'bb' has incorrect type (expected numpy.ndarray, got list)
terminate called without an active exception


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1622008774 (unix time) try "date -d @1622008774" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800000c6b) received by PID 3179 (TID 0x7fb03fcb3700) from PID 3179 ***]

Aborted (core dumped)

**Comment by bbbxixixixi** [comment]
> 相比于改检测库代码，改数据集标注制作可能更方便实用。在数据集COCO格式的json标注制作时，假设每个框annotation的bbox字段为[x0, y0, w, h]，则新加segmentation字段为[[x0, y0, x0+w, y0+h]]，检测库代码应该不用修改就可以训练Mask R-CNN。

我看别的实例检测的segment是[x,y,x,y,x,y.....x,y]这样的格式，按照这种生成4个点，又无法运行起来

**Comment by bbbxixixixi** [comment]
> > 相比于改检测库代码，改数据集标注制作可能更方便实用。在数据集COCO格式的json标注制作时，假设每个框annotation的bbox字段为[x0, y0, w, h]，则新加segmentation字段为[[x0, y0, x0+w, y0+h]]，检测库代码应该不用修改就可以训练Mask R-CNN。
> 
> 我看别的实例检测的segment是[x,y,x,y,x,y.....x,y]这样的格式，按照这种生成4个点，又无法运行起来

改成segment;[[x,y,x,y,x,y]]这样的就行了，里面是个list，然后长度不能等于4，cocoapi里面的一个坑
