### ISSUE TITLE
1.7.0框架 tools/eval.py  & infer.py 接口未更新吗？

### ISSUE THREAD

**Issue by pele228** [PaddlePaddle/PaddleDetection#317]
1.7.0框架的eval.py 和 infer.py 接口。 train结束后调用eval和infer，会报错
ValueError: Model pretrain path output/yolov3_r34_voc/model_final does not exists.
目前生成的模型文件不是1.6版本的文件夹形式，是三个.pd*文件。

**Comment by willthefrog** [comment]
都是使用的是同样的接口，能否提供下具体执行命令以及output下的文件列表？

**Comment by pele228** [comment]
按照文档来的，数据集用的教程里的fruit，
训练python tools/train.py -c configs/yolov3_r34_voc_fruit.yml
训练得到的output模型列表
-rw-r--r-- 1 aistudio aistudio   2039224 Mar 10 19:10 40000.pdmodel
-rw-r--r-- 1 aistudio aistudio 252091563 Mar 10 19:10 40000.pdopt
-rw-r--r-- 1 aistudio aistudio 253423813 Mar 10 19:10 40000.pdparams
-rw-r--r-- 1 aistudio aistudio   2039224 Mar 10 19:45 50000.pdmodel
-rw-r--r-- 1 aistudio aistudio 252174593 Mar 10 19:45 50000.pdopt
-rw-r--r-- 1 aistudio aistudio 253435217 Mar 10 19:45 50000.pdparams
-rw-r--r-- 1 aistudio aistudio   2039224 Mar 10 20:20 60000.pdmodel
-rw-r--r-- 1 aistudio aistudio 252116394 Mar 10 20:20 60000.pdopt
-rw-r--r-- 1 aistudio aistudio 253435594 Mar 10 20:20 60000.pdparams
-rw-r--r-- 1 aistudio aistudio   2039224 Mar 10 20:55 70000.pdmodel
-rw-r--r-- 1 aistudio aistudio 252142980 Mar 10 20:55 70000.pdopt
-rw-r--r-- 1 aistudio aistudio 253438572 Mar 10 20:55 70000.pdparams
-rw-r--r-- 1 aistudio aistudio   2039224 Mar 10 21:30 80000.pdmodel
-rw-r--r-- 1 aistudio aistudio 251934786 Mar 10 21:30 80000.pdopt
-rw-r--r-- 1 aistudio aistudio 253434754 Mar 10 21:30 80000.pdparams
-rw-r--r-- 1 aistudio aistudio   2039224 Mar 10 22:04 90000.pdmodel
-rw-r--r-- 1 aistudio aistudio 252079639 Mar 10 22:04 90000.pdopt
-rw-r--r-- 1 aistudio aistudio 253440806 Mar 10 22:04 90000.pdparams
-rw-r--r-- 1 aistudio aistudio   2039224 Mar 11 07:00 model_final.pdmodel
-rw-r--r-- 1 aistudio aistudio 252193247 Mar 11 07:00 model_final.pdopt
-rw-r--r-- 1 aistudio aistudio 253422130 Mar 11 07:00 model_final.pdparams

然后  python tools/eval.py -c configs/yolov3_r34_voc_fruit.yml

**Comment by willthefrog** [comment]
配置文件不是默认带的吧？确定路径是正确的？ `ls output/yolov3_r34_voc/model_final*`显示是什么？  `yolov3_r34_voc`还是`yolov3_r34_voc_fruit`?

**Comment by willthefrog** [comment]
`train.py`保存路径是根据配置文件名字来的，如果是`yolov3_r34_voc_fruit.yml`需要相应的修改`weight`字段的路径，不然对应不上的。

**Comment by pele228** [comment]
谢谢，确实路径有些问题
