### ISSUE TITLE
服务器部署debug模式

### ISSUE THREAD

**Issue by shishi369** [PaddlePaddle/PaddleDetection#3171]
请问windows的预测库fluid_inference_install_dir支持debug调试模式吗？
具体地，检测模型进行服务器c++部署时，使用debug生成会报错，与paddle中libpaddle_fluid.lib相关的错误。

**Comment by liuhuiCNN** [comment]
(1) windows的预测库fluid_inference_install_dir是release版本的，不支持debug，若需要debug，您可以自己编译paddle。

**Comment by shishi369** [comment]
请问，有没有预测库fluid_inference_install_dir的编译教程呢？

**Comment by liuhuiCNN** [comment]
> 请问，有没有预测库fluid_inference_install_dir的编译教程呢？

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/windows-compile.html

**Comment by shishi369** [comment]
> 
> 
> > 请问，有没有预测库fluid_inference_install_dir的编译教程呢？
> 
> https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/windows-compile.html

好的，谢谢
