### ISSUE TITLE
paddledetection安装问题

### ISSUE THREAD

**Issue by AN-ZE** [PaddlePaddle/PaddleDetection#3176]
win10 or linux
2.0-rc 及以前的版本，我习惯是修改源码，满足自己的训练要求进行训练的。
2.1现在发现，训练工程代码中的调用的是包？
例如：
```
from ppdet.utils.download import create_voc_list
```
调用的不是当前目录文件下的 ppdet.utils.download.py
而是paddledet包中的。
应该怎么修改，或者设置。

是不是卸载了paddledet就可以。以前旧版本是没有安装过的。

**Comment by AN-ZE** [comment]
已解决，卸载了之后确实正常了。
只是不太明白这样设置的目的是什么

**Comment by AN-ZE** [comment]
已解决，卸载了之后确实正常了。
只是不太明白这样设置的目的是什么

**Comment by heavengate** [comment]
如果想修改源码的话可以`pip uninstall paddledet`在PaddleDetection下
```
export PYTHONPATH=`pwd`:$PYTHONPATH
```
这样可以直接引用改动的文件

另外也可以修改完之后，`python setup.py install `重新安装一下也可以~
