### ISSUE TITLE
YOLOV3 训练问题

### ISSUE THREAD

**Issue by zjutlzt** [PaddlePaddle/PaddleDetection#318]
在制作yolov3 数据集的时候，COCO的json格式  要是想加入很多没有gt的数据、
因为这些图片没有框所以是 不用加到['annotations'] 里面
只是在json['images']  里面一直加图片就可以了吗，训练的时候就会加入吗

**Comment by willthefrog** [comment]
coco数据集加载的时候会过滤掉空的sample，所以只加图片是没有作用的。

**Comment by zjutlzt** [comment]
那请问   yolov3 要增加 没有gt的数据是要怎么加呢

**Comment by willthefrog** [comment]
配置 reader的 `drop_empty`参数，参见[这里](https://github.com/paddlepaddle/PaddleDetection/blob/master/ppdet/data/reader.py#L166)
