### ISSUE TITLE
多目标跟踪推理，加载后报killed

### ISSUE THREAD

**Issue by yunchangxiaoguan** [PaddlePaddle/PaddleDetection#3182]
CUDA_VISIBLE_DEVICES=0 python3 tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=models/fairmot_dla34_30e_1088x608.pdparams --video_file=docs/abc.mp4 --save_videos
W0527 11:07:29.327987 13446 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 10.2, Runtime API Version: 10.2
W0527 11:07:29.623159 13446 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[05/27 11:07:35] ppdet.utils.checkpoint INFO: Finish resuming model weights: models/fairmot_dla34_30e_1088x608.pdparams
[05/27 11:07:35] ppdet.engine.tracker INFO: Starting tracking docs/abc.mp4
[05/27 11:07:35] ppdet.data.source.mot INFO: Length of the video: 980 frames
Killed
请问要怎么解决

**Comment by nemonameless** [comment]
可以给下机器环境？看起来像是内存不足，但是980帧也不算多

**Comment by yunchangxiaoguan** [comment]
> 可以给下机器环境？看起来像是内存不足，但是980帧也不算多

![image](https://user-images.githubusercontent.com/47582901/119926212-819f2180-bfa9-11eb-91c2-ec3cc2a50be2.png)
![image](https://user-images.githubusercontent.com/47582901/119926403-f1ada780-bfa9-11eb-8980-82be669eeca3.png)
![image](https://user-images.githubusercontent.com/47582901/119926476-16098400-bfaa-11eb-8380-86ecc7b1ec87.png)

云环境，之前跑过一个很小的视频倒是能跑通，这个占用资源很大嘛，推荐什么配置阿，感谢大佬

**Comment by nemonameless** [comment]
@yunchangxiaoguan 已经换decord来读取视频，应该比opencv更加高效了

**Comment by tianrking** [comment]
同样 被kill  百度飞奖 至尊版环境

**Comment by nemonameless** [comment]
目前使用视频infer时会提前抽成图片帧，不会出现此问题。支持自己设置frame_rate。
CUDA_VISIBLE_DEVICES=0 python3.7 tools/infer_mot.py -c ${config} -o weights=model_final.pdparams --video_file=test_demo.mp4 --frame_rate=20 --save_videos
