### ISSUE TITLE
请问该如何加载PaddleDetection模型进行finetune

### ISSUE THREAD

**Issue by CandyCook** [PaddlePaddle/PaddleDetection#3183]
尝试过使用PaddleHub进行finetune，但没有成功，有什么新的方法吗

**Comment by heavengate** [comment]
训练的时候使用`-o pretrain_weights=xxx`指定需要加载的finetune权重即可，这里的教程里面包含`Fine-tune训练`的介绍
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/GETTING_STARTED_cn.md
我们发布的权重可以在MODEL ZOO里获取https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/MODEL_ZOO_cn.md
你这边失败是报什么错了么

**Comment by CandyCook** [comment]
我想通过paddle框架查看fairmot的网络结构，并且进行修改，固定一些网络结构进行调整，有什么办法可以固定网络结构，进行微调呢？期待回答ing

**Comment by heavengate** [comment]
是指固定一部分的网络不训练，只训练其余的网络？那个固定结构的输出特征图`x.stop_gradient=True`就可以了
