### ISSUE TITLE
【代码问题反馈】单图像数据增强算子代码变量名称不一致

### ISSUE THREAD

**Issue by a2824256** [PaddlePaddle/PaddleDetection#3187]
PaddleDetection版本: 2.1
文件路径：ppdet/data/transform/operators.py

210行IDE提示异常，__init__函数参数higher未被使用
![image](https://user-images.githubusercontent.com/7108023/119806028-6a622480-bf14-11eb-9189-157c168b245c.png)
根据__init__函数参数higher和230行self.higher
`
target_area = random.uniform(self.lower, self.higher) * area
`
应该将210行下面代码，统一名称为higher
`
self.heigher=heigher
`
改为
`
self.higher=higher
`
解决变量名称不一致导致的问题

**Comment by heavengate** [comment]
好的，感谢指出，我们修复一下~
