### ISSUE TITLE
ppdet 增加训练背景类图片 报错

### ISSUE THREAD

**Issue by carol510** [PaddlePaddle/PaddleDetection#319]
增加了非检测类图片进行训练，drop_empty = false 报错。
![image](https://user-images.githubusercontent.com/22268236/76382382-8ae7a280-6393-11ea-9566-f0eb7228e158.png)

**Comment by willthefrog** [comment]
@qingqing01  could you take a look?

**Comment by qingqing01** [comment]
@carol510 除了YOLOv3模型外，其他模型空bbox的图片作为输入，需要设置drop_empty=True。

**Comment by jesen8** [comment]
@qingqing01  release/2.0-beta 训练时，使用coco格式数据，训练ppyolo模型
 {
    "images": [],
    "categories": [],
    "annotations": []
}
只在images里面添加了图片信息，没有在annotations里面添加对应的框信息， 因为ie图片里面没有目标，训练时，查看加载coco数据集的代码部分，空白图片直接就被过滤了
https://github.com/PaddlePaddle/PaddleDetection/blob/59d4eef6dadf47b7405765200c44aaa9f2b3aa5a/ppdet/data/source/coco.py#L148
是我理解错了吗还是不支持空白图片，
谢谢回答
