### ISSUE TITLE
SOLOV2训练config_solov2 num_class很小时，训练不收敛

### ISSUE THREAD

**Issue by gpsherry** [PaddlePaddle/PaddleDetection#3191]
https://github.com/PaddlePaddle/PaddleDetection/blob/effbad5db4f1a046dd63cdf14ae49412ba4a836f/ppdet/modeling/anchor_heads/solov2_head.py#L370
cate_score_idx =paddle.add(inds[:, 0] * 80, cate_labels)应该改成下面的写法
cate_score_idx = paddle.add(inds[:, 0] * self.num_classes, cate_labels)
改完后类别数量较小时训练一样收敛

**Comment by yghstill** [comment]
@gpsherry 感谢反馈，已修复。
