### ISSUE TITLE
调用finetune时出现问题

### ISSUE THREAD

**Issue by CandyCook** [PaddlePaddle/PaddleDetection#3192]
!python -m paddle.distributed.launch --gpus 0 PaddleDetection-release-2.1/tools/train.py \
    -c PaddleDetection-release-2.1/configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml \
    -o pretrain_weights=https://paddledet.bj.bcebos.com/models/pretrained/fairmot_dla34_crowdhuman_pretrained.pdparams

[log.zip](https://github.com/PaddlePaddle/PaddleDetection/files/6557734/log.zip)

-----------  Configuration Arguments -----------
gpus: 0
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
run_mode: None
server_num: None
servers: 
training_script: PaddleDetection-release-2.1/tools/train.py
training_script_args: ['-c', 'PaddleDetection-release-2.1/configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml', '-o', 'pretrain_weights=https://paddledet.bj.bcebos.com/models/pretrained/fairmot_dla34_crowdhuman_pretrained.pdparams']
worker_num: None
workers: 
------------------------------------------------
WARNING 2021-05-28 10:07:03,812 launch.py:357] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2021-05-28 10:07:03,814 launch_utils.py:510] Local start 1 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:55681               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:55681               |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                        0                      |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2021-05-28 10:07:03,815 launch_utils.py:514] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:1583 idx:0
INFO 2021-05-28 10:07:12,857 launch_utils.py:327] terminate all the procs
ERROR 2021-05-28 10:07:12,858 launch_utils.py:584] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-05-28 10:07:15,858 launch_utils.py:327] terminate all the procs

**Comment by jerrywgz** [comment]
如果是单卡训练，可以使用```CUDA_VISIBLE_DEVICES=0 python tools/train.py
-c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml
-o pretrain_weights=https://paddledet.bj.bcebos.com/models/pretrained/fairmot_dla34_crowdhuman_pretrained.pdparams```
这样可以看到具体的报错信息，或者在```log/workerlog.0```中也可以查看
