### ISSUE TITLE
关于 coco 数据集评估

### ISSUE THREAD

**Issue by FL77N** [PaddlePaddle/PaddleDetection#3197]
您好，请问在 ppdet 的 coco eval 里面，假如一张图的 gt 有 20 个，我预测并经过后处理的最终结果有 30 个，最后 eval 的时候会选出分数在 top 20 的框与 gt 进行 eval，其余框不会产生影响吗？

**Comment by jerrywgz** [comment]
其余的框也是会加入计算的

**Comment by FL77N** [comment]
> 其余的框也是会加入计算的

那会影响最后的 ap 吗？如果 gt 有 20 个，我输入了 100 个，但是这 100 个里面有 20 个刚好和 gt match，其他的框会影响 ap 吗

**Comment by FL77N** [comment]
> 其余的框也是会加入计算的

还请教您一个问题，在 ppdet coco eval 时未转为 coco 类别前，class_id 是从 0 到 80 还是 1 到 81 呢（左闭右开）

**Comment by jerrywgz** [comment]
通常来说会有一定影响，但是如果这个预测出来match的20个框的分数是最大的20个时，影响不大。
在网络中class_id是0-80的，其中80是背景类
