### ISSUE TITLE
libra_rcnn在自定义数据集上报数据尺寸不匹配错误

### ISSUE THREAD

**Issue by A1exy** [PaddlePaddle/PaddleDetection#320]
PaddleDetection版本为0.2，paddle版本为1.7
1、在coco官方数据集上训练测试流程均OK
2、在自定义coco格式数据集上，检测的类别为3。
修改配置文件如下：
![image](https://user-images.githubusercontent.com/7035538/76394762-f855fc00-63b0-11ea-9cad-a42e680f8a8e.png)

开始训练报错信息如下：
![image](https://user-images.githubusercontent.com/7035538/76394664-d9f00080-63b0-11ea-9c50-3c4b9eeaffce.png)

数据尺寸不匹配，一边还是coco默认的81类，请问是哪里还需要修改这个类别数吗

**Comment by littletomatodonkey** [comment]
在LibraBBoxAssigner字段中添加类别数的参数即可~
![image](https://user-images.githubusercontent.com/14270174/76396810-dd858680-63b4-11ea-8dd5-9937fd4a6932.png)

**Comment by A1exy** [comment]
已解决，多谢
