### ISSUE TITLE
voc eval problem

### ISSUE THREAD

**Issue by blank-97** [PaddlePaddle/PaddleDetection#3202]
eval的时候只会有显示迭代次数，然后并不会输出eval结果。

**Comment by yghstill** [comment]
@blank-97 在eval结束时应该会输出mAP(0.5)的数值，没有输出的话方便发下截图吗

**Comment by blank-97** [comment]
@yghstill 
![QQ图片20210530143921](https://user-images.githubusercontent.com/69951071/120094753-dc28b100-c154-11eb-87e8-9de09a04f7b6.png)

**Comment by yghstill** [comment]
@blank-97 我本地测试voc eval是能打印mAP的，你在计算mAP的位置加上debug的调试信息看是否能打印出来再试下：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/metrics/metrics.py#L273

**Comment by blank-97** [comment]
@yghstill 我有在你给的位置直接加print语句，但是并不能打印出来，我还有在这个位置加调试语句，也没有打印出来：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/engine/trainer.py#L386，感觉就是没有进入evaluate阶段。

**Comment by yghstill** [comment]
@blank-97 没进evaluate的话不会打印`Eval iter`的信息，eval时evaluate函数是一定会执行的，可能和环境有关，你在cmd中执行看能否打印？https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/tools/eval.py#L105

**Comment by yghstill** [comment]
@blank-97 使用logger.info调试再试下呢？print可能由于多线程的影响打印不出。
