### ISSUE TITLE
在jetson NX平台上，哪个检测模型最佳

### ISSUE THREAD

**Issue by lvrh2018** [PaddlePaddle/PaddleDetection#3203]
综合速度和精度，用哪个检测模型最好，最高能达多少帧/秒？

**Comment by yghstill** [comment]
@lvrh2018 推荐你使用ppyolo-tiny模型，是经过优化的轻量级模型：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/configs/ppyolo#pp-yolo-tiny
