### ISSUE TITLE
VehicleDetection车辆和行人检测使用文档有误

### ISSUE THREAD

**Issue by hengai** [PaddlePaddle/PaddleDetection#321]
contrib文件夹里的README.md文件有误，没有描述车辆和行人的类别文件vehicle.json 、pedestrian.json怎么用，按README.md文件的操作会导致输出的结果类别混乱，能补充完善车辆和行人检测的使用文档吗？

**Comment by willthefrog** [comment]
@FlyingQianMM can you take look at this issue?

**Comment by FlyingQianMM** [comment]
@hengai 
step1. 对照yolo3_darknet.yml修改contrib文件夹里的README.md文件中提到的参数。
step2. 把yolov3_reader.yml中TestReader的anno_path替换成vehicle.json、pedestrian.json的路径。vehicle.json、pedestrian.json只提供了类别信息。

**Comment by FlyingQianMM** [comment]
感谢指出。已提pr修复（pr #323）
