### ISSUE TITLE
我想计算模型在测试集上的精度，有没有方法

### ISSUE THREAD

**Issue by luqihui** [PaddlePaddle/PaddleDetection#3210]
计算模型在测试集上的精度，如ap,map.

**Comment by liuhuiCNN** [comment]
测试集有标签吗？有标签的话，您可以试下， `python tools/eval.py`

**Comment by luqihui** [comment]
> 测试集有标签吗？有标签的话，您可以试下， `python tools/eval.py`

好的，有标签的，我去试试。
