### ISSUE TITLE
用pp-yolo-v2训练自己的数据集出错

### ISSUE THREAD

**Issue by agumon2020** [PaddlePaddle/PaddleDetection#3211]
我用pp-yolo-v2训练自己的数据集，数据集格式是coco类型，报以下错误
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)
在此错误之前还有很多这种警告
ppdet.data.source.coco WARNING: Found an invalid bbox in annotations: im_id: 560, area: 0.0 x1: 634.0, y1: 347.0, x2: 634.0, y2: 500.0.

**Comment by liuhuiCNN** [comment]
（1）警告里的信息是说该数据标签中，矩形框面积是0，标记是有问题的，请您核实一下这条数据；
（2）发生的错误在reader中，从错误提示信息中没法判断错误具体位置，建议您关闭多线程，设置worker_num: 0，减小batch_size试试。
