### ISSUE TITLE
x2coco.py转换报错

### ISSUE THREAD

**Issue by thomas-yanxin** [PaddlePaddle/PaddleDetection#3213]
在使用x2coco.py将VOC格式的数据集转COCO格式时报如下错误：
Traceback (most recent call last):
  File "x2coco.py", line 474, in <module>
    main()
  File "x2coco.py", line 360, in main
    output_file=args.voc_out_name)
  File "x2coco.py", line 274, in voc_xmls_to_cocojson
    ann = voc_get_coco_annotation(obj=obj, label2id=label2id)
  File "x2coco.py", line 233, in voc_get_coco_annotation
    assert label in label2id, "label is not in label2id."
AssertionError: label is not in label2id.

请问是什么原因，该如何解决呢？

**Comment by wangxinxin08** [comment]
这个代码好像不是最新的代码，麻烦拉一下最新的代码

**Comment by thomas-yanxin** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/tools/x2coco.py
我尝试了一下上面这个链接中的x2coco.py代码，报同样的错误。

**Comment by wangxinxin08** [comment]
可以先打印下label2id的内容确认下问题，报错信息是说当前的label不在label2id这个字典里面

**Comment by yangjiachenheihei** [comment]
我也是报这样的错误
