### ISSUE TITLE
fairmot预测视频出错

### ISSUE THREAD

**Issue by llO-Oll** [PaddlePaddle/PaddleDetection#3217]
已经检测到视频路径，还是报错
![image](https://user-images.githubusercontent.com/57003610/120140763-cc20d800-c20d-11eb-8b47-30758e0dfcef.png)

![image](https://user-images.githubusercontent.com/57003610/120139581-5451ae00-c20b-11eb-9124-82e416874693.png)

![image](https://user-images.githubusercontent.com/57003610/120139516-3dab5700-c20b-11eb-9f83-6321da7ca652.png)

**Comment by nemonameless** [comment]
请问是每个视频都预测不了吗？可以给下机器环境? 或者可以试试很短的小视频预测看能否跑通

**Comment by llO-Oll** [comment]
我测试18帧的视频还是不行，一样的错误，就是aistudio上的环境

**Comment by llO-Oll** [comment]
已解决，修改配置文件的输入尺寸

**Comment by GexLoong** [comment]
> 已解决，修改配置文件的输入尺寸

请问一下修改哪个配置文件的输入尺寸
