### ISSUE TITLE
动态图使用softnms 或者 matrixNMS

### ISSUE THREAD

**Issue by PeterJaq** [PaddlePaddle/PaddleDetection#3223]
想在动态图版本使用softnms 和 matrix nms 不知道有没有什么解决方案

**Comment by wangxinxin08** [comment]
动态图版本支持Matrix NMS，可以参考ppyolo的配置文件，soft nms目前动态图不支持，可以使用matrix nms替代

**Comment by PeterJaq** [comment]
> 动态图版本支持Matrix NMS，可以参考ppyolo的配置文件，soft nms目前动态图不支持，可以使用matrix nms替代

你好，我参照ppyolo中的matrixNMS配置了cascade rcnn 
BBoxPostProcess:
  decode:
    name: RCNNBox
    prior_box_var: [15.0, 15.0, 30.0, 30.0]
  nms:
    name: MatrixNMS
    keep_top_k: 100
    score_threshold: 0.01
    post_threshold: 0.01
    nms_top_k: -1
    background_label: -1

推理时报错 ：
ValueError: (InvalidArgument) The rank of Input(Scores) must be 3. But received rank = 2.
  [Hint: Expected score_size == 3 == true, but received score_size == 3:0 != true:1.] (at /paddle/paddle/fluid/operators/detection/matrix_nms_op.cc:41)
  [operator < matrix_nms > error]

**Comment by wangxinxin08** [comment]
目前MatrixNMS暂时不支持RCNN系列的输出，你可以使用Paddle细粒度Op组装出soft nms或者matrix nms，放在ppdet/modeling/layers.py，以供调用
