### ISSUE TITLE
mot 可以在cpu的环境中运行吗

### ISSUE THREAD

**Issue by quhaohao** [PaddlePaddle/PaddleDetection#3224]
请问 2.1版本的Mot可以cpu的环境中运行吗？

**Comment by lyuwenyu** [comment]
- 训练+预测 是可以的
- 部署现在还没有打通

**Comment by quhaohao** [comment]
> * 训练+预测 是可以的
> * 部署现在还没有打通

你说的部署指的是？ 我现在使用cpu的主机可以完成对一段视频的跟踪吗

**Comment by lyuwenyu** [comment]
> > * 训练+预测 是可以的
> > * 部署现在还没有打通
> 
> 你说的部署指的是？ 我现在使用cpu的主机可以完成对一段视频的跟踪吗

可以的 使用tools下边的infer_mot是没问题的
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/tools/infer_mot.py#L109

**Comment by quhaohao** [comment]
> er_mo
ok  非常感谢
