### ISSUE TITLE
评估时batch_size只能设置为1，否则报图像尺寸不一致。

### ISSUE THREAD

**Issue by Harry-675** [PaddlePaddle/PaddleDetection#3225]
配置文件如下：这样配置我理解应该是都会resize到（192，384），图像尺寸应该一致才对，为什么会报错？
EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [192, 384], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1

**Comment by lyuwenyu** [comment]
1. 报什么错 错误信息能否贴一下?
2. 示例配置 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/_base_/ppyolo_reader.yml#L32

**Comment by Harry-675** [comment]
@lyuwenyu 
如下图所示：是否将192，384看成了两个不同的尺寸，我是想输入大小为（192，384）
![image](https://user-images.githubusercontent.com/29157861/120314046-6582e380-c30d-11eb-8bd0-111d17dbf543.png)

**Comment by lyuwenyu** [comment]
paddle是什么版本

1. 不是两个size, 是识别成（h, w）的 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/data/transform/operators.py#L614
2. 这个建议你打印一下 出错时候 batch里的image的size

**Comment by yghstill** [comment]
@Harry-675 是voc数据集吗？config里加上这两行：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/ppyolo_r50vd_dcn_voc.yml#L19-L20
