### ISSUE TITLE
多目标跟踪只能用于跟踪行人吗

### ISSUE THREAD

**Issue by lfxx** [PaddlePaddle/PaddleDetection#3232]
1.是否支持基于目标模板的不限类别跟踪?
2.是否支持long-term tracking?

**Comment by lyuwenyu** [comment]
- 是的 不限制类别的, 但是目前只支持单类

**Comment by lfxx** [comment]
> * 是的 不限制类别的, 但是目前只支持单类

目前的多目标跟踪难点在于目标重叠或者丢失后的重识别。基于目标模板的跟踪更实用些吧，
https://github.com/visionml/pytracking  这个项目做的就是这种，不过它的long-term tracking做的不是很好。想知道百度官方会考虑实现该方向的目标跟踪算法吗？

**Comment by lyuwenyu** [comment]
> > * 是的 不限制类别的, 但是目前只支持单类
> 
> 目前的多目标跟踪难点在于目标重叠或者丢失后的重识别。基于目标模板的跟踪更实用些吧，
> https://github.com/visionml/pytracking 这个项目做的就是这种，不过它的long-term tracking做的不是很好。想知道百度官方会考虑实现该方向的目标跟踪算法吗？

- 好的 多谢建议，后期会讨论是否加入基于模板的tracker

**Comment by lfxx** [comment]
> > > * 是的 不限制类别的, 但是目前只支持单类
> > 
> > 
> > 目前的多目标跟踪难点在于目标重叠或者丢失后的重识别。基于目标模板的跟踪更实用些吧，
> > [visionml/pytracking](https://github.com/visionml/pytracking) 这个项目做的就是这种，不过它的long-term tracking做的不是很好。想知道百度官方会考虑实现该方向的目标跟踪算法吗？
> 
> * 好的 多谢建议，后期会讨论是否加入基于模板的tracker

期待项目更新!
