### ISSUE TITLE
多目标跟踪在我自己视频上测试效果很差

### ISSUE THREAD

**Issue by lfxx** [PaddlePaddle/PaddleDetection#3234]
使用命令如下：
```
CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=models/mot/fairmot_dla34_30e_1088x608.pdparams --video_file=videos/bodou_cut1.mp4  --save_videos
```
结果如下：

https://user-images.githubusercontent.com/27956643/120314658-125d6080-c30e-11eb-9a27-7c209e477c4e.mp4

是不是我用的不对，这效果也太差了;跟踪错了可以理解，检测不到人就很奇怪
附上原视频，希望官方可以测试下：

https://user-images.githubusercontent.com/27956643/120314807-33be4c80-c30e-11eb-8aae-5c7a799d367a.mp4

另外视频长一点就爆内存，希望官方可以优化下

**Comment by nemonameless** [comment]
收到建议，近期会优化。换数据集测效果是可能会变差的，毕竟数据集之间差异很大。可以试下调一些参数，例如configs/mot/fairmot/_base_/fairmot_dla34.yml里
```
JDETracker:
  conf_thres: 0.1
  tracked_thresh: 0.1
  metric_type: cosine
```
