### ISSUE TITLE
cascade rcnn模型验证出现种类不匹配问题

### ISSUE THREAD

**Issue by YangLuLu-0806** [PaddlePaddle/PaddleDetection#3235]
在训练时，我设置种类为6类或7类（加了背景类），然后验证时计算AP输出时**q6种类AP一直不显示**，如下图：

下图是label_list种类设置文件：
![2021-06-01 21-28-22 的屏幕截图](https://user-images.githubusercontent.com/51730731/120332664-8e14d880-c321-11eb-859e-0054ac20e3b7.png)

下图时验证输出时q6显示为none
![2021-06-01 21-24-45 的屏幕截图](https://user-images.githubusercontent.com/51730731/120332697-92d98c80-c321-11eb-8704-d91f13204ec0.png)

计算不同种类的AP是否在ppdet/metrics/map_utils.py文件中？或是要在哪个文件改代码才能全部显示种类的AP值？

**Comment by yghstill** [comment]
@Aterlayer 设置num_classes是否是真实的类别数？可以在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/metrics/map_utils.py#L247 打印看下具体评估结果。
我使用原始voc数据进行classwise评估，结果是正确的：
```
[06/02 08:06:10] ppdet.metrics.map_utils INFO: Per-category of VOC AP:
+-------------+-------+-------------+-------+----------+-------+
| category    | AP    | category    | AP    | category | AP    |
+-------------+-------+-------------+-------+----------+-------+
| aeroplane   | 0.763 | bicycle     | 0.821 | bird     | 0.695 |
| boat        | 0.631 | bottle      | 0.464 | bus      | 0.812 |
| car         | 0.800 | cat         | 0.856 | chair    | 0.591 |
| cow         | 0.734 | diningtable | 0.742 | dog      | 0.815 |
| horse       | 0.862 | motorbike   | 0.840 | person   | 0.768 |
| pottedplant | 0.490 | sheep       | 0.684 | sofa     | 0.813 |
| train       | 0.849 | tvmonitor   | 0.735 | None     | None  |
+-------------+-------+-------------+-------+----------+-------+
[06/02 08:06:10] ppdet.metrics.map_utils INFO: per-category PR curve has output to voc_pr_curve folder.
[06/02 08:06:10] ppdet.metrics.metrics INFO: mAP(0.50, 11point) = 73.83%
```

**Comment by gaorui999** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/metrics/map_utils.py
这个是怎么用
