### ISSUE TITLE
FairMot Loss为负数是什么原因？其他loss还挺正常的

### ISSUE THREAD

**Issue by YmanChris** [PaddlePaddle/PaddleDetection#3236]
![image](https://user-images.githubusercontent.com/18142592/120403405-b1b63e00-c376-11eb-99ee-1f085de43319.png)

**Comment by nemonameless** [comment]
你好，fairmot loss计算[代码](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/modeling/losses/fairmot_loss.py#L37)，总loss是可能为负数的。另外可以给下运行命令，数据集以及配置文件？

**Comment by YmanChris** [comment]
> 你好，fairmot loss计算[代码](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/modeling/losses/fairmot_loss.py#L37)，总loss是可能为负数的。另外可以给下运行命令，数据集以及配置文件？

用的MOT20数据集，python tools/train.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml,配置文件是release2.1分支里没有改过的，训练几轮之后就负数了，请问可以从何处优化？

**Comment by FlyingQianMM** [comment]
![image](https://user-images.githubusercontent.com/22235422/120416430-b5a28a00-c38f-11eb-9a64-3a052c98ea0f.png)

使用mot20.train，bs=6，lr=0.00005，单卡，没有复现出负loss的情况，请问对config配置文件都做了哪些修改呢？另外是怎么运行命令的？

**Comment by YmanChris** [comment]
> ![image](https://user-images.githubusercontent.com/22235422/120416430-b5a28a00-c38f-11eb-9a64-3a052c98ea0f.png)
> 
> 使用mot20.train，bs=6，lr=0.00005，单卡，没有复现出负loss的情况，请问对config配置文件都做了哪些修改呢？另外是怎么运行命令的？

运行命令上面已发，mot20需要多训几十轮才会出现，默认的config，自制数据集就很快出现这个问题了。
![image](https://user-images.githubusercontent.com/18142592/120455631-83ad1a00-c3c7-11eb-9599-129ef1906117.png)

**Comment by nemonameless** [comment]
请问训完测了吗结果是否符合预期？总loss从计算公式上看是可能出现为负的。

**Comment by YmanChris** [comment]
> 请问训完测了吗结果是否符合预期？总loss从计算公式上看是可能出现为负的。

我增强了数据集，目前负数情况减少了。问题已解决，多谢。
