### ISSUE TITLE
Question about pp-yolov2 network structure

### ISSUE THREAD

**Issue by menggui1993** [PaddlePaddle/PaddleDetection#3239]
In pp-yolov2, dropblock and spp are used in the PAN. In the paper, it seems that dropblock and spp are inserted after the second Conv Block in the Detection Block.
![Screenshot from 2021-06-02 10-58-16](https://user-images.githubusercontent.com/13851918/120417920-36fb1c00-c392-11eb-921e-8f33c60eda7c.png)

However, in your code, it seems they are inserted after the third Conv Block.
https://github.com/PaddlePaddle/PaddleDetection/blob/66d7eefab9aca8243ddf49a52b748b786b80ffb5/ppdet/modeling/necks/yolo_fpn.py#L910

Though I think this might not affect the results much, is there any reason for making the change?

**Comment by wangxinxin08** [comment]
Each conv block contains two conv layers，so dropblock is inserted after the second conv block. And SPP is inserted after the first layer of the second block.

**Comment by menggui1993** [comment]
Is SPP inserted or replacing the conv? In the code, it seems that it will replace the second conv of the second block.

**Comment by wangxinxin08** [comment]
In fact, the SPP module is consisted of spp layer and a  conv layer, so the SPP module replaces the second conv of the second layer while ths spp layer is inserted the first layer of the second block.

**Comment by menggui1993** [comment]
Thanks.
