### ISSUE TITLE
计算模型计算量输出负值

### ISSUE THREAD

**Issue by Harry-675** [PaddlePaddle/PaddleDetection#3240]
如下图所示，计算模型计算量时输出负值。
（注，直接使用2.1版本计算量函数有报错，因此修改了dynamic_flops里面的函数，将图像尺寸变换成了词典，修改如图1 所示）
图1：
![image](https://user-images.githubusercontent.com/29157861/120418772-ba693d00-c393-11eb-96a3-197bdcfbed5e.png)
图2：计算量错误，好像是数值范围越界了，但是64位的python为什么最大值是32位
![image](https://user-images.githubusercontent.com/29157861/120418477-31ea9c80-c393-11eb-8e20-0f049a456297.png)

**Comment by nemonameless** [comment]
看起来是flops计算逻辑的问题，建议可以到paddle提个issue？ https://github.com/PaddlePaddle/Paddle/issues

**Comment by yghstill** [comment]
@Harry-675 目前已支持计算FLOPs功能：#3629
