### ISSUE TITLE
PPYOLO 训练 VOC 数据集，评估卡死

### ISSUE THREAD

**Issue by Lutl** [PaddlePaddle/PaddleDetection#3246]
- PaddleDetection版本是2.0.1
- 使用 ppyolo_r50vd_dcn_voc.yml 对 VOC2007 数据集进行训练

在对模型进行评估时，长时间等待，没有评估进度提高，就是出现以下终端输出后就没了反应，应该是卡死了
```
ppdet.engine INFO: Eval iter: 0
```

**Comment by nemonameless** [comment]
请问是边训边验证？前几个epoch的评估吗？ppyolo训练前期精度较低nms非常慢，建议不开启--eval的 边训边验证，或者可以多训几个epoch后自己手动eval

**Comment by Lutl** [comment]
> 请问是边训边验证？前几个epoch的评估吗？ppyolo训练前期精度较低nms非常慢，建议不开启--eval的 边训边验证，或者可以多训几个epoch后自己手动eval

是训练后，用 tools/eval.py 手动评估的，特别慢，15个小时，也就评了100张吧，龟速，不知道怎么回事

**Comment by XingYZhu** [comment]
有同样的问题

**Comment by wangxinxin08** [comment]
建议更新到PaddleDetection最新的release/2.3版本
