### ISSUE TITLE
用自己的训练集训练yolov3后无法检测到目标！

### ISSUE THREAD

**Issue by Eve66666** [PaddlePaddle/PaddleDetection#325]
我从git上今天刚刚clone下来的代码，在ai studio上去跑，一开始使用的水果数据集跑完yolov3_mobilenet后，目标检测没有出问题，然后我将水果数据集里面的标签和图片换成自己的，并且把label list和yaml里面的classes也改成对应的，运行以后，终端也能通过代码找到我的验证集和训练集(看返回的样本数量)，但最终跑完以后检测图片的时候却无法得到结果。请问是为什么？
ps：跑完以后，我通过它检测原本训练集中的数据时，能出结果，但检测其他的图片就不行了，共测验了6张（1张来自训练集，5张来自其他途径）

**Comment by FDInSky** [comment]
如果检测训练集图片，出结果，说明代码流程没问题，请问模型正常收敛了吗？

**Comment by 1024er** [comment]
如果已经没问题了麻烦close下issue吧，谢谢。
