### ISSUE TITLE
在TX2部署PPYOLO-tiny，在cpu、fluid、trt_fp32、trt_fp16、trt_int8下的问题

### ISSUE THREAD

**Issue by lleesg** [PaddlePaddle/PaddleDetection#3254]
环境：TX2、Ubuntu18.04、CUDA10.2、cudnn 8.0.0、jetpack 4.4、python3.6、Paddle2.1.0

代码：导出PPYOLO-tiny模型后，使用https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/python/infer.py进行预测

- CPU：一切正常
- fluid：正常运行，但检测不到结果（No object detected）
- trt_fp32：一切正常
- trt_fp16：报错
![2021-06-02_205821](https://user-images.githubusercontent.com/16949144/120483992-36d83c00-c3e5-11eb-84ea-3e9f73e329c1.jpg)

- trt_int6：量化生成校准表时报错
![11](https://user-images.githubusercontent.com/16949144/120484114-55d6ce00-c3e5-11eb-9a41-1c45fe67f303.png)

NVD官网显示是TX资源不足？
![微信图片_20210602205659](https://user-images.githubusercontent.com/16949144/120483774-02648000-c3e5-11eb-9918-109885c61ee0.png)

**Comment by liuhuiCNN** [comment]
看起来是资源不足引起的错误，请问有打开最大性能模型吗？使用命令 `sudo nvpmodel -m 0`试下。
您还可以参考文档：https://paddle-inference.readthedocs.io/en/latest/demo_tutorial/cuda_jetson_demo.html

**Comment by lleesg** [comment]
> 看起来是资源不足引起的错误，请问有打开最大性能模型吗？使用命令 `sudo nvpmodel -m 0`试下。
> 您还可以参考文档：https://paddle-inference.readthedocs.io/en/latest/demo_tutorial/cuda_jetson_demo.html

打开了最大性能模式也报这个错，fluid、trt_fp16的两个错能帮忙看下么？3q~~

**Comment by liuhuiCNN** [comment]
> > 看起来是资源不足引起的错误，请问有打开最大性能模型吗？使用命令 `sudo nvpmodel -m 0`试下。
> > 您还可以参考文档：https://paddle-inference.readthedocs.io/en/latest/demo_tutorial/cuda_jetson_demo.html
> 
> 打开了最大性能模式也报这个错，fluid、trt_fp16的两个错能帮忙看下么？3q~~

根据提示错误，结合我们在Nano设备上PPYOLO是正常的，看起来像是opencv错的，请问使用的opencv版本是多少呢？测试图像是demo文件夹下的示例图像吗？
之前有遇到过图像尺寸过大，导致错误，也是提示resource的问题。您测试图像尺寸多大呢？

**Comment by lleesg** [comment]
> > > 看起来是资源不足引起的错误，请问有打开最大性能模型吗？使用命令 `sudo nvpmodel -m 0`试下。
> > > 您还可以参考文档：https://paddle-inference.readthedocs.io/en/latest/demo_tutorial/cuda_jetson_demo.html
> > 
> > 
> > 打开了最大性能模式也报这个错，fluid、trt_fp16的两个错能帮忙看下么？3q~~
> 
> 根据提示错误，结合我们在Nano设备上PPYOLO是正常的，看起来像是opencv错的，请问使用的opencv版本是多少呢？测试图像是demo文件夹下的示例图像吗？
> 之前有遇到过图像尺寸过大，导致错误，也是提示resource的问题。您测试图像尺寸多大呢？

Opencv 4.1.1
测试图像用的demo下的示例图像（跟这个应该关系不大）
测试尺寸是608

**Comment by wwqgtxx** [comment]
在 https://github.com/PaddlePaddle/Paddle/pull/33442 这个提交后，TX2的检测应该是正常了，我这次亲测的fluid、trt_fp32、trt_fp16、trt_int8 都是正常的

```
dji@manifold2:~/PaddleDetection$ python3 tools/export_model.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyolo_tiny_650e_coco.pdparams
/usr/local/lib/python3.6/dist-packages/Pillow-8.2.0-py3.6-linux-aarch64.egg/PIL/_imaging.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for a
ernative uses
[09/15 21:47:13] ppdet.utils.download INFO: Downloading ppyolo_tiny_650e_coco.pdparams from https://paddledet.bj.bcebos.com/models/ppyolo_tiny_650e_coco.pdparams
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4342/4342 [00:15<00:00, 279.06KB/
[09/15 21:47:30] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/dji/.cache/paddle/weights/ppyolo_tiny_650e_coco.pdparams
[09/15 21:47:30] ppdet.engine INFO: Export inference config file to output_inference/ppyolo_tiny_650e_coco/infer_cfg.yml
W0915 21:47:52.814337 22266 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.2, Driver API Version: 10.2, Runtime API Version: 10.2
W0915 21:47:52.814443 22266 device_context.cc:422] device: 0, cuDNN Version: 8.0.
[09/15 21:47:58] ppdet.engine INFO: Export model and saved in output_inference/ppyolo_tiny_650e_coco

dji@manifold2:~/PaddleDetection$ CUDA_VISIBLE_DEVICES=0 python3 deploy/python/infer.py --model_dir=output_inference/ppyolo_tiny_650e_coco --image_file=demo/000000014439_640x640.jpg --device=GPU --run_mode fluid
/usr/local/lib/python3.6/dist-packages/Pillow-8.2.0-py3.6-linux-aarch64.egg/PIL/_imaging.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for a
ernative uses
-----------  Running Arguments -----------
batch_size: 1
camera_id: -1
cpu_threads: 1
device: GPU
enable_mkldnn: False
image_dir: None
image_file: demo/000000014439_640x640.jpg
model_dir: output_inference/ppyolo_tiny_650e_coco
output_dir: output
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: fluid
save_images: False
save_mot_txts: False
threshold: 0.5
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dark: True
use_gpu: False
video_file: None
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
class_id:0, confidence:0.9592, left_top:[384.90,145.12],right_bottom:[495.65,454.26]
class_id:0, confidence:0.9490, left_top:[261.95,126.10],right_bottom:[299.20,268.16]
class_id:0, confidence:0.9426, left_top:[494.36,176.56],right_bottom:[569.97,437.16]
class_id:0, confidence:0.9079, left_top:[159.92,131.09],right_bottom:[204.24,263.57]
class_id:0, confidence:0.8303, left_top:[106.42,67.97],right_bottom:[123.09,147.51]
class_id:0, confidence:0.8248, left_top:[581.02,180.81],right_bottom:[610.46,309.72]
class_id:0, confidence:0.7366, left_top:[361.02,67.16],right_bottom:[386.99,167.88]
class_id:0, confidence:0.6171, left_top:[378.33,68.31],right_bottom:[393.92,136.93]
class_id:0, confidence:0.5617, left_top:[352.31,72.77],right_bottom:[376.60,160.07]
class_id:2, confidence:0.5533, left_top:[538.18,23.79],right_bottom:[568.87,49.88]
class_id:33, confidence:0.9312, left_top:[164.72,151.78],right_bottom:[546.81,552.04]
save result to: output/000000014439_640x640.jpg
------------------ Inference Time Info ----------------------
total_time(ms): 1195.4, img_num: 1
average latency time(ms): 1195.40, QPS: 0.836540
preprocess_time(ms): 42.70, inference_time(ms): 1152.60, postprocess_time(ms): 0.10


dji@manifold2:~/PaddleDetection$ CUDA_VISIBLE_DEVICES=0 python3 deploy/python/infer.py --model_dir=output_inference/ppyolo_tiny_650e_coco --image_file=demo/000000014439_640x640.jpg --device=GPU --run_mode trt_fp32
/usr/local/lib/python3.6/dist-packages/Pillow-8.2.0-py3.6-linux-aarch64.egg/PIL/_imaging.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for a
ernative uses
-----------  Running Arguments -----------
batch_size: 1
camera_id: -1
cpu_threads: 1
device: GPU
enable_mkldnn: False
image_dir: None
image_file: demo/000000014439_640x640.jpg
model_dir: output_inference/ppyolo_tiny_650e_coco
output_dir: output
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: trt_fp32
save_images: False
save_mot_txts: False
threshold: 0.5
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dark: True
use_gpu: False
video_file: None
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
class_id:0, confidence:0.9592, left_top:[384.68,144.95],right_bottom:[495.43,454.08]
class_id:0, confidence:0.9490, left_top:[261.85,126.02],right_bottom:[299.10,268.08]
class_id:0, confidence:0.9426, left_top:[494.16,176.36],right_bottom:[569.78,436.96]
class_id:0, confidence:0.9079, left_top:[159.83,131.01],right_bottom:[204.15,263.49]
class_id:0, confidence:0.8303, left_top:[106.44,67.86],right_bottom:[123.10,147.40]
class_id:0, confidence:0.8248, left_top:[580.98,180.73],right_bottom:[610.43,309.64]
class_id:0, confidence:0.7366, left_top:[360.93,67.08],right_bottom:[386.90,167.80]
class_id:0, confidence:0.6171, left_top:[378.39,68.21],right_bottom:[393.98,136.83]
class_id:0, confidence:0.5617, left_top:[352.19,72.72],right_bottom:[376.49,160.02]
class_id:2, confidence:0.5533, left_top:[538.08,23.72],right_bottom:[568.77,49.82]
class_id:33, confidence:0.9312, left_top:[164.32,151.38],right_bottom:[546.41,551.64]
save result to: output/000000014439_640x640.jpg
------------------ Inference Time Info ----------------------
total_time(ms): 94.2, img_num: 1
average latency time(ms): 94.20, QPS: 10.615711
preprocess_time(ms): 42.40, inference_time(ms): 51.70, postprocess_time(ms): 0.10


dji@manifold2:~/PaddleDetection$ CUDA_VISIBLE_DEVICES=0 python3 deploy/python/infer.py --model_dir=output_inference/ppyolo_tiny_650e_coco --image_file=demo/000000014439_640x640.jpg --device=GPU --run_mode=trt_fp16
/usr/local/lib/python3.6/dist-packages/Pillow-8.2.0-py3.6-linux-aarch64.egg/PIL/_imaging.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for a
ernative uses
-----------  Running Arguments -----------
batch_size: 1
camera_id: -1
cpu_threads: 1
device: GPU
enable_mkldnn: False
image_dir: None
image_file: demo/000000014439_640x640.jpg
model_dir: output_inference/ppyolo_tiny_650e_coco
output_dir: output
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: trt_fp16
save_images: False
save_mot_txts: False
threshold: 0.5
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dark: True
use_gpu: False
video_file: None
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
class_id:0, confidence:0.9590, left_top:[384.75,145.00],right_bottom:[495.50,454.00]
class_id:0, confidence:0.9492, left_top:[261.75,126.06],right_bottom:[299.00,268.00]
class_id:0, confidence:0.9424, left_top:[494.25,176.25],right_bottom:[569.50,437.00]
class_id:0, confidence:0.9077, left_top:[159.88,131.12],right_bottom:[204.12,263.25]
class_id:0, confidence:0.8320, left_top:[106.44,67.88],right_bottom:[123.06,147.38]
class_id:0, confidence:0.8218, left_top:[581.00,180.75],right_bottom:[610.50,309.50]
class_id:0, confidence:0.7383, left_top:[361.00,67.06],right_bottom:[387.00,167.88]
class_id:0, confidence:0.6182, left_top:[378.50,68.19],right_bottom:[394.00,136.88]
class_id:0, confidence:0.5630, left_top:[352.25,72.75],right_bottom:[376.50,160.00]
class_id:2, confidence:0.5542, left_top:[538.00,23.73],right_bottom:[569.00,49.81]
class_id:33, confidence:0.9316, left_top:[164.25,151.38],right_bottom:[546.50,551.50]
save result to: output/000000014439_640x640.jpg
------------------ Inference Time Info ----------------------
total_time(ms): 132.20000000000002, img_num: 1
average latency time(ms): 132.20, QPS: 7.564297
preprocess_time(ms): 44.20, inference_time(ms): 87.90, postprocess_time(ms): 0.10

dji@manifold2:~/PaddleDetection$ CUDA_VISIBLE_DEVICES=0 python3 deploy/python/infer.py --model_dir=output_inference/ppyolo_tiny_650e_coco --image_file=demo/000000014439_640x640.jpg --device=GPU --run_mode
rt_int8 --trt_calib_mode True
/usr/local/lib/python3.6/dist-packages/Pillow-8.2.0-py3.6-linux-aarch64.egg/PIL/_imaging.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for a
ernative uses
-----------  Running Arguments -----------
batch_size: 1
camera_id: -1
cpu_threads: 1
device: GPU
enable_mkldnn: False
image_dir: None
image_file: demo/000000014439_640x640.jpg
model_dir: output_inference/ppyolo_tiny_650e_coco
output_dir: output
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: trt_int8
save_images: False
save_mot_txts: False
threshold: 0.5
trt_calib_mode: True
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dark: True
use_gpu: False
video_file: None
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
class_id:0, confidence:0.9652, left_top:[264.59,130.09],right_bottom:[299.59,265.69]
class_id:0, confidence:0.9579, left_top:[396.74,146.50],right_bottom:[483.53,453.00]
class_id:0, confidence:0.8784, left_top:[161.50,134.84],right_bottom:[204.00,259.44]
class_id:0, confidence:0.8374, left_top:[499.01,177.35],right_bottom:[569.46,435.26]
class_id:0, confidence:0.8087, left_top:[582.71,181.45],right_bottom:[610.04,288.95]
class_id:0, confidence:0.7682, left_top:[106.69,70.85],right_bottom:[123.66,145.33]
class_id:0, confidence:0.6550, left_top:[361.47,70.48],right_bottom:[387.00,161.75]
class_id:0, confidence:0.6161, left_top:[377.90,69.84],right_bottom:[394.58,134.55]
class_id:0, confidence:0.5735, left_top:[326.82,63.14],right_bottom:[341.62,121.02]
class_id:0, confidence:0.5145, left_top:[351.51,74.32],right_bottom:[376.47,157.01]
save result to: output/000000014439_640x640.jpg
------------------ Inference Time Info ----------------------
total_time(ms): 47021.0, img_num: 1
average latency time(ms): 47021.00, QPS: 0.021267
preprocess_time(ms): 43.30, inference_time(ms): 46977.60, postprocess_time(ms): 0.10
```

**Comment by lleesg** [comment]
更新到2.1.2后，问题解决，测试结果：https://github.com/PaddlePaddle/PaddleDetection/issues/4352#issue-1032327425

**Comment by lleesg** [comment]
> 在 [PaddlePaddle/Paddle#33442](https://github.com/PaddlePaddle/Paddle/pull/33442) 这个提交后，TX2的检测应该是正常了，我这次亲测的fluid、trt_fp32、trt_fp16、trt_int8 都是正常的
> 
> ```
> dji@manifold2:~/PaddleDetection$ python3 tools/export_model.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyolo_tiny_650e_coco.pdparams
> /usr/local/lib/python3.6/dist-packages/Pillow-8.2.0-py3.6-linux-aarch64.egg/PIL/_imaging.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for a
> ernative uses
> [09/15 21:47:13] ppdet.utils.download INFO: Downloading ppyolo_tiny_650e_coco.pdparams from https://paddledet.bj.bcebos.com/models/ppyolo_tiny_650e_coco.pdparams
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4342/4342 [00:15<00:00, 279.06KB/
> [09/15 21:47:30] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/dji/.cache/paddle/weights/ppyolo_tiny_650e_coco.pdparams
> [09/15 21:47:30] ppdet.engine INFO: Export inference config file to output_inference/ppyolo_tiny_650e_coco/infer_cfg.yml
> W0915 21:47:52.814337 22266 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.2, Driver API Version: 10.2, Runtime API Version: 10.2
> W0915 21:47:52.814443 22266 device_context.cc:422] device: 0, cuDNN Version: 8.0.
> [09/15 21:47:58] ppdet.engine INFO: Export model and saved in output_inference/ppyolo_tiny_650e_coco
> 
> dji@manifold2:~/PaddleDetection$ CUDA_VISIBLE_DEVICES=0 python3 deploy/python/infer.py --model_dir=output_inference/ppyolo_tiny_650e_coco --image_file=demo/000000014439_640x640.jpg --device=GPU --run_mode fluid
> /usr/local/lib/python3.6/dist-packages/Pillow-8.2.0-py3.6-linux-aarch64.egg/PIL/_imaging.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for a
> ernative uses
> -----------  Running Arguments -----------
> batch_size: 1
> camera_id: -1
> cpu_threads: 1
> device: GPU
> enable_mkldnn: False
> image_dir: None
> image_file: demo/000000014439_640x640.jpg
> model_dir: output_inference/ppyolo_tiny_650e_coco
> output_dir: output
> reid_batch_size: 50
> reid_model_dir: None
> run_benchmark: False
> run_mode: fluid
> save_images: False
> save_mot_txts: False
> threshold: 0.5
> trt_calib_mode: False
> trt_max_shape: 1280
> trt_min_shape: 1
> trt_opt_shape: 640
> use_dark: True
> use_gpu: False
> video_file: None
> ------------------------------------------
> -----------  Model Configuration -----------
> Model Arch: YOLO
> Transform Order:
> --transform op: Resize
> --transform op: NormalizeImage
> --transform op: Permute
> --------------------------------------------
> class_id:0, confidence:0.9592, left_top:[384.90,145.12],right_bottom:[495.65,454.26]
> class_id:0, confidence:0.9490, left_top:[261.95,126.10],right_bottom:[299.20,268.16]
> class_id:0, confidence:0.9426, left_top:[494.36,176.56],right_bottom:[569.97,437.16]
> class_id:0, confidence:0.9079, left_top:[159.92,131.09],right_bottom:[204.24,263.57]
> class_id:0, confidence:0.8303, left_top:[106.42,67.97],right_bottom:[123.09,147.51]
> class_id:0, confidence:0.8248, left_top:[581.02,180.81],right_bottom:[610.46,309.72]
> class_id:0, confidence:0.7366, left_top:[361.02,67.16],right_bottom:[386.99,167.88]
> class_id:0, confidence:0.6171, left_top:[378.33,68.31],right_bottom:[393.92,136.93]
> class_id:0, confidence:0.5617, left_top:[352.31,72.77],right_bottom:[376.60,160.07]
> class_id:2, confidence:0.5533, left_top:[538.18,23.79],right_bottom:[568.87,49.88]
> class_id:33, confidence:0.9312, left_top:[164.72,151.78],right_bottom:[546.81,552.04]
> save result to: output/000000014439_640x640.jpg
> ------------------ Inference Time Info ----------------------
> total_time(ms): 1195.4, img_num: 1
> average latency time(ms): 1195.40, QPS: 0.836540
> preprocess_time(ms): 42.70, inference_time(ms): 1152.60, postprocess_time(ms): 0.10
> 
> 
> dji@manifold2:~/PaddleDetection$ CUDA_VISIBLE_DEVICES=0 python3 deploy/python/infer.py --model_dir=output_inference/ppyolo_tiny_650e_coco --image_file=demo/000000014439_640x640.jpg --device=GPU --run_mode trt_fp32
> /usr/local/lib/python3.6/dist-packages/Pillow-8.2.0-py3.6-linux-aarch64.egg/PIL/_imaging.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for a
> ernative uses
> -----------  Running Arguments -----------
> batch_size: 1
> camera_id: -1
> cpu_threads: 1
> device: GPU
> enable_mkldnn: False
> image_dir: None
> image_file: demo/000000014439_640x640.jpg
> model_dir: output_inference/ppyolo_tiny_650e_coco
> output_dir: output
> reid_batch_size: 50
> reid_model_dir: None
> run_benchmark: False
> run_mode: trt_fp32
> save_images: False
> save_mot_txts: False
> threshold: 0.5
> trt_calib_mode: False
> trt_max_shape: 1280
> trt_min_shape: 1
> trt_opt_shape: 640
> use_dark: True
> use_gpu: False
> video_file: None
> ------------------------------------------
> -----------  Model Configuration -----------
> Model Arch: YOLO
> Transform Order:
> --transform op: Resize
> --transform op: NormalizeImage
> --transform op: Permute
> --------------------------------------------
> class_id:0, confidence:0.9592, left_top:[384.68,144.95],right_bottom:[495.43,454.08]
> class_id:0, confidence:0.9490, left_top:[261.85,126.02],right_bottom:[299.10,268.08]
> class_id:0, confidence:0.9426, left_top:[494.16,176.36],right_bottom:[569.78,436.96]
> class_id:0, confidence:0.9079, left_top:[159.83,131.01],right_bottom:[204.15,263.49]
> class_id:0, confidence:0.8303, left_top:[106.44,67.86],right_bottom:[123.10,147.40]
> class_id:0, confidence:0.8248, left_top:[580.98,180.73],right_bottom:[610.43,309.64]
> class_id:0, confidence:0.7366, left_top:[360.93,67.08],right_bottom:[386.90,167.80]
> class_id:0, confidence:0.6171, left_top:[378.39,68.21],right_bottom:[393.98,136.83]
> class_id:0, confidence:0.5617, left_top:[352.19,72.72],right_bottom:[376.49,160.02]
> class_id:2, confidence:0.5533, left_top:[538.08,23.72],right_bottom:[568.77,49.82]
> class_id:33, confidence:0.9312, left_top:[164.32,151.38],right_bottom:[546.41,551.64]
> save result to: output/000000014439_640x640.jpg
> ------------------ Inference Time Info ----------------------
> total_time(ms): 94.2, img_num: 1
> average latency time(ms): 94.20, QPS: 10.615711
> preprocess_time(ms): 42.40, inference_time(ms): 51.70, postprocess_time(ms): 0.10
> 
> 
> dji@manifold2:~/PaddleDetection$ CUDA_VISIBLE_DEVICES=0 python3 deploy/python/infer.py --model_dir=output_inference/ppyolo_tiny_650e_coco --image_file=demo/000000014439_640x640.jpg --device=GPU --run_mode=trt_fp16
> /usr/local/lib/python3.6/dist-packages/Pillow-8.2.0-py3.6-linux-aarch64.egg/PIL/_imaging.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for a
> ernative uses
> -----------  Running Arguments -----------
> batch_size: 1
> camera_id: -1
> cpu_threads: 1
> device: GPU
> enable_mkldnn: False
> image_dir: None
> image_file: demo/000000014439_640x640.jpg
> model_dir: output_inference/ppyolo_tiny_650e_coco
> output_dir: output
> reid_batch_size: 50
> reid_model_dir: None
> run_benchmark: False
> run_mode: trt_fp16
> save_images: False
> save_mot_txts: False
> threshold: 0.5
> trt_calib_mode: False
> trt_max_shape: 1280
> trt_min_shape: 1
> trt_opt_shape: 640
> use_dark: True
> use_gpu: False
> video_file: None
> ------------------------------------------
> -----------  Model Configuration -----------
> Model Arch: YOLO
> Transform Order:
> --transform op: Resize
> --transform op: NormalizeImage
> --transform op: Permute
> --------------------------------------------
> class_id:0, confidence:0.9590, left_top:[384.75,145.00],right_bottom:[495.50,454.00]
> class_id:0, confidence:0.9492, left_top:[261.75,126.06],right_bottom:[299.00,268.00]
> class_id:0, confidence:0.9424, left_top:[494.25,176.25],right_bottom:[569.50,437.00]
> class_id:0, confidence:0.9077, left_top:[159.88,131.12],right_bottom:[204.12,263.25]
> class_id:0, confidence:0.8320, left_top:[106.44,67.88],right_bottom:[123.06,147.38]
> class_id:0, confidence:0.8218, left_top:[581.00,180.75],right_bottom:[610.50,309.50]
> class_id:0, confidence:0.7383, left_top:[361.00,67.06],right_bottom:[387.00,167.88]
> class_id:0, confidence:0.6182, left_top:[378.50,68.19],right_bottom:[394.00,136.88]
> class_id:0, confidence:0.5630, left_top:[352.25,72.75],right_bottom:[376.50,160.00]
> class_id:2, confidence:0.5542, left_top:[538.00,23.73],right_bottom:[569.00,49.81]
> class_id:33, confidence:0.9316, left_top:[164.25,151.38],right_bottom:[546.50,551.50]
> save result to: output/000000014439_640x640.jpg
> ------------------ Inference Time Info ----------------------
> total_time(ms): 132.20000000000002, img_num: 1
> average latency time(ms): 132.20, QPS: 7.564297
> preprocess_time(ms): 44.20, inference_time(ms): 87.90, postprocess_time(ms): 0.10
> 
> dji@manifold2:~/PaddleDetection$ CUDA_VISIBLE_DEVICES=0 python3 deploy/python/infer.py --model_dir=output_inference/ppyolo_tiny_650e_coco --image_file=demo/000000014439_640x640.jpg --device=GPU --run_mode
> rt_int8 --trt_calib_mode True
> /usr/local/lib/python3.6/dist-packages/Pillow-8.2.0-py3.6-linux-aarch64.egg/PIL/_imaging.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for a
> ernative uses
> -----------  Running Arguments -----------
> batch_size: 1
> camera_id: -1
> cpu_threads: 1
> device: GPU
> enable_mkldnn: False
> image_dir: None
> image_file: demo/000000014439_640x640.jpg
> model_dir: output_inference/ppyolo_tiny_650e_coco
> output_dir: output
> reid_batch_size: 50
> reid_model_dir: None
> run_benchmark: False
> run_mode: trt_int8
> save_images: False
> save_mot_txts: False
> threshold: 0.5
> trt_calib_mode: True
> trt_max_shape: 1280
> trt_min_shape: 1
> trt_opt_shape: 640
> use_dark: True
> use_gpu: False
> video_file: None
> ------------------------------------------
> -----------  Model Configuration -----------
> Model Arch: YOLO
> Transform Order:
> --transform op: Resize
> --transform op: NormalizeImage
> --transform op: Permute
> --------------------------------------------
> class_id:0, confidence:0.9652, left_top:[264.59,130.09],right_bottom:[299.59,265.69]
> class_id:0, confidence:0.9579, left_top:[396.74,146.50],right_bottom:[483.53,453.00]
> class_id:0, confidence:0.8784, left_top:[161.50,134.84],right_bottom:[204.00,259.44]
> class_id:0, confidence:0.8374, left_top:[499.01,177.35],right_bottom:[569.46,435.26]
> class_id:0, confidence:0.8087, left_top:[582.71,181.45],right_bottom:[610.04,288.95]
> class_id:0, confidence:0.7682, left_top:[106.69,70.85],right_bottom:[123.66,145.33]
> class_id:0, confidence:0.6550, left_top:[361.47,70.48],right_bottom:[387.00,161.75]
> class_id:0, confidence:0.6161, left_top:[377.90,69.84],right_bottom:[394.58,134.55]
> class_id:0, confidence:0.5735, left_top:[326.82,63.14],right_bottom:[341.62,121.02]
> class_id:0, confidence:0.5145, left_top:[351.51,74.32],right_bottom:[376.47,157.01]
> save result to: output/000000014439_640x640.jpg
> ------------------ Inference Time Info ----------------------
> total_time(ms): 47021.0, img_num: 1
> average latency time(ms): 47021.00, QPS: 0.021267
> preprocess_time(ms): 43.30, inference_time(ms): 46977.60, postprocess_time(ms): 0.10
> ```

你好，能否帮忙看看：#4352 (comment)
谢谢~
