### ISSUE TITLE
关于mot_pose_demo_640x360.gif骨架识别是由哪个算法实现的

### ISSUE THREAD

**Issue by Zzhenh** [PaddlePaddle/PaddleDetection#3257]
想学习应用一下骨架识别，但是只看到了效果图片，没有找到对应算法

**Comment by nemonameless** [comment]
人体姿态估计算法HRNet + 多目标跟踪算法FairMOT，算法分别在 [configs/keypoint](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/configs/keypoint)  和 [configs/mot](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/configs/mot)
