### ISSUE TITLE
训练SSD_mobilenetv1 模型出错

### ISSUE THREAD

**Issue by 1220985305** [PaddlePaddle/PaddleDetection#3259]
λ 87851cdca26b /opt/LiangXS/PaddleDetection_ssd python3.7 tools/train.py -c configs/ssd/ssd_mobilenet_v1_300_120e_voc.yml
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
W0602 16:29:25.165112 17192 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W0602 16:29:25.169080 17192 device_context.cc:372] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
File "tools/train.py", line 140, in
main()
File "tools/train.py", line 136, in main
run(FLAGS, cfg)
File "tools/train.py", line 102, in run
trainer = Trainer(cfg, mode='train')
File "/usr/local/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 87, in __init__
self.lr = create('LearningRate')(steps_per_epoch)
File "/usr/local/lib/python3.7/site-packages/ppdet/optimizer.py", line 173, in __call__
step_per_epoch=step_per_epoch)
File "/usr/local/lib/python3.7/site-packages/ppdet/optimizer.py", line 120, in __call__
return optimizer.lr.PiecewiseDecay(boundary, value)
File "/usr/local/lib/python3.7/site-packages/paddle/optimizer/lr.py", line 369, in __init__
last_epoch=last_epoch, verbose=verbose)
File "/usr/local/lib/python3.7/site-packages/paddle/optimizer/lr.py", line 90, in __init__
self.step()
File "/usr/local/lib/python3.7/site-packages/paddle/optimizer/lr.py", line 113, in step
self.last_lr = self.get_lr()
File "/usr/local/lib/python3.7/site-packages/paddle/optimizer/lr.py", line 374, in get_lr
return self.values[i]
TypeError: 'NoneType' object is not subscriptable
**********************************************************************************************************
版本为paddledetection2.1

**Comment by nemonameless** [comment]
亲测可以训练，看起来你的代码没有更新到最新，建议拉下最新代码，以及卸载旧版本ppdet和重装ppdet `python setup.py install`

**Comment by 1220985305** [comment]
配置文件
architecture: SSD
pretrain_weights: pretain_model/ssd_mobilenet_v1_300_120e_voc.pdparams

SSD:
  backbone: MobileNet
  ssd_head: SSDHead
  post_process: BBoxPostProcess

MobileNet:
  norm_decay: 0.
  scale: 1
  conv_learning_rate: 0.1
  extra_block_filters: [[256, 512], [128, 256], [128, 256], [64, 128]]
  with_extra_blocks: true
  feature_maps: [11, 13, 14, 15, 16, 17]

SSDHead:
  kernel_size: 1
  padding: 0
  anchor_generator:
    steps: [0, 0, 0, 0, 0, 0]
    aspect_ratios: [[2.], [2., 3.], [2., 3.], [2., 3.], [2., 3.], [2., 3.]]
    min_ratio: 20
    max_ratio: 90
    base_size: 300
    min_sizes: [60.0, 105.0, 150.0, 195.0, 240.0, 285.0]
    max_sizes: [[], 150.0, 195.0, 240.0, 285.0, 300.0]
    offset: 0.5
    flip: true
    min_max_aspect_ratios_order: false

BBoxPostProcess:
  decode:
    name: SSDBox
  nms:
    name: MultiClassNMS
    keep_top_k: 200
    score_threshold: 0.01
    nms_threshold: 0.45
    nms_top_k: 400
    nms_eta: 1.0
**********************************************************************************************************************
数据采用Pascalvoc格式
![image](https://user-images.githubusercontent.com/74039253/120581800-02ed2d00-c45e-11eb-89af-907af3209156.png)

**Comment by 1220985305** [comment]
> 亲测可以训练，看起来你的代码没有更新到最新，建议拉下最新代码，以及卸载旧版本ppdet和重装ppdet `python setup.py install`

已更新代码，问题仍未解决

**Comment by 1220985305** [comment]
> 亲测可以训练，看起来你的代码没有更新到最新，建议拉下最新代码，以及卸载旧版本ppdet和重装ppdet `python setup.py install`

有无训练步骤教程？

**Comment by heavengate** [comment]
训练步骤参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/GETTING_STARTED_cn.md

**Comment by 1220985305** [comment]
> 训练步骤参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/GETTING_STARTED_cn.md

THX

**Comment by heavengate** [comment]
鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen此issue~

**Comment by 1220985305** [comment]
问题未解决，使用最新代码训练，并未解决问题，仍然报错

**Comment by yangy996** [comment]
我也报这个错误，也是最新的代码release/2.1

**Comment by xiangfeidecao** [comment]
> 问题未解决，使用最新代码训练，并未解决问题，仍然报错

请问你后来怎么解决的

**Comment by xiangfeidecao** [comment]
> 我也报这个错误，也是最新的代码release/2.1

请问你后来怎么解决的
