### ISSUE TITLE
在ai studio上如何实时检测模型训练的状态？

### ISSUE THREAD

**Issue by Eve66666** [PaddlePaddle/PaddleDetection#326]
我在ai studio 上训练yolov3时，加了tb_log=true 和-eval ，但我打不开tensorboard，按照网上的说明，我也试过通过网址进入visualdl，结果里面什么都没有，请问有什么好的方法能解决嘛

**Comment by FDInSky** [comment]
请问你是参考什么教程，打开tensorboard的？

**Comment by qingqing01** [comment]
@Eve66666 最新已经换成了VisualDL，AIStudio上支持了VisualDL。
