### ISSUE TITLE
关键点检测能否用自己的数据集进行训练？

### ISSUE THREAD

**Issue by PiggyJie** [PaddlePaddle/PaddleDetection#3263]
如题，各位大佬，我想知道关键点检测能否训练自己的数据集（非人体姿态）？主要用于检测其他类别关键点，如果可以的话应该怎么做？然后现在的关键点检测速度能达到多少呢？如果是多目标情况下的表现又如何？刚接触深度学习，还有很多地方不懂，望各位大佬不吝赐教，感谢！

**Comment by heavengate** [comment]
1. 可以的，我们发布的关键点检测模型都是支持训练的，你可以将你的数据集标注为coco的格式，在配置文件里修改训练数据集路径到你自己的数据集就可以训练
https://github.com/PaddlePaddle/PaddleDetection/blob/df6ce20c25a4c5319039b2beb5a5f7973ff580af/configs/keypoint/hrnet/hrnet_w32_256x192.yml#L60

2. 关键点检测的部署及benchmark我们还在测试中
3. 现在发布的关键点检测都是针对多目标人体关键点检测

**Comment by PiggyJie** [comment]
> 1. 可以的，我们发布的关键点检测模型都是支持训练的，你可以将你的数据集标注为coco的格式，在配置文件里修改训练数据集路径到你自己的数据集就可以训练
>    https://github.com/PaddlePaddle/PaddleDetection/blob/df6ce20c25a4c5319039b2beb5a5f7973ff580af/configs/keypoint/hrnet/hrnet_w32_256x192.yml#L60
> 2. 关键点检测的部署及benchmark我们还在测试中
> 3. 现在发布的关键点检测都是针对多目标人体关键点检测

感谢您的回复。您说是支持自定义训练的，但是如果训练种类不是person的话还支持吗？比如说猫、狗等其他类别的数据（甚至是不属于80个coco类别中的其他类），当然，这些数据都会标注成coco格式。如果支持的话，是不是要修改很多地方？还是只需要修改一些简单的参数就行。
因为现在在做一个关键点检测的课题，但是没有找到合适的模型，所以希望您能进一步解答我的疑问。非常感谢！！！

**Comment by heavengate** [comment]
支持的，只需要标注成coco的格式就可以了
