### ISSUE TITLE
Pass tensorrt_subgraph_pass has not been registered.

### ISSUE THREAD

**Issue by JianJingGao** [PaddlePaddle/PaddleDetection#3264]
改了一下run mode报出
![image](https://user-images.githubusercontent.com/51236891/120604708-e235cf00-c47f-11eb-95cb-fb4891a6a0a9.png)
然后我安装了tensorrt7.0，系统win10，Paddle2.1

请问咋注册这个？

**Comment by heavengate** [comment]
TensorRT预测需要安装带TensorRT编译的Paddle包，可以在这里获取 https://www.paddlepaddle.org.cn/whl/stable/tensorrt.html

**Comment by JianJingGao** [comment]
@heavengate windows有办法吗，我看你给的包都是Linux的呢

**Comment by JianJingGao** [comment]
@heavengate 带TensorRT编译的包之中有适合jetson agx的包吗

**Comment by liuhuiCNN** [comment]
> @heavengate 带TensorRT编译的包之中有适合jetson agx的包吗

有的，请参考这里： https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release

**Comment by liuhuiCNN** [comment]
> @heavengate windows有办法吗，我看你给的包都是Linux的呢

您好，windows下官方没有提供whl包，需要您重新编译。编译的文档，https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/windows-compile.html

**Comment by ximitiejiang** [comment]
windows下不是有吗？这不是你们官方提供的带trt的库吗？
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows

**Comment by JianJingGao** [comment]
C++的，不是Pyhon的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Liang ***@***.***>
发送时间: 2021年6月24日 17:55
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [PaddlePaddle/PaddleDetection] Pass tensorrt_subgraph_pass has not been registered. (#3264)


windows下不是有吗？这不是你们官方提供的带trt的库吗？
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows

―

**Comment by wangxinxin08** [comment]
@JianJingGao windows下面暂时没有trt的python包

**Comment by JianJingGao** [comment]
嗯嗯 我已经自行编译了 这个问题可以关掉了，谢谢。
期待SOLOV2在trt的加速和Swin Transformer推出

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年7月14日 16:10
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [PaddlePaddle/PaddleDetection] Pass tensorrt_subgraph_pass has not been registered. (#3264)


@JianJingGao<https://github.com/JianJingGao> windows下面暂时没有trt的python包

―
