### ISSUE TITLE
EfficientDet 检测类别包括背景么

### ISSUE THREAD

**Issue by xupengao** [PaddlePaddle/PaddleDetection#3266]
在模型配置文件中，num_classes=81，EfficientDet单阶段检测，怎么会带有背景类别，这个是不是弄错了

**Comment by heavengate** [comment]
最后bbox的分类上是需要区分出来是前景的还是背景的，背景的需要被删除掉，所以分类上需要带上一个背景，和SSD及RetinaNet同理

**Comment by xupengao** [comment]
有一些配置参数想请教一下，想调大输入尺寸， 
 - !TargetAssign
    image_size: 512
是只需要改这个么，但是efficient有分辨率的对应比例，是不是需要调整scale，
EfficientNet:
  norm_type: bn
  scale: b0 
而且我自定义训练数据的效果较差，map值不到0.5
