### ISSUE TITLE
PPYOLO MobileNetV3评估报错

### ISSUE THREAD

**Issue by Harry-675** [PaddlePaddle/PaddleDetection#3268]
如图所示，训练没问题，评估时报错，使用ppyolo_tiny训练评估都没有问题，但是large就不行。
![image](https://user-images.githubusercontent.com/29157861/120615982-693c7480-c48b-11eb-8b35-1ec3960c0185.png)

**Comment by wangxinxin08** [comment]
fixed by https://github.com/PaddlePaddle/PaddleDetection/pull/3255! 可以更新最新的代码或者手动修改下
