### ISSUE TITLE
deepsort中的视频读取转换出错

### ISSUE THREAD

**Issue by zhude233** [PaddlePaddle/PaddleDetection#3269]
![image](https://user-images.githubusercontent.com/60126992/120620633-bde1ee80-c48f-11eb-85ae-6bb16e8f55ba.png)
如图在126中返回的im为空值

**Comment by nemonameless** [comment]
可以git clone release/2.1分支的代码试试，以及请提供运行命令和环境版本等信息。

**Comment by zhude233** [comment]
> ・克隆解脱/2.1+1+1+1

![image](https://user-images.githubusercontent.com/60126992/120623445-51b4ba00-c492-11eb-8946-66fa6eb54347.png)环境为paddlepaddle2.1  paddledet2.1.0 paddleDetection2.1
![image](https://user-images.githubusercontent.com/60126992/120623727-8fb1de00-c492-11eb-825f-b8d4d9f39372.png)

**Comment by zhude233** [comment]
在注释掉126行后能够正常运行，不知道是否对其他地方造成什么影响

**Comment by nemonameless** [comment]
deepsort读视频还在完善中，因为涉及到部署问题可能代码还需要稍微改动，近期会尽快更新上去。

**Comment by nemonameless** [comment]
@zhude233 已经支持
