### ISSUE TITLE
如何在训练和推理中VisualDL可视化图片过程，如何配置

### ISSUE THREAD

**Issue by xupengao** [PaddlePaddle/PaddleDetection#3276]
目前用VisualDL只能训练时可视化loss和map曲线吗，我看infer,py时可以参数配置VisualDL logging directory for image，但是我运行后，visualdl网也打开不显示结果，是空白的。我检查是有保存下来的log文件的，但是没有可视化的图片结果

**Comment by jerrywgz** [comment]
我这边测试visualdl是可以正确显示的
![image](https://user-images.githubusercontent.com/22989727/120956437-1f52d780-c786-11eb-9769-587f9fe8fc52.png)
可以确认下visualdl的端口设置是否正确，以及是否增加了--use_vdl=True的命令。在infer完成之后，默认会在vdl_log_dir/image/ 下生成文件
