### ISSUE TITLE
paddle2.1 windows下训练完JDE模型保存模型出错

### ISSUE THREAD

**Issue by xdg2016** [PaddlePaddle/PaddleDetection#3277]
![image](https://user-images.githubusercontent.com/16351823/120750371-d65a1380-c538-11eb-807a-e88acf9f2fd7.png)
如图，训练完第一个epoch,保存模型的时候提示 memory error,查看了下保存路径：
![image](https://user-images.githubusercontent.com/16351823/120750509-0dc8c000-c539-11eb-9d8e-0c7f621a0839.png)
文件夹已经新建，模型保存了37.9M，突然中断，请问什么情况会出现这种错误

**Comment by nemonameless** [comment]
看起来可能是机器环境问题，请提供运行命令和环境版本等信息以便我们复现您提的问题。

**Comment by xdg2016** [comment]
查到了原因，后台运行了一个很占内存的软件，导致保存模型时内存不足，所以提示 memory error。关掉了其他程序，重新训练就可以保存了
