### ISSUE TITLE
尝试训练farimot时错误

### ISSUE THREAD

**Issue by Mr-ind1fferent** [PaddlePaddle/PaddleDetection#3278]
![image](https://user-images.githubusercontent.com/74087260/120755186-3607ed00-c540-11eb-9930-32d2bc05e5d1.png)

**Comment by nemonameless** [comment]
您好，我们这边亲测可以训练
```
单卡训：
CUDA_VISIBLE_DEVICES=0 python tools/train.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml
多卡训:
python -m paddle.distributed.launch --log_dir=./log/ --gpus 0,1 tools/train.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml
```
请git clone release/2.1分支的最新代码试试，以及请提供运行命令和环境版本等信息以便我们复现您提的问题。

**Comment by Mr-ind1fferent** [comment]
> 您好，我们这边亲测可以训练
> 
> ```
> 单卡训：
> CUDA_VISIBLE_DEVICES=0 python tools/train.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml
> 多卡训:
> python -m paddle.distributed.launch --log_dir=./log/ --gpus 0,1 tools/train.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml
> ```
> 
> 请git clone release/2.1分支的最新代码试试，以及请提供运行命令和环境版本等信息以便我们复现您提的问题。

![image](https://user-images.githubusercontent.com/74087260/120790874-12f03400-c566-11eb-98e6-5c0c5f601ee4.png)

**Comment by Mr-ind1fferent** [comment]
> > 您好，我们这边亲测可以训练
> > ```
> > 单卡训：
> > CUDA_VISIBLE_DEVICES=0 python tools/train.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml
> > 多卡训:
> > python -m paddle.distributed.launch --log_dir=./log/ --gpus 0,1 tools/train.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请git clone release/2.1分支的最新代码试试，以及请提供运行命令和环境版本等信息以便我们复现您提的问题。
> 
> ![image](https://user-images.githubusercontent.com/74087260/120790874-12f03400-c566-11eb-98e6-5c0c5f601ee4.png)

python tools/train.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml
这个是运行命令，python3.7

**Comment by zouzhuo777** [comment]
请问你这个问题解决了吗，我在aistudio上用FairMOT训练MOT20数据集，也出现了这个问题。
paddledet是2.1.0

**Comment by Mr-ind1fferent** [comment]
> 请问你这个问题解决了吗，我在aistudio上用FairMOT训练MOT20数据集，也出现了这个问题。
> paddledet是2.1.0

我本地没解决，但是aistudio可以跑，完全一样的环境，我发现了在yml文件下，对应的不一样，同样是我git clone的

**Comment by nemonameless** [comment]
> > 请问你这个问题解决了吗，我在aistudio上用FairMOT训练MOT20数据集，也出现了这个问题。
> > paddledet是2.1.0
> 
> 我本地没解决，但是aistudio可以跑，完全一样的环境，我发现了在yml文件下，对应的不一样，同样是我git clone的

请使用git clone这样能保持实时最新的代码，之前pip install上传的那个包可能会有点小的差异
