### ISSUE TITLE
how can I change the backbone ?

### ISSUE THREAD

**Issue by 2hyes** [PaddlePaddle/PaddleDetection#3281]
MOT>
how can I change the backbone ? 
Because I want to test the performance and FPS of the FairMot and DeepSort on the same backbone.

**Comment by jerrywgz** [comment]
FairMot allows the backbone of DLA34 only and DeepSort could fit for any detector. Now we plan to release the CenterNet in FairMot and deploy code for MOT models on next version.

**Comment by nemonameless** [comment]
> MOT>
> how can I change the backbone ?
> Because I want to test the performance and FPS of the FairMot and DeepSort on the same backbone.

DeepSort support load yolov3 and reid model at the same time, see `configs/mot/deepsort/deepsort_yolov3_pcb_pyramid_r101.yml`, you can test the performance and FPS of the JDE and DeepSort on the same backbone now.
