### ISSUE TITLE
如何处理DOTA数据集

### ISSUE THREAD

**Issue by Becomebright** [PaddlePaddle/PaddleDetection#3288]
您好，请问是否有现成的脚本，可以从DOTA标注得到训练 s2anet 所需的 trainval_split/s2anet_trainval_paddle_coco.json ？

**Comment by liuhuiCNN** [comment]
develop中增加了脚本：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/dataset/dota_coco/dota_to_coco.py

**Comment by Becomebright** [comment]
> develop中增加了脚本：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/dataset/dota_coco/dota_to_coco.py

该脚本得到的json文件包含 'category_id' 和 'bbox' 两个字段 (113-124行)，但 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/dota/s2anet_conv_1x_dota.yml 第9行 `data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_rbox']` 中是 gt_bbox, gt_rbox 和 gt_class，为什么这样呢？

**Comment by liuhuiCNN** [comment]
> gt_bbox, gt_rbox 和 gt_clas

两者不影响，data_fields是训练时需要准备的字段。确切的说，dota数据集训练的时候需要gt_rbox，并不需要gt_bbox，但是营部影响训练。
