### ISSUE TITLE
训练中图像大小的问题，一直提示以下内容The actual image width: 3000 is not equal to the width: 4000.0 in annotation, and update sample['w'] by actual image width.

### ISSUE THREAD

**Issue by meng8407** [PaddlePaddle/PaddleDetection#3290]
感谢paddledetection让我的训练方便很多，我有些问题请教
1，The actual image width: 3000 is not equal to the width: 4000.0 in annotation, and update sample['w'] by actual image width.
2， DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  "image height.".format(im.shape[0], sample['h']))

![2021-06-04 19-36-14屏幕截图](https://user-images.githubusercontent.com/69879311/120882783-7765ce80-c60c-11eb-8ce1-704d19707c07.png)

问题，这些提示不停在终端打印，影响我的训练进度，我怎么清楚这些提示，需要在提前将图像处理成统一尺寸吗？paddledetection送入图像尺寸应该是多大？
期待回复！！

**Comment by yghstill** [comment]
@meng8407 就是你的实际图像尺寸和你标注文件中w、h不一致，可以重新输出一下标注文件，让实际图片尺寸和标注文件中匹配

**Comment by meng8407** [comment]
> @meng8407 就是你的实际图像尺寸和你标注文件中w、h不一致，可以重新输出一下标注文件，让实际图片尺寸和标注文件中匹配

您好,针对您的回答，我做了测试，同样的数据集，在aistudio上训练就不会出现这种提示，是我物理机在装环境种出现的问题吗？我应该怎么修改。

**Comment by meng8407** [comment]
![b3504fe86b7b918f28f8aec3ebda5e2](https://user-images.githubusercontent.com/69879311/121331926-ec594100-c949-11eb-92c7-40a590cc72d0.png)
这是在aistudio上训练的截图，这个就不会提示The actual image width: 3000 is not equal to the width: 4000.0 in annotation, and update sample['w'] by actual image width.

**Comment by yghstill** [comment]
@meng8407 aistudio上和本地环境不太一样，这个只是警告，会将image width修改成真实的size，但最好建议你修改标注文件为正确的。

**Comment by CrazyStone6** [comment]
我也碰到了这种情况，不过我标注文件上的图片大小明明和图片实际大小一一样的呀，他也出现这种警告

**Comment by leyiwang** [comment]
+1
