### ISSUE TITLE
使用tools中的x2coco.py进行voc转coco时出错

### ISSUE THREAD

**Issue by RhythmF** [PaddlePaddle/PaddleDetection#3294]
输入与报错如下，有没有大佬帮我看一下

(base) PS F:\pd\PaddleDetection> python tools/x2coco.py \
>>         --dataset_type voc \
>>         --voc_anno_dir dataset/VOCdevkit/VOC2007/Annotations/ \
>>         --voc_anno_list dataset/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt \
>>         --voc_label_list dataset/voc/label_list.txt \
>>         --voc_out_name voc_train.json

所在位置 行:2 字符: 11
+         --dataset_type voc \
+           ~
一元运算符“--”后面缺少表达式。
所在位置 行:2 字符: 11
+         --dataset_type voc \
+           ~~~~~~~~~~~~
表达式或语句中包含意外的标记“dataset_type”。
所在位置 行:3 字符: 11
+         --voc_anno_dir dataset/VOCdevkit/VOC2007/Annotations/ \
+           ~
一元运算符“--”后面缺少表达式。
所在位置 行:3 字符: 11
+         --voc_anno_dir dataset/VOCdevkit/VOC2007/Annotations/ \
+           ~~~~~~~~~~~~
表达式或语句中包含意外的标记“voc_anno_dir”。
所在位置 行:4 字符: 11
+         --voc_anno_list dataset/VOCdevkit/VOC2007/ImageSets/Main/trai ...
+           ~
一元运算符“--”后面缺少表达式。
所在位置 行:4 字符: 11
+         --voc_anno_list dataset/VOCdevkit/VOC2007/ImageSets/Main/trai ...
+           ~~~~~~~~~~~~~
表达式或语句中包含意外的标记“voc_anno_list”。
所在位置 行:5 字符: 11
+         --voc_label_list dataset/voc/label_list.txt \
+           ~
一元运算符“--”后面缺少表达式。
所在位置 行:5 字符: 11
+         --voc_label_list dataset/voc/label_list.txt \
+           ~~~~~~~~~~~~~~
表达式或语句中包含意外的标记“voc_label_list”。
所在位置 行:6 字符: 11
+         --voc_out_name voc_train.json
+           ~
一元运算符“--”后面缺少表达式。
所在位置 行:6 字符: 11
+         --voc_out_name voc_train.json
+           ~~~~~~~~~~~~
表达式或语句中包含意外的标记“voc_out_name”。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

**Comment by liuhuiCNN** [comment]
您好，请问您用的是release2.1版本吗？release2.1版本是正常的，请您检查一下各个参数是否正确。请注意voc_anno_list参数给的是id的list，建议您打印一下中间结果调试一下。
