### ISSUE TITLE
solov2 infer单张图片耗时700多毫秒其中loader耗时300多毫秒，啥意思，loader都做了啥操作？

### ISSUE THREAD

**Issue by fdong0598** [PaddlePaddle/PaddleDetection#3295]
![image](https://user-images.githubusercontent.com/37216947/120920940-e407c880-c6f3-11eb-9d03-c0276580218f.png)
![image](https://user-images.githubusercontent.com/37216947/120920991-14e7fd80-c6f4-11eb-9ad0-8d545ea5caf2.png)

**Comment by yghstill** [comment]
@Fei-dong 使用tools/infer评估有初始化等耗时，计算结果有偏差，如果想计算预处理、inference、后处理分别的耗时，请使用预测部署脚本测试deploy/python/infer.py，https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/python 同时设置`--run_benchmark=True`计算的更准确.
