### ISSUE TITLE
数据增广

### ISSUE THREAD

**Issue by sxlyiyiyi** [PaddlePaddle/PaddleDetection#3296]
PaddleDetection/ppdet/data/transform/operators.py

hue (list): hue settings. in [lower, upper, probability] format.        
saturation (list): saturation settings. in [lower, upper, probability] format.        
contrast (list): contrast settings. in [lower, upper, probability] format.        
brightness (list): brightness settings. in [lower, upper, probability] format.
随机数据增广概率的设定是不是应该理解为发生的概率？
def apply_hue(self, img):       
    low, high, prob = self.hue        
    if np.random.uniform(0., 1.) < prob:            
         return img
但是代码中似乎是不发生的概率

**Comment by sxlyiyiyi** [comment]
而且里面实现的逻辑很奇怪，例如lower和upper，用图像直接乘delta，这就会出现全为0的图像，
例如：
delta = np.random.uniform(low, high)
img = img.astype(np.float32)
img *= delta

**Comment by sxlyiyiyi** [comment]
亮度，对比度等的实现是不是有问题，这不是会出现全为0的图像吗，
low 和 high的定义是不是在原图的基础上增加或减少这些值，例如img *= (1 + delta)
delta = np.random.uniform(low, high)
        img = img.astype(np.float32)
        img *= delta

**Comment by liuhuiCNN** [comment]
(1) hue中概率是不发生的概率；（2）设置low high参数时可以通过设置合理参数避免您提到的情况。
