### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by ANewAnonymous** [PaddlePaddle/PaddleDetection#3298]
使用pyinstaller打包后发现程序目录下生成了paddle/fluid/core_avx.pyd文件，发现该文件大小为1.23GB。这实在是太大了  是否有缩减的方法

**Comment by liuhuiCNN** [comment]
这个是paddle生成的，文件大小是正常的，您可以参考下文档： https://docs.nvidia.com/cuda/cuda-binary-utilities/#nvprune
