### ISSUE TITLE
HRNet + detector 检测联合部署推理出错, im_channel = im.shape[2] IndexError: tuple index out of range

### ISSUE THREAD

**Issue by ko440124** [PaddlePaddle/PaddleDetection#3299]
使用HigherHRnet infer成功。
转向HRNet + PPyolo联合部署时报错，主要步骤为:
1.导出ppyolo模型至 output_inference/ppyolo_r50vd_dcn_2x_coco/
2.导出hrnet模型至 output_inference/hrnet_w32_384x288/
3.运行 
`CUDA_VISIBLE_DEVICES=0 python deploy/python/keypoint_det_unite_infer.py --det_model_dir=output_inference/ppyolo_r50vd_dcn_2x_coco/ --keypoint_model_dir=output_inference/hrnet_w32_384x288/ --image_file=/home/chill/software/data_set/赛道2/2_images/0bf7b300_17c7_41e1_a4b4_1eac741e9adb.JPG --use_gpu=True`
出错
`-----------  Running Arguments -----------
camera_id: -1
cpu_threads: 1
det_model_dir: output_inference/ppyolo_r50vd_dcn_2x_coco/
det_threshold: 0.5
enable_mkldnn: False
image_dir: None
image_file: /home/chill/software/data_set/赛道2/2_images/0bf7b300_17c7_41e1_a4b4_1eac741e9adb.JPG
keypoint_model_dir: output_inference/hrnet_w32_384x288/
keypoint_threshold: 0.5
output_dir: output
run_benchmark: False
run_mode: fluid
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dynamic_shape: False
use_gpu: True
video_file: None
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
I0607 00:42:55.259429  4738 analysis_config.cc:424] use_dlnne_:0
I0607 00:42:55.259465  4738 analysis_config.cc:424] use_dlnne_:0
I0607 00:42:55.259479  4738 analysis_config.cc:424] use_dlnne_:0
I0607 00:42:55.259490  4738 analysis_config.cc:424] use_dlnne_:0
-----------  Model Configuration -----------
Model Arch: HRNet
Transform Order: 
--transform op: TopDownEvalAffine
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
Traceback (most recent call last):
  File "deploy/python/keypoint_det_unite_infer.py", line 199, in <module>
    main()
  File "deploy/python/keypoint_det_unite_infer.py", line 190, in main
    topdown_unite_predict(detector, topdown_keypoint_detector, img_list)
  File "deploy/python/keypoint_det_unite_infer.py", line 71, in topdown_unite_predict
    results = detector.predict(image, FLAGS.det_threshold)
  File "/home/chill/.local/share/Trash/files/PaddleDetection1/deploy/python/infer.py", line 140, in predict
    inputs = self.preprocess(image_list)
  File "/home/chill/.local/share/Trash/files/PaddleDetection1/deploy/python/infer.py", line 99, in preprocess
    im, im_info = preprocess(im_path, preprocess_ops,
  File "/home/chill/.local/share/Trash/files/PaddleDetection1/deploy/python/preprocess.py", line 218, in preprocess
    im, im_info = operator(im, im_info)
  File "/home/chill/.local/share/Trash/files/PaddleDetection1/deploy/python/preprocess.py", line 72, in __call__
    im_channel = im.shape[2]
IndexError: tuple index out of range`

传入--img_file，或是--img_dir均发生同样错误。不知道是不是导出模型步骤有误？导出模型使用的代码如下：
1. 
`python tools/export_model.py -c configs/ppyolo/ppyolo_r50vd_dcn_2x_coco.yml -o weights=/home/chill/software/PaddleDetection/output_inference/model_final.pdparams`

2.
` python tools/export_model.py -c /home/chill/software/PaddleDetection/output_inference/hrnet_w32_384x288.yml -o weights=/home/chill/software/PaddleDetection/output_inference/hrnet_w32_384x288.pdparams`

均提示`ppdet.engine INFO: Export model and saved in xxx`

**Comment by zhiboniu** [comment]
results = detector.predict(image, FLAGS.det_threshold)
这行改成results = detector.predict([image], FLAGS.det_threshold)试一下，这里有过改动

**Comment by ko440124** [comment]
> results = detector.predict(image, FLAGS.det_threshold)
> 这行改成results = detector.predict([image], FLAGS.det_threshold)试一下，这里有过改动

这样改确实有效
