### ISSUE TITLE
是否可以进行文档 证件类的四点或者多点检测？

### ISSUE THREAD

**Issue by bikerr** [PaddlePaddle/PaddleDetection#3300]

**Comment by wangxinxin08** [comment]
可以具体描述下你的问题？如果只是检测出举行物体的四个顶点，可以考虑检测算法，如果要检测数物体的多个关键点可以考虑关键点的算法

**Comment by bikerr** [comment]
> 可以具体描述下你的问题？如果只是检测出举行物体的四个顶点，可以考虑检测算法，如果要检测数物体的多个关键点可以考虑关键点的算法

@wangxinxin08  文档证件类的四个顶点的检测  你说的检测算法主要是哪个呢？

**Comment by wangxinxin08** [comment]
如果是矩形框，PaddleDection中的大多数算法都能满足你的需求，你可以根据实际情况选用

**Comment by TinyQi** [comment]
@wangxinxin08 主要有些证件存在旋转或者透视变换的效果，不是矩形框和旋转矩形框的算法都不太好，我也想着用关键点检测，不知道方案可行嘛

**Comment by Dandelion111** [comment]
> @wangxinxin08 主要有些证件存在旋转或者透视变换的效果，不是矩形框和旋转矩形框的算法都不太好，我也想着用关键点检测，不知道方案可行嘛

大佬，用什么办法解决的
