### ISSUE TITLE
调整学习率和迭代次数的文档地址找不到了。

### ISSUE THREAD

**Issue by ulanbator** [PaddlePaddle/PaddleDetection#3304]
(https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/FAQ.md)调整学习率和迭代次数。

**Comment by wangxinxin08** [comment]
可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/FAQ.md 或者https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/docs/FAQ.md

**Comment by ulanbator** [comment]
谢谢！
