### ISSUE TITLE
文档bug

### ISSUE THREAD

**Issue by xmy0916** [PaddlePaddle/PaddleDetection#3305]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/docs/featured_model/LARGE_SCALE_DET_MODEL.md
这个链接下面的配置文件链接全挂了~

**Comment by wangxinxin08** [comment]
感谢你的反馈，我们马上修复下

**Comment by wangxinxin08** [comment]
fixed by https://github.com/PaddlePaddle/PaddleDetection/pull/3318
