### ISSUE TITLE
说明文档问题

### ISSUE THREAD

**Issue by wzwb** [PaddlePaddle/PaddleDetection#3309]
您好，2.0rc版本的rcnn说明文档格式好像还是老版本的，其中的类别数是不是应该写成不带背景的数量，按照您的文档写的加上背景（81）测试的时候会出现问题。

**Comment by lyuwenyu** [comment]
- 好的 多谢建议

ps. 建议之后都用新版本 -.-

**Comment by wzwb** [comment]
嗯嗯，就是想用dygraph中的版本，但是打开对应的说明文档格式都对不上。

**Comment by lyuwenyu** [comment]
> 嗯嗯，就是想用dygraph中的版本，但是打开对应的说明文档格式都对不上。

嗯现在release/2.1默认就是dygraph的

**Comment by wzwb** [comment]
嗯，我用的是2.0-rc里面的rcnn说明文档跟dygraph中的yml文件格式不太一样



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月8日(星期二) 下午4:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] 说明文档问题 (#3309)





  
嗯嗯，就是想用dygraph中的版本，但是打开对应的说明文档格式都对不上。
  
嗯现在release/2.1默认就是dygraph的
