### ISSUE TITLE
Hybrid Task RCNN需要的semantic数据有生成的api吗？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleDetection#3312]
目前数据集中有bbox和segmentation
{
            "segmentation": [
                [
                    416.6666666666667,
                    299.6666666666667,
                    408.6666666666667,
                    309.6666666666667,
                    411.3333333333333,
                    316.3333333333333,
                    412.0,
                    329.0,
                    419.3333333333333,
                    327.6666666666667,
                    422.0,
                    317.6666666666667,
                    425.3333333333333,
                    309.0
                ]
            ],
            "iscrowd": 0,
            "image_id": 470,
            "bbox": [
                408.0,
                299.0,
                17.0,
                30.0
            ],
            "area": 510.0,
            "category_id": 4,
            "id": 2734
        }

**Comment by lyuwenyu** [comment]
- 你说的`semantic` 是指 `binary mask` 嘛

- 可以使用Coco的API
```python
annids = coco.getAnnIds()
anns = coco.loadAnns(annids)
mask = coco.annToMask(anns[0])
```

**Comment by bbbxixixixi** [comment]
> * 你说的`semantic` 是指 `binary mask` 嘛
> * 可以使用Coco的API
> 
> ```python
> annids = coco.getAnnIds()
> anns = coco.loadAnns(annids)
> mask = coco.annToMask(anns[0])
> ```

不是这个，而是HybridTaskCascade训练时需要的stuffthingmaps，长下图这样，每张图片对应一个stuffthingmaps
![20200314113931187](https://user-images.githubusercontent.com/24725986/121118874-33154100-c84d-11eb-8d67-0c9903cb7632.png)

**Comment by lyuwenyu** [comment]
- 这个可以认为是多个binary-mask合在一起的<不同的class 对应不同的非0值 加在一起就可以 可视化时不同值对应不同的cmap>
- paddledet暂时没有这样的接口
- 可以去paddleseg问问
  - https://github.com/PaddlePaddle/PaddleSeg

**Comment by bbbxixixixi** [comment]
> * 这个可以认为是多个binary-mask合在一起的<不同的class 对应不同的非0值 加在一起就可以 可视化时不同值对应不同的cmap>
> * paddledet暂时没有这样的接口
> * 可以去paddleseg问问
>   
>   * https://github.com/PaddlePaddle/PaddleSeg
写了个简单的函数解决了这个问题
coco = COCO(anno_file_path)
annids = coco.getAnnIds()
anns = coco.loadAnns(annids)
imgids = coco.getImgIds()
imgid2annos = {}
for im_id in imgids:
    imgid2annos[im_id] = []
for anno in anns:
    imgid2annos[anno['image_id']].append(anno)

for im_id in imgids:
    target_anns = imgid2annos[im_id]
    img_info = coco.loadImgs([im_id])[0]
    height, width, im_fname = img_info['height'], img_info['width'], img_info['file_name']
    stuff = np.zeros((height, width))
    for anno in target_anns:
        cate_id = anno['category_id']
        mask = coco.annToMask(anno)
        stuff[np.where(mask == 1)] = cate_id
    cv.imwrite(os.path.join(target_dir, im_fname[:-3] + 'png'), stuff)

同时又发现了另一个问题
我用的是master分支
在eval阶段，tools/train.py中，HybridTaskCascade是拿不到resolution的，这会导致下面的eval_run报异常
  if FLAGS.eval:
      # evaluation
      resolution = None
      if 'Mask' in cfg.architecture:
          resolution = model.mask_head.resolution
