### ISSUE TITLE
请问如何通过统计得到的bbox信息（宽高比，大小，类别）来调整fpn，使得检测结果更加准确？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleDetection#3315]
以常见的FPNRPNHead为例
FPNRPNHead:
  anchor_generator:
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 32
  min_level: 2
  max_level: 6
  num_chan: 256
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_positive_overlap: 0.7
    rpn_negative_overlap: 0.3
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 2000
    post_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 1000
    post_nms_top_n: 1000

假设gt bbox的宽高比集中在1：5和5：1，其他也有少部分分布，并且2：1的很少，那aspect_ratios是不是就可以改成 [0.2, 0.5, 1.0,  5]这样？
如果gt bbox的大小普遍集中在·6*6到128*128，为了减少其他大小的检测框（如256*256），该如何设置FPNRPNHead？

**Comment by lyuwenyu** [comment]
- 如果bbox分布有比较集中的统计特征 可以按照你说的调整aspect_ratios 
- anchor的大小 可以通过 anchor_sizes 调整

**Comment by bbbxixixixi** [comment]
> * 如果bbox分布有比较集中的统计特征 可以按照你说的调整aspect_ratios
> * anchor的大小 可以通过 anchor_sizes 调整

这个anchor_sizes 的大小映射到原图的大小之间有什么计算公式吗？比如anchor_sizes 32，对应到输入原图是多少？

**Comment by lyuwenyu** [comment]
- 这里的size就是对应输入的尺寸
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/modeling/proposal_generator/anchor_generator.py#L67
