### ISSUE TITLE
配置文件问题

### ISSUE THREAD

**Issue by xmy0916** [PaddlePaddle/PaddleDetection#3317]
ppyolov2的配置文件：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml#L9
这里有一个snapshot_epoch。
在runtime.yml里面：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/runtime.yml#L4
这里也有一个snapshot_epoch。

感觉有点乱。到底用的哪个呢？还是两个不一样的作用？

**Comment by lyuwenyu** [comment]
- 后出现的snapshot_epoch起作用 <这个例子就是ppyolov2里的> 
- 框架的逻辑是 
  - 同一级别的参数 后出现的覆盖之前的
  - 这个例子可以认为`runtime.yml`里的是默认的公用的  如果想要修改在自己的配置文件yml里重新写就行了
