### ISSUE TITLE
想问一下paddleDetection 2.0版本可以infer的时候只输出.json文件而不需要可视化吗

### ISSUE THREAD

**Issue by shen-wenxin** [PaddlePaddle/PaddleDetection#3320]
如题，我半年前用过paddleDetection 2.0训练过一些模型
现在想在其基础上接着训练
但是我现在想要infer img的时候，output文件夹里只输出了可视化后的图片
然而我想要的是.json格式的输出文件
请问有什么办法实现吗

**Comment by lyuwenyu** [comment]
1. 建议迁移到最新版本
2. 如果老版本不支持的话 可以在trainer里 predict添加你想要的实现 https://github.com/PaddlePaddle/PaddleDetection/blob/457f649abaad14809ad344269f982bf00cc752b4/ppdet/engine/trainer.py#L390
