### ISSUE TITLE
模型在训练过程中评估时会报错，修改bachsize==1,报错为图1，其他为图2，paddle 版本2.1.0

### ISSUE THREAD

**Issue by liuwenhua6666** [PaddlePaddle/PaddleDetection#3323]
![image](https://user-images.githubusercontent.com/58496976/121132581-e5580300-c863-11eb-91a4-fc689ef00f43.png)
![image](https://user-images.githubusercontent.com/58496976/121132631-f43eb580-c863-11eb-89b5-91944d2384b5.png)

**Comment by lyuwenyu** [comment]
问题1. 可以使用develop分支 这个问题已经修复了
问题2. 参考 https://github.com/PaddlePaddle/PaddleDetection/issues/3225
