### ISSUE TITLE
模型在边训练边评估时报错。paddlepaddle==2.0.0 paddleDetection==2.0.0

### ISSUE THREAD

**Issue by VJoer** [PaddlePaddle/PaddleDetection#3324]
在跑完第一轮训练后进入验证就会出现这样的错误
![image](https://user-images.githubusercontent.com/41233036/121143901-163e3500-c870-11eb-869a-f7c61502a790.png)
这是我的配置文件参数
![image](https://user-images.githubusercontent.com/41233036/121144644-c449df00-c870-11eb-8dd1-3bbd0510c236.png)
![image](https://user-images.githubusercontent.com/41233036/121144706-d3c92800-c870-11eb-93b1-b6d7151dccc6.png)
![image](https://user-images.githubusercontent.com/41233036/121144814-eb081580-c870-11eb-9509-c3cceeff96af.png)
![image](https://user-images.githubusercontent.com/41233036/121144984-13900f80-c871-11eb-8a2b-0d05ff53a71f.png)
![image](https://user-images.githubusercontent.com/41233036/121145047-260a4900-c871-11eb-8e44-61fb9bc5d815.png)

**Comment by lyuwenyu** [comment]
- 单独eval会报错嘛？ 是自己的数据集嘛 检查一下数据生成是否正确
![image](https://user-images.githubusercontent.com/17582080/121144917-02df9980-c871-11eb-9ab3-6a51f87f2275.png)

ps. 建议都升级到2.1

**Comment by VJoer** [comment]
> * 单独eval会报错嘛？ 是自己的数据集嘛 检查一下数据生成是否正确
>   ![image](https://user-images.githubusercontent.com/17582080/121144917-02df9980-c871-11eb-9ab3-6a51f87f2275.png)
> 
> ps. 建议都升级到2.1

数据集是使用labelme自己标注的，再用x2coco.py生成coco格式的数据集，请问如何检查数据集是否转化错误？
单独eval也会报错
![image](https://user-images.githubusercontent.com/41233036/121146809-df1d5300-c872-11eb-924d-ce3bd942057d.png)

**Comment by lyuwenyu** [comment]
> > * 单独eval会报错嘛？ 是自己的数据集嘛 检查一下数据生成是否正确
> >   ![image](https://user-images.githubusercontent.com/17582080/121144917-02df9980-c871-11eb-9ab3-6a51f87f2275.png)
> > 
> > ps. 建议都升级到2.1
> 
> 数据集是使用labelme自己标注的，再用x2coco.py生成coco格式的数据集，请问如何检查数据集是否转化错误？
> 单独eval也会报错
> ![image](https://user-images.githubusercontent.com/41233036/121146809-df1d5300-c872-11eb-924d-ce3bd942057d.png)

- 你的数据一共几个类别
- 如果train时候可以 你eval时候用train.json试一下

**Comment by VJoer** [comment]
> > > * 单独eval会报错嘛？ 是自己的数据集嘛 检查一下数据生成是否正确
> > >   ![image](https://user-images.githubusercontent.com/17582080/121144917-02df9980-c871-11eb-9ab3-6a51f87f2275.png)
> > > 
> > > ps. 建议都升级到2.1
> > 
> > 
> > 数据集是使用labelme自己标注的，再用x2coco.py生成coco格式的数据集，请问如何检查数据集是否转化错误？
> > 单独eval也会报错
> > ![image](https://user-images.githubusercontent.com/41233036/121146809-df1d5300-c872-11eb-924d-ce3bd942057d.png)
> 
> * 你的数据是一共几个类别
> * 如果train时候可以 你eval时候用train.json试一下

数据集一共5个类别
将eval.json换成train.json还是会报相同的错误
![image](https://user-images.githubusercontent.com/41233036/121149153-ff4e1180-c874-11eb-8393-a6dffd9a02d7.png)
![image](https://user-images.githubusercontent.com/41233036/121149352-2b699280-c875-11eb-8967-90c2382751a0.png)

**Comment by lyuwenyu** [comment]
五个类别的编号是什么

**Comment by VJoer** [comment]
使用的标签是1到5

**Comment by lyuwenyu** [comment]
改成 0-4

类别是从0开始计数的

**Comment by VJoer** [comment]
> 改成 0-4
> 
> 类别是从0开始计数的

好的，感谢

**Comment by VJoer** [comment]
你好，我使用脚本文件将labelme标注的标注改为0-4，再使用x2cool.py进行数据集格式转换，配置文件中num_classes==5，但是还是会报相同的错误
这是train.json文件中categories类别对应关系
![image](https://user-images.githubusercontent.com/41233036/121170361-b05da780-c887-11eb-8fd0-a3148d550ba9.png)

**Comment by lyuwenyu** [comment]
改id 不是改name

**Comment by VJoer** [comment]
> 改id 不是改name

这个id是x2coco.py文件自动生成的，请问要怎么修改？
还有介绍中提到CBResNet为Cascade-Faster-RCNN-CBResNet200vd-FPN模型，但是我在configs文件夹下并没有找到这个模型配置文件，请问这个模型配置文件在哪？

**Comment by lyuwenyu** [comment]
> > 改id 不是改name
> 
> 这个id是x2coco.py文件自动生成的，请问要怎么修改？
> 还有介绍中提到CBResNet为Cascade-Faster-RCNN-CBResNet200vd-FPN模型，但是我在configs文件夹下并没有找到这个模型配置文件，请问这个模型配置文件在哪？

哦好吧 我以为是你标注文件

解释的链接在哪里

**Comment by VJoer** [comment]
> 哦好吧 我以为是你标注文件
> 
> 解释的链接在哪里

[在README_cn.md文件模型概览中说明的第一点](https://github.com/PaddlePaddle/PaddleDetection#%E6%A8%A1%E5%9E%8B%E6%80%A7%E8%83%BD%E6%A6%82%E8%A7%88)

![image](https://user-images.githubusercontent.com/41233036/121313195-ba8bae80-c938-11eb-80f9-6b226eed981a.png)

**Comment by lyuwenyu** [comment]
- 不是你标注的问题 
  - 建议升级到2.1 
  - https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/metrics/json_results.py#L32
- Cascade-Faster-RCNN-CBResNet200vd-FPN
  - https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/configs/dcn/cascade_rcnn_cbr200_vd_fpn_dcnv2_nonlocal_softnms.yml

**Comment by VJoer** [comment]
> 不是你标注的问题
> * 建议升级到2.1
