### ISSUE TITLE
关于训练

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleDetection#3327]
我在aistudio上进行训练，GPU使用时间到时，我将最后一个保存的模型转移到另一个号上，想继续训练，使用-r，但是出现如下错误。
![image](https://user-images.githubusercontent.com/71364549/121157972-94083d80-c87c-11eb-9746-c9350e820116.png)

**Comment by lyuwenyu** [comment]
你转移了几个文件?  是需要<xx.pdopt 和 xx.pdparams>这两个
