### ISSUE TITLE
PP-YOLOv2 使用自定义的 VOC 数据集训练，部分 loss 指标不收敛是正常情况吗？

### ISSUE THREAD

**Issue by Nehcknarf** [PaddlePaddle/PaddleDetection#3328]
总loss在下降，cls和obj下降很快，但wh, xy, iou的loss一直在波动，没有下降的意思。
是不是因为VOC标注格式的问题？若转换为COCO格式是不是就正常了？如果不转换应该也不影响训练吧

配置文件为 ppyolov2_r50vd_dcn_voc.yml

**Comment by lyuwenyu** [comment]
数据格式不影响的训练的  保证dataset.yml里设置正确就行
