### ISSUE TITLE
PP-YOLOv3最后回归目标框是按左下角、右上角的格式输出的吗？

### ISSUE THREAD

**Issue by ulanbator** [PaddlePaddle/PaddleDetection#3330]
coco的dataset代码中对于非旋转框生成的标签是左下角和右上角，那么yolov3最后输出的也是左下角和右下角吗？
is_rbox_anno = True if len(inst['bbox']) == 5 else False
                    if is_rbox_anno:
                        xc, yc, box_w, box_h, angle = inst['bbox']
                        x1 = xc - box_w / 2.0
                        y1 = yc - box_h / 2.0
                        x2 = x1 + box_w
                        y2 = y1 + box_h
                    else:
                        x1, y1, box_w, box_h = inst['bbox']
                        x2 = x1 + box_w
                        y2 = y1 + box_h

**Comment by lyuwenyu** [comment]
- 经过`BBoxPostProcess`处理后 是的

**Comment by lyuwenyu** [comment]
是的

参考

- https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/modeling/layers.py#L465
- https://github.com/PaddlePaddle/PaddleDetection/blob/27d4a24d31c9c68160acf77eeb1b33575aed7333/ppdet/modeling/ops.py#L600
