### ISSUE TITLE
solov2训练自己的数据，训练结果显示ap为0，模型测试图像标签显示错误

### ISSUE THREAD

**Issue by ResonLee** [PaddlePaddle/PaddleDetection#3335]
在使用paddle 实现的 solov2训练自己的数据集，数据集使用labelme标注，数据类别一共5类(G、GD、GS、GJ、car)，标注的的时候同一张图像上多个同类目标物的时候，标签为（G1、G2...GD1、GD2、GD3...),
1、按文档教程，运行x2coco.py转化为coco数据结构如下
---dataset/Guarid
------annotations
---------instance_train.json
---------instance_val.json
------train
         .......jpg
------val
         .......jpg
2、在coco_instance.yml中配置如下
`metric: COCO
num_classes: 5

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/instance_train.json
    dataset_dir: dataset/Guarid
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_poly', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/instance_val.json
    dataset_dir: dataset/Guarid

TestDataset:
  !ImageFolder
    anno_path: annotations/instance_train.json`
3、训练得到的模型推理图像，显示的标签不是自定义数据库中的目标表签而是coco数据集中的标签
问题1：labelme标注的时候是不是不需要对同一张图像中的统一类目标使用类别加序号的标注方式，而只给一个统一的标签？
问题2：为什么推理图像显示的标签是coco的而不是数据集中的？该怎么做？

**Comment by yghstill** [comment]
@JackLee-Python 
1. 实例分割中类别只给统一的标签
2. TestDataset的anno_path指定你自己的标注json绝对路径

**Comment by JackLee-Python** [comment]
即是标注的时候只按G、GD、GS、GJ、car来标注，而不是多个同一类加序号？
TestDataset的anno_path指定的json文件同样也是将test数据集所有图像标签文件信息写到一个json文件中？还是说可以每张图像各自对应一个json文件？

**Comment by ResonLee** [comment]
@yghstill 
谢谢，即是标注的时候只按G、GD、GS、GJ、car来标注，而不是多个同一类加序号？
TestDataset的anno_path指定的json文件同样也是将test数据集所有图像标签文件信息写到一个json文件中？还是说可以每张图像各自对应一个json文件？

**Comment by yghstill** [comment]
@JackLee-Python (1)只按G、GD、GS、GJ、car来标注，(2)anno写到一个json文件

**Comment by ResonLee** [comment]
@yghstill 谢谢，问题已经解决了，这个训练没有详细的教程嘛？你们发布的上手教程看了很多遍，可是还有很多坑，但是上手训练这一步就是诸多波折，比如所之前用的mask-rcnn的训练标签是同类按序号分开的，直接过渡到solov2自然而然地以为是这样。

**Comment by springsha** [comment]
@JackLee-Python 
您好，请问具体的标注格式是这样的吗，我没太明白对于同一个类别中的不同实例（比如人）
{"segmentation": [[...]],
"area": 27718.476299999995,
"iscrowd": 0,
"image_id": 61471,
"bbox": [272.1,200.23,151.97,279.77],
"category_id": 1,
"id": 1773},
{
"segmentation": 
[[....]],
"area": 78969.31690000003,
"iscrowd": 0,
"image_id": 61471,
"bbox": [124.71,196.18,372.85,356.81],
"category_id": 1,
"id": 2551},
他们之间的区别是不是除了segmentation、area、bbox不同外只要保证category_id相同（都是人）id不同就可以了

**Comment by springsha** [comment]
@yghstill 请问是这样吗
