### ISSUE TITLE
FairMOT打印问题

### ISSUE THREAD

**Issue by ReverseSacle** [PaddlePaddle/PaddleDetection#3337]
看了FairMOT的相关代码，关于ppdet/engine/tracker的代码中有打印文本的代码块，但使用其预测视频时最终并未生成相应的类似于（'{frame},{id},{x1},{y1},{w},{h},1,-1,-1,-1\n'）这种格式内容的txt文件，想问下是否是并未支持打印输出功能？

**Comment by nemonameless** [comment]
> 看了FairMOT的相关代码，关于ppdet/engine/tracker的代码中有打印文本的代码块，但使用其预测视频时最终并未生成相应的类似于（'{frame},{id},{x1},{y1},{w},{h},1,-1,-1,-1\n'）这种格式内容的txt文件，想问下是否是并未支持打印输出功能？

之前考虑预测视频时，并没有把视频抽帧图片保存下来，就没有记录txt文件。后面会尽快支持。可以暂时先用eval_mot.py跑出结果(需事先抽成图片)，虽然最后由于没有gt导致MOTA指标会-inf或0，但不影响保存结果。

**Comment by ReverseSacle** [comment]
> > 看了FairMOT的相关代码，关于ppdet/engine/tracker的代码中有打印文本的代码块，但使用其预测视频时最终并未生成相应的类似于（'{frame},{id},{x1},{y1},{w},{h},1,-1,-1,-1\n'）这种格式内容的txt文件，想问下是否是并未支持打印输出功能？
> 
> 之前考虑预测视频时，并没有把视频抽帧图片保存下来，就没有记录txt文件。后面会尽快支持。可以暂时先用eval_mot.py跑出结果(需事先抽成图片)，虽然最后由于没有gt导致MOTA指标会-inf或0，但不影响保存结果。

这个抽帧图片是指预测视频后保存的图片吗？要是这个，infer_mot之后就有生成了有带框的图片集了。还有一个问题，对于eval_mot，这个能评估自己的测试集吗。试了下，就报错：丢失seqinfo.ini。这个要自己生成吗？

**Comment by nemonameless** [comment]
> > > 看了FairMOT的相关代码，关于ppdet/engine/tracker的代码中有打印文本的代码块，但使用其预测视频时最终并未生成相应的类似于（'{frame},{id},{x1},{y1},{w},{h},1,-1,-1,-1\n'）这种格式内容的txt文件，想问下是否是并未支持打印输出功能？
> > 
> > 
> > 之前考虑预测视频时，并没有把视频抽帧图片保存下来，就没有记录txt文件。后面会尽快支持。可以暂时先用eval_mot.py跑出结果(需事先抽成图片)，虽然最后由于没有gt导致MOTA指标会-inf或0，但不影响保存结果。
> 
> 这个抽帧图片是指预测视频后保存的图片吗？要是这个，infer_mot之后就有生成了有带框的图片集了。还有一个问题，对于eval_mot，这个能评估自己的测试集吗。试了下，就报错：丢失seqinfo.ini。这个要自己生成吗？

抽帧图片是指输入视频抽出来的一帧帧，写入结果txt要区分第几帧的，最好也是把图片集生成了这样更直观。可以在 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/engine/tracker.py#L369 加上
```
        self.write_mot_results(result_filename, results, data_type)
```

对于eval_mot.py，可以自制数据集，按照MOT16的目录和格式，seqinfo.ini这个仿照着MOT16的自己制作也是可以的。

**Comment by nemonameless** [comment]
已经支持infer_mot之后生成txt

**Comment by ReverseSacle** [comment]
> 已经支持infer_mot之后生成txt

今天我重新下载了paddle_detection,在百度ai studio试了下infer_mot,但结果并未生成txt。

> 已经支持infer_mot之后生成txt

已重新下载paddle_detection并在百度ai studio中测试，但并未生成txt文件。

**Comment by nemonameless** [comment]
> > 已经支持infer_mot之后生成txt
> 
> 今天我重新下载了paddle_detection,在百度ai studio试了下infer_mot,但结果并未生成txt。
> 
> > 已经支持infer_mot之后生成txt
> 
> 已重新下载paddle_detection并在百度ai studio中测试，但并未生成txt文件。

请拉取最新develop分支

**Comment by nemonameless** [comment]
请拉取最新develop分支，这个分支是会有最新改动的。也可以自行在 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/engine/tracker.py#L369 加上
```
      self.write_mot_results(result_filename, results, data_type)
```
