### ISSUE TITLE
C++部署推理时，结果中的检测框信息是循环重复的，是不是bug呢？

### ISSUE THREAD

**Issue by TinyQi** [PaddlePaddle/PaddleDetection#3339]
我在使用C++进行推理的时候，发现打印信息里的检测框的信息是循环重复的，下面我加粗的字体就是重复的，突然不能传图片了，大家将就看看吧。
(gdb) c
Continuing.
**class=0 confidence=0.9869 rect=[107 11 252 391]**
class=32 confidence=0.9356 rect=[42 357 88 400]
**class=0 confidence=0.9869 rect=[107 11 252 391]**
class=32 confidence=0.9356 rect=[42 357 88 400]
Visualized output saved as output/hrnet_demo.jpg
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0609 16:29:24.384572 41800 main.cc:59] ----------------------- Config info -----------------------
I0609 16:29:24.384702 41800 main.cc:60] runtime_device: cpu
I0609 16:29:24.384718 41800 main.cc:61] ir_optim: True
I0609 16:29:24.384738 41800 main.cc:62] enable_memory_optim: True
I0609 16:29:24.384769 41800 main.cc:69] enable_tensorrt: False
I0609 16:29:24.384788 41800 main.cc:70] precision: fp32
I0609 16:29:24.384805 41800 main.cc:72] enable_mkldnn: False
I0609 16:29:24.384819 41800 main.cc:73] cpu_math_library_num_threads: 1
I0609 16:29:24.384833 41800 main.cc:74] ----------------------- Data info -----------------------
I0609 16:29:24.384848 41800 main.cc:75] batch_size: 1
I0609 16:29:24.384862 41800 main.cc:76] input_shape: dynamic shape
I0609 16:29:24.384876 41800 main.cc:77] ----------------------- Model info -----------------------
I0609 16:29:24.384907 41800 main.cc:79] model_name: yolov3_mobilenet_v3_large_270e_coco
I0609 16:29:24.384927 41800 main.cc:80] ----------------------- Perf info ------------------------
I0609 16:29:24.384945 41800 main.cc:81] Total number of predicted data: 1 and total time spent(s): 1077
I0609 16:29:24.384959 41800 main.cc:84] preproce_time(ms): 102.682, inference_time(ms): 975.437, postprocess_time(ms): 0.052585

后来发现调试的中间信息中的结果也是循环重复的
(gdb) p result
$1 = std::vector of length 8, capacity 8 = {{rect = std::vector of length 4, capacity 4 = {**107, 11, 252, 391**}, class_id = 0, 
    confidence = 0.986944377}, {rect = std::vector of length 4, capacity 4 = {42, 357, 88, 400}, class_id = 32, 
    confidence = 0.935643971}, {rect = std::vector of length 4, capacity 4 = {**107, 11, 252, 391**}, class_id = 0, 
    confidence = 0.986944377}, {rect = std::vector of length 4, capacity 4 = {42, 357, 88, 400}, class_id = 32, 
    confidence = 0.935643971}, {rect = std::vector of length 4, capacity 4 = {**107, 11, 252, 391**}, class_id = 0, 
    confidence = 0.986944377}, {rect = std::vector of length 4, capacity 4 = {42, 357, 88, 400}, class_id = 32, 
    confidence = 0.935643971}, {rect = std::vector of length 4, capacity 4 = {**107, 11, 252, 391**}, class_id = 0, 
    confidence = 0.986944377}, {rect = std::vector of length 4, capacity 4 = {42, 357, 88, 400}, class_id = 32, 
    confidence = 0.935643971}}

**Comment by TinyQi** [comment]
@willthefrog @ZeyuChen

**Comment by liuhuiCNN** [comment]
感谢反馈，问题正在排查中。

**Comment by liuhuiCNN** [comment]
> 感谢反馈，问题正在排查中。

fix #3392
