### ISSUE TITLE
PaddleX训练的检测模型，在PaddleDetection里怎么用?

### ISSUE THREAD

**Issue by TigerKylin** [PaddlePaddle/PaddleDetection#3340]
二者的模型文件不一样，有什么转换工具吗？

**Comment by qingqing01** [comment]
@TigerKylin 请问具体是什么模型？有可能需要依据模型名字对应关系，转换下名字。没有直接的转换工具。

**Comment by TigerKylin** [comment]
@qingqing01 
FasterRCNN模型
ResNet50  backBone
做检测训练，导出模型文件夹里有：  ' ____model____'  、  '____params____'   、 ' model.yml '
![image](https://user-images.githubusercontent.com/73530861/121504693-c8aefd00-ca14-11eb-866b-e81e19a5674d.png)

这个和paddledetection用到的模型文件不一样，要怎么改名字？

> @TigerKylin 请问具体是什么模型？有可能需要依据模型名字对应关系，转换下名字。没有直接的转换工具。

**Comment by qingqing01** [comment]
@TigerKylin  您发的paddlex导出来的是给推理用的模型。您是想训练finetune，还是用PaddleDetection部署呢？

咨询了下PaddleX实现的同学，说模型结构和权重名字和PaddleDetection的静态图一致。当前PaddleX导出的模型还是静态图的格式，导出非推理的模型，在PaddleDetection里可以直接加载试下。

**Comment by TigerKylin** [comment]
> @TigerKylin 您发的paddlex导出来的是给推理用的模型。您是想训练finetune，还是用PaddleDetection部署呢？
> 
> 咨询了下PaddleX实现的同学，说模型结构和权重名字和PaddleDetection的静态图一致。当前PaddleX导出的模型还是静态图的格式，导出非推理的模型，在PaddleDetection里可以直接加载试下。

我是想直接作为推理模型，在PaddleDetection上部署。
