### ISSUE TITLE
data.transform.operators的resizeimage，参数里面resize_box默认值为false

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleDetection#3342]
图片缩放不是应该同步操作gtbbox吗？大部分配置文件中都没更改。或者后续有步骤隐式的处理过了？

**Comment by qingqing01** [comment]
@bbbxixixixi 

在静态图中是您提到这样，一些配置，有显示的配置gt bbox的normalize操作。Resize图片时就没有对gt box做normalize。

在动态图中，做了统一的处理，对图片做什么操作，对gt bbox也做什么操作。比如Resze可以参考如下:

https://github.com/PaddlePaddle/PaddleDetection/blob/27d4a24d31c9c68160acf77eeb1b33575aed7333/ppdet/data/transform/operators.py#L720
