### ISSUE TITLE
怎么获得骨干网络输出的特征图？ 

### ISSUE THREAD

**Issue by oldZhangYH** [PaddlePaddle/PaddleDetection#3348]
我看源代码是直接将data丢到model里然后返回了各种loss`outputs=model(data)`，骨干网络输出的特征图怎么获得呢？

**Comment by qingqing01** [comment]
@kekekahuatian 

需要在源码里获取，ppdet/modeling/architectures下面每类算法的主体框架里，forward()内部获取骨干网络输出的特征图，拿YOLO来说，下面 ` body_feats = self.backbone(self.inputs)` 返回就可以得到骨干网络输出的特征图。可以打印看下。

https://github.com/PaddlePaddle/PaddleDetection/blob/27d4a24d31c9c68160acf77eeb1b33575aed7333/ppdet/modeling/architectures/yolo.py#L63

**Comment by zsbjmy** [comment]
请问如何打印骨干网络输出的特征图，能具体说明调用什么方法吗？

**Comment by qingqing01** [comment]
@zsbjmy 直接print打印上面body_feats就可以了。您是想怎么打印呢？

**Comment by zsbjmy** [comment]
我想得到特征图的可视化图片

**Comment by qingqing01** [comment]
@zsbjmy 骨干网络特征图可视化，您需要从body_feats里取出，写代码可视化。

**Comment by zsbjmy** [comment]
谢谢！
