### ISSUE TITLE
S2ANet测试中发现的问题。

### ISSUE THREAD

**Issue by ZJH970922** [PaddlePaddle/PaddleDetection#3352]
我在制作数据集的时候，利用rolabelimg工具打标签，分类只有一类，在configs\datasets的yml文件中，num_classes为1。结果发现，可以进行正常训练，但是到了利用训练好的模型推理图片时，出现以下错误：

```
Traceback (most recent call last):
  File "tools/infer.py", line 158, in <module>
    main()
  File "tools/infer.py", line 154, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 132, in run
    save_txt=FLAGS.save_txt)
  File "G:\Anaconda\envs\paddle\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\engine\trainer.py", line 418, in predict
    batch_res = get_infer_results(outs, clsid2catid)
  File "G:\Anaconda\envs\paddle\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\metrics\coco_utils.py", line 50, in get_infer_results
    outs['bbox'], outs['bbox_num'], im_id, catid, bias=bias)
  File "G:\Anaconda\envs\paddle\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\metrics\json_results.py", line 58, in get_det_poly_res
    category_id = label_to_cat_id_map[int(num_id)]
KeyError: 2
```

当我利用相同数据集，在configs\datasets的yml文件中，将num_classes改为2时，依然可进行训练，并可顺利进行图片推理，但是图里输出的结果没有检测框。

**Comment by liuhuiCNN** [comment]
您好，感谢反馈，请问您数据中标签是从0开始还是从1开始的呢？

**Comment by ZJH970922** [comment]
> 您好，感谢反馈，请问您数据中标签是从0开始还是从1开始的呢？

您好，数据集的标签应该是从1开始的。
数据集的制作采用的是rolabelimg工具，生成的xml文件如下：
<annotation verified="yes">
  <folder>data</folder>
  <filename>1</filename>
  <path>G:\PaddleDetection\GIS_images\data\1.jpg</path>
  <source>
    <database>Unknown</database>
  </source>
  <size>
    <width>640</width>
    <height>480</height>
    <depth>3</depth>
  </size>
  <segmented>0</segmented>
  <object>
    <type>robndbox</type>
    <name>GIS</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <robndbox>
      <cx>268.5644</cx>
      <cy>246.901</cy>
      <w>456.0</w>
      <h>114.0</h>
      <angle>0.01</angle>
    </robndbox>
  </object>
</annotation>

转换成coco数据类型后，生成的json文件如下所示：
{
    "images": [
        {
            "file_name": "1.jpg",
            "height": 480,
            "width": 640,
            "id": 1
        }
    ],
    "type": "instances",
    "annotations": [
        {
            "area": 51984,
            "iscrowd": 0,
            "image_id": 1,
            "bbox": [
                267,
                245,
                456,
                114,
                0.01
            ],
            "category_id": 1,
            "id": 1,
            "ignore": 0,
            "segmentation": []
        }
    ],
    "categories": [
        {
            "supercategory": "none",
            "id": 1,
            "name": "GIS"
        }
    ]
}

**Comment by qingqing01** [comment]
related https://github.com/PaddlePaddle/PaddleDetection/issues/3308

**Comment by liuhuiCNN** [comment]
fix in #3401
