### ISSUE TITLE
打包后出现大量进程

### ISSUE THREAD

**Issue by ANewAnonymous** [PaddlePaddle/PaddleDetection#3353]
对ppyolov2推理程序打包后生成exe，在创建detection后，出现大量进程
打包工具:pyinstaller                      ver:4.3
paddle版本:paddlepaddle-gpu     ver:2.0.0
命令:pyinstaller -D -w sss1.py

![QQ图片20210610203448](https://user-images.githubusercontent.com/17308906/121525810-5ac20000-ca2b-11eb-9707-e8f6b3a6819d.png)
![QQ图片20210610203454](https://user-images.githubusercontent.com/17308906/121525817-5d245a00-ca2b-11eb-98ad-ffac549a37a4.png)
![QQ图片20210610203459](https://user-images.githubusercontent.com/17308906/121525830-60b7e100-ca2b-11eb-8d78-842335de2c16.png)

**Comment by qingqing01** [comment]
@ANewAnonymous 像是运行了很多次，进程没有正确退出
