### ISSUE TITLE
关于FairMOT的result问题

### ISSUE THREAD

**Issue by ReverseSacle** [PaddlePaddle/PaddleDetection#3354]
目标：在预测中输出每个被框住的人的框的置信度。想问下，FairMOT在预测时，它的result中有保存置信度吗？还是在检测部分中才有置信度，要是这样该怎样输出对应框的置信度。

**Comment by nemonameless** [comment]
> 目标：在预测中输出每个被框住的人的框的置信度。想问下，FairMOT在预测时，它的result中有保存置信度吗？还是在检测部分中才有置信度，要是这样该怎样输出对应框的置信度。

在检测部分中才有置信度，按一定阈值过滤后送入跟踪后处理的，后面这个置信度就没有用到了。近期会添加跟踪结果也输出对应框的置信度。
