### ISSUE TITLE
solov2训练map值宽幅震荡，无上升趋势，检测效果不好，检测置信度超过了偏高

### ISSUE THREAD

**Issue by ResonLee** [PaddlePaddle/PaddleDetection#3359]
windows下单卡GPU训练，batch_size=1,原图尺寸1242*2208，resize图像尺寸（640， 800）paddlepaddle 2.0.2, paddledetection2.0.0
自定义的数据，目标实例分为5类，图像数量1000张，
训练配置如下：
epoch: 36

LearningRate:
  base_lr: 0.00125
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [24, 33]
  - !LinearWarmup
    start_factor: 0.
    steps: 2000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2
map值训练如图
![image](https://user-images.githubusercontent.com/54474938/121618504-7532c280-ca99-11eb-80fe-82cf1f04e286.png)
推理效果如图
![image](https://user-images.githubusercontent.com/54474938/121618045-b4144880-ca98-11eb-8159-423596d3e1ca.png)
![image](https://user-images.githubusercontent.com/54474938/121618101-cdb59000-ca98-11eb-8128-74fa67ddbeae.png)

问题1、有什么办法能是map值收敛上升，是数据库的问题吗？之前用mask-rcnn训练效果挺好的
问题2、检测图像中目标的置信度超过1是怎么回事啊？还有第二个检测图，掩膜覆盖了整张图是把整张图像当作目标物了吗？

**Comment by yghstill** [comment]
@JackLee-Python 
1. 前几天修复了num_classes的一个小问题 #3193 ，请使用https://github.com/PaddlePaddle/PaddleDetection/tree/develop 代码，然后将https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/datasets/coco_instance.yml#L2 num_classes修改成5类，同时由于你数据集较小，建议直接加载coco训好的预训练权重https://paddledet.bj.bcebos.com/models/solov2_r50_fpn_1x_coco.pdparams
2. 置信度超过1我们再定位排查下问题，第二个检测结果中整张图都误检成了一个物体，还是模型收敛不充分的问题，再安装1中重新训练看下。
