### ISSUE TITLE
快速开始文档中多卡精度如何对齐单卡

### ISSUE THREAD

**Issue by raymondchu-z** [PaddlePaddle/PaddleDetection#3363]
版本信息：
PaddleDetection2.1，ubantu16.04，paddlepaddle_gpu-2.1.0.post101-cp36-cp36m-linux_x86_64.whl

[快速开始](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/QUICK_STARTED_cn.md)中提供了单卡的训练命令和配置，我测试后mAP=0.88，没有问题。但该文档并没有说如何多卡训练，于是我参考[30分钟快速上手PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/GETTING_STARTED_cn.md)中的说明，使用同样的配置执行8卡训练，得到mAP=0.58。
请问：1、config中的默认学习率（QUICK_STARTED_cn.md）是针对多卡还是单卡？2、使用多卡训练需要调整哪些超参数，如何调整？

同时也发现其他问题：
1、batchsize过大导致OOM后，GPU0中进程挂掉，在GPU1-7中均残留进程占用显存，需要手动kill。
2、某些情况（尚不清楚什么情况，甚至不改代码只改学习率都会出现）多卡训练正常结束后，使用GPU评估会报Segmentation fault (core dumped)。

> python tools/eval.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml -o use_gpu=trueW0611 14:56:53.741338 69167 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0611 14:56:53.745541 69167 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[06/11 14:56:59] ppdet.utils.checkpoint INFO: Finish loading model weights: output/yolov3_mobilenet_v1_roadsign/model_final.pdparams
C++ Traceback (most recent call last):
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&)
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 2ul, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, long>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, paddle::platform::complex64>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, paddle::platform::complex128> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   void paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, float>::SliceCompute<2ul>(paddle::framework::ExecutionContext const&) const
5   Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 2, 1, int>, 16, Eigen::MakePointer>, Eigen::TensorSlicingOp<Eigen::DSizes<int, 2> const, Eigen::DSizes<int, 2> const, Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, int>, 16, Eigen::MakePointer> const> const> const, Eigen::DefaultDevice, true, (Eigen::internal::TiledEvaluation)1>::run(Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 2, 1, int>, 16, Eigen::MakePointer>, Eigen::TensorSlicingOp<Eigen::DSizes<int, 2> const, Eigen::DSizes<int, 2> const, Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, int>, 16, Eigen::MakePointer> const> const> const&, Eigen::DefaultDevice const&)
6   paddle::framework::SignalHandle(char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
Error Message Summary:
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1623394619 (unix time) try "date -d @1623394619" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x4) received by PID 69167 (TID 0x7f1c746a1700) from PID 4 ***]
Segmentation fault (core dumped)

**Comment by heavengate** [comment]
1. 快速开始文档里对应的是单卡配置，如果使用多卡的话，可以对应把learning rate乘以卡数，训练的epoch数可以对应调小一些
2. OOM是cuda的error，python程序端没法捕捉并退出子进程，这个目前暂时没有其他解决办法，只能手动kill一下，其他错误或者ctrl+c一般子进程是可以退出的
3. 我本地没有复现这个segmentfault，你看下吧`configs/yolov3/_base_/yolov3_reader.yml`里`EvalReader`的batch_szie改成1试下呢

**Comment by raymondchu-z** [comment]
> 1. 快速开始文档里对应的是单卡配置，如果使用多卡的话，可以对应把learning rate乘以卡数，训练的epoch数可以对应调小一些
> 2. OOM是cuda的error，python程序端没法捕捉并退出子进程，这个目前暂时没有其他解决办法，只能手动kill一下，其他错误或者ctrl+c一般子进程是可以退出的
> 3. 我本地没有复现这个segmentfault，你看下吧`configs/yolov3/_base_/yolov3_reader.yml`里`EvalReader`的batch_szie改成1试下呢

感谢回复。
1. 请问有使用多卡训练的文档或配置文件，能达到单卡相当的精度吗？
2. 关于segmentfault，测试发现几次，只改了学习率也会报错。具体是多卡训练不报错，当单卡评估时该错误。
3. 怀疑可能是ppdet版本问题，现在用ppdet2.0.0版本试一下。请问怎么查看ppdet的版本？除了安装时的指定`pip install paddledet==2.0.0`

**Comment by heavengate** [comment]
1. 理论上来说是可以达到的，实际可能有少许波动，不过波动应该不大，0.x的样子
2. paddledet 2.1.0版本已经发布了，可以更新一下paddledet或者在develop分支`python setup.py install`安装试下

**Comment by raymondchu-z** [comment]
1. 经多次测试，8卡时，将`lr*8，warmup_step*8，epoch*2`，使用CosineDecay；这样的修改下能达到84.16%（单卡88%）。能否提供一对单卡和多卡对应的配置文件供参考？
2. 上述测试用的是paddledet 2.1.0。
3. segmentfault的报错是我修改了batchsize后没有满足`warmup_steps <= lr_decay_epochs[0] * num_steps_each_epoch`的要求。
4. 探讨一个问题：如果需要提高显存使用率（目的是提高准确率和减少训练时间），就需要增大batchsize。但是增大batchsiz导致lr需要对应增大（否则收敛慢）。lr增大会使得warmup的step不变时的初始学习率也增大，导致模型发散。此时如果增加warmup的step，也需要增加相应的epoch，来避免warmup占用的epoch过大而学习率衰减的epoch过小。这样的话，增大batchsize就需要相应增加epoch，这样还能达到节省训练时间和提高精度的目的吗？

**Comment by heavengate** [comment]
单卡变多卡将lr对应调整就可以了，`warmup`和`epoch`不需要调整，warmup的初始lr是按比例设置的，比如说0或者初始lr的`1/3`这种
