### ISSUE TITLE
C++部署paddledetection2.1和cuda10.2windows预测库 报错，搞了3天了，求助一下

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleDetection#3365]
cmake和使用vs2019编译均一切正常，最后点击main.exe什么都没有出现，也没有创建output文件夹
调试C++代码发现PaddleDetection::ObjectDetector det 这里初始化失败，卡在了下边这个函数
 bool load_config(const std::string& model_dir,
                   const std::string& cfg = "infer_cfg.yml") {
    // Load as a YAML::Node
    YAML::Node config;
    config = YAML::LoadFile(model_dir + OS_PATH_SEP + cfg);   //这里需要加载infer_cfg.yml,为什么？？？？？？？？我路径下也 
                                                                  没有这个文件啊，我把权重对应的yml文件名改成infer_cfg.yml放到对应路径下，结果还 
                                                                  是报错，报错内容包括"Please set mode, support value : fluid/trt_fp16/trt_fp32. 
                                                                  std::endl(但是实际上已经设置了fluid的）;还有Cannot open file 
                                                                   ./models/\model.pdmodel, please confirm whether the  file is normal.这是啥情况，求大神相助

**Comment by heavengate** [comment]
你好，你用的是`PaddleDetection/deploy`下的代码还是`PaddleDetection/static/deploy`下的，另外部署需要先通过`tools/export_model.py`导出模型，导出模型的时候会生成`infer_cfg.yml`的，`Cannot open file
./models/\model.pdmodel, please confirm whether the file is normal.`看着像是Windows上的目录分隔符`/`和`\`的问题，排查一下路径设置是否符合windows规范呢

**Comment by aiwenzhu** [comment]
> 你好，你用的是`PaddleDetection/deploy`下的代码还是`PaddleDetection/static/deploy`下的，另外部署需要先通过`tools/export_model.py`导出模型，导出模型的时候会生成`infer_cfg.yml`的，`Cannot open file ./models/\model.pdmodel, please confirm whether the file is normal.`看着像是Windows上的目录分隔符`/`和`\`的问题，排查一下路径设置是否符合windows规范呢

我没有用到static/deploy下的代码，我是参考readme里推荐的PaddleDetection在windows下的部署（一）这篇文章部署的，另外您说的导出模型如何操作，我看了几篇博客都是直接用下载的权重就好了，就我遇到了这个问题

**Comment by liuhuiCNN** [comment]
deploy下部署需要先导出模型，导出模型文件夹中有 infer_cfg.yml，请参考文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_MODEL.md

**Comment by aiwenzhu** [comment]
> > 你好，你用的是`PaddleDetection/deploy`下的代码还是`PaddleDetection/static/deploy`下的，另外部署需要先通过`tools/export_model.py`导出模型，导出模型的时候会生成`infer_cfg.yml`的，`Cannot open file ./models/\model.pdmodel, please confirm whether the file is normal.`看着像是Windows上的目录分隔符`/`和`\`的问题，排查一下路径设置是否符合windows规范呢
> 
> 我没有用到static/deploy下的代码，我是参考readme里推荐的PaddleDetection在windows下的部署（一）这篇文章部署的，另外您说的导出模型如何操作，我看了几篇博客都是直接用下载的权重就好了，就我遇到了这个问题

@heave
