### ISSUE TITLE
如何修改PPYOLO neck:YOLOV3FPN的结构

### ISSUE THREAD

**Issue by zsbjmy** [PaddlePaddle/PaddleDetection#3368]
YOLOv3:
  backbone: ResNet
  neck: YOLOv3FPN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess
我想在YOLOv3FPN的浅层特征与深层特征之间加入注意力机制，请问我应该修改哪些源文件？
我尝试直接修改PaddleDetection/ppdet/modeling/necks/yolo_fpn.py这个文件，但是修改的部分并没有被添加进去，请问我该怎么修改？

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/27d4a24d31c9c68160acf77eeb1b33575aed7333/configs/ppyolo/_base_/ppyolo_r50vd_dcn.yml#L9

PP-YOLO模型的neck结构是PPYOLOFPN，需要修改这个类
https://github.com/PaddlePaddle/PaddleDetection/blob/27d4a24d31c9c68160acf77eeb1b33575aed7333/ppdet/modeling/necks/yolo_fpn.py#L532
