### ISSUE TITLE
如何使用PaddleDetection实时预测摄像头输入视频流？

### ISSUE THREAD

**Issue by vincentpengpeng** [PaddlePaddle/PaddleDetection#337]
基于yolov3框架训练好模型，能成功使用
python -u tools/infer.py -c configs/yolov3_mobilenet_v1_fruit.yml -o weights=output/yolov3_mobilenet_v1_fruit/best_model --infer_img=demo/orange_71.jpg
进行预测单个图片文件。
但是infer.py文件输入参数需要为文件路径或者文件夹路径，如何使用训练好的模型，对cv2实时捕获的视频帧进行预测。

**Comment by qingqing01** [comment]
@vincentpengpeng 目前没有直接提供针对视频的预测，需要自己改下代码，读取视频的每一帧预测，然后再合成。  我们最近也在加强这块，后续会提供视频流的预测。

**Comment by vincentpengpeng** [comment]
> @vincentpengpeng 目前没有直接提供针对视频的预测，需要自己改下代码，读取视频的每一帧预测，然后再合成。 我们最近也在加强这块，后续会提供视频流的预测。

你好，我现在改为将CV2捕获的每一帧，先保存为图片，再使用Infer.py进行读取预测，但是效率会非常低，能否提供一些样例，在infer.py文件中，如何修改，将cv2截取的图片直接送入模型进行预测。

**Comment by sjtubinlong** [comment]
@vincentpengpeng 你好，可以参考下我们之前做的视频预测口罩人脸的预测代码，https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.5/demo/mask_detection/python

整个预测逻辑和PaddleDetection是类似的，代码都在infer.py里面，可以参考以下。

另外，PaddleDetection的预测近期回增加视频流的支持。

**Comment by byq-luo** [comment]
> @vincentpengpeng 你好，可以参考下我们之前做的视频预测口罩人脸的预测代码，https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.5/demo/mask_detection/python
> 
> 整个预测逻辑和PaddleDetection是类似的，代码都在infer.py里面，可以参考以下。
> 
> 其中 `predict_video`函数示范了获取视频帧做检测加上检测框再合成新视频的过程。
> 
> 另外，PaddleDetection的预测近期回增加视频流的支持。

视频流的支持是不是还没有增加？

**Comment by qingqing01** [comment]
@byq-luo  可以参考这里 https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/deploy  支持输入是视频的预测

**Comment by qingqing01** [comment]
@byq-luo 已提供文档说明
