### ISSUE TITLE
关于 2.1.0 gt 处理

### ISSUE THREAD

**Issue by FL77N** [PaddlePaddle/PaddleDetection#3375]
你好，我注意到 PadBatch 是去除了 pad_gt，那这个操作是被移到了其他地方，还是整体去除了呢？如果是去除了，我们现在新版本有其他替代的操作吗？谢谢

**Comment by jerrywgz** [comment]
新版本整体去除了pad_gt字段，在预处理操作中默认对sample中的gt字段进行pad

**Comment by FL77N** [comment]
> 新版本整体去除了pad_gt字段，在预处理操作中默认对sample中的gt字段进行pad

3QU

**Comment by FL77N** [comment]
> 新版本整体去除了pad_gt字段，在预处理操作中默认对sample中的gt字段进行pad

您好，可以指一下在哪段代码吗

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/data/transform/batch_operators.py#L41 可以参考这里

**Comment by FL77N** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/data/transform/batch_operators.py#L41 可以参考这里

您好，这里面只有对 img 进行 pad 的代码，没看到对 gt 进行 pad 的呀

**Comment by jerrywgz** [comment]
在PadBatch中只会对每张图内的gt做pad，同时将图片pad到stride的整倍数。在RCNN中，每张图的gt_box个数不同时，会直接以list的方式返回每张图的gt_box。在YOLO中，会首先使用[PadBox](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/data/transform/operators.py#L1702) 将gt_box pad到固定个数

**Comment by FL77N** [comment]
> 在PadBatch中只会对每张图内的gt做pad，同时将图片pad到stride的整倍数。在RCNN中，每张图的gt_box个数不同时，会直接以list的方式返回每张图的gt_box。在YOLO中，会首先使用[PadBox](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/data/transform/operators.py#L1702) 将gt_box pad到固定个数

懂了，谢谢你
