### ISSUE TITLE
无法复现结果

### ISSUE THREAD

**Issue by ShawnDong98** [PaddlePaddle/PaddleDetection#3378]
固定 paddle.seed(), random.seed(), np.random.seed()

设置 export FLAGS_cudnn_deterministic=True;

相同的数据集， 相同的配置文件， 每次训练结果不一样。

paddledetection version: 2.0
paddle version: 2.0.2

**Comment by liuhuiCNN** [comment]
请问是哪个模型呢？部分算法在数据增强，anchor匹配过程中会有随机操作，这些操作也需要去掉随机性。比如是否随机翻转，需要设置random为False。

**Comment by bbbxixixixi** [comment]
> 请问是哪个模型呢？部分算法在数据增强，anchor匹配过程中会有随机操作，这些操作也需要去掉随机性。比如是否随机翻转，需要设置random为False。

这些其实也是通过random来设置的吧，为啥不能统一一个seed？

**Comment by liuhuiCNN** [comment]
目前不同算法的设置不完全一样，感觉您的建议，后面我们会考虑统一设置。
在coco数据集上结果浮动0.3以内是正常的，您的训练结果如果浮动在一定范围内是正常的。
