### ISSUE TITLE
cuda报错

### ISSUE THREAD

**Issue by Tolk5946** [PaddlePaddle/PaddleDetection#3379]
![QQ图片20210613220116](https://user-images.githubusercontent.com/79153269/121810561-fe154e00-cc93-11eb-8a97-610ac289b736.png)
请问这是什么原因？从来未见过这个报错。。

**Comment by liuhuiCNN** [comment]
报错在CUDA中，请您检查一下使用的CUDA版本与paddle要求的CUDA版本是否一致。此外，请您提供下paddle 版本、CUDA环境、ppdet版本、硬件设备等信息，方便我们查看问题，谢谢。
