### ISSUE TITLE
Question about the default policy of AutoAugmentImage

### ISSUE THREAD

**Issue by sbl1996** [PaddlePaddle/PaddleDetection#338]
Why "v1" is used as the default policy instead of "v0" as used in the original paper? Is there any experiment comparison? Thanks.

**Comment by littletomatodonkey** [comment]
Thanks for your attention. As we can see in the article, for larger network with pretrained imagenet model, a 20 sub-policy learned aumentation  is utilized.
![image](https://user-images.githubusercontent.com/14270174/76758025-c46d4300-67c3-11ea-8b7d-c3a855629b95.png)

**Comment by sbl1996** [comment]
Thanks for your detailed explanation. I would close this issue.
