### ISSUE TITLE
你好，我找不到ppyolo-tiny后处理的代码在哪里，想知道位置

### ISSUE THREAD

**Issue by EdwardVincentMa** [PaddlePaddle/PaddleDetection#3384]
你好，我找不到ppyolo-tiny后处理的代码，想知道位置

**Comment by wangxinxin08** [comment]
这里定义了https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/_base_/ppyolo_tiny.yml#L43 后处理的模块，可以在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/ppdet/utils/post_process.py 中找到
