### ISSUE TITLE
安装编译paddledetection-develop的代码bug

### ISSUE THREAD

**Issue by ResonLee** [PaddlePaddle/PaddleDetection#3387]
代码bug,[[之前使用paddledetection2.0.2做mask-rcnn的训练，训练完一轮后，评估的时候出错，（）](https://github.com/PaddlePaddle/PaddleDetection/issues/3311)，大佬说试下paddledetection-develop版或2.1.1版本，今天在安装验证的时候报了一个错误，` from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\engine\__init__.py", line 30
    __all__ = __all__ + tracker.__all__ \
                                        ^
SyntaxError: unexpected EOF while parsing`，于是找到报错的地方，发现源码里这样写`from . import tracker
from .tracker import *
__all__ = __all__ + tracker.__all__ \`编译不过去，于是改成`from . import tracker
from .tracker import *
__all__ = __all__ + tracker.__all__`,编译通过。

**Comment by nemonameless** [comment]
typo，会尽快修正
