### ISSUE TITLE
bbox_reg分支过大，影响其他分支，最终loss 为nan

### ISSUE THREAD

**Issue by wxf764571829** [PaddlePaddle/PaddleDetection#3389]
环境faster_rcnn_r50_fpn_1x_coco.yml lr0.0001  ubuntu16.04,cuda10.1,cudnn7.6.5,

![image](https://user-images.githubusercontent.com/46362180/122029849-d3480880-cdff-11eb-8181-05c711fe1bfa.png)

**Comment by wangxinxin08** [comment]
我们无法复现你的问题，可以检查下标注框的坐标是否正确

**Comment by wxf764571829** [comment]
> 我们无法复现你的问题，可以检查下标注框的坐标是否正确

数据是没问题的，同样数据在你们的环境训练都没出现这个问题
