### ISSUE TITLE
使用x2coco.py将voc格式的数据集转为coco，报错

### ISSUE THREAD

**Issue by JoyFuture** [PaddlePaddle/PaddleDetection#3393]
![image](https://user-images.githubusercontent.com/35593546/122076666-a579b880-ce2d-11eb-96d5-48d82717be09.png)
![image](https://user-images.githubusercontent.com/35593546/122077097-03a69b80-ce2e-11eb-9d27-c7010b54a9eb.png)
都是按照文档写的，为什么会报错呢？帮忙看看 感谢

**Comment by lyuwenyu** [comment]
trainval.txt格式不对吧，应该只有xml文件

ps. 方便把文档链接贴一下？ `都是按照文档写的，为什么会报错呢？帮忙看看 感谢`

**Comment by lyuwenyu** [comment]
- trainval.txt 应该是只能包含xml数据  https://github.com/PaddlePaddle/PaddleDetection/blob/b87a1ea86fa18ce69e44a17ad1b49c1326f19ff9/tools/x2coco.py#L200
- 重新建一个只包含xml的文件

**Comment by JoyFuture** [comment]
PaddleDetection\static\docs\tutorials\PrepareDataSet.md
中的voc数据格式说明
![image](https://user-images.githubusercontent.com/35593546/122154382-7861f000-ce97-11eb-8b3c-b0473018ae7e.png)
下面的用户数据转为voc格式
![image](https://user-images.githubusercontent.com/35593546/122154713-240b4000-ce98-11eb-87f5-8fa5c9a11c84.png)
再下面的用户数据转为coco的第二点voc转coco
![image](https://user-images.githubusercontent.com/35593546/122154902-82d0b980-ce98-11eb-9dbe-0518e9371992.png)

PaddleDetection\static\docs\tutorials\DetectionPipeline.md
中的各文件说明
![image](https://user-images.githubusercontent.com/35593546/122154415-89aafc80-ce97-11eb-97f8-2283e41f8fb0.png)

以上全部的资料都是xml和图片在同一行，又重新翻了一遍文档
PaddleDetection\static\docs\tutorials\Custom_DataSet.md
只有此处给出的例子是
![image](https://user-images.githubusercontent.com/35593546/122155054-c3c8ce00-ce98-11eb-96d9-18517007964c.png)

应该就是你所说的的格式，但是此处的格式与标准格式不一致了，还需要额外再新建一个文件，感觉很麻烦，希望适配标准的voc格式的转coco数据集

**Comment by lyuwenyu** [comment]
好的 多谢建议

**Comment by yzy913** [comment]
楼主的问题最后是怎么解决的，能讲一下吗？我现在也遇到了同样的问题！
