### ISSUE TITLE
KeyError: 'TestDataset' when running configuration

### ISSUE THREAD

**Issue by Mandroide** [PaddlePaddle/PaddleDetection#3394]
After I move the configurations of [AICity2020-Anomaly-Detection](https://github.com/PaddlePaddle/Research/tree/master/CV/AICity2020-Anomaly-Detection/det_code) to the configs directory of PaddleDetection and run the following code, it happens the following in Google Colab:

```python
infer_dir = "datasets/AIC20_track4/test-data"
output_dir = "../intermediate_result/data/AIC20_track4/test-data/"
# Inference Procedure of model.
CUDA_VISIBLE_DEVICES = 0
FLAGS_fraction_of_gpu_memory_to_use = 0.1
!export CUDA_VISIBLE_DEVICES={CUDA_VISIBLE_DEVICES}
!export FLAGS_fraction_of_gpu_memory_to_use={FLAGS_fraction_of_gpu_memory_to_use}
!python det_code/PaddleDetection/tools/infer.py \
 -c det_code/PaddleDetection/configs/aicity2020-track4/faster_rcnn_se154_vd_fpn_s1x_track4_new_anchors.yml \
  -o use_gpu=true --infer_dir "{infer_dir}" --output_dir "{output_dir}"
```
![Traceback](https://user-images.githubusercontent.com/31109774/122099281-d59a6a80-cddf-11eb-95d5-e05c384f7c8d.png)

**Comment by wangxinxin08** [comment]
you can change the directiry to `det_code` using the follwing command`cd det_code`，and try it agian. if there is still the same error, please post your config file because the error information shows that there is noe TestDataset in your config file

**Comment by Mandroide** [comment]
> you can change the directiry to `det_code` using the follwing command`cd det_code`，and try it agian. if there is still the same error, please post your config file because the error information shows that there is noe TestDataset in your config file

I tried it, and it didn't make any difference. I am using the same configuration from [aicity2020-track4](https://github.com/PaddlePaddle/Research/tree/master/CV/AICity2020-Anomaly-Detection/det_code/aicity2020-track4) for this program.

You can see my notebook here: [Test_AICity2020-Anomaly-Detection](https://github.com/Mandroide/Test_AICity2020-Anomaly-Detection/blob/main/Test_AICity2020_Anomaly_Detection.ipynb)

**Comment by wangxinxin08** [comment]
The config file from  [aicity2020-track4](https://github.com/PaddlePaddle/Research/tree/master/CV/AICity2020-Anomaly-Detection/det_code/aicity2020-track4) is used by static graph，you should change the directory to `det_code/PaddleDetection/static` to run the model defined by [aicity2020-track4](https://github.com/PaddlePaddle/Research/tree/master/CV/AICity2020-Anomaly-Detection/det_code/aicity2020-track4)

**Comment by Mandroide** [comment]
> The config file from [aicity2020-track4](https://github.com/PaddlePaddle/Research/tree/master/CV/AICity2020-Anomaly-Detection/det_code/aicity2020-track4) is used by static graph，you should change the directory to `det_code/PaddleDetection/static` to run the model defined by [aicity2020-track4](https://github.com/PaddlePaddle/Research/tree/master/CV/AICity2020-Anomaly-Detection/det_code/aicity2020-track4)

I did what you asked, and it looks like it will work. But the part within [Test_AICity2020_Anomaly_Detection.ipynb](https://github.com/Mandroide/Test_AICity2020-Anomaly-Detection/blob/main/Test_AICity2020_Anomaly_Detection.ipynb) that has this stub of code:

```python
#@title Step1: Detection Model

# Move the files to the PaddleDetection
!mv det_code/aicity2020-track4 det_code/PaddleDetection/static/configs/
!mv det_code/*.sh det_code/PaddleDetection/static

output_dir = "../intermediate_result/data/AIC20_track4/test-data/"

%cd det_code/PaddleDetection/static/

# Inference Procedure of model.
CUDA_VISIBLE_DEVICES = 0
FLAGS_fraction_of_gpu_memory_to_use = 0.1
!export CUDA_VISIBLE_DEVICES={CUDA_VISIBLE_DEVICES}
!export FLAGS_fraction_of_gpu_memory_to_use={FLAGS_fraction_of_gpu_memory_to_use}
!python tools/infer.py \
 -c configs/aicity2020-track4/faster_rcnn_se154_vd_fpn_s1x_track4_new_anchors.yml \
  -o use_gpu=true --infer_dir "{infer_dir}" --output_dir "{output_dir}"

%cd ../../..
```
outputs that No module named 'ppdet.utils.eval_utils'.

**Comment by Mandroide** [comment]
Thank you for your help. I solved the "No module name 'ppdet.utils.eval_utils". It was only that the [PYTHONPATH](https://docs.python.org/3.7/using/cmdline.html#envvar-PYTHONPATH) environment wasn't correctly set. In Google Colab I had to do:
```python
ROOT_PATH = pathlib.Path.cwd()
REPO_PATH = ROOT_PATH/"AICity2020-Anomaly-Detection"
%env PYTHONPATH="{REPO_PATH}/det_code/PaddleDetection/static"
```
