### ISSUE TITLE
paddle_detection2.10 在windows下报错找不到<dirent.h>

### ISSUE THREAD

**Issue by ximitiejiang** [PaddlePaddle/PaddleDetection#3398]
如题，windows下，最新版的paddle detection2.1 release版本下用vs2019编译报错：
`
错误	C1083	无法打开包括文件: “dirent.h”: No such file or directory	main
`
旧版paddle_detection2.0没有用这个库，请问该库哪里有

**Comment by ximitiejiang** [comment]
dirent.h似乎是linux的头文件，在https://github.com/tronkko/dirent找了一个windows兼容的头文件放上去不报这个错了。
不过还是报错无法识别lstate()函数，貌似这是linux独有的函数，windows不支持，需要注释掉这个GetAllFiles()和main函数中调用这个函数的地方。

**Comment by liuhuiCNN** [comment]
感谢反馈，我们尽快修复。

**Comment by ximitiejiang** [comment]
编译还是过不了，报了一堆LNK2019，和LNK2001/LNK1120，不知道还有别的什么原因吗

**Comment by ximitiejiang** [comment]
解决了
