### ISSUE TITLE
ppyolov2会出MobileNetV3版的吗？

### ISSUE THREAD

**Issue by qinxianyuzi** [PaddlePaddle/PaddleDetection#3400]
你好，ppyolov2的工作很出色，请问会出MobileNetV3版的吗？ppyolov2可以转到paddlelite吗？谢谢。

**Comment by lyuwenyu** [comment]
- MobileNetV3会按照计划发布的」
- 可以使用paddlelite部署的
  - 参考 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/lite
