### ISSUE TITLE
数据增强方式，我配置MixupImage，在源码中加断点debug,调试class MixupImage,怎么不运行类内的函数呢

### ISSUE THREAD

**Issue by xupengao** [PaddlePaddle/PaddleDetection#3402]
我想把增强后的图片保存下来，可视化下效果，但是没找打增强后的图片，只有DecodeImage解码图片才有输入图片，没有增强后的图片。

**Comment by lyuwenyu** [comment]
- 暂时还没有这样的功能
- 不过你可以
  - 首先worker设置成1，并且用单卡启动程序
  - 然后 可以在你需要debug的位置 插入save的代码

**Comment by xupengao** [comment]
我尝试过了，插入了save的代码，图片没有保存下来，因为不走那一块函数，print打印字符串也不起作用，是不支持mixup这个数据增强的方式么，数据处理的流程是怎么走的。

**Comment by raymondchu-z** [comment]
请问如何添加断点调试或者打印信息。

**Comment by raymondchu-z** [comment]
安装时无论使用pip安装还是源码编译安装，都会使用`/home/*/anaconda3/envs/paddle_env/lib/python3.6/site-packages/easy-install.pth`里的ppdet，而不是下载的源码。想要使用git clone下来的代码调试，需要删除上述问题里的路径，然后添加`/home/*/anaconda3/envs/paddle_env/lib/python3.6/site-packages/mypath.pth`文件，文件中写`/home/*/PaddleDetection`

**Comment by lyuwenyu** [comment]
> 我尝试过了，插入了save的代码，图片没有保存下来，因为不走那一块函数，print打印字符串也不起作用，是不支持mixup这个数据增强的方式么，数据处理的流程是怎么走的。

支持mixup的
save代码放到哪里了,  放到这个类的__call__里

**Comment by lyuwenyu** [comment]
> 安装时无论使用pip安装还是源码编译安装，都会使用`/home/*/anaconda3/envs/paddle_env/lib/python3.6/site-packages/easy-install.pth`里的ppdet，而不是下载的源码。想要使用git clone下来的代码调试，需要删除上述问题里的路径，然后添加`/home/*/anaconda3/envs/paddle_env/lib/python3.6/site-packages/mypath.pth`文件，文件中写`/home/*/PaddleDetection`

这个是Python的语法问题 包的使用顺序是按照环境变量的顺序来的 优先搜索安装路径->当前路径
1. 要么卸载之前按照的ppdet
2. 要么修改 sys.path

**Comment by xupengao** [comment]
好的，已经解决。


| |
徐鹏翱
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年6月17日 ***@***.***> 写道：

我尝试过了，插入了save的代码，图片没有保存下来，因为不走那一块函数，print打印字符串也不起作用，是不支持mixup这个数据增强的方式么，数据处理的流程是怎么走的。

支持mixup的
save代码放到哪里了, 放到这个类的__call__里
