### ISSUE TITLE
paddle solov2 内存释放

### ISSUE THREAD

**Issue by cslixin1997** [PaddlePaddle/PaddleDetection#3403]
paddle solov2 不能ctrl+c直接中断杀死吗?     我这边在训练中 ctrl+c中断训练后  gpu显示程序还在后台跑着，gpu使用率100%，显存也占着，只有我用kill强制杀进程才行

**Comment by lyuwenyu** [comment]
会有这个问题 建议手动kill
` ps -aux | grep tools/train.py | awk '{print $2}' | uniq | xargs kill -9 `
