### ISSUE TITLE
关于ppdet FairMOT中的问题

### ISSUE THREAD

**Issue by ReverseSacle** [PaddlePaddle/PaddleDetection#3404]
如题，本想在windows下运行develop版中的FairMOT,结果报错了，去看了官方paddle文档，文档中没有这个函数。
<img width="730" alt="报错" src="https://user-images.githubusercontent.com/73418195/122201750-efff4180-cece-11eb-9dd5-d0c597e2062e.png">

**Comment by nemonameless** [comment]
请安装paddlepaddle 2.1版本 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/INSTALL_cn.md
文档不一定更新及时

**Comment by ReverseSacle** [comment]
> 请安装paddlepaddle 2.1版本 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/INSTALL_cn.md
> 文档不一定更新及时

还有个问题，我用paddle_detection2.1版本训练好了FairMOT，并用develop版本的export_model.py导出了2.1版本的fairmot模型，但报错提示输出的是NCHW格式，可能是格式错误，这是版本导致的错误吗？
```InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 608, the input's shape is [1, 608, 1088, 3]; the filter's channels is 3, the filter's shape is [16, 3, 7, 7]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.```
```[Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:608 != filter_dims[1] * groups:3.] (at C:/home/workspace/Paddle_release/paddle/fluid/operators/conv_op.cc:100)[operator < conv2d > error]```

**Comment by nemonameless** [comment]
> paddle_detection2.1
请问你的paddle_detection2.1版本是什么时候拉取和训练的，config的TrainReader里有 - RGBReverse: {}吗？ 用modelzoo里提供的fairmot权重是可以export_model的。以及请发下export_model.py的命令。

**Comment by nemonameless** [comment]
> > 请安装paddlepaddle 2.1版本 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/INSTALL_cn.md
> > 文档不一定更新及时
> 
> 还有个问题，我用paddle_detection2.1版本训练好了FairMOT，并用develop版本的export_model.py导出了2.1版本的fairmot模型，但报错提示输出的是NCHW格式，可能是格式错误，这是版本导致的错误吗？
> `InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 608, the input's shape is [1, 608, 1088, 3]; the filter's channels is 3, the filter's shape is [16, 3, 7, 7]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.`
> `[Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:608 != filter_dims[1] * groups:3.] (at C:/home/workspace/Paddle_release/paddle/fluid/operators/conv_op.cc:100)[operator < conv2d > error]`

paddle_detection2.1
请问你的paddle_detection2.1版本是什么时候拉取和训练的，config的TrainReader里有 - RGBReverse: {}吗？ 用modelzoo里提供的fairmot权重是可以export_model的。以及请发下export_model.py的命令。

**Comment by ReverseSacle** [comment]
> > > 请安装paddlepaddle 2.1版本 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/INSTALL_cn.md
> > > 文档不一定更新及时
> > 
> > 
> > 还有个问题，我用paddle_detection2.1版本训练好了FairMOT，并用develop版本的export_model.py导出了2.1版本的fairmot模型，但报错提示输出的是NCHW格式，可能是格式错误，这是版本导致的错误吗？
> > `InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 608, the input's shape is [1, 608, 1088, 3]; the filter's channels is 3, the filter's shape is [16, 3, 7, 7]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.`
> > `[Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:608 != filter_dims[1] * groups:3.] (at C:/home/workspace/Paddle_release/paddle/fluid/operators/conv_op.cc:100)[operator < conv2d > error]`
> 
> paddle_detection2.1
> 请问你的paddle_detection2.1版本是什么时候拉取和训练的，config的TrainReader里有 - RGBReverse: {}吗？ 用modelzoo里提供的fairmot权重是可以export_model的。以及请发下export_model.py的命令。

paddle_detection2.1版本是上个星期一左右拉取的，上个星期三左右开始训练，TrainReader里面有RGBReverse: {}，用自己训练好的模型权重来export_model。
```
%cd ~/develop/
!python tools/export_model.py -c /home/aistudio/PD2.1/configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml
```

**Comment by nemonameless** [comment]
> > > > 请安装paddlepaddle 2.1版本 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/INSTALL_cn.md
> > > > 文档不一定更新及时
> > > 
> > > 
> > > 还有个问题，我用paddle_detection2.1版本训练好了FairMOT，并用develop版本的export_model.py导出了2.1版本的fairmot模型，但报错提示输出的是NCHW格式，可能是格式错误，这是版本导致的错误吗？
> > > `InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 608, the input's shape is [1, 608, 1088, 3]; the filter's channels is 3, the filter's shape is [16, 3, 7, 7]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.`
> > > `[Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:608 != filter_dims[1] * groups:3.] (at C:/home/workspace/Paddle_release/paddle/fluid/operators/conv_op.cc:100)[operator < conv2d > error]`
> > 
> > 
> > paddle_detection2.1
> > 请问你的paddle_detection2.1版本是什么时候拉取和训练的，config的TrainReader里有 - RGBReverse: {}吗？ 用modelzoo里提供的fairmot权重是可以export_model的。以及请发下export_model.py的命令。
> 
> paddle_detection2.1版本是上个星期一左右拉取的，上个星期三左右开始训练，TrainReader里面有RGBReverse: {}，用自己训练好的模型权重来export_model。
> 
> ```
> %cd ~/develop/
> !python tools/export_model.py -c /home/aistudio/PD2.1/configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml
> ```

modelzoo里的模型链接 https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608.pdparams ，你导出也会有这个问题吗？建议重新拉取最新的并且 python setup.py install。modelzoo里这个权重是在加RGBReverse之前训的，这个理论上也不会有影响。

**Comment by nemonameless** [comment]
导出模型后可以直接infer video，注意需要先python setup.py install，暂时不支持infer单张图，单张图跟踪也没意义。
```
python deploy/python/mot_infer.py --model_dir=output_inference/fairmot_dla34_30e_1088x608 --video_file=test.mp4 --device=GPU
```

**Comment by ReverseSacle** [comment]
> 导出模型后可以直接infer video，注意需要先python setup.py install，暂时不支持infer单张图，单张图跟踪也没意义。
> 
> ```
> python deploy/python/mot_infer.py --model_dir=output_inference/fairmot_dla34_30e_1088x608 --video_file=test.mp4 --device=GPU
> ```
我是在win10的pycharm里运行mot_infer.py的，之前是把FairMOT相关文件整合加上完整的ppdet来运行deploy里的mot_infer.py,结果就报错了。刚刚以完整的paddle_detection的develop版重新试了一边，可以导入权重。但报了OpenCV的错误。
```e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
[ERROR:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-nvves523\opencv\modules\videoio\src\cap.cpp (142) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-nvves523\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): D:\BaiduNetdiskDownload\Paddle_FairMOT\video.avi in function 'cv::icvExtractPattern'


frame_count 0
[ERROR:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-nvves523\opencv\modules\videoio\src\cap.cpp (563) cv::VideoWriter::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-nvves523\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): output\video.avi in function 'cv::icvExtractPattern' 
```

**Comment by ReverseSacle** [comment]
> 导出模型后可以直接infer video，注意需要先python setup.py install，暂时不支持infer单张图，单张图跟踪也没意义。
> 
> ```
> python deploy/python/mot_infer.py --model_dir=output_inference/fairmot_dla34_30e_1088x608 --video_file=test.mp4 --device=GPU
> ```

之前那个是我设置路径的问题，昨天我用develop版重新训练了，发现了几个问题。
 一.Win10运行setup.py安装，有一处警告是ppdet/engine文件夹下的__init__.py中最后一行```__all__ = __all__ + tracker.__all__ \```多了个'\'。
二.另外我训练了一个epoch后用mot_infer.py生成的一个视频中全部是第一张截取的图片的总和（相当于把第一张图片拼接了n次合成的视频)
三.在win10中使用deploy下的mot_infer.py会报错提示关键字错误，这是infer_cfg.yml中的to_rgb的错误，删除后，又提示之前这个错误了。
```The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 608, the input's shape is [1, 608, 1088, 3]; the filter's channels is 3, the filter's shape is [16, 3, 7, 7]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.```

**Comment by ReverseSacle** [comment]
> > 导出模型后可以直接infer video，注意需要先python setup.py install，暂时不支持infer单张图，单张图跟踪也没意义。
> > ```
> > python deploy/python/mot_infer.py --model_dir=output_inference/fairmot_dla34_30e_1088x608 --video_file=test.mp4 --device=GPU
> > ```
> 
> 之前那个是我设置路径的问题，昨天我用develop版重新训练了，发现了几个问题。
> 一.Win10运行setup.py安装，有一处警告是ppdet/engine文件夹下的__init__.py中最后一行`__all__ = __all__ + tracker.__all__ \`多了个''。
> 二.另外我训练了一个epoch后用mot_infer.py生成的一个视频中全部是第一张截取的图片的总和（相当于把第一张图片拼接了n次合成的视频)

我试了下，将paddle_detection2.1版中的ppdet/engine文件夹下的tracker.py文件替换了develop对应文件，既能生成正常的视频还生成了对应的txt文件。

**Comment by nemonameless** [comment]
> > > 导出模型后可以直接infer video，注意需要先python setup.py install，暂时不支持infer单张图，单张图跟踪也没意义。
> > > ```
> > > python deploy/python/mot_infer.py --model_dir=output_inference/fairmot_dla34_30e_1088x608 --video_file=test.mp4 --device=GPU
> > > ```
> > 
> > 
> > 之前那个是我设置路径的问题，昨天我用develop版重新训练了，发现了几个问题。
> > 一.Win10运行setup.py安装，有一处警告是ppdet/engine文件夹下的__init__.py中最后一行`__all__ = __all__ + tracker.__all__ \`多了个''。
> > 二.另外我训练了一个epoch后用mot_infer.py生成的一个视频中全部是第一张截取的图片的总和（相当于把第一张图片拼接了n次合成的视频)
> 
> 我试了下，将paddle_detection2.1版中的ppdet/engine文件夹下的tracker.py文件替换了develop对应文件，既能生成正常的视频还生成了对应的txt文件。

tracker.__all__ \ 已经修复，后两点我这试验没有出现你的问题。建议每换一个版本的PaddleDetection或者有改动ppdet文件夹里的代码后，重新python setup.py install 更新下。建议使用develop分支，实时更新和维护的，release/2.1分支很多改动还没有合入，之后会基于develop切换到2.1.1或2.2分支。
