### ISSUE TITLE
running inference in jetson nano

### ISSUE THREAD

**Issue by LucasVillarroelR** [PaddlePaddle/PaddleDetection#3406]
Hi, I'm trying to run the inference demo with pre-trained models in a jetson nano.
I modified infer.py to get the time of each detection

I'm having a couple of troubles now, first, the inference is not drawing in output.
Second, the time of the inferences is too high.

Is there a solution for this?

![Captura de pantalla de 2021-06-15 17-39-56](https://user-images.githubusercontent.com/55993714/122261781-bb759080-cea2-11eb-95d0-ab487275e636.png)

**Comment by lyuwenyu** [comment]
- try to set `run_benchmakr=True` to test inference time
- referenece https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/python
