### ISSUE TITLE
NMS的阈值是否会影响模型训练

### ISSUE THREAD

**Issue by yinggo** [PaddlePaddle/PaddleDetection#3407]
请教下，NMS的阈值会影响模型训练吗？实验结果来看，不同阈值训练出来的模型检测效果会有一些小的差别，但原理上想不明白，感觉应该是没有影响的，NMS是在最后做的(具体我用的是这个[class MultiClassDiouNMS(object):](https://github.com/PaddlePaddle/PaddleDetection/blob/5e19955b011d47377a3f1443a6e592ddd9e5024a/static/ppdet/modeling/ops.py#L676)，貌似并没有参与训练过程？

**Comment by nemonameless** [comment]
请问你训的是什么模型？另外不同阈值训练出来的模型，你测试的时候是用同一个阈值吗？

**Comment by yinggo** [comment]
> 请问你训的是什么模型？不同阈值训练出来的模型，你测试的时候是用同一个阈值吗？

您好，我训练是基于cascade_rcnn_dcn_r50_fpn_1x_coco修改使用了MultiClassDiouNMS，训练的其他检测数据集
测试和训练使用同样的阈值，测试过0.3和0.5，不同case下（eg, reasonable case/occluded case/small case）的实验结果有一些变动。。
请问这个模型训练的过程是否有用到nms？

**Comment by nemonameless** [comment]
> > 请问你训的是什么模型？不同阈值训练出来的模型，你测试的时候是用同一个阈值吗？
> 
> 您好，我训练是基于cascade_rcnn_dcn_r50_fpn_1x_coco修改使用了MultiClassDiouNMS，训练的其他检测数据集
> 测试和训练使用同样的阈值，测试过0.3和0.5，不同case下（eg, reasonable case/occluded case/small case）的实验结果有一些变动。。
> 请问这个模型训练的过程是否有用到nms？

两阶段模型训练时在RPNHead生成proposal是需要nms的，但你的改动只是head上和训练是无关的。你用同一个阈值训练用不同阈值测试，结果肯定也是不同的。另外数据集太小容易出现波动。

**Comment by yinggo** [comment]
@nemonameless 感谢！
