### ISSUE TITLE
c++部署代码和第三方库嵌入到其他程序报错: 值“MT_StaticRelease”不匹配值"MD_DynamicRelease"

### ISSUE THREAD

**Issue by ximitiejiang** [PaddlePaddle/PaddleDetection#3408]
你好，我尝试在windows下把部署代码deploy cpp移植到另一个主程序中集成编译，在编译时报错：
```
检测到“RuntimeLibrary”的不匹配项：值"MT_StaticRelease"不匹配值"MD_DynamicRelease"
```
搜索了下有如下猜测：
- 部署代码deploy cpp所使用的所有第三方库(paddle inference/mkldnn/...)都基于/MT选项进行编译，链接的运行时库为LIBCMT.lib
-  我的主程序以及之前使用的第三方库都基于默认的/MD选项，链接的运行时库为MSVCRT.lib/MSVCRT.dll
- 不同第三方库所使用的运行时库不同，导致冲突

我的问题是，我当前所用的其他库文件没有替代的MT编译版本，当前windows端貌似很多库也都是基于默认MD选项编译，我们的paddle inference库编译是否也可以提供基于/MD编译的版本？

或者是我的理解有错误，那么针对我的问题，是否有什么建议的解决方案？

**Comment by ximitiejiang** [comment]
补充一下：
- 如果基于默认编译设置：代码生成/MD，则会报上面的不匹配错误
- 如果修改编译设置：代码生成/MT，则会报"C1189: #error: Please use the /MD switch for _AFXDLL builds."

大佬们，何解？

**Comment by liuhuiCNN** [comment]
你好，paddle预测库默认使用  /MT 模式进行编译，您可以自己重新编译一下Paddle预测库，windows编译预测库文档请参考：https://paddle-inference.readthedocs.io/en/latest/user_guides/source_compile.html

**Comment by ximitiejiang** [comment]
临时方案还是用MT进行编译，禁用了冲突的库。

谢谢！
