### ISSUE TITLE
关于断点/打印信息调试无效的问题

### ISSUE THREAD

**Issue by raymondchu-z** [PaddlePaddle/PaddleDetection#3410]
安装时无论使用pip安装还是源码编译安装，都会使用`/home/*/anaconda3/envs/paddle_env/lib/python3.6/site-packages/easy-install.pth`里的ppdet，而不是下载的源码。想要使用git clone下来的代码调试，需要删除上述问题里的路径，然后添加`/home/*/anaconda3/envs/paddle_env/lib/python3.6/site-packages/mypath.pth`文件，文件中写`/home/*/PaddleDetection`

**Comment by lyuwenyu** [comment]
-  你现在系统几个Python环境？ 确保pip 和 python 对应 <which pip / python>
- python import package是有顺序的，默认会优先搜索`site-packages`里的 而不是当前目录 <查看环境变量路径的顺序>

**Comment by nemonameless** [comment]
可以pip uninstall paddledet试试。代码调试就能根据本地代码了。
