### ISSUE TITLE
paddleslim剪枝问题

### ISSUE THREAD

**Issue by wflrz123** [PaddlePaddle/PaddleDetection#3412]
!python prune.py \
-c /home/aistudio/PaddleDetection/configs/ppyolo/ppyolov2_r101vd_dcn_365e_coco.yml \
--print_params
使用paddleslim里的prune确定待分析参数时报错：ModuleNotFoundError: No module named 'ppdet.experimental'
ppdet是否已更新，导致没有experimental该函数

**Comment by yghstill** [comment]
@wflrz123 请参考slim的文档教程：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/configs/slim
根据已有prune的配置文件，增加新的prune配置，执行：
```shell
python tools/train.py -c configs/{MODEL.yml} --slim_config configs/slim/{SLIM_CONFIG.yml}
```

**Comment by lleesg** [comment]
关键是生成敏感度文件，从而确定各层的剪裁率，可参考https://github.com/PaddlePaddle/PaddleX/tree/release/2.0.0/tutorials/slim/prune/object_detection
