### ISSUE TITLE
关于添加backbone

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleDetection#3415]
我在paddle detection中添加了自己的backbone，然后进行训练，出现了如下错误：
![D48QR0J$MO2Z1%JZW9H1B55](https://user-images.githubusercontent.com/71364549/122363057-3a45f880-cf8b-11eb-9300-52a4540b46e5.png)
这是什么原因呢

**Comment by lyuwenyu** [comment]
参数名字有重名的冲突  建议自己的`backbone`里的参数 不要指定名字 或者 名字加上特定前缀

**Comment by yuchen02** [comment]
@553548793 请问您是如何注册自定义模块的？我自定义后出现AssertionError: the module ResNet-1 is not registered的错误

**Comment by fpjnice** [comment]
> @553548793 请问您是如何注册自定义模块的？我自定义后出现AssertionError: the module ResNet-1 is not registered的错误

我也想问如何定义新模块
