### ISSUE TITLE
fairmot使用训练好的pdparams预测视频

### ISSUE THREAD

**Issue by Dejavusd** [PaddlePaddle/PaddleDetection#3416]
在训练的时候已下载配置好训练集得到pdparams，后又创了新的项目，使用训练好的pdparams预测视频，会报数据集未下载的错误 NotImplementedError: Dataset mot is not valid for download automatically. Please apply and download the dataset following docs/tutorials/PrepareMOTDataSet.md 
请问如何在不下载配置训练集下，使用自己训练好的pdparams预测视频

**Comment by nemonameless** [comment]
> 在训练的时候已下载配置好训练集得到pdparams，后又创了新的项目，使用训练好的pdparams预测视频，会报数据集未下载的错误 NotImplementedError: Dataset mot is not valid for download automatically. Please apply and download the dataset following docs/tutorials/PrepareMOTDataSet.md
> 请问如何在不下载配置训练集下，使用自己训练好的pdparams预测视频

预测视频不需要下载数据集。训练和评估(tools/eval_mot.py)需要下载数据集。
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/mot/fairmot/README_cn.md 
3. 预测
```
CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights={your model name}.pdparams --video_file={your video name}.mp4  --save_videos
```

**Comment by Dejavusd** [comment]
> > 在训练的时候已下载配置好训练集得到pdparams，后又创造了新的项目，使用训练好的pdparams预测视频，会报数据集未下载的错误 NotImplementedError: Dataset mot is not valid for download automatically. 请按照docs/tutorials/PrepareMOTDataSet.md申请并下载数据
> > 集，请问如何在不下载配置训练集下，使用自己训练好的pdparams视频预测
> 
> 预测视频无需下载数据集。训练和评估(tools/eval_mot.py)需要下载集。
> https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/mot/fairmot/README_cn.md
> 3.预测
> 
> ```
> CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights={your model name}.pdparams --video_file={your video name}.mp4  --save_videos
> ```

这种相比 用develop 导出模型后来infer，有什么区别，预测视频速度之类的

**Comment by Dejavusd** [comment]
> > 在训练的时候已下载配置好训练集得到pdparams，后又创了新的项目，使用训练好的pdparams预测视频，会报数据集未下载的错误 NotImplementedError: Dataset mot is not valid for download automatically. Please apply and download the dataset following docs/tutorials/PrepareMOTDataSet.md
> > 请问如何在不下载配置训练集下，使用自己训练好的pdparams预测视频
> 
> 预测视频不需要下载数据集。训练和评估(tools/eval_mot.py)需要下载数据集。
> https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/mot/fairmot/README_cn.md
> 3. 预测
> 
> ```
> CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights={your model name}.pdparams --video_file={your video name}.mp4  --save_videos
> ```

刚刚我试了一遍，还是会报错 NotImplementedError: Dataset mot is not valid for download automatically. Please apply and download the dataset following docs/tutorials/PrepareMOTDataSet.md
我使用的是 PaddleDetection-release-2.1 
代码 CUDA_VISIBLE_DEVICES=0 
!python  /home/aistudio/PD/tools/infer_mot.py -c  /home/aistudio/PD/configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml 
-o weights=/home/aistudio/PD/output/fairmot/model.pdparams --video_file=/home/aistudio/video_1.mp4  --save_videos

**Comment by nemonameless** [comment]
> > > 在训练的时候已下载配置好训练集得到pdparams，后又创造了新的项目，使用训练好的pdparams预测视频，会报数据集未下载的错误 NotImplementedError: Dataset mot is not valid for download automatically. 请按照docs/tutorials/PrepareMOTDataSet.md申请并下载数据
> > > 集，请问如何在不下载配置训练集下，使用自己训练好的pdparams视频预测
> > 
> > 
> > 预测视频无需下载数据集。训练和评估(tools/eval_mot.py)需要下载集。
> > https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/mot/fairmot/README_cn.md
> > 3.预测
> > ```
> > CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights={your model name}.pdparams --video_file={your video name}.mp4  --save_videos
> > ```
> 
> 这种相比 用develop 导出模型后来infer，有什么区别，预测视频速度之类的

建议每换一个版本的PaddleDetection或者有改动ppdet文件夹里的代码后，重新python setup.py install 更新下。实验过没有出现你的问题。https://github.com/PaddlePaddle/PaddleDetection/releases 这里的zip包可能有改动没合入，建议拉取github上的release/2.1或develop。导出模型后deploy下的infer见文档  https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/python ，目前develop分支里的跟踪模型的deploy还待完善。

**Comment by Dejavusd** [comment]
> > > > 在训练的时候已下载配置好训练集得到pdparams，后又创造了新的项目，使用训练好的pdparams预测视频，会报数据集未下载的错误 NotImplementedError: Dataset mot is not valid for download automatically. 请按照docs/tutorials/PrepareMOTDataSet.md申请并下载数据
> > > > 集，请问如何在不下载配置训练集下，使用自己训练好的pdparams视频预测
> > > 
> > > 
> > > 预测视频无需下载数据集。训练和评估(tools/eval_mot.py)需要下载集。
> > > https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/mot/fairmot/README_cn.md
> > > 3.预测
> > > ```
> > > CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights={your model name}.pdparams --video_file={your video name}.mp4  --save_videos
> > > ```
> > 
> > 
> > 这种相比 用develop 导出模型后来infer，有什么区别，预测视频速度之类的
> 
> 建议每换一个版本的PaddleDetection或者有改动ppdet文件夹里的代码后，重新python setup.py install 更新下。实验过没有出现你的问题。https://github.com/PaddlePaddle/PaddleDetection/releases 这里的zip包可能有改动没合入，建议拉取github上的release/2.1或develop。导出模型后deploy下的infer见文档 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/python ，目前develop分支里的跟踪模型的deploy还待完善。

两个我都试了 release/2.1或develop，setup 也更新过了，但还是报同样的错，是不是哪里我没有修改，如果能告诉我你那边使用的是哪个git实验的就好了。

**Comment by Dejavusd** [comment]
[06/17 18:11:32] ppdet.utils.download WARNING: Config dataset_dir dataset/mot is not exits, dataset config is not valid
[06/17 18:11:32] ppdet.utils.download INFO: Dataset /home/aistudio/dataset/mot is not valid for reason above, try searching /home/aistudio/.cache/paddle/dataset or downloading dataset...

**Comment by nemonameless** [comment]
请问你的数据集目录是？git  clone下来什么都不用改就运行即可。你是把dataset文件夹删掉了，还是改了configs/datasets/mot.yml的dataset_dir？

**Comment by Dejavusd** [comment]
> 请问你的数据集目录是？git clone下来什么都不用改就运行即可。你是不是把dataset文件夹删掉了？还是改了configs/datasets/mot.yml的dataset_dir？

对，我刚刚也发现到了这个问题，目前已经成功解决了。
configs/datasets/mot.yml下的全部dataset_dir要修改成自己的路径。
