### ISSUE TITLE
安装paddle没有报错，但是无法运行

### ISSUE THREAD

**Issue by PiggyJie** [PaddlePaddle/PaddleDetection#3418]
问题如题所述。安装完paddle后无法运行，使用官方提供的paddle.utils.run_check()方法后不出结果，提示信息如下：
`(paddle) PS C:\Users\jie> python
Python 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0617 18:00:22.433677 19572 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 10.2
W0617 18:00:22.442680 19572 device_context.cc:422] device: 0, cuDNN Version: 7.6.`

下面为系统版本信息：

> paddle版本：2.1最新版
> cuda版本：10.2
> cudnn版本：7.6.5
> Python版本：3.7/3.8（都试过）
> 显卡：rtx3050（移动版）

**Comment by PiggyJie** [comment]
首先问一下，是不是paddle不能在win10家庭版上使用？因为尝试了各种方法，我的电脑上始终运行不起来paddle（运行check方法时会卡住，既出不了结果，也无法进行键盘操作）。如果能在家庭版中使用，那我实在找不出其他原因了。

更新：
各种方法都尝试过了，还是不行。应该不是操作上的问题，同样的操作，公司电脑上能正常使用，且是一次成功。
尝试的方法：
1、不同的cuda版本：10.2,10.1
2、重建虚拟环境
3、Pip、conda安装方式
4、彻底重装anaconda、pycharm
5、其他各种依赖的重装
6、。。。。

电脑型号：联想小新pro16 rtx3050版
CPU：AMD R75800H
显卡：RTX3050（laptop版本）
内存：16G
显存：4G

希望各位大佬能帮忙解答一波，本人感激不尽，实在困扰太久！！！

**Comment by nemonameless** [comment]
30系列的显卡应该要cuda11才行。
https://www.paddlepaddle.org.cn/install/quick/zh/2.0rc-linux-source?docurl=/documentation/docs/zh/install/pip/windows-pip.html  
如果您使用的是安培架构的GPU，推荐使用CUDA11.2，执行以下命令安装：
```
python -m pip install paddlepaddle-gpu==2.1.0.post112 -f https://paddlepaddle.org.cn/whl/mkl/stable.html
```
如果您使用的是非安培架构的GPU，推荐使用CUDA10.2，性能更优。

**Comment by PiggyJie** [comment]
首先，非常感谢大佬的回答。目前这个问题已经成功解决，的确是cuda版本的问题。现在安装了cuda11.2和cudnn8.2之后已经能够正常运行了。但是在此也希望官方能在官网上给出提示：
“RTX3050不支持cuda10.x系列版本使用”
其实RTX3050不支持cuda10也是我在安装pytorch时发现的，pytorch上很明确的说明了RTX3050是不支持cuda10的。
总之非常感谢回答，祝生活愉快！

> 30系列的显卡应该要cuda11才行。
> https://www.paddlepaddle.org.cn/install/quick/zh/2.0rc-linux-source?docurl=/documentation/docs/zh/install/pip/windows-pip.html
> 如果您使用的是安培架构的GPU，推荐使用CUDA11.2，执行以下命令安装：
> 
> ```
> python -m pip install paddlepaddle-gpu==2.1.0.post112 -f https://paddlepaddle.org.cn/whl/mkl/stable.html
> ```
> 
> 如果您使用的是非安培架构的GPU，推荐使用CUDA10.2，性能更优。
