### ISSUE TITLE
关键点检测

### ISSUE THREAD

**Issue by GexLoong** [PaddlePaddle/PaddleDetection#3419]
![9704`ZS(2QLT LV`U{EXH%K](https://user-images.githubusercontent.com/71758483/122376992-3ddf7c80-cf97-11eb-9693-65aea81851b1.png)
请问keypoints能用其他数据集吗，我用的posetrack官网的数据集报错

**Comment by nemonameless** [comment]
目前KeyPoint模型基于coco数据集开发，其他数据集尚未验证。可以将posetrack的标注文件改成coco keypoint的格式。

**Comment by GexLoong** [comment]
请问关键点检测能和多目标跟踪相结合吗，就是通过关键点检测提高跟踪识别的准确率和召回率，我看到官方给了一篇文章写着能结合使用，但是是先通过fairmot跟踪得到人的框，再通过关键点检测得到人的关键点标识，这样貌似不是提高跟踪的准确率和召回率吧。求教，谢谢！！

**Comment by MyGitHub-G** [comment]
请问关键点检测能和多目标跟踪相结合吗，就是通过关键点检测提高跟踪识别的准确率和召回率，我看到官方给了一篇文章写着能结合使用，但是是先通过fairmot跟踪得到人的框，再通过关键点检测得到人的关键点标识，这样貌似不是提高跟踪的准确率和召回率吧。求教，谢谢！！

**Comment by nemonameless** [comment]
> 请问关键点检测能和多目标跟踪相结合吗，就是通过关键点检测提高跟踪识别的准确率和召回率，我看到官方给了一篇文章写着能结合使用，但是是先通过fairmot跟踪得到人的框，再通过关键点检测得到人的关键点标识，这样貌似不是提高跟踪的准确率和召回率吧。求教，谢谢！！

我们官网的第2个demo就是关键点检测和多目标跟踪结合的，的确是先fairmot跟踪再hrnet得到人的keypoints。个人觉得看你的需求偏向于哪方面吧。跟踪的结果是多了个id标记的检测框，本质上是更加精确的框。而top-down的pose estimation最初来源于行人检测框架，依赖强检测器的性能可以获取较高的召回，得到检出框后，再在框中检测人体关键点，所以先跟踪后关键点的做法是比较直观的。bottom-up的方法是先检出所有人体关键点再重组成人形，和检测框关系不大，要么根据关键点结果对跟踪的框进行过滤或精修，感觉意义不是很大，跟踪的框一般已经是高置信度的了。

**Comment by GexLoong** [comment]
感谢您的解答！！！
