### ISSUE TITLE
paddle中使用自定义数据集，设置shuffle为False，显存溢出

### ISSUE THREAD

**Issue by zhude233** [PaddlePaddle/PaddleDetection#3422]
在shuffle设置为True时，显存占用约1.4g，下图为设置为True时
![$N )9I%C58V@1LSWZW{C~Q](https://user-images.githubusercontent.com/60126992/122398956-f663eb00-cfac-11eb-88ee-8ca3af40afe6.png)
在shuffle设置为False时，显存会溢出，下图为设置为False时
![O~UIMJP8S7`8T7S %Q(P{ 8](https://user-images.githubusercontent.com/60126992/122399093-1398b980-cfad-11eb-9134-9e94fa1c6a62.png)
两者均在同一环境下测试，以下为dataset定义
![image](https://user-images.githubusercontent.com/60126992/122399317-43e05800-cfad-11eb-9526-20eb0a848dc9.png)
![image](https://user-images.githubusercontent.com/60126992/122399369-4fcc1a00-cfad-11eb-9b03-72a4db6eb6da.png)

**Comment by zhude233** [comment]
![image](https://user-images.githubusercontent.com/60126992/122399439-61adbd00-cfad-11eb-9f17-db13067ff507.png)

**Comment by zhude233** [comment]
最长的data返回仅为[3000+,800]

**Comment by zhude233** [comment]
paddlepaddle版本为2.0

**Comment by nemonameless** [comment]
> paddlepaddle版本为2.0

建议换2.1版本，ppdet版本也拉取最新的develop或release/2.1分支试试

**Comment by zhude233** [comment]
> > paddlepaddle版本为2.0
> 
> 建议换2.1版本，ppdet版本也拉取最新的develop或release/2.1分支试试

paddlepaddle2.1GPU版，根据paddlepaddle文档使用会出现训练异常，暂无法解决，并未使用ppdet

**Comment by nemonameless** [comment]
> > > paddlepaddle版本为2.0
> > 
> > 
> > 建议换2.1版本，ppdet版本也拉取最新的develop或release/2.1分支试试
> 
> paddlepaddle2.1GPU版，根据paddlepaddle文档使用会出现训练异常，暂无法解决，并未使用ppdet

PaddleDetection是哪个分支？

**Comment by zhude233** [comment]
> > > > paddlepaddle版本为2.0
> > > 
> > > 
> > > 建议换2.1版本，ppdet版本也拉取最新的develop或release/2.1分支试试
> > 
> > paddlepaddle2.1GPU版，根据paddlepaddle文档使用会出现训练异常，暂无法解决，并未使用ppdet
> 
> PaddleDetection是哪个分支？

并未使用paddledetection

**Comment by nemonameless** [comment]
> > > > > paddlepaddle版本为2.0
> > > > 
> > > > 
> > > > 建议换2.1版本，ppdet版本也拉取最新的develop或release/2.1分支试试
> > > 
> > > 
> > > paddlepaddle2.1GPU版，根据paddlepaddle文档使用会出现训练异常，暂无法解决，并未使用ppdet
> > 
> > 
> > PaddleDetection是哪个分支？
> 
> 并未使用paddledetection

建议给 https://github.com/PaddlePaddle/Paddle/issues/new/choose 也提个issue

**Comment by zhude233** [comment]
> > > > > > paddlepaddle版本为2.0
> > > > > 
> > > > > 
> > > > > 建议换2.1版本，ppdet版本也拉取最新的develop或release/2.1分支试试
> > > > 
> > > > 
> > > > paddlepaddle2.1GPU版，根据paddlepaddle文档使用会出现训练异常，暂无法解决，并未使用ppdet
> > > 
> > > 
> > > PaddleDetection是哪个分支？
> > 
> > 并未使用paddledetection
> 
> 建议给 https://github.com/PaddlePaddle/Paddle/issues/new/choose 也提个issue

好的，之前没找到paddle的😂
