### ISSUE TITLE
ppyolov2 训练速度慢

### ISSUE THREAD

**Issue by lazyn1997** [PaddlePaddle/PaddleDetection#3423]
![image](https://user-images.githubusercontent.com/34644177/122405420-a1c36e80-cfb2-11eb-87f4-9a465cb2bf66.png)

这个 ips 是指速度嘛，是现在对 cuda11 优化不好吗，为什么速度差这么多，cuda11.2 显卡是 3080，cuda10.2 显卡是 T4，理论上是不是 3080 更快啊？

**Comment by qingqing01** [comment]
@lazyn1997 理论上是3080更快一些。您是单卡训练吗？

**Comment by lazyn1997** [comment]
> @lazyn1997 理论上是3080更快一些。您是单卡训练吗？

是的，两个结果都是单卡训练。

**Comment by xiegegege** [comment]
@lazyn1997 你好，我这里一样的环境复现了下，结果跟你的不太一样。我的显存比较小，所以都设的batch_size=1，都是单卡训练
cuda11.2，显卡3080的结果：
<img width="962" alt="e19e4cd4c62bbc12e69413b17b2f8879" src="https://user-images.githubusercontent.com/46314656/123372827-de94f400-d5b6-11eb-9d19-bfa41f33a587.png">
cuda10.2，显卡T4的结果：
<img width="891" alt="f271d19b47ff4941eac36f3f2e273e9e" src="https://user-images.githubusercontent.com/46314656/123372950-2156cc00-d5b7-11eb-977b-1b013212e554.png">
还是3080稍快些的
运行命令都是：python tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.y
ml -o TrainReader.batch_size=1

**Comment by lazyn1997** [comment]
> @lazyn1997 你好，我这里一样的环境复现了下，结果跟你的不太一样。我的显存比较小，所以都设的batch_size=1，都是单卡训练
> cuda11.2，显卡3080的结果：
> <img alt="e19e4cd4c62bbc12e69413b17b2f8879" width="962" src="https://user-images.githubusercontent.com/46314656/123372827-de94f400-d5b6-11eb-9d19-bfa41f33a587.png">
> cuda10.2，显卡T4的结果：
> <img alt="f271d19b47ff4941eac36f3f2e273e9e" width="891" src="https://user-images.githubusercontent.com/46314656/123372950-2156cc00-d5b7-11eb-977b-1b013212e554.png">
> 还是3080稍快些的
> 运行命令都是：python tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.y
> ml -o TrainReader.batch_size=1

那我清楚了，可能是因为我 batch_size 大小设置不一致造成的，因为 T4 的显存比 3080 大许多，所以我设置的就大一些，感谢解答。
