### ISSUE TITLE
使用maskrcnn预测大于725*725的图片没有mask

### ISSUE THREAD

**Issue by Anonymous-99999** [PaddlePaddle/PaddleDetection#3424]
用的是2.0版本，使用2048\*2448的图去训练了一个maskrcnn的模型，预测的时候，如果输入的图仍然是2048\*2448的话，能画出不错的bbox，但是没有mask，mask数组都是0，后来测试，如果输入图片小于等于724*724，则有mask，如果大于等于725\*725，则mask就全为0，预测的结果图上就完全没有mask，这是什么原因呢？

**Comment by jerrywgz** [comment]
可以尝试使用paddle develop版本，安装方法可以参考https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html 近期paddle对mask rcnn预测使用的grid_mask做了修复
