### ISSUE TITLE
经过检查和搜索还是没有解决该问题：Not found any voc record in trainval.txt

### ISSUE THREAD

**Issue by FeiMa-REC** [PaddlePaddle/PaddleDetection#3428]
### 前提：
` %cd PaddleDetection/ `
` %env PYTHONPATH=/home/aistudio/PaddleDetection `
### 已经设置PaddleDetection为工作目录,且安装过程无误。

![图片](https://user-images.githubusercontent.com/62004245/122532026-aa6b8180-d052-11eb-98c8-3fd6bd9a0386.png)

**报错提示，没有识别到VOC格式，开始检查数据集结构。**

![图片](https://user-images.githubusercontent.com/62004245/122532306-f61e2b00-d052-11eb-9809-3a12fea81a96.png)

![图片](https://user-images.githubusercontent.com/62004245/122533116-c4f22a80-d053-11eb-81ef-a7b4c3929b39.png)

![图片](https://user-images.githubusercontent.com/62004245/122533355-0edb1080-d054-11eb-8e5a-8b7fb4012a47.png)

如上图，觉得VOC数据集格式没什么问题，路径应该也没错，为什么会出现BUG？

**Comment by nemonameless** [comment]
请确认下这个数据集格式是否和VOC严格一致，以及JPEGImages和Annotations是否和trainval.txt在同一级目录下。

**Comment by FeiMa-REC** [comment]
>@nemonameless
> 请确认下这个数据集格式是否和VOC严格一致，以及JPEGImages和Annotations是否和trainval.txt在同一级目录下。

数据集格式和目录结构在上面的截图有，检查过好几遍没有发现问题。

**Comment by FeiMa-REC** [comment]
### 问题已经解决，自定义数据集的xml标注不规范。
