### ISSUE TITLE
你好，如何把 ppyolo_tiny_650e_coco.pdparams 转为 onnx 模型

### ISSUE THREAD

**Issue by EdwardVincentMa** [PaddlePaddle/PaddleDetection#3429]
你好，如何把 ppyolo_tiny_650e_coco.pdparams 转为 onnx 模型。非常感谢～

你好，这个模型属于动态图吧，我看了教程，没看懂。请问此模型如何转换

**Comment by yghstill** [comment]
@EdwardVincentMa 请参考模型转onnx教程文档：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_ONNX_MODEL.md
