### ISSUE TITLE
关于FairMOT在window下的运行错误

### ISSUE THREAD

**Issue by ReverseSacle** [PaddlePaddle/PaddleDetection#3430]
如题，目前有几处疑惑的地方。
![问题1](https://user-images.githubusercontent.com/73418195/122537852-9165cf00-d058-11eb-91ac-fa95876920be.png)
![问题2](https://user-images.githubusercontent.com/73418195/122537854-9165cf00-d058-11eb-9e9f-1a8974ff17ec.png)

另外是否是RGBReverse{}这个数据增强导致了下面的问题?
```InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 608, the input's shape is [1, 608, 1088, 3]; the filter's channels is 3, the filter's shape is [16, 3, 7, 7]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.```
```      [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:608 != filter_dims[1] * groups:3.] (at C:/home/workspace/Paddle_release/paddle/fluid/operators/conv_op.cc:100)```
    ```  [operator < conv2d > error] ```

**Comment by nemonameless** [comment]
RGBReverse只是RGB转为BGR或者相反，与NCHW无关的。在linux运行有这个问题吗？

**Comment by ReverseSacle** [comment]
> RGBReverse只是RGB转为BGR或者相反，与NCHW无关的。在linux运行有这个问题吗？

目前还没在linux下测试。windows下重装了两次环境，依然都是 -1073741819(0xc0000005)这个错误，此外我想知道红色的地方是什么问题？

**Comment by ReverseSacle** [comment]
> RGBReverse只是RGB转为BGR或者相反，与NCHW无关的。在linux运行有这个问题吗？

关于这个问题，我在paddle社区找到了相关问题的原因。想问问有什么解决方法？
<img width="702" alt="paddle_问题" src="https://user-images.githubusercontent.com/73418195/122629908-c4f53780-d0f2-11eb-9235-a348ac9c99ac.png">

**Comment by ReverseSacle** [comment]
> RGBReverse只是RGB转为BGR或者相反，与NCHW无关的。在linux运行有这个问题吗？

经排查，发现问题出现在mot_infer.py的predict函数中，如下，当运行到```self.predictor.run()```时会报
```
ValueError: In user code:

    File "tools/export_model.py", line 111, in <module>
      main()
    File "tools/export_model.py", line 107, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 75, in run
      trainer.export(FLAGS.output_dir)
```
之后才会报形状不匹配的错误。
```        
        for i in range(repeats):
            self.predictor.run()      #错误一
            print('assert_1')
            output_names = self.predictor.get_output_names()
            #print('assert_2')
            boxes_tensor = self.predictor.get_output_handle(output_names[0])
            #print('assert_3')
            pred_dets = boxes_tensor.copy_to_cpu()
            #print('assert_4')
            embs_tensor = self.predictor.get_output_handle(output_names[1])
            #print('assert_5')
            pred_embs = embs_tensor.copy_to_cpu()
            #print('assert_6')
```
