### ISSUE TITLE
fairmot下的merge_config()函数

### ISSUE THREAD

**Issue by Dejavusd** [PaddlePaddle/PaddleDetection#3435]
使用fairmot预测视频时会加上 -o weights=output/fairmot_dla34_30e_1088x608/model_final.pdparams
然后我想在infer_mot.py 下main()函数里:
        merge_config(FLAGS.opt) 
改成
        weights='output/fairmot_dla34_30e_1088x608/model_final.pdparams'（这里为我自己的pdparams路径）
        merge_config(weights)

但是会报错：  
File "/home/aistudio/PD/fairmot.py", line 76, in runf
    merge_config(weights)
  File "/home/aistudio/PD/ppdet/core/workspace.py", line 154, in merge_config
    return dict_merge(dct, config)
  File "/home/aistudio/PD/ppdet/core/workspace.py", line 134, in dict_merge
    for k, v in merge_dct.items():
AttributeError: 'str' object has no attribute 'items

我本意是想在pycharm跑，不使用python的命令符来开始运行，请问我该如何添加自己的pdparams来使用

**Comment by nemonameless** [comment]
FLAGS = parser.parse_args() 是解析config里的设置的，可以改这一行 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml#L10
