### ISSUE TITLE
FairMot导出模型后，用deploy/python/mot_infer.py检测视频很慢

### ISSUE THREAD

**Issue by andyzhongzxy** [PaddlePaddle/PaddleDetection#3438]
%cd ~/PaddleDetection-develop
!CUDA_VISIBLE_DEVICES=0 python deploy/python/mot_infer.py --model_dir=output_inference/fairmot_dla34_30e_1088x608 --video_file=demo/2.avi --device=GPU --use_gpu=0
要好几秒才一帧，导出前用tools/infer_mot.py都能十帧每秒
![image](https://user-images.githubusercontent.com/55987753/122661427-9f346500-d1bc-11eb-9a4a-8cfa72e78af4.png)

**Comment by nemonameless** [comment]
--use_gpu=True

**Comment by jerrywgz** [comment]
可以更新下代码，在最新的代码中使用gpu的方式修改--device=gpu

**Comment by andyzhongzxy** [comment]
> --use_gpu=True

这个deploy/python/mot_infer.py里的--threshold是没效果吗，我在飞桨和本地都试过都不能像infer.py可以控制阈值

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/3443 same issue
