### ISSUE TITLE
Random Erasing bug

### ISSUE THREAD

**Issue by xmy0916** [PaddlePaddle/PaddleDetection#3439]
https://github.com/PaddlePaddle/PaddleDetection/blob/86720c1fa0be0c36384faacfb3338eb37c05656b/ppdet/data/transform/operators.py#L203
这一行的heigher这个单词和init里面的变量名对不上，多了个‘e’，一跑就报错...
而且...这英语单词也拼错了吧...没有heigher这个单词，我理解应该是lower对应higher？？？怎么来个变量名heigher...

**Comment by xmy0916** [comment]
代码对应文档里面heigher也拼错了...

**Comment by xmy0916** [comment]
而且修改完后报错：
```
[06/20 15:07:39] reader WARNING: fail to map op [RandomErasingImage_a2f7f3] with error: apply() takes 2 positional arguments but 3 were given and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 56, in __call__
    data = f(data)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/operators.py", line 101, in __call__
    sample = self.apply(sample, context)
TypeError: apply() takes 2 positional arguments but 3 were given
```
然后在paddledetection里面搜这个数据增强也没有一个配置文件用了，只有静态图有一个配置文件有示例配置...有点怀疑这个数据增强qa测试过能用吗？

**Comment by jerrywgz** [comment]
可以更新下代码，目前我们已经修复了这个问题

**Comment by wstchhwp** [comment]
> 而且修改完后报错：
> 
> ```
> [06/20 15:07:39] reader WARNING: fail to map op [RandomErasingImage_a2f7f3] with error: apply() takes 2 positional arguments but 3 were given and stack:
> Traceback (most recent call last):
>   File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 56, in __call__
>     data = f(data)
>   File "/home/aistudio/PaddleDetection/ppdet/data/transform/operators.py", line 101, in __call__
>     sample = self.apply(sample, context)
> TypeError: apply() takes 2 positional arguments but 3 were given
> ```
> 
> 然后在paddledetection里面搜这个数据增强也没有一个配置文件用了，只有静态图有一个配置文件有示例配置...有点怀疑这个数据增强qa测试过能用吗？

现在版本还是报错。。

**Comment by wawatt** [comment]
> > 而且修改完后报错：
> > ```
> > [06/20 15:07:39] reader WARNING: fail to map op [RandomErasingImage_a2f7f3] with error: apply() takes 2 positional arguments but 3 were given and stack:
> > Traceback (most recent call last):
> >   File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 56, in __call__
> >     data = f(data)
> >   File "/home/aistudio/PaddleDetection/ppdet/data/transform/operators.py", line 101, in __call__
> >     sample = self.apply(sample, context)
> > TypeError: apply() takes 2 positional arguments but 3 were given
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后在paddledetection里面搜这个数据增强也没有一个配置文件用了，只有静态图有一个配置文件有示例配置...有点怀疑这个数据增强qa测试过能用吗？
> 
> 现在版本还是报错。。

你好，这个报错解决了吗

**Comment by xmy0916** [comment]
@wawatt 不知道哎不好用
