### ISSUE TITLE
paddledetection读取VOC格式数据集报错

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleDetection#3442]
![image](https://user-images.githubusercontent.com/40813430/122670649-af1c6b00-d1f5-11eb-907d-4120c56aa280.png)
如上图所示，根据roadsign_voc文件夹的格式建立了power_voc文件夹，并且修改了下面的yml文件：
![image](https://user-images.githubusercontent.com/40813430/122670729-12a69880-d1f6-11eb-9b5d-a39b2de32b7e.png)
![image](https://user-images.githubusercontent.com/40813430/122670738-1f2af100-d1f6-11eb-9df2-7092eb46e4ba.png)
但是运行代码python tools/train.py -c configs/]ppyolo/ppyolov2_r50vd_dcn_voc.yml报了如下的错误：
![image](https://user-images.githubusercontent.com/40813430/122670680-ca877600-d1f5-11eb-87c0-86ad4d00fa74.png)
请问如何解决呢，谢谢

**Comment by jerrywgz** [comment]
请问其他配置是否做过修改

**Comment by wstchhwp** [comment]
没有做过相应修改

**Comment by jerrywgz** [comment]
我这边在voc数据集上验证是能正常跑的，从报错信息来看是mixup的时候输入的gt box维度不一致导致的，可以在这里 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/data/transform/operators.py#L1619 打印下gt_box 看看标注信息上是否有问题。 另外调试过程建议将worker_num设置为1
