### ISSUE TITLE
deploy/python/mot_infer.py的--threshold阈值不起作用

### ISSUE THREAD

**Issue by andyzhongzxy** [PaddlePaddle/PaddleDetection#3443]
![image](https://user-images.githubusercontent.com/55987753/122671795-eb9e9580-d1fa-11eb-87ab-e6a705aefe50.png)
python mot_infer.py --model_dir=.\model\ --video_file=D:\Download\mot_images\3.mp4 --device=GPU --use_gpu=True --threshold=0.5
依旧有很多分值小于0.5的出现

**Comment by andyzhongzxy** [comment]
不管是飞桨上还是本地，阈值都不起作用

**Comment by andyzhongzxy** [comment]
deploy/python的

**Comment by jerrywgz** [comment]
是的，当前threshold在mot预测的时候没有起作用，已经提pr修复了https://github.com/PaddlePaddle/PaddleDetection/pull/3444
