### ISSUE TITLE
优化器选择Adam优化器，会出现Corrupt JPEG data: premature end of data segment

### ISSUE THREAD

**Issue by xupengao** [PaddlePaddle/PaddleDetection#3445]
优化器参数设置，训练cascade rcnn模型，使用默认优化器并没有问题，换成Adam训练到一半就出问题了
OptimizerBuilder:
  optimizer:
    type: Adam
  regularizer:
    factor: 0.0
    type: L2

**Comment by yghstill** [comment]
@xupengao 看报错是数据预处理出现问题，方便发下完整报错信息吗？

**Comment by xupengao** [comment]
只是训练过程中出现了这句话，但是loss还在正常更新，不过eval的时候会没有结果。数据增强我是新加了mixup和cutmix两个增强方式
  - !DecodeImage
    to_rgb: True
    with_mixup: True
    with_cutmix: True
  - !MixupImage
    alpha: 1.5
    beta: 1.5
  - !CutmixImage
    alpha: 1.5
    beta: 1.5

**Comment by yghstill** [comment]
@xupengao 
- 加上mixup和cutmix后，收敛速度会变慢，看loss变化趋势是否能正常收敛？
- 之前没有在rcnn系列算法中验证过这两个算子，可以试下AutoAugment，这个效果很好：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/configs/rcnn_enhance/cascade_rcnn_dcn_r50_vd_fpn_3x_server_side.yml#L126-L127
