### ISSUE TITLE
paddleDetection是否有数据扩充？

### ISSUE THREAD

**Issue by shen-wenxin** [PaddlePaddle/PaddleDetection#3452]
您好，我想问一下：
PaddleDetection是否有在训练的时候默认给dataset做数据扩充呢（比如旋转、裁剪等），类似于pytorch种transform的功能

我是否还需要在训练之前自己做一次训练扩充呢(指单纯的旋转、裁剪、平移）？

**Comment by yghstill** [comment]
@shen-wenxin ppdet中有丰富的数据增强方法，可搭配使用：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/advanced_tutorials/READER.md#31%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA%E7%AE%97%E5%AD%90

**Comment by shen-wenxin** [comment]
这太有用了，非常感谢您
