### ISSUE TITLE
windows10下c++部署问题

### ISSUE THREAD

**Issue by lhx123456-lang** [PaddlePaddle/PaddleDetection#3454]
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0621 17:39:40.062985 21472 analysis_config.cc:424] use_dlnne_:0
I0621 17:39:40.063984 21472 analysis_config.cc:424] use_dlnne_:0
I0621 17:39:40.063984 21472 analysis_config.cc:424] use_dlnne_:0
I0621 17:39:40.063984 21472 analysis_config.cc:424] use_dlnne_:0
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]
class=3 confidence=0.75 rect=[245 222 258 268]
class=3 confidence=0.51 rect=[245 119 258 145]

已完成cmake编译，并通过调用可运行，但是运行结果明明只有两个bbox，但是保存bbox的容器内却重复存在了几十个，请问有遇到过这种情况吗

**Comment by liuhuiCNN** [comment]
你好，感谢反馈，已经在 #3392 修复

**Comment by yghstill** [comment]
@lhx123456-lang 请使用paddledetection develop分支最新代码编译cpp预测代码再试下。
