### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'

### ISSUE THREAD

**Issue by 442616159** [PaddlePaddle/PaddleDetection#3455]
明明已经安装成功paddle-gpu了
在test时还是报错
ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'

**Comment by 442616159** [comment]
File "ppdet/modeling/tests/test_architectures.py", line 20, in <module>
    import ppdet
  File "/home/cyd/.conda/envs/paddle1/lib/python3.6/site-packages/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/home/cyd/.conda/envs/paddle1/lib/python3.6/site-packages/ppdet/data/__init__.py", line 17, in <module>
    from . import reader
  File "/home/cyd/.conda/envs/paddle1/lib/python3.6/site-packages/ppdet/data/reader.py", line 28, in <module>
    from paddle.fluid.dataloader.collate import default_collate_fn
ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'

**Comment by yghstill** [comment]
@442616159 请安装paddlepaddle 2.1.0版本

**Comment by 442616159** [comment]
可是我的cuda是11.1没有对应的2.1.0版本阿

**Comment by 442616159** [comment]
可是我的cuda是11.1没有对应的2.1.0版本阿 @yghstill

**Comment by yghstill** [comment]
@442616159 https://www.paddlepaddle.org.cn/whl/mkl/stable.html 下载post110试下呢，或者回退paddleDetection版本到release 2.0

**Comment by 442616159** [comment]
我是linux系统这上面没有@yghstill

**Comment by yghstill** [comment]
@442616159 https://www.paddlepaddle.org.cn/whl/cu110/mkl/develop.html 选择合适的python版本下载即可

**Comment by 442616159** [comment]
pip 直接装吗@yghstill

**Comment by 442616159** [comment]
比如pip install paddlepaddle-gpu==2.1.0.dev0.post110 -f https://www.paddlepaddle.org.cn/whl/mkl/stable.html

**Comment by 442616159** [comment]
@yghstill 是这样吗

**Comment by 442616159** [comment]
我不知道这个网址的版本我怎么下载下来

**Comment by 442616159** [comment]
https://www.paddlepaddle.org.cn/whl/mkl/stable.html 点击不是下载啊@yghstill

**Comment by 442616159** [comment]
https://www.paddlepaddle.org.cn/whl/cu110/mkl/develop.html 这个点击下载不了

**Comment by yghstill** [comment]
@442616159 可以试下：
```
pip install paddlepaddle-gpu==2.1.0.dev0.post110 -f https://www.paddlepaddle.org.cn/whl/cu110/mkl/develop.html 
```
或者从链接中直接下载安装包到本地，然后安装。
