### ISSUE TITLE
ppyolo_tiny 转 mnn 失败

### ISSUE THREAD

**Issue by EdwardVincentMa** [PaddlePaddle/PaddleDetection#3457]
你好，请问 ppyolo_tiny 转 onnx 成功了，但是，onnx 到 mnn 失败，请问是否 mnn 支持所有 op？

错误提示：TopK 为空值

**Comment by yghstill** [comment]
@EdwardVincentMa mnn可能TopK这个op还不支持，TopK是yolo_box这个API中的算子，可以在导出ppyolo_tiny模型时不导出yolo_box和nms，放在后处理中进行，不执行post_process 即可：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/modeling/architectures/yolo.py#L93

**Comment by EdwardVincentMa** [comment]
> @EdwardVincentMa mnn可能TopK这个op还不支持，TopK是yolo_box这个API中的算子，可以在导出ppyolo_tiny模型时不导出yolo_box和nms，放在后处理中进行，不执行post_process 即可：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/modeling/architectures/yolo.py#L93

你好，转模型如何选择输出节点？规避 nms 和 yolo_box

**Comment by yghstill** [comment]
@EdwardVincentMa 在 nms 和 yolo_box之前直接return即可

**Comment by EdwardVincentMa** [comment]
> @EdwardVincentMa 在 nms 和 yolo_box之前直接return即可

可是我之前遇到过问题，修改任何代码无效。不起作用，哪怕调用 setup.py

**Comment by yghstill** [comment]
@EdwardVincentMa 卸载一下PaddleDetection：python setup.py uninstall ，然后再修改完再重新：python setup.py install

**Comment by EdwardVincentMa** [comment]
> @EdwardVincentMa 卸载一下PaddleDetection：python setup.py uninstall ，然后再修改完再重新：python setup.py install

**Comment by EdwardVincentMa** [comment]
> @EdwardVincentMa mnn可能TopK这个op还不支持，TopK是yolo_box这个API中的算子，可以在导出ppyolo_tiny模型时不导出yolo_box和nms，放在后处理中进行，不执行post_process 即可：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/modeling/architectures/yolo.py#L93

你好，我工程没这blob这个文件夹，只有ppdet/modeling/architectures/yolo.py

**Comment by EdwardVincentMa** [comment]
> @EdwardVincentMa 卸载一下PaddleDetection：python setup.py uninstall ，然后再修改完再重新：python setup.py install

解决了，不能pip install paddledetection，只能源码安装
