### ISSUE TITLE
Keypoint detection framerate

### ISSUE THREAD

**Issue by Brumeux** [PaddlePaddle/PaddleDetection#3459]
Hey, I have successfully installed everything and inference works fine. However I am having issues using detector in real time, frame rate is very low.

I used the exemple inference line with exported models:
`python deploy/python/keypoint_det_unite_infer.py --det_model_dir=output_inference/ppyolo_r50vd_dcn_2x_coco/ --keypoint_model_dir=output_inference/hrnet_w32_384x288/ --video_file=../video/xxx.mp4  --use_gpu=True`

I am using  nvidia 3090 and I can't get over 5 frames per second. Is this normal or my gpu acceleration isnt working ? The football gif exemple is much faster but maybe it is not performed real time ?
Thank for your help

**Comment by zhiboniu** [comment]
The inference time depends much on person number per frame. The average inference time of hrnet(batchsize=1) is about 20ms, so the total cost of a frame is about 20xN(person number)+ det time. 
And yes, the footbal exemple is not performed real time.
Does this help you?

**Comment by Brumeux** [comment]
Hey, thanks yes it helps a lot. Would you know of any solution using PaddlePaddle (or anything else) that would run faster for multiple person on screen (max 5-10) ?
Thank you for your insight

**Comment by zhiboniu** [comment]
There is some solutions to try:
1) You may try the DarkPose with half input size which supported by develop branch.
2) Use a light backbone which need a new pretrained model that you should prepare it youself. Or you can drop the pretrained model if you have extra train data.
3) Use the both two.

**Comment by Brumeux** [comment]
Weights for DarkPose would be the same as hrnet ? For exemple hrnet_w32_256x192.pdparams with dark_hrnet_w32_256x192.yml config file ? Thanks a lot

**Comment by Brumeux** [comment]
After exporting model "configs/keypoint/hrnet/dark_hrnet_w32_256x192.yml", I tried inference with 
`python deploy/python/keypoint_det_unite_infer.py --det_model_dir=output_inference/ppyolo_r50vd_dcn_2x_coco/ --keypoint_model_dir=output_inference/dark_hrnet_w32_256x192/ --camera_id=0`

But I get error:

-----------  Running Arguments -----------
camera_id: 0
cpu_threads: 1
det_model_dir: output_inference/ppyolo_r50vd_dcn_2x_coco/
det_threshold: 0.5
device: cpu
enable_mkldnn: False
image_dir: None
image_file: None
keypoint_model_dir: output_inference/dark_hrnet_w32_256x192/
keypoint_threshold: 0.5
output_dir: output
run_benchmark: False
run_mode: fluid
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
video_file: None

Traceback (most recent call last):
  File "deploy/python/keypoint_det_unite_infer.py", line 202, in <module>
    main()
  File "deploy/python/keypoint_det_unite_infer.py", line 157, in main
    pred_config = PredictConfig(FLAGS.det_model_dir)
  File "E:\Installers\PaddleDetection-develop\PaddleDetection-develop\deploy\python\infer.py", line 328, in __init__
    self.use_dynamic_shape = yml_conf['use_dynamic_shape']
KeyError: 'use_dynamic_shape'


Also it wont let me use argument --use_gpu=True

Thanks for your help

**Comment by zhiboniu** [comment]
You should export inference model again because we update the code lately. The command to inference is update too(use_gpu=True --> device=gpu), you can reference to the new README.
And to get faster inference time, bigger batchsize may help which now is set to 1, we will update our code to support that soon.

**Comment by Brumeux** [comment]
> You should export inference model again because we update the code lately. The command to inference is update too(use_gpu=True --> device=gpu), you can reference to the new README.
> And to get faster inference time, bigger batchsize may help which now is set to 1, we will update our code to support that soon.

I exported inference model again and changed inference command as in the new readme from keypoint directory. I still get the error posted above. I also get same error with only infer.py and re-exported ppyolo model.
Also yes, I think bigger batch size would help a lot.
Thanks

**Comment by zhiboniu** [comment]
try add a line 'use_dynamic_shape: False' in your det yml file and then export model again

**Comment by yghstill** [comment]
@Brumeux Please add `use_dynamic_shape: False` in `output_inference/ppyolo_r50vd_dcn_2x_coco/infer_cfg.yml`

**Comment by Brumeux** [comment]
That worked, thanks. Performance are a bit better but still not enough for true real time with 3090 and multiple persons on screen. I'm not very sure how to setup another lighter backbone using paddlepaddle. I think I will wait for batch processing unless this is an easy step.
Thank you!

**Comment by zhiboniu** [comment]
You can try batch inference now, the pr is merged.
