### ISSUE TITLE
PaddleDetection的maskrcnn训练时报错

### ISSUE THREAD

**Issue by wflrz123** [PaddlePaddle/PaddleDetection#3461]
ValueError: (InvalidArgument) The rois_batch_size and imgs batch_size must be the same. But received rois_batch_size = 1, batch_size = 16
  [Hint: Expected rois_batch_size == batch_size, but received rois_batch_size:1 != batch_size:16.] (at /paddle/paddle/fluid/operators/roi_align_op.cu:277)
  [operator < roi_align > error]
我在配置文件里设置的batchsize是16，突然报rois_batch_size不等于batch_size的错误，什么是rois_batch_size啊？没找到设置的地方

**Comment by wflrz123** [comment]
worker_num: 2
TrainReader:
  sample_transforms:
  - Decode: {}
  - RandomResize: {target_size: [[640, 360]], interp: 2, keep_ratio: True}
  - RandomFlip: {prob: 0.5}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 16
  shuffle: true
  drop_last: true
  collate_batch: false
  use_shared_memory: true

EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [640, 360], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 16
  shuffle: false
  drop_last: false


TestReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [640, 360], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 16
  shuffle: false
  drop_last: false
这是配置batch_size的文件

**Comment by 1450976314** [comment]
你好，我训练cascade rcnn时也遇到相同的问题。请问你解决了吗

**Comment by jerrywgz** [comment]
有修改过模型代码吗？另外paddle版本是多少？

**Comment by 1450976314** [comment]
首先，感激你抽空回答我的问题。除了anchor_size，epoch参数外，就修改了batch_size为4。然后使用的是cascade rcnn。paddle版本为2.0.1。请问有不修改paddle版本的方法吗？------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月23日(星期三) 下午2:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] PaddleDetection的maskrcnn训练时报错 (#3461)

**Comment by jerrywgz** [comment]
如果使用paddle2.0.1版本，建议使用paddledetection release/2.0版本，我这边测试了cascade rcnn训练正常

**Comment by 1450976314** [comment]
我去尝试一下。感谢你的帮助------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月23日(星期三) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] PaddleDetection的maskrcnn训练时报错 (#3461)
