### ISSUE TITLE
请问现在的版本有可视化GT的脚本了吗？

### ISSUE THREAD

**Issue by raymondchu-z** [PaddlePaddle/PaddleDetection#3466]
需要可视化GT以及模型预测，之前有[issue](https://github.com/PaddlePaddle/PaddleDetection/issues/872)提过这个建议，请问现在有相应的接口或脚本了吗？

**Comment by liuhuiCNN** [comment]
这里有数据处理后可视化函数，您可以参考下：https://github.com/PaddlePaddle/PaddleDetection/blob/e1e02efe93246c3f681c4e9605e44134a0aae72a/ppdet/data/transform/operators.py#L1754

**Comment by raymondchu-z** [comment]
> 这里有数据处理后可视化函数，您可以参考下：
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/e1e02efe93246c3f681c4e9605e44134a0aae72a/ppdet/data/transform/operators.py#L1754

好的谢谢。请问，我想在eval过程中将推理错误的的目标画出来，应该在哪个文件里面改？

**Comment by liuhuiCNN** [comment]
> > 这里有数据处理后可视化函数，您可以参考下：
> > https://github.com/PaddlePaddle/PaddleDetection/blob/e1e02efe93246c3f681c4e9605e44134a0aae72a/ppdet/data/transform/operators.py#L1754
> 
> 好的谢谢。请问，我想在eval过程中将推理错误的的目标画出来，应该在哪个文件里面改？

您可以eval时增加 `--json_eval` 参数 把eval结果保存下来，然后再可视化。

**Comment by raymondchu-z** [comment]
> 您可以eval时增加 `--json_eval` 参数 把eval结果保存下来，然后再可视化。

@liuhuiCNN你好，eval时增加 `--json_eval` 参数后报错`assert metric == 'COCO'`。我用的数据格式是VOC的，如何保存eval结果？
而且看输出提示， `--json_eval`是读取`output_eval`路径下的json文件进行评估，而不是保存评估结果？
