### ISSUE TITLE
solov2输出json问题

### ISSUE THREAD

**Issue by wflrz123** [PaddlePaddle/PaddleDetection#3470]
![image](https://user-images.githubusercontent.com/48908943/122901778-71981900-d380-11eb-9e19-19a58854e9e3.png)
solov2输出json中的segementation是RLE格式的，能否修改为polygon多边形格式（坐标形式）？

**Comment by liuhuiCNN** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/e1e02efe93246c3f681c4e9605e44134a0aae72a/ppdet/metrics/json_results.py#L70 这里是显示分割结果函数，您可以在调用rle编码 `rle = mask_util.encodenp.array(mask[:, :, None], order="F", dtype="uint8"))[0]` 之前获取您需要的结果。
