### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'

### ISSUE THREAD

**Issue by Dejavusd** [PaddlePaddle/PaddleDetection#3471]
我在本地pycharm运行的时候报错 ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'
但是运行 paddle.fluid.install_check.run_check()却可以：
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now

paddle gpu版本2.1.0

**Comment by liuhuiCNN** [comment]
卸载重新安装一下试试？

**Comment by Dejavusd** [comment]
> 卸载重新安装一下试试？

我刚刚试过了，重装了一遍，还是报错 ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'
我使用的是paddle官网里面的 pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple （cuda10.2版本）

**Comment by liuhuiCNN** [comment]
> > 卸载重新安装一下试试？
> 
> 我刚刚试过了，重装了一遍，还是报错 ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'
> 我使用的是paddle官网里面的 pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple （cuda10.2版本）

从这里： https://paddlepaddle.org.cn/whl/mkl/stable.html 找到对应的paddle包，本地安装一下试一下。

**Comment by yghstill** [comment]
@Dejavusd 需要安装paddlepaddle 2.1.0以上版本

**Comment by Dejavusd** [comment]
> @Dejavusd 需要安装paddlepaddle 2.1.0以上版本

我安装的就是 官网里面的2.1版本

**Comment by Dejavusd** [comment]
> > > 卸载重新安装一下试试？
> > 
> > 
> > 我刚刚试过了，重装了一遍，还是报错 ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'
> > 我使用的是paddle官网里面的 pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple （cuda10.2版本）
> 
> 从这里： https://paddlepaddle.org.cn/whl/mkl/stable.html 找到对应的paddle包，本地安装一下试一下。

这里面没我需要的cuda10.2的版本，该不会我需要重新安装cuda10.1版本来适应post101？
我本来是想安装10.1的可是看到官方那里 “如果你使用的是非安培架构的GPU，推荐使用CUDA10.2，性能更优。”才装的10.2（哭，小小抱怨一下）

**Comment by yghstill** [comment]
@Dejavusd 那你可以安装最新develop 的PaddlePaddle版本https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html

**Comment by Dejavusd** [comment]
> @Dejavusd 那你可以安装最新develop 的PaddlePaddle版本https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html

呜，我的电脑是Windows系统的，而且我也不会用Linux

**Comment by Dejavusd** [comment]
> > > 卸载重新安装一下试试？
> > 
> > 
> > 我刚刚试过了，重装了一遍，还是报错 ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'
> > 我使用的是paddle官网里面的 pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple （cuda10.2版本）
> 
> 从这里： https://paddlepaddle.org.cn/whl/mkl/stable.html 找到对应的paddle包，本地安装一下试一下。

我装的cuda10.1版的也出现同样的问题 : ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'

**Comment by yghstill** [comment]
@Dejavusd 安装的是PaddlePaddle 2.1.0吗？打印一下paddle版本看下：
```shell
import paddle
print(paddle.__version__)
```

**Comment by learningpro** [comment]
直接安装cuda11和cudnn8，再使用paddle的2.1.1-cuda11那个docker，完美运行

**Comment by Fly-hub** [comment]
报错解决方法是将paddle改成2.1版本，我使用2.0版本就报这个错改为2.1就好了

**Comment by Fly-hub** [comment]
我是在aistudio平台上运行的
