### ISSUE TITLE
ubuntu16.04 CUDA9.2 安装paddlepaddle-gpu develop 和paddledetection develop ?

### ISSUE THREAD

**Issue by ResonLee** [PaddlePaddle/PaddleDetection#3474]
系统：ubuntu 16.04 Cuda 9.2 cudnn7.6.3
1、安装paddlepaddle-gpu的语句是啥？在安装文档里找了半天也没找到
2、通过anaconda在虚拟环境里安装cudatoolkit 10.1 和cudnn7.6.5后，能在虚拟环境里安装cuda10.1 对应的paddlepaddle-gpu develop吗？或者通过其他办法在虚拟环境中安装10.1对应的版本吗？

**Comment by wangxinxin08** [comment]
安装PaddlePaddle-gpu develop可以参考页面：https://www.paddlepaddle.org.cn/
