### ISSUE TITLE
只训练一轮epoch就结束了

### ISSUE THREAD

**Issue by lizhenhanabc** [PaddlePaddle/PaddleDetection#3476]
根据教程，输入 python tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml ，只训练一轮就结束了，没有任何报错，环境python3.7，paddledetection是clone的2.1-gpu版本，epoch是默认的12。
![1](https://user-images.githubusercontent.com/60728647/123026379-a488ee00-d40e-11eb-8007-b45ae1c7e8a7.PNG)

**Comment by wangxinxin08** [comment]
麻烦贴下Paddle版本，PaddleDetection版本，我明天找台windows机器复现一下

**Comment by lizhenhanabc** [comment]
> 麻烦贴下Paddle版本，PaddleDetection版本，我明天找台windows机器复现一下

版本是2.1.0
![2](https://user-images.githubusercontent.com/60728647/123197194-c3a28100-d4dd-11eb-8cc6-c5e0bfda2e19.PNG)
之前这台电脑有用过darknet跑yolo4，这个显卡配置和驱动应该是没问题，然后用paddle训练的时候，设置了gpu训练，但是gpu算力占用只有2%左右，第一轮的训练完，还没保存就结束了（设置12个epoch，每个epoch保存一次）

**Comment by wangxinxin08** [comment]
我们在linux下没遇到过这个问题，等下找台windows机器试下

**Comment by lizhenhanabc** [comment]
> 我们在linux下没遇到过这个问题，等下找台windows机器试下

麻烦你了- ̗̀(๑ᵔ⌔ᵔ๑)

**Comment by wangxinxin08** [comment]
这个问题我同事有定位过问题，目前还没有一个确切的结论，不使用anaconda，直接使用python环境不会出现这个问题

**Comment by lizhenhanabc** [comment]
> 这个问题我同事有定位过问题，目前还没有一个确切的结论，不使用anaconda，直接使用python环境不会出现这个问题
好的，我用python环境试一下，还有想问一下paddledetection的maskrcnn或者solov2能在C++上部署吗？

**Comment by wangxinxin08** [comment]
mask rcnn可以，solov2之后会支持

**Comment by lizhenhanabc** [comment]
> mask rcnn可以，solov2之后会支持

我换成pycharm来弄，还是只训练一轮就结束了，output里面没有保存，我看到也有人在问，是不是在哪里return掉了？我换成CPU训练，也是只训练一轮，output没有保存。
![1](https://user-images.githubusercontent.com/60728647/123504376-6fd59a80-d68b-11eb-9009-c337aa8af681.PNG)
![2](https://user-images.githubusercontent.com/60728647/123504379-76641200-d68b-11eb-8c21-d1c7ebc91df1.PNG)

**Comment by cpsu00** [comment]
我也在FRCNN遇到一樣的問題
python tools/train.py -c configs/faster_rcnn/faster_rcnn_r50_1x.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar

![image](https://user-images.githubusercontent.com/85643374/123605723-b9aab600-d82e-11eb-832b-11addf331116.png)

**Comment by lizhenhanabc** [comment]
@wangxinxin08 这个确实是个问题。。。有定位到问题所在吗？

**Comment by wangxinxin08** [comment]
@lizhenhanabc 不用anaconda创建的虚拟环境不会出现该问题，不是已经说过用原生python环境训练吗？

**Comment by wwwPADDLE** [comment]
> @wangxinxin08这个确实是一个问题。。。有锁定到问题吗？

请问您解决这个问题了吗 我也是只能训练迭代一轮 就跳出是什么问题呢？ （试了环境用anaconda和python原声环境 都会出现这个问题）
![5736363ebd0ad6386099f9399fb408d](https://user-images.githubusercontent.com/57277333/124059849-5dc67400-da5e-11eb-9db8-e4a5ecbc7738.png)

**Comment by robisly** [comment]
同样遇到这个问题，也同样试了环境用anaconda和python原生环境  都没有解决这个问题

**Comment by lizhenhanabc** [comment]
> > @wangxinxin08这个确实是一个问题。。。有锁定到问题吗？
> 
> 请问您解决这个问题了吗 我也是只能训练迭代一轮 就跳出是什么问题呢？ （试了环境用anaconda和python原声环境 都会出现这个问题）
> ![5736363ebd0ad6386099f9399fb408d](https://user-images.githubusercontent.com/57277333/124059849-5dc67400-da5e-11eb-9db8-e4a5ecbc7738.png)

我的问题还没解决，我试了用pycharm创建的python环境，也是不行。

**Comment by lizhenhanabc** [comment]
> 同样遇到这个问题，也同样试了环境用anaconda和python原生环境 都没有解决这个问题

@wangxinxin08 有定位到吗？确实很多人都遇到。。。

**Comment by oldZhangYH** [comment]
我也遇到了这个问题，ubuntu上没有问题。但是在windows上训练一轮就跳出也不保存模型

**Comment by wexin-c** [comment]
![image](https://user-images.githubusercontent.com/78461277/125180435-ad5e2a00-e22c-11eb-92a1-4cf6304a94b7.png)
我也遇到这个情况，请问解决了吗

**Comment by oldZhangYH** [comment]
没



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月11日(周日) 上午9:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] 只训练一轮epoch就结束了 (#3476)




 

 我也遇到这个情况，请问解决了吗

**Comment by yumeng88** [comment]
### 我的是faster_rcnn_r50_fpn_1x_coco.yml，训练到11个epoch跳出来的，然后模型保存了前十个的

**Comment by xlh9718** [comment]
我也遇到这个问题，还没有解决吗？

**Comment by wexin-c** [comment]
据说windows系统不兼容的问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月23日(星期五) 下午4:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] 只训练一轮epoch就结束了 (#3476)





 
我也遇到这个问题，还没有解决吗？

**Comment by xlh9718** [comment]
非常感谢您的回复。
奇怪的是，我在家里的电脑也是 win10 系统，可以正常训练跑完指定的 epoch。
但在公司的电脑上，就是不行。
下载的模型，推理测试都正常的，说明 CUDA 驱动都 OK 的。
训练过程中，PaddleDet&nbsp; 内部记录的有 log 吗，可以帮助诊断这个问题？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月23日(星期五) 下午4:15
***@***.***&gt;;
抄送:&nbsp;"XLH"<xlh9718@***@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 只训练一轮epoch就结束了 (#3476)





 据说windows系统不兼容的问题 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年7月23日(星期五) 下午4:11 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [PaddlePaddle/PaddleDetection] 只训练一轮epoch就结束了 (#3476) 
 
 
 
 
 
   
 我也遇到这个问题，还没有解决吗？

**Comment by wexin-c** [comment]
动态图版本好像不行&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月23日(星期五) 下午5:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 只训练一轮epoch就结束了 (#3476)





 非常感谢您的回复。 
 奇怪的是，我在家里的电脑也是 win10 系统，可以正常训练跑完指定的 epoch。 
 但在公司的电脑上，就是不行。 
 下载的模型，推理测试都正常的，说明 CUDA 驱动都 OK 的。 
 训练过程中，PaddleDet&amp;nbsp; 内部记录的有 log 吗，可以帮助诊断这个问题？ 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年7月23日(星期五) 下午4:15 
 ***@***.***&amp;gt;; 
 抄送:&amp;nbsp;"XLH"<xlh9718@***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [PaddlePaddle/PaddleDetection] 只训练一轮epoch就结束了 (#3476) 
 
 
 
 
 
  据说windows系统不兼容的问题  
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2021年7月23日(星期五) 下午4:11  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [PaddlePaddle/PaddleDetection] 只训练一轮epoch就结束了 (#3476)  
   
   
   
   
   
     
  我也遇到这个问题，还没有解决吗？

**Comment by xlh9718** [comment]
PaddleDetection 2.2 版本解决了上面的问题，感谢！

**Comment by FAFUzxf** [comment]
我用的是最新的2.3版本，也出现了这个问题，请问具体是什么原因造成的？

**Comment by Synmul** [comment]
我PaddleDetection2.5版本 win10  python原生环境 也遇到这个问题 有解决方法

**Comment by kuhippo** [comment]
我也有

**Comment by Synmul** [comment]
> 我也有

换2.2就解决了.

**Comment by kuhippo** [comment]
我2.6也有这个问题

**Comment by Synmul** [comment]
> 我2.6也有这个问题

把Paddle版本退回去，我也忘了是不是2.2了，不是这个PaddleDetection的版本.
