### ISSUE TITLE
PPYOLOV2训练数据

### ISSUE THREAD

**Issue by shishifang** [PaddlePaddle/PaddleDetection#3478]
请问， PPYOLOV2训练时，采用VOC数据格式，如果标记背景类别，那么.xml文件里面还有没有object字段？或者背景类别应该怎么标记？（背景类不是包含目标的图片！！！）

**Comment by wangxinxin08** [comment]
背景类别不需要标记

**Comment by shishifang** [comment]
> 
> 
> 背景类别不需要标记

![123](https://user-images.githubusercontent.com/50400151/123042836-fb4ff100-d429-11eb-9117-ef2147468740.JPG)
不需要标记的话，如图train.txt中的格式（图片的路径 标记xml文件的路径），如果不标记就没有.xml文件，那么这里只有.jpg的路径，.xml的路径是什么呢？

**Comment by shishifang** [comment]
> 
> 
> > 背景类别不需要标记
> 
> ![123](https://user-images.githubusercontent.com/50400151/123042836-fb4ff100-d429-11eb-9117-ef2147468740.JPG)
> 不需要标记的话，如图train.txt中的格式（图片的路径 标记xml文件的路径），如果不标记就没有.xml文件，那么这里只有.jpg的路径，.xml的路径是什么呢？
@wangxinxin08

**Comment by wangxinxin08** [comment]
需要有xml文件，xml文件中不需要包含object字段

**Comment by shishifang** [comment]
> 
> 
> 需要有xml文件，xml文件中不需要包含object字段

好的，谢谢
