### ISSUE TITLE
单卡训练报错

### ISSUE THREAD

**Issue by GexLoong** [PaddlePaddle/PaddleDetection#3480]
训练报错ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.

训练语句python -m paddle.distributed.launch --log_dir=./fairmot_dla34_30e_1088x608/ tools/train.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml --use_vdl=true --vdl_log_dir=output/fairmot_dla34_30e_1088x608/vdl_dir/scalar

**Comment by nemonameless** [comment]
单卡不需要 paddle.distributed.launch
```
CUDA_VISIBLE_DEVICES=0 python tools/train.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml
```
