### ISSUE TITLE
paddleDetection release/2.1 训练报错

### ISSUE THREAD

**Issue by cuesong** [PaddlePaddle/PaddleDetection#3483]
训练参数：边训练边评估
export CUDA_VISIBLE_DEVICES=0,4,5
python -m paddle.distributed.launch --gpus 0,4,5 tools/train.py -c configs/yolov3/mul_yolov3_darknet53_270e_voc.yml --eval -o use_gpu=true --use_vdl=True --vdl_log_dir=vdl_dir/scalar

保存模型时报错：

06/23 15:43:36] ppdet.engine INFO: Epoch: [0] [280/295] learning_rate: 0.000018 loss_xy: 10.935499 loss_wh: 7.782958 loss_obj: 33.818359 loss_cls: 9.891621 loss: 62.345547 eta: 1 day, 3:48:29 batch_cost: 1.2332 data_cost: 0.0020 ips: 3.2435 images/s
[06/23 15:44:03] ppdet.utils.checkpoint INFO: Save checkpoint: output/mul_yolov3_darknet53_270e_voc
Corrupt JPEG data: 2 extraneous bytes before marker 0xd9

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&)
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 2ul, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, long>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, paddle::platform::complex64>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, paddle::platform::complex128> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   void paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, float>::SliceCompute<2ul>(paddle::framework::ExecutionContext const&) const
5   Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 2, 1, int>, 16, Eigen::MakePointer>, Eigen::TensorSlicingOp<Eigen::DSizes<int, 2> const, Eigen::DSizes<int, 2> const, Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, int>, 16, Eigen::MakePointer> const> const> const, Eigen::DefaultDevice, true, (Eigen::internal::TiledEvaluation)1>::run(Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 2, 1, int>, 16, Eigen::MakePointer>, Eigen::TensorSlicingOp<Eigen::DSizes<int, 2> const, Eigen::DSizes<int, 2> const, Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, int>, 16, Eigen::MakePointer> const> const> const&, Eigen::DefaultDevice const&)
6   paddle::framework::SignalHandle(char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1624434244 (unix time) try "date -d @1624434244" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x4) received by PID 59845 (TID 0x7fc55d581740) from PID 4 ***]

INFO 2021-06-23 15:44:11,273 launch_utils.py:327] terminate all the procs
ERROR 2021-06-23 15:44:11,273 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.

**Comment by cuesong** [comment]
加上--eval就会报错，不加没事

**Comment by cuesong** [comment]
@ZeyuChen @QingshuChen

**Comment by wangxinxin08** [comment]
麻烦更新下代码试下，这个应该已经修复了

**Comment by fantasysee** [comment]
> 麻烦更新下代码试下，这个应该已经修复了

更新了确实有效。已经不会报 Segmentation Fault 了。感谢！！！

**Comment by Dtt-Lunatic** [comment]
怎么更新代码啊
