### ISSUE TITLE
post_process 中的 decode 代码在哪里？

### ISSUE THREAD

**Issue by EdwardVincentMa** [PaddlePaddle/PaddleDetection#3485]
您好，我正在看 ppyolo_tiny 后处理代码，现在不知道 decode 函数在哪里。麻烦指点一下，感谢～

**Comment by wangxinxin08** [comment]
ppdet/modeling/post_process.py这个文件中，可以根据decode的name来找相应的类

**Comment by EdwardVincentMa** [comment]
> ppdet/modeling/post_process.py这个文件中，可以根据decode的name来找相应的类

![Screenshot from 2021-06-24 11-42-41](https://user-images.githubusercontent.com/39480728/123199365-5133a000-d4e1-11eb-8a8d-cf3105880d7a.png)

您好，谢谢您的回答，我指的是第70行的self.decode函数的代码。

**Comment by wangxinxin08** [comment]
上面已经说了看ppyolo_tiny的配置文件，找到decode的name对应的类对应的代码就能找到了，比如ppyolo_tiny: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/_base_/ppyolo_tiny.yml#L45 对应的decode的name是YOLOBox，你去找YOLOBox这个类: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/modeling/layers.py#L465
就找到对应的代码了

**Comment by EdwardVincentMa** [comment]
> 上面已经说了看ppyolo_tiny的配置文件，找到decode的name对应的类对应的代码就能找到了，比如ppyolo_tiny: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/_base_/ppyolo_tiny.yml#L45 对应的decode的name是YOLOBox，你去找YOLOBox这个类: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/modeling/layers.py#L465
> 就找到对应的代码了

感谢您的耐心解答，我看了您说的位置，最后转到了 ops.py 下的 yolo_box()函数。但是还是看不到具体代码～
![Screenshot from 2021-06-24 16-48-05](https://user-images.githubusercontent.com/39480728/123233061-53f7ba80-d50c-11eb-91e6-3c1d809c5de4.png)

**Comment by wangxinxin08** [comment]
这个对应fluid.layers.yolo_box这个op，再往里面看就是Paddle的OP的代码，包含CPU和GPU的实现

**Comment by EdwardVincentMa** [comment]
> yolo_box

您好，还是没找到 yolo_box 函数的源代码。

**Comment by wangxinxin08** [comment]
在PaddlePaddle的源码里面：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/yolo_box_op.h

**Comment by EdwardVincentMa** [comment]
> yolo_box

您好，还是没找到 yolo_box 函数的源代码。

> yolo_box_op.h

我当时打印了一下，in_dygraph_mode()是False， 所以，实际上是 ops.py  的 yolo_box 调用了 LayerHelper.py，然后怎么调用的这个yolo_box_op.h我就不知道了

**Comment by EdwardVincentMa** [comment]
> 在PaddlePaddle的源码里面：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/yolo_box_op.h
谢谢您的解答，我当时打印了一下，in_dygraph_mode() 是 False， 所以，实际上是 ops.py 的 yolo_box 调用了 LayerHelper.py，然后通过 append_op。 然后怎么通过 append_op 调用的这个 yolo_box_op.h 我就不知道了。谢谢您的耐心解答，我直接看到了源码。
