### ISSUE TITLE
deepsort训练问题

### ISSUE THREAD

**Issue by GexLoong** [PaddlePaddle/PaddleDetection#3486]
请问为什么deepsort不提供训练功能

**Comment by nemonameless** [comment]
> 请问为什么deepsort不提供训练功能

DeepSORT相比SORT的一个改进是加入了一个深度特征提取网络也就是reid模块做跟踪，但本质上还是和检测器完全分离的，它所需要的reid模型，是用大规模行人reid数据集训好得到的，做跟踪只有在前向时提取特征用，只做测试用，它需要的只是检测框的结果。文档中说不用训练，是指不用像jde fairmot那样训练MOT跟踪数据集。要重训或换新的reid模型，是需要训reid数据集的。
