### ISSUE TITLE
tools/eval.py报错

### ISSUE THREAD

**Issue by COST-97** [PaddlePaddle/PaddleDetection#349]
环境配置
Python版本 python3.7
框架版本 PaddlePaddle 1.7.0

运行代码：
`%cd ~
%cd PaddleDetection/
!export CUDA_VISIBLE_DEVICES=0
!python -u tools/eval.py -c configs/yolov3_darknet_voc.yml \
                    -o weights=output/yolov3_darknet_voc/model_final/model_final \`
报错：
`/home/aistudio
/home/aistudio/PaddleDetection
2020-03-18 14:40:35,944-INFO: 555 samples in file dataset/underwater_data/val.txt
2020-03-18 14:40:35,945-INFO: places would be ommited when DataLoader is not iterable
W0318 14:40:36.816187    92 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0318 14:40:36.819629    92 device_context.cc:245] device: 0, cuDNN Version: 7.3.
2020-03-18 14:40:38,289-INFO: Loading parameters from output/yolov3_darknet_voc/model_final/model_final...
I0318 14:40:45.824139    92 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I0318 14:40:45.835911    92 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0318 14:40:45.844874    92 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0318 14:40:45.851544    92 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
2020-03-18 14:40:46,435-INFO: Test iter 0
2020-03-18 14:40:53,315-INFO: Test finish iter 69
2020-03-18 14:40:53,316-INFO: Total number of images: 546, inference time: 72.78175902722134 fps.
2020-03-18 14:40:53,316-INFO: Start evaluate...
2020-03-18 14:40:54,039-INFO: Accumulating evaluatation results...
2020-03-18 14:40:54,092-INFO: mAP(0.50, 11point) = 24.81
terminate called without an active exception
W0318 14:40:54.233896   161 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0318 14:40:54.233942   161 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0318 14:40:54.233947   161 init.cc:214] The detail failure signal is:

W0318 14:40:54.233958   161 init.cc:217] *** Aborted at 1584513654 (unix time) try "date -d @1584513654" if you are using GNU date ***
W0318 14:40:54.236248   161 init.cc:217] PC: @                0x0 (unknown)
W0318 14:40:54.236397   161 init.cc:217] *** SIGABRT (@0x3e80000005c) received by PID 92 (TID 0x7f627d408700) from PID 92; stack trace: ***
W0318 14:40:54.238324   161 init.cc:217]     @     0x7f633f430390 (unknown)
W0318 14:40:54.240118   161 init.cc:217]     @     0x7f633f08a428 gsignal
W0318 14:40:54.241885   161 init.cc:217]     @     0x7f633f08c02a abort
W0318 14:40:54.243038   161 init.cc:217]     @     0x7f62ffff784a __gnu_cxx::__verbose_terminate_handler()
W0318 14:40:54.243932   161 init.cc:217]     @     0x7f62ffff5f47 __cxxabiv1::__terminate()
W0318 14:40:54.245133   161 init.cc:217]     @     0x7f62ffff5f7d std::terminate()
W0318 14:40:54.246130   161 init.cc:217]     @     0x7f62ffff5c5a __gxx_personality_v0
W0318 14:40:54.246970   161 init.cc:217]     @     0x7f63002e8b97 _Unwind_ForcedUnwind_Phase2
W0318 14:40:54.247804   161 init.cc:217]     @     0x7f63002e8e7d _Unwind_ForcedUnwind
W0318 14:40:54.249603   161 init.cc:217]     @     0x7f633f42f070 __GI___pthread_unwind
W0318 14:40:54.251329   161 init.cc:217]     @     0x7f633f427845 __pthread_exit
W0318 14:40:54.251813   161 init.cc:217]     @     0x5587877e4e59 PyThread_exit_thread
W0318 14:40:54.251967   161 init.cc:217]     @     0x55878766ac17 PyEval_RestoreThread.cold.798
W0318 14:40:54.252374   161 init.cc:217]     @     0x7f62f4d3458d (unknown)
W0318 14:40:54.252758   161 init.cc:217]     @     0x7f62f4eab2a4 (unknown)
W0318 14:40:54.253254   161 init.cc:217]     @     0x558787766744 _PyMethodDef_RawFastCallKeywords
W0318 14:40:54.253748   161 init.cc:217]     @     0x558787766861 _PyCFunction_FastCallKeywords
W0318 14:40:54.254218   161 init.cc:217]     @     0x5587877d22bd _PyEval_EvalFrameDefault
W0318 14:40:54.254654   161 init.cc:217]     @     0x558787716539 _PyEval_EvalCodeWithName
W0318 14:40:54.255089   161 init.cc:217]     @     0x558787717635 _PyFunction_FastCallDict
W0318 14:40:54.255519   161 init.cc:217]     @     0x558787735e53 _PyObject_Call_Prepend
W0318 14:40:54.255748   161 init.cc:217]     @     0x55878776da3a slot_tp_call
W0318 14:40:54.256179   161 init.cc:217]     @     0x55878776e8fb _PyObject_FastCallKeywords
W0318 14:40:54.256647   161 init.cc:217]     @     0x5587877d1e86 _PyEval_EvalFrameDefault
W0318 14:40:54.257081   161 init.cc:217]     @     0x55878771756b _PyFunction_FastCallDict
W0318 14:40:54.257534   161 init.cc:217]     @     0x558787735e53 _PyObject_Call_Prepend
W0318 14:40:54.257763   161 init.cc:217]     @     0x55878776da3a slot_tp_call
W0318 14:40:54.258198   161 init.cc:217]     @     0x55878776e8fb _PyObject_FastCallKeywords
W0318 14:40:54.258669   161 init.cc:217]     @     0x5587877d26e8 _PyEval_EvalFrameDefault
W0318 14:40:54.259097   161 init.cc:217]     @     0x558787716539 _PyEval_EvalCodeWithName
W0318 14:40:54.259537   161 init.cc:217]     @     0x558787717635 _PyFunction_FastCallDict
W0318 14:40:54.259961   161 init.cc:217]     @     0x558787735e53 _PyObject_Call_Prepend
Aborted (core dumped)`

**Comment by willthefrog** [comment]
看上去是程序退出时报错，使用原始的voc时是否也会报错？ 如果batch size设为1是否也会报错？

**Comment by willthefrog** [comment]
@heavengate  能否看下这个问题？
