### ISSUE TITLE
yolov3使用的损失函数公式

### ISSUE THREAD

**Issue by zsbjmy** [PaddlePaddle/PaddleDetection#3490]
请问，能把yolov3使用的损失函数公式具体写出来吗？求具体公式

**Comment by lyuwenyu** [comment]
- 建议查看论文 https://arxiv.org/pdf/1804.02767.pdf
- 或者查看paddle文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/ops/yolo_loss_cn.html#yolo-loss
- 或者查看代码 https://github.com/PaddlePaddle/PaddleDetection/blob/e1e02efe93246c3f681c4e9605e44134a0aae72a/ppdet/modeling/losses/yolo_loss.py#L36
