### ISSUE TITLE
为什么训练后不生成output文件

### ISSUE THREAD

**Issue by zhangzhipan** [PaddlePaddle/PaddleDetection#3493]
根据3[0分钟快速上手PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/GETTING_STARTED_cn.md#30%E5%88%86%E9%92%9F%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8Bpaddledetection)做训练，最后一步不生成output文件夹，没有任何训练结果保存。

**Comment by nemonameless** [comment]
训练log可以发下看看吗？设置的多少epoch保存一次？
