### ISSUE TITLE
参照git说明执行keypoint_det_unite_infer.py报错“IndexError: tuple index out of range”

### ISSUE THREAD

**Issue by caterwang13K73** [PaddlePaddle/PaddleDetection#3494]
参考：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/configs/keypoint 部署预测部分

运行环境：
win10,cuda10.1,python3.8,opencv3.4.8(pip安装),1050TI(4G)显卡

参考以下代码：
#keypoint top-down模型 + detector 检测联合部署推理（联合推理只支持top-down方式）
python deploy/python/keypoint_det_unite_infer.py --det_model_dir=output_inference/ppyolo_r50vd_dcn_2x_coco/ --keypoint_model_dir=output_inference/hrnet_w32_384x288/ --video_file=../video/xxx.mp4  --use_gpu=True

实际执行代码：
python deploy/python/keypoint_det_unite_infer.py --det_model_dir=./model/ppyolo_r50vd_dcn_2x_coco/ --keypoint_model_dir=./model\hrnet_w32_384x288/ --video_file=./video_file/1.mp4  --use_gpu=True

报错信息：
IndexError: tuple index out of range

完整输出信息：
-----------  Running Arguments -----------
camera_id: -1
cpu_threads: 1
det_model_dir: ./model/ppyolo_r50vd_dcn_2x_coco/
det_threshold: 0.5
enable_mkldnn: False
image_dir: None
image_file: None
keypoint_model_dir: ./model\hrnet_w32_384x288/
keypoint_threshold: 0.5
output_dir: output
run_benchmark: False
run_mode: fluid
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dynamic_shape: False
use_gpu: True
video_file: ./video_file/3.mp4
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
I0624 22:00:19.930990 24720 analysis_config.cc:424] use_dlnne_:0
I0624 22:00:19.930990 24720 analysis_config.cc:424] use_dlnne_:0
I0624 22:00:19.931986 24720 analysis_config.cc:424] use_dlnne_:0
I0624 22:00:19.931986 24720 analysis_config.cc:424] use_dlnne_:0
-----------  Model Configuration -----------
Model Arch: HRNet
Transform Order:
--transform op: TopDownEvalAffine
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
detect frame:1
Traceback (most recent call last):
  File "deploy/python/keypoint_det_unite_infer.py", line 199, in <module>
    main()
  File "deploy/python/keypoint_det_unite_infer.py", line 185, in main
    topdown_unite_predict_video(detector, topdown_keypoint_detector,
  File "deploy/python/keypoint_det_unite_infer.py", line 124, in topdown_unite_predict_video
    results = detector.predict(frame2, FLAGS.det_threshold)
  File "E:\PaddlePaddle_Study\PaddleDetection\deploy\python\infer.py", line 135, in predict
    inputs = self.preprocess(image_list)
  File "E:\PaddlePaddle_Study\PaddleDetection\deploy\python\infer.py", line 103, in preprocess
    im, im_info = preprocess(im_path, preprocess_ops)
  File "E:\PaddlePaddle_Study\PaddleDetection\deploy\python\preprocess.py", line 205, in preprocess
    im, im_info = operator(im, im_info)
  File "E:\PaddlePaddle_Study\PaddleDetection\deploy\python\preprocess.py", line 68, in __call__
    im_channel = im.shape[2]
IndexError: tuple index out of range

**Comment by zhiboniu** [comment]
你好，keypoint_det_unite_infer.py中的下面这行frame2转成list：
results = detector.predict(frame2, FLAGS.det_threshold)
修改为
results = detector.predict([frame2], FLAGS.det_threshold)
，或者可以使用develop分支下的代码。

**Comment by caterwang13K73** [comment]
谢谢，问题解决了。
