### ISSUE TITLE
ppyolov2推理时间

### ISSUE THREAD

**Issue by shishifang** [PaddlePaddle/PaddleDetection#3497]
我的显卡是1080ti，ubuntu16.04，cuda10.2，cudnn7.6，测试自己训练的ppyolov2_r101vd_dcn_365e_coco.yml模型，显示推理时间60ms~65ms一张图片，直接用time.time()测试，代码如图：
![1111111111111](https://user-images.githubusercontent.com/50400151/123364421-f2d0f500-d5a6-11eb-8046-a769b9b9a6dc.jpg)
感觉这个时间和论文给出的时间有很大差距，想问这个时间正常吗？或者应该怎么测试？

**Comment by wangxinxin08** [comment]
请参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/python使用deploy/python/infer.py进行测试，我们是在16G V100上bs=1进行测试的

**Comment by xinsuinizhuan** [comment]
> 链接失效
> 
> 请参考[https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/python使用deploy/python/infer.py进行测试，我们是在16G](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/python%E4%BD%BF%E7%94%A8deploy/python/infer.py%E8%BF%9B%E8%A1%8C%E6%B5%8B%E8%AF%95%EF%BC%8C%E6%88%91%E4%BB%AC%E6%98%AF%E5%9C%A816G) V100上bs=1进行测试的

**Comment by nemonameless** [comment]
> > 链接失效
> > 请参考[https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/python使用deploy/python/infer.py进行测试，我们是在16G](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/python%E4%BD%BF%E7%94%A8deploy/python/infer.py%E8%BF%9B%E8%A1%8C%E6%B5%8B%E8%AF%95%EF%BC%8C%E6%88%91%E4%BB%AC%E6%98%AF%E5%9C%A816G) V100上bs=1进行测试的

https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/python
