### ISSUE TITLE
fairmot读取视频帧数

### ISSUE THREAD

**Issue by Dejavusd** [PaddlePaddle/PaddleDetection#3505]
想知道` release-2.1版本 的fairmot怎么设置每次读取视频的帧数
![QQ图片20210626114017](https://user-images.githubusercontent.com/80375767/123500816-4c9ef100-d673-11eb-8eca-4c4c68f422db.png)

**Comment by Dejavusd** [comment]
> 想知道` release-2.1版本 的fairmot怎么设置每次读取视频的帧数
> ![QQ图片20210626114017](https://user-images.githubusercontent.com/80375767/123500816-4c9ef100-d673-11eb-8eca-4c4c68f422db.png)

如果不是内存问题的话，请解答

**Comment by nemonameless** [comment]
请使用develop分支也试试? aistudio机器配置不高

**Comment by Dejavusd** [comment]
> 请使用develop分支也试试? aistudio机器配置不高

这个是我在自己本地pycharm上面跑的报的错，先前在aistudio上面跑一样的代码并无问题，所以应该是我自己电脑的原因。
因此我想通过调小fairmot预测时每次读取的视频帧数来解决内存问题（不知道我的思路对不对）

**Comment by nemonameless** [comment]
现在develop分支已支持设置帧数。
CUDA_VISIBLE_DEVICES=0 python3.7 tools/infer_mot.py -c ${config} -o weights=model_final.pdparams --video_file=test_demo.mp4 --frame_rate=20 --save_videos
