### ISSUE TITLE
在训练pedestrain时，保存权重失败，

### ISSUE THREAD

**Issue by Mr-ind1fferent** [PaddlePaddle/PaddleDetection#3506]
如题

**Comment by qingqing01** [comment]
有具体的错误信息嘛？

**Comment by Mr-ind1fferent** [comment]
> 有具体的错误信息嘛？

无，我设置了每一个epoch保存一次，但是没有

**Comment by qingqing01** [comment]
是动态图训练嘛？什么模型？log中是否有保存模型的日志? 正常都是没问题的。您有改动什么的？ 

具体的代码流程:

callbacks调用`on_epoch_end`:

https://github.com/PaddlePaddle/PaddleDetection/blob/e1e02efe93246c3f681c4e9605e44134a0aae72a/ppdet/engine/trainer.py#L334

-> 

Checkpointer :

https://github.com/PaddlePaddle/PaddleDetection/blob/e1e02efe93246c3f681c4e9605e44134a0aae72a/ppdet/engine/callbacks.py#L152

**Comment by Mr-ind1fferent** [comment]
> 是动态图训练嘛？什么模型？log中是否有保存模型的日志? 正常都是没问题的。您有改动什么的？
> 
> 具体的代码流程:
> 
> callbacks调用`on_epoch_end`:
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/e1e02efe93246c3f681c4e9605e44134a0aae72a/ppdet/engine/trainer.py#L334
> 
> ->
> 
> Checkpointer :
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/e1e02efe93246c3f681c4e9605e44134a0aae72a/ppdet/engine/callbacks.py#L152

完全没有修改
![image](https://user-images.githubusercontent.com/74087260/123584932-d508c780-d814-11eb-97b4-8fe66a7517a7.png)

**Comment by wangxinxin08** [comment]
你在哪里修改的snapshot_epoch?
