### ISSUE TITLE
PaddlePaddle 1.7.0 裁剪问题

### ISSUE THREAD

**Issue by pele228** [PaddlePaddle/PaddleDetection#351]
在PaddleDetection根目录下已经运行过 export PYTHONPATH=`pwd`:$PYTHONPATH

然后在PaddleDetection/slim/sensitive/路径下执行 
python sensitive.py \ 
-c ../../configs/yolov3_mobilenet_v1_voc.yml \ 
--print_params

报错
aistudio@jupyter-135123-311635:~/work/PaddleDetection/slim/sensitive$ python sensitive.py -c ../../configs/yolov3_mobilenet_v1_voc.yml --print_params
Traceback (most recent call last):
  File "sensitive.py", line 39, in <module>
    from ppdet.experimental import mixed_precision_context
ModuleNotFoundError: No module named 'ppdet'

**Comment by TianyouChen** [comment]
把PaddleDetection/tools/ppdet 文件夹 拷贝到PaddleDetection/slim/sensitive/目录下

**Comment by pele228** [comment]
拷贝过去之后，报错如下：

aistudio@jupyter-135123-311635:~/work/PaddleDetection/slim/sensitive$ python sensitive.py -c ../../configs/yolov3_mobilenet_v1_voc.yml --print_params
Traceback (most recent call last):
  File "sensitive.py", line 52, in <module>
    from ppdet.modeling.model_input import create_feed
ModuleNotFoundError: No module named 'ppdet.modeling.model_input'

**Comment by TianyouChen** [comment]
> 拷贝过去之后，报错如下：
> 
> aistudio@jupyter-135123-311635:~/work/PaddleDetection/slim/sensitive$ python sensitive.py -c ../../configs/yolov3_mobilenet_v1_voc.yml --print_params
> Traceback (most recent call last):
> File "sensitive.py", line 52, in 
> from ppdet.modeling.model_input import create_feed
> ModuleNotFoundError: No module named 'ppdet.modeling.model_input'

我是把sensitive.py里from ppdet.modeling.model_input import create_feed 注释里，因为里面有from ppdet.data.reader import 
create_reader，我认为应该一样的，然后跑会出现我提的#350错误在等百度回复

**Comment by TianyouChen** [comment]
> 拷贝过去之后，报错如下：
> 
> aistudio@jupyter-135123-311635:~/work/PaddleDetection/slim/sensitive$ python sensitive.py -c ../../configs/yolov3_mobilenet_v1_voc.yml --print_params
> Traceback (most recent call last):
> File "sensitive.py", line 52, in 
> from ppdet.modeling.model_input import create_feed
> ModuleNotFoundError: No module named 'ppdet.modeling.model_input'

我直接注释掉from ppdet.modeling.model_input import create_feed
看后文没用到 然后会出现#350的问题

**Comment by TianyouChen** [comment]
#350

**Comment by heavengate** [comment]
> 在PaddleDetection根目录下已经运行过 export PYTHONPATH=`pwd`:$PYTHONPATH
> 
> 然后在PaddleDetection/slim/sensitive/路径下执行
> python sensitive.py \
> -c ../../configs/yolov3_mobilenet_v1_voc.yml \
> --print_params
> 
> 报错
> aistudio@jupyter-135123-311635:~/work/PaddleDetection/slim/sensitive$ python sensitive.py -c ../../configs/yolov3_mobilenet_v1_voc.yml --print_params
> Traceback (most recent call last):
> File "sensitive.py", line 39, in 
> from ppdet.experimental import mixed_precision_context
> ModuleNotFoundError: No module named 'ppdet'

看报错是找不到ppdet包，请确认下PaddleDetection根目录下` export PYTHONPATH=pwd:$PYTHONPATH`是否正确执行，或者`echo $PYTHONPATH`确认下路径是否正确

**Comment by pele228** [comment]
还是找不到ppdet
aistudio@jupyter-135123-311635:~$ cd work/PaddleDetection/
aistudio@jupyter-135123-311635:~/work/PaddleDetection$ export PYTHONPATH=pwd:$PYTHONPATH
aistudio@jupyter-135123-311635:~/work/PaddleDetection$ echo $PYTHONPATH
pwd:
aistudio@jupyter-135123-311635:~/work/PaddleDetection$ cd slim/sensitive/
aistudio@jupyter-135123-311635:~/work/PaddleDetection/slim/sensitive$ python sensitive.py -c ../../configs/yolov3_mobilenet_v1_voc.yml --print_params
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "sensitive.py", line 39, in <module>
    from ppdet.experimental import mixed_precision_context
ModuleNotFoundError: No module named 'ppdet'

**Comment by heavengate** [comment]
> 还是找不到ppdet
> aistudio@jupyter-135123-311635:~$ cd work/PaddleDetection/ aistudio@jupyter-135123-311635:~/work/PaddleDetection$ export PYTHONPATH=pwd:$PYTHONPATH
> aistudio@jupyter-135123-311635:~/work/PaddleDetection$ echo $PYTHONPATH pwd: aistudio@jupyter-135123-311635:~/work/PaddleDetection$ cd slim/sensitive/
> aistudio@jupyter-135123-311635:~/work/PaddleDetection/slim/sensitive$ python sensitive.py -c ../../configs/yolov3_mobilenet_v1_voc.yml --print_params
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
> import imp
> Traceback (most recent call last):
> File "sensitive.py", line 39, in 
> from ppdet.experimental import mixed_precision_context
> ModuleNotFoundError: No module named 'ppdet'

"""
export PYTHONPATH=`pwd`:$PYTHONPATH
"""

pwd需要用`括起来

**Comment by pele228** [comment]
@slf12  你好，按照说明修改之后
aistudio@jupyter-135123-311635:~/work/PaddleDetection$ export PYTHONPATH=`pwd`:$PYTHONPATH
aistudio@jupyter-135123-311635:~/work/PaddleDetection$ echo $PYTHONPATH
/home/aistudio/work/PaddleDetection:
aistudio@jupyter-135123-311635:~/work/PaddleDetection$ cd slim/sensitive/
aistudio@jupyter-135123-311635:~/work/PaddleDetection/slim/sensitive$ python sensitive.py -c ../../configs/yolov3_mobilenet_v1_voc.yml --print_params
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "sensitive.py", line 52, in <module>
    from ppdet.modeling.model_input import create_feed
ModuleNotFoundError: No module named 'ppdet.modeling.model_input'

**Comment by pele228** [comment]
@slf12 我看了1.6.2框架有model_input.y   1.7.0没有这个文件了，需要将modeling用旧版替换吗？

**Comment by heavengate** [comment]
不需要，用最新的release/0.2就行

**Comment by TianyouChen** [comment]
问题解决了吗？ @pele228

**Comment by pele228** [comment]
@TianyouChen  我把缺失的文件用release/0.1的补上了。 现在sensitive运行正常了。不过这种方式不一定正确，后期也可能会导致其他问题

**Comment by TianyouChen** [comment]
> @TianyouChen 我把缺失的文件用release/0.1的补上了。 现在sensitive运行正常了。不过这种方式不一定正确，后期也可能会导致其他问题
@pele228 你跑sensitive不出错吗？我的报以下错误，你用的啥版本？
Traceback (most recent call last):
  File "slim/sensitive/sensitive.py", line 214, in <module>
    main()
  File "slim/sensitive/sensitive.py", line 172, in main
    pruned_ratios=pruned_ratios)
  File "/usr/local/lib/python3.5/dist-packages/paddleslim/prune/sensitive.py", line 86, in sensitivity
    baseline = eval_func(graph.program)
  File "slim/sensitive/sensitive.py", line 154, in test
    dataset=dataset)
  File "/home/chenchaocun/PaddleDetection_slim/slim/sensitive/ppdet/utils/eval_utils.py", line 222, in eval_results
    map_type=map_type)
  File "/home/chenchaocun/PaddleDetection_slim/slim/sensitive/ppdet/utils/voc_eval.py", line 72, in bbox_eval
    gt_boxes = t['gt_bbox'][0]
KeyError: 'gt_bbox'
