### ISSUE TITLE
关于reid模块

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleDetection#3510]
开发者您好，我在使用官方的reid模块时遇到了模块未注册的问题，如下图：
![Q53)G8XCSTHJ6~`AZS3A1LV](https://user-images.githubusercontent.com/71364549/123530780-d4970080-d730-11eb-9e7c-1e19d3a31cff.png)
我们的环境是window10的paddle2.1.0，paddledetection也是最新的2.1，希望能帮助我们一下。

**Comment by heavengate** [comment]
你好，你是之前安装过2.0版本的`paddledet`的whl包么，`pip uninstall paddledet`之后重新安装试下呢，或者`python setup.py install`
