### ISSUE TITLE
跑多目标跟踪 时候每次都被kill

### ISSUE THREAD

**Issue by tianrking** [PaddlePaddle/PaddleDetection#3511]
百度飞奖2.1  至尊版 aistudio环境 

[06/27 10:56:50] ppdet.utils.checkpoint INFO: Finish resuming model weights: /home/aistudio/.cache/paddle/weights/fairmot_dla34_30e_1088x608.pdparams
[06/27 10:56:51] ppdet.engine.tracker INFO: Starting tracking /home/aistudio/media/LongRoad.mp4
[06/27 10:56:51] ppdet.data.source.mot INFO: Length of the video: 7096 frames
killed

**Comment by tianrking** [comment]
提示
代码执行异常：内存溢出，执行已被中止。请检查相关代码。

**Comment by MyGitHub-G** [comment]
至尊版的也不行吗，那只能是7096frames的视频着实太大了

**Comment by heavengate** [comment]
看着是视频有7096帧太大了，内存占用过大，换个小一点的视频或者分段预测试下呢

**Comment by tianrking** [comment]
> 看着是视频有7096帧太大了，内存占用过大，换个小一点的视频或者分段预测试下呢

分割视频再合并的确是一种可行的方法 已实现  谢谢您

**Comment by nemonameless** [comment]
> 百度飞奖2.1 至尊版 aistudio环境
> 
> [06/27 10:56:50] ppdet.utils.checkpoint INFO: Finish resuming model weights: /home/aistudio/.cache/paddle/weights/fairmot_dla34_30e_1088x608.pdparams
> [06/27 10:56:51] ppdet.engine.tracker INFO: Starting tracking /home/aistudio/media/LongRoad.mp4
> [06/27 10:56:51] ppdet.data.source.mot INFO: Length of the video: 7096 frames
> killed

建议试试develop分支，是用decord来读帧的，pip 安装一下decord，release/2.1分支还是opencv

**Comment by Flyingdog-Huang** [comment]
> > 百度飞奖2.1 至尊版 aistudio环境
> > [06/27 10:56:50] ppdet.utils.checkpoint INFO: Finish resuming model weights: /home/aistudio/.cache/paddle/weights/fairmot_dla34_30e_1088x608.pdparams
> > [06/27 10:56:51] ppdet.engine.tracker INFO: Starting tracking /home/aistudio/media/LongRoad.mp4
> > [06/27 10:56:51] ppdet.data.source.mot INFO: Length of the video: 7096 frames
> > killed
> 
> 建议试试develop分支，是用decord来读帧的，pip 安装一下decord，release/2.1分支还是opencv

您好，我按照您的方法操作后，有如下报错：
git branch -vv
* develop     6eed850 [origin/develop] update (#3638)
  release/2.1 89d1478 [origin/release/2.1] Replace deprecated methods 'warn' and 'getargspec' (#3600)
(paddle_env) hlx@hlx:~/objectDetection/ht/project/PaddleDetection$ CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608.pdparams --video_file=cam0.mp4  --save_videos
/home/hlx/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0709 10:18:56.782553 17639 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 10.1
W0709 10:18:56.798476 17639 device_context.cc:422] device: 0, cuDNN Version: 8.0.
[07/09 10:18:59] ppdet.utils.checkpoint INFO: Finish resuming model weights: /home/hlx/.cache/paddle/weights/fairmot_dla34_30e_1088x608.pdparams
Traceback (most recent call last):
  File "tools/infer_mot.py", line 123, in <module>
    main()
  File "tools/infer_mot.py", line 119, in main
    run(FLAGS, cfg)
  File "tools/infer_mot.py", line 105, in run
    draw_threshold=FLAGS.draw_threshold)
TypeError: mot_predict() got an unexpected keyword argument 'draw_threshold'


我在查看infer_mot.py代码后，看到在parse_args()中没有draw_threshold，想请教一下原因

**Comment by nemonameless** [comment]
> > > 百度飞奖2.1 至尊版 aistudio环境
> > > [06/27 10:56:50] ppdet.utils.checkpoint INFO: Finish resuming model weights: /home/aistudio/.cache/paddle/weights/fairmot_dla34_30e_1088x608.pdparams
> > > [06/27 10:56:51] ppdet.engine.tracker INFO: Starting tracking /home/aistudio/media/LongRoad.mp4
> > > [06/27 10:56:51] ppdet.data.source.mot INFO: Length of the video: 7096 frames
> > > killed
> > 
> > 
> > 建议试试develop分支，是用decord来读帧的，pip 安装一下decord，release/2.1分支还是opencv
> 
> 您好，我按照您的方法操作后，有如下报错：
> git branch -vv
> 
> * develop     [6eed850](https://github.com/PaddlePaddle/PaddleDetection/commit/6eed850e4b4eee6a99bffbfd336b8e2aaf6ae30b) [origin/develop] update ([sparse import  #3638](https://github.com/PaddlePaddle/PaddleDetection/pull/3638))
>   release/2.1 [89d1478](https://github.com/PaddlePaddle/PaddleDetection/commit/89d147823b99dead0d6cc644c8aaf852be2e49c3) [origin/release/2.1] Replace deprecated methods 'warn' and 'getargspec' ([Replace deprecated methods 'warn' and 'getargspec' #3600](https://github.com/PaddlePaddle/PaddleDetection/pull/3600))
>   (paddle_env) hlx@hlx:~/objectDetection/ht/project/PaddleDetection$ CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608.pdparams --video_file=cam0.mp4  --save_videos
>   /home/hlx/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
>   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
>   if data.dtype == np.object:
>   W0709 10:18:56.782553 17639 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 10.1
>   W0709 10:18:56.798476 17639 device_context.cc:422] device: 0, cuDNN Version: 8.0.
>   [07/09 10:18:59] ppdet.utils.checkpoint INFO: Finish resuming model weights: /home/hlx/.cache/paddle/weights/fairmot_dla34_30e_1088x608.pdparams
>   Traceback (most recent call last):
>   File "tools/infer_mot.py", line 123, in 
>   main()
>   File "tools/infer_mot.py", line 119, in main
>   run(FLAGS, cfg)
>   File "tools/infer_mot.py", line 105, in run
>   draw_threshold=FLAGS.draw_threshold)
>   TypeError: mot_predict() got an unexpected keyword argument 'draw_threshold'
> 
> 我在查看infer_mot.py代码后，看到在parse_args()中没有draw_threshold，想请教一下原因

draw_threshold很早在develop分支里加了的，release/2.1分支很久未更新。切换分支后，python setup.py install 重新安装下

**Comment by Flyingdog-Huang** [comment]
> > > > 百度飞奖2.1 至尊版 aistudio环境
> > > > [06/27 10:56:50] ppdet.utils.checkpoint INFO: Finish resuming model weights: /home/aistudio/.cache/paddle/weights/fairmot_dla34_30e_1088x608.pdparams
> > > > [06/27 10:56:51] ppdet.engine.tracker INFO: Starting tracking /home/aistudio/media/LongRoad.mp4
> > > > [06/27 10:56:51] ppdet.data.source.mot INFO: Length of the video: 7096 frames
> > > > killed
> > > 
> > > 
> > > 建议试试develop分支，是用decord来读帧的，pip 安装一下decord，release/2.1分支还是opencv
> > 
> > 
> > 您好，我按照您的方法操作后，有如下报错：
> > git branch -vv
> > 
> > * develop     [6eed850](https://github.com/PaddlePaddle/PaddleDetection/commit/6eed850e4b4eee6a99bffbfd336b8e2aaf6ae30b) [origin/develop] update ([sparse import  #3638](https://github.com/PaddlePaddle/PaddleDetection/pull/3638))
> >   release/2.1 [89d1478](https://github.com/PaddlePaddle/PaddleDetection/commit/89d147823b99dead0d6cc644c8aaf852be2e49c3) [origin/release/2.1] Replace deprecated methods 'warn' and 'getargspec' ([Replace deprecated methods 'warn' and 'getargspec' #3600](https://github.com/PaddlePaddle/PaddleDetection/pull/3600))
> >   (paddle_env) hlx@hlx:~/objectDetection/ht/project/PaddleDetection$ CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608.pdparams --video_file=cam0.mp4  --save_videos
> >   /home/hlx/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
> >   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> >   if data.dtype == np.object:
> >   W0709 10:18:56.782553 17639 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 10.1
> >   W0709 10:18:56.798476 17639 device_context.cc:422] device: 0, cuDNN Version: 8.0.
> >   [07/09 10:18:59] ppdet.utils.checkpoint INFO: Finish resuming model weights: /home/hlx/.cache/paddle/weights/fairmot_dla34_30e_1088x608.pdparams
> >   Traceback (most recent call last):
> >   File "tools/infer_mot.py", line 123, in
> >   main()
> >   File "tools/infer_mot.py", line 119, in main
> >   run(FLAGS, cfg)
> >   File "tools/infer_mot.py", line 105, in run
> >   draw_threshold=FLAGS.draw_threshold)
> >   TypeError: mot_predict() got an unexpected keyword argument 'draw_threshold'
> > 
> > 我在查看infer_mot.py代码后，看到在parse_args()中没有draw_threshold，想请教一下原因
> 
> draw_threshold很早在develop分支里加了的，release/2.1分支很久未更新。切换分支后，python setup.py install 重新安装下

您好，按照您的指导操作后依旧报错，切换分支后我也重新安装了，您看是什么原因，谢谢

git checkout develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.
(paddle_env) hlx@hlx:~/objectDetection/ht/project/PaddleDetection$ python setup.py install
Using /home/hlx/anaconda3/envs/paddle_env/lib/python3.7/site-packages
Finished processing dependencies for paddledet==2.1.0
(paddle_env) hlx@hlx:~/objectDetection/ht/project/PaddleDetection$ CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608.pdparams --video_file=1.mp4  --save_videos
/home/hlx/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0713 11:23:12.135538 14652 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 10.1
W0713 11:23:12.136546 14652 device_context.cc:422] device: 0, cuDNN Version: 8.0.
[07/13 11:23:13] ppdet.utils.checkpoint INFO: Finish resuming model weights: /home/hlx/.cache/paddle/weights/fairmot_dla34_30e_1088x608.pdparams
Traceback (most recent call last):
  File "tools/infer_mot.py", line 123, in <module>
    main()
  File "tools/infer_mot.py", line 119, in main
    run(FLAGS, cfg)
  File "tools/infer_mot.py", line 105, in run
    draw_threshold=FLAGS.draw_threshold)
TypeError: mot_predict() got an unexpected keyword argument 'draw_threshold'
