### ISSUE TITLE
cpp里面的，阈值没有用，并且没有做nms过滤

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleDetection#3514]
我是了yolov2转换了模型，c++加载，cpu库正常，但是gpu库有问题：
![图片](https://user-images.githubusercontent.com/40679769/123550519-70138a00-d7a0-11eb-9cec-a2bd393f068e.png)
![图片](https://user-images.githubusercontent.com/40679769/123550526-7e61a600-d7a0-11eb-957b-f41578aa734e.png)
![图片](https://user-images.githubusercontent.com/40679769/123550530-87527780-d7a0-11eb-82d3-cb00736ecc52.png)

同时，里面的阈值没有起作用，没有做nms过滤

**Comment by heavengate** [comment]
你好，ppyolov2模型里用的是matrix nms，不是multiclass nms，不是通过阈值来过滤的，可以参考这里
https://github.com/PaddlePaddle/PaddleDetection/blob/e1e02efe93246c3f681c4e9605e44134a0aae72a/configs/ppyolo/_base_/ppyolov2_r50vd_dcn.yml#L59

**Comment by xinsuinizhuan** [comment]
那按您的意思，我外层，就不需要再做iou过滤了？ 第一个阈值我看到了，是在外层进行了阈值过滤，阈值传到了object_detector.h里面去了，但是里面没有使用。

**Comment by xinsuinizhuan** [comment]
另外，yolov2的图像输入格式是啥样的，rgb,bgr？
![图片](https://user-images.githubusercontent.com/40679769/123577430-64f34500-d806-11eb-9816-d5ec5292cb93.png)
这个狗狗识别不了，得分阈值才0.22。我看cpp里面，都没有图像格式转换的步骤，图像直接读取格式为bgr格式

**Comment by heavengate** [comment]
> 那按您的意思，我外层，就不需要再做iou过滤了？ 第一个阈值我看到了，是在外层进行了阈值过滤，阈值传到了object_detector.h里面去了，但是里面没有使用。

是的

**Comment by heavengate** [comment]
> 另外，yolov2的图像输入格式是啥样的，rgb,bgr？
> ![图片](https://user-images.githubusercontent.com/40679769/123577430-64f34500-d806-11eb-9816-d5ec5292cb93.png)
> 这个狗狗识别不了，得分阈值才0.22。我看cpp里面，都没有图像格式转换的步骤，图像直接读取格式为bgr格式

https://github.com/PaddlePaddle/PaddleDetection/blob/b97fc1d9e3fb831ad9cf2a41ca849e8d41fa1ecf/ppdet/data/transform/operators.py#L127 
读图的时候直接做了
