### ISSUE TITLE
训练时输入尺寸RandomResize应该怎么设置anchor的大小

### ISSUE THREAD

**Issue by raymondchu-z** [PaddlePaddle/PaddleDetection#3516]
PPYOLOv2里
~~~
batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}
~~~
训练输入尺寸是抽样的，那么运行`anchor_cluster.py`时的-s参数应该怎么设？

**Comment by jerrywgz** [comment]
anchor_cluster.py中设置的size是eval时输入模型的尺寸，例如608或者416

**Comment by raymondchu-z** [comment]
好的谢谢回复。

**Comment by chenxuezhao** [comment]
@jerrywgz 请问eval时输入模型的尺寸指的是这个吗？
![image](https://user-images.githubusercontent.com/42796059/124895633-4ca5d600-e00f-11eb-9b84-5f01f3e8790a.png)
这个 值可以修改吗？我训练用的图片比较大（且大小不一），感觉320有点小，怕影响模型的效果
