### ISSUE TITLE
ppyolov2，训练自己的数据集，模型输入尺寸修改为1536，怎么操作？

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleDetection#3519]
yolov2的训练文档并不多，我想训练自己的数据集，模型输入尺寸为1536*1536

**Comment by jerrywgz** [comment]
模型输入大小可以通过https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/_base_/ppyolo_reader.yml#L13 这里来调整，可以改成```BatchRandomResize: {target_size: [1536], random_size: True, random_interp: True, keep_ratio: False}```

**Comment by xinsuinizhuan** [comment]
![图片](https://user-images.githubusercontent.com/40679769/123658776-9c90da00-d864-11eb-8fee-e79ff994c323.png)
python tools/anchor_cluster.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml -n 9 -s 320 -m v2 -i 1000 这个命令是啥意思？

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/tools/anchor_cluster.py#L284 具体参数可以参考这里，目的是为了生成训练所需的anchor。
n表示聚类个数；s表示anchor size（设置为eval是输入网络的size大小）；m表示模式，目前支持YOLOv2AnchorCluster和YOLOv5AnchorCluster两种。i表示迭代轮数

**Comment by xinsuinizhuan** [comment]
我的理解是，目标检测是，n标识检测的目标类别个数，s标识魔心输入大小，如果使用paddleyolov的话，m应该是哪个，v2? 
还有就是，直接使用这个命令后，就不需要手动改输入尺寸了吧，我的模型输入是1536？

**Comment by jerrywgz** [comment]
这个命令得到的只是用于生成anchor，如果期望模型输入就是1536，那用-s设置1536尺寸后，evalreader中的size可以不需要再修改。trainreader使用了多尺度训练，可以在1536这个尺寸的基础上再增加一些尺度来提升模型效果

**Comment by xinsuinizhuan** [comment]
> 
> 
> 这个命令得到的只是用于生成anchor，如果期望模型输入就是1536，那用-s设置1536尺寸后，evalreader中的size可以不需要再修改。trainreader使用了多尺度训练，可以在1536这个尺寸的基础上再增加一些尺度来提升模型效果

那按照您的意思，BatchRandomResize: {target_size: 这个target_size就是训练时这里面的尺度都会进行训练，是吧？

**Comment by jerrywgz** [comment]
嗯嗯是的
