### ISSUE TITLE
在 pycharm 中调试崩溃的问题。

### ISSUE THREAD

**Issue by txyugood** [PaddlePaddle/PaddleDetection#352]
发现一个小问题，pycharm 的体验不太好，应该也不算是 bug。
不知道大家用不用 pycharm，在使用 pycharm 调试的时候，停止调试的时候，整个 IDE 会被 kill 掉。问题出在ppdet/data/parallel_map.py文件中，会捕获信号。
最后一行
`signal.signal(signal.SIGINT, _term_group)`会把 pycharm 杀掉。
应该不算 bug 吧，算是给用pycharm 的朋友一个提示，要不然自己解决这个问题也是很浪费时间的。

**Comment by willthefrog** [comment]
好的，谢谢反馈。

**Comment by willthefrog** [comment]
@heavengate 辛苦看下能否解决。

**Comment by heavengate** [comment]
master和release/0.2已修复，可以pull下试试
