### ISSUE TITLE
visualdl无可视化结果展示

### ISSUE THREAD

**Issue by crj0322** [PaddlePaddle/PaddleDetection#3520]
http://localhost:8040/ 可以连接，但显示“无可视化结果展示”；

log内容：
自定义数据，即在data/source中注册新的Dataset，train/eval/infer都没有问题，
log由“python tools/train.py  -c ... --use_vdl=true --vdl_log_dir=vdl_log_dir/ppyolov2_r50vd_dcn_80e_custom”产生；

可视化命令：
visualdl --logdir vdl_dir/ppyolov2_r50vd_dcn_80e_custom/

浏览器：
Microsoft Edge 91.0.864.59

log文件：
[vdlrecords.1624845161.log](https://github.com/PaddlePaddle/PaddleDetection/files/6724230/vdlrecords.1624845161.log)

**Comment by jerrywgz** [comment]
请问使用的是哪个版本的visualdl呢

**Comment by crj0322** [comment]
> 请问使用的是哪个版本的visualdl呢

python: 3.7.10
paddlepaddle-gpu 2.1.0
paddledet 2.1.0
visualdl 2.2.0

**Comment by ShenYuhan** [comment]
![image](https://user-images.githubusercontent.com/28444161/123750834-9ee94780-d8e9-11eb-97b7-36bb45bac47f.png)

您好，日志文件没有问题，可以尝试使用更高版本的chrome浏览器，看是否可以看到数据。

**Comment by crj0322** [comment]
> ![image](https://user-images.githubusercontent.com/28444161/123750834-9ee94780-d8e9-11eb-97b7-36bb45bac47f.png)
> 
> 您好，日志文件没有问题，可以尝试使用更高版本的chrome浏览器，看是否可以看到数据。

您好，改用chrome，
打开一直显示“数据载入中，请稍后”，点击“标量数据”后显示“无可视化结果展示”，
控制台有时会出现“[ERROR 2021-06-29 16:42:00,303 api.py:59] Internal server error. Retry later.”

![image](https://user-images.githubusercontent.com/17036914/123766989-b9c3b800-d8f9-11eb-9a27-63ca187cff61.png)

![image](https://user-images.githubusercontent.com/17036914/123767180-deb82b00-d8f9-11eb-8743-1ec44e27cba7.png)

**Comment by RaidenCJ** [comment]
遇到同样问题，有人能解答下吗？

**Comment by wddwzwhhxx** [comment]
> > ![image](https://user-images.githubusercontent.com/28444161/123750834-9ee94780-d8e9-11eb-97b7-36bb45bac47f.png)
> > 您好，日志文件没有问题，可以尝试使用更高版本的chrome浏览器，看是否可以看到数据。
> 
> 您好，改用chrome，
> 打开一直显示“数据载入中，请稍后”，点击“标量数据”后显示“无可视化结果展示”，
> 控制台有时会出现“[ERROR 2021-06-29 16:42:00,303 api.py:59] Internal server error. Retry later.”
> 
> ![image](https://user-images.githubusercontent.com/17036914/123766989-b9c3b800-d8f9-11eb-9a27-63ca187cff61.png)
> 
> ![image](https://user-images.githubusercontent.com/17036914/123767180-deb82b00-d8f9-11eb-8743-1ec44e27cba7.png)
这个问题后面解决了吗
