### ISSUE TITLE
'Momentum' object has no attribute 'user_defined_optimizer'

### ISSUE THREAD

**Issue by cslixin1997** [PaddlePaddle/PaddleDetection#3521]
![image](https://user-images.githubusercontent.com/50700993/123599357-18b8fc80-d828-11eb-9b32-836bbc5aa596.png)

paddle2.1-gpu10.2的版本    python3.6   cuda11.2  gpu：Tesla v100       

使用飞浆加速时报错：
![image](https://user-images.githubusercontent.com/50700993/123599633-67ff2d00-d828-11eb-8e68-7d1efcc901c5.png)

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/3527 问题已经提pr修复了，感谢反馈
