### ISSUE TITLE
Evaluating PP-YOLOv2 with COCO val2017 results in lower mAP than in published article

### ISSUE THREAD

**Issue by huyhung411991** [PaddlePaddle/PaddleDetection#3523]
I installed PaddlePaddle v2.1.1 and PaddleDetection v2.1 with:
`pip install paddlepaddle-gpu -f https://paddlepaddle.org.cn/whl/stable/tensorrt.html`
`pip install paddledet -i https://mirror.baidu.com/pypi/simple`

Then try to evaluate PP-YOLOv2 on COCO val2017 with provided pretrained weights and default configs with
`python tools/eval.py -c configs/ppyolo/ppyolov2_r101vd_dcn_365e_coco.yml -o weights=models/ppyolov2_r101vd_dcn_365e_coco.pdparams`
`python tools/eval.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml -o weights=models/ppyolov2_r50vd_dcn_365e_coco.pdparams`

However the results are lower than expected with **48.1%** (instead of **49.7%**) for model with **ResNet101vd** backbone and input size **640**, and **47.5%** (instead of **49.1%**) for model with **ResNet50vd** backbone and input size **640**.

Result with ResNet101vd@640:
` Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.481
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.679
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.525
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.303
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.531
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.633
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.357
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.598
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.648
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.457
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.701
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.810
[06/28 14:08:52] ppdet.engine INFO: Total sample number: 4952, averge FPS: 19.207783687191142`

Result with ResNet50vd@640:
` Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.475
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.672
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.519
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.285
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.523
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.621
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.355
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.594
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.645
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.430
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.698
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.799
[06/28 16:34:52] ppdet.engine INFO: Total sample number: 4952, averge FPS: 26.49940884796535`

Can you help me explain it?
I ran the code on Titan X with CUDA 10.2.

**Comment by xinsuinizhuan** [comment]
how to train with ppyolov2?

**Comment by jerrywgz** [comment]
you need to set --bias at the stage of evaluation. Please refer to https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/README.md#2-evaluation

**Comment by huyhung411991** [comment]
> you need to set --bias at the stage of evaluation. Please refer to https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/README.md#2-evaluation

Just read again and recognized the note that I missed. Thank you for your help.
