### ISSUE TITLE
数据处理流程问题：

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#3525]
请教：在YAML文件TrainReader下sample_transforms:中，增加了一些数据增强的配置，训练时数据处理的流程怎样？是直接对每张图像做对应增强后和原来数据一起train？还是保留数据重量不变，仅仅随机选择部分图像增强，然后与未增强数据一起train？请指教！！

**Comment by jerrywgz** [comment]
sample_transform表示的将一张图进行数据增强，最终进入网络训练的都是经过数据增强后的图像，原始图像不会参与训练

**Comment by jackie8310** [comment]
@jerrywgz ，如果是将每一张图进行数据增强喂入训练，那增强的方法有几种，是对每张图随机选择一种增强方法，还是依次按照增强方法（一张图片变成多张图片）喂入训练？

**Comment by jerrywgz** [comment]
逻辑是一张图依次按照多种数据增强方法，得到最终的一张输入图训练
