### ISSUE TITLE
fairmot预测视频

### ISSUE THREAD

**Issue by Dejavusd** [PaddlePaddle/PaddleDetection#3526]
![QQ图片20210626114017](https://user-images.githubusercontent.com/80375767/123631786-b83ab700-d849-11eb-81b8-61c4a654d4e2.png)
在本地pycharm跑fairmot预测报了这个错，但是在aistudio上跑一样的代码可以正常运行
想知道在release-2.1版本中，怎么修改fairmot预测时每次读取视频的帧数（代码中在aistudio里面跑过好像是40帧每次），我想调小些。如果有更好解决这个报错的方法求告知

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/engine/tracker.py#L127 目前fairmot预测的帧数是固定的40，这里的代码可以进行修改，我们后面优化下。另外本地预测出错可能是图像过大，解码时间过长导致的。可以尝试减小视频大小，或者使用decord进行视频解码

**Comment by Dejavusd** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/engine/tracker.py#L127 目前fairmot预测的帧数是固定的40，这里的代码可以进行修改，我们后面优化下。另外本地预测出错可能是图像过大，解码时间过长导致的。可以尝试减小视频大小，或者使用decord进行视频解码

关于这个decord？在哪里加找到paddle的和在哪加上

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/source/mot.py#L327 可以参考这里的使用方法

**Comment by Dejavusd** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/engine/tracker.py#L127 目前fairmot预测的帧数是固定的40，这里的代码可以进行修改，我们后面优化下。另外本地预测出错可能是图像过大，解码时间过长导致的。可以尝试减小视频大小，或者使用decord进行视频解码

![微信图片_20210628203355](https://user-images.githubusercontent.com/80375767/123637097-326e

**Comment by Dejavusd** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/source/mot.py#L327 可以参考这里的使用方法

按 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/source/mot.py# （L326-L349）这样处理后会报这样的错  缺少 frame_rate
![微信图片_20210628205525](https://user-images.githubusercontent.com/80375767/123640048-5d0dc200-d853-11eb-9c2c-51263e183ed8.png)

原代码中是这样
![微信截图_20210628205811](https://user-images.githubusercontent.com/80375767/123640272-93e3d800-d853-11eb-929c-68974da5a6b3.png)

**Comment by Dejavusd** [comment]
> > https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/source/mot.py#L327 可以参考这里的使用方法
> 
> 按 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/source/mot.py# （L326-L349）这样处理后会报这样的错 缺少 frame_rate
> ![微信图片_20210628205525](https://user-images.githubusercontent.com/80375767/123640048-5d0dc200-d853-11eb-9c2c-51263e183ed8.png)
> 
> 原代码中是这样
> ![微信截图_20210628205811](https://user-images.githubusercontent.com/80375767/123640272-93e3d800-d853-11eb-929c-68974da5a6b3.png)

我想保留帧速率

**Comment by jerrywgz** [comment]
可以直接试下develop分支

**Comment by Dejavusd** [comment]
> 可以直接试下develop分支

我试了一下，也会报错，会不会是PyQt的兼容的问题
参考 https://blog.csdn.net/wangguan9527/article/details/82845409

**Comment by Dejavusd** [comment]
> 可以直接试下develop分支

可以运行，但是不会完全运行完。比方说就是我用一个300frame的视频，代码会保存预测结果的每一帧图片，但只保存到299张就没了，并且也没有预测好的视频文件生成（跑到第299张的时候又自己退了）
![1](https://user-images.githubusercontent.com/80375767/123657657-91897a00-d863-11eb-9176-b755831514b4.png)

imshow也总是显示未响应
![2](https://user-images.githubusercontent.com/80375767/123658472-563b7b00-d864-11eb-83b2-c4f0f3627b26.png)

**Comment by nemonameless** [comment]
> > 可以直接试下develop分支
> 
> 可以运行，但是不会完全运行完。比方说就是我用一个300frame的视频，代码会保存预测结果的每一帧图片，但只保存到299张就没了，并且也没有预测好的视频文件生成（跑到第299张的时候又自己退了）
> ![1](https://user-images.githubusercontent.com/80375767/123657657-91897a00-d863-11eb-9176-b755831514b4.png)
> 
> imshow也总是显示未响应
> ![2](https://user-images.githubusercontent.com/80375767/123658472-563b7b00-d864-11eb-83b2-c4f0f3627b26.png)

linux平台上应该都没这个问题。可以详细说下您windows平台环境吗？cuda cudnn python paddle等

**Comment by Dejavusd** [comment]
> > > 可以直接试下develop分支
> > 
> > 
> > 可以运行，但是不会完全运行完。比方说就是我用一个300frame的视频，代码会保存预测结果的每一帧图片，但只保存到299张就没了，并且也没有预测好的视频文件生成（跑到第299张的时候又自己退了）
> > ![1](https://user-images.githubusercontent.com/80375767/123657657-91897a00-d863-11eb-9176-b755831514b4.png)
> > imshow也总是显示未响应
> > ![2](https://user-images.githubusercontent.com/80375767/123658472-563b7b00-d864-11eb-83b2-c4f0f3627b26.png)
> 
> linux平台上应该都没这个问题。可以详细说下您windows平台环境吗？cuda cudnn python paddle等

Windows10
cuda是10.1 cudnn是v7.6.5.32 python是3.8 paddle是gpu版2.1.0.post101
电脑版本的cuda是
![3](https://user-images.githubusercontent.com/80375767/123760430-6c444c80-d8f3-11eb-8638-14a9881fe047.png)

**Comment by nemonameless** [comment]
#3549

**Comment by nemonameless** [comment]
> ![QQ图片20210626114017](https://user-images.githubusercontent.com/80375767/123631786-b83ab700-d849-11eb-81b8-61c4a654d4e2.png)
> 在本地pycharm跑fairmot预测报了这个错，但是在aistudio上跑一样的代码可以正常运行
> 想知道在release-2.1版本中，怎么修改fairmot预测时每次读取视频的帧数（代码中在aistudio里面跑过好像是40帧每次），我想调小些。如果有更好解决这个报错的方法求告知

已经支持自己设置帧率infer视频，请使用develop分支或release/2.2分支，命令如下：
```
CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608.pdparams --video_file={your video name}.mp4 --frame_rate=20 --save_videos
```
