### ISSUE TITLE
把背景图片加入训练集中:

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#3529]
请教：如何将背景图像（无标注框的正常图像）加入两阶段检测模型训练以降低误检率（数据标注格式是COCO的）？

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/data/source/coco.py#L51 可以在dataset中设置allow_empty字段来加入背景图像，同时可以设置empty_ratio来设置加入背景图像的比重

**Comment by jackie8310** [comment]
@jerrywgz ，如果用静态图训练，加入接口在哪里呢？这个https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/ppdet/data/source/coco.py中没有？？

**Comment by jerrywgz** [comment]
静态图目前没有增加这个功能

**Comment by oldZhangYH** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/data/source/coco.py#L51 可以在dataset中设置allow_empty字段来加入背景图像，同时可以设置empty_ratio来设置加入背景图像的比重

当前voc格式数据支持背景图训练吗

**Comment by jerrywgz** [comment]
目前已经支持voc数据集训练
