### ISSUE TITLE
iou aware，在YOLOv3中增加一个通道预测iou 

### ISSUE THREAD

**Issue by dhao-island** [PaddlePaddle/PaddleDetection#3533]
请问这个通道加在那个位置呢，通道中是一个3*3卷积加一个sigmoid函数嘛（原文），
想画一下它的训练结构图

**Comment by wangxinxin08** [comment]
yolov3原先会预测每一个anchor的xwwh, obj, cls，这用一个输出通道为anchor_num * (classes + 1)的卷积来实现，现在iou aware就添加在这个卷积上

**Comment by seekFire** [comment]
@wangxinxin08 
您好, 添加iou aware head之后, 输出的每个分支的通道数是**anchor_num** * **(classes + 6)** 吗? 也就是 classes + (x, y, w, h, obj, iou) ?

**Comment by wangxinxin08** [comment]
@seekFire 是的

**Comment by seekFire** [comment]
@wangxinxin08  谢谢您啦!

**Comment by seekFire** [comment]
@wangxinxin08 谢谢您啦!
