### ISSUE TITLE
ppyolo_tiny 预处理除了 mean 和 std 之外还需要其他的处理吗？

### ISSUE THREAD

**Issue by EdwardVincentMa** [PaddlePaddle/PaddleDetection#3536]
ppyolo_tiny 预处理除了 mean 和 std 之外还需要其他的处理吗？

**Comment by yghstill** [comment]
@EdwardVincentMa https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/_base_/ppyolo_tiny_reader.yml#L39-L41
有 resize、归一化(除255，减mean除std)，还有hwc->chw这三种
