### ISSUE TITLE
人像圣诞特效自动生成里面这个长宽缩放因子怎么算的,比如我有一个新的帽子mask,怎么计算这些缩放因子?

### ISSUE THREAD

**Issue by intjun** [PaddlePaddle/PaddleDetection#3538]
HAT_SCALES = {
    '1.png': [3.0, 0.9, .0],
    '2.png': [3.0, 1.3, .5],
    '3.png': [2.2, 1.5, .8],
    '4.png': [2.2, 1.8, .0],
    '5.png': [1.8, 1.2, .0],
}

**Comment by yghstill** [comment]
@intjun 这些scales参数是人工调的，你可以根据帽子具体形状手动调到最优。
