### ISSUE TITLE
PaddleDetection C++预测部署，不能使用yolov3_mobilenet.yaml

### ISSUE THREAD

**Issue by nortoncpppp** [PaddlePaddle/PaddleDetection#354]
你好，我按照https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.1/inference 的教程可以成功测试detection_rcnn.yaml，但是不能使用下面的yaml
https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.1/inference/conf/yolov3_mobilenet.yaml
该yaml中我修改了USE_GPU: 0 和MODEL_PATH: "D:/Work/code/models/yolov3_mobilenet_v1"，模型我是从https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/MODEL_ZOO_cn.md
中下载的YOLOv3-MobileNet-V1-320，错误的截图如下

![image](https://user-images.githubusercontent.com/62343574/76972252-4a76be80-6969-11ea-908b-28298c8bf7f7.png)
想请问一下是什么原因？

**Comment by willthefrog** [comment]
Model zoo里的文件不是inference model，可以尝试用`tools/export_mode.py`进行转换，不过请注意目前提供支持的是fast rcnn模型，release 0.2也未提供yolo的inference conf，不确定是否会有其他问题。

**Comment by qingqing01** [comment]
@nortoncpppp `inference`目录下的C++预测引擎，需要先通过 `tools/export_mode.py` 进行模型转换，再使用。

**Comment by nortoncpppp** [comment]
使用tools/export_mode.py转换model zoo里面的yolov3_mobilenet模型，测试成功了，感谢~

**Comment by willthefrog** [comment]
好的，如果没问题了麻烦close下issue吧，谢谢。
