### ISSUE TITLE
gen_labels_MOT.py不生成txt文件

### ISSUE THREAD

**Issue by Fitz-Fitz** [PaddlePaddle/PaddleDetection#3540]
按照PrepareMOTDataSet_cn.md的用户数据准备中，构建目录结构，并按照要求有gt.txt文件，格式为：[frame_id],[identity],[bb_left],[bb_top],[width],[height],[x],[y],[z]，随后按操作切换目录，更换gen_labels_MOT.py文件中路径名称运行程序，不生产对应的labels_with_ids文件夹下的txt文件。
经验证，如使用MOT16原生数据集下的gt.txt文件，则可生成labels_with_ids文件夹下的txt文件，而原生数据集下的gt.txt文件内容如下：
1,1,912,484,97,109,0,7,1
2,1,912,484,97,109,0,7,1
3,1,912,484,97,109,0,7,1
4,1,912,484,97,109,0,7,1
5,1,912,484,97,109,0,7,1
6,1,912,484,97,109,0,7,1
7,1,912,484,97,109,0,7,1
截了一小段，好像不符合教程中[frame_id],[identity],[bb_left],[bb_top],[width],[height],[x],[y],[z]格式，请问是这种情况是怎么回事？该如何解决？

**Comment by nemonameless** [comment]
请确保您的数据集目录和格式都和MOT16保持一致。gt.txt的每一行就前6个数据是重点，[frame_id],[identity],[bb_left],[bb_top],[width],[height]

**Comment by Fitz-Fitz** [comment]
> 请确保您的数据集目录和格式都和MOT16保持一致。gt.txt的每一行就前6个数据是重点，[frame_id],[identity],[bb_left],[bb_top],[width],[height]


官方文档中说到：
gt.txt里是当前视频中所有图片的原始标注文件，每行都描述一个边界框，格式如下：[frame_id],[identity],[bb_left],[bb_top],[width],[height],[x],[y],[z]
注意:
·frame_id为当前图片帧序号
·identity是从0到num_identifies-1的整数(num_identifies是数据集中不同物体实例的总数)，如果此框没有identity标注，则为-1
·bb_left是目标框的左边界的x坐标
·bb_top是目标框的上边界的y坐标
·width，height是真实的像素宽高
·x,y,z是3D中用到的，在2D中默认为-1



自己生成的gt.txt截选如下：
1,-1,990.2231,795.45276,1050.9244,1014.5106,-1,-1,-1
1,-1,372.3353,678.3274,433.2606,884.6161,-1,-1,-1
1,-1,887.01294,249.51904,938.677,367.67108,-1,-1,-1
1,-1,198.04906,601.86664,253.61281,785.2005,-1,-1,-1
1,-1,1449.6871,507.42456,1499.7496,674.7999,-1,-1,-1
1,-1,920.0549,251.2647,970.0422,366.6456,-1,-1,-1
1,-1,52.89514,910.72754,104.512436,1054.4688,-1,-1,-1
1,-1,871.4736,818.2473,937.17255,1036.3774,-1,-1,-1

MOT16-02目录下的gt.txt截选如下：
1,1,912,484,97,109,0,7,1
2,1,912,484,97,109,0,7,1
3,1,912,484,97,109,0,7,1
4,1,912,484,97,109,0,7,1
5,1,912,484,97,109,0,7,1
6,1,912,484,97,109,0,7,1
7,1,912,484,97,109,0,7,1
8,1,912,484,97,109,0,7,1

小哥瞅瞅我这个生成的gt.txt格式对吗，然后为什么和官方MOT16-02的区别这么大呢

**Comment by Fitz-Fitz** [comment]
我自己生成的gt.txt是无法生成labels_with_ids文件夹下的txt文件，但是MOT16-02就可以，但是MOT16-02下txt格式貌似和官网讲的有一点出入，没有理解的很清楚，还请小哥指点

**Comment by nemonameless** [comment]
> 我自己生成的gt.txt是无法生成labels_with_ids文件夹下的txt文件，但是MOT16-02就可以，但是MOT16-02下txt格式貌似和官网讲的有一点出入，没有理解的很清楚，还请小哥指点

您生成的gt.txt，第2列都是-1吗，那这个数据集只能做检测没法做跟踪。MOT16-02的gt.txt同一个物体的不同帧的标注放在一起，你的是同一帧的所有物体标注放在一起了。方便的话截图看看你的数据集的目录结构和文件命名，也可以对比着MOT16打印debug gen_labels_MOT.py看哪里有差异。
gt.txt文件每行意义这里解释有误，后3个应该是 mask, label, visibility ratio，表示目标轨迹是否进入考虑范围内的标志(0 忽略，1 active)，该轨迹对应的目标种类(7是static person类，自定义数据集默认类别应该是1)，目标运动时被其他目标box包含/覆盖的可见率。自定义数据集默认后3项应该是1，1，1
