### ISSUE TITLE
Vehicle Detection c++版本使用fluid可以正常检测车辆，但是使用trt_fp16检测结果出现问题，使用trtint8无法使用，直接报错

### ISSUE THREAD

**Issue by zsffuture** [PaddlePaddle/PaddleDetection#3542]
版本使用的paddledetection2.1版本，python调用Vehicle 检测模型可以正常使用，c++使用fluid，trt_fp32也可以正常使用，但是当使用trt_fp16时就出现问题了，问题如下：
1.返回的矩形框出现负值，
2.返回矩形框出现[0,0,0,0]值
3.图片显示结果为只有远处小目标可以检测到，近处的大目标无法检测
这是怎么回事？
![image](https://user-images.githubusercontent.com/39027951/123892867-f3de9980-d98d-11eb-99d9-929ac0ab5a25.png)
![image](https://user-images.githubusercontent.com/39027951/123893050-4324ca00-d98e-11eb-94bd-344d417b4c79.png)

**Comment by liuhuiCNN** [comment]
（1）应该是数据类型溢出，应该是个bug，我们尽快修复；
（2）检测为空时会返回classid=-1，rect=[0,0,0,0]的结果，这样表示检测为空；
（3）这根模型本身，以及具体训练时间有关。

**Comment by zsffuture** [comment]
> （1）应该是数据类型溢出，应该是个bug，我们尽快修复；
> （2）检测为空时会返回classid=-1，rect=[0,0,0,0]的结果，这样表示检测为空；
> （3）这根模型本身，以及具体训练时间有关。

用的是你们训练好的车辆检测模型即vehicle_yolov3_darknet.pdparams，然后直接进行转换使用c++调用，我并没有训练，只是使用c++调用而已。
其中返回为空的置信度是有值得，不是-1，说明是有检测目标的，意味着这个是不是bug？

**Comment by liuhuiCNN** [comment]
在预测为空时，我们会构造一个classid=-1的结果，用以表示检测为空的情况。
此外，int8需要使用paddleslim量化后的模型，或者使用tensorrt_int8量化校准的方式。我们会完善检测库的文档，paddle也有提供预测文档，您可以参考： https://paddle-inference.readthedocs.io/en/latest/optimize/paddle_trt.html?highlight=int8#int8

**Comment by zsffuture** [comment]
大神，按照您给的链接，发现没有可以量化yolov3_darkNet的方法啊？你们有尝试吗

**Comment by liuhuiCNN** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/configs/slim
