### ISSUE TITLE
C++部署，GPU报错   Cuda error(700), an illegal memory access was encountered

### ISSUE THREAD

**Issue by sdnusqy-art** [PaddlePaddle/PaddleDetection#3545]
C++部署gpu检测报错，cpu正常。用yolov3_mobilenet_v1训练的roadsign数据，单线程，初始化单个predictor,遍历检测多张不同图片，出现cuda error(700)错误；遍历检测同一张图片多次无错误。
PaddlePaddle:release/2.0
PaddleDetection: release/2.0
cuda：10.2
cudnn:7.6.5
os: centos7.8

详细错误如下：
Error Message Summary:
----------------------
ExternalError:  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /home/sqy/Paddle-2.0/paddle/fluid/platform/gpu_info.cc:296)

用paddle1.8.5和paddleDetection1.8.5进行c++部署没有问题。

**Comment by liuhuiCNN** [comment]
遍历检测多张不同图时，在每次预测结束后建议增加内存回收代码：
`// 释放中间Tensor
predictor->ClearIntermediateTensor();

// 释放内存池中的所有临时 Tensor
predictor->TryShrinkMemory();`
参考文档：https://paddle-inference.readthedocs.io/en/latest/api_reference/cxx_api_doc/Predictor.html

**Comment by sdnusqy-art** [comment]
> 遍历检测多张不同图时，在每次预测结束后建议增加内存回收代码：
> `// 释放中间Tensor
> predictor->ClearIntermediateTensor();
> 
> // 释放内存池中的所有临时 Tensor
> predictor->TryShrinkMemory();`
> 参考文档：https://paddle-inference.readthedocs.io/en/latest/api_reference/cxx_api_doc/Predictor.html

释放Tensor之后同样出现cuda error（700）错误， Traceback有变化：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::memory::detail::BuddyAllocator::Release()
1   paddle::memory::detail::GPUAllocator::Free(void*, unsigned long, unsigned long)
2   paddle::platform::RecordedCudaFree(void*, unsigned long, int)
3   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
4   paddle::platform::GetCurrentTraceBackString()

----------------------


未添加释放Tensor时：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   void paddle::ZeroCopyTensor::copy_from_cpu<float>(float const*)
1   void paddle::memory::Copy<paddle::platform::CUDAPlace, paddle::platform::CPUPlace>(paddle::platform::CUDAPlace, void*, paddle::platform::CPUPlace, void const*, unsigned long, CUstream_st*)
2   paddle::platform::GpuMemcpyAsync(void*, void const*, unsigned long, cudaMemcpyKind, CUstream_st*)
3   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
4   paddle::platform::GetCurrentTraceBackString()

----------------------

**Comment by AN-ZE** [comment]
python版批量预测也是同样问题，2.0，2.1都是。2.0_rc和之前版本是没有问题的。

**Comment by liuhuiCNN** [comment]
> python版批量预测也是同样问题，2.0，2.1都是。2.0_rc和之前版本是没有问题的。

cuda版本与paddle的版本匹配吗？

**Comment by sdnusqy-art** [comment]
> python版批量预测也是同样问题，2.0，2.1都是。2.0_rc和之前版本是没有问题的。

python版我测试2.0是没问题的

**Comment by sdnusqy-art** [comment]
> > python版批量预测也是同样问题，2.0，2.1都是。2.0_rc和之前版本是没有问题的。
> 
> cuda版本与paddle的版本匹配吗？

目前C++版本的问题有人在跟踪吗？不行的话我只能用1.8版本了。 请教以下，1.8版本与2.0版本的gpu性能差别大吗？1.8版本的是不是不支持INT8量化？

**Comment by liuhuiCNN** [comment]
你好，之前有类似bug，paddle==2.1.1已经修复，请您试下。
