### ISSUE TITLE
pedstrain预测不了图片

### ISSUE THREAD

**Issue by Mr-ind1fferent** [PaddlePaddle/PaddleDetection#3546]
用了是官方给的命令，但是输出没有框，没有报错，没有修改yml

**Comment by liuhuiCNN** [comment]
请问您使用的paddle版本是2.1.0吗？我测试使用paddle==2.1.0是正常的：
![004](https://user-images.githubusercontent.com/25636152/123920303-649aab80-d9b8-11eb-8c3a-952a954df3d8.png)

**Comment by Mr-ind1fferent** [comment]
> 请问您使用的paddle版本是2.1.0吗？我测试使用paddle==2.1.0是正常的：
> ![004](https://user-images.githubusercontent.com/25636152/123920303-649aab80-d9b8-11eb-8c3a-952a954df3d8.png)

对的

**Comment by liuhuiCNN** [comment]
请检查一下paddle版本，cuda版本是否匹配。paddle按照正常的话，是没有问题的。
