### ISSUE TITLE
develop分支下fairmot预测视频问题

### ISSUE THREAD

**Issue by Dejavusd** [PaddlePaddle/PaddleDetection#3549]
预测视频时不会完全运行完。比方说就是我用一个300frame的视频，代码会保存预测结果的每一帧图片，但只保存到299张就没了，并且也没有预测好的视频文件生成（跑到第299张的时候又自己退了）
![2](https://user-images.githubusercontent.com/80375767/123924311-6d8d7c00-d9bc-11eb-852c-8750d7d862cb.png)
imshow也是一直显示未响应
![3](https://user-images.githubusercontent.com/80375767/123924352-78481100-d9bc-11eb-9b00-748437248392.png)
Windows10环境
cuda是10.1 cudnn是v7.6.5.32 python是3.8 paddle是gpu版2.1.0.post101
电脑版本的cuda是
![1](https://user-images.githubusercontent.com/80375767/123924405-84cc6980-d9bc-11eb-9737-8cbe09376d28.png)

**Comment by Dejavusd** [comment]
这个问题很着急QAQ

**Comment by liuhuiCNN** [comment]
收到，我们尽快查下问题

**Comment by nemonameless** [comment]
> 预测视频时不会完全运行完。比方说就是我用一个300frame的视频，代码会保存预测结果的每一帧图片，但只保存到299张就没了，并且也没有预测好的视频文件生成（跑到第299张的时候又自己退了）
> ![2](https://user-images.githubusercontent.com/80375767/123924311-6d8d7c00-d9bc-11eb-852c-8750d7d862cb.png)
> imshow也是一直显示未响应
> ![3](https://user-images.githubusercontent.com/80375767/123924352-78481100-d9bc-11eb-9b00-748437248392.png)
> Windows10环境
> cuda是10.1 cudnn是v7.6.5.32 python是3.8 paddle是gpu版2.1.0.post101
> 电脑版本的cuda是
> ![1](https://user-images.githubusercontent.com/80375767/123924405-84cc6980-d9bc-11eb-9737-8cbe09376d28.png)

opencv版本是？

**Comment by Dejavusd** [comment]
> > 预测视频时不会完全运行完。比方说就是我用一个300frame的视频，代码会保存预测结果的每一帧图片，但只保存到299张就没了，并且也没有预测好的视频文件生成（跑到第299张的时候又自己退了）
> > ![2](https://user-images.githubusercontent.com/80375767/123924311-6d8d7c00-d9bc-11eb-852c-8750d7d862cb.png)
> > imshow也是一直显示未响应
> > ![3](https://user-images.githubusercontent.com/80375767/123924352-78481100-d9bc-11eb-9b00-748437248392.png)
> > Windows10环境
> > cuda是10.1 cudnn是v7.6.5.32 python是3.8 paddle是gpu版2.1.0.post101
> > 电脑版本的cuda是
> > ![1](https://user-images.githubusercontent.com/80375767/123924405-84cc6980-d9bc-11eb-9737-8cbe09376d28.png)
> 
> opencv版本是？

![4](https://user-images.githubusercontent.com/80375767/123926775-ceb64f00-d9be-11eb-8643-c5fe3b961c8d.png)

**Comment by Dejavusd** [comment]
> > 预测视频时不会完全运行完。比方说就是我用一个300frame的视频，代码会保存预测结果的每一帧图片，但只保存到299张就没了，并且也没有预测好的视频文件生成（跑到第299张的时候又自己退了）
> > ![2](https://user-images.githubusercontent.com/80375767/123924311-6d8d7c00-d9bc-11eb-852c-8750d7d862cb.png)
> > imshow也是一直显示未响应
> > ![3](https://user-images.githubusercontent.com/80375767/123924352-78481100-d9bc-11eb-9b00-748437248392.png)
> > Windows10环境
> > cuda是10.1 cudnn是v7.6.5.32 python是3.8 paddle是gpu版2.1.0.post101
> > 电脑版本的cuda是
> > ![1](https://user-images.githubusercontent.com/80375767/123924405-84cc6980-d9bc-11eb-9737-8cbe09376d28.png)
> 
> opencv版本是？

我最想解决的就是它会运行到倒数第二帧然后自己断了，不会保存预测结果的视频，我需要的就是预测结果视频

**Comment by nemonameless** [comment]
> > > 预测视频时不会完全运行完。比方说就是我用一个300frame的视频，代码会保存预测结果的每一帧图片，但只保存到299张就没了，并且也没有预测好的视频文件生成（跑到第299张的时候又自己退了）
> > > ![2](https://user-images.githubusercontent.com/80375767/123924311-6d8d7c00-d9bc-11eb-852c-8750d7d862cb.png)
> > > imshow也是一直显示未响应
> > > ![3](https://user-images.githubusercontent.com/80375767/123924352-78481100-d9bc-11eb-9b00-748437248392.png)
> > > Windows10环境
> > > cuda是10.1 cudnn是v7.6.5.32 python是3.8 paddle是gpu版2.1.0.post101
> > > 电脑版本的cuda是
> > > ![1](https://user-images.githubusercontent.com/80375767/123924405-84cc6980-d9bc-11eb-9737-8cbe09376d28.png)
> > 
> > 
> > opencv版本是？
> 
> 我最想解决的就是它会运行到倒数第二帧然后自己断了，不会保存预测结果的视频，我需要的就是预测结果视频

无法复现你的问题。ffmpeg安装了吗？把视频裁小一点，100帧左右的小视频也是同样报错？

**Comment by nemonameless** [comment]
已经支持自己设置帧率infer视频，请使用develop分支或release/2.2分支，命令如下：
```
CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608.pdparams --video_file={your video name}.mp4 --frame_rate=20 --save_videos
```
