### ISSUE TITLE
C++ 部署接口的执行效率

### ISSUE THREAD

**Issue by pele228** [PaddlePaddle/PaddleDetection#355]
windows下编译的C++预测接口测试，1080卡+CUDA10，
yolov3_r34模型处理单帧平均时长为
608*608  80ms
416*416  65ms
320*320  62ms
yolov3_mobilenet_v1模型
608*608  65ms
416*416  55ms
320*320  52ms

yolov3_mobilenet_v1_voc.yaml文件如下
DEPLOY:
    USE_GPU: 1
    MODEL_PATH: "yolov3_mobilenet_v1_voc"
    MODEL_FILENAME: "__model__"
    PARAMS_FILENAME: "__params__"
    EVAL_CROP_SIZE: (320, 320)
    RESIZE_TYPE: "UNPADDING"
    MEAN:  [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    IMAGE_TYPE: "rgb"
    NUM_CLASSES: 26
    CHANNELS : 3
    PRE_PROCESSOR: "DetectionPreProcessor"
    PREDICTOR_MODE: "ANALYSIS"
    BATCH_SIZE : 1
    RESIZE_MAX_SIZE: 1333
    FEEDS_SIZE: 3

感觉执行效率很低， 还需要对参数设置做哪些调整吗？

**Comment by cvfzhong** [comment]
我也发现了，应该是预处理耗时太长

**Comment by qingqing01** [comment]
已经重构了C++预测代码，支持使用预测库的优化，以及TensorRT https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/deploy
