### ISSUE TITLE
ciou怎么用？

### ISSUE THREAD

**Issue by raymondchu-z** [PaddlePaddle/PaddleDetection#3551]
模型是PPYOLOv2，
配置如下：
> IouLoss:
  loss_weight: 2.5
  loss_square: true
  ciou_term: true

报错如下：
> __init__() got an unexpected keyword argument 'ciou_term'

**Comment by liuhuiCNN** [comment]
在动态图中，IouLoss参数名改为 ciou，请参考
https://github.com/PaddlePaddle/PaddleDetection/blob/5e19955b011d47377a3f1443a6e592ddd9e5024a/ppdet/modeling/losses/iou_loss.py#L47

**Comment by raymondchu-z** [comment]
好的谢谢。
