### ISSUE TITLE
ppyolov2部署时报错，视频读写错误

### ISSUE THREAD

**Issue by Enyu-Liu** [PaddlePaddle/PaddleDetection#3553]
Traceback (most recent call last):
  File "G:/竞赛/rc/桶/last/gpu_infence.py", line 110, in <module>
    predictor = predict_config(model_file, params_file)
  File "G:/竞赛/rc/桶/last/gpu_infence.py", line 54, in predict_config
    predictor = create_predictor(config)
ValueError: (InvalidArgument) Cannot parse tensor desc
  [Hint: Expected desc.ParseFromArray(buf.get(), size) == true, but received desc.ParseFromArray(buf.get(), size):0 != true:1.] (at C:/home/workspace/Paddle_release/paddle/fluid/framework/.tensor_util.cu:957)
  [operator < load_combine > error]

**Comment by Enyu-Liu** [comment]
您好，我是在aistudio上训练的模型，把模型文件下载后就没办法部署了，请问这是什么问题？

**Comment by liuhuiCNN** [comment]
您好，请问是用 deploy 文件夹下代码进行部署吗？
使用 deploy 文件夹下代码进行部署需要先导出模型，直接下载的模型不能直接这样部署。
模型导出可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_MODEL.md

**Comment by Enyu-Liu** [comment]
> 您好，请问是用 deploy 文件夹下代码进行部署吗？
> 使用 deploy 文件夹下代码进行部署需要先导出模型，直接下载的模型不能直接这样部署。
> 模型导出可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_MODEL.md

您好，我又重新使用deploy文件夹下的infer.py文件进行了部署，但是我发现只能预测图片，视频和打开摄像头都不可以，请问这是什么问题？

**Comment by Enyu-Liu** [comment]
> 您好，请问是用 deploy 文件夹下代码进行部署吗？
> 使用 deploy 文件夹下代码进行部署需要先导出模型，直接下载的模型不能直接这样部署。
> 模型导出可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_MODEL.md

IndexError: tuple index out of range 打开设想头时的报错，
用视频预测的时候，没有报错，但预测结果的视频内存为0B,无法打开

**Comment by liuhuiCNN** [comment]
> > 您好，请问是用 deploy 文件夹下代码进行部署吗？
> > 使用 deploy 文件夹下代码进行部署需要先导出模型，直接下载的模型不能直接这样部署。
> > 模型导出可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_MODEL.md
> 
> IndexError: tuple index out of range 打开设想头时的报错，
> 用视频预测的时候，没有报错，但预测结果的视频内存为0B,无法打开

paddle 2.1.0 + ppdet 2.1.0 ppylov2 python视频预测我们测试是正常的。请您检测一下本地环境是否正确，尤其是检测ffmpeg安装是否正确。建议本地先写一个简单的视频读写单测测试一下看看。

**Comment by Enyu-Liu** [comment]
> > > 您好，请问是用 deploy 文件夹下代码进行部署吗？
> > > 使用 deploy 文件夹下代码进行部署需要先导出模型，直接下载的模型不能直接这样部署。
> > > 模型导出可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_MODEL.md
> > 
> > 
> > IndexError: tuple index out of range 打开设想头时的报错，
> > 用视频预测的时候，没有报错，但预测结果的视频内存为0B,无法打开
> 
> paddle 2.1.0 + ppdet 2.1.0 ppylov2 python视频预测我们测试是正常的。请您检测一下本地环境是否正确，尤其是检测ffmpeg安装是否正确。建议本地先写一个简单的视频读写单测测试一下看看。

您好，我在aistudio上测试了一下，同样有报错IndexError: tuple index out of range，请问这是什么问题？

**Comment by liuhuiCNN** [comment]
请确认aistudio上ffmpeg环境是否正常，建议本地测试一下看看。

**Comment by Enyu-Liu** [comment]
您好，请问ffmpeg需要怎么测试，我在本地读写了一下视频，是正常的

**Comment by liuhuiCNN** [comment]
如果本地测试正常的话，说明代码是OK的。可能是云服务器环境问题，不支持视频读写。建议您在云服务器训练模型，本地预测。

**Comment by xiegegege** [comment]
> > 您好，请问是用 deploy 文件夹下代码进行部署吗？
> > 使用 deploy 文件夹下代码进行部署需要先导出模型，直接下载的模型不能直接这样部署。
> > 模型导出可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_MODEL.md
> 
> IndexError: tuple index out of range 打开设想头时的报错，
> 用视频预测的时候，没有报错，但预测结果的视频内存为0B,无法打开

@YuEn-git camera_id这个参数可以设置成0 - (摄像头数目-1)，如果超过摄像头个数-1就会报你这个错
