### ISSUE TITLE
如何任意将一个节点当模型输出节点？

### ISSUE THREAD

**Issue by EdwardVincentMa** [PaddlePaddle/PaddleDetection#3554]
如何任意将一个节点当模型输出节点？
您好，我将 ppyolo_tiny 转 mnn，发现 BBox 输出结果错误，想将模型的某些节点作为输出节点检查错误点的位置。想随笔输出一个节点。

**Comment by liuhuiCNN** [comment]
可以在网络前向Forward中，在需要返回的地方return结果。这样构造的网络就是您需要的子网络了。然后再讲改子网络转成其他格式。

**Comment by qingqing01** [comment]
拿YOLO (含PP YOLO)来说，下面返回的是nms后的结果，您可以更改下面返回的内容:

https://github.com/PaddlePaddle/PaddleDetection/blob/8c6f05f5ea2933dad79e03855939514613949336/ppdet/modeling/architectures/yolo.py#L96

**Comment by EdwardVincentMa** [comment]
![image](https://user-images.githubusercontent.com/39480728/124233646-a0af4700-db45-11eb-8b38-0eb5020b725d.png)，yolo_box 中有很多节点，但是这些节点貌似被paddlepaddle 封装了，我是想看其中任意一个小节点。不是 yolo_box 返回的节点

**Comment by EdwardVincentMa** [comment]
> 可以在网络前向Forward中，在需要返回的地方return结果。这样构造的网络就是您需要的子网络了。然后再讲改子网络转成其他格式。
![image](https://user-images.githubusercontent.com/39480728/124233646-a0af4700-db45-11eb-8b38-0eb5020b725d.png)，yolo_box 中有很多节点，但是这些节点貌似被paddlepaddle 封装了，我是想看其中任意一个小节点。不是 yolo_box 返回的节点

**Comment by EdwardVincentMa** [comment]
> 拿YOLO (含PP YOLO)来说，下面返回的是nms后的结果，您可以更改下面返回的内容:
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/8c6f05f5ea2933dad79e03855939514613949336/ppdet/modeling/architectures/yolo.py#L96

因为 yolo_box 是 paddlepaddle封装的库吧，想返回 yolo_box 中的某一个小节点，可以做到吗？

**Comment by qingqing01** [comment]
yolo_box是个完整的算子，无法返回中间的某个小节点，只能返回yolo_box之前的节点。
