### ISSUE TITLE
训练时--eval报错

### ISSUE THREAD

**Issue by wzwb** [PaddlePaddle/PaddleDetection#3555]
我希望在每一轮训练完进行验证，python tools/train.py --eval但是会出现报错如图。当我用python tools/eval.py进行测试时可以正常出结果。请问这是哪里的问题？
![image](https://user-images.githubusercontent.com/63113083/123976244-94fe3c00-d9f0-11eb-8d3e-550b852ae4f1.png)

**Comment by liuhuiCNN** [comment]
根据日志，是检测结果为空而报错，在训练初期由于网络还未收敛，有可能预测结果是空。等训练完成后，在进行评估是正常的。请问您两次使用是同一个模型权重吗？

**Comment by wzwb** [comment]
您好，感谢您的回复，我这两个不使用的同一个模型权重，在训练的时候加上--eval是在第一个epoch训练完然后进行eval时出现报错，然后我把--eval去掉，在训练完12个epoch之后，使用最后一轮的模型权重进行python tools/eval.py进行验证可以正常出结果。我把报错的bbox.json进行输出，里面并不是空的。
![image](https://user-images.githubusercontent.com/63113083/124054255-39659a00-da54-11eb-82da-22ef71709679.png)

**Comment by liuhuiCNN** [comment]
> 您好，感谢您的回复，我这两个不使用的同一个模型权重，在训练的时候加上--eval是在第一个epoch训练完然后进行eval时出现报错，然后我把--eval去掉，在训练完12个epoch之后，使用最后一轮的模型权重进行python tools/eval.py进行验证可以正常出结果。我把报错的bbox.json进行输出，里面并不是空的。
> ![image](https://user-images.githubusercontent.com/63113083/124054255-39659a00-da54-11eb-82da-22ef71709679.png)

我的意思是，--eval的时候，第一轮评估时，由于网络还没收敛，预测结果为空。

**Comment by wzwb** [comment]
您好，我这个截图就是第一轮训练后预测的结果。

**Comment by wwwPADDLE** [comment]
请问只能训练迭代一轮 就跳出是什么问题呢？ （试了环境用anaconda和python原声环境 都会出现这个问题）
![5736363ebd0ad6386099f9399fb408d](https://user-images.githubusercontent.com/57277333/124059328-7e41fe80-da5d-11eb-823c-c59e95ed1302.png)

**Comment by wzwb** [comment]
应该是2.0-rc本身代码的问题，在--eval和eval.py的时候少了一步更改self.mode的步骤。当进入trainer.py中的train方法之后，如果是--eval此时validate=True。下面需要用到self._metrics,这个self._metrics是在初始化Trainer类的时候进行初始化的，因为现在是训练过程，所以初始化的时候self.mode='train'，self.dataset是训练集的dataset,所以在_init_metrics方法中，COCOMetric(
                    anno_file=self.dataset.get_anno(),
                    bias=bias）的时候获取的就是训练集的标注数据。应该在train中多加一步操作：
![image](https://user-images.githubusercontent.com/63113083/124065326-24dfcc80-da69-11eb-8670-7022f37ef8c8.png)

下面是上述解释的整体步骤：
首先进入trainer.py的train方法中，此时validate=True
![image](https://user-images.githubusercontent.com/63113083/124065392-50fb4d80-da69-11eb-8b5f-e86b290801c1.png)
然后进入
__eval_with_loader()方法中,其中的self._metrics还是之前初始化时候的值
![image](https://user-images.githubusercontent.com/63113083/124065481-82741900-da69-11eb-85e9-7eff6d2697ca.png)
接下来看看在哪里进行了初始化，因为此时是通过train.py进来的，所以self.mode='train'
![image](https://user-images.githubusercontent.com/63113083/124065562-a8012280-da69-11eb-867f-18c956015813.png)
![image](https://user-images.githubusercontent.com/63113083/124065682-d7179400-da69-11eb-91b2-2a82a4062b19.png)

所以此处获取的是测试集的标注
下面是我在coco_utils.py中加了一个print语句后显示的结果
![image](https://user-images.githubusercontent.com/63113083/124065887-3aa1c180-da6a-11eb-9c0f-39635d82bca8.png)
![image](https://user-images.githubusercontent.com/63113083/124070563-9707df80-da70-11eb-807a-7c5ea7829c8b.png)
![image](https://user-images.githubusercontent.com/63113083/124070575-9b33fd00-da70-11eb-8218-944bca55f729.png)

**Comment by liuhuiCNN** [comment]
文件内容是否是空的呢？

**Comment by wzwb** [comment]
> 文件内容是否是空的呢？

您好，我之前跟您的回复截图就是bbox.json内容，您可以看一下。并不是空的

**Comment by liuhuiCNN** [comment]
（1）你好，请更新一下代码试试；
（2）请检查一下配置中EvalReader中数据路径是否正确。

**Comment by wzwb** [comment]
更新成2.1应该没问题，但是比赛环境是2.0-rc。。。
