### ISSUE TITLE
DLL

### ISSUE THREAD

**Issue by Dejavusd** [PaddlePaddle/PaddleDetection#3556]
用PyInstaller打包时，其中出现
WARNING: lib not found: mkldnn.dll dependency of d:\anaconda\ana\envs\paddle-10.1\lib\site-packages\paddle\fluid\core_avx.pyd
不知道有没有和paddle关系

**Comment by liuhuiCNN** [comment]
看起来是打包失败，看看是不是路径配置错误导致的。可以参考issue #3298。或者到Paddle repo提issue问下。
