### ISSUE TITLE
只能训练迭代一轮 就跳出 无法生成权重文件 进行下一轮迭代

### ISSUE THREAD

**Issue by wwwPADDLE** [PaddlePaddle/PaddleDetection#3558]
请问只能训练迭代一轮 就跳出是什么问题呢？ （试了环境用anaconda和python原声环境 都会出现这个问题）
![5736363ebd0ad6386099f9399fb408d](https://user-images.githubusercontent.com/57277333/124059587-e7297680-da5d-11eb-98d0-a1e655ef1b56.png)

**Comment by lizhenhanabc** [comment]
我也遇到了，还没解决

**Comment by shenjun1994** [comment]
遇到同样问题，好几个月前就遇到了，今天又重新安装环境试试，还是一样在第一轮最后一个batchsize就自动退出了。

**Comment by jerrywgz** [comment]
目前我们正在解决这个问题，从复现情况来看，会在某些windows环境下出现这个问题，我们本地的环境还都没有复现这个问题，想请问下能否提供下远程协助的环境呢，我们可以登录看下具体情况。

对现在出现的问题很抱歉，我们尽快解决～

**Comment by zhwesky2010** [comment]
@wangbo-git 您好，我们内部的Windows环境是 `Windows 10专业版 版本号：21H1、CUDA10.1、Python3.7、显卡2080Ti`，无法复现问题，请问与这个环境有什么差异吗

**Comment by shenjun1994** [comment]
> @wangbo-git 您好，我们内部的Windows环境是 `Windows 10专业版 版本号：21H1、CUDA10.1、Python3.7、显卡2080Ti`，无法复现问题，请问与这个环境有什么差异吗

windows10版本号一样，我的是cuda10.2， 其他一样，“https://github.com/PaddlePaddle/PaddleDetection/issues/2475”，这是我以前训练时遇到的同样问题，换了现在的版本代码后，现在的情况和#3558一样

**Comment by FAFUzxf** [comment]
> 

请问你们现在有解决这个问题吗？
