### ISSUE TITLE
cascade_rcnn_r50_fpn：std::exception caught, parallel_for failed: invalid configuration argument

### ISSUE THREAD

**Issue by huxianhe0** [PaddlePaddle/PaddleDetection#356]
运行cascade_rcnn_r50_fpn_1x.yml网络，2个gpu，自己的数据集，num_classes=1,遇到如下问题，多次运行都是到一半就戛然停止，求助百度paddlepaddle的开发大神帮忙看下咋回事？
![avatar](https://github.com/huxianhe0/Pictures/blob/master/2020-03-19%2011-01-58-snap.png?raw=true)
用coco2017数据集却从头到尾跑的很顺畅，没遇到问题。

**Comment by huxianhe0** [comment]
使用了finetune后仍没能解决问题
![avatar](https://github.com/huxianhe0/Pictures/blob/master/2020-03-19%2015-06-14-snap.png?raw=true)

**Comment by huxianhe0** [comment]
2020-03-19 15:04:57,922-INFO: iter: 2940, lr: 0.020000, 'loss_cls_0': '0.000000', 'loss_loc_0': '0.249135', 'loss_cls_1': '0.000000', 'loss_loc_1': '0.074044', 'loss_cls_2': '0.000000', 'loss_loc_2': '0.000000', 'loss_rpn_cls': '0.549833', 'loss_rpn_bbox': '0.128763', 'loss': '1.384443', time: 0.881, eta: 21:18:56
/home/zhaogang/Envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 323, in <module>
    main()
  File "tools/train.py", line 233, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/home/zhaogang/Envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/home/zhaogang/Envs/paddle/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/zhaogang/Envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/home/zhaogang/Envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 843, in _run_impl
    return_numpy=return_numpy)
  File "/home/zhaogang/Envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 677, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
3   paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
4   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, long>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::details::ComputationOpHandle::RunImpl()
9   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
10  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
11  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
12  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
13  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/zhaogang/Envs/paddle/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/zhaogang/Envs/paddle/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/zhaogang/Envs/paddle/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 135, in append_bias_op
    attrs={'axis': dim_start})
  File "/home/zhaogang/Envs/paddle/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 357, in fc
    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)
  File "/home/zhaogang/Python/PaddleDetection/ppdet/modeling/roi_heads/cascade_head.py", line 338, in __call__
    regularizer=L2Decay(0.)))
  File "/home/zhaogang/Python/PaddleDetection/ppdet/modeling/roi_heads/cascade_head.py", line 70, in get_output
    head_feat = self.head(roi_feat, wb_scalar, name)
  File "/home/zhaogang/Python/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 158, in build
    name='_' + str(i + 1) if i > 0 else '')
  File "/home/zhaogang/Python/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 328, in train
    return self.build(feed_vars, 'train')
  File "tools/train.py", line 116, in main
    train_fetches = model.train(feed_vars)
  File "tools/train.py", line 323, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: When calling this method, the Tensor's numel must be equal or larger than zero. Please check Tensor::dims, or Tensor::Resize has been called first. The Tensor's shape is [-1, 1024] now
  [Hint: Expected numel() >= 0, but received numel():-1024 < 0:0.] at (/paddle/paddle/fluid/framework/tensor.cc:45)
  [operator < elementwise_add > error]
terminate called without an active exception
W0319 15:05:03.347280 21290 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0319 15:05:03.347293 21290 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0319 15:05:03.347296 21290 init.cc:214] The detail failure signal is:

W0319 15:05:03.347301 21290 init.cc:217] *** Aborted at 1584601503 (unix time) try "date -d @1584601503" if you are using GNU date ***
W0319 15:05:03.348135 21290 init.cc:217] PC: @                0x0 (unknown)
W0319 15:05:03.348217 21290 init.cc:217] *** SIGABRT (@0x3e8000052ae) received by PID 21166 (TID 0x7f1739029700) from PID 21166; stack trace: ***
W0319 15:05:03.348958 21290 init.cc:217]     @     0x7f17c7ce4890 (unknown)
W0319 15:05:03.349579 21290 init.cc:217]     @     0x7f17c717ae97 gsignal
W0319 15:05:03.350181 21290 init.cc:217]     @     0x7f17c717c801 abort
W0319 15:05:03.350788 21290 init.cc:217]     @     0x7f17a17f7957 (unknown)
W0319 15:05:03.351455 21290 init.cc:217]     @     0x7f17a17fdae6 (unknown)
W0319 15:05:03.351944 21290 init.cc:217]     @     0x7f17a17fdb21 std::terminate()
W0319 15:05:03.352419 21290 init.cc:217]     @     0x7f17a17fd4ea __gxx_personality_v0
W0319 15:05:03.352859 21290 init.cc:217]     @     0x7f17ae527668 (unknown)
W0319 15:05:03.353296 21290 init.cc:217]     @     0x7f17ae527c5c _Unwind_ForcedUnwind
W0319 15:05:03.353914 21290 init.cc:217]     @     0x7f17c7ce2f10 __GI___pthread_unwind
W0319 15:05:03.354516 21290 init.cc:217]     @     0x7f17c7cdaae5 __pthread_exit
W0319 15:05:03.354822 21290 init.cc:217]     @     0x55a32a98b53c PyThread_exit_thread
W0319 15:05:03.355108 21290 init.cc:217]     @     0x55a32aaa2f47 PyEval_RestoreThread
W0319 15:05:03.356739 21290 init.cc:217]     @     0x7f1774c98c49 pybind11::gil_scoped_release::~gil_scoped_release()
W0319 15:05:03.356930 21290 init.cc:217]     @     0x7f1774c45644 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL22pybind11_init_core_avxERNS_6moduleEEUlRNS2_9operators6reader22LoDTensorBlockingQueueERKSt6vectorINS2_9framework9LoDTensorESaISC_EEE60_bIS9_SG_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESY_
W0319 15:05:03.358497 21290 init.cc:217]     @     0x7f1774cb6fc1 pybind11::cpp_function::dispatcher()
W0319 15:05:03.358856 21290 init.cc:217]     @     0x55a32aa144b3 _PyCFunction_FastCallKeywords
W0319 15:05:03.358975 21290 init.cc:217]     @     0x55a32aaa24a0 call_function
W0319 15:05:03.359374 21290 init.cc:217]     @     0x55a32aaa6fb0 _PyEval_EvalFrameDefault
W0319 15:05:03.359467 21290 init.cc:217]     @     0x55a32aaa2343 _PyEval_EvalCodeWithName
W0319 15:05:03.359797 21290 init.cc:217]     @     0x55a32aaa33ce PyEval_EvalCodeEx
W0319 15:05:03.359923 21290 init.cc:217]     @     0x55a32a9da6ed function_call
W0319 15:05:03.360213 21290 init.cc:217]     @     0x55a32a9a705e PyObject_Call
W0319 15:05:03.360504 21290 init.cc:217]     @     0x55a32aaa549a _PyEval_EvalFrameDefault
W0319 15:05:03.360558 21290 init.cc:217]     @     0x55a32aaa1818 _PyFunction_FastCall
W0319 15:05:03.360651 21290 init.cc:217]     @     0x55a32aaa2886 call_function
W0319 15:05:03.360991 21290 init.cc:217]     @     0x55a32aaa6fb0 _PyEval_EvalFrameDefault
W0319 15:05:03.361088 21290 init.cc:217]     @     0x55a32aaa1818 _PyFunction_FastCall
W0319 15:05:03.361179 21290 init.cc:217]     @     0x55a32aaa2886 call_function
W0319 15:05:03.361496 21290 init.cc:217]     @     0x55a32aaa6fb0 _PyEval_EvalFrameDefault
W0319 15:05:03.361580 21290 init.cc:217]     @     0x55a32aaa1818 _PyFunction_FastCall
W0319 15:05:03.361841 21290 init.cc:217]     @     0x55a32aaab8e0 _PyFunction_FastCallDict
已放弃 (核心已转储)

**Comment by FDInSky** [comment]
你的paddle是编译安装的吗？我也遇到过类似问题，后来重新编译安装了paddle解决了

**Comment by huxianhe0** [comment]
最后找到了解决办法，需要确认数据类别是否加上了背景类，例如，coco数据集的类别数为80，在mask-rcnn中使用的num_classes就是81（增加一类背景类）

**Comment by huxianhe0** [comment]
> 你的paddle是编译安装的吗？我也遇到过类似问题，后来重新编译安装了paddle解决了

最后找到了解决办法，需要确认数据类别是否加上了背景类，例如，coco数据集的类别数为80，在cascade-rcnn中使用的num_classes就是81（增加一类背景类 add a background category）。我的数据集就1类，num_classes=2
