### ISSUE TITLE
关于特色垂类检查模型的行人与汽车的训练数据集

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleDetection#3560]
官网：[https://paddledetection.readthedocs.io/featured_model/CONTRIB_cn.html#pedestrian-detection](url)

请问能开源特色垂类检查模型的行人与汽车的训练数据集吗？还有两者的训练图片数量大概是多少？

**Comment by wangxinxin08** [comment]
你好，训练数据集不公开
