### ISSUE TITLE
模型库中未找到Readme中介绍的模型CBResNet

### ISSUE THREAD

**Issue by ZiQiangXie** [PaddlePaddle/PaddleDetection#3561]
Cascade-Faster-RCNN-CBResNet200vd-FPN，这个模型在模型库和配置文件中均未找到，readme中介绍说是模型库中都有。
另外backbone里面没有看到cbresnet的网络文件，想问一下，有没有支持？

**Comment by nemonameless** [comment]
#3450   
在static目录下，是以前的静态图模型
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/docs/MODEL_ZOO_cn.md
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/configs/dcn/cascade_rcnn_cbr200_vd_fpn_dcnv2_nonlocal_softnms.yml
暂时只有静态图版本。后期动态图应该也会支持。

**Comment by ZiQiangXie** [comment]
@wangxinxin08 好的 谢谢
