### ISSUE TITLE
is it possible to perform QAT on pruned models?

### ISSUE THREAD

**Issue by ichbing1** [PaddlePaddle/PaddleDetection#3566]
Hi,

I trained a pruned model with `python tools/train.py --slim_config configs/slim/prune/ppyolo_r50vd_prune_fpgm.yml` using a custom dataset.

For further acceleration, I applied `int8` post-training quantization with 500 calibration images, but the detection accuracy got considerably worse than `fp16` (about 4-5 mAP points lower).

To minimize the drop in accuracy, I would like to perform quantization-aware training on the pruned model, but it seems only one type of `slim` can be specified at training time.

Does current version of PaddleDetection or PaddleSlim support doing QAT on pruned models? For example, if it's possible to save the pruned model just like a normal model (.pdparams, .pdopt), then it would be possible to do QAT on it by using it as a pretrained model for further training. But I couldn't find a way to save the pruned model as files.

FYI, I'm using PaddleDetection release/2.1. Any advice would be greatly appreciated.

**Comment by yghstill** [comment]
@ichbing1 Thanks for your feedback, now there is only a combined strategy of distillation and pruning in PaddleDetection, and we will support the combined strategy of pruning and quantification in the future. You can modify the code about slim to increase the mode of `PruneQAT`:
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/slim/__init__.py#L50

**Comment by ichbing1** [comment]
> @ichbing1 Thanks for your feedback, now there is only a combined strategy of distillation and pruning in PaddleDetection, and we will support the combined strategy of pruning and quantification in the future. You can modify the code about slim to increase the mode of `PruneQAT`:
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/slim/__init__.py#L50

Oh, I had originally thought of modifying the code before giving up, but looking at the code again, it does seem possible to modify it to make it work, by first calling `cfg.pruner` on the model, loading weights, and then setting `cfg.slim = 'QAT'` to slim the model. I also built a config file by combining pruning and QAT, and now the training works well. Thanks a lot for your help!

**Comment by LMR2018** [comment]
> 

@ichbing1    你好，请问能具体分享一下你的做法吗？还有你的配置文件

**Comment by Jiashuhao518** [comment]
> > @ichbing1 Thanks for your feedback, now there is only a combined strategy of distillation and pruning in PaddleDetection, and we will support the combined strategy of pruning and quantification in the future. You can modify the code about slim to increase the mode of `PruneQAT`:
> > https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/slim/__init__.py#L50
> 
> Oh, I had originally thought of modifying the code before giving up, but looking at the code again, it does seem possible to modify it to make it work, by first calling `cfg.pruner` on the model, loading weights, and then setting `cfg.slim = 'QAT'` to slim the model. I also built a config file by combining pruning and QAT, and now the training works well. Thanks a lot for your help!

Hello, I'm confused about modifying this code in _init_.py and config file , could you show me your modification ? Thanks a lot!
