### ISSUE TITLE
ppyolov2部署后推理报错cuda error(77)

### ISSUE THREAD

**Issue by Yikunzhang** [PaddlePaddle/PaddleDetection#3567]
用自己的训练数据训练了ppyolov2模型，然后导出模型后用deploy/python/infer.py进行推理，在少量数据集上测试没有问题，但对3万张数据集进行预测时会在中途报错。
报错信息如下：
save result to: /home/zyk/aaa/000031-2021-06-25_18-19-23-255.jpg
Traceback (most recent call last):
  File "deploy/python/infer.py", line 582, in <module>
    main()
  File "deploy/python/infer.py", line 506, in main
    predict_image(detector)
  File "deploy/python/infer.py", line 424, in predict_image
    results = detector.predict(imageName, FLAGS.threshold)
  File "deploy/python/infer.py", line 129, in predict
    input_tensor.copy_from_cpu(inputs[input_names[i]])
OSError: (External)  Cuda error(77), an illegal memory access was encountered.
  [Advise: The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:296)

terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  (External)  Cuda error(77), an illegal memory access was encountered.
  [Advise: The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:411)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::~AnalysisPredictor()
1   paddle::AnalysisPredictor::~AnalysisPredictor()
2   paddle::memory::allocation::AutoGrowthBestFitAllocator::FreeIdleChunks()
3   paddle::memory::allocation::AlignedAllocation::~AlignedAllocation()
4   paddle::memory::allocation::CUDAAllocator::FreeImpl(paddle::memory::allocation::Allocation*)
5   paddle::platform::RecordedCudaFree(void*, unsigned long, int)
6   paddle::framework::SignalHandle(char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1625195001 (unix time) try "date -d @1625195001" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3ea0002ad76) received by PID 175478 (TID 0x7fe584019700) from PID 175478 ***]

Aborted (core dumped)

**Comment by lyuwenyu** [comment]
- 什么版本的paddle 和 ppdet

**Comment by liuhuiCNN** [comment]
每次预测结束后建议增加内存回收代码：
`// 释放中间Tensor
predictor->ClearIntermediateTensor();

// 释放内存池中的所有临时 Tensor
predictor->TryShrinkMemory();`
参考文档：https://paddle-inference.readthedocs.io/en/latest/api_reference/cxx_api_doc/Predictor.html

**Comment by liuhuiCNN** [comment]
你好，方便提供一个可以复现的环境和代码吗？方便我们调试。

**Comment by Yikunzhang** [comment]
> * addle

**Comment by Yikunzhang** [comment]
> * addle

**Comment by Yikunzhang** [comment]
> * addle

**Comment by Yikunzhang** [comment]
> * 什么版本的paddle 和 ppdet

@lyuwenyu 不好意思忘说了
环境是
paddledet           2.0.1
paddlepaddle-gpu    2.0.2.

**Comment by Yikunzhang** [comment]
> 你好，方便提供一个可以复现的环境和代码吗？方便我们调试。

@liuhuiCNN 环境就是paddle2.0.2环境，用的是/deploy/python/infer.py，做了一点修改其实就是加了for循环，用于推理整个文件夹内的图片。代码可能不是很方便，我先尝试一下在每次预测完单张图片后回收内存，非常感谢！

**Comment by Yikunzhang** [comment]
@liuhuiCNN 
可能是由于infer.py内
input_tensor.copy_from_cpu(inputs[input_names[i]]) 
中的copy_from_cpu函数出现的问题
