### ISSUE TITLE
Data parallel and memory sharing

### ISSUE THREAD

**Issue by XiongZhongxia** [PaddlePaddle/PaddleDetection#3569]
Hi there. During training, I found memory cost often increases which may break the training procedure. In addition, I only have a PC of 4×12GB GPUs, I cannot train large models such as Res101 even using batch_size=1. So can I use these 4 GPUs to share just 1 image when training? In other words, I assume using batch_size=1 on 4 GPUs leads to totall batch_size=4, but can I training on these GPUs using total batchsize=1? Thanks in advance.

我主要是想在四张12G的卡上跑个大模型，但是显存经常不够用。能不能像pytorch那样四张卡共享一张图片，总的batch_size=1呢？

**Comment by lyuwenyu** [comment]
`四张卡共享一张图片，总的batch_size=1` torch怎么操作的?

我觉得你应该 把graph的不同部分 放到不同的卡上做计算

**Comment by XiongZhongxia** [comment]
> 
> 
> `四张卡共享一张图片，总的batch_size=1` torch怎么操作的?
> 
> 我觉得你应该 把graph的不同部分 放到不同的卡上做计算

你说的对，torch里也是把不同部分放在不同的GPU上。看来得自己改了啊。。。
