### ISSUE TITLE
windows端运行模型

### ISSUE THREAD

**Issue by JunLei01** [PaddlePaddle/PaddleDetection#3575]
在AI studio上训练好的模型放到Windows本地端效果就很差，模型是修改过的，但是在AIstudio上运行效果不错，一旦在本地端运行效果就很差，而且差距很明显。

**Comment by nemonameless** [comment]
PaddlePaddle 和 PaddleDetection 版本是否两边一致呢？改动代码后最好pip setup.py install 更新一下
