### ISSUE TITLE
ValueError: Dataset dataset/Gun_detection is not valid and cannot parse dataset type 'Gun_detection' for automaticly downloading, which only supports 'voc ' , 'coco', 'wider_face', 'fruit', 'roadsign_voc' and 'mot' currently

### ISSUE THREAD

**Issue by LiangYong1216** [PaddlePaddle/PaddleDetection#3576]
当我训练我数据集的时候出现了问题，
![image](https://user-images.githubusercontent.com/66230782/124280928-cfe0ab00-db7b-11eb-8ae8-2c4b89b2cc23.png)
我知道配置除了问题，可是不论怎么修改都不对

我的环境：win10  paddledetection2.1

**Comment by nemonameless** [comment]
这本来是为了方便刚开始使用时自动下载经典数据集。自定义数据集没有注册名字就不行了。您可以注释掉这个函数 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/source/dataset.py#L151   ，然后python setup.py install更新一下，就可以运行了。

**Comment by LiangYong1216** [comment]
> 这本来是为了方便刚开始使用时自动下载经典数据集。自定义数据集没有注册名字就不行了。您可以注释掉这个函数 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/source/dataset.py#L151 ，然后python setup.py install更新一下，就可以运行了。

感谢感谢，已经解决了，但是出现了新的问题，我又提问了，还清多多指教

**Comment by zzzfo** [comment]
怎么我注释掉也更新了，还是有这个错误啊

**Comment by LiangYong1216** [comment]
> 怎么我注释掉也更新了，还是有这个错误啊
你整理好数据集后好好检查一下图片，我那个是 因为只复制了图片名字导致的错误

**Comment by zzzfo** [comment]
> > 怎么我注释掉也更新了，还是有这个错误啊
> > 你整理好数据集后好好检查一下图片，我那个是 因为只复制了图片名字导致的错误

ok,感谢

**Comment by wenyifromsichuan** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/b0e3ce94d00409a53f32e4674a5a4cf5a23877ba/ppdet/data/source/dataset.py#L151请问是注释掉dataset_dir这一行，还是 super(ImageFolder, self).__init__(
            dataset_dir,
            image_dir,
            anno_path,
            sample_num=sample_num,
            use_default_label=use_default_label) 整个函数，试过后都不行
