### ISSUE TITLE
自训练的ppyolo_tiny模型，predict的score非常小

### ISSUE THREAD

**Issue by chenxuezhao** [PaddlePaddle/PaddleDetection#3588]
训练流程：
1、根据自己已标定过的图片(100张），生成coco格式的数据。（生成instances_train2017.json和instances_val2017.json）
2、开启训练：python3  tools/train.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml
3、训练完成（650 轮），且生成了output/ppyolo_tiny_650e_coco/model_final.pdopt 和 output/ppyolo_tiny_650e_coco/model_final.pdparams
4、predict一张训练过程当中使用过的图片，发现predict的score非常小，导致最后生成的检测结果的图片没有任何结果框。predict的命令：
`python3 tools/infer.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml -o weights=output/ppyolo_tiny_650e_coco/model_final.pdparams --infer_img=./test.jpg`

**Comment by chenxuezhao** [comment]
训练开启之前，主要修改了以下配置文件：
configs/datasets/coco_detection.yml
`将num_classes: 80，改为：num_classes: 5`
因为我只需要检测5种类型的物体；instances_train2017.json文件中的categories也定义了5种类型。

**Comment by chenxuezhao** [comment]
按照我的理解，predict一张训练过程中使用的图片，即使训练的数据比较少，但最后的识别结果应该也是比较好的，不是吗？

**Comment by heavengate** [comment]
你用的哪个版本呢，PP-YOLO系列最近修复过一个训练上收敛性的问题，可以更新到最新develop分支，`python setup.py install`试下
参考 https://github.com/PaddlePaddle/PaddleDetection/issues/3411

**Comment by chenxuezhao** [comment]
我用的是release/2.1

**Comment by chenxuezhao** [comment]
![image](https://user-images.githubusercontent.com/42796059/124448275-d7d75f80-ddb4-11eb-8020-689047d10b84.png)

**Comment by chenxuezhao** [comment]
checkout到develop分支后，模型需要重新训练吗？

**Comment by chenxuezhao** [comment]
我的instances_train2017.json文件是格式是这样的，请帮忙确认一下，是不是instances_train2017.json文件的格式错误导致的这个问题：
![image](https://user-images.githubusercontent.com/42796059/124455914-b24e5400-ddbc-11eb-9257-48325c24456b.png)
![image](https://user-images.githubusercontent.com/42796059/124456617-7ebff980-ddbd-11eb-8db5-888452928579.png)

**Comment by chenxuezhao** [comment]
@heavengate 你好，我从COCO数据集当中选取了10张图片进行训练，训练40轮之后，将训练当中用到的一张图片送入生成的模型做predict，predict的结果是这样的：
![test1](https://user-images.githubusercontent.com/42796059/124529465-43fda600-de3d-11eb-85df-128c3a955377.jpg)
按照我的理解，predict一张训练过程中使用的图片，即使训练的数据比较少，但最后的识别结果应该也是比较好的，但现在看起来好像不是这样的（我用的develope版本），请问是不是我理解的不对？

**Comment by heavengate** [comment]
> checkout到develop分支后，模型需要重新训练吗？

需要重新训练下

**Comment by heavengate** [comment]
> 我的instances_train2017.json文件是格式是这样的，请帮忙确认一下，是不是instances_train2017.json文件的格式错误导致的这个问题：
> ![image](https://user-images.githubusercontent.com/42796059/124455914-b24e5400-ddbc-11eb-9257-48325c24456b.png)
> ![image](https://user-images.githubusercontent.com/42796059/124456617-7ebff980-ddbd-11eb-8db5-888452928579.png)

格式看着没什么问题，或者可以可视化看下

**Comment by chenxuezhao** [comment]
你好，我把coco的5000张val数据当做train数据来训练ppyolo的tiny模型，训练十几轮之后，用训练的图片进行predict,predict的结果score还是非常小，导致结果图片没有画出任何框。
我用的是develop的代码：
![image](https://user-images.githubusercontent.com/42796059/124541059-3e12bf80-de53-11eb-8d0e-44aeab615c5b.png)

**Comment by chenxuezhao** [comment]
按照我的理解，predict一张训练过程中使用的图片，即使训练的数据比较少，但最后的识别结果应该也是比较好的。是不是我的理解有偏差？

**Comment by heavengate** [comment]
即使是预测原图，训练十几个iter也没有收敛的，甚至训练网络都没有过一遍这5000张图，如果想预测训练的数据看看效果，至少要训练到loss收敛到比较低的水平，5000张图的话一般可以训练几千个iter，并且对应调整learning rate的decay
