### ISSUE TITLE
预下载的权重样本无法使用 CascadeMaskRCNN

### ISSUE THREAD

**Issue by KKDDD** [PaddlePaddle/PaddleDetection#359]
![image](https://user-images.githubusercontent.com/21326738/77073868-e4eb0680-6a2a-11ea-841b-0d32b70528eb.png)

paddle版本是1.7.1的GPU，relase-0.2

**Comment by FDInSky** [comment]
你是说下载的CascadeMaskRCNN预训练权重，无法加载使用吗？

**Comment by KKDDD** [comment]
> 你是说下载的CascadeMaskRCNN预训练权重，无法加载使用吗？

是的，我的截图就是错误信息

**Comment by xiegegege** [comment]
@KKDDD 你好，我们这里在windows上试了下是可以正常加载的，但是如果路径名里有中文是会报这个错的，你能把路径里的中文改成英文吗？
![image](https://user-images.githubusercontent.com/46314656/77741388-ccdd3d80-704f-11ea-922b-6a114c8507f0.png)
