### ISSUE TITLE
请教导出ONNX后如何验证

### ISSUE THREAD

**Issue by raymondchu-z** [PaddlePaddle/PaddleDetection#3591]
使用的模型是PPYOLOv2，根据[文档](https://github.com/PaddlePaddle/PaddleDetection/blob/5e19955b011d47377a3f1443a6e592ddd9e5024a/deploy/EXPORT_ONNX_MODEL.md)导出了PPYOLOv2.onnx文件。
请问我应该怎样去验证这个导出的文件是正确的？

**Comment by raymondchu-z** [comment]
用[netron](https://netron.app/)查看这个模型，信息如下。这是正常的吗？
> MODEL PROPERTIES
format
ONNX v7
producer
PaddlePaddle
imports
ai.onnx v11
im_shape
name: im_shape
type: float32[-1,2]
image
name: image
type: float32[-1,3,640,640]
scale_factor
name: scale_factor
type: float32[-1,2]
save_infer_model/scale_0.tmp_1
name: save_infer_model/scale_0.tmp_1
type: float32[25200,6]
save_infer_model/scale_1.tmp_1
name: save_infer_model/scale_1.tmp_1
type: int32[-1]

**Comment by heavengate** [comment]
导出成功后就是ONNX的部署模型，要验证的话可以通过ONNX部署的方式，可以参考 https://aistudio.baidu.com/aistudio/projectdetail/1479970

**Comment by raymondchu-z** [comment]
@heavengate 感谢回复
1. 我希望将`ai.onnx::ll::NonMaxSuppression`这个算子从模型中剥离出来，应该怎么操作？
2. `ai.onnx::ll::NonZero`算子相关的资料文档应该在哪里找？
