### ISSUE TITLE
ppyolo导出tensorRT

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/PaddleDetection#3593]
请问下这里的ppyolo导出tensorRT并测试AP，有写好的脚本吗
<img width="529" alt="微信图片_20210705151909" src="https://user-images.githubusercontent.com/26462054/124432748-89ba6000-dda4-11eb-8df5-7d3a6d485579.png">

**Comment by heavengate** [comment]
导出模型是不需要指定TensorRT，TensorRT是部署的时候使用的加速方法，和模型导出过程无关，模型导出就直接用 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/configs/ppyolo#4-inferece-deployment  这里的导出方法就可以了，部署的时候可以指定使用TensorRT加速，可以参考   https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/TENSOR_RT.md

**Comment by zhengzhe97** [comment]
@heavengate 可能是我表达不清楚。想知道ppyolo的参数如何转化成tensorRT

**Comment by addicter2017** [comment]
同问, 目前知道在线量化训练可以得到Tensorrt的int8模型,那有没有办法得到tensorrt的Float32或者float16模型呢?

**Comment by heavengate** [comment]
> @heavengate 可能是我表达不清楚。想知道ppyolo的参数如何转化成tensorRT

不需要转换，导出模型正常导出，预测部署的时候开启tensorrt就可以了

**Comment by heavengate** [comment]
> 同问, 目前知道在线量化训练可以得到Tensorrt的int8模型,那有没有办法得到tensorrt的Float32或者float16模型呢?

fp32和fp16的不需要转换，设置`--run_mode=trt_fp32或者trt_fp16`就可以了

**Comment by wu-yakun** [comment]
可是，预测部署的时候开启TensorRT时，TensorRT会将paddlepaddle的模型转为符合TensorRT的模型格式，这个过程特别耗时间，大概需要至少5分钟。有什么方法可以解决吗？

**Comment by KevenLee** [comment]
可能需要自己去扣出相应的转换代码吧，就是不知道有没有特殊的层
