### ISSUE TITLE
请教关于YOLOv3+DarkNet53训练后的误识别：比如将黄色系的东西识别成火苗。请教如何解决？

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleDetection#3596]
请教关于YOLOv3+DarkNet53训练后的误识别：比如将黄色系的东西识别成火苗。请教如何解决？

**Comment by heavengate** [comment]
这个需要结合具体数据和场景判断的，可以尝试的方法有
1. 增加火苗和黄色的样本
2. 给火苗较高的接受阈值
3. 如果确实对分类精度要求很高，也可以考虑把检测的框抠出来再过一个分类器的方案

**Comment by 670133189** [comment]
> 这个需要结合具体数据和场景判断的，可以尝试的方法有
> 
> 1. 增加火苗和黄色的样本
> 2. 给火苗较好的接受阈值
> 3. 如果确实对分类精度要求很高，也可以考虑把检测的框抠出来再过一个分类器的方案

感谢您的回答，您提到的“增加黄色的样本”是指负样本么？如果是的话那该如何添加？我的理解是往训练集添加即可，而且也得有“仅有负样本路径”的Annotations文件。添加负样本图片后，模型里还需要调整代码么？我不知道这样理解对不对 ^ ^
