### ISSUE TITLE
训练过程开启eval,但是一直显示ppdet.engine INFO: Eval iter: 0

### ISSUE THREAD

**Issue by FeiMa-REC** [PaddlePaddle/PaddleDetection#3597]
训练开始：
![图片](https://user-images.githubusercontent.com/62004245/124450016-98aa0e00-ddb6-11eb-8562-acd49c570cd6.png)

训练途中：
![图片](https://user-images.githubusercontent.com/62004245/124450048-a2cc0c80-ddb6-11eb-9ffd-afddadeba0e9.png)

**Comment by heavengate** [comment]
eval过程每100个iter才会打印一次log，如果你的eval iter数不足100就会只打印0

**Comment by FeiMa-REC** [comment]
@heavengate 明白了，谢谢~
