### ISSUE TITLE
yolov3_darknet_voc加载预训练权重的时候出错

### ISSUE THREAD

**Issue by wssywh** [PaddlePaddle/PaddleDetection#360]
错误为：
Traceback (most recent call last):
  File "tools/train.py", line 325, in <module>
    main()
  File "tools/train.py", line 196, in main
    exe, train_prog, cfg.pretrain_weights, ignore_params=ignore_params)
  File ".\ppdet\utils\checkpoint.py", line 111, in load_params
    "exists.".format(path))
ValueError: Model pretrain path dataset/DarkNet53_pretrained.tar does not exists.
配置文件中给的权重URL为
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/DarkNet53_pretrained.tar
将下载后的tar文件解压
![image](https://user-images.githubusercontent.com/19625405/77082544-2ed9e980-6a37-11ea-8365-38e8a57e6e03.png)
出错的代码定位：
![image](https://user-images.githubusercontent.com/19625405/77082847-9db74280-6a37-11ea-8d18-29012e708cce.png)

下载的权重文件中不包含“.pdparams”文件

**Comment by heavengate** [comment]
`release/0.2`和`develop`代码需要使用Paddle 1.7的版本，Paddle 1.7版本兼容老的权重格式和新的.pdparams的权重格式
