### ISSUE TITLE
如何准备训练数据章节生成label_list示例代码有误

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/PaddleDetection#3604]
该目录下PaddleDetection/docs/tutorials/PrepareDataSet.md 
数据准备说明文件中，用户数据数据转换示例部分，示例在终端下生成label_list示例代码为：
>>echo "speedlimit\ncrosswalk\ntrafficlight\nstop" > label_list.txt， 使用该命令没有加入 -e 参数，\n起不到换行的作用。
应该为： echo  -e "speedlimit\ncrosswalk\ntrafficlight\nstop" > label_list.txt

**Comment by jerrywgz** [comment]
感谢反馈
