### ISSUE TITLE
在训练过程中，如何设置参数使得仅保留最新的几个checkpoint以及最优的checkpoint呢？

### ISSUE THREAD

**Issue by fantasysee** [PaddlePaddle/PaddleDetection#3605]
PaddleDetection团队的同学好，请问我在训练模型的过程中，如何设置参数使得仅保留最新的几个checkpoint以及最优的checkpoint呢？

我查看了一下 `runtime.yml` 文件，里面仅有 `snapshot_epoch ` 一个参数，并且设置这个并不能实现上述功能。另，请问如何查看所有可配置的命令行参数呢？我找了好久没有找到相应的文档，麻烦了！

**Comment by jerrywgz** [comment]
目前还没有支持这样的功能，如果开启--eval，是可以保存最优的checkpoint, 可以在ppdet/engine/callbacks.py下的Checkpointer中修改模型保存的逻辑

**Comment by fantasysee** [comment]
> 目前还没有支持这样的功能，如果开启--eval，是可以保存最优的checkpoint, 可以在ppdet/engine/callbacks.py下的Checkpointer中修改模型保存的逻辑

好的，感谢解答！
