### ISSUE TITLE
如何使export_model保存的模型不包含NMS

### ISSUE THREAD

**Issue by raymondchu-z** [PaddlePaddle/PaddleDetection#3607]
请教一下，如何修改PaddleDetection的代码，使它export_model保存的模型不包含NMS？

**Comment by jerrywgz** [comment]
![image](https://user-images.githubusercontent.com/22989727/124574911-83e47d80-de7d-11eb-913c-e35999764b54.png)
动态图下暂时还没有增加配置项来控制是否包含NMS,可以在模型导出的时候把配置文件中nms的相关配置删除

**Comment by raymondchu-z** [comment]
感谢回复，可以了。

**Comment by raymondchu-z** [comment]
转出来后ONNX模型的输出是：
> save_infer_model/scale_0.tmp_1
name: save_infer_model/scale_0.tmp_1
type: float32[1,25200,4]
save_infer_model/scale_1.tmp_1
name: save_infer_model/scale_1.tmp_1
type: float32[1,7,25200]

请问这些维度的含义是什么？@jerrywgz

**Comment by jerrywgz** [comment]
1表示batch size, 25200表示box的个数，7表示类别数

**Comment by raymondchu-z** [comment]
谢谢。4是什么？

**Comment by raymondchu-z** [comment]
@jerrywgz 你好，我的理解是：
[1,25200,4]是表示对于1张图片，预测出了25200个框，每个框的坐标是xyxy；
[1,7,25200]是表示对于1张图片，对于7个类别，这25200个预测框针对每个类别都有一个置信度分数。
是这样吗？
25200是怎么来的？
