### ISSUE TITLE
win10下编译cmake报错

### ISSUE THREAD

**Issue by wxf764571829** [PaddlePaddle/PaddleDetection#3609]
F:\code\Paddle\build>cmake .. -G "Visual Studio 14 2015 Win64"  -DWITH_GPU=OFF -DWITH_TESTING=OFF -DON_INFER=ON
-- Found Paddle host system: win32, version:
-- Found Paddle host system's CPU: 8 cores
-- Selecting Windows SDK version  to target Windows 10.0.19042.
CMake Error at CMakeLists.txt:23 (project):
  Generator

    Visual Studio 14 2015 Win64

  does not support platform specification, but platform

    x64

  was specified.

日志内容：
![image](https://user-images.githubusercontent.com/46362180/124572141-fef86480-de7a-11eb-986d-8a91fed7f141.png)

**Comment by jerrywgz** [comment]
Paddle编译安装的问题转到Paddle repo的issue下吧～https://github.com/PaddlePaddle/Paddle/issues
