### ISSUE TITLE
develop版本，ppyolo_tiny训练时异常退出

### ISSUE THREAD

**Issue by chenxuezhao** [PaddlePaddle/PaddleDetection#3615]
![image](https://user-images.githubusercontent.com/42796059/124683948-c69b6980-df00-11eb-997a-44ad8cdcaa22.png)

**Comment by yghstill** [comment]
@chenxuezhao 看报错可能是内存爆了，将worker_num 调小再试下：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/_base_/ppyolo_tiny_reader.yml#L1

**Comment by chenxuezhao** [comment]
@yghstill ppyolo_tiny训练70轮之后（训练数据是是从coco官网下载的coco val数据，总共5000张图片），predict一张训练用过的图片，检测结果很差，没有识别出任何物体。predict命令：
`python tools/infer.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml -o weights=output/ppyolo_tiny_650e_coco/69.pdparams use_gpu=false --infer_img=./test.jpg`
加载的预训练权重是：
![image](https://user-images.githubusercontent.com/42796059/124690771-3f082780-df0d-11eb-9d68-44f00c7fea9a.png)

**Comment by yghstill** [comment]
@chenxuezhao ppyolo_tiny收敛很慢，同时，你单卡训练的话，学习率需要调低8倍

**Comment by chenxuezhao** [comment]
@yghstill 这样设置吗？一般最后loss会收敛到多大？
![image](https://user-images.githubusercontent.com/42796059/124696161-2735a100-df17-11eb-850a-3e1b6711bff1.png)

**Comment by chenxuezhao** [comment]
调整了configs/ppyolo/_base_/optimizer_650e.yml中的base_lr：0.000625，epoch:52000, 收敛确实慢。
![image](https://user-images.githubusercontent.com/42796059/124697426-4af9e680-df19-11eb-8716-9522dd2895bf.png)
请问有什么办法加能快收敛速度吗？

**Comment by yghstill** [comment]
@chenxuezhao epoch不用调整，保持650即可，yolo系列模型收敛本身会比较慢，目前我们正在调优训练速度，同时近期将推出anchor free对标ppyolo-tiny的小模型，收敛更快，训练时长更短，可以关注下

**Comment by chenxuezhao** [comment]
@yghstill 有个问题我一直搞不清楚。是不是模型如果没有进行充分的训练（比如，只训练个2、3轮，而且训练的数据很少（100张图片）），这是即使用训练过的图片去predict,检测结果也会很差？

**Comment by yghstill** [comment]
@chenxuezhao 是的，在图片很少的情况下，训练前期模型收敛不是很好，需要多训一段时间再评测

**Comment by chenxuezhao** [comment]
@yghstill  worker_num从4改为了2，但随着训练时间的增长，训练主机的内存也一直在增长，最后内存全部被占用后，训练异常终止。训练主机内存32G。

**Comment by heavengate** [comment]
Paddle用的是2.1.0版本么，可以换成2.0.2版本试下，2.1.0上有个内存泄漏问题正在定位

**Comment by chenxuezhao** [comment]
用的是develop版本

**Comment by heavengate** [comment]
> 用的是develop版本

不是PaddleDetection版本，是Paddle版本

**Comment by chenxuezhao** [comment]
@heavengate 用2.0.2版本后报错：
![image](https://user-images.githubusercontent.com/42796059/124874230-10b44600-dffa-11eb-8891-3788b48de7e8.png)

**Comment by chenxuezhao** [comment]
paddleDetection回退到release2.0后可以了。
