### ISSUE TITLE
cascade系列模型能不能用PAN

### ISSUE THREAD

**Issue by ZiQiangXie** [PaddlePaddle/PaddleDetection#3637]
cascadercnn系列的模型，能不能把默认的FPN变成PAN，看到ppyolo里面用到了PAN，但是是针对yolo的PPYOLOPAN，好像不能直接用到其他模型里面吧，直接放进去好像会报错。

**Comment by liuhuiCNN** [comment]
你好，要把PAN应用到cascade rcnn，需要改动地方比较多，主要涉及特征融合的feature map的数量。您可以参考PPYOLO-PAN来改。

**Comment by ZiQiangXie** [comment]
好的谢谢！另外请问一下，百度在The 1st Tiny Object Detection Challenge这个比赛中取得第一名，请问有没有开源方案，谢谢！

**Comment by ZiQiangXie** [comment]
@liuhuiCNN 
好的谢谢！另外请问一下，百度在The 1st Tiny Object Detection Challenge这个比赛中取得第一名，请问有没有开源方案，谢谢！

**Comment by ZiQiangXie** [comment]
@liuhuiCNN 
好的，再问一下，百度在The 1st Tiny Object Detection Challenge这个比赛中取得第一名，请问有没有开源具体的方案？

**Comment by liuhuiCNN** [comment]
> 好的，再问一下，百度在The 1st Tiny Object Detection Challenge这个比赛中取得第一名，请问有没有开源具体的方案？

目前还未开源。
