### ISSUE TITLE
啥时候支持负样本？目前怎么去除误检呢？

### ISSUE THREAD

**Issue by TinyQi** [PaddlePaddle/PaddleDetection#3639]
rt
这个负样本训练在模型优化中起到关键的作用，竟然不支持？那么问题来了，如果遇到误检的话，我该怎么操作呢？

**Comment by TinyQi** [comment]
难道只有改源码这一条路了吗。。。。。

**Comment by cuesong** [comment]
竟然不支持？

**Comment by liuhuiCNN** [comment]
Faster RCNN中，可以在dataset里设置allow_empty=True。也可以考虑将检测出来的过再过一个分类器。
