### ISSUE TITLE
关于迁移学习的问题：

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#3641]
各位大神，咨询一个问题：已训练好的模型包括10个类别，现在其中有5个类又新增了部分数据准备训练，是将5新增的数据加入原来数据集，在原有拟合好模型上进行迁移训练? 还是直接训练新增数据？如果直接训练新增数据，将原来拟合好模型作为pretrain_weights，单类别数量不一样，切label的序号也与原来不一样，哪种带来的效果会好些？谢谢！

**Comment by liuhuiCNN** [comment]
你好，建议是将5新增的数据加入原来数据集进行训练。直接训练新增数据的话，数据分布与原来数据不同（5类 vs 10类）。

**Comment by jackie8310** [comment]
@liuhuiCNN ，谢谢！那如果将5新增的数据是加入原来训练，将原来拟合好模型作为pretrain_weights，如何控制再次训练不使得先前拟合好的模型性能不下降，同时还能学习到新加入数据的特征？除了减小learning rate，还有其它的trick吗？谢谢！

**Comment by liuhuiCNN** [comment]
> @liuhuiCNN ，谢谢！那如果将5新增的数据是加入原来训练，将原来拟合好模型作为pretrain_weights，如何控制再次训练不使得先前拟合好的模型性能不下降，同时还能学习到新加入数据的特征？除了减小learning rate，还有其它的trick吗？谢谢！

可以考虑给每个类别设置一个权重。

**Comment by jackie8310** [comment]
@liuhuiCNN ，加入的类别标签和原数据集中标签一样，设置类别权重是加大新加入数据的训练占比吗？可以指教在哪个文件位置进行设置？谢谢！

**Comment by liuhuiCNN** [comment]
> @liuhuiCNN ，加入的类别标签和原数据集中标签一样，设置类别权重是加大新加入数据的训练占比吗？可以指教在哪个文件位置进行设置？谢谢！

请参考：https://github.com/PaddlePaddle/PaddleDetection/issues/3641#issuecomment-876835835
