### ISSUE TITLE
FairMOT预测视频被killed

### ISSUE THREAD

**Issue by Flyingdog-Huang** [PaddlePaddle/PaddleDetection#3647]
CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608.pdparams --video_file=cam0.mp4  --save_videos
/home/hlx/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0709 10:04:05.135447 13556 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 10.1
W0709 10:04:05.158352 13556 device_context.cc:422] device: 0, cuDNN Version: 8.0.
[07/09 10:04:08] ppdet.utils.checkpoint INFO: Finish resuming model weights: /home/hlx/.cache/paddle/weights/fairmot_dla34_30e_1088x608.pdparams
[07/09 10:04:08] ppdet.engine.tracker INFO: Starting tracking cam0.mp4
[07/09 10:04:08] ppdet.data.source.mot INFO: Length of the video: 4377 frames
Killed

求问大神

**Comment by nemonameless** [comment]
建议切分成小视频 #3511

**Comment by Flyingdog-Huang** [comment]
> 建议切分成小视频 #3511

谢谢，已解决
