### ISSUE TITLE
Evaluation code is not running

### ISSUE THREAD

**Issue by LeDuySon** [PaddlePaddle/PaddleDetection#3648]
When i run eval.py to evaluate my dataset with ppyolov2_r50vd_dcn_365e_coco.yml config, its just stuck in Eval iter:0.
![Screenshot from 2021-07-09 09-07-01](https://user-images.githubusercontent.com/33374938/125012974-3f332f00-e095-11eb-837c-97c4b7312082.png)

but when i run with ppyolo_r50vd_dcn_1x_coco.yml config, it runs normally and i got bbox.json after the evaluation finished.
What happend with ppyolov2_r50vd_dcn_365e_coco.yml config? Can anyone explain?

**Comment by wangxinxin08** [comment]
It seem like that you want to eval the model defined by ppyolo_r50vd_dcn_1x_coco.yml but load the wrong weights, which you should use [ppyolo_r50vd_dcn_1x_cooco.pdparams](https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams)

**Comment by LeDuySon** [comment]
the image above its when i run ppyolov2_r50vd_dcn_365e_coco.yml so the pretrained model is ppyolov2_r50vd_dcn_365e_coco.pdparams. I think i load the right weights...

**Comment by wangxinxin08** [comment]
The INFO says that there are a lot of unmatched parameters, so obviously you load the wrong weights. Maybe you should upgrade PaddleDetection to release/2.1.1 and try it agian!
