### ISSUE TITLE
关于模型导出

### ISSUE THREAD

**Issue by Abris-087** [PaddlePaddle/PaddleDetection#3649]
你好，我初次使用Paddle Detection套件。我记得之前用老版本导出的模型都是__model__和__params__文件。昨天我使用ppdet2.0版本的tools/export_model.py导出的模型文件变得不一样了（.pdmodel和.pdiparams）。我想将预测模型部署到嵌入式设备上，请问如何才能生成上述两个文件？

**Comment by wangxinxin08** [comment]
你需要使用新的部署方式，可以参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy
