### ISSUE TITLE
训练自己的数据集时报错

### ISSUE THREAD

**Issue by xiaotantongxue123** [PaddlePaddle/PaddleDetection#3651]
/work/PaddleDetection$ python3 tools/train.py -c ~/work/cascade_mask_rcnn_dcnv2_se154_vd_fpn_gn_s1x.yml -o use_gpu=true --use_vdl=true --vdl_log_dir=~/work/vdl_dir/scalar
2021-07-09 03:58:34,311-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
W0709 03:58:35.785419 171978 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.0, Runtime API Version: 11.0
W0709 03:58:35.791921 171978 device_context.cc:422] device: 0, cuDNN Version: 7.6.
W0709 03:58:37.598073 171978 device_context.h:361] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.0, but CUDNN version in your machine is 7.6, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
/.local/lib/python3.6/site-packages/paddle/fluid/io.py:2358: UserWarning: This list is not set, Because of Paramerter not found in program. There are: mask_inter_feat_2_weights mask_inter_feat_1_offset mask_inter_feat_1_weights mask_inter_feat_3_weights conv5_mask_b mask_inter_feat_4_weights mask_fcn_logits_b mask_inter_feat_4_offset mask_fcn_logits_w mask_inter_feat_1_scale mask_inter_feat_2_scale conv5_mask_w mask_inter_feat_2_offset mask_inter_feat_3_offset mask_inter_feat_3_scale mask_inter_feat_4_scale
  format(" ".join(unused_para_list)))
2021-07-09 03:58:41,167-INFO: Dataset /work/work/work/coco is not valid for reason above, try searching /.cache/paddle/dataset or downloading dataset...
2021-07-09 03:58:41,167-INFO: Downloading train2017.zip from http://images.cocodataset.org/zips/train2017.zip
  2%|█▉                                                                                                                       | 295833/18883655 [09:50<2397:22:05,

**Comment by xiaotantongxue123** [comment]
使用的是csv2coco进行的数据转换，生成coco数据格式：
![image](https://user-images.githubusercontent.com/87167917/125037320-91407880-e0c6-11eb-8343-db09fc9dc84e.png)
![image](https://user-images.githubusercontent.com/87167917/125037349-9998b380-e0c6-11eb-996c-212c23e49a8e.png)
想问一下生成的coco数据为啥还是不能进行训练？

**Comment by wangxinxin08** [comment]
数据集路径没有正确配置，导致找不到coco数据集
