### ISSUE TITLE
训练时 加上--eval后报错

### ISSUE THREAD

**Issue by chenxuezhao** [PaddlePaddle/PaddleDetection#3653]
paddle-gpu2.0.2 + paddleDetection release2.0,训练ppyolo_tiny模型时，如果加上--eval会报错，报错信息如下：
![image](https://user-images.githubusercontent.com/42796059/125050648-bc31c900-e0d4-11eb-8f20-6180d8f8ea2c.png)

**Comment by wangxinxin08** [comment]
可以将Paddle版本更新到Paddle 2.1.1，将PaddleDetection版本更新到release/2.1试下

**Comment by chenxuezhao** [comment]
@wangxinxin08 
![image](https://user-images.githubusercontent.com/42796059/125055982-5c3e2100-e0da-11eb-89bf-3d210ea474da.png)

**Comment by chenxuezhao** [comment]
![image](https://user-images.githubusercontent.com/42796059/125057396-c2777380-e0db-11eb-823b-b048ea7d22c5.png)

**Comment by wangxinxin08** [comment]
pip install paddlepaddle-gpu==2.1，可以参考Paddle 官网安装文档https://www.paddlepaddle.org.cn/

**Comment by chenxuezhao** [comment]
![image](https://user-images.githubusercontent.com/42796059/125179082-703e6b80-e21d-11eb-8b56-eb8a904a7578.png)
paddle升级到2.1.1后，训练中报如上错误。

**Comment by wangxinxin08** [comment]
配置文件有修改过吗？看起来是你某些tensor不一致导致无法组batch

**Comment by chenxuezhao** [comment]
现在可以训练了（不加--eval），但训练出来的模型，不能用：
[https://github.com/PaddlePaddle/PaddleDetection/issues/3665](url)

**Comment by chenxuezhao** [comment]
训练过程中还会报错：
![image](https://user-images.githubusercontent.com/42796059/125263135-5abc6500-e335-11eb-8e76-c59ff9d6ed4a.png)
修改了如下的配置文件：
configs/ppyolo/ppyolo_tiny_650e_coco.yml：
![image](https://user-images.githubusercontent.com/42796059/125263302-7f184180-e335-11eb-8c6b-f6fce6d7568f.png)

configs/ppyolo/../datasets/coco_detection.yml：
![image](https://user-images.githubusercontent.com/42796059/125263758-e0d8ab80-e335-11eb-891f-274800038cb2.png)

configs/_base_/ppyolo_tiny.yml:
![image](https://user-images.githubusercontent.com/42796059/125264063-1e3d3900-e336-11eb-9cc8-31cd9cdc5a44.png)

configs/_base_/optimizer_650e.yml：
![image](https://user-images.githubusercontent.com/42796059/125264191-3a40da80-e336-11eb-8aa6-53fd864cb6f8.png)

configs/_base_/ppyolo_tiny_reader.yml:
![image](https://user-images.githubusercontent.com/42796059/125264641-9c99db00-e336-11eb-96ac-27ce8e91a101.png)

**Comment by chenxuezhao** [comment]
@wangxinxin08 请问，能帮忙看下这个问题吗？

**Comment by jerrywgz** [comment]
单独eval是否会有问题呢，另外能否提供下配置文件

**Comment by chenxuezhao** [comment]
@jerrywgz 训练的时候，不加--eval也报错。报错信息如下：
![image](https://user-images.githubusercontent.com/42796059/125641622-b6ac5124-f75a-41b1-9482-c69e936d27bd.png)
配置文件请看之前的截图，用红框框出来的地方，是我修改过的。

**Comment by chenxuezhao** [comment]
配置文件我也上传一下（coco/ppyolo_tiny）：
[ppyolo.zip](https://github.com/PaddlePaddle/PaddleDetection/files/6819551/ppyolo.zip)

**Comment by wangxinxin08** [comment]
你好，我看你把EvalDataset的image_dir改成了train2017，这样会导致无法加载图片

**Comment by chenxuezhao** [comment]
@wangxinxin08 你好，谢谢回复。我现在的问题是训练的时候即使不加 --eval，训练130-140个Epoch的时候，也会异常退出。错误信息请看之前的截图：
![image](https://user-images.githubusercontent.com/42796059/126939554-a4993a9b-96a9-40d3-83d6-da851beeb692.png)

**Comment by wangxinxin08** [comment]
那这个问题和加不加--eval应该是无关的，你使用的环境是什么？操作系统，PaddlePaddle和PaddleDetection版本等？

**Comment by chenxuezhao** [comment]
@wangxinxin Ubuntu 18.04.5 LTS / PaddlePaddle2.1.1 / PaddleDetection release 2.1

**Comment by wangxinxin08** [comment]
看起来是dataloader的问题，你可以尝试从断点处resume，这个问题会在之后的PaddlePaddle版本中修复
