### ISSUE TITLE
 C++调用python时，包含paddle库出现, 会出现首次 import paddle 弹出重复界面的情况

### ISSUE THREAD

**Issue by e-vist** [PaddlePaddle/PaddleDetection#3658]
in7电脑配置了paddlepaddle的GPU环境，实验了一个AI studio上的模型，用cmd运行起来没问题，之后就想用C++去调用python。

但是因为python程序中import了paddle库，引发了一些调用问题。就是以下这两句。

import paddle
import paddle.fluid as fluid
在.cpp文件中调用语句如下，编译没问题，运行有问题，问题语句在

PyImport_ImportModule()
源程序如下，包含在一个MFC的按钮中

PyObject* pFunc = NULL;
PyObject* Strin = NULL;
PyObject* pReturn = NULL;
//main命令行参数
int argc = 1;
wchar_t * argv[] = { L" " };
PySys_SetArgv(argc, argv);   //加入argv参数 否则出错
PyObject* pModule = PyImport_ImportModule("test_python");  //参数为Python脚本的文件名
如果不加第456行的话，当单机按钮之后，当前界面会重复地再弹出一个，关掉重复弹出的界面后，PyImport_ImportModule()函数会将pModule清空为NULL。

**Comment by qingqing01** [comment]
> 如果不加第456行的话

456行是什么呢？
