### ISSUE TITLE
FairMOT is not supported for exporting model now

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/PaddleDetection#3659]
[07/10 17:07:11] ppdet.utils.checkpoint INFO: Finish loading model weights: output/fairmot_dla34_30e_1088x608/model_final.pdparams
[07/10 17:07:11] ppdet.engine ERROR: Architecture: FairMOT is not supported for exporting model now

**Comment by lyuwenyu** [comment]
现在FairMOT还不支持导出   请关注下个版本

**Comment by nemonameless** [comment]
> [07/10 17:07:11] ppdet.utils.checkpoint INFO: Finish loading model weights: output/fairmot_dla34_30e_1088x608/model_final.pdparams
> [07/10 17:07:11] ppdet.engine ERROR: Architecture: FairMOT is not supported for exporting model now

develop分支已经支持，欢迎使用

**Comment by Wei-JL** [comment]
from collections import Sized
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
[07/12 11:13:58] ppdet.utils.checkpoint INFO: reid.classifier.weight not used, shape [128, 2653] unmatched with [128, 14455] in model.
[07/12 11:13:58] ppdet.utils.checkpoint INFO: reid.classifier.bias not used, shape [2653] unmatched with [14455] in model.
[07/12 11:13:58] ppdet.utils.checkpoint INFO: Finish loading model weights: output/fairmot_dla34_30e_1088x608/model_final.pdparams
[07/12 11:13:58] ppdet.engine ERROR: Architecture: FairMOT is not supported for exporting model now
重新拉取了，但是还是失败啊？

**Comment by lyuwenyu** [comment]
切换到develop分支了没？（git clone拉取的默认不是develop分支 ）

**Comment by Wei-JL** [comment]
> 切换到develop分支了没？（git clone拉取的默认不是develop分支 ）

不好意思，我没在本地，想问问在虚拟环境下如何切换分支

**Comment by Wei-JL** [comment]
就是在Ai studio上 怎么切换呀

**Comment by nemonameless** [comment]
> 就是在Ai studio上 怎么切换呀

git checkout develop或者git clone https://github.com/PaddlePaddle/PaddleDetection.git -b develop，然后python setup.py install 更新一下覆盖以前安装的paddledet。

**Comment by Wei-JL** [comment]
> > 就是在Ai studio上 怎么切换呀
> 
> git checkout develop或者git clone https://github.com/PaddlePaddle/PaddleDetection.git -b develop，然后python setup.py install 更新一下覆盖以前安装的paddledet。

多谢多谢

**Comment by Wei-JL** [comment]
> > 就是在Ai studio上 怎么切换呀
> 
> git checkout develop或者git clone https://github.com/PaddlePaddle/PaddleDetection.git -b develop，然后python setup.py install 更新一下覆盖以前安装的paddledet。

Installed /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg
Processing dependencies for paddledet==2.1.0
Searching for decord
Reading https://pypi.org/simple/decord/
Downloading https://files.pythonhosted.org/packages/11/79/936af42edf90a7bd4e41a6cac89c913d4b47fa48a26b042d5129a9242ee3/decord-0.6.0-py3-none-manylinux2010_x86_64.whl#sha256=51997f20be8958e23b7c4061ba45d0efcd86bffd5fe81c695d0befee0d442976

输入python setup.py install之后一直在运行，日志如上 卡死到那了

**Comment by nemonameless** [comment]
> > > 就是在Ai studio上 怎么切换呀
> > 
> > 
> > git checkout develop或者git clone https://github.com/PaddlePaddle/PaddleDetection.git -b develop，然后python setup.py install 更新一下覆盖以前安装的paddledet。
> 
> Installed /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg
> Processing dependencies for paddledet==2.1.0
> Searching for decord
> Reading https://pypi.org/simple/decord/
> Downloading https://files.pythonhosted.org/packages/11/79/936af42edf90a7bd4e41a6cac89c913d4b47fa48a26b042d5129a9242ee3/decord-0.6.0-py3-none-manylinux2010_x86_64.whl#sha256=51997f20be8958e23b7c4061ba45d0efcd86bffd5fe81c695d0befee0d442976
> 
> 输入python setup.py install之后一直在运行，日志如上 卡死到那了

手动安装 pip install decord，或者源码安装参考 https://github.com/dmlc/decord#installation

**Comment by Wei-JL** [comment]
代码：
!paddle_lite_opt \
    --model_file=output_inference/fairmot_dla34_30e_1088x608/model.pdmodel \
    --param_file=output_inference/fairmot_dla34_30e_1088x608/model.pdiparams \
    --optimize_out=output_inference/fairmot_dla34_30e_1088x608 \
    --optimize_out_type=naive_buffer \
    --valid_targets=arm 


Loading topology data from output_inference/fairmot_dla34_30e_1088x608/model.pdmodel
Loading params data from output_inference/fairmot_dla34_30e_1088x608/model.pdiparams
1. Model is successfully loaded!
[F  7/13 10:49: 0.744 ...island/Paddle-Lite/lite/core/mir/node.cc:32 picked_kernel] Check failed: !valid_kernels_.empty(): no kernel for depthwise_conv2d_transpose
Aborted (core dumped)

导出.np文件时报错

**Comment by nemonameless** [comment]
> 代码：
> !paddle_lite_opt
> --model_file=output_inference/fairmot_dla34_30e_1088x608/model.pdmodel
> --param_file=output_inference/fairmot_dla34_30e_1088x608/model.pdiparams
> --optimize_out=output_inference/fairmot_dla34_30e_1088x608
> --optimize_out_type=naive_buffer
> --valid_targets=arm
> 
> Loading topology data from output_inference/fairmot_dla34_30e_1088x608/model.pdmodel
> Loading params data from output_inference/fairmot_dla34_30e_1088x608/model.pdiparams
> 
> 1. Model is successfully loaded!
>    [F  7/13 10:49: 0.744 ...island/Paddle-Lite/lite/core/mir/node.cc:32 picked_kernel] Check failed: !valid_kernels_.empty(): no kernel for depthwise_conv2d_transpose
>    Aborted (core dumped)
> 
> 导出.np文件时报错

还不支持和paddlelite一起使用

**Comment by jerrywgz** [comment]
可以更新下paddlelite的版本，另外fairmot的后处理需要先自己加下，后面我们会补充lite的打通代码
