### ISSUE TITLE
solov2的输出模型格式

### ISSUE THREAD

**Issue by wflrz123** [PaddlePaddle/PaddleDetection#3662]
solov2 inference部署后的输出格式为什么不是pdiparams的类型

**Comment by wflrz123** [comment]
![QQ图片20210711181535](https://user-images.githubusercontent.com/48908943/125191304-46fcfa00-e274-11eb-975f-c23ffdb74a47.png)
是这种格式，能否转成pdiparams的格式呢

**Comment by wflrz123** [comment]
![QQ图片20210711181535](https://user-images.githubusercontent.com/48908943/125191304-46fcfa00-e274-11eb-975f-c23ffdb74a47.png)
是这种格式，能否转成pdiparams的格式呢

**Comment by nemonameless** [comment]
您截图里使用的是静态图版本，在默认github release/2.1分支或develop分支下是在static文件夹里了，暂时不能转成pdiparams的格式。更推荐使用动态图版本，git clone release/2.1分支或develop分支下来根目录默认就是使用动态图的。

**Comment by wflrz123** [comment]
我下载develop版本推理部署的时候会报错

**Comment by nemonameless** [comment]
> 我下载develop版本推理部署的时候会报错

什么报错呢？动态图版本release/2.1分支或develop我们都自测过可以的。

**Comment by XianrenYty** [comment]
我也是develop分支导出模型报错
```bash
File "/opt/conda/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/tensor_shape_transformer.py", line 188, in visit_For
        self._transform_var_shape_if_necessary(iter)
    File "/opt/conda/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/tensor_shape_transformer.py", line 225, in _transform_var_shape_if_necessary
        parent_node = wrapper_node.parent.node
    AttributeError: 'NoneType' object has no attribute 'parent'
```

**Comment by qingqing01** [comment]
@XianrenYty  我们自测develop分支，动态图模型导出没问题。请说明下有什么修改、PaddlePaddle版本号、运行命令吧
