### ISSUE TITLE
文本图片和非文本图片二分类

### ISSUE THREAD

**Issue by wanghaisheng** [PaddlePaddle/PaddleDetection#3664]
我的任务很简单，连续采集的视频流检测当前帧是否包含文字，不需要关心文字位置、文字内容，能回答有无即可，需要考虑多语种。
请教下，如果想基于目前paaddledetection已有的预训练模型，轻量级的实现最佳实践能指点下吗
看了下大规模实用目标检测模型的576类别中并没有文本这一类别

**Comment by qingqing01** [comment]
@wanghaisheng 

PaddleDetection提供的预训练模型是基于COCO、Object365、PascalVOC等物体检测识别的模型。
针对文本检测的话，您可以考虑采用 PaddleOCR的文字检测模型 https://github.com/PaddlePaddle/PaddleOCR

**Comment by wanghaisheng** [comment]
@qingqing01 如果要了解具体文字内容 ocr我是知道
我想请问下 车牌、公交站牌、书籍这些属于物体检测的类别吗 还是说压根就不属于
或者问题是目前的676类别中包含文本字符的类别有哪些 我的关注点可能偏了 字符在这些类别区分的特征中贡献度应该很低

**Comment by qingqing01** [comment]
目前的676类别是否包含 "车牌、公交站牌、书籍"，您可查看下  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/dataset/voc/generic_det_label_list_zh.txt  这里

有车辆拍照: https://github.com/PaddlePaddle/PaddleDetection/blob/d7383ad99c69e03f984ead52cc645d17f4729837/static/dataset/voc/generic_det_label_list_zh.txt#L14

书: https://github.com/PaddlePaddle/PaddleDetection/blob/d7383ad99c69e03f984ead52cc645d17f4729837/static/dataset/voc/generic_det_label_list_zh.txt#L122
