### ISSUE TITLE
训练的模型predict时报错

### ISSUE THREAD

**Issue by chenxuezhao** [PaddlePaddle/PaddleDetection#3665]
paddlepaddle-gpu=2.1.1,paddleDectection=release2.1,用自己的数据训练ppyolo_tiny模型时，修改了ppyolo_tiny.yml和ppyolo_tiny_reader.yml的anchors和size值，修改的地方如下：
![image](https://user-images.githubusercontent.com/42796059/125219315-304bb700-e2f7-11eb-91bc-20c493ec1a1d.png)
![image](https://user-images.githubusercontent.com/42796059/125219345-36419800-e2f7-11eb-8802-44ced809e2b1.png)
用训练的模型，predict一张训练用的图片时，报了如下错误：
![image](https://user-images.githubusercontent.com/42796059/125219460-5b360b00-e2f7-11eb-9f4d-366991a5b994.png)

**Comment by heavengate** [comment]
你好，`Resize:  {keep_ratio: False}` 里 `keep_ratio`需要配置为False，是将图片resize成416*416的，不是保持原图片宽高比resize
