### ISSUE TITLE
export_model保存的模型删除NMS后，模型的输出是什么含义？

### ISSUE THREAD

**Issue by raymondchu-z** [PaddlePaddle/PaddleDetection#3666]
> save_infer_model/scale_0.tmp_1
name: save_infer_model/scale_0.tmp_1
type: float32[1,25200,4]

> save_infer_model/scale_1.tmp_1
name: save_infer_model/scale_1.tmp_1
type: float32[1,7,25200]

我的理解是：
[1,25200,4]是表示对于1张图片，预测出了25200个框，每个框的坐标是xyxy；
[1,7,25200]是表示对于1张图片，对于7个类别，这25200个预测框针对每个类别都有一个置信度分数。
是这样吗？
25200是怎么来的？

**Comment by qingqing01** [comment]
您的理解没错，25200是推理得到的所有bbox的个数。

**Comment by raymondchu-z** [comment]
@qingqing01 好的谢谢。25200是怎么来的？或者换个问法，修改配置或代码的哪些参数会影响这个25200？和输入尺寸有关吗？

**Comment by qingqing01** [comment]
如果是YOLO系列模型的话，和anchor数量、图片大小都有关系，可以参考 https://github.com/PaddlePaddle/PaddleDetection/issues/1356
