### ISSUE TITLE
模型导出onnx后转openvino ir模型报错

### ISSUE THREAD

**Issue by 15162162323** [PaddlePaddle/PaddleDetection#3667]
**模型转ir格式报错**
**另外下面这段说明中的参数定义在转openvino时如何设置呢？** @liuhuiCNN @wangxinxin08 
<html>
<body>
<h3 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 24px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">导出模输入输出说明</h3><ul style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; padding-left: 2em; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 16px;">输入变量以及输入形状如下：</p>

输入名称 | 输入形状 | 表示含义
-- | -- | --
image | [None, 3, H, W] | 输入网络的图像，None表示batch维度，如果输入图像大小为变长，则H,W为None
im_shape | [None, 2] | 图像经过resize后的大小，表示为H,W, None表示batch维度
scale_factor | [None, 2] | 输入图像大小比真实图像大小，表示为scale_y, scale_x

</li></ul>
</body>
</html>

```
2021-07-11 22:51:21.427312: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
[ ERROR ]  Shape [-1  2] is not fully defined for output 0 of "scale_factor". Use --input_shape with positive integers to override model input shapes.
[ ERROR ]  Cannot infer shapes or values for node "scale_factor".
[ ERROR ]  Not all output shapes were inferred or fully defined for node "scale_factor". 
 For more information please refer to Model Optimizer FAQ, question #40. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=40#question-40)
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function Parameter.infer at 0x7f3dc0dcc620>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "scale_factor" node. 
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?
```

**Comment by qingqing01** [comment]
您ONNX转OpenVINO IR参考文档发下？

**Comment by 15162162323** [comment]
> 您ONNX转OpenVINO IR参考文档发下？
@qingqing01 

1.参考的这个介绍paddle转onnx，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_ONNX_MODEL.md
`paddle2onnx --model_dir /project/train/models/inference_model/yolov3_darknet53_270e_coco \
            --model_filename model.pdmodel \
            --params_filename model.pdiparams \
            --opset_version 11 \
            --save_file /project/train/models/inference_model/onnx/model.onnx \
            --enable_onnx_checker True`
2.onnx转openvino参考的官网介绍https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Converting_Model_General.html 
`python mo_onnx.py \
--input_model /project/train/models/inference_model/onnx/model.onnx \
--output_dir /project/train/models/inference_model/openvino \
--input_shape [3,608,608] --log_level DEBUG`
3.我查看转换后的onnx模型结构 inputs参数为这三个 im_shape  image  scale_factor，和上面介绍的一样
4.最后，我看网上介绍说paddle已经支持openvnio的方式，但是目前还没有找到任何说明文档，我也没有搞懂怎么转换此类模型，如何声明参数~。~

**Comment by jiangjiajun** [comment]
openvino在做推理时，需要每个节点的shape都是固定的，因此我们在转openvino进行部署时需要一些trick来解决。

当前主要原因是yolov3模型中最后一个NMS的输入shape虽然是固定的，但是输出的box数量是不确定的，因此会导致转OpenVINO IR时失败，你可以在导出yolov3模型时，去掉最后的NMS来解决这个问题

**Comment by 15162162323** [comment]
@jiangjiajun 
> openvino在做推理时，需要每个节点的shape都是固定的，因此我们在转openvino进行部署时需要一些trick来解决。
> 
> 当前主要原因是yolov3模型中最后一个NMS的输入shape虽然是固定的，但是输出的box数量是不确定的，因此会导致转OpenVINO IR时失败，你可以在导出yolov3模型时，去掉最后的NMS来解决这个问题

您的意思是需要去掉yml中的 nms吗？我使用的是yolov3_darknet53_270e_coco 这个配置，export_model.py导出模型，然后pd-->onnx-->ir，最后还是有同样的报错
`[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.front.user_data_repack.UserDataRepack'>): Original placeholders: 'im_shape, image, scale_factor'. Freezing was requested for ''. --input_shape was provided without --input. Can not deduce which node shape to override`

**Comment by jiangjiajun** [comment]
1. 导出不含nms的yolov3模型
> 这里参照上面所说修改yaml文件重新导出即可
2. 安装Paddle2ONNX
> 卸载原始的paddle2onnx，安装github上代码（刚提了PR解决clip问题)
> ```
> pip uninstall paddle2onnx
> git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
> cd Paddle2ONNX
> git checkout release/0.7
> python setup.py install
> ```
3. 转为ONNX格式
> 正常转换即可
> `paddle2onnx --model_dir=. --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file model.onnx`
4. 转为OpenVINO IR，注意指定shape信息
> `mo.py --framework onnx --input_model model.onnx --model_name yolov3 --output_dir ov_model --input_shape "[1,3,608,608],[1,2],[1,2]" --input "image,im_shape,scale_factor"`

**Comment by 15162162323** [comment]
多谢大佬，此方法实测有效，悟了！

**Comment by jiangjiajun** [comment]
OpenVINO目前已经可以通过ONNX支持YOLOv3系列模型的部署，参考此文档  https://github.com/PaddlePaddle/Paddle2ONNX/blob/release/0.9/experimental/openvino_ppdet_cn.md
