### ISSUE TITLE
OOM问题，多尺度训练没有问题，但是测试时采用大尺度会报错。

### ISSUE THREAD

**Issue by ZiQiangXie** [PaddlePaddle/PaddleDetection#3672]
CascadeRCNN模型，训练时采用了7个尺度进行多尺度训练，训练完成后，采用最大的前两个尺度进行验证集的评估，都会出现out of memory的问题，采用中间尺度也几乎将gpu占满；
环境：Ubuntu18.04，1080ti单卡，paddle2.0.1，没有同时跑其他模型，训练没有使用fp16；
训练过多个模型，目前发现两个模型出现问题，采用中间尺度生成的结果是对的，而且效果较好，所以网络结构和训练都应该没有问题。

**Comment by heavengate** [comment]
具体用的哪个模型哪个尺度呢，可以把`EvalReader`里的batch size调小一点试下

**Comment by ZiQiangXie** [comment]
模型自己做了一点点的修改，下面是配置文件的一些信息。


_BASE_: [
  'cascade_rcnn_dcn_r50_fpn_1x_coco.yml',
]
pretrain_weights: pretrained_weights/ResNeXt152_64x4d_pretrained.pdparams
weights: output/cascade_rcnn_dcn_x152_vd_64x4d_fpn_1x_coco/model_final

ResNet:
  depth: 152
  groups: 64
  base_width: 4
  variant: d
  norm_type: bn
  freeze_at: -1
  return_idx: [0,1,2,3]
  num_stages: 4
  dcn_v2_stages: [1,2,3]

RPNHead:
  anchor_generator:
    aspect_ratios: [0.5, 1.0, 2.0]
    anchor_sizes: [[8], [16], [32], [48], [64], [96], [128]]
    strides: [4, 8, 16, 32, 64]
  rpn_target_assign:
    batch_size_per_im: 256
    fg_fraction: 0.5
    negative_overlap: 0.3
    positive_overlap: 0.6
    use_random: True
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 2000
    post_nms_top_n: 2000
    topk_after_collect: True
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 1000
    post_nms_top_n: 1000

worker_num: 1
TrainReader:
  sample_transforms:
  - Decode: {}
  - RandomResize: {target_size: [[448, 864], [480, 960], [512, 960], [544, 1024], [576, 1280], [608, 1280]], interp: 2, keep_ratio: True}
  - RandomFlip: {prob: 0.5}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32, pad_gt: true}
  batch_size: 1
  shuffle: true
  drop_last: true

EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [544, 1024], keep_ratio: True}
  - RandomFlip: {prob: 1.0}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32, pad_gt: false}
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false

**Comment by heavengate** [comment]
cascade模型比较大，如果采用大的输入尺寸的话对显存要求比较高，看报错是out of memory的话应该是你机器上线显存不够，可以尝试用小一点的batch size或者输入尺寸，或者可以尝试用个小一点的模型
