### ISSUE TITLE
cascade-rcnn什么时候支持多batch_size推理？

### ISSUE THREAD

**Issue by wddwzwhhxx** [PaddlePaddle/PaddleDetection#3674]
# rpn proposals
        rpn_rois = self.rpn_head.get_proposals(body_feats, im_info, mode=mode)

        if mode == 'train':
            #fluid.layers.Print(gt_bbox)
            #fluid.layers.Print(is_crowd)
            rpn_loss = self.rpn_head.get_loss(im_info, gt_bbox, is_crowd)
        else:
            if self.rpn_only:
                im_scale = fluid.layers.slice(
                    im_info, [1], starts=[2], ends=[3])
                im_scale = fluid.layers.sequence_expand(im_scale, rpn_rois)
                rois = rpn_rois / im_scale
                return {'proposal': rois}

看上去目前并不能支持多卡推理，在导出模型后尝试加上多batch_size，结果与batch_size为1的时候有diff

**Comment by heavengate** [comment]
你好，cascade rcnn的batch size > 1推理还在验证，faster rcnn和mask rcnn用最新的develop是支持的
