### ISSUE TITLE
目标检测 Serving http响应问题

### ISSUE THREAD

**Issue by lizhangling1** [PaddlePaddle/PaddleDetection#3675]
给予PaddleDetection 进行目标检测训练，之后进行serving模型部署。

发起http请求：
curl -H "Content-Type:application/json" -X POST -d '{"feed":[{"image":  "/Users/lizhangling/Downloads/beizi608.jpeg"}], "fetch":["save_infer_model/scale_0.tmp_1"]}' http://127.0.0.1:9292/detection/prediction
返回：
{"result":"cannot reshape array of size 1 into shape (3,608,608)"}

请问该如何解决？

**Comment by liuhuiCNN** [comment]
你好，这里需要feed的是图像内容数据，并不是图像文件。您可以参考下deploy下代码或者PaddleServing的示例。
