### ISSUE TITLE
ttfnet推理出现问题

### ISSUE THREAD

**Issue by zsffuture** [PaddlePaddle/PaddleDetection#3677]
本人没有训练直接使用官方提供的模型进行测试，发现输出存在问题，检测目标框不正确：
1.输入的命令：
python tools/infer.py -c configs/ttfnet/ttfnet_darknet53_1x_coco.yml --infer_dir E:\yc\image2 -o weights=configs/ttfnet/pafnet_10x_coco.pdparams  --draw_threshold 0.2 --output_dir E:\yc/ttt
2.经过测试使用yolov3的模型测试可以通过
3.ttfnet 的检测结果如下，明明有车和人检测不出来：
![image](https://user-images.githubusercontent.com/39027951/125419616-c271f02e-1940-4c57-9331-0ecd02ecbba2.png)

**Comment by nemonameless** [comment]
你的运行命令-c config和-o weights不一致

**Comment by heavengate** [comment]
你好，你用的`ttfnet_darknet53_1x_coco`的配置文件但是用的`pafnet_10x_coco.pdparams`的权重，权重需要与配置文件对应
