### ISSUE TITLE
ppyolo v2训练时加载完参数就退出

### ISSUE THREAD

**Issue by wang-hao-feng** [PaddlePaddle/PaddleDetection#3678]
使用ppyolo v2训练时，加载完resnet的参数后，报提示

> WARNING: Detect dataset only contains single fileds, return format changed since Paddle 2.1. In Paddle <= 2.0, DataLoader add a list surround output data(e.g. return [data]), and in Paddle >= 2.1, DataLoader return the single filed directly (e.g. return data).

输出完几秒后程序退出

现在定位到退出发生在ppdet/engine/trainer.py第307行处的语句
`
outputs = model(data)
`

**Comment by nemonameless** [comment]
建议使用Paddle 2.1，PaddleDetection 2.1或develop分支

**Comment by wang-hao-feng** [comment]
> 建议使用Paddle 2.1，PaddleDetection 2.1或develop分支

使用的就是2.1版本

**Comment by heavengate** [comment]
`outputs = model(data)`
是跑到这一行退出了？把data打印出来看下呢

**Comment by wang-hao-feng** [comment]
> `outputs = model(data)`
> 是跑到这一行退出了？把data打印出来看下呢

https://paste.ubuntu.com/p/TCRSNw2GhZ/ 
（data）
进入model函数后都是在跑forward的时候退出，昨天调出来的

**Comment by MatchX** [comment]
你查看你的scipy版本如果高于1.3.3 可以尝试安装1.3.3版本
