### ISSUE TITLE
paddleDetection在训练时出现Out of memory error on GPU 0. Cannot allocate 39.062744MB memory on GPU 0, 7.900513GB memory has been allocated and available memory is only 29.437500MB.

### ISSUE THREAD

**Issue by xiaotantongxue123** [PaddlePaddle/PaddleDetection#3679]
loading annotations into memory...
Done (t=0.10s)
creating index...
index created!
2021-07-13 16:34:21,130-INFO: iter: 0, lr: 0.000012, 'loss_cls_0': '1.152286', 'loss_loc_0': '0.000001', 'loss_cls_1': '0.545614', 'loss_loc_1': '0.000001', 'loss_cls_2': '0.289684', 'loss_loc_2': '0.000000', 'loss_rpn_cls': '0.694718', 'loss_rpn_bbox': '0.003722', 'loss': '2.686026', eta: 0:00:00, batch_cost: 0.00003 sec, ips: 38479.85321 images/sec
W0713 16:34:31.576385   221 operator.cc:242] roi_align raises an exception paddle::memory::allocation::BadAlloc, ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 48.473877MB memory on GPU 0, 7.900513GB memory has been allocated and available memory is only 29.437500MB.
Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
W0713 16:34:31.684660   219 operator.cc:242] conv2d_grad raises an exception paddle::memory::allocation::BadAlloc, ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 39.062744MB memory on GPU 0, 7.900513GB memory has been allocated and available memory is only 29.437500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
W0713 16:34:31.691952   222 operator.cc:242] conv2d_grad raises an exception paddle::memory::allocation::BadAlloc, ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 39.062744MB memory on GPU 0, 7.900513GB memory has been allocated and available memory is only 29.437500MB.

**Comment by nemonameless** [comment]
先检查0号卡是否已被其他程序任务占满，若显卡不够用可以减小batchsize或减小输入图尺寸，一般在configs/xxx/_base_/xxx_reader.yml里的TrainReader修改 RandomResize的target_size 以及batch_size等相关数值

**Comment by xiaotantongxue123** [comment]
batch_size改为1，target_size下面为三个数：- 640 - 800 - 1024改为- 512 - 640  - 800，查了显存没有被占用，出现错误：
RuntimeError: ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 49.000244MB memory on GPU 0, 7.916138GB memory has been allocated and available memory is only 13.437500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)

terminate called without an active exception


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1626171553 (unix time) try "date -d @1626171553" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e80000052e) received by PID 1326 (TID 0x7f34bd356700) from PID 1326 ***]

Segmentation fault


> 先检查0号卡是否已被其他程序任务占满，若显卡不够用可以减小batchsize或减小输入图尺寸，一般在configs/xxx/_base_/xxx_reader.yml里的TrainReader修改 RandomResize的target_size 以及batch_size等相关数值

**Comment by heavengate** [comment]
这个是显存不够的报错，可以看看卡上是不是有其他任务，或者调小`TrainReader.batch_size`试下

**Comment by xiaotantongxue123** [comment]
> 这个是显存不够的报错，可以看看卡上是不是有其他任务，或者调小`TrainReader.batch_size`试下
查看卡上没有其他任务，batch_size=1，出现错误：
index created!
2021-07-14 11:41:08,006-INFO: iter: 0, lr: 0.000012, 'loss_cls_0': '1.105609', 'loss_loc_0': '0.000000', 'loss_cls_1': '0.540752', 'loss_loc_1': '0.000000', 'loss_cls_2': '0.235018', 'loss_loc_2': '0.000000', 'loss_rpn_cls': '0.701424', 'loss_rpn_bbox': '0.009759', 'loss': '2.592563', eta: 0:00:00, batch_cost: 0.00003 sec, ips: 38479.85321 images/sec
W0714 11:41:26.591893  2411 operator.cc:242] conv2d raises an exception paddle::memory::allocation::BadAlloc, ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 297.000244MB memory on GPU 0, 7.693481GB memory has been allocated and available memory is only 241.437500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 270, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/home/simpleai/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 719, in reraise
    raise value
  File "/home/simpleai/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/home/simpleai/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1252, in _run_impl
    return_merged=return_merged)
  File "/home/simpleai/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 913, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
RuntimeError: ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 297.000244MB memory on GPU 0, 7.693481GB memory has been allocated and available memory is only 241.437500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)

terminate called without an active exception


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1626234087 (unix time) try "date -d @1626234087" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800000937) received by PID 2359 (TID 0x7fb7eb17d700) from PID 2359 ***]

Aborted

**Comment by qingqing01** [comment]
@xiaotantongxue123 

那您机器显存是多少？ 是哪个模型？

**Comment by heavengate** [comment]
cascade系列模型显存需求比较大，训练一般使用12G以上的显存，如果你的卡上显存不够的可以试下显存需求少一些的模型，比如faster rcnn之类的
