### ISSUE TITLE
训练后测试单张图片报错

### ISSUE THREAD

**Issue by felixgalaxy** [PaddlePaddle/PaddleDetection#368]
你好，我用paddle训练自己的数据集，改的configs中的yml文件，最后训练的时候每次保存的三个结果没在一个文件夹，请问我测试选个哪个结果呢？
下面是我改的yml截图和训练后output的结果图
测试的时候我没指定结果权重，但是总是出现这样的错误，求帮忙解决
![2](https://user-images.githubusercontent.com/49911457/77217010-ef57ee00-6b59-11ea-8edc-47b936863d6a.png)
![3](https://user-images.githubusercontent.com/49911457/77217011-f4b53880-6b59-11ea-9065-f20ac8dd2f41.png)
![1](https://user-images.githubusercontent.com/49911457/77217018-fbdc4680-6b59-11ea-92a2-878840478910.png)

**Comment by heavengate** [comment]
看着是训练和评估的时候`dataset`里`with_background`参数设置不一致，可以检查看下

**Comment by heavengate** [comment]
1. 看你使用的数`fruit`的配置文件，用的是voc的数据集，两者配置有区别的，建议使用匹配的配置文件和数据集
2. 类别数读入为0，请确认数据集目录下`label_list.txt`文件是否正确生成，如果是使用数据集目录提供的脚本下载或者是自动下载的数据集，`label_list.txt`文件是能正确生成的
