### ISSUE TITLE
paddle detection 里的ppdet/modeling/reid怎么用

### ISSUE THREAD

**Issue by Mr-ind1fferent** [PaddlePaddle/PaddleDetection#3680]
如题

**Comment by nemonameless** [comment]
> 如题

这个是作为多目标跟踪的reid部分或者类似reid功能的部分的代码。fairmot_embedding_head.py和jde_embedding_head.py顾名思义是fairmot jde的和检测并行的reid分支，pyramidal_embedding.py是deepsort的，采用PCBPyramid (PCB + Pyramidal)，resnet.py是pyramidal_embedding的主干网络，和检测的backbone略有不同，PCBPyramid ResNet101是paddleclas训好的精度极高的行人reid模型，所以可以直接用于deepsort的行人跟踪。

**Comment by Mr-ind1fferent** [comment]
> > 如题
> 
> 
> 
> 这个是作为多目标跟踪的reid部分或者类似reid功能的部分的代码。fairmot_embedding_head.py和jde_embedding_head.py顾名思义是fairmot jde的和检测并行的reid分支，pyramidal_embedding.py是deepsort的，采用PCBPyramid (PCB + Pyramidal)，resnet.py是pyramidal_embedding的主干网络，和检测的backbone略有不同，PCBPyramid ResNet101是paddleclas训好的精度极高的行人reid模型，所以可以直接用于deepsort的行人跟踪。

该如何使用pyramidal这个py文件实现行人reid

**Comment by nemonameless** [comment]
> > > 如题
> > 
> > 
> > 这个是作为多目标跟踪的reid部分或者类似reid功能的部分的代码。fairmot_embedding_head.py和jde_embedding_head.py顾名思义是fairmot jde的和检测并行的reid分支，pyramidal_embedding.py是deepsort的，采用PCBPyramid (PCB + Pyramidal)，resnet.py是pyramidal_embedding的主干网络，和检测的backbone略有不同，PCBPyramid ResNet101是paddleclas训好的精度极高的行人reid模型，所以可以直接用于deepsort的行人跟踪。
> 
> 该如何使用pyramidal这个py文件实现行人reid

这部分是网络主体。可以参考 PaddleClas的reid模型，比如https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/application/vehicle_recognition.md

**Comment by Mr-ind1fferent** [comment]
> > > > 如题
> 
> > > 
> 
> > > 
> 
> > > 这个是作为多目标跟踪的reid部分或者类似reid功能的部分的代码。fairmot_embedding_head.py和jde_embedding_head.py顾名思义是fairmot jde的和检测并行的reid分支，pyramidal_embedding.py是deepsort的，采用PCBPyramid (PCB + Pyramidal)，resnet.py是pyramidal_embedding的主干网络，和检测的backbone略有不同，PCBPyramid ResNet101是paddleclas训好的精度极高的行人reid模型，所以可以直接用于deepsort的行人跟踪。
> 
> > 
> 
> > 该如何使用pyramidal这个py文件实现行人reid
> 
> 
> 
> 这部分是网络主体。可以参考 PaddleClas的reid模型，比如https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/application/vehicle_recognition.md 

可以更改为清华大学的行人reid数据集完成行人reid吗

**Comment by nemonameless** [comment]
做reid的思路是基本统一的，换数据集从头训应该是可以的。

**Comment by Mr-ind1fferent** [comment]
有具体的readme介绍如何训练吗，没有找到> > > > > > 如题
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 这个是作为多目标跟踪的reid部分或者类似reid功能的部分的代码。fairmot_embedding_head.py和jde_embedding_head.py顾名思义是fairmot jde的和检测并行的reid分支，pyramidal_embedding.py是deepsort的，采用PCBPyramid (PCB + Pyramidal)，resnet.py是pyramidal_embedding的主干网络，和检测的backbone略有不同，PCBPyramid ResNet101是paddleclas训好的精度极高的行人reid模型，所以可以直接用于deepsort的行人跟踪。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 该如何使用pyramidal这个py文件实现行人reid
> 
> > > 
> 
> > > 
> 
> > > 这部分是网络主体。可以参考 PaddleClas的reid模型，比如https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/application/vehicle_recognition.md
> 
> > 
> 
> > 可以更改为清华大学的行人reid数据集完成行人reid吗
> 
> 
> 
> 做reid的思路是基本统一的，换数据集从头训应该是可以的。

**Comment by Mr-ind1fferent** [comment]
有具体的readme介绍吗，如何训练

**Comment by nemonameless** [comment]
请参照PaddleClas 去训练reid。
以pplcent为例：

https://github.com/PaddlePaddle/PaddleClas/blob/develop/ppcls/configs/GeneralRecognition/GeneralRecognition_PPLCNet_x2_5.yaml#L26    可以看这个配置文件，本质上ppdet里的reid是从clas移植过去的，就是backbone+neck复制过去，neck就是在backbone的特征flatten后再加一层FC变到128或512等维度

原版pplcnet网络在这里
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/ppcls/arch/backbone/legendary_models/pp_lcnet.py    paddleclas

ppdet里的pplcnet reid在这里
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/reid/pplcnet_embedding.py
