### ISSUE TITLE
PaddleServing 运行出错

### ISSUE THREAD

**Issue by blackxer** [PaddlePaddle/PaddleDetection#3682]
问题：
按官方文档导出模型：python tools/export_model.py -c configs/yolov3/yolov3_darknet53_270e_coco.yml -o weights=weights/yolov3_darknet53_270e_coco.pdparams --export_serving_model=True
开启server服务，运行客户端测试代码
python ../../deploy/serving/test_client.py ../../demo/000000014439.jpg
服务端报错：
Error Message Summary:
----------------------
InvalidArgumentError: The Tensor in the elementwise_div Op's Input Variable Y(scale_factor) is not initialized.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1644)
  [operator < elementwise_div > error]

临时解决方法：
查看 serving_client_conf.prototxt 文件，内容为
feed_var {
  name: "im_shape"
  alias_name: "im_shape"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
  shape: 608
  shape: 608
}
feed_var {
  name: "scale_factor"
  alias_name: "scale_factor"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
其中第三个 feed_var 为 scale_factor
修改 test_client.py 文件中的 fetch_map 变量，添加  "scale_factor" 输入参数
fetch_map = client.predict(
    feed={
        "image": im,
        "im_shape": np.array(list(im.shape[1:])),
        "scale_factor": np.array([1,1])  # 添加的 scale_factor 参数
    },
    fetch=["save_infer_model/scale_0.tmp_1"])
程序可以正常运行，但检测结果和paddleDetection模型检测结果不一致。
希望官方示例可以更新对 各输入参数 的配置说明。
谢谢！

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/serving 可以先参考这里的文档对相应文件做下修改

**Comment by liuhuiCNN** [comment]
看您使用代码跟deploy/serving/test_client.py不太一样，请参考这里：https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/deploy/serving/test_client.py
