### ISSUE TITLE
关于oidv5模型相关的一些问题

### ISSUE THREAD

**Issue by ziyanyang** [PaddlePaddle/PaddleDetection#3683]
你好！
我尝试着用一部分google open image dataset来train这个模型
（https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/configs/oidv5/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.yml)
关于configuration file有几点疑问：
1.在Train Reader中：
  dataset:
      !COCODataSet
      dataset_dir: dataset/oid
      anno_path: train.json
      image_dir: train
是不是意味着你们在train的时候先把数据集转换成coco的形式然后做的training？
2.metric: OID
现在的版本是否不支持直接对oid数据进行evaluation？是否可以把这个参数改成COCO，把validation data也转换成COCO格式然后做evaluation？你们在train原本的oidv5模型的时候是不是没有一边train一边做evaluation呢？

谢谢！

**Comment by jerrywgz** [comment]
是的，这里是会对数据集格式提前进行转换，暂时应该是需要把oid数据的metric改成COCO做evaluation

**Comment by ziyanyang** [comment]
> 是的，这里是会对数据集格式提前进行转换，暂时应该是需要把oid数据的metric改成COCO做evaluation

好的，明白了。
还有一个问题是关于参数num_classes，这个OIDV5的num_classes设置的是501，是不是就是原来的500个加上一个background？那么with_background这个参数（这个configuration里没出现）默认值是不是True？

**Comment by jerrywgz** [comment]
在静态图下，with_background默认为True, 同时num_classes也还是需要设置为501
