### ISSUE TITLE
ppyolo tiny转onnx后，Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))

### ISSUE THREAD

**Issue by zyl112334** [PaddlePaddle/PaddleDetection#3698]
转为onnx后，查看onnx模型的图，输入如下：
im_shape
name: im_shape
type: float32[-1,2]
image
name: image
type: float32[-1,3,608,608]
scale_factor
name: scale_factor
type: float32[-1,2]

代码：
img = cv2.resize(img, (608, 608))
img = img.transpose((2, 0, 1))
img = np.expand_dims(img, axis=0)
input_dict = {"image":img, "im_shape":np.array([[608, 608]],dtype=np.float32), "scale_factor": np.array([[1, 1]],dtype=np.float32)}

运行错误信息：
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))

**Comment by qingqing01** [comment]
@zyl112334 

img看起来dtyle是uint8, 需要float32类型。您需要cv2.resize之后，将类型转换为float32。
