### ISSUE TITLE
想把ppyolo训练的模型部署在华为海思的开发板上，但是海思的nnie引擎不支持DCN可变形卷积，请问如何用常规卷积进行替代

### ISSUE THREAD

**Issue by yuanwei0908** [PaddlePaddle/PaddleDetection#3702]

**Comment by raymondchu-z** [comment]
配置里面dcn
> ResNet:
  depth: 50
  variant: d
  return_idx: [1, 2, 3]
  dcn_v2_stages: [-1]

dcn_v2_stages: [-1]这个设-1就行

**Comment by nemonameless** [comment]
dcn_v2_stages: [-1]或者这一行注释即可
