### ISSUE TITLE
训练ppyolo完后显存没有释放应该怎么解决

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#3703]
训练ppyolo完后显存没有释放应该怎么解决，也没有找到对应的id
<img width="599" alt="截屏2021-07-15 下午7 44 53" src="https://user-images.githubusercontent.com/87430649/125782798-694cb764-8642-4106-94b5-183c7bcaa1b9.png">

**Comment by lyuwenyu** [comment]
可以用 `ps aux` 查看下
