### ISSUE TITLE
单卡可以训练，多卡训练不了如何解决

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#3704]
<img width="1032" alt="截屏2021-07-15 下午8 19 26" src="https://user-images.githubusercontent.com/87430649/125786995-4dfd55db-a492-4faa-b093-c4c0c8316319.png">
<img width="1309" alt="截屏2021-07-15 下午8 17 16" src="https://user-images.githubusercontent.com/87430649/125787005-6060a5d6-6d45-42db-81f7-cea6d003be47.png">

**Comment by lyuwenyu** [comment]
可以在指定的`--log_dir`目录里查看`workerlog.1`具体的报错信息
