### ISSUE TITLE
YOLOV3训练的文本检测模型，经常出现偏差

### ISSUE THREAD

**Issue by Andy546** [PaddlePaddle/PaddleDetection#3705]
【黄埔学院】
使用yolov3_mobilenet_v1.yml配置文件进行训练的模型，场景为检测发票的特定信息，如发票代码、发票号码。
在数据标注时只标注了发票代码、发票号码，但是测试时发现检测框经常出现偏移，框出其他区域或者少框一部分信息，如下图，有没有大佬遇到过这种情况？求助
![20190509133722769](https://user-images.githubusercontent.com/10570127/125886262-4c23cea7-6f01-43f9-aeb3-ad775cc35a71.jpg)

**Comment by liuhuiCNN** [comment]
不太明白您的问题，可以再详细说明一下吗？
如果预测结果错误，（1）先用官方模型看下预测代码是否正常；（2）如果预测代码正常，那就是模型没有训练好。

**Comment by Andy546** [comment]
> 不太明白您的问题，可以再详细说明一下吗？
> 如果预测结果错误，（1）先用官方模型看下预测代码是否正常；（2）如果预测代码正常，那就是模型没有训练好。

首先代码预测正常，模型没训练好实在是太宽泛了...请问下如果YOLO做这种文本检测模型文本标注、模型训练有什么技巧吗？

**Comment by liuhuiCNN** [comment]
> > 不太明白您的问题，可以再详细说明一下吗？
> > 如果预测结果错误，（1）先用官方模型看下预测代码是否正常；（2）如果预测代码正常，那就是模型没有训练好。
> 
> 首先代码预测正常，模型没训练好实在是太宽泛了...请问下如果YOLO做这种文本检测模型文本标注、模型训练有什么技巧吗？

试试设置anchor，请参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/tools/anchor_cluster.py
