### ISSUE TITLE
dataset/voc/create_list.py 文件运行不通

### ISSUE THREAD

**Issue by wddwzwhhxx** [PaddlePaddle/PaddleDetection#3706]
import sys
import os.path as osp
import logging
# add python path of PadleDetection to sys.path
parent_path = osp.abspath(osp.join(__file__, *(['..'] * 3)))
if parent_path not in sys.path:
    sys.path.append(parent_path)

from ppdet.utils.download import create_voc_list

logging.basicConfig(level=logging.INFO)

voc_path = osp.split(osp.realpath(sys.argv[0]))[0]
create_voc_list(voc_path)
----------------------------
dataset/voc/create_list.py这个文件的用法是怎样的？
如果按 python create_list.py path/to/dataset/的方式，sys.argv[0]直接指向py文件的地址？

**Comment by liuhuiCNN** [comment]
是的

**Comment by wddwzwhhxx** [comment]
> 是的

那么如何按照旧版create_list的方法来使用呢，该物件无法找到用户想处理的文件夹路径

**Comment by liuhuiCNN** [comment]
> > 是的
> 
> 那么如何按照旧版create_list的方法来使用呢，该物件无法找到用户想处理的文件夹路径

你好，我们测试是正常的，请使用ppdet  release2.1 试下。
