### ISSUE TITLE
安装完成后使用cpu测试报错TypeError: predict() got an unexpected keyword argument 'save_txt'

### ISSUE THREAD

**Issue by Madfoid** [PaddlePaddle/PaddleDetection#3707]
python infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=false weights=C:\Users\user1\Downloads\ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg
Traceback (most recent call last):
  File "infer.py", line 162, in <module>
    main()
  File "infer.py", line 158, in main
    run(FLAGS, cfg)
  File "infer.py", line 137, in run
    savetxt=FLAGS.savetxt)
TypeError: predict() got an unexpected keyword argument 'save_txt'

报错位置
def run(FLAGS, cfg):
    # build trainer
    trainer = Trainer(cfg, mode='test')

    # load weights
    trainer.load_weights(cfg.weights)

    # get inference images
    images = get_test_images(FLAGS.infer_dir, FLAGS.infer_img)

    # inference
    trainer.predict(
        images,
        draw_threshold=FLAGS.draw_threshold,
        output_dir=FLAGS.output_dir,
        save_txt=FLAGS.save_txt)

**Comment by liuhuiCNN** [comment]
请在命令行中指定 save_txt参，以官方ppyolo为例：
`python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_2x_coco.yml -o weights=ppyolo_r50vd_dcn_1x_coco.pdparams  --infer_img=demo/000000014439_640x640.jpg --save_txt=True`

**Comment by Madfoid** [comment]
修改后依然报错TypeError: predict() got an unexpected keyword argument 'save_txt'

**Comment by Madfoid** [comment]
> 请在命令行中指定 save_txt参，以官方ppyolo为例：
> `python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_2x_coco.yml -o weights=ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439_640x640.jpg --save_txt=True`

修改后依旧报错TypeError: predict() got an unexpected keyword argument 'save_txt'
(venv) C:\Users\user1\Downloads\PaddleDetection-release-2.1\venv\Scripts\PaddleDetection\tools>python infer.py -c C:\Users\user1\Downloads\PaddleDetection-release-2.1\configs\ppyolo\ppyolo_r50vd_dcn_2x_coco.yml -o use_gpu=false weights=ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo\000000014439_640x640.jpg --save_txt=True
Traceback (most recent call last):
  File "infer.py", line 162, in <module>
    main()
  File "infer.py", line 158, in main
    run(FLAGS, cfg)
  File "infer.py", line 137, in run
    save_txt=FLAGS.save_txt)
TypeError: predict() got an unexpected keyword argument 'save_txt'

**Comment by liuhuiCNN** [comment]
> > 请在命令行中指定 save_txt参，以官方ppyolo为例：
> > `python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_2x_coco.yml -o weights=ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439_640x640.jpg --save_txt=True`
> 
> 修改后依旧报错TypeError: predict() got an unexpected keyword argument 'save_txt'
> (venv) C:\Users\user1\Downloads\PaddleDetection-release-2.1\venv\Scripts\PaddleDetection\tools>python infer.py -c C:\Users\user1\Downloads\PaddleDetection-release-2.1\configs\ppyolo\ppyolo_r50vd_dcn_2x_coco.yml -o use_gpu=false weights=ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo\000000014439_640x640.jpg --save_txt=True
> Traceback (most recent call last):
> File "infer.py", line 162, in
> main()
> File "infer.py", line 158, in main
> run(FLAGS, cfg)
> File "infer.py", line 137, in run
> save_txt=FLAGS.save_txt)
> TypeError: predict() got an unexpected keyword argument 'save_txt'

请问解决了吗？我们测试是正常的，请使用最新的 ppdet release 2.1 试下。
