### ISSUE TITLE
单阶段网络训练能收敛，但是双阶段网络训练不收敛问题。

### ISSUE THREAD

**Issue by zdyshine** [PaddlePaddle/PaddleDetection#371]
最近在训练一批coco格式的自己的数据集，单阶段和双阶段训练，训练集，验证集，以及置信度都是一样的，开始使用的是yolov3进行训练，计算的验证集map=0.49，训练过程也能逐渐收敛。后面改用双阶段网络cascade系列网络训练，试了5个双阶段的网络，目前训练出来的过程，几乎都是一直的：loss在几百个iter之后，就开始震荡，就算训练到5w的iter，loss和几百iter时也几乎一样。计算的验证集map=0.43。请问有遇到这个问题的么，求大佬解答，急，急，急，在线等大佬~~~

**Comment by qingqing01** [comment]
@zdyshine  需要注意双阶段和YOLOv3的差异，双阶段包含背景类，而YOLOv3不含背景类，双阶段类别上差1。 另外，针对自己的数据，总得样本数有变化，注意按照epoch数调节训练的论文和学习率decay的轮数。 

不知道您具体用的哪个cascade网络，以及超参数是怎样调整的？

**Comment by zdyshine** [comment]
感谢您的回复~
目前，config/dcn文件夹里面的几个cascade配置文件都做了修改，
cascade_rcnn_dcn_r50_fpn_1x.yml修改大致如下：
1.修改对应类别，num_classes: 5  # 原始 81（class + 1）
2.修改LearningRate:
             base_lr: 0.0025 # 原始0.02
3.修改 max_size， 根据显存进行了降低
训练轮次等，其他参数暂未修改。


目前所涉及到的其他训练配置文件修改思路是
1.修改类别（class + 1）
2.lr=lr/8
3.修改训练最大尺度
但是训练过程发现训练3w iter的loss和几百个iter的loss，几乎是一样的，没有降低。感觉很奇怪。
| |
张东阳
|
|
zdysuyi@163.com
|
签名由网易邮箱大师定制
在2020年3月22日 11:21，qingqing01<notifications@github.com> 写道：

@zdyshine 需要注意双阶段和YOLOv3的差异，双阶段包含背景类，而YOLOv3不含背景类，双阶段类别上差1。 另外，针对自己的数据，总得样本数有变化，注意按照epoch数调节训练的论文和学习率decay的轮数。

不知道您具体用的哪个cascade网络，以及超参数是怎样调整的？

**Comment by jerrywgz** [comment]
可以尝试使用迁移学习的方式，通过coco上训练好的rcnn模型对你的任务做finetune，参数方面可以降低迭代次数和降低学习率。使用文档可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md
coco上训练好的模型在https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/MODEL_ZOO_cn.md 里可以找到

**Comment by qingqing01** [comment]
@zdyshine  由于时间较久了，暂且关闭了。有问题，可以开新的issue。
