### ISSUE TITLE
检测视频时，检测不到目标

### ISSUE THREAD

**Issue by dhao-island** [PaddlePaddle/PaddleDetection#3711]
下面是输出，希望大佬能指出问题和解决思路，谢谢
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
-----------  Running Arguments -----------
camera_id: -1
image_file: 
model_dir: inference_model/faster_rcnn_r50_1x/
output_dir: output
run_benchmark: False
run_mode: fluid
threshold: 0.2
use_gpu: True
video_file: fire_test/fire.mp4
------------------------------------------
-----------  Model Configuration -----------
Model Arch: RCNN
Use Paddle Executor: False
Transform Order: 
--transform op: Normalize
--transform op: Resize
--transform op: Permute
--------------------------------------------
W0718 15:24:58.436532  4638 analysis_predictor.cc:1145] Deprecated. Please use CreatePredictor instead.
detect frame:1
Inference: 100.47006607055664 ms per batch image
[WARNNING] No object detected.
detect frame:2
Inference: 91.09830856323242 ms per batch image
[WARNNING] No object detected.
后面都是No object detected.

**Comment by dhao-island** [comment]
环境是在ai studio，下面是命令代码
! python PaddleDetection-release-2.0-rc/deploy/python/infer.py --model_dir=inference_model/faster_rcnn_r50_1x/ --video_file=fire_test/fire.mp4 --use_gpu=True  --thresh=0.2

**Comment by nemonameless** [comment]
> 环境是在ai studio，下面是命令代码
> ! python PaddleDetection-release-2.0-rc/deploy/python/infer.py --model_dir=inference_model/faster_rcnn_r50_1x/ --video_file=fire_test/fire.mp4 --use_gpu=True --thresh=0.2

建议切换到release/2.1或develop分支再试试。以及先单张图用tools/infer.py试试看能否检测出来，如果也不能可能就是数据集问题了。如果能则可能导出模型和deploy下infer某步有问题了。
