### ISSUE TITLE
关于预训练模型问题：

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#3713]
以前的模型都是用静态图训练的，现在想用动态图训练，但想加载原来静态图的模型作为预训练模型，可以直接用加载静态图保存的模型断点吗？如不行，有其它方法吗？谢谢！

**Comment by nemonameless** [comment]
静态图和动态图模型的权重的key做下映射一一对应转过去是可以的，可以参考这个代码 https://github.com/nemonameless/weights_st2dy   。但是不保证所有静态图的权重的key映射都能对应上，静态图是把背景也训练了，动态图去背景类训的，而且现有动态图模型训出来的一般都比以前静态图更高，资源时间够的情况下建议还是直接训动态图版本。

**Comment by gongchenting** [comment]
> 静态图和动态图模型的权重的key做下映射一一对应转过去是可以的，可以参考这个代码 https://github.com/nemonameless/weights_st2dy 。但是不保证所有静态图的权重的key映射都能对应上，静态图是把背景也训练了，动态图去背景类训的，而且现有动态图模型训出来的一般都比以前静态图更高，资源时间够的情况下建议还是直接训动态图版本。

你好，weights_st2dy代码库中提供的layer_helper_base.py，这里面会from .initializer import _global_weight_initializer, _global_bias_initializer，但这个_global_weight_initializer与_global_bias_initializer好像并不存在
