### ISSUE TITLE
训练时，加上--eval会报错AttributeError: object has no attribute 'map_type' 

### ISSUE THREAD

**Issue by yumeng88** [PaddlePaddle/PaddleDetection#3714]
训练时，加上--eval会报错 ，训练完成之后在运行python -u tools/eval.py -c configs/yolov3/yolov3_darknet53_270e_four.yml也会报错AttributeError: object has no attribute 'map_type'

**Comment by nemonameless** [comment]
您使用自定义的数据集吗？是VOC格式的？那需要指定评测指标的map_type是 '11point'或者'integral'，参考configs/datasets/voc.yml或者configs/datasets/roadsign_voc.yml开头

**Comment by yumeng88** [comment]
@nemonameless 是的，用的是自定义数据集，VOC格式，我试一下

**Comment by yumeng88** [comment]
@nemonameless 多谢问题解决了，我自定义数据集打开了configs/datasets/coco.yml的复制了一下，少了这个map_type这个评测指标。多谢多谢
