### ISSUE TITLE
 如何对CenterNet训练？

### ISSUE THREAD

**Issue by Sharpiless** [PaddlePaddle/PaddleDetection#3717]
我看到PPDet里面有CenterNet的结构，但是没有给出类似Gt2CenterNetTarget的读取数据接口

**Comment by nemonameless** [comment]
还在计划中，还没有实现Gt2CenterNetTarget。目前有的这个CenterNet是给跟踪模型FairMOT用的。

**Comment by Sharpiless** [comment]
好的感谢
