### ISSUE TITLE
模型结果图片输出处理

### ISSUE THREAD

**Issue by zoain-it** [PaddlePaddle/PaddleDetection#3722]
你好，我用 Paddle(1.7.2) 和 PaddleDetection(c7a1252f20f8c3d9979445f91dbe6706953efcee) 训练了人脸检测模型，可以正确识别并输出标记图片。我想仅输出识别到的人脸部分，但是我不知道需要怎么做。

**Comment by qingqing01** [comment]
您是说只输出检测坐标值，但不可视化到图片上吗？如果是tools/infer.py，最新的代码增加了save_txt的功能:

https://github.com/PaddlePaddle/PaddleDetection/blob/d7383ad99c69e03f984ead52cc645d17f4729837/tools/infer.py#L81

**Comment by zoain-it** [comment]
好的，感谢，我自己切也可以
