### ISSUE TITLE
大规模检测数据集

### ISSUE THREAD

**Issue by xiaohuihui52309** [PaddlePaddle/PaddleDetection#3727]
请问大规模检测数据集在哪里下载呢  试用了这个模型 效果不太好 想自己训练看看！
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/docs/featured_model/LARGE_SCALE_DET_MODEL.md

**Comment by nemonameless** [comment]
融合Open Images V5和Objects365训练集数据的，并不开放。而且数据集太大了训练非常耗时，只下载objects365去训练一般也足够了，http://www.objects365.org/download.html
