### ISSUE TITLE
ppdet/data/transform/operators.py程序BUG (Version 2.1.0)

### ISSUE THREAD

**Issue by jesse01** [PaddlePaddle/PaddleDetection#3729]
![image](https://user-images.githubusercontent.com/6436061/126308219-739c80aa-7b43-4af9-a870-96b2d23c9de7.png)
该代码有3个BUG:
1、202行：变量名写错了，与参数名称不一致
2、648行：参数名写错了，mask写成了image
3、1273行：没有import情况下，直接使用logging

**Comment by nemonameless** [comment]
谢谢反馈，已提pr修正，已经合入develop分支和release/2.2分支。
