### ISSUE TITLE
train blazeface single GPU too long time; 4 GPU core dumped

### ISSUE THREAD

**Issue by yja1** [PaddlePaddle/PaddleDetection#374]
when run CUDA_VISIBLE_DEVICES=1 python tools/train.py -c configs/face_detection/blazeface_nas_v2.yml
too long time, and as training continues, spend more time. htop see cpu, CPU blocking
![image](https://user-images.githubusercontent.com/24217235/77271623-23faaf80-6cea-11ea-8945-dda5c0ca2aa0.png)

when run CUDA_VISIBLE_DEVICES=1,2,3,4 python tools/train.py -c configs/face_detection/blazeface_nas_v2.yml
![image](https://user-images.githubusercontent.com/24217235/77271665-3543bc00-6cea-11ea-9136-f75205980c62.png)

**Comment by ceci3** [comment]
你好，请问下跑 configs/face_detection/blazeface_nas.yml 或者 configs/face_detection/blazeface.yml 的版本正常吗？

**Comment by yja1** [comment]
不正常

**Comment by qingqing01** [comment]
@yja1  What‘s your environment?  the version of Paddle, and the GPU type, CUDA version， the system type.

**Comment by yja1** [comment]
python3 -m pip install paddlepaddle-gpu==1.7.1.post107 -i https://mirror.baidu.com/pypi/simple

GPU  :
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243


linux:
Linux sentec-017 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux


nccl:nccl-2.5.6-2

cudnn:cudnn-10.1-linux-x64-v7.6.5.32.tgz

**Comment by yja1** [comment]
now it can run multigpu. But training time too long.
![image](https://user-images.githubusercontent.com/24217235/77383421-d3ed1d00-6dbd-11ea-9478-8165e7cba4f0.png)

30 minutes past：still here
![image](https://user-images.githubusercontent.com/24217235/77385221-7b6c4e80-6dc2-11ea-9f95-bbbc5ffb33b3.png)

**Comment by yja1** [comment]
现在可以运行多卡，但是停留在第一个iter，训练30分钟过去了：

![image](https://user-images.githubusercontent.com/24217235/77385467-1fee9080-6dc3-11ea-90c4-98e6b7c77d93.png)
![image](https://user-images.githubusercontent.com/24217235/77385475-24b34480-6dc3-11ea-93cf-dd29ed0a3dd3.png)
![image](https://user-images.githubusercontent.com/24217235/77385482-2846cb80-6dc3-11ea-9253-aa2b9d9e00db.png)

**Comment by heavengate** [comment]
麻烦截图看下`top -c` CPU占用数据

**Comment by xiegegege** [comment]
@yja1 你好，我们这没有这种显卡，我用的P40 4卡，然后用docker模拟了你一样的环境ubuntu14.04 CUDA10 CUDNN7.6 paddle1.7.1是可以正常训练的
![image](https://user-images.githubusercontent.com/46314656/77740787-cf8b6300-704e-11ea-9d25-41a6c71eaefb.png)

**Comment by yja1** [comment]
@heavengate 可能要等一天，现在服务器跑的其他训练

**Comment by yja1** [comment]
@heavengate 
![image](https://user-images.githubusercontent.com/24217235/77840675-907b2000-71bc-11ea-86c5-895cefbeeaed.png)
![image](https://user-images.githubusercontent.com/24217235/77840677-96710100-71bc-11ea-819d-8e892d18ab07.png)
![image](https://user-images.githubusercontent.com/24217235/77840681-9a9d1e80-71bc-11ea-833e-82b0c6331c8b.png)

**Comment by heavengate** [comment]
> @heavengate
> ![image](https://user-images.githubusercontent.com/24217235/77840675-907b2000-71bc-11ea-86c5-895cefbeeaed.png)
> ![image](https://user-images.githubusercontent.com/24217235/77840677-96710100-71bc-11ea-819d-8e892d18ab07.png)
> ![image](https://user-images.githubusercontent.com/24217235/77840681-9a9d1e80-71bc-11ea-833e-82b0c6331c8b.png)

看着reader进程CPU基本打满了，是训练很慢么，可以尝试下`TrainReader.worker_num`调大一些试下

**Comment by yja1** [comment]
@heavengate 
4 gpu, worker_num:8 batch_size:32
![image](https://user-images.githubusercontent.com/24217235/77866924-8bbf7600-7267-11ea-92a9-e25bdf241e09.png)

**Comment by yja1** [comment]
1 gpu, worker_num:8 batch_size:32
![image](https://user-images.githubusercontent.com/24217235/77868117-86185f00-726c-11ea-8f21-88ad30f6087d.png)

看起来时间少点。看来还是多卡训练哪里有问题

**Comment by qingqing01** [comment]
@yja1 如果不卡住的话，您用的是TITAN X，速度还算正常的。然后使用多进程的方式，会加快训练 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/tutorials/GETTING_STARTED_cn.md#%E6%B7%B7%E5%90%88%E7%B2%BE%E5%BA%A6%E8%AE%AD%E7%BB%83 ，虽然标题是对混合精度，但对FP32，同样的启动方式也可以的。

**Comment by yja1** [comment]
目前问题是单卡训练，多卡训练，多卡distribute方式启动，worker_num增大，都不能正常训练。
开始几个iter看上去时间正常，但是
2000+iter 之后，训练时间就会达到eta: 10+ days 甚至达到100+ days

**Comment by qingqing01** [comment]
@yja1  因为没有和你完全一样的环境，我们先排查下代码层面的问题？ 方便把你跑的源码+数据一起打包给我们吗？您也可以加Paddle 官方QQ群 703252161，我们找你看下~

**Comment by yja1** [comment]
@qingqing01 怎么发我进入那个群里了Yja1

**Comment by qingqing01** [comment]
closed 

有问题，可以再开新的issue
