### ISSUE TITLE
闪退bug终于找到了，infer.py关于loader()的GeneratorLoader类__next__方法bug

### ISSUE THREAD

**Issue by xzkzdx** [PaddlePaddle/PaddleDetection#3742]
关于loader()的底层GeneratorLoader类__next__方法导致程序闪退问题：
当最后一个元素获取完毕后再调用self._reader.read_next()，StopIteration异常并不能捕获，反而是直接程序闪退

位置：infer.py
for iter_id, data in enumerate(loader()):  

底层位置：paddle\fluid\reader.py

![image](https://user-images.githubusercontent.com/43203333/126469097-4968a9fb-ee91-4b8c-98b4-3a5af97b3a1d.png)

**Comment by heavengate** [comment]
你好，你用的是哪个版本，是用的静态图模型么，还有Paddle版本和操作系统是啥呢

**Comment by xzkzdx** [comment]
windows10系统 cpu
Python 3.7.5
PaddleDetection：http://github.com/PaddlePaddle/PaddleDetection/tree/release/0.5
paddlepaddle==2.1.0

使用的物体识别的相关yml
python tools/infer.py -c configs/dcn/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco.yml 
都是到GeneratorLoader类__next__方法导致自动退出

**Comment by heavengate** [comment]
目前windows上确实有C++端的exception报不到python端的情况，我们还在定位，预计下个发布Paddle版本能带出去

**Comment by SchrodingerLLX** [comment]
这个问题我也遇到了
windows10系统 cpu
Python 3.7
PaddleDetection：http://github.com/PaddlePaddle/PaddleDetection/tree/release/2.2
paddlepaddle-gpu==2.1.3
都是在enumerate(self.XXloader)之后遇到。
相关的一些问题链接：
https://github.com/PaddlePaddle/Paddle/issues/32056
https://github.com/PaddlePaddle/PaddleOCR/issues/2590

**Comment by jjqcat** [comment]
我也遇到一样的问题，不过是在trainer.py程序读取情况下

**Comment by zpf1095** [comment]
同样是在train.py训练时，trainer.py中 for step_id, data in enumerate(self.loader): 异常退出，epoch0正常，到epoch1的时候就出错了

**Comment by nemonameless** [comment]
请使用最新develop或2.6分支，https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.6
