### ISSUE TITLE
关于PP_YOLO_R50vd_slim训练结果预测没有框显示的是原图、模型不收敛问题

### ISSUE THREAD

**Issue by smallwhi** [PaddlePaddle/PaddleDetection#3743]
**前言：**
在了解了PPYOLO的各种优化策略后，我用paddlex训练出一个PPYOLO模型，效果还不错，但是遗憾的是不能用paddlex裁剪量化PPYOLO模型，所以我转到PaddleDetection找到了一个基于COCO上benchmark如下：
![image](https://user-images.githubusercontent.com/66171021/126582343-383ff5c3-5616-4af9-800b-22eed6a9f8e4.png)
这个效果正是我理想中的模型，于是我开始着手训练，但是结果并不理想。训练的模型大小model_final.pdopt和model_final.pdparams每个大小都有将近300MB，预测结果没有框，显示的是原图，转化后的模型文件夹里总共也有200MB
**我训练的环境是：**
paddlepaddle-gpu==2.1.0.post101
paddledet==2.1.0
paddleslim==2.1.1
**训练配置文件：**
基本按照默认的文件，只是自定义了自己的数据集,我自己定义的数据集在训练的过程中没有报警告和错误，是用VOC数据集转成COCO的。
修改了coco_detection.yml中的数据集路径为自己的路径，num_classes=自己的类别数
修改了ppyolo_reader.yml中的TrainReader:batch_size: 24->8
修改了ppyolo_r50vd_qat_pact.yml中的epoch: 50变为epoch: 150，base_lr: 0.0005变为0.0003
    milestones:
    - 30
    - 45
    改变为
    milestones:
    - 90
    - 135
训练过程中，loss有正常下降，但是反常的是下降到一定程度后开始上升，到了一定高度又不再上升，保持原值。
**可视化结果如下：**
![image](https://user-images.githubusercontent.com/66171021/126581939-c31e1f42-5663-4597-aeab-6e4e30eae9ff.png)

**模型评估结果是：**
![image](https://user-images.githubusercontent.com/66171021/126581124-7859ef1a-6485-4bb6-9791-a84bf5834bd9.png)
**我的问题**
**①主要问题是没有框的原因是我训练的结果没有收敛吗？**
②coco_detection.yml中num_classes=自己的类别数？还是需要+1？因为with_background: true是默认的，但是我没有这样做
③batch_size/8=3好像并不合理，我设置成=8是不是太大了，需要设置成2吗，base_lr是我需要改的学习率吗？

**Comment by yghstill** [comment]
@smallwhi ppyolo模型在你自己的数据上完整训练过吗？还是说你直接使用slim的config做量化？如果没有完整训练，请把模型训练收敛好，再加载到slim_config中开始量化
1. 看着是没有收敛好
2. num_classes设置真实类别数即可
3. batch_size根据显存大小来设置即可，如果batch_size减半，将lr减半即可

**Comment by smallwhi** [comment]
请问在哪里把完整训练的模型加载进去？我之前是直接量化训练的

**Comment by yghstill** [comment]
@smallwhi 先非量化训练好模型后，再进行量化训练

**Comment by smallwhi** [comment]
嗯，我现在非量化训练了一个ppyolo模型（用paddlex训练好了一个ppyolo模型），接着想做量化训练，但是不知道在哪配置把训练好的模型文件加载进去训练。
所以想问下该怎么加载，现在已经将模型加载进去了，是将pretrain_weights改成模型的.pdparam文件路径就可以了。
非常感谢！

**Comment by smallwhi** [comment]
训练了四个小时，发现loss在20几下不去了应该是没有配置成功，把训练停了。用生成的15.pdparam,15.pdpot进行测试，仍然没有框，请问我将pretrain_weights改成非量化训练好的模型的.pdparam文件路径是正确的方法吗？
还是说paddlex下训练的模型无法拿到paddlepaddle下进行训练？paddlex训练的生成模型文件结构如下：
![image](https://user-images.githubusercontent.com/66171021/126958864-5945bee6-b40a-4732-8c8c-e694c8e698c7.png)
这和paddlepaddle训练只有生成model.pdparam和model.pdopt有所不同
 @yghstill

**Comment by yghstill** [comment]
@smallwhi PaddleX训练的模型已经是导出的模型，无法在PaddleDetection中继续训练了，可以直接在PaddleDetection中进行实验。

**Comment by smallwhi** [comment]
直接训练ppyolo，没有量化或裁剪，仍然遇到相同的问题--训练出来的模型用来预测没有框，我在训练yolov3_darknet却不会发生这种问题

**Comment by kaixin-bai** [comment]
遇到的问题和 @smallwhi 一样，用yolov3_darknet可训练可收敛，类似的参数用ppyolo无法收敛

**Comment by TUDelftHao** [comment]
同样的问题，训练ppyolo无法收敛，指标很低，预测没有框
