### ISSUE TITLE
how can i add a bbox assigner?

### ISSUE THREAD

**Issue by krisandchris** [PaddlePaddle/PaddleDetection#3746]

**Comment by jerrywgz** [comment]
Could you please specify your question？ Do you want to optimize the bbox assigner module in Faster RCNN?

**Comment by krisandchris** [comment]
> Could you please specify your question？ Do you want to optimize the bbox assigner module in Faster RCNN?

I want to use atss in paddle (https://github.com/sfzhang15/ATSS)

**Comment by yghstill** [comment]
@krisandchris atss already supports: https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/transform/atss_assigner.py
and released GFL model: https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/gfl
