### ISSUE TITLE
mask_rcnn_r50_fpn Eval时占用内存持续增长

### ISSUE THREAD

**Issue by cvfzhong** [PaddlePaddle/PaddleDetection#375]
用mask_rcnn_r50_fpn在coco上训练，训练正常，但eval的时候占用内存/显存持续增长，且速度越来越慢，计算大概500张图后就跑不动了，最后导致系统卡死，是内存没释放吗？

用mask_rcnn_r50就正常

**Comment by jerrywgz** [comment]
我这边使用paddle1.7+paddledetection master分支测试mask_rcnn_r50_fpn是正常的， 
![image](https://user-images.githubusercontent.com/22989727/77280806-4eeffe00-6d00-11ea-8b4c-a4ff5ecbda29.png)
速度基本保持不变，top观察内存也相对稳定，你这边的机器有其他任务在跑吗，另外你的paddle和检测库版本分别是什么？

**Comment by cvfzhong** [comment]
没有别的任务，我是paddle1.7+paddledetection release0.2，系统是ubuntu 14.04。。paddle库是我自己编译的，pip安装的库当时报TLS错误，我自己编译了个不带MKL的版本

刚刚跑mask_rcnn_r50，也是有问题，只不过内存占用增长慢一点，到第2轮eval快跑完的时候也不行了

**Comment by qingqing01** [comment]
@cvfzhong 您把 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/data/reader.py#L198

中的bufsize改成2试下呢？ 或者在 `configs/mask_reader.yml` 中设置bufsize试下:

```
worker_num: 2
bufsize: 2
```

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/381

**Comment by qingqing01** [comment]
@cvfzhong 请问是否有设置bufsize试下呢？ 你的评估是训练中的评估呢？还是训练完成后，使用tools/eval.py评估？

**Comment by cvfzhong** [comment]
我现在去了--eval在跑，等跑完再试下设置bufsize。是在训练中评估的。

**Comment by qingqing01** [comment]
@cvfzhong 好的，感谢回复~

**Comment by cvfzhong** [comment]
设置bufsize和用eval.py都还是一样
不过我用自己写的一个eval（从infer.py改过来的）程序跑就没问题

**Comment by jerrywgz** [comment]
可以提供下你的eval脚本吗，另外可以试下把worker_num设置为-1看下

**Comment by cvfzhong** [comment]
设置成-1也一样

这是我的eval代码
[pptest.zip](https://github.com/PaddlePaddle/PaddleDetection/files/4375850/pptest.zip)

**Comment by jerrywgz** [comment]
看了下你的代码，输出部分原检测库是res，你这边是解析后的maskout，这部分的内存占用应该是会大于res的，所以应该reader的地方导致的，可以再发下你的配置文件吗

**Comment by cvfzhong** [comment]
说明一下，上边那个我自己写的eval是不会内存爆炸的，用ppdet自带的eval.py才会。maskout如果每次能正确释放，也占不了多少内存吧

这是我的config文件
[mask_rcnn_r50_fpn_1x_v1.yml.txt](https://github.com/PaddlePaddle/PaddleDetection/files/4378700/mask_rcnn_r50_fpn_1x_v1.yml.txt)

**Comment by qingqing01** [comment]
Fixed by https://github.com/PaddlePaddle/PaddleDetection/pull/430
