### ISSUE TITLE
关于优化器配置

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleDetection#3750]
我发现大部分.yml都是默认配置 **Momentum** 优化器，我有2点想请教一下：一是为何不添加 **use_nesterov** ，二是 **Momentum** 比 **Adam** 更适合目标检测么？

**Comment by jerrywgz** [comment]
目前确实绝大部分优化器都使用momentum，也有个别网络使用adam，例如目标跟踪的fairmot；以及DETR使用了AdamW。我们还没有专门对比过不同优化器的效果

**Comment by lyuwenyu** [comment]
> 我发现大部分.yml都是默认配置 **Momentum** 优化器，我有2点想请教一下：一是为何不添加 **use_nesterov** ，二是 **Momentum** 比 **Adam** 更适合目标检测么？

默认优化器配置是参考原文的设置
