### ISSUE TITLE
mask rcnn 如何使用

### ISSUE THREAD

**Issue by 827346462** [PaddlePaddle/PaddleDetection#3751]
我想知道如何使用paddleDetection套件的mask rcnn 。我去查看https://www.paddlepaddle.org.cn/modelbasedetail/maskrcnn的运行文档。1是文档失效2是操作命令明显有错
![image](https://user-images.githubusercontent.com/50097546/126612967-7a2843e5-c4c8-4beb-9e7e-bc08ef61b2e6.png)

**Comment by 827346462** [comment]
![image](https://user-images.githubusercontent.com/50097546/126614206-a923cd86-6172-4d1d-bdb1-1d39388b24e0.png)

**Comment by jerrywgz** [comment]
paddle官网中的教程对应的是静态图版本了，可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/GETTING_STARTED_cn.md 这里的文档
