### ISSUE TITLE
使用人脸检测模型出错，the module BlazeFace is not registered

### ISSUE THREAD

**Issue by 1667** [PaddlePaddle/PaddleDetection#3760]
![image](https://user-images.githubusercontent.com/5113570/126731430-10e36e47-80d7-4ce5-8abe-25b4dae5e0ce.png)

**Comment by 1667** [comment]
在modeling/architectures/__init__.py文件中添加from . import blazeface 即可

**Comment by watertianyi** [comment]
没有效果，加了

**Comment by 1667** [comment]
> 没有效果，加了

加上以后再从源码重新安装一下，或者直接到安装目录修改添加
