### ISSUE TITLE
下载的时候出现错误：RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 1

### ISSUE THREAD

**Issue by 905390215** [PaddlePaddle/PaddleDetection#3766]
下载之后，输入命令paddle.utils.run_check()后报错：
      RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126）
       Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at C:\home\workspace\Paddle_release\paddle\fluid\platform\dynload\dynamic_loader.cc:265)
  -我是windows系统，我没找到platform\dynload\dynamic_loader这个文件夹，这个应该怎么处理啊

**Comment by liuhuiCNN** [comment]
根据日志，提示CUDA 库没有找到，请先检查一下CUDA安装是否正常。
