### ISSUE TITLE
 S2ANet 运行python3 setup.py install时报错ValueError: Not found CUDA runtime, please use `export CUDA_HOME=XXX` to specific it.

### ISSUE THREAD

**Issue by kelek2** [PaddlePaddle/PaddleDetection#3769]

**Comment by kelek2** [comment]
正常安装paddle环境，版本2.1.0，能否跑检测demo，现在想跑一下S2ANET，运行安装python3 setup.py install时报错ValueError: Not found CUDA runtime, please use `export CUDA_HOME=XXX` to specific it.求解答如何设置，多谢🙏

**Comment by liuhuiCNN** [comment]
根据错误提示，是没找到CUDA环境，请检查一下CUDA环境安装是否正常。develop分支中ext_op支持CPU和GPU，建议用develop代码。

**Comment by kelek2** [comment]
> 根据错误提示，是没找到CUDA环境，请检查一下CUDA环境安装是否正常。develop分支中ext_op支持CPU和GPU，建议用deve

多谢，重新设置了CUDA环境，OK跑通～但是测试DOTA图像时候出现下面问题
line 124, in draw_bbox
    text = "{} {:.2f}".format(catid2name[catid], score)
KeyError: 12

**Comment by liuhuiCNN** [comment]
> > 根据错误提示，是没找到CUDA环境，请检查一下CUDA环境安装是否正常。develop分支中ext_op支持CPU和GPU，建议用deve
> 
> 多谢，重新设置了CUDA环境，OK跑通～但是测试DOTA图像时候出现下面问题
> line 124, in draw_bbox
> text = "{} {:.2f}".format(catid2name[catid], score)
> KeyError: 12

你好，这是数据路径设置错误导致无法读取标签列表，请检查一下数据配置路径。请使用develop分支或者release2.2分支代码

**Comment by lilong-epfl** [comment]
> > 根据错误提示，是没找到CUDA环境，请检查一下CUDA环境安装是否正常。develop分支中ext_op支持CPU和GPU，建议用deve
> 
> 多谢，重新设置了CUDA环境，OK跑通～但是测试DOTA图像时候出现下面问题
> line 124, in draw_bbox
> text = "{} {:.2f}".format(catid2name[catid], score)
> KeyError: 12

您好，我这边出现了个您一样的问题，请问您的问题解决了吗？

**Comment by kelek2** [comment]
> > > 根据错误提示，是没找到CUDA环境，请检查一下CUDA环境安装是否正常。develop分支中ext_op支持CPU和GPU，建议用deve
> > 
> > 
> > 多谢，重新设置了CUDA环境，OK跑通～但是测试DOTA图像时候出现下面问题
> > line 124, in draw_bbox
> > text = "{} {:.2f}".format(catid2name[catid], score)
> > KeyError: 12
> 
> 您好，我这边出现了个您一样的问题，请问您的问题解决了吗？

将CUDA的环境重配以下，需要重启电脑，我这里就可以了

**Comment by lilong-epfl** [comment]
> > > > 根据错误提示，是没找到CUDA环境，请检查一下CUDA环境安装是否正常。develop分支中ext_op支持CPU和GPU，建议用deve
> > > 
> > > 
> > > 多谢，重新设置了CUDA环境，OK跑通～但是测试DOTA图像时候出现下面问题
> > > line 124, in draw_bbox
> > > text = "{} {:.2f}".format(catid2name[catid], score)
> > > KeyError: 12
> > 
> > 
> > 您好，我这边出现了个您一样的问题，请问您的问题解决了吗？
> 
> 将CUDA的环境重配以下，需要重启电脑，我这里就可以了

不好意思，我没有说清楚，我是说那个 KeyError:12 的问题。

**Comment by kelek2** [comment]
> > > > > 根据错误提示，是没找到CUDA环境，请检查一下CUDA环境安装是否正常。develop分支中ext_op支持CPU和GPU，建议用deve
> > > > 
> > > > 
> > > > 多谢，重新设置了CUDA环境，OK跑通～但是测试DOTA图像时候出现下面问题
> > > > line 124, in draw_bbox
> > > > text = "{} {:.2f}".format(catid2name[catid], score)
> > > > KeyError: 12
> > > 
> > > 
> > > 您好，我这边出现了个您一样的问题，请问您的问题解决了吗？
> > 
> > 
> > 将CUDA的环境重配以下，需要重启电脑，我这里就可以了
> 
> 不好意思，我没有说清楚，我是说那个 KeyError:12 的问题。

text = "{} {:.2f}".format(catid2name[catid+1], score)
可能有两个原因，一个是标签没对上，看看你那里0开始还是1开始，还有一个可能你测试图像写标签的时候越界了，可以把置信度先调高点

**Comment by lilong-epfl** [comment]
> > > > > > 根据错误提示，是没找到CUDA环境，请检查一下CUDA环境安装是否正常。develop分支中ext_op支持CPU和GPU，建议用deve
> > > > > 
> > > > > 
> > > > > 多谢，重新设置了CUDA环境，OK跑通～但是测试DOTA图像时候出现下面问题
> > > > > line 124, in draw_bbox
> > > > > text = "{} {:.2f}".format(catid2name[catid], score)
> > > > > KeyError: 12
> > > > 
> > > > 
> > > > 您好，我这边出现了个您一样的问题，请问您的问题解决了吗？
> > > 
> > > 
> > > 将CUDA的环境重配以下，需要重启电脑，我这里就可以了
> > 
> > 
> > 不好意思，我没有说清楚，我是说那个 KeyError:12 的问题。
> 
> text = "{} {:.2f}".format(catid2name[catid+1], score)
> 可能有两个原因，一个是标签没对上，看看你那里0开始还是1开始，还有一个可能你测试图像写标签的时候越界了，可以把置信度先调高点

好的，谢谢
