### ISSUE TITLE
ppyolo模型支持转openvino吗？使用预训练模型导出转换报错

### ISSUE THREAD

**Issue by 15162162323** [PaddlePaddle/PaddleDetection#3771]

**Comment by 15162162323** [comment]
➜  src_repo git:(master) python /opt/intel/openvino/deployment_tools/tools/benchmark_tool/benchmark_app.py -m /project/train/models/inference_model/onnx/model.onnx
[Step 1/11] Parsing and validating input arguments
[ WARNING ]  -nstreams default value is determined automatically for a device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README. 
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
         API version............. 2.1.2021.3.0-2787-60059f2c755-releases/2021/3
[ INFO ] Device info
         CPU
         MKLDNNPlugin............ version 2.1
         Build................... 2021.3.0-2787-60059f2c755-releases/2021/3

[Step 3/11] Setting device configuration
[ WARNING ] -nstreams default value is determined automatically for CPU device. Although the automatic selection usually provides a reasonable performance,but it still may be non-optimal for some cases, for more information look at README.
[Step 4/11] Reading network files
[ INFO ] Read network took 565.77 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
[Step 7/11] Loading the model to the device
[ ERROR ] get_shape was called on a descriptor::Tensor with dynamic shape
Traceback (most recent call last):
  File "/opt/intel/openvino/python/python3.6/openvino/tools/benchmark/main.py", line 240, in run
    exe_network = benchmark.load_network(ie_network)
  File "/opt/intel/openvino/python/python3.6/openvino/tools/benchmark/benchmark.py", line 73, in load_network
    num_requests=1 if self.api_type == 'sync' else self.nireq or 0)
  File "ie_api.pyx", line 336, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 345, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: get_shape was called on a descriptor::Tensor with dynamic shape

**Comment by 15162162323** [comment]
2021-07-24 19:43:39.628335: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.UnsqueezeTileReshapeBlockToInterpolate.UnsqueezeTileReshapeBlockToInterpolate'>): After partial shape inference were found shape collision for node Reshape_5 (old shape: [   1  512 3600], new shape: [512  20  20   9])

**Comment by liuhuiCNN** [comment]
你好，请问你是怎样导出模型的呢？请参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_MODEL.md
和 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_ONNX_MODEL.md 试试。

**Comment by 15162162323** [comment]
> 你好，请问你是怎样导出模型的呢？请参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_MODEL.md
> 和 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_ONNX_MODEL.md 试试。
@liuhuiCNN @qingqing01  

是的，我也是按照文档中的方式进行导出和转换的，前期已经完成了paddledetection的yolov3模型的导出转换（https://github.com/PaddlePaddle/PaddleDetection/issues/3667），踩了两个坑。但是用同样的的方法ppyolo模型不适用。
`➜  src_repo git:(master) ✗ python /opt/intel/openvino/deployment_tools/model_optimizer/mo.py --framework onnx \
--input_model /project/train/models/inference_model/pponnx/model.onnx \
--model_name ppyolo \
--output_dir /project/train/models/inference_model/openvino2 \
--input_shape "[1,3,608,608],[1,2],[1,2]" \
--input "image,im_shape,scale_factor"
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      /project/train/models/inference_model/pponnx/model.onnx
        - Path for generated IR:        /project/train/models/inference_model/openvino2
        - IR output name:       ppyolo
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         image,im_shape,scale_factor
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [1,3,608,608],[1,2],[1,2]
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       False
ONNX specific parameters:
        - Inference Engine found in:    /opt/intel/openvino/python/python3.6/openvino
Inference Engine version:       2.1.2021.3.0-2787-60059f2c755-releases/2021/3
Model Optimizer version:            2021.3.0-2787-60059f2c755-releases/2021/3
2021-07-25 14:16:30.323532: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.UnsqueezeTileReshapeBlockToInterpolate.UnsqueezeTileReshapeBlockToInterpolate'>): After partial shape inference were found shape collision for node Reshape_5 (old shape: [   1  512 3249], new shape: [512  19  19   9])`

**Comment by jiangjiajun** [comment]
PPYOLO由于模型中存在DCN，这个OP比较复杂，转成ONNX后，涉及到多个OP组合实现，当前确实会从onnx转openvino出现问题。

-------------------------------------------------------------------

当前我们正计划OpenVINO原生支持Paddle模型，包括PPYOLO模型

**Comment by 15162162323** [comment]
> PPYOLO由于模型中存在DCN，这个OP比较复杂，转成ONNX后，涉及到多个OP组合实现，当前确实会从onnx转openvino出现问题。
> 
> 当前我们正计划OpenVINO原生支持Paddle模型，包括PPYOLO模型

tks！我们项目上正在尝试paddle的模型转openvino，对于yolov3版本已经验证完成，当前在尝试ppyolo的转换

**Comment by lfxx** [comment]
> 

你好，请问ppyolov2转换成功了吗，我转换成功了，但检测结果是混乱的

**Comment by lfxx** [comment]
> 

你好，请问ppyolov2转换成功了吗，我转换成功了，但检测结果是混乱的

**Comment by lfxx** [comment]
> > PPYOLO由于模型中存在DCN，这个OP比较复杂，转成ONNX后，涉及到多个OP组合实现，当前确实会从onnx转openvino出现问题。
> > 当前我们正计划OpenVINO原生支持Paddle模型，包括PPYOLO模型
> 
> tks！我们项目上正在尝试paddle的模型转openvino，对于yolov3版本已经验证完成，当前在尝试ppyolo的转换

你好，请问ppyolov2转换成功了吗，我转换成功了，但检测结果是混乱的
