### ISSUE TITLE
如果只做简单的分类，不需要位置标注，应该怎么弄

### ISSUE THREAD

**Issue by sinoboy168** [PaddlePaddle/PaddleDetection#3772]
各位大佬，是在VOC数据里面标注那个数据留空吗？谢谢

**Comment by liuhuiCNN** [comment]
如果是分类的话，请参考以下分类算法？您可以参考下：https://github.com/PaddlePaddle/Paddleclas

**Comment by sinoboy168** [comment]
我去看过PaddleClas，那边说类别较少，建议用PaddleDetection啊

**Comment by liuhuiCNN** [comment]
类别较少但是**没有标注框**的话，最推荐的还是用分类算法解决。
