### ISSUE TITLE
数据下载函数返回值

### ISSUE THREAD

**Issue by gathierry** [PaddlePaddle/PaddleDetection#3773]
这个函数的返回值是不是应该在while外面，不然如果数据已经下载过的话，这里就会返回None

https://github.com/PaddlePaddle/PaddleDetection/blob/d7383ad99c69e03f984ead52cc645d17f4729837/ppdet/utils/download.py#L379

**Comment by liuhuiCNN** [comment]
你好，这里会判断路径是否存在，不存在的话才会调用下载数据的逻辑，所以这里没有影响。
https://github.com/PaddlePaddle/PaddleDetection/blob/d7383ad99c69e03f984ead52cc645d17f4729837/ppdet/utils/download.py#L275

**Comment by gathierry** [comment]
了解了，谢谢回复。
因为我在本地下载了压缩包，但还没有解压，又不想等待下载，就直接把压缩包复制到`.cache/paddle`相应的目录下了，而`fullpath`是解压后的路径，所以我就遇到了这个报错。
确实是我的操作不太常规
