### ISSUE TITLE
为什么rcnn_enhance中fps说有61，而实际在eval时只有19？

### ISSUE THREAD

**Issue by DQAA** [PaddlePaddle/PaddleDetection#3774]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/configs/rcnn_enhance

**Comment by wangxinxin08** [comment]
你好，我们测试fps是使用deploy/python/infer.py下面的代码进行测试的，你可以参考这个链接：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy, 将模型导出后进行测试
