### ISSUE TITLE
有没有加载模型进行测试的API

### ISSUE THREAD

**Issue by sanmulab** [PaddlePaddle/PaddleDetection#3775]
请问ppdet有像paddlex那样加载模型进行预测的API吗？例如下面几行代码。因为我用ppdet自带的infer.py脚本文件进行推理整个图片文件夹时，返回的save_txt没有全部保存到一个文件当中，并且返回的txt内容和我的需求不符合。所以我想自己写一个脚本，对得到的预测结果进行后续单独处理。
import paddlex as pdx
model = pdx.load_model('output/faster_rcnn_r101vd_fpn/best_model')
image_name = 'test_images/test1.jpg'
result = model.predict(image_name)
print("Predict Result: ", result)

**Comment by wangxinxin08** [comment]
参考https://github.com/PaddlePaddle/PaddleDetection/blob/d7383ad99c69e03f984ead52cc645d17f4729837/ppdet/model_zoo/tests/test_get_model.py#L32, 可以直接获取model，图片需要经过预处理保存在inputs这个字典里面(一般包含image, im_shape, scale_factor三个字段)，然后就可以使用model.get_pred进行预测了

**Comment by sanmulab** [comment]
你好，感谢回复！看了test_get_model.py文件后还是不知道怎么重写，能提供一份案例py脚本吗？只需加载训练好的模型，然后输入单张图片路径，最后打印出预测结果的文本信息的功能。例如下列代码
from mmdet.apis import init_detector, inference_detector
import mmcv


# Specify the path to model config and checkpoint file
config_file = 'configs/faster_rcnn/faster_rcnn_r101_fpn_2x_coco.py'
checkpoint_file = 'outfaster/latest.pth'


# build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file, device='cuda:0')


# test a single image and show the results
img = 'test.jpg'&nbsp;


&nbsp;# or img = mmcv.imread(img), which will only load it once
result = inference_detector(model, img)


model.show_result(img, result, out_file='result.jpg')
print(result)&nbsp; #output category score xmin ymin w h







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月26日(星期一) 中午11:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 有没有加载模型进行测试的API (#3775)





 
参考https://github.com/PaddlePaddle/PaddleDetection/blob/d7383ad99c69e03f984ead52cc645d17f4729837/ppdet/model_zoo/tests/test_get_model.py#L32, 可以直接获取model，图片需要经过预处理保存在inputs这个字典里面(一般包含image, im_shape, scale_factor三个字段)，然后就可以使用model.get_pred进行预测了

**Comment by wangxinxin08** [comment]
可以直接参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/python 用deploy的方式预测单张图片，
