### ISSUE TITLE
同样的coco格式数据集，在mask rcnn上可以达到53%的ap,solov2是9%，相差巨大，想问下是不是2.0的版本solov2还有不完善的地方呢

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleDetection#3780]
so lo
<img width="766" alt="image" src="https://user-images.githubusercontent.com/67897601/126923934-5fec5a57-888e-4596-8546-483b9c745a60.png">
mask
<img width="788" alt="image" src="https://user-images.githubusercontent.com/67897601/126923994-550a233d-20fe-4502-92ce-51ecd65d0b03.png">

**Comment by lyuwenyu** [comment]
看截图 一个是mask ap, 一个是bbox ap ？

**Comment by yghstill** [comment]
@aishangmaxiaoming 经沟通，切换release/2.2版本后SOLOv2模型收敛的问题已解决。
