### ISSUE TITLE
paddledetection如何checkout到develop

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#3781]
各位前辈们好，我试了checkout但是都失败了
<img width="652" alt="截屏2021-07-26 上午11 25 51" src="https://user-images.githubusercontent.com/87430649/126929096-796d7915-79df-4956-989d-c5a39a10c8fc.png">

**Comment by lyuwenyu** [comment]
- 图里什么版本的Python,  另外建议直接使用 不要pip安装
---
- 如果是从官网直接clone的  `git fetch; git checkout -b xxx develop`
- 如果是从fork的repo clone的  `git remote add upstream https://github.com/PaddlePaddle/PaddleDetection.git; git fetch upstream; git checkout -b xxx upstream/develop`
