### ISSUE TITLE
训练可视化问题，服务器端训练模型，本地可视化训练指标变化，无法加载出变化趋势图

### ISSUE THREAD

**Issue by ResonLee** [PaddlePaddle/PaddleDetection#3791]
训练的服务器系统：ubuntu
cuda:10.1
paddledetection：2.1
paddle：2.1
本地笔记本：windows
cuda:10.1
paddledetection:2.1
paddle:2.1

在ubuntu下训练得到的模型和训练日志文件，训练完成后将保存的权重文件和训练日志文件下载到本地Windows电脑上，使用可视化命令显示训练日志文件，想看下模型ap值及loss的变化趋势，运行命令后vdl可视化网页一直处于正在加载数据，但是总是加载不出来（网络没问题），记事本的方式打开log文件，发现里面全是乱码，是不是保存日志文件的时候不是按utf-8的编码来的啊？该怎么处理
![image](https://user-images.githubusercontent.com/54474938/127081376-caa0ff85-0d68-4600-97a1-dd8688b2f1bd.png)

**Comment by YixinKristy** [comment]
1. 首先，【显示数据加载中】可能是您的浏览器版本问题，您可以使用chrome浏览器试试~
2. VDL保存的日志是以二进制格式保存，如需读取，可用【logreader】接口
![image](https://user-images.githubusercontent.com/48054808/127123097-64b584f7-248c-482f-b15d-0d8b8cb66d23.png)

具体使用方式请参考：https://github.com/PaddlePaddle/VisualDL/blob/develop/docs/io/LogReader.md

VDL与框架、操作系统不绑定，您可以灵活使用~

**Comment by ResonLee** [comment]
使用的浏览器版本就是chrome浏览器，使用vdl后端loadReader可以将训练的日志文件可视化图形嘛？

**Comment by ResonLee** [comment]
使用的浏览器版本就是chrome浏览器，使用vdl后端loadReader可以将训练的日志文件可视化图形嘛？

**Comment by YixinKristy** [comment]
使用的vdl版本是？使用logreader只能看具体的数值数据，如果写入的数据无问题，是可以正常画出来的哈~

**Comment by ResonLee** [comment]
2.2.0版本

**Comment by YixinKristy** [comment]
可以将log日志发出来看下么？我们这边帮您看下~
