### ISSUE TITLE
验证集的batchsize设大一点有影响嘛

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#3796]
我看到很多网络训练的batchsize会设的比较大，但是验证集的batchsize始终为8，请问验证集的batchsize设大一点有影响嘛

**Comment by nemonameless** [comment]
对训练和eval的结果都没有影响。验证集的batchsize设大一点，eval的过程就会更快。但偶尔有某个网络可能还不支持bs>1的eval。
