### ISSUE TITLE
PaddleDetection的精度只有50%左右，在工业上可以落地吗？

### ISSUE THREAD

**Issue by sinoboy168** [PaddlePaddle/PaddleDetection#3797]
就在PaddleDetection的首页里面描述：
PP-YOLO在COCO数据集精度45.9%，Tesla V100预测速度72.9FPS，精度速度均优于YOLOv4
PP-YOLO v2是对PP-YOLO模型的进一步优化，在COCO数据集精度49.5%，Tesla V100预测速度68.9FPS

**Comment by nemonameless** [comment]
可以落地。COCO数据集精度50%左右已经不低了吧

**Comment by sinoboy168** [comment]
这和数据集有关系吗？一般的理解，哪怕只是要达到辅助人工的左右，应该也要80%精度吧？

**Comment by nemonameless** [comment]
所谓的精度是指mAP(IoU=0.5:0.95): mean Average Precision，即各类别AP的平均值。而AP50为mAP(IoU=0.5)。
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/ppyolo/README_cn.md 建议再看下文档的表格以及表格下面的注解。
