### ISSUE TITLE
solov2 训练 coco数据集 FatalError: `Segmentation fault` is detected by the operating system.

### ISSUE THREAD

**Issue by LeonNerd** [PaddlePaddle/PaddleDetection#3802]
## 描述问题/Describe the bug
使用solov2训练coco数据集时出现下面的报错
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1627458384 (unix time) try "date -d @1627458384" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 4090078 (TID 0x7f906098b740) from PID 0 ***]

Segmentation fault (core dumped)

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
请填写命令/A placeholder for the command.

> python tools/train.py -c configs/solov2/solov2_r50_fpn_3x_coco.yml

```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

> 修改coco_instances.yaml中的dataset_dir

> metric: COCO
    num_classes: 80

TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: /data2/hdsx_data/COCO
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_poly', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: /data2/hdsx_data/COCO

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json

3. 您使用的数据集是？/What dataset did you use?

> coco数据集中的train2017

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
```
> (paddle_env) [hdsx@localhost PaddleDetection]$ python tools/train.py -c configs/solov2/solov2_r50_fpn_3x_coco.yml
/home/hdsx/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
loading annotations into memory...
Done (t=12.45s)
creating index...
index created!
[07/28 15:46:15] ppdet.data.source.coco WARNING: Found an invalid bbox in annotations: im_id: 200365, area: 0.0 x1: 296.65, y1: 388.33, x2: 297.67999999999995, y2: 388.33.
[07/28 15:46:20] ppdet.data.source.coco WARNING: Found an invalid bbox in annotations: im_id: 550395, area: 0.0 x1: 9.98, y1: 188.56, x2: 15.52, y2: 188.56.
W0728 15:46:21.790194 4090078 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.1, Runtime API Version: 10.1
W0728 15:46:21.792263 4090078 device_context.cc:422] device: 0, cuDNN Version: 8.0.
/home/hdsx/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/data/transform/batch_operators.py:625: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ins_ind_label = np.zeros([num_grid**2], dtype=np.bool)
/home/hdsx/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/data/transform/batch_operators.py:625: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ins_ind_label = np.zeros([num_grid**2], dtype=np.bool)
[07/28 15:46:23] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/hdsx/.cache/paddle/weights/ResNet50_cos_pretrained.pdparams
[07/28 15:46:24] ppdet.engine INFO: Epoch: [0] [    0/58633] learning_rate: 0.000000 loss_ins: 2.442639 loss_cate: 1.173750 loss: 3.616388 eta: 21 days, 13:42:58 batch_cost: 0.8830 data_cost: 0.0003 ips: 2.2651 images/s

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1627458384 (unix time) try "date -d @1627458384" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 4090078 (TID 0x7f906098b740) from PID 0 ***]

Segmentation fault (core dumped)
```

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
paddledet                 2.1.0
paddlepaddle-gpu          2.1.0.post101

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：
paddle2onnx               0.6                      pypi_0    pypi
paddlehub                 2.1.0                    pypi_0    pypi
paddlenlp                 2.0.1                    pypi_0    pypi
paddleslim                1.1.1                    pypi_0    pypi
paddlex                   1.3.11                   pypi_0    pypi

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
centos7

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
python3.7.10

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
GPU Compute Capability: 7.5, Driver API Version: 11.1, Runtime API Version: 10.1 cuDNN Version: 8.0.

**Comment by yghstill** [comment]
@LeonNerd 训练其他模型有问题吗？看报错应该和环境有关。

**Comment by LeonNerd** [comment]
> @LeonNerd 训练其他模型有问题吗？看报错应该和环境有关。
之前用ppyolov2训练road sign数据集是没有问题的

**Comment by LeonNerd** [comment]
> @LeonNerd 训练其他模型有问题吗？看报错应该和环境有关。
@yghstill  之前用ppyolov2训练road sign数据集是没有问题的

**Comment by yghstill** [comment]
@LeonNerd solov2修复了一个num_classes的问题，PaddleDetection更新到最新release/2.2或者develop版本，Paddle更新到2.1.1再试下还有问题没
