### ISSUE TITLE
测试paddle serving所使用的test_client.py是否应该对图像进行标准化

### ISSUE THREAD

**Issue by firedent** [PaddlePaddle/PaddleDetection#3804]
https://github.com/PaddlePaddle/PaddleDetection/blob/f53e8f7f48d5f952d487da8ea75f6793086156da/deploy/serving/test_client.py#L20-L24
PaddleDetection大多数模型在训练时都对数据进行了归一化操作，在预测时也应该对传入的数据进行归一化。

**Comment by yghstill** [comment]
@firedent Div(255.0)就是归一化。

**Comment by firedent** [comment]
@yghstill 应该说是缺少标准化（Standardization）。根据文档[3.1数据增强算子](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/advanced_tutorials/READER.md#31%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA%E7%AE%97%E5%AD%90)表格第四项：`NormalizeImage`，PaddleDetection在对数据预处理的时候，先对所有像素值除以255进行feature scaling，之后会对三个通道按照
https://github.com/PaddlePaddle/PaddleDetection/blob/f53e8f7f48d5f952d487da8ea75f6793086156da/configs/ppyolo/_base_/ppyolo_reader.yml#L17
进行标准化（Standardization）。test_clinet.py只是对像素值div(255)，缺少标准化（Standardization）的过程。

**Comment by liuhuiCNN** [comment]
> @yghstill 应该说是缺少标准化（Standardization）。根据文档[3.1数据增强算子](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/advanced_tutorials/READER.md#31%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA%E7%AE%97%E5%AD%90)表格第四项：`NormalizeImage`，PaddleDetection在对数据预处理的时候，先对所有像素值除以255进行feature scaling，之后会对三个通道按照
> https://github.com/PaddlePaddle/PaddleDetection/blob/f53e8f7f48d5f952d487da8ea75f6793086156da/configs/ppyolo/_base_/ppyolo_reader.yml#L17
> 
> 
> 进行标准化（Standardization）。test_clinet.py只是对像素值div(255)，缺少标准化（Standardization）的过程。

这里需要根据算法预处理自定义配置。

**Comment by firedent** [comment]
> > @yghstill 应该说是缺少标准化（Standardization）。根据文档[3.1数据增强算子](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/advanced_tutorials/READER.md#31%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA%E7%AE%97%E5%AD%90)表格第四项：`NormalizeImage`，PaddleDetection在对数据预处理的时候，先对所有像素值除以255进行feature scaling，之后会对三个通道按照
> > https://github.com/PaddlePaddle/PaddleDetection/blob/f53e8f7f48d5f952d487da8ea75f6793086156da/configs/ppyolo/_base_/ppyolo_reader.yml#L17
> > 
> > 进行标准化（Standardization）。test_clinet.py只是对像素值div(255)，缺少标准化（Standardization）的过程。
> 
> 这里需要根据算法预处理自定义配置。

确实
在`PaddleDetection/configs/`里中一共有21个文件夹是实例配置文件，其中17个都用到了标准化，是不是应该把进行标准化作为test_client.py的默认选项？

**Comment by liuhuiCNN** [comment]
> > > @yghstill 应该说是缺少标准化（Standardization）。根据文档[3.1数据增强算子](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/advanced_tutorials/READER.md#31%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA%E7%AE%97%E5%AD%90)表格第四项：`NormalizeImage`，PaddleDetection在对数据预处理的时候，先对所有像素值除以255进行feature scaling，之后会对三个通道按照
> > > https://github.com/PaddlePaddle/PaddleDetection/blob/f53e8f7f48d5f952d487da8ea75f6793086156da/configs/ppyolo/_base_/ppyolo_reader.yml#L17
> > > 
> > > 进行标准化（Standardization）。test_clinet.py只是对像素值div(255)，缺少标准化（Standardization）的过程。
> > 
> > 
> > 这里需要根据算法预处理自定义配置。
> 
> 确实
> 在`PaddleDetection/configs/`里中一共有21个文件夹是实例配置文件，其中17个都用到了标准化，是不是应该把进行标准化作为test_client.py的默认选项？

感谢建议。本issue问题已解决，先关闭了。
