### ISSUE TITLE
AssertionError: the module BlazeFace is not registered

### ISSUE THREAD

**Issue by watertianyi** [PaddlePaddle/PaddleDetection#3806]
AssertionError: the module BlazeFace is not registered?
已经按照人脸检测的说明下载了模型，放到对应的目录下，为什么会出现上述情况呢，很着急

**Comment by yghstill** [comment]
@hande6688 更新代码至release/2.1以上，如果本地安装了paddledet，卸载后再进行操作

**Comment by watertianyi** [comment]
我的paddle就是2.1，docker部署的，验证了没有问题，就是人脸检测有问题

**Comment by yghstill** [comment]
@hande6688 运行命令是什么？PaddleDetection的代码是release/2.1分支吗？是否pip install paddledet?

**Comment by hande6688** [comment]
运行命令：python tools/infer.py -c configs/face_detection/blazeface_1000e.yml -o use_gpu=true weights=output/blazeface_1000e.pdparams --infer_img=demo/hrnet_demo.jpg

**Comment by hande6688** [comment]
>>> import paddle
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
>>> print(paddle.__version__)
2.1.1
pip install paddledet==2.1.0 -i https://mirror.baidu.com/pypi/simple

**Comment by hande6688** [comment]
git clone https://github.com/PaddlePaddle/PaddleDetection.git
cd PaddleDetection

**Comment by yghstill** [comment]
@hande6688 把paddledet卸载了，pip uninstall paddledet
因为BlazeFace的更新没有放入paddledet安装包中，直接源码运行即可

**Comment by hande6688** [comment]
可以给个参考吗，怎么运行BlazeFace

**Comment by watertianyi** [comment]
可以运行了，谢谢！
