### ISSUE TITLE
LearningRate直接使用Paddle框架的MultiStepDecay

### ISSUE THREAD

**Issue by songrui2009** [PaddlePaddle/PaddleDetection#3808]
在Optimizer.yml配置LearningRate使用Paddle的MultiStepDecay；框架中LearningRate.__call__依赖schedulers[0].use_warmup成员变量；Paddle的MultiStepDecay没有

**Comment by heavengate** [comment]
PaddleDetection里有队optimizer做一层封装，封装代码在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/optimizer.py
这个文件里面，如果你要用自定义optimizer的话可以在这个下面参考一下加一下封装。
另外，我们封装好的`PiecewiseDecay`是支持multi step decay，也可以用这个
