### ISSUE TITLE
paddle如何指定GPU进行训练？

### ISSUE THREAD

**Issue by lihui669** [PaddlePaddle/PaddleDetection#3809]
paddle默认GPU的序号为0，我想用GPU 2 来训练
我在train中加入了指令：os.environ["CUDA_VISIBLE_DEVICES"] = '2'，但是训练时依然用的是GPU0,请问在哪里指定GPU训练呢？

**Comment by nemonameless** [comment]
```
CUDA_VISIBLE_DEVICES=2 python **.py
```
指定GPU训练和是什么框架无关的。

**Comment by heavengate** [comment]
`export CUDA_VISIBLE_DEVICES=2`或者`CUDA_VISIBLE_DEVICES=2 python tools/train.py ...`
