### ISSUE TITLE
solov2 实现对单个类别的实例分割，训练过程中map一直为0

### ISSUE THREAD

**Issue by liuxi1007** [PaddlePaddle/PaddleDetection#3810]
### 数据集
对某单个类别进行实例分割，数据集标签只包含一个类别，一张图像中有多个此类别的物体，要求分割出来。
### 训练
PaddleDetection release/2.2版本，数据集标签只包含一个类别的样本，训练loss下降至0.07，可视化结果中mask-map始终为0.
### 疑问
请问这种现象是怎么回事，如何应对？这种情况下的map如何计算？请问是否这种现象与difficult参数有关，还是其他原因？

**Comment by yghstill** [comment]
@liuxi1007 PaddleDetection是哪个版本？更新到最新release/2.2或者develop版本后再训练试下，修复了一个num_classes的问题

**Comment by liuxi1007** [comment]
PaddleDetection release/2.2版本，数据集标签只包含一个类别的样本，训练loss下降至0.07，可视化结果中mask-map始终为0

**Comment by liuxi1007** [comment]
请问是否这种现象与difficult参数有关，还是其他原因？

**Comment by liuxi1007** [comment]
> @liuxi1007 PaddleDetection是哪个版本？更新到最新release/2.2或者develop版本后再训练试下，修复了一个num_classes的问题

PaddleDetection release/2.2版本，数据集标签只包含一个类别的样本，训练loss下降至0.07，可视化结果中mask-map始终为0
请问是否这种现象与difficult参数有关，还是其他原因？

**Comment by liuxi1007** [comment]
您好，使用新版本后依然验证map出不来,loss看上去是正常的。您看是不是数据集需要分割的物体只有一个类别导致的？是否是代码有bug?目前用的是release-2.2版本。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Guanghua Yu ***@***.***&gt;
发送时间: 2021年7月29日 11:00
收件人: PaddlePaddle/PaddleDetection ***@***.***&gt;
抄送: liuxi1007 ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[PaddlePaddle/PaddleDetection] solov2 实现对单个类别的实例分割，训练过程中map一直为0 (#3810)





 
@liuxi1007 PaddleDetection是哪个版本？更新到最新release/2.2或者develop版本后再训练试下，修复了一个num_classes的问题
