### ISSUE TITLE
eval时候报错

### ISSUE THREAD

**Issue by Weilongxin** [PaddlePaddle/PaddleDetection#3811]
W0723 16:30:03.859206 1127 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0723 16:30:03.864948 1127 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2021-07-23 16:30:12,625-INFO: Test iter 0
2021-07-23 16:30:14,206-INFO: Test finish iter 91
2021-07-23 16:30:14,206-INFO: Total number of images: 91, inference time: 50.773135477533835 fps.
2021-07-23 16:30:14,206-INFO: Start evaluate...
Traceback (most recent call last):
File "/home/aistudio/work/PaddleDetection/static/tools/eval.py", line 206, in
main()
File "/home/aistudio/work/PaddleDetection/static/tools/eval.py", line 188, in main
save_only=save_only)
File "/home/aistudio/work/PaddleDetection/static/ppdet/utils/eval_utils.py", line 267, in eval_results
map_type=map_type)
File "/home/aistudio/work/PaddleDetection/static/ppdet/utils/voc_eval.py", line 71, in bbox_eval
gt_boxes = t['gt_bbox'][0]
KeyError: 'gt_bbox'

这个是什么原因呢？有什么解决办法吗？

**Comment by Weilongxin** [comment]
W0729 11:04:00.202333   215 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0729 11:04:00.217445   215 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2021-07-29 11:04:07,360-INFO: Test iter 0
2021-07-29 11:04:07,955-INFO: Test finish iter 91
2021-07-29 11:04:07,955-INFO: Total number of images: 91, inference time: 115.43642903524443 fps.
2021-07-29 11:04:07,955-INFO: Start evaluate...
Traceback (most recent call last):
  File "/home/aistudio/work/PaddleDetection/static/tools/eval.py", line 206, in <module>
    main()
  File "/home/aistudio/work/PaddleDetection/static/tools/eval.py", line 188, in main
    save_only=save_only)
  File "/home/aistudio/work/PaddleDetection/static/ppdet/utils/eval_utils.py", line 267, in eval_results
    map_type=map_type)
  File "/home/aistudio/work/PaddleDetection/static/ppdet/utils/voc_eval.py", line 71, in bbox_eval
    gt_boxes = t['gt_bbox'][0]
KeyError: 'gt_bbox'
terminate called without an active exception
W0729 11:04:08.110780   319 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0729 11:04:08.110821   319 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0729 11:04:08.110832   319 init.cc:231] The detail failure signal is:

W0729 11:04:08.110843   319 init.cc:234] *** Aborted at 1627527848 (unix time) try "date -d @1627527848" if you are using GNU date ***
W0729 11:04:08.112418   319 init.cc:234] PC: @                0x0 (unknown)
W0729 11:04:08.113185   319 init.cc:234] *** SIGABRT (@0x3e8000000d7) received by PID 215 (TID 0x7f0edaffd700) from PID 215; stack trace: ***
W0729 11:04:08.114389   319 init.cc:234]     @     0x7f0fd01e0390 (unknown)
W0729 11:04:08.115391   319 init.cc:234]     @     0x7f0fcfe3a428 gsignal
W0729 11:04:08.116417   319 init.cc:234]     @     0x7f0fcfe3c02a abort
W0729 11:04:08.120820   319 init.cc:234]     @     0x7f0f90bb084a __gnu_cxx::__verbose_terminate_handler()
W0729 11:04:08.121601   319 init.cc:234]     @     0x7f0f90baef47 __cxxabiv1::__terminate()
W0729 11:04:08.122815   319 init.cc:234]     @     0x7f0f90baef7d std::terminate()
terminate called recursively
W0729 11:04:08.123505   319 init.cc:234]     @     0x7f0f90baec5a __gxx_personality_v0
W0729 11:04:08.125030   319 init.cc:234]     @     0x7f0f90ee1b97 _Unwind_ForcedUnwind_Phase2
W0729 11:04:08.125988   319 init.cc:234]     @     0x7f0f90ee1e7d _Unwind_ForcedUnwind
W0729 11:04:08.127045   319 init.cc:234]     @     0x7f0fd01df070 __GI___pthread_unwind
W0729 11:04:08.128049   319 init.cc:234]     @     0x7f0fd01d7845 __pthread_exit
W0729 11:04:08.132735   319 init.cc:234]     @     0x559100f7de59 PyThread_exit_thread
W0729 11:04:08.132870   319 init.cc:234]     @     0x559100e03c17 PyEval_RestoreThread.cold.798
W0729 11:04:08.133757   319 init.cc:234]     @     0x7f0fc432f29c (unknown)
W0729 11:04:08.134829   319 init.cc:234]     @     0x559100eff744 _PyMethodDef_RawFastCallKeywords
W0729 11:04:08.135073   319 init.cc:234]     @     0x559100eff861 _PyCFunction_FastCallKeywords
W0729 11:04:08.135298   319 init.cc:234]     @     0x559100f6b2bd _PyEval_EvalFrameDefault
W0729 11:04:08.135510   319 init.cc:234]     @     0x559100eaf539 _PyEval_EvalCodeWithName
W0729 11:04:08.135715   319 init.cc:234]     @     0x559100eb0635 _PyFunction_FastCallDict
W0729 11:04:08.135929   319 init.cc:234]     @     0x559100ecee53 _PyObject_Call_Prepend
W0729 11:04:08.136041   319 init.cc:234]     @     0x559100f06a3a slot_tp_call
W0729 11:04:08.136245   319 init.cc:234]     @     0x559100f078fb _PyObject_FastCallKeywords
W0729 11:04:08.136469   319 init.cc:234]     @     0x559100f6ae86 _PyEval_EvalFrameDefault
W0729 11:04:08.136674   319 init.cc:234]     @     0x559100eb056b _PyFunction_FastCallDict
W0729 11:04:08.136871   319 init.cc:234]     @     0x559100ecee53 _PyObject_Call_Prepend
W0729 11:04:08.136981   319 init.cc:234]     @     0x559100f06a3a slot_tp_call
W0729 11:04:08.137181   319 init.cc:234]     @     0x559100f078fb _PyObject_FastCallKeywords
W0729 11:04:08.137463   319 init.cc:234]     @     0x559100f6b6e8 _PyEval_EvalFrameDefault
W0729 11:04:08.137679   319 init.cc:234]     @     0x559100eaf539 _PyEval_EvalCodeWithName
W0729 11:04:08.137883   319 init.cc:234]     @     0x559100eb0635 _PyFunction_FastCallDict
W0729 11:04:08.138082   319 init.cc:234]     @     0x559100ecee53 _PyObject_Call_Prepend
W0729 11:04:08.138300   319 init.cc:234]     @     0x559100ec1dbe PyObject_Call
Aborted (core dumped)

**Comment by heavengate** [comment]
你修改了配置么，看着是读取数据集的时候没有把gt_box带出来，是否修改了数据集相关的配置

**Comment by Weilongxin** [comment]
> 你修改了配置么，看着是读取数据集的时候没有把gt_box带出来，是否修改了数据集相关的配置

是在哪修改配置呢，好像是没修改数据集配置

**Comment by heavengate** [comment]
看报错是没找到`gt_box`字段，如果你没修改配置的话是不是使用了自定义的数据集，数据集里没包含这个字段
