### ISSUE TITLE
对labelme转成coco数据集有疑惑

### ISSUE THREAD

**Issue by zxsitu** [PaddlePaddle/PaddleDetection#3815]
开发者您好，我打算使用labelme去标注2000张图片，标注框的格式为矩形，但是这2000张图片我是设置好标注顺序的，所以不希望转换成coco格式时顺序被shuffle掉。
我打算使用[x2coco.py](https://github.com/PaddlePaddle/PaddleDetection/blob/f53e8f7f48d5f952d487da8ea75f6793086156da/tools/x2coco.py)将标注好的json文件分三次转换，第一次全部转成训练集1600张，第二次是验证集200张，第三次测试集200张。我看您的[教程](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/PrepareDataSet.md#%E7%94%A8%E6%88%B7%E6%95%B0%E6%8D%AE%E6%95%B0%E6%8D%AE%E8%BD%AC%E6%8D%A2%E7%A4%BA%E4%BE%8B)上面有提到下面的代码，因此请问我可以这样设置吗？然后分三次去运行x2coco.py文件。
```
python tools/x2coco.py \
                --dataset_type labelme \
                --json_input_dir ./labelme_annos/ \
                --image_input_dir ./labelme_imgs/ \
                --output_dir ./cocome/ \
                --train_proportion 0.8 \    <----第一次可以设置这个为1.0吗？
                --val_proportion 0.2 \      <----第二次可以设置这个为1.0吗？
                --test_proportion 0.0       <----第三次可以设置这个为1.0吗？
```

另外还有一点疑惑，就是转成coco格式后，id的编号似乎是跟标注出现的先后顺序有关，比如第一张图的第一个标注框是苹果，那id：0就是苹果，但如果我的测试集第一张的第一个标注框是梨，那id：0则代表了梨。运行时会检测不出对象甚至报错，请问有办法解决吗？实在不行那我调整数据集内的图片先后顺序。谢谢！

**Comment by heavengate** [comment]
是想指定coco数据集的类别顺序么？这个确实没有支持，我们排期支持一下~ 目前的话是按图片输入顺序解析类别的，可以先调整一下图片顺序规避一下

**Comment by ilem777** [comment]
@heavengate 嗯嗯，如果您能开发这个功能会更好，锦上添花。

另外咨询一下，我如果分三次运行tools/x2coco.py，其中第一次--train_proportion 1.0；第二次--val_proportion 1.0；第三次--test_proportion 1.0
请问一下可不可以正常的生成：instance_train.json，instance_val.json，instance_test.json文件呢？因为正如我前述的，我三个数据集拆开来放了，所以不清楚这样设置指令能不能正常运行。
