### ISSUE TITLE
Yolov5 后处理层不支持

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/PaddleDetection#3818]
问题描述：
1、pytorch训练模型，导出onnx，再转到paddle，paddle模型没有实现yolov5后处理部分（解码+nms），请问怎么实现呢？

**Comment by heavengate** [comment]
nms我们有MultiClassNMS，解码部分的话跟这个YOLOv3Head部分应该是基本一致的，如果要用的话可以结合这个组一下
https://github.com/PaddlePaddle/PaddleDetection/blob/f53e8f7f48d5f952d487da8ea75f6793086156da/ppdet/modeling/heads/yolo_head.py#L17
另外PaddleDetection里开源了PP-YOLOv2模型，精度速度也是由于yolov5，也可以试下这个
