### ISSUE TITLE
test_client.py中scale_factor设置为固定数

### ISSUE THREAD

**Issue by firedent** [PaddlePaddle/PaddleDetection#3819]
根据文档[导出模输入输出说明](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_MODEL.md#1%E5%AF%BC%E5%87%BA%E6%A8%A1%E8%BE%93%E5%85%A5%E8%BE%93%E5%87%BA%E8%AF%B4%E6%98%8E)，`scale_factor`应为输入图像大小与真实图像大小之比，虽然本示例将目标框长宽的转换移到了`RCNNPostprocess`里，但是直接把scale_factor定死很容易让使用者产生误解，而且和参数本意不符。
https://github.com/PaddlePaddle/PaddleDetection/blob/383ffa1491269c7aaa9f2df95029a82c028a7140/deploy/serving/test_client.py#L37

**Comment by liuhuiCNN** [comment]
感谢反馈，这里是参考：https://github.com/PaddlePaddle/Serving/blob/8e88e89be0fc738f40be1f5b4722d09db88fb960/python/examples/detection/yolov3_darknet53_270e_coco/test_client.py#L37 ，后续我们会跟serving同步优化。

**Comment by Viserion-nlper** [comment]
遇到了同样问题，请问是否有解决方法
