### ISSUE TITLE
使用c++推理部署，windows平台vs2019编译时报错

### ISSUE THREAD

**Issue by HoyTiger** [PaddlePaddle/PaddleDetection#382]
报错如下

![image](https://user-images.githubusercontent.com/42536260/77298306-b5d3de00-6d25-11ea-968b-5417709fe92c.png)
找不到以上文件/目录，不知道什么问题

**Comment by sjtubinlong** [comment]
@HoyTiger 你好，试试把图中`生成+Intelisense`改成 `仅生成`

**Comment by HoyTiger** [comment]
> @HoyTiger 你好，试试把图中`生成+Intelisense`改成 `仅生成`

你好这样并没有解决问题

**Comment by HoyTiger** [comment]
运行下面这个命令并没有找到输出的图片，
`.\detection_demo.exe` --conf=conf\detection_rcnn.yaml --input_dir=images\detection_rcnn\
![image](https://user-images.githubusercontent.com/42536260/77437384-90c39600-6e1f-11ea-8003-0ff90396dd6e.png)

**Comment by sjtubinlong** [comment]
@HoyTiger 
您好，产出的不是一个结果图片，是一个pb文件，在输入图片同级目录下，需要使用python再进行可视化。这块我们新版本已经优化，可以C++直接产出结果。

如果还有问题，能否提供下您的windows下编译产出的整个release目录，我们这边可以帮忙测试一下是什么问题。

**Comment by JianJingGao** [comment]
> > @HoyTiger 你好，试试把图中`生成+Intelisense`改成 `仅生成`
> 
> 你好这样并没有解决问题

我换了一台电脑于是解决了问题，也可以采用手册中VS2015提供的方法

**Comment by HoyTiger** [comment]
> @HoyTiger
> 您好，产出的不是一个结果图片，是一个pb文件，在输入图片同级目录下，需要使用python再进行可视化。这块我们新版本已经优化，可以C++直接产出结果。
> 
> 如果还有问题，能否提供下您的windows下编译产出的整个release目录，我们这边可以帮忙测试一下是什么问题。
你好，我采用手册vs2015的方法也是没有输出结果的。release目录在下面的百度网盘中。
链接：https://pan.baidu.com/s/1M0LwttMjGMpLQK4dWuF8yQ 
提取码：2lji

**Comment by HoyTiger** [comment]
> @HoyTiger
> 您好，产出的不是一个结果图片，是一个pb文件，在输入图片同级目录下，需要使用python再进行可视化。这块我们新版本已经优化，可以C++直接产出结果。
> 
> 如果还有问题，能否提供下您的windows下编译产出的整个release目录，我们这边可以帮忙测试一下是什么问题。

如果还有问题，能否提供下您的windows下编译产出的整个release目录，我们这边可以帮忙测试一下是什么问题。
你好，我采用手册vs2015的方法也是没有输出结果的。release目录在下面的百度网盘中。
链接：https://pan.baidu.com/s/1M0LwttMjGMpLQK4dWuF8yQ
提取码：2lji

**Comment by qingqing01** [comment]
@HoyTiger 由于时间较久，关闭此issue，有问题，可以开新的issue
