### ISSUE TITLE
在使用 python ppdet/modeling/tests/test_architectures.py 命令时出现这个问题  if data.dtype == np.object:

### ISSUE THREAD

**Issue by yyyssq** [PaddlePaddle/PaddleDetection#3820]
aistudio@jupyter-701037-2225957:~/PaddleDetection-2.0/PaddleDetection-release-2.0$ python ppdet/modeling/tests/test_architectures.py
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0729 15:33:29.725375  3044 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0729 15:33:29.731137  3044 device_context.cc:422] device: 0, cuDNN Version: 7.6.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
.....
----------------------------------------------------------------------
Ran 5 tests in 3.678s

OK

我使用的是aistudio平台  环境为paddle2.0版本，当然paddle2.1版本我也遇到了同样的问题。python版本为3.7

**Comment by heavengate** [comment]
```
Ran 5 tests in 3.678s

OK
```

测试是跑成功了的，上面那个是个warning，不影响模型正常运行。
