### ISSUE TITLE
关于mask分支的修改

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#383]
想将mask分支 放在FPN和RPN之间      该如何操作呢

**Comment by qingqing01** [comment]
@shuxsu 你是想在RPN后面直接加mask分支？

**Comment by shuxsu** [comment]
> @shuxsu 你是想在RPN后面直接加mask分支？

是的 想参考一步法的目标检测  直接将FPN出来的 进行一个大概的mask  然后在通过RPN  精确定个位

**Comment by jerrywgz** [comment]
原本的mask分支是基于rpn得到的roi进行筛选得到target，再经过roi align得到feature map作为mask 分支的输入，对应shape是[roi_num, C, 14, 14]，这其中mask_assigner和roi align是必须的，负责无法进行loss的计算。想问下你是希望具体省略哪些步骤呢？

**Comment by shuxsu** [comment]
> 原本的mask分支是基于rpn得到的roi进行筛选得到target，再经过roi align得到feature map作为mask 分支的输入，对应shape是[roi_num, C, 14, 14]，这其中mask_assigner和roi align是必须的，负责无法进行loss的计算。想问下你是希望具体省略哪些步骤呢？

因为现在的RPN提取 是通过滑动框  一个个进行筛选  想省去这个过程  通过初步出来的FPN  进行一次mask  通过这个mask 去进入RPN的roi  省去那些滑动筛选的过程

**Comment by jerrywgz** [comment]
那可以直接通过anchor和rpn部分的回归分支做decode得到roi然后直接做roi align，输出进mask分支。这样可以省去筛选的过程
