### ISSUE TITLE
ppdet.utils.download INFO: Downloading train2017.zip from http://images.cocodataset.org/zips/train2017.zip   0%|自动下载训练集

### ISSUE THREAD

**Issue by yyyssq** [PaddlePaddle/PaddleDetection#3830]
我是voc 转的coco数据集 生成了voc_train.json 和 voc_test.json两个文件

数据Tree如下：

dataset
     coco
         annotations
             voc_train.json
             voc_test.json
         JPEGImages
             若干图片.jpeg

faster_fpn_reader.yml文件配置如下：

worker_num: 12
TrainReader:
  dataset:
     !COCODataSet
     image_dir: ./dataset/coco/JPEGImages/
     anno_path: annotations/voc_train.json
     dataset_dir: ./dataset/coco/
     #with_background: true
  sample_transforms:
  - Decode: {}
  - RandomResize: {target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], interp: 2, keep_ratio: True}
  - RandomFlip: {prob: 0.5}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32, pad_gt: true}
  batch_size: 1
  shuffle: true
  drop_last: true

EvalReader:
  dataset:
     !COCODataSet
     image_dir: ./dataset/coco/JPEGImages/
     anno_path: annotations/voc_test.json
     dataset_dir: ./dataset/coco/
     #with_background: true
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32, pad_gt: false}
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false

TestReader:
  dataset:
      !COCODataSet
      image_dir: ./dataset/coco/JPEGImages/
     anno_path: annotations/voc_test.json
     dataset_dir: ./dataset/coco/
      #with_background: true
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32, pad_gt: false}
  batch_size: 1
  shuffle: false
  drop_last: false

faster_reader.yml文件配置如下：

worker_num: 12
TrainReader:
  dataset:
     !COCODataSet
     image_dir: ./dataset/coco/JPEGImages/
     anno_path: annotations/voc_train.json
     dataset_dir: ./dataset/coco/
     #with_background: true
  sample_transforms:
  - Decode: {}
  - RandomResize: {target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], interp: 2, keep_ratio: True}
  - RandomFlip: {prob: 0.5}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: -1, pad_gt: true}
  batch_size: 1
  shuffle: true
  drop_last: true

EvalReader:
  dataset:
     !COCODataSet
     image_dir: ./dataset/coco/JPEGImages/
     anno_path: annotations/voc_test.json
     dataset_dir: ./dataset/coco/
     #with_background: true
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: -1, pad_gt: false}
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false

TestReader:
  dataset:
     !COCODataSet
     image_dir: ./dataset/coco/JPEGImages/
     anno_path: annotations/voc_test.json
     dataset_dir: ./dataset/coco/
     #with_background: true
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: -1}
  batch_size: 1
  shuffle: false
  drop_last: false

按照以上配置，训练时候自动下载train2017数据集。希望大佬给解答一波。感激不尽

**Comment by jerrywgz** [comment]
TrainReader EvalReader的image_dir设置成JPEGImages即可

**Comment by jerrywgz** [comment]
在触发自动下载之前会有路径没有找到的日志，可以作为参考

**Comment by yyyssq** [comment]
> 在触发自动下载之前会有路径没有找到的日志，可以作为参考

在触发前确实有一条警告产生 警告如下
ppdet.utils.download WARNING: Config image_dir dataset/coco/train2017 is not a directory, dataset config is not valid

我在yml中没有关于这样的配置 image_dir 的配置是 这样的
TrainReader:
  dataset:
     !COCODataSet
     dataset_dir: ./dataset/coco/
     image_dir: JPEGImages
     anno_path: annotations/instances_train2017.json

EvalReader:
  dataset:
     !COCODataSet
     dataset_dir: ./dataset/coco/
     image_dir: JPEGImages
     anno_path: annotations/instances_test2017.json

TestReader:
  dataset:
     !COCODataSet
     dataset_dir: ./dataset/coco/
     image_dir: JPEGImages
     anno_path: annotations/instances_test2017.json

在项目中的文件夹路径是
dataset
       coco
           JPEGImages
               若干图片.jpeg
           annotations
               instances_train2017.json
               instances_test2017.json

**Comment by jerrywgz** [comment]
需要先确认下reader文件是否是你实际配置的，看起来用的还是默认coco的数据路径
