### ISSUE TITLE
[Other General Issues]关于在Paddledetection使用中遇到的问题

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleDetection#3847]
最近在学习使用paddleDetection进行目标检测，十分感谢飞桨提供的paddleDetection，方便了我这种小白，但是在使用过程中还是遇到了一些问题，希望可以完善一下（我主要是在paddledetection2.1中使用cascade rcnn）。

### bug：
**MultiscaleTestResize出错**
复现方式：在配置文件configs/cascade_rcnn/_base_/cascade_rcnn_r50_fpn.yml中，
将Resize替换为MultiscaleTestResize: {origin_target_size: [1600, 1333], target_size: [[1280, 2666], [1344, 2666], [1408, 2666], [1472, 2666], [1536, 2666], [1600, 2666]]}

### 缺少的功能：
SWA/随机加权平均、Soft NMS、WBF/权重框融合、DetectoRS：RFP-SAC

**SWA**
可以稳定提升目标检测AP指标，知乎参考：https://zhuanlan.zhihu.com/p/341190337 ；论文：https://arxiv.org/abs/2012.12645 ；pytorch代码：https://hub.fastgit.org//timgaripov/swa     https://pytorch.org/blog/stochastic-weight-averaging-in-pytorch/
SWA在比赛、项目实践中都有不错表现，强烈建议官方考虑实现下

**Soft NMS**
提高预测精度，知乎参考：https://zhuanlan.zhihu.com/p/41046620 ；论文：https://arxiv.org/abs/1704.04503 ；

**WBF/权重框融合**
多模型集成方法，参考：https://blog.csdn.net/weixin_42990464/article/details/108204282 ；论文：https://arxiv.org/pdf/1910.13302.pdf，
在Paddledetection中没有找到多模型集成的相关文档、代码，目前我也只了解到一种多模型集成方法，如果可能的话，希望官方考虑下这方面内容

**DetectoRS：RFP-SAC**
听同学介绍的一种由于cascade rcnn的目标检测网络，希望有机会在paddledetection上体验下，参考：https://blog.csdn.net/weixin_45798949/article/details/107362285 ，论文：https://arxiv.org/abs/2006.02334 ，torch代码：https://github.com/joe-siyuan-qiao/DetectoRS

### 其他问题：
**Matrix NMS不能再cascade rcnn中使用**
似乎是因为RCNNBox输出结果不能与Matrix NMS输入匹配？如果可以使用的话，麻烦官方可以给个在cascade rcnn中使用Matrix NMS的配置文件示例

**CBResNet模型缺失**
在readme中比较亮眼的CBResNet没有在动态图中实现，有些可惜

**backbone查找替换文档**
paddledetection中包含了许多backbone，但是我在使用过程中感觉替换起来很麻烦，希望可以出个单独的所有backbone及预训练文档方便新手学习替换backbone(一些ssd、dcn之类的也可以一起放在里面)

**关键点检测 eval**
此外，前两天试验了下人体关键点检测，在运行eval.py时，不能使用save_prediction_only导出预测json结果

最后，祝飞桨越来越好，Paddledetection可以成为最好用的目标检测工具

**Comment by yghstill** [comment]
@huilin16 非常感谢详细的反馈和建议，
1. 关于MultiscaleTestResize，目前在动态图中没有支持完善，我们后续将排期完善。
2. 关于Matrix NMS，在RCNN模型中也没有测试过，这个也作为一个需求进行补充。
3. 关于CBResNet的backbone 和backbone替换的教程文档的反馈我们也会后续支持。
4. 关键点等其他模型save_prediction_only这个功能也会增强下。
5. 关于缺失的功能SWA、多模型融合、DetectoRS等新的功能，也会后续调研下，如果可以会陆续支持。
