### ISSUE TITLE
[Other General Issues]TTFNet相关问题

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#3853]
在TTF的训练中，TrainReader读入数据data后，打印data的内容为data:{'im_id', 'curr_iter', 'image', 'im_shape', 'scale_factor', 'ttf_heatmap', 'ttf_box_target', 'ttf_reg_weight'}。请问ttf_heatmap\ttf_box_target\ttf_reg_weight 这3者是根据标注得到的结果嘛？还有他们的计算写在哪里呢，我debug步进也没有看到，是预处理嘛？
THX！

**Comment by nemonameless** [comment]
是预处理，Gt2TTFTarget，代码在https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/transform/batch_operators.py#L598
所有的预处理代码都位于ppdet/data/transform，可以全局搜ttf_heatmap就能找到相关代码了，static目录下的是以前的静态图代码可以不用看。

**Comment by ghost** [comment]
> 是预处理，Gt2TTFTarget，代码在https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/transform/batch_operators.py#L598
> 所有的预处理代码都位于ppdet/data/transform，可以全局搜ttf_heatmap就能找到相关代码了，static目录下的是以前的静态图代码可以不用看。

好的，我去看看，十分感谢！
