### ISSUE TITLE
S2anet mAP=0

### ISSUE THREAD

**Issue by yumeng88** [PaddlePaddle/PaddleDetection#3861]
S2anet   mAP=0
问题：使用s2anet训练多个数据集，数据集格式都保持一样，只有一个数据集的map可以达到4.8，其余数据集的map都是零，无论是边训练边评估还是训练完成后评估，想问一下可能的原因啊？检测效果也是没有。 
边训练便评估会出现
![image](https://user-images.githubusercontent.com/56550062/127822091-ec8b1d0f-95eb-4467-9bf4-c74adab95437.png)
查询资料讲有可能是png格式导致的错误，但是我的图片全是.jpg

**Comment by yumeng88** [comment]
![image](https://user-images.githubusercontent.com/56550062/127822333-83d21ddf-6a94-4c02-899d-36779f8ac0ac.png)

**Comment by wangxinxin08** [comment]
mAP为4.8也比较低，建议先检查下数据和标注文件，比如把标注文件可视化在图片上
