### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/PaddleDetection#3864]
联合PP-YOLOV2与Hrnet模型推理
# [联合部署推理] 使用命令如下:
!python deploy/python/keypoint_det_unite_infer.py --det_model_dir=output_inference/ppyolov2_r50vd_dcn_voc/ \
--keypoint_model_dir=output_inference/hrnet_w32_384x288/ --video_file=../../Test/test.mp4  --use_gpu=True

报出日志
-----------  Running Arguments -----------
camera_id: -1
cpu_threads: 1
det_model_dir: output_inference/ppyolov2_r50vd_dcn_voc/
det_threshold: 0.5
enable_mkldnn: False
image_dir: None
image_file: None
keypoint_model_dir: output_inference/hrnet_w32_384x288/
keypoint_threshold: 0.5
output_dir: output
run_benchmark: False
run_mode: fluid
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dynamic_shape: False
use_gpu: True
video_file: ../../Test/test.mp4
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
I0802 16:04:17.733971   528 analysis_config.cc:424] use_dlnne_:0
I0802 16:04:17.734045   528 analysis_config.cc:424] use_dlnne_:0
I0802 16:04:17.734071   528 analysis_config.cc:424] use_dlnne_:0
I0802 16:04:17.734083   528 analysis_config.cc:424] use_dlnne_:0
-----------  Model Configuration -----------
Model Arch: HRNet
Transform Order: 
--transform op: TopDownEvalAffine
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
detect frame:1
Traceback (most recent call last):
  File "deploy/python/keypoint_det_unite_infer.py", line 199, in <module>
    main()
  File "deploy/python/keypoint_det_unite_infer.py", line 186, in main
    FLAGS.camera_id)
  File "deploy/python/keypoint_det_unite_infer.py", line 130, in topdown_unite_predict_video
    batch_images, FLAGS.keypoint_threshold)
  File "/home/aistudio/work/PaddleDetection/deploy/python/keypoint_infer.py", line 128, in predict
    inputs = self.preprocess(image)
  File "/home/aistudio/work/PaddleDetection/deploy/python/keypoint_infer.py", line 85, in preprocess
    preprocess_ops.append(eval(op_type)(**new_op_info))
  File "<string>", line 1, in <module>
**NameError: name 'TopDownEvalAffine' is not defined**

我训练的是PPYOLOV2的VOC格式 ，Det推理没问题。 与这个Hrnet联合推理抱这个问题 之前也问过 但是要我更新，这次是最新的了还是这样，请问怎么解决呢

**Comment by wangxinxin08** [comment]
可以在deploy/python/keypoint_infer.py加上以下两行代码试下，检测和keypoint的联合部署将会在PaddleDectection release/2.2正式支持
``` python
from keypoint_preprocess import *
from preprocess import *
```

**Comment by Wei-JL** [comment]
> 可以加上以下两行代码试下
> 
> ```python
> from keypoint_preprocess import *
> from preprocess import *
> ```

我试试看哦 稍等

**Comment by Wei-JL** [comment]
> 可以在deploy/python/keypoint_infer.py加上以下两行代码试下，检测和keypoint的联合部署将会在PaddleDectection release/2.2正式支持
> 
> ```python
> from keypoint_preprocess import *
> from preprocess import *
> ```

谢谢 ，确实可以联合推理了 但是推理出来只有检测框没有关键点 ，是因为我的模型训练的不够好吗

**Comment by wangxinxin08** [comment]
你可以试下是我们提供的官方模型，看下检测效果如何
