### ISSUE TITLE
TTFNet训练过程中hm_loss的疑问

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#3877]
我最近在TTFNet的训练过程中遇到一些问题
当我使用1200张图片的单类别小数据集测试TTFNet时，同样的数据设置和训练配置，时而会出现hm_loss增大至9.208499并在之后的训练的过程中保持不变，在反复启动训练的过程中发现这种现象也可能不出现，loss稳定下降。此外好像在—eval指令下更为常见（或许是我记错了）
请问这是我数据集整理的问题还是代码中哪里需要进行设置？

**Comment by nemonameless** [comment]
你好，可以发下你改动的几个config配置文件吗？像这样的 #3871

**Comment by ghost** [comment]
> 你好，可以发下你改动的几个config配置文件吗？像这样的 #3871

感谢你的回复，我的config配置如下：
### ttfnet_darknet53_1×_coco.yml
![image](https://user-images.githubusercontent.com/59326436/128104298-9062fbb2-7ae5-409e-9499-774634eb455f.png)
### ttfnet_darknet53.yml
![image](https://user-images.githubusercontent.com/59326436/128104407-acd7db69-bdac-4eba-804b-0cceb1d0a1b9.png)
### ttfnet_reader.yml
![image](https://user-images.githubusercontent.com/59326436/128104345-b5901ab4-4e2b-4e85-8cad-42cb048ae52f.png)
### coco_detection.yml
![image](https://user-images.githubusercontent.com/59326436/128104246-9b28aedb-dc3a-4679-a105-724154d7c33b.png)

**Comment by ghost** [comment]
> 你好，可以发下你改动的几个config配置文件吗？像这样的 #3871
其中部分训练log如下：
![image](https://user-images.githubusercontent.com/59326436/128104674-3c94f611-1729-444c-a513-7fa472f6bb66.png)

**Comment by TangJiamin** [comment]
我也是，训练到第4个epoch的时候hm_loss突然增大到9.208504，然后就不变了。而且我在训练中eval的时候一直显示ppdet.engine WARNING: Evaluation results empty, this may be due to training iterations being too few or not loading the correct weights.

**Comment by ghost** [comment]
> 我也是，训练到第4个epoch的时候hm_loss突然增大到9.208504，然后就不变了。而且我在训练中eval的时候一直显示ppdet.engine WARNING: Evaluation results empty, this may be due to training iterations being too few or not loading the correct weights.

我倒是没有这个Warning，我刚才有开启一次训练，又正常了。。。
就很奇怪

**Comment by TangJiamin** [comment]
> > 我也是，训练到第4个epoch的时候hm_loss突然增大到9.208504，然后就不变了。而且我在训练中eval的时候一直显示ppdet.engine WARNING: Evaluation results empty, this may be due to training iterations being too few or not loading the correct weights.
> 
> 我倒是没有这个Warning，我刚才有开启一次训练，又正常了。。。
> 就很奇怪

你现在训的时候wh_loss有变化吗，我hm_loss变的时候wh_loss就一直是4.999999。还有一个很奇怪的事,训练到第4个epoch的时候eval报错，之前训练的时候没有出现过这个问题，报错如下：
```
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 317, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 337, in _eval_with_loader
    metric.update(data, outs)
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/metrics/metrics.py", line 91, in update
    outs, self.clsid2catid, bias=self.bias)
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/metrics/coco_utils.py", line 53, in get_infer_results
    outs['bbox'], outs['bbox_num'], im_id, catid, bias=bias)
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/metrics/json_results.py", line 32, in get_det_res
    category_id = label_to_cat_id_map[int(num_id)]
KeyError: 56
```

**Comment by ghost** [comment]
> > > 我也是，训练到第4个epoch的时候hm_loss突然增大到9.208504，然后就不变了。而且我在训练中eval的时候一直显示ppdet.engine WARNING: Evaluation results empty, this may be due to training iterations being too few or not loading the correct weights.
> > 
> > 
> > 我倒是没有这个Warning，我刚才有开启一次训练，又正常了。。。
> > 就很奇怪
> 
> 你现在训的时候wh_loss有变化吗，我hm_loss变的时候wh_loss就一直是4.999999。还有一个很奇怪的事,训练到第4个epoch的时候eval报错，之前训练的时候没有出现过这个问题，报错如下：
> 
> ```
> Traceback (most recent call last):
>   File "tools/train.py", line 140, in <module>
>     main()
>   File "tools/train.py", line 136, in main
>     run(FLAGS, cfg)
>   File "tools/train.py", line 111, in run
>     trainer.train(FLAGS.eval)
>   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 317, in train
>     self._eval_with_loader(self._eval_loader)
>   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 337, in _eval_with_loader
>     metric.update(data, outs)
>   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/metrics/metrics.py", line 91, in update
>     outs, self.clsid2catid, bias=self.bias)
>   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/metrics/coco_utils.py", line 53, in get_infer_results
>     outs['bbox'], outs['bbox_num'], im_id, catid, bias=bias)
>   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/metrics/json_results.py", line 32, in get_det_res
>     category_id = label_to_cat_id_map[int(num_id)]
> KeyError: 56
> ```
没有，我最新一次的训练正常结束了，loss整成下降至1.0左右，eval也正常，就是ap有点低

**Comment by jerrywgz** [comment]
想问下训练是使用的几卡呢，如果是单卡的话学习率需要对应降低8倍。另外ttfnet模型因为自身设置的学习率比较大，可能会出现其他数据集训练出现不稳定的情况。建议pretrain_weights加载官方release出的coco数据集上训练好的模型，然后将学习率再调低一些

**Comment by TangJiamin** [comment]
> > > > 我也是，训练到第4个epoch的时候hm_loss突然增大到9.208504，然后就不变了。而且我在训练中eval的时候一直显示ppdet.engine WARNING: Evaluation results empty, this may be due to training iterations being too few or not loading the correct weights.
> > > 
> > > 
> > > 我倒是没有这个Warning，我刚才有开启一次训练，又正常了。。。
> > > 就很奇怪
> > 
> > 
> > 你现在训的时候wh_loss有变化吗，我hm_loss变的时候wh_loss就一直是4.999999。还有一个很奇怪的事,训练到第4个epoch的时候eval报错，之前训练的时候没有出现过这个问题，报错如下：
> > ```
> > Traceback (most recent call last):
> >   File "tools/train.py", line 140, in <module>
> >     main()
> >   File "tools/train.py", line 136, in main
> >     run(FLAGS, cfg)
> >   File "tools/train.py", line 111, in run
> >     trainer.train(FLAGS.eval)
> >   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 317, in train
> >     self._eval_with_loader(self._eval_loader)
> >   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 337, in _eval_with_loader
> >     metric.update(data, outs)
> >   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/metrics/metrics.py", line 91, in update
> >     outs, self.clsid2catid, bias=self.bias)
> >   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/metrics/coco_utils.py", line 53, in get_infer_results
> >     outs['bbox'], outs['bbox_num'], im_id, catid, bias=bias)
> >   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/metrics/json_results.py", line 32, in get_det_res
> >     category_id = label_to_cat_id_map[int(num_id)]
> > KeyError: 56
> > ```
> 
> 没有，我最新一次的训练正常结束了，loss整成下降至1.0左右，eval也正常，就是ap有点低

就很奇怪，我都不知道哪里出问题了

**Comment by ghost** [comment]
> 想问下训练是使用的几卡呢，如果是单卡的话学习率需要对应降低8倍。另外ttfnet模型因为自身设置的学习率比较大，可能会出现其他数据集训练出现不稳定的情况。建议pretrain_weights加载官方release出的coco数据集上训练好的模型，然后将学习率再调低一些

好的，我会尝试更改学习率，但是好像因为学习率过大导致hm_loss不变有些牵强，毕竟每一个label是不同的呀

**Comment by ghost** [comment]
> > > > > 我也是，训练到第4个epoch的时候hm_loss突然增大到9.208504，然后就不变了。而且我在训练中eval的时候一直显示ppdet.engine WARNING: Evaluation results empty, this may be due to training iterations being too few or not loading the correct weights.
> > > > 
> > > > 
> > > > 我倒是没有这个Warning，我刚才有开启一次训练，又正常了。。。
> > > > 就很奇怪
> > > 
> > > 
> > > 你现在训的时候wh_loss有变化吗，我hm_loss变的时候wh_loss就一直是4.999999。还有一个很奇怪的事,训练到第4个epoch的时候eval报错，之前训练的时候没有出现过这个问题，报错如下：
> > > ```
> > > Traceback (most recent call last):
> > >   File "tools/train.py", line 140, in <module>
> > >     main()
> > >   File "tools/train.py", line 136, in main
> > >     run(FLAGS, cfg)
> > >   File "tools/train.py", line 111, in run
> > >     trainer.train(FLAGS.eval)
> > >   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 317, in train
> > >     self._eval_with_loader(self._eval_loader)
> > >   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 337, in _eval_with_loader
> > >     metric.update(data, outs)
> > >   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/metrics/metrics.py", line 91, in update
> > >     outs, self.clsid2catid, bias=self.bias)
> > >   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/metrics/coco_utils.py", line 53, in get_infer_results
> > >     outs['bbox'], outs['bbox_num'], im_id, catid, bias=bias)
> > >   File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/metrics/json_results.py", line 32, in get_det_res
> > >     category_id = label_to_cat_id_map[int(num_id)]
> > > KeyError: 56
> > > ```
> > 
> > 
> > 没有，我最新一次的训练正常结束了，loss整成下降至1.0左右，eval也正常，就是ap有点低
> 
> 就很奇怪，我都不知道哪里出问题了

更改学习率试试吧
