### ISSUE TITLE
请问YOLOv4、PP-YOLOv2的配置文件何时发布呢

### ISSUE THREAD

**Issue by wu-yakun** [PaddlePaddle/PaddleDetection#3878]
请问PaddleDetection飞桨目标检测开发套件公布的代码中不包含YOLOv4、PP-YOLOv2吗？官方有发布YOLOv4和PP-YOLOv2的配置文件吗

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/ppyolo ，PP-YOLO和v2
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/static/configs/yolov4 ，YOLOv4暂时只有静态图版本
推荐直接使用PP-YOLOv2
