### ISSUE TITLE
批量检测图片时，总是检测一部分图片就终止，也没有报错。

### ISSUE THREAD

**Issue by wu-yakun** [PaddlePaddle/PaddleDetection#3882]
批量检测图片时，总是检测一部分图片就终止，也没有报错。
debug定位出问题出在self.predictor.run() ，但不知问题出在何处。
求大佬指点！

**Comment by nemonameless** [comment]
> 批量检测图片时，总是检测一部分图片就终止，也没有报错。
> debug定位出问题出在self.predictor.run() ，但不知问题出在何处。
> 求大佬指点！

你好，可以描述再详细点吗？哪个分支和版本，什么模型？self.predictor.run()是哪一个文件的哪一行的，方便的话最好提供运行出错的截图，谢谢

**Comment by wu-yakun** [comment]
PaddleDetection的2.1版本，YOLOv3的检测模型(配置文件为yolov3_darknet53_207e_voc.yml). 
self.predictor.run()位于PaddleDetection中deploy/python/infer.py的第141行。
没有报错，只是批量检测时，总是检测一部分后，自动停止。

**Comment by MengQiDWangChao** [comment]
同样的问题，最新的2.1版本测试用的infer.py的trainer.predict(images,
                    draw_threshold=FLAGS.draw_threshold,
                    output_dir=FLAGS.output_dir,
                    save_txt=FLAGS.save_txt)函数无法正常结束运行，没有报错，在for step_id, data in enumerate(loader):这个循环里就结束了，原因不明

**Comment by nemonameless** [comment]
批量检测是多少张图，能定位到哪张图报错吗？用它单独infer有没有问题？另外请提供具体运行命令。如急用请使用develop分支或release/2.2分支，并使用paddlepaddle 2.1。

**Comment by MengQiDWangChao** [comment]
安装的paddlepaddle2.1.2, paddledetection2.1, 使用的就是教程的python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=false weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg的参数进行调试的，只是用的是cpu,调试的时候发现trainer.predict(images,
draw_threshold=FLAGS.draw_threshold,
output_dir=FLAGS.output_dir,
save_txt=FLAGS.save_txt)没有正常结束，我在看看是不是哪里配置有问题，这张图像的结果是有输出的。

**Comment by MengQiDWangChao** [comment]
具体是这样的，我想在run(FLAGS, cfg)后面进行一些显示啥的，发现程序运行不到后面，在trainer.predict中貌似就退出了
run(FLAGS, cfg)
print(os.environ.get('CPU_NUM'))
print(os.environ.get('OMP_NUM_THREADS'))，我试了一下demo文件夹下的图像结果是都可以输出的，貌似是最后一次迭代的时候退出了，
PS D:\PaddleDetection-2.1.0>  d:; cd 'd:\PaddleDetection-2.1.0'; & 'C:\Users\iBird\anaconda3\envs\PaddleDetection\python.exe' 'c:\Users\iBird\.vscode\extensions\ms-python.python-2021.7.1060902895\pythonFiles\lib\python\debugpy\launcher' '51578' '--' 'd:\PaddleDetection-2.1.0\tools\infer.py' '-c' 'configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml' '-o' 'use_gpu=false' 'weights=models/ppyolov2_r50vd_dcn_365e_coco.pdparams' '--infer_dir=demo' 
['-c', 'configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml', '-o', 'use_gpu=false', 'weights=models/ppyolov2_r50vd_dcn_365e_coco.pdparams', '--infer_dir=demo']
[08/04 17:53:46] ppdet.utils.checkpoint INFO: Finish loading model weights: models/ppyolov2_r50vd_dcn_365e_coco.pdparams
[08/04 17:53:46] train INFO: Found 9 inference images in total.
[08/04 17:53:51] ppdet.engine INFO: Detection bbox results save in output\000000014439.jpg
[08/04 17:53:55] ppdet.engine INFO: Detection bbox results save in output\hrnet_demo.jpg
[08/04 17:54:00] ppdet.engine INFO: Detection bbox results save in output\P0072__1.0__0___0.png
[08/04 17:54:04] ppdet.engine INFO: Detection bbox results save in output\000000014439_640x640.jpg
[08/04 17:54:08] ppdet.engine INFO: Detection bbox results save in output\P0861__1.0__1154___824.png
[08/04 17:54:13] ppdet.engine INFO: Detection bbox results save in output\000000087038.jpg
[08/04 17:54:17] ppdet.engine INFO: Detection bbox results save in output\road554.png
[08/04 17:54:21] ppdet.engine INFO: Detection bbox results save in output\000000570688.jpg
[08/04 17:54:26] ppdet.engine INFO: Detection bbox results save in output\orange_71.jpg

**Comment by wu-yakun** [comment]
实测，不调用GPU去批量检测，没有问题，是OK的。当用GPU时，单张图片检测也没有问题，但是，调用GPU做批量检测总在检测几张后就出现无报错退出的问题。
运行指令：python deploy/python/infer.py --model_dir=./export_model/yolov3_darknet53_270e_character_voc  --use_gpu=True

问题排除1：用批量检测停止的照片去做单张检测，也没有问题；并且停止的图片是随机的，并且停止的图片均可以做单张检测。
问题排除2：8G的显卡，只占用了1.7G左右，CPU占用60%上下。因此，排除显存或内存爆炸的问题。
问题排除3：检测的出图片，结果都是正确的。

这个问题研究一天半了，也没解决，哎。好气哦。

**Comment by MengQiDWangChao** [comment]
下午花了点时间看了下代码，怀疑是ppdet/data/reader.py中的迭代的问题，这个里面的BaseDataLoader中的next函数貌似没有正常结束，我改成了根据样本数目个数停止迭代可以正常运行了，但不知道是不是本质上是不是这个原因导致的；
def __next__(self):
        try:
            return next(self.loader)
        except StopIteration:
            self.loader = iter(self.dataloader)
            six.reraise(*sys.exc_info())
改成了
def __next__(self):            
	if self.iter_num <= len(self._batch_sampler):
		self.iter_num += 1
		return next(self.loader)
	else:
		self.loader = iter(self.dataloader)
		raise StopIteration


> 批量检测是多少张图，能定位到哪张图报错吗？用它单独infer有没有问题？另外请提供具体运行命令。如急用请使用develop分支或release/2.2分支，并使用paddlepaddle 2.1。

下午花了点时间看了下代码，怀疑是ppdet/data/reader.py中的迭代的问题，这个里面的BaseDataLoader中的next函数貌似没有正常结束，我改成了根据样本数目个数停止迭代可以正常运行了，但不知道是不是本质上是不是这个原因导致的；
def __next__(self):
        try:
            return next(self.loader)
        except StopIteration:
            self.loader = iter(self.dataloader)
            six.reraise(*sys.exc_info())
改成了
def __next__(self):            
	if self.iter_num <= len(self._batch_sampler):
		self.iter_num += 1
		return next(self.loader)
	else:
		self.loader = iter(self.dataloader)
		raise StopIteration

**Comment by nemonameless** [comment]
正在排查，感谢反馈～

**Comment by nemonameless** [comment]
@wu-yakun 您测的deploy下的导出模型的infer，打印日志每张都会输出坐标的吧
```
CUDA_VISIBLE_DEVICES=1 python3.7 deploy/python/infer.py --model_dir=output_inference/yolov3_darknet53_270e_coco --device=GPU --image_dir=dataset/coco/val2017
```
@MengQiDWangChao 您测的是tools下原模型的infer，是ppdet.engine INFO: Detection bbox results save in 的打印日志
```
CUDA_VISIBLE_DEVICES=1 python3.7 tools/infer.py -c configs/yolov3/yolov3_darknet53_270e_coco.yml  -o weights=/root/.cache/paddle/weights/yolov3_darknet53_270e_coco.pdparams --infer_dir=dataset/coco/val2017
```
我们这两句命令测coco val2017的5000张，都没有问题不会卡住，是在develop分支下。你们使用develop分支能复现问题吗？

**Comment by MengQiDWangChao** [comment]
> @wu-yakun 您测的deploy下的导出模型的infer，打印日志每张都会输出坐标的吧
> 
> ```
> CUDA_VISIBLE_DEVICES=1 python3.7 deploy/python/infer.py --model_dir=output_inference/yolov3_darknet53_270e_coco --device=GPU --image_dir=dataset/coco/val2017
> ```
> 
> @MengQiDWangChao 您测的是tools下原模型的infer，是ppdet.engine INFO: Detection bbox results save in 的打印日志
> 
> ```
> CUDA_VISIBLE_DEVICES=1 python3.7 tools/infer.py -c configs/yolov3/yolov3_darknet53_270e_coco.yml  -o weights=/root/.cache/paddle/weights/yolov3_darknet53_270e_coco.pdparams --infer_dir=dataset/coco/val2017
> ```
> 
> 我们这两句命令测coco val2017的5000张，都没有问题不会卡住，是在develop分支下。你们使用develop分支能复现问题吗？

我的问题不是卡住，是infer.py的main()中的run(FLAGS, cfg)函数不能结束，无法在这个函数后面进行操作，原因是在trainer.predict里面最后一张图片处理完之后没有正常退出，但是没有报错；你可以试一下用一张图调试，在run(FALGS, cfg)加一下代码看看能否执行到，我也去试下develop分支有没有这个问题

**Comment by MengQiDWangChao** [comment]
> > @wu-yakun 您测的deploy下的导出模型的infer，打印日志每张都会输出坐标的吧
> > ```
> > CUDA_VISIBLE_DEVICES=1 python3.7 deploy/python/infer.py --model_dir=output_inference/yolov3_darknet53_270e_coco --device=GPU --image_dir=dataset/coco/val2017
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @MengQiDWangChao 您测的是tools下原模型的infer，是ppdet.engine INFO: Detection bbox results save in 的打印日志
> > ```
> > CUDA_VISIBLE_DEVICES=1 python3.7 tools/infer.py -c configs/yolov3/yolov3_darknet53_270e_coco.yml  -o weights=/root/.cache/paddle/weights/yolov3_darknet53_270e_coco.pdparams --infer_dir=dataset/coco/val2017
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我们这两句命令测coco val2017的5000张，都没有问题不会卡住，是在develop分支下。你们使用develop分支能复现问题吗？
> 
> 我的问题不是卡住，是infer.py的main()中的run(FLAGS, cfg)函数不能正常结束，无法在这个函数后面添加其他函数等操作，原因是在trainer.predict里面最后一张图片处理完之后没有正常退出，但是没有报错；你可以试一下用一张图调试，在run(FALGS, cfg)加一下代码看看能否执行到，我也去试下develop分支有没有这个问题

**Comment by MengQiDWangChao** [comment]
> > > @wu-yakun 您测的deploy下的导出模型的infer，打印日志每张都会输出坐标的吧
> > > ```
> > > CUDA_VISIBLE_DEVICES=1 python3.7 deploy/python/infer.py --model_dir=output_inference/yolov3_darknet53_270e_coco --device=GPU --image_dir=dataset/coco/val2017
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @MengQiDWangChao 您测的是tools下原模型的infer，是ppdet.engine INFO: Detection bbox results save in 的打印日志
> > > ```
> > > CUDA_VISIBLE_DEVICES=1 python3.7 tools/infer.py -c configs/yolov3/yolov3_darknet53_270e_coco.yml  -o weights=/root/.cache/paddle/weights/yolov3_darknet53_270e_coco.pdparams --infer_dir=dataset/coco/val2017
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我们这两句命令测coco val2017的5000张，都没有问题不会卡住，是在develop分支下。你们使用develop分支能复现问题吗？
> > 
> > 
> > 我的问题不是卡住，是infer.py的main()中的run(FLAGS, cfg)函数不能正常结束，无法在这个函数后面添加其他函数等操作，原因是在trainer.predict里面最后一张图片处理完之后没有正常退出，但是没有报错；你可以试一下用一张图调试，在run(FALGS, cfg)之后加一些代码看看能否执行到，我也去试下develop分支有没有这个问题
