### ISSUE TITLE
怎么加入负样本训练

### ISSUE THREAD

**Issue by meng8407** [PaddlePaddle/PaddleDetection#3883]
## 描述问题/Describe the bug
我将已经标注好的数据，制作coco数据集进行训练，发现FP特别高，很容易将错误的图像检测为正确，想要杀FP,加入大量的负样本进去，
问题一，我是直接将未标注的负样本图像放入coco数据集中，模型训练时候能读取空图当作背景图像读取吗，我用的是faster_rcnn.
问题二，还是我直接拼接负样本图像到原图中去，再次标注图像进行新的训练，这样的话比较麻烦，您有什么好的办法，将我的标注图像利用上吗？

3. 您使用的数据集是？/What dataset did you use?
自己根据数据集制作的coco数据。

## 环境/Environment
1. 请提供您使用的Paddle
PaddleDetection-master

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g.,
 Linux：

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
3.7.0

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
11.0

**Comment by nemonameless** [comment]
FP特别高不一定要加入大量的负样本去解决，即使加那么其数量也没有标准控制吧。你说的两个问题做法都可以，个人建议使用更强的模型，也可以从数据增广角度入手更方便，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/rcnn_enhance/_base_/faster_rcnn_enhance_reader.yml   可以参考下

**Comment by meng8407** [comment]
> FP特别高不一定要加入大量的负样本去解决，即使加那么其数量也没有标准控制吧。你说的两个问题做法都可以，个人建议使用更强的模型，也可以从数据增广角度入手更方便，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/rcnn_enhance/_base_/faster_rcnn_enhance_reader.yml 可以参考下
您好：
1、我听从您的建议，使用了cascade rcnn 更强的模型结果，项目应用的话FP依旧是太高，
2、我准备尝试数据增广的方法，我有四个标签，15000张训练图像，数据增广的话，依据您的经验，数量扩大到一倍合适吗？

**Comment by nemonameless** [comment]
数据量扩大一倍可能还不够多。这些调优也是因数据集而异的，还有比如NMS阈值参数等也都可以调试试
