### ISSUE TITLE
How to use checkpoint and continue training

### ISSUE THREAD

**Issue by thutran292** [PaddlePaddle/PaddleDetection#3888]
I want to use checkpoint and continue training. How to do this?

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/GETTING_STARTED.md
use `-r`
```
python tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml -r output/yolov3_mobilenet_v1_roadsign/100
``` 
please make sure 100.pdopt and 100.pdparams exist.
