### ISSUE TITLE
使用tensorrt推理时报错

### ISSUE THREAD

**Issue by NewToolAI** [PaddlePaddle/PaddleDetection#3892]
显卡是3090，已经安装tensorrt和paddle包。--run_mode=trt_fp16时报如下错误

```
--------------------------------------------
ValueError: (InvalidArgument) The TRT network should be initialized first.
  [Hint: Expected network() != nullptr == true, but received network() != nullptr:0 != true:1.] (at /paddle/paddle/fluid/inference/tensorrt/engine.cc:250)
```

**Comment by qingqing01** [comment]
@Shulin-Zhang 你是使用Python预测、还是C++预测？ 使用的Paddle版本是多少？

**Comment by NewToolAI** [comment]
使用python预测，paddle版本是2.1.1

**Comment by qingqing01** [comment]
@Shulin-Zhang  2.1.1默认Python包没有包含TensorRT编译，您需要从下面列表中依据您的CUDA、cuDNN、TensorRT版本号选择影响的PaddlePaddle whl包

https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release
