### ISSUE TITLE
图片分辨率非对称，差异较大的情况下，参数设置异常

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleDetection#3893]
例如图片分辨率在3000 X  500   max_height等参数设置如下
![K)R76{50CW18PT Y45G UT5](https://user-images.githubusercontent.com/88479008/128313912-c22eebc2-a4e6-4ec1-a0e2-8489fef34d0f.jpg)
![C OAAXR)E9DM72P28KOBO2](https://user-images.githubusercontent.com/88479008/128314013-20cf58c4-261a-4351-a876-60be1f8cc8b8.jpg)
![ACYMRDL0% ~U4EKB7R9}P7](https://user-images.githubusercontent.com/88479008/128314025-44dcff70-d7d9-4b4e-884c-2b0d24b8a8da.jpg)

这样设置可以训练  ，   但是C++下无法推理

所有相关全部设置为608，可以正常训练及推理

但是不对等的图片尺寸设置   在推理时偶尔效果不太好

yoloV3及yoloV4是可以分开设置的（原版）
对于长宽非对等的比较友好

这个问题需要怎么解决？

**Comment by qingqing01** [comment]
您C++推理，模型导出时输入H、W设置是多少？

**Comment by 534114658** [comment]
训练时的配置

![捕获](https://user-images.githubusercontent.com/88479008/128468084-15356522-b900-4c11-8a69-8ca4b5244531.PNG)


自动生成C++的配置文件
![捕获2](https://user-images.githubusercontent.com/88479008/128468096-7634253d-25e9-4932-bb07-18eed0266918.PNG)

**Comment by qingqing01** [comment]
您当前设置的 target_size: 512，推理的时候模型输入是512 x 512。
TestReader中image_shape的导出是[3, 512, 3008]，2个不一致。

您推理想用的输入是多少？(512x512推理速度会快， 512x3008推理速度慢，精度需要eval知道)

**Comment by 534114658** [comment]
如果需要512x3008推理要怎么设置？
(512x512推理速度会快   但是推理效果不太好   很多检测框有较大偏移  重叠等现象

**Comment by qingqing01** [comment]
ResizeImage的参数设置为 target_size设置为list，[512, 3008], keep_ratio设置False。

https://github.com/PaddlePaddle/PaddleDetection/blob/ab6ca82d2af79384016d19e64daa5b19cc0691e9/deploy/python/preprocess.py#L49


不过看您是静态图，总之就是确保 Resize后输入的shape和您想要的匹配。

**Comment by 534114658** [comment]
用动态图解决

**Comment by bueredgirll** [comment]
> 用动态图解决

请问怎么用动态解决呢
