### ISSUE TITLE
新做的 coco 数据集 无法正常识别 新的目标种类 还是原先的目标种类

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#3896]
用labelme 做了新的 coco数据集 并做了对应数据的两种 类别 标签 但是 训练完成后 infer 图片时候 目标种类还是 原来的 没能正常 识别新的 目标种类 这是什么情况？ 数据集修改后 已经修改了响应的配置文件 
![04318f48027a39a237beb2951fc6413](https://user-images.githubusercontent.com/88072901/128363566-f6814ec7-6730-4bae-8286-b6af1ead7341.png)

**Comment by heavengate** [comment]
`TestDataset`里的`anno_path`指向你新做的数据集的annotation路径试下

**Comment by STUSER001** [comment]
我上传的 图片 就是我自己 设置的 数据集 所在的路径

**Comment by heavengate** [comment]
`TestDataset`里的anno_path是`annotations/val.json`这个路径应该不是annotation文件的路径吧

**Comment by STUSER001** [comment]
这个 可以 无视吧 因为我 检测图片 是用的 自定义目录下的图片 且是一张 一张 手动做推理的

**Comment by heavengate** [comment]
infer图片的时候也是要读数据集类别的，读的就是`TestDataset`里anno_path指定的annotation里的类别，不配置的话就会因为找不到文件去读coco数据集的默认类别

**Comment by STUSER001** [comment]
可是 刚刚下载 模型的时候  就是 这样的 只不过 我吧 原来 instance_val2017.json 修改成了 自己的 val.json 这个 里面也是 coco 数据集的 json 文件 所以类别用的 也是 一样的啊
 就是说 我又要 做 test.json 么？？

**Comment by heavengate** [comment]
把`TestDataset`里的anno_path配置成你的val.json的绝对路径试下呢

**Comment by STUSER001** [comment]
已解决 多谢

**Comment by pureloveljc** [comment]
这个是怎么解决的

**Comment by STUSER001** [comment]
把TestDataset里的anno_path配置成你的val.json的绝对路径 就可以了
