### ISSUE TITLE
paddle serving方式进行paddle detection的服务端部署后预测结果bbox.json位置信息问题

### ISSUE THREAD

**Issue by keweisong** [PaddlePaddle/PaddleDetection#3897]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.

## 描述问题/Describe the bug

使用paddle serving方式进行paddle detection的服务端部署
python -m paddle_serving_server.serve --model serving_server --port 9393

然后运行预测命令
python test_client.py road554.png

得到的图片结果正常检测出目标对象, 但是bbox.json中目标对象的位置信息不正常
[
    {
        "category_id": 0,
        "bbox": [
            165.65567016601562,
            390.0230712890625,
            131.86630249023438,
            85.201904296875
        ],
        "score": 0.9685503244400024
    },
...
]

正常的位置信息应该是

### <object>
        <name>speedlimit</name>
        <pose>Unspecified</pose>
        <truncated>0</truncated>
        <occluded>0</occluded>
        <difficult>0</difficult>
        <bndbox>
            <xmin>87</xmin>
            <ymin>257</ymin>
            <xmax>142</xmax>
            <ymax>311</ymax>
        </bndbox>
    </object>

我理解的bbox.json中的位置信息格式应该是x1y1x2y2, 如果不是, 请说明一下.

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by keweisong** [comment]
感谢飞桨群友的答复.
自己回答下吧, 以帮助有同样问题的同学.

bbox中的位置信息需要根据Sequential中的处理进行转换. 
比如我的sequential是:
`Sequential([
    File2Image(), BGR2RGB(), Resize(
        (608, 608), interpolation=cv2.INTER_LINEAR), Div(255.0), Transpose(
            (2, 0, 1))
])
`
则需要将bbox中的尺寸乘以原始图的尺寸再除以608. 

另外注意bbox中的位置格式是xywh

**Comment by heavengate** [comment]
感谢更新，鉴于问题已经解决，当前issue就先关闭了，如果有问题可以reopen这个issue~
