### ISSUE TITLE
ppyolov2使用自定义的voc数据集，使用训练好的模型测试没有效果是什么原因，map为0.02%

### ISSUE THREAD

**Issue by wujitiana** [PaddlePaddle/PaddleDetection#3898]
voc.yml配置
metric: VOC
map_type: 11point
num_classes: 1

TrainDataset:
  !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: trainval.txt    #trainval.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: test.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: test.txt      #dataset/voc/label_list.txt

可以正常训练，但是训练好的模型对我的数据集没有效果 是什么原因

**Comment by heavengate** [comment]
训练的log发一下看下呢，是不是训练过程还没有收敛，另外你是用的PaddleDetection是哪个版本，2.1.0版本有个收敛性问题，可以更新到develop版本试下

**Comment by wujitiana** [comment]
我训练了200个epoch这是最后两个迭代&nbsp; 我使用的是2.1版本的paddleDetection


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月6日(星期五) 下午3:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] ppyolov2使用自定义的voc数据集，使用训练好的模型测试没有效果是什么原因，map为0.02% (#3898)





 
训练的log发一下看下呢，是不是训练过程还没有收敛，另外你是用的PaddleDetection是哪个版本，2.1.0版本有个收敛性问题，可以更新到develop版本试下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heavengate** [comment]
可以试下develop分支或者release/2.2分支，可以`pip uninstall paddledet`之后`python setup.py install`重新安装一下，release/2.1上之前有个训练收敛性问题
