### ISSUE TITLE
数据集不够 会导致 无法 替换原来的 检测目标种类么？

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#3899]
训练使用的 数据集 较少 会导致 最后 训练出来的 模型 在进行图片 检测时候 无法替换 原来的 目标种类

**Comment by heavengate** [comment]
没太理解你的意思，“无法替换原来的检测目标种类”是指啥呢

**Comment by STUSER001** [comment]
比如 模型 刚开始 识别的 目标是 车 后来 我自己做的数据集 是识别动物的 可是 训练完后 图片 推理的时候 还是 识别 车 不识别 动物

**Comment by heavengate** [comment]
如果是自定义的数据集，需要对应的`configs/datasets/xxx.yml`配置文件里`TestDataset`的anno_path指定到你的标注文件所在路径，否则会因为找不到标注文件而读取默认的COCO、VOC这些数据集的类别
