### ISSUE TITLE
How to evaluate just a single category,not for multi categories

### ISSUE THREAD

**Issue by lyw615** [PaddlePaddle/PaddleDetection#39]
In the project, it can detect six categories.But how can i modify it to just detect a single category.

**Comment by willthefrog** [comment]
Could you elaborate? What do you mean by "detect a single category"? Do you want to build a single class detector?  Or do you simply want to filter the predictions by class?

**Comment by lyw615** [comment]
I have tried to build a single class detector,but found it's impossile  to achieved. Isn't it? So i choose to filter the prediction by class

**Comment by lyw615** [comment]
Furthermore,  are there any paper can be refered for the project of vehicle detetion

**Comment by willthefrog** [comment]
> I have tried to build a single class detector,but found it's impossile to achieved. Isn't it? So i choose to filter the prediction by class

In that case, it should be pretty straight forward to implement, just modify `infer.py` and filter the items in `bbox_results` by their `category_id` field.

**Comment by lyw615** [comment]
Yeah, i have done  what you said yestoday. The result seems good. So if any description for the training process offered  will be appreciated

**Comment by willthefrog** [comment]
The vehicle detection model is basically yolov3 trained on an internal dataset, the training tricks were detailed in [this paper](https://arxiv.org/abs/1902.04103).

**Comment by hande6688** [comment]
How to label a single category with labelme and instance segmentation? There are cat, cat, cat, cat0, cat1, cat2 or cat-0, cat-1, cat-2, etc. which annotation method is used?thank you!

I use cat-0, cat-1, cat-2 for annotation, and use labelme2coco to convert annotations.json, where the annotation is [], what's the matter?
