### ISSUE TITLE
[BUG]C++部署时图片的H和W不等，源代码将H和W弄反了

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/PaddleDetection#3901]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.
3. 确认bug是否在新版本里还未修复/The bug has not been fixed in the latest version.

## 描述问题/Describe the bug
（1）export.py在导出模型时，使用的是coco默认的分类，而不是数据集自身的分类。在deploy.yml中可以看到。
（2）导出的静态图模型，当检测到的目标数量为0时，会报错，在Python的infer.py和c++中都出现过。
（3）在C++部署代码中，将H和W有个地方弄反了，后来我修改过来，运行才正常，否则效果很差，建议认真检查一下代码，因为示例中很多代码都是H=W，弄反无所谓，但实际项目中，H和W一般不等，会带来很差的推理效果。很多代码都没有解释输入或者输出哪个是H，哪个是W。
（4）PaddleDetection套件很强大，比pytorch等使用字典的方式可靠很多，但里面是如何解析，如何create类的，注册、序列化是怎么进行的，作为一个5年Python编码的都看的迷迷糊糊的，希望你们能够详细的讲述一下。对于很多学习者来说，代码的数据读取、model构造、loss编写、训练都可以搞定，但detection的解析一用，就懵逼了，如果想对代码进行大幅改动，编写多任务或者更加复杂的结构，编写新的实例分割框架，是非常困难的。而且detection的解析与seg套件还不同，前段时间花了很大精力搞懂 了seg，但detection一看又懵逼了。因为咱们的工程师水平很高，Python用的很好，可是对于很多哦深度学习者来说，并不关心Python的能力，更多关注的是网络结构和设计，但由于基本的解析搞不懂，很多精力都花在Python基础知识上了，主要为core包中的内容不明白怎么运行的。
非常感谢！

**Comment by heavengate** [comment]
1. 如果是自定义数据集，export的时候没有使用自定义数据集的分类，一般是因为`xxx_reader.yml`里`TestDataset`里的anno_path字段没有指向自定义数据集的annotation文件，导致程序找不到文件后使用了默认的coco分类
2. 我们确认一下，方便提供一下具体报什么错么
3. 你用的是哪个模型呢，HW反了的代码行数方便发一下么，我们排查一下
4. 感谢反馈，我们最近也在整理文档，针对代码结构的介绍我们也整理一下~

**Comment by zkz1994** [comment]
你好，可以指明下是哪里的W和H搞错了嘛，感激不尽

**Comment by BerylLuo** [comment]
> 码中，将H和W有个地方弄反了，后来我修改过来，运行才正常，否则效果很差，建议认真检查一下代码，因为示例中很多代码都是H=W，弄反无所谓，但实际项目中，H和W一般不等，会带来很差的推理效果。很多代码都没有解释输入或者输出哪个是H，哪个是W。

请问这个问题后来解决了么，我使用deploy/cpp结果测试的mAP很低，想检查一下是不是这个原因呢
