### ISSUE TITLE
在AI Studio上进行ppyolo tiny的训练和预测

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleDetection#3902]
在AI Studio上进行ppyolo tiny的训练和预测，使用的是voc的数据集，在训练后进行预测，出现如下错误。
![image](https://user-images.githubusercontent.com/71364549/128453902-40311272-afdd-44b5-8fe2-3c630755055b.png)

**Comment by heavengate** [comment]
你修改了配置文件里关于`num_classes`的配置么，或者你的数据集里的类别数跟`num_classes`不一致？
