### ISSUE TITLE
[Document Improvement]

### ISSUE THREAD

**Issue by yhygta** [PaddlePaddle/PaddleDetection#3903]
## 📖  文档优化/Documentation Improvement 咨询关于PP-YOLO模型页面的超参数设置问题

**请简单说明文档存在问题/Please provide a concise and brief description of the documentation problem:**
PP-YOLO 模型页面
提到的PP-YOLO tiny模型的320和416尺寸,对应的都是同一个配置文件(https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/ppyolo_tiny_650e_coco.yml),

但是实际训练使用的config_ppyolo_tiny.txt是本身自带的deploy/lite/下文件是320*320的,希望文档能注明如果需要调整为416尺寸的,是否是直接修改config_ppyolo_tiny.txt的Resize为416*416嘛
以及还想了解如果是其他的模型,对应config_ppyolo_???.txt去哪里取,谢谢

**请提供有问题的文档部分截图及链接/Please provide the screen shoot and the link of the document:**
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/README_cn.md

**Comment by heavengate** [comment]
感谢反馈，我们整理一下这部分的文档~
