### ISSUE TITLE
numpy版本问题

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#3906]
anaconda3
python   3.8
numpy    1.21.1
paddlepaddle-gpu    2.1.1.post112

--------------------------------------------

WARNING: Detect dataset only contains single fileds, return format changed since Paddle 2.1. In Paddle <= 2.0, DataLoader add a list surround output data(e.g. return [data]), and in Paddle >= 2.1, DataLoader return the single filed directly (e.g. return data). For example, in following code: 

import numpy as np
from paddle.io import DataLoader, Dataset

class RandomDataset(Dataset):
    def __getitem__(self, idx):
        data = np.random.random((2, 3)).astype('float32')

        return data

    def __len__(self):
        return 10

dataset = RandomDataset()
loader = DataLoader(dataset, batch_size=1)
data = next(loader())

In Paddle <= 2.0, data is in format '[Tensor(shape=(1, 2, 3), dtype=float32)]', and in Paddle >= 2.1, data is in format 'Tensor(shape=(1, 2, 3), dtype=float32)'

---------------

numpy版本太新了吗 应该怎么解决

**Comment by lyuwenyu** [comment]
这是waring不影响使用   升级一下paddle就行了

**Comment by monkeycc** [comment]
paddlepaddle-gpu 2.1.1

最新版了  应该要怎么升级？

**Comment by heavengate** [comment]
这个是warning，是针对数据集只有单个字段的时候报的，不影响模型运行，可以不用关注，另外把Paddle升级到2.1.2版本可以去掉这个warning
可以先`pip uninstall paddlepaddle-gpu`再`pip insstall paddlepaddle-gpu`重新安装一下~
