### ISSUE TITLE
训练出来的 模型 如何在 其他程序中使用

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#3908]
>查找文档后发现 导出后的 模型还是要 用paddle 提供的 infer.py 来对图片 进行 预测 那么就是说 如果 我要把模型由于 其他 程序 还得 搭建 paddle 环境 然后才能使用是这样的意思么？？？
![001](https://user-images.githubusercontent.com/88072901/128503650-f64dcfb4-aadd-4082-8811-1844dede53d1.png)

**Comment by jerrywgz** [comment]
如果是其他程序调用是需要依赖paddle预测库的，deploy/python/infer.py是python调用的例子可以参考
