### ISSUE TITLE
paddledetection 模型部署 出错 

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#3909]
如下图所示 运行后 提示 错误
![0002](https://user-images.githubusercontent.com/88072901/128547795-f4951580-1a98-4f03-925e-267a2a3c7928.PNG)

**Comment by jerrywgz** [comment]
麻烦提供下Paddle版本，PaddleDetection版本，以及模型相关配置。另外看起来模型使用的是旧版本的接口，可以参考PaddleDetection新版本下的预测部署参考实例
