### ISSUE TITLE
ssd文档

### ISSUE THREAD

**Issue by DongChenwei2000** [PaddlePaddle/PaddleDetection#3910]
开发者你好，现在的ssd文档中没有对MobileNet v3和ghostnet的介绍，希望后续可以添加下，并且想要询问下这2个在几gpu的环境下训练的？在AI studio上的单GPU环境使用哪一个比较好？
![image](https://user-images.githubusercontent.com/71364549/128593073-aab55aa0-91e5-4c53-8967-43600c2a9f3a.png)

**Comment by nemonameless** [comment]
ssdlite 的 MobileNet v3和ghostnet是8卡训的，其实每卡占应该不到10G显存，但是训练周期非常非常长，不建议在AI studio或单卡训练。可以考虑使用静态图版本 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/static/configs/ssd    ，
或者其他小模型比如 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/picodet
