### ISSUE TITLE
PR曲线绘制问题：

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#3916]
请教，目前评估时--classwise可以输出每类的AP和PR曲线，其中PR曲线只能是IOU0.5时的，如果想绘制每类在不同IOU时的PR曲线该如何处理，谢谢！

**Comment by zxsitu** [comment]
想咨询一下，请问如何绘制综合所有测试类别的一条PR曲线呢？
是把每一类的对应数据加起来取平均得到总的PR曲线呢？谢谢。

**Comment by yghstill** [comment]
> 请教，目前评估时--classwise可以输出每类的AP和PR曲线，其中PR曲线只能是IOU0.5时的，如果想绘制每类在不同IOU时的PR曲线该如何处理，谢谢！

@jackie8310 VOC数据默认iou=0.5，如果想要评估不同iou，需要修改：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/metrics/metrics.py#L211
COCO数据绘制PR曲线也默认是iou=0.5，如果想评估不同iou，需要修改：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/metrics/coco_utils.py#L141

**Comment by yghstill** [comment]
> 想咨询一下，请问如何绘制综合所有测试类别的一条PR曲线呢？
> 是把每一类的对应数据加起来取平均得到总的PR曲线呢？谢谢。

@ilem777 绘制所有类别的PR曲线，将各类PR数据加权平均计算就行。

**Comment by zxsitu** [comment]
> > 想咨询一下，请问如何绘制综合所有测试类别的一条PR曲线呢？
> > 是把每一类的对应数据加起来取平均得到总的PR曲线呢？谢谢。
> 
> @ilem777 绘制所有类别的PR曲线，将各类PR数据加权平均计算就行。

好的谢谢，我明白了。
