### ISSUE TITLE
每次 启动 配置好的 ppyolov2 环境 就提示安装pycocotools

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#3917]
环境配置 完后 每次重启 就提示 安装pycocotools 这个 怎么回事儿？ 
![0000](https://user-images.githubusercontent.com/88072901/128650519-72ac0152-f4bb-4a4f-acea-7fce6fdadaf4.PNG)

**Comment by wangxinxin08** [comment]
这个提示是说你的环境没有安装pycocotools，需要先安装pycocotools

**Comment by STUSER001** [comment]
这个 我知道 就是现在 问题是 我这次装好了 下次启动 又得在装一遍 也就是说我每次 启动 paddle 环境 就要装一遍

**Comment by wangxinxin08** [comment]
AI studio每次重启都要安装依赖

**Comment by STUSER001** [comment]
这样啊 那好吧 我还以为 我配置有问题呢 谢谢
