### ISSUE TITLE
[Other General Issues] 训练完没有保存 model_final 模型

### ISSUE THREAD

**Issue by kaixin-bai** [PaddlePaddle/PaddleDetection#3919]
## 遇到的问题
训练完成没有保存model_final模型，且loss还比较高。

## 疑问
训练完没有保存model_final模型是否说明模型效果不好，所以没有自动保存，还是因为我哪里做错了啊？

**Comment by wangxinxin08** [comment]
使用的PaddlePaddle，PaddleDetection以及运行的命令是什么？model_final没有保存的话可以看下训练是否正常退出了？loss比较高，可以先检查下：1. 学习率的设置 2.数据集路径等设置以及num_classes的设置
