### ISSUE TITLE
我用自己的COCO格式的数据集训练PPyolov2,为什么测试的结果全都接近于0

### ISSUE THREAD

**Issue by lihui669** [PaddlePaddle/PaddleDetection#3921]
我的损失函数收敛在23左右，测试结果为0是什么原因呢？训练的时候需要修改标签吗？在哪里修改标签？

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/data/source/category.py

建议可视化看一下
