### ISSUE TITLE
[模型蒸馏 Feature Map NMS 是否支持]

### ISSUE THREAD

**Issue by TianpengBu** [PaddlePaddle/PaddleDetection#3922]
如题，参考了PaddleDetection推荐的参考文章：Object detection at 200 Frames Per Second，上面在模型蒸馏中提出了两个方法：
1. objectness scaled distillation
2. feature map NMS

参考了Paddle的代码，看到代码中有用到1的方法，但是没有看到feature map NMS的方法。请问开发者，是因为这个方法对蒸馏效果不明显才弃用的吗？有无相关实验或者方法，想要参考一下～ 感谢

**Comment by yghstill** [comment]
@TianpengBu feature map NMS在实验中发现效果不明显，性价比不是很好，所以没有继续探索。

**Comment by zkf331** [comment]
@yghstill 您好，请教两个问题：
1、objectness scaled distillation 中的参数 weights 是大概怎么选择的呢。是根据 weights * distillation_loss 和 student_loss 在一个量级上吗
2、我在 pytorch 复现了 objectness scaled distillation 和 FM-map，两个方法一起使用比只使用 distillation 精度要高一点。但相同的 epochs，训练时间增加了一倍。你们也是这个原因吗

**Comment by zkf331** [comment]
@yghstill 您好，可以请教您两个问题吗
1、objectness scaled distillation 中的参数 weights 是大概怎么选择的呢。是根据 weights * distillation_loss 和 student_loss 在一个量级上吗？
2、我在 pytorch 复现了 objectness scaled distillation 和 FM-map，两个方法一起使用比只使用 distillation 精度要高一点。但相同的 epochs，训练时间增加了一倍。你们也是这个原因吗？
期待您的回答，谢谢！

**Comment by yghstill** [comment]
@zkf331 
1. weights是根据经验调整的，像您说的为了让distillation_loss 和 student_loss 在一个量级上，这样设置超参训练效果好一点。
2. 一方面是训练时间的原因，另一方面是精度收益不明显，可能是实现的有问题，没有继续跟进FM-map这个了。
