### ISSUE TITLE
安装报错The original error is: No module named 'paddle.fluid.core_avx'

### ISSUE THREAD

**Issue by ResonLee** [PaddlePaddle/PaddleDetection#3927]
## 描述问题/Describe the bug
Windows下安装配置PaddleDetection develop版本，CUDA版本为10.1，安装完成后验证安装情况，import paddle,报错The original error is: No module named 'paddle.fluid.core_avx'

## 复现/Reproduction

```
(Paddle_d) D:\PaddleDetection-develop>python
Python 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Hint: Your machine support AVX, but the installed paddlepaddle doesn't have avx core. Hence, no-avx core with worse preformance will be imported.
If you like, you could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' to get better performance.
The original error is: No module named 'paddle.fluid.core_avx'
```

**Comment by lyuwenyu** [comment]
安装时候的命令是？

**Comment by lyuwenyu** [comment]
`python -m pip install paddlepaddle-gpu==2.1.2.post101 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html`

**Comment by ResonLee** [comment]
因为安装的是develop版本的，所示安装命令按教程给的是
python -m pip install paddlepaddle-gpu==0.0.0.post101 -f https://www.paddlepaddle.org.cn/whl/windows/gpu/develop.html

**Comment by lyuwenyu** [comment]
移步 ---> https://github.com/PaddlePaddle/Paddle/issues
