### ISSUE TITLE
量化训练后模型速度几乎没有变快

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/PaddleDetection#3939]
![image](https://user-images.githubusercontent.com/26452514/128885417-4e7e19dd-2711-4735-b592-1eee46be3146.png)

**Comment by yghstill** [comment]
@youngstu 由于量化训练只量化了conv等层，像后处理等无法量化，所以导致PPYOLO模型整体量化加速比不高。目前正在适配支持FP16预测，FP16支持更多的kernel，加速效果比int8好点。
