### ISSUE TITLE
性能相近的处理器同一网络性能数据差别很大

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/PaddleDetection#3940]
![image](https://user-images.githubusercontent.com/26452514/128886267-6f419169-80a2-42ba-b9ee-7fe5da8f8719.png)
![image](https://user-images.githubusercontent.com/26452514/128886382-fa0821b3-d2da-44ec-8a5d-982637aa5e65.png)

**Comment by yghstill** [comment]
@youngstu 第一张图是在SD855上4线程测试结果，第二张图是kirin 990上单线程测试结果，SD855和kirin 990本身有性能差异，4线程和单线程也有性能差异
