### ISSUE TITLE
PPYolo_Tiny 是否支持量化训练？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/PaddleDetection#3941]
![image](https://user-images.githubusercontent.com/26452514/128887566-0c65d2a8-904c-4d47-9d4c-70cce7adffbe.png)

**Comment by heavengate** [comment]
这个不是量化训练，是训练完模型之后的后量化

**Comment by youngstu** [comment]
是的，这个是动态离线量化，能否支持量化训练呢？

**Comment by yghstill** [comment]
@youngstu 支持量化训练，参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/slim/quant/ppyolo_mbv3_large_qat.yml 修改即可训练

**Comment by lleesg** [comment]
支持，但测试下来虽然精度下降很少，但速度提升非常有限（5%左右），不知为何。
