### ISSUE TITLE
[BUG]单类别实例分割 map一直为0

### ISSUE THREAD

**Issue by liuxi1007** [PaddlePaddle/PaddleDetection#3942]
### 数据集
对某单个类别进行实例分割，数据集标签只包含一个类别，一张图像中有多个此类别的物体，要求分割出来。
### 训练
PaddleDetection release/2.2版本，数据集标签只包含一个类别的样本，训练loss下降至0.07，可视化结果中mask-map始终为0.
### 疑问
请问这种现象是怎么回事，如何应对？这种情况下的map如何计算？请问是否这种现象与difficult参数有关，还是其他原因？

**Comment by nemonameless** [comment]
使用的哪个模型和训练命令？也可以提供下loss截图。另外可视化结果是否很乱，还是只是mask-map为0？

**Comment by liuxi1007** [comment]
模型：SOLOv2
训练命令：python tools/train.py -c ***.yml --use_vdl=True --eval
可视化结果：loss正常下降，只是mask-map一直为0

**Comment by liuxi1007** [comment]
> 使用的哪个模型和训练命令？也可以提供下loss截图。另外可视化结果是否很乱，还是只是mask-map为0？

模型：SOLOv2
训练命令：python tools/train.py -c ***.yml --use_vdl=True --eval
可视化结果：loss正常下降，只是mask-map一直为0

**Comment by nemonameless** [comment]
使用mask rcnn训练过吗精度正常吗？再检查下是否数据集制作方面没有问题？

**Comment by nemonameless** [comment]
拉取develop分支最新代码试试

**Comment by weihongwei-zg** [comment]
我也是map一直很低，预测结果都没东西

**Comment by liuxi1007** [comment]
请问map为0的问题解决了吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wei Hongwei ***@***.***&gt;
发送时间: 2021年8月23日 18:56
收件人: PaddlePaddle/PaddleDetection ***@***.***&gt;
抄送: liuxi1007 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942)





 
我也是map一直很低，预测结果都没东西
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weihongwei-zg** [comment]
解决了，我没有用最新的代码 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月26日(星期四) 下午4:21
***@***.***&gt;;
抄送:&nbsp;&quot;Wei ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942)

**Comment by liuxi1007** [comment]
您好，请问您是怎么解决的？用的那个版本的代码？感谢～





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wei Hongwei ***@***.***&gt;
发送时间: 2021年8月26日 16:23
收件人: PaddlePaddle/PaddleDetection ***@***.***&gt;
抄送: liuxi1007 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942)





 解决了，我没有用最新的代码 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 ***@***.***&amp;gt; 
 发送时间:&amp;nbsp;2021年8月26日(星期四) 下午4:21 
 ***@***.***&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;Wei ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942) 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weihongwei-zg** [comment]
就是最新版本，重新下载paddledetection，重新安装。如果没有重新安装，用的代码还是原来版本的代码------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月26日(星期四) 下午4:31
***@***.***&gt;;
抄送:&nbsp;&quot;Wei ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942)

**Comment by liuxi1007** [comment]
请问安装的是release 2.2还是develop？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wei Hongwei ***@***.***&gt;
发送时间: 2021年8月26日 16:44
收件人: PaddlePaddle/PaddleDetection ***@***.***&gt;
抄送: liuxi1007 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942)





 就是最新版本，重新下载paddledetection，重新安装。如果没有重新安装，用的代码还是原来版本的代码------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 ***@***.***&amp;gt; 
 发送时间:&amp;nbsp;2021年8月26日(星期四) 下午4:31 
 ***@***.***&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;Wei ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942) 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weihongwei-zg** [comment]
2.2



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月26日(周四) 下午4:53
收件人: ***@***.***&gt;;
抄送: "Wei ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942)




 请问安装的是release 2.2还是develop？ 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: Wei Hongwei ***@***.***&amp;gt; 
 发送时间: 2021年8月26日 16:44 
 收件人: PaddlePaddle/PaddleDetection ***@***.***&amp;gt; 
 抄送: liuxi1007 ***@***.***&amp;gt;, Author ***@***.***&amp;gt; 
 主题: 回复：[PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942) 
 
 
 
 
 
  就是最新版本，重新下载paddledetection，重新安装。如果没有重新安装，用的代码还是原来版本的代码------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  ***@***.***&amp;amp;gt;  
  发送时间:&amp;amp;nbsp;2021年8月26日(星期四) 下午4:31  
  ***@***.***&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;&amp;amp;quot;Wei ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942)  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liuxi1007** [comment]
谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wei Hongwei ***@***.***&gt;
发送时间: 2021年8月26日 16:56
收件人: PaddlePaddle/PaddleDetection ***@***.***&gt;
抄送: liuxi1007 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942)





 2.2 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年8月26日(周四) 下午4:53 
 收件人: ***@***.***&amp;gt;; 
 抄送: "Wei ***@***.******@***.***&amp;gt;; 
 主题: Re: [PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942) 
 
 
 
 
  请问安装的是release 2.2还是develop？  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: Wei Hongwei ***@***.***&amp;amp;gt;  
  发送时间: 2021年8月26日 16:44  
  收件人: PaddlePaddle/PaddleDetection ***@***.***&amp;amp;gt;  
  抄送: liuxi1007 ***@***.***&amp;amp;gt;, Author ***@***.***&amp;amp;gt;  
  主题: 回复：[PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942)  
   
   
   
   
   
   就是最新版本，重新下载paddledetection，重新安装。如果没有重新安装，用的代码还是原来版本的代码------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   ***@***.***&amp;amp;amp;gt;   
   发送时间:&amp;amp;amp;nbsp;2021年8月26日(星期四) 下午4:31   
   ***@***.***&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;&amp;amp;amp;quot;Wei ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942)   
  —  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liuxi1007** [comment]
数据集制作应该是没有问题的，用别的框架的其他实例分割网络训练过。现在用的是paddle detection release2.2版本，训练过程看上去是正常的，loss也没有显示nan，但是验证是结果为空，不知道是不是因为我的数据是单类别的实例分割导致，感觉代码有bug。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: George Ni ***@***.***&gt;
发送时间: 2021年8月12日 10:52
收件人: PaddlePaddle/PaddleDetection ***@***.***&gt;
抄送: liuxi1007 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942)





 
使用mask rcnn训练过吗精度正常吗？再检查下是否数据集制作方面没有问题？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenneng** [comment]
> 我也是map一直很低，预测结果都没东西

请问我用的也是2.2，单类别结果一直没东西咋回事

**Comment by liuxi1007** [comment]
您打开标签的json文件确定一下标签类别数和代码中设置的类别数是否一致。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chenneng ***@***.***&gt;
发送时间: 2021年9月12日 15:55
收件人: PaddlePaddle/PaddleDetection ***@***.***&gt;
抄送: liuxi1007 ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[PaddlePaddle/PaddleDetection] [BUG]单类别实例分割 map一直为0 (#3942)





  
我也是map一直很低，预测结果都没东西
  
请问我用的也是2.2，单类别结果一直没东西咋回事
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by panp4n** [comment]
![image](https://user-images.githubusercontent.com/40445051/165058571-841c48bc-cf8f-40ef-9ecc-b8abcaaa835e.png)
我也遇到了同样的问题，用了SOLOv2各种backbone 都尝试了，参数检查了，Loss如图。Paddledetection2.2-2.4也都试了。还是没有解决。单类别实例分割。
