### ISSUE TITLE
30分钟快速上手PaddleDetection的预测结果为什么会这样啊？

### ISSUE THREAD

**Issue by sinoboy168** [PaddlePaddle/PaddleDetection#3944]
我按照文档上做的训练，数据集也是官网下载的，可是结果为什么会这样呢？路标的label里面就没有aeroplane啊。
谢谢大佬解答！
![road554](https://user-images.githubusercontent.com/41009721/128963694-1f0097c4-6f9a-431e-9f39-6a1fffe0984c.png)

**Comment by nemonameless** [comment]
请问你改动了哪个文件哪些地方吗？ 另外检测库版本是哪个？

**Comment by sinoboy168** [comment]
我改了configs里面的几个设置，训练集没有动。库版本是按照“30分钟快速上手”文档安装的。

**Comment by JackDance** [comment]
配置文件中testdataset路径写错了

**Comment by nemonameless** [comment]
把TestDataset里的anno_path配置成你的val.json的绝对路径试下
#3896
