### ISSUE TITLE
ppyolo_tiny 基于麒麟990处理器性能测试和文档相差30倍

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/PaddleDetection#3945]
![Screenshot from 2021-08-11 11-47-19](https://user-images.githubusercontent.com/26452514/128966552-077ab439-6af0-42fe-92a0-e9b4063841b1.png)
![Screenshot from 2021-08-11 11-45-33](https://user-images.githubusercontent.com/26452514/128966558-34c4530c-cf71-4ba7-8000-27bea9785030.png)

测试环境：华为Mate30 5G版（麒麟990处理器）、armv8、4线程、320x320分辨率

**Comment by heavengate** [comment]
可以排查一下这几个方面：
1. 手机是否处于激活状态，一般建议亮屏测试，保证CPU几个主核在正常运转
2. 手机是否有其他任务，建议请一下缓存任务
3. 测试的时候建议先跑10-20个左右的warmup step，然后再跑预测速度测试，头几次会有一些启动任务比较耗时
4. 模型权重是否正确加载了，预测出来的图片里有没有结果，如果模型权重没有正确加载，会导致输出乱码，nms耗时大幅增加

**Comment by youngstu** [comment]
按上面要求，又重新测试了几次，结果如下，还是差几十倍

![Screenshot from 2021-08-12 10-51-19](https://user-images.githubusercontent.com/26452514/129131088-d1fb8aab-e17c-4a61-840f-f04f29edd714.png)

测试方法：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/lite

能否帮忙确认一下，文档中性能测试数据是不是有问题，不大可能差几十倍呢

**Comment by heavengate** [comment]
已提供测试代码
