### ISSUE TITLE
Yolov3-darknet53预测结果的类别与数据集的类别不对应

### ISSUE THREAD

**Issue by smallwhi** [PaddlePaddle/PaddleDetection#3946]
是预训练权重的问题吗？还是数据集的问题？
训练出来的类别和数据集不一样。如下
![image](https://user-images.githubusercontent.com/66171021/128972861-7a782abb-8cfe-4673-9d42-060c51e4bbc5.png)
而我的类别里明明是松鼠啊
![image](https://user-images.githubusercontent.com/66171021/128972929-1b4cbb45-bff1-4eae-a919-3240320e24c7.png)

**Comment by nemonameless** [comment]
换数据集的话，你改动了哪个文件哪些地方吗？ https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/source/category.py    这里有没有加你自己改的类别？

**Comment by smallwhi** [comment]
我是在aistudio上训练的，只配置了如下文件：
![image](https://user-images.githubusercontent.com/66171021/129042567-bf2ff42b-3119-4727-acd5-3cc4c3b75479.png)
修改了coco_detections.yml中类别数为自己的
![image](https://user-images.githubusercontent.com/66171021/129042606-a6753363-5df1-49fd-8775-04b5677cc0e4.png)
似乎不能改动您说的这个文件
不过似乎id与这个文件对应
请问在aistudio上需要怎么修改？

**Comment by nemonameless** [comment]
把TestDataset里的anno_path配置成你的val.json的绝对路径试下
#3896 #3944

**Comment by smallwhi** [comment]
感谢已经解决了！
这么说，训练的时候有dataset_dir参数，所以可以是相对路径，测试时无法加载anno_path这一个参数，所以加载了默认的分类文件。
那么coco训练识别的其实是id，id对应的name不一样就显示不一样的类别了
