### ISSUE TITLE
训练找不到参数，

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleDetection#3948]
您好我的训练命令是如下，但是会报错，解析不了config，帮忙看看，谢谢
![image](https://user-images.githubusercontent.com/43515926/128987718-79894364-7a33-4885-9d97-e21e97234335.png)

**Comment by nemonameless** [comment]
训练命令语句多加了一个`tools/train.py`

**Comment by zcswdt** [comment]
> 训练命令语句多加了一个`tools/train.py`

谢谢回复
