### ISSUE TITLE
batch-size和显卡爆满问题

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleDetection#3949]
您好，我的显卡内存有8G，但是训练的显卡内存爆掉了，但是我看batch-size=2，如果设置成1的来训练就是单张图片来训练，请问会对训练有影响吗？
![image](https://user-images.githubusercontent.com/43515926/129004263-5e2c6046-13f4-4dd1-88d9-c650994c8484.png)

**Comment by nemonameless** [comment]
batch-size减半，理论上相应lr也减半，训练精度才会和原先基本差不多
