### ISSUE TITLE
使用yolov3_mobilenet_v1_fruit.yml训练出模型，在红米7上运行很慢

### ISSUE THREAD

**Issue by sdjkxhb2016** [PaddlePaddle/PaddleDetection#395]
我把我自己的数据集放到PaddleDetection/dataset/fruit目录，yolov3_mobilenet_v1_fruit.yml 也没有修改，直接用下面的语句训练
!python -u tools/train.py -c configs/yolov3_mobilenet_v1_fruit.yml \
                        --use_tb=True \
                        --tb_log_dir=tb_fruit_dir/scalar \
                        --eval
训练出的模型放到红米7上运行，可以正确检测，就是非常慢，我用Paddle_Lite 的SSD模型测试只要300ms,而用我的模型，要1300-1700ms ,我没有使用slim 压缩模型

**Comment by jerrywgz** [comment]
你训练出的检测模型是怎么在红米7上运行的呢，需要先通过export_model.py将模型转成预测的模型格式

**Comment by sdjkxhb2016** [comment]
不好意思，是我没说清楚，我是先出来模型，再
# 导出YOLOv3模型，输入是3x320x320
!python tools/export_model.py -c configs/yolov3_mobilenet_v1_fruit.yml \
        --output_dir=./inference_model \
        -o weights=output/yolov3_mobilenet_v1_fruit/best_model \
           TestReader.inputs_def.image_shape=[3,608,608]
再用opt 导出model.mb
!/home/aistudio/work/tools/opt \
    --model_file=./inference_model/yolov3_mobilenet_v1_fruit/__model__ \
    --param_file=./inference_model/yolov3_mobilenet_v1_fruit/__params__ \
    --optimize_out_type=naive_buffer \
    --optimize_out=/home/aistudio/work/yolov3_model/lite_model \
    --valid_targets=arm \
    --prefer_int8_kernel=true

**Comment by jerrywgz** [comment]
我查下我们这边的测试数据，另外你自己的数据集和fruit数据集的类别数是一样的吗

**Comment by sdjkxhb2016** [comment]
是的，一样 
![image](https://user-images.githubusercontent.com/19500296/77405708-863cd880-6dee-11ea-802c-4cb0f4ef25c4.png)

**Comment by jerrywgz** [comment]
那你训练的时候使用的类别还是3吗？还是改成157了

**Comment by sdjkxhb2016** [comment]
num_classes: 157 
是157的，放到手机上是可以检测的，只是慢而已

**Comment by jerrywgz** [comment]
我们这边在845和835的芯片上测试yolo跟ssd这两个模型在输入是608的情况下，yolo的耗时大概是ssd的2.5倍左右

**Comment by sdjkxhb2016** [comment]
我现在在手机上是设置4个线程，你的意思是，ssd 在CPU里，比yolo还要更快是吗
这个输入608，和图片大小有没有关系呢，手机拍的照片是很大的

**Comment by jerrywgz** [comment]
我们这边测试是用的相同图片，1，2，4线程都有测试，速度跟我刚说的差不多

**Comment by sdjkxhb2016** [comment]
那我再做一个SSD的模型，看下速度怎样，多谢
