### ISSUE TITLE
两卡训练ppyolo的报错

### ISSUE THREAD

**Issue by mortal-Zero** [PaddlePaddle/PaddleDetection#3952]
环境：Ubuntu16.04
gcc            8.4.0
python       3.7
cuda          10.1
cudnn        7.6.5
paddle       2.1.1
paddledet  2.1.0

您好，我在尝试训练ppyolov2，当设置gpu=0,1时会报错，当改为gpu=0时，就可以正常训练。

终端命令如下：
python -m paddle.distributed.launch --gpus 0,1 tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml --eval

报错信息如下：
-----------  Configuration Arguments -----------
gpus: 0,1
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
run_mode: None
server_num: None
servers: 
training_script: tools/train.py
training_script_args: ['-c', 'configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml', '--eval']
worker_num: None
workers: 
------------------------------------------------
WARNING 2021-08-11 19:45:19,722 launch.py:359] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2021-08-11 19:45:19,722 launch_utils.py:621] Change selected_gpus into reletive values. --ips:0,1 will change into relative_ips:[0, 1] according to your CUDA_VISIBLE_DEVICES:['0', '1', '2', '3']
INFO 2021-08-11 19:45:19,723 launch_utils.py:510] Local start 2 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:52369               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:52369,127.0.0.1:56975       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2021-08-11 19:45:19,723 launch_utils.py:514] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:23739 idx:0
launch proc_id:23744 idx:1
/home/allen/miniconda3/envs/paddle2.1.1/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0811 19:45:21.104879 23739 dynamic_loader.cc:238] You may need to install 'nccl2' from NVIDIA official website: https://developer.nvidia.com/nccl/nccl-downloadbefore install PaddlePaddle.
Traceback (most recent call last):
  File "tools/train.py", line 139, in <module>
    main()
  File "tools/train.py", line 135, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 95, in run
    init_parallel_env()
  File "/home/allen/miniconda3/envs/paddle2.1.1/lib/python3.7/site-packages/ppdet/engine/env.py", line 42, in init_parallel_env
    paddle.distributed.init_parallel_env()
  File "/home/allen/miniconda3/envs/paddle2.1.1/lib/python3.7/site-packages/paddle/distributed/parallel.py", line 196, in init_parallel_env
    parallel_helper._init_parallel_ctx()
  File "/home/allen/miniconda3/envs/paddle2.1.1/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel_helper.py", line 42, in _init_parallel_ctx
    __parallel_ctx__clz__.init()
RuntimeError: (PreconditionNotMet) The third-party dynamic library (libnccl.so) that Paddle depends on is not configured correctly. (error code is libnccl.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:265)

INFO 2021-08-11 19:45:25,745 launch_utils.py:327] terminate all the procs
ERROR 2021-08-11 19:45:25,745 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-08-11 19:45:28,745 launch_utils.py:327] terminate all the procs

**Comment by nemonameless** [comment]
有改动其他配置文件吗？建议使用paddle2.1和PaddleDetection develop分支

**Comment by mortal-Zero** [comment]
> 有改动其他配置文件吗？建议使用paddle2.1和PaddleDetection develop分支

改动了锚点框尺寸，训练批次大小改为了2，验证批次大小改为了1，以及数据集路径，应该不是导致这个问题的原因。
我按照您的建议使用了paddledetection的develop分支，同样是训练ppyolov2，还是出现上述问题，gpus改为0后，单卡训练还是正常，也确实使用了0序号卡
请问可能是我的机器本身的环境导致的吗？

**Comment by ghostxsl** [comment]
> 环境：Ubuntu16.04
> gcc 8.4.0
> python 3.7
> cuda 10.1
> cudnn 7.6.5
> paddle 2.1.1
> paddledet 2.1.0
> 
> 您好，我在尝试训练ppyolov2，当设置gpu=0,1时会报错，当改为gpu=0时，就可以正常训练。
> 
> 终端命令如下：
> python -m paddle.distributed.launch --gpus 0,1 tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml --eval
> 
> ## 报错信息如下：
> ----------- Configuration Arguments -----------
> gpus: 0,1
> heter_worker_num: None
> heter_workers:
> http_port: None
> ips: 127.0.0.1
> log_dir: log
> nproc_per_node: None
> run_mode: None
> server_num: None
> servers:
> training_script: tools/train.py
> training_script_args: ['-c', 'configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml', '--eval']
> worker_num: None
> workers:
> WARNING 2021-08-11 19:45:19,722 launch.py:359] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
> launch train in GPU mode!
> INFO 2021-08-11 19:45:19,722 launch_utils.py:621] Change selected_gpus into reletive values. --ips:0,1 will change into relative_ips:[0, 1] according to your CUDA_VISIBLE_DEVICES:['0', '1', '2', '3']
> INFO 2021-08-11 19:45:19,723 launch_utils.py:510] Local start 2 processes. First process distributed environment info (Only For Debug):
> +=======================================================================================+
> | Distributed Envs Value |
> +---------------------------------------------------------------------------------------+
> | PADDLE_TRAINER_ID 0 |
> | PADDLE_CURRENT_ENDPOINT 127.0.0.1:52369 |
> | PADDLE_TRAINERS_NUM 2 |
> | PADDLE_TRAINER_ENDPOINTS 127.0.0.1:52369,127.0.0.1:56975 |
> | PADDLE_RANK_IN_NODE 0 |
> | PADDLE_LOCAL_DEVICE_IDS 0 |
> | PADDLE_WORLD_DEVICE_IDS 0,1 |
> | FLAGS_selected_gpus 0 |
> | FLAGS_selected_accelerators 0 |
> +=======================================================================================+
> 
> INFO 2021-08-11 19:45:19,723 launch_utils.py:514] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
> launch proc_id:23739 idx:0
> launch proc_id:23744 idx:1
> /home/allen/miniconda3/envs/paddle2.1.1/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
> Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> if data.dtype == np.object:
> W0811 19:45:21.104879 23739 dynamic_loader.cc:238] You may need to install 'nccl2' from NVIDIA official website: https://developer.nvidia.com/nccl/nccl-downloadbefore install PaddlePaddle.
> Traceback (most recent call last):
> File "tools/train.py", line 139, in
> main()
> File "tools/train.py", line 135, in main
> run(FLAGS, cfg)
> File "tools/train.py", line 95, in run
> init_parallel_env()
> File "/home/allen/miniconda3/envs/paddle2.1.1/lib/python3.7/site-packages/ppdet/engine/env.py", line 42, in init_parallel_env
> paddle.distributed.init_parallel_env()
> File "/home/allen/miniconda3/envs/paddle2.1.1/lib/python3.7/site-packages/paddle/distributed/parallel.py", line 196, in init_parallel_env
> parallel_helper._init_parallel_ctx()
> File "/home/allen/miniconda3/envs/paddle2.1.1/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel_helper.py", line 42, in _init_parallel_ctx
> **parallel_ctx__clz**.init()
> RuntimeError: (PreconditionNotMet) The third-party dynamic library (libnccl.so) that Paddle depends on is not configured correctly. (error code is libnccl.so: cannot open shared object file: No such file or directory)
> Suggestions:
> 
> 1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
> 2. Configure third-party dynamic library environment variables as follows:
> 
> * Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
> * Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:265)
> 
> INFO 2021-08-11 19:45:25,745 launch_utils.py:327] terminate all the procs
> ERROR 2021-08-11 19:45:25,745 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
> INFO 2021-08-11 19:45:28,745 launch_utils.py:327] terminate all the procs

看报错信息，应该是你nccl没有正确安装，才导致了你单卡能跑通，多卡跑不起来的情况，再检查一下自己机器的环境呢

**Comment by mortal-Zero** [comment]
> > 环境：Ubuntu16.04
> > gcc 8.4.0
> > python 3.7
> > cuda 10.1
> > cudnn 7.6.5
> > paddle 2.1.1
> > paddledet 2.1.0
> > 您好，我在尝试训练ppyolov2，当设置gpu=0,1时会报错，当改为gpu=0时，就可以正常训练。
> > 终端命令如下：
> > python -m paddle.distributed.launch --gpus 0,1 tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml --eval
> > ## 报错信息如下：
> > ----------- Configuration Arguments -----------
> > gpus: 0,1
> > heter_worker_num: None
> > heter_workers:
> > http_port: None
> > ips: 127.0.0.1
> > log_dir: log
> > nproc_per_node: None
> > run_mode: None
> > server_num: None
> > servers:
> > training_script: tools/train.py
> > training_script_args: ['-c', 'configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml', '--eval']
> > worker_num: None
> > workers:
> > WARNING 2021-08-11 19:45:19,722 launch.py:359] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
> > launch train in GPU mode!
> > INFO 2021-08-11 19:45:19,722 launch_utils.py:621] Change selected_gpus into reletive values. --ips:0,1 will change into relative_ips:[0, 1] according to your CUDA_VISIBLE_DEVICES:['0', '1', '2', '3']
> > INFO 2021-08-11 19:45:19,723 launch_utils.py:510] Local start 2 processes. First process distributed environment info (Only For Debug):
> > +=======================================================================================+
> > | Distributed Envs Value |
> > +---------------------------------------------------------------------------------------+
> > | PADDLE_TRAINER_ID 0 |
> > | PADDLE_CURRENT_ENDPOINT 127.0.0.1:52369 |
> > | PADDLE_TRAINERS_NUM 2 |
> > | PADDLE_TRAINER_ENDPOINTS 127.0.0.1:52369,127.0.0.1:56975 |
> > | PADDLE_RANK_IN_NODE 0 |
> > | PADDLE_LOCAL_DEVICE_IDS 0 |
> > | PADDLE_WORLD_DEVICE_IDS 0,1 |
> > | FLAGS_selected_gpus 0 |
> > | FLAGS_selected_accelerators 0 |
> > +=======================================================================================+
> > INFO 2021-08-11 19:45:19,723 launch_utils.py:514] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
> > launch proc_id:23739 idx:0
> > launch proc_id:23744 idx:1
> > /home/allen/miniconda3/envs/paddle2.1.1/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
> > Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> > if data.dtype == np.object:
> > W0811 19:45:21.104879 23739 dynamic_loader.cc:238] You may need to install 'nccl2' from NVIDIA official website: https://developer.nvidia.com/nccl/nccl-downloadbefore install PaddlePaddle.
> > Traceback (most recent call last):
> > File "tools/train.py", line 139, in
> > main()
> > File "tools/train.py", line 135, in main
> > run(FLAGS, cfg)
> > File "tools/train.py", line 95, in run
> > init_parallel_env()
> > File "/home/allen/miniconda3/envs/paddle2.1.1/lib/python3.7/site-packages/ppdet/engine/env.py", line 42, in init_parallel_env
> > paddle.distributed.init_parallel_env()
> > File "/home/allen/miniconda3/envs/paddle2.1.1/lib/python3.7/site-packages/paddle/distributed/parallel.py", line 196, in init_parallel_env
> > parallel_helper._init_parallel_ctx()
> > File "/home/allen/miniconda3/envs/paddle2.1.1/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel_helper.py", line 42, in _init_parallel_ctx
> > **parallel_ctx__clz**.init()
> > RuntimeError: (PreconditionNotMet) The third-party dynamic library (libnccl.so) that Paddle depends on is not configured correctly. (error code is libnccl.so: cannot open shared object file: No such file or directory)
> > Suggestions:
> > 
> > 1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
> > 2. Configure third-party dynamic library environment variables as follows:
> > 
> > 
> > * Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
> > * Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:265)
> > 
> > INFO 2021-08-11 19:45:25,745 launch_utils.py:327] terminate all the procs
> > ERROR 2021-08-11 19:45:25,745 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
> > INFO 2021-08-11 19:45:28,745 launch_utils.py:327] terminate all the procs
> 
> 看报错信息，应该是你nccl没有正确安装，才导致了你单卡能跑通，多卡跑不起来的情况，再检查一下自己机器的环境呢

好的呢，多谢解答。
