### ISSUE TITLE
GPU单卡训练报错

### ISSUE THREAD

**Issue by CY-GAO222** [PaddlePaddle/PaddleDetection#3959]
![1628752427(1)](https://user-images.githubusercontent.com/70746768/129154872-0469bbfb-2dd4-409c-a574-d128cd9c8260.jpg)
根据教程先export CUDA_VISIBLE_DEVICES=1,
接着python tools/train.py -c configs/yolov3/yolov3_mobilenet_v3_large_270e_coco.yml  --slim configs/slim/quant/yolov3_mobilenet_v3_qat.yml

但是报错：ValueError: The device should not be 'gpu', since PaddlePaddle is not compiled with CUDA

**Comment by ghostxsl** [comment]
应该是你安装的paddle版本不对，需要安装带GPU预编译的版本。

参考官网上安装步骤：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
如pip安装gpu版本命令：python -m pip install paddlepaddle-gpu==2.1.2.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
