### ISSUE TITLE
yolov3_r50vd_dcn_db_obj365_pretrained_coco C++ 

### ISSUE THREAD

**Issue by Sheldonai** [PaddlePaddle/PaddleDetection#396]
Ryolov3_r50vd_dcn_db_obj365_pretrained_coco 使用C++ 预测时 yaml 文件如何配置，我的配置文件如下
DEPLOY:
    USE_GPU: 0
    MODEL_PATH: "yolov3_r50vd_dcn_db_obj365_pretrained_coco"

  
  # 模型文件名
    MODEL_FILENAME: "__model__"
    # 参数文件名
    PARAMS_FILENAME: "__params__"
    # 预测图片的标准输入，尺寸不一致会resize
    EVAL_CROP_SIZE: (608, 608)
    # resize方式，支持 UNPADDING和RANGE_SCALING
    RESIZE_TYPE: "UNPADDING"
    # 短边对齐的长度，仅在RANGE_SCALING下有效
    TARGET_SHORT_SIZE : 800
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    # 图片类型， rgb或者rgba
    IMAGE_TYPE: "rgb"
    # 像素分类数
    NUM_CLASSES: 1
    # 通道数
    CHANNELS : 3
    # 预处理器， 目前提供图像检测的通用处理类DetectionPreProcessor
    PRE_PROCESSOR: "DetectionPreProcessor"
    # 预测模式，支持 NATIVE 和 ANALYSIS
    PREDICTOR_MODE: "ANALYSIS"
    # 每次预测的 batch_size
    BATCH_SIZE : 1
    # 长边伸缩的最大长度，-1代表无限制。
    RESIZE_MAX_SIZE: -1
    FEEDS_SIZE: 3

**Comment by jerrywgz** [comment]
这样配置是会遇到报错吗

**Comment by Sheldonai** [comment]
不会报错，但是识别错误。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wangguanzhong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 下午5:00
收件人:&nbsp;"PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送:&nbsp;"吴翔"<80183376@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] yolov3_r50vd_dcn_db_obj365_pretrained_coco C++  (#396)





 
这样配置是会遇到报错吗

**Comment by sjtubinlong** [comment]
@Sheldonai 您好，请问下具体是什么错误，还有识别出错的图片能否提供下，谢谢

**Comment by qingqing01** [comment]
@Sheldonai 此issue暂时关闭了，有问题，请再建新的issue或open。
