### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleDetection#3961]
![image](https://user-images.githubusercontent.com/43515926/129161951-fa1aeee2-47a1-4d0b-8f44-12b11e46ae8f.png)
很奇怪的是，我给voc.py里面的这些东西注释了，但是还是会报错，真是奇怪啊奇怪
![image](https://user-images.githubusercontent.com/43515926/129163087-b7cfd714-ace9-48c3-915e-5e68302bbad2.png)

**Comment by ghostxsl** [comment]
看报错提示的话应该是没有在您提供的val.txt发现annotations，您可以check一下 val.txt 中的数据格式是否正确。
你注释掉以后要卸载之前安装的paddledetection，重新pip install一下

**Comment by zcswdt** [comment]
> paddledetection

谢谢回复，那训练数据的格式是这样的么？中间的fengefu分隔符是/t还是空格？
![image](https://user-images.githubusercontent.com/43515926/129171887-12fc06d1-f74c-4c7a-8145-0c9ce67d9f94.png)
为什么我在代码中注释了然后还会打印，还要卸载paddledection，那这个代码存在的意义是什么呢？

**Comment by ghostxsl** [comment]
你使用的paddle、paddledetection版本是多少？修改了什么？
你是通过pip install paddledetection以后使用的吗？

**Comment by zcswdt** [comment]
> 你使用的paddle、paddledetection版本是多少？修改了什么？
> 你是通过pip install paddledetection以后使用的吗？

我拉取的镜像，完全按照文档来的，然后是2.1版本的，没用修改过，我是下载的源码使用的，不是pip install paddledection

**Comment by ghostxsl** [comment]
麻烦发一下你修改voc.py之后完整的代码

**Comment by zcswdt** [comment]
> 麻烦发一下你修改voc.py之后完整的代码
![image](https://user-images.githubusercontent.com/43515926/129180862-81c3f519-5e16-4738-a5ae-76f40922d1f0.png)
我就注释了，没修改任何东西，但是还是会打印。
[voc.zip](https://github.com/PaddlePaddle/PaddleDetection/files/6974651/voc.zip)

**Comment by ghostxsl** [comment]
如果你注释了，执行时没生效，我感觉应该是你用的这个镜像原本就安装了ppdet，你可以先pip uninstall一下，再在你这个源码路径下运行一下看看呢

**Comment by zcswdt** [comment]
> 如果你注释了，执行时没生效，我感觉应该是你用的这个镜像原本就安装了ppdet，你可以先pip uninstall一下，再在你这个源码路径下运行一下看看呢

那训练数据的格式是这样的么？中间的分隔符是/t还是空格‘ ’分隔符？
 ![image](https://user-images.githubusercontent.com/43515926/129171887-12fc06d1-f74c-4c7a-8145-0c9ce67d9f94.png)

**Comment by ghostxsl** [comment]
> > 如果你注释了，执行时没生效，我感觉应该是你用的这个镜像原本就安装了ppdet，你可以先pip uninstall一下，再在你这个源码路径下运行一下看看呢
> 
> 那训练数据的格式是这样的么？中间的分隔符是/t还是空格‘ ’分隔符？
> ![image](https://user-images.githubusercontent.com/43515926/129171887-12fc06d1-f74c-4c7a-8145-0c9ce67d9f94.png)

\t或者空格‘ ’分隔符都可以的
