### ISSUE TITLE
文档某处超链接失效

### ISSUE THREAD

**Issue by jhcgt4869** [PaddlePaddle/PaddleDetection#3967]
bug提交来源：https://aistudio.baidu.com/paddle/forum/topic/show/990235

问题地址：https://paddledetection.readthedocs.io/tutorials/Custom_DataSet.html#demo

准备数据里面的方法三中：**添加新数据源**的链接无法实现。

![image](https://user-images.githubusercontent.com/61859193/129225932-9871eb77-5f74-4e9a-8164-f643581c5822.png)

超链接地址：https://paddledetection.readthedocs.io/advanced_tutorials/READER.md#%E6%B7%BB%E5%8A%A0%E6%96%B0%E6%95%B0%E6%8D%AE%E6%BA%90

页面情况：
![image](https://user-images.githubusercontent.com/61859193/129226385-f9c71a04-f661-4cc2-bf69-7e1453049f13.png)

希望能够及时处理

**Comment by heavengate** [comment]
你好，这个文档是之前静态图的文档，我们从2.0版本开始支持了动态图，动态图的文档还在整理，我们会在近期整理更新一版动态图的文档，可以关注一下~
