### ISSUE TITLE
Cascade-Faster-RCNN-CBResNet200vd-FPN

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleDetection#3969]
请问这个文件在哪里压，我在config文件里面没有找到
![image](https://user-images.githubusercontent.com/43515926/129295222-03a896f3-cd9e-4b9c-b79c-a425b132977f.png)

**Comment by nemonameless** [comment]
在static目录下，是以前的静态图模型
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/docs/MODEL_ZOO_cn.md
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/configs/dcn/cascade_rcnn_cbr200_vd_fpn_dcnv2_nonlocal_softnms.yml
#3450

**Comment by zcswdt** [comment]
> 在static目录下，是以前的静态图模型
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/docs/MODEL_ZOO_cn.md
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/configs/dcn/cascade_rcnn_cbr200_vd_fpn_dcnv2_nonlocal_softnms.yml
> #3450

我想用来这个项目参加一下比赛，请问推荐哪个呢，或者 是哪个组合最好呢。谢谢

**Comment by qingqing01** [comment]
如果想选择COCO上表现较好的模型、速度也没有要求的话，可以考虑此模型训练base看下效果。

**Comment by zcswdt** [comment]
> 如果想选择COCO上表现较好的模型、速度也没有要求的话，可以考虑此模型训练base看下效果。

我现在使用这个模型来训练，会报错，DecodeImage模块，这个如何解决呢？
![image](https://user-images.githubusercontent.com/43515926/129338879-5d3e3623-3a6e-4e8d-8e35-b81f390b2765.png)

**Comment by qingqing01** [comment]
使用静态图static模型时，需要pip uninstall paddledet，卸载已安装的动态图PaddleDetection版本:
```
cd static  # 进入static文件夹下，直接使用static文件下静态图的源码
```

**Comment by zcswdt** [comment]
> 使用静态图static模型时，需要pip uninstall paddledet，卸载已安装的动态图PaddleDetection版本:
> 
> ```
> cd static  # 进入static文件夹下，直接使用static文件下静态图的源码
> ```

您好，我在训练的时候还是报错，原因是我给这个Yaml的coco加载方式改成了voc的，但是会报错。如下是我的改动：
![image](https://user-images.githubusercontent.com/43515926/129504874-57f90af8-d197-439e-b3cb-b94cac970364.png)

![image](https://user-images.githubusercontent.com/43515926/129504912-48c8f533-23e9-4158-994b-daf2b2037c0d.png)
