### ISSUE TITLE
picodet模型量化训练如何配置？

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/PaddleDetection#3972]
picodet模型量化训练是否支持，需要如何配置？

**Comment by qingqing01** [comment]
配置参考这里：

https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/slim/quant/picodet_s_mbv3_320_quant_coco.yml

训练流程参考：

https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/slim#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
