### ISSUE TITLE
mask rcnn 训练问题

### ISSUE THREAD

**Issue by 827346462** [PaddlePaddle/PaddleDetection#3974]
![image](https://user-images.githubusercontent.com/50097546/129317102-c58e6e4e-7c9b-4f3f-b897-b743bc33d43e.png)

我用自己训练的数据集在win10上可以进行训练。但是在ai studio 进行训练就出现这个问题

**Comment by qingqing01** [comment]
麻烦描述下AiStudio上 PaddleDetection版本、以及您修改了啥？ PaddleDetection源码里没有API的输入参数有` pad_gt`，您看下是不是配置文件改错了~
