### ISSUE TITLE
实际自己检测结果 和 评估出来的 AP 值 差距很大

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#3976]
自己看infer来的的结果 准确率 很高 但是 评估出来后的 AP 值却很低 什么情况？
![image](https://user-images.githubusercontent.com/88072901/129430123-0241345e-14bb-42f5-9953-0f68ec503074.png)

**Comment by heavengate** [comment]
第一行那个是IoU=0.5:0.95的评估标准，这个标准比较严格，有53.8%就是挺高的精度了，一般情况下我们看第二行那个IoU=0.5的标准就可以了，96.2%的精度也挺高的了

**Comment by STUSER001** [comment]
这个意思啊  那下面的 表格 为啥 显示的 Ap 这么低呢？？

**Comment by heavengate** [comment]
> 这个意思啊 那下面的 表格 为啥 显示的 Ap 这么低呢？？

表格里的API也是mAP(0.5:0.95)这个维度的

**Comment by STUSER001** [comment]
好的 明白了 谢谢
