### ISSUE TITLE
[Other General Issues]

### ISSUE THREAD

**Issue by CY-GAO222** [PaddlePaddle/PaddleDetection#3978]
安装好环境，执行python ppdet/modeling/tests/test_architectures.py
报错如下：
ImportError: cannot import name '_api' from 'matplotlib' (/home/gcy/.local/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/matplotlib/__init__.py)

**Comment by heavengate** [comment]
看报错信息是`pycocotools` import matplotlib._api出错了，是不是matplotlib没有正确安装呢，可以重新安装一下matplotlib和pycocotools试下
