### ISSUE TITLE
[Other General Issues]

### ISSUE THREAD

**Issue by liu100286** [PaddlePaddle/PaddleDetection#3979]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## 描述问题/Describe the bug
/home/aistudio/PaddleDetection
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 102, in run
    trainer = Trainer(cfg, mode='train')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 62, in __init__
    self.loader = create('{}Reader'.format(self.mode.capitalize()))(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/core/workspace.py", line 276, in create
    return cls(**cls_kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/reader.py", line 236, in __init__
    num_classes, collate_batch, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/reader.py", line 151, in __init__
    collate_batch)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/reader.py", line 69, in __init__
    super(BatchCompose, self).__init__(transforms, num_classes)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/reader.py", line 47, in __init__
    f = op_cls(**v)
TypeError: __init__() got an unexpected keyword argument 'pad_gt'

## 复现/Reproduction

https://aistudio.baidu.com/aistudio/projectdetail/2283437?forkThirdPart=1&shared=1
在我的公开版本中可复现此问题
需要解压PaddleDetection
未对yml配置文件进行修改，直接报错

1. 您使用的命令是？/What command or script did you run?

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by liu100286** [comment]
问题已解决  把PaddleDetection 下的ppnet 复制到 /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/目录下
把原来的覆盖掉即可

**Comment by heavengate** [comment]
如果修改了代码的话可以`pip uninstall paddledet`然后`python setup.py install`重新安装一下
