### ISSUE TITLE
建议将paddledetection和paddleseg以及classification等合并成paddleCV

### ISSUE THREAD

**Issue by gengyanlei** [PaddlePaddle/PaddleDetection#398]
官方预训练的模型都放在paddleCV中，更有利于百度paddle的推广。

**Comment by willthefrog** [comment]
呃，这两个都是从models/PaddleCV里拆出来的。。。classification也正准备拆出来。。。 🤦‍♂️

**Comment by gengyanlei** [comment]
呃。。。好吧，之前没用过paddle，现在看了看教程，期待更好。看了看paddleHub全覆盖，棒棒的，后面尝试一下。个人喜欢1个包全覆盖(CV+NLP)
