### ISSUE TITLE
[BUG]安装 PaddleDetection 后验证不能通过

### ISSUE THREAD

**Issue by yang20085936** [PaddlePaddle/PaddleDetection#3980]
安装环境满足安装文档中的环境要求：
PaddlePaddle 2.1
OS 64位操作系统
Python 3(3.5.1+/3.6/3.7/3.8/3.9)，64位版本
pip/pip3(9.0.1+)，64位版本
CUDA >= 10.1
 cuDNN >= 7.6

安装完后运行测试代码
`python ppdet/modeling/tests/test_architectures.py `
时候报错：
`Ran 5 tests in 0.088s
FAILED (errors=5)`

更新paddlepaddle之后报错依旧。cuda和cudnn正常安装，机器上TF和torch可在GPU环境下正常运行。
详细报错代码如下：
`/home/usename/anaconda3/envs/paddle1/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0814 22:44:48.561463  8161 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 10.2
W0814 22:44:48.561690  8161 dynamic_loader.cc:267] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
EEEEE
======================================================================
ERROR: test_trainer (__main__.TestCascadeRCNN)
`

**Comment by heavengate** [comment]
```
 The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is libcudnn.so: cannot open shared object file: No such file or directory)
```
看报错信息是没找到cuDNN，可以排查一下cuDNN是否正确安装，以及安装的cuDNN版本和Paddle需求的cuDNN版本是否一致
