### ISSUE TITLE
[论文复现] 请问有torchvision.ops.batched_nms这个算子对应的实现吗

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleDetection#3981]
请问有torchvision.ops.batched_nms这个算子对应的实现吗， 比如Matrix NMS算子是否能够替代这个？

**Comment by qingqing01** [comment]
`multiclass_nms` 对应`torchvision.ops.batched_nms`功能：

https://github.com/PaddlePaddle/PaddleDetection/blob/4c09bff65c5a2906b9059b328c1cf8fe31417c46/ppdet/modeling/ops.py#L873

输入:  注意输入shape不同、Paddle用rois_num表示每个样本的box长度。Paddle多了更多阈值控制的功能。
输出：multiclass_nms的直接输出了score、label、box，也可以输出indices。torchvision只输出indices。

https://github.com/PaddlePaddle/PaddleDetection/blob/4c09bff65c5a2906b9059b328c1cf8fe31417c46/ppdet/modeling/ops.py#L941
