### ISSUE TITLE
关于S2ANet的问题

### ISSUE THREAD

**Issue by 15050188022** [PaddlePaddle/PaddleDetection#3982]
在我使用sa2net训练一个obb目标检测数据集时发现，infer时同一个目标会有多于一个的预测框，并且置信度不同。不知道这种情况时是否在论文里就是如此？我理解或许应该取置信度最高的一个预测框
![Uploading 4.png…]()
[4.txt](https://github.com/PaddlePaddle/PaddleDetection/files/6989514/4.txt)

**Comment by wangxinxin08** [comment]
这个是可能存在的，infer的时候并不知道哪些预测框对应于同一个目标，一般去除这种情况的方式是NMS，你可以调整下NMS的阈值看下

**Comment by 15050188022** [comment]
> 这个是可能存在的，infer的时候并不知道哪些预测框对应于同一个目标，一般去除这种情况的方式是NMS，你可以调整下NMS的阈值看下

即使调整NMS的阈值，也会存在同一目标出现多个预测框。我记得NMS中有一步是比较摸个候选框与其他候选框的IOU，超过某个阈值则删去，不过我没找到你们代码里这部分的NMS在哪里，能指点一下吗

**Comment by 15050188022** [comment]
> > 这个是可能存在的，infer的时候并不知道哪些预测框对应于同一个目标，一般去除这种情况的方式是NMS，你可以调整下NMS的阈值看下
> 
> 即使调整NMS的阈值，也会存在同一目标出现多个预测框。我记得NMS中有一步是比较摸个候选框与其他候选框的IOU，超过某个阈值则删去，不过我没找到你们代码里这部分的NMS在哪里，能指点一下吗

![142](https://user-images.githubusercontent.com/30464411/129854555-6ef25bcf-2cd5-4dba-845e-bba7f0f9104b.png)
类似于这种情况，同一目标被预测为不同的类别，预测框之间的IOU极高，接近1，置信度也很接近，小于0.01，调整过nms阈值，哪怕设为0也无法解决。这时候是不是需要判断一下如果当IOU超过多少时比较一下类别置信度并且只取类别置信度大的那个框

**Comment by wangxinxin08** [comment]
NMS的配哦指在这里https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/dota/_base_/s2anet.yml#L51, 文档参考https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/layers_cn/multiclass_nms_cn.html#multiclass-nms，multiclass nms是对每一个类别分别进行NMS，是标准的NMS实现。你可能需要的cross class的NMS，可能需要自己修改一下代码，比如把所有的类别都设置成一样的。另外，你可以看一下为什么会出现score如此接近的情况？猜测是每一个class过于相近

**Comment by 15050188022** [comment]
> NMS的配哦指在这里https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/dota/_base_/s2anet.yml#L51, 文档参考[https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/layers_cn/multiclass_nms_cn.html#multiclass-nms，multiclass](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/layers_cn/multiclass_nms_cn.html#multiclass-nms%EF%BC%8Cmulticlass) nms是对每一个类别分别进行NMS，是标准的NMS实现。你可能需要的cross class的NMS，可能需要自己修改一下代码，比如把所有的类别都设置成一样的。另外，你可以看一下为什么会出现score如此接近的情况？猜测是每一个class过于相近

谢谢你的耐心解答。的确是因为比较细粒度的检测，所以score会比较接近。关于cross class的NMS实现请问有什么参考吗？或者有没有考虑过将其加入到PaddleDetection中呢？感谢你们的开源贡献。

**Comment by wangxinxin08** [comment]
目前PaddleDetection里面暂时没有实现，你需要自己添加一些代码来实现，思路基本上是将[N, C, M]的score取max得到[N, 1, M]的score，取argmax得到[N, 1, M]类别信息cls，然后设置multiclass nms的return index获取keep_idx, 使用keep_idx索引cls，得到真实的类别

**Comment by 15050188022** [comment]
> 目前PaddleDetection里面暂时没有实现，你需要自己添加一些代码来实现，思路基本上是将[N, C, M]的score取max得到[N, 1, M]的score，取argmax得到[N, 1, M]类别信息cls，然后设置multiclass nms的return index获取keep_idx, 使用keep_idx索引cls，得到真实的类别

你们的代码封装程度太高啦，我尝试一下。谢谢你的耐心解答。

**Comment by thinkthinking** [comment]
如果未解决可以重新打开该issue。
