### ISSUE TITLE
stadic分支下训练数据coco格式改voc报错

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleDetection#3985]
您好，我在训练的时候还是报错，原因是我给这个Yaml的coco加载方式改成了voc的，但是会报错。如下是我的改动：
![image](https://user-images.githubusercontent.com/43515926/129504874-57f90af8-d197-439e-b3cb-b94cac970364.png)

![image](https://user-images.githubusercontent.com/43515926/129504912-48c8f533-23e9-4158-994b-daf2b2037c0d.png)

**Comment by nemonameless** [comment]
静态图下使用和动态图的配置略有不同，请参考静态图的相关voc的配置写法，比如 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/configs/yolov3_darknet_voc.yml
#3969

**Comment by zcswdt** [comment]
> 静态图下使用和动态图的配置略有不同，请参考静态图的相关voc的配置写法，比如 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/static/configs/yolov3_darknet_voc.yml
> #3969

您好，请教一下，在静态图分支里面的label_list这个参数怎么指定，还有就是use_default_label这个是什么意思呢？谢谢
![image](https://user-images.githubusercontent.com/43515926/129533987-735b0c8e-776b-4c69-846f-a7605ec9dad2.png)

**Comment by yghstill** [comment]
@zcswdt use_default_label表示是否使用voc默认的label list，如果自定义数据集，这个字段设置成false就行
