### ISSUE TITLE
[BUG] cascadeRcnn进行目标检测模型训练时第二轮训练结束后报错

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/PaddleDetection#3987]
在使用cascadeRcnn进行目标检测模型训练时，第二轮训练结束后，报如下错误：
![1123](https://user-images.githubusercontent.com/18167382/129540947-c54e139d-b866-4829-98d1-c97c70a30bc3.png)
查看了配置文件，感觉也没有哪里不妥，最后在群里大佬的指导下，根据错误提示，修改了配置文件中的
`BBoxPostProcess:
  decode:
    name: RCNNBox
    prior_box_var: [30.0, 30.0, 15.0, 15.0]
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.05
    nms_threshold: 0.5
`
将 score_threshold和nms_threshold都设置为0,解决了问题
分析原因如下：
配置文件中关于nms的两个阈值有些高，最终导致第一轮评估没有检测到框，最终导致无法计算mAP而引发了报错
建议官方能做个判断，避免在该情况下导致无法计算mAP，最终出现问题，同时也希望官方在出现异常时，给出直接提示，而不是截图中的那种提示，太隐晦了。

**Comment by yghstill** [comment]
@yuyangup 感谢反馈，我们测试定位下问题

**Comment by jerrywgz** [comment]
我这边使用PaddleDetection release/2.2 分支测试cascade rcnn，只使用初始化权重进行预测，最终是没有报错的。看报错信息是后处理解码的时候报错，理论上还没有到nms的阶段。可以先试下release/2.2分支，如果还有问题可以提供下权重我再测下

**Comment by huilin16** [comment]
我记得5月份好像出现过这个问题，原因是预测结果为空，处理空结果的代码位置错了，但后来这里的问题被修复了，空结果不会报错了应该
