### ISSUE TITLE
paddledetection 训练中断

### ISSUE THREAD

**Issue by sosan-nian** [PaddlePaddle/PaddleDetection#3989]
使用2.1 运行yolov3_mobilenet_v1_roadsign.yml训练过程中断
![图片](https://user-images.githubusercontent.com/82444943/129574007-e4498afe-e6f0-4b00-8ef4-01227833911e.png)

**Comment by yghstill** [comment]
@sosan-nian Windows小部分环境 训练会出现中断的情况，目前这个问题仍在解决中

**Comment by lazyn1997** [comment]
> @sosan-nian Windows小部分环境 训练会出现中断的情况，目前这个问题仍在解决中
有同样的情况出现，使用配置文件ppyolov2_r50vd_dcn.yml
