### ISSUE TITLE
如何给SSD模块添加mask分支

### ISSUE THREAD

**Issue by gujingxiao** [PaddlePaddle/PaddleDetection#399]
如题，我在做一个项目，需要给SSD模块添加mask分支，让SSD检测bbox的同时也能够进行实例分割，目前通过对paddledetection中ssd代码的梳理，我想在
        locs, confs, box, box_var = self.multi_box_head(
            inputs=body_feats, image=im, num_classes=self.num_classes)
这个后面添加mask分支，但是参考工程里面只有mask rcnn的例子，我研究了一阵子毫无头绪，因为mask rcnn里面需要选定proposals，再进行roialign，然后才能处理mask，维度各方面都需要对应。SSD的话因为已经有anchor出来了，我想直接用multi_box_head的结果处理mask，不知道有没有这方面的例子，或者请大佬给讲解一下。十分感谢。

**Comment by willthefrog** [comment]
没有听说过这种设计，如果需要单阶段实例分割模型，可以参考 [yoloact](https://arxiv.org/abs/1904.02689) 或者  [solov2](https://arxiv.org/abs/2003.10152)。

**Comment by FDInSky** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/modeling/architectures/ssd.py参考ssd的71，81行获取feat和bbox之后，然后用roi_laign/roi_pool获取新的feat，最后把feat和bbox送入mask head里，基本就可以完成mask分支，当然这里面你要注意一下这些tensor形状的适配
