### ISSUE TITLE
Paddle-TRT 静态图版本的CascadeRCNN在fp16精度下速度没有提升，显存反而增大了

### ISSUE THREAD

**Issue by wenli1216cy** [PaddlePaddle/PaddleDetection#3993]
paddlepaddle使用的2.1.1,显卡是3090，已经安装tensorrt和paddle包。--run_mode=trt_fp16

**Comment by wangxinxin08** [comment]
Paddle TRT静态图版本的TRT速度可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/static/docs/advanced_tutorials/deploy/BENCHMARK_INFER_cn.md

**Comment by wenli1216cy** [comment]
> Paddle TRT静态图版本的TRT速度可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/static/docs/advanced_tutorials/deploy/BENCHMARK_INFER_cn.

**Comment by wenli1216cy** [comment]
> > Paddle TRT静态图版本的TRT速度可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/static/docs/advanced_tutorials/deploy/BENCHMARK_INFER_cn.

谢谢，我找到速度没有提升的原因了
