### ISSUE TITLE
使用训练好的模型评估fps时，batch_size必须设为1吗

### ISSUE THREAD

**Issue by lao-xu** [PaddlePaddle/PaddleDetection#3994]
使用训练好的模型评估fps时，batch_size必须设为1吗？因为设置不同的batch_size得到的fps不同。哪个为准？

**Comment by wangxinxin08** [comment]
一般使用deploy/python/infer.py去测速，大多数模型的测速结果是在bs=1下测的

**Comment by lao-xu** [comment]
> 一般使用deploy/python/infer.py去测速，大多数模型的测速结果是在bs=1下测的

一定要用deploy吗，他与release分支有何差异？另外detection套件里提到推理时间(fps): 推理时间是在一张Tesla V100的GPU上通过'tools/eval.py'测试所有验证集得到，单位是fps(图片数/秒), cuDNN版本是7.5，包括数据加载、网络前向执行和后处理, batch size是1。
可是batch size是1时得到的fps就会很低，无法得到套件里基线模型表格所示的fps

**Comment by wangxinxin08** [comment]
release分支包含deploy，推荐使用deploy测速，这个和部署时是一致的
