### ISSUE TITLE
使用提供的solov2_r50_enhance_coco.pdparams 模型推理时，效果较差，参数应该如何设置？

### ISSUE THREAD

**Issue by lcc157** [PaddlePaddle/PaddleDetection#3997]
python tools/infer.py -c configs/solov2/solov2_r50_enhance_coco.yml -o weights=weights/solov2_r50_enhance_coco.pdparams --infer_img=demo/000000570688.jpg
![000000570688(1)](https://user-images.githubusercontent.com/69669353/129676822-dbeafcb2-46d3-47de-87d9-76b7d8736afa.jpg)

打印的推理时间（outs = self.model(data)）
[08/17 14:30:31] ppdet.engine INFO: forwoard times in 0.15596437454223633
[08/17 14:30:31] ppdet.engine INFO: Detection bbox results save in output/000395.jpg

**Comment by yghstill** [comment]
@lcc157 预训练模型上传有问题，正在解决中

**Comment by lcc157** [comment]
------------------ Inference Time Info ----------------------
total_time(ms): 77568.20000000001, img_num: 484
average latency time(ms): 160.26, QPS: 6.239670sha
preprocess_time(ms): 81.70, inference_time(ms): 78.50, postprocess_time(ms): 0.00  

这是在Tesla P40卡sha，基于python部署推理的时间消耗，inference_time大约12.7fps, 这是正常的吗？

**Comment by lcc157** [comment]
------------------ Inference Time Info ----------------------
total_time(ms): 77568.20000000001, img_num: 484
average latency time(ms): 160.26, QPS: 6.239670sha
preprocess_time(ms): 81.70, inference_time(ms): 78.50, postprocess_time(ms): 0.00&nbsp;&nbsp;


您好，这是在Tesla P40卡，基于python部署推理的时间消耗（configs/weights:solov2_r50_enhance），inference_time大约12.7fps, 请问这是正常的吗？





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Guanghua ***@***.***&gt;; 
发送时间: 2021年8月20日(星期五) 下午4:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] 使用提供的solov2_r50_enhance_coco.pdparams 模型推理时，效果较差，参数应该如何设置？ (#3997)





 
@lcc157 预训练模型上传有问题，正在解决中
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yghstill** [comment]
@lcc157 solov2_r50_enhance_coco.pdparams 已重新训练上传，mask AP：39.3

**Comment by yghstill** [comment]
@lcc157 P40上12.7FPS的预测耗时是符合预期的
