### ISSUE TITLE
coco数据集的标注格式能直接用吗

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleDetection#3999]
您好，coco数据集的标注格式能直接用吗？我按照coco官网的数据集格式准备了json文件，字段和官方的一样，如果用的话需要怎么改呢？ 谢谢
coco数据集的json格式如下。

{
"info": info,
"images": [image],
"annotations": [annotation],
"licenses": [license],
}

image{
"id": int, "width": int, "height": int, "file_name": str, "license": int, "flickr_url": str, "coco_url": str, "date_captured": datetime,
}

annotation{
"id": int,
"image_id": int,
"category_id": int,
"segmentation": RLE or [polygon],
"area": float,
"bbox": [x,y,width,height],
"iscrowd": 0 or 1,
}

**Comment by wangxinxin08** [comment]
如果格式与cooc一致，可以直接使用，实例分割可以在configs/datasets/coco_instance.yml上修改数据集的num_classes和相关路径，目标检测可以在configs/datasets/coco_detection.yml上修改数据集的num_classes和相关路径

**Comment by kingbirdWc** [comment]
> 如果格式与cooc一致，可以直接使用，实例分割可以在configs/datasets/coco_instance.yml上修改数据集的num_classes和相关路径，目标检测可以在configs/datasets/coco_detection.yml上修改数据集的num_classes和相关路径

您好，onfigs/datasets/coco_detection.yml的data_fields的字段gt_bbox gt_class在coco数据集上是没有的，我该改哪个呢？谢谢
TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

**Comment by wangxinxin08** [comment]
不用修改，保持默认就行

**Comment by kingbirdWc** [comment]
谢谢，可以运行了
