### ISSUE TITLE
yolov3-anchor调整，出现map不增反降的现象

### ISSUE THREAD

**Issue by zimoqingfeng** [PaddlePaddle/PaddleDetection#400]
同学您好，我在配置文件yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco.yml中修改了anchor size的设置，尝试用自己在数据集上聚类的anchor结果进行训练，但是map不增反降。请问可能是什么原因呢。。
----------------
优化前anchor设置：

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01
  drop_block: true
----------------
优化后anchor设置：
YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[18, 22], [30, 34], [40, 54],
            [66, 97], [69, 55], [97, 165],
            [143, 100], [159, 273], [297, 147]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01
  drop_block: true

----------------
辛苦啦

**Comment by FDInSky** [comment]
你的意思是默认的anchor配置的mAP效果差一些？

**Comment by zimoqingfeng** [comment]
默认的要好一些，但是我的训练集不是coco。调整过后变差了

**Comment by zimoqingfeng** [comment]
我发现我的dataloader的yml文件内的anchor size还没有调整，可能是这个原因。

**Comment by heavengate** [comment]
> 我发现我的dataloader的yml文件内的anchor size还没有调整，可能是这个原因。

应该是这个原因，另外你聚类的时候是在原图尺度的bbox上聚类的还是再608*608尺度的bbox上聚类的

**Comment by zimoqingfeng** [comment]
608*608 这个注意啦
