### ISSUE TITLE
按照MODEL_TECHNICAL.md新增architecture无法使用tools/export_model.py导出

### ISSUE THREAD

**Issue by songrui2009** [PaddlePaddle/PaddleDetection#4000]
如题，发现_dump_infer_config中对config['architecture']有检测，值必须是，TRT_MIN_SUBGRAPH中预定义的；自定义Architecture无法支持导出model?还是需要别的配置？

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/engine/export_utils.py#L44

**Comment by songrui2009** [comment]
就是这个文件

**Comment by lyuwenyu** [comment]
没有其他特殊的配置了

**Comment by songrui2009** [comment]
那就是无法导出自定义architecture？还是说把自定义的architecture加入这个数组中？加入的话，对应的数字填多少？

**Comment by songrui2009** [comment]
MODEL_TECHNICAL.md中增加自定义architecture的部分，应该没提到需要修改这个数组

**Comment by lyuwenyu** [comment]
官方支持的就是那个列表里的  其他的你可以加一下尝试一下

**Comment by songrui2009** [comment]
想从整体结构上确认一下paddledetection默认支持就数组里的那些；但底层paddlepaddle是能够支持自定义的architecture的，对不？

**Comment by lyuwenyu** [comment]
是的
