### ISSUE TITLE
ppyolo模型在预测图片时，有的图片是正常显示预测，有的图片是经过处理之后的。

### ISSUE THREAD

**Issue by yumeng88** [PaddlePaddle/PaddleDetection#4001]
![53451180385503412](https://user-images.githubusercontent.com/56550062/129823873-7df774d1-4a8f-4a40-b5d8-7ceb480fc0be.png)
![56419621075202304](https://user-images.githubusercontent.com/56550062/129824005-6ac77789-a28f-4ade-9045-96cb83b7c264.png)

**Comment by yumeng88** [comment]
这是同一个文件夹下面的图片，为什么图片显示的都不一样？？？

**Comment by lyuwenyu** [comment]
看看reader里 有什么数据预处理没

**Comment by yumeng88** [comment]
@lyuwenyu 谢谢你的回答，即使包含预处理的情况下，对于同一次预测的结果怎么有的是预处理有的不是预处理，这。。。。。

**Comment by lyuwenyu** [comment]
预处理里会有random的操作嘛

**Comment by yumeng88** [comment]
@lyuwenyu 是有这个操作,不明白为什么预测的时候还要进行预处理,还有一个文件夹全部是第一张图的情况...还有的文件夹是全部没有处理....我是将这个操作关掉就能解决问题吗?

**Comment by lyuwenyu** [comment]
test_reader啊
