### ISSUE TITLE
reader.yml中的数据增强配置的 { } 是按照默认参数增强吗？

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleDetection#4005]
您好，请问reader.yml中的数据增强配置的 { } 是按照这个类的__init__函数里的默认参数增强吗？如下面的Decode RandomDistort RandomCrop RandomFlip。谢谢
 sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}

**Comment by lyuwenyu** [comment]
是

**Comment by kingbirdWc** [comment]
谢谢
