### ISSUE TITLE
如果一个图片没有任何对应的标注框，那么这个图在训练的时候会被自动舍弃吗？

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleDetection#4006]
你会，如果一个图片没有任何对应的标注框，那么这个图在训练的时候会被自动舍弃吗？

**Comment by lyuwenyu** [comment]
默认会舍弃 在`allow_empty`
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/data/source/coco.py#L51

**Comment by kingbirdWc** [comment]
谢谢

**Comment by annzheng** [comment]
> 默认会舍弃 在`allow_empty`
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/data/source/coco.py#L51

也就是说无标注框图片不会对训练造成影响是吗？
