### ISSUE TITLE
profiling report怎么解读？

### ISSUE THREAD

**Issue by sdnusqy-art** [PaddlePaddle/PaddleDetection#4009]
开启config.EnableProfile()后，打印的profiling report看不懂，跟我打印的时间无法对应，能解释一下profiling report中时间主要是哪部分时间吗？
paddle: 2.1.1
paddledetection: cpp deploy  
os: ubuntu 18.4.1
cuda: 10.2
cudnn:7.6.5
tensorRT:6.0.1.8
显卡：nvidia v100

![无标题](https://user-images.githubusercontent.com/73977336/129880992-747cac29-0a6b-4fad-b170-3ac5c3572d62.png)

**Comment by lyuwenyu** [comment]
cpu和gpu是并行执行的，所以时间不能直接加。可以单独看cpu或gpu的时间，做op之间的性能比较。
