### ISSUE TITLE
blazeface model inference 

### ISSUE THREAD

**Issue by Amanda-Barbara** [PaddlePaddle/PaddleDetection#401]
how to use .\detection_demo.exe with blazeface model,thanks,

**Comment by still-wait** [comment]
C++ inference please reference [Official tutorial documentation](https://paddledetection.readthedocs.io/advanced_tutorials/inference/index.html), include `export model` and [ inference & deployment](https://paddledetection.readthedocs.io/advanced_tutorials/inference/DEPLOYMENT.html#id8) etc.

**Comment by Amanda-Barbara** [comment]
@still-wait How can I use C++ inference to run blazeface model ? I've run succeed by the official example step by step, but the blazeface model like this:
batch_norm_0.b_0
batch_norm_0.w_0
batch_norm_0.w_1
batch_norm_0.w_2
batch_norm_1.b_0
batch_norm_1.w_0
batch_norm_1.w_1
batch_norm_1.w_2
batch_norm_10.b_0
batch_norm_10.w_0
batch_norm_10.w_1
batch_norm_10.w_2
batch_norm_11.b_0
batch_norm_11.w_0
batch_norm_11.w_1
batch_norm_11.w_2
batch_norm_12.b_0
batch_norm_12.w_0
batch_norm_12.w_1
batch_norm_12.w_2
batch_norm_13.b_0
batch_norm_13.w_0
batch_norm_13.w_1
batch_norm_13.w_2
batch_norm_14.b_0
batch_norm_14.w_0
batch_norm_14.w_1
batch_norm_14.w_2
batch_norm_15.b_0
batch_norm_15.w_0
batch_norm_15.w_1
batch_norm_15.w_2
batch_norm_16.b_0
batch_norm_16.w_0
batch_norm_16.w_1
batch_norm_16.w_2
batch_norm_17.b_0
batch_norm_17.w_0
batch_norm_17.w_1
batch_norm_17.w_2
batch_norm_18.b_0
batch_norm_18.w_0
batch_norm_18.w_1
batch_norm_18.w_2
batch_norm_19.b_0
batch_norm_19.w_0
batch_norm_19.w_1
batch_norm_19.w_2
batch_norm_2.b_0
batch_norm_2.w_0
batch_norm_2.w_1
batch_norm_2.w_2
batch_norm_20.b_0
batch_norm_20.w_0
batch_norm_20.w_1
batch_norm_20.w_2
batch_norm_21.b_0
batch_norm_21.w_0
batch_norm_21.w_1
batch_norm_21.w_2
batch_norm_22.b_0
batch_norm_22.w_0
batch_norm_22.w_1
batch_norm_22.w_2
batch_norm_23.b_0
batch_norm_23.w_0
batch_norm_23.w_1
batch_norm_23.w_2
batch_norm_24.b_0
batch_norm_24.w_0
batch_norm_24.w_1
batch_norm_24.w_2
batch_norm_25.b_0
batch_norm_25.w_0
batch_norm_25.w_1
batch_norm_25.w_2
batch_norm_26.b_0
batch_norm_26.w_0
batch_norm_26.w_1
batch_norm_26.w_2
batch_norm_27.b_0
batch_norm_27.w_0
batch_norm_27.w_1
batch_norm_27.w_2
batch_norm_28.b_0
batch_norm_28.w_0
batch_norm_28.w_1
batch_norm_28.w_2
batch_norm_29.b_0
batch_norm_29.w_0
batch_norm_29.w_1
batch_norm_29.w_2
batch_norm_3.b_0
batch_norm_3.w_0
batch_norm_3.w_1
batch_norm_3.w_2
batch_norm_30.b_0
batch_norm_30.w_0
batch_norm_30.w_1
batch_norm_30.w_2
batch_norm_31.b_0
batch_norm_31.w_0
batch_norm_31.w_1
batch_norm_31.w_2
batch_norm_32.b_0
batch_norm_32.w_0
batch_norm_32.w_1
batch_norm_32.w_2
batch_norm_33.b_0
batch_norm_33.w_0
batch_norm_33.w_1
batch_norm_33.w_2
batch_norm_34.b_0
batch_norm_34.w_0
batch_norm_34.w_1
batch_norm_34.w_2
batch_norm_35.b_0
batch_norm_35.w_0
batch_norm_35.w_1
batch_norm_35.w_2
batch_norm_36.b_0
batch_norm_36.w_0
batch_norm_36.w_1
batch_norm_36.w_2
batch_norm_37.b_0
batch_norm_37.w_0
batch_norm_37.w_1
batch_norm_37.w_2
batch_norm_4.b_0
batch_norm_4.w_0
batch_norm_4.w_1
batch_norm_4.w_2
batch_norm_5.b_0
batch_norm_5.w_0
batch_norm_5.w_1
batch_norm_5.w_2
batch_norm_6.b_0
batch_norm_6.w_0
batch_norm_6.w_1
batch_norm_6.w_2
batch_norm_7.b_0
batch_norm_7.w_0
batch_norm_7.w_1
batch_norm_7.w_2
batch_norm_8.b_0
batch_norm_8.w_0
batch_norm_8.w_1
batch_norm_8.w_2
batch_norm_9.b_0
batch_norm_9.w_0
batch_norm_9.w_1
batch_norm_9.w_2
blaze_01_dw_weights
blaze_01_sep_weights
blaze_11_dw_weights
blaze_11_sep_weights
blaze_21_dw_weights
blaze_21_sep_weights
blaze_31_dw_weights
blaze_31_sep_weights
blaze_41_dw_weights
blaze_41_sep_weights
conv1_weights
conv2d_27.b_0
conv2d_27.w_0
conv2d_28.b_0
conv2d_28.w_0
conv2d_29.b_0
conv2d_29.w_0
conv2d_30.b_0
conv2d_30.w_0
double_blaze_01_dw_weights
double_blaze_01_sep_weights
double_blaze_02_dw_weights
double_blaze_02_sep_weights
double_blaze_11_dw_weights
double_blaze_11_sep_weights
double_blaze_12_dw_weights
double_blaze_12_sep_weights
double_blaze_21_dw_weights
double_blaze_21_sep_weights
double_blaze_22_dw_weights
double_blaze_22_sep_weights
double_blaze_31_dw_weights
double_blaze_31_sep_weights
double_blaze_32_dw_weights
double_blaze_32_sep_weights
double_blaze_41_dw_weights
double_blaze_41_sep_weights
double_blaze_42_dw_weights
double_blaze_42_sep_weights
double_blaze_51_dw_weights
double_blaze_51_sep_weights
double_blaze_52_dw_weights
double_blaze_52_sep_weights
shortcutblaze_2_weights
shortcutdouble_blaze_0_weights
shortcutdouble_blaze_3_weights
how can I use ? thanks!

**Comment by qingqing01** [comment]
@Amanda-Barbara You should export model at-first https://paddledetection.readthedocs.io/advanced_tutorials/inference/EXPORT_MODEL.html
