### ISSUE TITLE
读取图片路径为tensor的代码是哪个哦？

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleDetection#4012]
您好。
我需要读取二十万行二十万列的遥感影像进行预测，因此需要使用gdal对这个影像进行分块读取并进行预测，不过一直没找到infer的时候在哪个位置将图片的路径变为tensor，希望能解答一下，谢谢

**Comment by lyuwenyu** [comment]
1. https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/tools/infer.py#L132
2. https://github.com/PaddlePaddle/PaddleDetection/blob/0981e4ca0dde073a9ffca681ebc38f90a6600781/ppdet/engine/trainer.py#L454
3. TestReader -> transforms -> decode(numpy)
