### ISSUE TITLE
【论文复现】使用PaddleDetection套件运行报错thrust::system::system_error exception.

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleDetection#4013]
outputs[:, :, :2] = (outputs[:, :, :2] + grids)
SystemError: (Fatal) Operator set_value raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument. (at /paddle/paddle/fluid/imperative/tracer.cc:192)

运行一个普通的加法算子，在eval一定轮次之后就会报这个错，而且通常出现在batch_size>1的时候

如何解决， 请给点建议 @qingqing01

**Comment by thunder95** [comment]
如果batch_size设置为1， 也会出现这个问题，只是出现的时间更晚一些

**Comment by thunder95** [comment]
把代码中paddle相应的切片操作换成numpy后就没出现这样的错误。

但是batch设大了后，却出现下面错误：（batch设小就没有）

```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1629336772 (unix time) try "date -d @1629336772" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 26626 (TID 0x7f5d9cd4b740) from PID 0 ***]


Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

```

**Comment by qingqing01** [comment]
> cudaErrorInvalidConfiguration: invalid configuration argument

这个错误，有时候会因为变量的是空的导致的，请注意outputs、grids是否为空的。

下面换成Numpy后，错误不是很具体。
