### ISSUE TITLE
ppyolo_tiny 导出的模型 提示维度不一致 这什么情况  官方训练好的 模型 没有报错 自己训练后导出的却报错

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#4016]
![06758056d18181030bcf7d11b99d9b6](https://user-images.githubusercontent.com/88072901/130009845-6e6aac3e-97f5-476d-9106-543e78926b7f.png)
上图是自己训练后 导出的模型 部署提示的错误 下图是 直接使用官方给的 训练好的 ppyolo_tiny后的结果
![image](https://user-images.githubusercontent.com/88072901/130009954-c3c3fd89-fdb4-4f29-96f7-f8009f088e1a.png)

部署在了树莓派 说可能维度不同导致的  但是 都是一个模型 我训练时候也就修改了 学习率 和 batchsize 为啥导出后就不能用呢 整了好几天 实在是不知道 错在哪里了 请大神解惑
使用的 是下图的教程 训练后 导出的模型
![image](https://user-images.githubusercontent.com/88072901/130010128-663b570f-edb4-49b0-89ac-3851e622cc2b.png)
图片 尺寸 都是 一样的
![image](https://user-images.githubusercontent.com/88072901/130010171-9490caf5-0c0c-4c9d-890a-e42fa4883369.png)

**Comment by nemonameless** [comment]
是训的coco吗？官方训练好的模型你拿去预测的结果和你自己训的模型结果相近吗？
建议使用最新develop分支或release/2.2分支看看

**Comment by STUSER001** [comment]
![image](https://user-images.githubusercontent.com/88072901/130043737-af471a64-ef60-4932-ada9-e61eb6a1d231.png)

是coco 预测的 在paddle 平台上都能正常 运行 就是导出来后 opt 转换后 就是第一张那样 提示错误 但是官方给的 就没问题上图是 官方给的模型 下载的地址 还有 用的 paddlelite  预测库 一直安装不了 就安装了 paddlelite 和 。whl 文件
![image](https://user-images.githubusercontent.com/88072901/130043227-948a1e74-6a83-486d-a00f-04a928a13fce.png)
图片是 日志 这样 然后 就 死机了

**Comment by heavengate** [comment]
看一下是不是你lite给的输入的shape不对，或者输入tensor的shape反了
