### ISSUE TITLE
请问训练自己数据的话，多目标跟踪应该如何配置文件。

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleDetection#4021]
我已经根据https://gitee.com/zhao_huilin/PaddleDetection/blob/release/2.2/docs/tutorials/PrepareMOTDataSet_cn.md
将自己的数据集重组为如下格式：

custom_data
   |——————images
   |        └——————test
   |        └——————train
   |                └——————seq1
   |                |        └——————gt
   |                |        |       └——————gt.txt
   |                |        └——————img1
   |                |        |       └——————000001.jpg
   |                |        |       |——————000002.jpg
   |                |        |       └—————— ...
   |                |        └——————seqinfo.ini
   |                └——————seq2
   |                └——————...
   └——————labels_with_ids
            └——————train
                    └——————seq1
                    |        └——————000001.txt
                    |        |——————000002.txt
                    |        └—————— ...
                    └——————seq2
                    └—————— ...

但我不清楚应该如何配置配置文件中的TrainDataset部分，请问应该如何配置

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/datasets/mot.yml#L8  
制作image_lists并写在这里，以及数据集路径名字对应上即可

**Comment by BainOuO** [comment]
> 

怎么制作image_lists呢
