### ISSUE TITLE
PPyolo c++推理报错

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleDetection#4022]
生成的推理文件如下：

mode: fluid
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: false
arch: YOLO
min_subgraph_size: 3
Preprocess:

interp: 2
keep_ratio: false
target_size:
128
1280
type: Resize
is_scale: true
mean:
0.485
0.456
0.406
std:
0.229
0.224
0.225
type: NormalizeImage
type: Permute
label_list:
person
bicycle

报错内容为：

WARNING: Logging before InitGoogleLogging() is written to STDERR
I0820 13:10:32.976213 14244 analysis_config.cc:424] use_dlnne_:0
I0820 13:10:32.977210 14244 analysis_config.cc:424] use_dlnne_:0
I0820 13:10:32.977210 14244 analysis_config.cc:424] use_dlnne_:0
I0820 13:10:32.977210 14244 analysis_config.cc:424] use_dlnne_:0
total images = 1, batch_size = 1, total steps = 1

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The 2-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [1, 160, 40, 4], input[1]'s shape = [1, 1, 4, 40].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:40 != inputs_dims[i][j]:4.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/concat_op.h:63)

**Comment by ghostxsl** [comment]
请问paddle，paddledetection版本是什么？运行命令是什么？

**Comment by 534114658** [comment]
PaddleDetection-release-2.2生成的c++
.\main --model_dir=D:\\models\\yolov3_darknet --image_file=D:\\images\\test.jpeg
![image](https://user-images.githubusercontent.com/88479008/130202982-bb3f828c-e598-4124-b570-4d6656d78065.png)

主要是  target_size:   这个参数
如果训练为608   或者512   c++推理正常的

指定尺寸训练出的模型在c++推理报错
但是指定尺寸训练的模型用python可以正常推理

**Comment by ghostxsl** [comment]
C++ infer应该是支持正方形输入，size的H要等于W

**Comment by 534114658** [comment]
这样的话   像128*1280这种长方形的图片推理效果很差

python都支持了   c++什么时候支持？

**Comment by 534114658** [comment]
这样的话   像128*1280这种长方形的图片推理效果很差

python都支持了   c++什么时候支持？

**Comment by ghostxsl** [comment]
收到您的反馈，我们会排期增加这个功能～

**Comment by 534114658** [comment]
yolo 的图片尺寸为128*1280

target_size该怎么设置？

 - RandomResize: {target_size: [[128, 1280]], interp: 2, keep_ratio: True}
 
这样配置会报错
raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

**Comment by ghostxsl** [comment]
如果你只是想要resize图像，请不要用RandomResize，请使用Resize

**Comment by 534114658** [comment]
好的
