### ISSUE TITLE
[08/20 16:39:08] ppdet.engine.tracker INFO: Processing frame 0 (100000.00 fps)

### ISSUE THREAD

**Issue by gitqinxinyu** [PaddlePaddle/PaddleDetection#4025]
![image](https://user-images.githubusercontent.com/40631787/130206160-547f50e4-1da0-4764-b27c-1af0f014781c.png)

**Comment by nemonameless** [comment]
确定抽出来图片了吗，看看当前目录下有没有test文件夹，里面有没有图片？另外cuda版本可以换成10.2 10.1试试？

**Comment by gitqinxinyu** [comment]
我是直接导的视频文件，写的绝对路径

**Comment by jiamengsi** [comment]
@gitqinxinyu 你好，我这里在win环境，cuda11.2，paddle2.1.2，ppdet devlop测试是正常的
<img width="1043" alt="48fe77e7f3c59381692bc1a0da92259d" src="https://user-images.githubusercontent.com/71755120/131105587-d3b2aff9-21e0-43ad-8752-6e5b636c04e5.png">
