### ISSUE TITLE
paddledetection结束时抛出异常

### ISSUE THREAD

**Issue by tughv** [PaddlePaddle/PaddleDetection#4027]
paddledetection2.1, pddle2.1  在运行案例里面的路标数据和下载的水果数据集是在训练结束的时候会抛出线程和文件夹不存在的异常，但是不影响保存中间的过程参数和最后的预测
[
![image](https://user-images.githubusercontent.com/40344969/130220137-ec452f0e-59fd-40de-a971-d2d5983bb0e9.png)
](url)
[
![image](https://user-images.githubusercontent.com/40344969/130220140-65ae5918-59ab-4881-982a-7ad5cf8da469.png)
](url)

**Comment by ghostxsl** [comment]
建议您使用最新版本运行您的代码～

**Comment by tughv** [comment]
是最新版本
[
![image](https://user-images.githubusercontent.com/40344969/130222652-0363b91e-8ac0-4416-a859-04dd0b2aedf8.png)
](url)

**Comment by ghostxsl** [comment]
运行命令是什么？提供运行环境，我这边复现一下看看

**Comment by tughv** [comment]
> 运行命令是什么？提供运行环境，我这边复现一下看看

!python tools/eval.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml -o use_gpu=true

**Comment by tughv** [comment]
运行环境是aistudio最新版的paddle,pip 下载的paddledet,PaddleDetection文件是2.0

**Comment by tughv** [comment]
> 运行命令是什么？提供运行环境，我这边复现一下看看

现在有不报错了，太玄学了
