### ISSUE TITLE
为啥量化前后的模型大小没有变化？

### ISSUE THREAD

**Issue by mzxhzhp** [PaddlePaddle/PaddleDetection#4032]
按照官方教程文档的指示进行操作。
1. 训练时使用如下命令：
python tools/train.py -c configs/ssd/ssd_mobilenet_v1_300_120e_voc.yml  --use_vdl=true  --eval
2. 训练完成后，使用如下命令进行量化训练：
python tools/train.py -c configs/ssd/ssd_mobilenet_v1_300_120e_voc.yml  --slim_config configs/slim/quant/ssd_mobilenet_v1_qat.yml  --use_vdl=true  --eval
（备注：ssd_mobilenet_v1_qat.yml中 pretrain_weights 改为第一步训练时生成的模型）

但是，奇怪的是，量化训练完成后的模型，和没有量化的模型，其大小一模一样。
这个是什么原因呢？是不是还有哪里没配置对？

**Comment by qingqing01** [comment]
量化完保存的模型格式还是FP32，如果是使用Paddle Lite部署的话， 使用Paddle Lite的opt工具，转换后，模型会保存为INT8，体积减小，参考：

https://paddle-lite.readthedocs.io/zh/latest/user_guides/quant_aware.html#id4

或者参考:

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/deploy/lite/README.md#211-%E5%AE%89%E8%A3%85paddle_lite_opt%E5%B7%A5%E5%85%B7


但，注意使用Paddle Lite opt工具转换后模型只能Paddle Lite加载。

**Comment by mzxhzhp** [comment]
> 量化完保存的模型格式还是FP32，如果是使用Paddle Lite部署的话， 使用Paddle Lite的opt工具，转换后，模型会保存为INT8，体积减小，参考：
> 
> https://paddle-lite.readthedocs.io/zh/latest/user_guides/quant_aware.html#id4
> 
> 或者参考:
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/deploy/lite/README.md#211-%E5%AE%89%E8%A3%85paddle_lite_opt%E5%B7%A5%E5%85%B7
> 
> 但，注意使用Paddle Lite opt工具转换后模型只能Paddle Lite加载。

这么说倒是可以理解了。但是还有个疑问：
用PaddleDet训练完的模型，也可以用 Paddle Lite opt工具 进行量化转换，那为啥还要用PaddleDet进行量化训练呢？量化训练和不量化训练有啥区别？

**Comment by qingqing01** [comment]
Paddle Lite的opt工具只是将 量化的模型 转换到符合Paddle Lite的格式。 opt会做图转换、融合等。
Paddle Lite是部署工具，不支持量化训练。

**Comment by mzxhzhp** [comment]
> Paddle Lite的opt工具只是将 量化的模型 转换到符合Paddle Lite的格式。 opt会做图转换、融合等。
> Paddle Lite是部署工具，不支持量化训练。

那为啥没有经过量化训练，也可以使用 paddle_lite_opt  --quant_model=true --quant_type=QUANT_INT16 进行转换呢？我发现转换后，模型大小确实变小了。

**Comment by qingqing01** [comment]
opt除了对量化模型转换外，也支持非量化的Paddle模型转换到Paddle Lite的nb格式。

**Comment by mzxhzhp** [comment]
> opt除了对量化模型转换外，也支持非量化的Paddle模型转换到Paddle Lite的nb格式。

嗯，我能理解你说的意思，也感谢解答。
但是我还是有疑问，对于非量化的Paddle模型，用 paddle_lite_opt 工具转换成 Paddle Lite格式，如果不加 --quant_model=true --quant_type=QUANT_INT16  参数的话，模型大小是没有变化的，加了 quant_type 参数模型大小确实会产生变化。我不理解的地方在于，既然都是非量化模型，那加的这个量化参数有什么意义呢？为啥模型大小也发生了改变？还有，使用量化的Paddle模型和非量化的Paddle模型，最终使用 paddle_lite_opt --quant_model=true --quant_type=QUANT_INT16 转换成的Paddle Lite模型，我没有看到明显的区别，不知道这个该怎么理解。

**Comment by yghstill** [comment]
@mzxhzhp 在转换模型时，当模型原本是fp32模型，直接设置--quant_model=true，模型将进行INT格式存储，模型大小确实小了，但是这样的模型是不能预测的，weights的数值直接从fp32->int，精度损失很大。所以才需要在PaddleDetection中进行量化训练后，模型weights适配过int再转换时精度就基本无损了。

**Comment by mzxhzhp** [comment]
> @mzxhzhp 在转换模型时，当模型原本是fp32模型，直接设置--quant_model=true，模型将进行INT格式存储，模型大小确实小了，但是这样的模型是不能预测的，weights的数值直接从fp32->int，精度损失很大。所以才需要在PaddleDetection中进行量化训练后，模型weights适配过int再转换时精度就基本无损了。

嗯，理解了。感谢大佬解答！

**Comment by yghstill** [comment]
@mzxhzhp 补充一下，最新版本PaddleLite，最新OPT不需要指定--quant_model了，会自动解析int8还是fp32模型

**Comment by xiaoxifuhongse** [comment]
@yghstill  那量化训练完了之后我不想用PaddleLite去推理怎么用这个模型呢，比如我想转Onnx然后在去OnnxRuntime运行

**Comment by northeastsquare** [comment]
https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/static/quant_aware_tutorial.md
保存的量化模型相比原始FP32模型，模型体积没有明显差别，这是因为量化预测模型中的权重依旧保存为FP32类型。在部署时，使用PaddleLite opt工具转换量化预测模型后，模型体积才会真实减小。

**Comment by APeiZou** [comment]
@yghstill   哈喽，qat训练后的模型经过PaddleLite转换后的模型比ptq的模型经过转换后的模型尺寸要大，qat的nb模型比ptq的nb模型节点要多一些fill_constant这是为什么呢？

**Comment by ChenH12** [comment]
现在PaddleLite还能用吗，我看官方的paddlelite部署模型文档打开是404
