### ISSUE TITLE
版本选择

### ISSUE THREAD

**Issue by isLiuHao** [PaddlePaddle/PaddleDetection#4035]
想请问一下只识别静态图，选用哪个版本进行训练和预测?
release/2.2可以识别静态图吗，可以用静态图训练吗？

**Comment by nemonameless** [comment]
release/2.2分支可以训静态图。静态图版本在static文件夹下，仍然可以使用。请尽量选择PaddlePaddle和PaddleDetection最新版本。

**Comment by heavengate** [comment]
release/2.2版本支持静态图，的静态图在`static`目录下，PaddleDetection和PaddlePaddle的版本依赖关系请参考https://github.com/PaddlePaddle/PaddleDetection/pull/4024
