### ISSUE TITLE
使用solov2中最新的配置文件solov2_r50_enhance_coco.yml，会出现报错，TypeError: __init__() got an unexpected keyword argument 'drop_block'

### ISSUE THREAD

**Issue by weihongwei-zg** [PaddlePaddle/PaddleDetection#4037]

**Comment by weihongwei-zg** [comment]
报错显示缺少该字段

**Comment by yghstill** [comment]
@wobushihuair 请问使用的是哪个版本代码呢？请使用PaddleDetection release/2.2最新代码试下还有问题吗？

**Comment by weihongwei-zg** [comment]
是昨天重新下载的paddledetection的2.2最新代码

**Comment by weihongwei-zg** [comment]
配置文件也是用这边提供的配置文件，然后就显示没有这个字段

**Comment by weihongwei-zg** [comment]
昨天傍晚，使用命令重新拉取后也依然是这样
git clone https://github.com/PaddlePaddle/PaddleDetection.git

# 编译安装paddledet
cd PaddleDetection
python setup.py install

# 安装其他依赖
pip install -r requirements.txt

**Comment by jerrywgz** [comment]
我这边测试了release/2.2分支是可以正常运行的，drop_block的接口在solov2里面是大概2个月之前加入的https://github.com/PaddlePaddle/PaddleDetection/pull/3517/files#diff-633ef1d159720d5ac3639ab27d15d17632aa14010ef21fdfef16a0e9c689e558L185 可以确认下是否先前安装了PaddleDetection, 可以先pip uninstall paddledet然后重新运行

**Comment by weihongwei-zg** [comment]
感谢！已经解决了 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月27日(星期五) 下午3:28
***@***.***&gt;;
抄送:&nbsp;&quot;Wei ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 使用solov2中最新的配置文件solov2_r50_enhance_coco.yml，会出现报错，TypeError: __init__() got an unexpected keyword argument &#39;drop_block&#39; (#4037)

**Comment by jerrywgz** [comment]
好的，那issue关闭了哈～
