### ISSUE TITLE
voc用训练好的模型训练自己的数据集检测图片，出现很多错误的检测框

### ISSUE THREAD

**Issue by bueredgirll** [PaddlePaddle/PaddleDetection#4039]
用aistudio上的paddledetection水果分类的yolov3模型，训练自己的数据集，检测图片出现许多错误的框框和标签。

**Comment by bueredgirll** [comment]
应该怎么改配置呢

**Comment by jerrywgz** [comment]
如果要训练自己的数据集，建议检查下数据类别数的设置，已经预训练权重的设置，可以加载coco预训练好的权重进行迁移学习

**Comment by bueredgirll** [comment]
类别数设置是正确的，预训练权重应该怎么设置

**Comment by jerrywgz** [comment]
在pretrain_weight的字段设置coco上已经训练好的检测模型，比如如果是yolov3算法 可以使用这个里面的链接https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.2/configs/yolov3#yolov3
