### ISSUE TITLE
solov2模型，边训练边评估时，评估的时候报错！！！

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/PaddleDetection#4040]
我使用的是静态图模型，使用多卡进行训练，跑到评估的时候就会报错，但是设置export CUDA_VISIBLE_DEVICES=4为单卡的时候就不会报错

**Comment by jerrywgz** [comment]
请问使用的Paddle和PaddleDetection版本分别是什么呢，然后麻烦贴下报错信息吗，也方便我们定位问题
