### ISSUE TITLE
win10编译后，用命令行进行预测时，无任何输出

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/PaddleDetection#4046]
[win10 C++预测编译过程.pdf](https://github.com/PaddlePaddle/PaddleDetection/files/7035777/win10.C%2B%2B.pdf)

具体编译过程，请看我上传的pdf文档，谢谢，主要的问题如下：
1、with gpu 选择了，后面还能用cpu进行预测吗？
2、with mkl 是cpu加速，我勾了with gpu后，不勾这个，报缺少libopenblas错误，因为官方下载的paddle_inference的third_party目录下根本没有这东西，导致后面在vs2019里编译失败
3、with tensorrt，勾不勾都没有用，而且非得安装tensorrt，不然后期运行时报"you are using  paddle compiled with tensorrt ,but tensorrt ... is not found"错误。这是bug吗？如果我不想用tensorrt呢，怎么办？
4、关于官方给的参数表，我看了一下，与main.cc代码中的参数个别是有不一样的，我想问一下，是所有的模型，都这样给输入参数吗？还是每个模型不一样，如果不一样，文档中是不是应该明确一下？
5、在成功编译以后，进入了release目录下，里面有main.exe和几个dll，官方文档说如果提示找不到opencv_world346.dll，把D:\projects\packages\opencv3_4_6\build\x64\vc14\bin文件夹下的opencv_world346.dll拷贝到main.exe文件夹下即可，请问，编译以后，主要有哪几个dll呢？明确一下会比较好
6、所有编译都没有问题后，按官方文档中的命令“.\main --model_dir=D:\\models\\yolov3_darknet --video_path=D:\\videos\\test.mp4 --device=GPU ”其实是报错的，立马提示没有什么video_path和device参数等，然后进代码中查main.cc，发现参数都对不上，device应该是use_gpu，所以是否直接告知查看编译后的工程的main.cc文件里的参数更准确？
7、所有参数也给对了，执行预测，发现等了很久，然后执行完了没有任何输出，output没有东西，命令行也直接进入下一行了，也就是说，预测成功与否都不清楚，也没有打印相关过程日志，是不是考虑提供一个输出日志的配置？即使预测不成功，也知道出现了什么问题，这样发个issue也能准确描述问题啊

望官方大佬能给予指导，不胜感激！！！

**Comment by yuyangup** [comment]
补充一下信息：
’环境是win10、预测库是cuda11.0_cudnn8.0_avx_mkl_trt7、trt是TensorRT-7.2.3.4（TensorRT-8.0.1.6也试过），被预测的模型是fasterrcnn训练的模型，trt正常路径正常配置，相关的bin include和lib都放进了cuda对应目录，编译过程未报错，另外本机是cuda11.2，gpu是rtx2080ti

**Comment by ghostxsl** [comment]
1. 可以
2. 需要自己安装openblas，这个地方只有两个选项：MKL or openblas
3. 这个trt的我稍后看一下
4. 运行main的参数应该跟模型没关系
5. 应该就这一个，预处理主要依赖opencv库
6. 文档我check一下
7. 这个问题我复现一下看看

最后，感谢您的反馈～

**Comment by yuyangup** [comment]
1、如果勾选了with_mkl,我还需要下载openblas吗？这个openblas是做什么的？
2、最新测试情况，我使用paddlex的c++编译教程，编译成功了，但是使用main预测的时候，在命令行下面出现了"you are using paddle compiled with tensorrt ,but tensorrt ... is not found"错误，但是trt的环境变量、拷贝到的目录（cuda下的bin、lib、include）包括多trt版本测试，都有试过。依然是报此错误，但是paddledetection的编译，也是成功了，但是预测时，啥提示也没有，预测输出也没有
3、运行main的参数，是适用所有的模型吗？比如fasterrcnn、yolo、ppyolo系列训练处的模型，参数也是一样的吗？
4、运行main进行预测时，建议提供日志输出配置，让用户在测试模式下，能看到整个预测的过程，以便有问题时，能快速定位问题，及时自己搞不定，请教官方时，也能把错误日志发出来。
5、综合paddlex和paddledetection c++预测编译的过程来看，我觉得文档中是不是应该明确官方编译时相关依赖的具体版本，这样至少可以保证用户能编译成功。

最后再次感谢官方支持，希望能尽快解决此问题，不胜感激

**Comment by yuyangup** [comment]
还有一个问题，能不能不适用trt呢？不用trt加速不行吗？我看编译时那个with_tensorrt就是个摆设，勾和不勾都是需要trt。。。

**Comment by ghostxsl** [comment]
1. 两者选其一，openblas官网：http://www.openblas.net/  简单来讲这就是个计算库
2. 你这个情况，我复现了一下，我本地编译没有报这个错，按照你给出的错误信息提示的话，我觉得可能是你安装的paddle库是用trt编译的，如果你不指定trt的目录，在你运行的时候，会因为找不到runtime的环境而报这个错
3. 是的，main的参数是固定的，适用于所有paddledetection下的导出模型
4. 这个问题我这边复现时是可以打印日志信息的，怀疑是你的环境可能没配置好
运行成功：
![image](https://user-images.githubusercontent.com/23647349/130891535-4aff23e1-8bec-49af-be8b-99f852b63ead.png)
运行失败及错误原因：
![image](https://user-images.githubusercontent.com/23647349/130891774-93b3e2f7-e95c-4c52-a207-eb066dbd9283.png)

5. 亲，我们有详细文档说明，请参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/deploy/cpp/README.md

如果，你还有任何问题，我们可以继续沟通～
