### ISSUE TITLE
【论文复现】fp16混合精度训练总是提示Found inf or nan

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleDetection#4049]
不用fp16训练很正常， 用了fp16总是出现提示：
Found inf or nan, current scale is: 128.0, decrease to: 128.0*0.5

loss整体没有明显下降，反复震荡。

请问怎么解决？

**Comment by yghstill** [comment]
@thunder95 建议复现论文阶段用fp32训练，先复现论文。fp16混合精度训练不稳定，有些算子尚未支持，还需要针对模型去优化
