### ISSUE TITLE
static 下的 yolov4 训练时出问题

### ISSUE THREAD

**Issue by Jialiang123** [PaddlePaddle/PaddleDetection#4051]
在静态图下用yolov4训练自己的模型时跑个2000步就会报错，如下
![image](https://user-images.githubusercontent.com/37236583/130593810-522b526b-6d2a-4ba4-84de-c7ae18ba1543.png)

**Comment by yghstill** [comment]
@Jialiang123 看报错是图片读取发生错误，请在decode阶段打印一些debug信息，将出问题的im_file找到并check下：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/static/ppdet/data/transform/operators.py#L114
