### ISSUE TITLE
yolo目标检测怎样并行化

### ISSUE THREAD

**Issue by tiandilinghuo** [PaddlePaddle/PaddleDetection#4062]
有大批量图片url 需要从网上下载 并检测内容，怎么讲图片预处理【下载 ImageDecode resize等】 和 预测并行化，需要怎么编码？

**Comment by tiandilinghuo** [comment]
![image](https://user-images.githubusercontent.com/2712674/130759939-6a96e56f-f255-40ed-a9e3-6e03f75abc1b.png)
预测时候传入的是list  list中只能有一个元素（yi'zha一张图） 多个 图片会报错

**Comment by wangxinxin08** [comment]
现在动态图支持bs > 1, 你可以参考：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.2/deploy
