### ISSUE TITLE
轻量级solov2 

### ISSUE THREAD

**Issue by XiongZhongxia** [PaddlePaddle/PaddleDetection#4064]
您好，请问有轻量级的solov2吗？比如solov2 +GhostNet或者mobilenet，我自己替换backbone的时候遇到一些问题解决不了。。。。

**Comment by lyuwenyu** [comment]
怎么替换的 遇到什么问题了

**Comment by XiongZhongxia** [comment]
> 
> 
> 怎么替换的 遇到什么问题了

 solov2_r50中，backbone接FPN，需要有对应每一层的strides，但是ppdet中的mobilenet、ghostnet最后都没有把这个参数加进去，我不知道应该怎么修改。。。

**Comment by lyuwenyu** [comment]
你可以参考这一行，在你需要得模型上把stride加上 
 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/modeling/backbones/resnet.py#L576
