### ISSUE TITLE
请问Paddledetection在aistudio上应该如何部署

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleDetection#4067]
请问Paddledetection在aistudio的notebook上部署，是否有教程或相关项目可以学习

**Comment by lyuwenyu** [comment]
@FL77N

**Comment by FL77N** [comment]
> 请问Paddledetection在aistudio的notebook上部署，是否有教程或相关项目可以学习

同学你好，其实只需要把 PPDet clone 下来然后上传到 aistudio，然后进行开发就好了，注意的是 aistudio 只能进行单卡训练，然后需要修改的是数据集的位置，一般解压后会放在 data 里面。可以参考一下我的这个项目，https://aistudio.baidu.com/aistudio/projectdetail/2256615 对项目有什么疑问可以在评论里面交流噢

**Comment by huilin16** [comment]
您好，我咨询的是在aistudio notebbok上进行部署的问题，您的回答对我的问题并没有帮助
