### ISSUE TITLE
请问Paddledetection在aistudio notebook上进行在线部署应该如何实现

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleDetection#4072]
请问Paddledetection在aistudio的notebook上进行在线部署，

是否有教程或相关项目可以学习

![L$HYYF99$GY2B0O45SHZALC](https://user-images.githubusercontent.com/36887207/131107300-a863c852-a595-4644-a44b-dbec4b7e0b0b.png)

**Comment by ghostxsl** [comment]
请参考文档：https://ai.baidu.com/ai-doc/AISTUDIO/bk3e382cq
