### ISSUE TITLE
使用PaddleDetection训练365数据集，请问下应该怎么运行训练呢

### ISSUE THREAD

**Issue by chen61175379** [PaddlePaddle/PaddleDetection#4074]

**Comment by chen61175379** [comment]
使用的是 yolov3_darknet53_270e_coco.yml

调整了下coco_deletection.yml

metric: COCO
num_classes: 80

TrainDataset:
  !COCODataSet
    image_dir: images/train
    anno_path: annotations/train/train.json
    dataset_dir: /home/aistudio/PaddleDetection/dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: images/val
    anno_path: annotations/val/val.json
    dataset_dir: /home/aistudio/PaddleDetection/dataset/coco

TestDataset:
  !ImageFolder
    anno_path: /home/aistudio/PaddleDetection/dataset/coco/annotations/val/val.json

**Comment by ghostxsl** [comment]
请参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/docs/tutorials/GETTING_STARTED_cn.md
