### ISSUE TITLE
mot无法输出视频格式

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleDetection#4075]
您好，用python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608.pdparams --video_file=demo/jumpwater.mp4 --frame_rate=30 --save_videos 对视频进行预测，输出一些列图片 但是没有视频
报错信息如下：
Input #0, image2, from 'output/myjump/mot_outputs/jumpwater/%05d.jpg':
  Duration: 00:00:49.76, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 1088x608 [SAR 1:1 DAR 34:19], 25 fps, 25 tbr, 25 tbn, 25 tbc
[NULL @ 0x214fce0] Unable to find a suitable output format for 'scale=trunc(iw/2)*2:trunc(ih/2)*2'
scale=trunc(iw/2)*2:trunc(ih/2)*2: Invalid argument
[08/28 19:13:49] ppdet.engine.tracker INFO: Save video in output/myjump/mot_outputs/jumpwater/../jumpwater_vis.mp4

**Comment by nemonameless** [comment]
修复在这里，https://github.com/PaddlePaddle/PaddleDetection/pull/4078
