### ISSUE TITLE
主页上的这个人体姿态检测是哪个模型？

### ISSUE THREAD

**Issue by sinoboy168** [PaddlePaddle/PaddleDetection#4076]
是否可以检测到人姿态的变化，比如人弯腰或者趴下的时候输出？谢谢
![Uploading 微信截图_20210829102206.png…]()

**Comment by qingqing01** [comment]
下面页面中的TopDown的HRNet模型测试的:

https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.2/configs/keypoint

这里提供的模型是基于COCO数据集训练，人弯腰或趴下这类的数据可能较少，可以测试看下，或者有此类数据的，可以训练看下。
