### ISSUE TITLE
cpp部署预测报错

### ISSUE THREAD

**Issue by sosan-nian** [PaddlePaddle/PaddleDetection#4077]
pp 2.1.2 ，cuda10.2 ，detection2.0  ppyolov2训练的模型
使用同一个视频使用python部署预测正常，但是使用cpp部署预测到固定帧报错
![图片](https://user-images.githubusercontent.com/82444943/131243038-886d35f2-23fd-4631-9f1e-0f1ef0112fbe.png)
![图片](https://user-images.githubusercontent.com/82444943/131243042-18482d50-3662-4355-8997-b495cba728f0.png)
第一个图是python预测的整个视频都可以预测完成，第二个图是cpp部署的每次都那里就报错了（同时测试了detection2.1 2.2 也是一样的）
paddleinference预测库版本如下
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
CUDA version: 10.2
CUDNN version: v7.6
CXX compiler version: 19.16.27045.0
WITH_TENSORRT: ON
TensorRT version: v7

另外观察每一帧预测的log信息，由于前面一部分视频没有目标出现分数都很低，但box框的结果有一部分差异。如果换成有目标物的视频经过阈值过滤后输出的对象框python和cpp基本一致

**Comment by yghstill** [comment]
@sosan-nian 连续帧预测报错是Paddle Inference库bug，已经在Paddle 2.1.1以上版本已经修复，cpp infer的预测库版本更新到2.1.1再试下呢？https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html

**Comment by sosan-nian** [comment]
> 
> 
> @sosan-nian 连续帧预测报错是Paddle Inference库bug，已经在Paddle 2.1.1以上版本已经修复，cpp infer的预测库版本更新到2.1.1再试下呢？https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html

我原来就是2.1版本  刚刚又测试了你发的2.1.1还是一样的报错

**Comment by ghostxsl** [comment]
能否提供一下详细的复现环境及运行命令？
