### ISSUE TITLE
mask_rcnn_r50_fpn训第2个epoch报错

### ISSUE THREAD

**Issue by usuixingyili** [PaddlePaddle/PaddleDetection#4086]
第一个epoch的检查点已经保存下来，在第二个epoch报错
paddlepaddle 2.1.1 
paddledet 2.1.0

Traceback (most recent call last):
  File "tools\train.py", line 140, in <module>
    main()
  File "tools\train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools\train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\ppdet\engine\trainer.py", line 350, in train
    self._eval_with_loader(self._eval_loader)
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\ppdet\engine\trainer.py", line 366, in _eval_with_loader
    outs = self.model(data)
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\ppdet\modeling\architectures\meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\ppdet\modeling\architectures\mask_rcnn.py", line 133, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\ppdet\modeling\architectures\mask_rcnn.py", line 116, in _forward
    im_shape, scale_factor)
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\ppdet\modeling\post_process.py", line 120, in get_pred
    scaled_bbox = pred_bbox / scale_factor_list
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 250, in __impl__
    return math_op(self, other_var, 'axis', axis)
RuntimeError: (PreconditionNotMet) The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-1, 4] now
  [Hint: Expected numel() >= 0, but received numel():-4 < 0:0.] (at C:\home\workspace\Paddle_release2\paddle\fluid\framework\tensor.cc
:59)
  [operator < elementwise_div > error]

**Comment by jerrywgz** [comment]
可以更新版本到paddlepaddle 2.1.2； paddledetection 2.2版本，目前验证该问题已修复

**Comment by usuixingyili** [comment]
> 可以更新版本到paddlepaddle 2.1.2； paddledetection 2.2版本，目前验证该问题已修复

更新到paddledetection  2.2 版本时报错
Building wheels for collected packages: cython-bbox
  Building wheel for cython-bbox (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'E:\opensources\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\iplant\\AppDa
ta\\Local\\Temp\\pip-install-9y0n07u_\\cython-bbox_f7f3c0ff70d44c17ad30a50327e98746\\setup.py'"'"'; __file__='"'"'C:\\Users\\iplant\\A
ppData\\Local\\Temp\\pip-install-9y0n07u_\\cython-bbox_f7f3c0ff70d44c17ad30a50327e98746\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"
'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdis
t_wheel -d 'C:\Users\iplant\AppData\Local\Temp\pip-wheel-mz92_c5i'
       cwd: C:\Users\iplant\AppData\Local\Temp\pip-install-9y0n07u_\cython-bbox_f7f3c0ff70d44c17ad30a50327e98746\
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'cython_bbox' extension
  creating build
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\src
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /G
L /DNDEBUG /MD -IE:\opensources\Anaconda3\lib\site-packages\numpy\core\include -IE:\opensources\Anaconda3\include -IE:\opensources\Ana
conda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Progra
m Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSD
K\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\inclu
de\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\i
nclude\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcsrc/cython_bbox.c /Fobuild\temp
.win-amd64-3.7\Release\src/cython_bbox.obj -Wno-cpp
  cl: 命令行 error D8021 :无效的数值参数“/Wno-cpp”
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\
cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for cython-bbox
  Running setup.py clean for cython-bbox
Failed to build cython-bbox
Installing collected packages: py-cpuinfo, pytest-benchmark, flake8-import-order, terminaltables, sklearn, pycocotools, motmetrics, la
p, cython-bbox, paddledet
    Running setup.py install for cython-bbox ... error
    ERROR: Command errored out with exit status 1:
     command: 'E:\opensources\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\iplant\\App
Data\\Local\\Temp\\pip-install-9y0n07u_\\cython-bbox_f7f3c0ff70d44c17ad30a50327e98746\\setup.py'"'"'; __file__='"'"'C:\\Users\\iplant\
\AppData\\Local\\Temp\\pip-install-9y0n07u_\\cython-bbox_f7f3c0ff70d44c17ad30a50327e98746\\setup.py'"'"';f=getattr(tokenize, '"'"'open
'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' in
stall --record 'C:\Users\iplant\AppData\Local\Temp\pip-record-7f_nj7zy\install-record.txt' --single-version-externally-managed --compi
le --install-headers 'E:\opensources\Anaconda3\Include\cython-bbox'
         cwd: C:\Users\iplant\AppData\Local\Temp\pip-install-9y0n07u_\cython-bbox_f7f3c0ff70d44c17ad30a50327e98746\
    Complete output (11 lines):
    running install
    running build
    running build_ext
    building 'cython_bbox' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3
/GL /DNDEBUG /MD -IE:\opensources\Anaconda3\lib\site-packages\numpy\core\include -IE:\opensources\Anaconda3\include -IE:\opensources\A
naconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Prog
ram Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFX
SDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\inc
lude\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10
\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcsrc/cython_bbox.c /Fobuild\te
mp.win-amd64-3.7\Release\src/cython_bbox.obj -Wno-cpp
    cl: 命令行 error D8021 :无效的数值参数“/Wno-cpp”
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64
\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'E:\opensources\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv
[0] = '"'"'C:\\Users\\iplant\\AppData\\Local\\Temp\\pip-install-9y0n07u_\\cython-bbox_f7f3c0ff70d44c17ad30a50327e98746\\setup.py'"'"';
 __file__='"'"'C:\\Users\\iplant\\AppData\\Local\\Temp\\pip-install-9y0n07u_\\cython-bbox_f7f3c0ff70d44c17ad30a50327e98746\\setup.py'"
'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(cod
e, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\iplant\AppData\Local\Temp\pip-record-7f_nj7zy\install-record.txt' --single-v
ersion-externally-managed --compile --install-headers 'E:\opensources\Anaconda3\Include\cython-bbox' Check the logs for full command output.
