### ISSUE TITLE
怎么引入albumentations？

### ISSUE THREAD

**Issue by sphcn** [PaddlePaddle/PaddleDetection#409]
怎么引入albumentations？从哪儿下手比较好？

**Comment by qingqing01** [comment]
@sphcn 

数据预处理位于 https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.2/ppdet/data/transform 

也可以参考: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/READER.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA%E7%AE%97%E5%AD%90

**Comment by sphcn** [comment]
@qingqing01 
材料看了，谢谢！
最后还是直接在Reader里加了albumentations的引用模块，在yaml里加有点麻烦

**Comment by qingqing01** [comment]
@sphcn 可以直接在reader里加，您能明白在哪里加即可。 YAML觉得主要是不同模型预处理不同，方便配置化管理。

**Comment by zct-cap** [comment]
你好，是在Reader.py里面直接加吗
