### ISSUE TITLE
KeyError: 'gt_poly'

### ISSUE THREAD

**Issue by MorningWind** [PaddlePaddle/PaddleDetection#4091]
我用的是paddle detection库 用的是CBResNet 的 cascade_mask_rcnn_r50_vd_fpn_ssld_2x_coco.yml
在AI studio中，输入训练指令 python tools/train.py -c configs/cascade_rcnn/cascade_mask_rcnn_r50_vd_fpn_ssld_2x_coco.yml
时出现了这个问题 求解！

（when I used paddle detection  and I choosed cascade_mask_rcnn_r50_vd_fpn_ssld_2x_coco.yml
when I trained it, there was an error:）

 File "/home/aistudio/PaddleDetection-release-2.2/ppdet/modeling/proposal_generator/target_layer.py", line 254, in __call__
    **gt_segms = inputs['gt_poly']

KeyError: 'gt_poly'**

please help me!

**Comment by jerrywgz** [comment]
cascade_mask needs segmentation input data, and coco dataset source will convert it into gt_poly here. https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/data/source/coco.py. And the data config depends on https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/datasets/coco_instance.yml 
So you could check the input data at first.

**Comment by MorningWind** [comment]
> cascade_mask needs segmentation input data, and coco dataset source will convert it into gt_poly here. https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/data/source/coco.py. And the data config depends on https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/datasets/coco_instance.yml
> So you could check the input data at first.

ok thanks  I will try it !
