### ISSUE TITLE
minicoco

### ISSUE THREAD

**Issue by FengJin-cv** [PaddlePaddle/PaddleDetection#4094]
你好，我也想在minicoco做实验，coco数据集太大了训练很慢，我自己复现的ppyolo和ppyolov2，在minicoco数据集上map（0.5-0.95）达到多少算正常值，希望恢复，因为训练一次coco成本太高了

**Comment by wangxinxin08** [comment]
minicoco数据集是coco数据集的子集，minicoco的数据集只包含一个训练的json文件，instances_minitrain2017.json，可以从这个链接https://drive.google.com/open?id=1lezhgY4M_Ag13w0dEzQ7x_zQ_w0ohjin 下载，其他与coco数据集一致，在minicoco上的AP大致等于coco上的AP - 10.
