### ISSUE TITLE
使用deploy/python推理脚本连接摄像头预测视频流，怎么提高流畅度

### ISSUE THREAD

**Issue by bueredgirll** [PaddlePaddle/PaddleDetection#4100]
paddleDetection导出的ppyolo模型在python上部署，连接摄像头实时预测，出来的视频很卡顿，修改fps帧数，效果不明显。应该怎么提高流畅度

**Comment by yghstill** [comment]
@bueredgirll 请问是在什么GPU下部署的吗？ppyolo-r50vd的模型适合在性能交强GPU下部署，CPU或低性能的GPU下预测速度较慢，建议更换ppyolo-mbv3等轻量级模型试下

**Comment by bueredgirll** [comment]
在cpu环境下部署的，请问量化模型可以提高流畅度吗？

**Comment by yghstill** [comment]
@bueredgirll 可以使用mkldnn加速，量化的话只能在tensorRT或者移动端上加速

**Comment by bueredgirll** [comment]
使用mkldnn加速了，视频还是有些卡顿，不流畅，因为这个要用在集成环境，所以有一点卡都不行。量化模型可以好点吗？或者还有其他办法加速吗？

**Comment by yghstill** [comment]
@bueredgirll 可以换个轻量级的模型试试，比如ppyolo-mobilenetv3
