### ISSUE TITLE
int8预测报错

### ISSUE THREAD

**Issue by sosan-nian** [PaddlePaddle/PaddleDetection#4104]
使用pp2.2在线量化训练ppyolov2导出的模型，在cpp部署预测启用trt_int8以后报错，如下图；启动trt_fp16预测的置信度为nan时间需要3000ms，非量化模型只需要40ms左右
![图片](https://user-images.githubusercontent.com/82444943/131631319-a9d30b2e-5a05-41ee-bf78-26531d47ef0d.png)

**Comment by yghstill** [comment]
@sosan-nian 
1. 当前环境下trt可以跑通，只有trt_int8跑不通？Inference预测库的版本是多少？
2. int8的模型用trt_int8模式测试，其他模式测试会有问题
