### ISSUE TITLE
在C++上进行GPU推理，没有检测到目标会报错

### ISSUE THREAD

**Issue by Myxrf** [PaddlePaddle/PaddleDetection#4106]
连续推理的时候，没有检测目标的话会报错。（例如第一张有检测到目标，但是第二张没有检测到目标）。

**Comment by Myxrf** [comment]
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0901 20:14:06.238124 11120 analysis_predictor.cc:1145] Deprecated. Please use CreatePredictor instead.
6 12 28 28 6122828
Inference: 4336.000000 ms per batch image
class=1 confidence=0.8428 rect=[834 875 665 761]
class=1 confidence=0.9369 rect=[761 963 1052 1194]
class=2 confidence=0.9885 rect=[963 1077 875 1010]
1 1 1100
[WARNING] No object detected.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/9.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at D:\wangye19\Paddle\paddle\fluid\platform\gpu_info.cc:296)

**Comment by Myxrf** [comment]
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0901 20:14:06.238124 11120 analysis_predictor.cc:1145] Deprecated. Please use CreatePredictor instead.
6 12 28 28 6122828
Inference: 4336.000000 ms per batch image
class=1 confidence=0.8428 rect=[834 875 665 761]
class=1 confidence=0.9369 rect=[761 963 1052 1194]
class=2 confidence=0.9885 rect=[963 1077 875 1010]
1 1 1100
[WARNING] No object detected.
C++ Traceback (most recent call last):
Not support stack backtrace yet.

Error Message Summary:

ExternalError:  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/9.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at D:\wangye19\Paddle\paddle\fluid\platform\gpu_info.cc:296)

**Comment by yghstill** [comment]
@Myxrf 连续图片预测Cuda error(700)的一个报错问题已在最新Paddle-Inference 2.1.1之后修复了，可以更新下再试下

**Comment by Myxrf** [comment]
> @Myxrf 连续图片预测Cuda error(700)的一个报错问题已在最新Paddle-Inference 2.1.1之后修复了，可以更新下再试下

解决了感谢哈，但是在旧版本的paddledetection里使用Paddle-Inference 2.1.1 cmake后的工程好像有点问题，好像有些路径没包含进来
