### ISSUE TITLE
ppyolo模型连接摄像头预测，怎么提高推理速度？

### ISSUE THREAD

**Issue by bueredgirll** [PaddlePaddle/PaddleDetection#4108]
现在的情况时，画面看起来有延迟不流畅，使用了mkldnn加速，还有其他提高流畅度的办法吗，比如，降低图片分辨率？量化模型？还是使用tiny轻量级模型？这个模型还要用在集成环境上，不知道该怎么做？求指教

**Comment by wangxinxin08** [comment]
如果是端侧设备的话，可以考虑使用ppyolo tiny轻量级模型，ppyolo大模型是为了gpu设备设计的
