### ISSUE TITLE
C++推理支持mask-rcnn吗？

### ISSUE THREAD

**Issue by cvfzhong** [PaddlePaddle/PaddleDetection#411]
试了下用faster-rcnn的配置好像不行
请问需要做什么样的修改才能适配mask-rcnn？

**Comment by qingqing01** [comment]
@cvfzhong 
注意，使用C++推理时，需要先使用tools/export_model.py导出模型，再使用C++推理程序。
MaskRCNN的输入需要3个输入image、image_info(resize的信息)、image_shape(原始图像大小)，参考: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/inference/EXPORT_MODEL.md#%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA


C++预测的配置，可以参考RCNN-FPN：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/inference/conf/detection_rcnn_fpn.yaml


另外，您的部署如果不是一定必需依赖C++的话，可以参考Python的预测代码。  相比C++还是要简单很多。同时我们也在重构C++预测，使得代码更容易读懂、以及使用更简单。

**Comment by cvfzhong** [comment]
cpp_infer.py在MaskRCNN上对outs的解析好像不对，outs[0]是bounding-box，outs[1]是mask，cpp_infer.py里用outs[-1]去获得bounding-box，是个bug吧？我改成outs[0]可以正常运行。

但是我把use_python_inference改成false的时候，c++推理模块在GetFetch函数里报EnforceNotMet的异常。

所以，是我导出的模型fetch-list有错吗？还是库本身有什么bug？

**Comment by qingqing01** [comment]
@cvfzhong 

https://github.com/PaddlePaddle/PaddleDetection/blob/master/tools/cpp_infer.py

master分支上，有合入新的，这个文件完全脱离PaddleDetection可以用，也是适配了MaskRCNN。您用下这个呢

**Comment by jerrywgz** [comment]
@cvfzhong 你提到的outs得到的box和mask顺序不一致的问题是不同python版本在save_inference_model时得到的fetch list不同导致的，这个问题已经在master分支上修复了

**Comment by cvfzhong** [comment]
用master的cpp_infer.py也需要用master训练和导出模型吧？ 我用release0.2的模型好像问题更多

我改了下infer.py现在可以在视频上跑测试了，问题暂时解决了，谢谢！

**Comment by qingqing01** [comment]
@cvfzhong 感谢，我们持续改进~
