### ISSUE TITLE
使用coco格式的json，图片名称不是纯数字，静态图，训练时报错，怎么解决？

### ISSUE THREAD

**Issue by rock4you** [PaddlePaddle/PaddleDetection#4111]
paddle/fluid/data_feeder.py", line 202, in done
    arr = np.array(self.data, dtype=self.dtype)
ValueError: invalid literal for int() with base 10: 'xxx'

**Comment by wangxinxin08** [comment]
coco标注中图片名称原本就不是纯数字，需要保证image中的id字段为数字，建议先检查下数据标注是否合理

**Comment by rock4you** [comment]
标注中的id跟文件名前缀一致，不是数字

**Comment by rock4you** [comment]
已解决，将image_id改为数字即可
