### ISSUE TITLE
怎么修改mask Rcnn的loss

### ISSUE THREAD

**Issue by Myxrf** [PaddlePaddle/PaddleDetection#4114]
我现在用的是mask_rcnn_r50_fpn_1x这个网络，因为样本的不平衡想通过对每个类别的loss进行加权，paddle有提供相应的操作吗，或者需要修改哪里

**Comment by ghostxsl** [comment]
可以修改bbox和mask分支的loss，请参考：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/modeling/heads/bbox_head.py#L259
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/modeling/heads/mask_head.py#L160

**Comment by Myxrf** [comment]
> 可以修改bbox和mask分支的loss，请参考：
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/modeling/heads/bbox_head.py#L259
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/modeling/heads/mask_head.py#L160

emmmm我是在静态版本2.0里面进行训练的，我对比这两个python文件不太一样，静态版本的也是在这里面改吗，感谢！！！！

**Comment by ghostxsl** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/static/ppdet/modeling/roi_heads/bbox_head.py#L250
这里

**Comment by Myxrf** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/static/ppdet/modeling/roi_heads/bbox_head.py#L250
> 这里

my_weight = paddle.to_tensor([1.0, 0.2, 0.2, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], dtype='float32')
        loss_mask = F.binary_cross_entropy_with_logits(
            mask_pred, mask_target, weight=mask_weight, reduction="mean",pos_weight=my_weight)         
        return loss_mask

我一共12类，参考API文档我在这添加了权重，但是提示报错。

pos_weight (Tensor，可选) - 手动指定正类的权重，必须是与类别数相等长度的向量。数据类型是float32, float64。默认值是：None。


报错信息
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [17, 28, 28] and the shape of Y = [12]. Received [28] in X is not equal to [12] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at C:\home\workspace\Paddle_release2\paddle/fluid/operators/elementwise/elementwise_op_function.h:169)
  [operator < elementwise_mul > error]
想问一下应该怎么改这个权重

**Comment by ghostxsl** [comment]
看报错信息提示的是两边的维度不匹配，你再检查一下mask_pred, mask_target呢？

**Comment by Myxrf** [comment]
> 看报错信息提示的是两边的维度不匹配，你再检查一下mask_pred, mask_target呢？

mask_label_input Tensor(shape=[6], dtype=int32, place=CUDAPlace(0), stop_gradient=False,
       [10, 10, 10, 10, 10, 10])
mask_label [6, 12, 28, 28]
mask_logits [6, 12, 28, 28]
mask_pred [6, 28, 28]
mask_target [6, 28, 28]

我把输入都打印出来出来看了一下，知道是怎么匹配pred和target然后计算损失了，就是不太明白这个pos_weight,要怎么写成什么形式的，我在bbox_head.py里面设置分类损失权重，my_weight =paddle.to_tensor([1.0,1.0,0.2,0.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0], dtype='float32') ， loss_bbox_cls = F.cross_entropy( input=scores, label=tgt_labels,weight=my_weight, reduction='mean')是可行的，mask_head.py报错是在binary_cross_entropy_with_logits里面的core.ops.elementwise_mul(label, core.ops.elementwise_sub(pos_weight, one))，是pos_weight和label的不匹配，刚入门，感谢！！

**Comment by Myxrf** [comment]
> 看报错信息提示的是两边的维度不匹配，你再检查一下mask_pred, mask_target呢？

mask_label_input Tensor(shape=[6], dtype=int32, place=CUDAPlace(0), stop_gradient=False,
       [10, 10, 10, 10, 10, 10])
mask_label [6, 12, 28, 28]
mask_logits [6, 12, 28, 28]
mask_pred [6, 28, 28]
mask_target [6, 28, 28]

我把输入都打印出来出来看了一下，知道是怎么匹配pred和target然后计算损失了，就是不太明白这个pos_weight,要怎么写成什么形式的，我在bbox_head.py里面设置分类损失权重，my_weight =paddle.to_tensor([1.0,1.0,0.2,0.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0], dtype='float32') ， loss_bbox_cls = F.cross_entropy( input=scores, label=tgt_labels,weight=my_weight, reduction='mean')是可行的，mask_head.py报错是在binary_cross_entropy_with_logits里面的core.ops.elementwise_mul(label, core.ops.elementwise_sub(pos_weight, one))，是pos_weight和label的不匹配，刚入门，感谢！！

**Comment by ghostxsl** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/binary_cross_entropy_with_logits_cn.html#binary-cross-entropy-with-logits
我你举个例子：
```
import paddle
logit=paddle.rand([8,100,100,12])
label=paddle.ones([8,100,100,12])
weight=paddle.rand([8, 100, 100, 12])
pos_weight=paddle.rand([12])
loss=paddle.nn.functional.binary_cross_entropy_with_logits(logit,label,weight,'none',pos_weight)
```
如果pos_weight.shape=[12]的话，这里的类别这一维度，你要放到最后一维，要不然它内部做elementwise_mul的时候，维度匹配不上
如果你非要把类别放在第二维也可以，那你就必须扩展一下维度：pos_weight=pos_weight.reshape([12, 1, 1])，让他能够进行广播计算
```
import paddle
logit=paddle.rand([8,12,100,100])
label=paddle.ones([8,12,100,100])
weight=paddle.rand([8, 12, 100, 100])
pos_weight=paddle.rand([12, 1, 1])
loss=paddle.nn.functional.binary_cross_entropy_with_logits(logit,label,weight,'none',pos_weight)
```

**Comment by Myxrf** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/binary_cross_entropy_with_logits_cn.html#binary-cross-entropy-with-logits
> 我你举个例子：
> 
> ```
> import paddle
> logit=paddle.rand([8,100,100,12])
> label=paddle.ones([8,100,100,12])
> weight=paddle.rand([8, 100, 100, 12])
> pos_weight=paddle.rand([12])
> loss=paddle.nn.functional.binary_cross_entropy_with_logits(logit,label,weight,'none',pos_weight)
> ```
> 
> 如果pos_weight.shape=[12]的话，这里的类别这一维度，你要放到最后一维，要不然它内部做elementwise_mul的时候，维度匹配不上
> 如果你非要把类别放在第二维也可以，那你就必须扩展一下维度：pos_weight=pos_weight.reshape([12, 1, 1])，让他能够进行广播计算
> 
> ```
> import paddle
> logit=paddle.rand([8,12,100,100])
> label=paddle.ones([8,12,100,100])
> weight=paddle.rand([8, 12, 100, 100])
> pos_weight=paddle.rand([12, 1, 1])
> loss=paddle.nn.functional.binary_cross_entropy_with_logits(logit,label,weight,'none',pos_weight)
> ```

 loss_mask = F.binary_cross_entropy_with_logits(  mask_pred, mask_target, weight=mask_weight, reduction="mean",pos_weight=my_weight)

mask_pred [6, 28, 28]
mask_target [6, 28, 28]
mask_label [6, 12, 28, 28]
mask_logits [6, 12, 28, 28]

你给的例子中 输入到binary_cross_entropy_with_logits的是四维的，但是mask_head.py输入到binary_cross_entropy_with_logits的是三维的，是不是要把mask_pred替换成mask_logits ，把mask_target 替换成mask_label ，但是替换后weight=mask_weight权重又报错了。。。。。不太懂，问题有点多谢谢啦

**Comment by ghostxsl** [comment]
你这是12分类吧？我理解mask_target存的是label的index，mask_label是one_hot后的tensor，mask_pred是你softmax后的结果吗？mask_pred的shape为啥少了12？
老铁，讲道理，binary_cross_entropy_with_logits的输入一个是logits，另一个是one_hot后的label，weight的shape要跟你前面输入的logits一样。
官网API的说明：
![image](https://user-images.githubusercontent.com/23647349/132840059-803f990a-bb34-4c1a-aad8-02c46acde0a8.png)

PS：F.binary_cross_entropy_with_logits这个loss函数的输入可以是任意维度的，只要你每个维度对应的上，搞清楚是类别的维度
PPS：铁子，要实在不行，你把你改的代码发过来，我帮你瞅瞅

**Comment by Myxrf** [comment]
def get_loss(self, mask_logits, mask_label, mask_target, mask_weight):
        print("mask_labelinput", mask_label)
        mask_label = F.one_hot(mask_label, self.num_classes).unsqueeze([2, 3])
        mask_label = paddle.expand_as(mask_label, mask_logits)
        mask_label.stop_gradient = True
        mask_pred = paddle.gather_nd(mask_logits, paddle.nonzero(mask_label))
        shape = mask_logits.shape
        mask_pred = paddle.reshape(mask_pred, [shape[0], shape[2], shape[3]])
        mask_target = mask_target.cast('float32')
        mask_weight = mask_weight.unsqueeze([1, 2])
        my_weight = paddle.to_tensor([1.0, 0.2, 0.2, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], dtype='float32')
        my_weight = my_weight.reshape([12, 1,1])
        print("my_weight",my_weight,my_weight.shape)
        print("mask_label", mask_label.shape)
        print("mask_logits", mask_logits.shape)
        print("mask_pred",mask_pred.shape)
        print("mask_target", mask_target.shape)
        loss_mask = F.binary_cross_entropy_with_logits(
            mask_pred, mask_target, weight=mask_weight, reduction="mean",pos_weight=my_weight)
        return loss_mask  


就是分12类，想要让2，3类loss_mask  的权重小一点，样本太多了，过程我是清楚的，但是代码是真的懵。

**Comment by ghostxsl** [comment]
> def get_loss(self, mask_logits, mask_label, mask_target, mask_weight):
> print("mask_labelinput", mask_label)
> mask_label = F.one_hot(mask_label, self.num_classes).unsqueeze([2, 3])
> mask_label = paddle.expand_as(mask_label, mask_logits)
> mask_label.stop_gradient = True
> mask_pred = paddle.gather_nd(mask_logits, paddle.nonzero(mask_label))
> shape = mask_logits.shape
> mask_pred = paddle.reshape(mask_pred, [shape[0], shape[2], shape[3]])
> mask_target = mask_target.cast('float32')
> mask_weight = mask_weight.unsqueeze([1, 2])
> my_weight = paddle.to_tensor([1.0, 0.2, 0.2, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], dtype='float32')
> my_weight = my_weight.reshape([12, 1,1])
> print("my_weight",my_weight,my_weight.shape)
> print("mask_label", mask_label.shape)
> print("mask_logits", mask_logits.shape)
> print("mask_pred",mask_pred.shape)
> print("mask_target", mask_target.shape)
> loss_mask = F.binary_cross_entropy_with_logits(
> mask_pred, mask_target, weight=mask_weight, reduction="mean",pos_weight=my_weight)
> return loss_mask
> 
> 就是分12类，想要让2，3类loss_mask 的权重小一点，样本太多了，过程我是清楚的，但是代码是真的懵。

有一说一，你写的有点乱。。。

首先，我不知道你这里的mask_label和mask_target的区别是啥？还有既然你是想要调节2，3类的weight，只用pos_weight就可以了，weight是用来调节每个batch的权重的（参考官网API中的解释）。
其次，我假设你这里mask_logits是网络的输出，那应该是[batch_size, 12, h, w]，如果你get到的label是hard label，也就是那种index类型的标签mask_label，调一次F.one_hot后你的mask_label的shape是[batch_size, h, w, 12]，然后按照我之前跟你讲的，对mask_logits做个转置就行了：mask_logits=mask_logits.transpose([0, 2, 3, 1])，
最后，你的pos_weight可以这么写：
pos_weight=paddle.ones([12])
pos_weight[1:3]=0.2
计算loss：
loss_mask = F.binary_cross_entropy_with_logits(
mask_logits, mask_label,  reduction="mean", pos_weight=pos_weight)

PS：我就想知道你这里的mask_weight是个啥？用来调节啥的权重的？

**Comment by Myxrf** [comment]
> > def get_loss(self, mask_logits, mask_label, mask_target, mask_weight):
> > print("mask_labelinput", mask_label)
> > mask_label = F.one_hot(mask_label, self.num_classes).unsqueeze([2, 3])
> > mask_label = paddle.expand_as(mask_label, mask_logits)
> > mask_label.stop_gradient = True
> > mask_pred = paddle.gather_nd(mask_logits, paddle.nonzero(mask_label))
> > shape = mask_logits.shape
> > mask_pred = paddle.reshape(mask_pred, [shape[0], shape[2], shape[3]])
> > mask_target = mask_target.cast('float32')
> > mask_weight = mask_weight.unsqueeze([1, 2])
> > my_weight = paddle.to_tensor([1.0, 0.2, 0.2, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], dtype='float32')
> > my_weight = my_weight.reshape([12, 1,1])
> > print("my_weight",my_weight,my_weight.shape)
> > print("mask_label", mask_label.shape)
> > print("mask_logits", mask_logits.shape)
> > print("mask_pred",mask_pred.shape)
> > print("mask_target", mask_target.shape)
> > loss_mask = F.binary_cross_entropy_with_logits(
> > mask_pred, mask_target, weight=mask_weight, reduction="mean",pos_weight=my_weight)
> > return loss_mask
> > 就是分12类，想要让2，3类loss_mask 的权重小一点，样本太多了，过程我是清楚的，但是代码是真的懵。
> 
> 有一说一，你写的有点乱。。。
> 
> 首先，我不知道你这里的mask_label和mask_target的区别是啥？还有既然你是想要调节2，3类的weight，只用pos_weight就可以了，weight是用来调节每个batch的权重的（参考官网API中的解释）。
> 其次，我假设你这里mask_logits是网络的输出，那应该是[batch_size, 12, h, w]，如果你get到的label是hard label，也就是那种index类型的标签mask_label，调一次F.one_hot后你的mask_label的shape是[batch_size, h, w, 12]，然后按照我之前跟你讲的，对mask_logits做个转置就行了：mask_logits=mask_logits.transpose([0, 2, 3, 1])，
> 最后，你的pos_weight可以这么写：
> pos_weight=paddle.ones([12])
> pos_weight[1:3]=0.2
> 计算loss：
> loss_mask = F.binary_cross_entropy_with_logits(
> mask_logits, mask_label, reduction="mean", pos_weight=pos_weight)
> 
> PS：我就想知道你这里的mask_weight是个啥？用来调节啥的权重的？

。。。。这是官方的代码呀，只有这my_weight = paddle.to_tensor([1.0, 0.2, 0.2, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], dtype='float32')和那些print是我写的。。。。，我这里理解的mask_logits应该是网络预测出来的所有目标对应所有类别的mask，
mask_label一开始输入的话应该是类别标签，后面转成四维的，跟mask_logits做匹配得到每个目标对应类别的mask，也就是mask_pred，然后跟输入的mask_target计算损失。。还有就是我也也想知道这个mask_weight是个啥，我看不懂不敢乱改呀。。

**Comment by ghostxsl** [comment]
官方的code？给我个链接我看一下呢

**Comment by Myxrf** [comment]
[https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/modeling/heads/mask_head.py#L160](url)
这不是你之前我看的吗

**Comment by ghostxsl** [comment]
你又用动态图啦？😳我还以为你用的是静态图，稍等啊，我给你看一下

**Comment by Myxrf** [comment]
静态图我更懵，动态库还稍微看出点东西。。。。。。。

**Comment by ghostxsl** [comment]
代码位置：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/modeling/heads/mask_head.py#L160
我先给你解释一下原来的代码，再跟你讲一下怎么按照你的需求改
```
def get_loss(self, mask_logits, mask_label, mask_target, mask_weight):
    # mask_logits.shape=[b, c, h, w], 这个是网络的输出
    # mask_label.shape=[n], 这是n个mask的类别标签
    # mask_target.shape=[n, h, w], n个mask的分割label
    # mask_weight.shape=[n], 对应着mask_label，我看了下代码，这里应该永远都是1（没啥用，可以忽略）

    # 根据label生成one_hot标签，shape=[n, c, 1, 1]
    mask_label = F.one_hot(mask_label, self.num_classes).unsqueeze([2, 3])
    # 将label扩展成和mask_logits一样的shape=[n, c, h, w]
    mask_label = paddle.expand_as(mask_label, mask_logits)
    # 设置不反传梯度
    mask_label.stop_gradient = True
    # 下面三行代码是根据positive的index，从mask_logits里gather出来，再reshape成[n, h, w]
    mask_pred = paddle.gather_nd(mask_logits, paddle.nonzero(mask_label))
    shape = mask_logits.shape
    mask_pred = paddle.reshape(mask_pred, [shape[0], shape[2], shape[3]])
    # 类型转换
    mask_target = mask_target.cast('float32')
    # 跟我之前跟你说的一样，扩展维度为了后面能够广播计算
    mask_weight = mask_weight.unsqueeze([1, 2])
    # 计算loss
    loss_mask = F.binary_cross_entropy_with_logits(
        mask_pred, mask_target, weight=mask_weight, reduction="mean")
    return loss_mask
```

修改后：
```
def get_loss(self, mask_logits, mask_label, mask_target, mask_weight):
    # mask_logits.shape=[b, c, h, w], 这个是网络的输出
    # mask_label.shape=[n], 这是n个mask的类别标签
    # mask_target.shape=[n, h, w], n个mask的分割label
    # mask_weight.shape=[n], 对应着mask_label，我看了下代码，这里应该永远都是1（没啥用，可以忽略）
    
    # 定义pos_weight，根据label gather出来对应的weight
    pos_weight = paddle.to_tensor([1.0, 0.2, 0.2, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])
    my_weight = paddle.gather(pos_weight, mask_label, axis=0).unsqueeze([1, 2])
    
    # 根据label生成one_hot标签，shape=[n, c, 1, 1]
    mask_label = F.one_hot(mask_label, self.num_classes).unsqueeze([2, 3])
    # 将label扩展成和mask_logits一样的shape=[n, c, h, w]
    mask_label = paddle.expand_as(mask_label, mask_logits)
    # 设置不反传梯度
    mask_label.stop_gradient = True
    # 下面三行代码是根据positive的index，从mask_logits里gather出来，再reshape成[n, h, w]
    mask_pred = paddle.gather_nd(mask_logits, paddle.nonzero(mask_label))
    shape = mask_logits.shape
    mask_pred = paddle.reshape(mask_pred, [shape[0], shape[2], shape[3]])
    # 类型转换
    mask_target = mask_target.cast('float32')
    # 跟我之前跟你说的一样，扩展维度为了后面能够广播计算
    mask_weight = mask_weight.unsqueeze([1, 2])
    # 计算loss
    loss_mask = F.binary_cross_entropy_with_logits(
        mask_pred, mask_target, weight=mask_weight, reduction="mean", pos_weight=my_weight)
    return loss_mask
```

**Comment by Myxrf** [comment]
懂了懂了老铁，感谢感谢😄
