### ISSUE TITLE
如何将PaddleX的模型转换成PaddleDetection的模型？

### ISSUE THREAD

**Issue by ucsk** [PaddlePaddle/PaddleDetection#4115]
我发现PaddleX导出的模型是`model.yml`，而PaddleDetection导出的是`infer_cfg.yml`，并且其中有些配置是不同的（例如`arch`），所以我猜想这两个模型调用方式不同，或者如何对PaddleX的模型进行转换而能够将其当作目标跟踪的检测器？谢谢！

**Comment by ghostxsl** [comment]
请问具体是什么需求呢？如果您想要训练目标跟踪的检测器，建议您使用我们最新发布的多目标跟踪模型，参考文档：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/mot/README_cn.md

**Comment by ucsk** [comment]
> 请问具体是什么需求呢？如果您想要训练目标跟踪的检测器，建议您使用我们最新发布的多目标跟踪模型，参考文档：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/mot/README_cn.md

我想要训练自己的跟踪器（非COCO中的类别，即重新训练ReID网络），应该如何布置数据集并进行训练？

**Comment by ghostxsl** [comment]
可以参考文档：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.2/configs/mot
可以直接使用fairmot进行训练，如果你的数据没有id标签就不可以了，只能先训检测再用deepsort去做跟踪

**Comment by ghostxsl** [comment]
你是要用PaddleX导出的模型直接加载到PaddleDetection的模型里进行训练嘛？

**Comment by ucsk** [comment]
> 你是要用PaddleX导出的模型直接加载到PaddleDetection的模型里进行训练嘛？

您好，我的主要想法是将训练好的paddlex模型作为检测器（因为训练效果比较好），而跟踪器选用 `SORT`算法 无需训练（没有数据集），请问该项目有无不需要训练的跟踪器实现呢？

**Comment by nemonameless** [comment]
请参考使用  https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/mot/deepsort   。
PaddleDetection的DeepSORT现在支持两种评估的方式，您适用的方式是加载检测结果文件和ReID模型，需要按照MOT16结果提交格式来准备 检测结果，需要是txt形式。
```
det_results_dir
   |——————MOT16-02.txt
   |——————MOT16-04.txt
   |——————MOT16-05.txt
   |——————MOT16-09.txt
   |——————MOT16-10.txt
   |——————MOT16-11.txt
   |——————MOT16-13.txt
```
其中每个txt是每个视频中所有图片的检测结果，每行都描述一个边界框，格式如下：
```
[frame_id],[bb_left],[bb_top],[width],[height],[conf]
```
