### ISSUE TITLE
有能在树莓派上实时运行的轻量级目标检测模型吗？

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleDetection#4119]

**Comment by qingqing01** [comment]
Paddle Lite Demo中有提供树莓派的目标检测示例  https://github.com/PaddlePaddle/Paddle-Lite-Demo

模型的话，

release分支的ppyolo tiny可以试下：

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/ppyolo/README_cn.md#pp-yolo-tiny%E6%A8%A1%E5%9E%8B

dev分支的picodet可以试下:
 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/picodet

**Comment by kingbirdWc** [comment]
谢谢，请问拿官方的模型哪来推理的话该怎么用呢？解压后是__params__， __model__，infer_cfg.yml三个文件，而infer.py需要是pdparams格式的，怎么用这些来推理？
![image](https://user-images.githubusercontent.com/23066646/132175733-5f2d00ec-ae3d-4c94-a511-e8661c197d4a.png)

![image](https://user-images.githubusercontent.com/23066646/132175324-069171f4-d055-415c-9b20-8466d4e20f4f.png)

**Comment by qingqing01** [comment]
这两种格式是等价的，都支持的，只是命名不同~
