### ISSUE TITLE
目标检测模型是否可以获取目标的面积大小

### ISSUE THREAD

**Issue by liuhuaguang** [PaddlePaddle/PaddleDetection#4121]
图像分割模型可以获取到检测到目标在图片中的面积大小，想请问下目标检测模型是否也可以做到呢？我看代码里结果返回的只要左上角、右下角的坐标信息。

**Comment by qingqing01** [comment]
当前没提供。您可以利用得到的长方形框坐标，进行计算。

**Comment by liuhuaguang** [comment]
明白了，我其实是想得到更为准确的面积数据，多谢解答
