### ISSUE TITLE
infer时怎样将opencv读取的摄像头作为输入？

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleDetection#4124]

**Comment by qingqing01** [comment]
Python部署的话，参考下面链接中的--camera_id，是用摄像头实时视频作为输入:

https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.2/deploy/python#2-%E5%9F%BA%E4%BA%8Epython%E7%9A%84%E9%A2%84%E6%B5%8B


C++部署也类似:

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/deploy/cpp/src/main.cc#L43
