### ISSUE TITLE
模型网页端部署

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleDetection#4125]
请问训练好的模型怎么部署到网页上？

**Comment by qingqing01** [comment]
部署到网页上需要使用 PaddleJS  https://github.com/PaddlePaddle/Paddle.js

**Comment by Monday-Leo** [comment]
有相关的js的教程吗，我看文档不是很齐全

**Comment by qingqing01** [comment]
所有教程都在首页了 https://github.com/PaddlePaddle/Paddle.js/blob/master/README_cn.md 也有一些OCR、手势等示例。

也可以在JS下面提issue问下。
