### ISSUE TITLE
No module named 'lap'

### ISSUE THREAD

**Issue by Chenzixi1** [PaddlePaddle/PaddleDetection#4126]
Windows 下如何安装'lap‘ ？可否有替代的方案？

**Comment by qingqing01** [comment]
可以参考这里 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/mot/README_cn.md#%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96

请问现在出了什么错？

lap用户多目标跟踪MOT的。 如果您不做多目标跟踪，可以在  requirements.txt 中去掉lap 

https://github.com/PaddlePaddle/PaddleDetection/blob/4630e56bd3c630d13633f0d9c00134d06f72b583/requirements.txt#L13

**Comment by nemonameless** [comment]
#3886 换gcc版本试试
