### ISSUE TITLE
PaddleDetection剪枝的基础上再量化该怎么做

### ISSUE THREAD

**Issue by TianyouChen** [PaddlePaddle/PaddleDetection#413]
我想用剪枝出来的模型进行量化，发现参数加载不匹配，网络加载原始yolov3，但是参数加载剪枝后的，这个该怎么配置修改让参数匹配并能量化训练？
详细信息如下：
训练指令：

```
python3 slim/quantization/train.py --not_quant_pattern slim_output \
 --eval --c ./configs/yolov3_mobilenet_v1_Headshoulder.yml -o max_iters=30000 \
save_dir=./output/prune_quant_yolov3 LearningRate.base_lr=0.0001 LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [10000]}]" pretrain_weights=output/prue_Headshoulder/yolov3_mobilenet_v1_Headshoulder/best_model
```

报错信息：

```
2020-03-30 09:53:24,269-INFO: 1690 samples in file dataset/voc/test.txt
2020-03-30 09:53:24,270-INFO: places would be ommited when DataLoader is not iterable
W0330 09:53:25.296880  6945 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0330 09:53:25.300591  6945 device_context.cc:245] device: 0, cuDNN Version: 7.6.
2020-03-30 09:53:28,249-INFO: Loading parameters from output/prue_Headshoulder/yolov3_mobilenet_v1_Headshoulder/best_model...
Traceback (most recent call last):
  File "slim/quantization/train.py", line 314, in <module>
    main()
  File "slim/quantization/train.py", line 193, in main
    ignore_params=ignore_params)
  File "/home/chenchaocun/PaddleDetection_3.27/ppdet/utils/checkpoint.py", line 142, in load_params
    fluid.io.set_program_state(prog, state)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/io.py", line 1942, in set_program_state
    .format(orig_para_np.shape, para.name, new_para_np.shape)
AssertionError: Shape not matching: the Program requires a parameter with a shape of ((512, 1024, 1, 1)), while the loaded parameter (namely [ yolo_block.0.0.0.conv.weights ]) has a shape of  ((51, 1024, 1, 1)).
```
多谢指教～

**Comment by qingqing01** [comment]
@TianyouChen `configs/yolov3_mobilenet_v1_Headshoulder.yml` 这个网络配置是裁剪之后的网络吗？错误是，加载的是裁剪之后的weight，但网络构建时的weight的shape却是裁剪之前的。

**Comment by TianyouChen** [comment]
> @TianyouChen `configs/yolov3_mobilenet_v1_Headshoulder.yml` 这个网络配置是裁剪之后的网络吗？错误是，加载的是裁剪之后的weight，但网络构建时的weight的shape却是裁剪之前的。

这是加载之前的，我问的就是裁剪之后的网络怎么确定网络结构并配置到yml里？

**Comment by heavengate** [comment]
在quant脚本中使用裁剪的网络结构和权重需要添加裁剪相关的代码，参考`slim/prune/prune.py`里如下段代码
https://github.com/PaddlePaddle/PaddleDetection/blob/a3eb2de17b89527f18f69ef33e91da85e16ba0d2/slim/prune/prune.py#L177
```
    pruned_params = FLAGS.pruned_params
    assert FLAGS.pruned_params is not None, \
        "FLAGS.pruned_params is empty!!! Please set it by '--pruned_params' option."
    pruned_params = FLAGS.pruned_params.strip().split(",")
    logger.info("pruned params: {}".format(pruned_params))
    pruned_ratios = [float(n) for n in FLAGS.pruned_ratios.strip().split(",")]
    logger.info("pruned ratios: {}".format(pruned_ratios))
    assert len(pruned_params) == len(pruned_ratios), \
        "The length of pruned params and pruned ratios should be equal."
    assert (pruned_ratios > [0] * len(pruned_ratios) and
            pruned_ratios < [1] * len(pruned_ratios)
            ), "The elements of pruned ratios should be in range (0, 1)."

    pruner = Pruner()
    train_prog = pruner.prune(
        train_prog,
        fluid.global_scope(),
        params=pruned_params,
        ratios=pruned_ratios,
        place=place,
        only_graph=False)[0]

    compiled_train_prog = fluid.CompiledProgram(train_prog).with_data_parallel(
        loss_name=loss.name,
        build_strategy=build_strategy,
        exec_strategy=exec_strategy)

    if FLAGS.eval:

        base_flops = flops(eval_prog)
        eval_prog = pruner.prune(
            eval_prog,
            fluid.global_scope(),
            params=pruned_params,
            ratios=pruned_ratios,
            place=place,
            only_graph=True)[0]
        pruned_flops = flops(eval_prog)
        logger.info("FLOPs -{}; total FLOPs: {}; pruned FLOPs: {}".format(
            float(base_flops - pruned_flops) / base_flops, base_flops,
            pruned_flops))
        compiled_eval_prog = fluid.compiler.CompiledProgram(eval_prog)
```

**Comment by TianyouChen** [comment]
> 在quant脚本中使用裁剪的网络结构和权重需要添加裁剪相关的代码，参考`slim/prune/prune.py`里如下段代码
> https://github.com/PaddlePaddle/PaddleDetection/blob/a3eb2de17b89527f18f69ef33e91da85e16ba0d2/slim/prune/prune.py#L177
> 
> ```
>     pruned_params = FLAGS.pruned_params
>     assert FLAGS.pruned_params is not None, \
>         "FLAGS.pruned_params is empty!!! Please set it by '--pruned_params' option."
>     pruned_params = FLAGS.pruned_params.strip().split(",")
>     logger.info("pruned params: {}".format(pruned_params))
>     pruned_ratios = [float(n) for n in FLAGS.pruned_ratios.strip().split(",")]
>     logger.info("pruned ratios: {}".format(pruned_ratios))
>     assert len(pruned_params) == len(pruned_ratios), \
>         "The length of pruned params and pruned ratios should be equal."
>     assert (pruned_ratios > [0] * len(pruned_ratios) and
>             pruned_ratios < [1] * len(pruned_ratios)
>             ), "The elements of pruned ratios should be in range (0, 1)."
> 
>     pruner = Pruner()
>     train_prog = pruner.prune(
>         train_prog,
>         fluid.global_scope(),
>         params=pruned_params,
>         ratios=pruned_ratios,
>         place=place,
>         only_graph=False)[0]
> 
>     compiled_train_prog = fluid.CompiledProgram(train_prog).with_data_parallel(
>         loss_name=loss.name,
>         build_strategy=build_strategy,
>         exec_strategy=exec_strategy)
> 
>     if FLAGS.eval:
> 
>         base_flops = flops(eval_prog)
>         eval_prog = pruner.prune(
>             eval_prog,
>             fluid.global_scope(),
>             params=pruned_params,
>             ratios=pruned_ratios,
>             place=place,
>             only_graph=True)[0]
>         pruned_flops = flops(eval_prog)
>         logger.info("FLOPs -{}; total FLOPs: {}; pruned FLOPs: {}".format(
>             float(base_flops - pruned_flops) / base_flops, base_flops,
>             pruned_flops))
>         compiled_eval_prog = fluid.compiler.CompiledProgram(eval_prog)
> ```

ok 我去折腾看下

**Comment by Fauny** [comment]
@TianyouChen 同样问题，解决了吗，可否分享一下修改后代码 🙏🙏
