### ISSUE TITLE
paddle detection训练问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleDetection#4137]
报错如下：
![image](https://user-images.githubusercontent.com/61399616/132281814-53fcea5f-840e-4718-b086-9e07417b07df.png)

**Comment by qingqing01** [comment]
看报错行数，您用的是PaddleDetection 2.0，RPN阶段anchor和gt匹配之后正样本个数是0，导致出错了。建议升级到最新版2.2试下。
