### ISSUE TITLE
paddleinference

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#4144]

**Comment by guotongjian** [comment]
各位老师好，我基于paddledetection做了一个应用的论文，推理用了教程里的paddleinference，把这个推理的时间写进了论文里，最近才意识到我用的模型的时间好像比其他论文的都快好多，想问一下这个paddleinference是优化过的吗，我很纠结算不算造假。。。。

**Comment by heavengate** [comment]
你好，方便给一下问题的相关信息么

**Comment by guotongjian** [comment]
> 你好，方便给一下问题的相关信息么

大神您好，我拿paddledetection做了一个应用的论文，然后用paddleinference推理，把推理时间写到了论文里，最近发现时间好像要比一般的快很多（比如darknet上的yolov3和paddleinference比较），想问下这个是优化过的吗，可以代表算法模型运行的时间吗，我这个算不算造假。。。

**Comment by qingqing01** [comment]
如果您实测、并且推理检测结果正确，就是正确的。  关于速度的比较，需要关注 硬件差异，比如V100 、TitanX速度不同， 推理软件的差异，比如是否用TensorRT速度不同， 是否用FP16速度都不同。

**Comment by guotongjian** [comment]
> 如果您实测、并且推理检测结果正确，就是正确的。 关于速度的比较，需要关注 硬件差异，比如V100 、TitanX速度不同， 推理软件的差异，比如是否用TensorRT速度不同， 是否用FP16速度都不同。

好的，谢谢您
