### ISSUE TITLE
关节点检测

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#4145]
您好，我是用PP-YOLOv2+HRNET进行联合关节点推理预测，但是显示的视频上始终只能预测一个人，我想问一下什么原因
链接：https://pan.baidu.com/s/1_uKmx6sk2WuMmGC0vtdlAg 
提取码：gl4o 
希望您能帮我看一下视频预测不准的原因，视频我放在百度网盘里面了，谢谢!

**Comment by jerrywgz** [comment]
建议只使用PP-YOLOv2看下检测的效果并调优检测模型，关键点模型效果会依赖于检测模型输出的检测框
