### ISSUE TITLE
VisualDL

### ISSUE THREAD

**Issue by lovesusu1314** [PaddlePaddle/PaddleDetection#4146]
可以在paddleDetection里增加可视化的指标吗
比如 增加acc

**Comment by jerrywgz** [comment]
目前paddleDetection有mAP的指标，已经单个类别的AP并绘制PR曲线，可以参考这里的文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/docs/tutorials/GETTING_STARTED_cn.md
