### ISSUE TITLE
paddlex2.0.0训练模型运行在相同部署环境报错

### ISSUE THREAD

**Issue by 15254042250** [PaddlePaddle/PaddleDetection#4147]
这是报错信息
---------------------------------------------------------------------------UnboundLocalError                         Traceback (most recent call last)<ipython-input-3-6abedaeb5580> in <module>
      6 # 而使用Predictor方式加载模型，会对模型计算图进行优化，预测速度会更快
      7 print("Loading model...")
----> 8 model = pdx.deploy.Predictor('/home/aistudio/inference_model/inference_model')
      9 print("Model loaded.")
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/deploy.py in __init__(self, model_dir, use_gpu, gpu_id, cpu_thread_num, use_mkl, mkl_thread_num, use_trt, use_glog, memory_optimize, max_trt_batch_size, trt_precision_mode)
     50         """
     51         self.model_dir = model_dir
---> 52         self._model = load_model(model_dir, with_net=False)
     53 
     54         if trt_precision_mode.lower() == 'float32':
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/load_model.py in load_model(model_dir, **params)
     84     with paddle.utils.unique_name.guard():
     85         model = getattr(paddlex.cv.models, model_info['Model'])(
---> 86             **model_info['_init_params'])
     87         if with_net:
     88             if status == 'Pruned' or osp.exists(
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/detector.py in __init__(self, num_classes, backbone, anchors, anchor_masks, use_iou_aware, use_spp, use_drop_block, scale_x_y, ignore_threshold, label_smooth, use_iou_loss, use_matrix_nms, nms_score_threshold, nms_topk, nms_keep_topk, nms_iou_threshold, **params)
   1502         self.anchors = anchors
   1503         self.anchor_masks = anchor_masks
-> 1504         self.downsample_ratios = downsample_ratios
   1505         self.model_name = 'PPYOLOv2'
   1506 
UnboundLocalError: local variable 'downsample_ratios' referenced before assignment

以下是操作步骤 在aistudio
!pip install paddlex==2.0.0 -i https://mirror.baidu.com/pypi/simple

PaddleDetection-release-2.1 环境

voc数据集

这是训练代码
from paddlex import transforms as T
import paddlex as pdx
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

train_transforms = T.Compose([
    T.MixupImage(mixup_epoch=-1), T.RandomDistort(),
    T.RandomExpand(im_padding_value=[123.675, 116.28, 103.53]), T.RandomCrop(),
    T.RandomHorizontalFlip(), T.BatchRandomResize(
        target_sizes=[
            320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704,
            736, 768
        ],
        interp='RANDOM'), T.Normalize(
            mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

eval_transforms = T.Compose([
    T.Resize(
        target_size=640, interp='CUBIC'), T.Normalize(
            mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

train_dataset = pdx.datasets.VOCDetection(
    data_dir='/home/aistudio/gao_pai_yi_voc',
    file_list='/home/aistudio/gao_pai_yi_voc/train_list.txt',
    label_list='/home/aistudio/gao_pai_yi_voc/labels.txt',
    transforms=train_transforms,
    shuffle=True)
eval_dataset = pdx.datasets.VOCDetection(
    data_dir=r'/home/aistudio/gao_pai_yi_voc',
    file_list=r'/home/aistudio/gao_pai_yi_voc/val_list.txt',
    label_list=r'/home/aistudio/gao_pai_yi_voc/labels.txt',
    transforms=eval_transforms)

num_classes = len(train_dataset.labels)
model = pdx.det.PPYOLOv2(num_classes=num_classes, backbone='ResNet50_vd_dcn')
model.train(
    num_epochs=170,
    train_dataset=train_dataset,
    train_batch_size=8,
    eval_dataset=eval_dataset,
    pretrain_weights='COCO',
    learning_rate=0.005 / 12,
    warmup_steps=1000,
    warmup_start_lr=0.0,
    lr_decay_epochs=[105, 135, 150],
    save_interval_epochs=1,
    save_dir='/home/aistudio/out',
    use_vdl=True
    )

这是导出的推理模型代码
!paddlex --export_inference --model_dir=/home/aistudio/out/epoch_1/ --save_dir=/home/aistudio/inference_model

这是预测代码
import paddlex as pdx
import cv2
print("Loading model...")
model = pdx.deploy.Predictor('/home/aistudio/inference_model/inference_model')
print("Model loaded.")

然后就报了开头的错误

解决办法
修改
paddlex2.0源码  paddlex/cv/models/detector.py  第1504行 将其屏蔽
#self.downsample_ratios = downsample_ratios

**Comment by jerrywgz** [comment]
可以到https://github.com/PaddlePaddle/PaddleX 下提issue哈～
