### ISSUE TITLE
PaddleDetection多模态输入转onnx模型

### ISSUE THREAD

**Issue by Chenzixi1** [PaddlePaddle/PaddleDetection#4149]
目前paddledetection可实现多模态输入吗？

尝试在sample中加入多输入。‘depth’可实现，但是无法转成onnx模型，是否可以解决？

mobilenet_v1.py 399行
    def forward(self, inputs):

在转onnx的时候，需要将inputs = inputs['image']，因此只能支持单输入

**Comment by jerrywgz** [comment]
目前backbone部分只接受image字段的输入，如果输入是不同字段可以修改下backbone的forward并在architectures中指定传入字段

**Comment by Chenzixi1** [comment]
您好，通过字典字段的方式可以实现多输入，但是在转换onnx的时候，如何实现多模态输入呢？

paddle.onnx.export(model, save_path, input_spec=[rgb, depth], opset_version=11)

**Comment by jiangjiajun** [comment]
> 您好，通过字典字段的方式可以实现多输入，但是在转换onnx的时候，如何实现多模态输入呢？
> 
> paddle.onnx.export(model, save_path, input_spec=[rgb, depth], opset_version=11)

Hi， Chezixi1, 当前在保存模型时，无论是以`ONNX`形式导出，或者保存成Paddle格式的模型，在接口上的使用方式是一致的。

当模型为多输入时，则在`input_spec`参数传入多个输入的`input_spec`即可
