### ISSUE TITLE
跪求模型保存改成以前的格式

### ISSUE THREAD

**Issue by Cristhine** [PaddlePaddle/PaddleDetection#415]
旧版本ppadet保存模型是分层的模型，可以自己决定是不是freeze使用；

**Comment by qingqing01** [comment]
@Cristhine 您是觉得分层(每个参数一个文件)更有好一些吗？ 当前的接口，即可以加载之前每个参数一个文件的模型，也可以加载合成一个文件的模型。

**Comment by Cristhine** [comment]
> @Cristhine 您是觉得分层(每个参数一个文件)更有好一些吗？ 当前的接口，即可以加载之前每个参数一个文件的模型，也可以加载合成一个文件的模型。

那当前版本如何保存为之前的形式？config文件可以设置吗？

**Comment by qingqing01** [comment]
config里不能设置，但还原代码，https://github.com/PaddlePaddle/PaddleDetection/pull/229/files
