### ISSUE TITLE
paddletetection 的训练后的动态图模型可以在转成静态图模型吗，怎么转

### ISSUE THREAD

**Issue by Myxrf** [PaddlePaddle/PaddleDetection#4151]

**Comment by jerrywgz** [comment]
可以通过tools/export_model.py完成动静转换 可以参考文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/docs/tutorials/GETTING_STARTED_cn.md#8-%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA

**Comment by Myxrf** [comment]
> 可以通过tools/export_model.py完成动静转换 可以参考文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/docs/tutorials/GETTING_STARTED_cn.md#8-%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA

因为之前都是用导出的静态图的模型在python和c++上使用，现在用动态图导出的模型格式跟静态图的完全不一样了，可以先用动态图版本的模型转成静态图在导出吗，还是说静态图版本的export_model.py同样也能导出动态图版本的模型，感谢！！1

**Comment by jerrywgz** [comment]
请问是哪个模型呢，目前动态图和静态图在模型结构上有一些差异，所以模型是没法通用的。直接把动态图的模型导出成inference model的格式这样不行吗？

**Comment by Myxrf** [comment]
> 请问是哪个模型呢，目前动态图和静态图在模型结构上有一些差异，所以模型是没法通用的。直接把动态图的模型导出成inference model的格式这样不行吗？
动态图导出是可以的，但是因为之前是用静态图的模型导出在c++上调用，改了里面的一些东西，后面用动态图版本训练的模型导出模型的文件形式不一样了，没办法直接调用。就是想问问在模型没导出之前（刚训练完），可以把动态图版本的模型先转成静态图版本再导出吗

**Comment by jerrywgz** [comment]
用动态图版本导出的模型，用c++调用的接口和静态图基本相同，可以参考下PaddleDetection deploy/cpp/目录下的调用方式。 PaddleDetection现在动态图和静态图版本是不互通的
