### ISSUE TITLE
训练后精度很低

### ISSUE THREAD

**Issue by helloyan** [PaddlePaddle/PaddleDetection#4153]
使用paddledetection训练了20轮，结果很差，使用的是 ppyolov2_r50vd_dcn_365e_coco.yml，修改了一些参数

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.123
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.401
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.039
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.104
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.041
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.098
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.159
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.324
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.454
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.217
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.453
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.553

同样的数据抛到easydl上效果很好
![image](https://user-images.githubusercontent.com/1699033/132627708-abb2cfc9-6f40-4364-8e88-351423b89ed1.png)
![image](https://user-images.githubusercontent.com/1699033/132628019-afd6224b-f2ca-4ea7-ae9e-b5f54faf2bb9.png)

可能是哪里配置出问题了吗？

**Comment by yghstill** [comment]
@helloyan 数据太少，PPYOLOv2模型太大不易收敛，加载coco上训好的预训练模型作为pretrain_weights，增大训练轮数再试下。或者换更小的模型比如ppyolo-mobilenetv3这类模型
