### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/PaddleDetection#4156]
请问在训练的过程之中是不会进行评估吗？我看到目前为止还没有输出map那些指标，那么没有map怎么看有没有过拟合？
![image](https://user-images.githubusercontent.com/40531744/132663847-983833d2-a343-4d9d-b2f1-d63bd254cd93.png)
目前我的训练输出日志如下，不知有没问题？

**Comment by yghstill** [comment]
@hhhhhhogan 训练的时候加上--eval指令就可以边训练边评估，还可以设置eval的epoch间隔数：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/runtime.yml#L4
