### ISSUE TITLE
Segmentation fault` is detected by the operating system

### ISSUE THREAD

**Issue by helloyan** [PaddlePaddle/PaddleDetection#4158]
这个错误不时发生，昨天训练的好好的模型，今天重启以后重新运行相同命令就报了下面的错误，执行train.py
jetson xavier jetpack 4.5，
paddlepaddle  2.1.2
paddledetection 拉的最新的release2.2

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   cuDevicePrimaryCtxRetain
1   paddle::framework::SignalHandle(char const*, int)
2   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1631198054 (unix time) try "date -d @1631198054" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7f92f05090) received by PID 15482 (TID 0x7f92f52010) from PID 18446744071879807120 ***]

**Comment by yghstill** [comment]
@helloyan 看`cuDevicePrimaryCtxRetain `字段应该是GPU占用出问题， jetson资源有限，训练耗费资源很多，一般不做模型训练，只做预测部署，建议在GPU开发机中训练模型。
