### ISSUE TITLE
关键点示例代码运行出现“NameError: name 'TopDownEvalAffine' is not defined”报警

### ISSUE THREAD

**Issue by sinoboy168** [PaddlePaddle/PaddleDetection#4159]
完全按照示例运行，最后出现这个报警，不知道如何解决，谢谢！

**Comment by sinoboy168** [comment]
用的是deploy/python/keypoint_infer.py

**Comment by zhiboniu** [comment]
你好，麻烦查看一下preprocess_op.h中这个类是否存在：
class TopDownEvalAffine

另外，最好贴一下完整的报错信息更方便排查。

**Comment by sinoboy168** [comment]
谢谢，我更新了版本，现在好了，但我前面这个版本一个月前下载的，你们好像这期间也没有更新吧，所以问题也不知道再哪。
另外还有个问题，python setup.py install 里缺少version.py 文件

**Comment by zhiboniu** [comment]
嗯，有可能是键盘误操作导致名称变更了。与repo保持同步就好。
另外，version.py文件是通过setup.py生成的，不是本地读取的

参看代码：
def write_version_py(filename='ppdet/version.py'):
    ver_str = """# THIS FILE IS GENERATED FROM PADDLEPADDLE SETUP.PY
#
full_version    = '%(version)s'
commit          = '%(commit)s'
"""

    _git_commit = git_commit()
    with open(filename, 'w') as f:
        f.write(ver_str % {
            'version': PPDET_VERSION,
            'commit': _git_commit})

write_version_py()

**Comment by sinoboy168** [comment]
那可能是ppdet没有写权限，所以没能安装
