### ISSUE TITLE
使用PaddleDetection和BML训练结果相差很大

### ISSUE THREAD

**Issue by CharlesYXW** [PaddlePaddle/PaddleDetection#4164]
请问BML里的YOLOv3-Darknet的具体参数配置和PaddleDetection里面的yolov3_darknet53_270e_coco.yml有什么差别吗，我完全按照BML里面的脚本内容配置，且根据BML里面的训练日志修改了我的学习率、warmup策略和，但是训练效果相差很大，自己用PaddleDetection训练的best test box ap只有0.5，然而BML的ap却能到90多。
另外，刚才仔细看了一下BML的训练日志，是不是因为BML里面test box的ap取的是IoU=0.5，而PaddleDetection取的是IoU=0.5:0.95

![AP](https://user-images.githubusercontent.com/51958687/132826665-a5bc5317-2ba6-4bb7-9b16-553457d2fd31.PNG)

**Comment by lyuwenyu** [comment]
是的 ppdet的指标按照iou-0.5:0.95
