### ISSUE TITLE
FairMot模型目前不支持export导出

### ISSUE THREAD

**Issue by rock4you** [PaddlePaddle/PaddleDetection#4165]
具体有哪些字段，以及每个字段的含义

**Comment by nemonameless** [comment]
推理的输出结果也是跟踪的结果，包括坐标 分数和id号

**Comment by rock4you** [comment]
执行导出命令后报错：
`python tools/export_model.py \
-c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml \
--output_dir=./inference_model \
-o weights=output/fairmot_dla34_30e_1088x608/0.pdparams`

/usr/local/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favourof importlib; see the module's documentation for alternative uses
  import imp
[09/13 20:57:42] ppdet.utils.checkpoint INFO: reid.classifier.weight not used, shape [128, 519] unmatched with [128, 14455] in model.
[09/13 20:57:42] ppdet.utils.checkpoint INFO: reid.classifier.bias not used, shape [519] unmatched with [14455] in model.
[09/13 20:57:42] ppdet.utils.checkpoint INFO: Finish loading model weights: output/fairmot_dla34_30e_1088x608/0.pdparams
[09/13 20:57:42] ppdet.engine ERROR: Architecture: FairMOT is not supported for exporting model now

**Comment by nemonameless** [comment]
> 执行导出命令后报错：
> `python tools/export_model.py \ -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml \ --output_dir=./inference_model \ -o weights=output/fairmot_dla34_30e_1088x608/0.pdparams`
> 
> /usr/local/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favourof importlib; see the module's documentation for alternative uses
> import imp
> [09/13 20:57:42] ppdet.utils.checkpoint INFO: reid.classifier.weight not used, shape [128, 519] unmatched with [128, 14455] in model.
> [09/13 20:57:42] ppdet.utils.checkpoint INFO: reid.classifier.bias not used, shape [519] unmatched with [14455] in model.
> [09/13 20:57:42] ppdet.utils.checkpoint INFO: Finish loading model weights: output/fairmot_dla34_30e_1088x608/0.pdparams
> [09/13 20:57:42] ppdet.engine ERROR: Architecture: FairMOT is not supported for exporting model now

release/2/2和develop分支已经支持了，请更新代码
