### ISSUE TITLE
paddleDetection训练日志问题

### ISSUE THREAD

**Issue by lovesusu1314** [PaddlePaddle/PaddleDetection#4166]
paddleDetection训练完后的日志文件 只看到train/loss 没有看到val/loss，，怎么看的呀

**Comment by lyuwenyu** [comment]
ppdet在val时候不会计算loss 
如果想要查看的话可以修改 `1. eval reader  2. modeling/architectures 3. engine/trainer` 相应的逻辑

**Comment by lovesusu1314** [comment]
感谢回复！  请问你之前有改过吗？可以让我看看 示例吗

**Comment by lyuwenyu** [comment]
没改过 需要你自己改 这三个地方
