### ISSUE TITLE
在paddelDetection使用呢Mask rcnn训练coco类型数据的问题

### ISSUE THREAD

**Issue by piaomiao920** [PaddlePaddle/PaddleDetection#4167]
问题描述：coco类型数据集无法训练多分类，只能训练单分类。
环境：window10，paddelDetection2.2，
步骤如下：
1、使用x2coco.py将labelme数据类型转成coco数据集类型
得到的json文件的分类为
"categories": [
        {
            "supercategory": "component",
            "id": 1,
            "name": "kettle"
        },
        {
            "supercategory": "component",
            "id": 2,
            "name": "book"
        }
    ],
2、使用train.py进行训练，使用的config文件中，num_classes:只能填2，填3就报错，按理说加上背景类，应该填3才对
报错信息如下：
  File "F:\PaddleDetection\PaddleDetection\ppdet\metrics\json_results.py", line 30, in get_det_res
    category_id = label_to_cat_id_map[int(num_id)]
KeyError: 2

最终只能填了：num_classes: 2，不报错，但是只能检测单分类

3、使用infer.py进行推理，所有的检测结果只有kettle分类，无book

求助，怎么训练多分类，难道是我的coco格式json文件不对吗，我用paddelDetection2.2自带的 tools/x2coco.py从labelme转换啊

**Comment by lyuwenyu** [comment]
两类就是num_classes==2

**Comment by piaomiao920** [comment]
感谢您的回复，难道paddelDetection2.2版本，对于maskrcnn这种两个阶段检测器，不是需要手动 给背景类加+1了吗

**Comment by lyuwenyu** [comment]
嗯呢 现在ppdet默认会处理背景类
