### ISSUE TITLE
solov2训练后连训练集图片都检不出来，不知道哪里出问题，但是是按照步骤一步步设置的

### ISSUE THREAD

**Issue by chenneng** [PaddlePaddle/PaddleDetection#4168]
solov2训练后连训练集图片都检不出来，不知道哪里出问题，但是是按照步骤一步步设置的

**Comment by nemonameless** [comment]
方便给出详细点的训练配置描述吗？方便传下训练最后的loss截图吗？是自定义数据集的话建议先检查确保gt标注制作没有问题再训练。
