### ISSUE TITLE
paddleDetection视频流检测问题

### ISSUE THREAD

**Issue by lovesusu1314** [PaddlePaddle/PaddleDetection#4169]
输入命令python PaddleDetection/deploy/python/infer.py --model_dir=PaddleDetection/inference_model_yolo/yolov3_darknet53_270e_coco --camera_id=0 --device=gpu --output_dir=output

打开视频或视频文件检测不到一会就自动断掉了
![image](https://user-images.githubusercontent.com/49550942/132987256-ce6041d6-c5c5-4cf9-85da-436263381feb.png)

```
detect frame:25
[0.02758023 0.01488077 0.01294961 0.01242954] [0. 0. 0. 0.]
detect frame:26
[WARNNING] No object detected.
Traceback (most recent call last):
  File "PaddleDetection/deploy/python/infer.py", line 675, in <module>
    main()
  File "PaddleDetection/deploy/python/infer.py", line 632, in main
    predict_video(detector, FLAGS.camera_id)
  File "PaddleDetection/deploy/python/infer.py", line 581, in predict_video
    im = visualize_box_mask(
  File "D:\xiangmu\voc2coco\PaddleDetection\deploy\python\visualize.py", line 46, in visualize_box_mask
    im = draw_box(im, results['boxes'], labels, threshold=threshold)
  File "D:\xiangmu\voc2coco\PaddleDetection\deploy\python\visualize.py", line 129, in draw_box
    print(np_boxes[:, 1],np_boxes[:,0])
IndexError: index 1 is out of bounds for axis 1 with size 0
[ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-h4wtvo23\opencv\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback`
```

**Comment by lovesusu1314** [comment]
![image](https://user-images.githubusercontent.com/49550942/132987291-38716378-dc3f-4892-ad31-8fedbbd71753.png)

**Comment by nemonameless** [comment]
其他视频测试过有同样情况吗？方便发下这个测试视频吗？

**Comment by Myxrf** [comment]
> 输入命令python PaddleDetection/deploy/python/infer.py --model_dir=PaddleDetection/inference_model_yolo/yolov3_darknet53_270e_coco --camera_id=0 --device=gpu --output_dir=output
> 
> 打开视频或视频文件检测不到一会就自动断掉了
> ![image](https://user-images.githubusercontent.com/49550942/132987256-ce6041d6-c5c5-4cf9-85da-436263381feb.png)
> `detect frame:25 [0.02758023 0.01488077 0.01294961 0.01242954] [0. 0. 0. 0.] detect frame:26 [WARNNING] No object detected. Traceback (most recent call last): File "PaddleDetection/deploy/python/infer.py", line 675, in <module> main() File "PaddleDetection/deploy/python/infer.py", line 632, in main predict_video(detector, FLAGS.camera_id) File "PaddleDetection/deploy/python/infer.py", line 581, in predict_video im = visualize_box_mask( File "D:\xiangmu\voc2coco\PaddleDetection\deploy\python\visualize.py", line 46, in visualize_box_mask im = draw_box(im, results['boxes'], labels, threshold=threshold) File "D:\xiangmu\voc2coco\PaddleDetection\deploy\python\visualize.py", line 129, in draw_box print(np_boxes[:, 1],np_boxes[:,0]) IndexError: index 1 is out of bounds for axis 1 with size 0 [ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-h4wtvo23\opencv\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback`

我在C++部署的时候也遇到过，官方也说是他们的bug，后面换了个最新预测库就行了。python端话的可以升级一下版本看看。
