### ISSUE TITLE
Mixup读取数据报错[Other General Issues]

### ISSUE THREAD

**Issue by wenjiett** [PaddlePaddle/PaddleDetection#4172]
我想请问一下，我在ai studio中使用paddledetection进行训练模型时使用了Mixup的数据增强方式，但是出现了如下报错：

```
File "/home/aistudio/PaddleDetection-release-2.2/ppdet/data/transform/operators.py", line 1626, in __call__
    gt_bbox = np.concatenate((gt_bbox1, gt_bbox2), axis=0)
File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
```

我打印gt_bbox1, gt_bbox2后发现出现了空值，但是我对train.txt文件中的xml文件进行遍历，并没有发现有空的bbox，请问这是什么情况呢？

**Comment by nemonameless** [comment]
方便截图下你训练的reader配置吗

**Comment by ghostxsl** [comment]
我们会对gt_bbox做非法检查，如果bbox的面积小于0，是不会被加入到gt中去的，你可以检查一下你的数据集中有没有非法的bbox的标注

看你的报错信息是 ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)，就是说gt_bbox2只有一维，你是不是修改过代码或者reader没有配置正确呢？正常来说即便是空值，shape是[0, 4]，维度也是两维

**Comment by wangxinxin08** [comment]
如果是VOC数据集的话，这个问题在PR: https://github.com/PaddlePaddle/PaddleDetection/pull/4097 修复了，可以按照这个PR修复下代码

**Comment by wenjiett** [comment]
> 如果是VOC数据集的话，这个问题在PR: #4097 修复了，可以按照这个PR修复下代码

问题已经解决了，之前是数据集有点问题
