### ISSUE TITLE
[Other General Issues]

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#4175]
我这里模型在训练的时候没问题，但是一到模型导出的时候形状就不对了，然后具体的问题我录了个视频
[https://www.bilibili.com/video/bv1FQ4y1r7UX](https://www.bilibili.com/video/bv1FQ4y1r7UX)

**Comment by ghostxsl** [comment]
是这样的，首先，导出模型用的是paddle的动转静的方法，你在动态图里写的print非tensor的函数不会被解析进你的导出模型的。
其次，你这里的错误是shape对不上，应该是你动态图中某些写法不支持动转静导出，才会出现这种问题。
那两个tensor你是不是用了reshape、插值等之类改变shape的方法？
你可以参考一下官网上关于动转静的文档，有些语法是不支持的：
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/04_dygraph_to_static/grammar_list_cn.html
