### ISSUE TITLE
[Other General Issues] solov2在训练时学习律逐渐变大，最后训练曲线起飞了

### ISSUE THREAD

**Issue by kaixin-bai** [PaddlePaddle/PaddleDetection#4181]
## 描述问题/Describe the bug
在使用solov2训练实例分割时学习律逐渐变大最后训练曲线起飞。最后学习律稳定在0.01然后不再变化
![loss (1)](https://user-images.githubusercontent.com/38804949/133275461-d6334549-dc64-4853-8c97-f567b6d44ada.png)

请问我应该如何调整参数，调整哪些参数？

## 复现/Reproduction
以下为配置文件中学习律的默认参数，使用的是`solov2_r101_vd_fpn_3x`，其他参数均为默认参数，训练为单机单卡，大概900个iteration后训练曲线起飞。

```bash
LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [180000, 240000]
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2
```

**Comment by qingqing01** [comment]
默认配置base_lr: 0.01是按照单机8卡训练、每个卡的batch_size=2配置的。如果改成单机单卡，batch_size=2，降base_lr调整成0.00125 。参考FAQ:  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/docs/tutorials/FAQ/FAQ%E7%AC%AC%E9%9B%B6%E6%9C%9F.md

**Comment by kaixin-bai** [comment]
> 默认配置base_lr: 0.01是按照单机8卡训练、每个卡的batch_size=2配置的。如果改成单机单卡，batch_size=2，降base_lr调整成0.00125 。参考FAQ: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/docs/tutorials/FAQ/FAQ%E7%AC%AC%E9%9B%B6%E6%9C%9F.md

给大佬比心了
