### ISSUE TITLE
yolo系列的更新

### ISSUE THREAD

**Issue by TimZhang001** [PaddlePaddle/PaddleDetection#4183]
最近的yolov5  yolox关注度比较高，效果也都不错，是否有考虑在paddle上进行更新呢

**Comment by heavengate** [comment]
感谢建议，我们这边也在评估和跟进，在排期复现和优化，有结果会第一时间发布出来，可以关注一下~

**Comment by TimZhang001** [comment]
> 感谢建议，我们这边也在评估和跟进，在排期复现和优化，有结果会第一时间发布出来，可以关注一下~

如果可以的话，还可以看看yolop 这种端到端的多任务训练在工业领域很有意义

**Comment by qingqing01** [comment]
@TimZhang001 会排期考虑，我们也欢迎您贡献~

**Comment by nemonameless** [comment]
https://github.com/nemonameless/PaddleDetection_YOLOSeries  已支持。
也可以看宣传稿了解下 https://mp.weixin.qq.com/s/yesNqqaf5bvLERWEgBWMwA
