### ISSUE TITLE
[BUG]报错找不到原因

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4185]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.
3. 确认bug是否在新版本里还未修复/The bug has not been fixed in the latest version.

## 描述问题/Describe the bug
重开了项目按照另一个项目一模一样的步骤训练，就是报错，我只改了数据集，但是数据集的位置，配置（annotations、images+四个txt文件）都是一样的，只是图片内容不同，为什么报错？

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
!python -u tools/train.py -c configs/yolov3_darknet_voc.yml -o  use_gpu=True --use_vdl=True --vdl_log_dir=vdl_dir/scalar --eval
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

改了yolov3_darknet_voc.yml的num_classes为2。num_classes: 2
3. 您使用的数据集是？/What dataset did you use?
自己的数据集
4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
Traceback (most recent call last):
  File "tools/train.py", line 412, in <module>
    main()
  File "tools/train.py", line 180, in main
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
  File "/home/aistudio/PaddleDetection/static/ppdet/data/reader.py", line 442, in create_reader
    reader = Reader(**cfg)()
  File "/home/aistudio/PaddleDetection/static/ppdet/data/reader.py", line 210, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/home/aistudio/PaddleDetection/static/ppdet/data/source/dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "/home/aistudio/PaddleDetection/static/ppdet/data/source/voc.py", line 154, in load_roidb_and_cname2cid
    gt_class.append([cname2cid[cname]])
KeyError: 'fire'
## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
Paddle2.1.2，paddle detection我不会看版本

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
Windows
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
3
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by heavengate** [comment]
是否是没有对应修改数据集下`label_list`文件里的类别信息，VOC格式数据集需要在`label_list`文件里每行写一下类别，看报错是没找到file类别，应该是`label_list`没有修改加载的是VOC的默认类别
