### ISSUE TITLE
训练静态图的cascade_mask_rcnn_dcnv2_se154_vd_fpn_gn_s1x_ms_test 时，类别4类，number class 改为5，训练时eval报错

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleDetection#4190]
<img width="977" alt="d0499dd7fe0e12542f95ac645ac781bb" src="https://user-images.githubusercontent.com/67897601/133407566-459f7e11-f384-44f3-ba80-34620efc4b12.png">

**Comment by heavengate** [comment]
静态图的配置文件里有多处`num_classes`配置，确认一下模型对应的配置文件和对应的`cascade_rcnn_xxx_reader.yml`文件里有没有没有修改的`num_classes`配置，看报错应该就是配置不一致导致shape不一致
