### ISSUE TITLE
[BUG]在使用AIStudio时，visualdl service 出现问题

### ISSUE THREAD

**Issue by gaooolianggg** [PaddlePaddle/PaddleDetection#4197]
在使用AIStudio时，我选择了边训练边eval，但是在visualdl service的页面中，bbox-mAP始终没有更新，而loss更新正常

**Comment by jerrywgz** [comment]
我这里看到bbox-mAP在每一个epoch之后是可以正常更新的哈，可以在这里观察下map_value是不是每次正常更新了https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/engine/callbacks.py#L254

**Comment by YixinKristy** [comment]
visualdl前端界面是15s更新一次哈~
