### ISSUE TITLE
特色垂类跟踪模型

### ISSUE THREAD

**Issue by Sencc** [PaddlePaddle/PaddleDetection#4200]
特色垂类跟踪模型中的FairMOT模型不能下载了，可以提供一下吗，谢谢！ 链接是 https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608_kitticars.pdparams

**Comment by nemonameless** [comment]
你好，现在这个链接也可以下载到，其实已更名为 https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608_kitti_vehicle.pdparams  ，两个链接权重现在都可下载了是同一份。更推荐使用 bdd100k训好的模型  https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608_bdd100k_vehicle.pdparams   近期会更新在develop分支
