### ISSUE TITLE
anchor_cluster.py生成的anchors训练的结果还没有自带的anchors精度高

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleDetection#4201]
PP-YOLO
使用PP-YOLO的ResNet18vd
原档anchors如下：
anchors: [[10, 14], [23, 27], [37, 58], [81, 82], [135, 169], [344, 319]]

使用anchor_cluster.py生成anchors如下图
生成命令：  python anchor_cluster.py -c annotations\train.yml -n 6 -s 416,256 -m v2 -i 1000
![image](https://user-images.githubusercontent.com/88479008/133746620-7f988cd6-d90a-48dc-acc2-9c4976137e78.png)
anchors: [[30, 35], [37, 35], [36, 40], [47, 48], [53, 62], [59, 61]]

30张图片  都训练10分钟
自带的anchors训练效果很好，100%识别，识别框也很准确
用anchor_cluster.py生成的anchors训练   同样的参数训练有10%无法识别   还有些识别框不准确，如下图：
![image](https://user-images.githubusercontent.com/88479008/133747866-dc9189a4-ea89-4bf0-8ee2-f25edb5a7b72.png)
正常标注如下：
![image](https://user-images.githubusercontent.com/88479008/133747936-920aeffc-d108-46a3-be16-b9d61748e7f3.png)

是哪里参数设置问题吗？

**Comment by yghstill** [comment]
@534114658 原本的anchor设置是在coco大规模数据上聚类得到的，鲁棒性很高，图片较少时不建议重新聚类了。或者要确认下anchors这个要在网络和reader中两处同时修改
