### ISSUE TITLE
导出模型时我把NMS层去掉了，推理的时候输出如下结果，想问一下这个结果的含义是什么？需要通过怎样的操作才能输出正确的目标检测结果？

### ISSUE THREAD

**Issue by gyr-kdgc** [PaddlePaddle/PaddleDetection#4202]
{'Concat_3': array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08]]],
      dtype=float32), 'Concat_5': array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08]]],
      dtype=float32), 'Concat_7': array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -2.1118117e+08]]],
      dtype=float32), 'save_infer_model/scale_0.tmp_0': array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)}

**Comment by yghstill** [comment]
@gyr-kdgc 去除nms是为了导出到onnx吗？一般不建议去除nms导出，如果要去除，需要将后处理decode和nms部分单独实现：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/modeling/post_process.py#L36
可以查看配置文件中BBoxPostProcess是如何配置的
