### ISSUE TITLE
训练keypoint模型，数据集有四个点（物体的四个角点），训练报错

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleDetection#4203]
<img width="1183" alt="1b97b038948fb27bda66b30ad7415c6d" src="https://user-images.githubusercontent.com/67897601/133755486-88b40387-5288-4cbb-87b6-13ed703009cc.png">
![Uploading 1b97b038948fb27bda66b30ad7415c6d.png…]()
![a0ee2f7a6e016537432cda0351fec839](https://user-images.githubusercontent.com/67897601/133755583-c10b485c-0aca-452c-9632-b9680fb15f27.jpg)
配置文件修改了以下部分：
<img width="757" alt="681b8958702d5f7115e2272d03e1325e" src="https://user-images.githubusercontent.com/67897601/133755742-42bb70cf-f90d-4a18-b404-616e06ed87bd.png">
paddle 2.1.2

**Comment by aishangmaxiaoming** [comment]
![a0ee2f7a6e016537432cda0351fec839](https://user-images.githubusercontent.com/67897601/133755867-2d99fe3a-4249-4722-b8c1-5ebd89607459.jpg)

**Comment by zoooo0820** [comment]
请问数据中一张图的角点数量大约有多少个呢？看这个报错似乎是目标数目超过max_people这个参数的值了，方便的话可以再发下样例数据标注看看。

**Comment by aishangmaxiaoming** [comment]
> 请问数据中一张图的角点数量大约有多少个呢？看这个报错似乎是目标数目超过max_people这个参数的值了，方便的话可以再发下样例数据标注看看。

max_people 可以随意调大吗

**Comment by aishangmaxiaoming** [comment]
> 请问数据中一张图的角点数量大约有多少个呢？看这个报错似乎是目标数目超过max_people这个参数的值了，方便的话可以再发下样例数据标注看看。

我一个实例四个点，每张图不超过30个实例呀

**Comment by zoooo0820** [comment]
> > 请问数据中一张图的角点数量大约有多少个呢？看这个报错似乎是目标数目超过max_people这个参数的值了，方便的话可以再发下样例数据标注看看。
> 
> 我一个实例四个点，每张图不超过30个实例呀

这个参数对输出有影响，过大会对显存占用和速度有一定影响。
