### ISSUE TITLE
图片尺寸和网络输入尺寸、anchor之间的设置关系

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleDetection#4208]
所给数据集图片均为200x200,但是采用faster_rcnn_r50_vd_fpn_2x_coco.yml配置文件训练时，网络默认输入尺寸和anchor设置如下：
（1）网络faster_rcnn_r50_vd_fpn默认输入为大概为[800, 1333]左右，请问在实际训练种，网络尺寸是应该设置为200x200，还是使用默认的800x1333？
（2） 如果使用200x200,anchor的尺寸如何修改？？

TrainReader:
 - **RandomResize: {target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], interp: 2, keep_ratio: True}**

EvalReader:
 **- Resize: {interp: 2, target_size: [800, 1333], keep_ratio: True}**

TestReader:
 **- Resize: {interp: 2, target_size: [800, 1333], keep_ratio: True}**

RPNHead:
  anchor_generator:
    aspect_ratios: [0.5, 1.0, 2.0]
    anchor_sizes: [[32], [64], [128], [256], [512]] 
    strides: [4, 8, 16, 32, 64]

**Comment by ghostxsl** [comment]
1. 两种尺寸都可以使用，效果以实验结果为准
2. 如果修改为200x200的尺寸，可以尝试将anchor等比列进行缩放
