### ISSUE TITLE
模型在验证集和测试集上的map精度相差过大

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleDetection#4209]
参加了飞桨的练习赛钢铁缺陷检测挑战赛，利用paddledet2.2中的faster_rcnn_r50_vd_fpn_2x_coco.yml配置文件进行训练，数据集尺寸为200x200，利用网络默认尺寸800x1300进行训练，在验证集上map可以达到0.38左右，但是提交到测试集以后，map只有0.04左右，这个精度差距过大？是不是哪儿有问题？？

infer命令
export CUDA_VISIBLE_DEVICES=1 
python tools/infer.py -c configs/defect/faster_rcnn_r50_vd_fpn_2x_coco.yml \
                    --infer_dir=dataset/defect/test/ \
                    --output_dir=defect_results/infer_output/ \
                    --draw_threshold=0.0001\
                    -o weights=output/faster_rcnn_r50_vd_fpn_2x_coco/best_model \
                    --save_txt=True

BBoxPostProcess:
  decode: RCNNBox
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.0001
    nms_threshold: 0.4

钢铁缺陷检测挑战赛
https://aistudio.baidu.com/aistudio/competition/detail/114

**Comment by ghostxsl** [comment]
建议您调一下参看看，或者验证一下代码是否正确

**Comment by wstchhwp** [comment]
> 建议您调一下参看看，或者验证一下代码是否正确

您好，你说的调参是这infer嘛?这块只有score置信度阈值和nms的iou阈值两个，我都试了不同组合，还是一样的问题。

**Comment by ghostxsl** [comment]
就目前看来，你这个问题不太好定位，但感觉大概率是代码的问题或者格式的问题，你可能还要自己再排查一下～
