### ISSUE TITLE
PPYOLO推理时需要的显存多大呢？

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleDetection#4215]
请问PPYOLO推理时需要的显存多大呢？有不同模型对应的显存大小吗？谢谢

**Comment by qingqing01** [comment]
文档上没有直接提供。和batch size、backbone大小也有关系。拿R50的backbone、bs=1，8G的显存应该够用。也可以实测下。

**Comment by kingbirdWc** [comment]
建议加上batchsize等于1时的显存占用，可用对模型有个更好的认识
![image](https://user-images.githubusercontent.com/23066646/134458116-9bf44019-6fce-49ab-b97b-f33713c8308e.png)

**Comment by qingqing01** [comment]
好的，多谢建议。
