### ISSUE TITLE
[Other General Issues]请问如何设置ppyolo的分辨率

### ISSUE THREAD

**Issue by gaooolianggg** [PaddlePaddle/PaddleDetection#4218]
在PPYOLO模型库中，有多种输入尺寸，并且每种尺寸的后边都附有模型和config的下载链接，请问这些不同分辨率的模型如何使用呢？我看config文件好像都是一样的，

**Comment by heavengate** [comment]
评估的尺寸在`EvalReader`里的`target_size`，预测和部署的时候用的是`TestReader`里的`target_size`
https://github.com/PaddlePaddle/PaddleDetection/blob/a5d46d3d19128ec3cb8931eeee7c41a1894c6223/configs/ppyolo/_base_/ppyolo_reader.yml#L29

**Comment by gaooolianggg** [comment]
@heavengate 谢谢。意思就是训练时不需要设置相关的分辨率参数是吗？那使用anchor_cluster时，设置的size指的也是这个size是吗

**Comment by heavengate** [comment]
训练的时候是RandomShape的，每个batch的shape随机
https://github.com/PaddlePaddle/PaddleDetection/blob/5b949596ea7603cd79e3fc9067766bbc79a3e93d/configs/ppyolo/_base_/ppyolo_reader.yml#L13

anchor_cluster是anchor的大小，不是图片的大小，是这里配置的
https://github.com/PaddlePaddle/PaddleDetection/blob/5b949596ea7603cd79e3fc9067766bbc79a3e93d/configs/ppyolo/_base_/ppyolo_reader.yml#L19
https://github.com/PaddlePaddle/PaddleDetection/blob/5b949596ea7603cd79e3fc9067766bbc79a3e93d/configs/ppyolo/_base_/ppyolo_r50vd_dcn.yml#L30

**Comment by clxia12** [comment]
请问这个anchor是在那个size下聚类出来的，谢谢

**Comment by izhaolinger** [comment]
> 训练的时候是RandomShape的，每个batch的shape随机
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/5b949596ea7603cd79e3fc9067766bbc79a3e93d/configs/ppyolo/_base_/ppyolo_reader.yml#L13
> 
> anchor_cluster是anchor的大小，不是图片的大小，是这里配置的
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/5b949596ea7603cd79e3fc9067766bbc79a3e93d/configs/ppyolo/_base_/ppyolo_reader.yml#L19
> 
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/5b949596ea7603cd79e3fc9067766bbc79a3e93d/configs/ppyolo/_base_/ppyolo_r50vd_dcn.yml#L30

您好，我在做小目标检测，目标比较小，图像分辨率也不高，我想将训练时RandomShape的target_size，请问调整幅度有讲究吗？多少合适？
