### ISSUE TITLE
用cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas.yml训练VOC格式数据集时出错

### ISSUE THREAD

**Issue by NeVermore2** [PaddlePaddle/PaddleDetection#422]
同一个数据集，我用yolov3、faster-rcnn配置文件进行训练都可以正常进行。但用cascade出现错误。我觉得应该是配置文件出现错误，因此想请教一下如何用cascade配置voc格式的数据集。
这是我的文件，修改了类别数量等相关信息。我是仿照faster-rcnn的voc配置进行了修改。
[cascade_myobj - 副本.txt](https://github.com/PaddlePaddle/PaddleDetection/files/4412499/cascade_myobj.-.txt)

错误原因是:
![image](https://user-images.githubusercontent.com/36319813/78094136-61f08580-7406-11ea-9bf9-5f31c0e6abd3.png)

谢谢！

**Comment by willthefrog** [comment]
voc数据集没有提供gt_poly字段，目前不支持训练带mask的模型。

**Comment by NeVermore2** [comment]
> voc数据集没有提供gt_poly字段，目前不支持训练带mask的模型。

那我就只能用coco格式训练带mask的模型了吧

**Comment by willthefrog** [comment]
是这样的，如果这个问题解决了的话麻烦close下issue，谢谢。
