### ISSUE TITLE
LabelImg标注出来的怎么转换COCO

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#4229]
LabelImg 标注出来的怎么转换 COCO

我比较喜欢用LabelImg 

但是 PaddleDetection 文档中没有写

我的 VOC结构：

dataset/xxx/
├── annotations
│ ├── xxx1.xml
│ ├── xxx2.xml
│ ├── xxx3.xml
│ | ...
├── images
│ ├── xxx1.jpg
│ ├── xxx2.jpg
│ ├── xxx3.jpg

------------------

官方的转换是这样的
 --voc_anno_list path/to/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt \
        --voc_label_list dataset/voc/label_list.txt \
我的数据集结构 没有这种的  
没有ImageSets trainval.txt label_list.txt

**Comment by Sencc** [comment]
网上的转换脚本很多

**Comment by jerrywgz** [comment]
可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/tools/x2coco.py 这个脚本

**Comment by qingqing01** [comment]
可以参考文档  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/docs/tutorials/PrepareDataSet.md#%E7%94%A8%E6%88%B7%E6%95%B0%E6%8D%AE%E8%BD%AC%E6%88%90coco%E6%95%B0%E6%8D%AE

**Comment by monkeycc** [comment]
我的 VOC结构：

dataset/xxx/
├── annotations
│ ├── xxx1.xml
│ ├── xxx2.xml
│ ├── xxx3.xml
│ | ...
├── images
│ ├── xxx1.jpg
│ ├── xxx2.jpg
│ ├── xxx3.jpg

只有 annotations 和 images 两个文件夹

官方的转换是这样的
--voc_anno_list path/to/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt
--voc_label_list dataset/voc/label_list.txt

我的数据集结构 没有这种的
没有ImageSets trainval.txt    label_list.txt

@jerrywgz  @qingqing01  @Sencc

**Comment by Sencc** [comment]
你这个是VOC数据结构，需要将labelme标注的数据集进行转换就行了 @monkeycc
