### ISSUE TITLE
tensorboard的优化建议

### ISSUE THREAD

**Issue by zimoqingfeng** [PaddlePaddle/PaddleDetection#423]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/tools/train.py#L240

如上所示，tb_writer记录的是“当前”iteration的loss值，我觉得改成当前log_iter的loss均值更好一些。也就是说，如果log_iter=20，那么tb_writer记录的应当是这20个iteration的loss均值。

如果我的表达有难理解的地方，还望及时反馈～

**Comment by willthefrog** [comment]
tensorboard本身具有smooth功能，目前的设置相当于隔`log_iter`采样一次，步数足够多时其实差别不大。

**Comment by zimoqingfeng** [comment]
嗯嗯 也没问题的，主要是我看到其他检测库的loss是按epc计算的，给你们提供一些参考哈。
