### ISSUE TITLE
[Other General Issues]Loss设计的问题

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#4231]
最近在进行TTFNet的相关工作，请问若是要在网络中新增一项loss函数，在ttf_head的get_loss函数中进行具体的实现后直接在返回的total_loss:{}中新增该loss的做法可行吗？因为我在阅读代码时发现在配置文件中包含了hm_loss和wh_loss的具体类型和权重定义，而在trainer.py中则在得到loss直接进行了反向传播。请问是否需要在配置文件中进行相应的修改？直接增加loss的方法是否可行？
![image](https://user-images.githubusercontent.com/59326436/134648923-3c33e02b-54d5-4d61-b247-0f466a1aa07d.png)

期待您的回复！

**Comment by yghstill** [comment]
@Xwmiss 可以直接在head中增加loss，loss会在arch中相加，训练时自动梯度更新https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/modeling/architectures/ttfnet.py#L88

**Comment by ghost** [comment]
> @Xwmiss 可以直接在head中增加loss，loss会在arch中相加，训练时自动梯度更新https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/modeling/architectures/ttfnet.py#L88

好的！此外config中的loss_weight也是在这一步中进行相应的加权吗？如果没有在congif设置相应的loss_weight应该是默认为1吧
