### ISSUE TITLE
[Other General Issues]

### ISSUE THREAD

**Issue by Kaitosama7** [PaddlePaddle/PaddleDetection#4235]
epoch: 270

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [45792,51516]
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
请问我使用的是这个参数训练自己的模型，但是在[216,243]轮次没有改变学习率是什么原因呢？max_iters是写在_base_下的模型文件开头处还是？

architecture: YOLOv3
norm_type: sync_bn
max_iters: 57240

YOLOv3:
  backbone: ResNet
  neck: YOLOv3FPN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess

**Comment by yghstill** [comment]
@Kaitosama7 是static下静态图模型还是根目录下动态图模型配置？动态图模型下只有设置epoch这个参数来控制训练轮数，static下才会使用max_iters

**Comment by Kaitosama7** [comment]
@yghstill 我是在configs中的模型配置，也就是说设置成[216,243]就可以了，那是不是说我要从216轮开始断点续训？还有就是学习率问题，请问我使用的是aistudio的至尊GPU环境，我看单卡的lr要设置成0.00125，我已经有使用0.001训练了216轮的模型了，需要重新训练吗还是 ？

**Comment by jerrywgz** [comment]
看起来是milestone设置的问题，可以从216轮开始继续训练
