### ISSUE TITLE
paddledetection c++部署问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleDetection#4236]
报错如下：
![5 $(JO(UKU{}X1)SCJYZ9A4](https://user-images.githubusercontent.com/61399616/134762883-c5eb84d0-aaa5-4100-b0b9-21215ecca563.png)

paddledetection版本：release2.1
paddle_inference版本：
![image](https://user-images.githubusercontent.com/61399616/134762951-c4afac29-394d-454e-8edd-85d5dcadfe77.png)

**Comment by yghstill** [comment]
@gxqnba 更新PaddleDetection版本到release 2.2，paddle_inference版本到v2.1再试下吧
