### ISSUE TITLE
jetson nano部署PaddleDetection运行ppyolo出错求助

### ISSUE THREAD

**Issue by bbilixzc** [PaddlePaddle/PaddleDetection#4237]
参考该文档在jetson nano上部署PaddleDecetion：[https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/cpp/docs/Jetson_build.md](url)

想要在jetson nano上跑ppyolo，但是报以下错误：
![ETNI NV9D@NDCX$CBJAMDYS](https://user-images.githubusercontent.com/40461420/134792079-740cb779-8846-4ff5-a89b-c6cccedee4cb.jpg)

ppyolo的模型是在AI studio上用Paddle Detection导出的：
![I769IH I42Y1MHHUL}Q%J@V](https://user-images.githubusercontent.com/40461420/134764309-1c4fb748-d5f4-4f77-9d07-3ec4c2b70d07.jpg)

想求助下有没有人也遇到这个问题了？该怎么解决呢？

**Comment by yghstill** [comment]
@zhujiaweiaaa 报错截图似乎给错了，麻烦更新下吧，同时更新代码到release 2.2再试下吧

**Comment by bbilixzc** [comment]
> @zhujiaweiaaa 报错截图似乎给错了，麻烦更新下吧，同时更新代码到release 2.2再试下吧

抱歉，报错截图已更新。
感谢回复，我会在release 2.2版本再试一下。

**Comment by bbilixzc** [comment]
使用PaddleDetection-release-2.2导出模型，以及在jetson nano上进行C++部署，成功运行ppyolo-tiny预测一张图片：
![ppyolo_tiny_cpu](https://user-images.githubusercontent.com/40461420/135192292-49b99e7f-9c28-40eb-91ee-a0d7fa86aa79.png)

但是预测视频时报错：
![ppyolo_tiny_video](https://user-images.githubusercontent.com/40461420/135192412-5b836d79-67f8-440b-bcc0-8e6cd1cc419c.png)

以及使用GPU时也出现问题：
![ppyolo_tiny_GPU](https://user-images.githubusercontent.com/40461420/135192492-716d8598-2a63-4082-a646-53b06a9cd206.png)
我在jtop上看GPU资源也没怎么调用啊

**Comment by wangxinxin08** [comment]
读取视频的问题已经解决了，你可以拉取最新代码试下哈
