### ISSUE TITLE
[BUG]c++部署后的预测问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleDetection#4238]
在windows上进行c++部署预测，已经设置draw阈值为0.8，但是得到的output图片上还是有很多置信度小于0.8的检测框
![image](https://user-images.githubusercontent.com/61399616/134765458-e434fe91-19db-45c0-922a-c703783ad128.png)
![image](https://user-images.githubusercontent.com/61399616/134765498-897f7adf-e4ba-48e9-bf27-f289407ee5f7.png)
![D5W9% RLWX@ %VJUABZCI 7](https://user-images.githubusercontent.com/61399616/134765531-4f577286-3bb6-4b3a-b6b7-904a038dcd73.png)

**Comment by yghstill** [comment]
@gxqnba 通过在命令行中 `--threshold`指定可视化阈值，不是draw_threshold
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/deploy/cpp/src/main.cc#L46
