### ISSUE TITLE
'not found any coco record in %s' %

### ISSUE THREAD

**Issue by DevilMay-Cry** [PaddlePaddle/PaddleDetection#4240]
![image](https://user-images.githubusercontent.com/63840313/134791861-2dc788d9-2073-44f2-b6b7-dd21a732baf5.png)
检查过coco_detection文件里边的路径了 没有问题  求助是什么原因造成的

**Comment by wangxinxin08** [comment]
这个报错是说train.json文件中没有没有标注，建议先检查一下标注文件

**Comment by DevilMay-Cry** [comment]
已解决

**Comment by laoda1112222** [comment]
> 已解决

你好，请问是如何解决的？

**Comment by aaaeric026** [comment]
> > 已解决
> 
> 你好，请问是如何解决的？

您好，请问您解决了吗
