### ISSUE TITLE
ppyolo_tiny是否支持RK3399PRO

### ISSUE THREAD

**Issue by wangerxiao719** [PaddlePaddle/PaddleDetection#4241]

**Comment by wangxinxin08** [comment]
ppyolo-tiny使用paddle-lite部署到移动端设备上，关于瑞芯微芯片目前的支持列表可以参考：https://paddlelite.paddlepaddle.org.cn/introduction/support_hardware.html#rockchip-npu, 目前暂不支持RK3399Pro

**Comment by wangerxiao719** [comment]
> ppyolo-tiny使用paddle-lite部署到移动端设备上，关于瑞芯微芯片目前的支持列表可以参考：https://paddlelite.paddlepaddle.org.cn/introduction/support_hardware.html#rockchip-npu, 目前暂不支持RK3399Pro

我将ppyolo_tiny模型转换成了onnx格式，但是不会调用onnx，请问有没有相关文档

**Comment by wangxinxin08** [comment]
直接使用onnx可以参考官方文档：https://github.com/onnx/onnx，将onnx转换成Paddle可以参考https://github.com/PaddlePaddle/X2Paddle
