### ISSUE TITLE
maskRcnn部署如何得到mask的结果

### ISSUE THREAD

**Issue by hymanzhu1983** [PaddlePaddle/PaddleDetection#4242]
版本：
paddle-serving-app                0.6.0          
paddle-serving-client             0.6.0          
paddle-serving-server-gpu         0.6.0.post11   
paddlepaddle-gpu                  2.1.2.post112
PaddleDetection  2.0

问题：
训练了一个模型，打算用serving方式部署，用infer.py验证能得到正确结果。然后用export_model.py导出模型，得到如下serving_server_conf.prototxt文件。
feed_var {
  name: "im_shape"
  alias_name: "im_shape"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
}
feed_var {
  name: "scale_factor"
  alias_name: "scale_factor"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
fetch_var {
  name: "save_infer_model/scale_0.tmp_1"
  alias_name: "save_infer_model/scale_0.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_1.tmp_1"
  alias_name: "save_infer_model/scale_1.tmp_1"
  is_lod_tensor: true
  fetch_type: 2
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_2.tmp_1"
  alias_name: "save_infer_model/scale_2.tmp_1"
  is_lod_tensor: true
  shape: -1
}
写了一个小例子测试这个导出的模型，发现
save_infer_model/scale_0.tmp_1 的shape是(5, 6)，这应该是np_boxes的结果
save_infer_model/scale_1.tmp_1 的shape是(1,)
save_infer_model/scale_2.tmp_1 的shape是(1, 800, 1248)，这个应该是包含mask的结果，但是感觉维度不对，应该是(5, 800, 1248)才对吧？
用的是mask_rcnn_x101_vd_64x4d_fpn_2x_coco.yml这个配置文件，请问这里是哪个步骤出了问题，如何才能得到每个box的mask结果？

**Comment by lyuwenyu** [comment]
可以可视化看一下 (1, 800, 1248) 这个
