### ISSUE TITLE
改进ppyolov2的实现细节

### ISSUE THREAD

**Issue by henryccl** [PaddlePaddle/PaddleDetection#4246]
如果我要改进ppyolov2的网络结构（或者数据增强等其他部分），我需要特别注意哪些文件的修改呢？似乎ppyolo的网络结构都写在config文件里并不太好 直接进行修改，有没有修改的案例呢？

对于改进， 有没有推荐的改进方向呢？

**Comment by nemonameless** [comment]
数据增强和网络结构的配置在[_base_](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.2/configs/ppyolo/_base_)里   ，
数据增强配置文件在 *_reader.yml里，reader修改参考 [FAQ](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/docs/tutorials/FAQ/FAQ%E7%AC%AC%E9%9B%B6%E6%9C%9F.md) 【Q: 如何更好的理解reader和自定义修改reader文件】, 改网络结构可以参看ppyolo_mbv3_large.yml，ppyolo_tiny.yml之类的。
各个数据增强或网络结构组件的定义代码，找到对应的class xxx或def xxx看下。修改的案例 ppyolo_tiny就是啊，或者你可以自行github上搜其他开发者的。
