### ISSUE TITLE
使用模型部署预测报错：use_dynamic_shape

### ISSUE THREAD

**Issue by DevilMay-Cry** [PaddlePaddle/PaddleDetection#4247]
![image](https://user-images.githubusercontent.com/63840313/135052491-0c559f5e-c4d9-48e9-9a8b-cd583c2d562c.png)
我是用一下命令预测图片时报错:
python deploy/python/infer.py  --model_dir=./inference_model/yolov3_darknet53_270e_coco  --image_dir=/root/workspace/input/test --output_dir=/root/workspace/out --device=GPU

**Comment by nemonameless** [comment]
请使用最新release/2.2分支或develop分支，拉取最新代码。以及说下运行命令方便我们复现问题帮你解决。

**Comment by DevilMay-Cry** [comment]
> 请使用最新release/2.2分支或develop分支，拉取最新代码。以及说下运行命令方便我们复现问题帮你解决。

导出模型命令：
python tools/export_model.py -c configs/yolov3/yolov3_darknet53_270e_coco.yml --output_dir=./inference_model \
 -o weights=./output/yolov3_darknet53_270e_coco/best_model.pdparams
模型部署命令：
python deploy/python/infer.py --model_dir=./inference_model/yolov3_darknet53_270e_coco --image_dir=/root/workspace/input/test --output_dir=/root/workspace/out --device=GPU

**Comment by wjplove8** [comment]
请问如何解决的？

**Comment by jerrywgz** [comment]
更新版本到2.2以上分支后，重新导出模型即可
