### ISSUE TITLE
PPYOLO训练参数

### ISSUE THREAD

**Issue by keepalook** [PaddlePaddle/PaddleDetection#4248]
请问ppyolo的训练参数应该如何设置呢？环境为aistudio中的至尊GPU，bs设置为30，学习率以及epoch应该为多少呢？

**Comment by nemonameless** [comment]
原lr是按卡数×每卡bs的bs总数来的，按这个标准bs总数和你现在的bs总数算比例，原lr除以这个比例即可。动态图训练以epoch方式计数，因此调整GPU卡数后只需要修改学习率即可，epoch数对于ppyolo已经足够长可不用修改，当然训更长一点epoch应该会比改了lr还训原来的epoch来的高。
