### ISSUE TITLE
图片预测结果 突然很多乱的标注

### ISSUE THREAD

**Issue by DevilMay-Cry** [PaddlePaddle/PaddleDetection#4249]
![59428e35-3c35-4b42-bd1a-e60789dd9981](https://user-images.githubusercontent.com/63840313/135077359-ec09d7f5-783b-4877-88fe-2d3853998433.jpg)
模型训练生成的权重文件之前还是好好的  今天突然识别结果就变成了这样了

**Comment by nemonameless** [comment]
环境变了还是代码变了，和昨天有哪些改变请描述详细一点。

**Comment by DevilMay-Cry** [comment]
代码变更了 导致的
