### ISSUE TITLE
Load symbol getPluginRegistry failed.

### ISSUE THREAD

**Issue by maichm** [PaddlePaddle/PaddleDetection#4253]
platform: win10
cuda: 10.2
cudnn: 7.6
tensorRT: 7.0

while compile done, run main.exe show the error！please help

You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0929 10:57:39.426221 15024 port.h:50] Load symbol getPluginRegistry failed.

**Comment by maichm** [comment]
My te

**Comment by lvpinrui** [comment]
你好，我也遇到了同样的问题请问一下你最后是怎么解决的
