### ISSUE TITLE
paddledection 使用余弦退火

### ISSUE THREAD

**Issue by xiaohui345** [PaddlePaddle/PaddleDetection#4258]
paddledection 使用余弦退火 

在paddledection中的配置文件中 修改对应的学习策略后，报错。

求助 有这方面的参考吗

**Comment by nemonameless** [comment]
请提供一下修改后的代码和报错信息。
另外也可以向 https://github.com/PaddlePaddle/PaddleClas   或   https://github.com/PaddlePaddle/Paddle 提issue。

**Comment by jerrywgz** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/lr/CosineAnnealingDecay_cn.html#cosineannealingdecay 可以参考这里的实现
