### ISSUE TITLE
自己训练的模型，再下次训练时，如何继续上次的模型继续训练？

### ISSUE THREAD

**Issue by DavidFangx** [PaddlePaddle/PaddleDetection#426]
1)自己训练的模型，再下次训练时，如何继续上次的模型继续训练？
2)从github上下载的模型，如何基于这个模型进行训练？

**Comment by willthefrog** [comment]
使用 `--resume=<path_to_model_file>` 命令行参数就可以了，注意需指定模型参数路径去掉后缀(即不带 `.pdmodel`的部分）

**Comment by qingqing01** [comment]
@DavidFangx 其他参数都可以查看文档: https://paddledetection.readthedocs.io/tutorials/GETTING_STARTED_cn.html#id3
