### ISSUE TITLE
[Other General Issues]请问在2.2版本中如何使用GIOU Loss CIOU Loss？

### ISSUE THREAD

**Issue by 17076372880** [PaddlePaddle/PaddleDetection#4265]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

**Comment by 17076372880** [comment]
![image](https://user-images.githubusercontent.com/41175199/135738959-997a6201-12e9-4c72-9e42-e0f082118035.png)
这么写是否正确

**Comment by 17076372880** [comment]
![image](https://user-images.githubusercontent.com/41175199/135739024-0c827638-adfe-4505-b0c2-7cfbc667a9cd.png)
还是要这么写，这么写后会报错，错误如下：
![image](https://user-images.githubusercontent.com/41175199/135739053-2b927694-a7fb-48f7-991e-953590b534f7.png)

**Comment by nemonameless** [comment]
> ![image](https://user-images.githubusercontent.com/41175199/135738959-997a6201-12e9-4c72-9e42-e0f082118035.png) 这么写是否正确

这种写法用在YOLOv3Loss这里是对的，iou系列loss的函数接口的输入输出保证一致即可。
