### ISSUE TITLE
S2ANet模型预测问题

### ISSUE THREAD

**Issue by wenjiett** [PaddlePaddle/PaddleDetection#4266]
我在使用S2ANet模型进行预测时遇到了下面的一个问题：
        当我使用tools/infer.py脚本进行预测时，可视化结果都比较准确，但是当我导出模型用deploy/python/infer.py脚本进行预测时，就什么都没有识别到。后来我用paddleInference进行推理预测，结果也没有用tools/infer.py脚本预测的结果好，请问这是什么原因呢？我在官方文档里看到用tools/infer.py预测时会生成一个txt文件包含一些坐标信息，格式是image_id score x1 y1 x2 y2 x3 y3 x4 y4。我用PaddleInference预测得到了下面的结果[0.0000000e+00 ，7.0659733e-01， 3.5534906e+02 ，6.8808685e+02 ，4.8217526e+02， 7.4520026e+02 ，4.8186716e+02， 7.4588446e+02 ，3.5504095e+02 ，6.8877106e+02]，请问是否也是那种格式呢？但是按那种格式测试时画出来的框都变成线了。

**Comment by wenjiett** [comment]
用deploy/python/infer.py脚本预测的结果是：{'boxes': array([[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32), 'boxes_num': array([1], dtype=int32)}

**Comment by wangxinxin08** [comment]
感谢你的反馈，目前deploy/python/infer.py的结果确实存在一些问题，我们之后排期修复一下

**Comment by wenjiett** [comment]
> 感谢你的反馈，目前deploy/python/infer.py的结果确实存在一些问题，我们之后排期修复一下

用原生paddleInference推理得到的结果也是image_id score x1 y1 x2 y2 x3 y3 x4 y4这种格式吗，如果按这种格式虽然有四个点，但(x1,y1) 与 (x4,y4)，(x2,y2) 与 (x3,y3)都挨得很近，不知道这个推理结果是不是正确的

**Comment by wangxinxin08** [comment]
> > 感谢你的反馈，目前deploy/python/infer.py的结果确实存在一些问题，我们之后排期修复一下
> 
> 用原生paddleInference推理得到的结果也是image_id score x1 y1 x2 y2 x3 y3 x4 y4这种格式吗，如果按这种格式虽然有四个点，但(x1,y1) 与 (x4,y4)，(x2,y2) 与 (x3,y3)都挨得很近，不知道这个推理结果是不是正确的

使用deploy/python/infer.py的推理结果的格式也是image_id score x1 y1 x2 y2 x3 y3 x4 y4，不过deploy/python/infer.py的结果母测有点问题，后续会debug修复

**Comment by wangxinxin08** [comment]
s2anet模型预测问题已修复，可以拉取PaddleDetection 2.3.0重新导出测试
