### ISSUE TITLE
reader 报错

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#4269]
您好，可否帮忙看一下，下图的报错如何解决
![image](https://user-images.githubusercontent.com/68497831/136334450-b4a2c375-50e1-494f-b78e-79e9fe2a8932.png)

**Comment by ghostxsl** [comment]
看错误信息是调用默认的collate_fn时报错的，你可以检查一下自己的输入的shape是否一致，或者可以在配置里设置reader的collate_fn=False
