### ISSUE TITLE
训练coco形式的数据集出错

### ISSUE THREAD

**Issue by NeVermore2** [PaddlePaddle/PaddleDetection#427]
weights: output/cascade_rcnn_cls_aware_r101_vd_fpn_1x_softnms/model_final

W0401 21:42:07.599655 307517 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.0, Runtime API Version: 10.0
W0401 21:42:07.607129 307517 device_context.cc:245] device: 0, cuDNN Version: 7.6.
2020-04-01 21:42:10,792-INFO: Found /home/renpeng2/.cache/paddle/weights/ResNet101_vd_pretrained
2020-04-01 21:42:10,793-INFO: Loading parameters from /home/renpeng2/.cache/paddle/weights/ResNet101_vd_pretrained...
2020-04-01 21:42:10,793-WARNING: /home/renpeng2/.cache/paddle/weights/ResNet101_vd_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-04-01 21:42:10,793-WARNING: /home/renpeng2/.cache/paddle/weights/ResNet101_vd_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-04-01 21:42:10,808-WARNING: variable file [ /home/renpeng2/.cache/paddle/weights/ResNet101_vd_pretrained/fc_0.b_0 /home/renpeng2/.cache/paddle/weights/ResNet101_vd_pretrained/fc_0.w_0 ] not used
2020-04-01 21:42:10,808-WARNING: variable file [ /home/renpeng2/.cache/paddle/weights/ResNet101_vd_pretrained/fc_0.b_0 /home/renpeng2/.cache/paddle/weights/ResNet101_vd_pretrained/fc_0.w_0 ] not used
W0401 21:42:12.378114 307517 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0401 21:42:12.378155 307517 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0401 21:42:12.378165 307517 init.cc:214] The detail failure signal is:

W0401 21:42:12.378175 307517 init.cc:217] *** Aborted at 1585748532 (unix time) try "date -d @1585748532" if you are using GNU date ***
W0401 21:42:12.391445 307517 init.cc:217] PC: @                0x0 (unknown)
W0401 21:42:12.391806 307517 init.cc:217] *** SIGSEGV (@0x0) received by PID 307517 (TID 0x7f424a910740) from PID 0; stack trace: ***
W0401 21:42:12.400959 307517 init.cc:217]     @     0x7f424a518370 (unknown)
W0401 21:42:12.406363 307517 init.cc:217]     @     0x7f424aa3c210 (unknown)
W0401 21:42:12.407595 307517 init.cc:217]     @     0x7f41d18790cf (unknown)
W0401 21:42:12.408649 307517 init.cc:217]     @     0x7f41d1879935 (unknown)
W0401 21:42:12.410121 307517 init.cc:217]     @     0x7f41d1542cdd qpycore_init()
W0401 21:42:12.411516 307517 init.cc:217]     @     0x7f41d1519bfc PyInit_QtCore
W0401 21:42:12.416157 307517 init.cc:217]     @     0x7f424ab5dbd5 _PyImport_LoadDynamicModuleWithSpec
W0401 21:42:12.420771 307517 init.cc:217]     @     0x7f424ab5dde0 _imp_create_dynamic
W0401 21:42:12.425595 307517 init.cc:217]     @     0x7f424aa5c491 PyCFunction_Call
W0401 21:42:12.430522 307517 init.cc:217]     @     0x7f424ab0879a _PyEval_EvalFrameDefault
W0401 21:42:12.436998 307517 init.cc:217]     @     0x7f424aada274 _PyEval_EvalCodeWithName
W0401 21:42:12.439369 307517 init.cc:217]     @     0x7f424aadb0f1 fast_function
W0401 21:42:12.441447 307517 init.cc:217]     @     0x7f424aae0e85 call_function
W0401 21:42:12.443593 307517 init.cc:217]     @     0x7f424ab0366a _PyEval_EvalFrameDefault
W0401 21:42:12.445735 307517 init.cc:217]     @     0x7f424aadaebb fast_function
W0401 21:42:12.448613 307517 init.cc:217]     @     0x7f424aae0e85 call_function
W0401 21:42:12.450964 307517 init.cc:217]     @     0x7f424ab0366a _PyEval_EvalFrameDefault
W0401 21:42:12.457075 307517 init.cc:217]     @     0x7f424aadaebb fast_function
W0401 21:42:12.467550 307517 init.cc:217]     @     0x7f424aae0e85 call_function
W0401 21:42:12.471834 307517 init.cc:217]     @     0x7f424ab0366a _PyEval_EvalFrameDefault
W0401 21:42:12.477816 307517 init.cc:217]     @     0x7f424aadaebb fast_function
W0401 21:42:12.482522 307517 init.cc:217]     @     0x7f424aae0e85 call_function
W0401 21:42:12.487242 307517 init.cc:217]     @     0x7f424ab0366a _PyEval_EvalFrameDefault
W0401 21:42:12.491904 307517 init.cc:217]     @     0x7f424aadaebb fast_function
W0401 21:42:12.496546 307517 init.cc:217]     @     0x7f424aae0e85 call_function
W0401 21:42:12.501317 307517 init.cc:217]     @     0x7f424ab0366a _PyEval_EvalFrameDefault
W0401 21:42:12.505717 307517 init.cc:217]     @     0x7f424aadb52b _PyFunction_FastCallDict
W0401 21:42:12.510494 307517 init.cc:217]     @     0x7f424aa598bf _PyObject_FastCallDict
W0401 21:42:12.513447 307517 init.cc:217]     @     0x7f424aa9aff0 _PyObject_CallMethodIdObjArgs
W0401 21:42:12.517895 307517 init.cc:217]     @     0x7f424aa507d0 PyImport_ImportModuleLevelObject
W0401 21:42:12.522372 307517 init.cc:217]     @     0x7f424aaeb75a builtin___import__
W0401 21:42:12.527271 307517 init.cc:217]     @     0x7f424aa5c426 PyCFunction_Call

根据要求，把自己的数据集配置成了coco格式，但出现如上错误。配置文件用的默认文件（coco数据形式）。
coco的json格式如下文件。。。求解答啊
[train.txt](https://github.com/PaddlePaddle/PaddleDetection/files/4415504/train.txt)

[train.txt](https://github.com/PaddlePaddle/PaddleDetection/files/4415504/train.txt)

**Comment by willthefrog** [comment]
能否提供个详细配置？图片文件和json文件放在一起的？ `image_dir`和`anno_path`设置是对应的么？

**Comment by NeVermore2** [comment]
> 能否提供一个详细配置？图片文件和json文件放在一起的？`image_dir`和`anno_path`设置是对应的么？

是放在一起的，路径也对。但是，json文件里有空目标，即xmin=xmax。
之前voc格式也会出现相应错误，删除了有空目标的xml文件后，能够正常训练。
此coco格式的数据，没有删除空目标。但显示的错误与之前voc显示的错误不一样。

**Comment by willthefrog** [comment]
这种情况最好还是过滤下吧，目前coco的解析好像没有过滤这种情况，不确定是否会造成后面的步骤出错。参见[这里](https://github.com/paddlepaddle/PaddleDetection/blob/master/ppdet/data/source/coco.py#L111)。

另外，这种情况感觉应该默认过滤掉啊  @qingqing01

**Comment by learning-boy** [comment]
我也出现了同样的问题，请问怎么解决的，什么是过滤

**Comment by willthefrog** [comment]
把不合法的bboxes （w或者h <=0) 和对应的class丢弃掉。

**Comment by qingqing01** [comment]
最新版已增强。
