### ISSUE TITLE
[BUG]AIStudio中使用新版BMLCodelab转换数据集时，生成json文件名错误

### ISSUE THREAD

**Issue by gaooolianggg** [PaddlePaddle/PaddleDetection#4271]
我在AIStudio中使用BML CodeLab模式的项目。当我运行PaddleDetection转换数据集格式时，生成的json文件的文件名附带了一个换行符，这个给我后续的处理带来了一些麻烦。
  我觉得这个问题应该是CodeLab模式的问题，因为我之前在终端中运行转换格式的语句时没有这个问题，但我不清楚AIStudio的问题在哪里反馈，所以希望PaddleDetection官方可以帮助我反馈这个情况。
  我已经把有问题的项目公开了，下面是项目的链接，谢谢
https://aistudio.baidu.com/aistudio/projectdetail/2445401?contributionType=1&shared=1

**Comment by qingqing01** [comment]
您是指这里的mv命令后的“\r\n”嘛？您修改下mv命令这行呢？

<img width="656" alt="图片" src="https://user-images.githubusercontent.com/7845005/136487470-314387c5-6b6f-4266-be4e-fb10e3c68786.png">
