### ISSUE TITLE
cascade导出模型报错

### ISSUE THREAD

**Issue by felixhjh** [PaddlePaddle/PaddleDetection#4274]
![690add3cb8bd9c6d5880d3db223f8530](https://user-images.githubusercontent.com/16222477/136548714-0f83c820-8cb4-4a9e-a520-fd8a7ef90855.jpg)
这是从model zoo下载的yml文件 导出模型的时候报错了
![a1302dc6816738bbe86179ead39390b0](https://user-images.githubusercontent.com/16222477/136548765-2748c566-be36-4b68-8596-45819242e8e0.jpg)
这个是detection 2.2 config下的模型yml文件并没有什么问题

**Comment by qingqing01** [comment]
您有做什么修改嘛？ 我是用PaddleDetection 2.2 , 导出模型命令如下:

```
 python tools/export_model.py -c configs/cascade_rcnn/cascade_mask_rcnn_r50_vd_fpn_ssld_2x_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/cascade_mask_rcnn_r50_vd_fpn_ssld_2x_coco.pdparams
```

可以导出成功:

```
W1009 02:35:50.182348  8511 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 10.2
W1009 02:35:50.182395  8511 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[10/09 02:35:57] ppdet.engine INFO: Export model and saved in output_inference/cascade_mask_rcnn_r50_vd_fpn_ssld_2x_coco
```

`ls output_inference/cascade_mask_rcnn_r50_vd_fpn_ssld_2x_coco/`

```
infer_cfg.yml  model.pdiparams  model.pdiparams.info  model.pdmodel
```

另外请注意准确描述issue标题 :)

**Comment by felixhjh** [comment]
您好，下次注意标题哈哈哈，我的cascade_rcnn yml文件是从这个网址下载的https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/cascade_rcnn  不是用configs/cascade下面的yml文件，导出的时候就会出现第一个报错，用configs下面的文件就没问题

**Comment by qingqing01** [comment]
我切换到develop分支是可以的。请注意相互配套。 yml里有嵌套使用_base_文件里yml，下载时需要下载全套。

**Comment by felixhjh** [comment]
明白了，谢谢麻烦了~
