### ISSUE TITLE
COCO评估精度输出问题

### ISSUE THREAD

**Issue by lixinlelexinli** [PaddlePaddle/PaddleDetection#4275]
请问COCO进行评估的时候怎么输出指定的mAP结果吗？比如只输出0.5mAP，如何在visualdl中显示0.5mAP的变化曲线而不是0.5：0.95的曲线？

**Comment by qingqing01** [comment]
需要改下代码，COCO的评估指标采用COCO API计算的结果，COCO API中stats数组中第1个(从0计数)是mAP@0.5的值，

https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/cocoeval.py#L461

因此: 将下面代码中 `map_value[0]` 改成  `map_value[1]`

https://github.com/PaddlePaddle/PaddleDetection/blob/5b949596ea7603cd79e3fc9067766bbc79a3e93d/ppdet/engine/callbacks.py#L256
