### ISSUE TITLE
Only one epoch is run by train.py

### ISSUE THREAD

**Issue by zhyang28tx** [PaddlePaddle/PaddleDetection#4278]
1). Set epoch to 300 in the config file, 
2). python tools/train.py -c configs/keypoint/higherhrnet/higherhrnet_hrnet_w32_512.yml

But only one epoch was run and the model weight was not saved.

**Comment by heavengate** [comment]
你用的Paddle和PaddleDetection是哪个版本，操作系统是windows么

**Comment by zhyang28tx** [comment]
Paddle: 2.1.3
PaddleDetection: 2.2
OS: Windows 10

**Comment by SchrodingerLLX** [comment]
同问，在data = self._reader.read_next_var_list()这里报错跳出
Paddle: 2.1.3
PaddleDetection: 2.2
OS: Windows 10

**Comment by lyf6** [comment]
@heavengate @SchrodingerLLX 请问你们的问题解决了吗，我在paddleseg下遇到相同的问题

**Comment by SchrodingerLLX** [comment]
@lyf6 [lyf6](https://github.com/lyf6)
> @heavengate @SchrodingerLLX 请问你们的问题解决了吗，我在paddleseg下遇到相同的问题
当时的版本下没有解决，改为使用PaddleDetection: 2.1了，目前最新的PaddleDetection没试过
