### ISSUE TITLE
训练voc数据出现gt_ploy错误

### ISSUE THREAD

**Issue by NeVermore2** [PaddlePaddle/PaddleDetection#428]
![image](https://user-images.githubusercontent.com/36319813/78159979-e4fcf480-7475-11ea-8845-de2a05fa79e3.png)
错误如图所示。
该数据集yolo配置可以正常训练使用。
我该如何改正呢？

**Comment by NeVermore2** [comment]
同样的配置，用casasde rcnn可以成功训练，只有mask不可以

**Comment by willthefrog** [comment]
voc数据集没有提供gt_poly字段，目前不支持训练mask。
