### ISSUE TITLE
[BUG]使用多卡训练模型，--eval 边训练，边评估，runtime里的snapshot_epoch: 1，但每5个epoch才评估一次

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleDetection#4283]
## 描述问题/Describe the bug
使用多卡训练模型，--eval 边训练，边评估，runtime里的snapshot_epoch: 1，但每5个epoch才评估一次

## 复现/Reproduction

https://aistudio.baidu.com/aistudio/clusterprojectdetail/2456042

1. 您使用的命令是？/What command or script did you run?
启动命令
`os.system("cd PaddleDetection-release-2.2 && python -m paddle.distributed.launch  tools/train.py -c configs/yolov3/yolov3_mobilenet_v3_large_270e_voc.yml --eval --use_vdl=True --vdl_log_dir='./output_vdl'")`
```none
2.runtime.yml文件

```
use_gpu: true
log_iter: 1
save_dir: output
snapshot_epoch: 1
print_flops: true
```

**Comment by nemonameless** [comment]
configs/yolov3/yolov3_mobilenet_v3_large_270e_voc.yml  这里写了snapshot_epoch: 5覆盖了
