### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Unknown-parameters** [PaddlePaddle/PaddleDetection#4284]
## 🚀  新功能/Feature

PaddleDetection欢迎大家以清晰简洁的语言提出新功能需求。

A clear and concise description of the feature proposal.
s2anet 模型转onnx格式
## 需求原因&示例/Motivation & Examples

请描述这个需求的必要性。

Tell us why the feature is useful.
更广的应用场景
请描述这个需求可实现的具体功能，如果可以，辛苦您提供相关代码实现效果。

Describe what the feature would look like, if it is implemented.
Best demonstrated using **code examples** in addition to words.

## 📣 注意/Note

PaddleDetection仅添加通用性较高的新功能/特性。

We only consider adding new features if they are relevant to many users.

如果您需要论文中的模型能力，PaddleDetection会优先考虑与目标检测强相关且意义较大的论文。

If you request implementation of research papers -- we only consider papers that have enough significance and prevalence in the object detection field.

比如“让XX功能更快”类似的需求不能作为一个有效需求，需要更具体的描述，如“创建一个具体XX工具/功能，让XX更快”即是一个有效需求。

"Make X faster/accurate" is not a valid feature request. "Implement a concrete feature that can make X faster/accurate" can be a valid feature request.

PaddleDetection感谢您的支持，我们期待您提出新功能需求！

Thanks for your suggestions!

**Comment by qingqing01** [comment]
closed since duplicated with https://github.com/PaddlePaddle/PaddleDetection/issues/4289
