### ISSUE TITLE
[BUG] jetson nano使用PaddleDetection C++部署，运行ppyolo无法预测视频的问题

### ISSUE THREAD

**Issue by bbilixzc** [PaddlePaddle/PaddleDetection#4285]
参考以下文档想要在jetson nano平台上运行ppyolo：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/deploy/cpp/docs/Jetson_build.md

使用PaddleDetection-release-2.2导出模型，以及在jetson nano上进行C++部署，运行ppyolo-tiny预测一张图片是可以的：
![ppyolo_tiny_image](https://user-images.githubusercontent.com/40461420/136721981-40b566cc-101c-48c9-bcd2-36ef6ed105c4.png)

但是预测视频时会报错：
![ppyolo_tiny_video](https://user-images.githubusercontent.com/40461420/136722004-6f519aef-2231-4094-90b8-8f255ad1d8d2.png)

想要用GPU进行推理也会报错：
![ppyolo_tiny_gpu](https://user-images.githubusercontent.com/40461420/136722041-5b59f6c9-59f5-4dcc-a081-ffedb52a7adc.png)

**Comment by wangxinxin08** [comment]
1. 视频报错的原因应该是opencv读取的问题，可以参考我们修复的PR:https://github.com/PaddlePaddle/PaddleDetection/pull/4296/files 进行修改
2. GPU推理报错是显存溢出，可以先检查下板子上是不是有其他的程序在占用显存

**Comment by bbilixzc** [comment]
> 1. 视频报错的原因应该是opencv读取的问题，可以参考我们修复的PR:https://github.com/PaddlePaddle/PaddleDetection/pull/4296/files 进行修改
> 2. GPU推理报错是显存溢出，可以先检查下板子上是不是有其他的程序在占用显存

感谢回复。
但是我的需求是在英伟达jetson平台上进行部署，所以编译脚本中下载opencv的部分是红框部分：
![1634209862(1)](https://user-images.githubusercontent.com/40461420/137308226-c3114dff-4c5e-4265-a0d3-2a7efb2f79fc.png)
您给的参考修复的是编译脚本中针对X86平台下载opencv的部分：
![1634210645(1)](https://user-images.githubusercontent.com/40461420/137308428-584df070-b157-4fbb-9b1a-ce661f077df4.png)
如果可以的话请麻烦再看一下这个问题。
谢谢！

**Comment by wangxinxin08** [comment]
你好，现在已经修复了，请拉去一下最新代码试下
