### ISSUE TITLE
paddle_detection使用TensorRT加速时报错

### ISSUE THREAD

**Issue by 606BlueStar** [PaddlePaddle/PaddleDetection#429]
Error: Pass tensorrt_subgraph_pass has not been registered at (/paddle/paddle/fluid/framework/ir/pass.h:170)

安装了TensorRT 6
并且在tensorflow上可以加速使用

**Comment by FDInSky** [comment]
你安装的是带Tensor-RT编译的预测库吗？可以先参考下这个文档
https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/inference_improving/paddle_tensorrt_infer.html#paddle-tensorrt

**Comment by 606BlueStar** [comment]
好的，谢谢！linux预测库里看到只有ubuntu14的版本，目前不支持18吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "FDInSky"<notifications@github.com&gt;; 
发送时间: 2020年4月2日(星期四) 下午2:11
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 
抄送: "开始"<1781843589@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] paddle_detection使用TensorRT加速时报错 (#429)





 
你安装的是带Tensor-RT编译的预测库吗？可以先参考下这个文档
 https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/inference_improving/paddle_tensorrt_infer.html#paddle-tensorrt

**Comment by qingqing01** [comment]
ubuntu18是支持的
