### ISSUE TITLE
[Other General Issues] 训练好的ppyolo模型  如何追加目标追踪功能

### ISSUE THREAD

**Issue by yqsoooo** [PaddlePaddle/PaddleDetection#4295]
最近在调研paddleDetection 目标追踪检测。
我目前已经使用ppyolo2/yolov3  训练出业务需要的目标检测模型（检测夜晚路灯不亮）。
需求需要在视频中识别出主体追踪情况。

看了下相关的文档，目前了解到有两种途径，
1：deepsort  （无需重新训练 仅针对目标检测结果txt 识别，个人理解：分离检测）
2：jde/failmot  （重新按照mot相关要求标注  重新训练，个人理解：一体检测）

但是我目前还没清楚我的场景如何进行目标追踪预测。
选择deepsort疑问： 如何将我的检测结果方便的输出成 mot格式txt
选择 jde/failmot疑问：重新按照Mot标注训练，成本是不是太高了。不太现实。
关于mot的疑问，看到官方提供了数据集image_lists，Caltech，Cityscapes等等，难道是追踪这些标准训练集更方便(人，车，猫狗等垂类训练集)。 本身想追踪特殊的场景物体就比较费事？

**Comment by nemonameless** [comment]
想追踪特殊的场景物体，且在没有gt id标注的情况下，推荐使用 deepsort，可以用任意检测模型来训纯检测任务，然后拿到检测结果去过deepsort，后期优化就专注优化检测器即可且方便加数据。deepsort支持两种模式，一种加载检测结果，一种加载检测模型，本质上是一样的，deepsort的输出就是mot格式。
https://github.com/PaddlePaddle/PaddleDetection/pull/4277  通用的yolov3或其他检测器+deepsort使用可参照此PR，近期会合入。

**Comment by yqsoooo** [comment]
> 想追踪特殊的场景物体，且在没有gt id标注的情况下，推荐使用 deepsort，可以用任意检测模型来训纯检测任务，然后拿到检测结果去过deepsort，后期优化就专注优化检测器即可且方便加数据。deepsort支持两种模式，一种加载检测结果，一种加载检测模型，本质上是一样的，deepsort的输出就是mot格式。 #4277 通用的yolov3或其他检测器+deepsort使用可参照此PR，近期会合入。

我使用deepsort第二种方式同时加载了检测模型和rid模型，但是报错了。
det_weight 应该对应的是训练生成的权重文件 还是导出的export,inference_model文件夹。

 #4277 通用的yolov3或其他检测器+deepsort使用可参照此PR，近期会合入。
这个指的是目前还不支持 检测器+deepsort的组合吗 ？必须先用第一种det_result的方式？det_result的文件  是自己用python去拼结果集吗？


我目前使用的是detection2.1训练出的模型。我看到detection2.2 deploy/infer.py 可以预测出--save_mot_txts。不知道是不是就是上面提到的det_result。

我使用2.1训练的模型去2.2  deploy/infer.py  
报错KeyError: 'use_dynamic_shape'  在2.1中预测无问题


![image](https://user-images.githubusercontent.com/15975613/137057343-44ee3f33-260f-46e0-a64b-de6b8c3339d9.png)
![image](https://user-images.githubusercontent.com/15975613/137057414-d948f95d-eded-45a2-a5f7-9c01f73aac86.png)

**Comment by nemonameless** [comment]
det_weight 是训练生成的权重文件。导出的模型也支持，看readme里的例子语句
```
python deploy/python/mot_sde_infer.py --model_dir=output_inference/pedestrian_yolov3_darknet/ --reid_model_dir=output_inference/deepsort_pcb_pyramid_r101/ --video_file={your video name}.mp4 --device=GPU --scaled=True --save_mot_txts
```
output_inference/pedestrian_yolov3_darknet/  里放的就是导出的模型。
#4277 已经给了yolov3的例子，其他检测器也同理配置即可，之后会开放faster rcnn的检测+deepsort，就是deepsort config里yolov3换成faster rcnn或ppyolo的配置，把原版faster rcnn检测的config搬过来即可。参照 configs/mot/deepsort/_base_/deepsort_yolov3_darknet53_pcb_pyramid_r101.yml 
```
DeepSORT:
  detector: FasterRCNN #YOLOv3 
  reid: PCBPyramid
  tracker: DeepSORTTracker

FasterRCNN:
  backbone: ResNet
  neck: FPN
  rpn_head: RPNHead
  bbox_head: BBoxHead
  # post process
  bbox_post_process: BBoxPostProcess
.........
```
det_result的文件请自行根据检测器输出的结果json或其他形式的结果 用python去处理拼接，注意格式，是有点麻烦但确有场景只给检测框结果不给检测模型而去做跟踪。
deploy/infer/deploy/python/mot_sde_infer.py和tools/infer_mot.py 预测出的结果就已经是最终的跟踪结果了，det_result的文件就是纯检测结果，没有带id号的，如果你确定要用这种加载结果的方式 请自行准备det_result。
你图中的报错，有跟着改动deepsort_yolov3_darknet53_pcb_pyramid_r101.yml 里的配置吗？不然就是用的yolov3的配置去加载ppyolo模型权重就会权重不匹配。得把PPYOLO的模型配置config部分替换掉deepsort_yolov3_darknet53_pcb_pyramid_r101里的Yolov3
请再仔细阅读文档 configs/mot/deepsort/README_cn.md，所有文档和代码建议请直接使用2.2分支或develop分支

**Comment by yqsoooo** [comment]
首先感谢您耐心的回复 这确实使我有新的进展。
目前我在复制ppyolov2_r50vd_dcn.yml的配置到mot/_base_/ppyolov2_r50vd_dcn.yml 时  遇到了一些预测报错。
我觉得对于新手来说根据read_me配置成功确实挺难的。
![image](https://user-images.githubusercontent.com/15975613/137294410-1cb51bd8-89e0-42e7-ba59-c06c37dfda60.png)


配置文件如下：
**cat configs/mot/deepsort/deepsort_yolov3_pcb_pyramid_r101.yml**                                                                  
_BASE_: [
  '../../datasets/mot.yml',
  '../../runtime.yml',
  '_base_/ppyolov2_r50vd_dcn.yml',
  '_base_/deepsort_reader_1088x608.yml',
]

EvalMOTDataset:
  !MOTImageFolder
    dataset_dir: dataset/mot
    data_root: MOT16/images/train
    keep_ori_im: True # set as True in DeepSORT

det_weights: output/ppyolov2_r50vd_dcn_voc/best_model
reid_weights: https://paddledet.bj.bcebos.com/models/mot/deepsort_pcb_pyramid_r101.pdparams

DeepSORT:
  detector: YOLOv3
  reid: PCBPyramid
  tracker: DeepSORTTracker

YOLOv3:
  backbone: ResNet
  neck: PPYOLOPAN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess



---------------
**cat configs/mot/deepsort/_base_/ppyolov2_r50vd_dcn.yml** 

architecture: DeepSORT
pretrain_weights: None

DeepSORT:
  detector: YOLOv3 # JDE version
  reid: PCBPyramid
  tracker: DeepSORTTracker


YOLOv3:
  backbone: ResNet
  neck: PPYOLOPAN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess

ResNet:
  depth: 50
  variant: d
  return_idx: [1, 2, 3]
  dcn_v2_stages: [3]
  freeze_at: -1
  freeze_norm: false
  norm_decay: 0.

PPYOLOPAN:
  drop_block: true
  block_size: 3
  keep_prob: 0.9
  spp: true

YOLOv3Head:
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  loss: YOLOv3Loss
  iou_aware: true
  iou_aware_factor: 0.5

YOLOv3Loss:
  ignore_thresh: 0.7
  downsample: [32, 16, 8]
  label_smooth: false
  scale_x_y: 1.05
  iou_loss: IouLoss
  iou_aware_loss: IouAwareLoss

IouLoss:
  loss_weight: 2.5
  loss_square: true

IouAwareLoss:
  loss_weight: 1.0

BBoxPostProcess:
  decode:
    name: YOLOBox
    conf_thresh: 0.01
    downsample_ratio: 32
    clip_bbox: true
    scale_x_y: 1.05
  nms:
    name: MatrixNMS
    keep_top_k: 100
    score_threshold: 0.01
    post_threshold: 0.01
    nms_top_k: -1
    background_label: -1

PCBPyramid:
  num_conv_out_channels: 128
  num_classes: 751

DeepSORTTracker:
  budget: 100
  max_age: 70
  n_init: 3
  metric_type: cosine
  matching_threshold: 0.2
  max_iou_distance: 0.9
  motion: KalmanFilter

**Comment by yqsoooo** [comment]
上面问题描述的主要是  ppyolo 配置mot/base/ 时候 估计出了一些问题。
为了快速验证技术路线，我重新训练了yolov3 darknet53的模型，直接修改
configs/mot/deepsort/deepsort_yolov3_pcb_pyramid_r101.yml 
det_weights: /home/work/workspace/PaddleDetection2.2/output/yolov3_darknet53_270e_voc/best_model

**其余配置包括_base_内容全部保持原样未改动**

但是预测追踪特别慢， 我看了下Output中的图片  感觉是识别的种类和个数都有问题， 不知道是哪里出了问题。
![image](https://user-images.githubusercontent.com/15975613/137307384-d3fd1ae5-4862-4d2c-963e-5aad49226b09.png)

![image](https://user-images.githubusercontent.com/15975613/137307264-376c5c71-caaa-4dc5-8f75-3b35136cdb2d.png)

**Comment by nemonameless** [comment]
过几天会更新ppyolo picodet和faster rcnn的对应配置和模型

**Comment by yqsoooo** [comment]
> 过几天会更新ppyolo picodet和faster rcnn的对应配置和模型

好的

我尝试了下2.2和devlop 按照官方read_me中的步骤默认det+reid权重导出后预测视频 还是满屏框 是还需要配置一些class_num之类吗？没见到相关文档

det_weght=https://paddledet.bj.bcebos.com/models/mot/jde_yolov3_darknet53_30e_1088x608.pdparams
reid_weights=https://paddledet.bj.bcebos.com/models/mot/deepsort_pcb_pyramid_r101.pdparams

**Comment by nemonameless** [comment]
> > 过几天会更新ppyolo picodet和faster rcnn的对应配置和模型
> 
> 好的
> 
> 我尝试了下2.2和devlop 按照官方read_me中的步骤默认det+reid权重导出后预测视频 还是满屏框 是还需要配置一些class_num之类吗？没见到相关文档
> 
> det_weght=https://paddledet.bj.bcebos.com/models/mot/jde_yolov3_darknet53_30e_1088x608.pdparams reid_weights=https://paddledet.bj.bcebos.com/models/mot/deepsort_pcb_pyramid_r101.pdparams

你的场景是检测行人吗？现在只支持单类别，我们提供的两个模型jde_yolov3和yolov3的权重都是只训一类行人的。

**Comment by yqsoooo** [comment]
> 过几天会更新ppyolo picodet和faster rcnn的对应配置和模型

好的

我尝试了下2.2和devlop readme,按照官方deepsort   read_me.cn中的默认det+reid权重导出后预测视频 还是满屏框 是还需要配置一些class_num之类吗？没见到相关文档

det_weght=https://paddledet.bj.bcebos.com/models/mot/jde_yolov3_darknet53_30e_1088x608.pdparams
reid_weights=https://paddledet.bj.bcebos.com/models/mot/deepsort_pcb_pyramid_r101.pdparams

> > > 过几天会更新ppyolo picodet和faster rcnn的对应配置和模型
> > 
> > 
> > 好的
> > 我尝试了下2.2和devlop 按照官方read_me中的步骤默认det+reid权重导出后预测视频 还是满屏框 是还需要配置一些class_num之类吗？没见到相关文档
> > det_weght=https://paddledet.bj.bcebos.com/models/mot/jde_yolov3_darknet53_30e_1088x608.pdparams reid_weights=https://paddledet.bj.bcebos.com/models/mot/deepsort_pcb_pyramid_r101.pdparams
> 
> 你的场景是检测行人吗？现在只支持单类别，我们提供的两个模型jde_yolov3和yolov3的权重都是只训一类行人的。



我的期望不是检测行人，我标注了一些单类别  路灯，
使用Ppyolo 或者yolov3训练出模型 目前det_weight已经可用。

但是我的理解是，我使用了readme中的de_yolov3_darknet53_30e_1088x608.pdparams检测器，
和默认的reid deepsort_pcb_pyramid_r101.pdparams
我根据readme预测任意视频，就算没有行人，也不应该满屏幕的画框把。

**Comment by yqsoooo** [comment]
坐等

**Comment by nemonameless** [comment]
已经合入了，https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/mot/deepsort 
请使用release/2.3或develop分支代码。

**Comment by yqsoooo** [comment]
> 已经合入了，https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/mot/deepsort 请使用release/2.3或develop分支代码。

好的感谢提醒，有空我会尽快尝试
