### ISSUE TITLE
visualdl如何配置远程web页面访问

### ISSUE THREAD

**Issue by lujx1024** [PaddlePaddle/PaddleDetection#4300]
## 描述问题/Describe the bug

使用PaddleDetection训练模型，训练过程正常，启用visualdl功能后，由于训练服务器在远程，在本地查看可视化数据趋势需要通过远程web形式，但是出现了访问超时的情况。

## 环境/Environment
1. Paddle 和 PaddleDetection均为当前最新版本，且训练过程正常。
2. 已开启visualdl功能
3. 训练服务器为CentOS 7 操作系统，局域网IP地址：192.168.1.101
4. 操作终端操作系统 Windows 10，局域网IP地址：192.168.1.200

### Visual启动日志
```
(detection) [root@centos PaddleDetection]# visualdl --logdir vdl_dir/scalar/ --host 192.168.1.101

VisualDL 2.2.0
Running VisualDL at http://192.168.1.101:8040/ (Press CTRL+C to quit)
```

### CURL 远程访问日志

```
C:\Users\lujx>curl http://192.168.1.101:8040
curl: (7) Failed to connect to 192.168.1.101 port 8040: Timed out
```

### CURL 本地访问日志

```
[root@centos_aoto home]# curl http://192.168.1.101:8040/app
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="http://192.168.1.101:8040/app/">http://192.168.1.101:8040/app/</a>. If not click the link.
```

指定了`--host`后，只有本地可以访问，远程依然访问不了？ 请问这个问题应该如何排查和解决？

**Comment by wangxinxin08** [comment]
远程访问的话，能正常ping 192.168.1.101吗？如果不能正常ping通，应该是网络的原因

**Comment by lujx1024** [comment]
@wangxinxin08 能ping通的，以上的训练以及CURL指令，都是通过ssh远程连接服务器之后操作的，所以与服务器之间的网络连接应该是没有问题的

**Comment by wangxinxin08** [comment]
远程访问的话，网址也要带上/app

**Comment by lujx1024** [comment]
我带了/app尝试了一下，还是不行。 这个`--host` 指定的是不是训练服务器的地址？是不是我设置错了？

**Comment by rainyfly** [comment]
在windows机器上直接用浏览器可以访问吗，或者visualdl --logdir vdl_dir/scalar/ --host 0.0.0.0 ， 然后再试试

**Comment by lujx1024** [comment]
我尝试过了，使用浏览器访问也是超时，使用 `0.0.0.0`也无法访问，我检查了防火墙设置，防火墙没有阻拦这个请求，关闭防火墙测试后依然无法访问。

**Comment by lujx1024** [comment]
更换了一台训练服务器再次尝试了一下，`--host`还是需要设置成服务器的地址,关闭防火墙或开通`8040`端口即可访问可视化数据。
