### ISSUE TITLE
不能自己训练吗

### ISSUE THREAD

**Issue by a6965921** [PaddlePaddle/PaddleDetection#4301]
不能自己训练吗   我要训练某个图标

**Comment by lyuwenyu** [comment]
可以

**Comment by a6965921** [comment]
> 可以

没看到教程。。我要重头开始训练

**Comment by lyuwenyu** [comment]
参考这个

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/docs/tutorials/GETTING_STARTED_cn.md
