### ISSUE TITLE
[Other General Issues]关于yolo中的loss问题

### ISSUE THREAD

**Issue by 17076372880** [PaddlePaddle/PaddleDetection#4302]
请问在yolo的loss中
![image](https://user-images.githubusercontent.com/41175199/137055549-db72bdb9-e684-4726-bb3e-6478610d9442.png)
回归的loss乘了一个权重来平衡样本数量，这个在PaddleDection中有体现吗？我去看代码没有发现，我想改一下这个权重没有找到地方下手，希望帮忙指出来在哪里修改，谢谢。

**Comment by lyuwenyu** [comment]
以yolo loss为例  可以在代码里找到loss_xy loss_wh然后进行修改

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/modeling/losses/yolo_loss.py#L113

**Comment by 17076372880** [comment]
> 以yolo loss为例 可以在代码里找到loss_xy loss_wh然后进行修改
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/modeling/losses/yolo_loss.py#L113

我的意思是，这个yolov3的loss的计算是不是就是loss_xy+loss_wh+loss_conf+loss_cls，并没有给loss_xy+loss_wh乘权重

**Comment by lyuwenyu** [comment]
是的，  你不是想要修改嘛  可以直接在那个类里操作

**Comment by 17076372880** [comment]
> 是的， 你不是想要修改嘛 可以直接在那个类里操作

谢谢回答，请问当时为什么没有加这个权重呢？是因为用处不大吗？还是添加了别的东西来达到同样的作用。

**Comment by lyuwenyu** [comment]
@17076372880

我们这个是为了复现yolov3 和yolov3一致的

你发这个loss 是在那个文章看到的呢

**Comment by 17076372880** [comment]
> @17076372880
> 
> 我们这个是为了复现yolov3 和yolov3一致的
> 
> 你发这个loss 是在那个文章看到的呢

上面那张图里的loss是Paddle实现的YOLO_loss
![image](https://user-images.githubusercontent.com/41175199/137233983-6187e512-a784-4430-9957-8be35a479457.png)

**Comment by lyuwenyu** [comment]
好的 ppdet里的计算没有那个weight_box
