### ISSUE TITLE
使用yolov3训练的模型目标检测效果很差

### ISSUE THREAD

**Issue by DevilMay-Cry** [PaddlePaddle/PaddleDetection#4305]
我目前在用yolov3的yolov3_darknet53_270e_coco训练了一个针对卡车的目标检测模型，样本类别有6个，训练集大概有2500多张图片，一共训练了默认的270轮，训练完之后的效果召回率很低，但是正确率还可以，如果我想提高模型的召回率应该怎么做？
针对某一种类别进行恢复训练和全部类别进行恢复训练对模型的召回率影响大吗？

**Comment by lyuwenyu** [comment]
1. recall低 可以考虑把 nms_threshold调低一些
2. 这块应该影响不是很大吧
