### ISSUE TITLE
C++推理部署win10+VS2019编译

### ISSUE THREAD

**Issue by Simonlyym** [PaddlePaddle/PaddleDetection#431]
![image](https://camo.githubusercontent.com/0771bce0753abe87fccce1166e23d482a72a1bb8/68747470733a2f2f706164646c657365672e626a2e626365626f732e636f6d2f696e666572656e63652f7673323031395f73746570352e706e67)
在我的VS2019上到这上面这一步的时候并没没有出现上面的情况；
没有以下三个变量
*CUDA_LIB
OPENCV_DIR
PADDLE_DIR
同时左上角的显示的也不是x64-release而是x64-debug
![image](https://user-images.githubusercontent.com/42372497/78216233-f41e8980-74eb-11ea-9ee9-dae51c7ac328.png)
这个是什么原因啊，求大佬指点

**Comment by FDInSky** [comment]
*CUDA_LIB
OPENCV_DIR
PADDLE_DIR
如果没有可以进行手动配置

**Comment by Simonlyym** [comment]
怎样手动配置？？

**Comment by Simonlyym** [comment]
还有大佬在吗

**Comment by qingqing01** [comment]
@Simonlyym  是否还有问题，可以试下release/0.3分支下的预测试下。 以及还有问题，可以新开issue。
