### ISSUE TITLE
[Other General Issues]已有inference模型，请问该如何用python代码加载该模型

### ISSUE THREAD

**Issue by MatrixLyz0623** [PaddlePaddle/PaddleDetection#4310]
请问一下可否像如下PaddleOCR那样使用Python代码而不是命令行进行模型加载部署
from paddleocr import PaddleOCR, draw_ocr

```
# Paddleocr目前支持中英文、英文、法语、德语、韩语、日语，可以通过修改lang参数进行切换
# 参数依次为`ch`, `en`, `french`, `german`, `korean`, `japan`。
ocr = PaddleOCR(use_angle_cls=True, lang="ch")  # need to run only once to download and load model into memory
img_path = 'PaddleOCR/doc/imgs/11.jpg'
result = ocr.ocr(img_path, cls=True)
for line in result:
    print(line)
```
这样的话就可以得到加载ocr的模型

**Comment by ghostxsl** [comment]
可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/deploy/python/infer.py#L529
使用predictor的写法来实现

**Comment by MatrixLyz0623** [comment]
> 可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/deploy/python/infer.py#L529 使用predictor的写法来实现

感谢，已经实现
