### ISSUE TITLE
设置标签

### ISSUE THREAD

**Issue by QL-AR** [PaddlePaddle/PaddleDetection#4313]
请问怎么设置中文标签   让检测标签显示中文？

**Comment by MatrixLyz0623** [comment]
你需要在visualize.py的draw_bbox函数里加上字体

from PIL import Image, ImageDraw,ImageFont
font=ImageFont.truetype("../NotoSerifCJK-Light.ttc",8)#你需要的中文字体



 tw, th = draw.textsize(text,font=font)
        draw.rectangle(
            [(xmin + 1, ymin - th), (xmin + tw + 1, ymin)], fill=color)
        draw.text((xmin + 1, ymin - th), text,font=font, fill=(255, 255, 255))

**Comment by QL-AR** [comment]
训练模型的代码用改吗？

**Comment by QL-AR** [comment]
他也不支持中文？

**Comment by ghostxsl** [comment]
训练代码改不改都可以，我理解你这个需求是为了可视化的时候中文正常显示，那你训练的代码就可以不用改

**Comment by QL-AR** [comment]
具体怎么操作的
