### ISSUE TITLE
paddledetection测试不生成权重文件

### ISSUE THREAD

**Issue by 14385423** [PaddlePaddle/PaddleDetection#4316]
![QQ图片20211014190318](https://user-images.githubusercontent.com/61214936/137445371-ddd398fa-49ec-4ced-bf0e-ecfb55cb5076.jpg)
运行python tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml 命令后训练未完成第一轮就停了，不报错，也不生成权重文件，在搭环境的时候用到过有关cython_bbox-0.1.3报错的解决方案：https://blog.csdn.net/u010013028/article/details/107771600       
，和他有关系吗？还是学习率的问题，用同样的数据集在yoloV5，pytorch下能得到训练的权重文件，但paddledetecttion在output文件夹里不生成，并且训练未完成就自动结束，求助。

**Comment by yuanjim** [comment]
1）训练中止，有可能是显存满了，可以先用nvidia-smi检查一下显存占用情况，如果训练依然提前中断，可以把batchsize调小一点（一般除以2），不断除以2直到batchsize为1，如果还是中断就是模型网络太大的问题了，可以尝试小一点的网络。
2）没有生成权重文件，是因为第一个Epoch都还没完成，一般在配置文件中设置了1以上的snapshot_epoch（我设置的是 10，每10个epoch生成一次当下的权重）。
