### ISSUE TITLE
[Other General Issues] 训练好的模型，导出模型后，预测视频时报错

### ISSUE THREAD

**Issue by yqsoooo** [PaddlePaddle/PaddleDetection#4319]
基本信息： PaddleDetection_devlop  yolov3_darknet53_270e_voc   label_list.txt就一种类别

configs/yolov3/yolov3_darknet53_270e_voc.yml
![image](https://user-images.githubusercontent.com/15975613/137466046-9666abaf-9966-4721-811c-9834db46264f.png)

configs/datasets/voc.yml
![image](https://user-images.githubusercontent.com/15975613/137466137-2278b661-54bf-4da2-aef2-59c27aef37bb.png)

训练完成执行导出模型
python tools/export_model.py -c configs/yolov3/yolov3_darknet53_270e_voc.yml --output_dir=./inference_model  -o weights=output/yolov3_darknet53_270e_voc/model_final
执行预测 
python deploy/python/infer.py --model_dir=inference_model/yolov3_darknet53_270e_voc --video_file=123.mp4 --device=GPU

IndexError: index 1 is out of bounds for axis 1 with size 0

![image](https://user-images.githubusercontent.com/15975613/137467389-47ea8d80-36ca-4c2b-ad52-c610a0274dbf.png)

**Comment by ghostxsl** [comment]
你把np_boxes打印一下看看，看报错信息是当前帧是没检测出物体的吧，index越界了

**Comment by yqsoooo** [comment]
> np_boxes
没有检测出物体咋会index越界呢。。
[[0.0000000e+00 1.5152230e-02 5.3638611e+02 1.8725439e+02 5.5899829e+02
  2.0404321e+02]
 [0.0000000e+00 1.0863523e-02 5.3259833e+02 1.9074054e+02 5.6675604e+02
  1.9852841e+02]]

![image](https://user-images.githubusercontent.com/15975613/137474321-7d7f2e8e-f3f4-4710-84e7-c57c31b94ed7.png)

**Comment by ghostxsl** [comment]
![image](https://user-images.githubusercontent.com/23647349/137609412-a98d24ed-fea3-4049-b7b9-1becd15fea06.png)
你这个地方是空数组，按理说不应该会传进一个空list进来，你可以check一下外面的那个函数的输出看看是咋回事

**Comment by yqsoooo** [comment]
> 你这个地方是空数组，按理说不应该会传进一个空list进来，你可以check一下外面的那个函数的输出看看是咋回事


![image](https://user-images.githubusercontent.com/15975613/137664410-e3dbbca8-12f7-42c6-87e6-ad2fd082d0e4.png)

detect frame:53
{'boxes': array([[0.0000000e+00, 1.3823928e-02, 5.5502875e+02, 2.3858968e+02,
        5.7205255e+02, 2.5134258e+02]], dtype=float32), 'boxes_num': array([1], dtype=int32)}
detect frame:54
[WARNNING] No object detected.
{'boxes': array([], shape=(1, 0), dtype=float64), 'boxes_num': [0]}

很神奇，不知道本地环境发生啥问题了。。我都已经重新拉取git代码，跑roadsign官方demo 还有这个问题。

**Comment by ghostxsl** [comment]
看你这个输出，应该是你改了原来代码中的post_process方法，他这个地方如果没有检测到物体应该是输出：{'boxes': array([], shape=(0, 6), dtype=float64), 'boxes_num': [0]}，但你这里的'boxes'的shape是[1, 0]，你再看一下你代码中最后输出bbox格式的地方有没有问题呢

**Comment by yqsoooo** [comment]
> 看你这个输出，应该是你改了原来代码中的post_process方法，他这个地方如果没有检测到物体应该是输出：{'boxes': array([], shape=(0, 6), dtype=float64), 'boxes_num': [0]}，但你这里的'boxes'的shape是[1, 0]，你再看一下你代码中最后输出bbox格式的地方有没有问题呢


我没有修改任何的源码。只是跑了个demo。
![image](https://user-images.githubusercontent.com/15975613/137670202-54c922be-e0c7-42ab-941d-44306fb58cbe.png)
![image](https://user-images.githubusercontent.com/15975613/137670258-d5b187a3-90a7-48db-87af-8b880863c5a4.png)
![image](https://user-images.githubusercontent.com/15975613/137670284-e1eea07b-0489-456a-92f1-d1b9cf2b0c69.png)
![image](https://user-images.githubusercontent.com/15975613/137670297-1f4b538a-7959-4f41-a23b-17a992e3d6a5.png)
![image](https://user-images.githubusercontent.com/15975613/137670317-1238df8e-60d5-45eb-b173-1e0457bc946d.png)

**Comment by ghostxsl** [comment]
bug已修复，请参考 #4325

**Comment by yqsoooo** [comment]
> bug已修复，请参考 #4325

刚想回复   使用2.1

> bug已修复，请参考 #4325


好的 我试一下，develop和2.2都修复了是吗
在你最后回复的时 我去尝试了下2.1的demo是可以跑通的  但是会提示[WARNNING] No object detected.记得以前好像是没有这种提示的

![image](https://user-images.githubusercontent.com/15975613/137689968-d9f85cbd-d967-456a-9436-09a6e30ffc1e.png)

**Comment by ghostxsl** [comment]
PR还没合入，你先本地更新一下试试看～

**Comment by yqsoooo** [comment]
> PR还没合入，你先本地更新一下试试看～

本地更新后可以正常预测视频
