### ISSUE TITLE
请问基于Paddle的CBNet具体实现在哪里？

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#4321]
我看到PaddleDetction中提到是拥有CBNet的，可是为何我找不到呀？

**Comment by ghostxsl** [comment]
这个应该是在静态图下有：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/static/ppdet/modeling/backbones/cb_resnet.py
动态图下暂时未添加，后续会考虑支持

**Comment by ghost** [comment]
> 这个应该是在静态图下有：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/static/ppdet/modeling/backbones/cb_resnet.py 动态图下暂时未添加，后续会考虑支持

Thanks！
