### ISSUE TITLE
[Other General Issues]CBNet应用实现的相关问题

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#4324]
你好，我最近想使用其他Backbone来构成一个新的CBNet，我参考了paddle此前的cb_resnet.py的工作，发现其静态图版本中按照CBNet结构将多个ResNet拼接在一起，并且权重命名时添加了一个“_level”来注明是第几个Backbone，我还没有找到参数load部分是否也有相应改动。
目前我在最新的paddledetection版本下想构建一个新的CBNet，请问：“是否直接在建立结构后，在外部先按照结构中的命名方式复制修改权重即可？还是需要对load部分进行一定改动？”

**Comment by jerrywgz** [comment]
这里有两种方式应该都可以，一个是cbnet中的每个子model分别去load权重，这样名字应该是能对应上的。另一种方式就是在外部调整load的逻辑，两个子model的参数在动态图下只是前缀名不同

**Comment by ghost** [comment]
> 这里有两种方式应该都可以，一个是cbnet中的每个子model分别去load权重，这样名字应该是能对应上的。另一种方式就是在外部调整load的逻辑，两个子model的参数在动态图下只是前缀名不同

感谢您的回复，目前已经直接将ResNet50直接拼接为Dual-CBNet结构并调整预训练权重，正在进行相关实验测试其性能。
Thanks！

**Comment by ghost** [comment]
> 这里有两种方式应该都可以，一个是cbnet中的每个子model分别去load权重，这样名字应该是能对应上的。另一种方式就是在外部调整load的逻辑，两个子model的参数在动态图下只是前缀名不同

请问Paddle有CBNetV2的应用吗，目前都没看到有人在使用？
