### ISSUE TITLE
centernet方案

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleDetection#4330]
请问现在有没有centernet的方案，何时可以更新？

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/centernet 已经更新

**Comment by Monday-Leo** [comment]
主干网络替换成mobilenet的轻量化网络后期会更新吗？

**Comment by jerrywgz** [comment]
这个我们目前暂时还没有计划，可以尝试更换下骨干网络，同时fpn结构去除dcn相关的操作训练一版
