### ISSUE TITLE
[Document Improvement] 特色垂类车辆追踪的权重文件都404了

### ISSUE THREAD

**Issue by yqsoooo** [PaddlePaddle/PaddleDetection#4331]
CUDA_VISIBLE_DEVICES=0 python tools/eval_mot.py -c configs/mot/vehicle/fairmot_dla34_30e_1088x608_bdd100k_vehicle.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608_bdd100k_vehicle.pdparams

并且fairmot_dla34_30e_1088x608_bdd100k_vehicle.xml 应该少了个mot把。

**Comment by yqsoooo** [comment]
我在其他issues中搜索到可用的kitti权重 
 但issues推荐的bdd100k权重依旧404。https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608_kitti_vehicle.pdparams
 
 使用kitti_vehicle权重 识别的fps是15左右，我当前的机器是tesla V100 16G 单卡 这个预测速度正常吗。还可以提速吗

**Comment by nemonameless** [comment]
https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608_bdd100kmot_vehicle.pdparams  
已经可以下载。请使用develop分支代码。release/2.2分支暂时不cherry-pick develop分支的改动了。
提速建议使用deploy下的infer，需要导出预测模型，用导出的模型基于Python去预测。具体参照文档 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/mot/vehicle
