### ISSUE TITLE
如何支持压缩数据来训练

### ISSUE THREAD

**Issue by wdbsf** [PaddlePaddle/PaddleDetection#4343]
用自己的数据集，格式是coco, 训练paddledetection， 使用飞桨bml, 自定义作业， 数据集上传bos, 数据集110G左右，分train, val, test 三个压缩数据文件上传，但ppdet 如何支持压缩数据训练？

**Comment by lyuwenyu** [comment]
@FL77N

**Comment by wangxinxin08** [comment]
目前暂不支持压缩数据训练，你可以先下载下来解压后进行训练
