### ISSUE TITLE
请教一下，关于paddledetection中预测部分的输出格式

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/PaddleDetection#435]
写好了预测部分，生成bbox和mask，想请教一下，如何转换为paddledetection的预测格式

目前得到的bbox是一个list [ [box1], [box2], .... ]  其中box为 （ n * 6 ）的Variable

**Comment by qingqing01** [comment]
@zhengzhe97  也可以参考文档： https://paddledetection.readthedocs.io/advanced_tutorials/inference/EXPORT_MODEL.html#id1

**Comment by zhengzhe97** [comment]
谢谢回复，使用了multiclass_nms这个op，对于输出的预测框是否能找到对应输入预测框的索引

**Comment by heavengate** [comment]
> 谢谢回复，使用了multiclass_nms这个op，对于输出的预测框是否能找到对应输入预测框的索引

multiclass_nms一般是预测的是有，理论上来说预测的过程是不需要知道也不用给定gt bbox，输入只有image的信息，所以multiclass_nms不存在预测框对于输入预测框的索引一说，我理解里要的预测框对于输出预测框的索引应该是类似于发生在metric，可以参考一下我们提供的voc数据集上metric里的方法，其实就是对于每个预测bbox，遍历每个gt bbox找到IoU最大的的一个
https://github.com/PaddlePaddle/PaddleDetection/blob/83622f9a7ef64b6300ddc6f4096eecca2526b362/ppdet/utils/map_utils.py#L113

**Comment by zhengzhe97** [comment]
@heavengate 可能是我没表述清楚，我所说的输入预测框是指输入到`multiclass_nms`里的bboxes，
输出的预测框是指`multiclass_nms`经过nms后输出的pred_bbox。因为后面要用到pred_bbox在bboxes上的索引，是否有办法获得
`paddle.fluid.layers.multiclass_nms(bboxes, scores, score_threshold, nms_top_k, keep_top_k, nms_threshold=0.3, normalized=True, nms_eta=1.0, background_label=0, name=None)`

**Comment by heavengate** [comment]
> @heavengate 可能是我没表述清楚，我所说的输入预测框是指输入到`multiclass_nms`里的bboxes，
> 输出的预测框是指`multiclass_nms`经过nms后输出的pred_bbox。因为后面要用到pred_bbox在bboxes上的索引，是否有办法获得
> `paddle.fluid.layers.multiclass_nms(bboxes, scores, score_threshold, nms_top_k, keep_top_k, nms_threshold=0.3, normalized=True, nms_eta=1.0, background_label=0, name=None)`

嗯，由于一般业务没有关心这个索引信息的，当前这个索引信息封装的multiclass_nms内部没有暴露出来，如果你想获取的话可以尝试下把multiclass_nms的输入和输出都fetch出来，匹配一下看看是哪个bbox，另外就只能自行封装multiclass_nms了。。

**Comment by zhengzhe97** [comment]
自己封装了一个，nms后的结构输入验证脚本里面需要score从大到小排列吗

**Comment by heavengate** [comment]
> 自己封装了一个，nms后的结构输入验证脚本里面需要score从大到小排列吗

nms应该只保留posk个，这posk个都会用于做metric，score不会在metric中用到

**Comment by zhengzhe97** [comment]
输出里面这个maxDets=  1是取最大的score，并不是输入的第一个，是这样吗
![N6{A`PKD$M786~IHG9KEPCC](https://user-images.githubusercontent.com/26462054/78454182-0570bd00-76c9-11ea-8209-5c5beebf8281.png)

**Comment by heavengate** [comment]
> 输出里面这个maxDets= 1是取最大的score，并不是输入的第一个，是这样吗
> ![N6{A`PKD$M786~IHG9KEPCC](https://user-images.githubusercontent.com/26462054/78454182-0570bd00-76c9-11ea-8209-5c5beebf8281.png)

pycocotool是这么处理，如果你用COCO的评估需要注意score

**Comment by zhengzhe97** [comment]
了解了，感谢解答！

**Comment by zhengzhe97** [comment]
@heavengate 
请问一下，关于mask的评估，感觉太吃内存，评估模型的时候内存溢出，最后把nms输出的数量调少了。
我想是不是由于存储mask太占内存。
测试的是coco的验证集大约4900张图片，nms输出数量为100的时候，内存溢出。

**Comment by heavengate** [comment]
这个问题在master分支已经修复了，可以pull一下最新的master分支试下

**Comment by zhengzhe97** [comment]
谢谢，已解决

**Comment by qingqing01** [comment]
```
            out, index = fluid.layers.multiclass_nms2(bboxes=boxes,
                                              scores=scores,
                                              background_label=0,
                                              score_threshold=0.5,
                                              nms_top_k=400,
                                              nms_threshold=0.3,
                                              keep_top_k=200,
                                              normalized=False,
                                              return_index=True)
```
使用这个接口可以返回nms之后的index

**Comment by zhengzhe97** [comment]
好的，我之后试下这个api，应该可以快不少
