### ISSUE TITLE
[Other General Issues]SystemError，无法使用COCO数据集进行训练

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#4354]
目前在使用TTFNet进行相关工作，准备使用COCO数据集进行网络的训练，但是反复出现下图中的错误：
![image](https://user-images.githubusercontent.com/59326436/138278324-cb7e8819-2289-470c-a004-41f8429b18d6.png)
感到奇怪的有两点：
1.我可以使用自己准备的其他COCO格式的图片进行训练
2.在9.30我已经使用这份COCO数据集进行了相关训练

**Comment by ghost** [comment]
按照下述提示，将woker_num修改为0后，程序卡死：
![image](https://user-images.githubusercontent.com/59326436/138279331-24f41314-9e93-4152-b4f3-d9d0c594b857.png)

**Comment by nemonameless** [comment]
能完整训完一个epoch吗？使用其他模型训练是否同样会有这个问题？建议使用Paddle最新版和PaddleDetection最新分支或2.2分支。

**Comment by ghost** [comment]
（这个问题和4357中的是两个问题）
我将代码全部回调至最初的TTFnet，也无法利用该COCO数据集进行训练
![image](https://user-images.githubusercontent.com/59326436/138536746-534cf4bd-0566-4341-b85f-d33d0ecbcfe8.png)

**Comment by ghost** [comment]
该问题已在将代码更新至2.2后解决。
但是奇怪的还是曾经已经使用该COCO数据集进行训练过，我也没有改动过train.py的代码，不知道为什么这次会出现问题？

**Comment by ghost** [comment]
相似的问题再次出现在我训练COCO训练集的过程中，此前在重装2.2版本后我曾经尝试了一下训练，当时成功了，随后我终止了代码进行相关调试改进，昨晚想开启COCO训练时就发现还是报错，目前我使用TTFNet标准设置进行训练，若是使用其他数据集则正常进行，但是使用COCO就反复得到多进程错误，设置work_num=0如下图所示，显存和计算资源始终不变，迟迟无法开始训练：
![image](https://user-images.githubusercontent.com/59326436/138793563-47467e0a-86ec-4cdd-b465-c70ad8921db3.png)
worker_num=4下直接无法load权重进行初始化：
![image](https://user-images.githubusercontent.com/59326436/138793795-08b55b35-f1d0-4263-96f1-fae473c77903.png)
