### ISSUE TITLE
[Other General Issues]TTFNet在训练过程中设置eval_batch>1

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#4357]
在训练TTFnet时开启了--eval，并修改了配置文件中EvalReader中的batch_size=18，但是会出现如下错误：
![F83C564468F778B667EE1912982E8B9F](https://user-images.githubusercontent.com/59326436/138389627-46cb5f0b-b7a8-442d-afb6-b1b9fa73d2e7.jpg)
我查阅了其他开发者所提出到Issue，但是发现都没有效果，请问这是为什么呢

**Comment by nemonameless** [comment]
如果不开启--eval是否会有这个问题？能训完一个完整的epoch吗？
#4354

**Comment by ghost** [comment]
我可以在batch_size=1的条件下进行边训练边eval，但是一增大batch_size后，单个epoch是可以跑完的，就是无法进入eval

**Comment by ghost** [comment]
该问题已在将代码更新至2.2后解决。
