### ISSUE TITLE
PaddleDetection训练VOC数据集出现问题

### ISSUE THREAD

**Issue by QIANXUNZDL123** [PaddlePaddle/PaddleDetection#4359]
**PaddleDetection ==2.1

报AssertionError: not found any voc record in train_list.txt错误
![image](https://user-images.githubusercontent.com/46549527/138393521-9021d4c9-b092-437a-bf90-c3b87273fb68.png)

我的数据集格式：
![image](https://user-images.githubusercontent.com/46549527/138393597-7e9ae8ec-cae3-4af8-aafa-064239c6dd08.png)

**Comment by nemonameless** [comment]
可能是路径问题，建议打印出来再仔细检查下

**Comment by HRyixin** [comment]
请问该问题最后如何解决的呢？
