### ISSUE TITLE
请问mask rcnn模型支持使用paddleslim进行压缩吗？

### ISSUE THREAD

**Issue by Magsun** [PaddlePaddle/PaddleDetection#436]
@百度专家 您好，
由于分割模型想要应用在嵌入式板载设备上，对模型的大小会有要求，mask rcnn 50的大小勉强能加载运行。阅读paddleslim的介绍时发现示例都是yolov3模型进行剪枝和蒸馏，请问mask rcnn支持模型压缩吗？

**Comment by heavengate** [comment]
mask rcnn目前我们没有开始探索压缩模型，不过对mask rcnn压缩是支持的，
**剪枝**
如果想要对mask rcnn模型裁剪，建议先跑一下mask rcnn模型的敏感度分析，确定裁剪率，参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.2/slim/sensitive
然后根据裁剪率压缩，参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.2/slim/sensitive
**蒸馏**
mask rcnn模型的蒸馏需要自行制定蒸馏的特征图和设置蒸馏loss，可参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.2/slim/distillation

**Comment by Magsun** [comment]
> mask rcnn目前我们没有开始探索压缩模型，不过对mask rcnn压缩是支持的，
> **剪枝**
> 如果想要对mask rcnn模型裁剪，建议先跑一下mask rcnn模型的敏感度分析，确定裁剪率，参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.2/slim/sensitive
> 然后根据裁剪率压缩，参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.2/slim/prune
> **蒸馏**
> mask rcnn模型的蒸馏需要自行制定蒸馏的特征图和设置蒸馏loss，可参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.2/slim/distillation

非常感谢您的解答！

顺颂商祺
