### ISSUE TITLE
[BUG] 10月22更新后出现安装异常 No module named 'static'

### ISSUE THREAD

**Issue by InkingWater** [PaddlePaddle/PaddleDetection#4368]
你好！我们在尝试安装2.2的最新版本时出现了异常，static这个Module无法找到，只有回退到9月份的版本才安装成功。

**Comment by qingqing01** [comment]
您安装的PaddlePaddle版本是多少？注意PaddlPaddleDetection和PaddlePaddle的版本对应关系需要正确。

<img width="991" alt="图片" src="https://user-images.githubusercontent.com/7845005/138627373-f28bef56-c5bb-4274-917b-eadb41714b08.png">

**Comment by HuangZurong** [comment]
> 你好！我们在尝试安装2.2的最新版本时出现了异常，static这个Module无法找到，只有回退到9月份的版本才安装成功。

切换PaddleDetection如不行，可以查看一下paddledet依赖的版本，选择对应的版本（与PaddlePaddle一致）的试试

**Comment by moshanshan** [comment]
我也遇到了同样的问题，paddlepaddle版本为2.1.3，paddledetection版本为2.2，在编译完成后提示No module named 'static' 。
自己pip安装static后，提示ppdet/modeling/architectures/meta_arch.py
from static.ppdet.untils.post_process import nms
No module named 'static.ppdet'

**Comment by pureloveljc** [comment]
在static 文件下　添加　__init__.py　就行了

**Comment by moshanshan** [comment]
> 在static 文件下　添加　**init**.py　就行了

非常感谢，解决了

**Comment by wzq5210** [comment]
> > 在static 文件下　添加　**init**.py　就行了
> 
> 非常感谢，解决了

你好，我也遇到了这个问题，能具体讲一讲怎么做的吗？

**Comment by moshanshan** [comment]
> > > 在static 文件下　添加　**init**.py　就行了
> > 
> > 
> > 非常感谢，解决了
> 
> 你好，我也遇到了这个问题，能具体讲一讲怎么做的吗？

在static 文件下，添加__init__.py就行了，空文件就行

**Comment by wzq5210** [comment]
> > > > 在static 文件下　添加　**init**.py　就行了
> > > 
> > > 
> > > 非常感谢，解决了
> > 
> > 
> > 你好，我也遇到了这个问题，能具体讲一讲怎么做的吗？
> 
> 在static 文件下，添加__init__.py就行了，空文件就行

![image](https://user-images.githubusercontent.com/69022461/138993562-62a35c38-1b09-4a71-b364-7a7fc6a95e8f.png)
请问是这样吗？还是不行...

**Comment by moshanshan** [comment]
> > > > > 在static 文件下　添加　**init**.py　就行了
> > > > 
> > > > 
> > > > 非常感谢，解决了
> > > 
> > > 
> > > 你好，我也遇到了这个问题，能具体讲一讲怎么做的吗？
> > 
> > 
> > 在static 文件下，添加__init__.py就行了，空文件就行
> 
> ![image](https://user-images.githubusercontent.com/69022461/138993562-62a35c38-1b09-4a71-b364-7a7fc6a95e8f.png) 请问是这样吗？还是不行...

我是这样添加了之后就可以了

**Comment by wzq5210** [comment]
> > > > > > 在static 文件下　添加　**init**.py　就行了
> > > > > 
> > > > > 
> > > > > 非常感谢，解决了
> > > > 
> > > > 
> > > > 你好，我也遇到了这个问题，能具体讲一讲怎么做的吗？
> > > 
> > > 
> > > 在static 文件下，添加__init__.py就行了，空文件就行
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/69022461/138993562-62a35c38-1b09-4a71-b364-7a7fc6a95e8f.png) 请问是这样吗？还是不行...
> 
> 我是这样添加了之后就可以了

哦哦 好的  谢谢了

**Comment by qingqing01** [comment]
是最近 https://github.com/PaddlePaddle/PaddleDetection/pull/4317 引起的， 会在PR https://github.com/PaddlePaddle/PaddleDetection/pull/4374 修复该问题。
