### ISSUE TITLE
YOLO IOU loss

### ISSUE THREAD

**Issue by zimoqingfeng** [PaddlePaddle/PaddleDetection#437]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/modeling/losses/iou_loss.py#L91
同学您好：
         IOU loss是确定有平方么，辛苦您帮忙核对一下。

**Comment by CodesFarmer** [comment]
你好，在论文中IoU loss的实现是

**Comment by CodesFarmer** [comment]
你好，论文https://arxiv.org/abs/1908.03851里边确实是L_iou=1-iou
我们实现的L_iou= 1 - iou^2，是参考了https://github.com/ruinmessi/ASFF/blob/master/models/utils_loss.py#L60 这个实现，
我们最好的实验结果也是L_iou= 1 - iou^2比原文略高(COCO mAP大概高0.1%个点)

**Comment by zimoqingfeng** [comment]
好的 辛苦您啦
