### ISSUE TITLE
PP-yolov2训练时间

### ISSUE THREAD

**Issue by lucky-xu-1994** [PaddlePaddle/PaddleDetection#4372]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## 描述问题/Describe the bug
使用两万张数据集，采用VOC格式，下载预训练模型，对PP-YOLOv2进行训练，目前训练时间长达12天。

## 复现/Reproduction

1. 使用的命令如下：

```none
Python tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml --eval
```
2. 更改了configs/ppyolov2_r50vd_dcn_voc.yml ,将batch_size改为8.（更高会导致out of memory）, epoch:330
    更改了configs/ppyolov2_reader.yml ,将worker_num改为8.

3. 使用自定义的数据集，图片大小为640*512，格式为VOC格式。

## 环境/Environment
1. 使用PaddleDetection-release-2.2.

2. 操作系统信息。Linux：ubantu 18.04

4. Python 3.8.

5. 显卡P40，cuda 10.2 cudNN 8.2
 
请问目前这个训练速度是正常的么，除了使用多GPU外，有什么加速训练的方法么？谢谢

**Comment by jerrywgz** [comment]
可以使用coco训练好的权重作为预训练模型，然后finetune 新的数据集，这样可以适当减少训练epoch个数
还可以尝试下将ppyolo中的预处理操作简化一些，比如去除mixup, randomexpand, randomcrop。我们目前也在优化ppyolo的训练速度

**Comment by lucky-xu-1994** [comment]
> 可以使用coco训练好的权重作为预训练模型，然后finetune 新的数据集，这样可以适当减少训练epoch个数 还可以尝试下将ppyolo中的预处理操作简化一些，比如去除mixup, randomexpand, randomcrop。我们目前也在优化ppyolo的训练速度

好的，谢谢！
