### ISSUE TITLE
[Other General Issues]新增模型mAP效果不理想

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4381]
我配置的yolo4+mobilenetv3，可是训练几万iter，mAP值也只有百分之几，到底是这种模型就不行，还是因为没有预训练模型的原因的，或者是其他什么原因呢？我能把静态图放到paddleDetection动态图的那里训练吗？感觉那边的自增模型比静态图简单

**Comment by lyuwenyu** [comment]
不可以直接把静态图的放到动态图的

**Comment by zmdcs** [comment]
为什么？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月29日(星期五) 下午4:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] [Other General Issues]新增模型mAP效果不理想 (Issue #4381)





 
不可以直接把静态图的放到动态图的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
