### ISSUE TITLE
PaddleDetection路标识别数据集

### ISSUE THREAD

**Issue by landscapelc** [PaddlePaddle/PaddleDetection#4387]
评估阶段时选择：默认将训练生成的模型保存在当前output文件夹下

运行以下代码后报错
`export CUDA_VISIBLE_DEVICES=0 #windows和Mac下不需要执行该命令
python tools/eval.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml -o weights=https://paddledet.bj.bcebos.com/models/yolov3_mobilenet_v1_roadsign.pdparams
`

报错如下：
RuntimeError: Downloading from https://paddledet.bj.bcebos.com/models/yolov3_mobilenet_v1_roadsign.pdparams failed with code 404!

应该是网址失效问题，请求解决谢谢

**Comment by lyuwenyu** [comment]
这这个路径`https://paddledet.bj.bcebos.com/models/yolov3_mobilenet_v1_roadsign.pdparams` 应该选择你的output结果啊

**Comment by MintonLee** [comment]
所以解决了吗？百度框架确实不太行。。。。官方都不解答，，，，
