### ISSUE TITLE
Picodet代码问题

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#4391]
您好，picodet的head中，4*（reg_max+1）,其中reg_max含义是什么，还有+1代表什么含义？谢谢
![image](https://user-images.githubusercontent.com/68497831/139293541-dc20be69-0c93-42c6-94d9-36e772da28c4.png)

**Comment by lyuwenyu** [comment]
这个是把区间离散化的隔数  具体公式见
`Distribution Focal Loss`小节  https://arxiv.org/pdf/2006.04388.pdf

**Comment by qdd1234** [comment]
> 这个是把区间离散化的隔数 具体公式见 `Distribution Focal Loss`小节 https://arxiv.org/pdf/2006.04388.pdf

那这个4不是代表4个坐标点吗？

**Comment by yghstill** [comment]
> 那这个4不是代表4个坐标点吗？

@qdd1234 4代表预测框坐标信息
