### ISSUE TITLE
[Document Improvement]PaddleDetection给出的YML文件能给每个变量的选项吗？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4393]
## 📖  文档优化/Documentation Improvement
就像是map_type: 11point这种，除了11point我还能填什么呢？

**Comment by lyuwenyu** [comment]
'11point', 'integral'

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/metrics/map_utils.py#L182

**Comment by zmdcs** [comment]
我想问的是这一类参数去哪里找，并不是单指这一个参数




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月29日(星期五) 下午5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] [Document Improvement]PaddleDetection给出的YML文件能给每个变量的选项吗？ (Issue #4393)





 
'11point', 'integral'
 
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/metrics/map_utils.py#L182
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/metrics/map_utils.py#L160
代码全局搜索一下，找到定义的位置即可，都有注释的

**Comment by zmdcs** [comment]
在AIStudio里面能用全局搜索？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月1日(星期一) 上午10:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] [Document Improvement]PaddleDetection给出的YML文件能给每个变量的选项吗？ (Issue #4393)





 
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/metrics/map_utils.py#L160
 代码全局搜索一下，找到定义的位置即可，都有注释的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nemonameless** [comment]
github或IDE都能全局搜索吧。文档会继续完善，谢谢建议。
