### ISSUE TITLE
[Other General Issues]什么是动态图，什么是静态图？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4404]
原谅我现在才来问这个问题，我之前一直以为动态图是像动态表情包一样，一个会动的图片，可是我看到教程里说行人和车辆也可以作为动态图的训练数据，所以动态图的训练数据指的是会动的图片？还是指图片中待检测的东西是会动的？

**Comment by qingqing01** [comment]
动态图： 是指利用PaddlePaddle框架的动态图实现的，动态图执行和PyTorch类似， 预言特性像Python，构造的模型网络(nn.Layer的实例模块)forward执行过程就可以拿到结果。

静态图:  static文件里是利用PaddlePaddle框架静态图接口实现，一版过程是先构建网络图(Program)，只执行一次，再定义执行器(ParallelExecutor)，再用执行器执行构造的图，执行期间，在构建的网络图(Program)中使用Python的print等不会起到作用。


和检测算法本身没有关系。

**Comment by zmdcs** [comment]
感觉你的回答好复杂，所以不是我理解的动态图是像视频，静态图是图片那样？

**Comment by qingqing01** [comment]
是的，您理解的不对。

**Comment by zmdcs** [comment]
所以进行目标检测的训练时，其实用静态还是动态的没什么区别是吧？只是一个用pytorch开发，一个用Tensor flow开发

**Comment by qingqing01** [comment]
都是飞桨PaddlePaddle框架开发，既支持动态图、也支持静态图。<PyTorch框架是动态图，TF框架既支持静态图、也支持动态图>。 建议使用动态图，主推和维护动态图、调试方便。
