### ISSUE TITLE
yolov3转ONNX，如何指定转出不包括后处理的模型？

### ISSUE THREAD

**Issue by lucky-xu-1994** [PaddlePaddle/PaddleDetection#4408]
## 描述问题/Describe the bug
您好！以下是我转出来的yolov3_mobilenetv3的ONNX模型。
![1635754296(1)](https://user-images.githubusercontent.com/57120921/139641421-c776e85d-2e12-45c4-8251-338626a9972b.png)
输出是两个列表，分别为框的位置信息和得分。
请问，如何将ONNX固定为只输出后处理之前的结果——卷积之后的结果？

**Comment by qingqing01** [comment]
YOLO的后处理包含了yolo-box解码、以及NMS，

1. 如果只不想包含nms，可以 转ONNX前的Paddle模型导出时，配置文件中去掉nms：

https://github.com/PaddlePaddle/PaddleDetection/blob/6220fd3a860e32596e6b83a9583a9ee58ef7424d/configs/yolov3/_base_/yolov3_mobilenet_v3_large.yml#L39-L44

2. 如果yolo-box、nms都不想包含，需要修改源码，下面代码 return的output改成返回`yolo_head_outs`中的内容

https://github.com/PaddlePaddle/PaddleDetection/blob/6220fd3a860e32596e6b83a9583a9ee58ef7424d/ppdet/modeling/architectures/yolo.py#L109-L116

**Comment by lucky-xu-1994** [comment]
> YOLO的后处理包含了yolo-box解码、以及NMS，
> 
> 1. 如果只不想包含nms，可以 转ONNX前的Paddle模型导出时，配置文件中去掉nms：
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/6220fd3a860e32596e6b83a9583a9ee58ef7424d/configs/yolov3/_base_/yolov3_mobilenet_v3_large.yml#L39-L44
> 
> 1. 如果yolo-box、nms都不想包含，需要修改源码，下面代码 return的output改成返回`yolo_head_outs`中的内容
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/6220fd3a860e32596e6b83a9583a9ee58ef7424d/ppdet/modeling/architectures/yolo.py#L109-L116

非常感谢，已经转成功了，谢谢！

**Comment by lucky-xu-1994** [comment]
您好，我已经成功转成了不带后处理的ONNX，如下图所示：
![1635840028(1)](https://user-images.githubusercontent.com/57120921/139808023-4d05ef6a-58df-4c84-af81-d983cb1e53f6.png)
请问，如何进行ONNX输出名称的修改？谢谢！

**Comment by jiangjiajun** [comment]
Hi @lucky-xu-1994 

请问你这里是出于什么需求要将模型转成ONNX格式呢？ 

另外目前在模型导出ONNX过程中，我们会将输入输出名与原模型保持一致（因此你这里会看到是scale_2.tmp_1这个输出名），为什么你需要修改输出名呢？

**Comment by lucky-xu-1994** [comment]
> Hi @lucky-xu-1994
> 
> 请问你这里是出于什么需求要将模型转成ONNX格式呢？
> 
> 另外目前在模型导出ONNX过程中，我们会将输入输出名与原模型保持一致（因此你这里会看到是scale_2.tmp_1这个输出名），为什么你需要修改输出名呢？

做模型的移植，目前是不可以自己定义输出的名字么？

**Comment by lucky-xu-1994** [comment]
非常感谢您的回复，目前直接修改ONNX文件来修改节点的名称，谢谢！
