### ISSUE TITLE
[Other General Issues]静态图的slim能用于动态图吗？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4413]
静态图的slim能用于动态图吗？
如果不行的话，动态图要如何剪枝呢？

**Comment by yghstill** [comment]
@zmdcs 可以参考：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/slim

**Comment by heavengate** [comment]
静态图的slim不能用于动态图，动态图剪枝可以参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/slim
