### ISSUE TITLE
[Other General Issues]labelme转coco数据格式时报错

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4426]
![image](https://user-images.githubusercontent.com/40875421/139808656-503f18df-f5fa-4107-83fe-5453ca6e72cd.png)
报错，为什么？

**Comment by heavengate** [comment]
看报错是没有读到你的labelme格式数据集annotation标注文件里的样本的`imageHeight`字段，可以排查一下你的数据集是否符合labelme的格式，是否包含imageHeight字段，以及是否是有个别样本没有标注这个字段

**Comment by zmdcs** [comment]
嗯，没有，我发现你们公司做的产品兼容性真的蛮差的，EsayDL出的数据压根不是labelme，可以跟他们反馈一下吗？能导入AIStudio倒是直接做成能用的数据格式呀！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 晚上8:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] [Other General Issues]labelme转coco数据格式时报错 (Issue #4426)





 
看报错是没有读到你的labelme格式数据集annotation标注文件里的样本的imageHeight字段，可以排查一下你的数据集是否符合labelme的格式，是否包含imageHeight字段，以及是否是有个别样本没有标注这个字段
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heavengate** [comment]
感谢反馈，我跟EasyDL反馈一下~

**Comment by zmdcs** [comment]
OK，感谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 晚上9:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] [Other General Issues]labelme转coco数据格式时报错 (Issue #4426)





 
感谢反馈，我跟EasyDL反馈一下~
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heavengate** [comment]
![image](https://user-images.githubusercontent.com/12605721/139853221-dfb3c841-6d80-4b56-bb90-e453919e0172.png)
你好，跟EasyDL的同学确认了下，labelme还不支持，但是支持COCO和VOC格式的，你可以直接导出这个格式就行，不用再转一遍

**Comment by zmdcs** [comment]
底下那个权限非常麻烦！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 晚上9:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] [Other General Issues]labelme转coco数据格式时报错 (Issue #4426)





 

 你好，跟EasyDL的同学确认了下，labelme还不支持，但是支持COCO和VOC格式的，你可以直接导出这个格式就行，不用再转一遍
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
