### ISSUE TITLE
[BUG]picodet

### ISSUE THREAD

**Issue by yu937861** [PaddlePaddle/PaddleDetection#4435]
python tools/train.py -c configs/picodet/picodet_l_416_coco.yml

featmap.shape[-2] * featmap.shape[-1] for featmap in cls_scores
AttributeError: 'list' object has no attribute 'shape'

**Comment by yghstill** [comment]
@yu937861 Fixed in https://github.com/PaddlePaddle/PaddleDetection/pull/4438
