### ISSUE TITLE
快速开始示例程序，为什么不是使用第一步中训练出来的模型，而是重新下载了一个呢？

### ISSUE THREAD

**Issue by gaooolianggg** [PaddlePaddle/PaddleDetection#444]
快速开始的示例程序中，在infer步骤识别橘子时，使用了`-o weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_mobilenet_v1_fruit.tar`，这样不就是使用了官方训练的模型，而没有使用第一步的模型了么

**Comment by qingqing01** [comment]
@gaooolianggg 文档中的命令是为了使得大家不训练也可以直接做预测。 您可以使用第一步训练得到的模型哈。

**Comment by gaooolianggg** [comment]
> @gaooolianggg 文档中的命令是为了使得大家不训练也可以直接做预测。 您可以使用第一步训练得到的模型哈。

谢谢，貌似自己训练这个效果没有你们提供的好

**Comment by qingqing01** [comment]
@gaooolianggg 您是保存的最好的模型测试的吗？
