### ISSUE TITLE
[Other General Issues]单卡训练PP-PicoDet，学习率设置

### ISSUE THREAD

**Issue by zwhua006** [PaddlePaddle/PaddleDetection#4453]
请问单卡训练PP-PicoDet ，学习率应该如何设置呢，默认应该是多卡训练。还有如果想在单卡上达到差不多的精度，bs和lr应该如何设置？

**Comment by yghstill** [comment]
@zwhua006 单卡的话，学习率除以4就行啦，因为是cosine decay策略，这个对模型收敛的影响不大，起始学习率避免过大有震荡即可。

**Comment by zwhua006** [comment]
那请问bs和lr的关系呢

**Comment by zwhua006** [comment]
如果我现在是单卡,bs为16的话，初始学习率设置为原来的1/8?

**Comment by yghstill** [comment]
@zwhua006 嗯嗯，可以的，bs减半lr也减半就行
