### ISSUE TITLE
save checkpoints

### ISSUE THREAD

**Issue by zwhua006** [PaddlePaddle/PaddleDetection#4454]
我发现snapshot_epoch如果设置为1的话，会每次评估，然后同时保存best,但是也会保存这一轮的权重。如果我想只保存best和最后一轮的权重，应该怎么修改。

**Comment by yghstill** [comment]
@zwhua006 如果只想保存best_model的话，删掉这段代码就行：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/engine/callbacks.py#L175-L182
