### ISSUE TITLE
PP-PicoDet-l

### ISSUE THREAD

**Issue by 10nger** [PaddlePaddle/PaddleDetection#4459]
你好，关于PP-PicoDet-l模型两个问题想问一下：
1.我发现在训练过程中使用了多尺度训练，但是在验证和测试的时候使用的是单一尺度，正常来说不应该是多尺度训练多尺度测试吗？
2.我发现数据增强部分仅仅采用了非常简单的增强，关于mosaic增强等并未使用到，是实验证明相应增强的效果并不理想吗？

**Comment by yghstill** [comment]
@10nger 
1. 测试时没有加multi scale test哈，如果加入multi scale test的话mAP会更高，但是目标检测一般情况默认单尺度评估，因为在部署时是统一input size部署的。
2. mosaic我们做了尝试的，在PicoDet S和M模型上是负向的，L模型不确定，一般小模型上过多的数据增强是负向的，大模型的话类似mosaic等都有不错的收益。
