### ISSUE TITLE
显存充足，但报错 out of memory

### ISSUE THREAD

**Issue by yinggo** [PaddlePaddle/PaddleDetection#446]
用cascade_rcnn_cbr200_vd_fpn_dcnv2_nonlocal_softnms.yml训练自己的数据集
显存充足，但报错 out of memory，请问该怎么解决这个问题？

> `python3 -u tools/train.py -c configs/dcn/cascade_rcnn_cbr200_vd_fpn_dcnv2_nonlocal_softnms.yml -o pretrain_weights=models/cascade_rcnn_cbr200_vd_fpn_dcnv2_nonlocal_softnms --use_tb=True --tb_log_dir=tb_log_caltech/scalar --eval

P.S. batch_size已经设置为1，
尝试多进程方式 python -m paddle.distributed.launch --selected_gpus 0,1,2,3 tools/train.py ...  也有同样的问题
实在不知道要怎么做了，求指教...

2020-04-06 17:36:49,707-INFO: 6707 samples in file dataset/coco/annotations/instances_val2007.json
2020-04-06 17:36:49,712-INFO: places would be ommited when DataLoader is not iterable
W0406 17:36:50.419684 27808 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.0, Runtime API Version: 10.0
W0406 17:36:50.422271 27808 device_context.cc:245] device: 0, cuDNN Version: 7.6.
2020-04-06 17:36:51,523-INFO: Loading parameters from models/cascade_rcnn_cbr200_vd_fpn_dcnv2_nonlocal_softnms...
2020-04-06 17:36:51,524-WARNING: models/cascade_rcnn_cbr200_vd_fpn_dcnv2_nonlocal_softnms.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-04-06 17:36:51,524-WARNING: models/cascade_rcnn_cbr200_vd_fpn_dcnv2_nonlocal_softnms.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
loading annotations into memory...
Done (t=0.20s)
creating index...
index created!
2020-04-06 17:36:53,468-WARNING: Found an invalid bbox in annotations: im_id: 5387, area: -10.0 x1: 348, y1: 176, x2: 348, y2: 196.
2020-04-06 17:36:53,481-WARNING: Found an invalid bbox in annotations: im_id: 5765, area: -10.0 x1: 71, y1: 174, x2: 71, y2: 197.
2020-04-06 17:36:53,686-INFO: 15649 samples in file dataset/coco/annotations/instances_train2007.json
2020-04-06 17:36:53,699-INFO: places would be ommited when DataLoader is not iterable
I0406 17:36:54.286912 27808 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 4 cards are used, so 4 programs are executed in parallel.
W0406 17:37:00.890586 27808 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 730. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 604.
I0406 17:37:01.025799 27808 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0406 17:37:28.992170 27808 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0406 17:37:29.978662 27808 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
W0406 17:37:42.174067   508 operator.cc:181] deformable_conv raises an exception paddle::memory::allocation::BadAlloc, 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
2   paddle::memory::allocation::AlignedAllocator::AllocateImpl(unsigned long)
3   paddle::memory::allocation::AutoGrowthBestFitAllocator::AllocateImpl(unsigned long)
4   paddle::memory::allocation::Allocator::Allocate(unsigned long)
5   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
6   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
7   paddle::memory::Alloc(paddle::platform::Place const&, unsigned long)
8   paddle::memory::Alloc(paddle::platform::DeviceContext const&, unsigned long)
9   paddle::framework::Tensor paddle::framework::ExecutionContext::AllocateTmpTensor<float, paddle::platform::CUDADeviceContext>(paddle::framework::DDim const&, paddle::platform::CUDADeviceContext const&) const
10  paddle::operators::DeformableConvCUDAKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
11  std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::DeformableConvCUDAKernel<paddle::platform::CUDADeviceContext, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
12  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
13  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
14  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
15  paddle::framework::details::ComputationOpHandle::RunImpl()
16  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
17  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
18  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
19  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
20  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 2. Cannot allocate 66.797119MB memory on GPU 2, available memory is only 31.062500MB.

Please check whether there is any other process using GPU 2.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 at (/paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
F0406 17:37:42.174147   508 exception_holder.h:37] std::exception caught, 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
2   paddle::memory::allocation::AlignedAllocator::AllocateImpl(unsigned long)
3   paddle::memory::allocation::AutoGrowthBestFitAllocator::AllocateImpl(unsigned long)
4   paddle::memory::allocation::Allocator::Allocate(unsigned long)
5   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
6   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
7   paddle::memory::Alloc(paddle::platform::Place const&, unsigned long)
8   paddle::memory::Alloc(paddle::platform::DeviceContext const&, unsigned long)
9   paddle::framework::Tensor paddle::framework::ExecutionContext::AllocateTmpTensor<float, paddle::platform::CUDADeviceContext>(paddle::framework::DDim const&, paddle::platform::CUDADeviceContext const&) const
10  paddle::operators::DeformableConvCUDAKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
11  std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::DeformableConvCUDAKernel<paddle::platform::CUDADeviceContext, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
12  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
13  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
14  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
15  paddle::framework::details::ComputationOpHandle::RunImpl()
16  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
17  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
18  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
19  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
20  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 2. Cannot allocate 66.797119MB memory on GPU 2, available memory is only 31.062500MB.

Please check whether there is any other process using GPU 2.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 at (/paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
*** Check failure stack trace: ***
    @     0x7fdb53276c2d  google::LogMessage::Fail()
    @     0x7fdb5327a6dc  google::LogMessage::SendToLog()
    @     0x7fdb53276753  google::LogMessage::Flush()
    @     0x7fdb5327bbee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fdb558509b8  paddle::framework::details::ExceptionHolder::Catch()
    @     0x7fdb558fc68e  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
    @     0x7fdb558fb29f  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
    @     0x7fdb558fb564  _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
    @     0x7fdb532cf983  std::_Function_handler<>::_M_invoke()
    @     0x7fdb5305dc37  std::__future_base::_State_base::_M_do_set()
    @     0x7fdb8dfe5a99  __pthread_once_slow
    @     0x7fdb558f6a52  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7fdb5305fe64  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7fdb7f27d3e7  execute_native_thread_routine_compat
    @     0x7fdb8dfde6ba  start_thread
    @     0x7fdb8dd1441d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

> nvidia-smi

Mon Apr  6 17:51:08 2020       

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 00000000:05:00.0  On |                  N/A |
| 26%   46C    P8    19W / 250W |    380MiB / 12188MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    Off  | 00000000:06:00.0 Off |                  N/A |
| 26%   46C    P8    18W / 250W |      2MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN X (Pascal)    Off  | 00000000:09:00.0 Off |                  N/A |
| 25%   44C    P8    19W / 250W |      2MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  TITAN X (Pascal)    Off  | 00000000:0A:00.0 Off |                  N/A |
| 23%   40C    P8    17W / 250W |      2MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1523      G   /usr/lib/xorg/Xorg                           215MiB |
|    0      3783      G   /opt/teamviewer/tv_bin/TeamViewer             41MiB |
|    0     12214      G   /usr/bin/nvidia-settings                       1MiB |
|    0     20941      G   compiz                                       109MiB |
|    0     26423      G   .../local/MATLAB/R2018a/bin/glnxa64/MATLAB     6MiB |
+-----------------------------------------------------------------------------+

`

**Comment by littletomatodonkey** [comment]
您好，这个模型比较大，是在32G的显卡上运行的~可以尝试一些较小的模型，或者减小训练的图像尺度

**Comment by yinggo** [comment]
> 您好，这个模型比较大，是在32G的显卡上运行的~可以尝试一些较小的模型，或者减小训练的图像尺度

谢谢，请问可以查询到模型对应的支持的显存大小吗？因为model zoo中看到cascade_rcnn_cbr200_vd_fpn_dcnv2_nonlocal_softnms在coco上表现最好，所以想用这个模型来训练，没想到对显卡内存要求这么高，我是在titanx 12G*4上面训练，请问能推荐下最大可运行的比较优秀的模型吗？（只做ap box不用mask，yolo系列精度有些偏低）

**Comment by littletomatodonkey** [comment]
不知道您对速度有什么要求呢？如果是在12G 的显卡训练，推荐resnet50_vd + fpn + dcn + cascade de 的组合方法，可以结合一些其他的训练策略，比如说auto augment，libra loss，iou loss等，继续提升性能，这些技巧都在config的配置里有对应的文件哈，您可以尝试组合一下~

**Comment by littletomatodonkey** [comment]
我们最近在master分支中提交了 V100下20fps的服务端实用检测模型，coco mAP能到47.8%，结合了上述的训练技巧，您也可以尝试一下~https://github.com/PaddlePaddle/PaddleDetection/blob/master/configs/rcnn_server_side_det/README.md

**Comment by yinggo** [comment]
@littletomatodonkey 非常感谢~ 速度要求不高，20fs可以接受的~
-------------------------
尝试cascade_rcnn_dcn_r50_vd_fpn_3x_server_side.yml出现另外一个错误：
Traceback (most recent call last):
  File "tools/train.py", line 323, in <module>
    main()
  File "tools/train.py", line 68, in main
    cfg = load_config(FLAGS.config)
  File "/home/ds1/anaconda3/envs/paddle/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/yaml/constructor.py", line 400, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/yaml/constructor.py", line 421, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!AutoAugmentImage'
  in "configs/rcnn_server_side_det/cascade_rcnn_dcn_r50_vd_fpn_3x_server_side.yml", line 127, column 5
-------------------------------
尝试把项目最新版本重新拉了一遍似乎还是报错

**Comment by littletomatodonkey** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/58d3349330d7447a606bea7384b87d588987a3e0/ppdet/data/transform/operators.py#L439

**Comment by yinggo** [comment]
> 您可以参考这里：代码是在master分支下面来着~
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/58d3349330d7447a606bea7384b87d588987a3e0/ppdet/data/transform/operators.py#L439

好的，谢谢~

**Comment by yinggo** [comment]
@littletomatodonkey 您好，模型似乎无法下载呢？https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_82.39_pretrained.tar 请帮忙确认下

File "/home/ds1/anaconda3/envs/paddle/PaddleDetection/ppdet/utils/download.py", line 276, in _download
    "{}!".format(url, req.status_code))
RuntimeError: Downloading from https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_82.39_pretrained.tar failed with code 404!

**Comment by littletomatodonkey** [comment]
您拉的应该不是最新的代码，最新的代码是这样哈：
https://github.com/PaddlePaddle/PaddleDetection/blob/e5137cb275391afd88ccdd2bf86022a4ba467ef4/configs/rcnn_server_side_det/cascade_rcnn_dcn_r50_vd_fpn_3x_server_side.yml#L8

这个预训练模型是我们基于蒸馏方案训练出来的，之后也会开源蒸馏方案，蒸馏方案的代码和文档会放在分类库中，欢迎star：https://github.com/PaddlePaddle/PaddleCLS

**Comment by yinggo** [comment]
> 您拉的应该不是最新的代码，最新的代码是这样哈：
> https://github.com/PaddlePaddle/PaddleDetection/blob/e5137cb275391afd88ccdd2bf86022a4ba467ef4/configs/rcnn_server_side_det/cascade_rcnn_dcn_r50_vd_fpn_3x_server_side.yml#L8
> 
> 这个预训练模型是我们基于蒸馏方案训练出来的，之后也会开源蒸馏方案，蒸馏方案的代码和文档会放在分类库中，欢迎star：https://github.com/PaddlePaddle/PaddleCLS

谢谢！在训练了！后续会继续尝试一些trick来帮助提升精度~（再次感谢您的指导^^解答真的好及时）

**Comment by yinggo** [comment]
@littletomatodonkey @qingqing01
您好，在使用yolo config训练的过程中，出现loss一直比较大的情况，感觉可能是没有很好的收敛？
（由于yolo预定义的数据大小是608x608。 我之前训练480x640的图片，最小loss在10-12左右；现在训练1024x2048的图片，最小loss在50左右，在iter 2w~3w的时候eval acc就不再增长了）
请问对于不同大小的输入图片yolo config中该如何调参？对于比较大长宽不等的图片该如何调参？求指教~！

**Comment by qingqing01** [comment]
@yinggo 

更改YOLO的长宽，可以在YML中TrainReader/EvalReader/TestReader中修改。另外，之前YOLO应该不支持长方形训练，后续的版本会支持。 由于时间较久了，暂且关闭了此issue。有问题，可以建新issue哈。
