### ISSUE TITLE
读取图片

### ISSUE THREAD

**Issue by DLUT-LYZ** [PaddlePaddle/PaddleDetection#4460]
我看到tools/infer里面只能是图片路径，但是我现在只有所得到numpy矩阵，如果变换成图片再次读，速度会下降。请问我该从哪里入手重写推理代码。

**Comment by yghstill** [comment]
@lllyyqq 部署不使用tools/infer，你是要在什么硬件下部署呢？ 需要使用https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy 里的代码

如果使用python部署，直接从numpy里读数据的话，直接修改decode_image 函数即可：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/python/preprocess.py#L19

**Comment by DLUT-LYZ** [comment]
def predict(self, image, threshold=0.5, warmup=0, repeats=1):
        '''
        Args:
            image (str/np.ndarray): path of image/ np.ndarray read by cv2
            threshold (float): threshold of predicted box' score
        Returns:
            results (dict): include 'boxes': np.ndarray: shape:[N,6], N: number of box,
                            matix element:[class, score, x_min, y_min, x_max, y_max]
        '''
        self.det_times.preprocess_time_s.start()
        inputs = self.preprocess(image)
        self.det_times.preprocess_time_s.end()
        input_names = self.predictor.get_input_names()

这里说image可以直接传入numpy数组，但是我使用下面的代码
model_dir = 'inference_model/picodet_l_640_coco'
pred_config = PredictConfig(model_dir)
detect = DetectorPicoDet(pred_config,model_dir,device='GPU')
img_path = 'demo/000002.jpg'
img = cv2.imread(img_path)
results = detect.predict(img)
是无法成功的，依旧是需要使用图片路径才能成功，一直报IndexError: tuple index out of range错误

**Comment by yghstill** [comment]
@lllyyqq 这里是支持直接传入numpy的，但是detect.predict传入的是list，需要是
```
results = detect.predict([img])
```
