### ISSUE TITLE
[Other General Issues]在windows系统部署paddleDetection预测没结果

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4470]
动态图用tools/infer.py 去预测，代码能运行成功，但是没有结果图片，按道理是应该保存在output文件夹下，可是就是没有。
![微信图片_20211104211949](https://user-images.githubusercontent.com/40875421/140320498-75c6dd66-68e8-45e6-84f1-928d16d8339a.jpg)
![微信图片_20211104212159](https://user-images.githubusercontent.com/40875421/140320776-ba0d5c08-4603-4f2c-8aa9-7b1206906c26.jpg)

**Comment by yghstill** [comment]
@zmdcs 可能因为你模型没有训好，导致infer没有结果输出，请使用eval.py脚本验证下模型的精度，没有结果输出应该增加提示信息，这个我们修复下。
