### ISSUE TITLE
Deploy issue

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#4482]
Hi, I want to deploy Picodet with openvino. but I meet an error as followed:
CMake Error at CMakeLists.txt:7 (find_package):
  By not providing "FindInferenceEngine.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "InferenceEngine", but CMake did not find one.

**Comment by yghstill** [comment]
@qdd1234 InferenceEngine is not configured successfully, please configure it again according to the document.
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/third_engine/demo_openvino/README.md
You also can download the installation package of openvino directly：
https://registrationcenter-download.intel.com/akdlm/irc_nas/18096/l_openvino_toolkit_p_2021.4.689.tgz
