### ISSUE TITLE
[Other General Issues] 如何更换优化器和

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#4493]
我现在在使用PaddleDetection的PPYOLOV2我想把学习率下降换成ReduceOnPlateau，优化器换成Adam

请问该如何操作

**Comment by lyuwenyu** [comment]
- `ReduceOnPlateau` 这个学习率调节策略目前是不支持的， 如果有兴趣的话可以考虑贡献一下 参考[optimizer.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/optimizer.py)里的代码
- 在optimizer里把type改成出`Adam` 可以参考这个[adamw](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/detr/_base_/optimizer_1x.yml#L15)
