### ISSUE TITLE
训练中断

### ISSUE THREAD

**Issue by wjplove8** [PaddlePaddle/PaddleDetection#4496]
[11/06 16:03:07] ppdet.utils.checkpoint INFO: Save checkpoint: output/yolov3_mobilenet_v1_270e_coco_ppk
INFO 2021-11-06 16:03:27,655 launch_utils.py:327] terminate all the procs
ERROR 2021-11-06 16:03:27,656 launch_utils.py:584] ABORT!!! Out of all 4 trainers, the trainer process with rank=[2] was aborted. Please check its log.
INFO 2021-11-06 16:03:30,659 launch_utils.py:327] terminate all the procs

**Comment by nemonameless** [comment]
batchsize多少呢，调小一点试试。
