### ISSUE TITLE
[Feature Request]   DetectoRS算法的支持

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleDetection#4502]
原论文DetectoRS在COCO上单尺度测试精度达到53.3mAP，而多尺度测试中达到目前所有文献报告的最高精度SOTA：54.7mAP！想学习这个递归特征金字塔对模型的改进，但自己代码能力比较弱，希望官方能给复现下原文的这个Neck：RFP(递归特征金字塔)

**Comment by nemonameless** [comment]
感谢建议，我们后续会讨论复现安排。
