### ISSUE TITLE
s2a net测试

### ISSUE THREAD

**Issue by fanxiaochen-123** [PaddlePaddle/PaddleDetection#4506]
在进行测试时，我选用的代码为release2.1，s2a net模型为s2anet_conv_1x_dota.pdparams，配置文件为s2anet_conv_1x_dota.yml，使用命令为python tools/infer.py -c configs/dota/s2anet_conv_1x_dota.yml -o weights=s2anet_conv_1x_dota.pdparams  --infer_dir=dota_test_images --draw_threshold=0.05 --save_txt=True --output_dir=output
paddlepaddle-gpu版本为2.0.1，paddledet版本为2.0.1，运行相应命令产生以下错误：
Traceback (most recent call last):
  File "tools/infer.py", line 161, in <module>
    main()
  File "tools/infer.py", line 157, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 135, in run
    save_txt=FLAGS.save_txt)
  File "C:\Users\admin\anaconda3\envs\padd2.0\lib\site-packages\ppdet\engine\trainer.py", line 399, in predict
    draw_threshold)
  File "C:\Users\admin\anaconda3\envs\padd2.0\lib\site-packages\ppdet\utils\visualizer.py", line 41, in visualize_results
    image = draw_bbox(image, im_id, catid2name, bbox_res, threshold)
  File "C:\Users\admin\anaconda3\envs\padd2.0\lib\site-packages\ppdet\utils\visualizer.py", line 118, in draw_bbox
    text = "{} {:.2f}".format(catid2name[catid], score)
KeyError: 12
请问这是什么原因呢，另外我也在release2.0的代码中测试，也是相同的错误，其中paddlepaddle采用命令测试显示安装成功。

**Comment by ghostxsl** [comment]
看报错信息，应该是anno_file没有正确加载之类的问题，你可以先尝试用2.3版本试一下，如果不行再从配置文件和anno_file入手调试一下

**Comment by fanxiaochen-123** [comment]
请问这个anno_file是在哪里呢

**Comment by ghostxsl** [comment]
你这个地方报错是在catid2name里没有找到对应的key，参考一下这里代码的实现：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/engine/trainer.py#L497
一般来说，他是会加载对应的anno_file：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/datasets/dota.yml#L19

**Comment by fanxiaochen-123** [comment]
好，我去试一下，我刚才在2.3的代码下尝试了，报了不一样的错误

**Comment by fanxiaochen-123** [comment]
我找到了，就是您说的那个anno_file里边的coco.json我没有，他这个是跟coco一样的80个类别吗还是什么

**Comment by ghostxsl** [comment]
如果没有的话，是会默认加载coco的标签的：https://github.com/PaddlePaddle/PaddleDetection/blob/531bca9dc886a0dc8873912fc80d8b3bca51bd44/ppdet/data/source/category.py#L56

**Comment by fanxiaochen-123** [comment]
嗯，您说的这些都是存在的，我在那里想尝试输出对应的东西，但是命令行执行之后他是没有东西输出的，就是代码没有走那里

**Comment by fanxiaochen-123** [comment]
imid2path = self.dataset.get_imid2path()
        print("imid2path:", imid2path)

        anno_file = self.dataset.get_anno()
        clsid2catid, catid2name = get_categories(
            self.cfg.metric, anno_file=anno_file)
就是trainer.py的这里

**Comment by fanxiaochen-123** [comment]
@ghostxsl ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
直接运行就会报这个错，是不是我的paddle版本与代码不匹配导致的

**Comment by fanxiaochen-123** [comment]
Package                           Version
--------------------------------- ---------
astor                             0.8.1
atomicwrites                      1.4.0
attrs                             21.2.0
Babel                             2.9.1
backports.entry-points-selectable 1.1.0
bce-python-sdk                    0.8.62
certifi                           2021.10.8
cfgv                              3.3.1
charset-normalizer                2.0.7
click                             8.0.3
colorama                          0.4.4
cycler                            0.11.0
Cython                            0.29.24
cython-bbox                       0.1.3
decorator                         4.4.2
distlib                           0.3.3
et-xmlfile                        1.1.0
filelock                          3.3.2
flake8                            4.0.1
flake8-import-order               0.18.1
Flask                             2.0.2
Flask-Babel                       2.0.0
future                            0.18.2
gast                              0.3.3
identify                          2.3.4
idna                              3.3
importlib-metadata                4.2.0
iniconfig                         1.1.1
itsdangerous                      2.0.1
Jinja2                            3.0.2
joblib                            1.1.0
kiwisolver                        1.3.2
lap                               0.4.0
MarkupSafe                        2.0.1
matplotlib                        3.4.3
mccabe                            0.6.1
motmetrics                        1.2.0
nodeenv                           1.6.0
numpy                             1.19.5
opencv-python                     4.5.1.48
openpyxl                          3.0.9
packaging                         21.2
paddledet                         2.0.1
paddlepaddle-gpu                  2.0.1
pandas                            1.3.4
Pillow                            8.4.0
pip                               21.2.4
platformdirs                      2.4.0
pluggy                            1.0.0
pre-commit                        2.15.0
protobuf                          3.19.1
py                                1.11.0
py-cpuinfo                        8.0.0
pycocotools                       2.0.2
pycodestyle                       2.8.0
pycryptodome                      3.11.0
pyflakes                          2.4.0
pyparsing                         2.4.7
pytest                            6.2.5
pytest-benchmark                  3.4.1
python-dateutil                   2.8.2
pytz                              2021.3
PyYAML                            6.0
rbox-iou-ops                      0.0.0
requests                          2.26.0
scikit-learn                      1.0.1
scipy                             1.7.2
setuptools                        42.0.0
Shapely                           1.8.0
six                               1.16.0
sklearn                           0.0
terminaltables                    3.1.0
threadpoolctl                     3.0.0
toml                              0.10.2
tqdm                              4.62.3
typeguard                         2.13.0
typing-extensions                 3.10.0.2
urllib3                           1.26.7
virtualenv                        20.10.0
visualdl                          2.1.0
Werkzeug                          2.0.2
wheel                             0.37.0
wincertstore                      0.2
xmltodict                         0.12.0
zipp                              3.6.0
这是我程序的运行环境，CUDA10.1

**Comment by fanxiaochen-123** [comment]
@ghostxsl 您好，我照您说的修改那个之后，它产生了新的报错，
Traceback (most recent call last):
  File "tools/infer.py", line 158, in <module>
    main()
  File "tools/infer.py", line 154, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 132, in run
    save_txt=FLAGS.save_txt)
  File "C:\Users\admin\anaconda3\envs\padd2.0\lib\site-packages\ppdet\engine\trainer.py", line 368, in predict
    clsid2catid, catid2name = get_categories(self.cfg.metric, anno_file)
  File "C:\Users\admin\anaconda3\envs\padd2.0\lib\site-packages\ppdet\data\source\category.py", line 42, in get_categories
    from pycocotools.coco import COCO
  File "C:\Users\admin\anaconda3\envs\padd2.0\lib\site-packages\pycocotools\coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "C:\Users\admin\anaconda3\envs\padd2.0\lib\site-packages\pycocotools\mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools\_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
他的报错地方指向了下边这个地方
  if metric_type.lower() == 'coco':
        if anno_file and os.path.isfile(anno_file):
            # lazy import pycocotools here
            from pycocotools.coco import COCO

            coco = COCO(anno_file)
            cats = coco.loadCats(coco.getCatIds())

            clsid2catid = {i: cat['id'] for i, cat in enumerate(cats)}
            catid2name = {cat['id']: cat['name'] for cat in cats}

            return clsid2catid, catid2name

请问这个还是您说的那个错吗

**Comment by ghostxsl** [comment]
看起来要么环境有问题，要么anno_file有问题，建议单独写个单测看一下问题在哪

**Comment by fanxiaochen-123** [comment]
@ghostxsl 那个anno_file他加载的json文件是我自己加上的，之前的错误就消失了，环境的话就是按照官网配置的，paddlepaddle:2.0.1，paddledet：2.0.1，您说的写单测是测试环境吗

**Comment by ghostxsl** [comment]
是这样的，首先，之前的错误是因为没有加载对应数据集的标签，默认调用的是coco的标签格式；其次你增加anno_file以后报的错有可能是你的pycocotools包没正确安装，但如果是你之前确定这个包是正确的话，那就只有是你自己添加的json文件有问题，你可以自己再检查一下，这个问题应该跟paddle和paddledet的版本没有太大关系～
