### ISSUE TITLE
[Feature Request] kaiming_normal_(m.weight, mode='fan_out')

### ISSUE THREAD

**Issue by sayoko17** [PaddlePaddle/PaddleDetection#4509]
kaiming_normal_(m.weight, mode='fan_out') 这个在paddle里面是如何实现的呢？在文档里只看到 fan_in的，没有看到fan_out，求求解答谢谢

**Comment by ghostxsl** [comment]
可以参考： https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/modeling/initializer.py#L246
