### ISSUE TITLE
BoxInst的支持

### ISSUE THREAD

**Issue by TimZhang001** [PaddlePaddle/PaddleDetection#4514]
希望能够支持Boxinst，我测试了效果很好，可以解决工业标注的问题。麻烦考虑一下呀！！！！！
https://github.com/aim-uofa/AdelaiDet/blob/master/configs/BoxInst/README.md
BoxInst: High-Performance Instance Segmentation with Box Annotations

**Comment by qingqing01** [comment]
收到需要，感谢建议。我们评估下。
