### ISSUE TITLE
[Other General Issues]SSLD知识蒸馏可以用于目标检测吗？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4517]
我查看官方文档，ssld好像是用于分类的，那用于目标检测有用吗？

**Comment by qingqing01** [comment]
目标检测也有半监督的训练方法，用法类似，用有标签数据训练的teacher，给无标签数据打伪标签，再利用这些数据训练student。可以参考Soft Teacher论文  https://arxiv.org/abs/2106.09018
