### ISSUE TITLE
[Other General Issues]ppyolo训练读取数据报错

### ISSUE THREAD

**Issue by ZiQiangXie** [PaddlePaddle/PaddleDetection#4518]
aistudio项目，paddle=2.1.2.post101，PaddleDetection为2.2版本。训练时报错：
![2021-11-09_120643](https://user-images.githubusercontent.com/59564630/140861304-134124a3-5a58-4720-a685-6d7bc91c7d64.jpg)

**Comment by qingqing01** [comment]
@ZiQiangXie  您的数据格式什么？看起来是feed给DataLoader的数据格式不对。

**Comment by ZiQiangXie** [comment]
@qingqing01 感谢，我的是开源的一个数据集，我转成Coco格式了。我检查了生成的数据，但是没找到问题。然后换了一个转换脚本，生成的结果可以正常训练。
