### ISSUE TITLE
请问对于FairMOT的自定义数据集训练有可以使用的标注工具吗？

### ISSUE THREAD

**Issue by Ranger-D** [PaddlePaddle/PaddleDetection#4520]

**Comment by qingqing01** [comment]
1. EasyDL在线标注，标注数据不支持导出： https://ai.baidu.com/ai-doc/EASYDL/wkqj1q8cs
2. 离线标注工具，可以参考 https://github.com/openvinotoolkit/cvat
  https://openvinotoolkit.github.io/cvat/docs/manual/advanced/formats/format-mot/

**Comment by Ranger-D** [comment]
非常感谢您的解答，请问一下在FairMOT要求的数据格式中，track_id是指在这一场景中出现的数量的ID号吗？

**Comment by nemonameless** [comment]
> 非常感谢您的解答，请问一下在FairMOT要求的数据格式中，track_id是指在这一场景中出现的数量的ID号吗？

自定义跟踪数据集制作可以参照 
 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/PrepareMOTDataSet_cn.md
需要和MOT16 MOT17数据集的格式一样。
在训练标注中identity(即id标签)是指每一个不同的人有一个不同id号，eval或infer的时候的跟踪结果的track_id也是不同的人有一个不同id号，前一帧后一帧同一个人是相同的id号

**Comment by Ranger-D** [comment]
非常感谢
