### ISSUE TITLE
[Other General Issues] 如何安装静态图版本的pp det？

### ISSUE THREAD

**Issue by YilanWang** [PaddlePaddle/PaddleDetection#4522]
如题。
顺便，其实之前有挺多好用的模型，比如openimage det，obj365的，直接trans一个到动态版本的其实更好，个人意见，诚惶诚恐~

**Comment by qingqing01** [comment]
@YilanWang 直接`cd static`文件，和原来的一样方式使用即可，可以pip uninstall 已安装的动态图版本。 感谢建议，我们后续转换下这些模型到动态图吧。
