### ISSUE TITLE
自编译的c++推理库推理模型报错

### ISSUE THREAD

**Issue by sp-ljw** [PaddlePaddle/PaddleDetection#4523]
我训练了一个ppyolo_mbv3_large_coco模型，自定义了数据和类别，可以成功通过Infer.py推理 。
训练环境如下：
```
PaddleDetection ->  release-2.2
PaddlePaddle  -> paddlepaddle-gpu 2.1.3
cuda 10.1,  cudnn7.6.5
```

接着我，把该模型放到cpu环境进行推理，使用的是**自己编译的paddle inference库**进行推理
以下是自己编译的paddle inference库编译和模型运行环境
```
centos7
gcc/g++=4.8.5,
cpu环境
基于paddlepaddke-realease-2.0编译)
```

以下是gcc4.8.5推理库version信息
```
GIT COMMIT ID: 2a7c2cf8f32541f3c7691b852bd4a8fe48505294
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: OFF
CXX compiler version: 4.8.5
```

然后推理ppyolo_mbv3_large_coco模型报错,报错信息如下：
```
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/data/upfconlas6/ljw_develop/deep_learn_detect/PaddleDetection-release-2.2/ppdet/modeling/necks/yolo_fpn.py", line 37, in add_coord
      gx = gx.reshape([1, 1, 1, w]).expand([b, 1, h, w])
    File "/root/baidu_paddle/lib/python3.6/site-packages/paddle/tensor/manipulation.py", line 1502, in expand
      type='expand_v2', inputs=inputs, outputs={'Out': out}, attrs=attrs)
    File "/root/baidu_paddle/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/root/baidu_paddle/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2967, in append_op
      attrs=kwargs.get("attrs", None))
    File "/root/baidu_paddle/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2039, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::operators::ExpandV2Op::InferShape(paddle::framework::InferShapeContext*) const
6   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
7   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The 0th element of 'shape' for expand_v2 op must be greater than 0, but the value given is -2.
  [Hint: Expected expand_shape[i] > 0, but received expand_shape[i]:-2 <= 0:0.] (at /home/sqwang/test/Paddle/paddle/fluid/operators/expand_v2_op.cc:75)
  [operator < expand_v2 > error]
Aborted
```

我用官网上的库（库信息如下）并在gcc8环境下是能够推理出来的，没有问题，但是工程化环境必须gcc4.8.5和低版本GLIBC才行。
```
GIT COMMIT ID: 1e62c239d323354eccfc974d4e2e6496f93d848e
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
WITH_ROCM: OFF
CUDA version: 10.1
CUDNN version: v7.6
CXX compiler version: 5.4.0
WITH_TENSORRT: ON
TensorRT version: v6
```

请问一下这个报错的原因是什么，有没有解决方法？

**Comment by wangxinxin08** [comment]
您好，可以编译最新的Paddle版本试一下，推荐使用PaddlePaddle release/2.2rc或者release/2.1

**Comment by sp-ljw** [comment]
> 您好，可以编译最新的Paddle版本试一下，推荐使用PaddlePaddle release/2.2rc或者release/2.1

从release/2.1版本开始要求gcc版本必须大于等于5.4，但是我的工程要求4.8.5，在底层GLIBC上不匹配，无法使用最新的进行编译。是否我可以修改2.1的flags.cmake把5.4的限制拿掉？或者有没有其他的方法呢

**Comment by wangxinxin08** [comment]
> > 您好，可以编译最新的Paddle版本试一下，推荐使用PaddlePaddle release/2.2rc或者release/2.1
> 
> 从release/2.1版本开始要求gcc版本必须大于等于5.4，但是我的工程要求4.8.5，在底层GLIBC上不匹配，无法使用最新的进行编译。是否我可以修改2.1的flags.cmake把5.4的限制拿掉？或者有没有其他的方法呢

可以尝试下把gcc的版本限制拿掉，或者使用对应的PaddleDetection版本试下，比如尝试下PaddleDetection release/2.0试下

**Comment by sp-ljw** [comment]
> 可以尝试下把gcc的版本限制拿掉，或者使用对应的PaddleDetection版本试下，比如尝试下PaddleDetection release/2.0试下

1.我把限制拿掉但是在“CHECK_CXX_SYMBOL_EXISTS(UINT64_MAX "stdint.h" UINT64_MAX_EXISTS)”这一步不过，估计有c++14兼容问题。
2.请问这里指我是用PaddleDetection release/2.0再训练一次模型试试是吗？

**Comment by wangxinxin08** [comment]
> > 可以尝试下把gcc的版本限制拿掉，或者使用对应的PaddleDetection版本试下，比如尝试下PaddleDetection release/2.0试下
> 
> 1.我把限制拿掉但是在“CHECK_CXX_SYMBOL_EXISTS(UINT64_MAX "stdint.h" UINT64_MAX_EXISTS)”这一步不过，估计有c++14兼容问题。 2.请问这里指我是用PaddleDetection release/2.0再训练一次模型试试是吗？

不用训练，使用PaddlePaddle release/2.0和PaddleDetection release/2.0直接导出试试

**Comment by sp-ljw** [comment]
> 不用训练，使用PaddlePaddle release/2.0和PaddleDetection release/2.0直接导出试试

切换为PaddleDetection release/2.0以后，我重新把在detection2.2训练的模型在detection2.0里面export以后，再在自己编译的2.0推理库里推理就成功了，十分感谢！

**Comment by wangxinxin08** [comment]
> > 不用训练，使用PaddlePaddle release/2.0和PaddleDetection release/2.0直接导出试试
> 
> 切换为PaddleDetection release/2.0以后，我重新把在detection2.2训练的模型在detection2.0里面export以后，再在自己编译的2.0推理库里推理就成功了，十分感谢！。

好的，你可以先看下精度是否正常(精度如果不正常的话，可能是参数的名称发生了改变，不过这个模型参数的名字应该没有变化)，因为PaddleDetection会随着PaddlePaddle版本升级而升级，所以在**部署**的时候最好能对应版本使用
