### ISSUE TITLE
[Other General Issues]动态图剪枝可以自己配yml文件吗?

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4526]
1.动态图剪枝可以自己配yml文件吗?
2.没有敏感度分析的话,能不能用静态图的敏感度分析方法分析卷积层名称以及剪枝比例?
3.量化和蒸馏能不能直接自己配yml文件呢?

**Comment by qingqing01** [comment]
1.  动态图剪枝可以依据您选的模型，自己配置yml， 具体的可以参考中yolov3模型，可以配置FPGM、L1Norm等，推荐FPGM剪枝  https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/slim/prune 

2. 也是可以用静态图作为分析，动态图用。就是麻烦些。

3. 量化和蒸馏也是可以自己配置yml，参考下面文件，当前只支持了yolov3/ppyolo系列模型蒸馏，其他模型蒸馏不一定适用
 
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/slim/extensions/yolov3_mobilenet_v1_coco_distill_prune.yml
