### ISSUE TITLE
请问大佬们，picodet模型用paddlelite和openvino哪里推理速度更快，在windows平台上

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#4529]

**Comment by yghstill** [comment]
@Dandelion111 Paddle Lite在嵌入式移动端设备上性能优化较好，Openvino在intel cpu上性能优化较好，可以实际测下速度。

**Comment by Dandelion111** [comment]
> @Dandelion111 Paddle Lite在嵌入式移动端设备上性能优化较好，Openvino在intel cpu上性能优化较好，可以实际测下速度。

好的，谢谢大佬
