### ISSUE TITLE
Yolov3模型配置不一致问题

### ISSUE THREAD

**Issue by ZhenguoYuan** [PaddlePaddle/PaddleDetection#453]
为什么dcn中yolov3_enchance_reader.yml中is_scale是False 而yolov3_reader.yml的is_scale却是True

**Comment by jerrywgz** [comment]
在yolov3_enchance_reader.yml里采用的is_scale是True和False之前验证的结论是对精度影响不大，我们再做下完整的验证，后续会把is_scale统一成True

**Comment by ZhenguoYuan** [comment]
好的 谢谢
