### ISSUE TITLE
麻烦给一个mask rcnn训练自定义数据集的说明文档或者例子吧

### ISSUE THREAD

**Issue by cloudsurging** [PaddlePaddle/PaddleDetection#4530]
## 📖  文档优化/Documentation Improvement

**请简单说明文档存在问题/Please provide a concise and brief description of the documentation problem:**

**请提供有问题的文档部分截图及链接/Please provide the screen shoot and the link of the document:**

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/PrepareDataSet.md#用户数据
自定义数据集的话可以参考这个~
