### ISSUE TITLE
如何在eval过程中获得train_reader同样的预处理

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#4531]
最近在进行TTFNet的相关应用，今天想要在eval的过程中获取数据的预处理结果：ttf_heatmap、ttf_box_target，但是好像只是修改reader.yml文件中的EvalReader配置好像没有用：
![image](https://user-images.githubusercontent.com/59326436/141040605-b9d7771f-4b4a-4bf1-8ac5-576f042e12fa.png)
![image](https://user-images.githubusercontent.com/59326436/141040916-bfbfe947-bec9-4ba8-a000-5f4a9221d50f.png)
可能是evalreader不会去读取gt_box？我在trainer.py中看了半天希望将eval_reader修改为train_reader也无济于事，请问要怎么操作才能够在eval过程中获取预处理结果？

期待您的回复！

**Comment by heavengate** [comment]
`configs/datasets`目录下对应的数据集文件，参考`TrainDataset`配置一下`data_fields`
https://github.com/PaddlePaddle/PaddleDetection/blob/d9187ad5d054bc8a4333b9a8ba686569be91a8c6/configs/datasets/coco_detection.yml#L9

**Comment by ghost** [comment]
> `configs/datasets`目录下对应的数据集文件，参考`TrainDataset`配置一下`data_fields`
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/d9187ad5d054bc8a4333b9a8ba686569be91a8c6/configs/datasets/coco_detection.yml#L9

已解决！感谢您的回复！
