### ISSUE TITLE
[Other General Issues] 使用cascade报错

### ISSUE THREAD

**Issue by YilanWang** [PaddlePaddle/PaddleDetection#4538]
paddlepaddle版本：2.00rc
det版本：release0.5
当使用 **configs/obj365/cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas.yml**
会报错
/data1/wangyilan/code/PaddleDetection/ppdet/utils/voc_utils.py:70: DeprecationWarning: invalid escape sequence \.
  elif re.match('test\.txt', fname):
/data1/wangyilan/code/PaddleDetection/ppdet/utils/voc_utils.py:68: DeprecationWarning: invalid escape sequence \.
  if re.match('trainval\.txt', fname):
/data1/wangyilan/code/PaddleDetection/ppdet/core/workspace.py:118: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  isinstance(merge_dct[k], collections.Mapping)):
Traceback (most recent call last):
  File "tools/infer.py", line 271, in <module>
    main()
  File "tools/infer.py", line 117, in main
    inputs_def = cfg['TestReader']['inputs_def']
KeyError: 'inputs_def'

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/4553
参考这个pr本地修改下应该就可以了~
