### ISSUE TITLE
输入处理的差异

### ISSUE THREAD

**Issue by chenyanghe** [PaddlePaddle/PaddleDetection#4539]
你好，我想请问，deploy/python文件夹里infer.py代码，def predict(self, image_list, threshold=0.5, warmup=0, repeats=1)，其中image_list是list of image，之前2.0-beta版本直接可以传入np.ndarray数据类型，现在2.1版本如果想把传参list of image类型改为np.ndarray，怎么修改啊？麻烦指导一下

**Comment by heavengate** [comment]
没太理解你的意思，`predict`函数里的image_list里的是image的路径，读image是在preprocess里做的
