### ISSUE TITLE
使用python dataset/voc/create_list.py -d dataset/voc/VOCdevkit/VOC2012/ImageSets/Main/指令生成的txt是空白的

### ISSUE THREAD

**Issue by WindMirror1108** [PaddlePaddle/PaddleDetection#4544]
使用了python dataset/voc/create_list.py -d dataset/voc/VOCdevkit/VOC2012/ImageSets/Main/指令
出来的txt是空白的。

更改了ppdet/utils/voc_utils.py 的第67和69行：
if re.match(r'trainval.txt', fname):

elif re.match(r'test.txt', fname):

使用的数据集是Pascal VOC格式

Windows10 
CUDA 11.2

**Comment by jerrywgz** [comment]
感谢反馈！看了下voc annotation的标注文件格式是以_trainval.txt或者_test.txt结尾的，你这里使用的是VOC原始数据格式吗？
