### ISSUE TITLE
PaddleDetection运行出现 paddlepaddle is not compiled with cuda

### ISSUE THREAD

**Issue by InstantWindy** [PaddlePaddle/PaddleDetection#4551]
系统：windows10
Cuda:11.2
python:3.8
通过 pip install paddlepaddle-gpu==2.1.3.post112安装，然后git clone https://github.com/PaddlePaddle/PaddleDetection.git, 
cd PaddleDetection执行python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg命令出现the device should not be 'gpu' paddlepaddle is not compiled with cuda 错误

**Comment by jerrywgz** [comment]
在安装完paddle后，可以执行
```
import paddle
paddle.utils.run_check()
```
检查是否安装正常
