### ISSUE TITLE
加载configs/yolov3_darknet.yml测试出现 keyerror: no key testDataset 

### ISSUE THREAD

**Issue by InstantWindy** [PaddlePaddle/PaddleDetection#4555]
通过运行命令python tools/infer.py -c configs/yolov3_darknet.yml -o weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet.tar --infer_img=demo/000000014439.jpg出现以下错误：
    keyerror: no key testDataset ,报的错误是出现在 ppdet / engine / trainer.py文件中的66行[](https://gitee.com/paddlepaddle/PaddleDetection/blob/release/2.2/ppdet/engine/trainer.py)

- [ ]

**Comment by jerrywgz** [comment]
是否修改过dataset部分的配置文件呢

**Comment by InstantWindy** [comment]
没有修改过，加载的是static/config/yolov3_darknet.yml文件

**Comment by alanzhai219** [comment]
anyone can fix it?
