### ISSUE TITLE
如何导出No-Combined格式模型

### ISSUE THREAD

**Issue by ponycloud235** [PaddlePaddle/PaddleDetection#4556]
rt,如何导出No-Combined 模型，在使用paddle-lite 需要导出No-Combined 进行部署

**Comment by jerrywgz** [comment]
可以使用tools/export_model.py将模型导出，步骤参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/GETTING_STARTED_cn.md#8-%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA

**Comment by ponycloud235** [comment]
> 可以使用tools/export_model.py将模型导出，步骤参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/GETTING_STARTED_cn.md#8-%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA

不行，这里只能设置导出Combined 模型。

**Comment by jerrywgz** [comment]
https://paddle-lite.readthedocs.io/zh/latest/user_guides/opt/opt_bin.html#paddle-lite 可以参考这里的文档，paddle-lite可以通过--model-file和==param_file使用combined的模型

**Comment by ponycloud235** [comment]
> https://paddle-lite.readthedocs.io/zh/latest/user_guides/opt/opt_bin.html#paddle-lite 可以参考这里的文档，paddle-lite可以通过--model-file和==param_file使用combined的模型

谢谢 我试试combined模型。
