### ISSUE TITLE
[Feature Request]适配YOLO-FastestV2数据集格式

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#4557]
## 🚀  新功能/Feature

PaddleDetection欢迎大家以清晰简洁的语言提出新功能需求。

A clear and concise description of the feature proposal.

## 需求原因&示例/Motivation & Examples

我当前有训练集和验证集，具体格式如下图所示，如何转成YOLOX可训练的数据格式？
![image](https://user-images.githubusercontent.com/78945582/141277452-9823f80a-ccf7-4f2d-b403-8fe89ddb69ff.png)

其中，txt格式如下所示
class_id                 cx/w                      cy/h                                 box_w/w                            box_h/h
0            0.510814878287011 0.33199194073677063    0.04678068331669093    0.12072434276342392

Tell us why the feature is useful.

请描述这个需求可实现的具体功能，如果可以，辛苦您提供相关代码实现效果。

Describe what the feature would look like, if it is implemented.
Best demonstrated using **code examples** in addition to words.

## 📣 注意/Note

PaddleDetection仅添加通用性较高的新功能/特性。

We only consider adding new features if they are relevant to many users.

如果您需要论文中的模型能力，PaddleDetection会优先考虑与目标检测强相关且意义较大的论文。

If you request implementation of research papers -- we only consider papers that have enough significance and prevalence in the object detection field.

比如“让XX功能更快”类似的需求不能作为一个有效需求，需要更具体的描述，如“创建一个具体XX工具/功能，让XX更快”即是一个有效需求。

"Make X faster/accurate" is not a valid feature request. "Implement a concrete feature that can make X faster/accurate" can be a valid feature request.

PaddleDetection感谢您的支持，我们期待您提出新功能需求！

Thanks for your suggestions!

**Comment by jerrywgz** [comment]
目前我们还不支持这种数据集格式的读取或者转换，可以尝试参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/tools/x2coco.py 将其他数据格式转化为coco，也可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/data/source/coco.py 新建一个dataset来读取这个数据格式。我们也会评估下这个数据格式，感谢反馈

**Comment by yghstill** [comment]
@lixiangMindSpore 如果有使用轻量级模型的需求，欢迎试用新SOTA模型PP-PicoDet模型：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet
