### ISSUE TITLE
运行sensitive.py报错ModuleNotFoundError: No module named 'ppdet.modeling.model_input'

### ISSUE THREAD

**Issue by dongfuyeah** [PaddlePaddle/PaddleDetection#456]
在0.2的PaddleDetection中没有model_input.py，而在0.1中有

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/slim/sensitive/sensitive.py 在0.2分支下是不需要model_input.py的，你现在使用的检测库版本是0.2吗

**Comment by dongfuyeah** [comment]
谢谢，新版本fix了，我是几天前git clone 的版本出现问题了
