### ISSUE TITLE
是否支持Python API开发？

### ISSUE THREAD

**Issue by ucsk** [PaddlePaddle/PaddleDetection#4560]
PaddleDetection 有无和 [PaddleSeg](https://paddleseg.readthedocs.io/zh_CN/release-2.1/apis/index.html) 类似的API开发接口用于代码实现？而非仅在 `.yml` 中完成项目配置？

**Comment by yghstill** [comment]
@ucsk 有这个功能，但是目前还没有开放文档，感谢反馈，我们看下能否补充下文档。
