### ISSUE TITLE
Openvino deploy issue

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#4562]
Hi, I follow the instruction about deploying for picodet with openvino. But when I finish making and run the code for prediction, I meet an issue as followed. How can I solve it
Issue:
sudo: picodet_demo：找不到命令

Besides, I have seen "Built target picodet_demo"

**Comment by yghstill** [comment]
@qdd1234 先进入到build下再执行
```shell
cd build
./picodet_demo 1 ../test.jpg
```
