### ISSUE TITLE
nms 为什么没有把重叠得box去掉？

### ISSUE THREAD

**Issue by jeffzhengye** [PaddlePaddle/PaddleDetection#4566]
下图中有两个button-off 重叠在一起， nms 应该可以去掉一个啊。
我的配置如下：

BBoxPostProcess:
  decode:
    name: YOLOBox
    conf_thresh: 0.005
    downsample_ratio: 32
    clip_bbox: true
  nms:
    name: MultiClassNMS
    keep_top_k: 30
    score_threshold: 0.4
    nms_threshold: 0.4
    nms_top_k: 1000

![image](https://user-images.githubusercontent.com/4641009/141455318-6735e86e-6ba2-4ae9-9968-86c9ecd54fdf.png)

**Comment by qingqing01** [comment]
1. 可以通过调节NMS的阈值控
2. 也可以输出的后，通过阈值控制: 
https://github.com/PaddlePaddle/PaddleDetection/blob/0e74bbc07d86cbe4bf34eb947cb288bc773ca5eb/tools/infer.py#L60-L63

**Comment by jeffzhengye** [comment]
@qingqing01  已经加了阈值啊。但是还是输出了，比如就这个例子，阈值应该写多少？

**Comment by qingqing01** [comment]
您把输出的阈值控制到0.59看下。

**Comment by jeffzhengye** [comment]
如果这样的话，nms 就没必要了

**Comment by lyy1988323** [comment]
可以计算一下这两个button-off的iou，估计他俩的iou低于0.4
