### ISSUE TITLE
[BUG] Wrong Model pdparams and yml for Yolo MobileNet-V3 320 model

### ISSUE THREAD

**Issue by franva** [PaddlePaddle/PaddleDetection#4570]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## 描述问题/Describe the bug
On the page [Yolov3](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/yolov3), 
for model: 

MobileNet-V3 | 320 | 8 | 270e | - | 76.4 for Pasacl VOC, the pdparams and its yml files are still pointing to the large model which has input size 608*608

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
![image](https://user-images.githubusercontent.com/5151146/141544067-4de3753a-3154-42aa-96aa-2ea0bbfceb68.png)

No need for any command, just go to that page(https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/yolov3)
and download the pdparams and yml files.

You will notice that no matter which model you choose(i.e. 320, 416, etc), the links are all pointing to the "https://paddledet.bj.bcebos.com/models/yolov3_mobilenet_v3_large_270e_voc.pdparams" and "https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/yolov3/yolov3_mobilenet_v3_large_270e_voc.yml" which are for the large model.

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
![image](https://user-images.githubusercontent.com/5151146/141551682-9706b427-5e5c-475e-acab-f048b6ee8e10.png)

**Comment by qingqing01** [comment]
In YOLOv3, thed trained model by multi-scale can be predicted in 608, 416, 320 scale.  The mAP on shape of 608, 416, 320 is the same model
