### ISSUE TITLE
Deployment for Picodet with openvino

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#4571]
Hi, I have a suggestion for openvino deployment that when we convert our onnx model to openvino, the code should be modified as followed:
python3 mo_onnx.py --input_model <onnx model path> --input_shape [1,3,416,416] --mean_values [103.53,116.28,123.675] --scale_values [57.375,57.12,58.395].

Compared with official code, the modified code add input shape. Because when I run the official code, I meet an issue which prompts me that input shape is wrong, but It is official code, I don not make any changes. I hope you can add input shape to origin code which may help perfect the documents, Thanks!

**Comment by yghstill** [comment]
@qdd1234 Thanks for your suggestion, we will fix it soon.
