### ISSUE TITLE
Train和Eval中出现了一些问题

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#4579]
此前的训练都好好的，今天下午回来终止了一次结果不太好的训练，本来想评估一下，结果疯狂JsonDecoderError（前天刚跑过一样的，啥事没有），随后想开启训练看看训练中Eval正常不，结果发现训练也爆炸了：本来使用Num_workers=9进行训练，现在使用和以前一样的配置开启训练会发现显卡会处于待命状态，显存维持在一个较低值不动，始终无法开始训练，调整成num_workers=1后发现可以，Eval也正常，但是我现在根本没法像以前一样正常使用了！
请问这到底是什么问题？我服务器的问题嘛？可是我看了内存和CPU都还很充足，就是无法正常训练，而且使用eval也还是报错（但是训练中eval没问题）

**Comment by wangxinxin08** [comment]
eval报错的截图可以发一下

**Comment by ghost** [comment]
@wangxinxin08 
感谢您的回复！log如下：
![image](https://user-images.githubusercontent.com/59326436/141650437-8fa8b5ff-f589-4837-94c0-2c89d4af0b3b.png)

**Comment by wangxinxin08** [comment]
评估结果默认会保存在bbox.json文件中，如果同时读写这个文件会导致文件错误，从而无法读取，从报错上来看应该是这个问题

**Comment by ghost** [comment]
> 评估结果默认会保存在bbox.json文件中，如果同时读写这个文件会导致文件错误，从而无法读取，从报错上来看应该是这个问题

@wangxinxin08 感谢您的回复，可是我没有对bbox.json进行任何操作，我每次eval之前哪怕把它删除了，任由代码重新创建也是会出现这个问题，请问到底该如何修复或直接跳过这个文件的保存？而且我在训练过程中的eval他全都是正常的，bbox.json也是正常生成的，真不知如何是好。

**Comment by wangxinxin08** [comment]
一般避免同时评估代码即可，不行的话，可以升级下pycocotools这个包
