### ISSUE TITLE
量化后的yolo3_mobilenet_v1模型在PaddleLite上使用提示No kernels found for conv2d

### ISSUE THREAD

**Issue by rupei110** [PaddlePaddle/PaddleDetection#458]
![1](https://user-images.githubusercontent.com/50095586/78742031-8069fa00-798d-11ea-9ad1-c74bed19ea6d.png)

**Comment by willthefrog** [comment]
确认下lite是否最新版本吧。另外，这个issue建议提到[lite的repo](https://github.com/PaddlePaddle/Paddle-Lite), 感觉不是PaddleDetection的问题，你单独跑mobilenet可以正常运行吗？

**Comment by willthefrog** [comment]
另外，你是在model转换时报的错吗？如果是可以加上 `--prefer_int8_kernel=true`试下
