### ISSUE TITLE
train log

### ISSUE THREAD

**Issue by www516717402** [PaddlePaddle/PaddleDetection#4587]
how to get pp-yolo-v2 train log? I meet some error in train and consider compare log to official log.

**Comment by wangxinxin08** [comment]
here is ppyolov2 train log [ppyolov2_r50vd_dcn.log](https://github.com/PaddlePaddle/PaddleDetection/files/7542955/ppyolo_r50vd_491.log)，which is originally trained using static graph.

**Comment by www516717402** [comment]
Great help. Thanks.
