### ISSUE TITLE
如何把模型中保存的两个权重，其中一个权重的部分参数移植到另一个权重中

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/PaddleDetection#459]
用相同的模型（参数相同），使用不同的训练策略训练两个权重。如何能把其中一个权重中的参数移植到另一个模型中，或者在加载模型时，如何先加载一个权重，再把另一个权重的一部分加载进去

**Comment by willthefrog** [comment]
当前版本使用的是paddle 1.7的save/load API， 存储的".pdmodel"文件其实是一个pickle dump的dict，可以用pickle加载进来，然后根据需要修改该dict后再保存就可以了。

**Comment by zhengzhe97** [comment]
谢谢回复，之前没怎么用过pickle
![N7OUJWXQQVN7~YX97_1R6TM](https://user-images.githubusercontent.com/26462054/78749548-0cd1e800-79a1-11ea-84ad-36c2d2c4b643.png)
我尝试导入.pdmodel出错，导入.pdparams和.pdopt是没有问题的

**Comment by willthefrog** [comment]
sorry, 说错了，权重就是`.pdparams`，`.pdmodel`是网络结构。修改`.pdparams`就可以了。

**Comment by zhengzhe97** [comment]
好的，修改成功了。
然后在网络里新加了几个个卷积层，导入参数出问题
![M}FK~}B 7`69%VGO_E73QAY](https://user-images.githubusercontent.com/26462054/78753586-99cc6f80-79a8-11ea-8e5c-811208c9aae1.png)
这个有解决办法吗

**Comment by willthefrog** [comment]
缺少是没法加载的，你先随机初始个save下，然后把pretrained的weight merge进去应该是可以的。

**Comment by zhengzhe97** [comment]
成功了，感谢
