### ISSUE TITLE
[BUG]在YOLOX可以训练的COCO数据集，在PP-Picodet-S中训练却出现如下问题

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#4598]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.
3. 确认bug是否在新版本里还未修复/The bug has not been fixed in the latest version.

## 描述问题/Describe the bug
在YOLOX可以训练的数据集，在PP-Picodet-S中训练却出现如下问题
![image](https://user-images.githubusercontent.com/78945582/141928873-5f5e02d5-ed9b-4d0f-a6e6-05b7ad2610b4.png)
我作了一个软链接：
![image](https://user-images.githubusercontent.com/78945582/141929407-71366c44-d4f2-47fc-862e-9e6acfc64809.png)

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
export CUDA_VISIBLE_DEVICES=1
python tools/train.py -c configs/picodet/picodet_s_320_coco.yml --eval
```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by ghostxsl** [comment]
您可以直接修改：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/datasets/coco_detection.yml#L8
TrainDataset.dataset_dir为您指定的数据目录

**Comment by lixiangMindSpore** [comment]
> 您可以直接修改：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/datasets/coco_detection.yml#L8 TrainDataset.dataset_dir为您指定的数据目录

为了尽可能不修改代码，在dataset下建立软链接，如下图所示：
![image](https://user-images.githubusercontent.com/78945582/141930863-396b1aa3-318c-4b28-9d04-be1d43dc3eb5.png)
目录下是下面三个文件夹
![image](https://user-images.githubusercontent.com/78945582/141931269-0c727898-1612-4a5e-bceb-43d1a4811934.png)

**Comment by lixiangMindSpore** [comment]
> 您可以直接修改：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/datasets/coco_detection.yml#L8 TrainDataset.dataset_dir为您指定的数据目录

是不是软链接得写绝对路径？

**Comment by ghostxsl** [comment]
> > 您可以直接修改：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/datasets/coco_detection.yml#L8 TrainDataset.dataset_dir为您指定的数据目录
> 
> 是不是软链接得写绝对路径？

是的

**Comment by lixiangMindSpore** [comment]
> > > 您可以直接修改：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/datasets/coco_detection.yml#L8 TrainDataset.dataset_dir为您指定的数据目录
> > 
> > 
> > 是不是软链接得写绝对路径？
> 
> 是的

修改pp-picodet-s的batchsize，在哪里修改？

**Comment by ghostxsl** [comment]
在其对应文件夹下的_base_里的xxx_reader.yml里修改，参考如下：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/_base_/picodet_320_reader.yml#L12

**Comment by lixiangMindSpore** [comment]
> 在其对应文件夹下的_base_里的xxx_reader.yml里修改，参考如下： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/_base_/picodet_320_reader.yml#L12

如果把picodet_320_reader.yml中TrainReader的batch_size从128改为64，AP指标会有什么影响？能下降多少？
![image](https://user-images.githubusercontent.com/78945582/141943568-facb7e1b-6e89-4a74-b5dd-0a6d7dee57e2.png)

**Comment by ghostxsl** [comment]
一般来讲，满足SGD线性学习率缩放准则的话，AP应该不会有太大变化

**Comment by lixiangMindSpore** [comment]
> 一般来讲，满足SGD线性学习率缩放准则的话，AP应该不会有太大变化

我这面只改动batchsize，上下浮动会有多大？
