### ISSUE TITLE
[Other General Issues]计算FLOPs的示例代码有吗？可直接运行的那种

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#4610]
## 描述问题/Describe the bug

计算FLOPs的示例代码有吗？可直接运行的那种

**Comment by qingqing01** [comment]
可以通过tools下面的训练/评估/推理命令行时设置 `-o print_flops=true`  试下

**Comment by lixiangMindSpore** [comment]
> 可以通过tools下面的训练/评估/推理命令行时设置 `-o print_flops=true` 试下

相关代码在哪里有写？谢谢您

**Comment by yghstill** [comment]
@lixiangMindSpore 计算flops代码位置：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/engine/trainer.py#L684

算出来的数值为macs，flops=2*macs
