### ISSUE TITLE
关于ppyolov2恢复训练问题，与不同阈值ap降低过多问题[Other General Issues]

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#4612]
您好，我在使用PPYOLOV2进行训练，在我B账号算力用尽后将训练保存的权重与训练策略文件下载下来并放到A账号上继续训练时会发现相比较继续训练之前，A账号在继续训练时的Map相比较B账号的Map会下降1%到2%，想请问一下这个问题应该如何解决·

同时我在使用ppyolov2进行目标检测使用Coco评价方式阈值在0.5的情况下ap在90%而阈值到了0.75的情况下ap就降低到了40以下，请问一下能否有办法提高一下阈值较高时的得分情况，
![image](https://user-images.githubusercontent.com/78856426/142150948-086ddffd-cc0e-4cee-8de2-89692c5551b4.png)

**Comment by violetweir** [comment]
这里贴的是A账号继续训练后的第一次的eval，相比较b账号最后的一次eval下降了1，8个百分点

**Comment by wangxinxin08** [comment]
由于目前ppyolov2在训练时使用了ema，而在模型的保存和resume时并没有保存ema的状态，因此会出现resume之后训练精度上升或者下降，这个问题已经在解决当中，后续会提PR修复这个问题

**Comment by wangxinxin08** [comment]
AP(IoU=0.75)相较于AP(IoU=0.50)是一个相对苛刻的目标，所以指标会下降，如果像提高检测的准确性，可以考虑适当增加回归的权重
