### ISSUE TITLE
新增类别相关参数的设置疑问

### ISSUE THREAD

**Issue by coderchuan** [PaddlePaddle/PaddleDetection#4617]
若原先训练了模型，num_classes 数量为10
后来又重新添加了一些图片数据，新增的类别数为5 
把之前的模型作为预训练模型，第二次训练只训练新增的图片数据
那第二次训练时的 num_classes 应该设置为 5 还是 15 呢

**Comment by qingqing01** [comment]
具体的需要依据您最终想要做15类的检测、还是5类的检测模型，如果是5类，第二次只训练新增的5类的图片数据，类别数设置为5即可。 如果是15类，那第二次训练，需要训练全部的15类图片数据。

**Comment by coderchuan** [comment]
> 具体的需要依据您最终想要做15类的检测、还是5类的检测模型，如果是5类，第二次只训练新增的5类的图片数据，类别数设置为5即可。 如果是15类，那第二次训练，需要训练全部的15类图片数据。

这样确实可以解决问题，可是我们后续还会增加更多的类别，每次增加都要全部重新训练感觉会浪费很多时间，我现在是想要只训练增加的类别，所以对 num_classes 的设置有疑惑。请问有更好的方法解决这类问题吗？

**Comment by qingqing01** [comment]
如果尺训练新增类别，最终还想只用1个模型做推理，基本不太可行。 用已有的模型做预训练，是可以考虑减少训练轮数节约时间。

**Comment by Heimdall-Nss** [comment]
我也遇到这个问题了，和题主需求一样，请问有找到合适的解决方案吗
