### ISSUE TITLE
ppyolo-tiny 训练速度很慢

### ISSUE THREAD

**Issue by clearlove7-piggy** [PaddlePaddle/PaddleDetection#4620]
3090训练ppyolo-tiny很慢。总轮数设置100轮，需要3天。。。batchsize：32 ,work_num:8 lr:0.001,单卡。MOT20数据集。
![~6E`MCEVQ3HO}O_{(@OJ7(U](https://user-images.githubusercontent.com/81201184/142339978-034fddfc-d95d-4787-8649-f18fda78dd46.png)

**Comment by yghstill** [comment]
@clearlove7-piggy 因为ppyolo-tiny数据预处理较为复杂，所以预处理耗时较多，可以适当减少这些一些数据增强：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/ppyolo/_base_/ppyolo_tiny_reader.yml#L7-L11
这个训练时间的话，看着是正常的。
如果有移动端检测的需求，可以尝试更好的模型PicoDet，训练时间会下降很多：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet
