### ISSUE TITLE
PP-PicoDet 如果只要一类的预测结果要怎么修改代码？还有如果只要训练一类目标的检测要怎么修改？

### ISSUE THREAD

**Issue by Zachary-ZCH** [PaddlePaddle/PaddleDetection#4628]
没有找到修改类别的配置文件。

**Comment by yghstill** [comment]
@Zachary-ZCH 修改数据集及类别位置：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/datasets/coco_detection.yml#L2

**Comment by voyag8r** [comment]
可以用预训练好的模型只预测一类的目标吗？
想减少显存使用量

**Comment by voyag8r** [comment]
@Zachary-ZCH
