### ISSUE TITLE
[Other General Issues]ppyolotiny，训练很慢，且损失一直很大！

### ISSUE THREAD

**Issue by xihuanafeng** [PaddlePaddle/PaddleDetection#4630]
## 描述问题/Describe the bug
训练很慢，且损失值一直在跌宕起伏。
![image](https://user-images.githubusercontent.com/78284628/142547083-3e8a98a4-977e-4848-9d68-7a553582c557.png)
![image](https://user-images.githubusercontent.com/78284628/142548439-460d0670-eb89-4465-ae22-5fc8b22cb591.png)

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
     使用的ppyolo_mbv3_small_coco.yml，更改了数据读取部分，batch_size=8，worker_num =2
3. 您使用的数据集是？/What dataset did you use?
     voc口罩数据集转成的coco数据集！
4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
    没有报错，但是训练很慢，损失值一直很大
## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
    2.20
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
   win10
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
   python3.8

**Comment by yghstill** [comment]
@xihuanafeng 因为ppyolo-tiny数据预处理较为复杂，所以预处理耗时较多，可以适当减少这些操作：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/ppyolo/_base_/ppyolo_tiny_reader.yml#L7-L11
同时你的loss看上去是正常的。
如果有移动端检测的需求，可以尝试更好的模型PicoDet：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet
