### ISSUE TITLE
[Feature Request]动态图训练yolov3时，没有准确度的输出吗？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4634]
训练的输出现在是有mAP和各种loss，我想问：
1.没有precision和recall和iou的输出吗？有什么办法输出这些评价指标吗？
2.yolov3的总的loss是其他几个loss输出的和吗？loss=loss_cls+loss_xy+loss_wh+loss_obj这样

**Comment by zmdcs** [comment]
然后生成的log文件没法在VisualDL中绘制PR曲线和ROC曲线，有什么办法自己会绘制吗？

**Comment by yghstill** [comment]
@zmdcs 
1. 绘制PR曲线可以在eval时指定--classwise: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/tools/eval.py#L70
2. 是的，总loss是各个分支loss的加和
