### ISSUE TITLE
Soft-teacher

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#4636]
您好，paddledetection可否对s半监督目标检测方法soft-teacher进行复现，这样便于我们进一步提升模型的性能，谢谢！

**Comment by yghstill** [comment]
@qdd1234 感谢建议，我们调研梳理下。

**Comment by July-zh** [comment]
蹲，请问现在有集成吗？

**Comment by nemonameless** [comment]
PaddleDetection目前已支持半监督检测方法DenseTeacher，在develop分支中，欢迎使用~
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/semi_det/denseteacher
