### ISSUE TITLE
关于PaddleDetection读取照片问题[Other General Issues]

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#4640]
您好我想请问一下PaddleDetection中COCO数据集以及VOC数据集读取照片的地方是哪里，因为我这个数据集有些问题，虽然它标注的时候显示是三通道，但是其实这个三通道的信息是一样的，只需要拿出来一个通道的信息就可以了，我想请问一下哪里是读取照片的地方，我好进行修改。

**Comment by lyuwenyu** [comment]
这个修改reader里的decode就行吧
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/data/transform/operators.py#L113
