### ISSUE TITLE
请问pp-picodet最小的模型在windows i7十代的推理速度大概是多少ms？

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#4642]
请问哪位大佬有尝试过，pp-picodet最小的模型在windows i7十代的推理速度大概是多少ms？

**Comment by lyuwenyu** [comment]
你环境方便的话 可以直接执行下边两个命令测一下

```
python tools/export_model.py -c configs/picodet/picodet_s_320_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/picodet_s_320_coco.pdparams

python deploy/python/infer.py  --run_mode=fluid --device=GPU --threshold=0.5 --output_dir=python_infer_output --image_dir=./demo --model_dir=output_inference/picodet_s_320_coco --runbenchmark=True
```

**Comment by lyuwenyu** [comment]
@Dandelion111  有结果的话 可以贴一下哈

**Comment by Dandelion111** [comment]
> @Dandelion111 有结果的话 可以贴一下哈
笔记本是i7 十代，用openvino推理速度如下
![image](https://user-images.githubusercontent.com/48303408/142961694-76829ae9-305a-437c-8dd5-8ae678059bdf.png)
模型是picodet_m_416
s模型感觉和m模型速度差不太多，不知道我测得准不准

**Comment by qdd1234** [comment]
> > @Dandelion111 有结果的话 可以贴一下哈
> > 笔记本是i7 十代，用openvino推理速度如下
> > ![image](https://user-images.githubusercontent.com/48303408/142961694-76829ae9-305a-437c-8dd5-8ae678059bdf.png)
> > 模型是picodet_m_416
> > s模型感觉和m模型速度差不太多，不知道我测得准不准

您的测试时间的代码方便贴一下吗，谢谢

**Comment by Dandelion111** [comment]
> > > @Dandelion111 有结果的话 可以贴一下哈
> > > 笔记本是i7 十代，用openvino推理速度如下
> > > ![image](https://user-images.githubusercontent.com/48303408/142961694-76829ae9-305a-437c-8dd5-8ae678059bdf.png)
> > > 模型是picodet_m_416
> > > s模型感觉和m模型速度差不太多，不知道我测得准不准
> 
> 您的测试时间的代码方便贴一下吗，谢谢

我用的官方给的openvino的c++ demo
