### ISSUE TITLE
创建模型

### ISSUE THREAD

**Issue by isLiuHao** [PaddlePaddle/PaddleDetection#4647]
请问一下模型是不是都是封装好了，想要更改模型怎么实现（发论文的需求）？

**Comment by lyuwenyu** [comment]
可以修改的  可以简单说下你需要修改那些 模型相关的源代码都在 ppdet/modeling

**Comment by isLiuHao** [comment]
好的谢谢  我想在yolo模型的基础上做一下修改 我看一下源代码

**Comment by lyuwenyu** [comment]
以yolov3为例子 

1. 查看config [yolov3](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/yolov3/_base_/yolov3_darknet53.yml#L1)
2. 找到要修改的模块名字  例如：`YOLOv3Head`
3. 到 ppdet/modeling下找到相关的代码  [code](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/heads/yolo_head.py#L17)


np~  有问题留言

**Comment by isLiuHao** [comment]
超级感谢

**Comment by isLiuHao** [comment]
模型修改已经实现了，请问一下训练的时候怎么打印出模型的结构呢？

**Comment by dengxinlong** [comment]
> 模型修改已经实现了，请问一下训练的时候怎么打印出模型的结构呢？

你好，我想请问一下这个问题你解决了吗，paddle提供了paddle.summary()来打印模型的结构，但是我没找到应该加在哪里？
