### ISSUE TITLE
Benchmark测试后续会加上用视频测试的功能吗？

### ISSUE THREAD

**Issue by bbilixzc** [PaddlePaddle/PaddleDetection#4649]
目前PaddleDetection提供的Benchmark测试功能仅针对于用模型去预测图片进行测试：
![1637566098(1)](https://user-images.githubusercontent.com/40461420/142822967-7acdbb55-133b-42df-a4dd-9c228c7cc474.png)

我使用官方提供的Benchmark批量测试脚本在jetson nano上对ppyolo-tiny进行测试，结果如下：
![1](https://user-images.githubusercontent.com/40461420/142823560-6376d407-018a-4208-8959-bc8d227b803c.png)
![2](https://user-images.githubusercontent.com/40461420/142823588-a295b23b-6512-4a49-b1fb-e2a87f5974f9.png)
关于GPU的资源利用率没有测试出来。

希望后续Benchmark测试可以加上用模型处理视频进行测试的功能，以便更好的测试模型在不同硬件平台上运行的性能，资源利用率和功耗等指标。

**Comment by lyuwenyu** [comment]
好 感谢意见 我们会认真评估
