### ISSUE TITLE
paddle模型转openvino模型遇到错误

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#4660]
各位大佬，我在paddle模型转openvino模型遇到如下错误：
第一步先转onnx模型没出现问题，转换命令如下
![image](https://user-images.githubusercontent.com/48303408/142960715-63c17f1b-1f54-45f8-8157-d40515bc834a.png)
第二部onnx转openvino出现错误
![image](https://user-images.githubusercontent.com/48303408/142960769-1ae4fdf9-fc9e-4df3-8e5d-1e261a618a66.png)
请问这错误可能是什么原因呢？

有这个错误还是可以得到转换后的模型，不过结果有问题，paddle模型是在官方连接下载的
![predict](https://user-images.githubusercontent.com/48303408/142961384-87f7a8dd-072f-47aa-906b-912de51c58f6.jpg)

**Comment by Dandelion111** [comment]
可以得到转换的模型，但是这个结果有问题，paddle模型是在官方连接下载的
![predict](https://user-images.githubusercontent.com/48303408/142961240-b9586125-994d-4b4d-b12c-908eca1f399b.jpg)

**Comment by yghstill** [comment]
@Dandelion111 转onnx后进行simplify 简化模型了吗？
```shell
python -m onnxsim picodet_s_320_coco.onnx picodet_s_processed.onnx
```
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet#deployment
也可以直接下载我们转好的onnx模型测试。

**Comment by Dandelion111** [comment]
> @Dandelion111 转onnx后进行simplify 简化模型了吗？
> 
> ```shell
> python -m onnxsim picodet_s_320_coco.onnx picodet_s_processed.onnx
> ```
> 
> https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet#deployment 也可以直接下载我们转好的onnx模型测试。

这个操作没有做，请问这个步骤的作用是啥呢？

**Comment by Dandelion111** [comment]
> @Dandelion111 转onnx后进行simplify 简化模型了吗？
> 
> ```shell
> python -m onnxsim picodet_s_320_coco.onnx picodet_s_processed.onnx
> ```
> 
> https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet#deployment 也可以直接下载我们转好的onnx模型测试。

刚才用您提供的连接下载了onnx模型，转换到openvino模型还是得不到正确推理结果，转换使用的命令如下：
python "C:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\mo.py" --input_model=picodet_s_416_coco.onnx --output_dir=.  --model_name=picodet_s_416_coco --data_type=FP32
推理结果如下：
![predict](https://user-images.githubusercontent.com/48303408/142988800-4482b6b5-4b3c-43b6-be5f-9cc52bde7c72.jpg)

**Comment by Dandelion111** [comment]
> @Dandelion111 转onnx后进行simplify 简化模型了吗？
> 
> ```shell
> python -m onnxsim picodet_s_320_coco.onnx picodet_s_processed.onnx
> ```
> 
> https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet#deployment 也可以直接下载我们转好的onnx模型测试。

请问这个简化步骤在哪里能看到，没有见过这个步骤

**Comment by xiangfeidecao** [comment]
> > @Dandelion111 转onnx后进行simplify 简化模型了吗？
> > ```shell
> > python -m onnxsim picodet_s_320_coco.onnx picodet_s_processed.onnx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet#deployment 也可以直接下载我们转好的onnx模型测试。
> 
> 请问这个简化步骤在哪里能看到，没有见过这个步骤

请问你这个错误找到原因了吗？我也有这个错误，但是我没生成bin文件，用官方给的onnx也不行，自己简化后的也不行

**Comment by xiangfeidecao** [comment]
> 
> 请问你这个错误找到原因了吗？我也有这个错误，但是我没生成bin文件，用官方给的onnx也不行，自己简化后的也不行

--后来我成功了，大概是我一开始没指定output_dir

**Comment by xiangfeidecao** [comment]
请问你后来成功了吗？我除了官方给的picodet_416.xml成功了能正常检测。其他用官方的onnx转的IR模型都检测很乱，我自己的训练的然后转的，都乱的。

**Comment by TomHardy1138** [comment]
Hi, @Dandelion111 . Try to convert your model in openVINO with admin mode, maybe it will help
