### ISSUE TITLE
多进程推理报错

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleDetection#4662]
https://github.com/PaddlePaddle/PaddleDetection/issues/2450 这个issue是说咱们paddle没办法多进程启动吗。我这边启动多个进程也报错
![ba26187b5d8b1d82eb7c7ee49d7c6727](https://user-images.githubusercontent.com/67897601/142968209-b58621cf-9ee8-479f-af23-f3a6c8fc7235.jpg)

**Comment by nemonameless** [comment]
暂时未支持

**Comment by felixhjh** [comment]
请问这个问题解决了吗？python多进程跟上面报错相同，想问下 为什么Paddle会不支持多进程启用方式呢？python的话使用多线程是有性能损失的，我理解多进程才比较方便，求解答
