### ISSUE TITLE
 人脸检测模型blazeface_fpn_ssh_1000e.yml。A10卡上qps 9，GPU利用率10%,是否正常。怎么加速呢？不用tensorrt

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleDetection#4663]

**Comment by qingqing01** [comment]
不太正常，这个模型比BlazeFace应该稍慢一点，但BlazeFace我们在P4上测试，输入尺寸128、320、640尺寸时，基本都是ms级别。

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/static/docs/featured_model/FACE_DETECTION.md#%E6%8E%A8%E7%90%86%E6%97%B6%E9%97%B4%E5%92%8C%E6%A8%A1%E5%9E%8B%E5%A4%A7%E5%B0%8F%E6%AF%94%E8%BE%83

即使不用TensorRT应该也不会特别慢，您输入尺寸多大？
