### ISSUE TITLE
win10环境下，调用tools/infer.py 无任何结果反馈

### ISSUE THREAD

**Issue by xiuyangleiasp** [PaddlePaddle/PaddleDetection#4669]
如图，win10环境下按照quick start中的命令进行picodet模型推理验证时，无任何结果反馈，亦无相应的检测图片保存。
![image](https://user-images.githubusercontent.com/9282338/142980745-aeb8c296-d73c-4cea-8188-f74a172e9e3b.png)

paddlepaddle的版本是：2.2.0

**Comment by nemonameless** [comment]
您可以在此处print打印下看看究竟有没有检测结果输出，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/architectures/picodet.py#L90

**Comment by xiuyangleiasp** [comment]
经过打印，有检测结果输出，另外经过跟踪，结果会在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/engine/trainer.py#L516
的results中append，但奇怪的是append之后，后续步骤不执行，如图：
![image](https://user-images.githubusercontent.com/9282338/142983426-e4f489f8-863d-47db-a89a-f15f8e44c0f8.png)

程序仅输出“11111111111111111111111111”
![image](https://user-images.githubusercontent.com/9282338/142983565-50f217f2-e4ed-4346-913f-c1951724ae85.png)

**Comment by liqing1993** [comment]
我也遇到了这个问题，请问解决了吗

**Comment by xiuyangleiasp** [comment]
> 我也遇到了这个问题，请问解决了吗

没有解决

**Comment by RoyXinyun** [comment]
2022年同问

**Comment by RoyXinyun** [comment]
同问
