### ISSUE TITLE
[Other General Issues]预测的时候,如何改变检测框的线条粗细?

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4671]
如何改变预测图片时,检测框的粗细以及置信度字体的大小?现在的大小不放大看不清楚

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/utils/visualizer.py#L109
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/utils/visualizer.py#L127
可自行调整

**Comment by zmdcs** [comment]
您好,设置字体大小,我看网上关于draw.text设置字体大小,需要指定字体样式,于是我是这样设置的
ft = ImageFont.truetype("D:/Paddle/PaddleDetection/ppdet/utils/arialuni.ttf", 30)
draw.text((xmin + 1, ymin - th), text, fill=(255, 255, 255),font=ft)


可是,上面设置的关于置信度底色的那个框的大小,它是根据默认大小设置的,我有两个疑问,1.这个修改字体大小是不是有更简单的方法,以至于能够让 tw, th = draw.textsize(text)能够匹配进行;2.或者只有上面那一种办法修改字体大小,我要如何对应修改底框的大小呢?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月23日(星期二) 下午3:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] [Other General Issues]预测的时候,如何改变检测框的线条粗细? (Issue #4671)





 
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/utils/visualizer.py#L109
 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/utils/visualizer.py#L127
 可自行调整
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
