### ISSUE TITLE
[Other General Issues]想要输出AR,AP,presicion和recall的值

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4673]
我看其他人的issue里可以输出 
Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.123
Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.401
Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.039
Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.104
Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.041
Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.098
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.159
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.324
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.454
Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.217
Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.453
Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.553
这个样子的信息,我也想能输出这样的 信息,要怎么操作呢?现在只能输出PR曲线,看不到具体的presicion\recall\AR\AP值.

**Comment by nemonameless** [comment]
请问运行语句是什么呢？数据集是coco格式吗？

**Comment by zmdcs** [comment]
不是，是voc



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月23日(星期二) 下午3:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] [Other General Issues]想要输出AR,AP,presicion和recall的值 (Issue #4673)





 
请问的运行语句是什么？数据集是coco格式吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nemonameless** [comment]
#4657  相关问题。
只有coco格式才能调用cocoapi打印这种格式的结果。您也可以把voc格式的数据转成coco格式然后采用COCOMetric而不是VOCMetric，训完评估就有这种coco格式的结果了

首先pip安装pycocotools包
代码里会有
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
ppdet里的打印调用在此：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/metrics/coco_utils.py#L114
cocoapi里的原始代码在此
https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L422

主要代码：
```
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

coco_gt = COCO(anno_file) # anno_file是gt json的路径
coco_dt = coco_gt.loadRes(jsonfile) # jsonfile是结果json的路径
coco_eval = COCOeval(coco_gt, coco_dt, 'bbox')  # 'bbox'评估检测，还有‘segm’是评估实例分割的，‘keypoints’是评估关键点检测

coco_eval.evaluate()
coco_eval.accumulate()
coco_eval.summarize() # 打印指标
```
