### ISSUE TITLE
ttfnet 训练过程中，wh_loss和loss值一直增大，ap为0

### ISSUE THREAD

**Issue by cuesong** [PaddlePaddle/PaddleDetection#4679]
训练过程的信息：loss值一直增加
![训练过程](https://user-images.githubusercontent.com/31815086/142994646-56cf8215-290f-4d21-870a-f8ca0d707f72.png)
数据集配置：
    数据集是通过 tools/x2coco.py  将 labelme  转换到coco
![data_config](https://user-images.githubusercontent.com/31815086/142995013-aae2df21-2d0a-4f80-b67a-242dcfb0783c.JPG)

这种是什么问题导致的？学习率？

**Comment by cuesong** [comment]
偶尔会出现： DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("Evaluation results empty, this may be due to  Evaluation results empty, this may be due to training iterations being too few or not loading the correct weights****

**Comment by nemonameless** [comment]
您好，请先检查下数据集gt是否制作正确，建议可视化出来看看。
另外训练loss请截取第一个epoch开始阶段的，以及再贴下运行指令，和有改动过的config设置，以便于排查问题，谢谢

**Comment by cuesong** [comment]
> 您好，请先检查下数据集gt是否制作正确，建议可视化出来看看。 另外训练loss请截取第一个epoch开始阶段的，以及再贴下运行指令，和有改动过的config设置，以便于排查问题，谢谢

您好，确认了gt正确，另外，替换了paddl版本为paddlepaddle-gpu=2.2.0.post101，loss有降低为loss: 1.366281就收敛了，ap上不去，最高为0.416，epoch已经为1000，请问有什么方法提升ap吗

**Comment by cuesong** [comment]
config只修改过coco_detection,信息如下

metric: COCO
num_classes: 3
TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/instance_train.json
    dataset_dir: dataset/coco_data_pfw
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/instance_val.json
    dataset_dir: dataset/coco_data_pfw

TestDataset:
  !ImageFolder
    anno_path: annotations/instance_test.json

**Comment by aaaeric026** [comment]
请问解决了吗？有同样的问题
