### ISSUE TITLE
s2anet使用paddleinference推理报错。[BUG]

### ISSUE THREAD

**Issue by chenran06** [PaddlePaddle/PaddleDetection#4680]
s2anet使用paddleinference推理报错。

模型转换：
`python tools/export_model.py -c ./configs/dota/s2anet_conv_2x_dota.yml -o weights=./s2anet_conv_2x_dota.pdparams`

paddleinference推理：
`./build/main --model_dir=./output_inference/s2anet_conv_2x_dota --image_file=./tests/20180520172120828.png`

推理报错内容：
`---    Fused 0 subgraphs into layer_norm op.
total images = 1, batch_size = 1, total steps = 1
Illegal instruction (core dumped)
`

**Comment by wangxinxin08** [comment]
请问使用的PaddlePaddle，PaddleDetection以及PaddleInference版本是什么？

**Comment by chenran06** [comment]
@wangxinxin08 
PaddlePaddle 2.2.0   PaddleDetection 2.3.0  PaddleInference 2.1.1

**Comment by wangxinxin08** [comment]
使用PaddlePaddle 2.2.0 PaddleDetection 2.3.0 PaddleInference 2.1.1执行上述命令没有问题，猜测可能的原因：
1. PaddleDetection 2.3.0不是最新的版本，建议拉取最新版本重新导出测试
2. model_dir路径或者image_file没有正确指定
