### ISSUE TITLE
[Feature Request]VOC格式的目标检测想要输出一下内容

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4684]
1.想要在某一阈值下的precision，recall，TP，TN，FP，FN的值。现在有已经存在的方法吗？没有的话，希望添加，如果可以麻烦提供一个思路。
2.有计算模型参数量的功能吗？（因为mobilenet的轻量级一是体现在参数量减少，一是推理速度加快，FLOPS我觉得只能说明推理速度变快了，没有指标能说明参数量变小了吗？）

**Comment by gaorui999** [comment]
直接加到trainer.py __init__.py，当然也可以加到self_flops的函数里
params = sum([
            p.numel() for n, p in self.model.named_parameters()
            if all([x not in n for x in ['_mean', '_var']])
        ])

**Comment by zmdcs** [comment]
不能加在infer.py或者eval.py中吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月24日(星期三) 上午10:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] [Feature Request]VOC格式的目标检测想要输出一下内容 (Issue #4684)





 
直接加到trainer.py init.py，当然也可以加到self_flops的函数里
 params = sum([
 p.numel() for n, p in self.model.named_parameters()
 if all([x not in n for x in ['_mean', '_var']])
 ])
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zmdcs** [comment]
paddleDetection的self_flops函数在哪里呢?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月24日(星期三) 上午10:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] [Feature Request]VOC格式的目标检测想要输出一下内容 (Issue #4684)





 
直接加到trainer.py init.py，当然也可以加到self_flops的函数里
 params = sum([
 p.numel() for n, p in self.model.named_parameters()
 if all([x not in n for x in ['_mean', '_var']])
 ])
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zmdcs** [comment]
不好意思,看错了,输出了Tensor,谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月24日(星期三) 上午10:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] [Feature Request]VOC格式的目标检测想要输出一下内容 (Issue #4684)





 
直接加到trainer.py init.py，当然也可以加到self_flops的函数里
 params = sum([
 p.numel() for n, p in self.model.named_parameters()
 if all([x not in n for x in ['_mean', '_var']])
 ])
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gaorui999** [comment]
第一个问题我通过x2coco.py这个数据转换解决了，COCO的评估方式能解决很多的问题。
