### ISSUE TITLE
🔥 实时跟踪系统PP-Tracking已发布，欢迎大家试用讨论

### ISSUE THREAD

**Issue by jerrywgz** [PaddlePaddle/PaddleDetection#4688]
🔥 PP-Tracking是基于飞桨深度学习框架的业界首个开源实时跟踪系统，具有以下特色：

功能丰富：配备单镜头跟踪，多类别跟踪，跨镜头跟踪，流量监测等功能
场景覆盖全：涵盖行人、车辆跟踪，人头跟踪，小目标跟踪多种预训练模型，应对各类复杂场景
使用灵活：支持API代码调用方式进行模型训练、预测、部署全流程；同时支持可视化界面，无需开发即可体验功能
部署便捷：支持Python, C++两种部署语言，同时提供Paddle Inference, Paddle Serving部署方式
详细细节请见：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/pptracking/README.md

为了方便大家交流沟通，欢迎扫码添加微信群，提出您的意见、建议或者使用中的疑问。

![IMG_0081](https://user-images.githubusercontent.com/48054808/161363173-86e8c158-9912-496c-bcf3-80eaf479a562.JPG)

**Comment by nemonameless** [comment]
PP-Tracking也提供了AI Studio公开项目案例，可以参考[PP-Tracking之手把手玩转多目标跟踪](https://aistudio.baidu.com/aistudio/projectdetail/3022582)快速上手体验。

**Comment by sunxirui310** [comment]
二维码过期了。

**Comment by YixinKristy** [comment]
二维码已更新~

**Comment by wanglu362** [comment]
二维码已过期，麻烦更新，谢谢

**Comment by jerrywgz** [comment]
二维码已更新

**Comment by lilith-zy** [comment]
PP-Tracking技术交流群二维码更新：
<div  align="center">    
<img src="https://user-images.githubusercontent.com/80816848/146365848-1663a16d-6dca-4783-8624-1adc3cdf1d31.jpg" width = "300" height = "300" alt="图片名称" align=center />
</div>

**Comment by Xinjun-Wu** [comment]
@YixinKristy 二维码还能再更新一个么？*-^

**Comment by nemonameless** [comment]
![image](https://user-images.githubusercontent.com/13104100/147754584-cd695dd9-4572-496e-a9d3-41ddcd91e713.png)

**Comment by nemonameless** [comment]
> @YixinKristy 二维码还能再更新一个么？*-^

![image](https://user-images.githubusercontent.com/13104100/147754678-c1a3d35a-5521-4392-aae6-c5a31fc99f87.png)

**Comment by YixinKristy** [comment]
二维码已更新~

**Comment by dongyangli-del** [comment]
2022 3.28, 二维码又过期了..

**Comment by dongyangli-del** [comment]
球球了,给个码吧~

**Comment by dongyangli-del** [comment]
2022 3.30, 球球给个码吧......

**Comment by dongyangli-del** [comment]
> 二维码已更新~

施主, 球球给个码吧......

**Comment by dongyangli-del** [comment]
@YixinKristy

**Comment by dongyangli-del** [comment]
@[jerrywgz](https://github.com/jerrywgz)

**Comment by dongyangli-del** [comment]
3.31有人吗?这个专栏别沉啊

**Comment by dongyangli-del** [comment]
@[lilith-zy](https://github.com/lilith-zy)

**Comment by dongyangli-del** [comment]
@[jerrywgz](https://github.com/jerrywgz)

**Comment by changtimwu** [comment]
Hi! Quite a lot of people are interested in pp-tracking.   Placing an expired wechat link here doesn't make any sense.   Please create a forum for it or close this issue immediately.

**Comment by seekme-ai** [comment]
请更新二维码 谢谢

**Comment by JAY022** [comment]
请更新二维码 谢谢

**Comment by shuyu888** [comment]
???

**Comment by shiboyang** [comment]
可以留个管理员微信把大家拉进去吗
