### ISSUE TITLE
怎么测试coco的test数据

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/PaddleDetection#469]

**Comment by FDInSky** [comment]
你是要eval整个test数据集?

**Comment by zhengzhe97** [comment]
@FDInSky 是的，我看代码里只有val集的

**Comment by qingqing01** [comment]
@zhengzhe97 参考预测这个脚本，可以预测一个image foler目录，但这个脚本是可视化图片，如果要保存结果的话，需要稍微改下代码，可以参考：  https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/tutorials/GETTING_STARTED_cn.md#%E6%A8%A1%E5%9E%8B%E6%8E%A8%E6%96%AD 


请问您测试test集，一般会保存成什么格式，我们可以加强下。
