### ISSUE TITLE
关键点检测配置参数

### ISSUE THREAD

**Issue by xywlpo** [PaddlePaddle/PaddleDetection#4691]
您好，paddledetection中的关键点检测是否有详细的yml参数文件的解释说明？因为是刚接触关键点检测问题，我要做的不是人体的关键点，是物体的关键点检测，但是不知道如何修改配置参数

我看hrnet、lite_hrnet、tiny_pos中的architecture都是TopDown**，这样的方式需要前面接目标检测吗？标注时需要把目标的bbox也标注吗？
然后对于配置文件中的 num_classes是指的什么？和num_joins有啥区别，然后flip_perm是什么意思？

**Comment by ghostxsl** [comment]
您好，我们正在更新相关参数说明的文档，后续进展会同步给您～

**Comment by xywlpo** [comment]
好的，期望参数说明文档能尽快更新，要不参数太多用起来很不方便。那能先帮我解答下面的困惑吗？
1. 目前我们的keypoints算法中，higherhrnet是bottom-to-up的，hrnet、lite_hrnet、tiny_pose都是Top-to-down的方法的是吗？对于这种Top-to-down的方法前段是要接一个目标检测吗？这种方法只能处理单个目标的关键点检测吗？标注的文件也只能包含一个目标实例是吗？
2. 配置文件中的num_classes是指的有几种类型的实例是吧？比如只做人的关键点检测，num_classes=1? 然后参数中的flip_perm是什么意思？

**Comment by zoooo0820** [comment]
@xywlpo 
1. Top-down类型的算法需要接一个目标检测模型，本质上是通过检测将多人关键点任务转化为多个单人关键点检测任务，整体来看精度指标会高于Bottom-up类的算法。  标注上，以COCO数据集的格式为例，是允许一张图片(同一个image_id)中包含多个实例的，只要保证这个实例标注的image_id能与所在图像id对齐即可， 另外实例需要有对应的Bbox信息。
2. 您对num_classes的理解是正确的，目前关键点任务主要由num_joints这个参数来控制要预测的关键点的数量。 由于关键点任务中的标注是有特定顺序的，而在常用的数据增强策略中会用到水平翻转策略做数据增强，翻转前后关键点的语义会变化（例如左肩变为右肩），因此通过flip_perm来指定翻转前后序号的对应关系。这里具体可参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/PrepareKeypointDataSet_cn.md 文档对COCO数据集的说明，可以看到都是左-右的对应关系。

**Comment by xywlpo** [comment]
> @xywlpo
> 
> 1. Top-down类型的算法需要接一个目标检测模型，本质上是通过检测将多人关键点任务转化为多个单人关键点检测任务，整体来看精度指标会高于Bottom-up类的算法。  标注上，以COCO数据集的格式为例，是允许一张图片(同一个image_id)中包含多个实例的，只要保证这个实例标注的image_id能与所在图像id对齐即可， 另外实例需要有对应的Bbox信息。
> 2. 您对num_classes的理解是正确的，目前关键点任务主要由num_joints这个参数来控制要预测的关键点的数量。 由于关键点任务中的标注是有特定顺序的，而在常用的数据增强策略中会用到水平翻转策略做数据增强，翻转前后关键点的语义会变化（例如左肩变为右肩），因此通过flip_perm来指定翻转前后序号的对应关系。这里具体可参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/PrepareKeypointDataSet_cn.md 文档对COCO数据集的说明，可以看到都是左-右的对应关系。

非常感谢您的帮助，我还想问一下，config文件中的pixel_std参数是什么意思，如何获得的？因为我训练的数据不是人体
个人觉得，咱们paddledetection做的非常好，不过我也觉得文档可能更加重要，咱们这么好的东西，如果没有一个好的使用文档，会让大家转头其他算法平台的，比如mmpose之类的，到时候哪怕后续文档补上来了，可能一些人也不会再转头使用paddledetection了，非常期待我们的详细使用文档

**Comment by zoooo0820** [comment]
@xywlpo 
非常感谢您的意见，文档清晰可读是十分重要的一部分，我们会尽快补充相关文档内容。
关于您的问题：pixel_std这个参数是一个尺度相关的超参数，具体到使用上，无需考虑这个参数，也不要修改，仍然让它保持200这个取值即可。关于这个参数的引入，在整个Pose预测上其实存在一些历史问题，我们后续会考虑优化这一块。

如果有其他相关的问题或者建议，也欢迎继续提出，这也是我们改进的的重要参考。

**Comment by Dandelion111** [comment]
> 好的，期望参数说明文档能尽快更新，要不参数太多用起来很不方便。那能先帮我解答下面的困惑吗？
> 
> 1. 目前我们的keypoints算法中，higherhrnet是bottom-to-up的，hrnet、lite_hrnet、tiny_pose都是Top-to-down的方法的是吗？对于这种Top-to-down的方法前段是要接一个目标检测吗？这种方法只能处理单个目标的关键点检测吗？标注的文件也只能包含一个目标实例是吗？
> 2. 配置文件中的num_classes是指的有几种类型的实例是吧？比如只做人的关键点检测，num_classes=1? 然后参数中的flip_perm是什么意思？

大佬，关键点检测配置文件参数说明更新了吗

**Comment by zoooo0820** [comment]
@Dandelion111  可以参考这里：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/KeyPointConfigGuide_cn.md
