### ISSUE TITLE
关于PPYOLOV2 epoch和分段式学习超参设置[Other General Issues]

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#4698]
您好我想请问一下PPYOLOV2在进行epoch设定和 分段式学习率调整时是怎么确定的呀。
因为我是用PaddleDetection使用我自己的数据集进行训练时，map在152轮就达到了50.1map，但是之后就逐步下降了。直到在243轮的时候学习率被降低到了1/10时 map才有回升的趋势
![image](https://user-images.githubusercontent.com/78856426/143228579-115330e8-d5c1-4edd-82b6-969d9b4f039b.png)

我想请问一下如果是这种情况下我是不是应该将分段式学习率在的下降轮数从243轮调整到152轮？

**Comment by ghostxsl** [comment]
ppyolov2的学习率策略是在coco上调整的不一定适用于其他数据集，你可以在你自己的数据集上做出适当的调整
