### ISSUE TITLE
抱歉，远程环境已经停止运行并无法自动重启

### ISSUE THREAD

**Issue by 1160300723** [PaddlePaddle/PaddleDetection#47]
在fork开源项目https://aistudio.baidu.com/aistudio/projectdetail/174549 中，进行模型训练约两个epoch时，项目停止运行并弹出如题目提示

**Comment by qingqing01** [comment]
@1160300723 issue是不是发错地方了？ 我看是 `基于transformer的机器翻译系统`,  这里是检测的repo  :)

**Comment by 1160300723** [comment]
哦哦哦，我看官网以为是问题统一上报的方法。。。。抱歉

---原始邮件---
发件人: "qingqing01"<notifications@github.com&gt;
发送时间: 2019年11月28日(星期四) 上午10:25
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"1160300723"<485837652@qq.com&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] 抱歉，远程环境已经停止运行并无法自动重启 (#47)



@1160300723 issue是不是发错地方了？ 我看是 基于transformer的机器翻译系统,  这里是检测的repo  :)

**Comment by qingqing01** [comment]
@1160300723 没关系，我先暂时关闭此issue了~
