### ISSUE TITLE
安装paddledetection出错

### ISSUE THREAD

**Issue by yousong1992** [PaddlePaddle/PaddleDetection#470]
按照安装流程一步一步走的 在进行到测试代码  用行test_architectures.py时 因为系统是win10,开发工具是pycharm,把里面的代码路径改成绝对路径后依然报错，不知道是为什么 

错误提示如下：
test_architectures.py::TestFasterRCNN::test_test <- decorator_helper.py 
test_architectures.py::TestFasterRCNN::test_train <- decorator_helper.py 
test_architectures.py::TestMaskRCNN::test_test <- decorator_helper.py PASSED [  8%]PASSED [ 16%]
test_architectures.py::TestMaskRCNN::test_train <- decorator_helper.py 
test_architectures.py::TestCascadeRCNN::test_test <- decorator_helper.py PASSED [ 25%]PASSED [ 33%]
test_architectures.py::TestCascadeRCNN::test_train <- decorator_helper.py 
test_architectures.py::TestYolov3::test_test <- decorator_helper.py PASSED [ 41%]PASSED [ 50%]PASSED [ 58%]
test_architectures.py::TestYolov3::test_train <- decorator_helper.py PASSED [ 66%]
test_architectures.py::TestRetinaNet::test_test <- decorator_helper.py FAILED [ 75%]
decorator_helper.py:21 (TestRetinaNet.test_test)
args = (<ppdet.modeling.tests.test_architectures.TestRetinaNet testMethod=test_test>,)
kwargs = {}
prog = blocks {
  idx: 0
  parent_idx: -1
}
version {
  version: 1007001
}

startup_prog = blocks {
  idx: 0
  parent_idx: -1
}
version {
  version: 1007001
}

scope = <paddle.fluid.core_avx._Scope object at 0x000001F2FDF661B0>

    def __fn__(*args, **kwargs):
        prog = fluid.Program()
        startup_prog = fluid.Program()
        scope = fluid.core.Scope()
        with fluid.scope_guard(scope):
            with fluid.program_guard(prog, startup_prog):
                with fluid.unique_name.guard():
>                   fn(*args, **kwargs)

**Comment by still-wait** [comment]
@yousong1992 请问是PaddleDetection的哪个分支，release/0.2还是master分支，我们用windows机器测试一下

**Comment by yousong1992** [comment]
我也不清楚是哪个分支，就按照咱们正常的流程下来，到测试那行代码就报错了，错误信息太多了我看不懂…发自我的华为手机-------- 原始邮件 --------发件人： Guanghua Yu <notifications@github.com>日期： 2020年4月10日周五 上午10:50收件人： PaddlePaddle/PaddleDetection <PaddleDetection@noreply.github.com>抄送： yousong1992 <dltbjys1992@163.com>, Mention <mention@noreply.github.com>主    题： Re: [PaddlePaddle/PaddleDetection] 安装paddledetection出错 (#470)

@yousong1992 请问是PaddleDetection的哪个分支，release/0.2还是master分支，我们用windows机器测试一下

**Comment by still-wait** [comment]
刚我们通过测试，发现官方最新代码在windows下测试没有问题，请您重新拉最新代码，然后指定代码python路径，windows的命令行下运行如下：
```shell
set PYTHONPATH=%PYTHONPATH%;.

然后：
```shell
python ppdet/modeling/tests/test_architectures.py

**Comment by yousong1992** [comment]
好的谢谢您发自我的华为手机-------- 原始邮件 --------发件人： Guanghua Yu <notifications@github.com>日期： 2020年4月10日周五 下午4:24收件人： PaddlePaddle/PaddleDetection <PaddleDetection@noreply.github.com>抄送： yousong1992 <dltbjys1992@163.com>, Mention <mention@noreply.github.com>主    题： Re: [PaddlePaddle/PaddleDetection] 安装paddledetection出错 (#470)

刚我们通过测试，发现官方最新代码在windows下测试没有问题，请您重新拉最新代码，然后指定代码python路径，windows的命令行下运行如下：

set PYTHONPATH=%PYTHONPATH%;.



然后：

```shell

python ppdet/modeling/tests/test_architectures.py



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
