### ISSUE TITLE
RCNN 系列模型都无法支持多batch 推理

### ISSUE THREAD

**Issue by Louis8582** [PaddlePaddle/PaddleDetection#4706]
1.  maskrcnn fasterrcnn 支持多batch推理。
查看2.2 2.3的更改，在ppdet/modeling/post_process.py 中的BBoxPostProcess  总是提到Currently only support bs = 1，经过测试确实也是会报错。

目前我比较常用到 maskrcnn fasterrcnn 两种 object detection ，所以已经自行更改成多 batch (并且支持转换静态图，所以我想不是大工程)，但我这样更改不确定在其他模型是否会有所影响，因此束缚了模型更改灵活性。 我想这种应该是常见的需求，希望能近快补足这部份。

**Comment by jerrywgz** [comment]
您好，目前rcnn系列模型在进行多batch推理的时候，如果batch中某一张图片输出为空时的处理还不完善，我们尽快补充这部分能力，也感谢您的反馈
