### ISSUE TITLE
[Document Improvement] 文档链接失效

### ISSUE THREAD

**Issue by YY-GAO** [PaddlePaddle/PaddleDetection#4709]
## 📖  文档优化/Documentation Improvement

PaddleDetection/configs/ppyolo/README_cn.md中PP-YOLO 轻量级模型下 **FAQ** 的链接失效

**Comment by qingqing01** [comment]
感谢指出，我们修改下，可以参考这里 

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/FAQ/FAQ%E7%AC%AC%E9%9B%B6%E6%9C%9F.md#faq%E7%AC%AC%E9%9B%B6%E6%9C%9F
