### ISSUE TITLE
使用关键点检测的部署推理时报错[Other General Issues]

### ISSUE THREAD

**Issue by deepthman** [PaddlePaddle/PaddleDetection#4711]
环境是cuda10.2 cudnn8.3
使用命令:python deploy/python/keypoint_infer.py --model_dir=output_inference/hrnet_w32_384x288/ --image_file=./demo/hrnet_demo.jpg --device=gpu --threshold=0.5
出现以下错误：
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1637837408 (unix time) try "date -d @1637837408" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 18951 (TID 0x7fe1da737700) from PID 0 ***]

未能找到原因

**Comment by wendinghe** [comment]
同问

**Comment by zoooo0820** [comment]
请问能否提供下`output_inference/hrnet_w32_384x288/infer_cfg.yml`的内容呢

**Comment by deepthman** [comment]
> 请问能否提供下`output_inference/hrnet_w32_384x288/infer_cfg.yml`的内容呢

mode: fluid
draw_threshold: 0.5
metric: KeyPointTopDownCOCOEval
use_dynamic_shape: false
arch: HRNet
min_subgraph_size: 3
Preprocess:
- trainsize:
  - 288
  - 384
  type: TopDownEvalAffine
- is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: NormalizeImage
- type: Permute
label_list:
- keypoint

**Comment by black11white** [comment]
遇到了同样的问题，把cudnn换成7.6.5就可以了

**Comment by deepthman** [comment]
> 遇到了同样的问题，把cudnn换成7.6.5就可以了

换了之后跑程序还是显示的cudnn8.3，裂开

**Comment by manongXT** [comment]
> > 遇到了同样的问题，把cudnn换成7.6.5就可以了
> 
> 换了之后跑程序还是显示的cudnn8.3，裂开

我的也是虚拟环境是7.6.5，但是跑起来后却是8.2，请问这个问题你解决了吗？

**Comment by deepthman** [comment]
> > > 遇到了同样的问题，把cudnn换成7.6.5就可以了
> > 
> > 
> > 换了之后跑程序还是显示的cudnn8.3，裂开
> 
> 我的也是虚拟环境是7.6.5，但是跑起来后却是8.2，请问这个问题你解决了吗？

完全卸载重装就行了

**Comment by manongXT** [comment]
> > > > 遇到了同样的问题，把cudnn换成7.6.5就可以了
> > > 
> > > 
> > > 换了之后跑程序还是显示的cudnn8.3，裂开
> > 
> > 
> > 我的也是虚拟环境是7.6.5，但是跑起来后却是8.2，请问这个问题你解决了吗？
> 
> 完全卸载重装就行了

是卸载重装cudnn，还是说重搭虚拟环境？

**Comment by deepthman** [comment]
> > > > > 遇到了同样的问题，把cudnn换成7.6.5就可以了
> > > > 
> > > > 
> > > > 换了之后跑程序还是显示的cudnn8.3，裂开
> > > 
> > > 
> > > 我的也是虚拟环境是7.6.5，但是跑起来后却是8.2，请问这个问题你解决了吗？
> > 
> > 
> > 完全卸载重装就行了
> 
> 是卸载重装cudnn，还是说重搭虚拟环境？

把cudn,cudnn都卸载了再装，我也不熟练只能这样确保能用。最好找个详细点的教程

**Comment by manongXT** [comment]
> > > > > > 遇到了同样的问题，把cudnn换成7.6.5就可以了
> > > > > 
> > > > > 
> > > > > 换了之后跑程序还是显示的cudnn8.3，裂开
> > > > 
> > > > 
> > > > 我的也是虚拟环境是7.6.5，但是跑起来后却是8.2，请问这个问题你解决了吗？
> > > 
> > > 
> > > 完全卸载重装就行了
> > 
> > 
> > 是卸载重装cudnn，还是说重搭虚拟环境？
> 
> 把cudn,cudnn都卸载了再装，我也不熟练只能这样确保能用。最好找个详细点的教程

谢谢解答
