### ISSUE TITLE
卡证检测用哪种模型[Other General Issues]

### ISSUE THREAD

**Issue by xiangfeidecao** [PaddlePaddle/PaddleDetection#4716]
想在ppocr之前用ppdetection检测卡证。生产环境是centos，没有GPU.之前在3090上训练过一个ssd的ssd_mobilenet_v1_300_120e_voc。在cpu环境上大概几十ms。但是在生产环境上速度就比较慢。请问有比较合适的模型推荐吗？还有ssd只能回归出一个矩形位置，有没有哪个模型直接输出畸变的卡证的四个角点？

**Comment by heavengate** [comment]
cpu上的建议使用我们最新推出的PicoDet系列模型，在移动端CPU上精度达到SOTA
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet
畸变角点是什么形式畸变的呢
