### ISSUE TITLE
centos上部署的服务，单独卡证检测用什么模型快速？如果想得到四个角点用哪个模型呢？[Other General Issues]

### ISSUE THREAD

**Issue by xiangfeidecao** [PaddlePaddle/PaddleDetection#4718]
## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
paddlepaddle 2.0.2,
PaddleDetection2.1
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
centos
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
python3.6
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
无，cpu环境

**Comment by heavengate** [comment]
cpu上的建议使用我们最新推出的PicoDet系列模型，在移动端CPU上精度达到SOTA
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet
检测模型默认输出的检测框的格式是[x1, y1, w, h] ，其中x1 y1是左上角的坐标，w, h是检测框的宽度和高度，可以通过这个计算出四个角点的坐标
