### ISSUE TITLE
可以提供一下PP-Tracking行人跨境追踪的训练模型吗？文档里只有车辆的

### ISSUE THREAD

**Issue by gitqinxinyu** [PaddlePaddle/PaddleDetection#4725]

**Comment by nemonameless** [comment]
感谢关注，会尽快更新上去的。复现车辆的可以试试这个项目 https://aistudio.baidu.com/aistudio/projectdetail/3022582

**Comment by cross-hello** [comment]
> _No description provided._

Sorry, I just find the model for human, could you tell me where is the model for cars?

**Comment by cross-hello** [comment]
Oh, sorry, I confuse **MOT** model with others. Now I want to see if it is a car model for *FairMOT*?

**Comment by gitqinxinyu** [comment]
@nemonameless 您好，PP-Tracking行人跨境追踪的训练模型大概什么时候能更新上去？

**Comment by cross-hello** [comment]
> Oh, sorry, I confuse **MOT** model with others. Now I want to see if it is a car model for _FairMOT_?

[Vehicle model, the help from George](https://bj.bcebos.com/v1/paddledet/models/mot/deepsort/ppyolov2_r50vd_dcn_365e_aic21mtmct_vehicle.tar)
