### ISSUE TITLE
VOC格式转COCO格式

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleDetection#4732]
![image](https://user-images.githubusercontent.com/87969070/143562760-5a6c21bd-b37a-4367-b534-e36d60994abf.png)
请问，这种错误是怎么一回事呢？我直接加载的是通过voTT软件生成的VOC格式的文件
![image](https://user-images.githubusercontent.com/87969070/143563073-2e47e9ba-018d-4099-a31f-ffa314fb05c0.png)
这是命令行

**Comment by nemonameless** [comment]
路径问题，路径斜杠请先统一。另外不建议路径有中文名，建议最好都在linux里操作。

**Comment by tianrking** [comment]
解決了嗎
