### ISSUE TITLE
[Document Improvement][Question] Loading pdparams trained model for inference in pytorch

### ISSUE THREAD

**Issue by amitgalor18** [PaddlePaddle/PaddleDetection#4733]
## 📖  文档优化/Documentation Improvement
Hi, is it possible to load a pretrained model in an outside application?
I want to use the model trained in the MOT21 head detection in a pytorch framework, but wasn't able to load and convert the .pdparams file type.
I didn't find a solution in: 
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/load_en.html
My app is based on FairMOT and usually uses torch.load to load models, so I tried using paddle.load instead, and also tried using paddle.load into model.state_dict, but the formats weren't compatible.
Any help would be really appreciated.
Thank you.

**Comment by yghstill** [comment]
@amitgalor18 The code below is convert torch weights to paddle, you can modify it to convert weights to torch:
```python
def load_torch_model(filename):
    weights = torch.load(filename)
    state_dict = weights['state_dict']
    for k in state_dict.keys():
        state_dict[k] = state_dict[k].numpy()
    return state_dict

def load_paddle_model(filename):
    state_dict = paddle.load(filename)
    for k in state_dict.keys():
        state_dict[k] = state_dict[k].numpy()
    return state_dict

def convert(weights, target_name):
    dst = {}
    src = load_torch_model(weights)
    for k, v in weight_name_map.items():
        dst[k] = src[v]
    pickle.dump(dst, open(target_name, 'wb'), protocol=2)
```

**Comment by amitgalor18** [comment]
Thank you very much for sharing the code. How is the variable "weight_name_map" defined?

**Comment by edwardnguyen1705** [comment]
Dear @yghstill ,
> Thank you very much for sharing the code. How is the variable "weight_name_map" defined?
Could you take a look at this? Thanks for your time.
