### ISSUE TITLE
PicoDet 的导出的interface，供C++调用的预训练模型在哪

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleDetection#4737]
## 📖  文档优化/Documentation Improvement

**请简单说明文档存在问题/Please provide a concise and brief description of the documentation problem:**

**请提供有问题的文档部分截图及链接/Please provide the screen shoot and the link of the document:**

**Comment by yghstill** [comment]
@xinsuinizhuan 如果你想得到Inference model，请直接导出即可：
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet#export-and-convert-model
文档下方表格中提供了onnx和Paddle Lite的模型。
