### ISSUE TITLE
PP-TinyPose  官方提供的模型直接放进detect_demo运行崩溃

### ISSUE THREAD

**Issue by guorenqing** [PaddlePaddle/PaddleDetection#4745]
我们期望测试tinyPose f16模型预测效果，把.nb文件导入到官方的iOS  detect_demo  进行测试，结果运行到创建预测器步骤就崩溃了
官方有没有提供tinyPose ios端的demo啊，这类问题新手真不知道怎么弄

**Comment by wangxinxin08** [comment]
tinypose暂时没有ios端的demo
