### ISSUE TITLE
格式转换

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleDetection#4746]
![image](https://user-images.githubusercontent.com/87969070/143834514-51c74b41-c9d3-4ecc-bc1a-fa82c278525e.png)
![image](https://user-images.githubusercontent.com/87969070/143834545-3f178a8d-48c5-45dc-89e5-89302fa362ed.png)
![image](https://user-images.githubusercontent.com/87969070/143834578-82db3fb9-fea2-420d-87a9-adc17a9d37ed.png)
![image](https://user-images.githubusercontent.com/87969070/143834620-61e30748-12ae-4a83-a7c8-728da53a1adb.png)
![image](https://user-images.githubusercontent.com/87969070/143834690-39c10583-768a-494f-87d6-09a45710f234.png)
请问一下，VOC格式转COCO格式报错，这该如何解决呢？

**Comment by lyuwenyu** [comment]
名字是不是没对上
