### ISSUE TITLE
  动态图版本不兼容静态图版本的yolov4进行推理

### ISSUE THREAD

**Issue by Krystalyyyyyy** [PaddlePaddle/PaddleDetection#4749]
## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
请填写命令/A placeholder for the command.
python -u tools/infer.py -c ../static/configs/yolov4/yolov4_cspdarknet_voc.yml\
                         -o weights=D:/AAAAProject/DuoYuTuXiang/Pretrain/model/yolov4_voc/yolov4_cspdarknet_voc.pdparams.pdparams \
                         --infer_dir ../static/configs/yolov4/demo \
                         --draw_threshold 0.3 \
                         --output_dir ../static/configs/yolov4/demo/output

2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
否

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

TypeError: __init__() got an unexpected keyword argument 'with_background'

**Comment by lyuwenyu** [comment]
使用static里的tools试一下吧
