### ISSUE TITLE
[Other General Issues]ssd_vgg16_300.yml文件存在问题？

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#4754]
![image](https://user-images.githubusercontent.com/32217129/144000436-740f4443-cf73-4c88-9c0e-a26ee02c99d6.png)
问题描述看上面的截图，Train和Val采用的都是同一个数据集train2017，这应该不是我搞错了吧？？
文件具体位置：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/static/configs/ssd/ssd_vgg16_300.yml

**Comment by nemonameless** [comment]
是写错了，我们会尽快修改。建议使用动态图版本去训ssd，建议使用release/2.3或develop分支。

**Comment by dengxinlong** [comment]
> 是写错了，我们会尽快修改。建议使用动态图版本去训ssd，建议使用release/2.3或develop分支。

嗯嗯，主要是看到你们动态图版本没有通过ssd_vgg16模型对coco数据集的训练，只有对voc的，所以才采用静态图。

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/ssd 有的，不过如果还是要vgg16的话，可以参考ssd_r34_70e_coco.yml 自己修改下数据集配置为coco即可

**Comment by dengxinlong** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/ssd 有的，不过如果还是要vgg16的话，可以参考ssd_r34_70e_coco.yml 自己修改下数据集配置为coco即可

嗯嗯，这倒是，因为以前一直用的是静态图，应该就是修改下面截图的地方就可以吧？
![image](https://user-images.githubusercontent.com/32217129/144016070-2df5d982-7f09-46fe-a2f4-6ee4e11b8192.png)


 还有一个问题就是，在SSD中，num_classes好像需要叠加背景类别吧？
![image](https://user-images.githubusercontent.com/32217129/144016236-80696ad9-fa8a-4e5c-bb65-3ec6ed587dca.png)
![image](https://user-images.githubusercontent.com/32217129/144016308-046a2111-b64b-4569-a132-54c532daf45b.png)
针对coco_detection，num_classes为什么不是81，而是80啊？

**Comment by nemonameless** [comment]
动态图里的检测模型都 统一移除了背景类。

**Comment by dengxinlong** [comment]
> 动态图里的检测模型都 统一移除了背景类。

ok，非常感谢您的回复，这个issue可以关闭了。
