### ISSUE TITLE
训练mobilenet yolo占用6G左右的磁盘空间

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#476]
df -h 查看磁盘使用情况，训练mobilenet yolo时，会占用下面这个分区6G左右的容量（这个分区只剩6.4G了），如果不对分区扩容，怎么解决这个问题？ 有人帮忙解决下？
/dev/sda1        29G   21G  6.4G   77% /

**Comment by heavengate** [comment]
数据集放在哪个位置了呢，是不是数据集放在这个下面了或者触发了自动下载数据集了，自动下载数据集和预训练权重存储在`~/.cache/paddle/dataset`和`~/.cache/paddle/weights`目录，可以检查一下

**Comment by JensenHJS** [comment]
数据集是链接的之前已经有的数据集，~/.cache/paddle/dataset里面是空的。weights里面预训练模型只占用了17M

**Comment by heavengate** [comment]
是不是保存的checkpoint占用的空间，可以看下`output`目录下保存的checkpoint，如果不想占用着这么大的空间可以把配置文件里的`snapshot_iter`设置大一些
