### ISSUE TITLE
[Other General Issues]训练自定义数据集报错

### ISSUE THREAD

**Issue by Abris-087** [PaddlePaddle/PaddleDetection#4761]
使用的配置文件是configs/yolov3/yolov3_darknet53_270e_coco.yml，修改了两处：一是增大了worker_num: 2--->8，二是修改了anchors。训练一开始无异常，数个epoch之后突然报如下错误。请问是哪里出错了呢？
![image](https://user-images.githubusercontent.com/61613537/144155396-fe2dcd72-3714-4d09-a091-50d7c2056717.png)

**Comment by nemonameless** [comment]
建议先eval一下最新保存的权重，看精度正常与否。建议重新检查下数据集制作过程，并把gt连同其标签一起可视化出来检查下。

**Comment by xiegegege** [comment]
@Abris-087 你是在docker里跑的吗？这个报错应该是共享内存不够了，可以起docker的时候--shm-size 这个参数设置的大些。
