### ISSUE TITLE
检测训练报错

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleDetection#4762]
![94b1151d3739dffa3e53c11e768c311](https://user-images.githubusercontent.com/87969070/144157491-bf1c5782-c70d-4626-9784-ac308fe5f02c.png)
![ebd6e561484d4b65ffe8ef93470107a](https://user-images.githubusercontent.com/87969070/144157499-d05070a6-d096-44b3-8005-bc0028564a70.png)
![5f0ecc144241136605cd31686ea1114](https://user-images.githubusercontent.com/87969070/144157512-56f9176a-8cd7-47c1-9c2c-45c116adebe1.png)
![dd73464bed35352a336ffc7ac54ecf4](https://user-images.githubusercontent.com/87969070/144157522-7b3a31cd-d117-4c86-a375-5e9df4c676c5.png)
训练时报错，说是索引错误，IndexError: index 7 is out of bounds for axis 1 with size 7 请问这种问题如何解决呢？

**Comment by nemonameless** [comment]
首先json文件里的种类定义有问题，你的数据集是几类待测物体呢？如果是1类，那你训练的时候num_classes有没有也修改为1呢？建议重新检查下数据集制作过程，并把gt连同其标签一起可视化出来检查下。

**Comment by Hold-on-li** [comment]
> 首先json文件里的种类定义有问题，你的数据集是几类待测物体呢？如果是1类，那你训练的时候num_classes有没有也修改为1呢？建议重新检查下数据集制作过程，并把gt连同其标签一起可视化出来检查下。

我现在是将num_classes改为1时，报以上的错误，改为2以上的数字就能正确训练，请问这是怎么一回事呢？

**Comment by nemonameless** [comment]
json文件里的种类定义你写了两个，虽然是重复的。去掉一个再num_classes改为1重训下试试
