### ISSUE TITLE
android目标检测实现加载多模型

### ISSUE THREAD

**Issue by xiaofeixuan** [PaddlePaddle/PaddleDetection#4764]
使用demo是PaddleLite-android-demo/yolo_detection_demo ，目标检测功能，目前demo里面是加载单个模型nb文件，现在是想实现加载多个nb模型文件。自己训练的模型再加上自带的模型文件怎么可以同时调用，去检测这两个模型里面存在的所有分类？？

**Comment by yghstill** [comment]
可以到Paddle-Lite-Demo repo中咨询。
如果使用PaddleDetection中的Android Demo，首先在src/main/assets/models/中更新模型：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/static/deploy/android_demo/app/build.gradle#L50
然后更新模型读取：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/static/deploy/android_demo/app/src/main/java/com/baidu/paddledetection/detection/SettingsActivity.java#L74
JNI具体执行逻辑在：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/android_demo/app/src/main/cpp

**Comment by xiaofeixuan** [comment]
> 可以到Paddle-Lite-Demo repo中咨询。 如果使用PaddleDetection中的Android Demo，首先在src/main/assets/models/中更新模型：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/static/deploy/android_demo/app/build.gradle#L50 然后更新模型读取： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/static/deploy/android_demo/app/src/main/java/com/baidu/paddledetection/detection/SettingsActivity.java#L74 JNI具体执行逻辑在： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/android_demo/app/src/main/cpp

是加载多个模型nb文件  ，不是更新呢，更换模型文件我知道在哪里，主要是有两个，怎么同时加载都有效？？

**Comment by yghstill** [comment]
@xiaofeixuan 两个模型同时执行一遍预测逻辑，如果有类别重复的，将输出的所有检测框再利用NMS进行一次过滤。如果两个模型没有类别重复，两个模型的输出结果可以一起可视化后输出。
