### ISSUE TITLE
[Other General Issues] 请问一下说有监控场景下车流量统计的已导出模型哪里可以下载呢？

### ISSUE THREAD

**Issue by voyag8r** [PaddlePaddle/PaddleDetection#4766]
请问一下说有监控场景下车流量统计的已导出模型哪里可以下载呢？
我只找到了自动驾驶和航拍情况下的预训练和导出模型
谢谢

**Comment by nemonameless** [comment]
车流量统计 是一个功能，自动驾驶和航拍情况下的导出模型都可以测试的时候加上车流量统计，在预测语句里加上--do_entrance_counting就可以，可以参照 https://aistudio.baidu.com/aistudio/projectdetail/3022582  step6
