### ISSUE TITLE
yolov3_enhance_reader.yml文件中的NormalizeImage参数mean与std如何生成？

### ISSUE THREAD

**Issue by HaiLongEmb** [PaddlePaddle/PaddleDetection#477]
我想训练私有数据集，有什么工具能在私有数据集上生成mean与std。

感谢各位大神的帮助

**Comment by heavengate** [comment]
是coco数据集上统计的，一般用这个值就可以了，要在自己数据集上统计话的实际上就是遍历所有图像像素求均值和方差

**Comment by HaiLongEmb** [comment]
请问有例子吗？还有一点加这一步处理对提高准确率帮助大吗？我在考虑要不要去掉这一步。

**Comment by heavengate** [comment]
这种例子网上很多的，如 https://blog.csdn.net/dcrmg/article/details/102467434

**Comment by HaiLongEmb** [comment]
感谢
