### ISSUE TITLE
[Feature Request]这个模型可以在单卡上同时对两个camera进行车流量监控吗？

### ISSUE THREAD

**Issue by voyag8r** [PaddlePaddle/PaddleDetection#4776]
这个模型可以在单卡上同时对两个camera进行车流量监控吗？

**Comment by nemonameless** [comment]
可以但不推荐。两个camera的话，需要轨迹融合，就和跨镜头跟踪是一个道理了，但是受限于跨镜头跟踪的方法简单不鲁邦，导致结果精度会大打折扣的。而如果不做跨镜头跟踪，则最终车流量以哪个为准有待商榷，可能两个camera的视觉重叠区域很小或没有，可能两个镜头有时间差，这些都会对结果有很大影响。

**Comment by voyag8r** [comment]
> 可以但不推荐。两个camera的话，需要轨迹融合，就和跨镜头跟踪是一个道理了，但是受限于跨镜头跟踪的方法简单不鲁邦，导致结果精度会大打折扣的。而如果不做跨镜头跟踪，则最终车流量以哪个为准有待商榷，可能两个camera的视觉重叠区域很小或没有，可能两个镜头有时间差，这些都会对结果有很大影响。

我讲的两个摄像头是指两个独立的摄像头，分别做一个输出。

**Comment by nemonameless** [comment]
那你同时跑两个车流量的命令即可

**Comment by voyag8r** [comment]
好吧
