### ISSUE TITLE
Potential bug in method load_config

### ISSUE THREAD

**Issue by thisisi3** [PaddlePaddle/PaddleDetection#4781]
https://github.com/PaddlePaddle/PaddleDetection/blob/f5b0327ead34d72cf96d3413a376285e0bc9969a/ppdet/core/workspace.py#L152

This will update everything to global_config if another_cfg is an empty dict, which is probably not what you want.

**Comment by ghostxsl** [comment]
Thanks~ We will pay attention to this problem.
