### ISSUE TITLE
请问PaddleDetection中哪些算法支持不规则四边形的检测？

### ISSUE THREAD

**Issue by skw1975** [PaddlePaddle/PaddleDetection#4792]
请问PaddleDetection中哪些算法支持不规则四边形的检测？或者支持4个坐标（8顶点）标注数据的目标检测

**Comment by qingqing01** [comment]
现在没有不规则四边形检测模型，有旋转的矩形框检测模型、关键点模型。 您有推荐的模型候选吗？

**Comment by yangy996** [comment]
插眼，很不错的研究方向

**Comment by yangy996** [comment]
> 现在没有不规则四边形检测模型，有旋转的矩形框检测模型、关键点模型。 您有推荐的模型候选吗？

大佬，帮忙看看这个靠谱不
https://xueshu.baidu.com/usercenter/paper/show?paperid=123j02y0d44t0pk0wd1k0px0nb416386&site=xueshu_se
