### ISSUE TITLE
如何实现传入opencv的Mat类型图像数据 做推理？

### ISSUE THREAD

**Issue by opencvfun** [PaddlePaddle/PaddleDetection#48]

**Comment by qingqing01** [comment]
C++推理，可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/inference/predictor/detection_predictor.cpp#L242 

将opencv的Mat的数据指针拿出来，放到 `paddle::PaddleTensor` 里。

**Comment by opencvfun** [comment]
python如何传入opencv的Mat类型进行推理呢？

**Comment by qingqing01** [comment]
请问您具体预测什么模型？以及想怎么使用？以及预测脚本是那个？ 下面是Executor的run的接口，可以使用np.array作为输入

```
    detection, = exe.run(compile_program,
                         feed={'image': img},  # img可以是个np.array，opencv的Mat转换成np.array
                         fetch_list=[out_var], # 输出的variable
                         return_numpy=False)
```

**Comment by qingqing01** [comment]
先关闭此issue，如果有问题，请再打开~

**Comment by qingqing01** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/master/tools/cpp_infer.py  @opencvfun Python端增加了预测示例
