### ISSUE TITLE
paddlelite 端侧部署编译问题

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#4800]
请问各位大佬，如何用aarch64-linux-gnu交叉编译工具编译padllelite预测库以及picodet代码，我的宿主机是x86linux，目标设备是arm linux

**Comment by yghstill** [comment]
可以参考文档：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/lite

**Comment by Dandelion111** [comment]
> 可以参考文档：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/lite

这个文档的步骤是部署到手机上面，我如果要部署的zynq的一个板子上面有什么可以参考的吗
