### ISSUE TITLE
[Other General Issues] pp-tracking测试结果不理想

### ISSUE THREAD

**Issue by 754467737** [PaddlePaddle/PaddleDetection#4801]
大概就是按pp-tracking步骤进行测试，结果不理想
![Uploading 11.png…]()

**Comment by 754467737** [comment]
![11](https://user-images.githubusercontent.com/45877544/144578825-4317ef82-df2c-4e19-9060-94f2c16ff041.png)
![22](https://user-images.githubusercontent.com/45877544/144578830-5d9b531d-e62c-4f3b-9bc1-1acb0021cf89.png)
![33](https://user-images.githubusercontent.com/45877544/144578832-3fbd35c3-b5ac-4c41-86b4-ce432de2ff5e.png)

**Comment by nemonameless** [comment]
尝试降低score阈值，默认0.5，比如试试运行语句后面加--threshold=0.3
