### ISSUE TITLE
tinypose部署在端侧，编译没有问题，检测也没问题，但是到了关键点检测就不执行了，没有报错日志

### ISSUE THREAD

**Issue by Jonsun-N** [PaddlePaddle/PaddleDetection#4808]
OP4EA7:/data/local/tmp/deploy $ ./main keypoint_runtime_config.json
WARNING: linker: Warning: "/data/local/tmp/deploy/libpaddle_light_api_shared.so" unused DT entry: DT_RPATH (type 0xf arg 0x1f7b0) (ignoring)
Usage: ./main [config_path](option) [image_dir](option)
config created
before object detector
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1118 Setup] ARM multiprocessors name: HARDWARE
: QUALCOMM TECHNOLOGIES, INC SM8250
_KONA_KONA_
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1119 Setup] ARM multiprocessors number: 8
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 0, max freq: 99472, min freq: 1804, cluster ID: 1, CPU ARCH: A55
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 1, max freq: 99472, min freq: 1804, cluster ID: 1, CPU ARCH: A55
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 2, max freq: 99472, min freq: 1804, cluster ID: 1, CPU ARCH: A55
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 3, max freq: 99472, min freq: 1804, cluster ID: 1, CPU ARCH: A55
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 4, max freq: 123623, min freq: 2419, cluster ID: 0, CPU ARCH: A77
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 5, max freq: 123623, min freq: 2419, cluster ID: 0, CPU ARCH: A77
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 6, max freq: 123623, min freq: 2419, cluster ID: 0, CPU ARCH: A77
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1121 Setup] ARM multiprocessors ID: 7, max freq: 130198, min freq: 2841, cluster ID: 0, CPU ARCH: A77
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1127 Setup] L1 DataCache size is:
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 256 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 256 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 256 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 256 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 192 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 192 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 192 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1129 Setup] 192 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1131 Setup] L2 Cache size is:
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 512 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 512 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 512 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 512 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 768 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 768 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 768 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1133 Setup] 768 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1135 Setup] L3 Cache size is:
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 4096 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 4096 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 4096 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 4096 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 4096 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 4096 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 4096 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1137 Setup] 4096 KB
[I 12/ 3 11:18: 9.934 ...and/Paddle-Lite/lite/core/device_info.cc:1139 Setup] Total memory: 7706568KB
create object detector
before keypoint detector
create keypoint detector
batchsize of detection forced to be 1 while keypoint model is not empty()class=0 confidence=0.8264 rect=[351 1200 401 1278]
class=0 confidence=0.8114 rect=[560 1188 610 1260]
./demo.jpg The number of detected box: 2
Segmentation fault

**Comment by jerrywgz** [comment]
麻烦发下编译命令吧

**Comment by Jonsun-N** [comment]
> 麻烦发下编译命令吧

编译都是按照给出的指导来的，没有报错
make ARM_ABI=arm8
预测库是直接下载官网给出的，paddle_lite的opt是按照指导编译的./lite/tools/build.sh build_optimize_tool
推理的模型是直接转换成FP32的

**Comment by LMR2018** [comment]
@Jonsun-N  兄弟，出现这个问题知道是什么原因吗？

**Comment by Jonsun-N** [comment]
> @Jonsun-N 兄弟，出现这个问题知道是什么原因吗？

推理代码问题，更换了关键点的个数，相应的推理代码，有的地方没有更正过来。在绘图的时候源代码是有点问题的，可以用VS调试一下。
