### ISSUE TITLE
提示没有足够的空间开辟page

### ISSUE THREAD

**Issue by peace-zy** [PaddlePaddle/PaddleDetection#481]
训练过程中出现
not enough space for reason[failed to malloc 1783 pages at pos[14265] for reason[not found enough pages[avail:0, expect:1783]
但训练还是可以进行，请问开辟page失败对训练有影响吗？通常什么原因导致没有足够空间？谢谢

**Comment by still-wait** [comment]
@peace-zy 在TrainReader

**Comment by peace-zy** [comment]
> @peace-zy 是因为内存资源不足，尝试在TrainReader下设置将memsize或bufsize调大:
> 
> ```
> TrainReader:
>      memsize: 10G
>      bufsize: 32
> ```

@still-wait 非常感谢，还想问一下，内存资源不足的话，是不是有些训练数据就加载失败了，虽然可以继续训练，但每个batch只有部分参与训练？

**Comment by still-wait** [comment]
@peace-zy 是的，在多进程模式下，内存资源不足会导致某些进程挂掉，其余的进程还能继续训练。

**Comment by peace-zy** [comment]
@still-wait 好的，多谢
