### ISSUE TITLE
picodet检测头的个数和其下采样倍数，支持设置吗？

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#4818]
现在picodet的检测头是4个，下采样倍数分别是8， 16， 32， 64，针对不同的数据集可能需要不同的检测头和下采样倍数，如果数据集以小目标为主，32，64倍下采样可能就作用不大，这样就可以只,8,16倍下采样的检测头也能满足需求，请问目前支持这种设置吗？或者后期会支持吗？

**Comment by yghstill** [comment]
@Dandelion111 可以在配置文件中配置修改head的分支数就行：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/_base_/picodet_esnet.yml#L27
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/_base_/picodet_esnet.yml#L30

**Comment by Dandelion111** [comment]
> @Dandelion111 可以在配置文件中配置修改head的分支数就行： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/_base_/picodet_esnet.yml#L27 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/_base_/picodet_esnet.yml#L30

好的，谢谢大佬，如果我去掉2个检测头训练出来的模型大小会不会小一些

**Comment by Dandelion111** [comment]
> @Dandelion111 可以在配置文件中配置修改head的分支数就行： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/_base_/picodet_esnet.yml#L27 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/_base_/picodet_esnet.yml#L30

大佬你好，我更改了    num_fpn_stride=2和 fpn_stride:=[8, 16]，但是会报错，num_feats依然为4，长度与fpn_stride不符
