### ISSUE TITLE
关于SNIPER中使用VisDrone数据集问题

### ISSUE THREAD

**Issue by codedlong** [PaddlePaddle/PaddleDetection#4825]
在PaddleDetection中的sniper模型中，使用的是VisDrone数据集来训练和测试的，想问一下paddle这边能否提供关于这个数据集的转换为coco格式的代码，我这边写了一下，但是始终不对。
链接：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/sniper/ppyolo_r50vd_dcn_1x_visdrone.yml
VisDrone数据集格式是txt形式。

**Comment by lyuwenyu** [comment]
使用tools下的x2coco

**Comment by lyuwenyu** [comment]
链接: https://pan.baidu.com/s/1G3RlSY1kl3qs1BvikomRUA 提取码: jrrs 复制这段内容后打开百度网盘手机App，操作更方便哦
链接: https://pan.baidu.com/s/1Rf_-9GoRFvm-v0GX6tZeYA 提取码: uzc7 复制这段内容后打开百度网盘手机App，操作更方便哦
