### ISSUE TITLE
PP-Tracking可视化界面的行人跨境头追踪模型调用的是多类别小目标模型，而非行人跨境追踪模型，运行会出错。

### ISSUE THREAD

**Issue by gitqinxinyu** [PaddlePaddle/PaddleDetection#4836]
![捕获](https://user-images.githubusercontent.com/40631787/144948284-fd14a358-7da0-4dc0-b6eb-ab3083c0482d.JPG)

**Comment by nemonameless** [comment]
你好，请发下运行命令。也可以更新一下代码再运行一次看看。

**Comment by gitqinxinyu** [comment]
命令为python main.py

**Comment by gitqinxinyu** [comment]
另外行人跨境追踪模型可以提供一下嘛？我看好像目前只有车辆跨境追踪的模型

**Comment by jerrywgz** [comment]
目前GUI还没有支持跨境跟踪的功能，可以先用deploy/pptracking/python下的跨境跟踪

**Comment by gitqinxinyu** [comment]
deploy/pptracking/python下的跨境跟踪也没有行人跨境追踪的模型，只有车辆的。

**Comment by nemonameless** [comment]
> deploy/pptracking/python下的跨境跟踪也没有行人跨境追踪的模型，只有车辆的。

行人跨境跟踪效果不佳，检测模型还是推荐自己的数据集单独训一个，按原先的pp-yolo或picodet的配置训就可以，本质上是检测和reid分离的方法，检测权重是完全独立的，其实甚至可以直接用coco训好的模型权重去测。
