### ISSUE TITLE
[Other General Issues]使用coco类型的数据训练，预测出来的标签不对要在哪修改

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4838]
.json文件中我的类型是fire，但是最后预测出来的标签是people。coco类型数据集的类别要去哪里改？

**Comment by wangxinxin08** [comment]
是使用deploy/python/infer.py预测出来的结果吗？如果是的话，导出模型的时候在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/datasets/coco_detection.yml#L19 指定你自己的标注文件的路径，如dataset/custom/annotations/val.json

**Comment by zmdcs** [comment]
可是我就是按默认的呀，我的val2017.json文件里类别是fire。可是预测出来是people。我用的是PaddleDetection/tools/infer.py

**Comment by wangxinxin08** [comment]
因为TestReader默认的路径没有dataset_dir，所以找不到json文件，此时会加载默认的coco json文件。这样做的初衷是避免用户导出模型时还需要下载coco的json文件，对于自定义数据集的话，你需要指定anno_path，需要把dataset_dir的路径也填上，参考dataset/custom/annotations/val.json，tools/infer.py也需要这么做

**Comment by zmdcs** [comment]
默认路径就是PaddleDetection/dataset/coco/annotations/instance_val2017.json，我把我的.json文件就放在这个文件夹下了呀。然后dataset_dir=dataset/coco也没错呀，默认就是这个，既然能成功训练，就证明路径没错误吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月7日(星期二) 下午4:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] [Other General Issues]使用coco类型的数据训练，预测出来的标签不对要在哪修改 (Issue #4838)





 
因为TestReader默认的路径没有dataset_dir，所以找不到json文件，此时会加载默认的coco json文件。这样做的初衷是避免用户导出模型时还需要下载coco的json文件，对于自定义数据集的话，你需要指定anno_path，需要把dataset_dir的路径也填上，参考dataset/custom/annotations/val.json，tools/infer.py也需要这么做
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zmdcs** [comment]
额,不好意思,说的是TestDataset没有,是没有,我盯着eval那里看了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 下午4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] [Other General Issues]使用coco类型的数据训练，预测出来的标签不对要在哪修改 (Issue #4838)





 
因为TestReader默认的路径没有dataset_dir，所以找不到json文件，此时会加载默认的coco json文件。这样做的初衷是避免用户导出模型时还需要下载coco的json文件，对于自定义数据集的话，你需要指定anno_path，需要把dataset_dir的路径也填上，参考dataset/custom/annotations/val.json，tools/infer.py也需要这么做
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
