### ISSUE TITLE
建议在yaml配置文件中将常用的FLAGS加进去

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleDetection#484]
PaddleDetection/tools/train.py里对FLAGS和cfg文件的读取顺序有点不太方便。。。
FLAGS需要在import paddle之前设置，读取配置文件是在import paddle之后，所以FLAGS不能在yaml配置文件里设置，导致还要改train.py代码，不能在配置文件里一步到位的修改涉及到FLAGS的参数。。。

是否可以考虑将某些常用的，比如FLAGS_selected_gpus等涉及到GPU操作的FLAG添加到yaml配置文件中，免去修改train.py的工作，更简洁点

另外，paddleDetection是默认会使用所有的GPU device么？我有两块，默认都用上了，实际上显存是一块就够够的了。。。

还有个问题想请教下，如果是多个PaddleDetection的不同程序/任务跑在同一块GPU上，使用auto_growth比较好，还是使用预分配显存（观察nvidia-smi得到某个程序的显存占用）的策略比较好呢？

感谢！

**Comment by qingqing01** [comment]
1.  FLAGS您指的是那些呢？ 如果是 FLAGS_selteced_gpus的话，这个无需设置，下面多进程方式启动的话，会自动选择:
     ```
     python -m paddle.distributed.launch --selected_gpus 0,1,2,3,4,5,6,7 tools/train.py --fp16 -c configs/faster_rcnn_r50_fpn_1x.yml
    ````
    
     如果是CUDA_VISIBLE_DEVICES，也无需修改train.py，直接环境变量设置即可。


2.  Paddle的代码一般启动都默认采用所有的显卡， [文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/tutorials/GETTING_STARTED_cn.md) 介绍了，`export CUDA_VISIBLE_DEVICES=0`设置单卡。

3.  2种方式都可以吧，auto_growth在1.7版本已默认开启。参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/singlenode_training_improving/memory_optimize.html#autogrowth

**Comment by nihuizhidao** [comment]
明白了，感谢！
