### ISSUE TITLE
[Other General Issues]如何移植到tx2?

### ISSUE THREAD

**Issue by Gakkifan1314** [PaddlePaddle/PaddleDetection#4845]
您好也许是我看的不仔细的原因，我想问一下这个有无部署到tx2的教程呢？还有若是在目标检测上需要训练自己的数据集需要怎么样进行修改，不胜感激

**Comment by lyuwenyu** [comment]
1. 可以部署 教程在deploy下
2. https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/PrepareDataSet_en.md

**Comment by qingqing01** [comment]
@Gakkifan1314 

TX2设备部署使用Paddle Inference。
C++预言部署参考 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/cpp
Python部署参考 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/python
