### ISSUE TITLE
使用Swin 作为Backbone 使用ema报错

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#4847]
![image](https://user-images.githubusercontent.com/78856426/145148686-e00882a8-0024-4f3b-b2b0-3d3135f264e8.png)

我使用swintransformer的时候加入了ema但是为什么会直接报错呀

**Comment by lyuwenyu** [comment]
因为swin里的pos(int)注册成了buffer  ema的初始化的数据都是float，  导致赋值的时候有问题   这个之后我们会修

着急用的话
1. 修改swin的代码   去掉注册buffer的操作  改成成员变量
2. 修改ema   过滤掉非float类型的变量 不紧张ema操作

**Comment by HeyDWJ** [comment]
现在5月了，请问啥时候修一下呢

**Comment by lwbmowgli** [comment]
这个是不是还没有修啊。。。我用2.3还是报错
