### ISSUE TITLE
将PaddleDetection部署为服务至特定端口

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleDetection#485]
想请问下PaddleDetection是否支持将模型部署为服务的形式，例如将结果发布到某个端口？

**Comment by qingqing01** [comment]
@nihuizhidao PaddleDetection这个项目中还没提供部署的服务，PaddleServing目前也还没提供， 仅仅是服务的话，可以看下PaddleHub是否可以。

**Comment by qingqing01** [comment]
PaddleServing最近提供检测模型的支持，可以参考 https://github.com/PaddlePaddle/Serving/issues/464
