### ISSUE TITLE
gpu个数与batch_size,num_workers如何设置？

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleDetection#4853]
情况描述：
有1000张图片，每张图片大小为1MB.  运行硬件为8张V100, 请问下batch_size如何设置，num_workers如何设置？

**Comment by nemonameless** [comment]
和网络结构有关，一般按照ppdet默认的配置来即可。比如coco一般是8卡训练的，总bs=8 x 单卡bs，对应默认lr。然后如果卡数或单卡bs有变，都按总bs来算，总bs和lr设置按和默认的线性比例来算，比如默认是bs=8 x 2，lr=0.01，如果你用3卡训bs=4 x 3，则lr需设置为0.0075。num_workers就按默认即可。
