### ISSUE TITLE
picodet，在做推理引擎初始化模型的时候报：Segmentation fault is detected by the operating system

### ISSUE THREAD

**Issue by Hoogck** [PaddlePaddle/PaddleDetection#4855]
picodet，在做服务化推理引擎初始化模型的时候报：`Segmentation fault` is detected by the operating system
1.具体报错如下：
[2021-12-09 09:41:33,774] - [DEBUG] - ###Request Id:0,NodeName:chexian.detect.zj_20211209,The batch of input data:1
[2021-12-09 09:41:33,774] - [INFO] - model predicting....

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1639014095 (unix time) try "date -d @1639014095" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 15810 (TID 0x7f7f828a0740) from PID 0 ***]

段错误(吐核)

2.我的环境：
GPU 3090
cuda 11.2
paddle-serving-app        0.7.0                 
paddle-serving-client     0.7.0                     
paddle-serving-server-gpu 0.7.0.post112             
paddlepaddle-gpu          2.2.1  

3.infer_cfg.yml配置，我就把use_dynamic_shape改为了true; target_size 改为 800*800 以及其他threshold
注：在启用use_dynamic_shape 之前是正常的。

**Comment by yghstill** [comment]
@Hoogck PicoDet导出的是静态尺寸，为什么要设置dynamic_shape？使用deploy下的python或者cpp infer脚本可以测试通吗？
