### ISSUE TITLE
picodet非结构化稀疏训练报错

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleDetection#4858]
除了coco_detection.yml配置文件修改了，其他均为修改。参照文档执行的命令，但是有报错

!python3.7 -m paddle.distributed.launch --log_dir=log_test --gpus 0 tools/train.py -c configs/picodet/pruner/picodet_m_320_coco_pruner.yml --slim_config configs/slim/prune/picodet_m_unstructured_prune_75.yml --eval

![微信截图_20211209121326](https://user-images.githubusercontent.com/77316774/145333328-35fcd079-69d5-40b7-b300-bee7e71989b1.png)

**Comment by yghstill** [comment]
@gaorui999 更新PaddleSlim到2.2.1再试下吧。

**Comment by gaorui999** [comment]
![image](https://user-images.githubusercontent.com/77316774/145350327-bc0b24a6-bb04-42f1-9325-be55ec6d8c42.png)

**Comment by gaorui999** [comment]
又出来一个报错，是这样命令导致的from paddleslim import GMPUnstructuredPruner
ImportError: cannot import name 'GMPUnstructuredPruner' from 'paddleslim' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/__init__.py)

**Comment by LMR2018** [comment]
@gaorui999   你好，请问你解决这个问题了吗？我也碰到你第一个问题，你最终是怎么解决的？
