### ISSUE TITLE
[Other General Issues]如果想把知识蒸馏用于其他网络模型，要怎么操作呢？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#4865]
了解到paddleDetection自带的知识蒸馏，是在ImageNet上运行后，将预训练权重带入，如果我想用于其他模型呢？比如yolov4有办法操作吗？

**Comment by ghostxsl** [comment]
参考https://github.com/ghostxsl/PaddleDetection/blob/develop/configs/slim/distill/README.md
