### ISSUE TITLE
实现混淆矩阵分析目标检测

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/PaddleDetection#4866]
## 🚀  实现混淆矩阵分析目标检测

A clear and concise description of the feature proposal.

## 需求原因&示例/Motivation & Examples

混淆矩阵分析实现目标检测性能提升的重要手段。

Tell us why the feature is useful.

[小白都能看懂！手把手教你使用混淆矩阵分析目标检测](https://zhuanlan.zhihu.com/p/443499860)。

Describe what the feature would look like, if it is implemented.
Best demonstrated using **code examples** in addition to words.

**Comment by ghostxsl** [comment]
您的建议对我们的产品非常用帮助，感谢您的支持，我们会将其列入需求列表中～
