### ISSUE TITLE
如何确定对应的ARM CPU是否支持非结构稀疏？

### ISSUE THREAD

**Issue by MengQiDWangChao** [PaddlePaddle/PaddleDetection#4868]
如题

**Comment by minghaoBD** [comment]
谢谢对于稀疏化的关注和问题。

稀疏化推理实现，我们是支持armv7和armv8，并在低端机（SD625、SD660），中端机（SD710，SD835， SD845），和高端机（SD865）验证了加速收益。所以理论上ARM CPU应该都是支持稀疏化加速的。

**Comment by minghaoBD** [comment]
另外，如果想先验证后训练：

可以下载[教程里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/README_PRUNER.md)的[稀疏化模型](https://paddledet.bj.bcebos.com/models/slim/picodet_m_320__coco_sparse_85.pdparams)，然后在对应的ARM CPU设备上测试速度（请参照[这里](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/lite)），并且额外注意这个[开关](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/README_PRUNER.md#7-%E6%A8%A1%E5%9E%8B%E8%AF%84%E4%BC%B0%E4%B8%8E%E6%8E%A8%E7%90%86%E9%83%A8%E7%BD%B2)。

**Comment by MengQiDWangChao** [comment]
好的，谢谢回复，我去尝试一下

**Comment by MengQiDWangChao** [comment]
> 另外，如果想先验证后训练：
> 
> 可以下载[教程里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/README_PRUNER.md)的[稀疏化模型](https://paddledet.bj.bcebos.com/models/slim/picodet_m_320__coco_sparse_85.pdparams)，然后在对应的ARM CPU设备上测试速度（请参照[这里](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/lite)），并且额外注意这个[开关](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/README_PRUNER.md#7-%E6%A8%A1%E5%9E%8B%E8%AF%84%E4%BC%B0%E4%B8%8E%E6%8E%A8%E7%90%86%E9%83%A8%E7%BD%B2)。

好的，谢谢回复，我去尝试一下

**Comment by MengQiDWangChao** [comment]
> 另外，如果想先验证后训练：
> 
> 可以下载[教程里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/README_PRUNER.md)的[稀疏化模型](https://paddledet.bj.bcebos.com/models/slim/picodet_m_320__coco_sparse_85.pdparams)，然后在对应的ARM CPU设备上测试速度（请参照[这里](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/lite)），并且额外注意这个[开关](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/README_PRUNER.md#7-%E6%A8%A1%E5%9E%8B%E8%AF%84%E4%BC%B0%E4%B8%8E%E6%8E%A8%E7%90%86%E9%83%A8%E7%BD%B2)。

还有一个问题，如果我是在mnn上跑这个稀疏化的模型的需要什么设置那，是否有对应教程

**Comment by minghaoBD** [comment]
> > 另外，如果想先验证后训练：
> > 可以下载[教程里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/README_PRUNER.md)的[稀疏化模型](https://paddledet.bj.bcebos.com/models/slim/picodet_m_320__coco_sparse_85.pdparams)，然后在对应的ARM CPU设备上测试速度（请参照[这里](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/lite)），并且额外注意这个[开关](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/README_PRUNER.md#7-%E6%A8%A1%E5%9E%8B%E8%AF%84%E4%BC%B0%E4%B8%8E%E6%8E%A8%E7%90%86%E9%83%A8%E7%BD%B2)。
> 
> 还有一个问题，如果我是在mnn上跑这个稀疏化的模型的需要什么设置那，是否有对应教程

这个我们没有测试过。可以尝试用ONNX工具转换到MNN支持的模型格式。
但是因为稀疏化在Paddle和MNN都是新功能，不确定会不会存在未知错误。
