### ISSUE TITLE
ppyolo_tiny_quant怎么部署到安卓芯片上？

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#4870]
ppyolo_tiny_quant怎么部署到安卓芯片上？

**Comment by qingqing01** [comment]
可以参考 文档  https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/lite

**Comment by heavengate** [comment]
ppyolo_tiny的量化模型是后量化的，部署的时候是在加载过程中会把量化的int8权重重新加载回fp32的权重，部署流程和fp32是一致的，可以参考 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/lite 或者 https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/object_detection_demo
