### ISSUE TITLE
ppyolo_tiny_quant怎么训练自己的数据？

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#4871]
ppyolo_tiny_quant怎么训练自己的数据？

**Comment by qingqing01** [comment]
@LMR2018 

1. 首先需要使用PPYOLO Tiny训练自己的数据，具体流程参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/ppyolo/README_cn.md

2. 量化的话，如果仅仅是为了体积减少，建议使用后量化，只量化weight，体积减少，推理时会使用FP32推理，精度微小损失。使用Paddle-Lite的opt工具，参考文档:

https://paddle-lite.readthedocs.io/zh/latest/user_guides/quant_aware.html#id9

```
./OPT \
    --model_dir=<model_param_dir> \
    --model_file=<model_path> \
    --param_file=<param_path> \
    --optimize_out_type=naive_buffer \
    --optimize_out= <output_optimize_model_dir>\
    --quant_model=true \
    --quant_type=QUANT_INT16
```

在COCO上试过量化训练有精度损失，而且量化后加速不明显。


另外， 如果是ARM CPU上使用，也建议您使用  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/README_cn.md  精度比PPYOLO Tiny高，速度也比较好，具体参考文档。
