### ISSUE TITLE
用paddlex和paddlepaddle部署到c#时，出现categoty idis greater than labelsin your config file[BUG]

### ISSUE THREAD

**Issue by liutianwen12138** [PaddlePaddle/PaddleDetection#4872]
![图片](https://user-images.githubusercontent.com/74774788/145695605-df1da5ea-914f-4fef-b707-80e5d63b0daa.png)

**Comment by qingqing01** [comment]
duplicated with https://github.com/PaddlePaddle/PaddleDetection/issues/4873
