### ISSUE TITLE
用paddlex和paddlepaddle部署到c#时，出现categoty id is greater than labels in your config file

### ISSUE THREAD

**Issue by liutianwen12138** [PaddlePaddle/PaddleDetection#4873]
![图片](https://user-images.githubusercontent.com/74774788/145695701-5f86b97d-df66-4cfb-b956-b3e424abf0c8.png)

**Comment by liutianwen12138** [comment]
求指教

**Comment by liutianwen12138** [comment]
模型是faster rcnn,用yolo系列部署就不会出问题，

**Comment by qingqing01** [comment]
@liutianwen12138 看起来指定的config file中关于label 标签映射不太正确。另外，您是PaddleDetection训练，然后用PaddleX部署吗？

**Comment by heavengate** [comment]
你用的PaddleDetection是哪个版本呢，静态图还是动态图，是否`num_classes`配置和数据集里的实际类别数不一致
