### ISSUE TITLE
用paddlex和paddlepaddle生成的faster rcnn模型部署到c#时，出现categoty idis greater than labelsin your config file，error happen while process bboxes[BUG]

### ISSUE THREAD

**Issue by liutianwen12138** [PaddlePaddle/PaddleDetection#4874]
![图片](https://user-images.githubusercontent.com/74774788/145695813-d66017c4-08b2-4ec5-8b8f-cfddf461ba14.png)

**Comment by qingqing01** [comment]
duplicated with https://github.com/PaddlePaddle/PaddleDetection/issues/4873
