### ISSUE TITLE
使用PPTracking做跨镜头跟踪，启动报错Segmentation fault[BUG]

### ISSUE THREAD

**Issue by wanglu362** [PaddlePaddle/PaddleDetection#4875]
按照PPTracking的文档（https://aistudio.baidu.com/aistudio/projectdetail/3022582），运行跨镜头跟踪demo，使用GPU，启动时报错：

<img width="715" alt="图片" src="https://user-images.githubusercontent.com/68686958/145697399-2428170c-2085-4767-834f-2abdce09bd27.png">

**Comment by nemonameless** [comment]
在aistudio上运行有没有相同问题？

**Comment by jerrywgz** [comment]
可以先确定下跨境数据集文件夹里是不是包含其他文件

**Comment by cqlyiyeshu** [comment]
我也遇到一样的问题，在paddledetection的pptracking模型
CUDA_VISIBLE_DEVICES=0 python tools/export_model.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=~/.cache/paddle/weights/fairmot_dla34_30e_1088x608.pdparams
用上面导出的模型，用cpu推断没错
python deploy/pptracking/python/mot_jde_infer.py --model_dir=output_inference/fairmot_dla34_30e_1088x608 --video_file=demo/person.mp4
加了--device=GPU，就出现这个错误
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1639733973 (unix time) try "date -d @1639733973" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 24825 (TID 0x7fbdc7749740) from PID 0 ***]

**Comment by se7enXF** [comment]
我和你遇到一样的问题#4934
