### ISSUE TITLE
[Other General Issues]

### ISSUE THREAD

**Issue by WeizXy** [PaddlePaddle/PaddleDetection#4878]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## 描述问题/Describe the bug
   你好，我在使用PaddleDetection训练时无法开始，始终报错：
    **cudaHostAlloc failed.
    cudaHostAlloc Cannot allocate 32 bytes in CUDAPinnedPlace**

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

 python tools/train.py -c configs/first_work/first_work1.yml --eval --use_vdl=true --vdl_log_dir=Vdl_Dir/vdllog1

2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
 更改了：PaddleDetection/configs/datasets/coco_detection.yml中的目标类别数以及位置定义
                   数据读取和增强是复制的yolov3的配置，只是放大了其中target_size和anchor的尺寸：
                 target_size: [768, 800, 832, 864, 896, 928, 960]
                 anchors: [[13,27], [17,69], [33,44], [64,72], [39,135], [105,126],[130,238], [227,308], [299,595]]

3. 您使用的数据集是？/What dataset did you use?
  公开的数据集：SODA10M，使用了其中带标记的5000张train训练集图像。

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
`loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
W1213 10:56:04.051448  7081 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W1213 10:56:04.059582  7081 device_context.cc:422] device: 0, cuDNN Version: 8.1.
W1213 10:56:06.110567  7165 system_allocator.cc:205] cudaHostAlloc failed.
W1213 10:56:06.110623  7165 naive_best_fit_allocator.cc:519] cudaHostAlloc Cannot allocate 32 bytes in CUDAPinnedPlace`

`C++ Traceback (most recent call last):`

`   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
   paddle::framework::SignalHandle(char const*, int)
   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()`

`Error Message Summary:`

`FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1639364166 (unix time) try "date -d @1639364166" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 7081 (TID 0x7f2fd37fe700) from PID 0 ***]`

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
    Paddle:2.1.0
    PaddleDetection:2.2.0

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：
   无

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
   Linux

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
   3.8.10

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
    CUDA： 11.2
    cuDNN：8.1

我在Aistudio上是可以正常训练的，但是在实验室租的云显卡上始终无法开始，麻烦技术大佬帮小弟看看，谢谢！！！！

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

**Comment by jerrywgz** [comment]
请尝试使用cuda10.2版本，之前有遇到过类似的问题可以通过降级cuda版本解决

**Comment by wgq1134711420** [comment]
我也遇到这个问题了 
 Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 10.2
device: 0, cuDNN Version: 7.6.
paddlepaddle-gpu       2.4.2

cudaHostAlloc Cannot allocate 81920000 bytes in CUDAPinnedPlace
您好有解决方案吗

**Comment by JoshvirN** [comment]
Same issue. Do we have a solution to this?
