### ISSUE TITLE
MOT Challenge上面的Head Tracking榜单中的“fairmot_head: FairMOT of PaddleDetection”这一个结果是Paddle官方的结果吗

### ISSUE THREAD

**Issue by GuangyaoZhang** [PaddlePaddle/PaddleDetection#4879]
请问在MOT Challenge上面的Head Tracking中“fairmot_head: FairMOT of PaddleDetection”这一个结果是Paddle官方的结果吗？链接[fairmot_head: FairMOT of PaddleDetection](https://motchallenge.net/method/HT=8&chl=21)，如果是的话，超参数和训练过程具体可以详细说一下吗？

**Comment by nemonameless** [comment]
是的，模型和训练配置具体信息都在 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/mot/headtracking21
