### ISSUE TITLE
S2ANet预测出的框不准

### ISSUE THREAD

**Issue by skw1975** [PaddlePaddle/PaddleDetection#4881]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) /I have read the [FAQ documentation](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) but cannot get the expected help.

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
PaddleDetection 2.3
2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：
PaddleDetection
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
linux  (使用的是aistudio JupyterLab 16G单卡)
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
3.7
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
cuDNN 7.6

数据集为257张图片，13个类别，配置文件使用configs\dota\s2anet_1x_spine.yml，只修改了学习率为原来的1/8，其它的没有修改，训练集和验证集一样，共训练了60个epoch，从预测结果看，分类正常但是检测框部分没能框住文本，请看附图：
![test](https://user-images.githubusercontent.com/7607773/145774831-2a8e9ae3-8674-4d3a-b7c3-49f546eb087e.jpg)

请问大佬，框不准是什么原因？

**Comment by jerrywgz** [comment]
看起来是模型训练效果的问题
