### ISSUE TITLE
模型结构

### ISSUE THREAD

**Issue by isLiuHao** [PaddlePaddle/PaddleDetection#4882]
请问一下训练的时候怎么打印出模型的结构呢？

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/engine/trainer.py#L94
可以在这里 print(self.model)

**Comment by isLiuHao** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/engine/trainer.py#L94 可以在这里 print(self.model)

用的是static版本代码，请问要加在哪呢？

**Comment by jerrywgz** [comment]
可以直接打印 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/static/tools/train.py#L228 里面的train_prog
