### ISSUE TITLE
PP-PicoDet怎么训练自己的数据集？

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#4894]
PP-PicoDet怎么训练自己的数据集？

**Comment by wangxinxin08** [comment]
目前PaddleDetection支持coco格式和voc格式的数据集，你可以考虑转成coco格式或者voc格式的数据集进行训练

**Comment by wangxinxin08** [comment]
可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/PrepareDataSet.md#%E7%94%A8%E6%88%B7%E6%95%B0%E6%8D%AE
