### ISSUE TITLE
mask rcnn本地C++部署，预测无结果

### ISSUE THREAD

**Issue by Ss-shuang123** [PaddlePaddle/PaddleDetection#4899]
尝试最新的paddledetection进行模型部署，将训练好的maskrcnn进行本地cpu部署。
paddledetection部署：
`cmake . -G "Visual Studio 15 2017" -A x64 -T host=x64 -DWITH_GPU=OFF -DWITH_MKL=ON -DCMAKE_BUILD_TYPE=Release -DPADDLE_DIR=E:\paddle_deploy\quick_start\paddle_inference -DPADDLE_LIB_NAME=paddle_inference -DOPENCV_DIR=E:\opencv\opencv -DWITH_KEYPOINT=OFF`
结果：The number of detected box: 0
paddlex部署，按照流程，预测结果正确有值。
都是用同一个inference的库。
一般会是什么问题？有什么debug意见吗？

**Comment by wangxinxin08** [comment]
感谢您的反馈，相关问题我们正在排查中

**Comment by rgkannan676** [comment]
Hi @Ss-shuang123 , Was this issue resolved for you? If so please comment what changes did you make. Thanks.

Hi @wangxinxin08 , Any update on this issue. I am also facing the same issue. Please check #5259 .Thanks.
