### ISSUE TITLE
如何正确得到模型的推理时间和Params

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#4900]
最近在使用PadddleDetection进行相关实验时需要测试模型的推理时间、GFolps和Params，此时遇到了几个问题：
1查询issue发现，最为推荐的测速方式是使用depoly/infer.py，但是我在设置batch=1时所得到的infer_time只能达到35ms(TTFNet,3090,1700张图)，无法取得和原文中相对应的推理时间，所以好奇到底应该如何测速？
2GFolps使用目前paddle所集成的方式，在config/runtime.yml中开启print_flops进行计算，然后Params目前还是不知道要怎么测试，直接看训练过程所保留下来的权重大小可以吗？
3我对PAFNet论文中的实验结果存在着一些疑问，我难以理解的是为什么随着参数量和GFLOPs减少的情况下，模型的推理时间反而增加了，在我看来不应该是参数量和GFLOPs增加，推理时间增加嘛？
<img width="443" alt="image" src="https://user-images.githubusercontent.com/59326436/146117013-5fde2a46-6010-4933-92b1-41208a3bb441.png">

期待您的回复！

**Comment by wangxinxin08** [comment]
1. 我们测速的方法是使用deloy/python/infer.py进行测速，使用V100进行测速，并打开run_benchmark
2. 目前PaddleDetection中暂时没有计算Parameters的方法，后续会考虑添加该功能，你可以加载权重，然后使用python执行
   ```
   import paddle
   import numpy as np
   w = paddle.load('/path/to/parameters')
   p = 0
   for k, v in w.items():
         p += np.prod(v.shape)
   print('parameters: ', p)
   ```
3. F和G的参数量应该有误，参数量应该相较于E增加了少量参数，GFLOPS应该也同比增加了，增加的部分为3个DCN引入的参数量和计算量，Infer time应该测试是准确的

**Comment by ghost** [comment]
> * 我们测速的方法是使用deloy/python/infer.py进行测速，使用V100进行测速，并打开run_benchmark
> * 目前PaddleDetection中暂时没有计算Parameters的方法，后续会考虑添加该功能，你可以加载权重，然后使用python执行
>   ```
>   import paddle
>   import numpy as np
>   w = paddle.load('/path/to/parameters')
>   p = 0
>   for k, v in w.items():
>         p += np.prod(v.shape)
>   print('parameters: ', p)
>   ```
> * F和G的参数量应该有误，参数量应该相较于E增加了少量参数，GFLOPS应该也同比增加了，增加的部分为3个DCN引入的参数量和计算量，Infer time应该测试是准确的

感谢您的回复！
