### ISSUE TITLE
tools/infer.py 返回的预测框顶点数只有4个吗

### ISSUE THREAD

**Issue by skw1975** [PaddlePaddle/PaddleDetection#4901]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) /I have read the [FAQ documentation](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) but cannot get the expected help.

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
python tools/infer.py -c configs/faster_rcnn/faster_rcnn_r34_fpn_1x_coco.yml
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
只修改过学习率为原来的1/8
3. 您使用的数据集是？/What dataset did you use?
自定义数据集，300多张图片，标注的是带角度的旋转框
4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
PaddleDetection2.3
2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：
没有
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
liunix (Studio jupyterNote /linux)
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
3.7
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

cuDNN 7.6
如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

tools/infer.py 返回的预测框只有4个顶点，且预检测出的长、宽以及中心点坐标目测跟实际高度一致，请问faster_rcnn能返回倾斜度吗？

**Comment by wangxinxin08** [comment]
faster rcnn目前暂时不支持旋转框检测，你可以使用https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/dota 检测旋转框
