### ISSUE TITLE
[BUG] ubuntu can't find libavcodec-ffmpeg.so.56, libavformat-ffmpeg.so.56, libavutil-ffmpeg.so.54,libswscale-ffmpeg.so.3

### ISSUE THREAD

**Issue by canghaiyunfan** [PaddlePaddle/PaddleDetection#4903]
ubuntu 18.04 编译tiny-pose C++ 代码， 找不到ibavcodec-ffmpeg.so.56, libavformat-ffmpeg.so.56, libavutil-ffmpeg.so.54,libswscale-ffmpeg.so.3

/usr/bin/ld: warning: libavcodec-ffmpeg.so.56, needed by ../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libavformat-ffmpeg.so.56, needed by ../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libavutil-ffmpeg.so.54, needed by ../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libswscale-ffmpeg.so.3, needed by ../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16, not found (try using -rpath or -rpath-link)

**Comment by zhiboniu** [comment]
请问使用的opencv是自己的版本还是我们编译包自带的版本，看起来是opencv的依赖库没找到。
如果是自己的opencv请编译的时候带上ffmpeg，如果是我们编译环境提供的版本可能下载不完全，清理掉opencv重新编译。

**Comment by canghaiyunfan** [comment]
使用的是paddledetection 带的 opencv-3.4.16_gcc8.2_ffmpeg

重新编译还是一样的错误

**Comment by PSQzzzxk** [comment]
我也是使用自动下载的opencv-3.4.16_gcc8.2_ffmpeg，报错相同，请问有解决方法吗？
