### ISSUE TITLE
trainer.py文件里面的回调类传参问题

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleDetection#4904]
def _init_callbacks(self):
        # 训练train
        if self.mode == 'train':
            self._callbacks = [LogPrinter(self), Checkpointer(self)]
            if self.cfg.get('use_vdl', False):
                self._callbacks.append(VisualDLWriter(self))
            if self.cfg.get('save_proposals', False):
                self._callbacks.append(SniperProposalsGenerator(self))
            self._compose_callback = ComposeCallback(self._callbacks)

def _init_callbacks里的self传入的是class Trainer(object)，而在callbacks.py里面的class Callback(object)初始化时，需要的参数是model类，但是传入的是# <ppdet.engine.trainer.Trainer object at 0x7f62475fc350>，二者不符合。想知道原因是什么？谢谢。

class Callback(object):
    def __init__(self, model):
        self.model = model
    def on_step_begin(self, status):
        pass
    def on_step_end(self, status):
        pass

**Comment by wangxinxin08** [comment]
Callback需要传入的参数其实是Trainer这个Object，因为Callback中往往不仅需要model，有时候也需要一些其他的信息，比如cfg里面的信息，这里model的命名可能引起了歧义

**Comment by wstchhwp** [comment]
> Callback需要传入的参数其实是Trainer这个Object，因为Callback中往往不仅需要model，有时候也需要一些其他的信息，比如cfg里面的信息，这里model的命名可能引起了歧义

好的，谢谢！
