### ISSUE TITLE
关于BBoxPostProcess中的一个问题

### ISSUE THREAD

**Issue by C-ZR** [PaddlePaddle/PaddleDetection#4906]
我修改了yolo的head，输出的通道和普通yolo的不一样，前面部分的代码基本完成修改，但是在后处理部分的BBoxPostProcess中
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/post_process.py#L70
的decode函数部分使用的是paddle的op，请问有没有别的参考代码代替这部分程序用于修改呢？

**Comment by wangxinxin08** [comment]
如果只是输出通道的不同，其实应该可以复用原先的post prcoess，另外一种做法是自己封装一个YOLOBox的函数，参考https://github.com/wangxinxin08/PaddleDetection/blob/ppyolov2-p/ppdet/modeling/layers.py#L610, 然后在配置文件中使用这个类即可

**Comment by C-ZR** [comment]
我试了一下你提供的另外两个YOLOBox的函数，和paddle提供的YOLOBox函数的原理是不一样的，而且不能使用

**Comment by wangxinxin08** [comment]
> 我试了一下你提供的另外两个YOLOBox的函数，和paddle提供的YOLOBox函数的原理是不一样的，而且不能使用

是的，我的意思是你可以参考这个代码写一个解码的函数
