### ISSUE TITLE
paddle detection 进项serving部署时产生的问题

### ISSUE THREAD

**Issue by snoopy1316** [PaddlePaddle/PaddleDetection#4907]
使用paddle servingv0.7.0,在docker中部署，在启动服务端时，显示没有paddle_serving_server模块，但是在使用serving时已经下载了，在路径中可查，具体情况如下：
![image](https://user-images.githubusercontent.com/94336500/146290541-766c51d6-7cd0-4838-b1fa-265ec4788c9f.png)
![image](https://user-images.githubusercontent.com/94336500/146290576-1b5b5d21-ec02-470a-9ef4-17dbe4418e1c.png)
请教该如何解决

**Comment by snoopy1316** [comment]
参考文档：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/serving
https://github.com/PaddlePaddle/Serving/blob/v0.7.0/doc/Quick_Start_CN.md

**Comment by lyuwenyu** [comment]
安装正确了嘛   在server里也提个issue问下吧 https://github.com/PaddlePaddle/Serving/issues
