### ISSUE TITLE
[BUG]jetson nano编译完C++预测库之后，运行程序不能调用摄像头

### ISSUE THREAD

**Issue by Chunssu** [PaddlePaddle/PaddleDetection#4913]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## 描述问题/Describe the bug
根据这篇jetson 编译指南(https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/cpp/docs/Jetson_build.md)，编写完成后，运行main程序
qihang@qihang-nano:~/Downloads/PaddleDetection/deploy/cpp/build$ ./main --model_dir=/home/qihang/Downloads/PaddleDetection/output_inference/picodet_s_192_pedestrian/ --model_dir_keypoint=/home/qihang/Downloads/PaddleDetection/output_inference/tinypose_128x96 --camera_id=0 --device=GPU
会报Usage提示：
Usage: ./main --model_dir=/PATH/TO/INFERENCE_MODEL/ (--model_dir_keypoint=/PATH/TO/INFERENCE_MODEL/)--image_file=/PATH/TO/INPUT/IMAGE/

我根据Usage预测图片，正常运行，能够输出结果。

但是编译指南这篇文档有提到摄像头的优先级顺序最高
优先级顺序：camera_id > video_file > image_dir > image_file。

## 复现/Reproduction

请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
ubuntu 18lts 
请问您使用的Python版本是？/ Please provide the version of Python you used.
3.6
请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
cuda10.2 cudnn8

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by lyuwenyu** [comment]
先检查下单独使用摄像头可以不

**Comment by Chunssu** [comment]
> 先检查下单独使用摄像头可以不

单独使用是可以的

**Comment by dengmingD** [comment]
缺少--image_file参数，没用也得加上
