### ISSUE TITLE
训练的时候忽略有问题的图像

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#4914]
文件名是这样的
`BenɡQueDuanChi_10196.jpg`

但是会报错以下信息：

`ppdet.data.source.voc WARNING: Illegal image file: G:/AI_workspace33/datasets/D0003/JPEGImages\Ben伞QueDuanChi_10196.jpg, and it will be ignored`

Ben伞 名称是什么？

我怎么查看 这个图片 
到底是什么问题 导致的
图片正常 能正常打开

**Comment by nemonameless** [comment]
报错信息显示出错在 ppdet/data/source/voc.py ，代码搜下'Illegal image file' 就能定位到 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/data/source/voc.py#L110 
图片路径存放问题，建议打印路径自查下。
此外图片命名不建议中英文混杂。
