### ISSUE TITLE
bdd100kmot转换问题

### ISSUE THREAD

**Issue by hello3281** [PaddlePaddle/PaddleDetection#4921]
当我在尝试用bdd100k转换mot格式的时候遇到问题，是我的路径存放的问题吗

**Comment by nemonameless** [comment]
请先确保数据集目录正确，原标注json文件是否存在于比如 bdd100k/labels/box_track_20 目录下

**Comment by hello3281** [comment]
> 请先确保数据集目录正确，原目录json文件是否存在于例如bdd100k/labels/box_track_20

这是我的数据集路径，我把tqdm去掉了，上个问题没有出现了，但是出现了新的问题，我不确定是需要更改代码，还是我下
载的json文件的有问题，因为我查看我的json文件里没有videoname，和labels标签，我的json文件是和每一张图片对应的
![2021-12-17 17-16-15 的屏幕截图](https://user-images.githubusercontent.com/91302837/146521631-bbeb30ef-0bc2-4e42-8a7a-a8708b2d536d.png)

**Comment by nemonameless** [comment]
已整理好，36G左右预存好空间，wget https://bj.bcebos.com/v1/paddledet/data/mot/bdd100kmot_vehicle.zip

**Comment by hello3281** [comment]
> 已整理好，36G左右预存好空间，wget https://bj.bcebos.com/v1/paddledet/data/mot/bdd100kmot_vehicle.zip

非常感谢，现在我想用这个数据集训练做fairmot的跨境追踪可以吗，我只找到了deepsort的跨境

**Comment by nemonameless** [comment]
> > 已整理好，36G左右预存好空间，wget https://bj.bcebos.com/v1/paddledet/data/mot/bdd100kmot_vehicle.zip
> 
> 非常感谢，现在我想用这个数据集训练做fairmot的跨境追踪可以吗，我只找到了deepsort的跨境

本质上跨镜头跟踪是多个单镜头跟踪结果的融合，但是严格意义上的跨镜头数据集很难找，推荐使用deepsort方案训bdd100k，然后到你自己的几个不同视角的视频去测下。
