### ISSUE TITLE
pp-picodet怎么用摄像头实时推断输出？

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#4926]
pp-picodet怎么用摄像头实时推断输出？

**Comment by yghstill** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/picodet#deploy 这里面有Paddle Lite和ncnn的Android demo可以实时预测手机摄像头数据。cpp或者python demo可以接收电脑摄像头数据。
