### ISSUE TITLE
跨境头跟踪，reid

### ISSUE THREAD

**Issue by yzqxy** [PaddlePaddle/PaddleDetection#4927]
跨镜头跟踪，原版提供测试的reid模型deepsort_pplcnet_vehicle，正常运行的结果如下
![image](https://user-images.githubusercontent.com/51917814/146481345-cabb262b-aeb6-40f9-b946-ba5d47235ecb.png)

然后我那paddleClas的pplcnet重新训练了个ried模型，并且对比了paddledetection中的reid框架，修改过paddleclas中的backbone进行训练的，然后出现以下问题。input_names从crops变成了x，
![image](https://user-images.githubusercontent.com/51917814/146481145-ab624f9f-58e8-4978-8b75-ae1c95411d77.png)

输出上面的inputs都一样，第一个标签也是crops，但是input_names = self.predictor.get_input_names()获取的就不一样，这个函数的作用是啥？为何出现不同？
![image](https://user-images.githubusercontent.com/51917814/146481666-6c36a9ea-6bf1-4d8c-997f-827014ddad65.png)

**Comment by nemonameless** [comment]
导出模型的过程是在ppdet还是clas下导出的呢？

**Comment by yzqxy** [comment]
我是在clas下导出的，我刚用下面的命令在ppdet下试了下，生成了可以用的模型，不过好像跟下载的一样，跟我训练的初始best_model无关？您看是在ppdet这么导出么
python tools/export_model.py -c configs/mot/deepsort/reid/deepsort_pplcnet_vehicle.yml  -o Global.pretrained_model="output/best_model"

**Comment by nemonameless** [comment]
需要在ppdet下导出，导出模型在ppdet和clas下的通路是不同的。
另外可以先用tools/infer_mot.py的过程跑通一下，结果正常了才说明是没问题的。然后再导出模型去deploy下部署infer使用。

**Comment by yzqxy** [comment]
是按照PaddleDetection给的示例这样做么
![image](https://user-images.githubusercontent.com/51917814/146513300-8fb02186-749f-43ef-8d78-12e77d4c2057.png)
我吧从clas中训练到的best_model,赋值到了det的目录下
![image](https://user-images.githubusercontent.com/51917814/146513447-61b4e523-6c18-4ff9-a0f2-1ef35deec85b.png)
然后按照示例的代码格式跑了下
![image](https://user-images.githubusercontent.com/51917814/146513538-f9884103-6e8f-494b-a5eb-88a99a048485.png)
出来的结果好像还是跟之前的参数是相同的？文件大小啥的都没区别，测了一下也没啥区别
![image](https://user-images.githubusercontent.com/51917814/146513613-0bbada91-700a-4e40-993e-ee0d1bf16c8a.png)
是上面给的命令只能用于检测不能用于reid？还是我的操作有误，请大佬告知

**Comment by nemonameless** [comment]
请参照deepsort导出模型的文档，pptracking里的[doc](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/pptracking/python#2-%E5%AF%B9deepsort%E6%A8%A1%E5%9E%8B%E7%9A%84%E5%AF%BC%E5%87%BA%E5%92%8C%E9%A2%84%E6%B5%8B) 或者config里的 [doc](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/mot/deepsort#3-%E5%AF%BC%E5%87%BA%E9%A2%84%E6%B5%8B%E6%A8%A1%E5%9E%8B) 。
可以先用tools/infer_mot.py的过程跑通一下这个best.pdparams，结果正常了才说明是你这个reid加过来是没问题的，注意修改det_weights和reid_weights，例如：
```
CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/deepsort/deepsort_ppyolov2_pplcnet.yml --video_file={your video name}.mp4 --scaled=True --save_videos -o det_weights=https://paddledet.bj.bcebos.com/models/mot/deepsort/ppyolov2_r50vd_dcn_365e_640x640_mot17half.pdparams
reid_weights=best.pdparams

```

**Comment by yzqxy** [comment]
好的，谢谢大佬！
