### ISSUE TITLE
pip install paddle2onnx安装好0.9版本后，window10运行转化命令，显示'paddle2onnx' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#4929]
pip install paddle2onnx安装好0.9版本后，window10运行转化命令，显示'paddle2onnx' 不是内部或外部命令，也不是可运行的程序，怎么解决？

**Comment by nissansz** [comment]
你好，是怎么解决的？

**Comment by nemonameless** [comment]
python -m paddle2onnx.command 
python环境问题，有些时候这个安装的路径没被系统找到，就会找不到command

**Comment by nissansz** [comment]
简化命令不知道为什么不行了
x2paddle --framework=onnx --model=C:\Users\Ni\Downloads\best_accuracy\chinese_04-sim.onnx --save_dir=C:\Users\Ni\Downloads\best_accuracy\04-sim

只有指定site-packages下的py文件才能执行，有办法简化吗？
python D:\Python3.8.8\Lib\site-packages\x2paddle\convert.py --framework=onnx --model=\\DESKTOP-5T3O8J7\Users\Public\CRNN\checkpoint\230215-cnjp11533\chinese_04.onnx --save_dir=C:\Users\Ni\Downloads\best_accuracy\04-nosim

环境变了加了这2个，没有解决
![image](https://user-images.githubusercontent.com/41010669/219071079-00b59b68-0c25-469e-a887-cc5840900abd.png)
