### ISSUE TITLE
如何使用多个数据集训练？

### ISSUE THREAD

**Issue by qiqcheng** [PaddlePaddle/PaddleDetection#493]
比如我想同时使用COCO和自己定义的数据集训练，自己的数据集已经是COCO格式的了。若我定义类XXXDataSet,在配置文件如何引入我的数据？
是这样吗？
dataset:  
      !COCODataSet 
      dataset_dir: dataset/coco  
      anno_path: annotations/instances_train2017.json  
      image_dir: train2017  
      !XXXDataSet 
      dataset_dir: dataset/xxx
      anno_path: annotations/xxx_instances_train2017.json  
      image_dir: xxx_train2017  

还是说我只能把COCO和自定义的数据合并？

**Comment by qingqing01** [comment]
@qiqcheng 不支持自定义多个数据集，需要合并数据。
