### ISSUE TITLE
[Other General Issues]在jetson nano上关键点预测不准确

### ISSUE THREAD

**Issue by incklaw-working** [PaddlePaddle/PaddleDetection#4931]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) /I have read the [FAQ documentation](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) but cannot get the expected help.

## 描述问题/Describe the bug
我按照[这里](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/keypoint/tiny_pose)的步骤在
jetson nano上部署了pp-tinypose，我直接下载了模型库中提供的对应预测部署模型```picodet_s_192_pedestrian```和```tinypose_128x96```并把他们放到了相应的目录里。
然后执行了
```
python3 deploy/python/det_keypoint_unite_infer.py --det_model_dir=output_inference/picodet_s_320_pedestrian --keypoint_model_dir=output_inference/tinypose_128x96 --image_file={your image file} --device=GPU
```
得到的是
```
-----------  Running Arguments -----------
camera_id: -1
cpu_threads: 1
det_model_dir: output_inference/picodet_s_192_pedestrian
det_threshold: 0.5
device: GPU
enable_mkldnn: False
image_dir: None
image_file: /home/mrx/Downloads/paddledetection/demo/hrnet_demo.jpg
keypoint_batch_size: 1
keypoint_model_dir: output_inference/tinypose_128x96
keypoint_threshold: 0.5
output_dir: output
run_benchmark: False
run_mode: fluid
save_res: False
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dark: True
video_file: None
------------------------------------------
-----------  Model Configuration -----------
Model Arch: PicoDet
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--transform op: PadStride
--------------------------------------------
-----------  Model Configuration -----------
Model Arch: HRNet
Transform Order: 
--transform op: TopDownEvalAffine
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
keypoint visualize image saved to: output/hrnet_demo_vis.png
------------------ Inference Time Info ----------------------
total_time(ms): 1483.7, img_num: 1
average latency time(ms): 1483.70, QPS: 0.673991
preprocess_time(ms): 17.30, inference_time(ms): 1419.50, postprocess_time(ms): 46.90
------------------ Inference Time Info ----------------------
total_time(ms): 767.7, img_num: 2
average latency time(ms): 383.85, QPS: 2.605184
preprocess_time(ms): 128.50, inference_time(ms): 127.30, postprocess_time(ms): 128.10
```

![sendpix0](https://user-images.githubusercontent.com/78078409/146497771-6a675004-52be-443c-8fdc-b36ea5f0bba1.jpg)

然后预测的结果是这样的：
![hrnet_demo_edg](https://user-images.githubusercontent.com/78078409/146498019-5683be8e-2e6a-42f4-af0e-7d9f81af62eb.png)
我是根据[这个网站](https://github.com/Qengineering/Paddle-Jetson-Nano)安装paddle的，会不会和这有关？

我不太清楚还需要提供什么信息，如果有需要请告诉我，我会及时补充。

**Comment by zoooo0820** [comment]
应该和paddle框架的版本有关系，麻烦按照文档描述的将paddle更换到v2.2以上呢

**Comment by incklaw-working** [comment]
> 应该和paddle框架的版本有关系，麻烦按照文档描述的将paddle更换到v2.2以上呢

请问要如何在jetson上配置paddle v2.2？我常识安装whl的时候他告诉我说不兼容这个平台
![sendpix0](https://user-images.githubusercontent.com/78078409/149045593-b5f463e9-0613-48f0-9f5d-07715370d467.jpg)

**Comment by zoooo0820** [comment]
@incklaw-working 可以在[这里](https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html) ，根据环境选择下安装包。
