### ISSUE TITLE
pp-picodet 用转化成的onnx来推断的图片跟直接训练得到的模型推断结果不一样

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#4932]
pp-picodet 用paddle2onnx --model_dir inference_model/picodet_s_320_voc/ --model_filename model.pdmodel  --params_filename model.pdiparams --opset_version 11 --save_file picodet_s_320_voc.onnx
转化成的onnx模型来推断的图片结果，跟直接训练得到的模型推断图片结果不一样，得到的outputs张量好像也没对应上

**Comment by LMR2018** [comment]
pp-picodet  paddle2onnx转化得到的onnx模型的输入张量inputs和输出张量outputs分别是什么？能不能在paddle2onnx转化的时候指定好输出张量outputs？

**Comment by se7enXF** [comment]
> 

两种方法：  
1. 使用Netron打开网络文件查看输入、输出节点信息  
2. 使用onnx直接读取网络输入输出节点，参考我的代码：  
```python
import onnxruntime
session = onnxruntime.InferenceSession(model_path)
input_name = session.get_inputs()[0].name
output_name = session.get_outputs()[0].name
```

**Comment by LMR2018** [comment]
@yghstill  @se7enXF 我查看他们的输出张量outputs命名并不相同，onnx的输出张量是['transpose_10.tmp_0', 'transpose_12.tmp_0', 'transpose_14.tmp_0', 'transpose_16.tmp_0', 'transpose_11.tmp_0', 'transpose_13.tmp_0', 'transpose_15.tmp_0', 'transpose_17.tmp_0']
模型直接训练得到的实际是['bbox', 'bbox_num']，onnx转化的时候我能直接指定输出张量吗？

**Comment by se7enXF** [comment]
> 

bbox的维度一般是[?, 6]，bbox_num的维度一般是[?, 1]，所以你要看输出节点的维度，你只需要拿到符合预期的节点输出，然后后处理一下就可以。

**Comment by LMR2018** [comment]
@se7enXF   onnx模型 outputs的那几个输出张量的shape没看到有符合的啊 [1, 1600, 10]
[1, 400, 10]
[1, 100, 10]
[1, 25, 10]
[1, 1600, 32]
[1, 400, 32]
[1, 100, 32]
[1, 25, 32]

**Comment by yghstill** [comment]
@LMR2018 
1. 转成onnx后你是用什么预测库部署的呢？看下这里面的demo可以满足你的需求吗？https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/picodet#deploy
2. PicoDet的模型输出比较特殊，有8个输出，前4个是每个head输出的class分支，后四个是bbox分支，还需要单独的后处理解码和nms操作，可以看上面的后处理如何做的。
3. 关于output name对应的问题，可以使用netron打开确认下name，在你的预测程序中适配下不同output对应的name即可。
