### ISSUE TITLE
[BUG] 使用GPU推理出现Segmentation fault

### ISSUE THREAD

**Issue by se7enXF** [PaddlePaddle/PaddleDetection#4934]
## 描述问题/Describe the bug  
在服务器上，使用PaddleClas+PaddlePaddle-gpu（使用pip安装）训练模型是正常的，将模型导出后，在本地机器上使用predict_cls.py进行预测，CPU上执行正常。下载了你们提供的检测模型，在本地机器上使用predict_det.py进行预测，CPU上执行正常，推理结果正确。但是在服务器上，使用GPU来运行predict脚本就会出现段错误，检测和分类都会错。    

1. 您使用的命令是？
直接使用python执行推理脚本

2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。
理解，按需修改，训练模型无问题，CPU推理无问题，GPU推理段错误。    

3. 您使用的数据集是？
私有数据集
 
4. 请提供您出现的报错信息及相关log。.
```shell
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1639637073 (unix time) try "date -d @1639637073" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 2426 (TID 0x7f6bfbfad740) from PID 0 ***]

Segmentation fault
```

## 环境
1. 请提供您使用的Paddle和PaddleDetection的版本号
paddlepaddle-gpu==2.2.1（pip安装）
paddleclas==2.3（zip下载）
paddledetection==2.3（zip下载）

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
linux

3. 请问您使用的Python版本是？
python3.8

4. 请问您使用的CUDA/cuDNN的版本号是？
cuda 11.0，cudnn 8.0.4

5. 硬件  
CPU：Intel Xeon Gold 5218  
GPU：NVIDIA Tesla T4
驱动版本：Driver 450，CUDA 11.0

**Comment by nemonameless** [comment]
可以再提供一下更详细的截图报错信息吗？predict_cls.py和predict_det.py是您自己写的代码？可以再PaddleClas下也提issue问下看？

**Comment by se7enXF** [comment]
> 可以再提供一下更详细的截图报错信息吗？predict_cls.py和predict_det.py是您自己写的代码？可以再PaddleClas下也提issue问下看？

错误就这些，没有其他报错。脚本是paddleclas的文件，在[这里](https://github.com/PaddlePaddle/PaddleClas/tree/release/2.3/deploy/python)。这个问题应该是paddlepaddle-gpu内部错误，没必要再去paddleclas踢皮球了。python脚本并没有报错。

**Comment by cqlyiyeshu** [comment]
我也跟你碰到一样的问题，是在跑paddledetection的pptracking，导出来的模型，用cpu推断没错，用gpu就报这个错：
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1639733973 (unix time) try "date -d @1639733973" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 24825 (TID 0x7fbdc7749740) from PID 0 ***]

**Comment by thunder95** [comment]
遇到同样的问题，请问解决了吗?

**Comment by se7enXF** [comment]
> 遇到同样的问题，请问解决了吗?

使用cuda10.1，cudnn7.6.5，就可以正常使用了

**Comment by pengwei1024** [comment]
我也遇到了这个问题，出问题的版本是 cuda10.2 + cudnn8, 改成10.2 + cudnn 7.6.5 就可以了。
在 https://developer.nvidia.com/rdp/cudnn-archive 下载 cudnn 的 tar 包
