### ISSUE TITLE
ssd-r34相关问题

### ISSUE THREAD

**Issue by insoliang** [PaddlePaddle/PaddleDetection#4938]
我想请问为什么ssd-r34的配置文件里
ResNet:
  # index 0 stands for res2
  depth: 34
  norm_type: bn
  freeze_norm: False
  freeze_at: -1
  return_idx: [2]
  num_stages: 3

return_idx只输出了【2】特征图 而不是像vgg一样输出2层再生成4层

还有为什么通道数只能是256呢？

**Comment by nemonameless** [comment]
对标[MLPerf Training Benchmark](https://github.com/mlcommons/training/tree/master/single_stage_detector/ssd)

return_idx: [2] 是指layer4，[0,1,2,3]分别对应layer2,3,4,5，因为是res34使用的就是BasicBlock而不是BottleNeck，输出通道就只是256，res50才是1024（256 * expansion=4）。
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/backbones/resnet.py#L532

**Comment by insoliang** [comment]
> 

谢谢回复！，我想问一下为什么resnetz只用layer4 而不用layer5呀？

**Comment by insoliang** [comment]
> 对标[MLPerf Training Benchmark](https://github.com/mlcommons/training/tree/master/single_stage_detector/ssd)
> 
> return_idx: [2] 是指layer4，[0,1,2,3]分别对应layer2,3,4,5，因为是res34使用的就是BasicBlock而不是BottleNeck，输出通道就只是256，res50才是1024（256 * expansion=4）。 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/backbones/resnet.py#L532

谢谢回复！，我想问一下为什么resnetz只用layer4 而不用layer5呀？

**Comment by nemonameless** [comment]
对标[MLPerf Training Benchmark](https://github.com/mlcommons/training/tree/master/single_stage_detector/ssd)
一般认为 layer4的1/16下采样已经足够，SSD论文发的比FPN论文更早，Faster R-CNN最初也只取layer4一层。

**Comment by insoliang** [comment]
> 对标[MLPerf Training Benchmark](https://github.com/mlcommons/training/tree/master/single_stage_detector/ssd) 一般认为 layer4的1/16下采样已经足够，SSD论文发的比FPN论文更早，Faster R-CNN最初也只取layer4一层。

好的，十分感谢！！
