### ISSUE TITLE
picodet 在安卓端识别精准度很低怎么调整？？

### ISSUE THREAD

**Issue by xiaofeixuan** [PaddlePaddle/PaddleDetection#4939]
https://github.com/marsplus-wjh/Picodet-PaddleLite-AndroidDemo ，示例中，自定义训练的数据集模型，电脑端执行预测命令，infer.py 精准度很高，通过export_model.py 导出的nb文件放置assets对应模型文件中，识别度很低，并且需要拿着手机离图片很近，远了识别不了，需要调整哪里的参数？picodet中picodet_s_320_voc.yml训练的，使用的默认参数，只更改了voc.yml跟batch_size,其他都是默认参数

**Comment by yghstill** [comment]
@xiaofeixuan 
1. 训练时的AP50是多少？使用tools/eval.py评估下模型精度看看。infer.py测试的图片和手机端测试的场景一样吗？训练时的物体大小和测试时最后差不多，如果部署在手机上，多用手机采集一些数据来训练模型。
2. 几卡训练的呢？默认的配置文件是4卡，如果改变卡数的话，需要线性调整学习率。改变batch_size，学习率也需要调低
