### ISSUE TITLE
训练自定义数据集，选取预训练模型时选择问题？

### ISSUE THREAD

**Issue by xiaofeixuan** [PaddlePaddle/PaddleDetection#4940]
通过train.py训练自定义数据集，怎么选择对应的模型，根据自己 识别物体大小还是其他？选择哪个模型进行训练比较合适问题

**Comment by nemonameless** [comment]
推荐ppyolo或picodet，都有不同输出尺度的大模型小模型。
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/ppyolo
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet
