### ISSUE TITLE
pp-picodet模型转化成picodet_s_320_coco.onnx后，怎么演示出box那些东西？

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#4941]
pp-picodet模型转化成picodet_s_320_coco.onnx后，怎么演示出box那些东西？outputs张量有太多了

**Comment by yghstill** [comment]
@LMR2018 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/picodet#deploy  可以参考下NCNN、MNN、openvino的demo~

**Comment by xiangfeidecao** [comment]
请问您解决了吗？onnx转化完之后，我用简化的onnx转IR模型，用网上的output = exec_net.infer(inputs={input_blob: images})推理图片，输出太多了。搞不清怎么用
