### ISSUE TITLE
开启print_flops,_flops函数会导致验证跳过第一个batch[BUG]

### ISSUE THREAD

**Issue by weyoung0** [PaddlePaddle/PaddleDetection#4942]
## 描述问题/Describe the bug
print_flops参数设为True时，eval过程会调用一次self._flops函数，导致验证时跳过第一个batch的数据。
执行到self._eval_with_loader函数(trainer.py, line464)有如下操作：
```
if self.cfg.get('print_flops', False):
    self._flops(loader)
for step_id, data in enumerate(loader):
```
而在self._flops函数中，self.loader,704行有如下取值操作：
```
for data in loader:
        input_data = data
        break
```
此时loader的第一个batch已被取出，这导致 for step_id, data in enumerate(loader)操作的取值是从第2个batch开始的，因此最终的Total Sample num数值始终会少一个batch的数量。batch越大，可能对指标的影响越大。
## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
python tools/train.py -c $CONFIG_PATH --eval
```

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

PaddleDetection2.3

**Comment by yghstill** [comment]
@weyoung0 感谢反馈，正在修复

**Comment by yghstill** [comment]
@weyoung0 已修复
