### ISSUE TITLE
pp-picodet模型window单卡训练，gpu的内存已经用满了，但gpu利用率和占比很低，cpu和内存还有很多

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#4946]
pp-picodet模型window单卡训练，gpu的内存已经用满了，但gpu利用率和占比很低，cpu和内存还有很多

**Comment by yghstill** [comment]
@LMR2018 训练时的性能瓶颈在数据IO和预处理，gpu空闲等待较多导致利用率低下，可减少数据预处理方法，或调大worker num
