### ISSUE TITLE
[Other General Issues] 评估模型时只能看系统给出的指标，比如ap50 ap75这些，如果我想看ap25，应该怎么做

### ISSUE THREAD

**Issue by JoyFuture** [PaddlePaddle/PaddleDetection#4948]
![image](https://user-images.githubusercontent.com/35593546/146668300-152ba116-4a23-4094-acf9-eb02ad1c9c73.png)

**Comment by nemonameless** [comment]
#4657 
#4673 
coco格式评估使用的是pycocotools包，源码在此
https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L462
