### ISSUE TITLE
[BUG] Resize 当 keep_ratio=True 时的目标大小计算存在潜在的问题

### ISSUE THREAD

**Issue by vbvg2008** [PaddlePaddle/PaddleDetection#4949]
你们好！我刚刚发现了Resize的目标大小计算可能存在潜在问题， 想和你们分享并确定一下。

可能出现问题的代码在以下几行： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/data/transform/operators.py#L805-L820 ：
```python
        if self.keep_ratio:

            im_size_min = np.min(im_shape[0:2])
            im_size_max = np.max(im_shape[0:2])

            target_size_min = np.min(self.target_size)
            target_size_max = np.max(self.target_size)

            im_scale = min(target_size_min / im_size_min,
                           target_size_max / im_size_max)

            resize_h = im_scale * float(im_shape[0])
            resize_w = im_scale * float(im_shape[1])

            im_scale_x = im_scale
            im_scale_y = im_scale
```
假设原始图片大小为100x50, 目标(target_size)大小为500x800, `keep_ratio`=True

#### 理想的情况
根据图片的高和宽 __分别__ 计算scale, 取最小的scale从而最终可以让图片放在500x800的目标框架中。 在这个例子中，最终目标大小应该从100x50 -> 500x250:
```python
scale = min(500/100, 800/50) # 5
resize_h = scale * height # 500
resize_w = scale * width # 250
```

#### 代码中的情况
在目前的代码中， scale的计算将宽和高混淆在一块， 这样做的坏处是不能保证最终的图片可以放在目标(target_size)框架里. 在这个例子中， 最终目标大小变成800x400， 超出目标范围:
```python
        if self.keep_ratio:

            im_size_min = np.min(im_shape[0:2]) # 50
            im_size_max = np.max(im_shape[0:2]) # 100

            target_size_min = np.min(self.target_size) # 500
            target_size_max = np.max(self.target_size) # 800

            im_scale = min(target_size_min / im_size_min,
                           target_size_max / im_size_max) # min(10, 8) = 8

            resize_h = im_scale * float(im_shape[0]) # 100*8=800
            resize_w = im_scale * float(im_shape[1]) # 50*8=400
```

#### 其他评论
我也尝试过理解目前代码中`target_size`同时适用于高和宽，所以可以将其混淆使用。 但是在 `keep_ratio`=False的逻辑中 目标大小(target_size)的高和宽是明确分开的：
```python
        if self.keep_ratio:
           ...
        else:
            resize_h, resize_w = self.target_size
            im_scale_y = resize_h / im_shape[0]
            im_scale_x = resize_w / im_shape[1]
```

期待回答

**Comment by heavengate** [comment]
感谢反馈，我们修复一下~

**Comment by wangxinxin08** [comment]
@vbvg2008 你应该理解错了，keep_ratio为True时，应该是长边/长边，短边/短边，所以最终im_scale应该是8

**Comment by vbvg2008** [comment]
@wangxinxin08 我觉得这个取决于 `target_size` 的定义。 

如果是长边/长边， 短边/短边的话，`target_size` 的定义就是 (短边目标长度, 长边允许的最大长度)。这也解释了为什么很多模型的config中 `target_size` 是 (800, 1333) 。 因为这个的确和 Detectron 中 Resize 的逻辑一致 https://github.com/facebookresearch/Detectron/blob/main/detectron/utils/blob.py#L111-L116  只不过在Detectron中 这两个数是明确分开的： `target_size` 为 800， `max_size` 是 1333 。现有代码将两个意义完全不同的数一起变成 `target_size` 会给用户带来很多疑惑。

还有当keep_ratio=False的时候， `target_size` 的意义完全改变了， 变成了 （目标长度， 目标宽度）， 这种定义改变也会让用户比较难理解。

只是建议， 希望有帮助。

**Comment by wangxinxin08** [comment]
@vbvg2008 确实这两个逻辑现在是并用的一套逻辑，容易造成混淆，后续我们看看是否把这两种逻辑解耦出来，或者添加文档以及注释以帮助用户理解
