### ISSUE TITLE
关于将swin 放进ssd的backbone，loss不收敛的问题

### ISSUE THREAD

**Issue by insoliang** [PaddlePaddle/PaddleDetection#4951]
https://github.com/PaddlePaddle/PaddleDetection/issues/4922#issue-1082114111
这是之前提的issue，已经尝试改为adamw，还是不收敛，请问还有其他的办法吗？

**Comment by lyuwenyu** [comment]
怎么设置的 把optimizer贴出来看下

**Comment by insoliang** [comment]
> 怎么设置的 把optimizer贴出来看下
OptimizerBuilder:
  clip_grad_by_norm: 1.0
  optimizer:
    type: AdamW
    weight_decay: 0.05
    without_weight_decay_params: ['absolute_pos_embed', 'relative_posit
ion_bias_table', 'norm']

**Comment by insoliang** [comment]
@lyuwenyu 
是这样的：
OptimizerBuilder:
clip_grad_by_norm: 1.0
optimizer:
type: AdamW
weight_decay: 0.05
without_weight_decay_params: ['absolute_pos_embed', 'relative_posit
ion_bias_table', 'norm']

**Comment by lyuwenyu** [comment]
lr呢  贴个完整的吧

**Comment by insoliang** [comment]
> lr呢 贴个完整的吧

@lyuwenyu 

metric: VOC
map_type: 11point
num_classes: 3

#runtime
use_gpu: true
log_iter: 20
save_dir: output
print_flops: false

#optimizer_240e.yml
epoch: 100
LearningRate:
base_lr: 0.0001
schedulers:

!PiecewiseDecay
gamma: 0.1
milestones:
70
90
!LinearWarmup
start_factor: 0.1
steps: 4000

OptimizerBuilder:
clip_grad_by_norm: 1.0
optimizer:
type: AdamW
weight_decay: 0.05
without_weight_decay_params: ['absolute_pos_embed', 'relative_posit
ion_bias_table', 'norm']

architecture: SSD
SSD:
backbone: SwinTransformer
ssd_head: SSDHead
post_process: BBoxPostProcess

SwinTransformer:
embed_dim: 128
depths: [2, 2, 18, 2]
num_heads: [4, 8, 16, 32]
window_size: 7
ape: false
drop_path_rate: 0.1
patch_norm: true
out_indices: [1]

SSDHead:
anchor_generator:
steps: [8, 16, 32, 64, 100, 300]
aspect_ratios: [[2.], [2., 3.], [2., 3.], [2., 3.], [2.], [2.]]
min_sizes: [21.0, 45.0, 99.0, 153.0, 207.0, 261.0]
max_sizes: [45.0, 99.0, 153.0, 207.0, 261.0, 315.0]
offset: 0.5
clip: True
min_max_aspect_ratios_order: True
use_extra_head: True

BBoxPostProcess:
decode:
name: SSDBox
nms:
name: MultiClassNMS
keep_top_k: 200
score_threshold: 0.05
nms_threshold: 0.5
nms_top_k: 400
worker_num: 2

TrainReader:
inputs_def:
num_max_boxes: 90
sample_transforms:
- Decode: {}
- RandomCrop: {allow_no_crop: true}
- Resize: {target_size: [512, 512], keep_ratio: False, interp: 2}
#- RandomFlip: {prob: 0.5}
#- RandomDistort: {brightness: [0.875, 1.125, 0.5], random_apply: Fals
e}
- NormalizeBox: {}
- PadBox: {num_max_boxes: 90}
- NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.2
25], is_scale: true}
- Permute: {}
batch_transforms:
- PadBatch: { pad_to_stride: 32 }
batch_size: 1
shuffle: true
drop_last: true

**Comment by lyuwenyu** [comment]
把swin的pretrained params加上吧
