### ISSUE TITLE
基于ttfnet做个anchor free的实力分割模型

### ISSUE THREAD

**Issue by cloudsurging** [PaddlePaddle/PaddleDetection#4958]
本来想基于ttfnet做个anchor free的实力分割模型，可是能力不够，还是请大神们来帮忙吧。

本人看半天paddledetection源码，也没找到数据处理与加载在哪里做的，怎么就加载出来dict_keys(['im_id', 'curr_iter', 'image', 'im_shape', 'scale_factor', 'ttf_heatmap', 'ttf_box_target', 'ttf_reg_weight', 'epoch_id'])这样结构的数据呢，大神们能讲解一下吗？

**Comment by nemonameless** [comment]
代码全局搜 ttf_heatmap
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/transform/batch_operators.py#L614

建议先看下 [reader的文档 ](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/advanced_tutorials/READER.md#3%E6%95%B0%E6%8D%AE%E9%A2%84%E5%A4%84%E7%90%86)
