### ISSUE TITLE
OIDV5的模型评估AssertionError: the module CascadeRCNNClsAware is not registered

### ISSUE THREAD

**Issue by cao1124** [PaddlePaddle/PaddleDetection#4965]
按照 OIDV5_BASELINE_MODEL.md中的方法去预测，python -u tools/infer.py -c configs/oidv5/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.yml -o weights=./oidv5_cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms/ --infer_img=demo/000000570688.jpg
报错：AssertionError: the module CascadeRCNNClsAware is not registered？

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/static/docs/featured_model/champion_model/OIDV5_BASELINE_MODEL.md
这个文档是静态图下的文档，对应使用静态图下的模型，需要`cd static`到static目录下运行，运行前可以`export PYTHONPATH=`pwd`:$PYTHONPATH`

**Comment by cao1124** [comment]
> Collaborator

您好，按照您讲的执行成功了，谢谢~
大佬，牛逼~
