### ISSUE TITLE
请问如何打印量化后权重每一层的值？

### ISSUE THREAD

**Issue by hp-cuiwb** [PaddlePaddle/PaddleDetection#497]
目前已经通过python slim/quantization/export_model.py转成如下：
![image](https://user-images.githubusercontent.com/47169147/79196308-6edb9300-7e62-11ea-9383-66df7b479935.png)

**Comment by slf12** [comment]
> 目前已经通过python slim/quantization/export_model.py转成如下：
> ![image](https://user-images.githubusercontent.com/47169147/79196308-6edb9300-7e62-11ea-9383-66df7b479935.png)

for var in program.list_vars():
        if var.persistable:
            array = np.array(fluid.global_scope().find_var(var.name).get_tensor())
            print(var.name, array)
可以这样打印出来

**Comment by hp-cuiwb** [comment]
感谢！
