### ISSUE TITLE
voc和coco的map50指标计算方法不同吗？

### ISSUE THREAD

**Issue by JoyFuture** [PaddlePaddle/PaddleDetection#4971]
同一个模型，相同测试集。
这是coco的评估结果
![image](https://user-images.githubusercontent.com/35593546/146855359-d9ad10be-a11d-4ad0-9212-54b48223c38f.png)
zh这是voc的评估结果
![image](https://user-images.githubusercontent.com/35593546/146855385-71f192a2-b063-496c-8675-63779e5894f5.png)
这是什么原因

**Comment by jerrywgz** [comment]
coco和voc的计算方式不同，coco使用的cocoapi计算评估结果，voc使用的是这里的计算方法https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/metrics/map_utils.py#L149

**Comment by nemonameless** [comment]
#4826 #4963 #4657 #4673 #4948
