### ISSUE TITLE
865上picodet推理时间相比官方时间慢很多

### ISSUE THREAD

**Issue by LushZY3300** [PaddlePaddle/PaddleDetection#4973]
picodet_320_s的模型在865上的平均时间为13ms，官方给出的时间为7ms，想咨询下是哪里出了问题，因为tinypose在865上的时间基本和官方时间相同，还有picodet训练速度很慢，单卡，多卡都有实验，结果很慢，和nanodet相比训练时间显著是卡顿的感觉

**Comment by LushZY3300** [comment]
用的paddle lite进行的部署

**Comment by yghstill** [comment]
@LushZY3300 
1. 测试速度是使用fp16预测的吗？
2. 由于数据预处理比较复杂，耗时增加，同时simOTA动态采样方法和ATSS相比慢30%，所以导致整体训练时间慢了。
