### ISSUE TITLE
labelme标注的关键点数据集用paddledection如何转为coco格式

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#4975]
请问paddledection有可以把labelme标注的关键点数据集转为coco格式的功能吗

**Comment by jerrywgz** [comment]
目前还没有提供转换脚本，近期会提供

**Comment by Dandelion111** [comment]
> 目前还没有提供转换脚本，近期会提供

好的，谢谢大佬

**Comment by Dandelion111** [comment]
> 目前还没有提供转换脚本，近期会提供

请问大佬，如果我用自己的数据集训练，转为coco格式的，那我自己的数据集也需要标注17个关键点并且关键点名称和顺序要和coco的保持一致吗，实例的bbox也必须提供吗，我的目标是用picodet扣出来的
