### ISSUE TITLE
检测速度慢，fps数值低导致结果显示特别卡顿

### ISSUE THREAD

**Issue by luckychay** [PaddlePaddle/PaddleDetection#4978]
## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
根据readme中的以下部分：
```bash
# 下载行人跟踪demo视频：
wget https://bj.bcebos.com/v1/paddledet/data/mot/demo/mot17_demo.mp4

# Python预测视频
python deploy/pptracking/python/mot_jde_infer.py --model_dir=output_inference/fairmot_hrnetv2_w18_dlafpn_30e_576x320 --video_file=mot17_demo.mp4 --device=GPU --threshold=0.5 --save_mot_txts --save_images
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
未做任何更改

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
无报错，fps太低，仅仅14左右，检测结果显示卡顿
![7ed319233925daeb01dbc22ccfccbc7](https://user-images.githubusercontent.com/55084546/146954942-84155d63-48fa-4346-8939-785f61a728be.png)

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
Paddle版本2.2.0, PaddleDetection版本2.3.0 

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：
无

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
ubuntu 20.04

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
python 3.7

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
CUDA 10.2， cuDNN 7.6

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by nemonameless** [comment]
这个只是极短的一个demo视频，fps可能还在上涨阶段。另外您使用的GPU机器是什么呢？

**Comment by luckychay** [comment]
谢谢您的回复。
我的GPU是1050Ti， 换用了其他更长的视频仍然一样， 换用其他模型甚至fps只有4左右 。
另外我是使用的官方docker 镜像，在容器内运行。

`W1221 14:11:47.844183  6438 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.0, Runtime API Version: 10.2
W1221 14:11:47.844204  6438 device_context.cc:465] device: 0, cuDNN Version: 7.6.
`

Wed Dec 22 02:10:50 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.156.00   Driver Version: 450.156.00   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P3    N/A /  N/A |    647MiB /  4040MiB |     12%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by Absencell** [comment]
我也是同样的困扰，行人属性检测很卡，rtsp推流播放严重卡顿，完全按照教程来的，使用的轻量化模型也没改善，跳帧也设置了，请教一下 是不是哪里可以进行配置优化，本人纯小白。

配置文件如下：
crop_thresh: 0.5
attr_thresh: 0.5
kpt_thresh: 0.2
visual: True
warmup_frame: 50


DET:
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_s_36e_pipeline.$  batch_size: 1

MOT:
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_s_36e_pipeline.$  tracker_config: deploy/pipeline/config/tracker_config.yml
  batch_size: 1
  skip_frame_num: 2 # preferably no more than 3
  enable: True

KPT:
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/dark_hrnet_w32_256x192.zip
  batch_size: 8

ATTR:
  model_dir:  https://bj.bcebos.com/v1/paddledet/models/pipeline/PPLCNet_x1_0_person_attrib$  batch_size: 8
  enable: True

======================================================================

环境信息：官方docker镜像 registry.baidubce.com/paddlepaddle/paddle:2.3.2-gpu-cuda11.2-cudnn8
环境测试如下
λ 4689c7ec152b /home/PaddleDetection python ppdet/modeling/tests/test_architectures.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
W1021 07:28:11.254982 10218 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.2
W1021 07:28:11.257864 10218 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
.......
----------------------------------------------------------------------
Ran 7 tests in 1.173s

=========================================================================

docker 测试

Fri Oct 21 07:31:55 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.75       Driver Version: 517.40       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A5000    On   | 00000000:01:00.0  On |                  Off |
| 30%   38C    P8    15W / 230W |    357MiB / 24564MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by Absencell** [comment]
@luckychay 你好 请问最后找到解决办法了吗
