### ISSUE TITLE
目标检测模型picodet和关键点检测模型是训练数据集问题

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#4979]
请问，关键点检测模型用的数据是用目标检测模型扣出来之后再进行标注和训练吗？

**Comment by zoooo0820** [comment]
@Dandelion111  
以COCO数据集为例，详细解释可以见[这里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/PrepareKeypointDataSet_cn.md)。

标注上，是按实例进行标注的（即一个人为一个单位）。直接标注该实例每一个部位的点（如左肩，右膝等）在原图尺寸上的坐标，同时也会有该实例对应的boundingbox。
训练上，根据模型不同会有差异，top-down的模型是根据上面标注的检测框抠出来之后再送入网络（相应会有个坐标变换的过程）；bottom-up则一般是原图直接送入网络。但两类模型所用的标注文件是共通的。

**Comment by Dandelion111** [comment]
> @Dandelion111 以COCO数据集为例，详细解释可以见[这里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/PrepareKeypointDataSet_cn.md)。
> 
> 标注上，是按实例进行标注的（即一个人为一个单位）。直接标注该实例每一个部位的点（如左肩，右膝等）在原图尺寸上的坐标，同时也会有该实例对应的boundingbox。 训练上，根据模型不同会有差异，top-down的模型是根据上面标注的检测框抠出来之后再送入网络（相应会有个坐标变换的过程）；bottom-up则一般是原图直接送入网络。但两类模型所用的标注文件是共通的。

谢谢大佬回复，我想用TinyPose进行训练，现在已经训练好了检测模型picodet，不过在标注检测模型的时候没有标注关键点，我如果用TinyPose训练关键点检测模型的话，是再把之前标注的数据标上关键点信息，还是用扣好的目标图像呢？

**Comment by zoooo0820** [comment]
@Dandelion111 
直接在之前的数据中增加关键点标注即可，然后检测模型和关键点模型可以共用一份标注文件

**Comment by Dandelion111** [comment]
> @Dandelion111 直接在之前的数据中增加关键点标注即可，然后检测模型和关键点模型可以共用一份标注文件

好的，谢谢大佬的指导
