### ISSUE TITLE
我自己训练得到的picodet_s_320_coco模型，在rk3399安卓上运行速度很慢，只有7FPS左右，在华为mate 30e pro上是30FPS左右，这是正常的吗？

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#4981]
我自己训练得到的picodet_s_320_coco模型，在rk3399安卓上运行速度很慢，只有7FPS左右，在华为mate 30e pro上是30FPS左右，这是正常的吗？主要是模型的 predict 时间太多

相关命令：
python tools/train.py -c configs/picodet/picodet_s_320_coco.yml --eval

python tools/export_model.py -c configs/picodet/picodet_s_320_coco.yml -o weights=output/picodet_s_320_coco/model_final.pdparams --output_dir=inference_model

paddle_lite_opt  --valid_targets=arm --model_file=picodet_s_320_coco/model.pdmodel --param_file=picodet_s_320_coco/model.pdiparams --optimize_out=picodet_s_320_coco/model
将inference模型配置转化为json格式
python deploy/lite/convert_yml_to_json.py output_inference/picodet_s_320_coco/infer_cfg.yml

![Snipaste_2021-12-22_11-04-57](https://user-images.githubusercontent.com/37955893/147043787-862ebb47-9622-4b15-b0e7-ddb6bf69e468.png)

**Comment by yghstill** [comment]
@LMR2018  看着是正常的，这个预测速度是fp32的，如果是fp16和int8的话速度更快些。可以试下模型量化训练或者非结构化剪枝，加快模型推理速度：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet#quantization

**Comment by zhouweic36** [comment]
这种部署方法能在 linux arm64  ，rk1808上部署吗？

**Comment by 1190202328** [comment]
您好，请问您是如何在rk3399上部署的，我的报错如下：

**root@localhost:/home/topeet/Desktop/deployment_on_rk3399/src# ./run.sh 
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- TARGET ARCH ABI: armv8
-- PADDLE LITE DIR: ../cxx
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Found OpenMP  4.0
-- OpenMP C flags:  -fopenmp
-- OpenMP CXX flags:  -fopenmp
-- OpenMP OpenMP_CXX_LIB_NAMES:  gomp;pthread
-- OpenMP OpenMP_CXX_LIBRARIES:  /usr/lib/gcc/aarch64-linux-gnu/5/libgomp.so;/usr/lib/aarch64-linux-gnu/libpthread.so
-- Found OpenCV: /usr/local (found version "4.5.4") 
-- OpenCV library status:
--     version: 4.5.4
--     libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_stitching;opencv_video;opencv_videoio
--     include path: /usr/local/include/opencv4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/topeet/Desktop/deployment_on_rk3399/src/build
Scanning dependencies of target fruit_detection
[ 50%] Building CXX object CMakeFiles/fruit_detection.dir/fruit_detection.cc.o
[100%] Linking CXX executable fruit_detection
[100%] Built target fruit_detection
1
./run.sh: line 20:  6772 Aborted                 (core dumped) LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${PADDLE_LITE_DIR}/libs/${TARGET_ARCH_ABI} ./fruit_detection /home/topeet/Desktop/deployment_on_rk3399/src/picodet_l_320_coco_lcnet_augmentation.nb /home/topeet/Desktop/deployment_on_rk3399/src/label_list.txt**

请问可能的原因是什么呢？

**Comment by zhouweic36** [comment]
我是在rk1808上跑的demo ，按官方步骤是没有问题的



在 2022-07-09 22:00:35，"JingJiang" ***@***.***> 写道：

您好，请问您是如何在rk3399上部署的，我的报错如下：
***@***.***:/home/topeet/Desktop/deployment_on_rk3399/src# ./run.sh -- The C compiler identification is GNU 5.4.0 -- The CXX compiler identification is GNU 5.4.0 -- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc -- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc -- works -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Detecting C compile features -- Detecting C compile features - done -- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++ -- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++ -- works -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Detecting CXX compile features -- Detecting CXX compile features - done -- TARGET ARCH ABI: armv8 -- PADDLE LITE DIR: ../cxx -- Found OpenMP_C: -fopenmp (found version "4.0") -- Found OpenMP_CXX: -fopenmp (found version "4.0") -- Found OpenMP: TRUE (found version "4.0") -- Found OpenMP 4.0 -- OpenMP C flags: -fopenmp -- OpenMP CXX flags: -fopenmp -- OpenMP OpenMP_CXX_LIB_NAMES: gomp;pthread -- OpenMP OpenMP_CXX_LIBRARIES: /usr/lib/gcc/aarch64-linux-gnu/5/libgomp.so;/usr/lib/aarch64-linux-gnu/libpthread.so -- Found OpenCV: /usr/local (found version "4.5.4") -- OpenCV library status: -- version: 4.5.4 -- libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_stitching;opencv_video;opencv_videoio -- include path: /usr/local/include/opencv4 -- Configuring done -- Generating done -- Build files have been written to: /home/topeet/Desktop/deployment_on_rk3399/src/build Scanning dependencies of target fruit_detection [ 50%] Building CXX object CMakeFiles/fruit_detection.dir/fruit_detection.cc.o [100%] Linking CXX executable fruit_detection [100%] Built target fruit_detection 1 ./run.sh: line 20: 6772 Aborted (core dumped) LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${PADDLE_LITE_DIR}/libs/${TARGET_ARCH_ABI} ./fruit_detection /home/topeet/Desktop/deployment_on_rk3399/src/picodet_l_320_coco_lcnet_augmentation.nb /home/topeet/Desktop/deployment_on_rk3399/src/label_list.txt
请问可能的原因是什么呢？

**Comment by 1190202328** [comment]
您好，我已经解决问题了，原来是paddlelite版本太低了，之前用的2.10，现在用2.11就可以了。
> 我是在rk1808上跑的demo ，按官方步骤是没有问题的 在 2022-07-09 22:00:35，"JingJiang" ***@***.***> 写道： 您好，请问您是如何在rk3399上部署的，我的报错如下： ***@***.***:/home/topeet/Desktop/deployment_on_rk3399/src# ./run.sh -- The C compiler identification is GNU 5.4.0 -- The CXX compiler identification is GNU 5.4.0 -- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc -- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc -- works -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Detecting C compile features -- Detecting C compile features - done -- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++ -- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++ -- works -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Detecting CXX compile features -- Detecting CXX compile features - done -- TARGET ARCH ABI: armv8 -- PADDLE LITE DIR: ../cxx -- Found OpenMP_C: -fopenmp (found version "4.0") -- Found OpenMP_CXX: -fopenmp (found version "4.0") -- Found OpenMP: TRUE (found version "4.0") -- Found OpenMP 4.0 -- OpenMP C flags: -fopenmp -- OpenMP CXX flags: -fopenmp -- OpenMP OpenMP_CXX_LIB_NAMES: gomp;pthread -- OpenMP OpenMP_CXX_LIBRARIES: /usr/lib/gcc/aarch64-linux-gnu/5/libgomp.so;/usr/lib/aarch64-linux-gnu/libpthread.so -- Found OpenCV: /usr/local (found version "4.5.4") -- OpenCV library status: -- version: 4.5.4 -- libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_stitching;opencv_video;opencv_videoio -- include path: /usr/local/include/opencv4 -- Configuring done -- Generating done -- Build files have been written to: /home/topeet/Desktop/deployment_on_rk3399/src/build Scanning dependencies of target fruit_detection [ 50%] Building CXX object CMakeFiles/fruit_detection.dir/fruit_detection.cc.o [100%] Linking CXX executable fruit_detection [100%] Built target fruit_detection 1 ./run.sh: line 20: 6772 Aborted (core dumped) LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${PADDLE_LITE_DIR}/libs/${TARGET_ARCH_ABI} ./fruit_detection /home/topeet/Desktop/deployment_on_rk3399/src/picodet_l_320_coco_lcnet_augmentation.nb /home/topeet/Desktop/deployment_on_rk3399/src/label_list.txt 请问可能的原因是什么呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>
