### ISSUE TITLE
使用自己的数据集做目标跟踪训练报错

### ISSUE THREAD

**Issue by pussss** [PaddlePaddle/PaddleDetection#4982]
![image](https://user-images.githubusercontent.com/86936794/147045100-8f2bc702-6e6c-4ba3-9d62-ea85b3273a32.png)

**Comment by nemonameless** [comment]
可以截图一下你制作的labels_with_ids里的txt吗

**Comment by pussss** [comment]
> 可以截图一下你制作的labels_with_ids里的txt吗

谢谢，我确实发现是labels_with_ids里txt的错误
