### ISSUE TITLE
paddle_lite_opt --model_dir=inference_model/picodet_s_320_coco --valid_targets=arm --optimize_out=picodet_s_320_coco_fp16 --enable_fp16=true 这个命令导出的.nb模型，现在安卓上是使用不了吗？

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#4985]
paddle_lite_opt --model_dir=inference_model/picodet_s_320_coco --valid_targets=arm --optimize_out=picodet_s_320_coco_fp16 --enable_fp16=true 这个命令导出的.nb模型，现在安卓上是使用不了吗？

**Comment by yghstill** [comment]
@LMR2018 可以使用，但是现在官方的Android demo只提供了fp32的预测，fp16预测还在适配中。可以先使用https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/lite 测速，这里支持fp16
