### ISSUE TITLE
TinyPose训练自己的数据集转为coco格式问题

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#4986]
![image](https://user-images.githubusercontent.com/48303408/147053232-69e2a766-3623-4886-a0b6-4ee8a90efe65.png)
请问这个步骤的意思是把自己的数据集关键点的顺序和名称搞成和coco一模一样的吗？Right Shoulder的序号由0变为13是啥意思呢，coco中序号13的名字也不是Right Shoulder啊，我自己的数据集名字和coco中的完全不一样，个数也不一样应该怎么搞呢？

**Comment by zoooo0820** [comment]
@Dandelion111 
这个文档中是因为模型本身用到了coco数据集，因此在加入其他数据的时候要对齐coco，否则同序号点意义不一样导致模型没法训练。
如果是完全自定义的数据集且不考虑用coco原本的数据训练，只需要自己先规定好各点的序号，同序号点的语义是一致的就行。这里参考上面的文档，保证标注的json文件的字段、格式和coco一致，从而让代码能顺利解析标注文件。而字段里的内容则按照实际的标注（如bbox坐标，keypoint坐标、文件名等）填写。

举个例子：如果自定义一个4点的数据集，那么对应在`annotations`中的`keypoint`中按序号将这4个点的坐标和标志位填入即可。对应在模型config文件中的num_joints改为4。
