### ISSUE TITLE
pptracking mot_sde_infer.py  已经选择cpu 报gpu错

### ISSUE THREAD

**Issue by zkailinzhang** [PaddlePaddle/PaddleDetection#4989]
File "/home/aistudio/PaddleDetection/deploy/pptracking/python/det_infer.py", line 462, in load_predictor
    predictor = create_predictor(config)
ValueError: (InvalidArgument) Device id must be less than GPU count, but received id is: 0. GPU count is: 0.
  [Hint: Expected id < GetCUDADeviceCount(), but received id:0 >= GetCUDADeviceCount():0.] (at /paddle/paddle/fluid/platform/gpu_info.cc:350)

!cd ~/PaddleDetection && python deploy/pptracking/python/mot_sde_infer.py --device=CPU --model_dir=output_inference/ppyolov2_r50vd_dcn_365e_aic21mtmct_vehicle/ --reid_model_dir=output_inference/deepsort_pplcnet_vehicle/ --mtmct_dir=./mtmct-demo --device=GPU --mtmct_cfg=deploy/pptracking/python/mtmct_cfg.yml --scaled=True --save_mot_txts --save_images

**Comment by wangxinxin08** [comment]
> !cd ~/PaddleDetection && python deploy/pptracking/python/mot_sde_infer.py --device=CPU --model_dir=output_inference/ppyolov2_r50vd_dcn_365e_aic21mtmct_vehicle/ --reid_model_dir=output_inference/deepsort_pplcnet_vehicle/ --mtmct_dir=./mtmct-demo --device=**GPU** --mtmct_cfg=deploy/pptracking/python/mtmct_cfg.yml --scaled=True --save_mot_txts --save_images

你这边后面又加了一个--device=GPU

**Comment by zkailinzhang** [comment]
是的 多写了
