### ISSUE TITLE
使用picodet的ncnn编译错误

### ISSUE THREAD

**Issue by mjanddy** [PaddlePaddle/PaddleDetection#4992]
![image](https://user-images.githubusercontent.com/27938658/147227084-24cbad4c-de58-42ac-8c7d-6bd294565730.png)
我在使用ncnn过程中编译demo,但是显示路径不对，这个报错应该设置哪个环境变量，已设置ncnn_DIR，但ncnnConfig.cmake不在ncnn_DIR路径下

**Comment by yghstill** [comment]
@mjanddy 请重新检查下ncnn的安装步骤，确保ncnnConfig.cmake存在

**Comment by mjanddy** [comment]
> @mjanddy 请重新检查下ncnn的安装步骤，确保ncnnConfig.cmake存在

ncnnConfig.cmake存在，但是不和ncnn.cmake在同一目录下；ncnn安装步骤是按官方的步骤来的
