### ISSUE TITLE
s2anet训练 mAP过低

### ISSUE THREAD

**Issue by jackiezzq** [PaddlePaddle/PaddleDetection#4993]
## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
使用s2anet_1x_spine.yml配置，只修改了学习率
python tools/train.py -c configs/dota/s2anet_1x_spine.yml --eval

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
loss 在下降但是mAP反而更低了
![image](https://user-images.githubusercontent.com/18511799/147264563-1e8937c9-173e-4abc-bbb3-4675d2d04b20.png)
![image](https://user-images.githubusercontent.com/18511799/147264693-88c7cd12-802e-4010-98c4-77d7984f29ce.png)

## 环境/Environment
aistudio paddle2.2.1

**Comment by lyuwenyu** [comment]
训练完了嘛，  用的什么数据 ， 几个卡训练的， 学习率改成了多少

**Comment by wangxinxin08** [comment]
你好，你是直接训练spine这个数据集吗？使用的PaddlePaddle和PaddleDetection版本是什么？

**Comment by jackiezzq** [comment]
> 
自己标注的旋转数据，发票混贴场景。 
aistudio paddle2.2.1 ppdet develop版本，单卡学习率0.00125

**Comment by wangxinxin08** [comment]
你好，使用自定义数据集的话，需要修改数据集配置文件，如`configs/datasets/spine_coco.yml`，并注意修改num_classes为你所使用的类别，同时注意在`configs/dota/s2anet_1x_spine.yml`修改**S2ANetHead**的num_classes，最后可以加载dota的预训练模型，可以在[S2ANet文档](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/dota)中找到，你需要加载alignconv的预训练模型，即https://paddledet.bj.bcebos.com/models/s2anet_alignconv_2x_dota.pdparams

**Comment by jackiezzq** [comment]
![image](https://user-images.githubusercontent.com/18511799/147327188-fb3799b2-8d61-4dda-a7b8-2ef2a770f75f.png)
自定义数据集这两个个改了的，忘说了。
然后我直接s2anet_1x_spine.yml改学习率0.00125，spine_coco数据集，训练完的mAP也巨低

> 你好，使用自定义数据集的话，需要修改数据集配置文件，如`configs/datasets/spine_coco.yml`，并注意修改num_classes为你所使用的类别，同时注意在`configs/dota/s2anet_1x_spine.yml`修改**S2ANetHead**的num_classes，最后可以加载dota的预训练模型，可以在[S2ANet文档](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/dota)中找到，你需要加载alignconv的预训练模型，即https://paddledet.bj.bcebos.com/models/s2anet_alignconv_2x_dota.pdparams

**Comment by wangxinxin08** [comment]
稍等，我试下

**Comment by wangxinxin08** [comment]
可以尝试可视化下效果，这个训练的精度确实相对较低，但是可视化效果还行，另外加在dota预训练精度会更好一些

**Comment by jackiezzq** [comment]
> 

大概的框是对的，但是角度有点差距，这个训练应该往哪个方向调整？
![image](https://user-images.githubusercontent.com/18511799/147427924-f69f89e0-873d-4fdf-ac70-2681bd04a5b2.png)

**Comment by jackiezzq** [comment]
> 可以尝试可视化下效果，这个训练的精度确实相对较低，但是可视化效果还行，另外加在dota预训练精度会更好一些

大概的框是对的，但是角度有点差距，这个训练应该往哪个方向调整？
![image](https://user-images.githubusercontent.com/18511799/147428084-9502068f-72dd-4ce0-9850-44898ba4acff.png)

**Comment by wangxinxin08** [comment]
可以加载dota预训练模型，以及适当地提高一下回归loss的权重，如果有更多的数据来训练，应该会有更好的效果

**Comment by jackiezzq** [comment]
> 可以加载dota预训练模型，以及适当地提高一下回归loss的权重，如果有更多的数据来训练，应该会有更好的效果

![image](https://user-images.githubusercontent.com/18511799/147443097-c0351760-2949-4428-973a-81d2adcbde26.png)
具体调哪个权重呢

**Comment by wangxinxin08** [comment]
reg_loss_weight可以都适当增加一下

**Comment by changgege195** [comment]
请问map增高了么 我训练了 训练效果还不错 但map也是很低
