### ISSUE TITLE
我在安卓上跑的模型，我怎么修改Java代码和c++代码，才能用Java返回c++预测结果的results值而不是boolean值？

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#4994]
我在安卓上跑的模型，我怎么修改Java代码和c++代码，才能用Java返回c++预测结果的results值而不是boolean值？
官方的代码是直接返回boolean类型的true和false，我想在c++那边直接把目标检测的结果返回到Java中来进行下一步的处理，我该如何修改？

Java所在的代码是：
CameraFragment.java 中的：
 boolean predictor.process(inTextureId, outTextureId, textureWidth, textureHeight, savedImagePath);
Native.java 中的：
 return nativeProcess(ctx, inTextureId, outTextureId, textureWidth, textureHeight, savedImagePath);
c++所在的代码：
Native.cc中的：
return pipeline->Process(inTextureId, outTextureId, textureWidth, textureHeight, savedImagePath);
Pipeline.cc中的：
bool Pipeline::Process(int inTexureId, int outTextureId, int textureWidth,
                       int textureHeight, std::string savedImagePath) {
Pipeline.h中的：
bool->Process(int inTextureId, int outTextureId, int textureWidth,
                 int textureHeight, std::string savedImagePath);

**Comment by lyuwenyu** [comment]
这代码从哪来的  你可以修改一下预测的代码吧

**Comment by LMR2018** [comment]
> 这代码从哪来的 你可以修改一下预测的代码吧

@lyuwenyu   从这里拿来的 https://github.com/marsplus-wjh/Picodet-PaddleLite-AndroidDemo，我在c++那里可以用struct返回多个返回值，但是我要在Java中对应修改他们的返回值类型呢？

**Comment by lyuwenyu** [comment]
那相关的repo下也提个issue吧
