### ISSUE TITLE
[BUG]tiny-pose python 和C++ 预处理代码不一致

### ISSUE THREAD

**Issue by canghaiyunfan** [PaddlePaddle/PaddleDetection#4995]
发现tiny-pose python 和C++ 预处理代码有不一致的地方，请确认下是否有问题

具体在get_affine_transform 函数中
1.
![image](https://user-images.githubusercontent.com/21115878/147327243-19e05452-89ac-494c-a04e-800a1c854fc9.png)
![image](https://user-images.githubusercontent.com/21115878/147327203-151a9cf5-0a08-48ee-a691-65ee1c3178ac.png)
2.
![image](https://user-images.githubusercontent.com/21115878/147327311-4485b81f-d809-4f21-a164-6b1c10e87d47.png)
![image](https://user-images.githubusercontent.com/21115878/147327338-effe2dad-db7c-4931-9f8e-ef14319efc1e.png)

**Comment by zhiboniu** [comment]
这个差别不影响效果

**Comment by canghaiyunfan** [comment]
好的，感谢
