### ISSUE TITLE
labelme标注的数据集训练TinyPose如何转为COCO格式

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#4998]
请问各位大佬，我用labelme标注的关键点数据集，其中目标检测标注了4类，我在目标检测之后对其中的一个目标类进行关键点检测，在标注好了框和关键点，目前不知道应该如何转为coco格式，官方有没有相关的脚本呢？

**Comment by lyuwenyu** [comment]
参考这个脚本 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/tools/x2coco.py
