### ISSUE TITLE
多类别目标跟踪训练自己的数据集， eval过程得到的只有0cls的物体轨迹，并且物体轨迹的坐标为负数

### ISSUE THREAD

**Issue by bppps** [PaddlePaddle/PaddleDetection#5000]
## 描述问题/Describe the bug
多类别目标跟踪训练自己的数据集， eval过程得到的只有0cls的物体轨迹，并且物体轨迹的坐标为负数

## 复现/Reproduction

```
python -m paddle.distributed.launch --log_dir=./mcfairmot_dla34_30e_1088x608_visdrone/ --gpus 0 tools/train.py -c configs/mot/mcfairmot/mcfairmot_dla34_30e_1088x608_visdrone.yml
```
 CUDA_VISIBLE_DEVICES=0 python tools/eval_mot.py -c configs/mot/mcfairmot/mcfairmot_dla34_30e_1088x608_visdrone.yml -o weights=output/mcfairmot_dla34_30e_1088x608_visdrone/0.pdparams

2. 更改代码处：配置文件的类数更改， batchsize改为1

3. eval得到的轨迹
293,1,-142.29570692881188,-146.90969255778572,280.57317224147255,293.8834166142955,0.2890338599681854,0,-1,-1
294,1,-142.34055239197244,-146.94119952612655,280.6626585468102,293.9473673522692,0.2951013445854187,0,-1,-1
295,1,-142.3234443541488,-146.756893703707,280.6287998722457,293.57909577964125,0.2912135720252991,0,-1,-1
296,1,-142.68784519023606,-146.88495048420876,281.3628322953261,293.8310036010118,0.2888449430465698,0,-1,-1
297,1,-142.89437426479643,-146.94084478513474,281.7807889980397,293.94020826892586,0.2879382371902466,0,-1,-1
298,1,-143.12729950981335,-147.00784155514413,282.2440936798664,294.07196244850206,0.2923367917537689,0,-1,-1
299,1,-143.25251067990772,-146.9955820256241,282.49122547521245,294.0450014010443,0.29638877511024475,0,-1,-1

labels with ids:
0 1 0.503125 0.492708 0.950000 0.889583

4. 训练时re_id loss 维持在72左右就收敛了， 但loss 在4左右收敛

**Comment by nemonameless** [comment]
第一个epoch还没训的很好，起码10epoch再eval看看。
bs=1太小了，lr需要跟着改下的，和默认bs算下线性比例改下再训。
自定义数据集，以及多类别时，请仔细检查gt制作过程，可视化确认下框和id种类有没有对上。
另外请提供loss截图(刚开始阶段和训完时的阶段的)，以便分析原因，谢谢。

**Comment by bppps** [comment]
感谢您的回复！gt的制作应该没有问题，但是在dataset初始化的时候出现了这些信息，是否指示类别有问题？
![批注 2021-12-26 144430](https://user-images.githubusercontent.com/44322223/147401177-29582b5c-8dc3-44f8-88e9-1ee301c8fde0.jpg)

**Comment by bppps** [comment]
loss变化如下
![批注 2021-12-26 144900](https://user-images.githubusercontent.com/44322223/147401430-fea26258-03a6-487c-92bb-67eb6083618f.jpg)
![批注 2021-12-26 144312](https://user-images.githubusercontent.com/44322223/147401431-7e833d14-fc67-49ce-b3e1-baf079546110.jpg)

：

**Comment by nemonameless** [comment]
> 感谢您的回复！gt的制作应该没有问题，但是在dataset初始化的时候出现了这些信息，是否指示类别有问题？ ![批注 2021-12-26 144430](https://user-images.githubusercontent.com/44322223/147401177-29582b5c-8dc3-44f8-88e9-1ee301c8fde0.jpg)

你要跟踪的目标的类别有20类吗？这个打印是区分联合数据集时每个数据集对应类别的开始id号的。如果只有1个数据集，这样每个类别的开始id就都是0。

**Comment by nemonameless** [comment]
确定是跟踪20类？建议再检查下gt的id号和类别号。你的loss刚开始感觉太大了有点不正常。

**Comment by bppps** [comment]
> 确定是跟踪20类？建议再检查下gt的id号和类别号。你的loss刚开始感觉太大了有点不正常。

感谢您的回复， 跟踪的类别一共是43类（一共4w4k张图片）。通过打印MOTDataSet中存储的roidb中的内容， 存储的和labelswithid的内容是一致的，并且也包含了多类别，标注的内容也是正确的。数据集的图片size不规则（480 * 640等等），这会对模型的收敛有影响吗，我看到即使是训练很久的权重文件，在训练集上的输出的坐标都是正的，但是置信度很低(小于0.1）

**Comment by chenjw1009** [comment]
可以截图看下评估的数据集的格式吗

**Comment by chenjw1009** [comment]
@SFEcoder 你好，你多类别的gt.txt 是什么样子的，可以截图看下吗
