### ISSUE TITLE
训练TinyPose时开启--eval参数，出现问题

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#5001]
各位大佬，我在训练TinyPose时出现如下错误，
<img width="556" alt="1640424422" src="https://user-images.githubusercontent.com/48303408/147382115-632b2334-4b79-46c6-b099-f2edebaab6cd.png">
我的关键点个数是13个，我已经在配置文件把num_join改为13，coco的个数是17，请问还有别的地方需要改吗
不开启--eval参数可以训练，就是loss开始就很低，只有0.002，最终下降到0.001左右

**Comment by zoooo0820** [comment]
@Dandelion111  请问配置文件中train / eval的对应文件路径是否都更改了呢？

**Comment by Dandelion111** [comment]
> @Dandelion111 请问配置文件中train / eval的对应文件路径是否都更改了呢？

你好，train和eval都已经改成了我自己的数据集路径
![294)PK04~{_ 8G7FZIQPKUD](https://user-images.githubusercontent.com/48303408/147431910-76d8d9ae-9b91-420f-ae6e-62c2c0e34f4f.png)
难道目前TinyPose只能训练17个点的数据集吗，oks_iou函数中的vars是用来干嘛的呢

**Comment by zhiboniu** [comment]
当然可以训练非17个点的，但是不仅仅是改num_joint。
这里的sigma数量也要改的，而且sigmas里的值也应该根据实际点位的可靠范围来估计一个，位置越精确值越小，可以跟coco关键点对应起来看。
还有upper_body_ids、flip_perm还有可视化函数里的关键点链接关系，都是应该根据你自己的点定义做修改的

**Comment by Dandelion111** [comment]
> 当然可以训练非17个点的，但是不仅仅是改num_joint。 这里的sigma数量也要改的，而且sigmas里的值也应该根据实际点位的可靠范围来估计一个，位置越精确值越小，可以跟coco关键点对应起来看。 还有upper_body_ids、flip_perm还有可视化函数里的关键点链接关系，都是应该根据你自己的点定义做修改的

感谢大佬的回复，num_joint、upper_body_ids、flip_perm我都已经改过了，但是不太明白大佬说的sigma数量如何修改，配置文件默认的sigma为2
![image](https://user-images.githubusercontent.com/48303408/147467979-a4d93a92-6930-4267-9ea3-cf735dbc2d2a.png)
如果我训练13个关键点，这个值应该如何修改呢？
大佬说的sigmas是这个吗？
![image](https://user-images.githubusercontent.com/48303408/147468096-e47e74bc-856a-469d-972a-56395ff5fed6.png)

这里面的值根据实际点位的可靠范围来估计一个，是啥意思呢，我是一个小白，对这方面不太明白，希望大佬能给解答一下，谢谢！

**Comment by Victoria-1** [comment]
你好，遇到同样的问题，请问这个sigmas是什么意思呢，怎么估计

**Comment by zoooo0820** [comment]
@Victoria-1 
sigma的来源和计算中的用途，可以参考 https://cocodataset.org/#keypoints-eval 中1.2、1.3小节。
