### ISSUE TITLE
开启trt加速后，模型初始化这一步非常慢

### ISSUE THREAD

**Issue by Songjingze** [PaddlePaddle/PaddleDetection#5005]
## 描述问题/Describe the bug
开启trt加速后，模型初始化这一步非常慢，需要10分钟。
定位到具体代码在 deploy/python/infer.py  564行
    ‘’‘predictor = create_predictor(config)’‘’
## 复现/Reproduction

```none
python .\deploy\python\det_keypoint_unite_infer.py --det_model_dir=output_inference/picodet_s_320_pedestrian --keypoint_model_dir=output_inference/tinypose_256x192 --video_file=E:\tool\test_video\test_yolo.mp4 --device=GPU --run_mode=trt_fp16
```

## 环境/Environment
win10
python3.8 cuda 11.2 cudnn 8.1.1 tensorrt 8.0.1.6

**Comment by qingqing01** [comment]
Paddle-TRT在加载时确实耗时。

**Comment by Songjingze** [comment]
> Paddle-TRT在加载时确实耗时。
感谢回复，在win10 2060 gpu 上跑tiny_pose不用trt加速很难达到实时，用trt的话，加载很慢。我想实时检测肢体关键点，有解决方法吗？

**Comment by zwfcrazy** [comment]
因为用tensorrt加速需要先把模型转换为tensorrt模型，这一步很慢。但是其实这一步只需要做一次，模型转换完之后保存为文件，后面直接加载就可以了。不清楚Paddle是否支持保存tensorrt模型，我们通常都是自己写tensorrt的代码来调用模型的。
