### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by hello3281** [PaddlePaddle/PaddleDetection#5006]
我尝试去训练bdd100k2mot，但是出现了这样的错误AssertionError: The dataset/mot/image_lists is not a directory.，我用的数据是提供的zip包，配置文件如下，我用val评估是没问题的，这是训练执行语句  CUDA_VISIBLE_DEVICES=0 python tools/train.py -c configs/mot/vehicle/fairmot_dla34_30e_1088x608_bdd100kmot_vehicle.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608_bdd100kmot_vehicle.pdparams

TrainDataset:
  !MOTDataSet
    dataset_dir: dataset/mot
    image_lists: ['bdd100kmot_vehicle.train']
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_ide']

EvalMOTDataset:
  !MOTImageFolder
    dataset_dir: dataset/mot
    data_root: bdd100kmot_vehicle/images/val
    keep_ori_im: False # set True if save visualization images or video, or used in DeepSORT

TestMOTDataset:
  !MOTImageFolder
    dataset_dir: dataset/mot
    keep_ori_im: True # set True if save visualization images or video

FairMOT:
  detector: CenterNet
  reid: FairMOTEmbeddingHead
  loss: FairMOTLoss
  tracker: JDETracker

JDETracker:
  min_box_area: 0
  vertical_ratio: 0 # no need to filter bboxes according to w/h
  conf_thres: 0.4
  tracked_thresh: 0.4
  metric_type: cosine

![2021-12-27 14-49-09 的屏幕截图](https://user-images.githubusercontent.com/91302837/147443872-26dc455b-a9d4-49ae-aed4-6dd6ddae67ec.png)

**Comment by nemonameless** [comment]
参考文档
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/mot#%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9B%AE%E5%BD%95 

首先按照以下命令下载image_lists.zip并解压放在PaddleDetection/dataset/mot目录下：
```
wget https://dataset.bj.bcebos.com/mot/image_lists.zip
```

**Comment by hello3281** [comment]
感谢已经可以了，但是训练速度很慢，显示eta两百多天，batchsize为16，work_num=16,rtx3090
