### ISSUE TITLE
infer推断时，保存的置信度最小是0.01？

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleDetection#5007]
你好，我这边infer的时候，发现可视化结果或者是保存的txt中，最小的置信度均为0.01，不可以设置为更小的吗，比如0.0001。我这边尝试将draw_threshold调整为0.0001，最小的置信度仍然为0.01，是模型训练的问题还是nms中卡阈值了？？

**Comment by nemonameless** [comment]
nms中卡阈值了，可自行检查nms配置，搜索下```score_threshold: ```。你所说的情况应该就是设置0.01

**Comment by wstchhwp** [comment]
好的，谢谢！建议这个可以给个配置，因为计算map时这个值很关键

**Comment by nemonameless** [comment]
> 好的，谢谢！建议这个可以给个配置，因为计算map时这个值很关键

模型配置文件里都有设置，例如 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/ppyolo/_base_/ppyolov2_r50vd_dcn.yml#L62
开放的模型的配置默认是coco数据集上最佳的设置了。
