### ISSUE TITLE
MOT模型中哪些是支持多类别的

### ISSUE THREAD

**Issue by LingyvKong** [PaddlePaddle/PaddleDetection#5008]
## 📖  文档优化/Documentation Improvement

请问MOT模型中哪些是支持多类别的？
除了mcfairmot之外，deepsort和JDE是否支持多类别呢？

此外，以下两个链接有矛盾，链接1的数据格式写到支持多类别，链接2写到 "目前仅支持单类别多目标跟踪", 希望可以统一。

链接1：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/mot/README.md
链接2：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/PrepareMOTDataSet_cn.md

**Comment by nemonameless** [comment]
目前只有MCFairMOT 支持多类别跟踪，考虑到单类别行人跟踪FairMOT已经超越JDE很多，所以JDE就没有支持多类别。
DeepSORT受限于ReID权重(一般只用人或车的ReID数据集训的)，故也没有支持多类别。
文档会尽快修复，感谢建议。
