### ISSUE TITLE
pp-picodet使用安卓案例，当安卓用异步线程时cpp文件夹中的Pipeline.h用glReadPixels方法获取像素失败

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#5012]
pp-picodet使用安卓案例，当安卓用异步线程时cpp文件夹中的Pipeline.h用glReadPixels方法获取像素失败，没法正常获取缓存数据data，我应该如何解决？

rgbaImage->create(textureHeight, textureWidth, CV_8UC4);
glReadPixels(0, 0, textureWidth, textureHeight, GL_RGBA, GL_UNSIGNED_BYTE, rgbaImage->data);

**Comment by yghstill** [comment]
@LMR2018 android及JNI调用应该保持在同一线程吧，可以检索下有没有解决方案。
