### ISSUE TITLE
PaddleDetection如何以数据流形式进行预测而非调用文件[Feature Request]

### ISSUE THREAD

**Issue by LFeightyFour** [PaddlePaddle/PaddleDetection#5015]
目前paddledetection的infer.py文件中，是通过ImageFolder的方式加载图像，即只能通过文件输入，这对使用摄像头实时预测带来困难。我想要直接给numpy数据，以数据流形式输入。
我看到今年二月份有类似的提问，我看到回复是两种处理方式。
方式一是使用旧的infer.py代码，但其中使用了fluid模块，这个模块现在已不提倡使用。
方式二是自行增加数据流形式的DataSet，替换原有的方式，这个实现起来又较为困难。
请问现在官方有没有提供新的demo，可以方便的以数据流形式输入呢？

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/b6f4099fa788644043dc5140803b3d92b99bd2cd/deploy/python/infer.py#L667
视频流的预测一般是预测部署时候的需求，我们在部署的deploy下实现了video的预测部署方法，可以使用这个或者和参考这个适配一下你的数据流形式~
