### ISSUE TITLE
TinyPose更改关键点个数，如何修改配置文件

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#5019]
各位大佬，请教一个问题，我想用TinyPose训练一个13个关键点的数据，num_joint、upper_body_ids、flip_perm我都已经改过了，但是不太明白sigma数量如何修改，配置文件默认的sigma为2
![image](https://user-images.githubusercontent.com/48303408/147560578-11f687f3-55b9-4ec8-96e8-dca432fbd868.png)
如果我训练13个关键点，这个值应该如何修改呢？
还有源码中的sigmas也需要修改吗，这个应该如何修改呢？
![image](https://user-images.githubusercontent.com/48303408/147560615-6576da92-b3c6-4c0f-907d-9207087e1958.png)

**Comment by zhiboniu** [comment]
上面那个sigma:2不用改，下面这个list可以看一下数量跟关键点数量是一样的，而且是对应的。表示的是高斯核的方差，对应是一个点位定位的精准度，这个需要根据自己定义的关键点特性估计一下大小。

**Comment by Dandelion111** [comment]
> 上面那个sigma:2不用改，下面这个list可以看一下数量跟关键点数量是一样的，而且是对应的。表示的是高斯核的方差，对应是一个点位定位的精准度，这个需要根据自己定义的关键点特性估计一下大小。

谢谢大佬的解答，我直接在源码中修改了一下，但是验证ap一直为0，不知这是什么原因呢？
![2}DD$_1F~ 3A4W5Q4P`80`W](https://user-images.githubusercontent.com/48303408/147659203-81ec69ed-7957-4580-828e-67a252bcc2fb.png)
![6)K5X7 E4E~RK)HX3HZPF1V](https://user-images.githubusercontent.com/48303408/147659220-04eba2d4-a0d5-492a-b5fa-9ca19afe2ea2.png)

**Comment by ShawnXsw** [comment]
@Dandelion111   请问如何解决的呢？
