### ISSUE TITLE
请问如何计算模型的参数量

### ISSUE THREAD

**Issue by guoqiang0148666** [PaddlePaddle/PaddleDetection#502]
感谢你们杰出的工作！

请问如何计算模型的总参数呢？

是训练后的model_final.pdparams文件的大小除以４吗？

**Comment by jerrywgz** [comment]
model_final.pdparams文件是表示了模型参数的体积，参数量如果是FP32的数据是可以按照除4计算的，或者可以参考这里直接计算参数量：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/paddleslim/analysis/model_size.py#L21

**Comment by ysh329** [comment]
请问如何计算模型参数 · Issue #23861 · PaddlePaddle/Paddle
https://github.com/PaddlePaddle/Paddle/issues/23861

**Comment by guoqiang0148666** [comment]
@jerrywgz @ysh329  Thanks
