### ISSUE TITLE
[Other General Issues]mcfairmot验证时没有第一帧的结果

### ISSUE THREAD

**Issue by LingyvKong** [PaddlePaddle/PaddleDetection#5021]
您好，我在使用 tools/eval_mot.py 验证 mcfairmot 模型时，

发现得到的txt结果都是从第二帧开始的，生成的图片在第一帧时也没有结果，

请问我可以修改哪里或者有什么参数可以让模型在第一帧就输出结果吗？

期待回复，非常感谢！

**Comment by nemonameless** [comment]
遗留问题待修复。
