### ISSUE TITLE
致泊老师在《轻量级关键点算法的产业应用》课程中说会公开“机房人员摔倒检测”代码，请问还更新吗？谢谢

### ISSUE THREAD

**Issue by desertfex** [PaddlePaddle/PaddleDetection#5028]
致泊老师在《轻量级关键点算法的产业应用》课程中说会公开“机房人员摔倒检测”代码，请问还更新吗？谢谢

**Comment by zhiboniu** [comment]
摔倒检测Demo项目：https://aistudio.baidu.com/aistudio/projectdetail/3147220 
我们之前已经在aistudio上公开了，可以加入paddledetection交流群，有利于及时了解相关信息
