### ISSUE TITLE
关于Detection检测缺陷

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleDetection#5029]
请问一下，PaddleDetection检测瑕疵用哪些模型？还有就是用LabelME进行标注的时候，那些OK品该如何标注？

**Comment by yghstill** [comment]
@18362890185 你需要检测的瑕疵在图中所占多大？项目部署在服务器端还是移动端，服务器端可以使用PP-YOLO模型，移动端可使用PP-PicoDet模型。OK品应该属于负样本，不用标注，只标注瑕疵所在区域即可。

**Comment by Hold-on-li** [comment]
> @18362890185 你需要检测的瑕疵在图中所占多大？项目部署在服务器端还是移动端，服务器端可以使用PP-YOLO模型，移动端可使用PP-PicoDet模型。OK品应该属于负样本，不用标注，只标注瑕疵所在区域即可。

占比不大，属于小的那种瑕疵，离线部署在本地电脑中。还有一点疑问，那OK品需要训练吗？

**Comment by yghstill** [comment]
@18362890185 建议先使用PP-YOLO看能不能解决你的问题。如果只为了检测有瑕疵的，那么OK品不需要训练，如果为了更好的拟合数据，也可以OK品作为一个类别进行标注，参与训练
