### ISSUE TITLE
VOC格式数据源，使用11points插值计算mAP 

### ISSUE THREAD

**Issue by ai-zml** [PaddlePaddle/PaddleDetection#503]
@qingqing01 你好，以VOC格式作为数据源，使用11points插值计算mAP ，请问这个mAP的计算方式是先将每一类目标的AP计算出来之后，再除上所有的目标种类数以后得到的mAP；还是将所有的目标整体放在一起，用11点插值后，直接得出mAP？看了以下源码，没太看懂，期待收到您的解答，谢谢

**Comment by heavengate** [comment]
> @qingqing01 你好，以VOC格式作为数据源，使用11points插值计算mAP ，请问这个mAP的计算方式是先将每一类目标的AP计算出来之后，再除上所有的目标种类数以后得到的mAP；还是将所有的目标整体放在一起，用11点插值后，直接得出mAP？看了以下源码，没太看懂，期待收到您的解答，谢谢

每种有效类别计算出来mAP再除以有效类别数，有效类别为groud truth里有该类别的bbox，即如果gt里面那个类别没有bbox，该类别不统计

**Comment by ai-zml** [comment]
@heavengate 谢谢您的回答。您的意思是对于每一种有效类别，利用11点插值法，求出**AP**, 然后将这些**AP**加在一起，再除以有效目标类别数，最终得到**mAP**。比如说，PASCAL VOC 有20个种类，将分别求出的20个AP值相加，然后除以20，得到mAP。

**Comment by heavengate** [comment]
> @heavengate 谢谢您的回答。您的意思是对于每一种有效类别，利用11点插值法，求出**AP**, 然后将这些**AP**加在一起，再除以有效目标类别数，最终得到**mAP**。比如说，PASCAL VOC 有20个种类，将分别求出的20个AP值相加，然后除以20，得到mAP。

是的

**Comment by ai-zml** [comment]
非常感谢
