### ISSUE TITLE
centernet使用自定义的backbone，得不到结果

### ISSUE THREAD

**Issue by mjanddy** [PaddlePaddle/PaddleDetection#5030]
训练centernet时，将dla34替换成自己的backone时，训练的结果都为0，请问是哪里出了问题

**Comment by nemonameless** [comment]
请提供代码改动和loss截图，以便分析问题谢谢。

**Comment by mjanddy** [comment]
![image](https://user-images.githubusercontent.com/27938658/147723293-0e8b2917-0ddc-47ce-ac2d-9ae99a95fdd5.png)
![image](https://user-images.githubusercontent.com/27938658/147723311-27a9cca8-0796-4223-a9ad-d3976f8b7130.png)

**Comment by mjanddy** [comment]
> 请提供代码改动和loss截图，以便分析问题谢谢。

修改的yml和loss以及eval结果，之前第0个epoch结果都是0，目前是在个位数

**Comment by nemonameless** [comment]
看你eval的图片数，训和测的数据集不是COCO？请先确认数据集制作没有问题，可以先拿centernet dla34原版训看mAP正常与否。
你写的simplenet 和dla34结构一样吗？如果不一样用centernet dla34 coco预训练就没啥用相当于train from scratch，刚开始几个epoch很低是正常的。

**Comment by mjanddy** [comment]
> 看你eval的图片数，训和测的数据集不是COCO？请先确认数据集制作没有问题，可以先拿centernet dla34原版训看mAP正常与否。 你写的simplenet 和dla34结构一样吗？如果不一样用centernet dla34 coco预训练就没啥用相当于train from scratch，刚开始几个epoch很低是正常的。

我再测试一下吧，之前是使用了自己的基干和neck，然后训练30多个epoch,结果也不正常，基本为0，所以现在只是替换了基干
