### ISSUE TITLE
关于picodet模型计算量的疑问

### ISSUE THREAD

**Issue by xiuyangleiasp** [PaddlePaddle/PaddleDetection#5031]
请教一下，
在arxiv的论文中，PP-PicoDet-S 模型在320x320分辨率下的计算量为**0.73Gflops**，
但我在paddleDetection中，通过在**picodet_s_320_coco.yml**中增加了**print_flops:true** 字段，打印出的计算量为**0.3573Gflops**，
故，应该以哪个数据为准？
![image](https://user-images.githubusercontent.com/9282338/147720275-5141bb93-76be-42a6-808a-26e2d224316c.png)
![image](https://user-images.githubusercontent.com/9282338/147720299-59209f1c-352e-447b-a4a2-f5de5ea229a4.png)

**Comment by yghstill** [comment]
@xiuyangleiasp print_flops:true打印出来的是macs，flops=2*macs，另外print_flops是调用的PaddleSlim封装的接口，和arxiv中计算的方式稍微有点差别，不过误差不是很大。

**Comment by xiuyangleiasp** [comment]
好的，谢谢
