### ISSUE TITLE
关于LabelMe转coco格式数据集

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleDetection#5033]
![image](https://user-images.githubusercontent.com/87969070/147725090-f4963468-caac-4785-b973-8ab6e66013ea.png)
请问一下，我用LabelME标注了30张图像，但是生成的train加val下只有15张，请问是怎么回事？下图是命令行
![image](https://user-images.githubusercontent.com/87969070/147725267-18e17d09-4165-4ed3-9b67-f20963d3c984.png)

**Comment by yghstill** [comment]
@18362890185 可以确认下是否每张图里都有标注，然后x2coco脚本中debug下没有生成标注的图片和json的原因是什么，可能标注字段有问题
