### ISSUE TITLE
跪求det项目合集

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleDetection#5034]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) /I have read the [FAQ documentation](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) but cannot get the expected help.

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by yuwoyizhan** [comment]
1.https://aistudio.baidu.com/aistudio/projectdetail/450925?channelType=0&channel=0 ,paddlex等很多套件已经出了一个项目合集,并且有静态图和动态图版本,项目合集中蕴含了paddlex的4个主要方向,图像分类,目标检测,语义分割,实例分割,每个方向都至少有一个项目,项目里面包含项目代码,一些参数和代码的解释,注释等.
希望det也可以出一个项目合集,蕴含det目前所包含的所有比较不同的方向,比如根据目标检测,关键点检测,实时跟踪系统,Sniper小目标检测优化模型,Transformer检测系列模型,人头、车辆跟踪垂类模型,多目标跟踪,人脸检测,旋转框检测,模型有较大差异,知识蒸馏,量化等方向做一个项目合集,最好是包含静态图和动态图版本,如果你们没精力的话,只做个动态图版本也行,这样我们这些学习者就不用到处找项目和代码来学习了.动态图版本肯定要支持飞桨2.2.1和det最新release版本.最好就是学习完这个det项目合集,可以把det多数知识都会应用了,不要求掌握原理,比如模型原理等.而且你们做这个合集,希望可以包含一个项目,项目里面的网络是自定义,比较深的网络,包含卷积,池化,drop等API,这种项目太少见了,现在都是直接应用ResNet,搞得我简单的神经网络编程反而不会了.有些目标检测只需要很小的网络,因为图像很简单,而且对于延迟要求非常低.最好再来个项目教导我们如何写ResNet,毕竟这个技术对于机器视觉领域太有用了.做视频太慢了,还是做个项目合集好,做视频半年精力才几个小视频,甚至讲解基础知识.做项目对你们来说,7天就可以弄个项目合集了,包含很多知识了,只限于应用,不限于原理,我只需要改代码,哈哈哈哈.
2.https://aistudio.baidu.com/aistudio/projectdetail/78972 ,这是ai studio精品内容中的一个项目,静态图版本,希望增加动态图版本.

**Comment by nemonameless** [comment]
非常感谢建议，您的反馈我们已经收到，我们会讨论排期安排。
