### ISSUE TITLE
__inject__和__shared__这两个参数是啥意思呢？

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleDetection#5036]
这是原始的训练reader代码
class TrainReader(BaseDataLoader):
   ` __shared__ = ['num_classes']`
    def` __init__`(self, sample_transforms=[], batch_transforms=[], batch_size=1, shuffle=True, drop_last=True, num_classes=80, collate_batch=True, **kwargs):
        super(TrainReader, self).__init__(sample_transforms, batch_transforms, batch_size, shuffle, drop_last, num_classes, collate_batch, **kwargs)

传完参数之后的
'TrainReader': {'inputs_def': {'num_max_boxes': 100}, 'sample_transforms': [{'Decode': {}}, {'Mixup': {'alpha': 1.5, 'beta': 1.5}}, {'RandomDistort': {}}, {'RandomExpand': {'fill_value': [123.675, 116.28, 103.53]}}, {'RandomCrop': {}}, {'RandomFlip': {}}], 'batch_transforms': [{'BatchRandomResize': {'target_size': [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], 'random_size': True, 'random_interp': True, 'keep_ratio': False}}, {'NormalizeBox': {}}, {'PadBox': {'num_max_boxes': 100}}, {'BboxXYXY2XYWH': {}}, {'NormalizeImage': {'mean': [0.485, 0.456, 0.406], 'std': [0.229, 0.224, 0.225], 'is_scale': True}}, {'Permute': {}}, {'Gt2YoloTarget': {'anchor_masks': [[6, 7, 8], [3, 4, 5], [0, 1, 2]], 'anchors': [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]], 'downsample_ratios': [32, 16, 8]}}], 'batch_size': 12, 'shuffle': True, 'drop_last': True,  'mixup_epoch': 25, 'use_shared_memory': True}, 

想知道num_classes是怎么传入的？
具体想知道`__inject__`和`__shared__`这两个参数设计的原理是什么？是怎么更新的？

**Comment by nemonameless** [comment]
__inject__表示引入全局字典中已经封装好的模块
__shared__表示实现一些参数的配置全局共享。
文档 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/advanced_tutorials/MODEL_TECHNICAL.md

**Comment by wstchhwp** [comment]
谢谢

**Comment by LanWong1** [comment]
”表示引入全局字典中已经封装好的模块“  这句话如何理解呢？

**Comment by LanWong1** [comment]
> __inject__表示引入全局字典中已经封装好的模块 __shared__表示实现一些参数的配置全局共享。 文档 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/advanced_tutorials/MODEL_TECHNICAL.md

“表示引入全局字典中已经封装好的模块”这句话该如何理解呢
