### ISSUE TITLE
[BUG] 视频追踪infer时，输入不能为视频，ffmpeg erroe

### ISSUE THREAD

**Issue by chenjw1009** [PaddlePaddle/PaddleDetection#5040]
ffmpeg -y -loglevel error -i yourvideo.mp4 -r 0 -f image2 ../../xx.png

**Comment by nemonameless** [comment]
> ffmpeg -y -loglevel error -i yourvideo.mp4 -r 0 -f image2 ../../xx.png

是这句命令运行不了吗？请先自查ffmpeg单独抽图命令能否执行 或更新ffmpeg版本

**Comment by chenjw1009** [comment]
已解决
