### ISSUE TITLE
pp-picodet量化训练和量化校准后，rk3399上安卓示例的Detector predict costs 时间变化不大，才降10-20ms左右，这是正常的吗？如何能将Detector predict costs时间大幅降低？

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#5042]
pp-picodet量化训练和量化校准后，rk3399上安卓示例的Detector predict costs 时间变化不大，才降10-20ms左右，这是正常的吗？如何能将Detector predict costs时间大幅降低？为什么rk3399上picodet_s_320_coco模型的Detector predict costs时间需要100多ms，怎么才能降低时间？
python tools/train.py -c configs/picodet/picodet_s_320_coco.yml \
          --slim_config configs/slim/quant/picodet_s_quant.yml --eval

python tools/post_quant.py -c configs/picodet/picodet_s_320_coco.yml \
          --slim_config configs/slim/post_quant/picodet_s_ptq.yml

D/JNI: Detector preprocess costs 12.702000 ms
D/JNI: Detector predict costs 108.147003 ms
    Detector postprocess costs 0.450000 ms

![Snipaste_2021-12-31_10-04-19](https://user-images.githubusercontent.com/37955893/147800678-1cd5fce4-8e4d-4c56-83f1-c29bfdb39033.png)

**Comment by yghstill** [comment]
@LMR2018 方便profile看看哪个算子耗时比较严重吗？之前有开发者反馈rk系列芯片可能对transpose算子支持不是很友好，但是PicoDet的backbone（ESNet）中有一些transpose算子，建议再使用PicoDet-LCNet再训练模型测试下速度情况呢？关于各类芯片适配问题我们也在持续优化中，你有最新进展也烦请同步下~
PP-PicoDet-LCNet配置文件：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/more_config/picodet_lcnet_1_5x_416_coco.yml
可改为输入320训练，或者使用LCNet 1x进行训练，预训练地址：https://bj.bcebos.com/v1/paddledet/models/pretrained/LCNet_x1_0_pretrained.pdparams

**Comment by LMR2018** [comment]
@yghstill   你好，如何profile看哪个算子耗时比较严重？

**Comment by yghstill** [comment]
@LMR2018 需要重新编译下PaddleLite，并且打开`--with_profile=ON`，详情可以查看[Paddle Lite文档](https://paddle-lite.readthedocs.io/zh/latest/performance/benchmark_tools.html?highlight=profile#id1)
```shell
./lite/tools/build_android.sh --toolchain=clang  --with_extra=ON --with_exception=ON --with_cv=ON --with_log=ON --with_profile=ON

```

**Comment by LMR2018** [comment]
@yghstill   我重新编译了PaddleLite，并且打开--with_profile=ON，在rk3399安卓上得到的conv2d算子耗时最多，我该如何降低它的耗时，它的耗时太高了
![Snipaste_2022-01-04_13-48-25](https://user-images.githubusercontent.com/37955893/148015351-5e97deb8-0b1d-4ff7-a870-4be065d4ecdf.png)

**Comment by LMR2018** [comment]
> @LMR2018 方便profile看看哪个算子耗时比较严重吗？之前有开发者反馈rk系列芯片可能对transpose算子支持不是很友好，但是PicoDet的backbone（ESNet）中有一些transpose算子，建议再使用PicoDet-LCNet再训练模型测试下速度情况呢？关于各类芯片适配问题我们也在持续优化中，你有最新进展也烦请同步下~ PP-PicoDet-LCNet配置文件：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/more_config/picodet_lcnet_1_5x_416_coco.yml 可改为输入320训练，或者使用LCNet 1x进行训练，预训练地址：https://bj.bcebos.com/v1/paddledet/models/pretrained/LCNet_x1_0_pretrained.pdparams

@yghstill 我使用PicoDet-LCNet再训练模型， /picodet_lcnet_1_5x_416_coco.yml 也改为输入320训练，训练得到的模型测试使用时间更多，模型大小更大，这是怎么回事？以前的100多ms，现在的变成200多ms，以前量化训练校准的模型才1.8M左右，现在3.8M左右了
![Snipaste_2022-01-04_16-07-59](https://user-images.githubusercontent.com/37955893/148030150-c38df6ab-0bb1-4c00-8a28-dd35774b15cb.png)
![Snipaste_2022-01-04_16-07-08](https://user-images.githubusercontent.com/37955893/148030189-685a0016-0bee-4f6c-b741-7cc1eee3616a.png)

**Comment by xiaoxifuhongse** [comment]
你好为什么量化训练之后的模型大小跟之前的一样，怎么看不出有什么变化？

**Comment by LMR2018** [comment]
> 



> 你好为什么量化训练之后的模型大小跟之前的一样，怎么看不出有什么变化？

@xiaoxifuhongse   你运行量化校准之后模型就变小了

**Comment by xiaoxifuhongse** [comment]
@LMR2018 量化校准是不是只能用paddlelite去加载，我想把模型转onnx用其他去加载呢？

**Comment by LMR2018** [comment]
> @LMR2018 量化校准是不是只能用paddlelite去加载，我想把模型转onnx用其他去加载呢？

@xiaoxifuhongse 可以

**Comment by xiaoxifuhongse** [comment]
@LMR2018 能详细说下吗？paddlelite 优化nb文件然后再转onnx？有什么方法吗？谢谢

**Comment by LMR2018** [comment]
> @LMR2018 能详细说下吗？paddlelite 优化nb文件然后再转onnx？有什么方法吗？谢谢

@xiaoxifuhongse 转化成nb文件后不能再转成onnx了吧，没试过，不清楚，可以直接在官网新建一个问题来问

**Comment by LMR2018** [comment]
> @LMR2018 量化校准是不是只能用paddlelite去加载，我想把模型转onnx用其他去加载呢？

@xiaoxifuhongse 量化后不能转onnx模型了

**Comment by zhouweic36** [comment]
> pp-picodet量化训练和量化校准后，rk3399上安卓示例的Detector predict costs 时间变化不大，才降10-20ms左右，这是正常的吗？如何能将Detector predict costs时间大幅降低？为什么rk3399上picodet_s_320_coco模型的Detector predict costs时间需要100多ms，怎么才能降低时间？ python tools/train.py -c configs/picodet/picodet_s_320_coco.yml --slim_config configs/slim/quant/picodet_s_quant.yml --eval
> 
> python tools/post_quant.py -c configs/picodet/picodet_s_320_coco.yml --slim_config configs/slim/post_quant/picodet_s_ptq.yml
> 
> D/JNI: Detector preprocess costs 12.702000 ms D/JNI: Detector predict costs 108.147003 ms Detector postprocess costs 0.450000 ms
> 
> ![Snipaste_2021-12-31_10-04-19](https://user-images.githubusercontent.com/37955893/147800678-1cd5fce4-8e4d-4c56-83f1-c29bfdb39033.png)
能否支持下，picodet 的前后处理代码呀，我在rk1808 arm 上跑通了，后处理不会写？ 在npu上还没有跑，285325701@qq.com  谢谢

**Comment by LMR2018** [comment]
@zhouweic36  我 直接跑官方项目的，没有用Npu来跑，官方的gpu跑的后处理在安卓项目上的cpp c++代码上啊

**Comment by zhouweic36** [comment]
恩，安卓是这样，rk1808 是linux，所以要改改吧













At 2022-02-24 15:52:14, "LMR2018" ***@***.***> wrote:

@zhouweic36 我 直接跑官方项目的，没有用Npu来跑，官方的gpu跑的后处理在安卓项目上的cpp c++代码上啊

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
