### ISSUE TITLE
多类别多目标跟踪，用训练模型评估时，报错。

### ISSUE THREAD

**Issue by chenjw1009** [PaddlePaddle/PaddleDetection#5043]
# 使用训练保存的checkpoint
CUDA_VISIBLE_DEVICES=0 python tools/eval_mot.py -c configs/mot/mcfairmot/mcfairmot_dla34_30e_1088x608_visdrone.yml -o weights=output/mcfairmot_dla34_30e_1088x608_visdrone/model_final.pdparams

mcmot.yml ： 评估数据集设置
<img width="511" alt="1640933878" src="https://user-images.githubusercontent.com/83409851/147808598-bd70b7be-d79f-4f5b-b7d7-6e394a9c2ec5.png">

gt.txt : groundtruth文本
<img width="107" alt="1640934120(1)" src="https://user-images.githubusercontent.com/83409851/147808734-27b51704-301a-4e0d-a427-69a21d640440.png">

error log:
<img width="553" alt="1640934209(1)" src="https://user-images.githubusercontent.com/83409851/147808809-807bccca-3085-4346-9046-b79802dbda36.png">

**Comment by nemonameless** [comment]
没有对应多类别MOT格式的gt标注。
多类别模型暂时只支持visdrone数据集，多类别[metric](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/metrics/mcmot_metrics.py)和MOT16的[metric](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/metrics/mot_metrics.py)是不一样的，其gt标注也不一样。
而且MOT16 test本来就没有开放gt，需要到motchallenge官网提交。

**Comment by chenjw1009** [comment]
你好，我只不过路径名字用的MOT16，里面的数据都是visdrone的，难道和路径名称有关系吗？

**Comment by chenjw1009** [comment]
@nemonameless 你好，我只不过路径名字用的MOT16，里面的数据都是visdrone的，难道和路径名称有关系吗？

**Comment by nemonameless** [comment]
> @nemonameless 你好，我只不过路径名字用的MOT16，里面的数据都是visdrone的，难道和路径名称有关系吗？

https://bj.bcebos.com/v1/paddledet/data/mot/visdrone_mcmot.zip 这是我们处理后的数据集，格式请参照这个，gt的txt是在sequences文件夹里的，是visdrone原本验证集数据集的gt。

**Comment by chenjw1009** [comment]
可以了，谢谢。
