### ISSUE TITLE
[Other General Issues]执行安装指南的Inference demo没有任何输出（没有检测结果图片），也没有任何报错

### ISSUE THREAD

**Issue by HWSQHL** [PaddlePaddle/PaddleDetection#5045]
Inference demo：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/INSTALL.md#inference-demo

**Comment by nemonameless** [comment]
前面的环境各个步骤确定没问题了吧？前面的步骤是否能跑通？
可以在 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/architectures/yolo.py#L118 加上print(output) 看看究竟有没有结果框，最好截图下Inference demo命令后的控制台输出信息谢谢。

**Comment by HWSQHL** [comment]
![1](https://user-images.githubusercontent.com/39974747/147870461-130766af-b9ed-4c4d-bd1f-7c9b6348c849.jpg)
前面环境没问题

**Comment by HWSQHL** [comment]
> 前面的环境各个步骤确定没问题了吧？前面的步骤是否能跑通？ 可以在 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/architectures/yolo.py#L118 加上print(output) 看看究竟有没有结果框，最好截图下Inference demo命令后的控制台输出信息谢谢。

添加了print(output),运行如上图，还是没有检测画框的输出图片

**Comment by nemonameless** [comment]
linux上没有这个问题。正常来讲网络里print(output)应该至少有信息打印的。
建议换paddle最新版本试试。

**Comment by HWSQHL** [comment]
liunx没有问题，在windows环境下，我在这里
[https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/engine/trainer.py#L58](url)
前面添加print("----")结果没有输出----，
这个Trainer在[https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/tools/infer.py#L33](url)被import
我觉得可能的原因是不同级目录下import不成功导致的。

**Comment by nemonameless** [comment]
这个paddle版本是什么呢？换用最新的2.2.1或develop版本后试试还有没有这个问题呢？

**Comment by HWSQHL** [comment]
换用最新的2.2.1或develop版本后依然有这个问题，请问其他人有在windows上安装成功的吗，我同学也出现了这个问题

**Comment by RoyXinyun** [comment]
我也是这个问题，请问你解决了吗
