### ISSUE TITLE
[BUG]dcn系列等训练异常无详细报错退出

### ISSUE THREAD

**Issue by ShawnXsw** [PaddlePaddle/PaddleDetection#5048]
## 描述问题/Describe the bug
网络：cascade_rcnn_dcn_x101_vd_64x4d_fpn_1x、cascade_rcnn_r50_vd_fpn_ssld_2x、faster_rcnn_dcn_x101_vd_64x4d_fpn_1x，使用相同数据集训练退出，同数据集ppyolov2训练正常。

## 复现/Reproduction
1. 您使用的命令是？/What command or script did you run?
python  tools/train.py -c  cascade_rcnn_dcn_x101_vd_64x4d_fpn_1x.yml  --use_vdl=true     --vdl_log_dir=./cascade_rcnn/vdl_dir_cascade_rcnn_dcn_x101_vd_64x4d_fpn_1x/scalar  --eval

python -m paddle.distributed.launch --gpus 0,1,2,3  tools/train.py -c cascade_rcnn_dcn_x101_vd_64x4d_fpn_1x.yml  --use_vdl=true                         --vdl_log_dir=./cascade_rcnn/vdl_dir_cascade_rcnn_dcn_x101_vd_64x4d_fpn_1x/scalar --eval

2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
-改为voc格式、调节超参

3. 您使用的数据集是？/What dataset did you use?
-自定义数据集，该数据集ppyolov2训练正常

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
-单卡、多卡时，当batchsize=2，均报（显存24G，batchsize=1时使用11g）：

                  [01/03 13:13:03] ppdet.utils.checkpoint INFO: Finish loading model weights: /root/.cache/paddle/weights/ResNeXt101_vd_64x4d_pretrained.pdparams
                  [01/03 13:13:04] ppdet.engine INFO:  Model FLOPs : 264.334636G. (image shape is [1, 3, 704, 864])
                  --------------------------------------
                  C++ Traceback (most recent call last):
                  --------------------------------------
                  No stack trace in paddle, may be caused by external reasons.
                  
                  ----------------------
                  Error Message Summary:
                  ----------------------
                  FatalError: `Segmentation fault` is detected by the operating system.
                    [TimeInfo: *** Aborted at 1641215584 (unix time) try "date -d @1641215584" if you are using GNU date ***]
                    [SignalInfo: *** SIGSEGV (@0x0) received by PID 47873 (TID 0x7f6937641240) from PID 0 ***]
                  
                  Segmentation fault (core dumped)

-多卡时（单卡未尝试），当batchsize=1，正常训练半个epoch左右，报：

[01/03 13:05:25] ppdet.engine INFO: Epoch: [0] [1090/2516] learning_rate: 0.000427 loss_rpn_cls: 0.010813 loss_rpn_reg: 0.005152 loss_bbox_cls_stage0: 0.021450 loss_bbox_reg_stage0: 0.021058 loss_bbox_cls_stage1: 0.016776 loss_bbox_reg_stage1: 0.029276 loss_bbox_cls_stage2: 0.014039 loss_bbox_reg_stage2: 0.021044 loss: 0.139609 eta: 1 day, 16:36:59 batch_cost: 0.6889 data_cost: 0.0002 ips: 1.4515 images/s
 INFO 2022-01-03 13:05:30,356 launch_utils.py:319] terminate process group gid:37977
INFO 2022-01-03 13:05:30,358 launch_utils.py:319] terminate process group gid:37982
INFO 2022-01-03 13:05:30,360 launch_utils.py:319] terminate process group gid:37993
INFO 2022-01-03 13:05:34,365 launch_utils.py:340] terminate all the procs
ERROR 2022-01-03 13:05:34,366 launch_utils.py:603] ABORT!!! Out of all 4 trainers, the trainer process with rank=[3] was aborted. Please check its log.
 INFO 2022-01-03 13:05:38,370 launch_utils.py:340] terminate all the procs
INFO 2022-01-03 13:05:38,370 launch.py:304] Local processes completed.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
CUDA 10.2； paddlepaddle-gpu v2.2.0；PaddleDetection v2.3

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：
None

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
Ubuntu 18.04

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
Python v3.7.11

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
CUDA 10.2.89；cuDNN 8.0.5

**Comment by ghostxsl** [comment]
请问paddle版本是多少？看报错信息，应该是环境的问题：  No stack trace in paddle, may be caused by external reasons.

**Comment by ghostxsl** [comment]
建议您更新一下paddle版本，检查一下log/worklog.1、log/worklog.2、log/worklog.3的日志

**Comment by ShawnXsw** [comment]
> 建议您更新一下paddle版本，检查一下log/worklog.1、log/worklog.2、log/worklog.3的日志
@ghostxsl 

> 
1、针对多卡，当batchsize=1，正常训练半个epoch左右后异常退出，我调整了LinearWarmup后坚持训练完1一个完整epoch了

2、针对batchsize>1的单卡报错：检查worklog发现（我当前已经是paddlepaddle-gpu v2.2.0，我需要切在2.2.1或者dev？）：

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   std::shared_ptr<paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type> paddle::imperative::PrepareData<paddle::imperative::VarBase>(paddle::framework::OperatorWithKernel const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::framework::OpKernelType const&)
3   paddle::framework::TransformData(paddle::framework::OpKernelType const&, paddle::framework::OpKernelType const&, paddle::framework::Tensor const&, paddle::framework::Tensor*)
4   paddle::framework::TransDataDevice(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::framework::Tensor*)
5   paddle::framework::TensorCopySync(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::framework::Tensor*)
6   void paddle::memory::Copy<paddle::platform::CUDAPlace, paddle::platform::CUDAPinnedPlace>(paddle::platform::CUDAPlace, void*, paddle::platform::CUDAPinnedPlace, void const*, unsigned long, CUstream_st*)
7   paddle::platform::GpuMemcpySync(void*, void const*, unsigned long, cudaMemcpyKind)

**Comment by ghostxsl** [comment]
切一下dev试试

**Comment by ShawnXsw** [comment]
> 切一下dev试试
@ghostxsl 
1、针对多卡，当batchsize=1，正常训练半个epoch左右后异常退出，我调整了LinearWarmup后坚持训练完1一个完整epoch了，但在下一个epoch报：
```
RuntimeError: (PreconditionNotMet) A serious error has occurred here. Please set find_unused_parameters=True to traverse backward graph in each step to prepare reduce in advance. If you have set, There may be several reasons for this error: 1) Please note that all forward outputs derived from the module parameters must participate in the calculation of losses and subsequent gradient calculations. If not, the wrapper will hang, waiting for autograd to generate gradients for these parameters. you can use detach or stop_gradient to make the unused parameters detached from the autograd graph. 2) Used multiple forwards and one backward. You may be able to wrap multiple forwards in a model.
  [Hint: Expected groups_need_finalize_ == false, but received groups_need_finalize_:1 != false:0.] (at /paddle/paddle/fluid/imperative/reducer.cc:573)
```


2、针对batchsize>1的单卡报错，切换到paddlepaddle-gpu dev，保持paddleDetection 2.3， 仍报错，worklog中没有什么有效日志，仍是：
```
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
I0103 15:58:20.937088 119074 gen_comm_id_helper.cc:200] Server listening on: 127.0.0.1:60252 successful.
I0103 15:58:24.117375 119074 nccl_context.cc:82] init nccl context nranks: 4 local rank: 3 gpu id: 3 ring id: 0
W0103 15:58:24.915052 119074 device_context.cc:533] Please NOTE: device: 3, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.2
W0103 15:58:24.918771 119074 device_context.cc:551] device: 3, cuDNN Version: 8.0.
/root/miniconda3/envs/paddle_det/lib/python3.7/site-packages/paddle/tensor/creation.py:132: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1641225527 (unix time) try "date -d @1641225527" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 119074 (TID 0x7f3a382e13c0) from PID 0 ***]
```

**Comment by ghostxsl** [comment]
请在执行命令中添加 `--fleet -o find_unused_parameters=True` 参数

**Comment by ShawnXsw** [comment]
> 切换到paddlepaddle-gpu dev，保持paddleDetection 2.3， 仍报错，worklog中没有什么有效日志，仍是：
@ghostxsl 
好，我在batch=1实验中试试。 but batch>1 报错这个是什么情况呢？

**Comment by ghostxsl** [comment]
一般报这个错误不是paddle框架的错误，应该是系统级的错误，所以框架本身无法捕获，就会往外抛出`No stack trace in paddle, may be caused by external reasons.`这个异常

**Comment by ShawnXsw** [comment]
> 

@ghostxsl   请问有排查方向的建议吗，我尝试一下，主要控制变量到batchsize了就会完全复现。

**Comment by ghostxsl** [comment]
我之前也碰到过一样的报错，我当时是怀疑oom了，但是他没报oom的错，我一样的配置切到32G V100下就跑通了，当然也有可能是环境的问题，具体的原因我当时也没排查出来。。。

**Comment by ShawnXsw** [comment]
> 我之前也碰到过一样的报错，我当时是怀疑oom了，但是他没报oom的错，我一样的配置切到32G V100下就跑通了，当然也有可能是环境的问题，具体的原因我当时也没排查出来。。。

我128G  不太可能OOM，卡是24G Titan RTX *4，显存也够。。有点晕

**Comment by ghostxsl** [comment]
应该是环境的问题，建议您换个环境尝试一下～
