### ISSUE TITLE
pp-picodet float16模型的安卓应用示例有没有啊？

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#5054]
pp-picodet float16模型的安卓应用示例有没有啊？float32的太耗时了

**Comment by yghstill** [comment]
@LMR2018  Paddle Lite的FP16 Android demo正在适配中，可以先使用ncnn的安卓demo，默认fp16预测：https://github.com/JiweiMaster/PP-PicoDet-Android-Demo
