### ISSUE TITLE
pp-picodet模型如何进行剪裁、离线量化联合策略训练？

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#5058]
pp-picodet模型如何进行剪裁、离线量化联合策略训练？

**Comment by yghstill** [comment]
@LMR2018 目前还不支持联合策略压缩，如果你模型量化的加速效果不明显，建议使用非结构化稀疏试下吧：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/pruner/README.md
