### ISSUE TITLE
如何添加稀疏化训练所需的 4 行代码？

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#5060]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/pruner/README.md

如何添加稀疏化训练所需的 4 行代码？

```
# after constructing model and before training

# Pruner Step1: configs
configs = {
    'pruning_strategy': 'gmp',
    'stable_iterations': self.stable_epochs * steps_per_epoch,
    'pruning_iterations': self.pruning_epochs * steps_per_epoch,
    'tunning_iterations': self.tunning_epochs * steps_per_epoch,
    'resume_iteration': 0,
    'pruning_steps': self.pruning_steps,
    'initial_ratio': self.initial_ratio,
}
```
# Pruner Step2: construct a pruner object
```
self.pruner = GMPUnstructuredPruner(
    model,
    ratio=self.cfg.ratio,
    skip_params_func=skip_params_self, # Only pass in this value when you design your own skip_params function. And the following argument (skip_params_type) will be ignored.
    skip_params_type=self.cfg.skip_params_type,
    local_sparsity=True,   
    configs=configs)
```
（ 添加这个参数报错，   local_sparsity=True， 怎么解决？）

这一步在哪个文件下的哪个位置添加？

```
# training  
for epoch_id in range(self.start_epoch, self.cfg.epoch):
    model.train()
    for step_id, data in enumerate(self.loader):
        # model forward
        outputs = model(data)
        loss = outputs['loss']
        # model backward
        loss.backward()
        self.optimizer.step()

        # Pruner Step3: step during training
        self.pruner.step()

    # Pruner Step4: save the sparse model
    self.pruner.update_params()
    # model-saving API
```

**Comment by minghaoBD** [comment]
> pruning_strategy

您好，谢谢您对于飞桨非结构化稀疏工作的关注。

问题1: 如何添加稀疏化训练所需的 4 行代码？
回答: 目前改功能已经集成在PaddleDection repo中，可以参照[这里](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet/pruner#61-%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8)直接使用。

问题2: 添加这个参数报错， local_sparsity=True， 怎么解决？
回答: https://github.com/PaddlePaddle/PaddleDetection/issues/5056

问题3: 这一步（step3 & step4）在哪个文件下的哪个位置添加？
回答: 
step1: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/slim/unstructured_prune.py#L48-L56
step2: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/slim/unstructured_prune.py#L58-L64
step3: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/engine/trainer.py#L408-L409
step4: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/engine/trainer.py#L426-L427
