### ISSUE TITLE
paddledetetion最近有更新检测模型的计划吗？

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleDetection#5066]
感觉检测的模型有点少，有更新更多模型的计划吗

**Comment by heavengate** [comment]
您好，您这边是需求哪些模型呢，我们也在调研和整理待支持的模型进行排期~

**Comment by wstchhwp** [comment]
比如经典的yolov4, cascade rcnn系列的模型有点少 还有就是那边给的libe rcnn找不到配置文件

**Comment by nemonameless** [comment]
> 比如经典的yolov4, cascade rcnn系列的模型有点少 还有就是那边给的libe rcnn找不到配置文件

yolov4, htc, libera rcnn都有静态图版本，在PaddleDetection/static目录下，动态图版本暂未开发，主要会从工业界应用面考虑复现的计划。
