### ISSUE TITLE
picodet最小的模型在工控机上速度很慢

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#5068]
请问大佬，用picodet最小模型在i7的8代工控机上耗时20ms，比笔记本要慢好多，是什么原因呢？

**Comment by yghstill** [comment]
@Dandelion111 你的预测库用的Paddle Inference还是openvino？ i7的8代工控机上可以开启mkldnn加速吗？

**Comment by Dandelion111** [comment]
> @Dandelion111 你的预测库用的Paddle Inference还是openvino？ i7的8代工控机上可以开启mkldnn加速吗？

大佬你好，用的openvino，用openvino的时候也能同时用mkldnn吗？我在i7的10代笔记本上测得最小模型大概10ms多一点，在工控机上用的重新用cooc数据集训练的LCNet0.5骨干网络，按理说速度不应该这么慢呢？大佬在pc端cpu上测试过吗
