### ISSUE TITLE
TinyPose应用在别的场景上，效果不佳

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#5069]
各位大佬，我把TinyPose应用在别的场景上，用训练集拿来测试，测试效果依然不太好，只有少部分图像能得到合理结果，训练数据大概200多张，请问如果用预训练模型应用在别的场景上大概需要多少数据能保证基本的效果，另外，有什么提升精度的技巧可以尝试吗？

**Comment by zoooo0820** [comment]
能否具体说明一下场景和目前的做法呢，方便进一步分析

**Comment by Dandelion111** [comment]
> 能否具体说明一下场景和目前的做法呢，方便进一步分析

这位大佬看着面熟，我之前因为验证ap为0的问题，在微信给您看过我的数据集，目前怎么调参，效果都差太多
