### ISSUE TITLE
[BUG]利用paddlelite opt 把picodet量化训练的模型转换nb的时候 指定目标平台为arm和opencl的时候报错

### ISSUE THREAD

**Issue by xiaoxifuhongse** [PaddlePaddle/PaddleDetection#5070]
1. Model is successfully loaded!
[F  1/ 6 17:15:49.431 ...optimizer/mir/static_kernel_pick_pass.cc:126 Apply] Check failed: one_adj_instruct.op_info()->HasInputScale(out_node_name): 
Aborted (core dumped)

**Comment by yghstill** [comment]
@xiaoxifuhongse 请发下执行指令，我们复现下

**Comment by xiaoxifuhongse** [comment]
paddle_lite_opt --model_file=/home/xxx/PaddleDetection/tools/output_inference/picodet_s_ptq/model.pdmodel --param_file=/home/xxx/PaddleDetection/tools/output_inference/picodet_s_ptq/model.pdiparams --valid_targets=arm,opencl  --optimize_out=picodet_tiny

**Comment by yghstill** [comment]
@xiaoxifuhongse 你是使用离线量化还是量化训练产出的模型，PicoDet请使用量化训练吧，离线量化的精度很差，暂不建议使用。 同时导出量化模型请使用Paddle 2.1.2版本，2.2的问题刚修复，还未发布。 Paddle-Lite使用v2.10版本。
