### ISSUE TITLE
使用cascade-mask-rcnn训练模型，能否在预测的时候得到物体的边缘框呢？

### ISSUE THREAD

**Issue by MatrixLyz0623** [PaddlePaddle/PaddleDetection#5072]
如上图所示，标注数据是围绕物体的边缘标注的，有什么办法可以在预测的时候预测的是物体的边缘框呢
![1](https://user-images.githubusercontent.com/43607268/148372309-2185bf45-1a24-458e-9392-8321fdcba60d.jpg)
转化成coco训练数据一条标注信息如下
{
            "segmentation": [
                [
                    590,
                    358,
                    1090,
                    484,
                    1085,
                    669,
                    580,
                    572
                ]
            ],
            "iscrowd": 0,
            "image_id": 1,
            "bbox": [
                580.0,
                358.0,
                510.0,
                311.0
            ],
            "area": 158610.0,
            "category_id": 1,
            "id": 1
        },

**Comment by nemonameless** [comment]
mask-rcnn 预测的时候是先出框再在框内出mask的，所以预测物体的边缘框这个事本来就能做到的吧。
你的数据集虽然符合coco格式，不过segmentation字段只有4个点的坐标有点少，这样mask就是个四边形了。
