### ISSUE TITLE
有两个问题请教

### ISSUE THREAD

**Issue by 205418367** [PaddlePaddle/PaddleDetection#5076]
１、有没有可以借鉴的blazeface c++推理代码？
２、能不能用通用目标检测算法训练人脸检测？效果会与blazeface相当还差一些？

**Comment by yghstill** [comment]
@205418367 
- C++ 推理代码可以参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/cpp ，和普通检测模型后处理一致。
- 可以使用其他目标检测算法训练人脸检测，blazeface只是一个非常轻量级的人脸算法，可以试下PicoDet、ppyolo-tiny等，也有不错的效果。
