### ISSUE TITLE
paddleserving部署出问题

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleDetection#5078]
feed_var {
  name: "im_shape"
  alias_name: "im_shape"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
}
feed_var {
  name: "scale_factor"
  alias_name: "scale_factor"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
fetch_var {
  name: "concat_12.tmp_0"
  alias_name: "concat_12.tmp_0"
  is_lod_tensor: false
  fetch_type: 1
  shape: 6
}
fetch_var {
  name: "multiclass_nms3_0.tmp_2"
  alias_name: "multiclass_nms3_0.tmp_2"
  is_lod_tensor: false
  fetch_type: 2
}

![a85f2726242bf9b5ff3825d2d643027](https://user-images.githubusercontent.com/40813430/148509578-ee2093c9-24df-4fa8-b3d6-a01681ce4d08.png)

```python
import sys
import numpy as np
import cv2
from paddle_serving_client import Client
from paddle_serving_app.reader import *


preprocess = Sequential([
            File2Image(), BGR2RGB(), Resize((800, 1333), interpolation=cv2.INTER_LINEAR), Div(255.0), Normalize((0.485,0.456,0.406), (0.229,0.224,0.225)), Transpose((2, 0, 1)), PadStride(32)
            ])

postprocess = RCNNPostprocess("deploy/serving/label_list.txt", "output", [800, 1333])

client = Client()
client.load_client_config("output_inference/faster_rcnn_r50_fpn_coco/serving_client/serving_client_conf.prototxt")
client.connect(['127.0.0.1:9393'])

# image_file = "test.jpg"
# im = preprocess(image_file)
im = preprocess(sys.argv[1])

fetch_map = client.predict(
    feed={
        "image": im,
        "im_shape": np.array(list(im.shape[1:])).reshape(-1),
        "scale_factor": np.array([1.0, 1.0]).reshape(-1),
    },
    fetch=["concat_12.tmp_0"],
    batch=False)

fetch_map["image"] = sys.argv[1]
postprocess(fetch_map)
```

**Comment by wjplove8** [comment]
请教一下问题怎么解决的？
