### ISSUE TITLE
自定义数据集配置方式

### ISSUE THREAD

**Issue by xinliyangguang** [PaddlePaddle/PaddleDetection#5079]
使用paddleDetection-release-2.0中的ppyolo训练时使用的是自定义的coco数据集：
coco_detection如下：
metric: COCO
num_classes: 3 # 80

TrainDataset:
  !COCODataSet
    image_dir: 20210525train # train2017
    anno_path: 20210525annotations/train.json # annotations/instances_train2017.json
    dataset_dir: /root/paddlejob/workspace/env_run/afs/zhaoxin34/user/ad-hdmap/benchmark/zhaoxin34/dataset/coco # dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: 20210525test # val2017
    anno_path: 20210525annotations/test.json # annotations/instances_val2017.json
    dataset_dir: /root/paddlejob/workspace/env_run/afs/zhaoxin34/dataset/coco #dataset/coco

TestDataset:
  !ImageFolder
    image_dir: 20210525test
    anno_path: 20210525annotations/test.json #20210525annotations/test.json # annotations/instances_val2017.json
    dataset_dir: /root/paddlejob/workspace/env_run/afs/zhaoxin34/dataset/coco

可是训练中还是会报错：
requests.exceptions.ConnectionError: HTTPConnectionPool(host='images.cocodataset.org', port=80): Max retries exceeded with url: /zips/train2017.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff4dba3a90>: Failed to establish a new connection: [Errno 110] Connection timed out'))

自定义数据的格式是：
dataset/coco
-----20210525annotations
                        ---------train.json
                        ---------test.json
-----20210525train
                       ---------1.jpg
                       ---------2.jpg
                       ......
-----20210525test
                      ---------3.jpg
                      ---------4.jpg

数据是原来在paddledetection-release-0.5中用的，不知道在paddledetection-2.0中怎么改动这么大啊！

**Comment by nemonameless** [comment]
cfg里数据集的路径设置对了吗？找不到数据集默认就会下载coco，你这个报错信息是网络问题下载没成功。

**Comment by xinliyangguang** [comment]
> cfg里数据集的路径设置对了吗？找不到数据集默认就会下载coco，你这个报错信息是网络问题下载没成功。

具体是哪个cfg呢？我就是修改了coco_detection.yml，optmizer_1x.yml，ppyolo_reader.yml，ppyolo_r50_dcn.yml，runtime.yml。

**Comment by xinliyangguang** [comment]
> cfg里数据集的路径设置对了吗？找不到数据集默认就会下载coco，你这个报错信息是网络问题下载没成功。

好的，通过检查coco_detection.yml的配置，已经成功开始运行了。
