### ISSUE TITLE
数据预处理耗时问题

### ISSUE THREAD

**Issue by HaiLongEmb** [PaddlePaddle/PaddleDetection#508]
我使用的YOLOV3模型，检测逻辑是opencv从摄像头获取一帧图片，经过Normalize等处理送给模型检测，再显示，经过测试模型检测速度很快，但预处理使用的是CPU比较耗时，有什么办法能提高预处理速度，我想满足实时显示，如果使用本地图片批量处理fps还是很高的，但我现在要从摄像头拿图片必须是顺序执行。请问有什么好办法解决？

在此感谢大佬的帮助

**Comment by willthefrog** [comment]
yolo预测可以达到20ms以内，预处理的话只需要normalize和resize，用opencv实现的话感觉上10ms是够得。另外即使是实时通常也是有一两帧延时的，建议给预处理加个double buffer来进一步掩盖延时。

**Comment by HaiLongEmb** [comment]
什么CPU能达到10ms啊，我用的i5-4950一个normalize耗时达到平均55ms，我一帧图片的分辨率是1920*1080的。目前的情况就算我使用多个线程进行预处理，也很难满足实时性。

**Comment by JensenHJS** [comment]
预处理耗时太多的话，可以考虑把预处理部分写成cuda程序放到GPU上跑，Normalize可以改，我就是这样做的。但是，后来改成多线程预测，发现cuda预处理有问题了，就还是用的cpu预处理
