### ISSUE TITLE
[Other General Issues]export_model.py: error: unrecognized arguments: -c configs/picodet/picodet_s_320_voc.yml

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#5083]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) /I have read the [FAQ documentation](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) but cannot get the expected help.

## 描述问题/Describe the bug

PicoDet模型训练  一直提示
paddle\nn\layer\norm.py:653: UserWarning: When training, we now always track global mean and variance.

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
PicoDet模型训练
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?
VOC

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
```
python tools/export_model.py -c configs/picodet/picodet_s_320_voc.yml -o weights=https://paddledet.bj.bcebos.com/models/picodet_s_320_coco.pdparams --output_dir=inference_model

usage: export_model.py [-h] [-o [OPT [OPT ...]]] [--output_dir OUTPUT_DIR]
                       [--export_serving_model EXPORT_SERVING_MODEL]
                       [--slim_config SLIM_CONFIG]

export_model.py: error: unrecognized arguments: -c configs/picodet/picodet_s_320_voc.yml


```

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：
paddledet                         2.3.0
paddlepaddle-gpu                  2.2.1.post112
paddleslim                        2.1.1
paddlex                           2.0.0

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
WIN

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
python3.7

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
cuda11.2 cudnn8

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by nemonameless** [comment]
换到linux上试试？
另外你的命令中权重是coco模型但是cfg是voc，这样head部分维度会对不上的会报新的错。

**Comment by monkeycc** [comment]
我的是VOC数据集

不能调用COCO模型吗
也没VOC模型嘛

是不是要VOC转COCO数据集
@nemonameless

**Comment by nemonameless** [comment]
> 我的是VOC数据集
> 
> 不能调用COCO模型吗 也没VOC模型嘛
> 
> 是不是要VOC转COCO数据集 @nemonameless

VOC和COCO种类数不同，cfg里的num_classes设置不同的，训好的模型head的通道数不一样的。建议直接使用COCO模型。

**Comment by yghstill** [comment]
@monkeycc 你是想导出PicoDet模型来测试吗？
可以通过以下命令进行导出：
```shell
python tools/export_model.py -c configs/picodet/picodet_s_320_coco.yml \
              -o weights=https://paddledet.bj.bcebos.com/models/picodet_s_320_coco.pdparams --output_dir=inference_model
```
我们只发布了COCO上的预训练模型，VOC的配置文件只是一个demo。
看你上面的用法应该是命令输入有误，不是代码的原因，在终端shell下，输入指令后检查下-c前后的空格等是否正确。

**Comment by monkeycc** [comment]
用了spine_coco数据集

`python  tools/export_model.py  -c  configs/picodet/picodet_s_320_coco.yml  -o  weights=https://paddledet.bj.bcebos.com/models/picodet_s_320_coco.pdparams  --output_dir=inference_model`

```

usage: export_model.py [-h] [-o [OPT [OPT ...]]] [--output_dir OUTPUT_DIR]
                       [--export_serving_model EXPORT_SERVING_MODEL]
                       [--slim_config SLIM_CONFIG]
export_model.py: error: unrecognized arguments: -c configs/picodet/picodet_s_320_coco.yml
```

win环境
命令行 空格没问题
改为绝对路径 也是一样
@nemonameless  @yghstill
