### ISSUE TITLE
PaddleDetection预测

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleDetection#5085]
你好，请问一下，detection预测单次只支持一张图像预测吗？无法加载文件夹

**Comment by nemonameless** [comment]
都支持的。
单张图片是--infer_img，文件夹是--infer_dir。
infer_img的优先级更高，设置了infer_dir就不能设置infer_img。
文件夹读入是会处理成图片list然后一张张去过网络，相关[code](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/tools/infer.py#L88)。
deploy部署同理，是指定--image_file或--image_dir。
