### ISSUE TITLE
关于获得检测的方向信息

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleDetection#5086]
如何通道检测获得方向信息呢？

**Comment by nemonameless** [comment]
#4908 
请详细描述您的需求和想法谢谢。方向信息具体指什么？是旋转框检测？参照[s2anet](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/dota)

**Comment by Hold-on-li** [comment]
> #4908 请详细描述您的需求和想法谢谢。方向信息具体指什么？是旋转框检测？参照[s2anet](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/dota)

Detection应该获得的是检测框的四点坐标信息，能否获得物体的方向信息呢？例如抓取项目是需要方向的

**Comment by nemonameless** [comment]
方向信息是指同一个框在下一帧里偏移的方向？这个应该是视频检测和跟踪的问题，但即使如此也很难从网络输出就获得所谓的方向信息，最多只是对结果框进行坐标位置判断的后处理。

**Comment by Xinjun-Wu** [comment]
> 

也许他是想要提取人物的面部朝向或者身体朝向吧，类似拓展到其他有常规正面定义的物体，比如汽车
