### ISSUE TITLE
请问S2ANet的conv版本（非alignconv）是否支持量化剪枝？是否支持移动端部署？

### ISSUE THREAD

**Issue by zf900** [PaddlePaddle/PaddleDetection#5087]
请问S2ANet的conv版本（非alignconv）是否支持量化剪枝？是否支持移动端部署？

**Comment by nemonameless** [comment]
量化剪枝目前没有适配过。没有特殊操作的话移动端部署应该是可以的，但是速度不一定很快。

**Comment by wangxinxin08** [comment]
目前是可以移动端部署的，不过因为速度会相对比较差

**Comment by zf900** [comment]
> 目前是可以移动端部署的，不过因为速度会相对比较差

那么这个算法的AlignConv版本，现在是否支持移动端部署呢？

**Comment by wangxinxin08** [comment]
AlignConv需要使用DCN，应该不支持移动端部署

**Comment by zf900** [comment]
> AlignConv需要使用DCN，应该不支持移动端部署

您好，我用opt转换工具转换训练好的 Conv 版本的S2ANet模型时，出现了如下的错误，您知道怎么解决的吗？
./opt_backup  --valid_targets=arm --model_file=inference_model/jdx_s2anet_conv_2x_dota/model.pdmodel --param_file=inference_model/jdx_s2anet_conv_2x_dota/model.pdiparams --optimize_out=output_inference/jdx_s2anet_conv_2x_dota/model --optimize_out_type=naive_buffer --quant_model=false

**[W  1/11  8:27:29.544 .../dskj/xiexie/Paddle-Lite/lite/api/opt.cc:187 RunOptimize] Load combined-param model. Option model_dir will be ignored
Loading topology data from inference_model/jdx_s2anet_conv_2x_dota/model.pdmodel
Loading params data from inference_model/jdx_s2anet_conv_2x_dota/model.pdiparams
1. Model is successfully loaded!
[F  1/11  8:27:30.362 ...ite/core/mir/type_precision_cast_pass.cc:261 AddCastInst] Check failed: is_found: Can't find a Cast kernel for Cast op: Tensor<arm,float,NCHW,0>:tmp_150->Tensor<arm,int64_t,NCHW,0>:elementwise_mod
Aborted (core dumped)**

**Comment by wangxinxin08** [comment]
出现这个原因是某些算子不支持
