### ISSUE TITLE
roLabelImg标注的图像转coco格式

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleDetection#5088]
请问一下，roLabelImg标注的图像如何转coco格式？

**Comment by nemonameless** [comment]
比普通检测多了角度信息，coco格式 json文件里多加个字段。自定义数据文档 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/dota#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE
做好后的格式参照 https://paddledet.bj.bcebos.com/data/spine_coco.tar

**Comment by wangxinxin08** [comment]
可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/dataset/dota_coco/dota_to_coco.py 转换下格式

**Comment by JimXu1989** [comment]
没有解决阿
