### ISSUE TITLE
如何在PaddleDetection中获取目标检测模型的参数和GFLOPs

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#5090]
我使用PaddleDetection改进了一下网络，想测试一下我新的模型的参数量和GFLOPs，请问应该如何做呀

**Comment by ghostxsl** [comment]
请参考FAQ中的How to count model parameters.部分：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet#faq

**Comment by ghostxsl** [comment]
你可以在yml文件里设置print_flops: True来获得GFLOPs
