### ISSUE TITLE
多卡训练失败[Other General Issues]

### ISSUE THREAD

**Issue by xinliyangguang** [PaddlePaddle/PaddleDetection#5092]
多卡训练设置失败，显示只用了一张卡：
![image](https://user-images.githubusercontent.com/53338761/148945461-059a2eb0-4d98-4e20-8503-6a15e1579972.png)

训练开始脚本如下：
export CUDA_VISIBLE_DEVICES=0,1,2,3
python3 -m paddle.distributed.launch --log_dir=./ppyolo_dygraph/ --gpus 0,1,2,3 /root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleDetection-release-2.0/configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml

多卡环境信息如下：
![image](https://user-images.githubusercontent.com/53338761/148945646-9ea10267-f83d-42ba-9e49-510d90ee8508.png)

**Comment by ghostxsl** [comment]
请给出详细的运行命令以及报错信息

**Comment by xinliyangguang** [comment]
> 请给出详细的运行命令以及报错信息

您好，运行脚本就是
export CUDA_VISIBLE_DEVICES=0,1,2,3
python3 -m paddle.distributed.launch --log_dir=./ppyolo_dygraph/ --gpus 0,1,2,3 /root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleDetection-release-2.0/configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml

运行的时候就是watch查看显卡的利用率就是只用了一张卡

**Comment by ghostxsl** [comment]
是报错停止了吗？还是说可以正常运行？如果报错了，请问错误是什么？如果没报错，可以正常运行，但是只有一块卡在跑的话，建议您确认一下您的paddle版本
