### ISSUE TITLE
无法导出__model__文件

### ISSUE THREAD

**Issue by ZuoDaHai** [PaddlePaddle/PaddleDetection#5094]
使用export_model.py导出yolov3_mobilenet_v1_270e模型只能导出如下文件：
_infer_cfg.yml
model.pdiparams
model.pdiparams.info
model.pdmodel_

没有导出`__model__`文件，麻烦问一下如何才能导出`__model__`文件

**Comment by nemonameless** [comment]
目前默认是动态图导出，结果就是那4个文件。
__model__是静态图导出，请在PaddleDetection/static中使用。
