### ISSUE TITLE
PaddleDetection的预测近期回增加视频流的支持，请问已发布了？

### ISSUE THREAD

**Issue by DavidFangx** [PaddlePaddle/PaddleDetection#510]
PaddleDetection的预测近期回增加视频流的支持，请问已发布了？

**Comment by qingqing01** [comment]
@DavidFangx master分支的Python版本刚合入   https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/python

**Comment by DavidFangx** [comment]
PaddleDetection的预测近期回增加视频流的支持，请问已发布了？
