### ISSUE TITLE
paddleserving 下的Pipeline下测试案例将获取的json格式的矩形框位置合成框图出现的结果与实际结果相差很大

### ISSUE THREAD

**Issue by wxf764571829** [PaddlePaddle/PaddleDetection#5102]
预测结果合成如下：
![4351399025921794af9ee8b5c818f07](https://user-images.githubusercontent.com/46362180/149262525-2602a144-b4cb-46f7-82e7-46e38eeab8e4.png)

serving版本0.7.0，paddle版本2.2.1
测试案例地址：https://github.com/PaddlePaddle/Serving/tree/v0.7.0/examples/Pipeline/PaddleDetection/ppyolo_mbv3
我不知道是我合成图片的代码问题还是什么问题。合成代码是根据PaddleDetection中修改的，我在想合成图的偏差是不是和resize有关，如果是我应该如何修改，劳烦前辈们贴一下代码
def draw_box(im, np_boxes, labels, threshold=0.5):
    if isinstance(im, str):
        im = Image.open(im).convert('RGB')
    else:
        im = Image.fromarray(im)
    draw_thickness = 5
    draw = ImageDraw.Draw(im)
    color = (255, 0, 0)
    for dt in np_boxes:
        clsid, bbox, score = int(dt['category_id']), dt['bbox'], dt['score']
        if float(score)<threshold:
            continue
        if len(bbox) == 4:
            xmin,ymin,w,h = bbox
            xmax=xmin+w
            ymax=h+ymin
            print('class_id:{:d}, confidence:{:.4f}, left_top:[{:.2f},{:.2f}],'
                  'right_bottom:[{:.2f},{:.2f}]'.format(
                      int(clsid), score, xmin, ymin, xmax, ymax))
            draw.line(
                [(xmin, ymin), (xmin, ymax), (xmax, ymax), (xmax, ymin),
                 (xmin, ymin)],
                width=draw_thickness,
                fill=color)
        elif len(bbox) == 8:
            x1, y1, x2, y2, x3, y3, x4, y4 = bbox
            draw.line(
                [(x1, y1), (x2, y2), (x3, y3), (x4, y4), (x1, y1)],
                width=2,
                fill=color)
            xmin = min(x1, x2, x3, x4)
            ymin = min(y1, y2, y3, y4)

        # draw label
        text = "{} {:.4f}".format(labels[clsid], score)
        tw, th = draw.textsize(text)
        draw.rectangle(
            [(xmin + 1, ymin - th), (xmin + tw + 1, ymin)], fill=color)
        draw.text((xmin + 1, ymin - th), text, fill=(255, 255, 255))
    return im

以下是我client获取的数据：
{'err_no': 0, 'err_msg': '', 'key': ['bbox_result'], 'value': ["[{'category_id': 0, 'bbox': [104.77781677246094, 220.04672241210938, 26.746688842773438, 94.14239501953125], 'score': 0.9640887975692749}, {'category_id': 0, 'bbox': [261.9789123535156, 240.54869079589844, 28.68646240234375, 78.90553283691406], 'score': 0.8898410797119141}, {'category_id': 0, 'bbox': [129.2666473388672, 226.21530151367188, 22.13275146484375, 84.9058837890625], 'score': 0.8659509420394897}, {'category_id': 0, 'bbox': [201.70130920410156, 230.8160858154297, 22.97906494140625, 77.64558410644531], 'score': 0.7219269275665283}, {'category_id': 0, 'bbox': [10.000456809997559, 234.29498291015625, 16.534008979797363, 48.3221435546875], 'score': 0.6267762184143066}, {'category_id': 0, 'bbox': [228.2361297607422, 250.35365295410156, 29.966384887695312, 69.64634704589844], 'score': 0.5459369421005249}, {'category_id': 0, 'bbox': [155.479248046875, 253.79025268554688, 27.455657958984375, 41.54345703125], 'score': 0.5031428933143616}, {'category_id': 0, 'bbox': [80.72022247314453, 246.94285583496094, 23.80780029296875, 35.07670593261719], 'score': 0.5007156729698181}, {'category_id': 0, 'bbox': [49.320274353027344, 247.65826416015625, 15.526123046875, 28.13006591796875], 'score': 0.455748587846756}, {'category_id': 0, 'bbox': [68.85765838623047, 244.1172332763672, 13.843948364257812, 32.69041442871094], 'score': 0.4165054261684418}, {'category_id': 0, 'bbox': [252.58009338378906, 249.45486450195312, 21.008712768554688, 69.3369140625], 'score': 0.3903881311416626}, {'category_id': 0, 'bbox': [185.34873962402344, 243.6025390625, 9.71185302734375, 20.22100830078125], 'score': 0.3216567039489746}, {'category_id': 0, 'bbox': [193.24346923828125, 236.28211975097656, 11.90863037109375, 28.985488891601562], 'score': 0.24344971776008606}, {'category_id': 0, 'bbox': [0.7632584571838379, 230.71495056152344, 10.926928997039795, 41.00544738769531], 'score': 0.1596643477678299}, {'category_id': 0, 'bbox': [37.44097137451172, 246.95372009277344, 10.906280517578125, 25.067672729492188], 'score': 0.1594216674566269}, {'category_id': 0, 'bbox': [164.748046875, 237.98731994628906, 7.593902587890625, 21.414718627929688], 'score': 0.15178322792053223}, {'category_id': 0, 'bbox': [69.41304779052734, 242.54443359375, 9.963607788085938, 21.63653564453125], 'score': 0.13828220963478088}, {'category_id': 0, 'bbox': [241.49710083007812, 237.57098388671875, 9.55072021484375, 24.04180908203125], 'score': 0.12375061959028244}, {'category_id': 0, 'bbox': [285.961669921875, 278.46832275390625, 20.49835205078125, 39.2310791015625], 'score': 0.12212376296520233}, {'category_id': 0, 'bbox': [47.71091842651367, 242.14566040039062, 9.621788024902344, 17.767852783203125], 'score': 0.11466776579618454}, {'category_id': 0, 'bbox': [2.6708006858825684, 238.4586639404297, 11.30529260635376, 46.31599426269531], 'score': 0.09807839244604111}, {'category_id': 0, 'bbox': [90.9610824584961, 242.23593139648438, 26.988189697265625, 47.371826171875], 'score': 0.09298521280288696}, {'category_id': 0, 'bbox': [223.43670654296875, 232.9137420654297, 9.8106689453125, 20.303619384765625], 'score': 0.07590923458337784}, {'category_id': 0, 'bbox': [95.74839782714844, 253.88368225097656, 12.947189331054688, 24.901260375976562], 'score': 0.06756293773651123}, {'category_id': 0, 'bbox': [79.17843627929688, 209.60513305664062, 64.88380432128906, 106.12506103515625], 'score': 0.06710196286439896}, {'category_id': 0, 'bbox': [242.7984619140625, 247.4145965576172, 13.60919189453125, 29.554641723632812], 'score': 0.063991479575634}, {'category_id': 0, 'bbox': [128.98138427734375, 232.63487243652344, 10.82183837890625, 37.61366271972656], 'score': 0.05455680191516876}, {'category_id': 0, 'bbox': [235.85386657714844, 246.2654266357422, 20.116912841796875, 43.00025939941406], 'score': 0.046146053820848465}, {'category_id': 0, 'bbox': [211.26414489746094, 232.8152313232422, 14.574432373046875, 29.886520385742188], 'score': 0.045629601925611496}, {'category_id': 0, 'bbox': [84.02812194824219, 245.55104064941406, 9.152130126953125, 16.806442260742188], 'score': 0.0455605685710907}, {'category_id': 0, 'bbox': [252.2805633544922, 257.4069519042969, 13.570297241210938, 41.88812255859375], 'score': 0.045533448457717896}, {'category_id': 0, 'bbox': [264.5662536621094, 234.99530029296875, 10.1854248046875, 22.108673095703125], 'score': 0.04436985403299332}, {'category_id': 0, 'bbox': [202.88546752929688, 265.8107604980469, 20.2958984375, 54.047119140625], 'score': 0.04066871851682663}, {'category_id': 0, 'bbox': [131.0711669921875, 242.74331665039062, 13.006744384765625, 39.16448974609375], 'score': 0.0392686165869236}, {'category_id': 0, 'bbox': [309.6045227050781, 229.70028686523438, 7.1514892578125, 15.314117431640625], 'score': 0.03677855804562569}, {'category_id': 0, 'bbox': [312.711669921875, 279.6818542480469, 7.288330078125, 33.6279296875], 'score': 0.03606400638818741}, {'category_id': 0, 'bbox': [149.8148956298828, 233.8909149169922, 4.510650634765625, 8.024139404296875], 'score': 0.035880327224731445}, {'category_id': 0, 'bbox': [257.60809326171875, 240.74752807617188, 18.06378173828125, 56.512451171875], 'score': 0.031066296622157097}, {'category_id': 0, 'bbox': [3.7802281379699707, 224.1557159423828, 9.595162868499756, 17.800933837890625], 'score': 0.02785852923989296}, {'category_id': 0, 'bbox': [246.78485107421875, 233.73484802246094, 8.15594482421875, 9.2408447265625], 'score': 0.027851291000843048}, {'category_id': 0, 'bbox': [314.61029052734375, 262.7970886230469, 5.38970947265625, 42.03094482421875], 'score': 0.02773158811032772}, {'category_id': 0, 'bbox': [151.11831665039062, 249.7738037109375, 43.389617919921875, 57.58380126953125], 'score': 0.027723141014575958}, {'category_id': 2, 'bbox': [246.78485107421875, 233.73484802246094, 8.15594482421875, 9.2408447265625], 'score': 0.028934551402926445}, {'category_id': 24, 'bbox': [49.320274353027344, 247.65826416015625, 15.526123046875, 28.13006591796875], 'score': 0.07237203419208527}, {'category_id': 24, 'bbox': [220.49705505371094, 262.42218017578125, 33.94207763671875, 57.57781982421875], 'score': 0.05787387490272522}, {'category_id': 24, 'bbox': [290.365234375, 279.0458984375, 15.7193603515625, 33.7293701171875], 'score': 0.053795140236616135}, {'category_id': 24, 'bbox': [251.61244201660156, 276.2293395996094, 25.561019897460938, 42.9481201171875], 'score': 0.02837657742202282}, {'category_id': 26, 'bbox': [290.365234375, 279.0458984375, 15.7193603515625, 33.7293701171875], 'score': 0.08666737377643585}, {'category_id': 26, 'bbox': [49.320274353027344, 247.65826416015625, 15.526123046875, 28.13006591796875], 'score': 0.08247902244329453}, {'category_id': 26, 'bbox': [15.220354080200195, 229.57711791992188, 14.137325286865234, 49.01171875], 'score': 0.0702630952000618}, {'category_id': 26, 'bbox': [131.0711669921875, 242.74331665039062, 13.006744384765625, 39.16448974609375], 'score': 0.06700517982244492}, {'category_id': 26, 'bbox': [83.56745910644531, 247.42088317871094, 18.363632202148438, 31.571426391601562], 'score': 0.06437550485134125}, {'category_id': 26, 'bbox': [252.22776794433594, 282.8163146972656, 18.295944213867188, 36.19622802734375], 'score': 0.06416095793247223}, {'category_id': 26, 'bbox': [37.44097137451172, 246.95372009277344, 10.906280517578125, 25.067672729492188], 'score': 0.060257427394390106}, {'category_id': 26, 'bbox': [0.7632584571838379, 230.71495056152344, 10.926928997039795, 41.00544738769531], 'score': 0.0536506250500679}, {'category_id': 26, 'bbox': [68.85765838623047, 244.1172332763672, 13.843948364257812, 32.69041442871094], 'score': 0.04994073882699013}, {'category_id': 26, 'bbox': [220.49705505371094, 262.42218017578125, 33.94207763671875, 57.57781982421875], 'score': 0.04987350478768349}, {'category_id': 26, 'bbox': [157.95298767089844, 258.46490478515625, 23.588958740234375, 33.60784912109375], 'score': 0.03764669969677925}, {'category_id': 26, 'bbox': [285.8175048828125, 301.1617431640625, 21.4073486328125, 18.8382568359375], 'score': 0.037382662296295166}, {'category_id': 33, 'bbox': [161.3020477294922, 110.5899658203125, 69.60986328125, 31.129302978515625], 'score': 0.8318474888801575}, {'category_id': 33, 'bbox': [163.50860595703125, 43.322120666503906, 32.932464599609375, 15.67987060546875], 'score': 0.7850776314735413}, {'category_id': 33, 'bbox': [104.46907806396484, 174.47776794433594, 65.69660186767578, 30.46148681640625], 'score': 0.7323276400566101}, {'category_id': 33, 'bbox': [215.5902862548828, 20.69767189025879, 9.717376708984375, 9.320362091064453], 'score': 0.6093507409095764}, {'category_id': 33, 'bbox': [230.535400390625, 170.38589477539062, 8.75604248046875, 8.873382568359375], 'score': 0.582856297492981}, {'category_id': 33, 'bbox': [180.67295837402344, 80.13336181640625, 6.964111328125, 7.33001708984375], 'score': 0.5715456008911133}, {'category_id': 33, 'bbox': [252.06407165527344, 131.34054565429688, 10.320907592773438, 12.364410400390625], 'score': 0.5050010085105896}, {'category_id': 33, 'bbox': [116.24293518066406, 14.946075439453125, 4.87176513671875, 6.040863037109375], 'score': 0.5018177032470703}, {'category_id': 33, 'bbox': [131.40054321289062, 141.35267639160156, 81.0572509765625, 31.807525634765625], 'score': 0.4940277636051178}, {'category_id': 33, 'bbox': [134.87765502929688, 117.96810913085938, 90.93850708007812, 42.8350830078125], 'score': 0.45113810896873474}, {'category_id': 33, 'bbox': [120.64641571044922, 82.58491516113281, 11.941017150878906, 7.7373199462890625], 'score': 0.4398003816604614}, {'category_id': 33, 'bbox': [58.00877380371094, 119.26322174072266, 10.404739379882812, 7.4671630859375], 'score': 0.33544406294822693}, {'category_id': 33, 'bbox': [109.35174560546875, 116.77772521972656, 57.610260009765625, 27.150390625], 'score': 0.30991044640541077}, {'category_id': 33, 'bbox': [137.0703125, 61.817508697509766, 25.218505859375, 8.80178451538086], 'score': 0.2993524968624115}, {'category_id': 33, 'bbox': [41.569549560546875, 70.16163635253906, 26.247329711914062, 8.289474487304688], 'score': 0.2982534170150757}, {'category_id': 33, 'bbox': [29.40200424194336, 168.73802185058594, 4.914558410644531, 4.318359375], 'score': 0.2970665991306305}, {'category_id': 33, 'bbox': [88.9444351196289, 155.56719970703125, 33.40150451660156, 15.097259521484375], 'score': 0.27710196375846863}, {'category_id': 33, 'bbox': [79.92208099365234, 127.24400329589844, 7.9838104248046875, 6.562591552734375], 'score': 0.2425222098827362}, {'category_id': 33, 'bbox': [117.99847412109375, 149.89418029785156, 98.61587524414062, 40.26348876953125], 'score': 0.19696420431137085}, {'category_id': 33, 'bbox': [296.9390869140625, 0.0, 20.885498046875, 8.381329536437988], 'score': 0.168702632188797}, {'category_id': 33, 'bbox': [88.37452697753906, 155.50161743164062, 55.057098388671875, 29.975738525390625], 'score': 0.12303498387336731}, {'category_id': 33, 'bbox': [42.4930419921875, 68.8037338256836, 5.987030029296875, 4.6690673828125], 'score': 0.1058867797255516}, {'category_id': 33, 'bbox': [58.162689208984375, 120.93990325927734, 14.011627197265625, 7.4203948974609375], 'score': 0.10208256542682648}, {'category_id': 33, 'bbox': [30.223472595214844, 169.8108367919922, 5.3067169189453125, 4.285125732421875], 'score': 0.09688357263803482}, {'category_id': 33, 'bbox': [117.02528381347656, 13.713472366333008, 4.44915771484375, 5.150276184082031], 'score': 0.08531945943832397}, {'category_id': 33, 'bbox': [155.479248046875, 253.79025268554688, 27.455657958984375, 41.54345703125], 'score': 0.08339046686887741}, {'category_id': 33, 'bbox': [42.666481018066406, 148.44764709472656, 3.6043853759765625, 3.60260009765625], 'score': 0.0753670185804367}, {'category_id': 33, 'bbox': [59.37783432006836, 210.90452575683594, 63.916690826416016, 30.205535888671875], 'score': 0.074627585709095}, {'category_id': 33, 'bbox': [90.33345031738281, 159.356689453125, 70.24696350097656, 42.218292236328125], 'score': 0.07454878091812134}, {'category_id': 33, 'bbox': [140.13076782226562, 64.16253662109375, 6.197235107421875, 5.222900390625], 'score': 0.06673435866832733}, {'category_id': 33, 'bbox': [105.12716674804688, 115.27299499511719, 92.50146484375, 39.214599609375], 'score': 0.05628605931997299}, {'category_id': 33, 'bbox': [106.47122192382812, 117.14395141601562, 23.82427978515625, 14.825668334960938], 'score': 0.050907064229249954}, {'category_id': 33, 'bbox': [299.37481689453125, 0.0, 7.36944580078125, 7.277366638183594], 'score': 0.04641982540488243}, {'category_id': 33, 'bbox': [48.68267822265625, 211.44992065429688, 20.631698608398438, 17.972808837890625], 'score': 0.0377458781003952}, {'category_id': 33, 'bbox': [142.03839111328125, 58.0018196105957, 25.4373779296875, 11.968059539794922], 'score': 0.033972661942243576}, {'category_id': 33, 'bbox': [139.00241088867188, 43.36893081665039, 60.937255859375, 22.190196990966797], 'score': 0.03145671263337135}, {'category_id': 33, 'bbox': [232.95480346679688, 173.10511779785156, 7.701629638671875, 7.551666259765625], 'score': 0.030147897079586983}, {'category_id': 33, 'bbox': [196.6067657470703, 198.06613159179688, 10.19873046875, 9.876678466796875], 'score': 0.029660195112228394}, {'category_id': 33, 'bbox': [111.400634765625, 177.395263671875, 24.440582275390625, 14.125274658203125], 'score': 0.029003433883190155}, {'category_id': 56, 'bbox': [290.365234375, 279.0458984375, 15.7193603515625, 33.7293701171875], 'score': 0.031555965542793274}, {'category_id': 56, 'bbox': [252.22776794433594, 282.8163146972656, 18.295944213867188, 36.19622802734375], 'score': 0.027451490983366966}]"], 'tensors': []}

**Comment by wxf764571829** [comment]
合成代码
![image](https://user-images.githubusercontent.com/46362180/149262679-b054be4b-35ec-470e-aaa3-d0a8ed9fff19.png)

**Comment by heavengate** [comment]
你在哪里做了resize，看你贴的代码是画框的代码，没有resize的代码
