### ISSUE TITLE
关于S2ANet旋转模型

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleDetection#5104]
![image](https://user-images.githubusercontent.com/87969070/149274192-65e26710-3878-455a-8727-1834435ab87e.png)
请问一下，检测上图中的三种目标，同时显示正确的方向，目前训练集是45张。检测结果中方向一直存在着问题，请问有什么优化策略吗？
![image](https://user-images.githubusercontent.com/87969070/149274485-eb2c51b4-9042-4a3d-a695-3b88b763be49.png)
num_classes设置为3

**Comment by heavengate** [comment]
你好，贴一下你的检测效果图看一下呢
如果你训练集只有45张的话，你可以把你要检测的图也加到训练集中做训练，来过拟合你要检测的图，来确认一下是什么问题，如果过拟合训练之后能正确检测出你的图，那说明可能是训练数据不够或者训练iter不够之类的问题，如果过拟合训练都不能检测出正确的结果，可能就是配置错误了

**Comment by Hold-on-li** [comment]
> 你好，贴一下你的检测效果图看一下呢 如果你训练集只有45张的话，你可以把你要检测的图也加到训练集中做训练，来过拟合你要检测的图，来确认一下是什么问题，如果过拟合训练之后能正确检测出你的图，那说明可能是训练数据不够或者训练iter不够之类的问题，如果过拟合训练都不能检测出正确的结果，可能就是配置错误了
![image](https://user-images.githubusercontent.com/87969070/149320519-ebc4b310-f41d-4c4c-8c3e-1287620d6c4d.png)
结果如上图
但是我label的时候 
![image](https://user-images.githubusercontent.com/87969070/149320600-af50362d-d5ca-4e28-949a-fdc471bcfbb1.png)
是这样的

**Comment by heavengate** [comment]
看着框位置基本正确，角度大致方向也对，角度精度不太好，应该是训练不足导致的，可以试下能否加大一下数据集，多训一个epoch，可以根据你的卡数调整一下learning rate
另外，这个loss_weight的第5位就是角度的loss weight，也可以调大一点试下
https://github.com/PaddlePaddle/PaddleDetection/blob/635e3e0a80f3d05751cdcfca8af04ee17c601a92/configs/dota/s2anet_alignconv_2x_dota.yml#L24
