### ISSUE TITLE
[BUG]preprocess对视频与图片的处理不一致

### ISSUE THREAD

**Issue by lazyn1997** [PaddlePaddle/PaddleDetection#5107]
## 描述问题/Describe the bug
preprocess操作对视频与图片的处理不一致，如果预测图片，则用opencv读入图片后要进行BGR到RGB颜色空间的转换，如果预测视频，则对帧图片不做任何处理就返回，
![image](https://user-images.githubusercontent.com/34644177/149349291-075e48a0-713c-4576-ae61-cab0a8a76de7.png)
preprocess.py中处理部分如下图所示：
![image](https://user-images.githubusercontent.com/34644177/149348478-4530e91b-841f-4bed-9012-73cffdb6af3e.png)

这样的话，预测视频与预测图片传入detector的数据的颜色空间根本不一致，预测视频为BGR，预测图片为RGB，应该会影响预测效果，请问我应该采用哪一种颜色空间，并对相关文件做出修改。

**Comment by nemonameless** [comment]
建议以图片预测的为准

**Comment by lazyn1997** [comment]
首先是明确了这是bug吗，其次意思是视频那里也需要加一句下面的语句是吗？
![image](https://user-images.githubusercontent.com/34644177/149650908-7dac28eb-b638-4782-978a-b174006a14dc.png)

**Comment by wangxinxin08** [comment]
确实是一个问题，需要加下面的语句转化为RGB，后续我们会修复这个问题

**Comment by lazyn1997** [comment]
训练的时候是用RGB进行训练的是吗？

**Comment by wangxinxin08** [comment]
是的

**Comment by lazyn1997** [comment]
好的，感谢

**Comment by lazyn1997** [comment]
此问题在当前版本依然存在，请问这个颜色空间问题对结果的影响有多大，还望修复一下，保持视频与图片处理的一致性。
![image](https://user-images.githubusercontent.com/34644177/167526421-8a9d841e-f9d9-4229-9241-8de70c5cb505.png)

**Comment by wangxinxin08** [comment]
感谢你的反馈，fixed by https://github.com/PaddlePaddle/PaddleDetection/pull/5918, https://github.com/PaddlePaddle/PaddleDetection/pull/5919
