### ISSUE TITLE
[Other General Issues]windows安装requirements的cython_bbox包报错cl.exe不存在

### ISSUE THREAD

**Issue by yangjian1218** [PaddlePaddle/PaddleDetection#5108]
我电脑系统为win11,在安装paddleDetection前,安装requirements的cython_bbox包,报错:
error: command 'cl.exe' failed: No such file or directory.
我使用的是vs2019, cl.exe所在的目录也添加到系统环境变量中了.在终端输入cl是有信息输出的. 用prompt管理者打开进行安装也是报错.跪求大神来解决这个bug,同理,在安装其他python包或者编译其他库,比如insightface最新包等或者编译seetaface也是这个问题. 到底是我电脑系统问题还是vs2019不支持的问题?
![image](https://user-images.githubusercontent.com/66234937/149497557-2e6170a4-151e-466a-a786-6fe89cf3e163.png)

**Comment by nemonameless** [comment]
windons安装可以
```
pip install -e git+https://github.com/samson-wang/cython_bbox.git#egg=cython-bbox
```
或参考这个链接 https://stackoverflow.com/questions/60349980/is-there-a-way-to-install-cython-bbox-for-windows
您想跑什么模型呢？如果不是实用跟踪模型的话，是不需要cython_bbox包的，也可以注释相关代码。

**Comment by LukeALee** [comment]
把requirements.txt里的Cython 改成小写应该就可以了
