### ISSUE TITLE
ppyolo_tiny2.0 如何画val的 loss  以及 每个类的AP值？

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#5109]
如何 修改 eval 评估时候 后面 添加 --classwise 后 
![Uploading 捕获.PNG…]()
显示的 各类的 AP 值 是 IOU =0.5的呢

**Comment by yghstill** [comment]
@STUSER001 利用coco api得到的mAP和单类AP是0.5：0.95，如果想获取iou=0.5的值，可以改成VOC的评估方式，或者修改classwise逻辑：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/metrics/coco_utils.py#L115

**Comment by Bigtuo** [comment]
针对coco评估，ppdet/metrics/coco_utils.py 133行的precision = precisions[：, :, idx, 0, -1]改成precision = precisions[0, :, idx, 0, -1]，第一项0代表iou=0.5
