### ISSUE TITLE
yolov3-enhance-reader，normalization设置

### ISSUE THREAD

**Issue by zimoqingfeng** [PaddlePaddle/PaddleDetection#511]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/configs/dcn/yolov3_enhance_reader.yml#L71

如上所示，我们的yolo-v3模型在预处理的时候，是不做“/255”的操作么。如果这个时候方差设置<1，那么预处理后的像素值可能是大于255的吗。

先多谢您解答啦。

**Comment by willthefrog** [comment]
这个配置是个特例。当时训练时设置有些错误，导致结果的权重是按照这种方式预处理的，所以这里保持了一致。

**Comment by zimoqingfeng** [comment]
ok 多谢哈
