### ISSUE TITLE
[Other General Issues]使用gpu预测达不到预期效果

### ISSUE THREAD

**Issue by q774740909** [PaddlePaddle/PaddleDetection#5110]
有个项目我在tensorflow上能达到70ms一次检测，并且gpu的内存使用是5个G左右，比cpu块7倍。但是最近我用ppyolov2重新训练并部署，在和tensorflow同一个机器下，只能达到500ms一次，gpu使用率是1.5个G，并且用GPU的检测速度只比CPU块两倍而已。请问这是什么原因吗？

**Comment by wangxinxin08** [comment]
请问你GPU的机器是什么？如何进行部署的？
