### ISSUE TITLE
onnx相关问题

### ISSUE THREAD

**Issue by ElieenAndBella** [PaddlePaddle/PaddleDetection#5112]
为什么导出的onnx的input_feed会有scale_factor这个参数，压根就没见过

**Comment by ElieenAndBella** [comment]
有没有paddledetection导出的onnx调用的相关文章啊

**Comment by ElieenAndBella** [comment]
我的模型是Yolov3模型

**Comment by yghstill** [comment]
@ElieenAndBella scale_factor这个参数是真是图片尺寸和resize后图片尺寸的比例因子，用来后处理解码，具体可参考预测部署的预处理代码：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/python/preprocess.py#L77
