### ISSUE TITLE
ppyolo_tiny2.0 评估 过拟合问题

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#5113]
在自定义数据集的 验证集 map 比 测试集 大2倍 这个怎么解决 训练越多 验证集的 map 提高 测试集的反而 越来越下降

**Comment by wangxinxin08** [comment]
你的数据量是多少？如果数据量过少的话，可以加强一下数据增广，另外，可以增加weight decay

**Comment by STUSER001** [comment]
> 你的数据量是多少？如果数据量过少的话，可以加强一下数据增广，另外，可以增加weight decay

2.3万 weight decay 怎么加啊？ 这个算法 刚刚接触 有些地方 还没有太看懂

**Comment by wangxinxin08** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/ppyolo/_base_/optimizer_650e.yml#L21 这里可以增大下weight decay，另外小模型在数据集上过拟合有点奇怪，而且你的数据量并不算小，可以看下测试集，验证集和训练集切分的是否合理？

**Comment by STUSER001** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/ppyolo/_base_/optimizer_650e.yml#L21 这里可以增大下weight decay，另外小模型在数据集上过拟合有点奇怪，而且你的数据量并不算小，可以看下测试集，验证集和训练集切分的是否合理？

我的数据分配比例 是 8:1:1 这样分配的

**Comment by STUSER001** [comment]
> > https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/ppyolo/_base_/optimizer_650e.yml#L21 这里可以增大下weight decay，另外小模型在数据集上过拟合有点奇怪，而且你的数据量并不算小，可以看下测试集，验证集和训练集切分的是否合理？
> 
> 我的数据分配比例 是 8:1:1 这样分配的

还有一个 问题是 自己写了 一个根据 标签 看检测分类准不准的 代码 这里分类准确率99% 在不看 iou的时候

**Comment by wangxinxin08** [comment]
你这属于数据不均衡，可以考虑的一种方法是：对数据量的比较多的类别进行采样，或者对数据量比较少的类别手动进行数据增广，使其数量接近匹配

**Comment by STUSER001** [comment]
> 你这属于数据不均衡，可以考虑的一种方法是：对数据量的比较多的类别进行采样，或者对数据量比较少的类别手动进行数据增广，使其数量接近匹配

我现在做的是 二分类 的 类别数据量是 5:5  只不过 训练的时候  训练集，验证集，测试集 比例 设置了 8:1:1： 且每个数据集 类别分配也是 5：5 的 没有那个类别数据多的情况啊

**Comment by STUSER001** [comment]
> 你这属于数据不均衡，可以考虑的一种方法是：对数据量的比较多的类别进行采样，或者对数据量比较少的类别手动进行数据增广，使其数量接近匹配

还有问题请问下 ppyolo_tiny 官方给的 检测头部 用的还是 yolov3 的是吧 但是我在网上看说是用了 深度可分离卷积啊，这个好像对不上啊，还有头部文件里那个是 深度可分离卷积呢 由于代码读写能力有限 还请大神麻烦告诉我一下 谢谢

**Comment by wangxinxin08** [comment]
yolov3_head确实不是使用深度可分离卷积因为head只有一个卷积层，ppyolo-tiny的neck和head确实使用的是深度可分离卷积

**Comment by STUSER001** [comment]
> yolov3_head确实不是使用深度可分离卷积因为head只有一个卷积层，ppyolo-tiny的neck和head确实使用的是深度可分离卷积

我看ppyolv论文里说的yolov3 检测头部就是 3*3卷积 加1*1 卷积 这样做的 ，这里卷积是正常的卷积啊 这样好像tiny 检测头没有用 dw卷积啊

![image](https://user-images.githubusercontent.com/88072901/150947504-f618e14a-4a0c-415f-98fc-0b37011984f6.png)

![image](https://user-images.githubusercontent.com/88072901/150948705-3c0cf0de-f5ab-493c-9864-14daf1240517.png)

还有这个是一篇论文上的截图 按照这位作者的说法 检测头是yolov3 的也就是 正常卷积操作吧 这个作者也是 在原有官方提供的ppyolo_tiny 模型基础上把 FPN 做了修改
![image](https://user-images.githubusercontent.com/88072901/150950976-083b083f-c167-4a2d-8bcc-2128f31943ce.png)

**Comment by wangxinxin08** [comment]
是的，这篇文章的链接可以发一下吗？

**Comment by STUSER001** [comment]
> 是的，这篇文章的链接可以发一下吗？
https://kns.cnki.net/kcms/detail/11.4537.x.20211221.1700.001.html
这是文章的连接 也就是说官方给的 检测头 还是用的yolov3的检测头 常规卷积是吧

**Comment by wangxinxin08** [comment]
是的，yolov3的检测头还是常规卷积

**Comment by STUSER001** [comment]
> 是的，yolov3的检测头还是常规卷积

哦 这样的话 官方说的 head 部分 采用 dw 是那个文件啊
![image](https://user-images.githubusercontent.com/88072901/150953818-84e71649-e3d7-4db3-87ee-1ae774a4dbe6.png)

现在想按照网上说的 把检测头部更换看看
![image](https://user-images.githubusercontent.com/88072901/150953992-86e85ecb-bf16-4b48-94c4-c0c336a59b49.png)
但是我看官方这个代码 就只做了 1X1的卷积啊 我理解有误么？
![image](https://user-images.githubusercontent.com/88072901/151029730-0c9cfa4b-8dad-4309-a4f4-63f3c4d74021.png)

**Comment by wangxinxin08** [comment]
yolov3 head使用1x1的卷积其实没必要换成dw的

**Comment by wangxinxin08** [comment]
> > 你这属于数据不均衡，可以考虑的一种方法是：对数据量的比较多的类别进行采样，或者对数据量比较少的类别手动进行数据增广，使其数量接近匹配
> 
> 我现在做的是 二分类 的 类别数据量是 5:5 只不过 训练的时候 训练集，验证集，测试集 比例 设置了 8:1:1： 且每个数据集 类别分配也是 5：5 的 没有那个类别数据多的情况啊

好的，如果这样还是出现过拟合的话，可能需要看下训练集，验证集和测试集的切分是否合理，比如数据分布(目标的大小)是否一致

**Comment by STUSER001** [comment]
> > > 你这属于数据不均衡，可以考虑的一种方法是：对数据量的比较多的类别进行采样，或者对数据量比较少的类别手动进行数据增广，使其数量接近匹配
> > 
> > 
> > 我现在做的是 二分类 的 类别数据量是 5:5 只不过 训练的时候 训练集，验证集，测试集 比例 设置了 8:1:1： 且每个数据集 类别分配也是 5：5 的 没有那个类别数据多的情况啊
> 
> 好的，如果这样还是出现过拟合的话，可能需要看下训练集，验证集和测试集的切分是否合理，比如数据分布(目标的大小)是否一致

这样啊 还有一个问题 想问 这个算法 说做了 数据曾广
![image](https://user-images.githubusercontent.com/88072901/151094597-fde2230d-b713-4754-ac23-7eb8b9fdc0ec.png)

这个曾广了多少倍怎么看啊

**Comment by STUSER001** [comment]
> yolov3 head使用1x1的卷积其实没必要换成dw的

那就是说 与 论文的检测头 不一样 是吧  论文说是 先做了3x3 卷积 然后 在做了1x1 卷积啊

**Comment by STUSER001** [comment]
![image](https://user-images.githubusercontent.com/88072901/151095000-37c79483-dfe9-4951-b6fb-4d49fc7f2fb4.png)
还有 数据自定义了2万张 一次迭代1000 跑个 5天多 这正常么？

**Comment by wangxinxin08** [comment]
>
> 这个曾广了多少倍怎么看啊

增广了多少倍是没办法定义的

**Comment by STUSER001** [comment]
> > 这个曾广了多少倍怎么看啊
> 
> 增广了多少倍是没办法定义的

问这个就是 因为 数据自定义了2万张 一次迭代1000 跑个 5天多  这正常么？是因为曾广了数据 所以 时间久吧 我听说 公用的十几万张才跑一星期多啊

还有我现在 遇到情况就是 训练的时候是 训练集和 验证集 交叉训练的 ，因此评估的时候  验证集 高可以理解 ，问题是测试集 差iou=0.5时候 50 左右 而且 训练越多 差的越多。。。

**Comment by wangxinxin08** [comment]
> 

ppyolo论文中detection head确实是3x3卷积+1x1卷积，其中3x3卷积在neck中，见https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/necks/yolo_fpn.py#L95 , ppyolo tiny的detection head相比于ppyolo做了一些改动，只有两个1x1的卷积，见https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/necks/yolo_fpn.py#L291 , 这一点和论文中的并不冲突

**Comment by wangxinxin08** [comment]
> > > 这个曾广了多少倍怎么看啊
> > 
> > 
> > 增广了多少倍是没办法定义的
> 
> 问这个就是 因为 数据自定义了2万张 一次迭代1000 跑个 5天多 这正常么？是因为曾广了数据 所以 时间久吧 我听说 公用的十几万张才跑一星期多啊
> 
> 还有我现在 遇到情况就是 训练的时候是 训练集和 验证集 交叉训练的 ，因此评估的时候 验证集 高可以理解 ，问题是测试集 差iou=0.5时候 50 左右 而且 训练越多 差的越多。。。

1. 默认配置是使用8卡训练的，你用单卡训练的话，自然会变慢，另外数据增广不会增加运行的图片的数量，只是在数据变换的时候对图片以及标注做随机处理，所以不存在你说的增广多少倍的问题
2. 如果过拟合，可以考虑调小训练schedule试试，把schedule同比缩放为原来的2/3或者1/2，这样也可以节省训练时间

**Comment by STUSER001** [comment]
> 2\. schedule

缩小迭代次数 是么？ 我训练时候 用了8卡的训练啊 
![image](https://user-images.githubusercontent.com/88072901/151096344-4aaa47b2-a734-4f17-9957-acff6affc0ae.png)

按照这个命令 执行的啊 还有 我看都说 数据集不够 就做数据增广么 位移 旋转 缩放啥的 那不就是增加数据的意思么？

**Comment by wangxinxin08** [comment]
> > 2. schedule
> 
> 缩小迭代次数 是么？ 我训练时候 用了8卡的训练啊 ![image](https://user-images.githubusercontent.com/88072901/151096344-4aaa47b2-a734-4f17-9957-acff6affc0ae.png)
> 
> 按照这个命令 执行的啊 还有 我看都说 数据集不够 就做数据增广么 位移 旋转 缩放啥的 那不就是增加数据的意思么？

1. 数据增广并没有增加数据，只是对数据做了变换，增加了数据的多样性，使用不使用数据增广同样的schedule迭代的次数不变
2. 可以修改optimizer配置文件，将整个schedule减少下，比如缩小为原来的2/3或者1/2，见https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/ppyolo/ppyolo_tiny_650e_coco.yml#L5

**Comment by STUSER001** [comment]
> > 
> 
> ppyolo论文中detection head确实是3x3卷积+1x1卷积，其中3x3卷积在neck中，见https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/necks/yolo_fpn.py#L95 , ppyolo tiny的detection head相比于ppyolo做了一些改动，只有两个1x1的卷积，见https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/necks/yolo_fpn.py#L291 , 这一点和论文中的并不冲突

tiny 是这两个 1x1 卷积是么？ 那neck 加 head 不就用3个 1x1 卷积么？
![image](https://user-images.githubusercontent.com/88072901/151097569-aee34688-9296-4ac0-8193-a6a0baa528f8.png)

**Comment by STUSER001** [comment]
> > > 2. schedule
> > 
> > 
> > 缩小迭代次数 是么？ 我训练时候 用了8卡的训练啊 ![image](https://user-images.githubusercontent.com/88072901/151096344-4aaa47b2-a734-4f17-9957-acff6affc0ae.png)
> > 按照这个命令 执行的啊 还有 我看都说 数据集不够 就做数据增广么 位移 旋转 缩放啥的 那不就是增加数据的意思么？
> 
> 1. 数据增广并没有增加数据，只是对数据做了变换，增加了数据的多样性，使用不使用数据增广同样的schedule迭代的次数不变
> 2. 可以修改optimizer配置文件，将整个schedule减少下，比如缩小为原来的2/3或者1/2，见https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/ppyolo/ppyolo_tiny_650e_coco.yml#L5

这个明白 就是 数据多样性 不就是 每次训练时候 进入的图片数量一定 ，只不过 每次进入的图片比上次做了一些修改 不就是这种意思么 也可以理解 变相增加了数据吧

还有 这个数据增强部分 就是每次对图片 随机做图中mixup，随机对比度，裁剪，扩张等操作 所以 就不能说 多少倍 ，只不过每次做了 这些操作 会影响 训练时间对吧
![image](https://user-images.githubusercontent.com/88072901/151099711-9082076e-be5a-4c16-89e7-1476a7b0dede.png)

**Comment by wangxinxin08** [comment]
> > > 
> > 
> > 
> > ppyolo论文中detection head确实是3x3卷积+1x1卷积，其中3x3卷积在neck中，见https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/necks/yolo_fpn.py#L95 , ppyolo tiny的detection head相比于ppyolo做了一些改动，只有两个1x1的卷积，见https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/necks/yolo_fpn.py#L291 , 这一点和论文中的并不冲突
> 
> tiny 是这两个 1x1 卷积是么？ 那neck 加 head 不就用3个 1x1 卷积么？ ![image](https://user-images.githubusercontent.com/88072901/151097569-aee34688-9296-4ac0-8193-a6a0baa528f8.png)

图中画的1x1和head无关，是fpn的upsample的一部分，所以只有两个1x1，建议认真看下代码

**Comment by wangxinxin08** [comment]
> > > > 2. schedule
> > > 
> > > 
> > > 缩小迭代次数 是么？ 我训练时候 用了8卡的训练啊 ![image](https://user-images.githubusercontent.com/88072901/151096344-4aaa47b2-a734-4f17-9957-acff6affc0ae.png)
> > > 按照这个命令 执行的啊 还有 我看都说 数据集不够 就做数据增广么 位移 旋转 缩放啥的 那不就是增加数据的意思么？
> > 
> > 
> > 
> > 1. 数据增广并没有增加数据，只是对数据做了变换，增加了数据的多样性，使用不使用数据增广同样的schedule迭代的次数不变
> > 2. 可以修改optimizer配置文件，将整个schedule减少下，比如缩小为原来的2/3或者1/2，见https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/ppyolo/ppyolo_tiny_650e_coco.yml#L5
> 
> 这个明白 就是 数据多样性 不就是 每次训练时候 进入的图片数量一定 ，只不过 每次进入的图片比上次做了一些修改 不就是这种意思么 也可以理解 变相增加了数据吧
> 
> 还有 这个数据增强部分 就是每次对图片 随机做图中mixup，随机对比度，裁剪，扩张等操作 所以 就不能说 多少倍 ，只不过每次做了 这些操作 会影响 训练时间对吧 ![image](https://user-images.githubusercontent.com/88072901/151099711-9082076e-be5a-4c16-89e7-1476a7b0dede.png)

数据增广会增加数据预处理的时间

**Comment by STUSER001** [comment]
> > > > 
> > > 
> > > 
> > > ppyolo论文中detection head确实是3x3卷积+1x1卷积，其中3x3卷积在neck中，见https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/necks/yolo_fpn.py#L95 , ppyolo tiny的detection head相比于ppyolo做了一些改动，只有两个1x1的卷积，见https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/necks/yolo_fpn.py#L291 , 这一点和论文中的并不冲突
> > 
> > 
> > tiny 是这两个 1x1 卷积是么？ 那neck 加 head 不就用3个 1x1 卷积么？ ![image](https://user-images.githubusercontent.com/88072901/151097569-aee34688-9296-4ac0-8193-a6a0baa528f8.png)
> 
> 图中画的1x1和head无关，是fpn的upsample的一部分，所以只有两个1x1，建议认真看下代码

哦 明白了 就是 现在tiny 是 neck 一个1x1 head 一个 1x1 这样做的 2个1x1卷积 是吧 由于刚开始看 很多地方 看不太懂 哈哈
