### ISSUE TITLE
tools里边并没有这些程序

### ISSUE THREAD

**Issue by sfx-666** [PaddlePaddle/PaddleDetection#5116]
# bdd100kmot
tools/bdd100kmot/gen_bdd100kmot_vehicle.sh：通过执行bdd100k2mot.py和gen_labels_MOT.py生成bdd100kmot_vehicle 数据集
tools/bdd100kmot/bdd100k2mot.py：将bdd100k全集转换成mot格式
tools/bdd100kmot/gen_labels_MOT.py：生成单类别的labels_with_ids文件
# visdrone
tools/visdrone/visdrone2mot.py：生成visdrone_vehicle

**Comment by wangxinxin08** [comment]
你好，请问你说的这些工具是在哪个文档中介绍的？

**Comment by sfx-666** [comment]
你好，在车辆跟踪中提到的，已经找到了，在configs/mot/vehivle/tools里



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月17日(星期一) 上午10:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] tools里边并没有这些程序 (Issue #5116)





 
你好，请问你说的这些工具是在哪个文档中介绍的？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
