### ISSUE TITLE
致泊老师在aistudio上公开的“基于关键点检测的摔倒识别”的例子是离线检测，如何做到在线检测？ 

### ISSUE THREAD

**Issue by desertfex** [PaddlePaddle/PaddleDetection#5119]
请教如何通过笔记本电脑的摄像头或者手机摄像头做到实时的摔倒检测？有可以参考的例子、代码吗？谢谢

我目前已经通过笔记本电脑的内置摄像头实现了实时的关键点检测，可是老师的摔倒检测需要读取一个已有的.json的文件，而该文件似乎无法实时生成，这样就做不到无法实时进行摔倒检测。求老师指导！本人微信：mingjialia

**Comment by desertfex** [comment]
python deploy/python/det_keypoint_unite_infer.py --det_model_dir=output_inference/ppyolo_r50vd_dcn_2x_coco/ --keypoint_model_dir=output_inference/hrnet_w32_256x192/ --camera_id 0  --device=gpu --save_res=True

我用的上面这个命令就可以做到实时的关键点检测，我现在想做到实时的摔倒检测

**Comment by nemonameless** [comment]
#4666  可以加入paddledetection交流群。

**Comment by zoooo0820** [comment]
@desertfex 
json的文件实际只是存储了一下预测结果，而本身的预测结果在[这里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/python/det_keypoint_unite_infer.py#L193-L223)给出。可以自己修改一下这个脚本，将摔倒检测的代码函数功能加进来，将`keypoint_res`的相关内容作为下一步的输入实现摔倒检测。
