### ISSUE TITLE
官网发布的预训练模型，能直接用于生产环境进行预测？

### ISSUE THREAD

**Issue by DavidFangx** [PaddlePaddle/PaddleDetection#512]
官网发布的预训练模型，能直接用于生产环境进行预测？
比如这个模型：
https://paddlemodels.bj.bcebos.com/object_detection/yolov3_r50vd_dcn_obj365_dropblock_iouloss.tar

以及这里发布的模型列表：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/MODEL_ZOO_cn.md

若能用，怎么使用？或转成hub方式部署？

**Comment by FDInSky** [comment]
这些预训练模型，都是基于通用数据集训练的，比如coco，object365，一般情况下都是要finetune一下自己的数据。

**Comment by still-wait** [comment]
@DavidFangx Python端部署请参考[Python 部署方案](https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/python)，和[C++部署方案](https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/advanced_tutorials/inference/DEPLOYMENT.md)

**Comment by qingqing01** [comment]
@DavidFangx 预训练模型能否用于生产环境进行预测，得看看检测的类别是否匹配，目前提供的模型有COCO和OBJ-365, OpenImages的，可以对别类别，如果类别匹配，可以试下，否则就不行。
