### ISSUE TITLE
pptiny-pose 这个模型可以移植到英伟达jetson 设备吗

### ISSUE THREAD

**Issue by francislinker** [PaddlePaddle/PaddleDetection#5121]
请问pptiny-pose 这个模型可以移植到英伟达jetson 设备吗，如果可以，有相关教程没有呢

**Comment by zoooo0820** [comment]
@francislinker 
jetson设备上部署模型需要在[这里](https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html)根据具体设备安装对应预测库，其他使用流程可以参考模型所在文档。
