### ISSUE TITLE
报错问题[Other General Issues]

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#5127]
<img width="981" alt="iShot2022-01-18 18 09 54" src="https://user-images.githubusercontent.com/78856426/149916853-a5600ad0-5ddc-4ab1-a2f3-798abe9eef03.png">
请问这个报错是怎么回事呀

**Comment by nemonameless** [comment]
根据报错提示，可以在cfg文件里添加```find_unused_parameters: True```试试。
提问请发下运行命令，以及说明下如何复现这个问题谢谢。
