### ISSUE TITLE
不同的分支，训练同一套配置文件，产生不同的模型结构？？？[Other General Issues]

### ISSUE THREAD

**Issue by TinyQi** [PaddlePaddle/PaddleDetection#5130]
我今天测试了一下发现2.0的paddledetection分支和2.2的paddledetection分支训练出来的模型结构很不一样，这是正常的吗？

**Comment by nemonameless** [comment]
具体哪个模型？可以在2.2分支下那个模型相关的代码查看commit改动日志

**Comment by TinyQi** [comment]
> 具体哪个模型？可以在2.2分支下那个模型相关的代码查看commit改动日志

模型是：ppyolo_r50vd_dcn_voc

具体两个训练环境如下
1. 训练工程的分支：PaddleDetection-release-2.3，paddlepaddle-gpu：2.1.3
2. devlop分支：具体记不住了，半年前的版本，paddlepaddle-gpu：2.0.1

昨天也具体测试了一下，发现很不一样

**Comment by TinyQi** [comment]
模型结构不一样，这是正常的嘛？不应该呀

**Comment by wangxinxin08** [comment]
模型结构不一样是指哪一部分啊？

**Comment by TinyQi** [comment]
> 模型结构不一样是指哪一部分啊？

我把模型导出成图片了，可以看看

这是2.1.3的
![2 1 3](https://user-images.githubusercontent.com/28993936/150097884-3fa49b84-73a3-4dfe-b509-d82e287610c0.png)


这是2.0.1的
![2 0 1](https://user-images.githubusercontent.com/28993936/150097644-4ce054b9-af7b-4029-8bee-abc1fcbb24a9.png)

**Comment by TinyQi** [comment]
> 模型结构不一样是指哪一部分啊？

主要就是下面的结构就不一样了，具体我还真说不清楚

我把模型导出成图片了，可以看看

这是2.1.3的模型图
![2 1 3](https://user-images.githubusercontent.com/28993936/150098599-3aad238b-5423-4442-8788-f7f161304598.png)

这是2.0.1的模型图
![2 0 1](https://user-images.githubusercontent.com/28993936/150098769-dc99c982-645b-4eb1-9e59-39eb412b2a7b.png)
