### ISSUE TITLE
如何根据修改已有inference模型的输入为“动态shape” ？

### ISSUE THREAD

**Issue by zzcgithub** [PaddlePaddle/PaddleDetection#5131]
目前已有一些导出的模型参数（model/__params）, 可以通过paddle框架进行正常的推理，但是因为输入的shape已经固定，导致无法进行动态推理/无法使用tensorrt。具体问题如下，模型的输入输出截图截图均由netron可视化得出。

1. 使用paddledetection导出的faster-rcnn检测模型，paddle版本1.8.4，只有model和params参数。
如何将输入的shape从（[?,3,?,?]）转化为（?x3x512x512)， 以便支持tensorrt的推理加速

![image](https://user-images.githubusercontent.com/13117136/149952959-15f8985b-d4f6-426d-8bc7-5869a5ddaf61.png)

2. 使用paddledetection导出ppyolo的检测模型paddle版本2.1， 能否将matrix nms的输出改成动态形式？
即从[3840,6] -> [?,3840,6]

![image](https://user-images.githubusercontent.com/13117136/149953000-9fc716b3-ade1-469b-9f64-ef56a4467f9d.png)

**Comment by ghostxsl** [comment]
想用动态shape的话，1. 重新导出，导出的时候指定TestReader.inputs_def.image_shape: [3, -1, 1]。2. 在导出后的文件infer_cfg.yml里，设置use_dynamic_shape: true
