### ISSUE TITLE
如何在源码中安全地添加代码以实现预测而不是在终端指定（那个模型相关的文件不知道怎么在infer.py中直接指定，而不是在终端指定）

### ISSUE THREAD

**Issue by DLNovice** [PaddlePaddle/PaddleDetection#5133]
在终端运行代码是可以正常输出的
python tools/infer.py --model_dir=inference_model_final/ssd_mobilenet_v1_300_120e_voc --image_file=dataset_augment/JPEGImages/58.jpg  --use_gpu=True
但我想将在终端指定的文件添入源码中，而不是每次预测都在终端，我看在终端运行infer.py只需要指定模型包的位置、预测图片、是否使用GPU，后面俩好指定，就是指定模型包位置不知道怎么修改源码，尝试修改过ppdet.utils.cli下的ArgsParser，但不行，请问怎么修改啊

**Comment by ghostxsl** [comment]
啥意思？你想要干嘛？自己修改源码，不用命令行传参嘛？

**Comment by DLNovice** [comment]
> 

是的，不用命令行的形式预测，直接运行脚本进行预测

**Comment by DLNovice** [comment]
传参只需要指定模型包的位置、预测图片、是否使用GPU，后面俩好改，就是传模型包位置有点懵，我尝试我根据错误提示找到ppdet.utils.cli 中的ArgsParser，并尝试修改，报了些奇怪的错误

**Comment by ghostxsl** [comment]
那你直接在代码里修改你想要修改的变量就行了，不用管ArgsParser

**Comment by DLNovice** [comment]
> 那你直接在代码里修改你想要修改的变量就行了，不用管ArgsParser

非常抱歉，打扰您了，我应该用deploy/python下的infer.py而不是tools下的infer.py，我说怎么改那么麻烦，抱歉
