### ISSUE TITLE
在做MCFairMOT时用export_model.py导出的模型后，用post dynamic量化得出如下结果， 这个结果可以用于TensorRT的部署吗？

### ISSUE THREAD

**Issue by wenchima** [PaddlePaddle/PaddleDetection#5134]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## 描述问题/Describe the bug
在做MCFairMOT时用export_model.py导出的模型后，用post dynamic量化得出如下结果， 这个结果可以用于TensorRT的部署吗？

## 复现/Reproduction

1. 您使用的命令是？

paddleslim.quant.quant_post_dynamic

原始的用export_model.py导出的模型文件夹下包括如下文件/：

infer_cfg.yml  model.pdiparams  model.pdiparams.info  model.pdmodel

2. 生成的模型文件中包含如下信息：
batch_norm2d_0.b_0   batch_norm2d_17.w_1  batch_norm2d_26.b_0  batch_norm2d_34.w_1  batch_norm2d_42.b_0  batch_norm2d_4.w_1   batch_norm2d_8.b_0  conv2d_35.w_0  conv2d_53.b_0           deform_conv2d_0.w_0
batch_norm2d_0.w_0   batch_norm2d_17.w_2  batch_norm2d_26.w_0  batch_norm2d_34.w_2  batch_norm2d_42.w_0  batch_norm2d_4.w_2   batch_norm2d_8.w_0  conv2d_36.w_0  conv2d_53.w_0           deform_conv2d_10.b_0
batch_norm2d_0.w_1   batch_norm2d_18.b_0  batch_norm2d_26.w_1  batch_norm2d_35.b_0  batch_norm2d_42.w_1  batch_norm2d_50.b_0  batch_norm2d_8.w_1  conv2d_37.w_0  conv2d_54.b_0           deform_conv2d_10.w_0
batch_norm2d_0.w_2   batch_norm2d_18.w_0  batch_norm2d_26.w_2  batch_norm2d_35.w_0  batch_norm2d_42.w_2  batch_norm2d_50.w_0  batch_norm2d_8.w_2  conv2d_38.w_0  conv2d_54.w_0           deform_conv2d_11.b_0
batch_norm2d_10.b_0  batch_norm2d_18.w_1  batch_norm2d_27.b_0  batch_norm2d_35.w_1  batch_norm2d_43.b_0  batch_norm2d_50.w_1  batch_norm2d_9.b_0  conv2d_39.b_0  conv2d_55.b_0           deform_conv2d_11.w_0
batch_norm2d_10.w_0  batch_norm2d_18.w_2  batch_norm2d_27.w_0  batch_norm2d_35.w_2  batch_norm2d_43.w_0  batch_norm2d_50.w_2  batch_norm2d_9.w_0  conv2d_39.w_0  conv2d_55.w_0           deform_conv2d_12.b_0
batch_norm2d_10.w_1  batch_norm2d_19.b_0  batch_norm2d_27.w_1  batch_norm2d_36.b_0  batch_norm2d_43.w_1  batch_norm2d_51.b_0  batch_norm2d_9.w_1  conv2d_3.w_0   conv2d_56.b_0           deform_conv2d_12.w_0
batch_norm2d_10.w_2  batch_norm2d_19.w_0  batch_norm2d_27.w_2  batch_norm2d_36.w_0  batch_norm2d_43.w_2  batch_norm2d_51.w_0  batch_norm2d_9.w_2  conv2d_40.b_0  conv2d_56.w_0           deform_conv2d_13.b_0
batch_norm2d_11.b_0  batch_norm2d_19.w_1  batch_norm2d_28.b_0  batch_norm2d_36.w_1  batch_norm2d_44.b_0  batch_norm2d_51.w_1  conv2d_0.w_0        conv2d_40.w_0  conv2d_57.b_0           deform_conv2d_13.w_0
batch_norm2d_11.w_0  batch_norm2d_19.w_2  batch_norm2d_28.w_0  batch_norm2d_36.w_2  batch_norm2d_44.w_0  batch_norm2d_51.w_2  conv2d_10.w_0       conv2d_41.b_0  conv2d_57.w_0           deform_conv2d_14.b_0
batch_norm2d_11.w_1  batch_norm2d_1.b_0   batch_norm2d_28.w_1  batch_norm2d_37.b_0  batch_norm2d_44.w_1  batch_norm2d_52.b_0  conv2d_11.w_0       conv2d_41.w_0  conv2d_58.b_0           deform_conv2d_14.w_0
batch_norm2d_11.w_2  batch_norm2d_1.w_0   batch_norm2d_28.w_2  batch_norm2d_37.w_0  batch_norm2d_44.w_2  batch_norm2d_52.w_0  conv2d_12.w_0       conv2d_42.b_0  conv2d_58.w_0           deform_conv2d_15.b_0
batch_norm2d_12.b_0  batch_norm2d_1.w_1   batch_norm2d_29.b_0  batch_norm2d_37.w_1  batch_norm2d_45.b_0  batch_norm2d_52.w_1  conv2d_13.w_0       conv2d_42.w_0  conv2d_59.b_0           deform_conv2d_15.w_0
batch_norm2d_12.w_0  batch_norm2d_1.w_2   batch_norm2d_29.w_0  batch_norm2d_37.w_2  batch_norm2d_45.w_0  batch_norm2d_52.w_2  conv2d_14.w_0       conv2d_43.b_0  conv2d_59.w_0           deform_conv2d_1.b_0
batch_norm2d_12.w_1  batch_norm2d_21.b_0  batch_norm2d_29.w_1  batch_norm2d_38.b_0  batch_norm2d_45.w_1  batch_norm2d_53.b_0  conv2d_15.w_0       conv2d_43.w_0  conv2d_5.w_0            deform_conv2d_1.w_0
batch_norm2d_12.w_2  batch_norm2d_21.w_0  batch_norm2d_29.w_2  batch_norm2d_38.w_0  batch_norm2d_45.w_2  batch_norm2d_53.w_0  conv2d_16.w_0       conv2d_44.b_0  conv2d_60.b_0           deform_conv2d_2.b_0
batch_norm2d_13.b_0  batch_norm2d_21.w_1  batch_norm2d_2.b_0   batch_norm2d_38.w_1  batch_norm2d_46.b_0  batch_norm2d_53.w_1  conv2d_17.w_0       conv2d_44.w_0  conv2d_60.w_0           deform_conv2d_2.w_0
batch_norm2d_13.w_0  batch_norm2d_21.w_2  batch_norm2d_2.w_0   batch_norm2d_38.w_2  batch_norm2d_46.w_0  batch_norm2d_53.w_2  conv2d_18.w_0       conv2d_45.b_0  conv2d_61.b_0           deform_conv2d_3.b_0
batch_norm2d_13.w_1  batch_norm2d_22.b_0  batch_norm2d_2.w_1   batch_norm2d_39.b_0  batch_norm2d_46.w_1  batch_norm2d_54.b_0  conv2d_19.w_0       conv2d_45.w_0  conv2d_61.w_0           deform_conv2d_3.w_0
batch_norm2d_13.w_2  batch_norm2d_22.w_0  batch_norm2d_2.w_2   batch_norm2d_39.w_0  batch_norm2d_46.w_2  batch_norm2d_54.w_0  conv2d_1.w_0        conv2d_46.b_0  conv2d_62.b_0           deform_conv2d_4.b_0
batch_norm2d_14.b_0  batch_norm2d_22.w_1  batch_norm2d_30.b_0  batch_norm2d_39.w_1  batch_norm2d_47.b_0  batch_norm2d_54.w_1  conv2d_21.w_0       conv2d_46.w_0  conv2d_62.w_0           deform_conv2d_4.w_0
batch_norm2d_14.w_0  batch_norm2d_22.w_2  batch_norm2d_30.w_0  batch_norm2d_39.w_2  batch_norm2d_47.w_0  batch_norm2d_54.w_2  conv2d_22.w_0       conv2d_47.b_0  conv2d_6.w_0            deform_conv2d_5.b_0
batch_norm2d_14.w_1  batch_norm2d_23.b_0  batch_norm2d_30.w_1  batch_norm2d_3.b_0   batch_norm2d_47.w_1  batch_norm2d_5.b_0   conv2d_23.w_0       conv2d_47.w_0  conv2d_7.w_0            deform_conv2d_5.w_0
batch_norm2d_14.w_2  batch_norm2d_23.w_0  batch_norm2d_30.w_2  batch_norm2d_3.w_0   batch_norm2d_47.w_2  batch_norm2d_5.w_0   conv2d_24.w_0       conv2d_48.b_0  conv2d_8.w_0            deform_conv2d_6.b_0
batch_norm2d_15.b_0  batch_norm2d_23.w_1  batch_norm2d_31.b_0  batch_norm2d_3.w_1   batch_norm2d_48.b_0  batch_norm2d_5.w_1   conv2d_25.w_0       conv2d_48.w_0  conv2d_9.w_0            deform_conv2d_6.w_0
batch_norm2d_15.w_0  batch_norm2d_23.w_2  batch_norm2d_31.w_0  batch_norm2d_3.w_2   batch_norm2d_48.w_0  batch_norm2d_5.w_2   conv2d_26.w_0       conv2d_49.b_0  conv2d_transpose_0.w_0  deform_conv2d_7.b_0
batch_norm2d_15.w_1  batch_norm2d_24.b_0  batch_norm2d_31.w_1  batch_norm2d_40.b_0  batch_norm2d_48.w_1  batch_norm2d_6.b_0   conv2d_27.w_0       conv2d_49.w_0  conv2d_transpose_1.w_0  deform_conv2d_7.w_0
batch_norm2d_15.w_2  batch_norm2d_24.w_0  batch_norm2d_31.w_2  batch_norm2d_40.w_0  batch_norm2d_48.w_2  batch_norm2d_6.w_0   conv2d_28.w_0       conv2d_4.w_0   conv2d_transpose_2.w_0  deform_conv2d_8.b_0
batch_norm2d_16.b_0  batch_norm2d_24.w_1  batch_norm2d_33.b_0  batch_norm2d_40.w_1  batch_norm2d_49.b_0  batch_norm2d_6.w_1   conv2d_29.w_0       conv2d_50.b_0  conv2d_transpose_3.w_0  deform_conv2d_8.w_0
batch_norm2d_16.w_0  batch_norm2d_24.w_2  batch_norm2d_33.w_0  batch_norm2d_40.w_2  batch_norm2d_49.w_0  batch_norm2d_6.w_2   conv2d_2.w_0        conv2d_50.w_0  conv2d_transpose_4.w_0  deform_conv2d_9.b_0
batch_norm2d_16.w_1  batch_norm2d_25.b_0  batch_norm2d_33.w_1  batch_norm2d_41.b_0  batch_norm2d_49.w_1  batch_norm2d_7.b_0   conv2d_30.w_0       conv2d_51.b_0  conv2d_transpose_5.w_0  deform_conv2d_9.w_0
batch_norm2d_16.w_2  batch_norm2d_25.w_0  batch_norm2d_33.w_2  batch_norm2d_41.w_0  batch_norm2d_49.w_2  batch_norm2d_7.w_0   conv2d_31.w_0       conv2d_51.w_0  conv2d_transpose_6.w_0  __model__
batch_norm2d_17.b_0  batch_norm2d_25.w_1  batch_norm2d_34.b_0  batch_norm2d_41.w_1  batch_norm2d_4.b_0   batch_norm2d_7.w_1   conv2d_33.w_0       conv2d_52.b_0  conv2d_transpose_7.w_0
batch_norm2d_17.w_0  batch_norm2d_25.w_2  batch_norm2d_34.w_0  batch_norm2d_41.w_2  batch_norm2d_4.w_0   batch_norm2d_7.w_2   conv2d_34.w_0       conv2d_52.w_0  deform_conv2d_0.b_0

对于Nvidia-RT部署int8模型，上述导出后的模型（非常多的层文件）是用来进行Nvidia-RT 部署的模型文件吗？
按照这个https://github.com/PaddlePaddle/PaddleSlim/blob/develop/demo/quant/deploy/TensorRT/README.md 步骤， 待部署模型应该包含，inference/|-- model|-- params， 但是为什么我的int8 quantization导出模型有这么多的文件？

**Comment by nemonameless** [comment]
MCFairMOT等跟踪系列模型还没有做过量化，导出的模型目前只支持trt16或trt32预测。
