### ISSUE TITLE
loss中加入一个替换值的操作后，gpu需要内存暴增

### ISSUE THREAD

**Issue by mjanddy** [PaddlePaddle/PaddleDetection#5135]
![image](https://user-images.githubusercontent.com/27938658/150061360-3f4e4529-619d-4acd-92d6-dbc96210237d.png)
r如图所示，加入红框中的代码后，所需要gpu达到43G,没法训练了

**Comment by ghostxsl** [comment]
你不要用inplace的方式对节点进行赋值，建议使用op组合的方式实现你的想法

**Comment by mjanddy** [comment]
> 你不要用inplace的方式对节点进行赋值，建议使用op组合的方式实现你的想法

可以再详细说一下吗？具体要怎么写？

**Comment by ghostxsl** [comment]
我没看懂你是想要干嘛？先说一下你的想法，你想改成什么样子的？

**Comment by mjanddy** [comment]
> 我没看懂你是想要干嘛？先说一下你的想法，你想改成什么样子的？

target是label的值；fg_map是选择出来索引值；ious是pred计算的iou值; 想要实现的想法就是将target中属于fg_map位置的值替换为ious对应位置的值

**Comment by mjanddy** [comment]
> > 我没看懂你是想要干嘛？先说一下你的想法，你想改成什么样子的？
> 
> target是label的值；fg_map是选择出来索引值；ious是pred计算的iou值; 想要实现的想法就是将target中属于fg_map位置的值替换为ious对应位置的值



> 我没看懂你是想要干嘛？先说一下你的想法，你想改成什么样子的？

就是类似于numpy中数组的操作   a[b>1]=c[b>1]

**Comment by ghostxsl** [comment]
那建议您可以使用一下gather：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/gather_cn.html#gather 和 scatter：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/scatter_cn.html#scatter 来实现你的想法

**Comment by ghostxsl** [comment]
你确定你是只改了这一行才报错的嘛？我感觉你这个操作本身没问题

**Comment by mjanddy** [comment]
> 你确定你是只改了这一行才报错的嘛？我感觉你这个操作本身没问题

去掉了就不报错了

**Comment by mjanddy** [comment]
> 那建议您可以使用一下gather：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/gather_cn.html#gather 和 scatter：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/scatter_cn.html#scatter 来实现你的想法

好的，我去看一下，多谢
