### ISSUE TITLE
PaddleDetection是否支持多标签检测?

### ISSUE THREAD

**Issue by JiehangXie** [PaddlePaddle/PaddleDetection#5139]
## 🚀  新功能/Feature

PaddleDetection欢迎大家以清晰简洁的语言提出新功能需求。

A clear and concise description of the feature proposal.

## 需求原因&示例/Motivation & Examples

我目前有一个任务需求,除了检测出图片中的人之外,还要识别检测这个人的年龄/性别/是否戴眼镜等等属性
想问下PaddleDetection目前能支持多标签检测任务吗?或者能否提供其他的解决思路,谢谢了!
https://www.sohu.com/a/396686780_610522

**Comment by ghostxsl** [comment]
您好，可以支持多标签预测的，您可以修改head的分类为BCE就可以了，请问您使用的是哪个模型？

**Comment by JiehangXie** [comment]
> 您好，可以支持多标签预测的，您可以修改head的分类为BCE就可以了，请问您使用的是哪个模型？

PPYOLO

**Comment by ghostxsl** [comment]
> > 您好，可以支持多标签预测的，您可以修改head的分类为BCE就可以了，请问您使用的是哪个模型？
> 
> PPYOLO

可以的，你需要自己改写一下head和dataset的代码

**Comment by JiehangXie** [comment]
> > > 您好，可以支持多标签预测的，您可以修改head的分类为BCE就可以了，请问您使用的是哪个模型？
> > 
> > 
> > PPYOLO
> 
> 可以的，你需要自己改写一下head和dataset的代码

可以再问一下,BCE全称是什么吗?BCELoss?

**Comment by ghostxsl** [comment]
参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/binary_cross_entropy_cn.html#binary-cross-entropy
我看了ppyolo，本身就是用的BCE，可以进行多标签训练的，只是要改一下输入数据的格式

**Comment by JiehangXie** [comment]
谢谢,我尝试一下

**Comment by HaoLiuHust** [comment]
hello, 后来有实现吗？

**Comment by JiehangXie** [comment]
这是自动回复邮件。
 
您好，您的邮件已到达我的邮箱，我将尽快查阅并回复，谢谢。Hello, I have reveived your email. But due to the time differences and my busy work, perhaps I will reply to you in 24 to 48 hours.

**Comment by 2399240664** [comment]
这个输入数据的格式的意思是将Coco数据集修改？举个例子category_id改成数组的形式？


> 参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/binary_cross_entropy_cn.html#binary-cross-entropy 我看了ppyolo，本身就是用的BCE，可以进行多标签训练的，只是要改一下输入数据的格式

**Comment by JiehangXie** [comment]
这是自动回复邮件。
 
您好，您的邮件已到达我的邮箱，我将尽快查阅并回复，谢谢。Hello, I have reveived your email. But due to the time differences and my busy work, perhaps I will reply to you in 24 to 48 hours.
