### ISSUE TITLE
预测时使用的配置文件infer_cfg.yml没有生成

### ISSUE THREAD

**Issue by itslgl** [PaddlePaddle/PaddleDetection#514]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/inference/EXPORT_MODEL.md
根据这个文档，在导出模型的时候，会生成一个预测时使用的配置文件infer_cfg.yml。但是我在成功导出模型之后，没有找到这个配置文件。请帮忙看下，谢谢
我的项目地址是https://aistudio.baidu.com/aistudio/projectdetail/401863

**Comment by still-wait** [comment]
aistudio地址设置私密无法打开，我们刚在本地测试过，执行`tools/export_model.py`文件导出模型生成infer_cfg.yml是没有问题的，请拉下最新的PaddleDetection代码，再试下。

**Comment by itslgl** [comment]
我今天才更新的代码，用的最新的。下面是我导出模型的命令，的确没有生成infer_cfg.yml
python tools/export_model.py -c configs/yolov3_mobilenet_v1_chinamap.yml \
        --output_dir=./inference_model \
        -o weights=output/yolov3_mobilenet_v1_chinamap/ \

**Comment by still-wait** [comment]
@itslgl  请`git checkout master`切换至master开发分支重新运行下你的代码，注意你自己修改的代码也需copy至master分支。release/0.2分支export_model.py目前还不支持生成infer_cfg.yml，我们会尽快修复。

**Comment by itslgl** [comment]
切换到master分支以后，导出模型报错
---------------------------------------------------------
aistudio@jupyter-221076-401863:~/work/PaddleDetection$ python tools/export_model.py -c configs/yolov3_mobilenet_v1_chinamap.yml         --output_dir=./inference_model         -o weights=output/yolov3_mobilenet_v1_chinamap/         TestReader.im_size=[608,608] TestReader.inputs_def.image_shape=[3,608,608]
2020-04-16 14:18:52,763-INFO: Loading parameters from output/yolov3_mobilenet_v1_chinamap/...
2020-04-16 14:18:52,764-WARNING: output/yolov3_mobilenet_v1_chinamap/.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-04-16 14:18:52,764-WARNING: output/yolov3_mobilenet_v1_chinamap/.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/export_model.py", line 209, in <module>
    main()
  File "tools/export_model.py", line 194, in main
    checkpoint.load_params(exe, infer_prog, cfg.weights)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/checkpoint.py", line 125, in load_params
    state = _load_state(path)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/checkpoint.py", line 91, in _load_state
    state = fluid.io.load_program_state(path)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/io.py", line 1868, in load_program_state
    "Failed to load model file , please make sure model file is saved with the "
RuntimeError: Failed to load model file , please make sure model file is saved with the following APIs: save_params, save_persistables, save_vars
--------------------------------------------------

**Comment by jerrywgz** [comment]
export model时使用的weights路径应该是output/yolov3_mobilenet_v1_chinamap （结尾不加/）

**Comment by itslgl** [comment]
同样会报错
aistudio@jupyter-221076-401863:~/work/PaddleDetection$ python tools/export_model.py -c configs/yolov3_mobilenet_v1_chinamap.yml         --output_dir=./inference_model         -o weights=output/yolov3_mobilenet_v1_chinamap
2020-04-16 14:36:47,154-INFO: Loading parameters from output/yolov3_mobilenet_v1_chinamap...
2020-04-16 14:36:47,155-WARNING: output/yolov3_mobilenet_v1_chinamap.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-04-16 14:36:47,155-WARNING: output/yolov3_mobilenet_v1_chinamap.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/export_model.py", line 209, in <module>
    main()
  File "tools/export_model.py", line 194, in main
    checkpoint.load_params(exe, infer_prog, cfg.weights)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/checkpoint.py", line 125, in load_params
    state = _load_state(path)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/checkpoint.py", line 91, in _load_state
    state = fluid.io.load_program_state(path)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/io.py", line 1868, in load_program_state
    "Failed to load model file , please make sure model file is saved with the "
RuntimeError: Failed to load model file , please make sure model file is saved with the following APIs: save_params, save_persistables, save_vars
aistudio@jupyter-221076-401863:~/work/PaddleDetection$

**Comment by jerrywgz** [comment]
请问你使用的paddle版本是什么呢，检测库要求paddle版本在1.7以上

**Comment by itslgl** [comment]
1.7

`aistudio@jupyter-221076-401863:~/work/PaddleDetection$ python -c "import paddle; print(paddle.__version__)"
1.7.1
aistudio@jupyter-221076-401863:~/work/PaddleDetection$ `

**Comment by jerrywgz** [comment]
想问下你的模型保存成什么格式的呢，我们这边测试了几种情况都是可以正常加载的

**Comment by itslgl** [comment]
没有model_final这个目录，只有“model_final.pdmodel”，“model_final.pdopt”，“model_final.pdparams”这三个文件

`aistudio@jupyter-221076-401863:~/work/PaddleDetection$ ls output/yolov3_mobilenet_v1_chinamap
10000.pdmodel   1200.pdparams   14400.pdopt     16800.pdmodel   19000.pdparams  3400.pdopt     5800.pdmodel   8000.pdparams
10000.pdopt     12200.pdmodel   14400.pdparams  16800.pdopt     19200.pdmodel   3400.pdparams  5800.pdopt     800.pdmodel
10000.pdparams  12200.pdopt     14600.pdmodel   16800.pdparams  19200.pdopt     3600.pdmodel   5800.pdparams  800.pdopt
1000.pdmodel    12200.pdparams  14600.pdopt     17000.pdmodel   19200.pdparams  3600.pdopt     6000.pdmodel   800.pdparams
1000.pdopt      12400.pdmodel   14600.pdparams  17000.pdopt     19400.pdmodel   3600.pdparams  6000.pdopt     8200.pdmodel
1000.pdparams   12400.pdopt     14800.pdmodel   17000.pdparams  19400.pdopt     3800.pdmodel   6000.pdparams  8200.pdopt
10200.pdmodel   12400.pdparams  14800.pdopt     17200.pdmodel   19400.pdparams  3800.pdopt     600.pdmodel    8200.pdparams
10200.pdopt     12600.pdmodel   14800.pdparams  17200.pdopt     19600.pdmodel   3800.pdparams  600.pdopt      8400.pdmodel
10200.pdparams  12600.pdopt     15000.pdmodel   17200.pdparams  19600.pdopt     4000.pdmodel   600.pdparams   8400.pdopt
10400.pdmodel   12600.pdparams  15000.pdopt     17400.pdmodel   19600.pdparams  4000.pdopt     6200.pdmodel   8400.pdparams
10400.pdopt     12800.pdmodel   15000.pdparams  17400.pdopt     19800.pdmodel   4000.pdparams  6200.pdopt     8600.pdmodel
10400.pdparams  12800.pdopt     15200.pdmodel   17400.pdparams  19800.pdopt     400.pdmodel    6200.pdparams  8600.pdopt
10600.pdmodel   12800.pdparams  15200.pdopt     17600.pdmodel   19800.pdparams  400.pdopt      6400.pdmodel   8600.pdparams
10600.pdopt     13000.pdmodel   15200.pdparams  17600.pdopt     2000.pdmodel    400.pdparams   6400.pdopt     8800.pdmodel
10600.pdparams  13000.pdopt     15400.pdmodel   17600.pdparams  2000.pdopt      4200.pdmodel   6400.pdparams  8800.pdopt
10800.pdmodel   13000.pdparams  15400.pdopt     17800.pdmodel   2000.pdparams   4200.pdopt     6600.pdmodel   8800.pdparams
10800.pdopt     13200.pdmodel   15400.pdparams  17800.pdopt     200.pdmodel     4200.pdparams  6600.pdopt     9000.pdmodel
10800.pdparams  13200.pdopt     15600.pdmodel   17800.pdparams  200.pdopt       4400.pdmodel   6600.pdparams  9000.pdopt
11000.pdmodel   13200.pdparams  15600.pdopt     18000.pdmodel   200.pdparams    4400.pdopt     6800.pdmodel   9000.pdparams
11000.pdopt     13400.pdmodel   15600.pdparams  18000.pdopt     2200.pdmodel    4400.pdparams  6800.pdopt     9200.pdmodel
11000.pdparams  13400.pdopt     15800.pdmodel   18000.pdparams  2200.pdopt      4600.pdmodel   6800.pdparams  9200.pdopt
11200.pdmodel   13400.pdparams  15800.pdopt     1800.pdmodel    2200.pdparams   4600.pdopt     7000.pdmodel   9200.pdparams
11200.pdopt     13600.pdmodel   15800.pdparams  1800.pdopt      2400.pdmodel    4600.pdparams  7000.pdopt     9400.pdmodel
11200.pdparams  13600.pdopt     16000.pdmodel   1800.pdparams   2400.pdopt      4800.pdmodel   7000.pdparams  9400.pdopt
11400.pdmodel   13600.pdparams  16000.pdopt     18200.pdmodel   2400.pdparams   4800.pdopt     7200.pdmodel   9400.pdparams
11400.pdopt     13800.pdmodel   16000.pdparams  18200.pdopt     2600.pdmodel    4800.pdparams  7200.pdopt     9600.pdmodel
11400.pdparams  13800.pdopt     1600.pdmodel    18200.pdparams  2600.pdopt      5000.pdmodel   7200.pdparams  9600.pdopt
11600.pdmodel   13800.pdparams  1600.pdopt      18400.pdmodel   2600.pdparams   5000.pdopt     7400.pdmodel   9600.pdparams
11600.pdopt     14000.pdmodel   1600.pdparams   18400.pdopt     2800.pdmodel    5000.pdparams  7400.pdopt     9800.pdmodel
11600.pdparams  14000.pdopt     16200.pdmodel   18400.pdparams  2800.pdopt      5200.pdmodel   7400.pdparams  9800.pdopt
11800.pdmodel   14000.pdparams  16200.pdopt     18600.pdmodel   2800.pdparams   5200.pdopt     7600.pdmodel   9800.pdparams
11800.pdopt     1400.pdmodel    16200.pdparams  18600.pdopt     3000.pdmodel    5200.pdparams  7600.pdopt     best_model.pdmodel
11800.pdparams  1400.pdopt      16400.pdmodel   18600.pdparams  3000.pdopt      5400.pdmodel   7600.pdparams  best_model.pdopt
12000.pdmodel   1400.pdparams   16400.pdopt     18800.pdmodel   3000.pdparams   5400.pdopt     7800.pdmodel   best_model.pdparams
12000.pdopt     14200.pdmodel   16400.pdparams  18800.pdopt     3200.pdmodel    5400.pdparams  7800.pdopt     model_final.pdmodel
12000.pdparams  14200.pdopt     16600.pdmodel   18800.pdparams  3200.pdopt      5600.pdmodel   7800.pdparams  model_final.pdopt
1200.pdmodel    14200.pdparams  16600.pdopt     19000.pdmodel   3200.pdparams   5600.pdopt     8000.pdmodel   model_final.pdparams
1200.pdopt      14400.pdmodel   16600.pdparams  19000.pdopt     3400.pdmodel    5600.pdparams  8000.pdopt
aistudio@jupyter-221076-401863:~/work/PaddleDetection$ `

**Comment by jerrywgz** [comment]
python tools/export_model.py -c configs/yolov3_mobilenet_v1_chinamap.yml -o weights=weights=output/yolov3_mobilenet_v1_chinamap/model_final

**Comment by itslgl** [comment]
谢谢，这个问题解决了！
