### ISSUE TITLE
AP-FPS图相关问题

### ISSUE THREAD

**Issue by XuecWu** [PaddlePaddle/PaddleDetection#5143]
您好，我想询问下paper中的AP-FPS图是如何得出的呢？我不太清楚AP值与FPS值之间所存在的关系，谢谢。
![image](https://user-images.githubusercontent.com/75833531/150312126-894ae6c1-1fe7-461a-9956-cfc28fc6a70e.png)

**Comment by wangxinxin08** [comment]
测量一个模型的精度和速度即可，这里的图中是分别测试了PP-YOLO在608，512，416，320下的精度和速度得到的AP和FPS所画的图

**Comment by XuecWu** [comment]
好的知道啦谢谢您

**Comment by XuecWu** [comment]
> 测量一个模型的精度和速度即可，这里的图中是分别测试了PP-YOLO在608，512，416，320下的精度和速度得到的AP和FPS所画的图

老哥您好，我还有一个问题就是，对于PP-YOLO来说，团队所提供的权重在COCO2017上是训练了多少个epoch才得到的呢？谢谢您了哥

**Comment by XuecWu** [comment]
老哥还有一个问题就是，对于论文中的消融实验，是在COCO2017训练集上训练然后在COCO207-val进行评估所得出来的结果吧？

**Comment by wangxinxin08** [comment]
@XuecWu  
1. PP-YOLO 1x是在coco上训练405个epoch得到的，PP-YOLOv2是在coco上训练365个epoch得到的 
2. 论文的消融实验是在coco2017-val上评估得到的

**Comment by XuecWu** [comment]
好的谢谢老哥

**Comment by XuecWu** [comment]
@wangxinxin08  哥我看paper里面，咱们起初lr设定为0.01，这样做不会出现nan嘛，我在COCO2017上训练YOLOv4起初lr设定为0.001还会爆nan害

**Comment by wangxinxin08** [comment]
这个学习率是8卡下设置的，对应的batch_size=8(卡数) * 12，如果你是单卡batch_size=12的话，你需要将学习率设置成原来的1/8

**Comment by XuecWu** [comment]
@wangxinxin08 好类好类哥，我可算明白了

**Comment by XuecWu** [comment]
@wangxinxin08  老哥您好，请问paper中在COCO2017上训练PP-YOLO所用的总时间大概是多久呢，一个epoch的时间又是多久呢？谢谢老哥
