### ISSUE TITLE
[BUG]ppyolov2训练时损失变为nan，并且评估一直卡死在iter0不动

### ISSUE THREAD

**Issue by curryJ** [PaddlePaddle/PaddleDetection#5149]
![image](https://user-images.githubusercontent.com/23001027/150517896-e55df081-64b3-44d0-81c3-3a6c8051518a.png)
我在AI studio上也遇到了这个问题，然后我在自己的2080ti上搭配好了环境之后继续进行训练，也出现了同样的问题。
我使用的config为ppyolov2_r50vd_dcn_365e_bdd100k.yml，仅仅在ppyolov2_r50vd_dcn_365e_coco.yml上进行了修改，数据集为bdd100k，读取数据也正常。但是就是无法评估，单独进行eval也是有同样的问题。
非常感谢

**Comment by nemonameless** [comment]
建议加载coco预训练模型去训，snapshot_epoch设置大一点。
如果从imagenet预训练去训，刚开始阶段eval精度极低，低质量框处理会很耗时。

**Comment by curryJ** [comment]
请问有没有类似于pytorch中model=model.cuda()这个函数呢，我打印了输出，发现是place=CPUPlace，因此我想把模型放在gpu上，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月21日(星期五) 晚上8:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] [BUG]ppyolov2训练时损失变为nan，并且评估一直卡死在iter0不动 (Issue #5149)





 
建议加载coco预训练模型去训，snapshot_epoch设置大一点。
 如果从imagenet预训练去训，刚开始阶段eval精度极低，低质量框处理会很耗时。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nemonameless** [comment]
请先检查下自己安装的paddle是否GPU版本，以及运行时是否GPU运行。没有cuda()函数，但只要是GPU上运行的打印自然是GPU的。
```
import paddle
paddle.device.cuda.device_count()
```
文档在[官网](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/index_cn.html)，可自行搜索其他想要的功能api。

**Comment by curryJ** [comment]
> 请先检查下自己安装的paddle是否GPU版本，以及运行时是否GPU运行。没有cuda()函数，但只要是GPU上运行的打印自然是GPU的。
> 
> ```
> import paddle
> paddle.device.cuda.device_count()
> ```
> 
> 文档在[官网](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/index_cn.html)，可自行搜索其他想要的功能api。

我查看了其他的issue发现是学习率太高导致的损失值变为nan，然后我降低了学习率，训练正常进行，损失也一直在降低。但是现在我运行infer.py发现一个问题，会出现我数据中没有的标签，如下图所示：
![image](https://user-images.githubusercontent.com/23001027/150636376-6ab9bda8-a67a-484e-8d70-59ea73f90b0d.png)
我使用的是bdd100k数据集，只有10个class，如下，
![image](https://user-images.githubusercontent.com/23001027/150636397-e74580af-a84a-4787-ae4c-f860708fcb74.png)
![image](https://user-images.githubusercontent.com/23001027/150636500-077f72e7-6d09-4e90-b674-21b38311b0cd.png)

我想请问这是不是导入的pretrain_weights有问题呀，但是这个导入的难道不是backbone的权重吗，很是不理解，谢谢啦
![image](https://user-images.githubusercontent.com/23001027/150636609-bb42d006-3a9f-406a-a60d-e2eaf17d346f.png)

**Comment by heavengate** [comment]
自定义数据集的话，`TestDataset.anno_path`需要配置到你自定义数据集的annotation文件，类别默认会读这个，这个路径不存在的话回去读COCO默认的类别

**Comment by curryJ** [comment]
我已经在bdd100k_detection.yml文件中改了

请问这个必须是绝对路径吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月22日(星期六) 晚上8:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] [BUG]ppyolov2训练时损失变为nan，并且评估一直卡死在iter0不动 (Issue #5149)





 
自定义数据集的话，TestDataset.anno_path需要配置到你自定义数据集的annotation文件，类别默认会读这个，这个路径不存在的话回去读COCO默认的类别
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nemonameless** [comment]
> 我已经在bdd100k_detection.yml文件中改了 请问这个必须是绝对路径吗

都可以。设置绝对路径更保险点。

**Comment by John-chen521** [comment]
怎么解决的
