### ISSUE TITLE
print_flops失败[Other General Issues]

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#5150]
![image](https://user-images.githubusercontent.com/78856426/150630247-4a699343-4bce-46c5-80fe-2c2204a5cb34.png)

我在训练的时候想看一下flops当我把print_flops设置为True时结果让我安装paddleslim，但是我已经安装了

**Comment by yghstill** [comment]
@violetweir 通过`import paddleslim` 确认下是否安装成功。
