### ISSUE TITLE
使用opt进行模型转换时出现文件读取报错

### ISSUE THREAD

**Issue by LuoyesK** [PaddlePaddle/PaddleDetection#5151]
执行命令：paddle_lite_opt --model_file=model.pdmodel --param_file=model.pdiparams --valid_targets=arm --optimize_out=result
报错：Loading topology data from model.pdmodel
Loading params data from model.pdiparams
[F  1/22 18:52:22.297 ...d/Paddle-Lite/lite/core/model/base/io.cc:54 Read] Check failed: (fread(dst, 1, size, file_) == size): 0!==9437184 Failed to read 9437184 bytes.

**Comment by LuoyesK** [comment]
补充：训练50轮，报错，但训练300轮后又能通过

**Comment by nemonameless** [comment]
使用的是静态图？
可以在 [Paddle-Lite](https://github.com/PaddlePaddle/Paddle-Lite/issues)提issue
