### ISSUE TITLE
 请问有人用自定义的数据集训练过PPYOLOV2的模型吗，我colab跑了半个小时都没有出第一个epcho的结果，是我参数设置的问题吗？我的参数设置是10 epcho,batchsize=12 学习率是0.00125[Other General Issues]

### ISSUE THREAD

**Issue by kkhuangzekai** [PaddlePaddle/PaddleDetection#5153]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

请问有人用自定义的数据集训练过PPYOLOV2的模型吗，我colab跑了半个小时都没有出第一个epcho的结果，是我参数设置的问题吗？我的参数设置是10 epcho,batchsize=12 学习率是0.00125
![ca0ac3e4fcf1ed6cab9a09ce9c3592d](https://user-images.githubusercontent.com/82854498/150666894-6c6512b7-aeed-4385-aad7-efe56399f641.png)

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) /I have read the [FAQ documentation](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) but cannot get the expected help.

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
!export CUDA_VISIBLE_DEVICES=0
!python "/content/drive/My Drive/PaddleDetection/tools/train.py" -c "/content/drive/My Drive/PaddleDetection/configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml" --eval
```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by curryJ** [comment]
我也想问这个问题，我在bdd100k上根本就跑不出来，而且每次评估的时候都会卡死，显示Eval iter: 0然后一直不动。我看issue上面说降低学习率可以解决这个问题，所以我降低了学习率，后来确实能跑，但是mAP一直是0.
我后来为了验证是否是数据集的问题，又下载了benchmark中的coco_benchmark，然后训练没有问题，到了评估这里又是一模一样的问题。最后我选择了ppyolo的其他模型，也是这个问题。难受住了

**Comment by kkhuangzekai** [comment]
> 我也想问这个问题，上面显示的bdd100k上根本就跑不出来，而且每次我评估的时候都会固定死卡，然后Eval it: 0一直显示。我看问题说学习率可以降低这个问题，所以我提高了学习率，后来一样能跑，但是mAP一直是0。 我后来为了验证是否是数据集的问题，又下载了基准中的coco_benchmark，然后训练问题没有问题，到了评估这里又是一模。最后我选择了ppyolo的其他住模型，也是这个问题。难受了

兄弟你试过哪个数据集和预训练模型跑train.py是成功的吗？

**Comment by kkhuangzekai** [comment]
兄弟你试过哪个数据集和预训练模型跑train.py是成功的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月23日(星期天) 晚上7:46
***@***.***&gt;;
抄送:&nbsp;"life is ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection]  请问有人用自定义的数据集训练过PPYOLOV2的模型吗，我colab跑了半个小时都没有出第一个epcho的结果，是我参数设置的问题吗？我的参数设置是10 epcho,batchsize=12 学习率是0.00125[Other General Issues] (Issue #5153)





 
我也想问这个问题，我在bdd100k上根本就跑不出来，而且每次评估的时候都会卡死，显示Eval iter: 0然后一直不动。我看issue上面说降低学习率可以解决这个问题，所以我降低了学习率，后来确实能跑，但是mAP一直是0.
 我后来为了验证是否是数据集的问题，又下载了benchmark中的coco_benchmark，然后训练没有问题，到了评估这里又是一模一样的问题。最后我选择了ppyolo的其他模型，也是这个问题。难受住了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by curryJ** [comment]
我刚开始使用的是bdd100k，没有成功，现在使用的是benchmark中自带的coco_benchmark数据集，也没有成功。我现在想去试一试coco数据集



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月23日(星期天) 晚上7:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection]  请问有人用自定义的数据集训练过PPYOLOV2的模型吗，我colab跑了半个小时都没有出第一个epcho的结果，是我参数设置的问题吗？我的参数设置是10 epcho,batchsize=12 学习率是0.00125[Other General Issues] (Issue #5153)





  
我也想问这个问题，上面显示的bdd100k上根本就跑不出来，而且每次我评估的时候都会固定死卡，然后Eval it: 0一直显示。我看问题说学习率可以降低这个问题，所以我提高了学习率，后来一样能跑，但是mAP一直是0。 我后来为了验证是否是数据集的问题，又下载了基准中的coco_benchmark，然后训练问题没有问题，到了评估这里又是一模。最后我选择了ppyolo的其他住模型，也是这个问题。难受了
  
兄弟你试过哪个数据集和预训练模型跑train.py是成功的吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kkhuangzekai** [comment]
> 我刚开始使用的是bdd10k，没有成功，现在使用的是benchmark中自带的coco_benchmark数据集，也没有成功。我现在想去试一试coco数据集
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年1月23日(星期天) 晚上7:58 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [PaddlePaddle/PaddleDetection] 请问有人用自定义的数据集训练过PPYOLOV2的模型吗，我colab跑了半个小时都没有出第一个epcho的结果，是我参数设置的问题吗？我的参数设置是10 epcho,batchsize=12 学习率是0.00125[Other General Issues] (Issue #5153) 我也想问这个问题，上面显示的bdd100k上根本就跑不出来，而且每次我评估的时候都会固定死卡，然后Eval it: 0一直显示。我看问题说学习率可以降低这个问题，所以我提高了学习率，后来一样能跑，但是mAP一直是0。 我后来为了验证是否是数据集的问题，又下载了基准中的coco_benchmark，然后训练问题没有问题，到了评估这里又是一模。最后我选择了ppyolo的其他住模型，也是这个问题。难受了 兄弟你试过哪个数据集和预训练模型跑train.py是成功的吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

我用的是VOC格式的  PPYOLOV2的训练文档我看了看  大多数是VOC的   你也可以考虑试试VOC

**Comment by curryJ** [comment]
好的好的 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月23日(星期天) 晚上8:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection]  请问有人用自定义的数据集训练过PPYOLOV2的模型吗，我colab跑了半个小时都没有出第一个epcho的结果，是我参数设置的问题吗？我的参数设置是10 epcho,batchsize=12 学习率是0.00125[Other General Issues] (Issue #5153)





  
我刚开始使用的是bdd10k，没有成功，现在使用的是benchmark中自带的coco_benchmark数据集，也没有成功。我现在想去试一试coco数据集
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年1月23日(星期天) 晚上7:58 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PaddlePaddle/PaddleDetection] 请问有人用自定义的数据集训练过PPYOLOV2的模型吗，我colab跑了半个小时都没有出第一个epcho的结果，是我参数设置的问题吗？我的参数设置是10 epcho,batchsize=12 学习率是0.00125[Other General Issues] (Issue #5153) 我也想问这个问题，上面显示的bdd100k上根本就跑不出来，而且每次我评估的时候都会固定死卡，然后Eval it: 0一直显示。我看问题说学习率可以降低这个问题，所以我提高了学习率，后来一样能跑，但是mAP一直是0。 我后来为了验证是否是数据集的问题，又下载了基准中的coco_benchmark，然后训练问题没有问题，到了评估这里又是一模。最后我选择了ppyolo的其他住模型，也是这个问题。难受了 兄弟你试过哪个数据集和预训练模型跑train.py是成功的吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: @.***&gt;
  
我用的是VOC格式的  PPYOLOV2的训练文档我看了看  大多数是VOC的   你也可以考虑试试VOC
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nemonameless** [comment]
ppyolo系列模型如果是imagenet pretrain的，刚开始阶段eval会耗时在低质量的框上，建议多训几个epoch再eval。
训其他数据集时，请先自查coco或voc格式转的对不对，为了加速收敛，可以加载coco训好的模型权重去fintune，这样第一个epoch应该也可以很快出较高精度的结果。
