### ISSUE TITLE
请问人脸检测支持,多张图片为一个batch,进行一次性前向推理么?

### ISSUE THREAD

**Issue by yangjian1218** [PaddlePaddle/PaddleDetection#5156]
应用场景,针对百万级数据进行制作数据库,如果一张一张推理太慢了,人脸检测是否支持多张图片同时推理?

**Comment by wangxinxin08** [comment]
可以组成batch去预测，但是所有图片需要resize或者到同一尺寸https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/yolov3/_base_/yolov3_reader.yml#L29, 或者resize到不同尺寸，Pad到统一尺寸:https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/faster_rcnn/_base_/faster_reader.yml#L18
