### ISSUE TITLE
YOLOV3解码函数

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleDetection#5161]
YOLOV3输出的解码函数为yolo_box，在ppdet/modeling/ops内，请问源码在哪里可以看到？

**Comment by lyuwenyu** [comment]
代码 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/yolo_box_op.h
文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/ops/yolo_box_cn.html#yolo-box

**Comment by Monday-Leo** [comment]
感谢！还有一个问题，YOLOV3的FPN和head，ppdet的代码将最后head部分的3×3卷积放在了FPN部分，head部分只是一个1×1的卷积，图中已经框出。虽然执行下来没有错误，但是想问一下这个3*3的卷积到底是归属于FPN还是head?
![3](https://user-images.githubusercontent.com/53975909/151101249-96eadd19-bd55-4293-851c-1fffb0c3ece3.jpg)

**Comment by nemonameless** [comment]
属于FPN
