### ISSUE TITLE
[operate < elementwise_mul > error ] 

### ISSUE THREAD

**Issue by chenjw1009** [PaddlePaddle/PaddleDetection#5165]
DOTA 数据集，S2A_alignconv_2x_dota.yml 评估时，把配置项batch_size 设置为8，出现这样的错误[operate < elementwise_mul > error ]

**Comment by chenjw1009** [comment]
batch_size=1 没问题，但速度特别慢。

**Comment by wangxinxin08** [comment]
你好，感谢你的反馈，目前s2anet的训练和评估确实不支持bs>1，我们将会排期支持这一特性，另外，dota数据集评估可以参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/dota#5-dota%E6%95%B0%E6%8D%AE%E8%AF%84%E4%BC%B0 因为没有标注数据，所以暂时需要保存数据到DOTA官网进行评估
