### ISSUE TITLE
显存溢出

### ISSUE THREAD

**Issue by chenjw1009** [PaddlePaddle/PaddleDetection#5166]
用DOTA 数据集，cascade_mask-rcnn, 训练时，显存24G，batch-size=1, 显存都溢出，这是咋回事呢？

**Comment by nemonameless** [comment]
DOTA训cascade mask rcnn是把旋转框的点当成mask去训？cascade mask是大模型，建议先检查配置文件和数据集，要训的话可以开--fp16训、换小backbone、换小尺度等

**Comment by qingqing01** [comment]
您有更改什么吗？
