### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by HaiLongEmb** [PaddlePaddle/PaddleDetection#517]
你好，我使用的paddle版本是1.7版本，环境是Windows，使用的0.2版本的PaddleDetection，想使用pyinstaller将cpp_infer.py打包成exe，发现打包完以后运行发现卡在import paddle.fluid as fluid，系统中的cpp_infer进程不断在增加，请问这是什么情况，目前paddle无法使用pyinstaller打包吗？应该注意什么。

**Comment by sjtubinlong** [comment]
@HaiLongEmb 

试试在 `if __name__=='__main__:' `

下添加一句 `multiprocessing.freeze_support()` 。

**Comment by HaiLongEmb** [comment]
@sjtubinlong 还是不行
![image](https://user-images.githubusercontent.com/32731062/79426420-b9d9df80-7ff5-11ea-930f-fd75e314abd0.png)
![image](https://user-images.githubusercontent.com/32731062/79426481-cbbb8280-7ff5-11ea-9e33-e2fa2640523c.png)

![image](https://user-images.githubusercontent.com/32731062/79426304-9151e580-7ff5-11ea-8249-22c3a9b75439.png)
还是遇到import paddle.fluid as fluid就执行不下去了 ，我打包的命令是pyinstaller cpp_infer.py

**Comment by qingqing01** [comment]
@HaiLongEmb 由于时间较久，关闭了此issue，还问题，还可以开新的issue。
