### ISSUE TITLE
[BUG]跑tinypose demo 同一张图片裁剪后得到的结果不一样

### ISSUE THREAD

**Issue by tomjeans** [PaddlePaddle/PaddleDetection#5173]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.
3. 确认bug是否在新版本里还未修复/The bug has not been fixed in the latest version.

## 描述问题/Describe the bug
同一张图片原图和裁剪后的图关键点出现漂移缩放现象

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by tomjeans** [comment]
![keypoint_footballrect](https://user-images.githubusercontent.com/37204571/151766745-abf9aac7-aeba-4276-9d07-4010cc86c7f8.jpg)尺寸 1280*853

![keypoint_footballafterrect_origin](https://user-images.githubusercontent.com/37204571/151766947-db5cf12c-ae67-4309-8fca-e1d6c6f3e842.jpg) 尺寸 406*803

**Comment by tomjeans** [comment]
![lei_black_middele](https://user-images.githubusercontent.com/37204571/152962136-419c3400-78ad-4733-ae7c-6a0a42eb5145.jpg)
padding 成4:3的比例结果才正常 是仿射变换那部分的问题吗

**Comment by zoooo0820** [comment]
请问具体执行模型的命令是什么呢，在第二张图上未能复现问题

**Comment by tomjeans** [comment]
> 请问具体执行模型的命令是什么呢，在第二张图上未能复现问题

执行的是./main keypoint_runtime_config.json   小米11 手机上adb 运行的
![152962136-419c3400-78ad-4733-ae7c-6a0a42eb5145](https://user-images.githubusercontent.com/37204571/153116206-05eef952-0876-4405-b4b1-956605a65ab9.jpg)
这种比例的图片会出现偏移

**Comment by zoooo0820** [comment]
@tomjeans 问题已经复现，我们先排查一下

**Comment by tomjeans** [comment]
void get_affine_transform(std::vector<float>& center,
                          std::vector<float>& scale,
                          float rot,
                          std::vector<int>& output_size,
                          cv::Mat& trans,
                          int inv) {
  float src_w = scale[0];
  float dst_w = static_cast<float>(output_size[0]);
  float dst_h = static_cast<float>(output_size[1]);
  float rot_rad = rot * PI / HALF_CIRCLE_DEGREE;
  std::vector<float> src_dir = get_dir(-0.5 * src_w, 0, rot_rad);
  std::vector<float> dst_dir{static_cast<float>(-0.5) * dst_w, 0.0};
  cv::Point2f srcPoint2f[3], dstPoint2f[3];
  srcPoint2f[0] = cv::Point2f(center[0], center[1]);
  srcPoint2f[1] = cv::Point2f(center[0] + src_dir[0], center[1] + src_dir[1]);
  srcPoint2f[2] = get_3rd_point(srcPoint2f[0], srcPoint2f[1]);

  dstPoint2f[0] = cv::Point2f(dst_w * 0.5, dst_h * 0.5);
  dstPoint2f[1] =
      cv::Point2f(dst_w * 0.5 + dst_dir[0], dst_h * 0.5 + dst_dir[1]);
  dstPoint2f[2] = get_3rd_point(dstPoint2f[0], dstPoint2f[1]);
  if (inv == 0) {
    trans = cv::getAffineTransform(srcPoint2f, dstPoint2f);
  } else {
    trans = cv::getAffineTransform(dstPoint2f, srcPoint2f);
  }
}
应该是这段代码 srcPoint2f[2] = get_3rd_point(srcPoint2f[0], srcPoint2f[1]); 有问题
尝试修改 srcPoint2f[2] = cv::Point2f(center[0],center[1]+0.5*scale[1]);
