### ISSUE TITLE
yolov3如何进行数据增强？

### ISSUE THREAD

**Issue by huangjianyi45903** [PaddlePaddle/PaddleDetection#5174]
小白请假个问题，就是如何通过sample_transforms下的 RandomFlip进行数据增强？数据增强的详细流程如何进行呢？

**Comment by jerrywgz** [comment]
sample_transforms是每个iter，选中的样本都会随机进行数据增广，例如随机反转，会生成一个随机数，如果随机数大于0.5，就对反转样本，反之则不反转。经过增广之后的样本再组合成batch进行训练。

**Comment by huangjianyi45903** [comment]
> sample_transforms是每个iter，选中的样本都会随机进行数据增广，例如随机反转，会生成一个随机数，如果随机数大于0.5，就对反转样本，反之则不反转。经过增广之后的样本再组合成batch进行训练。

   那这个参数RandomFlip: {}要如何配置呢？因为我的infer推理的输出结果会将原始图片进行旋转，然后得到一些错误的预测框，我猜想是由于模型训练中缺少随机翻转，因此想加入这么一个算子，不知道怎么在配置文件进行配置...

**Comment by jerrywgz** [comment]
infer阶段是不会引入RandomFlip这个算子的，如果是训练阶段希望加入，可以参考这里的配置https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/yolov3/_base_/yolov3_reader.yml#L11

**Comment by lvjianjin001** [comment]
> 
同问，我也是在infer的过程中出现了原始图片会产生旋转的问题，这是什么原因呢？
