### ISSUE TITLE
Solov2 inference

### ISSUE THREAD

**Issue by Amrou7** [PaddlePaddle/PaddleDetection#5175]
I want to use instance segmentation using solov2. The Script I wrote for this task is as follows:

> from infer import PredictConfig, DetectorSOLOv2
> import cv2
> import time
> 
> model_dir = './inference_models/inference_r101/solov2_r101_vd_fpn_3x_coco'
> image_path = 'path to the inference image'
> pred_config = PredictConfig(model_dir)
> device = 'GPU'
> detector = DetectorSOLOv2(pred_config, model_dir, device=device, run_mode='TensorRT', batch_size=1, trt_min_shape=1, 
                      trt_max_shape=1280, trt_opt_shape=640, trt_calib_mode=False, cpu_threads=1, enable_mkldnn=True)
> 
> img = cv2.imread(image_path)
> results = detector.predict([img], threshold=0.6)
> print(results)

This works well, but it's slow ( 1.7s). Since I want to construct a real-time instance segmentation application, this isn't suitable for me.
How can I use solov2 in order to make a real-time application? Is there another way to make inference on a given ndarray image?

The inference image size is (1980,1080,3). The GPU I use is NVIDIA GeForce RTX 3060.

**Comment by yghstill** [comment]
@Amrou7 
- `run_mode` can be set to `paddle/trt_fp32/trt_fp16/trt_int8`. If you want to use TensorRT, please set run_mode='trt_fp32' or 'trt_fp16'.
- The inference image size is so large, the data preprocessing time will increase, you can reduce the real image size and test it again.
- The solov2_r101_vd  parameters is large, and smaller models can be used, such as `solo2_r50_enhance`.

**Comment by Amrou7** [comment]
Hello @yghstill. Thank you for your response.
I tried to use trt_fp32/trt_fp16/trt_int8, but the inference time is the same.
Also, I already tried to decrease the image shape to (200,200) and used smaller model before posting the issue, but the inference time didn't decrease.
I noticed that the cause of this high inference time are the following lines in the **class DetectorSOLOv2**, in the function **predict()** of the file **deploy/python/infer.py**:
```
for i in range(len(input_names)):
            input_tensor = self.predictor.get_input_handle(input_names[i])
            input_tensor.copy_from_cpu(inputs[input_names[i]])
self.predictor.run()
```
when `input_names[i] == 'im_shape'`,  it takes a long time to execute (600 ms), also `self.predictor.run()` takes alone more than 900 ms.
How can I solve that?

**Comment by yghstill** [comment]
@Amrou7 
- The first execution of predictor takes some time to initialize, and it should be run several times to average.
