### ISSUE TITLE
tinypose 是否可以run在mali  G52  gpu上，PP目前是否已经支持

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleDetection#5178]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

    tinypose 是否可以run在mali c52 gpu上，PP目前是否已经支持
我只看到arm cpu上运行的tinypose文档说明，但没有看到gpu版本的
，如果有的话是否可以提供下链接， tks

**Comment by zhiboniu** [comment]
mali G系列的处理器没有做过尝试，可以看看paddle LIte相关资料看看是否支持。https://paddlelite.paddlepaddle.org.cn/
另外，tinypose也支持第三方部署方式mnn等，可以如果mnn支持也可以用第三方部署工具尝试一下。

**Comment by 2050airobert** [comment]
那我们现在主要支持的mali gpu型号系列主要是哪些？ 尤其是tinypose现在在哪种mali gpu上跑通过？tks

**Comment by 2050airobert** [comment]
1 我看了下mali g52 gpu支持的opencl 2.0以及以上的版本（比如 amlogic rockchip ），不知道paddlelite支持吗？ 
2 目前paddle lite 主要支持的是mali 400 450还是mali T系列 比如T 880 之类的呢？ 有木有示例 链接呢？
3 有tinypose在哪款gpu或者平台上跑通的case吗

**Comment by 2050airobert** [comment]
hello  any idea?
