### ISSUE TITLE
yolo训练时间随gpu数目增加而增加

### ISSUE THREAD

**Issue by barry2025** [PaddlePaddle/PaddleDetection#518]
环境：
docker: paddlepaddle/paddle:1.7.1-gpu-cuda9.0-cudnn7
paddledetection: release0.2
模型：yolov3_r50vd_dcn.yml，yolov3_r34_voc.yml
显卡：P4， V100

固定config中的batch_size，采用2卡训练：
![image](https://user-images.githubusercontent.com/20043808/79421621-c8bc9400-7fed-11ea-9801-3fcf1932ee84.png)
采用单卡训练：
![image](https://user-images.githubusercontent.com/20043808/79421640-d6721980-7fed-11ea-9d8a-b3c1f3040fb2.png)

每张卡的batch_size是一样的，但是每次的迭代时间随着卡数增加而增加了，请问这里是有什么配置或者环境没设置好吗

**Comment by still-wait** [comment]
@barry2025 您好，单卡训练确实要比多卡训练快，由于config中的batch_size设置是指每张卡上的，所以多卡训练时，总体batch_size翻倍，数据预处理本身比较耗时，导致训练时间变慢，看您截图，两卡训练耗时程线性增长，如果想多卡训练时提高速度，可增大yolov3_reader.yml中的`worker_num`与`bufsize`.

**Comment by barry2025** [comment]
我这边在V100-32G显卡上1卡-2卡-4卡，不改work和bufsize时，基本都是线性情况，改了之后确实改善了，印象中之前用paddle0.1好像没有出现这种情况，请问是0.2做了啥改变么，worker和bufsize和总batch之间的关系的通常值除了自己实验外有没有啥先验值，例如，请问下官方用yolov3_r50vd_dcn跑obj365 8卡的时候是咋设置的worker和bufeize？

**Comment by heavengate** [comment]
```
  batch_size: 8                                                                                                                                                    
  shuffle: true                                                                                                                                                    
  mixup_epoch: 250                                                                                                                                                 
  drop_last: true                                                                                                                                                  
  worker_num: 16                                                                                                                                                   
  bufsize: 16                                                                                                                                                      
  use_process: true 
```

**Comment by xyxwinner** [comment]
我也遇到一样的问题了 版本是  ppdet版本2.5 paddle-gpu=2.2.2 cuda11.2 cudnn 8.1.1  3080TI的卡 训练ppyoloe_crn_l_300e ，单卡ips能到30image/s 上多了多卡 单卡只有7-8的image/s 修改了work_num 和 和bufsize 无效果。 2张显卡的负载确认都跑起来了，cpu和内存也都够用。但是速度确实是线性下降
