### ISSUE TITLE
[BUG] tinypose on android phone : no person or box detected on the demo jpg

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleDetection#5181]
用arm cpu跑tinypose demo，picodet model采用320*320分辨率，tinypose model采用官网文档128 96和 256 192 两种分辨率分别尝试，手机上运行 ./main det_runtime_config.json ，demo.jpg采用官方包里面的640x404的行人jpg图片，log 信息如下：
注意 ./demo.jpg The number of detected box: 0  ， 这明显不对啊，因为图片里面是有许多行人的，而且应该是官方demo自带的图片，麻烦帮忙看下log，哪里有问题？多谢

详细log如下： 
warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
      version of opt:00e38a8
      version of current Paddle-Lite:v2.10-rc
create object detector
./demo.jpg The number of detected box: 0
Visualized output saved as result_demo.jpg
----------------------- Config info -----------------------
num_threads: 4
----------------------- Data info -----------------------
batch_size_det: 1
----------------------- Model info -----------------------
detection model_name: ./model_det/
----------------------- Perf info ------------------------
Total number of predicted data: 1 and total time spent(ms): 130.756

**Comment by 2050airobert** [comment]
附加个问题： warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
这个 picodet和tinypose 模型我用的是官方的 nb文件直接下载的，这里的warning 应该不影响检测结果吧？

**Comment by 2050airobert** [comment]
just following the web ：  https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/lite

下面的hrnet没有找到，我用tinypose模型替代了，不知道是否可以？
# 如果需要关键点模型，则只需操作：
cp {PadddleDetection_Root}/output_inference/hrnet_w32_256x192/model.nb ./model_keypoint/
cp {PadddleDetection_Root}/output_inference/hrnet_w32_256x192/infer_cfg.json ./model_keypoint/

官方的结果如下:
![image](https://user-images.githubusercontent.com/8407513/153155612-18382b46-4ca1-4748-a063-dd4e6cb6dbfc.png)
但是我并没有找到 该图显示的model info 里面的ppyolo_tiny.nb 在哪，必须用这个模型才可以检测出行人吗？

**Comment by 2050airobert** [comment]
还有个问题，请问下num_threads 设置为1 ， 2 ，3，4 程序运行结果尤其是时间耗时基本都没什么变化，这个正常吗？
是不是目前的模型和demo并不支持多线程加速呢？

**Comment by zoooo0820** [comment]
@2050airobert 
运行关键点模型的话，应该使用keypoint_runtime_config.json。不过检测框为0的问题比较奇怪，需要再排查一下。

另外整体回复下其他问题：
1. 关于lite与opt版本warning。可能出现影响预测结果的情况，最好统一转换模型opt和Lite版本；
2. 可以用tinypose替代，只要保证模型路径与输入大小配置等正确；
3. 理论上num_threads影响还比较明显，可以参考下[关键点benchmark](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/keypoint/KeypointBenchmark.md)。另外在测速时最好在配置文件中打开run_benchmark选项。

**Comment by 2050airobert** [comment]
hi，
     我之前的图用的是640 404 那张官方实验用的图片，人比较多，一个人也没检测出来。但是我换了一张只有一个人的图片，可以检测出1个人来，然后我又截取了640 404这张图包括三个人的区域，然后也能检测出来，但是只检测出一个人就是最左边那个。用det_runtime_xxxx 和keypoint_runtime_config.json 的检测box结果数量都是一样的。 我理解keypoint_runtime_config跑的是带关键点检测的det   detection结果，而det_runtime 跑的是不带key point检测的结果，本质上这两个json程序都要有pico net Detection的部分，是这样的吗？
     1、这只是个warning，而且opt版本只会影响性能吧？结果不一定有偏差，对吗？  如果在ubuntu PPlite环境下查看当前版本是哪个呢(比如git 分支), 有木有某个命令可以直接查看当前版本的opt和基础版本version？ 
     2、嗯，目前就是采用tinypose 配置
     3、这部分很奇怪，num_threads 设置不同的值确实没有任何变化，检测box数量和耗时 打印时间都几乎没变化。我后面打开了run_benchmark选项，结果也是没变化。  对于 arm core配置 a53X2 + a73X4 (比如 amlogic rockchip)有实测过吗？
      Best Regards

**Comment by zoooo0820** [comment]
@2050airobert 
验证了下模型和demo图片的结果，这边暂时未能复现问题。

> keypoint_runtime_config跑的是带关键点检测的det detection结果，而det_runtime 跑的是不带key point检测的结果

这个是理解是对的。另外辛苦您检查一下存放检测模型picodet的路径（包括Infer_cfg.json及.nb文件)，其中json文件的内容是否与[模型](https://bj.bcebos.com/v1/paddledet/models/keypoint/picodet_s_320_pedestrian.tar)链接中的.yml对应的json内容一致？

另外关于耗时问题我们只实测过上述benmark页面中给出的设备。

**Comment by 2050airobert** [comment]
tks，
     1、  num_threads 的设置不一定在其他平台上也适用吧？ 这个取决于main 主程序里 对于相应cpu的多线程功能启动的配置是否生效吧？ 我看了下，程序运行的时候确实只有1个core在使用，这说明num_threads没有生效，根本原因需要修改main主程序对吧？也就是 src 文件夹里的main.cc等文件，对吗？ any idea？ tks
     2、 这个tinypose有 single 版本和mutiple版本的模型，也就是说single 的模型只能检测一个人，而mutiple的才有可能都检测出来，是这样的吗？

**Comment by zoooo0820** [comment]
@2050airobert 
1. num_threads的启动设置在https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/lite/src/keypoint_detector.cc#L25 ，如果在您的设备上还是无法生效，方便的话可以在Paddle-Lite repo下询问下支持情况。
2. 本质上tinypose因为采用了Top-Down处理多人问题，随着人数增多整体耗时也会增长。考虑到精度与速度的折中，single/multi是我们对不同场景下推荐的一种模型组合选择，并非single就无法处理多人场景。您也可以根据实际设备上速度/效果表现自行选择模型的组合。

**Comment by LMR2018** [comment]
@2050airobert   兄弟，你的问题解决了吗？安卓项目能正常跑了吗？能发一份你的安卓项目给我参考下吗？
