### ISSUE TITLE
could not find the detailed examples of the  cnn model running case on mali gpu ？

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleDetection#5188]
关于mail gpu的case，有木有更详细点的文档和示例提供下？ 相比cpu 和 arm，maili gpu的相关例子很单薄，是否可以提供下，更方便复现和调试。 tks

备注： 我只看到了如下关于gpu的文档，opencl 版本
 https://paddle-lite.readthedocs.io/zh/release-v2.10_a/demo_guides/opencl.html

**Comment by 2050airobert** [comment]
有木有我们目前支持的gpu 类型的列表总结啊？
就像下面这样
![企业微信截图_16444909334230](https://user-images.githubusercontent.com/8407513/153393949-e98a0631-d628-4208-945b-6e117ddc7bbb.png)

**Comment by nemonameless** [comment]
same issue #5196

**Comment by lyuwenyu** [comment]
请在这提问 https://github.com/PaddlePaddle/Paddle-Lite/issues
