### ISSUE TITLE
yml文档详解

### ISSUE THREAD

**Issue by d2623587501** [PaddlePaddle/PaddleDetection#5189]
## 📖  文档优化/Documentation Improvement
您好，请问yml中的预训练权重是怎么得到的呢，例如以下的pretrain_weights
`architecture: FairMOT
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/HRNet_W18_C_pretrained.pdparams
for_mot: True`
咱们这边是否有详细的yml文档（解读每个关键词的内容及可修改方式），谢谢

**Comment by nemonameless** [comment]
预训练权重是PaddleClas提供的，是在imagenet上用paddle框架训练过的。
yml文档参照https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/docs/tutorials/config_annotation
FairMOT等跟踪模型的配置文件基本类似所以没有单独写。

**Comment by d2623587501** [comment]
感谢大佬的回复，请问这些有预训练权重的模型都有哪些呢，有这方面的文档嘛

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/algorithm_introduction/ImageNet_models.md

**Comment by d2623587501** [comment]
谢谢大佬
