### ISSUE TITLE
请教一下关键点检测标注问题

### ISSUE THREAD

**Issue by liyuyuan6969** [PaddlePaddle/PaddleDetection#5191]
## questions:

1.请问视频里说的会出的关键点标注工具已经出了吗？

2.我现在想训练一批关键点数据，我是标了检测模型的框之后，只标17个点就可以了吗？但是我看coco的数据集中有x,y坐标之后，还有一个v值，v = 0表示未标记，v = 1表示标记但不可见，v = 2表示标记且可见，请问这个v值需要标吗？如果要标的话用labelme要怎么标才方便呢？

3.请问视频中说的除了人类别之外还可以同时标其他的类别，那模型训练的时候是先训练好人类别的关键点模型之后再在此模型的基础上训练其他类别的数据吗？还是说可以一起训练呢？需要注意些什么？

4.请问这个关键点检测的健身app demo中，c++部分的推理调用是线程安全的嘛？我看里面的推理函数调用是放在opengl的reder函数中的，据说render是多线程渲染的，那这个是不是就是多线程调用推理函数？这样写能表明c++的推理是支持线程安全，可以多线程调用呢？因为在c++代码里面也没有看到有使用多线程来进行推理

5.现在在机器上的推理耗时是100多ms，是不是意味着1s钟只能渲染10帧左右呢？怎么能够提高并发呢？如果20ms opengl的render函数触发一次模型推理的话，上一次推理还没有完成的话，是会等待上一次推理完成后才进行本次推理吗？

在论坛上也提了同样的问题：https://aistudio.baidu.com/paddle/forum/topic/show/993514

感谢回答哈~！！蟹蟹

**Comment by jerrywgz** [comment]
1. 关键点的标注工具预计会在3月底release出来～
2. 如果用labelme做数据标注的话，可见度的标注会比较麻烦，建议v=1，v=2的点都标出来，v=0的不标，不单独标注可见度；目前ppdet中实际训练出来的模型也是这样处理的
3. 如果是其他类别的关键点，建议单独再训练一个模型，不和人体关键点模型共享

**Comment by liyuyuan6969** [comment]
> 1. 关键点的标注工具预计会在3月底release出来～
> 2. 如果用labelme做数据标注的话，可见度的标注会比较麻烦，建议v=1，v=2的点都标出来，v=0的不标，不单独标注可见度；目前ppdet中实际训练出来的模型也是这样处理的
> 3. 如果是其他类别的关键点，建议单独再训练一个模型，不和人体关键点模型共享

谢谢大佬，还有些疑问：
1. 这里不单独标注可见度不是很理解，是说只要是没遮挡都标出来，遮挡了的不标，v的值可以不用管吗？还是说比如我标记的时候需要区分为 左肩_标记但不可见 左肩_标记可见这两类，然后转化为coco标记的时候分别将v设置为1和2呢？
2. 还有就是不是很懂这里的未标记和标记但不可见，不可见不是就不用标不就是未标记了吗？为什么会分标记但不可见呢？
3. 如果其他类别的话，单独训练一个模型为了不增加耗时是不是要使用多线程或者其他方法呢？有可以不增加耗时的方法推荐吗？
4. 还有就是还有两个问题没有回，是需要单独提一个issues吗？

**Comment by zhiboniu** [comment]
4. c++部分基于Paddle LIte推理引擎，咨询了他们也没有做过线程安全的测试，但是paddle lite本身就是多线程跑的。而且本身速度瓶颈受限于手机处理器，同时启动多个可能并不能加速。
5. 是的，帧数约等于1s/infertime。推荐使用gpu部署速度会非常快。这个推理顺序问题并不清楚，可以到PaddleLite repo下去问问。

**Comment by zhiboniu** [comment]
未标记和标记但不可见的区别在于，
标记但不可见：关键点局部小区域被遮挡，但是可以判断出关键点所在位置。
未标记：一般情况下是大面积被遮挡以至于不能判断关键点位置。

所以这里的不区分是否遮挡是说 标记但不可见 的类型与正常可见类型同等处理。

另外增加一个模型一般情况下会导致耗时增加，如果计算资源没跑慢可以尝试同步处理，可能不需要增加耗时。

**Comment by liyuyuan6969** [comment]
> 1. 关键点的标注工具预计会在3月底release出来～
> 2. 如果用labelme做数据标注的话，可见度的标注会比较麻烦，建议v=1，v=2的点都标出来，v=0的不标，不单独标注可见度；目前ppdet中实际训练出来的模型也是这样处理的
> 3. 如果是其他类别的关键点，建议单独再训练一个模型，不和人体关键点模型共享



> 4. c++部分基于Paddle LIte推理引擎，咨询了他们也没有做过线程安全的测试，但是paddle lite本身就是多线程跑的。而且本身速度瓶颈受限于手机处理器，同时启动多个可能并不能加速。
> 5. 是的，帧数约等于1s/infertime。推荐使用gpu部署速度会非常快。这个推理顺序问题并不清楚，可以到PaddleLite repo下去问问。

好的，谢谢大佬！！

**Comment by liyuyuan6969** [comment]
> 未标记和标记但不可见的区别在于， 标记但不可见：关键点局部小区域被遮挡，但是可以判断出关键点所在位置。 未标记：一般情况下是大面积被遮挡以至于不能判断关键点位置。
> 
> 所以这里的不区分是否遮挡是说 标记但不可见 的类型与正常可见类型同等处理。
> 
> 另外增加一个模型一般情况下会导致耗时增加，如果计算资源没跑慢可以尝试同步处理，可能不需要增加耗时。

感谢感谢！！

**Comment by LMR2018** [comment]
@liyuyuan6969   兄弟，你自己用labelme标注的数据跑通了吗？你是怎么标注的，能不能发个标注结果给我看看？训练配置你是怎样配的？

**Comment by LUOrenjia** [comment]
> 1. 关键点的标注工具预计会在3月底release出来～
> 2. 如果用labelme做数据标注的话，可见度的标注会比较麻烦，建议v=1，v=2的点都标出来，v=0的不标，不单独标注可见度；目前ppdet中实际训练出来的模型也是这样处理的
> 3. 如果是其他类别的关键点，建议单独再训练一个模型，不和人体关键点模型共享

大佬你好！三月底的release中没有看到关键点标注工具，请问后面有计划推出关键点标注工具吗？

**Comment by zhouweic36** [comment]
请问，这个标记工具在哪里？

**Comment by jieduba1** [comment]
请问你是怎么把labelme标注的关键点数据集转成Tiny-Pose模型可以训练的coco数据集的呢？

**Comment by shanchao0906** [comment]
同问，是哪个标注工具？

**Comment by Bradly-s** [comment]
请问有新出的标注工具？还是用labelme？
