### ISSUE TITLE
关于使用paddleX训练得到模型后如何使用的问题。

### ISSUE THREAD

**Issue by wyyzxml2120** [PaddlePaddle/PaddleDetection#5193]
求大佬看看，我已经在aistudio提了一下了 链接如下 ：[点我](https://aistudio.baidu.com/paddle/forum/topic/show/993425)

https://aistudio.baidu.com/paddle/forum/topic/show/993425

**Comment by lyuwenyu** [comment]
你好请在这个地方提问 https://github.com/PaddlePaddle/PaddleX/issues
