### ISSUE TITLE
could not find the detailed examples of the cnn model running case on mali gpu 

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleDetection#5196]
1，关于mail gpu的case，有木有更详细点的文档和示例提供下？ 相比cpu 和 arm，maili gpu的相关例子很单薄，是否可以提供下，更方便复现和调试。 tks
备注： 我只看到了如下关于gpu的文档，opencl 版本
https://paddle-lite.readthedocs.io/zh/release-v2.10_a/demo_guides/opencl.html
2，有木有我们目前支持的gpu 类型的列表总结啊？
就像下面这样
![企业微信截图_16444909334230](https://user-images.githubusercontent.com/8407513/153394251-a371823b-73e4-4e03-ae08-1bf5e38d1225.png)

**Comment by lyuwenyu** [comment]
请在这提问 https://github.com/PaddlePaddle/Paddle-Lite/issues
