### ISSUE TITLE
使用Yolov3配置文件在本机训练路灯数据报错TypeError: __init__() got an unexpected keyword argument 'use_default_label‘

### ISSUE THREAD

**Issue by tobyxiong** [PaddlePaddle/PaddleDetection#5199]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.
3. 确认bug是否在新版本里还未修复/The bug has not been fixed in the latest version.

## 描述问题/Describe the bug
依据教程（https://aistudio.baidu.com/aistudio/projectdetail/929173）步骤在本机运行YOLOV3，出现报错TypeError: __init__() got an unexpected keyword argument 'use_default_label‘。

运行前验证安装已经通过，log如下：
(base) toby-xiong@DESKTOP-KD3REM5:~/PaddleDetection$ python ppdet/modeling/tests/test_architectures.py
/home/toby-xiong/anaconda3/lib/python3.9/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0211 11:03:52.598008    69 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.5, Runtime API Version: 11.2
W0211 11:03:52.609663    69 device_context.cc:465] device: 0, cuDNN Version: 8.1.
/home/toby-xiong/anaconda3/lib/python3.9/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
.......
----------------------------------------------------------------------
Ran 7 tests in 3.109s

OK
## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
python -u tools/train.py -c configs/hw_configs/yolov3_mobilenet_v1_roadsign_voc_template.yml -o use_gpu=True --eval

2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
配置文件没有更改，数据集直接从本案列中下载到本地，并放置于/dataset目录下。

3. 您使用的数据集是？/What dataset did you use?
roadsign_voc 
4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
报错log如下：
(base) toby-xiong@DESKTOP-KD3REM5:~/PaddleDetection$ python -u tools/train.py -c configs/hw_configs/yolov3_mobilenet_v1_roadsign_voc_template.yml -o use_gpu=True --eval
/home/toby-xiong/anaconda3/lib/python3.9/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Error when construct VOCDataSet instance from yaml config
Traceback (most recent call last):
  File "/home/toby-xiong/PaddleDetection/tools/train.py", line 171, in <module>
    main()
  File "/home/toby-xiong/PaddleDetection/tools/train.py", line 132, in main
    cfg = load_config(FLAGS.config)
  File "/home/toby-xiong/PaddleDetection/ppdet/core/workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "/home/toby-xiong/PaddleDetection/ppdet/core/workspace.py", line 79, in _load_config_with_base
    file_cfg = yaml.load(f, Loader=yaml.Loader)
  File "/home/toby-xiong/anaconda3/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/toby-xiong/anaconda3/lib/python3.9/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/home/toby-xiong/anaconda3/lib/python3.9/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/home/toby-xiong/anaconda3/lib/python3.9/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/toby-xiong/anaconda3/lib/python3.9/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/toby-xiong/anaconda3/lib/python3.9/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/toby-xiong/anaconda3/lib/python3.9/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/home/toby-xiong/PaddleDetection/ppdet/core/config/yaml_helpers.py", line 45, in python_constructor
    raise ex
  File "/home/toby-xiong/PaddleDetection/ppdet/core/config/yaml_helpers.py", line 41, in python_constructor
    return cls(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_default_label'
## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
Paddle版本2.2.1

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：
没有使用其他产品
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
WSL Ubuntu1804
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
Python3.9.7
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
cuda11.2, cuDNN8.1

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by nemonameless** [comment]
配置文件也发下方便查bug。
这个教程很老了不建议使用，还是静态图的时候。目前github上根目录的代码默认是动态图版本，以前的静态图代码在PaddleDetection/static目录里
目前可以参照此文档训练 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/QUICK_STARTED_cn.md

**Comment by tobyxiong** [comment]
感谢！已经试过其他configs下的配置文件了，可以运行。
