### ISSUE TITLE
请问cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms支持c++推理吗？求教yaml如何编写

### ISSUE THREAD

**Issue by opencvfun** [PaddlePaddle/PaddleDetection#52]
我是使用./configs/oidv5/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.yml生成的model和param文件

**Comment by qingqing01** [comment]
可以参考  https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/inference/conf/detection_rcnn_fpn.yaml

**Comment by opencvfun** [comment]
![4368E23E-7B48-4c93-B5FF-A5AF6673993D](https://user-images.githubusercontent.com/16854424/69924409-36a46b00-14e6-11ea-84a6-af4b99a28339.png)
![4FAAC4EB-DC52-4c45-86FB-F4D2DAC7BCB1](https://user-images.githubusercontent.com/16854424/69924411-373d0180-14e6-11ea-9a63-d4a9691420c4.png)
![897C6AA5-7BDF-4f69-B006-76D8D1A32953](https://user-images.githubusercontent.com/16854424/69924412-373d0180-14e6-11ea-8643-75b92a94a836.png)

**Comment by qingqing01** [comment]
@opencvfun 建议不要截图，直接贴错误信息，图片我这里无法正确显示。

**Comment by sjtubinlong** [comment]
@opencvfun  能否提供一下完整的运行命令，还有OPENCV, PADDLE预测库，是否使用GPU（CUDA和CUDNN版本）等信息

感谢。

**Comment by opencvfun** [comment]
@sjtubinlong 
sorry，最近已经放弃这个框架了，坐等官方更新完善后再用。

**Comment by qingqing01** [comment]
@opencvfun 我们欢迎多提意见，会持续改进  :)
