### ISSUE TITLE
检测结果可视化脚本运行报错

### ISSUE THREAD

**Issue by itslgl** [PaddlePaddle/PaddleDetection#520]
请帮忙看下这个报错，paddle version：1.7.1，master分支和0.2分支都有同样问题
参考文档：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/inference/DEPLOYMENT.md

`
root@eric-VirtualBox:/home/eric/project/PaddleDetection/inference/build# python ../tools/vis.py --img_path=jpeg/chinamap_a236.jpg --img_result_path=jpeg/chinamap_a236.jpg.pb --threshold=0.1 --c2l_path=../tools/chinamap.json
Traceback (most recent call last):
  File "../tools/vis.py", line 83, in <module>
    with open(Flags.c2l_path, "r", encoding="utf-8") as json_f:
TypeError: 'encoding' is an invalid keyword argument for this function
root@eric-VirtualBox:/home/eric/project/PaddleDetection/inference/build#
`

**Comment by still-wait** [comment]
@itslgl 请将`vis.py`的第83行改为：
```python
import io
with io.open(Flags.c2l_path, "r", encoding="utf-8") as json_f:
...
```
如果此方法有效，请反馈一下，open方法与io.open不一样，如果io.open有效，我们会改进一下此代码。

**Comment by itslgl** [comment]
这样改可以，谢谢！
