### ISSUE TITLE
我训练自己的数据集，检测不出对象？

### ISSUE THREAD

**Issue by beixixingdeshangkong** [PaddlePaddle/PaddleDetection#5200]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) /I have read the [FAQ documentation](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) but cannot get the expected help.

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
 python tools/train.py -c  configs/yolov3/yolov3_mobilenet_v1_270e_coco.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar
 python tools/eval.py -c configs/yolov3/yolov3_mobilenet_v1_270e_coco.yml  -o weights=tools/output/yolov3_mobilenet_v1_270e_coco/49

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?
自己数据集，制作成了coco，用来检测A4纸上的发票，拍照出来的发票，扫描出来的发票，类别只有1个，训练样本170，验证样本42。
![loss_wh](https://user-images.githubusercontent.com/93569845/153564026-2c15d3bc-9314-43fd-a7f4-c27a2e69ff62.png)
![loss_obj](https://user-images.githubusercontent.com/93569845/153564269-b32e9262-f780-4515-983c-84c47a90199f.png)
![loss_cls](https://user-images.githubusercontent.com/93569845/153564447-d820fd71-32db-43cf-9fc8-d678c0844bb2.png)
![loss](https://user-images.githubusercontent.com/93569845/153564462-36a16a3e-58ea-47c8-8948-58e9573852c9.png)

![loss_xy](https://user-images.githubusercontent.com/93569845/153563919-f6373bab-61e9-432e-8f66-998cc0b18eca.png)

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
[02/11 16:33:52] ppdet.utils.checkpoint INFO: Finish loading model weights: tools/output/yolov3_mobilenet_v1_270e_coco/49.pdparams
[02/11 16:33:53] ppdet.engine INFO: Eval iter: 0
[02/11 16:34:23] ppdet.metrics.metrics INFO: The bbox result is saved to bbox.json.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[02/11 16:34:23] ppdet.metrics.coco_utils INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.04s).
Accumulating evaluation results...
DONE (t=0.01s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.255
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.731
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.113
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.255
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.249
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.398
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.398
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.398
[02/11 16:34:23] ppdet.engine INFO: Total sample number: 42, averge FPS: 1.3889123881811545

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
2.2.2

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
Windows
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
3.7
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
cpu训练的

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by nemonameless** [comment]
infer命令是```python tools/infer.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml -o use_gpu=true --infer_img=demo/road554.png```，是这句命令得到的可视化图片是没有框吗？
能eval出mAP说明至少训的还可以，数据集太小了，可以参照 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/yolov3/yolov3_mobilenet_v1_roadsign.yml 加载coco预训练去训

**Comment by beixixingdeshangkong** [comment]
> infer命令是`python tools/infer.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml -o use_gpu=true --infer_img=demo/road554.png`，是这句命令得到的可视化图片是没有框吗？ 能eval出mAP说明至少训的还可以，数据集太小了，可以参照 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/yolov3/yolov3_mobilenet_v1_roadsign.yml 加载coco预训练去训

你好，我加载了coco预训练去训，训练数据集有500张，100个epoch，其他指标都收敛了，但是loss_xy反复在跳，
![image](https://user-images.githubusercontent.com/93569845/154415639-4b11d989-a7e6-4614-ae5a-f3aac1e258bc.png)
还没有收敛，我测试一张图片，可以标出来，但位置标的不准确，测试命令是 python tools/infer.py -c configs/yolov3/yolov3_mobilenet_v1_270e_coco.yml --infer_img=demo/vat_4.jpg -o weights=tools/output/yolov3_mobilenet_v1_270e_coco/model_final --save_txt=true，请问该怎么解决呢？

**Comment by dongyangli-del** [comment]
数据集太少了吧,500张还训100e,肯定过你和
