### ISSUE TITLE
paddle2.2.2现在支持RTX3060了吗

### ISSUE THREAD

**Issue by cena001plus** [PaddlePaddle/PaddleDetection#5206]
你好，在安装paddle遇到问题，在gpu是2080的机子上安装cuda10.2，按指导安装paddle是可以运行的，但是
在另一台gpu为3060的机子上安装cuda10.2，安装paddle后执行下面的命令出错。

`Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0214 14:20:51.479054 24961 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 10.2
W0214 14:20:51.479620 24961 device_context.cc:465] device: 0, cuDNN Version: 8.3.
`

`RuntimeError: parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device
`

**Comment by tuteming** [comment]
3060 ->cuda 11.1
