### ISSUE TITLE
[Feature Request] 打印建议

### ISSUE THREAD

**Issue by xmy0916** [PaddlePaddle/PaddleDetection#5209]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/engine/trainer.py#L520

墙裂建议这一行用tqdm包装一下或者加log打印，predict的文件如果比较多会在这个for循环卡很久...终端一点输出都没有还以为是代码bug...不太友好

**Comment by heavengate** [comment]
好的，感谢反馈，我们加一下~
