### ISSUE TITLE
picodet如何量化或者剪枝

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#5213]
请问各位大佬，picodet如何对模型量化或者剪枝，picodet可以蒸馏训练吗

**Comment by yghstill** [comment]
@Dandelion111 
- 量化可以参考文档：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet#quantization
- 非结构化剪枝可以参考文档：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/picodet#unstructured-pruning
- 目前还不支持蒸馏训练
