### ISSUE TITLE
PP-Tinypose关键点标注卡证目标

### ISSUE THREAD

**Issue by xiangfeidecao** [PaddlePaddle/PaddleDetection#5217]
请问下，我的卡证目标虽然是同一类，但是由于正反面都有，而且可能有第一代第二代多版本。这类目标如何用labelme标注？请看下我的流程：1.bbox时候就分成第一代正面，第二代正面，第一代反面，第二代反面，2.然后每一类再按照固定起点顺时针标4个关键点。还是说第一步时直接正面，反面两类。

**Comment by heavengate** [comment]
关键点现在没有多目标类别的配置，是单一类别(比如人)上检测多个关键点，如果卡证的关键点位置相近，建议当成一种类别来看，如果要区分正反面一二代的话可能需要检测之后把bbox扣出来再过关键点检测

**Comment by xiangfeidecao** [comment]
> 关键点现在没有多目标类别的配置，是单一类别(比如人)上检测多个关键点，如果卡证的关键点位置相近，建议当成一种类别来看，如果要区分正反面一二代的话可能需要检测之后把bbox扣出来再过关键点检测

谢谢，我现在是用正面的一代二代放在一起训练，不区分一代二代。反面是单独的。
