### ISSUE TITLE
picodet 由paddle2onnx导出失败

### ISSUE THREAD

**Issue by ChaoII** [PaddlePaddle/PaddleDetection#5225]
## 描述问题/Describe the bug
`picodet` 由`paddle2onnx`导出失败，模型主干网络：PPLCNet 和ESNet 都试过不行
## 失败原因
```bash
NotImplementedError:
There's 7 ops are not supported yet
=========== lod_array_length ===========
=========== while ===========
=========== meshgrid ===========
=========== select_input ===========
=========== conditional_block ===========
=========== write_to_array ===========
=========== tensor_array_to_tensor ===========
```
## tips:
我看到PicoDet文档中有已经转好的`onnx`中间格式文件，这个请问这个`onnx`是由`paddlepaddle` 实现导出的么？如果是，请问，我应该如何处理？需要修改模型结构么？

**Comment by jerrywgz** [comment]
可以确认下onnx和paddleonnx版本，我这边使用onnx-1.10.1 和paddle2onnx 0.9.0，使用命令`paddle2onnx --model_dir=output_inference/picodet_s_320_coco/ --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file picodet_s_320_coco.onnx` 可以正常导出

**Comment by ChaoII** [comment]
> 
非常感谢，我这边已经转onnx成功了，前面失败是因为picodet是用paddlex训练然后导出为pdmodel 和 pdiparams，后面得知里面有部分后处理（分支）的逻辑，所以导致导出失败，用paddleDetection就没这个问题额。

**Comment by jerrywgz** [comment]
好的，那关闭issue了哈，有其他问题可以再提issue沟通
