### ISSUE TITLE
[Feature Request]检测结果输出视频流到前端

### ISSUE THREAD

**Issue by boris-lb** [PaddlePaddle/PaddleDetection#5226]
## 🚀  新功能/Feature

检测模型部署到服务器，但是需要将检测结果视频推流输出到前端显示，有没有好的解决方法进行长时间推流？

**Comment by jerrywgz** [comment]
目前PaddleDetection还没有视频推流的相关内容，可以参考下https://github.com/ZLMediaKit/ZLMediaKit 这个repo看能不能帮到您，后续我们会跟进在线视频流的部分
