### ISSUE TITLE
Error in export_model.py for solov2_r50_fpn_1x_coco.pdparams

### ISSUE THREAD

**Issue by RivkinMikhail** [PaddlePaddle/PaddleDetection#5227]
Hello everyone and thank you for this great repo!

I'm trying to run the inference for the solov2_r50_fpn_1x_coco.pdparams model. Firstly, I'm doing the export call:
`python3 tools/export_model.py -c configs/solov2/solov2_r50_fpn_1x_coco.yml --output_dir=inference_model -o weights=solov2_r50_fpn_1x_coco.pdparams
`
And I receive the next error:

Traceback (most recent call last):
  File "tools/export_model.py", line 115, in <module>
    main()
  File "tools/export_model.py", line 111, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 74, in run
    trainer.load_weights(cfg.weights)
  File "/PaddleDetection/ppdet/engine/trainer.py", line 316, in load_weights
    load_pretrain_weight(self.model, weights)
  File "/PaddleDetection/ppdet/utils/checkpoint.py", line 193, in load_pretrain_weight
    param_state_dict = paddle.load(weights_path)
  File "/venvs/paddle/lib/python3.8/site-packages/paddle/framework/io.py", line 935, in load
    load_result = pickle.load(f, encoding='latin1', errors='ignore')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 3128409: invalid start byte

I've tried changing the encoding in pickle.load() but nothing changes. 

However, for the solov2_r50_enhance_coco.pdparams everything worked fine. 

I'm using Python 3.8 with the CPU only computer. 

Here is my dependency list if it is necessary:

astor               0.8.1    
attrs               21.4.0   
certifi             2021.10.8
charset-normalizer  2.0.12   
cycler              0.11.0   
Cython              0.29.27  
cython-bbox         0.1.3    
decorator           5.1.1    
et-xmlfile          1.1.0    
flake8              4.0.1    
flake8-import-order 0.18.1   
fonttools           4.29.1   
idna                3.3      
iniconfig           1.1.1    
joblib              1.1.0    
kiwisolver          1.3.2    
lap                 0.4.0    
matplotlib          3.5.1    
mccabe              0.6.1    
motmetrics          1.2.0    
numpy               1.22.2   
opencv-python       4.5.5.62 
openpyxl            3.0.9    
packaging           21.3     
paddledet           2.3.0    
paddlepaddle        2.2.2    
pandas              1.4.1    
Pillow              9.0.1    
pip                 20.0.2   
pkg-resources       0.0.0    
pluggy              1.0.0    
protobuf            3.19.4   
py                  1.11.0   
py-cpuinfo          8.0.0    
pycocotools         2.0.4    
pycodestyle         2.8.0    
pyflakes            2.4.0    
pyparsing           3.0.7    
pytest              7.0.1    
pytest-benchmark    3.4.1    
python-dateutil     2.8.2    
pytz                2021.3   
PyYAML              6.0      
requests            2.27.1   
scikit-learn        1.0.2    
scipy               1.8.0    
setuptools          44.0.0   
Shapely             1.8.1    
shellcheck-py       0.8.0.4  
six                 1.16.0   
sklearn             0.0      
terminaltables      3.1.10   
threadpoolctl       3.1.0    
tomli               2.0.1    
tqdm                4.62.3   
typeguard           2.13.3   
urllib3             1.26.8   
wheel               0.37.1   
xmltodict           0.12.0

**Comment by jerrywgz** [comment]
It seems like incomplete weight file. You could try the weight released here https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/solov2#model-zoo at first.

**Comment by RivkinMikhail** [comment]
Hello, @jerrywgz 

I've loaded these two models from this exact page and the error raised from the solov2_r50_fpn_1x_coco.pdparams one. Anyways, I'll try to download it again and get back to you. Maybe the problem was that I was downloading this model through wget, not the browser.

**Comment by RivkinMikhail** [comment]
The problem was in downloading the weight file through wget, so the right way to do it is using the browser. Thank you and I'm closing the issue.
