### ISSUE TITLE
关于RCNN数据集 数据类别问题[Other General Issues]

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#5228]
我记得我在之前的版本是记得如faster-RCNN Cascade-RCNN在PaddleDetection上训练时需要将dataset中的类别数设置为 n+1 n是你要识别的种类，1是背景，我想问一下现在的版本也要这么设置嘛。

**Comment by nemonameless** [comment]
类别数n+1是静态图在PaddleDetection/static目录，现在默认根目录是动态图，去除背景类了，类别数就设置为n。
