### ISSUE TITLE
在AI Studio 使用PaddleDetection测试是否安装成功时，发现报错

### ISSUE THREAD

**Issue by ai-zml** [PaddlePaddle/PaddleDetection#523]
#### 1、检查PaddlePaddle是否安装正确
     `import_ paddle.fluid as fluid`
     `fluid.install_check.run_check()`
     结果显示正常：
     Running Verify Paddle Program ... 
     Your Paddle works well on SINGLE GPU or CPU.
     Your Paddle works well on MUTIPLE GPU or CPU.
     Your Paddle is installed successfully! Let's start deep Learning with Paddle now
#### 2、测试PaddlePaddle版本：
      `python -c "import paddle; print(paddle.__version__)"`
1.7.1
#### 3、`export PYTHONPATH=$PYTHONPATH:.`
       `python ppdet/modeling/tests/test_architectures.py`
就出现了下面的错误，前面每次运行模型之前，我都是按着这个步骤，屡试不爽，但是从昨天开始就不对了：
ERROR: test_test (__main__.TestSSD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 51, in test_test
    test_fetches = model.eval(feed_vars)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/ssd.py", line 130, in eval
    return self.build(feed_vars, 'eval')
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/ssd.py", line 82, in build
    inputs=body_feats, image=im, num_classes=self.num_classes)
  File "/home/aistudio/work/PaddleDetection/ppdet/core/workspace.py", line 150, in partial_apply
    return op(*args, **kwargs_)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/detection.py", line 2202, in multi_box_head
    min_max_aspect_ratios_order)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/detection.py", line 1786, in prior_box
    attrs=attrs, )
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1877, in __init__
    self.desc.check_attrs()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
2   paddle::framework::ExtractAttribute<std::vector<float, std::allocator<float> > >::operator()(boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>&) const
3   std::_Function_handler<void (std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >*, bool), paddle::framework::TypedAttrChecker<std::vector<float, std::allocator<float> > > >::_M_invoke(std::_Any_data const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >*, bool)
4   paddle::framework::OpDesc::CheckAttrs()

----------------------
Error Message Summary:
----------------------
Error: Cannot get attribute max_sizes by type std::vector<float, std::allocator<float> >, its type is std::vector<int, std::allocator<int> > at (/paddle/paddle/fluid/framework/attribute.h:42)

阴霾挥之不去，很是苦恼
请问这个可以怎么解决呢？非常感谢

**Comment by heavengate** [comment]
请问跑模型能跑么

**Comment by heavengate** [comment]
本地测试了下，1.7.1在master和release/0.2上都可以跑通的，看你描述似乎AIStudio环境有问题？请问有联系过AIStudio的同学排查下么~

**Comment by heavengate** [comment]
测试了下Paddle1.7.1跑PaddleDetection的master和release/0.2分支的test_architechure.py都可以跑通，看你描述AIStudio的环境有些问题？请问有没有联系过AIStudio的同学帮忙看下呢~

**Comment by ai-zml** [comment]
@heavengate 非常感谢您的回答，我把AIStudio平台里面自己建的文件夹都删掉了，从新安装PaddleDetection, 可以跑通了，初步估计是aistudio环境里缓存的文件太大了，启动环境时，难以同步的问题

**Comment by heavengate** [comment]
好的，如果问题解决了，当前issue就先关闭了~
