### ISSUE TITLE
tinypose模型转换问题！！！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleDetection#5230]
hi，

1 tinypose官方提供的是*.pdmodel  *.pdiparams 等格式，是否可以提供keypoint版本的 paddle训练结果的*.pdmodel，*.pdparams格式？
2 tinypose 要想利用 opt 工具转换生成 Amlogic NPU 模型，必须先转成__model__格式吧？有木有现成的tinypose和movenet的__model__格式模型文件分享下？
3 tinypose从训练好的模型最初的格式转换再转化一直到生成能够再NPU上运行的nb格式，具体的流程能否简单画下？能分享下相关链接吗？

BR

**Comment by zoooo0820** [comment]
@2050airobert 
你好
1.没太看明白，PaddleDetection训练得到的就是上述格式，keypoint模型并没有专门的特殊格式。
2. opt模型转换直接针对导出(./tool/export.py)的模型就可以了。针对Amlogic NPU， 请参考文档https://paddle-lite.readthedocs.io/zh/develop/demo_guides/amlogic_npu.html   即在转换命令中加入`--valid_targets=amlogic_npu,arm` ， 此外paddle-lite的库版本应该也需要替换为针对该NPU的适配版本，具体可以参考文档流程。
3. 目前我们并未在Amlogic NPU上测试过部署，不太清楚该款npu对模型参数是否有特殊的要求？整体大致为训练(*.pdparams)-> 导出export（*.pdmodel, *.pdiparams) -> Paddle-Lite opt转化（*.nb)
