### ISSUE TITLE
训练MCFairMOT时没有visdrone_mcmot.train

### ISSUE THREAD

**Issue by 1996nolan** [PaddlePaddle/PaddleDetection#5231]

**Comment by nemonameless** [comment]
https://bj.bcebos.com/v1/paddledet/data/mot/visdrone_mcmot.zip 这是我们处理后的数据集，gt的txt是在sequences文件夹里的，是visdrone原本验证集数据集的gt。

**Comment by LMR2018** [comment]
@1996nolan  兄弟，你训练MCFairMOT模型推断速度怎样？在什么平台测的？有多少FPS？快不快？
