### ISSUE TITLE
请问paddleslim可以对ppyolov2进行剪枝吗？

### ISSUE THREAD

**Issue by curryJ** [PaddlePaddle/PaddleDetection#5232]
我尝试利用paddleslim剪枝ppyolov2_r50vd，但是出现了如下提示：
![image](https://user-images.githubusercontent.com/23001027/154844161-f8973822-5cb6-4e25-bcc4-c3edee273833.png)
对深度可分离卷积无法剪枝，那么我可以对ppyolov2进行剪枝压缩吗 谢谢

**Comment by yghstill** [comment]
@curryJ 可以对ppyolov2进行剪枝，只是部分层无法剪枝，具体剪枝哪些层可以先打印下网络结构，将print_params设为True即可，一般yolo模型剪枝head部分：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/slim/prune/ppyolo_r50vd_prune_fpgm.yml#L13
