### ISSUE TITLE
PP-tinyPose能不能转成onnx模型进行C++调用呀

### ISSUE THREAD

**Issue by lofyol** [PaddlePaddle/PaddleDetection#5239]

**Comment by lofyol** [comment]
![111](https://user-images.githubusercontent.com/43843359/155054435-3a4b6cfe-3ed5-4452-818e-8bc230cbb778.JPG)

**Comment by lofyol** [comment]
我用paddle2onnx转，这是没成功还是成功了呀

**Comment by zoooo0820** [comment]
@lofyol 
您好，可以参考这个页面 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/third_engine/demo_mnn_kpts  提供了对其他一些部署框架的支持，其中包含有转Onnx的步骤
