### ISSUE TITLE
error when --eval 

### ISSUE THREAD

**Issue by cena001plus** [PaddlePaddle/PaddleDetection#5244]
在训练faster-rcnn-swin时，如果增加-eval，就有如下错误，所以训练的时候没有加eval，正常训练了几个epoch后，就推理了几张图，是可以检测出框的，想eval一下验证集，然后就在验证到1200张数据后，就出如下问题。
之前也问过类似问题，但是当时是因为数据集没有设置正确，现在这个问题我不知道是怎么产生的，如果有一张没检测到框按道理讲也不应该出现这个错误啊。

`02/22 17:40:08] ppdet.engine INFO: Eval iter: 900
[02/22 17:40:13] ppdet.engine INFO: Eval iter: 1000
[02/22 17:40:18] ppdet.engine INFO: Eval iter: 1100
[02/22 17:40:23] ppdet.engine INFO: Eval iter: 1200

省略
省略

File "/home/zhangwei/work/detection/PaddleDetection/ppdet/metrics/metrics.py", line 273, in update
    gt_box = gt_boxes[i].numpy()

RuntimeError: (PreconditionNotMet) Tensor's dimension is out of bound.Tensor's dimension must be equal or less than the size of its memory.But received  Tensor's dimension is d16 memory's size is 0.

  [Hint: Expected numel() * SizeOfType(type()) <= memory_size(), but received numel() * SizeOfType(type()):16 > memory_size():0.] (at /paddle/paddle/fluid/framework/tensor.cc:39`

**Comment by ghostxsl** [comment]
faster-rcnn-swin应该是只支持batch size = 1的预测

**Comment by cena001plus** [comment]
> faster-rcnn-swin应该是只支持batch size = 1的预测

有没有看问题

**Comment by cena001plus** [comment]
> 然后就在验证到1200张数据后，就出如下问题

然后就在验证到1200张数据后，就出如下问题

> faster-rcnn-swin应该是只支持batch size = 1的预测

然后就在验证到1200张数据后，就出如下问题

**Comment by ghostxsl** [comment]
你自己debug一下看看吧

**Comment by cena001plus** [comment]
eval 时，batch_size=1, 但是推理100个itera打印一次，我想推理一次打印一下，我就能知道是哪个图出错了，但是没找到设置选项

**Comment by cena001plus** [comment]
重新生成验证集，验证时不再提示错误，认真检查图片是否有损害是否有截断。 

只能单卡训练，batch_size设置为1， 这样训练速度极其缓慢，另外因为batch_size太小，训练的模型精度会很差，建议不要用这个框架的大模型。
