### ISSUE TITLE
picodet训练遇到错误

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#5247]
![X_OEAQW4FD7A{G7W`D)X8)V](https://user-images.githubusercontent.com/48303408/155251812-368525f9-7e2d-47dc-a8ef-e8f0c4a404b7.png)
用另一个数据集没问题，用这个数据集就出现这个问题，请问大佬这是什么原因呢？

**Comment by zhiboniu** [comment]
看起来是队列返回了empty，请查看一下数据加载是否正常呢
