### ISSUE TITLE
PPYOLOv2训练自己的数据集，读取速度很慢

### ISSUE THREAD

**Issue by HardHat-Det** [PaddlePaddle/PaddleDetection#5250]
![image](https://user-images.githubusercontent.com/49087498/155323198-43344fc9-513c-4d6a-86c4-25c85e2233a0.png)

**Comment by HardHat-Det** [comment]
单张V100

**Comment by zhiboniu** [comment]
检查一下Gpu利用率、本地有没有同时在跑其他任务

**Comment by HardHat-Det** [comment]
> 检查一下Gpu利用率、本地有没有同时在跑其他任务

GPU利用率很低，我在训练代码里加了时间戳，就是读取速度很慢，会不会跟共享内存有关，我在docker里启的训练

**Comment by HardHat-Det** [comment]
> > 检查一下Gpu利用率、本地有没有同时在跑其他任务
> 
> GPU利用率很低，我在训练代码里加了时间戳，就是读取速度很慢，会不会跟共享内存有关，我在docker里启的训练

> 检查一下Gpu利用率、本地有没有同时在跑其他任务

GPU利用率长时间为0

**Comment by mengdongwei** [comment]
@zhangyusen1997 我也遇到了类似的问题。batch_size=16时 data_cost 还算正常（小于1秒）；batch_size=48时（cpu系统调用很高），data_cost直接到20秒，随着训练进行，data_cost涨到离谱的150秒。我也是在docker里训练的，我关掉共享内存后也会出现类型的情况。

**Comment by mengdongwei** [comment]
@zhangyusen1997 又试了一下，把num_worker设置为0时，batch_size=64，data_cost很稳定在3.6秒左右。感觉就是dataloader多线程 的问题。
