### ISSUE TITLE
PicoDet支持batch>1部署

### ISSUE THREAD

**Issue by surfola** [PaddlePaddle/PaddleDetection#5252]
https://github.com/PaddlePaddle/PaddleDetection/blob/6e65f11d8ec0169655b5ec7614a6360b25090ae3/ppdet/modeling/heads/pico_head.py#L265
什么时候可以优化一下这个picodet，支持下batch>1的部署呢

**Comment by nemonameless** [comment]
后续会支持，敬请期待，谢谢关注。
