### ISSUE TITLE
paddledetection中静态动态模型部署格式问题

### ISSUE THREAD

**Issue by liangruofei** [PaddlePaddle/PaddleDetection#5256]
各位大佬：有几个相关的困惑需要解答一下
1、paddledetion的动态、静态的具体含义是指啥
我理解的套件外围的训练属于动态，static包里面的属于静态模式，不知道理解的是否正确

2、两种流程训练的结果格式不同
动态的结果output模型为：model_final.pdparams 和model_final.pdopt文件
static包里面训练的output模型为：model_final.pdmodel、model_final.pdopt、model_final.pdparams
这两种模型之间可以转换吗，如何转换

3、用套件做python的部署
动态的结果inference_model模型为：model.pdmodel 、model.pdiparams、model.pdiparams.info和infer_cfg.yml文件
static包里面训练的inference_model模型为：__model__、__params__、infer_cfg.yml
这两种模型之间可以转换吗，如何转换

4、动态的inference_model模型部署和static包里面的inference_model模型部署有什么区别，哪个更高效

**Comment by zhouweic36** [comment]
我也想知道，动态图怎么一键转静态图？

**Comment by wangxinxin08** [comment]
@liangruofei 
1. 理解正确。static下面属于静态模式，主目录下面属于动态模式
2. 两种模式下训练的模型一般不需要转换，如果你使用静态图，就直接使用static目录下的代码，如果使用动态图，就直接使用主目录下面的代码
3. 部署时两种模式下的模型一般也不需要转换，如果你使用静态图，直接使用static目录下面的部署方式，如果使用动态图，就直接使用主目录下面的部署方式
4. 动态图的inference model和静态图的inference model在底层有一些差异，但可以使用相同的接口调用，建议使用动态图的方式进行模型的训练，使用动转静的方式进行模型部署，之后这种方式会持续迭代，而静态图基本不会增加新的特性了

**Comment by TANSHOUTAO** [comment]
> @liangruofei
> 
> 1. 理解正确。static下面属于静态模式，主目录下面属于动态模式
> 2. 两种模式下训练的模型一般不需要转换，如果你使用静态图，就直接使用static目录下的代码，如果使用动态图，就直接使用主目录下面的代码
> 3. 部署时两种模式下的模型一般也不需要转换，如果你使用静态图，直接使用static目录下面的部署方式，如果使用动态图，就直接使用主目录下面的部署方式
> 4. 动态图的inference model和静态图的inference model在底层有一些差异，但可以使用相同的接口调用，建议使用动态图的方式进行模型的训练，使用动转静的方式进行模型部署，之后这种方式会持续迭代，而静态图基本不会增加新的特性了



> @liangruofei
> 
> 1. 理解正确。static下面属于静态模式，主目录下面属于动态模式
> 2. 两种模式下训练的模型一般不需要转换，如果你使用静态图，就直接使用static目录下的代码，如果使用动态图，就直接使用主目录下面的代码
> 3. 部署时两种模式下的模型一般也不需要转换，如果你使用静态图，直接使用static目录下面的部署方式，如果使用动态图，就直接使用主目录下面的部署方式
> 4. 动态图的inference model和静态图的inference model在底层有一些差异，但可以使用相同的接口调用，建议使用动态图的方式进行模型的训练，使用动转静的方式进行模型部署，之后这种方式会持续迭代，而静态图基本不会增加新的特性了

大佬，如果想要在static里对模型进行剪枝与量化的两种操作，该怎么做？？
