### ISSUE TITLE
paddleDetection 目前我发现config里面模型 voc训练得很少，但都是coco得数据集

### ISSUE THREAD

**Issue by wyc880622** [PaddlePaddle/PaddleDetection#526]
我想问得是coco得数据集yolov3_reader.yml这个是设置coco得数据集路径，但是其他得模型没有，比如faster_rcnn_r50_fpn_1x.yml 我不知道如何用faster_rcnn_r50_fpn_1x.yml 来训练我自己得数据集，我目前得数据集是voc 。请问我应该怎么做。还有我训练完成后，我如果用C#来调用训练完成得模型进行推理。谢谢

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/e040d0e61a2a8f2315d56e40c13a6730364daaa1/configs/yolov3_darknet_voc.yml#L72 
可以参考这个改一下，yolo的模型都是同时提供了coco和voc数据集上的配置，你可以vimdiff对比一下看看怎么从coco数据集修改为voc数据集

**Comment by wyc880622** [comment]
你的意思可以将faster_rcnn_r50_fpn_1x.yml 来改成voc格式的配置，是这样的码？

**Comment by heavengate** [comment]
> 你的意思可以将faster_rcnn_r50_fpn_1x.yml 来改成voc格式的配置，是这样的码？

是的，一般只需要改`class_num`字段和数据集路径配置的那段copy过来就可以了

**Comment by ai-zml** [comment]
yolov3_darknet_voc.yml中的
num_max_boxes: 50 这一行用注释掉吗？会报错

**Comment by wishgale** [comment]
希望能多提供voc格式的yml配置文件,用yolov3的yolov3_darknet_voc.yml修改有问题.
比如修改:faster_fpn_reader.yml,改为voc个时候,训练会出现下面的问题
persistable: false
need_check_feed: true
), ('gt_bbox', name: "gt_bbox"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 4
    }
    lod_level: 1
  }
}
persistable: false
need_check_feed: true
), ('gt_class', name: "gt_class"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT32
      dims: -1
      dims: 1
    }
    lod_level: 1
  }
}
persistable: false
need_check_feed: true
), ('is_difficult', name: "is_difficult"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT32
      dims: -1
      dims: 1
    }
    lod_level: 1
  }
}
persistable: false
need_check_feed: true
)]) has no is_crowd field

**Comment by wishgale** [comment]
> 希望能多提供voc格式的yml配置文件,用yolov3的yolov3_darknet_voc.yml修改有问题.
> 比如修改:faster_fpn_reader.yml,改为voc个时候,训练会出现下面的问题
> persistable: false
> need_check_feed: true
> ), ('gt_bbox', name: "gt_bbox"
> type {
> type: LOD_TENSOR
> lod_tensor {
> tensor {
> data_type: FP32
> dims: -1
> dims: 4
> }
> lod_level: 1
> }
> }
> persistable: false
> need_check_feed: true
> ), ('gt_class', name: "gt_class"
> type {
> type: LOD_TENSOR
> lod_tensor {
> tensor {
> data_type: INT32
> dims: -1
> dims: 1
> }
> lod_level: 1
> }
> }
> persistable: false
> need_check_feed: true
> ), ('is_difficult', name: "is_difficult"
> type {
> type: LOD_TENSOR
> lod_tensor {
> tensor {
> data_type: INT32
> dims: -1
> dims: 1
> }
> lod_level: 1
> }
> }
> persistable: false
> need_check_feed: true
> )]) has no is_crowd field

找到原因了,加上is_crowd就可以训练了
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_mask']

**Comment by qingqing01** [comment]
rcnn已提供了voc的配置
