### ISSUE TITLE
[Other General Issues]PP-PicoDet 如何指定推理输入大小？

### ISSUE THREAD

**Issue by ChungTak** [PaddlePaddle/PaddleDetection#5260]
使用yolov5 习惯训练使用640x640 ,然后推理的指定大小为 384 x640。 请问  PP-PicoDet 是否支持这样的操作?
 PP-PicoDet  推理demo都是输入配置文件，没看到可以设置推理输入大小。

**Comment by liangruofei** [comment]
我也想知道

**Comment by noahzn** [comment]
@ChungTak 我觉得你可以在配置文件里改TestReader
https://github.com/PaddlePaddle/PaddleDetection/blob/19478edce0d2b940fdb333159ee9e0f42a1d44bf/configs/picodet/_base_/picodet_416_reader.yml#L35
