### ISSUE TITLE
关于预处理的参数[Other General Issues]

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#5261]
请问PaddleDetection 里面有没有 擦除 和 随机重组这些预处理参数

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/data/transform/operators.py#L309 
随机重组具体是指什么？mixup cutmix mosaic之类的吗？相关的可以在此[operators.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/data/transform/operators.py)文件里搜索。

**Comment by jerrywgz** [comment]
随机重组可以参考这里的代码 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/data/transform/operators.py#L2475
