### ISSUE TITLE
picodet转化onnx,openvino推理结果是很多小数，官方没有windows+python的指导文档

### ISSUE THREAD

**Issue by xiangfeidecao** [PaddlePaddle/PaddleDetection#5263]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

onnx转化后，openvino加载onnx或者简化的onnx,exec_net.infer推理输出不是目标框。使用的是pip install openvino。所以没有转IR文件，直接openvino加载onnx模型。

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) /I have read the [FAQ documentation](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) but cannot get the expected help.

## 描述问题/Describe the bug

Processing output blob [[[1.6074101e-02 1.4028271e-02]
  [8.0285119e-03 7.3967515e-03]
  [3.5309466e-03 3.5542445e-03]
  ...
  [3.7131427e-05 4.1627580e-05]
  [1.7567823e-04 1.7590502e-04]
  [1.4011755e-04 1.6459050e-04]]]

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by yghstill** [comment]
@xiangfeidecao 将配置文件中export_post_process 字段设为True，然后重新导出下模型，即可预测输出检测框信息：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/picodet/_base_/picodet_esnet.yml#L3

或者参考https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/third_engine/demo_openvino 完成模型预测输出的后处理就可得到检测框信息。

**Comment by xiangfeidecao** [comment]
> @xiangfeidecao 将配置文件中export_post_process 字段设为True，然后重新导出下模型，即可预测输出检测框信息：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/picodet/_base_/picodet_esnet.yml#L3
> 
> 或者参考https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/third_engine/demo_openvino 完成模型预测输出的后处理就可得到检测框信息。

非常感谢您的回复。但是我用第一种方法重新导出训练的模型，然后转onnx.还是用我的openvino代码推理同一张图，结果还是一样，[1,1600,2].连数据都一样，我估计我拿到的就是模型参数吧，不是推理结果。第二种方案，我觉得我的输出和那个c++完全对不上。

**Comment by xiangfeidecao** [comment]
> @xiangfeidecao 将配置文件中export_post_process 字段设为True，然后重新导出下模型，即可预测输出检测框信息：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/picodet/_base_/picodet_esnet.yml#L3
> 
> 或者参考https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/third_engine/demo_openvino 完成模型预测输出的后处理就可得到检测框信息。

还请教下，为啥我用官网下的picodet_s_320_coco.onnx推理一张004.png.得到的是结果shape【1，1600，80】。这是表明我openvino代码有问题吗？

**Comment by yghstill** [comment]
@xiangfeidecao 官方的picodet模型是不包含后处理的，输出结果是[1，1600，80]是正确的，需要额外的后处理，可以参考https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/third_engine/demo_openvino
