### ISSUE TITLE
能不能出个python版本openvino加载picodet_s_320_coco检测模型的指导文档

### ISSUE THREAD

**Issue by xiangfeidecao** [PaddlePaddle/PaddleDetection#5265]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

请问，能不能出个python版本openvino加载picodet_s_320_coco检测模型的指导文档？目前我按照网络上各种openvino+onnx或者pdmodel教程，仍不能准确获得检测框。但是官方给的c++代码和python版本区别比较大。希望有个python版本，并且加载picdet官方现有模型的示例。谢谢

**Comment by yghstill** [comment]
@xiangfeidecao 感谢反馈，我们近期支持一下。
