### ISSUE TITLE
在aistudio上训练，没有lap模块

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#5271]
各位大佬，我在aistudio上训练picodet，lap明明安装好了，训练的时候还是报错没有lap模块

**Comment by nemonameless** [comment]
环境问题，请仔细查看下python路径和对应的pip list。

**Comment by Dandelion111** [comment]
> 环境问题，请仔细查看下python路径和对应的pip list。

我运行paddle官方的例子也是有这个情况
https://aistudio.baidu.com/aistudio/projectdetail/2882573?channelType=0&channel=0

**Comment by Dandelion111** [comment]
> 环境问题，请仔细查看下python路径和对应的pip list。

请问这个python路径怎么看的
![image](https://user-images.githubusercontent.com/48303408/156281287-b0183250-a512-490f-bfef-5e2b0553a72a.png)
