### ISSUE TITLE
[Other General Issues] configs中的faster_rcnn配置文件没有voc格式

### ISSUE THREAD

**Issue by xiaoxiangch** [PaddlePaddle/PaddleDetection#5273]
使用PaddleDetection的过程中，发现configs下yolov3有基于voc格式的配置文件，所以把自定义数据集转为了voc格式，但是再换到
fasterrcnn下时，发现全部都是coco格式的，所以想问下为什么没有voc格式的配置文件，是有什么技术问题还是说不适用？

**Comment by wangxinxin08** [comment]
你好，faster rcnn也是支持voc格式的，你只需要https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/faster_rcnn/faster_rcnn_r50_1x_coco.yml#L2 替换成../datasets/voc.yml即可
