### ISSUE TITLE
[安装依赖] requirements.txt 里写Cython 直接安装会装不上，建议改成小写

### ISSUE THREAD

**Issue by LukeALee** [PaddlePaddle/PaddleDetection#5275]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-25t48to0/cython-bbox_2e9c83f93dcb48ba9384205a7afa7231/setup.py'"'"'; __file__='"'"'/tmp/pip-install-25t48to0/cython-bbox_2e9c83f93dcb48ba9384205a7afa7231/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mlq5m8xd
         cwd: /tmp/pip-install-25t48to0/cython-bbox_2e9c83f93dcb48ba9384205a7afa7231/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-25t48to0/cython-bbox_2e9c83f93dcb48ba9384205a7afa7231/setup.py", line 10, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
WARNING: Discarding https://pip.baidu-int.com/packages/packages/fa/b9/fc7d60e8c3b29cc0ff24a3bb3c4b7457e10b7610fbb2893741b623487b34/cython_bbox-0.1.3.tar.gz#sha256=82e2d887534ecc10d3507489a05b11259f3baacd29eee37e6d8c97e1ffb16554 (from https://pip.baidu-int.com/simple/cython-bbox/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached https://pip.baidu-int.com/packages/packages/be/50/21618d0e79554dadd44383a1448ae667941950e391e2d9f7cf1986a0a512/cython_bbox-0.1.2.tar.gz (40 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-25t48to0/cython-bbox_18a40a9dfe7a45889217534a566ca7a7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-25t48to0/cython-bbox_18a40a9dfe7a45889217534a566ca7a7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-s7xbbv9t
         cwd: /tmp/pip-install-25t48to0/cython-bbox_18a40a9dfe7a45889217534a566ca7a7/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-25t48to0/cython-bbox_18a40a9dfe7a45889217534a566ca7a7/setup.py", line 10, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
WARNING: Discarding https://pip.baidu-int.com/packages/packages/be/50/21618d0e79554dadd44383a1448ae667941950e391e2d9f7cf1986a0a512/cython_bbox-0.1.2.tar.gz#sha256=81740b3b5e88be8ab12165fc6e176094ac71ef8bc12a27588fe94d85b6128c1c (from https://pip.baidu-int.com/simple/cython-bbox/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement cython_bbox
ERROR: No matching distribution found for cython_bbox

python3.7.10, requirements.txt 中大写Cython pip install -r  requirements.txt 会报错，改成小写即可。

**Comment by wangxinxin08** [comment]
收到，我们验证并修复下

**Comment by lugengyou** [comment]
我也遇到相同的问题，可以尝试一下这样解决：
安装前升级一下 pip: python -m pip install --upgrade pip
再单独安装 cython: pip install cython
