### ISSUE TITLE
RTX3090 预测慢

### ISSUE THREAD

**Issue by fujunhao411** [PaddlePaddle/PaddleDetection#5276]
RTX3090显卡在视频预测时fps过低。
（1）Paddle版本为2.2.2
（2）GPU：RTX 3090，CUDA11.2 CUDNN 8.2，完全对应的官方版本，24G显存
（3）系统环境：W10，Python版本：3.8
（4）CPU：I9-10920X
（5）模型：PP-Tracking中的行人检测模型，MOT17.官方预训练模型，并非自己训练的模型。出问题了以后使用的官方模型进行的实测。
（6）预测视频：实时视频流，输入fps为25，模型预测输出fps为8
（7）同样代码、同样模型情况下，2070显卡搭配CUDA10.2，模型预测输出为30+

已调整过的CUDA版本：11.0、11.1、11.2，三者fps分别为：8.05、8.55、8.89
依据官方CUDA版本要求，只支持至11.2，则未进行11.4等更新的版本测试。

预测过程中：GPU使用2.2G，CPU使用8%，并未出现爆内存的情况。
麻烦各位大佬帮忙分析下，具体问题出在了哪里，8fps无法应对实时视频流传输需求。而且相同条件下，2070的预测速率比3090的要快4倍，感觉有问题。

同样代码、同样模型，在1660Ti搭配CUDA10.2上，fps达到22-25。
代码采用的均为官方实例代码，并未进行改动。
需要专业人士讲解是否是 Paddle对30系显卡的支持性有些许的问题。
后续将进行CUDA11.3、11.4等高版本测试，按官方说明Paddle最高支持版本为11.2，所以不清楚是否能够顺利运行。

**Comment by fujunhao411** [comment]
有大佬帮忙解答一下么

**Comment by fujunhao411** [comment]
有没有官方大大回复下

**Comment by wangxinxin08** [comment]
你好，RTX3090属于安培架构，最好使用cuda11.2的paddle版本进行测试

**Comment by fujunhao411** [comment]
> 你好，RTX3090属于安培架构，最好使用cuda11.2的paddle版本进行测试

使用的就是CUDA11.2，预测fps太慢

**Comment by wangxinxin08** [comment]
不好意思，没注意到，你使用同样的代码在1660Ti上和RTX 3090上测试的结果是1660Ti的速度大于RTX 3090吗？

**Comment by fujunhao411** [comment]
> 不好意思，没注意到，你使用同样的代码在1660Ti上和RTX 3090上测试的结果是1660Ti的速度大于RTX 3090吗？

是的，完全复制过来的代码，只不过搭配的CUDA不同，1660TI对应的是10.2,3090对应的11.2

**Comment by wangxinxin08** [comment]
收到，我们验证下，如果有问题，将会排期修复

**Comment by fujunhao411** [comment]
> 收到，我们验证下，如果有问题，将会排期修复

好的，如果确认问题，也请麻烦您回复一下，十分感谢。

**Comment by wangxinxin08** [comment]
好的

**Comment by fujunhao411** [comment]
> 好的

补充一下，预测文件使用的是   PaddleDetection2.3下面的  deploy/pptracking/python/mot_jde_infer.py

**Comment by fujunhao411** [comment]
> 好的

新的测试结果：C++部署过后，生成的exe文件，预测速度有些许的提升，从8.05提升至8.4fps，但依然差距很远。同时，请麻烦测试一下3060所对应的预测效果。我也在进行后续的测试。

**Comment by wangxinxin08** [comment]
我们这边已经反馈给相关同学，后续会排期定位优化

**Comment by voyag8r** [comment]
@fujunhao411 麻烦问一下 您的3090预测只有8fps的时候是用了trt吗？
我目前做的1080ti上只用gpu加速，fps大约有10

**Comment by fujunhao411** [comment]
> trt

是的，使用C++部署的过程中用了trt，但是提升效果并没有多大，只提高了0.4的fps，官方给的说法是安培系列显卡的sm值均为84，但官方paddle编译时编入的为sm_80,可以去Paddle的github下，我提了同样的问题，那个问题下有官方的回复

**Comment by voyag8r** [comment]
> 

好的多谢
