### ISSUE TITLE
opencv_c++ demos指导文档疑问

### ISSUE THREAD

**Issue by xiangfeidecao** [PaddlePaddle/PaddleDetection#5277]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

1.按照openvino官网安装，临时初始化环境变量后，可以成功运行演示程序。然后按照PicoDet OpenVINO Demo上set the system environment variables once for all:方式设置环境变量后，无法运行openvino的演示程序，提示：
**C:\Program Files (x86)\Intel\openvino_2021\deployment_tools\demo>demo_security_barrier_camera.bat
target_precision = FP16
此时不应有 \Intel\openvino_2021\deployment_tools\inference_engine\bin\intel64\Debug。**
请问这是正常吗？

2.mkdir -p build
cd build
cmake ..这个之后msbuild picodet_demo.vcxproj /p:configuration=release /p:platform=x64，提示：
'msbuild' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
请问这个要处理吗？

3.在build中点开picodet_demo.sln,重新生成后，小改了几个地方（1.#include <chrono>，2.filenames）,生成了exe.但是运行不成功，在InferenceEngine::Core ie初始化报错。这个地方还没有加载模型，是哪里问题呢？
![image](https://user-images.githubusercontent.com/41140837/156151080-09142892-cb4a-4a54-9464-3293ef1c94ce.png)

**Comment by xiangfeidecao** [comment]
原来是debug模式不行，改成release就可以正常跑官方的picodet_416.xml.但是不能跑我自己训练成功的picodet_s_320模型。onnxz转ir：python mo_onnx.py --input_model E:\openvino_ppdet\onnx\picodet_s320coco0222.onnx --mean_values [0.485,0.456,0.406] --scale_values [0.229,0.224,0.225] --output_dir E:\openvino_ppdet\onnx\openvino。试过用简化和不简化两版，然后只修改了num_class_=1(头文件中).都无法检测到目标。挂在auto results = detector.detect(resized_img, 0.4, 0.5);

**Comment by xiangfeidecao** [comment]
原来是image_size没改。改成320，num_class_=1.类型数组改成我自己的类别，可以跑通，但是检测结果不对。漏检误检。

**Comment by xiangfeidecao** [comment]
请大佬帮忙看看，现在除了官方给的picodet_416.xml可以正常跑通，其他官方的picodet_s_320.onnx或者我自己训练的模型转的onnx,简化的onnx,再转IR模型都不能正常检测，都乱的。我修改了image_size成320，num_class_=1.类型数组改成我自己的类别

**Comment by wangxinxin08** [comment]
检测结果的话，可以对比下直接使用PaddleDetection的tools/infer.py预测得到的结果，如果这两个结果没有太大出入可以排除是由于openvino带来的影响

**Comment by xiangfeidecao** [comment]
> 检测结果的话，可以对比下直接使用PaddleDetection的tools/infer.py预测得到的结果，如果这两个结果没有太大出入可以排除是由于openvino带来的影响

目前我训练的用infer都是正常的。在demo_openvino上都是乱的。我只改了几个地方。可能还有什么需要改的，或者onnx转IR的命令有什么错误的
