### ISSUE TITLE
如何训练自己的Backbone

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#5279]
我试着在 PaddleDetection 中加入了 BotNet 作为 Backbone 我应该如何去训练 BotNet 的预训练模型，同时如何训练他的蒸馏模型？

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/ppdet/modeling/backbones
参考一下这里backbone的写法，同时在__init__里导入，就可以在config里用了
