### ISSUE TITLE
An Unknown Error When Training YOLOV3 DARKNET with Fruit Dataset

### ISSUE THREAD

**Issue by p1n0cch10** [PaddlePaddle/PaddleDetection#528]
I am using yolov3 darknet53 to finetuning the fruit data.
The .yml file is modified according to yolov3_mobilenet_v1_fruit.yml and yolov3_darknet_fruit_test.yml.

I change the .yml to .txt in order to upload the file to the github post.
[yolov3_darknet_fruit_test.txt](https://github.com/PaddlePaddle/PaddleDetection/files/4493893/yolov3_darknet_fruit_test.txt)

After I execute

python -u tools/train.py -c configs/yolov3_darknet_fruit_test.yml -o use_fine_grained_loss=true --eval

an unknown error occurs. Could anyone help me with the error. Many thanks.

`2020-04-17 23:53:16,897-INFO: 60 samples in file dataset/fruit/val.txt
2020-04-17 23:53:16,898-INFO: places would be ommited when DataLoader is not iterable
/home/alex/paddle-venv/lib/python3.6/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 331, in <module>
    main()
  File "tools/train.py", line 172, in main
    exe.run(startup_prog)
  File "/home/alex/paddle-venv/lib/python3.6/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/home/alex/paddle-venv/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/alex/paddle-venv/lib/python3.6/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/home/alex/paddle-venv/lib/python3.6/site-packages/paddle/fluid/executor.py", line 831, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/alex/paddle-venv/lib/python3.6/site-packages/paddle/fluid/executor.py", line 905, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

C++ Call Stacks (More useful to developers):

0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace)
3   std::_Function_handler<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > (), std::reference_wrapper<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()> > >::_M_invoke(std::_Any_data const&)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   std::__future_base::_Deferred_state<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_run_deferred()
7   paddle::platform::DeviceContextPool::Get(paddle::platform::Place const&)
8   paddle::framework::GarbageCollector::GarbageCollector(paddle::platform::Place const&, unsigned long)
9   paddle::framework::UnsafeFastGPUGarbageCollector::UnsafeFastGPUGarbageCollector(paddle::platform::CUDAPlace const&, unsigned long)
10  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
11  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

Error Message Summary:

Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information: out of memory at (/paddle/paddle/fluid/platform/device_context.cc:221)`

**Comment by jerrywgz** [comment]
I tried the config file exactly the same as your's on my own environment and it ran correctly.
The error message shows the OOM and there are several methods for you:
1. Use the same data configure as https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/configs/yolov3_mobilenet_v1_fruit.yml , because the batch_size is 8 and multiprocess is used in yolov3_reader.yml which may be not friendly for your environment. We adopt batch size of 1 on fruit dataset by default.
2. The pretrain model you used is DarkNet on ImageNet. I recommend https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet.tar for better performance.

**Comment by p1n0cch10** [comment]
> I tried the config file exactly the same as your's on my own environment and it ran correctly.
> The error message shows the OOM and there are several suggestion for you:
> 
> 1. Use the same data configure as https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/configs/yolov3_mobilenet_v1_fruit.yml , because the batch_size is 8 and multiprocess is used in yolov3_reader.yml which may not be friendly for your environment. We adopt batch size of 1 on fruit dataset by default.
> 2. The pretrain model you used is DarkNet on ImageNet. I recommend https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet.tar for better performance.

Hi jerrywgz, that works. Thanks a lot.

My GPU usage was very larget...
