### ISSUE TITLE
aistudio上面用paddledetection训练picodet没有pycocotools和lap模块

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#5280]
请问大佬，aistudio上面用paddledetection训练picodet没有pycocotools和lap模块，用paddle官方的教程项目和自己新建的项目都出现这个问题，
教程项目：https://aistudio.baidu.com/aistudio/projectdetail/2882573?channelType=0&channel=0

**Comment by lyuwenyu** [comment]
```
! pip install --upgrade -r requirements.txt -i https://mirror.baidu.com/pypi/simple
```
教程前半段有个依赖的按照 查看一下有没有正确执行

**Comment by Dandelion111** [comment]
> ```
> ! pip install --upgrade -r requirements.txt -i https://mirror.baidu.com/pypi/simple
> ```
> 
> 教程前半段有个依赖的按照 查看一下有没有正确执行

依赖库都安装好了，用pip list也能看到pycocotools和lap已经有了
![image](https://user-images.githubusercontent.com/48303408/156309701-7922162c-4e5f-4db4-bca8-e4a61272f885.png)
![image](https://user-images.githubusercontent.com/48303408/156309733-378076db-bce9-424b-8d08-b8be5ae8289c.png)
