### ISSUE TITLE
c++部署编译失败

### ISSUE THREAD

**Issue by terrancraft** [PaddlePaddle/PaddleDetection#5285]
## 描述问题/Describe the bug
如题，编译c++部署代码时出现报错
## 复现/Reproduction

使用的命令： sh  scripts/build.sh

编译文件如下图所示：

![build sh (~-git_opensource-PaddleDetection-release-2 3-pork-cpp-scripts) - gedit_001](https://user-images.githubusercontent.com/51820927/156504345-6d194678-bf9e-499b-8973-207b39b21440.png)

报错内容：找不到log头文件

如图所示：
![ubuntu@natb-gpu-server: ~-git_opensource-PaddleDetection-release-2 3-pork-cpp_003](https://user-images.githubusercontent.com/51820927/156504611-29965682-dbb8-43aa-9d33-53225c34d8aa.png)

版本描述：
ubuntu18.04
cuda11.2
gcc 7.5
cudnn8.2.1

疑问：

是不是我的paddle inference路径填写的不对？

**Comment by nemonameless** [comment]
建议再仔细自查下路径~

**Comment by terrancraft** [comment]
上一个问题解决了，opencv编译动态链接库的那一步骤过不去
如图所示：
![Screenshot from 2022-03-04 18-41-49](https://user-images.githubusercontent.com/51820927/156981442-67bb7272-f17e-4056-a4e4-fb4c4b45e666.png)

我的gcc 是8.2版本 
@nemonameless 
望解答，谢谢！

**Comment by pphgood** [comment]
楼主 我和你是一样的问题 请问你解决了吗
