### ISSUE TITLE
PaddleDetection是否可以进行停车位的四个角点的检测？有没有代码链接？

### ISSUE THREAD

**Issue by daigang896** [PaddlePaddle/PaddleDetection#5286]
您好，PaddleDetection是否可以进行停车位的四个角点的检测？有没有训练代码和测试代码的链接？

**Comment by nemonameless** [comment]
是异形框(旋转框)的检测吗？可以参照S2ANet模型 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/dota

**Comment by daigang896** [comment]
应该不算旋转框，就是四边形的4个角点，不是旋转矩形。

**Comment by nemonameless** [comment]
个人觉得可以当成实例分割来做，把四个角点当成mask，可以参照 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/solov2， 不过结果也是mask了需要后处理成4个角点比如取4个极值点之类的操作。

**Comment by daigang896** [comment]
这样感觉太复杂了，就当作普通的检测4个点，类似目标框检测，是否可以？

**Comment by Kus66** [comment]
有解决方案了吗
