### ISSUE TITLE
MultiscaleTestResize

### ISSUE THREAD

**Issue by CocoSkyler** [PaddlePaddle/PaddleDetection#5287]
打扰了，请问现在动态图增加了MultiScaleTEST功能吗，谢谢

**Comment by nemonameless** [comment]
已经支持，PR #4377 ，参照  https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/faster_rcnn/faster_rcnn_r34_fpn_multiscaletest_1x_coco.yml
