### ISSUE TITLE
关于PicoDet的模型输出问题[Other General Issues]

### ISSUE THREAD

**Issue by szNightFury** [PaddlePaddle/PaddleDetection#5290]
想问下PicoDet的Head部分是怎么转换为最终的分类结果和预测框的，用netron看了最后是transpose_xx.tmp_0，我还是个小白不太懂，希望能解释清楚一点，只知道每个分支或许输出分类和预测框坐标？那这四个检测头的输出已经是最终结果了吗，看其他issue说是还要后处理和nms，我不太理解，意思是netron这里的图不包括后处理和nms部分吗？那后处理和nms又是怎么做的呢
![Uploading 1646300402937..jpg…]()

**Comment by yghstill** [comment]
@szNightFury PicoDet导出模型默认是不包含后处理的，只输出了每个分支的feature，后处理需要单独处理，可以参考：
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/python/picodet_postprocess.py

即将发布的最新PicoDet模型将后处理包含在网络中，直接输出检测框信息，开发者无需再写后处理代码，可以使用develop代码，导出时指定export_post_process: True：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/picodet/_base_/picodet_esnet.yml#L3

**Comment by warren-wzw** [comment]
想问一下楼主后面有搞明白他这个8个输出是怎么得到最后的检测框和类别的嘛？
