### ISSUE TITLE
模型导出部署

### ISSUE THREAD

**Issue by Abris-087** [PaddlePaddle/PaddleDetection#5294]
您好，我使用PaddleDetection训练出了一些SSD、PPYOLO的目标检测模型，并用tools/export.py将模型导出。
然后我想将这些模型部署到嵌入式设备中（比如树莓派、百度EdgeBoard嵌入式卡），请问有这方面的指导文档吗？我在嵌入式设备中该如何调用导出的模型文件呢？

**Comment by ghostxsl** [comment]
请参考Paddle-Lite部署文档：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/lite/README.md
