### ISSUE TITLE
picodet m模型非结构剪枝训练后使用  tools/export_model.py  和./opt 模型转换为nb模型后模型大小和原来正常训练后转换的模型大小一致

### ISSUE THREAD

**Issue by yangyukun0619** [PaddlePaddle/PaddleDetection#5296]
picodet m模型非结构剪枝训练后使用  tools/export_model.py  和./opt 模型转换为nb模型后模型大小和原来正常训练后转换的模型大小一致，请问是什么原因   

原始模型：*.pdott  8293kb  *.pdparams 8429kb  
非结构剪枝： *.pdott  8293kb  *.pdparams 11053kb  

动转静模型大小
原始模型： model.pdiparams  8379kb  model.pdmodel  4112kb
非结构剪枝：model.pdiparams  8379kb  model.pdmodel  4112kb

nb模型
原始模型：model.nb  8909kb
非结构剪枝：model.nb  8909kb

**Comment by yghstill** [comment]
@yangyukun0619 非结构化剪枝导出的模型weight会变大，导出的模型和正常fp32模型一样大，属于正常现象，主要测试加速情况即可。
