### ISSUE TITLE
PaddleDetection 迁移学习方法请教

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleDetection#530]
我现在使用PaddleDetection，用自己标注的数据，已经训练了一个YOLO v3的模型，保存在本地文件中。现在又多了一批训练数据（类别一样），我想继续训练模型，但是PaddleDetection上的迁移学习教程中使用了pretrain_weights和finetune_exclude_pretrained_params这两个参数，其中第一个参数是网址，意思是要从网上下载预训练模型。问题是：

1、那我自己的模型，pretrain_weights是不是就是本地模型的文件路径？

2、使用自己的模型时，finetune_exclude_pretrained_params参数是否有用，该如何使用？

谢谢！

**Comment by qingqing01** [comment]
@670133189 因为你类别数一样，继续恢复训练即可，通过 `-r checkpoint_path` 即可，参考：

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/tutorials/GETTING_STARTED_cn.md#%E5%8F%AF%E9%80%89%E5%8F%82%E6%95%B0%E5%88%97%E8%A1%A8

**Comment by 670133189** [comment]
> @ 670133189因为你类别数一样，继续恢复训练即可，通过`-r checkpoint_path`即可，参考：
> 
> [https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/tutorials/GETTING_STARTED_cn.md#%E5%8F%AF%E9%80%89%E5%8F%82%E6%95%B0 ％E5％88％97％E8％A1％A8](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/tutorials/GETTING_STARTED_cn.md#%E5%8F%AF%E9%80%89%E5%8F%82%E6%95%B0%E5%88%97%E8%A1%A8)

感谢回复！

**Comment by 670133189** [comment]
> @670133189 因为你类别数一样，继续恢复训练即可，通过 `-r checkpoint_path` 即可，参考：
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/tutorials/GETTING_STARTED_cn.md#%E5%8F%AF%E9%80%89%E5%8F%82%E6%95%B0%E5%88%97%E8%A1%A8

如果我在原有的自定义类别基础上，再添加新类别的话，该如何操作？
比如我已经训练了“篮球”，我需要再添加“足球、排球”。

**Comment by heavengate** [comment]
> > @670133189 因为你类别数一样，继续恢复训练即可，通过 `-r checkpoint_path` 即可，参考：
> > https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/tutorials/GETTING_STARTED_cn.md#%E5%8F%AF%E9%80%89%E5%8F%82%E6%95%B0%E5%88%97%E8%A1%A8
> 
> 如果我在原有的自定义类别基础上，再添加新类别的话，该如何操作？
> 比如我已经训练了“篮球”，我需要再添加“足球、排球”。

类别不一样需要滤除与类别相关的层的权重加载，因为这些层类别不一样会shape不匹配，不能正确下载，可以参考
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md
YOLOv3中指定`finetune_exclude_pretrained_params=['yolo_output']`即可

**Comment by 670133189** [comment]
> > > @670133189 因为你类别数一样，继续恢复训练即可，通过 `-r checkpoint_path` 即可，参考：
> > > https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/tutorials/GETTING_STARTED_cn.md#%E5%8F%AF%E9%80%89%E5%8F%82%E6%95%B0%E5%88%97%E8%A1%A8
> > 
> > 
> > 如果我在原有的自定义类别基础上，再添加新类别的话，该如何操作？
> > 比如我已经训练了“篮球”，我需要再添加“足球、排球”。
> 
> 类别不一样需要滤除与类别相关的层的权重加载，因为这些层类别不一样会shape不匹配，不能正确下载，可以参考
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md
> YOLOv3中指定`finetune_exclude_pretrained_params=['yolo_output']`即可

**Comment by AntyRia** [comment]
> 我现在使用PaddleDetection，用自己标注的数据，已经训练了一个YOLO v3的模型，保存在本地文件中。现在又多了一批训练数据（类别一样），我想继续训练模型，但是PaddleDetection上的迁移学习教程中使用了pretrain_weights和finetune_exclude_pretrained_params这两个参数，其中第一个参数是网址，意思是要从网上下载预训练模型。问题是：
> 
> 1、那我自己的模型，pretrain_weights是不是就是本地模型的文件路径？
> 
> 2、使用自己的模型时，finetune_exclude_pretrained_params参数是否有用，该如何使用？
> 
> 谢谢！

你好，请问下你解决了吗，关于增加新类别的训练方法，我看了官方文档，有些链接文件缺失，看的不是很明白
