### ISSUE TITLE
picodet的python推理代码中有NMS步骤吗

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#5309]
请问 python推理代码中有NMS步骤在哪里呢？只找到了阈值过滤部分，没找到NMS
![image](https://user-images.githubusercontent.com/48303408/156874028-8d61d073-e377-4ea8-98c9-4f80edfd8d5e.png)

**Comment by zhiboniu** [comment]
你好，应该是在模型内部处理的。
