### ISSUE TITLE
[Other General Issues] ppyolo_tiny中可以设置只对单一分类进行训练吗？

### ISSUE THREAD

**Issue by 6UOOON9** [PaddlePaddle/PaddleDetection#5311]
比如我只想对 人 这一分类进行训练？

**Comment by zoooo0820** [comment]
@6UOOON9 
可以参考下利用Picodet只训练人这一类别的做法，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/application/pedestrian_detection/picodet_s_320_pedestrian.yml
