### ISSUE TITLE
PicoDet serving 部署的fetch_list 要怎么配置

### ISSUE THREAD

**Issue by lguowang** [PaddlePaddle/PaddleDetection#5325]
大家好，我用pp训练了PicoDet，然后导出模型进行sering部署，但预测时出现主要的错误： {'err_no': 8, 'err_msg': "(data_id=0 log_id=0) [ppyolo|0] Failed to postprocess: 'transpose_17.tmp_0.lod'", 'key': [], 'value': [], 'tensors': []}
请问 fetch_list: 要配置成什么样的？
请问 fetch_list: 要配置成什么样的？
请问 fetch_list: 要配置成什么样的？

serving_server 中的 serving_server_conf.prototxt ：
feed_var {
name: "image"
alias_name: "image"
is_lod_tensor: false
feed_type: 1
shape: 1
shape: 3
shape: 416
shape: 416
}
fetch_var {
name: "transpose_10.tmp_0"
alias_name: "transpose_10.tmp_0"
is_lod_tensor: false
fetch_type: 1
shape: 1
shape: 2704
shape: 4
}
fetch_var {
name: "transpose_11.tmp_0"
alias_name: "transpose_11.tmp_0"
is_lod_tensor: false
fetch_type: 1
shape: 1
shape: 2704
shape: 32
}
fetch_var {
name: "transpose_12.tmp_0"
alias_name: "transpose_12.tmp_0"
is_lod_tensor: false
fetch_type: 1
shape: 1
shape: 676
shape: 4
}
fetch_var {
name: "transpose_13.tmp_0"
alias_name: "transpose_13.tmp_0"
is_lod_tensor: false
fetch_type: 1
shape: 1
shape: 676
shape: 32
}
fetch_var {
name: "transpose_14.tmp_0"
alias_name: "transpose_14.tmp_0"
is_lod_tensor: false
fetch_type: 1
shape: 1
shape: 169
shape: 4
}
fetch_var {
name: "transpose_15.tmp_0"
alias_name: "transpose_15.tmp_0"
is_lod_tensor: false
fetch_type: 1
shape: 1
shape: 169
shape: 32
}
fetch_var {
name: "transpose_16.tmp_0"
alias_name: "transpose_16.tmp_0"
is_lod_tensor: false
fetch_type: 1
shape: 1
shape: 49
shape: 4
}
fetch_var {
name: "transpose_17.tmp_0"
alias_name: "transpose_17.tmp_0"
is_lod_tensor: false
fetch_type: 1
shape: 1
shape: 49
shape: 32
}

我配置的config.yml:
dag:
is_thread_op: false
tracer:
interval_s: 30
http_port: 18888
op:
ppyolo:
concurrency: 1

local_service_conf:
  client_type: local_predictor
  device_type: 1
  devices: '0'
  fetch_list: 
  - transpose_17.tmp_0
  model_config: serving_server/
rpc_port: 9998
worker_num: 2

请问 fetch_list: 要配置成什么样的？
请问 fetch_list: 要配置成什么样的？

**Comment by ChiTaoGIS** [comment]
遇到了同样的问题，希望告诉一下怎么解决
