### ISSUE TITLE
picodet 运行时报错，使用的是 官方的 roadsign 数据，运行yolov3 时不会报错

### ISSUE THREAD

**Issue by YuNaruto** [PaddlePaddle/PaddleDetection#5329]
1. 在运行  CUDA_VISIBLE_DEVICES=0 python tools/train.py  -c configs/picodet/picodet_s_320_roadsign_voc.yml --eval ，命令时会报错
2. 在运行 CUDA_VISIBLE_DEVICES=0  python tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml --eval ，命令不会报错，正常运行结束
3. 数据：官方的 roadsign voc 数据，没有做改动
4. 配置文件也没有改动
5. 环境：paddlepaddle-gpu  2.2.1；paddledet    2.3.0；GTX TITAN X， 12G

![image](https://user-images.githubusercontent.com/32025355/157234969-5c575c19-3496-4b1f-938b-749172248d9f.png)
![image](https://user-images.githubusercontent.com/32025355/157235177-77648775-c52a-4673-b900-8207ab5ce1fd.png)

**Comment by YuNaruto** [comment]
这个bug并不是每次运行都会出现，但**很**容易出现，崩溃前 loss_vfl 的值 会变得非常大

**Comment by YuNaruto** [comment]
![image](https://user-images.githubusercontent.com/32025355/157231767-62b37ea3-5b46-4ec7-b682-742284541036.png)
 
如上图，上一次 300个epoch 训练完毕，没有任何变动，直接运行相同的代码，然后就崩溃了

**Comment by YuNaruto** [comment]
上图中：
红框是上一次运行结束
绿框是再一次运行
黄框是报错内容

@heavengate

**Comment by heavengate** [comment]
看日志里是出nan了，你是几卡训练的，picodet的默认配置是8卡训练的，如果你是单卡训练的话可以把learning rate除以8试下

**Comment by YuNaruto** [comment]
> 看日志里是出nan了，你是几卡训练的，picodet的默认配置是8卡训练的，如果你是单卡训练的话可以把learning rate除以8试下

我是单卡训练的，好的我调一下 lr 试试

**Comment by YuNaruto** [comment]
调小学习率之后，ok了，没有出现崩溃现象
