### ISSUE TITLE
怎样用opencv的dnn模块调用picodet导出的onnx文件

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleDetection#5330]
你好，怎样用opencv的dnn模块调用picodet导出的onnx文件？有C++和Python版本的示例吗，谢谢

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/cpp/src/object_detector.cc
可以参考一下我们提供的C++部署代码，预处理是基于cv2实现的，把中间加载模型和模型推理部分替换掉就行
