### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#5332]
请问一下，如果要使用 MobileNetV3-small 0.5x 这种模型作为骨干网络的话，怎么修改预训练模型的地址呢？直接将x1_0 修改为 x0_5 的话，报错网址找不到。

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/algorithm_introduction/ImageNet_models.md
