### ISSUE TITLE
[Feature Request] 关于高通的SNPE的dlc模型不支援hardsigmoid激活功能

### ISSUE THREAD

**Issue by jayer95** [PaddlePaddle/PaddleDetection#5333]
您好，首先感谢您们的优秀PaddlePaddle的端到端目标检测，
请问您們是否能够提供高通SNPE的dlc模型转换的支持，
请参考: https://developer.qualcomm.com/sites/default/files/docs/snpe/overview.html

我们已经在高通晶片的边缘端/移动端使用了yolov5n.dlc，并得到满意的结果。
我们在互联网查询到了您的模型架构，在边缘端/移动端似乎比yolov5n更快、更好，

我检查了您提供的ONNX内部，您的ONNX模型使用了SNPE不支持的hardsigmoid激活功能，现在无法转换为SNPE .dlc。
它需要用其他层(Sigmoid)替换hardsigmoid来解决这个限制，
请参考: https://github.com/PeterL1n/RobustVideoMatting/issues/47

请问您们能提供上述的协助吗? 我们对最轻量的PicoDet有兴趣，
但是，我不确定替换模型是否与原始模型特征相同。

**Comment by yghstill** [comment]
@jayer95 hardsigmoid激活函数均出现在se模块中，请使用[PicoDet-LCNet](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/more_config/picodet_lcnet_1_5x_416_coco.yml) ，同时需要修改LCNet的block6，se均设为False，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/backbones/lcnet.py#L52

就可以整个网络均屏蔽hardsigmoid激活函数。您可以试下，有任何问题欢迎反馈。

**Comment by rossilhf** [comment]
@yghstill 您好，我在修改lcnet.py后，se是设为False了，但是用infer.py推理的结果却也都不对了。是不是修改lcnet.py后，预训练模型都没用了，需要重头自己训练模型？谢谢！
