### ISSUE TITLE
模型优化提示 ops 不支持 softplus

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#5334]
![image](https://user-images.githubusercontent.com/88072901/157370682-a87b3548-e171-418a-a9a3-271087d47836.png)
如图所示 模型用的ppyolo-tiny 就是neck用的 pan 模型导出后转换的时候 提示这个 不支持 怎么解决啊

**Comment by jerrywgz** [comment]
请问使用的paddlelite opt版本是多少呢，目前softplus只有mish激活函数中用到了 我这边看了下ppyolo-tiny中没有用到这个激活，可以再确认下模型结构？

**Comment by STUSER001** [comment]
> 请问使用的paddlelite opt版本是多少呢，目前softplus只有mish激活函数中用到了 我这边看了下ppyolo-tiny中没有用到这个激活，可以再确认下模型结构？

是版本问题 我用2.10 就没问题了  谢谢
