### ISSUE TITLE
我已经设置好训练集，但为什么还自动下载训练集，并且还一直下载不下来。

### ISSUE THREAD

**Issue by wyc880622** [PaddlePaddle/PaddleDetection#534]
这是我的训练命令 python  tools/train.py -c configs/yolov3_r34_voc.yml
请问为什么呢，我不想下载了，就想直接进行训练。
yolov3_r34_voc.yml 文件 

architecture: YOLOv3
use_gpu: true
max_iters: 20000
log_smooth_window: 20
save_dir: output
snapshot_iter: 2000
metric: VOC
map_type: 11point
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet34_pretrained.tar
weights: output/yolov3_r34_voc/model_final
num_classes: 3
use_fine_grained_loss: false

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head

ResNet:
  norm_type: sync_bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 34
  feature_maps: [3, 4, 5]

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

YOLOv3Loss:
  batch_size: 8
  ignore_thresh: 0.7
  label_smooth: false

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 55000
    - 62000
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'yolov3_reader.yml'
TrainReader:
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: trainval.txt
    use_default_label: true
    with_background: false

EvalReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: test.txt
    use_default_label: true
    with_background: false

TestReader:
  dataset:
    !ImageFolder
    use_default_label: true
    with_background: false

**Comment by wyc880622** [comment]
我运行了2条命令 
python  tools/train.py -c configs/yolov3_r34_voc.yml 会一直下载数据集
python -u tools/train.py -c configs/yolov3_r34_voc.yml  --use_tb=True --tb_log_dir=tb_fruit_dir/scalar --eval 不会自动下载，但是报错
我数据集用的给公用数据集 苹果 橙子 香蕉
报错内容：
Traceback (most recent call last):
  File "tools/train.py", line 324, in <module>
    main()
  File "tools/train.py", line 141, in main
    eval_reader = create_reader(cfg.EvalReader)
  File "G:\Halcon\Paddle\PaddleDetection\ppdet\data\reader.py", line 406, in create_reader
    reader = Reader(**cfg)()
  File "G:\Halcon\Paddle\PaddleDetection\ppdet\data\reader.py", line 202, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "G:\Halcon\Paddle\PaddleDetection\ppdet\data\source\dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "G:\Halcon\Paddle\PaddleDetection\ppdet\data\source\voc.py", line 131, in load_roidb_and_cname2cid
    gt_class[i][0] = cname2cid[cname]
KeyError: 'orange'

**Comment by jerrywgz** [comment]
使用水果数据集的话需要在配置文件中dataset的部分将voc的数据路径修改为水果数据集的路径，具体配置可以参考： https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/configs/yolov3_mobilenet_v1_fruit.yml#L76

**Comment by zxz-cc** [comment]
检查一下你的数据路径，最好用绝对路径，免得出错
