### ISSUE TITLE
[Other General Issues]导出模型格式问题

### ISSUE THREAD

**Issue by haotian18** [PaddlePaddle/PaddleDetection#5343]
使用tools/export_model.py导出模型为pdmodel和pdiparams，但是需要老版的__model__和__params__，请问两者有区别么，或者有什么方法转换成__model__和__params__格式？

**Comment by yghstill** [comment]
@haotian18 内容基本一致，可以重命名一下使用。

**Comment by Craw-B** [comment]
重新命名后能用吗
