### ISSUE TITLE
[BUG]PicoDet 在 Sering 部署问题

### ISSUE THREAD

**Issue by lguowang** [PaddlePaddle/PaddleDetection#5345]
PicoDet 在 Sering 部署问题，出现以下错误：

  File "/usr/local/lib/python3.7/site-packages/paddle_serving_server/pipeline/operator.py", line 1105, in _run_postprocess
    logid_dict.get(data_id))
  File "testser.py", line 49, in postprocess
    fetch_dict, visualize=False))
  File "/usr/local/lib/python3.7/site-packages/paddle_serving_app/reader/image_reader.py", line 434, in __call__
    self.clsid2catid)
  File "/usr/local/lib/python3.7/site-packages/paddle_serving_app/reader/image_reader.py", line 346, in _get_bbox_result
    output = fetch_map[fetch_name]

主要问题是：fetch_map的key 只有 image,没有其他key,没有其他key
我训练和导出是用2.3版本，怎么才能正常用在 Sering 部署?？？？？

serving_server_conf.prototxt：
feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
  shape: 416
  shape: 416
}
fetch_var {
  name: "save_infer_model/scale_0.tmp_1"
  alias_name: "save_infer_model/scale_0.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_1.tmp_1"
  alias_name: "save_infer_model/scale_1.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_2.tmp_1"
  alias_name: "save_infer_model/scale_2.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_3.tmp_1"
  alias_name: "save_infer_model/scale_3.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_4.tmp_1"
  alias_name: "save_infer_model/scale_4.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_5.tmp_1"
  alias_name: "save_infer_model/scale_5.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_6.tmp_1"
  alias_name: "save_infer_model/scale_6.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_7.tmp_1"
  alias_name: "save_infer_model/scale_7.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}

config.yml文件：
dag:
  is_thread_op: false
  tracer:
    interval_s: 20
http_port: 18888
op:
  yolov3:
    concurrency: 1
    local_service_conf:
      client_type: local_predictor
      device_type: 1
      devices: '0'
      fetch_list:
      - save_infer_model/scale_0.tmp_1
      - save_infer_model/scale_1.tmp_1
      - save_infer_model/scale_2.tmp_1
      - save_infer_model/scale_3.tmp_1
      - save_infer_model/scale_4.tmp_1
      - save_infer_model/scale_5.tmp_1
      - save_infer_model/scale_6.tmp_1
      - save_infer_model/scale_7.tmp_1      
      model_config: serving_server/
rpc_port: 9998
worker_num: 1

**Comment by wangxinxin08** [comment]
image是feed_var，fetch_name是在fetch_list中定义的
