### ISSUE TITLE
[Document Improvement]数据增强顺序问题

### ISSUE THREAD

**Issue by lazyn1997** [PaddlePaddle/PaddleDetection#5348]
## 📖  文档优化/Documentation Improvement

**请简单说明文档存在问题/Please provide a concise and brief description of the documentation problem:**
PaddleDetection/docs/advanced_tutorials/READER.md文档中3.1部分几点说明中对批数据增强算子的使用顺序做了一定的限制，然而在最新的PaddleDetection/configs/ppyolo/_base_/ppyolov2_reader.yml文件中数据增强算子的顺序却和文档中不一致，我按照这样的顺序仍可以正常训练，所以这个顺序不是强制要求吗？那这样的话输入数据的格式不就无法保证为CHW格式了吗，为什么训练过程中也没有报错？
还有一个问题，就是
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 100}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
这些算子不都是单图像增强算子吗，为什么放置到batch_transforms中而不是sample_transforms中？
**请提供有问题的文档部分截图及链接/Please provide the screen shoot and the link of the document:**
![QQ截图20220311155732](https://user-images.githubusercontent.com/34644177/157829207-3592fa40-6db8-4a8b-9e71-92c3f222677d.jpg)
![QQ截图20220311160051](https://user-images.githubusercontent.com/34644177/157829228-4fadbd72-9425-44ca-96e8-058a7649852f.jpg)

**Comment by wangxinxin08** [comment]
1. 文档中有说，单图数据增强算子也可用于批数据处理中，不过应当了解单图数据增强算子和批处理算子的区别，比如文档中所说的BatchRandomResize和RandomResize的区别
2. ppyolov2_reader其实满足文档中关于顺序的限制，Permute在BatchRandomResize之后，Gt2YoloTarget之前，NormalizeBox在Gt2xxxTarget之前，NormalizeBox和Permute的顺序并无限制

**Comment by lazyn1997** [comment]
感谢回复，我明白了。
