### ISSUE TITLE
[snipper的negative chip mining应该训练多少轮]

### ISSUE THREAD

**Issue by github-eliviate** [PaddlePaddle/PaddleDetection#5351]
## 📖  文档优化/Documentation Improvement

**请简单说明文档存在问题/Please provide a concise and brief description of the documentation problem:**
snipper论文中，negative chip mining时，只训练了2轮的rpn，官方文档【PaddleDetection/configs/sniper/README_cn.md 22行】的negative chip mining训练的是12个epoch，模型训练时又是12个epoch，请问：b步骤的epoch和数据集有关么？也就是说在visdrone数据集上，b步骤就是应该训练12个epoch；还是说步骤b只是示例，实际应该少训练几个epoch

**请提供有问题的文档部分截图及链接/Please provide the screen shoot and the link of the document:**
文档截图：
![image](https://user-images.githubusercontent.com/14120941/157837627-3ddcff07-9cfb-4412-b12a-65ebc792866c.png)
论文：
![image](https://user-images.githubusercontent.com/14120941/157837883-51a2d598-1cee-4960-abe0-84df80a65880.png)

**Comment by wangxinxin08** [comment]
paper中是在coco数据集上实验的结果，在visdrone上你可以通过实验调整下，我们的实验并不充分，这里并非说训练12个epoch对于visdrone的negative chip mining是一个最佳的epoch
