### ISSUE TITLE
使用PP-Tracking算法测试自定义数据集没有结果

### ISSUE THREAD

**Issue by LegendSun0** [PaddlePaddle/PaddleDetection#5354]
您好，使用PP-Tracking算法测试自定义数据集模型时遇到以下问题。
python -m paddle.distributed.launch --log_dir=./output/log/fairmot_hrnetv2_w18_dlafpn_30e_1088x608/ --gpus 2,3 tools/train.py -c configs/mot/vehicle/fairmot_hrnetv2_w18_dlafpn_30e_1088x608_visdrone_vehicle.yml训练模型，数据集、训练过程正常，
![image](https://user-images.githubusercontent.com/57515354/158002378-e8c55431-2a56-42d5-8a15-f281716a4535.png)

也可以导出模型，但在使用模型预测是并没有结果。
![image](https://user-images.githubusercontent.com/57515354/158002398-fee73934-c79c-4f34-b272-c2b767a1bbc6.png)

评估是所有参数为0.
![1647056411(1)](https://user-images.githubusercontent.com/57515354/158002345-43a8df63-0654-4c60-a0f3-0f9d44213302.jpg)

**Comment by LegendSun0** [comment]
同样在使用configs/mot/vehicle/fairmot_dla34_30e_1088x608_bdd100kmot_vehicle.yml配置文件训练的模型，测试、评估就有结果
![image](https://user-images.githubusercontent.com/57515354/158002701-d0fee767-4cea-4283-a6c2-c58b18fdffc6.png)

![image](https://user-images.githubusercontent.com/57515354/158002692-8a8bc33d-3326-40e8-9d43-642e2899bc9f.png)

但使用dla34网络并不能进行onnx转换，我查看了文档目前只支持的PaddleSeg模型，所以dla34 并不是PaddleSeg模型么？
![image](https://user-images.githubusercontent.com/57515354/158002962-97b2faf0-4ece-4fcd-9b21-fc575a901e0c.png)

**Comment by nemonameless** [comment]
1. eval是需要验证集的gt文件存在且标注正确的，建议先检查下。infer的话看保存的txt文件里有没有结果，可视化会有个阈值默认0.5，可以调低点就能画出来更多。
2.dla34 是一个backbone主干网络，fairmot论文是使用它作backbone的，也可以用HRNet做backbone组装网络，但是fairmot这个模型在PaddleDetection套件里是还没有支持onnx。

**Comment by LegendSun0** [comment]
好的，感谢您的回答。
