### ISSUE TITLE
使用paddleslim蒸馏时报错ImportError: cannot import name 'create_reader' from 'ppdet.data.reader'

### ISSUE THREAD

**Issue by Muke6** [PaddlePaddle/PaddleDetection#5355]
我已经正常安装了paddledetection

**Comment by Muke6** [comment]
我已经尝试了1. run static model under PaddleDetection/static ，2. run 'pip uninstall ppdet' to uninstall ppdet无法解决Importing ppdet failed when running static model

**Comment by lewisandJiang** [comment]
> 我已经尝试了1. run static model under PaddleDetection/static ，2. run 'pip uninstall ppdet' to uninstall ppdet无法解决Importing ppdet failed when running static model

兄弟你解决了吗？

**Comment by bbilixzc** [comment]
遇到了相同的问题，请问您解决了吗？

**Comment by nemonameless** [comment]
建议拉取最新代码，pip uninstall paddledet，然后再安装一下 python setup.py install。
