### ISSUE TITLE
paddle inference Tensor数据如何读取

### ISSUE THREAD

**Issue by zgq91** [PaddlePaddle/PaddleDetection#5361]
你好：
 我想请问一下 使用Paddle inference时预测获取到的Tensor类的数据假设维度1x21x40x80。数据按行还是按列读取

for(int n=0; n<21; n++)
{
     for(int i=0; i<40; i++)
     {
         for(int j=0; j<80; j++)
         {
             int index = n*40*80 + i*80 +j;
             float data = output_data[index];
          }
     }
}
这样索引读取对嘛

**Comment by ghostxsl** [comment]
对的

**Comment by zgq91** [comment]
> 对的
但我这样索引读取数据和用python 多维数组索引读取数据会不一样；预处理和模型是相同的
