### ISSUE TITLE
deepsort for tracking

### ISSUE THREAD

**Issue by chenjw1009** [PaddlePaddle/PaddleDetection#5362]
给的例子都是fairmot 进行训练的，deepsort怎么来进行训练呢？有相关例子吗，文档中deepsort都是预测、评价相关的，没有训练的；

**Comment by nemonameless** [comment]
deepsort是分离检测和reid的，检测器是单独训练的，[参照](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/mot/deepsort/detector) 
reid是用已经训好的模型权重。检测器训完后，可以单独eval检测指标 导出 部署之类的，但是eval跟踪指标需要组装成一个这样的deepsort的[yml](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/mot/deepsort/deepsort_ppyoloe_pplcnet.yml#L39)， 结构定义为deepsort，权重路径自行指定，参照文档即可运行跟踪的评估和部署。
