### ISSUE TITLE
“ERROR: No matching distribution found for cython_bbox”

### ISSUE THREAD

**Issue by shenhm** [PaddlePaddle/PaddleDetection#5363]
问题主要是源的问题，一些源不稳定，可以替换一下其他源，所以我的解决方案先使用其他源安装Cython，再接着安装就没问题了
# 先安装Cython
pip install Cython -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
# 再接着安装
pip install -r requirements.txt

**Comment by ghostxsl** [comment]
您是碰到环境安装的问题，已经解决了吗？
