### ISSUE TITLE
class id是什么意思

### ISSUE THREAD

**Issue by github-eliviate** [PaddlePaddle/PaddleDetection#5369]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## 描述问题/Describe the bug
![image](https://user-images.githubusercontent.com/14120941/158512241-80aa4ba0-bc0a-4ec4-a582-e1c3e028bed8.png)
category id和category name在coco的categories项里面能找到，那个class id是什么含义？该怎么设置，我没有在文档里面找到它的含义
其它问题：
1. bbox_num的长度和category类别相等？对应位置的值就是该类别的检测结果数量？
2. im_id是什么意思？
我用sniper的时候
 image_shape和scale_factor也出现了多个，这个和bbox_num，bbox有什么对应关系吗

**Comment by zoooo0820** [comment]
1. coco检测的预测类别数80类，class_id怎么来的可以看[这里](https://github.com/PaddlePaddle/PaddleDetection/blob/f7b0fb44d80cd12da62cdf686a7c16b7ed259798/ppdet/data/source/coco.py#L71-L86) 。预测结果出来后通过映射得到标注定义的类别序号。
2. bbox_num请参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/post_process.py#L63
3. 预测结果的解析请参考上面链接里的过程。
