### ISSUE TITLE
[BUG]PPTracking跨镜跟踪用自己的数据集失效

### ISSUE THREAD

**Issue by sry948749099** [PaddlePaddle/PaddleDetection#5376]
您好，

我配置好PaddleDetection后测试MOT单相机跟踪可以运行且效果较好

运行跨镜跟踪readme中的AIC demo数据集同样与展示效果一致，检测结果较好

更换AIC为自己数据集且修改mtmct_cfg.yml中的视频名称后，运行时出现 : Frame 1680 has no object, try to modify score threshold  提示，且运行后检测框与图像内的行人不对准，如下所示

![00263](https://user-images.githubusercontent.com/56307410/158585270-36f65cb0-67bb-421e-a083-01b87aa7462a.jpg)

请问出现这种情况是什么原因呢？  是因为数据集的问题还是需要在源代码里修改一些参数？

**Comment by sry948749099** [comment]
运行所用的模型如下：

--model_dir=jde_yolov3_darknet53_30e_1088x608_mix
--_reid_dir=deepsort_pcb_pyramid_r101

跨镜数据集内仅包含行人一个类别

**Comment by nemonameless** [comment]
完整的运行命令可以发下吗？另外其他的检测模型比如ppyolo yolov3等也可试试

**Comment by sry948749099** [comment]
> 完整的运行命令可以发下吗？另外其他的检测模型比如ppyolo yolov3等也可试试

完整命令如下：

python deploy/pptracking/python/mot_sde_infer.py --model_dir=output_inference/jde_yolov3_darknet53_30e_1088x608_mix/ --reid_model_dir=output_inference/deepsort_pplcnet --mtmct_dir=./mtmct-demo --device=GPU -mtmct_cfg=deploy/pptracking/python/mtmct_cfg.yml --scaled=False --save_mot_txts --save_images --threshold=0.1

请问出现上面的检测框与行人不对齐是什么原因呢？

检测器模型我试过了yolov2和v3，行人重识别模型只用了LCNET

**Comment by dongyangli-del** [comment]
我也是用JDE_YOLOv3和你一样  出现了画面检测框与行人对不齐的状况,请问解决了吗?
