### ISSUE TITLE
用自己的coco数据集训练好模型后加载权重进行infer的时候，标签对不上

### ISSUE THREAD

**Issue by USDuser** [PaddlePaddle/PaddleDetection#5386]
![1](https://user-images.githubusercontent.com/94952993/158742524-fee9e5fd-6fe6-46d4-be4d-b0a7d6c4b905.jpg)
json里面的标签没有问题，训练什么的也是正常的，但是执行infer.py的时候标签不对

**Comment by USDuser** [comment]
![1](https://user-images.githubusercontent.com/94952993/158742799-11206353-8781-4286-86fc-567440b34186.jpg)

**Comment by qingqing01** [comment]
您注意TestDataset里正确设置 json文件，避免用的默认的COCO标签。

https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/datasets/coco_detection.yml#L19

**Comment by Craw-B** [comment]
我也遇见了，这个需要怎么解决的啊
