### ISSUE TITLE
deepsort Reid 模型如何训练? 有参考吗？

### ISSUE THREAD

**Issue by chenjw1009** [PaddlePaddle/PaddleDetection#5388]
deepsort 有相关的检测模型训练方法，ReID模型如何训练，有参考吗？

**Comment by nemonameless** [comment]
使用的是PaddleClas训好的reid模型。参考 PaddleClas 的reid 训练文档，https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/ppcls/configs/Vehicle/PPLCNet_2.5x_ReID.yaml  ，相关问题 #4927  。另外不建议自己训，deepsort的跟踪能力非常依赖检测器，为提高跟踪效果建议优化检测器。
