### ISSUE TITLE
模型导出后c++部署推理，得不到结果

### ISSUE THREAD

**Issue by baigang666** [PaddlePaddle/PaddleDetection#539]
yolo增强模型模型在python下正常训练，并且使用python的infer.py推理可以检测到目标，然后利用export_model.py导出模型后，在c++下部署，推理检测不到目标。请问如何解决？附件中是我的模型文件和yaml配置 ，请帮忙看一下是否正确，谢谢

**Comment by baigang666** [comment]
以下是cpp_demo.xml文件，在python下使用cpp_infer.py也没有检测结果

# demo for cpp_infer.py

use_python_inference: true # whether to use python inference
mode: fluid # trt_fp32, trt_fp16, trt_int8, fluid
arch: YOLO # YOLO, SSD, RCNN, RetinaNet
min_subgraph_size: 3 # need 3 for YOLO arch

# visualize the predicted image
metric: COCO # COCO, VOC
draw_threshold: 0.2

Preprocess:
- type: Resize
  target_size: 1280
  max_size: 1280
- type: Normalize
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  is_scale: True
- type: Permute
  to_bgr: False
- type: PadStride
  stride: 0 # set 32 on FPN and 128 on RetinaNet

**Comment by baigang666** [comment]
pyhton 下infer.py中的配置文件和参数文件
"config",default='./dcn/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco.yml', 
 "-o", "--opt",nargs='*',default=['weights=./yolov3_r50vd_dcn_obj365_dropblock_iouloss']

**Comment by baigang666** [comment]
c++下的配置文件如下：
DEPLOY:
    USE_GPU: 1
    MODEL_PATH: "F:/PaddleDetection-master2019/inference/model/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco"
    MODEL_FILENAME: "__model__"
    PARAMS_FILENAME: "__params__"
    RESIZE_TYPE: "UNPADDING_SCALING"
    EVAL_CROP_SIZE: (1280, 1280)
    TARGET_SHORT_SIZE : 1280
    RESIZE_MAX_SIZE: 1280
    #归一化
    MEAN:  [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    #图像类型
    IMAGE_TYPE: "rgb"
    #图像通道数
    CHANNELS : 3
    #图像分类的类别数
    NUM_CLASSES: 80
     # 含义：预处理方式，目前提供图像检测的通用预处理类DetectionPreProcessor.
    PRE_PROCESSOR: "DetectionPreProcessor"
    #预测模式
    PREDICTOR_MODE: "ANALYSIS"
    #每次预测的batch_size
    BATCH_SIZE : 1 
    #输入张量的个数。大部分模型不需要设置。默认值为1
    FEEDS_SIZE: 2

**Comment by baigang666** [comment]
DEPLOY:
    USE_GPU: 1
    MODEL_PATH: "F:/PaddleDetection-master2019/inference/model/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco"
    MODEL_FILENAME: "__model__"
    PARAMS_FILENAME: "__params__"
    RESIZE_TYPE: "UNPADDING_SCALING"
    EVAL_CROP_SIZE: (1280, 1280)
    TARGET_SHORT_SIZE : 1280
    RESIZE_MAX_SIZE: 1280
    #归一化
    MEAN:  [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    #图像类型
    IMAGE_TYPE: "rgb"
    #图像通道数
    CHANNELS : 3
    #图像分类的类别数
    NUM_CLASSES: 80
     # 含义：预处理方式，目前提供图像检测的通用预处理类DetectionPreProcessor.
    PRE_PROCESSOR: "DetectionPreProcessor"
    #预测模式
    PREDICTOR_MODE: "ANALYSIS"
    #每次预测的batch_size
    BATCH_SIZE : 1 
    #输入张量的个数。大部分模型不需要设置。默认值为1
    FEEDS_SIZE: 2

**Comment by willthefrog** [comment]
可否提供下运行的命令及其输出？

**Comment by baigang666** [comment]
@willthefrog  2019 c++编译后运行的那个命令呀？ 您那边可以出来检测结果么？

**Comment by willthefrog** [comment]
请提供export_model.py和cpp_infer.py运行的具体命令及输出结果。

**Comment by baigang666** [comment]
@willthefrog 我在python下利用export_model.py导出模型，然后利用cpp_infer.py推理，也检测成功了，但是在C++下部署的时候还是得不到检测结果。以下是我的C++下的yaml文件，可以帮忙看一下是否正确么？
DEPLOY:
USE_GPU: 1
MODEL_PATH: "F:/PaddleDetection-master2019/inference/model/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco"
MODEL_FILENAME: "model"
PARAMS_FILENAME: "params"
RESIZE_TYPE: "UNPADDING_SCALING"
EVAL_CROP_SIZE: (1280, 1280)
TARGET_SHORT_SIZE : 1280
RESIZE_MAX_SIZE: 1280
#归一化
MEAN: [0.485, 0.456, 0.406]
STD: [0.229, 0.224, 0.225]
#图像类型
IMAGE_TYPE: "rgb"
#图像通道数
CHANNELS : 3
#图像分类的类别数
NUM_CLASSES: 80
# 含义：预处理方式，目前提供图像检测的通用预处理类DetectionPreProcessor.
PRE_PROCESSOR: "DetectionPreProcessor"
#预测模式
PREDICTOR_MODE: "ANALYSIS"
#每次预测的batch_size
BATCH_SIZE : 1
#输入张量的个数。大部分模型不需要设置。默认值为1
FEEDS_SIZE: 2

**Comment by baigang666** [comment]
@willthefrog 
![微信图片_20200423105246](https://user-images.githubusercontent.com/15216518/80053927-a6c49380-8550-11ea-8d67-050bcd03a61a.png)

**Comment by willthefrog** [comment]
改成
```yaml
RESIZE_TYPE: "UNPADDING"
EVAL_CROP_SIZE: (608, 608)
```
试下呢？

**Comment by baigang666** [comment]
@willthefrog 还是同样的结果，求解  大神。谢谢

**Comment by willthefrog** [comment]
@sjtubinlong 能否帮忙看下？

**Comment by sjtubinlong** [comment]
@baigang666 试试最新的master分支的代码来export_model以及c++预测

**Comment by baigang666** [comment]
@willthefrog @sjtubinlong 我用的就是最新的版本，还是同样的结果。。。。求解，大神

**Comment by Channingss** [comment]
@baigang666 请问后来使用cpp_infer.py来推理ok了，是改了哪个地方吗？能把cpp_infer.py跑通的yml配置文件内容再贴一下吗？

**Comment by baigang666** [comment]
@willthefrog @sjtubinlong 
# demo for cpp_infer.py

use_python_inference: false # whether to use python inference
mode: fluid # trt_fp32, trt_fp16, trt_int8, fluid
arch: YOLO # YOLO, SSD, RCNN, RetinaNet
min_subgraph_size: 3 # need 3 for YOLO arch

# visualize the predicted image
metric: COCO # COCO, VOC
draw_threshold: 0.2

Preprocess:
- type: Resize
  target_size: 1280
  max_size: 1280
- type: Normalize
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  is_scale: False
- type: Permute
  to_bgr: True（以前是False，后来改成True,python的cpp_infer.py就可以正尝推理了）
- type: PadStride
  stride: 0 # set 32 on FPN and 128 on RetinaNet

**Comment by baigang666** [comment]
@sjtubinlong @willthefrog 
# demo for cpp_infer.py

use_python_inference: false # whether to use python inference
mode: fluid # trt_fp32, trt_fp16, trt_int8, fluid
arch: YOLO # YOLO, SSD, RCNN, RetinaNet
min_subgraph_size: 3 # need 3 for YOLO arch

......# visualize the predicted image
metric: COCO # COCO, VOC
draw_threshold: 0.2

Preprocess:
- type: Resize
  target_size: 1280
  max_size: 1280
- type: Normalize
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  is_scale: False
- type: Permute
  to_bgr: True（以前是False，后来改成True,python的cpp_infer.py就可以正尝推理了）
- type: PadStride
  stride: 0 # set 32 on FPN and 128 on RetinaNet

**Comment by mingmmq** [comment]
> @sjtubinlong @willthefrog
> 
> # demo for cpp_infer.py
> use_python_inference: false # whether to use python inference
> mode: fluid # trt_fp32, trt_fp16, trt_int8, fluid
> arch: YOLO # YOLO, SSD, RCNN, RetinaNet
> min_subgraph_size: 3 # need 3 for YOLO arch
> 
> ......# visualize the predicted image
> metric: COCO # COCO, VOC
> draw_threshold: 0.2
> 
> Preprocess:
> 
> * type: Resize
>   target_size: 1280
>   max_size: 1280
> * type: Normalize
>   mean:
>   
>   * 0.485
>   * 0.456
>   * 0.406
>     std:
>   * 0.229
>   * 0.224
>   * 0.225
>     is_scale: False
> * type: Permute
>   to_bgr: True（以前是False，后来改成True,python的cpp_infer.py就可以正尝推理了）
> * type: PadStride
>   stride: 0 # set 32 on FPN and 128 on RetinaNet

实际起作用的是 **is_scale: False** 而不是 **to_bgr: True**,
你一次改了两个东西。obj365 以及 自己训练的时候，都没有scale，所以这里也不该scale的。

**Comment by qingqing01** [comment]
@mingmmq @baigang666  最新的master分支(即将发布release 0.3)Python, C++预测，测试增强YOLOv3和普通YOLOv3，目前都没问题。这个scale的问题，确实需要注意，我们后续更新模型时会考虑重新训练使得统一。

**Comment by qingqing01** [comment]
最新版的Python和C++测试均没有问题了， https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/deploy  因此关闭此issue

**Comment by JensenHJS** [comment]
请问，下载pddetection代码，编译paddle c++库，没有错误后下面这部如何进行？
readme中step5如下，但是编译后的paddle/build文件夹下没有main这个文件
###########################################
预测及可视化
编译成功后，预测入口程序为`build/main`其主要命令参数说明如下：
|  参数   | 说明  |
|  ----  | ----  |
| model_dir  | 导出的预测模型所在路径 |
| image_path  | 要预测的图片文件路径 |
| video_path  | 要预测的视频文件路径 |
| use_gpu  | 是否使用 GPU 预测, 支持值为0或1(默认值为0)|
| --run_mode |使用GPU时，默认为fluid, 可选（fluid/trt_fp32/trt_fp16）|

**注意**：如果同时设置了`video_path`和`image_path`，程序仅预测`video_path`。

**Comment by JensenHJS** [comment]
请问，下载pddetection代码，编译paddle c++库，没有错误后下面这部如何进行？
readme中step5如下，但是编译后的paddle/build文件夹下没有main这个文件
###########################################
预测及可视化
编译成功后，预测入口程序为`build/main`其主要命令参数说明如下：
|  参数   | 说明  |
|  ----  | ----  |
| model_dir  | 导出的预测模型所在路径 |
| image_path  | 要预测的图片文件路径 |
| video_path  | 要预测的视频文件路径 |
| use_gpu  | 是否使用 GPU 预测, 支持值为0或1(默认值为0)|
| --run_mode |使用GPU时，默认为fluid, 可选（fluid/trt_fp32/trt_fp16）|

**注意**：如果同时设置了`video_path`和`image_path`，程序仅预测`video_path`。
`样例一`：
```shell
#不使用`GPU`测试图片 `/root/projects/images/test.jpeg`  
./build/main --model_dir=/root/projects/models/yolov3_darknet --image_path=/root/projects/images/test.jpeg
```
