### ISSUE TITLE
PPYOLO训练的模型得不到检测结果

### ISSUE THREAD

**Issue by TTgogogo** [PaddlePaddle/PaddleDetection#5391]
yolov3和mask rcnn都能得到检测结果，但ppyolo检测不到结果，请问会是什么原因？

**Comment by qingqing01** [comment]
您用的2.3最新版训练吗？训练mAP如何呢？也很差吗？

**Comment by TTgogogo** [comment]
@qingqing01 是用的2.3release版本，是版本不对吗？

**Comment by pengyuanzhang666** [comment]
请问解决了吗我也遇到了同样的问题
