### ISSUE TITLE
多尺度测试

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#5392]
您好，怎么在deploy中应用多尺度测试？或者 在infer进行测试时候使用TTA？

**Comment by nemonameless** [comment]
[#4377](https://github.com/PaddlePaddle/PaddleDetection/pull/4377)   [#5287](https://github.com/PaddlePaddle/PaddleDetection/issues/5287)  
deploy下本身是为了高效部署，不建议多尺度测试。
infer是使用tools/infer.py，多尺度配置需要参照 [configs/faster_rcnn/faster_rcnn_r34_fpn_multiscaletest_1x_coco.yml](https://github.com/PaddlePaddle/PaddleDetection/pull/4377/files#diff-1ca0056fad63d522e51b2846e358323bb0c9cf7e76c11894ffc5180a6427d403)
