### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by PUSSKI** [PaddlePaddle/PaddleDetection#5396]
我使用pyinstaller将预测脚本打包成为exe，可是它运行启动非常慢，一个一分钟的视频，检测出结果花了三个多小时，请问这是什么原因呢？有什么解决办法吗？
![image](https://user-images.githubusercontent.com/98137099/158932514-4ea93ac1-3d94-4eec-8e03-87f5214897fb.png)
![image](https://user-images.githubusercontent.com/98137099/158932579-a3211b2e-c7d7-4f84-8bc1-20c109767946.png)
![image](https://user-images.githubusercontent.com/98137099/158932600-57b66ad8-ee17-4b70-b437-924eff516ccb.png)
![image](https://user-images.githubusercontent.com/98137099/158932733-ae9e0bf8-ae08-4457-b457-4e705e36eb8b.png)

**Comment by heavengate** [comment]
是不是你运行的时候没有用到GPU，只使用了CPU，导致比价慢
