### ISSUE TITLE
[Other General Issues]请问如何打印模型的flops？

### ISSUE THREAD

**Issue by RhythmF** [PaddlePaddle/PaddleDetection#5400]
环境是最新的AI Studio，请问下打印flops的代码怎么用？
还有就是只能训练的时候打印吗？以及训练好的模型是否能够计算flops？
谢谢

**Comment by heavengate** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/summary_cn.html#summary
可以用这个接口试下
