### ISSUE TITLE
develop版本训练ppyoloe报错

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleDetection#5406]
尝试使用develop版本训练ppyoloe，使用的是voc数据集，只修改了configs中的数据集部分，其他保持默认，报错如下。相同数据集训练yolov3是正常的，请问该怎么解决？
![X86AO$J2F7EPV4NC8IM7_8](https://user-images.githubusercontent.com/53975909/159129919-e94b4371-84f9-4e96-a2db-86626540900f.png)

**Comment by yghstill** [comment]
@Monday-Leo PaddlePaddle版本是多少？更新至2.2.2试下呢？

**Comment by Monday-Leo** [comment]
原来的版本是2.2.0，更新为2.2.2后还是相同的报错，没有解决。

**Comment by Monday-Leo** [comment]
在ppyoloe_reader.yml文件中：

TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - PadGT: {}

有这个PadGT，看处理的代码应该是这一个函数出了问题，但不知道该怎么解决。

**Comment by wangxinxin08** [comment]
fixed by https://github.com/PaddlePaddle/PaddleDetection/pull/5412
