### ISSUE TITLE
tiny-pose安卓模型代码运行：Wrong broadcast type是什么错误？怎么解决？

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#5408]
A/Paddle-Lite: [F 11/ 1 18: 0:58.555 .../lite/kernels/host/elementwise_op_func.h:339 Update] Wrong broadcast type
E/libc++abi: terminating with uncaught exception of type paddle::lite::PaddleLiteException: Paddle-Lite C++ Exception: 
    [F 11/ 1 18: 0:58.555 .../lite/kernels/host/elementwise_op_func.h:339 Update] Wrong broadcast type
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 11084 (GLThread 218), pid 11035 (ction.detection)

**Comment by jackwysxw** [comment]
最后怎么处理的？

**Comment by Pius-Z** [comment]
> A/Paddle-Lite: [F 11/ 1 18: 0:58.555 .../lite/kernels/host/elementwise_op_func.h:339 Update] Wrong broadcast type E/libc++abi: terminating with uncaught exception of type paddle::lite::PaddleLiteException: Paddle-Lite C++ Exception: [F 11/ 1 18: 0:58.555 .../lite/kernels/host/elementwise_op_func.h:339 Update] Wrong broadcast type A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 11084 (GLThread 218), pid 11035 (ction.detection)

请问最后怎么解决的？
