### ISSUE TITLE
[Other General Issues]百度AI STUDIO上【PaddleDetection2.0专项】新版本快速体验项目直接在NOTEBOOK运行报错

### ISSUE THREAD

**Issue by 13136983989** [PaddlePaddle/PaddleDetection#5415]
运行到这句话就会报错 
![image](https://user-images.githubusercontent.com/42019021/159213029-a2697f21-e851-4ee8-a0e7-567a1456b283.png)

![image](https://user-images.githubusercontent.com/42019021/159212997-59079b6f-d706-4470-8a1c-9283ddc9fb91.png)

**Comment by wangxinxin08** [comment]
应该是PaddleDetection的版本不对，一些模型不包含，可以拉取最新的PaddleDetection release/2.3试下
