### ISSUE TITLE
训练picodet时coco_detection.yml填写时如何能并行加入多组数据集

### ISSUE THREAD

**Issue by xiangfeidecao** [PaddlePaddle/PaddleDetection#5422]
训练picodet时coco_detection.yml填写时目前只能填写一组数据集，当我有多组数据集，并且不能整合成一组时，有什么方式可以填写多组数据集？目前paddleocr中训练都可以填写多个label_list.然后用ratio指定数据集的使用比例。

**Comment by lyuwenyu** [comment]
目前ppdet里不支持多个数据集  我反馈下  也可以直接在 ppdet/data/source里修改相应的文件

**Comment by July-zh** [comment]
请问这个问题解决了吗？

**Comment by July-zh** [comment]
> 训练picodet时coco_detection.yml填写时目前只能填写一组数据集，当我有多组数据集，并且不能整合成一组时，有什么方式可以填写多组数据集？目前paddleocr中训练都可以填写多个label_list.然后用ratio指定数据集的使用比例。
请问这个问题解决了吗？

**Comment by July-zh** [comment]
> 训练picodet时coco_detection.yml填写时目前只能填写一组数据集，当我有多组数据集，并且不能整合成一组时，有什么方式可以填写多组数据集？目前paddleocr中训练都可以填写多个label_list.然后用ratio指定数据集的使用比例。

请问你有解决这个问题吗
