### ISSUE TITLE
debug下“debug assertion failed”

### ISSUE THREAD

**Issue by TTgogogo** [PaddlePaddle/PaddleDetection#5446]
qt环境下运行paddle出现debug assertion failed对话框，提示yaml-cppd.dll，debug_heap.cpp Line 996错误，Expression: _acrt_first_block == header
麻烦帮助找到什么原因，release模式下没有这个错误。

**Comment by ghostxsl** [comment]
请完善一下详细的版本信息，运行命令以及报错信息，方便定位问题
