### ISSUE TITLE
[BUG]在使用paddleDetection时候，使用VOC数据集导出的模型的infer_info的label_list与正常一样，但是每次使用COCO数据集，指点数据集的位置和分类的种类数目，但是每次导出模型的infer_info的label_list都是80个，且模型无效，不能预测出测试集的目标。

### ISSUE THREAD

**Issue by Craw-B** [PaddlePaddle/PaddleDetection#5448]
在我的coco数据集的格式如下
metric: COCO
num_classes: 4

TrainDataset:
  !COCODataSet
    image_dir: images
    anno_path: annotations/train.json
    dataset_dir: dataset/roadsign_coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: images
    anno_path: annotations/valid.json
    dataset_dir: dataset/roadsign_coco

TestDataset:
  !ImageFolder
    anno_path: annnotations/valid.json
但是导出模型就先80个，而且无法进行预测和部署
如下
mode: fluid
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: false
arch: SSD
min_subgraph_size: 60
Preprocess:
- interp: 1
  keep_ratio: false
  target_size:
  - 300
  - 300
  type: Resize
- is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: NormalizeImage
- type: Permute
label_list:
- person
- bicycle
- car
- motorcycle
- airplane
- bus
- train
- truck
- boat
- traffic light
- fire hydrant
- stop sign
- parking meter
- bench
- bird
- cat
- dog
- horse
- sheep
- cow
- elephant
- bear
- zebra
- giraffe
- backpack
- umbrella
- handbag
- tie
- suitcase
- frisbee
- skis
- snowboard
- sports ball
- kite
- baseball bat
- baseball glove
- skateboard
- surfboard
- tennis racket
- bottle
- wine glass
- cup
- fork
- knife
- spoon
- bowl
- banana
- apple
- sandwich
- orange
- broccoli
- carrot
- hot dog
- pizza
- donut
- cake
- chair
- couch
- potted plant
- bed
- dining table
- toilet
- tv
- laptop
- mouse
- remote
- keyboard
- cell phone
- microwave
- oven
- toaster
- sink
- refrigerator
- book
- clock
- vase
- scissors
- teddy bear
- hair drier
- toothbrush

**Comment by ghostxsl** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/datasets/coco_detection.yml#L19
更换指定anno_path内的json文件里的标注类别名称

**Comment by Craw-B** [comment]
你的意思时写成拒绝路径对吗，按照这个coco_detection的例子他不是绝对路经啊。我不太懂你的意思，我如果要用自己的coco数据应该怎么办，能给我一个具体的指导意见吗，卡了好几天了

**Comment by ghostxsl** [comment]
如果你没有指定anno_file，框架会默认加载coco的类别标签，参考：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/engine/trainer.py#L545

**Comment by ghostxsl** [comment]
anno_file得写成绝对路径，要么你就直接在代码里改也行，参考：https://github.com/PaddlePaddle/PaddleDetection/blob/b615336fe3a9ff740fdb1b889be7bc865b6d20fa/ppdet/data/source/category.py#L29
