### ISSUE TITLE
请问配置文件中的置信度阈值是哪个呀，是配置文件中的 score_threshold嘛？谢谢

### ISSUE THREAD

**Issue by learning-boy** [PaddlePaddle/PaddleDetection#545]

**Comment by learning-boy** [comment]
控制筛选预测框的那个，达不到规定的值不予标注，请问是哪个，谢谢

**Comment by heavengate** [comment]
eval的时候是这里配置的
https://github.com/PaddlePaddle/PaddleDetection/blob/a6ab91d5896a48a7ee7669aef9d13646e6d7b8ac/configs/yolov3_darknet.yml#L35

infer的话脚本里有`--draw_thresh` 参数

**Comment by learning-boy** [comment]
好的，谢谢您的回复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kaipeng Deng <notifications@github.com&gt;
发送时间: 2020年4月24日 10:36
收件人: PaddlePaddle/PaddleDetection <PaddleDetection@noreply.github.com&gt;
抄送: learning-boy <1342346303@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[PaddlePaddle/PaddleDetection] 请问配置文件中的置信度阈值是哪个呀，是配置文件中的 score_threshold嘛？谢谢 (#545)





 
eval的时候是这里配置的
 https://github.com/PaddlePaddle/PaddleDetection/blob/a6ab91d5896a48a7ee7669aef9d13646e6d7b8ac/configs/yolov3_darknet.yml#L35
 
infer的话脚本里有--draw_thresh 参数

**Comment by heavengate** [comment]
鉴于问题已经解决，当前issue先关闭了，如果还有问题可以reopen此issue或者提新的issue，我们将在第一时间回复~
