### ISSUE TITLE
源代码

### ISSUE THREAD

**Issue by Craw-B** [PaddlePaddle/PaddleDetection#5454]
我想找paddle的源代码，比如如何实现yolo或者SSD。官方是否提供了这些源代码以供我们学习

**Comment by ghostxsl** [comment]
yolo: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/architectures/yolo.py
ssd: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/architectures/ssd.py
具体的代码细节可以自己查看
