### ISSUE TITLE
[Other General Issues]

### ISSUE THREAD

**Issue by QL-AR** [PaddlePaddle/PaddleDetection#5457]
请问怎么映射中文标签？

**Comment by nemonameless** [comment]
[#4912](https://github.com/PaddlePaddle/PaddleDetection/issues/4912)
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/utils/visualizer.py#L123   改动这一行就可以

**Comment by QL-AR** [comment]
怎么显示中文标签？

**Comment by QL-AR** [comment]
怎么训练中文标签？
