### ISSUE TITLE
 Cannot find fetched variable(im_id).

### ISSUE THREAD

**Issue by ellinyang** [PaddlePaddle/PaddleDetection#546]
运行环境：
Linux 16.06/ NVIDIA P4 /CUDA9,cudnn7.0
paddle版本:1.7.1_cuda9_cudnn7.0
paddleDetection release/0.2
复现情况：
基于PaddleDetection跑faster_rcnn_r50_fpn_2x时，默认的start() 和 reset() 数据读取过程训练、评估正常。
因为业务需要通过for-range的方法循环迭代输出数据，feed进模型。于是将 fluid.io.DataLoader 中的iterable 改为 True。这么改训练正常，但是训练中运行eval_run时会报错。已确认将reader.yml里的iterable改为true，data输出正常。辛苦paddle同学看一下。
train.py中修改：
![image](https://user-images.githubusercontent.com/20673237/80171812-f1f8a800-861d-11ea-92cb-309aaaebab09.png)
eval_run中修改：
![image](https://user-images.githubusercontent.com/20673237/80172930-e65ab080-8620-11ea-907d-1c74e3bd41b5.png)

错误日志如下：
I0424 10:57:04.039811 34768 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I0424 10:57:04.073230 34768 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0424 10:57:04.147104 34768 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0424 10:57:04.171646 34768 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
2020-04-24 10:57:05,668-INFO: iter: 0, lr: 0.006667, 'loss_cls': '3.527403', 'loss_bbox': '0.032837', 'loss_rpn_cls': '0.692826', 'loss_rpn_bbox': '0.102103', 'loss': '4.355169', time: 25.332, eta: 21:06:37
2020-04-24 10:57:25,907-INFO: iter: 20, lr: 0.007200, 'loss_cls': '1.405681', 'loss_bbox': '0.330584', 'loss_rpn_cls': '0.642447', 'loss_rpn_bbox': '0.052094', 'loss': '2.438134', time: 1.041, eta: 0:51:43
2020-04-24 10:57:45,843-INFO: iter: 40, lr: 0.007733, 'loss_cls': '1.382848', 'loss_bbox': '0.209869', 'loss_rpn_cls': '0.612721', 'loss_rpn_bbox': '0.086118', 'loss': '2.293122', time: 1.022, eta: 0:50:23
2020-04-24 10:57:55,730-INFO: Save model to /home/lj/data/objectDet/paddle-job-79090-0/work_dirs/faster_rcnn_r50_fpn_2x_fluid171_02_20200422_1/faster_rcnn_r50_fpn_2x_79090/50.
> /home/lj/DLcode/PaddleDetection/tools/train_feeder.py(89)eval_run_feeder()
-> for it, data in enumerate(loader()):
(Pdb) c
I0424 10:58:15.984709 34768 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I0424 10:58:15.994505 34768 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train_feeder.py", line 437, in <module>
    main()
  File "tools/train_feeder.py", line 358, in main
    resolution=resolution)
  File "tools/train_feeder.py", line 89, in eval_run_feeder
    for it, data in enumerate(loader()):
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/root/miniconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 843, in _run_impl
    return_numpy=return_numpy)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 677, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::details::FastThreadedSSAGraphExecutor::InsertFetchOps(std::vector<std::string, std::allocator<std::string> > const&, std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*, std::unordered_map<std::string, std::vector<paddle::framework::details::VarHandleBase*, std::allocator<paddle::framework::details::VarHandleBase*> >, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::vector<paddle::framework::details::VarHandleBase*, std::allocator<paddle::framework::details::VarHandleBase*> > > > >*, std::unordered_map<paddle::framework::details::OpHandleBase*, std::atomic<int>, std::hash<paddle::framework::details::OpHandleBase*>, std::equal_to<paddle::framework::details::OpHandleBase*>, std::allocator<std::pair<paddle::framework::details::OpHandleBase* const, std::atomic<int> > > >*, std::vector<paddle::framework::details::OpHandleBase*, std::allocator<paddle::framework::details::OpHandleBase*> >*, std::vector<paddle::framework::details::OpHandleBase*, std::allocator<paddle::framework::details::OpHandleBase*> >*)
3   paddle::framework::details::FastThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&)
4   paddle::framework::details::ScopeBufferedMonitor::Apply(std::function<void ()> const&, bool)
5   paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&)
6   paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&)

----------------------
Error Message Summary:
----------------------
PreconditionNotMetError: Cannot find fetched variable(im_id). Perhaps the main_program is not set to ParallelExecutor.
  [Hint: Expected fetched_var_it != fetched_vars->end(), but received fetched_var_it == fetched_vars->end().] at (/paddle/paddle/fluid/framework/details/fast_threaded_ssa_graph_executor.cc:147)

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/a6ab91d5896a48a7ee7669aef9d13646e6d7b8ac/tools/eval.py#L102
可以试下把这行直接改成
```
compile_program = prog
```

**Comment by ellinyang** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/a6ab91d5896a48a7ee7669aef9d13646e6d7b8ac/tools/eval.py#L102
> 
> 
> 可以试下把这行直接改成
> ```
> compile_program = prog
> ```

改之后，偶尔成功，偶尔又会报下面的错误？请问是什么原因？

I0424 15:07:54.324955 36271 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I0424 15:07:54.358475 36271 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0424 15:07:54.433758 36271 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0424 15:07:54.458595 36271 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
2020-04-24 15:07:55,597-INFO: iter: 0, lr: 0.006667, 'loss_cls': '3.331507', 'loss_bbox': '0.027822', 'loss_rpn_cls': '0.689008', 'loss_rpn_bbox': '0.088898', 'loss': '4.137236', time: 0.818, eta: 0:40:54
2020-04-24 15:08:16,722-INFO: iter: 20, lr: 0.007200, 'loss_cls': '1.277817', 'loss_bbox': '0.028217', 'loss_rpn_cls': '0.641183', 'loss_rpn_bbox': '0.167512', 'loss': '2.505414', time: 1.069, eta: 0:53:05
/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train_feeder.py", line 377, in <module>
    main()
  File "tools/train_feeder.py", line 256, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values, feed=data)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/root/miniconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 843, in _run_impl
    return_numpy=return_numpy)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 677, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   void paddle::operators::GPUGather<float, int>(paddle::platform::DeviceContext const&, paddle::framework::Tensor const&, paddle::framework::Tensor const&, paddle::framework::Tensor*)
3   paddle::operators::CUDAGenerateProposalsKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
4   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDAGenerateProposalsKernel<paddle::platform::CUDADeviceContext, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::details::ComputationOpHandle::RunImpl()
9   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
10  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
11  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
12  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
13  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/layers/detection.py", line 2814, in generate_proposals
    'RpnRoiProbs': rpn_roi_probs})
  File "/home/lj/DLcode/PaddleDetection/ppdet/core/workspace.py", line 150, in partial_apply
    return op(*args, **kwargs_)
  File "/home/lj/DLcode/PaddleDetection/ppdet/modeling/anchor_heads/rpn_head.py", line 438, in _get_single_proposals
    variances=self.anchor_var)
  File "/home/lj/DLcode/PaddleDetection/ppdet/modeling/anchor_heads/rpn_head.py", line 462, in get_proposals
    fpn_feat, im_info, lvl, mode)
  File "/home/lj/DLcode/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 100, in build
    rois = self.rpn_head.get_proposals(body_feats, im_info, mode=mode)
  File "/home/lj/DLcode/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 240, in train
    return self.build(feed_vars, 'train')
  File "tools/train_feeder.py", line 126, in main
    train_fetches = model.train(feed_vars)
  File "tools/train_feeder.py", line 377, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: The index of gather_op should not be empty when the index's rank is 1.
  [Hint: Expected index.dims()[0] > 0, but received index.dims()[0]:0 <= 0:0.] at (/paddle/paddle/fluid/operators/gather.cu.h:82)
  [operator < generate_proposals > error]

**Comment by ellinyang** [comment]
另外，想问一下
1. realse/0.1中 exe.run(startup_prog) 放在compiled_eval_prog = fluid.compiler.CompiledProgram(eval_prog)之后，
realse/0.2放在compiled_train_prog = fluid.CompiledProgram(train_prog).with_data_parallel(...)之前，这个顺序有影响吗？
2.CompiledProgram的功能，为什么训练保留，测试要去掉？
 compiled_eval_prog = fluid.compiler.CompiledProgram(eval_prog)
 compiled_eval_prog = eval_prog

**Comment by jerrywgz** [comment]
训练偶然挂的问题，这个是训练时得到的proposals均超出了image_size的范围并被过滤掉了，导致某个batch为空，这里我们会再优化下尽可能避免这种情况，目前的解决方式有几种：1. 增大warmup轮数 2. 使用coco数据集上训好的rcnn模型做finetune，这种通常效果会比较明显

**Comment by ellinyang** [comment]
> rcnn模型做finetune，这种通常效果会比较

改为compiled_eval_prog = eval_prog后，训练成功时，效果很差，经常nan,或评估一直为空。

**Comment by heavengate** [comment]
把DataLoader修改为`iterable`的方式可能会有很多地方需要适配，比如说原来DataLoader返回的是一个dict，可以直接给`exe.run(feed`，现在是返回一个list，需要自己组装出一个dict，看你的代码里面没有做这个组装，所以`exe.run`读入数据会有问题，同时`iterable=True`的训练速度也是慢于Iterable=False的，您这边是什么场景必须使用`iterable=True`

**Comment by ellinyang** [comment]
> 把DataLoader修改为`iterable`的方式可能会有很多地方需要适配，比如说原来DataLoader返回的是一个dict，可以直接给`exe.run(feed`，现在是返回一个list，需要自己组装出一个dict，看你的代码里面没有做这个组装，所以`exe.run`读入数据会有问题，同时静态图`iterable=True`的训练速度也是慢于`Iterable=False`的，您这边是什么场景必须使用`iterable=True`

DataLoader修改为iterable=True，适配的地方不多，很方便。评估一直为空，是因为Faster_rcnn未加载预训练权重，默认用了yaml里的backbone的权重。修改之后，很快收敛了。

**Comment by heavengate** [comment]
鉴于问题解决，当前issue关闭，如果还有问题可以reopen此issue或再提新issue ~
