### ISSUE TITLE
转换模型会生成一个infer_cfg.yml，要修改里面的label_list，要在哪里先改？

### ISSUE THREAD

**Issue by TTgogogo** [PaddlePaddle/PaddleDetection#5461]
想修改label_list，如何生成一个具有新的label_list的infer_cfg.yaml?在哪里改？

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/engine/export_utils.py#L83
label_list是通过读取anno_file的配置，也就是你数据集配置里的TestDataset里的anno_path，修改anno_path即可。如果找不到anno_path默认是会加载coco80类。
