### ISSUE TITLE
使用多线程报错can't pickle paddle.fluid.core_avx.PaddleInferPredictor objects

### ISSUE THREAD

**Issue by klkkkkl** [PaddlePaddle/PaddleDetection#5465]
File "D:/ThunderDownload/paddle/local/work/test.py", line 262, in main
    det_threads.start()
  File "C:\Users\13603\Anaconda3\envs\paddle\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\13603\Anaconda3\envs\paddle\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\13603\Anaconda3\envs\paddle\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\13603\Anaconda3\envs\paddle\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle paddle.fluid.core_avx.PaddleInferPredictor objects

**Comment by zoooo0820** [comment]
能提供下复现代码和命令吗

**Comment by klkkkkl** [comment]
> 能提供下复现代码和命令吗

class PredictConfig():
    def __init__(self, model_dir):
        # parsing Yaml config for Preprocess
        deploy_file = os.path.join(model_dir, 'infer_cfg.yml')
        with open(deploy_file) as f:
            yml_conf = yaml.safe_load(f)
        self.arch = yml_conf['arch']
        self.preprocess_infos = yml_conf['Preprocess']
        self.min_subgraph_size = yml_conf['min_subgraph_size']
        self.labels = yml_conf['label_list']
        self.print_config()

    def print_config(self):
        print('%s: %s' % ('Model Arch', self.arch))
        for op_info in self.preprocess_infos:
            print('--%s: %s' % ('transform op', op_info['type']))


def get_test_images(infer_file):
    with open(infer_file, 'r') as f:
        dirs = f.readlines()
    images = []
    for dir in dirs:
        images.append(eval(repr(dir.replace('\n', ''))).replace('\\', '/'))
    assert len(images) > 0, "no image found in {}".format(infer_file)
    return images


def load_predictor(model_dir):
    config = Config(
        os.path.join(model_dir, 'model.pdmodel'),
        os.path.join(model_dir, 'model.pdiparams'))
    # initial GPU memory(M), device ID
    config.enable_use_gpu(2000, 0)
    # optimize graph and fuse op
    config.switch_ir_optim(True)
    # disable print log when predict
    config.disable_glog_info()
    # enable shared memory
    config.enable_memory_optim()
    # disable feed, fetch OP, needed by zero_copy_run
    config.switch_use_feed_fetch_ops(False)
    predictor = create_predictor(config)
    return predictor, config


def create_inputs(imgs, im_info):
    inputs = {}

    im_shape = []
    scale_factor = []
    if len(imgs) == 1:
        inputs['image'] = np.array((imgs[0],)).astype('float32')
        inputs['im_shape'] = np.array(
            (im_info[0]['im_shape'],)).astype('float32')
        inputs['scale_factor'] = np.array(
            (im_info[0]['scale_factor'],)).astype('float32')
        return inputs

    for e in im_info:
        im_shape.append(np.array((e['im_shape'],)).astype('float32'))
        scale_factor.append(np.array((e['scale_factor'],)).astype('float32'))

    inputs['im_shape'] = np.concatenate(im_shape, axis=0)
    inputs['scale_factor'] = np.concatenate(scale_factor, axis=0)

    imgs_shape = [[e.shape[1], e.shape[2]] for e in imgs]
    max_shape_h = max([e[0] for e in imgs_shape])
    max_shape_w = max([e[1] for e in imgs_shape])
    padding_imgs = []
    for img in imgs:
        im_c, im_h, im_w = img.shape[:]
        padding_im = np.zeros(
            (im_c, max_shape_h, max_shape_w), dtype=np.float32)
        padding_im[:, :im_h, :im_w] = img
        padding_imgs.append(padding_im)
    inputs['image'] = np.stack(padding_imgs, axis=0)
    return inputs


class Detector(object):

    def __init__(self,
                 pred_config,
                 model_dir):
        self.pred_config = pred_config
        self.predictor, self.config = load_predictor(model_dir)
        self.preprocess_ops = self.get_ops()

    def get_ops(self):
        preprocess_ops = []
        for op_info in self.pred_config.preprocess_infos:
            new_op_info = op_info.copy()
            op_type = new_op_info.pop('type')
            preprocess_ops.append(eval(op_type)(**new_op_info))
        return preprocess_ops

    def predict(self, inputs):
        # preprocess
        input_names = self.predictor.get_input_names()
        for i in range(len(input_names)):
            input_tensor = self.predictor.get_input_handle(input_names[i])
            input_tensor.copy_from_cpu(inputs[input_names[i]])

        # model prediction
        self.predictor.run()
        output_names = self.predictor.get_output_names()
        boxes_tensor = self.predictor.get_output_handle(output_names[0])
        np_boxes = boxes_tensor.copy_to_cpu()
        boxes_num = self.predictor.get_output_handle(output_names[1])
        np_boxes_num = boxes_num.copy_to_cpu()

        # postprocess
        results = []
        if reduce(lambda x, y: x * y, np_boxes.shape) < 6:
            results = {'boxes': np.zeros([]), 'boxes_num': [0]}
        else:
            results = {'boxes': np_boxes, 'boxes_num': np_boxes_num}
        return results


def det_image_preprocess(name, start_index, image_list, batch_size, preprocess_ops_det, queue_det):
    # print("Start " + name)
    index = 0
    length = len(image_list)

    while index < length:
        input_im_lst = []
        input_im_info_lst = []
        im_paths = image_list[index:index + batch_size]
        for im_path in im_paths:
            im, im_info = preprocess(im_path, preprocess_ops_det)
            input_im_lst.append(im)
            input_im_info_lst.append(im_info)
        inputs = create_inputs(input_im_lst, input_im_info_lst)
        queue_det.put([inputs, index + start_index])
        index = index + batch_size
    # print("Leave " + name)


def det_process(name,detector, batch_size, img_list, queue_det, result_path, queue_det_post):
    print("Start " + name)
    # pred_config = PredictConfig(det_model_path)
    # detector = Detector(pred_config, det_model_path)
    total_counts = int(len(img_list) / batch_size)
    predict_counts = 0
    c_results = {"result": []}
    multiclass_thres = [0.51, 0.49, 0.51, 0.43, 0.37, 0.67, 0.43, 0.0, 0.0, 0.0]  # ppyolo r50 reducepan mass anchor
    # multiclass_thres = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.0, 0.0, 0.0]

    while predict_counts < total_counts:
        # tt = time.time()
        inputs, index = queue_det.get()
        # print(index)
        batch_image_list = img_list[index:index+batch_size]
        image_ids = []
        for i in range(batch_size):
            image_ids.append(int(os.path.basename(batch_image_list[i]).split('.')[0]))
        # print('get_det:', time.time() - tt)

        # tt1 = time.time()
        det_np_result = detector.predict(inputs)
        # print('run_det:', time.time() - tt1)

        accum_num = 0
        for i in range(batch_size):
            im_bboxes_num = det_np_result['boxes_num'][i]

            if im_bboxes_num > 0:
                bbox_results = det_np_result['boxes'][accum_num:im_bboxes_num + accum_num, 2:]
                id_results = det_np_result['boxes'][accum_num:im_bboxes_num + accum_num, 0]
                score_results = det_np_result['boxes'][accum_num:im_bboxes_num + accum_num, 1]
                for idx in range(im_bboxes_num):
                    if (float(bbox_results[idx][2]) - float(bbox_results[idx][0])) >= 1 and int(
                            id_results[idx]) >= 0 and int(id_results[idx]) <= 9:
                        if float(score_results[idx]) >= multiclass_thres[int(id_results[idx])]:
                            width = float(bbox_results[idx][2]) - float(bbox_results[idx][0])
                            height = float(bbox_results[idx][3]) - float(bbox_results[idx][1])

                            c_results["result"].append({"image_id": image_ids[i],
                                                        "type": int(id_results[idx]) + 1,
                                                        # "score": round(float(score_results[idx]), 2),
                                                        "x": round(float(bbox_results[idx][0]),0),
                                                        "y": round(float(bbox_results[idx][1]),0),
                                                        "width": round(width,0),
                                                        "height": round(height,0),
                                                        "segmentation": []})

            accum_num = accum_num + im_bboxes_num

        predict_counts = predict_counts + 1
    queue_det_post.put(c_results)
    c_results_det = queue_det_post.get()
    with open(result_path, 'w') as ft:
        json.dump(c_results_det, ft)
    print("Leave " + name)



def main(infer_txt, result_path, det_model_path, batch_size=4, num_worker=4):
    # Init Det Preprocess Ops
    pred_config = PredictConfig(det_model_path)
    detector = Detector(pred_config, det_model_path)
    preprocess_ops_det = detector.get_ops()

    # Get Image List
    img_list = get_test_images(infer_txt)
    print('total images:', len(img_list))
    # total_img = len(img_list)
    # Create Multiprocessing. Note: Must use 'spawn'
    # 获取上下文
    manager = multiprocessing.get_context('spawn')
    queue_det = manager.Queue(4)
    queue_det_post = manager.Queue(1)

    # Create Det Process
    det_threads = manager.Process(target=det_process, args=("Det Process",detector, batch_size, img_list, queue_det, result_path, queue_det_post))

    # Create Det Dataloarder Process
    det_workers = int(num_worker)
    threads = []
    worker_step = int(len(img_list) / det_workers)
    for worker_id in range(det_workers):
        tmp_img_list = img_list[worker_id * worker_step: (worker_id + 1) * worker_step]
        threads.append(manager.Process(target=det_image_preprocess, args=("Det DataLoader Process-{}".format(worker_id), worker_id * worker_step, tmp_img_list, batch_size, preprocess_ops_det, queue_det,)))

    # All Process Start
    det_threads.start()
    for worker_id in range(num_worker):
        threads[worker_id].start()

    # Finish
    for worker_id in range(num_worker):
        threads[worker_id].join()
    det_threads.join()

**Comment by zct-cap** [comment]
大佬现在还报错吗

**Comment by simon-sxx** [comment]
@zct-cap @klkkkkl @zoooo0820 请问解决了吗
