### ISSUE TITLE
ppyolo-tiny 的 fpn 和 ppyolo的 fpn 有啥区别？

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#5467]
如题 ppyolo-tiny的 fpn  和 ppyolo的 fpn 不一样么 代码有点看不懂 有没有 注释说明啥的？

**Comment by command-z-z** [comment]
暂未找到相关ppyolo-tiny模型的详细讲解，请问官方能否提供下。
