### ISSUE TITLE
[Other General Issues]评估deepsort相关模型，指标显示大多为0，这是正常的吗？

### ISSUE THREAD

**Issue by ponyo-cho** [PaddlePaddle/PaddleDetection#5468]
IDF1  IDP  IDR Rcll Prcn  GT MT PT  ML     FP     FN IDs  FM    MOTA  MOTP IDt IDa IDm
MOT16-02 0.0% 0.0% 0.0% 0.0% 0.0%  54  0  0  54  19508  17793   0   0 -109.6%   NaN   0   0   0
MOT16-04 0.4% 0.4% 0.4% 0.6% 0.7%  83  0  0  83  42809  47256  15  22  -89.4% 0.448  11   9   5
MOT16-05 4.3% 4.8% 3.9% 6.1% 7.4% 125  0  7 118   5192   6402  34  42  -70.5% 0.404  31  17  19
MOT16-09 0.0% 0.0% 0.0% 0.0% 0.0%  25  0  0  25   5544   5257   0   0 -105.5%   NaN   0   0   0
MOT16-10 0.0% 0.0% 0.0% 0.0% 0.0%  54  0  0  54  13991  12318   0   0 -113.6%   NaN   0   0   0
MOT16-11 0.1% 0.1% 0.1% 0.2% 0.1%  69  0  0  69  10177   9159   0   0 -110.8% 0.407   1   0   1
MOT16-13 0.0% 0.0% 0.0% 0.0% 0.0% 107  0  0 107  12274  11450   0   0 -107.2%   NaN   0   0   0
OVERALL  0.4% 0.4% 0.4% 0.7% 0.7% 517  0  7 510 109495 109635  49  64  -98.6%   NaN  43  26  25

#-----------------#
使用python tools/eval_mot.py -c configs/mot/deepsort/deepsort_jde_yolov3_pplcnet.yml --scaled=True 指令评估deepsort相关模型，结果显示如上，是我中间漏掉了什么问题吗？ 求指教 谢谢~

**Comment by nemonameless** [comment]
运行jde_yolov3不需要 --scaled=True或设置为False，因为这个模型输出的坐标未缩放回原图尺寸。

**Comment by ponyo-cho** [comment]
> 运行jde_yolov3不需要 --scaled=True或设置为False，因为这个模型输出的坐标未缩放回原图尺寸。

问题很好的解决了，非常感谢您的回复！
