### ISSUE TITLE
fpn通道数 对应的是这样的么？

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#5469]
![417168168d254618fc2248eacb5a870](https://user-images.githubusercontent.com/88072901/160266051-ec83a377-aecc-48eb-9e34-ae7799fb2e81.png)

backbone 发的通道24,56,80, neck后 对应为 96 128 160这样的是吧

**Comment by qingqing01** [comment]
这个要依据具体模型来看，您也可以导出模型，通过Netron 或这 VisualDL可视化 https://www.paddlepaddle.org.cn/paddle/visualdl/demo/graph  来查看具体的通道数，比较清晰
