### ISSUE TITLE
c++部署，如何修改bbox的数量？ [Other General Issues]

### ISSUE THREAD

**Issue by wzy123456wzy** [PaddlePaddle/PaddleDetection#5471]
c++编译出来的main.exe，修改配置文件并没有生效，是我使用有误嘛？代码版本为2.3release
NMS:
  keep_top_k: 100
  name: MultiClassNMS
  nms_threshold: 0.5
  nms_top_k: 1
  score_threshold: 0.3
![image](https://user-images.githubusercontent.com/44393339/160285280-7d5a5877-590a-4dfe-9a33-43e19644bdfe.png)

**Comment by qingqing01** [comment]
NMS我们提供算子，需要导出前修改阈值、或者top-k的参数，不同阈值的含义可以参考下面注释，然后导出，再预测。

https://github.com/PaddlePaddle/PaddleDetection/blob/d3b5ecd54fdd1c9910c2f698b93e768a7be1da39/ppdet/modeling/ops.py#L903
