### ISSUE TITLE
[Other General Issues]模型训练的问题

### ISSUE THREAD

**Issue by Craw-B** [PaddlePaddle/PaddleDetection#5473]
## 描述问题
我在使用PaddleDetection0.5训练模型的时候，做目标检测任务的时候，识别一个物体的精准率和召回率为0

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
python3 tools/train.py -c configs/ssd/ssdlite_mobilenet_v1.yml -o use_gpu=false save_dir=/root/data/code/model --eval
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。
修改过配置文件的学习率和学习率调度器
3. 您使用的数据集是？
自定义数据集
5. 请提供您出现的报错信息及相关log。

![df0c2f1d51544e4be3cae1289693b45](https://user-images.githubusercontent.com/82355890/160319738-f9b2c593-2a94-4604-8556-f0f9e5bbbb0f.png)

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
0.5
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
linux
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
python=3.7.9   paddle=1.8.5 
7. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
cuda=10.0

**Comment by heavengate** [comment]
一般看前两个指标，分别是mAP(0.5:0.95)和mAP(0.5)，你框的两个是对小目标的准确度，ssdlite本身是个轻量级模型，在小目标上效果不好，如果需要小目标上效果好的话可以试下RCNN系列模型
