### ISSUE TITLE
[BUG][DOCS]关于PP-TinyPose

### ISSUE THREAD

**Issue by m00nLi** [PaddlePaddle/PaddleDetection#5475]
# 环境
- OS: Ubuntu 18.04
- PaddleDetection 版本： c04a6ff6|release/2.3
- Paddle-Lite:v2.10 通过 pip 安装: `pip install paddlelite`
- Paddle-Lite Armv8 Lib: [v2.10](https://github.com/PaddlePaddle/Paddle-Lite/releases/download/v2.10/inference_lite_lib.android.armv8.gcc.c++_static.with_extra.with_cv.tar.gz)
- 检测模型：[picodet_s_320_pedestrian.nb](https://bj.bcebos.com/v1/paddledet/models/keypoint/picodet_s_320_pedestrian.nb). 192x192 的模型也试过
- 关键点模型： [tinypose_256x192.nb](https://bj.bcebos.com/v1/paddledet/models/keypoint/tinypose_256x192.nb). 128x96 的模型也试过
- 使用的部署代码：[deploy/lite](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/lite)
  模型、代码还有一些部署配置 yml 文件，都是从你们给的链接下的，按照这里的readme流程走的。

# 问题
1. ARM 端实测效果极差。
`./main det_runtime_config.json`, 只跑检测模型，检测结果如下：
![result_000000014439](https://user-images.githubusercontent.com/102453574/160331768-d409a1ff-de2c-4e69-8eae-abc1e4d30c7c.jpg)
![result_hrnet_demo](https://user-images.githubusercontent.com/102453574/160332030-ee087492-e654-4065-8be7-58ce4bd64e61.jpg)
`./main keypoint_runtime_config.json`, 跑检测+关键点模型，完全检测不到：
![keypoint_000000014439](https://user-images.githubusercontent.com/102453574/160332399-6cdbca65-04fe-4943-a2fa-cc9f8a78bf76.jpg)
![keypoint_hrnet_demo](https://user-images.githubusercontent.com/102453574/160332448-e643fd4a-a3e7-4dbf-b46e-9b2a6211e528.jpg)
2. deploy/lite编译问题
按照`Paddle-Lite端侧部署`的流程走，前面只说了要准备好Android NDK(R17)以上版本，没说具体版本，要导出NDK_ROOT也没说（我自己导出的是ANDROID_NDK），我用NDK 24编译直接报错，你们的Makefile写法实测只支持NDK 22以下的版本。

3. 示例是怎样用的，参数怎么填？
`./main det_runtime_config.json` 中config.json实测是必须填的，但是提示：
`Usage: ./main [config_path](option) [image_dir](option)`, 必须填的怎么又是可选的呢？
一开始运行结果不对，查看输出发现：
`"Please set model arch,
 "support value : YOLO, SSD, RetinaNet, RCNN, Face."`，不支持你们的PicoDet？
![image](https://user-images.githubusercontent.com/102453574/160333387-74fff3f6-ce69-4bc4-8d6f-fd8965d8172d.png)
但再仔细看源码其实是有处理PicoDet的。
4. paddle-lite-arm 库怎么编译？
按照
![image](https://user-images.githubusercontent.com/102453574/160336085-866ce6d2-b5ad-4df0-8af7-ae63bf03ad12.png)
执行
`./lite/tools/build_android.sh --arch=armv8 --toolchain=clang --with_cv=ON --with_extra=ON`
无任何输出

**Comment by zhiboniu** [comment]
你好，我重新复现了一遍，文档和资料却是是有些缺失，我会尽快补上。
对于你这个问题，很明显没有正常推理，看你的资料大概可能有两个原因：
1）你用的lite库应该是fp32的，但是模型是fp16的，需要用fp16的lite库，lite页面第三个链接[arm8(FP16)](https://github.com/PaddlePaddle/Paddle-Lite/releases/download/v2.10-rc/inference_lite_lib.android.armv8_clang_c++_static_with_extra_with_cv_with_fp16.tiny_publish_427e46.zip)。
2）Picodet是可以支持的，print log里内容需要更新。注意每个模型对应的infer_cfg.json文件，模型链接里遗漏了这个文件，会尽快补充。
其他，NDK_ROOT设置缺失没有提醒，paddle-lite-arm这个命令之前确实是可以用的，但是lite也在不断更新，可能最近不支持了，lite编译还是以lite库官方为主。

**Comment by zhiboniu** [comment]
我这里测试4中命令仍然是有效的
<img width="795" alt="image" src="https://user-images.githubusercontent.com/31800336/160404160-d5937e9c-66ff-416a-a21b-cac2c98df4d9.png">

**Comment by m00nLi** [comment]
你好。1. 我下载的paddle-lite armv8库应该是fp32的，跑的模型也是fp32的，我用Netron查看模型，如果模型是fp16的话，输入层后面会是calib层，可以看到是__kernel_type_attr_fp32_to_fp16这些字样；而fp32模型则是一个scale层，应该是将输入除以255.0。所以我确定跑的库和模型都是fp32的。
2. paddle-lite库编译，我用现在最新的2.4再试一下。因为我还有其他的库是用较新的NDK 24.0.8215888编的，如果要用到paddle-lite库需要降到NDK 21的，不然会报错，所以想自己编译paddle-lite 库的。

**Comment by zhiboniu** [comment]
另外还需要注意一下用的infer_cfg.json需要与模型对应，模型导出的时候一起产生的，还会有十分fuse_normalize的选项，预处理也会不一样。

**Comment by m00nLi** [comment]
是模型的问题，你们之前给的链接下的模型，用Netron查看可知，包含了预处理，而代码里面又做了一遍同样的预处理，所以检测结果不对。
![image](https://user-images.githubusercontent.com/102453574/160524108-a4174bcd-f932-413d-8729-6f8411b65ab2.png)

**Comment by zhiboniu** [comment]
嗯，模型链接中增加了对应配置文件，已经更新到repo了
