### ISSUE TITLE
Paddle 那个模型 用了 CBAM注意力机制啊？

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#5476]
我看mobilenetv3 有SE模块 有没有 写 CBAM模块的 ？

**Comment by heavengate** [comment]
目前没有使用CBAM机制，我们会联合PM调研一下这个需求是否排期新增，另外如果你感兴趣也欢迎向PaddleDetection贡献~

**Comment by STUSER001** [comment]
> 目前没有使用CBAM机制，我们会联合PM调研一下这个需求是否排期新增，另外如果你感兴趣也欢迎向PaddleDetection贡献~

好的 ， 此外ppyolo-tiny 这个 没有详细 代码注释 之类的么 有些部分看不太明白

**Comment by song121982** [comment]
同求注意力机制
