### ISSUE TITLE
676类目标检测中的模型如何预测，能否给个demo？我用ResNet50-vd-FPN-Dcnv2预测报错

### ISSUE THREAD

**Issue by WanguoHou** [PaddlePaddle/PaddleDetection#5477]
我在学习676类目标检测模型，下载ResNet50-vd-FPN-Dcnv2模型后，在BML Codelab下运行如下命令：

aistudio@jupyter-696848-3621570:~/PaddleDetection/static$ python tools/infer.py -c configs/rcnn_enhance/generic/cascade_rcnn_dcn_r50_vd_fpn_gen_server_side.yml --infer_img=output/test/road554.png -o weights=models/cascade_rcnn_dcn_r50_vd_fpn_gen_server_side.pdparams

报错：
Traceback (most recent call last):
File "tools/infer.py", line 60, in
raise e
File "tools/infer.py", line 42, in
from ppdet.utils.eval_utils import parse_fetches
ModuleNotFoundError: No module named 'ppdet.utils.eval_utils'

麻烦帮我看看是出了什么问题或者给我一个demo？

另外我看ppdet.utils目录下存在eval_utils这个python文件，且PaddleDetection安装提示是成功
aistudio@jupyter-696848-3621570:~/PaddleDetection$ python ppdet/modeling/tests/test_architectures.py
W0328 11:37:09.326740 12939 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0328 11:37:09.332962 12939 device_context.cc:465] device: 0, cuDNN Version: 7.6.
.......
----------------------------------------------------------------------
Ran 7 tests in 3.942s

OK

**Comment by WanguoHou** [comment]
> 我在学习676类目标检测模型，下载ResNet50-vd-FPN-Dcnv2模型后，在BML Codelab下运行如下命令：
> 
> aistudio@jupyter-696848-3621570:~/PaddleDetection/static$ python tools/infer.py -c configs/rcnn_enhance/generic/cascade_rcnn_dcn_r50_vd_fpn_gen_server_side.yml --infer_img=output/test/road554.png -o weights=models/cascade_rcnn_dcn_r50_vd_fpn_gen_server_side.pdparams
> 
> 报错： Traceback (most recent call last): File "tools/infer.py", line 60, in raise e File "tools/infer.py", line 42, in from ppdet.utils.eval_utils import parse_fetches ModuleNotFoundError: No module named 'ppdet.utils.eval_utils'
> 
> 麻烦帮我看看是出了什么问题或者给我一个demo？
> 
> ## 另外我看ppdet.utils目录下存在eval_utils这个python文件，且PaddleDetection安装提示是成功
> aistudio@jupyter-696848-3621570:~/PaddleDetection$ python ppdet/modeling/tests/test_architectures.py
> W0328 11:37:09.326740 12939 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
> W0328 11:37:09.332962 12939 device_context.cc:465] device: 0, cuDNN Version: 7.6.
> .......
> Ran 7 tests in 3.942s
> 
> OK

**Comment by PFloyd0** [comment]
您好，请问您这个问题解决了吗，是怎么解决的。。。谢谢！

**Comment by ltm920716** [comment]
@PFloyd0 ,
pip uninstall paddledet

**Comment by GaoYangGF** [comment]
您好，那个大规模实用目标检测模型676个类别的那个，下面三个网络模型的配置文件都无法现在，有其他下载路径吗？
