### ISSUE TITLE
关于ppyoloe backbone 不懂得地方进行询问

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#5483]
在看ppyoloe的backbone cspresnet结果发现了一点疑问
<img width="599" alt="image" src="https://user-images.githubusercontent.com/78856426/160375396-6d03e2fd-7698-4701-9260-69acb9bf333d.png">
如图所述的的地方我看了一下这里定义了_**convert_to_deploy**_方法但是我并没有看到它在哪里应用呀，如果方便麻烦能否告诉我一下它的功能与在哪里作用

**Comment by ghostxsl** [comment]
这个函数是为了做重参数化的，只会在模型导出的时候调用，参考：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/engine/trainer.py#L650

**Comment by violetweir** [comment]
> 这个函数是为了做重参数化的，只会在模型导出的时候调用，参考：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/engine/trainer.py#L650

好的满麻烦您了
