### ISSUE TITLE
无法可视化loss曲线

### ISSUE THREAD

**Issue by terrancraft** [PaddlePaddle/PaddleDetection#5490]
## 描述问题

您好，我想启动visualdl来可视化我训练模型时的loss曲线，但web界面并没有返回结果(no visualized data)

## 使用的命令：
1. python -m paddle.distributed.launch tools/train.py --use_vdl True --vdl_log_dir vdl_log_dir/scalar **（*代表后面省略） 
2. visualdl --logdir ./vdl_log_dir/scalar/

## 返回的结果：
1. visualdl可以正常启动 web界面可以正常打开
2. vdl_log_dir/scalar下面出现vdlrecords文件
3. 但web界面显示"no visualized data"

## 环境/Environment
python 3.7 visualdl 2.2.3
paddle-gpu 2.2
PaddleDetection 2.3
cuda 11.2 cudnn 8.1

望解答～谢谢！

**Comment by wzh326** [comment]
请问解决了么？我也遇到了同样的问题

**Comment by zhaotun** [comment]
同样的问题
