### ISSUE TITLE
[Other General Issues]关于ppyoloe 验证步骤输入图像target_size大小限制的问题

### ISSUE THREAD

**Issue by Tongfengyu** [PaddlePaddle/PaddleDetection#5498]
验证读入图片resize到256会报错如下：
![屏幕截图 2022-03-29 152539](https://user-images.githubusercontent.com/82866148/160655539-8dbeb288-0155-4537-b76d-53d717bd79ff.png)
调到默认640，不会报错
![1](https://user-images.githubusercontent.com/82866148/160557226-7a99c0ed-c172-4c39-9a6f-93419296d5ce.png)
Q:1.不知道为什么，是输入图片不能太小吗？2.Y=[8400,2],第一维度的8400是什么意思，在哪定义的？

**Comment by lzh111222334** [comment]
+1，推理模型导出的时候也遇到这个问题

**Comment by jerrywgz** [comment]
目前ppyoloe如果要设置其他尺寸评估，除了修改EvalReader之外，还需要修改https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/_base_/ppyoloe_crn.yml#L31 中的eval_input_size为对应尺寸，或者不设置eval_input_size 这个我们后面再优化下

**Comment by Tongfengyu** [comment]
谢谢

**Comment by sdreamforchen** [comment]
您好。我在转ONNX模型的时候，提示了警告：Due to the operator:multiclass_nms3, the converted ONNX model will only supports input[batch_size] == 1；  我得到的onnx，我查看输入的维数为[-1,3,640,640]，下游环境对这个-1不能识别，比较悲催。请问可以在哪设置一下吗
