### ISSUE TITLE
训练时/ppdet/utils/eval_utils.py文件报错

### ISSUE THREAD

**Issue by chk218** [PaddlePaddle/PaddleDetection#550]
**环境**
Python版本：python3.7
框架版本：PaddlePaddle 1.7.1
PaddleDetection：release/0.2

报错信息：

`2020-04-25` 00:52:54,259-INFO: Save model to output/yolov3_mobilenet_v1_fruit_penyouzhui/200.

I0425 00:52:57.979563   717 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.

I0425 00:52:57.987470   717 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1

Traceback (most recent call last):

  File "tools/train.py", line 364, in <module>

    main()

  File "tools/train.py", line 285, in main

    resolution=resolution)

  File "/home/aistudio/work/PaddleDetection/ppdet/utils/eval_utils.py", line 161, in eval_run

    if 'Corner' in cfg.architecture and post_config is not None:

AttributeError: 'NoneType' object has no attribute 'architecture'

terminate called without an active exception`

**Comment by jerrywgz** [comment]
已修复
