### ISSUE TITLE
[BUG]使用剪裁+蒸馏联合策略时提示蒸馏模型没有加载均值标准差的属性

### ISSUE THREAD

**Issue by mengjing556** [PaddlePaddle/PaddleDetection#5502]
为什么我在使用剪裁+蒸馏的时候会报这个错误呢，我在配置文件当中已经配置了TestReader的参数。
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 118, in run
    trainer = Trainer(cfg, mode='train')
  File "D:\jupyter\PaddleDetectionExample\PaddleDetection\ppdet\engine\trainer.py", line 97, in __init__
    self.model.load_meanstd(cfg['TestReader']['sample_transforms'])
  File "D:\anaconda\envs\tensorflow2-4-gpu\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1110, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DistillModel' object has no attribute 'load_meanstd'
这是我在配置文件里面的配置（slim-config和config指定的配置文件都有写）。
TestReader:
  inputs_def:
    image_shape: [3, 512, 512]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [512, 512], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.418, 0.494, 0.447], std: [0.314, 0.270, 0.279], is_scale: True}
    - Permute: {}
  batch_size: 1

**Comment by mengjing556** [comment]
我使用的teacher_model是ppyolov2_r50vd_dcn，yml是ppyolov2_r50vd_dcn_365e_coco.yml。student_model是ppyolo_tiny_mbv3_large，yml是ppyolo_tiny_mbv3_large_coco.yml。

**Comment by mengjing556** [comment]
刚刚输出cfg也没有问题，但为什么model会没有这个属性呢。

**Comment by jiaowei123456** [comment]
你好请问pp-yolov2蒸馏怎么写配置文件？

**Comment by jiaowei123456** [comment]
@mengjing556 
你好，我也遇到这个问题：
![QQ截图20220407125657](https://user-images.githubusercontent.com/70888273/162123115-48446a69-8731-4971-82cb-f980f48884f4.png)
请问你解决了吗？望回复。
