### ISSUE TITLE
YOLOv3 output layer number not equal target number

### ISSUE THREAD

**Issue by joshuazm** [PaddlePaddle/PaddleDetection#551]
```
/opt/anaconda3/bin/anaconda/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, defaultdict
EvalReader:
  batch_size: 32
  bufsize: 32
  dataset: !COCODataSet
    anno_path: dx_val.json
    dataset_dir: dataset/dx
    image_dir: images/val2020
    sample_num: -1
    with_background: false
  drop_empty: false
  inputs_def:
    fields:
    - image
    - im_size
    - im_id
    image_shape:
    - 3
    - 608
    - 608
    num_max_boxes: 50
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !ResizeImage
    interp: 2
    max_size: 0
    target_size: 608
    use_cv2: true
  - !NormalizeImage
    is_channel_first: false
    is_scale: false
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  - !Permute
    channel_first: true
    to_bgr: false
  worker_num: 8
IouLoss:
  loss_weight: 2.5
  max_height: 608
  max_width: 608
LearningRate:
  [32mbase_lr[0m: 0.0001
  [32mschedulers[0m:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 55000
    - 75000
    values: null
  - !LinearWarmup
    start_factor: 0.0
    steps: 4000
OptimizerBuilder:
  [32mregularizer[0m:
    factor: 0.0005
    type: L2
  optimizer:
    momentum: 0.9
    type: Momentum
ResNet:
  [32mdcn_v2_stages[0m:
  - 5
  [32mfeature_maps[0m:
  - 3
  - 4
  - 5
  [32mfreeze_at[0m: 0
  [32mfreeze_norm[0m: false
  [32mnorm_type[0m: sync_bn
  [32mvariant[0m: d
  depth: 50
  gcb_params: {}
  gcb_stages: []
  nonlocal_stages: []
  norm_decay: 0.0
  weight_prefix_name: ''
TrainReader:
  batch_size: 16
  batch_transforms:
  - !RandomShape
    random_inter: true
    sizes:
    - 320
    - 352
    - 384
    - 416
    - 448
    - 480
    - 512
    - 544
    - 576
    - 608
  - !NormalizeImage
    is_channel_first: false
    is_scale: false
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  - !Permute
    channel_first: true
    to_bgr: false
  - !Gt2YoloTarget
    anchor_masks:
    - - 6
      - 7
      - 8
    - - 3
      - 4
      - 5
    - - 0
      - 1
      - 2
    anchors:
    - - 10
      - 13
    - - 16
      - 30
    - - 33
      - 23
    - - 30
      - 61
    - - 62
      - 45
    - - 59
      - 119
    - - 116
      - 90
    - - 156
      - 198
    - - 373
      - 326
    downsample_ratios:
    - 32
    - 16
    - 8
    num_classes: 80
  bufsize: 32
  dataset: !COCODataSet
    anno_path: dx_train.json
    dataset_dir: dataset/dx
    image_dir: images/train2020
    sample_num: -1
    with_background: false
  drop_last: true
  inputs_def:
    fields:
    - image
    - gt_bbox
    - gt_class
    - gt_score
    num_max_boxes: 50
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !RandomCrop
    allow_no_crop: true
    aspect_ratio:
    - 0.5
    - 2.0
    cover_all_box: false
    num_attempts: 50
    scaling:
    - 0.3
    - 1.0
    thresholds:
    - 0.0
    - 0.1
    - 0.3
    - 0.5
    - 0.7
    - 0.9
  - !RandomFlipImage
    is_mask_flip: false
    is_normalized: false
    prob: 0.5
  - !NormalizeBox {}
  - !PadBox
    num_max_boxes: 50
  - !BboxXYXY2XYWH {}
  shuffle: false
  use_fine_grained_loss: true
  use_process: true
  worker_num: 8
YOLOv3:
  [32mbackbone[0m: ResNet
  [32muse_fine_grained_loss[0m: false
  yolo_head: YOLOv3Head
YOLOv3Head:
  [32mdrop_block[0m: true
  [32mnms[0m:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01
  anchor_masks:
  - - 6
    - 7
    - 8
  - - 3
    - 4
    - 5
  - - 0
    - 1
    - 2
  anchors:
  - - 10
    - 13
  - - 16
    - 30
  - - 33
    - 23
  - - 30
    - 61
  - - 62
    - 45
  - - 59
    - 119
  - - 116
    - 90
  - - 156
    - 198
  - - 373
    - 326
  block_size: 3
  keep_prob: 0.9
  norm_decay: 0.0
  num_classes: 80
  weight_prefix_name: ''
  yolo_loss: YOLOv3Loss
YOLOv3Loss:
  [32mbatch_size[0m: 16
  [32miou_loss[0m: IouLoss
  [32mlabel_smooth[0m: false
  [32muse_fine_grained_loss[0m: true
  ignore_thresh: 0.7
architecture: YOLOv3
log_smooth_window: 20
max_iters: 85000
metric: COCO
num_classes: 1
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/ResNet50_vd_dcn_db_obj365_pretrained.tar
save_dir: output
snapshot_iter: 200
use_fine_grained_loss: true
use_gpu: true
weights: output/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco/model_final

Traceback (most recent call last):
  File "tools/train.py", line 323, in <module>
    main()
  File "tools/train.py", line 116, in main
    train_fetches = model.train(feed_vars)
  File "/mnt/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 156, in train
    return self.build(feed_vars, mode='train')
  File "/mnt/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 85, in build
    gt_score, targets)
  File "/mnt/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 277, in get_loss
    self.prefix_name)
  File "/mnt/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 57, in __call__
    mask_anchors, self._ignore_thresh)
  File "/mnt/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 107, in _get_fine_grained_loss
    "YOLOv3 output layer number not equal target number"
AssertionError: YOLOv3 output layer number not equal target number

```

我是想用来训练自己的数据，且只有一个类

**Comment by qingqing01** [comment]
@joshuazm  参考迁移学习文档: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md#paddledetection%E8%BF%9B%E8%A1%8C%E8%BF%81%E7%A7%BB%E5%AD%A6%E4%B9%A0 

通过 `finetune_exclude_pretrained_params= [`yolo_output`]  设置跳过不加在这个参数。

**Comment by qingqing01** [comment]
@joshuazm  请问问题是否解决？

**Comment by joshuazm** [comment]
> @joshuazm 请问问题是否解决？
我没有加这个语句，将use_fine_grained_loss设为false也过去了，但是，出来的结果很糟糕乱画图，而且在infer的时候，会让我在test下添加一个anno_path的json文件，但是作为test预测，怎么会有json文件呐？还有不适用迁移训练来做这个事情，话是怎么配置的呢，谢谢，能否发个参考的yml文件。

**Comment by qingqing01** [comment]
> 出来的结果很糟糕乱画图

感觉还是模型训练没训练好。

> 会让我在test下添加一个anno_path的json文件

看了下代码是可以设置None，此时use_default_label需要设置True。 这个文件主要是为了【获取到类别名字】， 在可视化时显示类别名字。

如果使用不顺畅，我们可以考虑优化下。

> 还有不适用迁移训练来做这个事情，话是怎么配置的呢，谢谢，能否发个参考的yml文件

这个没有特别明白，一般配置预训练模型、数据路径，改变class_num。 如果有具体错误，也可以发出来。

**Comment by joshuazm** [comment]
修改后，我看输出里面还是numclasses是80个呢？

> > 出来的结果很糟糕乱画图
> 
> 感觉还是模型训练没训练好。
> 
> > 会让我在test下添加一个anno_path的json文件
> 
> 看了下代码是可以设置None，此时use_default_label需要设置True。 这个文件主要是为了【获取到类别名字】， 在可视化时显示类别名字。
> 
> 如果使用不顺畅，我们可以考虑优化下。
> 
> > 还有不适用迁移训练来做这个事情，话是怎么配置的呢，谢谢，能否发个参考的yml文件
> 
> 这个没有特别明白，一般配置预训练模型、数据路径，改变class_num。 如果有具体错误，也可以发出来。



> > 出来的结果很糟糕乱画图
> 
> 感觉还是模型训练没训练好。
> 
> > 会让我在test下添加一个anno_path的json文件
> 
> 看了下代码是可以设置None，此时use_default_label需要设置True。 这个文件主要是为了【获取到类别名字】， 在可视化时显示类别名字。
> 
> 如果使用不顺畅，我们可以考虑优化下。
> 
> > 还有不适用迁移训练来做这个事情，话是怎么配置的呢，谢谢，能否发个参考的yml文件
> 
> 这个没有特别明白，一般配置预训练模型、数据路径，改变class_num。 如果有具体错误，也可以发出来。

这个是我的yml配置文件：
architecture: YOLOv3
use_gpu: true
max_iters: 20000
log_smooth_window: 20
save_dir: output
snapshot_iter: 1000
metric: COCO
# metric: VOC
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/ResNet50_vd_dcn_db_obj365_pretrained.tar
weights: output/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_dx/model_final
num_classes: 1
finetune_exclude_pretrained_params: ['yolo_output'] 
use_fine_grained_loss: false

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head
  use_fine_grained_loss: false

ResNet:
  norm_type: sync_bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 50
  feature_maps: [3, 4, 5]
  variant: d
  dcn_v2_stages: [5]

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01
  drop_block: true

YOLOv3Loss:
  # batch_size here is only used for fine grained loss, not used
  # for training batch_size setting, training batch_size setting
  # is in configs/yolov3_reader.yml TrainReader.batch_size, batch
  # size here should be set as same value as TrainReader.batch_size
  batch_size: 16
  ignore_thresh: 0.7
  label_smooth: false
  use_fine_grained_loss: false
  iou_loss: IouLoss

IouLoss:
  loss_weight: 2.5
  max_height: 608
  max_width: 608

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 55000
    - 75000
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

# _READER_: 'yolov3_enhance_reader.yml'

TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  use_fine_grained_loss: false
  dataset:
    !COCODataSet
    image_dir: images/train2020
    anno_path: dx_train.json
    dataset_dir: dataset/dx
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !RandomCrop {}
    - !RandomFlipImage
      is_normalized: false
    - !NormalizeBox {}
    - !PadBox
      num_max_boxes: 50
    - !BboxXYXY2XYWH {}
  batch_transforms:
    - !RandomShape
      sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
      random_inter: True
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: False
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
    # Gt2YoloTarget is only used when use_fine_grained_loss set as true,
    # this operator will be deleted automatically if use_fine_grained_loss
    # is set as false
    - !Gt2YoloTarget
      anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
      anchors: [[10, 13], [16, 30], [33, 23],
                [30, 61], [62, 45], [59, 119],
                [116, 90], [156, 198], [373, 326]]
      downsample_ratios: [32, 16, 8]
  batch_size: 16
  shuffle: false
  drop_last: true
  worker_num: 8
  bufsize: 32
  use_process: true

EvalReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
    num_max_boxes: 50
  dataset:
    !COCODataSet
    dataset_dir: dataset/dx
    anno_path: dx_val.json
    image_dir: images/val2020
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: false
    - !ResizeImage
      interp: 2
      target_size: 608
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: False
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 32
  drop_empty: false
  worker_num: 8
  bufsize: 32

TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
  dataset:
    !ImageFolder
      anno_path: dx_val.json #由于要求有该路径所以添加了一个
      dataset_dir: dataset/dx
      image_dir: images/val2020
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: false
    - !ResizeImage
      interp: 2
      target_size: 608
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: False
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
--------------
下面是输出的训练情况：我选用的
2020-04-26 14:37:01,536-INFO: iter: 28220, lr: 0.000100, 'loss': '3.663044', time: 0.789, eta: 12:27:05
2020-04-26 14:37:16,114-INFO: iter: 28240, lr: 0.000100, 'loss': '3.240354', time: 0.715, eta: 11:16:00
2020-04-26 14:37:29,464-INFO: iter: 28260, lr: 0.000100, 'loss': '3.489028', time: 0.672, eta: 10:35:34
2020-04-26 14:37:40,307-INFO: iter: 28280, lr: 0.000100, 'loss': '3.837735', time: 0.551, eta: 8:40:47
2020-04-26 14:37:53,269-INFO: iter: 28300, lr: 0.000100, 'loss': '3.888747', time: 0.650, eta: 10:13:48
2020-04-26 14:38:08,708-INFO: iter: 28320, lr: 0.000100, 'loss': '3.673880', time: 0.765, eta: 12:02:12
2020-04-26 14:38:25,040-INFO: iter: 28340, lr: 0.000100, 'loss': '3.887210', time: 0.822, eta: 12:55:49
2020-04-26 14:38:38,870-INFO: iter: 28360, lr: 0.000100, 'loss': '3.724604', time: 0.693, eta: 10:54:15
2020-04-26 14:38:51,759-INFO: iter: 28380, lr: 0.000100, 'loss': '3.665164', time: 0.634, eta: 9:58:17
2020-04-26 14:39:07,789-INFO: iter: 28400, lr: 0.000100, 'loss': '3.780353', time: 0.807, eta: 12:41:28
2020-04-26 14:39:07,791-INFO: Save model to output/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco/28400.
---------------------------

**Comment by qingqing01** [comment]
> 我看输出里面还是numclasses是80个呢？

指得是yml里配置了num_classes=1，但训练起来打印的log里还是80吗？如果是，可以忽略这个打印，这个打印有误。

**Comment by qingqing01** [comment]
@joshuazm 

建议使用COCO的预训练模型，试下呢？

```
https://paddlemodels.bj.bcebos.com/object_detection/yolov3_r50vd_dcn_obj365_v2.tar
```

**Comment by joshuazm** [comment]
> @joshuazm
> 
> 建议使用COCO的预训练模型，试下呢？
> 
> ```
> https://paddlemodels.bj.bcebos.com/object_detection/yolov3_r50vd_dcn_obj365_v2.tar
> ```

训练画出来全是渔网一样的框图，整个图片充满画框，如同渔网一样的格子

**Comment by qingqing01** [comment]
@joshuazm 那还是训练的模型不正常，如果有数据方便共享，可以发出来，我们测下看看。

**Comment by qingqing01** [comment]
@joshuazm 请问现在问题解决了吗？
