### ISSUE TITLE
[BUG]PP-tracking: IndexError: arrays used as indices must be of integer (or boolean) type

### ISSUE THREAD

**Issue by dongyangli-del** [PaddlePaddle/PaddleDetection#5510]
## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
python deploy/pptracking/python/mot_sde_infer.py --model_dir=output_inference/ppyolov2_r50vd_dcn_365e_aic21mtmct_vehicle/ --reid_model_dir=output_inference/deepsort_pplcnet_vehicle/ --video_file=test.mp4 --device=GPU --scaled=True --save_mot_txts
```

2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。
未修改.
3. 您使用的数据集是？/What dataset did you use?
自定义行人视频测试集.
4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
paddle 2.2 PaddleDetection-Release-2.2.0 
2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
Linux
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
3.7
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
CUDA-10.2

**Comment by dongyangli-del** [comment]
评估的时候还是正常的,导出模型后就不正常了:
![image](https://user-images.githubusercontent.com/62006079/160642289-98723c1e-1b68-47a5-a4fd-84191928b69e.png)

**Comment by nemonameless** [comment]
请使用最新develop或release/2.4的代码。
