### ISSUE TITLE
[BUG]    AttributeError: module 'paddle.nn.functional' has no attribute 'mish'

### ISSUE THREAD

**Issue by dongyangli-del** [PaddlePaddle/PaddleDetection#5515]
![image](https://user-images.githubusercontent.com/62006079/160755047-16c8924c-6693-410b-b0bb-1886e17ec3f3.png)

命令:

>`CUDA_VISIBLE_DEVICES=0 python tools/export_model.py -c configs/mot/deepsort/detector/ppyolov2_r50vd_dcn_365e_640x640_mot17half.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/deepsort/ppyolov2_r50vd_dcn_365e_640x640_mot17half.pdparams
`

**Comment by yghstill** [comment]
@dongyangli-del 参考issue：https://github.com/PaddlePaddle/PaddleDetection/issues/5509
更新PaddlePaddle版本到2.2.2。

**Comment by Victoria-1** [comment]
抱歉，看错版本了，更新后可以了
