### ISSUE TITLE
个别图片读图失败后，如何让reader继续训练

### ISSUE THREAD

**Issue by qpfhuan** [PaddlePaddle/PaddleDetection#552]
如题。
找到了ppdet/data/reader.py 和ppdet/data/parallel_map.py两个文件。
修改其中next()读取方式，如果exception则再取下一个next()

但其中会遇到很多问题。输入或者input queue会莫名没有，导致后续无法处理。

想请问，从哪里更改读图方式比较好。

**Comment by qingqing01** [comment]
@qpfhuan 依据您的数据格式，可以在 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/data/source  

解析数据的时候，尝试过滤读取失败的。 

另外，您的图片为什么会读取失败？

**Comment by qpfhuan** [comment]
有一些数据集图片很多，可能图片质量，或者图片本身就不存在。需要更改读图方式鲁棒的读取。
ppdet/data/source/dataset.py里只是把图片路径都进来。真正读图是在reader 和parrallel_map.py两个文件。

但我尝试更改发现其中逻辑很复杂，一环套一环。想问你们有没有什么顶层的设计或者方法可以简单的更改的。

**Comment by qingqing01** [comment]
@qpfhuan 如果你的数据是coco格式，目前觉得最简单的方式，ppdet/data/source/coco.py 往`records `里append全量数据的时候判断下，

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/data/source/coco.py#L152

可以`try catch`先尝试读一次，不成功，就过滤掉，continue，不append到`records`。

**Comment by qpfhuan** [comment]
好的，我看下，谢谢答复。

**Comment by qingqing01** [comment]
@qpfhuan 还有一种方式

reader.py中  https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/data/reader.py#L339

设置`self._load_img=True`，这里判断下 `sample['image'] = self._load_image(sample['im_file'])`
 判断，如果不成功，跳过试下。

**Comment by qpfhuan** [comment]
在reader加了个标志位判断。提了pr, 可以看下。new robust reader #556

**Comment by qpfhuan** [comment]
提交了pr但貌似格式不对。在reader上加了标志位判断路径是否有效。你们自己可以改下如果觉得需要的话。
