### ISSUE TITLE
配置文件flip_perm， halfbody是否支持弃用

### ISSUE THREAD

**Issue by Victoria-1** [PaddlePaddle/PaddleDetection#5522]
借用关键点检测模型hrnet训练自己的数据集，配置文件中有个flip_perm设置水平翻转，以及训练过程中使用halfbody,。但我训练的数据由于不是人体关键点检测，不存在halfbody , flip_perm也不一定严格水平对称，请问这两个参数是否可以舍弃，或者需要做哪些修改，谢谢

**Comment by zoooo0820** [comment]
@Victoria-1 
在HRNet对应的[config](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/keypoint/hrnet/hrnet_w32_256x192.yml#L93)中，对应[类的位置](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/transform/keypoint_operators.py#L411) ，可以对照修改下各个参数的值。例如（flip: false, prob_half_body:0)

**Comment by Victoria-1** [comment]
> @Victoria-1 在HRNet对应的[config](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/keypoint/hrnet/hrnet_w32_256x192.yml#L93)中，对应[类的位置](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/transform/keypoint_operators.py#L411) ，可以对照修改下各个参数的值。例如（flip: false, prob_half_body:0)

感谢大佬！还有个问题，在评价中计算oks_iou的时候，有组固定的参数
sigmas = np.array([
            .26, .25, .25, .35, .35, .79, .79, .72, .72, .62, .62, 1.07, 1.07,
            .87, .87, .89, .89,
        ]) / 10.0。
由之前提供的帮助了解了这组参数的来源。但因为我现在没有真实数据源，只有手工标注的，我是否要再挑选一批样本重新标注一次当作真实，然后进行统计。或者能不能改成其他的评价方式，谢谢

**Comment by zoooo0820** [comment]
- 一般来说，统计这个sigma会比较繁琐，当然如果可以的话指标反应得会更准确。这里如果自定义的数据在尺度上不会出现很大差异的话可以不需要动。
- 另外目前PPDET里还有一种基于MPII数据集的PCKH的metric方式，调整方式见[这里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/keypoint/hrnet/hrnet_w32_256x256_mpii.yml#L9)，当然适配自定义数据的话还是需要对代码做一些改动。

**Comment by Victoria-1** [comment]
感谢大佬！
