### ISSUE TITLE
[Other General Issues]可视化数据预处理后的图片

### ISSUE THREAD

**Issue by haotian18** [PaddlePaddle/PaddleDetection#5524]
观察文档中有DebugVisibleImage类，但不知如何使用，由于要写相关预处理的文档，求告知如何使用或者有什么其他方法可视化每一步预处理后的图片

**Comment by yghstill** [comment]
DebugVisibleImage可以可视化简单的预处理，可以按照https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/data/transform/operators.py#L1878 的思路在你的预处理代码中将处理后的图片save到本地查看是否正确。
