### ISSUE TITLE
pp-yolo-tiny 用的  交叉熵损失函数是 二分类么？？

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#5537]
![image](https://user-images.githubusercontent.com/88072901/160841091-37c76285-c027-45ad-b1e8-2959bc2f6d6c.png)

这里用的是 二分类的 交叉损失函数吧  那这个80类咋分的啊？？

**Comment by yghstill** [comment]
@STUSER001 binary_cross_entropy是二分类交叉熵损失，这里是指对物体前景和背景进行分类。

**Comment by STUSER001** [comment]
> @STUSER001 binary_cross_entropy是二分类交叉熵损失，这里是指对物体前景和背景进行分类。

目标分类用的是啥？我看这是loss 只有这个 也就是说用交叉熵损失惨重函数 做了前后景分类 以及目标分类是么？
![CE1AD722-5652-4D4E-885E-D2CE2D2C51F3](https://user-images.githubusercontent.com/88072901/160966698-0a52ab65-7275-4759-bff2-f6f2082b7a88.jpeg)

**Comment by wangxinxin08** [comment]
cls loss也是二分类交叉熵分类，如果多个类别，会预测每一个类别的概率，这个有别于softmax cross entropy

**Comment by STUSER001** [comment]
> cls loss也是二分类交叉熵分类，如果多个类别，会预测每一个类别的概率，这个有别于softmax cross entropy

也就是说 这边用二分类交叉熵损失函数 做了 多分类是么？

**Comment by wangxinxin08** [comment]
这里是多分类，可以认为是预测每一种类别的概率

**Comment by STUSER001** [comment]
> 这里是多分类，可以认为是预测每一种类别的概率

什么意思？ 我看网上说的二分类交叉熵损失函数 扩展后可做多分类 公式都不一样啊 那么这里用的不是二分类的交叉熵损失函数么？ binary 不是二分类么？ 有点不太懂 请大神多多指教

**Comment by wangxinxin08** [comment]
> > 这里是多分类，可以认为是预测每一种类别的概率
> 
> 什么意思？ 我看网上说的二分类交叉熵损失函数 扩展后可做多分类 公式都不一样啊 那么这里用的不是二分类的交叉熵损失函数么？ binary 不是二分类么？ 有点不太懂 请大神多多指教

binary cross entropy相当于对每一个类别预测二分类，是one-vs-all的多分类方式。gt依然是一个one hot向量。如果类别数为3， 类别为1，则one hot向量是[0, 1, 0], 这里会对每一个类别分别做binary cross entropy。
这里注意区分多分类和多标签分类，这里是多分类，也就是gt的向量是one hot向量。多标签分类gt的向量不是one hot向量。

**Comment by STUSER001** [comment]
> > > 这里是多分类，可以认为是预测每一种类别的概率
> > 
> > 
> > 什么意思？ 我看网上说的二分类交叉熵损失函数 扩展后可做多分类 公式都不一样啊 那么这里用的不是二分类的交叉熵损失函数么？ binary 不是二分类么？ 有点不太懂 请大神多多指教
> 
> binary cross entropy相当于对每一个类别预测二分类，是one-vs-all的多分类方式。gt依然是一个one hot向量。如果类别数为3， 类别为1，则one hot向量是[0, 1, 0], 这里会对每一个类别分别做binary cross entropy。 这里注意区分多分类和多标签分类，这里是多分类，也就是gt的向量是one hot向量。多标签分类gt的向量不是one hot向量。

那些个80个 指的是多标签是吧。是不是 多分类然后 再根据分类 再分标签？  如果 一个分类一个标签 那么是不是 分类个数 和 标签分类数是一样呢？

**Comment by wangxinxin08** [comment]
@STUSER001 80指的**是多分类，不是多标签**，多分类就是区分三个及以上类别，和二分类相对，通常用softmax cross entropy，也可以使用binary cross entropy来计算loss

**Comment by STUSER001** [comment]
> @STUSER001 80指的**是多分类，不是多标签**，多分类就是区分三个及以上类别，和二分类相对，通常用softmax cross entropy，也可以使用binary cross entropy来计算loss

这样啊  我看推理结果 有 label 和 box 坐标 以为 这个是 多标签的呢 好的 谢谢

**Comment by STUSER001** [comment]
> @STUSER001 80指的**是多分类，不是多标签**，多分类就是区分三个及以上类别，和二分类相对，通常用softmax cross entropy，也可以使用binary cross entropy来计算loss

还有一个问题 这里检测头 目标检测 用了 iou loss  是吧 那这个 点使用啥 获得的 是 l1 loss 么？？ 代码哪里体现了呢  我就看到 IOUloss 其他 一直找不到 
![image](https://user-images.githubusercontent.com/88072901/161042328-3902e628-568f-4332-8ee0-ddb4602f4d79.png)
![image](https://user-images.githubusercontent.com/88072901/161042356-eb59fce8-dce1-4a33-a5f9-42ecacbcbe31.png)

**Comment by wangxinxin08** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/modeling/losses/yolo_loss.py#L154 loss_xy和loss_wh表示的是l1 loss
