### ISSUE TITLE
ABORT!!! Out of all 4 trainers, the trainer process with rank=[3] was aborted. Please check its log.[Other General Issues]

### ISSUE THREAD

**Issue by bzcl** [PaddlePaddle/PaddleDetection#5538]
1. 您使用的命令是？/What command or script did you run?

```none
export CUDA_VISIBLE_DEVICES=0,1,2,3
python -m paddle.distributed.launch --gpus 0,1,2,3 tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml --eval
```
(使用单卡训练时不会报错)
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

修改了类别数和学习率

3. 您使用的数据集是？/What dataset did you use?

自定义的数据集，VOC格式

5. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::GPUUniformRandomKernel<float>, paddle::operators::GPUUniformRandomKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   thrust::device_ptr<float> thrust::transform<thrust::cuda_cub::tag, thrust::counting_iterator<unsigned int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::device_ptr<float>, paddle::operators::UniformGenerator<float> >(thrust::detail::execution_policy_base<thrust::cuda_cub::tag> const&, thrust::counting_iterator<unsigned int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::counting_iterator<unsigned int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::device_ptr<float>, paddle::operators::UniformGenerator<float>)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1648647210 (unix time) try "date -d @1648647210" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e8000589fc) received by PID 363080 (TID 0x7fcfbeece380) from PID 363004 ***]

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
paddle2.2.2
2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

linux

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.

python3.6

6. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

CUDA11.2/cuDNN8.0

**Comment by wangxinxin08** [comment]
截图报错信息不全哈，可以发下workerlog.3看下

**Comment by bzcl** [comment]
workerlog.3如下：
The actual image width: 4607 is not equal to the width: 4960.0 in annotation, and update sample['w'] by actual image width.
The actual image height: 3507 is not equal to the height: 3508.0 in annotation, and update sample['h'] by actual image height.
The actual image width: 4960 is not equal to the width: 4961.0 in annotation, and update sample['w'] by actual image width.
The actual image height: 3189 is not equal to the height: 3508.0 in annotation, and update sample['h'] by actual image height.
The actual image width: 4607 is not equal to the width: 2481.0 in annotation, and update sample['w'] by actual image width.
The actual image height: 3507 is not equal to the height: 3508.0 in annotation, and update sample['h'] by actual image height.
The actual image width: 4960 is not equal to the width: 4961.0 in annotation, and update sample['w'] by actual image width.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::MultiDeviceFeedReader<paddle::operators::reader::LoDTensorBlockingQueue>::CheckNextStatus()
1   paddle::pybind::MultiDeviceFeedReader<paddle::operators::reader::LoDTensorBlockingQueue>::WaitFutures(std::__exception_ptr::exception_ptr*)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1648610046 (unix time) try "date -d @1648610046" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e8000311fe) received by PID 201313 (TID 0x7fcf8df79380) from PID 201214 ***]

I0330 11:14:21.662825 203147 gen_comm_id_helper.cc:190] Server listening on: 127.0.0.1:38775 successful.
I0330 11:14:24.679246 203147 nccl_context.cc:74] init nccl context nranks: 4 local rank: 3 gpu id: 3 ring id: 0
W0330 11:14:25.892344 203147 device_context.cc:447] Please NOTE: device: 3, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 11.2
W0330 11:14:25.916321 203147 device_context.cc:465] device: 3, cuDNN Version: 8.0.
W0330 11:14:27.433230 203147 device_context.h:397] WARNING: device: 3. The installed Paddle is compiled with CUDNN 8.1, but CUDNN version in your machine is 8.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
The actual image height: 3191 is not equal to the height: 3507.0 in annotation, and update sample['h'] by actual image height.
The actual image width: 4607 is not equal to the width: 4960.0 in annotation, and update sample['w'] by actual image width.
The actual image height: 3507 is not equal to the height: 3191.0 in annotation, and update sample['h'] by actual image height.
The actual image width: 4960 is not equal to the width: 4607.0 in annotation, and update sample['w'] by actual image width.
The actual image height: 3507 is not equal to the height: 3189.0 in annotation, and update sample['h'] by actual image height.
The actual image width: 4960 is not equal to the width: 4607.0 in annotation, and update sample['w'] by actual image width.
The actual image height: 3507 is not equal to the height: 3190.0 in annotation, and update sample['h'] by actual image height.
The actual image width: 4960 is not equal to the width: 4607.0 in annotation, and update sample['w'] by actual image width.
The actual image height: 3191 is not equal to the height: 3507.0 in annotation, and update sample['h'] by actual image height.
The actual image width: 4607 is not equal to the width: 4960.0 in annotation, and update sample['w'] by actual image width.
The actual image height: 3071 is not equal to the height: 3507.0 in annotation, and update sample['h'] by actual image height.
The actual image width: 4605 is not equal to the width: 4960.0 in annotation, and update sample['w'] by actual image width.
The actual image height: 3507 is not equal to the height: 3190.0 in annotation, and update sample['h'] by actual image height.
The actual image width: 4960 is not equal to the width: 4607.0 in annotation, and update sample['w'] by actual image width.
The actual image height: 3189 is not equal to the height: 3507.0 in annotation, and update sample['h'] by actual image height.
The actual image width: 4607 is not equal to the width: 4960.0 in annotation, and update sample['w'] by actual image width.
The actual image height: 3507 is not equal to the height: 3190.0 in annotation, and update sample['h'] by actual image height.
The actual image width: 4960 is not equal to the width: 4607.0 in annotation, and update sample['w'] by actual image width.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::GPUUniformRandomKernel<float>, paddle::operators::GPUUniformRandomKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   thrust::device_ptr<float> thrust::transform<thrust::cuda_cub::tag, thrust::counting_iterator<unsigned int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::device_ptr<float>, paddle::operators::UniformGenerator<float> >(thrust::detail::execution_policy_base<thrust::cuda_cub::tag> const&, thrust::counting_iterator<unsigned int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::counting_iterator<unsigned int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::device_ptr<float>, paddle::operators::UniformGenerator<float>)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1648610130 (unix time) try "date -d @1648610130" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e800031928) received by PID 203147 (TID 0x7f49e77e5380) from PID 203048 ***]

**Comment by wangxinxin08** [comment]
在配置文件下面添加
```python
EvalReader:
  collate_batch: false
```
试下呢

**Comment by wangxinxin08** [comment]
请问使用的PaddleDetection版本是什么，另外可以贴下配置文件修改了哪些地方？

**Comment by bzcl** [comment]
runtime.yml
use_gpu: true
use_xpu: false
log_iter: 20
save_dir: output
snapshot_epoch: 1
print_flops: false

# Exporting the model
export:
  post_process: True  # Whether post-processing is included in the network when export model.
  nms: True           # Whether NMS is included in the network when export model.
  benchmark: False    # It is used to testing model performance, if set `True`, post-process and NMS will not be exported.


reader.yml（改了 num_max_boxes）
worker_num: 2
TrainReader:
  inputs_def:
    num_max_boxes: 500
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 100}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]], downsample_ratios: [32, 16, 8]}
  batch_size: 4
  shuffle: true
  drop_last: true
  mixup_epoch: 25000
  use_shared_memory: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 8

TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1

voc.yml（改了类别数）
metric: VOC
map_type: 11point
num_classes: 7

TrainDataset:
  !VOCDataSet
    dataset_dir: dataset/datanew
    anno_path: trainval.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: dataset/data
    anno_path: test.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: dataset/voc/label_list.txt

optimizer.yml(改了学习率、LinearWarmup的step、clip_grad_by_norm)

请问PaddleDetection的版本指的是什么，以下是我的环境：
absl-py                      1.0.0
astor                        0.8.1
astunparse                   1.6.3
attrs                        21.4.0
Babel                        2.9.1
bce-python-sdk               0.8.64
beautifulsoup4               4.10.0
bs4                          0.0.1
cached-property              1.5.2
cachetools                   5.0.0
certifi                      2021.10.8
cfgv                         3.3.1
charset-normalizer           2.0.12
click                        8.0.4
cloudpickle                  2.0.0
colorama                     0.4.4
commonmark                   0.9.1
cssselect                    1.1.0
cssutils                     2.4.0
cycler                       0.11.0
Cython                       0.29.28
cython-bbox                  0.1.3
datasets                     1.6.2
decorator                    4.4.2
detectron2                   0.3+cu101
dill                         0.3.4
distlib                      0.3.4
editdistance                 0.6.0
et-xmlfile                   1.1.0
fasttext                     0.9.1
filelock                     3.6.0
flake8                       4.0.1
flake8-import-order          0.18.1
Flask                        2.1.0
Flask-Babel                  2.0.0
flatbuffers                  2.0
fonttools                    4.29.1
fsspec                       2022.2.0
future                       0.18.2
fvcore                       0.1.5.post20220305
gast                         0.4.0
google-auth                  2.6.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.44.0
h5py                         3.6.0
huggingface-hub              0.0.19
identify                     2.4.12
idna                         3.3
imageio                      2.16.1
imgaug                       0.4.0
importlib-metadata           4.2.0
iniconfig                    1.1.1
iopath                       0.1.9
itsdangerous                 2.1.2
Jinja2                       3.1.1
joblib                       1.1.0
keras                        2.8.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.3.2
lap                          0.4.0 
layoutparser                 0.0.0
libclang                     13.0.0
lmdb                         1.2.1
lxml                         4.8.0
Markdown                     3.3.6
MarkupSafe                   2.1.1
matplotlib                   3.5.1
mccabe                       0.6.1
motmetrics                   1.2.0
multiprocess                 0.70.12.2
networkx                     2.6.3
nodeenv                      1.6.0
numpy                        1.21.4
oauthlib                     3.2.0
opencv-contrib-python        4.4.0.46
opencv-python                4.5.4.60
openpyxl                     3.0.9
opt-einsum                   3.3.0
packaging                    21.3
paddleocr                    2.4.0.3
paddlepaddle-gpu             2.2.2.post101
pandas                       1.3.5
pi                           0.1.2
Pillow                       8.4.0
pip                          22.0.4
pip-search                   0.0.10
platformdirs                 2.5.1
pluggy                       1.0.0
portalocker                  2.4.0
pre-commit                   2.17.0
premailer                    3.10.0
protobuf                     3.19.1
py                           1.11.0
py-cpuinfo                   8.0.0
pyarrow                      7.0.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pybind11                     2.9.1
pyclipper                    1.3.0.post2
pycocotools                  2.0.4
pycodestyle                  2.8.0
pycryptodome                 3.14.1
pydot                        1.4.2
pyflakes                     2.4.0
Pygments                     2.11.2
pyparsing                    3.0.7
pytest                       7.1.1
pytest-benchmark             3.4.1
python-dateutil              2.8.2
python-Levenshtein           0.12.2
pytz                         2021.3
PyWavelets                   1.3.0
PyYAML                       6.0
regex                        2022.3.2
requests                     2.27.1
requests-oauthlib            1.3.1
rich                         11.2.0
rsa                          4.8
sacremoses                   0.0.47
scikit-image                 0.19.2
scikit-learn                 1.0.2
scipy                        1.7.3
seqeval                      1.2.2
setuptools                   59.5.0
Shapely                      1.8.1.post1
shellcheck-py                0.8.0.4
six                          1.16.0
sklearn                      0.0
soupsieve                    2.3.1
tabulate                     0.8.9
tensorboard                  2.8.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorboardX                 2.4.1
tensorflow                   2.8.0
tensorflow-io-gcs-filesystem 0.24.0
termcolor                    1.1.0
terminaltables               3.1.10
tf-estimator-nightly         2.8.0.dev2021122109
threadpoolctl                3.1.0
tifffile                     2021.11.2
tokenizers                   0.10.3
toml                         0.10.2
tomli                        2.0.1
torch                        1.7.1+cu101
torchvision                  0.8.2+cu101
tqdm                         4.49.0
transformers                 4.5.1
typeguard                    2.13.3
typing_extensions            4.0.1
urllib3                      1.26.8
virtualenv                   20.14.0
visualdl                     2.2.3
Werkzeug                     2.0.3
wheel                        0.37.0
wrapt                        1.14.0
xmltodict                    0.12.0
xxhash                       3.0.0
yacs                         0.1.8
zipp                         3.7.0

**Comment by wangxinxin08** [comment]
除了num_max_boxes在PadBox中没有同步改过来之外，其他应该不影响训练。所以PaddleDetection的版本是什么？

**Comment by bzcl** [comment]
请问您说的PaddleDetection的版本是指什么

**Comment by wangxinxin08** [comment]
release/2.3还是release/2.4?
