### ISSUE TITLE
PPYOLOE训练集格式

### ISSUE THREAD

**Issue by Feng1909** [PaddlePaddle/PaddleDetection#5539]
请问PPYOLOE除了COCO格式外，能够使用VOC格式进行训练吗

**Comment by wangxinxin08** [comment]
可以使用，直接将配置文件中的数据集换成https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml#L2 
换成../configs/datasets/voc.yml 试下
