### ISSUE TITLE
faster_rcnn_r50_1x 训练10w次，但预测时为什么一点都没有标注出来，一共3种类型

### ISSUE THREAD

**Issue by wyc880622** [PaddlePaddle/PaddleDetection#554]
以下是训练结果评估结果，帮忙给看下。
这是数据集有问题，还是yml有问题？麻烦百度大佬给解决一下，因为我已经训练了好几次了都这样，一直都没有预测成功。谢谢。我将数据集和yml在百度云盘上

链接：https://pan.baidu.com/s/1ZzxXC4Cpui7SEkmJ_McIpA 密码：7zfb

2020-04-26 05:37:36,427-INFO: iter: 99840, lr: 0.000100, 'loss_cls': '0.002928',
 'loss_bbox': '0.000691', 'loss_rpn_cls': '0.000069', 'loss_rpn_bbox': '0.000110
', 'loss': '0.003521', time: 1.152, eta: 0:03:04
2020-04-26 05:37:59,466-INFO: iter: 99860, lr: 0.000100, 'loss_cls': '0.002101',
 'loss_bbox': '0.000775', 'loss_rpn_cls': '0.000064', 'loss_rpn_bbox': '0.000113
', 'loss': '0.003694', time: 1.152, eta: 0:02:41
2020-04-26 05:38:22,463-INFO: iter: 99880, lr: 0.000100, 'loss_cls': '0.001806',
 'loss_bbox': '0.000916', 'loss_rpn_cls': '0.000093', 'loss_rpn_bbox': '0.000110
', 'loss': '0.002956', time: 1.150, eta: 0:02:17
2020-04-26 05:38:45,482-INFO: iter: 99900, lr: 0.000100, 'loss_cls': '0.002629',
 'loss_bbox': '0.001159', 'loss_rpn_cls': '0.000064', 'loss_rpn_bbox': '0.000118
', 'loss': '0.003804', time: 1.151, eta: 0:01:55
2020-04-26 05:39:08,502-INFO: iter: 99920, lr: 0.000100, 'loss_cls': '0.003152',
 'loss_bbox': '0.000819', 'loss_rpn_cls': '0.000041', 'loss_rpn_bbox': '0.000111
', 'loss': '0.004007', time: 1.151, eta: 0:01:32
2020-04-26 05:39:31,532-INFO: iter: 99940, lr: 0.000100, 'loss_cls': '0.003664',
 'loss_bbox': '0.000775', 'loss_rpn_cls': '0.000059', 'loss_rpn_bbox': '0.000109
', 'loss': '0.004821', time: 1.152, eta: 0:01:09
2020-04-26 05:39:54,549-INFO: iter: 99960, lr: 0.000100, 'loss_cls': '0.002765',
 'loss_bbox': '0.000710', 'loss_rpn_cls': '0.000054', 'loss_rpn_bbox': '0.000101
', 'loss': '0.003740', time: 1.151, eta: 0:00:46
2020-04-26 05:40:17,580-INFO: iter: 99980, lr: 0.000100, 'loss_cls': '0.001990',
 'loss_bbox': '0.000718', 'loss_rpn_cls': '0.000073', 'loss_rpn_bbox': '0.000110
', 'loss': '0.003247', time: 1.151, eta: 0:00:23
2020-04-26 05:40:39,423-INFO: Save model to output\faster_rcnn_r50_1x\model_fina
l.
2020-04-26 05:40:42,905-INFO: Test iter 0
2020-04-26 05:41:08,299-INFO: Test finish iter 42
2020-04-26 05:41:08,299-INFO: Total number of images: 42, inference time: 1.6127
174299306581 fps.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2020-04-26 05:41:08,305-INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.01s).
Accumulating evaluation results...
DONE (t=0.01s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000

 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
2020-04-26 05:41:08,332-INFO: Best test box ap: 6.387735547748324e-05, in iter:
4000

(paddle) E:\paddle\PaddleDetection-release-0.2>python -u tools/infer.py -c confi
gs/faster_rcnn_r50_1x.yml -o weights=output\faster_rcnn_r50_1x\best_model --infe
r_img=demo/1.jpg --output_dir=infer_output
W0426 11:01:37.559897  5576 device_context.cc:237] Please NOTE: device: 0, CUDA
Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.0
W0426 11:01:37.568897  5576 device_context.cc:245] device: 0, cuDNN Version: 7.5
.
2020-04-26 11:01:38,493-INFO: Loading parameters from output\faster_rcnn_r50_1x\
best_model...
2020-04-26 11:01:40,755-INFO: Load categories from E:/paddle/PaddleDetection-rel
ease-0.2/dataset/coco/annotations/instance_test.json
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2020-04-26 11:01:42,005-INFO: Infer iter 0
2020-04-26 11:01:42,014-INFO: Detection bbox results save in infer_output\1.jpg

**Comment by still-wait** [comment]
@wyc880622 我用你给的数据复现下。

**Comment by still-wait** [comment]
@wyc880622 我可视化了一下你的ground truth，感觉标注或转换数据时有问题，请check一下数据标注文件中`bbox`正确性，另外，`category_id`建议从零开始计数。
![image](https://user-images.githubusercontent.com/15628872/80297501-0b345c80-87b6-11ea-92c5-720ba9500a0e.png)
![image](https://user-images.githubusercontent.com/15628872/80297556-adecdb00-87b6-11ea-9f14-1e62d4acfa42.png)

**Comment by wyc880622** [comment]
你好，我标注的没有问题，我检查了一下，标注文件能正确显示标注内容。
![image](https://user-images.githubusercontent.com/25219834/80326248-ba327000-886a-11ea-8701-f48611a6909f.png)
只是数据标注后进行分割时，我利用这个网址的内容，是由百度客服提供。
https://github.com/jiangjiajun/PaddleSolution
谢谢，请帮忙在看下。

**Comment by wyc880622** [comment]
category_id建议从零开始计数。可我看到 0 不是默认为背景吗？
转换数据时有问题这个问题应该存在，客服给我的程序我感觉是不对的。谢谢。你们可以验证下这个网址。

**Comment by still-wait** [comment]
@wyc880622 category_id包含背景后从1开始计数，你再检查一下instance json文件的正确性，我们也验证一下。

**Comment by wyc880622** [comment]
instance json它是不正确的，我已经给改了。你们给的那个网址程序有问题。我已经使用其他的程序生成了，现在正在训练。谢谢



wangyongchao8806@126.com
 
发件人： Guanghua Yu
发送时间： 2020-04-27 10:42
收件人： PaddlePaddle/PaddleDetection
抄送： wyc880622; Mention
主题： Re: [PaddlePaddle/PaddleDetection] faster_rcnn_r50_1x 训练10w次，但预测时为什么一点都没有标注出来，一共3种类型 (#554)
@wyc880622 category_id包含背景后从1开始计数，你再检查一下instance json文件的正确性，我们也验证一下。

**Comment by still-wait** [comment]
@wyc880622 https://github.com/jiangjiajun/PaddleSolution 经反馈，这个repo已经弃用，不推荐再使用，此issue有问题再reopen。
