### ISSUE TITLE
[BUG]PicoDet检测器无法在车辆多目标跟踪中使用

### ISSUE THREAD

**Issue by dongyangli-del** [PaddlePaddle/PaddleDetection#5540]
命令:
`python deploy/pptracking/python/mot_sde_infer.py --model_dir=output_inference/picodet_l_640_aic21mtmct_vehicle/ --tracker_config=./deploy/pptracking/python/tracker_config.yml --reid_model_dir=output_inference/deepsort_pplcnet_vehicle/  --video_file=c003.mp4 --device=GPU   --scaled=True --save_mot_txts
`
报错如下:
![image](https://user-images.githubusercontent.com/62006079/160950964-ae498ce8-cae6-4cc8-b618-6648512e6d1e.png)

**Comment by dongyangli-del** [comment]
多目标车辆跨境跟踪已经可以使用,问题的本质是paddle版本没有满足>2.2.2,话说paddle的向下兼容做的一点也不好,我2.1.1就完全用不了了,我以为小版本肯定兼容的....

**Comment by nemonameless** [comment]
paddle2.2大版本和2.1个别OP有较大差别，2.2以内的小版本差别不大。安装推荐按照官网的最新稳定版。
