### ISSUE TITLE
ObjectDector加速方法

### ISSUE THREAD

**Issue by TTgogogo** [PaddlePaddle/PaddleDetection#5541]
将PaddleDetection::ObjectDetector det(FLAGS_model_dir, "CPU")改为PaddleDetection::ObjectDetector det(FLAGS_model_dir, "GPU",false,1,"trt_fp16")，并没起到加速作用，是什么地方不对吗？

**Comment by wangxinxin08** [comment]
使用的是什么模型呢？可以提供下可复现的环境和代码

**Comment by TTgogogo** [comment]
模型是YoloV3,代码调用ObjectDetector ，如下：
        // Load model and create a object detector
        std::string FLAGS_model_dir = "D:/projects/ppmodel";

        PaddleDetection::ObjectDetector det(FLAGS_model_dir, "CPU");

        Mat outImg;
        // Do inference on input video or image
        PredictImage(frame, outImg,
            1,
            0.1,
            false,
            &det,
            "D:/output");

**Comment by wangxinxin08** [comment]
请问你是使用的PaddleDetection的代码吗？如果不是的话，可以把可复现代码上传到github或者网盘吗？不然没办法定位问题

**Comment by TTgogogo** [comment]
是用的PaddleDection的代码，包含了config_parser.h, object_detector.h, preprocess_op.h, object_detector.cc,preprocess_op.cc而已。然后按照上面的代码调用objectdetector。不是运行的问题，只是如何切换为GPU模式进行加速？
