### ISSUE TITLE
[BUG]pp-Tracking无法使用行人跨镜头跟踪

### ISSUE THREAD

**Issue by dongyangli-del** [PaddlePaddle/PaddleDetection#5542]
如下图所示,使用如下命令加载跨镜头行人跟踪:

预测时会直接报错:
![image](https://user-images.githubusercontent.com/62006079/160959212-ab8199f8-c829-4908-990a-9e9e0477a282.png)

![image](https://user-images.githubusercontent.com/62006079/160959480-b2c1ee29-33a8-4eaf-9674-55f76786e35c.png)

**Comment by dongyangli-del** [comment]
命令:`python deploy/pptracking/python/mot_sde_infer.py --model_dir=output_inference/jde_yolov3_darknet53_30e_1088x608_mix/  --reid_model_dir=output_inference/deepsort_pcb_pyramid_r101/ --mtmct_dir=mtmct-demo --mtmct_cfg=deploy/pptracking/python/mtmct_cfg.yml --device=GPU --scaled=True --save_mot_txts --save_images
`

**Comment by nemonameless** [comment]
调用jde_yolov3得设置--scaled=False。mtmct-demo 下载的是车辆跨境头跟踪视频，检测不到行人的。请再仔细查阅文档运行。

**Comment by dongyangli-del** [comment]
我使用PaddleDetection-2.3Release,现在可以正常跨镜头行人跟踪了,但同样的操作在PaddleDetection-Develop的默认分支无法运行.

目前的一个问题是,对于某些场景尤其是单一目标的场景,算法运行会由于异常而中断,打印余弦度量矩阵发现很多地方爆nan了:
![image](https://user-images.githubusercontent.com/62006079/161034745-2af81c1f-c67d-4a9c-af63-9177d693abbc.png)
![image](https://user-images.githubusercontent.com/62006079/161034774-48838dd6-dc5e-47a7-bab7-4a2f44f01bfc.png)

当然上述问题只在部分场景中出现,这应该与代码的健壮性较差有关.可能开发者并没有考虑到某些异常情况如单一目标且检测不连续等.

我需要做哪些异常处理方式,以便于算法能够在任何视频输入的情况下不因异常而中断呢? 我已经尝试在某些地方设置try except 捕获异常,但这种一刀切的方式会导致最终mtmct.txt文件为空的情况.期待得到回复.@[nemonameless](https://github.com/nemonameless)

**Comment by dongyangli-del** [comment]
报错场景:图中给出的是典型的少目标及检测因光线或遮挡而导致部分帧缺失的典型情况:
![image](https://user-images.githubusercontent.com/62006079/161035550-f7022964-a8c2-407a-9d7d-22828933e015.png)

**Comment by dongyangli-del** [comment]
这样就是正常的:这显然表明是项目的BUG:
![image](https://user-images.githubusercontent.com/62006079/161035838-54549bed-3308-4d11-860d-a428237f5d18.png)

**Comment by dongyangli-del** [comment]
> 调用jde_yolov3得设置--scaled=False。mtmct-demo 下载的是车辆跨境头跟踪视频，检测不到行人的。请再仔细查阅文档运行。

不好意思,我是原来设置为False后无法正常运行,后来就改为True了,这一点我没有事先说明,抱歉.不过现在这个问题已经解决了,应该是paddle和项目版本不匹配.

**Comment by nemonameless** [comment]
请使用最新develop或release/2.4的代码。提供的模型是用MOT17数据集训练的，无法覆盖任意场景检测，最好是用你想测的场景数据集重新训练检测。
