### ISSUE TITLE
调参指导，训练之初loss迅速趋近于0

### ISSUE THREAD

**Issue by Victoria-1** [PaddlePaddle/PaddleDetection#5546]
使用hrnet关键点检测，自定义数据集（共38个关键点，6007张图像，训练集4802，测试集1201），原配置学习率为
![image](https://user-images.githubusercontent.com/35481439/160986373-a4398d8e-b692-46ca-ab8e-166061e5ebf9.png)
batchsize为64。

我训练过程中采用单卡训练，batchsize = 8, 学习率试过0.0001,  0.0005， （0.0005/32）,  steps也试过改成300， 3000但无论改大还是改小，每次训练一开始就出现loss迅速趋近于0的情况，batch_cost，data_cost也基本不变，但loss有看到在变小
![image](https://user-images.githubusercontent.com/35481439/160988065-46b2a2dd-2727-4cfc-a673-39a2143a2a14.png)

请大佬指导，这是什么原因，应该怎么调，谢谢！

**Comment by zhiboniu** [comment]
loss变小是正常的啊，是效果有问题吗？
如果怀疑不正常，建议把训练的heatmap_gt保存下来看看关键点的高斯核放置是否和预期一致。

**Comment by Victoria-1** [comment]
1. 可是才跑一个batch，loss就是0.00083，已经接近0了，怎么感觉不太不正常，或者如果这是正常，那loss应该收敛到什么程度才比较好（因为是自定义数据集，计算oks_iou中的sigmas还未进行统计所以无法用use_vdl查看训练过程）。之前用默认参数跑了一次，效果也确实很差
2. 请问heatmap_gt保存在哪里可以修改查看
感谢大佬！ @zhiboniu

**Comment by zhiboniu** [comment]
1. 关键点的loss计算是heatmap L2距离的平均值，因为本身heatmap_gt的范围是0-1，大部分区域都是0， 所以算出来肯定是类似0.00xx这种比较小的，具体多少是合理的不好说。因为大部分区域是0，所以感觉下降快点也是合理的。你可以等训练几十个epoch以后再确认一下是否OK。
2.保存heatmap_gt是需要自己做的，并没有提供这种很细节的调试功能。就是把计算loss前面的heatmap_gt每一层作为图片存下来，看看是否在图片对应关键点位置有高亮的高斯核。注意heatmap_gt值的范围是0-1，存储图片需要*255变换到0-255。
另外，感觉你的数据量有点小，最好用一个比较好关键点预训练模型上finetune，不要使参数变化太剧烈

**Comment by Victoria-1** [comment]
我把从头开始训练的数据直接保存下来用excel画出来了，才4个epoch就已经这样了
![image](https://user-images.githubusercontent.com/35481439/161020305-4018a8fd-020e-4064-8f44-b47a850aaa23.png)

<img width="751" alt="image" src="https://user-images.githubusercontent.com/35481439/161020100-e2fcd721-c4e3-4c52-9308-96a7c7a4464b.png">
我的参数设置
![image](https://user-images.githubusercontent.com/35481439/161020588-77b41f4a-f7e9-4bd0-9bc9-44ceb8dd84ad.png)
看起来已经收敛了，感觉确实不正常
然后我用debug的方式看了一个heatmap_gt，发现全为0
![image](https://user-images.githubusercontent.com/35481439/161026341-144a23e5-a26c-4643-9ed8-0021a4257dab.png)
   请问这是什么原因导致？如何修正？  
谢谢 @zhiboniu

**Comment by zhiboniu** [comment]
可能是关键点位置标注有误，不在区域范围内？
