### ISSUE TITLE
验证模型报错

### ISSUE THREAD

**Issue by joshuazm** [PaddlePaddle/PaddleDetection#555]
Traceback (most recent call last):
  File "/opt/anaconda3/bin/anaconda/lib/python3.7/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/eval.py", line 190, in <module>
    main()
  File "tools/eval.py", line 173, in main
    dataset=dataset)
  File "/mnt/qql/PaddleDetection/ppdet/utils/eval_utils.py", line 205, in eval_results
    is_bbox_normalized=is_bbox_normalized)
  File "/mnt/qql/PaddleDetection/ppdet/utils/coco_eval.py", line 94, in bbox_eval
    map_stats = cocoapi_eval(outfile, 'bbox', coco_gt=coco_gt)
  File "/mnt/qql/PaddleDetection/ppdet/utils/coco_eval.py", line 147, in cocoapi_eval
    coco_eval = COCOeval(coco_gt, coco_dt, style)
  File "/opt/anaconda3/bin/anaconda/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/opt/anaconda3/bin/anaconda/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/opt/anaconda3/bin/anaconda/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/opt/anaconda3/bin/anaconda/lib/python3.7/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
terminate called without an active exception
W0426 15:09:00.840675 18619 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0426 15:09:00.840696 18619 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0426 15:09:00.840706 18619 init.cc:214] The detail failure signal is:

W0426 15:09:00.840714 18619 init.cc:217] *** Aborted at 1587884940 (unix time) try "date -d @1587884940" if you are using GNU date ***
W0426 15:09:00.843050 18619 init.cc:217] PC: @                0x0 (unknown)
W0426 15:09:00.843123 18619 init.cc:217] *** SIGABRT (@0x487c) received by PID 18556 (TID 0x7f06627fc700) from PID 18556; stack trace: ***
W0426 15:09:00.845201 18619 init.cc:217]     @     0x7f0737c73390 (unknown)
W0426 15:09:00.849298 18619 init.cc:217]     @     0x7f07378cd428 gsignal
W0426 15:09:00.851326 18619 init.cc:217]     @     0x7f07378cf02a abort
W0426 15:09:00.852880 18619 init.cc:217]     @     0x7f071a2903df __gnu_cxx::__verbose_terminate_handler()
W0426 15:09:00.854301 18619 init.cc:217]     @     0x7f071a28eb16 __cxxabiv1::__terminate()
W0426 15:09:00.855829 18619 init.cc:217]     @     0x7f071a28eb4c std::terminate()
W0426 15:09:00.857275 18619 init.cc:217]     @     0x7f071a28e81e __gxx_personality_v0
W0426 15:09:00.858788 18619 init.cc:217]     @     0x7f071ae30045 _Unwind_ForcedUnwind_Phase2
W0426 15:09:00.860298 18619 init.cc:217]     @     0x7f071ae3031b _Unwind_ForcedUnwind
W0426 15:09:00.862291 18619 init.cc:217]     @     0x7f0737c72070 __GI___pthread_unwind
W0426 15:09:00.864257 18619 init.cc:217]     @     0x7f0737c6a845 __pthread_exit
W0426 15:09:00.864611 18619 init.cc:217]     @     0x55ad511087a9 PyThread_exit_thread
W0426 15:09:00.864715 18619 init.cc:217]     @     0x55ad50f8294f PyEval_RestoreThread.cold.794
W0426 15:09:00.865523 18619 init.cc:217]     @     0x7f0714c6ef03 (unknown)
W0426 15:09:00.865908 18619 init.cc:217]     @     0x55ad51080f45 _PyMethodDef_RawFastCallKeywords
W0426 15:09:00.866276 18619 init.cc:217]     @     0x55ad51080fc1 _PyCFunction_FastCallKeywords
W0426 15:09:00.866633 18619 init.cc:217]     @     0x55ad510f63ae _PyEval_EvalFrameDefault
W0426 15:09:00.866959 18619 init.cc:217]     @     0x55ad5102f528 _PyEval_EvalCodeWithName
W0426 15:09:00.867296 18619 init.cc:217]     @     0x55ad510305b4 _PyFunction_FastCallDict
W0426 15:09:00.867619 18619 init.cc:217]     @     0x55ad5104f703 _PyObject_Call_Prepend
W0426 15:09:00.867784 18619 init.cc:217]     @     0x55ad510891fa slot_tp_call
W0426 15:09:00.868113 18619 init.cc:217]     @     0x55ad5108a11b _PyObject_FastCallKeywords
W0426 15:09:00.868469 18619 init.cc:217]     @     0x55ad510f5c16 _PyEval_EvalFrameDefault
W0426 15:09:00.868796 18619 init.cc:217]     @     0x55ad510304eb _PyFunction_FastCallDict
W0426 15:09:00.869113 18619 init.cc:217]     @     0x55ad5104f703 _PyObject_Call_Prepend
W0426 15:09:00.869283 18619 init.cc:217]     @     0x55ad510891fa slot_tp_call
W0426 15:09:00.869622 18619 init.cc:217]     @     0x55ad5108a11b _PyObject_FastCallKeywords
W0426 15:09:00.869972 18619 init.cc:217]     @     0x55ad510f62ce _PyEval_EvalFrameDefault
W0426 15:09:00.870301 18619 init.cc:217]     @     0x55ad5102f528 _PyEval_EvalCodeWithName
W0426 15:09:00.870625 18619 init.cc:217]     @     0x55ad510305b4 _PyFunction_FastCallDict
W0426 15:09:00.870940 18619 init.cc:217]     @     0x55ad5104f703 _PyObject_Call_Prepend
W0426 15:09:00.871306 18619 init.cc:217]     @     0x55ad51041cee PyObject_Call
Aborted (core dumped)

**Comment by qingqing01** [comment]
@joshuazm  由于numpy的最新1.18版本改了一个接口的参数类型，pycocotools里评估时用到这个接口，就报错了，请回退numpy版本或者升级pycocotools，具体参考 #560 245 #445 的issue解决方案。

**Comment by joshuazm** [comment]
> @joshuazm 由于numpy的最新1.18版本改了一个接口的参数类型，pycocotools里评估时用到这个接口，就报错了，请回退numpy版本或者升级pycocotools，具体参考 #245 #445 的issue解决方案。

terminate called without an active exception
W0426 16:23:18.324445 19117 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0426 16:23:18.324465 19117 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0426 16:23:18.324470 19117 init.cc:214] The detail failure signal is:

W0426 16:23:18.324477 19117 init.cc:217] *** Aborted at 1587889398 (unix time) try "date -d @1587889398" if you are using GNU date ***
W0426 16:23:18.326802 19117 init.cc:217] PC: @                0x0 (unknown)
W0426 16:23:18.326874 19117 init.cc:217] *** SIGABRT (@0x4a61) received by PID 19041 (TID 0x7f3c22ffd700) from PID 19041; stack trace: ***
W0426 16:23:18.328965 19117 init.cc:217]     @     0x7f3cb9507390 (unknown)
W0426 16:23:18.331039 19117 init.cc:217]     @     0x7f3cb9161428 gsignal
W0426 16:23:18.333042 19117 init.cc:217]     @     0x7f3cb916302a abort
W0426 16:23:18.334612 19117 init.cc:217]     @     0x7f3c9bb303df __gnu_cxx::__verbose_terminate_handler()
W0426 16:23:18.335990 19117 init.cc:217]     @     0x7f3c9bb2eb16 __cxxabiv1::__terminate()
W0426 16:23:18.337519 19117 init.cc:217]     @     0x7f3c9bb2eb4c std::terminate()
W0426 16:23:18.338956 19117 init.cc:217]     @     0x7f3c9bb2e81e __gxx_personality_v0
W0426 16:23:18.340456 19117 init.cc:217]     @     0x7f3c9c610045 _Unwind_ForcedUnwind_Phase2
W0426 16:23:18.341970 19117 init.cc:217]     @     0x7f3c9c61031b _Unwind_ForcedUnwind
W0426 16:23:18.343938 19117 init.cc:217]     @     0x7f3cb9506070 __GI___pthread_unwind
W0426 16:23:18.345902 19117 init.cc:217]     @     0x7f3cb94fe845 __pthread_exit
W0426 16:23:18.346251 19117 init.cc:217]     @     0x562d68bb37a9 PyThread_exit_thread
W0426 16:23:18.346349 19117 init.cc:217]     @     0x562d68a2d94f PyEval_RestoreThread.cold.794
W0426 16:23:18.347132 19117 init.cc:217]     @     0x7f3c9650ef03 (unknown)
W0426 16:23:18.347506 19117 init.cc:217]     @     0x562d68b2bf45 _PyMethodDef_RawFastCallKeywords
W0426 16:23:18.347863 19117 init.cc:217]     @     0x562d68b2bfc1 _PyCFunction_FastCallKeywords
W0426 16:23:18.348213 19117 init.cc:217]     @     0x562d68ba13ae _PyEval_EvalFrameDefault
W0426 16:23:18.348533 19117 init.cc:217]     @     0x562d68ada528 _PyEval_EvalCodeWithName
W0426 16:23:18.348865 19117 init.cc:217]     @     0x562d68adb5b4 _PyFunction_FastCallDict
W0426 16:23:18.349180 19117 init.cc:217]     @     0x562d68afa703 _PyObject_Call_Prepend
W0426 16:23:18.349342 19117 init.cc:217]     @     0x562d68b341fa slot_tp_call
W0426 16:23:18.349679 19117 init.cc:217]     @     0x562d68b3511b _PyObject_FastCallKeywords
W0426 16:23:18.350036 19117 init.cc:217]     @     0x562d68ba0c16 _PyEval_EvalFrameDefault
W0426 16:23:18.350363 19117 init.cc:217]     @     0x562d68adb4eb _PyFunction_FastCallDict
W0426 16:23:18.350687 19117 init.cc:217]     @     0x562d68afa703 _PyObject_Call_Prepend
W0426 16:23:18.350849 19117 init.cc:217]     @     0x562d68b341fa slot_tp_call
W0426 16:23:18.351168 19117 init.cc:217]     @     0x562d68b3511b _PyObject_FastCallKeywords
W0426 16:23:18.351512 19117 init.cc:217]     @     0x562d68ba12ce _PyEval_EvalFrameDefault
W0426 16:23:18.351837 19117 init.cc:217]     @     0x562d68ada528 _PyEval_EvalCodeWithName
W0426 16:23:18.352166 19117 init.cc:217]     @     0x562d68adb5b4 _PyFunction_FastCallDict
W0426 16:23:18.352486 19117 init.cc:217]     @     0x562d68afa703 _PyObject_Call_Prepend
W0426 16:23:18.352840 19117 init.cc:217]     @     0x562d68aeccee PyObject_Call
Aborted (core dumped)
已做numpy回退到1.17.4还是报这个错误。

**Comment by still-wait** [comment]
@joshuazm `terminate called without an active exception`之前的log信息麻烦也贴一下

**Comment by joshuazm** [comment]
> @joshuazm `terminate called without an active exception`之前的log信息麻烦也贴一下


root@ecs-1e61-0328538:PaddleDetection # python -u tools/eval.py -c configs/dcn/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco.yml  -o weights=output/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco/model_final
/opt/anaconda3/bin/anaconda/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, defaultdict
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2020-04-26 17:24:07,469-INFO: 1121 samples in file dataset/dx/dx_val.json
2020-04-26 17:24:07,469-INFO: places would be ommited when DataLoader is not iterable
W0426 17:24:08.080296  1069 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.2, Runtime API Version: 10.0
W0426 17:24:08.083788  1069 device_context.cc:245] device: 0, cuDNN Version: 7.6.
2020-04-26 17:24:09,276-INFO: Loading parameters from output/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco/model_final...
2020-04-26 17:24:09,277-WARNING: output/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco/model_final.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-04-26 17:24:09,277-WARNING: output/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco/model_final.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-04-26 17:24:09,278-WARNING: variable file [ output/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco/model_final/28400.pdmodel output/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco/model_final/28400.pdopt output/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco/model_final/28400.pdparams ] not used
2020-04-26 17:24:09,278-WARNING: variable file [ output/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco/model_final/28400.pdmodel output/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco/model_final/28400.pdopt output/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco/model_final/28400.pdparams ] not used
/opt/anaconda3/bin/anaconda/lib/python3.7/site-packages/paddle/fluid/executor.py:804: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
I0426 17:24:09.288731  1069 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I0426 17:24:09.298132  1069 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0426 17:24:09.306345  1069 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0426 17:24:09.312530  1069 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
2020-04-26 17:24:15,429-INFO: Test iter 0
2020-04-26 17:24:46,104-INFO: Test finish iter 36
2020-04-26 17:24:46,104-INFO: Total number of images: 1121, inference time: 30.44263111069006 fps.
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
2020-04-26 17:24:54,139-INFO: Start evaluate...
Loading and preparing results...
DONE (t=1.29s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=23.51s).
Accumulating evaluation results...
DONE (t=3.60s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
terminate called without an active exception
W0426 17:25:23.076860  1139 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0426 17:25:23.076881  1139 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0426 17:25:23.076887  1139 init.cc:214] The detail failure signal is:

W0426 17:25:23.076897  1139 init.cc:217] *** Aborted at 1587893123 (unix time) try "date -d @1587893123" if you are using GNU date ***
W0426 17:25:23.079318  1139 init.cc:217] PC: @                0x0 (unknown)
W0426 17:25:23.079393  1139 init.cc:217] *** SIGABRT (@0x42d) received by PID 1069 (TID 0x7f90d504f700) from PID 1069; stack trace: ***
W0426 17:25:23.081609  1139 init.cc:217]     @     0x7f912b27d390 (unknown)
W0426 17:25:23.083703  1139 init.cc:217]     @     0x7f912aed7428 gsignal
W0426 17:25:23.085793  1139 init.cc:217]     @     0x7f912aed902a abort
W0426 17:25:23.087452  1139 init.cc:217]     @     0x7f910d8a63df __gnu_cxx::__verbose_terminate_handler()
W0426 17:25:23.089066  1139 init.cc:217]     @     0x7f910d8a4b16 __cxxabiv1::__terminate()
W0426 17:25:23.090749  1139 init.cc:217]     @     0x7f910d8a4b4c std::terminate()
W0426 17:25:23.092308  1139 init.cc:217]     @     0x7f910d8a481e __gxx_personality_v0
W0426 17:25:23.093935  1139 init.cc:217]     @     0x7f910e386045 _Unwind_ForcedUnwind_Phase2
W0426 17:25:23.095546  1139 init.cc:217]     @     0x7f910e38631b _Unwind_ForcedUnwind
W0426 17:25:23.097645  1139 init.cc:217]     @     0x7f912b27c070 __GI___pthread_unwind
W0426 17:25:23.099712  1139 init.cc:217]     @     0x7f912b274845 __pthread_exit
W0426 17:25:23.100077  1139 init.cc:217]     @     0x55e3e06067a9 PyThread_exit_thread
W0426 17:25:23.100183  1139 init.cc:217]     @     0x55e3e048094f PyEval_RestoreThread.cold.794
W0426 17:25:23.101049  1139 init.cc:217]     @     0x7f91082abcde (unknown)
W0426 17:25:23.101444  1139 init.cc:217]     @     0x55e3e057eea4 _PyMethodDef_RawFastCallKeywords
W0426 17:25:23.101814  1139 init.cc:217]     @     0x55e3e057efc1 _PyCFunction_FastCallKeywords
W0426 17:25:23.102170  1139 init.cc:217]     @     0x55e3e05f3e8c _PyEval_EvalFrameDefault
W0426 17:25:23.102496  1139 init.cc:217]     @     0x55e3e052d528 _PyEval_EvalCodeWithName
W0426 17:25:23.102833  1139 init.cc:217]     @     0x55e3e052e5b4 _PyFunction_FastCallDict
W0426 17:25:23.103157  1139 init.cc:217]     @     0x55e3e054d703 _PyObject_Call_Prepend
W0426 17:25:23.103322  1139 init.cc:217]     @     0x55e3e05871fa slot_tp_call
W0426 17:25:23.103648  1139 init.cc:217]     @     0x55e3e058811b _PyObject_FastCallKeywords
W0426 17:25:23.104015  1139 init.cc:217]     @     0x55e3e05f3c16 _PyEval_EvalFrameDefault
W0426 17:25:23.104344  1139 init.cc:217]     @     0x55e3e052e4eb _PyFunction_FastCallDict
W0426 17:25:23.104660  1139 init.cc:217]     @     0x55e3e054d703 _PyObject_Call_Prepend
W0426 17:25:23.104830  1139 init.cc:217]     @     0x55e3e05871fa slot_tp_call
W0426 17:25:23.105159  1139 init.cc:217]     @     0x55e3e058811b _PyObject_FastCallKeywords
W0426 17:25:23.105521  1139 init.cc:217]     @     0x55e3e05f42ce _PyEval_EvalFrameDefault
W0426 17:25:23.105851  1139 init.cc:217]     @     0x55e3e052d528 _PyEval_EvalCodeWithName
W0426 17:25:23.106175  1139 init.cc:217]     @     0x55e3e052e5b4 _PyFunction_FastCallDict
W0426 17:25:23.106493  1139 init.cc:217]     @     0x55e3e054d703 _PyObject_Call_Prepend
W0426 17:25:23.106849  1139 init.cc:217]     @     0x55e3e053fcee PyObject_Call
Aborted (core dumped)

**Comment by still-wait** [comment]
@joshuazm 请设置`-o weights=output/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco/model_final/28400.pdparams`

**Comment by qingqing01** [comment]
@joshuazm 上面错误，看着是已经评估完，推出时报的错，应该不影响评估。 不过mAP都是0，觉得还是模型没有训练好。

**Comment by qingqing01** [comment]
@joshuazm 时间较久了，若有还有问题，可以再开issue，先关闭此issue
