### ISSUE TITLE
使用trt版paddle inference library与安装tensorrt出现问题

### ISSUE THREAD

**Issue by TTgogogo** [PaddlePaddle/PaddleDetection#5550]
提示You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found.
但我已经添加了C:\Program Files\NVIDIA\TensorRT-7.2.1.6\bin到环境变量了，请问是怎么回事呢？

**Comment by wangxinxin08** [comment]
C:\Program Files\NVIDIA\TensorRT-7.2.1.6\**lib** 添加到环境变量试下

**Comment by TTgogogo** [comment]
添加了依然有这一问题呢

> C:\Program Files\NVIDIA\TensorRT-7.2.1.6*_lib_* 添加到环境变量试下

**Comment by wangxinxin08** [comment]
@TTgogogo  你的报错是说tensorrt动态库无法加载，动态库一般存在于lib目录，你可以先检查下C:\Program Files\NVIDIA\TensorRT-7.2.1.6\lib 目录是否存在，再确认下路径设置成功，再运行试试
