### ISSUE TITLE
Faster-rcnn 中的nms_thresh设置

### ISSUE THREAD

**Issue by Liqq1** [PaddlePaddle/PaddleDetection#5551]
您好，我想问一下Faster-rcnn 中的nms_thresh具体是什么含义？
当我将nms_thresh设为0的时候，test出来的结果仍然有很多重合的bbox
（当nms_thresh=0时，同类的bbox不是应该没有重合吗？）
![A6679F2ED4F37EE9B3A5DC98CC07E5CA](https://user-images.githubusercontent.com/54054113/161014263-db2f4374-b97d-47dd-a102-e157206f670f.png)

**Comment by wangxinxin08** [comment]
你修改的是哪里的nms_thresh啊？另外这几个框(颜色有点难以区分)是同一个类别吗？

**Comment by Liqq1** [comment]
> 

Q1：我修改的是faster_rcnn_r50.yml里面的
![2C797CDD19AD09079F4E9F237B6A7A98](https://user-images.githubusercontent.com/54054113/161037920-cba2d3cf-a928-469b-a24a-b1ed1114da18.png)

Q2: 是同一个类别的（我整个就数据集就放了一个类别）

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/faster_rcnn/_base_/faster_rcnn_r50.yml#L66 可以修改这里的nms阈值，rpn部分的阈值只影响第一阶段产生的proposal，可以在网络后处理的地方调整
