### ISSUE TITLE
Nano开发板，安装系统后py3.7.1 与官方的最低3.6不匹配？ 一直安装不了推理库

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/PaddleDetection#5554]
Nano开发板，安装系统后py3.7.1 与官方的 https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python
最低3.6不匹配，安装conda后指定安装py版本3.6.9同样不匹配，球球了，官方大大出一个py3.7的Nanogpu推理库吧

目前安装完成nano的系统后，自带的python版本是3.7.1，安装conda之后新建环境py3.6.9，pip导入一直显示非法指令(已转核心储存)，但新建3.7以上的环境就可以正常导入py的依赖包。但是安装3.7以上的py之后，又不能安装飞桨2.2.2 cp3.6的whl了，报错不支持导入。尝试过卸载系统自带的python版本是3.7.1，但是整个linux系统直接崩了，在conda里面又不能下载py3.6.9用pip指令或者conda指令卡主好几天了。 望能够快速解答 谢谢

**Comment by wangxinxin08** [comment]
收到，我们向Paddle Inference反馈下

**Comment by song121982** [comment]
同求jetson agx python3.7推理库，自已一直编译失败，jetson上面安装miniconda又只能新建3.7以上的python环境，而paddle官方又只出了3.6的预测库，只有jetpack原有的基环境是3.6.9的，一旦崩了就没了哇，，， @wangxinxin08

**Comment by Wangzheee** [comment]
请问是用 JetPack 4.6.1 预装系统，发现jetson自带的python就是3.7吗？

**Comment by Wei-JL** [comment]
> 请问是用 JetPack 4.6.1 预装系统，发现jetson自带的python就是3.7吗？

您好，预装的系统是官方下载的，应该是最新的。能确定一点的是 系统自带的python就是3.7.1  而且删除后 整个linux会在15-20分钟崩了 无法进入系统

**Comment by Wangzheee** [comment]
哦哦，好的，由于jetpack最新更新，我们发布的包还没来得及更新，最近两周内我们会根据 jetson 最新的环境更新包，感谢支持~

**Comment by Wangzheee** [comment]
刚问了下发版计划，2.3会在两周后发版，建议使用 paddle 2.3 + jetson最新的环境进行使用，python3.7的支持会在 2.3 同步发包

**Comment by Wei-JL** [comment]
> 刚问了下发版计划，2.3会在两周后发版，建议使用 paddle 2.3 + jetson最新的环境进行使用，python3.7的支持会在 2.3 同步发包

太感谢了，我想了很多办法解决。一周了 实在解决不了  重装系统都有三次 ，多谢

**Comment by Wangzheee** [comment]
> > 刚问了下发版计划，2.3会在两周后发版，建议使用 paddle 2.3 + jetson最新的环境进行使用，python3.7的支持会在 2.3 同步发包

**Comment by leiqing1** [comment]
> 点的是 系统自带的pytho

你好，如果是nano自带的python是3.7， paddle inference下载的nano包是python3.6，这种情况可以直接在nano上再安装一个python3.6，然后设置成使用python3.6即可，linux系统多了python版本切换配置是很常见的操作。（注意：系统自带的python版本不能随便删除，因为很多系统文件会用到的）
