### ISSUE TITLE
陣列出錯

### ISSUE THREAD

**Issue by LiaoCC0323** [PaddlePaddle/PaddleDetection#5556]
我照著PP-Tracking Python端预测部署去執行模型基于Python去做跨镜头跟踪
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/pptracking/python/README.md
但都出現IndexError: list index out of range
![擷取](https://user-images.githubusercontent.com/88362160/161058247-6388e0ad-b468-4c78-80cd-9553d80c9565.PNG)

**Comment by nemonameless** [comment]
配置文件有没有更改？几个测试视频的名字是什么呢？可能是视频名字和你配置的cameras_bias没有对应上。

**Comment by LiaoCC0323** [comment]
我的配置文件和視頻都是用
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/pptracking/python/README.md
提供的沒有自己額外更動

> 配置文件有沒有什麼測試視頻的名字是改變？可能是視頻名字和你配置的cameras_bias沒有上。

![擷取](https://user-images.githubusercontent.com/88362160/161204472-9b9cc1da-713c-43ce-8ac3-09135a62f20a.PNG)

**Comment by heiheiheiheiheihei** [comment]
请问如何解决，我也遇到了同样的问题，使用了跟文档中一样的命令，一样的配置。

**Comment by chenfang0927** [comment]
我也是这样的
