### ISSUE TITLE
ImportError: /root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#5561]
ImportError: /root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

怎么解决这个问题？以前能用的，后来Ubuntu系统有东西更新后就出这个问题了，当时模型还能继续训练

>>> import paddle
Error: Can not import avx core while this file exists: /root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/core.py", line 294, in <module>
    raise e
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/core.py", line 256, in <module>
    from .core_avx import *
ImportError: /root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE
>>>

**Comment by LMR2018** [comment]
(py37) root@alg-ubuntu:/home/alg/ai# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.5.0-0ubuntu4' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.5.0 (Ubuntu 8.5.0-0ubuntu4)

**Comment by wangxinxin08** [comment]
是gcc版本原先是8.2吧，现在是更新到8.5了是吗？

**Comment by LMR2018** [comment]
> 是gcc版本原先是8.2吧，现在是更新到8.5了是吗？

@wangxinxin08 以前是10.3.0的，后来我好像看到变成11点多的版本，后面网上看了一些帖子，我再降为8.5的，不过还是出现这个问题，不知道是什么原因出现的这个错误？

**Comment by wangxinxin08** [comment]
报错信息显示是GLIBC版本或者GCC版本问题，可以回退GLIBC版本试试

**Comment by LMR2018** [comment]
> 

@wangxinxin08 我现在的系统是Ubuntu21.10，能不能正常支持paddle-gpu的使用？

**Comment by wangxinxin08** [comment]
> > 
> 
> @wangxinxin08 我现在的系统是Ubuntu21.10，能不能正常支持paddle-gpu的使用？

可以拉取docker，避免本地环境的问题https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html#linuxdocker
