### ISSUE TITLE
[ppyoloe] TypeError: __init__() got an unexpected keyword argument 'epochs'

### ISSUE THREAD

**Issue by jeyoucy** [PaddlePaddle/PaddleDetection#5562]
## 📖  ppyoloe 配置文件参数无法读入

在下载了官方的ppyoloe模型以及配置文件后，本地推理了一下，出现如下错误：
![2022-04-01 12-11-41屏幕截图](https://user-images.githubusercontent.com/41880505/161194125-b61df9b6-b96e-4689-830c-58a8442f929c.png)

于是查找了一下'epochs'在哪个位置，发现在如下位置：
![2022-04-01 12-11-56屏幕截图](https://user-images.githubusercontent.com/41880505/161194243-1bad06b9-7515-4d7f-9695-7c1d79aa1136.png)

本地的paddle版本都是没什么问题的(截至2022-4-1)：
![2022-04-01 12-10-07屏幕截图](https://user-images.githubusercontent.com/41880505/161194571-b818ddce-6447-4900-98a4-ee7ae0fab5f6.png)

请问配置文件如何修改一下能正常呢？

**Comment by jeyoucy** [comment]
推理使用的是tools里的infer.py  指定的ppyoloe_l模型及参数

**Comment by wangxinxin08** [comment]
paddledet的版本太低了，这个参数是PaddleDetection 2.4引入的，可以考虑pip uninstall paddledet，并git clone最新的PaddleDetection/release/2.4试下

**Comment by jeyoucy** [comment]
paddledet更换为2.4.0后可用了，多谢
