### ISSUE TITLE
关于PPYOLOE的细节问题

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#5563]
您好，我最近写了两个关于PPYOLOE的介绍项目，但是我害怕有一些地方讲的不太对，不知道能不能帮忙看一下，哪里不对的地方我去进行修改

[PPYOLOE 1 Backbone](https://aistudio.baidu.com/aistudio/projectdetail/3700074)
[PPYOLOe 2 Neck](https://aistudio.baidu.com/aistudio/projectdetail/3722610)

**Comment by lyuwenyu** [comment]
优秀 会安排同学看一下

**Comment by sdreamforchen** [comment]
> 优秀 会安排同学看一下

您好，从源代码class CSPResStage(nn.Layer)看，论文中的Figure 3(d)是否画错了。右边分支的输入应该就是x，而不是（1X1）后的值吧。

**Comment by violetweir** [comment]
> > 优秀 会安排同学看一下
> 
> 您好，从源代码class CSPResStage(nn.Layer)看，论文中的Figure 3(d)是否画错了。右边分支的输入应该就是x，而不是（1X1）后的值吧。
这个我看了一下在训练的时候是tensor分别经过1x1和3x3的卷积后相加，在预测的时候只经过3x3的卷积好像是，这个是我个人的理解呀，我自己看的时候记得是这样的。

**Comment by sdreamforchen** [comment]
> 

这是一前一后，是串行，不是并行的可以re-parameter。
