### ISSUE TITLE
新版picodet简化时出错

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#5566]
请问新版picodet简化出现如下错误是什么原因
![image](https://user-images.githubusercontent.com/48303408/161225489-7ca7e6c4-a3e7-4280-9d62-49ebb2631bfd.png)

**Comment by yghstill** [comment]
由于新版PicoDet支持了batch size大于1，并且后处理操作放进了网络中，所以导出时需请指定动态shape：
```
python3.7 -m onnxsim picodet_s_416_coco.onnx picodet_s_processed.onnx --dynamic-input-shape --input-shape image:1,3,416,416
```
PS：转出onnx的所有demo正在升级中，即将发布，之前的demo暂时无法使用，敬请关注~

**Comment by Dandelion111** [comment]
> 由于新版PicoDet支持了batch size大于1，并且后处理操作放进了网络中，所以导出时需请指定动态shape：
> 
> ```
> python3.7 -m onnxsim picodet_s_416_coco.onnx picodet_s_processed.onnx --dynamic-input-shape --input-shape image:1,3,416,416
> ```
> 
> PS：转出onnx的所有demo正在升级中，即将发布，之前的demo暂时无法使用，敬请关注~

我看那说明的意思后处理部分可以选择是否导出，如果选择导出的话，之前的demo可以用吗
![image](https://user-images.githubusercontent.com/48303408/161262904-af938022-e231-40ee-a147-4005d3814ac4.png)

**Comment by yghstill** [comment]
@Dandelion111 如果导出的话，之前的demo用不了了，目前能用的有：paddle lite和openvino，其他的正在更新中。

**Comment by Dandelion111** [comment]
> @Dandelion111 如果导出的话，之前的demo用不了了，目前能用的有：paddle lite和openvino，其他的正在更新中。

好的，谢谢大佬

**Comment by Dandelion111** [comment]
> @Dandelion111 如果导出的话，之前的demo用不了了，目前能用的有：paddle lite和openvino，其他的正在更新中。

大佬你好，按照您的方法简化之后，无法转openvino模型，，转换命令和错误如下：
![image](https://user-images.githubusercontent.com/48303408/162407203-05a8d2eb-cea1-4dc1-8869-be981205df9a.png)

不加后面的input_shape也不对：
![image](https://user-images.githubusercontent.com/48303408/162407413-6a9970d5-9918-46dd-b666-07e1782c5f3c.png)
