### ISSUE TITLE
CPU模式切换为GPU模式，加速并不明显

### ISSUE THREAD

**Issue by TTgogogo** [PaddlePaddle/PaddleDetection#5568]
将PaddleDetection::ObjectDetector det(FLAGS_model_dir, "CPU");变为PaddleDetection::ObjectDetector det(FLAGS_model_dir, "GPU", false, 1, "trt_fp16");
推理变得更慢，半天都没有显示结果。是设置不对吗？

**Comment by lyuwenyu** [comment]
用trt 推理的话会先进行engine的生成

**Comment by TTgogogo** [comment]
@lyuwenyu 改成PaddleDetection::ObjectDetector det(FLAGS_model_dir, "GPU", false, 1, "paddle");就没那么慢了，但是相比CPU模式，加速不是很明显的，还有加速的办法吗？

**Comment by qingqing01** [comment]
@TTgogogo 

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/cpp/docs/linux_build.md

具体的设置参数参考这里。您设置没问题。但看速度，需要调过前几轮启动时间，再统计时间。 采用TensorRT启动时间较久，需要等一下。
