### ISSUE TITLE
[BUG]PPYOLOE训练问题

### ISSUE THREAD

**Issue by m00nLi** [PaddlePaddle/PaddleDetection#5574]
训练yoloe_s报错,提示：
```
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of 
X = [1, 3024, 2] and the shape of Y = [8400, 2]. Received [3024] in X is not equal to [8400] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, 
but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] 
(at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < elementwise_add > error]
```

**Comment by nemonameless** [comment]
请拉取最新代码运行，提供训练命令、版本信息、做了什么更改，以及更多的报错截图信息，谢谢。

**Comment by wangxinxin08** [comment]
修改输入尺寸的话，需要在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/_base_/ppyoloe_reader.yml#L23 和 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/_base_/ppyoloe_crn.yml#L31 同步修改，或者你也可以拉取最新版的代码，最新版的代码里面对其做了易用性提升，只需修改一次即可

**Comment by m00nLi** [comment]
1. 我那天是上午拉取的代码，用自己的数据训练，就出现上面的问题了，batch-size不一样时，上面报错的不匹配的维度也不一样。
输入尺寸没改，我那天试了我的数据集用picodet是可以正常训练的。
2. 今天早上重新拉取代码，可以正常训练了。但感觉训练有点慢，我的显卡是8*TiTan RTX 24G的，大概5万张图片，训练200轮提示大概要2天？你们用yoloe-l-640训练coco2017大概需要多长时间？

**Comment by wangxinxin08** [comment]
> 1. 我那天是上午拉取的代码，用自己的数据训练，就出现上面的问题了，batch-size不一样时，上面报错的不匹配的维度也不一样。
>    输入尺寸没改，我那天试了我的数据集用picodet是可以正常训练的。
> 2. 今天早上重新拉取代码，可以正常训练了。但感觉训练有点慢，我的显卡是8*TiTan RTX 24G的，大概5万张图片，训练200轮提示大概要2天？你们用yoloe-l-640训练coco2017大概需要多长时间？

PP-YOLOE-l训练COCO大概需要4天多的时间

**Comment by keyxuliang** [comment]
请问这个是什么原因啊？只是换了自己的数据
`  pred_bboxes = self._bbox_decode(anchor_points_s, pred_distri)
  File "/ppdet/modeling/heads/ppyoloe_head.py", line 237, in _bbox_decode
    pred_dist = F.softmax(pred_dist.reshape([b, l, 4, self.reg_max + 1
  File "/python3.8/site-packages/paddle/tensor/linalg.py", line 139, in matmul
    return op(x, y, 'trans_x', transpose_x, 'trans_y', transpose_y)
OSError: (External) CUBLAS error(7). 
  [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:55)
  [operator < matmul_v2 > error]`

**Comment by wangxinxin08** [comment]
> 请问这个是什么原因啊？只是换了自己的数据 ` pred_bboxes = self._bbox_decode(anchor_points_s, pred_distri) File "/ppdet/modeling/heads/ppyoloe_head.py", line 237, in _bbox_decode pred_dist = F.softmax(pred_dist.reshape([b, l, 4, self.reg_max + 1 File "/python3.8/site-packages/paddle/tensor/linalg.py", line 139, in matmul return op(x, y, 'trans_x', transpose_x, 'trans_y', transpose_y) OSError: (External) CUBLAS error(7). [Hint: 'CUBLAS_STATUS_INVALID_VALUE'. An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:55) [operator < matmul_v2 > error]`

建议使用PaddlePaddle 2.2.2版本以及PaddleDetection release/2.4训练哈

**Comment by keyxuliang** [comment]
> > 请问这个是什么原因啊？只是换了自己的数据 ` pred_bboxes = self._bbox_decode(anchor_points_s, pred_distri) File "/ppdet/modeling/heads/ppyoloe_head.py", line 237, in _bbox_decode pred_dist = F.softmax(pred_dist.reshape([b, l, 4, self.reg_max + 1 File "/python3.8/site-packages/paddle/tensor/linalg.py", line 139, in matmul return op(x, y, 'trans_x', transpose_x, 'trans_y', transpose_y) OSError: (External) CUBLAS error(7). [Hint: 'CUBLAS_STATUS_INVALID_VALUE'. An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:55) [operator < matmul_v2 > error]`
> 
> 建议使用PaddlePaddle 2.2.2版本以及PaddleDetection release/2.4训练哈

对的，两个版本都是和你说的是一致的，我训练solov2都没问题，同样的数据拿来训练ppyoloe就报这个错，今天上午才拉的最新的代码

**Comment by wangxinxin08** [comment]
> > > 请问这个是什么原因啊？只是换了自己的数据 ` pred_bboxes = self._bbox_decode(anchor_points_s, pred_distri) File "/ppdet/modeling/heads/ppyoloe_head.py", line 237, in _bbox_decode pred_dist = F.softmax(pred_dist.reshape([b, l, 4, self.reg_max + 1 File "/python3.8/site-packages/paddle/tensor/linalg.py", line 139, in matmul return op(x, y, 'trans_x', transpose_x, 'trans_y', transpose_y) OSError: (External) CUBLAS error(7). [Hint: 'CUBLAS_STATUS_INVALID_VALUE'. An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:55) [operator < matmul_v2 > error]`
> > 
> > 
> > 建议使用PaddlePaddle 2.2.2版本以及PaddleDetection release/2.4训练哈
> 
> 对的，两个版本都是和你说的是一致的，我训练solov2都没问题，同样的数据拿来训练ppyoloe就报这个错，今天上午才拉的最新的代码

我用上述版本并没有报错哈，刚刚验证过，建议先检查下环境，包括Paddle版本以及与cuda版本和cudnn版本是否匹配，PaddleDetection版本

**Comment by code10086web** [comment]
> 1. 我那天是上午拉取的代码，用自己的数据训练，就出现上面的问题了，batch-size不一样时，上面报错的不匹配的维度也不一样。
>    输入尺寸没改，我那天试了我的数据集用picodet是可以正常训练的。
> 2. 今天早上重新拉取代码，可以正常训练了。但感觉训练有点慢，我的显卡是8*TiTan RTX 24G的，大概5万张图片，训练200轮提示大概要2天？你们用yoloe-l-640训练coco2017大概需要多长时间？

你好，请问您的batch_size设置多大呀，我使用的8*RTX 3090 24g,大概2000张图片，batch_size设置的为4，但是训练一个epoch就预估一天左右，这太长了，想问下您有什么建议嘛，或者您那边可以试着设置batch_size比较小的情况观察下训练时长吗？实在麻烦了。

**Comment by wangxinxin08** [comment]
> > 1. 我那天是上午拉取的代码，用自己的数据训练，就出现上面的问题了，batch-size不一样时，上面报错的不匹配的维度也不一样。
> >    输入尺寸没改，我那天试了我的数据集用picodet是可以正常训练的。
> > 2. 今天早上重新拉取代码，可以正常训练了。但感觉训练有点慢，我的显卡是8*TiTan RTX 24G的，大概5万张图片，训练200轮提示大概要2天？你们用yoloe-l-640训练coco2017大概需要多长时间？
> 
> 你好，请问您的batch_size设置多大呀，我使用的8*RTX 3090 24g,大概2000张图片，batch_size设置的为4，但是训练一个epoch就预估一天左右，这太长了，想问下您有什么建议嘛，或者您那边可以试着设置batch_size比较小的情况观察下训练时长吗？实在麻烦了。

训练一个epoch就1天不太正常，2000张图片应该几十分钟就训练完了，你说的一个epoch是指训练300个epoch吗？

**Comment by code10086web** [comment]
不是，就是单独一个epoch，想确定下您的每个gpu上的图片数量是多少




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月11日(星期一) 上午10:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] [BUG]PPYOLOE训练问题 (Issue #5574)





    
我那天是上午拉取的代码，用自己的数据训练，就出现上面的问题了，batch-size不一样时，上面报错的不匹配的维度也不一样。
 输入尺寸没改，我那天试了我的数据集用picodet是可以正常训练的。
 
今天早上重新拉取代码，可以正常训练了。但感觉训练有点慢，我的显卡是8*TiTan RTX 24G的，大概5万张图片，训练200轮提示大概要2天？你们用yoloe-l-640训练coco2017大概需要多长时间？
   
你好，请问您的batch_size设置多大呀，我使用的8*RTX 3090 24g,大概2000张图片，batch_size设置的为4，但是训练一个epoch就预估一天左右，这太长了，想问下您有什么建议嘛，或者您那边可以试着设置batch_size比较小的情况观察下训练时长吗？实在麻烦了。
  
训练一个epoch就1天不太正常，2000张图片应该几十分钟就训练完了，你说的一个epoch是指训练300个epoch吗？

**Comment by wangxinxin08** [comment]
> 不是，就是单独一个epoch，想确定下您的每个gpu上的图片数量是多少
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年4月11日(星期一) 上午10:55 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [PaddlePaddle/PaddleDetection] [BUG]PPYOLOE训练问题 (Issue #5574) 我那天是上午拉取的代码，用自己的数据训练，就出现上面的问题了，batch-size不一样时，上面报错的不匹配的维度也不一样。 输入尺寸没改，我那天试了我的数据集用picodet是可以正常训练的。 今天早上重新拉取代码，可以正常训练了。但感觉训练有点慢，我的显卡是8*TiTan RTX 24G的，大概5万张图片，训练200轮提示大概要2天？你们用yoloe-l-640训练coco2017大概需要多长时间？ 你好，请问您的batch_size设置多大呀，我使用的8*RTX 3090 24g,大概2000张图片，batch_size设置的为4，但是训练一个epoch就预估一天左右，这太长了，想问下您有什么建议嘛，或者您那边可以试着设置batch_size比较小的情况观察下训练时长吗？实在麻烦了。 训练一个epoch就1天不太正常，2000张图片应该几十分钟就训练完了，你说的一个epoch是指训练300个epoch吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

1个epoch 2000张图片训练一天是不可能的，建议先检查下训练环境是否正常吧

**Comment by m00nLi** [comment]
还是提一下吧，一开始我看训练正常后没仔细看，但前几天训练了59轮后看一下ap情况，发现全是0，默认是每10轮eval一次，我发现前面的eval结果也都是0。用同样的数据训练picodet正常，ap也正常，可以排除数据及数据格式的问题吧

**Comment by m00nLi** [comment]
> > 1. 我那天是上午拉取的代码，用自己的数据训练，就出现上面的问题了，batch-size不一样时，上面报错的不匹配的维度也不一样。
> >    输入尺寸没改，我那天试了我的数据集用picodet是可以正常训练的。
> > 2. 今天早上重新拉取代码，可以正常训练了。但感觉训练有点慢，我的显卡是8*TiTan RTX 24G的，大概5万张图片，训练200轮提示大概要2天？你们用yoloe-l-640训练coco2017大概需要多长时间？
> 
> 你好，请问您的batch_size设置多大呀，我使用的8*RTX 3090 24g,大概2000张图片，batch_size设置的为4，但是训练一个epoch就预估一天左右，这太长了，想问下您有什么建议嘛，或者您那边可以试着设置batch_size比较小的情况观察下训练时长吗？实在麻烦了。

我设的batch-size是8，前些天训练了59轮看下情况，发现AP都是0，就没怎么看了

**Comment by m00nLi** [comment]
> > 1. 我那天是上午拉取的代码，用自己的数据训练，就出现上面的问题了，batch-size不一样时，上面报错的不匹配的维度也不一样。
> >    输入尺寸没改，我那天试了我的数据集用picodet是可以正常训练的。
> > 2. 今天早上重新拉取代码，可以正常训练了。但感觉训练有点慢，我的显卡是8*TiTan RTX 24G的，大概5万张图片，训练200轮提示大概要2天？你们用yoloe-l-640训练coco2017大概需要多长时间？
> 
> 你好，请问您的batch_size设置多大呀，我使用的8*RTX 3090 24g,大概2000张图片，batch_size设置的为4，但是训练一个epoch就预估一天左右，这太长了，想问下您有什么建议嘛，或者您那边可以试着设置batch_size比较小的情况观察下训练时长吗？实在麻烦了。

我设的batch-size是8，前些天训练了59轮看下情况，发现AP都是0，就没怎么看了

**Comment by wangxinxin08** [comment]
> > > 1. 我那天是上午拉取的代码，用自己的数据训练，就出现上面的问题了，batch-size不一样时，上面报错的不匹配的维度也不一样。
> > >    输入尺寸没改，我那天试了我的数据集用picodet是可以正常训练的。
> > > 2. 今天早上重新拉取代码，可以正常训练了。但感觉训练有点慢，我的显卡是8*TiTan RTX 24G的，大概5万张图片，训练200轮提示大概要2天？你们用yoloe-l-640训练coco2017大概需要多长时间？
> > 
> > 
> > 你好，请问您的batch_size设置多大呀，我使用的8*RTX 3090 24g,大概2000张图片，batch_size设置的为4，但是训练一个epoch就预估一天左右，这太长了，想问下您有什么建议嘛，或者您那边可以试着设置batch_size比较小的情况观察下训练时长吗？实在麻烦了。
> 
> 我设的batch-size是8，前些天训练了59轮看下情况，发现AP都是0，就没怎么看了

@m00nLi 你的配置文件和log文件方便发下吗？我帮你看看是什么问题

**Comment by wangxinxin08** [comment]
> 需要

@m00nLi 这个明显不合理，初步判断可能是配置文件没有正确设置

**Comment by wangxinxin08** [comment]
> 还是提一下吧，一开始我看训练正常后没仔细看，但前几天训练了59轮后看一下ap情况，发现全是0，默认是每10轮eval一次，我发现前面的eval结果也都是0。用同样的数据训练picodet正常，ap也正常，可以排除数据及数据格式的问题吧

@m00nLi 这个明显不合理，初步判断可能是配置文件没有正确设置

**Comment by code10086web** [comment]
在pp-yoloe-l我的结果可以正常产生了，有问题就是模型的评估时间为什么只有11fps左右，在rtx 3090，测试时候batch_size=1,按理来说不该这么慢，这个速度是正常吗？

**Comment by wangxinxin08** [comment]
> 在pp-yoloe-l我的结果可以正常产生了，有问题就是模型的评估时间为什么只有11fps左右，在rtx 3090，测试时候batch_size=1,按理来说不该这么慢，这个速度是正常吗？

不正常，rtx 3090建议使用TensorRT测速，测速方法参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe#speed-testing

**Comment by m00nLi** [comment]
> > 还是提一下吧，一开始我看训练正常后没仔细看，但前几天训练了59轮后看一下ap情况，发现全是0，默认是每10轮eval一次，我发现前面的eval结果也都是0。用同样的数据训练picodet正常，ap也正常，可以排除数据及数据格式的问题吧
> 
> @m00nLi 这个明显不合理，初步判断可能是配置文件没有正确设置

1. 配置文件我没改什么的，除了dataset部分改成自己的数据之外，runtime、__base__里的三个yml都没改;
2. 之前AP是0的情况没有截屏，在log下看了workerlog
[workerlog.0.txt](https://github.com/PaddlePaddle/PaddleDetection/files/8470315/workerlog.0.txt)
部分如下：
![image](https://user-images.githubusercontent.com/102453574/162899390-51de1b55-c84c-4baf-874f-62097bad5a10.png)
从workerlog里可以看出，网络初始学习率0.06， 随着训练loss值变得越来越大。可能学习率太大了，但是我看你们文档说这个学习率是按照4卡设置的，我用的8卡，其实应该再调大的，但是训练时我没改。现在看来在我的数据下学习率可能要调的更小，我后面再测。

**Comment by wangxinxin08** [comment]
> > > 还是提一下吧，一开始我看训练正常后没仔细看，但前几天训练了59轮后看一下ap情况，发现全是0，默认是每10轮eval一次，我发现前面的eval结果也都是0。用同样的数据训练picodet正常，ap也正常，可以排除数据及数据格式的问题吧
> > 
> > 
> > @m00nLi 这个明显不合理，初步判断可能是配置文件没有正确设置
> 
> 1. 配置文件我没改什么的，除了dataset部分改成自己的数据之外，runtime、__base__里的三个yml都没改;
> 2. 之前AP是0的情况没有截屏，在log下看了workerlog
>    [workerlog.0.txt](https://github.com/PaddlePaddle/PaddleDetection/files/8470315/workerlog.0.txt)
>    部分如下：
>    ![image](https://user-images.githubusercontent.com/102453574/162899390-51de1b55-c84c-4baf-874f-62097bad5a10.png)
>    从workerlog里可以看出，网络初始学习率0.06， 随着训练loss值变得越来越大。可能学习率太大了，但是我看你们文档说这个学习率是按照4卡设置的，我用的8卡，其实应该再调大的，但是训练时我没改。现在看来在我的数据下学习率可能要调的更小，我后面再测。

@m00nLi PP-YOLOE-s的学习率是按照8卡，每张卡batch_size是32设置的，你可以看ppyoloe的文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/README_cn.md ，按照学习率线性缩放准则，你如果设置为8卡，每张卡batch_size为8的话，你应该将学习率设置成 0.04 / (8 * 32) * (8 * 8)=0.01

**Comment by m00nLi** [comment]
好的，我后面再试试

**Comment by shuxp** [comment]
一样的错误。
`
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 8400, 2] and the shape of Y = [25200, 2]. Received [8400] in X is not equal to [25200] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < elementwise_add > error]
`

**Comment by shuxp** [comment]
> 一样的错误。 `ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 8400, 2] and the shape of Y = [25200, 2]. Received [8400] in X is not equal to [25200] in Y at i:1. [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240) [operator < elementwise_add > error]`

我解决这个问题了，train/eval/test的时候尺度没对应上，单步调试下就好了，仔细检查下代码resize的尺寸吧。

**Comment by m00nLi** [comment]
> > 一样的错误。 `ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 8400, 2] and the shape of Y = [25200, 2]. Received [8400] in X is not equal to [25200] in Y at i:1. [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240) [operator < elementwise_add > error]`
> 
> 我解决这个问题了，train/eval/test的时候尺度没对应上，单步调试下就好了，仔细检查下代码resize的尺寸吧。

bug太多了，这里设置print_flops就报错了，说明都没有测试过。训练不仅慢，还有训练训练着显存就不够了，我设置全程用最大的单尺度跑，跑几个epoch没问题，train&eval都跑过了，显存还有几个G的空余，你以为不会溢出了，但很明显是你想的简单了，第二天你就会知道，自己错的有多离谱。国产框架有待改善啊。。。

**Comment by shuxp** [comment]
> > > 一样的错误。 `ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 8400, 2] and the shape of Y = [25200, 2]. Received [8400] in X is not equal to [25200] in Y at i:1. [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240) [operator < elementwise_add > error]`
> > 
> > 
> > 我解决这个问题了，train/eval/test的时候尺度没对应上，单步调试下就好了，仔细检查下代码resize的尺寸吧。
> 
> bug太多了，这里设置print_flops就报错了，说明都没有测试过。训练不仅慢，还有训练训练着显存就不够了，我设置全程用最大的单尺度跑，跑几个epoch没问题，train&eval都跑过了，显存还有几个G的空余，你以为不会溢出了，但很明显是你想的简单了，第二天你就会知道，自己错的有多离谱。国产框架有待改善啊。。。

非paddle相关人士。但我现在用的挺好的，det/seg/ocr都在用。

我刚开始用caffe的时候也是一堆问题。有问题，你能发现，那说明你厉害，可以来提issue，或者来帮别人解决，都是技术人，何必这么说。

你现在这心态有点问题，建议你反省下，不然说的难听点，就是*洋*外。

**Comment by m00nLi** [comment]
> > > > 一样的错误。 `ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 8400, 2] and the shape of Y = [25200, 2]. Received [8400] in X is not equal to [25200] in Y at i:1. [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240) [operator < elementwise_add > error]`
> > > 
> > > 
> > > 我解决这个问题了，train/eval/test的时候尺度没对应上，单步调试下就好了，仔细检查下代码resize的尺寸吧。
> > 
> > 
> > bug太多了，这里设置print_flops就报错了，说明都没有测试过。训练不仅慢，还有训练训练着显存就不够了，我设置全程用最大的单尺度跑，跑几个epoch没问题，train&eval都跑过了，显存还有几个G的空余，你以为不会溢出了，但很明显是你想的简单了，第二天你就会知道，自己错的有多离谱。国产框架有待改善啊。。。
> 
> 非paddle相关人士。但我现在用的挺好的，det/seg/ocr都在用。
> 
> 我刚开始用caffe的时候也是一堆问题。有问题，你能发现，那说明你厉害，可以来提issue，或者来帮别人解决，都是技术人，何必这么说。
> 
> 你现在这心态有点问题，建议你反省下，不然说的难听点，就是_洋_外。

确实没你这战狼心态好，要反省一下。
你用着没问题，用的挺好，就不允许别人吐槽了？
不说PaddlePaddle框架，此份repos文档、有些代码、示例中的错误显而易见，写的极其随意，可以看出根本没有看出经过必要的一些测试。
你不 **洋外**，请用gitee，**请自觉禁用舶来品**， **请支持国产**，拜托了

**Comment by shuxp** [comment]
> > > > > 一样的错误。 `ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 8400, 2] and the shape of Y = [25200, 2]. Received [8400] in X is not equal to [25200] in Y at i:1. [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240) [operator < elementwise_add > error]`
> > > > 
> > > > 
> > > > 我解决这个问题了，train/eval/test的时候尺度没对应上，单步调试下就好了，仔细检查下代码resize的尺寸吧。
> > > 
> > > 
> > > bug太多了，这里设置print_flops就报错了，说明都没有测试过。训练不仅慢，还有训练训练着显存就不够了，我设置全程用最大的单尺度跑，跑几个epoch没问题，train&eval都跑过了，显存还有几个G的空余，你以为不会溢出了，但很明显是你想的简单了，第二天你就会知道，自己错的有多离谱。国产框架有待改善啊。。。
> > 
> > 
> > 非paddle相关人士。但我现在用的挺好的，det/seg/ocr都在用。
> > 我刚开始用caffe的时候也是一堆问题。有问题，你能发现，那说明你厉害，可以来提issue，或者来帮别人解决，都是技术人，何必这么说。
> > 你现在这心态有点问题，建议你反省下，不然说的难听点，就是_洋_外。
> 
> 确实没你这战狼心态好，要反省一下。 你用着没问题，用的挺好，就不允许别人吐槽了？ 不说PaddlePaddle框架，此份repos文档、有些代码、示例中的错误显而易见，写的极其随意，可以看出根本没有看出经过必要的一些测试。 你不 **洋外**，请用gitee，**请自觉禁用舶来品**， **请支持国产**，拜托了

有问题，欢迎提出，没必要在这说：国产，不行。。。

ps:你这说法，使用github，都洋外了？你这说法真牛逼。

不占用官方资源在这和你争了，仁者见仁，智者见智，争下去永远没完没了。

over

**Comment by m00nLi** [comment]
> > > > > > 一样的错误。 `ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 8400, 2] and the shape of Y = [25200, 2]. Received [8400] in X is not equal to [25200] in Y at i:1. [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240) [operator < elementwise_add > error]`
> > > > > 
> > > > > 
> > > > > 我解决这个问题了，train/eval/test的时候尺度没对应上，单步调试下就好了，仔细检查下代码resize的尺寸吧。
> > > > 
> > > > 
> > > > bug太多了，这里设置print_flops就报错了，说明都没有测试过。训练不仅慢，还有训练训练着显存就不够了，我设置全程用最大的单尺度跑，跑几个epoch没问题，train&eval都跑过了，显存还有几个G的空余，你以为不会溢出了，但很明显是你想的简单了，第二天你就会知道，自己错的有多离谱。国产框架有待改善啊。。。
> > > 
> > > 
> > > 非paddle相关人士。但我现在用的挺好的，det/seg/ocr都在用。
> > > 我刚开始用caffe的时候也是一堆问题。有问题，你能发现，那说明你厉害，可以来提issue，或者来帮别人解决，都是技术人，何必这么说。
> > > 你现在这心态有点问题，建议你反省下，不然说的难听点，就是_洋_外。
> > 
> > 
> > 确实没你这战狼心态好，要反省一下。 你用着没问题，用的挺好，就不允许别人吐槽了？ 不说PaddlePaddle框架，此份repos文档、有些代码、示例中的错误显而易见，写的极其随意，可以看出根本没有看出经过必要的一些测试。 你不 **洋外**，请用gitee，**请自觉禁用舶来品**， **请支持国产**，拜托了
> 
> 有问题，欢迎提出，没必要在这说：国产，不行。。。
> 
> ps:你这说法，使用github，都洋外了？你这说法真牛逼。
> 
> 不占用官方资源在这和你争了，仁者见仁，智者见智，争下去永远没完没了。
> 
> over

说国产框架有待改善，就是说：国产，不行，就是， **_洋_外**
你这说法更牛逼，厉害了我的战狼

**Comment by wangxinxin08** [comment]
@m00nLi 有问题说问题，ppyoloe在训练的过程中会变更assigner，TAL会占用更多的显存，所以即使你前面能正常运行，后面依然可能爆显存。如果你没有其他的问题的话，我把这个issue关了。另外，我们欢迎用户以一种正常的态度提出自己的意见，反馈问题。如果以一种带有偏见的态度的话，我们也支持你用脚投票！

**Comment by dium6i** [comment]
> > 请问这个是什么原因啊？只是换了自己的数据 ` pred_bboxes = self._bbox_decode(anchor_points_s, pred_distri) File "/ppdet/modeling/heads/ppyoloe_head.py", line 237, in _bbox_decode pred_dist = F.softmax(pred_dist.reshape([b, l, 4, self.reg_max + 1 File "/python3.8/site-packages/paddle/tensor/linalg.py", line 139, in matmul return op(x, y, 'trans_x', transpose_x, 'trans_y', transpose_y) OSError: (External) CUBLAS error(7). [Hint: 'CUBLAS_STATUS_INVALID_VALUE'. An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:55) [operator < matmul_v2 > error]`
> 
> 建议使用PaddlePaddle 2.2.2版本以及PaddleDetection release/2.4训练哈

我遇到了其他的问题，提示“An unsupported value or parameter was passed to the function (a negative vector size, for example).”，换用PaddlePaddle 2.2.2版本以及PaddleDetection release/2.4训练解决了，用PaddlePaddle 2.3.2版本以及PaddleDetection release/2.5训练就不行，这算不算待优化的bug呢？
