### ISSUE TITLE
SNIPER训练自己数据集显示类别错误

### ISSUE THREAD

**Issue by jiaowei123456** [PaddlePaddle/PaddleDetection#5577]
![(GYE)IQM JHB(AOUT%P)5T3](https://user-images.githubusercontent.com/70888273/161380703-f70386de-a40b-4052-b485-773abeea39fb.png)
使用sniper训练成功，但是模型导出之后检测种类不是我想要的，而是开始的person，但是检测的位置是对的。是不是我配置哪里没有修改？
![W{O$X@6LG(4SWY4ZK}9C4HT](https://user-images.githubusercontent.com/70888273/161380789-b0f36c64-ed13-4b61-bea6-2e66396ba5a4.png)

**Comment by nemonameless** [comment]
导出是和TestDataset有关，需要保证TestDataset的anno_path配置正确。

**Comment by jiaowei123456** [comment]
谢谢，已解决。原始TestDataset中没有anno_path，需自己添加
