### ISSUE TITLE
[Other General Issues]想使用蒸馏压缩ppyolov2报错

### ISSUE THREAD

**Issue by jiaowei123456** [PaddlePaddle/PaddleDetection#5589]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.

## 描述问题/Describe the bug
使用蒸馏压缩ppyolov2_r50vd_dcn模型报错:
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 118, in run
    trainer = Trainer(cfg, mode='train')
  File "/root/autodl-tmp/PaddleDetection/ppdet/engine/trainer.py", line 102, in __init__
    if 'slim' in cfg and cfg['slim_type'] == 'OFA':
KeyError: 'slim_type'
## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
python tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml --slim_config configs/slim/distill/ppyolov2.yml
```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
改过蒸馏配置文件：
_BASE_: [
  '../../ppyoloe/ppyoloe_crn_m_300e_coco.yml',
]

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_m_pretrained.pdparams

slim: Distill
distill_loss: DistillYOLOv3Loss

DistillYOLOv3Loss:
  weight: 1000
3. 您使用的数据集是？/What dataset did you use?
自己的coco格式数据集
4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 118, in run
    trainer = Trainer(cfg, mode='train')
  File "/root/autodl-tmp/PaddleDetection/ppdet/engine/trainer.py", line 102, in __init__
    if 'slim' in cfg and cfg['slim_type'] == 'OFA':
KeyError: 'slim_type'
## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by wangxinxin08** [comment]
你的slim_type不存在，可以检查下你的slim_config是否设置正确

**Comment by jiaowei123456** [comment]
谢谢你的回复，不过我的slim_config如下图：
![ZY~61XD(A_~ _KO@5HIZVNP](https://user-images.githubusercontent.com/70888273/161895752-3db24348-1e75-4d5c-8984-23bcc8108b47.png)
里面是有slim的。
而且我使用贵方提供案例对YOLOv3-MobileNetV1进行蒸馏，版本为paddle2.2.2，paddleslim2.2.2，config文件未修改，仅改变数据集路径，依旧报相同错误：
![QQ截图20220406123116](https://user-images.githubusercontent.com/70888273/161896179-112472cf-8a78-4605-b1b1-3505c9e88c76.png)
不知道是为什么？

**Comment by jiaowei123456** [comment]
> 你的slim_type不存在，可以检查下你的slim_config是否设置正确
谢谢你的回复，不过我使用的slim_config如下图：
![ZY~61XD(A_~ _KO@5HIZVNP](https://user-images.githubusercontent.com/70888273/161897012-6cd8ac20-09d8-4fe7-b640-92a646899a9f.png)
里面是有slim的。
而且我使用贵方提供的案例以及slim_config对YOLOv3-MobileNetV1进行压缩，paddle版本2.2.2，paddleslim版本2.2.2，仅改变数据集路径其他config均未修改，命令行：
python tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_270e_coco.yml --slim_config configs/slim/distill/yolov3_mobilenet_v1_coco_distill.yml
但是仍然报错：
![QQ截图20220406123116](https://user-images.githubusercontent.com/70888273/161897452-4c93e18b-ad63-4234-ac8a-03ccf4631a99.png)
请问是为什么呢？

**Comment by jiaowei123456** [comment]
@wangxinxin08 
感谢你的回复，不过我使用的slim_config如下图：
![ZY~61XD(A_~ _KO@5HIZVNP](https://user-images.githubusercontent.com/70888273/161898284-51be6062-a01e-431f-8513-5362893d88c0.png)
里面好像是有slim的。
然后我使用贵方提供的案例和slim_config对YOLOv3-MobileNetV1进行复现，paddle版本2.2.2，paddleslim版本2.2.2，仅修改数据集未改变其他config文件，命令行如下：
python tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_270e_coco.yml --slim_config configs/slim/distill/yolov3_mobilenet_v1_coco_distill.yml
仍然报错：
![QQ截图20220406123116](https://user-images.githubusercontent.com/70888273/161898646-f5cb9830-2a13-4b7f-b076-65ffd91ad2c5.png)
不知道是为什么，可以再回复一下吗？谢谢。

**Comment by jiaowei123456** [comment]
@RachelXu7 
你好，我发现在ppdet/slim/__init__.py下面39行处加入cfg['slim_type'] = cfg.slim可解决此报错，不过仍然报错：
![QQ截图20220407125657](https://user-images.githubusercontent.com/70888273/162123550-cb109121-ec0a-42b8-b5ee-3155e4944df5.png)
不知道应该怎么处理？

**Comment by RachelXu7** [comment]
load_meanstd 应该是ppdet新增的，slim未来得及适配。如果你着急的话，可以先把这段注释掉，或者增加一条判断
elif 'slim' in cfg and cfg['slim_type'] == 'Distill':
            self.model.student_model.load_meanstd(cfg['TestReader'][
                'sample_transforms'])

**Comment by jiaowei123456** [comment]
@RachelXu7 
谢谢你的回复，请问可以使用之前版本的paddledetection可以完成压缩吗？比如2.3或2.2。

**Comment by RachelXu7** [comment]
2.2版本还没有load_meanstd，是可以的。

**Comment by jiaowei123456** [comment]
@RachelXu7 
谢谢您的回复。

**Comment by Tongfengyu** [comment]
请问load_meanstd的作用是什么？为什么在这里加这个？相关代码在哪里查看？
