### ISSUE TITLE
能不能配合Cuda来加速推理过程？

### ISSUE THREAD

**Issue by TTgogogo** [PaddlePaddle/PaddleDetection#5596]
能不能自己修改部署的代码，配合Cuda来加速推理过程？有没有例子呢？

**Comment by wangxinxin08** [comment]
GPU模式也就是通过cuda来加速推理过程，你可以先按照官方文档https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/cpp 来运行cpu和gpu模型，之后再参考官方代码进行修改你自己的代码
