### ISSUE TITLE
faster rcnn 那些模型都是基于多大图片的？ 没有说明啊

### ISSUE THREAD

**Issue by Stillremains** [PaddlePaddle/PaddleDetection#560]
faster rcnn 那些模型都是基于多大图片的？ 没有说明啊，像下面的yolov3 都说明提供了3种大小的图片模型   而其他模型的都没说明 懵逼啊

**Comment by qingqing01** [comment]
@Stillremains  FasterRCNN模型都是短边800， 但长边不超过1333。评估也是这样。参考TrainReader和EvalReader。  https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/configs/faster_reader.yml#L19  感谢关注，我们也加强下文档。

**Comment by Stillremains** [comment]
> @Stillremains FasterRCNN模型都是短边800， 但长边不超过1333。评估也是这样。参考TrainReader和EvalReader。 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/configs/faster_reader.yml#L19 感谢关注，我们也加强下文档。

我的图片是424*240的 需不需要设置什么？ 我图片会不会太小啊 有没有影响

**Comment by qingqing01** [comment]
@Stillremains faster rcnn模型的anchor size比较大，可以先使用800，1333这样的尺寸训练。

**Comment by Stillremains** [comment]
> @Stillremains faster rcnn模型的anchor size比较大，可以先使用800，1333这样的尺寸训练。
好的 谢谢
