### ISSUE TITLE
能否出一个带读paddlepaddledetction代码的教程

### ISSUE THREAD

**Issue by FAFUzxf** [PaddlePaddle/PaddleDetection#5602]
paddlepaddledetction的代码对于中低阶玩家感觉是真的难读懂，都不了解他要干什么，大而全的模型库虽然啥都有，但是根本不利于新手在上面改模型，写创意。

**Comment by nemonameless** [comment]
收到建议，谢谢反馈。可以先参考这几个文档 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/docs/advanced_tutorials
