### ISSUE TITLE
[Other General Issues] Concat error in eval script when using picodet with Widerface

### ISSUE THREAD

**Issue by Ame04** [PaddlePaddle/PaddleDetection#5611]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.

## 描述问题/Describe the bug
I try to train picodet_s_320 with the widerface dataset. I have a mismatch dimention error on a concat layer in the eval script while the train and infer script seems to work.

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
python3 tools/train.py -c configs/picodet/picodet_s_320_coco.yml -o use_gpu=false 
python3 tools/eval.py -c configs/picodet/picodet_s_320_coco.yml -o use_gpu=false 
python3 tools/eval.py -c configs/picodet/picodet_s_320_coco.yml -o use_gpu=false --infer_img demo/000000014439.jpg

请填写命令/A placeholder for the command.
Root of PaddleDetection 2.3

2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

In picodet_s_320_coco.yml I just changed :
_BASE_: [
  '../datasets/wider_face.yml',
  '../runtime.yml',
  '_base_/picodet_esnet.yml',
  '_base_/optimizer_300e.yml',
  '_base_/picodet_320_reader.yml',
]
weights: output/picodet_s_320_widerface/model_final
TrainReader:
  batch_size: 4

3. 您使用的数据集是？/What dataset did you use?

Widerface

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
ValueError: (InvaliArgument) the 2-th dimension of input[0] and input[1] is expected to be equal. But received input[0]'s shape =[1,96,44,64], input[1]'s shape =[1,96,43,64].
[Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:44 != inputs_dims[i][j]:43.] (at /paddle/paddle/fluid/operators/concat_op.h:63)
[operator < concat > error]

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：2.3

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：
Last version for each depandency

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
Ubuntu with WSL2 on windows 10

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
python3.8.10

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
none, i run on CPU

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by yghstill** [comment]
We will fix this soon.

**Comment by Edward715** [comment]
Has this bug been fixed? I try to fix the image shape in ppdet/metrics/widerface_ utils/detect_ face to 320x320 for picodet_s_320, and then eval run successfully. Can this solve the bug? Will it affect the results of the evaluation?
