### ISSUE TITLE
picodet   c++部署 使用tensortrt问题

### ISSUE THREAD

**Issue by WTtree-lz** [PaddlePaddle/PaddleDetection#5614]
up！您好！
本人在使用win10，vs2019，部署picodet模型时，采用gpu和tensortrt加速！模型加载的时候报错！
对应的模型参数我也设置了，

mode: trt_fp16
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: true
arch: GFL
min_subgraph_size: 3

config.FLAGS_run_mode = "trt_fp16";
config.FLAGS_batch_size = 1;
config.FLAGS_gpu_id = 0;
config.FLAGS_gpu_mem = 4000;
config.FLAGS_trt_min_shape = 1;
config.FLAGS_trt_max_shape = 1280;
config.FLAGS_trt_opt_shape = 320;

报错信息：
TensorRT dynamic shape enabled
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at ..\paddle/fluid/inference/tensorrt/convert/op_converter.h:245)

**Comment by yghstill** [comment]
@WTtree-lz 在导出模型的时候设置`'GFL': 48试下吧：`https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/engine/export_utils.py#L47
或者在导出模型时不导出后处理，设置export.benchmark=True再试下。
