### ISSUE TITLE
May I freeze some layers' parameters when fine-tuning?

### ISSUE THREAD

**Issue by p1n0cch10** [PaddlePaddle/PaddleDetection#563]
Hi,

I am using a pretrained model to fine-tune yolov3. Are there any options that I can use to freeze some layers, and just training other layers' parameters?

Thanks.

**Comment by qingqing01** [comment]
@p1n0cch10 

If you use ResNet backbone, you will see an arg `freeze_at` in YML config, which meaning freeze backbone until which stage.    If want to freeze more, need to change the code in [architecture]( https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/modeling/architectures/yolov3.py) or [yolo_head](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/modeling/anchor_heads/yolo_head.py) , set `stop_gradient=True` for one variable.  But note, do not set `stop_gradient=True`  for   [yolo_output](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/modeling/anchor_heads/yolo_head.py#L224), which is related to `classes_num`

**Comment by qingqing01** [comment]
@p1n0cch10 Is there any question?
