### ISSUE TITLE
[Feature Request]请求添加模型量化PTQ方法及教程

### ISSUE THREAD

**Issue by Disciple7** [PaddlePaddle/PaddleDetection#5634]
## 🚀  新功能/Feature

目前PaddleDetection已经有QAT量化方式，希望引入PTQ量化方式。

## 需求原因&示例/Motivation & Examples

正在进行应急场景下的目标检测项目，在无人机场景下进行目标检测模型部署，需要尽可能减小模型大小、提升模型推理速度。
目前已经测试了QAT量化，希望能够引入PTQ量化，特别是PaddleSlim的动态离线量化方式。该量化方式与模型训练过程解耦，能够比较好的提升开发速度，以及降低后期引入新模型的难度。

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/slim#%E7%A6%BB%E7%BA%BF%E9%87%8F%E5%8C%96 这里面有一些离线量化的文档可以参考，https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/slim/post_quant 这里面也提供了一些相关配置
