### ISSUE TITLE
picodet的网络输出

### ISSUE THREAD

**Issue by yuexiayiren159aaa** [PaddlePaddle/PaddleDetection#5636]
# 这是picodet的网络输出，没有后处理的。
# 我想知道这个网络有8个输出，代表什么。我需要自己写后处理。
类似yolo的输出 （13,13,255),(26,26,255)(52,52,255),13*13的特征图，255=85*3 ,82=80 + 5 ,5 = x,y,w,h,c
![image](https://user-images.githubusercontent.com/102778714/162400704-de3f319a-9593-4efb-bf49-82f6bb88c92d.png)

**Comment by jerrywgz** [comment]
picodet如果不导出后处理，输出表示的是每一层对应的分数和box坐标https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/modeling/heads/pico_head.py#L532
