### ISSUE TITLE
[Other General Issues] 如何直接得到预测的json文件

### ISSUE THREAD

**Issue by Asthestarsfalll** [PaddlePaddle/PaddleDetection#5637]
很多时候用户都是需要直接得到对应格式的json文件，而infer.py只支持导出分散的txt，eval虽然能导出json但是需要对应的label json文件，十分不方便。

**Comment by jerrywgz** [comment]
这里是希望将infer.py输出的结果已json的格式保存吗，可以将导出的txt已自己期望的格式转换成json

**Comment by Asthestarsfalll** [comment]
自己转换确实可以，但是对于这种重复性的工作（比如很多比赛需要提交COCO格式的Json文件），每个用户都要自己写一遍，略显麻烦。我建议可以添加将推理结果保存为对应的格式（比如通过dataset来确定格式）的文件。方便且全面，这不正是一个优秀开发套件所要具备的嘛。
