### ISSUE TITLE
使用yaml读取configs下的模型配置文件出错

### ISSUE THREAD

**Issue by omtbreak** [PaddlePaddle/PaddleDetection#564]
我想要使用python下的yaml库读取configs下的 模型名.yml 文件，代码如下
```
with open('/Users/omtbreak/Desktop/faster_fpn_reader.yml')as file:
    cfg = yaml.load(file,Loader=yaml.Loader)
    print(cfg)
```
但是报错
```
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!COCODataSet'
```
我看train.py中的源码，同样适用yaml进行读取
```
with open(file_path) as f:
        cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
```
个人推测是 !COCODataSet是Paddle对配置文件自定义的标签，希望可以解答如何读取配置文件

**Comment by qingqing01** [comment]
@omtbreak 

需要这样加载:

export PYTHONPATH=`pwd`:$PYTHONPATH

```
from ppdet.core.workspace import load_config
cfg = load_config('configs/faster_fpn_reader.yml')
print(cfg)
```

无法不import `ppdet.core.workspace`，直接使用yaml加载。原因是configs下面的yml文件加载时，`!x`需要实例化一些模块。

**Comment by omtbreak** [comment]
> @omtbreak
> 
> 需要这样加载:
> 
> export PYTHONPATH=`pwd`:$PYTHONPATH
> 
> ```
> from ppdet.core.workspace import load_config
> cfg = load_config('configs/faster_fpn_reader.yml')
> print(cfg)
> ```
> 
> 无法不import `ppdet.core.workspace`，直接使用yaml加载。原因是configs下面的yml文件加载时，`!x`需要实例化一些模块。
> 
> 您想单独加载这个yml文件，有什么特殊的意图吗？

感谢您的回复。我们是想在网站上通过界面的方式配置模型参数，所以需要对模型的配置文件做读写操作。这种读取方式我尝试成功了，我看到了这段源码但没想到可以这样用，谢谢。但我没注意到有load_config后再将cfg写入yml文件的源码。如果有的话，请您分享下。

**Comment by willthefrog** [comment]
试下这段代码可以吗？
```python
import yaml
import ppdet.core.workspace 
cfg = yaml.load(open('configs/faster_fpn_reader.yml'), Loader=yaml.Loader)
print(yaml.dump(cfg))
```

**Comment by omtbreak** [comment]
> 试下这段代码可以吗？
> 
> ```python
> import yaml
> import ppdet.core.workspace 
> cfg = yaml.load(open('configs/faster_fpn_reader.yml'), Loader=yaml.Loader)
> print(yaml.dump(cfg))
> ```

您好，我尝试过这样写，但是不行，会识别不出配置文件中例如!PiecewiseDecay这样的标签，报错为
```
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!PiecewiseDecay'
```

**Comment by willthefrog** [comment]
不应该啊，试了下这段代码可以正常打印的，这个yaml也包含`!PiecewiseDecay`。
```python
import yaml
import ppdet.core.workspace 
cfg = yaml.load(open('configs/faster_rcnn_r101_1x.yml'), Loader=yaml.Loader)
print(yaml.dump(cfg))
```

**Comment by omtbreak** [comment]
> 不应该啊，试了下这段代码可以正常打印的，这个yaml也包含`!PiecewiseDecay`。
> 
> ```python
> import yaml
> import ppdet.core.workspace 
> cfg = yaml.load(open('configs/faster_rcnn_r101_1x.yml'), Loader=yaml.Loader)
> print(yaml.dump(cfg))
> ```
!!!抱歉我愚钝了，感谢您，我想错了

**Comment by willthefrog** [comment]
没事，如果解决了麻烦关下这个issue吧，谢谢。
