### ISSUE TITLE
picodet新版onnx模型简化之后，无法转openvino模型

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#5643]
简化命令：
python3.7 -m onnxsim picodet_s_320_coco.onnx picodet_s_processed.onnx --dynamic-input-shape --input-shape image:1,3,320,320
转换openvino命令：
python "C:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\mo_onnx.py" --input_model picodet_s_processed.onnx --output_dir . --mean_values [123.675,116.28,103.53] --scale_values [58.395,57.12,57.375]
报错：
![image](https://user-images.githubusercontent.com/48303408/162552106-6a118dce-8e78-437b-903e-83660f7fc3be.png)
后面加上input_shape参数还是报错：
![image](https://user-images.githubusercontent.com/48303408/162552122-0981bf9f-2b18-4c91-ab8a-96ccf11993bc.png)
求各位大佬帮忙看一下

**Comment by yghstill** [comment]
@Dandelion111 请升级openvino到2022.1，并使用新版demo进行测试，直接加载onnx模型进行预测。

**Comment by Dandelion111** [comment]
> @Dandelion111 请升级openvino到2022.1，并使用新版demo进行测试，直接加载onnx模型进行预测。

谢谢大佬回复，我升级一下openvino试试，我试过直接加载onnx模型，但是ReadNetwork这一步会报错，新版openvino demo是不是还没有c++版本？

**Comment by yghstill** [comment]
> 谢谢大佬回复，我升级一下openvino试试，我试过直接加载onnx模型，但是ReadNetwork这一步会报错，新版openvino demo是不是还没有c++版本？

C++部署代码正在开发中，很快发布，可以先测试python的demo~

**Comment by Dandelion111** [comment]
> > 谢谢大佬回复，我升级一下openvino试试，我试过直接加载onnx模型，但是ReadNetwork这一步会报错，新版openvino demo是不是还没有c++版本？
> 
> C++部署代码正在开发中，很快发布，可以先测试python的demo~

谢谢！

**Comment by Dandelion111** [comment]
> > 谢谢大佬回复，我升级一下openvino试试，我试过直接加载onnx模型，但是ReadNetwork这一步会报错，新版openvino demo是不是还没有c++版本？
> 
> C++部署代码正在开发中，很快发布，可以先测试python的demo~

新版的picodet是只能用openvino2022.1版本吧，以前版本不支持动态shape

**Comment by yghstill** [comment]
@Dandelion111 是的
