### ISSUE TITLE
在用户数据转coco数据中（tools/x2coco.py）输入的json文件如何获得的，目前只有对应图片的xml文件

### ISSUE THREAD

**Issue by code10086web** [PaddlePaddle/PaddleDetection#5645]
![image](https://user-images.githubusercontent.com/53412966/162576216-2a1ecd65-9a5e-45f2-a459-ee113faa3ef0.png)

**Comment by nemonameless** [comment]
xml转coco格式，就把你的数据集做成VOC数据集相同的目录和格式，dataset_type选择voc，当成voc转coco去运行即可。
dataset_type为labelme时的json输入文件是标注工具做成的。
