### ISSUE TITLE
关于pp-yoloe训练时长

### ISSUE THREAD

**Issue by code10086web** [PaddlePaddle/PaddleDetection#5646]
在自己数据集上训练，数据集训练集大小为2160张图片，设备为使用rtx3090，batch_size为每个gpu大小为4，预估时长一个epoch需要1天，训练的很慢是正常的吗？我使用coco数据集去测试了下，每个gpu的图片数量为1张时，训练一个epoch预估需要219天。。。，请问pp-yoloe训练时长很慢是什么原因呢

**Comment by zsy1987** [comment]
请问你解决了吗？我训练没问题，但是推理没达到预计的速度

**Comment by code10086web** [comment]
> 

还没有，想问下你是将自己数据集转换为coco格式训练的吗？

**Comment by xihuanafeng** [comment]
> 请问你解决了吗？我训练没问题，但是推理没达到预计的速度

请问一下你的loss降低的速度如何？

**Comment by wangxinxin08** [comment]
> > 请问你解决了吗？我训练没问题，但是推理没达到预计的速度
> 
> 请问一下你的loss降低的速度如何？

@loss下降不正常的话，可以参考文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/README_cn.md 注意调整学习率
