### ISSUE TITLE
matching_matrix[gt_idx][pos_idx] = 1  matching_matrix是一个tensor 为什么不能赋值 

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/PaddleDetection#5647]
gt_idx = 0
pos_idx = Tensor(shape=[8], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [36, 37, 38, 32, 33, 27, 91, 42])
matching_matrix[gt_idx][pos_idx] = 1.0 

为甚么[36, 37, 38, 32, 33, 27, 91, 42]这些索引的值还是0

**Comment by Wei-JL** [comment]
```
matching_matrix = Tensor(shape=[1, 95], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [[0., 0., 0., 0., 0., 0., 0., ... 0., 0., 0., 0., 0.]])
gt_idx = 0
pos_idx = Tensor(shape=[8], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
[36, 37, 38, 32, 33, 27, 91, 42])
matching_matrix[gt_idx][pos_idx] = 1.0

最终输出matching_matrix还是全0
```

为甚么[36, 37, 38, 32, 33, 27, 91, 42]这些索引的值还是0，应该什么样才能改变tensor对应index值

**Comment by lyuwenyu** [comment]
改成这样试一下 matching_matrix[gt_idx, pos_idx] = 1.0

**Comment by Wei-JL** [comment]
改成这样试一下 matching_matrix[gt_idx, pos_idx] = 1.0  似乎直接报错诶   matching_matrix， gt_idx ,  pos_idx需要改类型吗

**Comment by Wei-JL** [comment]
matching_matrix[gt_idx, pos_idx] =1.0  这样可以赋值 ，但是不能查看，调试查看的话只能matching_matrix[gt_idx][pos_idx]，非常感谢 已经解决

**Comment by nemonameless** [comment]
PaddleDetection中已经发布[YOLOX](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/yolox)，欢迎使用。
