### ISSUE TITLE
请问怎么样可视化feature map？

### ISSUE THREAD

**Issue by yinggo** [PaddlePaddle/PaddleDetection#565]

**Comment by qingqing01** [comment]
@yinggo 暂时没有提供直接对feature map可视化的功能，如果想可视化的，需要修改下代码，拿到中间的feature map，在外面自己可视化。能问下您想如何可视化吗？

**Comment by yinggo** [comment]
![image](https://user-images.githubusercontent.com/7889064/80437508-55434c80-8934-11ea-81a4-e7eae20cf93b.png)
您好，我自己训练了网络想看看feature map的差异，需要类似这样的图，请问怎样拿中间的feature map去做可视化呢？能否给个demo参考？谢谢！

**Comment by qingqing01** [comment]
@yinggo 已FasterRCNN为例，找到想可视化的feature map，

可以在`architectures`中:  https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/modeling/architectures/faster_rcnn.py#L89  或  backbone中，找到feature_map，可以对应的名字， [可打印获取print(feature_map.name) ]。

然后从tools/train.py，如果仅仅是预测得到feature map，可以通过tools/infer.py脚本，在exe.run中,把想获取的输出放到fetch_list中，比如名字是: 'conv_output'



```   
        values = values + ['values']
        outs = exe.run(infer_prog,
                       feed=data,
                       fetch_list=values,
                       return_numpy=False)
        conv_output_numpy = np.array(outs[-1])
```

拿到输出可视化，得改下代码。

**Comment by yinggo** [comment]
@qingqing01 您好，我找了一些可视化heatmap的工具，有的基于keras有的基于pytorch. 
比如https://github.com/jacobgil/keras-cam；https://github.com/zhoubolei/CAM
需要.hdf5/.pth的输入；请问conv_output_numpy输出怎么转换成这种数据格式呢？

**Comment by qingqing01** [comment]
@yinggo .hdf5是keras模型格式，.pth是PyTorch的模型格式。 没有直接的转换方式。间接的方式，可以自定义keras/pytorch的tensor，加载paddle的numpy，给这个tensor初始化存储？
