### ISSUE TITLE
ppyoloe的模型推理速度

### ISSUE THREAD

**Issue by zsy1987** [PaddlePaddle/PaddleDetection#5652]

**Comment by lyuwenyu** [comment]
你测的是模型的速度嘛，导出时候去掉nms, 另外加上 --benchmark

> CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/ppyoloe_crn_l_300e_coco --image_file=demo/000000014439_640x640.jpg --device=gpu --run_benchmark=True

**Comment by YuNaruto** [comment]
> 你测的是模型的速度嘛，导出时候去掉nms, 另外加上 --benchmark
> 
> > CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/ppyoloe_crn_l_300e_coco --image_file=demo/000000014439_640x640.jpg --device=gpu --run_benchmark=True

为什么要使用 deploy/python/infer.py，我使用的是 tools/infer.py, 在 trainer.py 下添加时间打印，时间要比你的这种方法慢了四倍，很夸张。
添加的时间打印：
![image](https://user-images.githubusercontent.com/32025355/169010363-3a905bbb-2d3e-4398-bfb4-6f07e3cf00ae.png)



为什么测速，要单独这样呢？
![image](https://user-images.githubusercontent.com/32025355/169010172-865be4a8-616d-4f9c-9af2-05f1126f27a5.png)

**Comment by shuaijun-deng** [comment]
我直接在视频上测试，感觉比yolov5-s速度慢很多，整个人都懵了，不知道百度测试标准是什么，怎么测试的

**Comment by shuaijun-deng** [comment]
python deploy/python/infer.py --model_dir=./inference_model/ppyoloe_crn_s_300e_coco/ --video_file /home/hasaki/data/video_data/CBG/t1.mp4 --device=GPU --use_gpu=True
视频大小是1920*1080的大小
