### ISSUE TITLE
有没有比较过PPYoloe和Picodet的精度和速度？

### ISSUE THREAD

**Issue by xiaoxifuhongse** [PaddlePaddle/PaddleDetection#5653]
如题，有没有对picodet进行对比测试？

**Comment by lyuwenyu** [comment]
这两个模型是根据不同领域设计的  是互补的关系， picodet是针对移动端设备 arm等，yoloe是是服务器端的高性能卡 n卡等. 

具体的指标可以看技术文档
- [picodet](https://arxiv.org/abs/2111.00902)
- [yoloe](https://arxiv.org/pdf/2203.16250.pdf)
