### ISSUE TITLE
关于多卡训练过程中，中途停止训练，显卡显存无法释放的问题[BUG]

### ISSUE THREAD

**Issue by yjhtc007** [PaddlePaddle/PaddleDetection#5658]
各位大佬好，我在使用PaddleDetection训练模型的时候遇到了一个bug，就是用多卡训练模型，如果中途出现错误的话，会出现训练进程无法结束的情况，人为用kill -9 命令杀死后显卡占据的显存仍不会释放。我用PaddleOCR进行多卡训练，中途报错或停止的话不会报这个错误。之前用PaddleClas进行多卡训练也出现过和PaddleDetection一样的错误，就是显存没法释放的问题，请问我该如何解决呢？

**Comment by yjhtc007** [comment]
![1649727078(1)](https://user-images.githubusercontent.com/52524345/162860933-fb0f9459-0530-40bc-8651-9b0fa04bbd86.png)
这个是报错的图片，在多卡训练中途出现了错误，但进程没有被杀死

**Comment by yjhtc007** [comment]
![1649729640(1)](https://user-images.githubusercontent.com/52524345/162865556-4ec5d5c1-8dbe-44f1-b678-189c53c9f559.png)

**Comment by wangxinxin08** [comment]
一般用`ps aux | grep config.yml | awk '{print $2}' | xargs kill -9`
