### ISSUE TITLE
安装paddle develop分支后，运行报错

### ISSUE THREAD

**Issue by qjing666** [PaddlePaddle/PaddleDetection#566]
<img width="1437" alt="截屏2020-04-27下午8 49 06" src="https://user-images.githubusercontent.com/19721227/80374004-8f770480-88c8-11ea-92ba-c0ec3b32d5a4.png">

**Comment by qingqing01** [comment]
@qjing666 暂且是不支持develop版本。 develop版本有点问题，修复PR： https://github.com/PaddlePaddle/Paddle/pull/23797 。 您可以在rpn_head.py 177行的，返回临时修改下:

```
rpn_rois, rpn_roi_probs, _ = prop_op(
```

**Comment by qingqing01** [comment]
@qjing666 这个修复合入了，抱歉，请更新下版本吧。

**Comment by qjing666** [comment]
问题已修复，感谢！
