### ISSUE TITLE
如何调整yolov3_darknet_voc.yml中的图片输入尺寸，改成image_shape: [3, 300, 300]回报错

### ISSUE THREAD

**Issue by ai-zml** [PaddlePaddle/PaddleDetection#567]
Error Message Summary:
----------------------
Error: ShapeError: Dimension 2 in inputs' shapes must be equal. But recevied input[0]'s shape = [-1, 256, 20, 20], input[1]'s shape = [-1, 512, 19, 19].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:20 != inputs_dims[i][j]:19.] at (/paddle/paddle/fluid/operators/concat_op.h:55)

**Comment by heavengate** [comment]
> ## Error Message Summary:
> Error: ShapeError: Dimension 2 in inputs' shapes must be equal. But recevied input[0]'s shape = [-1, 256, 20, 20], input[1]'s shape = [-1, 512, 19, 19].
> [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:20 != inputs_dims[i][j]:19.] at (/paddle/paddle/fluid/operators/concat_op.h:55)

需要是32的倍数，YOLOv3里面有跨视域的concat，不是32的倍数有的层降采样之后shape会不匹配，concat会报错，建议设置成288*288

**Comment by ai-zml** [comment]
谢谢
