### ISSUE TITLE
(InvalidArgument) concat(): argument 'X' (position 0) must be list of Tensors, but got empty list

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/PaddleDetection#5671]
```
cls_targets = paddle.concat(cls_targets, 0)
       **cls_targets为list , 里面只有一个为0**的tensor -->Tensor(shape=[0, 4], dtype=float32, place=CUDAPlace(0), stop_gradient=True, [])
   
```
  报错日志 : File "D:\PyCharm\YOLO\paddle_fuxian\yolox_paddle\nets\yolo_training.py", line 210, in get_losses
    cls_targets = paddle.concat(cls_targets, 0)
  File "D:\Anaconda3\envs\paddle2-2-2g\lib\site-packages\paddle\tensor\manipulation.py", line 345, in concat
    return paddle.fluid.layers.concat(input=x, axis=axis, name=name)

**Comment by Wei-JL** [comment]
您好，有什么解决方法吗？ 这边无法对Tensor(shape=[0, 4], dtype=float32, place=CUDAPlace(0), stop_gradient=True, []) concat

**Comment by nemonameless** [comment]
试试设置假数据如全0。用的哪份代码？
