### ISSUE TITLE
AttributeError: 'PPYOLOEHead' object has no attribute 'mask_anchors'

### ISSUE THREAD

**Issue by will-wiki** [PaddlePaddle/PaddleDetection#5681]
你好，我想用ppyolo导出图像的实体特征用于其他任务的训练，看了下源码应是对应 yolo.py中的 for_mot参数，尝试了下最新版本的ppyoloe模型，发现在调用infer.py时候会报错“AttributeError: 'PPYOLOEHead' object has no attribute 'mask_anchors'”，是因为ppyoloe模型不支持这个功能么？

**Comment by ghostxsl** [comment]
是的

**Comment by will-wiki** [comment]
@ghostxsl 感谢回复，那想请问下目前PaddleDetection仓库中有支持这个功能的模型么，效果比较好的有推荐的嘛，之前一直用的faster-rcnn，但是它的速度太慢了

**Comment by ghostxsl** [comment]
想输出feature map，自己可以稍微改一下代码即可～

**Comment by will-wiki** [comment]
@ghostxsl 您的意思是改下ppyoloe的代码就可以得到具体bbox的feature map么，有没有修改建议呀

**Comment by ghostxsl** [comment]
我不太清楚你下游任务是要干什么，如果你是想要像类似roi_pool的那种操作的话，参考faster_rcnn的实现即可

**Comment by will-wiki** [comment]
@ghostxsl 您好再次打扰一下，想问下ppyoloe模型有没有发布MSCOCO数据集之外的预训练模型版本呀。

**Comment by ghostxsl** [comment]
暂时没有，这个还在计划中

**Comment by will-wiki** [comment]
那之前发布的模型比如ppyolov2模型，有发布过除了MSCOCO数据集之外的预训练版本么

**Comment by ghostxsl** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyolo#pp-yolo-on-pascal-voc
有VOC的
