### ISSUE TITLE
测试时为什么每次还得下载train2017.zip数据集,如何设置不下载，直接检测呢？

### ISSUE THREAD

**Issue by tuodi** [PaddlePaddle/PaddleDetection#5684]
` python tools/infer.py -c configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.yml -o weights=/home/ubuntu/workspace/work/faster_rcnn_r50_fpn_1x_coco.pdparams --infer_dir=/home/ubuntu/workspace/work/data/abnormal_action_frames --output_dir=/home/ubuntu/workspace/work/data/detection_result --draw_threshold 0.5 --save_txt True 
`

测试时为什么每次还得下载train2017.zip数据集,如何设置不下载，直接检测呢？谢谢

**Comment by ghostxsl** [comment]
首先，dataset_dir的设置在：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/datasets/coco_detection.yml#L8，如果这个路径下没有相关数据，框架会自动启动下载。所以解决方法有两个，要么你软链接到这个目录，要么直接更改config里的路径

**Comment by nemonameless** [comment]
有个简单办法就是  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/data/source/dataset.py#L151  这个函数直接return

**Comment by tuodi** [comment]
好的，我试试哈 谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 上午9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 测试时为什么每次还得下载train2017.zip数据集,如何设置不下载，直接检测呢？ (Issue #5684)





 
有个简单办法就是  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/data/source/dataset.py#L151  这个函数直接return

**Comment by tuodi** [comment]
您好，我直接对check_or_download_dataset(self)函数进行return 但是python tools/infer.py时还是在下载数据集呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 上午9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 测试时为什么每次还得下载train2017.zip数据集,如何设置不下载，直接检测呢？ (Issue #5684)





 
有个简单办法就是  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/data/source/dataset.py#L151  这个函数直接return

**Comment by nemonameless** [comment]
我自己试验过没有问题。你确定改对了吗？check_or_download_dataset函数只要一个return，其余都注释。
#5691 已提PR修复

**Comment by tuodi** [comment]
是的啊 全都注释了呀




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 中午11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 测试时为什么每次还得下载train2017.zip数据集,如何设置不下载，直接检测呢？ (Issue #5684)





 
我自己试验过没有问题。你确定改对了吗？check_or_download_dataset函数只要一个return，其余都注释

**Comment by nemonameless** [comment]
是不是先前python setup install过了？先卸载吧 pip uninstall paddledet然后再重新安装

**Comment by tuodi** [comment]
是的 已经装过了的。我再试试，谢谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 中午12:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 测试时为什么每次还得下载train2017.zip数据集,如何设置不下载，直接检测呢？ (Issue #5684)





 
是不是先前python setup install过了？先卸载吧 pip uninstall paddledet然后再重新安装

**Comment by tuodi** [comment]
我重新安装了一遍paddledetection，测试了一下，还是不行啊。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 中午12:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 测试时为什么每次还得下载train2017.zip数据集,如何设置不下载，直接检测呢？ (Issue #5684)





 
是不是先前python setup install过了？先卸载吧 pip uninstall paddledet然后再重新安装

**Comment by tuodi** [comment]
可以了，我将dataset修改完，重新setup install一下，就不执行那个函数了。谢谢您了哈。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 上午9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 测试时为什么每次还得下载train2017.zip数据集,如何设置不下载，直接检测呢？ (Issue #5684)





 
有个简单办法就是  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/data/source/dataset.py#L151  这个函数直接return
