### ISSUE TITLE
[Other General Issues]在使用paddle进行训练的时候报错。

### ISSUE THREAD

**Issue by weiluonika** [PaddlePaddle/PaddleDetection#5685]
<img width="759" alt="1649843568(1)" src="https://user-images.githubusercontent.com/50006064/163152731-cf067fb4-fd84-470f-95c4-9a47de197950.png">

**Comment by ghostxsl** [comment]
发一下paddle版本和ppdet版本以及跑的什么模型？

**Comment by weiluonika** [comment]
> 发一下paddle版本和ppdet版本以及跑的什么模型？

paddle 2.1.3  ppdet 2.4  mask-r-cnn _r50_fpn_1x_coco

**Comment by ghostxsl** [comment]
请使用paddle 2.2.2版本
