### ISSUE TITLE
C++部署paddledetectino 发现说明与现在最新版本对应不上。

### ISSUE THREAD

**Issue by wyc880622** [PaddlePaddle/PaddleDetection#569]
https://paddledetection.readthedocs.io/advanced_tutorials/inference/docs/windows_vs2019_build.html
我根据上面的说明进行部署，发现报错。
CMakeCache.txt 指向 D:\1.6.1\paddle。
此目录不存在。
后来我打开下面网址https://paddledetection.readthedocs.io/advanced_tutorials/inference/docs/windows_vs2015_build.html
这个部署版本与paddleDetection 不同，还是需要1.6版本，我是应该部署1.6版本吗，可我的训练文件是0.2的paddleDetection。请问我应该如何解决。

**Comment by Channingss** [comment]
@wyc880622 能把编译时候报错的截图发出来吗？另外1.6.1应该指的是paddle的版本，这里的0.2是release/0.2吗？如果是想表达release/0.2，那这个版本指的是PaddleDetection的版本。PaddleDetection依赖于paddle。

**Comment by wyc880622** [comment]
![image](https://user-images.githubusercontent.com/25219834/80456158-b16f9600-895f-11ea-8359-c8ee4b9759a2.png)

**Comment by Channingss** [comment]
@wyc880622 检查下paddle_dir指定对了吗。![image](https://user-images.githubusercontent.com/12471701/80456768-c00a7d00-8960-11ea-987d-3d4b7ddc48de.png)

**Comment by wyc880622** [comment]
你好我现在不知你们的C++版本应该用那个 还有paddle_dir的路径是paddleDetction吗还是paddle
https://codeload.github.com/PaddlePaddle/models/zip/develop
https://codeload.github.com/PaddlePaddle/PaddleDetection/zip/master

**Comment by Channingss** [comment]
@wyc880622  paddle_dir是指paddle预测库的路径，如图这里下载的。
![image](https://user-images.githubusercontent.com/12471701/80458808-fbf31180-8963-11ea-9c9b-0370f72f0d26.png)

**Comment by wyc880622** [comment]
你好我已经更改，还是报这个错误，不知道为什么？
![image](https://user-images.githubusercontent.com/25219834/80459379-e3cfc200-8964-11ea-856f-fb5c798e1f85.png)
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		'D:/projects/fluid_inference/paddle/paddle/fluid/inference/libpaddle_fluid.lib', needed by 'detection_demo.exe', missing and no known rule to make it	D:\projects\models-1.6\PaddleCV\PaddleDetection\inference\out\build\x64-Debug\inference	D:\projects\models-1.6\PaddleCV\PaddleDetection\inference\out\build\x64-Debug\ninja	1

**Comment by Channingss** [comment]
@wyc880622 指定为D:/projects/fluid_inference/ 就可以了

**Comment by wyc880622** [comment]
好的，我改了还是上面的错误，难道程序有问题吗，还是我设置的有问题？
![image](https://user-images.githubusercontent.com/25219834/80462224-fa781800-8968-11ea-8320-3477644384f1.png)

**Comment by Channingss** [comment]
@wyc880622 刚刚给的是linux的路径分隔符，把“/”改为“\”就可以了

**Comment by wyc880622** [comment]
![image](https://user-images.githubusercontent.com/25219834/80463697-3c09c280-896b-11ea-97d8-ef906ee66a1a.png)
![image](https://user-images.githubusercontent.com/25219834/80463721-45932a80-896b-11ea-8dd0-19357225af33.png)
找不到这个lib？？？

**Comment by Channingss** [comment]
> ![image](https://user-images.githubusercontent.com/25219834/80463697-3c09c280-896b-11ea-97d8-ef906ee66a1a.png)
> ![image](https://user-images.githubusercontent.com/25219834/80463721-45932a80-896b-11ea-8dd0-19357225af33.png)
> 找不到这个lib？？？

请问有点击：保存并生成CMake缓存以加载变量吗？
另外make这里，点击全部清理。可能是cmake生成的缓存没有被清理掉。
![image](https://user-images.githubusercontent.com/12471701/80464282-2943bd80-896c-11ea-9f34-3257dd9b3cbf.png)

**Comment by wyc880622** [comment]
他还是报这个错误，不知道为什么？
D:/projects/fluid_inference/paddle/paddle/fluid/inference/libpaddle_fluid.lib', needed by 'detection_demo.exe', missing and no known rule to make it	D:\projects\models-1.6\PaddleCV\PaddleDetection\inference\out\build\x64-Debug\inference	D:\projects\models-1.6\PaddleCV\PaddleDetection\inference\out\build\x64-Debug\ninja	1

**Comment by Channingss** [comment]
@wyc880622 https://github.com/PaddlePaddle/PaddleDetection/blob/c7a1252f20f8c3d9979445f91dbe6706953efcee/deploy/cpp/CMakeLists.txt#L154，
paddle预测库的依赖在这里设置的，paddle_dir在这里解析就是${PADDLE_DIR}，你找下解压的fluid_inference中libpaddle_fluid.lib的路径，然后对应修改下这里代码和paddle_dir。

**Comment by wyc880622** [comment]
你好，非常感谢你的回答，上面的错误已经处理，但是我生成的时候又出现了错误。
![image](https://user-images.githubusercontent.com/25219834/80552360-feec1180-89f8-11ea-895a-7abaa1a03af0.png)
![image](https://user-images.githubusercontent.com/25219834/80552424-2511b180-89f9-11ea-8b7a-88e74117ca73.png)

**Comment by wyc880622** [comment]
opencv的路径我给更改后，没错误了。但是这个有错误了
![image](https://user-images.githubusercontent.com/25219834/80552714-14ae0680-89fa-11ea-8e41-12c4a7dede3a.png)

**Comment by wyc880622** [comment]
你好有新的问题，请您查看一下。


wangyongchao8806@126.com
 
发件人： channings
发送时间： 2020-04-28 16:58
收件人： PaddlePaddle/PaddleDetection
抄送： wyc880622; Mention
主题： Re: [PaddlePaddle/PaddleDetection] C++部署paddledetectino 发现说明与现在最新版本对应不上。 (#569)
@wyc880622 https://github.com/PaddlePaddle/PaddleDetection/blob/c7a1252f20f8c3d9979445f91dbe6706953efcee/deploy/cpp/CMakeLists.txt#L154，
paddle预测库的依赖在这里设置的，paddle_dir在这里解析就是${PADDLE_DIR}，你找下解压的fluid_inference中libpaddle_fluid.lib的路径，然后对应修改下这里代码和paddle_dir。

**Comment by Channingss** [comment]
@wyc880622 vs studio的c++版本现在是多少呢。配置为c++ 17再试试

**Comment by wyc880622** [comment]
我用的是2019 ，。配置为c++ 17再试试 是用vs2017吗？

**Comment by Channingss** [comment]
@wyc880622 在vs studio 2019的配置界面可以修改c++的版本，可以参考下这个教程：https://blog.csdn.net/qq_40946921/article/details/90645890

**Comment by wyc880622** [comment]
![image](https://user-images.githubusercontent.com/25219834/80559685-fa335780-8a10-11ea-9c7b-8218fea870e0.png)
你好，这个项目现在是不是还没有sh生成，项目里面是找不到属性的。

**Comment by Channingss** [comment]
@wyc880622 没有在这里生成可运行文件吗？
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/inference/docs/windows_vs2019_build.md#step5-%E9%A2%84%E6%B5%8B%E5%8F%8A%E5%8F%AF%E8%A7%86%E5%8C%96

**Comment by wyc880622** [comment]
谢谢你，就是因为生成失败才找你们解决上面的问题。
![image](https://user-images.githubusercontent.com/25219834/80560878-1f29c980-8a15-11ea-8f8d-81f9a009bf7b.png)

**Comment by Channingss** [comment]
@wyc880622 修改了c++的版本为17，还是这个错误吗？

**Comment by wyc880622** [comment]
> @ wyc880622修改了c ++的版本为17，还是这个错误吗？
> 
> > 谢谢你，就是因为生成失败才找你们解决上面的问题。
> > ![图片](https://user-images.githubusercontent.com/25219834/80560878-1f29c980-8a15-11ea-8f8d-81f9a009bf7b.png)

是的，还是这样啊。

**Comment by Channingss** [comment]
@wyc880622 要不你先试试新版本的c++部署，这个问题我去复现一下https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/cpp

**Comment by wyc880622** [comment]
这个是设置C++ 17
https://www.jb51.net/article/180465.htm

**Comment by Channingss** [comment]
@wyc880622 

> @wyc880622 在vs studio 2019的配置界面可以修改c++的版本，可以参考下这个教程：https://blog.csdn.net/qq_40946921/article/details/90645890

按照这个教程里的试过吗？

**Comment by wyc880622** [comment]
> @ wyc880622
> 
> > @ wyc880622在vs Studio 2019的配置界面可以修改c ++的版本，可以参考下这个教程：[https](https://blog.csdn.net/qq_40946921/article/details/90645890) : [//blog.csdn.net/qq_40946921/article/details/90645890](https://blog.csdn.net/qq_40946921/article/details/90645890)
> 
> 按照这个教程里的试过吗？

你这个我这里找不到，没有项目属性这个选项。

**Comment by wyc880622** [comment]
你给的新版本，直接生成成功，什么都不用改了。说明你们老版本有问题啊。已经浪费了我2天的时间。也非常的感谢你的支持。谢谢了。

**Comment by Channingss** [comment]
@wyc880622 不客气

**Comment by wyc880622** [comment]
![image](https://user-images.githubusercontent.com/25219834/80569195-ff9d9b80-8a2a-11ea-831c-3953652d1157.png)
你好，我进行预测，没有任何反应。

**Comment by Channingss** [comment]
@wyc880622 看看目录下面有没有output.jpeg文件

**Comment by wyc880622** [comment]
没有找到，这是为什么呢？根本就没有输出，我的模型在训练完成后我进行过预测，没有问题啊。

**Comment by Channingss** [comment]
@wyc880622 在master分支，按照第三步导出的模型吗，导出会有这三个文件
![image](https://user-images.githubusercontent.com/12471701/80571022-75573680-8a2e-11ea-8a55-3955c874314b.png)

https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/cpp#3%E7%BC%96%E8%AF%91%E9%83%A8%E7%BD%B2

**Comment by wyc880622** [comment]
我又确认从新导出了一下，确实是这样导出的。就是预测没有生成图片。
![image](https://user-images.githubusercontent.com/25219834/80572105-480b8800-8a30-11ea-9549-66c41ea92a52.png)

**Comment by Channingss** [comment]
@wyc880622  把./main 换成 ./main.exe

**Comment by wyc880622** [comment]
![image](https://user-images.githubusercontent.com/25219834/80573925-78085a80-8a33-11ea-8702-5a88b35d055d.png)
你好还是没有输出，输出的话应该会打印信息的。为什么还抛出异常。

**Comment by Channingss** [comment]
@wyc880622 直接main.exe，把./去掉

**Comment by wyc880622** [comment]
![image](https://user-images.githubusercontent.com/25219834/80574335-3a580180-8a34-11ea-9c3e-86662790ed60.png)
谢谢你，你这里有yolonet的权重吗，我下载一下，使用你们例子的权重进行测试，看下是不是我训练的权重不行。

**Comment by Channingss** [comment]
@wyc880622 这里导出来的就是预训练模型。https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/advanced_tutorials/inference/EXPORT_MODEL.md#%E8%AE%BE%E7%BD%AE%E5%AF%BC%E5%87%BA%E6%A8%A1%E5%9E%8B%E7%9A%84%E8%BE%93%E5%85%A5%E5%A4%A7%E5%B0%8F

**Comment by wyc880622** [comment]
![image](https://user-images.githubusercontent.com/25219834/80576890-886f0400-8a38-11ea-9cf0-7e973f5f1766.png)
你好，这个模型导出来并没有 param model ，现在C++我这里真是没办法了，你们还有办法能解决吗。在次感谢。

**Comment by Channingss** [comment]
@wyc880622 图片加载不出来，你那边能加载吗？我这边跑一下看。

**Comment by wyc880622** [comment]
我这加载不了，需要我给你提供什么吗？

**Comment by wyc880622** [comment]
> @wyc880622 图片加载不出来，你那边能加载吗？我这边跑一下看。

我这加载不了，需要我给你提供什么吗？

**Comment by Channingss** [comment]
暂时不用，我先跑一下，尽快给你回复

**Comment by Channingss** [comment]
@wyc880622 hi，我在master分支下，在mac上运行导出yolov3_darknet的预训练模型的示例：python tools/export_model.py -c configs/yolov3_darknet.yml   --output_dir=./inference_model  -o weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet.tar
运行结果和生成文件目录如下：
![image](https://user-images.githubusercontent.com/12471701/80585769-785e2100-8a46-11ea-9de6-9e8d05d2667e.png)

然后在windows上编译了master分支下deploy/cpp，在cmd中，运行如下代码，运行打印log如下：
![image](https://user-images.githubusercontent.com/12471701/80585925-b65b4500-8a46-11ea-9767-b82b74fbb5fc.png)

可视化结果如下：
![image](https://user-images.githubusercontent.com/12471701/80585905-ae030a00-8a46-11ea-9804-09fa82188069.png)

你那边导出来的模型有__model__，__params__，infer_cfg.yml吗？

**Comment by wyc880622** [comment]
谢谢的你回答。
你好，咱们有差别的地方是我的导出模型没有导出yml文件，我是将config里面yml拷贝到inference_model中。我不知道为什么不能导出yml。难道必须用最新版本吗，目前我的版本是0.2padddleDetetion
![image](https://user-images.githubusercontent.com/25219834/80660778-41782180-8abf-11ea-83ce-092663cf28b8.png)

**Comment by Channingss** [comment]
@wyc880622 必须是master分支哈。

**Comment by wyc880622** [comment]
是 的，我已经验证，必须是master。版本不一样导致了很多问题。我现在已经成功。非常的感谢你的支持。C++版本的部署。如果使用C# 语言调用应该直接使用main吗？或是我应该调用http调用？

**Comment by wyc880622** [comment]
Paddlex发布完成的模型，为什么c++部署 识别是不可以？

**Comment by Channingss** [comment]
@wyc880622 c#是可以调用c++，具体怎么调用您可以研究下。PaddleX和PaddleDetection的模型是相通的，但是yml配置文件是不一样的。PaddleX的c++部署模块很快就会发布。

**Comment by wyc880622** [comment]
> @wyc880622 c#是可以调用c++，具体怎么调用您可以研究下。PaddleX和PaddleDetection的模型是相通的，但是yml配置文件是不一样的。PaddleX的c++部署模块很快就会发布。

好的，谢谢你，但是我发现你们的这个masterC++部署有bug，可以预测yolo的模型，但是faserRcnn的就不行，我从网上下载了你们自己的fasterrcnn导出，然后进行main预测 。根本预测不了，但是yolo可以。你可以重现一下。
我已经确认了多次，我肯定肯定得说 fastercnn不行。ssd 和yolo可以
![image](https://user-images.githubusercontent.com/25219834/80677263-3804ae80-8aeb-11ea-86d6-388194a7d9b6.png)

**Comment by Channingss** [comment]
@wyc880622 请问faster rcnn报错的信息是？

**Comment by wyc880622** [comment]
![image](https://user-images.githubusercontent.com/25219834/81543616-e1c82300-93a8-11ea-9ac9-db9904c70b9a.png)
我用没有导出的模型进行测试没有问题，导出后的模型进行测试是有问题的。

**Comment by Channingss** [comment]
@wyc880622 切到master分支，使用deploy/python目录下的infer.py试试

**Comment by jerrywgz** [comment]
> ![image](https://user-images.githubusercontent.com/25219834/81543616-e1c82300-93a8-11ea-9ac9-db9904c70b9a.png)
> 我用没有导出的模型进行测试没有问题，导出后的模型进行测试是有问题的。

从报错信息看，可能是没空格之类的问题 应该是输入指令的问题，不是代码的问题，我们这边在windows环境上测试也是可以正常跑通的

**Comment by qingqing01** [comment]
@wyc880622 你代码更新到最新了吗？ git pull 到最新呢

**Comment by calibacy** [comment]
现在的paddleDection代码包里根本没有deploy这个文件夹啊，请问是什么情况？

**Comment by qingqing01** [comment]
@calibacy release/0.3和master分支有deploy文件夹

**Comment by qingqing01** [comment]
@wyc880622 @calibacy 这个issue较长且较久了，关闭了。有新的问题，可以再开issue。

**Comment by shlucky401** [comment]
> @wyc880622 
>   
>     
>       PaddleDetection/deploy/cpp/CMakeLists.txt
>     
>     
>          Line 156
>       in
>       c7a1252
>     
>     
>     
>     
> 
>         
>           
>            ${PADDLE_DIR}/paddle/fluid/inference/libpaddle_fluid${CMAKE_STATIC_LIBRARY_SUFFIX}) 
>         
>     
>   
> 
> 
> paddle预测库的依赖在这里设置的，paddle_dir在这里解析就是${PADDLE_DIR}，你找下解压的fluid_inference中libpaddle_fluid.lib的路径，然后对应修改下这里代码和paddle_dir。

你好我也遇到相同的问题，请问这段代码，您是怎么更改的
${PADDLE_DIR}/paddle/fluid/inference/libpaddle_fluid${CMAKE_STATIC_LIBRARY_SUFFIX})
