### ISSUE TITLE
jetson部署

### ISSUE THREAD

**Issue by song121982** [PaddlePaddle/PaddleDetection#5692]
请问支持NVIDIA jetson Orin嘛?

那个还有我之前的问题一直没被解答哇

**Comment by wangxinxin08** [comment]
jetson orin是新出的硬件，目前还没有验证过，目前在jetson tx2 agx nx nano上验证过是支持的

**Comment by song121982** [comment]
> 

麻烦建议官方验证更新下，AGX已经停产了，现在做项目做设计只能用新出的Orin了。

**Comment by song121982** [comment]
建议官方验证更新一下，现在AGX已经停产了，大众能买到的只有这个Orin了，感觉这个事情还是挺重要的，谢谢。 @wangxinxin08

**Comment by wangxinxin08** [comment]
目前软件栈应该是ok的，CUDA, cuDNN以及TensorRT整个软件栈在jetson的其他系列已经验证过
