### ISSUE TITLE
[BUG]华为昇腾910 训练

### ISSUE THREAD

**Issue by zyl75391** [PaddlePaddle/PaddleDetection#5697]
使用华为昇腾910 训练
![e72bec62fb47ed9ef27195df56fdda3](https://user-images.githubusercontent.com/59155736/163358107-4d366aa5-7422-4519-8d00-450dd4642907.jpg)

模型加载在npu里但是使用率为0
![e2bc8ac53dde1b0cecac15bc8c498a1](https://user-images.githubusercontent.com/59155736/163358129-8c106d22-5128-4d4c-b894-a5ca11b6f95a.jpg)
使用半精度训练问题同样

**Comment by zyl75391** [comment]
还需要我补充别的信息吗

**Comment by zyl75391** [comment]
<img width="265" alt="23cb749e8d3df966d061947181f7ad8" src="https://user-images.githubusercontent.com/59155736/163969161-6f0ac766-7e13-44ff-b182-80d850f10800.png">

环境信息 
使用官方docker环境  paddlepaddle/paddle:latest-dev-cann5.0.2.alpha005-gcc82-aarch64

**Comment by Aganlengzi** [comment]
@zyl75391 hi，看你截图的信息，显存有占用，你是要使用「使用率」数据还是为了确定是在昇腾910卡上跑？

**Comment by zyl75391** [comment]
@Aganlengzi      您好我是为了确认训练可以正常运行，我发现训练之后很长时间都没有跟新数据，所以我看了tpu的info，发现显存有明显的占用，说明模型加载在tpu中了      但是tpu使用率非常低，说明可能没有用tpu进行计算。

**Comment by Aganlengzi** [comment]
@zyl75391 hi，我查了内部关于yolov3_darknet53_270e_voc.yml适配的记录，这个模型目前还没有提测。
根据记录，模型是跑在昇腾910芯片上的（check方法：打开export GLOG_v=4，查看输出日志是否有关键字`missing`将算子fallback到CPU）。
当时记录的性能数据比较差，与V100相比只有18%左右，不排除有些算子在昇腾910芯片内部跑在AI CPU上而非AI Core上；
另外，昇腾910芯片上训练有个冷启动阶段，开始可能会比较慢。

**Comment by zyl75391** [comment]
@Aganlengzi 
![图片](https://user-images.githubusercontent.com/59155736/164588648-2b73afe0-5486-4c80-8e2d-4a5c6606531b.png)

**Comment by Aganlengzi** [comment]
> @Aganlengzi ![图片](https://user-images.githubusercontent.com/59155736/164588648-2b73afe0-5486-4c80-8e2d-4a5c6606531b.png)

看日志算子是正常跑在昇腾910芯片上的。

**Comment by zyl75391** [comment]
有测试过的目标检测模型吗。确实有一部分是在CPU上

![图片](https://user-images.githubusercontent.com/59155736/164589819-149a99b6-4a71-4b80-9b83-4028b3303549.png)

**Comment by Aganlengzi** [comment]
> 有测试过的目标检测模型吗。确实有一部分是在CPU上
> 
> ![图片](https://user-images.githubusercontent.com/59155736/164589819-149a99b6-4a71-4b80-9b83-4028b3303549.png)

Host端框架逻辑肯定是CPU上跑，看你贴出的日志，算子是正常跑在昇腾910芯片上的；
昇腾910内部有AICore(DaVinci AI Core)和AICPU(Taishan Core)，我指的AI CPU是芯片内部的，这块我们看不到；如果输出的日志中没有missing、fallback字样，说明算子是跑在昇腾910芯片上的。

目标检测模型可尝试YoloV3-DarkNet53(静态图) 和 SSD-MobileNetV1(动态图)

**Comment by zyl75391** [comment]
@Aganlengzi  
大概半个小时  现在好像正常了   我想问下[PaddleDetection] 怎么做动和静态的转换  好像2.x版本后  我没看见过相关文档是默认转换的吗。
![图片](https://user-images.githubusercontent.com/59155736/164592368-4c590054-aad6-4ca6-af68-0ca94e9e66eb.png)

**Comment by Aganlengzi** [comment]
> 大概半个小时 现在好像正常了

@zyl75391 如果训练的问题解决 建议您另开个issue具体描述下您转换的需求，会有相关值班同学跟进，谢谢！

**Comment by zyl75391** [comment]
@Aganlengzi  好的，非常感谢您的帮助

**Comment by Aganlengzi** [comment]
> @Aganlengzi 好的，非常感谢您的帮助

不客气，这个issue我关掉了，后续有问题再沟通~
