### ISSUE TITLE
coco数据集格式问题以及分类类别问题

### ISSUE THREAD

**Issue by Stillremains** [PaddlePaddle/PaddleDetection#570]
我现在用yolov3 datknet coco格式的数据 为啥我看json文件标注  categories的id都是从1开始  而我自己用 从1开始 他就报错 我是红绿灯的 就分两类  下图是我设置id从1开始的bao报错
![cuowu](https://user-images.githubusercontent.com/48147367/80450786-e1656c00-8954-11ea-80b5-696151c0f82b.png)
如果我改成从0 开始 这个错误就没有
![shezhi](https://user-images.githubusercontent.com/48147367/80450831-f7732c80-8954-11ea-8379-d2127f8d786b.png)
看他们的格式都是从1开始 我从0开始才行？我看了coco_eval.py文件里 0不是分配给background的么

然后还想问分类的问题 怎么改成只分类红绿灯的？？ 这方面教程也没 不过看coco_eval.py有这方面的分类 是改这里？表示一脸懵逼
另外万人血书求个群 身边一堆人不懂 求详细文档

**Comment by jerrywgz** [comment]
关于cooc数据集的问题 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/data/source/coco.py#L86 在这里可以看到，无论标注文件中给定的类别，都会在这里生成一个分类id和实际id的对照表，这个表的生成和是否包含背景类有关，如果包含背景类，则分类id 0 是分配给backgroud。

关于你的报错，coco标准的标注格式中，annotation里存放的每个instance的类别是存在‘category_id’中的，PaddleDetection也会根据这个字段来读取，而‘id’字段表示的是该instance属于那个图片id

如果想只对红绿灯进行分类，需要先过滤下数据，保留红绿灯相关的instance，然后修改配置文件中的num_classes为（1+with_background）,这边有个迁移学习文档可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md

**Comment by Stillremains** [comment]
> 关于cooc数据集的问题 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/data/source/coco.py#L86 在这里可以看到，无论标注文件中给定的类别，都会在这里生成一个分类id和实际id的对照表，这个表的生成和是否包含背景类有关，如果包含背景类，则分类id 0 是分配给backgroud。
> 
> 关于你的报错，coco标准的标注格式中，annotation里存放的每个instance的类别是存在‘category_id’中的，PaddleDetection也会根据这个字段来读取，而‘id’字段表示的是该instance属于那个图片id
> 
> 如果想只对红绿灯进行分类，需要先过滤下数据，保留红绿灯相关的instance，然后修改配置文件中的num_classes为（1+with_background）,这边有个迁移学习文档可以参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md

你好 数据格式的问题我发现问题了 是我在voc转coco的过程中一个参数没处理好 就是您说的‘category_id’ 与下面的categories 的id不对应造成的 另外我比较好奇为啥num_classes填（1+with_background） 不应该是2么     我在yml中with_background设置为false

**Comment by Stillremains** [comment]
我之前yolov3 darknet voc跑的时候num_classes 也设置的2  不过跑出来不知道为啥 有些图片直接没有框框了 而且数量挺多的 比如我验证集400张 差不多有三分之一的图片没有框框输出 把threshold调小后 出现了比较多框框但是没有框灯上  有人说是没训练好 但我看mAP也挺高啊 不知道为啥没框框 按理说红绿灯很好识别

**Comment by jerrywgz** [comment]
使用yolo训练的话with_ground应该是False，所以num_classes应该设置为1

**Comment by Stillremains** [comment]
> 使用yolo训练的话with_ground应该是False，所以num_classes应该设置为1

我明明是两种 设置为1 怎么去理解?  0  1?

**Comment by Stillremains** [comment]
> > 使用yolo训练的话with_ground应该是False，所以num_classes应该设置为1
> 
> 我明明是两种 设置为1 怎么去理解? 0 1?

要是去其他网络呢？比如fast rcnn呢？

**Comment by jerrywgz** [comment]
你这里需要训练的类别数总共是多少呢，如果只是红绿灯这一类的话，那在yolo当中num_classes就是1。 faster rcnn的话是需要增加背景类的，即num_classes需要设置成2

**Comment by jerrywgz** [comment]
还有一点就是，你可视化效果不好也可以再确认下模型加载的是否正确

**Comment by Stillremains** [comment]
> 你这里需要训练的类别数总共是多少呢，如果只是红绿灯这一类的话，那在yolo当中num_classes就是1。 faster rcnn的话是需要增加背景类的，即num_classes需要设置成2

哦哦 可能我表达不清楚 识别绿色和红色的灯的意思哈哈

**Comment by jerrywgz** [comment]
嗯那在yolo里num_classes是2，faster_rcnn中num_classes是3

**Comment by Stillremains** [comment]
> 嗯那在yolo里num_classes是2，faster_rcnn中num_classes是3

我崩了 能否加个联系方式我qq32488484  感觉这里联系比较麻烦  好奇怪我识别出来 不管什么颜色都red。。。。 我仔细看了数据集中images和annotations 的‘category_id’  与下免categories 类别是对应的 没有问题

**Comment by Stillremains** [comment]
> > 嗯那在yolo里num_classes是2，faster_rcnn中num_classes是3
> 
> 我崩了 能否加个联系方式我qq32488484 感觉这里联系比较麻烦 好奇怪我识别出来 不管什么颜色都red。。。。 我仔细看了数据集中images和annotations 的‘category_id’ 与下免categories 类别是对应的 没有问题

![coico](https://user-images.githubusercontent.com/48147367/80465807-3eb9e700-896e-11ea-9146-1d19e132069c.png)  这是我在类别推断 那里改的代码 应该没有什么问题 不知道为什么全部识别为red

**Comment by Stillremains** [comment]
已经解决了，我数据集处理有错误，同样的id 有两张

**Comment by forestemperor** [comment]
> 已经解决了，我数据集处理有错误，同样的id 有两张

所以category的id从0和1开始都行吗？
