### ISSUE TITLE
[Feature Request] PP-Human动作识别模块

### ISSUE THREAD

**Issue by WooXinyi** [PaddlePaddle/PaddleDetection#5711]
目前动作识别模块只有跌倒这种动作，后续会考虑识别更多的动作吗？如果会，会有哪些动作呢？

**Comment by zoooo0820** [comment]
感谢关注。 扩充行为识别的动作已有计划，目前具体考虑新增的动作还在结合实际应用场景调研中。也十分欢迎提出您的需求或是建议。

**Comment by jingting-mountain** [comment]
动作识别模块能够自己训练模型识别其他动作吗？如果可以，请问如何操作？

**Comment by zoooo0820** [comment]
我们更新了自定义训练的文档，请参考[文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/pphuman/docs/action.md)的`自定义模型训练部分`
