### ISSUE TITLE
TestReader读取图片时resize后图片宽度问题

### ISSUE THREAD

**Issue by nealbity** [PaddlePaddle/PaddleDetection#572]
以使用OIDV5数据集训练的Cascade R-CNN为例，yml中test的target_size是800。我按照相同逻辑自行将图片预处理后作为feed送入模型，发现ShapeError的报错，检查后发现reader读取的图片会比我自己resize的图片宽（例如demo中的orange_71.jpg宽了32个像素，000000570688.jpg宽了22个像素）。并且多出来的右侧这部分貌似是进行了填0的操作。请问resize的宽度是如何确定的呢？

**Comment by jerrywgz** [comment]
test中resize的逻辑和训练和评估时的resize逻辑相同，都是将图片的短边先等比例resize到800，然后如果长边大于1333则再将长边等比例resize到1333，之后由于使用了fpn的原因，要求输入尺寸必须为32的倍数，因此将图片统一padding
