### ISSUE TITLE
Picodet更换注意力模块后mAP骤降

### ISSUE THREAD

**Issue by lip0041** [PaddlePaddle/PaddleDetection#5725]
## 问题描述
在AIStudio上，搭配了paddlepaddle2.2，使用的picodet是backbone为esnet的版本，数据集是coco的验证集。

在esnet.py中增添了Coordinate Attention模块的代码，将原本的SEmodule更换为CAModule，进行训练，如图经过第一个10epoch后mAP比起原版本骤降

![p1](https://user-images.githubusercontent.com/53994773/163718297-29d669b9-61c5-4150-bbfc-d881958a55bc.png)
第一个10epoch原本第一个指标mAP(0.5, 0.95)应为约0.040，但这里仅有0.002。
更换注意力机制SEModule为CAModule应该效果会更好（根据Coordinate Attention论文中CA效果要比SE高出0.6%～0.7%指标）
![p2](https://user-images.githubusercontent.com/53994773/163718529-48d40254-b9dd-4063-838f-347bfc2eaacd.png)
但实际不增反而骤降

CA模块的代码为
```python
class CAModule(nn.Layer):
    def __init__(self, channel, groups=32):
        super(CAModule, self).__init__()
        self.pool_h = AdaptiveAvgPool2D((None, 1))
        self.pool_w = AdaptiveAvgPool2D((1, None))

        mip = max(8, channel // groups)

        self.conv1 = Conv2D(
            in_channels=channel,
            out_channels=mip,
            kernel_size=1,
            stride=1,
            padding=0
        )
        self.bn1 = nn.BatchNorm2D(mip)
        self.conv2 = Conv2D(
            in_channels=mip,
            out_channels=channel,
            kernel_size=1,
            stride=1,
            padding=0
        )
        self.conv3 = Conv2D(
            in_channels=mip,
            out_channels=channel,
            kernel_size=1,
            stride=1,
            padding=0
        )

    def forward(self, x):
        
        indentity = x
        n,c,h,w = x.shape
        x_h = self.pool_h(x)
        x_w = paddle.transpose(self.pool_w(x), (0, 1, 3, 2))

        y = paddle.concat([x_h, x_w], axis=2)
        y = self.conv1(y)
        y = self.bn1(y)
        y = F.hardswish(y)
        x_h, x_w = paddle.split(y, [h, w], axis=2)
        x_w = paddle.transpose(x_w, (0, 1, 3, 2))

        x_h = paddle.expand(F.hardsigmoid(self.conv2(x_h)), (-1, -1, h, w))
        x_w = paddle.expand(F.hardsigmoid(self.conv3(x_w)), (-1, -1, h, w))

        y = indentity * x_w * x_h

        return y
```
使用模块即把InvertedResidual和InvertedResidualDS中的SE均改为调用CA。

## 疑惑
请问这是为什么呢？应该怎么去解决这个问题，之前我也有把SEModule改为ECAModule（同为一种更优的注意力机制），但结果也是mAP骤降。训练时的loss是正常降低的，除了原先导入的预训练权重se部分没有导入外，没有其他警告信息

**Comment by yghstill** [comment]
@lip0041 修改backbone结构后，预训练weight会失效，多训些轮数看下？或者对比下base config不加载pretrain的结果

**Comment by lip0041** [comment]
> @lip0041 修改backbone结构后，预训练weight会失效，多训些轮数看下？或者对比下base config不加载pretrain的结果

base config不加载pretrain，结果也是骤降
![Screen Shot 2022-04-18 at 12 26 55](https://user-images.githubusercontent.com/53994773/163754378-03119ff2-99eb-467b-8ec8-b9c6ce50faf1.png)

多训练几轮的话（训练100个epoch），加载pretrain时mAP(0.5:0.95)应该达到近30%，不加载时100个epoch后仅能达到10%左右。

预训练权重这个东西，我们个人用户可能什么方式有效获取或修改吗？比如说baseconfig中加载到预训练权重是https://paddledet.bj.bcebos.com/models/pretrained/ESNet_x0_75_pretrained.pdparams。

有没有方法修改pdparams中要替换模块的权重信息，或增加一些权重信息？如果有这个修改或增加权重值应该怎么去设定才会有效呢

**Comment by yghstill** [comment]
@lip0041 请参考[PaddleClas](https://github.com/PaddlePaddle/PaddleClas)重新在imagenet上训练下pretrain，但PicoDet中使用的ESNet是搜索得到的，PaddleClas无法直接得到，建议使用PicoDet基于LCNet的增强版模型，PaddleClas可直接训练得到~

**Comment by lip0041** [comment]
> @lip0041 请参考[PaddleClas](https://github.com/PaddlePaddle/PaddleClas)重新在imagenet上训练下pretrain，但PicoDet中使用的ESNet是搜索得到的，PaddleClas无法直接得到，建议使用PicoDet基于LCNet的增强版模型，PaddleClas可直接训练得到~

好的，请问有什么工具或方法可以编辑pdparams文件吗

**Comment by lip0041** [comment]
> @lip0041 请参考[PaddleClas](https://github.com/PaddlePaddle/PaddleClas)重新在imagenet上训练下pretrain，但PicoDet中使用的ESNet是搜索得到的，PaddleClas无法直接得到，建议使用PicoDet基于LCNet的增强版模型，PaddleClas可直接训练得到~

好的，我后续会考虑基于LCNet，另外请问有什么工具或方法可以编辑pdparams文件吗

**Comment by yghstill** [comment]
@lip0041 可以参考https://github.com/yghstill/paddle_some_toolkit/blob/main/ppcls_to_ppdet/match_weight_name.py#L5
load weight后可以使用numpy处理

**Comment by lip0041** [comment]
> @lip0041 可以参考https://github.com/yghstill/paddle_some_toolkit/blob/main/ppcls_to_ppdet/match_weight_name.py#L5
> load weight后可以使用numpy处理

好的 谢谢

**Comment by lip0041** [comment]
请问修改backbone，增加一些模块（如卷积）在原backbone对应的预训练权重正常加载的情况下，为什么训练后的模型mAP还是会下降很多呢？  
请问在原有backbone基础上添加模块，需要遵循什么步骤或按照什么方法吗？

**Comment by liuhuixiang-987** [comment]
有找到mAP骤降的原因吗

**Comment by Schweizliu** [comment]
> 

有找到mAP骤降的原因吗
