### ISSUE TITLE
🔥 实时行人分析系统PP-Human已发布，欢迎大家试用讨论

### ISSUE THREAD

**Issue by jerrywgz** [PaddlePaddle/PaddleDetection#5728]
🔥 PP-Human是基于飞桨深度学习框架的业界首个开源实时行人分析系统，具有以下特色：

功能丰富：覆盖三大功能、六大核心技术，支持属性识别、行为识别和流量计数
泛化能力强：通过丰富训练数据、优化网络结构及工程实现，模型具备较强泛化性，适应不同光线、视角、背景
极低使用门槛：兼容图片，单镜头视频，多镜头视频输入类型，一行命令功能即可快速实现
超高灵活度：六大核心技术灵活解耦，支持任意高效重组
详细细节请见：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/pphuman

为了方便大家交流沟通，欢迎扫码添加微信群，提出您的意见、建议或者使用中的疑问。
<img width="250" alt="tinypose_group" src="https://user-images.githubusercontent.com/48054808/172337694-770d5b4d-b6b9-4f9e-913f-dcd463e2c600.jpeg">

🌈 **未来计划：**
- 属性识别：新增自定义属性训练
- 动作分析：新增打架、抽烟、玩手机、睡觉、工业SOP五大动作类型；完善动作类型扩展文档

📮 因此，现向各位用户征集实际落地场景，有以上动作或其他动作识别需求的用户【欢迎联系飞桨-PM 微信：18108656919】（备注：姓名+企业+具体动作类型）

**Comment by LiQiang0307** [comment]
可支持多镜头视频输入，是否支持同时传入两个摄像头的实时视频流并实时显示结果？

**Comment by jerrywgz** [comment]
目前多镜头视频还是以串联的方式依次读取

**Comment by Indigo6** [comment]
您好，请问我是否可以将目标检测/姿态估计的模型替换为更大的模型来提升准确度呢？

**Comment by nemonameless** [comment]
> 您好，请问我是否可以将目标检测/姿态估计的模型替换为更大的模型来提升准确度呢？

可以的，训练完后需要像这样[导出模型权重](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/python#1-%E5%AF%BC%E5%87%BA%E9%A2%84%E6%B5%8B%E6%A8%A1%E5%9E%8B)，然后更改配置文件里的路径为你的新的模型权重 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/pphuman/config/infer_cfg.yml

**Comment by Indigo6** [comment]
> > 您好，请问我是否可以将目标检测/姿态估计的模型替换为更大的模型来提升准确度呢？
> 
> 可以的，训练完后需要像这样[导出模型权重](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/python#1-%E5%AF%BC%E5%87%BA%E9%A2%84%E6%B5%8B%E6%A8%A1%E5%9E%8B)，然后更改配置文件里的路径为你的新的模型权重 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/pphuman/config/infer_cfg.yml

好的，感谢您的回复~

**Comment by mazai-xiangji** [comment]
你好，我在使用带TensorRT的paddle时，import paddle为什么会发生【ImportError: DLL load failed while importing core_avx: 动态链接库(DLL)初始化例程失败】这样的错误

**Comment by nemonameless** [comment]
> 你好，我在使用带TensorRT的paddle时，import paddle为什么会发生【ImportError: DLL load failed while importing core_avx: 动态链接库(DLL)初始化例程失败】这样的错误

你好，请至少说明下什么版本哪个平台谢谢？以及可以搜索[issues](https://github.com/search?q=org%3APaddlePaddle+ImportError%3A+DLL+load+failed+while+importing+core_avx&type=issues)

**Comment by mazai-xiangji** [comment]
你好，部署在win10的pp-human的行为识别除了通过tensorrt推理加速外，是否可以通过使用更小的模型来更换其中的目标检测或者关键点提取模型来提高速度

**Comment by YixinKristy** [comment]
您好，可以尝试替换更轻量的检测和关键点模型，更改模型路径方式有两种：
1. `./deploy/pphuman/config/infer_cfg.yml`下可以配置不同模型路径，关键点模型和行为识别模型分别对应KPT和ACTION字段，修改对应字段下的路径为实际期望的路径即可。
2. 命令行中增加--model_dir修改模型路径：
```
python deploy/pphuman/pipeline.py --config deploy/pphuman/config/infer_cfg.yml \
                                                   --video_file=test_video.mp4 \
                                                   --device=gpu \
                                                   --enable_action=True \
                                                   --model_dir kpt=./dark_hrnet_w32_256x192 action=./STGCN
```

**Comment by mazai-xiangji** [comment]
> 您好，可以尝试替换更轻量的检测和关键点模型，更改模型路径方式有两种：
> 
>     1. `./deploy/pphuman/config/infer_cfg.yml`下可以配置不同模型路径，关键点模型和行为识别模型分别对应KPT和ACTION字段，修改对应字段下的路径为实际期望的路径即可。
> 
>     2. 命令行中增加--model_dir修改模型路径：
> 
> 
> ```
> python deploy/pphuman/pipeline.py --config deploy/pphuman/config/infer_cfg.yml \
>                                                    --video_file=test_video.mp4 \
>                                                    --device=gpu \
>                                                    --enable_action=True \
>                                                    --model_dir kpt=./dark_hrnet_w32_256x192 action=./STGCN
> ```

你好，在将目标检测的模型换成picodet_s_192_pedestrian时会出现错误，请问对更换的模型有要求吗
error：Traceback (most recent call last):
  File "deploy/pphuman/pipeline.py", line 755, in <module>
    main()
  File "deploy/pphuman/pipeline.py", line 744, in main
    pipeline.run()
  File "deploy/pphuman/pipeline.py", line 206, in run
    self.predictor.run(self.input)
  File "deploy/pphuman/pipeline.py", line 414, in run
    self.predict_video(input)
  File "deploy/pphuman/pipeline.py", line 511, in predict_video
    [copy.deepcopy(frame)], visual=False)
  File "/home/aistudio/PaddleDetection/deploy/pptracking/python/mot_sde_infer.py", line 408, in predict_image
    det_result = self.postprocess(inputs, result)
  File "/home/aistudio/PaddleDetection/deploy/pptracking/python/mot_sde_infer.py", line 190, in postprocess
    if np_boxes_num[0] <= 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by zoooo0820** [comment]
@mazai-xiangji 
你好，这个问题是由于旧版的PicoDet模型的后处理与其他检测模型有区别导致的。目前PicoDet更新后已经支持将后处理部分合进模型中执行从而兼容这种情况。由于`picodet_s_192_pedestrian `这个模型的默认导出仍然是旧版不包含后处理的。可以重新参考下列命令执行导出即可：
```python
python tools/export_model.py -c configs/picodet/legacy_model/application/pedestrian_detection/picodet_s_192_pedestrian.yml -o weights=https://bj.bcebos.com/v1/paddledet/models/keypoint/picodet_s_192_pedestrian.pdparams export.nms=True export.post_process=True
```

**Comment by mazai-xiangji** [comment]
关于tensorrt使用的问题，根据[官方案例](https://aistudio.baidu.com/aistudio/projectdetail/3842982)使用--run_mode=trt_fp16开启tensorrt之后需要较长的一段时间去转化tensorrt的模型，然后在进行inference，推理速度会比原来快一些，但是重新运行时又要再一次加载tensorrt模型，想知道如何解决这个问题，tensorrt转化的模型不会自动保存吗
环境：OS win10  CUDA 10.2 cudnn 7.6.5  tensorrt 7.0.0.11 paddle版本是在[官方](https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows)下的带trt的版本

**Comment by jzdhd** [comment]
关于pphuman的摄像头问题，似乎没有在代码里看到有关于摄像头的解码部分，请问部署在WIN的pphuman对视频流进行预测是需要自己写相关的解码部分吗

**Comment by YixinKristy** [comment]
对于在线视频流的输入（编解码）的部分，目前PP-Human尚未支持，在7月份左右有计划支持~

**Comment by Cuzny** [comment]
你好，请问人体属性识别的StrongBaseline会开源吗？想要新增一个衣着颜色的属性。

**Comment by zhouyuchong** [comment]
@Cuzny 这篇论文来源于[here](https://arxiv.org/pdf/2107.03576v2.pdf)，本身就是开源的，代码在github上[here](https://github.com/valencebond/Rethinking_of_PAR)。颜色属性是自带的，但是在训练之前需要选择需要的属性（那个数据集里面的属性特别多）。
但是飞浆的mA比原文还高了8、9个百分点属实把我震撼了。推理速度也特别快，我自己2080ti上一张图要推理几十毫秒飞浆数据是2ms?不知道是不是进行了什么改动。

**Comment by YixinKristy** [comment]
> 你好，请问人体属性识别的StrongBaseline会开源吗？想要新增一个衣着颜色的属性。

PP-Human的属性识别及行为识别的训练教程将在本月底前发布~

**Comment by ccLemonTree** [comment]
你好，我想问一下我更改了infer_config.yml中ACTION的max_frames参数 对视频进行推理时为什么会出现这个错误
![image](https://user-images.githubusercontent.com/94359077/172352544-273fc21e-e401-4b42-9241-f1a7e5711732.png)
![image](https://user-images.githubusercontent.com/94359077/172353134-27f4f932-71d2-43b3-947f-22349010d6b1.png)

**Comment by EdsionYeh** [comment]
> 



> > 你好，请问人体属性识别的StrongBaseline会开源吗？想要新增一个衣着颜色的属性。
> 
> PP-Human的属性识别及行为识别的训练教程将在本月底前发布~

您好，一直在等待能自定义训练，现在已经7月中了，请问属性识别及行为识别的训练教程什么时候能安排上？谢谢

**Comment by YixinKristy** [comment]
> > 
> 
> > > 你好，请问人体属性识别的StrongBaseline会开源吗？想要新增一个衣着颜色的属性。
> > 
> > 
> > PP-Human的属性识别及行为识别的训练教程将在本月底前发布~
> 
> 您好，一直在等待能自定义训练，现在已经7月中了，请问属性识别及行为识别的训练教程什么时候能安排上？谢谢

已经上线啦：https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/pipeline

**Comment by EdsionYeh** [comment]
> Referen



> > > 
> > 
> > 
> > > > 你好，请问人体属性识别的StrongBaseline会开源吗？想要新增一个衣着颜色的属性。
> > > 
> > > 
> > > PP-Human的属性识别及行为识别的训练教程将在本月底前发布~
> > 
> > 
> > 您好，一直在等待能自定义训练，现在已经7月中了，请问属性识别及行为识别的训练教程什么时候能安排上？谢谢
> 
> 已经上线啦：https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/pipeline

非常感谢！祝好

**Comment by YaoOOoooolin** [comment]
您好，请问现在开启摄像头实时可以使用吗，我尝试后会报错
Traceback (most recent call last):
  File "C:\Users\13708\PaddleDetection\deploy\pipeline\pipeline.py", line 1103, in <module>
    main()
  File "C:\Users\13708\PaddleDetection\deploy\pipeline\pipeline.py", line 1088, in main
    pipeline = Pipeline(FLAGS, cfg)
  File "C:\Users\13708\PaddleDetection\deploy\pipeline\pipeline.py", line 89, in __init__
    self.predictor.set_file_name(self.input)
  File "C:\Users\13708\PaddleDetection\deploy\pipeline\pipeline.py", line 476, in set_file_name
    self.file_name = os.path.split(path)[-1]
  File "C:\Users\13708\AppData\Local\Programs\Python\Python39\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not int

**Comment by wenke727** [comment]
> @Cuzny 这篇论文来源于[here](https://arxiv.org/pdf/2107.03576v2.pdf)，本身就是开源的，代码在github上[here](https://github.com/valencebond/Rethinking_of_PAR)。颜色属性是自带的，但是在训练之前需要选择需要的属性（那个数据集里面的属性特别多）。
> 但是飞浆的mA比原文还高了8、9个百分点属实把我震撼了。推理速度也特别快，我自己2080ti上一张图要推理几十毫秒飞浆数据是2ms?不知道是不是进行了什么改动。

同为T4，Ubuntu 18.04系统，cuda10.2，cuddn7.6， tensortrt 7.2，速度慢了一个数量级，而且频率占满，才到 150 fps，性能约为 paddle 官方提供数据的 30%

**Comment by zhangyuxinzz** [comment]
我在摔倒识别检测中，出现静态不动的拖把等被检测成摔倒的人的情况，按理说ST-GCN动作识别不得关节点有变化动作有变化才被识别么，请问这样我该怎么调优呢？将我的场景视频再加进去基于行为识别的预训练参数再训一版模型可以吗

**Comment by daihuidai** [comment]
请问 PP-LCNet_x1_0 有PP-Human的预训练模型吗？我只找到了推理模型和关于imagenet的预训练模型，没有PP-Human的预训练模型

**Comment by nuonuo0426** [comment]
进行行人属性识别二次开发，关于PaddleDetection 和训练代码PaddleClas的关系，两个代码很多都重复了，她们应该属于两个代码项目，但是训练又要在PaddleClas中进行，数据又放在PaddleDetection中，不能只用PaddleClas进行训练嘛？看二次开发的时候有点懵，能不能跟我讲一下她们两个的关系呀？开发的时候是不是两个代码同时进行的哇，求求了
