### ISSUE TITLE
ssd_mobilenet_v1_voc.yml中先验框的大小修改会报错

### ISSUE THREAD

**Issue by ai-zml** [PaddlePaddle/PaddleDetection#573]
@heavengate 您好，又要麻烦你了，我在训练自己的VOC源的数据集时遇到这么一个问题，就是我的检测目标尺寸都比较小，可能是[10,10]~[150,150]，大多集中在[60,60], 所以我就想修改先验框的尺寸，也就是max_sizes和min_sizes这两个字段的值，但是只要一修改就报出一堆错误，请问这个是已经固定了，不能修改吗？谢谢

MultiBoxHead:
  aspect_ratios: [[2.], [2., 3.], [2., 3.], [2., 3.], [2., 3.], [2., 3.]]
  base_size: 512
  flip: true
  max_ratio: 90
  **max_sizes: [[], 150.0, 195.0, 240.0, 285.0, 300.0]**
  min_ratio: 20
  **min_sizes: [60.0, 105.0, 150.0, 195.0, 240.0, 285.0]**
  offset: 0.5

**Comment by still-wait** [comment]
@ai-zml `min_sizes `和`max_sizes `可以修改，你修改成了什么样子，会报什么错？

**Comment by ai-zml** [comment]
**修改成了这样：**
max_sizes: [30, 60, 105, 150, 225, 265]
min_sizes: [15, 30, 60, 105, 150, 225]

**错误是这样：**
Traceback (most recent call last):
  File "tools/train.py", line 331, in <module>
    main()
  File "tools/train.py", line 116, in main
    train_fetches = model.train(feed_vars)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/ssd.py", line 127, in train
    return self.build(feed_vars, 'train')
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/ssd.py", line 82, in build
    inputs=body_feats, image=im, num_classes=self.num_classes)
  File "/home/aistudio/work/PaddleDetection/ppdet/core/workspace.py", line 150, in partial_apply
    return op(*args, **kwargs_)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/detection.py", line 2202, in multi_box_head
    min_max_aspect_ratios_order)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/detection.py", line 1786, in prior_box
    attrs=attrs, )
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1877, in __init__
    self.desc.check_attrs()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
2   paddle::framework::ExtractAttribute<std::vector<float, std::allocator<float> > >::operator()(boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>&) const
3   std::_Function_handler<void (std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >*, bool), paddle::framework::TypedAttrChecker<std::vector<float, std::allocator<float> > > >::_M_invoke(std::_Any_data const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >*, bool)
4   paddle::framework::OpDesc::CheckAttrs()

----------------------
Error Message Summary:
----------------------
Error: Cannot get attribute max_sizes by type std::vector<float, std::allocator<float> >, its type is std::vector<int, std::allocator<int> > at (/paddle/paddle/fluid/framework/attribute.h:42)

**Comment by still-wait** [comment]
@ai-zml 数组里的数，全部改成浮点数，再试一下

**Comment by ai-zml** [comment]
好的，我试试

**Comment by ai-zml** [comment]
真的运行起来了，真的谢谢你。

**Comment by still-wait** [comment]
好的，有问题再反馈，感谢使用并关注。
