### ISSUE TITLE
hrnet现在不支持tensorrt推理，怎么才能支持呢

### ISSUE THREAD

**Issue by zhangdengp** [PaddlePaddle/PaddleDetection#5732]
目前hrnet关节点好像不支持trnsorrt推理，改怎么做呢？

**Comment by jerrywgz** [comment]
HRNet模型是可以跑通tensort推理的，可以参考这个文档https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/python#22-%E5%85%B3%E9%94%AE%E7%82%B9%E6%A3%80%E6%B5%8B 
具体命令：`python deploy/python/det_keypoint_unite_infer.py --det_model_dir=output_inference/yolov3_darknet53_270e_coco/ --keypoint_model_dir=output_inference/hrnet_w32_384x288/ --video_file={your video name}.mp4  --device=GPU --run_model=trt_fp32`

**Comment by zhangdengp** [comment]
> 

我也用这个命令，但是报错：
ValueError: (InvalidArgument) Pass tensorrt_subgraph_pass has not been registered. Please use the paddle inference library compiled with tensorrt or disable the tensorrt engine in inference configuration! 
  [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/pass.h:236)

**Comment by jerrywgz** [comment]
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python 需要从这里面下载带tensorrt的paddle whl包
