### ISSUE TITLE
保存program，加载后重新运行，py_reader报错

### ISSUE THREAD

**Issue by qjing666** [PaddlePaddle/PaddleDetection#574]
尝试了在组网后将program保存到本地，重新加载后训练中py_reader报错如下
![image](https://user-images.githubusercontent.com/19721227/80556465-34e3c280-8a06-11ea-81da-a3bdc5126436.png)想请问这个py_reader是在哪里调用的呢，是否可以改成其他reader呢

**Comment by willthefrog** [comment]
"组网后将program保存到本地，重新加载后训练"具体是怎么操作的呢？ py_reader是`fluid.io.DataLoader`内部调用的。

**Comment by qjing666** [comment]
问题已解决
