### ISSUE TITLE
AttributeError: 'Program' object has no attribute '_remove_training_info'[BUG]

### ISSUE THREAD

**Issue by Roly-Yang** [PaddlePaddle/PaddleDetection#5743]
## 描述问题

在使用--export_serving_model时遇到如下报错：
Traceback (most recent call last):
  File "tools/export_model.py", line 115, in <module>
    main()
  File "tools/export_model.py", line 111, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 90, in run
    params_filename="model.pdiparams")
  File "/home/phm/J/Anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle_serving_client/io/__init__.py", line 334, in inference_model_to_serving
    model_filename, params_filename, show_proto, feed_alias_names, fetch_alias_names)
  File "/home/phm/J/Anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle_serving_client/io/__init__.py", line 214, in save_model
    new_model_file.write(main_program._remove_training_info(False).desc.serialize_to_string())
AttributeError: 'Program' object has no attribute '_remove_training_info'

## 环境/Environment

ubuntu 18.0 base on GPU
python3.7
cuda10.0
paddledetection==2.3.0
paddleserving==0.8.3

## 复现/Reproduction

导出在paddledetection下训练的模型，使用的命令如下：
python tools/export_model.py -c configs/ssd/ssd_mobilenet_v1_300_120e_voc.yml --output_dir=./inference_model -o weights=output/ssd_mobilenet_v1_300_120e_voc/model_final.pdparams --export_serving_model=True

**Comment by ShiningZhang** [comment]
请问使用的Paddle版本是多少？paddleserving 0.8.3应该配套使用PaddlePaddle 2.2.2版本

**Comment by Roly-Yang** [comment]
> 请问使用的Paddle版本是多少？paddleserving 0.8.3应该配套使用PaddlePaddle 2.2.2版本
您好 以下是我的版本信息：
paddlepaddle              2.0.2    
paddlepaddle-gpu          2.1.1

那么我现在是需要安装什么版本的paddleserving呢？我尝试安装0.7.0的依旧报错

**Comment by Roly-Yang** [comment]
> 请问使用的Paddle版本是多少？paddleserving 0.8.3应该配套使用PaddlePaddle 2.2.2版本

您好，我升级了paddlepaddle到2.2.2版本之后成功导出了模型，我想问一下：如何使用训练得到的model_final.pdparams文件，导出模型的文件是__model___和__params__？

我现在只能导出以下四个文件，万分感谢～
①infer_cfg.yml,
②model.pdiparams, 
③model.pdiparams.info, 
④model.pdmodel

**Comment by Roly-Yang** [comment]
问题已解决
