### ISSUE TITLE
PP-TinyPose在执行图片预测时，picodet_postprocess.py文件总是显示 cannot reshape array of size 1 into shape (4)

### ISSUE THREAD

**Issue by wy1996-hub** [PaddlePaddle/PaddleDetection#5745]
!python deploy/python/det_keypoint_unite_infer.py --det_model_dir=output_inference/picodet_s_320_pedestrian \
        --keypoint_model_dir=output_inference/tinypose_128x96 \
        --image_file=demo/000000570688.jpg --device=GPU --keypoint_threshold=0.35

-----------  Running Arguments -----------
camera_id: -1
cpu_threads: 1
det_model_dir: output_inference/picodet_s_320_pedestrian
det_threshold: 0.5
device: GPU
enable_mkldnn: False
image_dir: None
image_file: demo/000000570688.jpg
keypoint_batch_size: 8
keypoint_model_dir: output_inference/tinypose_128x96
keypoint_threshold: 0.35
output_dir: output
run_benchmark: False
run_mode: paddle
save_res: False
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dark: True
video_file: None
------------------------------------------
-----------  Model Configuration -----------
Model Arch: PicoDet
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--transform op: PadStride
--------------------------------------------
-----------  Model Configuration -----------
Model Arch: HRNet
Transform Order: 
--transform op: TopDownEvalAffine
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
Traceback (most recent call last):
  File "deploy/python/det_keypoint_unite_infer.py", line 269, in <module>
    main()
  File "deploy/python/det_keypoint_unite_infer.py", line 239, in main
    FLAGS.keypoint_batch_size, FLAGS.save_res)
  File "deploy/python/det_keypoint_unite_infer.py", line 80, in topdown_unite_predict
    results = detector.predict_image([image], visual=False)
  File "/home/aistudio/PaddleDetection/deploy/python/infer.py", line 263, in predict_image
    result = self.postprocess(inputs, result)
  File "/home/aistudio/PaddleDetection/deploy/python/infer.py", line 461, in postprocess
    np_boxes, np_boxes_num = postprocessor(np_score_list, np_boxes_list)
  File "/home/aistudio/PaddleDetection/deploy/python/picodet_postprocess.py", line 160, in __call__
    box_distance = np.sum(box_distance, axis=1).reshape((-1, 4))
ValueError: cannot reshape array of size 1 into shape (4)

--------------------------------------------------------------------------------------------------------------------------
运行的是aistudio项目，https://aistudio.baidu.com/aistudio/projectdetail/3839462

**Comment by yghstill** [comment]
@wy1996-hub 使用官方最新release/2.4代码试下呢？https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/python/keypoint_infer.py

**Comment by Jiaweixu2012** [comment]
这个版本picodet不需要post-process，模型最后一层就输出np_boxes, np_boxes_num了

**Comment by danielzhangau** [comment]
> 这个版本picodet不需要post-process，模型最后一层就输出np_boxes, np_boxes_num了

Halo, 请问下那为什么`infer.py`要在`class DetectorPicoDet(Detector):`里写一个重写一个`postprocess`，但没有跑他，跑的是`class Detector(object):`里的`postprocess`？

在第一个`postprocess`里是没有做`nms`的，是不需要吗？

**Comment by danielzhangau** [comment]
> @wy1996-hub 使用官方最新release/2.4代码试下呢？https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/python/keypoint_infer.py

我跑的是2.4，这个问题还是存在
