### ISSUE TITLE
训练PP-YOLOE的时候 报错TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by huangch1024** [PaddlePaddle/PaddleDetection#5746]
训练PP-YOLOE的时候出现这个报错，看这个应该是批处理数据的时候报错：
![image](https://user-images.githubusercontent.com/31469777/163914703-0333fd71-7ee4-44b9-b8e1-3fbdbd5585b6.png)
我看了下sampe输入是两个图片信息，请问这个是bug吗？

**Comment by wangxinxin08** [comment]
你修改了什么配置文件？

**Comment by huangch1024** [comment]
![image](https://user-images.githubusercontent.com/31469777/163921424-508753d1-78ea-40ff-a005-3f22fed84664.png)
这个是所有修改的配置，然后没有用gpu在测试。

**Comment by huangch1024** [comment]
> 你修改了什么配置文件？

![image](https://user-images.githubusercontent.com/31469777/163921555-2afef82e-5b75-471a-aa0d-243b5366e1e8.png)
这个是所有修改的配置，然后没有用gpu在测试。

**Comment by huangch1024** [comment]
> > 你修改了什么配置文件？
> 
> ![image](https://user-images.githubusercontent.com/31469777/163921555-2afef82e-5b75-471a-aa0d-243b5366e1e8.png) 这个是所有修改的配置，然后没有用gpu在测试。

去掉mixup_epoch：3这一行即可。
转述答案这里报错的原因是设置了mixup，但是预处理算子里面却没有，mixup在PP-YOLOE没有正向效果，所以配置中移除了这个预处理算子
