### ISSUE TITLE
PP-Picodet增强版疑问

### ISSUE THREAD

**Issue by Dekadenc** [PaddlePaddle/PaddleDetection#5750]
请问增强版是否有相关文档（改进部分的网络结构介绍），其次对于picodet有多少种型号，该如何进行选择。

**Comment by yghstill** [comment]
@chenfancc 可以查看文档：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/picodet
和模型升级解析：https://github.com/PaddlePaddle/PaddleDetection/issues/5723
PicoDet的model zoo中共9个模型，看你部署的设备情况，和实时性要求，如果比较低端的设备，建议使用xs和s系列模型，如果设备比较高端或者实时性要求不高，可使用m、L系列模型。
