### ISSUE TITLE
PicoDet的疑问

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleDetection#5756]
您好，有两点疑问：
（1）官方文档里的onnx模型的w后处理和wo后处理的含义是什么？
![image](https://user-images.githubusercontent.com/23066646/163970458-284f7f78-53cf-4b6f-b2d6-f33b5776725e.png)
（2）我用python的PaddleDetection/deploy/third_engine/demo_onnxruntime/的代码运行了一下图片，使用s和xs模型，CPU下推理时间是100毫秒，不是官网介绍的6毫秒4毫秒，时间差的比较大，不知是什么原因？
希望得到指导，谢谢

**Comment by yghstill** [comment]
@kingbirdWc 
1. w/ 后处理表示网络中带有后处理，w/o 表示网络中不带后处理
2. 官方测速使用https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/third_engine/demo_openvino/python ，可以详细看下文档，具体的测速要看CPU的型号，并且测速时确认下没有其他进程占用资源。
