### ISSUE TITLE
您好，我这样修改了还是会有那个constant，请问还需要改哪里吗？

### ISSUE THREAD

**Issue by LYHTZHANGJIANG** [PaddlePaddle/PaddleDetection#5757]
1 去除掉NMS，
2去除掉与scale_factor相关部分（paddle2onnx输入参数中只设置input image的值），
3所有代码都在postprocess里面，注释掉：从scale_y, scale_x =....此行开始到结束，增加return pred_bboxes,pred_scores。

_Originally posted by @sdreamforchen in https://github.com/PaddlePaddle/PaddleDetection/issues/5511#issuecomment-1097608819_

**Comment by sdreamforchen** [comment]
> 1 去除掉NMS， 2去除掉与scale_factor相关部分（paddle2onnx输入参数中只设置input image的值）， 3所有代码都在postprocess里面，注释掉：从scale_y, scale_x =....此行开始到结束，增加return pred_bboxes,pred_scores。
> 
> _Originally posted by @sdreamforchen in [#5511 (comment)](https://github.com/PaddlePaddle/PaddleDetection/issues/5511#issuecomment-1097608819)_

你按照3中说的都删除掉，应该是没问题的哈。你可以再将函数的输入变量scale_factor删除了，是不是这个你没有删除。
