### ISSUE TITLE
模型剪裁 'NoneType' object has no attribute '_var'

### ISSUE THREAD

**Issue by ZHZhang-whu** [PaddlePaddle/PaddleDetection#5758]
跑下面这个示例时（示例链接：https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/slim/prune/README.md），
python3 prune.py \
> -c ../../configs/yolov3_mobilenet_v1_voc.yml \
> --pruned_params "yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights" \
> --pruned_ratios="0.2,0.3,0.4"

AttributeError: 'NoneType' object has no attribute '_var'

third@ubuntu:~/Desktop/base/PaddleDetection/static/slim/prune$ python3 prune.py \
> -c ../../configs/yolov3_mobilenet_v1_voc.yml \
> --pruned_params "yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights" \
> --pruned_ratios="0.2,0.3,0.4"
/home/third/.local/lib/python3.8/site-packages/paddle/fluid/framework.py:744: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
2022-04-19 21:19:36,582-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
/home/third/.local/lib/python3.8/site-packages/paddle/fluid/io.py:2407: UserWarning: This list is not set, Because of Paramerter not found in program. There are: fc7_offset fc7_weights
  warnings.warn(
2022-04-19 21:19:41,139-INFO: pruned params: ['yolo_block.0.0.0.conv.weights', 'yolo_block.0.0.1.conv.weights', 'yolo_block.0.1.0.conv.weights']
2022-04-19 21:19:41,139-INFO: pruned ratios: [0.2, 0.3, 0.4]
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "prune.py", line 427, in <module>
    main()
  File "prune.py", line 221, in main
    train_prog = pruner.prune(
  File "/usr/local/lib/python3.8/dist-packages/paddleslim/prune/pruner.py", line 88, in prune
    collections = StaticPruningCollections(params, graph)
  File "/usr/local/lib/python3.8/dist-packages/paddleslim/prune/collections.py", line 243, in __init__
    self._collections = self.create_pruning_collections(
  File "/usr/local/lib/python3.8/dist-packages/paddleslim/prune/collections.py", line 182, in create_pruning_collections
    leaves = self._find_leaves(graph)
  File "/usr/local/lib/python3.8/dist-packages/paddleslim/prune/collections.py", line 136, in _find_leaves
    if len(_var.outputs()) == 0:
  File "/usr/local/lib/python3.8/dist-packages/paddleslim/core/graph_wrapper.py", line 103, in outputs
    if self in op.all_inputs():
  File "/usr/local/lib/python3.8/dist-packages/paddleslim/core/graph_wrapper.py", line 67, in __eq__
    return self._var.name == other._var.name
AttributeError: 'NoneType' object has no attribute '_var'

查看了一下源代码，未弄清问题原因
在做敏感度分析时同样遇到了这个报错

恳求各位大佬提供帮助

**Comment by yghstill** [comment]
@WITHBUG PaddleSlim的版本是多少？是<=1.0.1吗

**Comment by ZHZhang-whu** [comment]
> @WITHBUG PaddleSlim的版本是多少？是<=1.0.1吗

paddleslim版本为2.1.0，谢谢

**Comment by yghstill** [comment]
@WITHBUG 你跑的代码有点老，ppdet和paddleslim升级会导致不兼容问题的发生，ppdet请更新到2。4版本，paddleslim更新到2.2再试下，Demo使用：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/static/slim

**Comment by ZHZhang-whu** [comment]
> @WITHBUG 你跑的代码有点老，ppdet和paddleslim升级会导致不兼容问题的发生，ppdet请更新到2。4版本，paddleslim更新到2.2再试下，Demo使用：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/static/slim

感谢感谢，问题已经解决 确实是ppdet版本与slim不兼容导致

**Comment by moneypi** [comment]
```
(base) luke@luke-NH5x-7xRCx-RDx:~/PaddleDetection/static$ pip list|grep paddle
paddle-upgrade-tool           0.0.27
paddle2onnx                   0.9.5
paddledet                     2.4.0
paddlefsl                     1.1.0
paddlehub                     2.2.0
paddlenlp                     2.2.6
paddlepaddle-gpu              2.2.2
paddleslim                    2.2.2
paddleslim-opt-tools          2.11
(base) luke@luke-NH5x-7xRCx-RDx:~/PaddleDetection/static$ python slim/prune/prune.py -c ./configs/yolov3_mobilenet_v1_voc.yml --pruned_params "yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights" --pruned_ratios="0.2,0.3,0.4"
/home/luke/miniconda3/lib/python3.9/site-packages/fontTools/misc/py23.py:11: DeprecationWarning: The py23 module has been deprecated and will be removed in a future release. Please update your code.
  warnings.warn(
/home/luke/miniconda3/lib/python3.9/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
Traceback (most recent call last):
  File "/home/luke/PaddleDetection/static/slim/prune/prune.py", line 61, in <module>
    raise e
  File "/home/luke/PaddleDetection/static/slim/prune/prune.py", line 41, in <module>
    from ppdet.experimental import mixed_precision_context
ModuleNotFoundError: No module named 'ppdet.experimental'
```

**Comment by liupeng0606** [comment]
> @WITHBUG 你跑的代码有点老，ppdet和paddleslim升级会导致不兼容问题的发生，ppdet请更新到2。4版本，paddleslim更新到2.2再试下，Demo使用：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/static/slim

可否贴出您的版本信息，我也遇到了这样的问题

**Comment by ZHZhang-whu** [comment]
> > @WITHBUG 你跑的代码有点老，ppdet和paddleslim升级会导致不兼容问题的发生，ppdet请更新到2。4版本，paddleslim更新到2.2再试下，Demo使用：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/static/slim
> 
> 可否贴出您的版本信息，我也遇到了这样的问题

我的解决方式是 paddlepaddle和slim都换成了2.1版本 就不会报错了

**Comment by liupeng0606** [comment]
> > > @WITHBUG 你跑的代码有点老，ppdet和paddleslim升级会导致不兼容问题的发生，ppdet请更新到2。4版本，paddleslim更新到2.2再试下，Demo使用：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/static/slim
> > 
> > 
> > 可否贴出您的版本信息，我也遇到了这样的问题
> 
> 我的解决方式是 paddlepaddle和slim都换成了2.1版本 就不会报错了

请问您的cuda是那个版本？paddledet是哪个版本？
