### ISSUE TITLE
关于使用paddle inference自己编写代码运行行人预测模型，输出出错

### ISSUE THREAD

**Issue by yanglilongss** [PaddlePaddle/PaddleDetection#5759]
![image](https://user-images.githubusercontent.com/84090682/164048080-b3143a29-f206-4fb2-9ccf-c2e3878fa370.png)
这是我用paddle inference自己编写代码进行行人检测模型的预测的输入和输出
输入我进行比对和给的infer.py中处理图片后的输入一致，但是输出结果不一样
无法得到可信度和预测框坐标
下图为我将infer.py中图片处理后的结果的print输出，还有模型的输出
![image](https://user-images.githubusercontent.com/84090682/164049827-404cd23b-bce4-4ceb-ae3b-a111df26c3b1.png)
再有就是我自己写的代码中获取input_names的元素个数为1，但是infer.py中获取的元素个数却为2
![image](https://user-images.githubusercontent.com/84090682/164050702-f723da4e-2372-40b2-a635-da0f7e5a36d4.png)
![image](https://user-images.githubusercontent.com/84090682/164050749-db27746f-2071-443a-8e9d-add28b0cc078.png)

**Comment by yanglilongss** [comment]
![image](https://user-images.githubusercontent.com/84090682/164050966-b177711b-69ed-4198-9c98-7954f30e1c1f.png)
最后再附上我的源代码
望解答

**Comment by wangxinxin08** [comment]
@yanglilongss scale_factor就是你在resize的时候，宽和高的缩放因子哈，[scale_y, scale_x]，你可以添加下这个输入

**Comment by yanglilongss** [comment]
> @yanglilongss scale_factor就是你在resize的时候，宽和高的缩放因子哈，[scale_y, scale_x]，你可以添加下这个输入

但是我自己的代码读取的input_names只有一个元素这是因为什么呢？

**Comment by wangxinxin08** [comment]
@yanglilongss 这个和导出模型有关，如果你导出模型时没有导出scale_factor，这里应该就只有一个input_names
