### ISSUE TITLE
如何使用PaddleDetection导出模型__model__和__params__?  [Other General Issues]

### ISSUE THREAD

**Issue by Roly-Yang** [PaddlePaddle/PaddleDetection#5761]
## 描述问题/Describe the bug

如何使用PaddleDetection训练获得的model_final.pdparams文件导出模型__model__和__params__? 

## 复现/Reproduction

使用训练得到的model_final.pdparams文件，导出模型时只能导出以下四个文件：
①infer_cfg.yml,
②model.pdiparams,
③model.pdiparams.info,
④model.pdmodel

使用的命令是：
python tools/export_model.py -c configs/ssd/ssd_mobilenet_v1_300_120e_voc.yml --output_dir=./inference_model -o weights=output/ssd_mobilenet_v1_300_120e_voc/model_final.pdparams

## 环境/Environment

PaddlePaddle-gpu  2.2.2
PaddleDetection 2.3.0
cuda 10.0
ubuntu 18.0
python 3.7

万分感谢～

**Comment by yghstill** [comment]
@Roly-Yang 文件内容一致，直接重命名即可
```shell
mv model.pdmodel __model__
mv model.pdiparams __params__
```

**Comment by Roly-Yang** [comment]
> @Roly-Yang 文件内容一致，直接重命名即可
> 
> ```shell
> mv model.pdmodel __model__
> mv model.pdiparams __params__
> ```

谢谢 成功啦
