### ISSUE TITLE
[Other General Issues] ppyoloe的anchor在哪个文件里设置

### ISSUE THREAD

**Issue by nine-city** [PaddlePaddle/PaddleDetection#5766]
ppyoloe的anchor在哪个文件里设置

**Comment by wangxinxin08** [comment]
ppyoloe是anchor-free的模型，不需要设置anchor哈

**Comment by nine-city** [comment]
还有个问题：在大尺寸图片下（4000x4000px），ppyoloe需要特别调什么参数吗。

**Comment by wangxinxin08** [comment]
@nine-city 需要调整2处配置哈，另外，可以看下4000x4000是否有必要，是不是1024*1024就足够了
1. 多尺度训练时的尺寸，修改为eval尺寸0.5～1.2，每隔32取值: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/_base_/ppyoloe_reader.yml#L14
2. 评估时的尺寸: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/_base_/ppyoloe_reader.yml#L2
