### ISSUE TITLE
使用PaddleDetection突然报错

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#5767]
一直用的好好的，今天训练突然报错，百度查不到什么原因，求大佬解答
<img width="701" alt="f64ab901895d248f2a78a35b969cda2" src="https://user-images.githubusercontent.com/48303408/164162994-3d5f56c0-5413-460b-b4c8-4b5fff7b28cd.png">

**Comment by wangxinxin08** [comment]
从报错信息上来看是GLIB版本不匹配，你可以描述下:
1. 操作系统的环境
2. PaddlePaddle的版本
3. GCC版本
