### ISSUE TITLE
bad file

### ISSUE THREAD

**Issue by SeventhBlue** [PaddlePaddle/PaddleDetection#5768]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 已查阅相关issues问题，但是没有给出具体解决方法；

## 描述问题：所有输出信息如下，
REGISTER_CLASS:paddlex
init PaddleXModel,model_type=paddlex
terminate called after throwing an instance of 'YAML::BadFile'
  what():  bad file
Aborted (core dumped)

## 问题描述

1. 早期训练的模型依然可以使用，这次是后期添加新数据重新训练后，在板子上加载时出现的错误。
2.使用paddlex版本2.1.0，paddlex可视化客户端2.1.0，飞桨版本paddlepaddle2.2.1，cuda版本11.2，cudnn版本8.1.0；

**Comment by wangxinxin08** [comment]
应该是yaml文件路径错误哈

**Comment by SeventhBlue** [comment]
> 应该是yaml文件路径错误哈

[捂脸哭]哈哈哈，脑袋魔怔了，是路径问题。感谢答主耐心答复！
