### ISSUE TITLE
官方链接的YOLOV3 darknet format可以转成Paddle lite格式吗？

### ISSUE THREAD

**Issue by guoqiang0148666** [PaddlePaddle/PaddleDetection#577]
你好，感谢你们优秀的工作．

我从[YOLOV3的官方介绍](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/featured_model/YOLOv3_ENHANCEMENT.md)中下载了[YOLOV3 darknet format模型](https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet.tar)，请问该模型可以转成Paddle lite格式吗？我尝试着转换了一下，提示报错：
```
fin.is_open(): Cannot open file: yolov3_darknet/__model__
```
我发现yolov3_darknet文件夹下确实没有__model__文件，请问这种情况怎么解决呢？谢谢．

**Comment by willthefrog** [comment]
可以的，需要先用`tools/export_model.py` 导出 inference model 然后再用 lite的工具转换。

**Comment by qingqing01** [comment]
@guoqiang0148666   参考文档： https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/inference/EXPORT_MODEL.md

**Comment by guoqiang0148666** [comment]
@willthefrog @qingqing01 
谢谢，问题解决了。
