### ISSUE TITLE
【已解决】同样的输入尺寸下，在RV1126上面测试的时间快于YOLOX

### ISSUE THREAD

**Issue by LYHTZHANGJIANG** [PaddlePaddle/PaddleDetection#5772]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by wangxinxin08** [comment]
你是怎么测速的呢？

**Comment by LYHTZHANGJIANG** [comment]
就是你这是在pc上面测试的，我是移植到硬件平台之后测试的。移植过去有什么加速的操作吗？

**Comment by wangxinxin08** [comment]
@LYHTZHANGJIANG 怎么移植的，具体流程可以描述下，另外测速的方式是怎样的，两边统一吗？

**Comment by LYHTZHANGJIANG** [comment]
我是需要在RV1126这个硬件平台上面运行：
1、python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml --output_dir=output_inference -o weights=./output/ppyoloe_crn_s_300e_coco/0.pdparams
2、paddle2onnx --model_dir output_inference/ppyoloe_crn_s_300e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file ppyoloe_crn_s_300e_coco.onnx
3、把onnx 转成.rknn文件
然后就可以移植到板端运行了。测试方式是一样的。

**Comment by wangxinxin08** [comment]
@LYHTZHANGJIANG 
1. 这样导出PP-YOLOE是带NMS的，YOLOX导出是否带NMS可以确认下
2. 有一个小细节可以使得导出后的ONNX提速，就是在导出的时候将
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/modeling/ops.py#L49
修改成
```
ACT_SPEC = {'mish': mish, 'swish': swish}
```

**Comment by wangxinxin08** [comment]
@LYHTZHANGJIANG 可以先确认下是否都带NMS，再确认下第二点

**Comment by LYHTZHANGJIANG** [comment]
我在代码里面把NMS那部分给注释掉了，都不带NMS,NMS转模型的时候转换不过去。

![image](https://user-images.githubusercontent.com/49071179/164189786-2e930eb2-2caa-46d8-bc44-16bc3e97ce61.png)

**Comment by LYHTZHANGJIANG** [comment]
还有，我觉得可能是激活函数在这种硬件平台的支持度不是很好，所以就会运行比较慢.

**Comment by wangxinxin08** [comment]
@LYHTZHANGJIANG 那你修改下第二点重新导出试试吧，从网络结构，参数量，计算量的角度来看，同等模型不可能比YOLOX慢的

**Comment by wangxinxin08** [comment]
> 还有，我觉得可能是激活函数在这种硬件平台的支持度不是很好，所以就会运行比较慢.

你是说哪一个激活函数呢？

**Comment by LYHTZHANGJIANG** [comment]
哦哦一样的，我当时看到是swish，以为这个会比较慢，看到参数为1，那么也就是silu,那么YOLOX和YOLOv5中也都是silu,   还有一点就是我把PPYOLOE中的有个hardsigmoid 转成了sigmoid,由于hardsigmoid这个算子不支持

**Comment by wangxinxin08** [comment]
> 哦哦一样的，我当时看到是swish，以为这个会比较慢，看到参数为1，那么也就是silu,那么YOLOX和YOLOv5中也都是silu, 还有一点就是我把PPYOLOE中的有个hardsigmoid 转成了sigmoid,由于hardsigmoid这个算子不支持

sigmoid和hardsigmoid速度差异应该不会很大

**Comment by LYHTZHANGJIANG** [comment]
可以了，时间要比YOLOX要少了。时间是改之前的一半了,这里就是把swish 给换成silu了 
就是我还有个问题如果把下面的hardsigmoid激活函数换成了sigmoid  这样影响大吗？
![image](https://user-images.githubusercontent.com/49071179/164202862-e88533b0-176c-4bd4-9f3d-41a97f3f7237.png)

**Comment by wangxinxin08** [comment]
@LYHTZHANGJIANG 训练精度会稍微有些影响，部署的话，速度差异不是很大，可以忽略

**Comment by LYHTZHANGJIANG** [comment]
好的，谢谢哈，主要是部署的hardsigmoid 转换不过去，硬件不支持这个算子，所以就修改了
