### ISSUE TITLE
[用户训练问题待确认]测试对比发现PPYOLOE比YOLOX低了差不多10个点。差不多2w多张图像，只检测行人

### ISSUE THREAD

**Issue by LYHTZHANGJIANG** [PaddlePaddle/PaddleDetection#5789]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by LYHTZHANGJIANG** [comment]
1、我就修改了hardsigmoid 改成sigmoid.（由于硬件原因）
2、初始化权重采用CSPResNetb_s_pretrained.pdparams和ppyoloe_crn_s_300e_coco.pdparams有没有区别呀？ 如果有采用哪个会好点？
3、还有一点 我把学习率     我是4卡batch为8，  按照我的配置应该改为0.04/(8*32)*(4*8)=0.005 ，但是发现刚开始有点跑飞的样子，就改为0.00125了。
其他的就没有改了

**Comment by lyuwenyu** [comment]
1. 这数据集上两个模型都用hardsigmoid对比过没，yoloe这个预训练参数都是在hardsigmoid下得到的 改完之后可能会有些diff
2. 有区别`CSPResNetb_s_pretrained `是backbone在imagenet上的预训练， `ppyoloe_crn_s_300e_coco `这是模型在coco上的预训练参数 ，，建议用`ppyoloe_crn_s_300e_coco`吧

**Comment by wangxinxin08** [comment]
可以说下PP-YOLOE和YOLOX分别是怎么训练的吗？
1. 使用的数据集是什么？数据集做了什么特殊的处理？
2. 使用的模型分别是什么？配置进行了怎样的修改？

**Comment by wangxinxin08** [comment]
我们对比过在COCO上的行人这一类别的指标，PP-YOLOE相比YOLOX在行人这个单一类别上的AP稍微高些，可以参考下。

**Comment by LYHTZHANGJIANG** [comment]
> 1. 这数据集上两个模型都用hardsigmoid对比过没，yoloe这个预训练参数都是在hardsigmoid下得到的 改完之后可能会有些diff
> 2. 有区别`CSPResNetb_s_pretrained `是backbone在imagenet上的预训练， `ppyoloe_crn_s_300e_coco `这是模型在coco上的预训练参数 ，，建议用`ppyoloe_crn_s_300e_coco`吧

1、替换hardsigmoid前后还没有对比精度掉了多少。
2、我用`ppyoloe_crn_s_300e_coco训练了一个版本，今天测试一下精度。
但是你们的这个权重ppyoloe_crn_s_300e_coco也是采用CSPResNetb_s_pretrained 初始化骨干训练出来的呀，我设置的epoch的个数为300,但是发现在190的时候就map就平稳了，在第20个epoch map为56，在190个epoch map69，在300个epoch map70

**Comment by LYHTZHANGJIANG** [comment]
> 可以说下PP-YOLOE和YOLOX分别是怎么训练的吗？
> 
> 1. 使用的数据集是什么？数据集做了什么特殊的处理？
> 2. 使用的模型分别是什么？配置进行了怎样的修改？

1、数据集采用的VOC07、12、还有一部分自己采集的数据集。
2、没经过特殊处理，只是我训练单个类别人，然后把所有的负样本都加进来了，你们训练和测试的时候是只有目标的样本吗？
3、YOLOX  和PPYOLOE都用的S。
4、YOLOX没修改
5、ppyoloE的配置文件如下：

====ppyoloe_crns_300e_coco.yml
_BASE_: [
  '../datasets/voc.yml',
  '../runtime.yml',
  './_base_/optimizer_300e.yml',
  './_base_/ppyoloe_crn.yml',
  './_base_/ppyoloe_reader.yml',
]

log_iter: 20
snapshot_epoch: 10
weights: output/ppyoloe_crn_s_300e_coco/model_final

#pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_s_pretrained.pdparams

#pretrain_weights: ./CSPResNetb_s_pretrained.pdparams
pretrain_weights: ./ppyoloe_crn_s_300e_coco.pdparams

find_unused_parameters: true
depth_mult: 0.33
width_mult: 0.50



TrainReader:
  batch_size: 8

LearningRate:
  base_lr: 0.00125


===optimizer_300e.yml
epoch: 300

LearningRate:
  base_lr: 0.025
  schedulers:
    - !CosineDecay
      max_epochs: 360
    - !LinearWarmup
      start_factor: 0.
      epochs: 5

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2


=====ppyoloe_reader.yml
worker_num: 4
eval_height: &eval_height 352
eval_width: &eval_width 608
eval_size: &eval_size [*eval_height, *eval_width]

TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - PadGT: {}
  batch_size: 8
  shuffle: true
  drop_last: true
  use_shared_memory: false
  collate_batch: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 2

TestReader:
  inputs_def:
    image_shape: [3, *eval_height, *eval_width]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1



总结就改了：
batchsize=8  4张卡，学习率  0.00125 

下面这些就没有影响的：
find_unused_parameters: true
use_shared_memory: false

**Comment by wangxinxin08** [comment]
1. **默认训练是不加负样本的，把allow_empty设置成false**
2. **学习率应该设置成0.005，参考ppyoloe的文档：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/README_cn.md**
3. **eval的时候把size改成长方形，多尺度训练的时候也建议改成长方形， BatchRandomResize这块也改成长方形，比如target_size: [[h1, w1], [h2, w2], [h3, w3], ...]**
4. **YOLOX默认使用640 * 640评估，你ppyoloe使用608 * 352评估，为什么这么对比呢？**

**Comment by LYHTZHANGJIANG** [comment]
1、就是我需要掺杂负样本进行训练一些场景消除误检的。
2、我当时设置成0.005在warmup阶段有点跑飞了，损失都涨了20-30了，然后我把学习率调小了就好了 就在7以下了。
3、这个我还没改。我还没仔细看数据处理这块，我以为跟YOLOX一样是对图像的尺寸的比例不变的。
4、YOLOX的我也改成同样的尺寸进行测试的，由于我最后需要测试的数据是16:9的，YOLOX和yolov5里面不是有个预测的时候都会对图像的宽高的比例不变，然后会用黑边进行填充补齐32倍数，所以我这里对输入的尺寸就直接按照608*352输入的。

**Comment by LYHTZHANGJIANG** [comment]
1、有个问题就是当我的卡、batch降低了，除了学习率是线性调整以外，那么还有epoch的个数是不是应该变多呢？  还有warmup阶段是不是也需要调整？ 其他的一些超参数应该也需要有所调整吧？
2、如果采用你的初始化骨干的权重，学习率设置为0.005就会跑飞，如果用你训练好的coco集上的权重，那么0.005就不会跑飞。
3、还有就是我能看一下你们的workerlog.0吗？下面是我的worklog.0,就是感觉的分类分类损失比回归损失大挺多的，这样是正常的吗？ 
![image](https://user-images.githubusercontent.com/49071179/164590410-2eefab68-a29d-469c-b032-d6f2b547e054.png)


4、昨天测试了一些图，就是感觉召回不是很好，还有特别是图像中目标比较多的时候。
5、有个问题就是你们有测试过加入mosaic这个图像增强吗？ 这样会不会对小目标的改善会好点呢？ 还是说 BatchRandomResize也可以达到同样的效果？

**Comment by wangxinxin08** [comment]
@LYHTZHANGJIANG 
1. epoch数目可以适当调这个，你把hardsigmoid改成sigmoid，预训练模型相当于不存在了，可以根据总的iter数目适当调整下
2. 可以加载coco预训练，学习率设置成0.005
3. **你感觉召回率不是很高，还要消除误检率？明显训练错误，加负样本可以，负样本的比例需要仔细看下，不要直接allow_empty为True**
4. 分类损失本身就比回归损失大，这是正常的
5. PP-YOLOE不是保持长宽比不变的，看配置文件keep_ratio为False，所以BatchRandomResize要修改成608和352这样的比例
6. mosaic尝试过，负向作用

**Comment by LYHTZHANGJIANG** [comment]
1、虽然把hardsigmoid换成sigmoid 但是这两者的输出值的偏差不是很大呀，我觉得在训练的过程中是可以调整过来的。
2、你的第三点，我不是因为感觉召回不高，才加负样本=====是因为要消除一些场景的误检，所以把负样本加入进去了。和YOLOX采用的同样加入负样本的数据进行训练之后。 是对比YOLOX和YOLOE两者的精度，精确率差不多，但是召回相比就是低了许多。=====。

**Comment by wangxinxin08** [comment]
> 1、虽然把hardsigmoid换成sigmoid 但是这两者的输出值的偏差不是很大呀，我觉得在训练的过程中是可以调整过来的。 2、你的第三点，我不是因为感觉召回不高，才加负样本=====是因为要消除一些场景的误检，所以把负样本加入进去了。和YOLOX采用的同样加入负样本的数据进行训练之后。 是对比YOLOX和YOLOE两者的精度，精确率差不多，但是召回相比就是低了许多。=====。

**1. 训练过程可以调整过来，所以可以调整epoch数目，增大训练时间
2. 我感觉你理解错了召回率的含义，召回率和误检率是两个基本相反的指标，加负样本是为了减少误检率。你感觉召回不高，就是因为你负样本加多了**

**Comment by LYHTZHANGJIANG** [comment]
> 
1、可能我没表达清楚，就是YOLOX和PPYOLOE训练同一批数据，测试同一批数据，PPYOLOE的召回（检出率）要低一点。
这里的对比不是说对于PPYOLOE加入负样本的前后对比。
2、那么对于一个网络而言，为什么加入了负样本之后你的召回就一定变低了呢？ 如果你的容量够，你都能够拟合呀，可能你的泛化能力会更强了呀  我不知道我的理解有没有问题？

**Comment by wangxinxin08** [comment]
> > 
> 
> 1、可能我没表达清楚，就是YOLOX和PPYOLOE训练同一批数据，测试同一批数据，PPYOLOE的召回（检出率）要低一点。 这里的对比不是说对于PPYOLOE加入负样本的前后对比。 2、那么对于一个网络而言，为什么加入了负样本之后你的召回就一定变低了呢？ 如果你的容量够，你都能够拟合呀，可能你的泛化能力会更强了呀 我不知道我的理解有没有问题？

**1. 你PP-YOLOE训练的有问题，负样本太多了，不管YOLOX怎么训练，PP-YOLOE不推荐使用这种训练方式
2. 你理解有问题，正常是期望召回率高，误检率低，但是召回率和误检率是冲突的，召回率高，误检率也会高。加负样本是为了降低误检率，导致召回率也下降。建议先理解下相关指标**

**Comment by LYHTZHANGJIANG** [comment]
1、那你说你测试的精度在COCO上面要高，你是模型训练的80类别之后，然后对比的person的精度。还是模型单独训练person这个类别。
2、我理解，你说的是指模型训练好了之后，那么那两个指标是冲突的。所以我们找一个最佳的阈值来平衡。然而你有没有试验过如果你加了新数据之后你在原数据集上面的p、r都会有可能提高呢？ 我试验过。
3、那你说你们是怎么对比的  我只是想复现一下而已。

**Comment by wangxinxin08** [comment]
**1. coco上对比过，训练80个类别，对比person精度比YOLOX高，你直接评估就可以复现
2. 这两个指标是冲突的，现在加负样本的方式肯定是不行的，你看下训练中的输入就知道了，不会同时使召回率提升，误检率下降的。另外，p是precison，不是误检率, r是recall，是召回率。
3. 建议理解下相关指标，思考下，或者直接按照我给的建议训练试试呢**

**Comment by LYHTZHANGJIANG** [comment]
1、为什么加负样本的方式不行？ 可以细说吗？

**Comment by wangxinxin08** [comment]
> 1、为什么加负样本的方式不行？ 可以细说吗？

不是说加负样本不行，是你这种方式不合理，你先确定一个上下界，负样本全加进去这个实验已经跑了，再跑一个不加负样本的对比下，大致就能确定上下界了，说了这么多，为什么不试试呢(大无语)
