### ISSUE TITLE
如何从套件中将单个模型拆解出来

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleDetection#5798]
有没有案例教程-如何从套件中将单个模型拆解出来？，像yolox,yolov5代码那样，想对某些网络做深入的研究和改进。发现套件集成的东西有点多，看的迷眼睛，单独拆解出来研究。

**Comment by nemonameless** [comment]
可以删掉benchmark/  static/  test_tipc/文件夹代码。
configs/文件夹里只保留datasets  runtime.yml 和你想要的模型，
deploy/文件夹里只保留python/ 和 cpp/，
对照你想要的模型的config，一个个组件代码全局搜索去 ppdet/文件夹里按你自己需求拆解。

**Comment by wstchhwp** [comment]
注册器那些怎么去掉呢

**Comment by wykkyle** [comment]
组件都在这个文件夹里：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/ppdet/modeling。子文件夹architectures是整体网络。文件夹body，neck，head是次级组建，比如resnet，fpn，探测器等等都在这里面。其它文件夹是组件的组件。文件考出来把import语句相应改了就能跑的。改一改，跑一跑，print一下，第一个模型2个月能吃透吧。

注册器就是提供了默认参数。在create函数的最后一行前面，加print语句，把cls_kwargs打印出来，他用什么参数你也用什么参数，把类构造出来就可以了，能跑的。

**Comment by wstchhwp** [comment]
谢谢
