### ISSUE TITLE
[Other General Issues]aistudio上单张图片检测耗费十几秒时间

### ISSUE THREAD

**Issue by cutexiaokele** [PaddlePaddle/PaddleDetection#5799]
在百度的aistudio上运行官方提供的
![image](https://user-images.githubusercontent.com/60963646/164579410-9104bbb5-f95e-492d-a839-50991c673d41.png)

但图片检测耗费十几秒
![f9d2e5412ffca2c9b76943c6a181b81](https://user-images.githubusercontent.com/60963646/164579449-1fc57648-c800-4759-9ada-7828a9196ad9.png)

我想问一下，我本地开发也有这个问题，运行预测的代码，会加载很慢，耗费好久  这部分时间如何减少

![image](https://user-images.githubusercontent.com/60963646/164579536-62fa62ea-e547-4d32-87a3-d000e1a975dd.png)

**Comment by nemonameless** [comment]
检查下是否运行时GPU没有使用上，以及环境和版本已经报问题了不匹配，虽然能跑但也有可能会导致慢
