### ISSUE TITLE
代码中的一些问题 .pymodule

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#580]
paddleDetection中的代码问题。举个例子，config是yml文件中读到的LearningRate或者OptimizerBuilder，经过这句代码后cls = getattr(config.pymodule, name)，cls变成了某个类，类似于
<class 'ppdet.optimizer.LearningRate'> 或者<class 'ppdet.optimizer.OptimizerBuilder'>。我的问题是.pymodule这句话为什么就定位到某个py文件了？

LearningRate:
  base_lr: 0.000125 #0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 440000 #55000 #
    - 496000 #62000
  - !LinearWarmup  #学习率热身
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

**Comment by willthefrog** [comment]
ppdet里的模块注册是会解析并记录相关信息，参考[这里](https://github.com/paddlepaddle/PaddleDetection/blob/master/ppdet/core/config/schema.py#L229)

**Comment by JensenHJS** [comment]
你好，你给的参考链接是在一个extract_schem()函数里。然后我发现这个函数是在解析命令行之前就自动调用了，比如下面这个解析命令行参数。下面是代码开始执行的地方，我的问题是extract_schem（）是怎么被调用的？我在程序流程中看不出来它为什么在ArgsParser（）之前就被调用了
if __name__ == '__main__':
    parser = ArgsParser()

我使用以下命令行开始训练
python tools/train.py -c configs/yolov3_mobilenet_v1_voc.yml -r output/yolov3_mobilenet_v1_voc/956000

**Comment by willthefrog** [comment]
ppdet模块需要通过[register](https://github.com/PaddlePaddle/PaddleDetection/blob/master/ppdet/core/workspace.py#L165) decorator注册，导入时会自动解析。
