### ISSUE TITLE
关于PaddleDection量化文件yml的设置[Other General Issues]

### ISSUE THREAD

**Issue by wangplin** [PaddlePaddle/PaddleDetection#5801]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.

## 描述问题/Describe the bug

我修改了yml里面config的相关配置，我想问的是假如我是自定义量化节点和权重处理方式，不使用官方默认的QAT量化。我是可以直接在yml文件里修改，加上我自定义的量化方式，还是需要重新编写，不使用官方文档给的benchmark。
## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```
python tools/train.py -c configs/ssd/ssd_mobilenet_v1_300_120e_voc.yml --slim_config configs/slim/quant/ssd_mobilenet_v1_qat.yml
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

我修改了yml里面config的相关配置，我想问的是假如我是自定义量化节点和权重处理方式，不使用官方默认的QAT量化。我是可以直接在yml文件里修改，加上我自定义的量化方式，还是需要重新编写，不使用上述的命令方式。
```
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/dygraph/ssd_mobilenet_v1_300_120e_voc.pdparams
slim: QAT

QAT:
  quant_config: {
    'weight_quantize_type': 'channel_wise_abs_max', 'activation_quantize_type': 'moving_average_abs_max',
    'weight_bits': 8, 'activation_bits': 8, 'dtype': 'int8', 'window_size': 10000, 'moving_rate': 0.9,
    'quantizable_layer_type': ['Conv2D', 'Linear', 'Conv2DTranspose']}

  print_model: True
```

**Comment by yghstill** [comment]
- 默认是所有conv、fc进行量化，如果自定义量化节点的话，想跳过某一层，可以conv.skip_quant=True。
- 关于自定义权重处理方式那需要重新改写代码了，可以看下PaddleSlim中的实现。

**Comment by crz-dg** [comment]
> * 默认是所有conv、fc进行量化，如果自定义量化节点的话，想跳过某一层，可以conv.skip_quant=True。
> * 关于自定义权重处理方式那需要重新改写代码了，可以看下PaddleSlim中的实现。

请问如果是自定义量化权重处理方式，是修改slimQAT中对应调用的quanter.py函数吗？
