### ISSUE TITLE
instance segmentation to onnx/tensorRT

### ISSUE THREAD

**Issue by Kenneth-X** [PaddlePaddle/PaddleDetection#5806]
Paddle有能支持导出onnx的instance segmentation 模型嘛？
最好不加自定义op，方便我用
/usr/src/tensorrt/bin/trtexec \
  --minShapes=input:1x3x1080x1920 \
  --optShapes=input:1x3x1080x1920 \
  --maxShapes=input:1x3x1080x1920 \
  --workspace=48000 \
  --onnx=xxxx.onnx  \
  --saveEngine=model.plan
  导出为tensorrt上线部署

**Comment by nemonameless** [comment]
mask rcnn和solov2 都有提供
