### ISSUE TITLE
[Other General Issues]nms输出index越界问题

### ISSUE THREAD

**Issue by will-wiki** [PaddlePaddle/PaddleDetection#5810]
## 描述问题/Describe the bug
想通过faster rcnn模型抽取实体检测前一层的roi feature，根据代码改了下nms的参数，返回挑选的index下标，但是发现下标的值很大。

[具体代码位置](https://github.com/PaddlePaddle/PaddleDetection/blob/e9f8dfb57bdcbeb73b57b66041f7a34b9fc91c4a/ppdet/modeling/architectures/faster_rcnn.py#L81)

```
rois, rois_num, _ = self.rpn_head(body_feats, self.inputs) 
preds, _ = self.bbox_head(body_feats, rois, rois_num, None) 
                                                                        
im_shape = self.inputs['im_shape']
scale_factor = self.inputs['scale_factor']

self.bbox_post_process.nms.return_index = True #唯一改动的地方，手动将nms参数打开
self.bbox_post_process.nms.score_threshold = 0 #设置为0主要是为了保证每张图都返回前100个box框

if self.bbox_post_process.nms.return_index:  
     bbox, bbox_num, index = self.bbox_post_process(preds, (rois, rois_num), im_shape, scale_factor) 
```

self.bbox_post_process函数中的self.nms调用信息如下
attrs参数
![image](https://user-images.githubusercontent.com/22003927/164723704-56f91795-aaa4-40e1-9d0e-8c7ac195e4b1.png)
scores参数大小为[1000,80]
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/22003927/164723806-56a8fc88-44fe-4db5-a547-657c19978fc9.png">
返回得到的index结果
![image](https://user-images.githubusercontent.com/22003927/164723855-206965ce-4b18-4bd1-bbb6-15eb53eea2c1.png)

**Comment by will-wiki** [comment]
hello，有人能帮助我一下吗

**Comment by wangxinxin08** [comment]
@will-wiki 一般情况下你一般不需要使用index，index的值是行对于输入到multiclass_nms中的bboxes，不只是nms_top_k，另外这个index是整个batch的index，不是单一图片的index

**Comment by will-wiki** [comment]
@wangxinxin08 是的，如果正常做实体检测是不需要用到index，但是我跑这个项目主要是为了把实体检测最后分类前的实体特征抽取出来，作为图像的特征表征用于其他任务的，所以我需要得到相应的index下标表示。有两个问题想问下吧
第一个问题：
想求证下抽取特征位置是否正确，希望抽取到的是实体分类前的最后一层特征，对应代码是
‘preds, _ = self.bbox_head(body_feats, rois, rois_num, None)’ 只要保留self.bbox_head函数里面的bbox_feat向量中，最终得到的实体预测下标位置的向量就可以了吧。
第二个问题：
看了下nms的官方例子，输入box[80,4]，score是[80],经过这个nms得到的index应该是[0,80]之内的
我这边输入的box[1000, 80, 4]，score是[1000, 80]，这个其实不是batch的输入是一张图的输入，1000是一张图输入后fpn+rpn二分类的输出有1000个候选框（固定的），所以我理解 nms对于这样的输入是先摊平在根据分数交集去过滤得到最终的结果，所以index是在[0, 80*1000]之内，我如果要得到对应的原始特征下标应该 index//80就可以了吧？
第三个问题：
不同的faster rcnn对于预测结果的nms处理不同，paddle这个版本的是对于输出统一放到nms里面进行过滤；我之前用的版本处理，比如说是[1000, 80]80表示分类的类别，对于每个类别分别进行nms过滤，然后再合并，这两个方式得到的结果会有很大差异么。

**Comment by wangxinxin08** [comment]
@will-wiki 
1. `‘preds, _ = self.bbox_head(body_feats, rois, rois_num, None)` 这里是不要index的
2. [1000, 80, 4]这个1000怎么来的，一般是不可能只有1000的
3. paddle里面的算子本身就是对每个类别分别nms

**Comment by will-wiki** [comment]
@wangxinxin08 
1.不是这个意思哈，我是打算抽取实体检测最后分类前的实体特征向量，所以需要获得两部分的值。
第一部分是实体检测最后分类前的所有实体特征，[对应代码位置]https://github.com/PaddlePaddle/PaddleDetection/blob/2702ef0f99758329f3d42c10fcf46b3bd84da5b4/ppdet/modeling/heads/bbox_head.py#L242
第二部分是实体检测分类结果经过nms过滤后的box下标，[对应代码位置]
https://github.com/PaddlePaddle/PaddleDetection/blob/23e9f24926f697299319d7319a00ce84cd89a023/ppdet/modeling/architectures/faster_rcnn.py#L86
需要第二部分的这个函数返回nms过滤后的下标，然后根据这个下标提取第一部分中的特征，不知道这样有没有表达出我的意思。
2.因为faster rcnn是两阶段的，第一阶段是采用rpn网络进行二分类+nms过滤，你们代码里面设定了测试阶段从所有fpn特征金字塔抽取的候选roi个数，这个是代码的具体位置和参数，这个1000是第一阶段rpn网络保留下来的候选，再去做head部分的预测的。
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/22003927/164959095-38d7b36d-5d2c-45ee-8b5d-6ad4e661fb1e.png">

**Comment by wangxinxin08** [comment]
@will-wiki 
1.index / 80试试，另外，返回的100个index，并不都是有效的，有效的数据可以看multiclass_nms的输出rois_num

**Comment by will-wiki** [comment]
@wangxinxin08 您指的rois_num是这里么
https://github.com/PaddlePaddle/PaddleDetection/blob/23e9f24926f697299319d7319a00ce84cd89a023/ppdet/modeling/ops.py#L1025
这个好像是一个标量，用于表示返回的nms过滤后的box个数吧，也就是首先对输入multiclass_nms的所有box按照score和box大小进行过滤，然后返回前nms_rois_num个最好box吧

**Comment by wangxinxin08** [comment]
@will-wiki 是的，因该是一个list，表示每一张图片最终检测到的bbox数目
