### ISSUE TITLE
ppyoloe导出后nms的疑问[Other General Issues]

### ISSUE THREAD

**Issue by hobeter** [PaddlePaddle/PaddleDetection#5811]
感觉导出的模型把所有bbox都保留了。
<img width="263" alt="截屏2022-04-23 10 13 36" src="https://user-images.githubusercontent.com/55823642/164865481-d416f382-a870-4450-8cee-994dbc7e931b.png">
是因为导出的模型不带nms吗？
但我看ppyoloe结构中head里是有nms的(我没有调整nms参数)
https://github.com/PaddlePaddle/PaddleDetection/blob/bbb72659f27572c347e370bb31b89f5d882404da/configs/ppyoloe/_base_/ppyoloe_crn.yml#L40
请问该怎么解决啊👀？

**Comment by ghostxsl** [comment]
你导出的命令是什么？

**Comment by hobeter** [comment]
`python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml -o weights=best_model.pdparams TestReader.fuse_normalize=true`



> 你导出的命令是什么？

**Comment by ghostxsl** [comment]
你检查一下输出的bbox的数量是不是100
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/_base_/ppyoloe_crn.yml#L43
这里有限定最多保留100个bbox，可以修改一下参数，也有可能模型没有收敛很好，可以排查一下

**Comment by hobeter** [comment]
> 你检查一下输出的bbox的数量是不是100
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/_base_/ppyoloe_crn.yml#L43
> 这里有限定最多保留100个bbox，可以修改一下参数，也有可能模型没有收敛很好，可以排查一下

好的，感谢
