### ISSUE TITLE
PP-Picodet增强版疑问

### ISSUE THREAD

**Issue by Dekadenc** [PaddlePaddle/PaddleDetection#5812]
问题1：请问下图红色框中的为普通版picodet的配置文件，而黄色框的为增强版里的配置文件吗？
![852f50aebc8391e2c5e3fb8de5501ca](https://user-images.githubusercontent.com/102035987/164886015-358e9719-68df-43b0-8e80-b48b8e16b76a.png)
问题2：pretrain_weights和weights有什么区别，执行训练时权重文件找的是该配置文件里的还是picodet_v2.yml中的，是否为终端配置文件>yml>picodet_v2的顺序
![ea401e1b4a2aaa65643b7c89d19da39](https://user-images.githubusercontent.com/102035987/164886144-86f21f21-0b61-4558-9b0d-3c74742d84b6.png)
![c3b481f6ceaa95a867c97238f1ae22a](https://user-images.githubusercontent.com/102035987/164886253-da46fb93-45bd-452b-87b1-078f94524589.png)
wen't
问题3：预训练权重不同型号是否都不一样，预训练权重起的作用是什么？
问题4：多GPU训练时的语句需要加export吗？
![b5703efee162c6de8d3dd49b1f5c08e](https://user-images.githubusercontent.com/102035987/164886374-8dacc519-45fb-4890-875e-b0c2bb71e08e.png)
zhe这两句是一起执行还是分开执行
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python tools/train.py -c configs/picodet/picodet_s_320_coco_lcnet.yml -o pretrain_weights=https://paddledet.bj.bcebos.com/models/picodet_s_320_coco.pdparams num_classes=1 LearningRate.base_lr=0.1 --eval  我这样可以训练，但是官方的就不行
问题5：多卡训练时的学习率改怎么调整比较合适

恳请大佬不吝指教，小白一枚，非常感谢！

**Comment by yghstill** [comment]
@Dekadenc 
问题1：是的
问题2：pretrain_weights是指训练时的预训练模型，weights是指评估或导出模型时指定的训好的模型权重，一般如果是在下游任务上训练，建议pretrain_weights加载coco上训好的weight作为pretrain_weights。配置文件优先级确实是：终端配置文件>主yml文件>picodet_v2
问题3：不同尺度的模型预训练模型都不一样，预训练权重的作用是加快模型收敛
问题4：多卡训练时需要指定CUDA_VISIBLE_DEVICES的环境变量，一起执行和分开执行的作用是一样的。
问题5：你上方截图文档中也说了，PicoDet的模型都是4卡GPU训练的，如果变动卡数，按照线性调整学习率就行，比如8卡的话，学习率翻倍，2卡的话学习率减半。

**Comment by Dekadenc** [comment]
> @Dekadenc 问题1： 是指训练时的预训练模型2：pretrain_weights是指训练时的预训练模型，权重是指训练时评估的或者是训练时的好模型配置文件优先级确定是：终端问题配置文件>主yml文件>picet_v23 ：不同尺寸模型的预训练模型，预训练权重的作用是模型模型收敛问题4_ 多卡训练时指定CUDA_DEVICES的环境变量训练，同时执行和单独执行文档中的作用是一样的。 问题5：你的VIS截图也需要，PicoDet的模型都是4卡GPU的，如果变化卡数，按照线性调整学习率就行，比如8卡的话，学习率翻倍，2卡的话学习率减半。

**Comment by Dekadenc** [comment]
不同型号的预训练权重在哪可以看到，有没有专门的网址查看
