### ISSUE TITLE
[C++  多线程predictor] 代码中的threadpool predictor是否有其他推荐的多线程inference的办法

### ISSUE THREAD

**Issue by timoxue** [PaddlePaddle/PaddleDetection#5813]
我正在尝试多线程跑predictor
看到c++里有相关代码：
class PD_INFER_DECL PredictorPool {
 public:
  PredictorPool() = delete;
  PredictorPool(const PredictorPool&) = delete;
  PredictorPool& operator=(const PredictorPool&) = delete;

  /// \brief Construct the predictor pool with \param size predictor instances.
  explicit PredictorPool(const Config& config, size_t size = 1);

  /// \brief Get \param id-th predictor.
  Predictor* Retrive(size_t idx);

 private:
  std::shared_ptr<Predictor> main_pred_;
  std::vector<std::unique_ptr<Predictor>> preds_;
};

请问下这个ThreadPool的实现是deprecated了么，如果想实现多线程跑predictor run C++推荐怎么实现呢？

**Comment by zhiboniu** [comment]
你好，predictor本身的配置里就包含了线程设置。
另外，如果有实用多个predictor需求的话可以参考PredictorPool文档https://www.paddlepaddle.org.cn/inference/master/inference/api_reference/cxx_api_doc/PredictorPool.html

**Comment by timoxue** [comment]
> 你好，predictor本身的配置里就包含了线程设置。 另外，如果有实用多个predictor需求的话可以参考PredictorPool文档https://www.paddlepaddle.org.cn/inference/master/inference/api_reference/cxx_api_doc/PredictorPool.html

非常感谢！ 但是链接失效了，麻烦提供个有效的参考链接吗。

**Comment by timoxue** [comment]
checked: https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/docs/api_reference/python_api_doc/PredictorPool.md
