### ISSUE TITLE
[BUG]使用PicoDet-S量化之后的模型精度很低

### ISSUE THREAD

**Issue by yumlll** [PaddlePaddle/PaddleDetection#5818]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## 描述问题/Describe the bug
使用PaddleInference 加载 PicoDet-S  416*416尺寸 量化训练之后的模型精度很差。

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
通过使用https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/picodet/  页面的 PicoDet-S  416*416尺寸量化训练之后的模型 https://paddledet.bj.bcebos.com/deploy/Inference/picodet_s_416_coco_lcnet_quant_non_postprocess.tar 对结果进行复现， 复现使用 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/python 代码，对coco2019验证集进行预测，测试精度很差。

python deploy/python/infer.py --model_dir=./output_inference/picodet_s_416_coco_lcnet_non_postprocess --image_file=./demo/000000014439.jpg 

3. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
没有进行更改
4. 您使用的数据集是？/What dataset did you use?
coco2019验证集
5. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
无报错，精度很差

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
PaddleDetection 2.4   
3. 请提供您使用的操作系统信息：
    Windows
4. 请问您使用的Python版本是？
    3.6
6. 请问您使用的CUDA/cuDNN的版本号是？
    cpu

**Comment by yghstill** [comment]
@yumlll 量化模型需要使用trt_int8模式预测，或者直接在paddle lite的demo中测试。文档中我们再添加下测试环境要求，感谢反馈。

**Comment by yumlll** [comment]
是否意味着 量化模型只能在PC GPU 上运行，而不能在CPU上运行呢？

将量化之后的Paddle模型转为onnx， 进行预测也会有较大精度损失， 需要怎么操作才能保持精度呢？

**Comment by yghstill** [comment]
@yumlll 可以在CPU上部署哈，可以参考文档：https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/docs/optimize/paddle_x86_cpu_int8.md
