### ISSUE TITLE
[Other General Issues] S2ANET 推理生成检测框问题

### ISSUE THREAD

**Issue by uuyymilkyl** [PaddlePaddle/PaddleDetection#5819]
## 描述问题/Describe the bug
使用S2Anet训练后，导出模型，用infer.py 推理，得出的预测框都把中心点当做左上角开始框的，有没有办法输出cx cy w h angle信息让我判断到底是哪里出了问题， 有没有建议的解决方法
（并不是只有一种情况不准，而是所有类都出现了这个问题）

问题图片链接：https://i.postimg.cc/hGkJff1t/5752659c4f07f0caf084a64046e481a.png
https://i.postimg.cc/jd3SDDsY/20220424161809.png

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
模型导出
python tools/export_model.py -c configs/dota/s2anet_1x_spine.yml -o weights=output/s2anet_1x_spine/model_final.pdparams
模型预测

3. 您使用的数据集是？/What dataset did you use?  自己制作的VOC----->COCO数据集

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号：

Paddledetection2.3

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

win10

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.  

python 3.7

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used. 

 CUDA10.2

**Comment by LeeLear** [comment]
我也一样，看了几周也没找到原因
