### ISSUE TITLE
用swin transformer作ppyoloe的backbone的疑问

### ISSUE THREAD

**Issue by hobeter** [PaddlePaddle/PaddleDetection#5824]
如果想要用swin transformer作ppyoloe的backbone，请问只需要仿照

https://github.com/PaddlePaddle/PaddleDetection/blob/b615336fe3a9ff740fdb1b889be7bc865b6d20fa/configs/faster_rcnn/_base_/faster_rcnn_swin_tiny_fpn.yml#L3-L20

修改ppyoloe配置文件中backbone内容↓即可吗？🧐

https://github.com/PaddlePaddle/PaddleDetection/blob/23e9f24926f697299319d7319a00ce84cd89a023/configs/ppyoloe/_base_/ppyoloe_crn.yml#L6-L17

另外请问除了这个规格↓

https://github.com/PaddlePaddle/PaddleDetection/blob/b615336fe3a9ff740fdb1b889be7bc865b6d20fa/configs/faster_rcnn/_base_/faster_rcnn_swin_tiny_fpn.yml#L10-L19

目前有其他规格的预训练过的swin transformer吗？😁

谢谢🙏

**Comment by lyuwenyu** [comment]
是的 直接从faster那个config里的backbone   copy过去就行，， 规格的话还有只有 tiny和large

**Comment by hobeter** [comment]
好的，感谢🙏
