### ISSUE TITLE
[BUG]mask训练中的潜在bug。

### ISSUE THREAD

**Issue by wykkyle** [PaddlePaddle/PaddleDetection#5829]
![image](https://user-images.githubusercontent.com/20754685/165071029-262f729f-ea4c-48be-9d21-913c4d28c61b.png)

阅读代码学习的时候发现一个代码上的bug，位于训练mask探测器的部分，如上截图。
来自文件https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/modeling/proposal_generator/target.py
中的generate_mask_target函数。

观察红框和蓝框圈出来的变量。fg_rois和bboxes是一个变量，只是储存位置分别在gpu/cpu上；fg_inds和fg_inds_new是一个变量，只是分别储存在gpu/cpu上。

fg_inds是一个索引序列，来自于前面的paddle.nonzero。
简单假设fg_inds长度为2，取[[0],[3]]。
那么fg_rois由paddle.gather得到，长度应该为2。
在接下来的循环中，对bboxes（即fg_rois)索引3时，会发生数组越界。

目前实际测试没有报错的原因是，猜测是fg_inds恰为平凡序列，如[0,1,2,3,4,5,6]。（如果从cascade_rcnn.py模型下调用，此处fg_inds一定是平凡序列）。

**Comment by jerrywgz** [comment]
感谢反馈，我这边循环条件修改成range(fg_inds_new.shape[0])训练验证下
