### ISSUE TITLE
关于#4264 中ema修改的疑问

### ISSUE THREAD

**Issue by hobeter** [PaddlePaddle/PaddleDetection#5830]
由 _@wangxinxin08 in https://github.com/PaddlePaddle/PaddleDetection/issues/4264#issuecomment-942895079_ 提到

> 报错原因是由于relative_position_index这个参数在model.state_dict中，这种参数是int类型的，在ema的更新过程中会变成float类型，导致模型无法加载权重。由于这类参数在ema的过程中是不需要更新的，可以先在ema中进行修改，之后我们会修复完善这个问题。
> 修复方法是：
> 在https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/optimizer.py#L296 以及https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/optimizer.py#L306 之后添加以下代码：
> ``` python
> if 'relative_position_index' in k:
>   continue
> ```

但是在https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/optimizer.py#L296 和 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/optimizer.py#L306 中，均不位于循环内。我修改后也会报错 `'continue' not properly in loop`  。可能是由于代码更新了？请问这段代码应当添加在那里啊🫥

另外，想确认一下这里(https://github.com/PaddlePaddle/PaddleDetection/issues/4264#issuecomment-944062856 )↓修改的位置应该是正确的吧🧐？ 

> 补充一点，还需要将https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/optimizer.py#L259 修改为
> ```
> self.state_dict[k] = paddle.zeros_like(v) if 'relative_position_index' not in k else v
> ```
> 
>

**Comment by wangxinxin08** [comment]
这个位置https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/optimizer.py#L379 修改为
``` python
self.state_dict[k] = paddle.zeros_like(v) if 'relative_position_index' not in k else v
```
在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/optimizer.py#L416 和 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/optimizer.py#L426 之后加入以下代码
``` python
if 'relative_position_index' in k:
    continue
```

**Comment by hobeter** [comment]
好的，感谢

**Comment by hobeter** [comment]
成功运行😀

**Comment by mingheyuemankong** [comment]
我按照下面这两个链接添加代码，均报错误，应该是代码进行了更新，方便重新更新一下问题解决办法吗？？？
在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/optimizer.py#L416 和 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/optimizer.py#L426 之后加入以下代码

**Comment by hobeter** [comment]
> 我按照下面这两个链接添加代码，均报错误，应该是代码进行了更新，方便重新更新一下问题解决办法吗？？？
> 在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/optimizer.py#L416 和 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/optimizer.py#L426 之后加入以下代码

@mingheyuemankong 

似乎应该是这里
<img width="595" alt="截屏2022-06-07 10 24 14" src="https://user-images.githubusercontent.com/55823642/172282910-1aec4734-7859-44b8-9309-5ffbfd3d6ef1.png">
改成

```
self.state_dict[k] = paddle.zeros_like(v) if 'relative_position_index' not in k else v
```

然后这两处
<img width="568" alt="截屏2022-06-07 10 25 15" src="https://user-images.githubusercontent.com/55823642/172283010-df708d2f-4e16-47f4-87f9-7237e8f04cc4.png">
后面添加
```
if 'relative_position_index' in k:
    continue
```

**Comment by mingheyuemankong** [comment]
好的感谢您的回复，问题已经解决。
