### ISSUE TITLE
[Other General Issues]PaddleDetection默认配置训练出来的ssd_mobilenet_v1模型如何使用敏感度分析？

### ISSUE THREAD

**Issue by zhigfu** [PaddlePaddle/PaddleDetection#5832]
目的：使用敏感度分析的教程进行敏感度分析，进一步进行剪枝。
版本：paddle paddle2.2.2    paddledetection2.1.0     paddleslim2.1.1
问题：2.1.0版本的paddledetection的sensitive.py在static/slim/sensitive中，我按照教程去敏感度分析时报错无法读取动态图的yml文件，只能读取static下的configs。如果我使用动态剪裁，目前默认的slim/prune中还没有ssd的配置文件，如果我自己写配置文件则无法确定应该剪哪些部分，每一个部分剪多少。
        恳请解答指导。

**Comment by always-wo** [comment]
同求
