### ISSUE TITLE
[yolov4 训练时是否根据gpu使用个数，和batchsize 相应调整学习率]

### ISSUE THREAD

**Issue by jiaerwang0328** [PaddlePaddle/PaddleDetection#5838]
yolov4 训练时是否需要根据gpu使用个数，和batchsize 相应调整学习率

**Comment by heavengate** [comment]
需要的，调整方法见 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/docs/tutorials/FAQ/FAQ第零期.md#faq第零期
