### ISSUE TITLE
视频怎么进行目标识别？

### ISSUE THREAD

**Issue by lhy823436493** [PaddlePaddle/PaddleDetection#584]
已经训练好了模型，可以正常训练图片，怎么修改infer.py达到训练视频的效果？

**Comment by FDInSky** [comment]
你意思是拿训练好的模型，预测视频嘛？

**Comment by lhy823436493** [comment]
> 你意思是拿训练好的模型，预测视频嘛？
是的，现在我看文档只能预测图片，我想要预测视频的每一帧，并且保存，应该怎么修改呢？

**Comment by FDInSky** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/python 我们有这个脚本，可以看下这里的教程

**Comment by lhy823436493** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/python 我们有这个脚本，可以看下这里的教程

好的，谢谢您！

**Comment by lhy823436493** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/python 我们有这个脚本，可以看下这里的教程

在执行的时候需要到处模型，用了0.2版本的expot_model.py，只导出了__model__和__params__，缺少一个infer_cfg.yml文件，请问怎么解决？

**Comment by qingqing01** [comment]
@lhy823436493 切换到master分支导出模型吧。 git checkout master
