### ISSUE TITLE
调用picodet_l_640_aic21mtmct_vehicle模型出错

### ISSUE THREAD

**Issue by gzsvip** [PaddlePaddle/PaddleDetection#5840]
python deploy/pptracking/python/mot_sde_infer.py  --device=CPU --model_dir=output_inference/picodet_l_640_aic21mtmct_vehicle/ --video_file=../../../Downloads/v/1.mp4 --tracker_config=deploy/pptracking/python/tracker_config.yml --reid_model_dir=output_inference/deepsort_pplcnet_vehicle

出现以下错误：
-----------  Model Configuration -----------
Model Arch: DeepSORT
Transform Order: 
--transform op: LetterBoxResize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
fps: 30, frame_count: 916
Traceback (most recent call last):
  File "deploy/pptracking/python/mot_sde_infer.py", line 755, in <module>
    main()
  File "deploy/pptracking/python/mot_sde_infer.py", line 720, in main
    detector.predict_video(FLAGS.video_file, FLAGS.camera_id)
  File "deploy/pptracking/python/mot_sde_infer.py", line 517, in predict_video
    [frame], visual=False, seq_name=seq_name)
  File "deploy/pptracking/python/mot_sde_infer.py", line 408, in predict_image
    det_result = self.postprocess(inputs, result)
  File "deploy/pptracking/python/mot_sde_infer.py", line 190, in postprocess
    if np_boxes_num[0] <= 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

同样环境及入参，调用ppyolov2_r50vd_dcn_365e_aic21mtmct_vehicle是正常的：
python deploy/pptracking/python/mot_sde_infer.py  --device=GPU --model_dir=output_inference/ppyolov2_r50vd_dcn_365e_aic21mtmct_vehicle/ --video_file=../v/3.mp4 --tracker_config=deploy/pptracking/python/tracker_config.yml --reid_model_dir=output_inference/deepsort_pplcnet_vehicle/ --threshold=0.5  --save_mot_txts --save_images 

xavier nx平台，4-25 git clone下来的最新版

**Comment by nemonameless** [comment]
已复现，是因为picodet后处理输出和通用检测器不同，pptracking中暂时不支持，会尽快修复。
