### ISSUE TITLE
PicoDet和PP-YOLOE的网络问题

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#5844]
## 描述问题/Describe the bug
1  picodet和ppyoloe关于检测头head有没有类似于下图（YOLOX）这样的图解？如何与前面的csp-neck或者lc-neck连接？
![image](https://user-images.githubusercontent.com/78945582/165477244-6dfa23a4-0cb5-4834-9306-701edf6e7bb1.png)
2  在picodet的backbone中，96 192 384从哪里来的？对应代码在哪里？
![image](https://user-images.githubusercontent.com/78945582/165477566-64dc44a5-c34e-4d3c-9704-a0b87613fb7c.png)

**Comment by heavengate** [comment]
1. https://arxiv.org/pdf/2203.16250.pdf  paper里有head部分的图解，三个head是独立的，Neck部分有三个输出，分别连接三个head
2. backbone是ESNet，ESNet各层的channels是在这里计算，picodet取的三层的channels数分别是96 192 384
