### ISSUE TITLE
ppedt利用ppslim进行剪枝量化

### ISSUE THREAD

**Issue by always-wo** [PaddlePaddle/PaddleDetection#5846]
我在使用ppdet2.1建立ssd_mobilenetv1模型时，想要对生成的模型进行剪枝以及8比特量化，好像是没有动态图版本的，有静态图版本的，请问是如何使用，并且对模型的卷积的敏感度分析好像也不太行。求大神指教

**Comment by heavengate** [comment]
量化可以使用这个配置文件  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/slim/quant/ssd_mobilenet_v1_qat.yml
剪裁没有单独提供配置文件，可以参考yolov3, picodet这些配置文件修改
