### ISSUE TITLE
请问如何对ppdet生成的pdmodel模型进行卷积敏感度分析

### ISSUE THREAD

**Issue by always-wo** [PaddlePaddle/PaddleDetection#5848]
我对ssd_mobilenet_v1模型进行训练，现在想要进行剪枝，但是卷积层的敏感度不清楚。所以求教大家（ppdet 2.1 ppslim 2.1）

**Comment by jerrywgz** [comment]
可以参考paddleslim的相关文档https://github.com/PaddlePaddle/PaddleSlim/blob/release/2.0.0/docs/zh_cn/tutorials/pruning/dygraph/filter_pruning.md#41-%E5%8D%B7%E7%A7%AF%E9%87%8D%E8%A6%81%E6%80%A7%E5%88%86%E6%9E%90

**Comment by always-wo** [comment]
好像和我的要求不太一样，ppdet种export_model.py产生的是pdmodel。好像是可用使用paddle.load加载，类型是program的。我是想对这个模型进行卷积敏感度分析

**Comment by qingqing01** [comment]
closed since duplicated with https://github.com/PaddlePaddle/PaddleDetection/issues/5848
