### ISSUE TITLE
怎样在C++代码中直接调用检测模型

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleDetection#5849]
怎样在C++代码中直接调用检测模型

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/cpp/README.md 可以参考下这个文档

**Comment by lgy2830** [comment]
你好，在pp-vehicle中，车辆的检测和跟踪是mot_ppyoloe_l_36e_ppvehicle这个模型，在cpp文件中，我把检测实现了，我看了CMakeLists.txt中关于追踪的部分，option(WITH_MOT       "Whether to Compile MOT detector" ON)，我把追踪打开了。然后把mot_ppyoloe_l_36e_ppvehicle这个模型输入进去，把预测视频输入进去，可是输出的结果里，跟踪的检测框一直显示在左顶角。我看了一下跟踪的输入，显示没有输入，那么这是不是说检测的结果没有传给跟踪，或者说检测没有结果。这个cpp文件里，我把车辆检测的给复现了，可是车辆检测与跟踪没有实现，不知道为什么？
