### ISSUE TITLE
在jetson nano上部署PaddleDetection

### ISSUE THREAD

**Issue by light666111** [PaddlePaddle/PaddleDetection#5850]
在jetson nano上使用paddle_inference库部署PaddleDetection时，在编译环节出现了如下问题：
`cc1plus:fatal error:CMakeFIles/main.dir/src/main.cc.d: 没有那个文件或目录`

应该如何解决？
谢谢

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/cpp/docs/Jetson_build.md 可以参考下这个文档编译呢

**Comment by deshuai666** [comment]
> 在jetson nano上使用paddle_inference库部署PaddleDetection时，在编译环节出现了如下问题： `cc1plus:fatal error:CMakeFIles/main.dir/src/main.cc.d: 没有那个文件或目录`
> 
> 应该如何解决？ 谢谢

您好，请问解决了吗？
