### ISSUE TITLE
[Other General Issues] 关于复现PP-YOLOE-s在COCO数据集上效果的batch-size设置

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleDetection#5851]
**We sincerely appreciate the assistance from PaddleDetection team~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.

## 描述问题/Describe the bug
我们在阅读PP-YOLOE-s的配置时发现，这里：https://github.com/PaddlePaddle/PaddleDetection/blob/f06c929055c6979f8b1ca2bb3e97751f18fcfb2c/configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml#L18
我们想请教一下，
1. 这里的“batch_size: 32”是设置单张GPU上batch大小为32吗？

2. 补充说明：好像这里的**32**跟PP-YOLOE论文中的描述并不是完全一致，
![8ea5f6c34257172d64f4cb88168b2b2](https://user-images.githubusercontent.com/27288110/165696281-1da64009-9b32-4ea6-bad6-b422a53f8b00.png)

期待你们的回复！
***

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by jerrywgz** [comment]
目前ppdet配置中的batch size表示的是每张卡上的bs，我们在训练过程中为了最大限度利用gpu资源，s/m/l/x选择了不同的bs

**Comment by songyuc** [comment]
> 目前ppdet配置中的batch size表示的是每张卡上的bs，我们在训练过程中为了最大限度利用gpu资源，s/m/l/x选择了不同的bs

@jerrywgz ，好的，谢谢你的解答~
