### ISSUE TITLE
如何用测试集评估模型

### ISSUE THREAD

**Issue by fan-min-97** [PaddlePaddle/PaddleDetection#5853]
PaddleDetection怎么用测试集来评估模型呢？需要将测试集的路径写在哪里呢？

**Comment by jerrywgz** [comment]
可以参考这个文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/docs/tutorials/GETTING_STARTED_cn.md#5-%E8%AF%84%E4%BC%B0
