### ISSUE TITLE
卷积敏感性分析

### ISSUE THREAD

**Issue by always-wo** [PaddlePaddle/PaddleDetection#5856]
ppdet中训练好之后，如何利用pdparams，pdmodel，等文件进行敏感度分析。
如果不行的话是应该如何做呢？

**Comment by always-wo** [comment]
剪枝率又如何确定呢

**Comment by qingqing01** [comment]
@always-wo 目前剪枝的敏感度分析只提供了静态图、YOLOv3代码分析(也就是static文件下YOLOv3)代码。 PaddleDetection中动态图还不支持。需要参考PaddleSlim代码。  

https://github.com/PaddlePaddle/PaddleSlim/blob/release/2.0.0/docs/zh_cn/tutorials/pruning/dygraph/filter_pruning.md#41-%E5%8D%B7%E7%A7%AF%E9%87%8D%E8%A6%81%E6%80%A7%E5%88%86%E6%9E%90

另外，也可以不做敏感度分析，直接做剪枝。

**Comment by liupeng0606** [comment]
> @always-wo 目前剪枝的敏感度分析只提供了静态图、YOLOv3代码分析(也就是static文件下YOLOv3)代码。 PaddleDetection中动态图还不支持。需要参考PaddleSlim代码。
> 
> https://github.com/PaddlePaddle/PaddleSlim/blob/release/2.0.0/docs/zh_cn/tutorials/pruning/dygraph/filter_pruning.md#41-%E5%8D%B7%E7%A7%AF%E9%87%8D%E8%A6%81%E6%80%A7%E5%88%86%E6%9E%90
> 
> 另外，也可以不做敏感度分析，直接做剪枝。

请问一下，用自己的数据集做敏感度分析，
'yolo_block.0.0.0.conv.weights': {0.1: 0.13382355165646295, 0.2: -0.004217178131184262, 0.3: -0.193924454941663, 0.4: 0.010026633525619883, 0.5: -0.9559243586572177, 0.6: -0.6940631263022814, 0.7: -0.6875052277611886, 0.8: -0.34521514965152666, 0.9: -0.501086814443298}


出现了负值是怎么回事？

**Comment by liupeng0606** [comment]
> > @always-wo 目前剪枝的敏感度分析只提供了静态图、YOLOv3代码分析(也就是static文件下YOLOv3)代码。 PaddleDetection中动态图还不支持。需要参考PaddleSlim代码。
> > https://github.com/PaddlePaddle/PaddleSlim/blob/release/2.0.0/docs/zh_cn/tutorials/pruning/dygraph/filter_pruning.md#41-%E5%8D%B7%E7%A7%AF%E9%87%8D%E8%A6%81%E6%80%A7%E5%88%86%E6%9E%90
> > 另外，也可以不做敏感度分析，直接做剪枝。
> 
> 请问一下，用自己的数据集做敏感度分析， 'yolo_block.0.0.0.conv.weights': {0.1: 0.13382355165646295, 0.2: -0.004217178131184262, 0.3: -0.193924454941663, 0.4: 0.010026633525619883, 0.5: -0.9559243586572177, 0.6: -0.6940631263022814, 0.7: -0.6875052277611886, 0.8: -0.34521514965152666, 0.9: -0.501086814443298}
> 
> 出现了负值是怎么回事？

这种情况算正常吗？

**Comment by Jiashuhao518** [comment]
> 

我也遇到了相同的问题 现在不太清楚如何分析敏感度

**Comment by Jiashuhao518** [comment]
> > > @always-wo 目前剪枝的敏感度分析只提供了静态图、YOLOv3代码分析(也就是static文件下YOLOv3)代码。 PaddleDetection中动态图还不支持。需要参考PaddleSlim代码。
> > > https://github.com/PaddlePaddle/PaddleSlim/blob/release/2.0.0/docs/zh_cn/tutorials/pruning/dygraph/filter_pruning.md#41-%E5%8D%B7%E7%A7%AF%E9%87%8D%E8%A6%81%E6%80%A7%E5%88%86%E6%9E%90
> > > 另外，也可以不做敏感度分析，直接做剪枝。
> > 
> > 
> > 请问一下，用自己的数据集做敏感度分析， 'yolo_block.0.0.0.conv.weights': {0.1: 0.13382355165646295, 0.2: -0.004217178131184262, 0.3: -0.193924454941663, 0.4: 0.010026633525619883, 0.5: -0.9559243586572177, 0.6: -0.6940631263022814, 0.7: -0.6875052277611886, 0.8: -0.34521514965152666, 0.9: -0.501086814443298}
> > 出现了负值是怎么回事？
> 
> 这种情况算正常吗？

我也遇到了相同的问题 现在不太清楚如何分析敏感度

**Comment by Jiashuhao518** [comment]
> @always-wo 目前剪枝的敏感度分析只提供了静态图、YOLOv3代码分析(也就是static文件下YOLOv3)代码。 PaddleDetection中动态图还不支持。需要参考PaddleSlim代码。
> 
> https://github.com/PaddlePaddle/PaddleSlim/blob/release/2.0.0/docs/zh_cn/tutorials/pruning/dygraph/filter_pruning.md#41-%E5%8D%B7%E7%A7%AF%E9%87%8D%E8%A6%81%E6%80%A7%E5%88%86%E6%9E%90
> 
> 另外，也可以不做敏感度分析，直接做剪枝。

请问如果不做敏感度分析 怎么在动态图做剪枝 因为不能print_params  不能确定需要剪切的权重
