### ISSUE TITLE
PPYOLOE训练时visualDL可视化参数添加

### ISSUE THREAD

**Issue by ForBetterDl** [PaddlePaddle/PaddleDetection#5859]
现有PPYOLOE训练时，visualDL可视化参数较少，无lr参数，map只有iou0.50:0.95,怎么添加有效的参数进去进行可视化呢？

**Comment by qingqing01** [comment]
添加其他的可视化信息，需要修改代码，具体的VisualDL的代码参考:


https://github.com/PaddlePaddle/PaddleDetection/blob/bb4fbe84252608a3bb52dc794fec10af169b5c0e/ppdet/engine/callbacks.py#L234

另外，LR在输出的log里其实会打印。
