### ISSUE TITLE
backbone中swin transformer中冻住层数的代码有问题

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleDetection#5863]
*![1651201175(1)](https://user-images.githubusercontent.com/40813430/165879011-59a22aff-9efb-499b-ba61-0f992f7a226f.png)

self.absolute_pos_embed.requires_grad = False的设置，模型层数冻住无效，改成self.absolute_pos_embed.stop_gradient = True正常运行没问题。

**Comment by qingqing01** [comment]
@wstchhwp 感谢反馈，我们会check并修复下。
