### ISSUE TITLE
YOLOE模型转onnx模型后，网络结构不一致问题

### ISSUE THREAD

**Issue by gsx1378** [PaddlePaddle/PaddleDetection#5868]
![1](https://user-images.githubusercontent.com/44281534/165916312-6e72c068-b64c-4fff-bbd5-556cd4fb3fd5.png)
![2](https://user-images.githubusercontent.com/44281534/165916325-f34ec751-47df-4412-8154-4ae2b702ade6.png)

您好，我对比YOLOE开源模型(ppyoloe_crn_s_300e_coco)导出模型(图1)与转onnx模型(图2),发现转onnx之后网络同一个地方个的网络结构不一样了，最明显的差距就是图1中只有一个Transpose层，转onnx模型之后却变成了3个，请问是否是转onnx时候出现了问题呢？

还有一点疑惑是，如果修改网络，把图1中的Transpose层删除是否对模型效果有较大影响呢？(因为一般Transpose都是0,2,3,1, 该层的Transpose死0,2,1,3，会对前端使用造成影响)。

十分期待您的回复！

**Comment by jiangjiajun** [comment]
- 关于提到的Paddle2ONNX转换过程中多出来两个transpose的原因
- - 第一个Transpose来源于原模型中的Transpose。 第二个和第三个Transpose是由SoftMax引入。 由于这个SoftMax中参数axis不是指向输入的最后一维，所以在过softmax前先transpose为最后一维，然后再transpose回来，因此你看到的多了两个transpose.
