### ISSUE TITLE
PaddleX部署找不到libpaddle_fluid.lib

### ISSUE THREAD

**Issue by kungkook** [PaddlePaddle/PaddleDetection#5869]
cuda11.2 cudnn8.2 下载官方的paddle-inference后，E:\projects\paddle_inference\paddle\lib中没有libpaddle_fluid.lib文件

```
'E:/projects/paddle_inference/paddle/lib/libpaddle_fluid.lib', needed by 'paddlex_inference/video_classifier.exe', missing and no known rule to make it	E:\projects\PaddleX\deploy\cpp\out\build\x64-Release\cpp	E:\projects\PaddleX\deploy\cpp\out\build\x64-Release\ninja	1	
```

**Comment by qingqing01** [comment]
您是Windows部署，注意正确下载推理库。另外，PaddleX的问题需要到PaddleX repo下问下。

**Comment by kungkook** [comment]
你好，我是在windows部署下下载的适配于cuda11.2的推理库，但是还是缺少文件。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月3日(星期二) 下午4:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] PaddleX部署找不到libpaddle_fluid.lib (Issue #5869)





 
您是Windows部署，注意正确下载推理库。另外，PaddleX的问题需要到PaddleX repo下问下。

**Comment by qingqing01** [comment]
@kungkook 最新的Paddle Inference的lib名字是'libpaddle_inference.lib'，不叫'libpaddle_fluid.lib':

https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows

```
|____lib
| |____paddle_inference.dll.manifest
| |____paddle_inference.lib
| |____paddle_inference.dll
| |____libpaddle_inference.lib
| |____paddle_inference.exp
```

您要么更改编译代码，要么更换预测库
