### ISSUE TITLE
BIG THANKS from a PaddleDetection user winning 1st in AI competition

### ISSUE THREAD

**Issue by sbl1996** [PaddlePaddle/PaddleDetection#587]
Using PaddleDetection, we have won 1st (￥100,000) in the [2020 Haihua AI Challange·Garbage Classification Track 2: Professional Track](https://www.biendata.com/competition/haihua_wastesorting_task2/). Our team's name is "专 业 团 队". We achieved 4st in the Public Leaderboard and finally 1st in the Final Leaderboard.

The strong OID-pretrained model is critical to our results. Certainly, the achievement also comes from your zealous support and positive response to our feature requests (AutoAugment and top-k voting-nms).

I will publicly thank your team and help to promote PaddleDetection in the award ceremony.

Finally, thanks for your open-source spirit and your great work.

**Comment by qingqing01** [comment]
Congratulations and thanks very much!

**Comment by heavengate** [comment]
Congratulations~

**Comment by dyning** [comment]
Congratulations~
