### ISSUE TITLE
AIStudio上训练保存权重时出错

### ISSUE THREAD

**Issue by ZhiXianZ** [PaddlePaddle/PaddleDetection#5870]
## 描述问题/Describe the bug

在aistudio上使用train.py时候，在保存权重的时候出现问题。之前未出现这种情况。已经更换过paddle2.1、paddle2.2和paddle2.3

```
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 175, 175] and the shape of Y = [1, 256, 176, 176]. Received [175] in X is not equal to [176] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
  [operator < elementwise_add > error]
```

## 复现/Reproduction

```
! python tools/train.py -c configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.yml --use_vdl=True --vdl_log_dir="./output"
```

修改内容: /只修改了config文件

数据: data142978、data138098

**Comment by jerrywgz** [comment]
可以发下训练使用的配置文件吗，cascade rcnn需要在预处理的时候将图片pad到32的倍数，具体可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/cascade_rcnn/_base_/cascade_fpn_reader.yml#L10 这里

**Comment by LongXuYu** [comment]
我也是在aistudio上使用train.py时候，在保存权重的时候出现问题。
python .\tools\train.py -c .\configs\rtdetr\rtdetr_hgnetv2_l_6x_coco.yml --eval --use_vdl=true 
只是换了个数据集就出错了
