### ISSUE TITLE
[Other General Issues]pptracking AssertionError: Note that tracker_config should be set.

### ISSUE THREAD

**Issue by seekme-ai** [PaddlePaddle/PaddleDetection#5872]
python deploy/pptracking/python/mot_sde_infer.py --model_dir=output_inference/ppyolov2_r50vd_dcn_365e_aic21mtmct_vehicle/ --reid_model_dir=output_inference/deepsort_pplcnet_vehicle/ --mtmct_dir=./mtmct-demo --device=GPU --mtmct_cfg=deploy/pptracking/python/mtmct_cfg.yml --scaled=True --save_mot_txts --save_images
-----------  Running Arguments -----------
batch_size: 1
camera_id: -1
cpu_threads: 1
device: GPU
do_entrance_counting: False
draw_center_traj: False
enable_mkldnn: False
image_dir: None
image_file: None
model_dir: output_inference/ppyolov2_r50vd_dcn_365e_aic21mtmct_vehicle/
mtmct_cfg: deploy/pptracking/python/mtmct_cfg.yml
mtmct_dir: ./mtmct-demo
output_dir: output
reid_batch_size: 50
reid_model_dir: output_inference/deepsort_pplcnet_vehicle/
run_benchmark: False
run_mode: paddle
save_images: True
save_mot_txt_per_img: False
save_mot_txts: True
scaled: True
secs_interval: 2
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dark: True
use_gpu: False
video_file: None
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
-----------  Model Configuration -----------
Model Arch: DeepSORT
Transform Order: 
--transform op: LetterBoxResize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
Traceback (most recent call last):
  File "/home/niu/code/paddle_det/PaddleDetection/deploy/pptracking/python/mot_sde_infer.py", line 755, in <module>
    main()
  File "/home/niu/code/paddle_det/PaddleDetection/deploy/pptracking/python/mot_sde_infer.py", line 696, in main
    detector = SDE_Detector(
  File "/home/niu/code/paddle_det/PaddleDetection/deploy/pptracking/python/mot_sde_infer.py", line 137, in __init__
    assert tracker_config is not None, 'Note that tracker_config should be set.'
AssertionError: Note that tracker_config should be set.

**Comment by seekme-ai** [comment]
add --tracker_config=./deploy/pptracking/python/tracker_config.yml

**Comment by 217TYNB** [comment]
怎么配置呢，有文件么
