### ISSUE TITLE
使用剪枝或量化后模型fps降低

### ISSUE THREAD

**Issue by always-wo** [PaddlePaddle/PaddleDetection#5874]
使用ppdet 不加任何slim_config 得到的fps是39
使用自带的量化配置训练后fps是26
使用自己写的剪枝配置训练后fps是34
请问这是什么原因？
不应该剪枝量化之后的fps会变快吗？为什么反而是越优化越慢呢？
这个问题好像挺多人都有的。

**Comment by yghstill** [comment]
@always-wo 模型预测时延请使用deploy下的脚本开启--run_benchmark=True测试速度，量化后模型需开启TensorRT int8模式
