### ISSUE TITLE
PP-YOLO_2x如何训练不同输入尺寸的模型（默认608）

### ISSUE THREAD

**Issue by HaitaoWuTJU** [PaddlePaddle/PaddleDetection#5875]
如题

**Comment by qingqing01** [comment]
训练默认的是多尺度，参考:

https://github.com/PaddlePaddle/PaddleDetection/blob/bb4fbe84252608a3bb52dc794fec10af169b5c0e/configs/ppyolo/_base_/ppyolo_reader.yml#L13

测试的时候可以导出不同的测试尺寸，参考教程

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/EXPORT_MODEL.md#4%E8%AE%BE%E7%BD%AE%E5%AF%BC%E5%87%BA%E6%A8%A1%E5%9E%8B%E7%9A%84%E8%BE%93%E5%85%A5%E5%A4%A7%E5%B0%8F
