### ISSUE TITLE
strongbaseline_r50_30e_pa100k人体属性识别使用的这个模型源码有开源吗？

### ISSUE THREAD

**Issue by liutinglong** [PaddlePaddle/PaddleDetection#5877]
strongbaseline_r50_30e_pa100k人体属性识别使用的这个模型源码有开源吗？在paddleDetection源码中并没有找到模型结构，因为想修改模型和重新训练，加入一些人体新的属性

**Comment by qingqing01** [comment]
训练源码暂且没有开源，近期会开源。

**Comment by liutinglong** [comment]
ok

**Comment by maoyutofu** [comment]
请问现在可以自己训练人脸属性模型了吗
