### ISSUE TITLE
about imagenet pretrain

### ISSUE THREAD

**Issue by cryboykevin** [PaddlePaddle/PaddleDetection#5881]
I find that ppyolo-e use imagenet pretrain.

My question is that what the acc of imagenet pretrain is and how much mAP the imagenet pretrain improves ppyolo-e.

**Comment by zoooo0820** [comment]
The accuracy of pretrained model on Imagenet is about 79.7 (cspresnet-L). And we did not test the mAP without pretrained model.

**Comment by cryboykevin** [comment]
> we
what about the acc of imagenet pretrain (ppyoloe-s)?

**Comment by wangxinxin08** [comment]
@cryboykevin the acc of cspresnet-s is about 71

**Comment by cryboykevin** [comment]
> thanks :D

**Comment by CangHaiQingYue** [comment]
> The accuracy of pretrained model on Imagenet is about 79.7 (cspresnet-L). And we did not test the mAP without pretrained model.

大佬，能提供一下cspresnet-s 在imagenet上的预训练模型吗，想复现一下指标~
邮箱是921156593@qq.com

**Comment by zoooo0820** [comment]
@CangHaiQingYue 
Please download it by  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml#L13

**Comment by CangHaiQingYue** [comment]
> @CangHaiQingYue Please download it by https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml#L13

失误了。没看到~
谢谢大佬！
