### ISSUE TITLE
使用paddle2onnx转换onnx格式问题

### ISSUE THREAD

**Issue by Shengcheng-Ma** [PaddlePaddle/PaddleDetection#5884]
## 描述问题
使用paddle2onnx_v0.9.5将PaddleDetection_v2.4版本训练产生的faster-rcnn模型住哪换成onnx格式时，报以下错误:

NotImplementedError:
There's 7 ops are not supported yet
=========== tensor_array_to_tensor ===========
=========== while ===========
=========== select_input ===========
=========== conditional_block ===========
=========== generate_proposals_v2 ===========
=========== write_to_array ===========
=========== lod_array_length ===========

报错截图
![image](https://user-images.githubusercontent.com/88013177/166885678-e682f840-8c0c-4405-af7d-ff172195d0b7.png)

**Comment by jiangjiajun** [comment]
Duplicate of https://github.com/PaddlePaddle/Paddle2ONNX/issues/699
请参考这个issue的回复 https://github.com/PaddlePaddle/Paddle2ONNX/issues/699

**Comment by Shengcheng-Ma** [comment]
您好，我参考了您提供的这条答复链接，然后paddle2onnx也使用了https://github.com/PaddlePaddle/Paddle2ONNX/pull/636代码进行了转换。

然后我执行下面这行代码生成onnx文件的时候，会报错误。
python paddle2onnx/command.py --model_dir /home/msc/Paddle2onnx/Paddle2ONNX/my_output/faster_rcnn_r50_fpn_1x_coco  --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 13 --save_file ./onnx_13/faster13.onnx

报错误如下：
Exception: Error happened when mapping node ['roi_align_0'] to onnx, which op_type is 'roi_align' with inputs: {'ROIs': ['distribute_fpn_proposals_0.tmp_0'], 'RoisNum': ['distribute_fpn_proposals_0.tmp_5'], 'X': ['conv2d_121.tmp_1']} and outputs: {'Out': ['roi_align_0.tmp_0']}, specific error: when aligned is true, onnx opset should be (onnx_opset>= 16)

但是我把--opset_version 13修改成--opset_version 16之后就不会报错，这是为什么呢？

**Comment by jiangjiajun** [comment]
由于里面使用的roialign参数，所以需要高版本opset

**Comment by wobenxiaoyaoKurt** [comment]
> 由于里面使用的roialign参数，所以需要高版本opset

您好 我在配置文件faster_rcnn_swin_tiny_fpn_3x_coco.yml中添加了export_onnx: True，可是使用paddle2onnx的时候依然会出现There's 7 ops are not supported yet的错误，不知道是哪里出错了，请教一下，非常感谢！

**Comment by jiangjiajun** [comment]
> > 由于里面使用的roialign参数，所以需要高版本opset
> 
> 您好 我在配置文件faster_rcnn_swin_tiny_fpn_3x_coco.yml中添加了export_onnx: True，可是使用paddle2onnx的时候依然会出现There's 7 ops are not supported yet的错误，不知道是哪里出错了，请教一下，非常感谢！

 转换时添加参数 --enable_dev_version=True

**Comment by wobenxiaoyaoKurt** [comment]
> > > 由于里面使用的roialign参数，所以需要高版本opset
> > 
> > 
> > 您好 我在配置文件faster_rcnn_swin_tiny_fpn_3x_coco.yml中添加了export_onnx: True，可是使用paddle2onnx的时候依然会出现There's 7 ops are not supported yet的错误，不知道是哪里出错了，请教一下，非常感谢！
> 
> 转换时添加参数 --enable_dev_version=True
还是报错
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,distribute_fpn_proposals,generate_proposals_v2,lod_array_length,pad,roll,select_input,tensor_array_to_tensor,while,write_to_array,
[ERROR] Due to the unsupported operators, the conversion is aborted.

我的命令如下
!paddle2onnx --model_dir inference_model/faster_rcnn_swin_tiny_fpn_3x_coco \
            --model_filename model.pdmodel \
            --params_filename model.pdiparams \
            --opset_version 16 \
            --enable_dev_version True\
            --enable_onnx_checker True\
            --save_file faster_rcnn.onnx

**Comment by wobenxiaoyaoKurt** [comment]
> > > 由于里面使用的roialign参数，所以需要高版本opset
> > 
> > 
> > 您好 我在配置文件faster_rcnn_swin_tiny_fpn_3x_coco.yml中添加了export_onnx: True，可是使用paddle2onnx的时候依然会出现There's 7 ops are not supported yet的错误，不知道是哪里出错了，请教一下，非常感谢！
> 
> 转换时添加参数 --enable_dev_version=True

还是报错
[Paddle2ONNX] LodTensorArray is not supported.
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,distribute_fpn_proposals,generate_proposals_v2,lod_array_length,pad,roll,select_input,tensor_array_to_tensor,while,write_to_array,
[ERROR] Due to the unsupported operators, the conversion is aborted.
我的命令如下
!paddle2onnx --model_dir inference_model/faster_rcnn_swin_tiny_fpn_3x_coco \
            --model_filename model.pdmodel \
            --params_filename model.pdiparams \
            --opset_version 16 \
            --enable_dev_version True\
            --enable_onnx_checker True\
            --save_file faster_rcnn.onnx

**Comment by jiangjiajun** [comment]
不好意思，刚打错了，应该是--enable_dev_version=False

**Comment by wobenxiaoyaoKurt** [comment]
> 不好意思，刚打错了，应该是--enable_dev_version=False

False和True都试过了，同样是以上的报错信息

**Comment by railgun-zyy** [comment]
> > > > 由于里面使用的roialign参数，所以需要高版本opset
> > > 
> > > 
> > > 您好 我在配置文件faster_rcnn_swin_tiny_fpn_3x_coco.yml中添加了export_onnx: True，可是使用paddle2onnx的时候依然会出现There's 7 ops are not supported yet的错误，不知道是哪里出错了，请教一下，非常感谢！
> > 
> > 
> > 转换时添加参数 --enable_dev_version=True
> 
> 还是报错 [Paddle2ONNX] LodTensorArray is not supported. [Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,distribute_fpn_proposals,generate_proposals_v2,lod_array_length,pad,roll,select_input,tensor_array_to_tensor,while,write_to_array, [ERROR] Due to the unsupported operators, the conversion is aborted. 我的命令如下 !paddle2onnx --model_dir inference_model/faster_rcnn_swin_tiny_fpn_3x_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 16 --enable_dev_version True --enable_onnx_checker True --save_file faster_rcnn.onnx

请问您解决了吗？我也遇到了这个问题

**Comment by Eric-Fung** [comment]
当我按照[文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/EXPORT_ONNX_MODEL.md)导出faster_rcnn_r50_fpn_1x_coco模型时出现了以下错误，部署模型的导出与文档一致，采用了云端的模型。但是在导出onnx模型时报了以下错误。请问是什么问题呢？
```
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: inference_model/faster_rcnn_r50_fpn_1x_coco/model.pdmodel
[Paddle2ONNX] Paramters file path: inference_model/faster_rcnn_r50_fpn_1x_coco/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including distribute_fpn_proposals,generate_proposals_v2,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted (core dumped)
```

**Comment by zhjian831129** [comment]
> 当我按照[文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/EXPORT_ONNX_MODEL.md)导出faster_rcnn_r50_fpn_1x_coco模型时出现了以下错误，部署模型的导出与文档一致，采用了云端的模型。但是在导出onnx模型时报了以下错误。请问是什么问题呢？
> 
> ```
> [Paddle2ONNX] Start to parse PaddlePaddle model...
> [Paddle2ONNX] Model file path: inference_model/faster_rcnn_r50_fpn_1x_coco/model.pdmodel
> [Paddle2ONNX] Paramters file path: inference_model/faster_rcnn_r50_fpn_1x_coco/model.pdiparams
> [Paddle2ONNX] Start to parsing Paddle model...
> [Paddle2ONNX] Oops, there are some operators not supported yet, including distribute_fpn_proposals,generate_proposals_v2,
> [ERROR] Due to the unsupported operators, the conversion is aborted.
> Aborted (core dumped)
> ```

我遇到和你一样的问题，请问你解决了吗？ @Eric-Fung

**Comment by Eric-Fung** [comment]
> > 当我按照[文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/EXPORT_ONNX_MODEL.md)导出faster_rcnn_r50_fpn_1x_coco模型时出现了以下错误，部署模型的导出与文档一致，采用了云端的模型。但是在导出onnx模型时报了以下错误。请问是什么问题呢？
> > ```
> > [Paddle2ONNX] Start to parse PaddlePaddle model...
> > [Paddle2ONNX] Model file path: inference_model/faster_rcnn_r50_fpn_1x_coco/model.pdmodel
> > [Paddle2ONNX] Paramters file path: inference_model/faster_rcnn_r50_fpn_1x_coco/model.pdiparams
> > [Paddle2ONNX] Start to parsing Paddle model...
> > [Paddle2ONNX] Oops, there are some operators not supported yet, including distribute_fpn_proposals,generate_proposals_v2,
> > [ERROR] Due to the unsupported operators, the conversion is aborted.
> > Aborted (core dumped)
> > ```
> 
> 我遇到和你一样的问题，请问你解决了吗？ @Eric-Fung

没有解决，后面换用[openmmdetection](https://github.com/open-mmlab/mmdetection)了

**Comment by zhjian831129** [comment]
> > > 当我按照[文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/EXPORT_ONNX_MODEL.md)导出faster_rcnn_r50_fpn_1x_coco模型时出现了以下错误，部署模型的导出与文档一致，采用了云端的模型。但是在导出onnx模型时报了以下错误。请问是什么问题呢？
> > > ```
> > > [Paddle2ONNX] Start to parse PaddlePaddle model...
> > > [Paddle2ONNX] Model file path: inference_model/faster_rcnn_r50_fpn_1x_coco/model.pdmodel
> > > [Paddle2ONNX] Paramters file path: inference_model/faster_rcnn_r50_fpn_1x_coco/model.pdiparams
> > > [Paddle2ONNX] Start to parsing Paddle model...
> > > [Paddle2ONNX] Oops, there are some operators not supported yet, including distribute_fpn_proposals,generate_proposals_v2,
> > > [ERROR] Due to the unsupported operators, the conversion is aborted.
> > > Aborted (core dumped)
> > > ```
> > 
> > 
> > 我遇到和你一样的问题，请问你解决了吗？ @Eric-Fung
> 
> 没有解决，后面换用[openmmdetection](https://github.com/open-mmlab/mmdetection)了

openmmdetection 好用吗？  也想换了， 一直解决不了

**Comment by Eric-Fung** [comment]
> > > > 当我按照[文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/EXPORT_ONNX_MODEL.md)导出faster_rcnn_r50_fpn_1x_coco模型时出现了以下错误，部署模型的导出与文档一致，采用了云端的模型。但是在导出onnx模型时报了以下错误。请问是什么问题呢？
> > > > ```
> > > > [Paddle2ONNX] Start to parse PaddlePaddle model...
> > > > [Paddle2ONNX] Model file path: inference_model/faster_rcnn_r50_fpn_1x_coco/model.pdmodel
> > > > [Paddle2ONNX] Paramters file path: inference_model/faster_rcnn_r50_fpn_1x_coco/model.pdiparams
> > > > [Paddle2ONNX] Start to parsing Paddle model...
> > > > [Paddle2ONNX] Oops, there are some operators not supported yet, including distribute_fpn_proposals,generate_proposals_v2,
> > > > [ERROR] Due to the unsupported operators, the conversion is aborted.
> > > > Aborted (core dumped)
> > > > ```
> > > 
> > > 
> > > 我遇到和你一样的问题，请问你解决了吗？ @Eric-Fung
> > 
> > 
> > 没有解决，后面换用[openmmdetection](https://github.com/open-mmlab/mmdetection)了
> 
> openmmdetection 好用吗？ 也想换了， 一直解决不了

训练导出和部署faster_rcnn都没遇到什么大的问题
