### ISSUE TITLE
执行剪枝命令出现问题

### ISSUE THREAD

**Issue by liupeng0606** [PaddlePaddle/PaddleDetection#5885]
在PaddleDetection的static目录下，执行 python slim/prune/prune.py -c ./configs/yolov3_mobilenet_v1_voc.yml --print_params

Traceback (most recent call last):
File "slim/prune/prune.py", line 61, in
raise e
File "slim/prune/prune.py", line 41, in
from ppdet.experimental import mixed_precision_context
ModuleNotFoundError: No module named 'ppdet.experimental'

请问这是什么问题？

**Comment by zoooo0820** [comment]
尝试下`pip uninstall paddledet`

**Comment by zeromasterfire** [comment]
> 尝试下`pip uninstall paddledet`

我也遇到了相同的问题，执行指令后 /home/server/anaconda3/lib/python3.9/site-packages/fontTools/misc/py23.py:11: DeprecationWarning: The py23 module has been deprecated and will be removed in a future release. Please update your code.
  warnings.warn(
/home/xt/paddle/PaddleDetection/static/ppdet/utils/voc_utils.py:67: DeprecationWarning: invalid escape sequence \.
  if re.match('trainval\.txt', fname):
/home/xt/paddle/PaddleDetection/static/ppdet/utils/voc_utils.py:69: DeprecationWarning: invalid escape sequence \.
  elif re.match('test\.txt', fname):
2022-05-06 21:39:40,049-ERROR: Config use_gpu cannot be set as true while you are using paddlepaddle cpu version !
Please try:
        1. Install paddlepaddle-gpu to run model on GPU
        2. Set use_gpu as false in config file to run model on CPU
xt@server-System-Product-Name:~/paddle/PaddleDetection/static/slim/prune$ export CUDA_VISIBLE_DEVICES=0
xt@server-System-Product-Name:~/paddle/PaddleDetection/static/slim/prune$ python prune.py \-c ../../configs/ssd/ssd_mobilenet_v1_voc.yml \--print_params
/home/server/anaconda3/lib/python3.9/site-packages/fontTools/misc/py23.py:11: DeprecationWarning: The py23 module has been deprecated and will be removed in a future release. Please update your code.
  warnings.warn(
2022-05-06 21:41:48,082-ERROR: Config use_gpu cannot be set as true while you are using paddlepaddle cpu version !
Please try:
        1. Install paddlepaddle-gpu to run model on GPU
        2. Set use_gpu as false in config file to run model on CPU

**Comment by zoooo0820** [comment]
@zeromasterfire 
使用的是cpu版本的paddle吧？
- 如果是gpu机器，可以装上paddlepaddle-gpu
- 或者在命令最后加上 `-o use_gpu=False`
- 或者直接在yml配置文件里，把`use_gpu`改成false

**Comment by zeromasterfire** [comment]
> @zeromasterfire 使用的是cpu版本的paddle吧？
> 
> * 如果是gpu机器，可以装上paddlepaddle-gpu
> * 或者在命令最后加上 `-o use_gpu=False`
> * 或者直接在yml配置文件里，把`use_gpu`改成false

您好，我也试过了，

 python prune.py \-c ../../configs/ssd/ssd_mobilenet_v1_voc.yml \--print_params -o use_gpu=false
/home/server/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "/home/xt/paddle/PaddleDetection/static/slim/prune/prune.py", line 61, in <module>
    raise e
  File "/home/xt/paddle/PaddleDetection/static/slim/prune/prune.py", line 41, in <module>
    from ppdet.experimental import mixed_precision_context
ModuleNotFoundError: No module named 'ppdet.experimental'

**Comment by zoooo0820** [comment]
@zeromasterfire 请在`PaddleDetection/static`这个路径下执行哈

**Comment by zeromasterfire** [comment]
xt@server-System-Product-Name:~/paddle/PaddleDetection/static/slim/prune$
python prune.py -c ../../configs/ssd/ssd_mobilenet_v1_voc.yml --print_params -o use_gpu=false
/home/server/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: np.object is a deprecated alias for the builtin object. To silence this warning, use object by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
if data.dtype == np.object:
Traceback (most recent call last):
File "/home/xt/paddle/PaddleDetection/static/slim/prune/prune.py", line 61, in
raise e
File "/home/xt/paddle/PaddleDetection/static/slim/prune/prune.py", line 41, in
from ppdet.experimental import mixed_precision_context
ModuleNotFoundError: No module named 'ppdet.experimental'

> @zeromasterfire 请在`PaddleDetection/static`这个路径下执行哈

确实是在其路径下面

**Comment by zoooo0820** [comment]
@zeromasterfire 
在`PaddleDetection/static`目录下执行命令，`python slim/prune/prune.py -c ./configs/yolov3_mobilenet_v1_voc.yml --print_params -o use_gpu=False` 。上面的报错是已经位于`PaddleDetection/static/slim/prune`下了

**Comment by zeromasterfire** [comment]
> python slim/prune/prune.py -c ./configs/yolov3_mobilenet_v1_voc.yml --print_params -o use_gpu=False
是一样的，还是那个问题，我是paddledetection 的最新版本，默认动态图，是不是要开启什么东西进入静态图？
 xt@server-System-Product-Name:~/paddle/PaddleDetection/static$ python slim/prune/prune.py -c ./configs/yolov3_mobilenet_v1_voc.yml --print_params -o use_gpu=False
/home/server/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "/home/xt/paddle/PaddleDetection/static/slim/prune/prune.py", line 61, in <module>
    raise e
  File "/home/xt/paddle/PaddleDetection/static/slim/prune/prune.py", line 41, in <module>
    from ppdet.experimental import mixed_precision_context
ModuleNotFoundError: No module named 'ppdet.experimental'

**Comment by liupeng0606** [comment]
在static下执行   export PYTHONPATH=`pwd`:$PYTHONPATH，我也遇到了这个问题，解决了

**Comment by liupeng0606** [comment]
谢谢大家，我的解决了，在static下执行   export PYTHONPATH=`pwd`:$PYTHONPATH

**Comment by liupeng0606** [comment]
谢谢大家，我的解决了，在static下执行 export PYTHONPATH=pwd:$PYTHONPATH
