### ISSUE TITLE
yolox的预训练模型

### ISSUE THREAD

**Issue by wzh326** [PaddlePaddle/PaddleDetection#5887]
在官方给的标准配置文件中，并没有给出yolox的预训练模型。从其他配置文件上获取预模型的网址也没办法访问。请问yolox是还没有提供相应的预训练模型嘛？个人应该怎么获取呢？

**Comment by nemonameless** [comment]
YOLOX没有用预训练，是train from scratch即从头训练的。

**Comment by wzh326** [comment]
> YOLOX没有用预训练，是train from scratch即从头训练的。

谢谢解答！感觉重头训练起来好慢呀，就想能不能有预训练模型加快一下速度

**Comment by nemonameless** [comment]
> > YOLOX没有用预训练，是train from scratch即从头训练的。
> 
> 谢谢解答！感觉重头训练起来好慢呀，就想能不能有预训练模型加快一下速度

可以试试ppyoloe，有预训练

**Comment by wzh326** [comment]
> > > YOLOX没有用预训练，是train from scratch即从头训练的。
> > 
> > 
> > 谢谢解答！感觉重头训练起来好慢呀，就想能不能有预训练模型加快一下速度
> 
> 可以试试ppyoloe，有预训练

谢谢帮助！之前用过ppyoloe，但是精度不够高。就想换其他模型试一下。但是不知道为啥，大模型的精度反而不如小模型精度高
