### ISSUE TITLE
[Document Improvement] 请问一下，在CPU上如何进行“快速体验”的测试呢？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleDetection#5890]
## 📖  文档优化/Documentation Improvement

**请简单说明文档存在问题/Please provide a concise and brief description of the documentation problem:**
[[快速体验]](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/docs/tutorials/INSTALL_cn.md#%E5%BF%AB%E9%80%9F%E4%BD%93%E9%AA%8C)没有提供CPU版本的测试指令。
**请提供有问题的文档部分截图及链接/Please provide the screen shoot and the link of the document:**
![image](https://user-images.githubusercontent.com/27288110/167074762-8ab54093-3817-45e7-90f8-a36f690d0db2.png)

**补充说明：**
请问一下，CPU测试的代码应该如何修改呢？

**Comment by qingqing01** [comment]
@songyuc  设置 `-o use_gpu=False`

**Comment by songyuc** [comment]
@qingqing01 ，好的，谢谢你的回复！
