### ISSUE TITLE
datasets下yml中，map_type的含义是什么？

### ISSUE THREAD

**Issue by bittergourd1224** [PaddlePaddle/PaddleDetection#5891]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## 描述问题/Describe the bug

**对于自定义数据集，发现yml中map_type这个变量没有清晰的解释。**

**提供的例子中

configs\datasets\roadsign_voc.yml里map_type设置的是integral
configs\datasets\voc.yml里map_type设置的是11point
分别代表什么含义？对于我自己的数据集应该填写什么？

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
Paddle为2.2.2，PaddleDetection为release/2.4

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
Windows

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
3.7

**Comment by qingqing01** [comment]
Pascal VOC数据集的mAP指标计算，包含内插11 point (内插AP)、integral (曲线下面积)两种，可以参考:

https://www.lijingle.com/article-73-1.html 

https://datascience.stackexchange.com/questions/25119/how-to-calculate-map-for-detection-task-for-the-pascal-voc-challenge

https://homepages.inf.ed.ac.uk/ckiw/postscript/ijcv_voc09.pdf

您用默认值即可。

**Comment by bittergourd1224** [comment]
好的，感谢~
