### ISSUE TITLE
导出静态图时，如何改变模型参数等的顺序，使模型预测时的计算顺序发生改变，提升速度

### ISSUE THREAD

**Issue by ZRS0326** [PaddlePaddle/PaddleDetection#5896]
目前模型部署到移动端后，可以发现模型的计算顺序是SSDHead与骨干混合计算的。也就是会在两者的计算间来回切换，影响硬件加速的性能。如何能够使它预测时的计算顺序变为：先把整个骨干网络（mobilenet）计算完成，然后再根据骨干的特定层结果计算SSDHead层。从而实现预测（加速）。目前的思路是在动态图导出静态图模型的过程解决此问题，但没有好的想法与思路（或者这个模型的计算顺序是由什么影响的）

**Comment by qingqing01** [comment]
Python组网代码中默认的顺序是：先骨干网络 -> 后Head计算，您观察下导出后的图的顺序是否为：先骨干网络 -> 后Head计算？另外，您是用PaddleLite部署的吗？

**Comment by yu-jie-cpu** [comment]
> Python组网代码中默认的顺序是：先骨干网络 -> 后Head计算，您观察下导出后的图的顺序是否为：先骨干网络 -> 后Head计算？另外，您是用PaddleLite部署的吗？

请问有没有办法通过修改模型导出静态图时的代码，使得卷积运算能够连续映射的放到CNN加速器上执行？（使用Paddle-Lite部署）
