### ISSUE TITLE
采用eval.py进行模型评估时，如何输出IOU=0.5时每个类的AP

### ISSUE THREAD

**Issue by lihui669** [PaddlePaddle/PaddleDetection#5899]
当测试时，在测试的命令行后加上 --classwise 时，显示的是IOU=0.50：0.95时每个类别的AP，如果想要显示IOU=0.5时每个类别的AP,应该修改哪些参数？

**Comment by nemonameless** [comment]
#4673
这个是由cocoapi评估代码决定的。
首先pip安装pycocotools包
代码里会有
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
ppdet里的打印调用在此：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/metrics/coco_utils.py#L112
cocoapi里的原始代码在此
https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L422
