### ISSUE TITLE
在训练时候选择了sample_transforms中的随机选择那个增强方式 结果报错

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#59]
我看控制台 每次跑起来程序的时候  这些默认配置都显示了  是默认的吗？还是只是输出个运行模板  最后的输出才是本地的配置？
运行参数和报错信息如下
![报错信息](https://user-images.githubusercontent.com/45937014/69939155-1b535300-151a-11ea-97e7-11249ca4da2c.jpg)
我的配置信息是按照例子中的sample_transform配置的：https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/docs/config_example/mask_rcnn_r50_fpn_1x.yml

**Comment by qingqing01** [comment]
@shuxsu 是默认显示的。 能否贴下您更改的数据处理配置，选择插入代码的方式， 贴下内容吧，不要截图。

**Comment by qingqing01** [comment]
@shuxsu 请问是否解决？

**Comment by shuxsu** [comment]
> @shuxsu 请问是否解决？已解决问题需要我close吗

**Comment by qingqing01** [comment]
那就可以close了，感谢反馈问题 :)
