### ISSUE TITLE
剪裁后的模型量化处理问题

### ISSUE THREAD

**Issue by ZHZhang-whu** [PaddlePaddle/PaddleDetection#5902]
您好，我在对于ssd_mobilenetv1网络进行了剪枝之后，查看了剪枝后模型的卷积通道数已经缩小，然后将这个剪枝后的模型进行了量化，量化后模型的卷积通道数又变成了剪枝前的数目（例如backbone.conv1._conv，剪枝前32×3×3×3，剪枝后23×3×3×3，量化后又变会了32×3×3×3）
1.请问这样的先剪枝后量化的操作是否会使剪枝无效？
2.官方有提供同时进行distillprune的配置，之前也有人提问quant和prune联合进行的配置如何去写，请问剪枝和量化联合飞桨是否支持，以及您对于之前那个问题的回答——“在配置文件里同时配置剪裁和量化就可以实现剪裁、量化联合策略”该如何去配置，有相关文档或者配置文件示例嘛？就我目前将两个配置放在同一个配置中，slim只会执行一个配置。
相关配置的源码我也查阅了，仍没有思路，诚恳的希望您给出一个解答，感谢！

**Comment by ZHZhang-whu** [comment]
#5842 这是之前那个问题，虽然得到了您们的解答，但是还是不知道如何去修改配置文件达到剪枝和量化联合的效果

**Comment by yu-jie-cpu** [comment]
遇到同样的问题

**Comment by qingqing01** [comment]
目前的配置还不太能同时支持剪枝后量化，代码中是if、else关系:


https://github.com/PaddlePaddle/PaddleDetection/blob/e9a5428f855a65480072e5c813949fba5f356eeb/ppdet/slim/__init__.py#L63-L76

如果自己修改的代码的话:

1. 一种方式，修改上面代码， 存在prune，先构建剪枝配置；存在quant，构建quant配置，顺序执行。但是否正确，可能要调试下。
2. 另一种方式，依据剪枝后的channel，更改源码，比较麻烦。


后续我们支持下这个需求。  @yghstill

**Comment by always-wo** [comment]
@qingqing01 请问我这样做之后会产生
fake_quantize_dequantize_moving_average_abs_max与type
moving_average_abs_max_scale算子，如何消除掉呢。我的硬件不支持

**Comment by always-wo** [comment]
我看用官方的训练配置文件来训练是不会出现这两个算子的

**Comment by Jiashuhao518** [comment]
> 我看用官方的训练配置文件来训练是不会出现这两个算子的

请问您解决这个问题了吗
