### ISSUE TITLE
PR曲线

### ISSUE THREAD

**Issue by Kaitosama7** [PaddlePaddle/PaddleDetection#5905]
使用paddledection可以输出单个模型的PR曲线，但是现在需要将两个模型画到一起，怎么去找输出的y_true和y_pred的文档呢？

**Comment by jerrywgz** [comment]
每个模型eval的时候都会得到一个eval result，将两个模型的result分别画出来就可以，具体代码参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/metrics/map_utils.py#L324
