### ISSUE TITLE
PicoFeat use_se 时 assert share_cls_reg == True

### ISSUE THREAD

**Issue by Li-4** [PaddlePaddle/PaddleDetection#5906]
https://github.com/PaddlePaddle/PaddleDetection/blob/acaf10684d8e071e48098c660355d54981d93b7c/ppdet/modeling/heads/pico_head.py#L93

```
assert share_cls_reg == True, \
                'In the case of using se, share_cls_reg is not supported'
```

后面的描述和 assert 不符合吧？这里必须 share_cls_reg == True 才能通过。  
但是 picodet_v2.yml 的配置文件中 share_cls_reg: True，use_se: True
搞不懂正确的情况是什么

**Comment by yghstill** [comment]
@Li-4 是的，描述不符，已修改，非常感谢~
