### ISSUE TITLE
请问pp-human如何用于双人动作识别？

### ISSUE THREAD

**Issue by ubikpkd** [PaddlePaddle/PaddleDetection#5907]
在参考如何训练ST-GCN识别自定义动作的教程时（https://github.com/PaddlePaddle/PaddleVideo/tree/develop/applications/PPHuman），该教程只支持单人动作的识别，在准备数据集时，即使检测到多人，它也只选取第一人
![image](https://user-images.githubusercontent.com/49560974/167325559-9a7c9cef-b16a-4c0e-815c-99c9d118dafe.png)
训练的配置文件也指明只识别单人动作
![image](https://user-images.githubusercontent.com/49560974/167325657-c6092f77-362d-4d20-b1a0-6be4850afbbf.png)
请问应当如何修改才能使pphuman用于识别多人动作？
提前感谢您的回答！

**Comment by zoooo0820** [comment]
目前pphuman中暂未直接提供多人共同定义的动作识别。关于在目前的方案中实现，可能需要修改较多的地方：
- 由于涉及到跟踪+关键点识别。在目前的pipeline的基于关键点识别的方案中，首先需要得到多个人物的跟踪结果（时序上要统一，即每人的动作在各帧上要对齐）。为了提升不同场景下的效果，最好将这些坐标调整到一个较为固定的坐标系下（可以参考NTU-RGB+D的双人动作，人物视角和位置是基本不变的）。
- 训练数据最后的维度以及配置文件将`person_nums`修改为最大支持人数即可，人数不足的动作数据用0补齐。

最后，我们目前也在补充一些多人动作的识别方案，预计在Q2可以放出

**Comment by ubikpkd** [comment]
> 目前pphuman中暂未直接提供多人共同定义的动作识别。关于在目前的方案中实现，可能需要修改较多的地方：
> 
> * 由于涉及到跟踪+关键点识别。在目前的pipeline的基于关键点识别的方案中，首先需要得到多个人物的跟踪结果（时序上要统一，即每人的动作在各帧上要对齐）。为了提升不同场景下的效果，最好将这些坐标调整到一个较为固定的坐标系下（可以参考NTU-RGB+D的双人动作，人物视角和位置是基本不变的）。
> * 训练数据最后的维度以及配置文件将`person_nums`修改为最大支持人数即可，人数不足的动作数据用0补齐。
> 
> 最后，我们目前也在补充一些多人动作的识别方案，预计在Q2可以放出

好的，感谢回复。
