### ISSUE TITLE
想问一个关于部署的问题

### ISSUE THREAD

**Issue by nine-city** [PaddlePaddle/PaddleDetection#5909]
训练好的模型，部署在GPU服务器上
我当前采用了摄像头进行推流
服务器进行了拉流处理并同时进行了模型的调用
我怎么知道当前GPU的处理上限是多少呢
是需要一个GPU还是多个GPU
有没有可以参考的服务器硬件配置

**Comment by yghstill** [comment]
Paddle Inference目前多进程不支持，部署使用单GPU环境即可，可以根据单个进程确定GPU显存占用，预估处理上限

**Comment by nine-city** [comment]
多路摄像头的情况下，需要自己去维护多线程，在各自线程内进行模型调用这样吗

**Comment by yghstill** [comment]
@nine-city 是的
