### ISSUE TITLE
请问有没有可以直接计算模型参数量和flops的工具？

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#5913]

**Comment by wangxinxin08** [comment]
在configs/runtime.yml中设置print_flops为True，然后运行eval即可打印MACS，FLOPS等于MACS的两倍。参数量，直接加载权重，按照下面的方式统计下即可
``` python
w = paddle.load(param_file)
p = sum([v.numel() for k, v in w.items() if '_mean' not in k and '_variance' not in k])
print('params: ', p)
```

**Comment by Dandelion111** [comment]
> 在configs/runtime.yml中设置print_flops为True，然后运行eval即可打印MACS，FLOPS等于MACS的两倍。参数量，直接加载权重，按照下面的方式统计下即可
> 
> ```python
> w = paddle.load(param_file)
> p = sum([v.numel() for k, v in w.items() if '_mean' not in k and '_variance' not in k])
> print('params: ', p)
> ```

多谢大佬

**Comment by Dekadenc** [comment]
> 
请问下方的代码是在这里运行吗
![image](https://user-images.githubusercontent.com/102035987/193384031-b72b5dd8-5739-425c-b54d-4bb3a08302f8.png)
param_file是导出模型后model.pdiparams的路径嘛
