### ISSUE TITLE
ppdet里面一些定义的类__shared__、__inject__这些属性表示什么意思

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#592]
__category__ = 
__inject__ = ['yolo_loss', 'nms']
__shared__ = ['num_classes', 'weight_prefix_name']

**Comment by still-wait** [comment]
@JensenHJS 
`__category__`: 为便于组织，模块可以分为不同类别
`__inject__`表示引入封装好了的检测组件/算子列表，此处`yolo_loss`与`nms`变量指向外部定义好的检测组件/算子
`__shared__`为了实现一些参数的配置全局共享，具体细节请参考[配置文件说明文档](https://paddledetection.readthedocs.io/advanced_tutorials/CONFIG_cn.html)
