### ISSUE TITLE
用picodet训练的模型严重误检

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#5923]
数据集中有A和B两种目标，其中A目标是贴在B目标上面，用picodet训练了一个只检测A的模型，有A目标的图像检测效果比较好，但是没有A目标的图像会误检为B目标上面的某个区域，而且置信度还挺高，有的达到0.8以上，求大佬分析一下这是什么原因？应该如何改进？

**Comment by wangxinxin08** [comment]
没有A目标的图像的误检确认是A目标的吗？如果确认的话，建议做一下数据增广：
1. A相对于B的位置的数据增广
2. 不包含A目标包含B目标的图像的数据增广

**Comment by Dandelion111** [comment]
> 没有A目标的图像的误检确认是A目标的吗？如果确认的话，建议做一下数据增广：
> 
> 1. A相对于B的位置的数据增广
> 2. 不包含A目标包含B目标的图像的数据增广

没有A目标时，会把B目标的某个区域识别成A。
A相对于B的位置的数据增广：这个是否可以用copypaste方法
不包含A目标包含B目标的图像的数据增广，意思是增加一些只有B目标的数据吗？我检测的时候没有检测B目标
