### ISSUE TITLE
PaddleDetection量化训练中的QAT量化问题

### ISSUE THREAD

**Issue by fash120** [PaddlePaddle/PaddleDetection#5929]
QAT量化的配置函数如下：
QAT:
  quant_config: {
    'weight_quantize_type': 'channel_wise_abs_max', 'activation_quantize_type': 'moving_average_abs_max',
    'weight_bits': 8, 'activation_bits': 8, 'dtype': 'int8', 'window_size': 10000, 'moving_rate': 0.9,
    'quantizable_layer_type': ['Conv2D', 'Linear']}
  print_model: True

我想请问以下 'quantizable_layer_type'这里可以对DW卷积也进行量化训练吗。还是说其实以及包括了DW卷积的量化训练了

**Comment by wangxinxin08** [comment]
可以对Conv2D进行量化训练，Conv2D包含DW卷机的量化

**Comment by fash120** [comment]
但是我看到其他的量化方式里边。有conv2d和dw的区分。再qat里边不用区分吗

**Comment by wangxinxin08** [comment]
> 但是我看到其他的量化方式里边。有conv2d和dw的区分。再qat里边不用区分吗

可以发一下链接看下哈
