### ISSUE TITLE
关于ppyoloe部分代码的疑问

### ISSUE THREAD

**Issue by janelu9** [PaddlePaddle/PaddleDetection#5932]
疑问是这段代码https://github.com/PaddlePaddle/PaddleDetection/blob/e9a5428f855a65480072e5c813949fba5f356eeb/ppdet/modeling/assigners/atss_assigner.py#L175

```
        # select positive sample, [B, n, L]
        mask_positive = is_in_topk * is_in_gts * pad_gt_mask

        # 7. if an anchor box is assigned to multiple gts,
        # the one with the highest iou will be selected.
        mask_positive_sum = mask_positive.sum(axis=-2)
        if mask_positive_sum.max() > 1:
            mask_multiple_gts = (mask_positive_sum.unsqueeze(1) > 1).tile(
                [1, num_max_boxes, 1])
            is_max_iou = compute_max_iou_anchor(ious)
            mask_positive = paddle.where(mask_multiple_gts, is_max_iou, mask_positive)
            mask_positive_sum = mask_positive.sum(axis=-2)
```
这个地方 当一个anchor属于多个gt_box时 会选择iou最大的那个gt_box 
但是这个写法在求每个anchor最大iou的gt_box时 没有考虑这个anchor属不属于gt_box的正样本
假设anchor甲iou最大的那个gt_box是乙  但是甲一定属于gt_box乙的正样本吗？有没有可能不属于 因为正样本是根据中心距离topk之后再根据iou确定的  但是iou最大的时候中心距离一定属于topk吗 
就是当某个列j的mask_multiple_gts大于1时，is_max_iou在某个行位置i为1，但是mask_positive在那个i,j地方有可能为0
就是虽然选取了该anchor(j)的最大iou的gt_box(i) 但是anchor(j)未必是gt_box(i) 的正样本
是不是应该先从属于gt_box 的正样本anchor集合中去找其最大iou的gt_box

我测试了一下
`is_max_iou = compute_max_iou_anchor(ious*pad_gt_mask)`
和
`is_max_iou = compute_max_iou_anchor(ious*mask_positive)`
最终得到的is_max_iou 是刚好相等的，似乎这个测试数据中最大iou的anchor都属于正样本（中心距属于topk且iou>阈值且中心在gt内）但感觉不能确保没有例外

**Comment by ghostxsl** [comment]
我们的开发人员正在排查问题，后续会提PR修复～
