### ISSUE TITLE
训练关键点检测模型，如何配置加载预训练模型

### ISSUE THREAD

**Issue by xywlpo** [PaddlePaddle/PaddleDetection#5935]
请问使用paddledetection 2.4时，训练关键点检测模型，LiteHRNet-18，backbone部分想使用预训练模型，在config中对应的配置文件应该如何修改啊？

**Comment by jerrywgz** [comment]
litehrnet的预训练模型可以直接使用这里提供的coco训练好的权重，https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/keypoint#%E6%A8%A1%E5%9E%8B%E5%BA%93 litehrnet的训练本身是没有使用imagenet做预训练权重的
配置文件中加下：`pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/keypoint/lite_hrnet_18_256x192_coco.pdparams`
