### ISSUE TITLE
推理报错

### ISSUE THREAD

**Issue by lvjianjin001** [PaddlePaddle/PaddleDetection#5936]
InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 1191, the input's shape is [1, 1191, 811, 3]; the filter's channels is 3, the filter's shape is [16, 3, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
      [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:1191 != filter_dims[1] * groups:3.] (at C:/home/workspace/Paddle_release/paddle/fluid/operators/conv_op.cc:100)
      [operator < conv2d > error]

**Comment by jerrywgz** [comment]
可以具体描述下使用的模型、部署方式、参考代码以及paddledetection和paddle的版本吗

**Comment by lvjianjin001** [comment]
> 可以具体描述下使用的模型、部署方式、参考代码以及paddledetection和paddle的版本吗

paddledetection下面自己训练的yolov3模型，windows下使用的python推理，paddle2.1
推理代码如下：python tools/export_model.py -c configs/yolov3/analysis/yolov3_mobilenet_v3_large_270e_voc.yml --output_dir=./infernce_model/analysis/ -o weight=weight/analysis/best_model.pdparams

**Comment by lvjianjin001** [comment]
> 可以具体描述下使用的模型、部署方式、参考代码以及paddledetection和paddle的版本吗

我在该环境下使用相同的图片推理其他的模型是可以的，就是新训练的模型不行。使用的参数配置也都一样，只是类别与数据不同。

**Comment by lvjianjin001** [comment]
> 可以具体描述下使用的模型、部署方式、参考代码以及paddledetection和paddle的版本
还有一个问题是我根据官方文档重新安装了环境，在预训练模型上报了这个错，我记得之前是不需要去修改配置文件里面的这个参数的呀？两个都不能顺利推理。
![image](https://user-images.githubusercontent.com/88391549/168011025-84f55269-9bf5-415c-a304-e04cd24688ba.png)

**Comment by jerrywgz** [comment]
导出时需要制定-o weights=xxx，你这里的输入是weight
