### ISSUE TITLE
Paddle Detection依赖的lap编译不通过[Install]

### ISSUE THREAD

**Issue by njuptzwt** [PaddlePaddle/PaddleDetection#5940]
系统：macOS Big Sur 11.6.4
PaddlePaddle的版本：2.2.2
Python版本：3.7.3
已经按照步骤进行安装
出现的问题：PaddleDetection依赖报错，lap依赖无法加载成功

具体报错信息：
Collecting lap
  Using cached lap-0.4.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: lap
  Building wheel for lap (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6690 lines of output]
      Partial import of lap during the build process.
      Generating cython files
      running bdist_wheel
      running build
      running config_cc
      unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      build_src
      building extension "lap._lapjv" sources
      building data_files sources
      build_src: building npy-pkg config files
      /Users/zhengwentian/.pyenv/versions/3.7.3/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build_py
      creating build
      creating build/lib.macosx-10.15-x86_64-cpython-37
      creating build/lib.macosx-10.15-x86_64-cpython-37/lap
      copying lap/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-37/lap
      copying lap/lapmod.py -> build/lib.macosx-10.15-x86_64-cpython-37/lap
      running build_ext
      customize UnixCCompiler
      customize UnixCCompiler using build_ext
      customize UnixCCompiler
      #### ['clang', '-Wno-unused-result', '-Wsign-compare', '-Wunreachable-code', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include', '-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include'] #######
      customize UnixCCompiler using build_ext
      building 'lap._lapjv' extension
      compiling C++ sources
      C compiler: clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
      
      creating build/temp.macosx-10.15-x86_64-cpython-37/lap
      compile options: '-I/Users/zhengwentian/.pyenv/versions/3.7.3/lib/python3.7/site-packages/numpy/core/include -Ilap -I/Users/zhengwentian/.pyenv/versions/3.7.3/lib/python3.7/site-packages/numpy/core/include -I/Users/zhengwentian/.pyenv/versions/3.7.3/include/python3.7m -c'
      clang++: lap/lapjv.cppclang++: lap/_lapjv.cpp
      clang++: lap/lapmod.cpp
      
      In file included from lap/lapjv.cpp:1:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:93:16: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
      In file included from lap/lapmod.cpp:1:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:93:16: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]        unsigned char   *_base;
      
                              ^
              unsigned char   *_base;
                              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:93:16: note: insert '_Nullable' if the pointer may be null
              unsigned char   *_base;
                              ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h                          _Nullable :
      93:16: note: insert '_Nullable' if the pointer may be null
              unsigned char   *_base;
                              ^
                                _Nullable
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:93:16: note: insert '_Nonnull' if the pointer should never be null
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:93:16:         unsigned char   *_base;
                              ^
                                _Nonnull note
      : insert '_Nonnull' if the pointer should never be null
              unsigned char   *_base;
                              ^
                                _Nonnull
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:138:32: warning: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.hpointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]:
      138:32: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
              int     (* _Nullable _read) (void *, char *, int);
                                                ^
              int     (* _Nullable _read) (void *, char *, int);
                                                ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:138:32: note: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:138:insert '_Nullable' if the pointer may be null32
      : note: insert '_Nullable' if the pointer may be null
              int     (* _Nullable _read) (void *, char *, int);
                                                ^
                                                 _Nullable
              int     (* _Nullable _read) (void *, char *, int);
                                                ^
                                                 _Nullable
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:138:32: note: insert '_Nonnull' if the pointer should never be null
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:138:32: note: insert '_Nonnull' if the pointer should never be null
              int     (* _Nullable _read) (void *, char *, int);
                                                ^
                                                 _Nonnull
              int     (* _Nullable _read) (void *, char *, int);
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h                                          ^:
      138                                           _Nonnull:
      40: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:138:40: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
              int     (* _Nullable _read) (void *, char *, int);
                                                        ^
              int     (* _Nullable _read) (void *, char *, int);
                                                        ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:138:40: note: insert '_Nullable' if the pointer may be null
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:138:40: note: insert '_Nullable' if the pointer may be null
              int     (* _Nullable _read) (void *, char *, int);
                                                        ^
                                                         _Nullable
              int     (* _Nullable _read) (void *, char *, int);
                                                        ^
                                                         _Nullable
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:138:40: note: insert '_Nonnull' if the pointer should never be null
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:138:40: note: insert '_Nonnull' if the pointer should never be null
              int     (* _Nullable _read) (void *, char *, int);
                                                        ^
                                                         _Nonnull
              int     (* _Nullable _read) (void *, char *, int);
                                                        ^
                                                         _Nonnull
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:139:35: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:139:35: warning        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);:
                                                ^pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
      
              fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
                                                ^
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:139:35: note: insert '_Nullable' if the pointer may be null
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:139:35        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);:
                                                 ^note
      :                                            _Nullableinsert '_Nullable' if the pointer may be null
      
              fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
                                                ^
                                                 _Nullable
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:139:35: note: insert '_Nonnull' if the pointer should never be null
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:139:35:         fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
                                                ^note
      : insert '_Nonnull' if the pointer should never be null
                                                 _Nonnull
              fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
                                                ^
                                                 _Nonnull
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:140:32: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:140:32:         int     (* _Nullable _write)(void *, const char *, int);warning
      :                                           ^pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
      
              int     (* _Nullable _write)(void *, const char *, int);

**Comment by lyuwenyu** [comment]
直接 pip install lap不行嘛，  update一下你的pip版本

**Comment by voyag8r** [comment]
我遇到过你这个问题
conda install -c conda-forge lap
应该可以

**Comment by njuptzwt** [comment]
> 

好的，我是用pip装的，我尝试用conda试一试

**Comment by njuptzwt** [comment]
> 直接 pip install lap不行嘛， update一下你的pip版本

我换了一个Python版本用pip安装正常了，从3.7.3->3.8.9，不知道是不是我的Python环境太乱了，冲突
