### ISSUE TITLE
ppyolo-mobilenetv3 这个就是 mobilenetv3网络是么？

### ISSUE THREAD

**Issue by STUSER001** [PaddlePaddle/PaddleDetection#5942]
![image](https://user-images.githubusercontent.com/88072901/167806042-dc68817d-68ab-47fd-a045-bb1e15561417.png)
这个是 ppyolo的 mv3 么？ 这个 跟 ppyolo-tiny 有啥区别呢 我看结构都是 主干mv3 neck fpn

**Comment by lyuwenyu** [comment]
数据预处理和优化策略不一样   网络结构一样的
