### ISSUE TITLE
如何导出无nms的ppyoloe

### ISSUE THREAD

**Issue by hobeter** [PaddlePaddle/PaddleDetection#5948]
想导出不带nms的ppyoloe

尝试使用
-o exclude_nms=True

但infer的时候结果很奇怪，得到的result是
<img width="835" alt="截屏2022-05-11 22 05 27" src="https://user-images.githubusercontent.com/55823642/167869159-54c476f7-eaff-4cfd-98f7-7ed122384be9.png">

请问应该怎么导出无nms的ppyoloe
十分感谢🙏

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/modeling/heads/ppyoloe_head.py#L380
改成
```
return pred_bboxes, pred_scores
```
原本ppyoloe无nms时只是为了测速，所以直接返回sum。也可以返回过NMS前的结果，你需要自己接个NMS才能得到最终的检测结果。

**Comment by hobeter** [comment]
好的，十分感谢🙏
