### ISSUE TITLE
多类别目标跟踪的自定义数据集标注问题

### ISSUE THREAD

**Issue by nine-city** [PaddlePaddle/PaddleDetection#5951]
有什么工具能够很方便的标注VisDrone数据集呀，用于MCFairMOT检测

**Comment by nemonameless** [comment]
#4985 
EasyDL在线标注，标注数据不支持导出： https://ai.baidu.com/ai-doc/EASYDL/wkqj1q8cs
离线标注工具，可以参考 https://github.com/openvinotoolkit/cvat
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/formats/format-mot/
VisDrone MOT数据集在他们官网有提供下载。PaddleDetection团队是改格式为fairmot训练的格式，你可以下载这个链接
https://bj.bcebos.com/v1/paddledet/data/mot/visdrone_mcmot.zip

**Comment by nine-city** [comment]
就是说最终还是需要用fairmot（MIX数据集）的格式来训练多类别跟踪吗。这样是不是就相当于fairmot+多class？
用自己的视频来标注自定义数据集就的话还有什么地方要特殊调整的吗

**Comment by nemonameless** [comment]
用自己的视频标注，最好是切成图片存下来，然后参照 
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/PrepareMOTDataSet_cn.md
需要和MOT16 MOT17数据集的格式一样。多类别就是类别号不只是0了。

**Comment by nine-city** [comment]
如果切成了图片。用paddleseg或者EISEG标注的话。导出json或者coco格式，然后自己写脚本转为mot格式。这种方案是否可行呢

**Comment by nemonameless** [comment]
可以的
