### ISSUE TITLE
自定义数据，训练KeyPoint报错

### ISSUE THREAD

**Issue by ff12343** [PaddlePaddle/PaddleDetection#5961]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/42758082/168120012-e72b074b-fc5d-4b40-94f4-175fc9a4e284.png)
自定义数据集修改了输入数据集的关键点个数，测试评估的时候报错。
尝试keypoint_utils.py中的sigmas参数的个数；同时修改metrics.py的COCO_SIGMAS参数个数，依旧报错，请问是什么原因导致的

**Comment by zoooo0820** [comment]
@ff12343 
从报错上看，是groundtruth visible的维度和e的维度不匹配，先检查下这部分。还不行的话可以贴一下标注文件中keypoint部分，以及sigma参数是怎么修改的。
