### ISSUE TITLE
下载pycocotools的问题

### ISSUE THREAD

**Issue by lihaiyu01** [PaddlePaddle/PaddleDetection#5962]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我下载pdddledetection和ppdlex不知道是因为pycocotools的版本重合了吗？我之前可以运行的代码今天就提示我没有下载这个包，在终端下载了也不行。下载其他包也是出现这样的问题
![-44174fa677aaf571](https://user-images.githubusercontent.com/101405434/168161466-b3704279-78be-4542-bf97-b374b524ba1b.png)

**Comment by ghostxsl** [comment]
建议排查一下机器上多python环境的问题

**Comment by JAY022** [comment]
走链接下 直接pip不行好像
