### ISSUE TITLE
您好，我在windows10系统单机多卡的情况下，安装PaddlePaddle-gpu2.2.0时，安装成功，但是在验证时，提示以下报错信息，我应该怎样来指定固定的一张卡上安装paddlepaddle套件呢？谢谢

### ISSUE THREAD

**Issue by tuodi** [PaddlePaddle/PaddleDetection#5965]
### 问题描述 Please describe your issue

![paddlepaddle-error](https://user-images.githubusercontent.com/33543014/168189307-30450ad4-e3b5-4a7d-aae9-84f4060e65bc.png)
![paddlepaddle-error](https://user-images.githubusercontent.com/33543014/168189377-ebab2d48-d937-4e9e-a6ae-8cf992d8c57d.png)

**Comment by ghostxsl** [comment]
截图中的报错信息已经告诉你可能的原因了，建议先排查一下：NCCL是否安装正确
