### ISSUE TITLE
cpp_infer程序运行没有错误，但是没有bbox产生，infer.py运行结果OK，预测结果也都OK

### ISSUE THREAD

**Issue by mingmmq** [PaddlePaddle/PaddleDetection#597]
这是demo的yml，模型是参考教程进行export的。
`# demo for cpp_infer.py

use_python_inference: false # whether to use python inference
mode: fluid # trt_fp32, trt_fp16, trt_int8, fluid
arch: YOLO # YOLO, SSD, RCNN, RetinaNet
min_subgraph_size: 40 # need 3 for YOLO arch

# visualize the predicted image
metric: COCO # COCO, VOC
draw_threshold: 0.01

Preprocess:
- type: Resize
  target_size: 608
  max_size: 608
- type: Normalize
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  is_scale: True
- type: Permute
  to_bgr: False
- type: PadStride
  stride: 0 # set 32 on FPN and 128 on RetinaNet
`
predictor没有任何out产生。

**Comment by willthefrog** [comment]
> predictor没有任何out产生。
能否尝试打印下predictor的输出结果呢？
使用的输入是自己的图片么？
使用的版本是多少？

**Comment by mingmmq** [comment]
对的使用的自己的图片，
`        out = outs[-1]
        lod = out.lod() if conf['use_python_inference'] else out.lod
        lengths = offset_to_lengths(lod)
        np_data = np.array(out) if conf[
            'use_python_inference'] else out.as_ndarray()

        print("np data",np_data)
        res['bbox'] = (np_data, lengths)
        res['im_id'] = np.array([[0]])`
输出是：**np_data [[-1.]]**

使用的版本是：release0.2
paddle版本应该是：
I0506 22:52:36.435652 31256 analysis_predictor.cc:833] MODEL VERSION: 1.7.1
I0506 22:52:36.435678 31256 analysis_predictor.cc:835] PREDICTOR VERSION: 1.7.1

**Comment by willthefrog** [comment]
这个图片使用其他方式是可以检测出物体的么？ 看输出应该是正常运行的，但是没有检测到物体。使用demo 文件夹下的图片能检测出物体么？

**Comment by mingmmq** [comment]
是我自己训练的模型，用的自己的数据集。
使用python的infer.py是能够检测的，而且效果很好。
demo下的应该不行，因为模型是我自己训练的。

**Comment by mingmmq** [comment]
`
W0506 22:52:37.607172 31256 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.0
W0506 22:52:37.611021 31256 device_context.cc:245] device: 0, cuDNN Version: 7.6.
W0506 22:52:38.306897 31256 naive_executor.cc:45] The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.
W0506 22:52:38.306941 31256 naive_executor.cc:47] Unlike the training phase, all the scopes and variables will be reused to save the allocation overhead.
W0506 22:52:38.306947 31256 naive_executor.cc:50] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference
W0506 22:52:38.338858 31256 naive_executor.cc:45] The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.
W0506 22:52:38.338901 31256 naive_executor.cc:47] Unlike the training phase, all the scopes and variables will be reused to save the allocation overhead.
W0506 22:52:38.338907 31256 naive_executor.cc:50] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference
W0506 22:52:38.366299 31256 naive_executor.cc:45] The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.
W0506 22:52:38.366333 31256 naive_executor.cc:47] Unlike the training phase, all the scopes and variables will be reused to save the allocation overhead.
W0506 22:52:38.366340 31256 naive_executor.cc:50] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference
W0506 22:52:38.399917 31256 naive_executor.cc:45] The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.
W0506 22:52:38.399960 31256 naive_executor.cc:47] Unlike the training phase, all the scopes and variables will be reused to save the allocation overhead.
W0506 22:52:38.399969 31256 naive_executor.cc:50] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference
W0506 22:52:38.428539 31256 naive_executor.cc:45] The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.
W0506 22:52:38.428570 31256 naive_executor.cc:47] Unlike the training phase, all the scopes and variables will be reused to save the allocation overhead.
W0506 22:52:38.428580 31256 naive_executor.cc:50] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference
2020-05-06 22:52:38,584-INFO: run benchmark...
`

用cpp_infer 设置use_python_inference: false时候有这个提示，但应该不是影响的原因

**Comment by mingmmq** [comment]
使用Pretrain的YOLOV3 enhance模型，也无法得到bbox，虽然np_data里面有一定的内容：

`2020-05-07 02:28:43,939-INFO: The architecture is YOLO
2020-05-07 02:28:43,939-INFO: Extra info: im_size
W0507 02:28:44.536193 29263 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.0
W0507 02:28:44.539896 29263 device_context.cc:245] device: 0, cuDNN Version: 7.6.
2020-05-07 02:28:45,331-INFO: warmup...
2020-05-07 02:28:45,993-INFO: run benchmark...
Inference: 64.80458736419678 ms per batch image
2020-05-07 02:28:52,474-INFO: Load categories from /home/kik/Github/PaddleDetection/dataset/coco/annotations/instances_val2017.json
loading annotations into memory...
Done (t=0.59s)
creating index...
index created!
np data [[0.0000000e+00 2.6574144e-02 0.0000000e+00 0.0000000e+00 6.3900000e+02
  4.0300000e+02]
 [5.9000000e+01 1.4270748e-02 0.0000000e+00 0.0000000e+00 6.3900000e+02
  4.0300000e+02]
 [6.2000000e+01 1.9279426e-02 0.0000000e+00 0.0000000e+00 6.3900000e+02
  4.0300000e+02]
 [6.3000000e+01 1.2607769e-02 0.0000000e+00 0.0000000e+00 6.3900000e+02
  4.0300000e+02]
 [6.8000000e+01 1.0902748e-02 0.0000000e+00 0.0000000e+00 6.3900000e+02
  4.0300000e+02]
 [7.2000000e+01 1.5802321e-01 0.0000000e+00 0.0000000e+00 6.3900000e+02
  4.0300000e+02]]

`

**Comment by baigang666** [comment]
@mingmmq  我遇到过这个问题 ，你尝试把那个yml文件里的to_bgr那一项改为True.

**Comment by mingmmq** [comment]
> @mingmmq 我遇到过这个问题 ，你尝试把那个yml文件里的to_bgr那一项改为True.

尝试了下，没有效果呢。还是没有bbox产生。

**Comment by willthefrog** [comment]
yolo enhanced预处理部分有些差异，可以试下使用[标准的yolo v3 权重](https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet.tar)，然后使用demo里的图片，看看是否能正常检测。我这边测试了master分支是可以正常检测的。@mingmmq

**Comment by mingmmq** [comment]
> yolo enhanced预处理部分有些差异，可以试下使用[标准的yolo v3 权重](https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet.tar)，然后使用demo里的图片，看看是否能正常检测。我这边测试了master分支是可以正常检测的。@mingmmq

嗯，测试过了，用的标准权重是可以的。我怀疑是export_model.py的问题，只有标准的在export前后都能预测，使用enhance的，export之后就没法正确预测，不管是使用的PaddleDetection提供好的训练模型，还是我自己训练的。

**Comment by willthefrog** [comment]
enhance训练时配置有点错误，所以必须按当时错误的配置才能正常预测。你也可以试下其他模型的权重，应该是可以正常检测的。但是你自己训练的模型就不确定是什么问题了。

**Comment by mingmmq** [comment]
> enhance训练时配置有点错误，所以必须按当时错误的配置才能正常预测。你也可以试下其他模型的权重，应该是可以正常检测的。但是你自己训练的模型就不确定是什么问题了。

YOLOv3 ResNet50_vd DCN DropBlock IoULoss 这个模型，没有任何改动，使用训练好的权重，export之后的，也没有办法预测。请问错误配置在哪里可以拿到？

**Comment by willthefrog** [comment]
那个也是obj365 pretrain的，应该是一样的问题。参见 #511

**Comment by mingmmq** [comment]
> 那个也是obj365 pretrain的，应该是一样的问题。参见 #511

使用的就是 #511 里面有问题的配置，并没有什么效果，infer.py能正常出结果，export之后cpp_infer就没有结果。

**Comment by willthefrog** [comment]
> > 那个也是obj365 pretrain的，应该是一样的问题。参见 #511
> 
> 使用的就是 #511 里面有问题的配置，并没有什么效果，infer.py能正常出结果，export之后cpp_infer就没有结果。

`cpp_infer.py` 使用的是自己的预处理配置，并不是config里的配置，如果要用那几个model的话要做相应修改。

**Comment by mingmmq** [comment]
> > > 那个也是obj365 pretrain的，应该是一样的问题。参见 #511
> > 
> > 
> > 使用的就是 #511 里面有问题的配置，并没有什么效果，infer.py能正常出结果，export之后cpp_infer就没有结果。
> 
> `cpp_infer.py` 使用的是自己的预处理配置，并不是config里的配置，如果要用那几个model的话要做相应修改。

的确是的，就是is_scale的问题，在cpp_infer里面将scale变成false，就能检测出来结果了。
