### ISSUE TITLE
PPhuman使用stgcn导出的模型预测报window_size错误并且没有预测结果

### ISSUE THREAD

**Issue by che2d** [PaddlePaddle/PaddleDetection#5970]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我使用了18个关键点训练stgcn精度到87%，使用tools.py导出模型后用于PPhuamn去推理视频，存在max_frame设置的问题，我看到代码中max_frame其实就是Window_size，是要和训练时一致的，我设置的是50，这个含义看文档说累计到该帧数后开始预测。但是我预测一个10秒的视频，会在50帧时停下来并报错：InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But
received X's shape = [1, 1, 17, 2, 50], X's size = 1700, 'shape' is [-1, 36, 50], known capacity of 'shape' is -1800.
[Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:0 != -in_size:-1700.] (at .
.\paddle/fluid/operators/reshape_op.cc:210)
[operator < reshape2 > error]

但是官方给的yml文件里设置的也是50，给定的视频也是6秒远超50帧，但却没有报错，而且在50帧后视频里输出了预测类别，请问这个max_frame到底如何设置，或者说如何解决这个问题？
如果说是和训练一致，我训练模型时是设置的350，后面我将pphuman的yml文件以及max_frame设置成350，去预测一个20秒视频，依然在帧数到达350报错，和上面的差不多。该如何解决呢？

**Comment by che2d** [comment]
另外虽然我训练的模型精度还行，但是却并没有在pphuman输出预测结果，是因为我模型导出错误，还是是hrnet关键点17个和我18关键点的模型匹配不上，建议增设openpose18关键点的推理模型；
或者说是否有模型联合推理文档呢，让我们可以自行设计哪几个模型共同推理

**Comment by zoooo0820** [comment]
@che2d 
pphuman里是一个pipeline，前序模型输出传过来的shape和自训练的stgcn模型接收参数不匹配了，两者点数没有对应，这里没有结果是因为stgcn没有成功运行。
如果希望用18点模型，目前paddledetection里暂时没有openpose的点位定义与对应模型，关于新增计划我们会再考虑一下。短期内可以考虑使用[x2paddle](https://github.com/PaddlePaddle/X2Paddle)将模型转过来，并替换hrnet。

**Comment by Xinxinatg** [comment]
> @che2d pphuman里是一个pipeline，前序模型输出传过来的shape和自训练的stgcn模型接收参数不匹配了，两者点数没有对应，这里没有结果是因为stgcn没有成功运行。 如果希望用18点模型，目前paddledetection里暂时没有openpose的点位定义与对应模型，关于新增计划我们会再考虑一下。短期内可以考虑使用[x2paddle](https://github.com/PaddlePaddle/X2Paddle)将模型转过来，并替换hrnet。

你好我用x2paddle转换了Openpose的25个关键点的检测模型后，放到pphuman2的pipeline里面，得到如下错误：
InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [1, 1, 97, 2, 50], X's size = 9700, 'shape' is [-1, 75, 50], known capacity of 'shape' is -3750.
      [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-7500 != -in_size:-9700.] (at /paddle/paddle/fluid/operators/reshape_op.cc:190)
      [operator < reshape2 > error]

请问我应该怎样处理呢
