### ISSUE TITLE
PPhuman 使用 --run_mode trt_fp16 参数，程序 运行到Model Configuration ，不再往下运行，也不报错，也不返回

### ISSUE THREAD

**Issue by liuchangf** [PaddlePaddle/PaddleDetection#5975]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

PPhuman 使用 --run_mode trt_fp16 参数，程序 运行到Model Configuration ，不再往下运行，也不报错，也不返回

如果不使用 TensorRT，即不加--run_mode trt_fp16 参数，则可正常运行

### 复现环境 Environment

-paddlepaddle-gpu   2.2.2.post101
-paddledet          2.4.0
-python               3.8.0
-CUDA                 10.1
-CUDNN              7.6.5
-OS                       WIN10

python deploy/pphuman/pipeline.py --config deploy/pphuman/config/infer_cfg.yml --video_file=G:\win_project\FairMOT\code\data_prepaired\2.mp4 --device=gpu --enable_action=True --run_mode
 trt_fp16
F:\python_project\paddle_detection_project\venv\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: N
EAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
F:\python_project\paddle_detection_project\venv\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: B
ILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
F:\python_project\paddle_detection_project\venv\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: B
ICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
F:\python_project\paddle_detection_project\venv\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: B
OX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
F:\python_project\paddle_detection_project\venv\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: L
ANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
F:\python_project\paddle_detection_project\venv\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: H
AMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
deploy/pphuman/pipeline.py:26: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is
 deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Sequence
-----------  Running Arguments -----------
ACTION:
  batch_size: 1
  coord_size:
  - 384
  - 512
  display_frames: 80
  max_frames: 50
  model_dir: output_inference/STGCN
ATTR:
  batch_size: 8
  model_dir: output_inference/strongbaseline_r50_30e_pa100k/
DET:
  batch_size: 1
  model_dir: output_inference/mot_ppyoloe_l_36e_pipeline/
KPT:
  batch_size: 8
  model_dir: output_inference/dark_hrnet_w32_256x192/
MOT:
  batch_size: 1
  model_dir: output_inference/mot_ppyoloe_l_36e_pipeline/
  tracker_config: deploy/pphuman/config/tracker_config.yml
REID:
  batch_size: 16
  model_dir: output_inference/reid_model/
attr_thresh: 0.5
crop_thresh: 0.5
kpt_thresh: 0.2
visual: true
warmup_frame: 50

------------------------------------------
Action Recognition enabled
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: Permute
--------------------------------------------
程序停止在此处，无报错，无返回

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by liuchangf** [comment]
大约1个小时以后，模型加载完成。（太慢了）
但是使用TensorRT并没有加速，性能和不使用TensorRT相同

**Comment by zhiboniu** [comment]
你好，非常感谢你的异常反馈，初步怀疑是对tensorrt的支持有些问题，我们先排查一下

**Comment by mazai-xiangji** [comment]
> 你好，非常感谢你的异常反馈，初步怀疑是对tensorrt的支持有些问题，我们先排查一下

你好，想问一下tensorrt转换后的模型会存放在哪里，重新运行的时候又加载tensorrt的转换。
我的CUDA=10.2，cudnn=7.6.5，paddle是带trt的对应的版本，trt版本是7.0也是对应的

**Comment by exceedTu** [comment]
我也是你这样的问题，没有任何返回就自动结束了，

**Comment by ysguo0327** [comment]
看看这个[TensorRT 部署效率太差的BUG！](https://github.com/PaddlePaddle/PaddleDetection/issues/7027)。
另外，可以看看官网[使用Paddle-TensorRT库预测](https://www.paddlepaddle.org.cn/inference/master/optimize/paddle_trt.html)资料。
![image](https://user-images.githubusercontent.com/25575338/195287259-f241d5c2-6fa6-461e-bbd4-e901224fb5a5.png)
我个人`RTX3080`上的测试结果是`run_mode=trt_fp16`会比`run_mode=paddle`快约2.5倍。

```
------------------ Inference Time Info ----------------------
total_time(ms): 10305.0, img_num: 582
mot time(ms): 8617.4; per frame average time(ms): 14.806529209621992
cls_action time(ms): 1637.3; per trackid average time(ms): 2.813230240549828
average latency time(ms): 17.71, QPS: 56.477438
```
