### ISSUE TITLE
maskrcnn小目标检测如何调参

### ISSUE THREAD

**Issue by jiangxinufo** [PaddlePaddle/PaddleDetection#5979]
### 文档链接&描述 Document Links & Description

maskrcnn小目标检测如何调参，在一幅图像中，需要被提取的目标有的非常大，有的非常小，通过什么样的方法可以把大小目标都分割出来呢，目前看大目标效果较好，小目标漏检情况比较多，如何调参呢？

### 请提出你的建议 Please give your suggestion

maskrcnn小目标检测如何调参，在一幅图像中，需要被提取的目标有的非常大，有的非常小，通过什么样的方法可以把大小目标都分割出来呢，目前看大目标效果较好，小目标漏检情况比较多，如何调参呢？

**Comment by jerrywgz** [comment]
可以针对您的数据集调整下anchor 的大小，ppdet下面提供了anchor聚类的脚本可以尝试下，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/tools/anchor_cluster.py

**Comment by jiangxinufo** [comment]
> 可以针对您的数据集调整下anchor 的大小，ppdet下面提供了anchor聚类的脚本可以尝试下，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/tools/anchor_cluster.py

之前确实重新生成了下anchor，但是图像中有大，有小，物体大小比较随机，效果有所提升，但是不明显？还有是什么可行的优化方案吗

**Comment by laoda22222222** [comment]
> > 可以针对您的数据集调整下anchor 的大小，ppdet下面提供了anchor聚类的脚本可以尝试下，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/tools/anchor_cluster.py
> 
> 之前确实重新生成了下anchor，但是图像中有大，有小，物体大小比较随机，效果有所提升，但是不明显？还有是什么可行的优化方案吗

请问您这个问题有解决方案了吗？
