### ISSUE TITLE
静态量化

### ISSUE THREAD

**Issue by malcolm-wang** [PaddlePaddle/PaddleDetection#5980]
### 问题描述 Please describe your issue

现在已经有了inference_model下的.pdmodel和.pdiparams文件(来自于ssd_mobilenet)，请问应该如何进行静态量化？

**Comment by zhiboniu** [comment]
你好，量化方法可以参考paddleslim的介绍
https://github.com/PaddlePaddle/PaddleSlim

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/slim#%E7%A6%BB%E7%BA%BF%E9%87%8F%E5%8C%96 可以参考这部分文档
