### ISSUE TITLE
Unable to download the links from pp-human

### ISSUE THREAD

**Issue by icarofua** [PaddlePaddle/PaddleDetection#5982]
All the links from pp-human are giving the same issue "The site can't be reached".

**Comment by jerrywgz** [comment]
The link in https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/pphuman is correct and could you show the doc you used?

**Comment by icarofua** [comment]
I am trying to download the models and params in english or chinese versions. For example, for this link https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_pipeline.zip it is showing "The site can't be reached".

**Comment by YixinKristy** [comment]
Hi, we have tried to download through the link you provided and found out it works. Maybe its the internet, so can you try it again? At the same time, if we get new clues on this issue, we'll let you know~

**Comment by icarofua** [comment]
Apparently, some issues in the UAE downloading the links. when I am using the VPN works.
