### ISSUE TITLE
双卡训练，命令加入--use_vdl=True，会在指定文件夹下生成2个vdlrecords，可视化时候无显示数据

### ISSUE THREAD

**Issue by Tongfengyu** [PaddlePaddle/PaddleDetection#5984]
### 问题描述 Please describe your issue

命令：python -m paddle.distributed.launch --gpus 1,2 tools/train.py -c configs/ppyoloe/ppyoloe_crn_x_300e_coco.yml --amp --eval --use_vdl=True --vdl_log_dir='./output_vdl_dir/output_vdlxxx'
![image](https://user-images.githubusercontent.com/82866148/168427960-c03ded17-52b6-4660-8de6-1d5241ae04cf.png)
![image](https://user-images.githubusercontent.com/82866148/168427967-8e9cf7e2-280c-429d-9dbf-546031e6f92d.png)
可以看到先生成的文件是后续持续要写入的，后生成的是空的vdlrecords文件，在可视化的时候往往需要自己删掉空的，很繁琐。

**Comment by zhiboniu** [comment]
好的，您的问题已经收到。我这里分析原因应该是启动的两个任务每个都保持了一份，但是最终只有一份打印了完整数据。这个应该是visualdl需要的优化的点，建议在https://github.com/PaddlePaddle/VisualDL repo下也提一份issue

**Comment by YixinKristy** [comment]
您好，VisualDL的续写是需要指定对应log文件的，如果不指定对应log文件，visualdl无法判断需要基于哪一份文件进行续写，则会重新生成一个log文件，续写参数如下：
<img width="1027" alt="vdl" src="https://user-images.githubusercontent.com/48054808/168713678-6ac6ebb5-a566-4776-a6f9-0f6604844b43.png">

另外，在一个文件夹里有多个vdlrecords文件时，VisualDL会选择最新时间戳的进行可视化呈现，如果需要同时呈现多个vdlrecords文件，则将其分别放置一个log文件夹中，在启动时添加log路径即可。
