### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by yangxue-1** [PaddlePaddle/PaddleDetection#5985]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

快速体验的命令：
python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg

会下载一个http://images.cocodataset.org/zips/train2017.zip，高达18gb
然后回出现ConnectionResetError: [Errno 104] Connection reset by peer
请问这是什么情况？望解答！多谢！

### 复现环境 Environment

PaddlePaddle 2.2.2
OS 64位操作系统linux
Python 3.7.4，64位版本
pip/pip3(9.0.1+)，64位版本
CUDA = 11.2
cuDNN >= 7.6

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by zoooo0820** [comment]
找不到对应训练和测试集的时候会自动下载数据集。这个问题应该是修复过了，可以先更新paddledetection的代码再试下

**Comment by nemonameless** [comment]
数据集配置路径出错了，就会自动下载数据集。Connection reset by peer是网络没连上导致下载不了。
