### ISSUE TITLE
faster rcnn r50 fpn模型转换为onnx问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleDetection#5986]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问目前使用PaddleDetection训练出来的faster rcnn r50 fpn模型可以转换为onnx模型吗？

**Comment by jerrywgz** [comment]
RCNN模型导出的时候，需要在配置文件中增加`export_onnx: True`；另外paddle2onnx需要使用最新版本

可以再参考下这个issue https://github.com/PaddlePaddle/Paddle2ONNX/issues/699

**Comment by gxqnba** [comment]
> RCNN模型导出的时候，需要在配置文件中增加`export_onnx: True`；另外paddle2onnx需要使用最新版本
> 
> 可以再参考下这个issue [PaddlePaddle/Paddle2ONNX#699](https://github.com/PaddlePaddle/Paddle2ONNX/issues/699)

我将导出的model.onnx放到netron中查看，其输入有三个，其中scale_factor是啥意思啊？还有输出有两个，concat_6.tmp_0 和tmp_42是啥意思啊？
![image](https://user-images.githubusercontent.com/61399616/168553002-ac16df57-ef99-4904-ac7c-b0b7a6b43ee8.png)

**Comment by jerrywgz** [comment]
faster rcnn的输入输出说明可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/EXPORT_MODEL.md#1%E5%AF%BC%E5%87%BA%E6%A8%A1%E8%BE%93%E5%85%A5%E8%BE%93%E5%87%BA%E8%AF%B4%E6%98%8E 这个文档哈

**Comment by wobenxiaoyaoKurt** [comment]
> RCNN模型导出的时候，需要在配置文件中增加`export_onnx: True`；另外paddle2onnx需要使用最新版本
> 
> 可以再参考下这个issue [PaddlePaddle/Paddle2ONNX#699](https://github.com/PaddlePaddle/Paddle2ONNX/issues/699)

您好 我在配置文件faster_rcnn_swin_tiny_fpn_3x_coco.yml中添加了export_onnx: True，可是使用paddle2onnx的时候依然会出现There's 7 ops are not supported yet的错误，paddle2onnx版本为1.0.0，不知道是哪里出错了，请教一下，非常感谢！
