### ISSUE TITLE
ppyoloe对于小目标（比如visdrone数据集）和密集型目标（比如crowdhuman数据集）测试结果如何？

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#5990]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

1  ppyoloe对于小目标（比如visdrone数据集）和密集型目标（比如crowdhuman数据集）测试结果如何？
2  ppyoloe适合检测小目标和密集目标吗？
3  picodet对于小目标和密集目标适合吗？

**Comment by qingqing01** [comment]
1. PP-YOLOE在visdrone 数据参考  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/README_cn.md#%E6%B3%9B%E5%8C%96%E6%80%A7%E9%AA%8C%E8%AF%81 。在CrowdHuman数据集没有专门训练，不过在PP-Humean提供的检测/跟踪模型有使用CrowdHuman数据集。 您也可以专门训练看下。


2. PP-YOLOE对于小目标、密集: 个人觉得可以试下， 小目标和具体场景有关，一些方案也是对数据做处理较多。

3. PP-PicoDet对于小目标、密集: 觉得也可以试下，具体看效果。

通用小目标、密集方案:  如上，小目标上一些对数据做处理较多，比如切图；密集，通用的检测一版也可以试下，效果不好的话，可以加一些针对性的损失函数。

**Comment by lixiangMindSpore** [comment]
> 1. PP-YOLOE在visdrone 数据参考  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/README_cn.md#%E6%B3%9B%E5%8C%96%E6%80%A7%E9%AA%8C%E8%AF%81 。在CrowdHuman数据集没有专门训练，不过在PP-Humean提供的检测/跟踪模型有使用CrowdHuman数据集。 您也可以专门训练看下。
> 2. PP-YOLOE对于小目标、密集: 个人觉得可以试下， 小目标和具体场景有关，一些方案也是对数据做处理较多。
> 3. PP-PicoDet对于小目标、密集: 觉得也可以试下，具体看效果。
> 
> 通用小目标、密集方案: 如上，小目标上一些对数据做处理较多，比如切图；密集，通用的检测一版也可以试下，效果不好的话，可以加一些针对性的损失函数。

您说的关于密集目标检测的针对性损失函数是哪些？

**Comment by jerrywgz** [comment]
针对密集型检测的优化点可以参考下面几种方法：
1. 针对密集检测的label assign方法：https://www.sciencedirect.com/science/article/pii/S0925231221011796
2. 针对密集检测的nms优化：https://arxiv.org/abs/2003.12729
3. 基于sparse rcnn改进的端到端检测算法：https://github.com/megvii-research/Iter-E2EDET

其他可以参考下crowdhuman或者SKU110K上榜单中的方法
