### ISSUE TITLE
fake量化节点

### ISSUE THREAD

**Issue by houjingsong** [PaddlePaddle/PaddleDetection#5994]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问，在paddle里面，ssd模型的动态图导出静态图的时候，head部分的卷积前面没有fake量化节点。但是ssdlite模型动态图导出静态图的时候，head部分的卷积就会有fake量化节点。
**这是什么原因造成的呢？paddle对ssdlite有什么特殊处理吗？如果想主动加上fake节点，有什么办法吗？**

**Comment by yghstill** [comment]
@houjingsong 默认是所有的conv都会加入fake量化节点的，这属于已知问题，我们解决下。

**Comment by w77779999** [comment]
> @houjingsong 默认是所有的conv都会加入fake量化节点的，这属于已知问题，我们解决下。

你好，请问这个问题解决了吗

**Comment by fpjnice** [comment]
您好这个问题解决了吗

**Comment by fpjnice** [comment]
> @houjingsong 默认是所有的conv都会加入fake量化节点的，这属于已知问题，我们解决下。

您好这个问题具体怎么解决呢
