### ISSUE TITLE
static目录下执行infer.py预测时报错no module named 'paddle'

### ISSUE THREAD

**Issue by dragon5944** [PaddlePaddle/PaddleDetection#5995]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

终端在static目录下执行python tools/infer.py预测一张图片，报错No module named 'paddle'
我已经安装好了paddle库，在解释器中能正常import paddle，但只要程序中有import paddle或from paddle import **时，就会报错，无法执行程序，经过在百度搜索尝试后也不行，恳请帮助。

**Comment by jerrywgz** [comment]
检查下paddle安装的python和程序使用python路径是否一致，另外如果在static目录下，需要 export PYTHON_PATH=\`pwd\`
