### ISSUE TITLE
ppyoloe训练

### ISSUE THREAD

**Issue by zhangyingying520** [PaddlePaddle/PaddleDetection#5997]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

麻烦问一下，我用ppyolov2和ppyoloe使用相同的数据集，几乎都是使用套件里的默认配置，为什么ppyolov2能接近0.8，而ppyoloe只有0.5左右

**Comment by jerrywgz** [comment]
已在用户群沟通，辛苦提供下ppyolov2的训练配置和日志

**Comment by zhangyingying520** [comment]
> 已在用户群沟通，辛苦提供下ppyolov2的训练配置和日志

谢谢，已经帮助解决
