### ISSUE TITLE
Detection中无epoch概念？

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#60]
请问其中的周期次数是按照这样计算的吗？
![epoch](https://user-images.githubusercontent.com/45937014/69943343-3f199780-1520-11ea-9c8e-f0d771eefd83.jpg)
如果我的最大迭代次数是18W batch_size=4  图片大约300张训练图片 意思是 300/4=75个epoch？ 还是说 用最大迭代次数18W/300=600个epoch  ？

**Comment by qingqing01** [comment]
@shuxsu 没有epoc的概念,  按照您提供的说明是，如果单卡训练(config里的batch-size是单卡的):

一个epoc是迭代次数: 300/4 = 75轮
18w轮迭代的epoc数: 18w/75 = 2400个epoc

**Comment by shuxsu** [comment]
> @shuxsu 没有epoc的概念, 按照您提供的说明是，如果单卡训练(config里的batch-size是单卡的):
> 
> 一个epoc是迭代次数: 300/4 = 75轮
> 18w轮迭代的epoc数: 18w/75 = 2400个epoc
这个说明文件只是我在网上找到的 我也不知道detection是否是使用这个概念计算epoch

**Comment by qingqing01** [comment]
@shuxsu detection中没有使用epoc数，数据预处理有个epoc的记录，训练的for循环里没有使用。 对于用户，只设置batch_size，以及迭代的最大轮数max_iters即可。
