### ISSUE TITLE
模型合成

### ISSUE THREAD

**Issue by lhy823436493** [PaddlePaddle/PaddleDetection#600]
现在想同时检测车辆和行人，需要同时用到特色模型中车辆检测和行人检测这两个模型，如何将这两个模型合成为一个模型？

**Comment by willthefrog** [comment]
可以尝试将使用同时包含车辆和行人的数据集对模型进行fine tune，可以参考这里的[迁移学习文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md)
