### ISSUE TITLE
使用openvino_infer.py报错

### ISSUE THREAD

**Issue by uuyymilkyl** [PaddlePaddle/PaddleDetection#6000]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

模型是picodet_xs_416_lcnet_coco
input shape设置为 [1,3,416,416]
def __init__(self,
                 input_shape,
                 scale_x,
                 scale_y,
                 strides=[8, 16, 32, 64],
                 score_threshold=0.4,
                 nms_threshold=0.6,
                 nms_top_k=1000,
                 keep_top_k=100):

(pd-2.4) E:\PaddleDetection-release-2.4\deploy\third_engine\demo_openvino\python>python openvino_infer.py --onnx_path E:\PaddleDetection-release-2.4\output_inference\picodet_xs_416_coco_lcnet\pico416_model.onnx
Traceback (most recent call last):
  File "openvino_infer.py", line 267, in <module>
    detect(args.img_path, compiled_model, args.class_label)
  File "openvino_infer.py", line 232, in detect
    np_boxes = nms(decode_boxes, select_scores)
  File "openvino_infer.py", line 168, in __call__
    bboxes = np.concatenate(decode_boxes, axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2704 and the array at index 1 has size 676

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/third_engine/demo_openvino/python#%E7%9C%9F%E5%AE%9E%E5%9B%BE%E7%89%87%E6%B5%8B%E8%AF%95%E7%BD%91%E7%BB%9C%E5%8C%85%E5%90%AB%E5%90%8E%E5%A4%84%E7%90%86%E4%BD%86%E4%B8%8D%E5%8C%85%E5%90%ABnms 在导出模型的时候，需要将网络后处理部分导出，但是不包含nms
