### ISSUE TITLE
训练py端推理都没问题，C++部署推理报错

### ISSUE THREAD

**Issue by tiancailin** [PaddlePaddle/PaddleDetection#6001]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

模型：SOLOv2

数据集：自采集，经x2coco.py转换为COCO格式

训练过程：正常
模型导出：tools\export_model.py正常

模型本身：正常
tools\infer.py正常工作（CPU/GPU）、结果符合预期
deploy\python\infer.py（CPU/GPU）、结果符合预期

CMAKE指令（最后两段不为空会报错）：
CMAKE，顺利执行
cmake . -G "Visual Studio 16 2019" -A x64 -T host=x64 -DWITH_MKL=ON -DCMAKE_BUILD_TYPE=Release -DPADDLE_DIR=D:\001LWM\PaddleDetection\deploy\cpp\Packages\paddle_inference -DPADDLE_LIB_NAME=paddle_inference -DOPENCV_DIR=D:\001LWM\PaddleDetection\deploy\cpp\Packages\opencv -DWITH_GPU=OFF -DCUDA_LIB="" -DCUDNN_LIB=""

VS2019 打开 SLN文件，Ctrl+B build，完成exe以及4个.dll文件的生成（0error，0 warring）

执行的错误代码如下：
"""D:\******\Release>main.exe --model_dir=.\model\r50_enhance\ --image_file=.\img\001.jpg
total images = 1, batch_size = 1, total steps = 1

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Tensor holds the wrong type, it holds int64_t, but desires to be float
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/framework/tensor_impl.h:51)

![001](https://user-images.githubusercontent.com/6028808/168866083-9a0d8f67-f651-46f7-a8b9-407ca82a2221.jpg)
"""

我明确也知道这是个输入数据类型错误，但我并不是C++专长，故此提交此issues

具体环境信息下段描述
issues区有个类似的报错，[https://github.com/PaddlePaddle/PaddleDetection/pull/5300](url)
但是这个py结构已经大改了不少了，我不好定位

### 复现环境 Environment

- PaddlePaddle:2.2.2
- PaddleDetection:release/2.4 
- Python: 3.6.8
- CUDA:11.2
- CUDNN：8.2

openCV:
CPP部署里给出的url，3.4.6

paddle_inference推理库
paddle_inference(2.2.2_cpu_avx_mkl)

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by jerrywgz** [comment]
感谢反馈，目前solov2还没有支持c++部署，我们近期支持下

**Comment by tiancailin** [comment]
感谢回复，期待支持
