### ISSUE TITLE
Have MNN post-processing been finished for picodet-xs?

### ISSUE THREAD

**Issue by hitsz-zuoqi** [PaddlePaddle/PaddleDetection#6003]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Have MNN post-processing been finished for picodet-xs?

**Comment by jerrywgz** [comment]
post-processing is not included in picodet-xs model file and the code could refer to https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/third_engine/demo_mnn/picodet_mnn.cpp#L147
