### ISSUE TITLE
创建自己的重参数class

### ISSUE THREAD

**Issue by sdreamforchen** [PaddlePaddle/PaddleDetection#6004]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

ppyoloe的convert_to_deploy这个函数是在什么条件下调用呢？  我如果新写一个重参数的class。需要怎么修改才能得到正确的结果呢

**Comment by yghstill** [comment]
@sdreamforchen 在模型导出时调用，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/engine/trainer.py#L708
你可以在模型组网中新增相同命名的convert_to_deploy函数即可。

**Comment by sdreamforchen** [comment]
> @sdreamforchen 在模型导出时调用，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/engine/trainer.py#L708 你可以在模型组网中新增相同命名的convert_to_deploy函数即可。

感谢
