### ISSUE TITLE
visualize.py 文件 visualize_pose函数报错

### ISSUE THREAD

**Issue by ff12343** [PaddlePaddle/PaddleDetection#6006]
### 问题描述 Please describe your issue

keypoint topdown_unite_predict时，可视化推理结果报错。
报错信息如下
![image](https://user-images.githubusercontent.com/42758082/169012566-ef8e0b10-79ce-4c5b-94f2-96fe7f0438b2.png)
判断是matplotlib版本问题，更新matplotlib版本到3.4.3依旧报错

**Comment by yghstill** [comment]
@ff12343 这个只是warning，具体的报错是什么呢？
