### ISSUE TITLE
paddledetection(paddleslim)在线训练的问题！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleDetection#6013]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

hi,
1 请问下，为什么paddledetection 库下面有两份几乎同样目录的代码，比如在static里面又出现了重复的目录，见下图
![image](https://user-images.githubusercontent.com/8407513/169266879-0eda2ffe-855a-4365-80eb-505ce1a91486.png)
这是有什么区别吗？
2 另外，在线训练的话，这个工程不需要再以来paddleslim了吗？也就是说slim的一部分代码已经在这个工程里面了，是这样吗？
3 如果在线训练的话，tools/train.py 走的是哪个分支，static还是？train.py 里最终调用trainer.train(FLAGS.eval) 完成训练，但是我没有看到slim的配置 在哪里起作用的，在线量化是要有量化和反量化的操作的，也看不到在哪。反而在paddleslim工程里面看到了quant_aware_with_infermodel.py 这个酷似在线量化训练的文件，但是貌似跟我们的paddledetection没啥关系。能稍微详细讲解下大致流程吗？

BR

**Comment by yghstill** [comment]
@2050airobert 
1. static是指静态图模型，一般使用默认根目录下的动态图模型即可。
2. 动态图下如果想要slim训练，可以参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/slim
3. 在线训练使用tools/train.py脚本即可，如果你的模型是静态图模型才需要进到static下
