### ISSUE TITLE
有什么办法能在验证的时候不保存模型的权重文件吗？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#6022]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

有什么办法能在验证的时候不保存模型的权重文件吗？我希望输出每个epoch结束后的mAP但不想要中途的.pdparams这些文件，保存一个best.pdparams和一个final的就够了

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/engine/callbacks.py#L207-L220

ppdet暂时不提供 不过你可以在代码处修改save的逻辑
