### ISSUE TITLE
Using multiple datasets

### ISSUE THREAD

**Issue by m13ammed** [PaddlePaddle/PaddleDetection#6023]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Is it possible currently to mix multiple datasets and use them for training that has similar classes and in the same format?

**Comment by lyuwenyu** [comment]
目前只支持单个，1. 你可以把数据合成一个格式  2. 或者仿照已有的data source 开发一个新的 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/ppdet/data/source

example: 
https://github.com/lyuwenyu/PaddleDetection/blob/large_scale_model_v1_L/ppdet/data/source/plain.py  
https://github.com/lyuwenyu/PaddleDetection/blob/large_scale_model_v1_L/configs/ppyolo/lst_dataset.yml

**Comment by m13ammed** [comment]
Thank you for the feedback this was helpful
