### ISSUE TITLE
目标跟踪deepsort

### ISSUE THREAD

**Issue by lhy823436493** [PaddlePaddle/PaddleDetection#603]
已经能够目标检测，怎么进一步实现目标跟踪，paddle有没有类似deepsort的实现方式。

**Comment by FDInSky** [comment]
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/tracking 参考这里，有一部分目标跟踪的算法

**Comment by qingqing01** [comment]
@lhy823436493 目前没有提供多目标跟踪的算法， https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/tracking  里是单目标跟踪方法。
