### ISSUE TITLE
picodet使用tools/infer.py推理报错 AttributeError: 'COCODataSet' object has no attribute 'set_images'

### ISSUE THREAD

**Issue by hobeter** [PaddlePaddle/PaddleDetection#6030]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

用tools/infer.py推理，命令如下
```CUDA_VISIBLE_DEVICES=0 python tools/infer.py -c picodet_s_320_coco_lcnet.yml -o weights=model_final.pdparams --infer_dir=images ```
报错如下
<img width="747" alt="截屏2022-05-22 18 36 56" src="https://user-images.githubusercontent.com/55823642/169691199-0ca38ea1-5e68-4683-b767-0cfada144852.png">
test reader如下
<img width="725" alt="截屏2022-05-22 18 37 35" src="https://user-images.githubusercontent.com/55823642/169691220-999cceeb-6793-499f-9196-6d0d73be3734.png">
请问该怎么解决啊🧐
感谢🙏

**Comment by nemonameless** [comment]
请贴下数据集的配置，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/datasets/coco_detection.yml#L17，
大概率是你的TestDataset: 配置成了COCODataSet ，应该是ImageFolder

**Comment by hobeter** [comment]
啊，确实，十分感谢
