### ISSUE TITLE
使用paddleLite推理部署模型报错input_names_.size()>offset

### ISSUE THREAD

**Issue by dragon5944** [PaddlePaddle/PaddleDetection#6031]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

         在paddleDetection/static下训练正常ssd_mobilenet_roadsign，使用export_model.py正常导出inference模型，使用opt转换模型设置valid_places为arm，生成.nb文件，在paddlelite上推理时报错，错误信息**input_names.size()>offset,_the network has 1 inputs,the offset should be less than this.**
         而用相同的发方法在Detection主目录下训练生成的nb文件可以正常推理。
         另外在用netron可视化nb文件时发现，static目录下生成的nb文件其第一个节点是0，而Detection主目录下生成的nb文件其第一个节点是1，想知道是不是这里的区别导致的错误。

**Comment by nemonameless** [comment]
PaddleDetection/static下的是以前的静态图版本代码，PaddleDetection/下的主目录是动态图。建议使用动态图。
