### ISSUE TITLE
分布式训练重定向输出BUG

### ISSUE THREAD

**Issue by yuxiaoz** [PaddlePaddle/PaddleDetection#6036]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

在同时分布式训练多个程序时，使用nohup ... >> xx.log 2>&1 &命令将它们挂在后台运行，分别将日志输出重定向在各自的log文件中。但是，发现每个log文件中均有所有训练任务的重定向输出。

如果不采用分布式训练，则没发现这个问题。

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ghostxsl** [comment]
分布式训练可以使用--log_dir指定log存放位置
