### ISSUE TITLE
YOLOX训练问题

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#6038]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

1.很久没用paddleDetection发现出来了很多新的功能，请问有新功能的介绍文档吗？比如train.py中新加的--fleet和--amp这两个的作用，在训练YOLOX的时候查看文档，写了加这俩个参数可以避免显存溢出。有没有比较完整的教程视频或者文档？

2.YOLOX-nano训练时，调整batch-size仅仅只增加显存，GPU占用率却不提高，训练速度很慢是为什么？有什么办法提高GPU占用率吗？

3.单GPU训练时配置文件中worker_num的数量是不是只能为0？是不是越高训练速度也越快？

4.出现了一些新的xpu,npu这些东西，请问是干什么用的？

5.请问PaddleDetection有yolov5模型吗？我看各种文档里都对比了yolov5但是好像没有新增这个配置文件

**Comment by ghostxsl** [comment]
1. --fleet参数是调用更高层的paddle分布式api进行分布式训练，--amp是启用混合精度训练
2. 导致训练性能瓶颈的原因可能是dataloader加载数据效率低于GPU计算效率，也可能是模型组网使用的OP欠佳等原因，我们的技术人员需要进一步的排查。提高GPU利用率的手段通常是提升dataloader加载数据的效率等
3. worker_num对应的是多子线程dataloader中的线程数，在模型训练时，读取数据和GPU计算是异步进行的，设置worker_num跟GPU数量无关系，一般而言，增大worker_num会使得数据加载变快，训练变快，但是不能无限增大，这要视具体的硬件资源和GPU计算能力来调试
4. xpu和npu均是新硬件，可以理解成这些就是一种新的“GPU”
5. 由于yolov5使用GPL协议，与PaddleDetection的开源协议有冲突，不在计划内，但是我们在近期内会引入第三方开发者基于PaddleDetection贡献的yolov5代码库，也是经过我们严格测试和code review的，欢迎您届时使用～
