### ISSUE TITLE
ppyoloe剪裁

### ISSUE THREAD

**Issue by simon-sxx** [PaddlePaddle/PaddleDetection#6039]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

想对ppyoloe模型进行剪裁，但是PaddleDetection里面没有相应的配置文件，请问可以提供ppyoloe的剪裁配置吗？如果要自己配置的话，我应该进行哪些操作流程呢

**Comment by ghostxsl** [comment]
可以参考slim文档：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/slim
参考ppyolo_r50vd的剪裁yaml：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/slim/prune/ppyolo_r50vd_prune_fpgm.yml

**Comment by simon-sxx** [comment]
@ghostxsl 请问我应该怎样得出自己模型中的剪裁层和裁剪率呢？这些参数可以直接使用在ppyoloe上吗

pruned_params: ['conv2d_56.w_0', 'conv2d_57.w_0', 'conv2d_58.w_0',
                  'conv2d_59.w_0', 'conv2d_60.w_0', 'conv2d_61.w_0',
                  'conv2d_63.w_0', 'conv2d_64.w_0', 'conv2d_65.w_0',
                  'conv2d_66.w_0', 'conv2d_67.w_0', 'conv2d_68.w_0',
                  'conv2d_70.w_0', 'conv2d_71.w_0', 'conv2d_72.w_0',
                  'conv2d_73.w_0', 'conv2d_74.w_0', 'conv2d_75.w_0']
  pruned_ratios: [0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.875,0.875,0.875,0.875,0.875,0.875]

**Comment by railgun-zyy** [comment]
请问你剪裁成功了吗？我报错AssertionError: Can not pruning axis that will be squeezed.
