### ISSUE TITLE
YOLOV4有动态图的配置文件吗？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#6046]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

YOLOV4有动态图的配置文件吗？可不可以直接把静态图的配置文件稍微修改挪到动态图使用？还是说要重新在动态图写architecture和head什么的。

**Comment by zhiboniu** [comment]
你好，YOLOV4并没有再动态图中适配，如果要用的话是需要自己实现architecture和head的，同时静态图的配置文件跟动态图有些差别，不能直接挪用，需要修改。
推荐使用服务器端的ppyoloe和移动端的picodet，具有更好的性能。
