### ISSUE TITLE
训练时模型保存路径BUG

### ISSUE THREAD

**Issue by yuxiaoz** [PaddlePaddle/PaddleDetection#6047]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

在启动模型训练时，在config文件中设定了模型的存储路径，但是模型保存的路径并没有根据设置路径来，反而是保存在以config文件为名称的文件夹下。

比如在[PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection)/[configs](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs)/[ppyoloe](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe)/ppyoloe_crn_s_300e_coco.yml设置文件中，
如下所示：
```python
log_iter: 100
snapshot_epoch: 10
# weights: output/ppyoloe_crn_s_300e_coco/model_final
weights: output/my_checkpoints/model_final
```
最终，模型没有被保存在output/my_checkpoints下，而还是存储在了output/ppyoloe_crn_s_300e_coco下面。

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by w77779999** [comment]
这个weights在评估的时候用于设置你评估所需权重存放的位置，本来就不是保存路径

**Comment by yuxiaoz** [comment]
> 这个weights在评估的时候用于设置你评估所需权重存放的位置，本来就不是保存路径

那只能通过改变配置文件名称实现模型保存路径变化了哈。

**Comment by w77779999** [comment]
或者你可以看一下代码里面具体哪一段读取了文件名并设置成了保存路径然后自己改，图简单的话改文件名确实ok

**Comment by zhiboniu** [comment]
![image](https://user-images.githubusercontent.com/31800336/169980510-8dd17cdf-edf7-4baf-9f9c-e371ae2ecb25.png)
你好，通过排查代码看起来应该是通过这个save_dir设置的，你可以试试。
上面那个确实是评估的时候加载权重用的
