### ISSUE TITLE
module 'ppdet' has no attribute 'data'

### ISSUE THREAD

**Issue by tuya-yu** [PaddlePaddle/PaddleDetection#6049]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

################已执行#################
# 克隆PaddleDetection仓库
cd <path/to/clone/PaddleDetection>
git clone https://github.com/PaddlePaddle/PaddleDetection.git

# 安装其他依赖
cd PaddleDetection
pip install -r requirements.txt

# 编译安装paddledet
python setup.py install
#############
在执行 python ppdet/modeling/tests/test_architectures.py
###################BUG################################
File "\paddledet-2.4.0-py3.6.egg\ppdet\data\source\dataset.py", line 26, in <module>
    import ppdet.data.source as source
AttributeError: module 'ppdet' has no attribute 'data'

### 复现环境 Environment

paddle 2.2.2
[PaddleDetection] 2.4

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
你好，看起来当前执行目录在ppdet文件夹下，有可能python混淆了当前路径和安装的ppdet路径，请换一下文件夹试试呢。

**Comment by Weizhongjin** [comment]
一样的问题，看了半天找不到解决原因

**Comment by Weizhongjin** [comment]
将 ppdet/data/source/dataset.py 中的第25行
`import ppdet.data.source as source`
改成
`from ppdet.data import source as source`
我也不知道为什么。但就是可以了

**Comment by jerrywgz** [comment]
目前验证在python3.6下会有这个问题，其他python版本是ok的，已经提pr修复了，感谢反馈https://github.com/PaddlePaddle/PaddleDetection/pull/6056
