### ISSUE TITLE
在Jetson NX中 使用PP-TinyPose推理单张图片，8G内存占用了7G

### ISSUE THREAD

**Issue by LUOQING1994** [PaddlePaddle/PaddleDetection#6053]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在Jetson NX中，我按照PP-TinyPose的文档，成功运行了示例，但我发现推理单张1080P图片，8G内存占用了7G，请问该如何降低内存空间呢？

**Comment by zoooo0820** [comment]
你好，问题已收到，我们找机器复现一下，完成后在这里同步情况

**Comment by zoooo0820** [comment]
@LUOQING1994 
你好，这个问题经过与paddle inference相关同学沟通，因为jetson内存是共用的，不限于tinypose这一个具体模型，这个表现是正常的。
