### ISSUE TITLE
训练的时候加上--eval就会报错 什么原因啊

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleDetection#6058]
### 问题描述 Please describe your issue

![image](https://user-images.githubusercontent.com/77281977/170198996-ba3bce0f-7c13-452e-a044-0cf21c2a33bb.png)

**Comment by zoooo0820** [comment]
看起来是自定义数据集，类别上是几类？另外设置上具体做了哪些改动呢
