### ISSUE TITLE
Some warnings when choosing --amp in training 

### ISSUE THREAD

**Issue by AI-Passionner** [PaddlePaddle/PaddleDetection#6063]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

I0525 15:25:52.560097  7904 layout_autotune.cc:28] Layout AutoTuning is not available.
I0525 15:25:52.560097  7904 layout_autotune.cc:28] Layout AutoTuning is not available.
I0525 15:25:52.560097  7904 layout_autotune.cc:28] Layout AutoTuning is not available.
I0525 15:25:52.560097  7904 layout_autotune.cc:28] Layout AutoTuning is not available.
I0525 15:25:52.561080  7904 layout_autotune.cc:28] Layout AutoTuning is not available.
I0525 15:25:52.561080  7904 layout_autotune.cc:28] Layout AutoTuning is not available.
I0525 15:25:52.561080  7904 layout_autotune.cc:28] Layout AutoTuning is not available.
....

**Comment by lyuwenyu** [comment]
请问一下paddle用的什么版本，这个训练那个模型出现的 有完整的log嘛

**Comment by zhangting2020** [comment]
这个是amp的autotuning功能，应该是因为你的GPU不支持TensorCore，所以不能自动调优，打印出来了这个日志，不影响训练功能。

只是这条日志的级别需要调整下，我们后续会修复。

**Comment by Tim4AI** [comment]
@zhangting2020 日志等级怎么调整，我也遇到一样的问题，刷很多看不到其他日志

**Comment by wenzonghui** [comment]
我也遇到同样的问题，请问大佬们都怎么解决的？

**Comment by zhangting2020** [comment]
我们在该功能的日志等级上设置存在问题，下个版本会修复。目前可以通过环境变量，避免日志的输出

export GLOG_minloglevel=2

**Comment by nemonameless** [comment]
paddle2.3.0或develop版本暂时不推荐amp训练，如需amp训练请使用paddle2.2.2版本。
