### ISSUE TITLE
ppyoloe蒸馏

### ISSUE THREAD

**Issue by simon-sxx** [PaddlePaddle/PaddleDetection#6064]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

想要对ppyoloe进行蒸馏，但是PaddleDetection里面只有YOLOV3的配置文件，直接使用会报错，而且找不到相关的 蒸馏 loss ,请问我该怎么配置呢，（蒸馏文档太过简略）？

**Comment by qingqing01** [comment]
不同模型结构蒸馏会有点差异，当前还没适配PP-YOLOE。

关于PP-YOLOE，如果对网络输出可以在这个文件里获取 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/modeling/heads/ppyoloe_head.py
