### ISSUE TITLE
solov2_r50_enhance得到的精度低。

### ISSUE THREAD

**Issue by wudi-98** [PaddlePaddle/PaddleDetection#6071]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddledetection中solov2_r50_enhance训练得到的精度远比原作者提供的solov2_r50的精度要低。
训练过程和识别结果好像都没有什么问题，不明白为什么最后eval.py得出的精度很低？是评估方法不一样吗？还是训练中有什么容易被忽视的问题？

**Comment by qingqing01** [comment]
您是什么数据集吗？如果是COCO数据集的话，是否使用8卡进行训练？有做什么更改吗？

**Comment by wudi-98** [comment]
> 

我是使用的COCO数据集，使用的单卡训练，只修改了配置文件的类别数（+1），学习率（0.00125）。

**Comment by zoooo0820** [comment]
你好，有两个地方想确认一下
- coco这里新加的一类是什么类别呢
- 是同样按上述配置都进行训练后，solov2_r50_enhance比solov2_r50低，还是只是比放出来的solov2_r50预训练模型低呢？

另外从问题描述看，预测结果是正常的但是eval指标不正常是吗？ 这里方便的话可以贴一下eval的结果方便debug。

**Comment by wudi-98** [comment]
> 你好，有两个地方想确认一下
> 
>     * coco这里新加的一类是什么类别呢
> 
>     * 是同样按上述配置都进行训练后，solov2_r50_enhance比solov2_r50低，还是只是比放出来的solov2_r50预训练模型低呢？
> 
> 
> 另外从问题描述看，预测结果是正常的但是eval指标不正常是吗？ 这里方便的话可以贴一下eval的结果方便debug。

你好，增加的是背景这个类别，加上背景已经16个类别。自己训练的solov2_r50_enhance精度低。推理了几张图，结果都很正常，但是eval推理的精度却非常低。

**Comment by zoooo0820** [comment]
所以类别一共是16类，这里在eval的时候加上--class选项呢，其余未训练的类别会拖低指标

**Comment by wudi-98** [comment]
> 所以类别一共是16类，这里在eval的时候加上--class选项呢，其余未训练的类别会拖低指标

但是出来的结果还是15个类。
结果如下：
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.231
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.356
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.240
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.308
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.153
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.310
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.327
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.327
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
[05/27 12:22:25] ppdet.metrics.coco_utils INFO: Per-category of segm AP: 
+----------------+-------+--------------------+-------+---------------+-------+
| category       | AP    | category           | AP    | category      | AP    |
+----------------+-------+--------------------+-------+---------------+-------+
| Domestic waste | 0.045 | Construction waste | 0.048 | forest_empty  | 0.115 |
| road_surface   | 0.420 | illegal_building   | 0.366 | Interplanting | 0.247 |
| Uncovered_GH   | 0.405 | river              | 0.625 | greenhouse    | 0.796 |
| Rubble         | 0.060 | Land_cover         | 0.207 | Dead trees    | 0.000 |
| leaning-tree   | 0.000 | Gravel             | 0.125 | forest_empty2 | 0.000 |
+----------------+-------+--------------------+-------+---------------+-------+
[05/27 12:22:25] ppdet.metrics.coco_utils INFO: per-category PR curve has output to segm_pr_curve folder.
[05/27 12:22:26] ppdet.engine INFO: Total sample number: 641, averge FPS: 3.9755271499400178

**Comment by zoooo0820** [comment]
这些类别不是coco中的类别吧，coco是80类吧，看起来有几个类完全没有学习到，另外现在动态图版本的训练中不需要增加背景类了。这里具体对数据和标签做了哪些处理呢。另外原作者提供的预训练模型精度在这个数据集上是什么样呢？

**Comment by wudi-98** [comment]
> 这些类别不是coco中的类别吧，coco是80类吧，看起来有几个类完全没有学习到，另外现在动态图版本的训练中不需要增加背景类了。这里具体对数据和标签做了哪些处理呢。另外原作者提供的预训练模型精度在这个数据集上是什么样呢？

这是我自己的数据集，标签文件是按照coco的格式写的。在原作者提供的solov2_r50精度为47%（IoU=0.50:0.95）。

**Comment by zoooo0820** [comment]
你好，想请问下原作者模型的测出的AP47，是使用作者的代码自己训练得到的吗？如果是的话，可以也尝试直接训练下我们库中的SOLOv2_r50模型。
另外这里需要去除背景类（这个数据集即是15类就可以了）再迭代一版试下。
