### ISSUE TITLE
请问有没有打包好的docker镜像tar包

### ISSUE THREAD

**Issue by xiaozhaxie777** [PaddlePaddle/PaddleDetection#6074]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在官网上看都是要自己docker pull下来，docker hub也是pull，服务器没外网很尴尬，又没有linux能联网的电脑，没办法pull，想求一个paddle detection的tar包下载链接。谢谢。

**Comment by qingqing01** [comment]
PaddleDetection包的话，您可以Github或者Gitee(国内网速快)下载zip包吧。
<img width="374" alt="图片" src="https://user-images.githubusercontent.com/7845005/170614260-ec788154-6fa8-4e8e-9f6e-2e01c16307f5.png">
