### ISSUE TITLE
关于PP-TinyPose推理耗时的问题

### ISSUE THREAD

**Issue by thgpddl** [PaddlePaddle/PaddleDetection#6078]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在阅览文档是看到PP TinyPose的推理耗时如连接中所示：
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/keypoint/tiny_pose#%E5%85%B3%E9%94%AE%E7%82%B9%E6%A3%80%E6%B5%8B%E6%A8%A1%E5%9E%8B
该单人耗时确实惊艳到我，但同时我又看到一个更详细的推理耗时信息：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/keypoint/KeypointBenchmark.md#benchmark-on-server
在这个连接中注明了使用了“000000014439.jpg”这种图片，根据我的测试，改图包含了6个被检测到的行人，也即意味着一个[6,3,128,96]的输入耗时/6才是连接中所说的“单人耗时”，那么对于一次推理（总耗时，不是平均，并且按照单人耗时4.57ms计算）耗时也达到了27ms左右。这个一次耗时针对只有1个人的图片耗时也是在30ms左右。

实际上比如在[mediapipe中的pose预测](https://google.github.io/mediapipe/solutions/pose#:~:text=We%20designed%20our%20models%20specifically%20for%20live%20perception%20use%20cases%2C%20so%20all%20of%20them%20work%20in%20real%2Dtime%20on%20the%20majority%20of%20modern%20devices.)，在MacBook Pro (15-inch 2017)+full版本也能够达到这样的速度。

那么请问TT-TinyPose的优势在哪里？
并且我要实现实时的单人pose预测服务器请求，如何才能极致降低推理延时？

**Comment by zhiboniu** [comment]
你好，
TinyPose是Top-Down方案的模型，因此其耗时与人数成正比，在多人场景和单人场景下并不是一样的。
其总得耗时时间是4.3ms(picodet) + 4.57ms(tinypose)*人数。因此单人时其耗时是8.87ms而不是27ms。
上述时间是在骁龙865上开启benchmark测速得到。

tinypose的优势，可以从两个角度说明：
1）其时间可以动态调整，人数多时与mediapipe相当，人数少时耗时成比例减少。
2）在人数多的场景下，其模型精度仍然可以保持较高的水平，并不会急剧下降。

关于极致降低推理延时的方法，tinypose实际就是这方面的一个典型。可以参考tinypose设计思路，主要从方案、模型、部署3个环节优化，可以参考ppt中的介绍：https://aistudio.baidu.com/aistudio/education/lessonvideo/1980630
