### ISSUE TITLE
模型库是否有yolov4与yolov5的模型复现？

### ISSUE THREAD

**Issue by isLiuHao** [PaddlePaddle/PaddleDetection#6079]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问目前是没有yolo4与yolo5的模型复现吗

**Comment by nemonameless** [comment]
yolov4有静态图版本：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/static/configs/yolov4
yolov5由于开源协议无法加入主分支，目前暂时有试用版：https://github.com/nemonameless/PaddleDetection_YOLOv5/tree/main/configs/yolov5

推荐使用[YOLOX](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/yolox)、[PPYOLOE](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe)、[Picodet](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/picodet)

**Comment by nemonameless** [comment]
https://github.com/nemonameless/PaddleDetection_YOLOSeries  已支持。
也可以看宣传稿了解下 https://mp.weixin.qq.com/s/yesNqqaf5bvLERWEgBWMwA
