### ISSUE TITLE
剪枝量化联合策略的模型导出问题

### ISSUE THREAD

**Issue by Jiashuhao518** [PaddlePaddle/PaddleDetection#6080]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在ppdet/slim/_init_.py下构建了一个剪枝和量化的联合策略（先剪枝后量化），可以正常train，eval，但是不能导出，我看了trainer下的导出代码，剪枝或者量化的导出api不能同时实现，我现在想实现能正常导出经过剪枝量化后的模型，该怎么修改相关代码，谢谢！

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/slim/prune.py#L90 可以参考下这部分代码，目前develop分支已经支持了剪枝量化

**Comment by czczmr** [comment]
是实现了，但是导出遇到了问题
