### ISSUE TITLE
C++部署：找不到paddle2onnx.dll

### ISSUE THREAD

**Issue by terrancraft** [PaddlePaddle/PaddleDetection#6081]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

您好，参照deploy/cpp里面部署教程，cmake和编译都通过了。
但推理时报错 找到paadle2onnx.dll的动态库

步骤如下
1. 我用的cmake指令：
cmake . -G "Visual Studio 16 2019" -A x64 -T host=x64 -DWITH_GPU=ON -DWITH_MKL=ON -DCMAKE_BUILD_TYPE=Release -DCUDA_LIB=D:\CUDA\cuda11.2\lib\x64 -DCUDNN_LIB=D:\CUDA\cuda11.2\lib\x64 -DPADDLE_DIR=D:\GitSource\paddle_inference\paddle_inference_install_dir -DPADDLE_LIB_NAME=paddle_inference -DOPENCV_DIR=D:\opencv -DWITH_KEYPOINT=OFF

2. 使用visual studio 2019 enterprise release 生成
3. 执行指令推理：
main.exe --model_dir=.\output_inference\picodet_l_640_coco --image_file=.\dbdb_jb5.jpeg 
<img width="359" alt="微信图片_20220528142436" src="https://user-images.githubusercontent.com/51820927/170813300-71d4bc5f-7ad6-43e3-b39d-42b789c813c4.png">

望解答 谢谢！

### 复现环境 Environment

- Win10系统64位
- rtx 3090
- Paddleinference(avx_mkl_cuda11.2_cudnn8.2_avx_mkl-trt8.0.1.6) 下载自(https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows)
- CUDA11.2
- cudnn 8.2
- CMAKE 3.23
- Visual Studio 2019 Enterprise
- opencv 3.4.6

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by jerrywgz** [comment]
PADDLE_LIB_NAME 需要设置为libpaddle_inference

**Comment by dengmingD** [comment]
paddle_inference\third_party\install\paddle2onnx\lib

**Comment by dengmingD** [comment]
这个目录下有，copy到Release下

**Comment by terrancraft** [comment]
谢谢 我做一下尝试

**Comment by JackDance** [comment]
同问，也是在这遇到了同样的问题，“PADDLE_LIB_NAME 需要设置为libpaddle_inference”也不行，请问解决了吗大佬 @terrancraft

**Comment by JackDance** [comment]
同问，这个问题该如何解决呢

**Comment by ninjasz** [comment]
> PADDLE_LIB_NAME 需要设置为libpaddle_inference

你怎么这么确定？事实上改成这个，根本编译不过。

**Comment by ninjasz** [comment]
这个问题已解决，就是缺少paddle2onnx.dll和onnxruntime.dll
