### ISSUE TITLE
用PaddleDetection训练picodet增强版出现内存泄漏

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#6082]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

用PaddleDetection训练picodet增强版cpu内存直线上升，大概一个多小时就占满了64G内存，请问大佬这是什么原因

**Comment by jerrywgz** [comment]
麻烦提供下训练环境和版本信息，另外可以将reader配置文件中的worker_num设置为0观察下

**Comment by Dandelion111** [comment]
> 麻烦提供下训练环境和版本信息，另外可以将reader配置文件中的worker_num设置为0观察下

你好，训练环境：paddlepaddle-gpu 2.2.2 
python3.7
版本：最新的PaddleDetection2.4
我试了一下训练ppyoloe基本没有这个问题，之前都是用小数据集训练picodet没发现这个问题，现在用3000张数据集训练才发现的

**Comment by Dandelion111** [comment]
> 麻烦提供下训练环境和版本信息，另外可以将reader配置文件中的worker_num设置为0观察下

你好，我试了一下worker_num为0的时候也有这个情况
