### ISSUE TITLE
使用maskrcnn进行实例分割 如何显示出来 网络最后提取的特征？

### ISSUE THREAD

**Issue by weiluonika** [PaddlePaddle/PaddleDetection#6083]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用maskrcnn进行实例分割 如何显示出来 网络最后提取的特征？

**Comment by jerrywgz** [comment]
mask rcnn最后提取的特征在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/modeling/heads/mask_head.py#L193 中，需要添加下可视化代码

**Comment by weiluonika** [comment]
> mask rcnn最后提取的特征在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/modeling/heads/mask_head.py#L193 中，需要添加下可视化代码

请问一下 可视化代码有没有相关参考文档？

**Comment by jerrywgz** [comment]
将特征图按channel纬度叠加，然后映射到0-255区间就可以
