### ISSUE TITLE
ppyolo真的没问题吗？所有PPYOLO下的配置文件都报nan错

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#6084]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/40875421/170825974-e61ff6d5-f522-42e2-8a99-dda6f1c811e6.png)
我缩小了学习率loss值也变成了nan，所有的ppyolo的配置文件全部都有这个问题，为什么？

我修改了batch_size=1,snapshot_epoch=1，所有的学习率减半大概是0.0025,训练自己的数据集，使用的coco数据集

**Comment by nemonameless** [comment]
bs和lr修改不当。请先确保修改正确了再训练。
请按照[modelzoo](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe#model-zoo)下面的公式：
PP-YOLOE模型训练过程中使用8 GPUs进行混合精度训练，如果**GPU卡数**或者**batch size**发生了改变，你需要按照公式 **lr<sub>new</sub> = lr<sub>default</sub> * (batch_size<sub>new</sub> * GPU_number<sub>new</sub>) / (batch_size<sub>default</sub> * GPU_number<sub>default</sub>)** 调整学习率。
