### ISSUE TITLE
导出模型时报错AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by 1abourer** [PaddlePaddle/PaddleDetection#6086]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

导出hrnet_w32_384x288的模型时报错
PS D:\BS\again\final\work\PaddleDetection> python tools/export_model.py -c configs/keypoint/hrnet/hrnet_w32_384x288.yml -o weights = output/hrnet_w32_384x288/model_final.pdparams
C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\tensor\creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "tools/export_model.py", line 108, in <module>
    main()
  File "tools/export_model.py", line 93, in main
    merge_config(FLAGS.opt)
  File "D:\BS\again\final\work\PaddleDetection\ppdet\core\workspace.py", line 154, in merge_config
    return dict_merge(dct, config)
  File "D:\BS\again\final\work\PaddleDetection\ppdet\core\workspace.py", line 133, in dict_merge
    for k, v in merge_dct.items(): #merge_dct.items
AttributeError: 'list' object has no attribute 'items'

**Comment by jerrywgz** [comment]
-o weights后面的等号前后不加空格
