### ISSUE TITLE
模型导出

### ISSUE THREAD

**Issue by simon-sxx** [PaddlePaddle/PaddleDetection#6088]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

 在进行模型导出时，去掉TestReader.fuse_normalize=true字段，为什么模型预测时间（不算预处理时间）没有改变甚至略有增加？

**Comment by nemonameless** [comment]
fuse_normalize降的只是reader里的数据预处理NormalizeImage的耗时，模型预测时间不变的，略有增加应该是正常波动。
