### ISSUE TITLE
多个目标检测模型，如何并行检测同一张图片，且将结果合并，paddledetection是否有相关预测方案？

### ISSUE THREAD

**Issue by ALixuhui** [PaddlePaddle/PaddleDetection#6090]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

第一个问题：我现在有两个目标检测的模型，模型Ａ和模型B，然后这两个模型可以分别预测不同的类别，如果想要这两个模型预测同一张图片，paddledetection有什么并行预测的方案么？

第二个问题：我有两个数据集，数据集A只标注了车辆，数据集B只标注了交通标志。请问这两份数据能否同时训练出一个模型，然后用这一个模型直接预测一张图片中的车辆+交通标志信息？

谢谢~

**Comment by wangxinxin08** [comment]
可以参考下这个API https://www.paddlepaddle.org.cn/inference/v2.3/api_reference/python_api_doc/PredictorPool.html, 自己编写下代码试下
