### ISSUE TITLE
blazeface转onnx失败，请问你们能转成功吗

### ISSUE THREAD

**Issue by cv-nlp** [PaddlePaddle/PaddleDetection#6091]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

ppdetection/lib/python3.8/site-packages/onnx/helper.py:343: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  is_iterable = isinstance(value, collections.Iterable)
2022-05-30 16:35:22 [ERROR]     [PriorBox]Fixed shape is required, refer this doc for more information: https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/FAQ.md

按照这个链接的并没有解决

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
感谢您的反馈，我们后期验证并排期修复下
