### ISSUE TITLE
C++ inference on NX

### ISSUE THREAD

**Issue by m13ammed** [PaddlePaddle/PaddleDetection#6092]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

The provided compiled paddle inference is available only for Jetapck 4.3, since Jetson NX is not supported on Jetpack 4.3 I am unable to use the cpp inference (paddle fluid) on the NX. Additionally using higher jetpack version would cause conflicts with the pre-compiled package since jetpack 4.4+ has CudNN 8+ and TensorRT 7.  

Can you provide me with the instruction of how you did compile the paddle fluid / paddle inference  so that I can prepare a docker image for the cpp inference on the NX

**Comment by wangxinxin08** [comment]
you can download paddle inference library from https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#c, which supports jetpack 4.4, 4.5 and 4.6.

**Comment by m13ammed** [comment]
That's great. Is there also a link for a compatible opencv version? Or the TX2_JetPack4.3_opencv_3.4.6_gcc7.5.0.tar.gz is still compatible for newer jetpacks and the NX ?

**Comment by wangxinxin08** [comment]
Maybe you can compile compile opencv from source code on your jetson

**Comment by m13ammed** [comment]
It worked thank you!
