### ISSUE TITLE
Windows下使用tensorRT加速ppyoloel出现的问题

### ISSUE THREAD

**Issue by gouzi-tu** [PaddlePaddle/PaddleDetection#6094]
----

1、环境：Windows + cuda10.1， cudnn7.6.5， tensorRT6.0.15, paddlepaddle-gpu=2.3.0.post101，
2、操作步骤：
- 1、python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_300e_coco.pdparams trt=True
-  2、python deploy/python/infer.py --model_dir=output_inference/ppyoloe_crn_l_300e_coco --camera_id=0 --device=gpu  

3、运行结果：可以打开摄像头显示检测画面
4、当使用tensorRT进行加速的时候，使用了这个命令：python deploy/python/infer.py --model_dir=output_inference/ppyoloe_crn_l_300e_coco --camera_id=0 --device=gpu  --run_mode=trt_fp16
5、运行结果：
-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: 0
cpu_threads: 1
device: gpu
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: None
image_file: None
model_dir: output_inference/ppyoloe_crn_l_300e_coco
output_dir: output
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: trt_fp16
save_images: False
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dark: True
use_gpu: False
video_file: None
window_size: 50
------------------------------------------

-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
在这个界面等待了数分钟后程序就停止了，也没有报任何错误。

===============================================

您好，这是我哪里操作不当吗，希望得到回复，谢谢。

**Comment by wangxinxin08** [comment]
set GLOG_v=5再运行下看看

**Comment by gouzi-tu** [comment]
在哪里设置 “set GLOG_v=5” 呀

**Comment by wangxinxin08** [comment]
命令行直接输入

**Comment by gouzi-tu** [comment]
还是和原来一样，如下图
![image](https://user-images.githubusercontent.com/56339140/171079566-e8f59e03-0de7-4a87-b854-bc4bc2e4db14.png)

**Comment by wangxinxin08** [comment]
其他的模型TRT能够运行吗？如果不能运行，你安装的PaddlePaddle是不包含TensorRT的，建议安装带TensorRT的PaddlePaddle用作推理。另外需要确保TensorRT安装窃路径正确设置，具体参考文档https://www.paddlepaddle.org.cn/inference/v2.3/optimize/paddle_trt.html
