### ISSUE TITLE
在C++部署进行预测时首张图片和之后图片的速度差异很大

### ISSUE THREAD

**Issue by Heimdall-Nss** [PaddlePaddle/PaddleDetection#6099]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我发现模型在测试第一张图片或者单张图片测试的时候会比一批图片处理(除去第一张)的速度慢很多，这种情况是因为模型加载不可避免的吗？请问如何正确测试一张图片的预测时间呢

**Comment by lyuwenyu** [comment]
测试模型时间的话你需要把 加载时间去掉 另外加上warmup 多次求平均 不然的话波动很大

**Comment by njuptzwt** [comment]
> 测试模型时间的话你需要把 加载时间去掉 另外加上warmup 多次求平均 不然的话波动很大

想问一下，我在测单张图片的时候，发现dataloader加载的这一过程远比预测的时间要长？请问dataloader这边可以做什么优化能够对单张图片快速加载预测呢？

**Comment by wq1530825108** [comment]
请问你这个问题后面有解决吗？第一张图预测时间长这个还好，关键如果单张预测的间隔拉长，这种情况预测的时间长且不稳定 ， 这个在工业现场其实挺头疼的
