### ISSUE TITLE
文档中存在404链接

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/PaddleDetection#6101]
### 文档链接&描述 Document Links & Description

[该页面](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/docs/tutorials/GETTING_STARTED_cn.md#10-%E9%A2%84%E6%B5%8B%E9%83%A8%E7%BD%B2)中的[Python端预测部署](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/python.md)链接404了

### 请提出你的建议 Please give your suggestion

根据文档上下文来看，应该是[该页面](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/python)

**Comment by lyuwenyu** [comment]
收到 这个指的是https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/python，，，   之后会修复或者感兴趣的话你也可以提个PR修改下
