### ISSUE TITLE
对Dataloader的疑问

### ISSUE THREAD

**Issue by XA-hyy** [PaddlePaddle/PaddleDetection#6103]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，请问训练模型时，我想在训练几个epoch后再动态新增加一批数据继续训练，有好的实现方法吗？ 我尝试增加数据，但是在使用num_worker！=0，即多进程加载数据的方法时，在外部改变dataset的图像是无效的。

**Comment by lyuwenyu** [comment]
这个目前不支持的  给个思路是修改Decode的代码  加上逻辑  比如到达epoch之后 去固定地方读取图片和gt
