### ISSUE TITLE
ppyoloe没问题吗？

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/PaddleDetection#6104]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 错误信息
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 2100, 2] and the shape of Y = [8400, 2]. Received [2100] in X is not equal to [8400] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
  [operator < elementwise_add > error]
### 前提
1.自己的数据集在其他配置文件下均可以训练，比如ppyolo,faster rcnn等
2.没有修改ppyoloe的配置文件，除了epoch改小成100

**Comment by lyuwenyu** [comment]
这是训练过程中出的错误？  类别啥的改了没

**Comment by nemonameless** [comment]
ppyoloe没问题。这个报错可能是你改动了训练尺度导致的，请自己再仔细检查下除了epoch还有什么改动，或者重新拉取develop或release/2.4分支代码什么都不改再训下试试。

**Comment by zmdcs** [comment]
> 这是训练过程中出的错误？ 类别啥的改了没

算是训练过程吧，一启动命令就报这个错误 @lyuwenyu

**Comment by zmdcs** [comment]
@nemonameless 我今天的算力用光了，我可能明天才能回答你的问题了，不过我在算力用光前，从GitHub上看ppyoloe的base文件夹下的三个文件，一一对比，除了epoch，应该是没有改动的。不过我不确定我是不是哪天打开的时候不小心碰了键盘，所以不确定，等我明天能跑了，再来回复。

**Comment by lyuwenyu** [comment]
好的

**Comment by zmdcs** [comment]
@nemonameless 我刚刚用cpu的环境跑了一下，我将GitHub上的代码复制粘贴，修改了ppyoloe_reader.yml中的worker num为0，仍然报这个错误。
以下是整体的配置文件，我修改的是snapshot_epoch不是epoch但我觉得也不是导致这个问题的原因吧？
![image](https://user-images.githubusercontent.com/40875421/171182493-3e79270c-6916-471f-bbe9-515660b94ec0.png)

**Comment by lyuwenyu** [comment]
不是你自己的数据嘛  说的是num_classes

**Comment by jiguanglu** [comment]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.


### bug描述 Describe the Bug

使用 ppyoloe_crn_s_400e_coco.yml   
训练8000多张1200*1600的图片, 单卡3090训练，base_lr: 0.005.    batch_size: 32
因为训练中出现一次错误，查了一下 issues 所以把ppyoloe_reader.yml里面的 num_works 设置为0；
 然后可以正常训练，但是训练时间提示为5天，而且lr变成0.024，不知道是什么情况；
![企业微信截图_79222c2d-b42f-4fd3-9404-345b394e0d30](https://user-images.githubusercontent.com/16578290/177682931-3af8aa2d-307e-410b-8402-932b0376f2fc.png)



### 复现环境 Environment

- PaddlePaddle: 2.2.2
- PaddleDetection: release/2.4
- Pyhton: 3.7.13
- CUDA: 11.1
- CUDNN: 8.0.2

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ZhangLe-fighting** [comment]
我现在也遇到这个问题，请问题主解决了吗？

**Comment by zmdcs** [comment]
没解决





------------------ 原始邮件 ------------------
发件人: ZhangLe-fighting ***@***.***&gt;
发送时间: 2022年9月7日 12:04
收件人: PaddlePaddle/PaddleDetection ***@***.***&gt;
抄送: zmdcs ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleDetection] ppyoloe没问题吗？ (Issue #6104)





 
我现在也遇到这个问题，请问题主解决了吗？

**Comment by nemonameless** [comment]
重新拉取develop或release/2.5分支代码再试试

**Comment by moonlightian** [comment]
请问这个问题解决了吗，求分享
