### ISSUE TITLE
训练好的S2ANet在 “PC端” 和 “paddle lite处理后部署到移动端” 的结果不一样

### ISSUE THREAD

**Issue by FengYi-67** [PaddlePaddle/PaddleDetection#6108]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

左边是PC端推理的结果；右边是部署到移动端上的推理结果
![Snipaste_2022-05-31_14-24-15](https://user-images.githubusercontent.com/76467819/171315831-7a1b824f-a7b6-42b5-b046-2958f0b33115.png)
![Snipaste_2022-05-31_14-24-32](https://user-images.githubusercontent.com/76467819/171315926-fa8191e8-4368-4d09-9e3b-b6bbcd0514c2.png)
![Snipaste_2022-05-31_14-24-43](https://user-images.githubusercontent.com/76467819/171315938-372303bc-687f-45dd-bd5b-61c414965b97.png)
![Snipaste_2022-05-31_14-24-56](https://user-images.githubusercontent.com/76467819/171315947-f734594d-130d-4dba-9f28-edec669eae52.png)
![Snipaste_2022-05-31_14-25-08](https://user-images.githubusercontent.com/76467819/171315952-8fd0a8b8-69ab-43d0-8420-1decccfb270e.png)
![Snipaste_2022-05-31_14-25-19](https://user-images.githubusercontent.com/76467819/171315956-d9268095-43c3-4563-94c8-1c1c68f0463e.png)

### 是否愿意提交PR Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
感谢你的反馈，我们近期会验证定位下
