### ISSUE TITLE
c++预测报错

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleDetection#6110]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

<img width="797" alt="20220601133447" src="https://user-images.githubusercontent.com/72127773/171334941-9b387eb0-a275-4000-9bf6-c67ef7aa360f.png">

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by dengmingD** [comment]
调试信息如下：
“main.exe”(Win32): 已加载“D:\work\projects\PaddleDetection\deploy\cpp\Release\main.exe”。模块已生成，不包含符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\ntdll.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\kernel32.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\KernelBase.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\shlwapi.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\msvcrt.dll”。
“main.exe”(Win32): 已加载“D:\work\apps\opencv3_4_6\build\x64\vc15\bin\opencv_world346.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\gdi32.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\win32u.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\gdi32full.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\msvcp_win.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\ucrtbase.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\user32.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\ole32.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\rpcrt4.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\combase.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\oleaut32.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\comdlg32.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\SHCore.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\shell32.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\advapi32.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\sechost.dll”。
“main.exe”(Win32): 已加载“D:\work\projects\PaddleDetection\deploy\cpp\Release\paddle_inference.dll”。模块已生成，不包含符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\bcrypt.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\dbghelp.dll”。
“main.exe”(Win32): 已加载“C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.488_none_4238de57f6b64d28\comctl32.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\msvcp140.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\concrt140.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\mfplat.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\cfgmgr32.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\mf.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\mfreadwrite.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\d3d11.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140.dll”。
“main.exe”(Win32): 已加载“D:\work\projects\PaddleDetection\deploy\cpp\Release\mkldnn.dll”。模块已生成，不包含符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\onnxruntime.dll”。
“main.exe”(Win32): 已加载“D:\work\projects\PaddleDetection\deploy\cpp\Release\paddle2onnx.dll”。模块已生成，不包含符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\vcomp140.dll”。
“main.exe”(Win32): 已加载“C:\Windows\System32\dxgi.dll”。
线程 0x28c 已退出，返回值为 3221225595 (0xc000007b)。
线程 0x3084 已退出，返回值为 3221225595 (0xc000007b)。
程序“[3808] main.exe”已退出，返回值为 3221225595 (0xc000007b)。

**Comment by dengmingD** [comment]
//// Load model and create a object detector
  PaddleDetection::ObjectDetector det(FLAGS_model_dir,
                                      FLAGS_device,
                                      FLAGS_use_mkldnn,
                                      FLAGS_cpu_threads,
                                      FLAGS_run_mode,
                                      FLAGS_batch_size,
                                      FLAGS_gpu_id,
                                      FLAGS_trt_min_shape,
                                      FLAGS_trt_max_shape,
                                      FLAGS_trt_opt_shape,
                                      FLAGS_trt_calib_mode);
运行到这句时报如下错误：
D:\project\PaddleDetection\deploy\cpp\Release\main.exe (进程 16216)已退出，代码为 -1073741701。
按任意键关闭此窗口. . .

**Comment by dengmingD** [comment]
已经解决了

**Comment by effrey-liu** [comment]
你好，我也遇到了相似的问题，请问lz如何解决的呀？
