### ISSUE TITLE
paddleserving  执行test_client.py报错

### ISSUE THREAD

**Issue by KyrieHee** [PaddlePaddle/PaddleDetection#6118]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

```
leo@leo:$ python3 ../../deploy/serving/test_client.py ../../demo/000000014439.jpg
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0602 14:54:12.826076 1485254 naming_service_thread.cpp:202] brpc::policy::ListNamingService("127.0.0.1:9393"): added 1
Traceback (most recent call last):
  File "../../deploy/serving/test_client.py", line 33, in <module>
    fetch_map = client.predict(
  File "/home/sxct/.local/lib/python3.8/site-packages/paddle_serving_client/client.py", line 366, in predict
    raise ValueError("Wrong feed name: {}.".format(key))
ValueError: Wrong feed name: im_size.
```

### 复现环境 Environment

PaddleDetection版本： 2.1

- paddle-bfloat                 0.1.2
- paddle-ernie                  0.2.0.dev1
- paddle-serving-app            0.9.0
- paddle-serving-client         0.9.0
- paddle-serving-server         0.9.0
- paddle2onnx                   0.5.1
- paddleclas                    2.0.1
- paddledet                     2.1.0
- paddlehub                     2.1.0
- paddlenlp                     2.2.3
- paddleocr                     2.3.0.1
- paddlepaddle                  2.3.0
- paddlepaddle-gpu              2.1.0
- paddleslim                    1.1.1
- paddlex                       1.3.11
- x2paddle                      1.0.1

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by ghostxsl** [comment]
你跑的是什么模型？

**Comment by KyrieHee** [comment]
deploy 中serving  readme提供的案例

**Comment by KyrieHee** [comment]
> 你跑的是什么模型？

deploy 中serving  readme提供的案例

**Comment by ghostxsl** [comment]
你改过代码没有？我看你报错信息是找不到key：im_size，这个在我们的模型中是没有的，应该是im_shape

**Comment by KyrieHee** [comment]
> 

已修复，依赖包升级后没问题了，谢谢
