### ISSUE TITLE
关键点检测HRNet-w32在coco数据上表现比原始论文的结果还要好？

### ISSUE THREAD

**Issue by haizeigh** [PaddlePaddle/PaddleDetection#6121]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

关键点检测HRNet-w32在coco数据上AP=76.9，输入尺寸256x192，原始论文的结果是AP=74.4，比原始论文的表现还好，是修改了HRNet-w32什么结构吗？
数据来源地址
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/keypoint

**Comment by jerrywgz** [comment]
我们给出的AP精度是基于coco gt框的结果，精度会高一些；论文中的结果是使用检测器的结果，可以参考https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/keypoint#2%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87 网络结构上是和论文对齐的

**Comment by haizeigh** [comment]
好的，谢谢了
