### ISSUE TITLE
训练报错 /paddle/paddle/fluid/operators/bce_loss_op.cu:38

### ISSUE THREAD

**Issue by Abris-087** [PaddlePaddle/PaddleDetection#6123]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我将yolov3的backbone替换为swim transform，训练初期就出现如下报错。尝试过修改learning rate没能解决这个问题，请问我该怎么做呢？  版本是paddledet-2.3
![image](https://user-images.githubusercontent.com/61613537/171652936-d7b150bb-c2c1-4d10-a194-7f512b6de927.png)
![image](https://user-images.githubusercontent.com/61613537/171653053-95cc8185-5c29-4567-9fc6-6b8c9f0944c1.png)

**Comment by jerrywgz** [comment]
从日志上看是训练出现了nan的情况，可以先确认下如果不使用swin 的backbone，训练是否正常

**Comment by convnets** [comment]
same here. I changed the backbone to ViT, and got the exact error.

**Comment by wanmeiziyoulan** [comment]
尝试将ViT和ConNeXt分别与yolov3结合，使用adamw optimizer训练均出现nan，报错信息与上面的一致。
- 同时尝试将optimizer换成sgd训练是正常的，但是像ViT这种结构和AdamW结合是更好的，使用sgd还是治标不治本。
- 根据报错信息，目前定位到可能与iou_loss有关系，正在尝试丢弃iou_loss，使用adamw训练ViT yolov3，正在实验中

希望Paddle同学可以重视下这个问题！感谢
