### ISSUE TITLE
WRN paddlepaddle version: 2.2.2. The dynamic graph version of PARL is under development, not fully tested and supported

### ISSUE THREAD

**Issue by Q2539958** [PaddlePaddle/PaddleDetection#6124]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问我Paddle安装的是2.2.2版本，PaddleSlim版本为2.2.2，依然还是会出现这个警告，这个对GFLOPS的计算会有影响吗，我看我计算的GFLOPS和论文中的差距较大

**Comment by jerrywgz** [comment]
可以尝试下paddle.flops https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/flops_cn.html#flops
