### ISSUE TITLE
@houjingsong 默认是所有的conv都会加入fake量化节点的，这属于已知问题，我们解决下。

### ISSUE THREAD

**Issue by fpjnice** [PaddlePaddle/PaddleDetection#6125]
@houjingsong 默认是所有的conv都会加入fake量化节点的，这属于已知问题，我们解决下。

_Originally posted by @yghstill in https://github.com/PaddlePaddle/PaddleDetection/issues/5994#issuecomment-1128705037_

**Comment by yghstill** [comment]
@fpjnice 近期会高优看下这个问题，请先使用SSDLite模型或者Head部分最后一层conv先跳过~

**Comment by fpjnice** [comment]
我已经解决了这个问题。做法是自己def 了一个convlayer 类，类内部添加了 forward函数 就可以了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Guanghua ***@***.***&gt;; 
发送时间: 2022年6月3日(星期五) 晚上7:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] @houjingsong 默认是所有的conv都会加入fake量化节点的，这属于已知问题，我们解决下。 (Issue #6125)





 
@fpjnice 近期会高优看下这个问题，请先使用SSDLite模型或者Head部分最后一层conv先跳过~
