### ISSUE TITLE
模型部署树莓派报错

### ISSUE THREAD

**Issue by Abris-087** [PaddlePaddle/PaddleDetection#6126]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我训练了一个主干网络为swin transformer的检测网络，运行export.py导出之后，利用opt转化为.nb模型时报错。
![image](https://user-images.githubusercontent.com/61613537/171984177-30bfe8f0-7e9a-4c84-a9c6-206a815ec8aa.png)
![image](https://user-images.githubusercontent.com/61613537/171984182-1cf17744-3254-44b1-921b-ee9739f77150.png)

**Comment by jerrywgz** [comment]
麻烦提供下paddlelite的版本信息
