### ISSUE TITLE
C++编程需求

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleDetection#6127]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

pytorch在一年多以前,就非常完善的支持C++编程了,比如图像分类这个任务,可以从头到尾,不使用一行python代码完成数据集下载,加载,训练,预测等步骤.知乎和CSDN也有很多pytorch的C++编程代码,可以让我们学习和参考.目前我都没看到一个项目使用C++完成飞桨任务的,无论是图像分类clas等开发套件,还是飞桨paddlepaddle,我想请问,飞桨是否打算支持C++编程呢?
我不敢说pytorch支持C++20,C++23这些很新的标准,但是用VS2022编写pytorch代码,完全没有问题.对于飞桨框架来说,目前C++似乎只能用于预测,而且一个预测的代码,比如图像分类clas的C++预测代码,超级多代码,无语,能否封装一下,像python一样,实现一行C++代码预测呢?如果目前C++已经能用于飞桨的话,麻烦你们多提供项目案例,让我知道如何写代码,谢谢,比如可以一个开发套件做一个C++案例.

我还想请问下,我现在使用windows,C++,5600gCPU,飞桨.对于图像分类clas和目标检测dec这两个开发套件来说,预测时使用的是多核心多线程还是单核心单线程CPU?另外,预测是否可以让客户自主选择使用多少个CPU线程?
我有一个预测任务,单开任务的话,我希望,CPU的6核心12线程都可以参与预测.但是如果双开任务,我就希望为每个预测任务分配3核心6线程.

总结:1.希望提高C++编程体验,让C++不仅仅只能用于预测.希望提供C++案例.
2.C++预测,能否实现一行代码预测呢?跟python一样
3.C++预测,能否指定使用多少线程呢?

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jerrywgz** [comment]
第一个问题，目前飞桨还不支持C++的编程方式，可以在Paddle repo下提个issue看看
第二个问题，目前ppdet下面是对c++预测做了封装，代码和文档可以参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/cpp 编译完成后用一行命令就可以完成预测
第三个问题，在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/cpp/src/main.cc 下可以通过设置cpu_threads指定cpu线程个数
