### ISSUE TITLE
nms外部扩展库编译出错

### ISSUE THREAD

**Issue by 1171000410** [PaddlePaddle/PaddleDetection#6129]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

在 ppdet/ext_op/目录下执行

# 编译nms
python setup.py install

<img width="1895" alt="截屏2022-06-05 上午10 58 58" src="https://user-images.githubusercontent.com/47969298/172033076-2a3a750e-3974-474d-ad1a-5f02c0e1947c.png">

备注：
在paddle.utils.run_check()的时候，有个warning，不知道有没有影响：
WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.1, but CUDNN version in your machine is 8.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.

### 复现环境 Environment

paddlepaddle-gpu        2.2.2.post112
paddledet                      2.4.0
python                           3.7
gcc                                 8.2
cuda                               11.3
cudnn                             8.0

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by jerrywgz** [comment]
这个nms是自定义op的形式自己开发的吧，可以参考这个文档https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/custom_op/new_cpp_op_cn.html
