### ISSUE TITLE
Linux C++部署 最后一步报错，无法生成main文件

### ISSUE THREAD

**Issue by pphgood** [PaddlePaddle/PaddleDetection#6130]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![1](https://user-images.githubusercontent.com/101175483/172038357-8a850c70-8c4a-4892-bb79-8cd454f226dc.png)
在C++部署，运行build.sh文件 最后100%时报错，build.sh文件中配置路径已经修改正确，环境要求也配置正确，这个问题不知道怎么解决

**Comment by pphgood** [comment]
PPYOLOV2模型

**Comment by pphgood** [comment]
![FAU2VXD1PL2 7%2~CK12Y%R](https://user-images.githubusercontent.com/101175483/172043246-ca7e3f66-bca8-43b8-9b57-4cf4ac0ede8b.png)
我的环境是cuda10.2 cudnn7.6 gcc8.2

**Comment by pphgood** [comment]
使用文档中是ubuntu 16.04 而我是ubuntu 18 不知道这个有影响吗

**Comment by VantastyChen** [comment]
我用自己编译的opencv，解决了这个问题。

**Comment by pphgood** [comment]
> 我用自己编译的opencv，解决了这个问题。
你自己编译的是哪个版本的opencv呢

**Comment by pphgood** [comment]
请问自己编译的opencv 在build.sh文件中需要怎么修改配置

**Comment by VantastyChen** [comment]
4.5 把不支持的api改一下就行了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pphgood ***@***.***&gt;
发送时间: 2022年6月7日 18:49
收件人: PaddlePaddle/PaddleDetection ***@***.***&gt;
抄送: VantastyChen ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleDetection] Linux C++部署 最后一步报错，无法生成main文件 (Issue #6130)





  
我用自己编译的opencv，解决了这个问题。
 你自己编译的是哪个版本的opencv呢
