### ISSUE TITLE
计划将苹果的MobileViT作为骨干网络进行测试吗

### ISSUE THREAD

**Issue by QuStarry** [PaddlePaddle/PaddleDetection#6131]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

计划将苹果的MobileViT作为骨干网络进行测试吗

**Comment by jerrywgz** [comment]
目前还没有计划集成该骨干网络，现在paddleclas已经集成了这个模型，也欢迎向paddledetection贡献这部分骨干网络的代码～
