### ISSUE TITLE
训练之初打印网络架构

### ISSUE THREAD

**Issue by sdreamforchen** [PaddlePaddle/PaddleDetection#6132]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

paddle在训练之初可以打印整个网络架构不呢？有便捷的接口吗

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/engine/trainer.py#L384  
可以加上 print(self.model)
