### ISSUE TITLE
solov2 c++推理和python推理不一致

### ISSUE THREAD

**Issue by xdg2016** [PaddlePaddle/PaddleDetection#6135]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我这边用了python的推理脚本：PaddleDetection\deploy\python\infer.py可以顺利的进行推理。但是，在使用c++部署时，predictor->Run() 运行后，auto output_names = predictor->GetOutputNames() 的结果与python版完全不一样：
![image](https://user-images.githubusercontent.com/16351823/172142801-827c910f-5ed4-4db0-9ffe-9dc2eb80e505.png)
![image](https://user-images.githubusercontent.com/16351823/172142919-bbdf6bcd-374d-4869-881c-fae8c31eaef8.png)
再看了一下model.pdparams文件，输出和python是一致的，
![image](https://user-images.githubusercontent.com/16351823/172143587-42e8d9a9-d34b-41f7-b358-570fb9cf2740.png)

模型都用的是同一份导出后的静态图模型。这个结果应该不是输入数据不一致导致的（检查过了，两边输入数据一致），倒像是底层解析网络结构时出现了问题，麻烦有空帮我解答一下，是否需要重新编译paddle_inference库，谢谢~

**Comment by zoooo0820** [comment]
@xdg2016 
你好，我这边验证结果是正常的，也能与python对齐，请问paddledet的版本是否是develop，如果是2.4的话可以切换到develop试一下。另外paddle inference的版本是多少呢？

**Comment by xdg2016** [comment]
@zoooo0820 paddle inference 版本是2.1，paddledet 是develop版本，看到最新的deploy已经支持了solov2，我测试了那个cpp里面的object_detector.cc，就出现了前面的那个错误，难道是paddle inference版本太低了吗，去年编译的。

**Comment by zoooo0820** [comment]
辛苦先更新inference版本试下呢，可以在这里找到 https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html

**Comment by kouhinn** [comment]
一样的问题。paddle+paddle inference已经更新到2.3.0都不行。看起来是c++的object_detector.cc的Predict和python对应的实现都不一样。明显是c++版本的没有更新。
我这边c++版本和python版本的输出名是一样的。但是输出的数目不一致。c++这边输出是这样的： output: name: shape_40.tmp_0_slice_0  out_num:1
output: gather_18.tmp_0  out_num:42
output: gather_17.tmp_0  out_num:42
output:cast_19.tmp_0  out_num:38707200   
而python的对应上述4个输出的数目是： 1，43，43，39628800（43x720x1280 ）

**Comment by zoooo0820** [comment]
@kouhinn 
能辛苦提供下具体的使用环境吗，包括paddle inference 版本 、 paddledetection版本，系统及cuda版本，我们在对应环境上复现下问题

**Comment by kouhinn** [comment]
object_detector.cc:Predict和postprocess和python版本对应不上。应该是c++代码没有更新。

paddle inference/paddle版本：Paddle_2.3.0
paddledetection版本：PaddleDetection-release-2.4
系统及cuda版本：
  ubuntu18.04   
  cuda:10.2  
  cudnn:cudnn-10.2-linux-x64-v7.6.5.32

**Comment by zoooo0820** [comment]
@kouhinn 
solov2的cpp inference是最近新增加的功能，没有包含在release2.4中。辛苦把paddledetection代码切换到develop分支试一下呢

**Comment by kouhinn** [comment]
> @kouhinn solov2的cpp inference是最近新增加的功能，没有包含在release2.4中。辛苦把paddledetection代码切换到develop分支试一下呢

是这个问题！更新到develop分支之后就可以了。谢谢帮助！
