### ISSUE TITLE
导出行人模型报错

### ISSUE THREAD

**Issue by lhy823436493** [PaddlePaddle/PaddleDetection#614]
其他模型导出都没有问题，在导出特色模型检测行人的时候报错，请问一下是什么原因？
![QQ截图20200508155617](https://user-images.githubusercontent.com/53975909/81384699-a1686b00-9144-11ea-9f30-bf7b1c2e2ed0.png)

**Comment by still-wait** [comment]
@lhy823436493 我们复现了这个问题，会尽快修复^-^

**Comment by lhy823436493** [comment]
> @lhy823436493 我们复现了这个问题，会尽快修复^-^

好的好的，请尽快修复吧，急着要导出，谢谢您。

**Comment by still-wait** [comment]
@lhy823436493 请使用原下载链接更新下模型，再试下，我们这边修复了。
