### ISSUE TITLE
ppyoloe-s如何基于已训练好的模型再次训练？

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#6147]
### 问题描述 Please describe your issue

ppyoloe-s如何基于已训练好的模型再次训练？

**Comment by jerrywgz** [comment]
再次训练是基于已有数据继续训练还是会加入新数据和类别做迁移学习呢

**Comment by lixiangMindSpore** [comment]
> 再次训练是基于已有数据继续训练还是会加入新数据和类别做迁移学习呢
以下两种情况：
1  加入新数据和类别作迁移学习，需要用到之前已训练好的模型，比如在COCO数据集上训练好的模型；
2  如果中间机器重启需要接着训练。

**Comment by jerrywgz** [comment]
第一种情况，配置文件中的pretrain_weights设置为coco数据集上的权重就可以，然后适当调低学习率
第二种情况，命令行中使用`-r xxx.pdparams`即可，可以参考文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/docs/tutorials/GETTING_STARTED_cn.md#4-%E8%AE%AD%E7%BB%83

**Comment by lixiangMindSpore** [comment]
> 第一种情况，配置文件中的pretrain_weights设置为coco数据集上的权重就可以，然后适当调低学习率 第二种情况，命令行中使用`-r xxx.pdparams`即可，可以参考文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/docs/tutorials/GETTING_STARTED_cn.md#4-%E8%AE%AD%E7%BB%83

第一种情况是指ppyoloe_crn_s_300e_coco.yml配置文件吗？把backkbone模型pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_s_pretrained.pdparams  改成基于COCO训练好的检测模型？

**Comment by jerrywgz** [comment]
是的，改这个就行
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml#L13
