### ISSUE TITLE
Sota - tinypose VS movenet!

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleDetection#6171]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

hi，请问下
有对比过tinypose和movenet的人体关键点检测效果吗？
各种精度和识别率指标呢？
有木有相关的测试结果或者网络链接分享，多谢
BR

**Comment by wangxinxin08** [comment]
可以看下文档哈：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/keypoint/tiny_pose

**Comment by 2050airobert** [comment]
咱们有专门对比过吗？ 或者两个demo的同时展示？

**Comment by zhiboniu** [comment]
你好，上述页面对比表格的开源模型就是movenet的。tinypose的测试可以参考lite部署部分介绍。
movenet的部署对比在说明部分也有提供链接。
地址：https://github.com/zhiboniu/MoveNet-PaddleLite

**Comment by 2050airobert** [comment]
谢谢，这些写的很好，只是我想问下，咱们有木有专门对比过tinypose和movenet的精度 效果 以及部署的展示对比？

**Comment by jerrywgz** [comment]
https://baijiahao.baidu.com/s?id=1717359560384671269&wfr=spider&for=pc 可以看下这里面有一些展示对比

**Comment by 2050airobert** [comment]
这里明显没有movenet的结果啊！

**Comment by 2050airobert** [comment]
@wangxinxin08 @jerrywgz  anyone could reply ？ tks

**Comment by wangxinxin08** [comment]
> @wangxinxin08 @jerrywgz anyone could reply ？ tks

表格里面的multipose
