### ISSUE TITLE
请问能将prior_box设置成int8类型的输入吗？想要借此优化模型

### ISSUE THREAD

**Issue by Student-Fuz** [PaddlePaddle/PaddleDetection#6172]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

正在使用ssd_mobilenet_v1模型，想要修改prior_box的输入数据类型，使卷积全都变成8bit的卷积，实现卷积全量化

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
prior_box设置int8 但是运算的时候是需要float  可以试一下会不会强制转化

**Comment by Student-Fuz** [comment]
请问具体是改哪里呢？

**Comment by Student-Fuz** [comment]
> 

请问具体是改哪里呢？

**Comment by Student-Fuz** [comment]
> prior_box设置int8 但是运算的时候是需要float 可以试一下会不会强制转化

请问具体是改哪里呢？

**Comment by Jiashuhao518** [comment]
> > prior_box设置int8 但是运算的时候是需要float 可以试一下会不会强制转化
> 
> 请问具体是改哪里呢？

请问一下您有没有成功将SSD的卷积进行8bit量化
