### ISSUE TITLE
数据增强 RandomErasingImage参数缺失

### ISSUE THREAD

**Issue by wawatt** [PaddlePaddle/PaddleDetection#6173]
### 问题确认 Search before asking

- [ ] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

数据增强RandomErasingImage中apply参数与BaseOperator类中的不一致，导致调用报错：
apply() takes 2 positional arguments but 3 were given and stack:
Traceback (most recent call last)

要修改
class RandomErasingImage(BaseOperator):
        ...
        def apply(self, sample):
                ...
为
        def apply(self, sample, context=None):

### 复现环境 Environment

- PaddlePaddle: 2.3.0
- PaddleDetection: release/2.4
- Python: 3.8.10
- CUDA: 11.2
- CUDNN: 8.2

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
感谢反馈，有兴趣提个PR嘛
