### ISSUE TITLE
使用paddledetection导出训练模型出现问题

### ISSUE THREAD

**Issue by xyx18061932** [PaddlePaddle/PaddleDetection#618]
在导出文件时，出现AttributeError: 'list' object has no attribute 'read'。
![$P}`_6X_A2P6 80~26RX0EH](https://user-images.githubusercontent.com/65025198/81409744-3766ba80-9172-11ea-8c70-fb9c1c6eec93.png)

**Comment by still-wait** [comment]
@xyx18061932 请检查`-o weights`参数设置的权重路径是否正确，看你截图`output/`后是空格，这样路径不正确的

**Comment by xyx18061932** [comment]
@still-wait 
![41X U74I3(~CRF59 D KQ80](https://user-images.githubusercontent.com/65025198/81463415-12169280-91ec-11ea-8a4b-f2ad6bdd2b7
您好，我现在修改了那个空格，然后检查了路径，发现没问题，但是还是依旧是那个老问题

**Comment by xyx18061932** [comment]
@still-wait 
您好，我是完成了训练之后，想要导出模型，我怀疑是文件本身出了问题

**Comment by heavengate** [comment]
您好，请问下你的python版本和python里yaml库的版本是多少呢，看着像是yaml配置文件读入错误

**Comment by qingqing01** [comment]
@xyx18061932 你windows环境是什么？ 我们同学在windows测试没问题。我们需要看下怎么复现你的问题

**Comment by xyx18061932** [comment]
您好，不好意思，我已经解决了那个问题，我后来把0.2版换了，然后重新弄了一下0.1，发现导出就没问题了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "qingqing01"<notifications@github.com&gt;; 
发送时间: 2020年5月15日(星期五) 下午5:25
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 
抄送: "biubiubiu"<2503568084@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] 使用paddledetection导出训练模型出现问题 (#618)





 
@xyx18061932 你windows环境是什么？ 我们同学在windows测试没问题。我们需要看下怎么复现你的问题

**Comment by xyx18061932** [comment]
谢谢您的帮忙，麻烦您了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "qingqing01"<notifications@github.com&gt;; 
发送时间: 2020年5月15日(星期五) 下午5:25
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 
抄送: "biubiubiu"<2503568084@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] 使用paddledetection导出训练模型出现问题 (#618)





 
@xyx18061932 你windows环境是什么？ 我们同学在windows测试没问题。我们需要看下怎么复现你的问题
