### ISSUE TITLE
【急】自建模型预测报错 

### ISSUE THREAD

**Issue by yqsoooo** [PaddlePaddle/PaddleDetection#6182]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/15975613/173195266-66069e07-0300-481c-9ca2-d6d3853894c4.png)
![image](https://user-images.githubusercontent.com/15975613/173195282-349f9b80-a38a-4570-90dc-9942af76e37f.png)

背景：
这个是我基于 paddle2.3+paddleDetection2.3 自训练的ppyolo mbv3 small coco训练的模型，机器是ubuntu1804+T4显卡。
模型本身正常使用了半年了。但是最近发现环境出现了异常，现象为：预测日志卡在了显示参数环节、nvidia-smi显示not macth之类的报错。
我尝试卸载重装了显卡驱动440+cuda10.2+cudnn7.6.5     重装了Paddle的环境、重装了paddleDetection的python依赖。目前使用tools/infer 预测官方样例没有问题，自建模型报错，看样子是numpy数组想除的报错。请问能帮助解决下吗。

**Comment by yqsoooo** [comment]
![image](https://user-images.githubusercontent.com/15975613/173195433-58db8c7a-720b-4772-b18e-84622fafd2aa.png)

**Comment by nemonameless** [comment]
```预测日志卡在了显示参数环节、nvidia-smi显示not macth之类的报错。```是你尝试卸载重装了显卡驱动和paddleDetection的python依赖之前还是之后的问题现象？tools/infer 预测官方样例是指哪个？建议先确保排除环境问题后，或者确保原本代码或什么都不改的时候跑样例命令都能跑通，然后再排查你新增代码的问题。NormalizeImage是常见OP，不太可能出错。
