### ISSUE TITLE
PPYOLOE训练自有数据集问题

### ISSUE THREAD

**Issue by bittergourd1224** [PaddlePaddle/PaddleDetection#6188]
### 问题描述 Please describe your issue

1. 训练时不加选项--amp，刚开始训练打印了一行log后，就报错：
OSError: (External) CUDA error(719), unspecified launch failure.
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:258)

2. 加上选项--amp，训练了不到20epochs，就不再训练而只是不断重复以下log：
Found inf or nan, current scale is: 0.0, decrease to: 0.0*0.5
只是在使用l模型出现时出现，使用s模型未出现

3. 模型的训练效果，都不如yolov3_darknet53的效果

目前优先想解决的是问题一，想尝试一下不加--amp能否改善训练效果，因为yolov3_darknet53训练时就可以不加--amp而正常训练

**Comment by nemonameless** [comment]
0.请按模板提问，至少说明paddle版本和ppdet版本
1.请截图信息更多点，至少能看到是哪一行报的错
2.加上--amp显示Found inf or nan是paddle混合精度训练的正常现象
3.训自己的数据集用fintune，不要从头训，因为默认配置下bs lr等什么的都是COCO大型数据集的设置，从头训用这套参数未必合适。但是fintune的套路基本一致，加载coco训好的模型，lr变为1/10等，可以参照[visdrone](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/visdrone/ppyoloe_crn_l_80e_visdrone.yml)数据集的fintune配置
4.--amp是混合精度训练，只是减少显存占用防止溢出，任何模型都可以加或不加amp训，精度基本不会变

**Comment by bittergourd1224** [comment]
感谢回复：
0. paddle版本为paddlepaddle-gpu 2.3.0，paddledet版本为2.4.0
1. 不加--amp时的报错如下：
![2022-06-14 18-13-13 的屏幕截图](https://user-images.githubusercontent.com/26888350/173554903-9cd2a787-1aa1-4abb-891b-ccb0fa02894a.png)
![2022-06-14 18-11-17 的屏幕截图](https://user-images.githubusercontent.com/26888350/173554949-841e13a0-749c-48f1-9393-5416039bb9a5.png)
2. 不是只显示一行Found inf or nan，而是log只剩下反复打印Found inf or nan, current scale is: 0.0, decrease to: 0.0*0.5，并且可以注意到，scale的值已经是0.0了，似乎这是造成训练无法继续的原因。不好意思这个当时没有保存截图。
3. 好的，我试一下。这个配置文件好像是新commit的，我clone的时候还没有，就直接按照coco的yml改了。

**Comment by bittergourd1224** [comment]
@nemonameless Found inf or nan的log也复现了，并且这次我将lr缩小了10倍且使用了coco的预训练模型
![2022-06-15 09-22-29 的屏幕截图](https://user-images.githubusercontent.com/26888350/173716562-c07b82bf-95dd-49ad-8b92-6ca6e8d3cd72.png)
![2022-06-15 09-24-39 的屏幕截图](https://user-images.githubusercontent.com/26888350/173716590-375781a1-b80f-49e3-ad35-e92e6adfeb88.png)
loss比yolov3_darknet53大一个量级。

**Comment by wangxinxin08** [comment]
2.3.0先不要使用amp训练试下

**Comment by bittergourd1224** [comment]
> 感谢回复： 0. paddle版本为paddlepaddle-gpu 2.3.0，paddledet版本为2.4.0
> 
> 1. 不加--amp时的报错如下：
>    ![2022-06-14 18-13-13 的屏幕截图](https://user-images.githubusercontent.com/26888350/173554903-9cd2a787-1aa1-4abb-891b-ccb0fa02894a.png)
>    ![2022-06-14 18-11-17 的屏幕截图](https://user-images.githubusercontent.com/26888350/173554949-841e13a0-749c-48f1-9393-5416039bb9a5.png)
> 2. 不是只显示一行Found inf or nan，而是log只剩下反复打印Found inf or nan, current scale is: 0.0, decrease to: 0.0*0.5，并且可以注意到，scale的值已经是0.0了，似乎这是造成训练无法继续的原因。不好意思这个当时没有保存截图。
> 3. 好的，我试一下。这个配置文件好像是新commit的，我clone的时候还没有，就直接按照coco的yml改了。

@wangxinxin08 不加amp训练就会报错，截图如上所示。你说的2.3.0是指将paddledet切换为2.3.0版本吗？

**Comment by wangxinxin08** [comment]
我的意思是PaddlePaddle 2.3.0不要使用amp进行训练，报错信息是说出nan了，如果你学习率设置没问题，可以检查下数据是不是有问题

**Comment by bittergourd1224** [comment]
> 我的意思是PaddlePaddle 2.3.0不要使用amp进行训练，报错信息是说出nan了，如果你学习率设置没问题，可以检查下数据是不是有问题

数据是没问题的，用yolov3_darknet53训练正常，加上amp训练也正常，因此不应该是数据的问题。学习率我在根据我这边的batchsize和gpu数量的基础上，又降了1/10。还有可能是其他问题不？

**Comment by wangxinxin08** [comment]
@bittergourd1224 可以先回退到PaddlePaddle 2.2训练下，另外把修改的配置文件贴一下

**Comment by bittergourd1224** [comment]
> @bittergourd1224 可以先回退到PaddlePaddle 2.2训练下，另外把修改的配置文件贴一下

### configs/ppyoloe/ppyoloe_crn_l_300e_vehicle+person_obscure.yml文件：
_BASE_: [
  '../datasets/vehicle+person_obscure_voc.yml',
  '../runtime.yml',
  './_base_/optimizer_300e.yml',
  './_base_/ppyoloe_crn.yml',
  './_base_/ppyoloe_reader.yml',
]

log_iter: 100
snapshot_epoch: 1
weights: output/ppyoloe_crn_l_300e_vehicle+person_obscure/model_final

#pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_l_pretrained.pdparams
pretrain_weights: https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_300e_coco.pdparams
depth_mult: 1.0
width_mult: 1.0

TrainReader:
  batch_size: 4

LearningRate:
  base_lr: 0.0000625

epoch: 50


### configs/datasets/vehicle+person_obscure_voc.yml文件：
metric: VOC
map_type: 11point
num_classes: 2

TrainDataset:
  !VOCDataSet
    dataset_dir: /home/foia_xlc/chuan/paddle
    anno_path: train.txt
    label_list: label_list_vehicle+person.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: /home/foia_xlc/chuan/paddle
    anno_path: test.txt
    label_list: label_list_vehicle+person.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: /home/foia_xlc/chuan/paddle/label_list_vehicle+person.txt

**Comment by wangxinxin08** [comment]
看起来没什么问题，你可以把训练yolov3的配置也发下，另外可以先回退到PaddlePaddle 2.2.2训练下

**Comment by bittergourd1224** [comment]
回退到2.2.2后，不加amp还是一样的报错

### yolov3的配置文件configs/yolov3/yolov3_darknet53_270e_vehicle+person_obscure.yml：
_BASE_: [
  '../datasets/vehicle+person_obscure_voc.yml',
  '../runtime.yml',
  '_base_/optimizer_270e.yml',
  '_base_/yolov3_darknet53.yml',
  '_base_/yolov3_reader.yml',
]

snapshot_epoch: 5
weights: output/yolov3_darknet53_270e_vehicle+person_obscure/model_final

#set collate_batch to false because ground-truth info is needed
#on voc dataset and should not collate data in batch when batch size
#is larger than 1.
EvalReader:
  collate_batch: false

**Comment by wangxinxin08** [comment]
暂时没有发现什么问题，倾向于认为是数据的问题，你可以自己debug下
