### ISSUE TITLE
训练的最后发生core dump - Core dump in training at last log_smooth_window 

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleDetection#619]
Core dump without detailed error massage was found at last log_smooth_window, while fine tuning YOLOV3 in custom dataset. Part of my config yaml file:

> architecture: YOLOv3
> use_gpu: true
> max_iters: 25000
> log_smooth_window: 20
> save_dir: output
> snapshot_iter: 200
> metric: COCO
> pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet.tar
> weights: output/yolov3_darknet_schwarz_v3/model_final
> num_classes: 8
> finetune_exclude_pretrained_params: ['yolo_output']
> use_fine_grained_loss: false

> 
> LearningRate:
>   base_lr: 0.00005
>   schedulers:
>   - !PiecewiseDecay
>     gamma: 0.1
>     milestones:
>     - 18750
>     - 22500
>   - !LinearWarmup
>     start_factor: 0.
>     steps: 200

Training batch_size is 10, runing in 2 GPUs.

The error message and its context:

> 2020-05-09 07:48:32,532-INFO: iter: 24820, lr: 0.000000, 'loss': '9.387529', time: 2.270, eta: 0:06:48
> 2020-05-09 07:49:11,330-INFO: iter: 24840, lr: 0.000000, 'loss': '9.227110', time: 1.970, eta: 0:05:15
> 2020-05-09 07:49:46,325-INFO: iter: 24860, lr: 0.000000, 'loss': '9.516720', time: 1.718, eta: 0:04:00
> 2020-05-09 07:50:24,220-INFO: iter: 24880, lr: 0.000000, 'loss': '9.507334', time: 1.961, eta: 0:03:55
> 2020-05-09 07:50:59,543-INFO: iter: 24900, lr: 0.000000, 'loss': '9.366526', time: 1.704, eta: 0:02:50
> 2020-05-09 07:51:35,928-INFO: iter: 24920, lr: 0.000000, 'loss': '9.407713', time: 1.881, eta: 0:02:30
> 2020-05-09 07:52:12,927-INFO: iter: 24940, lr: 0.000000, 'loss': '9.048078', time: 1.792, eta: 0:01:47
> 2020-05-09 07:52:48,232-INFO: iter: 24960, lr: 0.000000, 'loss': '9.399294', time: 1.822, eta: 0:01:12
> 2020-05-09 07:53:26,531-INFO: iter: 24980, lr: 0.000000, 'loss': '8.900979', time: 1.847, eta: 0:00:36
> 2020-05-09 07:53:59,817-INFO: Save model to output/yolov3_tt_v1/model_final.
> 2020-05-09 07:54:07,028-INFO: Test iter 0
> 2020-05-09 07:54:08,037-INFO: Test finish iter 7
> 2020-05-09 07:54:08,037-INFO: Total number of images: 65, inference time: 51.95583207253508 fps.
> loading annotations into memory...
> Done (t=0.00s)
> creating index...
> index created!
> 2020-05-09 07:54:08,181-INFO: Start evaluate...
> Loading and preparing results...
> DONE (t=0.03s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type *bbox*
> DONE (t=0.77s).
> Accumulating evaluation results...
> DONE (t=0.28s).
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.295
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.509
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.330
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.402
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.671
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.279
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.293
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.383
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.383
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.443
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.689
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.376
> 2020-05-09 07:54:09,291-INFO: Best test box ap: 0.31016948065022704, in iter: 9200
> terminate called without an active exception
> W0509 07:54:10.161070 22881 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
> W0509 07:54:10.161113 22881 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
> W0509 07:54:10.161131 22881 init.cc:214] The detail failure signal is:
> 
> W0509 07:54:10.161152 22881 init.cc:217] *** Aborted at 1588982050 (unix time) try "date -d @1588982050" if you are using GNU date ***
> W0509 07:54:10.169255 22881 init.cc:217] PC: @                0x0 (unknown)
> W0509 07:54:10.169443 22881 init.cc:217] *** SIGABRT (@0x3e8000033bf) received by PID 13247 (TID 0x7f9439fff700) from PID 13247; stack trace: ***
> W0509 07:54:10.176609 22881 init.cc:217]     @     0x7f9afac08390 (unknown)
> W0509 07:54:10.181762 22881 init.cc:217]     @     0x7f9afa862428 gsignal
> W0509 07:54:10.186179 22881 init.cc:217]     @     0x7f9afa86402a abort
> W0509 07:54:10.189432 22881 init.cc:217]     @     0x7f9aeafc584a __gnu_cxx::__verbose_terminate_handler()
> W0509 07:54:10.192270 22881 init.cc:217]     @     0x7f9aeafc3f47 __cxxabiv1::__terminate()
> W0509 07:54:10.195497 22881 init.cc:217]     @     0x7f9aeafc3f7d std::terminate()
> W0509 07:54:10.198510 22881 init.cc:217]     @     0x7f9aeafc3c5a __gxx_personality_v0
> W0509 07:54:10.202011 22881 init.cc:217]     @     0x7f9af9a02b97 _Unwind_ForcedUnwind_Phase2
> W0509 07:54:10.205464 22881 init.cc:217]     @     0x7f9af9a02e7d _Unwind_ForcedUnwind
> W0509 07:54:10.208946 22881 init.cc:217]     @     0x7f9afac07070 __GI___pthread_unwind
> W0509 07:54:10.212412 22881 init.cc:217]     @     0x7f9afabff845 __pthread_exit
> W0509 07:54:10.213181 22881 init.cc:217]     @     0x561430665059 PyThread_exit_thread
> W0509 07:54:10.213379 22881 init.cc:217]     @     0x5614304eac10 PyEval_RestoreThread.cold.799
> W0509 07:54:10.215291 22881 init.cc:217]     @     0x7f9ae76d4b27 pyopencv_cv_imdecode()
> W0509 07:54:10.216156 22881 init.cc:217]     @     0x5614305ebab4 _PyMethodDef_RawFastCallKeywords
> W0509 07:54:10.216982 22881 init.cc:217]     @     0x5614305ebbd1 _PyCFunction_FastCallKeywords
> W0509 07:54:10.217809 22881 init.cc:217]     @     0x56143065257b _PyEval_EvalFrameDefault
> W0509 07:54:10.218571 22881 init.cc:217]     @     0x561430597389 _PyEval_EvalCodeWithName
> W0509 07:54:10.219349 22881 init.cc:217]     @     0x5614305984c5 _PyFunction_FastCallDict
> W0509 07:54:10.220100 22881 init.cc:217]     @     0x5614305b7a73 _PyObject_Call_Prepend
> W0509 07:54:10.220489 22881 init.cc:217]     @     0x5614305ff27a slot_tp_call
> W0509 07:54:10.221262 22881 init.cc:217]     @     0x5614306002db _PyObject_FastCallKeywords
> W0509 07:54:10.222090 22881 init.cc:217]     @     0x561430652146 _PyEval_EvalFrameDefault
> W0509 07:54:10.222860 22881 init.cc:217]     @     0x5614305983fb _PyFunction_FastCallDict
> W0509 07:54:10.223621 22881 init.cc:217]     @     0x5614305b7a73 _PyObject_Call_Prepend
> W0509 07:54:10.224014 22881 init.cc:217]     @     0x5614305ff27a slot_tp_call
> W0509 07:54:10.224784 22881 init.cc:217]     @     0x5614306002db _PyObject_FastCallKeywords
> W0509 07:54:10.225611 22881 init.cc:217]     @     0x561430652a39 _PyEval_EvalFrameDefault
> W0509 07:54:10.226372 22881 init.cc:217]     @     0x561430597389 _PyEval_EvalCodeWithName
> W0509 07:54:10.227146 22881 init.cc:217]     @     0x5614305984c5 _PyFunction_FastCallDict
> terminate called recursively
> W0509 07:54:10.227896 22881 init.cc:217]     @     0x5614305b7a73 _PyObject_Call_Prepend
> W0509 07:54:10.228734 22881 init.cc:217]     @     0x5614305a9fde PyObject_Call
> Aborted (core dumped)

My environment:
paddlepaddle-gpu 1.7.1.post107
GTX 1080Ti *2

This is not the first time that core dump happened in the same training task. I think it has something to do with `max_iters`, because when reduces or changes `max_iters`, it won't happen again, but I don't know why and where I did wrong. Thnaks!

这种情况发生蛮多次了，最近项目比较急，每次都是到最后一20个iteration的时候core dump，太影响进度了。。。顺便问下，如果要在训练的时候恢复到某个节点，那训练还是会严格按照配置文件里的配置，比如接着的iteration的learning rate还会是接续下来的么，比如这里用到的lr是跟iteration有关系的，利用checkpoints回复训练的时候paddle在这个是怎么操作的，是严格按照config yaml么，还是会认为是新的训练，lr从warmup开始？

**Comment by nihuizhidao** [comment]
会不会是最后的一个iteration发生了内存溢出？并且不是GPU计算的时候发生的。

**Comment by nihuizhidao** [comment]
我现在调整了把 `worker_num: 8` 调整为 `worker_num: 4` 试试，怀疑是进程太多了，但是还是要等很久出结果，这个问题有点严重啊。。

**Comment by nihuizhidao** [comment]
这个是训练初期时的`htop`内存使用情况：

![image](https://user-images.githubusercontent.com/26674015/81459182-24370780-91d1-11ea-94f9-fc30dfc43798.png)

**Comment by qingqing01** [comment]
@Niandalu 看着是eval推出时问了问题，你可以先训练时不加--eval，最后训练完了，再做评估。 另外，你的系统环境是啥？

**Comment by heavengate** [comment]
麻烦问下你的操作系统版本，还有opencv版本是啥，可以通过如下两条命令查询
```
uname -a
```
```
python -c "import cv2; print(cv2.__version__)"
```

**Comment by heavengate** [comment]
> 如果要在训练的时候恢复到某个节点，那训练还是会严格按照配置文件里的配置，比如接着的iteration的learning rate还会是接续下来的么，比如这里用到的lr是跟iteration有关系的，利用checkpoints回复训练的时候paddle在这个是怎么操作的

训练保存checkpoint会记录learning rate这些状态的，`resume`是重新加载这些状态训练，learning rate还有当前iter数都会还原，直接通过`--resume`指定checkpoint继续训练就可以了~

**Comment by heavengate** [comment]
```
W0509 07:54:10.215291 22881 init.cc:217] @ 0x7f9ae76d4b27 pyopencv_cv_imdecode()
W0509 07:54:10.216156 22881 init.cc:217] @ 0x5614305ebab4 
```
看你报错的栈信息是opencv里面，可能是opencv的这个问题 https://github.com/opencv/opencv/issues/15691，可以尝试一下更新opencv的版本试下~

**Comment by nihuizhidao** [comment]
> 麻烦问下你的操作系统版本，还有opencv版本是啥，可以通过如下两条命令查询
> 
> ```
> uname -a
> ```
> 
> ```
> python -c "import cv2; print(cv2.__version__)"
> ```

Linux DL 4.15.0-72-generic #81~16.04.1-Ubuntu SMP Tue Nov 26 16:34:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
OpenCV版本 3.4.2

**Comment by nihuizhidao** [comment]
请问PaddlePaddle有没有推荐的OpenCV版本？或者说在我这个环境下测试通过的OpenCV版本能否提供下？

**Comment by qingqing01** [comment]
@nihuizhidao  参考 https://github.com/PaddlePaddle/PaddleDetection/issues/243 

```
pip uninstall opencv-python
pip install opencv-python==4.0.0.21
```

**Comment by nihuizhidao** [comment]
> @nihuizhidao 参考 #243
> 
> ```
> pip uninstall opencv-python
> pip install opencv-python==4.0.0.21
> ```

我按照这个，更新了opencv的版本，结果还是core dump，但是貌似已经没有显示opencv的问题了，你看这个是否还是opencv得问题呢？另外，在这个conda环境里，我是新建后直接安装paddle，过程中opencv是作为依赖自己自动装的，是不是这个也会有问题？因为时间紧迫，所以我只能尝试先训练，再评估模型了，但是这个还会是个问题。。。

这次的报错信息如下：

> 2020-05-11 04:23:29,031-INFO: Best test box ap: 0.305600906965023, in iter: 22400
> 2020-05-11 04:23:53,331-INFO: iter: 24820, lr: 0.000000, 'loss': '11.442607', time: 1.609, eta: 0:04:49
> 2020-05-11 04:24:16,966-INFO: iter: 24840, lr: 0.000000, 'loss': '10.955601', time: 1.228, eta: 0:03:16
> 2020-05-11 04:24:39,993-INFO: iter: 24860, lr: 0.000000, 'loss': '11.790080', time: 1.145, eta: 0:02:40
> 2020-05-11 04:25:03,532-INFO: iter: 24880, lr: 0.000000, 'loss': '11.401484', time: 1.182, eta: 0:02:21
> 2020-05-11 04:25:26,744-INFO: iter: 24900, lr: 0.000000, 'loss': '12.151728', time: 1.159, eta: 0:01:55
> 2020-05-11 04:25:50,274-INFO: iter: 24920, lr: 0.000000, 'loss': '12.266766', time: 1.179, eta: 0:01:34
> 2020-05-11 04:26:13,564-INFO: iter: 24940, lr: 0.000000, 'loss': '12.069195', time: 1.158, eta: 0:01:09
> 2020-05-11 04:26:36,928-INFO: iter: 24960, lr: 0.000000, 'loss': '11.722236', time: 1.173, eta: 0:00:46
> 2020-05-11 04:27:00,678-INFO: iter: 24980, lr: 0.000000, 'loss': '12.319008', time: 1.179, eta: 0:00:23
> 2020-05-11 04:27:22,530-INFO: Save model to output/yolov3_tt_v1/model_final.
> 2020-05-11 04:27:29,555-INFO: Test iter 0
> 2020-05-11 04:27:30,554-INFO: Test finish iter 7
> 2020-05-11 04:27:30,554-INFO: Total number of images: 65, inference time: 52.4803619556214 fps.
> loading annotations into memory...
> Done (t=0.00s)
> creating index...
> index created!
> 2020-05-11 04:27:30,597-INFO: Start evaluate...
> Loading and preparing results...
> DONE (t=0.01s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type *bbox*
> DONE (t=0.25s).
> Accumulating evaluation results...
> DONE (t=0.17s).
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.303
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.515
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.307
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.270
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.568
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.293
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.305
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.372
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.373
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.329
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.600
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.369
> 2020-05-11 04:27:31,060-INFO: Best test box ap: 0.305600906965023, in iter: 22400
> terminate called recursively
> terminate called without an active exception
> W0511 04:27:31.763053 30522 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
> W0511 04:27:31.763120 30522 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
> W0511 04:27:31.763137 30522 init.cc:214] The detail failure signal is:
> 
> W0511 04:27:31.763156 30522 init.cc:217] *** Aborted at 1589142451 (unix time) try "date -d @1589142451" if you are using GNU date ***
> W0511 04:27:31.768396 30522 init.cc:217] PC: @                0x0 (unknown)
> W0511 04:27:31.768548 30522 init.cc:217] *** SIGABRT (@0x3e8000062ad) received by PID 25261 (TID 0x7f4f54ff9700) from PID 25261; stack trace: ***
> W0511 04:27:31.773273 30522 init.cc:217]     @     0x7f5224733390 (unknown)
> W0511 04:27:31.777858 30522 init.cc:217]     @     0x7f522438d428 gsignal
> W0511 04:27:31.781590 30522 init.cc:217]     @     0x7f522438f02a abort
> W0511 04:27:31.783998 30522 init.cc:217]     @     0x7f5207acb84a __gnu_cxx::__verbose_terminate_handler()
> W0511 04:27:31.785904 30522 init.cc:217]     @     0x7f5207ac9f47 __cxxabiv1::__terminate()
> W0511 04:27:31.788244 30522 init.cc:217]     @     0x7f5207ac9f7d std::terminate()
> W0511 04:27:31.790314 30522 init.cc:217]     @     0x7f5207ac9c5a __gxx_personality_v0
> W0511 04:27:31.792838 30522 init.cc:217]     @     0x7f522352db97 _Unwind_ForcedUnwind_Phase2
> W0511 04:27:31.795353 30522 init.cc:217]     @     0x7f522352de7d _Unwind_ForcedUnwind
> W0511 04:27:31.797935 30522 init.cc:217]     @     0x7f5224732070 __GI___pthread_unwind
> W0511 04:27:31.800487 30522 init.cc:217]     @     0x7f522472a845 __pthread_exit
> W0511 04:27:31.801246 30522 init.cc:217]     @     0x55b0fc0b5059 PyThread_exit_thread
> W0511 04:27:31.801447 30522 init.cc:217]     @     0x55b0fbf3ac10 PyEval_RestoreThread.cold.799
> W0511 04:27:31.802937 30522 init.cc:217]     @     0x7f51faae021c (unknown)
> W0511 04:27:31.803853 30522 init.cc:217]     @     0x55b0fc03bab4 _PyMethodDef_RawFastCallKeywords
> W0511 04:27:31.804679 30522 init.cc:217]     @     0x55b0fc03bbd1 _PyCFunction_FastCallKeywords
> W0511 04:27:31.805505 30522 init.cc:217]     @     0x55b0fc0a257b _PyEval_EvalFrameDefault
> W0511 04:27:31.806263 30522 init.cc:217]     @     0x55b0fbfe7389 _PyEval_EvalCodeWithName
> W0511 04:27:31.807044 30522 init.cc:217]     @     0x55b0fbfe84c5 _PyFunction_FastCallDict
> W0511 04:27:31.807790 30522 init.cc:217]     @     0x55b0fc007a73 _PyObject_Call_Prepend
> W0511 04:27:31.808176 30522 init.cc:217]     @     0x55b0fc04f27a slot_tp_call
> W0511 04:27:31.808938 30522 init.cc:217]     @     0x55b0fc0502db _PyObject_FastCallKeywords
> W0511 04:27:31.809756 30522 init.cc:217]     @     0x55b0fc0a2146 _PyEval_EvalFrameDefault
> W0511 04:27:31.810518 30522 init.cc:217]     @     0x55b0fbfe83fb _PyFunction_FastCallDict
> W0511 04:27:31.811269 30522 init.cc:217]     @     0x55b0fc007a73 _PyObject_Call_Prepend
> W0511 04:27:31.811656 30522 init.cc:217]     @     0x55b0fc04f27a slot_tp_call
> W0511 04:27:31.812420 30522 init.cc:217]     @     0x55b0fc0502db _PyObject_FastCallKeywords
> W0511 04:27:31.813239 30522 init.cc:217]     @     0x55b0fc0a2a39 _PyEval_EvalFrameDefault
> W0511 04:27:31.813992 30522 init.cc:217]     @     0x55b0fbfe7389 _PyEval_EvalCodeWithName
> W0511 04:27:31.814757 30522 init.cc:217]     @     0x55b0fbfe84c5 _PyFunction_FastCallDict
> W0511 04:27:31.815510 30522 init.cc:217]     @     0x55b0fc007a73 _PyObject_Call_Prepend
> W0511 04:27:31.816339 30522 init.cc:217]     @     0x55b0fbff9fde PyObject_Call
> Aborted (core dumped)

**Comment by qingqing01** [comment]
@nihuizhidao 这个只是最后退出时的错误，不影响评估结果，我们再看下。

**Comment by heavengate** [comment]
@nihuizhidao 您好，按这样修改试下呢~  https://github.com/PaddlePaddle/PaddleDetection/pull/632

**Comment by nihuizhidao** [comment]
> @nihuizhidao 您好，按这样修改试下呢~ #632
> 或者试下在`configs/yolov3_reader.cfg`里面修改`EvalReader`配置，设置`use_process: true` `worker_num: 2`试下
> 
> ```
> EvalReader:
>   inputs_def:
>     fields: ['image', 'im_size', 'im_id']
>     num_max_boxes: 50
>   dataset:
>     !COCODataSet
>       image_dir: val2017
>       anno_path: annotations/instances_val2017.json
>       dataset_dir: dataset/coco
>       with_background: false
>   sample_transforms:
>     - !DecodeImage
>       to_rgb: True
>     - !ResizeImage
>       target_size: 608
>       interp: 2
>     - !NormalizeImage
>       mean: [0.485, 0.456, 0.406]
>       std: [0.229, 0.224, 0.225]
>       is_scale: True
>       is_channel_first: false
>     - !PadBox
>       num_max_boxes: 50
>     - !Permute
>       to_bgr: false
>       channel_first: True
>   batch_size: 8
>   drop_empty: false
>   use_process: true
>   worker_num: 2
>   bufsize: 16
> ```

@heavengate 谢谢，你提供的这两个方法， #632 这个尝试了不行，最后终端log会卡死不动，但是也没有显示“core dump”，第二个方法，修改配置yaml文件：

>   use_process: true
>   worker_num: 2

这个解决了core dump的问题，最终到eval时是可以正常退出程序的。
非常感谢！

**Comment by heavengate** [comment]
> > @nihuizhidao 您好，按这样修改试下呢~ #632
> > 或者试下在`configs/yolov3_reader.cfg`里面修改`EvalReader`配置，设置`use_process: true` `worker_num: 2`试下
> > ```
> > EvalReader:
> >   inputs_def:
> >     fields: ['image', 'im_size', 'im_id']
> >     num_max_boxes: 50
> >   dataset:
> >     !COCODataSet
> >       image_dir: val2017
> >       anno_path: annotations/instances_val2017.json
> >       dataset_dir: dataset/coco
> >       with_background: false
> >   sample_transforms:
> >     - !DecodeImage
> >       to_rgb: True
> >     - !ResizeImage
> >       target_size: 608
> >       interp: 2
> >     - !NormalizeImage
> >       mean: [0.485, 0.456, 0.406]
> >       std: [0.229, 0.224, 0.225]
> >       is_scale: True
> >       is_channel_first: false
> >     - !PadBox
> >       num_max_boxes: 50
> >     - !Permute
> >       to_bgr: false
> >       channel_first: True
> >   batch_size: 8
> >   drop_empty: false
> >   use_process: true
> >   worker_num: 2
> >   bufsize: 16
> > ```
> 
> @heavengate 谢谢，你提供的这两个方法， #632 这个尝试了不行，最后终端log会卡死不动，但是也没有显示“core dump”，第二个方法，修改配置yaml文件：
> 
> > use_process: true
> > worker_num: 2
> 
> 这个解决了core dump的问题，最终到eval时是可以正常退出程序的。
> 非常感谢！

您好， #632 修改过一版，麻烦问下用最新版的也不行么？

**Comment by nihuizhidao** [comment]
> > > @nihuizhidao 您好，按这样修改试下呢~ #632
> > > 或者试下在`configs/yolov3_reader.cfg`里面修改`EvalReader`配置，设置`use_process: true` `worker_num: 2`试下
> > > ```
> > > EvalReader:
> > >   inputs_def:
> > >     fields: ['image', 'im_size', 'im_id']
> > >     num_max_boxes: 50
> > >   dataset:
> > >     !COCODataSet
> > >       image_dir: val2017
> > >       anno_path: annotations/instances_val2017.json
> > >       dataset_dir: dataset/coco
> > >       with_background: false
> > >   sample_transforms:
> > >     - !DecodeImage
> > >       to_rgb: True
> > >     - !ResizeImage
> > >       target_size: 608
> > >       interp: 2
> > >     - !NormalizeImage
> > >       mean: [0.485, 0.456, 0.406]
> > >       std: [0.229, 0.224, 0.225]
> > >       is_scale: True
> > >       is_channel_first: false
> > >     - !PadBox
> > >       num_max_boxes: 50
> > >     - !Permute
> > >       to_bgr: false
> > >       channel_first: True
> > >   batch_size: 8
> > >   drop_empty: false
> > >   use_process: true
> > >   worker_num: 2
> > >   bufsize: 16
> > > ```
> > 
> > 
> > @heavengate 谢谢，你提供的这两个方法， #632 这个尝试了不行，最后终端log会卡死不动，但是也没有显示“core dump”，第二个方法，修改配置yaml文件：
> > > use_process: true
> > > worker_num: 2
> > 
> > 
> > 这个解决了core dump的问题，最终到eval时是可以正常退出程序的。
> > 非常感谢！
> 
> 您好， #632 修改过一版，麻烦问下用最新版的也不行么？

对的，我昨天经行的两个测试，第一种方法使用的就是这个最新版的  `commit 91823e97bb3e2cc451c9cfaa90ea3a134c58a05e` 
最终的解决是第二种方法，使用了

> use_process: true
> worker_num: 2

并且没有改动`ppdet/data/parallel_map.py` 文件中的那两处。

限制了`worker_num: 2`可能会影响评估效率吧，但是这个是目前能用的解决方案了。

请问为什么是限制worker为2呢？是跟我的GPU数有关系么？

如果有任何更有效的方法，我也愿意尝试的~

**Comment by heavengate** [comment]
> #632

评估的时候预处理不多，没必要开很多子进程加速，你如果觉得影响效率可以把`worker_num`设置大一点，应该对评估效率影响不大的

**Comment by flishwnag** [comment]
我也遇到这个问题，训练结束后无法正常退出。怀疑跟 use_process: False有关。
