### ISSUE TITLE
加入了新的数据均衡策略，前期训练没有问题，但是训练到三万多batch时报下面的错

### ISSUE THREAD

**Issue by zhenjiaa** [PaddlePaddle/PaddleDetection#6190]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

W0614 00:04:21.023511 39104 init.cc:239] *** Aborted at 1655136261 (unix time) try "date -d @1655136261" if you are using GNU date ***
W0614 00:04:21.038332 39104 init.cc:239] PC: @                0x0 (unknown)
W0614 00:04:21.043859 39104 init.cc:239] *** SIGABRT (@0x8ff6) received by PID 36854 (TID 0x7f29887ff700) from PID 36854; stack trace: ***
W0614 00:04:21.133425 39104 init.cc:239]     @     0x7f2b7e9f1f3e google::(anonymous namespace)::FailureSignalHandler()
W0614 00:04:21.136157 39104 init.cc:239]     @     0x7f2bd83d5630 (unknown)
W0614 00:04:21.138651 39104 init.cc:239]     @     0x7f2bd802e387 __GI_raise
W0614 00:04:21.140962 39104 init.cc:239]     @     0x7f2bd802fa78 __GI_abort
W0614 00:04:21.156807 39104 init.cc:239]     @     0x7f2bc127684a __gnu_cxx::__verbose_terminate_handler()
W0614 00:04:21.158586 39104 init.cc:239]     @     0x7f2bc1274f47 __cxxabiv1::__terminate()
W0614 00:04:21.160459 39104 init.cc:239]     @     0x7f2bc1274f7d std::terminate()
W0614 00:04:21.162225 39104 init.cc:239]     @     0x7f2bc1274c5a __gxx_personality_v0
W0614 00:04:21.164331 39104 init.cc:239]     @     0x7f2bd1124b97 _Unwind_ForcedUnwind_Phase2
W0614 00:04:21.166432 39104 init.cc:239]     @     0x7f2bd1124e7d _Unwind_ForcedUnwind
W0614 00:04:21.168574 39104 init.cc:239]     @     0x7f2bd83d4362 __GI___pthread_unwind
W0614 00:04:21.170715 39104 init.cc:239]     @     0x7f2bd83ceef7 __pthread_exit
W0614 00:04:21.175158 39104 init.cc:239]     @     0x5650d0f07e59 PyThread_exit_thread
W0614 00:04:21.175314 39104 init.cc:239]     @     0x5650d0d8dc17 PyEval_RestoreThread.cold.798
W0614 00:04:21.200261 39104 init.cc:239]     @     0x7f2b7e67e599 pybind11::gil_scoped_release::~gil_scoped_release()
W0614 00:04:21.201328 39104 init.cc:239]     @     0x7f2b7e82e391 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybind10BindReaderEPNS_6moduleEEUlRNS2_9operators6reader40OrderedMultiDeviceLoDTensorBlockingQueueERKSt6vectorINS2_9framework9LoDTensorESaISC_EEE2_bJS9_SG_EJNS_4nameENS_9is_methodENS_7siblingENS_10call_guardIJNS_18gil_scoped_releaseEEEEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNES11_
W0614 00:04:21.204008 39104 init.cc:239]     @     0x7f2b7e69be9e pybind11::cpp_function::dispatcher()
W0614 00:04:21.204504 39104 init.cc:239]     @     0x5650d0e89744 _PyMethodDef_RawFastCallKeywords
W0614 00:04:21.204897 39104 init.cc:239]     @     0x5650d0e89861 _PyCFunction_FastCallKeywords
W0614 00:04:21.205283 39104 init.cc:239]     @     0x5650d0ef56e8 _PyEval_EvalFrameDefault
W0614 00:04:21.205646 39104 init.cc:239]     @     0x5650d0e3981a _PyEval_EvalCodeWithName
W0614 00:04:21.205992 39104 init.cc:239]     @     0x5650d0e3a635 _PyFunction_FastCallDict
W0614 00:04:21.206372 39104 init.cc:239]     @     0x5650d0ef2232 _PyEval_EvalFrameDefault
W0614 00:04:21.206702 39104 init.cc:239]     @     0x5650d0e88ccb _PyFunction_FastCallKeywords
W0614 00:04:21.207073 39104 init.cc:239]     @     0x5650d0ef0a93 _PyEval_EvalFrameDefault
W0614 00:04:21.207401 39104 init.cc:239]     @     0x5650d0e88ccb _PyFunction_FastCallKeywords
W0614 00:04:21.207787 39104 init.cc:239]     @     0x5650d0ef0a93 _PyEval_EvalFrameDefault
W0614 00:04:21.208134 39104 init.cc:239]     @     0x5650d0e3a56b _PyFunction_FastCallDict
W0614 00:04:21.208477 39104 init.cc:239]     @     0x5650d0e58e53 _PyObject_Call_Prepend
W0614 00:04:21.208858 39104 init.cc:239]     @     0x5650d0e4bdbe PyObject_Call
W0614 00:04:21.209017 39104 init.cc:239]     @     0x5650d0f48817 t_bootstrap
W0614 00:04:21.209107 39104 init.cc:239]     @     0x5650d0f03788 pythread_wrapper
ERROR 2022-06-14 00:08:06,379 utils.py:441] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0] was aborted. Please check its log.
Traceback (most recent call last):
  File "/root/user/soft_env/anaconda3/lib/python3.7/site-packages/paddle/distributed/utils.py", line 425, in watch_local_trainers
    terminate_local_procs(procs)
  File "/root/user/soft_env/anaconda3/lib/python3.7/site-packages/paddle/distributed/utils.py", line 256, in terminate_local_procs
    p.log_fn.close()
AttributeError: 'NoneType' object has no attribute 'close'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/user/soft_env/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/user/soft_env/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/user/soft_env/anaconda3/lib/python3.7/site-packages/paddle/distributed/launch.py", line 237, in <module>
    launch(args)
  File "/root/user/soft_env/anaconda3/lib/python3.7/site-packages/paddle/distributed/launch.py", line 220, in launch
    alive = watch_local_trainers(procs, cluster.trainers_nranks())
  File "/root/user/soft_env/anaconda3/lib/python3.7/site-packages/paddle/distributed/utils.py", line 442, in watch_local_trainers
    terminate_local_procs(procs)
  File "/root/user/soft_env/anaconda3/lib/python3.7/site-packages/paddle/distributed/utils.py", line 256, in terminate_local_procs
    p.log_fn.close()
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by zoooo0820** [comment]
paddle和paddledetection的版本分别是多少呢，另外具体改动了什么地方呢
