### ISSUE TITLE
30分钟快速入门官方文档中某个单词拼写错误

### ISSUE THREAD

**Issue by QixingJiang** [PaddlePaddle/PaddleDetection#6191]
### 文档链接&描述 Document Links & Description

在发布的release/2.4 版本中 
PaddleDetection/docs/tutorials/GETTING_STARTED_cn.md文件中：
6 预测
XXXXXX
·设置参数预测
XXX
--use_vdl=Ture

### 请提出你的建议 Please give your suggestion

这里的Ture应该为True

**Comment by zoooo0820** [comment]
感谢反馈，我们已经提交pr修复，预计晚些时候可以合入。如果您愿意的话，也欢迎在后续发现类似问题后提交PR修复，帮助我们做得更好~
