### ISSUE TITLE
PPYOLOE模型大小问题

### ISSUE THREAD

**Issue by jo-dean** [PaddlePaddle/PaddleDetection#6194]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/38728358/173517046-1d6e9765-897b-4c69-83c4-d12f5d455c2b.png)
图中PPyoloe-s模型大小显示7.9M，为什么右边下载的model有31M，训练自己的数据集导出的模型也有29M的参数？

**Comment by zoooo0820** [comment]
params是参数数量，按`float32`类型存储的话，每个参数占4B,  所以实际模型存储大小约为参数数量的4倍左右
