### ISSUE TITLE
模型不包含后处理

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleDetection#6195]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如果模型输出是不带有后处理，那么在onnxruntime中有推理实现的方式嘛，谢谢，如果麻烦告诉我一下在那个位置

**Comment by zoooo0820** [comment]
各个模型的后处理不尽相同，可以参考以下部分：
- 检测模型、实例分割模型请见[这里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/python/infer.py)。主要是`Detecor`类中的`postprocess`部分。部分模型特殊会有自己的特殊逻辑（如`solov2` / 未包含后处理导出的`picodet`等)
- 关键点模型请见[这里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/python/keypoint_infer.py) ，同样也是关注`postprocess`部分
