### ISSUE TITLE
obuject-detect for movie

### ISSUE THREAD

**Issue by ybonzou** [PaddlePaddle/PaddleDetection#6204]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

What are the options for real-time object detection in video using Paddle-Detection?
(For example) --video 0
etc.

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by heavengate** [comment]
If you are using GPU like V100/2080ti, PP-YOLOE is recommend, and if you are using CPU, you can try PP-PicoDet

**Comment by ybonzou** [comment]
Thanks!!  I understand.
But I am a very beginner.
I have a GPU on board.
I would like to know how to import video footage from a video or camera.
