### ISSUE TITLE
ppyoloe部署相关

### ISSUE THREAD

**Issue by heng3366** [PaddlePaddle/PaddleDetection#6205]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用ppyoloe，按照markdown文件训练了自己的数据集，训练成功效果也不错，但有2个疑问：
1、如果需要部署动态图模型的话，有无相关参数开启既可自己选择模型版本，如果无，是不是需要自己修改tools./train.pyhe  infer.py部分的代码，有无相关参考提供修改（主要使用熟悉的框架不是paddle）
2、如果不可以修改成动态图模型部署，有无其他yolo版本可使用参考

**Comment by heavengate** [comment]
自己训练的模型导出部署可以参考
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe#exporting-models
其中`-o weight`指定训练过程中保存在权重即可
