### ISSUE TITLE
solov2,  use_shared_memory=True时，报错

### ISSUE THREAD

**Issue by EthanChen1234** [PaddlePaddle/PaddleDetection#6212]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

1、代码
  self.dataloader = DataLoader(
      dataset=self.dataset,
      batch_sampler=self._batch_sampler,
      collate_fn=self._batch_transforms,
      num_workers=worker_num,
      return_list=return_list,
      use_shared_memory=True/False)  # 设置为True时，报错

2、详细报错文档
[use_shared_memory.log.tar.gz](https://github.com/PaddlePaddle/PaddleDetection/files/8918438/use_shared_memory.log.tar.gz)

### 复现环境 Environment

pp: 2.2.2
ppdet: 2.4
python: 3.7.6
cuda: 10.1
cudnn: 7

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by heavengate** [comment]
你好，报错信息麻烦贴出来一下，另外你可以确认一下`/dev/shm/`下的空间是否足够，如果不够的话不建议开`use_shared_memory`

**Comment by EthanChen1234** [comment]
>

> 你好，报错信息麻烦贴出来一下，另外你可以确认一下`/dev/shm/`下的空间是否足够，如果不够的话不建议开`use_shared_memory`

1、报错信息，在附件里面
2、/dev/shm/ 是足够的，11G

**Comment by zgsxwsdxg** [comment]
> 2、/dev/shm/ 是足够的，11G

您好，问题解决了么？如何解决的？我已遇到了同样的问题，谢谢！期待您的回答！
