### ISSUE TITLE
PPYOLOE，训练300个epoch,20000多张图像，num_work：8   4张卡 每张卡batchsize16，要训练 30多个小时？ 有什么办法能快点吗？

### ISSUE THREAD

**Issue by LYHTZHANGJIANG** [PaddlePaddle/PaddleDetection#6217]
### 问题描述 Please describe your issue

PPYOLOE，训练300个epoch,20000多张图像，num_work：8   4张卡 每张卡batchsize16，要训练 30多个小时？ 有什么办法能快点吗？

**Comment by jerrywgz** [comment]
1. 可以尝试将reader配置文件中的worker_num调大
2. 加载ppyoloe在coco数据集训练好的模型，https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe#model-zoo 然后调低学习率，减小epoch数
