### ISSUE TITLE
PaddleDetection把pretrain_weights设置为false是不是就可以不使用预训练模型了？

### ISSUE THREAD

**Issue by yang100123** [PaddlePaddle/PaddleDetection#6218]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddledet2.4.0 paddlepaddle2.3.0
训练ppyolov2_r50vd_dcn_voc的时候发现配置文件里并没有配置pretrain_weights，但开始训练后还是要下载预训练模型，是不是我添加一个pretrain_weights: false 配置，就可以不使用预训练模型，自己从头训练？

**Comment by jerrywgz** [comment]
配置文件中设置`pretrain_weights: ~` 即可
