### ISSUE TITLE
关于roi_align

### ISSUE THREAD

**Issue by a1056632260** [PaddlePaddle/PaddleDetection#6226]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在instance as query论文复现过程中，发现mmdet和paddledet通过roi_align计算出来的结果不一致，请问二者底层实现是否有区别？

**Comment by jerrywgz** [comment]
目前mmdet中使用的roi align对应的op是https://mmcv-jm.readthedocs.io/en/latest/_modules/mmcv/ops/roi_align.html ，对应的接口和paddle中的roi align是一致的，可以确认下是不是参数接口的差异
