### ISSUE TITLE
新版本的C++部署报错

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/PaddleDetection#6228]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

1.使用paddle_inference2.3进行部署，cmake时一切正常。使用vs2019生成工程时也提示正常，但运行代码时提示缺少paddle2onnx.dll
在paddle_inference包中寻找paddle2onnx.dll并复制到release，提示程序运行错误。
![image](https://user-images.githubusercontent.com/46549313/174471856-05c3ceb3-7369-49ef-89dc-efcecc9f843a.png)

将paddle_inference更换为cpu版本再次尝试，依然报错。
2.使用去年年底的paddle_inference2.2旧版本进行部署，则运行正常。
3.此外发现还有两个小问题，
（1）当输入图片路径为绝对路径时（代码例子：>.\main --model_dir=D:/bushu/model_set/yolov3_mbv1/model --image_file=D:/bushu/model_set/yolov3_mbv1/images/1.jpg，文件保存不成功，因为main.cc中：
                output_path +=
                    image_file_path.substr(image_file_path.find_last_of('/') + 1);
貌似没有正确运行。
更改为：output_path += image_file_path.substr(image_file_path.find_last_of(OS_PATH_SEP) + 1);
且命令为：
正常运行。这些正常运行都是使用的paddle_inference2.2，paddle_inference2.3一直如上提示的错误。
（2）当长宽不一致时，预测结果不对，本人之前曾经修改过，但咱们官方一直没有更改，你们帮我把这个问题答复完之后，我最近找找之前如何修改的，把修改的地方给提交一下。

### 复现环境 Environment

paddle版本：2.3.0.post112
cmake：3.23.2
vs：2019
opencv：3.4.6
paddle_inference:2.3
cuda:11.2,v11.2.67
cudnn:8.2.1
tensorrt:8.01 GA 

同时还在cpu环境下进行测试。

本人详细记录了每一步，有详细的操作记录，因为最近要发布一个教程，现在还不方便公开放在这里，麻烦联系手机号：15261652233，给您看详细记录。非常感谢！

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by JackDance** [comment]
@qiyuezhiguang 同问，当执行生成的main.exe时，输入命令后cmd中没有返回任何信息，过一会就结束了是什么问题呢

**Comment by JackDance** [comment]
2.3版本的paddle_inference会发生题主所说的错误，用2.2可以生成main.exe，执行命令时不发生paddle2onnx.dll找不到的情况。但是用2.2生成之后，执行main.exe没有返回任何信息，过一会就结束了，跟没执行一样

**Comment by dengmingD** [comment]
参考解决
1.model文件不全
2.缺少dll，把third_party\install里的dll拷到Release目录下
如果不行再找其他方案

**Comment by dengmingD** [comment]
<img width="379" alt="8F5266FA-4C57-4ab6-AA4D-ED39BA9A16FE" src="https://user-images.githubusercontent.com/72127773/175248253-8c7bf5ac-3043-4a5c-8540-e4831c1cf048.png">
model文件如上图

**Comment by dengmingD** [comment]
Release中的dll
<img width="430" alt="299B7735-5EA0-48f4-8840-2E7BF1BA2B53" src="https://user-images.githubusercontent.com/72127773/175248652-8e0f7047-ffa1-48b2-b5d3-512a92ada022.png">
