### ISSUE TITLE
安装paddledetection之后进行检测 出现错误,在网络上找不到一样的的error

### ISSUE THREAD

**Issue by ademengke** [PaddlePaddle/PaddleDetection#6229]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

在我运行paddledetection检测程序python ppdet/modeling/tests/test_architectures.py 和尝试进行快速图像识别的时候出现问题,以下是我的错误复现:

(paddle) C:\Users\aaa\Desktop\Q4\pythonProject>python F:/paddle/PaddleDetection/tools/train.py -c configs/picodet/picodet_s_416_coco_lcnet.yml --slim_config   F:/paddle/PaddleDetection/configs/slim/quant/picodet_s_416_lcnet_quant.ym
l --eval
E:\anaconda\envs\paddle\lib\site-packages\paddle\tensor\creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any
 behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "F:\paddle\PaddleDetection\tools\train.py", line 32, in <module>        
    from ppdet.core.workspace import load_config, merge_config                 
  File "F:\paddle\PaddleDetection\ppdet\__init__.py", line 15, in <module>     
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "F:\paddle\PaddleDetection\ppdet\data\__init__.py", line 16, in <module>
    from . import transform
  File "F:\paddle\PaddleDetection\ppdet\data\transform\__init__.py", line 15, in <module>
    from . import operators
  File "F:\paddle\PaddleDetection\ppdet\data\transform\operators.py", line 44, in <module>
    from ppdet.modeling import bbox_utils
  File "F:\paddle\PaddleDetection\ppdet\modeling\__init__.py", line 23, in <module>
    from . import heads
  File "F:\paddle\PaddleDetection\ppdet\modeling\heads\__init__.py", line 17, in <module>
    from . import yolo_head
  File "F:\paddle\PaddleDetection\ppdet\modeling\heads\yolo_head.py", line 26, in <module>
    from ..losses import IouLoss
  File "F:\paddle\PaddleDetection\ppdet\modeling\losses\__init__.py", line 26, in <module>
    from . import detr_loss
  File "F:\paddle\PaddleDetection\ppdet\modeling\losses\detr_loss.py", line 24, in <module>
    from ..transformers import bbox_cxcywh_to_xyxy, sigmoid_focal_loss
  File "F:\paddle\PaddleDetection\ppdet\modeling\transformers\__init__.py", line 17, in <module>
    from . import matchers
  File "F:\paddle\PaddleDetection\ppdet\modeling\transformers\matchers.py", line 25, in <module>
    from scipy.optimize import linear_sum_assignment
  File "e:\anaconda\envs\yolox\lib\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "e:\anaconda\envs\yolox\lib\site-packages\scipy\_distributor_init.py", line 59, in <module>
    WinDLL(os.path.abspath(filename))
  File "E:\anaconda\envs\paddle\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'e:\anaconda\envs\yolox\lib\site-packages\scipy\.libs\libbanded5x.UALCZY4KXIWFSNTUQY2S5KECOR3WRBFR.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with construct
or syntax.

### 复现环境 Environment

(paddle) C:\Users\aaa\Desktop\Q4\pythonProject>pip list
Package                 Version
----------------------- ---------------------
absl-py                 1.0.0
aiohttp                 3.8.1
aiosignal               1.2.0
apex                    0.1
argon2-cffi             21.3.0
argon2-cffi-bindings    21.2.0
astor                   0.8.1
asttokens               2.0.5
async-timeout           4.0.2
atomicwrites            1.4.0
attrs                   21.4.0
backcall                0.2.0
beautifulsoup4          4.11.1
bleach                  5.0.0
blinker                 1.4
brotlipy                0.7.0
cachetools              5.0.0
certifi                 2022.5.18.1
cffi                    1.15.0
charset-normalizer      2.0.12
click                   8.1.3
cloudpickle             2.0.0
colorama                0.4.4
cryptography            36.0.2
cxxfilt                 0.3.0
cycler                  0.11.0
Cython                  0.29.28
cytoolz                 0.11.2
dask                    2022.5.0
debugpy                 1.6.0
decorator               5.1.1
defusedxml              0.7.1
dlib                    19.24.0
entrypoints             0.4
et-xmlfile              1.1.0
executing               0.8.3
fastjsonschema          2.15.3
flatbuffers             2.0
fonttools               4.33.3
frozenlist              1.3.0
fsspec                  2022.3.0
google-auth             2.6.6
google-auth-oauthlib    0.4.6
grpcio                  1.46.0
h5py                    3.6.0
idna                    3.3
imagecodecs             2022.2.22
imageio                 2.19.1
importlib-metadata      4.11.3
iniconfig               1.1.1
ipykernel               6.13.0
ipython-genutils        0.2.0
ipywidgets              7.7.0
jedi                    0.18.1
Jinja2                  3.1.2
joblib                  1.1.0
jsonschema              4.5.1
jupyter                 1.0.0
jupyter-client          7.3.1
jupyter-console         6.4.3
jupyter-core            4.10.0
jupyterlab-pygments     0.2.2
jupyterlab-widgets      1.1.0
kiwisolver              1.4.2
lap                     0.4.0
locket                  1.0.0
loguru                  0.6.0
lxml                    4.8.0
Markdown                3.3.7
MarkupSafe              2.1.1
matplotlib              3.5.2
matplotlib-inline       0.1.3
mistune                 0.8.4
motmetrics              1.2.5
multidict               6.0.2
munkres                 1.1.4
nbclient                0.6.3
nbconvert               6.5.0
nbformat                5.4.0
nest-asyncio            1.5.5
networkx                2.8
ninja                   1.10.2.3
notebook                6.4.11
numpy                   1.22.4
oauthlib                3.2.0
onnx                    1.11.0
onnx-simplifier         0.3.5
onnxoptimizer           0.2.7
onnxruntime             1.8.0
opencv-python           4.5.5.64
openpyxl                3.0.10
opt-einsum              3.3.0
packaging               21.3
paddle-bfloat           0.1.2
paddledet               2.1.0
paddlepaddle-gpu        2.3.0.post112
paddleslim              2.2.2
pandas                  1.4.2
pandocfilters           1.5.0
parso                   0.8.3
partd                   1.2.0
pickleshare             0.7.5
Pillow                  9.1.1
pip                     22.0.4
pluggy                  1.0.0
prometheus-client       0.14.1
prompt-toolkit          3.0.29
protobuf                3.20.1
psutil                  5.9.0
pure-eval               0.2.2
py                      1.11.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycocotools             2.0.4
pycparser               2.21
Pygments                2.12.0
PyJWT                   2.3.0
pyOpenSSL               22.0.0
pyparsing               3.0.8
PyQt5                   5.12.3
PyQt5_sip               4.19.18
PyQtChart               5.12
PyQtWebEngine           5.12.1
pyreadline              2.1
pyrsistent              0.18.1
PySocks                 1.7.1
pytest                  7.1.2
python-dateutil         2.8.2
pytz                    2022.1
pyu2f                   0.1.5
PyWavelets              1.3.0
pywin32                 304
pywinpty                2.0.5
PyYAML                  6.0
pyzmq                   22.3.0
qtconsole               5.3.0
QtPy                    2.1.0
requests                2.27.1
requests-oauthlib       1.3.1
rsa                     4.8
scikit-image            0.19.2
scikit-learn            1.0.2
scipy                   1.8.0
Send2Trash              1.8.0
setuptools              62.1.0
Shapely                 1.8.2
six                     1.16.0
sklearn                 0.0
soupsieve               2.3.2.post1
stack-data              0.2.0
tabulate                0.8.9
tensorboard             2.9.0
tensorboard-data-server 0.6.0
tensorboard-plugin-wit  1.8.1
tensorflow-addons       0.16.1
terminado               0.15.0
terminaltables          3.1.10
thop                    0.0.31.post2005241907
threadpoolctl           3.1.0
tifffile                2022.5.4
tinycss2                1.1.1
tomli                   2.0.1
toolz                   0.11.2
torch                   1.11.0+cu113
torchaudio              0.11.0+cu113
torchvision             0.12.0+cu113
tornado                 6.1
tqdm                    4.64.0
traitlets               5.1.1
typeguard               2.13.3
typing_extensions       4.2.0
unicodedata2            14.0.0
urllib3                 1.26.9
wcwidth                 0.2.5
webencodings            0.5.1
Werkzeug                2.1.2
wheel                   0.37.1
widgetsnbextension      3.6.0
win-inet-pton           1.1.0
win32-setctime          1.1.0
wrapt                   1.14.1
xmltodict               0.13.0
yarl                    1.7.2
yolox                   0.3.0
zipp                    3.8.0

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
是否依赖和版本有问题 可以重新安装下依赖pip install -r requirements.txt

**Comment by ademengke** [comment]
> 是否和版本有问题可以重新安装依赖下依赖pip install -r requirements.txt

重新安装依赖后 出现 Ignoring visualdl: markers 'python_version <= "3.7"' don't match your environment

之后尝试 import ppdet 出现相同的问题 :
FileNotFoundError: Could not find module 'e:\anaconda\envs\yolox\lib\site-packages\scipy\.libs\libbanded5x.UALCZY4KXIWFSNTUQY2S5KECOR3WRBFR.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with construct
or syntax.

**Comment by ademengke** [comment]
问题已解决。
通过： 
pip uninstall scipy 卸载当前的scipy -> 然后重新安装scipy:    pip install scipy==1.8.1
