### ISSUE TITLE
关于Doc文档数据处理部分的VOC数据集格式问题

### ISSUE THREAD

**Issue by caoweiying123** [PaddlePaddle/PaddleDetection#623]
![8QQY_}F1IS)B93I`A%R}FC](https://user-images.githubusercontent.com/60028206/81471578-a3096000-9224-11ea-9547-a15ae8ebb001.png)

![JJ13$ZXLUIE$X{)LFTPL`V3](https://user-images.githubusercontent.com/60028206/81471582-aef52200-9224-11ea-9cf6-9dd16a805345.png)

**Comment by still-wait** [comment]
@caoweiying123 感谢反馈，`JPEGImages/`文件夹下应该是`jpg`图像格式，我们会修复文档错误
