### ISSUE TITLE
请问数据集中包含无目标的图片样本时配置要如何设置

### ISSUE THREAD

**Issue by morrigank12** [PaddlePaddle/PaddleDetection#6236]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

记得以前看配置文件文档时看到过相关配置项，是否包括无目标的图片，还附有说明此类图片过多容易发生过拟合，但是今天想搜一下怎么也搜不到了。
现在做人形目标检测的其中一个摄像头画面中包括一片树林，训练好的模型经常将树叶摆动的瞬间检测为人形，请问想将这种完全无人形目标出现的图片作为数据集的一部分，配置文件要如何修改？

**Comment by lyuwenyu** [comment]
dataset加上allow_empty参数

**Comment by morrigank12** [comment]
谢谢
