### ISSUE TITLE
export_model.py导出有BUG

### ISSUE THREAD

**Issue by tututu11** [PaddlePaddle/PaddleDetection#6245]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

export_model.py导出有BUG，我使用coco数据类型训练，coco_detection.yml如下，我只训练了一个类。
`metric: COCO
num_classes: 1

TrainDataset:
  !COCODataSet
    image_dir: c:/train
    anno_path: c:/voc_train.json
    dataset_dir: c:/
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: c:/val
    anno_path: c:/voc_test.json
    dataset_dir: c:/

TestDataset:
  !ImageFolder
    anno_path: c:/voc_test.json # also support txt (like VOC's label_list.txt)
    dataset_dir: c:/ # if set, anno_path will be 'dataset_dir/anno_path'`
训练完以后使用infer.py 推理，完全正常无任何问题，类和bbox识别正确。但是使用export_model.py再转换到ncnn时出现问题，ncnn推理出现了无数bbox,类别全部是coco默认的80个类。
导出的infer_cfg.yml中的label_list:已经识别正确为1个类，但是使用ncnn推理时却出现了默认的80个类。应该是export_model.py导出出现了问题，但是不知道问题在哪里。配置文件只修改了coco_detection.yml和batch_size，其他并无改动。

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
导出的infer_cfg.yml中的label_list是1类吗？
注意看运行打印的信息里有没有warning说为什么使用默认COCO80类，一般是路径设置有误找不到才会使用默认COCO80类。TestDataset里anno_path如果是绝对路径，dataset_dir这一行就不用设置应该去掉。

**Comment by tututu11** [comment]
> 导出的infer_cfg.yml中的label_list是1类吗？ 注意看运行打印的信息里有没有warning说为什么使用默认COCO80类，一般是路径设置有误找不到才会使用默认COCO80类。TestDataset里anno_path如果是绝对路径，dataset_dir这一行就不用设置应该去掉。

导出的infer_cfg.yml中的label_list如下所示，配置已经正确导出类
![image](https://user-images.githubusercontent.com/91424151/174806552-ae8c5ab4-1513-4264-b162-a8735a49d277.png)

运行时没有warning提示使用默认类，dataset_dir去掉还是一样的错误。另外我使用configs\datasets\voc.yml作为训练数据，全部转换为voc类型数据，得出的结果和coo数据集时是一样的。infer.py推理正确，转换为ncnn推理却出错，出现默认的coco类别，bbox出现一大堆非常乱。
voc.yml如下，使用的是相对路径，另外map_type是什么
![image](https://user-images.githubusercontent.com/91424151/174806483-c8e8014f-b51f-4a0c-a7d4-3a3132818518.png)

**Comment by tututu11** [comment]
> 导出的infer_cfg.yml中的label_list是1类吗？ 注意看运行打印的信息里有没有warning说为什么使用默认COCO80类，一般是路径设置有误找不到才会使用默认COCO80类。TestDataset里anno_path如果是绝对路径，dataset_dir这一行就不用设置应该去掉。

issues #6244 应该和我是同样的问题，export_model.py导出有BUG

**Comment by tututu11** [comment]
![0results0570688](https://user-images.githubusercontent.com/91424151/174806139-6e982de0-6f7f-4fbf-a68d-468d72d20089.jpg)
转换为ncnn推理就是这个效果，coco与voc训练出来都一样。

**Comment by tututu11** [comment]
使用的是PP2.2.2 py3.9，  pp2.3无法使用，运行直接出错，只能使用2.2.2.
