### ISSUE TITLE
配置文件中指定使用GPU的id

### ISSUE THREAD

**Issue by xiaoxiangch** [PaddlePaddle/PaddleDetection#6246]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PaddleDetection的配置文件中关于GPU的使用，只有use_gpu 为true或者false。单GPU训练时默认使用的GPU的id为0，但是我想指定使用1号GPU，该如何在配置文件中显示，或者有其他的设置方法吗？

**Comment by ghostxsl** [comment]
可以直接设置环境变量：CUDA_VISIBLE_DEVICES=1
