### ISSUE TITLE
tinypose训练出模型效果明显差！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleDetection#6257]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

Hi，
请问下， https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/keypoint/tiny_pose 这里的tinypose 官方发布的128X96的模型效果挺好的，但是我尝试按照这里的指示训练出来，结果明显不如官方发布的，请问下是否开源的这部分可以复现您官方发布的模型？
1 数据集必须采用关键点检测模型与行人检测模型的训练集在COCO以外还扩充了[AI Challenger](https://arxiv.org/abs/1711.06475)数据集， 不能只使用coco，如果只使用coco效果肯定明显会比这里官方发布的要差，对吗？
2 python3 -m paddle.distributed.launch tools/train.py -c configs/keypoint/tiny_pose/tinypose_128x96.yml 采用yml配置的默认参数训练就行，影响最终模型检测结果的参数，基本不需要自己再去调了吧？如果需要，是哪几个必须调？
3 部署的时候./build/main --model_dir=output_inference/picodet_s_320_pedestrian --model_dir_keypoint=output_inference/tinypose_128x96 --video_file={your video file} --device=GPU
为了跟官方您发布的结果环境一致，我使用了官方发布的picodet_s_320_pedestrian 模型，然后加上我自己训练出来的tinypose128X96，结果生成的视频，发现效果明显不如部署这里采用您官方发布的tinypose_128x96 模型，所以
说明训练出来的tinypose模型结果肯定有问题。想请教下，哪里有问题，能指点下吗？
BR 

### 复现环境 Environment

![image](https://user-images.githubusercontent.com/8407513/175226768-bec65844-d920-4c56-a817-2f119dc58bc2.png)

### 是否愿意提交PR Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by 2050airobert** [comment]
anyone could help ?

**Comment by zhiboniu** [comment]
你好，
1）实际即使只使用coco数据训练的模型效果也差的并不多，肉眼应该不会有特别明显的区别。
2）是的，基本不需要自己调整了。学习率可以根据卡数等比例调整一下，当前参数是4卡的配置。如果是单卡学习率可以/4.
3）请问你训练自己的模型的时候还有其他地方有修改吗？包括数据方面

**Comment by 2050airobert** [comment]
那就不对啊，我训练使用的是coco的数据集，person keypoint 这个我很确定，只不过我下载到本地了。
1 参数大多数都保持yaml里面的不便，唯一的区别就是epcho我设置了100，原始配置是420 ，跟这个有关吗？
2 也就是说能否打印整个过程中的 acc map presion之类的指标，方便查看呢？ 有什么设置吗？
3 这里有个preweight选项，我必须设置吗，可以从头训练，不写这个吗？ 如果要写我该从哪里下载这个preweights
![image](https://user-images.githubusercontent.com/8407513/175317125-c09da310-0ef0-471b-ace8-329f8643f5db.png)
我尝试不写preweights，cmd 命令也就是python arg参数以及 config yaml全都去掉weigths相关，结果报错
![image](https://user-images.githubusercontent.com/8407513/175318915-3d261acc-770d-4ed8-9705-a058314f7e7a.png)
4 关于数据的详细问题在这里，顺便麻烦您回答下这里的所有问题吧，辛苦啦
https://github.com/PaddlePaddle/PaddleDetection/issues/6251

**Comment by zhiboniu** [comment]
1. epoch数量从420减少到100变化比较大，有训练不足的可能。同时如果总epoch改变的话，学习率调整的milestones也要相应调整。
2. 训练是命令行加上--eval，开启训练中评估功能。
3. 这里的报错是weights不是preweight，两者不同。preweight是预训练模型，weights是评估性能时使用，训练中可以保留字段无需关注。

**Comment by zhiboniu** [comment]
我们对比的tinypose相比只使用coco数据集，增加AI Challenger数据后性能提升其实只有1-2个点，这个变化在肉眼看来是难以区分的。

**Comment by 2050airobert** [comment]
1 除了学习率，我是双卡，需要除以2，跟batchsize 关系大吗？ 如果我改为512 X2 =1024，相应的需要调整哪个参数容易最优呢？
![image](https://user-images.githubusercontent.com/8407513/175452109-4e2739f8-0272-463f-b382-93f6a168e058.png)
2 preweights 预训练权重，当然跟weight 评估用的阶段性网络输出不同，只是preweights 我在yaml 文件里面没找到，是必须cmd --preweights形式给出来吗？  但不管怎样，您的意思已经明确了就是实际上不需要preweights只要 epcho足够大，结果就会不错，对吧？
3 map 结果还不错，但是检测 视频，采用video file接口，输出的结果关键点显示比较差，调整了显示threshhold没有很好的改善，这是什么情况，该如何改进呢？
![image](https://user-images.githubusercontent.com/8407513/175456563-addf1be0-0b21-4c0c-9747-dc155089a4d1.png)
可以顺便把 tinypose 128X96 yaml配置训练好的官方发布模型的map打印出来发在这里吗？ 就像我上图一样，或者有链接有吗？
4 Unbiased Data Processing ([UDP](https://arxiv.org/abs/1911.07524))。
Augmentation by Information Dropping ([AID](https://arxiv.org/abs/2008.07139v2))。
我如何选择打开还是关闭这两个选项，在训练的过程中？  哪里有这个配置吗？ 
是不是我只要注释掉  AugmentationbyInformantionDropping  就相当于不使用AID数据增强 训练了？ 
5 EvalDataset:  下面的 use_gt_bbox: True  难道还可以改为 false？      freeze_at: -1 这个是什么呢 @Sin(e^t*x).sum()

**Comment by 2050airobert** [comment]
测试视频如下，可以参考 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/keypoint/tiny_pose
# 预测一个视频
python3 deploy/python/det_keypoint_unite_infer.py --det_model_dir=output_inference/picodet_s_320_pedestrian --keypoint_model_dir=output_inference/tinypose_128x96 --video_file={your video file} --device=GPU

https://user-images.githubusercontent.com/8407513/175528284-1f28045a-aa47-4db9-9447-2f9f087fb00c.mp4
通过实验对比发现，   预测部署模型是从 config和model export过来的吧？  但是为啥我测了下，我手动从config model 转过来的A 和 你这里下载到的预测部署模型B 检测结果不同啊？ 
具体在视频种的某几帧表现特别明显：

方法A 
![image](https://user-images.githubusercontent.com/8407513/175528635-aabbfe6f-a777-46df-9fa9-38ec0c04c5cd.png)
 方法B 不会出现明显错误检测
麻烦帮忙复现，并查下是哪里出错了吗？
多谢

**Comment by 2050airobert** [comment]
此视频仅供paddle团队内部测试，请知悉哈
![image](https://user-images.githubusercontent.com/8407513/175528953-58ea32a8-f5d8-40b1-b4f3-2c44f9c3de3b.png)
方法B就是直接下载上图中的 预测部署模型
方法A就是 config和model 通过export.py 转出来的 部署模型

**Comment by zhiboniu** [comment]
你好，我这里使用方法A、B都测试了一下，没有发现明显区别。以下是我的操作命令，你可以参考对比一下
<img width="713" alt="image" src="https://user-images.githubusercontent.com/31800336/175535860-42dea232-1a95-480f-82d4-e429b1d1adaf.png">
另外，tinypose128的模型加aic数据后确实提升不少，之前说的提升不到2个点的应该是256模型。以下是我们当时的对比记录。所以训练tinypose128还是有必要加入aic数据的
<img width="426" alt="d5bbd4be0a9728f2956e99058133cff0" src="https://user-images.githubusercontent.com/31800336/175536103-28656605-9a9f-4fb4-bc1c-78fe2a3872d0.png">
