### ISSUE TITLE
infer.py: error: the following arguments are required: --model_dir

### ISSUE THREAD

**Issue by ybonzou** [PaddlePaddle/PaddleDetection#6258]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

How do I infer a video file in "PPYoloE"?
An error occurs.
Sorry for being so rudimentary.

![1](https://user-images.githubusercontent.com/69044596/175228526-6a35e115-4c2c-4759-89c2-fea35c8e0f61.png)
![2](https://user-images.githubusercontent.com/69044596/175228535-5a8cc26e-1925-48ae-8acf-054f96468960.png)

**Comment by ybonzou** [comment]
Model created and resolved！

**Comment by zhiboniu** [comment]
congratulation!
welcome to PaddleDetection.
