### ISSUE TITLE
MacOS下CreatePaddlePredictor报错：Check failed: kernels.size() > 0 (0 vs. 0)  Error: This model is not supported, because kernel for 'conv2d' is not supported by Paddle-Lite.

### ISSUE THREAD

**Issue by panmin** [PaddlePaddle/PaddleDetection#6259]
### 
开发环境：MacOS
Paddle-Lite版本：v2.11
官方模型下载地址：https://paddledet.bj.bcebos.com/deploy/paddlelite/picodet_xs_320_coco_lcnet.tar
代码如下：
```
    string model_path = "models/picodet_xs_320_coco_lcnet.nb";
    MobileConfig config;
    config.set_model_from_file(model_path);
    config.set_threads(4);
    config.set_power_mode(PowerMode::LITE_POWER_HIGH);
    shared_ptr<PaddlePredictor> predictor = CreatePaddlePredictor(config);
```

报错信息：
`F0623 15:08:26.591073 277147072 program.cc:346] Check failed: kernels.size() > 0 (0 vs. 0) 
Error: This model is not supported, because kernel for 'conv2d' is not supported by Paddle-Lite.`

**Comment by mjp9527** [comment]
MacOS有两款芯片，x86和M1(ARM)，使用的模型和库均不一样，你检查一下使用的模型和库是否匹配你的笔记本

**Comment by panmin** [comment]
@mjp9527 用的x86版本的MacOS，Paddle Lite 预编译库下载[https://paddle-lite.readthedocs.io/zh/latest/quick_start/release_lib.html ](url)
<img width="301" alt="image" src="https://user-images.githubusercontent.com/2524761/175249450-66e0799a-e9e3-4935-b7a7-7b60c5242ceb.png">

**Comment by mjp9527** [comment]
> @mjp9527 用的x86版本的MacOS，Paddle Lite 预编译库下载[https://paddle-lite.readthedocs.io/zh/latest/quick_start/release_lib.html ](url) <img alt="image" width="301" src="https://user-images.githubusercontent.com/2524761/175249450-66e0799a-e9e3-4935-b7a7-7b60c5242ceb.png">

opt建议也使用v2.11，然后转换时--valid_targets=x86

**Comment by mjp9527** [comment]
> 开发环境：MacOS Paddle-Lite版本：v2.11 官方模型下载地址：https://paddledet.bj.bcebos.com/deploy/paddlelite/picodet_xs_320_coco_lcnet.tar 代码如下：
> 
> ```
>     string model_path = "models/picodet_xs_320_coco_lcnet.nb";
>     MobileConfig config;
>     config.set_model_from_file(model_path);
>     config.set_threads(4);
>     config.set_power_mode(PowerMode::LITE_POWER_HIGH);
>     shared_ptr<PaddlePredictor> predictor = CreatePaddlePredictor(config);
> ```
> 
> 报错信息： `F0623 15:08:26.591073 277147072 program.cc:346] Check failed: kernels.size() > 0 (0 vs. 0) Error: This model is not supported, because kernel for 'conv2d' is not supported by Paddle-Lite.`

你这个nb模型是个arm的模型，x86用不了，需要使用opt工具转换paddle的模型
