### ISSUE TITLE
c++ 预测问题，图片和视频没有问题，摄像头有问题

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleDetection#6260]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

main --model_dir=models --image_file=images/4.jpg --camera_id=0
Please set use_dynamic_shape.
FLAGS_camera_id==0
fps: 0, frame_count: -1
outputcreate video writer failed!

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
这个可能是cv::VideoWriter保存视频的格式不支持，可以换成其他格式试试。比如avi。

**Comment by dengmingD** [comment]
> 

不是这个问题，不过修改一下代码不影响使用，保存不了视频文件（画框的），但可以存在图片，一样能达到效果，谢谢您的回答。
