### ISSUE TITLE
picodet 如何修改配置文件，满足输入大小为192或者128？

### ISSUE THREAD

**Issue by fengyanWang** [PaddlePaddle/PaddleDetection#6264]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/36984088/175448672-dbb1037e-18d0-4122-9efd-7afb1ab77eaa.png)

你好，请问如何修改picodet模型配置文件中的参数实现模型输入为192或者128，因为没看到picodet模型配置文件参数说明，所以没法修改，目前直接修改数据部分是有feature尺寸问题报错的。

**Comment by zoooo0820** [comment]
@fengyanWang 
请参考这个[320尺度的reader文件](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/picodet/_base_/picodet_320_reader.yml#L2) 。新建一份picodet-192或128的reader配置。然后在[模型配置文件](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/picodet/picodet_l_320_coco_lcnet.yml#L6)中引用修改后的reader文件即可。

**Comment by DavidQiuChao** [comment]
> ### 问题确认 Search before asking
> * [x]  我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> 
> ### 请提出你的问题 Please ask your question
> ![image](https://user-images.githubusercontent.com/36984088/175448672-dbb1037e-18d0-4122-9efd-7afb1ab77eaa.png)
> 
> 你好，请问如何修改picodet模型配置文件中的参数实现模型输入为192或者128，因为没看到picodet模型配置文件参数说明，所以没法修改，目前直接修改数据部分是有feature尺寸问题报错的。

浅薄个人见解：修改yaml配置文件中的验证尺度大小（自己需要添加）和训练randombatchsize 大小。网络本身不需要改，理论上接受遵循特定下采样倍数的输入。

**Comment by fengyanWang** [comment]
> > ### 问题确认 Search before asking
> > 
> > * [x]   我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> > 
> > ### 请提出你的问题 Please ask your question
> > ![image](https://user-images.githubusercontent.com/36984088/175448672-dbb1037e-18d0-4122-9efd-7afb1ab77eaa.png)
> > 你好，请问如何修改picodet模型配置文件中的参数实现模型输入为192或者128，因为没看到picodet模型配置文件参数说明，所以没法修改，目前直接修改数据部分是有feature尺寸问题报错的。
> 
> 浅薄个人见解：修改yaml配置文件中的验证尺度大小（自己需要添加）和训练randombatchsize 大小。网络本身不需要改，理论上接受遵循特定下采样倍数的输入。

已经解决，谢谢大家！

**Comment by lingdu-xu** [comment]
新手看蒙了啊，题主方便解析一下reader.yaml文件么？拜托了！感谢
