### ISSUE TITLE
想问一下什么情况下is_bbox_normalized为False?

### ISSUE THREAD

**Issue by ljx111** [PaddlePaddle/PaddleDetection#627]
{'bbox': (array([[0.        , 0.9932496 , 0.44695184, 0.33945343, 0.4629064 ,
        0.35912254]], dtype=float32), [[1]]), 'im_id': (array([[0]], dtype=int64), [])}
[{'image_id': 0, 'category_id': 1, 'bbox': [0.44695183634757996, 0.33945342898368835, 1.0159545540809631, 1.0196691155433655], 'score': 0.9932495951652527}]
xmin,ymin,xmax,ymax都是正常范围的值，为什么is_bbox_normalized是False?导致后面可视化没输出矩形框

**Comment by still-wait** [comment]
@ljx111 请问使用哪个模型？使用ssd类算法，`is_bbox_normalized`都要设置为`True`，因为使用`SSDOutputDecoder`预测的结果都是输出归一化后的结果，请参照[code](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/utils/coco_eval.py#L247)对归一化后的bbox做还原操作。

**Comment by ljx111** [comment]
> @ljx111 请问使用哪个模型？使用ssd类算法，`is_bbox_normalized`都要设置为`True`，因为使用`SSDOutputDecoder`预测的结果都是输出归一化后的结果，请参照[code](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/utils/coco_eval.py#L247)对归一化后的bbox做还原操作。

我用的是yolov3，配置里面的is_normalized默认是false，但改成true还是报错。
2020-05-10 12:18:23,095-INFO: places would be ommited when DataLoader is not iterable
W0510 12:18:23.883211   789 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0510 12:18:23.887392   789 device_context.cc:245] device: 0, cuDNN Version: 7.3.
2020-05-10 12:18:25,392-INFO: Loading parameters from output/yolov3_r50vd_dcn_polyps/5...
I0510 12:18:27.305074   789 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I0510 12:18:27.317579   789 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0510 12:18:27.327291   789 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0510 12:18:27.334287   789 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
2020-05-10 12:18:28,189-INFO: Test iter 0
2020-05-10 12:18:29,296-INFO: Test finish iter 3
2020-05-10 12:18:29,296-INFO: Total number of images: 80, inference time: 39.96184653890966 fps.
loading annotations into memory...
Traceback (most recent call last):
  File "tools/eval.py", line 190, in <module>
    main()
  File "tools/eval.py", line 173, in main
    dataset=dataset)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/eval_utils.py", line 209, in eval_results
    is_bbox_normalized=is_bbox_normalized)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/coco_eval.py", line 74, in bbox_eval
    coco_gt = COCO(anno_file)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by qingqing01** [comment]
@ljx111  YOLOv3模型训练时BBox是非normalized，内部计算也是采用非normalized的bbox，不能设置True哈。

**Comment by ljx111** [comment]
> @ljx111 YOLOv3模型训练时BBox是非normalized，内部计算也是采用非normalized的bbox，不能设置True哈。

好的，明白了，谢谢！

**Comment by ljx111** [comment]
> @ljx111 YOLOv3模型训练时BBox是非normalized，内部计算也是采用非normalized的bbox，不能设置True哈。

你好，是不是BBox的值不必归一化就送到神经网络训练，但程序还是报错，我的数据读取器是自己重写load_roidb_and_cname2cid（）函数。还是说我要根据自己数据标签的格式写一个类似于coco_eval.py的文件？

**Comment by qingqing01** [comment]
@ljx111 您的数据格式不是COCO格式吗？ 如果想用coco mAP评估，还是需要COCO数据格式。 如果不是一定要用coco mAP，那也可以自己重写`load_roidb_and_cname2cid（）函数`，用VOC的mAP评估方式，yml里设置`metric:VOC  map_type: 11point`也可以。

**Comment by learning-boy** [comment]
请问一下，mask_RCNN可以采用mAP评估嘛，默认是coco评估，请问怎么修改

**Comment by ljx111** [comment]
> @ljx111 您的数据格式不是COCO格式吗？ 如果想用coco mAP评估，还是需要COCO数据格式。 如果不是一定要用coco mAP，那也可以自己重写`load_roidb_and_cname2cid（）函数`，用VOC的mAP评估方式，yml里设置`metric:VOC map_type: 11point`也可以。

好的，感谢您的热心回答！

**Comment by ljx111** [comment]
> 请问一下，mask_RCNN可以采用mAP评估嘛，默认是coco评估，请问怎么修改

这个我也不清楚，刚用这个框架

**Comment by ljx111** [comment]
> 请问一下，mask_RCNN可以采用mAP评估嘛，默认是coco评估，请问怎么修改

metric字段是改评估方式的

**Comment by qingqing01** [comment]
@learning-boy  VOC的评估方式，没有提供分割的评估。 你是有需求非COCO的分割评测需求吗？

**Comment by learning-boy** [comment]
我使用的是mask_RCNN的模型，训练完成后，默认使用coco的mAP评估方式，mAP相对使用Yolov3要低，coco采用的是10个IoU取平均的方式，最终mAP低一点，但当IoU等于0.5的时候，就是coco输出格式的第二行，打印的map很高但没有记录，我想把这个高map作为最终的mAP，并记录下来，但是不知道怎么修改评估脚本



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: qingqing01 <notifications@github.com&gt;
发送时间: 2020年5月11日 19:11
收件人: PaddlePaddle/PaddleDetection <PaddleDetection@noreply.github.com&gt;
抄送: learning-boy <1342346303@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[PaddlePaddle/PaddleDetection] 想问一下什么情况下is_bbox_normalized为False? (#627)





 
@learning-boy  VOC的评估方式，没有提供分割的评估。 你是有需求非COCO的分割评测需求吗？

**Comment by qingqing01** [comment]
@learning-boy 看你已经建了新的issue，先关闭了此issue

**Comment by learning-boy** [comment]
好的，谢谢您



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: qingqing01 <notifications@github.com&gt;
发送时间: 2020年5月15日 10:58
收件人: PaddlePaddle/PaddleDetection <PaddleDetection@noreply.github.com&gt;
抄送: learning-boy <1342346303@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[PaddlePaddle/PaddleDetection] 想问一下什么情况下is_bbox_normalized为False? (#627)





 
@learning-boy 看你已经建了新的issue，先关闭了此issue
