### ISSUE TITLE
💡PP-Human v2全面升级！五大行为识别、视频流功能上新！

### ISSUE THREAD

**Issue by YixinKristy** [PaddlePaddle/PaddleDetection#6282]
### Discussed in https://github.com/PaddlePaddle/PaddleDetection/discussions/6281

<div type='discussions-op-text'>

<sup>Originally posted by **YixinKristy** June 28, 2022</sup>
# 🔔[PP-Human v2](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/pipeline)强势来袭！
- 五大异常行为一键识别
- 10余种预训练模型一站下载
- 10分钟快速新增识别类型
- 多路视频流部署高性能支持
- 全流程保姆级教程，从技术选型、数据准备到模型部署全覆盖

<div align="center">
<img src="https://user-images.githubusercontent.com/48054808/179469496-c757b432-41d6-4ef7-b932-8f1a08f12219.gif"  width = "800" />  
</div>

教程文档：https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/pipeline

欢迎大家扫码进群，方便相互交流沟通

<img width="300" alt="ppyoloe_map_fps" src="https://user-images.githubusercontent.com/22989727/196743046-d2527cd1-4c46-4a6c-8779-1921a28aca48.jpg">

**Comment by liuyang77886** [comment]
二维码过期了
