### ISSUE TITLE
aistudio上使用PaddleDetection训练脚本报错 No stack trace in paddle, may be caused by external reasons.

### ISSUE THREAD

**Issue by liyongchao911** [PaddlePaddle/PaddleDetection#6283]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

在aistudio上fork了别人的项目，使用GPU(Tesla V100 32G 环境）跑训练脚本报错
1. 已安装paddlepaddle, 脚本如下：
!python -m pip install paddlepaddle-gpu==2.3.0 -i https://mirror.baidu.com/pypi/simple

2. clone paddleDetection套件后安装依赖：
%cd /home/aistudio/PaddleDetection
!pip install -r requirements.txt

3. 跑训练脚本报错
!python tools/train.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml --eval

4. 报错信息如下：
opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0628 10:25:43.193198  9523 dynamic_loader.cc:305] The third-party dynamic library (libcuda.so) that Paddle depends on is not configured correctly. (error code is /usr/lib/x86_64-linux-gnu/libcuda.so: file too short)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1656383143 (unix time) try "date -d @1656383143" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 9523 (TID 0x7f46f4f8c700) from PID 0 ***]

### 复现环境 Environment

 - Paddle ： paddlepaddle-gpu==2.3.0
 - Python： 3.7

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by yghstill** [comment]
@liyongchao911 看着是Paddle版本和cuda版本不匹配，检查cuda版本后重新安装下Paddle试下呢：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

**Comment by keithye119** [comment]
aistudio 默认cuda版本是10.1, paddle 2.3.0 默认是cuda 10.2, 要指定安装10.1版本
