### ISSUE TITLE
ValueError: (InvalidArgument) Input object type error or incompatible array data type. tensor.set() supports array with bool, float16, float32, float64, int8, int16, int32, int64, uint8 or uint16, please check your input or input array data type. (at /paddle/paddle/fluid/pybind/tensor_py.h:529)

### ISSUE THREAD

**Issue by thongvhoang** [PaddlePaddle/PaddleDetection#6302]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

I train the ppyolo_r50vd_dcn_1x_coco model using Google Colab environment. I use the python command:
`!python tools/train.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml --eval	`
And the error generates after that
```
/usr/local/lib/python3.7/dist-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
/usr/local/lib/python3.7/dist-packages/scipy/fft/__init__.py:97: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/usr/local/lib/python3.7/dist-packages/scipy/sparse/sputils.py:17: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
/usr/local/lib/python3.7/dist-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
W0629 05:34:12.921054 460461 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 11.2, Runtime API Version: 10.2
W0629 05:34:12.924480 460461 gpu_context.cc:306] device: 0, cuDNN Version: 7.6.
[06/29 05:34:15] ppdet.utils.checkpoint INFO: Finish loading model weights: /content/drive/MyDrive/UIT/Four_Year/Term_2/DS505.M21/Code/PaddleDetection/pretrained_model/ResNet50_vd_ssld_pretrained.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 251, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 237, in _thread_loop
    tmp.set(slot, core.CPUPlace())
ValueError: (InvalidArgument) Input object type error or incompatible array data type. tensor.set() supports array with bool, float16, float32, float64, int8, int16, int32, int64, uint8 or uint16, please check your input or input array data type. (at /paddle/paddle/fluid/pybind/tensor_py.h:529)


    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/content/drive/MyDrive/UIT/Four_Year/Term_2/DS505.M21/Code/PaddleDetection/ppdet/engine/trainer.py", line 428, in train
    for step_id, data in enumerate(self.loader):
  File "/content/drive/MyDrive/UIT/Four_Year/Term_2/DS505.M21/Code/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 270, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
```
My annotation COCO file:
[instances_train2017.zip](https://github.com/PaddlePaddle/PaddleDetection/files/9007570/instances_train2017.zip)
I checked and see my annotation custom dataset like COCO format.
My configure file includes optimizer_1x.yml, ppyolo_r50vd_dcn_1x_coco.yml, ppyolo_reader.yml, coco_detection.yml.
[configure_file.zip](https://github.com/PaddlePaddle/PaddleDetection/files/9007603/configure_file.zip)

Thank you for your time to support me.

### 复现环境 Environment

- Paddlepaddle-gpu==2.3.0
- PaddleDetection: Release/2.4
- Python 3.7.13
- CUDA Version: 11.2
- cuDNN Version: 7.6.

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
The error message shows that wrong input leads to this problem, maybe you should check the data loading process.

**Comment by thongvhoang** [comment]
> The error message shows that wrong input leads to this problem, maybe you should check the data loading process.


I used the dataset format COCO for training in the mmdetection framework and it worked fine.

**Comment by thongvhoang** [comment]
```
metric: COCO
num_classes: 1

TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: /content/drive/MyDrive/UIT/Four_Year/Term_2/DS505.M21/Dataset/detection_data/data/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: /content/drive/MyDrive/UIT/Four_Year/Term_2/DS505.M21/Dataset/detection_data/data/coco

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
    dataset_dir: /content/drive/MyDrive/UIT/Four_Year/Term_2/DS505.M21/Dataset/detection_data/data/coco # if set, anno_path will be 'dataset_dir/anno_path'
```
I don't understand the data_fields and I see it does not match COCO format. Does anybody explain it to me, pls? Thank you.

**Comment by wangxinxin08** [comment]
It's ok to keep default data_fields since it is defined in `ppdet/data/source/coco.py`. There is a lot of difference between PaddleDetection and MMDetection. I suggest you debug the data loading process by printing the value or type of sample.

**Comment by thongvhoang** [comment]
I print value of sample and type of sample. And I see that
`{'im_file': '/content/drive/MyDrive/UIT/Four_Year/Term_2/DS505.M21/Dataset/detection_data/data/coco/train2017/night_60m_987.jpg', 'im_id': array(['night_60m_987'], dtype='<U13'), 'h': 720.0, 'w': 1280.0, 'is_crowd': array([[0]], dtype=int32), 'gt_class': array([[0]], dtype=int32), 'gt_bbox': array([[731., 295., 767., 324.]], dtype=float32)} <class 'dict'>`

I debugged the file in `ppdet/data/source/coco.py`. I see 'im_id" with dtype='<U13', however; Is 'im_id' is a number or a float dtype in default setting PaddleDetection ?

**Comment by wangxinxin08** [comment]
In PaddleDetection, 'im_id' should be a number with int or float dtype.

**Comment by thongvhoang** [comment]
> In PaddleDetection, 'im_id' should be a number with int or float dtype.

If I want to use "im_id" to be a string, it can be converted?

**Comment by wangxinxin08** [comment]
> > In PaddleDetection, 'im_id' should be a number with int or float dtype.
> 
> If I want to use "im_id" to be a string, it can be converted?

Maybe you should first map the string im_id to a int number and the mapping dict. In `coco.py`, the im_id fields of sample should be number.

**Comment by thongvhoang** [comment]
> > > In PaddleDetection, 'im_id' should be a number with int or float dtype.
> > 
> > 
> > If I want to use "im_id" to be a string, it can be converted?
> 
> Maybe you should first map the string im_id to a int number and the mapping dict. In `coco.py`, the im_id fields of sample should be number.

I solved that problem with the solution, I convert the COCO format to Pascal VOC format and it works fine. 
The solution maps the string im_id to an int number which is complicated so I chose the solution above. However, anybody can approach the mapping solution, I think it is one of the possible solutions to solve the problem.
