### ISSUE TITLE
infer.py: error: unrecognized arguments: -c

### ISSUE THREAD

**Issue by Victoria-1** [PaddlePaddle/PaddleDetection#6317]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用2.3版本，突然无法进行推理，问题出现在用ppyolo进行训练后，之前用hrnet，hrnet等训练的模型均无法正常推理。只能导出以后进行推理，
![image](https://user-images.githubusercontent.com/35481439/176599713-0fa969ef-23e5-442a-b583-ca3dceca05ee.png)
提示中的usage里面的参数好像都不是tools/infer.py中需要的参数，所以感觉并没有真正调用tools/infer.py，是调用了其他的infer.py? 还有一点就是，调用怎么感觉好像是以客户端的方式在调用？不太明白，请问有什么思路或建议吗？

**Comment by lyuwenyu** [comment]
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/17582080/176654269-fdb4a53d-105c-443e-90c8-c5a4ab23c863.png">
看着没啥问题啊  你直接终端`python tools/eval.py -c xx`先试一下有没有问题

**Comment by Victoria-1** [comment]
> 
@lyuwenyu 
![image](https://user-images.githubusercontent.com/35481439/176808728-56eeb1ba-c07f-4ddb-863b-7fa8c94560c4.png)
还是一样的，你看我下面的那个提示，和你的是不一样的usage里面的那些是不一样的

**Comment by Victoria-1** [comment]
@lyuwenyu 你好，我又看了下，好像是因为之前训练ppyolo的时候启用了分布式训练的方式，所以导致不能识别tools/infer.py -c
![image](https://user-images.githubusercontent.com/35481439/177450118-571f1d8f-53b3-406c-880e-a37d836a0a6a.png)
请问这个要怎么处理？有什么建议吗？谢谢~

**Comment by jhonboHou** [comment]
同样的问题，报错
infer.py: error: unrecognized arguments: weights=output/best_model.pdparams
