### ISSUE TITLE
ppyoloe cpu 推理速度极慢

### ISSUE THREAD

**Issue by WooXinyi** [PaddlePaddle/PaddleDetection#6322]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

ppyoloe去除nms，开启benchmark，使用gpu推理时间约5ms，但是使用cpu推理时间约400ms，请问这是什么原因？

**Comment by wangxinxin08** [comment]
设置mkldnn，cpu_threads=4可以快点，另外，cpu的话可以试下picodet

**Comment by WooXinyi** [comment]
> 设置mkldnn，cpu_threads=4可以快点，另外，cpu的话可以试下picodet

设置mkldnn，cpu_threads=4后推理时间约350ms。能解释下为什么cpu推理速度这么慢吗？是不是有些算子只针对gpu做了优化哦

**Comment by wangxinxin08** [comment]
@WooXinyi 你可以看下用的算子都是普通的算子，在cpu上的快的网络一般是针对cpu做了优化的，比如depth wise卷积

**Comment by WooXinyi** [comment]
> @WooXinyi 你可以看下用的算子都是普通的算子，在cpu上的快的网络一般是针对cpu做了优化的，比如depth wise卷积

明白了，谢谢
