### ISSUE TITLE
config感叹号注册的类，怎么通过命令行指定

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/PaddleDetection#6330]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![25636533cf83abf9cb3a09fa1e1eafe](https://user-images.githubusercontent.com/31937673/176889361-d97a2399-54fd-41b1-aafb-b079a0b75da5.png)
我这么写会报错AttributeError: 'dict' object has no attribute 'check_or_download_dataset'

**Comment by nemonameless** [comment]
感叹号表示序列化模块，建议在配置文件里改写，没有必要命令行。TrainDataset是类，COCODataSet也是类，COCODataSet定义的时候有serializable。
