### ISSUE TITLE
训练PPYOLOE报错　OSError: (External) CUBLAS error(7).

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/PaddleDetection#6334]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

```shell
OSError: (External) CUBLAS error(7). 
  [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:55)
  [operator < matmul_v2 > error]
```
训练ppyoloe报错，ppyolov2能正常训练。

### 复现环境 Environment

PaddlePaddle paddlepaddle-gpu.post112
CUDA 11.2
cudnn 8.1、８.２、8.4都分别试过，均报同样的错,下载的均是for 11.X的.
cudnn-11.2-linux-x64-v8.1.1.33.tgz*
cudnn-11.3-linux-x64-v8.2.1.32.tgz
cudnn-linux-x86_64-8.4.0.27_cuda11.6-archive.tar.xz
PaddleDetection release/2.4
3090 单卡训练
能确保CUDA和ｃｕｄｎｎ能够匹配，安装没有问题。

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
https://github.com/search?q=org%3APaddlePaddle+An+unsupported+value+or+parameter+was+passed+to+the+function&type=issues
请先确保paddle版本安装正确，训其他模型比如yolov3试试有没有同样或类似问题

**Comment by blxie** [comment]
我也遇到了同样的问题，请问解决了吗？

**Comment by GuitarYourself** [comment]
同样的问题，哎，版本都是按照官网安装的，但是全都是cublas的报错

**Comment by blxie** [comment]
> 同样的问题，哎，版本都是按照官网安装的，但是全都是cublas的报错

用Docker一步到位，没有遇到任何问题，你可以试试
