### ISSUE TITLE
使用新版ppyolo V2 一直卡在验证集 卡1小时多也不动，也不报错

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/PaddleDetection#6337]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

问题和#3411 #3246相同,但是问题未解决.
加了--eval参数,当开始验证的时候,卡在ppdet.engine INFO: Eval iter: 0 还是卡着不动.

### 复现环境 Environment

PaddlePaddle 2.3.0
PaddleDetection 2.4
CUDA 11.2
cudnn 8.1
Python 3.7

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by ghostxsl** [comment]
这个是因为模型在训练初期没有很好的收敛，导致nms非常漫长，宏观上看起来就像是卡住了一样，建议你加载coco上训练好的模型finetuning
