### ISSUE TITLE
单卡训练ppyolo，提示没有use_gpu属性

### ISSUE THREAD

**Issue by Victoria-1** [PaddlePaddle/PaddleDetection#6345]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

已在训练前export CUDA_VISIBLE_DEVICES=0，但依然提示如下：
![image](https://user-images.githubusercontent.com/35481439/177076396-6baef459-98b7-4e43-9e03-5777fe5e5feb.png)
在tools/train.py中直接设置cfg.use_gpu=True以后，又会提示
![image](https://user-images.githubusercontent.com/35481439/177076809-3b6337a6-a0ab-4c99-bfb2-5584c6baca64.png)

但我试了下用hrnet训练模型是可以的，所以gpu和环境的配置应该是没问题的，请问这是什么原因呢，这是只能用多卡的方式跑吗？

**Comment by ChenjieXu** [comment]
你使用的config错了，用PaddleDetection/configs/ppyolo/ppyolo_mbv3_small_coco.yml这个，你那个是_BASE_下面的，是基础配置。

**Comment by Victoria-1** [comment]
@ChenjieXu 哦哦，看错了[emoj]，感谢~
