### ISSUE TITLE
PP-PicoDet使用静态图做预测bound box出现inf

### ISSUE THREAD

**Issue by phoenixsfly** [PaddlePaddle/PaddleDetection#6352]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

使用的是PicoDet-S 416x416 with后端处理的预训练模型：[w/后端处理](https://paddledet.bj.bcebos.com/deploy/Inference/picodet_s_416_coco_lcnet.tar)
加载该模型并进行推理时，发现输出的bound box存在inf
```python
import paddle
import numpy as np
from PIL import Image
import paddle.vision.transforms as transforms

MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
STD = np.array([0.229, 0.224, 0.225], dtype=np.float32)
trans=transforms.Compose([transforms.ToTensor(),transforms.Resize(size=[416,416]),transforms.Normalize(mean=MEAN,std=STD)])

# 输入图像
img=Image.open("./demo/hrnet_demo.jpg")
scale = np.array([416. / img.size[1], 416. / img.size[0]],dtype=np.float32)
tensor_img=trans(img).unsqueeze(0).numpy()

paddle.enable_static()

exe = paddle.static.Executor(paddle.CPUPlace())
#加载预训练模型
path_prefix = "./output_inference/picodet_s_416_pretrain/model"
[inference_program, feed_target_names,
 fetch_targets] = (paddle.static.load_inference_model(path_prefix, exe))

results = exe.run(inference_program,
                  feed={
                      feed_target_names[0]: tensor_img,
                      feed_target_names[1]: scale
                  },
                  fetch_list=fetch_targets,
                  return_numpy=False)

det=np.array(results[0])
num=np.array(results[1])
print(det)
```
得到的输出：
```python
array([[0.00000000e+00, 9.67206538e-01, 1.23129105e+02,            inf,
        2.58757172e+02,            inf],
       [0.00000000e+00, 6.45730123e-02, 5.10659714e+01,            inf,
        8.72315979e+01,            inf],
       [2.00000000e+00, 5.80499768e-02, 5.09358521e+01,            inf,
        8.76679916e+01,            inf],
       [2.00000000e+00, 4.60039414e-02, 1.14699318e+02,            inf,
        3.58021606e+02,            inf],
```
类别和score应该是没问题的，但是box有问题，这是为什么呢？

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by yghstill** [comment]
@phoenixsfly 你预处理有问题吧，没有transpose？参考现有demo测试吧：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/third_engine/demo_openvino/python/openvino_infer.py#L22

**Comment by phoenixsfly** [comment]
> @phoenixsfly 你预处理有问题吧，没有transpose？参考现有demo测试吧：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/third_engine/demo_openvino/python/openvino_infer.py#L22

找到问题了，问题在于scale_factor的shape要求是[1,2]，而不能是[2,]
将
`scale = np.array([416. / img.size[1], 416. / img.size[0]],dtype=np.float32)`
改为
`scale = np.array([[416. / img.size[1], 416. / img.size[0]]],dtype=np.float32)`
即可
