### ISSUE TITLE
OSError: (External) CUDA error(3), initialization error.

### ISSUE THREAD

**Issue by Jeremy-lf** [PaddlePaddle/PaddleDetection#6357]
![image](https://user-images.githubusercontent.com/45171399/177153607-a6abc3ed-903c-4df8-94aa-17e23465ed26.png)
[Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:66)

如流：lvfeng02

**Comment by nemonameless** [comment]
安装包和环境不对应，请自查。
