### ISSUE TITLE
行人检测和车辆检测预训练模型  page not found

### ISSUE THREAD

**Issue by jhl13** [PaddlePaddle/PaddleDetection#637]
Hi, 行人检测和车辆检测预训练模型 page not found.
Will you release a new link?
Best wishes!

**Comment by still-wait** [comment]
@jhl13 请问哪个链接失效了？

**Comment by qingqing01** [comment]
@jhl13 感谢反馈，我们修改下。 可以参考： https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.2/contrib

**Comment by qingqing01** [comment]
Fixed https://github.com/PaddlePaddle/PaddleDetection/pull/649
