### ISSUE TITLE
HightHRNET 训练时需要目标的bounding box 吗？

### ISSUE THREAD

**Issue by Wangj688** [PaddlePaddle/PaddleDetection#6374]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，请问自己的数据集必须要有bounding box,才能训练higherhrnet，我的数据集只有关键点的坐标，没有物体的边界框，好像训练不了

**Comment by zhiboniu** [comment]
不需要，higherhrnet是bottomup类型的模型，该类模型不需要图像中人的bbox，需要keypoint标注（按人区分），如果有没有标注的人需要有mask区域覆盖。
