### ISSUE TITLE
自己构建的模型，没有预训练模型，如何设置初始化策略？

### ISSUE THREAD

**Issue by wjplove8** [PaddlePaddle/PaddleDetection#6375]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如题

**Comment by yghstill** [comment]
@wjplove8 不用预训练模型的话，可以增加训练的轮数即可，其他的可以不变
