### ISSUE TITLE
服务端预测部署相关

### ISSUE THREAD

**Issue by snoopy1316** [PaddlePaddle/PaddleDetection#6376]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

参考文档：https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/serving
环境信息：Windows10
paddle-serving-client         0.9
paddle-serving-server         0.9
paddle-serving-server-gpu     0.9
paddledet                     2.4.0
paddlepaddle-gpu              2.2

在开启paddle serving服务时，终端显示FileNotFoundError: [Errno 2] No such file or directory: 'workdir_9393/general_infer_0/general_model.prototxt'，生成的workdir9393文件夹中没有文件，为什么？或者官方提供该文件夹内容，谢谢

**Comment by ghostxsl** [comment]
你运行的命令是什么？是按照文档跑的吗？

**Comment by snoopy1316** [comment]
> 你运行的命令是什么？是按照文档跑的吗？
按照文档，运行命令：python -m paddle_serving_server.serve --model serving_server --port 9393

**Comment by ghostxsl** [comment]
你在导出serving model的时候会生成serving_client目录，你可以按照需求把你生成的路径写到下面这个位置：
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/serving/test_client.py#L29
