### ISSUE TITLE
ppyoloe训练报错ValueError: Target *** is out of upper/lower bound.

### ISSUE THREAD

**Issue by Wanghe1997** [PaddlePaddle/PaddleDetection#6380]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

ppyoloe训练报错ValueError: Target *** is out of upper bound.

训练配置：
**ppyoloe_crn_l_300e_coco.yml**
_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/optimizer_300e.yml',
  './_base_/ppyoloe_crn.yml',
  './_base_/ppyoloe_reader.yml',
]

log_iter: 100
snapshot_epoch: 10
weights: output/ppyoloe_crn_l_300e_coco/model_final

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_l_pretrained.pdparams
depth_mult: 1.0
width_mult: 1.0

**coco_detection.yml**
metric: COCO
num_classes: 80

TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: dataset/coco

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
    dataset_dir: dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'

**optimizer_300e.yml**
epoch: 300

LearningRate:
  base_lr: 0.0025
  #0.0025 = 0.025 * (16 * 1) / (20 * 8)
  #lrnew = lrdefault * (batch_sizenew * GPU_numbernew) / (batch_sizedefault * GPU_numberdefault).
  schedulers:
    - !CosineDecay
      max_epochs: 360
    - !LinearWarmup
      start_factor: 0.
      epochs: 5

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

**ppyoloe_reader.yml**
worker_num: 4
eval_height: &eval_height 640
eval_width: &eval_width 640
eval_size: &eval_size [*eval_height, *eval_width]

TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - PadGT: {}
  batch_size: 16
  shuffle: true
  drop_last: true
  use_shared_memory: true
  collate_batch: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 2

TestReader:
  inputs_def:
    image_shape: [3, *eval_height, *eval_width]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1

综上，改动的配置有：
1.optimizer_300e.yml中base_lr改为0.0025；
2.ppyoloe_reader.yml中TrainReader的batch_size改为16
其他配置没动。

运行指令：
`python tools/train.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml`

出现报错：

(paddle_env) H:\zhujunyu\PaddleDetection-develop1>python tools/train.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
[07/07 11:40:31] ppdet.utils.download WARNING: Config annotation dataset/coco\annotations/instances_train2017.json is not a file, dataset config is not val
id
[07/07 11:40:31] ppdet.utils.download INFO: Dataset H:\zhujunyu\PaddleDetection-develop1\dataset\coco is not valid for reason above, try searching C:\Users
\Administrator/.cache/paddle/dataset or downloading dataset...
loading annotations into memory...
Done (t=12.40s)
creating index...
index created!
[07/07 11:40:49] ppdet.data.source.coco WARNING: Found an invalid bbox in annotations: im_id: 200365, area: 0.0 x1: 296.65, y1: 388.33, x2: 297.67999999999
995, y2: 388.33.
[07/07 11:41:00] ppdet.data.source.coco WARNING: Found an invalid bbox in annotations: im_id: 550395, area: 0.0 x1: 9.98, y1: 188.56, x2: 15.52, y2: 188.56
.
W0707 11:41:02.102504 16816 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
W0707 11:41:02.107491 16816 gpu_context.cc:306] device: 0, cuDNN Version: 8.2.
[07/07 11:41:06] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\Administrator/.cache/paddle/weights\CSPResNetb_l_pretrained.pdparams
Traceback (most recent call last):
  File "H:\zhujunyu\PaddleDetection-develop1\tools\train.py", line 172, in <module>
    main()
  File "H:\zhujunyu\PaddleDetection-develop1\tools\train.py", line 168, in main
    run(FLAGS, cfg)
  File "H:\zhujunyu\PaddleDetection-develop1\tools\train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "H:\zhujunyu\PaddleDetection-develop1\ppdet\engine\trainer.py", line 454, in train
    outputs = model(data)
  File "E:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "E:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "H:\zhujunyu\PaddleDetection-develop1\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "H:\zhujunyu\PaddleDetection-develop1\ppdet\modeling\architectures\yolo.py", line 124, in get_loss
    return self._forward()
  File "H:\zhujunyu\PaddleDetection-develop1\ppdet\modeling\architectures\yolo.py", line 88, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "E:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "E:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "H:\zhujunyu\PaddleDetection-develop1\ppdet\modeling\heads\ppyoloe_hea
d.py", line 218, in forward
    return self.forward_train(feats, targets)
  File "H:\zhujunyu\PaddleDetection-develop1\ppdet\modeling\heads\ppyoloe_hea
d.py", line 158, in forward_train
    return self.get_loss([
  File "H:\zhujunyu\PaddleDetection-develop1\ppdet\modeling\heads\ppyoloe_head.py", line 354, in get_loss
    self._bbox_loss(pred_distri, pred_bboxes, anchor_points_s,
  File "H:\zhujunyu\PaddleDetection-develop1\ppdet\modeling\heads\ppyoloe_head.py", line 291, in _bbox_loss
    loss_dfl = self._df_loss(pred_dist_pos,
  File "H:\zhujunyu\PaddleDetection-develop1\ppdet\modeling\heads\ppyoloe_head.py", line 256, in _df_loss
    loss_left = F.cross_entropy(
  File "E:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\nn\functional\loss.py", line 1719, in cross_entropy
    raise ValueError("Target {} is out of upper bound.".format(
ValueError: Target 604 is out of upper bound.

若“Target *** ”中 ***为负数，则为ValueError: Target *** is out of lower bound.
例如：
    raise ValueError("Target {} is out of lower bound.".format(
ValueError: Target -3 is out of lower bound.

请问该如何解决呢？

**Comment by yjtan118** [comment]
i also have same related error, but my one is target x is out of upper bound. i have also changed the LR based on the same formula that you used.

**Comment by ghostxsl** [comment]
请问，你用的是coco数据集还是自己的数据集？如果是自己的数据集，建议你debug一下：
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/modeling/heads/ppyoloe_head.py#L288
打印一下这里的assigned_ltrb看看，理论上这个tensor的min和max应该在[0, reg_max]之间

**Comment by ghostxsl** [comment]
你是用的amp训练的吗？

**Comment by yjtan118** [comment]
我用自己的数据集. will try print assigned_ltrb 的 value. 没用 --amp as we didnt use default config (base_lr recalculate)

**Comment by yjtan118** [comment]
![file1](https://user-images.githubusercontent.com/36371419/177793415-13bd2cff-aa4d-4570-bbfd-704dd44a34e1.jpg)
![file2](https://user-images.githubusercontent.com/36371419/177793488-fce676b0-b318-4d16-b5fc-142defafb976.jpg)
![file3](https://user-images.githubusercontent.com/36371419/177793501-5a90e4b8-fe16-4fa6-956b-995f75ef73ce.jpg)
![file4](https://user-images.githubusercontent.com/36371419/177793523-df37540b-4b13-4b59-9497-9be067089f54.jpg)
![file5](https://user-images.githubusercontent.com/36371419/177793557-a5adcb85-108b-472b-9320-66506a04ebf7.jpg)
![file6](https://user-images.githubusercontent.com/36371419/177793579-01d624e6-3b91-4344-a020-438cb7b700d1.jpg)
![file7](https://user-images.githubusercontent.com/36371419/177793597-a897794b-4493-42e7-a6a9-ab7048413dec.jpg)

**Comment by yjtan118** [comment]
noticed the loss has "nan" value, which could cause computation error, but not sure the root cause

**Comment by ghostxsl** [comment]
建议可以使用check_nan_inf工具排查一下：
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/flags/check_nan_inf_cn.html#check-nan-inf

**Comment by Wanghe1997** [comment]
1.打印assigned_ltrb，确认tensor的min和max是在[0, reg_max]之间（reg_max默认等于16）；
2.运行check_nan_inf工具，日志如下：

![image](https://user-images.githubusercontent.com/45507837/177931820-6186af83-5ffb-4821-bdaa-ee863984d59b.png)
![image](https://user-images.githubusercontent.com/45507837/177931926-1ec2a9fe-d9a9-4395-be2f-1cdfce560bf9.png)

**Comment by cloudsurging** [comment]
解决了吗？我也遇到这样的问题

**Comment by yjtan118** [comment]
can't solve it :( ...move on to use other framework

**Comment by Vinbert0203** [comment]
paddle真的是个垃圾框架

**Comment by chenxian9999** [comment]
> can't solve it :( ...move on to use other framework

您好，我也碰到了。原先用的cuda11.6 换成cuda11.1 就好了，没有这个问题了。供参考。

**Comment by ionescofung** [comment]
> paddle真的是个垃圾框架

你有什么框架推荐？

**Comment by qipengh** [comment]
这个问题，应该是paddlepaddle框架内部的同步异步拷贝问题导致的。前段我们适配mlu加速卡的时候遇到过。场景是label开始是host的地址，拷贝到device上再拷贝回host，这个数就是坏掉的了。因为拷贝是异步的，所以导致target是个野值。建议paddle排查下各种拷贝逻辑。因为我们这边只能修复我们自己的卡，其他卡GPU、NPU、XPU需要框架自己check。祝好运。

**Comment by nemonameless** [comment]
win下请安装最新develop版本的paddle。
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html

**Comment by tensor-song** [comment]
官方不出面解决一下吗

**Comment by ghostxsl** [comment]
Windows下paddle框架确实有问题，已反馈给Paddle主框架，为了不影响使用可以参考https://github.com/PaddlePaddle/PaddleDetection/issues/6723
