### ISSUE TITLE
如何加载pytorch yolov4(已用x2paddle转换)并进行预测推理？

### ISSUE THREAD

**Issue by wj920291253** [PaddlePaddle/PaddleDetection#6382]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用x2paddle将自己训练的yolov4模型，转换为paddle格式后，如何在paddledetection中加载并预测图片？我看代码里面，paddledetection加载模型并预测的流程是 通过yml文件内参数构建网络结构，然后加载.pdparams权重构建模型，然后进行预测的。我自己在pytorch中训练的yolov4并没有相应的yml文件，该如何加载转换后的模型进行预测？(现有.pdparams/.pdmodel/.pdiparams/.pdiparams.info四个文件）

**Comment by yghstill** [comment]
@wj920291253 直接使用deploy/python/infer.py进行预测就行了。不过还需要一个infer_cfg.yml，主要是配置预处理操作的，具体预处理配置可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/static/configs/yolov4/yolov4_cspdarknet_coco.yml#L162 ，export下yolov4的模型会生成infer_cdf.yml
