### ISSUE TITLE
 module 'paddle.fluid.core_avx.ops' has no attribute 'sync_batch_norm'

### ISSUE THREAD

**Issue by desdeom** [PaddlePaddle/PaddleDetection#6386]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

 paddlepaddle 2.3.1
paddlecls 2.4.1
PaddleClas-release-2.4
使用 cpu训练是报以上错误

**Comment by wangxinxin08** [comment]
CPU训练不能使用sync_batch_norm，建议将norm_type修改为bn

**Comment by desdeom** [comment]
E:\projects\pythonProject\DeepLearning\classification\PaddleClas-release-2.4\ppcls\data\preprocess\ops\timm_autoaugment.py:39: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  _RANDOM_INTERPOLATION = (Image.BILINEAR, Image.BICUBIC)
E:\projects\pythonProject\DeepLearning\classification\PaddleClas-release-2.4\ppcls\data\preprocess\ops\timm_autoaugment.py:39: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  _RANDOM_INTERPOLATION = (Image.BILINEAR, Image.BICUBIC)
usage: generic-image-rec train script [-h] [-c CONFIG] [-o OVERRIDE]
                                      [-p PROFILER_OPTIONS]
generic-image-rec train script: error: unrecognized arguments: norm_type=bn

norm_type在paddlepaddle 2.3.1这个版本中没有，无法设置

**Comment by wangxinxin08** [comment]
直接在配置文件中进行设置这个是对应的repo的参数
