### ISSUE TITLE
提取模型中特定的层做处理

### ISSUE THREAD

**Issue by Lilengli** [PaddlePaddle/PaddleDetection#6387]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我现在正在去尝试修改模型，我的模型是利用paddle_detection的模型配置文件训练的，利用了qat的量化策略，现在我想对于模型中的某个层的输出进行处理，比如模型的卷积层中有relu，我想对于relu的输出进行操作，请问我如何讲这个单独的层拿出来呢，感谢您的回复

**Comment by wangxinxin08** [comment]
建议修改下relu的定义，目前激活函数大多数是以function的形式在forward时调用的，这种print(model)是看不到的，你可以手动在初始化函数使用nn.ReLU进行定义

**Comment by Lilengli** [comment]
原谅我是paddle的初学者，但是我如果是根据YML文件进行操作的话，那这样我应该是修改不了Relu的初始定义的吧

**Comment by wangxinxin08** [comment]
> 原谅我是paddle的初学者，但是我如果是根据YML文件进行操作的话，那这样我应该是修改不了Relu的初始定义的吧

直接改模型中的代码，在定义了激活函数的位置，把激活函数的定义放到初始化函数里面

**Comment by Lilengli** [comment]
您好，我在paddle/vision/models/mobilenetv1.py的这个文件夹下找到了关于mobilenetv1的定义，但是激活函数的定义就是在初始化函数里面
![image](https://user-images.githubusercontent.com/93658838/177936485-c388dbf3-60d4-4806-a1c9-eb296d0eb28c.png)

**Comment by wangxinxin08** [comment]
你用的是那一个repo的模型？

**Comment by Lilengli** [comment]
我使用的是configs/ssd/下的ssd_mobilenet_v1_300_120e_voc这个yml

**Comment by wangxinxin08** [comment]
使用ppdet的话，去ppdet下找源码，在modeling/backboes，你贴的代码和ppdet的实现无关，你需要把激活函数改成和这个类似的

**Comment by Lilengli** [comment]
好的好的，十分感谢！

**Comment by Lilengli** [comment]
您好，我还想在询问一个问题，我这样修改之后，对于我的模型是不是需要重新训练，以前训练的pdparams，weights信息是不是没有用了

**Comment by wangxinxin08** [comment]
> 您好，我还想在询问一个问题，我这样修改之后，对于我的模型是不是需要重新训练，以前训练的pdparams，weights信息是不是没有用了

不是，你只改激活函数，其他的东西不要动，不用重新训练
