### ISSUE TITLE
faster_rcnn如何使用anchor_cluster.py生成的anchors

### ISSUE THREAD

**Issue by jm863936705** [PaddlePaddle/PaddleDetection#6388]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如何将 anchor_cluster,py （Kmeans聚类）生成的anchors用于faster_rcnn中？针对于此，如何修改faster_rcnn的配置文件和源码？

**Comment by wangxinxin08** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/faster_rcnn/_base_/faster_rcnn_r50_fpn.yml#L25 修改这里的anchor_sizes和aspect_ratio，直接把得到的anchor转变为size和ratio的形式
