### ISSUE TITLE
旋转框IOU计算OP，ext_op，win下安装出错

### ISSUE THREAD

**Issue by Tongfengyu** [PaddlePaddle/PaddleDetection#6389]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

按照官方教程，安装出错，求教！
![图片](https://user-images.githubusercontent.com/82866148/177995823-20878f5d-2057-43ba-86c7-6355399a5446.png)

**Comment by wangxinxin08** [comment]
请问现在解决了吗？

**Comment by Tongfengyu** [comment]
h没有

**Comment by wangxinxin08** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/6463#issuecomment-1186999067
