### ISSUE TITLE
tools/cpp_infer.py 进行推理发现速度慢，将batchsize增大 trt_fp32、trt_fp16、trt_int8 加速，但报错

### ISSUE THREAD

**Issue by wyc880622** [PaddlePaddle/PaddleDetection#639]
tools/cpp_infer.py 进行推理发现速度慢，将batchsize增大 trt_fp32、trt_fp16、trt_int8 加速，但报错，不知道如何解决麻烦你们给解决下。
在Fluid模式下进行推理是没有问题的。目前版本1.7.2 master分支下
![image](https://user-images.githubusercontent.com/25219834/81625194-b84fdb80-942a-11ea-8e2b-8c6f29cb0a5d.png)

**Comment by qingqing01** [comment]
@wyc880622 参考 https://github.com/PaddlePaddle/PaddleDetection/issues/615#issuecomment-625747570

**Comment by qingqing01** [comment]
@wyc880622 因为Python发布的whl包没有提供TensorRT，要使用的话，得编译Paddle才行，后续的版本会包含，这个issue先关闭了。
