### ISSUE TITLE
s2anet 训练报错

### ISSUE THREAD

**Issue by Tongfengyu** [PaddlePaddle/PaddleDetection#6392]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

1.一开始训练报错如下：
![image](https://user-images.githubusercontent.com/82866148/178089320-3e702de1-95e6-460b-aee4-fa662a2fa42f.png)
需要在reader.yml加collate_batch: False
2.运行命令：python -m paddle.distributed.launch --gpus 2,3 tools/train.py -c configs/dota/s2anet_1x_spine.yml --amp --eval --use_vdl=True --vdl_log_dir='./output_vdl_dir/s2anet_1x_spine'，报错如下：
![image](https://user-images.githubusercontent.com/82866148/178089455-f9978e4d-dff0-4012-ae1b-7b191309cb17.png)

**Comment by Tongfengyu** [comment]
是不支持batchsize>1训练吗

**Comment by wangxinxin08** [comment]
目前不支持batch size>1训练
