### ISSUE TITLE
ppyoloe导出报错

### ISSUE THREAD

**Issue by 15254042250** [PaddlePaddle/PaddleDetection#6393]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![图片](https://user-images.githubusercontent.com/51038002/178102359-13f05c2e-5368-4ddc-b301-cebaf3530e5b.png)

**Comment by nemonameless** [comment]
请按报错提示检查路径。
