### ISSUE TITLE
Are there any code for model evaluation metric?

### ISSUE THREAD

**Issue by lyw615** [PaddlePaddle/PaddleDetection#64]
I have check out  content  in **eval.py**, but not found the code  required. Are there any code for **precison and recalls calculation** for **single** category?  Which  favors  the **exported** yolov3 model, and **xml** or json format data for validation?

**Comment by lyw615** [comment]
If not offered in the project, completed by myself is ok.

**Comment by jerrywgz** [comment]
PaddleDetection supports evaluation for all input images and metric is based on cocoapi which can be referred here https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/ppdet/utils/coco_eval.py#L122. 
If you want to evaluate single category, you may filter the input images at first.
