### ISSUE TITLE
关键点模型评估，精度始终为0

### ISSUE THREAD

**Issue by Victoria-1** [PaddlePaddle/PaddleDetection#6406]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用hrnet, higherhrnet都试过，进行模型评估的时候，得到的值始终为0
![image](https://user-images.githubusercontent.com/35481439/178441619-09980b78-e600-4ddf-8358-0ac096cc5051.png)
 这是已经迭代到100个epoch了，但从始至终，评估得到的所有结果始终为0，请问大佬能帮忙找下原因吗？我用的是自己的数据集，不是人体关键点检测的，sigmas也是自己算出来的，可能不是很准，但感觉也不至于全部为0，请问大佬能不能帮忙分析下？

**Comment by zhiboniu** [comment]
先把数据标注在图片上可视化出来检查一下吧，如果没问题就在生成训练heatmap_gt的时候也可视化出来看看，这样全0应该是位置对应关系错了

**Comment by Victoria-1** [comment]
@zhiboniu 谢谢回复！原始标注文件我用labelme打开是没什么问题的，但看heatmap_gt确实有问题，全为0，但我的heatmap_pred又应该是正常的
![image](https://user-images.githubusercontent.com/35481439/178671337-eab5b3ca-7aae-411a-8526-c65f06036572.png)
而且我模型能正常训练，正常检测，请问这个heatmap_gt出问题是什么原因呢

**Comment by Victoria-1** [comment]
@zhiboniu 感谢回复，我数据标注用labelme工具检查了一遍，是没问题的，然后heatmap_gt我也看了
![image](https://user-images.githubusercontent.com/35481439/178718430-8228828b-2da0-42b2-ad5b-b6d4df9e4d8d.png)
 我是38个关键点，然后分别保存了每个关键点的位置，因为我原本关键点的位置比较近，压缩到[96,72]以后，感觉很多关键点的位置看起来好像在同一地方。有没有可能是因为我关键点的位置本身比较近的关系？

**Comment by Victoria-1** [comment]
解决了，不是样本的问题，是因为里面有很多参数是给的固定的，应该是只针对person关键点检测的，比如keypoint_metrics.py中
![image](https://user-images.githubusercontent.com/35481439/179134257-db6cae7f-deb2-4417-9f4c-a89027b7244a.png)
 这个地方是写死的，需要修改成自己的catid和cls，还有包括sigmas的参数也是固定的，然后也要根据自己的数据集统计修改。有个建议，是否能将这些接口放开，使得能在外面给定，比如像yml文件指定batchsize，base_lr那样，这样可能友好一点，不需要一步步定位到源码

**Comment by Bradly-s** [comment]
你好，我想问一下如何在keypoint_metrics.py设置sigmas参数？
