### ISSUE TITLE
能不能复现视频显著性检测网络

### ISSUE THREAD

**Issue by upupbo** [PaddlePaddle/PaddleDetection#6408]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 2. 需求场景（请描述你的项目中为什么需要用此功能）; 3. 功能描述（请简单描述或设计这个功能）
项目需要用到ViNet: Pushing the limits of Visual Modality for Audio-Visual Saliency Prediction，能不能复现一下

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by YixinKristy** [comment]
请问您的应用场景是什么呢？您想复现的具体网络是？PaddleDetection暂时没有这方面的复现计划，但您这边可以提供下您的应用场景以及您需要的原因，我们评估下~
