### ISSUE TITLE
增强版picoDet 剪枝

### ISSUE THREAD

**Issue by DavidQiuChao** [PaddlePaddle/PaddleDetection#6409]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问增强版picoDet 模型剪枝有参考的配置文件吗？
文档里面的介绍是老版本的和增强版本对不上

**Comment by yghstill** [comment]
@DavidQiuChao 非结构化剪枝只在PicoDet v1模型上适配支持了，目前增强版的剪枝还没有计划，后续如果有新的配置&模型，会第一时间开源，谢谢关注~
