### ISSUE TITLE
COCO训练报错

### ISSUE THREAD

**Issue by imsotable** [PaddlePaddle/PaddleDetection#6411]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

在COCO数据集上训练报错，运行：
‘’‘python3 -m paddle.distributed.launch tools/train.py -c configs/keypoint/tiny_pose/tinypose_128x96.yml’‘’

报错：
`
LAUNCH INFO 2022-07-12 19:02:08,818 -----------  Configuration  ----------------------
LAUNCH INFO 2022-07-12 19:02:08,818 devices: None
LAUNCH INFO 2022-07-12 19:02:08,818 elastic_level: -1
LAUNCH INFO 2022-07-12 19:02:08,818 elastic_timeout: 30
LAUNCH INFO 2022-07-12 19:02:08,818 gloo_port: 6767
LAUNCH INFO 2022-07-12 19:02:08,818 host: None
LAUNCH INFO 2022-07-12 19:02:08,818 job_id: default
LAUNCH INFO 2022-07-12 19:02:08,818 legacy: False
LAUNCH INFO 2022-07-12 19:02:08,818 log_dir: log
LAUNCH INFO 2022-07-12 19:02:08,818 log_level: INFO
LAUNCH INFO 2022-07-12 19:02:08,818 master: None
LAUNCH INFO 2022-07-12 19:02:08,818 max_restart: 3
LAUNCH INFO 2022-07-12 19:02:08,818 nnodes: 1
LAUNCH INFO 2022-07-12 19:02:08,818 nproc_per_node: None
LAUNCH INFO 2022-07-12 19:02:08,818 rank: -1
LAUNCH INFO 2022-07-12 19:02:08,818 run_mode: collective
LAUNCH INFO 2022-07-12 19:02:08,818 server_num: None
LAUNCH INFO 2022-07-12 19:02:08,818 servers: 
LAUNCH INFO 2022-07-12 19:02:08,818 trainer_num: None
LAUNCH INFO 2022-07-12 19:02:08,818 trainers: 
LAUNCH INFO 2022-07-12 19:02:08,818 training_script: tools/train.py
LAUNCH INFO 2022-07-12 19:02:08,818 training_script_args: ['-c', 'configs/keypoint/tiny_pose/tinypose_128x96.yml']
LAUNCH INFO 2022-07-12 19:02:08,818 with_gloo: 0
LAUNCH INFO 2022-07-12 19:02:08,818 --------------------------------------------------
LAUNCH INFO 2022-07-12 19:02:08,824 Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2022-07-12 19:02:08,824 Run Pod: agdcou, replicas 4, status ready
LAUNCH INFO 2022-07-12 19:02:08,855 Watching Pod: agdcou, replicas 4, status running
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.1.1:58891', '127.0.1.1:36273', '127.0.1.1:57109']
I0712 19:02:14.106011 36448 nccl_context.cc:83] init nccl context nranks: 4 local rank: 0 gpu id: 0 ring id: 0
W0712 19:02:14.689536 36448 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 10.2
W0712 19:02:14.694293 36448 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
loading annotations into memory...
Done (t=8.19s)
creating index...
index created!
LAUNCH INFO 2022-07-12 19:02:41,894 Pod failed
LAUNCH ERROR 2022-07-12 19:02:41,895 Container failed !!!
Container rank 3 status failed cmd ['/home/anaconda3/envs/PPdet/bin/python3', '-u', 'tools/train.py', '-c', 'configs/keypoint/tiny_pose/tinypose_128x96.yml'] code 1 log log/default.agdcou.3.log 
env {'CUDA_VISIBLE_DEVICE': '0,1', 'CONDA_SHLVL': '1', 'LC_ALL': 'en_US.UTF-8\r', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'LD_LIBRARY_PATH':  'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'PADDLE_MASTER': '127.0.1.1:35435', 'PADDLE_GLOBAL_SIZE': '4', 'PADDLE_LOCAL_SIZE': '4', 'PADDLE_GLOBAL_RANK': '3', 'PADDLE_LOCAL_RANK': '3', 'PADDLE_TRAINER_ENDPOINTS': '127.0.1.1:34397,127.0.1.1:58891,127.0.1.1:36273,127.0.1.1:57109', 'PADDLE_CURRENT_ENDPOINT': '127.0.1.1:57109', 'PADDLE_TRAINER_ID': '3', 'PADDLE_TRAINERS_NUM': '4', 'PADDLE_RANK_IN_NODE': '3', 'FLAGS_selected_gpus': '3'}
I0712 19:02:11.151257 36451 gen_comm_id_helper.cc:205] Server listening on: 127.0.1.1:57109 successful.
I0712 19:02:14.106135 36451 nccl_context.cc:83] init nccl context nranks: 4 local rank: 3 gpu id: 3 ring id: 0
W0712 19:02:14.693488 36451 gpu_resources.cc:61] Please NOTE: device: 3, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 10.2
W0712 19:02:14.700191 36451 gpu_resources.cc:91] device: 3, cuDNN Version: 8.1.
loading annotations into memory...
Done (t=7.61s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/PaddleDetection/ppdet/engine/trainer.py", line 393, in train
    self.model, find_unused_parameters=find_unused_parameters)
  File "/home/anaconda3/envs/PPdet/lib/python3.6/site-packages/paddle/fluid/dygraph/parallel.py", line 620, in __init__
    sync_params_buffers(self._layers)
  File "<decorator-gen-58>", line 2, in sync_params_buffers
  File "/home/anaconda3/envs/PPdet/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 299, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-56>", line 2, in sync_params_buffers
  File "/home/anaconda3/envs/PPdet/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/anaconda3/envs/PPdet/lib/python3.6/site-packages/paddle/fluid/framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/PPdet/lib/python3.6/site-packages/paddle/fluid/dygraph/parallel.py", line 401, in sync_params_buffers
    coalesced_var, src=src_rank, group=comm_group, use_calc_stream=True)
  File "/home/anaconda3/envs/PPdet/lib/python3.6/site-packages/paddle/distributed/collective.py", line 573, in broadcast
    ring_id)
OSError: (External) NCCL error(1), unhandled cuda error.  Detail: Resource temporarily unavailable
Please try one of the following solutions:
1. export NCCL_SHM_DISABLE=1;
2. export NCCL_P2P_LEVEL=SYS;
3. Increase shared memory by setting the -shm-size option when starting docker container, e.g., setting  -shm-size=2g.

  [Hint: 'ncclUnhandledCudaError'. A call to a CUDA function failed.] (at /paddle/paddle/fluid/operators/collective/c_broadcast_op.cu.cc:79)
  [operator < c_broadcast > error]
LAUNCH INFO 2022-07-12 19:02:42,497 Exit code -15
`

### 复现环境 Environment

paddle-bfloat           0.1.7
paddledet               2.4.0
paddlepaddle-gpu        2.3.1
python           3.6

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
请检查一下paddle gpu多卡环境是否安装好了，
import paddle;
paddle.utils.run_check()
如果有问题，请参考[安装指导](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/index_cn.html)重新进行安装
