### ISSUE TITLE
yoloe能部署到移动端吗

### ISSUE THREAD

**Issue by LeeLear** [PaddlePaddle/PaddleDetection#6413]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

yoloe能部署到移动端吗

**Comment by zoooo0820** [comment]
可以通过[Paddle-Lite](https://github.com/PaddlePaddle/Paddle-Lite)进行端侧部署。不过综合精度和速度考虑，移动端的部署我们推荐PP-Picodet。
更多模型资料可参考[模型库](https://github.com/PaddlePaddle/PaddleDetection/tree/develop#-%E6%A8%A1%E5%9E%8B%E5%BA%93)
