### ISSUE TITLE
s2anet中的reg_loss_weight

### ISSUE THREAD

**Issue by 939979325** [PaddlePaddle/PaddleDetection#6415]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问下reg_loss_weight[1.0 1.0 1.0 1.0 1.05]这五个权重分别代表哪五个参数的权重

**Comment by zoooo0820** [comment]
可以参考 [这里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/modeling/heads/s2anet_head.py#L890)
