### ISSUE TITLE
请问以下img_1和img_9的inference time 有区别的吗？

### ISSUE THREAD

**Issue by zhuoxun-xun** [PaddlePaddle/PaddleDetection#6422]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![Screenshot from 2022-07-13 17-36-06](https://user-images.githubusercontent.com/108833079/178702578-3643ff70-a2e9-4337-94a6-5cc1c9cae02c.png)

img_1和img_9的inference time 有区别的吗？我应该看哪个inference time 来看性能测试结果. 谢谢！

**Comment by zoooo0820** [comment]
辛苦给一下测试命令

**Comment by zhuoxun-xun** [comment]
python deploy/python/det_keypoint_untte_infer.py --det model dir=output inference/ptcodet_s_320_pedestrtan/--keypotnt_model_dir=output_inference/tinypose 128×96/ - -image ftle=demo/ 000000014439. jpg -device=gpu

**Comment by zoooo0820** [comment]
由于启动会有额外的耗时，请加上`--run_benchmark=True` 进行性能测试

**Comment by zhuoxun-xun** [comment]
好的，明白。谢谢！！
