### ISSUE TITLE
cpp部署代码在windows端进行连续预测产生内存泄漏 #3795 被关闭 但未提供解决方案后续解决方案代码

### ISSUE THREAD

**Issue by StormS0** [PaddlePaddle/PaddleDetection#6429]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

c++ 代码 PaddleDetection严重内存溢出 原因 内部  std::vector<const float*> output_data_list_; 指针未释放

det->Predict(imgs, FLAGS_threshold, 0, 1, &result, &bbox_num, &det_times); 严重内存溢出

修改 object_detector.cc
函数
void ObjectDetector::Predict
函数末尾增加
for (auto it = output_data_list_.begin(); it != output_data_list_.end(); it++)
  {
      if (*it != NULL)
      {
          delete* it;
          *it = NULL;
      }
  }
  output_data_list_.clear();

### 复现环境 Environment

所有c++版本

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by heavengate** [comment]
你好，你用的是哪个预测库版本，我们2.3.1版本发布了，这个问题修复过的

**Comment by StormS0** [comment]
> 你好，你用的是哪个预测库版本，我们2.3.1版本发布了，这个问题修复过的

release 2.4

**Comment by StormS0** [comment]
> 你好，你用的是哪个预测库版本，我们2.3.1版本发布了，这个问题修复过的



> > 你好，你用的是哪个预测库版本，我们2.3.1版本发布了，这个问题修复过的
> 
> release 2.4

并且 [pptracking](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/deploy/pptracking) cpp版本 按照说明部署检测,物体框错乱,一个都不对

**Comment by ShanksYI** [comment]
感谢，感谢，同样的问题解决了
