### ISSUE TITLE
YOLOv3增强模型 训练完预测不出东西

### ISSUE THREAD

**Issue by mcl-stone** [PaddlePaddle/PaddleDetection#643]
按照教程使用YOLOv3增强模型，训练完成后能完成预测，但预测不出东西，训练了六天啊，求解决

**Comment by jerrywgz** [comment]
请问你使用的哪个模型呢

**Comment by qingqing01** [comment]
@mcl-stone 你用的是自己的数据集吗？ 是如何使用的呢？ mAP如何呢？

**Comment by jerrywgz** [comment]
可以确认下你训练的预处理方式和测试的是否对齐

**Comment by mcl-stone** [comment]
使用的yolov3_r50vd_dcn_iouloss_obj365_pretained_coco.yml这个，现在我加上了eval评估，增大了max_iters到1000000，我数据集有40万照片，再训练一边试试吧，现在就是map太低了，不到20，iter已经训练了500000了，不知道map还能不能升上去

**Comment by mcl-stone** [comment]
> 可以确认下你训练的预处理方式和测试的是否对齐

对齐是指哪个？

**Comment by jerrywgz** [comment]
你有修改reader部分的配置文件吗，如果是yolov3_r50vd_dcn_iouloss_obj365_pretained_coco.yml的话对应的数据配置文件是yolov3_enhance_reader.yml
