### ISSUE TITLE
Maskrcnn 部署在 NVIDIA Jetson Xavier NX上的GPU加速问题

### ISSUE THREAD

**Issue by baoxuhong** [PaddlePaddle/PaddleDetection#6435]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我自己训练了一个maskrcnn的模型，部署在 NVIDIA Jetson Xavier NX上，打开了gpu，测试了好几遍，速度都是在200ms左右，这个速度太慢了，我们需要是30ms左右，请问有什么方法解决，下面是实测图和硬件配置
![image](https://user-images.githubusercontent.com/31894804/178911970-0ce1c042-5660-42ef-ae85-0345a6146ded.png)
![image](https://user-images.githubusercontent.com/31894804/178911987-23a880bf-869c-4201-8f4d-efd1ff31869f.png)

**Comment by heavengate** [comment]
重复问题，同 https://github.com/PaddlePaddle/PaddleDetection/issues/6432 当前issue关闭
