### ISSUE TITLE
在使用ppyoloe时，配置文件中batch_size的问题

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleDetection#6436]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在ppyoloe中的yml文件中，有两处都设置了batch_size，一处是总的配置中
![image](https://user-images.githubusercontent.com/101441487/178912851-2bc6da8b-424e-4c98-8e58-6396710bf6f5.png)
还有一处是其base中的reader中
![image](https://user-images.githubusercontent.com/101441487/178912978-13576eab-c39b-4321-a537-8e642df6c7d5.png)
请问是有什么区别吗？我看yolov3中的yml文件中只有一处设置了batch_size。

**Comment by ghostxsl** [comment]
所谓的总的配置中设置的参数会覆盖掉base的参数
