### ISSUE TITLE
什么时候可以导出DETR模型？有排期吗

### ISSUE THREAD

**Issue by hutao568** [PaddlePaddle/PaddleDetection#6439]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 2. 需求场景（请描述你的项目中为什么需要用此功能）; 3. 功能描述（请简单描述或设计这个功能）

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by heavengate** [comment]
DETR模型结构比较复杂，暂不支持导出，我们有FasterRCNN-Swin模型，可以试用下这个
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/faster_rcnn

**Comment by hutao568** [comment]
谢谢
