### ISSUE TITLE
如何用atss替换yolox中的simota？

### ISSUE THREAD

**Issue by ZiQiangXie** [PaddlePaddle/PaddleDetection#6444]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如何用atss替换yolox中的simota？

**Comment by nemonameless** [comment]
简单起见可以把ppyoloe head整体替换yolox head，static_assigner_epoch设置为最大epoch数就是全程ATSS，把reader也可以换下。
如果单独只换simota那一步改动稍微麻烦点，需要保持接口参数一致。但simota已经证明在coco上高于ATSS，在大部分数据集上也一样，个人觉得不是很有必要替换。

**Comment by ZiQiangXie** [comment]
感谢回复。看了接口，确实修改会比较麻烦一些。想替换主要是因为simota训练比较慢，想换成ppyoloe那种分配方式，但是又需要用yolox的检测头。
