### ISSUE TITLE
ppyoloe中学习率的问题

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleDetection#6447]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在你们论文中看见是将基础学习率设为0.01
![image](https://user-images.githubusercontent.com/101441487/179164117-d2902afb-916e-4f8d-8a9b-ca9fc950d108.png)
但我在你们ppyoloe中yaml文件中看到的是0.025
![image](https://user-images.githubusercontent.com/101441487/179164226-eae16b5d-759c-49bf-80d6-ffa9e1ee6a74.png)
请问在coco数据集中是0.025的比0.01的好一下吗？

**Comment by nemonameless** [comment]
lr和总bs成线性比例关系，0.01是总bs=64即8x8时的设置，可以认为每张图lr是1/64。[optimizer_300e.yml](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/_base_/optimizer_300e.yml)默认是L版本的参数，总bs是8x20=160，160/64=2.5，所以设置为0.01x2.5=0.025

**Comment by shangshanruowo** [comment]
好的，感谢
