### ISSUE TITLE
yolox中的预训练模型

### ISSUE THREAD

**Issue by jiejiangd** [PaddlePaddle/PaddleDetection#6448]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

想问一下yolox的预训练模型有提供吗，在yml中都没有看到相应的调用信息，还是说就直接用测试的那个最终模型当预训练模型

**Comment by nemonameless** [comment]
yolox训coco数据集本身就没用预训练权重，是train from scratch的。
如果训业务数据集自己的数据集，一般量级比coco小，可以加载coco训好的yolox的最终权重做预训练去训，会更快收敛精度也会更高。
