### ISSUE TITLE
VOC格式下，eval时无法得到json文件，VOCMetric没有实现

### ISSUE THREAD

**Issue by zhangluustb** [PaddlePaddle/PaddleDetection#6451]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

`python tools/eval.py --config configs/centernet/centernet_mbv3_small_40e_lp.yml -o weights=output/centernet_mbv3_small_40e_lp/best_model.pdparams
`

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
不同metric方式有自己的格式，不能混用。建议先了解下voc和coco的数据集格式。
你可以自己改成COCO metric，但是这样eval的gt也得是json形式。
检测框结果终归是一个类似N*6的数组形式，都可以自己手写python代码离线转成json形式，不依赖框架和模型。
