### ISSUE TITLE
想用命令行直接预测结果

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#6455]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（想用命令行直接预测结果）; 
2. 需求场景（想用命令行直接预测结果）; 
3. 功能描述（想用命令行直接预测结果）

```
python tool/infer.py --source 0  # 网络摄像头
                          img.jpg  # 图像
                          vid.mp4  # 视频
                          path/  # 文件夹
                          path/*.jpg  # glob
                          'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP 流
```

比如我想测试 PP-YOLOE-x 模型 或者 SOLOv2  或者 PP-TinyPose
我只想预测 看看预训练模型的效果

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by YixinKristy** [comment]
您可以参考下PaddleDetection全流程使用文档：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/GETTING_STARTED_cn.md
另外PP-YOLOE、PP-TinyPose或其他您想体验的功能，对应文档上都有预测命令的说明，您可以参照实现~
