### ISSUE TITLE
ppyoloe-s测试速度的问题

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleDetection#6462]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我在飞浆AL Studio上面使用ppyoloe-s训练了东北大学教授提供的钢材表面缺陷的数据集，使用的是V100 32G的环境，评估时发现map值还行，但fps不太行，感觉是不是存在什么问题。我在评估输入图片大小为320*320时的fps只有57
![320](https://user-images.githubusercontent.com/101441487/179399067-a317ad59-abbb-47a6-b902-2ce784919b52.png)
在测试输入为640*640时只有43的fps
![屏幕截图 2022-07-17 202428](https://user-images.githubusercontent.com/101441487/179399134-fcf5c908-fba6-4d06-a3b1-0561269c968e.png)
这和你们的论文里面fsp相距太大
![image](https://user-images.githubusercontent.com/101441487/179399172-fa4dd9dd-80ba-4a0a-9ffd-97cea43214fd.png)
并且我还测试过你们提供的yolox-s，其速度更慢
![yolox](https://user-images.githubusercontent.com/101441487/179399215-495dd7a3-0cd4-42fd-8eae-965483b5443a.png)
请问这是因为是在线测试的原因吗？还是因为我的操作失误之类的

**Comment by lyuwenyu** [comment]
测速度时候加上 `--run_benchmark=True`

详细测速流程见 `https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe`

**Comment by shangshanruowo** [comment]
好的。我看了一下测试的流程，就是说加了--run_benchmark=True时候测的速度是不包含图片预处理和nms后处理的，默认评估时的fps是包含预处理和nms的，是这样的吧？

**Comment by lyuwenyu** [comment]
是的

**Comment by shangshanruowo** [comment]
好的。谢谢
