### ISSUE TITLE
paddleslim中ssd_mobilenet_v1的剪裁后的推理速度的相关问题

### ISSUE THREAD

**Issue by SunYF-0729** [PaddlePaddle/PaddleDetection#6469]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

很费解，不清楚是非结构化剪裁与结构化剪裁的问题还是其他问题？
https://github.com/PaddlePaddle/PaddleSlim/issues/1305#issue-1308604097

**Comment by yghstill** [comment]
统一在 https://github.com/PaddlePaddle/PaddleSlim/issues/1305 跟进。

**Comment by SunYF-0729** [comment]
> 统一在 [PaddlePaddle/PaddleSlim#1305](https://github.com/PaddlePaddle/PaddleSlim/issues/1305) 跟进。

好的，我会持续关注，最近在做这方面，静态图和动态图都走不动，静态图在paddledet下的static文件下敏感度分析文件用不了，然后直接定义全部0.3剪裁后，eval文件也有报错，崩溃了😩
