### ISSUE TITLE
object 365数据集，CACascade网络，检测出的box框score值很低

### ISSUE THREAD

**Issue by ash12358** [PaddlePaddle/PaddleDetection#647]
一开始使用configs/obj365/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.yml这个配置文件进行训练，但是显存不够，就把里面TrainReader部分的target_size改为[416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896]，max_size改为1000，然后就可以训练了。
但是使用第73万代的权重进行测试时，却发现图片里一个目标也检测不出来，仔细研究发现不是检测不出来，而是检测出来的box框的score值太低了，所以没进行显示。
我的测试命令是：
CUDA_VISIBLE_DEVICES=2 python tools/infer.py -c configs/obj365/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.yml -o weights=output/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms/730000 --infer_img=obj365_train_000000561556.jpg

下面打印的是在这张图片里检测出的box框的socre值，从大到小排的序。

[0.19871799647808075, 0.12369368970394135, 0.10165795683860779, 0.09234470129013062, 0.07265584170818329, 0.06411097943782806, 0.062122464179992676, 0.05287851393222809, 0.04176606982946396, 0.025868283584713936, 0.022973747923970222, 0.022617541253566742, 0.015318585559725761, 0.013942703604698181, 0.011371687054634094, 0.00941875297576189, 0.008538085967302322, 0.008139370940625668, 0.008114771917462349, 0.007070728112012148, 0.0062351832166314125, 0.006038640160113573, 0.005461093503981829, 0.0053210086189210415, 0.005245765671133995, 0.004473457578569651, 0.004348668269813061, 0.004306811839342117, 0.004248030483722687, 0.003995387814939022, 0.003923956770449877, 0.003736711572855711, 0.003573616035282612, 0.0034804109018296003, 0.002887747483327985, 0.0027637837920337915, 0.0027543106116354465, 0.002701493678614497, 0.0025193614419549704, 0.0024635721929371357, 0.002446141093969345, 0.002293485216796398, 0.0022904907818883657, 0.0022407814394682646, 0.0022349494975060225, 0.0022058396134525537, 0.002164688892662525, 0.0020860133226960897, 0.0019273929065093398, 0.001894476474262774, 0.0016658041859045625, 0.0016063376097008586, 0.0015928368084132671, 0.0015067075146362185, 0.0015065361512824893, 0.0014710043324157596, 0.0014601039001718163, 0.0014205003390088677, 0.0014046811265870929, 0.001360807684250176, 0.00135509530082345, 0.0012938143918290734, 0.001271952292881906, 0.0012468107743188739, 0.00122644507791847, 0.001204382861033082, 0.0011982853757217526, 0.001098997425287962, 0.001094385632313788, 0.001076515531167388, 0.0010564541444182396, 0.0010551458690315485, 0.0010409322567284107, 0.0010178019292652607]

显卡是GeForce RTX 2080 Ti，11G。
请大家帮忙看看，现在这个情况跟修改的target_size和max_size有关吗，怎么能提高检测效果呢？

**Comment by jerrywgz** [comment]
请问你训练的是自己的数据吗，训练loss下降的是否正常，使用的是哪个预训练模型？分数低就是训练效果不好导致的，但是应该和target_size和max_size影响不大

**Comment by ash12358** [comment]
@jerrywgz 训练的是object365数据集；
目前训练到75万代左右，loss下降的不明显，在1.2左右，训练日志请看最下面的nohup.txt；
使用的预训练模型是默认的https://paddle-imagenet-models-name.bj.bcebos.com/ResNet200_vd_pretrained.tar

[nohup.txt](https://github.com/PaddlePaddle/PaddleDetection/files/4614153/nohup.txt)

**Comment by jerrywgz** [comment]
可以发下你的配置文件吗，如果直接使用object365数据集的话，我理解应该不需要做其他的修改

**Comment by ash12358** [comment]
@jerrywgz 
[cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.yml.txt](https://github.com/PaddlePaddle/PaddleDetection/files/4614200/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.yml.txt)

**Comment by littletomatodonkey** [comment]
您好，这个是8卡的配置文件，如果是4块GPU的话，学习率需要减少一半(0.01 -> 0.005)，同时各阶段的迭代轮数也要相应地扩大为之前的2倍。
这个因为包含365个类别，因此得分较低也是正常的，可视化的时候可以适当减小检测框绘制的得分阈值：https://github.com/PaddlePaddle/PaddleDetection/blob/0dac4bcf75d459eb10fd6005be45f2d1299c1031/tools/infer.py#L256

不过对于行人或者车辆等物体的检测，出来的score应该还是比较高的，看这个结果像是学习率太大，导致收敛不太正常的问题，方便的话可以发下您的训练日志吗？

**Comment by ash12358** [comment]
谢谢，你提醒了我，我又换了一张图进行测试，发现有些类别的socre还是挺高的，但好像类别名字不对。
<img width="582" alt="image" src="https://user-images.githubusercontent.com/41417805/81664629-3c798180-9472-11ea-9333-3dbf3c0d9dff.png">

另外我还有几个问题想问问：
1.学习率减半那里，是修改yml文件中的LearningRate下的base_lr吗，如果我只用1张卡，是不是要把0.01除以8？
2.各阶段的迭代轮数是指milestones: [520000, 740000]这里吗，那max_iters是不是也要放大？
3.我感觉检测出来的类别名字不太对，这该怎么改？
4.用tools/eval.py验证的时候，ap值全是0，这可能是那儿的问题呢
<img width="722" alt="image" src="https://user-images.githubusercontent.com/41417805/81665309-24eec880-9473-11ea-814c-3c53aea33b79.png">

训练日志：
[nohup.txt](https://github.com/PaddlePaddle/PaddleDetection/files/4614519/nohup.txt)

**Comment by ash12358** [comment]
@littletomatodonkey 
谢谢，你提醒了我，我又换了一张图进行测试，发现有些类别的socre还是挺高的，但好像类别名字不对。
<img width="538" alt="image" src="https://user-images.githubusercontent.com/41417805/81665847-d130af00-9473-11ea-9a6b-fe038edf40cc.png">

另外我还有几个问题想问问：
1.学习率减半那里，是修改yml文件中的LearningRate下的base_lr吗，如果我只用1张卡，是不是要把0.01除以8？
2.各阶段的迭代轮数是指milestones: [520000, 740000]这里吗，那max_iters是不是也要放大？
3.我感觉检测出来的类别名字不太对，这该怎么改？
4.用tools/eval.py验证的时候，ap值全是0，这可能是那儿的问题呢
<img width="704" alt="image" src="https://user-images.githubusercontent.com/41417805/81665885-e0aff800-9473-11ea-8645-8d6647b9e0b8.png">

训练日志：
[nohup.txt](https://github.com/PaddlePaddle/PaddleDetection/files/4614545/nohup.txt)

**Comment by littletomatodonkey** [comment]
1. 只用1张卡，base lr需要除以8
2. milestones和max_iter都需要同时乘以8，如果您是单卡训练的话
3. 这个感觉是您的类别没有映射上，可能是背景类的问题，可以看下person和fan的class id是否只差1，这个是需要保证标注文件没有问题的才行~
4. 您可以试着加载我们提供的预训练模型，先试下infer.py，看下是否能够正确预测（类别信息和框的位置），没问题的话 再eval试下
5. 如果是您自己的预训练模型，这个在infer的时候类别信息就是错误的，所以map是0是正常的。

**Comment by ash12358** [comment]
@littletomatodonkey 
好的。human和fan的class id并不是只差1。

我用了你们提供的模型，运行infer.py，发现类别名还是不对。
运行命令：
CUDA_VISIBLE_DEVICES=0 python tools/infer.py -c configs/obj365/cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas.yml -o weights=https://paddlemodels.bj.bcebos.com/object_detection/cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas_obj365.tar --infer_img=obj365_val_000000505576.jpg

**Comment by ash12358** [comment]
@littletomatodonkey 
好的。human和fan的class id并不是只差1。

我用了你们提供的模型，运行infer.py，发现类别名还是不对。
运行命令：
CUDA_VISIBLE_DEVICES=0 python tools/infer.py -c configs/obj365/cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas.yml -o weights=https://paddlemodels.bj.bcebos.com/object_detection/cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas_obj365.tar --infer_img=obj365_val_000000505576.jpg

<img width="579" alt="image" src="https://user-images.githubusercontent.com/41417805/81671098-2fad5b80-947b-11ea-9f08-b66d0b83088a.png">

**Comment by littletomatodonkey** [comment]
您好，那可能是因为您的类别映射文件与我们的不同，您的obj365标注文件是官网的标准文件吗？或者留下邮箱，我们对下类别映射？

**Comment by ash12358** [comment]
@littletomatodonkey 
我也不知道我这边的train.json和val.json是不是官方的。但我发现train.json里面的categories和val.json里的categories里面类别顺序是不一样的。
有可能是我这边这两个文件不是从官网弄来的，你们也可以再完善下代码。

train.json->categories:
[{'id': 216, 'name': 'ship'}, {'id': 348, 'name': 'okra'}, {'id': 186, 'name': 'printer'}, {'id': 241, 'name': 'cigar'}, {'id': 79, 'name': 'cellphone'}, {'id': 211, 'name': 'mango'}, ......]

val.json->categories:
[{'id': 224, 'name': 'scale'}, {'id': 220, 'name': 'tape'}, {'id': 217, 'name': 'chicken'}, {'id': 244, 'name': 'hurdle'}, {'id': 354, 'name': 'game board'}, {'id': 334, 'name': 'baozi'}, {'id': 360, 'name': 'target'}, {'id': 26, 'name': 'plants pot/vase'}, {'id': 209, 'name': 'toothbrush'}, ......]

**Comment by littletomatodonkey** [comment]
train和val需要完全对应上的

**Comment by ash12358** [comment]
@littletomatodonkey 
好的，谢谢

**Comment by ash12358** [comment]
@littletomatodonkey 
还想请教个问题，因为显卡内存不够用，我就把TrainReader部分的target_size改成了[416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896]，把max_size修改成1000，这样的话，EvalReader和TestReader里的target_size和max_size该设置成多少合适呢

**Comment by linyangsdu** [comment]
> 您好，那可能是因为您的类别映射文件与我们的不同，您的obj365标注文件是官网的标准文件吗？或者留下邮箱，我们对下类别映射？

您好，我想知道您放出来的预训练模型对应的 category可以吗

**Comment by nemonameless** [comment]
@littletomatodonkey  Could you provide the JSON of obj365 of your model for training and evaling?  nemonameless@qq.com, Thanks，the category name of the latest JSON fileon the official obj365  website is completely changed.
