### ISSUE TITLE
paddle2onnx转paddleClas以图搜图主体检测模型onnx中出现"Constant"这个额外输入怎么处理

### ISSUE THREAD

**Issue by lovegit2021** [PaddlePaddle/PaddleDetection#6472]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我使用paddle2onnx转以图搜图PaddleClas主体检测模型ppyolov2_r50vd_dcn_mainbody_v1.0_infer时候出现onnx中有一个“Constant”的输入，要怎么处理掉啊

**Comment by nemonameless** [comment]
建议截图下找到Constant对应代码里的位置，改下重新导出ppyolov2的权重再转paddle2onnx
