### ISSUE TITLE
PaddleDetection 不能用第三方库的形式作推理

### ISSUE THREAD

**Issue by Crown-Messi** [PaddlePaddle/PaddleDetection#6478]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

不能直接下载 ppdet来做推理吗，像paddleocr那样。

**Comment by ghostxsl** [comment]
你指的第三方库是什么？你具体是要运行什么任务？

**Comment by Crown-Messi** [comment]
就是我在自己的代码中
import ppdet
ppyolo = ppdet.(configs)
......

这种形式。
我想用把目标检测功能放在我的项目里面。
文档里好像没写怎么直接在代码里面使用，像这里的[use by code](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_en/quickstart_en.md) 一样

**Comment by ghostxsl** [comment]
这个目前还没支持，你的需求已经反馈给开发人员，后续会推动功能上线

**Comment by lyuwenyu** [comment]
不过得自己定制一下  更细节的写法可以参考几个文件 `tools/infer.py`, `ppdet/engine/trainer.py
`  
```
import paddle

import ppdet
from ppdet.core.workspace import load_config, create

cfg = load_config('./configs/faster_rcnn/xxxx.yml')
model = create(cfg.architecture)

```
