### ISSUE TITLE
PaddleDetection转换模型为TensorRT速度太慢，且每次都要重新转换

### ISSUE THREAD

**Issue by YasinFu** [PaddlePaddle/PaddleDetection#6480]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用PaddleDetection进行C++部署时，使用参数如 --run_mode trt_fp16，推理前模型在内部转化为对应精度的TensorRT模型，这个过程时间很长，ppyoloe_m 在nx上耗时5分钟以上，且每次都需要重新转换模型，请问有什么办法讲转换的结果缓存下来，一次转换永久有效

**Comment by ghostxsl** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/python/infer.py#L744
可以设置use_static=True，具体使用方法可以参考官方文档：https://www.paddlepaddle.org.cn/inference/optimize/paddle_trt.html#api

**Comment by wumeideqianbi** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/python/infer.py#L744 可以设置use_static=True，具体使用方法可以参考官方文档：https://www.paddlepaddle.org.cn/inference/optimize/paddle_trt.html#api

解决了，感谢感谢

**Comment by hezhi1220** [comment]
请问转化后的trt模型保存在什么位置？
