### ISSUE TITLE
Question about the YOLOE speeds.

### ISSUE THREAD

**Issue by mtjhl** [PaddlePaddle/PaddleDetection#6482]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi, in your paper of  PPYOLOE, the fps of YOLOE-m is 123.4, about  8.1 ms per image, however, when I use your commands you provided in github
```
CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/ppyoloe_crn_l_300e_coco --image_file=demo/000000014439_640x640.jpg --run_mode=paddle --device=gpu --run_benchmark=True
```
I tested on V100 32G GPU, the time is about 55.8 ms per image, only when I use batch-size =32, it cost about 6.8 ms per image. 

```
2022-07-20 17:46:04,089 - benchmark_utils - INFO - [DET] cpu_rss(MB): 3630, cpu_vms: 0, cpu_shared_mb: 0, cpu_dirty_mb: 0, cpu_util: 0%
2022-07-20 17:46:04,089 - benchmark_utils - INFO - [DET] gpu_rss(MB): 1503, gpu_util: 0.0%, gpu_mem_util: 0%
2022-07-20 17:46:04,089 - benchmark_utils - INFO - [DET] total time spent(s): 0.0813
2022-07-20 17:46:04,089 - benchmark_utils - INFO - [DET] preprocess_time(ms): 25.5, inference_time(ms): 55.8, postprocess_time(ms): 0.0
```

My question is , how to reproduce the 123.4 FPS when batch-size =1 ? Did you get the 123.4 fps results with batch-size =1?

**Comment by lyuwenyu** [comment]
```
# export inference model
python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_300e_coco.pdparams exclude_nms=True

# speed testing with run_benchmark=True
CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/ppyoloe_crn_l_300e_coco --image_file=demo/000000014439_640x640.jpg --run_mode=paddle --device=gpu --run_benchmark=True
```

**Comment by mtjhl** [comment]
@lyuwenyu  Hi, you close this issue, why?

**Comment by mtjhl** [comment]
@lyuwenyu I run those commands, and get 55.8 ms, did you get the result of  8.1 ms ?

**Comment by lyuwenyu** [comment]
你用的是什么环境 我们是能够复现的，，你可以测一下trt的速度是不是和我们的能对齐  55ms+这个貌似差的有点多

**Comment by mtjhl** [comment]
我是在 32G V100 的 GPU 测试的。

**Comment by lyuwenyu** [comment]
软件环境呢， cuda cudnn paddle 的版本等，另外需要注意的是模型测速的时候是不包含nms的  导出时候需要加上`exclude_nms=True`, 细节见[Speed testing部分
](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe)

---
我们测速的可复现的环境是
- V100
- PaddlePaddle: 2.2.2
- CUDA: 10.2
- CUDNN: 7.6
