### ISSUE TITLE
picodet 传递 scale 一维和二维的时候，结果不同，一维比较准

### ISSUE THREAD

**Issue by xiangyubo** [PaddlePaddle/PaddleDetection#6489]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我用 picodet 推理的时候，如果传递的 scale 是一维的，推理出来看着就比较准。同样的情况，我传二维的，结果就变了，不太明白为什么，怎么解决

**Comment by xiangyubo** [comment]
> ### 问题确认 Search before asking
> * [x]  我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> 
> ### 请提出你的问题 Please ask your question
> 我用 picodet 推理的时候，如果传递的 scale 是一维的，推理出来看着就比较准。同样的情况，我传二维的，结果就变了，不太明白为什么，怎么解决

我发现 scale 增加一维，x 和 y 的scale 交换位置才能对齐

**Comment by zoooo0820** [comment]
请参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/python/preprocess.py#L79
