### ISSUE TITLE
打电话识别如何训练自己的数据集

### ISSUE THREAD

**Issue by sweetboxwwy** [PaddlePaddle/PaddleDetection#6492]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/pipeline

**Comment by zoooo0820** [comment]
可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/advanced_tutorials/customization/action_recognotion/idbased_clas.md
