### ISSUE TITLE
多类别目标跟踪使用MCFairMOT 训练bdd100k数据集的格式应该如何准备？

### ISSUE THREAD

**Issue by ALixuhui** [PaddlePaddle/PaddleDetection#6495]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

1. 多类别目标跟踪使用MCFairMOT 训练bdd100k数据集的格式应该如何准备？[文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/mot/mcfairmot/README_cn.md)下没发现准备数据的例子
2. 多类别目标跟踪模型目前只有MCFairMOT 么？

谢谢~

**Comment by nemonameless** [comment]
1.MCFairMOT训练，需要把数据集做成VisDrone-MOT的样子，其实也就是MOT数据集的格式但是类别数更多。BDD100K由于数据集太大，整理较为繁琐暂未提供。也不再推荐使用MCFairMOT去做多类别跟踪。
2.多类别目标跟踪，更推荐使用bytetrack，本质上训练过程就是纯检测了，infer过程接多类别跟踪器即可，PaddleDetection把bytetrack做成了多类别，原论文是单类别。

**Comment by ALixuhui** [comment]
> 



> 1.MCFairMOT训练，需要把数据集做成VisDrone-MOT的样子，其实也就是MOT数据集的格式但是类别数更多。BDD100K由于数据集太大，整理较为繁琐暂未提供。也不再推荐使用MCFairMOT去做多类别跟踪。 2.多类别目标跟踪，更推荐使用bytetrack，本质上训练过程就是纯检测了，infer过程接多类别跟踪器即可，PaddleDetection把bytetrack做成了多类别，原论文是单类别。
请问paddledetection的bytetrack模型[文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/mot/bytetrack/README_cn.md)是这个么？那bytetrack多类别训练的数据如何整理呀，有什么地方可以参考吗

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/mot  
文档看develop分支哈，2.4分支不及时。

就是当成coco格式的检测数据集去训检测即可，不需要id标签。但是infer的时候选择tools/infer_mot.py，以及需要组装成这样
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/mot/bytetrack/bytetrack_ppyoloe.yml 

可以按这个文档都走一遍 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/mot/bytetrack

**Comment by ALixuhui** [comment]
>
好的，非常感谢，我看下~~

**Comment by ALixuhui** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/mot 文档看develop分支哈，2.4分支不及时。
> 
> 就是当成coco格式的检测数据集去训检测即可，不需要id标签。但是infer的时候选择tools/infer_mot.py，以及需要组装成这样 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/mot/bytetrack/bytetrack_ppyoloe.yml
> 
> 可以按这个文档都走一遍 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/mot/bytetrack

你好，我看了下文档还是有些疑惑，bytetrack做多类别视频跟踪时训练时只需要训练检测器，跟踪模块不需要训练么？
使用infer_mot.py时配置好检测器，然后代码会默认调用一个的追踪器？

**Comment by nemonameless** [comment]
跟踪器不参与训练过程，只有infer或eval过程用到跟踪器，相当于纯检测后接了个后处理逻辑。
跟踪器代码是按多类写好的，会自动按类别拆分，单类是作为多类的一个特例，
