### ISSUE TITLE
VITDet复现

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#6497]
### 问题描述 Please describe your issue

您好，我这边复现了今年ECCV2022上一篇论文： [VITDet](https://arxiv.org/abs/2203.16527)。基于Paddledetection进行复现，想问一下是否可以提交Pull Request增加到PaddleDetection里面。

AIStudio地址：https://aistudio.baidu.com/aistudio/projectdetail/4356950?contributionType=1

**Comment by lyuwenyu** [comment]
可以的 欢迎提PR，我们这复现了benckmark那篇  可以在这个基础上把你那边的模型增量添加 
 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/vitdet

**Comment by lyuwenyu** [comment]
提PR之后 可以at我帮你review

**Comment by qdd1234** [comment]
好的，我这两天提交PR
