### ISSUE TITLE
建议增加一个QT编译的教程

### ISSUE THREAD

**Issue by yuyangup** [PaddlePaddle/PaddleDetection#6498]
### 问题描述 Please describe your issue

目前国产化是大势所趋，QT作为国产化开发用的最多的框架，在跨平台和界面开发方面相对于C++ MFC更简单，希望官方能提供一份基于QT的paddledetection编译教程（包含windows和linux），不胜感激

**Comment by lyuwenyu** [comment]
收到，我们会反馈讨论，感觉建议

**Comment by yuyangup** [comment]
> 
大佬，你好啊，什么时候有qt编译的教程啊，我看了官方用的msvc编译器，但是国产化的操作系统是用不了微软那一套东西的啊，需要使用qt 的mingw编译器才行，能给点指导吗？

**Comment by yuyangup** [comment]
> 收到，我们会反馈讨论，感觉建议

大佬，你好啊，什么时候有qt编译的教程啊，我看了官方用的msvc编译器，但是国产化的操作系统是用不了微软那一套东西的啊，需要使用qt 的mingw编译器才行，能给点指导吗？
