### ISSUE TITLE
关于ppyoloe模型导出的问题

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleDetection#6499]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在aistudio上面新建一个项目，克隆paddledetection的源码，安装依赖，验证安装成功，之后我使用!python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_s_300e_coco.pdparams exclude_nms=True命令导出模型，可我在visualdl查看模型的结构，发现模型的输出不太正常，其输出如下：
![P](https://user-images.githubusercontent.com/101441487/180595545-acf5a763-b11a-4c5d-8f51-bc8788ca2c9f.png)
而我用ppyoloe训练玩自己的数据集后再导出，使用的命令是
!python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml --output_dir=./inference_model -o weights=output/ppyoloe_crn_s_300e_coco/best_model.pdparams
查看模型的输出结构是正常的
![p](https://user-images.githubusercontent.com/101441487/180595613-4fd5036a-0df6-4665-b755-3a79413dcd71.png)
我只找到你们提供coco数据集上的ppyoloe的.pdoparams文档，没找到.pdmodel文档

**Comment by lyuwenyu** [comment]
1. coco模型是在这里提供的啊  在download里  https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/ppyoloe
2. exclude_nms=True 这个只是为了测速，之后我么会提供去掉nms的正常的输出，，如果着急用的话可以根据你的需求修改这行 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/modeling/heads/ppyoloe_head.py#L379
