### ISSUE TITLE
用ppyoloe做1分类的目标检测，开启amp的时候，loss越来越大大到60000多什么情况？

### ISSUE THREAD

**Issue by janelu9** [PaddlePaddle/PaddleDetection#6504]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

除了num_class改成了1 ，数据换成了自己的，允许图片中没有bbox之外 没有改动其他参数；然后loss每次在scale之后就会变大 最后居然达到了6万！！！

![image](https://user-images.githubusercontent.com/24219258/180698257-a5502f05-7a3e-48cb-b4fb-579a5b870f32.png)

**Comment by janelu9** [comment]
不开amp的话训练就没事
![image](https://user-images.githubusercontent.com/24219258/180712828-dc5fd58d-5932-406b-9f87-4ab8dac307af.png)

**Comment by lyuwenyu** [comment]
paddle版本是多少，收到反馈  我们这边会排查一下，  建议先关掉amp使用

**Comment by janelu9** [comment]
> paddle版本是多少，收到反馈 我们这边会排查一下， 建议先关掉amp使用

版本是 2.2.0.post101

**Comment by lyuwenyu** [comment]
我们这边在paddle2.2.2上验证的是没有问题的，

**Comment by janelu9** [comment]
> 我们这边在paddle2.2.2上验证的是没有问题的，

可能更是学习率 设置大了 我只用了一张卡
