### ISSUE TITLE
需要重叠裁剪预测_滑窗检测

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#6508]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

![QQ图片20220725164101](https://user-images.githubusercontent.com/6490927/180735484-7f4a772d-36aa-4cc7-8347-0b1dcae103c3.jpg)

需要滑窗预测
9000*9000

不能缩小
细节看不到

需要重叠裁剪之后预测

但是预测
这一张 有识别到
那一张 没有识别到

合并的时候  不知道怎么合并

求解决方法
只想用PaddleDetection来解决

Mask RCNN
SOLOv2 
实例分割 是否可以实现滑窗？

我看PaddleSeg已经实现滑窗了
<html>
<body>

is_slide | bool | 是否通过滑动窗口进行评估 | 否 | False
-- | -- | -- | -- | --
stride | tuple/list | 设置滑动窗宽的宽度和高度，is_slide为True时生效 | 否 | None
crop_size | tuple/list | 设置滑动窗口的裁剪的宽度和高度，is_slide为True时生效 | 否 | None

</body>
</html>

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CocoSkyler** [comment]
对于这种大图片滑框预测比较好，这个需要写后处理和nms过滤冗余框，比较麻烦，希望官方能给个demo

**Comment by nemonameless** [comment]
切图拼图已支持，可以参考 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/smalldet

**Comment by monkeycc** [comment]
给力！
