### ISSUE TITLE
Searching for plugin: NonZero, plugin_version: 1, plugin_namespace

### ISSUE THREAD

**Issue by YouLei0106** [PaddlePaddle/PaddleDetection#6510]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

trt_logger = trt.Logger(trt.Logger.VERBOSE)  # trt.Logger.ERROR
    builder = trt.Builder(trt_logger)
    network = builder.create_network(
        1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    )

    parser = trt.OnnxParser(network, trt_logger)
    # parse ONNX
    with open(onnx_file_path, 'rb') as model:
        if not parser.parse(model.read()):
            print('ERROR: Failed to parse the ONNX file.')
            for error in range(parser.num_errors):
                print(parser.get_error(error))
            return None
    print("Completed parsing ONNX file")

>>> NonZero_2193 [NonZero] inputs: [2743 -> (-1)[INT32]], 
[07/25/2022-21:06:44] [TRT] [I] No importer registered for op: NonZero. Attempting to import as plugin.
[07/25/2022-21:06:44] [TRT] [I] Searching for plugin: NonZero, plugin_version: 1, plugin_namespace: 

>>>In node 2193 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

### 复现环境 Environment

Python3.8.5
CUDA 11.2
TensorRT - 8.4.1.5

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
请问是哪个模型，什么运行命令？
