### ISSUE TITLE
deploy->cpp中cmakelist 语句与注释不符合

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/PaddleDetection#6512]
https://github.com/PaddlePaddle/PaddleDetection/blob/9b6f1205b2fd2dcc333db41e24f0b056ba01dba9/deploy/cpp/CMakeLists.txt#L5

该语句注释说明默认cpu，但是默认参数是开启gpu。

**Comment by wangxinxin08** [comment]
感谢你的细心反馈，也欢迎你向我们提PR
