### ISSUE TITLE
关键点检测

### ISSUE THREAD

**Issue by zhuoxun-xun** [PaddlePaddle/PaddleDetection#6513]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我想请教以下我怎么可以提取关键点的信息比如坐标. 谢谢：）

**Comment by zoooo0820** [comment]
在执行`deploy/python/det_keypoint_unite_infer.py`时增加`--save_res True`即可，结束后会在根目录生成一个`det_keypoint_unite_image_results.json`即为结果文件。

参考命令：
```bash
python deploy/python/det_keypoint_unite_infer.py --det_model_dir {path to detection model} \
              --keypoint_model_dir {path to keypoint model} --device gpu  --image_file {your image}  \
              --save_res True
```

**Comment by zhuoxun-xun** [comment]
你好, 那关键点的对应的坐标信息是要怎么看呢？比如手和脸部。谢谢！

**Comment by zoooo0820** [comment]
点位定义可以参考[这里](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/data/PrepareKeypointDataSet.md)
