### ISSUE TITLE
如何在paddledetection打印模型结构

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleDetection#6515]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问在paddledetection里面有提供打印.yml对应的模型结构的py文件吗？我尝试过在ppdet/modeling/backbones里面添加paddle.summary()的操作，但出现了各种问题。

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/4882
