### ISSUE TITLE
maskrcnn在没有缺陷检出时，报错

### ISSUE THREAD

**Issue by Chen-Song** [PaddlePaddle/PaddleDetection#6518]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

<img width="683" alt="a7e41fb6b47bcd04d99fca24f757780b" src="https://user-images.githubusercontent.com/38151697/180993556-478a711a-4647-4059-8776-f647c87a709c.png">
<img width="793" alt="9586494769d7e7dbff1c8da71ac30e74" src="https://user-images.githubusercontent.com/38151697/180993590-88dc7e69-bdb7-40f1-a6b9-9522820df612.png">
或者使用一张黑图，用mask rcnn模型去infer一下

<img width="701" alt="451e631932585dbe4e182322a59032d3" src="https://user-images.githubusercontent.com/38151697/180993675-d2796b1f-e8b2-460f-9d37-f6860d98368f.png">
在静态图infer中，我这样改就不会报错了

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by zoooo0820** [comment]
你好使用黑图预测暂时能直接复现这个问题，能辛苦补充下paddle / paddledetection及系统环境等信息吗？
另外尝试使用黑图预测时，`np_boxes`值得到的是1，看描述中是-1，方便的话能否将模型和测试图片也提供出来呢
