### ISSUE TITLE
yolov3_enhance 预测问题

### ISSUE THREAD

**Issue by barry2025** [PaddlePaddle/PaddleDetection#652]
![image](https://user-images.githubusercontent.com/20043808/81694209-a3f3f900-9493-11ea-9186-d0a19815772a.png)
yolov3_enhance_reader预测reader的normalize 的 is_scale是 false，意思是说不会除以255，但是减均值除方差的时候还是用归一化的均值方差
![image](https://user-images.githubusercontent.com/20043808/81694354-d0a81080-9493-11ea-93c6-3b3dc8b0a1f6.png)
请问为啥这里不是按照255的均值方差？
![image](https://user-images.githubusercontent.com/20043808/81694790-59bf4780-9494-11ea-80c8-17203b6e10d4.png)

**Comment by jerrywgz** [comment]
这里确实是训练过程中出现的问题，因此在预测的时候需要和训练行为保持一致，后续我们会考虑统一yolo中的预处理方式

**Comment by barry2025** [comment]
感谢回复！我的意思是普通yolov3训练时除以255之后scale到[0,1]，采用[0.485, 0.456, 0.406]作为均值是正常的，为啥yolov3增强版没有scale到[0,1]，相当于像素值是[0,255]，这时候减均值还是用的[0.485, 0.456, 0.406]这一套是不是没啥意义，标准做法是否应该采用[123, 117, 104]这种未归一化的均值才合理？(虽然有了batchnorm，对最终训练结果没啥影响)

**Comment by jerrywgz** [comment]
是的，正常来说如果没有使用scale的话mean值应该是像你说的这样，test的mean这样做只是为了和训练对齐
