### ISSUE TITLE
ByteTracker

### ISSUE THREAD

**Issue by Xingyu-Romantic** [PaddlePaddle/PaddleDetection#6520]
https://github.com/PaddlePaddle/PaddleDetection/blob/67c757d3d499f8c8a03e2e380d0c091daedfb6c0/tools/infer_mot.py#L93

这里预测infer_mot 的 ByteTrack 加载权重应该是  self.model 加载 weights ，你们对应一下训练的代码中加载权重的这个。
我用的配置文件是 mot/bytetrack/yoloe....xxx.yaml

**Comment by nemonameless** [comment]
你的问题是什么呢？按照文档使用有遇到什么问题吗？

**Comment by Xingyu-Romantic** [comment]
而且，采用ByteTrack进行多类别多目标追踪的适合，modeling.mot. write_mot_results 这个里面的函数，127行128行要注释掉
```
# if data_type == 'mot':
                #     cls_id = -1
```

**Comment by nemonameless** [comment]
1.MOT模型的infer eval调用的是infer_mot.py和eval_mot.py，调用的是`ppdet/engine/tracker.py`里的`load_weights_jde`和`load_weights_sde`函数，这点不同于检测模型。但MOT模型的训练是和检测模型一样调用train.py，调用的是`ppdet/engine/trainer.py`里的函数。
2. write_mot_results里根据data_type有不同写入格式之分，data_type='mot'时每行最后3列都是-1这是[MOTChallenge](https://motchallenge.net/instructions)的格式，单类别不区分种类号，默认写入格式后的结果txt文件是要提交到MOTChallenge官网评测的。

结论：代码无误
