### ISSUE TITLE
请问萌新如何进行关键点识别

### ISSUE THREAD

**Issue by jianxin123** [PaddlePaddle/PaddleDetection#6528]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

之前用paddlex进行目标检测，效果不错，但是一旦想要识别指针之类的计算角度的东西就好像不好用了，查了以下是不是可以用paddleDetection的关键点识别计算角度。目前需求是在一张图片合中先框出带检测物体然后计算他指针的转角，我用labelme标注时一块把框和关键点标了，请问接下来该如何转成detection需要的格式以及如何训练，貌似配置config挺麻烦的，文档看的不是很明白，因为不是人体关键点检测，也没有具体的例子，希望paddde能有个简单的例子。还有我看文档预测时参数里有检测模型和关键点模型，目标检测模型是单独训练的吗。

**Comment by zoooo0820** [comment]
可以参考[关键点检测标注工具](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/data/KeyPointAnnoTools.md) 以及 [关键点检测任务二次开发](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/advanced_tutorials/customization/keypoint_detection.md)这两个文档。

另外，关于你的这个任务，建议也关注下[旋转框检测](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/dota)是否符合需求

**Comment by jianxin123** [comment]
你好，谢谢回复。关键点检测标注工具&nbsp;文档中create&nbsp;&nbsp;polygons 是否应该是create point。合还有生成coco后 目录好像也和文档中不太一样，这是我生成的。不知道有没有问题。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 上午10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 请问萌新如何进行关键点识别 (Issue #6528)





 
可以参考关键点检测标注工具 以及 关键点检测任务二次开发这两个文档。
 
另外，关于你的这个任务，建议也关注下旋转框检测是否符合需求

**Comment by jianxin123** [comment]
> 可以参考[关键点检测标注工具](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/data/KeyPointAnnoTools.md) 以及 [关键点检测任务二次开发](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/advanced_tutorials/customization/keypoint_detection.md)这两个文档。
> 
> 另外，关于你的这个任务，建议也关注下[旋转框检测](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/dota)是否符合需求

你好 这个旋转框检测的例子有版本要求吗。我之前用paddlex时没啥问题，用这个训练显示cudnn错误。

**Comment by Nullpo1nter** [comment]
同问，我现在想在老鼠上使用关键点识别，但是config文档如何配置查不到相关资料。。。
