### ISSUE TITLE
请问怎样修改评估脚本eval.py，使得tensorboard可以记录训练评估所得到得召回率，使用coco数据集

### ISSUE THREAD

**Issue by learning-boy** [PaddlePaddle/PaddleDetection#654]
请问怎样修改评估脚本，使得tensorboard可以记录训练评估得召回率，使用coco数据集

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/master/tools/train.py#L285 这里得到的box_ap_stats中包含了recall的信息，
![image](https://user-images.githubusercontent.com/22989727/81885337-b887dc80-95cc-11ea-8198-59f45f26e3a0.png)

box_ap_stats为一个list，其中每一个值即对应上图中每一行的指标，如果希望使用recall的话，可以考虑将box_ap_stats[8]加到tb_writer中

**Comment by learning-boy** [comment]
好的谢谢您，非常感谢您的回复
