### ISSUE TITLE
RROR: Could not build wheels for opencv-python, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by FANG-MING** [PaddlePaddle/PaddleDetection#6540]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

```pip install -r requirements.txt```
但是安装失败

```
ERROR: Could not build wheels for opencv-python, which is required to install pyproject.toml-based projects
```

**Comment by ghostxsl** [comment]
看错误信息是没安装成功，可以尝试按照报错信息中安装pyproject.toml-based projects或者换个环境呢
