### ISSUE TITLE
YOLOX训练自己数据集，AP一直为0

### ISSUE THREAD

**Issue by Xingyu-Romantic** [PaddlePaddle/PaddleDetection#6541]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

训练YOLOX MOT模型，采用COCO预训练模型，按原配置训练24个EPOCH，其中AP一直为0
数据格式不变，训练PPYOLOE，AP是能达到30左右的。
使用Aistudio脚本任务，

还未完全收敛，但是这样继续下去还有用吗
![image](https://user-images.githubusercontent.com/22713115/181683605-44f0922d-948e-4539-8ab3-96b31759357e.png)
![image](https://user-images.githubusercontent.com/22713115/181683692-a7a781b4-cade-4cca-af1f-cf86b95f85bf.png)

这个是预测出来的结果，是YOLOX多尺度的问题吗，还是其他原因，但是PPYOLOE不也有多尺度吗
![image](https://user-images.githubusercontent.com/22713115/181683837-bb7fca1b-bf1e-4e7c-8109-2142da210467.png)

**Comment by nemonameless** [comment]
配置文件做了什么改动吗，Mosaic的prob: 0试试。
如果不行先用PPYOLOE训检测然后去做跟踪，在慢慢排查问题。

**Comment by Petal99** [comment]
同样的bbox mAP情况，我训练的yolox_nano模型，看了下loss_cls的曲线也是有问题的

**Comment by nemonameless** [comment]
> 同样的bbox mAP情况，我训练的yolox_nano模型，看了下loss_cls的曲线也是有问题的

请说明环境版本和改动代码谢谢。
paddle版本建议使用paddle2.2.2。

**Comment by Petal99** [comment]
> > 同样的bbox mAP情况，我训练的yolox_nano模型，看了下loss_cls的曲线也是有问题的
> 
> 请说明环境版本和改动代码谢谢。 paddle版本建议使用paddle2.2.2。

我用的就是paddle2.2.2，改动了配置文件，我自制数据集是10个类，在coco_detection.yml文件里改了自己的数据集路径和类别数，然后设置的batchsize=64 base_lr=0.01
