### ISSUE TITLE
Hrnet and export eval problem！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleDetection#6542]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

Hi， 
1 请问下大佬 python3 tools/eval.py -c configs/keypoint/higherhrnet/higherhrnet_hrnet_w32_512 .yml ,执行这个以后,  结果为这个，为啥没有map的指标统计打印出来呢？
![2a19e4457ea008fe3261f38ad85a290](https://user-images.githubusercontent.com/8407513/181701335-27eba4e4-836a-4039-8568-17857d881f38.jpg)
2 通过以下命令将训练得到的模型导出，确定paddle所有的模型导出前后都是完全一致的吗？ paddle detection 是否有命令或者支持 直接测试export出的 pdiparam和pdmodel map等指标？ https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/slim

![1659077706185](https://user-images.githubusercontent.com/8407513/181701377-6be4ebdd-6fe5-490f-bebf-e195cfda1aab.jpg)

BR

### 复现环境 Environment

paddlepaddel 最新release
paddleslim 最新release
paddledetection 最新release 

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zoooo0820** [comment]
你好，
关于higherhrnet的问题我们已经复现这个Bug，正在排查问题。
关于导出模型，理论上导出前后是一致的；目前暂未提供直接使用导出后的模型进行评估的工具
