### ISSUE TITLE
关于PaddleDetection infer save result问题

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#6546]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

现在如果使用PaddleDetection 的infer功能时 如果使用save_results就会报错
![image](https://user-images.githubusercontent.com/78856426/181905607-3d37a66c-f76d-4c9a-b6bd-014195a8b9f8.png)

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/6547 问题已修复 感谢反馈
