### ISSUE TITLE
使用OID数据集子集训练

### ISSUE THREAD

**Issue by QuantumLiu** [PaddlePaddle/PaddleDetection#6549]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，请问如何在OID dataset上的某几类物体数据集，训练自己的模型呢？
我看到有OID的预训练模型和OID eval的文件，但是没看到使用OID数据集训练的代码，谢谢！

**Comment by ghostxsl** [comment]
需要自己将数据集格式转成coco格式再进行训练
