### ISSUE TITLE
S2Anet本地部署

### ISSUE THREAD

**Issue by jianxin123** [PaddlePaddle/PaddleDetection#6552]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/dota
请问这个链接的镜像是不是没了。
我显卡3070 cuda11.1 paddle2.2  paddledetection 2.2 按照教程训练显示cudnn错误。会不会是目前这个只支持cuda10 cudnn7.可30显卡好像对cuda10不太友好。请问有没有办法能本地安装上这个模型阿

**Comment by wangxinxin08** [comment]
可以看下cudnn版本和cuda 版本是否匹配，另外要安装对应cuda版本和cudnn版本的paddle

**Comment by jianxin123** [comment]
> 可以看下cudnn版本和cuda 版本是否匹配，另外要安装对应cuda版本和cudnn版本的paddle

目前的环境之前在paddlex中都是能用的，cuda11.1 cudnn8 是适配的

**Comment by wangxinxin08** [comment]
报错截图可以发下

**Comment by jianxin123** [comment]
> 报错截图可以发下
![Screenshot from 2022-08-02 15-58-14](https://user-images.githubusercontent.com/32336392/182323717-00358964-193a-4b84-931d-43131586b389.png)

**Comment by jianxin123** [comment]
我换了一个适配cuda11.1的cudnn还是不行

**Comment by wangxinxin08** [comment]
报错显示cudnn version不对，目测还是环境的问题，建议你使用官方的dcoker吧

**Comment by jianxin123** [comment]
> 报错显示cudnn version不对，目测还是环境的问题，建议你使用官方的dcoker吧

我也想用官方docker，可是那个好像失效了，我下不来

**Comment by wangxinxin08** [comment]
可以从这里下载https://hub.docker.com/r/paddlepaddle/paddle/tags

**Comment by jianxin123** [comment]
好的好的  谢谢大佬 网页打开有些慢，我今天试一下。十分感谢

**Comment by jianxin123** [comment]
还向请教以下我之前paddlex和paddle装在了conda环境下，现在又下了docker环境的话两个版本的paddle import时会不会i冲突，有什么办法吗

**Comment by wangxinxin08** [comment]
docker环境和本地环境不相关，是隔离的

**Comment by jianxin123** [comment]
主要代码中只有import paddle  不知道会是哪个，我先试试 不行在来问大佬。

**Comment by jianxin123** [comment]
> docker环境和本地环境不相关，是隔离的

你好，我用docker成功运行了代码，但是不知道输出的数字是什么意思，看着不象角度，是有什么换算公式
![Screenshot from 2022-08-04 15-31-25](https://user-images.githubusercontent.com/32336392/182790159-d1ae4287-e1ac-4f4d-8072-ef1c13f63c83.png)
吗

**Comment by wangxinxin08** [comment]
0.17是置信度

**Comment by jianxin123** [comment]
好家伙，输出的竟然是类别和置信度 ，我以为会带角度的，这样岂不是跟目标检测差不多

**Comment by wangxinxin08** [comment]
输出四个点的坐标和输出角度是等价的

**Comment by jianxin123** [comment]
> 输出四个点的坐标和输出角度是等价的

你好，我用的版本save_txt不能用了，用的是--save_results  保存下来的是bbox.json 可以获得四个点的坐标。我想在推理的时候直接在计算角度，不想读取json再分析，我看infer.py时没有发现哪里可以增加打印输出的地方，trainer.predict()返回的是一个none，但是结果还是保存到了json，请问有什么办法直接获取得到分析的结果吗

**Comment by jianxin123** [comment]
![Screenshot from 2022-08-05 15-15-51](https://user-images.githubusercontent.com/32336392/183024654-ebacfc68-b2b6-4f78-a8e2-1b7ce333d23b.png)
如图，不导出模型时可以从bbox.json获取预测框坐标，导出模型后只有x1,y1坐标，bbox后面的坐标请问是什么意思，另外可以像paddlex一样直接写个预测函数获取结果吗，paddlex很方便就能获得预测结果然后可以进行后处理

**Comment by jianxin123** [comment]
@wangxinxin08 
别沉啊，555，就差最后一步了

**Comment by wangxinxin08** [comment]
deploy/python/infer.py输出的结果应该是clsid, score, x1, y1, x2, y2, x3, y3, x4, y4，你可以从这里https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/python/infer.py#L196 获取，相关的代码你可以根据你的需求改下， save_results结果目前在旋转框上有点问题

**Comment by jianxin123** [comment]
可是deploy/python/infer.py输出的结果bbox只有四个值，换成点位也就2个点 而且后面还有一个负值。。。感觉不太对劲啊 ，但是图片框的还是正确的，这张图就是deploy框出来的

**Comment by wangxinxin08** [comment]
> 可是deploy/python/infer.py输出的结果bbox只有四个值，换成点位也就2个点 而且后面还有一个负值。。。感觉不太对劲啊 ，但是图片框的还是正确的，这张图就是deploy框出来的

保存成json的代码有问题，这里只考虑了正框

**Comment by jianxin123** [comment]
好的好的，我看看我能不能根据tools里面的改一下，改成四个点

**Comment by jianxin123** [comment]
请问，我想把目标检测得到的预测框裁减下来，paddle有相关的api吗 @wangxinxin08

**Comment by wangxinxin08** [comment]
> 请问，我想把目标检测得到的预测框裁减下来，paddle有相关的api吗 @wangxinxin08

没有相关的api，可以搜索下cv2是不是有类似的api可以实现你的功能

**Comment by jianxin123** [comment]
我用cv2老是报错误，百度说是可能图片路径问题但是我之间imshow时可以打开的。bbox也是有的，应该是40行有问题，但是我不知道问题在哪
![Screenshot from 2022-08-16 11-06-11](https://user-images.githubusercontent.com/32336392/184790080-ac6224aa-3263-42b2-820c-8fac23a8a6e3.png)

**Comment by jianxin123** [comment]
图片怎么托进来不显示了。。。。

**Comment by wangxinxin08** [comment]
建议自己搜索下cv2从原图中切出旋转框的方法，这种事情自行解决吧
