### ISSUE TITLE
./data文件如何打开查看信息

### ISSUE THREAD

**Issue by Lilengli** [PaddlePaddle/PaddleDetection#6557]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问我在使用敏感度分析工具sensitive.py进行敏感度分析时，生成了敏感度信息文件demo.data文件，请问我该如何打开这个文件并查看其中的不同剪裁率下的loss以及敏感度信息呢

**Comment by minghaoBD** [comment]
![image](https://user-images.githubusercontent.com/79566150/182510383-3f8dc34c-55f4-448e-af79-2029867b1dce.png)
https://github.com/PaddlePaddle/PaddleSlim/blob/4d75cb9cecf5a02e789576b0c02ce7376615dafd/docs/zh_cn/api_cn/static/prune/prune_api.rst
您好，可以参考下剪裁的文档。
