### ISSUE TITLE
使用paddledetection进行目标检测MAP太低了，相同数据集easydl可以到40%

### ISSUE THREAD

**Issue by zouxiaodong** [PaddlePaddle/PaddleDetection#6558]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用如下配置进行训练 ,之前使用yolov3配置一样的很低，在微信群里发了没人响应。
python tools/train.py -c configs/ppyolo/kiwi_coco.yml -o pretrain_weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams  --amp --eval      --use_vdl=true          --vdl_log_dir=vdl_dir/scalar 

_BASE_: [
  '../datasets/kiwi_coco.yml',
  '../runtime.yml',
  './_base_/ppyolo_r50vd_dcn.yml',
  './_base_/optimizer_1x.yml',
  './_base_/kiwi_reader.yml',
]

snapshot_epoch: 5
weights: output/kiwi_coco/model_final

![image](https://user-images.githubusercontent.com/46236818/182274991-c5b70121-9feb-41ab-a71f-ee9766d00977.png)

![image](https://user-images.githubusercontent.com/46236818/182274555-e1e962f3-a208-48c5-a446-8ba08af59d97.png)

paddledetection跑出来的MAP太低了根据没法使用，infer时根本出不来框。
![image](https://user-images.githubusercontent.com/46236818/182274659-aee2c801-4e00-4b5d-b7d0-b65aba2fc717.png)

相同数据集在EASYDL上高太多

**Comment by ghostxsl** [comment]
建议不要使用amp训练
