### ISSUE TITLE
Hrnet file code bug！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleDetection#6559]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

  Hi， 
    请问下下面param_attr  和 bias_attr  为啥右值完全一样，如下图的使用，不会出问题吗？ 麻烦帮忙看下是不是bug，是否可以详细解释下用处？
       param_attr = ParamAttr(
            learning_rate=norm_lr, regularizer=L2Decay(norm_decay))
        bias_attr = ParamAttr(

![image](https://user-images.githubusercontent.com/8407513/182284283-0b192c1d-e03d-4b53-a66d-59feffcf6754.png)
   第二，  请问下 bottleneck_block = self.add_sublayer 这个函数相当于pytorch的什么呢？  感觉找不到这函数定义啊。。。
![image](https://user-images.githubusercontent.com/8407513/182286582-802d0128-64e2-457f-90cf-e79fee43c8fd.png)
   据我对paddle所知， "  # 1.6中 列表中的Layer需要单独调用 add_sublayer, 增加使用成本 # 而且add_sublayer的第一个参数必须唯一，唯一出错 "  飞桨做了升级等等，请问是否可以详细讲解下来龙去脉，以及目前的妥善升级处理？ 
    多谢
BR 

### 复现环境 Environment

PADDLE 
PPDET
PPSLIM 
都是最新的release版本

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jerrywgz** [comment]
ParamAttr 指定的是特定参数的学习率和weight decay，weight和bias可以使用相同的ParamAttr设置
paddle中的add_sublayer等价于torch中的add_module
