### ISSUE TITLE
Hrnet pose just for fun？

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleDetection#6563]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi， 
请问下，这个hrnet_w32_256x192/model.nb是否在手机或者arm cpu上跑过，尤其是高通865上？
能share下这个下面链接的具体测速数据吗？多谢
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/lite
cp {PadddleDetection_Root}/output_inference/hrnet_w32_256x192/model.nb ./model_keypoint/      
BR

**Comment by jerrywgz** [comment]
部署再arm cpu上的话我们更推荐使用tinypose模型，https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/keypoint/tiny_pose#pipeline%E6%80%A7%E8%83%BD 这里有高通865上的测试数据 HRNet属于服务器端的模型，我们有测试T4上的性能可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/keypoint/KeypointBenchmark.md#benchmark-on-server
