### ISSUE TITLE
ppyoloe激活函数的问题

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleDetection#6570]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我最近学习了ppyoloe主干结构的源码，我发现其主干结构所使用的激活函数和网上画的图不一致，我看代码是，主干结构中除了EffectiveSELayer模块是使用hardsigmoid激活函数以外，其他地方都是使用的swish激活函数。并且我用visualdl中看了网络结构确实是这样的。
但在aistudio加精的项目给出的网络结构图是这样的：
![ppyooe](https://user-images.githubusercontent.com/101441487/182372086-c83dabf7-a7e1-49f7-9ed1-e3866135348e.png)
我看了ppyoloe的论文，里面我好像没有找到比较详细的网络结构，请问你们ppyoloe的主干结构中一直是使用swish激活函数吗？还是之前是使用的relu和silu

**Comment by ghostxsl** [comment]
目前对于ppyoloe的backbone来说swish等价于silu
