### ISSUE TITLE
solov2导出onnx

### ISSUE THREAD

**Issue by SiChuanJay** [PaddlePaddle/PaddleDetection#6583]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我在使用solov2导出onnx模型时，出现如下错误。请问是否solov2不支持导出onnx，如果我要在openvino和trt上部署solov2，该使用什么方法呢？
![图片](https://user-images.githubusercontent.com/52130681/182752600-39c90fe0-12c5-4cea-b72d-7603d783b8d8.png)

**Comment by wangxinxin08** [comment]
报错信息显示有三个op不支持，trt部署可以参考Paddle-TRT https://www.paddlepaddle.org.cn/inference/master/guides/nv_gpu_infer/gpu_trt_infer.html, openvino部署的话可以考虑参考https://docs.openvino.ai/latest/omz_tools_accuracy_checker_pdpd_launcher.html 试下
