### ISSUE TITLE
Copypaste

### ISSUE THREAD

**Issue by CocoSkyler** [PaddlePaddle/PaddleDetection#6585]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

对于现实中大图片需要检测的目标不是很多，能不能实现copypaste这个数据增强功能，想着ppocr已经实现了，我看detection还没有实现

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
感谢你的反馈，我们后期会评估下需求，也欢迎你为我们贡献代码
