### ISSUE TITLE
自己训练的检测效果不好

### ISSUE THREAD

**Issue by zhuoxun-xun** [PaddlePaddle/PaddleDetection#6587]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我用了自己的数据集来二次开发吸烟检测。请教以下有什么建议可以达到更好的精准度吗？谢谢！

**Comment by YixinKristy** [comment]
可以详细描述下 效果不好的类型么？比如效果不好的情况集中于哪几种，最好配上示例图~ 这样比较容易针对您的bad case给出针对性的建议~

**Comment by cheesezoella** [comment]
你好，就是有没有吸烟的动作但还是会检测出在吸烟
![Screenshot from 2022-08-08 09-58-33](https://user-images.githubusercontent.com/108833079/183323622-fb0d7a37-08c6-4ab9-8eb0-077f8db29c50.png)
。

**Comment by cheesezoella** [comment]
你好，比如烟较小的时候就没办法准确的预测到吸烟的动作了。我训练的数据集图片尺寸大概是512x512，如果提高分辨率不知对模型对什么影响呢？
