### ISSUE TITLE
PaddleDetection不支持Voc的instance segmentation数据集吗？

### ISSUE THREAD

**Issue by visionKinger** [PaddlePaddle/PaddleDetection#6588]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PaddleDetection不支持Voc的instance segmentation数据集吗？

**Comment by wangxinxin08** [comment]
可以转成coco格式

**Comment by visionKinger** [comment]
> 

instance segmentation在coco里是点，voc是图片，没法转

**Comment by wangxinxin08** [comment]
coco有API可以把图片转成点的，你可以搜索下

**Comment by visionKinger** [comment]
> 



> 

pycocotools？

**Comment by visionKinger** [comment]
> coco有API可以把图片转成点的，你可以搜索下

之前查了好久了，方便说一下是啥API吗？pycocotools肯定是不行 哭死

**Comment by wangxinxin08** [comment]
网上搜素下https://zhuanlan.zhihu.com/p/84214563, 见polygon和mask互转
