### ISSUE TITLE
剪枝不是应该剪完再重新训练吗

### ISSUE THREAD

**Issue by czczmr** [PaddlePaddle/PaddleDetection#6598]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

正常剪枝不是直接剪去通道后再微调吗？
python tools/train.py -c configs/{MODEL.yml} --slim_config configs/slim/{SLIM_CONFIG.yml}
这个为什么是训练和剪枝放一起了呢

**Comment by tranngocphuong89** [comment]
我也关注
