### ISSUE TITLE
YOLO Loss 中 为什么要加scale_x_y

### ISSUE THREAD

**Issue by sandy-ssdut** [PaddlePaddle/PaddleDetection#6599]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

YOLO loss 中为什么要添加scale_x_y？ 是参考了哪篇论文吗？
添加了scale_x_y 之后， 从网络输出恢复yolo_box 时， 公式变成了 scale_x_y * sigmoid(tx) + cx  吗

**Comment by ghostxsl** [comment]
这个是在PPYOLO里提到的一个trick，细节部分可以参考文中Grid Sensitive部分：https://arxiv.org/pdf/2007.12099.pdf
