### ISSUE TITLE
这个文件怎么是这样的。。。

### ISSUE THREAD

**Issue by gongkaixiong** [PaddlePaddle/PaddleDetection#6605]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

develop分支下的这个文件  感觉怪怪的
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/pipeline/ppvehicle/rec_word_dict.txt

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zoooo0820** [comment]
你好，我们即将发布PP-Vehicle，车牌识别功能作为其中一部分，使用到了ocr任务。这个文件是对应ocr任务的字符表，用于将模型输出对应到具体的字符。
