### ISSUE TITLE
模型转换paddle2onnx yolox 少两个op

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleDetection#6606]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

模型转换paddle2onnx yolox 少两个op

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
请问缺少哪两个呢？你的运行命令和报错截图请都发下谢谢。语句自测无误。
```
job_name=yolox_s_300e_coco
paddle2onnx --model_dir output_inference/${job_name} --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 12 --save_file ${job_name}.onnx
```
