### ISSUE TITLE
Faceboxes模型导出失败

### ISSUE THREAD

**Issue by AnBaolei1984** [PaddlePaddle/PaddleDetection#662]
python3 tools/export_model.py -c configs/face_detection/faceboxes_lite.yml --output_dir=./inference_model   -o weights=https://paddlemodels.bj.bcebos.com/object_detection/faceboxes_lite.tar TestReader.inputs_def.image_shape=[3,640,640]

执行上面的命令，出现下面的错误

AssertionError: Parameter file [~/.cache/paddle/weights/faceboxes_lite.pdparams] not exits

**Comment by still-wait** [comment]
@AnBaolei1984 请拉最新的release 0.2分支的代码进行测试

**Comment by AnBaolei1984** [comment]
> @AnBaolei1984 请拉最新的release 0.2分支的代码进行测试

![2501589427058_ pic_hd](https://user-images.githubusercontent.com/49897975/81889633-96935780-95d6-11ea-8ee9-be3c2de67a47.jpg)
重新拉代码后，还是一样的问题

**Comment by still-wait** [comment]
@AnBaolei1984 请问你的paddle版本是多少，我们在paddle 1.7.1下使用最新PaddleDetection release/0.2的代码测试，没发现问题

**Comment by AnBaolei1984** [comment]
> @AnBaolei1984 请问你的paddle版本是多少，我们在paddle 1.7.1下使用最新PaddleDetection release/0.2的代码测试，没发现问题

1.6.2，那我升级下paddle试试，谢谢

**Comment by still-wait** [comment]
@AnBaolei1984 更新paddle后是否还有问题？

**Comment by jerrywgz** [comment]
这个问题是由于paddle 1.7版本对参数加载接口做了调整，用新版的检测库不能和旧版的paddle导致的，升级至1.7及以上版本即可

**Comment by AnBaolei1984** [comment]
> @AnBaolei1984 更新paddle后是否还有问题？

paddle更新到1.7.2，就可以了。看来是版本问题，谢谢
