### ISSUE TITLE
基于PP-YOLOE的知识蒸馏方法和代码有吗？

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#6635]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

基于PP-YOLOE的知识蒸馏方法和代码有吗？多谢专家

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/slim/distill 目前提供的蒸馏方案可以参考这里，还没有在ppyoloe上实验验证过
