### ISSUE TITLE
在PP-Picodet的检测头中，为什么没有前景和背景信息？如下图所示

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#6636]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在PP-Picodet的检测头中，为什么没有前景和背景信息？如下图所示
![image](https://user-images.githubusercontent.com/78945582/184272447-d60287a2-b389-4f37-b9f2-cb2a88f5675f.png)

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/modeling/heads/pico_head.py#L637 可以参考这部分代码，在assign会得到正负样本然后分别计算loss
