### ISSUE TITLE
 .\main --model_dir=model --image_file --camera_id 0

### ISSUE THREAD

**Issue by QL-AR** [PaddlePaddle/PaddleDetection#6639]
报错[ WARN:0@2.101] global c:\build\master_winpack-build-win64-vc15\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('--camera_id'): can't open/read file: check file path/integrity是怎么回事？

**Comment by jerrywgz** [comment]
报错原因是opencv没有读取到camera_id=0的输入，可以先用python opencv检查能否正确读取
