### ISSUE TITLE
背景类的索引？

### ISSUE THREAD

**Issue by monsterlyg** [PaddlePaddle/PaddleDetection#6640]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在Faster rcnn里面，背景类上放在最后一个filter上，还是第0个filter，代码看了好久找不到

**Comment by jerrywgz** [comment]
背景类在最后一维上
