### ISSUE TITLE
metrics打印结果有误

### ISSUE THREAD

**Issue by monsterlyg** [PaddlePaddle/PaddleDetection#6641]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

验证类别只有一个类，保存的json文件category_id全是2，nonMotor，
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/40205682/184407736-0cedfbf8-86c5-40a4-89d6-a535d3936f9a.png">
但是指标在freighter上；
<img width="426" alt="image" src="https://user-images.githubusercontent.com/40205682/184407493-ad792666-c681-4bd5-b370-5cf8960c9af7.png">

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by monsterlyg** [comment]
使用的训练模型上faster rcnn，COCO数据格式

**Comment by jerrywgz** [comment]
是否有正确修改num_classes 配置，这个配置表示前景的类别个数
