### ISSUE TITLE
PP-Tracking预测报错AttributeError: 'OCSORTTracker' object has no attribute 'input_size'

### ISSUE THREAD

**Issue by liuyang77886** [PaddlePaddle/PaddleDetection#6644]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

用导出的PPYOLOe行人检测模型和PPLCNet ReID模型
python deploy/pptracking/python/mot_sde_infer.py --model_dir=output_inference/ppyoloe_crn_l_36e_640x640_mot17half/ --reid_model_dir=output_inference/deepsort_pplcnet/ --tracker_config=deploy/pptracking/python/tracker_config.yml --video_file=est_demo.mp4 --device=GPU --threshold=0.5 --save_mot_txts --save_images

Traceback (most recent call last):
  File "mot_sde_infer.py", line 848, in <module>
    main()
  File "mot_sde_infer.py", line 813, in main
    detector.predict_video(FLAGS.video_file, FLAGS.camera_id)
  File "mot_sde_infer.py", line 606, in predict_video
    [frame], visual=False, seq_name=seq_name)
  File "mot_sde_infer.py", line 488, in predict_image
    det_result = self.reidprocess(det_result)
  File "mot_sde_infer.py", line 257, in reidprocess
    w, h = self.tracker.input_size
AttributeError: 'OCSORTTracker' object has no attribute 'input_size'

### 复现环境 Environment

win10，python3.7，cuda10.1，PaddleDetection2.4

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
OCSORT 不支持接reid模型。OCSORT和Bytetrack 都不需要接reid模型，接了精度未必提升或提升极小，而速度会变很慢。

**Comment by antekca** [comment]
reid模型需要修改tracker_config.yml，在第一行Type 应该设为DeepSORTTracker，默认是OCSORTTracker

**Comment by nemonameless** [comment]
[DeepSORT模型导出和预测](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/pptracking/python#2-deepsort%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E5%92%8C%E9%A2%84%E6%B5%8B) 注意里有写
