### ISSUE TITLE
能否提供一下官方PPYOLOE在COCO数据集上的训练日志？

### ISSUE THREAD

**Issue by Nioolek** [PaddlePaddle/PaddleDetection#6646]
### 问题描述 Please describe your issue

能否提供一下官方PPYOLOE在COCO数据集上的训练日志？最近在基于COCO训练时发现loss cls突然增加的问题，想和官方训练日志进行比对发现问题，如果能提供最好能包含s模型的训练日志。

**Comment by nemonameless** [comment]
[ppyoloe_s_300e_coco_42.7.log](https://github.com/PaddlePaddle/PaddleDetection/files/9335964/ppyoloe_s_300e_coco_42.7.log)
42.7是以前的nms参数，现在代码里的nms参数就是43.0。

**Comment by Nioolek** [comment]
> [ppyoloe_s_300e_coco_42.7.log](https://github.com/PaddlePaddle/PaddleDetection/files/9335964/ppyoloe_s_300e_coco_42.7.log) 42.7是以前的nms参数，快速eval用的比真实值略低0.3左右，现在代码里的nms参数就是43.0。

收到，十分感谢

**Comment by XA-hyy** [comment]
> [ppyoloe_s_300e_coco_42.7.log](https://github.com/PaddlePaddle/PaddleDetection/files/9335964/ppyoloe_s_300e_coco_42.7.log) 42.7是以前的nms参数，现在代码里的nms参数就是43.0。

@nemonameless 你好，请问测试结果的43.0 相比42.7是修改了什么nms参数？
我目前用的参数为：nms_top_j=1000, keep_top_k=100, conf_thres=0.01, iou_thres=0.6，使用400epoch的官方模型，测不出43.4的mAP指标.

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/ppyoloe/_base_/ppyoloe_crn.yml#L41
