### ISSUE TITLE
最新的2.4的readme.md中，PP-Human的链接是无效的，点击显示page not found

### ISSUE THREAD

**Issue by WenzhiShao** [PaddlePaddle/PaddleDetection#6656]
### 文档链接&描述 Document Links & Description

如题

### 请提出你的建议 Please give your suggestion

只能官方人员矫正链接

**Comment by nemonameless** [comment]
PP-Human项目请使用develop分支，才是最新代码  https://github.com/PaddlePaddle/PaddleDetection/tree/develop
