### ISSUE TITLE
FatalError: `Erroneous arithmetic operation` is detected by the operating system.

### ISSUE THREAD

**Issue by gongchenting** [PaddlePaddle/PaddleDetection#6657]
### 问题描述 Please describe your issue

基于ppdet yolov3训练报错如下：

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&)
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 1ul, paddle::operators::SplitOpKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::SplitOpKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::SplitOpKernel<paddle::platform::CUDADeviceContext, long>, paddle::operators::SplitOpKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::SplitOpKernel<paddle::platform::CUDADeviceContext, bool>, paddle::operators::SplitOpKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::operators::SplitOpKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
5   paddle::operators::math::SplitFunctor<paddle::platform::CUDADeviceContext, float>::operator()(paddle::platform::CUDADeviceContext const&, paddle::framework::Tensor const&, std::vector<paddle::framework::Tensor const*, std::allocator<paddle::framework::Tensor const*> > const&, int, std::vector<paddle::framework::Tensor*, std::allocator<paddle::framework::Tensor*> >*)
6   paddle::framework::SignalHandle(char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Erroneous arithmetic operation` is detected by the operating system.
  [TimeInfo: *** Aborted at 1660599751 (unix time) try "date -d @1660599751" if you are using GNU date ***]
  [SignalInfo: *** SIGFPE (@0x7fd7f781054f) received by PID 73816 (TID 0x7fd83a7ee740) from PID 18446744073567012175 ***]

**Comment by ghostxsl** [comment]
建议换个环境试试，看起来是环境的问题
