### ISSUE TITLE
python tools/x2coco.py 报错

### ISSUE THREAD

**Issue by zhuoxun-xun** [PaddlePaddle/PaddleDetection#6659]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

你好，我不知道为什么voc转coco脚本会报错。它只报错在有些图片上但我检查了标注好像没有问题。

Traceback (most recent call last):
  File "tools/x2coco.py", line 542, in <module>
    main()
  File "tools/x2coco.py", line 431, in main
    voc_xmls_to_cocojson(
  File "tools/x2coco.py", line 269, in voc_xmls_to_cocojson
    ann = voc_get_coco_annotation(obj=obj, label2id=label2id)
  File "tools/x2coco.py", line 237, in voc_get_coco_annotation
    assert xmax > xmin and ymax > ymin, "Box size error."
AssertionError: Box size error.

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ghostxsl** [comment]
根据报错信息提示，box的坐标有错误 -> assert xmax > xmin and ymax > ymin, "Box size error."
建议检查一下标注

**Comment by ruijie0611** [comment]
数据集标注问题，一般是出现了点状标注。解决方法：用labelimg检查一下报错前后那张图片的标注，删掉脏数据
