### ISSUE TITLE
基于PaddleDetection的人员摔倒识别

### ISSUE THREAD

**Issue by Zzxxxyyy** [PaddlePaddle/PaddleDetection#6662]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

您好，我目前正在尝试做一个基于关键点检测摔倒的项目。
在使用picodet_s_192_pedestrian进行行人检测和用tinypose_128x96进行关键点检测之后，我使用“基于PaddleDetection的人员摔倒识别”提供的方案进行添加摔倒字幕添加后处理。
在正常执行完读取关键点结果后放入判断文件这个步骤之后，使用自己的文件执行videovis函数时会报错

fps: 25, frame_count: 284
---------------------------------------------------------------------------IndexError                                Traceback (most recent call last)/tmp/ipykernel_97/2477555930.py in <module>
     12 
     13 #4）根据检测的摔倒帧在视频显示
---> 14 videovis(videof, kpts_data, fallframes)
~/source.py in videovis(videof, posedata, fallframes)
    172         if not ret:
    173             break
--> 174         frameid, rects, kpts_all = posedata[index]
    175         if index in fallframes:
    176             fallmark = True
IndexError: list index out of range

按说已经正常的生成了判断文件，放入字幕的函数里面又不涉及数组创建函数，是不应该报数组下标错误的。所以想请教一下我还应该修改哪些参数。
附上folk链接 

 基于关键点检测的摔倒识别_副本2：https://aistudio.baidu.com/aistudio/projectdetail/4435736?sUid=2498778&shared=1&ts=1660641679614

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
你可以把L714行的posedata[index]打印出来看看，看起来是posedata数据存储结构不对
