### ISSUE TITLE
但是为什么ppyolo 没有voc.yaml的格式配置，可以把coco改成voc吗

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleDetection#6665]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 为什么ppyolo 没有voc.yaml的格式配置，可以把coco改成voc吗？
2. ppyolo_mbv3_small_coco   与 yolov3_mobilenet_v1_ssld_270e_voc.yml  哪个模型更快，更小？
![微信图片_20220817091051](https://user-images.githubusercontent.com/6648329/185013522-d86b8151-da37-4885-bf92-fdf53b915481.png)

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
1. 可以参考ppyolo_r50vd_dcn_voc.yml把相关的模型改成voc数据集
2. 可以直观的根据保存的模型参数的大小比较模型的大小，这里是ppyolo_mbv3_small更小一些，速度没有做过对比，你可以在自己的硬件上测试下
3. 建议类似的问题以后先自己想办法解决下

**Comment by gg22mm** [comment]
好的，谢谢！~~。 

第一个问题我参考一下。
第二个问题看来只能一个一个的试了，我以为有对比图。    我现在用：  yolov3_mobilenet_v1_ssld_270e_voc.yml  这个带蒸馏的，有压缩的，应该也会小一些，在试，谢谢了~
