### ISSUE TITLE
需要一个op能够计算points和polygons的位置关系

### ISSUE THREAD

**Issue by YellowLight021** [PaddlePaddle/PaddleDetection#6667]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标：要求最终得到points是否在polygongs的矩阵表示，论文Oriented RepPoints for Aerial Object Detection。 2. 在进行spatial loss计算的时候，论文要求算出预测点中不在对应groundtruthbox中的点，然后拿这些点与loss中心算l1损失; 3. 用CUDA实现点在多边形内外的判断，采用的是射线法判定交点个数。参考代码https://github.com/LiWentomng/OrientedRepPoints/tree/main/mmdet/ops/point_justify

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
请问这个功能是哪里用到的，请详细说明一下应用场景和重要性
