### ISSUE TITLE
deploy/python/infer.py 出现错误

### ISSUE THREAD

**Issue by lling-2021** [PaddlePaddle/PaddleDetection#6672]
### 问题描述 Please describe your issue

 python tools/export_model.py -c configs/solov2/solov2_r50_fpn_3x_coco.yml -o weights=output/solov2_r50_fpn_3x_coco/best_model.pdparams
用
 python deploy/python/infer.py --model_dir=output_inference/solov2_r50_fpn_3x_coco/ --image_file=../../datas/images/20.jpg出现如下错误，
环境是paddledetection2.2,
Package            Version
------------------ -------------
astor              0.8.1
Babel              2.10.3
bce-python-sdk     0.8.74
certifi            2022.6.15
charset-normalizer 2.1.0
click              8.1.3
cycler             0.11.0
Cython             0.29.32
cython-bbox        0.1.3
decorator          5.1.1
et-xmlfile         1.1.0
Flask              2.2.2
Flask-Babel        2.0.0
fonttools          4.34.4
future             0.18.2
idna               3.3
importlib-metadata 4.12.0
itsdangerous       2.1.2
Jinja2             3.1.2
joblib             1.1.0
kiwisolver         1.4.4
lap                0.4.0
MarkupSafe         2.1.1
matplotlib         3.5.3
motmetrics         1.2.5
numpy              1.23.1
opencv-python      4.6.0.66
openpyxl           3.0.10
opt-einsum         3.3.0
packaging          21.3
paddle-bfloat      0.1.7
paddledet          2.2.0
paddlepaddle-gpu   2.3.1.post116
pandas             1.4.3
Pillow             9.2.0
pip                22.1.2
protobuf           3.20.0
pycocotools        2.0.4
pycryptodome       3.15.0
pyparsing          3.0.9
python-dateutil    2.8.2
pytz               2022.1
PyYAML             6.0
requests           2.28.1
scikit-learn       1.1.2
scipy              1.9.0
setuptools         61.2.0
Shapely            1.8.2
six                1.16.0
sklearn            0.0
terminaltables     3.1.10
threadpoolctl      3.1.0
tqdm               4.64.0
typeguard          2.13.3
urllib3            1.26.11
visualdl           2.3.0
Werkzeug           2.2.2
wheel              0.37.1
xmltodict          0.13.0
zipp               3.8.1

-----------  Model Configuration -----------
Model Arch: SOLOv2
Transform Order:
--transform op: NormalizeImage
--transform op: Resize
--transform op: Permute
--transform op: PadStride
--------------------------------------------
Traceback (most recent call last):
  File "/home/88/project/ASR/test/2.2/PaddleDetection/deploy/python/infer.py", line 667, in <module>
    main()
  File "/home/88/project/ASR/test/2.2/PaddleDetection/deploy/python/infer.py", line 630, in main
    predict_image(detector, img_list, FLAGS.batch_size)
  File "/home/88/project/ASR/test/2.2/PaddleDetection/deploy/python/infer.py", line 544, in predict_image
    results = detector.predict(batch_image_list, FLAGS.threshold)
  File "/home/88/project/ASR/test/2.2/PaddleDetection/deploy/python/infer.py", line 258, in predict
    self.predictor.run()
IndexError: In user code:
OutOfRangeError: The element of Index must be less than the size of input dim size of axis which is 3872, but received index element which is 3872 in the 14 index.
      [Hint: Expected p_index[i] < input_size, but received p_index[i]:3872 >= input_size:3872.] (at /paddle/paddle/phi/kernels/funcs/gather.h:83)
      [operator < gather > error]

**Comment by zoooo0820** [comment]
请更新下paddledetection代码呢，这个bug从2.3版本开始有做修复

**Comment by lling-2021** [comment]
> 这个bug从2.3版本开始有做修复

用paddledetection2.4训练的话都是0

**Comment by zoooo0820** [comment]
请问paddledetection2.2 版本能eval得到精度吗。这个问题看起来是没能正确学习到数据集内容
