### ISSUE TITLE
Mask_rcnn评估的时候显存一直再长直到内存溢出

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/PaddleDetection#6676]
### 问题描述 Please describe your issue

![image](https://user-images.githubusercontent.com/15188456/185074742-65f3abad-ba4f-4a63-963d-e6a86bcd6e12.png)
![image](https://user-images.githubusercontent.com/15188456/185074859-362b45bb-6750-4bef-acd6-f7d86d8e1b82.png)

**Comment by zhiboniu** [comment]
请问代码是否有什么修改？如果有需要确保加载的数据、图片等资源每轮都得到了释放。
如果没有改动麻烦提供一下使用的模型和命令

**Comment by yangy996** [comment]
> 请问代码是否有什么修改？如果有需要确保加载的数据、图片等资源每轮都得到了释放。 如果没有改动麻烦提供一下使用的模型和命令

没有修改代码，下图是单走评估命令，显存从0一直增长到最大7G，就不在增长，不知道评估为什么会占用这么大的显存
单只训练显存就需要5.6G的显存
![7`T122DB}AS8C8E18U%VI~5](https://user-images.githubusercontent.com/15188456/185270702-34e3623b-fa69-49df-a404-fdc28fae3407.png)

**Comment by weitianyu1** [comment]
我也遇到了这个问题，请问解决了么。只有重新加载模型显存才能被释放，要不然就会一直累加

**Comment by yangy996** [comment]
> 我也遇到了这个问题，请问解决了么。只有重新加载模型显存才能被释放，要不然就会一直累加

没有解决，可以手动修改评估走的显卡，训练走0,1,2,3号显卡，评估走4号显卡

**Comment by fanweiya** [comment]
我的也一样
