### ISSUE TITLE
Could you please provide the training logs of YOLOE-m models.

### ISSUE THREAD

**Issue by DaniellChiang** [PaddlePaddle/PaddleDetection#6677]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi, YOLOE is a great work. I want to reproduce the YOLOE in PyTorch, howerer, my training result is lower than your results. So I ant to find the training logs of YOLOE-m model to check the difference.
If possible, please send the training logs to 157995010@qq.com. Thanks very much.

**Comment by lyuwenyu** [comment]
ppyoloe_m_300e_486.log

**Comment by lyuwenyu** [comment]
快速的nms版本 [ppyoloe_m_300e_486.log](https://github.com/PaddlePaddle/PaddleDetection/files/9367294/ppyoloe_m_300e_486.log)

最终的指标49.0

**Comment by nemonameless** [comment]
之前是简单nms参数测的48.6，eval速度稍快点。按现在最新代码里的nms参数配置测就是49.0。
