### ISSUE TITLE
静态图多机多卡训练教程

### ISSUE THREAD

**Issue by wenli1216cy** [PaddlePaddle/PaddleDetection#6680]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

静态图多机多卡训练教程

**Comment by zoooo0820** [comment]
请参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/static/docs/tutorials/MULTI_MACHINE_TRAINING_cn.md

**Comment by wenli1216cy** [comment]
> 请参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/static/docs/tutorials/MULTI_MACHINE_TRAINING_cn.md
我用公司的两台服务器跑的，是内网，命令：
export PYTHONPATH=$PYTHONPATH:.
# 设置GPU卡号信息
export CUDA_VISIBLE_DEVICES=0,7
# 启动训练
node_ip=`hostname -i`
python -m paddle.distributed.launch  \
     --cluster_node_ips "192.168.0.87, 192.168.0.88" \
     --node_ip ${node_ip} \
     ./tools/train_multi_machine.py \
     -c ./configs/test/test.yml \
     --vdl_log_dir=vdl_dir/scalar_test \
    --use_vdl=True

出错1：
提示没有 --cluster_node_ips
错误2：
![360截图17290507616641](https://user-images.githubusercontent.com/34612860/185308503-47bd0ab5-a533-4bff-abd9-5fb8d5ded307.png)

**Comment by zoooo0820** [comment]
由于静态图模型的版本已经比较老了（对应1.x的paddle)。随着paddle主框架更换为动态图以后。如果现在使用的是2.x的paddle，相比文档中api发生了一些变化。辛苦对照这两个链接 [分布式训练常见问题](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/distributed_cn.html#wenti-2-0fenbushixunliandeqidongminglingyoushenmebianhua) 以及 [paddle.distributed.launch api文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/launch_cn.html)，调整上述命令中的参数，其中api文档中有较详细的启动示例

**Comment by wenli1216cy** [comment]
> 由于静态图模型的版本已经比较老了（对应1.x的paddle)。随着paddle主框架更换为动态图以后。如果现在使用的是2.x的paddle，相比文档中api发生了一些变化。辛苦对照这两个链接 [分布式训练常见问题](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/distributed_cn.html#wenti-2-0fenbushixunliandeqidongminglingyoushenmebianhua) 以及 [paddle.distributed.launch api文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/launch_cn.html)，调整上述命令中的参数，其中api文档中有较详细的启动示例

**Comment by wenli1216cy** [comment]
> > 由于静态图模型的版本已经比较老了（对应1.x的paddle)。随着paddle主框架更换为动态图以后。如果现在使用的是2.x的paddle，相比文档中api发生了一些变化。辛苦对照这两个链接 [分布式训练常见问题](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/distributed_cn.html#wenti-2-0fenbushixunliandeqidongminglingyoushenmebianhua) 以及 [paddle.distributed.launch api文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/launch_cn.html)，调整上述命令中的参数，其中api文档中有较详细的启动示例

#命令：
python -m paddle.distributed.launch \
    --gpus 1,2 \
    --ips 192.168.0.87,192.168.0.88 \
    --servers="192.168.0.87:36301,192.168.0.88:36301" \
    --server_num 2 \
    --worker_num 2 \
    ./tools/train_multi_machine.py \
    -c ./configs/test/test.yml \
    --vdl_log_dir=vdl_dir/scalar_test \
    --use_vdl=True
#错误
![Uploading 360截图17290508166851.png…]()

**Comment by wenli1216cy** [comment]
> > 由于静态图模型的版本已经比较老了（对应1.x的paddle)。随着paddle主框架更换为动态图以后。如果现在使用的是2.x的paddle，相比文档中api发生了一些变化。辛苦对照这两个链接 [分布式训练常见问题](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/distributed_cn.html#wenti-2-0fenbushixunliandeqidongminglingyoushenmebianhua) 以及 [paddle.distributed.launch api文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/launch_cn.html)，调整上述命令中的参数，其中api文档中有较详细的启动示例

我对照文档调整了参数，我是在2.4的静态图版本上进行测试的
命令：
python -m paddle.distributed.launch \
    --gpus 8,9 \
    --ips 192.168.0.87,192.168.0.88 \
    --servers="192.168.0.87:36301,192.168.0.88:36301" \
    --server_num 2 \
    --worker_num 2 \
    ./tools/train_multi_machine.py \
    -c ./configs/test/test.yml \
    --vdl_log_dir=vdl_dir/scalar_test \
    --use_vdl=True
错误：
![360截图17290508166851](https://user-images.githubusercontent.com/34612860/185364897-4c6c722f-3a7a-400c-9aad-5e6e338c3497.png)

**Comment by zoooo0820** [comment]
看起来问题主要是分布式启动，辛苦在 https://github.com/PaddlePaddle/Paddle/issues 提一个issue呢

**Comment by kuizhiqing** [comment]
请尝试使用以下命令启动
```
python -m paddle.distributed.launch
--devices=8,9
--host=192.168.0.87
--servers="192.168.0.87:36301,192.168.0.88:36301"
--servers="192.168.0.87:36302,192.168.0.88:36302"
./tools/train_multi_machine.py
-c ./configs/test/test.yml
--vdl_log_dir=vdl_dir/scalar_test
--use_vdl=True
```
说明，看报错是你的环境中自动识别 ip 错误，可通过手动 --host 指定，注意两台机器需要分别制定。
