### ISSUE TITLE
小白提问，教程里都是notebook的代码，有pycharm直接用的教程吗

### ISSUE THREAD

**Issue by liuyifan6600** [PaddlePaddle/PaddleDetection#6681]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

RT

**Comment by zoooo0820** [comment]
教程里的python代码都是可执行的，也可以在Pycharm环境里按步骤使用吧。另外也可以尝试在Pycharm中配置notebook（似乎需要专业版才可以）
