### ISSUE TITLE
C++编译失败，编译到100%然后报错

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleDetection#6682]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

[100%] Linking CXX executable main
/usr/bin/ld: warning: libonnxruntime.so.1.10.0, needed by /home/alex/Downloads/paddle_inference/paddle/lib/libpaddle_inference.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libpaddle2onnx.so, needed by /home/alex/Downloads/paddle_inference/paddle/lib/libpaddle_inference.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libavcodec-ffmpeg.so.56, needed by ../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libavformat-ffmpeg.so.56, needed by ../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libavutil-ffmpeg.so.54, needed by ../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libswscale-ffmpeg.so.3, needed by ../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16, not found (try using -rpath or -rpath-link)
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avformat_close_input@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘sws_scale@LIBSWSCALE_FFMPEG_3’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_guess_codec@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_guess_format@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_guess_sample_aspect_ratio@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avcodec_get_context_defaults3@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avcodec_flush_buffers@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_codec_get_tag@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avformat_get_mov_video_tags@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avformat_open_input@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avformat_alloc_context@LIBAVFORMAT_FFMPEG_56’未定义的引用
/home/alex/Downloads/paddle_inference/paddle/lib/libpaddle_inference.so：对‘OrtGetApiBase@VERS_1.10.0’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avcodec_decode_video2@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_bitstream_filter_close@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_image_fill_arrays@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_find_input_format@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_rescale_q@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avcodec_find_decoder_by_name@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_frame_get_buffer@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘sws_getCachedContext@LIBSWSCALE_FFMPEG_3’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_bitstream_filter_init@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘sws_getContext@LIBSWSCALE_FFMPEG_3’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avio_open@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avformat_get_riff_video_tags@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_bitstream_filter_filter@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_freep@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_write_frame@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_mallocz@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avio_close@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_image_get_buffer_size@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_write_trailer@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_dict_parse_string@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avcodec_open2@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘sws_freeContext@LIBSWSCALE_FFMPEG_3’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avcodec_find_decoder@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avformat_new_stream@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avformat_find_stream_info@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avcodec_get_name@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_lockmgr_register@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_dict_free@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avcodec_encode_video2@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avcodec_pix_fmt_to_codec_tag@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_frame_alloc@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_free@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_read_frame@LIBAVFORMAT_FFMPEG_56’未定义的引用
/home/alex/Downloads/paddle_inference/paddle/lib/libpaddle_inference.so：对‘paddle2onnx::Export(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool, int, bool, bool, bool, bool, bool)’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_dict_get@LIBAVUTIL_FFMPEG_54’未定义的引用
/home/alex/Downloads/paddle_inference/paddle/lib/libpaddle_inference.so：对‘paddle2onnx::IsExportable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int, bool, bool, bool, bool, bool)’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_seek_frame@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_frame_free@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avformat_write_header@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avformat_free_context@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_frame_unref@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_codec_get_id@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_log_set_callback@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_sub_q@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avformat_network_init@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_opt_set@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_packet_unref@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avcodec_find_encoder@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_init_packet@LIBAVCODEC_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_log_set_level@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_dict_set@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_malloc@LIBAVUTIL_FFMPEG_54’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘av_register_all@LIBAVFORMAT_FFMPEG_56’未定义的引用
../deps/opencv-3.4.16_gcc8.2_ffmpeg/lib/libopencv_videoio.so.3.4.16：对‘avcodec_close@LIBAVCODEC_FFMPEG_56’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:168: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:108: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
make finished!

### 复现环境 Environment

CUDA-10.2
CUDNN-8.1.1
gcc-8.4.0
PaddleDetction-2.4.0

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zoooo0820** [comment]
这个错误是系统中的ffmpeg与默认提供的opencv的包依赖的版本有差异导致的。需要升级ffmpeg版本或者重新编译带ffmpeg的opencv（建议重新编包）

**Comment by ainndejj11** [comment]
请问有重新编译opencv的教程么，说明文档有嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月18日(星期四) 下午2:16
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] C++编译失败，编译到100%然后报错 (Issue #6682)





 
这个错误是系统中的ffmpeg与默认提供的opencv的包依赖的版本有差异导致的。需要升级ffmpeg版本或者重新编译带ffmpeg的opencv（建议重新编包）

**Comment by Jiangyangya** [comment]
> 系统中的ffmpeg与默认提供的opencv

我也用的是默认提供的opencv报的这个错，不太理解系统里的ffmpeg不也是这个默认opencv自带的吗？这样也会有冲突吗

**Comment by Jiangyangya** [comment]
> > 系统中的ffmpeg与默认提供的opencv
> 
> 我也用的是默认提供的opencv报的这个错，不太理解系统里的ffmpeg不也是这个默认opencv自带的吗？这样也会有冲突吗

之后我重新编译了opencv3.4.16本版的opencv，没有ffmpeg的问题，但是仍然存在未定义的utf8proc这个库的问题，是因为这个库是c语言库导致编译不兼容问题么？一直没法解决这个问题，求好心人帮忙= =
