### ISSUE TITLE
摔倒推理有问题

### ISSUE THREAD

**Issue by sxfmusic** [PaddlePaddle/PaddleDetection#6688]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

使用版本为develop，运行以下代码
python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_pphuman.yml \
                                                   --video_file=test_video.mp4 \
                                                   --device=gpu \
                                                   --model_dir kpt=./dark_hrnet_w32_256x192 action=./STGCN

提出参数有问题：pipeline.py: error: unrecognized arguments: action=./STGCN

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zoooo0820** [comment]
感谢反馈
由于我们在最近的版本中做了较多的功能新增和代码结构改动，文档描述上可能存在遗漏，我们将再排查并修复文档中的问题。

当前命令行覆盖的方式统一更改为使用 `-o`，实现对config文件中对应字段的覆盖
```
python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_pphuman.yml
--video_file=test_video.mp4 \
--device=gpu \
-o KPT.model_dir=./dark_hrnet_w32_256x192 SKELETON_ACTION.model_dir=./STGCN
```
