### ISSUE TITLE
PaddleDetection新版本问题

### ISSUE THREAD

**Issue by fan-min-97** [PaddlePaddle/PaddleDetection#6692]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我是按照aistudio上的【PaddleDetection2.0专项】新版本快速体验这个项目一步一步执行的，但是在执行
!python ppdet/modeling/tests/test_architectures.py
这行代码时，报错，说很多模块没有注册，错误部分如下图：
![image](https://user-images.githubusercontent.com/71055342/185527561-cb55b411-822f-45e5-ac88-0e4c413dcd87.png)
![image](https://user-images.githubusercontent.com/71055342/185527639-2cd50532-4784-488f-b5f7-07ae5227756e.png)

，请问我改如何解决？

**Comment by nemonameless** [comment]
重新拉下最新代码
git clone https://github.com/PaddlePaddle/PaddleDetection.git -b develop
