### ISSUE TITLE
ppyoloe 多卡训练报错 nan

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleDetection#6706]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![472c9e8fc7429a178f382de91c469e1](https://user-images.githubusercontent.com/77281977/185738450-e886d088-fcbe-4ecb-916a-9441705754e1.png)
![6795b169612a4d95aa3f6896569a0b6](https://user-images.githubusercontent.com/77281977/185738454-6ca7a7be-162a-4283-ad6b-df9c7a9ee2b7.png)

训练过程中应该是验证的时候 nan  报错 
这是什么原因

**Comment by ghostxsl** [comment]
调小学习率试一下
