### ISSUE TITLE
yolov7训练报错

### ISSUE THREAD

**Issue by NwTbbetter** [PaddlePaddle/PaddleDetection#6707]
### 麻烦问一下这个报错怎么解决，这个数据集在yolov5可以正常使用

![1661004008021](https://user-images.githubusercontent.com/99952437/185750789-a85be497-d35b-4717-ab90-b476ab013242.jpg)

**Comment by nemonameless** [comment]
请按模板提问说明paddle版本环境谢谢。也可去https://github.com/nemonameless/PaddleDetection_YOLOSeries 提问。
PaddleDetection_YOLOSeries 推荐使用paddle2.3.0及以上版本。

**Comment by NwTbbetter** [comment]
paddle的版本是2.2.2，CUDA10.1，python 3.7，单卡训练，是v7tiny版本，其他的配置文件都没改

**Comment by nemonameless** [comment]
> paddle的版本是2.2.2，CUDA10.1，python 3.7，单卡训练，是v7tiny版本，其他的配置文件都没改

YOLOSeries 推荐使用paddle2.3.0及以上版本

**Comment by panp4n** [comment]
我也是同样的问题，paddle版本是2.2.2，CUDA11.2，python3.8，单卡训练，YOLOv7_x版本，更新paddle到2.3.2版本之后，报CUDA（719）错误。
![image](https://user-images.githubusercontent.com/40445051/188832707-dad44e60-9ed2-420a-a6e6-481908412c28.png)
