### ISSUE TITLE
 在使用yolov3_mobilenet_v1进行预测命令时提示UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)应该怎么解决

### ISSUE THREAD

**Issue by P3210836357** [PaddlePaddle/PaddleDetection#671]

**Comment by qingqing01** [comment]
@P3210836357 能贴下预测命令吗？

**Comment by heavengate** [comment]
您好，看报错信息像是修改了python脚本或者配置文件，添加了中文的字符或者中文全角的空格之类，`git status` `git diff`看下文件修改情况呢~

**Comment by P3210836357** [comment]
> @ P3210836357能贴下预测命令吗？

python -u tools/infer.py -c configs/yolov3_mobilenet_v1_fruit.yml -o  weights=E:/Google/PaddleDetection-release-0.2/output/yolov3_mobilenet_v1_fruit/model_final --infer_img=demo/20200512132409.jpg --output_dir=infer_output

**Comment by P3210836357** [comment]
> git diff

我数据集中标注目标是用的中文 所以我就把ppdet/data/source/voc.py里面的labels_map换成了中文  有关系吗

**Comment by P3210836357** [comment]
> 您好，看报错信息像是修改了python脚本或者配置文件，添加了中文的字符或者中文全角的空格之类，`git status` `git diff`看下文件修改情况呢~

我数据集中标注目标是用的中文 所以我就把ppdet/data/source/voc.py里面的labels_map换成了中文 有关系吗

**Comment by qingqing01** [comment]
@P3210836357  目前不支持中文标注。

**Comment by P3210836357** [comment]
> @P3210836357 目前不支持中文标注，建议换成英文。

模型map没上去的时候预测还可以没有错误  但是map上去了预测就出问题了

**Comment by P3210836357** [comment]
> @P3210836357 目前不支持中文标注，建议换成英文。

没有什么其他的办法了吗  只能更换为英文吗

**Comment by qingqing01** [comment]
@P3210836357 估计得改下源码，让支持读取labels的时候支持utf8编码，可以试下。

**Comment by P3210836357** [comment]
> @P3210836357 估计得改下源码，读取labels的时候让支持utf8编码，可以试下。

好的  感谢

**Comment by heavengate** [comment]
建议使用英文的label，如果要用中文的话可以试下python3，或者在数据集相关文件里加上
```python
# -*- coding: utf-8 -*-
```

**Comment by P3210836357** [comment]
> 建议使用英文的label，如果要用中文的话可以试下python3，或者在数据集相关文件里加上
> 
> ```python
> # -*- coding: utf-8 -*-
> ```

好的  感谢
