### ISSUE TITLE
2.0-rc版本中solov2支持openvino推理吗

### ISSUE THREAD

**Issue by wxb961107** [PaddlePaddle/PaddleDetection#6720]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如题，想问题下，2.0-rc版本中solov2支持openvino推理吗。想用solov2的MobilenetV3版本

**Comment by wangxinxin08** [comment]
目前暂时不支持

**Comment by wxb961107** [comment]
好的
