### ISSUE TITLE
目标检测文档中的模型在COCO数据集上的精度是指什么？

### ISSUE THREAD

**Issue by thgpddl** [PaddlePaddle/PaddleDetection#6721]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/48787805/186060969-7618bfe3-6528-4cae-a5a3-06ae9e5ce4a3.png)
请问图中的精度是指什么？是如何计算的？（个人猜测这里的精度是否为mAP）

**Comment by lyuwenyu** [comment]
指的是mAP

**Comment by thgpddl** [comment]
谢谢
