### ISSUE TITLE
yolox的onnx部署推理

### ISSUE THREAD

**Issue by LLsmile** [PaddlePaddle/PaddleDetection#6726]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

能不能实现yolox的onnx推理？paddle的部署没有onnx方便

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
文档写了，[4.导出模型](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/yolox#4%E5%AF%BC%E5%87%BA%E6%A8%A1%E5%9E%8B)
```
# 导出推理模型
python tools/export_model.py -c configs/yolox/yolox_s_300e_coco.yml --output_dir=output_inference -o weights=https://paddledet.bj.bcebos.com/models/yolox_s_300e_coco.pdparams

# 安装paddle2onnx
pip install paddle2onnx

# 转换成onnx格式
paddle2onnx --model_dir output_inference/yolox_s_300e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file yolox_s_300e_coco.onnx
```

**Comment by LLsmile** [comment]
有没有onnx的推理代码？PaddleOCR里有转成的onnx推理，好像paddledetection就完全不支持onnx推理

**Comment by nemonameless** [comment]
参照这个 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/end2end_ppyoloe

**Comment by lyuwenyu** [comment]
参考这里 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/third_engine/demo_onnx_trt
