### ISSUE TITLE
会支持PP-LCNetv2吗？

### ISSUE THREAD

**Issue by ChungTak** [PaddlePaddle/PaddleDetection#6731]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

测试了一下PaddleCls的PP-LCNetv2~~效果很不错··。请问PaddleDetection有计划支持PP-LCNetv2吗？

**Comment by nemonameless** [comment]
会的排期中。
