### ISSUE TITLE
请问一下，Paddle版本的TTFNet中有用到PhotoMetricDistortion的数据增广操作吗？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleDetection#6732]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

尊敬的工程师，您好！
请问一下，Paddle版本的TTFNet中有用到“PhotoMetricDistortion”的数据增广操作吗？
我们看到论文版本[TTFNet](https://github.com/ZJULearning/ttfnet)是有用到这个增广操作的；

期待您的回复！

**Comment by nemonameless** [comment]
PaddleDetection里的TTFNet是训练1x的基础版本，对应在原作者modelzoo里是32.9这个(TTFNet-53 (1x) )，PaddleDetection复现的精度是33.5。
你可以使用同配置文件下的PAFNet，用到了RandomDistort、RandomExpand、RandomCrop，和PhotoMetricDistortion是差不多作用的，或者TTFNet直接使用pafnet_reader。见 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ttfnet/_base_/pafnet_reader.yml

**Comment by songyuc** [comment]
> PaddleDetection里的TTFNet是训练1x的基础版本，对应在原作者modelzoo里是32.9这个(TTFNet-53 (1x) )，PaddleDetection复现的精度是33.5。 你可以使用同配置文件下的PAFNet，用到了RandomDistort、RandomExpand、RandomCrop，和PhotoMetricDistortion是差不多作用的，或者TTFNet直接使用pafnet_reader。见 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ttfnet/_base_/pafnet_reader.yml

好的，谢谢你的解答！
