### ISSUE TITLE
支持将全部数据加载到内存以加速训练吗

### ISSUE THREAD

**Issue by lxgyChen** [PaddlePaddle/PaddleDetection#6734]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

请问：是否支持将全部数据加载到内存中以加速训练？类似yolov5中的--cache功能？之前训练5万张图片就要训练好几天，现在要训练30多万张，用yolov5将所有图片一次性加载到内存中可以显著加速训练

### 是否愿意提交PR Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
目前还不支持

**Comment by lxgyChen** [comment]
有计划支持吗，因为这会极大加快训练速度

**Comment by lyuwenyu** [comment]
你有兴趣贡献提PR嘛

**Comment by lxgyChen** [comment]
> 你有兴趣贡献提PR嘛

兴趣是有啊，但是不知道dataloader怎么改。。。

**Comment by linhandev** [comment]
有点好奇，30w张图都存在内存？这内存莫不是要上T了

**Comment by linhandev** [comment]
不知道把所有训练数据扔到 /dev/shm 里是不是就达到这个加载到内存训练的效果了，应该不需要改动代码

https://superuser.com/questions/45342/when-should-i-use-dev-shm-and-when-should-i-use-tmp
