### ISSUE TITLE
yolox训练问题

### ISSUE THREAD

**Issue by bixiaopeng0** [PaddlePaddle/PaddleDetection#6738]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

1、训练时显存利用率不高
在私有数据集上训练yolox_m 在四卡p40上，平均每张卡bs=4，利用率为70%，显卡利用率不高，而且每张卡上的显存波动比较大。
2、eval私有数据集时，显存利用率绝大时间为0%，评测指令为
`export CUDA_VISIBLE_DEVICES=0,1 #windows和Mac下不需要执行该命令
python tools/eval.py -c configs/yolox/yolox_m_300e_coco.yml -o weights=59.pdparams`

这俩个问题有什么好的解决办法吗？

**Comment by nemonameless** [comment]
yolox是多尺度训练，显存波动是正常的。
eval的时候建议单卡执行

**Comment by bixiaopeng0** [comment]
提高训练时显卡利用率有什么好的解决思路吗

**Comment by ijrys** [comment]
这个框架问题很多
我的显卡利用率基本0%，偶尔能有个比较高的数
它数据加载很慢，显卡全在等数据
我把worker_num调高后速度上来了，但是出现了Empty的bug
