### ISSUE TITLE
maxDets配置修改

### ISSUE THREAD

**Issue by bixiaopeng0** [PaddlePaddle/PaddleDetection#6745]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问eval的时候maxDets这个参数在哪里修改呀
<img width="775" alt="image" src="https://user-images.githubusercontent.com/31760851/186381094-37372255-dbc5-44f2-ba1c-51d812e5c0fb.png">

**Comment by nemonameless** [comment]
https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L461

你需要改你安装的pycocotools里的代码，先找到安装路径，然后改代码比如/usr/local/lib/python3.7/site-packages/pycocotools/cocoeval.py的对应行参数：https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L508
