### ISSUE TITLE
tinypose 新增关键点后eval评估异常！！！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleDetection#6750]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

1 请问下， 如果我的关键点标注coco json 有27个关键点，比之前原始的17个多了10个，json的格式跟原始coco 一样，就是增加了keypoints的数量 [     ... 27个三元组]  ，请问下我只要把yml文件里面的关键点数量改为27  然后 skeleton关系改为27个 关联关系就行了 对吗？ 
2   更改为31个点后，训练可以跑起来了，但是eval 评估有些问题 ，请您看下错误信息， 能指点下吗？ 多谢
![image](https://user-images.githubusercontent.com/8407513/186603236-93336e2f-9e74-4afd-957b-4fd05813f01a.png)

### 复现环境 Environment

![image](https://user-images.githubusercontent.com/8407513/186603400-053fd495-b1fd-4000-b6d0-e93fd12069a5.png)

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/keypoint

**Comment by zhiboniu** [comment]
可以参考这里的自定义关键点修改部分，你这里vars还是原理的17个没有修改

**Comment by Bradly-s** [comment]
> 

你好，我也遇到了相同的问题，请问如何解决的呢？请问vars这个参数是在哪个文件里修改呀？在https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/keypoint没有看到呢
