### ISSUE TITLE
训练卡住

### ISSUE THREAD

**Issue by qinlihaoWork** [PaddlePaddle/PaddleDetection#6756]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

适用picodet训练自己的数据集，与AI studio配置相同，但运行后窗口卡住不动，内存占用增加，GPU显存没变化。
use_gpu：true  batch_size:8
环境如图：paddle2.3.1 CUDA10.2 cuDNN7.6，与AI studio相同，显卡3060.
![image](https://user-images.githubusercontent.com/111327813/186634881-96bd7228-7f2f-48fc-a348-d8b5d23e29fd.png)
请问该如何解决？
将use_gpu改为false后，使用CPU训练正常。

**Comment by ghostxsl** [comment]
请问，使用的paddle和paddledetection版本是多少？

**Comment by qinlihaoWork** [comment]
> 请问，使用的paddle和paddledetection版本是多少？

Paddle版本是2.3.1  paddledetection的版本是release2.4

**Comment by ghostxsl** [comment]
我本地复现可以跑通，你再换个环境试试呢

**Comment by qinlihaoWork** [comment]
> 我本地复现可以跑通，你再换个环境试试呢

请问您使用的是release2.4版本么？我试一下paddle2.2行不行

**Comment by qinlihaoWork** [comment]
![image](https://user-images.githubusercontent.com/111327813/186877725-dcbf0a5a-7c85-4afe-86ba-85a23f55cb7f.png)
跑完隔一段时间显示这个错误，难道是把数据集都处理了一起放进显存？

**Comment by qinlihaoWork** [comment]
使用2.3.2，2.3.1都不能进行训练，更改为2.2.2可以训练
