### ISSUE TITLE
吸烟检测精度较低

### ISSUE THREAD

**Issue by jodie2235337** [PaddlePaddle/PaddleDetection#6758]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

测试环境：paddle detection 2.4
测试集：[Human detection and tracking using RGB-D camera]，服装店监控视频，行人就是店员和顾客
测试结果：吸烟检测精度较低。非吸烟动作误检为吸烟，视频中几乎80%的人都判定为吸烟，实际视频中没有人吸烟
参考文献：People detection and tracking using RGB-D cameras for mobile robots，2016

吸烟检测精度较低的问题会修复吗？大概什么时候？多谢解答

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
这个问题不容易避免，主要是2个原因：1）训练数据来源有限，数据量少。2）香烟目标太小，清晰特征本身不明显。
所以目前这个还是比较难解决的，我们更多是提供一个解决方案示例，如果希望精度比较高建议大家自己标注一批数据加入训练来提升。
