### ISSUE TITLE
mask_rcnn怎么跑不起来?? 试了很多次 一直卡在一个步骤

### ISSUE THREAD

**Issue by Stillremains** [PaddlePaddle/PaddleDetection#676]
![QQ图片20200514171003](https://user-images.githubusercontent.com/48147367/81915925-c73eb580-9605-11ea-8231-139cfe3dda0a.png)

**Comment by heavengate** [comment]
看下`top -c`和`nvidia-smi`呢~

**Comment by Stillremains** [comment]
![1](https://user-images.githubusercontent.com/48147367/81924051-26ee8e00-9611-11ea-88ad-b2a6879ca124.png)
nü'i
![2](https://user-images.githubusercontent.com/48147367/81924061-2a821500-9611-11ea-9760-e08f80fee336.png) GPU好像没利用起来 反正我十几天前跑Mask 也是这样 莫名其妙

**Comment by qingqing01** [comment]
@Stillremains  我fork https://aistudio.baidu.com/aistudio/projectdetail/473536 这个项目，使用其中的val数据做训练，在AIStudio上能跑通。

```
loading annotations into memory...
Done (t=0.65s)
creating index...
index created!
2020-05-14 18:30:49,147-INFO: 5000 samples in file dataset/coco/annotations/instances_val2017.json
2020-05-14 18:30:49,190-INFO: places would be ommited when DataLoader is not iterable
I0514 18:30:49.225615   272 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I0514 18:30:49.296576   272 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0514 18:30:49.560868   272 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0514 18:30:49.615567   272 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
2020-05-14 18:30:50,096-INFO: iter: 0, lr: 0.001000, 'loss_cls': '4.459077', 'loss_bbox': '0.027419', 'loss_rpn_cls': '0.699176', 'loss_rpn_bbox': '0.022433', 'loss_mask': '0.771959', 'loss': '5.980064', time: 0.000, eta: 0:00:06
2020-05-14 18:30:54,801-INFO: iter: 20, lr: 0.001180, 'loss_cls': '0.433990', 'loss_bbox': '0.053571', 'loss_rpn_cls': '0.476488', 'loss_rpn_bbox': '0.045735', 'loss_mask': '0.854847', 'loss': '2.162748', time: 0.269, eta: 13:25:50
2020-05-14 18:30:59,470-INFO: iter: 40, lr: 0.001360, 'loss_cls': '0.512560', 'loss_bbox': '0.060157', 'loss_rpn_cls': '0.269906', 'loss_rpn_bbox': '0.056992', 'loss_mask': '0.712379', 'loss': '1.692605', time: 0.233, eta: 11:39:43
```

**Comment by qingqing01** [comment]
@Stillremains 你除了换数据集外，还有其他操作吗？

**Comment by Stillremains** [comment]
> 看下`top -c`和`nvidia-smi`呢~



> @Stillremains 你除了换数据集外，还有其他操作吗？
改了下类别 学习率 nms 其他没动了

**Comment by qingqing01** [comment]
@Stillremains 是否先看下COCO能否跑起来？ 再一个一个变量加进来？

**Comment by Stillremains** [comment]
> @Stillremains 是否先看下COCO能否跑起来？ 再一个一个变量加进来？

我就是跑的coco

**Comment by Stillremains** [comment]
> @Stillremains 是否先看下COCO能否跑起来？ 再一个一个变量加进来？

换了mask_rcnn_r50_1x 只修改了类别 同样跑不起来

**Comment by qingqing01** [comment]
@Stillremains 默认的配置能跑起来吗？

**Comment by Stillremains** [comment]
> @Stillremains 默认的配置能跑起来吗？仅仅是只修改类别就跑不起来了？

默认同样卡在那步   不知道啥情况。。。。。faster rcnn 等其他网络全正常

**Comment by qingqing01** [comment]
@Stillremains 你是用的PaddleDetection版本和paddle版本是多少？

**Comment by Stillremains** [comment]
![3](https://user-images.githubusercontent.com/48147367/81925641-5d2d0d00-9613-11ea-8773-defda7bff1b9.png)
同样1.71 用的aistudio

**Comment by qingqing01** [comment]
@Stillremains 你在AIStudio上的项目是否公开？ 如果是提供一个，我们fork测试下。

**Comment by Stillremains** [comment]
> @Stillremains 你在AIStudio上的项目是否公开？ 如果是提供一个，我们fork测试看下问题。

啊哦 暂时还不能  下次我再私信你吧

**Comment by qingqing01** [comment]
@Stillremains 额，因为无法复现。 我在想，您是否再基于我上面fork的项目再重新试下？或者得通过某种方式，我在AIStudio上能复现排查。 然后export GLOG_vmodule=operator=4，是可以看下具体运行哪个操作卡住了，也可以观察下。

**Comment by zwf1234** [comment]
您好，请问您的问题最后解决了吗？我也遇到了这个问题，程序停在这里不动了

Done (t=0.95s)
creating index...
index created!
2020-07-26 17:27:08,185-INFO: places would be ommited when DataLoader is not iterable

**Comment by jinxuan777** [comment]
请问有结论了，同样遇到这个问题

**Comment by jinxuan777** [comment]
![Uploading image.png…]()
到这里就不动了

**Comment by jinxuan777** [comment]
![image](https://user-images.githubusercontent.com/23650957/101720153-d0322f80-3adf-11eb-9b94-889df25eaf8d.png)
CPU使用率：0%，GPU使用率：0%

**Comment by qingqing01** [comment]
@jinxuan777  请确保输入数据是足够的。这个issue较久了，您有问题的话，请开下新的issue吧，也请给出可复现的环境。 暂且关闭了此issue.
