### ISSUE TITLE
PP-PicoDet用GPU检测,有没什么影响

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#6761]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PP-PicoDet用GPU检测,有没什么影响

还是用CPU比较好？

速度 识别率有没什么影响

**Comment by zhiboniu** [comment]
精度没有影响，只是速度性价比不如cpu上
