### ISSUE TITLE
voc和coco格式是否

### ISSUE THREAD

**Issue by WKangC** [PaddlePaddle/PaddleDetection#6772]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PPYOLOE的配置后缀只有coco，是否代表只能用coco格式的数据集，VOC的可以吗
![11111111111](https://user-images.githubusercontent.com/86812421/187022875-513ef508-fd83-4650-96d6-1aa41e17bd72.jpg)
？

**Comment by zoooo0820** [comment]
这个后缀指的是使用coco数据进行训练的配置，使用的格式也是coco的。 如果使用voc数据格式，请参考https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/data/PrepareDetDataSet.md 准备voc数据或将自有数据集转化为voc格式
