### ISSUE TITLE
PaddleDetection教程最后一个阶段图片没有检测框

### ISSUE THREAD

**Issue by yjjdick** [PaddlePaddle/PaddleDetection#6774]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/8224370/187043475-c79cf386-e2ce-4030-a504-0809e16fa071.png)
![image](https://user-images.githubusercontent.com/8224370/187043498-7a6312e5-2fac-49a5-91c2-6476f3398006.png)
尝试过自己训练，训练好了用测试图集也meiyou没有显示框
命令：python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg
如何才能显示被检测图让它显示检测框？检测框的代码在哪里？

**Comment by yjjdick** [comment]
![image](https://user-images.githubusercontent.com/8224370/187054718-11e15a71-3d8b-40b1-9c34-14edf6956441.png)
而且自己训练的图集，用的是yolov3_mobilenet_v1_roadsign.yml，评估时一直是0，这个是代表精度是0吗，到底哪里出问题了？

**Comment by nemonameless** [comment]
win上gpu版本建议使用paddle2.2.2
