### ISSUE TITLE
训练最后一直是0.00%是没有训练好吗？

### ISSUE THREAD

**Issue by yjjdick** [PaddlePaddle/PaddleDetection#6775]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/8224370/187053767-333c05d8-1270-405a-9f5f-b4c37633e32e.png)
python tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml --eval -o use_gpu=true
根据官方教程训练，评估出来一直是0.00%，是没有训练好吗改怎么改动？

**Comment by jerrywgz** [comment]
从训练日志上看是出nan了，可以发下使用的配置文件吗，从log看应该是有过改动的

**Comment by yjjdick** [comment]
> 从训练日志上看是出nan了，可以发下使用的配置文件吗，从log看应该是有过改动的
因为显卡是RTX 3060 4G显存的，所以把batch_szie 从8 改成了4，其他没有改动
![image](https://user-images.githubusercontent.com/8224370/187146778-65748078-2071-415d-a50f-f400a6e2e08d.png)

**Comment by jerrywgz** [comment]
看起来模型保存的路径也修改过了，确定其他配置没有改了吗？
如果只是改了batch size，base_lr需要从 0.001改成0.0005

**Comment by yjjdick** [comment]
> 看起来模型保存的路径也修改过了，确定其他配置没有改了吗？ 如果只是改了batch size，base_lr需要从 0.001改成0.0005
![image](https://user-images.githubusercontent.com/8224370/187193783-54ab21f2-fe64-4aa6-8e28-acda2d62fc62.png)

因为我改了batch size所以我复制了一份reader改名为reader_test其他并没有改动，base_lr需要从 0.001改成0.0005，这个会影响训练精度？为什么我改Batch size这个也要动呢？

**Comment by yjjdick** [comment]
> base_lr

![image](https://user-images.githubusercontent.com/8224370/187194163-eca06f70-646d-4378-9c8b-fbbd939a3cf1.png)
是提高5倍0.0005？还是0.00005？

**Comment by yjjdick** [comment]
> 看起来模型保存的路径也修改过了，确定其他配置没有改了吗？ 如果只是改了batch size，base_lr需要从 0.001改成0.0005

![image](https://user-images.githubusercontent.com/8224370/187194521-4a65f770-09c1-4024-8347-e2d57b2f0afe.png)
我照你的改了base lr 成0.0005还是nan

**Comment by yjjdick** [comment]
> 看起来模型保存的路径也修改过了，确定其他配置没有改了吗？ 如果只是改了batch size，base_lr需要从 0.001改成0.0005
![image](https://user-images.githubusercontent.com/8224370/187196159-eebf242a-c795-4813-90d3-57667e3fe3ec.png)
上面的图是用CPU去训练的，明显CPU的是对的，这个框架GPU训练是有问题的，检查一下吧
![image](https://user-images.githubusercontent.com/8224370/187196281-8ab7f6a7-92a3-4694-9c74-f1ceeecf208e.png)
![image](https://user-images.githubusercontent.com/8224370/187196307-bf6c5e25-c714-46d4-9c27-d88c291557b1.png)
这个是我的测试的显卡型号和参数，RTX3050 4G显存
可以排除是我配置文件的问题了，因为如果是我配置文件的问题就不存在CPU行GPU不行的，应该都不可以才对

**Comment by yjjdick** [comment]
> 看起来模型保存的路径也修改过了，确定其他配置没有改了吗？ 如果只是改了batch size，base_lr需要从 0.001改成0.0005

现在的结论很明显了，你看我上面的测试图就能知道，CPU 训练和测试都是好的，同样的配置文件GPU都是不好的，这个是为什么？

**Comment by jerrywgz** [comment]
我们找一台windows环境训练确认下

**Comment by jerrywgz** [comment]
可以发下你安装的paddle whl包链接，还有本地的python，cuda，cudnn版本吗

**Comment by yjjdick** [comment]
> 可以发下你安装的paddle whl包链接，还有本地的python，cuda，cudnn版本吗
安装教程是参考的gitee上的
https://gitee.com/paddlepaddle/PaddleDetection/blob/release/2.4/docs/tutorials/INSTALL_cn.md
我的安装命令是参考：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html
python -m pip install paddlepaddle-gpu==2.3.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
windows系统 pip方式安装 CUDA10.2
conda的环境是python 3.7
![image](https://user-images.githubusercontent.com/8224370/187210073-68091e26-1520-46ea-977d-f3e136fe67e4.png)
安装PaddleDetection
git clone https://github.com/PaddlePaddle/PaddleDetection.git

# 安装其他依赖
cd PaddleDetection
pip install -r requirements.txt

# 编译安装paddledet
python setup.py install
都一切正常，最后快速体验那步用GPU就检测不出，GPU型号上面我发了

**Comment by yjjdick** [comment]
> 可以发下你安装的paddle whl包链接，还有本地的python，cuda，cudnn版本吗

安装教程是参考的gitee上的
https://gitee.com/paddlepaddle/PaddleDetection/blob/release/2.4/docs/tutorials/INSTALL_cn.md
我的安装命令是参考：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html
python -m pip install paddlepaddle-gpu==2.3.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
windows系统 pip方式安装 CUDA10.2
conda的环境是python 3.7
![image](https://user-images.githubusercontent.com/8224370/187210728-182ada20-2ba7-40ca-8945-5f9012ac699a.png)

image
安装PaddleDetection
git clone https://github.com/PaddlePaddle/PaddleDetection.git

安装其他依赖
cd PaddleDetection
pip install -r requirements.txt

编译安装paddledet
python setup.py install
都一切正常，最后快速体验那步用GPU就检测不出，GPU型号上面我发了

**Comment by jerrywgz** [comment]
我们这边测试windows环境上跑gpu是可以的，是用的环境可以参考：GPU 3080; paddle develop版本;CUDA11.0;CUDNN8.2;python3.8 
![f244b31dcd84d3b075c796cec0fd9c06](https://user-images.githubusercontent.com/22989727/187339969-f9f75375-19a3-4e4f-bd79-c267722bfbe1.png)

**Comment by yjjdick** [comment]
> 我们这边测试windows环境上跑gpu是可以的，是用的环境可以参考：GPU 3080; paddle develop版本;CUDA11.0;CUDNN8.2;python3.8 ![f244b31dcd84d3b075c796cec0fd9c06](https://user-images.githubusercontent.com/22989727/187339969-f9f75375-19a3-4e4f-bd79-c267722bfbe1.png)

 paddle develop 是哪个版本，能给个链接吗

**Comment by jerrywgz** [comment]
刚测试了下paddle2.3.2版本也是正常的，可以直接下载，测试使用的cuda11的环境，下载命令：python -m pip install paddlepaddle-gpu==2.3.2.post112 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html 其他版本可以参考https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

**Comment by yjjdick** [comment]
> 刚测试了下paddle2.3.2版本也是正常的，可以直接下载，测试使用的cuda11的环境，下载命令：python -m pip install paddlepaddle-gpu==2.3.2.post112 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html 其他版本可以参考https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

用你这个版本确实是可以的，我CUDA是10.2的应该有点问题，11确实没问题，能再请教一下base lr 吗，我现在在本地训练只能把batch size改成4，这样的话base lr 要改成0.0005？默认是0.0001，batch size默认是8，你意思是batch size每减少一倍base lr就要增长5倍？base lr这个参数代表的意思是？
如果我要修改batch size，那些参数需要调整呢，麻烦请教一下谢谢

**Comment by jerrywgz** [comment]
这里学习率应该和batch size成比例变化，如果总batch size减小一倍，学习率也需要减小一倍，前面的学习率打错了应该0.00005
