### ISSUE TITLE
快速开始按照教程中快速体验测试GPU模式无效

### ISSUE THREAD

**Issue by yjjdick** [PaddlePaddle/PaddleDetection#6790]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/8224370/187192643-7f6d3990-558e-4ed6-ad3e-7863d2e1ca14.png)
如果用GPU测试
# 用PP-YOLO算法在COCO数据集上预训练模型预测一张图片
python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg
图片是无检测框
但是只要把use_gpu = false 用cpu就好了，为什么？

**Comment by nemonameless** [comment]
win上gpu版本建议使用paddle2.2.2

**Comment by yjjdick** [comment]
> win上gpu版本建议使用paddle2.2.2

谢谢提醒，他们维护的工作人员好像再帮我看这个问题了，你也遇到了一样的问题吗？我用的好像是2.3还是2.4的版本，高版本windows gpu是有问题的对吧？我今天测试了一整天，CPU没问题，GPU训练和测试就是不好的

**Comment by nemonameless** [comment]
我之前paddle2.2.2在win上用过是ok。win平台开发中不常用难免有疏漏发现不及时。

**Comment by yjjdick** [comment]
> 我之前paddle2.2.2在win上用过是ok。win平台开发中不常用难免有疏漏发现不及时。

好的，我试试，感谢回答，这个问题从上周五一直困扰到我现在了

**Comment by Chengnotwang** [comment]
我也遇到了相同的问题，然后我安装了Paddle2.4.2-gpu版本，解决了问题
