### ISSUE TITLE
如何获取TP, FP, FN, TN数值

### ISSUE THREAD

**Issue by zoella25** [PaddlePaddle/PaddleDetection#6805]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，想请问该如何获取TP, FP, FN, TN这些内容吗？谢谢

**Comment by yghstill** [comment]
@zoella25 
- VOC数据集的话，可以在metric代码中打印具体的TP、FP值：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/metrics/map_utils.py#L254
- COCO API因为封装的原因，可以手动计算
