### ISSUE TITLE
why the topk is fixed in SimOTA?

### ISSUE THREAD

**Issue by lucasjinreal** [PaddlePaddle/PaddleDetection#6812]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

https://github.com/PaddlePaddle/PaddleDetection/blob/1b1f5909d013ffabb008eafa636a4d6cb689207d/ppdet/modeling/assigners/simota_assigner.py#L118

the candidate_topk is always 10 here...

**Comment by nemonameless** [comment]
Picodet has done experiments, which is 1.0 mAP higher than the original setting as Megvii/YOLOX. Later, ppdet-YOLOX also used this. Maybe it will be slightly higher and more obvious on the small models.
