### ISSUE TITLE
新需求：在一个paddledetection目录下，同时运行多个训练程序

### ISSUE THREAD

**Issue by Tongfengyu** [PaddlePaddle/PaddleDetection#6814]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标：; 
2. 需求场景：有时不需要多卡并行去跑一个训练程序，而是希望一张卡跑1个训练程序;
3. 功能描述：在一个paddledetection目录下，同时运行多个训练程序，我试了一下，好像打印的精度指标会混起来

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ziyaxuanyi** [comment]
为啥要在同一个目录呢，复制分开多个目录，每个目录运行想要运行的程序，不就好了

**Comment by Tongfengyu** [comment]
嗯,你说的对。我目前也是这样处理的。可能做对比实验（一些微小改动）需要，在复制个目录有点多余了。

**Comment by wangxinxin08** [comment]
一般训练的时候只要设置好log文件夹和保存模型的文件夹即可，如果使用`--eval`训练，可以设置output_eval文件夹，比如
``` bash
python -m paddle.distributed.launch --log_dir=/path/to/log --gpus 0,1,2,3 tools/train.py -c /path/to/config -o save_dir=/path/to/checkpoint output_eval=/path/to/eval 
```
