### ISSUE TITLE
deploy/python/infer.py的--batch_size参数不起作用

### ISSUE THREAD

**Issue by WooXinyi** [PaddlePaddle/PaddleDetection#6817]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

在使用deploy/python/infer.py对yolov3模型进行性能测试时，设置--batch_size大于1时推理速度没有明显变化。查看源码的时候，发现设置--batch_size只对预处理时间有影响，而模型实际推理时间只取决于文件里面的repeats参数。
那么，如果我需要测试多batch时的模型性能，应该怎么做？

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
`--batch_size`参数是起了作用了，至于模型推理时间没有变化，你可以自行分析一下

**Comment by WooXinyi** [comment]
> `--batch_size`参数是起了作用了，至于模型推理时间没有变化，你可以自行分析一下

谢谢回答。我发现infer_cfg.yml里有个参数use_dynamic_shape，默认为false，是否应该改为true才会使得多batch推理生效呢？

**Comment by wangxinxin08** [comment]
注意看上面的回答，batch_size已经生效了

**Comment by WooXinyi** [comment]
> 注意看上面的回答，batch_size已经生效了

好吧，请教一下哈，使用T4卡，在设置batch_size=4和batch_size=80时，最终QPS计算出来都在13左右，这个数据是正常的吗？

**Comment by wangxinxin08** [comment]
是使用deploy/python/infer.py并开启--run_benchmark=True测试模型的速度吗？

**Comment by WooXinyi** [comment]
设置的是--run_benchmark=False，这样才有QPS这个指标

**Comment by wangxinxin08** [comment]
> 设置的是--run_benchmark=False，这样才有QPS这个指标

测模型速度开启run_benchmark，QPS可以自己算

**Comment by WooXinyi** [comment]
> 

好吧，谢谢了
