### ISSUE TITLE
mot annotations

### ISSUE THREAD

**Issue by goldentimecoolk** [PaddlePaddle/PaddleDetection#6821]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

MOT部分你们在`https://dataset.bj.bcebos.com/mot`提供了转换后的MOT数据集，简化了我们的数据准备过程。然而，你们提供的数据集中未包含[`annotations/*.json`](https://github.com/PaddlePaddle/PaddleDetection/blob/release%2F2.4/configs/mot/bytetrack/_base_/mot17.yml#L8)，请问怎么得到这些json文件？

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
现在跟踪推荐使用bytetrack，就是当成检测任务来训，json文件标注就是coco格式，转coco格式的代码因用户数据集原本标注的形式而不同，需要自行写。
检测数据集准备，包括转COCO格式请参考： 
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/data/PrepareDetDataSet.md
MOT数据集准备请参考： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/data/PrepareMOTDataSet.md

**Comment by goldentimecoolk** [comment]
好的，已转。
有没有可能在`https://dataset.bj.bcebos.com/mot`提供转好的json文件？这样应该会更方便一些。

**Comment by nemonameless** [comment]
哪个数据集没提供json？每个数据集都是图片和json都一起打包传到云上的，你的意思是json单独放？

**Comment by UperFang** [comment]
我在https://dataset.bj.bcebos.com/mot下载的MOT17中没有找到对应的json文件, 解压的目录如下
MOT17
├── images
│   ├── half
│   ├── test
│   └── train
└── labels_with_ids
    └── train
同样其余的mot数据集也是

**Comment by nemonameless** [comment]
https://bj.bcebos.com/v1/paddledet/data/mot/MOT17.zip  这里下载的有。
转coco格式是基本功，总会有新的数据集要转。

**Comment by goldentimecoolk** [comment]
> https://bj.bcebos.com/v1/paddledet/data/mot/MOT17.zip 这里下载的有。 转coco格式是基本功，总会有新的数据集要转。

当时下载是没有的哈，上面也有人反馈了。
我们会转coco，并且已经自己转了，这里开个issue是反馈一下情况。既然你们提供了自己处理后的MOT数据集，那么将所有用到的文件提供完整不是更好吗？

**Comment by nemonameless** [comment]
#7002 更新旧版链接为新链接
