### ISSUE TITLE
我觉得产品做得很好，推理速度能再快就就完美了

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleDetection#6822]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我觉得产品做得很好，推理速度能再快就就完美了

我用模型：ppyolo_mbv3_small_voc_wll.yml 做识别

cpu_threads = 10
device = 'cpu'
enable_mkldnn=True
enable_auto_tune = False

推理速度都在： 1.2342767715454102 左右这样，能不能再快些， 如果能达到0.* 秒以下就完美了。

不知道有什么办法，用的模型应该是最小的了吧？

图片分类检测时间: 0.2739129066467285
图片分类清晰度: 0.24283409118652344
分割时间: 1.943784475326538
目标检测时间: 1.2342767715454102

总时间: 3.695807933807373
后面还会添加模型， 就越来越慢了

**Comment by wangxinxin08** [comment]
cpu可以试下picodet，gpu可以试下ppyoloe+ s模型

**Comment by gg22mm** [comment]
> cpu可以试下picodet，gpu可以试下ppyoloe+ s模型

非常感谢！~~： 回头我在试试，不完我用其它办法已经解决了：https://github.com/PaddlePaddle/PaddleSeg/issues/2501
