### ISSUE TITLE
关于PP-PicoDet的一个问题

### ISSUE THREAD

**Issue by wwdok** [PaddlePaddle/PaddleDetection#6824]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在picodet的[论文](https://arxiv.org/pdf/2111.00902.pdf)中，提到“Channel shuffle provides the information exchange of ShuffleNetV2 channels, but it causes the loss of fusion features.”
![image](https://user-images.githubusercontent.com/43233772/187662610-0537ee2f-e5e8-4d14-8921-97ddbde145a4.png)
我对这个“loss of fusion features”不是很理解，首先“fusion features”的定义是什么，然后怎么证明它loss了，有人能解释得更清楚一点吗

**Comment by wangxinxin08** [comment]
channel shuffle是为了解决不同channel之间没有交互而设计的，不过相比于用一个卷积直接去卷积，不同channel之间的交互还是相对较少的。直观上来看，交互的信息是少了，并没有直接证明这一点。一般是通过设计的模块的有效性来自圆其说
