### ISSUE TITLE
请问版面分析中picohead的ScaleReg相关代码在哪里

### ISSUE THREAD

**Issue by whalefa1I** [PaddlePaddle/PaddleDetection#6826]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在观察[模型](https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_cdla.pdparams) 结构的时候发现picohead中有一个
![image](https://user-images.githubusercontent.com/32239722/187681819-685e03b1-ee20-46a5-a29e-7bb3cb2b50a3.png)
head.p3_feat.scale_reg的操作，可能是计算bbox的回归值，但是根据yml查看到picohead中没有相关操作，请问在哪里可以看到呢

**Comment by whalefa1I** [comment]
同时在paddledetecion的代码中搜”ScaleReg“，只有[fcos_head](https://github.com/PaddlePaddle/PaddleDetection/blob/ede22043927a944bb4cbea0e9455dd9c91b295f0/ppdet/modeling/heads/fcos_head.py)、[gfl_head](https://github.com/PaddlePaddle/PaddleDetection/blob/ede22043927a944bb4cbea0e9455dd9c91b295f0/ppdet/modeling/heads/gfl_head.py)和[tood_head](https://github.com/PaddlePaddle/PaddleDetection/blob/ede22043927a944bb4cbea0e9455dd9c91b295f0/ppdet/modeling/heads/tood_head.py)有类似操作

**Comment by wangxinxin08** [comment]
看类的继承关系，scalereg基本都是同样的操作
