### ISSUE TITLE
测试MTMCT-demo中打开draw_center_traj无法绘制轨迹

### ISSUE THREAD

**Issue by ShaneCan** [PaddlePaddle/PaddleDetection#6827]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

**PP团队大神您好，我在测试官方MTMCT-demo中，打开draw_center_traj，但生成的视频中没有绘制轨迹：**

--model_dir=F:\PaddleDetection\output_inference\ppyolov2_r50vd_dcn_365e_aic21mtmct_vehicle
--reid_model_dir=F:\PaddleDetection\output_inference\deepsort_pplcnet_vehicle
--mtmct_dir=F:\PaddleDetection\output_inference\mtmct-demo
--mtmct_cfg=F:\PaddleDetection\deploy\pptracking\python\mtmct_cfg.yml
--tracker_config=F:\PaddleDetection\deploy\pptracking\python\tracker_config.yml
--device=GPU
--scaled=True
--save_mot_txts
--save_images
--draw_center_traj

这是我的运行形参，求解，谢谢！

**Comment by ShaneCan** [comment]
使用：
ffmpeg -y -i F:\PaddleDetection\output_inference\mtmct-demo\c003.mp4 -t 00:00:01 F:\PaddleDetection\output_inference\mtmct-demo/test_%3d.jpg
能够抽帧成功并保存

**Comment by ShaneCan** [comment]
[    def end(self, repeats=1, accumulative=True):](https://github.com/PaddlePaddle/PaddleDetection/blob/847c4c58ce98641b4533519e12a324b9866f76d4/deploy/pptracking/python/mot_utils.py#L203)

在改行我的time.time报错

**Comment by zhiboniu** [comment]
你好，MTMCT最后的demo主要展示跨镜融合后的id效果。跟踪轨迹是在每个视频跑完时生成的输出视频中显示的。可以找找那个视频看

**Comment by ShaneCan** [comment]
> 你好，MTMCT最后的demo主要展示跨镜融合后的id效果。跟踪轨迹是在每个视频跑完时生成的输出视频中显示的。可以找找那个视频看

您好，您是指PaddleDetection\deploy\pptracking\python\output\mtmct_vis下的c003_mtmct_vis.mp4和c004_mtmct_vis.mp4这两个文件吗？程序跑完只生成了这两个mp4，但是这两个视频内并没有显示轨迹

**Comment by ShaneCan** [comment]
此外我还有一个疑问就是MTMCT的输入只能是录制的视频吗，可否用两个摄像头进行实时的图像处理呢？

**Comment by Hyperjunct** [comment]
> > 你好，MTMCT最后的demo主要展示跨镜融合后的id效果。跟踪轨迹是在每个视频跑完时生成的输出视频中显示的。可以找找那个视频看
> 
> 您好，您是指PaddleDetection\deploy\pptracking\python\output\mtmct_vis下的c003_mtmct_vis.mp4和c004_mtmct_vis.mp4这两个文件吗？程序跑完只生成了这两个mp4，但是这两个视频内并没有显示轨迹

请问楼主现在找到带有轨迹的视频了吗

**Comment by ShaneCan** [comment]
> > > 你好，MTMCT最后的demo主要展示跨镜融合后的id效果。跟踪轨迹是在每个视频跑完时生成的输出视频中显示的。可以找找那个视频看
> > 
> > 
> > 您好，您是指PaddleDetection\deploy\pptracking\python\output\mtmct_vis下的c003_mtmct_vis.mp4和c004_mtmct_vis.mp4这两个文件吗？程序跑完只生成了这两个mp4，但是这两个视频内并没有显示轨迹
> 
> 请问楼主现在找到带有轨迹的视频了吗

没有，您有什么想法吗

**Comment by Hyperjunct** [comment]
> 此外我还有一个疑问就是MTMCT的输入只能是录制的视频吗，可否用两个摄像头进行实时的图像处理呢？

https://github.com/PaddlePaddle/PaddleDetection/issues/7245
百度的相关工作人员回复我表示目前的MTMCT算法仅支持离线的车辆跨境跟踪

**Comment by 217TYNB** [comment]
我目前想用mtmct实现行人的跨摄像头跟踪，并且生成一个路径图，能实现么
