### ISSUE TITLE
paddledetection是否支持单卡多进程推理？

### ISSUE THREAD

**Issue by WooXinyi** [PaddlePaddle/PaddleDetection#6830]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如题，手里只有一张卡，我想使用多进程并行推理，目前paddledetection是否支持？

**Comment by lyuwenyu** [comment]
不支持的

**Comment by WooXinyi** [comment]
> 不支持的

那岂不是一张卡只能跑一个程序了，这不是太浪费资源了嘛。
比如说我先启一个程序跑人脸识别，再启一个程序跑目标检测，这样都不行呀

**Comment by lyuwenyu** [comment]
两个程序可以占一个卡跑的， 如果是同一个模型也可以考虑组batch推理吧
