### ISSUE TITLE
PPOCRLabel四点标注的数据能用于s2anet网络训练吗

### ISSUE THREAD

**Issue by zhibin-hong** [PaddlePaddle/PaddleDetection#6837]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PPOCRLabel四点标注的数据能用于s2anet网络训练吗

**Comment by zhibin-hong** [comment]
因为看到rota航拍数据集的标注格式是说四个点是顺时针标注的

**Comment by wangxinxin08** [comment]
s2anet需要的是旋转的矩形框，你可以对这四个点求一个外接矩形框作为s2anet的标注
