### ISSUE TITLE
paddledetection推理报错

### ISSUE THREAD

**Issue by leechenggg** [PaddlePaddle/PaddleDetection#6842]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

用paddledetection预测图片时报错
链接：https://aistudio.baidu.com/aistudio/projectdetail/4483911

**Comment by nemonameless** [comment]
```
[09/02 14:56:12] ppdet.data.source.category WARNING: anno_file 'None' is None or not set or not exist, please recheck TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.
```
数据集路径怎么改的请说明。这个文件：configs/datasets/sniper_visdrone_detection.yml

**Comment by leechenggg** [comment]
> ```
> [09/02 14:56:12] ppdet.data.source.category WARNING: anno_file 'None' is None or not set or not exist, please recheck TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.
> ```
> 
> 数据集路径怎么改的请说明。这个文件：configs/datasets/sniper_visdrone_detection.yml

没明白您的意思，意思是您看不到数据集路径吗

**Comment by leechenggg** [comment]
configs/datasets/sniper_visdrone_detection.yml文件内容如下

metric: SNIPERCOCO
num_classes: 3

TrainDataset:
  !SniperCOCODataSet
    image_dir: /home/aistudio/MyDataset/dataset/train_data/JPEGImages
    anno_path: /home/aistudio/MyDataset/dataset/train_data/train.json
    dataset_dir: /home/aistudio/MyDataset/dataset/train_data
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']
    allow_empty: true
    is_trainset: true
    image_target_sizes: [1600, 1600]
    valid_box_ratio_ranges: [[0.02,0.233125], [-1, -1]]
    chip_target_size: 800
    chip_target_stride: 448
    use_neg_chip: false
    max_neg_num_per_im: 8


EvalDataset:
  !SniperCOCODataSet
    image_dir: /home/aistudio/MyDataset/dataset/train_data/JPEGImages
    anno_path: /home/aistudio/MyDataset/dataset/train_data/val.json
    dataset_dir: /home/aistudio/MyDataset/dataset/train_data
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']
    allow_empty: true
    is_trainset: false
    image_target_sizes: [1600, 1600]
    valid_box_ratio_ranges: [[0.02,0.233125], [-1, -1]]
    chip_target_size: 800
    chip_target_stride: 448
    max_per_img: -1
    nms_thresh: 0.5

TestDataset:
  !SniperCOCODataSet
    image_dir: /home/aistudio/MyDataset/dataset/test_data/test
    dataset_dir: /home/aistudio/MyDataset/dataset/test_data
    is_trainset: false
    image_target_sizes: [1600, 1600]
    valid_box_ratio_ranges: [[0.02,0.233125], [-1, -1]]
    chip_target_size: 800
    chip_target_stride: 448
    max_per_img: -1
    nms_thresh: 0.5

**Comment by ZhangLe-fighting** [comment]
TestDataset:
!SniperCOCODataSet
image_dir: /home/aistudio/MyDataset/dataset/test_data/test
dataset_dir: /home/aistudio/MyDataset/dataset/test_data
is_trainset: false
image_target_sizes: [1600, 1600]
valid_box_ratio_ranges: [[0.02,0.233125], [-1, -1]]
chip_target_size: 800
chip_target_stride: 448
max_per_img: -1
nms_thresh: 0.5

缺少anno_path ?
