### ISSUE TITLE
支持obj365训练测试

### ISSUE THREAD

**Issue by ZiQiangXie** [PaddlePaddle/PaddleDetection#6846]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

看到ppyoloeplus用了基于obj365的预训练模型，是否能支持直接训练obj365？

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
没有8卡32G以上不建议训，需要多机多卡才能训收敛。
