### ISSUE TITLE
找不到 ppyolo.yml

### ISSUE THREAD

**Issue by weiyaokun** [PaddlePaddle/PaddleDetection#6851]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

python tools/infer.py -c configs/ppyolo/ppyolo.yml -o use_gpu=true weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams --infer_img=demo/000000014439.jpg

测试时找不到ppyolo.yml文件

**Comment by ghostxsl** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/ppyolo 这个路径下没有你说的那个文件，是你自己写的嘛？
