### ISSUE TITLE
PPvehicle修改infer_cfg_ppvehicle中MOT model_dir后出现的问题

### ISSUE THREAD

**Issue by ShaneCan** [PaddlePaddle/PaddleDetection#6853]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我将MOT model改为了官方提供的YOLOX-l权重，结果视频检测结果中所有物体都检测为person，请问如何修改才能实现多类别识别呢？

**Comment by nemonameless** [comment]
官方提供的YOLOX-l权重是COCO 80类的，你确定要用这个模型权重吗？导出后的模型也是80类。
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/ppvehicle 这里也有更多车辆ppyoloe模型，单类多类都有。
就是换下导出后的权重的路径，但是注意检查下导出模型的infer_cfg,yml里类别是不是多类的。
跟踪器请选择BYTETracker，也就是deploy/pipeline/config/tracker_config.yml 里配置改成JDETracker。

**Comment by ShaneCan** [comment]
> 但是注意检查下导出模型的infer_cfg,yml

谢谢您，我使用了JDETracker后可以正常检测多目标，而OC SORT不可以，是因为OC SORT只支持检测单目标吗？

**Comment by nemonameless** [comment]
OC SORT tracker暂时只支持单类，大部分普通场景如运动较为线性规律的，OC SORT的MOTA不一定比bytetrack高。

**Comment by ShaneCan** [comment]
> OC SORT tracker暂时只支持单类，大部分普通场景如运动较为线性规律的，OC SORT的MOTA不一定比bytetrack高。

感谢解答！
