### ISSUE TITLE
训练deepsort有些困惑

### ISSUE THREAD

**Issue by hatecodes** [PaddlePaddle/PaddleDetection#6854]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，请问想要训练自己的车辆数据集实现deepsort跟踪，是否仅需要进行目标检测器的训练（比如自己训练一个YOLOX模型），然后直接用官方提供的deepsort_pplcnet_vehicle REID模型即可呢？支持使用YOLOX搭配deepsort嘛？ 感谢大神解答！

**Comment by nemonameless** [comment]
支持任意检测器适配deepsort，训检测 文档参照 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/mot/deepsort/detector

**Comment by hatecodes** [comment]
> 支持任意检测器适配deepsort，训检测 文档参照 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/mot/deepsort/detector

谢谢您的耐心回答，我还想麻烦请问下这个训练文档是训练deepsort中的REID模型吗？ 感谢！

**Comment by nemonameless** [comment]
意思是训deepsort中的检测器。configs/mot/deepsort/detector 是几个检测器示例，configs/mot/deepsort 里的yml是组装检测器+reid 为一个deepsort的配置示例，再仔细阅读下文档。
reid模型是不用自己训的。

**Comment by hatecodes** [comment]
> 意思是训deepsort中的检测器。configs/mot/deepsort/detector 是几个检测器示例，configs/mot/deepsort 里的yml是组装检测器+reid 为一个deepsort的配置示例，再仔细阅读下文档。 reid模型是不用自己训的。

明白了 ，谢谢，那deepsort文件夹下的JDE YOLOV3和普通的YOLOV3有什么区别呢？JDE作为一种tracker为什么会在deepsort文件夹下呢？如(PaddleDetection\configs\mot\deepsort\detector\jde_yolov3_darknet53_30e_1088x608_mix.yml)

**Comment by nemonameless** [comment]
jde_yolov3 是 [JDE](https://github.com/Zhongdao/Towards-Realtime-MOT)论文中使用到的yolov3，和普通yolov3稍有不同，具体在anchor、head、loss等方面。jde_yolov3_darknet53 这个前缀表示 检测器名字+backbone。
JDE可以作为具体一个跟踪模型的名字，也可以作为一类跟踪方法的统称，JDE yolov3是一个检测器名字，JDEtracker是一个跟踪器名字。

**Comment by hatecodes** [comment]
> jde_yolov3 是 [JDE](https://github.com/Zhongdao/Towards-Realtime-MOT)论文中使用到的yolov3，和普通yolov3稍有不同，具体在anchor、head、loss等方面。jde_yolov3_darknet53 这个前缀表示 检测器名字+backbone。 JDE可以作为具体一个跟踪模型的名字，也可以作为一类跟踪方法的统称，JDE yolov3是一个检测器名字，JDEtracker是一个跟踪器名字。

您的解答清晰明了，再次感谢
