### ISSUE TITLE
多卡训练卡住

### ISSUE THREAD

**Issue by gjghs** [PaddlePaddle/PaddleDetection#6857]
### 问题描述 Please describe your issue

多卡训练会卡住，一上来就训练不了，单卡的话训练就没有问题
![IJL55DNR%IBBX657{1OJD3O](https://user-images.githubusercontent.com/47850883/188314092-1df12833-2939-4742-a547-7f30f28536fa.png)
多卡训练命令python -m paddle.distributed.launch tools/train.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml --eval，显卡是3090，paddle-gpu 2.3.0.post112，paddledetection2.4release
![L7IB A7FSL)X5ZKYU)4A_ZT](https://user-images.githubusercontent.com/47850883/188314148-0835dcb3-c15c-4ac7-80ca-d16b365b75ff.png)

**Comment by zhiboniu** [comment]
可以检查一下paddle多卡安装是否有问题，使用paddle.utils.run_check()做下检查

**Comment by gjghs** [comment]
> paddle.utils.run_check()

![$0J7B{EMP)8EN@42TSRWO_L](https://user-images.githubusercontent.com/47850883/188356508-5d14c33e-de19-489b-8186-ba1633b6e7d8.png)
您好，看起来安装没有问题

**Comment by gjghs** [comment]
![O @I}~$KJHY 9771LYY8NYY](https://user-images.githubusercontent.com/47850883/188360355-4fc19ca4-029c-4d2b-aa92-07a0248ce5dd.png)
多卡训练时有一张卡利用率一直为零，看起来是掉卡了

**Comment by gjghs** [comment]
调小batchsize就好了，居然没有任何报错信息
