### ISSUE TITLE
pp human 

### ISSUE THREAD

**Issue by zhuoxun-xun** [PaddlePaddle/PaddleDetection#6860]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

pp human 具有不同的识别比如打电话和摔倒识别，在配置文件中与打电话和摔倒识别的参数设定好就可以有检测两个识别吗？还是只能检测一个行动识别？

**Comment by zhiboniu** [comment]
两个都打开enable就可以同时使用两个功能

**Comment by zhuoxun-xun** [comment]
好的，谢谢
