### ISSUE TITLE
是否有非人体姿态的工业关键点检测的解决方案？

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/PaddleDetection#6870]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我有一个工业场景，要检测钩子的弯头处，需要用关键点检测进行标点，而且图片中出现钩子的数量不一定。有没有相应的解决方案？因为COCO的数据集，一个种类的关键点只能有一个，我看好像没法用HRNet。

**Comment by jerrywgz** [comment]
这里可以考虑首先使用检测模型检测出钩子，然后再用关键点模型检测弯头处 这样就是关键点topdown的方案
