### ISSUE TITLE
有没有可以直接计算ap的方法

### ISSUE THREAD

**Issue by gjghs** [PaddlePaddle/PaddleDetection#6873]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

自己的数据集，不是voc也不是coco格式的，eval的时候不能通过dataset的gt_box和gt_class简单的计算ap吗，

### 是否愿意提交PR Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
暂时没有，可以自行参考网上的AP计算实现，全面且权威的指标还是voc或coco格式的。
