### ISSUE TITLE
YOLOE+混合精度训练的疑问

### ISSUE THREAD

**Issue by Dekadenc** [PaddlePaddle/PaddleDetection#6880]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

问题1：混合精度和正常多卡训练有什么区别吗
问题2：按照官网示例的混合精度语句，报了如下错误是什么原因
语句（train的bs由默认的8调整为4）：
python -m paddle.distributed.launch --gpus 0,1,2,3,4,5,6,7 tools/train.py \
	-c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco_HiXray.yml \
	-o num_classes=8 LearningRate.base_lr=0.005 \
	--use_vdl=true \
	--vdl_log_dir=./output/vdl_dir \
	--eval \
	--amp
![image](https://user-images.githubusercontent.com/102035987/188667524-dd7a7b20-831c-4363-8cd5-8a5b86bf8e61.png)

**Comment by nemonameless** [comment]
1.混合精度和正常多卡训练，显存占用更少，精度基本一样
2.查看保存的日志，这个报错一般还是因为显存爆了，加`--amp`或再调小bs试下
