### ISSUE TITLE
行人分析工具

### ISSUE THREAD

**Issue by zhuoxun-xun** [PaddlePaddle/PaddleDetection#6882]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问 pp-human是可以支持多摄像头吗？我应该如何开启多摄像头呢？

**Comment by jerrywgz** [comment]
目前还只支持单摄像头输入，后面会支持多视频流输入
