### ISSUE TITLE
如何制作一个自己的多目标跟踪的数据集，有详细的文档吗

### ISSUE THREAD

**Issue by BainOuO** [PaddlePaddle/PaddleDetection#6891]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

如何制作一个自己的多目标跟踪的数据集，有详细的文档吗

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/docs/tutorials/data
