### ISSUE TITLE
PicoDet 无法使用 TensorRT 加速吗?

### ISSUE THREAD

**Issue by Shrinco** [PaddlePaddle/PaddleDetection#6895]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PicoDet 用 TensorRT 加速之后推理的结果框都不正确.

**Comment by wangxinxin08** [comment]
GPU环境可以尝试PP-YOLOE，picodet可以参考https://github.com/PaddlePaddle/FastDeploy

**Comment by jiangjiajun** [comment]
@Shrinco 可以看下这里的目录 https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/paddledetection  

支持PicoDet使用TensorRT在GPU， OpenVINO在CPU上的部署加速。 所有结果均通过验证
