### ISSUE TITLE
使用tools/export_model.py导出模型出错

### ISSUE THREAD

**Issue by YgRen** [PaddlePaddle/PaddleDetection#69]
你好，我采用PaddleDetection的tools/export_model.py执行导出模型相关操作，出下如下错误，未查找出相关问题
运行环境为ubuntu16.04 Cuda9+Cudnn7.3
使用PaddleDetection yolov3+mobilenetv1训练正常
使用
python tools/export_model.py -c configs/fruveg/yolov3_mobilenet_v1_voc.yml          --output_dir=./inference_model         -o weights=output/yolov3_mobilenet_v1_voc/80000         YoloTestFeed.image_shape=[3,608,608]
出现如下错误
Traceback (most recent call last):
  File "tools/export_model.py", line 118, in <module>
    main()
  File "tools/export_model.py", line 88, in main
    test_feed = create(cfg.test_feed)
  File "/home/ryg/FruVeg/PaddleDetection/ppdet/core/workspace.py", line 160, in create
    "the module {} is not registered".format(name)
AssertionError: the module YoloTestFee is not registered
使用
ython tools/export_model.py -c configs/fruveg/yolov3_mobilenet_v1_voc.yml          --output_dir=./inference_model         -o weights=output/yolov3_mobilenet_v1_voc/80000
同样出现错误
Traceback (most recent call last):
  File "tools/export_model.py", line 118, in <module>
    main()
  File "tools/export_model.py", line 88, in main
    test_feed = create(cfg.test_feed)
  File "/home/ryg/FruVeg/PaddleDetection/ppdet/core/workspace.py", line 160, in create
    "the module {} is not registered".format(name)
AssertionError: the module YoloTestFee is not registered
使用python tools/configure.py list检查
Available modules in the category 'op':

AnchorGenerator     Wrapper for `anchor_generator` OP
RPNTargetAssign     Wrapper for `rpn_target_assign` OP
GenerateProposals   Wrapper for `generate_proposals` OP
MaskAssigner        Wrapper for `generate_mask_labels` OP
MultiClassNMS       Wrapper for `multiclass_nms` OP
BBoxAssigner        Wrapper for `generate_proposal_labels` OP
RoIAlign            Wrapper for `roi_align` OP
RoIPool             Wrapper for `roi_pool` OP
MultiBoxHead        Wrapper for `multi_box_head` OP
SSDOutputDecoder    Wrapper for `detection_output` OP
RetinaTargetAssign  Wrapper for `retinanet_target_assign` OP
RetinaOutputDecoder Wrapper for `retinanet_detection_output` OP
BoxCoder            Wrapper for `box_coder` OP

Available modules in the category 'module':

MultiClassSoftNMS    
RPNHead              RPN Head
FPNRPNHead           RPN Head that supports FPN input
YOLOv3Head           Head block for YOLOv3 network
RetinaHead           Retina Head
ResNet               Residual Network, see https://arxiv.org/abs/1512.03385
ResNetC5             Residual Network, see https://arxiv.org/abs/1512.03385
ResNeXt              ResNeXt, see https://arxiv.org/abs/1611.05431
ResNeXtC5            ResNeXt, see https://arxiv.org/abs/1611.05431
DarkNet              DarkNet, see https://pjreddie.com/darknet/yolo/
MobileNet            MobileNet v1, see https://arxiv.org/abs/1704.04861
SENet                Squeeze-and-Excitation Networks, see https://arxiv.org/abs/1709.01507
SENetC5              Squeeze-and-Excitation Networks, see https://arxiv.org/abs/1709.01507
FPN                  Feature Pyramid Network, see https://arxiv.org/abs/1612.03144
VGG                  VGG, see https://arxiv.org/abs/1409.1556
BlazeNet             BlazeFace, see https://arxiv.org/abs/1907.05047
FaceBoxNet           FaceBoxes, see https://https://arxiv.org/abs/1708.05234
CBResNet             CBNet, see https://arxiv.org/abs/1909.03625
FPNRoIAlign          RoI align pooling for FPN feature maps
XConvNormHead        RCNN head with serveral convolution layers
TwoFCHead            RCNN head with two Fully Connected layers
BBoxHead             RCNN bbox head
MaskHead             RCNN mask head
CascadeBBoxHead      Cascade RCNN bbox head
CascadeXConvNormHead RCNN head with serveral convolution layers
CascadeTwoFCHead     RCNN head with serveral convolution layers
CascadeBBoxAssigner  

Available modules in the category 'architecture':

FasterRCNN          Faster R-CNN architecture, see https://arxiv.org/abs/1506.01497
MaskRCNN            Mask R-CNN architecture, see https://arxiv.org/abs/1703.06870
CascadeRCNN         Cascade R-CNN architecture, see https://arxiv.org/abs/1712.00726
CascadeMaskRCNN     Cascade Mask R-CNN architecture, see https://arxiv.org/abs/1712.00726
CascadeRCNNClsAware Cascade R-CNN architecture, see https://arxiv.org/abs/1712.00726
YOLOv3              YOLOv3 network, see https://arxiv.org/abs/1804.02767
SSD                 Single Shot MultiBox Detector, see https://arxiv.org/abs/1512.02325
RetinaNet           RetinaNet architecture, see https://arxiv.org/abs/1708.02002
BlazeFace           BlazeFace: Sub-millisecond Neural Face Detection on Mobile GPUs,
FaceBoxes           FaceBoxes: Sub-millisecond Neural Face Detection on Mobile GPUs,

Available modules in the category 'optim':

LearningRate     Learning Rate configuration
OptimizerBuilder Build optimizer handles

Available modules in the category 'data':

TrainFeed           DataFeed encompasses all data loading related settings
EvalFeed            DataFeed encompasses all data loading related settings
TestFeed            DataFeed encompasses all data loading related settings
FasterRCNNTrainFeed DataFeed encompasses all data loading related settings
FasterRCNNEvalFeed  DataFeed encompasses all data loading related settings
FasterRCNNTestFeed  DataFeed encompasses all data loading related settings
MaskRCNNTrainFeed   DataFeed encompasses all data loading related settings
MaskRCNNEvalFeed    DataFeed encompasses all data loading related settings
MaskRCNNTestFeed    DataFeed encompasses all data loading related settings
SSDTrainFeed        DataFeed encompasses all data loading related settings
SSDEvalFeed         DataFeed encompasses all data loading related settings
SSDTestFeed         DataFeed encompasses all data loading related settings
YoloTrainFeed       DataFeed encompasses all data loading related settings
YoloEvalFeed        DataFeed encompasses all data loading related settings
YoloTestFeed        DataFeed encompasses all data loading related settings
不存在缺少模块
盼复🙏

**Comment by wangvation** [comment]
你好，请问，你是怎么解决的？
