### ISSUE TITLE
linux、windows平台，同一模型、权重，验证精度不一致；推理后预测值也不一样

### ISSUE THREAD

**Issue by Tongfengyu** [PaddlePaddle/PaddleDetection#6902]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在linux平台训练mobilenetv1-centernet模型，训练好后，进行验证推理，同时下载到本地windows测试。
在linux上验证精度mAP(0.50:0.95)为0.131，windows上mAP(0.50:0.95)为0.213；
推理后txt文件置信度，坐标也不一样。
win：paddlepaddle-gpu 2.3.0
linux: paddlepaddle-gpu 2.3.1

**Comment by wangxinxin08** [comment]
可以先check下使用的权重是否相同，比如用`md5sum model.pdparams`比较下md5值，另外确认下eval的数据是否一致。如果一致的话，可以把详细信息留一下：
1. windows和Linux的CUDA，CUDNN版本
2. mobilenetv1-centernet的pdparams

**Comment by Tongfengyu** [comment]
ok，谢谢，问题解决了。是eval的数据不一样
