### ISSUE TITLE
使用HRNet_ssld预训练backbone

### ISSUE THREAD

**Issue by ydhongHIT** [PaddlePaddle/PaddleDetection#6903]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

从https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/HRNet_W18_C_ssld_pretrained.pdparams下载了hrnet的ssld预训练模型，导入时键值不匹配，无法导入权重。

**Comment by wangxinxin08** [comment]
应该是名字不一致，建议对齐下名字转换一下
