### ISSUE TITLE
目标检测数据集需要一个类似TrustAI来清洗数据

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#6910]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标：当前手里有标注质量不是太好的目标检测数据集，当前需要类似Paddle出的TrustAI（https://github.com/PaddlePaddle/TrustAI）这样的工具来清洗数据集; 
2 需求场景：手里有很多数据集，每个数据集有部分标注质量不是很好，想用类似TrustAI这样的工具来清洗; 
3.功能描述：对目标检测数据集进行清洗，类似TrustAI，将不太好的数据删除，或者修正部分标注。

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
感谢建议

**Comment by lyuwenyu** [comment]
收到 会及时反馈
