### ISSUE TITLE
基于Paddle的YOLOX疑问，紧急，多谢

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#6913]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

1  为什么基于Paddle的YOLOX-nano/ YOLOX-tiny/ YOLOX-m/ YOLOX-l/ YOLOX-x都有不同程度的涨点？具体修改了哪些部分？
2  为什么基于Paddle的YOLOX-s却比官方公布的降点0.1%？

https://github.com/PaddlePaddle/PaddleDetection/issues/new?assignees=&labels=type%2Fquestion%2Cstatus%2Fnew-issue&template=4_ask-a-question.yml

**Comment by nemonameless** [comment]
照着megvii原版复现的。按照作者意见，改了ema_decay=0.9999，https://github.com/Megvii-BaseDetection/YOLOX/issues/735 ，0.1 mAP的diff是正常现象。

**Comment by lixiangMindSpore** [comment]
> 照着megvii原版复现的。按照作者意见，改了ema_decay=0.9999，[Megvii-BaseDetection/YOLOX#735](https://github.com/Megvii-BaseDetection/YOLOX/issues/735) ，0.1 mAP的diff是正常现象。

按照您给的issue链接，ema_decay从0.9998改为0.9999，您这面的total batchsize是多少？128还是64？为什么YOLOX-nano/ YOLOX-tiny/ YOLOX-m/ YOLOX-l/ YOLOX-x都有不同程度的涨点？

**Comment by nemonameless** [comment]
ppdet yolox coco模型的总bs都是64
