### ISSUE TITLE
Invitation to PaddleDetection team to speak at YOLO VISION event on September 27th, 2022

### ISSUE THREAD

**Issue by glenn-jocher** [PaddlePaddle/PaddleDetection#6916]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi PaddleDetection team,

I'm [Glenn Jocher](https://www.linkedin.com/in/glenn-jocher/), author of [YOLOv5](https://github.com/ultralytics/yolov5). I'd like to invite you to speak at the world's first-ever YOLO conference: [YOLO VISION](https://ultralytics.com/yolo-vision). This virtual event takes place on September 27th, 2022 with talks from the world's leading vision AI experts from Google, SenseTime's MMLabs, Meituan YOLOv6, Weight & Biases, Roboflow and of course Ultralytics and YOLOv5 and many others.

I've also extended invites to the YOLOv4 and YOLOv7 team and Megvii's YOLOX team to make this a truly YOLO-centric event. 

Please send us an email at glenn.jocher@ultralytics.com to get started.

Thanks!

<a align="center" href="https://ultralytics.com/yolo-vision" target="_blank">
      <img width="850" src="https://user-images.githubusercontent.com/26833433/187986731-f749af08-6e2b-4e14-aeaa-dec2fa0b0113.jpg"></a>

**Comment by YixinKristy** [comment]
Thanks for inviting us! We'd love to take the chance to learn and communicate with all the experts in object detection field. Already set a meeting tmr and look forward to discussing more details about this event~
