### ISSUE TITLE
TTA还是不能普遍适用吗？

### ISSUE THREAD

**Issue by ycyinchao** [PaddlePaddle/PaddleDetection#6917]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

**Comment by nemonameless** [comment]
see [multi_scale_test_config](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/config_annotation/multi_scale_test_config.md)
