### ISSUE TITLE
有没有基于Paddle的CenterX的实现？

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#6921]
### 问题描述 Please describe your issue

有没有基于Paddle的CenterX的实现？
https://github.com/JDAI-CV/centerX

**Comment by nemonameless** [comment]
暂时没有计划。centernet是有复现支持的，https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/centernet
