### ISSUE TITLE
about deploy/pipeline/pipeline.py use camera_id

### ISSUE THREAD

**Issue by oligaameiz** [PaddlePaddle/PaddleDetection#6930]
python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_pphuman.yml --camera_id=0 --device=gpu  --draw_center_traj --do_break_in_counting --region_type=custom --region_polygon 
200 200 400 200 300 400 100 400

deploy\pipeline\pipeline.py:24: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Sequence, defaultdict
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use OC-SORT, please install filterpy, for example: `pip install filterpy`, see https://github.com/rlabbe/filterpy
Warning: Unable to use motmetrics in MTMCT in PP-Tracking, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use OC-SORT, please install filterpy, for example: `pip install filterpy`, see https://github.com/rlabbe/filterpy
Warning: Unable to use motmetrics in MTMCT in PP-Tracking, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
-----------  Running Arguments -----------
ATTR:
  batch_size: 8
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/PPLCNet_x1_0_person_attribute_945_infer.zip
DET:
  batch_size: 1
  model_dir: output_inference\mot_ppyoloe_l_36e_pipeline
ID_BASED_CLSACTION:
  batch_size: 8
  display_frames: 80
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/PPHGNet_tiny_calling_halfbody.zip
  skip_frame_num: 2
  threshold: 0.8
ID_BASED_DETACTION:
  batch_size: 8
  display_frames: 80
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/ppyoloe_crn_s_80e_smoking_visdrone.zip
  skip_frame_num: 2
  threshold: 0.6
KPT:
  batch_size: 8
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/dark_hrnet_w32_256x192.zip
MOT:
  batch_size: 1
  enable: true
  model_dir: output_inference\mot_ppyoloe_l_36e_pipeline
  skip_frame_num: -1
  tracker_config: deploy/pipeline/config/tracker_config.yml
REID:
  batch_size: 16
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/reid_model.zip
SKELETON_ACTION:
  batch_size: 1
  coord_size:
  - 384
  - 512
  display_frames: 80
  enable: false
  max_frames: 50
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/STGCN.zip
VIDEO_ACTION:
  batch_size: 1
  enable: false
  frame_len: 8
  model_dir: https://videotag.bj.bcebos.com/PaddleVideo-release2.3/ppTSM_fight.zip
  sample_freq: 7
  short_size: 340
  target_size: 320
attr_thresh: 0.5
crop_thresh: 0.5
kpt_thresh: 0.2
visual: true
warmup_frame: 50

------------------------------------------
Multi-Object Tracking enabled
DET  model dir:  output_inference\mot_ppyoloe_l_36e_pipeline
MOT  model dir:  output_inference\mot_ppyoloe_l_36e_pipeline
KPT  model dir:  .cache/paddle/infer_weights\dark_hrnet_w32_256x192
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: Permute
--------------------------------------------
Traceback (most recent call last):
  File "deploy\pipeline\pipeline.py", line 1084, in <module>
    main()
  File "deploy\pipeline\pipeline.py", line 1069, in main
    pipeline = Pipeline(FLAGS, cfg)
  File "deploy\pipeline\pipeline.py", line 88, in __init__
    self.predictor.set_file_name(self.input)
  File "deploy\pipeline\pipeline.py", line 473, in set_file_name
    self.file_name = os.path.split(path)[-1]
  File "anaconda3\envs\paddlehub\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not int

**Comment by YaoOOoooolin** [comment]
您好，请问您解决这个问题了吗？

**Comment by hanhanshangying** [comment]
同问，问题解决了吗？

**Comment by YaoOOoooolin** [comment]
> 同问，问题解决了吗？

https://blog.csdn.net/m0_62267751/article/details/127573485?spm=1001.2014.3001.5502
