### ISSUE TITLE
Triton部署yolov3推理异常

### ISSUE THREAD

**Issue by Aspirinkb** [PaddlePaddle/PaddleDetection#6932]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

将训练的yolov3导出为推理模式，再转换为onnx格式，使用Triton部署。推理时报错：
```
Non-zero status code returned while running Gather node. Name:'p2o.Gather.12' Status Message: /workspace/onnxruntime/onnxruntime/core/providers/common.h:23 int64_t onnxruntime::HandleNegativeAxis(int64_t, int64_t) axis >= -tensor_rank && axis <= tensor_rank - 1 was false. axis 0 is not in valid range [-0,-1]
```
模型输入图像大小为[1, 3, 608, 608], float32数据类型   
如果将图像数据归一化，则报上面的错。   
如果不归一化，直接将原始数据由uint8转换为float32，则可以正常运行推理，但是返回的bboxes的坐标点错误。   

首先，是不是需要归一化？yolov3的mobilenet ssl模型。   
其次，如果不需要归一化，为什么模型返回值和paddlepaddle返回的不相同（后者返回正确），需要后处理吗？   
最后，如果需要归一化，为什么会出现上面运行时错误？   

提前谢谢

**Comment by jerrywgz** [comment]
数据预处理方法统一放在了paddle导出模型的infer_cfg.yml中，可以先用paddle导出的模型在paddledetection下验证deploy/python部署是否正常

**Comment by lingdu-xu** [comment]
> 数据预处理方法统一放在了paddle导出模型的infer_cfg.yml中，可以先用paddle导出的模型在paddledetection下验证deploy/python部署是否正常

我也遇到了同样的问题，刚刚训练好的模型存放在output/best_model中，我先使用export_model转inference,通过命令行指令验证能跑（截图如下）
![1714355020753](https://github.com/PaddlePaddle/PaddleDetection/assets/42382041/1fcd0df3-295d-457a-8ba9-f5970a18ecaf)
然后使用指令转onnx
![1714355135424](https://github.com/PaddlePaddle/PaddleDetection/assets/42382041/4ea60d6c-e143-4ef7-8c4a-4f0bc5c119c4)
然后使用onnx推理，就报这样的错误，
Traceback (most recent call last):
  File "C:\c_test\detection\main.py", line 219, in <module>
    one_img_rlt = detection_obj.predict_image(imgdata)    #单张图片的结果当场就返回了,注意，返回的结果是图像像素的结果，需要转换为实际坐标
  File "C:\c_test\detection\need\DetectionApi.py", line 295, in predict_image
    self.model.modelRun(self.image)
  File "C:\c_test\detection\need\ImageModel.py", line 241, in modelRun
    self.onnx_slice_Run(imgobj, processbar)
  File "C:\c_test\detection\need\ImageModel.py", line 332, in onnx_slice_Run
    outputs = self.predictor.run(output_names=None, input_feed=inputs)
  File "C:\Users\Raphael\AppData\Local\Programs\Python\Python39\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Gather node. Name:'p2o.Gather.8' Status Message: D:\a\_work\1\s\onnxruntime\core/providers/common.h:24 onnxruntime::HandleNegativeAxis axis >= -tensor_rank && axis <= tensor_rank - 1 was false. axis 0 is not in valid range [-0,-1]
而且奇怪的是，它并不是每张图都会报错，有的图可以正常推理，而有的图不能正常推理

**Comment by lingdu-xu** [comment]
> 数据预处理方法统一放在了paddle导出模型的infer_cfg.yml中，可以先用paddle导出的模型在paddledetection下验证deploy/python部署是否正常

经过多次实验，终于确定了一个最有可能引起这个问题的地方，以yolox举例，在cspdarknet.yml中有一个参数是score_threshold，假如把它从默认的0.001改成0.25，训练得到的图像就会引发onnx的推理问题：“ Non-zero status code returned while running Gather node”，建议修正。也有可能是我的用法不大对哈，
