### ISSUE TITLE
训练公开数据集，paddledetection 会自动下载数据的问题

### ISSUE THREAD

**Issue by zgsxwsdxg** [PaddlePaddle/PaddleDetection#6935]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我想问下，paddledetection训练怎么设置自动下载公开数据的保存位置，我发现它往/home/developer/.cache/paddle/dataset/coco目录下载，导致我的系统盘空间不够用了，通过哪里能设置修改下载路径了？谢谢！期待你的回答

**Comment by nemonameless** [comment]
自己的数据集路径配置对了就不会自动下载，请再自己检查下，log里会有warning打印出来的告诉你哪里配的不对，发现自动下载时就应该停止再自查。配置的不对即使把自动下载的代码注释掉，也是无法训练的。

学会代码全局搜索，关键字搜 log里报错自动下载的相关语句，就能定位到自动下载的函数，自己改代码注释掉或强制返回true即可。
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/utils/download.py#L226

相关issue:
https://github.com/PaddlePaddle/PaddleDetection/search?q=for+automaticly+downloading%2C+which+only+supports&type=issues

**Comment by zgsxwsdxg** [comment]
> 自己改代码注释掉或强制返回true即

非常感谢，我改下代码，应该没问题了。
