### ISSUE TITLE
C++部署使用trt加速，推测时间长

### ISSUE THREAD

**Issue by qinlihaoWork** [PaddlePaddle/PaddleDetection#6942]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

 使用PaddleDetection 按照教程进行cpp部署，将**object_detector.cc**中的 Engine, use_static改为true
![image](https://user-images.githubusercontent.com/111327813/190307967-06559e84-8b0d-4505-a344-c9208473f2e3.png)
在trt完成第一次warm-up时，推理一张照片的用时为**13ms**
![企业微信截图_16632126516838](https://user-images.githubusercontent.com/111327813/190308150-b55d8cb4-3224-4b76-87ad-2239f4c7eef9.png)
Engine生成后，再次使用trt进行推理加速，用时为**540ms**,推理用时比使用cpu进行预测还要久。
![企业微信截图_16632125243948](https://user-images.githubusercontent.com/111327813/190308228-e771f298-ccc4-4279-aa40-2df5234a8118.png)
请问这种情况该如何解决？

**Comment by jerrywgz** [comment]
这里使用trt_fp16是否会有问题？另外请使用paddle inference最新版本预测

**Comment by qinlihaoWork** [comment]
> 这里使用trt_fp16是否会有问题？另外请使用paddle inference最新版本预测

你好，使用trt_fp16不会有问题，推理单张的时间也是500多ms，paddle inference 使用的版本是v2.3
把一些图片放在文件夹中进行预测时，推理时间会快一些。
![image](https://user-images.githubusercontent.com/111327813/190549946-a9259fae-8d90-45fb-ac5c-7cd3e73ad6a6.png)
请问真正部署时的推理时间应该以哪一个作为参考？
