### ISSUE TITLE
Linux下用官方给的c++部署教程报错

### ISSUE THREAD

**Issue by 923629877** [PaddlePaddle/PaddleDetection#6943]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

在Linux下，用C++调用pp—tsm模型
按照官方给的教程，执行到最后一步（./build/ppvideo rec \
--rec_model_dir=../../inference/ppTSM \
--inference_model_name=ppTSM \
--video_dir=./example_video_dir \
--num_seg=8 \
--seg_len=1）
的时候抛出了一个错误（terminate called after throwing an instance of char const*）

### 复现环境 Environment

linux
paddlepaddle 2.3.2
python3.9

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [x] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by jerrywgz** [comment]
麻烦到PaddleVideo下提issue问下 https://github.com/PaddlePaddle/PaddleVideo/issues
