### ISSUE TITLE
PPYoloE-Plus的预测时间

### ISSUE THREAD

**Issue by loneclown** [PaddlePaddle/PaddleDetection#6946]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

命令：CUDA_VISIBLE_DEVICES=0 python python/infer.py --model_dir=ppyoloe_plus_crn_x_80e_coco --image_file=demo/000000014439_640x640.jpg --run_mode=paddle --device=gpu --save_images=True

------------------ Inference Time Info ----------------------
total_time(ms): 1358.8, img_num: 1
average latency time(ms): 1358.80, QPS: 0.735943
preprocess_time(ms): 22.30, inference_time(ms): 1336.40, postprocess_time(ms): 0.10

 inference_time(ms)为1336ms,这时间为什么这么长

显卡为3090

**Comment by jerrywgz** [comment]
单张图片的预测会包含模型启动的时间，可以开启--run_benchmark测试实际时间，另外还可以开启tensorrt进一步加速 需要设置--run_mode=trt_fp16
