### ISSUE TITLE
模型文件无法下载

### ISSUE THREAD

**Issue by Chenzixi1** [PaddlePaddle/PaddleDetection#6948]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

https://paddledet.bj.bcebos.com/deploy/third_engine/picodet_s_320_coco_lcnet.onnx

**Comment by nemonameless** [comment]
请自查自己机器的环境联网问题
