### ISSUE TITLE
自定义数据的行为识别教程

### ISSUE THREAD

**Issue by zhuoxun-xun** [PaddlePaddle/PaddleDetection#6951]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我想对人体骨骼点的行为识别进行二次开发但教程有点迷糊。
比如我有100视频。是要对每个视频分别获取序列的骨骼点坐标，再保存为PaddleVideo可用的文件格式？

**Comment by zoooo0820** [comment]
是的，一个视频片段会转化为一个骨骼点序列（每一帧都有人物的一组骨骼点坐标）
