### ISSUE TITLE
参数共享的实现

### ISSUE THREAD

**Issue by NwTbbetter** [PaddlePaddle/PaddleDetection#6952]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问参数共享是否可以这么实现，为什么会报这样的错误？
```
share1=self.create_parameter(
                shape=[c,c//2,1,1],
                attr=ParamAttr(initializer=Constant(value=1.)),
                dtype="float32")
        self.conv11 = ConvBNLayer(
            ch_in = c, 
            ch_out = c // 2,
            filter_size=1,
            stride=1,
            padding=0,
            weight_attr=share1)
```
![image](https://user-images.githubusercontent.com/99952437/190558528-ac4ef5eb-535a-4777-ae57-677afc9760e2.png)

**Comment by nemonameless** [comment]
请按模板提问，再详细描述谢谢。
ConvBNLayer是哪个ConvBNLayer，是怎么写的？weight_attr直观上看只可以赋值为true false。
可以代码全局搜索，搜self.create_parameter 模仿着写即可。
