### ISSUE TITLE
使用yolov7训练报错ValueError: (InvalidArgument) The dtype of Tensor in list must be int32 or int64, but received: 0 (at ..\paddle/fluid/operators/utils.h:85)   [operator < slice > error]

### ISSUE THREAD

**Issue by HUPg-95** [PaddlePaddle/PaddleDetection#6953]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

训练自己的数据集是出现```ValueError: (InvalidArgument) The dtype of Tensor in list must be int32 or int64, but received: 0 (at ..\paddle/fluid/operators/utils.h:85)```
根据提示找到代码部分```yolo_loss.py```文件，605行的```this_target = targets[b_idx]```，发现b_idx为布尔类型的Tensor，因此猜想是否这里有问题

### 复现环境 Environment

windows
paddlepaddle:2.2.2
paddlDetection:2.4
python: 3.7.6
CUDA: 10.2
CUDNN: 7.6

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
yolov7请使用paddle2.3.0以上版本训练，注意中有写。
[PaddleDetection_YOLOSeries](https://github.com/nemonameless/PaddleDetection_YOLOSeries)其develop分支请使用paddle develop版本，其他分支请使用paddle 2.3.2版本。
