### ISSUE TITLE
Target(Tensor(shape=[1],dtype=int64,place=CUDAPlace(0),stop_gradient=True,[10])) is out of class_dimension's upper bound(9)

### ISSUE THREAD

**Issue by chenjw1009** [PaddlePaddle/PaddleDetection#6955]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

Target(Tensor(shape=[1],dtype=int64,place=CUDAPlace(0),stop_gradient=True,[10])) is out of class_dimension's upper bound(9)

视频目标追踪，单目标，我用了10个视频序列，就出现这样的错误

### 复现环境 Environment

Target(Tensor(shape=[1],dtype=int64,place=CUDAPlace(0),stop_gradient=True,[10])) is out of class_dimension's upper bound(9)

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by chenjw1009** [comment]
Target(Tensor(shape=[1],dtype=int64,place=CUDAPlace(0),stop_gradient=True,[10])) is out of class_dimension's upper bound(9)

视频目标追踪，单目标，我用了10个视频序列，就出现这样的错误

**Comment by nemonameless** [comment]
请规范且认真的按模板提问谢谢，没有足够的有效信息很难帮你解决问题谢谢。
报bug请至少提供代码改动、运行命令、环境版本、报错截图或log，谢谢。
