### ISSUE TITLE
Segmentaion Fault paddlepaddleDetectionDev 

### ISSUE THREAD

**Issue by MyraBaba** [PaddlePaddle/PaddleDetection#6956]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference

### Bug描述 Describe the Bug

python3 deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_ppvehicle.yml    --video_file=/data/Videos/hiv00038.mp4  --device=gpu
deploy/pipeline/pipeline.py:24: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Sequence, defaultdict
-----------  Running Arguments -----------
DET:
  batch_size: 1
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_ppvehicle.zip
MOT:
  batch_size: 1
  enable: true
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_ppvehicle.zip
  skip_frame_num: -1
  tracker_config: deploy/pipeline/config/tracker_config.yml
VEHICLE_ATTR:
  batch_size: 8
  color_threshold: 0.5
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/vehicle_attribute_model.zip
  type_threshold: 0.5
VEHICLE_PLATE:
  det_limit_side_len: 736
  det_limit_type: min
  det_model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/ch_PP-OCRv3_det_infer.tar.gz
  enable: false
  rec_batch_num: 6
  rec_image_shape:
  - 3
  - 48
  - 320
  rec_model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/ch_PP-OCRv3_rec_infer.tar.gz
  word_dict_path: deploy/pipeline/ppvehicle/rec_word_dict.txt
crop_thresh: 0.3
visual: true
warmup_frame: 50

------------------------------------------
Multi-Object Tracking enabled
DET  model dir:  /home/alp2080/.cache/paddle/infer_weights/mot_ppyoloe_l_36e_ppvehicle
MOT  model dir:  /home/alp2080/.cache/paddle/infer_weights/mot_ppyoloe_l_36e_ppvehicle
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: Permute
--------------------------------------------
video fps: 25, frame_count: 12525
Thread: 0; frame id: 0

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1663332777 (unix time) try "date -d @1663332777" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 1553976 (TID 0x7fe07e306740) from PID 0 ***]

Segmentation fault (core dumped)

### 复现环境 Environment

Linux
PaddleDetecton latest dev

docker conatiner  working  ,  but in  linux installed paddledetection its gives seg fault for tracking

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/search?q=Segmentation+fault+is+detected+by+the+operating+system.&type=issues
1. try `--device=gpu`, make sure your cuda cudnn is ok, see https://github.com/PaddlePaddle/PaddleDetection/issues/4934
2. There are too many video frames. It is better to save them locally, or there may not be enough memory.
