### ISSUE TITLE
执行 tools/train.py训练提示错误 out of bound 

### ISSUE THREAD

**Issue by ionescofung** [PaddlePaddle/PaddleDetection#6959]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

已经下载了coco的数据集
执行tools/train.py训练提示错误。请问什么原因？
我的电脑gpu是3070显卡 cuda 11.6
![image](https://user-images.githubusercontent.com/55121158/190848152-04f1b552-d258-49ac-a86f-fb775b603369.png)

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/search?q=out+of+bound&type=issues

**Comment by nemonameless** [comment]
win下请安装最新develop版本的paddle。
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html
