### ISSUE TITLE
pp-humanv2部署调用摄像头问题

### ISSUE THREAD

**Issue by xihuanafeng** [PaddlePaddle/PaddleDetection#6960]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_pphuman.yml --camera_id=0 --device=gpu
显示
![image](https://user-images.githubusercontent.com/78284628/190858865-8f847416-59b3-4cd4-b21c-ce9e9d57e3e0.png)

**Comment by qq-tt** [comment]
把0改成"0"不可以么？

**Comment by xihuanafeng** [comment]
不可以噢，还是一样的效果

**Comment by xihuanafeng** [comment]
嗯嗯，也是不可以的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月22日(星期四) 上午10:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] pp-humanv2部署调用摄像头问题 (Issue #6960)





 
把0改成"0"不可以么？

**Comment by YaoOOoooolin** [comment]
您好，请问您解决了吗，我是同意的问题，开始以为是我python3.9版本高的问题，看到您3.8也报错。您能教教我吗

**Comment by qq-tt** [comment]
> 您好，请问您解决了吗，我是同意的问题，开始以为是我python3.9版本高的问题，看到您3.8也报错。您能教教我吗

把p值和他的类型输出来，看看是不是字符串类型

**Comment by YaoOOoooolin** [comment]
> 

您好，全部都是str

**Comment by YaoOOoooolin** [comment]
> > 您好，请问您解决了吗，我是同意的问题，开始以为是我python3.9版本高的问题，看到您3.8也报错。您能教教我吗
> 
> 把p值和他的类型输出来，看看是不是字符串类型
<img width="143" alt="屏幕截图 2022-10-26 095428" src="https://user-images.githubusercontent.com/108522692/197916153-be0f3b3c-fc07-4efc-8f24-57ba7cdf92b0.png">

**Comment by YaoOOoooolin** [comment]
> > 您好，请问您解决了吗，我是同意的问题，开始以为是我python3.9版本高的问题，看到您3.8也报错。您能教教我吗
> 
> 把p值和他的类型输出来，看看是不是字符串类型

<img width="376" alt="屏幕截图 2022-10-26 095844" src="https://user-images.githubusercontent.com/108522692/197916703-1d361299-b529-4e51-be12-682f341959eb.png">

**Comment by qq-tt** [comment]
> > > 您好，请问您解决了吗，我是同意的问题，开始以为是我python3.9版本高的问题，看到您3.8也报错。您能教教我吗
> > 
> > 
> > 把p值和他的类型输出来，看看是不是字符串类型
> 
> <img alt="屏幕截图 2022-10-26 095844" width="376" src="https://user-images.githubusercontent.com/108522692/197916703-1d361299-b529-4e51-be12-682f341959eb.png">

把gpu换成cpu试试


> > 
> 
> 您好，全部都是str

你自己也明确一下那些self.file_name正不正确

**Comment by YaoOOoooolin** [comment]
https://blog.csdn.net/m0_62267751/article/details/127573485?spm=1001.2014.3001.5502

解决方法↑
