### ISSUE TITLE
PaddleDetection是否有计划提供GUI界面，类似于PaddleX的GUI界面

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#6964]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

每次训练需要修改配置 麻烦
每次还要导出对应数据集

如果有PaddleX的GUI界面训练模型
那就方便多了

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
暂时没有计划。可以在PaddleX里使用PaddleDetection

**Comment by monkeycc** [comment]
PaddleX不能使用PaddleDetection吧
PaddleX也就是几个模型
