### ISSUE TITLE
单目标追踪

### ISSUE THREAD

**Issue by chenjw1009** [PaddlePaddle/PaddleDetection#6967]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddledetection 可以做单目标追踪吗？有相关示例吗？包括样本格式怎么组织之类的？

**Comment by chenjw1009** [comment]
paddledetection 可以做单目标追踪吗？有相关示例吗？包括样本格式怎么组织之类的？

**Comment by nemonameless** [comment]
暂时没有支持SOT，之后可能会计划复现SOT算法但近期暂时不会安排。
