### ISSUE TITLE
集群Docker训练报错：Compiled with WITH_GPU, but no GPU found in runtime.

### ISSUE THREAD

**Issue by fxd0122** [PaddlePaddle/PaddleDetection#6968]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在集群中使用同一个镜像，申请交互式调试任务的时候运行paddledet没有问题。
![image](https://user-images.githubusercontent.com/54058611/190946656-c3f62371-290b-4ca5-abe1-5399385299ad.png)
但是在申请训练任务的时候，会出现
![image](https://user-images.githubusercontent.com/54058611/190946841-fa5d91fa-a657-4eb3-b962-d6d4def8e136.png)
但是系统是存在gpu环境的
![image](https://user-images.githubusercontent.com/54058611/190947092-50f2bfa6-34e1-4fbf-8496-962fc613d97a.png)
按照以往使用其它深度学习的框架经验，申请交互式调试任务能够正常运行，申请任务训练时试可以正常运行的，请问是怎么回事？（我也试过cudnn8）

**Comment by nemonameless** [comment]
请先自查下环境变量export之类的问题
