### ISSUE TITLE
基于Paddle的YOLOX的backbone有没有替换成Hornet进行实验，与YOLOX-ConvNeXt-s相比精度如何？

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#6970]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

基于Paddle的YOLOX的backbone有没有替换成Hornet进行实验，与YOLOX-ConvNeXt-s相比精度如何？

**Comment by nemonameless** [comment]
暂未计划。代码好加，但是要加载paddle的Hornet imagenet预训练，可以给PaddleClas提需求。
