### ISSUE TITLE
param_groups在paddle中的api

### ISSUE THREAD

**Issue by bixiaopeng0** [PaddlePaddle/PaddleDetection#6976]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问torch优化器中的optimizer.param_groups，在paddle对应哪个api呀？

**Comment by ghostxsl** [comment]
参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/optimizer/optimizer.py#L310
