### ISSUE TITLE
det_keypoint_unite_infer 部署集成问题：NameError: name 'Detector' is not defined

### ISSUE THREAD

**Issue by usuixingyili** [PaddlePaddle/PaddleDetection#6977]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/74706568/191173531-20a8b06e-2578-4a48-8ce4-e44ba26d9268.png)

由于是集成到项目中，不采用命令行的方式，是否和未设置FLAGS参数有关？

**Comment by ghostxsl** [comment]
看报错信息，Detector这个class没有声明吧，再检查一下呢
