### ISSUE TITLE
使用的Cascade Faster rcnn 的模型出现Aborted（core dumped）

### ISSUE THREAD

**Issue by caoweiying123** [PaddlePaddle/PaddleDetection#698]
![QQ图片20200516231601](https://user-images.githubusercontent.com/60028206/82123315-4cbf9280-97cb-11ea-8d15-5d4e3527023c.png)

好像都是一千多次或者几百次iters就开始出现问题
GPU的显存是32GB的单卡，batch_size也是1，用的是VOC数据集，不知道是哪里出现问题
多谢啦！！！

**Comment by qingqing01** [comment]
@caoweiying123 截图太少了，没有看出具体错误。 请再多贴一些错误信息，另外，尽量贴文本信息，图片有时候打不开。 另外，请注意GPU卡数、batch-size变化时，调整参数： https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/FAQ.md#faq%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by caoweiying123** [comment]
我换了个层数较小的网络解决了😁
