### ISSUE TITLE
准备数据路径失效

### ISSUE THREAD

**Issue by WesleyYeh** [PaddlePaddle/PaddleDetection#6981]
### 文档链接&描述 Document Links & Description

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/data/PrepareDataSet.md#%E5%87%86%E5%A4%87%E8%AE%AD%E7%BB%83%E6%95%B0%E6%8D%AE
这里的路径失效

**Comment by nemonameless** [comment]
see https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/docs/tutorials/data
