### ISSUE TITLE
batch_size怎么设置才合理

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#6984]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

比如我的是3060显卡 12GB显存

TrainReader
  batch_size: 1

EvalReader
  batch_size: 1

TestReader:
  batch_size: 1

比如
yolo模型
maskrcnn v50 模型

需要怎么设置才比较合理

**Comment by ghostxsl** [comment]
根据显卡配置，建议设置成2的幂次

**Comment by monkeycc** [comment]
2的幂次  下面都是2吗
--------------------------

TrainReader
batch_size: 2

EvalReader
batch_size: 2

TestReader:
batch_size: 2

-------------------------

TrainReader
batch_size: 2

EvalReader
batch_size: 2

TestReader:
batch_size: 1

-------------------------

TrainReader
batch_size: 2

EvalReader
batch_size: 1

TestReader:
batch_size: 1
