### ISSUE TITLE
基于Paddle有没有自监督或者半自监督的目标检测模型？

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#6986]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

基于Paddle有没有自监督或者半自监督的目标检测模型？

**Comment by nemonameless** [comment]
在建设中，预计可能下个月。

**Comment by nemonameless** [comment]
PaddleDetection目前已支持半监督检测方法DenseTeacher，在develop分支中，欢迎使用~
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/semi_det/denseteacher
