### ISSUE TITLE
jetson TX2上用paddle inference部署pp-yoloe模型，遇到如下报错：

### ISSUE THREAD

**Issue by lkpk1994** [PaddlePaddle/PaddleDetection#6987]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![1258052902](https://user-images.githubusercontent.com/38982677/191399176-02e80952-20ae-44c7-8a30-a92848faf269.jpg)

`import cv2
import numpy as np
from paddle.inference import Config
from paddle.inference import PrecisionType
from paddle.inference import create_predictor
from PIL import Image, ImageDraw, ImageFont
import yaml
import time

# ————————————————图像预处理函数———————————————— #

def resize(img, target_size):
    """resize to target size"""
    if not isinstance(img, np.ndarray):
        raise TypeError('image type is not numpy.')
    im_shape = img.shape
    im_size_min = np.min(im_shape[0:2])
    im_size_max = np.max(im_shape[0:2])
    im_scale_x = float(target_size) / float(im_shape[1])
    im_scale_y = float(target_size) / float(im_shape[0])
    img = cv2.resize(img, None, None, fx=im_scale_x, fy=im_scale_y)
    return img

def normalize(img, mean, std):
    img = img / 255.0
    mean = np.array(mean)[np.newaxis, np.newaxis, :]
    std = np.array(std)[np.newaxis, np.newaxis, :]
    img -= mean
    img /= std
    return img

def preprocess(img, img_size):
    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]
    img = resize(img, img_size)
    img = img[:, :, ::-1].astype('float32')  # bgr -> rgb
    img = normalize(img, mean, std)
    img = img.transpose((2, 0, 1))  # hwc -> chw
    return img[np.newaxis, :]

# ——————————————————————模型配置、预测相关函数—————————————————————————— #
def predict_config(model_file, params_file):
    '''
    函数功能：初始化预测模型predictor
    函数输入：模型结构文件，模型参数文件
    函数输出：预测器predictor
    '''
    # 根据预测部署的实际情况，设置Config
    config = Config()
    # 读取模型文件
    config.set_prog_file(model_file)
    config.set_params_file(params_file)
    # Config默认是使用CPU预测，若要使用GPU预测，需要手动开启，设置运行的GPU卡号和分配的初始显存。
    config.enable_use_gpu(500, 0)
    # 可以设置开启IR优化、开启内存优化。
    config.switch_ir_optim()
    config.enable_memory_optim()
    config.enable_tensorrt_engine(workspace_size=1 << 30, precision_mode=PrecisionType.Float32, max_batch_size=1,
                                   min_subgraph_size=5, use_static=True, use_calib_mode=False)
    predictor = create_predictor(config)
    return predictor

def predict(predictor, img):
    '''
    函数功能：初始化预测模型predictor
    函数输入：模型结构文件，模型参数文件
    函数输出：预测器predictor
    '''
    input_names = predictor.get_input_names()
    for i, name in enumerate(input_names):
        input_tensor = predictor.get_input_handle(name)
        input_tensor.reshape(img[i].shape)
        input_tensor.copy_from_cpu(img[i].copy())
    # 执行Predictor
    predictor.run()
    # 获取输出
    results = []
    # 获取输出
    output_names = predictor.get_output_names()
    for i, name in enumerate(output_names):
        output_tensor = predictor.get_output_handle(name)
        output_data = output_tensor.copy_to_cpu()
        results.append(output_data)
    return results

# ——————————————————————后处理函数—————————————————————————— #
def draw_bbox_image(frame, result, label_list, threshold=0.5):

    for res in result:
        cat_id, score, bbox = res[0], res[1], res[2:]

        if score < threshold:
            continue

        for i in bbox:
            int(i)
        xmin, ymin, xmax, ymax = bbox

        cv2.rectangle(frame, (int(xmin), int(ymin)), (int(xmax), int(ymax)), (255, 0, 255), 2)
        print('category id is {}, bbox is {}'.format(cat_id, bbox))

        try:
            label_id = label_list[int(cat_id)]
            # #cv2.putText(图像, 文字, (x, y), 字体, 大小, (b, g, r), 宽度)
            cv2.putText(frame, label_id, (int(xmin), int(ymin - 2)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 0, 0), 2)
            cv2.putText(frame, str(round(score, 2)), (int(xmin - 35), int(ymin - 2)), cv2.FONT_HERSHEY_SIMPLEX, 0.5,
                        (0, 255, 0), 2)

        except KeyError:
            pass

vio_label = [
    "未戴安全帽",         # 1
    "无人扶梯",          # 2
    "未设置安全围栏",     # 3
    "未系安全带",        # 4
    "监护缺失",          # 5
    "带电作业未按规定进行作业防护"    # 6
]

####################
#音频输出
import pyttsx3

vio_label = [
    "未戴安全帽",         # 1
    "无人扶梯",          # 2
    "未设置安全围栏",     # 3
    "未系安全带",        # 4
    "监护缺失",          # 5
    "带电作业未按规定进行作业防护"    # 6
]

####################
#音频输出
import pyttsx3

def voice(i):
    engine = pyttsx3.init()
    engine.setProperty('voice', 'zh')
    engine.say(vio_label[i])
    engine.runAndWait()

####################

def show_ch(frame, i):
    pil_img = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)  # cv2和PIL中颜色的hex码的储存顺序不同，需转RGB模式
    pilimg = Image.fromarray(pil_img)  # Image.fromarray()将数组类型转成图片格式，与np.array()相反
    draw = ImageDraw.Draw(pilimg)  # PIL图片上打印汉字
    font = ImageFont.truetype('./chinese_font.ttc', 30)
    draw.text((30, 30), vio_label[i], (255, 0, 0), font=font)
    frame = cv2.cvtColor(np.array(pilimg), cv2.COLOR_RGB2BGR)  # 将图片转成cv2.imshow()可以显示的数组格式
    # cv2.imshow("frame", frame)
    # cv2.imwrite("vio_{}.jpg".format(i + 1), frame)

    return frame

def compute_distance_bounding_box(box1, box2):
    # 首先计算两个矩形中心点
    center1 = [(box1[0] + box1[2]) / 2, (box1[1] + box1[3]) / 2]
    box1_width = abs(box1[0] - box1[2])
    box1_height = abs(box1[1] - box1[3])

    center2 = [(box2[0] + box2[2]) / 2, (box2[1] + box2[3]) / 2]
    box2_width = abs(box2[0] - box2[2])
    box2_height = abs(box2[1] - box2[3])

    dis_center = [abs(center1[0] - center2[0]), abs(center1[1] - center2[1])]

    # 两矩形不相交，在X轴方向有部分重合的两个矩形，最小距离是上矩形的下边线与下矩形的上边线之间的距离
    if (dis_center[0] < ((box1_width + box2_width) / 2)) and (dis_center[1] >= ((box1_height + box2_height) / 2)):
        min_dist = dis_center[1] - ((box1_height + box2_height) / 2)

    # 两矩形不相交，在Y轴方向有部分重合的两个矩形，最小距离是左矩形的右边线与右矩形的左边线之间的距离
    elif (dis_center[0] >= ((box1_width + box2_width) / 2)) and (dis_center[1] < ((box1_height + box2_height) / 2)):
        min_dist = dis_center[0] - ((box1_width + box2_width) / 2)

    # 两矩形不相交，在X轴和Y轴方向无重合的两个矩形，最小距离是距离最近的两个顶点之间的距离，
    # 利用勾股定理，很容易算出这一距离
    elif (dis_center[0] >= ((box1_width + box2_width) / 2)) and (dis_center[1] >= ((box1_height + box2_height) / 2)):
        delta_x = dis_center[0] - ((box1_width + box2_width) / 2)
        delta_y = dis_center[1] - ((box1_height + box2_height) / 2)
        min_dist = np.sqrt(delta_x * delta_x + delta_y * delta_y)

    # 其他情况相交，距离为0
    else:
        min_dist = 0

    return min_dist

def process_results(frame, result, threshold=0.5):
    str_id = ''
    res_list = []

    for res in result[0]:
        cat_id = res[0]
        bbox = res[2:]
        score = res[1]

        if score < threshold:
            continue

        str_id += str(int(cat_id)) + ','
        xmin, ymin, xmax, ymax = bbox

        res_list.append([int(cat_id), score, [int(xmin), int(ymin), int(xmax), int(ymax)]])

    return str_id, res_list

def vio_1(str_id):
    person = str_id.count("0") + str_id.count("1") + str_id.count("2") + str_id.count("3") + str_id.count(
        "4") + str_id.count("5")
    helmet = str_id.count("6")
    if person > 0:
        if person > helmet:
            print("未戴安全帽")

            return True

def vio_2(str_id):
    if ("7" in str_id) and ("2" in str_id) and ("3" not in str_id):
        print("无人扶梯")

        return True

def vio_3(str_id):
    if (("0" or "1") in str_id) and ("8" not in str_id):
        print("未设置安全围栏")

        return True

def vio_4(str_id):
    if ("1" in str_id):
        print("未系安全带")

        return True

def vio_5(res_list):
    person5_coord = [res[2] for res in res_list if res[0] == 4]
    print('p5_coord is', person5_coord)

    person_coord = [res[2] for res in res_list if res[0] in [0, 1, 2, 3, 5]]
    print('p_coord is', person_coord)

    if person5_coord:
        for i in person5_coord:
            for j in person_coord:
                dist = compute_distance_bounding_box(i, j)
                if dist > 15:
                    print("监护缺失")

                    return True

    #(6)带电作业未按规定进行作业防护
    ###需要识别工作票
    # if ("9" or "10" or "11") not in str_id:
    #     print("带电作业未按规定进行作业防护")
   

def all_violation_rules(str_id, res_list, frame, i):
    if vio_1(str_id):
        frame = show_ch(frame, i)
        #voice(i)

    if vio_2(str_id):
        frame = show_ch(frame, i + 1)
        #voice(i + 1)

    if vio_3(str_id):
        frame = show_ch(frame, i + 2)
        #voice(i + 2)

    if vio_4(str_id):
        frame = show_ch(frame, i + 3)
        #voice(i + 3)

    if vio_5(res_list):
        frame = show_ch(frame, i + 4)
        #voice(i + 4)

    return frame

if __name__ == '__main__':

    # 从infer_cfg.yml中读出label
    infer_cfg = open('/home/nvidia/ppyoloe_plus_crn_s_80e_coco/infer_cfg.yml')
    data = infer_cfg.read()
    yaml_reader = yaml.load(data)
    label_list = yaml_reader['label_list']
    print(label_list)

    # 配置模型参数
    model_file = '/home/nvidia/ppyoloe_plus_crn_s_80e_coco/model.pdmodel'
    params_file = '/home/nvidia/ppyoloe_plus_crn_s_80e_coco/model.pdiparams'
    # 初始化预测模型
    predictor = predict_config(model_file, params_file)

    #########################################################################################
    cap = cv2.VideoCapture('/home/nvidia/ppyoloe_plus_crn_s_80e_coco/test_video/01-1.mp4')
    

    # 创建保存视频的对象，设置编码格式，帧率，图像的宽高等
    frame_width = int(cap.get(3))
    print('frame_width is', frame_width)
    frame_height = int(cap.get(4))
    print('frame_height is', frame_height)
    frame_size = (frame_width, frame_height)
    fps = int(cap.get(5))
    print('fps is', fps)
    fourcc = cv2.VideoWriter_fourcc(*'XVID')
    video_writer = cv2.VideoWriter('output.avi', fourcc, fps, frame_size)
    #############################################################################################

    # 图像尺寸相关参数初始化
    ret, img = cap.read()
    im_size = 640
    scale_factor = np.array([im_size * 1. / img.shape[0], im_size * 1. / img.shape[1]]).reshape((1, 2)).astype(
        np.float32)
    im_shape = np.array([im_size, im_size]).reshape((1, 2)).astype(np.float32)

    while True:
        ret, frame = cap.read()
        # 预处理
        data = preprocess(frame, im_size)

        time_start = time.time()
        # 预测
        result = predict(predictor, [im_shape, data, scale_factor])
        print('Time Cost：{}'.format(time.time() - time_start), "s")

        str_id, res_list = process_results(frame, result, threshold=0.7)
        frame = all_violation_rules(str_id, res_list, frame, 0)

        draw_bbox_image(frame, result[0], label_list, threshold=0.7)

        #cv2.imshow("frame", frame)

        ###保存视频###
        if not ret:
            break
        video_writer.write(frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break`

**Comment by zhiboniu** [comment]
你好，这个具体遇到的问题是什么？等待时间太久吗？

**Comment by lkpk1994** [comment]
> 你好，这个具体遇到的问题是什么？等待时间太久吗？
就一直是那个画面，很明显好像是报错了。一直等待，inference也跑不起来。

**Comment by lkpk1994** [comment]
> 你好，这个具体遇到的问题是什么？等待时间太久吗？
