### ISSUE TITLE
VS2019 部署模型教程 detection下载链接少东西

### ISSUE THREAD

**Issue by Stillremains** [PaddlePaddle/PaddleDetection#699]
昨天我在做VS2019 部署模型时，跟着文档配置环境 发现一个错误   detection下载链接少东西 没有inference文件夹，导致教程无法进行下去，我一度懵逼，最终再使用git的detection时发现 git的是有inference的
![1](https://user-images.githubusercontent.com/48147367/82137172-48858a80-9848-11ea-9941-3edacbd7d529.png)
![2](https://user-images.githubusercontent.com/48147367/82137176-4ae7e480-9848-11ea-8efe-fd4a4b495b7f.png)
![3](https://user-images.githubusercontent.com/48147367/82137178-4cb1a800-9848-11ea-8b8b-c1b3a38647a4.png)

**Comment by qingqing01** [comment]
@Stillremains 感谢反馈，在master分支已重构预测代码，修改了教程。

**Comment by qingqing01** [comment]
已修复，暂且关闭此issue。
