### ISSUE TITLE
将推理的结果按类名进行切割分类

### ISSUE THREAD

**Issue by Vergissmeinnic** [PaddlePaddle/PaddleDetection#6990]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

例如，我的模型是检测猫和狗的，在我预测一张图片后，能否将猫和狗的部分单独切分出来，并且放入两个不同的文件夹？

**Comment by zhiboniu** [comment]
你好，你的需求是简单的python处理过程，请参考python和opencv使用方法解决
