### ISSUE TITLE
onnx转换后无法读取

### ISSUE THREAD

**Issue by qinlihaoWork** [PaddlePaddle/PaddleDetection#6994]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用paddle2onnx转换picodet模型后，使用opencv的dnn读取onnx模型，出现如下报错。
![image](https://user-images.githubusercontent.com/111327813/191505785-d4ab1d7d-c33c-44d4-b39d-cd99faca832b.png)
请问是模型导出的问题么？

**Comment by zhiboniu** [comment]
你好，请参考这部分文档转换查onnx模型并检查是否正常
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/third_engine

**Comment by qinlihaoWork** [comment]
> 你好，请参考这部分文档转换查onnx模型并检查是否正常 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/third_engine

你好，按照教程重新进行onnx转换，在转trt engine时还是报错，报错信息如下。
![image](https://user-images.githubusercontent.com/111327813/191907535-e4f22428-dd1d-4070-b505-7ff6f1cf1ba0.png)
![image](https://user-images.githubusercontent.com/111327813/191907560-19e361e1-f6cf-40f8-b441-b7f77f8171f3.png)

尽管可以生成onnx模型，但是运行onnx_custom时遇到以下错误
![image](https://user-images.githubusercontent.com/111327813/191907692-7bda5af5-a61b-46a6-956b-453585fcbd0b.png)

**Comment by dengqizhou30** [comment]
opencv还不支持onnx的一些模型算法，建议不要在这个方向上浪费时间，直接用onnxruntime来跑导出的模型，

**Comment by qinlihaoWork** [comment]
> opencv还不支持onnx的一些模型算法，建议不要在这个方向上浪费时间，直接用onnxruntime来跑导出的模型，

谢谢，已经跑通了
