### ISSUE TITLE
ppyoloe 在导出模型时，如何去掉scale_factor相关分支？

### ISSUE THREAD

**Issue by wenston2006** [PaddlePaddle/PaddleDetection#6996]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我将ppyoloe模型导出转为onnx模型在某平台进行测试，该平台支持的onnx输入仅有图片一个参数，因此由于yoloe的输入包括图片image和scale_factor两个参数，现在我需要将scale_factor相关的计算分支从导出的模型中去掉，放在模型外进行后处理;请问应该如何操作？需要修改哪些代码？

**Comment by wangxinxin08** [comment]
可以考虑打开这个选项，剩余的后处理需要自己实现下

**Comment by QingYuan-L** [comment]
我也遇到这个问题了，请问问题解决了吗？

**Comment by Luna2199** [comment]
> 可以考虑打开这个选项，剩余的后处理需要自己实现下

请问是打开哪个选项？我也想在导出onnx模型时去除`scale_factor`输入节点。
