### ISSUE TITLE
No module named 'ppdet'

### ISSUE THREAD

**Issue by WuYue99** [PaddlePaddle/PaddleDetection#70]
No module named 'ppdet'
按照文件安装好之后提示这个，明明有ppdet这个文件夹啊。
请问该怎么解决。

**Comment by FDInSky** [comment]
进入PaddleDetection目录下，有没有执行export PYTHONPATH='pwd':$PYTHONPATH ?

**Comment by qingqing01** [comment]
@WuYue99  主要需要设置`PYTHONPATH`. 请问是否还有问题？

**Comment by liuchangji** [comment]
实测，在paddledet目录下输入这个好使
export PYTHONPATH=.:$PYTHONPATH
