### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by lhy823436493** [PaddlePaddle/PaddleDetection#700]
已经制作好了自己的VOC数据集，怎么放到PaddleDetection上进行训练。

**Comment by qingqing01** [comment]
@lhy823436493  在您选定的模型YML配置中，指定数据路径即可，参考： https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/READER.md#%E9%85%8D%E7%BD%AE%E5%8F%8A%E8%BF%90%E8%A1%8C 


加入是YOLOv3-DarkNet，在 https://github.com/PaddlePaddle/PaddleDetection/blob/master/configs/yolov3_darknet_voc.yml#L74 替换路径即可。

**Comment by qingqing01** [comment]
@lhy823436493 文档里也更新了 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md  如果没问题的话，麻烦关闭下issue
