### ISSUE TITLE
飞行器跟踪案例

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/PaddleDetection#7007]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在页面介绍中看到与飞行器跟踪的案例动态图，请问在哪里可以找到相应的数据集和跟踪设置代码呢，非常感谢。

**Comment by qiyuezhiguang** [comment]
此外，小目标识别中加入了切图识别，其中一个难点就是各个子图之间还要进行NMS，不知道对应的C++部署是否支持切图预测？

**Comment by nemonameless** [comment]
[gmot-40-airplane](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/mot/fairmot#results-on-gmot-40-airplane-subset) 是fairmot跟踪模型的应用。
小目标切图拼图暂时还不支持CPP部署，SAHI库也没有计划支持CPP。
