### ISSUE TITLE
YOLOv6 又更新了2.0版本 各项指标行业第一 YOLOv6 has been updated to version 2.0, the indicators are the first in the industry！

### ISSUE THREAD

**Issue by Stephanie11111** [PaddlePaddle/PaddleDetection#7008]
### 问题描述 Please describe your issue

**中文版：**

**Tech Report👉[YOLOv6: A Single-Stage Object Detection Framework for Industrial Applications](https://arxiv.org/abs/2209.02976)。**

🌟YOLOv6 2.0版本做了哪些更新？🌟

【量身定制的量化方案】轻量级网络全面升级，量化版模型 YOLOv6-S 的推理速度达到了 869 FPS。

【性能更强的全系列模型】推出了综合性能优异的中大型网络（YOLOv6-M/L），丰富了YOLOv6网络系列，其中，YOLOv6-M/L 在 COCO 上检测精度（AP）分别达到 49.5%/52.5%，在 T4卡上推理速度分别可达233/121 FPS（batch size =32）。

【完备的开发支持和多平台部署适配】同时支持 GPU（TensorRT）、CPU（OPENVINO）、ARM（MNN、TNN、NCNN）等不同平台的部署。

这么用心研发的高水准产品，还不赶紧Star收藏上车！传送门👉https://github.com/meituan/YOLOv6

**English Version**

**Tech Report👉[YOLOv6: A Single-Stage Object Detection Framework for Industrial Applications](https://arxiv.org/abs/2209.02976).**

🌟What updates have been made to YOLOv6 version 2.0?🌟

【Customized quantization methods】 The lightweight networks are fully upgraded, and the quantized version of YOLOv6-S reaches a throughput of 869 FPS.

【Release M/L models and update N/T/S models with enhanced performance】YOLOv6-M/L achieves excellent performance with 49.5%/52.5%  COCO AP and a throughput of  233/121 FPS at a batch size of 32 on a T4 GPU, respectively.

【Complete deployment support and adaptation on multi-platforms 】Support different platforms such as GPU (TensorRT), CPU (OPENVINO) and ARM (MNN, TNN, NCNN) , etc.

Don't hesitate to Star such a high level product! 👉https://github.com/meituan/YOLOv6

**Comment by lyuwenyu** [comment]
👍
以后可以直接用paddle和paddledetecion做模型， 欢迎加入paddle社区玩耍 😬

**Comment by leiqing1** [comment]
欢迎把YOLOv6贡献到PaddleDetection中来

**Comment by floveqq** [comment]
What amazing news, I suggest you also make a formal notification to yolov5, yolo7, yolox, mmyolo hahaha

**Comment by YixinKristy** [comment]
很高兴看到您对YOLOv6最新进展的同步，PaddleDetection团队持续关注着目标检测领域的最新进展，也同步关注到了YOLOv6的发布与更新，并基于飞桨实现了[YOLOv6](https://github.com/nemonameless/PaddleDetection_YOLOSeries/tree/release/2.5/configs/yolov6) ，非常欢迎美团团队后续基于飞桨进行算法的迭代更新👏👏👏

与此同时，PaddleDetection近期推出的[PP-YOLOE+](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/ppyoloe)在COCO数据集达到**mAP 54.9%，149.2FPS (bs=1)**，端到端**训练与推理**速度均提升**3倍**，在多个下游任务场景验证**泛化性显著提升**，最高精度**提高8%**，如果愿意的话，可以将[PP-YOLOE+](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/ppyoloe)放入YOLOv6的repo中进行对比。

📖详细文档可以参考
PP-YOLOE+：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/ppyoloe/README_cn.md

YOLO作为目标检测领域最核心热门的算法系列，PaddleDetection将会持续关注业界学术研究者的成果发布与最新动态，同时会不断打磨优化PP-YOLO系列的算法效果，为目标检测的发展做出贡献。

另外，看到美团YOLOv6同样受邀参加YOLO Vision的圆桌讨论，非常期待届时的交流，更希望后续能有机会一起针对检测领域做进步的研讨与合作：）

以上，
2022年9月23日
飞桨PaddleDetection产研团队

---

Thanks for updating the latest work of YOLOv6. PaddleDetection pays close attention to the latest progress in Object Detection. At the same time, we has noticed that the latest version release of YOLOv6 and reproduced [YOLOv6](https://github.com/nemonameless/PaddleDetection_YOLOSeries/tree/release/2.5/configs/yolov6) based on PaddlePaddle. Welcome to optimize YOLOv6 based on PaddlePaddle in the future👏👏👏


Meanwhile，PaddleDetection recently released [PP-YOLOE+](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/ppyoloe), which has a performance of **mAP 54.9%，149.2FPS (bs=1)** on COCO. And the end to end training and inference speed speedups of **3x**. Moreover, it has been proved that PP-YOLOE+ improved the robustness of the downstream tasks by **8% increased in mAP.** 

Feel free to add [PP-YOLOE+](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/ppyoloe) in the comparison list of YOLOv6 repo.


📖More Details:
PP-YOLOE+: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/ppyoloe/README_cn.md

YOLO as the most core and popular algorithm series in the Object Detection, PaddleDetection will continue to pay attention to the release of results and the latest developments of academic researchers in the industry. At the same time we will continue to optimize the effect of the algorithm of PP-YOLO series to contribute to the development of Object Detection.

In addition, seeing that Meituan YOLOv6 is also invited to participate in the panel session of YOLO Vision, we are looking forward to the communicate with you at that time, and we hope that we can have the opportunity to further discuss and cooperate in the future :)

Best，
Sep 23th, 2022
PaddleDetection Team

**Comment by floveqq** [comment]
> What amazing news, I suggest you also make a formal notification to yolov5, yolo7, yolox, mmyolo hahaha

@Stephanie11111  so interesting hahaha
https://github.com/Megvii-BaseDetection/YOLOX/issues/1520
