### ISSUE TITLE
引用数据集的模型参数去训练另一个数据集

### ISSUE THREAD

**Issue by L2439931749** [PaddlePaddle/PaddleDetection#701]
目标检测里面我想要一个数据集训练好的模型参数，来接着训练我的另一个数据集，应该改yml里面的那个参数呀
pretrain_weights
还是 weights

pretrain_weights里面的模型参数怎么更新呀

**Comment by qingqing01** [comment]
@L2439931749  指定`pretrain_weights`参数，参考： https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md#paddledetection%E8%BF%9B%E8%A1%8C%E8%BF%81%E7%A7%BB%E5%AD%A6%E4%B9%A0    如果是RCNN模型，ResNet的骨干网络的话，默认stage1和stage2的参数不更新，其他参数都更新。 其他模型的话，没有特殊设置的话，参数都更新。
