### ISSUE TITLE
solov2 推断标签错误和部署问题

### ISSUE THREAD

**Issue by Oink98** [PaddlePaddle/PaddleDetection#7011]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

1、我用自己的数据集训练后，infer的结果标签是coco数据集的标签，我应该修改什么部分能够让标签正确显示

2、我希望把solo推断的掩膜部分单独作为图像结果输出，如何修改代码

3、请问有没有solov2模型在安卓端部署的教程或者流程，官方模型导出的代码，导出后我没找到继续进行部署的方法

**Comment by lllllps** [comment]
I have the same problem, have u fixed this yet?

**Comment by nemonameless** [comment]
1.需要更改TestDataset的anno路径设置，找不到json标注就会默认使用COCO，有warning打印的请注意看
2.把掩码部分numpy转cv2或PIL保存成图片就行
3.暂无

**Comment by springsha** [comment]
您好 对于问题：我希望把solo推断的掩膜部分单独作为图像结果输出，如何修改代码
“2.把掩码部分numpy转cv2或PIL保存成图片就行” 
 @请问可以指明具体修改那一部分代码可以吗（科研小白）。 @Oink98 @nemonameless
