### ISSUE TITLE
MTMC车辆跟踪效果不理想

### ISSUE THREAD

**Issue by Luna2199** [PaddlePaddle/PaddleDetection#7012]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

**`python：3.6.13`
`paddle : 2.3.0 `
`PaddleDetection : v2.4.0`**
**参考资料:** [https://aistudio.baidu.com/aistudio/projectdetail/3469295](https://aistudio.baidu.com/aistudio/projectdetail/3469295)
**终端执行**：`python deploy/pptracking/python/mot_sde_infer.py --model_dir=output_inference/ppyolov2_r50vd_dcn_365e_aic21mtmct_vehicle/ --reid_model_dir=output_inference/deepsort_pplcnet_vehicle/ --mtmct_dir=./dataset/mtmct-demo --device=GPU --mtmct_cfg=deploy/pptracking/python/mtmct_cfg.yml --scaled=True --save_mot_txts --save_images --tracker_config=deploy/pptracking/python/tracker_config.yml
`
**实验效果:**
![00082](https://user-images.githubusercontent.com/21285692/191936768-cff52f92-57fe-4c27-83b8-ad9a10c60f67.jpg)
![00082](https://user-images.githubusercontent.com/21285692/191937095-7722377c-8214-4e82-99f0-b6dc3dc75591.jpg)

请问是什么原因导致了这种情况，需要怎么调整？？

**Comment by nemonameless** [comment]
换用vehicle里的车辆模型试试，这个教程对应的应该是 PaddleDetection的release/2.3分支。
 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/pipeline#pp-vehicle-1
