### ISSUE TITLE
请问摔倒检测的行为识别算法可以接收rtsp/rtfp视频流吗?

### ISSUE THREAD

**Issue by sweetboxwwy** [PaddlePaddle/PaddleDetection#7017]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问摔倒检测的行为识别算法可以接收rtsp/rtfp视频流吗?入参camera_id似乎只接受int值

**Comment by zhiboniu** [comment]
支持的，rtsp视频流的使用方法参考PP-Human快速开始页面：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/pipeline/docs/tutorials/PPHuman_QUICK_STARTED.md
![image](https://user-images.githubusercontent.com/31800336/192230711-aafd96f2-d95d-4462-aa0e-98f5a9f2c8aa.png)

**Comment by sweetboxwwy** [comment]
> 支持的，rtsp视频流的使用方法参考PP-Human快速开始页面： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/pipeline/docs/tutorials/PPHuman_QUICK_STARTED.md ![image](https://user-images.githubusercontent.com/31800336/192230711-aafd96f2-d95d-4462-aa0e-98f5a9f2c8aa.png)

但是好像用视频流的话，output下会生成一个main文件，也打不开，而且大概识别20秒左右就会断掉

**Comment by sweetboxwwy** [comment]
> > 支持的，rtsp视频流的使用方法参考PP-Human快速开始页面： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/pipeline/docs/tutorials/PPHuman_QUICK_STARTED.md ![image](https://user-images.githubusercontent.com/31800336/192230711-aafd96f2-d95d-4462-aa0e-98f5a9f2c8aa.png)
> 
> 但是好像用视频流的话，output下会生成一个main文件，也打不开，而且大概识别20秒左右就会断掉

并且GPU利用率只有14%

**Comment by LeeGeong** [comment]
我也是rtsp只能坚持10秒
