### ISSUE TITLE
跑官网情感分析案例，出现错误

### ISSUE THREAD

**Issue by LJJ1234567** [PaddlePaddle/PaddleDetection#703]
![QQ图片20200517135818](https://user-images.githubusercontent.com/65484382/82138703-06af1100-9855-11ea-9bb4-9d05de3da802.png)
![02](https://user-images.githubusercontent.com/65484382/82138704-0d3d8880-9855-11ea-89a1-94d8418a0ac4.png)
![03](https://user-images.githubusercontent.com/65484382/82138706-0f9fe280-9855-11ea-81ed-cb32ccbbab9c.png)

完全复制的案例代码，跑测试时，出现以下错误，不知道问题出在哪里了

**Comment by qingqing01** [comment]
@LJJ1234567 非检测的issue，可以去Paddle repo下提问。
