### ISSUE TITLE
在做头盔检测训练是出现loss nan，什么原因？

### ISSUE THREAD

**Issue by ionescofung** [PaddlePaddle/PaddleDetection#7035]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在做头盔检测训练是出现loss变为空值，什么原因？
![1921664262683_ pic](https://user-images.githubusercontent.com/55121158/192470374-2c740812-70ab-41c6-b1d0-c0a15d667e1e.jpg)

**Comment by nemonameless** [comment]
报bug请按模板提问谢谢。loss nan了，大概率是lr没调整好，默认lr是按8卡来算的。
https://github.com/PaddlePaddle/PaddleDetection/search?q=loss+nan&type=issues
