### ISSUE TITLE
paddle human detection model export to tensorrt

### ISSUE THREAD

**Issue by liuchangf** [PaddlePaddle/PaddleDetection#7043]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

按照以下截图的文档，可正常导出tensorRT模型，但是如何在c++环境下使用[EfficientNMS_TRT](https://github.com/NVIDIA/TensorRT/tree/main/plugin/efficientNMSPlugin) OP ，请提供教程

![图片](https://user-images.githubusercontent.com/31433358/192715799-987227a8-103c-45b6-a685-0d0ce6e229f5.png)

若在导出过程中未使用 exclude_nms=True 参数，即：
python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_300e_coco.pdparams trt=True exclude_nms=True

则在转换tensorRT 过程中，报下图错误：
![图片](https://user-images.githubusercontent.com/31433358/192716790-7bf72352-74b9-4c93-9d0f-08c41e76cbc9.png)

请提供不包含NonZero op 的onnx模型(所有节点均兼容tensorRT)，方便用户能够导出到tensorRT。谢谢

**Comment by lyuwenyu** [comment]
paddle, paddle2onnx, 还有tensorrt版本是什么

**Comment by liuchangf** [comment]
经过测试，发现tensorRT release版本已编译[EfficientNMS_TRT] OP ，可以正常使用 ，暂时未发现其它问题 。
