### ISSUE TITLE
PP-YOLOE与picodet的c++后处理差别大吗？

### ISSUE THREAD

**Issue by 205418367** [PaddlePaddle/PaddleDetection#7047]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PP-YOLOE与picodet的c++后处理差别大吗？

**Comment by lyuwenyu** [comment]
差别不大  应该后处理是一样的

**Comment by 205418367** [comment]
好的
