### ISSUE TITLE
paddle export to hailo-8 tappas

### ISSUE THREAD

**Issue by MyraBaba** [PaddlePaddle/PaddleDetection#7050]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi,

there is a growing number of AI chips on the market. is there any work with this Hailo-8 chip with paddle detections ?

What is the best way to export visdrone model to hailo-8 ?

as ie : https://github.com/hailo-ai/hailo_model_zoo/blob/master/hailo_models/vehicle_detection/docs/TRAINING_GUIDE.md

**Comment by ghostxsl** [comment]
You can go to PaddleLite to mention the issue： https://github.com/PaddlePaddle/Paddle-Lite/issues
