### ISSUE TITLE
训练自己的voc数据集进行infer报错

### ISSUE THREAD

**Issue by xxPete** [PaddlePaddle/PaddleDetection#7051]
### 问题描述 Please describe your issue

Traceback (most recent call last):
  File ".\tools\infer.py", line 226, in <module>
    main()
  File ".\tools\infer.py", line 222, in main
    run(FLAGS, cfg)
  File ".\tools\infer.py", line 187, in run
    visualize=FLAGS.visualize)
  File "D:\Project\PaddleDetection\ppdet\engine\trainer.py", line 822, in predict
    self.dataset.set_images(images)
AttributeError: 'VOCDataSet' object has no attribute 'set_images'

# 基于官方教程的roadsign.yml文件，就改了一个datssets，其他的都没动
_BASE_: [
  '../datasets/demo.yml',
  '../runtime.yml',
  '_base_/optimizer_40e.yml',
  '_base_/yolov3_mobilenet_v1.yml',
  '_base_/yolov3_reader.yml',
]
pretrain_weights: https://paddledet.bj.bcebos.com/models/yolov3_mobilenet_v1_270e_coco.pdparams
weights: output/yolov3_mobilenet_v1_roadsign/model_final

YOLOv3Loss:
  ignore_thresh: 0.7
  label_smooth: true

# demo.yml
metric: VOC
map_type: 11point
num_classes: 11

TrainDataset:
  !VOCDataSet
    dataset_dir: D:/Dukto/927dataset/need_enhance/result
    anno_path: train_list.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !VOCDataSet
    dataset_dir: D:/Dukto/927dataset/need_enhance/result
    anno_path: val_tiny.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !ImageFolder
    anno_path: D:/Dukto/927dataset/need_enhance/result/label_list.txt

**Comment by ghostxsl** [comment]
<img width="677" alt="image" src="https://user-images.githubusercontent.com/23647349/192930554-ff01c0a4-f0e8-4468-9fc6-357aa99b2554.png">
你这个里面的TestDataset和EvalDataset写反了

**Comment by xxPete** [comment]
>
