### ISSUE TITLE
Paddlex训练后导出的模型，在Paddle Detection里可以进行调用并实现推理吗

### ISSUE THREAD

**Issue by xxPete** [PaddlePaddle/PaddleDetection#7053]
### 问题描述 Please describe your issue

有个需求，之前用paddlx训练的模型，需要在paddledetection里进行推理，我用Paddle Detection/tools/infer.py进行尝试的时候发现paddlx经过export_inference后的模型没有infer_cfg.yml文件，无法运行，看了很多地方，没发现类似的问题，来请教一下
### paddlex --export_inference后的文件内容如下
- .success
- model.pdiparams
- model.pdiparams.info
- model.pdmodel
- model.yml
- pipeline.yml
### paddledetection export后的文件内容如下
- infer_cfg.yml
- model.pdiparams
- model.pdiparams.info
- model.pdmodel

**Comment by ghostxsl** [comment]
可以用PaddleDetection再训练一下，或者去PaddlX下提issue
