### ISSUE TITLE
训练数据裁剪

### ISSUE THREAD

**Issue by LeFuGang** [PaddlePaddle/PaddleDetection#7054]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

注意 ： 在实际使用的预测过程中，使用的是单人图像进行预测，**因此在训练过程中建议将图像裁剪为单人图像**，再进行烟头检测框的标注，以提升准确率。
你好，这是《基于人体id的检测模型开发》中的一句话，我想咨询下这个图像裁剪是直接根据人的box裁剪下来吗？还是说需要有一些tricks；
比如我想识别是否佩戴安全帽这个场景，我是否需要将人先检测出来，然后裁剪出来一个个识别是否佩戴安全帽。

**Comment by zhiboniu** [comment]
嗯，根据人的box裁剪就好了
