### ISSUE TITLE
paddledetec部署在centos8出现的问题

### ISSUE THREAD

**Issue by asdadadaada** [PaddlePaddle/PaddleDetection#7058]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

在centos8上部署paddledetection中ppyolov2_r50vd_dcn_voc的时运行build.sh出现的错误
![QQ图片20221001143627](https://user-images.githubusercontent.com/94736950/193396331-b2793336-cf70-4653-809f-fab7418f2548.png)
这是打印出的日志
![image](https://user-images.githubusercontent.com/94736950/193396407-95544388-052b-423d-8d50-9203e28d35c4.png)
也曾自己手动添加yaml-cpp没有用。paddle预测库是https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html
第一个。

### 复现环境 Environment

系统：centos8
gcc：8.2
cmake：3.15+
使用CPU没有下载CUDA和cudnn
opencv：4.6.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
环境问题，curl库没有支持https，可以baidu一下有很多这方面blog，可以跟着解决一下
