### ISSUE TITLE
训练时老是莫名中断，是什么原因

### ISSUE THREAD

**Issue by Dekadenc** [PaddlePaddle/PaddleDetection#7059]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

运行环境如下：
![image](https://user-images.githubusercontent.com/102035987/193432276-b72b2c59-1e20-4cef-93cf-612e50243a05.png)
1.当训练到中途时老是显示内存溢出，之前训练时都没有这个情况，请问是什么原因？
![252d120a0d44d5ce9a3d6186216f5cf](https://user-images.githubusercontent.com/102035987/193432295-8abb38d4-797c-4d39-9239-2798fb6478ac.png)
实验语句如下：
![image](https://user-images.githubusercontent.com/102035987/193432309-4132e12a-f84e-45ff-90cb-bcd0745eccef.png)
2.有时候运行时浏览器又会莫名崩溃，这和BML有关吗？
![image](https://user-images.githubusercontent.com/102035987/193432331-c1e78a70-a03f-409c-b041-b66c41967c07.png)

**Comment by zhiboniu** [comment]
先换个版本2.3.2试试呢，paddledetection也可以换成2.5版本试试看。看起来是有数据没有释放导致了溢出
