### ISSUE TITLE
速度测速时报错

### ISSUE THREAD

**Issue by NwTbbetter** [PaddlePaddle/PaddleDetection#7062]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

在使用Paddle Inference且使用TensorRT进行测速时，报这个错误是什么意思呀

```
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: Permute
--------------------------------------------
Traceback (most recent call last):
  File "deploy/python/infer.py", line 1032, in <module>
    main()
  File "deploy/python/infer.py", line 979, in main
    output_dir=FLAGS.output_dir)
  File "deploy/python/infer.py", line 118, in __init__
    delete_shuffle_pass=delete_shuffle_pass)
  File "deploy/python/infer.py", line 880, in load_predictor
    predictor = create_predictor(config)
ValueError: (InvalidArgument) Pass preln_embedding_eltwise_layernorm_fuse_pass has not been registered.
  [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/pass.h:242)

```

### 复现环境 Environment

- Linux
- paddle:2.3.1
- python:3.7.13

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
请先确保安装了带trt功能的paddle版本。
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python

**Comment by NwTbbetter** [comment]
> 请先确保安装了带trt功能的paddle版本。 https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python

如果不使用trt会报这样的错误

```
Traceback (most recent call last):
  File "deploy/python/infer.py", line 1032, in <module>
    main()
  File "deploy/python/infer.py", line 1005, in main
    save_results=FLAGS.save_results)
  File "deploy/python/infer.py", line 370, in predict_image
    result_warmup = self.postprocess(inputs, result)  # warmup
  File "deploy/python/infer.py", line 155, in postprocess
    if sum(np_boxes_num) <= 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

**Comment by nemonameless** [comment]
> > 请先确保安装了带trt功能的paddle版本。 https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python
> 
> 如果不使用trt会报这样的错误
> 
> ```
> Traceback (most recent call last):
>   File "deploy/python/infer.py", line 1032, in <module>
>     main()
>   File "deploy/python/infer.py", line 1005, in main
>     save_results=FLAGS.save_results)
>   File "deploy/python/infer.py", line 370, in predict_image
>     result_warmup = self.postprocess(inputs, result)  # warmup
>   File "deploy/python/infer.py", line 155, in postprocess
>     if sum(np_boxes_num) <= 0:
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
> ```

请补充你的运行命令谢谢。
导出模型命令里加了exclude_nms=True是导出给测速用的，测速的话运行deploy/python/infer.py的命令还要加--run_benchmark=True。
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/modeling/heads/ppyoloe_head.py#L383
#7060

**Comment by NwTbbetter** [comment]
> > > 请先确保安装了带trt功能的paddle版本。 https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python
> > 
> > 
> > 如果不使用trt会报这样的错误
> > ```
> > Traceback (most recent call last):
> >   File "deploy/python/infer.py", line 1032, in <module>
> >     main()
> >   File "deploy/python/infer.py", line 1005, in main
> >     save_results=FLAGS.save_results)
> >   File "deploy/python/infer.py", line 370, in predict_image
> >     result_warmup = self.postprocess(inputs, result)  # warmup
> >   File "deploy/python/infer.py", line 155, in postprocess
> >     if sum(np_boxes_num) <= 0:
> > ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
> > ```
> 
> 请补充你的运行命令谢谢。 导出模型命令里加了exclude_nms=True是导出给测速用的，测速的话运行deploy/python/infer.py的命令还要加--run_benchmark=True。 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/modeling/heads/ppyoloe_head.py#L383 #7060

模型导出：
```
python tools/export_model.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml -o weights=/home/yaozhuohan/bxy/data_434.pdparams exclude_nms=True

Params:  Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=False,[7.63683701])
[10/07 23:46:40] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/yaozhuohan/bxy/data_434.pdparams
[10/07 23:46:40] ppdet.engine INFO: Export inference config file to output_inference/ppyoloe_plus_crn_s_80e_coco/infer_cfg.yml
[10/07 23:46:48] ppdet.engine INFO: Export model and saved in output_inference/ppyoloe_plus_crn_s_80e_coco
```

速度测试：
```
 CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/ppyoloe_plus_crn_s_80e_coco --image_file=/home/yaozhuohan/bxy/demo/tiexiu.jpg --run_mode=paddle --device=gpu --run_benchmark=True
```

**Comment by NwTbbetter** [comment]
请问这个问题应该怎么解决？

**Comment by NwTbbetter** [comment]
> > > 请先确保安装了带trt功能的paddle版本。 https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python
> > 
> > 
> > 如果不使用trt会报这样的错误
> > ```
> > Traceback (most recent call last):
> >   File "deploy/python/infer.py", line 1032, in <module>
> >     main()
> >   File "deploy/python/infer.py", line 1005, in main
> >     save_results=FLAGS.save_results)
> >   File "deploy/python/infer.py", line 370, in predict_image
> >     result_warmup = self.postprocess(inputs, result)  # warmup
> >   File "deploy/python/infer.py", line 155, in postprocess
> >     if sum(np_boxes_num) <= 0:
> > ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
> > ```
> 
> 请补充你的运行命令谢谢。 导出模型命令里加了exclude_nms=True是导出给测速用的，测速的话运行deploy/python/infer.py的命令还要加--run_benchmark=True。 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/modeling/heads/ppyoloe_head.py#L383 #7060

请问这个问题该怎么解决？

**Comment by exceedTu** [comment]
> 请先确保安装了带trt功能的paddle版本。 https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python

这个链接打开是空白，如下图：
![image](https://user-images.githubusercontent.com/110536580/198456876-36a5f468-81b9-4974-a355-5c0e5a264baa.png)
