### ISSUE TITLE
ppyoloe替换一些部分导致，map(29epoch)=70%,map(39epoch)=0.09%

### ISSUE THREAD

**Issue by fan-min-97** [PaddlePaddle/PaddleDetection#7063]
### 问题描述 Please describe your issue

1.ppyoloe-m的模型配置文件中的act修改为silu
--------------------------
CustomCSPPAN:
  out_channels: [768, 384, 192]
  stage_num: 1
  block_num: 3
  act: 'silu'
  spp: true
-------------------------------
2.替换了backbone中的注意力机制，由EffectiveSELayer替换成Att
-------------------------------
        if attn:
            # self.attn = EffectiveSELayer(ch_mid, act='hardsigmoid')
            self.attn = Att(ch_mid)
        else:
            self.attn = None

-------------------------------

以上俩种情况是跑的俩次实验，都存在精度突然趋于0的情况，这是啥原因呢？
![image](https://user-images.githubusercontent.com/71055342/194190981-e3ecb5fc-abbf-46ea-956f-a59cbd54ec75.png)

![image](https://user-images.githubusercontent.com/71055342/194191142-791a13d1-5aa4-42f1-ab7c-ed0e85e0fc7a.png)

**Comment by nemonameless** [comment]
为更好地了解具体情况以便解决，请按模板提问谢谢。
https://github.com/PaddlePaddle/PaddleDetection/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml
