### ISSUE TITLE
部署模型导出ONNX格式，支持onnxruntime-gpu 1.4.0嘛？

### ISSUE THREAD

**Issue by ZhangLe-fighting** [PaddlePaddle/PaddleDetection#7067]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

# 运行环境
cuda: 10.1 
cudnn: 7.6.5
python: 3.6
onnxruntime-gpu 1.4.0

# ONNX导出命令
![image](https://user-images.githubusercontent.com/55420158/194693757-11a60824-10d9-4659-9ec2-cfaca895ec27.png)

# 使用python推理报错
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: Unknown model file format version.

**Comment by zhiboniu** [comment]
看报错是说模型文件格式不对，先确认下问题如果没错的话再确认下onnx版本之间兼容性问题吧。
