### ISSUE TITLE
PP-PicoDet全量化模型是否支持瑞芯微-开发板3568？

### ISSUE THREAD

**Issue by SigmaLGX** [PaddlePaddle/PaddleDetection#7069]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我训练了PicoDet-S-NPU全量化模型，使用deploy/python/infer.py验证效果较好。
使用picodet2onnx转换为onnx，接着使用RKNN的1.3.0版本rknn_toolkit2将onnx转换为.rknn模型。 推断出来的结果跟原始结果有偏差

硬件为RK3568板子

**Comment by lyuwenyu** [comment]
理论上是没有问题吧，转出来的onnx有测过正常嘛

**Comment by yghstill** [comment]
@SigmaLGX 转到onnx上的是FP32模型还是量化模型？

**Comment by SigmaLGX** [comment]
@lyuwenyu  onnx模型测试过是正常的，跟rknn跑出来的结果不一样

**Comment by SigmaLGX** [comment]
@yghstill   FP32的模型

**Comment by SigmaLGX** [comment]
模型导出命令：
`python tools/export_model.py  --output_dir=./output/picodet_s_320_192_RoadDamage_lossweight_relabel_bgr_npu/   -c configs/picodet/picodet_s_320_192_RoadDamage_lossweight_relabel_bgr_npu.yml  -o weights=output/picodet_s_320_192_RoadDamage_lossweight_relabel_bgr_npu/model_final.pdparams   export.benchmark=True export.nms=False
`
onnx模型转换命令：
`paddle2onnx --model_dir version/v0.0.9/picodet_s_320_192_RoadDamage_lossweight_relabel_bgr_mobilenetv3/    --model_filename model.pdmodel  --params_filename model.pdiparams  --opset_version 12  --save_file  version/v0.0.9/picodet_s_320_192_RoadDamage_lossweight_relabel_bgr_mobilenetv3.onnx`

RKNN模型转换命令：

`

class RKNNModel():
    def __init__(self, onnx_path,rknn_path,export_rknn=True,do_quantization=False,dataset=None):
        self.rknn = RKNN()


        print("??????????????????????????????????????")

        # pre-process config
        print('--> config model')
        # rknn.config(mean_values=[128, 128, 128], std_values=[128, 128, 128])
        # rknn.config(mean_values=[0., 0., 0.], std_values=[0.00392156862745, 0.00392156862745, 0.00392156862745])
        self.rknn.config(mean_values=[123.675, 116.28 , 103.53 ], std_values=[58.395, 57.12 , 57.375])
        print('done')

        # Load tensorflow model
        print('--> Loading model')
        ret = self.rknn.load_onnx(model=onnx_path)

        if ret != 0:
            print('Load onnx failed!')
            exit(ret)
        print('done')

        # Build model
        print('--> Building model')
        if do_quantization:
            ret = self.rknn.build(do_quantization=True, dataset=dataset)
        else:
            ret = self.rknn.build(do_quantization=False, dataset='./dataset.txt')
        if ret != 0:
            print('Build lanedet failed!')
            exit(ret)
        print('done')

        if export_rknn:
            # Export rknn model
            print('--> Export RKNN model')
            ret = self.rknn.export_rknn(rknn_path)
            if ret != 0:
                print('Export 33_lane_det.rknn failed!')
                exit(ret)
            print('done')

        # # load RKNN model
        # print('--> Load RKNN model')
        # ret = self.rknn.load_rknn(rknn_path)
        # if ret != 0:
        #     print('Load RKNN model failed')
        #     exit(ret)
        # print('done')

        # init runtime environment
        print('--> Init runtime environment')
        # run on RK3399Pro/RK1808 with Debian OS, do not need specify target.
        # if platform.machine() == 'aarch64':
        #     target = None
        # else:
        #     target = 'rk3568'
        ret = self.rknn.init_runtime()
        if ret != 0:
            print('Init runtime environment failed')
            exit(ret)
        print('done')
`
