### ISSUE TITLE
请教关于训练picodet算法时的负样本选取问题

### ISSUE THREAD

**Issue by 205418367** [PaddlePaddle/PaddleDetection#7070]
### 问题确认 Search before asking

- [ ] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

想知道picodet算法训练时的负样本是随机选取还是其他办法？因为我的训练数据中有很多遗漏的目标（即未标注的正样本），这对训练和预测产生多大影响？

**Comment by zhiboniu** [comment]
正样本没有标注会影响模型训练效果，如果数量很多的话影响会比较大
