### ISSUE TITLE
部署det训练好的模型，deploy/cpp

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/PaddleDetection#7072]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

以下是报错，不知道怎么生成不了`CMakeFiles/main.dir/src/main.cc.o`这个文件，已经卡了很久了希望大佬们帮忙解决一下这个部署问题。

 ```
-- Build files have been written to: /root/deploy_water/cpp/build
[  7%] Creating directories for 'ext-yaml-cpp'
[ 14%] Performing download step (download, verify and extract) for 'ext-yaml-cpp'
-- ext-yaml-cpp download command succeeded.  See also /root/deploy_water/cpp/build/ext/yaml-cpp/src/ext-yaml-cpp-stamp/ext-yaml-cpp-download-*.log
[ 21%] No update step for 'ext-yaml-cpp'
[ 28%] No patch step for 'ext-yaml-cpp'
[ 35%] Performing configure step for 'ext-yaml-cpp'
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test FLAG_WEXTRA
-- Performing Test FLAG_WEXTRA - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /root/deploy_water/cpp/build/ext/yaml-cpp/src/ext-yaml-cpp-build
[ 42%] Performing build step for 'ext-yaml-cpp'
-- ext-yaml-cpp build command succeeded.  See also /root/deploy_water/cpp/build/ext/yaml-cpp/src/ext-yaml-cpp-stamp/ext-yaml-cpp-build-*.log
[ 50%] No install step for 'ext-yaml-cpp'
[ 57%] Completed 'ext-yaml-cpp'
[ 57%] Built target ext-yaml-cpp
[ 64%] Building CXX object CMakeFiles/main.dir/src/main.cc.o
cc1plus: 错误：给定了太多文件名。试用 cc1plus --help 以了解用法
cc1plus: 致命错误：CMakeFiles/main.dir/src/main.cc.d：没有那个文件或目录
编译中断。
make[2]: *** [CMakeFiles/main.dir/build.make:76：CMakeFiles/main.dir/src/main.cc.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:111：CMakeFiles/main.dir/all] 错误 2
make: *** [Makefile:91：all] 错误 2
make finished!
 ```

### 复现环境 Environment

- OS: Linux
- paddle: paddle_inference/manylinux_cpu_avx_mkl_gcc8.2
- paddleDet: release/2.4
- GCC:  8.5.0 
- cmake: 3.20.2
- cpu推理

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by ghostxsl** [comment]
编译的时候需要联网下载依赖，可能是代理不通下载不下来，你换个代理看看呢

**Comment by Wei-JL** [comment]
> CMakeFiles/main.dir/src/main.cc.o

这个`CMakeFiles/main.dir/src/main.cc.o` 文件是下载下来的吗？  不是building出啦的啊  请问在哪下载呢？  我是虚拟机做的这个部署，后续要部署到服务器使用，我vpn挂一下试了  还是不行 一样的报错

**Comment by ghostxsl** [comment]
这个不是下载下来的，是编译产生的，我这边测试编译没有问题，我用的是docker环境：paddlepaddle/paddle:latest-dev-cuda10.2-cudnn7-gcc82，能够成功编译，建议你换个环境试试看呢

**Comment by Wei-JL** [comment]
> 这个不是下载下来的，是编译产生的，我这边测试编译没有问题，我用的是docker环境：paddlepaddle/paddle:latest-dev-cuda10.2-cudnn7-gcc82，能够成功编译，建议你换个环境试试看呢

您好，我这边没有cuda，只有CPU版本的服务器，后续要考虑到服务器的问题，请问您用的那个paddle_inference包呢？ 可能gpu版本可以，但是这边真的不行啊，关键看不见里面做了什么这个cmake，可以帮帮忙解决一下paddle_inference/manylinux_cpu_avx_mkl_gcc8.2推理库吗？ 或者别的Linux的cpu的推理库也可以，只需要ppyolov2目标检测的模型导出部署即可，确实卡2个月了。没进展才来提issue，我还发现了你们的关键点导出也有bug，我已经改完了。

**Comment by ghostxsl** [comment]
> > 这个不是下载下来的，是编译产生的，我这边测试编译没有问题，我用的是docker环境：paddlepaddle/paddle:latest-dev-cuda10.2-cudnn7-gcc82，能够成功编译，建议你换个环境试试看呢
> 
> 您好，我这边没有cuda，只有CPU版本的服务器，后续要考虑到服务器的问题，请问您用的那个paddle_inference包呢？ 可能gpu版本可以，但是这边真的不行啊，关键看不见里面做了什么这个cmake，可以帮帮忙解决一下paddle_inference/manylinux_cpu_avx_mkl_gcc8.2推理库吗？ 或者别的Linux的cpu的推理库也可以，只需要ppyolov2目标检测的模型导出部署即可，确实卡2个月了。没进展才来提issue，我还发现了你们的关键点导出也有bug，我已经改完了。

我这边本地复现一下cpu版本的看一下，稍后给你回复

**Comment by ghostxsl** [comment]
你用的是最新的release 2.5嘛？关键点导出是什么bug呢？

**Comment by Wei-JL** [comment]
> 你用的是最新的release 2.5嘛？关键点导出是什么bug呢？



> > > 这个不是下载下来的，是编译产生的，我这边测试编译没有问题，我用的是docker环境：paddlepaddle/paddle:latest-dev-cuda10.2-cudnn7-gcc82，能够成功编译，建议你换个环境试试看呢
> > 
> > 
> > 您好，我这边没有cuda，只有CPU版本的服务器，后续要考虑到服务器的问题，请问您用的那个paddle_inference包呢？ 可能gpu版本可以，但是这边真的不行啊，关键看不见里面做了什么这个cmake，可以帮帮忙解决一下paddle_inference/manylinux_cpu_avx_mkl_gcc8.2推理库吗？ 或者别的Linux的cpu的推理库也可以，只需要ppyolov2目标检测的模型导出部署即可，确实卡2个月了。没进展才来提issue，我还发现了你们的关键点导出也有bug，我已经改完了。
> 
非常感谢 ，我这边是centos8系统哦

**Comment by Wei-JL** [comment]
> 你用的是最新的release 2.5嘛？关键点导出是什么bug呢？

对的，今天跑的，2.5版本

步骤1:
![1](https://user-images.githubusercontent.com/71386288/194751352-12de9ce9-5e4e-4294-b6ea-a24f374e9c49.jpg)
步骤2:

![2](https://user-images.githubusercontent.com/71386288/194751374-a4d14003-1fbc-4dd7-83e3-5de3a605dd1f.jpg)
步骤3:
![3](https://user-images.githubusercontent.com/71386288/194751387-20eb72bb-f4c5-446c-a965-9c23151cfa2d.jpg)

**Comment by zhiboniu** [comment]
看提示你这个是命令行参数格式不对吧，把weights = xx中=号两边的空格去掉。

**Comment by Wei-JL** [comment]
> 看提示你这个是命令行参数格式不对吧，把weights = xx中=号两边的空格去掉。

这样吗，好吧  不好意思哈

**Comment by Wei-JL** [comment]
> > > 这个不是下载下来的，是编译产生的，我这边测试编译没有问题，我用的是docker环境：paddlepaddle/paddle:latest-dev-cuda10.2-cudnn7-gcc82，能够成功编译，建议你换个环境试试看呢
> > 
> > 
> > 您好，我这边没有cuda，只有CPU版本的服务器，后续要考虑到服务器的问题，请问您用的那个paddle_inference包呢？ 可能gpu版本可以，但是这边真的不行啊，关键看不见里面做了什么这个cmake，可以帮帮忙解决一下paddle_inference/manylinux_cpu_avx_mkl_gcc8.2推理库吗？ 或者别的Linux的cpu的推理库也可以，只需要ppyolov2目标检测的模型导出部署即可，确实卡2个月了。没进展才来提issue，我还发现了你们的关键点导出也有bug，我已经改完了。
> 
> 我这边本地复现一下cpu版本的看一下，稍后给你回复

请问这边CPU版本测试可以吗？

**Comment by Wei-JL** [comment]
> 看提示你这个是命令行参数格式不对吧，把weights = xx中=号两边的空格去掉。

其实联合推理还遇见了一个问题，两个模型我都导出了，联合推理报错（不同文件报错不同）
视频1:
![image](https://user-images.githubusercontent.com/71386288/194873314-d66d3154-8c33-4fef-9ee6-a5ddba4fc09d.png)
视频2:
![image](https://user-images.githubusercontent.com/71386288/194873467-5a197650-7aa2-4862-bc8d-83422e23b1aa.png)

**Comment by Wei-JL** [comment]
> 你用的是最新的release 2.5嘛？关键点导出是什么bug呢？

您好，复现会有报错吗？

**Comment by Wei-JL** [comment]
> 我这边本地复现一下cpu版本的看一下，稍后给你回复

您好，我这边用最新的paddledet2.5训练了一次，然后去部署，还是 `paddle_inference/manylinux_cpu_avx_mkl_gcc8.2`  推理库.
还是报同样错误:
```
[ 42%] Performing build step for 'ext-yaml-cpp'
-- ext-yaml-cpp build command succeeded.  See also /root/deploy/cpp/build/ext/yaml-cpp/src/ext-yaml-cpp-stamp/ext-yaml-cpp-build-*.log
[ 50%] No install step for 'ext-yaml-cpp'
[ 57%] Completed 'ext-yaml-cpp'
[ 57%] Built target ext-yaml-cpp
[ 64%] Building CXX object CMakeFiles/main.dir/src/main.cc.o
cc1plus: 错误：给定了太多文件名。试用 cc1plus --help 以了解用法
cc1plus: 致命错误：CMakeFiles/main.dir/src/main.cc.d：没有那个文件或目录
编译中断。
make[2]: *** [CMakeFiles/main.dir/build.make:76：CMakeFiles/main.dir/src/main.cc.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:111：CMakeFiles/main.dir/all] 错误 2
make: *** [Makefile:91：all] 错误 2
make finished!
```


=====================================================================



我提供一下我修改的地方: `deploy/cpp/scripts/build.sh` 文件如下:
```
# 是否使用GPU(即是否使用 CUDA)
WITH_GPU=OFF

# 是否使用MKL or openblas，TX2需要设置为OFF
WITH_MKL=ON

# 是否集成 TensorRT(仅WITH_GPU=ON 有效)
WITH_TENSORRT=OFF

# paddle 预测库lib名称，由于不同平台不同版本预测库lib名称不同，请查看所下载的预测库中`paddle_inference/lib/`文件夹下`lib`的名称
PADDLE_LIB_NAME=libpaddle_inference

# TensorRT 的include路径
TENSORRT_INC_DIR=/path/to/tensorrt/include

# TensorRT 的lib路径
TENSORRT_LIB_DIR=/path/to/tensorrt/lib

# Paddle 预测库路径
PADDLE_DIR=/root/deploy_water/paddle_inference

# CUDA 预测库路径
CUDA_LIB=/path/to/cuda/lib

# CUDNN 的 lib 路径
CUDNN_LIB=/path/to/cudnn/lib

# 是否开启关键点模型预测功能
WITH_KEYPOINT=OFF

# 是否开启跟踪模型预测功能
WITH_MOT=OFF

MACHINE_TYPE=`uname -m`
echo "MACHINE_TYPE: "${MACHINE_TYPE}


if [ "$MACHINE_TYPE" = "x86_64" ]
then
  echo "set OPENCV_DIR for x86_64"
  # linux系统通过以下命令下载预编译的opencv
  mkdir -p $(pwd)/deps && cd $(pwd)/deps
  wget -c https://paddledet.bj.bcebos.com/data/opencv-3.4.16_gcc8.2_ffmpeg.tar.gz
  tar -xvf opencv-3.4.16_gcc8.2_ffmpeg.tar.gz && cd ..

  # set OPENCV_DIR
  OPENCV_DIR=$(pwd)/deps/opencv-3.4.16_gcc8.2_ffmpeg

elif [ "$MACHINE_TYPE" = "aarch64" ]
then
  echo "set OPENCV_DIR for aarch64"
  # TX2平台通过以下命令下载预编译的opencv
  mkdir -p $(pwd)/deps && cd $(pwd)/deps
  wget -c https://bj.bcebos.com/v1/paddledet/data/TX2_JetPack4.3_opencv_3.4.6_gcc7.5.0.tar.gz
  tar -xvf TX2_JetPack4.3_opencv_3.4.6_gcc7.5.0.tar.gz && cd ..

  # set OPENCV_DIR
  OPENCV_DIR=$(pwd)/deps/TX2_JetPack4.3_opencv_3.4.6_gcc7.5.0/

else
  echo "Please set OPENCV_DIR manually"
fi

echo "OPENCV_DIR: "$OPENCV_DIR

# 以下无需改动
rm -rf build
mkdir -p build
cd build
cmake .. \
    -DWITH_GPU=${WITH_GPU} \
    -DWITH_MKL=${WITH_MKL} \
    -DWITH_TENSORRT=${WITH_TENSORRT} \
    -DTENSORRT_LIB_DIR=${TENSORRT_LIB_DIR} \
    -DTENSORRT_INC_DIR=${TENSORRT_INC_DIR} \
    -DPADDLE_DIR=${PADDLE_DIR} \
    -DWITH_STATIC_LIB=${WITH_STATIC_LIB} \
    -DCUDA_LIB=${CUDA_LIB} \
    -DCUDNN_LIB=${CUDNN_LIB} \
    -DOPENCV_DIR=${OPENCV_DIR} \
    -DPADDLE_LIB_NAME=${PADDLE_LIB_NAME} \
    -DWITH_KEYPOINT=${WITH_KEYPOINT} \
    -DWITH_MOT=${WITH_MOT}

make
echo "make finished!"

```
请问还需要改那些地方吗？

**Comment by Wei-JL** [comment]
您好，这边已经过去半个多月了？   cpu版本的推理有什么问题吗？

**Comment by lgy2830** [comment]
你好，我看你复现的是检测的模型，那么跟踪的实现了吗？也就是在CMakeLists.txt中的option(WITH_MOT       "Whether to Compile MOT detector" ON)设置为ON。
