### ISSUE TITLE
yolov6请问一下yaml的问题

### ISSUE THREAD

**Issue by dn1ftya** [PaddlePaddle/PaddleDetection#7073]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

yaml.constructor.ConstructorError: could not determine a constructor for the tag '!YOLOv5LRDecay'
  in "configs/yolov6/yolov6_n_400e_coco.yml", line 27, column 5
请问这个报错是什么原因 怎么解决呢

**Comment by nemonameless** [comment]
也可前往 https://github.com/PaddlePaddle/PaddleYOLO/issues 提问。
请使用这个分支的代码：https://github.com/PaddlePaddle/PaddleYOLO/tree/release/2.5 ，并确保拉取了最新。
测试过没有遇到你的问题。
