### ISSUE TITLE
labelme标注关键点无法通过x2coco转换为coco数据格式

### ISSUE THREAD

**Issue by imchenmin** [PaddlePaddle/PaddleDetection#7076]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

DataProcess

### Bug描述 Describe the Bug

在教程文档[KeyPointAnnoTools](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/data/KeyPointAnnoTools.md)中。按照gif图新建类型为point的关键点后通过x2coco.py转换发现没有生成数据集。如下图所示。
进一步分析，x2coco.py代码中并未对point类型进行keypoint数组生成。实际上根本没有进行关键点处理。
<img width="326" alt="image" src="https://user-images.githubusercontent.com/20356658/194744566-d6ad2871-5d23-48b5-a963-7cca96b95b8e.png">

### 复现环境 Environment

- OS: Linux
- PaddlePaddle: 2.2.2
- PaddleDetection: release/2.5
- Python: 3.8
- CUDA: 10.2
- CUDNN: 7.6
- GCC: 8.2.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
嗯，确实是。不好意思，实习生写文档的时候搞错了，我们后面会修复该文档

**Comment by imchenmin** [comment]
那么你们是如何标注数据的呢？还是用lableme吗？

**Comment by A-chen23** [comment]
请问这个问题是否已经解决？我看到工程中的代码这个问题还是没有解决，我现在也遇到的了同样的问题。

**Comment by Firestick-Xia** [comment]
插个眼，今天是2023年10月19号，这个问题还是存在

**Comment by zhiboniu** [comment]
coco格式也不复杂，自己写个脚本转一下吧
