### ISSUE TITLE
demo_openvino_kpts明显精度损失

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleDetection#7082]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

完整运行demo, 发现关键点预测结果不符合预期。因xml输出节点名称有变化，修改输出节点信息如下：
      {"save_infer_model/scale_0.tmp_1", "save_infer_model/scale_1.tmp_1", 8},
      {"save_infer_model/scale_2.tmp_1", "save_infer_model/scale_3.tmp_1", 16},
      {"save_infer_model/scale_4.tmp_1", "save_infer_model/scale_5.tmp_1", 32},
      {"save_infer_model/scale_6.tmp_1", "save_infer_model/scale_7.tmp_1", 64},

尝试自己的手动转模型以及用py代码复现，也发现关键点模型输出与paddle不一致，坐标有明显的偏移。对模型仅仅输入和输出也会发现无法精度对齐。

### 复现环境 Environment

-CUDA 10.2
- openvino： l_openvino_toolkit_ubuntu18_2022.2.0.7713

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by thunder95** [comment]
![Uploading keypoint_hrnet_demo.jpg…]()

**Comment by zhiboniu** [comment]
你好，openvino模型精度应该是验证过的。建议确认一下以下两点的影响：
1. 部署程序预处理实现可能稍有差异，建议在预处理后模型输入前使用同样的Tensor输入测试，打印模型输出后处理前的内容对比差异。
2. 注意预处理normalize是否放入了模型，该操作要统一，否则会有是否归一化的差异。

图片是个空链接，麻烦重新传一下吧。
另外你改的scale_0层名称，看起来是picodet检测模型，不用检测只用tinypose模型呢？

**Comment by thunder95** [comment]
@zhiboniu 您好， 我有对tinyposev2进行过测试，将paddle里的输入保存到np(已包含预处理，排除预处理的影响)，输入到tinypose的openvino模型(还没有后处理)， 比较结果在allclose时甚至1e-1都不能通过。我可以把代码贴上来，如果测试没问题，我也可以提交PR，如果不嫌弃的话。

**Comment by thunder95** [comment]
![keypoint_hrnet_demo](https://user-images.githubusercontent.com/22673612/194832080-e3fe471b-e8f5-43f0-9c9a-f3600c5d3442.jpg)
这是c++跑出来的结果，下载的模型输出名称不对，可能有预处理如归一化的影响。

**Comment by thunder95** [comment]
![hrnet_demo_vis](https://user-images.githubusercontent.com/22673612/194832313-cccc5842-aa8e-4602-81e2-014aa0afa997.jpg)
这是python跑出来的结果， 位置有明显的偏移，相比paddle里就正常很多。

**Comment by thunder95** [comment]
[run.py.txt](https://github.com/PaddlePaddle/PaddleDetection/files/9744688/run.py.txt)
没有加预处理的mean和scale之类的，就是直接转的模型 @zhiboniu

**Comment by zhiboniu** [comment]
你上面图跑的命令是什么？

**Comment by zhiboniu** [comment]
![截屏2022-10-10 下午5 30 51](https://user-images.githubusercontent.com/31800336/194837334-713b0c15-7631-48a4-9d1a-db6bf514dec2.png)

这是我这跑出来的结果，命令是：
python deploy/python/det_keypoint_unite_infer.py --det_model_dir=output_inference/picodet_s_320_lcnet_pedestrian/ --keypoint_model_dir=output_inference/tinypose_256x192/ --image_file=demo/hrnet_demo.jpg  --device=gpu

『下载的模型输出名称不对，可能有预处理如归一化的影响。』
这个问题，[demo_openvino_kpts](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/third_engine/demo_openvino_kpts)页面有提供模型和配合的代码，可以先用这里的模型测试一下效果。然后再对照你的模型看看差别是什么，先确认det+kpts两级中是那一级出的问题。

**Comment by thunder95** [comment]
@zhiboniu 我就是用的官网readme里的模型链接，那个不对了已经。在我的py脚本里，检测模型输出差异比较小。是kpts出的问题的，是不是我用的tinypose v2的原因，因为onnxsim的时候遇到了报错，然后 我就直接转的IR模型。

**Comment by thunder95** [comment]
c++下载的这个：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/third_engine/demo_openvino_kpts/README.md
python之前用的跟您的是一样的，参考的基准也是用的您这个命令，后来我改用c++的模型了，两个都是输出有明显差异。

**Comment by thunder95** [comment]
> 你上面图跑的命令是什么？

这个命令使用的我自己的脚本，python run.py

**Comment by zhiboniu** [comment]
[demo_openvino_kpts](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/third_engine/demo_openvino_kpts)页面有提供kpts模型，先用这个页面的模型对比看看。如果没有问题那基本可以确定是模型转换过程出了问题。然后就再分段看看具体是哪一步出了问题。

你跑的图片的关键点偏移问题，是输出结果映射回原图坐标映射的不对，代码逻辑问题。

**Comment by thunder95** [comment]
> 

我做的过程是这样：
1. 先使用自己转的模型，picodet输出没问题，在相同tensor输入下，paddle和openvino差距比较大
2. 接着尝试使用demo_openvino_kpts里的kpts模型， 然后出现了位置偏移，按照c++后处理逻辑复现到了py，出现了上述的位置偏移的情况
3. 然后决定一步步debug，是否有逻辑问题，就clone了官方的demo_openvino_kpts， 发现下载的官方模型输出名称不对，然后改了名称， 跑出来结果就这样了，也就不好一步步校验了。

尽管参考的标准结果就不对， 我还是可以一步步定位下去是吗？

**Comment by zhiboniu** [comment]
从你这段的描述来看，我是这样理解的：
1. 步骤一，你自己转的openvino模型，输出与paddle有差异，说明转出来的模型有问题。
2. 步骤二，使用demo_openvino_kpts里的kpts模型，输出有关键点了。但是有个问题是位置有偏移（上面说过了，这个偏移是关键点映射回原图位置错误造成的，是程序逻辑问题，这一步与模型无关）。从这里看模型应该是对了。这里是否只要修正映射逻辑后就满足预期了？
3. 步骤三，这里你提到的官方模型是否是demo_openvino_kpts页面下载的openvino格式模型，我上面说的用这个页面提供的模型就是指的这一步。这个应该是当时写代码时用的模型，验证过的。如果你用的不是这个模型可以换成这个试试，如果你用的是其他页面提供的官方模型是并不确定的，因为模型后来更改过，可能名称不一样了。如果你用的模型和程序就是这个页面的，那你可以等我验证完给你反馈，这个当时openvino的环境已经没有了，需要重新走流程验证。

**Comment by thunder95** [comment]
已解决　https://aistudio.baidu.com/aistudio/projectdetail/4596672
