### ISSUE TITLE
PP-YOLOE+   问题咨询

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#7083]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/ppyoloe/README_cn.md
![image](https://user-images.githubusercontent.com/78945582/194790417-b6620020-c5fa-44d4-bc65-e4486d65733b.png)
Box APval 0.5:0.95是基于COCO val的测试结果吗？还是基于Objects365的测试结果？

**Comment by jerrywgz** [comment]
这些都是基于COCO val2017的结果
