### ISSUE TITLE
垂类应用模型是基于PP-YOLOE还是基于PP-YOLOE+的模型，具体是s/m/l/x哪一个？

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#7084]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/ppyoloe/README_cn.md
![image](https://user-images.githubusercontent.com/78945582/194790543-c5124837-d321-49a1-afca-a3eedc73f212.png)
垂类应用模型是基于PP-YOLOE还是基于PP-YOLOE+的模型，具体是s/m/l/x哪一个？

**Comment by nemonameless** [comment]
PPYOLOE，这些疑问请自己点进去看配置文件。
