### ISSUE TITLE
PPYOLOE里面的Backbone（cspresnet-s/-m/-l/-x）有什么区别？

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#7087]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/78945582/194796372-895cd71a-5215-493b-9689-0b823a3c9389.png)
PPYOLOE里面的Backbone（cspresnet-s/cspresnet-m/cspresnet-l/cspresnet-x）有什么区别？具体哪个地方不一样？

**Comment by XYZ-916** [comment]
配置文件中depth_mult和width_mult两个变量控制模型规模。
