### ISSUE TITLE
PP-YOLOE中的检测头为什么没有背景类？如何区分该区域是不是背景类？

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#7090]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PP-YOLOE中的检测头为什么没有背景类？如何区分该区域是不是背景类？在YOLOX中是（80+4+1）*8400，而PP-YOLOE的检测头确是（80+4）*8400，PP-YOLOE如何区别正负样本？
![image](https://user-images.githubusercontent.com/78945582/194810027-f30cd957-1cc2-49a0-b108-89e18096922b.png)

**Comment by XYZ-916** [comment]
YOLOX中（80+4+1）*8400，80为coco数据集类别为80，4是要回归的框，1是object。PP-YOLOE中没有object这一项。在计算cls loss时会考虑背景。

**Comment by lixiangMindSpore** [comment]
> YOLOX中（80+4+1）*8400，80为coco数据集类别为80，4是要回归的框，1是object。PP-YOLOE中没有object这一项。在计算cls loss时会考虑背景。

您好，在计算类别损失的时候如何考虑背景的？

**Comment by XYZ-916** [comment]
> > YOLOX中（80+4+1）*8400，80为coco数据集类别为80，4是要回归的框，1是object。PP-YOLOE中没有object这一项。在计算cls loss时会考虑背景。
> 
> 您好，在计算类别损失的时候如何考虑背景的？

代码请看： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/modeling/heads/ppyoloe_head.py#L339
