### ISSUE TITLE
PicoDet转onnx的结果与静态图推理结果差异较大

### ISSUE THREAD

**Issue by xdg2016** [PaddlePaddle/PaddleDetection#7093]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference

### Bug描述 Describe the Bug

deploy\third_engine\demo_onnxruntime\infer_demo.py
将PicoDet转成静态图和onnx模型后，推理的结果差异较大，静态图推理结果是正确的，onnx的推理结果较差，经过调试，发现是在onnx的数据预处理时，使用的是BGR模式，没有做BGR2RGB的操作，而静态图的推理是有的，对比如下图所示：
静态图推理预处理：
![image](https://user-images.githubusercontent.com/16351823/195008098-eb5a683f-eb0c-474b-9e12-e41432535e8d.png)
onnx推理预处理：
![image](https://user-images.githubusercontent.com/16351823/195008247-b9eaecca-5971-42bf-b7c4-6323aa6f3de5.png)
此外，两种推理的resize方法也不一样，
静态图推理预处理resize，self,interp = 2
![image](https://user-images.githubusercontent.com/16351823/195014220-50f9db64-0234-4d98-9ed8-6bc3195dc1e5.png)
onnx推理预处理resize，interpolation=3
![image](https://user-images.githubusercontent.com/16351823/195014809-bd81d49b-d382-4828-ae4e-dc236f279f58.png)
这两个地方差异较大，导致最终的输出结果差异较大。

### 复现环境 Environment

-OS:windows
-PaddlePaddle 2.2.2.post112
-PaddleDetection: release/2.4
-python:3.8

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
优秀，方便提个PR嘛
