### ISSUE TITLE
PPYOLOE+在infer.py使用save_results生成json文件，我想在json文件中添加一个文件名字段，在哪里修改代码？

### ISSUE THREAD

**Issue by lixiangMindSpore** [PaddlePaddle/PaddleDetection#7098]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PPYOLOE+在infer.py使用save_results生成json文件，我想在json文件中添加一个文件名字段，在哪里修改代码？

**Comment by wangxinxin08** [comment]
保存json文件的相关代码在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/metrics/metrics.py#L73 你可以看下`update`和`accumulate`函数

**Comment by lixiangMindSpore** [comment]
> 保存json文件的相关代码在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/metrics/metrics.py#L73 你可以看下`update`和`accumulate`函数

有没有保存txt的命令？

**Comment by lixiangMindSpore** [comment]
> 保存json文件的相关代码在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/metrics/metrics.py#L73 你可以看下`update`和`accumulate`函数

image_id和图片如何一一对应上？

**Comment by wangxinxin08** [comment]
> > 保存json文件的相关代码在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/metrics/metrics.py#L73 你可以看下`update`和`accumulate`函数
> 
> 有没有保存txt的命令？

可以参照着自己改

**Comment by wangxinxin08** [comment]
> > 保存json文件的相关代码在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/metrics/metrics.py#L73 你可以看下`update`和`accumulate`函数
> 
> image_id和图片如何一一对应上？

建议看下源码，image_id和图片按照顺序对应保存在sample字典中

**Comment by lixiangMindSpore** [comment]
> > > 保存json文件的相关代码在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/metrics/metrics.py#L73 你可以看下`update`和`accumulate`函数
> > 
> > 
> > image_id和图片如何一一对应上？
> 
> 建议看下源码，image_id和图片按照顺序对应保存在sample字典中

您好，sample字典在哪个代码文件里？

**Comment by zyvonne** [comment]
我在yoloe里修改了update函数和Metric，这是我的解决方法：https://zhuanlan.zhihu.com/p/606514890， 你也可以按照这个模式添加自己的字段，注意对应
