### ISSUE TITLE
使用yolov3_r50vd_dcn训练卡住不动

### ISSUE THREAD

**Issue by itmajing** [PaddlePaddle/PaddleDetection#71]
使用yolov3_r50vd_dcn模型, 自定义coco数据集, 训练到20000多轮时, 卡住不动

![image](https://user-images.githubusercontent.com/24891592/70230851-2dd8c100-1794-11ea-8d3c-e87fc0ffcc7f.png)

**Comment by FDInSky** [comment]
之前的paddle有的版本会hang住，大概1.4 1.5的时候，好像是nccl版本之类的问题，后来框架好像修复了， 检查下你的版本；

**Comment by itmajing** [comment]
> 之前的paddle有的版本会hang住，大概1.4 1.5的时候，好像是nccl版本之类的问题，后来框架好像修复了， 检查下你的版本；

@FDInSky 我使用的是paddle 1.6.1版本

**Comment by qingqing01** [comment]
@itmajing 请问问题还是否存在？

**Comment by itmajing** [comment]
@qingqing01 最近没有使用, 不是很清清楚, 可以先关了吧
