### ISSUE TITLE
部署c++版本，跟踪代码报错

### ISSUE THREAD

**Issue by jiaerwang0328** [PaddlePaddle/PaddleDetection#7100]
### 问题描述 Please describe your issue

编译main_jde.cc主程序，代码运行报错。
![image](https://user-images.githubusercontent.com/38750407/195242574-da2ec6c2-3614-4856-946c-09cb426b7362.png)

经过定位，报错位置在tracker.cc中：
![image](https://user-images.githubusercontent.com/38750407/195242165-a0ff3c9a-8c6d-424e-91fc-e2344be21f3c.png)
请问该如何修改？

**Comment by nemonameless** [comment]
为更好地了解具体情况以便解决，请按模板提问谢谢。
https://github.com/PaddlePaddle/PaddleDetection/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml 
建议自己打印出 ltrb, score, embedding 看下
