### ISSUE TITLE
推理的时候 NameError: name 'Resize' is not defined

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleDetection#7104]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在windows下测试layout 的模型进行表格区域检测出现下面异常
`D:\ProgramData\Anaconda3\envs\paddle\python.exe "D:\PyCharm 2019.2.1\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 59728 --file E:/paddleDetection-develop/PaddleDetection/deploy/python/infer.py
pydev debugger: process 8356 is connecting

Connected to pydev debugger (build 192.7142.79)
-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: -1
combine_method: nms
cpu_threads: 1
device: CPU
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: E:/table_test/xhuigufen200-up/
image_file: None
match_metric: ios
match_threshold: 0.6
model_dir: E:/model/picodet_lcnet_x1_0_fgd_layout_infer/
output_dir: E:/table_test/xhuigufen200-up/output
overlap_ratio: [0.25, 0.25]
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: paddle
save_images: True
save_mot_txt_per_img: None
save_mot_txts: None
save_results: False
scaled: False
slice_infer: None
slice_size: [960, 960]
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_coco_category: False
use_dark: True
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: PicoDet
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--transform op: PadStride
--------------------------------------------
Found 8 inference images in total.
Traceback (most recent call last):
  File "D:\PyCharm 2019.2.1\helpers\pydev\pydevd.py", line 1418, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm 2019.2.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/paddleDetection-develop/PaddleDetection/deploy/python/infer.py", line 1041, in <module>
    main()
  File "E:/paddleDetection-develop/PaddleDetection/deploy/python/infer.py", line 1014, in main
    save_results=FLAGS.save_results)
  File "E:/paddleDetection-develop/PaddleDetection/deploy/python/infer.py", line 386, in predict_image
    inputs = self.preprocess(batch_image_list)
  File "E:/paddleDetection-develop/PaddleDetection/deploy/python/infer.py", line 132, in preprocess
    preprocess_ops.append(eval(op_type)(**new_op_info))
  File "<string>", line 1, in <module>
NameError: name 'Resize' is not defined

Process finished with exit code 1
`
模型也是采用的官网最新的模型，代码是develop中最新代码。
后来找了一下resize出处是infer-cfg.yml中，注释掉下面的又会出现新的问题
![image](https://user-images.githubusercontent.com/12640462/195288451-110f9b19-86bc-46fd-90c0-29585ac45135.png)

**Comment by wangxinxin08** [comment]
这个函数在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/python/infer.py#L36 声明了，不太清楚是不是你的这种调用方式导致未能成功import，一个临时的解决方式是你可以把相关的函数直接加到这个文件里面

**Comment by BeyondYourself** [comment]
多谢，问题已解决，是pycharm的代码格式化导致部分引用丢失
