### ISSUE TITLE
decord的GPU版本怎么编译啊，有没有可参考的方法。因为总是报这个错

### ISSUE THREAD

**Issue by qq-tt** [PaddlePaddle/PaddleDetection#7109]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

decord的GPU版本怎么编译啊，有没有可参考的方法。因为总是报这个错
![image](https://user-images.githubusercontent.com/32315802/195311117-628e1969-cc19-4c54-940d-4a650860507f.png)
pip install 只能在无GPU环境下安装，有GPU时没办法安装

**Comment by wangxinxin08** [comment]
可以网上搜索下解决方案哈
