### ISSUE TITLE
请问：使用paddledetection并使用TensorRT加速时，每次都要重新生成一次优化序列文件，导致加载速度慢能有方法解决吗？

### ISSUE THREAD

**Issue by Sco-cai** [PaddlePaddle/PaddleDetection#7117]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用paddledetection训练并转换PPYOLO_r18vd模型，在使用TensorRT加速部署时，每次都要加载很久

**Comment by slackzh** [comment]
enable_tensort_engine 中的 use_static 参数设为true，会生成缓存文件。下次就比较快了

**Comment by hezhi1220** [comment]
> enable_tensort_engine 中的 use_static 参数设为true，会生成缓存文件。下次就比较快了

这个参数在哪里改啊 全局搜索没有找到

**Comment by hoozh** [comment]
> 

https://github.com/PaddlePaddle/PaddleDetection/blob/ba2aad26e6bc1e5c2dad76ca96692a0d63eccfac/deploy/cpp/src/object_detector.cc#L48

**Comment by slackzh** [comment]
> > enable_tensort_engine 中的 use_static 参数设为true，会生成缓存文件。下次就比较快了
> 
> 这个参数在哪里改啊 全局搜索没有找到

c++ 部署的话是这里，倒数第二个参数

https://github.com/PaddlePaddle/PaddleDetection/blob/ba2aad26e6bc1e5c2dad76ca96692a0d63eccfac/deploy/cpp/src/object_detector.cc#L48
