### ISSUE TITLE
现在下载，config里面没有yolov5,yolov6,yolov7的相关文件

### ISSUE THREAD

**Issue by deshuai666** [PaddlePaddle/PaddleDetection#7127]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 2. 需求场景（请描述你的项目中为什么需要用此功能）; 3. 功能描述（请简单描述或设计这个功能）

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by kaixin-bai** [comment]
所以结论是什么？必须要自己去那个什么paddleYOLO里去添加过来是吗？
