### ISSUE TITLE
ppyolo模型的蒸馏配置文件

### ISSUE THREAD

**Issue by bittergourd1224** [PaddlePaddle/PaddleDetection#7128]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标
利用蒸馏获得准确率高的小模型，用于部署中

2. 需求场景
在交通目标识别中，训练的ppyolo的Resnet50模型效果达标但速度慢，直接训练的ppyolo的mobilenetv3小模型准确率又不够，想尝试从大模型向小模型蒸馏的效果。

3. 功能描述
目前蒸馏部分 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/slim/distill 中，只包含了yolov3的蒸馏配置文件，且ReadMe完全没有使用方法的介绍或者如何自己写蒸馏配置文件的教程。希望提供ppyolo模型之间的蒸馏配置文件与使用方法。
如果目前还不支持ppyolo的蒸馏，希望提供一个能够支持的预期时间，感谢~

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by XYZ-916** [comment]
可以尝试下ppyoloe系列模型看是否能够满足您的需求：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/ppyoloe

**Comment by bittergourd1224** [comment]
> 可以尝试下ppyoloe系列模型看是否能够满足您的需求：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/ppyoloe

ppyoloe系列也没有找到蒸馏配置文件，是否支持蒸馏？如果支持，能否帮忙提供蒸馏配置文件的示例呢？

**Comment by XYZ-916** [comment]
请看下这个文档是否对你有帮助：https://github.com/PaddlePaddle/PaddleDetection/blob/ede22043927a944bb4cbea0e9455dd9c91b295f0/deploy/auto_compression/README.md

**Comment by bittergourd1224** [comment]
好的，我有空试一下
