### ISSUE TITLE
多目标跟踪算法是否包含了评测脚本？

### ISSUE THREAD

**Issue by Hyperjunct** [PaddlePaddle/PaddleDetection#7130]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

已经使用YOLO目标检测算法和ReID模型基于python在自己录制的视频上实现了跟踪的功能，请问是否有评测脚本可以计算模型的跟踪性能指标？

**Comment by XYZ-916** [comment]
请参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/advanced_tutorials/customization/pphuman_mtmct.md 中性能评估部分。

**Comment by nemonameless** [comment]
此模型未提供评测脚本，是一个基础方案，你可以重训检测和重训reid专门去优化精度。
数据集是AI City Challenge的数据集，有专门车辆reid和车辆MTMCT的比赛，可以自行搜索。即使是AI City的数据集也不一定覆盖任何场景说训完用效果就都好，需要针对自己的场景专门训下自己的数据集。

**Comment by nemonameless** [comment]
此模型未提供评测脚本，是一个基础方案，你可以重训检测和重训reid专门去优化精度。
数据集是AI City Challenge的数据集，有专门车辆reid和车辆MTMCT的比赛，可以自行搜索。即使是AI City的数据集也不一定覆盖任何场景说训完用效果就都好，需要针对自己的场景专门训下自己的数据集。
