### ISSUE TITLE
目标跟踪算法能否支持2d box是不规则多边形呢？

### ISSUE THREAD

**Issue by weihongwei-zg** [PaddlePaddle/PaddleDetection#7134]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

这边目标跟踪算法能否支持2d box是不规则多边形呢？例如2d框是菱形或者梯形，能否用这边的目标跟踪算法进行跟踪？如果暂时不支持的话，我能否自己修改呢？

**Comment by XYZ-916** [comment]
目前目标检测只支持水平矩形框和旋转框的检测，还不支持任意形状目标检测哦。

**Comment by weihongwei-zg** [comment]
那能否单独训练一个自己的跟踪模型，检测结果我使用自己的模型来做。

**Comment by nemonameless** [comment]
跟踪目前只支持水平矩形框。tracker内部逻辑都是基于水平检测框，具体可以看 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/ppdet/modeling/mot/tracker

**Comment by weihongwei-zg** [comment]
了解了，那我现在想这样做，我用自己的检测模型，把检测出来的多边形结果求个外接矩形，就变成矩形框了。然后能否利用这些数据单独训练个跟踪模型呢（我只需要得需要跟踪物体的编号）！

**Comment by weihongwei-zg** [comment]
了解了，那我现在想这样做，我用自己的检测模型，把检测出来的多边形结果求个外接矩形，就变成矩形框了。然后能否利用这些数据单独训练个跟踪模型呢（我只需要得需要跟踪物体的编号）！

**Comment by nemonameless** [comment]
tracker代码不改动的情况下，只要确保送入tracker的是水平检测框即可。
