### ISSUE TITLE
Can slowfast model be integrated into pphuman 

### ISSUE THREAD

**Issue by Xinxinatg** [PaddlePaddle/PaddleDetection#7135]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 2. 需求场景（请描述你的项目中为什么需要用此功能）; 3. 功能描述（请简单描述或设计这个功能）
I would like to deploy the pphuman module in security monitoring, but the skeleton based action detection provided here can only detect falling. I found the the slowfast model pretrained on AVA dataset is provided in paddlevideo, are there any chance slowfast can be integrated into the pphuman pipeline as well?

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jerrywgz** [comment]
slowfast是时序行为检测的模型，目前再paddlevedio中也有集成，目前human还没有集成，可以参考pptsm的集成方法https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/pipeline/pphuman/video_action_infer.py
