### ISSUE TITLE
end2end_ppyoloe生成onnx模型报错

### ISSUE THREAD

**Issue by Luna2199** [PaddlePaddle/PaddleDetection#7139]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/21285692/196445015-f012cb55-ab9f-47d4-9495-916ec1b79777.png)
`paddle.__version__ ：2.3.0 `
`PaddleDetection ： release/2.5`
`Python 3.6.13`
`onnx                 1.11.0
onnx-graphsurgeon    0.3.24
onnxruntime          1.10.0
onnxsim              0.4.8
paddle2onnx          1.0.1
`
参照官方ReadeMe文档 : `https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/end2end_ppyoloe`
执行命令：`python ./deploy/end2end_ppyoloe/end2end.py --model-dir output_inference/ppyoloe_crn_s_300e_coco --save-file output_inference/ppyoloe_crn_s_300e_coco.onnx --opset 11 --batch-size 1 --topk-all 100 --iou-thres 0.6 --conf-thres 0.4`
报错信息：
`2022-10-18 21:39:10 [INFO]	ONNX model saved in output_inference/ppyoloe_crn_s_300e_coco.onnx
Traceback (most recent call last):
  File "./deploy/end2end_ppyoloe/end2end.py", line 97, in <module>
    main(opt)
  File "./deploy/end2end_ppyoloe/end2end.py", line 39, in main
    if node.op == 'Concat' and node.o().op == 'Reshape' and node.o().o().op == 'ReduceSum':
  File "/home/robot/anaconda3/envs/pp_env/lib/python3.6/site-packages/onnx_graphsurgeon/ir/node.py", line 89, in o
    return self.outputs[tensor_idx].outputs[consumer_idx]
IndexError: list index out of range
`

**Comment by cainiaojy** [comment]
同问

**Comment by laugh12321** [comment]
我这边修复了，可以试试[TensorRT-YOLO](https://github.com/laugh12321/TensorRT-YOLO)。支持PP-YOLOE、PP-YOLOE+添加EfficientNMS插件导出ONNX模型和TensorRT模型，且batch-size可以大于1。
