### ISSUE TITLE
paddle支持人脸检测加人脸识别加活体检测吗

### ISSUE THREAD

**Issue by LeeLear** [PaddlePaddle/PaddleDetection#7141]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddle支持人脸检测加人脸识别加活体检测吗

**Comment by nemonameless** [comment]
人脸检测已提供：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/face_detection
人脸识别可以使用 https://github.com/deepinsight/insightface/tree/master/recognition/arcface_paddle
活体检测暂不支持
