### ISSUE TITLE
PicoDet转成onnx后推理偶尔会出错

### ISSUE THREAD

**Issue by xdg2016** [PaddlePaddle/PaddleDetection#7143]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我基于自己的数据集训练了一个picodet_l_320模型，按照教程，先转成静态模型，再转成onnx模型，然后在用onnx推理的时候，遇到某些图，就会出现如下错误：
![image](https://user-images.githubusercontent.com/16351823/196586517-ff55a9ef-46e5-44a7-80ee-c4bd6d94749c.png)
看样子是某个Gather层出错了，用netron查看结构，这个节点在NMS的位置，
![image](https://user-images.githubusercontent.com/16351823/196586649-ab9aaef2-93ce-462b-9e62-53b335b21051.png)
我检查了这张图的输入尺寸和其他图没有什么差别，为什么会报维度错误呢？
我查了一些资料，说是可以用onnxsim做简化后，就不会有这些层了，但是简化后的模型还是会有这些层，还是报同样的错误
![image](https://user-images.githubusercontent.com/16351823/196587059-1fa333ea-ac88-4914-9e51-e92b41d1107c.png)
麻烦帮我解答一下谢谢，猜测可能是将nms一起导出有时候会有问题

**Comment by xdg2016** [comment]
问题已解决，原因是paddle导出静态图时，默认将nms也导出，而报错的地方正好在nms的位置，所以我在导出静态图和转换onnx的时候，去掉了nms，然后再将onnx的输出（picoHead的输出）接上nms（从动态图推理的地方拷贝的），就得到了和原来一样结果，前面报错的问题也解决了。

**Comment by 624861627** [comment]
> 问题已解决，原因是paddle导出静态图时，默认将nms也导出，而报错的地方正好在nms的位置，所以我在导出静态图和转换onnx的时候，去掉了nms，然后再将onnx的输出（picoHead的输出）接上nms（从动态图推理的地方拷贝的），就得到了和原来一样结果，前面报错的问题也解决了。



> 问题已解决，原因是paddle导出静态图时，默认将nms也导出，而报错的地方正好在nms的位置，所以我在导出静态图和转换onnx的时候，去掉了nms，然后再将onnx的输出（picoHead的输出）接上nms（从动态图推理的地方拷贝的），就得到了和原来一样结果，前面报错的问题也解决了。

你好，这个过程中怎么去掉nms呀？能详细说一说吗？谢谢了！！！！

**Comment by xdg2016** [comment]
@624861627 你参考一下这个官网文档：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/picodet
![image](https://user-images.githubusercontent.com/16351823/201559243-bc5179af-434c-40a2-9f1c-475521a7773b.png)
我这里导出的时候没有加nms，然后在导出后，推理的时候加上nms就可以了：
![image](https://user-images.githubusercontent.com/16351823/201560169-0fc7f664-f225-45a9-af5e-bd3ee4be402d.png)

**Comment by 624861627** [comment]
> @624861627 你参考一下这个官网文档：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/picodet ![image](https://user-images.githubusercontent.com/16351823/201559243-bc5179af-434c-40a2-9f1c-475521a7773b.png) 我这里导出的时候没有加nms，然后在导出后，推理的时候加上nms就可以了： ![image](https://user-images.githubusercontent.com/16351823/201560169-0fc7f664-f225-45a9-af5e-bd3ee4be402d.png)

好的好的，非常感谢！！！！

**Comment by 624861627** [comment]
> 将onnx的输出（picoHead的输出）接上nms（从动态图推理的地方拷贝的）

您好，我还有点疑问，拷贝的这部分代码具体是在哪个py文件里面呀。我找了，发现没有找到，麻烦您再细说一下。

**Comment by xdg2016** [comment]
@624861627 
![image](https://user-images.githubusercontent.com/16351823/201592194-8c708d2f-e63e-4c9f-9aba-a4b3d25ad688.png)
在后处理里面调用了nms，你看下导入的nms，
![image](https://user-images.githubusercontent.com/16351823/201592448-12923d76-f044-4aee-95bc-7e0d4ddf4081.png)
不过这个nms是paddle编译的c的库，我后面用了网上实现的一个版本，无缝衔接：

class multiclass_nms():
    def __init__(self, score_thresh=0.1, nms_thresh=0.5, pos_nms_topk=120):
        self.score_thresh = score_thresh
        self.nms_thresh = nms_thresh
        self.pos_nms_topk = pos_nms_topk
 
    def __call__(self, boxes, scores):
        batch_size = boxes.shape[0]
        class_num = scores.shape[1]
        rets = []
        for i in range(batch_size):
            bboxes_i = boxes[i]
            scores_i = scores[i]
            ret = []
            # 遍历所有类别，进行单分类NMS
            for c in range(class_num):
                scores_i_c = scores_i[c]
 
                keep_inds = self.nms(bboxes_i, scores_i_c)
                if len(keep_inds) < 1:
                    continue
                keep_bboxes = bboxes_i[keep_inds]
                keep_scores = scores_i_c[keep_inds]
                keep_results = np.zeros([keep_scores.shape[0], 6])
                keep_results[:, 0] = c
                keep_results[:, 1] = keep_scores[:]
                keep_results[:, 2:6] = keep_bboxes[:, :]
                ret.append(keep_results)
            if len(ret) < 1:
                rets.append(ret)
                continue
            ret_i = np.concatenate(ret, axis=0)
            scores_i = ret_i[:, 1]
 
            if len(scores_i) > self.pos_nms_topk:
                inds = np.argsort(scores_i)[::-1]
                inds = inds[:self.pos_nms_topk]
                ret_i = ret_i[inds]
            rets.append(ret_i)
        return rets
 
    def box_iou_xyxy(self, box1, box2):
        x1min, y1min, x1max, y1max = box1[0], box1[1], box1[2], box1[3]
        s1 = (y1max - y1min + 1.) * (x1max - x1min + 1.)
        x2min, y2min, x2max, y2max = box2[0], box2[1], box2[2], box2[3]
        s2 = (y2max - y2min + 1.) * (x2max - x2min + 1.)
        
        xmin = np.maximum(x1min, x2min)
        ymin = np.maximum(y1min, y2min)
        xmax = np.minimum(x1max, x2max)
        ymax = np.minimum(y1max, y2max)
 
        inter_h = np.maximum(ymax - ymin + 1., 0.)
        inter_w = np.maximum(xmax - xmin + 1., 0.)
        intersection = inter_h * inter_w
 
        union = s1 + s2 - intersection
        iou = intersection / union
        return iou
 
    def nms(self, bboxes, scores):
        # 对预测框得分进行排序
        inds = np.argsort(scores)
        inds = inds[::-1]
        keep_inds = []
        # 循环遍历预测框
        while(len(inds) > 0):
            cur_ind = inds[0]
            cur_score = scores[cur_ind]
            # 如果预测框得分低于阈值，则退出循环
            if cur_score < self.score_thresh:
                break
            # 计算当前预测框与保留列表中的预测框IOU，如果小于阈值则保留该预测框，否则丢弃该预测框
            keep = True
            for ind in keep_inds:
                current_box = bboxes[cur_ind]
                remain_box = bboxes[ind]
                # 计算当前预测框与保留列表中的预测框IOU
                iou = self.box_iou_xyxy(current_box, remain_box)
                if iou > self.nms_thresh:
                    keep = False
                    break
            if keep:
                keep_inds.append(cur_ind)
            inds = inds[1:]
        return np.array(keep_inds)

**Comment by 624861627** [comment]
> @624861627 ![image](https://user-images.githubusercontent.com/16351823/201592194-8c708d2f-e63e-4c9f-9aba-a4b3d25ad688.png) 在后处理里面调用了nms，你看下导入的nms， ![image](https://user-images.githubusercontent.com/16351823/201592448-12923d76-f044-4aee-95bc-7e0d4ddf4081.png) 不过这个nms是paddle编译的c的库，我后面用了网上实现的一个版本，无缝衔接：
> 
> class multiclass_nms(): def **init**(self, score_thresh=0.1, nms_thresh=0.5, pos_nms_topk=120): self.score_thresh = score_thresh self.nms_thresh = nms_thresh self.pos_nms_topk = pos_nms_topk
> 
> ```
> def __call__(self, boxes, scores):
>     batch_size = boxes.shape[0]
>     class_num = scores.shape[1]
>     rets = []
>     for i in range(batch_size):
>         bboxes_i = boxes[i]
>         scores_i = scores[i]
>         ret = []
>         # 遍历所有类别，进行单分类NMS
>         for c in range(class_num):
>             scores_i_c = scores_i[c]
> 
>             keep_inds = self.nms(bboxes_i, scores_i_c)
>             if len(keep_inds) < 1:
>                 continue
>             keep_bboxes = bboxes_i[keep_inds]
>             keep_scores = scores_i_c[keep_inds]
>             keep_results = np.zeros([keep_scores.shape[0], 6])
>             keep_results[:, 0] = c
>             keep_results[:, 1] = keep_scores[:]
>             keep_results[:, 2:6] = keep_bboxes[:, :]
>             ret.append(keep_results)
>         if len(ret) < 1:
>             rets.append(ret)
>             continue
>         ret_i = np.concatenate(ret, axis=0)
>         scores_i = ret_i[:, 1]
> 
>         if len(scores_i) > self.pos_nms_topk:
>             inds = np.argsort(scores_i)[::-1]
>             inds = inds[:self.pos_nms_topk]
>             ret_i = ret_i[inds]
>         rets.append(ret_i)
>     return rets
> 
> def box_iou_xyxy(self, box1, box2):
>     x1min, y1min, x1max, y1max = box1[0], box1[1], box1[2], box1[3]
>     s1 = (y1max - y1min + 1.) * (x1max - x1min + 1.)
>     x2min, y2min, x2max, y2max = box2[0], box2[1], box2[2], box2[3]
>     s2 = (y2max - y2min + 1.) * (x2max - x2min + 1.)
>     
>     xmin = np.maximum(x1min, x2min)
>     ymin = np.maximum(y1min, y2min)
>     xmax = np.minimum(x1max, x2max)
>     ymax = np.minimum(y1max, y2max)
> 
>     inter_h = np.maximum(ymax - ymin + 1., 0.)
>     inter_w = np.maximum(xmax - xmin + 1., 0.)
>     intersection = inter_h * inter_w
> 
>     union = s1 + s2 - intersection
>     iou = intersection / union
>     return iou
> 
> def nms(self, bboxes, scores):
>     # 对预测框得分进行排序
>     inds = np.argsort(scores)
>     inds = inds[::-1]
>     keep_inds = []
>     # 循环遍历预测框
>     while(len(inds) > 0):
>         cur_ind = inds[0]
>         cur_score = scores[cur_ind]
>         # 如果预测框得分低于阈值，则退出循环
>         if cur_score < self.score_thresh:
>             break
>         # 计算当前预测框与保留列表中的预测框IOU，如果小于阈值则保留该预测框，否则丢弃该预测框
>         keep = True
>         for ind in keep_inds:
>             current_box = bboxes[cur_ind]
>             remain_box = bboxes[ind]
>             # 计算当前预测框与保留列表中的预测框IOU
>             iou = self.box_iou_xyxy(current_box, remain_box)
>             if iou > self.nms_thresh:
>                 keep = False
>                 break
>         if keep:
>             keep_inds.append(cur_ind)
>         inds = inds[1:]
>     return np.array(keep_inds)
> ```

多谢大佬！！！！！！！！！！！！！！！！！！！！！！！！！！！  调试了半天（主要是入口难找），把您提供的代码加进去后，问题终于解决了。

**Comment by xdg2016** [comment]
paddle封装加上反射机制，确实不好调试，我一般调试的时候用F11跟进函数里去，然后一层层进去，再一层层退出来，这样就比较好理清思路了。

**Comment by 624861627** [comment]
> paddle封装加上反射机制，确实不好调试，我一般调试的时候用F11跟进函数里去，然后一层层进去，再一层层退出来，这样就比较好理清思路了。

是的，得一层层进去再最终找到入口了
