### ISSUE TITLE
layout analysis 版面分析模型无法训练

### ISSUE THREAD

**Issue by Leezzzzz** [PaddlePaddle/PaddleDetection#7144]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

版面分析模型无法训练，总是在下载好预训练模型后就卡住无法往下运行然后程序就自动推出。没有任何结果返回。数据集采用的是个人制作的coco数据集。
![record3](https://user-images.githubusercontent.com/62826242/196593711-7a6ccf7b-57a7-43e9-8a1b-a9d0f55e669d.PNG)
经过调试发现trainer.py中的self.loader这个数据加载器无法从里面正常读取数据，读取数据的for循环无法正常跳出。在读取最后一个数据后依旧执行for循环从loader中读取数据。调整batchsize也没有效果
![record](https://user-images.githubusercontent.com/62826242/196594004-179cfe22-dfc6-40a3-8d10-28bf3b99481d.PNG)
对配置文件picodet_lcnet_x1_0_layout.yml的配置如下
![record1](https://user-images.githubusercontent.com/62826242/196594129-ded3cb20-b44d-4396-923a-768e9c396235.PNG)
![record2](https://user-images.githubusercontent.com/62826242/196594134-fd272dbe-6fd3-4208-aaa3-01da8e0f6858.PNG)

### 复现环境 Environment

-OS: Windows
-paddlepaddle: 2.2.2
-python:3.7
-cuda:10.2
-cudnn：7.6

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
感觉是环境的问题，可以先在python环境中运行以下命令确认下是否正确安装试下
``` python
import paddle

paddle.utils.run_check()
```

**Comment by Leezzzzz** [comment]
paddle2.2和2.3都装过，都存在这个问题，在不同电脑上试过也存在同样的问题

**Comment by wangxinxin08** [comment]
> 感觉是环境的问题，可以先在python环境中运行以下命令确认下是否正确安装试下
> 
> ```python
> import paddle
> 
> paddle.utils.run_check()
> ```

这个命令能正常运行吗？

**Comment by Leezzzzz** [comment]
可以

**Comment by an1018** [comment]
可以先确认下数据格式有没有问题呢，比如用COCO代码读取、或在其他模型训练看是否存在相同的问题
