### ISSUE TITLE
PaddleYOLO模型库中导出的模型是否可以用于中的目标跟踪？

### ISSUE THREAD

**Issue by Hyperjunct** [PaddlePaddle/PaddleDetection#7146]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问PaddleYOLO模型库中的导出模型是否可以直接用于跟踪时的目标检测？

**Comment by nemonameless** [comment]
PaddleYOLO模型库中的模型都是COCO 80类。PP-Tracking中的跨镜头跟踪是只有1类车辆。
PPYOLOE的车辆模型已有提供 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/ppvehicle
你要用其他检测器，得用你的数据集重新训下或fintune下，然后带nms地导出即可，参考 https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.5/docs/MODEL_ZOO_cn.md 部署模型表格中的 导出后的权重(w NMS)

**Comment by Hyperjunct** [comment]
> PaddleYOLO模型库中的模型都是COCO 80类。PP-Tracking中的跨镜头跟踪是只有1类车辆。 PPYOLOE的车辆模型已有提供 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/ppvehicle 你要用其他检测器，得用你的数据集重新训下或fintune下，然后带nms地导出即可，参考 https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.5/docs/MODEL_ZOO_cn.md 部署模型表格中的 导出后的权重(w NMS)

我已成果使用yolov7和ppyoloe+导出后的模型替换车辆mtmct中原有的ppyolov2检测器进行跨境跟踪，感谢您的回答！

**Comment by nemonameless** [comment]
欢迎贡献PR！

**Comment by Hyperjunct** [comment]
> 欢迎贡献PR！

我就是在deploy/pptracking/python/mtmct_cfg.yml的配置文件中修改了camera_bias，加了一行c005: 0
![微信截图_20221104215642](https://user-images.githubusercontent.com/98454125/199990068-4a7795fb-9662-4b18-b132-436b5609e9fd.png)
并在--mtmct_dir文件夹下配置同名的视频文件，运行deploy/pptracking/python/mot_sde_infer.py即可
