### ISSUE TITLE
tinypose训练模型转化为deploy模型异常！！！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleDetection#7149]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

按照官方链接和文档 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/keypoint/tiny_pose
进行tinypose模型的转换，如下图所示 从花圈的1 转化为 2 ，发现使用网页推荐的命令 
python3 tools/export_model.py -c configs/keypoint/tiny_pose/tinypose_128x96.yml --output_dir=outut_inference -o weights=output/tinypose_128x96/model_final TestReader.fuse_normalize=true
 和 python3 tools/export_model.py -c configs/keypoint/tiny_pose/tinypose_128x96.yml --output_dir=outut_inference -o weights=output/tinypose_128x96/model_final TestReader.fuse_normalize=false
从pdparams和yml转化出来的 pdmodel 跟文档中给出的模型 https://bj.bcebos.com/v1/paddledet/models/keypoint/tinypose_256x192.pdparams 结果不同。
![4fb2a0038598d905749464a62d72d5f](https://user-images.githubusercontent.com/8407513/196641628-3b1d9fa6-969d-4780-8aa5-7b434368821a.jpg)

请问下，是否可以帮忙检查下如何才能顺利的导出与https://bj.bcebos.com/v1/paddledet/models/keypoint/tinypose_256x192.pdparams 结果一致的模型呢？

### 复现环境 Environment

paddle2onnx                   1.0.1
paddledet                     2.5.0
paddlepaddle-gpu              2.3.1.post112
Python 3.8.10 
GCC 9.4.0
CUDA Version: 11.7

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
实际上导出模型并没有多少特殊的操作，基本只需要注意这一个选项：TestReader.fuse_normalize
如果导出模型和已有导出模型结果不同，智能说明两者并不是同一个模型，没有其他的东西

**Comment by 2050airobert** [comment]
理论上确实如此，但实际我采用的模型都是官方发布的，也就是在上述链接上直接拿下来的，麻烦现在能否帮忙check下呢？
您可以直接尝试从1到2转化一次吗？

**Comment by 2050airobert** [comment]
或者说 是不是我用的python3 tools/export.py 的ppdet 或者paddlepaddle版本不对呢？  这块您有什么发现吗？

**Comment by MianMianMeow** [comment]
我也遇到了同样问题，请问您解决了么？
