### ISSUE TITLE
PPYOLOE在导出的时候不想带post_process和nms，应该如何操作？

### ISSUE THREAD

**Issue by LiLiLiam** [PaddlePaddle/PaddleDetection#7150]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如题，需要把PPYOLOE的模型部署在嵌入式设备上，paddle-lite的性能不理想，所以需要转换成其他框架，但是head中的post_process和nms在转换过程中不支持，如果才能导出不带post_process和nms的模型？

**Comment by wangxinxin08** [comment]
可以加上`exclude_post_process=True`这样一个flag，比如
```
python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml -o weights=/path/to/weights exclude_post_process=True
```

**Comment by LiLiLiam** [comment]
试过了没有作用，导出的模型依然带有后处理，而且查看PaddleDetection\ppdet\modeling\architectures\yolo.py里的class YOLOv3，这个类也不带有self.exclude_post_process属性，也试过手动添加这个属性，但是依然不起作用

**Comment by wangxinxin08** [comment]
代码在这里https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/modeling/heads/ppyoloe_head.py#L373 你可能命令敲错了在试一下，exclude_post_process=True必须要在-o 之后，且只能存在一个-o

**Comment by Sco-cai** [comment]
请问你的问题解决了吗？我遇到相同的问题，使用文档上的：python tools/export_model.py \
        -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml \
        -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_s_300e_coco.pdparams \
        trt=True exclude_nms=True \
依旧是保留有nms

**Comment by wangxinxin08** [comment]
@Sco-cai 看上面的回答
```
python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml -o weights=/path/to/weights trt=True exclude_post_process=True
```
另外，exclude_nms也不会包含nms

**Comment by lgy2830** [comment]
> ### 问题确认 Search before asking
> 
>     * [x]  我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> 
> 
> ### 请提出你的问题 Please ask your question
> 
> 如题，需要把PPYOLOE的模型部署在嵌入式设备上，paddle-lite的性能不理想，所以需要转换成其他框架，但是head中的post_process和nms在转换过程中不支持，如果才能导出不带post_process和nms的模型？

你好，你把nms去掉的话，应该要自己实现nms的，你有相关的代码吗？

**Comment by 851532562** [comment]
> 试过了没有作用，导出的模型依然带有后处理，而且查看PaddleDetection\ppdet\modeling\architectures\yolo.py里的class YOLOv3，这个类也不带有self.exclude_post_process属性，也试过手动添加这个属性，但是依然不起作用

请问下你的问题解决了吗，我导出ppyoloe r 也遇到了同样的问题
