### ISSUE TITLE
Tinypose augumentation detailed！！！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleDetection#7155]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi,
请问下
1 tinypose 训练的时候，采用了哪些数据增广呢？是否有针对不同的物体或者人 检测框box 尺寸和大小随机调整的数据增广呢？ 具体文档链接是？
2 就是说假如前面输入的人检测出来的box 比人要大的多而且尺寸 宽高比也很异常，那么这种情况的数据增广是怎么处理的呢？ 具体代码体现在哪个地方呢？ 具体代码位置是？
3 gt框 一般比较准确，万一检测box不准确的时候，怎样去学习检测框box 偏差大 尺寸和宽高比都异常的情况，怎么去做相应的数据增广呢？多谢

BR

**Comment by zhiboniu** [comment]
1. 检测框box 尺寸和大小随机调整。这类调整都在仿射变换里，是关键点训练的通用增强方式，可以百度搜索一下。
2、3问题本质是检测模型效果有问题，这类问题无法通过后处理修正，应该提升检测模型效果。

**Comment by 2050airobert** [comment]
hi，zhibo
      我想问下
1  keypoint_operators.py 文件里 class RandomFlipHalfBodyTransform(object):  里的     def halfbody_transform(self, joints, joints_vis):
       如下图的 scale 变量为啥会在config 文件默认配置的 self.pixel_std = 200 后面还要     scale = scale * 1.5 ，这是为什么呢？
![image](https://user-images.githubusercontent.com/8407513/197199020-ec720c58-393d-47d7-bcae-1940cdf9e7c0.png)
2  后面在上面的scale基础上又乘以一个数值，   但为什么这个数值会跟half_bodyXXX等参数相关呢？这是为什么要这么取值呢？  为啥不直接在gt box的基础上进行缩放或者scale，不是更简单吗？  
如下图所示：
 if (np.sum(joints_vis[:, 0]) > self.num_joints_half_body and
               np.random.rand() < self.prob_half_body):

![image](https://user-images.githubusercontent.com/8407513/197199927-2cf037db-fa88-4679-8290-88eee55d2bae.png)

 期待您的答复，多谢
BR

**Comment by zhiboniu** [comment]
1. 这里的1.5是一个范围扩充，增大图片范围。
2. 这里的scale是一个随机增强的缩放值，目的是适应各种尺寸。
上述两者目的不同
