### ISSUE TITLE
多摄像头跟踪是否支持三个及以上的视频输入？

### ISSUE THREAD

**Issue by Hyperjunct** [PaddlePaddle/PaddleDetection#7157]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问该算法框架是否支持三个及以上的视频输入？

**Comment by nemonameless** [comment]
暂不支持3个以上，提供的是比较基础的方案，有资源的话最好在自己的数据集上训练一下检测和reid。
