### ISSUE TITLE
你好，行人跨境跟踪，可以实时吗？

### ISSUE THREAD

**Issue by 140ai** [PaddlePaddle/PaddleDetection#7161]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我试了用三个rtsp链接运行pphuman，但是 mtmct 是在检测结束后再运行，是不是这版本不支持实时，只能用视频文件呢

**Comment by zhiboniu** [comment]
目前还不能支持实时的reid跨镜哦，只能支持离线完成后的匹配
