### ISSUE TITLE
convert ppyoloe_plus_crn_s_80e_coco  to onnx is ok, but from ppyoloe_plus_crn_s_80e_coco.onnx to ppyoloe_plus_crn_s_80e_coco.rknn is error

### ISSUE THREAD

**Issue by winterxx** [PaddlePaddle/PaddleDetection#7166]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

convert ppyoloe_plus_crn_s_80e_coco  to onnx is ok, but from ppyoloe_plus_crn_s_80e_coco.onnx to ppyoloe_plus_crn_s_80e_coco.rknn is error:
W The follow op is not support : ['Resize']
W Not match tensor Reshape_p2o.Reshape.19:out0 
E Try match layer: Reshape_p2o.Reshape.19:out0 failed!

### 复现环境 Environment

linux
paddle:2.2.3

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
请安装最新版的paddle和paddle2onnx，比如pip卸载再重新安装。
也可以前往 https://github.com/PaddlePaddle/Paddle2ONNX/issues 提问
