### ISSUE TITLE
关于paddlevideo的配置文件pptsm_fight_frames_dense.yaml和main.py里train_model_multigrid()模型评估方法

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#7168]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问这个模型评估代码的配置文件参数和代码是不是匹配不上
![image](https://user-images.githubusercontent.com/104432024/197166696-77953505-85ec-4838-923a-a8474dc250a0.png)
这个cfg.MULTIGRID.LONG_CYCLE在pptsm_fight_frames_dense.yaml根本不存在，还是我的yml选择错了？

**Comment by vvvweivv** [comment]
版主可以联系我这个邮箱，那个邮箱邮件不常用。3q
