### ISSUE TITLE
在aistudio上，使用ppyoloe_crn_l_300e_coco训练，aistudio上的数据集，gpu执行，多次执行都崩溃

### ISSUE THREAD

**Issue by lifw555** [PaddlePaddle/PaddleDetection#7169]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

istudio@jupyter-2276827-4851948:~/PaddleDetection$ python tools/train.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar --eval
loading annotations into memory...
Done (t=25.23s)
creating index...
index created!
[10/22 08:09:15] ppdet.data.source.coco WARNING: Found an invalid bbox in annotations: im_id: 200365, area: 0.0 x1: 296.65, y1: 388.33, x2: 297.67999999999995, y2: 388.33.
[10/22 08:09:29] ppdet.data.source.coco WARNING: Found an invalid bbox in annotations: im_id: 550395, area: 0.0 x1: 9.98, y1: 188.56, x2: 15.52, y2: 188.56.
W1022 08:09:34.471825 22388 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W1022 08:09:34.477408 22388 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
[10/22 08:09:42] ppdet.utils.download INFO: Downloading CSPResNetb_l_pretrained.pdparams from https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_l_pretrained.pdparams
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 82803/82803 [00:12<00:00, 6467.74KB/s]
[10/22 08:09:55] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/aistudio/.cache/paddle/weights/CSPResNetb_l_pretrained.pdparams

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1666397395 (unix time) try "date -d @1666397395" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 22388 (TID 0x7f468c57e700) from PID 0 ***]

Segmentation fault (core dumped)

![image](https://user-images.githubusercontent.com/2245040/197307159-b82557cb-de66-4d99-a7c0-35d43944290f.png)

### 复现环境 Environment

- OS:linux (https://aistudio.baidu.com/)
- PaddlePaddle: 2.3.2
- PaddleDetection: release/2.5
- Python:3.7.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
aistudio 环境重启试试

**Comment by lifw555** [comment]
> aistudio 环境重启试试

无意中尝试重新安装了依赖，就都好了，可能是依赖安装过程中出问题导致。

谢谢。
