### ISSUE TITLE
ResNeSt入篮

### ISSUE THREAD

**Issue by sleeplessai** [PaddlePaddle/PaddleDetection#717]
[https://arxiv.org/abs/2004.08955](ResNeSt)
[https://github.com/zhanghang1989/ResNeSt](zhanghang1989/ResNeSt)
目前是ResNet的最强版本，据说价值一百万刀，建议复现，入篮backbone。

**Comment by qingqing01** [comment]
@sleeplessai 感谢建议和关注，PaddleClas已经在做这个模型了，分类复现完成后，会加到检测里

**Comment by sleeplessai** [comment]
@qingqing01 持续关注，非常期待。
