### ISSUE TITLE
请问：PP-YOLOE+_s，PP-YOLOE+_m，PP-YOLOE+_l，PP-YOLOE+_x这里的：s/m/l/x 都表示什么意思？

### ISSUE THREAD

**Issue by lifw555** [PaddlePaddle/PaddleDetection#7170]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

问题如题，
本人新手小白，已经百度，google过了，也在飞桨的官网和aistudio中搜索了，没有找到对应的说明，也可能是我搜索的方式不对。

请帮忙解惑。谢谢。

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/7087

**Comment by XYZ-916** [comment]
s/m/l/x 按照顺序模型体积参数量越来越大。具体通过下面两个参数配置：
depth_mult (float): Depth multiplier, multiply number of channels in each layer, default as 1.0.
width_mult (float): Width multiplier, multiply number of blocks in CSPLayer, default as 1.0.

**Comment by lifw555** [comment]
感谢！
