### ISSUE TITLE
热力图绘制

### ISSUE THREAD

**Issue by NwTbbetter** [PaddlePaddle/PaddleDetection#7172]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问在PaddleDetection下怎么实现热力图的绘制？

**Comment by XYZ-916** [comment]
请问您想把什么数据绘制成热力图？

**Comment by NwTbbetter** [comment]
> 请问您想把什么数据绘制成热力图？

啥叫什么数据呀？就是想要了解倒图片中各个区域对模型作出预测的影响有多大

**Comment by XYZ-916** [comment]
> > 请问您想把什么数据绘制成热力图？
> 
> 啥叫什么数据呀？就是想要了解倒图片中各个区域对模型作出预测的影响有多大

可以了解下CAM、Grad-CAM、Contrastive EBP等。

**Comment by xs1997zju** [comment]
You  can try this: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/docs/tutorials/GradCAM_cn.md
