### ISSUE TITLE
关于paddlevideo的配置文件pptsm_fight_frames_dense.yaml和main.py里train_model_multigrid()模型评估方法 

### ISSUE THREAD

**Issue by vvvweivv** [PaddlePaddle/PaddleDetection#7173]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

问题确认 Search before asking
 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
请提出你的问题 Please ask your question
请问这个模型评估代码的配置文件参数和代码是不是匹配不上
![image](https://user-images.githubusercontent.com/104300389/197430431-5d662e07-56de-4592-92ac-822ce7183f9f.png)
这个cfg.MULTIGRID.LONG_CYCLE在pptsm_fight_frames_dense.yaml根本不存在，还是我的yml选择错了？

**Comment by XYZ-916** [comment]
不存在的话采用默认配置。

**Comment by vvvweivv** [comment]
能不能稍微再清楚点？

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月24日 11:28
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [PaddlePaddle/PaddleDetection] 关于paddlevideo的配置文件pptsm_fight_frames_dense.yaml和main.py里train_model_multigrid()模型评估方法 (Issue #7173)


不存在的话采用默认配置。

―

**Comment by XYZ-916** [comment]
> 
请问你训练的时候加了--multigrid参数吗？

**Comment by vvvweivv** [comment]
没有啊。我刚开始学习，我按着markdown命令来的。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月24日 13:49
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [PaddlePaddle/PaddleDetection] 关于paddlevideo的配置文件pptsm_fight_frames_dense.yaml和main.py里train_model_multigrid()模型评估方法 (Issue #7173)


请问你训练的时候加了--multigrid参数吗？

―

**Comment by XYZ-916** [comment]
如果没有启用multigrid训练，cfg.MULTIGRID.LONG_CYCLE等参数是用不到的。

**Comment by vvvweivv** [comment]
好的，谢谢

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月24日 15:53
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [PaddlePaddle/PaddleDetection] 关于paddlevideo的配置文件pptsm_fight_frames_dense.yaml和main.py里train_model_multigrid()模型评估方法 (Issue #7173)


如果没有启用multigrid训练，cfg.MULTIGRID.LONG_CYCLE等参数是用不到的。

―
