### ISSUE TITLE
小目标检测中，同一张图裁剪出的多张子图可不可以按一整批做一次推理，而不是一张一张子图推理

### ISSUE THREAD

**Issue by xdg2016** [PaddlePaddle/PaddleDetection#7174]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 2. 需求场景（请描述你的项目中为什么需要用此功能）; 3. 功能描述（请简单描述或设计这个功能）

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by XYZ-916** [comment]
可以的，推理的时候可以设定batch_size

**Comment by xdg2016** [comment]
@XYZ-916 谢谢，刚才试了，检测后处理有nms，然后在batch=8的时候就会报错

**Comment by XYZ-916** [comment]
> 

能不能把你的运行命令和错误贴出来看下。

**Comment by xdg2016** [comment]
这个是vscode的调试命令：
![image](https://user-images.githubusercontent.com/16351823/197444578-151e339f-1dfa-42d7-955c-e82c377e983e.png)
修改了训练的配置文件：
![image](https://user-images.githubusercontent.com/16351823/197445113-c57af26b-bcbc-4826-9bcb-cae3895585b5.png)
报错信息：
![image](https://user-images.githubusercontent.com/16351823/197445054-03848014-067d-43fa-ad96-bcc955c557c5.png)

**Comment by nemonameless** [comment]
子图暂时不支持任意组batch，有左上角像素起点限制。

**Comment by xdg2016** [comment]
好的，谢谢
