### ISSUE TITLE
目标多相机跟踪是否有论文出处？

### ISSUE THREAD

**Issue by Hyperjunct** [PaddlePaddle/PaddleDetection#7177]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问一下paddle提供的多相机跟踪demo是否有发表过相关论文?

**Comment by nemonameless** [comment]
#7130 
是一个很基础的方案，没有论文，数据集是AI City Challenge的数据集，每年有专门车辆reid和车辆MTMCT的比赛，想要更高精度可以自行搜索比赛方案。https://www.aicitychallenge.org  ,   https://github.com/NVIDIAAICITYCHALLENGE

**Comment by Hyperjunct** [comment]
> #7130 是一个很基础的方案，没有论文，数据集是AI City Challenge的数据集，每年有专门车辆reid和车辆MTMCT的比赛，想要更高精度可以自行搜索比赛方案。https://www.aicitychallenge.org , https://github.com/NVIDIAAICITYCHALLENGE

请问是否有相关文档对整个mtmct算法框架的流程进行解读吗，作为新手想深入学习一下，谢谢！
