### ISSUE TITLE
训练时出错

### ISSUE THREAD

**Issue by Young-GG** [PaddlePaddle/PaddleDetection#7178]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![图片](https://user-images.githubusercontent.com/93699131/197676226-dfc99057-d92e-4827-be12-0728f02601eb.png)
训练时出现：Target 784 is out of upper bound.的问题，应该如何解决

**Comment by jerrywgz** [comment]
windows建议使用oaddle 2.2版本，同时更新paddledetection到最新版本训练
