### ISSUE TITLE
pp-human  中的人体摔倒检测 支持tensorrt  加速吗？

### ISSUE THREAD

**Issue by lw-2017** [PaddlePaddle/PaddleDetection#7182]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

pp-human  中的人体摔倒检测 支持tensorrt  加速吗？

**Comment by jerrywgz** [comment]
支持的，启动的时候设置run_model=trt_fp16即可
