### ISSUE TITLE
mot_ppyoloe_l_36e_ppvehicle模型服务部署

### ISSUE THREAD

**Issue by gitmhg** [PaddlePaddle/PaddleDetection#7183]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/serving
部署mot_ppyoloe_l_36e_ppvehicle模型，我看官方给的样例是yolov3，我使用的是mot_ppyoloe_l_36e_ppvehicle预训练模型，已经成功启动服务，但是在test_client出错：
ValueError: Failed to fetch, maybe the type of [multiclass_nms3_0.tmp_0] is wrong, please check the model file
下面两个是我的模型文件
[serving_server_conf.prototxt.txt](https://github.com/PaddlePaddle/PaddleDetection/files/9858153/serving_server_conf.prototxt.txt)
[serving_client_conf.prototxt.txt](https://github.com/PaddlePaddle/PaddleDetection/files/9858154/serving_client_conf.prototxt.txt)

**Comment by ghostxsl** [comment]
请问你使用的paddle、paddle-serving版本是多少？

**Comment by ghostxsl** [comment]
你也可以参考文档：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/serving/python

**Comment by gitmhg** [comment]
> 请问你使用的paddle、paddle-serving版本是多少？
感谢回复
paddle-bfloat             0.1.7
paddle-serving-app        0.9.0
paddle-serving-client     0.9.0
paddle-serving-server-gpu 0.9.0.post112
paddleclas                2.4.3
paddlepaddle-gpu          2.3.2.post116

**Comment by gitmhg** [comment]
> 

我跑yolov3可以成功，但是换成ppyolo就失败，除了prototxt文是否哪个环节需要自己定义，

**Comment by ghostxsl** [comment]
这个prototxt是在export_model的时候生成的，你用的是生成的还是文档里的？

**Comment by gitmhg** [comment]
> 这个prototxt是在export_model的时候生成的，你用的是生成的还是文档里的？

对于mot_ppyoloe_l_36e_ppvehicle这个模型，我用的生成的

**Comment by ghostxsl** [comment]
你导出的模型能发一下看看嘛？

**Comment by ghostxsl** [comment]
> > 这个prototxt是在export_model的时候生成的，你用的是生成的还是文档里的？
> 
> 对于mot_ppyoloe_l_36e_ppvehicle这个模型，我用的生成的

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/serving/test_client.py#L39
需要根据prototxt修改这一行，这个demo易用性差一点，建议你使用新的demo试试看呢： https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/serving/python

**Comment by gitmhg** [comment]
> > > 这个prototxt是在export_model的时候生成的，你用的是生成的还是文档里的？
> > 
> > 
> > 对于mot_ppyoloe_l_36e_ppvehicle这个模型，我用的生成的
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/serving/test_client.py#L39 需要根据prototxt修改这一行，这个demo易用性差一点，建议你使用新的demo试试看呢： https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/serving/python

感谢回复，我试试，还有个问题人员属性分类我是参考https://github.com/PaddlePaddle/PaddleClas/tree/release/2.5/deploy/paddleserving#321-python-serving
但是出现问题https://github.com/PaddlePaddle/Serving/issues/1870，
有没有类似可参考的工程

**Comment by ghostxsl** [comment]
> 

这个问题我看着像是feed_list参数输入不对，你可以自己debug一下看看，具体的可以等Serving的开发者解答

**Comment by ghostxsl** [comment]
可以参考我刚给你发的demo看看，serving这个我理解你只要对齐feed_tensors和fetch_tensors后，直接调用serving的api就好了

**Comment by gitmhg** [comment]
> 可以参考我刚给你发的demo看看，serving这个我理解你只要对齐feed_tensors和fetch_tensors后，直接调用serving的api就好了

谢谢解答，对于paddlecls分类模型部署，[pipeline_http_client.py](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/deploy/paddleserving/pipeline_http_client.py)是否都是一样的，我感觉这块对于不同的模型需要修改pipeline_http_client.py，因为我的服务能正常拉起来，但是客户端发送请求失败并显式输入不正确，

**Comment by ghostxsl** [comment]
> > 可以参考我刚给你发的demo看看，serving这个我理解你只要对齐feed_tensors和fetch_tensors后，直接调用serving的api就好了
> 
> 谢谢解答，对于paddlecls分类模型部署，[pipeline_http_client.py](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/deploy/paddleserving/pipeline_http_client.py)是否都是一样的

这个跟模型无关，但是你可能需要修改web_service.py这个文件

**Comment by gitmhg** [comment]
> 

好的，非常感谢

**Comment by gitmhg** [comment]
> 还有个问

你好，我根据你的链接部署mot_ppyoloe_s_36e_ppvehicle模型服务，出现以下问题
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
config use_encryption model here None
[DAG] Succ init
[PipelineServicer] succ init
2022/10/27 10:10:34 start proxy service
W1027 10:10:35.545841 214594 analysis_predictor.cc:1118] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I1027 10:10:35.580128 214594 analysis_predictor.cc:985] ir_optim is turned off, no IR pass will be executed
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I1027 10:10:35.633138 214594 ir_params_sync_among_devices_pass.cc:100] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I1027 10:10:35.674618 214594 memory_optimize_pass.cc:216] Cluster name : scale_factor  size: 8
I1027 10:10:35.674634 214594 memory_optimize_pass.cc:216] Cluster name : batch_norm_54.tmp_1  size: 384
I1027 10:10:35.674638 214594 memory_optimize_pass.cc:216] Cluster name : reshape2_1.tmp_0  size: 1600
I1027 10:10:35.674639 214594 memory_optimize_pass.cc:216] Cluster name : pool2d_0.tmp_0  size: 307200
I1027 10:10:35.674641 214594 memory_optimize_pass.cc:216] Cluster name : swish_36.tmp_0  size: 614400
I1027 10:10:35.674643 214594 memory_optimize_pass.cc:216] Cluster name : swish_27.tmp_0  size: 307200
I1027 10:10:35.674645 214594 memory_optimize_pass.cc:216] Cluster name : swish_5.tmp_0  size: 2457600
I1027 10:10:35.674647 214594 memory_optimize_pass.cc:216] Cluster name : conv2d_111.tmp_0  size: 2457600
I1027 10:10:35.674649 214594 memory_optimize_pass.cc:216] Cluster name : swish_16.tmp_0  size: 3276800
I1027 10:10:35.674651 214594 memory_optimize_pass.cc:216] Cluster name : image  size: 4915200
I1027 10:10:35.674654 214594 memory_optimize_pass.cc:216] Cluster name : batch_norm_2.tmp_2  size: 13107200
I1027 10:10:35.674655 214594 memory_optimize_pass.cc:216] Cluster name : conv2d_108.tmp_0  size: 13107200
--- Running analysis [ir_graph_to_program_pass]
I1027 10:10:35.807643 214594 analysis_predictor.cc:1035] ======= optimize end =======
I1027 10:10:35.814424 214594 naive_executor.cc:102] ---  skip [feed], feed -> scale_factor
I1027 10:10:35.814443 214594 naive_executor.cc:102] ---  skip [feed], feed -> image
I1027 10:10:35.819341 214594 naive_executor.cc:102] ---  skip [multiclass_nms3_0.tmp_0], fetch -> fetch
I1027 10:10:35.819355 214594 naive_executor.cc:102] ---  skip [multiclass_nms3_0.tmp_2], fetch -> fetch
[OP Object] init success
W1027 10:13:15.963457 214594 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.6
W1027 10:13:15.968137 214594 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
Process Process-2:
Traceback (most recent call last):
  File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/site-packages/paddle_serving_server/pipeline/operator.py", line 1509, in _run
    = self._run_postprocess(parsed_data_dict, midped_data_dict, op_info_prefix, logid_dict)
  File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/site-packages/paddle_serving_server/pipeline/operator.py", line 1221, in _run_postprocess
    err, _ = ChannelData.check_npdata(postped_data)
  File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/site-packages/paddle_serving_server/pipeline/channel.py", line 172, in check_npdata
    value, list) and isinstance(value[0], str)):
IndexError: list index out of range
我怀疑是推理配置文件的问题
这个是我导出mot_ppyoloe_s_36e_ppvehicle模型生成的推理配置文件
[infer_cfg.yml.txt](https://github.com/PaddlePaddle/PaddleDetection/files/9875154/infer_cfg.yml.txt)
mot_ppyoloe_s_36e_ppvehicle模型是基于ppyoloe构建的，但是生成的推理配置文件中显式是基于yolov和coco数据集的
![image](https://user-images.githubusercontent.com/51695758/198176077-82c412e6-4b3e-4c43-ae57-e5645eb99382.png)

**Comment by ghostxsl** [comment]
模型发一下

**Comment by gitmhg** [comment]
> 模型发一下

链接：https://pan.baidu.com/s/1AgRZmy7obh7Oj4YXU2ZALQ 
提取码：6666

**Comment by ghostxsl** [comment]
> > 还有个问
> 
> ## 你好，我根据你的链接部署mot_ppyoloe_s_36e_ppvehicle模型服务，出现以下问题
> ----------- Model Configuration -----------
> Model Arch: YOLO
> Transform Order:
> --transform op: Resize
> --transform op: NormalizeImage
> --transform op: Permute
> config use_encryption model here None [DAG] Succ init [PipelineServicer] succ init 2022/10/27 10:10:34 start proxy service W1027 10:10:35.545841 214594 analysis_predictor.cc:1118] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect. I1027 10:10:35.580128 214594 analysis_predictor.cc:985] ir_optim is turned off, no IR pass will be executed --- Running analysis [ir_graph_build_pass] --- Running analysis [ir_graph_clean_pass] --- Running analysis [ir_analysis_pass] --- Running analysis [ir_params_sync_among_devices_pass] I1027 10:10:35.633138 214594 ir_params_sync_among_devices_pass.cc:100] Sync params from CPU to GPU --- Running analysis [adjust_cudnn_workspace_size_pass] --- Running analysis [inference_op_replace_pass] --- Running analysis [memory_optimize_pass] I1027 10:10:35.674618 214594 memory_optimize_pass.cc:216] Cluster name : scale_factor size: 8 I1027 10:10:35.674634 214594 memory_optimize_pass.cc:216] Cluster name : batch_norm_54.tmp_1 size: 384 I1027 10:10:35.674638 214594 memory_optimize_pass.cc:216] Cluster name : reshape2_1.tmp_0 size: 1600 I1027 10:10:35.674639 214594 memory_optimize_pass.cc:216] Cluster name : pool2d_0.tmp_0 size: 307200 I1027 10:10:35.674641 214594 memory_optimize_pass.cc:216] Cluster name : swish_36.tmp_0 size: 614400 I1027 10:10:35.674643 214594 memory_optimize_pass.cc:216] Cluster name : swish_27.tmp_0 size: 307200 I1027 10:10:35.674645 214594 memory_optimize_pass.cc:216] Cluster name : swish_5.tmp_0 size: 2457600 I1027 10:10:35.674647 214594 memory_optimize_pass.cc:216] Cluster name : conv2d_111.tmp_0 size: 2457600 I1027 10:10:35.674649 214594 memory_optimize_pass.cc:216] Cluster name : swish_16.tmp_0 size: 3276800 I1027 10:10:35.674651 214594 memory_optimize_pass.cc:216] Cluster name : image size: 4915200 I1027 10:10:35.674654 214594 memory_optimize_pass.cc:216] Cluster name : batch_norm_2.tmp_2 size: 13107200 I1027 10:10:35.674655 214594 memory_optimize_pass.cc:216] Cluster name : conv2d_108.tmp_0 size: 13107200 --- Running analysis [ir_graph_to_program_pass] I1027 10:10:35.807643 214594 analysis_predictor.cc:1035] ======= optimize end ======= I1027 10:10:35.814424 214594 naive_executor.cc:102] --- skip [feed], feed -> scale_factor I1027 10:10:35.814443 214594 naive_executor.cc:102] --- skip [feed], feed -> image I1027 10:10:35.819341 214594 naive_executor.cc:102] --- skip [multiclass_nms3_0.tmp_0], fetch -> fetch I1027 10:10:35.819355 214594 naive_executor.cc:102] --- skip [multiclass_nms3_0.tmp_2], fetch -> fetch [OP Object] init success W1027 10:13:15.963457 214594 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.6 W1027 10:13:15.968137 214594 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4. Process Process-2: Traceback (most recent call last): File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap self.run() File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/multiprocessing/process.py", line 93, in run self._target(*self._args, **self._kwargs) File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/site-packages/paddle_serving_server/pipeline/operator.py", line 1509, in _run = self._run_postprocess(parsed_data_dict, midped_data_dict, op_info_prefix, logid_dict) File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/site-packages/paddle_serving_server/pipeline/operator.py", line 1221, in _run_postprocess err, _ = ChannelData.check_npdata(postped_data) File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/site-packages/paddle_serving_server/pipeline/channel.py", line 172, in check_npdata value, list) and isinstance(value[0], str)): IndexError: list index out of range 我怀疑是推理配置文件的问题 这个是我导出mot_ppyoloe_s_36e_ppvehicle模型生成的推理配置文件 [infer_cfg.yml.txt](https://github.com/PaddlePaddle/PaddleDetection/files/9875154/infer_cfg.yml.txt) mot_ppyoloe_s_36e_ppvehicle模型是基于ppyoloe构建的，但是生成的推理配置文件中显式是基于yolov和coco数据集的 ![image](https://user-images.githubusercontent.com/51695758/198176077-82c412e6-4b3e-4c43-ae57-e5645eb99382.png)

这个报错我看了一下，是因为模型没有检测出物体，修复的PR已提：https://github.com/PaddlePaddle/PaddleDetection/pull/7205

**Comment by hyperion-thou** [comment]
File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/site-packages/paddle_serving_server/pipeline/channel.py", 
line 172, in check_npdata value, list) and isinstance(value[0], str)): 
IndexError: list index out of range

**Comment by gitmhg** [comment]
> File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/site-packages/paddle_serving_server/pipeline/channel.py", line 172, in check_npdata value, list) and isinstance(value[0], str)): IndexError: list index out of range
感谢回复，我将代码替换后还是会报同样的错，这个问题主要是因为图片中没有检测到对象，换个有对象的图片就好了

**Comment by ghostxsl** [comment]
不应该啊，我这边本地跑出来是不会报错的，你print一下results看看
https://github.com/PaddlePaddle/PaddleDetection/blob/e066d8d1abff729b0efc042a2e83e48d87898888/deploy/serving/python/web_service.py#L203
主要是return的results不能为空

**Comment by gitmhg** [comment]
> 不应该啊，我这边本地跑出来是不会报错的，你print一下results看看
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/e066d8d1abff729b0efc042a2e83e48d87898888/deploy/serving/python/web_service.py#L203
> 
> 
> 主要是return的results不能为空

这个是图片中没有车对象时，：
![image](https://user-images.githubusercontent.com/51695758/198226718-58e8d174-0559-4701-894d-9dbc6242a086.png)

这个是图片中有车是：
![image](https://user-images.githubusercontent.com/51695758/198226619-bcb1446f-53ec-443a-befc-bcd16e6107da.png)
我怀疑不止一处bug.


除此之外，我部署ppyoloe_crn_s_36e_pphuman模型时，图片中有人，但是却检测不到，我换了几个图片，依然是这种问题

**Comment by ghostxsl** [comment]
建议你最好先用deploy/python/infer.py预测一下看看，serving也是调用paddleinference的API，先确保模型正确才看serving的问题

**Comment by gitmhg** [comment]
> 最好先用deploy/python/infer.py预测一下看看，serving也是调用paddleinference的API，先确保模型正

好的，我还有一些疑问，劳烦您解答下
1、是否所有的模型都支持serving部署？我看一些模型不支持serving部署，例如人员摔倒等，
2、pipline和serving有啥区别

**Comment by ghostxsl** [comment]
> > 最好先用deploy/python/infer.py预测一下看看，serving也是调用paddleinference的API，先确保模型正
> 
> 好的，我还有一些疑问，劳烦您解答下 1、是否所有的模型都支持serving部署？我看一些模型不支持serving部署，例如人员摔倒等， 2、pipline和serving有啥区别

1. serving部署只是一种部署的手段，理论上所有模型都可以进行serving部署，人员摔倒只是没开发相关的demo
2. 有些任务比较简单，像图像分类，可以直接用模型进行推理；有些任务比较复杂，可能包含多个模型以及后处理等，像是人员摔倒这种case需要组合才能跑通。serving简单来讲就是启了一个http服务，后端嵌入模型推理或者pipeline等，接受http请求进行推理，再把结果返回给前端。所以两者只是部署的方式不同，你可以理解成pipeline是可以嵌入到serving的后端的

**Comment by gitmhg** [comment]
> > > 最好先用deploy/python/infer.py预测一下看看，serving也是调用paddleinference的API，先确保模型正
> > 
> > 
> > 好的，我还有一些疑问，劳烦您解答下 1、是否所有的模型都支持serving部署？我看一些模型不支持serving部署，例如人员摔倒等， 2、pipline和serving有啥区别
> 
> 1. serving部署只是一种部署的手段，理论上所有模型都可以进行serving部署，人员摔倒只是没开发相关的demo
> 2. 有些任务比较简单，像图像分类，可以直接用模型进行推理；有些任务比较复杂，可能包含多个模型以及后处理等，像是人员摔倒这种case需要组合才能跑通。serving简单来讲就是启了一个http服务，后端嵌入模型推理或者pipeline等，接受http请求进行推理，再把结果返回给前端。所以两者只是部署的方式不同，你可以理解成pipeline是可以嵌入到serving的后端的
**那有没有pipline serving 相关的demo,我看案例都是pipline 直接推理，没有启动serving服务**

**Comment by fusionshen** [comment]
> > > 可以参考我刚给你发的demo看看，serving这个我理解你只要对齐feed_tensors和fetch_tensors后，直接调用serving的api就好了
> > 
> > 
> > 谢谢解答，对于paddlecls分类模型部署，[pipeline_http_client.py](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/deploy/paddleserving/pipeline_http_client.py)是否都是一样的
> 
> 这个跟模型无关，但是你可能需要修改web_service.py这个文件

您好：
        PP-human中行人属性的Serving部署方案缺少Demo，因而我不能完成对mot_ppyoloe_l_36e和PPLCNet_x1_0这两个算子pre和post进行编写，我照搬PaddleOCR的det和rec的写法，web_service.py部署成功，但pipeline_http_client.py测试报错。
        能给点我任何建议吗？不胜感激。

**Comment by lgy2830** [comment]
你好，这个模型mot_ppyoloe_l_36e_ppvehicle我把后处理部分删掉后，转换为了engine模型，现在要测试这个engine模型，用c++，怎样自己写一个代码不用paddle的预测库去把这个engine模型跑起来。这个模型里没有后处理，后处理要自己写，预处理可也得自己写吧，现在太懵了，不知道怎么写

**Comment by Insert-Code** [comment]
```
Process Process-2:
Traceback (most recent call last):
File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/site-packages/paddle_serving_server/pipeline/operator.py", line 1509, in _run
= self._run_postprocess(parsed_data_dict, midped_data_dict, op_info_prefix, logid_dict)
File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/site-packages/paddle_serving_server/pipeline/operator.py", line 1221, in _run_postprocess
err, _ = ChannelData.check_npdata(postped_data)
File "/home/sysadmin/miniconda3/envs/byom/lib/python3.6/site-packages/paddle_serving_server/pipeline/channel.py", line 172, in check_npdata
value, list) and isinstance(value[0], str)):
IndexError: list index out of range
```
报这个错的原因的确是没有检测到数据，但根本原因还是paddle_serving_server/pipeline/channel.py 中的check_npdata 方法
```
        elif isinstance(npdata, dict):
            # batch_size = 1
            for _, value in npdata.items():
                if not isinstance(value, np.ndarray) and not (isinstance(
                        value, list) and isinstance(value[0], str)):
                    error_code = ChannelDataErrcode.TYPE_ERROR.value
                    error_info = "Failed to check data: the value " \
                            "of data must be np.ndarray, but get {}.".format(
                                    type(value))
```
没有做value的长度判断，就直接使用了value[0] 导致索引异常；
在不修改上述文件的情况下，修改web_service.py文件也可以解决。
```
    def parse_detection_result(self, input_dict, fetch_dict):
        bboxes = fetch_dict[GLOBAL_VAR['fetch_vars'][0]]
        bboxes_num = fetch_dict[GLOBAL_VAR['fetch_vars'][1]]
        if GLOBAL_VAR['model_config'].mask:
            masks = fetch_dict[GLOBAL_VAR['fetch_vars'][2]]
        idx = 0
        results = {}
        for img_name, num in zip(input_dict.keys(), bboxes_num):
            result = []
            bbox = bboxes[idx:idx + num]
            for line in bbox:
                if line[0] > -1 and line[1] > GLOBAL_VAR[
                        'model_config'].draw_threshold:
                    result.append(f"{int(line[0])} {line[1]} "
                                  f"{line[2]} {line[3]} {line[4]} {line[5]}")
            if len(result) > 0:
                results[img_name] = result
            idx += num
        return results
```
添加数据长度判断，治标不治本。
 ```
          if len(result) > 0:
                results[img_name] = result
```
