### ISSUE TITLE
C++部署PaddleDetection输出路径出错？

### ISSUE THREAD

**Issue by xiaoyuchen1998** [PaddlePaddle/PaddleDetection#7185]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

完全按照github上提供的[编译指南]操作(https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/cpp/docs/windows_vs2019_build.md)编译：
不过在使用可执行文件进行预测时输出路径总是输出图片路径
![image](https://user-images.githubusercontent.com/51957420/197725403-4f6adc37-d4de-49b0-84fc-0728492e800d.png)
![image](https://user-images.githubusercontent.com/51957420/197725652-90f72adc-df1c-4892-894d-cfa48bd2ce49.png)
最终把需要预测的图片放入根目录，根据程序显示的输出路径调整图片路径。才让预测结果在根目录的output文件夹成功输出
![image](https://user-images.githubusercontent.com/51957420/197726765-3516bfb2-4e1d-431f-a068-29fc70644c36.png)
![image](https://user-images.githubusercontent.com/51957420/197726821-2c11f8a7-01d4-48a1-bf8c-5592fc139008.png)
编译的代码没有修改，为什么output部分会出现问题呢？
个人的环境：
window10 vs2019 cuda11.2 cudnn8.2 tensorrt8.0.1.6 opencv3.4.6 [预测库使用官网对应预编译版本](https://paddleinference.paddlepaddle.org.cn/master/user_guides/download_lib.html#windows)

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/cpp/src/main.cc#L342 可以检查下这部分的路径生成是否有问题，windows下应该是需要先用相对路径

**Comment by xiaoyuchen1998** [comment]
路径生成的代码是一样的，而且你们样例也用的绝对路径没有出错啊。
如果用相对路径写入参数的话`main --model_dir=.\models --image_dir=.\images`  
输出结果会显示
![image](https://user-images.githubusercontent.com/51957420/198005669-78b05a0e-6885-4dfd-b3c3-13e0eac8c370.png)
还是有问题。
使用斜杠`main --model_dir=.\models --image_dir=./images`图片能检测出来，但是还是没有输出
![image](https://user-images.githubusercontent.com/51957420/198071263-d3b25452-511e-4366-83e0-00b135990113.png)
`--image_dir=images`信息和结果相同

我猜是因为https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/cpp/src/main.cc#L343 检测的是斜杠，改成检测反斜杠之后 ` image_file_path.substr(image_file_path.find_last_of('\\') + 1);`
![image](https://user-images.githubusercontent.com/51957420/198068437-22345267-6516-4490-ad63-72a3398f310d.png)
使用相对路径可以顺利输出，同时绝对路径也可以

windows确实使用反斜杠\作为路径分隔符。不过官方样例也是windows系统而且\\绝对路径没有问题。在csdn看到其他人/相对路径没有问题，为什么我要改一行的代码才行呢？

**Comment by lgy2830** [comment]
你好，请问你接着做追踪了吗？他这个模型是可以检测加追踪的。
