### ISSUE TITLE
没有YoloV4模型？

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/PaddleDetection#7188]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我没有看到YoloV4模型的代码, PaddleYolo也没有

https://paddlelite-demo.bj.bcebos.com/NNAdapter/models/PaddleDetection/yolov4_cspdarknet.tgz
这个yolov4的官方模型从何而来

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/static/configs/yolov4 是静态图模型。
release/2.5后移除了static静态图模型目录。
