### ISSUE TITLE
PaddleDetection/Paddle-Lite-目标跟踪问题

### ISSUE THREAD

**Issue by qiujianchen** [PaddlePaddle/PaddleDetection#7190]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

您好，我想问一下PaddleLite或者是PaddleDetection是否有目标检测+目标跟踪（例如YOLOv5+Deepsort）部署在Android移动端设备实现行人计数或者车辆计数或者钢筋计数等等的功能或者是实现样例呢？

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
暂时没有行人车辆跟踪。钢筋计数属于检测，检测相关的可以参考 https://github.com/PaddlePaddle/Paddle-Lite-Demo

**Comment by Edward-YS** [comment]
您好！请问现在实现了在Android端部署目标跟踪了吗？现在PaddleLite或者PaddleDetection基于的框架是什么？可以用GPU吗？
