### ISSUE TITLE
pp-humanv2调用摄像头失败报错

### ISSUE THREAD

**Issue by YaoOOoooolin** [PaddlePaddle/PaddleDetection#7192]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

命令行：
python C:\Users\13708\PaddleDetection\deploy\pipeline\pipeline.py --config deploy/pipeline/config/examples/infer_cfg_fall_down-Copy-local.yml --camera_id 0 --device=gpu

报错：

C:\Users\13708\PaddleDetection\deploy\pipeline\pipeline.py:24: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Sequence, defaultdict
-----------  Running Arguments -----------
KPT:
  batch_size: 8
  model_dir: output_inference/dark_hrnet_w32_256x192
MOT:
  batch_size: 1
  enable: true
  model_dir: output_inference/mot_ppyoloe_l_36e_pipeline
  tracker_config: deploy/pipeline/config/tracker_config.yml
SKELETON_ACTION:
  batch_size: 1
  coord_size:
  - 384
  - 512
  display_frames: 80
  enable: true
  max_frames: 50
  model_dir: output_inference/STGCN
crop_thresh: 0.5
kpt_thresh: 0.2
visual: true
warmup_frame: 50

------------------------------------------
Multi-Object Tracking enabled
SkeletonAction Recognition enabled
MOT  model dir:  output_inference/mot_ppyoloe_l_36e_pipeline
KPT  model dir:  output_inference/dark_hrnet_w32_256x192
SKELETON_ACTION  model dir:  output_inference/STGCN
-----------  Model Configuration -----------
Model Arch: STGCN
Transform Order:
--transform op: AutoPadding
--------------------------------------------
-----------  Model Configuration -----------
Model Arch: HRNet
Transform Order:
--transform op: TopDownEvalAffine
--transform op: Permute
--------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: Permute
--------------------------------------------
Traceback (most recent call last):
  File "C:\Users\13708\PaddleDetection\deploy\pipeline\pipeline.py", line 1103, in <module>
    main()
  File "C:\Users\13708\PaddleDetection\deploy\pipeline\pipeline.py", line 1088, in main
    pipeline = Pipeline(FLAGS, cfg)
  File "C:\Users\13708\PaddleDetection\deploy\pipeline\pipeline.py", line 89, in __init__
    self.predictor.set_file_name(self.input)
  File "C:\Users\13708\PaddleDetection\deploy\pipeline\pipeline.py", line 476, in set_file_name
    self.file_name = os.path.split(path)[-1]
  File "C:\Users\13708\AppData\Local\Programs\Python\Python39\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not int

**Comment by YaoOOoooolin** [comment]
<img width="376" alt="屏幕截图 2022-10-26 095844" src="https://user-images.githubusercontent.com/108522692/197919048-ca82abec-cf56-4017-9e26-8e44605e80a3.png">

**Comment by zhiboniu** [comment]
前面加一个判断，
if type(path)==int:
    self.file_name=path

**Comment by YaoOOoooolin** [comment]
> 前面加一个判断， if type(path)==int: self.file_name=path
<img width="360" alt="屏幕截图 2022-10-26 112000" src="https://user-images.githubusercontent.com/108522692/197926914-5d47bc0e-0da8-4e34-b39b-5ae26cf28d88.png">
 
还是之前的报错

**Comment by YaoOOoooolin** [comment]
<img width="628" alt="屏幕截图 2022-10-26 123215" src="https://user-images.githubusercontent.com/108522692/197935104-1534b254-3be9-4e37-b8ca-d49b91198ab6.png">

**Comment by hezhi1220** [comment]
![40e0931bbdc72628099e60dc7a85f26](https://user-images.githubusercontent.com/109505620/197954890-2fd5e4e1-4b56-4ae5-a4e8-9a23dd1ab7b3.jpg)
![a0a4dbcfce2763f84f3c9aa70430edc](https://user-images.githubusercontent.com/109505620/197954915-4a74eb3f-cafd-4d32-a6ce-c1abd75bad87.jpg)
还是一样的报错

**Comment by XYZ-916** [comment]
看下这个pr: https://github.com/PaddlePaddle/PaddleDetection/pull/7198/files
