### ISSUE TITLE
如何修改train log的保存路径？

### ISSUE THREAD

**Issue by monsterlyg** [PaddlePaddle/PaddleDetection#7193]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

记得以前好像还有一个--log_dir的参数，paddleDetection2.5 train的时候不知道怎么改默认路径参数，文件总是保存在根目录的log；如何修改？

**Comment by wangxinxin08** [comment]
python -m paddle.distributed.launch --log_dir $(LOG_DIR) --gpus 0,1,2,3 tools/train.py -c xxx
