### ISSUE TITLE
PP-TinyPose自然监控场景下的pose识别效果不佳

### ISSUE THREAD

**Issue by sunxirui310** [PaddlePaddle/PaddleDetection#7197]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，
我按照 [https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/keypoint/tiny_pose](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/keypoint/tiny_pose ) 最新发布的模型尝试了一下python 推理。

模型采用 单人模型配置 PicoDet-S-Lcnet-Pedestrian-192*192 + PP-TinyPose-128*96，并下好了模型。

推理命令是
`python deploy/python/det_keypoint_unite_infer.py --det_model_dir=output_inference/picodet_v2_s_192_pedestrian --keypoint_model_dir=output_inference/tinypose_128x96 --image_dir=./test --device=GPU`

部分图效果如下：
![hand_00026_vis](https://user-images.githubusercontent.com/19179730/198000413-a699ef05-8bdc-43a9-bf99-38a826573a28.jpg)

![SELF jiejing-1one_R6204_11_vis](https://user-images.githubusercontent.com/19179730/198000560-445970cb-5e28-47a2-ba71-cd353fb977c8.jpg)

![hand_00007_vis](https://user-images.githubusercontent.com/19179730/198000817-45247720-5d5f-4608-b058-555dc6b34048.jpg)

![MARKET 0613_c6s2_019293_01_vis](https://user-images.githubusercontent.com/19179730/198001015-10aa648e-9650-45f3-9bda-70eb0e129b48.jpg)

![hand_00004_vis](https://user-images.githubusercontent.com/19179730/198001143-c17e06e9-892d-4d2a-a023-236cce426497.jpg)

因此我想咨询一下，是不是测试某些细节没注意到？
谢谢

**Comment by sunxirui310** [comment]
附上原图
![MARKET 0613_c6s2_019293_01](https://user-images.githubusercontent.com/19179730/198002041-cc946fc8-da61-4e56-9d79-8ec54464abac.jpg)
![hand_00026](https://user-images.githubusercontent.com/19179730/198001957-324a6803-9271-40fc-a68f-0a1cc03f3066.jpg)
![SELF jiejing-1one_R6204_11](https://user-images.githubusercontent.com/19179730/198002011-9cabee4c-a5d4-47e5-b115-6217fde8eeb2.jpg)
![hand_00007](https://user-images.githubusercontent.com/19179730/198002162-1b89e876-e3a0-4cab-8643-f3d8b8adbe90.jpg)

![hand_00004](https://user-images.githubusercontent.com/19179730/198002253-4e8ab4e5-ff54-4fd2-874e-e485e513415d.jpg)

**Comment by zhiboniu** [comment]
开源数据与自然场景数据存在光线等细节的差异，会导致模型在自然场景效果差一些。建议：
1. 使用更大的tinypose256模型试试
2. 标注一批自然数据对模型进行finetune
