### ISSUE TITLE
PaddleDetection 目标检测微调 

### ISSUE THREAD

**Issue by JackMeiLong** [PaddlePaddle/PaddleDetection#7202]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好
PPOCRLabelv2 标注的目标检测数据，是否可以转换为VOC/COCO 格式，放到PaddleDetection中微调？

**Comment by XYZ-916** [comment]
可以的，只要数据符合VOC/COCO 格式规范，PaddleDetection就支持的。
