### ISSUE TITLE
pp-human v2抽烟检测报错 KeyError: 'DET'

### ISSUE THREAD

**Issue by gptq** [PaddlePaddle/PaddleDetection#7203]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

执行
!python deploy/pipeline/pipeline.py --config deploy/pipeline/config/examples/infer_cfg_smoking.yml --image_file=demo/000000014439_640x640.jpg --device=gpu

报错如下：

deploy/pipeline/pipeline.py:24: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sequence, defaultdict
-----------  Running Arguments -----------
ID_BASED_DETACTION:
  batch_size: 8
  display_frames: 80
  enable: true
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/ppyoloe_crn_s_80e_smoking_visdrone.zip
  skip_frame_num: 2
  threshold: 0.6
MOT:
  batch_size: 1
  enable: true
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_pipeline.zip
  tracker_config: deploy/pipeline/config/tracker_config.yml
crop_thresh: 0.5
visual: true
warmup_frame: 50

------------------------------------------
Multi-Object Tracking enabled
IDBASED Detection Action Recognition enabled
100%|████████████████████████████████| 186349/186349 [00:07<00:00, 25003.16KB/s]
MOT  model dir:  /home/aistudio/.cache/paddle/infer_weights/mot_ppyoloe_l_36e_pipeline
100%|██████████████████████████████████| 27194/27194 [00:00<00:00, 31835.57KB/s]
ID_BASED_DETACTION  model dir:  /home/aistudio/.cache/paddle/infer_weights/ppyoloe_crn_s_80e_smoking_visdrone
Traceback (most recent call last):
  File "deploy/pipeline/pipeline.py", line 1103, in <module>
    main()
  File "deploy/pipeline/pipeline.py", line 1088, in main
    pipeline = Pipeline(FLAGS, cfg)
  File "deploy/pipeline/pipeline.py", line 87, in __init__
    self.predictor = PipePredictor(args, cfg, self.is_video)
  File "deploy/pipeline/pipeline.py", line 369, in __init__
    det_cfg = self.cfg['DET']
KeyError: 'DET'

### 复现环境 Environment

拷贝自：https://aistudio.baidu.com/aistudio/projectdetail/4834683?channelType=0&channel=0
算力卡试过几个配置都一样。

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by jerrywgz** [comment]
基于图片输入时，配置文件中需要有DET相关配置项 抽烟的行为识别需要依赖视频输入

**Comment by platelee** [comment]
抽烟的行为识别一定要使用视频输入吗？如果只有图片可以支持吗？
