### ISSUE TITLE
ppyole+ infer 的时候存储的box.json 后期处理时无法直接对应到文件名。建议self._imid2path 也存储下来。

### ISSUE THREAD

**Issue by daodao316** [PaddlePaddle/PaddleDetection#7213]
### 问题描述 Please describe your issue

ppyole+ infer 的时候存储的box.json 后期处理时无法直接对应到文件名。建议self._imid2path 也存储下来。

**Comment by daodao316** [comment]
np.save('imid2path.npy', self._imid2path)

**Comment by daodao316** [comment]
是否有选项可以存储为类似COCO的标注的那种格式。

**Comment by lyuwenyu** [comment]
收到 我们会讨论一下

**Comment by xuyao91** [comment]
我也碰到这个问题，box.json出来的image_id与实际文件名无法对应

**Comment by planetb113** [comment]
同问

**Comment by WooXinyi** [comment]
> 收到 我们会讨论一下

请问有结果了吗

**Comment by sobikim** [comment]
#### workaround
- modify tools/infer.py

#### before
    run(FLAGS, cfg)

#### after
    cfg.metric = "RBOX"    
    run(FLAGS, cfg)

#### result >> 0000001_02999_d_0000005.txt
pedestrian 0.8723435997962952 580.0103759765625 450.3047180175781 15.74676513671875 37.91558837890625
...
