### ISSUE TITLE
paddleInference部署推理 设置--run_mode trt_fp16 加载时速度极慢,大概需要20分钟

### ISSUE THREAD

**Issue by deshuai666** [PaddlePaddle/PaddleDetection#7214]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

 python deploy/python/predict.py --model_dir=inference/ppyoloe_plus_crn_s_80e_coco \
            --run_mode trt_fp16 \
            --image_dir 1/in \
            --output_dir 1/out \
            --device=GPU --batch_size=1
![image](https://user-images.githubusercontent.com/33601373/198453608-61a689b3-1a2a-4ddf-9ccd-43779a1c00bb.png)
这里一直卡着不动，需要大概20分钟左右

### 复现环境 Environment

jetson ax nx

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
转trt-engine需要时间  不过这个你可以把第一次转的存下来 再使用时候就好了

**Comment by YinZhang98** [comment]
> 转trt-engine需要时间 不过这个你可以把第一次转的存下来 再使用时候就好了

您好，请问一下这个怎么存呢？我第一次弄这个，参考的这个链接https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/python
![image](https://user-images.githubusercontent.com/33601373/198487621-196af66a-07a8-4b24-8a29-0c5fa7b6196b.png)
参数里面没有找到存的方式

**Comment by wumeideqianbi** [comment]
> 转trt-engine需要时间 不过这个你可以把第一次转的存下来 再使用时候就好了

请问怎么存呀，以前没有用过不太懂

**Comment by patrickpy** [comment]
把use_stasitc设置为true
`
config.enable_tensorrt_engine(
            workspace_size=(1 << 25) * batch_size,
            max_batch_size=batch_size,
            min_subgraph_size=min_subgraph_size,
            precision_mode=precision_map[run_mode],
            use_static=True,
            use_calib_mode=trt_calib_mode)
`

**Comment by zyk23333** [comment]
> 把use_stasitc设置为true `config.enable_tensorrt_engine( workspace_size=(1 << 25) * batch_size, max_batch_size=batch_size, min_subgraph_size=min_subgraph_size, precision_mode=precision_map[run_mode], use_static=True, use_calib_mode=trt_calib_mode)`

你好，转存 之后仍会有几率需要重新转fp16，请问如何解决呢
