### ISSUE TITLE
复现S2ANet出现的精度问题

### ISSUE THREAD

**Issue by sherwin-silin-chen** [PaddlePaddle/PaddleDetection#7215]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Env：
4块11GB的2080Ti
按照官方教程复现S2ANet
数据集也是按照官方给出的进行剪切处理的

config没有改 直接跑的 s2anet_alignconv 2x的  在DOTA服务器上eval的结果mAP 59.07%
修改backbone 从resnetvd50->resnetvb50 mAP 71.19%

官方给出的结果应该为：
<img width="960" alt="image" src="https://user-images.githubusercontent.com/30338877/198454323-8456dc5e-5116-401b-b7b6-57656bc94cfe.png">

能给出训练过程的log 我排查一下问题

**Comment by wangxinxin08** [comment]
可以多跑几次看下，s2anet数据集精度存在波动，会出现从69~73的精度波动，这个问题暂时定位不出原因，可以尝试其他模型，精度会更稳定一些，https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/rotate
