### ISSUE TITLE
能不能直接将opencv的cv2.cuda_GpuMat 变量，直接转为 模型输入tensor

### ISSUE THREAD

**Issue by sqy2022** [PaddlePaddle/PaddleDetection#7222]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

能不能直接将opencv的cv2.cuda_GpuMat 变量，直接转为 模型输入tensor，我使用 飞桨目标检测的infer.py ， 里面提供的demo是使用opencv做前处理，但都是使用的CPU，能不能使用opencv的 cuda_GpuMat 做前处理，然后直接转入tensor做模型预测？

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ghostxsl** [comment]
paddle.to_tensor：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/api/paddle/to_tensor_cn.html#to-tensor
