### ISSUE TITLE
关于对应Paddle_inference库版本的问题

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleDetection#7224]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

当前PaddleDetection中C++的paddle_inference库下载，最高版本是2.2。   而PaddleOCR的paddle_inference已经支持2.4了。 
请问这两个的paddle_inference-2.2都是一样的吧？    如果想把两个程序联调起来使用，Paddledetectioon可以用大于2.2的推理库么？还是说两个都只能用paddle_inference-2.2的版本？

**Comment by XYZ-916** [comment]
可以试下高版本Paddle Inference是否存在问题。
