### ISSUE TITLE
MOT   选择SDE方案 可以使用检测标注的配置文件/configs/datasets/coco_detection.yml吗

### ISSUE THREAD

**Issue by BainOuO** [PaddlePaddle/PaddleDetection#7226]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如果用户选择SDE系列方案，是准备准检测标注的自定义数据集，则可以参照DET数据准备文档准备。

**Comment by nemonameless** [comment]
可以，请先阅读文档。
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/mot#mot%E6%95%B0%E6%8D%AE%E9%9B%86%E5%87%86%E5%A4%87

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/data/PrepareMOTDataSet.md

coco_detection.yml 里默认是COCO数据集，是80类的。你的数据集是需要做成COCO风格的格式，再自己改类别数。
