### ISSUE TITLE
MOT  使用JDE算法，自定义数据集的配置文件应该怎么写呢

### ISSUE THREAD

**Issue by BainOuO** [PaddlePaddle/PaddleDetection#7227]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

期待您的解答

**Comment by nemonameless** [comment]
请先阅读文档。
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/data/PrepareMOTDataSet.md

例子参照：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/mot/pedestrian/fairmot_dla34_30e_1088x608_visdrone_pedestrian.yml

更多参照：
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/mot/pedestrian
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/mot/vehicle
