### ISSUE TITLE
关于voc数据评估

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleDetection#7228]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问有没有评估voc的方法呢？我把我的标签文件都弄成了voc格式的，谢谢
![image](https://user-images.githubusercontent.com/43515926/198986588-8263e826-c2b0-46df-bff5-f6f229c0a4d3.png)

**Comment by XYZ-916** [comment]
参考这个配置文件：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/datasets/voc.yml
