### ISSUE TITLE
mot数据集 det.txt如何生成

### ISSUE THREAD

**Issue by BainOuO** [PaddlePaddle/PaddleDetection#7232]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

现已生成MOT相关的标注文件。不过我这里有一个新的问题：我使用darklabel工具标记自己的数据集，可以生成gt.txt文件，没有det.txt文件，导致无法生成相应的标注文件，det文件是如何制作的呢，期待您的回答！

**Comment by nemonameless** [comment]
建议再仔细阅读下文档。
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/data/PrepareMOTDataSet.md#jde%E6%95%B0%E6%8D%AE%E9%9B%86-1
gt.txt和det.txt选一个去制作标注文件都可以，你用gt.txt就可以。

**Comment by BainOuO** [comment]
> 建议再仔细阅读下文档。 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/data/PrepareMOTDataSet.md#jde%E6%95%B0%E6%8D%AE%E9%9B%86-1 gt.txt和det.txt选一个去制作标注文件都可以，你用gt.txt就可以。

但是我使用mot17.yml时需要annotations/train_half.json等json文件，使用您昨天推荐的convert_mot17_to_coco.py需要数据集有det.txt不然会报错
您的意思是 所有模型的数据集配置文件都可以用mot.yml吗，那自定义数据集的image_lists怎么写呢，期待您的回答！谢谢！！

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/7225
已经推荐给你下载了，下载完解压就能用。https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/mot/DataDownload.md
建议把文档仔细读一遍再去使用。然后按照给的默认配置去跑一遍模型的训练测试，有助于你了解数据集。
转数据集格式是基本功，给你推荐的转换代码是供你参考，自己要学会改写下。

**Comment by BainOuO** [comment]
> #7225 已经推荐给你下载了，下载完解压就能用。https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/mot/DataDownload.md 建议把文档仔细读一遍再去使用。然后按照给的默认配置去跑一遍模型的训练测试，有助于你了解数据集。 转数据集格式是基本功，给你推荐的转换代码是供你参考，自己要学会改写下。

我已经下载mot16 mot17 mix跑过了，都可以正常运行。但是使用我自己用darklabel标注的数据集就出现了问题，原代码mot.yml中的image_lists: ['mot17.train', 'caltech.all', 'cuhksysu.train', 'prw.train', 'citypersons.train', 'eth.train']，mot.train等是已经处理好的格式，我自己标注的数据集只有gt.txt，我该如何改写image_lists呢
谢谢您的回答！感恩！

**Comment by nemonameless** [comment]
建议再仔细读一遍文档。
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/data/PrepareMOTDataSet.md#jde%E6%95%B0%E6%8D%AE%E9%9B%86-1

gt.txt 是制作 labels_with_ids/ 用的，PaddleDetection/dataset/mot/gen_labels_MOT.py 已经有转换代码，和 image_lists 没有关系。没有det.txt也不影响。

image_lists 先看是什么再想怎么制作，像 mot17.train 就是每行记录图片路径，很基本的python代码操作。

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/mot/pedestrian
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/mot/vehicle
这些都是JDE格式自定义数据集的例子，建议看下学习下写法

**Comment by BainOuO** [comment]
> 建议再仔细读一遍文档。 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/data/PrepareMOTDataSet.md#jde%E6%95%B0%E6%8D%AE%E9%9B%86-1
> 
> gt.txt 是制作 labels_with_ids/ 用的，PaddleDetection/dataset/mot/gen_labels_MOT.py 已经有转换代码，和 image_lists 没有关系。没有det.txt也不影响。
> 
> image_lists 先看是什么再想怎么制作，像 mot17.train 就是每行记录图片路径，很基本的python代码操作。

您好！非常感谢您耐心的回复，对我有很大的帮助！
但是我现在还是存在一些问题：
根据您的提示，已通过gt.txt生成labels_with_ids，现在我的数据集格式已经和https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/data/PrepareMOTDataSet.md#jde%E6%95%B0%E6%8D%AE%E9%9B%86-1 一致，即：
custom_data
   |——————images
   |        └——————test
   |        └——————train
   |                └——————seq1
   |                |        └——————gt
   |                |        |       └——————gt.txt
   |                |        └——————img1
   |                |        |       └——————000001.jpg
   |                |        |       |——————000002.jpg
   |                |        |       └—————— ...
   |                |        └——————seqinfo.ini
   |                └——————seq2
   |                └——————...
   └——————labels_with_ids
            └——————train
                    └——————seq1
                    |        └——————000001.txt
                    |        |——————000002.txt
                    |        └—————— ...
                    └——————seq2
                    └—————— ...
无test集
此结构使用convert_mot17_to_coco.py生成的json文件是空的
loaded train_half for 0 images and 0 samples
loaded val_half for 0 images and 0 samples
loaded train for 0 images and 0 samples
该怎样正确的使用呢？

**Comment by BainOuO** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/data/PrepareMOTDataSet.md#jde%E6%95%B0%E6%8D%AE%E9%9B%86-1 
这样结构的数据集可以直接用于训练吗？image_list: [MOT16.train]

**Comment by jack00000** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/data/PrepareMOTDataSet.md#jde%E6%95%B0%E6%8D%AE%E9%9B%86-1 这样结构的数据集可以直接用于训练吗？image_list: [MOT16.train]

**Comment by congyao123456** [comment]
> ### 问题确认
> * [x] 我已经搜索过问题，但是没有找到解答。我已经搜索了这个问题，没有找到相关的答案。
> 
> ### 请提出你的问题
> 现已生成MOT相关的标注文件。不过我这里有一个新的问题：我使用darklabel工具标记自己的数据集，可以生成gt.txt文件，没有det.txt文件，导致无法生成相应的标注文件，det文件是如何制作的呢，期待您的回答！

您好，我和你有相同的问题，使用darklabel生成了gt.txt，请问如何生成det.txt的问题解决了吗，期待您的回复，不胜感激
