### ISSUE TITLE
ppyoloe多类检测如何计算每一类的map，召回率

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleDetection#7233]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

eval.py只能计算平均map，召回率

**Comment by nemonameless** [comment]
eval命令最后加上 `--classwise`
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/tools/eval.py#L70

**Comment by LJY6356** [comment]
你好，classwise这只是AP不能求召回率吗



------------------ 原始邮件 ------------------
发件人: Feng Ni ***@***.***&gt;
发送时间: 2022年11月1日 12:21
收件人: PaddlePaddle/PaddleDetection ***@***.***&gt;
抄送: LJY6356 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleDetection] ppyoloe多类检测如何计算每一类的map，召回率 (Issue #7233)





 
eval命令最后加上 --classwise
 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/tools/eval.py#L70
