### ISSUE TITLE
部署模型检测不到目标

### ISSUE THREAD

**Issue by gitmhg** [PaddlePaddle/PaddleDetection#7240]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我正在部署pphuman下的[ppyoloe_crn_s_36e_pphuman.yml](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/pphuman/ppyoloe_crn_s_36e_pphuman.yml)模型，但是检测不到结果。
![image](https://user-images.githubusercontent.com/51695758/199204794-d8ce8704-3236-4eae-ad90-2dd04f22720b.png)

**Comment by nemonameless** [comment]
为方便排查请按模板提问谢谢
https://github.com/PaddlePaddle/PaddleDetection/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml
