### ISSUE TITLE
多类检测召回率如何打印，如何打印指定IOU的AP

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleDetection#7241]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/67177370/199205347-9b59ede0-4635-47a5-aee7-36173986d021.png)
AP是IoU=0.50:0.95，如何打印IoU=0.50

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/5899
这个是由安装的cocoapi评估代码决定的，需要自行修改这个文件：
https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py 
自己打印下你的安装路径，找到这个文件去修改。
```
import pycocotools
pycocotools.__path__
```

**Comment by LJY6356** [comment]
修改位置可以给一下吗





------------------ 原始邮件 ------------------
发件人: Feng Ni ***@***.***&gt;
发送时间: 2022年11月1日 18:11
收件人: PaddlePaddle/PaddleDetection ***@***.***&gt;
抄送: LJY6356 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleDetection] 多类检测召回率如何打印，如何打印指定IOU的AP (Issue #7241)

**Comment by Dekadenc** [comment]
> ### 问题确认 Search before asking
> * [x]  我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> 
> ### 请提出你的问题 Please ask your question
> ![image](https://user-images.githubusercontent.com/67177370/199205347-9b59ede0-4635-47a5-aee7-36173986d021.png) AP是IoU=0.50:0.95，如何打印IoU=0.50
请问一下您这个是怎么打印出来的，修改的哪里呀
![image](https://user-images.githubusercontent.com/102035987/199260381-7c44bca4-b4d7-4993-b52c-07759303ee65.png)
