### ISSUE TITLE
Using a pre-trained picodet with different number of classes

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleDetection#7242]
Hi Everyone,
I'm using PicoDet for the layout analysis task
There's a pre-trained model already trained in English for 5 classes

I want to fine-tune this model using my dataset which contains only 2 classes

How can I do that using the configuration file for PicoDet?

Would only changing `num_classes: 2` work and adding the pre-trained model?

**Comment by jerrywgz** [comment]
Sure the only config you need to change is num_class and loading pre-trained model of your 5-class model
