### ISSUE TITLE
paddledetection，eval评估

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleDetection#7244]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

eval.py评估多类，如何打印每一类的Precision Recall  mAP.

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/GETTING_STARTED_cn.md#7-%E8%AE%AD%E7%BB%83%E5%8F%AF%E8%A7%86%E5%8C%96 可以参考这下面的参数文档，使用--classwise

**Comment by zcswdt** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/GETTING_STARTED_cn.md#7-%E8%AE%AD%E7%BB%83%E5%8F%AF%E8%A7%86%E5%8C%96 可以参考这下面的参数文档，使用--classwise

您好，这里只有绘制出来P-R曲线，没有打印出来0.5时候的P,R值？请问如何打印呢？
