### ISSUE TITLE
多摄像头跟踪方案是否支持在线跟踪？

### ISSUE THREAD

**Issue by Hyperjunct** [PaddlePaddle/PaddleDetection#7245]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问现有的多摄像头跟踪方案是否支持多个视频的在线跟踪？

**Comment by jerrywgz** [comment]
目前支持的方案还只支持离线对两个输入视频跟踪之后，再对跟踪结果进行匹配

**Comment by Hyperjunct** [comment]
> 目前支持的方案还只支持离线对两个输入视频跟踪之后，再对跟踪结果进行匹配

感谢您的答复，我还想请教一下，目前可以实现在线运行的mtmct算法有哪些？
