### ISSUE TITLE
PaddlePaddle配不上cuda环境

### ISSUE THREAD

**Issue by Hyperjunct** [PaddlePaddle/PaddleDetection#7246]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

PaddlePaddle配不上cuda环境，调用不了GPU
CUDA11.2 & 11.6版本皆安装失败
<img width="1235" alt="2c8abd7d6563490d1ec903ad3102026" src="https://user-images.githubusercontent.com/98454125/199237193-d24e1ab5-67b0-436f-8d9b-505b1bfd74aa.png">

### 复现环境 Environment

- OS: Linux
- PaddlePaddle : 2.3.2
- PaddleYOLO : release/2.5
- Python : 3.9.13
- CUDA : 11.4
- cuDNN Version : 8.4
- GUP : V100  

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Hyperjunct** [comment]
cuda11.4机器环境配不上paddlegpu112和116两个版本

**Comment by nemonameless** [comment]
paddle安装问题建议在 https://github.com/PaddlePaddle/Paddle/issues 提问。建议环境版本不用选太高。
