### ISSUE TITLE
人体骨骼点行为识别的二次开发

### ISSUE THREAD

**Issue by zhuoxun-xun** [PaddlePaddle/PaddleDetection#7251]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我想二次开发PP-Human下的基于骨骼点的摔倒识别。请问如果我想在摔倒识别上新增新的行为，那在准备新的数据集时，需要把摔跤的数据也添加进新的数据集一起训练吗？

**Comment by wangxinxin08** [comment]
如果你还想检测摔倒识别的话，是需要加进去一起训练的

**Comment by zhuoxun-xun** [comment]
请问我应该跑什么命令才能将数据的class_id保存为PaddleVideo可用的文件格式? 比如现在我的数据有3个类别摔倒，喝水，座下。

**Comment by zhiboniu** [comment]
可以参考摔倒的二次开发文档和paddlevideo相关文档：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/advanced_tutorials/customization/action_recognotion/skeletonbased_rec.md
https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/model_zoo/recognition/stgcn.md

**Comment by zhuoxun-xun** [comment]
我参考了https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/advanced_tutorials/customization/action_recognotion/skeletonbased_rec.md
但我要保存为PaddleVideo可用的文件格式是跑了提供的脚本报错。
跑的脚本是：PaddleVideo/applications/PPHuman/datasets下的prepare_dataset.py

**Comment by HNU-DC** [comment]
> ### 问题确认 Search before asking
> * [x]  我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> 
> ### 请提出你的问题 Please ask your question
> 你好，我想二次开发PP-Human下的基于骨骼点的摔倒识别。请问如果我想在摔倒识别上新增新的行为，那在准备新的数据集时，需要把摔跤的数据也添加进新的数据集一起训练吗？

您好请问这个问题您解决了吗，我也是在扩增行为识别种类出现问题，不知道应该如何修改那个代码才会生成包含多种类别的npy与kpl
