### ISSUE TITLE
openvino使用gpu加载模型报RuntimeError: Operation: multiclass_nms3_0.tmp_1 of type MulticlassNms(op::v0) is not supported

### ISSUE THREAD

**Issue by studywgf** [PaddlePaddle/PaddleDetection#7256]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

openvino使用gpu加载模型报RuntimeError: Operation: multiclass_nms3_0.tmp_1 of type MulticlassNms(op::v0) is not supported，如何解决？

**Comment by lyuwenyu** [comment]
这个是openvino后处理不支持这个nms类型吧     可以导出时候把后处理去掉 单独写个后处理吧

**Comment by studywgf** [comment]
> 这个是openvino后处理不支持这个nms类型吧 可以导出时候把后处理去掉 单独写个后处理吧

请问有相关操作链接提供一下吗？

**Comment by lgy2830** [comment]
在导出paddle模型时，设置一下参数，exclude_nms=True，就可以把nms部分给去掉，我给去掉了，但是要自己再写代码去实现去掉的哪一部分的代码，也就是后处理的代码，后处理就是实现nms的代码。

**Comment by lgy2830** [comment]
> > 这个是openvino后处理不支持这个nms类型吧 可以导出时候把后处理去掉 单独写个后处理吧
> 
> 请问有相关操作链接提供一下吗？

你好，你有实现后处理的代码吗？
