### ISSUE TITLE
picodet 评估报错

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/PaddleDetection#7257]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddleDet: release/2.4
paddle version: 2.2.2
Picodet eval时报错，报错信息如下：
![image](https://user-images.githubusercontent.com/37332773/199657883-df87c078-d07d-4255-9947-0af1a5ed26b2.png)

**Comment by lyuwenyu** [comment]
自己的数据集嘛？ 用2.5单独推理试一下 还会不会报错

**Comment by peiwenYe** [comment]
> 自己的数据集嘛？ 用2.5单独推理试一下 还会不会报错

感谢回答～
使用的是coco，从coco val2017中随机选了一部分数据进行评估。

**Comment by peiwenYe** [comment]
> 自己的数据集嘛？ 用2.5单独推理试一下 还会不会报错

同样的数据推理不报错

**Comment by lyuwenyu** [comment]
那2.4可能有点问题.. 要不先优先用2.5吧  2.4不维护了
