### ISSUE TITLE
使用：python tools/anchor_cluster.py 报AttributeError: 'SchemaDict' object has no attribute 'parse_dataset'

### ISSUE THREAD

**Issue by aiyodiulehuner** [PaddlePaddle/PaddleDetection#7262]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用：python tools/anchor_cluster.py 报AttributeError: 'SchemaDict' object has no attribute 'parse_dataset'

**Comment by lyuwenyu** [comment]
能再详细嘛 ，是不是命令使用错了;

**Comment by aiyodiulehuner** [comment]
![图片](https://user-images.githubusercontent.com/28584849/199717031-5014d937-6dfd-49c5-a594-49c5410904df.png)
就复制的这行

**Comment by aiyodiulehuner** [comment]
![图片](https://user-images.githubusercontent.com/28584849/199717174-8729227b-7c00-4916-9ea7-0de0d21eedf0.png)
这行报错

**Comment by aiyodiulehuner** [comment]
> 能再详细嘛 ，是不是命令使用错了;
![图片](https://user-images.githubusercontent.com/28584849/199717327-aeb046c6-48ae-4a65-935e-5445887f20c6.png)

**Comment by xmxxiong** [comment]
我也遇到了相同的问题

**Comment by hosea7456** [comment]
我也是同样的问题

**Comment by RnalU** [comment]
我也是同样的报错

**Comment by hahashayebuhui** [comment]
你好，请问你解决了吗，我也是报这个错

**Comment by draymski** [comment]
我也遇到了相同的问题。gpt觉得我是“在配置文件中使用了不正确的数据集配置”，但我是完全跟着教程（roadsign)配置的呀。会不会是源码本身就有问题。

**Comment by draymski** [comment]
破案了。把相关的yml配置文件中的形如`name: COCODataSet`，改为`!COCODataSet`即可。如图：
![1703789544616](https://github.com/PaddlePaddle/PaddleDetection/assets/75298565/075c3108-09a0-4dc3-80a8-2ed294fbb641)
- 错误直接原因：我们的dateset变量本来是一个[COCODataSet类](https://github.com/PaddlePaddle/PaddleYOLO/blob/release%2F2.6/ppdet/data/source/coco.py)/[VOC类](https://github.com/PaddlePaddle/PaddleYOLO/blob/release%2F2.6/ppdet/data/source/voc.py)的实例，这样才能有报错内容所提及的'parse_dataset'方法。但实际上，我们却得到的是一个‘SchemaDict'。
- 错误根本原因：paddle的教程是对的，但仓库源码中的配置文件错了（未更新导致）。教程里说”在PaddleDetection的yml配置文件中，使用!直接序列化模块实例"，例如[roadsign的配置](https://github.com/PaddlePaddle/PaddleYOLO/blob/develop/docs/tutorials/data/PrepareDetDataSet.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E8%AE%AD%E7%BB%83)；但仓库里相应的yml文件里用的却是`name: VOCDataSet`，例如[roadsign的配置](https://github.com/PaddlePaddle/PaddleYOLO/blob/release%2F2.6/configs/datasets/roadsign_voc.yml)。
