### ISSUE TITLE
如何修改多目标跟踪算法的输出文本？

### ISSUE THREAD

**Issue by Hyperjunct** [PaddlePaddle/PaddleDetection#7264]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问该在何处修改输出本文信息的顺序？

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/pptracking/python/mot/mtmct/postprocess.py#L185
根据打印的信息全局搜索代码就能找到。

**Comment by Hyperjunct** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/pptracking/python/mot/mtmct/postprocess.py#L185 根据打印的信息全局搜索代码就能找到。

感谢您的回复！
