### ISSUE TITLE
8显卡安装报错

### ISSUE THREAD

**Issue by ionescofung** [PaddlePaddle/PaddleDetection#7267]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

报错什么原因？
Error: Your machine doesn't support AVX, but the installed PaddlePaddle is avx core, you should reinstall paddlepaddle with no-avx core.
Traceback (most recent call last):
  File "/root/pyenv/paddel_env/test.py", line 1, in <module>
    import paddle
  File "/root/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
linux系统
8张p106显卡

还有
你们的回答问题太敷衍了！ 之前的问题你们问了一下就没有再跟进了！

**Comment by ionescofung** [comment]
多gpu训练报错 #7175

**Comment by nemonameless** [comment]
报bug请按模板提问谢谢，提前说明环境和版本信息等。
paddle安装相似问题搜索 或 提问也可以在 https://github.com/PaddlePaddle/Paddle/issues
已有提示
```
Error: Your machine doesn't support AVX, but the installed PaddlePaddle is avx core, you should reinstall paddlepaddle with no-avx core.
```
你的机器不支持avx，需要安装noavx的版本https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html
