### ISSUE TITLE
Salient Object Detection

### ISSUE THREAD

**Issue by bittergourd1224** [PaddlePaddle/PaddleDetection#7271]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）
进行画幅中心显著性目标的检测/分割

2. 需求场景（请描述你的项目中为什么需要用此功能）
显著性目标检测的好处是，无论目标具体是什么类别，都可以将最主要的那个提取出来。这样就可以一个模型适用多个场景，而不用针对每个场景单独训练这个场景的数据。
具体来说，一个好的显著性目标检测模型，既可以适用于仪表盘识别中提取仪表盘，又适用于人像拍照时提取被摄人物，而不需要收集数据以及重新训练。
SOD也一直是视觉领域的重要课题，包括ECCV等顶会也有专门的SOD赛道。

3. 功能描述（请简单描述或设计这个功能）
在PaddleDetection中加入一个Salient Object Detection的分支，复现以及提供一些SOTA模型可供大家试用

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by thinkthinking** [comment]
> ### 问题确认 Search before asking
> * [x]  我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.
> 
> ### 需求描述 Feature Description
> 1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）
>    进行画幅中心显著性目标的检测/分割
> 2. 需求场景（请描述你的项目中为什么需要用此功能）
>    显著性目标检测的好处是，无论目标具体是什么类别，都可以将最主要的那个提取出来。这样就可以一个模型适用多个场景，而不用针对每个场景单独训练这个场景的数据。
>    具体来说，一个好的显著性目标检测模型，既可以适用于仪表盘识别中提取仪表盘，又适用于人像拍照时提取被摄人物，而不需要收集数据以及重新训练。
>    SOD也一直是视觉领域的重要课题，包括ECCV等顶会也有专门的SOD赛道。
> 3. 功能描述（请简单描述或设计这个功能）
>    在PaddleDetection中加入一个Salient Object Detection的分支，复现以及提供一些SOTA模型可供大家试用
> 
> ### 是否愿意提交PR Are you willing to submit a PR?
> * [ ]  Yes I'd like to help by submitting a PR!

将该需求整理到Roadmap of PaddleDetection中 #7892
