### ISSUE TITLE
paddle trt下载链接BUG：跳转bug

### ISSUE THREAD

**Issue by exceedTu** [PaddlePaddle/PaddleDetection#7273]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

bug地址：
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python
bug描述：
![image](https://user-images.githubusercontent.com/110536580/200099704-51c6615b-9bd1-491f-8b65-e6274fd5eaab.png)

bug现象：
![image](https://user-images.githubusercontent.com/110536580/200099713-13e2509c-5be8-4694-882a-26a7775b1459.png)

### 复现环境 Environment

普通网页bug

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by exceedTu** [comment]
**
![image](https://user-images.githubusercontent.com/110536580/200099745-d28d28ab-8062-4f36-b9b4-e0736c5950dd.png)
**

**Comment by nemonameless** [comment]
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#python 旧网址失效了

新网址为：
https://paddleinference.paddlepaddle.org.cn/v2.2/user_guides/download_lib.html#python
