### ISSUE TITLE
请问在MOT中有没有评价HOTA这一个指标的方法？我看到只有关于MOTA、IDF1等指标

### ISSUE THREAD

**Issue by Jiahuan-Long** [PaddlePaddle/PaddleDetection#7275]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问在MOT中有没有评价HOTA这一个指标的方法？我看到只有关于MOTA、IDF1等指标

**Comment by nemonameless** [comment]
暂时没有，后面会计划加上。HOTA都是调用这个库计算的 https://github.com/JonathonLuiten/TrackEval
