### ISSUE TITLE
目标检测中的fps

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleDetection#7276]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我在使用voc数据集训练，请问怎么打印出来fps呢？

**Comment by nemonameless** [comment]
eval过程出mAP后都会打印fps，和数据集格式没关系。
