### ISSUE TITLE
多相机跟踪方案配置文件中的参数使用问题

### ISSUE THREAD

**Issue by Hyperjunct** [PaddlePaddle/PaddleDetection#7278]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

多相机跟踪方案的配置文件中有四类参数，想请教一下这些参数的具体含义和使用方法，谢谢！

**Comment by nemonameless** [comment]
这些是针对AIC的MTMCT数据集的，包括区域图限制用于过滤、相机补偿等，因数据集和拍摄相机而异，无法通用的。
最直接的方法是专门针对你的数据集重训检测和ReID。
AIC的MTMCT赛道一些比赛方案你也可以自行参考下：
比赛方案汇总：https://github.com/NVIDIAAICITYCHALLENGE   
比赛最新的官网：https://www.aicitychallenge.org/2022-challenge-tracks/
