### ISSUE TITLE
自动增强的旋转似乎有问题

### ISSUE THREAD

**Issue by greathope** [PaddlePaddle/PaddleDetection#728]
使用自动增强，非旋转的增强是正常的
![image](https://user-images.githubusercontent.com/30383377/82198028-4d246e80-992e-11ea-9d09-64fc16365240.png)
但旋转的就有问题
![image](https://user-images.githubusercontent.com/30383377/82198109-6c230080-992e-11ea-859a-a3b888040459.png)

官方能check下吗

**Comment by qingqing01** [comment]
@greathope 感谢反馈，我们check下。

**Comment by littletomatodonkey** [comment]
想问下方便提供下问题复现的图片和代码吗？ @greathope

**Comment by greathope** [comment]
@littletomatodonkey 可以的，链接如下 https://pan.zju.edu.cn/share/f9399ac3913e1ab2dab577e1b3 ，将ppdet/data/transform/autoaugment_utils.py 放到统一目录夹下就好了，重复多次增强出现旋转增强就能看到这个问题了～

**Comment by littletomatodonkey** [comment]
您好，这里的旋转应该是没有问题的，旋转之后，会把旋转后的bbox的外接矩形作为新的bbox，您可以把两个框画在同一幅图里看下（或者将旋转之前的框直接放在原图里，然后将其旋转并画上旋转后的框），更加具体的解释您也可以参考这里：https://blog.paperspace.com/data-augmentation-for-object-detection-rotation-and-shearing/
![image](https://user-images.githubusercontent.com/14270174/82214282-283cf500-9948-11ea-8ece-762328b09982.png)

**Comment by greathope** [comment]
@littletomatodonkey 原来如此，感谢了
