### ISSUE TITLE
JDE多目标跟踪

### ISSUE THREAD

**Issue by chengzhixing0202** [PaddlePaddle/PaddleDetection#7280]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

想问一下咋们JDE那里相较于原论文进行了哪些优化？

**Comment by nemonameless** [comment]
根据JDE原repo复现的，https://github.com/Zhongdao/Towards-Realtime-MOT ，没有优化。

**Comment by chengzhixing0202** [comment]
> 根据JDE原repo复现的，https://github.com/Zhongdao/Towards-Realtime-MOT ，没有优化。
谢谢聂风老师回复，MOTA直接从64涨到了72，为什么会涨这么多呢？

**Comment by nemonameless** [comment]
JDE-1088x608 在MOT16-Train数据集上的MOTA是72，JDE原作者代码库给的还是73.1，但这个其实没有多少意义，是因为MOT16没有验证集，Test集需要交官网 https://motchallenge.net 才能测出来真正的MOTA每月仅4次机会，所以用MOT16-Train集作为验证集只是有个大概的精度估计说明训的好，也是为了方便提测和给用户验证模型。
Test集上的结果，ppdet复现的交到官方Test是64.6，已写在readme中，JDE原作者的73.1的模型交到Test是64.4，论文里也是64.4。
