### ISSUE TITLE
cascase_rcnn模型导出部署后召回变差好多

### ISSUE THREAD

**Issue by DevilMay-Cry** [PaddlePaddle/PaddleDetection#7286]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我是使用cascade_rcnn_r50_vd_fpn_ssld_2x_coco.yml训练模型后用
python tools/export_model.py -c configs/cascade_rcnn/cascade_rcnn_r50_vd_fpn_ssld_2x_coco.yml --output_dir=./inference_model \
 -o weights=./output/cascade_rcnn_r50_vd_fpn_ssld_2x_coco//best_model.pdparams 
导出模型后部署效果和直接用
python3 tools/infer.py -c configs/cascade_rcnn/cascade_rcnn_r50_vd_fpn_ssld_2x_coco.yml  -o use_gpu=true weights=./output/cascade_rcnn_r50_vd_fpn_ssld_2x_coco/best_model.pdparams 
效果差了好多。
请问下可能是那个地方处理的有问题

**Comment by wangxinxin08** [comment]
infer.py默认使用0.5的阈值显示检测框，一般评估是的score_threshold远小于0.5

**Comment by DevilMay-Cry** [comment]
已解决
