### ISSUE TITLE
旋转目标检测训练出错

### ISSUE THREAD

**Issue by Jackson-en** [PaddlePaddle/PaddleDetection#7291]
### 问题描述 Please describe your issue

使用develop分支进行旋转目标得训练，转换的数据格式为json文件(COCO格式，带有角度)，使用configs/rotate/ppyoloe_r/ppyoloe_r_crn_s_3x_dota_ms.yml  配置文件，只修改了configs/datasets/dota_ms.yml 中num_classes，还有自己的json，image路径 ，运行tools\train.py  报错 coco.py 中
Traceback (most recent call last):
  File "D:/workbaseMos/PaddleDetection/tools/train.py", line 183, in <module>
    main()
  File "D:/workbaseMos/PaddleDetection/tools/train.py", line 179, in main
    run(FLAGS, cfg)
  File "D:/workbaseMos/PaddleDetection/tools/train.py", line 123, in run
    trainer = Trainer(cfg, mode='train')
  File "D:\workbaseMos\PaddleDetection\ppdet\engine\trainer.py", line 95, in __init__
    self.dataset, cfg.worker_num)
  File "D:\workbaseMos\PaddleDetection\ppdet\data\reader.py", line 163, in __call__
    self.dataset.parse_dataset()
  File "D:\workbaseMos\PaddleDetection\ppdet\data\source\coco.py", line 148, in parse_dataset
    x1, y1, box_w, box_h = inst['bbox']
ValueError: too many values to unpack (expected 4)

**Comment by wangxinxin08** [comment]
旋转框的数据集采用的是COCO格式，COCO格式中bbox只有四个值，这里表示的是正框的标注，不要添加角度信息。旋转框的预处理会从segmentation字段中读取poly信息(四边形的四个顶点)，bbox不会被使用。

**Comment by Jackson-en** [comment]
> 旋转框的数据集采用的是COCO格式，COCO格式中bbox只有四个值，这里表示的是正框的标注，不要添加角度信息。旋转框的预处理会从segmentation字段中读取poly信息(四边形的四个顶点)，bbox不会被使用。

意思是voc转coco的时候bbox里面只放[cx,cy,w,h], segmentation是8个值(4个点的坐标)， segmentation是自己生成的嘛还是

**Comment by wangxinxin08** [comment]
> > 旋转框的数据集采用的是COCO格式，COCO格式中bbox只有四个值，这里表示的是正框的标注，不要添加角度信息。旋转框的预处理会从segmentation字段中读取poly信息(四边形的四个顶点)，bbox不会被使用。
> 
> 意思是voc转coco的时候bbox里面只放[cx,cy,w,h], segmentation是8个值(4个点的坐标)， segmentation是自己生成的嘛还是

segmentation一般是从标注来的，一般旋转框的标注是[x1, y1, x2, y2, x3, y3, x4, y4]，如果你只有x, y, w, h, angle，你可能需要转换成4个点的坐标

**Comment by Jackson-en** [comment]
> > > 旋转框的数据集采用的是COCO格式，COCO格式中bbox只有四个值，这里表示的是正框的标注，不要添加角度信息。旋转框的预处理会从segmentation字段中读取poly信息(四边形的四个顶点)，bbox不会被使用。
> > 
> > 
> > 意思是voc转coco的时候bbox里面只放[cx,cy,w,h], segmentation是8个值(4个点的坐标)， segmentation是自己生成的嘛还是
> 
> segmentation一般是从标注来的，一般旋转框的标注是[x1, y1, x2, y2, x3, y3, x4, y4]，如果你只有x, y, w, h, angle，你可能需要转换成4个点的坐标

我这边是用rolabelimg标注的的旋转框，现在意思是我转换成segmentation=[x1, y1, x2, y2, x3, y3, x4, y4]，bbox直接为空不用管了对吗

**Comment by wangxinxin08** [comment]
> > > > 旋转框的数据集采用的是COCO格式，COCO格式中bbox只有四个值，这里表示的是正框的标注，不要添加角度信息。旋转框的预处理会从segmentation字段中读取poly信息(四边形的四个顶点)，bbox不会被使用。
> > > 
> > > 
> > > 意思是voc转coco的时候bbox里面只放[cx,cy,w,h], segmentation是8个值(4个点的坐标)， segmentation是自己生成的嘛还是
> > 
> > 
> > segmentation一般是从标注来的，一般旋转框的标注是[x1, y1, x2, y2, x3, y3, x4, y4]，如果你只有x, y, w, h, angle，你可能需要转换成4个点的坐标
> 
> 我这边是用rolabelimg标注的的旋转框，现在意思是我转换成segmentation=[x1, y1, x2, y2, x3, y3, x4, y4]，bbox直接为空不用管了对吗

COCO中bbox是不会空着的，可以直接从[x1, y1, x2, y2, x3, y3, x4, y4]中生成，在ppdet的x2coco.py中将labelme转成coco是已经包含了这一步骤的，https://github.com/PaddlePaddle/PaddleDetection/blob/develop/tools/x2coco.py#L158 也就是说不用你自己去处理的

**Comment by Jackson-en** [comment]
> > > > > 旋转框的数据集采用的是COCO格式，COCO格式中bbox只有四个值，这里表示的是正框的标注，不要添加角度信息。旋转框的预处理会从segmentation字段中读取poly信息(四边形的四个顶点)，bbox不会被使用。
> > > > 
> > > > 
> > > > 意思是voc转coco的时候bbox里面只放[cx,cy,w,h], segmentation是8个值(4个点的坐标)， segmentation是自己生成的嘛还是
> > > 
> > > 
> > > segmentation一般是从标注来的，一般旋转框的标注是[x1, y1, x2, y2, x3, y3, x4, y4]，如果你只有x, y, w, h, angle，你可能需要转换成4个点的坐标
> > 
> > 
> > 我这边是用rolabelimg标注的的旋转框，现在意思是我转换成segmentation=[x1, y1, x2, y2, x3, y3, x4, y4]，bbox直接为空不用管了对吗
> 
> COCO中bbox是不会空着的，可以直接从[x1, y1, x2, y2, x3, y3, x4, y4]中生成，在ppdet的x2coco.py中将labelme转成coco是已经包含了这一步骤的，https://github.com/PaddlePaddle/PaddleDetection/blob/develop/tools/x2coco.py#L158 也就是说不用你自己去处理的

嗯呢，那我现在是从voc转换成了dota，在从dota转换成coco这样是不是就符合训练的要求了

**Comment by xmzhuxm** [comment]
> 旋转框的数据集采用的是COCO格式，COCO格式中bbox只有四个值，这里表示的是正框的标注，不要添加角度信息。旋转框的预处理会从segmentation字段中读取poly信息(四边形的四个顶点)，bbox不会被使用。

ppyoloe_r 现在支持C++部署吗？

**Comment by wangxinxin08** [comment]
ppyoloe_r支持C++部署

**Comment by malege** [comment]
> ppyoloe_r支持C++部署


(base) PS E:\Python_Workspace\PaddleDetection-develop\deploy\cpp\Release> .\main.exe --model_dir=model --image_file=2022-10-24_11_00_41_825.bmp
total images = 1, batch_size = 1, total steps = 1
2022-10-24_11_00_41_825.bmp The number of detected box: 0
Visualized output saved as output\2022-10-24_11_00_41_825.bmp
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1123 09:47:38.477779  9436 main.cc:76] ----------------------- Config info -----------------------
I1123 09:47:38.477779  9436 main.cc:77] runtime_device: CPU
I1123 09:47:38.477779  9436 main.cc:78] ir_optim: True
I1123 09:47:38.478221  9436 main.cc:80] enable_memory_optim: True
I1123 09:47:38.478304  9436 main.cc:90] enable_tensorrt: False
I1123 09:47:38.478304  9436 main.cc:92] precision: fp32
I1123 09:47:38.478349  9436 main.cc:95] enable_mkldnn: False
I1123 09:47:38.478349  9436 main.cc:96] cpu_math_library_num_threads: 1
I1123 09:47:38.478458  9436 main.cc:97] ----------------------- Data info -----------------------
I1123 09:47:38.478458  9436 main.cc:98] batch_size: 1
I1123 09:47:38.478458  9436 main.cc:99] input_shape: dynamic shape
I1123 09:47:38.478458  9436 main.cc:101] ----------------------- Model info -----------------------
I1123 09:47:38.478458  9436 main.cc:103] model_name: model
I1123 09:47:38.478458  9436 main.cc:105] ----------------------- Perf info ------------------------
I1123 09:47:38.478458  9436 main.cc:106] Total number of predicted data: 1 and total time spent(ms): 302
I1123 09:47:38.478458  9436 main.cc:109] preproce_time(ms): 16.8976, inference_time(ms): 286.379, postprocess_time(ms): 0.0109

可以编译成功，输出检测框数目为0，python推理正常输出
