### ISSUE TITLE
导出的目标检测器误检现象严重

### ISSUE THREAD

**Issue by Hyperjunct** [PaddlePaddle/PaddleDetection#7295]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

使用paddle提供的YOLO目标检测算法作为检测器，但是在最终得到的可视化结果中发现检测器的误检现象十分严重，将交通信号灯和标识牌也进行了检测，请问是什么原因导致了这种现象？

![微信图片编辑_20221109170918](https://user-images.githubusercontent.com/98454125/200815467-ff65bc13-01b3-4a11-89c1-34da40d50f40.jpg)

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

**Comment by nemonameless** [comment]
请按 release/2.5 下的文档去跑，也可以自己重训检测器。
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/pptracking/python#4-%E8%BD%A6%E8%BE%86%E8%B7%A8%E9%95%9C%E5%A4%B4%E8%B7%9F%E8%B8%AA%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E5%92%8C%E9%A2%84%E6%B5%8B

**Comment by Hyperjunct** [comment]
> 请按 release/2.5 下的文档去跑，也可以自己重训检测器。 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/pptracking/python#4-%E8%BD%A6%E8%BE%86%E8%B7%A8%E9%95%9C%E5%A4%B4%E8%B7%9F%E8%B8%AA%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E5%92%8C%E9%A2%84%E6%B5%8B

感谢您的答复，我更换检测器再运行一下
