### ISSUE TITLE
训练正常但是边训练边评估以及单独评估/测试出现错误

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#73]
错误信息如下：

> 2019-12-06 09:52:00,229-INFO: Load categories from /home/shuxsu/models-develop/PaddleCV/PaddleDetection/dataset/coco/annotations/instance_val.json
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2019-12-06 09:52:00,692-INFO: Infer iter 0
Traceback (most recent call last):
  File "infer.py", line 270, in <module>
    main()
  File "infer.py", line 194, in main
    bbox_results = bbox2out([res], clsid2catid, is_bbox_normalized)
  File "/home/shuxsu/models-develop/PaddleCV/PaddleDetection/ppdet/utils/coco_eval.py", line 217, in bbox2out
    catid = (clsid2catid[int(clsid)])
KeyError: 6

**Comment by shuxsu** [comment]
配置信息如下：
> architecture: MaskRCNN
train_feed: MaskRCNNTrainFeed
eval_feed: MaskRCNNEvalFeed
test_feed: MaskRCNNTestFeed
use_gpu: true
max_iters: 500
snapshot_iter: 50
log_smooth_window: 20
save_dir: output
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/mask_rcnn_r50_1x.tar
metric: COCO
weights: output/mask_rcnn_r50_1x/model_final/
num_classes: 7
finetune_exclude_pretrained_params: ['cls_score','bbox_pred','mask_fcn_logits']


MaskRCNN:
  backbone: ResNet
  rpn_head: RPNHead
  roi_extractor: RoIAlign
  bbox_assigner: BBoxAssigner
  bbox_head: BBoxHead
  mask_assigner: MaskAssigner
  mask_head: MaskHead

ResNet:
  norm_type: affine_channel
  norm_decay: 0.
  depth: 50
  feature_maps: 4
  freeze_at: 2

ResNetC5:
  depth: 50
  norm_type: affine_channel

RPNHead:
  anchor_generator:
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 6000
    post_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 1000
    post_nms_top_n: 1000

RoIAlign:
  resolution: 14
  spatial_scale: 0.0625
  sampling_ratio: 0

BBoxHead:
  head: ResNetC5
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    normalized: false
    score_threshold: 0.05

MaskHead:
  dilation: 1
  conv_dim: 256
  resolution: 14

BBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5

MaskAssigner:
  resolution: 14

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [20000, 40000]
    #values: [0.005 , 0.0025 , 0.00125]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

MaskRCNNTrainFeed:
  batch_size: 1
  dataset:
    dataset_dir: /home/shuxsu/models-develop/PaddleCV/PaddleDetection/dataset/coco
    annotation: /home/shuxsu/models-develop/PaddleCV/PaddleDetection/dataset/coco/annotations/instance_train.json
    image_dir: train
  num_workers: 10
  sample_transforms:
    - !DecodeImage
      to_rgb: true  # default: true
      with_mixup: false  # default: false
    - !ResizeImage
      interp: 1
      max_size: 1333
      target_size: 800
      use_cv2: true  # default: true
    - !RandomFlipImage
      is_mask_flip: true  # default: false
      # Whether bbox is normalized
      is_normalized: false  # default: false
      prob: 0.5  # default: 0.5
    - !Permute
      # The format of image, [H, W, C]/[C, H, W], true by default
      channel_first: true
      to_bgr: false  # default: true
      # List of batch transformations to use


MaskRCNNEvalFeed:
  batch_size: 1
  dataset:
    dataset_dir: /home/shuxsu/models-develop/PaddleCV/PaddleDetection/dataset/coco
    annotation: /home/shuxsu/models-develop/PaddleCV/PaddleDetection/dataset/coco/annotations/instance_val.json
    image_dir: val
#  sample_transforms:
#    - !ResizeImage
#      interp: 1
#      max_size: 1333
#      target_size: 800
#      use_cv2: true  # default: true

MaskRCNNTestFeed:
  batch_size: 1
  dataset:
    annotation: /home/shuxsu/models-develop/PaddleCV/PaddleDetection/dataset/coco/annotations/instance_val.json
#  image_shape: [3, 2048,1024]
#  sample_transforms:
#    - !DecodeImage
#      to_rgb: true  # default: true
#      with_mixup: false  # default: false
#    - !ResizeImage
#      interp: 1
#      max_size: 1333
#      target_size: 800
#      use_cv2: true  # default: true
#    - !Permute
#      # The format of image, [H, W, C]/[C, H, W], true by default
#      channel_first: true
#      to_bgr: false  # default: true
#      # List of batch transformations to use

**Comment by shuxsu** [comment]
配置信息如下：
`architecture: MaskRCNN
train_feed: MaskRCNNTrainFeed
eval_feed: MaskRCNNEvalFeed
test_feed: MaskRCNNTestFeed
use_gpu: true
max_iters: 500
snapshot_iter: 50
log_smooth_window: 20
save_dir: output
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/mask_rcnn_r50_1x.tar
metric: COCO
weights: output/mask_rcnn_r50_1x/model_final/
num_classes: 7
finetune_exclude_pretrained_params: ['cls_score','bbox_pred','mask_fcn_logits']


MaskRCNN:
  backbone: ResNet
  rpn_head: RPNHead
  roi_extractor: RoIAlign
  bbox_assigner: BBoxAssigner
  bbox_head: BBoxHead
  mask_assigner: MaskAssigner
  mask_head: MaskHead

ResNet:
  norm_type: affine_channel
  norm_decay: 0.
  depth: 50
  feature_maps: 4
  freeze_at: 2

ResNetC5:
  depth: 50
  norm_type: affine_channel

RPNHead:
  anchor_generator:
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 6000
    post_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 1000
    post_nms_top_n: 1000

RoIAlign:
  resolution: 14
  spatial_scale: 0.0625
  sampling_ratio: 0

BBoxHead:
  head: ResNetC5
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    normalized: false
    score_threshold: 0.05

MaskHead:
  dilation: 1
  conv_dim: 256
  resolution: 14

BBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5

MaskAssigner:
  resolution: 14

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [20000, 40000]
    #values: [0.005 , 0.0025 , 0.00125]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

MaskRCNNTrainFeed:
  batch_size: 1
  dataset:
    dataset_dir: /home/shuxsu/models-develop/PaddleCV/PaddleDetection/dataset/coco
    annotation: /home/shuxsu/models-develop/PaddleCV/PaddleDetection/dataset/coco/annotations/instance_train.json
    image_dir: train
  num_workers: 10
  sample_transforms:
    - !DecodeImage
      to_rgb: true  # default: true
      with_mixup: false  # default: false
    - !ResizeImage
      interp: 1
      max_size: 1333
      target_size: 800
      use_cv2: true  # default: true
    - !RandomFlipImage
      is_mask_flip: true  # default: false
      # Whether bbox is normalized
      is_normalized: false  # default: false
      prob: 0.5  # default: 0.5
    - !Permute
      # The format of image, [H, W, C]/[C, H, W], true by default
      channel_first: true
      to_bgr: false  # default: true
      # List of batch transformations to use


MaskRCNNEvalFeed:
  batch_size: 1
  dataset:
    dataset_dir: /home/shuxsu/models-develop/PaddleCV/PaddleDetection/dataset/coco
    annotation: /home/shuxsu/models-develop/PaddleCV/PaddleDetection/dataset/coco/annotations/instance_val.json
    image_dir: val
#  sample_transforms:
#    - !ResizeImage
#      interp: 1
#      max_size: 1333
#      target_size: 800
#      use_cv2: true  # default: true

MaskRCNNTestFeed:
  batch_size: 1
  dataset:
    annotation: /home/shuxsu/models-develop/PaddleCV/PaddleDetection/dataset/coco/annotations/instance_val.json
#  image_shape: [3, 2048,1024]
#  sample_transforms:
#    - !DecodeImage
#      to_rgb: true  # default: true
#      with_mixup: false  # default: false
#    - !ResizeImage
#      interp: 1
#      max_size: 1333
#      target_size: 800
#      use_cv2: true  # default: true
#    - !Permute
#      # The format of image, [H, W, C]/[C, H, W], true by default
#      channel_first: true
#      to_bgr: false  # default: true
#      # List of batch transformations to use
`

**Comment by shuxsu** [comment]
修改的个别配置信息如下：

> max_iters: 500
snapshot_iter: 50
log_smooth_window: 20
save_dir: output
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/mask_rcnn_r50_1x.tar
metric: COCO
weights: output/mask_rcnn_r50_1x/model_final/
num_classes: 7
finetune_exclude_pretrained_params: ['cls_score','bbox_pred','mask_fcn_logits']

> LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [20000, 40000]
    #values: [0.005 , 0.0025 , 0.00125]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

> MaskRCNNTrainFeed:
  batch_size: 1
  dataset:
    dataset_dir: /home/shuxsu/models-develop/PaddleCV/PaddleDetection/dataset/coco
    annotation: /home/shuxsu/models-develop/PaddleCV/PaddleDetection/dataset/coco/annotations/instance_train.json
    image_dir: train
  num_workers: 10
  sample_transforms:
    - !DecodeImage
      to_rgb: true  # default: true
      with_mixup: false  # default: false
    - !ResizeImage
      interp: 1
      max_size: 1333
      target_size: 800
      use_cv2: true  # default: true
    - !RandomFlipImage
      is_mask_flip: true  # default: false
      # Whether bbox is normalized
      is_normalized: false  # default: false
      prob: 0.5  # default: 0.5
    - !Permute
      # The format of image, [H, W, C]/[C, H, W], true by default
      channel_first: true
      to_bgr: false  # default: true
      # List of batch transformations to use

**Comment by heavengate** [comment]
看你配置文件里写明是有7类，结果索引index 6也就是最后一类错误，是否数据集里面只有6类，跟配置文件不符

**Comment by shuxsu** [comment]
> 看你配置文件里写明是有7类，结果索引index 6也就是最后一类错误，是否数据集里面只有6类，跟配置文件不符

不是6类+1背景类吗

**Comment by heavengate** [comment]
> > 看你配置文件里写明是有7类，结果索引index 6也就是最后一类错误，是否数据集里面只有6类，跟配置文件不符
> 
> 不是6类+1背景类吗

rcnn系列需要带背景类是要+1的，你确认一下是不是你数据集的类别数和配置文件的类别数匹配不上

**Comment by shuxsu** [comment]
> > > 看你配置文件里写明是有7类，结果索引index 6也就是最后一类错误，是否数据集里面只有6类，跟配置文件不符
> > 
> > 
> > 不是6类+1背景类吗
> 
> rcnn系列需要带背景类是要+1的，你确认一下是不是你数据集的类别数和配置文件的类别数匹配不上
 
我自查一下 感谢答复

**Comment by shuxsu** [comment]
> > > 看你配置文件里写明是有7类，结果索引index 6也就是最后一类错误，是否数据集里面只有6类，跟配置文件不符
> > 
> > 
> > 不是6类+1背景类吗
> 
> rcnn系列需要带背景类是要+1的，你确认一下是不是你数据集的类别数和配置文件的类别数匹配不上

另咨询一下 eval评估指标的相关说明 这些指标我看都是平均精确率和召回率  具体啥区别呢。。

>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.038
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.094
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.042
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.038
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.031
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.043
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.062
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.062

**Comment by heavengate** [comment]
一般主要看第一个和第二个指标，指标含义可以参考 https://www.jianshu.com/p/d7a06a720a2b

**Comment by shuxsu** [comment]
> 一般主要看第一个和第二个指标，指标含义可以参考 https://www.jianshu.com/p/d7a06a720a2b

感谢
