### ISSUE TITLE
是否有DeepSORT算法的源码？

### ISSUE THREAD

**Issue by Hyperjunct** [PaddlePaddle/PaddleDetection#7300]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

想提升目标跟踪的准确率，打算对原的DeepSORT算法进行修改，请问有关该跟踪算法的源码包含在哪些脚本文件里？

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/pptracking/python/mot 都在这里。
[base_sde_tracker.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/pptracking/python/mot/tracker/base_sde_tracker.py) ，[deepsort_tracker.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/pptracking/python/mot/tracker/deepsort_tracker.py) 这两个是最主要的。

修改改进是好的，但是建议算法和代码理解了再去修改，要修改第一步就是找相关的代码，顺着import都能找到，第一步应该不至于提issue来问吧。另外改tracker基本很难有高收益，建议你重训检测器或重训ReID。
