### ISSUE TITLE
No module named 'paddle._C_ops'

### ISSUE THREAD

**Issue by Young-GG** [PaddlePaddle/PaddleDetection#7303]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![图片](https://user-images.githubusercontent.com/93699131/201046671-516b6703-a15e-4663-adc2-706b896c6320.png)
在训练时遇到如上问题

**Comment by nemonameless** [comment]
版本问题，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/INSTALL_cn.md 

另外报bug请按模板提问谢谢。
https://github.com/PaddlePaddle/PaddleDetection/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml
