### ISSUE TITLE
二次开发问题

### ISSUE THREAD

**Issue by lw-2017** [PaddlePaddle/PaddleDetection#7304]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

pphuman 准备应用在公司的异常行为分析项目上，但是二次开发上出现一些问题，希望可以安排技术人员指导，希望能够和paddle深入合作

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/7154 扫码问卷后即可加群交流了
