### ISSUE TITLE
有关deepsort中pplcnet的重识别模型训练问题

### ISSUE THREAD

**Issue by MessonC** [PaddlePaddle/PaddleDetection#7305]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问如果我想用一个数据集去训练一个重识别模型，官方有没有相关的训练文档？另外是否有可以替换pplcnet的特征提取网络？谢谢

**Comment by MessonC** [comment]
还有个问题就是：现有的车辆跨境跟踪方案是否用了pplcnet替换了deepsort里面原有的视觉特征提取模块

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/mot/deepsort/reid/README_cn.md
https://github.com/PaddlePaddle/PaddleDetection/issues/5388
