### ISSUE TITLE
JDE的loss

### ISSUE THREAD

**Issue by chengzhixing0202** [PaddlePaddle/PaddleDetection#7306]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，请问回归任务中的loss中是使用的左下和右下两个角点的坐标吗？reg_target这里的坐标是进行了归一化吗？我这里想改一下iou，能否直接把reg_delta和reg_target输入到iou_loss中？

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/transform/mot_operators.py#L419
smooth_l1_loss 都可以改为 iou_loss。
