### ISSUE TITLE
cornernet_squeeze_dcn_r50_vd_fpn_mixup_cosine  使用这个模型的时候 局部变量报错

### ISSUE THREAD

**Issue by Stillremains** [PaddlePaddle/PaddleDetection#731]
![image](https://user-images.githubusercontent.com/48147367/82226553-38a99b80-9959-11ea-8646-9fea7e58104c.png)

**Comment by jerrywgz** [comment]
最新代码已修复～cornernet需要首先编译外部op corner_pooling，详细文档可以参考https://github.com/PaddlePaddle/PaddleDetection/tree/master/ppdet/ext_op

**Comment by Stillremains** [comment]
> 最新代码已修复～cornernet需要首先编译外部op corner_pooling，详细文档可以参考https://github.com/PaddlePaddle/PaddleDetection/tree/master/ppdet/ext_op

我直接按这个步骤编译?  没太懂呀

**Comment by jerrywgz** [comment]
是的，按流程编译后再进行训练预测即可。具体还有什么问题吗？

**Comment by Stillremains** [comment]
> 是的，按流程编译后再进行训练预测即可。具体还有什么问题吗？

一模一样吗我不需要改什么吗  我有点看不懂因为 并且现在在训练 可能等下午再试试了

**Comment by jerrywgz** [comment]
是的，编译阶段不需要对代码做修改

**Comment by Stillremains** [comment]
> 是的，编译阶段不需要对代码做修改

我刚刚试了下 发现 报错 不知道什么原因造成  报错如下：

/home/aistudio/PaddleDetection/ppdet/ext_op/src
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/libs
bottom_pool_op.cc:82:14: error: ‘GradOpPtr’ has not been declared
   void Apply(GradOpPtr<T> op) const override {
              ^
bottom_pool_op.cc:82:23: error: expected ‘,’ or ‘...’ before ‘<’ token
   void Apply(GradOpPtr<T> op) const override {
                       ^
bottom_pool_op.cc: In member function ‘void paddle::operators::BottomPoolGradDescMaker<T>::Apply(int) const’:
bottom_pool_op.cc:83:5: error: ‘op’ was not declared in this scope
     op->SetType("bottom_pool_grad");
     ^
bottom_pool_op.cc: In instantiation of ‘class paddle::operators::BottomPoolGradDescMaker<paddle::framework::OpDesc>’:
/usr/include/c++/5/type_traits:1459:12:   required from ‘struct std::is_base_of<paddle::framework::OperatorBase, paddle::operators::BottomPoolGradDescMaker<paddle::framework::OpDesc> >’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:74:25:   required from ‘constexpr const bool paddle::framework::details::internal::IsMatchedBaseTypeImpl<paddle::operators::BottomPoolGradDescMaker<paddle::framework::OpDesc>, 0, true>::kValue’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:86:63:   required from ‘constexpr bool paddle::framework::details::internal::IsMatchedBaseType() [with T = paddle::operators::BottomPoolGradDescMaker<paddle::framework::OpDesc>; int kPos = 0]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:118:53:   required by substitution of ‘template<class T> using OpInfoFillTypeGetter = paddle::framework::details::internal::OpInfoFillTypeGetterImpl<T, 0, 8, false, IsMatchedBaseType<T, 0>()> [with T = paddle::operators::BottomPoolGradDescMaker<paddle::framework::OpDesc>]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:125:47:   required from ‘static constexpr paddle::framework::details::OpInfoFillType paddle::framework::details::OpInfoFillTypeID<T>::ID() [with T = paddle::operators::BottomPoolGradDescMaker<paddle::framework::OpDesc>]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:144:71:   recursively required from ‘paddle::framework::details::OperatorRegistrarRecursive<I, false, ARGS ...>::OperatorRegistrarRecursive(const char*, paddle::framework::OpInfo*) [with long unsigned int I = 1ul; ARGS = {paddle::operators::BottomPoolOp, paddle::operators::BottomPoolOpMaker, paddle::operators::BottomPoolGradDescMaker<paddle::framework::OpDesc>, paddle::operators::BottomPoolGradDescMaker<paddle::imperative::OpBase>}]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:144:71:   required from ‘paddle::framework::details::OperatorRegistrarRecursive<I, false, ARGS ...>::OperatorRegistrarRecursive(const char*, paddle::framework::OpInfo*) [with long unsigned int I = 0ul; ARGS = {paddle::operators::BottomPoolOp, paddle::operators::BottomPoolOpMaker, paddle::operators::BottomPoolGradDescMaker<paddle::framework::OpDesc>, paddle::operators::BottomPoolGradDescMaker<paddle::imperative::OpBase>}]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/op_registry.h:63:5:   required from ‘paddle::framework::OperatorRegistrar<ARGS>::OperatorRegistrar(const char*) [with ARGS = {paddle::operators::BottomPoolOp, paddle::operators::BottomPoolOpMaker, paddle::operators::BottomPoolGradDescMaker<paddle::framework::OpDesc>, paddle::operators::BottomPoolGradDescMaker<paddle::imperative::OpBase>}]’
bottom_pool_op.cc:96:1:   required from here
bottom_pool_op.cc:82:8: error: ‘void paddle::operators::BottomPoolGradDescMaker<T>::Apply(int) const [with T = paddle::framework::OpDesc]’ marked ‘override’, but does not override
   void Apply(GradOpPtr<T> op) const override {
        ^
top_pool_op.cc:83:14: error: ‘GradOpPtr’ has not been declared
   void Apply(GradOpPtr<T> op) const override {
              ^
top_pool_op.cc:83:23: error: expected ‘,’ or ‘...’ before ‘<’ token
   void Apply(GradOpPtr<T> op) const override {
                       ^
top_pool_op.cc: In member function ‘void paddle::operators::TopPoolGradDescMaker<T>::Apply(int) const’:
top_pool_op.cc:84:5: error: ‘op’ was not declared in this scope
     op->SetType("top_pool_grad");
     ^
top_pool_op.cc: In instantiation of ‘class paddle::operators::TopPoolGradDescMaker<paddle::framework::OpDesc>’:
/usr/include/c++/5/type_traits:1459:12:   required from ‘struct std::is_base_of<paddle::framework::OperatorBase, paddle::operators::TopPoolGradDescMaker<paddle::framework::OpDesc> >’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:74:25:   required from ‘constexpr const bool paddle::framework::details::internal::IsMatchedBaseTypeImpl<paddle::operators::TopPoolGradDescMaker<paddle::framework::OpDesc>, 0, true>::kValue’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:86:63:   required from ‘constexpr bool paddle::framework::details::internal::IsMatchedBaseType() [with T = paddle::operators::TopPoolGradDescMaker<paddle::framework::OpDesc>; int kPos = 0]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:118:53:   required by substitution of ‘template<class T> using OpInfoFillTypeGetter = paddle::framework::details::internal::OpInfoFillTypeGetterImpl<T, 0, 8, false, IsMatchedBaseType<T, 0>()> [with T = paddle::operators::TopPoolGradDescMaker<paddle::framework::OpDesc>]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:125:47:   required from ‘static constexpr paddle::framework::details::OpInfoFillType paddle::framework::details::OpInfoFillTypeID<T>::ID() [with T = paddle::operators::TopPoolGradDescMaker<paddle::framework::OpDesc>]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:144:71:   recursively required from ‘paddle::framework::details::OperatorRegistrarRecursive<I, false, ARGS ...>::OperatorRegistrarRecursive(const char*, paddle::framework::OpInfo*) [with long unsigned int I = 1ul; ARGS = {paddle::operators::TopPoolOp, paddle::operators::TopPoolOpMaker, paddle::operators::TopPoolGradDescMaker<paddle::framework::OpDesc>, paddle::operators::TopPoolGradDescMaker<paddle::imperative::OpBase>}]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:144:71:   required from ‘paddle::framework::details::OperatorRegistrarRecursive<I, false, ARGS ...>::OperatorRegistrarRecursive(const char*, paddle::framework::OpInfo*) [with long unsigned int I = 0ul; ARGS = {paddle::operators::TopPoolOp, paddle::operators::TopPoolOpMaker, paddle::operators::TopPoolGradDescMaker<paddle::framework::OpDesc>, paddle::operators::TopPoolGradDescMaker<paddle::imperative::OpBase>}]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/op_registry.h:63:5:   required from ‘paddle::framework::OperatorRegistrar<ARGS>::OperatorRegistrar(const char*) [with ARGS = {paddle::operators::TopPoolOp, paddle::operators::TopPoolOpMaker, paddle::operators::TopPoolGradDescMaker<paddle::framework::OpDesc>, paddle::operators::TopPoolGradDescMaker<paddle::imperative::OpBase>}]’
top_pool_op.cc:97:1:   required from here
top_pool_op.cc:83:8: error: ‘void paddle::operators::TopPoolGradDescMaker<T>::Apply(int) const [with T = paddle::framework::OpDesc]’ marked ‘override’, but does not override
   void Apply(GradOpPtr<T> op) const override {
        ^
right_pool_op.cc:82:14: error: ‘GradOpPtr’ has not been declared
   void Apply(GradOpPtr<T> op) const override {
              ^
right_pool_op.cc:82:23: error: expected ‘,’ or ‘...’ before ‘<’ token
   void Apply(GradOpPtr<T> op) const override {
                       ^
right_pool_op.cc: In member function ‘void paddle::operators::RightPoolGradDescMaker<T>::Apply(int) const’:
right_pool_op.cc:83:5: error: ‘op’ was not declared in this scope
     op->SetType("right_pool_grad");
     ^
right_pool_op.cc: In instantiation of ‘class paddle::operators::RightPoolGradDescMaker<paddle::framework::OpDesc>’:
/usr/include/c++/5/type_traits:1459:12:   required from ‘struct std::is_base_of<paddle::framework::OperatorBase, paddle::operators::RightPoolGradDescMaker<paddle::framework::OpDesc> >’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:74:25:   required from ‘constexpr const bool paddle::framework::details::internal::IsMatchedBaseTypeImpl<paddle::operators::RightPoolGradDescMaker<paddle::framework::OpDesc>, 0, true>::kValue’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:86:63:   required from ‘constexpr bool paddle::framework::details::internal::IsMatchedBaseType() [with T = paddle::operators::RightPoolGradDescMaker<paddle::framework::OpDesc>; int kPos = 0]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:118:53:   required by substitution of ‘template<class T> using OpInfoFillTypeGetter = paddle::framework::details::internal::OpInfoFillTypeGetterImpl<T, 0, 8, false, IsMatchedBaseType<T, 0>()> [with T = paddle::operators::RightPoolGradDescMaker<paddle::framework::OpDesc>]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:125:47:   required from ‘static constexpr paddle::framework::details::OpInfoFillType paddle::framework::details::OpInfoFillTypeID<T>::ID() [with T = paddle::operators::RightPoolGradDescMaker<paddle::framework::OpDesc>]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:144:71:   recursively required from ‘paddle::framework::details::OperatorRegistrarRecursive<I, false, ARGS ...>::OperatorRegistrarRecursive(const char*, paddle::framework::OpInfo*) [with long unsigned int I = 1ul; ARGS = {paddle::operators::RightPoolOp, paddle::operators::RightPoolOpMaker, paddle::operators::RightPoolGradDescMaker<paddle::framework::OpDesc>, paddle::operators::RightPoolGradDescMaker<paddle::imperative::OpBase>}]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:144:71:   required from ‘paddle::framework::details::OperatorRegistrarRecursive<I, false, ARGS ...>::OperatorRegistrarRecursive(const char*, paddle::framework::OpInfo*) [with long unsigned int I = 0ul; ARGS = {paddle::operators::RightPoolOp, paddle::operators::RightPoolOpMaker, paddle::operators::RightPoolGradDescMaker<paddle::framework::OpDesc>, paddle::operators::RightPoolGradDescMaker<paddle::imperative::OpBase>}]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/op_registry.h:63:5:   required from ‘paddle::framework::OperatorRegistrar<ARGS>::OperatorRegistrar(const char*) [with ARGS = {paddle::operators::RightPoolOp, paddle::operators::RightPoolOpMaker, paddle::operators::RightPoolGradDescMaker<paddle::framework::OpDesc>, paddle::operators::RightPoolGradDescMaker<paddle::imperative::OpBase>}]’
right_pool_op.cc:96:1:   required from here
right_pool_op.cc:82:8: error: ‘void paddle::operators::RightPoolGradDescMaker<T>::Apply(int) const [with T = paddle::framework::OpDesc]’ marked ‘override’, but does not override
   void Apply(GradOpPtr<T> op) const override {
        ^
left_pool_op.cc:82:14: error: ‘GradOpPtr’ has not been declared
   void Apply(GradOpPtr<T> op) const override {
              ^
left_pool_op.cc:82:23: error: expected ‘,’ or ‘...’ before ‘<’ token
   void Apply(GradOpPtr<T> op) const override {
                       ^
left_pool_op.cc: In member function ‘void paddle::operators::LeftPoolGradDescMaker<T>::Apply(int) const’:
left_pool_op.cc:83:5: error: ‘op’ was not declared in this scope
     op->SetType("left_pool_grad");
     ^
left_pool_op.cc: In instantiation of ‘class paddle::operators::LeftPoolGradDescMaker<paddle::framework::OpDesc>’:
/usr/include/c++/5/type_traits:1459:12:   required from ‘struct std::is_base_of<paddle::framework::OperatorBase, paddle::operators::LeftPoolGradDescMaker<paddle::framework::OpDesc> >’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:74:25:   required from ‘constexpr const bool paddle::framework::details::internal::IsMatchedBaseTypeImpl<paddle::operators::LeftPoolGradDescMaker<paddle::framework::OpDesc>, 0, true>::kValue’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:86:63:   required from ‘constexpr bool paddle::framework::details::internal::IsMatchedBaseType() [with T = paddle::operators::LeftPoolGradDescMaker<paddle::framework::OpDesc>; int kPos = 0]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:118:53:   required by substitution of ‘template<class T> using OpInfoFillTypeGetter = paddle::framework::details::internal::OpInfoFillTypeGetterImpl<T, 0, 8, false, IsMatchedBaseType<T, 0>()> [with T = paddle::operators::LeftPoolGradDescMaker<paddle::framework::OpDesc>]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:125:47:   required from ‘static constexpr paddle::framework::details::OpInfoFillType paddle::framework::details::OpInfoFillTypeID<T>::ID() [with T = paddle::operators::LeftPoolGradDescMaker<paddle::framework::OpDesc>]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:144:71:   recursively required from ‘paddle::framework::details::OperatorRegistrarRecursive<I, false, ARGS ...>::OperatorRegistrarRecursive(const char*, paddle::framework::OpInfo*) [with long unsigned int I = 1ul; ARGS = {paddle::operators::LeftPoolOp, paddle::operators::LeftPoolOpMaker, paddle::operators::LeftPoolGradDescMaker<paddle::framework::OpDesc>, paddle::operators::LeftPoolGradDescMaker<paddle::imperative::OpBase>}]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/details/op_registry.h:144:71:   required from ‘paddle::framework::details::OperatorRegistrarRecursive<I, false, ARGS ...>::OperatorRegistrarRecursive(const char*, paddle::framework::OpInfo*) [with long unsigned int I = 0ul; ARGS = {paddle::operators::LeftPoolOp, paddle::operators::LeftPoolOpMaker, paddle::operators::LeftPoolGradDescMaker<paddle::framework::OpDesc>, paddle::operators::LeftPoolGradDescMaker<paddle::imperative::OpBase>}]’
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/fluid/framework/op_registry.h:63:5:   required from ‘paddle::framework::OperatorRegistrar<ARGS>::OperatorRegistrar(const char*) [with ARGS = {paddle::operators::LeftPoolOp, paddle::operators::LeftPoolOpMaker, paddle::operators::LeftPoolGradDescMaker<paddle::framework::OpDesc>, paddle::operators::LeftPoolGradDescMaker<paddle::imperative::OpBase>}]’
left_pool_op.cc:96:1:   required from here
left_pool_op.cc:82:8: error: ‘void paddle::operators::LeftPoolGradDescMaker<T>::Apply(int) const [with T = paddle::framework::OpDesc]’ marked ‘override’, but does not override
   void Apply(GradOpPtr<T> op) const override {
        ^

**Comment by qingqing01** [comment]
```
bottom_pool_op.cc:82:14: error: ‘GradOpPtr’ has not been declared
   void Apply(GradOpPtr<T> op) const override {
              ^
```
这个错误需要使用 paddle 1.8.1版本，并且注意GCC版本的要求 https://github.com/PaddlePaddle/PaddleDetection/tree/master/ppdet/ext_op#%E8%87%AA%E5%AE%9A%E4%B9%89op%E7%9A%84%E7%BC%96%E8%AF%91%E8%BF%87%E7%A8%8B

**Comment by qingqing01** [comment]
@Stillremains 可以使用下最新版本，如果还有问题，可以再开新的issue。
