### ISSUE TITLE
exclude_nms = false 获得onnx，再转 tensort，转化报错

### ISSUE THREAD

**Issue by QingYuan-L** [PaddlePaddle/PaddleDetection#7310]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

查阅资料是因为sort在onnx中会被转化冲topk算子，其中的k是变量，但是tensorrt只支持常量

`[11/11/2022-10:23:23] [E] [TRT] ModelImporter.cpp:775: input: "p2o.Gather.5"
input: "p2o.ReduceMin.1"
output: "p2o.TopK.1"
output: "p2o.TopK.2"
name: "p2o.TopK.0"
op_type: "TopK"

[11/11/2022-10:23:23] [E] [TRT] ModelImporter.cpp:776: --- End node ---
[11/11/2022-10:23:23] [E] [TRT] ModelImporter.cpp:779: ERROR: ModelImporter.cpp:163 In function parseGraph:
[6] Invalid Node - p2o.TopK.0
This version of TensorRT only supports input K as an initializer. Try applying constant folding on the model using Polygraphy: https://github.com/NVIDIA/TensorRT/tree/master/tools/Polygraphy/examples/cli/surgeon/02_folding_constants`

mmdetection 好像已经解决了这个问题，paddle还没有对应的解决方案
https://mmdetection.readthedocs.io/en/latest/_modules/mmdet/core/export/onnx_helper.html#:~:text=def%20get_k_for_topk(k%2C%20size)

**Comment by ghostxsl** [comment]
你跑的是哪个模型？

**Comment by lgy2830** [comment]
请问你跑的是哪个模型？我现在是导出模型时，把nms去掉了，然后转换成engine模型以后，不知道怎么写后处理部分了。
