### ISSUE TITLE
paddle2onnx转化后由opencv调用报错

### ISSUE THREAD

**Issue by HuaiguangLiu** [PaddlePaddle/PaddleDetection#7315]
### 请提出你的问题 Please ask your question

**我用paddleDetection2.1中的ppyolo_tiny_650e_coco模型训练自己的数据集后，用paddle2onnx转化后，再用opencv调用报错。**
paddleDetection 版本: 2.1
paddle2onnx版本1.01
opencv版本4.6

（1）模型导出命令：
`python tools/export_model.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml -o weights=output/ppyolo_tiny_650e_coco/model_final.pdparams TestReader.inputs_def.image_shape=[3,320,320]`

（2）paddle2onnx转化命令：
`paddle2onnx --model_dir output_inference/ppyolo_tiny_650e_coco --model_filename model.pdmodel --params_filename model.pdiparams --save_file models/ppyolo_tiny.onnx --opset_version 11 --enable_onnx_checker True  --input_shape_dict "{'image':[3,320,320]}"`
 
以上两步都是成功的，用onnxruntime.run也是成功的。但是用opencv::readNetFromONNX加载报错：

`net = cv2.dnn.readNetFromONNX('ppyolo_tiny.onnx')`
错误：
`cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20220524::ONNXImporter::handleNode'
> Node [Clip@ai.onnx]:(onnx_node!p2o.Clip.0) parse error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1934: error: (-2:Unspecified error) in function 'void __cdecl cv::dnn::dnn4_v20220524::ONNXImporter::parseClip(class cv::dnn::dnn4_v20220524::LayerParams &,const class opencv_onnx::NodeProto &)'
> >  (expected: 'node_proto.input_size() == 1'), where
> >     'node_proto.input_size()' is 3
> > must be equal to
> >     '1' is 1
> `

![load](https://user-images.githubusercontent.com/118034195/201466402-c5c79a80-e3c4-4c0a-9469-c0fac8b6c7ae.jpg)

**Comment by ghostxsl** [comment]
看报错信息是输入节点以及节点的shape信息没对上，你再check一下模型的输入节点呢
