### ISSUE TITLE
求飞浆版模型的开源代码

### ISSUE THREAD

**Issue by ZW-Shi** [PaddlePaddle/PaddleDetection#7316]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问有没有飞浆版的Fsater-RCNN模型的开源代码？，我没太理解paddledetection的内置的许多模型是一个怎么的架构思路

**Comment by ghostxsl** [comment]
可以先参考教程文档看一下：
https://github.com/PaddlePaddle/PaddleDetection#-%E6%96%87%E6%A1%A3%E6%95%99%E7%A8%8B
Fsater-RCNN模型：
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/faster_rcnn

**Comment by ZW-Shi** [comment]
你好，冒昧打扰，对于你们的paddleDetection使用流程我已经基本了解，我之所以想要FasterRcnn的飞浆版的开源代码，是因为FasterRcnn在paddlers上面做遥感图像的识别可以用得上，但是迫于没有飞浆版模型的源码，后续研究工作开展起来比较费时间，如果能有FasterRcnn的飞浆版的开源代码能节省我工作开展的大量时间，不知道是否方便分享一下源码。 感谢！！！


ShiZhiWei
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月14日(星期一) 中午1:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 求飞浆版模型的开源代码 (Issue #7316)





 
可以先参考教程文档看一下：
 https://github.com/PaddlePaddle/PaddleDetection#-%E6%96%87%E6%A1%A3%E6%95%99%E7%A8%8B
 Fsater-RCNN模型：
 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/faster_rcnn

**Comment by ghostxsl** [comment]
亲，我们库里的所有模型均是开源代码，建议你阅读教程文档，学习后阅读源码
