### ISSUE TITLE
obj365 数据集的模型和Ovid5 数据的模型 导出问题

### ISSUE THREAD

**Issue by baigang666** [PaddlePaddle/PaddleDetection#732]
在使用Release 0.3版本的时候，从官网下载上述两个数据集的模型，利用python的export_model.py导出的时候，报错：
RuntimeError: Failed to load model file , please make sure model file is saved with the following APIs: save_params, save_persistables, save_vars

求大亨解答一下

**Comment by jerrywgz** [comment]
可以发下你的具体导出命令吗

**Comment by baigang666** [comment]
python tools/export_model.py -c G:/BAIDU_Paddle/Paddle_0.3-0518/PaddleDetection-release-0.3/configs/obj365/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.yml --output_dir=./inference_model  -o weights=G:/BAIDU_Paddle/Paddle_0.3-0518/PaddleDetection-release-0.3/tools/model/obj365_cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms


@jerrywgz

**Comment by jerrywgz** [comment]
是否使用的是paddle1.7之前的版本，我这边使用paddle1.7版本在release/0.3分支下是能正确导出模型的

**Comment by baigang666** [comment]
https://paddlemodels.bj.bcebos.com/object_detection/cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas_obj365.tar

这个链接的模型也可以正尝导出么？
@jerrywgz 


我这边yolo模型  和fastrcnn这一类都可以正尝导出。但是obj365模型不能正常导出，上午在paddlepaddle交流群问了 说是obj365的模型和 ovid5的模型 必须自己训练。是这么回事么？

**Comment by baigang666** [comment]
![E4C5B5A4-6981-44db-960A-5AFD529FF891](https://user-images.githubusercontent.com/15216518/82290598-e5c3f880-99d9-11ea-86bd-6f5173aa46c0.png)

**Comment by baigang666** [comment]
![E4C5B5A4-6981-44db-960A-5AFD529FF891](https://user-images.githubusercontent.com/15216518/82290630-f5dbd800-99d9-11ea-9615-b6ab628322a2.png)

请问一下  我红色矩形框选项里的  模型是不是不能直接导出？ @jerrywgz

**Comment by jerrywgz** [comment]
是可以直接导出的，我上面说1.7版本+release/0.3就是测试的obj365的模型：
```python
python -u tools/export_model.py -c configs/obj365/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.yml -o weights=https://paddlemodels.bj.bcebos.com/object_detection/obj365_cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.tar
```
模型导出是不依赖数据集的

**Comment by baigang666** [comment]
谢谢   我将weights后面写成下载连接后 导出成功了 ，以前直接下载后解压 写文件所在路径一直失败，万分感谢！ @jerrywgz

**Comment by baigang666** [comment]
@jerrywgz  大神   导出obj365模型后  使用deploy文件夹下python提供的infer.py  预测报错。具体错误：
D:\Anaconda3\envs\BaiduPaddle_env\python.exe G:/BAIDU_Paddle/Paddle_0.3-0518/PaddleDetection-release-0.3/deploy/python/infer.py
Traceback (most recent call last):
  File "G:/BAIDU_Paddle/Paddle_0.3-0518/PaddleDetection-release-0.3/deploy/python/infer.py", line 577, in <module>
    predict_image()
  File "G:/BAIDU_Paddle/Paddle_0.3-0518/PaddleDetection-release-0.3/deploy/python/infer.py", line 501, in predict_image
    results = detector.predict(FLAGS.image_file, FLAGS.threshold)
  File "G:/BAIDU_Paddle/Paddle_0.3-0518/PaddleDetection-release-0.3/deploy/python/infer.py", line 482, in predict
    self.predictor.zero_copy_run()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "d:\anaconda3\envs\baidupaddle_env\lib\site-packages\paddle\fluid\framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "d:\anaconda3\envs\baidupaddle_env\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "d:\anaconda3\envs\baidupaddle_env\lib\site-packages\paddle\fluid\layers\nn.py", line 12640, in py_func
    'backward_skip_vars': list(backward_skip_vars)
  File "G:\BAIDU_Paddle\Paddle_0.3-0518\PaddleDetection-release-0.3\ppdet\modeling\ops.py", line 602, in __call__
    func=_soft_nms, x=[bboxes, scores], out=pred_result)
  File "G:\BAIDU_Paddle\Paddle_0.3-0518\PaddleDetection-release-0.3\ppdet\modeling\roi_heads\cascade_head.py", line 264, in get_prediction_cls_aware
    pred_result = self.nms(bboxes=box_out, scores=sum_cascade_cls_prob)
  File "G:\BAIDU_Paddle\Paddle_0.3-0518\PaddleDetection-release-0.3\ppdet\modeling\architectures\cascade_rcnn_cls_aware.py", line 170, in build
    self.cascade_decoded_box, self.cascade_bbox_reg_weights)
  File "G:\BAIDU_Paddle\Paddle_0.3-0518\PaddleDetection-release-0.3\ppdet\modeling\architectures\cascade_rcnn_cls_aware.py", line 323, in test
    return self.build(feed_vars, 'test')
  File "G:/BAIDU_Paddle/Paddle_0.3-0518/PaddleDetection-release-0.3/tools/export_model.py", line 196, in main
    test_fetches = model.test(feed_vars)
  File "G:/BAIDU_Paddle/Paddle_0.3-0518/PaddleDetection-release-0.3/tools/export_model.py", line 215, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Invalid python callable id
  [Hint: Expected i < g_py_callables.size(), but received i:0 >= g_py_callables.size():0.] at (D:\1.7.1\paddle\paddle\fluid\operators\py_func_op.cc:45)
  [operator < py_func > error]

Process finished with exit code 1

python中个参数设置如下：
 parser.add_argument(
        "--model_dir",
        type=str,
        default='G:/BAIDU_Paddle/Paddle_0.3-0518/PaddleDetection-release-0.3/tools/output/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms',
        help=("Directory include:'__model__', '__params__', "
              "'infer_cfg.yml', created by tools/export_model.py."),
        )
    Image_file='G:/BAIDU_Paddle/Paddle_0.3-0518/PaddleDetection-release-0.3/demo/000000014439.jpg'
    parser.add_argument(
        "--image_file", type=str, default='G:/BAIDU_Paddle/Paddle_0.3-0518/PaddleDetection-release-0.3/demo/000000014439.jpg', help="Path of image file.")
    Video_file='G:/BAIDU_Paddle/Paddle_0.3-0518/PaddleDetection-release-0.3/demo/vtest.avi'
    parser.add_argument(
        "--video_file", type=str, default='', help="Path of video file.")
    parser.add_argument(
        "--run_mode",
        type=str,
        default='fluid',
        help="mode of running(fluid/trt_fp32/trt_fp16/trt_int8)")
    parser.add_argument(
        "--use_gpu", default=False, help="Whether to predict with GPU.")
    parser.add_argument(
        "--threshold", type=float, default=0.2, help="Threshold of score.")
    parser.add_argument(
        "--output_dir",
        type=str,
        default="output",
        help="Directory of output visualization files.")

请大神帮忙解答一下，万分感谢

**Comment by jerrywgz** [comment]
哦这个模型使用了softnms，这个算子是通过pyfunc实现的，暂时还不支持预测部署。有两种解决方法：1. 将网络中softnms的输入作为export model时的输出，然后在infer的过程中对输出增加softnms的后处理；2. 将网络中的softnms替换为nms，其他操作不变（第二种方法的正确性我们验证下）

**Comment by qingqing01** [comment]
@baigang666  替换softnms的可以参考 https://github.com/PaddlePaddle/PaddleDetection/issues/729#issuecomment-630100926 ，你们导出模型是为了部署，或加速吗？如果不是，一般用tools/infer.py即可。

**Comment by baigang666** [comment]
谢谢 ，我们在做行人重识别  前期行人检测的准确度要求必须很高，我在尝试那个模型的准确度好一些，然后再针对性训练。 @qingqing01
