### ISSUE TITLE
关于模型内存占用较大的疑问

### ISSUE THREAD

**Issue by ysguo0327** [PaddlePaddle/PaddleDetection#7333]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 问题描述
我从[PP-Human快速开始](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/pipeline/docs/tutorials/PPHuman_QUICK_STARTED.md)中下载了行人跟踪（高精度）模型和行人跟踪（轻量级）模型，用于测试模型资源占用情况。由测试结果可知，当device=gpu时，内存消耗增加较大（3000M以上），且无法通过优化模型大小降低这种消耗，即使模型再小，也有3000M左右的固定消耗。请问这些内存消耗主要是哪些方面的？还有什么优化手段吗？我想要运行轻量级模型时内存占用能控制在1.5G以内。

### device=cpu
使用官方提供的大模型(182M)内存占用为2.8%，约918M，小模型(27M)内存占用为1.8%，约590M，内存占用差距有328M。
    
大模型
![image](https://user-images.githubusercontent.com/25575338/201806522-bbd0f72d-9b0d-43cc-9480-c81d1aef6418.png)
小模型
![image](https://user-images.githubusercontent.com/25575338/201806375-1ab03d5c-3642-44ae-ba99-268c12d4ddbc.png)

### device=gpu，run_mode=paddle
使用官方提供的大模型(182M)内存占用为12.3%，约4030M，小模型(27M)内存占用为11.7，约3884M，发现内存占用差距仅有146M，且比CPU模式内存占用提高3112M以上。    

大模型
![image](https://user-images.githubusercontent.com/25575338/201806667-c5f0f5a7-88d6-4735-9c8e-7f7000cf90a2.png)
小模型
![image](https://user-images.githubusercontent.com/25575338/201806628-9045cedc-7fd5-416f-9f4b-48c6d92fade7.png)

### device=gpu，run_mode=trt_fp16

device=gpu，run_mode=trt_fp16时，使用官方提供的大模型(182M)内存占用为15.2%，约4981M，小模型(27M)内存占用为14.0，约4588M，发现内存占用差距仅有146M，且比CPU模式内存占用提高4063M以上。    

大模型
![image](https://user-images.githubusercontent.com/25575338/201806900-369977cc-a100-4b41-9c7f-2ec66083641b.png)
小模型
![image](https://user-images.githubusercontent.com/25575338/201806943-9e98e74e-c3c4-4b24-a518-10572788827f.png)

**Comment by shao77622** [comment]
同样，trt fp16，推理ppvehicle，ppyoloe_plus_crn_t_auxhead_320_60e_ppvehicle 每个进程4g多的内存。
<img width="573" alt="截屏2023-04-10 22 28 25" src="https://user-images.githubusercontent.com/16330359/230921517-a17a2aef-bb1e-41b8-bf48-0722d8ec403f.png">

**Comment by ziyuwzf** [comment]
期待回复，内存占用过大与楼主情况一致
