### ISSUE TITLE
yolov7训练为什么会cuda error(719)

### ISSUE THREAD

**Issue by Zhw1997** [PaddlePaddle/PaddleDetection#7337]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

![image](https://user-images.githubusercontent.com/44230563/201876529-80c720bf-0ff9-4cdb-9042-18c1a69343fb.png)
yolov7训练失败 我尝试了示例教程中的roadsign_voc.yml也不行

### 复现环境 Environment

windows11
paddle 2.3.2post116

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
测试过不会报错，大概率是你的本地环境问题。win可以安装官网最新develop版本，版本号是0.0.0。

**Comment by Zhw1997** [comment]
> 测试过不会报错，大概率是你的本地环境问题。win可以安装官网最新develop版本，版本号是0.0.0。

多谢 我试试看

**Comment by Zhw1997** [comment]
> 测试过不会报错，大概率是你的本地环境问题。win可以安装官网最新develop版本，版本号是0.0.0
试了 还是不行 不懂了 难道是windows的问题 cpu能运行 gpu就出错

**Comment by Zhw1997** [comment]
我之后用aistudio上训练是可以的，使用示例中的roadsign_voc.yml但是100个epoh后出现ValueError: need at least one array to concatenate，不知道会不会继续出现

**Comment by nemonameless** [comment]
改了什么配置和代码请说明。
另外不要使用过小的bs去训，yolov7原版都是总bs=256。
