### ISSUE TITLE
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.   [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

### ISSUE THREAD

**Issue by ttm43** [PaddlePaddle/PaddleDetection#7341]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/30242069/202051020-1e29e33a-2366-4881-aac7-ed5b75eec68a.png)

`python tools/train.py -c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml --eval -o use_gpu=true`
当我尝试使用command训练的时候，出现了上述问题，已经上网搜寻了各种解答并逐一尝试，并无法解决这个问题

**Comment by wangxinxin08** [comment]
reader报错，应该是数据预处理出错，可以看下文件路径是否正确配置

**Comment by jersonal** [comment]
> reader报错，应该是数据预处理出错，可以看下文件路径是否正确配置

并不是，训练好几个step后还是报错

**Comment by wangxinxin08** [comment]
@jersonal 这种数据报错一版是文件路径或者数据预处理报错的问题，你可以先自行check一下数据

**Comment by ttm43** [comment]
> @jersonal 这种数据报错一版是文件路径或者数据预处理报错的问题，你可以先自行check一下数据
请问这里的数据格式和路径有什么问题么，以及我的数据中只有table一个label，那么num_classes应该是2么？
（val.json里面包含了test和val两个xml转换成的json，因为看到readme里面是这样处理的）
![image](https://user-images.githubusercontent.com/30242069/202937100-e4d0a159-7044-4727-87e5-6f7cd5efd48c.png)
![image](https://user-images.githubusercontent.com/30242069/202937116-13659066-cf2a-4840-8d0b-6bc67c1af078.png)
![image](https://user-images.githubusercontent.com/30242069/202937385-603440da-6c99-4415-a30e-8efddbb12245.png)
![image](https://user-images.githubusercontent.com/30242069/202937137-0792433a-aead-49a6-9248-b9821a23585b.png)

**Comment by ttm43** [comment]
最新情况，训练可以在cpu上进行，但是在gpu上就会报错

**Comment by ttm43** [comment]
> 最新情况，训练可以在cpu上进行，但是在gpu上就会报错

重装了一边paddlepaddle，以及python cuda cudnn，可以正常运行了

**Comment by wangxinxin08** [comment]
num_classes为前景类别，如果只有一个前景类别，就写1
