### ISSUE TITLE
自定义关键点训练，AP为0，已修改对应的sigma值

### ISSUE THREAD

**Issue by huanmengmie** [PaddlePaddle/PaddleDetection#7351]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我使用自定义的数据集和自定义的关键点进行训练。
已经修改了对应的sigma列表，但是eval时ap值一直为0。
然后我修改了infer文件，对应的关键点和线都能画出来，效果还不错。请问这是怎么回事呢？

**Comment by lyuwenyu** [comment]
可视化的 label能对上嘛
