### ISSUE TITLE
PP-Human摔倒二次开发

### ISSUE THREAD

**Issue by YaoOOoooolin** [PaddlePaddle/PaddleDetection#7355]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在自己训练集上测试摔倒，效果不好，所以想用自己的数据集提高摔倒行为识别的准确率，怎么给预训练模型增加样本继续训练呢？也就是ST-GCN继续训练

**Comment by lyuwenyu** [comment]
fineture就行吧  可以加载给的pretrained的模型去初始化

**Comment by YaoOOoooolin** [comment]
> fineture就行吧 可以加载给的pretrained的模型去初始化
您好，我也搜到了fine-tune，但是没有找到相关内容的具体操作步骤，有没有文档或者教程之类的

**Comment by YaoOOoooolin** [comment]
@lyuwenyu

**Comment by qiulongquan** [comment]
我想要继续这个话题，我们也需要根据ST-GCN行为识别模型训练自己的模型
但是我debug了花样滑冰的example程序，它采用的是25个关键点数据进行行为识别，并且采用npy文件方式保存25个关键点的数据
paddlepaddle没有详细说明如何创建自己的训练数据和标签文件，以及npy训练数据和标签数据的格式指导

请问  是否有手册指导如何根据自己的短视频获取人体骨骼点数据，以及如何利用骨骼点数据训练自己的ST-GCN模型
希望能尽快回复 谢谢
