### ISSUE TITLE
Do not find ByteTrack model for multi classes tracking

### ISSUE THREAD

**Issue by HanXuMartin** [PaddlePaddle/PaddleDetection#7358]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好， 你们的文档中有提到paddle的byte track模型可以用于多种类目标跟踪（除了原论文提到的行人跟踪），但我没有找到相应的介绍或者使用方法。能请您进一步说明如何运用paddledetection的bytetrack模型做多种类目标跟踪么？

**Comment by nemonameless** [comment]
检测器权重替换为多类别训的就行，再改改数据集路径和类别。
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/mot/bytetrack/bytetrack_ppyoloe.yml#L20

部署上多类别跟踪会更方便，只改模型权重即可，在PPTracking中，注意tracker需要改为 JDETracker 
  https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/pptracking/python#3-bytetrack%E5%92%8Coc_sort%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E5%92%8C%E9%A2%84%E6%B5%8B

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/7364
这是tools/infer 的例子，使用训好的原模型而非导出的部署模型。

**Comment by HanXuMartin** [comment]
感谢！不过我没有找到issue提到的文件：configs/mot/bytetrack/bytetrack_ppyoloe_ppvehicle9cls.yml
> #7364 这是tools/infer 的例子，使用训好的原模型而非导出的部署模型。

**Comment by nemonameless** [comment]
merged，在develop分支里
