### ISSUE TITLE
训练时，保存模型Save checkpoint 总是保存上次训练的路径

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleDetection#7360]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

这次训练picodet   在配置文件中weights已经修改了路径，但是训练起来时，模型保存的路径，Save checkpoin 总是上次的那个了路径。请问这是怎么回事啊

**Comment by nemonameless** [comment]
改save_dir为你想要的名字如xxx，默认叫output，但是最终存的目录是xxx加config名字，比如 output/picodet_l_320_coco，里面存pdparams权重。
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/runtime.yml#L4  改这行或在最终config里加上 save_dir: xxx 会覆盖掉runtime.yml里的设置

存模型权重的逻辑在，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/utils/checkpoint.py#L227

每个配置文件里写 weights: output/picodet_l_320_coco/best_model，意思是eval/infer的时候自动读取config里weights写的权重路径去过网络，训完后就是best_model或model_final，也可以自己在命令行中手动指定 -o weights=output/picodet_l_320_coco/10.pdparams
