### ISSUE TITLE
paddletection训练过程是否可以在网页端同步显示？

### ISSUE THREAD

**Issue by xuhui1994** [PaddlePaddle/PaddleDetection#7366]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我已经训练了基于yolov3的roadsign数据集，效果很好。这次想询问是否可以将_训练过程中控制台的输出信息_在网页端同步显示。比如我正在训练，另一个客户端想了解目前此时训练状态，就可以通过一个url链接在网页端看到，我目前使用了flask，但没有成功。
![image](https://user-images.githubusercontent.com/35833743/202667618-ac2ea1a9-9e9c-47f0-a6c5-ccb5aab0bf6f.png)
如上图，这是训练过程控制台的打印信息。

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/QUICK_STARTED_cn.md#1%E8%AE%AD%E7%BB%83 
加 --use_vdl=true

**Comment by xuhui1994** [comment]
我按照该方法实施了，并且也生成了数据，如下图

但当我仍然在visualDL看不到数据。

模型仍在正常训练中，请问是什么原因。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 下午5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] paddletection训练过程是否可以在网页端同步显示？ (Issue #7366)





 
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/QUICK_STARTED_cn.md#1%E8%AE%AD%E7%BB%83
 加 --use_vdl=true

**Comment by xuhui1994** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/QUICK_STARTED_cn.md#1%E8%AE%AD%E7%BB%83 加 --use_vdl=true
解决了谢谢
