### ISSUE TITLE
增强算子里没看到blur，会考虑加吗？

### ISSUE THREAD

**Issue by niiikolai** [PaddlePaddle/PaddleDetection#737]

**Comment by jerrywgz** [comment]
这个我们暂时还没有计划，如果有需要的话我们后续会评估下然后加进来，当然我们也十分欢迎向PaddleDetection中提pr～

**Comment by niiikolai** [comment]
作用真的十分明显，特别是对于产品检测，由于镜头快速拍摄可能导致部分图片没有对焦。在paddleX上测试加入高斯模糊后，效果拔群。所以还请考虑，谢谢。
