### ISSUE TITLE
PaddleDetection/configs/mot/mcfairmot/README.md 83行存在错误

### ISSUE THREAD

**Issue by lazyn1997** [PaddlePaddle/PaddleDetection#7372]
### 文档链接&描述 Document Links & Description

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/mot/mcfairmot/README.md
文档第83行单词拼写错误，应为video
![image](https://user-images.githubusercontent.com/34644177/202883283-e18f8ff0-f804-4704-b883-a4ecdabd1885.png)

### 请提出你的建议 Please give your suggestion

应修改为video

**Comment by zhiboniu** [comment]
好的，感谢反馈
