### ISSUE TITLE
用paddleDetection的yolov3训练出的模型，经过opt转成nb模型，无法在Android手机上，用paddle-lite-demo代码运行

### ISSUE THREAD

**Issue by sunjie0812** [PaddlePaddle/PaddleDetection#7378]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在安卓手机上用的这个官网demo代码：
https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo/object_detection_demo

个人在ubuntu18.04机器上，用paddleDetection训练安全帽的目标检测：
 1）用paddleDetection的yolov3系列算出的模型，经过导出、opt转发成nb模型。
 2）在Android-手机上部署好官网的目标检测的paddle-lite框架，用demo自带的nb模型，可正常运行软件及检测物体。
 3）但是替换成自己用paddleDetection算出的nb模型，就无法运行。
 
 
 有什么方法，能确定，为什么自己训练的模型转成nb模型，放到安卓demo中，无法运行？

**Comment by XYZ-916** [comment]
请问无法运行具体报什么错呢？

**Comment by sunjie0812** [comment]
![Android上预测代码报错](https://user-images.githubusercontent.com/43714788/202952723-f9e66bc8-930c-4c25-ab13-ffa9474617d1.png)

在安卓上的官方paddle-lite-demo代码中，替换自己的nb模型，然后运行软件，进行图片输入来预测时，会报这个错误。

**Comment by yingshengBD** [comment]
这个大概率是你所使用的paddlelite库和opt工具版本不匹配导致的
你的opt程序 和 paddlelite库 分别是哪里来的呢？

**Comment by sunjie0812** [comment]
opt转化程序获取链接：https://paddlelite.paddlepaddle.org.cn/v2.10/user_guides/opt/opt_python.html
截图：
![微信截图_20221121173950](https://user-images.githubusercontent.com/43714788/203017285-639548f3-2e5c-46c4-9457-2278db9cde9b.png)


**#####################################################################**

paddlelite库获取链接：https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-armlinux-demo/object_detection_demo
截图：
![微信截图_20221121174254](https://user-images.githubusercontent.com/43714788/203017890-1dcde65b-7fb2-45da-b458-077d11a48b69.png)
![微信截图_20221121174302](https://user-images.githubusercontent.com/43714788/203017899-d8897950-6c26-49d7-8178-aa273194e63d.png)

**Comment by yingshengBD** [comment]
![image](https://user-images.githubusercontent.com/74164525/203318259-81cd6841-2959-43fc-8e0c-a9e6f2350438.png)
demo中自带的库是2.10rc 版本 所以opt的pip install也改成2.10rc试试

**Comment by sunjie0812** [comment]
已经尝试过，opt的pip install改成2.10rc，结果依然不行的。

**Comment by sunjie0812** [comment]
我重新描述下，我的需求吧。也并不一定，非要解决这个安卓demo问题。

我的训练环境：
        在Ubuntu18.04系统上，安装paddleDetection模块，用yolov3预测出模型，经过opt工具转成了arm平台得nb模型

公司实际应用场景：
       把自己算出的nb模型，能够在安卓手机上运行起来，再进行拍摄照片，来预测结果。

我的最终目标：
        除了利用安卓demo框架，替换里面nb模型的方案外。
        是否还有其他的方案，能让在安卓手机上，支持用自己算出的模型，进行对图片的目标检测。

**Comment by 2804685987** [comment]
飞浆官方给的Android Demo  都是一个图片输入参数     一个结果输出参数   

而paddleDetection 训练出来的模型 是三个输入    和两个输出    你要对应这输入输出  来设置模型预测     

不然的话无法运行模型    (demo给的模型都是一个输入一个输出的  所以能运行)
