### ISSUE TITLE
x2coco 报错 PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/PaddleDetection#7384]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

C:\Windows\system32>python D:\work\data\ljy\x2coco.py --dataset_type labelme --json_input_dir D:\work\data\ljy\ --image_input_dir D:\work\data\ljy\ --output_dir D:\work\data\ljy\coco\

Traceback (most recent call last):
  File "D:\work\data\ljy\x2coco.py", line 542, in <module>
    main()
  File "D:\work\data\ljy\x2coco.py", line 487, in main
    shutil.copyfile(
  File "C:\Users\jing\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
PermissionError: [Errno 13] Permission denied: 'D:\\work\\data\\ljy\\coco'

### 复现环境 Environment

Windows
没有安装paddle 
仅数据格式转换

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by cunjing56** [comment]
问题解决，一定要让img 跟json 不在同一路径下，x2coco不能区分img跟json 。。。有人上传过他修正的代码，我这也跑不通。所以还是改一下文件路径吧！

**Comment by LokeZhou** [comment]
应该是路径的问题，打印一下输入shutil.copyfile 的src,dst路径看看是否正确，或者修改路径用. replace("\\","/")试试。
