### ISSUE TITLE
在Ubuntu18.04上怎么使用openvino进行部署

### ISSUE THREAD

**Issue by simple123456T** [PaddlePaddle/PaddleDetection#7393]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如标题：
在Ubuntu18.04上怎么使用openvino进行部署

同理在其他的linux系统上怎么使用openvino 进行部署推理。

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/third_engine/demo_openvino 可以参考这个文档

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/docs/advanced_tutorials/openvino_inference 这里是python版本的一个demo
