### ISSUE TITLE
PaddleDetection-JDE里面MOT16 test的MOTA是如何计算的

### ISSUE THREAD

**Issue by cloud9wj** [PaddlePaddle/PaddleDetection#7394]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/mot/jde/README_cn.md
表格JDE在MOT-16 Test Set上结果的MOTA是如何计算的，MOT16test数据集没有找到轨标注的gt文件夹

**Comment by nemonameless** [comment]
MOT-17 Test 和 MOT-16 Test 的指标均为交到 [MOTChallenge](https://motchallenge.net)官网测试集评测后的指标。
账号申请现在很难很快通过了，且每30天只能提交4次，每次必须间隔3天。
