### ISSUE TITLE
Windows下使用C++ TRT推测报错

### ISSUE THREAD

**Issue by cyanjustice** [PaddlePaddle/PaddleDetection#740]
将config.enable_tensorrt_engine开启后出现报错，应该是C++推理库里没有包含TRT库的原因。
请问有包含TRT库的Windows下C++inference库的封装教程吗，官网上只找到Linux下的带TRT的预测库。

**Comment by willthefrog** [comment]
`config.enable_tensorrt_engine`看上去应该是用`infer.py`吧？ 那需要编译paddle时开启tensorrt.

**Comment by cyanjustice** [comment]
> `config.enable_tensorrt_engine`看上去应该是用`infer.py`吧？ 那需要编译paddle时开启tensorrt.

编译paddle时没看到开启tensorrt选项

**Comment by willthefrog** [comment]
这个好像没有提供开关，编译时能够找到tensorrt就会自动打开。可以尝试设置一下`TENSORRT_ROOT`环境变量。见[这里](https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/tensorrt.cmake#L20)

**Comment by cyanjustice** [comment]
附带TRT的paddle编译成功了，但推理开启TRT仍然会报错，请问这是什么问题？
![image](https://user-images.githubusercontent.com/46018705/82625063-c1089480-9c16-11ea-8d15-110570223577.png)
![image](https://user-images.githubusercontent.com/46018705/82625075-ca91fc80-9c16-11ea-8722-01480406ab9f.png)

**Comment by willthefrog** [comment]
感觉像是框架windows支持的问题，检测库linux下执行tensorrt预测都是正常的。建议去Paddle的Repo提个issue吧。

**Comment by cyanjustice** [comment]
问题已解决
