### ISSUE TITLE
python  tools/eval.py  预测框的阈值哪里设置尼

### ISSUE THREAD

**Issue by LeFuGang** [PaddlePaddle/PaddleDetection#7401]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我想问下python  tools/eval.py评估测试集的时候，我想设置预测框的置信度阈值，我该从哪里设置，因为我想看下我阈值设置为多少Map效果最好；

我用是ppyoloe训练的，

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/ppyoloe/_base_/ppyoloe_plus_crn.yml#L43 可以调节下nms里面的参数
