### ISSUE TITLE
关键点检测标注工具推荐

### ISSUE THREAD

**Issue by 983183947** [PaddlePaddle/PaddleDetection#7407]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

关键点检测是否有比较好的标注工具推荐，目前用labelme标注关键点但是有2个问题

1、标注点的顺序不直观
2、标注后的文件还需要转换成coco模式

**Comment by wangxinxin08** [comment]
这类问题可以搜索一下就能找到，比如label studio
