### ISSUE TITLE
paddle自定义voc训练的时候yaml配置文件看不懂，不会修改。

### ISSUE THREAD

**Issue by lingdu-xu** [PaddlePaddle/PaddleDetection#7408]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

感谢paddle开发工程师们，paddle很好用，但是对于小白来说有很多参数完全不能理解是啥意思，也不知道如何按照自己的需求去修改，可否提供详细的yaml配置文件的说明文档，目前对如下文档理解不充分
_BASE_: [
  '../datasets/roadsign_voc.yml',
  '../runtime.yml',
  '_base_/optimizer_40e.yml',
  '_base_/yolov3_mobilenet_v1.yml',
  '_base_/yolov3_reader.yml',
]
比如，我如何定义512*512的训练集，如何定义训练轮数，如何定义数据增强方案，如何指定学习率等等，，不胜感激！

**Comment by wangxinxin08** [comment]
一般看配置文件的名字可以知道其大致的作用
1. 一般reader.yml是配置数据增强的，比如yolov3_reader.yml，设置size为512*512可以在这里设置
2. optimizer.yml是优化器相关，包括学习率，训练轮数，以及学习率策略和weight decay
3. 数据集一般在datasets目录下面，目前主要是coco和voc两种格式
4. yolov3_mobilenet_v1.yml就是模型配置，一般是模型名字+backbone之类的命名格式
