### ISSUE TITLE
coc预测格式数据类别与训练json中定义的对应不上

### ISSUE THREAD

**Issue by L-lei** [PaddlePaddle/PaddleDetection#741]
在ools/infer.py预测数据后保存的图片与训练数据anno_path变量对应的json文件中类别对应不上；
我的解决如下：
第1步.修改ppdet/data/source/coco.py中87行catid2clsid为：
        cats = coco.loadCats(coco.getCatIds())
        cats.sort(key=lambda a: a['id'])
        catid2clsid = {
            cat['id']: i + int(self.with_background)
            for i, cat in enumerate(cats)
        }
第2步./home/yt/cl/project_all/PaddleDetection/ppdet/utils/coco_eval.py中 423行clsid2catid 变量之前添加排序，cats.sort(key=lambda a:a['id'])

**Comment by willthefrog** [comment]
看上去像是环境问题，这部分代码很久没有修改过了，应该没问题的。你的改动只有当`coco.getCatIds()` 返回的顺序不固定时才说的通，但是用下面代码测试多次，返回的顺序是确定的。

```python
from pycocotools.coco import COCO
coco = COCO('coco/annotations/instance_val2017.json')
cat_ids = coco.getCatIds()
cats = coco.loadCats(coco.getCatIds())
print(cat_ids)
print(cats)
```

**Comment by L-lei** [comment]
执行多次返回的顺序是确定的，在训练与预测中的字典互换，需要下面2个条件之一才能成立。
第一个是：训练时与预测时加载的同一个json文件。
第二个是：训练时与预测时中的json文件中categories里面"子元素对象顺序必须一致"
原因在于cat_ids = coco.getCatIds()获取后值是按照categories子元素对象顺序返回的

我是用xml格式转的coco格式，训练与预测categories中id和name内容是可以对应上的

**Comment by willthefrog** [comment]
这种情况建议还是修改下json的`categories` 键值保持一致吧, 你的改法也只能适用于`categories`的数目一致的情况吧。

**Comment by L-lei** [comment]
是的
