### ISSUE TITLE
yoloe是否支持自动压缩？对精度速度的影响如何？ 

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/PaddleDetection#7413]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

yoloe是否支持自动压缩？对精度速度的影响如何？

**Comment by lyuwenyu** [comment]
可以参考这里的一些指标 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/auto_compression
