### ISSUE TITLE
ppyolo-tiny单卡训练卡住

### ISSUE THREAD

**Issue by phybrain** [PaddlePaddle/PaddleDetection#7414]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

训练自己的数据集卡住，没有报错，在loding pretrained weight后就不动了
```python

WARNING: OMP_NUM_THREADS set to 10, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads.
PLEASE USE OMP_NUM_THREADS WISELY.
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
W1125 15:21:33.249322 36604 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.2
W1125 15:21:33.275835 36604 device_context.cc:465] device: 0, cuDNN Version: 7.6.
[11/25 15:21:37] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/user/.cache/paddle/weights/MobileNetV3_large_x0_5_pretrained.pdparams

```
```shell
python tools/train.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml
```

### 复现环境 Environment

- OS: Ubuntu18.04
- PaddlePaddle: paddlepaddle-gpu 2.2.0
- PaddleDetection: release/2.4
- Python: 3.6.0
- CUDA: 10.2
- CUDNN: 7.6
- GCC: 8.2.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
升级一下paddlepaddle到2.3.2试一下

**Comment by phybrain** [comment]
> 升级一下paddlepaddle到2.3.2试一下

不行呢，picodet可以训练，ppyoloe-tiny不行

**Comment by lyuwenyu** [comment]
是自己的数据嘛，  你用分布式的命令起一下  看看有没有log

**Comment by phybrain** [comment]
> 是自己的数据嘛， 你用分布式的命令起一下 看看有没有log

```python
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
W1128 10:45:15.855607 18629 dynamic_loader.cc:276] You may need to install 'nccl2' from NVIDIA official website: https://developer.nvidia.com/nccl/nccl-downloadbefore install PaddlePaddle.
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 112, in run
    init_parallel_env()
  File "/home/user/paddle/PaddleDetection/ppdet/engine/env.py", line 44, in init_parallel_env
    paddle.distributed.init_parallel_env()
  File "/home/user/.pyenv/versions/pth1.4/lib/python3.6/site-packages/paddle/distributed/parallel.py", line 317, in init_parallel_env
    parallel_helper._init_parallel_ctx()
  File "/home/user/.pyenv/versions/pth1.4/lib/python3.6/site-packages/paddle/fluid/dygraph/parallel_helper.py", line 42, in _init_parallel_ctx
    __parallel_ctx__clz__.init()
RuntimeError: (PreconditionNotMet) The third-party dynamic library (libnccl.so) that Paddle depends on is not configured correctly. (error code is libnccl.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/phi/backends/dynload/dynamic_loader.cc:303)

```
分布式有报错

**Comment by A1exan10er** [comment]
It seems that you did not install NCCL2, which is required while using multiple GPUs.
Follow the link mentioned in the warning:
"Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
W1128 10:45:15.855607 18629 dynamic_loader.cc:276] You may need to install 'nccl2' from NVIDIA official website: https://developer.nvidia.com/nccl/nccl-downloadbefore install PaddlePaddle."

After successfully installed NCCL2, problem should be solved.

**Comment by A1exan10er** [comment]
> 是自己的数据嘛， 你用分布式的命令起一下 看看有没有log

@lyuwenyu @phybrain 
I think this issue can be closed.

I met similar error and solved by installing NCCL2 and solution mentioned above.
