### ISSUE TITLE
请问voc格式xml里面没有任何目标，会加入训练吗 

### ISSUE THREAD

**Issue by deshuai666** [PaddlePaddle/PaddleDetection#7417]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问voc格式xml里面没有任何目标，会加入训练吗

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/datasets/voc.yml#L11 
加上 allow_empty: True，可以支持空样本训练，但是数据集集这种数据不能太多，太多了会影响训练精度。一般可以参与训练，偶尔一个batch里混入了空样本也没关系，具体和batch_size有关，如果整个batch里都是空样本则可能会报错。
