### ISSUE TITLE
pp-yoloe-r训练的模型转onnx和tensorrt能跑通的教程有么？

### ISSUE THREAD

**Issue by CachCheng** [PaddlePaddle/PaddleDetection#7419]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 2. 需求场景（请描述你的项目中为什么需要用此功能）; 3. 功能描述（请简单描述或设计这个功能）

pp-yoloe-r训练好的模型转onnx和tensorrt能跑通的教程有么？

PP-YOLOE-R-s/m/l/x在RTX 2080 Ti上使用TensorRT FP16分别能达到69.8/55.1/48.3/37.1 FPS

我想测试这个时间

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/rotate/ppyoloe_r#%E9%80%9F%E5%BA%A6%E6%B5%8B%E8%AF%95

**Comment by wangxinxin08** [comment]
可以使用Paddle-TRT去部署，在ppyoloe_r的文档中有介绍，需要使用PaddlePaddle develop版本，并切TRT版本大于8.2，详见文档https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/rotate/ppyoloe_r#%E9%A2%84%E6%B5%8B%E9%83%A8%E7%BD%B2

**Comment by wangxinxin08** [comment]
ppyoloe新增了使用onnx runtime进行部署的python示例，可以参考PR:https://github.com/PaddlePaddle/PaddleDetection/pull/7457
