### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by shaodong-ai** [PaddlePaddle/PaddleDetection#7420]
请问一下，有全部的ppdet的预训练模型列表吗

**Comment by shaodong-ai** [comment]
包括ppyoloe+在obj365下预训练的预训练模型的这种全部预训练模型列表

**Comment by zhiboniu** [comment]
你好，所有的预训练模型可以在对应配置文件中找到，如下
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_l_pretrained.pdparams

**Comment by wlpczsz** [comment]
github中对应模型的config目录下有预训练模型列表的
