### ISSUE TITLE
KeyError: 'name'

### ISSUE THREAD

**Issue by suiyuedongyin** [PaddlePaddle/PaddleDetection#7422]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference, Export

### Bug描述 Describe the Bug

在aistudio上使用pp-yoloe训练模型，模型训练完毕，但当我试着infer和export时，报出同样的bug
‘’‘Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use OC-SORT, please install filterpy, for example: `pip install filterpy`, see https://github.com/rlabbe/filterpy
Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
Traceback (most recent call last):
  File "tools/export_model.py", line 108, in <module>
    main()
  File "tools/export_model.py", line 104, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 64, in run
    trainer = Trainer(cfg, mode='test')
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 83, in __init__
    '{}Dataset'.format(capital_mode))()
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 283, in create
    return cls(**cls_kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/data/source/dataset.py", line 270, in __init__
    type = dataset_args.pop("name")
KeyError: 'name'’‘’ 

### 复现环境 Environment

命令如下
!python tools/infer.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml --infer_img=../work/train/001.jpg -o weights=output/ppyoloe_plus_crn_s_80e_coco/best_model.pdparams --output_dir output/result --use_vdl=True

!python tools/export_model.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml  #--output_dir=./inference_model  -o weights=./output/ppyoloe_plus_crn_s_80e_coco/best_model.pdparams[](url)

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
你好，是否修改了配置文件，请跟原始的配置文件对照一下区别
'../datasets/coco_detection.yml'

**Comment by jiguanglu** [comment]
请问解决了吗？

**Comment by 710350964** [comment]
同样的问题，请问解决了嘛？

**Comment by ChenQiang-CN** [comment]
> 你好，是否修改了配置文件，请跟原始的配置文件对照一下区别 '../datasets/coco_detection.yml'

非常感谢，我是把"EvalDataset"下的“!COCODataSet”丢失，导致eval失败

**Comment by mjcaoo** [comment]
同样有这个情况，因为我没有设置test集，所以在coco_detection.yml文件上就没有写TestDataset部分，在添加上之后就没有这个报错了

**Comment by htaoruan** [comment]
@mjcaoo 所以没写test这种怎么解决呢，我数据集本身没有划分test

**Comment by mjcaoo** [comment]
> @mjcaoo 所以没写test这种怎么解决呢，我数据集本身没有划分test

在数据集的yml文件里，把验证集当成测试集用就可以了
