### ISSUE TITLE
faster rcnn预测结果不正常

### ISSUE THREAD

**Issue by yuanyc06** [PaddlePaddle/PaddleDetection#743]
![图片](https://user-images.githubusercontent.com/14346915/82422688-5ab83080-9ab5-11ea-97a4-c591c0d13681.png)

使用faster-rcnn（save成params和model的模型）进行预测，输出检测框不正常，如上图的状态，不同的图都出现351和266两个数，不知是什么问题？

**Comment by willthefrog** [comment]
输入大小是？看上去像是预测超出图片边界，crop后就变成0x0的bbox了。能否具体描述下复现步骤?

**Comment by yuanyc06** [comment]
图片本身是1056*800的，输入网络的resize规则是短边resize到800，所以输入的其实就是实际尺寸

**Comment by willthefrog** [comment]
内部沟通已解决。
