### ISSUE TITLE
请问paddle_detection有半监督训练的实现嘛？

### ISSUE THREAD

**Issue by TinyQi** [PaddlePaddle/PaddleDetection#7438]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在paperswithcode.com的半监督榜单上看到排名第二的方法中（Dense Teacher: Dense Pseudo-Labels for Semi-supervised Object Detection），代码复现中有PaddleDetection的链接，但是我找了很久没有找到。麻烦官方提示一下。谢谢啦。
![image](https://user-images.githubusercontent.com/28993936/205056801-a768557c-9762-458c-bc84-808ac0321e4d.png)

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/semi_det 
在develop分支里，欢迎使用~
