### ISSUE TITLE
合并coco格式数据集

### ISSUE THREAD

**Issue by lwh104** [PaddlePaddle/PaddleDetection#7439]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我有8个类别的文件夹，用labelme分别对8个类别的文件夹打了标签。
我准备从每个文件夹中挑选出20%作为验证集，其他剩余的作为训练集，保证验证集类别均衡。
PaddleDection提供了转coco的代码，在我对每个文件夹都转为coco之后，请问我如何合并这几个数据集，有没有提供的工具呢？

**Comment by jerrywgz** [comment]
目前没有合并数据集的工具，可以根据coco数据集格式进行合并处理
