### ISSUE TITLE
【PaddleYOLO】专注YOLO系列，支持PP-YOLOE+、YOLOv8、YOLOv5、YOLOv7、YOLOv6、YOLOX、RTMDet等YOLO模型

### ISSUE THREAD

**Issue by thinkthinking** [PaddlePaddle/PaddleDetection#7442]
[PaddleYOLO](https://github.com/PaddlePaddle/PaddleYOLO) 是基于 [PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection) 的YOLO系列模型库，**只包含YOLO系列模型的相关代码**，支持`YOLOv3`、`PP-YOLO`、`PP-YOLOv2`、`PP-YOLOE`、`PP-YOLOE+`、`YOLOX`、`YOLOv5`、`YOLOv5u`、`YOLOv6`、`YOLOv7`、`YOLOv8`、`RTMDet`等YOLO模型，COCO数据集模型库请参照 [ModelZoo](https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/docs/MODEL_ZOO_cn.md) 和 [configs](https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/configs/)。

github网址为：https://github.com/PaddlePaddle/PaddleYOLO
gitee网址为：https://gitee.com/nemonameless/PaddleYOLO

**注意:**
 - **[PaddleYOLO](https://github.com/PaddlePaddle/PaddleYOLO)** 代码库协议为 **[GPL 3.0](https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/LICENSE)**，**[YOLOv5](https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/configs/yolov5)、[YOLOv6](https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/configs/yolov6)、[YOLOv7](https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/configs/yolov7)和[YOLOv8](https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/configs/yolov8)这几类模型代码不合入 [PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection)**，其余YOLO模型推荐在 [PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection) 中使用，**会最先发布PP-YOLO系列特色检测模型的最新进展**；
 - **[PaddleYOLO](https://github.com/PaddlePaddle/PaddleYOLO)** 代码库推荐安装**paddlepaddle-2.4.2以上的版本**，请参考[官网](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html)下载对应适合版本，**Windows平台请安装paddle develop版本**；
 - **[PaddleYOLO](https://github.com/PaddlePaddle/PaddleYOLO)** 的 **[Roadmap issue](https://github.com/PaddlePaddle/PaddleYOLO/issues/44)** 用于**收集用户需求**，欢迎提出您的建议和需求；
 - **[PaddleYOLO](https://github.com/PaddlePaddle/PaddleYOLO)** 的**自定义数据集训练教程**请参考 **[Tutorial issue](https://github.com/PaddlePaddle/PaddleYOLO/issues/43)** ;

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO
