### ISSUE TITLE
pp-yoloe-r loss权重怎么设置？

### ISSUE THREAD

**Issue by LLsmile** [PaddlePaddle/PaddleDetection#7444]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

旋转目标检测的结果可视化出来发现旋转角度精度不高，所以想增加角度的权重看看效果，不知道这个功能支不支持？大概就是把xywhr四个数据的权重分开

**Comment by wangxinxin08** [comment]
**一般情况下，你需要首先确认训练的结果是否符合预期，比如mAP是否足够高，如果不够高的话，建议你加载dota预训练或者检查下训练配置或者训练过程**。其次，在上面确认过之后，再通过可视化等手段看下是否存在角度精度不高的问题，如果存在的话，再通过调整https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/rotate/ppyoloe_r/_base_/ppyoloe_r_crn.yml#L32 的loss权重试下，loss_dfl为角度权重，loss_iou为x, y, w, h, angle的loss权重

**Comment by LLsmile** [comment]
Thanks.
