### ISSUE TITLE
使用离线量化效果并没有什么效果

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/PaddleDetection#7445]
### 问题描述 Please describe your issue

![image](https://user-images.githubusercontent.com/102579571/205225249-7b74c968-2549-4b1a-8dc7-a91ed9c0f54d.png)

demo如下
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/slim

**Comment by wangxinxin08** [comment]
测速时可以开启`--run_benchmark=True`

**Comment by lilianjie111111** [comment]
> 测速时可以开启`--run_benchmark=True`

cpu推理也支持么？

**Comment by wangxinxin08** [comment]
> > 测速时可以开启`--run_benchmark=True`
> 
> cpu推理也支持么？

deploy/python和deploy/cpp都支持的
