### ISSUE TITLE
多机分布训练文档是死链

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/PaddleDetection#7453]
### 文档链接&描述 Document Links & Description

一个小问题，这有个死链

https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/ppyoloe#training

![WeChat Image_20221204215437](https://user-images.githubusercontent.com/29757093/205539321-c6f9089c-403e-4799-96b7-d6243190d7d6.png)

**Comment by ghostxsl** [comment]
感谢你的建议，修复PR已提：#7456
