### ISSUE TITLE
yolov4跑不起来

### ISSUE THREAD

**Issue by GitLD** [PaddlePaddle/PaddleDetection#746]
环境aistudio GPU环境，python3.6，paddle1.7.1， 1.8都试了有问题，问题如下

> Traceback (most recent call last):
>   File "tools/train.py", line 366, in <module>
>     main()
>   File "tools/train.py", line 113, in main
>     train_fetches = model.train(feed_vars)
>   File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 156, in train
>     return self.build(feed_vars, mode='train')
>   File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 85, in build
>     gt_score, targets)
>   File "/home/aistudio/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 294, in get_loss
>     self.prefix_name)
>   File "/home/aistudio/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 69, in __call__
>     mask_anchors, self._ignore_thresh)
>   File "/home/aistudio/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 169, in _get_fine_grained_loss
>     num_classes, downsample, self._ignore_thresh, scale_x_y)
>   File "/home/aistudio/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 294, in _calc_obj_loss
>     scale_x_y=scale_x_y)
> TypeError: yolo_box() got an unexpected keyword argument 'scale_x_y'

**Comment by willthefrog** [comment]
yolov4需要最新的paddle 版本，`scale_x_y` 这个参数是刚加的

**Comment by qingqing01** [comment]
@GitLD 使用release/0.3 分支 使用Paddle 1.7, 1.8.1版本都可以。 使用master分支得使用paddle 2.0.alpha 版本，master分支增加了scale_x_y。

**Comment by GitLD** [comment]
> @GitLD PaddleDetection release/0.3 分支 使用Paddle 1.7, 1.8.1版本都可以。 使用master分支得使用paddle 2.0.alpha 版本，master分支增加了scale_x_y。 @jerrywgz 可以加个版本提示。

确实切换成release/0.3就没问题了，不过感觉PaddleDection对应paddle版本确实有时候搞不太清楚
