### ISSUE TITLE
预测出的bbox为负值

### ISSUE THREAD

**Issue by jo-dean** [PaddlePaddle/PaddleDetection#7468]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

使用ppyoloe_plus_crn_s_80e训练自己的数据集，大小为640*640的
使用其他图像不会出现这个问题
然后输入一张320*320的图像预测，发现预测出的bbox为负数
``result: [array([[ 1.0000000e+00,  6.3330078e-01, **-2.9725800e+00,  1.8005371e-03,
         3.1049582e+02,  3.2003864e+02],**
       [ 1.0000000e+00,  5.0292969e-01,  2.5281305e+02,  1.4746356e+02,
         3.1985501e+02,  2.7952563e+02],
       [ 0.0000000e+00,  3.5522461e-01,  1.3457812e+02,  2.3038281e+02,
         1.4402734e+02,  2.4767578e+02],
       ...,
       [ 2.0000000e+00,  1.4282227e-02,  2.4241772e+02,  1.9275638e+02,
         2.4717708e+02,  2.0183223e+02],
       [ 2.0000000e+00,  1.4282227e-02,  2.9335938e+02,  2.3135938e+02,
         3.1301562e+02,  2.8592188e+02],
       [ 3.0000000e+00,  1.4282227e-02,  1.3967969e+02,  2.6551562e+02,
         1.5274609e+02,  2.9681250e+02]], dtype=float32), array([300], dtype=int32)] 300

### 复现环境 Environment

训练
Linux
paddledet                   2.5.0
paddlepaddle-gpu            2.3.2.post116
推理
预编译的推理库
paddlepaddle-gpu            2.3.2.post116

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by XYZ-916** [comment]
可以debug看下模型推理后后处理部分。

**Comment by smalie2222** [comment]
请问为什么会出现负值呢？我也遇到了这样的问题
