### ISSUE TITLE
PP-YOLOE-R yaml 

### ISSUE THREAD

**Issue by zhengqun** [PaddlePaddle/PaddleDetection#7469]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/34435100/206114376-46ae9e24-9977-4328-a2ad-086c54a79e2d.png)

**Comment by wangxinxin08** [comment]
截图可以截全一些，猜测是yaml读取报错，你可以把yaml改成utf-8格式编码

**Comment by zhengqun** [comment]
> 

![image](https://user-images.githubusercontent.com/34435100/206115698-2ac12317-d569-457d-852b-26564f31a77c.png)

**Comment by wangxinxin08** [comment]
@zhengqun 你试下PaddleDetection\ppdet\core\workspace.py 搜索 open，然后都加上encoding=‘utf-8’

**Comment by zhengqun** [comment]
> encoding=‘utf-8’

你好，上午试过了，还是报那个错，是不是空格不对？

**Comment by wangxinxin08** [comment]
> > encoding=‘utf-8’
> 
> 你好，上午试过了，还是报那个错，是不是空格不对？

有可能，一般是yaml编码或者格式有误

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/206155171-eceb5da0-5cde-4ed3-b296-b8fee0635503.png)
paddledet =2.5.0 py:3.9.7

**Comment by wangxinxin08** [comment]
> ![image](https://user-images.githubusercontent.com/34435100/206155171-eceb5da0-5cde-4ed3-b296-b8fee0635503.png) paddledet =2.5.0 py:3.9.7

需要使用PaddleDetection的develop版本

**Comment by zhengqun** [comment]
> > ![image](https://user-images.githubusercontent.com/34435100/206155171-eceb5da0-5cde-4ed3-b296-b8fee0635503.png) paddledet =2.5.0 py:3.9.7
> 
> 需要使用PaddleDetection的develop版本

好的，多谢！

**Comment by zhengqun** [comment]
你好，我想问下，保存的结果里的类别和图片中检测的类别怎么全都不一样？代码能统计每个类别的数量吗？

**Comment by wangxinxin08** [comment]
> 你好，我想问下，保存的结果里的类别和图片中检测的类别怎么全都不一样？代码能统计每个类别的数量吗？

默认的配置是没有这个问题，你改动了什么配置？

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/206180535-140a9049-f3ed-4f03-ac36-61eb634d06ac.png)
这是我的运行命令，P0112.PNG里检测到了swimming-pool，但是保存的结果里没有swimming-pool。不好意思哈，我是第一次接触paddle。

**Comment by wangxinxin08** [comment]
发一下result.txt看下

**Comment by zhengqun** [comment]
[P0112.txt](https://github.com/PaddlePaddle/PaddleDetection/files/10176091/P0112.txt)

**Comment by wangxinxin08** [comment]
把图片也发一下我测试下，bench这个类不存在在DOTA数据集中，怀疑你可能错误地改动了什么配置或者代码？

**Comment by zhengqun** [comment]
P0112.png太大了，给你张10M以内的。
![P0057](https://user-images.githubusercontent.com/34435100/206183823-315ea07b-4582-4699-bb6c-d6841ced0c72.png)

**Comment by zhengqun** [comment]
代码没有动一点，图片上检测出来的类对，但是结果里的类不对。

**Comment by zhengqun** [comment]
是不是 save_result 写的有问题？

**Comment by wangxinxin08** [comment]
@zhengqun 这个是由于annotations.json没有读到，加载默认类别时加载了coco类别，已经修复：https://github.com/PaddlePaddle/PaddleDetection/pull/7473
