### ISSUE TITLE
如何使用./tools/infer.py推理在数据集配置文件coco_detection_xx.py中设定的测试集？

### ISSUE THREAD

**Issue by BainOuO** [PaddlePaddle/PaddleDetection#7471]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

metric: COCO
num_classes: 1

TrainDataset:
  !COCODataSet
    image_dir: images
    anno_path: annotations/train.json
    dataset_dir: dataset/data20221125
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: images
    anno_path: annotations/val.json
    dataset_dir: dataset/data20221125

TestDataset:
  !ImageFolder
    anno_path: annotations/test.json 
    dataset_dir: dataset/data20221125 

我的数据集配置文件如上：
数据集目录为
-annotation
 --train.json
 --val.json
 --test.json
-labels
-images

教程里的infer只能推理单张图片或单个文件夹
那数据集配置文件中的TestDataset怎么使用呢

**Comment by nemonameless** [comment]
可以写在EvalDataset里，像这样 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/ppyolo/ppyolo_test.yml
TestDataset里的json只是为了获取种类。
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/tools/infer.py#L166  只支持测试图片文件夹和单张图。
