### ISSUE TITLE
pphuman 训练多卡，在中间轮报错

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/PaddleDetection#7475]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

训练pphuman 使用mix_det数据集，使用下面的训练语句， 0-12轮正常，到了12轮后就报错了
python -m paddle.distributed.launch --log_dir=ppyoloe --gpus 0,1 tools/train.py -c configs/mot/bytetrack/detector/yolox_x_24e_800x1440_mix_det.yml --eval --amp

错误日志：
00 eta: 6:55:05 batch_cost: 0.9762 data_cost: 0.0008 ips: 6.1460 images/s
[12/08 02:04:19] ppdet.engine INFO: Epoch: [13] [ 420/2436] learning_rate: 0.000241 loss: 4.119185 loss_cls: 0.570294 loss_obj: 1.240836 loss_iou: 0.468043 loss_l1: 0.000000 size: 832.000000 eta: 6:54:44 batch_cost: 0.8378 data_cost: 0.0009 ips: 7.1612 images/s
[12/08 02:04:38] ppdet.engine INFO: Epoch: [13] [ 440/2436] learning_rate: 0.000241 loss: 3.701521 loss_cls: 0.541089 loss_obj: 1.011433 loss_iou: 0.435085 loss_l1: 0.000000 size: 704.000000 eta: 6:54:25 batch_cost: 0.9306 data_cost: 0.0009 ips: 6.4472 images/s

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::ThrowExceptionToPython(std::__exception_ptr::exception_ptr)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1670436290 (unix time) try "date -d @1670436290" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0xbb07b) received by PID 766075 (TID 0x7ff1f7d2c3c0) from PID 766075 ***]

LAUNCH INFO 2022-12-08 02:04:51,548 Pod failed
LAUNCH ERROR 2022-12-08 02:04:51,549 Container failed !!!
Container rank 0 status failed cmd ['/root/anaconda3/envs/pp37/bin/python', '-u', 'tools/train.py', '-c', 'configs/mot/bytetrack/detector/yolox_x_24e_800x1440_mix_det.yml', '--eval', '--amp'] code -6 log ppyoloe/workerlog.0 
env {'CONDA_SHLVL': '2', 'LD_LIBRARY_PATH': '/root/anaconda3/envs/pp37/lib/python3.7/site-packages/cv2/../../lib64:/usr/local/cuda-10.2/lib64', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'CONDA_EXE': '/root/anaconda3/bin/conda', 'LC_MEASUREMENT': 'zh_CN.UTF-8', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LC_PAPER': 'zh_CN.UTF-8', 'LC_MONETARY': 'zh_CN.UTF-8', 'LANG': 'en_US.UTF-8', 'SUDO_GID': '1000', 'OLDPWD': '/data/zhangshilin/bytetrack/PaddleDetection/configs', 'USERNAME': 'root', 'CONDA_PREFIX': '/root/anaconda3/envs/pp37', 'SUDO_COMMAND': '/bin/su', '_CE_M': '', 'LC_NAME': 'zh_CN.UTF-8', 'USER': 'root', 'CONDA_PREFIX_1': '/root/anaconda3', 'PWD': '/data/zhangshilin/bytetrack/PaddleDetection', 'HOME': '/root', 'CONDA_PYTHON_EXE': '/root/anaconda3/bin/python', 'CUDA_HOME': '/usr/local/cuda-10.2', 'SUDO_USER': 'bigdata', '_CE_CONDA': '', 'LC_ADDRESS': 'zh_CN.UTF-8', 'LC_NUMERIC': 'zh_CN.UTF-8', 'CONDA_PROMPT_MODIFIER': '(pp37) ', 'SUDO_UID': '1000', 'MAIL': '/var/mail/root', 'SHELL': '/bin/bash', 'TERM': 'xterm', 'SHLVL': '1', 'LC_TELEPHONE': 'zh_CN.UTF-8', 'LOGNAME': 'root', 'PATH': '/root/anaconda3/envs/pp37/bin:/root/anaconda3/condabin:/usr/local/cuda-10.2/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda-10.2/bin', 'LC_IDENTIFICATION': 'zh_CN.UTF-8', 'CONDA_DEFAULT_ENV': 'pp37', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'LC_TIME': 'zh_CN.UTF-8', '_': '/root/anaconda3/envs/pp37/bin/python', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'QT_QPA_PLATFORM_PLUGIN_PATH': '/root/anaconda3/envs/pp37/lib/python3.7/site-packages/cv2/qt/plugins', 'QT_QPA_FONTDIR': '/root/anaconda3/envs/pp37/lib/python3.7/site-packages/cv2/qt/fonts', 'POD_NAME': 'pcuvtm', 'PADDLE_MASTER': '127.0.1.1:47593', 'PADDLE_GLOBAL_SIZE': '2', 'PADDLE_LOCAL_SIZE': '2', 'PADDLE_GLOBAL_RANK': '0', 'PADDLE_LOCAL_RANK': '0', 'PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '127.0.1.1:47594,127.0.1.1:47595', 'PADDLE_CURRENT_ENDPOINT': '127.0.1.1:47594', 'PADDLE_TRAINER_ID': '0', 'PADDLE_TRAINERS_NUM': '2', 'PADDLE_RANK_IN_NODE': '0', 'FLAGS_selected_gpus': '0'}
LAUNCH INFO 2022-12-08 02:04:51,550 ------------------------- ERROR LOG DETAIL -------------------------
 size: 576.000000 eta: 6:57:26 batch_cost: 0.9543 data_cost: 0.0008 ips: 6.2873 images/s
[12/08 02:02:13] ppdet.engine INFO: Epoch: [13] [ 280/2436] learning_rate: 0.000244 loss: 3.808643 loss_cls: 0.540701 loss_obj: 1.068927 loss_iou: 0.440078 loss_l1: 0.000000 size: 736.000000 eta: 6:57:07 batch_cost: 0.9236 data_cost: 0.0009 ips: 6.4962 images/s
[12/08 02:02:32] ppdet.engine INFO: Epoch: [13] [ 300/2436] learning_rate: 0.000244 loss: 4.398577 loss_cls: 0.578722 loss_obj: 1.350881 loss_iou: 0.488598 loss_l1: 0.000000 size: 768.000000 eta: 6:56:48 batch_cost: 0.8982 data_cost: 0.0009 ips: 6.6799 images/s
[12/08 02:02:52] ppdet.engine INFO: Epoch: [13] [ 320/2436] learning_rate: 0.000244 loss: 4.138979 loss_cls: 0.560420 loss_obj: 1.332568 loss_iou: 0.468133 loss_l1: 0.000000 size: 832.000000 eta: 6:56:28 batch_cost: 0.9121 data_cost: 0.0008 ips: 6.5779 images/s
[12/08 02:03:05] ppdet.engine INFO: Epoch: [13] [ 340/2436] learning_rate: 0.000243 loss: 3.946646 loss_cls: 0.560777 loss_obj: 1.058180 loss_iou: 0.469519 loss_l1: 0.000000 size: 608.000000 eta: 6:56:04 batch_cost: 0.6506 data_cost: 0.0009 ips: 9.2224 images/s
[12/08 02:03:24] ppdet.engine INFO: Epoch: [13] [ 360/2436] learning_rate: 0.000243 loss: 3.936405 loss_cls: 0.570180 loss_obj: 1.007267 loss_iou: 0.472712 loss_l1: 0.000000 size: 608.000000 eta: 6:55:45 batch_cost: 0.9009 data_cost: 0.0013 ips: 6.6598 images/s
[12/08 02:03:41] ppdet.engine INFO: Epoch: [13] [ 380/2436] learning_rate: 0.000242 loss: 3.908615 loss_cls: 0.553348 loss_obj: 1.104859 loss_iou: 0.445904 loss_l1: 0.000000 size: 608.000000 eta: 6:55:23 batch_cost: 0.7664 data_cost: 0.0008 ips: 7.8288 images/s
[12/08 02:04:01] ppdet.engine INFO: Epoch: [13] [ 400/2436] learning_rate: 0.000242 loss: 4.402491 loss_cls: 0.580077 loss_obj: 1.331369 loss_iou: 0.494085 loss_l1: 0.000000 size: 864.000000 eta: 6:55:05 batch_cost: 0.9762 data_cost: 0.0008 ips: 6.1460 images/s
[12/08 02:04:19] ppdet.engine INFO: Epoch: [13] [ 420/2436] learning_rate: 0.000241 loss: 4.119185 loss_cls: 0.570294 loss_obj: 1.240836 loss_iou: 0.468043 loss_l1: 0.000000 size: 832.000000 eta: 6:54:44 batch_cost: 0.8378 data_cost: 0.0009 ips: 7.1612 images/s
[12/08 02:04:38] ppdet.engine INFO: Epoch: [13] [ 440/2436] learning_rate: 0.000241 loss: 3.701521 loss_cls: 0.541089 loss_obj: 1.011433 loss_iou: 0.435085 loss_l1: 0.000000 size: 704.000000 eta: 6:54:25 batch_cost: 0.9306 data_cost: 0.0009 ips: 6.4472 images/s

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::ThrowExceptionToPython(std::__exception_ptr::exception_ptr)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1670436290 (unix time) try "date -d @1670436290" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0xbb07b) received by PID 766075 (TID 0x7ff1f7d2c3c0) from PID 766075 ***]

LAUNCH INFO 2022-12-08 02:04:52,516 Exit code -6

### 复现环境 Environment

ubuntu18.04
paddlepaddle-gpu   2.4.0
paddledetecion 2.4
python 3.7.15
cuda 10.2
cudnn 7.6
gcc 7.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by LokeZhou** [comment]
先尝试一下单卡是否能完整训练

**Comment by xiaomujiang** [comment]
> 先尝试一下单卡是否能完整训练

好的，我尝试下，但感觉是不是哪里有问题， 因为在多卡下，使用这个命令是正常运行的  python -m paddle.distributed.launch --log_dir=ppyoloe --gpus 0,1tools/train.py -c configs/mot/bytetrack/detector/ppyoloe_crn_l_36e_640x640_mot17half.yml --eval --amp

**Comment by xiaomujiang** [comment]
> 先尝试一下单卡是否能完整训练
单卡进行训练python tools/train.py -c  configs/mot/bytetrack/detector/yolox_x_24e_800x1440_mix_det.yml --eval --amp
结果不正常，精度很低

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.004
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.025
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.018
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.032
[12/12 15:19:13] ppdet.engine INFO: Total sample number: 2652, averge FPS: 52.639461307974

**Comment by GeT-RiGhTTT** [comment]
> > 先尝试一下单卡是否能完整训练
> > 单卡进行训练python tools/train.py -c  configs/mot/bytetrack/detector/yolox_x_24e_800x1440_mix_det.yml --eval --amp
> > 结果不正常，精度很低
> 
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.000 Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.002 Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.000 Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000 Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000 Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.001 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.000 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.004 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.025 Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000 Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.018 Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.032 [12/12 15:19:13] ppdet.engine INFO: Total sample number: 2652, averge FPS: 52.639461307974

你解决了吗 多卡还是单卡

**Comment by zzwang058** [comment]
大佬解决了吗

**Comment by GeT-RiGhTTT** [comment]
> 

把bt worknums 调小试试
