### ISSUE TITLE
STGCN

### ISSUE THREAD

**Issue by zhuoxun-xun** [PaddlePaddle/PaddleDetection#7477]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问怎么改stgcn二次开发的序列数据的维度要求。比如我想改T维度（动作序列的时序维度），要怎么执行呢？谢谢

N | 不定 | 数据集序列个数
C | 2 | 关键点坐标维度，即(x, y)
T | 50 | 动作序列的时序维度（即持续帧数）
V | 17 | 每个人物关键点的个数，这里我们使用了COCO数据集的定义，具体可见这里
M | 1 | 人物个数，这里我们每个动作序列只针对单人预测

**Comment by zhiboniu** [comment]
你好，具体相关配置修改可以参考paddlevideo中使用说明，paddlevideo有完备的训练说明文档：https://github.com/PaddlePaddle/PaddleVideo/tree/develop/applications/PPHuman#%E5%87%86%E5%A4%87%E8%AE%AD%E7%BB%83%E6%95%B0%E6%8D%AE
