### ISSUE TITLE
ImportError: cannot import name 'BASE_KEY' from 'ppdet.core.workspace' (D:\jupyter\data\PaddleDetection\ppdet\core\workspace.py)

### ISSUE THREAD

**Issue by Junxiang-Zeng8443** [PaddlePaddle/PaddleDetection#7478]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/112910942/206368590-192dfb33-3f44-4bf0-b6dd-badf01edbce6.png)

你好，我用j本地的upyter notobook训练模型的时候，出现了这样的报错，求解答，谢谢！

**Comment by jerrywgz** [comment]
可以检查下你的paddledetection安装版本，以及是否改动过源码 ppdet\core\workspace.py中的BASE_KEY是否改过
