### ISSUE TITLE
跑车流检测模型的时候使用TRT转换报错。

### ISSUE THREAD

**Issue by hezhi1220** [PaddlePaddle/PaddleDetection#7483]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

主要问题：跑车流检测模型的时候使用TRT转换报错。可以跑前50帧。 

其他问题：我把use_static改成了TRUE 每次模型转化还是要很久nx的盒子大概10分钟，而且找不到缓存的trt模型文件。

运行代码：python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_ppvehicle.yml  --video_file=3.mp4 --device=gpu  --region_type=vertical  --do_entrance_counting --run_mode=trt_fp16 

报错代码：Traceback (most recent call last):
  File "deploy/pipeline/pipeline.py", line 1112, in <module>
    main()
  File "deploy/pipeline/pipeline.py", line 1099, in main
    pipeline.run_multithreads()
  File "deploy/pipeline/pipeline.py", line 170, in run_multithreads
    self.predictor.run(self.input)
  File "deploy/pipeline/pipeline.py", line 490, in run
    self.predict_video(input, thread_idx=thread_idx)
  File "deploy/pipeline/pipeline.py", line 753, in predict_video
    plate_input)
  File "/home/nvidia/work/PaddleDetection/deploy/pipeline/ppvehicle/vehicle_plate.py", line 249, in get_platelicense
    plateboxes, det_time = self.platedetector.predict_image(image_list)
  File "/home/nvidia/work/PaddleDetection/deploy/pipeline/ppvehicle/vehicle_plate.py", line 127, in predict_image
    self.predictor.run()
ValueError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
3   paddle::operators::TensorRTEngineOp::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
4   phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
5   phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: TRT runtime input shape of x is invalid. Expect runtime input shape to be within min/max input shape configured in SetTRTDynamicShapeInfo(),but got runtime input shape = [1, 3, 736, 1728], min input shape = [1, 3, 50, 50], max input shape = [1, 3, 1536, 1536].
  [Hint: Expected is_input_shape_valid( runtime_input_shape, min_input_shape, max_input_shape) == true, but received is_input_shape_valid( runtime_input_shape, min_input_shape, max_input_shape):0 != true:1.] (at /home/paddle/data/xly/workspace/23282/Paddle/paddle/fluid/operators/tensorrt/tensorrt_engine_op.h:165)

**Comment by jerrywgz** [comment]
看报错是在车牌识别的部分，可以把配置文件里车牌的部分设置成enable：False看下
