### ISSUE TITLE
Any model trained on Sku110k dataset ?

### ISSUE THREAD

**Issue by jaideep11061982** [PaddlePaddle/PaddleDetection#7486]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Please let me know if any of the model that is trained on sku110k dataset
@zhangjun @ZeyuChen @QingshuChen @sjtubinlong @

**Comment by nemonameless** [comment]
see  https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/ppyoloe/application/README.md

https://github.com/PaddlePaddle/PaddleDetection/pull/7465
