### ISSUE TITLE
picodet-openvinoC++部署如何在代码中限制检测框个数

### ISSUE THREAD

**Issue by uuyymilkyl** [PaddlePaddle/PaddleDetection#7495]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

由于后续的算力邮有限，如果我想在目标检测种限制检测框个数 ，如一个画幅只找到2个最高分数的bounding box该怎么做呢

**Comment by nemonameless** [comment]
是想在后处理NMS后进行？先找到获取结果框的代码，然后对结果框数据加个分数或限制只保留最高分两个框的过滤
。
