### ISSUE TITLE
自定义数据集训练报错AttributeError: object has no attribute 'use_gpu'

### ISSUE THREAD

**Issue by laoda1112222** [PaddlePaddle/PaddleDetection#7497]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/120240710/206949679-6a8eca21-e886-4c5f-b523-8b7183fcbd25.png)
![image](https://user-images.githubusercontent.com/120240710/206949693-21b4cedf-0bbc-45a5-9ea7-f9a7a19e3934.png)
![image](https://user-images.githubusercontent.com/120240710/206949726-5106fb60-c20d-4854-b3df-9a947f325ba3.png)
![image](https://user-images.githubusercontent.com/120240710/206949736-ac8a9d3e-8fbc-4f2e-a32c-90826a7f2e4e.png)
![image](https://user-images.githubusercontent.com/120240710/206949753-a2145ca7-ab6b-45df-8753-d651db83f6a5.png)
![image](https://user-images.githubusercontent.com/120240710/206949767-8a911291-c418-4500-9826-2b079f11bc7f.png)

**Comment by nemonameless** [comment]
为更好的排查问题请按模板提问谢谢
https://github.com/PaddlePaddle/PaddleDetection/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml
把改动的代码说下，且附上环境版本和训练命令
