### ISSUE TITLE
tiny-pose多人姿态识别速度

### ISSUE THREAD

**Issue by jason9777** [PaddlePaddle/PaddleDetection#7498]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我使用PicoDet-V2-S-Lcnet-Pedestrian-320*320 + PP-TinyPose-128*96来进行多人姿态识别。我使用的是CPU版本，编译好了CPP。预测单张图片，图片中有6人，PicoDet耗时82ms，TinyPose耗时100ms。与文档中FP32精度下6人耗时47.63ms相差比较多。请问有什么可以改进预测速度的地方？

我的CPU是AMD Ryzen 9 5900HX，系统是ubuntu20.04。

使用命令：
./build/main --model_dir ../../checkpoints/picodet_v2_s_320_pedestrian --model_dir_keypoint ../../checkpoints/tinypose_128x96/ --image_file ./build/test.jpeg --cpu_threads 4

输出：
total images = 1, batch_size = 1, total steps = 1
class=0 confidence=0.9099 rect=[43 106 155 447]
class=0 confidence=0.8842 rect=[154 113 246 445]
class=0 confidence=0.8793 rect=[232 106 333 440]
class=0 confidence=0.8427 rect=[431 107 577 428]
class=0 confidence=0.8252 rect=[311 113 424 432]
class=0 confidence=0.7481 rect=[394 108 491 431]
./build/test.jpeg The number of detected box: 6
Visualized output saved as output/keypoint_test.jpeg
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1212 14:15:59.151413 241118 main_keypoint.cc:83] ----------------------- Config info -----------------------
I1212 14:15:59.151432 241118 main_keypoint.cc:84] runtime_device: CPU
I1212 14:15:59.151433 241118 main_keypoint.cc:85] ir_optim: True
I1212 14:15:59.151436 241118 main_keypoint.cc:87] enable_memory_optim: True
I1212 14:15:59.151443 241118 main_keypoint.cc:96] enable_tensorrt: False
I1212 14:15:59.151446 241118 main_keypoint.cc:98] precision: fp32
I1212 14:15:59.151450 241118 main_keypoint.cc:101] enable_mkldnn: False
I1212 14:15:59.151453 241118 main_keypoint.cc:102] cpu_math_library_num_threads: 4
I1212 14:15:59.151455 241118 main_keypoint.cc:103] ----------------------- Data info -----------------------
I1212 14:15:59.151458 241118 main_keypoint.cc:104] batch_size: 1
I1212 14:15:59.151463 241118 main_keypoint.cc:105] input_shape: dynamic shape
I1212 14:15:59.151465 241118 main_keypoint.cc:107] ----------------------- Model info -----------------------
I1212 14:15:59.151472 241118 main_keypoint.cc:109] model_name: ../../checkpoints/picodet_v2_s_320_pedestrian
I1212 14:15:59.151477 241118 main_keypoint.cc:110] ----------------------- Perf info ------------------------
I1212 14:15:59.151480 241118 main_keypoint.cc:111] Total number of predicted data: 1 and total time spent(ms): 82.2796
I1212 14:15:59.151515 241118 main_keypoint.cc:115] preproce_time(ms): 1.48065, inference_time(ms): 80.7722, postprocess_time(ms): 0.026749
I1212 14:15:59.151548 241118 main_keypoint.cc:121] ----------------------- Data info -----------------------
I1212 14:15:59.151563 241118 main_keypoint.cc:122] batch_size_keypoint: 8
I1212 14:15:59.151566 241118 main_keypoint.cc:123] ----------------------- Model info -----------------------
I1212 14:15:59.151571 241118 main_keypoint.cc:126] keypoint_model_name: ../../checkpoints/tinypose_128x96
I1212 14:15:59.151572 241118 main_keypoint.cc:127] ----------------------- Perf info ------------------------
I1212 14:15:59.151574 241118 main_keypoint.cc:128] Total number of predicted data: 6 and total time spent(ms): 100.189
I1212 14:15:59.151582 241118 main_keypoint.cc:132] Average time cost per person:
I1212 14:15:59.151585 241118 main_keypoint.cc:133] preproce_time(ms): 0.623758, inference_time(ms): 15.9578, postprocess_time(ms): 0.116624

**Comment by zhiboniu** [comment]
你好，47.63ms的数据是使用paddleLite fp16模式在移动端芯片 snapdragon 865上的测试结果，AMD的cpu上部署工具和芯片都有所不同，无法直接对比结果。

**Comment by jason9777** [comment]
是的，我在snapdragon 8gen1+的机器上使用paddleLite fp16模式测试为45.7ms，这符合预期。
请问如果用在PC端用paddle inference库进行推理有那些加速推理的方法？比如PicoDet部分，始终要80-100ms/it(取决于开启的cpu线程数)。我原以为PC端芯片比移动端芯片更为强大，能带来更快的推理速度的。

**Comment by zhiboniu** [comment]
可以试试用openvino部署
