### ISSUE TITLE
picodet 模型问题

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleDetection#7500]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

怎么在主干中增加3d坐标点，输出3d坐标，因为已经有2d的bbox了剩下的只需要3d点的坐标就 可以输出，但是需要怎么增加

**Comment by nemonameless** [comment]
参考 https://github.com/PaddlePaddle/Paddle3D
