### ISSUE TITLE
关于数据评估指标

### ISSUE THREAD

**Issue by YLiyu** [PaddlePaddle/PaddleDetection#7504]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我使用ppyoloe进行小目标检测，然后训练完成后，使用评估命令:
python tools/eval.py -c configs/smalldet/ppyoloe_crn_l_80e_sliced_visdrone_640_025.yml -o weights=/home/aistudio/work/PaddleDetection/output_first/best_model.pdparams
然后出来的指标如下:
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.337
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.685
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.277
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.501
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.434
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.523
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.527
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.527
[12/13 12:55:01] ppdet.engine INFO: Total sample number: 3970, averge FPS: 22.740391863444945

我想知道0.5:0.95的AP，AR在small和medium中都为-1，这个指标正常吗？分别代表什么含义呢，
非常感谢

**Comment by ghostxsl** [comment]
PaddleDetection用的是cocoapi，可以自行在网上搜索关于coco指标的解答，https://www.jianshu.com/p/d7a06a720a2b

**Comment by YLiyu** [comment]
好的，谢谢

**Comment by BaiduPaddle** [comment]
PaddleDetection评估时用的是官方cocoapi，具体可自行参考官方coco评估指标说明。
![cd1786590049917b88f3811fee1be77](https://user-images.githubusercontent.com/128561709/226785235-87e2ba44-0501-4178-981f-09e5a9ca90db.png)
