### ISSUE TITLE
yolov4 Diou-NMS 实现

### ISSUE THREAD

**Issue by yinggo** [PaddlePaddle/PaddleDetection#751]
请问现阶段yolov4有考虑diou-nms的实现吗？没有看到对应的部分呢？跑出来的结果似乎还是对于重叠目标的检测不佳。。

**Comment by jerrywgz** [comment]
目前的实现中还没有加入diou-nms，原作者的实现中实际用到的是greedy_nms

**Comment by yinggo** [comment]
> 目前的实现中还没有加入diou-nms，原作者的实现中实际用到的是greedy_nms

好的，期待后续的更新~ 
请问对于重叠目标检测 有没有模型可以推荐下？
