### ISSUE TITLE
S2Anet自定义数据集训练中验证报错。

### ISSUE THREAD

**Issue by panp4n** [PaddlePaddle/PaddleDetection#7514]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddle版本：paddlepaddle-gpu2.4.post112
paddle detection版本：2.5
python：3.8

S2Anet模型训练中验证时报(InvalidArgument) multiclass_nms3(): argument (position 4) must be double, but got str (at ..\paddle\fluid\pybind\op_function_common.cc:211)
第一次保存参数文件前训练正常。
数据集按照paddle detection2.5要求制作，COCO格式中segmentation字段存放旋转框四个顶点。
报错截图：
![image](https://user-images.githubusercontent.com/40445051/207800727-54934eb5-6768-4138-8761-6b70b28d0f5b.png)

**Comment by panp4n** [comment]
用同样的数据集训练PPYoloe-r没有问题。

**Comment by wangxinxin08** [comment]
> 用同样的数据集训练PPYoloe-r没有问题。

看报错信息，可能是你MulticlassNMS的配置写错了

**Comment by panp4n** [comment]
我也妹改模型相关的东西啊

**Comment by wangxinxin08** [comment]
> 我也妹改模型相关的东西啊

自己检查/debug下吧

**Comment by ClassmateXiaoyu** [comment]
> 我也妹改模型相关的东西啊

你好，请问你解决这个问题了吗？我遇到的报错和你的一模一样，没有改模型，也就改了一下配置文件里的类别数，batchsize，epoch，coco数据集路径。

**Comment by panp4n** [comment]
> > 我也妹改模型相关的东西啊
> 
> 你好，请问你解决这个问题了吗？我遇到的报错和你的一模一样，没有改模型，也就改了一下配置文件里的类别数，batchsize，epoch，coco数据集路径。

还没有解决。我环境都是重新配的，现在不知道该如何解决。

**Comment by wangxinxin08** [comment]
@panp4n @ClassmateXiaoyu paddle 2.3.2+ppdet 2.5没有报错，你们试下这个环境。另外，遇到报错，先看报错信息自己思考一下，不行就debug下，培养自己动手解决问题的意识

**Comment by ClassmateXiaoyu** [comment]
> @panp4n @ClassmateXiaoyu paddle 2.3.2+ppdet 2.5没有报错，你们试下这个环境。另外，遇到报错，先看报错信息自己思考一下，不行就debug下，培养自己动手解决问题的意识

谢谢，问题得到解决，报错的时候paddle版本是2.4.0，回退到2.3.2后，可以正常运行了，没有报错。
