### ISSUE TITLE
yolo-nano模型输入尺寸问题

### ISSUE THREAD

**Issue by Ma-Liang-hub** [PaddlePaddle/PaddleDetection#7515]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

yolo-nano默认640*640训练模型，我想调整输入为1024或其他值，怎么设置，一直报错，不知道哪里改的不对

**Comment by nemonameless** [comment]
报错请按模板谢谢 https://github.com/PaddlePaddle/PaddleDetection/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml
