### ISSUE TITLE
option(WITH_MOT       "Whether to Compile MOT detector" ON)

### ISSUE THREAD

**Issue by lgy2830** [PaddlePaddle/PaddleDetection#7517]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在CMakeLists.txt中，我设置了option(WITH_MOT       "Whether to Compile MOT detector" ON)。也就是追踪时打开的。然后编译成功，在输入车辆跟踪检测模型与输入视频以后，输出视频中，检测框一直显示在视频的左顶角。没有正确的显示在车辆的位置上。

**Comment by nemonameless** [comment]
提供的信息太少很难帮排查，请再补充想些谢谢。先自查编译过程，最后运行命令至少发下。
