### ISSUE TITLE
paddledet的推理模型怎么打印出参数量是多少？

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/PaddleDetection#7525]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如上，请问如何打印出参数量是多少，搜到issue可以
params = sum([
    p.numel() for n, p in self.model. named_parameters()
    if all([x not in n for x in ['_mean', '_variance']])
]) # exclude BatchNorm running status
print('params: ', params)
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/engine/trainer.py#L141
但是在logger.info那个地方会报错，官方给纠正下吧，报错行
logger.info('Params: ', params / 1e6)

**Comment by wangxinxin08** [comment]
报什么错误？

**Comment by futureflsl** [comment]
> 报什么错误？

params 好像不是个数字不能直接除以1e6，报错大概是这个我已经调试得到params了，这个建议官方改下

**Comment by wangxinxin08** [comment]
@futureflsl params是一个数字啊
