### ISSUE TITLE
picodet-s训练出来的模型推理很慢

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/PaddleDetection#7526]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

采用完全一样的环境对分辨率640x360视频推理做FPS统计，结果如下
yolov5n GPU测试 36ms一张
nanodetplus-m-320 GPU测试 46ms一张
picodet-s-320 GPU测试 67ms一张
同样一模一样电脑一样视频不一样框架，但是速度明显最差为什么？

### 复现环境 Environment

windows10
paddlepaddle-gpu==2.3.2
paddledet==2.5.0
picodet-s-320

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
可以参考测速脚本进行测速，另外gpu环境可以考虑使用ppyoloe
