### ISSUE TITLE
ppyolo_r50vd_dcn_1x_coco.yml's infer.py output has no bounding box result

### ISSUE THREAD

**Issue by now2466** [PaddlePaddle/PaddleDetection#7527]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hello, I had some problem while follow quick start

I used this command
python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=/home/yoon/.cache/paddle/weights/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg

but output/000000014439.jpg has no bounding box result.
So i print bbox_res in visualize_results function(visualizer.py 32 lines )

then i got this boxes, this boxes's coordinates look strange and score(confidence) was so low.

And, in my environment, infer.py took too long time.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [09:36<00:00, 576.77s/it]

it takes 9 mins, i use single gpu(rtx 3070)

how do i fix this situation??

[{'image_id': 0, 'category_id': 41, 'bbox': [0.00039778975769877434, 0.018148453906178474, -0.0015120786847546697, -0.029572769068181515], 'score': 0.11924321949481964}, {'image_id': 0, 'category_id': 22, 'bbox': [0.02452731318771839, 0.0396442636847496, -0.031580097042024136, -0.058506252244114876], 'score': 0.1180451363325119}, {'image_id': 0, 'category_id': 41, 'bbox': [-0.011238429695367813, 0.03830855339765549, -0.01441720500588417, -0.04641220811754465], 'score': 0.10657654702663422}, {'image_id': 0, 'category_id': 41, 'bbox': [0.004437347874045372, 0.038424499332904816, 0.0021941103041172028, -0.05964824557304382], 'score': 0.10653954744338989}, ... {'image_id': 0, 'category_id': 14, 'bbox': [0.013428285717964172, 0.009826984256505966, -0.015274256002157927, -0.007382674608379602], 'score': 0.061835069209337234}, {'image_id': 0, 'category_id': 53, 'bbox': [-0.005796519108116627, 0.0031983908265829086, 0.006009767297655344, -0.013190273195505142], 'score': 0.06172925978899002}, {'image_id': 0, 'category_id': 6, 'bbox': [-0.01858193427324295, -0.022162729874253273, -0.02320018783211708, 0.012055030092597008], 'score': 0.06137837469577789}, {'image_id': 0, 'category_id': 53, 'bbox': [0.007230496499687433, 0.006925530266016722, -0.02591353515163064, 0.019961245823651552], 'score': 0.06116798147559166}]
[12/19 14:01:24] ppdet.engine INFO: Detection bbox results save in output/000000014439.jpg

Environment :
GPU : Single rtx3070 VRAM 8GB
CPU : 12th Gen Intel® Core™ i7-12700
RAM : 32GB
miniconda3 virtual environment
python=3.7
cuda-toolkit=10.2.89
cudnn=7.6.5
paddlepaddle-gpu=2.4.1

**Comment by lyuwenyu** [comment]
Hi,  

1. I cannot reproduced above phenomenon using `paddlepaddle 2.4.1`  

```python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg```
<img width="300" alt="image" src="https://user-images.githubusercontent.com/17582080/208364025-291b9417-a81e-495a-b5e8-4da30e2a97a2.png">

2. `it takes 9 mins, i use single gpu(rtx 3070)`
It should be that the NMS phase takes a long time for the strange results


3. Here, I have some questions and suggestions
- about system, linux or windows ? 
- about device, is the result correct just using CPU
- check your pretrained weights md5sum with [ppyolo_r50vd_dcn_1x_coco.pdparams](https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams)

**Comment by now2466** [comment]
> Hi,
> 
> 1. I cannot reproduced above phenomenon using `paddlepaddle 2.4.1`
> 
> `python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg` <img alt="image" width="300" src="https://user-images.githubusercontent.com/17582080/208364025-291b9417-a81e-495a-b5e8-4da30e2a97a2.png">
> 
> 2. `it takes 9 mins, i use single gpu(rtx 3070)`
>    It should be that the NMS phase takes a long time for the strange results
> 3. Here, I have some questions and suggestions
> 
> * about system, linux or windows ?
> * about device, is the result correct just using CPU
> * check your pretrained weights md5sum with [ppyolo_r50vd_dcn_1x_coco.pdparams](https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams)

3-1 Linux
3-2 just using CPU works, Thank you for advice

I guess problem 2 seems to be a problem with the cuda version.
Then, my gpu is rtx3070, How can i use cuda >=11.0?
When i use cudatoolkit==11.3.1, it makes error
*ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory*
I must use cuda=10.2?

**Comment by lyuwenyu** [comment]
Yes, I think your should using cuda >= 11.0,,  

- Install cuda>=11.0
- link `/usr/local/cuda` to your new installed cuda dir, (or export `LD_LIBRARY_PATH` and `PATH`)
- run `ldconfig` in bash
- take care to choose your proper cuda version when install paddlepaddle

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/17582080/208570551-4540b889-b955-4b69-ac10-708c3a66239d.png">

**Comment by now2466** [comment]
> Yes, I think your should using cuda >= 11.0,,
> 
> * Install cuda>=11.0
> * link `/usr/local/cuda` to your new installed cuda dir, (or export `LD_LIBRARY_PATH` and `PATH`)
> * run `ldconfig` in bash
> * take care to choose your proper cuda version when install paddlepaddle
> 
> <img alt="image" width="1238" src="https://user-images.githubusercontent.com/17582080/208570551-4540b889-b955-4b69-ac10-708c3a66239d.png">

Thank you for your advice, I'll try your solution.
Thank you

**Comment by xychen9459** [comment]
Hello. I have met the same no-box problem as @now2466 described before. 

I use WSL2 as the development environment, and the paddlepaddle with CUDA support is installed correctly. There is no bounding box when setting `use_gpu=true`. However, when I switch to CPU mode by setting `use_gpu=false`, the output image has boxes. 

My environment is :
miniconda3 virtual environment
python=3.9
cudatoolkit=11.6
cudnn=8.4
paddlepaddle-gpu=2.4.1.post116
