### ISSUE TITLE
ppyoloe训练多个目标模型出错

### ISSUE THREAD

**Issue by Martian-1** [PaddlePaddle/PaddleDetection#7528]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

yoloe+不能训练 多个目标检测吗？训练两个目标的数据集出现错误。

**Comment by nemonameless** [comment]
可以训练。自定义数据集请先自查数据集的制作过程，报错请按模板提问谢谢。
https://github.com/PaddlePaddle/PaddleDetection/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml
