### ISSUE TITLE
Python二次开发困难问题

### ISSUE THREAD

**Issue by Freshield** [PaddlePaddle/PaddleDetection#7534]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

目前的paddle detection在我的使用中对于二次开发，我个人有以下几个问题，希望有时间可以考虑改进下：
**1. 所有的信息都和配置文件深度绑定，模型的二次开发困难**：其实这个问题对于paddle当前其他的项目如paddle ocr也有类似的问题，但是在detection这边尤为的严重，所有的运行都和配置文件深度绑定，而且由于引入了模块化，甚至会配置文件还依赖配置文件的情况，在二次开发时，想找到一些类的信息，配置的信息以及模型的信息时非常混乱，难以定位以及修改。我个人在平时开发也会在很多地方使用配置文件，但更多的时候是协助减少参数输入之用，现在感觉有一些本末倒置了，变成面向配置编程了。
**2. 纯命令行调用，无python脚本示例以及API**：这个问题尤其严重，我把detection相关的二次开发任务都找了下，包括github上detection项目本身的示例，竟然都是命令行的，最神奇的是一个jupyter里一行python代码没有，都是命令行的命令，就有点离谱。隔壁paddle ocr好歹还有相应的python脚本的示例以及切口类，可以方便的进行二次开发，这里举个infer的例子。
最近在做人脸检测相关的，我们的人脸检测的示例，只是说通过调用infer，修改配置文件进行开发，那么打开tools/infer.py，可以看到除了读取配置文件以及输入参数，主要逻辑在于run的函数，使用trainer来进行预测，这里且不说用一个叫trainer的类来进行infer合不合理，这里有一个小点，命令行基本都是输入一个图像地址就完事了，但是真正业务很多时候都是图像的二进制数据，那么在这里images就需要是不只是一个str类型，而可能是numpy之类的类型，而通过predcit函数再打开，又由于使用create函数，所以具体的类信息简单的方法只能是用debug来进行查找。进到里边发现是TestReader类，而dataset是ImageFolder类，这里又只能用文件地址，如果想直接传入numpy数据没有任何的api接口。又比如，一般作为infer的函数，那么获取预测的结果应该是一个理所当然的需求，而由于命令行本身的问题，trainer的predict函数竟然是没有返回值的，这对于二次开发就很困惑了，作为一个用来预测的trainer类的predict函数竟然没有返回值，可能是开发逻辑本身是面向命令行的，所以这些相应的接口就都没有很深度的考虑。
上边是最近刚接触遇到的两个主要的问题，这可能更多的是项目本身的路线的问题，不过像paddle detection这样优秀的项目，如果可以把python脚本的需求考虑进去，我个人觉得可以很大方面促进项目更进一步的发展~

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by ghostxsl** [comment]
非常感谢你的建议～我们会将你的建议加入到后续的开发计划中，再次感谢～
