### ISSUE TITLE
solov2量化训练正常，但是导出模型后使用trt_int8进行识别时候报错了

### ISSUE THREAD

**Issue by dijiupianhai9** [PaddlePaddle/PaddleDetection#7536]
### 问题描述 Please describe your issue

./main --model_dir=../solov2_qat --image_dir=../images/ --run_mode=trt_int8
TensorRT dynamic shape enabled
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
3   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
5   paddle::AnalysisPredictor::OptimizeInferenceProgram()
6   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
8   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
9   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
10  paddle::framework::ir::DeleteQuantDequantOpPass::ApplyImpl(paddle::framework::ir::Graph*) const
11  paddle::framework::ir::GraphPatternDetector::operator()(paddle::framework::ir::Graph*, std::function<void (std::map<paddle::framework::ir::PDNode*, paddle::framework::ir::Node*, std::less<paddle::framework::ir::PDNode*>, std::allocator<std::pair<paddle::framework::ir::PDNode* const, paddle::framework::ir::Node*> > > const&, paddle::framework::ir::Graph*)>)
12  paddle::framework::ir::GraphSafeRemoveNodes(paddle::framework::ir::Graph*, std::unordered_set<paddle::framework::ir::Node const*, std::hash<paddle::framework::ir::Node const*>, std::equal_to<paddle::framework::ir::Node const*>, std::allocator<paddle::framework::ir::Node const*> > const&)
13  paddle::framework::ir::Graph::RemoveNode(paddle::framework::ir::Node*)
14  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
15  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
PreconditionNotMetError: The node to be removed does not exist.
  [Hint: Expected node_set_.find(node) != node_set_.end() == true, but received node_set_.find(node) != node_set_.end():0 != true:1.] (at /home/paddle/data/wangye19/Paddle/paddle/fluid/framework/ir/graph.h:213)

Aborted (core dumped)

**Comment by Rayxndt** [comment]
请问是怎样进行量化训练的呢
