### ISSUE TITLE
ppyoloe+_s_sod map为0

### ISSUE THREAD

**Issue by Yi-dashi** [PaddlePaddle/PaddleDetection#7538]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

最近尝试了用pytorch复现ppyolo-sod算法，因为gpu资源有限，只验证了ppyolo+-s-sod在coco上的指标，发现当部署小目标中心先验补偿+alpha主干时，指标是正常的，当在ppyoloe neck部分加入MultiHeadAttention后，map会在第3个epoch的时候降为0，起先也会伴随损失为nan的情况，我们对transformer重新初始化后便没有损失为nan的问题。现在的问题是，map为0和loss不变，请问下：你们在训练ppyoloe-sod的时候又遇到过同样的问题吗？添加transformer后，map在第3个epoch降为0这种情况是由什么导致的呢？希望得到您的回复

**Comment by Yi-dashi** [comment]
补充一点的是，我们用了混合精度训练

**Comment by nemonameless** [comment]
没有遇到过。提供的信息有点少，而且不是ppdet和paddle的代码，我们很难帮排查。mAP降为0因素很多，请先确保所有配置和我们提供的模型是一致的，以及你的复现和我们也是一致的 包括loss和梯度是对齐的，再去查问题吧。
