### ISSUE TITLE
paddledetection Infer picture to kitti txt

### ISSUE THREAD

**Issue by zjc5477** [PaddlePaddle/PaddleDetection#754]
我想将预测好的kitti图片转化为kitti txt描述文件（想用一下kitti官方的evaluation 程序评估一下），我需要怎么做才能实现啊？

**Comment by qingqing01** [comment]
@zjc5477 是想讲预测的bbox框输出到文本中吗？  如果是可以讲这里的 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/tools/infer.py#L183  bbox结果按照你需求的格式保存到文本文件中。

**Comment by zjc5477** [comment]
你好，这个是我想转化成[https://github.com/NVIDIA/DIGITS/blob/v4.0.0-rc.3/digits/extensions/data/objectDetection/README.md](url)#label format，这个格式现有的代码中有这些输出信息嘛，https://blog.csdn.net/weixin_42886817/article/details/102839065 这个是kitti官方出的一个评估程序，想要用这个程序来验证一下准确率

**Comment by zjc5477** [comment]
> @zjc5477 是想讲预测的bbox框输出到文本中吗？ 如果是可以讲这里的 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/tools/infer.py#L183 bbox结果按照你需求的格式保存到文本文件中。 或者如果还想把label也输出的话，通过tool/eval.py，在
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/f708d425d8deab26bfba59e72d8bd18453ad574e/ppdet/utils/eval_utils.py#L187
> 
> 这里把预测结果输出到text文件。 目前是可以保存到coco所需要的json格式里。
你好，这个是我想转化成https://github.com/NVIDIA/DIGITS/blob/v4.0.0-rc.3/digits/extensions/data/objectDetection/README.md#label format，这个格式现有的代码中有这些输出信息嘛，https://blog.csdn.net/weixin_42886817/article/details/102839065 这个是kitti官方出的一个评估程序，想要用这个程序来验证一下准确率

**Comment by qingqing01** [comment]
目前的输出是：NMS的输出，形状为[N, 6], N为预测框的个数，其中没一项是: [class_id, score, x1, y1, x2, y2] ，依据class_id可以得到具体的类型， score即为置信度，x1,y1,x2,y2分别为坐上和右下坐标。 可以具体这些信息转换下。

**Comment by zjc5477** [comment]
> 目前的输出是：NMS的输出，形状为[N, 6], N为预测框的个数，其中没一项是: [class_id, score, x1, y1, x2, y2] ，依据class_id可以得到具体的类型， score即为置信度，x1,y1,x2,y2分别为坐上和右下坐标。 可以依据这些信息转换下。

好的，我去看看，谢谢你
