### ISSUE TITLE
softnms在cascade_rcnn中的使用？

### ISSUE THREAD

**Issue by zhoupengc-zz** [PaddlePaddle/PaddleDetection#7546]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

BBoxPostProcess:
  decode:
    name: RCNNBox
    prior_box_var: [30.0, 30.0, 15.0, 15.0]
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.05
    nms_threshold: 0.5

能直接通过修改 MultiClassNMS 变为softnms么？ 具体应该怎么修改？

**Comment by nemonameless** [comment]
暂不支持softnms OP。也可以手写一个python的函数去做但是速度会很慢的多。
