### ISSUE TITLE
训练ppyloe+_s出现问题

### ISSUE THREAD

**Issue by Dekadenc** [PaddlePaddle/PaddleDetection#7547]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

训练到第四轮时报了以下错误：
![image](https://user-images.githubusercontent.com/102035987/209415188-740edea5-d07c-4b91-a6f8-377b52077585.png)
请问是什么原因，查看错误提示是否设置共享内存，去看了已经开了，之前训练时候还好好的

**Comment by nemonameless** [comment]
du -sh /dev/shm 先检查下是否已经很大内存了，然后清理下 rm -f  /dev/shm/*
