### ISSUE TITLE
PaddleInference编译问题

### ISSUE THREAD

**Issue by GoooHi** [PaddlePaddle/PaddleDetection#7548]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

环境：Windows 10; Cuda 11.6; Visual Studio 2019
问题描述：
![image](https://user-images.githubusercontent.com/109460192/209436708-24566ccc-754d-450e-8253-1a23344f5fb9.png)

**Comment by nemonameless** [comment]
cuda版本没对应上或缺东西。参考的哪篇文档？环境按文档上写的一一对应再去试试。
