### ISSUE TITLE
不想让数据集中某一类参加训练

### ISSUE THREAD

**Issue by gaohuayang** [PaddlePaddle/PaddleDetection#7549]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

VOC或者COCO格式的数据集，有一类不想要了（不想让这一类参加训练），能在配置文件或者代码里修改吗？还是需要在数据集的xml或者JSON文件中删除这一类的标注？

**Comment by jerrywgz** [comment]
建议还是离线处理下标注数据集
