### ISSUE TITLE
请问Pipeline对象是线程安全的吗？

### ISSUE THREAD

**Issue by liangshuisanqian** [PaddlePaddle/PaddleDetection#7551]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

最近在学习`ppvehicle`使用的过程中，把代码改成了提供http服务的方式：大致的方式是保持deploy/pipeline/pipeline.py中的主要流程不变，创建完`Pipeline`对象之后，不直接进行推理，而是把`Pipeline`对象保存下来， 然后通过flask启动了http服务；当有http请求进来的时候再通过之前保存的`Pipeline`对象进行推理。请问下`Pipeline`对象是否是线程安全的，是否可以工作在如上的方式下同时支持多个推理的请求？

我在mac mini 2018上进行了大致的测试（cpu推理），同时发出两个请求，有很大的概率其中一个请求无法推理出结果

**Comment by wangxinxin08** [comment]
Pipeline目前并没有做多线程相关处理，你可以参考https://www.paddlepaddle.org.cn/inference/v2.4/guides/performance_tuning/multi_thread.html 修改下代码

**Comment by liangshuisanqian** [comment]
> Pipeline目前并没有做多线程相关处理，你可以参考https://www.paddlepaddle.org.cn/inference/v2.4/guides/performance_tuning/multi_thread.html 修改下代码

好的，多谢！
