### ISSUE TITLE
关于旋转数据集格式转化脚本的需求以及旋转数据集数量增多，目前官方只提供了基于dota数据集转成能训练的coco脚本，像有些数据集是标注四点的多边形没有角度，或者是已经标注好的带角度的xml也需要单独运行脚本再处理。并且官方给的数据集dota有点大，大约40g，骨骼的也太小了，是否可以增加一些数据集的数量

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleDetection#7554]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 2. 需求场景（请描述你的项目中为什么需要用此功能）; 3. 功能描述（请简单描述或设计这个功能）

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
可以参考文档：https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/rotate#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86 准备数据，你只需要转成coco格式即可
