### ISSUE TITLE
评估ppyoloe模型时加上--classwise，想要输出每一个类别的AP值，报错

### ISSUE THREAD

**Issue by Dekadenc** [PaddlePaddle/PaddleDetection#7565]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用的环境信息：
![image](https://user-images.githubusercontent.com/102035987/209615110-bacae888-5dfc-45d8-bc2c-4a36b91dedc4.png)
1、使用的评估语句是：
CUDA_VISIBLE_DEVICES=0 python tools/eval.py \
	-c configs/ppyoloe/2022-12.26_ppyoloe_s_Baseline_SIOU.yml \
	-o weights=./output/2022-12.26-ppyoloe_s_Baseline_SIOU/2022-12.26_ppyoloe_s_Baseline_SIOU/best_model.pdparams \
	--classwise
报了如下错误：
![image](https://user-images.githubusercontent.com/102035987/209615193-502611fb-3e92-4cc9-b014-25bccad28023.png)
查阅了之前的issue发现有位同学也出现这个问题，但是不清楚他是在哪加的：
[https://github.com/PaddlePaddle/PaddleDetection/issues/3850](url)
![image](https://user-images.githubusercontent.com/102035987/209615412-341b91f7-edfc-461c-bb3e-70ed0af76774.png)

**Comment by lyuwenyu** [comment]
随便找个地方加都行吧  你可以加到tools/eval.py这个文件里

**Comment by Dekadenc** [comment]
> 随便找个地方加都行吧 你可以加到tools/eval.py这个文件里

解决了，感谢，下方输出的单类AP值是在0.5：0.95阈值下的结果吗，如果想要修改为0.5阈值下的结果该如何修改
![image](https://user-images.githubusercontent.com/102035987/209629215-795889f1-3843-4a40-b58e-6c7fc60644fd.png)
顺便再问下如何输出对应的Precision和Recall值呢

**Comment by lyuwenyu** [comment]
这个你可以在下面这个逻辑里 改一下输出  把Precision和Recall打印出来，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/metrics/coco_utils.py#L115

**Comment by youngyoung01** [comment]
你好，请问看到可以留个联系方式嘛，有些问题想要请教一下，谢谢
