### ISSUE TITLE
ppyoloe+训练问题

### ISSUE THREAD

**Issue by LeFuGang** [PaddlePaddle/PaddleDetection#7569]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我想请问下，我明明又540张训练图片，我训练ppyoloe+时batch size设置为32得，但是为什么我总得steps是3尼
![image](https://user-images.githubusercontent.com/28383188/209785099-7ddddd87-04d4-4676-9f79-3d820b0bbc1c.png)

不应该是540 / 32 吗，我是用coco_detection.yml设置数据路径得，
是不是没有目标得图片不会进去训练，而是被剔除掉？麻烦回答下

**Comment by nemonameless** [comment]
reader里设置的batch size是单卡的。总bs需要乘以卡数。
默认allow_empty为false，就是会剔除掉没gt的图片
