### ISSUE TITLE
InvalidArgumentError: The fed Variable gt_bbox should have dimensions = 3, shape = [-1, 505, 4], but received fed shape [8, 15, 4]

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/PaddleDetection#757]
使用paddledetection接口进行训练时出现以下错误，使用的是yolo模型
InvalidArgumentError: The fed Variable gt_bbox should have dimensions = 3, shape = [-1, 505, 4], but received fed shape [8, 15, 4]

**Comment by heavengate** [comment]
你修改了什么配置么，`gt_bbox`的shape默认应该是[-1, 50, 4]`，是不是哪里的配置修改错了

**Comment by liu824** [comment]
505代表的是框的最大数量，我把原来的15（yoloy配置默认是50,15是因为我copy的一个项目改成了15）改成了505就报错了

**Comment by heavengate** [comment]
> 505代表的是框的最大数量，我把原来的15（yoloy配置默认是50,15是因为我copy的一个项目改成了15）改成了505就报错了

框最大数量要匹配，如果你修改了`max_box_num`为505，对应的`PadBox`里的`max_box_num`也需要修改为505

**Comment by liu824** [comment]
谢谢，我昨晚发现了这个问题，已经改过来了

**Comment by heavengate** [comment]
好的，如果没有问题了，当前issue就先关闭了~
