### ISSUE TITLE
多进程报错

### ISSUE THREAD

**Issue by qq-tt** [PaddlePaddle/PaddleDetection#7571]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

多进程代码写法是参考网上的，能跑得通，但是用在飞桨这里就报错
![image](https://user-images.githubusercontent.com/32315802/209899671-eca1bb4c-ed74-4e55-824b-a8864bada620.png)
报错如下：
![image](https://user-images.githubusercontent.com/32315802/209899694-202c462d-bdf7-4e15-ab9a-c4873c9ed26d.png)

### 复现环境 Environment

linux:PadlepadleDetection

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by qq-tt** [comment]
自己找到答案了，这个问题可能是传进去的参数不能序列化导致的

**Comment by zhiboniu** [comment]
好的
