### ISSUE TITLE
VisDrone-DET 检测模型检测类别说明有误

### ISSUE THREAD

**Issue by tianmaxingkong168** [PaddlePaddle/PaddleDetection#7578]
### 文档链接&描述 Document Links & Description

链接：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/visdrone
第一段存在问题：PaddleDetection团队提供了针对VisDrone-DET小目标数航拍场景的基于PP-YOLOE的检测模型，用户可以下载模型进行使用。整理后的COCO格式VisDrone-DET数据集[下载链接](https://bj.bcebos.com/v1/paddledet/data/smalldet/visdrone.zip)，检测其中的10类，包括 pedestrian(1), people(2), bicycle(3), car(4), van(5), truck(6), tricycle(7), awning-tricycle(8), bus(9), motor(10)，原始数据集[下载链接](https://hub.nuaa.cf/VisDrone/VisDrone-Dataset)。
问题：这一部分“检测其中的10类，包括 pedestrian(1), people(2), bicycle(3), car(4), van(5), truck(6), tricycle(7), awning-tricycle(8), bus(9), motor(10)。”类别名和序号应该存在问题。
发现问题步骤：
1、执行如下命令python tools/infer.py -c configs/smalldet/ppyoloe_crn_l_80e_sliced_visdrone_640_025.yml --infer_img=demo/000000014439.jpg -o use_gpu=False weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_80e_sliced_visdrone_640_025.pdparams --infer_img=demo/000000014439.jpg --draw_threshold=0.1
2、output目录生成的文件打印的类别中包括traffic_light。
![000000014439](https://user-images.githubusercontent.com/68491689/210215881-6223c4c1-ba9e-4914-82db-f1329d00e332.jpg)

### 请提出你的建议 Please give your suggestion

从结果来看应该是有错的，暂时我也没找到正确的类别。

**Comment by tianmaxingkong168** [comment]
是否是这里面的前10个？
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 14, 13: 15, 14: 16, 15: 17, 16: 18, 17: 19, 18: 20, 19: 21, 20: 22, 21: 23, 22: 24, 23: 25, 24: 27, 25: 28, 26: 31, 27: 32, 28: 33, 29: 34, 30: 35, 31: 36, 32: 37, 33: 38, 34: 39, 35: 40, 36: 41, 37: 42, 38: 43, 39: 44, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 55, 50: 56, 51: 57, 52: 58, 53: 59, 54: 60, 55: 61, 56: 62, 57: 63, 58: 64, 59: 65, 60: 67, 61: 70, 62: 72, 63: 73, 64: 74, 65: 75, 66: 76, 67: 77, 68: 78, 69: 79, 70: 80, 71: 81, 72: 82, 73: 84, 74: 85, 75: 86, 76: 87, 77: 88, 78: 89, 79: 90} {1: 'person', 2: 'bicycle', 3: 'car', 4: 'motorcycle', 5: 'airplane', 6: 'bus', 7: 'train', 8: 'truck', 9: 'boat', 10: 'traffic light', 11: 'fire hydrant', 13: 'stop sign', 14: 'parking meter', 15: 'bench', 16: 'bird', 17: 'cat', 18: 'dog', 19: 'horse', 20: 'sheep', 21: 'cow', 22: 'elephant', 23: 'bear', 24: 'zebra', 25: 'giraffe', 27: 
'backpack', 28: 'umbrella', 31: 'handbag', 32: 'tie', 33: 'suitcase', 34: 'frisbee', 35: 'skis', 36: 'snowboard', 37: 'sports ball', 38: 'kite', 39: 'baseball bat', 40: 'baseball glove', 41: 'skateboard', 42: 'surfboard', 43: 'tennis racket', 44: 'bottle', 46: 'wine glass', 47: 'cup', 48: 'fork', 49: 'knife', 50: 'spoon', 51: 'bowl', 52: 'banana', 53: 'apple', 54: 'sandwich', 55: 'orange', 56: 'broccoli', 57: 'carrot', 58: 'hot dog', 59: 'pizza', 60: 'donut', 61: 'cake', 62: 
'chair', 63: 'couch', 64: 'potted plant', 65: 'bed', 67: 'dining table', 70: 'toilet', 72: 'tv', 73: 'laptop', 74: 'mouse', 75: 'remote', 76: 'keyboard', 77: 'cell phone', 78: 'microwave', 79: 'oven', 80: 'toaster', 81: 'sink', 82: 'refrigerator', 84: 'book', 85: 'clock', 86: 'vase', 87: 'scissors', 88: 'teddy bear', 89: 'hair drier', 90: 'toothbrush'}

**Comment by nemonameless** [comment]
你打印的是COCO 80类的种类，运行的时候有打印警告说数据集路径没找到所以采用默认COCO种类，请仔细观察打印信息。

https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/smalldet/ppyoloe_crn_l_80e_sliced_visdrone_640_025.yml#L2   根据这行去检查你的TestDataset配置，你的 anno_path 或 dataset_dir 路径现在应该是不存在的，把数据集下载放到对应目录下就行。https://bj.bcebos.com/v1/paddledet/data/smalldet/visdrone.zip  或者 https://bj.bcebos.com/v1/paddledet/data/smalldet/visdrone_sliced.zip 都可以，重点是TestDataset 配置正确。

**Comment by tianmaxingkong168** [comment]
> 你打印的是COCO 80类的种类，运行的时候有打印警告说数据集路径没找到所以采用默认COCO种类，请仔细观察打印信息。
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/smalldet/ppyoloe_crn_l_80e_sliced_visdrone_640_025.yml#L2 根据这行去检查你的TestDataset配置，你的 anno_path 或 dataset_dir 路径现在应该是不存在的，把数据集下载放到对应目录下就行。https://bj.bcebos.com/v1/paddledet/data/smalldet/visdrone.zip 或者 https://bj.bcebos.com/v1/paddledet/data/smalldet/visdrone_sliced.zip 都可以，重点是TestDataset 配置正确。

**Comment by tianmaxingkong168** [comment]
> 你打印的是COCO 80类的种类，运行的时候有打印警告说数据集路径没找到所以采用默认COCO种类，请仔细观察打印信息。
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/smalldet/ppyoloe_crn_l_80e_sliced_visdrone_640_025.yml#L2 根据这行去检查你的TestDataset配置，你的 anno_path 或 dataset_dir 路径现在应该是不存在的，把数据集下载放到对应目录下就行。https://bj.bcebos.com/v1/paddledet/data/smalldet/visdrone.zip 或者 https://bj.bcebos.com/v1/paddledet/data/smalldet/visdrone_sliced.zip 都可以，重点是TestDataset 配置正确。

非常感谢，还要继续学习。
