### ISSUE TITLE
EfficientNMS_TRT

### ISSUE THREAD

**Issue by lgy2830** [PaddlePaddle/PaddleDetection#7579]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我的tensorrt版本是7.2的，可是我想使用EfficientNMS_TRT这个8.0才有的插件，怎么办？我的ppyoloe模型在导出onnx时，把nms部分去掉了，现在需要做一下后处理，看到了EfficientNMS_TRT这个插件可以用，但是需要更换tensorrt版本，我不想更换。

**Comment by wangxinxin08** [comment]
你可以自己写一下后处理，或者使用Paddle-TRT，或者使用[batchedNMSPlugin](https://github.com/NVIDIA/TensorRT/blob/release/7.2/plugin/batchedNMSPlugin)，类似问题可以自行解决
