### ISSUE TITLE
行人属性识别任务二次开发问题

### ISSUE THREAD

**Issue by balcklive** [PaddlePaddle/PaddleDetection#7582]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我按照https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/advanced_tutorials/customization/pphuman_attribute.md的说明对行人属性识别模型进行了二次开发。我主要做了如下工作：1.自己准备了数据集；2.**对模型的输出向量进行了删减（由原来的26个减少到了23个）**。
训练完成后得到PPLCNet_x1_0_person_attribute_infer文件夹，里面有inference.pdiparams，inference.pdiparams.info，inference.pdmodel三个文件。然后使用model = paddleclas.PaddleClas(inference_model_dir=".\PPLCNet_x1_0_person_attribute_infer")，加载了模型。使用result = model.predict(input_data = r"./20221013094531.jpg")输出结果。
但是得到的结果却是[{'class_ids': [12, 21, 2, 15, 16],
  'scores': [0.99986, 0.99329, 0.99195, 0.82017, 0.17123],
  'label_names': ['house finch, linnet, Carpodacus mexicanus',
   'kite',
   'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias',
   'robin, American robin, Turdus migratorius',
   'bulbul'],
  'filename': './20221013094531.jpg'}]
按道理我应该得到类似如下结果
[{'attributes': ['Female',
   'Age18-60',
   'Back',
   'Glasses: False',
   'Hat: False',
   'HoldObjectsInFront: False',
   'No bag',
   'Upper: LongSleeve',
   'Lower:  LongCoat Trousers',
   'Boots'],
  'output': [0,0, 0,  1,   0,   0,   0,   0,   0,   0,   1,   1,   0,   0,   1,   0,   0,   0,   0,   0,   1,   0,   1,   0,   0,   1],
  'filename': './20221013094531.jpg'}]
请问是哪里出了问题呢？ 如有需要我补充的请向我提出，谢谢

**Comment by balcklive** [comment]
这个没有人能回答一下吗？我使用python tools/infer.py -c ./ppcls/configs/PULC/person_attribute/PPLCNet_x1_0.yaml -o Global.pretrained_model=output/PPLCNet_x1_0/\epoch_161 -o Infer.infer_img=.\20221013094531.jpg这个命令进行预测结果又是正确的。
使用python tools/export_model.py -c ./ppcls/configs/PULC/person_attribute/PPLCNet_x1_0.yaml -o Global.pretrained_model=output/PPLCNet_x1_0/epoch_161 -o Global.save_inference_dir=deploy/models/PPLCNet_x1_0_person_attribute_infer导出后的模型又不行了，请问这是什么原因呢

**Comment by nuonuo0426** [comment]
您好，我也在做行人属性识别二次开发，我能问一下你：PaddleDetection 和训练代码PaddleClas的关系嘛，我看她们两个很多都重复了，她们应该属于两个代码项目，但是训练又要在PaddleClas中进行，数据又放在PaddleDetection中，不能只用PaddleClas进行训练嘛？
