### ISSUE TITLE
PP-YOLOE-SOD 支持c++部署吗

### ISSUE THREAD

**Issue by xmzhuxm** [PaddlePaddle/PaddleDetection#7589]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PP-YOLOE-SOD 支持c++部署吗

**Comment by lyuwenyu** [comment]
模型本身是支持cxx部署的，  但是如果用到切片相关的前后处理是不支持的

**Comment by xmzhuxm** [comment]
> 模型本身是支持cxx部署的， 但是如果用到切片相关的前后处理是不支持的
c++切片的前后处理后续会支持吗

**Comment by lyuwenyu** [comment]
短期内应该不会支持的
