### ISSUE TITLE
执行train.py进程被杀

### ISSUE THREAD

**Issue by Irvingao** [PaddlePaddle/PaddleDetection#759]
`2020-05-22 11:10:56,175-INFO: The 'num_classes'(number of classes) you set is 2, and 'with_background' in 'dataset' sets False.
So please note the actual number of categories is 2.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/clip.py:779: UserWarning: Caution! 'set_gradient_clip' is not recommended and may be deprecated in future! We recommend a new strategy: set 'grad_clip' when initializing the 'optimizer'. This method can reduce the mistakes, please refer to documention of 'optimizer'.
  warnings.warn("Caution! 'set_gradient_clip' is not recommended "
2020-05-22 11:10:58,501-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
W0522 11:10:59.047950   483 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0522 11:10:59.053092   483 device_context.cc:260] device: 0, cuDNN Version: 7.3.
W0522 11:10:59.153594   538 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0522 11:10:59.153664   538 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0522 11:10:59.153669   538 init.cc:221] The detail failure signal is:

W0522 11:10:59.153676   538 init.cc:224] *** Aborted at 1590117059 (unix time) try "date -d @1590117059" if you are using GNU date ***
W0522 11:10:59.156500   538 init.cc:224] PC: @                0x0 (unknown)
W0522 11:10:59.156975   538 init.cc:224] *** SIGSEGV (@0x1170) received by PID 483 (TID 0x7ff688ec5700) from PID 4464; stack trace: ***
W0522 11:10:59.158893   538 init.cc:224]     @     0x7ff6bee70390 (unknown)
W0522 11:10:59.159065   538 init.cc:224]     @     0x7ff6419441ff (unknown)
W0522 11:10:59.159189   538 init.cc:224]     @     0x7ff641aa18a4 (unknown)
W0522 11:10:59.159309   538 init.cc:224]     @     0x7ff641a3a578 (unknown)
W0522 11:10:59.160868   538 init.cc:224]     @     0x7ff6bee666ba start_thread
W0522 11:10:59.162434   538 init.cc:224]     @     0x7ff6beb9c41d clone
W0522 11:10:59.163992   538 init.cc:224]     @                0x0 (unknown)
Segmentation fault (core dumped)
`
我已经将yml和reader.yml中的with_background和num_classes参数分别设置为 fasle 和 2,use_default_label也设置为false。

**Comment by heavengate** [comment]
您好，请问下你跑的是哪个模型，Paddle和PaddleDetection的版本信息之类的麻烦发一下

**Comment by Irvingao** [comment]
YOLOv4_VOC






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kaipeng Deng"<notifications@github.com&gt;; 
发送时间: 2020年5月22日(星期五) 下午2:48
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 
抄送: "Kyrie"<1729854488@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] 执行train.py进程被杀 (#759)





 
您好，请问下你跑的是哪个模型，Paddle和PaddleDetection的版本信息之类的麻烦发一下

**Comment by heavengate** [comment]
嗯，操作系统，Paddle，PaddleDetection的版本信息麻烦发一下

**Comment by Irvingao** [comment]
AI studio,  paddle 1.8,  paddledetection最新的，我是pip 下载的

**Comment by qingqing01** [comment]
搜索其他issue，有的这种情况是TrainReader中的worker_num和bufsize导致。由于时间较久，关闭了此issue，有问题可以再建新的issue。
