### ISSUE TITLE
object365数据集，使用官方提供的权重进行测试，预测出来的框的位置是对的，但类别是错的

### ISSUE THREAD

**Issue by ash12358** [PaddlePaddle/PaddleDetection#760]
原因可能是我训练使用的train.json、val.json和你们的不一样，请问能提供一下你们的val.json，或者val.json里面categories这个字段的信息吗？

**Comment by qingqing01** [comment]
@ash12358  下载这个吧： https://paddlemodels.bj.bcebos.com/object_detection/object365_val.tar.gz  ，这个只提供了val.json，注意在TestReader里配置的时候，配置绝对路径。我们后续把train和val都提供下。

**Comment by ash12358** [comment]
好的，非常感谢
