### ISSUE TITLE
yaml.load(f, Loader=yaml.Loader) 问题

### ISSUE THREAD

**Issue by kevinuserdd** [PaddlePaddle/PaddleDetection#7606]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

yaml.load(f, Loader=yaml.Loader) 一直报错，需要更换为yaml.load(f, Loader=yaml.BaseLoader)才可以

**Comment by jerrywgz** [comment]
发下配置 和 报错信息吧
