### ISSUE TITLE
Could not write header for output file #0

### ISSUE THREAD

**Issue by Yuanhong-Zheng** [PaddlePaddle/PaddleDetection#7607]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

当我部署基于图像分类的行为识别（打电话行为识别）并用rtsp进行拉流再推流时，出现了以下的错误：
![错误](https://user-images.githubusercontent.com/117512740/211475518-9bfce75d-96ae-4e16-879c-d9005dde02ed.png)
这是我的参数：`python deploy/pipeline/pipeline.py --config deploy/pipeline/config/examples/infer_cfg_calling.yml --video_file=rtsp://192.168.0.105:8554/video --device=gpu --output_dir=F:\\temp2 --pushurl rtsp://192.168.0.105:8554`
去掉--output_dir也是一样的结果。
请问这是什么原因呢？谢谢！
当导出为video_t00_rtsp.mp4文件时，也是打不开的文件

**Comment by gg22mm** [comment]
这个问题是无解吗？

**Comment by gg22mm** [comment]
我也遇到这样的问题了：https://github.com/PaddlePaddle/PaddleDetection/issues/7964

**Comment by Yuanhong-Zheng** [comment]
@gg22mm 并不是无解，至少我后来跑通了，用OpenCV能进行拉流推理。但是很抱歉，我已经不记得当时是如何解决的了，但这应该不是大问题

**Comment by gg22mm** [comment]
> 我已经不记得当时是如何解决的了

不可能，如果直接用opcv我也是可以跑通的，  我之前做过这方面的。  但是在百度这里不行

**Comment by gg22mm** [comment]
我已经修复了这个问题，但出出现另外的问题
