### ISSUE TITLE
安装ppyoloe-r 旋转检测模型依赖项 ext_op 报错 

### ISSUE THREAD

**Issue by forword-1234** [PaddlePaddle/PaddleDetection#7608]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

测试旋转检测模型 安装依赖报错
版本： python3.8 cuda11.6 paddlepaddle-gpu2.4.1 
安装：cd ppdet/ext_op  python setup.py install
报错内容：
/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating ext_op.egg-info
writing ext_op.egg-info/PKG-INFO
writing dependency_links to ext_op.egg-info/dependency_links.txt
writing top-level names to ext_op.egg-info/top_level.txt
writing manifest file 'ext_op.egg-info/SOURCES.txt'
reading manifest file 'ext_op.egg-info/SOURCES.txt'
writing manifest file 'ext_op.egg-info/SOURCES.txt'
installing library code to build/ext_op/bdist.linux-x86_64/egg
running install_lib
running build_ext
Compiling user custom op, it will cost a few seconds.....
building 'ext_op' extension
gcc -pthread -B /home/kb/anaconda3/envs/paddle_env/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/kb/anaconda3/envs/paddle_env/include -fPIC -O2 -isystem /home/kb/anaconda3/envs/paddle_env/include -fPIC -I/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include -I/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/kb/anaconda3/envs/paddle_env/include/python3.8 -c /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc -o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/matched_rbox_iou.o -DPADDLE_WITH_CUDA -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -DPADDLE_WITH_CUDA -std=c++14
/usr/local/cuda-11.6/bin/nvcc -I/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include -I/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/kb/anaconda3/envs/paddle_env/include/python3.8 -c /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cu -o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/matched_rbox_iou.cu.o -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -ccbin cc -Xcompiler -fPIC --expt-relaxed-constexpr -DNVCC -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
gcc -pthread -B /home/kb/anaconda3/envs/paddle_env/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/kb/anaconda3/envs/paddle_env/include -fPIC -O2 -isystem /home/kb/anaconda3/envs/paddle_env/include -fPIC -I/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include -I/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/kb/anaconda3/envs/paddle_env/include/python3.8 -c /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/csrc/nms_rotated/nms_rotated.cc -o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/nms_rotated.o -DPADDLE_WITH_CUDA -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -DPADDLE_WITH_CUDA -std=c++14
/usr/local/cuda-11.6/bin/nvcc -I/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include -I/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/kb/anaconda3/envs/paddle_env/include/python3.8 -c /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/csrc/nms_rotated/nms_rotated.cu -o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/nms_rotated.cu.o -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -ccbin cc -Xcompiler -fPIC --expt-relaxed-constexpr -DNVCC -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
gcc -pthread -B /home/kb/anaconda3/envs/paddle_env/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/kb/anaconda3/envs/paddle_env/include -fPIC -O2 -isystem /home/kb/anaconda3/envs/paddle_env/include -fPIC -I/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include -I/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/kb/anaconda3/envs/paddle_env/include/python3.8 -c /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/csrc/rbox_iou/rbox_iou.cc -o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/rbox_iou.o -DPADDLE_WITH_CUDA -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -DPADDLE_WITH_CUDA -std=c++14
/usr/local/cuda-11.6/bin/nvcc -I/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include -I/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/kb/anaconda3/envs/paddle_env/include/python3.8 -c /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/csrc/rbox_iou/rbox_iou.cu -o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/rbox_iou.cu.o -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -ccbin cc -Xcompiler -fPIC --expt-relaxed-constexpr -DNVCC -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
g++ -pthread -B /home/kb/anaconda3/envs/paddle_env/compiler_compat -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/home/kb/anaconda3/envs/paddle_env/lib -Wl,-rpath-link,/home/kb/anaconda3/envs/paddle_env/lib -L/home/kb/anaconda3/envs/paddle_env/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/home/kb/anaconda3/envs/paddle_env/lib -Wl,-rpath-link,/home/kb/anaconda3/envs/paddle_env/lib -L/home/kb/anaconda3/envs/paddle_env/lib /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/matched_rbox_iou.o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/matched_rbox_iou.cu.o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/nms_rotated.o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/nms_rotated.cu.o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/rbox_iou.o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/rbox_iou.cu.o -L/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/libs -L/usr/local/cuda-11.6/lib64 -L/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid -Wl,-R/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/libs -Wl,-R/usr/local/cuda-11.6/lib64 -Wl,-R/home/kb/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid -o build/ext_op/lib.linux-x86_64-cpython-38/ext_op.so -l:libpaddle.so -lcudart
/home/kb/anaconda3/envs/paddle_env/lib/libcudart.so: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
error: command '/usr/bin/g++' failed with exit code 1

**Comment by sunfw2008** [comment]
gcc版本是多少，我系统默认4.2.0的，升级到8.2.0就可以了
