### ISSUE TITLE
Request for confirmation of spelling in callback module.

### ISSUE THREAD

**Issue by ryan-minato** [PaddlePaddle/PaddleDetection#7610]
I wanted to bring your attention to this code, which I believe contains some errors in spelling.
https://github.com/PaddlePaddle/PaddleDetection/blob/607c64ce7ca404bba50f0668fe6f801ef5574133/ppdet/engine/callbacks.py#L155

**Comment by wangxinxin08** [comment]
Thanks for pointing it out，we will fix this spelling errors or maybe you can contribute a pull request for us

**Comment by ryan-minato** [comment]
This issue appears to have been resolved in PR [#7614](https://github.com/PaddlePaddle/PaddleDetection/pull/7614/)

I will close this issue.
