### ISSUE TITLE
如何找出漏检、误检的目标所在图片?

### ISSUE THREAD

**Issue by gaohuayang** [PaddlePaddle/PaddleDetection#7611]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

数据集共有1w张图片，想找出所有漏检、误检物体所在图片，进而优化模型，我的想法如下：

1. eval的时候得到bbox.json文件
2. 设置score阈值筛选bbox.json里的结果
3. 将筛选后的bbox.json与真实标注比较

**我的疑问？**
1. 有没有简单点的方法？
2. bbox.json文件中的score怎么算的？
3. 怎么得到每类物体特定IoU下的AP，比如每一类的AP50、每一类的AP75

**Comment by gaohuayang** [comment]
3. 怎么得到每类物体特定IoU下的AP，比如每一类的AP50、每一类的AP75
可以修改ppdet/metrics/coco_utils.py第133行`precision = precisions[:, :, idx, 0, -1]`，eval时添加`--classwise`得到。
- `precision = precisions[0, :, idx, 0, -1]`为AP50
- `precision = precisions[9, :, idx, 0, -1]`为AP95
- `precision = precisions[10, :, idx, 0, -1]`IndexError: index 10 is out of bounds for axis 0 with size 10

**Comment by wangxinxin08** [comment]
1. 一般通过bbox.json与真实标注去比较，这是最直接简单的方法
2. score再bbox.json中有专门的字段
3. `--classwise`可以打印每类物体的IoU，如果报错，可以检查下是否类别正确设置
