### ISSUE TITLE
ppyoloe-r 旋转检测模型 安装依赖python ppdet/ext_op/setup.py install 报错

### ISSUE THREAD

**Issue by forword-1234** [PaddlePaddle/PaddleDetection#7613]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

测试paddledetection 旋转检测模型ppyoloe-r 安装依赖是报错：
环境：cuda 11.6  paddlepaddle 2.3.2 &2.4.1
运行：python ppdet/ext_op/setup.py install 
报错：
/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating ext_op.egg-info
writing ext_op.egg-info/PKG-INFO
writing dependency_links to ext_op.egg-info/dependency_links.txt
writing top-level names to ext_op.egg-info/top_level.txt
writing manifest file 'ext_op.egg-info/SOURCES.txt'
reading manifest file 'ext_op.egg-info/SOURCES.txt'
writing manifest file 'ext_op.egg-info/SOURCES.txt'
installing library code to build/ext_op/bdist.linux-x86_64/egg
running install_lib
running build_ext
Compiling user custom op, it will cost a few seconds.....
building 'ext_op' extension
gcc -pthread -B /home/kb/miniconda3/envs/paddle_env/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/kb/miniconda3/envs/paddle_env/include -fPIC -O2 -isystem /home/kb/miniconda3/envs/paddle_env/include -fPIC -I/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include -I/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/kb/miniconda3/envs/paddle_env/include/python3.8 -c /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cc -o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/matched_rbox_iou.o -DPADDLE_WITH_CUDA -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -DPADDLE_WITH_CUDA -std=c++14
/usr/local/cuda-11.6/bin/nvcc -I/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include -I/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/kb/miniconda3/envs/paddle_env/include/python3.8 -c /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cu -o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/matched_rbox_iou.cu.o -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -ccbin cc -Xcompiler -fPIC --expt-relaxed-constexpr -DNVCC -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
gcc -pthread -B /home/kb/miniconda3/envs/paddle_env/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/kb/miniconda3/envs/paddle_env/include -fPIC -O2 -isystem /home/kb/miniconda3/envs/paddle_env/include -fPIC -I/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include -I/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/kb/miniconda3/envs/paddle_env/include/python3.8 -c /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/csrc/nms_rotated/nms_rotated.cc -o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/nms_rotated.o -DPADDLE_WITH_CUDA -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -DPADDLE_WITH_CUDA -std=c++14
/usr/local/cuda-11.6/bin/nvcc -I/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include -I/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/kb/miniconda3/envs/paddle_env/include/python3.8 -c /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/csrc/nms_rotated/nms_rotated.cu -o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/nms_rotated.cu.o -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -ccbin cc -Xcompiler -fPIC --expt-relaxed-constexpr -DNVCC -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
gcc -pthread -B /home/kb/miniconda3/envs/paddle_env/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/kb/miniconda3/envs/paddle_env/include -fPIC -O2 -isystem /home/kb/miniconda3/envs/paddle_env/include -fPIC -I/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include -I/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/kb/miniconda3/envs/paddle_env/include/python3.8 -c /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/csrc/rbox_iou/rbox_iou.cc -o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/rbox_iou.o -DPADDLE_WITH_CUDA -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -DPADDLE_WITH_CUDA -std=c++14
/usr/local/cuda-11.6/bin/nvcc -I/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include -I/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/kb/miniconda3/envs/paddle_env/include/python3.8 -c /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/csrc/rbox_iou/rbox_iou.cu -o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/rbox_iou.cu.o -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -ccbin cc -Xcompiler -fPIC --expt-relaxed-constexpr -DNVCC -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
g++ -pthread -B /home/kb/miniconda3/envs/paddle_env/compiler_compat -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/home/kb/miniconda3/envs/paddle_env/lib -Wl,-rpath-link,/home/kb/miniconda3/envs/paddle_env/lib -L/home/kb/miniconda3/envs/paddle_env/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/home/kb/miniconda3/envs/paddle_env/lib -Wl,-rpath-link,/home/kb/miniconda3/envs/paddle_env/lib -L/home/kb/miniconda3/envs/paddle_env/lib /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/matched_rbox_iou.o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/matched_rbox_iou.cu.o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/nms_rotated.o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/nms_rotated.cu.o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/rbox_iou.o /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/rbox_iou.cu.o -L/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/libs -L/usr/local/cuda-11.6/lib64 -L/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid -Wl,-R/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/libs -Wl,-R/usr/local/cuda-11.6/lib64 -Wl,-R/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid -o build/ext_op/lib.linux-x86_64-cpython-38/ext_op.so -l:core_avx.so -lcudart
creating build/ext_op/bdist.linux-x86_64
creating build/ext_op/bdist.linux-x86_64/egg
copying build/ext_op/lib.linux-x86_64-cpython-38/rbox_iou.cu.o -> build/ext_op/bdist.linux-x86_64/egg
copying build/ext_op/lib.linux-x86_64-cpython-38/version.txt -> build/ext_op/bdist.linux-x86_64/egg
copying build/ext_op/lib.linux-x86_64-cpython-38/ext_op.so -> build/ext_op/bdist.linux-x86_64/egg
copying build/ext_op/lib.linux-x86_64-cpython-38/matched_rbox_iou.cu.o -> build/ext_op/bdist.linux-x86_64/egg
copying build/ext_op/lib.linux-x86_64-cpython-38/rbox_iou.o -> build/ext_op/bdist.linux-x86_64/egg
copying build/ext_op/lib.linux-x86_64-cpython-38/nms_rotated.cu.o -> build/ext_op/bdist.linux-x86_64/egg
copying build/ext_op/lib.linux-x86_64-cpython-38/matched_rbox_iou.o -> build/ext_op/bdist.linux-x86_64/egg
copying build/ext_op/lib.linux-x86_64-cpython-38/nms_rotated.o -> build/ext_op/bdist.linux-x86_64/egg
creating stub loader for ext_op.so
Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    setup(name='ext_op', ext_modules=get_extensions())
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/utils/cpp_extension/cpp_extension.py", line 204, in setup
    setuptools.setup(**attr)
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 178, in run
    write_stub(os.path.basename(ext_name), pyfile)
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 179, in custom_write_stub
    new_custom_ops = load_op_meta_info_and_register_op(so_path)
  File "/home/kb/miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 134, in load_op_meta_info_and_register_op
    core.load_op_meta_info_and_register_op(lib_filename)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (/data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/ext_op.so) that Paddle depends on is not configured correctly. (error code is /data/code/PaddleDetection_lastet/PaddleDetection-develop/ppdet/ext_op/build/ext_op/lib.linux-x86_64-cpython-38/ext_op.so: failed to map segment from shared object)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/phi/backends/dynload/dynamic_loader.cc:303)

**Comment by wangxinxin08** [comment]
看具体报错信息，显示cuda和cudnn的版本问题，可能是PaddlelPaddle的cuda和cudnn版本与你环境中的版本不符，或者cuda/cudnn路径没有正确设置

**Comment by forword-1234** [comment]
1.能帮我看一下 这路径有问题吗
export PATH=/usr/local/cuda-11.6/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-11.6/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export CUDA_HOME=/usr/local/cuda-11.6${CUDA_HOME:+:${CUDA_HOME}}

2. PaddlePaddle cuda cudnn 版本都是按照匹配的版本安装的 cuda11.6 cudnn8.4.0 PaddlePaddle2.3.2
