### ISSUE TITLE
请问目前对faster rcnn的tensorrt的支持怎么样？

### ISSUE THREAD

**Issue by hp-cuiwb** [PaddlePaddle/PaddleDetection#762]
如题

**Comment by heavengate** [comment]
PaddleDetection里面提供了的python和c++部署方案是支持tensorrt的，可以参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/deploy/python
https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/deploy/cpp

另外从官网安装的whl包，默认不包含TensorRT。如果需要使用TensorRT，得编译下paddle，参考： https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/performance_improving/inference_improving/paddle_tensorrt_infer.html#id2 。 Paddle后续发布的whl包会包含TensorRT。
