### ISSUE TITLE
import paddle失败，但是明明已经安装了

### ISSUE THREAD

**Issue by qq-tt** [PaddlePaddle/PaddleDetection#7621]
请问大佬们，我明明已经安装paddle的gpu版本了，为什么import失败？如图：
![image](https://user-images.githubusercontent.com/32315802/212588735-d273caa0-fb3f-4eb4-ab88-a6b310fac4f2.png)

**Comment by jerrywgz** [comment]
确认下python路径和pip路径对应的python是否是一致的
