### ISSUE TITLE
paddle2onnx可以修改onnx的输出的shape吗

### ISSUE THREAD

**Issue by Captain-LSY** [PaddlePaddle/PaddleDetection#7628]
### 问题描述 Please describe your issue

![企业微信截图_16739428797215](https://user-images.githubusercontent.com/122439846/212843568-f1bd37ff-e3e7-423b-acba-7d15ebc4cb05.png)
想把这个输出的shape 3840, 6改为动态shape -1, 6

**Comment by lyuwenyu** [comment]
1. 这个和你的input有关系啊   得在导出的时候设置动态shape  
<img width="712" alt="image" src="https://user-images.githubusercontent.com/17582080/213672175-dde5dd1f-0e01-4d93-9c61-aec50cc7c32a.png">

2. 或者看你接下来用什么推理引擎  在推理端有的应该也能改  比如onnxruntime
