### ISSUE TITLE
改进PP-YOLOE+的S型号模型，训练效果不佳

### ISSUE THREAD

**Issue by Dekadenc** [PaddlePaddle/PaddleDetection#7638]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

（1）改进点：
1.在主干网络和检测颈之间添加注意力机制
2.将边界框回归损失函数由GIOU->SIOU
（2）训练参数设置：
![image](https://user-images.githubusercontent.com/102035987/215232047-fc56ebfe-3a62-4491-bd7a-d5a92684e2c3.png)
加载了obj预训练权重
（4）训练效果：
![image](https://user-images.githubusercontent.com/102035987/215232114-5257355a-a808-499c-865c-836b9a9ee610.png)
![image](https://user-images.githubusercontent.com/102035987/215232123-7b6857c3-f934-4d8a-98c4-bb4af1cabe49.png)
（5）
疑问1：训练效果C相较于B略有下降，正常吗
![image](https://user-images.githubusercontent.com/102035987/215232447-b3f88c5c-55ee-463d-a151-a63edfe1517f.png)
疑问2：map上升后在最后的epoch又略有下贱，是过拟合的问题吗
疑问3；为什么loss的下降先骤升后下降，但是看现在的曲线，是否因为还未收敛，该如何解决
疑问4：每次更改网络结构后，是否需要加载官方预训练权重进行训练

**Comment by nemonameless** [comment]
1. siou未必通用，以及先确保你的实现和原论文没有差异再训
2. 是的，波动也是正常的。base mAP太高说明数据集太简单，有些trick结论未必适用
3. 正常，可以自己再加大epoch数看
4. 不改动结构的情况下，加载官方预训练权重fintune会更快更高。改了结构，预训练对不上了效果就会削弱

**Comment by Dekadenc** [comment]
> 1. siou未必通用，以及先确保你的实现和原论文没有差异再训
> 2. 是的，波动也是正常的。base mAP太高说明数据集太简单，有些trick结论未必适用
> 3. 正常，可以自己再加大epoch数看
> 4. 不改动结构的情况下，加载官方预训练权重fintune会更快更高。改了结构，预训练对不上了效果就会削弱

1.实现用的是咱们官方提供的，单独添加的话有0.6个点的提升，C是在注意力的基础上添加的[https://github.com/PaddlePaddle/PaddleDetection/blob/6f384cb3043938943aa4ae51931e7d924f380f42/ppdet/modeling/losses/iou_loss.py#L215](url)
3.是在原有epoch上修改配置文件断点训练  还是加载最后一轮的权重重新训练（调小学习率？）
4.那这种情况多训练几轮会可能有所提升吗，有什么解决措施

**Comment by nemonameless** [comment]
1.从你的实验看 siou+注意力 并不是1+1>2，也属于正常现象
3.cosine lr策略只能从头重训
4.多训epoch可能可以提升的

**Comment by Dekadenc** [comment]
> 1.从你的实验看 siou+注意力 并不是1+1>2，也属于正常现象 3.cosine lr策略只能从头重训 4.多训epoch可能可以提升的

明白了，感谢您的回复~
