### ISSUE TITLE
视频预测报错

### ISSUE THREAD

**Issue by wd923923** [PaddlePaddle/PaddleDetection#765]
之前可以跑，突然就不行了，求助

```
detect frame:1
Traceback (most recent call last):
  File "deploy/python/infer.py", line 556, in <module>
    predict_video()
  File "deploy/python/infer.py", line 516, in predict_video
    results = detector.predict(frame, FLAGS.threshold)
  File "deploy/python/infer.py", line 482, in predict
    np_boxes, np_masks, im_info, threshold=threshold)
  File "deploy/python/infer.py", line 435, in postprocess
    expect_boxes = np_boxes[:, 1] > threshold
IndexError: index 1 is out of bounds for axis 1 with size 1
```

**Comment by qingqing01** [comment]
@wd923923 这里可能的错误是  `deploy/python/infer.py`的输出`np_boxes`是空的，代表这张图片没有检测到框。可以依据shape判断下，

https://github.com/PaddlePaddle/PaddleDetection/blob/095b03d21befee5d6b0239ce1e13707895ea75e9/deploy/python/infer.py#L440

如果  np_boxes的size小于6，就跳过，返回的`results`为空，

https://github.com/PaddlePaddle/PaddleDetection/blob/095b03d21befee5d6b0239ce1e13707895ea75e9/deploy/python/infer.py#L535

这里可视化时时，就直接用原图frame。

我们后续改进下。

**Comment by pomeloyou** [comment]
我也遇到了类似的问题
```
detect frame:0
class_id:0, confidence:0.25,left_top:[684.87,58.58], right_bottom:[1131.76,517.02]
class_id:0, confidence:0.22,left_top:[280.86,60.52], right_bottom:[589.30,352.29]
class_id:1, confidence:0.22,left_top:[684.87,58.58], right_bottom:[1131.76,517.02]
Traceback (most recent call last):
  File "deploy/python/infer.py", line 619, in <module>
    predict_video()
  File "deploy/python/infer.py", line 544, in predict_video
    mask_resolution=detector.config.mask_resolution)
  File "D:\code\PaddleDetection\deploy\python\visualize.py", line 48, in visualize_box_mask
    im = draw_box(im, results['boxes'], labels)
  File "D:\code\PaddleDetection\deploy\python\visualize.py", line 172, in draw_box
    clsid2color[clsid] = color_list[clsid]
IndexError: list index out of range
```

**Comment by pomeloyou** [comment]
> @wd923923 这里可能的错误是 `deploy/python/infer.py`的输出`np_boxes`是空的，代表这张图片没有检测到框。可以依据shape判断下，
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/095b03d21befee5d6b0239ce1e13707895ea75e9/deploy/python/infer.py#L440
> 
> 如果 np_boxes的size小于6，就跳过，返回的`results`为空，
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/095b03d21befee5d6b0239ce1e13707895ea75e9/deploy/python/infer.py#L535
> 
> 这里可视化时时，就直接用原图frame。
> 
> 我们后续改进下。

想要它跳过该帧还需要对代码进行改动吗，是否像#791那样改动呢

**Comment by Channingss** [comment]
PR#791 fix这个bug
