### ISSUE TITLE
训练时batchsize，设置为不是8的倍数是否可以？

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/PaddleDetection#7657]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我训练时，batchsize设置为16时，显存不够。设置为8，显存还富余点。所以我想问，设置为10或12这样的不是8的倍数，是否可以，会有啥影响不？

**Comment by nemonameless** [comment]
可以
