### ISSUE TITLE
i want to know pretrain_weights, det_weights  in bytetrack_yolox

### ISSUE THREAD

**Issue by moonnyeon** [PaddlePaddle/PaddleDetection#7662]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

I'm not sure what the difference is between pretrain_weights and det_weights in bytetrack_yolo.yml.

What I understand from bytetrack_yolo.yml is that as pretrain_weight does an update that increases yolox, what does det_weights do?

Architecture: Bytetrack
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/yolox_x_300e_coco.pdparams
Bytetrack:
    Detector: YOLOX
    reid: none
    Tracker: JDE Tracker
det_weights: https://bj.bcebos.com/v1/paddledet/models/mot/yolox_x_24e_800x1440_mix_det.pdparams
reid_weights: none

**Comment by nemonameless** [comment]
It is to load the trained weight with your mot dataset.  Bytetrack does not need reid_weights, so it's weight is just the weight of the detector yolox.
See   
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/tools/eval_mot.py#L84
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/tools/infer_mot.py#L94

**Comment by moonnyeon** [comment]
did you mean 
pretrain_weight --- > trained weight in my mot dataset for yolox?
reid_weight ------> bytetrack don't need !
det_weights -----> trained weight in my mot dataset for yolox?

sorry but I'm not sure what the difference is between "pretrain_weights" and "det_weights"
why did you call twice weight ,,

**Comment by nemonameless** [comment]
pretrain_weight is the weight trained by ImageNet or COCO, which is used for fast convergence and accuracy improvement for your mot dataset

**Comment by moonnyeon** [comment]
thank you bro !!
