### ISSUE TITLE
本人小白一枚，训练自己的数据集时，报错，还望大佬解答

### ISSUE THREAD

**Issue by chnejing88** [PaddlePaddle/PaddleDetection#7670]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

训练TT100K数据集时（已经将TT100K转成coco格式），报错如下：
![QQ图片20230201115847](https://user-images.githubusercontent.com/95913865/215942725-6d00e5dd-20f6-4b34-bab7-41d81de5c913.png)

**Comment by wangxinxin08** [comment]
报错信息系那时数据类型不支持，可以检查下下你的转换的数据集中那些数据不满足数据类型的要求，另外，提问最好贴一下PaddlePaddle和PaddleDetection的版本
