### ISSUE TITLE
coco数据训练到最后一个step_id时崩溃

### ISSUE THREAD

**Issue by jjqcat** [PaddlePaddle/PaddleDetection#7672]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

`       for epoch_id in range(self.start_epoch, self.cfg.epoch):
            self.status['mode'] = 'train'
            self.status['epoch_id'] = epoch_id
            self._compose_callback.on_epoch_begin(self.status)
            self.loader.dataset.set_epoch(epoch_id)
            model.train()
            iter_tic = time.time()
            for step_id, data in enumerate(self.loader):
                self.status['data_time'].update(time.time() - iter_tic)
                self.status['step_id'] = step_id
                profiler.add_profiler_step(profiler_options)
                self._compose_callback.on_step_begin(self.status)
                data['epoch_id'] = epoch_id
`
02/01 16:40:44] ppdet.engine INFO: Epoch: [0] [ 0/64] learning_rate: 0.000000 ...
当step_id执行完64时，程序奔溃在enumerate(self.loader)函数，进程退出
Process finished with exit code -1073741819 (0xC0000005)

### 复现环境 Environment

Windows
PaddlePaddle: 2.2.2
PaddleDetection: 2.4
CUDA: 10.2
CUDNN: 7.6
PyCharm: 2019.3.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
现有信息看不出程序报错的原因，可以先升级下PaddlePaddle版本和PaddleDetection版本是下
