### ISSUE TITLE
ValueError on slice_predict()

### ISSUE THREAD

**Issue by yuvalgrossman** [PaddlePaddle/PaddleDetection#7673]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference

### Bug描述 Describe the Bug

BUG: fails when trying to infer model to image with --infer_slice

Traceback (most recent call last):
  File "tools/infer.py", line 236, in <module>
    main()
  File "tools/infer.py", line 232, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 170, in run
    trainer.slice_predict(
  File "/home/yuval/Projects/PaddleDetection-develop/ppdet/engine/trainer.py", line 835, in slice_predict
    outs['bbox'][:, 2:4] = outs['bbox'][:, 2:4] + shift_amount.numpy()
ValueError: operands could not be broadcast together with shapes (12,2) (2,2)

SHELL: 
python tools/infer.py -c configs/rotate/ppyoloe_r/ppyoloe_r_crn_x_3x_dota_ms.yml -o use_gpu=false weights=/media/shared_weights/detection/ppyoloe_r_crn_x_3x_dota_ms.pdparams --infer_img=/Data/object_detection/img.bmp --output_dir ~/Outputs/object_detection --draw_threshold 0.2 --slice_infer

### 复现环境 Environment

- OS: Linux
- PaddlePaddle: 2.2.2
- PaddleDetection: Develop
- Python: 3.7 & 3.8

### Bug描述确认 Bug description confirmation

- [x] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [x] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
ppyoloe_r 等旋转框不支持slice_infer，slice_infer只适用于普通水平框
