### ISSUE TITLE
缺少 PaddleDetection/deploy/lite/src/main.cc 引用的头文件#include "json/json.h"

### ISSUE THREAD

**Issue by niuhaitaofeilong** [PaddlePaddle/PaddleDetection#7675]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

缺少 PaddleDetection/deploy/lite/src/main.cc 引用的头文件#include "json/json.h"，可否提供一下

**Comment by lyuwenyu** [comment]
linux机器下查看一下`usr/include/json.h` 
没有的话安装一下就行
`libjson-c-dev`或者`libjsoncpp-dev`
