### ISSUE TITLE
对于tinypose疑问，转出来的模型onnx模型存在疑问？

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleDetection#7678]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

当转化为onnx，pose关键点似乎出来的数据存在部分问题，与常规的onnx似乎存在区别，后处理解析出来的tensor点和原始的对不上。

**Comment by lyuwenyu** [comment]
问题能具体点嘛

**Comment by chen-del** [comment]
我使用类型对比吧，主要是mnn转化出来的时候，tensor点似乎对不上了点，我是按照正常方式转的。
![image](https://user-images.githubusercontent.com/58769772/216299299-ccea7fcb-5ca7-41a8-8c16-9ef35567c8a3.png)
图一是我这边使用paddle转的，图二是你们这边提供的。但是实际推理画关键点的时候输出点不对了，是如下结果
![image](https://user-images.githubusercontent.com/58769772/216299638-3318e384-a378-43a2-a2f2-a25b9a1ac859.png)
但是你们提供的mnn推理的结果又是正常的，如图
![image](https://user-images.githubusercontent.com/58769772/216300075-d099ed09-0f1e-41c1-8fb1-dad25fcff989.png)
，所以能帮忙排查一下是不是这个模型转化存在问题，谢谢！我提供一下模型文件和转化命令

[weight.zip](https://github.com/PaddlePaddle/PaddleDetection/files/10567908/weight.zip)

**Comment by LetmeSay** [comment]
麻烦问下TinyPose模型预测返回的[?,17,64,48]的64和48分别表示的是什么？
