### ISSUE TITLE
在paddleDetection中使用slim

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#768]
from paddleslim.quant import quant_aware, convert
ImportError: cannot import name 'quant_aware'
安装了paddleslim也报这个错，paddle是1.7版本slim是1.1.1。请问怎么解决

**Comment by slf12** [comment]
> from paddleslim.quant import quant_aware, convert
> ImportError: cannot import name 'quant_aware'
> 安装了paddleslim也报这个错，paddle是1.7版本slim是1.1.1。请问怎么解决

请将paddle升级到1.8版本
