### ISSUE TITLE
(paddletrt) question outofmemory infer.py

### ISSUE THREAD

**Issue by moonnyeon** [PaddlePaddle/PaddleDetection#7686]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

My current environment is cudnn 8.2.0, cuda 11.2, tensorrt 8.0.0.3

I entered the following command line:
CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/fairmot_dla34_30e_1088x608 --image_dir=/test_data/image1 --device=GPU --run_mode=trt_fp32 --run_benchmark=True

It seems my problem is out of  tmp_01159 and memory , can you tell me which line to modify?

-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: -1
combine_method: nms
cpu_threads: 1
device: GPU
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: /test_data/image1
image_file: None
match_metric: ios
match_threshold: 0.6
model_dir: output_inference/fairmot_dla34_30e_1088x608
output_dir: output
overlap_ratio: [0.25, 0.25]
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: True
run_mode: trt_fp32
save_images: True
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
slice_infer: False
slice_size: [640, 640]
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_coco_category: False
use_dark: True
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: FairMOT
Transform Order: 
--transform op: LetterBoxResize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
Enable TensorRT is: True
E0206 15:04:03.887042 10029 helper.h:114] [virtualMemoryBuffer.cpp::resizePhysical::61] Error Code 2: OutOfMemory (no further information)
E0206 15:04:03.887113 10029 helper.h:114] [virtualMemoryBuffer.cpp::resizePhysical::61] Error Code 2: OutOfMemory (no further information)
E0206 15:04:03.887702 10029 helper.h:114] Requested amount of GPU memory (34359738368 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
E0206 15:04:03.896977 10029 helper.h:114] [virtualMemoryBuffer.cpp::resizePhysical::61] Error Code 2: OutOfMemory (no further information)
E0206 15:04:03.897045 10029 helper.h:114] [virtualMemoryBuffer.cpp::resizePhysical::61] Error Code 2: OutOfMemory (no further information)
E0206 15:04:03.897634 10029 helper.h:114] Requested amount of GPU memory (34359738368 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
E0206 15:04:03.906966 10029 helper.h:114] [virtualMemoryBuffer.cpp::resizePhysical::61] Error Code 2: OutOfMemory (no further information)
E0206 15:04:03.907017 10029 helper.h:114] [virtualMemoryBuffer.cpp::resizePhysical::61] Error Code 2: OutOfMemory (no further information)
E0206 15:04:03.907989 10029 helper.h:114] Requested amount of GPU memory (34359738368 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
E0206 15:04:05.906121 10029 helper.h:114] 4: Output tensor tmp_01159 of type Float produced from output of incompatible type Bool
E0206 15:04:05.906169 10029 helper.h:114] 4: [network.cpp::validate::2534] Error Code 4: Internal Error (Could not compute dimensions for tmp_01159, because the network is not valid.)
E0206 15:04:05.906177 10029 helper.h:114] 2: [builder.cpp::buildSerializedNetwork::399] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
12  paddle::inference::tensorrt::TensorRTEngine::FreezeNetwork()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1675663445 (unix time) try "date -d @1675663445" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x8) received by PID 10029 (TID 0x7fa865f0d4c0) from PID 8 ***]

Segmentation fault (core dumped)

**Comment by moonnyeon** [comment]
When I run the code, sometimes the progress can be seen, but when I enter the same command line again, it dies immediately with an error, and the following error appears when an error occurs:
![image](https://user-images.githubusercontent.com/87063668/216884165-fa26a41b-1647-4597-8c44-3671f13528bf.png)

**Comment by moonnyeon** [comment]
E0206 14:44:10.730624  6682 helper.h:114] 4: Output tensor tmp_01159 of type Float produced from output of incompatible type Bool
E0206 14:44:10.730723  6682 helper.h:114] 4: [network.cpp::validate::2534] Error Code 4: Internal Error (Could not compute dimensions for tmp_01159, because the network is not valid.)
E0206 14:44:10.730733  6682 helper.h:114] 2: [builder.cpp::buildSerializedNetwork::399] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.)


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
12  paddle::inference::tensorrt::TensorRTEngine::FreezeNetwork()

**Comment by nemonameless** [comment]
If you want to infer and get tracking results, you should remove `--run_benchmark=True`, which only used to test the speed.
About outofmemory, try to use fairmot_dla34_30e_576x320.

**Comment by moonnyeon** [comment]
"Thank you for the response. However, the "out of memory" error message is also a problem, but why does my code always stop at tmp_01159? It keeps stopping there even if I run it again. Can you explain the meaning of the error "Output tensor tmp_01159 of type Float produced from output of incompatible type Bool"? "

CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/fairmot_dla34_30e_864x480/ --device=GPU --run_mode=trt_fp32 --enable_mkldnn=True --run_benchmark=True 
![image](https://user-images.githubusercontent.com/87063668/216911917-cb219f75-6fad-4346-a8cb-1f191def4733.png)
