### ISSUE TITLE
模型动态转静态后，梯度怎么打印？

### ISSUE THREAD

**Issue by zhoushuang66** [PaddlePaddle/PaddleDetection#7689]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我尝试打印梯度的model是configs/ssd/ssdlite_mobilenet_v1_300_coco.yml  ,tag：v2.4.0版本

**Comment by jerrywgz** [comment]
可以使用register_hook来对梯度进行操作，打印的话可以参考https://github.com/jerrywgz/PaddleDetection/blob/debug_gfl/ppdet/modeling/backbones/resnet.py#L598

**Comment by zhoushuang66** [comment]
谢谢回复，动态图梯度可以使用上述方法，动转静态梯度无法打印。

**Comment by Aurelius84** [comment]
有两种情况：
对于param类型，直接在loss.backward() 后，直接从net中取param用print(param.grad)即可
对于普通tensor：
```python
class Net(Layer):
    # .....
   @to_static
    def forward(self, x):
        y = self.fc(x)
        y = paddle.static.Print(y)  # <--- 用这种方式
        out = self.relu(y)
```
Print接口用法可以参考:https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/Print_cn.html#print
