### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by DragonLYL0718** [PaddlePaddle/PaddleDetection#769]
2020-05-24 00:13:24,369-INFO: Test iter 0
2020-05-24 00:13:41,353-INFO: Test iter 100
2020-05-24 00:13:49,655-INFO: Test finish iter 157
2020-05-24 00:13:49,655-INFO: Total number of images: 1253, inference time: 47.22646347602829 fps.
2020-05-24 00:13:49,655-INFO: Start evaluate...
Traceback (most recent call last):
  File "PaddleDetection/tools/train.py", line 366, in <module>
    main()
  File "PaddleDetection/tools/train.py", line 288, in main
    cfg['EvalReader']['dataset'])
  File "/home/aistudio/PaddleDetection/ppdet/utils/eval_utils.py", line 236, in eval_results
    map_type=map_type)
  File "/home/aistudio/PaddleDetection/ppdet/utils/voc_eval.py", line 71, in bbox_eval
    gt_boxes = t['gt_bbox'][0]
KeyError: 'gt_bbox'
terminate called without an active exception
W0524 00:13:50.482211  5568 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0524 00:13:50.482247  5568 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0524 00:13:50.482259  5568 init.cc:214] The detail failure signal is:

W0524 00:13:50.482267  5568 init.cc:217] *** Aborted at 1590250430 (unix time) try "date -d @1590250430" if you are using GNU date ***
terminate called recursively
之前用的别人notebook上面的旧版的paddledetection上可以运行，自己重新下了一个训练了一轮就被杀进程了

**Comment by DragonLYL0718** [comment]
Traceback (most recent call last):
  File "PaddleDetection/tools/train.py", line 366, in <module>
    main()
  File "PaddleDetection/tools/train.py", line 288, in main
    cfg['EvalReader']['dataset'])
  File "/home/aistudio/PaddleDetection/ppdet/utils/eval_utils.py", line 236, in eval_results
    map_type=map_type)
  File "/home/aistudio/PaddleDetection/ppdet/utils/voc_eval.py", line 71, in bbox_eval
    gt_boxes = t['gt_bbox'][0]
KeyError: 'gt_bbox'
terminate called without an active exception
W0524 00:36:21.401295  6674 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0524 00:36:21.401340  6674 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0524 00:36:21.401345  6674 init.cc:214] The detail failure signal is:

W0524 00:36:21.401362  6674 init.cc:217] *** Aborted at 1590251781 (unix time) try "date -d @1590251781" if you are using GNU date ***
W0524 00:36:21.402976  6674 init.cc:217] PC: @                0x0 (unknown)
W0524 00:36:21.403120  6674 init.cc:217] *** SIGABRT (@0x3e8000018fc) received by PID 6396 (TID 0x7f58147fc700) from PID 6396; stack trace: ***
W0524 00:36:21.404264  6674 init.cc:217]     @     0x7f5c07d42390 (unknown)
W0524 00:36:21.405339  6674 init.cc:217]     @     0x7f5c0799c428 gsignal
W0524 00:36:21.406406  6674 init.cc:217]     @     0x7f5c0799e02a abort
W0524 00:36:21.407125  6674 init.cc:217]     @     0x7f5bc875484a __gnu_cxx::__verbose_terminate_handler()
W0524 00:36:21.407709  6674 init.cc:217]     @     0x7f5bc8752f47 __cxxabiv1::__terminate()
W0524 00:36:21.408370  6674 init.cc:217]     @     0x7f5bc8752f7d std::terminate()
W0524 00:36:21.408965  6674 init.cc:217]     @     0x7f5bc8752c5a __gxx_personality_v0
W0524 00:36:21.409518  6674 init.cc:217]     @     0x7f5bc8a45b97 _Unwind_ForcedUnwind_Phase2
W0524 00:36:21.410074  6674 init.cc:217]     @     0x7f5bc8a45e7d _Unwind_ForcedUnwind
W0524 00:36:21.411177  6674 init.cc:217]     @     0x7f5c07d41070 __GI___pthread_unwind
W0524 00:36:21.412218  6674 init.cc:217]     @     0x7f5c07d39845 __pthread_exit
W0524 00:36:21.412483  6674 init.cc:217]     @     0x55a406f15e59 PyThread_exit_thread
W0524 00:36:21.412562  6674 init.cc:217]     @     0x55a406d9bc17 PyEval_RestoreThread.cold.798
W0524 00:36:21.413426  6674 init.cc:217]     @     0x7f5bfa77e58d (unknown)
W0524 00:36:21.414249  6674 init.cc:217]     @     0x7f5bfa8f52a4 (unknown)
W0524 00:36:21.414525  6674 init.cc:217]     @     0x55a406e97744 _PyMethodDef_RawFastCallKeywords
W0524 00:36:21.414753  6674 init.cc:217]     @     0x55a406e97861 _PyCFunction_FastCallKeywords
W0524 00:36:21.414976  6674 init.cc:217]     @     0x55a406f032bd _PyEval_EvalFrameDefault
W0524 00:36:21.415182  6674 init.cc:217]     @     0x55a406e47539 _PyEval_EvalCodeWithName
W0524 00:36:21.415405  6674 init.cc:217]     @     0x55a406e48635 _PyFunction_FastCallDict
W0524 00:36:21.415637  6674 init.cc:217]     @     0x55a406e66e53 _PyObject_Call_Prepend
W0524 00:36:21.415881  6674 init.cc:217]     @     0x55a406e9ea3a slot_tp_call
W0524 00:36:21.416111  6674 init.cc:217]     @     0x55a406e9f8fb _PyObject_FastCallKeywords
W0524 00:36:21.416345  6674 init.cc:217]     @     0x55a406f02e86 _PyEval_EvalFrameDefault
W0524 00:36:21.416553  6674 init.cc:217]     @     0x55a406e4856b _PyFunction_FastCallDict
W0524 00:36:21.416752  6674 init.cc:217]     @     0x55a406e66e53 _PyObject_Call_Prepend
W0524 00:36:21.416860  6674 init.cc:217]     @     0x55a406e9ea3a slot_tp_call
W0524 00:36:21.417062  6674 init.cc:217]     @     0x55a406e9f8fb _PyObject_FastCallKeywords
W0524 00:36:21.417280  6674 init.cc:217]     @     0x55a406f036e8 _PyEval_EvalFrameDefault
W0524 00:36:21.417493  6674 init.cc:217]     @     0x55a406e47539 _PyEval_EvalCodeWithName
W0524 00:36:21.417716  6674 init.cc:217]     @     0x55a406e48635 _PyFunction_FastCallDict
W0524 00:36:21.417920  6674 init.cc:217]     @     0x55a406e66e53 _PyObject_Call_Prepend
Aborted (core dumped)

**Comment by qingqing01** [comment]
@DragonLYL0718  说明下运行环境、模型、paddle版本吧，我们看下

**Comment by DragonLYL0718** [comment]
![image](https://user-images.githubusercontent.com/57632904/82779210-2a420f00-9e86-11ea-937a-1bd0bdf6edfa.png)
architecture: YOLOv3
use_gpu: true
max_iters: 30000
log_smooth_window: 20
save_dir: output
#log_iter: 50
snapshot_iter: 1000
metric: VOC
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/ResNet50_vd_obj365_pretrained.tar 
weights: output/head/model_final
num_classes: 1
use_fine_grained_loss: false

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head

ResNet:
  norm_type: sync_bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 50
  feature_maps: [3, 4, 5]
  variant: d
  dcn_v2_stages: [5]

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  nms:
    background_label: -1
    keep_top_k: 500
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01
YOLOv3Loss:
  batch_size: 8
  ignore_thresh: 0.7
  label_smooth: false

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 15000
    - 25000
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'yolov3_reader.yml'

TrainReader:
  dataset:
    !VOCDataSet
    dataset_dir: data/head
    anno_path: ImageSets/all.txt
    use_default_label: false
    with_background: false


EvalReader:
  dataset:
    !VOCDataSet
    dataset_dir: data/head
    anno_path: ImageSets/all.txt
    use_default_label: false
    with_background: false


TestReader:
  dataset:
    !ImageFolder
    anno_path: data/head/label_list.txt
    use_default_label: false
    with_background: false
就是在开源项目里面找到的一个人流识别的模型，之前跑过是可以运行的，重新克隆了paddle detection之后就跑不了了

**Comment by qingqing01** [comment]
@DragonLYL0718 你用的是VOC的评估方式吗？ 如果是`EvalReader` 中`fields`字段配置，参考： https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/configs/yolov3_mobilenet_v1_voc.yml#L79  和 COCO不同，`READER: 'yolov3_reader.yml'` 默认是COCO的方式。

**Comment by DragonLYL0718** [comment]
多谢，已经解决了之前没注意到那里默认的是COCO的方式
