### ISSUE TITLE
Picodet 用Paddle Lite V2.11 部署在 windows 端报错：kernel for 'matmul_v2' is not supported by Paddle-Lite.

### ISSUE THREAD

**Issue by niuhaitaofeilong** [PaddlePaddle/PaddleDetection#7690]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Picodet 用Paddle Lite V2.11 部署在 windows 端报错：kernel for 'matmul_v2' is not supported by Paddle-Lite.

**Comment by hong19860320** [comment]
是否可以尝试 Paddle Lite v2.12，然后把推理模型发上来，我复现一下。
