### ISSUE TITLE
Anchor_free使用问题

### ISSUE THREAD

**Issue by super3kl** [PaddlePaddle/PaddleDetection#770]
服务区 Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-47-generic x86_64)
0.3版本的paddledetection
configs选择的是cornernet_squeeze_r50_vd_fpn 
paddle-gpu 1.8.1

Can not find library: /home/data/aistudio/PaddleDetection/ppdet/ext_op/src/cornerpool_lib.so. The process maybe hang. Please try to add the lib path to LD_LIBRARY_PATH.
2020-05-24 15:13:21,176-ERROR: cornerpool_lib not found, compile in ppdet/ext_op at first
我找了一下 没有这个cornerpool_lib.so

**Comment by super3kl** [comment]
补充一下在aistudio运行也是此问题

**Comment by super3kl** [comment]
aistudio的问题和自己的服务器不一样 
aistudio的原因是：定义op 出现问题 要升级到1.8.1 但是aistudio预设的环境最大为1.8.0 如何修改
另外服务器上的paddle为1.8.1
sh make.sh时出现问题
(paddle) zhulei@node5:/home/data/aistudio/PaddleDetection/ppdet/ext_op/src$ sh make.sh 
/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include
/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/libs
/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnCreateSpatialTransformerDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetSpatialTransformerNdDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDestroySpatialTransformerDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfGridGeneratorForward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfGridGeneratorBackward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfSamplerForward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfSamplerBackward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnFindConvolutionForwardAlgorithmEx"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnFindConvolutionBackwardFilterAlgorithmEx"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnFindConvolutionBackwardDataAlgorithmEx"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnCreateDropoutDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDropoutGetStatesSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetDropoutDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnCreateRNNDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetRNNDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnGetRNNParamsSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnGetRNNWorkspaceSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnGetRNNTrainingReserveSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNForwardTraining"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNBackwardData"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNBackwardWeights"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNForwardInference"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDestroyDropoutDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDestroyRNNDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetTensorNdDescriptorEx"

25 errors detected in the compilation of "/tmp/tmpxft_0000187b_00000000-4_bottom_pool_op.cpp4.ii".
/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnCreateSpatialTransformerDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetSpatialTransformerNdDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDestroySpatialTransformerDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfGridGeneratorForward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfGridGeneratorBackward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfSamplerForward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfSamplerBackward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnFindConvolutionForwardAlgorithmEx"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnFindConvolutionBackwardFilterAlgorithmEx"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnFindConvolutionBackwardDataAlgorithmEx"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnCreateDropoutDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDropoutGetStatesSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetDropoutDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnCreateRNNDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetRNNDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnGetRNNParamsSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnGetRNNWorkspaceSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnGetRNNTrainingReserveSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNForwardTraining"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNBackwardData"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNBackwardWeights"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNForwardInference"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDestroyDropoutDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDestroyRNNDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetTensorNdDescriptorEx"

25 errors detected in the compilation of "/tmp/tmpxft_0000188a_00000000-4_top_pool_op.cpp4.ii".
/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnCreateSpatialTransformerDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetSpatialTransformerNdDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDestroySpatialTransformerDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfGridGeneratorForward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfGridGeneratorBackward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfSamplerForward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfSamplerBackward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnFindConvolutionForwardAlgorithmEx"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnFindConvolutionBackwardFilterAlgorithmEx"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnFindConvolutionBackwardDataAlgorithmEx"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnCreateDropoutDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDropoutGetStatesSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetDropoutDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnCreateRNNDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetRNNDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnGetRNNParamsSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnGetRNNWorkspaceSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnGetRNNTrainingReserveSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNForwardTraining"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNBackwardData"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNBackwardWeights"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNForwardInference"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDestroyDropoutDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDestroyRNNDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetTensorNdDescriptorEx"

25 errors detected in the compilation of "/tmp/tmpxft_00001899_00000000-4_right_pool_op.cpp4.ii".
/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnCreateSpatialTransformerDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetSpatialTransformerNdDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDestroySpatialTransformerDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfGridGeneratorForward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfGridGeneratorBackward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfSamplerForward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSpatialTfSamplerBackward"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnFindConvolutionForwardAlgorithmEx"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnFindConvolutionBackwardFilterAlgorithmEx"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnFindConvolutionBackwardDataAlgorithmEx"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnCreateDropoutDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDropoutGetStatesSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetDropoutDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnCreateRNNDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetRNNDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnGetRNNParamsSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnGetRNNWorkspaceSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnGetRNNTrainingReserveSize"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNForwardTraining"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNBackwardData"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNBackwardWeights"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnRNNForwardInference"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDestroyDropoutDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnDestroyRNNDescriptor"

/home/zhulei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/include/paddle/fluid/platform/dynload/cudnn.h(132): error: the global scope has no "cudnnSetTensorNdDescriptorEx"

25 errors detected in the compilation of "/tmp/tmpxft_000018a8_00000000-4_left_pool_op.cpp4.ii".
g++: error: bottom_pool_op.cu.o: No such file or directory
g++: error: top_pool_op.cu.o: No such file or directory
g++: error: right_pool_op.cu.o: No such file or directory
g++: error: left_pool_op.cu.o: No such file or directory
rm: cannot remove ‘*.cu.o’: No such file or directory

**Comment by qingqing01** [comment]
1.  使用自定义OP时，注意G++/GCC版本的问题：  https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/ppdet/ext_op/README.md#%E8%87%AA%E5%AE%9A%E4%B9%89op%E7%9A%84%E7%BC%96%E8%AF%91%E8%BF%87%E7%A8%8B

2. 使用1.8.0应该也可以试下。 但注意CUDA、CUDNN的路径正确设置： https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/ppdet/ext_op/src/make.sh#L19

**Comment by super3kl** [comment]
aistudiod的gcc版本为5.4.0
我使用这个也编译成功了 在src下有cornerpool_lib.so文件生成
也按照这样下面这样添加路径了
可通过如下方式添加动态库路径:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`python -c 'import paddle; print(paddle.sysconfig.get_lib())'`

但是在test_corner_pool.py时候
Error Message Summary:
----------------------
Error: Failed to find dynamic library: /home/aistudio/work/PaddleDetection/ppdet/ext_op/src/cornerpool_lib.so ( libpaddle_framework.so: cannot open shared object file: No such file or directory ) 
 Please specify its path correctly using following ways: 
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
 For instance, issue command: export LD_LIBRARY_PATH=... 
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at (/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:177)
如果要改aistudio的gcc版本  怎么弄

**Comment by qingqing01** [comment]
@super3kl 上面除了，将`paddle.sysconfig.get_lib()`加到`LD_LIBRARY_PATH`之外，还需要把`cornerpool_lib.so`的路径加进去。  AIStudio上的GCC版本估计要去AIStudio相关问题区问下，感觉不一定好弄。

**Comment by qingqing01** [comment]
@super3kl 如果是训练的话，也可以不用编译ext_op，https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/ppdet/ext_op/cornerpool_lib.py#L36 ext_op里主要是bottom_pool，top_pool，right_pool，left_pool这些，这些在实现中也提供了op组合，ext_op一方面是为了预测加速。

**Comment by super3kl** [comment]
训练的话：
anchor_free里面的 focs是不用编译ext_op的  但是很奇怪是 train的各个loss是收敛的
但是每次val的各项ap都是0 
另外cornernet：训练的时候会出现的问题是关于cornerpool的问题 还是需要编译生成cornernet

**Comment by qingqing01** [comment]
@super3kl 嗯，你说的没错。 FCOS不需要ext_op。  CornetNet的话，如果修改下代码也可以不需要。 预测过程为了加速还是需要的。  FCOS的ap是0，你跑的是啥数据？有改动什么吗？

**Comment by super3kl** [comment]
没有ext_op 速度有多慢呀 
train的时候还是要val的
另外
跑的是红绿灯数据集
贴下我的yml吧
architecture: FCOS
max_iters: 180000
use_gpu: true
snapshot_iter: 200
log_smooth_window: 20
log_iter: 20
save_dir: output
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
metric: COCO
weights: output/fcos_r50_fpn_multiscale_2x/model_final
num_classes: 2

FCOS:
  backbone: ResNet
  fpn: FPN
  fcos_head: FCOSHead

ResNet:
  norm_type: affine_channel
  norm_decay: 0.
  depth: 50
  feature_maps: [3, 4, 5]
  freeze_at: 2

FPN:
  min_level: 3
  max_level: 7
  num_chan: 256
  use_c5: false
  spatial_scale: [0.03125, 0.0625, 0.125]
  has_extra_convs: true

FCOSHead:
  num_classes: 3
  fpn_stride: [8, 16, 32, 64, 128]
  num_convs: 4
  norm_type: "gn"
  fcos_loss: FCOSLoss
  norm_reg_targets: True
  centerness_on_reg: True
  use_dcn_in_tower: False
  nms: MultiClassNMS

MultiClassNMS:
  score_threshold: 0.025
  nms_top_k: 1000
  keep_top_k: 100
  nms_threshold: 0.6
  background_label: -1

FCOSLoss:
  loss_alpha: 0.25
  loss_gamma: 2.0
  iou_loss_type: "giou"
  reg_weights: 1.0

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [120000, 160000]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score', 'im_info']
  dataset:
    !COCODataSet
    image_dir: train2014
    anno_path: train2014.json
    dataset_dir: dataset/traffic
    with_background: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !RandomFlipImage
    prob: 0.5
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    target_size: [640, 672, 704, 736, 768, 800]
    max_size: 1333
    interp: 1
    use_cv2: true
  - !Permute
    to_bgr: false
    channel_first: true
  batch_transforms:
  - !PadBatch
    pad_to_stride: 128
    use_padded_im_info: false
  - !Gt2FCOSTarget
    object_sizes_boundary: [64, 128, 256, 512]
    center_sampling_radius: 1.5
    downsample_ratios: [8, 16, 32, 64, 128]
    norm_reg_targets: True
  batch_size: 4
  shuffle: true
  worker_num: 4
  use_process: false

EvalReader:
  inputs_def:
    fields: ['image', 'im_id', 'im_shape', 'im_info']
  dataset:
    !COCODataSet
    image_dir: val2014
    anno_path: val2014.json
    dataset_dir: dataset/traffic
    with_background: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    target_size: 800
    max_size: 1333
    interp: 1
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 128
    use_padded_im_info: true
  batch_size: 8
  shuffle: false
  worker_num: 8
  use_process: false

TestReader:
  inputs_def:
    # set image_shape if needed
    fields: ['image', 'im_id', 'im_shape', 'im_info']
  dataset:
    !ImageFolder
    anno_path: val2014.json
    with_background: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    interp: 1
    max_size: 1333
    target_size: 800
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 128
    use_padded_im_info: true
  batch_size: 1
  shuffle: false

**Comment by CodesFarmer** [comment]
@super3kl FCOS配置文件中FCOSHead处的num_classes需要和全局的num_classes保持一致
