### ISSUE TITLE
训练的模型不精准问一下版面分析如何finetune

### ISSUE THREAD

**Issue by 1061302569** [PaddlePaddle/PaddleDetection#7700]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

来到paddle学习了一段时间，训练的版面分析模型不精准，得到的建议是让我finetune，可是版面分析要如何finetune，需要自己配置yml吗

**Comment by wangxinxin08** [comment]
参考文档进行训练：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/layout/README_ch.md#51-%E5%90%AF%E5%8A%A8%E8%AE%AD%E7%BB%83

**Comment by wangxinxin08** [comment]
fintune需要你收集并标注你自己的数据按照上述文档进行训练

**Comment by 1061302569** [comment]
> fintune需要你收集并标注你自己的数据按照上述文档进行训练

我是按这个教程训练的，是不是是我的数据集太少的原因导致 目前数据集标注了191张，一般finetune数据集多少比较合适，就是这个位置不少出现检测框识别不全，大部分都是正常的，是不是还需要加入新图片finetune,还是把原有不准确的图片复制进行重复标注是否可以提升识别率
![1675826706154](https://user-images.githubusercontent.com/44227598/217421131-0a0bc3b8-4137-41c5-8ee9-0e10be66a3a4.png)
![1675826839984](https://user-images.githubusercontent.com/44227598/217421609-05505918-a409-4841-8dc9-28ae1ba06d98.png)

**Comment by wangxinxin08** [comment]
可以增加下fintune的数据，检测不准确的数据类型也适当增加下

**Comment by 1061302569** [comment]
> 可以增加下fintune的数据，不准备的数据类型也是党增加下

谢谢老师，就是继续增加finetune的数据集，不准备的数据类型也是党增加下是什么

**Comment by 1061302569** [comment]
> 可以增加下fintune的数据，检测不准确的数据类型也适当增加下

感谢老师，我去试试把数据量堆到500看能不能完美识别这四个框
