### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 46: illegal multibyte sequence

### ISSUE THREAD

**Issue by 710350964** [PaddlePaddle/PaddleDetection#7701]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddle paddle==2.4.1，paddle detection==2.5，python==3.9.16
使用paddledetection时报错。
在cmd中输入指令python tools/train.py -c configs/picodet/picodet_s_320_coco_lcnet.yml  -o pretrain_weights=https://paddledet.bj.bcebos.com/models/picodet_s_320_coco.pdparams  num_classes=1  LearningRate.base_lr=0.1  --eval，项目是学习飞桨官方课程时发布的，公开项目

PP-PicoDet之手把手教你玩转移动端目标检测。还望指点。

**Comment by wangxinxin08** [comment]
这里是windows的默认编码为gbk导致的，可以把https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/core/workspace.py#L78 和https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/core/workspace.py#L91 的open函数都添加上参数`encoding='utf-8'`来解决

**Comment by 710350964** [comment]
问题已解决，应该填上'utf-8'，但要注意的是，如果是在虚拟环境中，也要修改。
