### ISSUE TITLE
使用paddlex提供的API，用YOLOv3进行模型训练时报错（pretrain_weights）

### ISSUE THREAD

**Issue by Zero521ZR** [PaddlePaddle/PaddleDetection#7721]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![5a2670358da2bbcce88c59b8b90420f](https://user-images.githubusercontent.com/84949376/217990606-a2c9ed09-9fd1-49d0-a03c-11791aab81f9.jpg)

**Comment by nemonameless** [comment]
报错请按模板提问以便排查谢谢，截图请截全谢谢 https://github.com/PaddlePaddle/PaddleDetection/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml
建议直接使用PaddleDetection，或前往 https://github.com/PaddlePaddle/PaddleX/issues 提问
