### ISSUE TITLE
DETR is not supported for exporting model now.

### ISSUE THREAD

**Issue by zhizhusheng** [PaddlePaddle/PaddleDetection#7727]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好 ，导出模型 detr 报错 Architecture: DETR is not supported for exporting model now.，我自己能解决么

**Comment by nemonameless** [comment]
支持导出的。请切换到develop分支或2.6分支。
https://github.com/PaddlePaddle/PaddleDetection/tree/develop
