### ISSUE TITLE
picodet推理报错

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/PaddleDetection#7729]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

deploy/python/infer.py
PredictConfig类中
picodet模型推理报错，picodet模型配置文件里没有fpn_stride和nms属性，但是infer.py代码里却要读取这俩属性，导致报错
我用的picodet模型是picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer

### 复现环境 Environment

window系统
paddle2.4.1
paddledetect是develop版本

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
主体检测请前往PaddleClas的PP-ShiTu去使用。 https://github.com/PaddlePaddle/PaddleClas 
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/picodet/legacy_model/application/mainbody_detection/README.md
