### ISSUE TITLE
fruit数据集 运行eval.py 报错没有gt_bbox

### ISSUE THREAD

**Issue by qjing666** [PaddlePaddle/PaddleDetection#773]
如题，用faster_rcnn模型训练fruit数据集，并有模型保存到 output/faster_rcnn_r50_fruit/ 路径下，在验证模型在测试集的效果时 运行 " python -u tools/eval.py -c configs/faster_rcnn_r50_fruit.yml -o weights=output/faster_rcnn_r50_fruit/"  报错如下：

Traceback (most recent call last):
  File "tools/eval.py", line 190, in <module>
    main()
  File "tools/eval.py", line 173, in main
    dataset=dataset)
  File "/home/jingqinghe/PaddleDetection/ppdet/utils/eval_utils.py", line 226, in eval_results
    map_type=map_type)
  File "/home/jingqinghe/PaddleDetection/ppdet/utils/voc_eval.py", line 73, in bbox_eval
    gt_boxes = t['gt_bbox'][0]
KeyError: 'gt_bbox'

**Comment by 924175302** [comment]
请问解决了吗

**Comment by qjing666** [comment]
还没有

**Comment by 924175302** [comment]
我也遇到这个问题，搞了一天没解决

**Comment by qingqing01** [comment]
@qjing666 你用的是VOC评估，注意`EavalReader`的fields字段内容是: `fields: ['image', 'im_info', 'im_id', 'im_shape', 'gt_bbox', 'gt_class', 'is_difficult']`，COCO评估不需要此字段，VOC需要。

**Comment by qjing666** [comment]
问题解决~ 非常感谢！

**Comment by qingqing01** [comment]
@924175302 看下是否统一问题哈。 @qjing666 如果没问题的话，可以关闭issue。

**Comment by Yaoxingtian** [comment]
> fields

請問fields字段是如何決定的呢 ？是不是訓練的時候定義的fields 內容然後測試的fields 也一樣？

**Comment by Yaoxingtian** [comment]
> @qjing666 你用的是VOC评估，注意`EavalReader`的fields字段内容是: `fields: ['image', 'im_info', 'im_id', 'im_shape', 'gt_bbox', 'gt_class', 'is_difficult']`，COCO评估不需要此字段，VOC需要。 参考: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/configs/faster_reader.yml#L36 。另外也注意其实Faster+FPN精度高，也速度快。
請問fields字段是如何決定的呢 ？是不是訓練的時候定義的fields 內容然後測試的fields 也一樣？
但是我的eval fields 內容是：['image', 'im_size', 'im_id','gt_bbox','gt_class', 'gt_score','is_difficult'] 才能運行正常
