### ISSUE TITLE
ppyoloe训练卡0占用显存过多

### ISSUE THREAD

**Issue by bixiaopeng0** [PaddlePaddle/PaddleDetection#7730]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![4a7551cc2908c073c667fcc4654be75d](https://user-images.githubusercontent.com/31760851/218054450-c62d01a7-5682-4893-be95-d0246908bd16.png)
如图所示，未使用多尺度训练的情况下，卡0占用显存较高，具体原因是为什么呢？

**Comment by nemonameless** [comment]
请使用develop分支。https://github.com/PaddlePaddle/PaddleDetection/tree/develop
