### ISSUE TITLE
训练一轮python异常退出

### ISSUE THREAD

**Issue by Synmul** [PaddlePaddle/PaddleDetection#7732]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![1](https://user-images.githubusercontent.com/50161120/218081556-b5651060-ba92-42f6-ac36-6706a14c5351.png)
![2](https://user-images.githubusercontent.com/50161120/218081579-3fafd6a5-cc35-40d4-bb76-f96c41c18242.png)
![3](https://user-images.githubusercontent.com/50161120/218083347-d8b2a956-706b-43bf-b15e-56216adbaf69.png)
![4](https://user-images.githubusercontent.com/50161120/218083358-82605e08-7342-4b74-8efd-5abc54d19455.png)

应该是训练结束保存或干别的什么事出异常了
我看到之前也有人有出过这个问题，但最后都不了了之了
0xC0000005
没符号

**Comment by Synmul** [comment]
![3](https://user-images.githubusercontent.com/50161120/218083046-b5919eb3-e2a6-45fe-907b-700de86b8c09.png)
![4](https://user-images.githubusercontent.com/50161120/218083059-d5d5e474-b984-4f17-8203-b0c282c71f04.png)

**Comment by nemonameless** [comment]
请补充使用的paddle版本和环境等信息。
win下使用paddle2.2.2试试。

**Comment by Synmul** [comment]
> 请补充使用的paddle版本和环境等信息。 win下使用paddle2.2.2试试。

2.4.1  我换2.2.2试试看
