### ISSUE TITLE
使用vgg16模型，该如何导入模型，并测试？并且如何能够得到网络的每一层的输入输出特征值？

### ISSUE THREAD

**Issue by taoja12** [PaddlePaddle/PaddleDetection#775]
对于得到每一层的输入输出特征值，类似于tensorflow的代码。
`import cv2
import os
import tensorflow as tf
import numpy as np
from caffe_classes import class_names
np.set_printoptions(threshold=np.inf)

interpreter =tf.lite.Interpreter(model_path='alexnet.tflite')
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

image = './images/llama.jpeg'
image = cv2.imread(image)
image = cv2.resize(image, (227, 227))

image = image.reshape((1, 227, 227, 3))
input_data = image.astype(np.float32)
index = input_details[0]['index']
interpreter.set_tensor(index, input_data)
interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])

tensor_detail = interpreter._get_tensor_details(20)
output = interpreter.get_tensor(tensor_detail['index'])
f = open(r'./each_layer_output/conv1.txt', 'w')
print(output, file=f)
f.close()
`
这是我的网络模型的链接
链接: https://pan.baidu.com/s/1LMsIETIcqlh6pedRFQG74Q 提取码: 9mf8

**Comment by qingqing01** [comment]
@taoja12 我看您的代码里有`tf.lite`，这个是paddle的代码吗？您是想问在paddle里怎么导入模型，并获取每一层的输入、输出特征吗？

**Comment by taoja12** [comment]
> @taoja12 我看您的代码里有tf.lite，这个是paddle的代码吗？您是想问在paddle里怎么导入模型，并获取每一层的输入、输出特征吗？

我附录的代码是我之前使用tensorflow获取模型每一层输入输出的过程，想请问paddle中获取是不是也类似的方法，具体该怎么做呢才能够在paddle模型中获取模型的每一层的输入输出特征值。

**Comment by qingqing01** [comment]
@taoja12 因为下载较慢，还没完全下载下来代码。 Paddle获取模型没一层的输入、输出，是可以找到要fetch的层，输入、输出的Variable的名字，然后放在run的fetch_list中。 FAQ文档： https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/train_cn.html#id6
