### ISSUE TITLE
你好，pp-yoloe 执行ACT自动压缩量化是必须要有训练数据集才能进行吗，如果不用数据集也可以进行ACT是否有教程？

### ISSUE THREAD

**Issue by lw-2017** [PaddlePaddle/PaddleDetection#7752]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，pp-yoloe 执行ACT自动压缩量化是必须要有训练数据集才能进行吗，如果不用数据集也可以进行ACT是否有教程？

**Comment by jerrywgz** [comment]
目前还不支持data free的量化，需要依赖数据校准量化模型
