### ISSUE TITLE
增强算子RandomCrop疑问

### ISSUE THREAD

**Issue by linghaolu** [PaddlePaddle/PaddleDetection#776]
1:  计算crop宽高一个是乘法一个是除法，很是疑惑。不知道是错误还是我没有理解
```
    crop_h = int(h * scale / np.sqrt(aspect_ratio))
    crop_w = int(w * scale * np.sqrt(aspect_ratio))
```
2: thresholds 参数计算的时候 area_i / area_o  这个感觉如果自己想设置一个阈值根本没办法控制，改为 area_i / area_a 是不是更直观？

**Comment by jerrywgz** [comment]
1. 这里的目的是是宽高比为aspect_ratio
2. thresholds是一个list然后随机得到一个阈值，这个random crop中有比较具体的代码注释，你这边是希望把阈值设定成一个固定值吗

**Comment by linghaolu** [comment]
2: 是的，希望根据和 bbox 的比例来控制，比如bbox被裁剪后，面积不能过小。

**Comment by jerrywgz** [comment]
这个我们后面可以增强下，我再确认下，一个是希望阈值为定值，另外一个是希望增加crop后bbox的面积限制？

**Comment by linghaolu** [comment]
我现在的业务场景是想bbox在增强过程中不被crop，或者小面积被crop，读代码过程中发现没有办法控制。

**Comment by jerrywgz** [comment]
可以先手动在https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/ppdet/data/transform/operators.py#L1673 中增加对crop出的box的限制，threshold的含义就是用于限制crop出的box与gt box的iou值，如果是面积的话还需要新增一个参数
