### ISSUE TITLE
使用基于yolov3_mobilenet_v1_roadsign.yml的配置文件，在自己的数据集上做上目标检测的训练，在visualdl中从哪个参数可以知道是否训练过拟合了，请帮忙指导一下，谢谢

### ISSUE THREAD

**Issue by happybuby** [PaddlePaddle/PaddleDetection#7763]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用基于yolov3_mobilenet_v1_roadsign.yml的配置文件，在自己的数据集上做上目标检测的训练，在visualdl中从哪个参数可以知道是否训练过拟合了，请帮忙指导一下，谢谢

**Comment by wangxinxin08** [comment]
取决于你visualdl中保存了那些数值，一般我们从loss和mAP两个指标去看，根据过拟合的定义，如果训练集的loss下降，验证集的loss上升或者训练集的mAP上升，验证集的mAP下降，我们认为出现了过拟合的现象
