### ISSUE TITLE
安装依赖的时候报错，权限不够

### ISSUE THREAD

**Issue by Farewell-CK** [PaddlePaddle/PaddleDetection#7765]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

![pdissue](https://user-images.githubusercontent.com/101492509/218946161-5d07d47b-561b-4def-82e8-1ab2f305ae44.png)

### 复现环境 Environment

AI studio 创建的CodeLab
python 3.7
paddle 2.4

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
按照提示，在安装时添加--user的flag
