### ISSUE TITLE
有没有模型前后处理说明？

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/PaddleDetection#7767]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

例如picodet主体检测模型picodet_lcnet_x2_5_640_mainbody_infer和Lite版的前后处理完全不一样，具体有没有相关文档说明？谢谢

**Comment by wangxinxin08** [comment]
1. 前处理定义在TestReader中的sample_transform中，主要是做resize/normalize_image/pad等操作，在做推理的时候预处理操作都继承自TestReader当中
2. 后处理一般是bbox解码和nms操作，后处理一般是一致的，不过在不同的硬件上推理时，可能会把后处理放在网络内部，或者网络外部。如果放在网络内部，后处理的操作在推理时就不可见了，如果放在网络外部，可以看到有明显的后处理过程。picodet提供了后处理放在网络内部和外部的两种方式，具体可以参考文档：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/picodet
