### ISSUE TITLE
用eval.py进行评估时输出不同

### ISSUE THREAD

**Issue by qjing666** [PaddlePaddle/PaddleDetection#777]
用fruit数据集训练20000轮后将模型保存至 output/faster_rcnn_r50_fruit/路径下。运行
`python -u tools/eval.py -c configs/faster_rcnn_r50_fruit.yml -o weights=output/faster_rcnn_r50_fruit/` 对模型进行评估时输出不同：

1. 遇到过两种不同的报错：

<img width="1440" alt="截屏2020-05-26下午1 39 43" src="https://user-images.githubusercontent.com/19721227/82864720-c7b94380-9f57-11ea-9dcc-35bd9b1b84ad.png">

以及

<img width="1440" alt="截屏2020-05-26下午1 39 29" src="https://user-images.githubusercontent.com/19721227/82864813-fb946900-9f57-11ea-8ec5-971a13caf91b.png">

且在运行时遇到warning，没有找到.pdparams文件（机器中安装的是paddle1.8， 参考之前的PR，这个问题可以忽略。）

2. 在评估正常运行时，输出的mAP也不同，以下为实验三次得到的不同结果（使用相同的验证集）：

<img width="875" alt="截屏2020-05-26下午1 40 09" src="https://user-images.githubusercontent.com/19721227/82864990-5a59e280-9f58-11ea-8106-849ed0b9beb1.png">
<img width="871" alt="截屏2020-05-26下午1 40 56" src="https://user-images.githubusercontent.com/19721227/82864996-5ded6980-9f58-11ea-9615-ef7a6f7bf272.png">
<img width="866" alt="截屏2020-05-26下午1 44 34" src="https://user-images.githubusercontent.com/19721227/82865194-c2a8c400-9f58-11ea-9ec7-902624b284d4.png">

想请问下，相同验证集得到不同mAP是什么原因导致的呢？

**Comment by jerrywgz** [comment]
可以确认下你的权重是否正确加载了，感觉命令应该修改为：python -u tools/eval.py -c configs/faster_rcnn_r50_fruit.yml -o weights=output/faster_rcnn_r50_fruit/20000

**Comment by qjing666** [comment]
赞，问题解决了，多谢！
