### ISSUE TITLE
smalldet

### ISSUE THREAD

**Issue by GeT-RiGhTTT** [PaddlePaddle/PaddleDetection#7771]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

切图的时候报错 ValueError：not enough values to unpack（expected 4, got 0）
![image](https://user-images.githubusercontent.com/58615953/218986305-ac0ac6db-7313-4b00-bc69-85aa92f06126.png)

**Comment by nemonameless** [comment]
检查一下是否有空标注，就是没有gt的图片，先排除掉这种图吧。
