### ISSUE TITLE
smalldet预测很慢

### ISSUE THREAD

**Issue by WooXinyi** [PaddlePaddle/PaddleDetection#7777]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

smalldet采用子图拼图评估，设置slice_size 640，overlap_ratio 0.25，原图会被切为40张子图，最后预测一张原图需要大约15分钟，请问是否正常？我的卡是3080。

### 复现环境 Environment

paddledet=2.5.0
paddlepaddle-gpu==2.2.2.post110

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
不太正常吧  是跑在gpu上了嘛 ， 能大概判断一下是推理慢  还是结果合并的时候慢嘛

**Comment by WooXinyi** [comment]
> 不太正常吧 是跑在gpu上了嘛 ， 能大概判断一下是推理慢 还是结果合并的时候慢嘛

测试了是推理速度慢，40张子图共用时989s，使用nvidia-smi看是占用了显存的。

**Comment by WooXinyi** [comment]
> 不太正常吧 是跑在gpu上了嘛 ， 能大概判断一下是推理慢 还是结果合并的时候慢嘛

测试了一下，是40张子图合并的时候慢，采用的是nms方法

**Comment by nemonameless** [comment]
40张子图太多了，原图有多大呢？slice_size 640可以设置大点比如800 960。子图越多整体速度越慢

**Comment by WooXinyi** [comment]
> 40张子图太多了，原图有多大呢？slice_size 640可以设置大点比如800 960。子图越多整体速度越慢

原图是3840*2160的，一般子图数量在多少是比较合适的呢？

**Comment by nemonameless** [comment]
10多张就已经算多了
