### ISSUE TITLE
推理多进程还是多线程好？

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/PaddleDetection#7778]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在开发视频流分析处理，比如pphuman，对于多路视频分析，我是采用多线程比较好，还是多进程比较好，谢谢

**Comment by lyuwenyu** [comment]
多进程会好点吧  不过还是得实测一下
