### ISSUE TITLE
Can yolo heads deal with input images where width <> height?

### ISSUE THREAD

**Issue by flishwnag** [PaddlePaddle/PaddleDetection#778]
Currently, yolo_box only support input shape [N, C, H, W] where H == W.
However, This means that I have to pad or expand the images (i.e. 512*1024) to square, resulting in either less compute efficiency or extra inaccuracy.
So can you add support for inputs with different shape?

In chinese:
目前，fluid.layers中yolo_box的输入尺寸只允许图片宽==高。因此，对于长宽比并不接近的图片来说，使用padding补成正方形的话，计算效率会受影响，使用拉伸方式拉成正方形的话，因为形变过大，会影响结果精度。能否增加对宽高不一致的输入尺寸的支持呢？

**Comment by jerrywgz** [comment]
目前还不支持长宽不一致的输入，如果希望保持宽高比的话可以尝试使用rcnn系列模型

**Comment by flishwnag** [comment]
> 目前还不支持长宽不一致的输入，如果希望保持宽高比的话可以尝试使用rcnn系列模型

好的。未来yolo系列是否考虑增加支持长宽不一致的输入呢？

**Comment by jerrywgz** [comment]
后续我们也会评估下这个需求，暂时可能还没有这个计划

**Comment by yinggo** [comment]
顶一下这个需求~  XD
