### ISSUE TITLE
什么时候支持单目标跟踪算法

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/PaddleDetection#7780]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（最近在做边缘端车辆和人员的检测跟踪，其中跟踪需要使用到单目标跟踪）; 2. 需求场景（由于相机带有云台，需要自动根据目标进行旋转，变焦等，因此需要单目标跟踪，效率高而且准确）; 3. 功能描述（单目标跟踪这个需求去年回复说今年第一季度出来算法，请问大概什么时候公开算法呢？）
2. 感谢帮助！AiStudio上的单目标算法效果太差，根本无法使用。

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
内部决策暂时没有排期了

**Comment by thinkthinking** [comment]
合入Roadmap of PaddleDetection 需求 #7892
