### ISSUE TITLE
ppyoloe_sod在COCO数据集上的训练日志

### ISSUE THREAD

**Issue by Yi-dashi** [PaddlePaddle/PaddleDetection#7784]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，请问可以提供一下ppyoloe_sod在coco数据集上的训练日志吗？

**Comment by nemonameless** [comment]
暂时找不到了，有资源可以自行训练一遍试试
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/smalldet#coco%E6%A8%A1%E5%9E%8B
