### ISSUE TITLE
pp-yoloe+train和eval结果相差很大

### ISSUE THREAD

**Issue by Phoenix8215** [PaddlePaddle/PaddleDetection#7785]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

- 使用pp-yoloe+模型训练的结果如下，train和eval的结果差距很大，不太清楚为啥，train显示loss很小，按理说AP应该很高才对，但是val这边MAP最高才81%，过拟合么
[![pSqpk0H.jpg](https://s1.ax1x.com/2023/02/17/pSqpk0H.jpg)](https://imgse.com/i/pSqpk0H)
[![pSqpFne.jpg](https://s1.ax1x.com/2023/02/17/pSqpFne.jpg)](https://imgse.com/i/pSqpFne)

**Comment by nemonameless** [comment]
loss小和AP高没有必然联系。
数据集难或种类很多时AP上限也不会太高。

**Comment by Phoenix8215** [comment]
> loss小和AP高没有必然联系。 数据集难或种类很多时AP上限也不会太高。

@nemonameless 哦哦，明白了谢谢😊
