### ISSUE TITLE
下载数据集

### ISSUE THREAD

**Issue by JULYLH** [PaddlePaddle/PaddleDetection#7794]
请问行人识别模型的官方数据集能够下载吗

**Comment by zhiboniu** [comment]
这个行人识别指的是行人检测吗？还是reid？

**Comment by JULYLH** [comment]
就是训练pp-human的跌倒打架模型的数据集，请问可以下载吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 上午10:28
***@***.***&gt;;
抄送:&nbsp;"JULY ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 下载数据集 (Issue #7794)





 
这个行人识别指的是行人检测吗？还是reid？

**Comment by zhiboniu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/pipeline/docs/tutorials/pphuman_action.md

**Comment by zhiboniu** [comment]
可以看看这个链接里提供的数据链接。
