### ISSUE TITLE
Inconsistent benchmark results for Jetson AGX Xavier for Faster RCNN FPN

### ISSUE THREAD

**Issue by arjitkatare** [PaddlePaddle/PaddleDetection#7796]
### 文档链接&描述 Document Links & Description

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/deploy/BENCHMARK_INFER.md

inference speed for larger image_size 800x1312 is faster than imagea_size 640x640 for trt_fp32 and trt_fp16

**Comment by jerrywgz** [comment]
The benchmark is tested on PaddlePaddle v2.0.1 and TRT 6.0 and Faster RCNN has dynamic shape which may slow down the inference speed on TRT. We will update the benchmark later.
