### ISSUE TITLE
ppyoloer 训练报错

### ISSUE THREAD

**Issue by zgsxwsdxg** [PaddlePaddle/PaddleDetection#7797]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在配置文件
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/rotate/ppyoloe_r/_base_/ppyoloe_r_reader.yml
 中TrainReader配置如下：
TrainReader: sample_transforms: - Decode: {} - Poly2Array: {} - RandomRFlip: {} - RandomRRotate: {angle_mode: 'value', angle: [0, 90, 180, -90]} - RandomRRotate: {angle_mode: 'value', angle: [30, 60], rotate_prob: 0.5} - RResize: {target_size: *image_size, keep_ratio: True, interp: 2} - Poly2RBox: {filter_threshold: 2, filter_mode: 'edge', rbox_type: 'oc'} batch_transforms: - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True} - Permute: {} - PadRGT: {} - PadBatch: {pad_to_stride: 32} batch_size: 2 shuffle: true drop_last: true use_shared_memory: true collate_batch: true

将 use_shared_memory 设置为true，训练报错如下：

loading annotations into memory...
Done (t=10.42s)
creating index...
index created!
W0220 17:14:15.887986 98951 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0220 17:14:16.016237 98951 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
Process Process-10:
Traceback (most recent call last):
File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
self.run()
File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/multiprocessing/process.py", line 99, in run
self._target(*self._args, **self._kwargs)
File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 368, in _worker_loop
six.reraise(*sys.exc_info())
File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/six.py", line 719, in reraise
raise value
File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 358, in _worker_loop
else tensor_share_memory(b) for b in batch
File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 358, in
else tensor_share_memory(b) for b in batch
RuntimeError: (Unavailable) Memory map failed when create shared memory.
[Hint: Expected ptr != ((void *) -1), but received ptr:0xffffffffffffffff == ((void *) -1):0xffffffffffffffff.] (at /paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:230)

Traceback (most recent call last):
File "tools/train.py", line 188, in
main()
File "tools/train.py", line 184, in main
run(FLAGS, cfg)
File "tools/train.py", line 123, in run
trainer = Trainer(cfg, mode='train')
File "/data/duxiaogang/PaddleDetection-dev/ppdet/engine/trainer.py", line 109, in init
self.model = create(cfg.architecture)
File "/data/duxiaogang/PaddleDetection-dev/ppdet/core/workspace.py", line 246, in create
cls_kwargs.update(cls.from_config(config, **kwargs))
File "/data/duxiaogang/PaddleDetection-dev/ppdet/modeling/architectures/yolo.py", line 62, in from_config
backbone = create(cfg['backbone'])
File "/data/duxiaogang/PaddleDetection-dev/ppdet/core/workspace.py", line 283, in create
return cls(**cls_kwargs)
File "/data/duxiaogang/PaddleDetection-dev/ppdet/modeling/backbones/cspresnet.py", line 258, in init
3, channels[0] // 2, 3, stride=2, padding=1, act=act)),
File "/data/duxiaogang/PaddleDetection-dev/ppdet/modeling/backbones/cspresnet.py", line 51, in init
bias_attr=False)
File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 657, in init
data_format=data_format)
File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 136, in init
default_initializer=_get_default_param_initializer())
File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 424, in create_parameter
default_initializer)
File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 381, in create_parameter
**attr._to_kwargs(with_initializer=True))
File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3572, in create_parameter
initializer(param, self)
File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 367, in call
'std', self._std_dev, 'seed', self._seed, 'use_mkldnn', False)
File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/multiprocess_utils.py", line 134, in handler
core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 98991) exited unexpectedly with code 1. Error detailed are lost due to multiprocessing. Rerunning with:

If run DataLoader by DataLoader.from_generator(...), run with DataLoader.from_generator(..., use_multiprocess=False) may give better error trace.
If run DataLoader by DataLoader(dataset, ...), run with DataLoader(dataset, ..., num_workers=0) may give better error trace (at /paddle/paddle/fluid/imperative/data_loader.cc:156)

我机器配置内存92G
GPU配置：32G
Mon Feb 20 17:56:05 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:08.0 Off |                    0 |
| N/A   42C    P0   115W / 300W |  15017MiB / 32510MiB |     26%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     99362      C   python                          15015MiB |
+-----------------------------------------------------------------------------+

PaddleDetection 版本为dev分支版本
Paddle版本为2.3.2

那位同仁帮忙看看如何解决？加快训练速度。我把use_shared_memory 设置为false可以训练，就是太慢了，该怎么办？

**Comment by wangxinxin08** [comment]
报错的原因显示是shared_memory不足，如果是docker需要在创建docker时设置shm-size，如果是裸机的话，可以搜索下提升shared_memory的办法

**Comment by zgsxwsdxg** [comment]
> 报错的原因显示是shared_memory不足，如果是docker需要在创建docker时设置shm-size，如果是裸机的话，可以搜索下提升shared_memory的办法

我的是linux 裸机，共享内存设置多大合适？

**Comment by zgsxwsdxg** [comment]
> 报错的原因显示是shared_memory不足，如果是docker需要在创建docker时设置shm-size，如果是裸机的话，可以搜索下提升shared_memory的办法

我的内存信息入下：
 free -mh
                    total        used        free      shared  buff/cache   available
Mem:           90Gi        23Gi       594Mi       1.4Gi        66Gi        64Gi
Swap:            0B          0B          0B

**Comment by wangxinxin08** [comment]
一般设置16G/32G是足够的

**Comment by zgsxwsdxg** [comment]
> 一般设置16G/32G是足够的
老师您好！
我看了下 通过df -h，信息如下：
![image](https://user-images.githubusercontent.com/12712884/220593265-e3bcda84-0a90-4d63-b1dc-1bac2efb21c2.png)

好像有/dev/shm 是32G了，就是训练还报错，能不能帮忙看看了，怎样才能可以定位到问题所在？谢谢！

**Comment by wangxinxin08** [comment]
报什么错，和原先的错误一样吗？

**Comment by zgsxwsdxg** [comment]
> 和原先的错误一样吗？

是的

**Comment by wangxinxin08** [comment]
如果数据预处理中存在0维度Tensor/numpy数组，会出现这样的问题，可以在数据预处理避免下

**Comment by zgsxwsdxg** [comment]
> 如果数据预处理中存在0维度Tensor/numpy数组，会出现这样的问题，可以在数据预处理避免下

您好，老师！
1. 我首先说下我的数据，是这样生成的，通过尺度裁切工具https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/rotate/tools/prepare_data.py这个脚本裁切成1024x1024的图片，这样的话生成样本可能会有没有bbox的数据，
所以，我在数据配置https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/datasets/dota_ms.yml 配置中配置了
TrainDataset:
    allow_empty: False,
    empty_ratio: 0.1 
这两个参数，防止训练得到的模型会误检，加入了0.1比例的负样本，难道是这两个参数影响访问共享内存？

2. “数据预处理中存在0维度Tensor/numpy数组，会出现这样的问题，可以在数据预处理避免下”，这个我需要改那块代码？还是哪些配置参数？谢谢，期待您的回复！！！

**Comment by zgsxwsdxg** [comment]
> 如果数据预处理中存在0维度Tensor/numpy数组，会出现这样的问题，可以在数据预处理避免下

您好，老师！
1. 我首先说下我的数据，是这样生成的，通过尺度裁切工具https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/rotate/tools/prepare_data.py这个脚本裁切成1024x1024的图片，这样的话生成样本可能会有没有bbox的数据，
所以，我在数据配置https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/datasets/dota_ms.yml 配置中配置了
TrainDataset:
    allow_empty: False,
    empty_ratio: 0.1 
这两个参数，防止训练得到的模型会误检，加入了0.1比例的负样本，难道是这两个参数影响访问共享内存？

2. “数据预处理中存在0维度Tensor/numpy数组，会出现这样的问题，可以在数据预处理避免下”，这个我需要改那块代码？还是哪些配置参数？谢谢，期待您的回复！！！

**Comment by wangxinxin08** [comment]
先去debug下，数据预处理后的结果是不是有的数组为0维度tensor，如果有，目前只能把shared memory关掉

**Comment by zgsxwsdxg** [comment]
> 1. TrainDataset:
>    allow_empty: False,
>    empty_ratio: 0.1

好的，老师！顺便问下，和我设置了
TrainDataset:
allow_empty: False,
empty_ratio: 0.1
这两参数没多大关系么？

**Comment by zgsxwsdxg** [comment]
> 



> 先去debug下，数据预处理后的结果是不是有的数组为0维度tensor，如果有，目前只能把shared memory关掉

老师好，我试验了，如果TrainDataset:
allow_empty: False,
empty_ratio: 0.1
训练集不允许加入负样本，能正常训练。就是说咱们ppyoloer目前不支持共享内存下加入负样本训练？

**Comment by bittergourd1224** [comment]
遇到同样问题，且确认也是由于allow_empty导致
