### ISSUE TITLE
fasterRcnn+FPN 推理出现误识别

### ISSUE THREAD

**Issue by wyc880622** [PaddlePaddle/PaddleDetection#781]
误识别图：
![image](https://user-images.githubusercontent.com/25219834/82879101-11615880-9f6f-11ea-9cf6-1fd591284a09.png)

1.训练的图片155张，识别3种类型 训练了2000次 batchsize=2
2.评估结果如下
![image](https://user-images.githubusercontent.com/25219834/82879268-4a99c880-9f6f-11ea-8467-a4a9b0773635.png)
我想问以下几个问题？
1.评估结果是怎么看的，没有详细说明
2,我如何处理误识别情况，难道是这样吗
![image](https://user-images.githubusercontent.com/25219834/82879424-816fde80-9f6f-11ea-897a-ea51fcf84eba.png) 多训练，多调优。我应该怎么去调优，有没有方法。
3.现在我预测的速度大概在1.2s一张图片，我想提速，该如何提速。
谢谢。

**Comment by jerrywgz** [comment]
上图中的评估结果是通过cocoapi得到的，一般会参考第一行的mAP指标，即0.300，这个指标反应了预测检测框与真实检测框相比，在相同类别的情况下iou在0.5到0.95之间的个数。如果没有参考指标的话观察可视化结果也可以，从上图来看会出现一定误检的情况，通常的调优策略包括增加预处理，训练更多轮数，也可以加载coco数据集上的预训练模型。

关于提速，可以尝试使用轻量化的骨干网络，例如mobilenetv3，但是相对的精度也会收到影响，另外也可以尝试下PaddleSlim对模型进行剪裁压缩，检测库中有https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/slim/prune 相关文档可以参考

**Comment by qingqing01** [comment]
关于问题3,  再补充下： 是Python预测吗？ 1.2s是CPU预测，还是GPU预测？ 提速的话： 

(1) 从模型角度考虑，可以选择速度较快的模型，比如YOLOv3-DarkNet53, YOLOv3-ResNet34，但精度可能比RCNN+FPN模型精度低。  不同模型速度比较可以参考: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/advanced_tutorials/deploy/BENCHMARK_INFER_cn.md

(2) 预测库，可以考虑使用 [deploy](https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/deploy) 下面，该预测使用了Paddle的预测引擎加速。 

(3) 最后考虑模型压缩

**Comment by wyc880622** [comment]
> 上图中的评估结果是通过cocoapi得到的，一般会参考第一行的mAP指标，即0.300，这个指标反应了预测检测框与真实检测框相比，在相同类别的情况下iou在0.5到0.95之间的个数。如果没有参考指标的话观察可视化结果也可以，从上图来看会出现一定误检的情况，通常的调优策略包括增加预处理，训练更多轮数，也可以加载coco数据集上的预训练模型。
> 
> 关于提速，可以尝试使用轻量化的骨干网络，例如mobilenetv3，但是相对的精度也会收到影响，另外也可以尝试下PaddleSlim对模型进行剪裁压缩，检测库中有https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/slim/prune 相关文档可以参考

谢谢你的答案，我还想具体问下
1.增加预处理是指那些方面的内容，能方便给出例子吗？
2.coco数据集预训练模型指的是那些？
3.我在训练中增加了训练次数，但在训练过程中loss_bbox 到25100以后突然递减到0，之后一直是0 不知道是什么原因造成的。所以评估的时候已经不能评估了。
如图所示
![image](https://user-images.githubusercontent.com/25219834/82962313-727e4000-9ff2-11ea-9e94-0f92194403b5.png)

**Comment by wyc880622** [comment]
> 关于问题3, 再补充下： 是Python预测吗？ 1.2s是CPU预测，还是GPU预测？ 提速的话：
> 
> (1) 从模型角度考虑，可以选择速度较快的模型，比如YOLOv3-DarkNet53, YOLOv3-ResNet34，但精度可能比RCNN+FPN模型精度低。 不同模型速度比较可以参考: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/advanced_tutorials/deploy/BENCHMARK_INFER_cn.md
> 
> (2) 预测库，可以考虑使用 [deploy](https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/deploy) 下面，该预测使用了Paddle的预测引擎加速。
> 
> (3) 最后考虑模型压缩
你好，谢谢你的回答
1.我的显卡是2080Ti 11G显存 内存是64G 预测1.2s是GPU预测，是python的deploy 下的infe.py
2.我现在主要是对精度要求比较高，都能识别出来，最主要不能误识别。
现在主要问题还是如何解决误识别问题。
谢谢

**Comment by jerrywgz** [comment]
对于rcnn模型，我们在server端做过一系列的优化，同时也保证了一定速度，可以参考这个链接，https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/configs/rcnn_enhance，
其中使用了autoaugmentation的数据增广方式，同时还包含了其他一些模块改进。这个链接中的模型都是基于coco数据集进行训练的，你可以直接使用这个模型对任务进行finetune，这是最推荐的方式，迁移学习的相关文档请参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md

关于loss_bbox减到0，可能是rpn阶段没有训好导致的，可以尝试降低学习率或是增大warmup的轮数。

**Comment by ymxcywl** [comment]
我也有这个问题，曾经使用过tensorflow的目标检测api，同样出现了很多误识别的问题，我听从issue里的建议将误识别的样本背景用大框框起来标注成单独的一类作为背景去训练rcnn，loss经常直接爆炸，所以也没成功，不知道paddle 目标检测是如何处理负样本的，请大佬们指教

**Comment by qingqing01** [comment]
@ymxcywl RCNN目前loss爆的问题，目前一般都是通过调节warmup、超参数(如学习率)处理的。
