### ISSUE TITLE
mot_sde_infer.py在使用自己的视频推理时报错，发现报错原因是未对画面中如果无人的情况做处理

### ISSUE THREAD

**Issue by zx377262372** [PaddlePaddle/PaddleDetection#7810]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference

### Bug描述 Describe the Bug

执行
‘’‘
python deploy/pptracking/python/mot_sde_infer.py --model_dir=output_inf
erence/ppyoloe_crn_l_36e_640x640_mot17half/ --reid_model_dir=output_inference/deepsort_pcb_pyramid_r101/ --tracker_config=deploy/pptracking/python/tracker_config.yml  --video_file=E:\test_nameplate\dc-radio1.mp4 --device=GPU --save_mot_txts --threshold=0.5 --skip_frame_num=5 --draw_center_traj --output_dir=./output/deepsort_ppyol
’‘’
报错如下
‘’‘
Traceback (most recent call last):
  File "deploy/pptracking/python/mot_sde_infer.py", line 885, in <module>
    mot_results = self.predict_image(
  File "deploy/pptracking/python/mot_sde_infer.py", line 503, in predict_image
    tracking_outs = self.tracking(det_result)
  File "deploy/pptracking/python/mot_sde_infer.py", line 293, in tracking
    online_targets = self.tracker.update(pred_dets, pred_embs)
  File "E:\python_project2\PaddleDetection-release-2.5\deploy\pptracking\python\mot\tracker\deepsort_tracker.py", line 104, in update
    for tlwh, score, feat, cls_id in zip(pred_tlwhs, pred_scores,
TypeError: 'NoneType' object is not iterable
’‘’
我的视频中存在几秒画面中没有行人的情况，但是换成官方demo视频就可以运行。

### 复现环境 Environment

OS：windows
python：3.8
paddle-detection/release：2.5
cuda：11.6
paddlepaddle：2.4.1
gcc：6.3.0
cudann：8.6

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [x] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zx377262372** [comment]
![image](https://user-images.githubusercontent.com/74412671/220802608-2963f052-c905-4775-898a-6bdaf24bdd0a.png)对mot_sde_infer.py脚本做如上处理就可以运行

**Comment by zhiboniu** [comment]
好的，感谢反馈
