### ISSUE TITLE
paddleDetection使用GPU训练无法正常执行

### ISSUE THREAD

**Issue by heguyu** [PaddlePaddle/PaddleDetection#7817]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

根据官网教程[https://gitee.com/paddlepaddle/PaddleOCR/blob/release/2.6/ppstructure/layout/README_ch.md#https://gitee.com/link?target=https%3A%2F%2Fgithub.com%2Fbuptlihang%2FCDLA](url)
中配置数据集并执行
`python tools/train.py -c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml --eval`
如果使用CPU版的paddle包，这个命令可以正常运行，如下图1
<img width="539" alt="屏幕截图 2023-02-23 141445" src="https://user-images.githubusercontent.com/126142219/220835291-ce704f95-9df0-448d-8fb9-d9bf98478403.png">
但当runtime.yml中use_gpu改为true并安装
`python -m pip install paddlepaddle-gpu==2.4.1 -i https://pypi.tuna.tsinghua.edu.cn/simple`
paddleGPU的版本时则无法正常运行，如下图2
<img width="512" alt="屏幕截图 2023-02-23 140918" src="https://user-images.githubusercontent.com/126142219/220835706-8fbfa1ae-1eae-493f-a516-5af8097bffc1.png">
我安装的cuda版是10.2，如下图3
<img width="506" alt="屏幕截图 2023-02-23 141009" src="https://user-images.githubusercontent.com/126142219/220835770-a992cc8c-19e0-48e0-b35a-878c14c5b040.png">
与其相对应的cudnn版，如下图4
<img width="415" alt="屏幕截图 2023-02-23 141034" src="https://user-images.githubusercontent.com/126142219/220835900-0e0fe754-bbbb-4deb-a2d4-d63ba6e45e60.png">
本机的可支持的cuda版本最高为12，如下图5
<img width="354" alt="屏幕截图 2023-02-23 141250" src="https://user-images.githubusercontent.com/126142219/220837321-ac94b797-43f2-4267-a5c5-0966298625a0.png">
paddleGPU支持配置的安装教程如下
[https://blog.csdn.net/apodx/article/details/123819148](url)
其中也出现 `Could not locate zlibwapi.dll. Please make sure it is in your library path` 缺失问题，也按照如下教程解决
[https://blog.csdn.net/qq_44224801/article/details/125525721](url)
但未安预期结果进行请看图2，还望前辈告知！

**Comment by lyuwenyu** [comment]
开你截图 无法运行指的是直接退出了嘛？

安装paddlepaddle-gpu后 运行`paddle.utils.run_check()`能跑嘛

**Comment by heguyu** [comment]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/126142219/220873063-82e5934c-7fa0-4be7-9497-a3838cf0560e.png">
可以运行

**Comment by heguyu** [comment]
> 开你截图 无法运行指的是直接退出了嘛？
> 
> 安装paddlepaddle-gpu后 运行`paddle.utils.run_check()`能跑嘛

**Comment by lyuwenyu** [comment]
你的报错信息在那 怎么没看到？

**Comment by heguyu** [comment]
> 你的报错信息在那 怎么没看到？

就像图2看到的一样，没有明细的报错信息。像是莫名退出一样

**Comment by heguyu** [comment]
@lyuwenyu 是不是和显卡驱动的版本有关系，太新的不兼容？

**Comment by lyuwenyu** [comment]
有可能吧 现在还有问题嘛， 比如说paddle.2.3.2有问题没

**Comment by EveningLin** [comment]
@lyuwenyu  @thinkthinking  @heguyu  @zhangjun  @ZeyuChen 
 各位解决了吗？ 我的版本是4070ti，CUDA Version是12.1，但是之前为了兼容mmlab使用11.7,然后也是遇到了楼主一样的问题，使用网上的解决方法之后就没有下文了。
![image](https://user-images.githubusercontent.com/110521494/226388072-e6068174-9714-4f4d-89dc-a910758a47ff.png)

**Comment by EveningLin** [comment]
我检查了一下 应该是显存爆了 但是应该是没有提示直接被kill掉了

**Comment by heguyu** [comment]
显存满了确实会终止，batch_size减小会有用，之后我用了CUDA Toolkit工具包解决的

> @lyuwenyu @thinkthinking @heguyu @zhangjun @ZeyuChen 各位解决了吗？ 我的版本是4070ti，CUDA Version是12.1，但是之前为了兼容mmlab使用11.7,然后也是遇到了楼主一样的问题，使用网上的解决方法之后就没有下文了。 ![image](https://user-images.githubusercontent.com/110521494/226388072-e6068174-9714-4f4d-89dc-a910758a47ff.png)

**Comment by achaosss** [comment]
我遇到一样的问题，环境是windows10，cuda11.6，python3.9，cudnn8.+。然后想用use_gpu的时候就遇到了这个问题。
could not locate zlibwapi.dll.Please make sure it is in your library path!

**Comment by EveningLin** [comment]
这个我也遇到过 谷歌一下应该有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月29日(周三) 晚上6:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] paddleDetection使用GPU训练无法正常执行 (Issue #7817)




 
我遇到一样的问题，环境是windows10，cuda11.6，python3.9，cudnn8.+。然后想用use_gpu的时候就遇到了这个问题。
 could not locate zlibwapi.dll.Please make sure it is in your library path!

**Comment by achaosss** [comment]
> 我遇到一样的问题，环境是windows10，cuda11.6，python3.9，cudnn8.+。然后想用use_gpu的时候就遇到了这个问题。 could not locate zlibwapi.dll.Please make sure it is in your library path!

解决了，下载好zlibwapi.dll文件后，放到系统路径上就行
