### ISSUE TITLE
在nvidia gpu上c++ trt部署旋转框模型报错

### ISSUE THREAD

**Issue by ilovefanjian** [PaddlePaddle/PaddleDetection#7824]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在nvidia gpu上c++ trt部署， 启用 TensorRT 进行预测加速
config.EnableTensorRtEngine(1 << 30, 1, 3, paddle_infer::PrecisionType::kFloat32, true, false);
报错：InvalidArgumentError: The input [image] shape of trt subgraphis[-1,3,-1,-1], please enable trt dynamic shape mode by SetTRTDynamicshapeInfo.
改成动态shape时，报错：InvalidArgumentError:some trt inputs dynamic shape info not set,check the INFO log above for more details.

**Comment by nemonameless** [comment]
为便于排查，报错请按模板提问谢谢
https://github.com/PaddlePaddle/PaddleDetection/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml

**Comment by wangxinxin08** [comment]
使用Paddle-TRT需要下载PaddlePaddle develop版本，并保证TensorRT版本大于8.2
