### ISSUE TITLE
在nvidia nano上c++ trt部署旋转框模型报错

### ISSUE THREAD

**Issue by ilovefanjian** [PaddlePaddle/PaddleDetection#7825]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference

### Bug描述 Describe the Bug

在Jetson Nano上使用c++部署，当旋转框模型被 Paddle Inference 加载后，使用trt 
config.EnableTensorRtEngine(1 << 30, 1, 3, paddle_infer::PrecisionType::kFloat32, true, false);
报错：’‘’InvalidArgumentError: The input [image] shape of trt subgraphis[-1,3,-1,-1], please enable trt dynamic shape mode by SetTRTDynamicshapeInfo.‘’‘
改成动态shape后，min_input_shape = {"image":[1,3, 10, 10]}
	                       max_input_shape = {"image":[1,3, 224, 224]}
	                       opt_input_shape = {"image":[1,3, 100, 100]}
                               config.set_trt_dynamic_shape_info(min_input_shape, max_input_shape, opt_input_shape)
报错：’‘’InvalidArgumentError:some trt inputs dynamic shape info not set,check the INFO log above for more details.‘’‘

### 复现环境 Environment

jetson nano

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
使用Paddle-TRT需要下载PaddlePaddle develop版本，并保证TensorRT版本大于8.2，文档中有说明

**Comment by ilovefanjian** [comment]
矩形框模型能正常部署，换成旋转框的报错

**Comment by ilovefanjian** [comment]
矩形框模型能正常部署，换成旋转框的报错

**Comment by wangxinxin08** [comment]
看文档，矩形框没有版本要求，旋转框标明了：需要PaddlePaddle develop版本，并且保证TensorRT版本大于8.2

**Comment by ilovefanjian** [comment]
用的paddleinference进行的模型推理部署，各项版本也符合要求

**Comment by wangxinxin08** [comment]
根据报错提示，你的TensorRT版本应该不符合要求，另外，导出模型请严格遵循文档，不要乱改。出现这种报错的两个原因：
1. TensorRT版本不对
2. 在运行TensorRT模式时，没有按照文档导出模型，没有加`trt=True`
