### ISSUE TITLE
训练结果可视化

### ISSUE THREAD

**Issue by haoaZ** [PaddlePaddle/PaddleDetection#7826]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问ppyoloe-sod训练结束后没有可视化的训练效果图么类似于下面这种
![results](https://user-images.githubusercontent.com/113076135/221135532-4b93c4d6-aec1-4d4b-a5ec-5849a89e3815.png)

**Comment by nemonameless** [comment]
训练命令后加`--use_vdl=True`，参照 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/docs/tutorials/GETTING_STARTED_cn.md#7-%E8%AE%AD%E7%BB%83%E5%8F%AF%E8%A7%86%E5%8C%96

https://github.com/PaddlePaddle/VisualDL
