### ISSUE TITLE
pphuman解析rtsp视频流有逻辑问题

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/PaddleDetection#7827]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

pphuman解析rtsp视频流有两个问题
1 读取的视频的帧都放到队列里，循环终止条件是while (not framequeue.empty()):这里有问题，经测试，在解析视频流时，如果长时间没有检测到物体，消耗队列帧的速度会比读取帧的速度要快，导致队列被消耗空，最终导致whlie提前终止，此时视频流并未结束。这里的判断逻辑应该是
while(1):            
    if framequeue.empty():
        continue //或者wait
2 主线程如果出现异常，主线程结束，但是视频流读取到队列的子现场并未终止，还在持续运行，该子线程应该有通知机制，可以终止该子线程

### 复现环境 Environment

windows10操作系统
paddle2.4
paddledetection develop
python 3.9

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
感谢反馈，请问你这样修改以后程序执行效果是否有明显变化呢？这里修改前后我的测试并没有明显的变化，
而且我测试过程中感觉视频流读取的速度应该是很快的

**Comment by truthsun22** [comment]
> 感谢反馈，请问你这样修改以后程序执行效果是否有明显变化呢？这里修改前后我的测试并没有明显的变化， 而且我测试过程中感觉视频流读取的速度应该是很快的

我的意思是并不是速度快慢，而是rtsp视频流并未结束，检测帧的while循环却提前终止了。造成这种问题的原因是，检测帧的速度太快，尤其是当没有检测到物体时，而读取视频流的速度比检测反而要慢，造成队列为空，检测while提前终止

**Comment by zhiboniu** [comment]
明白，请问你做修改之后使用效果有明显改善了吗？

**Comment by truthsun22** [comment]
> 明白，请问你做修改之后使用效果有明显改善了吗？

是的，主线程循环这样改
            while capture.isOpened():
                if framequeue.empty():
                    time.sleep(0.1)
                    continue
然后主线程关闭想要子线程也关闭，在创建读取视频流子线程时加上daemon=True参数即可

**Comment by zhiboniu** [comment]
好的，我们试一下

**Comment by Chenkeyi43** [comment]
其实我很不理解这个 队列的作用有什么用，索性直接放到主线程去读取不就得了

**Comment by DoctorDream** [comment]
> 其实我很不理解这个 队列的作用有什么用，索性直接放到主线程去读取不就得了

我尝试读了一下代码，可能是想实现视频帧的多线程预加载功能吧，但是感觉有点bug，多线程变单线程
