### ISSUE TITLE
Layout pretrain_weights wrong inference.

### ISSUE THREAD

**Issue by TapendraBaduwal** [PaddlePaddle/PaddleDetection#7828]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

Wrong inference result by pretrained model

!python3 tools/infer.py \
    -c configs/picodet/legacy_model/application/layout_analysis/picodet_lcnet_x1_0_layout.yml \
    -o weights=https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_cdla.pdparams \
    --infer_img=./dataset/publaynet/train/train/88965554-img4.jpg \
    --output_dir=output_dir/ \
    --draw_threshold=0.5

![88965554-img4](https://user-images.githubusercontent.com/87867535/221148941-09ac74eb-a1f6-409d-ab01-c3ba10537f02.jpg)

### 复现环境 Environment

paddlepaddle-gpu==2.3

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by thinkthinking** [comment]
@TapendraBaduwal 您好，这个属于PaddleOCR的模型，需要去[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)的issue区进行提问。
