### ISSUE TITLE
评估模型时报错 ValueError: not enough values to unpack (expected 6, got 1)

### ISSUE THREAD

**Issue by qjing666** [PaddlePaddle/PaddleDetection#783]
在运行 python tools/eval.py 时报错
<img width="921" alt="截屏2020-05-26下午5 37 54" src="https://user-images.githubusercontent.com/19721227/82885512-da437500-9f77-11ea-857b-7c7449c22ae9.png">

打印出bbox中的b为 [-1. ]

请问这个错误是因为模型训练不够导致的么还是因为模型保存下来出错呢？

**Comment by jerrywgz** [comment]
想问下你用的是什么模型训练的呢，可能是预测出来的结果为空导致的

**Comment by qjing666** [comment]
用的是faster_rcnn，我再多跑几轮试试吧

**Comment by jerrywgz** [comment]
好的，还有疑问的话可以再发下配置文件

**Comment by qjing666** [comment]
确实是因为训练的不够，已经验证完毕~
