### ISSUE TITLE
python setup.py install 干了什么事情，不装有什么影响？

### ISSUE THREAD

**Issue by gaohuayang** [PaddlePaddle/PaddleDetection#7830]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PaddleDetection安装文档中写到：
# 编译安装paddledet
python setup.py install

在AiStudio安装PaddleDetection时，需要编译安装paddledet吗？
不装似乎也能跑起来，有什么影响吗？

**Comment by ghostxsl** [comment]
install可以安装到你的python环境下，更方便使用

**Comment by truthsun22** [comment]
同问，文档里说从conda或pip就可以安装环境了，那setup.py install是干嘛用的？

**Comment by ghostxsl** [comment]
> 同问，文档里说从conda或pip就可以安装环境了，那setup.py install是干嘛用的？

源码编译安装

**Comment by gaohuayang** [comment]
> 

老师，可以详细说说吗？比如安装和不安装，二者在使用上的区别、对训练的影响、方便在哪些方面等等，感谢

**Comment by ghostxsl** [comment]
你看的文档是哪个文档？

**Comment by ghostxsl** [comment]
首先，对于`python setup.py install`这种编译安装的方式来说，你可简单的理解成把当前的代码打包一下放到你的python或者conda环境下，这样你如果想基于paddledet做二次开发的话，可以在你自己的代码里直接import paddledet来去做开发。如果你仅仅只是把paddledet当作训练评估的工具来使用的话，其实安装和不安装都无所谓，因为这并不影响你的使用。
其次，如果你不是基于paddledet做二次开发，而是作为开发者去修改paddledet的源码的话，由于源码改动只会影响你本地的代码，所以你需要卸载掉你python或者conda环境里的paddledet，重新`python setup.py install`来应用你的更新。
