### ISSUE TITLE
关于backbone返回特征图的疑问

### ISSUE THREAD

**Issue by smallVehicel** [PaddlePaddle/PaddleDetection#7836]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在调试ppyoloe模型源码发现，网络中backbone模块最终产生4个特征图，配置默认返回的特征图id为 return_idx=[1,2,3]
但是在论文中展示的网络结构图显示，backbone产生的C3,C4,C5特征图传入neck模块
我在读论文时，最开始认为是backbone产生5个特征图，返回后三个，其实应该是返回4个特征图中的后三个，是这样吗？

**Comment by nemonameless** [comment]
ppyoloe 的 backbone就是输出3层，就是C3,C4,C5也叫做res3 4 5，就是return_idx=[1,2,3]，起始index 0表示res2。5层的意思是stem+res2 3 4 5，stem一般是不会输出特征层的。

**Comment by smallVehicel** [comment]
> 
原来如此，5层的意思是stem+res2 3 4 5
很感谢您的解答，谢谢！

**Comment by smallVehicel** [comment]
> ppyoloe 的 backbone就是输出3层，就是C3,C4,C5也叫做res3 4 5，就是return_idx=[1,2,3]，起始index 0表示res2。5层的意思是stem+res2 3 4 5，stem一般是不会输出特征层的。

原来如此，5层的意思是stem+res2 3 4 5
很感谢您的解答，谢谢！
