### ISSUE TITLE
COCO dataset中的bug

### ISSUE THREAD

**Issue by Asthestarsfalll** [PaddlePaddle/PaddleDetection#7837]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

DataProcess

### Bug描述 Describe the Bug

https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/data/source/coco.py#L184-L196
bboxes在第一次pop之后，后续的pop都会有问题的吧？

### 复现环境 Environment

...

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
不是bug。可自己打印看看

**Comment by Asthestarsfalll** [comment]
```python
box = list(range(0, 10))
for i, b in enumerate(box):
    if b < 5:
        box.pop(i)    
```
期望的结果是5-9，实际结果是1, 3, 5, 6, 7, 8, 9
