### ISSUE TITLE
PPYOLOE C++部署 行人追踪 region_type region_polygon 参数设置

### ISSUE THREAD

**Issue by chccc1994** [PaddlePaddle/PaddleDetection#7843]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

 [PP-Human检测跟踪模块](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/pipeline/docs/tutorials/pphuman_mot.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)中可以实现`Python`推理设置 `region_type` `region_polygon `区域的类型和坐标，但是`C++`推理部署时怎么实现？？？ 

```python
python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_pphuman.yml \
                                                   --video_file=test_video.mp4 \
                                                   --device=gpu \
                                                   --draw_center_traj \
                                                   --do_break_in_counting \
                                                   --region_type=custom \
                                                   --region_polygon 200 200 400 200 300 400 100 400
```

**Comment by zhiboniu** [comment]
是说想在c++中实现类似功能，怎么传参吗？可以用str替代，读入后解析转换

**Comment by chccc1994** [comment]
> 是说想在c++中实现类似功能，怎么传参吗？可以用str替代，读入后解析转换

是的，有没有类似功能，传参进去之后，可以在图像或者视频上显示设定区域跟踪或者检测结果。

**Comment by zhiboniu** [comment]
目前pipeline没有实现c++版本，需要自己实现一下
