### ISSUE TITLE
关于deformable detr复现map低的请教

### ISSUE THREAD

**Issue by heng3366** [PaddlePaddle/PaddleDetection#7848]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

detr，用预训练权重，超参数没改，单卡训练一个50epoch，最终map只有十几，第一个peochmap只有3，请问是需要继续训练，还是需要调整lr之类的

**Comment by nemonameless** [comment]
是训的coco数据集还是自己的数据集？总bs只有2？那太小了没有必要训，默认总bs=16，如果资源不够用建议减小reader里的尺度，或根据总bs按线性比例调整lr
