### ISSUE TITLE
Paddledetection安装依赖时卡住

### ISSUE THREAD

**Issue by rzqiu** [PaddlePaddle/PaddleDetection#7849]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

之前一直都正常，不知道为什么从某一次打开开始一直都会卡在这一步，无法安装依赖。试着更换了清华源也不行。期待解答！
![image](https://user-images.githubusercontent.com/93416725/222085701-d088cdc2-ba7f-46b2-abb8-29c407792d58.png)
![image](https://user-images.githubusercontent.com/93416725/222085738-96c5f24e-5435-4bf4-bbbb-15d082cb6b70.png)

**Comment by wangxinxin08** [comment]
直接pip install opencv-python -i https://pip.baidu-int.com/simple/ 试下看看

**Comment by rzqiu** [comment]
> 直接pip install opencv-python -i https://pip.baidu-int.com/simple/ 试下看看

显示已经满足需求，请问是不是证明不用管之前的报错，直接继续就行了呢？
![image](https://user-images.githubusercontent.com/93416725/222105227-8b3e1e8d-7560-4b2c-939a-20df234976cf.png)

**Comment by wangxinxin08** [comment]
那应该没问题，你再跑一写pip install -r requirements.txt试下还报错吗？只要requirements.txt依赖都装上了就没问题

**Comment by rzqiu** [comment]
好的，可以成功安装，谢谢！
