### ISSUE TITLE
如何获取单帧图片预测结果？

### ISSUE THREAD

**Issue by LLsmile** [PaddlePaddle/PaddleDetection#7850]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我的数据集是完整图片， 但是识别的时候需要裁剪roi进行推理，然后把识别结果映射回原图。目前默认的tools/infer.py好像封装的有点严重，没法裁图？只能原图推理？

**Comment by wangxinxin08** [comment]
试一下--slice_infer这个flag，这个应该可以满足你的要求

**Comment by LLsmile** [comment]
我的输入是一张图的某个roi区域，而且roi区域（标注的roi）会变动，直接slice固定尺寸好像不太对，我就纯粹想实现一个直接输入图片数据，输出模型结果的功能。因为我这边输入需要裁图，输出需要映射，所以不能输入图片名。
