### ISSUE TITLE
ppyoloe-plus-tiny模型的蒸馏问题

### ISSUE THREAD

**Issue by xywlpo** [PaddlePaddle/PaddleDetection#7852]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我想用ppyoloe-plus-x蒸馏ppyoloe-plus-t的模型
目前看到只支持PPYOLOE的结构进行蒸馏，ppyoloe-tiny无法使用PPYOLOEWithAuxHead结构加载。如果去掉aux_head: SimpleConvHead的话是可以正常跑蒸馏的，我仍有一些问题：
1、如果不加aux_head头的话去蒸馏是否可能还不如使用该头直接训练呢？
2、这个头具体是用来干什么的呢？是只在训练的时候辅助训练，但是最后推理的时候不使用吗？
3、如果要使用这个辅助头，直接使用PaddleSlim是否可以保留这个头去蒸馏？
4、是否可以在训练时候同时蒸馏+int8量化？应该怎么配置？
![image](https://user-images.githubusercontent.com/728405/222134542-3ba9dff5-c10c-4be9-b3bc-47cefeaece39.png)

**Comment by lyuwenyu** [comment]
AuxHead只是训练时候会用到 推理不用的，量化参考这里 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.6/deploy/auto_compression
