### ISSUE TITLE
如何目标检测抠出大类，再送入分类网络分出小类，再进行部署

### ISSUE THREAD

**Issue by Wangyibo321** [PaddlePaddle/PaddleDetection#7854]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

比如说先用一个目标检测网络抠出一张图里面的所有狗，再对每只狗送入分类网络进行细分类，最后输出结果。两个模型怎么拼接起来并部署。因为我要分类的物体很相似，光用一个网络无法很好完成任务。

**Comment by lyuwenyu** [comment]
nms的结果出来之后 -> 原图去crop -> 送到你的分类网络   这样？
