### ISSUE TITLE
什么时候也来个特征图可视化

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#7855]
### 问题描述 Please describe your issue

https://github.com/open-mmlab/mmyolo/blob/main/docs/zh_cn/user_guides/visualization.md

隔壁的这个 特征图可视化
看起来不错

**Comment by nemonameless** [comment]
已经支持了
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/docs/tutorials/GradCAM_cn.md
