### ISSUE TITLE
pptracking C++ 编译到100%报错

### ISSUE THREAD

**Issue by cheng-yue-cpu** [PaddlePaddle/PaddleDetection#7858]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

[ 77%] Building CXX object CMakeFiles/main.dir/src/tracker.cc.o
[ 83%] Building CXX object CMakeFiles/main.dir/src/trajectory.cc.o
[ 88%] Building CXX object CMakeFiles/main.dir/src/lapjv.cpp.o
[ 94%] Building CXX object CMakeFiles/main.dir/src/postprocess.cc.o
[100%] Linking CXX executable main
/usr/local/bin/ld: warning: libonnxruntime.so.1.11.1, needed by /data/paddle_inference/paddle/lib/libpaddle_inference.so, not found (try using -rpath or -rpath-link)
/usr/local/bin/ld: warning: libpaddle2onnx.so.1.0.0rc2, needed by /data/paddle_inference/paddle/lib/libpaddle_inference.so, not found (try using -rpath or -rpath-link)
/data/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `paddle2onnx::IsExportable(void const*, int, void const*, int, int, bool, bool, bool, bool, bool, paddle2onnx::CustomOp*, int, char const*)'
/data/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `paddle2onnx::Export(void const*, int, voidconst*, int, char**, int*, int, bool, bool, bool, bool, bool, paddle2onnx::CustomOp*, int, char const*)'
/data/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `OrtGetApiBase@VERS_1.11.1'
/data/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `paddle2onnx::IsExportable(char const*, char const*, int, bool, bool, bool, bool, bool, paddle2onnx::CustomOp*, int, char const*)'
/data/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `paddle2onnx::Export(char const*, char const*, char**, int*, int, bool, bool, bool, bool, bool, paddle2onnx::CustomOp*, int, char const*)'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:224: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
make finished!

cuda 10.2
cudnn 8.1
gcc 8.2

**Comment by nemonameless** [comment]
paddle_inference [C++预测库下载列表](https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html)下载的版本对吗

**Comment by jiangjiajun** [comment]
是下载的预编译库吗？还是自己编译的FastDeploy啊
