### ISSUE TITLE
各位百度大佬，车辆检测的数据集能不能提供呢？

### ISSUE THREAD

**Issue by yangbisheng2009** [PaddlePaddle/PaddleDetection#786]

**Comment by jerrywgz** [comment]
这个是内部业务数据集，不太方便提供

**Comment by yangbisheng2009** [comment]
![3](https://user-images.githubusercontent.com/17609763/82974098-b9c4fa80-a00b-11ea-8a2a-f230eaf256a6.jpg)
明白，那请教下，训练集里面有没有这种类似数据。非常密集的车辆（堵车状态）

**Comment by yangbisheng2009** [comment]
![1](https://user-images.githubusercontent.com/17609763/82974173-e8db6c00-a00b-11ea-87fd-6e369c323ab8.jpg)
还有这种

**Comment by jerrywgz** [comment]
我们这边的数据集中没有特别针对密集的场景，可以用现有模型尝试下效果～

**Comment by yangbisheng2009** [comment]
https://www.dcjingsai.com/common/cmpt/%E4%BA%A4%E9%80%9A%E5%8D%A1%E5%8F%A3%E8%BD%A6%E8%BE%86%E4%BF%A1%E6%81%AF%E7%B2%BE%E5%87%86%E8%AF%86%E5%88%AB_%E8%B5%9B%E4%BD%93%E4%B8%8E%E6%95%B0%E6%8D%AE.html

我用的这个比赛的数据集（没有上两张图片那么密集，最多也就是十辆二十辆），也是交通路口的真实图像。fasterrcnn训练，但是对识别这种密集的情况，效果不算太好

**Comment by yangbisheng2009** [comment]
> 我们这边的数据集中没有特别针对密集的场景，可以用现有模型尝试下效果～

我先试试吧，以前一直用pytorch
这几天看了下padle，发现实用性真的太高了，马老师牛逼
