### ISSUE TITLE
xdm，我想问如果我想改paddleDetection的模型，是直接在源文件上改就行吗？可以加好友,可有偿

### ISSUE THREAD

**Issue by Zhw1997** [PaddlePaddle/PaddleDetection#7862]
### 问题描述 Please describe your issue

xdm，我想问如果我想改paddleDetection的模型，是直接在源文件上改就行吗？想用来发论文，所以想知道大家是怎么用的，如果有人可以教教我的话，可以有偿，但是因为是学生，所以钱不是很多请见谅！我的Q:1015909077

**Comment by nemonameless** [comment]
可以参考文档，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/docs/advanced_tutorials/MODEL_TECHNICAL.md

群公告
🎊学习大礼包
链接: https://pan.baidu.com/s/1P54C9wQAge5yYJwHqH988g 
提取码: bfc5  

🎊直播课录播链接
https://aistudio.baidu.com/aistudio/education/group/info/23670

🎊如果对您的工作有帮助，您的Star是对我们最大的鼓励！
https://github.com/PaddlePaddle/PaddleDetection
