### ISSUE TITLE
请问评估时如何输出所有类别的PR值和PR曲线

### ISSUE THREAD

**Issue by Dekadenc** [PaddlePaddle/PaddleDetection#7864]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如何输出模型整体的PR值呀，评估时添加--classwise只能输出单类的PR曲线，PR值输出看了一个同学的issue：https://github.com/PaddlePaddle/PaddleDetection/issues/2718，但是输出的也是单类的PR值
咱们是否考虑添加以上两个功能 可以输出所有类别的PR曲线和PR值呢，我相信很多同学都很需要这个功能的

**Comment by nemonameless** [comment]
谢谢建议，会考虑排期安排的。

**Comment by thinkthinking** [comment]
@Dekadenc 已将该feature需求合并到Roadmap of PaddleDetection #7892
