### ISSUE TITLE
In PaddleDetection which model is best for Television advertisement detection?

### ISSUE THREAD

**Issue by TapendraBaduwal** [PaddlePaddle/PaddleDetection#7866]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

In PaddleDetection which model is best for Television advertisement detection?

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by ghostxsl** [comment]
you can try PP-YOLOE: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/configs/ppyoloe/README.md
