### ISSUE TITLE
Padding Images in the training and inference

### ISSUE THREAD

**Issue by bely66** [PaddlePaddle/PaddleDetection#7867]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

I'm training the picodet model and I'm trying to pad images so that the shortest side is padded to match the long side before I input them to the model in training and inference
Because image contents gets distorted if you didn't
here's the current configuration:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/29528270/222792527-5f2ffdef-46d6-4ffe-b026-8ca3ff2dd384.png">

I'm assuming keep_ratio has something to do with it, however I checked the operators code and found that it changes the input ratio however it doesn't pad

So what should be changed so that the images are padded?

**Comment by ghostxsl** [comment]
you can use `Pad`, like: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/configs/yolox/_base_/yolox_reader.yml#L31
