### ISSUE TITLE
导出PP-YOLOE+在 Objects365数据集模型 配置文件中的类别不对

### ISSUE THREAD

**Issue by shnn98** [PaddlePaddle/PaddleDetection#7868]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

导出PP-YOLOE+在 Objects365数据集模型 配置文件类别不对，只有80类，请问正确的类别在哪里找

**Comment by nemonameless** [comment]
http://www.objects365.org/overview.html 可下载 zhiyuan_objv2_val.json 以获取种类。
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/configs/datasets/objects365_detection.yml#L20

**Comment by shnn98** [comment]
找到了
