### ISSUE TITLE
目标检测热力图，使用文档中的命令，但是报错AttributeError: 'NoneType' object has no attribute 'squeeze'

### ISSUE THREAD

**Issue by Petal99** [PaddlePaddle/PaddleDetection#7869]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

目标检测热力图，使用文档中的命令：
`python tools/cam_ppdet.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml --infer_img demo/000000014439.jpg --cam_out cam_ppyoloe --target_feature_layer_name model.backbone -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_300e_coco.pdparams，`
但是报错AttributeError: 'NoneType' object has no attribute 'squeeze'
位置在cam_utils.py", line 281, in get_bboxes_cams    -1].grad.squeeze().cpu().numpy()

环境为：

1. Win10
2. paddlepaddle-gpu = 2.4.1.post116
3. Paddledetection = 2.6

**Comment by xs1997zju** [comment]
Have u change any code in ppdet-release2.6?, It run successfully for me on linux machine with paddle-2.3

**Comment by nemonameless** [comment]
please try paddlepaddle-2.3

**Comment by Petal99** [comment]
> please try paddlepaddle-2.3

谢谢，paddle-2.3版本没有出现这个问题，看来是2.4版本的bug😀
