### ISSUE TITLE
关于PPhuman中STGCN识别多种行为类别的问题

### ISSUE THREAD

**Issue by HNU-DC** [PaddlePaddle/PaddleDetection#7871]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好我已参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/advanced_tutorials/customization/action_recognotion/skeletonbased_rec.md关于新增行为的教程，但是遇到问题首先采用det_keypoint_unite_infer.py可以获得多个视频的json格式检测结果文件，然后教程中描述采用prepare_dataset.py可以将上述的多个json文件转化为训练数据即得到了可用的训练数据（.npy）和对应的标注文件（.pkl）。但是prepare_dataset.py中采用如下代码给json文件对应标签，目前该代码只能将所有的json文件均对应标签0，教程中这样描述上述包含摔倒的动作是正样本，在实际训练中也需要一些其他的动作或正常站立等作为负样本，步骤同上，但注意label的类型取1。所以对此有疑问，第一在制作多分类行为数据集时，应该如何改写来生成包含多种行为类别的训练数据（.npy）和对应的标注文件（.pkl），第二如果按照教程描述，是否是要求对每一类别运行一次prepare_dataset.py，那么最后如何融合多个训练数据（.npy）和对应的标注文件（.pkl）
   for i, path in enumerate(os.listdir("annotations")):
        video_anno, score = decode_json_path(os.path.join("annotations", path))
        all_labels[0].append(str(i))
        all_labels[1].append(0)  #label 0 means falling
        all_scores.append(score)

**Comment by blueWall8** [comment]
我目前有以下想法，还未验证可行性： 

        if __name__ == '__main__':
            all_keypoints = []
            all_labels = [[], []]
            all_scores = []
            for i, path in enumerate(os.listdir("annotations")):
                video_anno, score = decode_json_path(os.path.join("annotations", path))
                all_keypoints.append(video_anno)
                all_labels[0].append(str(i))
                all_labels[1].append(0)  #label 0 means falling
                all_scores.append(score)
            all_data = np.stack(all_keypoints, 0)
            all_score_data = np.stack(all_scores, 0)
            np.save(f"train_data.npy", all_data)
            pickle.dump(all_labels, open(f"train_label.pkl", "wb"))
            np.save("kptscore_data.npy", all_score_data)

基于以上代码，由于data 和label都是先暂存在列表或字典中，那么可以修改代码：先处理lable=0的数据，再追加lable=1的数据，这样all_keypoints和all_labels就包含了lable=0,1的数据了，然后再存为.npy和.pkl文件。

基于这个想法，将两个类别的json文件放在不同路径；需要写两个for循环，从不同路径读取json；经过两个for循环的处理，就得到拼接的all_keypoints 和all_labels 了，然后再存为.npy和.pkl文件即可。

可以先试试这个方法，若成功了或者有其他idea请交流交流。

**Comment by zhiboniu** [comment]
这里是摔倒的一个示例，实际你可以根据自己的行为分类修改label。当然执行一次prepare_dataset.py就够了，你可以使用脚本获取你分好的种类，然后把这个类别赋值给label就行了。

**Comment by blueWall8** [comment]
> 这里是摔倒的一个示例，实际你可以根据自己的行为分类修改label。当然执行一次prepare_dataset.py就够了，你可以使用脚本获取你分好的种类，然后把这个类别赋值给label就行了。
以摔倒为例，请问摔倒和其他动作的训练比例应该是多少呢？
