### ISSUE TITLE
关于同时集成行人属性/特征识别和行人跟踪的方案

### ISSUE THREAD

**Issue by MontaEllis** [PaddlePaddle/PaddleDetection#7872]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

不知道能不能读行人属性和行人跟踪两个模型同时推理？有这方面的资料不

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/pipeline 多任务同时做也可以的
