### ISSUE TITLE
关于STGCN新增动作中训练数据的准备

### ISSUE THREAD

**Issue by blueWall8** [PaddlePaddle/PaddleDetection#7873]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

目前用单个json文件生成的.npl和.kpl文件进行训练做试验，但遇到了问题，请问是什么原因，以下是报错信息：
File "main.py", line 138, in main
    profiler_options=args.profiler_options)
File "D:\code_tools\python_all\py_projects_path\PaddleVideo-develop\paddlevideo\tasks\train.py", line 287, in train_model
    record_list["batch_time"].sum)
ZeroDivisionError: division by zero

**Comment by blueWall8** [comment]
> ### 问题确认 Search before asking
> 
>     * [x]  我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> 
> 
> ### 请提出你的问题 Please ask your question
> 
> 目前用单个json文件生成的.npl和.kpl文件进行训练做试验，但遇到了问题，请问是什么原因，以下是报错信息： File "main.py", line 138, in main profiler_options=args.profiler_options) File "D:\code_tools\python_all\py_projects_path\PaddleVideo-develop\paddlevideo\tasks\train.py", line 287, in train_model record_list["batch_time"].sum) ZeroDivisionError: division by zero

解决了，是数据太少了，需要把bath_size调小

**Comment by HNU-DC** [comment]
您好请问下你已经实现了制作多种行为的stgcn数据集了吗可以分享下经验吗谢谢

**Comment by blueWall8** [comment]
> 您好请问下你已经实现了制作多种行为的stgcn数据集了吗可以分享下经验吗谢谢

我也在探索，现在用脚本生成的lable都为0，如何设置其他动作的lable=1，2，3...

**Comment by blueWall8** [comment]
> 您好请问下你已经实现了制作多种行为的stgcn数据集了吗可以分享下经验吗谢谢

我目前有以下想法，还未验证可行性：

if __name__ == '__main__':
    all_keypoints = []
    all_labels = [[], []]
    all_scores = []
    for i, path in enumerate(os.listdir("annotations")):
        video_anno, score = decode_json_path(os.path.join("annotations", path))

        all_keypoints.append(video_anno)
        all_labels[0].append(str(i))
        all_labels[1].append(0)  #label 0 means falling
        all_scores.append(score)
    all_data = np.stack(all_keypoints, 0)
    all_score_data = np.stack(all_scores, 0)
    np.save(f"train_data.npy", all_data)
    pickle.dump(all_labels, open(f"train_label.pkl", "wb"))
    np.save("kptscore_data.npy", all_score_data)

       基于以上代码，由于data 和label都是先暂存在列表或字典中，那么可以修改代码：先处理lable=0的数据，再追加lable=1的数据，这样all_keypoints和all_labels就包含了lable=0,1的数据了，然后再存为.npy和.pkl文件。
       基于这个想法，将两个类别的json文件放在不同路径；需要写两个for循环，从不同路径读取json；经过两个for循环的处理，就得到拼接的all_keypoints 和all_labels 了，然后再存为.npy和.pkl文件即可。

可以先试试这个方法，若成功了或者有其他idea请交流交流。
