### ISSUE TITLE
PPYOLOE-s训练自己的数据集，总共15万张图片，验证集7000多张，FPS只有37左右，怎么这么低呢

### ISSUE THREAD

**Issue by 11140045** [PaddlePaddle/PaddleDetection#7874]
### 问题描述 Please describe your issue

PP-YOLO-s 使用的是300epoch的对应那个模型进行训练，乌第50epoch的结果如下，之后继续训练mAP没有更高的了，第88个epochmAP才0.3多，FPS官方给出的是一百的，为什么我的这么少啊
Average Precision  (AP) @[ IoU=0.50:0.95 \| area=   all \| maxDets=100 ] | 0.443 | 0.448 | 0.452 | 0.455 | 0.456 | 0.457
Average Precision  (AP) @[ IoU=0.50      \| area=   all \| maxDets=100 ] | 0.57 | 0.575 | 0.579 | 0.582 | 0.583 | 0.586
Average Precision  (AP) @[ IoU=0.75      \| area=   all \| maxDets=100 ] | 0.474 | 0.478 | 0.482 | 0.485 | 0.487 | 0.488
Average Precision  (AP) @[ IoU=0.50:0.95 \| area= small \| maxDets=100 ] | 0.15 | 0.158 | 0.163 | 0.166 | 0.161 | 0.169
Average Precision  (AP) @[ IoU=0.50:0.95 \| area=medium \| maxDets=100 ] | 0.371 | 0.376 | 0.382 | 0.383 | 0.385 | 0.384
Average Precision  (AP) @[ IoU=0.50:0.95 \| area= large \| maxDets=100 ] | 0.563 | 0.568 | 0.573 | 0.576 | 0.579 | 0.58
Average Recall     (AR) @[ IoU=0.50:0.95 \| area=   all \| maxDets=  1 ] | 0.437 | 0.438 | 0.442 | 0.445 | 0.443 | 0.443
Average Recall     (AR) @[ IoU=0.50:0.95 \| area=   all \| maxDets= 10 ] | 0.647 | 0.651 | 0.653 | 0.656 | 0.657 | 0.655
Average Recall     (AR) @[ IoU=0.50:0.95 \| area=   all \| maxDets=100 ] | 0.688 | 0.69 | 0.692 | 0.695 | 0.695 | 0.693
Average Recall     (AR) @[ IoU=0.50:0.95 \| area= small \| maxDets=100 ] | 0.462 | 0.47 | 0.471 | 0.467 | 0.47 | 0.468
Average Recall     (AR) @[ IoU=0.50:0.95 \| area=medium \| maxDets=100 ] | 0.658 | 0.662 | 0.665 | 0.666 | 0.668 | 0.665
Average Recall     (AR) @[ IoU=0.50:0.95 \| area= large \| maxDets=100 ] | 0.786 | 0.787 | 0.788 | 0.793 | 0.791 | 0.79
Total sample number | 7108 | 7108 | 7108 | 7108 | 7108 | 7108
averge FPS | 35.41968474 | 36.90456987 | 36.71885978 | 37.01660273 | 37.17134034 | 37.52105432

**Comment by nemonameless** [comment]
训练需要加载coco或obj365预训练，参考 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.6/configs/ppyoloe/application
FPS需要看机器环境，和是否带nms后处理。

**Comment by 11140045** [comment]
好的，谢谢
