### ISSUE TITLE
目标跟踪算法怎么把检测到的目标crop出来

### ISSUE THREAD

**Issue by liangchen341** [PaddlePaddle/PaddleDetection#7876]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

小白一枚，想请教一下怎么把目标跟踪算法中检测到的目标(人)裁剪下来，保存成图片，不胜感激！

**Comment by hs4601** [comment]
是的哦，同问

**Comment by nemonameless** [comment]
可以改这里， https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/ppdet/modeling/mot/utils.py#L147  注意区分单类或多类，可以模仿 plot_tracking 或 plot_tracking_dict 函数 把结果框画上去的过程，抽出来就行。
也可以得到txt形式的跟踪结果后，去根据结果抠出来对应框的图片

**Comment by liangchen341** [comment]
> 可以改这里， https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/ppdet/modeling/mot/utils.py#L147 注意区分单类或多类，可以模仿 plot_tracking 或 plot_tracking_dict 函数 把结果框画上去的过程，抽出来就行。 也可以得到txt形式的跟踪结果后，去根据结果抠出来对应框的图片

谢谢！

**Comment by thinkthinking** [comment]
@liangchen341 根据回复判断该issue已经解决，故先close，如果未解决可以reopen，非常感谢！
