### ISSUE TITLE
paddle单机双卡训练报错

### ISSUE THREAD

**Issue by AIwang666** [PaddlePaddle/PaddleDetection#7879]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

使用单机双卡训练 只能看见一块卡 另一块卡不能在命令行调用
![image](https://user-images.githubusercontent.com/56247915/223084556-4663f37d-a0d7-42eb-9168-b3392e1eef59.png)

### 复现环境 Environment

paddledection-2.6
cuda-11.8
cudnn-8.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
看起来是环境安装问题，win上请安装最新paddle版本试试 
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
