### ISSUE TITLE
关于STGCN新增动作时的lable设置

### ISSUE THREAD

**Issue by blueWall8** [PaddlePaddle/PaddleDetection#7882]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

https://github.com/PaddlePaddle/PaddleVideo/tree/develop/applications/PPHuman
该文档中以摔倒检测举例，在训练时正样本（摔倒）的lable=0，数据集里有负样本（其他动作或站立），且负样本应设置lable=1。请问在使用官方脚本生成训练文件的前提下，怎么把lable设置为1？

**Comment by blueWall8** [comment]
改写prepare_dataset.py的部分代码：

`if __name__ == '__main__':
    all_keypoints = []
    all_labels = [[], []]
    all_scores = []
    for i, path in enumerate(os.listdir("annotations_test_pos")):
        video_anno, score = decode_json_path(os.path.join("annotations_test_pos", path))

        all_keypoints.append(video_anno)
        all_labels[0].append(str(i))
        all_labels[1].append(0)  # label 0 means falling
        all_scores.append(score)

    len_pos = len(all_keypoints)
    for i, path in enumerate(os.listdir("annotations_test_neg")):
        video_anno, score = decode_json_path(os.path.join("annotations_test_neg", path))

        all_keypoints.append(video_anno)
        all_labels[0].append(str(i + len_pos))
        all_labels[1].append(1)  # label 1 means other
        all_scores.append(score)

    all_data = np.stack(all_keypoints, 0)
    all_score_data = np.stack(all_scores, 0)
    np.save(f"train_data.npy", all_data)
    pickle.dump(all_labels, open(f"train_label.pkl", "wb"))
    np.save("kptscore_data.npy", all_score_data)`

**Comment by zhiboniu** [comment]
只需要把0和1互换就行了吧
