### ISSUE TITLE
PPHuman中基于人体ID分类模型开发项目   分类模型的训练问题

### ISSUE THREAD

**Issue by liangchen341** [PaddlePaddle/PaddleDetection#7886]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

初学者，想使用基于人体ID分类模型项目的思路训练自己的数据集，并识别行为。我在训练分类网络时遇到了疑惑，是先使用目标跟踪网络将人物框选并截取出来后送入分类网络训练，还是直接将原视频每一帧直接送入网络训练？（在二次开发教程中提到了正样本行人检测模型处理为半身图像，负样本采样得到的图像，但是不太理解为什么正负样本不做同样的处理）希望能得到解答，不胜感激！

**Comment by zhiboniu** [comment]
是先使用目标跟踪网络将人物框选并截取出来后送入分类网络训练
是这个。
检测模型应该没有负样本得到的图像，正负样本是截取后对目标进行的二次分类才有，所以截取框的行为是统一的。
