### ISSUE TITLE
训练denseteacher中未标注数据的loss一直为0

### ISSUE THREAD

**Issue by yaofanji** [PaddlePaddle/PaddleDetection#7890]
![1678261371770](https://user-images.githubusercontent.com/94046113/223652268-7126590f-3d48-4fc6-b6d0-fb5294b9abd7.png)
![1678261561549](https://user-images.githubusercontent.com/94046113/223652366-d1feb339-609f-4e17-991e-8f2ee2d9b56d.png)
我用了50张标记数据和950张未标记数据，训练时未标记数据的loss一直为0，好像根本没用参加训练

**Comment by nemonameless** [comment]
还没到半监督阶段。数据集太小了，目前iters才 28x12，默认iters数到5000时才开启，可以自己改  https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/configs/semi_det/denseteacher/denseteacher_fcos_r50_fpn_coco_semi005.yml#L18
