### ISSUE TITLE
关于ppyoloe+的backbone的配置问题

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/PaddleDetection#7891]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在页面 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/configs/ppyoloe/README_cn.md
PP-YOLOE+_s  
PP-YOLOE+_m
PP-YOLOE+_l
PP-YOLOE+_x
是四种不同规模的网络结构，但使用的网络结构的配置文件都是：
'./_base_/ppyoloe_crn.yml' 
请问是什么原因呢？这个是默认的什么规模的结构呢？

**Comment by wangxinxin08** [comment]
ppyoloe系列的backbone和neck基本一致，主要靠width_mult和depth_mult来控制
