### ISSUE TITLE
ppyoloe onnx格式如何设置batch>1进行推理

### ISSUE THREAD

**Issue by bixiaopeng0** [PaddlePaddle/PaddleDetection#7895]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如题

**Comment by lyuwenyu** [comment]
这个和你使用的推理引擎有关系吧  ppyoloe去掉后处理导出onnx是支持bs纬度为动态shape的
