### ISSUE TITLE
 新需求:希望增加手部关键点的模型

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#7898]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

![1](https://user-images.githubusercontent.com/6490927/223936733-29628281-025c-4a84-b10c-4c944610c525.png)

需要手势控制
检测手指

参考代码
https://google.github.io/mediapipe/solutions/hands.html

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by thinkthinking** [comment]
说到，你好，可以写在issue置顶区的Roadmap of  #PaddleDetection里面吗？新增特性的需求统一在 #https://github.com/PaddlePaddle/PaddleDetection/issues/7892
下面

**Comment by thinkthinking** [comment]
你好，可以将这个issue合并到 #7892 下面吗？这样可以让更多的人看到，同时参与互动，感谢！

**Comment by thinkthinking** [comment]
开发者已合并到Roadmap of PaddleDetection下
