### ISSUE TITLE
YOLOE+的ONNX模型导出报错

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/PaddleDetection#7899]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用paddle转onnx过程中遇到了算子不支持问题：
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,select_input,
但官方文档里提到 PPTOLOE+是针对工业化部署的目标检测系列模型，抛弃了转onnx，trt等过程中不支持的特殊算子。但实际仍然存在不支持的算子，请问是什么原因呢，并且动态模型的推理速度，本地测试要低于pp-yolov2。

**Comment by nemonameless** [comment]
请使用paddle ppdet paddle2onnx最新版本。动态模型的推理速度，请发下运行命令和具体速度结果看看。
