### ISSUE TITLE
车牌识别报错：AttributeError:'PipePredictor' object has no attribute 'mot_predictor'

### ISSUE THREAD

**Issue by xiaoruoxu** [PaddlePaddle/PaddleDetection#7901]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference

### Bug描述 Describe the Bug

运行车牌识别测试：python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_ppvehicle.yml --image_file=demo/car.jpg --device=gpu

报错：
AttributeError:'PipePredictor' object has no attribute 'mot_predictor'

### 复现环境 Environment

-Os:ubuntu20.04
-paddlepaddle-gpu:2.4.2
-paddledetection:2.6.0
-CUDA:10.2
-CUDNN:7.6.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
infer_cfg_ppvehicle.yml配置文件中的mot是否已经enable了呢，或者可以直接使用examples文件夹下的示例。

**Comment by xiaoruoxu** [comment]
你好我把mot也enable了还是报一样的错误：
Traceback (most recent call last):
  File "deploy/pipeline/pipeline.py", line 1320, in <module>
    main()
  File "deploy/pipeline/pipeline.py", line 1307, in main
    pipeline.run_multithreads()
  File "deploy/pipeline/pipeline.py", line 179, in run_multithreads
    self.predictor.run(self.input)
  File "deploy/pipeline/pipeline.py", line 537, in run
    self.mot_predictor.det_times.tracking_info(average=True)
AttributeError: 'PipePredictor' object has no attribute 'mot_predictor'

**Comment by xiaoruoxu** [comment]
不光这样，所有PP-Human和PP-Vehicle我都会报这个错误：AttributeError: 'PipePredictor' object has no attribute 'mot_predictor'

**Comment by lgy2830** [comment]
你好，我出现车牌的检测框平行往左平移的情况，是偶尔的某一帧出现平移，并且检测框的大小与车牌区域的大小不太一致。平移的检测框在真实的检测框的左边，与车牌区域不重合。

**Comment by zhiboniu** [comment]
我这里测试如果有开启跟踪功能是不会有这个问题的，可以确认一下是否修改对了配置文件。另外这个bug已经提pr修复了
