### ISSUE TITLE
文档与实际不符

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleDetection#7907]
### 文档链接&描述 Document Links & Description

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/PrepareMOTDataSet_cn.md

![图片](https://user-images.githubusercontent.com/6648329/224207569-ae4f51cf-1714-4f98-91b9-087f94e86798.png)

文档与实际不符   ，图片下载的是： https://bj.bcebos.com/v1/paddledet/data/mot/demo/MOT16.zip 进行对比

**Comment by thinkthinking** [comment]
> ### 文档链接&描述 Document Links & Description
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/PrepareMOTDataSet_cn.md
> 
> ![图片](https://user-images.githubusercontent.com/6648329/224207569-ae4f51cf-1714-4f98-91b9-087f94e86798.png)
> 
> 文档与实际不符 ，图片下载的是： https://bj.bcebos.com/v1/paddledet/data/mot/demo/MOT16.zip 进行对比

@gg22mm 你好，这个是2.3版本的文档了，目前PaddleDetection已经更新到v2.6版本了，最新文档链接：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/docs/tutorials/data/PrepareMOTDataSet.md

**Comment by gg22mm** [comment]
> > ### 文档链接&描述 Document Links & Description
> > https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/PrepareMOTDataSet_cn.md
> > ![图片](https://user-images.githubusercontent.com/6648329/224207569-ae4f51cf-1714-4f98-91b9-087f94e86798.png)
> > 文档与实际不符 ，图片下载的是： https://bj.bcebos.com/v1/paddledet/data/mot/demo/MOT16.zip 进行对比
> 
> @gg22mm 你好，这个是2.3版本的文档了，目前PaddleDetection已经更新到v2.6版本了，最新文档链接：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/docs/tutorials/data/PrepareMOTDataSet.md

那也是一样的：
![图片](https://user-images.githubusercontent.com/6648329/224211712-9935a516-4f33-46f9-b2b0-591a9b626918.png)
只有是9个参数说明，但是 https://bj.bcebos.com/v1/paddledet/data/mot/MOT16.zip  里面确是10个参数

**Comment by gg22mm** [comment]
群里问了 ，估计是我导出的问题 
![图片](https://user-images.githubusercontent.com/6648329/224216403-23b6d854-6dff-4b21-8acc-f18efddc4404.png)

**Comment by thinkthinking** [comment]
> 群里问了 ，估计是我导出的问题 ![图片](https://user-images.githubusercontent.com/6648329/224216403-23b6d854-6dff-4b21-8acc-f18efddc4404.png)

ok
