### ISSUE TITLE
小白问源码

### ISSUE THREAD

**Issue by Manman35** [PaddlePaddle/PaddleDetection#7908]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

新手小白，想问一下PP-Human赋能社区智能精细化管理的源码在哪里

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/pipeline

**Comment by Manman35** [comment]
t谢谢

**Comment by thinkthinking** [comment]
@Manman35 根据回复来看该issue已经解决，故close，如果未解决可以reopen，非常感谢！
