### ISSUE TITLE
pp-yoloe-r导出onnx如何固定输入？

### ISSUE THREAD

**Issue by LLsmile** [PaddlePaddle/PaddleDetection#7909]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

默认方式导出的onnx为多batch状态，我想**导出一个输入为1*3*640*640的onnx**，按照[教程](https://github.com/jiangjiajun/PaddleUtils/tree/main/paddle)修改输入后，只改了输入image，还有个scale参数没有修改，而且导致输出也是之前的奇怪状态：
![Screenshot from 2023-03-10 14-18-33](https://user-images.githubusercontent.com/18437178/224238679-f63d3e9f-9058-4ffd-b6f3-de0ccc0917c7.png)

修改输入的命令:
`python paddle_infer_shape.py --model_dir ../../PaddleDetection/output_inference/ppyoloe_r_crn_m_3x_dota/ --model_filename model.pdmodel --params_filename model.pdiparams --save_dir renamed.onnx --input_shape_dict="{'image':[1,3,640,640]}" `

**Comment by LLsmile** [comment]
两个输入都固定后，输出还是不固定

![image](https://user-images.githubusercontent.com/18437178/224280984-38fee438-105b-4bd1-9663-fa82b29b74b6.png)

**Comment by wangxinxin08** [comment]
首先不建议直接修改输入为640 * 640，模型的评估尺寸为1024 * 1024，固定输入需要同时修改reader和image_shape，参考yoloe_reader.py

**Comment by LLsmile** [comment]
训练的时候已经改成640*640了，所以导出的时候也要这样。
你说的是yoloe_reader.yml里的配置方式吧，已经这样修改了，测试的时候也是这个尺寸没问题，主要是现在导出onnx不好固定输入输出大小。

**Comment by wangxinxin08** [comment]
> 训练的时候已经改成640*640了，所以导出的时候也要这样。 你说的是yoloe_reader.yml里的配置方式吧，已经这样修改了，测试的时候也是这个尺寸没问题，主要是现在导出onnx不好固定输入输出大小。

比较一下和yoloe_reader的TestReader很明显就能发现差异
