### ISSUE TITLE
pipeline.py visualize_video 参数丢失

### ISSUE THREAD

**Issue by Weihao-Jin** [PaddlePaddle/PaddleDetection#7912]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

**deploy/pipeline/pipeline.py line 807**
**_visualize_video_** 传参缺失 _**collector**_ 参数

代码位置：

```python
807                        im = self.visualize_video(frame_rgb, mot_res, frame_id,
808                                                 fps, entrance, records,
809                                                  center_traj)  # visualize
```
当MOT模型开启时，任何PPHuman或者PPVehicle的均可复现错误。该错误发生于画面中无检测目标时，传参缺失会导致逻辑输出有误。

解决方法：
```python
807                        im = self.visualize_video(frame_rgb, mot_res, self.collector, frame_id,
808                                                 fps, entrance, records,
809                                                  center_traj)  # visualize
```
补充参数，当画面中无检测目标时，**_mot_res_**无内容，该参数在**_visualize_video_**内不会被使用

### 复现环境 Environment

- OS： Ubuntu
- PaddlePaddle: GPU 2.4.2
- PaddleDetection: release/2.4
- Python: 3.7
- CUDA: 11.6
- CUDNN: 8.4.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
请使用最新 release/2.6试试。也可提PR修复2.4分支谢谢

**Comment by Weihao-Jin** [comment]
> 请使用最新 release/2.6试试。也可提PR修复2.4分支谢谢
测试了，2.6有一样的问题

**Comment by zhiboniu** [comment]
收到，感谢反馈，会修复该问题
