### ISSUE TITLE
请问有关眼动仪相关的算法吗

### ISSUE THREAD

**Issue by nine-city** [PaddlePaddle/PaddleDetection#7914]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问有关眼动仪/眼球追踪相关的算法库吗，能和paddle比较好集成的

**Comment by nemonameless** [comment]
暂时没有，或者您可以提供别的框架的比较有影响力的代码库，我们评估下有可能会排期复现下。

**Comment by thinkthinking** [comment]
> ### 问题确认 Search before asking
> * [x]  我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> 
> ### 请提出你的问题 Please ask your question
> 请问有关眼动仪/眼球追踪相关的算法库吗，能和paddle比较好集成的

将该需求合并到Roadmap of PaddleDetection #7892

**Comment by thinkthinking** [comment]
> ### 问题确认 Search before asking
> * [x]  我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> 
> ### 请提出你的问题 Please ask your question
> 请问有关眼动仪/眼球追踪相关的算法库吗，能和paddle比较好集成的

@nine-city 同时，可以具体描述一下这个需求的使用场景？或者一些难点吗？

**Comment by nine-city** [comment]
@thinkthinking 戴上眼动仪，通过AI去识别硬件传回来的眼球的反光，偏移之类的数据（可能是视频流），可以算出当前眼睛集中看的位置，比如可以用在VR游戏里面，目前遇到的问题是我不太清楚市面上有没有好的相关算法。

**Comment by thinkthinking** [comment]
> @thinkthinking 戴上眼动仪，通过AI去识别硬件传回来的眼球的反光，偏移之类的数据（可能是视频流），可以算出当前眼睛集中看的位置，比如可以用在VR游戏里面，目前遇到的问题是我不太清楚市面上有没有好的相关算法。

@nine-city 感谢说明，这是一个非常垂类的应用场景，PaddleDetection暂时还没有满足这个需求的算法。或许您可以再明确一下主流的算法，然后提到这里我们评估进行开发，我们也同步看一下。

**Comment by nine-city** [comment]
@thinkthinking 据我搜索到的，杜克大学有做相关研究，但是也只是理论上的，这是他们论文的PDF https://maria.gorlatova.com/wp-content/uploads/2022/03/EyeSyn_CR.pdf

**Comment by thinkthinking** [comment]
> @thinkthinking 据我搜索到的，杜克大学有做相关研究，但是也只是理论上的，这是他们论文的PDF https://maria.gorlatova.com/wp-content/uploads/2022/03/EyeSyn_CR.pdf

你好，已收到，并且合并到roadmap of paddledetection 进行投票沉淀。
