### ISSUE TITLE
The given version [11] is not supported, only version 1 to 10 is supported in this build.问题怎么排查？

### ISSUE THREAD

**Issue by MiShiDeHaiLuo** [PaddlePaddle/PaddleDetection#7915]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/97105652/224338263-4602b370-e2ea-47c9-8b38-b76a83c88f18.png)
下载C++的CPU预测库，采用VS2022进行部署。提示以上消息，按照网上方法排查Yaml文件的原因还是未能解决。是否与电脑存在cuda但是下载的CPU预测库有关系？

**Comment by zhiboniu** [comment]
看起来好像是库与环境不一致的原因，可以检查下版本是否对应
