### ISSUE TITLE
所有PP-Human和PP-Vehicle任务报错：AttributeError: 'PipePredictor' object has no attribute 'mot_predictor'

### ISSUE THREAD

**Issue by xiaoruoxu** [PaddlePaddle/PaddleDetection#7917]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

我把mot也enable了还是报一样的错误：
Traceback (most recent call last):
File "deploy/pipeline/pipeline.py", line 1320, in
main()
File "deploy/pipeline/pipeline.py", line 1307, in main
pipeline.run_multithreads()
File "deploy/pipeline/pipeline.py", line 179, in run_multithreads
self.predictor.run(self.input)
File "deploy/pipeline/pipeline.py", line 537, in run
self.mot_predictor.det_times.tracking_info(average=True)
AttributeError: 'PipePredictor' object has no attribute 'mot_predictor'

### 复现环境 Environment

-Os:ubuntu20.04
-paddlepaddle-gpu:2.4.2
-paddledetection:2.6.0
-CUDA:10.2
-CUDNN:7.6.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by miliner** [comment]
请问楼主的问题解决了吗？我也遇到了同样的问题

**Comment by zhiboniu** [comment]
请问报错执行的命令是什么？

**Comment by zhiboniu** [comment]
已确认这个问题是因为没有开启跟踪功能时，最后统计跟踪耗时时出的问题，已经在修复。使用带跟踪的功能不会有问题，可以参考examples下的配置

**Comment by gg22mm** [comment]
要记进对使用的模型设置： enable: False 改成 enable: True 才行如：
python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_pphuman.yml --video_file=demo/1.mp4
![图片](https://user-images.githubusercontent.com/6648329/224600573-9bf405cf-0ffd-48e7-81b7-001a97845c21.png)

或是：python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_pphuman.yml  -o  KPT.model_dir=./output_inference/dark_hrnet_w32_256x192 KPT.enable=True   SKELETON_ACTION.model_dir=./output_inference/STGCN SKELETON_ACTION.enable=True  --video_file=demo/1.mp4 --device=gpu

**Comment by zhiboniu** [comment]
好的，如果没问题了就关闭issue吧

**Comment by xiaoruoxu** [comment]
我原来就是加上的MOT的enable就是True,还是 有这个问题
这时我的infer_cfg_ppvehicle.yml的具体内容：
crop_thresh: 0.5
visual: True
warmup_frame: 50

DET:
  model_dir: output_inference/mot_ppyoloe_l_36e_ppvehicle/
  batch_size: 1

MOT:
  model_dir: output_inference/mot_ppyoloe_l_36e_ppvehicle/
  tracker_config: deploy/pipeline/config/tracker_config.yml
  batch_size: 1
  skip_frame_num: -1 # preferably no more than 3
  enable: True

VEHICLE_PLATE:
  det_model_dir: output_inference/ch_PP-OCRv3_det_infer/
  det_limit_side_len: 736
  det_limit_type: "min"
  rec_model_dir: output_inference/ch_PP-OCRv3_rec_infer/
  rec_image_shape: [3, 48, 320]
  rec_batch_num: 6
  word_dict_path: deploy/pipeline/ppvehicle/rec_word_dict.txt
  enable: True

VEHICLE_ATTR:
  model_dir: output_inference/vehicle_attribute_model
  batch_size: 8
  color_threshold: 0.5
  type_threshold: 0.5
  enable: False

LANE_SEG:
  lane_seg_config: deploy/pipeline/config/lane_seg_config.yml
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/pp_lite_stdc2_bdd100k.zip

VEHICLE_PRESSING:
  enable: False

VEHICLE_RETROGRADE:
  frame_len: 8
  sample_freq: 7
  enable: False
  filter_horizontal_flag: True
  keep_right_flag: True
  deviation: 23
  move_scale: 0.01
  fence_line: []   #[x1,y1,x2,y2] y2>y1.

运行命令为：python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_ppvehicle.yml --image_file=demo/car.jpg --device=gpu

报错如下：
Traceback (most recent call last):
  File "deploy/pipeline/pipeline.py", line 1320, in <module>
    main()
  File "deploy/pipeline/pipeline.py", line 1307, in main
    pipeline.run_multithreads()
  File "deploy/pipeline/pipeline.py", line 179, in run_multithreads
    self.predictor.run(self.input)
  File "deploy/pipeline/pipeline.py", line 537, in run
    self.mot_predictor.det_times.tracking_info(average=True)
AttributeError: 'PipePredictor' object has no attribute 'mot_predictor'

**Comment by zhiboniu** [comment]
哦哦，图片推理确实不会创建'mot_predictor'，已经在新的pr里修复了。拉下新的分支吧
