### ISSUE TITLE
ocsort使用导出模型去预测的时候报错，AssertionError: plot_tracking only supports single classes.

### ISSUE THREAD

**Issue by chengzhixing0202** [PaddlePaddle/PaddleDetection#7919]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

ocsort使用导出模型去预测的时候报错，AssertionError: plot_tracking only supports single classes；按照readme操作的不对，使用同样的检测器导出模型，换成Bytetrack跟踪就没问题

**Comment by zhiboniu** [comment]
应该是oc-sort目前的实现还不支持多类别。看起来应该是这个差异，如果多类别的话可以使用bytetrack吧
