### ISSUE TITLE
PaddleDetection export得到的模型部署后出现ShapeError

### ISSUE THREAD

**Issue by omtbreak** [PaddlePaddle/PaddleDetection#792]
1. 部署后调用出现[ShapeError](https://github.com/PaddlePaddle/Serving/issues/597)的模型有cascade rcnn、faster rcnn和yolov3，均是我们通过PaddleDetection训练，然后使用[转换工具](https://github.com/PaddlePaddle/PaddleDetection/blob/master/tools/export_serving_model.py)得到的模型。
2. 而我们的同事同样采用上述步骤，却可以[成功调用](https://github.com/PaddlePaddle/PaddleDetection/issues/774)

因此，我感到很迷惑，我认为问题不在于Serving模块，而是在模型导出或其他地方出现问题，希望能得到解答

**Comment by willthefrog** [comment]
能否diff下示例提供的和你们导出的prototxt呢，有什么差异吗？

**Comment by omtbreak** [comment]
> 能否diff下示例提供的和你们导出的prototxt呢，server的那个，有什么差异吗？

您好，以下是具体的prototxt文件截图
#### Serving开发工作人员提供的cascade rcnn的模型，我们可部署可成功调用
1. client的prototxt
![example-client](https://user-images.githubusercontent.com/12478872/82998103-ded06200-a039-11ea-93cb-f86001cc2160.png)
2. server的prototxt
![example-server](https://user-images.githubusercontent.com/12478872/82998128-e98af700-a039-11ea-9296-1db4a7c59298.png)

#### 我们同事训练的cascade rcnn(cascade rcnn中的一种)，同样可部署可成功调用
1. client的prototxt
![ssh-client](https://user-images.githubusercontent.com/12478872/82998415-49819d80-a03a-11ea-8010-f8b25fb0bbd1.png)
2. server的prototxt
![ssh-server](https://user-images.githubusercontent.com/12478872/82998288-20610d00-a03a-11ea-83e2-a91c4bdd13f6.png)

#### 我们训练的cascade rcnn模型，可部署，可调用，但是报shapeerror
1. client的prototxt
![baicheng-client](https://user-images.githubusercontent.com/12478872/82998548-7766e200-a03a-11ea-80fd-b4f52100e281.png)
2.server的prototxt
![Uploading baicheng-server.png…]()

同时有个点需要告诉您，我们在使用时修改了安装的paddle-serving-app包中的paddle_serving_app/reader/image_reader.py的源码，具体是将
```
fin = open(img_path)
```
修改为
```
fin = open(img_path,'rb')
```
修改原因是，如果不修改的话，读图片会有问题

**Comment by willthefrog** [comment]
你们的模型修改了什么？prototxt看着都是完全一致的吧

**Comment by willthefrog** [comment]
另外建议确认下你们和同事的版本是否都一致。

**Comment by wangjiawei04** [comment]
> > 能否diff下示例提供的和你们导出的prototxt呢，server的那个，有什么差异吗？
> > 您好，以下是具体的prototxt文件截图
> 
> #### Serving开发工作人员提供的cascade rcnn的模型，我们可部署可成功调用
> 1. client的prototxt
>    ![example-client](https://user-images.githubusercontent.com/12478872/82998103-ded06200-a039-11ea-93cb-f86001cc2160.png)
> 2. server的prototxt
>    ![example-server](https://user-images.githubusercontent.com/12478872/82998128-e98af700-a039-11ea-9296-1db4a7c59298.png)
> 
> #### 我们同事训练的cascade rcnn(cascade rcnn中的一种)，同样可部署可成功调用
> 1. client的prototxt
>    ![ssh-client](https://user-images.githubusercontent.com/12478872/82998415-49819d80-a03a-11ea-8010-f8b25fb0bbd1.png)
> 2. server的prototxt
>    ![ssh-server](https://user-images.githubusercontent.com/12478872/82998288-20610d00-a03a-11ea-83e2-a91c4bdd13f6.png)
> 
> #### 我们训练的cascade rcnn模型，可部署，可调用，但是报shapeerror
> 1. client的prototxt
>    ![baicheng-client](https://user-images.githubusercontent.com/12478872/82998548-7766e200-a03a-11ea-80fd-b4f52100e281.png)
>    2.server的prototxt
>    ![baicheng-server](https://user-images.githubusercontent.com/12478872/82999269-56eb5780-a03b-11ea-8b07-a74fbf7ac5f0.png)
> 
> 同时有个点需要告诉您，我们在使用时修改了安装的paddle-serving-app包中的paddle_serving_app/reader/image_reader.py的源码，具体是将
> 
> ```
> fin = open(img_path)
> ```
> 
> 修改为
> 
> ```
> fin = open(img_path,'rb')
> ```
> 
> 修改原因是，如果不修改的话，读图片会有问题

想问下 您在PaddlePaddle的QQ用户群里吗，我可以加您讨论下方便解决问题。

**Comment by willthefrog** [comment]
> 想问下 您在PaddlePaddle的QQ用户群里吗，我可以加您讨论下方便解决问题。

不在，内部同学得话可以直接交流吧？

**Comment by omtbreak** [comment]
> 想问下 您在PaddlePaddle的QQ用户群里吗，我可以加您讨论下方便解决问题。

是的，我在PaddlePaddle的交流3群里

**Comment by omtbreak** [comment]
> 你们的模型修改了什么？prototxt看着都是完全一致的吧

抱歉回复晚了，我们在训练模型时，只修改了超参数和读取数据集的路径，以及target size

**Comment by wangjiawei04** [comment]
> > 想问下 您在PaddlePaddle的QQ用户群里吗，我可以加您讨论下方便解决问题。
> 
> 是的，我在PaddlePaddle的交流3群里

说下QQ我去找你

**Comment by omtbreak** [comment]
> > > 想问下 您在PaddlePaddle的QQ用户群里吗，我可以加您讨论下方便解决问题。
> > 
> > 
> > 是的，我在PaddlePaddle的交流3群里
> 
> 说下QQ我去找你

2278543193

**Comment by omtbreak** [comment]
> > > 想问下 您在PaddlePaddle的QQ用户群里吗，我可以加您讨论下方便解决问题。
> > 
> > 
> > 是的，我在PaddlePaddle的交流3群里
> 
> 说下QQ我去找你

您是在哪个群？
