### ISSUE TITLE
PaddleDetection在华为NPU910ProA上的训练问题

### ISSUE THREAD

**Issue by Randy-1009** [PaddlePaddle/PaddleDetection#7922]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PaddleDetection Release：2.4
操作系统：EulerOS 2.0 (SP8)
NPU型号：Ascend 910ProA

Paddle安装参考教程链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/npu_docs/paddle_install_cn.html
调试训练教程链接：
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/npu_docs/train_example_cn.html

在华为的昇腾服务器上未使用docker镜像，直接根据Paddle安装教程进行Paddle的源码编译安装，最终测试时输出paddlepaddle显示在NPU上是可以正常运行的。
![B@X_J4J$0Q5@IORBBB7PUBW](https://user-images.githubusercontent.com/46707940/224541255-441e320b-f49e-44e1-b04b-cfdc638b92a5.png)

然后根据训练教程尝试验证使用NPU训练，训练过程部分截图如下：
![image](https://user-images.githubusercontent.com/46707940/224541344-ad4fdba8-96f7-4088-9ecc-c61860343605.png)

可以看到训练速度很慢，查看NPU的显存占用情况发现也并没有被占用，也就是说训练并没有用到NPU，模型并没有被成功加载到NPU上，但是在代码中添加语句发现NPU是设置成功了的，如下图所示：
![image](https://user-images.githubusercontent.com/46707940/224541557-a1424190-a086-4ec5-995b-9c0cae0f5b4b.png)
想问一下这是什么原因，如果需要更详细的说明或者训练过程中的日志可以提出，谢谢！

**Comment by Randy-1009** [comment]
补充：以上是使用的2.4分支下的static文件夹中的tool/train.py运行的情况，即static/tool/train.py。并非主文件夹下的tool/train.py，因为主文件夹下没有训练文档中的yolov3_darknet_roadsign.yml文件，自己修改了一版放在主文件夹config下的yolov3中之后，使用主文件夹下的tool/train.py进行训练，报错如下：
![image](https://user-images.githubusercontent.com/46707940/224543804-f03fabb6-0cd8-4f24-b530-ab24869de69a.png)

**Comment by zhiboniu** [comment]
你好，static文件夹下代码已经逐渐不再维护了。动态图和静态图yml文件有明显的不同，建议使用config下的yolov3直接训练看看能否成功，再换成自己的训练数据。

**Comment by Randy-1009** [comment]
> 你好，static文件夹下代码已经逐渐不再维护了。动态图和静态图yml文件有明显的不同，建议使用config下的yolov3直接训练看看能否成功，再换成自己的训练数据。

好的，已经尝试在主目录下训练，可以跑通，但是ACL error的报错偶尔会出现导致程序崩溃，即上述补充说明中的附图，想请教一下这个可能是什么原因呢

**Comment by zgz757183190** [comment]
> ### 问题确认 Search before asking
> * [x]  我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> 
> ### 请提出你的问题 Please ask your question
> PaddleDetection Release：2.4 操作系统：EulerOS 2.0 (SP8) NPU型号：Ascend 910ProA
> 
> Paddle安装参考教程链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/npu_docs/paddle_install_cn.html 调试训练教程链接： https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/npu_docs/train_example_cn.html
> 
> 在华为的昇腾服务器上未使用docker镜像，直接根据Paddle安装教程进行Paddle的源码编译安装，最终测试时输出paddlepaddle显示在NPU上是可以正常运行的。 ![B@X_J4J$0Q5@IORBBB7PUBW](https://user-images.githubusercontent.com/46707940/224541255-441e320b-f49e-44e1-b04b-cfdc638b92a5.png)
> 
> 然后根据训练教程尝试验证使用NPU训练，训练过程部分截图如下： ![image](https://user-images.githubusercontent.com/46707940/224541344-ad4fdba8-96f7-4088-9ecc-c61860343605.png)
> 
> 可以看到训练速度很慢，查看NPU的显存占用情况发现也并没有被占用，也就是说训练并没有用到NPU，模型并没有被成功加载到NPU上，但是在代码中添加语句发现NPU是设置成功了的，如下图所示： ![image](https://user-images.githubusercontent.com/46707940/224541557-a1424190-a086-4ec5-995b-9c0cae0f5b4b.png) 想问一下这是什么原因，如果需要更详细的说明或者训练过程中的日志可以提出，谢谢！


你好，请教一下，这个是怎么跑起来的呢，如果不训练模型的话，直接用共有的模型可以运行不呢？

**Comment by chenqion** [comment]
请问上述训练慢的问题解决了吗
