### ISSUE TITLE
执行python ppdet/modeling/tests/test_architectures.py  测试后，出现以下错误 paddlepaddle2.1.2，paddledetection2.1

### ISSUE THREAD

**Issue by GGGHHHLLL** [PaddlePaddle/PaddleDetection#7928]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

======================================================================
ERROR: test_trainer (__main__.TestSSD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 83, in __init__
    cfg['ema_decay'], self.model, use_thres_step=True)
KeyError: 'ema_decay'

======================================================================
ERROR: test_trainer (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 83, in __init__
    cfg['ema_decay'], self.model, use_thres_step=True)
KeyError: 'ema_decay'

======================================================================

**Comment by LokeZhou** [comment]
可以使用最新的paddledetection2.6试一下

**Comment by GGGHHHLLL** [comment]
我已经解决了这个问题，是因为版本不适配的问题，克隆paddledetection的那个命令默认下载了是最新版本的，而我的对应版本需要paddledetection2.1.0，需要在克隆那个命令中加入他的版本号：git clone https://github.com/PaddlePaddle/PaddleDetection.git 这样就可以了

**Comment by thinkthinking** [comment]
根据用户反馈该issue已经解决，故close掉，如果未解决可以reopen。
