### ISSUE TITLE
coco数据集与voc数据集的训练问题

### ISSUE THREAD

**Issue by luguanren** [PaddlePaddle/PaddleDetection#7929]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

同一份数据集，在使用coco格式与voc格式训练时voc20个epoch就可以达到七十几的map，coco100多个epoch才三十几。
模型其他参数完全一致，只有数据加载选择的配置文件不同，同时也是使用 tools/x2coco.py 下的脚本将voc转换成coco的，请问问题出在哪里呢？
![image](https://user-images.githubusercontent.com/126534866/224620905-5be5a338-4b7c-4aa3-b662-b4e5bf06fa57.png)
![image](https://user-images.githubusercontent.com/126534866/224620919-69595e3a-6d04-4161-b8b3-92dbec70aac2.png)

**Comment by luguanren** [comment]
voc:
![image](https://user-images.githubusercontent.com/126534866/224622024-17b71929-888b-4806-ab53-2ee58a54ca0f.png)
coco:
![image](https://user-images.githubusercontent.com/126534866/224622203-442e063c-c760-419b-b151-07a7874f5502.png)

**Comment by LokeZhou** [comment]
可以先可视化一下转成coco的数据与voc格式的label是否对应。其次在训练时，可以屏蔽voc数据以及coco数据的数据增强以及dataload的shuffle，验证两个数据集训练在随机量固定下是否对齐。
