### ISSUE TITLE
使用paddle的一点体会

### ISSUE THREAD

**Issue by zhaotun** [PaddlePaddle/PaddleDetection#7933]
经常在各种公众号或者文章中看到paddle发布的一些SOTA模型，感觉很厉害的样子，好几次都准备用paddle全家桶来进行训练和部署，但按照官方文档操作，总会出现一些这样那样的问题，想在issues里找找解决办法，但发现很多问题都没有得到有效的回复或者解决，于是耐心逐渐被一点点地消磨殆尽，由于没能及时地找到解决办法，不得不放弃使用。

而用yolov5就比较顺利，按照文档操作，基本会比较顺利，偶尔遇到些问题也基本能在issues中找到解决方案。

yolov5有36.2k个star，issues只有233，而paddledetection有9.7k个star，但issue有854个，这至少能说明两个问题：
第一是yolov5易用性较好，用的过程中比较顺利，不需要提issue；
第二，yolov5对于issue的回复和处理比较及时和有效，使用过程中遇到问题了可以通过查看issue找到解决办法，不需要再提新的issue了。

想说的是，有自研的框架有SOTA模型推当然很好，但是开源出来后，也需要进行持续的维护，及时有效地处理各种使用过程中出现的问题，这样才能让大家愿意继续用下去。特别是对于初次使用者，如果遇到的问题得不到及时有效的解决，很容易被劝退。

**Comment by thinkthinking** [comment]
@zhaotun 

您好，首先非常感谢您对Paddle的关注和建议。

PaddleDetection近期发版在模型广度上投入的精力较多，如：具备车辆、行人追踪、属性分析的套件PP-Human、PP-Vehicle；PP-YOLOE家族的通用、小目标、旋转框、密集检测算法以及模型蒸馏、少样本学习、自监督学习方案；关键点检测模型PP-TinyPose；ViT系列检测模型；DETR系列检测模型等等。

如果针对某个方向的使用体验不太好，还麻烦您可以具体说明一下，我们进行跟进解决。

您提到的issue方面的几点也是我们最近在专项治理、改进的，
这个改进专项kick off会议刚好在你提issue的一个半小时前。
你可以看到，从v2.6发版之后的每条issue都assign了相应的人员以及对应的标签。

以下是我们具体采取的措施。

以下是我们最近的具体措施，上周五制定完成，已于今天正式执行：
1. 细化issue值班细则，每条issue assign相应R&D同学跟进到底，直到issue关闭；
2. 针对每条issue，细化issue问题分类标签，便于统计我们目前issue主要集中的方面；
3. 针对每条issue，正常反馈时间为24小时，最晚不晚于72小时；
4. 设立Roadmap of PaddleDetection专区，针对新特性需求或者吐槽集中回复；
5. 建立需求库沉淀机制，将issue频现、以及roadmap专区的问题及时通过review的方式纳入下次发版中；
6. 增加版本更新频次，其实原先很多问题在于我们PR稿宣传的新功能并没有放在主分支，而是放在了develop分支下，而develop分支与主分支差异较大，如果不切分支的话很多代码确实跑不起来。针对这个问题，从v2.6版本开始，我们会保持动态发新，比如针对issue区反馈的bug，我们会及时修复，并且发布v2.6.x这样的小版本，保证大家及时体验最新代码；
7. 针对文档，我们也会从安装到最后部署进行梳理，完善文档、算法呈现方式，细化文档表述。

以上是我们正在实施的措施，也欢迎你的监督和关注！

如果有进一步的反馈，欢迎继续沟通！

如果方便的话，欢迎你添加微信thinkthinking_，进行详聊！

**Comment by zhaotun** [comment]
> 

非常感谢您的耐心回复，也非常高兴听到你们也关注到了这些问题并已采取了相应的措施。其实paddle在模型的广度方面已经做得很好了，提供了很多优秀先进的模型以及很多实用的套件和工具，如果能够进一步在易用性、好用性等方面多点关注和优化，相信一定能够逐步变得更好，生态会越来越完善，完全能够成为业内标杆。我会持续关注和使用，遇到问题会积极吐槽和提issue。

**Comment by thinkthinking** [comment]
> > 
> 
> 非常感谢您的耐心回复，也非常高兴听到你们也关注到了这些问题并已采取了相应的措施。其实paddle在模型的广度方面已经做得很好了，提供了很多优秀先进的模型以及很多实用的套件和工具，如果能够进一步在易用性、好用性等方面多点关注和优化，相信一定能够逐步变得更好，生态会越来越完善，完全能够成为业内标杆。我会持续关注和使用，遇到问题会积极吐槽和提issue。

共勉！

**Comment by clementzhao** [comment]
很久没关注paddle，听闻最新更新一波过来试试。工程配置好复杂，跑一下训练就发现代码有2个bug！
yolov5训练大概就几个小时，在yoloe+训练竟然提示eta要2天半！
这样的工程能力，实在太难用了，准备弃坑。

**Comment by nemonameless** [comment]
> 很久没关注paddle，听闻最新更新一波过来试试。工程配置好复杂，跑一下训练就发现代码有2个bug！ yolov5训练大概就几个小时，在yoloe+训练竟然提示eta要2天半！ 这样的工程能力，实在太难用了，准备弃坑。

如果有bug请具体报下，训练速度的问题也请具体说明最好列数据截图，以便查找问题和改进。
yolov5默认训300epoch，yoloe+默认训80epoch，在相同数据集相同batchsize设定下，排除使用不当问题的话，理论上yoloe+训练是不可能比yolov5训练慢的，还请再次确认下，最好列下数据或截图。

**Comment by clementzhao** [comment]
> > 很久没关注paddle，听闻最新更新一波过来试试。工程配置好复杂，跑一下训练就发现代码有2个bug！ yolov5训练大概就几个小时，在yoloe+训练竟然提示eta要2天半！ 这样的工程能力，实在太难用了，准备弃坑。
> 
> 如果有bug请具体报下，训练速度的问题也请具体说明最好列数据截图，以便查找问题和改进。 yolov5默认训300epoch，yoloe+默认训80epoch，在相同数据集相同batchsize设定下，排除使用不当问题的话，理论上yoloe+训练是不可能比yolov5训练慢的，还请再次确认下，最好列下数据或截图。

一个bug已经提了，也close了，但是没及时合到主干上这点就是给用户埋坑。
另一个简单，这里提一下：ppdet/data/source/coco.py：line 148:
                         continue
                     if 'bbox' not in inst.keys():
                         continue
+                    elif 'area' not in inst.keys():
+                        continue
                     else:
                         if not any(np.array(inst['bbox'])):
                             continue

yoloe+是改成300e和yolov5对比的，80e确实时间是一样，但说明啥了呢。
paddledetection自带了nms，导出tensorrt又要先自行删掉。看看隔壁openmmlab的，mmdet自带nms算子的so库，一步到位，请接受你们自己的不足吧。
