### ISSUE TITLE
yaml-cpp.cmake

### ISSUE THREAD

**Issue by fujianhai** [PaddlePaddle/PaddleDetection#794]
运行script/build.sh脚本，编译时yaml-cpp无法安装，如果自己先本地安装好yaml，那这里的.cmake和 cmakelist里面需要修改什么？

**Comment by willthefrog** [comment]
可以尝试删掉`include(cmake/yaml-cpp.cmake)`及 `ADD_DEPENDENCIES(main ext-yaml-cpp)` 并相应修改下面的路径
```cmake
include_directories("${CMAKE_CURRENT_BINARY_DIR}/ext/yaml-cpp/src/ext-yaml-cpp/include")
link_directories("${CMAKE_CURRENT_BINARY_DIR}/ext/yaml-cpp/lib")
```

**Comment by fujianhai** [comment]
@willthefrog ,按照这样修改make[2]: *** No rule to make target `fluid_inference/paddle/lib/libpaddle_fluid.so', needed by `main'.  Stop.
生成的库是 libyaml-cpp.a

**Comment by willthefrog** [comment]
你`PADDLE_DIR`是怎么设置的？

**Comment by fujianhai** [comment]
已经解决，是路径问题，就剩下最后一个问题
main.cc:24: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'

**Comment by willthefrog** [comment]
系统装了grpc了吧，版本可能太高

**Comment by willthefrog** [comment]
或者gflags

**Comment by fujianhai** [comment]
搞定
