### ISSUE TITLE
关于paddleDetection模型再训练，模型迁移，转预训练模型等的需求

### ISSUE THREAD

**Issue by lingdu-xu** [PaddlePaddle/PaddleDetection#7940]
### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by thinkthinking** [comment]
你是指用PaddleDetection的预训练模型在自己数据集上进行训练的需求吗？这个属于基本功能，PaddleDetection均已支持。
你可以参考一下这边的[范例](https://github.com/PaddlePaddle/PaddleDetection#%E4%BA%A7%E4%B8%9A%E5%AE%9E%E8%B7%B5%E8%8C%83%E4%BE%8B)，或者对应模型的文档。

**Comment by lingdu-xu** [comment]
paddle系列生态很好，很多工具，识别很准，小菜也可以使用，感谢paddle开发团队，我有这样的一个需求，以检测螺丝缺陷为例，我给用户一台机器一个模型，检测螺丝上的毛刺和凹陷这两个缺陷，初始模型识别一般，只有80%的准确率，我希望客户可以通过他们自己的数据反馈（比如通过人工反馈，标注这个识别对，另一个识别不对等）或者全新标注来不断提升这个模型的准确率。可能是因为我不够了解paddle或者需求太古怪，我暂时还处于探索实现方案的阶段。但是明确的需求有两个，第一，要基于一个老模型做继续开发而不是完全从头训练，第二，用户自己的数据很可能不愿意公开，而硬件环境取决于客户，可能也不是很可控。。。

**Comment by lingdu-xu** [comment]
感谢官方团队的回复，目前本人使用paddleDetection，很好用，感谢官方团队卓越的工作以使得像我这样的小菜也能使用到前沿的算法，感谢

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/issues/43  可以参考下

**Comment by wangbo-git** [comment]
可参考https://github.com/PaddlePaddle/PaddleDetection#%E4%BA%A7%E4%B8%9A%E5%AE%9E%E8%B7%B5%E8%8C%83%E4%BE%8B
