### ISSUE TITLE
训练yolov4_cspdarknet_voc.yml出现以下错误是什么原因呢？

### ISSUE THREAD

**Issue by Lbo18** [PaddlePaddle/PaddleDetection#795]
![image](https://user-images.githubusercontent.com/40286089/82987498-31a21d80-a02a-11ea-8cd5-71d0e63a6ca3.png)

**Comment by Lbo18** [comment]
voc格式训练自己的数据集

**Comment by willthefrog** [comment]
代码版本和配置文件版本是对应得么？看上去应该是代码版本太老了，还没加入这个配置参数

**Comment by Lbo18** [comment]
> 代码版本和配置文件版本是对应得么？看上去应该是代码版本太老了，还没加入这个配置参数

好的好的，应该是代码版本有点老了，是之前的版本~~

**Comment by Fitz-Fitz** [comment]
请问楼主也是跑YOLOV4时候出现这个问题的吗？最后解决了吗？
