### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ****.onnx failed:Node (p2o.Concat.8) Op (Concat) [ShapeInferenceError] Can't merge shape info. Both source and target dimension have values but they differ. Source=5 Target=4 Dimension=2

### ISSUE THREAD

**Issue by alatriste-lee** [PaddlePaddle/PaddleDetection#7955]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Export

### Bug描述 Describe the Bug

【前言：就在上周末，用paddleocr那边的方案训练了自己的一个文字识别模型，转onnx，用到了c#环境里，虽然有一些坎坷，也还是说的过去，效果出来了，出彩，wocao niubi！

没想到在paddledetection这出了问题。

多聊一句，手上有现成的yolo那种格式的标注，虽然不能直接用到paddledetection这里，转换一下也没啥，这里就有了一丝阴霾，这个yolo格式直接支持的话应该不复杂，几年下来都没支持，一定是有说法的吧～】

下面开始这个问题的描述：

走流程，训练ppyoloe，结果没问题，推理没问题。
python tools/train.py -c train_data/***/***_ppyoloe_plus_crn_s_80e_coco.yml
python tools/infer.py -c train_data/***/***_ppyoloe_plus_crn_s_80e_coco.yml -o weights=train_data/***/output/***_ppyoloe_plus_crn_s_80e_coco/model_final.pdparams --infer_img=***_***.jpg

到训练完推理这都没问题，训练速度，推理结果，素材准备的复杂度都可以说相当哇塞了。

导出模型：
python tools/export_model.py -c ***_ppyoloe_plus_crn_s_80e_coco.yml -o weights=***_ppyoloe_plus_crn_s_80e_coco/model_final.pdparams TestReader.inputs_def.image_shape=[3,128,128] --output_dir=output_inference

转onnx
paddle2onnx --model_dir **_ppyoloe_plus_crn_s_80e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file **infer.onnx
到这也没有报错。

用导出的onnx模型推理
python deploy/third_engine/onnx/infer.py --infer_cfg ***_ppyoloe_plus_crn_s_80e_coco\infer_cfg.yml --onnx_file ***_yolo_infer.onnx --image_file ***_***.jpg

【用导出的onnx模型推理报错了】：

Traceback (most recent call last):
  File "C:\Users\***\PaddleDetection\deploy\third_engine\onnx\infer.py", line 144, in <module>
    predictor = InferenceSession(FLAGS.onnx_file)
  File "C:\Users\**\anaconda3\envs\pdocr\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\**\anaconda3\envs\pdocr\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 397, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ***.onnx failed:Node (p2o.Concat.8) Op (Concat) [ShapeInferenceError] Can't merge shape info. Both source and target dimension have values but they differ. Source=5 Target=4 Dimension=2

### 复现环境 Environment

win10 x64 22h2
paddlepaddle-gpu      2.4.2.post117
paddle2onnx           1.0.5
onnx                  1.13.1
onnxruntime           1.14.1
python 3.10.9
Cuda compilation tools, release 11.6, V11.6.124

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
可以先在导出的时候去掉后处理试一下

**Comment by lyuwenyu** [comment]
导出时候把后处理去掉试一下

**Comment by alatriste-lee** [comment]
> 导出时候把后处理去掉试一下

`https://github.com/PaddlePaddle/PaddleDetection/issues/7977`
“该问题仅在图片小于224的情况下发生。”

还真是。“如果青山不来就我，我就去就青山”。

256也可以用。
