### ISSUE TITLE
train pp-yoloe fail with atss_assigner miss return mask_positive.

### ISSUE THREAD

**Issue by clementzhao** [PaddlePaddle/PaddleDetection#7956]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

File "/home/robustel/src/PaddleDetection/ppdet/modeling/heads/ppyoloe_head.py", line 390, in get_loss
    assigned_labels, assigned_bboxes, assigned_scores, mask_positive = \
ValueError: not enough values to unpack (expected 4, got 3)

ppdet/modeling/assigners/atss_assigner.py: 129
return assigned_labels, assigned_bboxes, assigned_scores

### 复现环境 Environment

OS: linux
Paddle: [8433300](https://github.com/PaddlePaddle/PaddleDetection/commit/843330075fa2d52f1f87f506d8bc7d7467744af3)

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/7958  已经在修复了 可以拉等merge之后可以拉最新的代码

**Comment by nemonameless** [comment]
see https://github.com/PaddlePaddle/PaddleDetection/pull/7958
or please use develop branch https://github.com/PaddlePaddle/PaddleDetection/tree/develop 
`git checkout develop`
