### ISSUE TITLE
missing xcoco.py file

### ISSUE THREAD

**Issue by fcakyon** [PaddlePaddle/PaddleDetection#796]
Hello, thanks a lot for this comprehensive library.

[In this doc](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/advanced_tutorials/READER.md) it says that we can use xcoco.py file to convert labelme annotations to coco format, however there are not any xcoco file in tools folder. Where can I find it?

**Comment by gongweibao** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/ppdet/data/tools/x2coco.py ?

**Comment by qingqing01** [comment]
@fcakyon 

In doc https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/advanced_tutorials/READER.md#%E6%96%B9%E5%BC%8F%E4%B8%80%E5%B0%86%E6%95%B0%E6%8D%AE%E9%9B%86%E8%BD%AC%E6%8D%A2%E4%B8%BAcoco%E6%A0%BC%E5%BC%8F

```
python ./ppdet/data/tools/x2coco.py \
                --dataset_type labelme \
                --json_input_dir ./labelme_annos/ \
                --image_input_dir ./labelme_imgs/ \
                --output_dir ./cocome/ \
                --train_proportion 0.8 \
                --val_proportion 0.2 \
                --test_proportion 0.0 \
```
