### ISSUE TITLE
推拉流问题 - 我发现之前他们提的bug也没有解决就关闭了.....................................................................................

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleDetection#7964]
124.71.30.191 ip地址我一起保留可以使用，直到调试成功为止，  你们可以使用来调试。  随便调试，测试用的，没关系~~!!!!!!

问题一（推流）：

//例：行人属性识别，单路视频流
python deploy/pipeline/pipeline.py --config deploy/pipeline/config/examples/infer_cfg_human_attr.yml --rtsp rtmp://124.71.30.191:8066/mylive/2 --device=cpu --pushurl rtmp://124.71.30.191:8066/mylive/1
![图片](https://user-images.githubusercontent.com/6648329/226075879-d59ee4db-72fb-4844-b7d4-a04d5fa30d47.png)

测试了下：并没有给： rtmp://124.71.30.191:8066/mylive/1 这个地址推流

我是通过拉流：--rtsp rtmp://124.71.30.191:8066/mylive/2 （这个是成功的）  , 然后再进行 --pushurl rtmp://124.71.30.191:8066/mylive/1 推流（这个失败）

//问题二（拉流）：
//    拉流有个小问题，添加这个参数后拉流会报错：-o visual=False
  

### 复现环境 Environment

PaddleDetection 2.6
windos

经过我的多方面测试：  

\deploy\pipeline\pipe_utils.py

查： self.command = [

替换成：
       `
# wll 没有声音 - 只做图片检测
        self.command = ['ffmpeg',
           '-y', '-an',                 # 您的命令行中有 -an 开关。这将从输出中删除音频。
           '-f', 'rawvideo',
           '-vcodec', 'rawvideo',
           '-pix_fmt', 'bgr24',
           '-s', "{}x{}".format(width, height),
           '-r', str(fps),
           '-i', '-',           
           '-c:v', 'libx264',
           '-pix_fmt', 'yuv420p',
           '-preset', 'ultrafast',           
           '-f', 'flv',
           self.pushurl]

`
        

修改后正确如： 
![图片](https://user-images.githubusercontent.com/6648329/226777444-4238e32f-ec7c-48ab-9d0e-8703f9722f9e.png)

虽然解决了我上面报错的问题，但是又遇到新问题如：
![图片](https://user-images.githubusercontent.com/6648329/226777171-f2600872-39ac-408d-81d4-66ce25a86220.png)

就一直卡在这里了。这个绝对是有问题的，希望官方一起把这个问题 解决了。..  上面的ip地址我一起保留可以使用，直到问题解决.. 

我查看了推流情况：
![图片](https://user-images.githubusercontent.com/6648329/226778110-dc1df399-eba9-402e-ae0c-4a20b032404c.png)

总结了一下： 拉流完->时行识别->再推流太 导致太卡了。没显示出来：

![图片](https://user-images.githubusercontent.com/6648329/226794637-fc8959ab-c9e5-4f77-96f1-c96caa14a324.png)
应该是太卡了，查是我都是本地的搭建的推流服务器，已经是最快了。。 证明这种方案不太成熟

**Comment by zhiboniu** [comment]
你好，现在的推流方案确实是最简化的demo。并不是一个很成熟或者商业用的推流方案，因为我们这边对推拉流的专业知识也不了解，只能提供简易demo。如果有更稳定的需求需要替换自己的推拉流方案哈。
另外，我们后面会推出基于fastdeploy的硬件拉流方案，有需求可以关注。

**Comment by gg22mm** [comment]
好的，感谢回复~~

**Comment by gg22mm** [comment]
好的，感谢回复~~

**Comment by MystericQ** [comment]
楼主 问题有解决办法了吗？

**Comment by Chenkeyi43** [comment]
目前还是有问题，无法做到一边拉流一边推流

**Comment by WangShengFeng1** [comment]
楼主解决了吗

**Comment by WangShengFeng1** [comment]
联系一下2324365941qq
