### ISSUE TITLE
infer的时候如何设定每幅图的bbox个数

### ISSUE THREAD

**Issue by super3kl** [PaddlePaddle/PaddleDetection#797]
原因是出现误识别  看了一下 bbox就出来了一个框

**Comment by FDInSky** [comment]
请说明下你用的模型，数据集，还有训练的结果等过程。

**Comment by super3kl** [comment]
数据集：红绿灯
yolov3_iouloss   50w iter
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.874
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.989
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.978
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.837
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.903
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.909
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.909
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.909
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.871
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.934
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
2020-05-27 13:10:14,566-INFO: Save model to output/my_yolov3_iouloss/best_model.
2020-05-27 13:10:25,511-INFO: Best test box ap: 0.8743811447559868, in iter: 485000

fastrcnn  18w iter
很奇怪 fastrcnn的numclass我只能设81 不然就报input的x和y shape不一致   设为81才能正常训练  虽然我给的label只有两类红绿灯 最后infer的结果也是对的 只不过label名字是person和bicycle 不过并无大碍 只不过最后把id 1和2 对应到红绿灯即可
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.865
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.995
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.974
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.832
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.895
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.898
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.899
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.899
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.865
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.926
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
2020-05-27 21:59:51,770-INFO: Save model to output/faster-r50-vd-c4-1x/my_fast_rcnn/best_model.
2020-05-27 21:59:54,956-INFO: Best test box ap: 0.8650610549453157, in iter: 168000

**Comment by FDInSky** [comment]
那你上面的预测结果是用训练的faster rcnn进行infer的？
如果用faster rcnn这样训练是不合理的，数据集里存在严重的类别不均衡，容易过拟合。
infer时，主要通过调整nms的参数，来设置保留的bbox的数量，参考
BBoxHead:
  head: ResNetC5
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    score_threshold: 0.05

**Comment by super3kl** [comment]
上面的结果是模型train的时候val的日志
但是确实用红绿灯数据集然后设81类 现在提交的成绩是比之前的yolo之类好

**Comment by still-wait** [comment]
@super3kl 
（1）在infer的时候通过指定`--draw_threshold=0.5`设置可视化得分的阈值，阈值越低bbox数量越多，模型输出bbox总数量通过nms的`keep_top_k`来指定。
（2）针对你`numclass我只能设81，不然就报input的x和y shape不一致`的问题，你的配置文件中设置是`num_classes=3`（class数+background）吗？具体报错信息可以贴一下。

**Comment by super3kl** [comment]
我刚刚又试了一下 fastrcnn又不报这个错误了
我觉得可能是因为之前在跑anchorfree的时候需要编译ext_op的时候 我手动把paddle升级到了1.8.1了 然后环境一直没有关过 现在我环境重启过了  paddle又回到了1.7.1 可能就没有这样的问题了
