### ISSUE TITLE
ppyoloe模型导出为onnx模型后用onnxruntime进行推理小图片失败

### ISSUE THREAD

**Issue by SchrodingerLLX** [PaddlePaddle/PaddleDetection#7977]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

使用160*160的图片训练得到ppyoloe的模型，之后使用https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/EXPORT_ONNX_MODEL.md中的教程将模型导出为onnx格式。在使用deploy/third_engine/onnx/infer.py推理的过程中报错。
出现onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from onnx/s.onnx failed:Node (p2o.Concat.8) Op (Concat) [ShapeInferenceError] Can't merge shape info. Both source and target dimension have values but they differ. Source=7 Target=5 Dimension=2。
该问题仅在图片小于224的情况下发生。

### 复现环境 Environment

- OS：Windows
- PaddlePaddle: 2.4.1
- PaddleDetecion: release/2.6
- python:3.8.0
- CUDA:11.2
- CUDNN: 8.4

-配置文件yml
mode: paddle
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: false
arch: YOLO
min_subgraph_size: 3
Preprocess:
- interp: 2
  keep_ratio: false
  target_size:
  - 160
  - 160
  type: Resize
- mean:
  - 0.0
  - 0.0
  - 0.0
  norm_type: none
  std:
  - 1.0
  - 1.0
  - 1.0
  type: NormalizeImage
- type: Permute
label_list:
- '2'
- '1'

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
问题已收到，目前已经定位出问题，正在解决中

**Comment by alatriste-lee** [comment]
> 

https://github.com/PaddlePaddle/PaddleDetection/issues/7955

期待解决

**Comment by alatriste-lee** [comment]
“该问题仅在图片小于224的情况下发生。”

还真是。“如果青山不来就我，我就去就青山”。

256也可以用。

**Comment by wangxinxin08** [comment]
该问题是由于paddle2onnx转换的时候引入的问题，目前已经在https://github.com/PaddlePaddle/Paddle2ONNX/pull/1061 修复，可以拉取Paddle2ONNX的github源码编译转换即可

**Comment by SchrodingerLLX** [comment]
在更新了 https://github.com/PaddlePaddle/Paddle2ONNX/pull/1061 之后问题已经解决。感谢paddlepaddle
