### ISSUE TITLE
pphuman推流报错

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/PaddleDetection#7984]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

我开了多个进程来运行pphuman，每个进程都进行了推流，当进程达到两三个时，就会报错。我觉得和ffmpeg有关
错误信息如下：
  File "/home/deepnature/ai/deepunion/pddetect/pipeline/pipeline.py", line 1240, in predict_video
    pushstream.pipe.stdin.write(im)
BrokenPipeError: [Errno 32] 断开的管道
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1679539050 (unix time) try "date -d @1679539050" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e80000347d) received by PID 13437 (TID 0x7f1458d1f0) from PID 13437 ***]

### 复现环境 Environment

- OS: ubuntu18
- PaddlePaddle: 2.4.2
- PaddleDetection: develop
- Python: 3.7
- CUDA: 10.2
部署在jetson AGX Xavier上，windows上有时也会出现

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
应该是进程多了处理不过来有堵塞
