### ISSUE TITLE
无法加载模型

### ISSUE THREAD

**Issue by wang-kangkang** [PaddlePaddle/PaddleDetection#799]
跑paddledetection，在windows平台下vs调试水果测试的这个，跑到：  
![421C661E6135525C6EA3708BDE2A645F](https://user-images.githubusercontent.com/30526278/83105098-94f48400-a0ec-11ea-97f4-dc591a35ccb7.JPG)
这个函数这里，报这个错，.cache下是有文件的。请问这是什么问题，该怎么解决？

**Comment by FDInSky** [comment]
看下你的截图，是路径分割符的问题。
ppdet/utils/download.py 里面的weight的路径是按照linux设置的，你改下这里就可以。

**Comment by wang-kangkang** [comment]
> ppdet/utils/download.py 里面的weight的路径是按照linux设置的，你改下这里就可以。

我把path改成C:\\Users\\wangkangkang\\.cache\\paddle\\weights\\yolov3_mobilenet_v1，仍然报相同的错误。

**Comment by still-wait** [comment]
@wang-kangkang 请删除`.cache\paddle\weights`下文件重新下载，或者从[链接](https://paddlemodels.bj.bcebos.com/object_detection/yolov3_mobilenet_v1_fruit.tar)下载好模型文件解压后，`-o weights=path/to/yolov3_mobilenet_v1_fruit` 就行。

**Comment by wang-kangkang** [comment]
> @wang-kangkang 请删除`.cache\paddle\weights`下文件重新下载，或者从[链接](https://paddlemodels.bj.bcebos.com/object_detection/yolov3_mobilenet_v1_fruit.tar)下载好模型文件解压后，`-o weights=path/to/yolov3_mobilenet_v1_fruit` 就行。

重新下载可以了，多谢。
能解释下什么原因吗？是我之前下载的模型少了哪个文件？

**Comment by wang-kangkang** [comment]
@still-wait 重新下载可以了，多谢。
能解释下什么原因吗？是我之前下载的模型少了哪个文件？

**Comment by still-wait** [comment]
> @still-wait 重新下载可以了，多谢。
> 能解释下什么原因吗？是我之前下载的模型少了哪个文件？

可能下载时网络问题等因素导致模型没下载完整。
