### ISSUE TITLE
ext_op安装报错

### ISSUE THREAD

**Issue by gyc137** [PaddlePaddle/PaddleDetection#8006]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Installation

### Bug描述 Describe the Bug

running install
running bdist_egg
running egg_info
writing ext_op.egg-info/PKG-INFO
writing dependency_links to ext_op.egg-info/dependency_links.txt
writing top-level names to ext_op.egg-info/top_level.txt
reading manifest file 'ext_op.egg-info/SOURCES.txt'
writing manifest file 'ext_op.egg-info/SOURCES.txt'
installing library code to build/ext_op/bdist.linux-x86_64/egg
running install_lib
running build_ext
Compiling user custom op, it will cost a few seconds.....
building 'ext_op' extension
gcc -pthread -B /home/gyc/anaconda3/envs/yoloer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/paddle/include -I/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda/include -I/home/gyc/anaconda3/envs/yoloer/include/python3.8 -c /home/gyc/PaddleDetection/ppdet/ext_op/csrc/rbox_iou/rbox_iou.cc -o /home/gyc/PaddleDetection/ppdet/ext_op/build/ext_op/lib.linux-x86_64-3.8/rbox_iou.o -DPADDLE_WITH_CUDA -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -DPADDLE_WITH_CUDA -std=c++14
cc1plus: 警告：command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -I/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/paddle/include -I/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda/include -I/home/gyc/anaconda3/envs/yoloer/include/python3.8 -c /home/gyc/PaddleDetection/ppdet/ext_op/csrc/rbox_iou/rbox_iou.cu -o /home/gyc/PaddleDetection/ppdet/ext_op/build/ext_op/lib.linux-x86_64-3.8/rbox_iou.cu.o -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -ccbin cc -Xcompiler -fPIC --expt-relaxed-constexpr -DNVCC -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11265): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11274): error: identifier "__builtin_ia32_scalefss_round" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_0000523b_00000000-6_rbox_iou.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

### 复现环境 Environment

Paddle版本为2.4.2-gpu
cuda为10.2，cudnn为7.6
gcc为8.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
参考https://github.com/PaddlePaddle/Paddle/issues/30870， 可以确保下GCC版本为8.2.0，然后移除`build`目录，重新编译下试试

**Comment by gyc137** [comment]
太奇怪了，我把paddle的版本降回2.3.2，编译就成功了。之前其他的错误也试过改变paddle的版本就解决了。

**Comment by mrljwlm** [comment]
> 太奇怪了，我把paddle的版本降回2.3.2，编译就成功了。之前其他的错误也试过改变paddle的版本就解决了。

同样的问题，用paddle2.2版本可以编译，用paddle2.4的版本编译不了 ext_op
