### ISSUE TITLE
关于faster rcnn中输入图片的大小问题

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleDetection#802]
请问在faster rcnn中  设置输入图片大小的参数在哪里设定？
除了在yaml文件中设定参数  请问default.py 在哪里

**Comment by qingqing01** [comment]
@lxk767363331 训练时输入图片大小设置在: 

https://github.com/PaddlePaddle/PaddleDetection/blob/c9edf50f03e7be85e6c6705a6b2f6e9270832caf/configs/faster_reader.yml#L19-L23

如果是fpn模型，在：

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/configs/faster_fpn_reader.yml#L19-L23

总之是在数据预处理里设置图片resize的大小。

**Comment by lxk767363331** [comment]
请问一下，网络在处理  以下两个数据时，是如何处理的，在看源代码中没有明白
   target_size: 800 
   max_size: 1333 
图片是以target_size输入 还是max_size输入？ 还是他们之间存在一定的关系，望回答 感谢

**Comment by qingqing01** [comment]
源码:
https://github.com/PaddlePaddle/PaddleDetection/blob/7bb04787ce99889331973811a1063cf6e3689914/ppdet/data/transform/operators.py#L299-L323

`target_size: 800` 是短边，`max_size: 1333` 是长(max)边。 先按照原始图片的height, width，选择短边，以Resize到短边大小为`target_size`，等比例缩放。  然后拿resize之后的长边和`max_size`比较，如果长边超过了`max_size`，则按照最长边为`max_size: 1333`，重新计算resize的scale。 再Resize。

也就是说，Resize之后的图片，短边可能是`target_size: 800`，长边不超过`max_size: 1333`。 是[800, W], [H, 800]，W, H不超过`max_size: 1333`； 或[1333, W], [H, 1333]。  


您也可以再上面函数的最后，打印shape看下。

**Comment by lxk767363331** [comment]
好的，跟我的理解的是一样的，我按照这个改的图片大小，根据k-means得到并调整的anchor，但是map一直没有提高，很奇怪&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "qingqing01"<notifications@github.com&gt;; 
发送时间: 2020年6月1日(星期一) 上午10:56
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 
抄送: "不要冲动保持心态"<767363331@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] 关于faster rcnn中输入图片的大小问题 (#802)





 
源码:
 https://github.com/PaddlePaddle/PaddleDetection/blob/7bb04787ce99889331973811a1063cf6e3689914/ppdet/data/transform/operators.py#L299-L323
 
target_size: 800 是短边，max_size: 1333 是长(max)边。 先按照原始图片的height, width，选择短边，以Resize到短边大小为target_size，等比例缩放。  然后拿resize之后的长边和max_size比较，如果长边超过了max_size，则按照最长边为max_size: 1333，重新计算resize的scale。 再Resize。
 
也就是说，Resize之后的图片，短边可能是target_size: 800，长边不超过max_size: 1333。 是[800, W], [H, 800]，W, H不超过max_size: 1333； 或[1333, W], [H, 1333]。
 
您也可以再上面函数的最后，打印shape看下。

**Comment by qingqing01** [comment]
@lxk767363331 您当前的mAP是较低吗？ 你自己的训练数据一般多大尺度呢？ 一般可以直接用RCNN的anchor先训练看下精度。

**Comment by lxk767363331** [comment]
很高兴您能解答我的问题。
      我的图片大小是200*200的，我将target_size，max_size均设置为200，下面是我使用yolov2的 kmean得到的anchor比例与大小，我将代码中的3个比例3个尺度更改为了一下五个。
设置了9W次迭代 使用aistudio训练faster rcnn  学习率设置为0.00125 最终最高的map为0.388。
      不知道为什么效果不好，如果您有一些好的建议或者想法，希望您可以解答，感谢您的回复。
rates:  [0.2765869847290149, 0.354231054302376, 0.8517519495780365, 1.0594399384287492, 2.208395071751882]
scales:  [1584.4135460163839, 3001.6197710701927, 8078.7427869256435, 8588.846125620894, 24561.813071713947]
sqrt of scales [ 39.80469251  54.78704017  89.88182679  92.67602778 156.72208865]
