### ISSUE TITLE
yolov4_voc问题 

### ISSUE THREAD

**Issue by super3kl** [PaddlePaddle/PaddleDetection#803]
https://github.com/PaddlePaddle/PaddleDetection/blob/c9edf50f03e7be85e6c6705a6b2f6e9270832caf/configs/yolov4/yolov4_cspdarknet_voc.yml#L85
针对于自己的数据集 
在 trainreader是不是少了一行  use_default_label:这个设置
下面的val和test都有这个设置 
没有这一行 在使用自己的数据集的时候
会报key error

**Comment by qingqing01** [comment]
@super3kl 可能是这个问题，可以设置看下，默认配置是VOC，就没配置了。
