### ISSUE TITLE
PP-YOLOE-R导出onnx后使用onnx Runtime推理失败

### ISSUE THREAD

**Issue by Petal99** [PaddlePaddle/PaddleDetection#8035]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

PP-YOLOE-R训练好的模型导出成ONNX之后，使用ONNX Runtime推理报错。
模型导出命令为：
`python tools/export_model.py -c configs/rotate/ppyoloe_r/ppyoloe_r_crn_s_3x_dota.yml -o weights=I:\Proj\result\output\ppyoloe_r_crn_s_3x_dota\best_model.pdparams TestReader.inputs_def.image_shape=[3,1024,1024]`
测试导出后的模型是否正常，使用paddle直接推理：
`python configs/rotate/tools/inference_benchmark.py --model_dir output_inference/ppyoloe_r_crn_s_3x_dota/ --image_dir F:\DataSets_for_CNN\DOTA_1024_5cls\val1024\images --run_mode paddle`
**结果正常**：
`Done image [50 / 2000], fps: 23.8 img / s, times per image: 42.0 ms / img
Done image [100/ 2000], fps: 21.8 img / s, times per image: 45.9 ms / img`

此后转换成onnx：
`paddle2onnx --model_dir output_inference/ppyoloe_r_crn_s_3x_dota --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file ppyoloe_r_crn_s_3x_dota.onnx`

然后测试onnx模型是否正常：
`python deploy/third_engine/onnx/infer.py --infer_cfg output_inference/ppyoloe_r_crn_s_3x_dota/infer_cfg.yml --onnx_file ppyoloe_r_crn_s_3x_dota.onnx --image_file F:\DataSets_for_CNN\DOTA_1024_5cls\val1024\images\P0801__1.0__0___686.png`

**到这里出现错误**：
![image](https://user-images.githubusercontent.com/52685620/229677229-7580ac21-6943-44d1-906e-6a3baa5df05c.png)

打开onnx模型观察算子：
![image](https://user-images.githubusercontent.com/52685620/229677604-5d2ac35c-bb0e-427f-bd32-b343a6e1379d.png)

发现这个split算子将最后一个维度长度为8的tensor，分割成了4个最后一个维度长度为1的tensor，没有对齐长度，符合报错的描述。

### 复现环境 Environment

- OS：Windows10
- paddlpaddle：2.4.2-gpu
- paddledetection:：develop
- paddle2onnx：1.0.6
- onnxruntime：1.14.1

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zzzzz1231** [comment]
我也遇到相同的问题，请问您解决了吗
