### ISSUE TITLE
在aistudio上训练fcos_r50_fpn_1x.yml上没有得到预期mAP

### ISSUE THREAD

**Issue by XianyuFFF** [PaddlePaddle/PaddleDetection#807]
您好，我在百度提供的aistudio平台提供的机器上训练默认参数的fcos没有得到预期结果。
训练命令：
python -c configs/anchor_free/fcos_r50_fpn_1x.yml --eval
请问可能是什么原因造成的？是否需要改一些参数。
大概结果只有给定训练好模型的一半

**Comment by qingqing01** [comment]
@XianyuFFF 配置默认是8卡训练，每个GPU的batch-size是2，总共的batch-size是16。如果你在AIStudio上训练，单卡的话，总的batch-size是2，需要调整总共`max_iters`，乘8，并且调整lr:

https://github.com/PaddlePaddle/PaddleDetection/blob/7bb04787ce99889331973811a1063cf6e3689914/configs/anchor_free/fcos_r50_fpn_1x.yml#L2-L3

lr调整参考FAQ:

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/FAQ.md#faq%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by XianyuFFF** [comment]
哦哦，非常感谢
