### ISSUE TITLE
PaddleDetection目前支持的学习率衰减策略

### ISSUE THREAD

**Issue by akhzz905** [PaddlePaddle/PaddleDetection#8070]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问一下，PaddleDetection 2.6支持Paddle中的所有学习率衰减策略吗？如果不完全支持，请问支持哪些。我看ppdet/optimizer/optimizer.py文件里面只有CosineDecay和PiecewiseDecay相关的代码，其他的比如ExponentialDecay、PolynomialDecay是不支持吗

**Comment by wangxinxin08** [comment]
目前PaddleDetection中没有对这些API进行封装，你可以参考CosineDecay封装一下
