### ISSUE TITLE
YOLOX训练DOTA数据集

### ISSUE THREAD

**Issue by gyc137** [PaddlePaddle/PaddleDetection#8078]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问用YOLOX训练DOTA数据集需要修改什么?
我将YOLOX的配置文件大体都按格式修改了，我想要训练100epochs，于是将max_epoch和对应的mosaic_epoch等都直接减了200，因为原配置文件是在coco数据集上跑300epochs。
然后学习率我也按照文档的方式进行了修改，单卡batch_size为2对应的学习率为0.0003125。
而数据集的处理我是按照数据准备文档处理的[https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/rotate/README.md#%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87](url)
目前的问题是，跑了几个epochs，发现mAP接近于0，而学习率也接近于0，然后显示要跑一天多的时间，实际却跑了好几天。
我这个问题是不是配置文件出问题了呢?望解答!

**Comment by nemonameless** [comment]
训检测bs这么小大概率训不出来的，建议换小模型或使用更大bs去训

**Comment by gyc137** [comment]
bs也会影响的吗?但我在PP-YOLOE-R的训练bs也是2，但效果是正常的。
