### ISSUE TITLE
paddle在CPU上运行时是否支持资源限制?

### ISSUE THREAD

**Issue by liuky74** [PaddlePaddle/PaddleDetection#8082]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好, 我们现在有一套算法是部署在CPU平台上运行的, 在该平台还部署了其他服务, 但是每次运行算法的时候paddle都会把CPU占满导致其他服务无法使用, 有没有什么方法能够控制paddle的CPU占用率?

**Comment by nemonameless** [comment]
可以先尝试改小worker_num，比如 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/configs/faster_rcnn/_base_/faster_fpn_reader.yml#L1

如果不行可能涉及框架，建议向 https://github.com/PaddlePaddle/Paddle/issues 提问看看
