### ISSUE TITLE
更换3080Ti后训练报错，大模型、小模型均提示tensor shape和内存问题。

### ISSUE THREAD

**Issue by dium6i** [PaddlePaddle/PaddleDetection#8106]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在PaddleYOLO那边提了[issue](https://github.com/PaddlePaddle/PaddleYOLO/issues/128)，更换使用PaddleDetection后依然报错。

## **老服务器**
**系统：**
CentOS Linux release 7.5.1804 (Core) 
**硬件：**
1080 8G 
驱动版本：470.86 
CUDA：版本11.4

## **新服务器1：**
**系统：**
Ubuntu 22.04
**硬件：**
3080Ti 12G 
驱动版本：525.105.17
CUDA版本：12.0

## **新服务器2：**
**系统：**
CentOS Linux release 7.9.2009 (Core) 
**硬件：**
3080Ti 12G 
驱动版本：530.30.02
CUDA版本：12.1

三者环境：
基于paddlepaddle/paddle:2.4.2-gpu-cuda10.2-cudnn7.6-trt7.0的docker镜像，安装了quirements.txt内的库。

基于相同的数据、配置，训练PicoDet-s-416模型。
老服务器运行正常；
新服务器1报错类似下面的代码：
```
Out of memory error on GPU 0. Cannot allocate 15.877086EB memory on GPU 0, 6.362915GB memory has been allocated and available memory is only 5.399963GB.
```
新服务器2报错类似下面的代码，并且加载完预训练模型后大约有20分钟才提示报错：
```
RuntimeError: (PreconditionNotMet) The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-4656394580360012950] now
```
一个报错显存不足，需要EB级别的显存，明显不合理；一个报错tensor的shape也很奇怪。
可能是哪里的问题呢？是否和CUDA版本有关呢？

## **解决**
更换使用CUDA11.7的镜像后，顺利运行。

**Comment by wangxinxin08** [comment]
感觉是环境问题，安培架构建议使用11.2的镜像

**Comment by dium6i** [comment]
> 11.2

好的，我先试试看，谢谢。

**Comment by dium6i** [comment]
> 感觉是环境问题，安培架构建议使用11.2的镜像

顺便问一下，11.7和11.2的镜像差别在哪里呢？我看镜像大小差挺多的。

**Comment by schild** [comment]
如果不想改cuda版本，因为好不容易配好的环境，那里可以修改代码bug
