### ISSUE TITLE
PPYOLOE测速GPU报错，CPU成功

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleDetection#8109]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用的是python deploy/python/infer.py --model_dir=output_inference/ppyoloe_crn_s_400e_coco --image_file=./dataset/video/images/val/00383.jpg --run_mode=paddle --device=gpu --run_benchmark=True
命令
paddledetection是2.6的cuda是11.7的，测速会报如下错误
![Uploading image.png…]()
不使用gpu就可以测速

**Comment by shangshanruowo** [comment]
![image](https://user-images.githubusercontent.com/101441487/233013688-2b6f29b3-29c3-4862-96d9-db5ef005dd3e.png)
报错图片


cpu成功图片
![image](https://user-images.githubusercontent.com/101441487/233013835-71f58352-4adc-45f6-8c4b-ad7c5aecfe36.png)

**Comment by wangxinxin08** [comment]
环境问题，可能是安装的Paddle版本与cuda/cudnn不一致，也可能是cuda路径没有设置，可以根据这些原因具体排查下

**Comment by shangshanruowo** [comment]
> 环境问题，可能是安装的Paddle版本与cuda/cudnn不一致，也可能是cuda路径没有设置，可以根据这些原因具体排查下

我都设置了呀，训练和评估推理用GPU都没问题，环境变量也默认配置了，这是我的版本号
![image](https://user-images.githubusercontent.com/101441487/233248569-a94f1f3b-8157-43fc-a022-f15bec39d95c.png)
![image](https://user-images.githubusercontent.com/101441487/233248677-003be61c-3de3-405c-af3f-bbd64c24914a.png)
会不会是其他原因呢，麻烦再问一下这个测速只能ppyoloe使用吗，ppyoloe-r可以类似测速吗

**Comment by wangxinxin08** [comment]
测速参考每一个模型的文档，虽然部署(非TRT)基本一致，但是测速方式不太一样，报错显示还是环境问题，你可以网上搜索下是不是cudnn和cuda不匹配

**Comment by shangshanruowo** [comment]
> 测速参考每一个模型的文档，虽然部署(非TRT)基本一致，但是测速方式不太一样，报错显示还是环境问题，你可以网上搜索下是不是cudnn和cuda不匹配

搜了说是可能不匹配，但我尝试了8.8和8.7的cudnn都不行呢，评估的时候加载了版本号，是这样的
![image](https://user-images.githubusercontent.com/101441487/233261269-2a6d4b96-8395-4aeb-860c-1efe2475910e.png)
cudnn官网和cuda的版本信息也是匹配的
![image](https://user-images.githubusercontent.com/101441487/233261388-34d3e8b2-2f82-4354-a551-42fdfebf6171.png)
我和paddle的版本号也是一样的
![image](https://user-images.githubusercontent.com/101441487/233261464-80a6eb4a-7139-4898-8485-74bc43b505b0.png)
我也是2.4的，我的paddledetection是2.6的，难道说cudnn还是太高了，我还要降版本吗，我用之前配的都可以训练的，是不是和paddle版本号还是不太对应呀

**Comment by shangshanruowo** [comment]
> 

解决了，是cudnn和cuda版本不一样，得安装你们paddle上规定的那个一样，好像必须cudnn是8.4.1的
![image](https://user-images.githubusercontent.com/101441487/233263811-c5b02a28-40c7-4e39-b7b3-b47c44453356.png)
