### ISSUE TITLE
在paddleDetection使用slim量化训练出错

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#811]
paddle1.7.1
slim1.0.1
使用https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/slim/quantization里面的命令行进行量化训练出错。命令如下
python slim/quantization/train.py --not_quant_pattern yolo_output
--eval
-c ./configs/yolov3_mobilenet_v1.yml
-o max_iters=30000
save_dir=./output/yolov3_mobilenet_v1_coco_quantization
LearningRate.base_lr=0.0001
LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [10000]}]"
pretrain_weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_mobilenet_v1.tar

发现在if FLAGS.eval: 里进入eval_results函数，返回值box_ap_stats是空的list
改为voc上训练，也会出错

**Comment by slf12** [comment]
> paddle1.7.1
> slim1.0.1
> 使用[https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/slim/quantization里面的命令行进行量化训练出错。命令如下](https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/slim/quantization%E9%87%8C%E9%9D%A2%E7%9A%84%E5%91%BD%E4%BB%A4%E8%A1%8C%E8%BF%9B%E8%A1%8C%E9%87%8F%E5%8C%96%E8%AE%AD%E7%BB%83%E5%87%BA%E9%94%99%E3%80%82%E5%91%BD%E4%BB%A4%E5%A6%82%E4%B8%8B)
> python slim/quantization/train.py --not_quant_pattern yolo_output
> --eval
> -c ./configs/yolov3_mobilenet_v1.yml
> -o max_iters=30000
> save_dir=./output/yolov3_mobilenet_v1_coco_quantization
> LearningRate.base_lr=0.0001
> LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [10000]}]"
> pretrain_weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_mobilenet_v1.tar
> 
> 发现在if FLAGS.eval: 里进入eval_results函数，返回值box_ap_stats是空的list
> 改为voc上训练，也会出错

报错的地方是这行吗？ https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/slim/quantization/train.py#L270 是否对代码做过修改？

**Comment by JensenHJS** [comment]
是这个地方，box_ap_stats = eval_results()，返回值box_ap_stats为空list，量化训练的代码没有修改

**Comment by slf12** [comment]
> 是这个地方，box_ap_stats = eval_results()，返回值box_ap_stats为空list，量化训练的代码没有修改

```
python tools/train.py 
--eval
-c ./configs/yolov3_mobilenet_v1.yml
-o max_iters=30000
save_dir=./output/yolov3_mobilenet_v1_coco_quantization
LearningRate.base_lr=0.0001
LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [10000]}]"
```
可以用这个命令看下正常训练会不会出错，可能是cfg.metric有问题

**Comment by JensenHJS** [comment]
可能是代码版本太旧了，或者是因为自己改了detection的一些代码，下载最新版代码得到解决。

**Comment by heavengate** [comment]
如果问题解决了，当前issue就先关闭了，如果还有问题可以reopen此issue
