### ISSUE TITLE
使用VOC格式的个人数据集训练报错

### ISSUE THREAD

**Issue by legendxty** [PaddlePaddle/PaddleDetection#812]
1、修改yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco.yml和yolov3_enhance_reader.yml，可正常训练
2、修改retinanet_r50_fpn_1x.yml和faster_fpn_reader.yml后，训练时报错如下：
2020-05-29 15:52:11,846-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
Traceback (most recent call last):
  File "tools/train.py", line 366, in <module>
    main()
  File "tools/train.py", line 144, in main
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
  File "/home/aistudio/work/PaddleDetection/ppdet/data/reader.py", line 410, in create_reader
    reader = Reader(**cfg)()
  File "/home/aistudio/work/PaddleDetection/ppdet/data/reader.py", line 204, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/home/aistudio/work/PaddleDetection/ppdet/data/source/dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "/home/aistudio/work/PaddleDetection/ppdet/data/source/voc.py", line 154, in load_roidb_and_cname2cid
    gt_class.append([cname2cid[cname]])
KeyError: 'box'

给出我的数据文件"1.xml"：
“”“
<?xml version="1.0" ?>
<annotation>
<folder>BoxTest</folder>
<filename>1.jpg</filename>
<path>E:\SteelScrap\BoxTest\1.jpg</path>
<source>
    <database>Unknown</database>
</source>
<size>
    <width>1440</width>
    <height>1080</height>
    <depth>3</depth>
</size>

<segmented>0</segmented>
    <object>
    <name>point</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
        <xmin>256</xmin>
        <ymin>586</ymin>
        <xmax>284</xmax>
        <ymax>614</ymax>
    </bndbox>
</object>
    <object>
    <name>point</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
        <xmin>270</xmin>
        <ymin>928</ymin>
        <xmax>292</xmax>
        <ymax>958</ymax>
    </bndbox>
</object>
    <object>
    <name>point</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
        <xmin>788</xmin>
        <ymin>950</ymin>
        <xmax>812</xmax>
        <ymax>976</ymax>
    </bndbox>
</object>
    <object>
    <name>point</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
        <xmin>766</xmin>
        <ymin>608</ymin>
        <xmax>796</xmax>
        <ymax>638</ymax>
    </bndbox>
</object>
    <object>
    <name>box</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
        <xmin>214</xmin>
        <ymin>564</ymin>
        <xmax>838</xmax>
        <ymax>990</ymax>
    </bndbox>
</object>
</annotation>
”“”

**不知道是不是reader里面的inputs_def->fields不一样，就是retinanet要求输入信息比较多导致的？这块怎么解决呢？**

**Comment by legendxty** [comment]
![image](https://user-images.githubusercontent.com/54163016/83236028-6d251f00-a1c5-11ea-88ad-7b7a602d347c.png)

**Comment by jerrywgz** [comment]
你的use_default_label是怎么设置的呢，看报错信息应该是类别的标签没有记录在cname2cid中导致的，如果是自己的数据集，需要先生成一个label_list.txt，其中是所有object的类别名称，然后将use_default_label设置为False。如果使用默认的设置，将会把voc数据集的类别信息存在cname2cid中

**Comment by legendxty** [comment]
label_list.txt内容：
box
point

faster_fpn_reader中设置了use_default_label: false

**Comment by legendxty** [comment]
我是在train的dataset中设置了use_default_label: false，而eval中没设置。。。
现在可以跑起来了，多谢！

**Comment by jerrywgz** [comment]
如果问题已经解决可以关闭下issue哈

**Comment by zzzfo** [comment]
我使用ppyolo训练自己的数据集也出现了这个问题，配置文件中没有use_default_label:呀
