### ISSUE TITLE
yolov3在使用IouAwareLoss时报错

### ISSUE THREAD

**Issue by wzl0329** [PaddlePaddle/PaddleDetection#813]
yolov3在使用IouAwareLoss时会报如下错误：
E0529 15:58:32.361232   507 elementwise_op_function.h:1068] Error, broadcast should not into w broadcast
E0529 15:58:32.381803   506 elementwise_op_function.h:1068] Error, broadcast should not into w broadcast
E0529 15:58:32.396085   507 elementwise_op_function.h:1068] Error, broadcast should not into w broadcast
这是什么原因呢？

**Comment by jerrywgz** [comment]
请升级至paddle2.0.0.a0版本，这个问题是1.8版本对elementwise优化时引入的错误，已在paddle2.0.0.a0版本修复
