### ISSUE TITLE
RT-DETR中AIFI能带来多少精度提升？

### ISSUE THREAD

**Issue by likyoo** [PaddlePaddle/PaddleDetection#8132]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，
感谢RT-DETR如此优秀的工作。我有一个小疑问是Attention-based Intrascale Feature Interaction (AIFI)能带来多少精度提升，我好像在文中没有找到相关的消融。

**Comment by lyuwenyu** [comment]
参考文章中的 D 和 D_s5的试验对比

**Comment by likyoo** [comment]
谢谢

**Comment by heidi-zhenhai** [comment]
Hi, where can I find 参考文章 to see D and D_s5的试验对比?  Thank you.
