### ISSUE TITLE
训练时卡在exe.run()

### ISSUE THREAD

**Issue by WuShuang1998** [PaddlePaddle/PaddleDetection#814]
(paddle) root@industry-ws981117-163com-jupyter-crhgv:~/project/PaddleDetection# python -u tools/train.py -c configs_ind/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.yml  -o pretrain_weights=./weights/oidv5_cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.tar  finetune_exclude_pretrained_params=['cls_score','bbox_pred']
2020-05-29 18:58:02,046-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
1
W0529 18:58:02.908135 13530 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 10.0
W0529 18:58:02.912559 13530 device_context.cc:260] device: 0, cuDNN Version: 7.4.

之后程序就卡住不动了

**Comment by qingqing01** [comment]
@BBT007 能说下机器环境吗？Paddle版本吗？以及`export GLOG_vmodule=operator=4`，贴下最后卡住前的log，看下是具体卡在了哪里。

**Comment by BBT007** [comment]
> @BBT007 能说下机器环境吗？Paddle版本吗？以及`export GLOG_vmodule=operator=4`，贴下最后卡住前的log，看下是具体卡在了哪里。

发现是paddle没安装成功，执行 paddle.fluid.install_check.run_check() 后只输出三行就卡住了，没有出现 Your Paddle Fluid is installed successfully!
