### ISSUE TITLE
global_config初始化位置？

### ISSUE THREAD

**Issue by wang-kangkang** [PaddlePaddle/PaddleDetection#815]
读代码的时候发现定义所有网络的类都是从global_config反射而得到的。但是我debug追踪这个变量的时候，https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/ppdet/core/workspace.py#L103  之后开始global_config就有了所有的网络结构pymodule了。无法进入更深的位置debug
我的问题是代码是在哪里读取了所有的网络结构？这个递归的merge_config（）是已什么逻辑运行的？

**Comment by qingqing01** [comment]
@wang-kangkang 

是通过 `register` 注册到 `global_config`中的:

https://github.com/PaddlePaddle/PaddleDetection/blob/7bb04787ce99889331973811a1063cf6e3689914/ppdet/core/workspace.py#L165-L180


每个模块在ppdet启动的时候通过register装饰器，注册进去，例如ResNet模块:

https://github.com/PaddlePaddle/PaddleDetection/blob/7bb04787ce99889331973811a1063cf6e3689914/ppdet/modeling/backbones/resnet.py#L487-L503

**Comment by wang-kangkang** [comment]
这两处代码位置只是说明了定义成装饰器吧，那装饰器是在哪里执行的？

**Comment by tangxuvis** [comment]
test

**Comment by liguoyu666** [comment]
遇到同样问题的路过

**Comment by wang-kangkang** [comment]
> 遇到同样问题的路过

此处的原理是用了python的装饰器，搜下装饰器的基础用法就会发现，它是在网络结构定义的函数的外层，又新增了一层函数。在主函数中import导入这些网络结构文件的时候，这些新增的函数就会执行，便实现了初始化global_config的任务。
理解这个问题有两个核心，第一是装饰器的基础，第二是import过程到底执行了什么

**Comment by liguoyu666** [comment]
> > 遇到同样问题的路过
> 
> 此处的原理是用了python的装饰器，搜下装饰器的基础用法就会发现，它是在网络结构定义的函数的外层，又新增了一层函数。在主函数中import导入这些网络结构文件的时候，这些新增的函数就会执行，便实现了初始化global_config的任务。
> 理解这个问题有两个核心，第一是装饰器的基础，第二是import过程到底执行了什么

谢谢讲解
