### ISSUE TITLE
 configs/dcn/yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.yml 报错

### ISSUE THREAD

**Issue by nosaydomore** [PaddlePaddle/PaddleDetection#816]
E0530 00:20:49.933074  7663 elementwise_op_function.h:1068] Error, broadcast should not into w broadcast 

但跑这个configs/dcn/yolov3_r50vd_dcn_db_iouloss_obj365_pretrained_coco.yml 不会报错 是iouaware loss 的错吗，在Iou loss 类下面好像有elementwise 但有好多，第一次用paddleDet 调试不太懂？

**Comment by llzhaoshuo** [comment]
你的paddle是哪个版本呀，我之前用的1.8.1也是报这个错，换成1.7.2的就好了。

**Comment by nosaydomore** [comment]
1.8.1哦，这样子哦， 谢谢

**Comment by jerrywgz** [comment]
升级到2.0.0.a0版本也可以，该错误是1.8版本引入的
