### ISSUE TITLE
修改主干结构后还能加载之前的预训练权重吗

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleDetection#8167]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问把模型的主干改了，比如多加一个卷积啥的，删除一个卷积啥的，那之前的预训练参数是不是就不能加载了，我看每个卷积都是有个数字编号的，我改了主干再加载预训练权重参数加载应该肯定对不上把

**Comment by lyuwenyu** [comment]
名字能对上的就会加载或者报错
