### ISSUE TITLE
aistudio上paddleDetection中使用visualdl

### ISSUE THREAD

**Issue by SangerY** [PaddlePaddle/PaddleDetection#817]
请问一下，paddleDetection中visualdl取代tensorboard后，在aistudio上如何实时查看训练情况，将项目地址中的notebooks及之后部分替换为visualdl，在本地网页打开好像不行，visualdl保存的logdir是自定义的。

**Comment by qingqing01** [comment]
@SangerY 

VisualDL是安装后VisualDL后，通过`visualdl`命令起个服务查看，AIStudio上可以去VisualDL下面提问看下，我们回头也测试看下是否可行。

**Comment by ShenYuhan** [comment]
您好，目前aistudio上支持visualdl 2.X版本，您可以查看使用说明
[AiStuidio帮助文档](https://ai.baidu.com/ai-doc/AISTUDIO/Dk3e2vxg9#visualdl%E5%B7%A5%E5%85%B7)
这里是一个使用demo项目
[VisualDL2.0 demo](https://aistudio.baidu.com/aistudio/projectdetail/502834)
更多关于visualdl的问题，您可以查看visualdl的repo，以及在issue中进行交流
[VisualDL repo](https://github.com/PaddlePaddle/VisualDL)

**Comment by SangerY** [comment]
@qingqing01 @ShenYuhan 收到，谢谢，已测试可行，aistudio上需要将log保存在/home/aistudio/log下
