### ISSUE TITLE
剪枝模型infer

### ISSUE THREAD

**Issue by SangerY** [PaddlePaddle/PaddleDetection#818]
请问按照官方示例对yolov3-mobilenetv1剪枝后
python slim/prune/prune.py \
-c ./configs/yolov3_mobilenet_v1.yml \
--pruned_params "yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights" \
--pruned_ratios="0.2,0.3,0.4"
剪枝后的模型评估IoU=0.5时mAP=0.458，使用python tools/infer.py进行推断未报错，但是结果只有某一个类别识别结果还算正常，其他类别基本检测不出来，同样的流程，训练的未剪枝模型IoU=0.5时mAP=0.468，使用python tools/infer.py检测结果就是正常的。
请问剪枝后的模型不能使用tools/infer.py来推断吗？该怎么对剪枝后的模型进行推理。

**Comment by heavengate** [comment]
不能直接用`tools/infer.py`，需要裁剪program，参考下这个吧~
https://github.com/PaddlePaddle/PaddleDetection/pull/825

**Comment by SangerY** [comment]
> 不能直接用`tools/infer.py`，需要裁剪program，参考下这个吧~
> #825

收到，谢谢，已测试，测试结果正确。
