### ISSUE TITLE
train.py: error: unrecognized arguments: True

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/PaddleDetection#819]
使用yoloV4训练时，打算设置使用eval,当我把它设置为True时，发生了以下错误：
usage: train.py [-h] [-c CONFIG] [-o [OPT [OPT ...]]] [-r RESUME_CHECKPOINT]
                [--fp16] [--loss_scale LOSS_SCALE] [--eval]
                [--output_eval OUTPUT_EVAL] [--use_tb USE_TB]
                [--tb_log_dir TB_LOG_DIR] [--enable_ce ENABLE_CE]
                [--is_profiler IS_PROFILER] [--profiler_path PROFILER_PATH]
train.py: error: unrecognized arguments: True
训练配置如下：#训练模型
#配置文件目录'configs/insects.yml'
!python -u PaddleDetection-release-0.3/tools/train.py -c PaddleDetection-release-0.3/configs/yolov4/yolov4_cspdarknet_voc.yml\
                                                        -o --eval True****

**Comment by jerrywgz** [comment]
如果希望在训练时进行评估，命令修改为：!python -u PaddleDetection-release-0.3/tools/train.py -c PaddleDetection-release-0.3/configs/yolov4/yolov4_cspdarknet_voc.yml
 --eval  即可
