### ISSUE TITLE
pp-shitu主体检测模型无法转onnx

### ISSUE THREAD

**Issue by edition3234** [PaddlePaddle/PaddleDetection#8194]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

官方文档说“PP-PicoDet模型部署友好: 支持PaddleLite/MNN/NCNN/OpenVINO等预测库，支持转出ONNX“，pp-shitu的主体检测模型不也是属于PicoDet类型的吗，但转onnx很多算子不支持，请问有什么办法吗，还是说只能换支持onnx的检测模型呢？

**Comment by WillWang325** [comment]
遇到了同样的问题，请问有解决方案吗？
