### ISSUE TITLE
C++推断为什么编译无法打开libpaddle_fluid.lib

### ISSUE THREAD

**Issue by kongxm889** [PaddlePaddle/PaddleDetection#821]
LINK : fatal error LNK1104: 无法打开文件“C:\Users\Administrator\Desktop\paddle_infer\fluid_inference_install_dir\paddle\lib\libpaddle_fluid.lib”

**Comment by qingqing01** [comment]
```
C:\Users\Administrator\Desktop\paddle_infer\fluid_inference_install_dir
```

这个路径存在吗？

**Comment by OliverLPH** [comment]
可以参考下这个issue [win7调用官方v1.7的库，编译出错：“无法打开文件libpaddle_fluid.lib”](https://github.com/PaddlePaddle/Paddle/issues/22993)

**Comment by kongxm889** [comment]
> 可以参考下这个问题[win7调用官方v1.7的库，编译错误：“无法打开文件libpaddle_fluid.lib”](https://github.com/PaddlePaddle/Paddle/issues/22993)

非常感谢
