### ISSUE TITLE
How do I change the size of the input image when inference?

### ISSUE THREAD

**Issue by starspder** [PaddlePaddle/PaddleDetection#8233]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Thank you for providing a good platform. I have one question.

I used RT-DETR model. The default reference size is set to 640x640. 
But, I want to change this to 320x320 and proceed with the inference, but I'm not sure how to change it. Any good ideas for this?

**Comment by lyuwenyu** [comment]
Your can change eval size from 640 to 320 in below files
1. https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/rtdetr/_base_/rtdetr_r50vd.yml#L10
2. https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/rtdetr/_base_/rtdetr_reader.yml

**Comment by starspder** [comment]
> Your can change eval size from 640 to 320 in below files
> 
> 1. https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/rtdetr/_base_/rtdetr_r50vd.yml#L10
> 2. https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/rtdetr/_base_/rtdetr_reader.yml


Oh I didn't know if I should change the rtdetr_r50vd.yml as well. It works fine. Thank you!
