### ISSUE TITLE
模型库中的学习率策略倍率是什么含义？

### ISSUE THREAD

**Issue by sleeplessai** [PaddlePaddle/PaddleDetection#826]
[ModelZoo](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/MODEL_ZOO_cn.md) 里面的模型和配置前面都有学习率调整的倍率（1x, 2x, 1.44x），请问：
1. 这一项是什么含义？
2. 实际训练中应该怎么调整设置这一项？
3. 会对性能有何种影响？

**Comment by qingqing01** [comment]
1. 1x, 2x, 1.44x是总共迭代的轮数不同，例如：

```bash
diff configs/faster_rcnn_r50_1x.yml configs/faster_rcnn_r50_2x.yml
```

会看到diff:

```
3c3
< max_iters: 180000
---
> max_iters: 360000
9c9
< weights: output/faster_rcnn_r50_1x/model_final
---
> weights: output/faster_rcnn_r50_2x/model_final
78c78
<     milestones: [120000, 160000]
---
>     milestones: [240000, 320000]
```

2x迭代轮数增大了1倍，学习率衰减的milestones也相应的增大，那相应的训练时间就增加了1倍。 

2. 实际业务数据训练:  RCNN模型训练相对快，在COCO上8GPU训练1x十多个小时，2x是三十多小时(也取决于模型)。 如果觉得时间不长，为了提高精度，可以选择2x。 在COCO数据上2x比1x的精度高，参考ModelZoo精度值，因为网络一样， 预测速度相同。  但也注意，如果选择COCO模型作为预训练，可能少量的iters也够了。

3. 性能影响： 训练时间增加，预测速度不变。

**Comment by sleeplessai** [comment]
@qingqing01 感谢回答。上述问题明白了。
还有几小点想要请教：
1. 一次iter的含义是不是表示optimizer执行一次step？即计算一次梯度，backward一次。
2. max_iters应该如何设置？比如darknet作者说对于coco每个类别至少给2000 iters。
3. lr decay milestones上述选择了2/3max_iters和8/9*max_iters两个节点作为标志，看到有些设置在80%和90%max_iters的位置，这个设置有什么技巧吗？
4. 我把FasterRCNN检测层部分修改成了几个自己的模块，训练的时候有backbone，neck，head的部分的梯度应该怎么给？哪些是要关掉的，何时又打开？数据集目前用的coco2017。

**Comment by qingqing01** [comment]
1.  是的，就是过一个batch。
2.  max_iters可以参考COCO的设置，比如YOLOv3训练271个epoch，COCO训练集图片总共118287张，270 *  (118287/64)大约50w个iter。 建议一般参考开源数据集的设置来适配自己数据。

3.  lr的decay一般选择，一个阶段lr下，loss不怎么变化时，选择降低一次lr，一般降低一次lr，指标会稍大幅度涨一次。 不要过早的降低，避免lr很快衰减到太小。

4.  可以参考FasterRCNN ResNet50在COCO上的设置，目前是ResNet50的前2个stage关掉了梯度，并且一直保持了关闭。neck, head因为没有初始化模型，都需要正常训练。

**Comment by sleeplessai** [comment]
@qingqing01 thanks for patience，按照建议开始实验了。
