### ISSUE TITLE
可视化

### ISSUE THREAD

**Issue by dcckAyou** [PaddlePaddle/PaddleDetection#8285]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我按照教程学习PaddleDetection,在可视化这里不知该如何操作。
我的系统是win10，在anaconda命令行模式下操作。
在教程《[30分钟快速上手PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/docs/tutorials/GETTING_STARTED_cn.md#7-%E8%AE%AD%E7%BB%83%E5%8F%AF%E8%A7%86%E5%8C%96)》 中，训练可视化这个章节中说的可视化步骤是，首先输入指令>python tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar，然后输入visualdl --logdir vdl_dir/scalar/，如下图所示
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/97494790/4f32d869-4240-4b5e-a85c-81c82595519e)
但是我在实际操作时，首先输入python tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar，然后回车，这时已经开始训练了，我无法再在命令行里输入第二步的visualdl --logdir vdl_dir/scalar/，也就无法实时查看训练状态了。
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/97494790/5204c8a6-7ed6-436c-b698-79a871483756)

请问是我的操作步骤有问题还是操作环境有问题？

**Comment by lyuwenyu** [comment]
新启一个终端
