### ISSUE TITLE
请问DETR模型在训练和推理过程中，inputs中的numpy类型的数据是在哪个函数中被转为tensor的？

### ISSUE THREAD

**Issue by xuewenyuan** [PaddlePaddle/PaddleDetection#8286]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如题，在ppdet下翻了很多文件也没看到

**Comment by lyuwenyu** [comment]
这个是dataloader内部做的

**Comment by xuewenyuan** [comment]
@lyuwenyu 
我在构造自定义的数据集和数据预处理时，使用paddle.Tensor类型也可以吧？还是说，我给dataloader的数据必须时numpy类型的

**Comment by lyuwenyu** [comment]
可以是numpy 也可以是tensor，，如果不想用默认的可以写个自定义的collate_fn

**Comment by xuewenyuan** [comment]
@lyuwenyu 
好的，谢谢。主要是，我需要对input的数据进行一个插值操作，使用tensor的interpolate比使用numpy更方便~
