### ISSUE TITLE
tools/infer 和 deploy/python/infer 模型导出后，图像预测结果完全不一致

### ISSUE THREAD

**Issue by chenjw1009** [PaddlePaddle/PaddleDetection#8299]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

tools/infer 和 deploy/python/infer 模型导出后，图像预测结果完全不一致

**Comment by shuaihutianxie** [comment]
请问这个问题解决了嘛
