### ISSUE TITLE
摔倒检测-相同数据，使用cpu可以检测到摔倒位置，gpu无法检测到摔倒位置

### ISSUE THREAD

**Issue by zhoushewei** [PaddlePaddle/PaddleDetection#8304]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

摔倒检测-相同数据，使用cpu可以检测到摔倒位置，gpu无法检测到摔倒位置

1、PaddleDetection-release-2.6

如下命令：输出视频流，gpu无法检测到摔倒位置
python deploy/pipeline/pipeline.py \
    --config deploy/pipeline/config/examples/infer_cfg_fall_down.yml \
    --video_file=摔倒.mp4 \
    --device=gpu
如下是gpu运行日志：

/home/dev/miniconda3/envs/env_fall4/lib/python3.8/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/home/dev/miniconda3/envs/env_fall4/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/dev/miniconda3/envs/env_fall4/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/dev/miniconda3/envs/env_fall4/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
-----------  Running Arguments -----------
KPT:
  batch_size: 8
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/dark_hrnet_w32_256x192.zip
MOT:
  batch_size: 1
  enable: true
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_pipeline.zip
  tracker_config: deploy/pipeline/config/tracker_config.yml
SKELETON_ACTION:
  batch_size: 1
  coord_size:
  - 384
  - 512
  display_frames: 80
  enable: true
  max_frames: 50
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/STGCN.zip
crop_thresh: 0.5
kpt_thresh: 0.2
visual: true
warmup_frame: 50

------------------------------------------
Multi-Object Tracking enabled
SkeletonAction Recognition enabled
MOT  model dir:  /home/dev/.cache/paddle/infer_weights/mot_ppyoloe_l_36e_pipeline
KPT  model dir:  /home/dev/.cache/paddle/infer_weights/dark_hrnet_w32_256x192
SKELETON_ACTION  model dir:  /home/dev/.cache/paddle/infer_weights/STGCN
-----------  Model Configuration -----------
Model Arch: STGCN
Transform Order:
--transform op: AutoPadding
--------------------------------------------
-----------  Model Configuration -----------
Model Arch: HRNet
Transform Order:
--transform op: TopDownEvalAffine
--transform op: Permute
--------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: Permute
--------------------------------------------
video fps: 29, frame_count: 203
Thread: 0; frame id: 0
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 10
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 20
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 30
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 40
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 50
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 60
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 70
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 80
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 90
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 100
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 110
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 120
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 130
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 140
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 150
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 160
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 170
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
[WARNNING] No object detected.
Thread: 0; frame id: 180
[WARNNING] No object detected.
Thread: 0; trackid number: 0
[WARNNING] No object detected.
[WARNNING] No object detected.
save result to output/摔倒.mp4
------------------ Inference Time Info ----------------------
total_time(ms): 1685531909421.6, img_num: 133
mot time(ms): 4883.9; per frame average time(ms): 36.72105263157894
average latency time(ms): 12673172251.29, QPS: 0.000000
------------------ Tracking Module Time Info ----------------------
preprocess_time(ms): 2.20, inference_time(ms): 33.90, postprocess_time(ms): 0.10, tracking_time(ms): 0.10

-------------------------------------
如下命令：输出视频流，cpu可以检测到摔倒位置

python deploy/pipeline/pipeline.py \
    --config deploy/pipeline/config/examples/infer_cfg_fall_down.yml \
    --video_file=摔倒.mp4 \
    --device=cpu
如下是cpu下日志：
/home/dev/miniconda3/envs/env_fall4/lib/python3.8/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/home/dev/miniconda3/envs/env_fall4/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/dev/miniconda3/envs/env_fall4/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/dev/miniconda3/envs/env_fall4/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
-----------  Running Arguments -----------
KPT:
  batch_size: 8
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/dark_hrnet_w32_256x192.zip
MOT:
  batch_size: 1
  enable: true
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_pipeline.zip
  tracker_config: deploy/pipeline/config/tracker_config.yml
SKELETON_ACTION:
  batch_size: 1
  coord_size:
  - 384
  - 512
  display_frames: 80
  enable: true
  max_frames: 50
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/STGCN.zip
crop_thresh: 0.5
kpt_thresh: 0.2
visual: true
warmup_frame: 50

------------------------------------------
Multi-Object Tracking enabled
SkeletonAction Recognition enabled
MOT  model dir:  /home/dev/.cache/paddle/infer_weights/mot_ppyoloe_l_36e_pipeline
KPT  model dir:  /home/dev/.cache/paddle/infer_weights/dark_hrnet_w32_256x192
SKELETON_ACTION  model dir:  /home/dev/.cache/paddle/infer_weights/STGCN
-----------  Model Configuration -----------
Model Arch: STGCN
Transform Order:
--transform op: AutoPadding
--------------------------------------------
-----------  Model Configuration -----------
Model Arch: HRNet
Transform Order:
--transform op: TopDownEvalAffine
--transform op: Permute
--------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: Permute
--------------------------------------------
video fps: 29, frame_count: 203
Thread: 0; frame id: 0
Thread: 0; trackid number: 1
Thread: 0; frame id: 10
Thread: 0; trackid number: 1
Thread: 0; frame id: 20
Thread: 0; trackid number: 1
Thread: 0; frame id: 30
Thread: 0; trackid number: 1
Thread: 0; frame id: 40
Thread: 0; trackid number: 1
Thread: 0; frame id: 50
Thread: 0; trackid number: 1
Thread: 0; frame id: 60
Thread: 0; trackid number: 1
Thread: 0; frame id: 70
Thread: 0; trackid number: 1
Thread: 0; frame id: 80
Thread: 0; trackid number: 1
Thread: 0; frame id: 90
Thread: 0; trackid number: 1
Thread: 0; frame id: 100
Thread: 0; trackid number: 1
Thread: 0; frame id: 110
Thread: 0; trackid number: 1
Thread: 0; frame id: 120
Thread: 0; trackid number: 1
Thread: 0; frame id: 130
Thread: 0; trackid number: 1
Thread: 0; frame id: 140
Thread: 0; trackid number: 1
Thread: 0; frame id: 150
Thread: 0; trackid number: 1
Thread: 0; frame id: 160
Thread: 0; trackid number: 1
Thread: 0; frame id: 170
Thread: 0; trackid number: 1
Thread: 0; frame id: 180
Thread: 0; trackid number: 1
save result to output/摔倒.mp4
------------------ Inference Time Info ----------------------
total_time(ms): 194437.6, img_num: 132
mot time(ms): 166907.90000000002; per frame average time(ms): 1264.453787878788
kpt time(ms): 27462.7; per trackid average time(ms): 208.0507575757576
skeleton_action time(ms): 50.6; per trackid average time(ms): 0.38333333333333336
average latency time(ms): 1473.01, QPS: 0.678881
------------------ Tracking Module Time Info ----------------------

### 复现环境 Environment

OS: ubuntu 18.04
PaddlePaddle: 2.4.2.post112
PaddleDetection: release/2.6
Python: 3.8.0
CUDA: 11.4 
CUDNN: 8.0.5.39-1
GCC:  7.5.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zhoushewei** [comment]
已经解决，有个别包版本过高导致，麻烦研发 写一下开发环境每个包的具体版本

**Comment by Qianqiu1** [comment]
想问一下是哪个包的版本不对啊，遇到了一样的问题

**Comment by Qianqiu1** [comment]
> 已经解决，有个别包版本过高导致，麻烦研发 写一下开发环境每个包的具体版本

想问一下是哪个包的版本不对啊，遇到了一样的问题
