### ISSUE TITLE
yolov4 效果差

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleDetection#831]
loss降低得很好(相比yolov3更好), 但是推理结果很差. 同样的数据集用yolov3去训练map能达到90+,但是yolov4却不到20. 可能是哪里没做对?

**Comment by qingqing01** [comment]
您两者都加载了COCO的预训练模型吗？

**Comment by thunder95** [comment]
是的 都加载了默认的预训练模型

**Comment by qingqing01** [comment]
@thunder95 能说下配置分别是哪个吗？v4的配置是 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/configs/yolov4/yolov4_cspdarknet_voc.yml 这个吗？ 以及训练方式，有没有做什么改动之类的？

**Comment by thunder95** [comment]
我在做那个AI识虫的作业, 就作了基本的配置改动,如类别数量,anno和image的路径, 把batch_size改到了12, 后来又动了下anchors的设置. 训练就直接用的命令python -u tools/train.py -c  configs/insects/insects_yolov4_v1.yml


[insects_yolov4_v1.txt](https://github.com/PaddlePaddle/PaddleDetection/files/4709544/insects_yolov4_v1.txt)

**Comment by qingqing01** [comment]
@thunder95  你配置中 Gt2YoloTarget中的anchor设置和YOLOv4Head中的anchor设置不一样。改成统一的看下。
