### ISSUE TITLE
yolov3_darknet问题

### ISSUE THREAD

**Issue by super3kl** [PaddlePaddle/PaddleDetection#835]
数据集是自己转的人流密度数据集为coco格式 
自己服务器来train  显卡titanxp
train的时候
creating index...
index created!
2020-06-01 16:55:32,798-INFO: places would be ommited when DataLoader is not iterable
这行打印出来之后 就没再动过  显存占用 900多m  ctrl + c 无法退出 要直接关掉terminal才行  
debug之后发现 一直在卡class SharedQueue当中的 

```
    def get(self, **kwargs):
        """ get an object from this queue
        """

        buff = None
        try:
            print('try')
            buff = super(SharedQueue, self).get(**kwargs)
            data = buff.get()
            return pickle.load(StringIO(data))
        except Empty as e:
            raise e
        except Exception as e:
            stack_info = traceback.format_exc()
            err_msg = 'failed to get element from SharedQueue '\
                        'with stack info[%s]' % (stack_info)
            logger.warn(err_msg)
            raise e
        finally:
            if buff is not None:
                buff.free()
```
我在try后面打印了一下  print（‘try’）
然后命令行就一直在打印try 大概 频率几秒钟一个
是一直卡在读数据吗？ 还是什么
之前用这个做红绿灯 没有这种情况

**Comment by qingqing01** [comment]
@super3kl   你用的那个配置呢？以及batch_size多大？ 几个建议:

1.  可以再YML配置中设置use_process=False 看下。
2. 也可以不做1，设置TrainReader里配置`memsize`，默认是3G，可以增大或减小看下，配置`memsize: 1G`, `memsize: 512M`试下。

**Comment by super3kl** [comment]
@qingqing01  
设为false后  debug 会卡在https://github.com/PaddlePaddle/PaddleDetection/blob/7bb04787ce99889331973811a1063cf6e3689914/ppdet/data/parallel_map.py#L233

第二个办法也用了 没有用

**Comment by heavengate** [comment]
数据读取和预处理很耗时么，启动之后看下`top -c`信息呢？

**Comment by super3kl** [comment]
这个问题好像是因为我在转成coco数据的格式的时候一张图的每个bbox的label 我都给了 iscrowd为1 
@qingqing01 @heavengate

**Comment by heavengate** [comment]
yolo模型不读`is_crowd`的bbox的，所以图片上会没有bbox，然后被`drop_empty`丢弃，所以一直没有数据进入训练，可以把`is_crowd`设置成0，应该就可以解决了
