### ISSUE TITLE
yolov3模型尝试配置softnms和diounms出错

### ISSUE THREAD

**Issue by StarryDing** [PaddlePaddle/PaddleDetection#836]
![image](https://user-images.githubusercontent.com/53610587/83397900-f8561d00-a430-11ea-816e-249639b0bf98.png)
我修改了图中两处的代码....都改成了MultiClassSoftNMS
![image](https://user-images.githubusercontent.com/53610587/83398242-90540680-a431-11ea-90f7-b07d0c260666.png)
在yml文件里也修改了对应的地方
![image](https://user-images.githubusercontent.com/53610587/83398375-d27d4800-a431-11ea-8ad1-ff0ef3264540.png)

运行的时候报错
![image](https://user-images.githubusercontent.com/53610587/83399008-09a02900-a433-11ea-8db9-c0022de30edb.png)
![image](https://user-images.githubusercontent.com/53610587/83399036-16bd1800-a433-11ea-9cc2-3da61bcdac90.png)

**Comment by StarryDing** [comment]
class YOLOv3Head(object):
    """
    Head block for YOLOv3 network

    Args:
        norm_decay (float): weight decay for normalization layer weights
        num_classes (int): number of output classes
        anchors (list): anchors
        anchor_masks (list): anchor masks
        nms (object): an instance of `MultiClassNMS`
    """
    __inject__ = ['yolo_loss', 'nms']
    __shared__ = ['num_classes', 'weight_prefix_name']

    def __init__(self,
                 norm_decay=0.,
                 num_classes=80,
                 anchors=[[10, 13], [16, 30], [33, 23], [30, 61], [62, 45],
                          [59, 119], [116, 90], [156, 198], [373, 326]],
                 anchor_masks=[[6, 7, 8], [3, 4, 5], [0, 1, 2]],
                 drop_block=False,
                 iou_aware=False,
                 iou_aware_factor=0.4,
                 block_size=3,
                 keep_prob=0.9,
                 yolo_loss="YOLOv3Loss",
                 nms=MultiClassSoftNMS(
                    score_threshold=0.01,
                    keep_top_k=300,
                    softnms_sigma=0.5,
                    normalized=False,
                    background_label=-1, ).__dict__,
                 weight_prefix_name='',
                 downsample=[32, 16, 8],
                 scale_x_y=1.0,
                 clip_bbox=True):
        self.norm_decay = norm_decay
        self.num_classes = num_classes
        self.anchor_masks = anchor_masks
        self._parse_anchors(anchors)
        self.yolo_loss = yolo_loss
        self.nms = nms
        self.prefix_name = weight_prefix_name
        self.drop_block = drop_block
        self.iou_aware = iou_aware
        self.iou_aware_factor = iou_aware_factor
        self.block_size = block_size
        self.keep_prob = keep_prob
        if isinstance(nms, dict):
            self.nms = MultiClassSoftNMS(**nms)
        self.downsample = downsample
        self.scale_x_y = scale_x_y
        self.clip_bbox = clip_bbox

这段里面的原来的MultiClassNMS都被我改成了MultiClassSoftNMS
YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    score_threshold: 0.01
    keep_top_k: 300
    softnms_sigma: 0.5
    normalized: False
    background_label: -1
yml文件里面原来nms的地方的配置我也改成了MultiClassSoftNMS的参数.....

然后运行出来报错
W0601 18:08:17.680256   123 operator.cc:181] py_func raises an exception pybind11::error_already_set, ValueError: all the input arrays must have same number of dimensions

At:
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/core/shape_base.py(340): hstack
  /home/aistudio/PaddleDetection/ppdet/modeling/ops.py(567): _soft_nms
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py(12409): __call__
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py(905): _run_program
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py(831): _run_impl
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py(778): run
  PaddleDetection/tools/output.py(221): main
  PaddleDetection/tools/output.py(287): <module>
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "PaddleDetection/tools/output.py", line 287, in <module>
    main()
  File "PaddleDetection/tools/output.py", line 221, in main
    return_numpy=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 831, in _run_impl
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 905, in _run_program
    fetch_var_name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12409, in __call__
    func_ret = self._func(*args[idx:], **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/ops.py", line 567, in _soft_nms
    dets_j = np.hstack((scores_j[:, np.newaxis], rois_j)).astype(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/core/shape_base.py", line 340, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input arrays must have same number of dimensions
terminate called without an active exception
W0601 18:08:17.763780   185 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0601 18:08:17.763890   185 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0601 18:08:17.763893   185 init.cc:214] The detail failure signal is:

W0601 18:08:17.763901   185 init.cc:217] *** Aborted at 1591006097 (unix time) try "date -d @1591006097" if you are using GNU date ***
W0601 18:08:17.766463   185 init.cc:217] PC: @                0x0 (unknown)
W0601 18:08:17.766628   185 init.cc:217] *** SIGABRT (@0x3e80000007b) received by PID 123 (TID 0x7f1f50832700) from PID 123; stack trace: ***
W0601 18:08:17.768649   185 init.cc:217]     @     0x7f1fc2374390 (unknown)
W0601 18:08:17.770494   185 init.cc:217]     @     0x7f1fc1fce428 gsignal
W0601 18:08:17.772351   185 init.cc:217]     @     0x7f1fc1fd002a abort
W0601 18:08:17.773488   185 init.cc:217]     @     0x7f1f81e8d84a __gnu_cxx::__verbose_terminate_handler()
W0601 18:08:17.774309   185 init.cc:217]     @     0x7f1f81e8bf47 __cxxabiv1::__terminate()
W0601 18:08:17.775389   185 init.cc:217]     @     0x7f1f81e8bf7d std::terminate()
W0601 18:08:17.776458   185 init.cc:217]     @     0x7f1f81e8bc5a __gxx_personality_v0
W0601 18:08:17.777392   185 init.cc:217]     @     0x7f1f821beb97 _Unwind_ForcedUnwind_Phase2
W0601 18:08:17.778200   185 init.cc:217]     @     0x7f1f821bee7d _Unwind_ForcedUnwind
W0601 18:08:17.780490   185 init.cc:217]     @     0x7f1fc2373070 __GI___pthread_unwind
W0601 18:08:17.782480   185 init.cc:217]     @     0x7f1fc236b845 __pthread_exit
W0601 18:08:17.783164   185 init.cc:217]     @     0x55701a0c1e59 PyThread_exit_thread
W0601 18:08:17.783432   185 init.cc:217]     @     0x557019f47c17 PyEval_RestoreThread.cold.798
W0601 18:08:17.783879   185 init.cc:217]     @     0x7f1f76d8129c (unknown)
W0601 18:08:17.784402   185 init.cc:217]     @     0x55701a043744 _PyMethodDef_RawFastCallKeywords
W0601 18:08:17.784883   185 init.cc:217]     @     0x55701a043861 _PyCFunction_FastCallKeywords
W0601 18:08:17.785351   185 init.cc:217]     @     0x55701a0af2bd _PyEval_EvalFrameDefault
W0601 18:08:17.785786   185 init.cc:217]     @     0x557019ff3539 _PyEval_EvalCodeWithName
W0601 18:08:17.786221   185 init.cc:217]     @     0x557019ff4635 _PyFunction_FastCallDict
W0601 18:08:17.786650   185 init.cc:217]     @     0x55701a012e53 _PyObject_Call_Prepend
W0601 18:08:17.786911   185 init.cc:217]     @     0x55701a04aa3a slot_tp_call
W0601 18:08:17.787353   185 init.cc:217]     @     0x55701a04b8fb _PyObject_FastCallKeywords
W0601 18:08:17.787827   185 init.cc:217]     @     0x55701a0aee86 _PyEval_EvalFrameDefault
W0601 18:08:17.788332   185 init.cc:217]     @     0x557019ff456b _PyFunction_FastCallDict
W0601 18:08:17.788810   185 init.cc:217]     @     0x55701a012e53 _PyObject_Call_Prepend
W0601 18:08:17.789054   185 init.cc:217]     @     0x55701a04aa3a slot_tp_call
W0601 18:08:17.789495   185 init.cc:217]     @     0x55701a04b8fb _PyObject_FastCallKeywords
W0601 18:08:17.789971   185 init.cc:217]     @     0x55701a0af6e8 _PyEval_EvalFrameDefault
W0601 18:08:17.790401   185 init.cc:217]     @     0x557019ff3539 _PyEval_EvalCodeWithName
W0601 18:08:17.790809   185 init.cc:217]     @     0x55701a042ef5 _PyFunction_FastCallKeywords
W0601 18:08:17.791309   185 init.cc:217]     @     0x55701a0aaa93 _PyEval_EvalFrameDefault
W0601 18:08:17.791721   185 init.cc:217]     @     0x55701a042ccb _PyFunction_FastCallKeywords
Aborted (core dumped)

**Comment by StarryDing** [comment]
我又重新试了下直接在yml里面配置运行
YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms: MultiClassSoftNMS

MultiClassSoftNMS:
  score_threshold: 0.01
  keep_top_k: 300
  softnms_sigma: 0.5
  normalized: False
  background_label: -1

还是报一样的错...

**Comment by heavengate** [comment]
本issue由 https://github.com/PaddlePaddle/PaddleDetection/issues/843 继续跟踪，当前issue先关闭
