### ISSUE TITLE
RT-DETR训练进程过半后，所有evaluation环节结果为0

### ISSUE THREAD

**Issue by hahapt** [PaddlePaddle/PaddleDetection#8380]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在模型训练至第49个epoch并进行evaluation时，一切结果正常如下：
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.750
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.920
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.805
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.066
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.666
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.896
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.340
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.785
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.827
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.190
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.785
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.931

在模型训练至第54个epoch后，所有evaluation结果为0：
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000

在第49至54个epoch训练过程中，并未出现异常报错

**Comment by wmjlincy** [comment]
你好，我从一开始训练的mAP都是0，但是loss在下降，请问你解决了吗，可不可以指导一下，非常感谢~

**Comment by hzhaoy** [comment]
同问，请问你们解决了吗 @hahapt @wmjlincy

**Comment by hzhaoy** [comment]
同问，请问你们解决了吗 @hahapt @wmjlincy

**Comment by lyuwenyu** [comment]
你们使用的代码的commit id是多少，  这个是在coco上试验的原始的代码 https://github.com/lyuwenyu/RT-DETR 可以先试一下   @hahapt  @wmjlincy @hzhaoy

**Comment by hzhaoy** [comment]
> 你们使用的代码的commit id是多少， 这个是在coco上试验的原始的代码 https://github.com/lyuwenyu/RT-DETR 可以先试一下 @hahapt @wmjlincy @hzhaoy

@lyuwenyu 好的谢谢！我这边是ppyoloe的问题，已经解决了，主要是因为有些图片名有中文导致无法读取，样本数比batch_szie，所以训练不成功
