### ISSUE TITLE
关于旋转框识别coco数据的疑惑

### ISSUE THREAD

**Issue by wxf764571829** [PaddlePaddle/PaddleDetection#8392]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

用的paddleDetection版本为最新版本 pad为2.4 在训练的时候出现了以下错误，我想问下旋转coco数据的具体格式是什么？我用的x2coco转的数据 ：
![1687742005200](https://github.com/PaddlePaddle/PaddleDetection/assets/46362180/d3f9282f-7dff-4cd6-add0-0be63a788286)

 我转换的数据如下，请教一下这个数据是哪里有问题？
{"images": [{"file_name": "1000.JPG", "height": 512.0, "width": 640.0, "id": 0}], "type": "instances", "annotations": [{"area": 10156.53868608, "segmentation": [[317.0, 474.0, 290.0, 474.0, 282.0, 99.0, 309.0, 98.0]], "category_id": 1, "ignore": 0, "iscrowd": 0, "image_id": 0, "id": 1}, {"area": 10156.53868608, "segmentation": [[349.0, 470.0, 322.0, 470.0, 314.0, 95.0, 341.0, 94.0]], "category_id": 1, "ignore": 0, "iscrowd": 0, "image_id": 0, "id": 2}], "categories": [{"supercategory": "none", "id": 1, "name": "jyz"}]}

**Comment by lyuwenyu** [comment]
解决了嘛
