### ISSUE TITLE
将模型转为onnx后使用deploy\third_engine\onnx\infer.py进行推理，如何配置是否使用GPU，不进行配置的话默认是用CPU推理的

### ISSUE THREAD

**Issue by JoyFuture** [PaddlePaddle/PaddleDetection#8393]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

是否需要增加什么参数python deploy\third_engine\onnx\infer.py --infer_cfg inference_model\ppyoloe_plus_crn_t_auxhead_300e_coco\infer_cfg.yml --onnx_file crn_t_3
00e.onnx --image_file 648.png

**Comment by lyuwenyu** [comment]
得安装`onnxruntime-gpu`版本，具体使用可以查一下ort的使用文档
