### ISSUE TITLE
行人属性识别二次开发

### ISSUE THREAD

**Issue by nuonuo0426** [PaddlePaddle/PaddleDetection#8397]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

进行行人属性识别二次开发，关于PaddleDetection 和训练代码PaddleClas的关系，两个代码很多都重复了，她们应该属于两个代码项目，但是训练又要在PaddleClas中进行，数据又放在PaddleDetection中，不能只用PaddleClas进行训练嘛？看二次开发的时候有点懵，能不能跟我讲一下她们两个的关系呀？开发的时候是不是两个代码同时进行的哇，求求了

**Comment by lyuwenyu** [comment]
是的 并行做的，侧重点不一样 一个是主要做分类的 一个是主要做检测的
