### ISSUE TITLE
ValueError: could not broadcast input array from shape (4032,3024,3) into shape (3024,4032,3)

### ISSUE THREAD

**Issue by felixgalaxy** [PaddlePaddle/PaddleDetection#840]
用网络爬取的数据集单张图80k左右，训练都正常
但是用自己拍的数据集训练，单张图片2m，一共300多张图，训练报错，是因为图片太大吗？请问应该怎么处理呢，如果裁剪或者resize了我标注的xml文件是不是不可以使用了？求助
2020-06-01 18:38:51,718-WARNING: recv endsignal from outq with errmsg[consumer[consumer-bab-2] failed to map with error:[could not broadcast input array from shape (4032,3024,3) into shape (3024,4032,3)]]
2020-06-01 18:39:04,304-INFO: fail to map op [RandomExpand_d635b1] with error: could not broadcast input array from shape (4032,3024,3) into shape (3024,4032,3) and stack:
Traceback (most recent call last):
  File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/reader.py", line 45, in __call__
    data = f(data, ctx)
  File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/transform/operators.py", line 1268, in __call__
    canvas[y:y + height, x:x + width, :] = img.astype(np.uint8)
ValueError: could not broadcast input array from shape (4032,3024,3) into shape (3024,4032,3)

Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by heavengate** [comment]
是不是xml里面的标注图像的height和width标反了

**Comment by felixgalaxy** [comment]
> 是不是xml里面的标注图像的height和width标反了

没有呀xml就是width,4032   height，3024呀
<annotation>
	<folder>FALL</folder>
	<filename>IMG647.jpg</filename>
	<path>C:\Users\DELL\Desktop\windows_v1.8.1\windows_v1.8.1\data\FALL\IMG647.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>4032</width>
		<height>3024</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>abnormal</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>85</xmin>
			<ymin>911</ymin>
			<xmax>3212</xmax>
			<ymax>2459</ymax>
		</bndbox>
	</object>
</annotation>

**Comment by heavengate** [comment]
```
canvas[y:y + height, x:x + width, :] = img.astype(np.uint8)
ValueError: could not broadcast input array from shape (4032,3024,3) into shape (3024,4032,3)
```
这个报错，前面的height和width是从xml里读取的，后面`img.astype(np.uint8)`是图像的实际尺寸，前面是`(4032,3024,3)`后面是`(3024,4032,3)`，原因就是xml的height和width和图像的实际height和width是反的，可以排查一下数据

**Comment by felixgalaxy** [comment]
> ```
> canvas[y:y + height, x:x + width, :] = img.astype(np.uint8)
> ValueError: could not broadcast input array from shape (4032,3024,3) into shape (3024,4032,3)
> ```
> 
> 这个报错，前面的height和width是从xml里读取的，后面`img.astype(np.uint8)`是图像的实际尺寸，前面是`(4032,3024,3)`后面是`(3024,4032,3)`，原因就是xml的height和width和图像的实际height和width是反的，可以排查一下数据

我标注的数据集是没有问题的呀，请问这个应该怎么解决呢？
![11](https://user-images.githubusercontent.com/49911457/83481158-a31d1880-a4cf-11ea-920f-86544a7d4c39.JPG)
![22](https://user-images.githubusercontent.com/49911457/83481170-ab755380-a4cf-11ea-9e29-be8b17889404.JPG)

**Comment by heavengate** [comment]
问题确实是标注的宽高和实际的宽高反了，如果你没有修改数据预处理配置的话，可以排查一下
1. 报错是报在这张图像上么，是不是数据集里面有哪副图像的反了
2. 可以用下面python代码查看图像的宽高，得到的应该是[height, width, 3]
```python
import cv2
img = cv2.imread('./test.jpg')
print(img.shape)
```

**Comment by felixgalaxy** [comment]
> 问题确实是标注的宽高和实际的宽高反了，如果你没有修改数据预处理配置的话，可以排查一下
> 
> 1. 报错是报在这张图像上么，是不是数据集里面有哪副图像的反了
> 2. 可以用下面python代码查看图像的宽高，得到的应该是[height, width, 3]
> 
> ```python
> import cv2
> img = cv2.imread('./test.jpg')
> print(img.shape)
> ```
感谢解答 我发现数据集中有的4032,3024   有的4032,3024，是xml的问题
