### ISSUE TITLE
RT-DETR训练COCO2017数据集，训练时eval的map一直是0

### ISSUE THREAD

**Issue by wmjlincy** [PaddlePaddle/PaddleDetection#8400]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我用RT-DETR训练COCO2017数据集，训练时eval的mAP一直是0，且loss在不断下降，pretrain_weights加载的是ResNet50_vd_ssld_v2_pretrained.pdparams，其他参数没做改动；除此之外，每次eval保存的bbox.json文件中，每张图片保存了300个检测框，但是每个检测框的类别、box位置和score都是一样的，请问我需要怎么解决呢？非常期待大佬能够回答一下我的问题，感激不尽~

**Comment by wmjlincy** [comment]
问题已解决，感谢大佬，笔芯~

**Comment by hzhaoy** [comment]
> 

请问是怎么解决的呢？我这边用ppyoloe的模型+自己的数据集，训练时eval的bbox ap也一直是0
