### ISSUE TITLE
must be Tensor, but got Tensor

### ISSUE THREAD

**Issue by AxeBlue** [PaddlePaddle/PaddleDetection#8401]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

ValueError: (InvalidArgument) multiclass_nms3(): argument 'BBoxes' (position 0) must be Tensor, but got Tensor (at /paddle/paddle/fluid/pybind/op_function_common.cc:818)

根据  https://github.com/PaddlePaddle/PaddleDetection/issues/7623  这个问题，看起来需要升级ppdet，但是我的项目是基于ppdet二次开发的，目录结构为
-xxxx
     -xxxx
     -xxxx
     -ppdet
     ...
有什么办法可以升级ppdet吗？

不想通过降级paddle版本使用，paddle 2.4引入了比较重要的dataloader的prefetcher_factor特性，我想试试能加速多少（也不是很懂torch实现了很久的东西paddle刚实现...）

**Comment by lyuwenyu** [comment]
可以用最新的paddle试一下
