### ISSUE TITLE
voc_utils.py存在Bug??

### ISSUE THREAD

**Issue by bodstersll** [PaddlePaddle/PaddleDetection#8406]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Other

### Bug描述 Describe the Bug

在使用create_list.py准备自定义数据集时，创建trainval.txt与test.txt失败
查看调用发现create_list()函数中调用了一个_walk_voc_dir()函数：

![91535ce8a8d068c6b5a2f64defb22cf](https://github.com/PaddlePaddle/PaddleDetection/assets/122479731/c0a2afe9-ea91-4738-af96-cc0aafa2344e)

请问这个的意思是，将trainval_list 和test_list置空以后直接返回？
![1688366706345](https://github.com/PaddlePaddle/PaddleDetection/assets/122479731/158f727a-899a-46d4-b23d-c7043e594ed8)

那么在后续的处理中，trainval, test这两个值始终为空？

### 复现环境 Environment

根据官网文档：https://paddledetection.readthedocs.io/tutorials/Custom_DataSet.html#id3
方式二：将数据集转换为VOC格式
运行
```
python dataset/voc/create_list.py -d path/to/dataset
```
无法正常创建trainval.txt和test.txt文件

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
定位到问题了嘛

**Comment by bodstersll** [comment]
> 定位到问题了嘛

应该就是返回值不对，需要在_walk_voc_dir函数的for循环里面加上trainval_list.append() 和 test_list_append() 逻辑，现在创建了trainval_list 和 test_list 后直接以空值返回了
