### ISSUE TITLE
视频流检测每帧速度太低怎么办？

### ISSUE THREAD

**Issue by LongLivecn** [PaddlePaddle/PaddleDetection#841]
我用的coco2017官方数据集在paddledetection上用给的PaddleDetection/configs/dcn/yolov3_r50vd_dcn_obj365_pretrained_coco.yml配置文件进行训练，然后用export_model.py转换模型，然后用infer检测一段视频，但是视频的检测速度好慢，只有1800多ms每张，请问怎么提高视频流的检测速度呢？

**Comment by heavengate** [comment]
用的是什么设备呢，CPU还是GPU，什么型号呢

**Comment by LongLivecn** [comment]
> 用的是什么设备呢，CPU还是GPU，什么型号呢

就用的AI Studio的TeslaV100进行视频流检测，然后把结果下载到自己的电脑上进行播放
