### ISSUE TITLE
BatchRandomResize中参数问题

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/PaddleDetection#8417]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

BatchRandomResize函数中target_size列表中的元素组合是[宽, 高]还是[高, 宽]

**Comment by lyuwenyu** [comment]
h 和 w
