### ISSUE TITLE
AttributeError: 'ImageDraw' object has no attribute 'textsize'

### ISSUE THREAD

**Issue by todesti2** [PaddlePaddle/PaddleDetection#8418]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

当我执行python tools/infer.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml -o weights=weights/rtdetr_r50vd_6x_coco.pdparams --infer_img=person.jpg  的时候，出现了上面的报错，请问这是为什么呢

**Comment by lyuwenyu** [comment]
rtdetr可以先这样 https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetr_paddle/ppdet/utils/visualizer.py#L128-L130

后续会合到ppdet里。

**Comment by todesti2** [comment]
谢谢您的建议。我当时是将pillow从10.0.0降到了7.1.2，然后这个报错居然没有了，哈哈哈真的很神奇！
但是，在我执行infer.py文件时，虽然能正确推理，但也出现了以下警告（实践证明，这些警告在后面我训练时有着很大的问题）：
WARNING: OMP_NUM_THREADS set to 12, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads.
PLEASE USE OMP_NUM_THREADS WISELY.
W0712 20:20:03.731561  1045 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.0, Runtime API Version: 11.2
W0712 20:20:03.741592  1045 gpu_resources.cc:149] device: 0, cuDNN Version: 8.1.

1.我将OMP_NUM_THREADS设置为1，再次执行就没有了这个警告
2.后面的警告我都解决不了 
其中cudnn版本的问题困扰了我好久，对于paddlepaddle、cuda、cudnn三者版本之间的版本我一直没能平衡好，请问您有什么建议吗，再次感谢您的回复！

**Comment by todesti2** [comment]
补充一下上面：
在autodl云服务器上，cuda 11.2 对应的cudnn是 8.1.1，但是我搜索后了解到为了适应paddlepaddle需要换成8.2.1版本的cudnn，因此我大费周折卸载和安装了相应的8.2.1的cudnn，但是不知为什么按照网上教程都没能配置好。所以现在非常苦恼，期待您的回复

**Comment by gangula-karthik** [comment]
managed to fix it by doing 

```
left, top, right, bottom = draw.textbbox((0, 0), text)
tw, th = right - left, bottom - top
```
 
instead of this on line 162 of deploy/python/visualize.py
```
tw, th = draw.textsize(text)
```
