### ISSUE TITLE
训练出现长警告

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/PaddleDetection#8419]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

训练出现长警告
```
I0706 13:09:13.075042 3772 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify 'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
I0706 13:09:13.382442 3772 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify 'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
```

### 复现环境 Environment

PaddleDetection2.6
PaddlePaddle2.5.0

经过排查将`ppdet/utils/stats.py`第77行进行如下修改
`v.update(stats[k].numpy())`→`v.update(float(stats[k]))`

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
感谢反馈，会尽快修复

**Comment by sdreamforchen** [comment]
> 感谢反馈，会尽快修复

我也遇到这个问题。但是有一次又出现是int。  所以这里是不是不要numpy()更好

**Comment by zdong22** [comment]
的确有这个问题，其它项目中看到是需要回退paddle版本到2.4，如 https://github.com/PaddlePaddle/PaddleOCR/issues/10295 ，这样能解决最好，感谢 GuoQuanhao

**Comment by lizhaoliaooo** [comment]
感谢这位同学

**Comment by joisonwk** [comment]
这个有修复了吗？ 我也遇到这个2.5.1  将loss_function返回的张量转numpy就会一直打印此警告。

**Comment by JiFfeng-Yu** [comment]
PaddleDetection2.6第77行原本就是这个了v.update(float(stats[k]))

**Comment by linuaries** [comment]
解决困扰我许久的问题，谢谢
