### ISSUE TITLE
利用增强版yolo v3训练时报错

### ISSUE THREAD

**Issue by feelinggxj** [PaddlePaddle/PaddleDetection#842]
报错如下
![52b253188641733ef4f20c9fc1f0012](https://user-images.githubusercontent.com/53445122/83410169-6fe37680-a448-11ea-9497-5f575a713b73.png)
![0694fb3dc7f90f20b418919894f82ec](https://user-images.githubusercontent.com/53445122/83410205-81c51980-a448-11ea-82a6-52a8e50ace12.png)
请问是什么原因导致的，是输入的数据集有问题吗？我之前在群里咨询了一下 他说试着换成.2/.3版本的paddledetection；但是经过尝试后还是报一样的错误

**Comment by feelinggxj** [comment]
使用模型YOLOv3 ResNet50_vd DCN

**Comment by soldier828** [comment]
我也是，之前从来没报过错。  环境也没动，是什么情况？  难道是远程的模型url出了问题？

**Comment by heavengate** [comment]
是否修改了`yolov3_r50vd_dcn.yml`里的`YOLOv3Loss.batch_size`, 这个`batch_size`值需要和`yolov3_reader.yml`里的`TrainReader.batch_size`值一致，看报错信息里是吧`YOLOv3Loss.batch_size`改成了32，但是`TrainReader.batch_size`没有修改，另外PaddleDetection里的`batch_size`都是指单卡batch_size，如果设置32的话需要很大的显存，建议确认一下

**Comment by feelinggxj** [comment]
是修改了batch_size，两个都设为了32是需要降一些吗

**Comment by heavengate** [comment]
> 是修改了batch_size，两个都设为了32是需要降一些吗

看报错信息，是`YOLOv3Loss.batch_size`设置为了32，但是`TrainReader.batch_size`还是8，需要统一。
另外参考你单卡显存大小，比如16G显存最大batch_size在14左右

**Comment by feelinggxj** [comment]
感谢回复 谢谢您 我在检查一下 麻烦了

**Comment by heavengate** [comment]
好的，如果有问题我们再继续跟进，如果没问题麻烦关闭一下issue~

**Comment by feelinggxj** [comment]
已经解决了 batchsize都调小。 但有个问题想要请教您 如果希望训练的效果好些 用增强模型型需要调整那些部分的参数 调大batch_size有没有效果

**Comment by heavengate** [comment]
可以使用COCO数据集上训练好的权重作为预训练权重进行迁移学习，参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md
