### ISSUE TITLE
pipe_util.py中crop_image_with_det方法中的start_idx貌似没有自增

### ISSUE THREAD

**Issue by Sijia-NR** [PaddlePaddle/PaddleDetection#8425]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

将infer_cfg_pphuman.yml配置文件中ATTR的batch_size改为大于1时(比如4)，使用多张照片推理时，比如：
```python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_pphuman.yml  --image_dir=demo/``` 会出现```    im_scale_x = resize_w / float(origin_shape[1])
ZeroDivisionError: float division by zero```的问题，我大概找到问题在pipe_util.py中crop_image_with_det方法中的start_idx貌似没有自增，在188行添加start_idx = start_idx + boxes_num_i 应该就可以解决问题

### 复现环境 Environment

macOS paddlepaddle2.4.1 PaddleDetection-release-2.6 python3.7

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Sijia-NR** [comment]
请帮忙确认一下 是否应该这么修改

**Comment by lyuwenyu** [comment]
提个PR我看下吧
