### ISSUE TITLE
yolov3用softnms数组形状报错问题

### ISSUE THREAD

**Issue by StarryDing** [PaddlePaddle/PaddleDetection#843]
![image](https://user-images.githubusercontent.com/53610587/83444032-57da1a00-a47d-11ea-9562-221dd28bf0be.png)
这个地方的两个数组输出的形状不一样
![image](https://user-images.githubusercontent.com/53610587/83443905-1e091380-a47d-11ea-842a-9a3da8442769.png)
还有 class_nums指的是什么啊 是分类数还是预测框总数啊
看代码的意思好像是预测框总数
但是看这句inds = np.where(scores[:, j] >= softnms_thres)[0]的意思又好像是分类数啊

**Comment by heavengate** [comment]
对于YOLO模型来说，class_num是分类数，对于RCNN/SSD来说，class_num是分类数+1，由于RCNN/SSD需要包含背景类

**Comment by heavengate** [comment]
请问具体报错信息是啥呢

**Comment by StarryDing** [comment]
![image](https://user-images.githubusercontent.com/53610587/83473889-37ca4b00-a4bd-11ea-973c-26e596e20619.png)
这边的scores.shape[-1]输出出来是22743啊
class_nums是分类数的话我感觉应该是scores.shape[1]的


报错信息是这个
W0602 02:57:07.562767   446 operator.cc:181] py_func raises an exception pybind11::error_already_set, ValueError: all the input arrays must have same number of dimensions

At:
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/core/shape_base.py(340): hstack
  /home/aistudio/PaddleDetection/ppdet/modeling/ops.py(571): _soft_nms
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py(12409): __call__
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py(905): _run_program
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py(831): _run_impl
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py(778): run
  PaddleDetection/tools/output.py(221): main
  PaddleDetection/tools/output.py(287): <module>
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "PaddleDetection/tools/output.py", line 287, in <module>
    main()
  File "PaddleDetection/tools/output.py", line 221, in main
    return_numpy=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 831, in _run_impl
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 905, in _run_program
    fetch_var_name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12409, in __call__
    func_ret = self._func(*args[idx:], **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/ops.py", line 571, in _soft_nms
    dets_j = np.hstack((scores_j[:, np.newaxis], rois_j)).astype(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/core/shape_base.py", line 340, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input arrays must have same number of dimensions
terminate called without an active exception
W0602 02:57:07.637873   507 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0602 02:57:07.637912   507 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0602 02:57:07.637917   507 init.cc:214] The detail failure signal is:

W0602 02:57:07.637933   507 init.cc:217] *** Aborted at 1591037827 (unix time) try "date -d @1591037827" if you are using GNU date ***
W0602 02:57:07.640224   507 init.cc:217] PC: @                0x0 (unknown)
W0602 02:57:07.640341   507 init.cc:217] *** SIGABRT (@0x3e8000001be) received by PID 446 (TID 0x7f30f320a700) from PID 446; stack trace: ***
W0602 02:57:07.642202   507 init.cc:217]     @     0x7f3164726390 (unknown)
W0602 02:57:07.643931   507 init.cc:217]     @     0x7f3164380428 gsignal
W0602 02:57:07.645642   507 init.cc:217]     @     0x7f316438202a abort
W0602 02:57:07.646749   507 init.cc:217]     @     0x7f312423f84a __gnu_cxx::__verbose_terminate_handler()
W0602 02:57:07.647564   507 init.cc:217]     @     0x7f312423df47 __cxxabiv1::__terminate()
W0602 02:57:07.648564   507 init.cc:217]     @     0x7f312423df7d std::terminate()
W0602 02:57:07.649456   507 init.cc:217]     @     0x7f312423dc5a __gxx_personality_v0
W0602 02:57:07.650231   507 init.cc:217]     @     0x7f3124570b97 _Unwind_ForcedUnwind_Phase2
W0602 02:57:07.650995   507 init.cc:217]     @     0x7f3124570e7d _Unwind_ForcedUnwind
W0602 02:57:07.652741   507 init.cc:217]     @     0x7f3164725070 __GI___pthread_unwind
W0602 02:57:07.654450   507 init.cc:217]     @     0x7f316471d845 __pthread_exit
W0602 02:57:07.654983   507 init.cc:217]     @     0x55d81c27be59 PyThread_exit_thread
W0602 02:57:07.655133   507 init.cc:217]     @     0x55d81c101c17 PyEval_RestoreThread.cold.798
W0602 02:57:07.655467   507 init.cc:217]     @     0x7f311913329c (unknown)
W0602 02:57:07.655967   507 init.cc:217]     @     0x55d81c1fd744 _PyMethodDef_RawFastCallKeywords
W0602 02:57:07.656445   507 init.cc:217]     @     0x55d81c1fd861 _PyCFunction_FastCallKeywords
W0602 02:57:07.656920   507 init.cc:217]     @     0x55d81c2692bd _PyEval_EvalFrameDefault
W0602 02:57:07.657354   507 init.cc:217]     @     0x55d81c1ad539 _PyEval_EvalCodeWithName
W0602 02:57:07.657804   507 init.cc:217]     @     0x55d81c1ae635 _PyFunction_FastCallDict
W0602 02:57:07.658241   507 init.cc:217]     @     0x55d81c1cce53 _PyObject_Call_Prepend
W0602 02:57:07.658468   507 init.cc:217]     @     0x55d81c204a3a slot_tp_call
W0602 02:57:07.658907   507 init.cc:217]     @     0x55d81c2058fb _PyObject_FastCallKeywords
W0602 02:57:07.659374   507 init.cc:217]     @     0x55d81c268e86 _PyEval_EvalFrameDefault
W0602 02:57:07.659807   507 init.cc:217]     @     0x55d81c1ae56b _PyFunction_FastCallDict
W0602 02:57:07.660243   507 init.cc:217]     @     0x55d81c1cce53 _PyObject_Call_Prepend
W0602 02:57:07.660465   507 init.cc:217]     @     0x55d81c204a3a slot_tp_call
W0602 02:57:07.660907   507 init.cc:217]     @     0x55d81c2058fb _PyObject_FastCallKeywords
W0602 02:57:07.661375   507 init.cc:217]     @     0x55d81c2696e8 _PyEval_EvalFrameDefault
W0602 02:57:07.661840   507 init.cc:217]     @     0x55d81c1ad539 _PyEval_EvalCodeWithName
W0602 02:57:07.662261   507 init.cc:217]     @     0x55d81c1fcef5 _PyFunction_FastCallKeywords
W0602 02:57:07.662729   507 init.cc:217]     @     0x55d81c264a93 _PyEval_EvalFrameDefault
W0602 02:57:07.663139   507 init.cc:217]     @     0x55d81c1fcccb _PyFunction_FastCallKeywords
Aborted (core dumped)

**Comment by heavengate** [comment]
这里的scores和bboxes应该是一个LoDTensor，你是怎么实现的在yolov3用softnms呢

**Comment by StarryDing** [comment]
我改yml文件还有改yolo_head代码都试过了
一开始改yml文件是这么改的...
YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms: MultiClassSoftNMS

MultiClassSoftNMS:
  score_threshold: 0.01
  keep_top_k: 300
  softnms_sigma: 0.5
  normalized: False
  background_label: -1


后来改的yolo_head的代码，把这两地方都换成softnms了
![image](https://user-images.githubusercontent.com/53610587/83482312-8fbf7c80-a4d2-11ea-8dd1-a0177343e551.png)
然后ymm文件里面 就直接把参数换成了softnms的
![image](https://user-images.githubusercontent.com/53610587/83482411-cf866400-a4d2-11ea-9e73-c31b5b419f9d.png)

然后这两种改法报错都是一样的...是我的用法有问题么

**Comment by qingqing01** [comment]
@StarryDing 已经复现，我们排查后回复你

**Comment by qingqing01** [comment]
@StarryDing  Fixed in https://github.com/PaddlePaddle/PaddleDetection/pull/854

但注意， 对于YOLOv3，在COCO数据上测试有效，在VOC数据上发现效果不好。 你使用时注意下。

配置，替换nms为：

```
MultiClassSoftNMS:
  score_threshold: 0.01
  keep_top_k: 100
  softnms_sigma: 0.5
  background_label: -1
```

**Comment by StarryDing** [comment]
@qingqing01 感谢感谢
