### ISSUE TITLE
Can RTDETR allow single-class( i.e. 1 category only) object detection? 

### ISSUE THREAD

**Issue by foresee-ai** [PaddlePaddle/PaddleDetection#8430]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

 After I modified RTDETR's code and used AGORA (head only) dataset's annotation, my code can be trained, evaluated, and tested.  But the head detection's evaluation mAP is very bad, only 0.002  after 75 epoch training.  I am suspecting if Hungarian matcher can be the problem.  From DETR's paper, DETR uses Hungarian Matcher to pick proper prediction candidates associated with the ground truth targets.  The cost function for Hungarian Matcher depends on the class, bbox, and giou losses.  But here the class loss seems not working properly and leads to the low mAP evaluation.  Do you have any ideas to help solve the problem?  Thank you!

Heidi

**Comment by lyuwenyu** [comment]
rtdetr fix a bug https://github.com/PaddlePaddle/PaddleDetection/pull/8409, you can try lastest ppdet or original  exp code https://github.com/lyuwenyu/RT-DETR

**Comment by foresee-ai** [comment]
Thank you very much for the quick response. I've checked bug #8409, and found gt_score occurs in following 4 files, [rtdetr_paddle/ppdet/data/source/voc.py](https://github.com/lyuwenyu/RT-DETR/blob/60b6e83849fba4c0594a045282445f5ee26e25d7/rtdetr_paddle/ppdet/data/source/voc.py#L141), [rtdetr_paddle/ppdet/data/transform/batch_operators.py](https://github.com/lyuwenyu/RT-DETR/blob/60b6e83849fba4c0594a045282445f5ee26e25d7/rtdetr_paddle/ppdet/data/transform/batch_operators.py#L157), [rtdetr_paddle/ppdet/modeling/transformers/utils.py](https://github.com/lyuwenyu/RT-DETR/blob/60b6e83849fba4c0594a045282445f5ee26e25d7/rtdetr_paddle/ppdet/modeling/transformers/utils.py#L437), and [‎rtdetr_paddle/ppdet/data/transform/operators.py](https://github.com/lyuwenyu/RT-DETR/blob/60b6e83849fba4c0594a045282445f5ee26e25d7/rtdetr_paddle/ppdet/data/transform/operators.py#L1577).  Since I don't use VOC's data format, the first file is not relevant.  So I'll check the rest files to see how to modify the code.

**Comment by john09282922** [comment]
> Thank you very much for the quick response. I've checked bug #8409, and found gt_score occurs in following 4 files, [rtdetr_paddle/ppdet/data/source/voc.py](https://github.com/lyuwenyu/RT-DETR/blob/60b6e83849fba4c0594a045282445f5ee26e25d7/rtdetr_paddle/ppdet/data/source/voc.py#L141), [rtdetr_paddle/ppdet/data/transform/batch_operators.py](https://github.com/lyuwenyu/RT-DETR/blob/60b6e83849fba4c0594a045282445f5ee26e25d7/rtdetr_paddle/ppdet/data/transform/batch_operators.py#L157), [rtdetr_paddle/ppdet/modeling/transformers/utils.py](https://github.com/lyuwenyu/RT-DETR/blob/60b6e83849fba4c0594a045282445f5ee26e25d7/rtdetr_paddle/ppdet/modeling/transformers/utils.py#L437), and [‎rtdetr_paddle/ppdet/data/transform/operators.py](https://github.com/lyuwenyu/RT-DETR/blob/60b6e83849fba4c0594a045282445f5ee26e25d7/rtdetr_paddle/ppdet/data/transform/operators.py#L1577). Since I don't use VOC's data format, the first file is not relevant. So I'll check the rest files to see how to modify the code.

Hi, did you fix the problem using single class, if you fix, plz let me know which part I should have to be changed

**Comment by foresee-ai** [comment]
Hi,

Sorry to reply late.  I have not yet solved the problem.   I've made quite
a few modifications on the Transformer Decoder and the Hungarian Matcher to
allow the network to output the object score instead of classification.
 And the output is still not ideal.

Heidi
