### ISSUE TITLE
PicoFeat 卷积神经网络通道数bug

### ISSUE THREAD

**Issue by xuyouqian** [PaddlePaddle/PaddleDetection#8432]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

错误代码链接：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/ppdet/modeling/heads/pico_head.py
第59行 PicoFeat 类中bug

在第112 行  创建 cls_conv_pw 变量的设置中：入通道为in_c，
 但是 cls_conv_pw 接收 上面 cls_conv_dw 的输出作为输入，而cls_conv_dw输出的通道数是cls_conv_dw。这样通道数不一致了。

只需要把 115行的 `ch_in=in_c` 改为 `ch_in=feat_out` 即可

### 复现环境 Environment

-OS：Linux

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
方便提个PR嘛

**Comment by xuyouqian** [comment]
提交了哈
