### ISSUE TITLE
使用官方提供的权重和配置文件复现多类别多目标跟踪(MCMOT)时，指标差异较大

### ISSUE THREAD

**Issue by ChenG-53** [PaddlePaddle/PaddleDetection#8439]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

感谢百度飞桨深度学习框架的开源，我在进行多目标多类别跟踪实验复现时，遇到了一些困难，如下：

选取数据集 VisDrone Vehicle val-set，使用如下指令进行评估：
(1) CUDA_VISIBLE_DEVICES=0 python tools/eval_mot.py -c configs/mot/mcfairmot/mcfairmot_dla34_30e_1088x608_visdrone_vehicle_bytetracker.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/mcfairmot_dla34_30e_1088x608_visdrone_vehicle_bytetracker.pdparams
官方结果：MOTA 为 37.7，IDF1 为 56.8，IDS 为 199
实际结果：MOTA 为 34.3，IDF1 为 47.2，IDS 为 1186

(2) CUDA_VISIBLE_DEVICES=0 python tools/eval_mot.py -c configs/mot/mcfairmot/mcfairmot_hrnetv2_w18_dlafpn_30e_1088x608_visdrone_vehicle_bytetracker.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/mcfairmot_hrnetv2_w18_dlafpn_30e_1088x608_visdrone_vehicle_bytetracker.pdparams
官方结果：MOTA 为 35.6，IDF1 为 56.3，IDS 为 190
实际结果：MOTA 为 32.0，IDF1 为 45.3，IDS 为 1311

实验环境：PyTorch  1.10.0，Python  3.8(ubuntu20.04)，Cuda  11.3

请问指标差异大可能是什么原因引起的，非常期待您的回答！

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/5377/files#diff-dd8452a5676c3480ef31145d38be13f82495784e896c0e7c3c696708b7bebaa7
ppdet/modeling/mot/tracker/jde_tracker.py
这个改回去mcfairmot精度应该就对了，应该是embedding特征的影响 ，但是fairmot + byte在MOT17上精度会掉了。后面会更新文档，为了精度可以暂时先改下。

**Comment by ChenG-53** [comment]
感谢您的回复！根据您的意见修改以后，测试精度与文档中的更加接近了，但是仍然有些许差距。
选取数据集 VisDrone Vehicle val-set，使用如下指令进行评估：
(1) CUDA_VISIBLE_DEVICES=0 python tools/eval_mot.py -c configs/mot/mcfairmot/mcfairmot_dla34_30e_1088x608_visdrone_vehicle_bytetracker.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/mcfairmot_dla34_30e_1088x608_visdrone_vehicle_bytetracker.pdparams
官方结果：MOTA 为 37.7，IDF1 为 56.8，IDS 为 199
实际结果：MOTA 为 34.3，IDF1 为 47.2，IDS 为 1186
修改后的结果：MOTA 为 37.1，IDF1 为 55.1，IDS 为 202

(2) CUDA_VISIBLE_DEVICES=0 python tools/eval_mot.py -c configs/mot/mcfairmot/mcfairmot_hrnetv2_w18_dlafpn_30e_1088x608_visdrone_vehicle_bytetracker.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/mcfairmot_hrnetv2_w18_dlafpn_30e_1088x608_visdrone_vehicle_bytetracker.pdparams
官方结果：MOTA 为 35.6，IDF1 为 56.3，IDS 为 190
实际结果：MOTA 为 32.0，IDF1 为 45.3，IDS 为 1311
修改后的结果：MOTA 为 36.0，IDF1 为 55.0，IDS 为 198
