### ISSUE TITLE
convnext large预训练权重

### ISSUE THREAD

**Issue by Oswells** [PaddlePaddle/PaddleDetection#8444]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我想要一个convnext large的预训练权重，但是paddledet里没有，paddleseg cls里代码又和det不太一样，我看这里代码和mmdet比较接近，mmdet可以转paddledet的权重吗？有对应脚本可以实现这个吗？

**Comment by lyuwenyu** [comment]
https://bj.bcebos.com/v1/paddledet/models/pretrained/convnext_large_1k_224_ema.pdparams
https://bj.bcebos.com/v1/paddledet/models/pretrained/convnext_large_22k_224.pdparams
https://bj.bcebos.com/v1/paddledet/models/pretrained/convnext_large_1k_384.pdparams

**Comment by Oswells** [comment]
谢谢
