### ISSUE TITLE
请问是否可基于PicoDet进行旋转框训练，或者是否有超轻量化的旋转框模型？

### ISSUE THREAD

**Issue by ashe2333** [PaddlePaddle/PaddleDetection#8445]
### 是否愿意提交PR Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
picodet目前不支持旋转框 也没有超轻量化的旋转框模型 ，不过可以在picodet上参考ppyoloe的旋转框进行修改

**Comment by ashe2333** [comment]
好的，请问一下picodet的网络结构代码在哪里有说明呢

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/ppdet/modeling/architectures/picodet.py 参考这个文件
