### ISSUE TITLE
Screen annotation customization

### ISSUE THREAD

**Issue by helloimdomas** [PaddlePaddle/PaddleDetection#8449]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

I am using the pipeline with these arguments: 
`ATTR:
  batch_size: 8
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/PPLCNet_x1_0_person_attribute_945_infer.zip
DET:
  batch_size: 1
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_s_36e_pipeline.zip
ID_BASED_CLSACTION:
  batch_size: 8
  display_frames: 80
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/PPHGNet_tiny_calling_halfbody.zip
  skip_frame_num: 2
  threshold: 0.8
ID_BASED_DETACTION:
  batch_size: 8
  display_frames: 80
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/ppyoloe_crn_s_80e_smoking_visdrone.zip
  skip_frame_num: 2
  threshold: 0.6
KPT:
  batch_size: 8
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/dark_hrnet_w32_256x192.zip
MOT:
  batch_size: 1
  enable: true
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_s_36e_pipeline.zip
  skip_frame_num: 2
  tracker_config: deploy/pipeline/config/tracker_config.yml
REID:
  batch_size: 16
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/reid_model.zip
SKELETON_ACTION:
  batch_size: 1
  coord_size:
  - 384
  - 512
  display_frames: 80
  enable: false
  max_frames: 50
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/STGCN.zip
VIDEO_ACTION:
  batch_size: 1
  enable: false
  frame_len: 8
  model_dir: https://videotag.bj.bcebos.com/PaddleVideo-release2.3/ppTSM_fight.zip
  sample_freq: 7
  short_size: 340
  target_size: 320
attr_thresh: 0.5
crop_thresh: 0.5
kpt_thresh: 0.2
visual: true
warmup_frame: 50

------------------------------------------
Multi-Object Tracking enabled
DET  model dir:  /home/etm/.cache/paddle/infer_weights/mot_ppyoloe_s_36e_pipeline
MOT  model dir:  /home/etm/.cache/paddle/infer_weights/mot_ppyoloe_s_36e_pipeline
KPT  model dir:  /home/etm/.cache/paddle/infer_weights/dark_hrnet_w32_256x192
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: Permute
`
Where can I change the thickness of the boxes (human annotation on screen), and the language of object names (currently it is in English: pedestrian_1, pedestrian_2... ). And how to make the calculations font size at the top left corner bigger? I can barely see it. 
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/76450741/958fb292-4265-4f25-adc4-3b2b2a8f4ab8)

![image](https://github.com/PaddlePaddle/PaddleDetection/assets/76450741/91c58e81-9d8b-4788-a66e-d2b8cecbb196)

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/ppdet/utils/visualizer.py#L35
画图的最终的代码在这，但是你得看下tracker里怎么调用的
