### ISSUE TITLE
为什么使用 ppyoloe+ 训练，将epoch从80修改为300后，训练完之后模型反而没有检测到目标，epoch为80的时候有目标，这是什么原因？

### ISSUE THREAD

**Issue by Hudaiguo** [PaddlePaddle/PaddleDetection#8456]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

为什么使用 ppyoloe+ 训练，将epoch从80修改为300后，训练完之后模型反而没有检测到目标，epoch为80的时候有目标，这是什么原因？

**Comment by lyuwenyu** [comment]
过拟合了吧

**Comment by Hudaiguo** [comment]
不是，我是使用相同的数据相同的模型(yoloe+ large )训练的。修改的ppyoloe_plus_crn_l_80e_coco.yml文件中'./_base_/optimizer_80e.yml'，训练之后模型可以检测出目标来，修改为'./_base_/optimizer_300e.yml'后，从0轮的300轮过程中一些模型都检测不出目标框来（目标的置信度很低，0.01-0.03）。



在 2023-07-21 13:10:47，"Wenyu" ***@***.***> 写道：

过拟合了吧

**Comment by lyuwenyu** [comment]
看下这两个的diff lr不一样吧
