### ISSUE TITLE
AttributeError: module 'ppdet.data.source' has no attribute 'IR_Dataset'

### ISSUE THREAD

**Issue by mtthwryn** [PaddlePaddle/PaddleDetection#8473]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

I am trying to finetune a ppyoloe model using a custom dataset but I encounter into this error when runnning the training script as provide in the readme for custom detection. Has anyone encountered this error before? I have already modified the coco_detection.yml which contains all the relevant paths to my images and annotations

**Comment by lyuwenyu** [comment]
`IR_Dataset` 这名字怎么来的？ 默认没有吧

**Comment by XWWW-XD** [comment]
同问，我也遇到了
