### ISSUE TITLE
怎么实时目标检测？

### ISSUE THREAD

**Issue by 2625009538** [PaddlePaddle/PaddleDetection#8479]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我看示例都是用的图片，我是想在视频当中使用，类似在足球场追踪球员那个，是在视频中使用。但是我只看到对图片的目标检测？请问我应该怎么操作？我是新手刚刚入行~麻烦说的详细点，谢谢~另外，我如果有多张图片，有木有类似huggingface的python代码，而不是命令行python -c 这种？谢谢~

**Comment by 2625009538** [comment]
补充一下，是用的RT-DETR

**Comment by lyuwenyu** [comment]
多张图片和一张一样的吧 多加个for循环， 或者 如果你用tools/infer.py有个img_dir的参数 文件里的结果都会处理

**Comment by 2625009538** [comment]
好的谢谢您。我以为能和yolo v8一样，直接让我输入视频呢，原来还需要自己对视频取每一帧呀。再次表示感谢。









      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 ***@***.***&gt; 于2023年7月27日(周四) 上午9:15写道:

  

 
多张图片和一张一样的吧 多加个for循环， 或者 如果你用tools/infer.py有个img_dir的参数 文件里的结果都会处理

**Comment by whisky-12** [comment]
我想知道 我如果想做到实时的效果， 比如有一个摄像头，可客户端直接查看摄像头视频时， 就可以看到检测结果

**Comment by WangShengFeng1** [comment]
> 我想知道 我如果想做到实时的效果， 比如有一个摄像头，可客户端直接查看摄像头视频时， 就可以看到检测结果

请问您实现了吗？我也想这么做，不知道怎么做
