### ISSUE TITLE
使用faster-rcnn进行训练时报错

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/PaddleDetection#848]
portlib; see the module's documentation for alternative uses
  import imp
2020-06-02 12:42:45,690-INFO: The 'num_classes'(number of classes) you set is 1, and 'with_background' in 'dataset' sets True.
So please note the actual number of categories is 0.
2020-06-02 12:42:46,152-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
2020-06-02 12:42:47,251-WARNING: /home/aistudio/.cache/paddle/weights/ResNet50_cos_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-06-02 12:42:47,536-WARNING: /home/aistudio/.cache/paddle/weights/ResNet50_cos_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-06-02 12:42:47,544-WARNING: variable file [ /home/aistudio/.cache/paddle/weights/ResNet50_cos_pretrained/fc_0.b_0 /home/aistudio/.cache/paddle/weights/ResNet50_cos_pretrained/fc_0.w_0 ] not used
2020-06-02 12:42:48,402-INFO: places would be ommited when DataLoader is not iterable
W0602 12:42:48.744968   130 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
W0602 12:42:48.813226   130 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 72. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 72.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "PaddleDetection-release-0.3/tools/train.py", line 366, in <module>
    main()
  File "PaddleDetection-release-0.3/tools/train.py", line 239, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::operators::math::CrossEntropyFunctor<paddle::platform::CPUDeviceContext, float>::operator()(paddle::platform::CPUDeviceContext const&, paddle::framework::Tensor*, paddle::framework::Tensor const*, paddle::framework::Tensor const*, bool, int, int)
2   paddle::operators::SoftmaxWithCrossEntropyKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::SoftmaxWithCrossEntropyKernel<float>, paddle::operators::SoftmaxWithCrossEntropyKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::details::ComputationOpHandle::RunImpl()
8   paddle::framework::details::OpHandleBase::Run(bool)
9   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
10  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
11  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
12  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
13  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/loss.py", line 1267, in softmax_with_cross_entropy
    attrs=attrs)
  File "/home/aistudio/PaddleDetection-release-0.3/ppdet/modeling/roi_heads/bbox_head.py", line 277, in get_loss
    logits=cls_score, label=labels_int64, numeric_stable_mode=True)
  File "/home/aistudio/PaddleDetection-release-0.3/ppdet/modeling/architectures/faster_rcnn.py", line 138, in build
    bbox_outside_weights)
  File "/home/aistudio/PaddleDetection-release-0.3/ppdet/modeling/architectures/faster_rcnn.py", line 240, in train
    return self.build(feed_vars, 'train')
  File "PaddleDetection-release-0.3/tools/train.py", line 113, in main
    train_fetches = model.train(feed_vars)
  File "PaddleDetection-release-0.3/tools/train.py", line 366, in <module>
    main()

----------------------
Error Message Summary:
----------------------
OutOfRangeError: label value should less than the shape of axis dimension when label value(1) not equal to ignore_index(-100), But received label value as 1 and shape of axis dimension is 1
  [Hint: Expected lbl < axis_dim, but received lbl:1 >= axis_dim:1.] at (/paddle/paddle/fluid/operators/math/cross_entropy.cc:69)
  [operator < softmax_with_cross_entropy > error]
terminate called without an active exception
W0602 12:43:08.481303   138 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0602 12:43:08.481348   138 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0602 12:43:08.481351   138 init.cc:221] The detail failure signal is:

W0602 12:43:08.481365   138 init.cc:224] *** Aborted at 1591072988 (unix time) try "date -d @1591072988" if you are using GNU date ***
W0602 12:43:08.483203   138 init.cc:224] PC: @                0x0 (unknown)
W0602 12:43:08.483292   138 init.cc:224] *** SIGABRT (@0x3e800000082) received by PID 130 (TID 0x7f7548bc1700) from PID 130; stack trace: ***
W0602 12:43:08.484649   138 init.cc:224]     @     0x7f758bba0390 (unknown)
W0602 12:43:08.485941   138 init.cc:224]     @     0x7f758b7fa428 gsignal
W0602 12:43:08.487212   138 init.cc:224]     @     0x7f758b7fc02a abort
W0602 12:43:08.488373   138 init.cc:224]     @     0x7f758577d84a __gnu_cxx::__verbose_terminate_handler()
W0602 12:43:08.489341   138 init.cc:224]     @     0x7f758577bf47 __cxxabiv1::__terminate()
W0602 12:43:08.490411   138 init.cc:224]     @     0x7f758577bf7d std::terminate()
W0602 12:43:08.491417   138 init.cc:224]     @     0x7f758577bc5a __gxx_personality_v0
W0602 12:43:08.492664   138 init.cc:224]     @     0x7f758aaaeb97 _Unwind_ForcedUnwind_Phase2
W0602 12:43:08.493966   138 init.cc:224]     @     0x7f758aaaee7d _Unwind_ForcedUnwind
W0602 12:43:08.495290   138 init.cc:224]     @     0x7f758bb9f070 __GI___pthread_unwind
W0602 12:43:08.496600   138 init.cc:224]     @     0x7f758bb97845 __pthread_exit
W0602 12:43:08.496923   138 init.cc:224]     @     0x55b400fede59 PyThread_exit_thread
W0602 12:43:08.497007   138 init.cc:224]     @     0x55b400e73c17 PyEval_RestoreThread.cold.798
W0602 12:43:08.497707   138 init.cc:224]     @     0x7f756bf24119 pybind11::gil_scoped_release::~gil_scoped_release()
W0602 12:43:08.498006   138 init.cc:224]     @     0x7f756c000d95 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybind10BindReaderEPNS_6moduleEEUlRNS2_9operators6reader40OrderedMultiDeviceLoDTensorBlockingQueueERKSt6vectorINS2_9framework9LoDTensorESaISC_EEE2_bIS9_SG_EINS_4nameENS_9is_methodENS_7siblingENS_10call_guardIINS_18gil_scoped_releaseEEEEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNES11_
W0602 12:43:08.498661   138 init.cc:224]     @     0x7f756bf408c9 pybind11::cpp_function::dispatcher()
W0602 12:43:08.498987   138 init.cc:224]     @     0x55b400f6f744 _PyMethodDef_RawFastCallKeywords
W0602 12:43:08.499276   138 init.cc:224]     @     0x55b400f6f861 _PyCFunction_FastCallKeywords
W0602 12:43:08.499555   138 init.cc:224]     @     0x55b400fdb6e8 _PyEval_EvalFrameDefault
W0602 12:43:08.499835   138 init.cc:224]     @     0x55b400f1f81a _PyEval_EvalCodeWithName
W0602 12:43:08.500102   138 init.cc:224]     @     0x55b400f20635 _PyFunction_FastCallDict
W0602 12:43:08.500380   138 init.cc:224]     @     0x55b400fd8232 _PyEval_EvalFrameDefault
W0602 12:43:08.500617   138 init.cc:224]     @     0x55b400f6eccb _PyFunction_FastCallKeywords
W0602 12:43:08.500895   138 init.cc:224]     @     0x55b400fd6a93 _PyEval_EvalFrameDefault
W0602 12:43:08.501137   138 init.cc:224]     @     0x55b400f6eccb _PyFunction_FastCallKeywords
W0602 12:43:08.501412   138 init.cc:224]     @     0x55b400fd6a93 _PyEval_EvalFrameDefault
W0602 12:43:08.501668   138 init.cc:224]     @     0x55b400f2056b _PyFunction_FastCallDict
W0602 12:43:08.501919   138 init.cc:224]     @     0x55b400f3ee53 _PyObject_Call_Prepend
W0602 12:43:08.502207   138 init.cc:224]     @     0x55b400f31dbe PyObject_Call
W0602 12:43:08.502316   138 init.cc:224]     @     0x55b40102e817 t_bootstrap
W0602 12:43:08.502367   138 init.cc:224]     @     0x55b400fe9788 pythread_wrapper
W0602 12:43:08.503707   138 init.cc:224]     @     0x7f758bb966ba start_thread
Aborted (core dumped)

配制如下：
faster_rcnn_r50_fpn_2x.yml改动：metric: VOC
faster_fpn_reader.yml改动：
TrainReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd']
  dataset:
    !VOCDataSet
    dataset_dir: /home/aistudio/PaddleDetection-release-0.3/dataset/density/head_train
    anno_path: train.txt
    image_dir: 
voc.py改动：
def pascalvoc_label(with_background=True):
    labels_map = {
        'dot':1
        # 'aeroplane': 1,
        # 'bicycle': 2,
        # 'bird': 3,
        # 'boat': 4,
        # 'bottle': 5,
        # 'bus': 6,
        # 'car': 7,
        # 'cat': 8,
        # 'chair': 9,
        # 'cow': 10,
        # 'diningtable': 11,
        # 'dog': 12,
        # 'horse': 13,
        # 'motorbike': 14,
        # 'person': 15,
        # 'pottedplant': 16,
        # 'sheep': 17,
        # 'sofa': 18,
        # 'train': 19,
        # 'tvmonitor': 20
    }
我只有一个分类

**Comment by heavengate** [comment]
RCNN系列模型的`num_classes`需要设置为类别数+1，加的那一类为背景类，如果你只有一个分类，`num_classes`需要设置为2

**Comment by liu824** [comment]
好的

**Comment by liu824** [comment]
with_background需要设置吗？

**Comment by heavengate** [comment]
> with_background需要设置吗？

RCNN的with_background都是true，不用修改

**Comment by liu824** [comment]
好的
