### ISSUE TITLE
使用ppyoloe+,或者ppyolo训练数据，都出现(AP)@[Iou=0.5:0.95|area=small|maxDets]=-1

### ISSUE THREAD

**Issue by shuaihutianxie** [PaddlePaddle/PaddleDetection#8481]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.491 Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.801 Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.600 Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000 Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.776 Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.478 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.620 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.670 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.670 Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000 Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.775 Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.661

请求什么原因，一直导致这个问题，数据集检测也没啥问题啊，如何修改呢！！！

**Comment by lyuwenyu** [comment]
是因为你的数据集里没有在coco标准下的小物体吧

**Comment by shuaihutianxie** [comment]
有一些小物体，但是不多，这个会不会影响模型效果呢，目前模型map=0.71,一直调参优化不上去，请问怎么解决呢，谢谢

**Comment by ruler77** [comment]
Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000 在小目标上召回率都为0了，你应该检测小目标检测情况，看你结果数据集都是些中等和大目标，大小目标划分用的是coco数据集的标准，你自己检查一下是否有小目标

**Comment by sy-l123** [comment]
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000 在小目标上召回率都为0了，你应该检测小目标检测情况，看你结果数据集都是些中等和大目标，大小目标划分用的是coco数据集的标准，你自己检查一下是否有小目标

没有小物体是否可以删除小物体的设置？
