### ISSUE TITLE
想问一下 blazeface部署到移动端耗时大概多少

### ISSUE THREAD

**Issue by anliyuan** [PaddlePaddle/PaddleDetection#8484]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

想问一下 blazeface部署到移动端耗时大概多少

**Comment by lyuwenyu** [comment]
这个和具体的设备的算力有关系  需要实测下
