### ISSUE TITLE
【论文复现】Co-DETR with ViT-L

### ISSUE THREAD

**Issue by shiyutang** [PaddlePaddle/PaddleDetection#8499]
## 背景
经过[需求征集](https://github.com/PaddlePaddle/PaddleOCR/issues/10334)，我们确定了Co-DETR目标检测任务，该任务基于大模型进行推理，使用[ViT-L](https://github.com/baaivision/EVA/tree/master/EVA-02) (304M) 骨干网络的Co-DETR是目前第一个在COCO测试集上达到66.0% AP的模型，也让他成为目前的最优模型。

## 解决步骤
1. 根据开源代码进行网络结构、评估指标转换。代码链接：https://github.com/Sense-X/Co-DETR
2. 结合[论文复现指南](https://github.com/PaddlePaddle/models/blob/release%2F2.2/tutorials/article-implementation/ArticleReproduction_CV.md)，进行前向对齐等操作，使用Co-DIno-SwinL 在COCO测试集上达到60.7% AP。
3. 参考[新增代码规范](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/docs/advanced_tutorials/MODEL_TECHNICAL.md)提交代码PR到ppdet中。

数据集：MS-COCO
代码、权重均已经开源，只需要进行前向对齐。

**Comment by daoqiugsy** [comment]
报名

**Comment by WeihongM** [comment]
请问这个模型预计什么时候完成迁移？
