### ISSUE TITLE
iou_similarity 不支持box_normalized参数

### ISSUE THREAD

**Issue by lxastro** [PaddlePaddle/PaddleDetection#85]
如题，iou_similarity对于整数坐标输入的计算存在问题。
对于box_normalized=False的情况，
iou_similarity中的面积计算都应该改为 (ymax-ymin+1) * (xmax-xmin+1)。

**Comment by qingqing01** [comment]
@lxastro  感谢反馈，这个我们在框架对应的op里增强下~
