### ISSUE TITLE
训练过程保存模型结果报错pickle.dump(param_dict, f, protocol=2) MemoryError

### ISSUE THREAD

**Issue by vincentpengpeng** [PaddlePaddle/PaddleDetection#850]
![image](https://user-images.githubusercontent.com/22005432/83495544-6ad70380-a4ea-11ea-86d2-4c4e06cfbc19.png)

**Comment by jerrywgz** [comment]
看起来像是空间不足导致的
![image](https://user-images.githubusercontent.com/22989727/83503579-d96d8e80-a4f5-11ea-9972-31e4c701ea1d.png)

**Comment by vincentpengpeng** [comment]
> 看起来像是空间不足导致的
> ![image](https://user-images.githubusercontent.com/22989727/83503579-d96d8e80-a4f5-11ea-9972-31e4c701ea1d.png)

检查过训练过程中硬盘空间和内存都是有空间的
![image](https://user-images.githubusercontent.com/22005432/83503900-61ec2f00-a4f6-11ea-96f8-a5d1094c171e.png)
有可能是pickle的bug导致的吗

**Comment by heavengate** [comment]
应该是pickle的bug，32位Python上pickle版本较低容易出现这个问题，可以尝试下升级python版本或者升级pickle版本

**Comment by vincentpengpeng** [comment]
thx
