### ISSUE TITLE
PP-YOLOE-R 编译旋转框自定义外部算子 出错

### ISSUE THREAD

**Issue by CF-chen-feng-CF** [PaddlePaddle/PaddleDetection#8504]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

以下为报错信息：

E:\ProfessionalOfficeSoftware\anacondaanzhuang\envs\paddle\lib\site-packages\paddle\include\third_party\pybind11\cast.h(628): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(725): here

E:\ProfessionalOfficeSoftware\anacondaanzhuang\envs\paddle\lib\site-packages\paddle\include\third_party\pybind11\cast.h(721): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(725): here

2 errors detected in the compilation of "F:/Project_python/AI_train/A_CF_projeict/3-ROObjectDetect/PaddleDetection-2.6.0/ppdet/ext_op/csrc/matched_rbox_iou/matched_rbox_iou.cu".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin\\nvcc.exe' failed with exit code 1

**Comment by SirojbekSafarov** [comment]
I am also facing this issue is there any idea how to solve it? 
I have windows 11 with Cuda 11.4.

**Comment by yeyupiaoling** [comment]
@CF-chen-feng-CF 你解决了吗？

**Comment by lyuwenyu** [comment]
解决了嘛  还有问题的话请提新的issue

**Comment by weiyaokun** [comment]
大佬们  有谁解决了吗？

**Comment by weiyaokun** [comment]
我也是一模一样的问题
