### ISSUE TITLE
yolov3模型如何调整预测框的样式

### ISSUE THREAD

**Issue by pomeloyou** [PaddlePaddle/PaddleDetection#851]
在哪个文件中可以进行样式修改

**Comment by heavengate** [comment]
预测框是通过这个函数画上去的
https://github.com/PaddlePaddle/PaddleDetection/blob/7bb04787ce99889331973811a1063cf6e3689914/ppdet/utils/visualizer.py#L70

**Comment by pomeloyou** [comment]
> 预测框是通过这个函数画上去的
> https://github.com/PaddlePaddle/PaddleDetection/blob/7bb04787ce99889331973811a1063cf6e3689914/ppdet/utils/visualizer.py#L70

谢谢指点

**Comment by pomeloyou** [comment]
这个是在修改参数过后需要重新训练模型才会生效吗，还是说修改过后在预测时就可以生效，我刚才修改了预测框线的宽度后重新预测并没有什么改变

**Comment by heavengate** [comment]
不需要重新训练，直接预测就可以生效，是使用`tools/infer.py`预测的么

**Comment by pomeloyou** [comment]
> 不需要重新训练，直接预测就可以生效，是使用`tools/infer.py`预测的么

不是，是使用`deploy/python/infer.py`预测的

**Comment by pomeloyou** [comment]
我知道了，这个`deploy/python/infer.py`也有对应的画预测框的函数，多谢指点

**Comment by heavengate** [comment]
> 我知道了，这个`deploy/python/infer.py`也有对应的画预测框的函数，多谢指点

`deploy/python/infer.py`的话用的是这个
https://github.com/PaddlePaddle/PaddleDetection/blob/7bb04787ce99889331973811a1063cf6e3689914/deploy/python/visualize.py#L151

**Comment by pomeloyou** [comment]
> > 我知道了，这个`deploy/python/infer.py`也有对应的画预测框的函数，多谢指点
> 
> `deploy/python/infer.py`的话用的是这个
> https://github.com/PaddlePaddle/PaddleDetection/blob/7bb04787ce99889331973811a1063cf6e3689914/deploy/python/visualize.py#L151

已经修改了，谢谢
