### ISSUE TITLE
bug to show detection result when using rtsp as input

### ISSUE THREAD

**Issue by Albert57060839** [PaddlePaddle/PaddleDetection#8510]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

I run the pipeline.py using rtsp as input：
!python deploy/pipeline/pipeline.py --device=gpu \
    --config deploy/pipeline/config/infer_cfg_pphuman.yml \
    -o ATTR.model_dir=output_inference/PPHGNet_tiny_person_attribute_952_infer \
    --video_file="my rtsp link"

when using rtsp to do detection, if no target is detected, no result will show
if at least one target is detected, it can correctly show the result.

### 复现环境 Environment

PaddleDetection:release/2.6
jupyter notebook: python3(ipykernal)

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
please modify `--video_file="my rtsp link"`

**Comment by Albert57060839** [comment]
I used my rtsp link (rtsp://localhost:8554/live.stream) but it's a local server and only accessible on my device, the link has no error and if I use rtsp video with people and vehicles in it, all thing works fine, but if I use rtsp video without a target, it won't show any result and crash
