### ISSUE TITLE
关于PPYOLOE-R模型部署推理报错

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleDetection#8511]
### 问题描述 Please describe your issue

你好，我在测试的过程中发现DetectionC++部署代码中开启mkldnn时，进行PPYOLOE-R训练的模型推理时程序崩掉，关闭mkldnn又能正常运行，但是当测试使用PPDet训练的模型开启mkldnn时，程序又能够正常运行，请问这是怎么回事呢？难道PPYOLOE-R不支持CPU使用mkldnn吗？
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/87969070/01c220ba-9c17-43bc-80ab-497685bbea69)
报错信息：
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/87969070/2fdbfa1a-3d2c-40af-9535-ae60c6c6db7a)

**Comment by lyuwenyu** [comment]
解决了嘛 有问题可以提新的issue
