### ISSUE TITLE
CUDNN error(9) CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by xiaopengaia** [PaddlePaddle/PaddleDetection#8516]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

执行：

`python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_pphuman.yml --image_file=test_image.jpg --device=gpu`

出现：

`CUDNN error(9) CUDNN_STATUS_NOT_SUPPORTED`

我的设备版本：

1. python 3.7.0
2. paddle 2.5.1
3. cuda 11.6
4. cudatiktool 11.3 (采用conda安装)

我执行的paddle 安装命令

`python -m pip install paddlepaddle-gpu==2.5.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`

说明：

执行所提供的**快速体验**均能正常执行，测试**PP-Human快速开始**出现CUDA版本不支持的问题。

保存问题描述中提及当前CUDA版本不支持：conv2d_fusion操作，可当前ｃｕｄａ版本为１１.６

**Comment by lsewcx** [comment]
解决方法：更换cudnn版本
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/107914845/a5b2cad4-c72e-423d-ab09-2c0d6bbb9384)
我是CUDA11.7 cudnn版本是8.5更换为8.4.1后解决
