### ISSUE TITLE
DetectionWindows环境C++部署

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleDetection#8525]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference

### Bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/PaddleDetection/assets/87969070/869170b7-4dcb-42a4-968f-fbce03dedea7)
主要问题点是：使用ppyoloe-r训练生成的推理模型，当开启mkldnn时程序运行崩溃，若换成pp-det训练生成的推理模型在开启mkldnn时程序运行正常
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/87969070/ec94db37-26b1-44d3-9fc0-0c793a5cf759)

### 复现环境 Environment

-OS:Windows
-PaddlePaddle:2.4.1
-PaddleDetection:release/2.6
CPU

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
看下paddlet的版本 和
