### ISSUE TITLE
显存32g可是训练很慢，只利用4g左右

### ISSUE THREAD

**Issue by felixgalaxy** [PaddlePaddle/PaddleDetection#853]
peddledetectin做检测训练，显存32g，可是训练很慢，感觉显存没有充分利用，请问如何解决呢
![1](https://user-images.githubusercontent.com/49911457/83512026-27888f00-a502-11ea-9d30-11af07ca183e.jpg)
![2](https://user-images.githubusercontent.com/49911457/83512032-2b1c1600-a502-11ea-9f0d-8055b23b6b3a.jpg)
![3](https://user-images.githubusercontent.com/49911457/83512041-2d7e7000-a502-11ea-9a97-3f954536b14c.jpg)

**Comment by heavengate** [comment]
应该是这个模型在当前的配置下只需要4G的显存就够了，如果想多用显存可以把`batch_size`调大一些

**Comment by imistyrain** [comment]
workers设小了吧，加载数据和预处理太慢

**Comment by felixgalaxy** [comment]
请问多少合适呢，感觉gpu没充分利用发自我的华为手机-------- 原始邮件 --------发件人： MistyRain <notifications@github.com>日期： 2020年6月5日周五 上午11:44收件人： PaddlePaddle/PaddleDetection <PaddleDetection@noreply.github.com>抄送： felixgalaxy <felixgalaxy@163.com>, Author <author@noreply.github.com>主    题： Re: [PaddlePaddle/PaddleDetection] 显存32g可是训练很慢，只利用4g左右 (#853)

workers设小了吧，加载数据和预处理太慢

**Comment by imistyrain** [comment]
> 请问多少合适呢，感觉gpu没充分利用发自我的华为手机-------- 原始邮件 --------发件人： MistyRain <notifications@github.com>日期： 2020年6月5日周五 上午11:44收件人： PaddlePaddle/PaddleDetection <PaddleDetection@noreply.github.com>抄送： felixgalaxy <felixgalaxy@163.com>, Author <author@noreply.github.com>主 题： Re: [PaddlePaddle/PaddleDetection] 显存32g可是训练很慢，只利用4g左右 (#853) workers设小了吧，加载数据和预处理太慢 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

用htop看下CPU利用率有没有满载吧，没有的话设成CPU的个数
