### ISSUE TITLE
通过PaddleDetection的export_serving_model.py导出模型，通过Serving部署报错

### ISSUE THREAD

**Issue by vinceyzw** [PaddlePaddle/PaddleDetection#855]
1、通过PaddleDetection的export_serving_model.py导出模型pddet_serving_model、pddet_client_conf；
2、通过 test_client.py进行部署；
3、报错：
Traceback (most recent call last):
  File "test_client.py", line 39, in <module>
    fetch=["multiclass_nms"])
  File "/usr/lib/python2.7/site-packages/paddle_serving_client/__init__.py", line 253, in predict
    "Fetch names should not be empty or out of saved fetch list.")
ValueError: Fetch names should not be empty or out of saved fetch list.

请大佬帮忙，看看什么情况。

**Comment by heavengate** [comment]
麻烦贴一下你`test_client.py`里的预测代码

**Comment by vinceyzw** [comment]
> 麻烦贴一下你`test_client.py`里的预测代码

因为我用的faster-rcnn，直接用的
https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/faster_rcnn_model
这里面的test_client.py

**Comment by heavengate** [comment]
本次测试了下，输出Variable的name是`multiclass_nms_0.tmp_0`, `fetch`参数需要指定为`multiclass_nms_0.tmp_0`
```
2020-06-03 03:05:40,014-INFO: Export serving model to output, client side: output/serving_client, server side: output/serving_server. input: ['image', 'im_size'], output: ['multiclass_nms_0.tmp_0']...
```

**Comment by vinceyzw** [comment]
还是报错了：
Traceback (most recent call last):
  File "test_client.py", line 41, in <module>
    postprocess(fetch_map)
  File "/usr/lib/python2.7/site-packages/paddle_serving_app/reader/image_reader.py", line 225, in __call__
    self.clsid2catid)
  File "/usr/lib/python2.7/site-packages/paddle_serving_app/reader/image_reader.py", line 149, in _get_bbox_result
    lod = [fetch_map[fetch_name + '.lod']]
KeyError: 'multiclass_nms_0.tmp_0.lod'

我直接下载 Model Zoo中的faster_rcnn_model.tar.gz、infer_cfg.yml是可以正常跑起来的。我自己训练了模型，替换了pddet_serving_model、pddet_client_conf、infer_cfg.yml、label_list.txt这几个文件，就报错了 @heavengate

**Comment by wangjiawei04** [comment]
> multiclass_nms_0.tmp_0.lod

这个是后处理报错，看看 server和client的 两个prototxt文件 在'multiclass_nms_0.tmp_0.lod‘ 的lod_tensor那一项是不是false？ 如果是的话 改成true再执行一下看看。

不确定这样是不是能解决问题。如果可以的话 我可能需要做一些框架上的改动。

**Comment by vinceyzw** [comment]
> > multiclass_nms_0.tmp_0.lod
> 
> 这个是后处理报错，看看 server和client的 两个prototxt文件 在'multiclass_nms_0.tmp_0.lod‘ 的lod_tensor那一项是不是false？ 如果是的话 改成true再执行一下看看。
> 
> 不确定这样是不是能解决问题。如果可以的话 我可能需要做一些框架上的改动。

刚试了下，修改成true确实是可以的。
关于serving，有没有详细的文档？对没做过服务部署的来说，看起来有点困难。

**Comment by wangjiawei04** [comment]
> > > multiclass_nms_0.tmp_0.lod
> > 
> > 
> > 这个是后处理报错，看看 server和client的 两个prototxt文件 在'multiclass_nms_0.tmp_0.lod‘ 的lod_tensor那一项是不是false？ 如果是的话 改成true再执行一下看看。
> > 不确定这样是不是能解决问题。如果可以的话 我可能需要做一些框架上的改动。
> 
> 刚试了下，修改成true确实是可以的。
> 关于serving，有没有详细的文档？对没做过服务部署的来说，看起来有点困难。

好的 我记录下这个问题 文档目前都在 https://github.com/paddlepaddle/serving 下面有详细的中英文文档 如果缺少的话 感谢多提issue，我们会第一时间补上
