### ISSUE TITLE
可以增加一下旋转目标检测的数据增强op吗？

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleDetection#8556]
### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by shangshanruowo** [comment]
bbox里面op非常多，但rbox里面的数据增强太少了，连mosica和mixup都没有，想用的话太难加了，还有可能把数据增强的可视化改进一下吗，比如我先看一张图片的变化，但开启debug可视化按钮它会一次都显示所有的照片变化再刷新，这来不及记录一张变化的，因为你们传入参数的都必须按你们格式来，对一个函数变化也不能只传入一张照片

**Comment by zhiboniu** [comment]
感谢提出的意见
