### ISSUE TITLE
paddledetection模型恢复训练方面问题

### ISSUE THREAD

**Issue by changzipeng** [PaddlePaddle/PaddleDetection#8563]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddledetection模型恢复训练的时候 从上次中断前训得模型开始继续训练 训练几个epoch后指标AP值会下降零点几个点 训练十个epoch也恢复不到模型中断前的那个AP值 而且从中断前的那个模型开始继续训练 它评估得到的AP值是在恢复训练后的模型的AP值 在计算best model的时候 恢复的那个epoch的那个模型的AP值没有算进去 我想问一下 模型恢复训练是否会对模型的精度产生影响

**Comment by nemonameless** [comment]
不会有影响。训练语句加类似`-r output/ppyoloe_crn_l_36e_coco/epoch_10`，注意epoch_10不要加后缀.pdparams，否则不会加载到.pdopt和.pdema

**Comment by changzipeng** [comment]
> 不会有影响。训练语句加类似`-r output/ppyoloe_crn_l_36e_coco/epoch_10`，注意epoch_10不要加后缀.pdparams，否则不会加载到.pdopt和.pdema

感谢感谢呜呜呜我就是加了后面说的pdparams，怪不得了，我还想着优化器的参数是不是没加进去呀

**Comment by HRyixin** [comment]
请问框架会自动加载后缀.pdparams，该如何解决呢
