### ISSUE TITLE
PP-YOLO-SOD  C++部署

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#8568]
### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
模型在推理上和ppyoloe一样的 应该没问题的

**Comment by Dandelion111** [comment]
> 模型在推理上和ppyoloe一样的 应该没问题的

请问用c++部署，sahi部分只能自己实现吗

**Comment by lyuwenyu** [comment]
是的  这部分没办法只能自己实现
