### ISSUE TITLE
更换anchors之后map没以前好了

### ISSUE THREAD

**Issue by wzl0329** [PaddlePaddle/PaddleDetection#857]
模型是yolov3增强模型，使用了iouloss和louawareloss，用k-means方法根据训练集更换了anchors，anchors的大小是根据输入的图片大小608按比例计算的，没有更改其他参数，没更改前的map可以达到90，更改之后效果变差了，想问一下还可以更改哪些参数可以使模型效果变好？
YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
#更改了anchors
  anchors: [[27, 66], [39, 66], [46, 68],
            [44, 86], [53, 91], [59, 94],
            [62, 104], [77, 106], [99, 142]]
  norm_decay: 0.
  iou_aware: true
  iou_aware_factor: 0.4
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01
  drop_block: true
   
YOLOv3Loss:
  batch_size: 16
  ignore_thresh: 0.7
  label_smooth: false
  use_fine_grained_loss: true
  iou_loss: IouLoss
  iou_aware_loss: IouAwareLoss
 
IouLoss:
  loss_weight: 2.5
  max_height: 608
  max_width: 608

IouAwareLoss:
  loss_weight: 1.0
  max_height: 608
  max_width: 608

**Comment by willthefrog** [comment]
是从头训练的吗？预训练权重是基于coco统计的anchor训练的。

**Comment by wzl0329** [comment]
刚才检查了一下，在yolov3_enhance_reader.yml还有一个anchors没有改，现在改了。等下看看训练的怎么样。
