### ISSUE TITLE
Paddle旋转目标检测转onnx后推理报错

### ISSUE THREAD

**Issue by Huangjiaming95** [PaddlePaddle/PaddleDetection#8571]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

 [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Split node. Name:'p2o.Split.6' Status Message: Cannot split using values in 'split' attribute. Axis=2 Input shape={1,21504,8} NumOutputs=4 Num entries in 'split' (must equal number of outputs) was 4 Sum of sizes in 'split' (must equal size of selected axis) was 4

**Comment by malinuonuo** [comment]
在export模型的时候，加入export_model=True的参数。

**Comment by zzzzz1231** [comment]
我也遇到相同的问题，请问你解决了吗

**Comment by vowsgray** [comment]
你好，我也遇到了同样的问题，请问是怎么解决的？
