### ISSUE TITLE
paddledetection中使用TensorRT的问题

### ISSUE THREAD

**Issue by lrp123456** [PaddlePaddle/PaddleDetection#8573]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

-----------  Running Arguments -----------
action_file: None
batch_size: 4
camera_id: -1
combine_method: nms
cpu_threads: 1
device: GPU
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: G:\COCO_labelImg_format_COCO_format\val2017
image_file: None
match_metric: ios
match_threshold: 0.6
model_dir: G:\PaddleDetection\infer\c_r_r50_base
output_dir: output
overlap_ratio: [0.25, 0.25]
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: trt_fp32
save_images: True
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
slice_infer: False
slice_size: [640, 640]
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_coco_category: False
use_dark: True
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: RCNN
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--transform op: PadStride
--------------------------------------------
trt set dynamic shape done!

使用tensorrt时无任何报错就会异常退出

根据以上问题我尝试根据https://www.paddlepaddle.org.cn/inference/master/guides/quick_start/python_demo.html写了一段代码。
代码如下：
# 引用 paddle inference 预测库
import paddle.inference as paddle_infer
import cv2
import numpy as np
from PIL import Image

# 创建 config
config = paddle_infer.Config("./infer/c_r_r50_base/model.pdmodel", "./infer/c_r_r50_base/model.pdiparams")

# 启用 GPU 进行预测 - 初始化 GPU 显存 100 M, Deivce_ID 为 0
config.enable_use_gpu(5000, 0)

# 启用 TensorRT 进行预测加速 - Int8
config.enable_tensorrt_engine(workspace_size = 1 << 29,
                              max_batch_size = 1,
                              min_subgraph_size = 1,
                              precision_mode=paddle_infer.PrecisionType.Int8,
                              use_static = False, use_calib_mode = True)

# 开启 TensorRT 显存优化
config.enable_tensorrt_memory_optim()

# 设置 TensorRT 的动态 Shape
config.set_trt_dynamic_shape_info(min_input_shape={"image": [1, 1, 640, 640]},
                                  max_input_shape={"image": [1, 1, 1296, 2304]},
                                  optim_input_shape={"image": [1, 1, 640, 640]})
predictor = paddle_infer.create_predictor(config)
# print(predictor)

def resize(img, target_size):
    """resize to target size"""
    if not isinstance(img, np.ndarray):
        raise TypeError('image type is not numpy.')
    im_shape = img.shape
    im_size_min = np.min(im_shape[0:2])
    im_size_max = np.max(im_shape[0:2])
    im_scale_x = float(target_size) / float(im_shape[1])
    im_scale_y = float(target_size) / float(im_shape[0])
    img = cv2.resize(img, None, None, fx=im_scale_x, fy=im_scale_y)
    return img

def normalize(img, mean, std):
    img = img / 255.0
    mean = np.array(mean)[np.newaxis, np.newaxis, :]
    std = np.array(std)[np.newaxis, np.newaxis, :]
    img -= mean
    img /= std
    return img

def preprocess(img, img_size):
    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]
    img = resize(img, img_size)
    img = img[:, :, ::-1].astype('float32')  # bgr -> rgb
    img = normalize(img, mean, std)
    img = img.transpose((2, 0, 1))  # hwc -> chw
    return img[np.newaxis, :]

def run(predictor, img):
    # copy img data to input tensor
    input_names = predictor.get_input_names()
    for i, name in enumerate(input_names):
        input_tensor = predictor.get_input_handle(name)
        input_tensor.reshape(img[i].shape)
        input_tensor.copy_from_cpu(img[i])

    # do the inference
    predictor.run()

    results = []
    # get out data from output tensor
    output_names = predictor.get_output_names()
    for i, name in enumerate(output_names):
        output_tensor = predictor.get_output_handle(name)
        output_data = output_tensor.copy_to_cpu()
        results.append(output_data)
    return results

if __name__ == "__main__":
    img_name = "output/000000000114.jpg"
    save_img_name = "res.jpg"
    im_size = 640
    img = cv2.imread(img_name)
    # print(img)
    data = preprocess(img, im_size)
    scale_factor = (
        np.array([im_size * 1.0 / img.shape[0], im_size * 1.0 / img.shape[1]])
        .reshape((1, 2))
        .astype(np.float32)
    )
    im_shape = np.array([im_size, im_size]).reshape((1, 2)).astype(np.float32)
    result = run(predictor, [im_shape, data, scale_factor])
    img = Image.open(img_name).convert("RGB")
    draw_bbox(img, result[0], save_name=save_img_name)
其中我使用了Cascade RCNN模型，自己训练的
会出现如下问题：
E:\procedure\anaconda\envs\paddle\python.exe G:/PaddleDetection/infer.py
I0825 22:51:47.682303  3588 analysis_predictor.cc:1378] TensorRT subgraph engine is enabled
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
I0825 22:51:47.706307  3588 executor.cc:187] Old Executor is Running.
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [trt_support_nhwc_pass]e[0m
e[32m--- Running IR pass [adaptive_pool2d_convert_global_pass]e[0m
e[32m--- Running IR pass [trt_map_ops_to_matrix_multiply_pass]e[0m
I0825 22:51:48.545225  3588 fuse_pass_base.cc:59] ---  detected 12 subgraphs
e[32m--- Running IR pass [shuffle_channel_detect_pass]e[0m
e[32m--- Running IR pass [quant_conv2d_dequant_fuse_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_op_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_filter_op_pass]e[0m
e[32m--- Running IR pass [trt_delete_weight_dequant_linear_op_pass]e[0m
e[32m--- Running IR pass [delete_quant_dequant_linear_op_pass]e[0m
e[32m--- Running IR pass [identity_scale_op_clean_pass]e[0m
e[32m--- Running IR pass [add_support_int8_pass]e[0m
I0825 22:51:49.659210  3588 fuse_pass_base.cc:59] ---  detected 721 subgraphs
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [trt_embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [preln_embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [delete_c_identity_op_pass]e[0m
e[32m--- Running IR pass [trt_multihead_matmul_fuse_pass_v2]e[0m
e[32m--- Running IR pass [trt_multihead_matmul_fuse_pass_v3]e[0m
e[32m--- Running IR pass [multihead_matmul_roformer_fuse_pass]e[0m
e[32m--- Running IR pass [constant_folding_pass]e[0m
e[32m--- Running IR pass [trt_flash_multihead_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [trt_cross_multihead_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [vit_attention_fuse_pass]e[0m
e[32m--- Running IR pass [trt_qk_multihead_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [layernorm_shift_partition_fuse_pass]e[0m
e[32m--- Running IR pass [merge_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [preln_residual_bias_fuse_pass]e[0m
e[32m--- Running IR pass [preln_layernorm_x_fuse_pass]e[0m
e[32m--- Running IR pass [reverse_roll_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.145850  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.145850  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
W0825 22:51:50.155851  3588 op_compat_sensible_pass.cc:232]  Check the Attr(axis) of Op(elementwise_add) in pass(conv_elementwise_add_fuse_pass) failed!
W0825 22:51:50.155851  3588 conv_elementwise_add_fuse_pass.cc:94] Pass in op compat failed.
e[32m--- Running IR pass [remove_padding_recover_padding_pass]e[0m
e[32m--- Running IR pass [delete_remove_padding_recover_padding_pass]e[0m
e[32m--- Running IR pass [dense_fc_to_sparse_pass]e[0m
e[32m--- Running IR pass [dense_multihead_matmul_to_sparse_pass]e[0m
e[32m--- Running IR pass [tensorrt_subgraph_pass]e[0m
I0825 22:51:50.224850  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 69 nodes
I0825 22:51:50.230852  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 9 nodes
W0825 22:51:50.230852  3588 tensorrt_subgraph_pass.cc:344] tensorrt_subgraph's input named fill_constant_35.tmp_0 having int64 dtype in pdmodel description, we will cast them to int32 dtype to feed them into paddle-trt.
W0825 22:51:50.230852  3588 tensorrt_subgraph_pass.cc:344] tensorrt_subgraph's input named fill_constant_33.tmp_0 having int64 dtype in pdmodel description, we will cast them to int32 dtype to feed them into paddle-trt.
W0825 22:51:50.231851  3588 tensorrt_subgraph_pass.cc:499] tensorrt_subgraph's output named fill_constant_37.tmp_0 having int64 dtype in pdmodel description, but in fact it is int32 dtype after executing this tensorrt_subgraph, so we need cast them into int64.
W0825 22:51:50.231851  3588 tensorrt_subgraph_pass.cc:499] tensorrt_subgraph's output named range_8.tmp_0 having int64 dtype in pdmodel description, but in fact it is int32 dtype after executing this tensorrt_subgraph, so we need cast them into int64.
I0825 22:51:50.231851  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 23 nodes
I0825 22:51:50.232852  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 42 nodes
I0825 22:51:50.235855  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 24 nodes
I0825 22:51:50.236853  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 6 nodes
I0825 22:51:50.237854  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 3 nodes
I0825 22:51:50.237854  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 9 nodes
W0825 22:51:50.238855  3588 tensorrt_subgraph_pass.cc:344] tensorrt_subgraph's input named fill_constant_47.tmp_0 having int64 dtype in pdmodel description, we will cast them to int32 dtype to feed them into paddle-trt.
W0825 22:51:50.238855  3588 tensorrt_subgraph_pass.cc:344] tensorrt_subgraph's input named fill_constant_49.tmp_0 having int64 dtype in pdmodel description, we will cast them to int32 dtype to feed them into paddle-trt.
W0825 22:51:50.238855  3588 tensorrt_subgraph_pass.cc:499] tensorrt_subgraph's output named fill_constant_51.tmp_0 having int64 dtype in pdmodel description, but in fact it is int32 dtype after executing this tensorrt_subgraph, so we need cast them into int64.
W0825 22:51:50.238855  3588 tensorrt_subgraph_pass.cc:499] tensorrt_subgraph's output named range_9.tmp_0 having int64 dtype in pdmodel description, but in fact it is int32 dtype after executing this tensorrt_subgraph, so we need cast them into int64.
I0825 22:51:50.238855  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 225 nodes
I0825 22:51:50.253449  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 3 nodes
I0825 22:51:50.254449  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 6 nodes
I0825 22:51:50.254449  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 3 nodes
W0825 22:51:50.254449  3588 tensorrt_subgraph_pass.cc:344] tensorrt_subgraph's input named array_length_3.tmp_0 having int64 dtype in pdmodel description, we will cast them to int32 dtype to feed them into paddle-trt.
W0825 22:51:50.254449  3588 tensorrt_subgraph_pass.cc:344] tensorrt_subgraph's input named tmp_40 having int64 dtype in pdmodel description, we will cast them to int32 dtype to feed them into paddle-trt.
I0825 22:51:50.255450  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 34 nodes
I0825 22:51:50.257449  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 6 nodes
I0825 22:51:50.258450  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 9 nodes
W0825 22:51:50.258450  3588 tensorrt_subgraph_pass.cc:344] tensorrt_subgraph's input named fill_constant_57.tmp_0 having int64 dtype in pdmodel description, we will cast them to int32 dtype to feed them into paddle-trt.
W0825 22:51:50.258450  3588 tensorrt_subgraph_pass.cc:344] tensorrt_subgraph's input named fill_constant_55.tmp_0 having int64 dtype in pdmodel description, we will cast them to int32 dtype to feed them into paddle-trt.
W0825 22:51:50.258450  3588 tensorrt_subgraph_pass.cc:499] tensorrt_subgraph's output named fill_constant_59.tmp_0 having int64 dtype in pdmodel description, but in fact it is int32 dtype after executing this tensorrt_subgraph, so we need cast them into int64.
W0825 22:51:50.258450  3588 tensorrt_subgraph_pass.cc:499] tensorrt_subgraph's output named range_10.tmp_0 having int64 dtype in pdmodel description, but in fact it is int32 dtype after executing this tensorrt_subgraph, so we need cast them into int64.
I0825 22:51:50.259449  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 3 nodes
I0825 22:51:50.259449  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 6 nodes
I0825 22:51:50.260449  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 3 nodes
W0825 22:51:50.260449  3588 tensorrt_subgraph_pass.cc:344] tensorrt_subgraph's input named array_length_2.tmp_0 having int64 dtype in pdmodel description, we will cast them to int32 dtype to feed them into paddle-trt.
W0825 22:51:50.260449  3588 tensorrt_subgraph_pass.cc:344] tensorrt_subgraph's input named tmp_38 having int64 dtype in pdmodel description, we will cast them to int32 dtype to feed them into paddle-trt.
I0825 22:51:50.260449  3588 tensorrt_subgraph_pass.cc:302] ---  detect a sub-graph with 60 nodes
e[32m--- Running IR pass [conv_elementwise_add_act_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add2_act_fuse_pass]e[0m
e[32m--- Running IR pass [transpose_flatten_concat_fuse_pass]e[0m
e[32m--- Running IR pass [auto_mixed_precision_pass]e[0m
e[1me[35m--- Running analysis [save_optimized_model_pass]e[0m
W0825 22:51:50.278450  3588 save_optimized_model_pass.cc:28] save_optim_cache_model is turned off, skip save_optimized_model_pass
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
I0825 22:51:50.278450  3588 ir_params_sync_among_devices_pass.cc:51] Sync params from CPU to GPU
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0825 22:51:50.690076  3588 analysis_predictor.cc:1660] ======= optimize end =======
I0825 22:51:50.692077  3588 naive_executor.cc:164] ---  skip [feed], feed -> scale_factor
I0825 22:51:50.692077  3588 naive_executor.cc:164] ---  skip [feed], feed -> image
I0825 22:51:50.692077  3588 naive_executor.cc:164] ---  skip [feed], feed -> im_shape
I0825 22:51:50.694077  3588 naive_executor.cc:164] ---  skip [concat_17.tmp_0], fetch -> fetch
I0825 22:51:50.694077  3588 naive_executor.cc:164] ---  skip [concat_13.tmp_0], fetch -> fetch
W0825 22:51:50.753075  3588 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.6
W0825 22:51:50.768077  3588 gpu_resources.cc:149] device: 0, cuDNN Version: 8.4.
I0825 22:51:50.771077  3588 tensorrt_engine_op.h:472] This process is generating calibration table for Paddle TRT int8...

Process finished with exit code -1073741819 (0xC0000005)

**Comment by LokeZhou** [comment]
问题是否解决？
