### ISSUE TITLE
paddledetection中在coco test-dev测试集上进行评估

### ISSUE THREAD

**Issue by changzipeng** [PaddlePaddle/PaddleDetection#8575]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

比如我用的模型是rtdetr模型，在执行eval.py的时候，只会对coco val2017数据集进行评估，但是我想看一下该模型在coco test-dev上的指标，我看在coco_detection.yml配置文件中设置了TestDataset，但是好像没有办法再eval.py中进行评估，请问可不可以将EvalDataset中的anno_path和image_dir修改为test数据集label及图片，这样进行评估和上传到coco官网进行评估一样嘛，还是说paddledetection现在已经支持test-dev的评估了呢

**Comment by LokeZhou** [comment]
可以把EvalDataset 里的路径文件换为test的
