### ISSUE TITLE
paddledetection在coco test2017上进行评估，计算指标全是-1是怎么回事？

### ISSUE THREAD

**Issue by changzipeng** [PaddlePaddle/PaddleDetection#8576]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![ade3b76fd6a35f26a2826cc4757c204](https://github.com/PaddlePaddle/PaddleDetection/assets/122015630/e312cfc6-7092-443b-af56-3a570882df3e)
这是我今天评估的结果，之前在coco val2017上边训练边评估的时候是可以计算出指标的，现在那边还在训练，然后我修改了下配置文件打算换成test-dev数据集测试一下，没想到返回来的全是-1！

**Comment by LokeZhou** [comment]
检查一下test-dev数据集是否完整
