### ISSUE TITLE
ppyoloe训练模型

### ISSUE THREAD

**Issue by Quentin-Song** [PaddlePaddle/PaddleDetection#8577]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly W0827 17:56:00.471585 65541 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.2 W0827 17:56:00.887068 65541 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2. Traceback (most recent call last):   File "train.py", line 183, in <module>     main()   File "train.py", line 179, in main     run(FLAGS, cfg)   File "train.py", line 132, in run     trainer.train(FLAGS.eval)   File "/home/quentin/TCP/px_yes_adi/src/AI/hmls_AI_backend/ppdet/engine/trainer.py", line 539, in train     outputs = model(data)   File "/root/miniconda3/envs/mypaddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__ Exception in thread Thread-1: Traceback (most recent call last):   File "/root/miniconda3/envs/mypaddle/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 623, in _get_data     data = self._data_queue.get(timeout=self._timeout)   File "/root/miniconda3/envs/mypaddle/lib/python3.7/multiprocessing/queues.py", line 105, in get     raise Empty _queue.Empty  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/root/miniconda3/envs/mypaddle/lib/python3.7/threading.py", line 926, in _bootstrap_inner     self.run()   File "/root/miniconda3/envs/mypaddle/lib/python3.7/threading.py", line 870, in run     self._target(*self._args, **self._kwargs)   File "/root/miniconda3/envs/mypaddle/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 536, in _thread_loop     batch = self._get_data()   File "/root/miniconda3/envs/mypaddle/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 639, in _get_data     "pids: {}".format(len(failed_workers), pids)) RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 65698      return self.forward(*inputs, **kwargs)   File "/home/quentin/TCP/px_yes_adi/src/AI/hmls_AI_backend/ppdet/modeling/architectures/meta_arch.py", line 55, in forward     self.inputs = inputs   File "/root/miniconda3/envs/mypaddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1340, in __setattr__     object.__setattr__(self, name, value)   File "/root/miniconda3/envs/mypaddle/lib/python3.7/site-packages/paddle/fluid/multiprocess_utils.py", line 135, in __handler__     core._throw_error_if_process_failed() SystemError: (Fatal) DataLoader process (pid 65698) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:188)

### 复现环境 Environment

paddlepaddle_gpu==2.42

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by xiaoli-feidao** [comment]
请问这个问题解决了吗  我同样的docker 同样的数据 换个电脑就报同样的错误，另一个电脑运行正常

**Comment by LokeZhou** [comment]
更新一下paddle版本试试
