### ISSUE TITLE
使用Cascade RCNN模型替换主干网络为swin transformer后无法使用tensorrt推理，替换前可以正常推理

### ISSUE THREAD

**Issue by lrp123456** [PaddlePaddle/PaddleDetection#8585]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: -1
combine_method: nms
cpu_threads: 1
device: GPU
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: /dev/shm/COCO_labelImg_format_COCO_format/val2017
image_file: None
match_metric: ios
match_threshold: 0.6
model_dir: ./inference_model/my_quant_swin/
output_dir: output
overlap_ratio: [0.25, 0.25]
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: True
run_mode: trt_fp32
save_images: True
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
slice_infer: False
slice_size: [640, 640]
threshold: 0.5
tracker_config: None
trt_calib_mode: True
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_coco_category: False
use_dark: True
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
The RCNN export model is used for ONNX and it only supports batch_size = 1
-----------  Model Configuration -----------
Model Arch: RCNN
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--transform op: PadStride
--------------------------------------------

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::framework::ir::SubGraphFuser::ReplaceNodesWithSubGraphs()
11  paddle::framework::ir::SubgraphDetector::operator()()
12  paddle::framework::ir::SubgraphDetector::MarkNodesInsideSubGraph()
13  paddle::inference::tensorrt::OpTeller::Tell(paddle::framework::ir::Node const*, bool, bool)
14  paddle::inference::tensorrt::SimpleOpTypeSetTeller::operator()(paddle::framework::OpDesc const&, bool, bool)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1693290558 (unix time) try "date -d @1693290558" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 14539 (TID 0x2b4fc13b9880) from PID 0 ***]

/var/spool/slurmd/job706459/slurm_script: line 36: 14539 Segmentation fault      (core dumped) python deploy/python/infer.py --model_dir=./inference_model/my_quant_swin/ --image_dir=/dev/shm/COCO_labelImg_format_COCO_format/val2017 --device=GPU --run_mode=trt_fp32 --run_benchmark=True --trt_calib_mode=False

**Comment by LokeZhou** [comment]
可能是算子不支持
