### ISSUE TITLE
HRNet关键点模型训练问题

### ISSUE THREAD

**Issue by Bradly-s** [PaddlePaddle/PaddleDetection#8587]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

标注了4个关键点（名称、顺序均与coco的不同，但格式相同）。
其配置文件的前半部分如下所示：
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/49717982/dde4d415-ae92-47d3-9f84-90d6c598a083)
训练中开启了验证--eval
### 问题（报错如下）：
ppdet.engine INFO: Eval iter: 0
ppdet.metrics.keypoint_metrics INFO: The keypoint result is saved to output/keypoints_results.json.
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *keypoints*
Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main()
  File "tools/train.py", line 198, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 151, in run
    trainer.train(FLAGS.eval)
  File "/PycharmProjects/PaddleDetection/ppdet/engine/trainer.py", line 599, in train
    self._eval_with_loader(self._eval_loader)
  File "/PycharmProjects/PaddleDetection/ppdet/engine/trainer.py", line 650, in _eval_with_loader
    metric.accumulate()
  File "/PycharmProjects/PaddleDetection/ppdet/metrics/keypoint_metrics.py", line 201, in accumulate
    coco_eval.evaluate()
  File "/home/dp504/miniconda3/envs/paddle/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 149, in evaluate
    for imgId in p.imgIds
  File "/home/dp504/miniconda3/envs/paddle/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 150, in <dictcomp>
    for catId in catIds}
  File "/home/dp504/miniconda3/envs/paddle/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 229, in computeOks
    e = (dx**2 + dy**2) / vars / (gt['area']+np.spacing(1)) / 2
ValueError: operands could not be broadcast together with shapes (4,) (17,) 

==============================================================================
版本信息如下：
Package              Version
-------------------- -------------
aiofiles             23.1.0
aiohttp              3.8.4
aiosignal            1.3.1
altair               4.2.2
anyio                3.6.2
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
astor                0.8.1
async-timeout        4.0.2
asynctest            0.13.0
attrdict             2.0.1
attrs                22.2.0
av                   10.0.0
Babel                2.12.1
backcall             0.2.0
bce-python-sdk       0.8.79
beautifulsoup4       4.11.2
bleach               6.0.0
Brotli               1.0.9
certifi              2022.12.7
cffi                 1.15.1
charset-normalizer   3.1.0
click                8.1.3
colorama             0.4.6
colorlog             6.7.0
cycler               0.11.0
Cython               0.29.33
datasets             2.13.1
debugpy              1.6.6
decorator            5.1.1
decord               0.6.0
defusedxml           0.7.1
dill                 0.3.4
entrypoints          0.4
fastapi              0.95.0
fastjsonschema       2.16.3
ffmpy                0.3.0
filelock             3.10.0
Flask                2.2.3
Flask-Babel          2.0.0
fonttools            4.38.0
frozenlist           1.3.3
fsspec               2023.1.0
future               0.18.3
gevent               22.10.2
geventhttpclient     2.0.2
gradio               3.22.1
greenlet             2.0.2
grpcio               1.51.3
h11                  0.14.0
httpcore             0.16.3
httpx                0.23.3
huggingface-hub      0.13.2
idna                 3.4
imageio              2.31.1
importlib-metadata   6.1.0
importlib-resources  5.12.0
ipykernel            6.16.2
ipython              7.34.0
ipython-genutils     0.2.0
ipywidgets           8.0.4
itsdangerous         2.1.2
jedi                 0.18.2
jieba                0.42.1
Jinja2               3.1.2
joblib               1.2.0
jsonschema           4.17.3
jupyter              1.0.0
jupyter_client       7.4.9
jupyter-console      6.6.3
jupyter_core         4.12.0
jupyter-server       1.23.6
jupyterlab-pygments  0.2.2
jupyterlab-widgets   3.0.5
kiwisolver           1.4.4
lap                  0.4.0
linkify-it-py        2.0.0
llvmlite             0.39.1
lmdb                 1.4.1
markdown-it-py       2.2.0
MarkupSafe           2.1.2
matplotlib           3.5.3
matplotlib-inline    0.1.6
mdit-py-plugins      0.3.3
mdurl                0.1.2
mistune              2.0.5
motmetrics           1.4.0
mpmath               1.3.0
multidict            6.0.4
multiprocess         0.70.12.2
nbclassic            0.5.3
nbclient             0.7.2
nbconvert            7.2.10
nbformat             5.7.3
nest-asyncio         1.5.6
networkx             2.6.3
notebook             6.5.3
notebook_shim        0.2.2
numba                0.56.4
numpy                1.21.6
onnx                 1.13.1
opencv-python        4.5.5.64
opt-einsum           3.3.0
orjson               3.8.7
packaging            23.0
paddle-bfloat        0.1.7
paddle2onnx          1.0.8
paddledet            2.6.0
paddlefsl            1.1.0
paddlenlp            2.5.2
paddlepaddle-gpu     0.0.0.post116
pandas               1.1.5
pandocfilters        1.5.0
parso                0.8.3
pexpect              4.8.0
pickleshare          0.7.5
Pillow               9.4.0
pip                  23.0.1
pkgutil_resolve_name 1.3.10
prometheus-client    0.16.0
prompt-toolkit       3.0.38
protobuf             4.23.4
psutil               5.9.4
ptyprocess           0.7.0
pyarrow              12.0.1
pyclipper            1.3.0.post4
pycocotools          2.0.6
pycparser            2.21
pycryptodome         3.17
pydantic             1.10.6
pydub                0.25.1
Pygments             2.14.0
pyparsing            3.0.9
pyrsistent           0.19.3
python-dateutil      2.8.2
python-multipart     0.0.6
python-rapidjson     1.10
pytz                 2022.7.1
PyWavelets           1.3.0
PyYAML               6.0
pyzmq                25.0.1
qtconsole            5.4.1
QtPy                 2.3.0
rarfile              4.0
requests             2.28.2
rfc3986              1.5.0
rich                 13.5.2
scikit-image         0.19.3
scikit-learn         1.0.2
scipy                1.7.3
Send2Trash           1.8.0
sentencepiece        0.1.99
seqeval              1.2.2
setuptools           67.6.1
shapely              2.0.1
SimpleITK            2.2.1
six                  1.16.0
sklearn              0.0
sniffio              1.3.0
soupsieve            2.4
starlette            0.26.1
sympy                1.10.1
terminado            0.17.1
terminaltables       3.1.10
threadpoolctl        3.1.0
tifffile             2021.11.2
tinycss2             1.2.1
toolz                0.12.0
tornado              6.2
tqdm                 4.65.0
traitlets            5.9.0
tritonclient         2.31.0
typeguard            2.13.3
typer                0.9.0
typing_extensions    4.5.0
uc-micro-py          1.0.1
urllib3              1.26.15
uvicorn              0.21.1
visualdl             2.4.2
wcwidth              0.2.6
webencodings         0.5.1
websocket-client     1.5.1
websockets           10.4
Werkzeug             2.2.3
wheel                0.40.0
widgetsnbextension   4.0.5
x2paddle             1.4.0
xmltodict            0.13.0
xxhash               3.3.0
yarl                 1.8.2
zipp                 3.15.0
zope.event           4.6
zope.interface       6.0

**Comment by MianMianMeow** [comment]
你好，我也在尝试4个关键点的训练。num_classes我的理解是实例的类别数量，num_joints才是关键点的数量，如有错误请指正哈。我的配置yml如下：
```
use_gpu: true
log_iter: 5
save_dir: output
snapshot_epoch: 10
weights: output/tinypose_256x192/model_final
epoch: 420
num_joints: &num_joints 4
pixel_std: &pixel_std 200
metric: KeyPointTopDownCOCOEval
num_classes: 1
train_height: &train_height 256
train_width: &train_width 192
trainsize: &trainsize [*train_width, *train_height]
hmsize: &hmsize [48, 64]
flip_perm: &flip_perm []
```

**Comment by Bradly-s** [comment]
好的，感谢。已解决。

**Comment by zhaoxin111** [comment]
> 好的，感谢。已解决。

你好，请问你这个问题解决了吗，我也遇到这个报错了，我看了下问题是调用cocoeval时，coco写死了kp_sigma是17，但自定义数据集不一定是17，所以才会shape对不上，这只能改cocoeval里的sigma吗？
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/9295202/2bef8426-9b17-4ab7-919f-94cc8b904d33)
