### ISSUE TITLE
blazeface使用tensorRT推理，如何确定动态shape尺寸？

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/PaddleDetection#8588]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

blazeface用trt推理，提示需要设置几个算子的动态shape尺寸，如何确定尺寸输入多少呢？

**Comment by lyuwenyu** [comment]
使用的paddleinference嘛

**Comment by truthsun22** [comment]
> 使用的paddleinference嘛

是的

**Comment by LokeZhou** [comment]
可以参考这里：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/deploy/TENSOR_RT.md
