### ISSUE TITLE
is there a convenient way to indicate interesting classes at inference?

### ISSUE THREAD

**Issue by tino926** [PaddlePaddle/PaddleDetection#8591]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

The pre-trained model provided typically outputs 80 classes. However, I am only interested in a few specific classes, such as person and backpack. Is there an easy way to specify which classes should be processed during inference?

我目前使用 tools/infer.py 進行測試，請問是否有簡便的方法在inference時指定特定的幾個類別做輸出？乎略其他類別？會想這樣做主要是因為如果所有類別都顯示時，結果的影像會太亂。

**Comment by lyuwenyu** [comment]
目前还不支持这种方式
