### ISSUE TITLE
关于pp-human v2的摔倒检测

### ISSUE THREAD

**Issue by TaroPlay** [PaddlePaddle/PaddleDetection#8597]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我想知道，pp-human v2用于摔倒检测的模块dark_hrnet、mot ppyolo、STGCN的参数量为多少，并没有看到参数量统计的log或者文献。期待您的回复

**Comment by LokeZhou** [comment]
可以根据这个https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/deploy/pipeline/config/infer_cfg_pphuman.yml 里的模型配置，找到https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.7/configs 里面对应的模型配置
