### ISSUE TITLE
怎么设置保存的时候的预测阈值

### ISSUE THREAD

**Issue by aixier** [PaddlePaddle/PaddleDetection#86]
怎么设置保存的时候的预测阈值
看了这个文档：https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/docs/GETTING_STARTED_cn.md
和这个文档
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/configs/dcn/yolov3_r50vd_dcn.yml
没有找到设置

**Comment by jerrywgz** [comment]
请问你说的什么阈值呢？是infer阶段nms的阈值吗？

**Comment by aixier** [comment]
infer的。算了直接在画框的是过滤就好了。不去设置也没关系

**Comment by jerrywgz** [comment]
--draw_threshold 可以设置，https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/tools/infer.py#L256

**Comment by aixier** [comment]
因为这个model需要用在另外的工程里面，所以不能用官方的infer.py

**Comment by qingqing01** [comment]
Related to https://github.com/PaddlePaddle/PaddleDetection/issues/98

score的阈值预测的后处理设置即可~
