### ISSUE TITLE
paddledetection直接预测与导出模型预测结果差别

### ISSUE THREAD

**Issue by Preston-Dong** [PaddlePaddle/PaddleDetection#860]
您好！最近刚入门学习使用paddledetection，在训练完之后，直接使用infer.py和导出模型，再预测出现了明显的差别，如图：
![image](https://user-images.githubusercontent.com/47602592/83610699-768dfd00-a5b2-11ea-83b6-33c5cfd26756.png)
下面的是通过导出的模型最终得到的结果：
![image](https://user-images.githubusercontent.com/47602592/83610770-8efe1780-a5b2-11ea-82d2-75bccbb38424.png)
由于刚入门，对paddledetection还不太熟悉，想请教一下这个问题

**Comment by willthefrog** [comment]
明显的差别是指score有0.02的差异吗？infer.py和cpp预测预处理部分可能不完全一致。

**Comment by Preston-Dong** [comment]
嗯是的，在得分这里，普遍低了一些，其实并不影响，哈哈哈哈

**Comment by willthefrog** [comment]
好的，可能是预处理不同造成的，cpp 预处理和 python不一定完全一致。

**Comment by Preston-Dong** [comment]
多谢呀！至少自己这次知道了点为什么

**Comment by willthefrog** [comment]
不客气
