### ISSUE TITLE
Cascade RCNN (Swin+Bifpn)推理报错

### ISSUE THREAD

**Issue by lrp123456** [PaddlePaddle/PaddleDetection#8600]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

使用如题的模型报错如下：
-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: -1
combine_method: nms
cpu_threads: 1
device: GPU
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: None
image_file: G:\PaddleDetection\dataset\dota_sliced\instances_train2017_images_640_025\000000000001_0_0_640_640.jpg
match_metric: ios
match_threshold: 0.6
model_dir: G:\PaddleDetection\output_inference\c_r_r50_base_swin_neck_small
output_dir: output
overlap_ratio: [0.25, 0.25]
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: paddle
save_images: True
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
slice_infer: False
slice_size: [640, 640]
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_coco_category: False
use_dark: True
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
The RCNN export model is used for ONNX and it only supports batch_size = 1
-----------  Model Configuration -----------
Model Arch: RCNN
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--transform op: PadStride
--------------------------------------------
Traceback (most recent call last):
  File "G:\PaddleDetection\deploy\python\infer.py", line 1114, in <module>
    main()
  File "G:\PaddleDetection\deploy\python\infer.py", line 1082, in main
    detector.predict_image(
  File "G:\PaddleDetection\deploy\python\infer.py", line 408, in predict_image
    result = self.predict()
  File "G:\PaddleDetection\deploy\python\infer.py", line 208, in predict
    self.predictor.run()
ValueError: (InvalidArgument) Shape of Input(Paddings) should be equal to [6], but received [10].
  [Hint: Expected paddings.size() == 6, but received paddings.size():10 != 6:6.] (at ..\paddle\phi\infermeta\unary.cc:2680)
  [operator < pad3d > error]

### 复现环境 Environment

CUDA11.6
paddlepaddle-gpu          0.0.0.post116、
paddledetection：2.6

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
你好，需要检查为什么padding_size不一致，建议先从动态图中debug找原因，然后再逐步过度到静态图
