### ISSUE TITLE
使用 tools/export_model.py 导出模型遇到的问题

### ISSUE THREAD

**Issue by niiikolai** [PaddlePaddle/PaddleDetection#861]
还请麻烦看下如下问题：
1.使用导出的模型在aistudio上预测（deploy/python/infer.py），无论哪张图片总是会出现最后一类的预测结果，在图片下方（其实并没有目标）。

2.模型下载到本地，使用 deploy/python/infer.py 预测时报错
InvalidArgumentError: Fully Connected input and weigth size do not match. input width: 12544,weight height: 12548
  [Hint: Expected in_mat_dims[1] == w_dims0, but received in_mat_dims[1]:12544 != w_dims0:12548.] at (D:\1.7.1\paddle\paddle/fluid/opera
tors/fc_op.h:39)

**Comment by willthefrog** [comment]
能否提供下具体复现步骤？

**Comment by niiikolai** [comment]
1.
1.1先用如下命令导出模型
!python tools/export_model.py -c configs/dcn/cascade_rcnn_dcn_r101_vd_fpn_1x.yml \
        --output_dir=./inference_model \
        -o weights=output/cascade_rcnn_dcn_r101_vd_fpn_1x/best_model
1.2再用如下命令测试
!python deploy/python/infer.py --model_dir=inference_model/cascade_rcnn_dcn_r101_vd_fpn_1x --image_file=dataset/test/val_img/a7.jpg --use_gpu=true

2.
2.1 安装paddle1.7.1
2.2 下载release 0.3到本地
2.3 安装依赖 pip install -r requirements.txt
2.4 在pycharm terminal中输入
python deploy/python/infer.py --model_dir=inference_model/cascade_rcnn_dcn_r101_vd_fpn_1x --image_file=demo/a7.jpg --use_gpu=false 报错:FC ... not match
另外本地我使用的python 是3.6的版本

**Comment by willthefrog** [comment]
本地试了下无法复现，能否试下使用model zoo里下载的weight 及 demo 里的图片是否可以复现呢？

**Comment by niiikolai** [comment]
谢谢，准备使用serving部署到服务器上进行预测。
