### ISSUE TITLE
请问 Paddle 团队有关于 seed 的经验性实验结果吗？

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleDetection#8610]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Torch.manual_seed(3407) is all you need: On the influence of random seeds in deep learning architectures for computer vision https://arxiv.org/abs/2109.08203 中详细调查了 torch seed 对图像类任务的影响， 请问 Paddle 中有类似的调查吗？

**Comment by zhiboniu** [comment]
你好，paddle有类似api paddle.seed
