### ISSUE TITLE
希望支持Go语言

### ISSUE THREAD

**Issue by caitou2019** [PaddlePaddle/PaddleDetection#8618]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

任务目标:
实现Go语言目标检测, 目标跟踪等例子
需求场景:
Go编译型语言, 运行速度快, 语法简洁, 增快项目部署上线, 结合了C++的速度优势与python的简洁度

**Comment by zhiboniu** [comment]
你好，go语言开发者可以参考python、c++案例来做go语言案例开发
