### ISSUE TITLE
[Yolo]yolov4_cspdarknet.pdparams是如何得到的

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/PaddleDetection#8620]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

yolov4_cspdarknet.pdparams  是如何得到的
[下载链接](https://paddlemodels.bj.bcebos.com/object_detection/yolov4_cspdarknet.pdparams) 

https://github.com/PaddlePaddle/PaddleYOLO/commit/76f6c9397809ab60a9811e8ccb414b896daf1e99
我看说明是转换了darknet

那么如何转换darknet到paddle模型上呢？

**Comment by zhiboniu** [comment]
你好，该模型可以使用paddle完成训练
