### ISSUE TITLE
按照官网文档训练检测模型，tools/train.py后提示KeyError: 'image'

### ISSUE THREAD

**Issue by jesung1993** [PaddlePaddle/PaddleDetection#8622]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

按照如下参考文档：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.md**

PaddleDetection 用的release/2.7, PaddlePaddle用的paddlepaddle-gpu==2.5.1.post112。
ppyolo_mbv3_large.yml文件内容如下：
              
      architecture: YOLOv3
      pretrain_weights: 
         https://paddledet.bj.bcebos.com/models/pretrained/MobileNetV3_large_x1_0_ssld_pretrained.pdparams
      norm_type: sync_bn
      use_ema: true
      ema_decay: 0.9998
      use_gpu: false
      
      YOLOv3:
        backbone: MobileNetV3
        neck: PPYOLOFPN
        yolo_head: YOLOv3Head
        post_process: BBoxPostProcess
      
      MobileNetV3:
        model_name: large
        scale: 1.
        with_extra_blocks: false
        extra_block_filters: []
        feature_maps: [13, 16]
      
      PPYOLOFPN:
        in_channels: [160, 368]
        coord_conv: true
        conv_block_num: 0
        spp: true
        drop_block: true
      
      YOLOv3Head:
        anchors: [[11, 18], [34, 47], [51, 126],
                  [115, 71], [120, 195], [254, 235]]
        anchor_masks: [[3, 4, 5], [0, 1, 2]]
        loss: YOLOv3Loss
      
      YOLOv3Loss:
        ignore_thresh: 0.5
        downsample: [32, 16]
        label_smooth: false
        scale_x_y: 1.05
        iou_loss: IouLoss
      
      IouLoss:
        loss_weight: 2.5
        loss_square: true
      
      BBoxPostProcess:
        decode:
          name: YOLOBox
          conf_thresh: 0.005
          downsample_ratio: 32
          clip_bbox: true
          scale_x_y: 1.05
        nms:
          name: MultiClassNMS
          keep_top_k: 10
          nms_threshold: 0.45
          nms_top_k: 100
          score_threshold: 0.005
      
      metric: VOC
      map_type: 11point
      num_classes: 2
      worker_num: 1
      save_dir: dataset/save
      epoch: 12
      
      TrainDataset:
        !VOCDataSet
          dataset_dir: dataset/seal_VOC
          anno_path: train.txt
          label_list: label_list.txt
          data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']
      
      EvalDataset:
        !VOCDataSet
          dataset_dir: dataset/seal_VOC
          anno_path: test.txt
          label_list: label_list.txt
          data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']
      
      TestDataset:
        !ImageFolder
          anno_path: dataset/seal_VOC/label_list.txt

dataset中voc数据文件的目录结构如下：

    /home/PaddleDetection/dataset/seal_VOC
    -valid.txt
    -train.txt
    -label_list.txt
    -JPEGImages
      --1.jpg
      --2.jpg
      --...
    -ImageSets
      --Main
       ---valid.txt
       ---train.txt
    -Annotations
      --1.xml
      --2.xml
      --...
      ...

1.xml的内容如下：

    <annotation>
        <folder>seal_VOC</folder>
        <filename>1.jpg</filename>
        <path>JPEGImages/1.jpg</path>
        <size>
            <width>640</width>
            <height>640</height>
            <depth>3</depth>
        </size>
        <segmented>0</segmented>
        <object>
            <name>redseal</name>
            <pose>Unspecified</pose>
            <truncated>0</truncated>
            <difficult>0</difficult>
            <bndbox>
                <xmin>3</xmin>
                <ymin>3</ymin>
                <xmax>640</xmax>
                <ymax>640</ymax>
            </bndbox>
        </object>
    </annotation>

按照官方文档操作，按照步骤4，输入民命令，开始训练：python3  tools/train.py  -c configs/ppyolo/ppyolo_mbv3_large.yml  --eval后，报错：

        [09/13 17:44:42] ppdet.utils.checkpoint INFO: Finish loading model weights: 
          /root/.cache/paddle/weights/MobileNetV3_large_x1_0_ssld_pretrained.pdparams
        Traceback (most recent call last):
          File "tools/train.py", line 202, in <module>
            main()
          File "tools/train.py", line 198, in main
            run(FLAGS, cfg)
          File "tools/train.py", line 151, in run
            trainer.train(FLAGS.eval)
          File "/home/PaddleDetection/ppdet/engine/trainer.py", line 539, in train
            outputs = model(data)
          File "/usr/local/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
            return self._dygraph_call_func(*inputs, **kwargs)
          File "/usr/local/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
            outputs = self.forward(*inputs, **kwargs)
          File "/home/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 60, in forward
            out = self.get_loss()
          File "/home/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 147, in get_loss
            return self._forward()
          File "/home/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 81, in _forward
            body_feats = self.backbone(self.inputs)
          File "/usr/local/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
            return self._dygraph_call_func(*inputs, **kwargs)
          File "/usr/local/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
            outputs = self.forward(*inputs, **kwargs)
          File "/home/PaddleDetection/ppdet/modeling/backbones/mobilenet_v3.py", line 456, in forward
            x = self.conv1(inputs['image'])
        KeyError: 'image'

困扰我好几天了，请问一下问题出在哪里？

**Comment by To-Wanderer** [comment]
之前用coco格式的数据集的时候出现过相同类型的报错（keyerror)，最后检查发现是数据集中出现了不存在的标签。仅供参考。

**Comment by huanghao128** [comment]
问题解决了吗，遇到同样的问题，是不是PaddleDetection有更新，而对应的印章检测应用的文档没更新
