### ISSUE TITLE
预测框

### ISSUE THREAD

**Issue by HelloAI-twj** [PaddlePaddle/PaddleDetection#864]
请问一下，Paddledetection可以输出预测框的坐标吗

**Comment by willthefrog** [comment]
可以的。默认输出就包含坐标。

**Comment by HelloAI-twj** [comment]
> 可以的。默认输出就包含坐标。

如果我想调用的话，可以用Python代码获取到这个值吗

**Comment by willthefrog** [comment]
可以的，模型输出的就是[class, score, x1, y1, x2, y2]
