### ISSUE TITLE
Error: The index of gather_op should not be empty when the index's rank is 1. 

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/PaddleDetection#867]
配置faster_rcnn_r50_fpn_2x.yml训练时报错：

Error: The index of gather_op should not be empty when the index's rank is 1. 之前训练时我出现这个问题，但我再次运行时成功跑通，所以我无法给你具体的错误，但我仍然想知道这个错误的原因。

**Comment by willthefrog** [comment]
呃，没有复现步骤的话很难确定具体原因啊。

**Comment by liu824** [comment]
那没事了，我这个同样的代码，再运行一次就不报错了，我close这个issue吧
