### ISSUE TITLE
国产化设备运行旋转框s2anet检测模型的单卡检测速度

### ISSUE THREAD

**Issue by QAQTATQAQTAT** [PaddlePaddle/PaddleDetection#8672]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

模型：s2anet_align
数据量：90
图像尺寸：1024×1024
硬件：FT-2000 + 昆仑R200
操作系统：麒麟v10
在用上述模型测试时，后台无其他程序占用，XPU正常调用，经过多次实验，最终的耗时均在420s左右，请问有什么方法提速吗

**Comment by zhiboniu** [comment]
你好，可以参考paddle支持的国产硬件列表，如果在支持列表应该是一样用的
