### ISSUE TITLE
Small bug in rtdetr

### ISSUE THREAD

**Issue by rydenisbak** [PaddlePaddle/PaddleDetection#8680]
https://github.com/PaddlePaddle/PaddleDetection/blob/4877a75210969e42d784af87a2932ecb6c639365/ppdet/modeling/transformers/rtdetr_transformer.py#L498

I got problem with detections if image width and height is not equal. 
This fix solve my problem
 valid_WH = paddle.to_tensor([h, w]).astype(dtype) ->  valid_WH = paddle.to_tensor([w, h]).astype(dtype)

**Comment by lyuwenyu** [comment]
Thanks, It has been fixed in rtdetr repo. I will cherry-pick this into ppdet in future. @rydenisbak 

https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetr_paddle/ppdet/modeling/transformers/rtdetr_transformer.py#L465
