### ISSUE TITLE
模型转换问题

### ISSUE THREAD

**Issue by zelohon** [PaddlePaddle/PaddleDetection#8681]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![5G}RS$ZOZ4{ 2BATZ)W6)TB](https://github.com/PaddlePaddle/PaddleDetection/assets/36800197/c6b51ff4-0820-4570-ba98-6f685fbb32fd)
官网的 这个基础模型我下载下来是正常推理的
![R{DB3422UK(WQ~V41X5G20](https://github.com/PaddlePaddle/PaddleDetection/assets/36800197/a5c5cd44-8e98-4b3d-b1d3-0764268b7dcc)
这个部署模型也是正常推理的  但是 如果我自己去转换这个基础模型到部署模型  就会出现无法推理出结果
python tools/export_model.py -c configs/yolov8/yolov8_s_500e_coco.yml --output_dir=output_inference -o weights=https://paddledet.bj.bcebos.com/models/yolov8_s_500e_coco.pdparams 
我用的是这种转换推理模型方式  转换后  无法推理

**Comment by zelohon** [comment]
没人回答吗？  这个问题一直没有解决！

**Comment by zhiboniu** [comment]
你好，可以关注下模型导出的不同设置是否相同
