### ISSUE TITLE
VOC 格式的数据可以用COCO metric吗？

### ISSUE THREAD

**Issue by lyf6** [PaddlePaddle/PaddleDetection#8685]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

VOC 格式的数据可以用COCO metric吗？

**Comment by zhiboniu** [comment]
两者标注格式不同，需要做格式转换后使用
