### ISSUE TITLE
c++端部署疑问

### ISSUE THREAD

**Issue by zelohon** [PaddlePaddle/PaddleDetection#8686]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在C++端部署   如果版本更新新功能  c++端的如何更新呢？

**Comment by zhiboniu** [comment]
不大明白你的意思，如果模型有更新一般会在c++Demo中适配
