### ISSUE TITLE
单机多卡，docker环境下使用paddle出现nccl报错

### ISSUE THREAD

**Issue by overjjjj** [PaddlePaddle/PaddleDetection#8687]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在单机多卡，docker环境下出现nccl报错，但通过nvdia-nccl-test测试后nccl已正常安装。
错误信息如下
WARNING:root:PaddlePaddle meets some problem with 8 GPUs. This may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.co m/NVIDIA/nccl-tests
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
WARNING:root:
 Original Error is: (External) CUDA error(209), no kernel image is available for execution on the device.
  [Hint: 'cudaErrorNoKernelImageForDevice'. This indicates that there is no kernel image available that is                                                                                suitable for the device. This can occur when a user specifiescode generation options for a particular CUDA source file that do not include the corresponding device configuration.] (at/paddle/paddle/fluid/framew ork/details/all_reduce_op_handle.cc:299)
PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddle now.

**Comment by zhiboniu** [comment]
你好，如果docker有问题推荐使用官方docker，https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html
