### ISSUE TITLE
paddlepaddle预测时间问题

### ISSUE THREAD

**Issue by wq1530825108** [PaddlePaddle/PaddleDetection#8690]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

情况一：在for函数里预测一组图片的时间比较稳定且相对较短
情况二：如果单击按钮预测一张图片   如果单击的频率大于200ms   预测的时间不稳定  且相对与情况一预测的时间偏长，这种情况工业场景预测时间不稳定会出现问题的？

如何达到预测时间稳定的情况 也就是情况一那种状态？

**Comment by zhiboniu** [comment]
你好，这个应该跟你说的情况二中单击按钮的具体实现有关。每次单击是否会造成cpu调度的额外损耗，导致整体时间偏长
