### ISSUE TITLE
在deploy/pipeline/pphuman/mtmct.py 的gen_restxt函数中，因正则表达式不严谨导致的BUG

### ISSUE THREAD

**Issue by lanfengc** [PaddlePaddle/PaddleDetection#8691]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

在gen_restxt 中，有一行代码：
`pattern = re.compile(r'c(\d)_t(\d)')`
下方有
`cid, tid = pattern.search(key).groups()`
当key 是"c0_t9"这样数字是一位的时候，没有问题。
当key 是"c10_t99" 或者 "c100_t999" 等多位数字时候，导致无法提取到数字，程序报错退出。

### 复现环境 Environment

任意环境均能复现。

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
好的，感谢反馈，已收到
