### ISSUE TITLE
关于训练后测试bbox的类别不符的问题

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#87]
通过单张图片迭代500次后测试得到了比较好的效果
如图：
![aachen58](https://user-images.githubusercontent.com/45937014/70491548-7b5e8080-1b3c-11ea-9024-8f7c1fb66962.png)

![aachen155](https://user-images.githubusercontent.com/45937014/70491976-d9d82e80-1b3d-11ea-89e9-edd838fc515c.png)

但是我增大样本数量  数据集由原来的单张改变为150张
进行训练后得到的效果  个别类别是错误的 
而且收敛的比较慢   通过--eval评估发现ap ar也都特别小  0.01-0.1这个区间
想知道是什么原因会导致这样

训练4w轮后的测试结果如图

![aachen143](https://user-images.githubusercontent.com/45937014/70492227-b2359600-1b3e-11ea-9bcb-2e56ee0b3e80.png)
![aachen88](https://user-images.githubusercontent.com/45937014/70492240-b792e080-1b3e-11ea-9c5c-569c35e0795f.png)
可以看到person类别是正确的 但是car和 terrain就是不对的  想知道这是什么原因可能会导致

**Comment by jerrywgz** [comment]
再可视化的时候可以，再coco_eval.py的get_category_info有相关clsid2catid, catid2name 可以打印看下这个是不是符合预期的。在训练过程中是根据coco_loader.py中的clsid2catid, catid2name 来定义类别的，可以看下这两个是不是一致的

**Comment by shuxsu** [comment]
> 可视化的时候可以在coco_eval.py的get_category_info中查看clsid2catid, catid2name信息 可以看下这个是不是符合预期的。在训练过程中是根据coco_loader.py中的clsid2catid, catid2name 来定义类别的，可以看下这两个是不是一致的

训练过程打印  infer可视化再打印看看是不是一致的吗？

**Comment by shuxsu** [comment]
> catid2name

训练过程打印发现：

> index created!
{1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6}
{'sky': 1, 'building': 2, 'vegetation': 3, 'person': 4, 'car': 5, 'terrain': 6}
和我数据集id不相符合啊，数据集id为：

> categories":[6 items
0:{3 items
"supercategory":string"component"
"id":int1
"name":string"sky"
}
1:{3 items
"supercategory":string"component"
"id":int2
"name":string"building"
}
2:{3 items
"supercategory":string"component"
"id":int3
"name":string"terrain"
}
3:{3 items
"supercategory":string"component"
"id":int4
"name":string"person"
}
4:{3 items
"supercategory":string"component"
"id":int5
"name":string"vegetation"
}
5:{3 items
"supercategory":string"component"
"id":int6
"name":string"car"
}

**Comment by shuxsu** [comment]
> 可视化的时候可以在coco_eval.py的get_category_info中查看clsid2catid, catid2name信息 可以看下这个是不是符合预期的。在训练过程中是根据coco_loader.py中的clsid2catid, catid2name 来定义类别的，可以看下这两个是不是一致的

找到问题所在可能为： 
训练集和验证集的  类别id并不一样导致，是否为x2coco.py脚本文件导致？
因为转换后数据集和验证集不再为一样的id对应类别 如上面数据集代码所示
1：sky
2：building
3：训练集为terrain  验证集为vegetation
4：person
5：训练集为car    验证集为vegetation
6：训练集为terrain 验证集为car

当使用训练集的json文件进行测试时发现  bbox类别标签正确

**Comment by jerrywgz** [comment]
这个问题应该是你是分别对训练集和测试集进行转换的，在x2coco当中label_to_num这个字典产生的顺序不一致导致的，https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/ppdet/data/tools/x2coco.py#L171 你可以在这里手动给定一个label_to_num的字典，保证训练和测试集转换后对应的cat_id顺序是一致的

**Comment by shuxsu** [comment]
解决
