### ISSUE TITLE
yolov4_cspdarknet_voc推理时，检测的低分框多，导致推理速度慢

### ISSUE THREAD

**Issue by diligentpeng** [PaddlePaddle/PaddleDetection#870]
代码：使用    tool/infer.py

其中一张图片的结果
第0张图片  检测到框的数量 29
打印框的得分 :第1个框 category_id： 0 score： 0.0031717403326183558
打印框的得分 :第2个框 category_id： 0 score： 0.0027068716008216143
打印框的得分 :第3个框 category_id： 1 score： 0.9970547556877136
打印框的得分 :第4个框 category_id： 1 score： 0.9950928688049316
打印框的得分 :第5个框 category_id： 1 score： 0.0024673198349773884
打印框的得分 :第6个框 category_id： 1 score： 0.002446211175993085
打印框的得分 :第7个框 category_id： 2 score： 0.9902437925338745
打印框的得分 :第8个框 category_id： 2 score： 0.9886312484741211
打印框的得分 :第9个框 category_id： 2 score： 0.0011978072579950094
打印框的得分 :第10个框 category_id： 4 score： 0.009197567589581013
打印框的得分 :第11个框 category_id： 4 score： 0.004211307503283024
打印框的得分 :第12个框 category_id： 9 score： 0.0030405137222260237
打印框的得分 :第13个框 category_id： 10 score： 0.0018510916270315647
打印框的得分 :第14个框 category_id： 10 score： 0.0018076719716191292
打印框的得分 :第15个框 category_id： 10 score： 0.0012732124887406826
打印框的得分 :第16个框 category_id： 14 score： 0.0032876948826014996
打印框的得分 :第17个框 category_id： 14 score： 0.0015140471514314413
打印框的得分 :第18个框 category_id： 15 score： 0.008369611576199532
打印框的得分 :第19个框 category_id： 15 score： 0.0036690193228423595
打印框的得分 :第20个框 category_id： 16 score： 0.025101616978645325
打印框的得分 :第21个框 category_id： 16 score： 0.01028266828507185
打印框的得分 :第22个框 category_id： 18 score： 0.001469713170081377
打印框的得分 :第23个框 category_id： 19 score： 0.003822282189503312
打印框的得分 :第24个框 category_id： 19 score： 0.0018613646971061826
打印框的得分 :第25个框 category_id： 20 score： 0.025168532505631447
打印框的得分 :第26个框 category_id： 20 score： 0.01115255057811737
打印框的得分 :第27个框 category_id： 21 score： 0.0027399619575589895
打印框的得分 :第28个框 category_id： 24 score： 0.0016381327295675874
打印框的得分 :第29个框 category_id： 24 score： 0.0014791288413107395

而对同一张图片：yolov3_darknet 和 fater_rcnn_r50_fpn会好很多
yolov3:
第0张图片 检测到框的数量 4
打印框的得分 :第1个框 category_id： 9 score： 0.02805972658097744
打印框的得分 :第2个框 category_id： 19 score： 0.9374240040779114
打印框的得分 :第3个框 category_id： 19 score： 0.20605266094207764
打印框的得分 :第4个框 category_id： 20 score： 0.010907121002674103

fater_rnn_r50_fpn
第0张图片 检测到框的数量 1
打印框的得分 :第1个框 category_id： 21 score： 0.9988721013069153

**Comment by diligentpeng** [comment]
想请教一下，这个问题如何解决

**Comment by jerrywgz** [comment]
yolov4在预测的时候https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/configs/yolov4/yolov4_cspdarknet_voc.yml#L26 没有限制nms输出的box个数，请问可视化的效果如何呢

**Comment by diligentpeng** [comment]
可视化结果还比较好的

**Comment by jerrywgz** [comment]
嗯嗯效果还好的话说明模型训练没有大问题，可以把nms中的score_thresh调大或是其他参数。另外，目前yolov4中的mish激活函数是使用现有api组合的方式，我们已经进行了优化，提升了推理速度，会在后续的paddle版本中发布

**Comment by diligentpeng** [comment]
好的  谢谢
