### ISSUE TITLE
如何修改能将检测和目标的一些属性一起训练？

### ISSUE THREAD

**Issue by HaoLiuHust** [PaddlePaddle/PaddleDetection#8700]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

任务是检测人体的同时，输出人体的年龄，性别之类的属性，而不是分为检测+属性模型2个模型，PaddleDetection能做到吗？

**Comment by zhiboniu** [comment]
你好，可以自己改造在输出box的同时增加几个属性维度

**Comment by HaoLiuHust** [comment]
多谢
