### ISSUE TITLE
模型预测包含未初始化张量

### ISSUE THREAD

**Issue by tfy02** [PaddlePaddle/PaddleDetection#8708]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

import cv2
import paddle
from onvif import ONVIFCamera
from paddle.inference import Config
from paddle.inference import create_predictor
from paddle.inference import PrecisionType
import numpy as np
ip_address = '192.168.1.64'
port = 80
username = 'admin'
password = 'a1234567'
model_path = 'C:\\Users\\dwll\\Desktop\\chepython\\python\\model.pdmodel'
params_path = 'C:\\Users\\dwll\\Desktop\\chepython\\python\\model.pdiparams'
# 初始化ONVIF相机
mycam = ONVIFCamera(ip_address, port, username, password)
# 获取媒体服务
media = mycam.create_media_service()
# 获取配置
media_profile = media.GetProfiles()[0]
# 获取流URI
stream_uri = media.GetStreamUri({'StreamSetup': {'Stream': 'RTP-Unicast', 'Transport': 'RTSP'}, 'ProfileToken': media_profile.token})
# 创建PaddlePaddle配置和预测器
config = Config(model_path, params_path)
# 设置PaddlePaddle配置为CPU
config.switch_ir_optim(True)  # 打开优化开关
config.disable_gpu()
config.enable_mkldnn()  # 使用MKLDNN加速
config.set_cpu_math_library_num_threads(4)  # 设置CPU线程数
config.enable_memory_optim()
config.set_mkldnn_cache_capacity(10)
config.switch_use_feed_fetch_ops(False)
config.switch_specify_input_names(True)
config.enable_profile()
config.set_model(model_path, params_path)
predictor = create_predictor(config)
cap = cv2.VideoCapture(stream_uri.Uri)
# 模型要求的输入尺寸是320*320
input_size = (320, 320)

# 归一化时使用的均值和标准差
mean_val = [0.485, 0.456, 0.406]  # 示例值，需要替换为模型的实际值
std_dev = [0.229, 0.224, 0.225]   # 示例值，需要替换为模型的实际值

LABEL = ["bird"]
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # 对帧进行预处理，例如：调整大小、归一化等（根据模型需求调整）
    # 调整大小到模型要求的输入尺寸
    resized_frame = cv2.resize(frame, input_size)
    
    # 转换颜色从BGR到RGB
    rgb_frame = cv2.cvtColor(resized_frame, cv2.COLOR_BGR2RGB)

    # 归一化处理
    rgb_frame = rgb_frame / 255.0  # 将像素值从0-255缩放到0-1
    normalized_frame = (rgb_frame - mean_val) / std_dev

    
    frame_normalized = normalized_frame.astype('float32')
    # 将处理后的图像转换为PaddlePaddle的输入格式
    # HWC to CHW
    frame_transposed = np.transpose(frame_normalized, (2, 0, 1))

    # 增加batch维度
    frame_input = frame_transposed[np.newaxis, :]
    
    # 设置输入
    input_names = predictor.get_input_names()
    input_tensor = predictor.get_input_handle(input_names[0])
    input_tensor.reshape(frame_input.shape)
    input_tensor.copy_from_cpu(frame_input)

    # 执行预测
    predictor.run()

    # 获取输出
    output_names = predictor.get_output_names()
    output_tensor = predictor.get_output_handle(output_names[0])
    output_data = output_tensor.copy_to_cpu()

    # 解析检测结果
    for data in output_data[0]:
        confidence = data[1]
        if confidence > 0.3:
            xmin, ymin, xmax, ymax = map(int, data[2:])
            cv2.rectangle(frame, (xmin, ymin), (xmax, ymax), (0, 255, 0), 2)

            # 可以添加标签显示代码，例如：
            label = LABEL[0]  # 鸟类标签
            cv2.putText(frame, f'{label} {confidence:.2f}', (xmin, ymin - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

    # 显示处理后的帧
    cv2.imshow('Detection', frame)

    # 按 'q' 键退出
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    
cap.release()
cv2.destroyAllWindows()
这是我的代码，我使用的模型是ppyolo_mbv3_large_coco，运行之后报错如下，Traceback (most recent call last):
  File "c:\Users\dwll\Desktop\chepython\python\jiance001.py", line 78, in <module>
    predictor.run()
ValueError: (InvalidArgument) The conv2d Op's Input Variable `Input` contains uninitialized Tensor.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at ..\paddle\fluid\framework\operator.cc:2411)
  [operator < conv2d > error]
请问如何解决。

**Comment by LokeZhou** [comment]
先验证直接跑官方教程是否成功https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/deploy/python/README.md
