### ISSUE TITLE
paddleDetection docker2.4版本无法运行jupyterNotebook文件

### ISSUE THREAD

**Issue by keeper-jie** [PaddlePaddle/PaddleDetection#8709]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Other

### Bug描述 Describe the Bug

目标：使用vscode连接docker container进行ipynb文件开发

报错描述：使用vscode远程登录到dev容器中，新建ipynb文件不能运行cell，一直在转圈圈，以为是因为没有开启jupyterNotebook服务器的缘故，使用`jupyter notebook --ip=0.0.0.0 --port=3344 --no-browser --allow-root`可以进入jupyter网站，但是也不可以正常运行，显示无法获取内核

### 复现环境 Environment

paddle Detection docker安装命令：`docker run --name dev --runtime=nvidia -v $PWD:/mnt -p 8888:8888 -it paddlecloud/paddledetection:2.4-gpu-cuda10.2-cudnn7-e9a542 /bin/bash`

使用vscode远程登陆docker container新建ipynb运行cell即可重现错误

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by LokeZhou** [comment]
先排除vscode远程连接的因素，直接上终端看是否可以运行
