### ISSUE TITLE
track模型转为onnx，ByteTrack等如何转为onnx并且推理，追踪模型应该是需要前后帧一起推理的，bs为1该如何设置？希望官方提供demo

### ISSUE THREAD

**Issue by hardlipay** [PaddlePaddle/PaddleDetection#8720]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 2. 需求场景（请描述你的项目中为什么需要用此功能）; 3. 功能描述（请简单描述或设计这个功能）

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by LokeZhou** [comment]
模型导出可以直接用https://github.com/PaddlePaddle/Paddle2ONNX， 追踪模型是由检测模型+匹配逻辑实现的，bs=1是送到检测模型里面，追踪的id记录由匹配逻辑实现

**Comment by hardlipay** [comment]
> 模型导出可以直接用[https://github.com/PaddlePaddle/Paddle2ONNX，](https://github.com/PaddlePaddle/Paddle2ONNX%EF%BC%8C) 追踪模型是由检测模型+匹配逻辑实现的，bs=1是送到检测模型里面，追踪的id记录由匹配逻辑实现

谢谢，了解了，我现在已经做好了逻辑追踪实现的，好像另一种追踪不是逻辑实现的，是有重识别模型的，请问你做过吗？实现方法咋样走

**Comment by lsewcx** [comment]
你好能详细讲讲输入的格式和输出的格式吗

**Comment by hardlipay** [comment]
> 你好能详细讲讲输入的格式和输出的格式吗

这个模型就是目标检测，追踪是靠多个逻辑结合判断的。底层部署应该有个结构体存储轨迹，再用轨迹去找框等等

**Comment by lsewcx** [comment]
@hardlipay 但是我转onnx推理过后发现它的输出有两个，不太清楚两个是具体干什么用的，有一个应该是目标检测的
