### ISSUE TITLE
复现论文实验时出现了nan问题

### ISSUE THREAD

**Issue by LuckyMeMePxm** [PaddlePaddle/PaddleDetection#8722]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Error: /paddle/paddle/phi/kernels/gpu/bce_loss_kernel.cu:42 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but received nan.

**Comment by LokeZhou** [comment]
是哪篇论文呢？一般出现nan是有除0的操作，或数据溢出，可以查一下
