### ISSUE TITLE
单张图片物体大概有2000个的时候，评估map显示MaxDets=100,这里需要修改吗？

### ISSUE THREAD

**Issue by li-an666** [PaddlePaddle/PaddleDetection#8723]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://github.com/PaddlePaddle/PaddleDetection/assets/82367713/ced1bc45-7eb3-47b8-be07-88beab991016)

**Comment by LokeZhou** [comment]
需要的，https://github.com/PaddlePaddle/PaddleDetection/blob/2d3517aa0b8adeec2752db2411c61ee56ec5a0af/ppdet/metrics/coco_utils.py#L78
