### ISSUE TITLE
postprocess 函数 地方有写错

### ISSUE THREAD

**Issue by dreaming12580** [PaddlePaddle/PaddleDetection#8724]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

    def postprocess(self, inputs, result):
        # postprocess output of predictor
        keep_idx = result['boxes'][:, 1] > self.threshold
        result['boxes'] = result['boxes'][keep_idx]
        np_boxes_num = [len(result['boxes'])]
        if np_boxes_num[0] <= 0:
            print('[WARNNING] No object detected.')
            result = {'boxes': np.zeros([0, 6]), 'boxes_num': [0]}
        result = {k: v for k, v in result.items() if v is not None}
        return result

这里keep_idx = result['boxes'][:, 1] > self.threshold ,  应该是用 result['scores']吧

### 复现环境 Environment

-os:linux

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by LokeZhou** [comment]
感谢反馈，如有兴趣，可提交修改pr
