### ISSUE TITLE
help help

### ISSUE THREAD

**Issue by no5-hao** [PaddlePaddle/PaddleDetection#8727]
### 问题确认 Search before asking

- [ ] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问我只找得到ppyoloe的源代码，但是并没有看到有pp-yolo-sod的源代码，只有与它相关的yaml文件

**Comment by LokeZhou** [comment]
是在ppyolo的基础上改网络配置，可以参考这里https://github.com/PaddlePaddle/PaddleDetection/tree/2d3517aa0b8adeec2752db2411c61ee56ec5a0af/configs/smalldet

**Comment by highquanglity** [comment]
@LokeZhou @no5-hao can you tell me the information of ppyoloe-sod-s and ppyoloe-p2, I cant find it anywhere. Thank you so much
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/91304338/e865e9e1-2520-474e-a740-ac9af7d56f69)
