### ISSUE TITLE
关于自己修改网络结构

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#873]
官方给的例子都提供了预训练模型，如果在这基础上修改网络结构的话，预训练模型怎么解决？

**Comment by jerrywgz** [comment]
目前检测库在加载预训练模型时，会自动忽略形状不匹配的权重，当然也可以手动指定不加载的权重名称，支持通配符的方式，详细可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/advanced_tutorials/TRANSFER_LEARNING_cn.md
