### ISSUE TITLE
RT-DETR训练

### ISSUE THREAD

**Issue by sdreamforchen** [PaddlePaddle/PaddleDetection#8734]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

对超参数进行了调整，找到了3个精度一样的超参配置；但是其中2个精度在训练的前中期精度验证中明显高于第1个（共72epoch），但是最后精度mAP一致，ap50则相比有所增加，请问有何建议吗？

**Comment by lyuwenyu** [comment]
这很正常吧  收敛趋势不一样

**Comment by sdreamforchen** [comment]
哦，那我不纠结这了。谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月1日(周五) 下午4:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] RT-DETR训练 (Issue #8734)




 
这很正常吧  收敛趋势不一样
