### ISSUE TITLE
关于N卡环境与昆仑显卡环境模型适配性的问题。

### ISSUE THREAD

**Issue by wj920291253** [PaddlePaddle/PaddleDetection#8740]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

N卡训练模型在昆仑显卡环境中是否可以直接使用？不能的话，有没有模型格式转换脚本？

**Comment by QAQTATQAQTAT** [comment]
试过在N卡下训练过旋转框的s2anet，可以直接在昆仑R200环境下调用
