### ISSUE TITLE
请问paddledetection的模型可以部署到Apollo中吗？有没有相关教程？

### ISSUE THREAD

**Issue by rwb1123** [PaddlePaddle/PaddleDetection#8741]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问paddledetection的模型可以部署到Apollo中吗？有没有相关教程？

**Comment by LokeZhou** [comment]
可以参考这里面的：https://github.com/PaddlePaddle/Paddle3D
