### ISSUE TITLE
编译paddledetection 出现错误

### ISSUE THREAD

**Issue by ZZZZZZHE** [PaddlePaddle/PaddleDetection#8743]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://github.com/PaddlePaddle/PaddleDetection/assets/34742752/f0fb40e9-e5bc-43a3-90df-38b108d1fa8d)

cmake generate后 编译main 工程出现这个copyfile错误
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/34742752/b3602986-9826-4b3e-b30c-6cc9dc6d8c08)
不知道怎么引起的，求求解答

**Comment by ZZZZZZHE** [comment]
有没有大佬 求解答

**Comment by LokeZhou** [comment]
看着像paddleinference的问题，可以参照这里下载相应的库https://www.paddlepaddle.org.cn/inference/master/guides/install/download_lib.html#windows
