### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by EwardJohn** [PaddlePaddle/PaddleDetection#875]
使用两张Tesla v100 32G显存，进行模型裁剪时出现错误Segmentation fault (core dumped)，使用的裁剪命令为：
python slim/prune/prune.py \
-c ./configs/yolov3_mobilenet_v1_voc.yml \
--pruned_params "yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights" \
--pruned_ratios="0.2,0.3,0.4"

出错的日志如下：
![image](https://user-images.githubusercontent.com/63114159/83775336-63198980-a6b9-11ea-9066-bd4313b845b8.png)
![image](https://user-images.githubusercontent.com/63114159/83775370-6c0a5b00-a6b9-11ea-8062-0e657c7fbde2.png)
![image](https://user-images.githubusercontent.com/63114159/83775408-76c4f000-a6b9-11ea-8955-44ff5fbb38d7.png)
![image](https://user-images.githubusercontent.com/63114159/83775621-bee41280-a6b9-11ea-87df-72dd2bd376dd.png)

请问问题出现在哪？谢谢

**Comment by heavengate** [comment]
看报错信息像是nccl没有正确安装或者版本不匹配，可以试下设置单卡的话能跑，如果设置单卡能跑应该就是nccl的问题，可以重新安装正确版本的nccl试下
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/index_cn.html

**Comment by EwardJohn** [comment]
Thanks ,single GPU  run well.

**Comment by qingqing01** [comment]
@EwardJohn 报错信息的最后确实出现了ncclxx。 你2张v100，是 `export CUDA_VISIBLE_DEVICES=0`设置单卡训练吗？

**Comment by EwardJohn** [comment]
@qingqing01 是的，我没设置卡数量的时候就出了上面的错误，设置成单卡的时候没有出错

**Comment by qingqing01** [comment]
@EwardJohn 如果没设置卡数出错，默认会用全部的卡，那就是因为NCCL安装的问题，看下nccl的版本是多少？ 也可以设置 ` export NCCL_P2P_DISABLE=1` 看下2个卡是否出错，但设置这个会使得速度变慢。

**Comment by EwardJohn** [comment]
@qingqing01  我不知道NCCL的版本在哪查看，我使用的是镜像，使用的是CUDA-10.0和cudnn-7.5，昨天卡0，卡1运行程序都没有错，我使用的paddledetection是1.8.1版本，这个版本需要NCCL2的哪个版本的？

**Comment by qingqing01** [comment]
@EwardJohn  NCCL版本>=nccl_2.1.4都可以吧。

**Comment by EwardJohn** [comment]
好的，谢谢！
