### ISSUE TITLE
我再测试rtdetr时发现 我在windows10环境下 使用voc数据集进行训练时 训练到1epoch会异常停止。python程序会终止，我这个实在aistudio上进行验证过的 是没有任何问题的代码 是不是对于windows下有bug呢

### ISSUE THREAD

**Issue by op-newman** [PaddlePaddle/PaddleDetection#8754]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我再测试rtdetr时发现 我在windows10环境下 使用voc数据集进行训练时 训练到1epoch会异常停止。python程序会终止，我这个实在aistudio上进行验证过的 是没有任何问题的代码 是不是对于windows下有bug呢

**Comment by lyuwenyu** [comment]
paddle版本是多少 rtdetr建议使用paddle-2.4.2
