### ISSUE TITLE
静态图问题

### ISSUE THREAD

**Issue by l1uj1awe103** [PaddlePaddle/PaddleDetection#8755]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

对于一个元素不固定的list，如何定义paddle.static.InputSpec？类似rtdetr的gt_class、gt_bbox?
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/52949650/c2adbe1c-e778-49a6-a160-398ccd6134c8)

**Comment by lyuwenyu** [comment]
可以参考engine/trainer里的写法 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/ppdet/engine/trainer.py#L1209
