### ISSUE TITLE
导出为onnx模型时候报错

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/PaddleDetection#8756]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

报错信息如下: 
```
ValueError: (InvalidArgument) The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [1, 68, 20, 20], X's size = 27200, 'shape' is [-1, 4, 17, 1600], known capacity of 'shape' is -108800.
  [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:0 != -in_size:-27200.] (at ../paddle/fluid/operators/[reshape_op.cc:204](http://reshape_op.cc:204/))
  [operator < reshape2 > error]
```
  
  我使用`python/infer.py`导出paddle的模型后可以正常推理，但我想试试导出ppyoloe_plus_crn_x_80e_coco的ONNX模型，导出指令如下,报错信息在上面:
  `
%cd ~/work/PaddleDetection/deploy/
!python end2end_ppyoloe/end2end.py \
    --model-dir inference_model/paddle_model/ppyoloe_plus_crn_x_80e_coco/ \
    --save-file inference_model/onnx_model/ppyoloe_plus_crn_x_80e_coco.onnx \
    --opset 11 \
    --batch-size 1 \
    --topk-all 10 \
    --iou-thres 0.6 \
    --conf-thres 0.4
`
 
  

### 复现环境 Environment

paddle: 2.5.2
paddledetection：v2.7
CUDA:12.2
ubuntu: 2204
python: 3.10

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Wei-JL** [comment]
抱歉我知道错哪了，这个问题解决了，我的模型输入是1280*1280，我把指令改为如下：
   %cd ~/work/PaddleDetection/deploy/
   !python end2end_ppyoloe/end2end.py \
    --model-dir inference_model/paddle_model/ppyoloe_plus_crn_x_80e_coco/ \
    --save-file inference_model/onnx_model/ppyoloe_plus_crn_x_80e_coco.onnx \
    --opset 11 \
    --batch-size 1 \
    --img-size 1280 1280 \
    --topk-all 10 \
    --iou-thres 0.6 \
    --conf-thres 0.4
    
 但又出现新的错误了，我先自己找找解决方案

**Comment by Wei-JL** [comment]
最新的报错信息为: 

I1215 17:06:11.166870 2837585 [interpretercore.cc:237](http://interpretercore.cc:237/)] New Executor is Running.
2023-12-15 17:06:19 [INFO]        ONNX model saved in inference_model/onnx_model/ppyoloe_plus_crn_x_80e_coco.onnx
Traceback (most recent call last):
  File "/home/ai/work/PaddleDetection/deploy/end2end_ppyoloe/end2end.py", line 97, in <module>
    main(opt)
  File "/home/ai/work/PaddleDetection/deploy/end2end_ppyoloe/end2end.py", line 39, in main
    if node.op == 'Concat' and node.o().op == 'Reshape' and node.o().o().op == 'ReduceSum':
  File "/home/ai/anaconda3/envs/torch_paddle/lib/python3.10/site-packages/onnx_graphsurgeon/ir/node.py", line 92, in o
    return self.outputs[tensor_idx].outputs[consumer_idx]
IndexError: list index out of range

以下是调试过程，环境跟上面是一样的。

**Comment by Wei-JL** [comment]
![20231215-171807](https://github.com/PaddlePaddle/PaddleDetection/assets/71386288/2e4c0a37-3fa0-4a50-aa28-9c053b34eed8)

**Comment by mengoat** [comment]
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/33283385/81cc614f-81c2-47f2-8639-90b5fe88f338)
问题点应该在这里，这里的concat14 悬空了，只有一个孩子节点，没有孙子节点。所以node.o().o() 会报错

**Comment by Wei-JL** [comment]
> ![image](https://private-user-images.githubusercontent.com/33283385/290979508-81cc614f-81c2-47f2-8639-90b5fe88f338.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTgxMDYsIm5iZiI6MTcwMjcxNzgwNiwicGF0aCI6Ii8zMzI4MzM4NS8yOTA5Nzk1MDgtODFjYzYxNGYtODFjMi00N2YyLTg2MzktOTBiNWZlODhmMzM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA5MTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYTEzODdlYTU1YTkyODkzZGY3NWYwYTk0Mjk2OGFiOTRhZDQzOTE1ZTY1YmNkNzU4OWY4NGQ0MjkxYjdiMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pdIYvp1RHxVkw9EQnHc_JW3ii0h3KHYp6dZuuEXhGms) 问题点应该在这里，这里的concat14 悬空了，只有一个孩子节点，没有孙子节点。所以node.o().o() 会报错

您好，请问怎么解决呢，把后面使用了`node.o()`全删了？， 我最开始也有这个想法，但我不知道会不会导致转onnx失败或者降低很多准确度

**Comment by Wei-JL** [comment]
`python end2end_ppyoloe/end2end.py --model-dir inference_model/paddle_model/ppyoloe_plus_crn_x_80e_coco/ --save-file inference_model/onnx_model/ppyoloe_plus_crn_x_80e_coco.onnx --opset 11 --batch-size 1 --topk-all 10 --img-size 1280 1280 --iou-thres 0.6 --conf-thres 0.4 ` 

_I1220 15:44:13.067536 172148 [interpretercore.cc:237](http://interpretercore.cc:237/)] New Executor is Running.
2023-12-20 15:44:21 [INFO]	ONNX model saved in inference_model/onnx_model/ppyoloe_plus_crn_x_80e_coco.onnx
Simplifier failure: [ShapeInferenceError] (op_type:Gather, node name: Gather_12): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 0: (1) vs (-1)
Traceback (most recent call last):
  File "/home/ai/work/deploy_birdNest/end2end_ppyoloe/end2end.py", line 97, in <module>
    main(opt)
  File "/home/ai/work/deploy_birdNest/end2end_ppyoloe/end2end.py", line 42, in main
    assert mul.outputs[0].shape[1] == concat.outputs[0].shape[2], 'Something wrong in outputs shape'
TypeError: 'NoneType' object is not subscriptable_

**Comment by Wei-JL** [comment]
现在报错变了，成这样了，请问如何解决呢

**Comment by laugh12321** [comment]
我这边修复了，可以试试[TensorRT-YOLO](https://github.com/laugh12321/TensorRT-YOLO)。支持PP-YOLOE、PP-YOLOE+添加EfficientNMS插件导出ONNX模型和TensorRT模型，且batch-size可以大于1。

**Comment by Wei-JL** [comment]
> 我这边修复了，可以试试[TensorRT-YOLO](https://github.com/laugh12321/TensorRT-YOLO)。支持PP-YOLOE、PP-YOLOE+添加EfficientNMS插件导出ONNX模型和TensorRT模型，且batch-size可以大于1。

您好，请问是您给的这个GitHub链接吗？ 直接复制进项目既可？

**Comment by laugh12321** [comment]
是这个链接，不用复制进PaddleDetection项目。只需要把使用`python tools/export_model.py`导出的PP-YOLOE、PP-YOLOE+按照说明执行`python python/export/ppyoloe/export.py`即可。

**Comment by Wei-JL** [comment]
> 是这个链接，不用复制进PaddleDetection项目。只需要把使用`python tools/export_model.py`导出的PP-YOLOE、PP-YOLOE+按照说明执行`python python/export/ppyoloe/export.py`即可。

非常感谢，我试试

**Comment by LokeZhou** [comment]
当前先关闭此iussues,如后续还有问题，可reopen或重提
