### ISSUE TITLE
同一时间只能训练一个模型

### ISSUE THREAD

**Issue by wj920291253** [PaddlePaddle/PaddleDetection#8758]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在单机多卡环境里，同一时间只能训练一个模型；就算处在不同容器内，使用不同显卡，跑第二个模型的时候，第一个模型的训练会卡住，第二个模型也会卡住。

**Comment by lyuwenyu** [comment]
理论上不会啊   具体那个模型 paddle/paddledet的版本是啥

**Comment by shangshanruowo** [comment]
我单卡都可以跑多个模型同时训练，只要显存和内存够感觉就可以，你可以看看你跑的时候内存显卡的占用情况
