### ISSUE TITLE
缺乏摄像头demo

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/PaddleDetection#876]
现有两个infer.py都是基于图像或者视频的，希望能添加摄像头的支持

**Comment by heavengate** [comment]
好的，我们评估一下看看摄像头数据infer的支持~

**Comment by liu824** [comment]
我也希望有摄像头的demo,自己写一个太麻烦了

**Comment by Channingss** [comment]
这一行改为 cv2.VideoCapture(0)
https://github.com/PaddlePaddle/PaddleDetection/blob/d59c29935d04b2f7b74cf34cc504111deb741438/deploy/python/infer.py#L557

**Comment by liu824** [comment]
我按照你给的方法改了程序，但还是无法使用摄像头，但也不报错。
以下是我在Spyder中的console中的代码和结果：
!python deploy/python/infer.py --model_dir inference_model/yolov4_cspdarknet_voc --use_gpu True
-----------  Running Arguments -----------
image_file: 
model_dir: inference_model/yolov4_cspdarknet_voc
output_dir: output
run_benchmark: False
run_mode: fluid
threshold: 0.5
use_gpu: True
video_file: 
------------------------------------------

**Comment by liu824** [comment]
我已经成功处理好了，后面需要加一些东西

**Comment by qingqing01** [comment]
@imistyrain  @liu824  摄影头预测可以跟进 https://github.com/PaddlePaddle/PaddleDetection/pull/1003/files

**Comment by liu824** [comment]
谢谢，我自己写了一个摄像头的demo
