### ISSUE TITLE
semi_det支持除fcos和ppyoloe+以外的模型吗？

### ISSUE THREAD

**Issue by LorenzoSun-V** [PaddlePaddle/PaddleDetection#8761]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

semi_det里的denseteacher支持yolov5-v8和其他检测器进行半监督训练吗？
另外部署的话是否只需按照基础的检测器导出ONNX，就能使用FastDeploy部署？

**Comment by lyuwenyu** [comment]
目前还没有适配其他模型。可以用FastDeploy部署

**Comment by LorenzoSun-V** [comment]
好的感谢
