### ISSUE TITLE
打印log事宜

### ISSUE THREAD

**Issue by sdreamforchen** [PaddlePaddle/PaddleDetection#8767]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请教一下，由于连续多次训练RT-DETR，修改了backbone之类（已经知道怎么打印log了）的，以及超参数。有时候记录来不及，容易搞混：
怎么打印优化器参数、class_loss权重等超参数呢？

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/tools/train.py#L205

run之前的cfg可以打印一下
