### ISSUE TITLE
tools/slice_image.py 不能生成切割图，jason文件正确生成

### ISSUE THREAD

**Issue by virtual8888** [PaddlePaddle/PaddleDetection#8768]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Other

### Bug描述 Describe the Bug

如题，生成的切割图片只有名字，大小是0Bytes， jason文件是正确生成。

### 复现环境 Environment

-AI Studio里的项目 “基于PP-YOLOE-SOD的无人机航拍图像检测案例全流程实操”
!python tools/slice_image.py --image_dir /home/aistudio/work/demo/input_im --json_path /home/aistudio/work/demo/input_im/demo.json --output_dir /home/aistudio/work/demo/sliced --slice_size 640 --overlap_ratio 0.25
生成的切割图片只有名字，大小是0Bytes。 在本地电脑也是不能生成切割图片。

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by David-dotcom666** [comment]
我也遇到这个问题，请问你有解吗

**Comment by David-dotcom666** [comment]
我也遇到这个问题，请问你有解吗
@virtual8888

**Comment by David-dotcom666** [comment]
@virtual8888
我暂时把sahi源码改了下保存图
Lib\site-packages\sahi下的slicing中的
image_pil.save(slice_file_path, quality="keep")
参数,quality="keep"去掉后可以保存图片

**Comment by virtual8888** [comment]
@David-dotcom666 是的，我也是改了SAHI的源码，去掉了参数quality="keep"，不知会不会有影响子图质量，毕竟作者是想子图像将使用与原始图像相同的量化表和二次采样保存的。

**Comment by virtual8888** [comment]
@David-dotcom666 是的，我也是改了SAHI的源码，去掉了参数quality="keep"，不知会不会有影响子图质量，毕竟作者是想子图像将使用与原始图像相同的量化表和二次采样保存的。

**Comment by haoaZ** [comment]
您好在Aistudio上的官方项目能改sahi代码吗，我没有找到Lib\site-packages\sahi
