### ISSUE TITLE
保存训练过程的中间日志信息

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/PaddleDetection#877]
我们需要进行很多轮的对比实验，每轮都要改动很多的参数，需要保存下这些过程中重要的日志信息
看依赖里已经有了tqdm，可以使用其以滚动条的形式显示epoch的信息，并将每个epoch后的loss和评估的map等信息记录在日志文件中

**Comment by heavengate** [comment]
您好，当前PaddleDetection里没有显式的epoch概念，是基于`snapshot_iter`进行保存和评估的，只要在训练的时候加上`--eval`参数即可每隔`snapshot_iter`次iteration进行一次评估，评估结果会记录在日志中的

**Comment by sidney-zb** [comment]
您好，请问每一轮训练的结果日志存储在哪个路径中呢
