### ISSUE TITLE
picodet-m-320模型，用NCNN和Paddle分别预测相同图像，预测结果存在差异。

### ISSUE THREAD

**Issue by czyczyczy** [PaddlePaddle/PaddleDetection#8772]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

预测数据总共92张，其中有两张NCNN框架推断正确，Paddle推断错误；有三张NCNN推断错误，Paddle推断正确；
并且某些图片推断结果，置信度差异较大。
ncnn用的官方的demo测试，paddle使用的tools/infer.py。

**Comment by lyuwenyu** [comment]
ncnn怎么用的 导致paddle模型到onnx嘛？

**Comment by czyczyczy** [comment]
是的，paddle导出到onnx，onnx转ncnn

**Comment by czyczyczy** [comment]
> ncnn怎么用的 导致paddle模型到onnx嘛？

是的，paddle转onnx，onnx转ncnn

**Comment by LokeZhou** [comment]
可以先验证paddle转onnx后输出是否有差异
