### ISSUE TITLE
Slow download

### ISSUE THREAD

**Issue by Qengineering** [PaddlePaddle/PaddleDetection#8776]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

Downloading any *.pdparams file from https:://paddledet.bj.bcebos.com is so slow. About 33 KB/sec.
I'm located in the Netherlands

### 复现环境 Environment

Linux
Python 3.11
PaddlePaddle 2.6.0
PaddleDetection 2.7

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [x] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
try to change  the proxy

**Comment by Qengineering** [comment]
Such as??

**Comment by LokeZhou** [comment]
It depends on your environment and what agents you can connect to
