### ISSUE TITLE
机械硬盘加载数据耗时很长，调试过程很慢

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/PaddleDetection#878]
构造了一个仅有10个样本的数据用于调试，但是其到达第一个iter的时间长达数分钟，严重影响调试效率，加载真值部分很快，但是映射到共享内存很慢，能查下原因吗？

**Comment by heavengate** [comment]
如果只有10个样本，数据加载时间应该不会很慢的，如果你是启动慢，可能有两个原因
1. PaddleDetection目前是基于静态图实现的，静态图启动需要对网络进行编译，编译过程需要耗时，启动过程中的耗时应该主要是网络启动的耗时，数据耗时相对较少
2. 可以确认一下是否数据预处理比较复杂，如果你是调试的时候想快一点，可以减少数据的预处理，或者把`use_process`设置`False`减少进程启动时间试下
