### ISSUE TITLE
求问是否有objects365的 模型可以用的

### ISSUE THREAD

**Issue by lixinye666** [PaddlePaddle/PaddleDetection#8782]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

先要问一下有没有用objects365模型训练的

**Comment by lyuwenyu** [comment]
具体那个模型的obj365模型  目前只有部分模型有 参考相应的config里的readme
