### ISSUE TITLE
能不能在自动压缩工具中添加对旋转目标检测的支持，我使用自动压缩工具时它提升只支持VOC，COCO格式的进行训练，但旋转目标检测RRBOX的

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleDetection#8787]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1.目前我使用ppyoloe-r的旋转目标检测，但发现自动压缩工具对这个不支持，只支持COCO.VOC的目标检测，对RBOX的是不支持的，目前旋转检测也有大部分人使用，官方是否支持一下这个，不要对模型厚此薄彼嘛。
2. 自动压缩在部署时能够提升速度保证精度

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
暂时还不支持，会评估下需求的
