### ISSUE TITLE
PP-YOLOE-SOD

### ISSUE THREAD

**Issue by 15689933561** [PaddlePaddle/PaddleDetection#8788]
### 问题描述 Please describe your issue

为什么yoloe-sod在金字塔最顶层加位置编码和encoder有助于小目标检测呢，我理解的金字塔高层包含的都是大目标的特征信息啊，可视化小目标几乎没有鸭

**Comment by lyuwenyu** [comment]
是为了encode不同物体间的关系去辅助推理检测，
