### ISSUE TITLE
python 跨摄像头跟踪

### ISSUE THREAD

**Issue by mxyqsh** [PaddlePaddle/PaddleDetection#8789]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

用导出的模型基于Python去做跨镜头跟踪时，从结果图片以及结果视频中，哪里显示出是哪个ID是跨摄像头的呢

**Comment by lyuwenyu** [comment]
你用的是那个可视化的脚本

**Comment by mxyqsh** [comment]
您好，使用的是deploy/pptracking/python/mot_sde_infer.py  2.5版本

**Comment by LokeZhou** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/deploy/pptracking/python/mot_sde_infer.py#L578 这里是可视化相关代码，可以具体进去看看
