### ISSUE TITLE
PaddleDetection能否导出.pth的权重文件

### ISSUE THREAD

**Issue by wyzh0912** [PaddlePaddle/PaddleDetection#8790]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PaddleDetection导出文件为infer_cfg.yml, model.pdiparams, model.pdiparams.info, model.pdmodel，能否导出成.pth格式的权重文件呢？

**Comment by lyuwenyu** [comment]
不可以的
