### ISSUE TITLE
serving部署，模型导出失败

### ISSUE THREAD

**Issue by yootou** [PaddlePaddle/PaddleDetection#8791]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

RuntimeError: Can't call main_program when full_graph=False. Use paddle.jit.to_static(full_graph=True) instead.

**Comment by lyuwenyu** [comment]
是使用这个`paddle.jit.to_static(full_graph=True)`解决了嘛，用的paddle/paddledet的版本分别是什么？
