### ISSUE TITLE
关于paddledetection使用slim配置的一些问题，包括你们文档是不是有一点错误

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleDetection#8792]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

1、量化问题，我发现https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.7/configs/slim文档上面的量化测试那一块是这样写的
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/101441487/b91384dd-df35-4ffd-a273-37e792b0f4b5)
yolov3_mv1那一块，量化前模型是94.2MB，量化后模型是25.4MB，我理解量化不应该改变模型体积才是，并且我下载你们后面的连接这是你们没量化前的文件大小
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/101441487/fd07a4a6-7360-4488-8686-8931965b3283)
这是后的
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/101441487/7c8f9171-a430-4282-a788-b0d3d425aa27)
_opt_cache文件夹里面是啥也没有，从文件大小看其实量化后好像大一点，所以你们文档上面那个模型大小是指实际加载内存里面的容量吗，还有的一些测速你们是没写，是单纯没有进行测试还是效果不好没写上去？

2、减枝的问题，我使用的其他模型，按照你们的写法也能进行减枝配置训练，但很奇怪我剪出来后导出静态模型，模型文件的大小还变大了，模型文件按道理不应该边小吗，参数文件变大我还能理解，你们的减枝是单纯的把一些通道变成0，没有真正的把那个通道给去除吗?很奇怪，因为导出静态模型用netron看设置减枝的那几层并没有通道变小。我使用的是fgpm减枝策略。
希望能被你们解答一下，谢谢你们。

**Comment by lyuwenyu** [comment]
存储和真正理论上用 不太一样吧， 具体可以在paddleslim提问

**Comment by shangshanruowo** [comment]
> 存储和真正理论上用 不太一样吧， 具体可以在paddleslim提问

奥好的，新年快乐^_^，但还是想问一下我提的第二个问题，因为我减枝出来它为什么模型结构和参数文件都变大了...，是我减枝的问题吗，太奇怪了

**Comment by minghaoBD** [comment]
> > 存储和真正理论上用 不太一样吧， 具体可以在paddleslim提问
> 
> 奥好的，新年快乐^_^，但还是想问一下我提的第二个问题，因为我减枝出来它为什么模型结构和参数文件都变大了...，是我减枝的问题吗，太奇怪了

变大是不符合预期的，建议用netron 可视化pdmodel看下剪裁后的模型结构。

**Comment by minghaoBD** [comment]
您的问题：yolov3_mv1那一块，量化前模型是94.2MB，量化后模型是25.4MB，我理解量化不应该改变模型体积才是，并且我下载你们后面的连接这是你们没量化前的文件大小
回答：这里存储的是fp32数值类型的量化模型，调用paddle Lite的opt工具，可以得到推理部署时的模型体积。模型转换和部署文档如下：
https://www.paddlepaddle.org.cn/lite/v2.12/user_guides/quant_aware.html#paddle-lite
