### ISSUE TITLE
python tools/infer.py        !!!TypeError: object of type 'Variable' has no len()

### ISSUE THREAD

**Issue by lsm140** [PaddlePaddle/PaddleDetection#8793]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

 File "C:\Users\lsm\Desktop\pp\PaddleDetection-2.7\ppdet\modeling\heads\yolo_head.py", line 254, in _generate_anchor_point
    [len(anchor_points[-1]), 1], stride, dtype=self._dtype))
TypeError: object of type 'Variable' has no len()

but in paddle=2.2 and ppdet=2.5.0 is normal

### 复现环境 Environment

windows  pp=2.4.2-gpu  ppdet=2.7 python=3.9 cuda=11.7 cudnn=8.4.1 

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
建议使用最新的paddle试一下

**Comment by lsm140** [comment]
哈哈哈，用的就是最新的paddle2.6.0出的问题，尝试了ppdet2.5/2.6/2.7都出问题，后面paddle-gpu降级到2.5.2了，问题消失发自我的手机-------- 原始邮件 --------发件人： Wenyu ***@***.***>日期： 2024年1月23日周二 11:42收件人： PaddlePaddle/PaddleDetection ***@***.***>抄送： lsm140 ***@***.***>, Author ***@***.***>主    题： Re: [PaddlePaddle/PaddleDetection] python tools/infer.py        !!!TypeError: object of type 'Variable' has no len() (Issue #8793)
建议使用最新的paddle试一下
