### ISSUE TITLE
关于Detection的C++部署

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleDetection#8795]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问一下，Mask-RCNN模型训练的实例分割模型，C++框架支持吗？我用Mask-RCNN模型无法运行 换为PicoDet就可以运行，请问是怎么回事呢？

**Comment by lyuwenyu** [comment]
那应该是不支持的， 可以参考使用fastdeploy仓库

**Comment by wxf764571829** [comment]
> 那应该是不支持的， 可以参考使用fastdeploy仓库

大佬，请教一下我使用paddle中maskrcnn训练出的模型导出后按照fastdeploy服务部署时报这个错误UNAVAILABLE: Invalid argument: unable to load model 'runtime', configuration expects datatype TYPE_FP32 for output 'concat_9.tmp_0', model pr |
|             |         | ovides TYPE_INT32 
这个如何解决 我在config.obtxt中将output下的oncat_9.tmp_0配置修改为TYPE_INT32后就会报以下这个错误Invalid argument: unexpected inference input 'concat_5.tmp_0', allowed inputs are: concat_13.tmp_0, concat_9.tmp_0, tmp_150

**Comment by David-dotcom666** [comment]
@Hold-on-li 应该是可以的，你C++部署的用的是inference原生自己写的，还是fastdepoly，还是ppdet下的CPP示例？
1.如果是inference写的就需要看下你的代码，你可以看下result类中的mask vector是否都是0，如果是的话你可以试下更换inference版本。如果是存在1的话，说明是你自己处理部分的代码有问题。
2.如果是fastdepoly，目前只有fastdepoly1.0.3 - 1.0.7的版本在mask rcnn模型上结果应该是有bug，可以使用1.0.2的
3.如果是ppdet下的CPP,这个跟1差不多，用 https://www.paddlepaddle.org.cn/inference/v2.6/guides/install/download_lib.html#windows这里对应的版本应该就可以。注意不要注释掉mask相关源码，有些你搜索的教程中因为opencv版本的问题导致flag报错，然后让你注释掉了部分代码。报错只需要修改flag从CV_XXX到cv::XXX。

**Comment by Hold-on-li** [comment]
好的，谢谢！------------------------------------------------------------------
***@***.***>
日　期：2024年02月21日 10:55:39
***@***.***>
抄　送：Hold ***@***.***>; ***@***.***>
主　题：Re: [PaddlePaddle/PaddleDetection] 关于Detection的C++部署 (Issue #8795)

@Hold-on-li 应该是可以的，你C++部署的用的是inference原生自己写的，还是fastdepoly，还是ppdet下的CPP示例？
 1.如果是inference写的就需要看下你的代码，你可以看下result类中的mask vector是否都是0，如果是的话你可以试下更换inference版本。如果是存在1的话，说明是你自己处理部分的代码有问题。
 2.如果是fastdepoly，目前只有fastdepoly1.0.3 - 1.0.7的版本在mask rcnn模型上结果应该是有bug，可以使用1.0.2的
 3.如果是ppdet下的CPP,这个跟1差不多，用 https://www.paddlepaddle.org.cn/inference/v2.6/guides/install/download_lib.html#windows这里对应的版本应该就可以。注意不要注释掉mask相关源码，有些你搜索的教程中因为opencv版本的问题导致flag报错，然后让你注释掉了部分代码。报错只需要修改flag从CV_XXX到cv::XXX。

**Comment by LokeZhou** [comment]
如有fastdeploy相关问题，可到fastdeploy仓库下提issues

**Comment by Hold-on-li** [comment]
> @Hold-on-li 应该是可以的，你C++部署的用的是inference原生自己写的，还是fastdepoly，还是ppdet下的CPP示例？ 1.如果是inference写的就需要看下你的代码，你可以看下result类中的mask vector是否都是0，如果是的话你可以试下更换inference版本。如果是存在1的话，说明是你自己处理部分的代码有问题。 2.如果是fastdepoly，目前只有fastdepoly1.0.3 - 1.0.7的版本在mask rcnn模型上结果应该是有bug，可以使用1.0.2的 3.如果是ppdet下的CPP,这个跟1差不多，用 [https://www.paddlepaddle.org.cn/inference/v2.6/guides/install/download_lib.html#windows这里对应的版本应该就可以。注意不要注释掉mask相关源码，有些你搜索的教程中因为opencv版本的问题导致flag报错，然后让你注释掉了部分代码。报错只需要修改flag从CV_XXX到cv::XXX。]

您好，我这边按照您下载的最新Paddle_inference预测maskRCNN还是会报错，模型使用paddleDetection2.6版本训练的 请问是什么原因呢？
