### ISSUE TITLE
使用pphuman检测到人员，如何实时的通知外部应用。

### ISSUE THREAD

**Issue by xcmonline** [PaddlePaddle/PaddleDetection#8797]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用pphuman检测测试图片中的人员，也有对应的输出，但输出局限于图片与日志信息，能调用外部接口或推送渠道消息么，这样能及时通知外部应用，目前只有输出的日志信息与对应的图片信息，如果使用视频是不是会有很多图片，外部应用如何集成pphuman输出的结果呢。

**Comment by lyuwenyu** [comment]
pipeline可以任务是个例子 其他需求需要自己开发，

**Comment by xcmonline** [comment]
好像都是安装，训练的资料，这方面的很少。

**Comment by lyuwenyu** [comment]
嗯这个和具体的业务流程相关了

**Comment by Chenkeyi43** [comment]
我是通过修改 pipline 的脚本内容实现其他业务流程，具体还要看代码
