### ISSUE TITLE
请问命令行中的-o 可修改哪些参数呢？

### ISSUE THREAD

**Issue by David-dotcom666** [PaddlePaddle/PaddleDetection#8799]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

例如：python tools/train.py -c configs/smalldet/ppyoloe_crn_l_80e_sliced_visdrone_640_025.yml -o LearningRate.base_lr=0.000625 --eval 这个LearningRate.base_lr格式是怎么来的？有相关的一些说明吗？谢谢

**Comment by lyuwenyu** [comment]
yml里面所有的参数都可以修改

**Comment by highquanglity** [comment]
@David-dotcom666  do you know the gflops and number of parameters of PPyoloe-SOD-s, tell me please, I cant find it anywhere
