### ISSUE TITLE
使用pp-yoloe-r训练自己的数据集报错

### ISSUE THREAD

**Issue by LeungWaiHo** [PaddlePaddle/PaddleDetection#8802]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

ValueError: (InvalidArgument) Each value of attribute 'shape' is expected to be no less than 0. But recieved: shape[1] = -1607630848; shape = [1, -1607630848, 1].
  [Hint: Expected shape[i] >= 0, but received shape[i]:-1607630848 < 0:0.] (at /paddle/paddle/fluid/operators/fill_constant_op.cc:36)
  [operator < fill_constant > error]
![Snipaste_2024-01-26_14-33-04](https://github.com/PaddlePaddle/PaddleDetection/assets/72845073/7f06ea02-37f2-4f60-b80d-11690fe346f6)

**Comment by lyuwenyu** [comment]
有确认过给的默认数据能跑嘛

**Comment by LeungWaiHo** [comment]
> 有确认过给的默认数据能跑嘛

没有，但是我强制把w和h改成int()之后就没有错误了，我不知道是不是paddle的版本问题

**Comment by LeungWaiHo** [comment]
> 有确认过给的默认数据能跑嘛

我目前的paddlepaddle-gpu==2.3.2，但是如何安装更新版本的paddlepaddle我无法安装ext_op

**Comment by haoaZ** [comment]
@LeungWaiHo兄弟你是改的哪，我也是同样的问题

**Comment by LokeZhou** [comment]
可以更新paddle版本试试，不一定要最新的，2.4，2.5都可以
