### ISSUE TITLE
数据增强

### ISSUE THREAD

**Issue by sdreamforchen** [PaddlePaddle/PaddleDetection#8803]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，pp很少用复杂的数据增强，能否给一个例子，配置文件如何配置mixup，cutmix，mosaic。感谢！

**Comment by lyuwenyu** [comment]
mosaic可以参考paddleyolo
