### ISSUE TITLE
修改picodet的激活函数：将hardswish修改为leaky_relu

### ISSUE THREAD

**Issue by wmy10128** [PaddlePaddle/PaddleDetection#8804]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

将esnet、pico_head、csp_pan以及picodet_s_320_pedestrian.yml的act = “hard_swish”修改为act = "leaky_relu"，联合推理无法检测出bbox，是还需要修改其他的地方嘛？导出并转换为onnx模型如下：
![图片](https://github.com/PaddlePaddle/PaddleDetection/assets/83941240/90bdea1d-5aea-4a87-885f-3517d1c09484)  
![图片](https://github.com/PaddlePaddle/PaddleDetection/assets/83941240/3c203bf2-d191-40f8-9d73-a4be96135129)

### 复现环境 Environment

-OS:Windows
-PaddlePaddle：2.6.0
-PaddleDetection：release-2.7
-python：3.8

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
导出之前的结果呢 正常嘛
