### ISSUE TITLE
教程文档中，快速开始的“三、训练、评估、预测”涉及的config文件可能有问题

### ISSUE THREAD

**Issue by HeShiwen** [PaddlePaddle/PaddleDetection#8805]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Validation, Inference

### Bug描述 Describe the Bug

在参照教程文档进行训练过后，尝试评估以及预测会报错：Model pretrain path `output/yolov3_mobilenet_v1_roadsign/model_final` does not exists. If you don't want to load pretrain model, please delete `pretrain_weights` field in config file.
似乎应进行如下更改：
修改config文件夹中的yolov3_mobilenet_v1_roadsign.yml文件，
weights: output/yolov3_mobilenet_v1_roadsign/model_final改为：
weights: output/best_model/model
修改完成之后无异常。

### 复现环境 Environment

Windows11，paddlepaddle2.4，CUDA11.7

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
辛苦提一个PR
