### ISSUE TITLE
复现ppyoloe+出错

### ISSUE THREAD

**Issue by haoaZ** [PaddlePaddle/PaddleDetection#8808]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

ValueError: (InvalidArgument) The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [989727621], X's size = 989727621, 'shape' is [-1, 4], known capacity of 'shape' is -4.
  [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-989727620 != -in_size:-989727621.] (at /paddle/paddle/fluid/operators/reshape_op.cc:190)
  [operator < reshape2 > error]
  跟着流程走出现这个问题
![图片](https://github.com/PaddlePaddle/PaddleDetection/assets/113076135/a6888670-8507-4de9-87e2-e2fa68e8d3ea)

### 复现环境 Environment

linux
paddlepaddle=2.3.2
paddledetection = 2.7

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
请先使用最新的paddle试下
