### ISSUE TITLE
转化onnx时报错

### ISSUE THREAD

**Issue by skming666** [PaddlePaddle/PaddleDetection#8809]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

ppyoloe转化onnx时报错
root@107491c2bfc6:/workspace/PaddleDetection# paddle2onnx --model_dir inference_model/ppyoloe_plus_crn_s_80e_voc --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file ./onnx/ppyoloe.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: inference_model/ppyoloe_plus_crn_s_80e_voc/model.pdmodel
[Paddle2ONNX] Paramters file path: inference_model/ppyoloe_plus_crn_s_80e_voc/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR] Cannot found attribute beta in op: swish
Aborted (core dumped)

**Comment by lyuwenyu** [comment]
使用的各个套件的版本号可以写一下

**Comment by laugh12321** [comment]
Hello everyone!

I would like to introduce my open-source project - [TensoRT-YOLO](https://github.com/laugh12321/TensorRT-YOLO), a tool for deploying YOLO Series (Support PP-YOLOE and PP-YOLOE+) with Efficient NMS in TensorRT. 

## Key Features

- Supports FLOAT32, FLOAT16 ONNX export, and TensorRT inference
- Supports YOLOv5, YOLOv8, YOLOv9, PP-YOLOE and PP-YOLOE+
- Integrates EfficientNMS TensorRT plugin for accelerated post-processing
- Utilizes CUDA kernel functions to accelerate preprocess
- Supports C++ and Python inference

**Comment by ManikSinghSarmaal** [comment]
> ### 问题确认 Search before asking
> * [x]  我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> 
> ### 请提出你的问题 Please ask your question
> ppyoloe转化onnx时报错 root@107491c2bfc6:/workspace/PaddleDetection# paddle2onnx --model_dir inference_model/ppyoloe_plus_crn_s_80e_voc --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file ./onnx/ppyoloe.onnx [Paddle2ONNX] Start to parse PaddlePaddle model... [Paddle2ONNX] Model file path: inference_model/ppyoloe_plus_crn_s_80e_voc/model.pdmodel [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_plus_crn_s_80e_voc/model.pdiparams [Paddle2ONNX] Start to parsing Paddle model... [ERROR] Cannot found attribute beta in op: swish Aborted (core dumped)

Did you find any solutions to this ?? I am also stuck in the same problem

**Comment by zjykzj** [comment]
> ### 问题确认 Search before asking
> * [x]  我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> 
> ### 请提出你的问题 Please ask your question
> ppyoloe转化onnx时报错 root@107491c2bfc6:/workspace/PaddleDetection# paddle2onnx --model_dir inference_model/ppyoloe_plus_crn_s_80e_voc --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file ./onnx/ppyoloe.onnx [Paddle2ONNX] Start to parse PaddlePaddle model... [Paddle2ONNX] Model file path: inference_model/ppyoloe_plus_crn_s_80e_voc/model.pdmodel [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_plus_crn_s_80e_voc/model.pdiparams [Paddle2ONNX] Start to parsing Paddle model... [ERROR] Cannot found attribute beta in op: swish Aborted (core dumped)

@skming666 @ManikSinghSarmaal  @lyuwenyu same question!

first, export model 

```
λ user-X11DAi-N /workdir/paddle/PaddleDetection python3 tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_400e_coco.yml -o weights=./ppyoloe_crn_s_400e_coco.pdparams --output_dir inference_model
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
[08/22 09:53:20] ppdet.utils.checkpoint INFO: Finish loading model weights: ./ppyoloe_crn_s_400e_coco.pdparams
loading annotations into memory...
Done (t=0.83s)
creating index...
index created!
[08/22 09:53:21] ppdet.engine INFO: Export inference config file to inference_model/ppyoloe_crn_s_400e_coco/infer_cfg.yml
I0822 09:53:25.800313   960 program_interpreter.cc:212] New Executor is Running.
[08/22 09:53:25] ppdet.engine INFO: Export model and saved in inference_model/ppyoloe_crn_s_400e_coco
```

second, paddle2onnx

```
λ user-X11DAi-N /workdir/paddle/PaddleDetection
λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file ppyoloe_crn_s_400e_coco.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
[Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR] Cannot found attribute beta in op: swish
Aborted (core dumped)
λ user-X11DAi-N /workdir/paddle/PaddleDetection
λ user-X11DAi-N /workdir/paddle/PaddleDetection
λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 12 --save_file ppyoloe_crn_s_400e_coco.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
[Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR] Cannot found attribute beta in op: swish
Aborted (core dumped)
λ user-X11DAi-N /workdir/paddle/PaddleDetection
λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 13 --save_file ppyoloe_crn_s_400e_coco.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
[Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR] Cannot found attribute beta in op: swish
Aborted (core dumped)
λ user-X11DAi-N /workdir/paddle/PaddleDetection
λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 15 --save_file ppyoloe_crn_s_400e_coco.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
[Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR] Cannot found attribute beta in op: swish
Aborted (core dumped)
λ user-X11DAi-N /workdir/paddle/PaddleDetection
λ user-X11DAi-N /workdir/paddle/PaddleDetection
λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 18 --save_file ppyoloe_crn_s_400e_coco.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
[Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR] Paddle2ONNX now only support opset version in range of [7, 17].
Aborted (core dumped)
λ user-X11DAi-N /workdir/paddle/PaddleDetection
λ user-X11DAi-N /workdir/paddle/PaddleDetection
λ user-X11DAi-N /workdir/paddle/PaddleDetection
λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 17 --save_file ppyoloe_crn_s_400e_coco.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
[Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR] Cannot found attribute beta in op: swish
Aborted (core dumped)
λ user-X11DAi-N /workdir/paddle/PaddleDetection
```

## Related configuration information

Running in docker `ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle:2.6.2-gpu-cuda11.2-cudnn8.2-trt8.0`

```
λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --version
2025-08-22 09:55:28 [INFO]      paddle2onnx-1.1.0 with python>=3.6, paddlepaddle>=2.0.0

λ user-X11DAi-N /workdir/paddle/PaddleDetection python3
Python 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
paddle.>>>
>>> paddle.__version__
'2.6.2'
>>>
```

**Comment by zjykzj** [comment]
1. https://github.com/PaddlePaddle/Paddle2ONNX/issues/1167
2. https://github.com/PaddlePaddle/Paddle2ONNX/issues/1358
3. https://github.com/PaddlePaddle/Paddle2ONNX/issues/1153

> > ### 问题确认 Search before asking
> > 
> > 
> > * [x]   我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> > ### 请提出你的问题 Please ask your question
> > ppyoloe转化onnx时报错 root@107491c2bfc6:/workspace/PaddleDetection# paddle2onnx --model_dir inference_model/ppyoloe_plus_crn_s_80e_voc --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file ./onnx/ppyoloe.onnx [Paddle2ONNX] Start to parse PaddlePaddle model... [Paddle2ONNX] Model file path: inference_model/ppyoloe_plus_crn_s_80e_voc/model.pdmodel [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_plus_crn_s_80e_voc/model.pdiparams [Paddle2ONNX] Start to parsing Paddle model... [ERROR] Cannot found attribute beta in op: swish Aborted (core dumped)
> 
> [@skming666](https://github.com/skming666) [@ManikSinghSarmaal](https://github.com/ManikSinghSarmaal) [@lyuwenyu](https://github.com/lyuwenyu) same question!
> 
> first, export model
> 
> ```
> λ user-X11DAi-N /workdir/paddle/PaddleDetection python3 tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_400e_coco.yml -o weights=./ppyoloe_crn_s_400e_coco.pdparams --output_dir inference_model
> grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
> Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
> Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
> Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
> Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
> Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
> Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
> [08/22 09:53:20] ppdet.utils.checkpoint INFO: Finish loading model weights: ./ppyoloe_crn_s_400e_coco.pdparams
> loading annotations into memory...
> Done (t=0.83s)
> creating index...
> index created!
> [08/22 09:53:21] ppdet.engine INFO: Export inference config file to inference_model/ppyoloe_crn_s_400e_coco/infer_cfg.yml
> I0822 09:53:25.800313   960 program_interpreter.cc:212] New Executor is Running.
> [08/22 09:53:25] ppdet.engine INFO: Export model and saved in inference_model/ppyoloe_crn_s_400e_coco
> ```
> 
> second, paddle2onnx
> 
> ```
> λ user-X11DAi-N /workdir/paddle/PaddleDetection
> λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file ppyoloe_crn_s_400e_coco.onnx
> [Paddle2ONNX] Start to parse PaddlePaddle model...
> [Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
> [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
> [Paddle2ONNX] Start to parsing Paddle model...
> [ERROR] Cannot found attribute beta in op: swish
> Aborted (core dumped)
> λ user-X11DAi-N /workdir/paddle/PaddleDetection
> λ user-X11DAi-N /workdir/paddle/PaddleDetection
> λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 12 --save_file ppyoloe_crn_s_400e_coco.onnx
> [Paddle2ONNX] Start to parse PaddlePaddle model...
> [Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
> [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
> [Paddle2ONNX] Start to parsing Paddle model...
> [ERROR] Cannot found attribute beta in op: swish
> Aborted (core dumped)
> λ user-X11DAi-N /workdir/paddle/PaddleDetection
> λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 13 --save_file ppyoloe_crn_s_400e_coco.onnx
> [Paddle2ONNX] Start to parse PaddlePaddle model...
> [Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
> [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
> [Paddle2ONNX] Start to parsing Paddle model...
> [ERROR] Cannot found attribute beta in op: swish
> Aborted (core dumped)
> λ user-X11DAi-N /workdir/paddle/PaddleDetection
> λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 15 --save_file ppyoloe_crn_s_400e_coco.onnx
> [Paddle2ONNX] Start to parse PaddlePaddle model...
> [Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
> [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
> [Paddle2ONNX] Start to parsing Paddle model...
> [ERROR] Cannot found attribute beta in op: swish
> Aborted (core dumped)
> λ user-X11DAi-N /workdir/paddle/PaddleDetection
> λ user-X11DAi-N /workdir/paddle/PaddleDetection
> λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 18 --save_file ppyoloe_crn_s_400e_coco.onnx
> [Paddle2ONNX] Start to parse PaddlePaddle model...
> [Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
> [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
> [Paddle2ONNX] Start to parsing Paddle model...
> [ERROR] Paddle2ONNX now only support opset version in range of [7, 17].
> Aborted (core dumped)
> λ user-X11DAi-N /workdir/paddle/PaddleDetection
> λ user-X11DAi-N /workdir/paddle/PaddleDetection
> λ user-X11DAi-N /workdir/paddle/PaddleDetection
> λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 17 --save_file ppyoloe_crn_s_400e_coco.onnx
> [Paddle2ONNX] Start to parse PaddlePaddle model...
> [Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
> [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
> [Paddle2ONNX] Start to parsing Paddle model...
> [ERROR] Cannot found attribute beta in op: swish
> Aborted (core dumped)
> λ user-X11DAi-N /workdir/paddle/PaddleDetection
> ```
> 
> ## Related configuration information
> Running in docker `ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle:2.6.2-gpu-cuda11.2-cudnn8.2-trt8.0`
> 
> ```
> λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --version
> 2025-08-22 09:55:28 [INFO]      paddle2onnx-1.1.0 with python>=3.6, paddlepaddle>=2.0.0
> 
> λ user-X11DAi-N /workdir/paddle/PaddleDetection python3
> Python 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import paddle
> 
> grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
> paddle.>>>
> >>> paddle.__version__
> '2.6.2'
> >>>
> ```

Related questions in Paddle2ONNX

1. https://github.com/PaddlePaddle/Paddle2ONNX/issues/1206
2. https://github.com/PaddlePaddle/Paddle2ONNX/issues/1167
3. https://github.com/PaddlePaddle/Paddle2ONNX/issues/1153

**Comment by ManikSinghSarmaal** [comment]
> 1. [需要将Paddle模型转换为onnx，报错：[ERROR] Cannot found attribute beta in op: swish Paddle2ONNX#1167](https://github.com/PaddlePaddle/Paddle2ONNX/issues/1167)
> 2. [[ERROR] Cannot found attribute beta in op: swish Paddle2ONNX#1358](https://github.com/PaddlePaddle/Paddle2ONNX/issues/1358)
> 3. [转onnx模型报错Cannot found attribute beta in op: swish Paddle2ONNX#1153](https://github.com/PaddlePaddle/Paddle2ONNX/issues/1153)
> 
> > > ### 问题确认 Search before asking
> > > 
> > > 
> > > * [x]    我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.
> > > ### 请提出你的问题 Please ask your question
> > > ppyoloe转化onnx时报错 root@107491c2bfc6:/workspace/PaddleDetection# paddle2onnx --model_dir inference_model/ppyoloe_plus_crn_s_80e_voc --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file ./onnx/ppyoloe.onnx [Paddle2ONNX] Start to parse PaddlePaddle model... [Paddle2ONNX] Model file path: inference_model/ppyoloe_plus_crn_s_80e_voc/model.pdmodel [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_plus_crn_s_80e_voc/model.pdiparams [Paddle2ONNX] Start to parsing Paddle model... [ERROR] Cannot found attribute beta in op: swish Aborted (core dumped)
> > 
> > 
> > [@skming666](https://github.com/skming666) [@ManikSinghSarmaal](https://github.com/ManikSinghSarmaal) [@lyuwenyu](https://github.com/lyuwenyu) same question!
> > first, export model
> > ```
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection python3 tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_400e_coco.yml -o weights=./ppyoloe_crn_s_400e_coco.pdparams --output_dir inference_model
> > grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
> > Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
> > Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
> > Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
> > Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
> > Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
> > Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
> > [08/22 09:53:20] ppdet.utils.checkpoint INFO: Finish loading model weights: ./ppyoloe_crn_s_400e_coco.pdparams
> > loading annotations into memory...
> > Done (t=0.83s)
> > creating index...
> > index created!
> > [08/22 09:53:21] ppdet.engine INFO: Export inference config file to inference_model/ppyoloe_crn_s_400e_coco/infer_cfg.yml
> > I0822 09:53:25.800313   960 program_interpreter.cc:212] New Executor is Running.
> > [08/22 09:53:25] ppdet.engine INFO: Export model and saved in inference_model/ppyoloe_crn_s_400e_coco
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > second, paddle2onnx
> > ```
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file ppyoloe_crn_s_400e_coco.onnx
> > [Paddle2ONNX] Start to parse PaddlePaddle model...
> > [Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
> > [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
> > [Paddle2ONNX] Start to parsing Paddle model...
> > [ERROR] Cannot found attribute beta in op: swish
> > Aborted (core dumped)
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 12 --save_file ppyoloe_crn_s_400e_coco.onnx
> > [Paddle2ONNX] Start to parse PaddlePaddle model...
> > [Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
> > [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
> > [Paddle2ONNX] Start to parsing Paddle model...
> > [ERROR] Cannot found attribute beta in op: swish
> > Aborted (core dumped)
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 13 --save_file ppyoloe_crn_s_400e_coco.onnx
> > [Paddle2ONNX] Start to parse PaddlePaddle model...
> > [Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
> > [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
> > [Paddle2ONNX] Start to parsing Paddle model...
> > [ERROR] Cannot found attribute beta in op: swish
> > Aborted (core dumped)
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 15 --save_file ppyoloe_crn_s_400e_coco.onnx
> > [Paddle2ONNX] Start to parse PaddlePaddle model...
> > [Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
> > [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
> > [Paddle2ONNX] Start to parsing Paddle model...
> > [ERROR] Cannot found attribute beta in op: swish
> > Aborted (core dumped)
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 18 --save_file ppyoloe_crn_s_400e_coco.onnx
> > [Paddle2ONNX] Start to parse PaddlePaddle model...
> > [Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
> > [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
> > [Paddle2ONNX] Start to parsing Paddle model...
> > [ERROR] Paddle2ONNX now only support opset version in range of [7, 17].
> > Aborted (core dumped)
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --model_dir inference_model/ppyoloe_crn_s_400e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 17 --save_file ppyoloe_crn_s_400e_coco.onnx
> > [Paddle2ONNX] Start to parse PaddlePaddle model...
> > [Paddle2ONNX] Model file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdmodel
> > [Paddle2ONNX] Paramters file path: inference_model/ppyoloe_crn_s_400e_coco/model.pdiparams
> > [Paddle2ONNX] Start to parsing Paddle model...
> > [ERROR] Cannot found attribute beta in op: swish
> > Aborted (core dumped)
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Related configuration information
> > Running in docker `ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle:2.6.2-gpu-cuda11.2-cudnn8.2-trt8.0`
> > ```
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection paddle2onnx --version
> > 2025-08-22 09:55:28 [INFO]      paddle2onnx-1.1.0 with python>=3.6, paddlepaddle>=2.0.0
> > 
> > λ user-X11DAi-N /workdir/paddle/PaddleDetection python3
> > Python 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] on linux
> > Type "help", "copyright", "credits" or "license" for more information.
> > >>> import paddle
> > 
> > grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
> > paddle.>>>
> > >>> paddle.__version__
> > '2.6.2'
> > >>>
> > ```
> 
> Related questions in Paddle2ONNX
> 
> 1. [An error while attempting to convert a PaddlePaddle model to ONNX format Paddle2ONNX#1206](https://github.com/PaddlePaddle/Paddle2ONNX/issues/1206)
> 2. [需要将Paddle模型转换为onnx，报错：[ERROR] Cannot found attribute beta in op: swish Paddle2ONNX#1167](https://github.com/PaddlePaddle/Paddle2ONNX/issues/1167)
> 3. [转onnx模型报错Cannot found attribute beta in op: swish Paddle2ONNX#1153](https://github.com/PaddlePaddle/Paddle2ONNX/issues/1153)

You can try the paddlepaddle version=2.4.2 and paddle2onnx=1.0.8 this will work, from paddle2.6 the swish operator has deleted the attribute of beta.
check this - https://blog.csdn.net/qq_37380933/article/details/137624355
you can either upgrade paddlepaddle andd paddle2onnx which checks hasattr('beta') in node for swish and constructs graph accordingly or you can switch back to older versions, this is mainly paddlepaddle and paddle2onnx incompatibilty.
