### ISSUE TITLE
paddle detection 模型c++推理部署output目录为空目录

### ISSUE THREAD

**Issue by MyIslandZHJ** [PaddlePaddle/PaddleDetection#8812]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

paddle detction导出PPYOLOE模型后进行Windows c++推理部署，推理图片生成的output目录为空目录，main.exe运行未报错，确认不是目录没有权限的问题

### 复现环境 Environment

-OS:Windows -PaddleDetection:2.7.0 -PaddlePaddle:2.5.2 -Python:3.8.16 -CUDA:11.3 -CUDNN:8.2.0

### Bug描述确认 Bug description confirmation

- [x] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
debug看下模型输出是不是正确

**Comment by MyIslandZHJ** [comment]
您好，谢谢您的回复，从我debug的结果来看，程序运行到object_detector.cc中ObjectDetector类的Predict函数,执行到for (int i = 0; i < repeats; i++)循环中的predictor_->Run();语句，其后的语句似乎都无法执行了，程序又并未报错，但却获取不到预测结果，个人感觉是predictor_->Run();这个部分导致程序闪退了，但具体原因不明，不知道您有没有遇到过这个问题，有没有什么建议，麻烦请多指教了，谢谢您！

> debug看下模型输出是不是正确

**Comment by David-dotcom666** [comment]
@MyIslandZHJ 我之前也遇到过这个问题，要看下你的paddleinference的版本,基本上是版本的问题。你可以试试从（https://www.paddlepaddle.org.cn/inference/v2.6/guides/install/download_lib.html#windows）
这里来安装,最好不要从其他地址获取，官方有些其他连接的版本可能都不太维护或者版本比较低了。还有就是用的各个版本最好是与官方的预编译版用的一致。

**Comment by LokeZhou** [comment]
可以试试早期版本
