### ISSUE TITLE
使用海光DCU进行预测时，如何指定DCU的device_id目前通过PaddleDetection/deploy/python /infer.py进行推理，目前默认使用0，手动指定device_id 没有效果

### ISSUE THREAD

**Issue by leizhu900516** [PaddlePaddle/PaddleDetection#8813]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如题，DCU暂时不能使用fastdeploy部署

**Comment by lyuwenyu** [comment]
设置DCU的环境变量呢

**Comment by leizhu900516** [comment]
设置环境变量可以
export CUDA_VISIBLE_DEVICES=0
