### ISSUE TITLE
ONNXRuntime部署示例颜色错误

### ISSUE THREAD

**Issue by HeShiwen** [PaddlePaddle/PaddleDetection#8817]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

PaddleDetection\deploy\third_engine\demo_onnxruntime\infer_demo.py进行ONNX推理，得到的图片结果颜色错误。原因是在保存图片之前没有将RGB转为OpenCV默认的颜色格式，应该在174与175行之间添加以下代码：srcimg = cv2.cvtColor(srcimg, cv2.COLOR_RGB2BGR)

### 复现环境 Environment

PaddleDetection2.7

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
感谢反馈，方便提个PR嘛

**Comment by HeShiwen** [comment]
感谢回复，我已经尝试提交一个PR，标题为Update infer_demo.py<https://github.com/PaddlePaddle/PaddleDetection/pull/8820> 。#8820
我是Github新手用户。若此次PR有什么错误，请及时联系我改正。
________________________________
发件人: Wenyu ***@***.***>
发送时间: 2024年2月22日 14:37
收件人: PaddlePaddle/PaddleDetection ***@***.***>
抄送: HeShiwen ***@***.***>; Author ***@***.***>
主题: Re: [PaddlePaddle/PaddleDetection] ONNXRuntime部署示例颜色错误 (Issue #8817)


感谢反馈，方便提个PR嘛

―

**Comment by LokeZhou** [comment]
感谢pr,ci跑过后合入

**Comment by LokeZhou** [comment]
感谢贡献，ci跑过后会合入，后续相关可以在pr界面反馈，当前issue先关闭
