### ISSUE TITLE
我用paddledetection训练我的目标检测数据集，只有第一次训练快，之后训练读取图片什么的特别慢训练速度非常慢。重装后也是第一次快，后面就很慢

### ISSUE THREAD

**Issue by cfsl007** [PaddlePaddle/PaddleDetection#8818]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我用paddledetection训练我的目标检测数据集，只有第一次训练快，之后训练读取图片什么的特别慢训练速度非常慢。重装后也是第一次快，后面就很慢

**Comment by lyuwenyu** [comment]
标准的数据集有同样的问题嘛  比如 `coco`
