### ISSUE TITLE
ValueError: The module TrainDataset is not registered问题求解决

### ISSUE THREAD

**Issue by silas-yy** [PaddlePaddle/PaddleDetection#8825]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

![5ef09175fb50766e27a47d48d1122a0](https://github.com/PaddlePaddle/PaddleDetection/assets/125504659/9ec4d88a-30a8-4bd1-8c1d-367729db9ca9)
一直显示未注册，路径什么的都是正确的，不知道为什么一直显示未注册
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/125504659/24feb474-1cff-47e5-8cb1-14f10ccda03c)

### 复现环境 Environment

windows
cuda12.0
CuDNN Version: 8.9.

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by LokeZhou** [comment]
先验证一下，直接运行官方demo，看看能不能正常跑起来，在这基础上，再改具体路径
