### ISSUE TITLE
'ppdet.data.transform' has no attribute 'CropImage'

### ISSUE THREAD

**Issue by GitHubmalajava** [PaddlePaddle/PaddleDetection#8828]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Other

### Bug描述 Describe the Bug

使用官方文件代码，本地复现基于PP-PicoDet v2 的路面垃圾检测项目时，出现错误

### 复现环境 Environment

Windows，paddlepaddle-gpu = 2.6.0.post120，paddledet =2.6.0，Python=3.8，cudnn=8.9.1

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by LokeZhou** [comment]
该项目要求PaddlePaddle = 2.2.2
