### ISSUE TITLE
ppyoloe转onnx模型问题，onnx-graphsurgeo包无法安装

### ISSUE THREAD

**Issue by yscolc** [PaddlePaddle/PaddleDetection#8829]
### 文档链接&描述 Document Links & Description

https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/end2end_ppyoloe

**Comment by yscolc** [comment]
其中  pip install onnx-graphsurgeon --index-url https://pypi.ngc.nvidia.com
无法使用，英伟达的这个源地址已经封闭了，第三方源地址也没有此包下载

**Comment by jzhang533** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/end2end_ppyoloe

there is a typo in the doc

the correct command might be : `python3 -m pip install onnx_graphsurgeon --index-url https://pypi.ngc.nvidia.com` as described in this page: https://github.com/NVIDIA/TensorRT/tree/main/tools/onnx-graphsurgeon#using-prebuilt-wheels.

please be aware of the slight difference between onnx-graphsurgeon and onnx_graphsurgeon.

**Comment by Aurelius84** [comment]
@jzhang533 Great！ 我提个PR 给Dectection 仓库修复下这个库名的问题

**Comment by laugh12321** [comment]
Hello everyone!

I would like to introduce my open-source project - [TensoRT-YOLO](https://github.com/laugh12321/TensorRT-YOLO), a tool for deploying YOLO Series (Support PP-YOLOE and PP-YOLOE+) with Efficient NMS in TensorRT. 

## Key Features

- Supports FLOAT32, FLOAT16 ONNX export, and TensorRT inference
- Supports YOLOv5, YOLOv8, YOLOv9, PP-YOLOE and PP-YOLOE+
- Integrates EfficientNMS TensorRT plugin for accelerated post-processing
- Utilizes CUDA kernel functions to accelerate preprocess
- Supports C++ and Python inference
