### ISSUE TITLE
parl的问题

### ISSUE THREAD

**Issue by EwardJohn** [PaddlePaddle/PaddleDetection#883]
当我使用下面的命令进行敏感度分析时，我已经按照要求把voc数据集放在指定位置，安装了parl：

```
nohup python sensitive.py \
-c ../../configs/yolov3_mobilenet_v1_voc.yml \
--pruned_params "yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights,yolo_block.0.1.1.conv.weights,yolo_block.0.2.conv.weights,yolo_block.0.tip.conv.weights,yolo_block.1.0.0.conv.weights,yolo_block.1.0.1.conv.weights,yolo_block.1.1.0.conv.weights,yolo_block.1.1.1.conv.weights,yolo_block.1.2.conv.weights,yolo_block.1.tip.conv.weights,yolo_block.2.0.0.conv.weights,yolo_block.2.0.1.conv.weights,yolo_block.2.1.0.conv.weights,yolo_block.2.1.1.conv.weights,yolo_block.2.2.conv.weights,yolo_block.2.tip.conv.weights" \
--sensitivities_file "./demo.data"

```
但是程序还是进行数据集的下载，

![image](https://user-images.githubusercontent.com/63114159/83873668-cc0b0b00-a766-11ea-90dc-2145f9a87d27.png)
上面的问题是parl没有安装，但是我明明已经安装了parl了
![image](https://user-images.githubusercontent.com/63114159/83873768-f957b900-a766-11ea-87d9-d8f09652d629.png)
不知道这个问题怎末解决？谢谢

**Comment by qingqing01** [comment]
@EwardJohn  

你VOC的目录组织如下：

```
voc/
|-- VOCdevkit 
|-- create_list.py
|-- download_voc.py
|-- label_list.txt
|-- test.txt 
`-- trainval.txt 
```

数据集下载不是parl引起的，是TrainReader/EvalReader里配置的数据路径没有找到。

您可到PaddleDetection根目录下运行：

```
python slim/sensitive/sensitive.py -c configs/yolov3_mobilenet_v1_voc.yml -o weights=xx # 省略后续配置 
```

**Comment by EwardJohn** [comment]
嗯，好的，谢谢

**Comment by EwardJohn** [comment]
还有一个问题是，我在运行代码：
python slim/distillation/distill.py \
    -c configs/yolov3_mobilenet_v1_voc.yml \
    -t configs/yolov3_r34_voc.yml \
    --teacher_pretrained /deluious/PaddleDetection/pre_weights/yolov3_r34_voc.tar
时，它报了错误如下：
![image](https://user-images.githubusercontent.com/63114159/83937277-dfb58080-a7fd-11ea-9cfd-96321e974659.png)
请问是什么问题，是因为.tar格式不对吗？

**Comment by qingqing01** [comment]
已在 https://github.com/PaddlePaddle/PaddleDetection/issues/887 回复，故关闭此issue。
