### ISSUE TITLE
印章检测官网文档运行不通

### ISSUE THREAD

**Issue by yubuyuabc** [PaddlePaddle/PaddleDetection#8830]
### 文档链接&描述 Document Links & Description

https://aistudio.baidu.com/projectdetail/4983788
运行不通
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/58143197/c9d39a8f-6d40-43d5-8243-0e42cfdffd80)

**Comment by lyuwenyu** [comment]
<img width="619" alt="image" src="https://github.com/PaddlePaddle/PaddleDetection/assets/17582080/4a168863-503b-428e-a226-df7d2b4fed05">
先检测下你路径对不对吧

**Comment by yubuyuabc** [comment]
> <img alt="image" width="619" src="https://private-user-images.githubusercontent.com/17582080/308406381-4a168863-503b-428e-a226-df7d2b4fed05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTA2MTQsIm5iZiI6MTcwOTExMDMxNCwicGF0aCI6Ii8xNzU4MjA4MC8zMDg0MDYzODEtNGExNjg4NjMtNTAzYi00MjhlLWEyMjYtZGY3ZDJiNGZlZDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA4NTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MmQ4ZTA0NjQzOGM4Y2QzYjRiODZjMTBkYmFlMzJkYjNkNjhmZWI2MzQ4ZTY3NDEzN2NjMjQ5YzczNDIwZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FclxLTMtAbMrULRB_sPLWT9OCCbdz4rFaAiBHfV1wj8"> 先检测下你路径对不对吧

路径是正确的，麻烦检查一下paddledetect版本更新后文档是否可用
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/58143197/ddb8fcb3-fce8-4cba-82c9-e806e4a4445b)

**Comment by LokeZhou** [comment]
该aistudio项目较早，如果最新版本的ppdetection无法运行，建议克隆早些版本的运行，如2.2等。

**Comment by lolocoo** [comment]
真的可以
