### ISSUE TITLE
paddleDetction中的slim不支持对ppyoloe-r进行减枝吗？

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/PaddleDetection#8831]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我和这个issues出现一样的问题
https://github.com/PaddlePaddle/PaddleDetection/issues/7454
我在你们ai平台上paddlepaddle为2.6、paddledetection为2.7、paddleSlim为2.6，安装了所有依赖，对ppyoloe-r采用
python tools/train.py -c configs/{MODEL.yml} --slim_config configs/slim/{SLIM_CONFIG.yml}
方式进行量化和fpgm减枝，发现都有问题，其中减枝的错误和我贴的issues一模一样，请问是不支持旋转框的减枝吗，如果想实现应该如何修改，劳烦回复一下

**Comment by jzhang533** [comment]
cc: @michaelowenliu @terrysha

**Comment by lyuwenyu** [comment]
自定义算子暂不支持
