### ISSUE TITLE
导出的 onnx 模型推理出错

### ISSUE THREAD

**Issue by jrsebastian** [PaddlePaddle/PaddleDetection#8834]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference

### Bug描述 Describe the Bug

我通过 `tools/export_model.py` 成功导出了 `ppyoloe_plus_crn_s_80e_coco` ，并通过 `paddle2onnx` 转成了 `.onnx ` 文件，但是在 infer 的时候报了错。使用的命令和Log如下：
1. export_model(pass)
```python
python tools/export_model.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml -o weights=../ppyoloe_plus_crn_s_80e_coco.pdparams exclude_nms=True use_gpu=false

[02/28 17:58:39] ppdet.utils.checkpoint INFO: Finish loading model weights: ../ppyoloe_plus_crn_s_80e_coco.pdparams
loading annotations into memory...
Done (t=0.53s)
creating index...
index created!
[02/28 17:58:40] ppdet.engine INFO: Export inference config file to output_inference/ppyoloe_plus_crn_s_80e_coco/infer_cfg.yml
[02/28 17:58:42] ppdet.engine INFO: Export model and saved in output_inference/ppyoloe_plus_crn_s_80e_coco
```
2. paddle2onnx(pass)
```python
paddle2onnx --model_dir output_inference/ppyoloe_plus_crn_s_80e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file ppyoloe_plus_crn_s_80e_coco.onnx

[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: output_inference/ppyoloe_plus_crn_s_80e_coco/model.pdmodel
[Paddle2ONNX] Paramters file path: output_inference/ppyoloe_plus_crn_s_80e_coco/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Use opset_version = 11 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
2024-02-28 18:03:16 [INFO]      ===============Make PaddlePaddle Better!================
2024-02-28 18:03:16 [INFO]      A little survey: https://iwenjuan.baidu.com/?code=r8hu2s
```
3. infer(failed)
```python
python deploy/third_engine/onnx/infer.py --infer_cfg output_inference/ppyoloe_plus_crn_s_80e_coco/infer_cfg.yml --onnx_file ../ppyoloe_plus_crn_s_80e_coco.onnx --image_file demo/000000014439.jpg

-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
ONNXRuntime predict:
Traceback (most recent call last):
  File "/data/shijiarong/workspace/ppyoloe/PaddleDetection/deploy/third_engine/onnx/infer.py", line 148, in <module>
    predict_image(infer_config, predictor, img_list)
  File "/data/shijiarong/workspace/ppyoloe/PaddleDetection/deploy/third_engine/onnx/infer.py", line 134, in predict_image
    if bbox[0] > -1 and bbox[1] > infer_config.draw_threshold:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

请问是什么问题呀？

### 复现环境 Environment

- PaddleDetection release/2.7
- onnxruntime 1.11.1
- paddlepaddle 2.4.0rc0
- paddle2onnx 1.1.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by jrsebastian** [comment]
模型权重下载来自：`https://paddledet.bj.bcebos.com/models/ppyoloe_plus_crn_s_80e_coco.pdparams`
尝试在导出时增加了`TestReader.inputs_def.image_shape=[3,640,640]`，infer 时仍然报同样的错误

**Comment by jrsebastian** [comment]
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/34502782/86f1ec88-120b-4b01-97c9-4b531e1a3113)
仔细 debug 了下这里，确实是有点问题，`bbox` 是 一个 `shape = (8400, 4)` 的 array，这里直接和 int 比较得到的也是 array，所以这里的用法有问题，如果是想要全为 true，应该用 all()，如果有一个为 true 就行，应该用 any()，这里判断的逻辑是什么呢？另外下面 `int(bbox[0])` 的用法也有问题 `bbox[0].shape=（4,)`，还是说这里得到的 bboxes 的 shape 是不符合预期的？请问正确的应该是什么？

**Comment by laugh12321** [comment]
Hello everyone!

I would like to introduce my open-source project - [TensoRT-YOLO](https://github.com/laugh12321/TensorRT-YOLO), a tool for deploying YOLO Series (Support PP-YOLOE and PP-YOLOE+) with Efficient NMS in TensorRT. 

## Key Features

- Supports FLOAT32, FLOAT16 ONNX export, and TensorRT inference
- Supports YOLOv5, YOLOv8, YOLOv9, PP-YOLOE and PP-YOLOE+
- Integrates EfficientNMS TensorRT plugin for accelerated post-processing
- Utilizes CUDA kernel functions to accelerate preprocess
- Supports C++ and Python inference
