### ISSUE TITLE
在利用paddledetection2.7训练rtdetr  res50的时候，显存随着迭代次数不断地增加，直到显存爆掉

### ISSUE THREAD

**Issue by nothingws** [PaddlePaddle/PaddleDetection#8836]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在利用paddledetection2.7训练rtdetr res50的时候，显存随着迭代次数不断地增加，直到显存爆掉

**Comment by zhiboniu** [comment]
请问是自定义的代码还是直接clone的代码库，有没有可能有些显存没有释放

**Comment by nothingws** [comment]
> 请问是自定义的代码还是直接clone的代码库，有没有可能有些显存没有释放
直接用代码库跑的，用的自己的数据集，有的图片中目标标签很多，我发现把标签很多的图片删除训练后，显存明显没了不断增加的现象，请问是什么原因呢

**Comment by zhiboniu** [comment]
看下标签数据是每次重新创建的还是覆盖共用的，应该还是有预期之外的显存使用
