### ISSUE TITLE
RT-DETR的量化、剪枝需求

### ISSUE THREAD

**Issue by bittergourd1224** [PaddlePaddle/PaddleDetection#8839]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

请问目前是否支持RT-DETR模型的量化、剪枝等模型压缩处理？
如果支持，能否帮忙添一份加示例的config文件？
比如对于ppyolo的剪枝配置文件 configs/slim/prune/ppyolo_r50vd_prune_fpgm.yml，应该如何修改，才能使得对于RT-DETR模型是有效的？
谢谢

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
收到 内部会评估一下

**Comment by bittergourd1224** [comment]
> 收到 内部会评估一下

好的感谢，期待新的进展
