### ISSUE TITLE
2.5.0版本的 faster_rcnn 模型进行模型压缩

### ISSUE THREAD

**Issue by CXSforHPU** [PaddlePaddle/PaddleDetection#8842]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

2.5.0版本的 faster_rcnn 模型进行模型压缩

**Comment by lyuwenyu** [comment]
有什么问题嘛
