### ISSUE TITLE
量化感知训练得到的模型如何导出和部署

### ISSUE THREAD

**Issue by wapping** [PaddlePaddle/PaddleDetection#8843]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

根据[PP-PicoDet全量化示例](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/picodet/FULL_QUANTIZATION.md)训练了picodet，执行eval.py评估没问题。
现在想在rknpu上测试，不知道怎么导出模型，能否用fastdeploy部署。

**Comment by lyuwenyu** [comment]
参考下paddlelite这里的文档 https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/develop/object_detection/linux/picodet_detection

理论上可以用fastdeploy的
