### ISSUE TITLE
yolo系列不支持MultiScaleTEST吗，理论上应该都支持的啊，之后会更新yolo的多尺度测试吗

### ISSUE THREAD

**Issue by nosaydomore** [PaddlePaddle/PaddleDetection#885]

**Comment by nosaydomore** [comment]
yolo系列不支持MultiScaleTEST吗，理论上应该都支持的啊，之后会更新过yolo的多尺度测试吗

**Comment by qingqing01** [comment]
@nosaydomore  YOLO暂且不支持多尺度测试。实际业务一般不用多尺度测试吧，一般实在打比赛，为了刷榜才用吧。您想用多尺度测试的目的是？

**Comment by nosaydomore** [comment]
刷榜~~~~(>_<)~~~~
