### ISSUE TITLE
依赖库lap替换

### ISSUE THREAD

**Issue by ltcs11** [PaddlePaddle/PaddleDetection#8858]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; 2. 需求场景（请描述你的项目中为什么需要用此功能）; 3. 功能描述（请简单描述或设计这个功能）

依赖库lap已经暂停更新，目前在高版本python>=3.9情况下pip安装会失败（官方pypi只提供了需setup版本）
可否考虑将lap库替换为lapx，以支持高等级python版本

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/8853 

develop已经更新
