### ISSUE TITLE
cuda12.2运行paddledetection 

### ISSUE THREAD

**Issue by 11075225** [PaddlePaddle/PaddleDetection#8866]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

cuda12.2如何运行paddledetection

**Comment by 11075225** [comment]
训练时加载完预训练模型参数然后就没有继续训练

**Comment by lyuwenyu** [comment]
paddle安装的对嘛 

`paddle.utils.run_check()`

**Comment by 11075225** [comment]
问题已解决，是显卡算力的问题，换了旧版本的paddlepaddle就能正常运行，但是在运行dinoDETR的时候会出现数据报错
