### ISSUE TITLE
rtdetr 如何加入没有标注目标的负样本进行训练？

### ISSUE THREAD

**Issue by mrljwlm** [PaddlePaddle/PaddleDetection#8869]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在dataset的yml里设置了 allow_empty: true
训练的时候提示我那些负样本都是invalid的， 是rtdetr这个网络不支持负样本训练吗
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/23266835/c080b82d-a642-442f-a122-04a7ea317cc1)

**Comment by lyuwenyu** [comment]
是的 目前不支持
