### ISSUE TITLE
求教大神们问题

### ISSUE THREAD

**Issue by 11075225** [PaddlePaddle/PaddleDetection#8873]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

 The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
训练时报错，无法训练

**Comment by lyuwenyu** [comment]
paddle的版本不对   看下你cuda的版本 在官网找相应的
