### ISSUE TITLE
solov2跑了一个月也没跑通啊

### ISSUE THREAD

**Issue by lingdu-xu** [PaddlePaddle/PaddleDetection#8874]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

作为pd的老忠粉，跑个solov2，那还不是手到擒来，结果我完全不知道为什么跑不出结果。环境是没问题的，因为yolox，yolo3等的都能跑，
启动命令：python tools/train.py -c configs/solov2/solov2_r50_fpn_3x_coco.yml --eval
预训练模型直接走默认：Finish loading model weights: C:\Users\Raphael/.cache/paddle/weights\ResNet50_cos_pretrained.pdparams
yml中的那些除了batch_size改成1之外，其他的咱也不改，省得引起问题
coco格式数据集都配了好几版了，有自己写的，怕自己写的不对又从120000的官方数据集拆出来了一千张，每次都是同一个提示：
[03/14 15:28:12] ppdet.engine INFO: Best test mask ap is 0.000.
或者是这个提示：
WARNING: Evaluation results empty, this may be due to training iterations being too few or not loading the correct weights.
我找谁惹谁了啊，，
得，solov2咱跑不起来，那我去跑mask-rcnn吧，得，还是同一个提示啊，不是没有评估结果就是评估结果是000，，到底是为啥啊，，，难道solov2的数据量必须要上万？

**Comment by lyuwenyu** [comment]
跑自己的数据还是coco的数据 一直为0

**Comment by lingdu-xu** [comment]
是的，自己的coco数据集，数据量4k/1k，提示：ppdet.engine INFO: Best test mask ap is 0.000.总是这样，没见过波动。如果训官方数据集，就那个80标签的那个，同样的是4k/1k能见到波动。。关键是我自己的数据集也是正确的，真的，，或者，，我再去找个其他数据集试试？

**Comment by lyuwenyu** [comment]
用coco官方的数据集试一下  不用跑完 跑一两个epoch就行
