### ISSUE TITLE
PaddleDetectionv2.7.0

### ISSUE THREAD

**Issue by Le-soleile** [PaddlePaddle/PaddleDetection#8875]
### Discussed in https://github.com/PaddlePaddle/PaddleDetection/discussions/8678

<div type='discussions-op-text'>

<sup>Originally posted by **shiyutang** October 19, 2023</sup>
## New Projects:
* Added SQR enhancement strategy based on PPDET Deformable DETR. (#8579)
* Added RT-DETR model. (#8094)
* Added semi-supervised detection based on RT-DETR. (#8336)

## New Features:
* Provide Chinese support in draw_bbox. (#8581)
* Support specifying the priority of step and epoch in LinearWarmup. (#8540)
* Compatible with pillow upgrade to 10.0. (#8446)

## BugFix:
* Fixed the problem of video memory usage and slowdown after Paddle supports stride. (#8489)
* Fix import error and modify visualize.py. (#8476)
* Fix v.dtype in ema blacklist. (#8466)
* Fix image_resize_c error reporting problem during inference. (#8460)
* Fixed textbbox error reporting problem in ImageDraw. (#8455)
* Fixed picodet_layout error in Paddle2.5 and added nms_cpu parameter. (#8453)
* Fixed long warning in training. (#8421)
* Fix iou_score error reporting problem and modify ppdet/modeling/losses/detr_loss.py. (#8409)
* Fixed the 0-dimensional problem in solov2. (#8643)
* Fixed distributed parameters to solve the problem of error reporting when running multiple cards on non-GPU device TIPC. (#8635)
* Fixed removal of fluid calls and modified deploy/pipeline/ppvehicle/vehicle_plateutils.py. (#8631)

## Documentations:
* Updated the README_cn.md document and added the Flying Plate AI Kit description. (#8601)
* Add and release RTDETR Obj365 pre-training model document and modify configs/rtdetr/README.md. (#8567)
* Fixed typos in README_en.md document. (#8551)
* Update xpu tipc script. (#8546)
* Added data set alias COCODetDataset. (#8503)
* Add obj365 pre-trained model parameters. (#8500)
* Update npu python version in tipc config. (#8485)
* Adapt and upgrade libmkldnn, modify deploy/cpp/CMakeLists.txt. (#8442)

## Projects：
* 基于PPDET Deformable DETR 新增 SQR增强策略。（#8579）
* 新增RTDeTR模型。（#8094）
* 新增基于rt-detr的半监督检测。（#8336）

## New Features:
* 在draw_bbox中提供中文支持。（#8581）
* 支持在 LinearWarmup 中指定step和epoch的优先级。（#8540）
* 兼容 pillow 升级至10.0。（#8446）

## BugFix:
* 修复Paddle支持stride后，显存占用，运行降速问题。（#8489）
* 修复import错误，修改visualize.py。（#8476）
* 修复ema blacklist中v.dtype。（#8466）
* 修复推理时image_resize_c报错问题。（#8460）
* 修复ImageDraw中的textbbox报错问题。（#8455）
* 修复Paddle2.5中picodet_layout报错，增加nms_cpu参数。（#8453）
* 修复训练出现长警告。（#8421）
* 修复iou_score报错问题，修改ppdet/modeling/losses/detr_loss.py。（#8409）
* 修复solov2中0维问题。（#8643）
* 修复分布式参数以解决非GPU设备TIPC时多卡运行报错的问题。（#8635）
* 修复移除fluid调用，修改deploy/pipeline/ppvehicle/vehicle_plateutils.py。（#8631）

## Documentations:
* 更新README_cn.md文档，加入飞浆AI套件说明。（#8601）
* 添加发布RTDETR Obj365预训练模型文档，修改configs/rtdetr/README.md。（#8567）
* 修正README_en.md文档拼写错误。（#8551）
* 更新xpu tipc脚本。（#8546）
* 增加数据集别名COCODetDataset。（#8503）
* 添加obj365预训练模型参数。（#8500）
* 更新tipc config中npu python版本。（#8485）
* 适配升级libmkldnn，修改deploy/cpp/CMakeLists.txt。（#8442）

## New Contributors
* @veyron95 made their first contribution in https://github.com/PaddlePaddle/PaddleDetection/pull/7746
* @ZhangYulongg made their first contribution in https://github.com/PaddlePaddle/PaddleDetection/pull/7759
* @Zhao-Yian made their first contribution in https://github.com/PaddlePaddle/PaddleDetection/pull/7865
* @DefTruth made their first contribution in https://github.com/PaddlePaddle/PaddleDetection/pull/7950
* @dust8 made their first contribution in https://github.com/PaddlePaddle/PaddleDetection/pull/8005
* @xiaoluomi made their first contribution in https://github.com/PaddlePaddle/PaddleDetection/pull/8211
* @flytocc made their first contribution in https://github.com/PaddlePaddle/PaddleDetection/pull/8066
* @khan-yin made their first contribution in https://github.com/PaddlePaddle/PaddleDetection/pull/8278
* @zhangting2020 made their first contribution in https://github.com/PaddlePaddle/PaddleDetection/pull/8305
* @EmmonsCurse made their first contribution in https://github.com/PaddlePaddle/PaddleDetection/pull/8351
* @nijkah made their first contribution in https://github.com/PaddlePaddle/PaddleDetection/pull/8409
* @Pcjmmc made their first contribution in https://github.com/PaddlePaddle/PaddleDetection/pull/8442
* @livingbody made their first contribution in https://github.com/PaddlePaddle/PaddleDetection/pull/8446
* @shiyutang made their first contribution in https://github.com/PaddlePaddle/PaddleDetection/pull/8455

**Full Changelog**: https://github.com/PaddlePaddle/PaddleDetection/compare/v2.6.0...v2.7.0

<hr /><em>This discussion was created from the release <a href='https://github.com/PaddlePaddle/PaddleDetection/releases/tag/v2.7.0'>PaddleDetectionv2.7.0</a>.</em></div>

**Comment by Le-soleile** [comment]
![KQG9JR0B)_~0N4VARZZ51BG](https://github.com/PaddlePaddle/PaddleDetection/assets/156195357/69c94319-4a6e-421a-8e35-4b46629db888)
![IRTBP0CWHGV53 T~Z3)`ANX](https://github.com/PaddlePaddle/PaddleDetection/assets/156195357/cddb57ee-effe-4f73-a937-10531d8eff0b)
paddle多卡训练，出现这样的问题具体怎么解决呀

**Comment by lyuwenyu** [comment]
<img width="300" alt="image" src="https://github.com/PaddlePaddle/PaddleDetection/assets/17582080/5b402b4f-3289-4dc3-a90a-14d98e635e24">

去看下详细的log
