### ISSUE TITLE
resolution of pretrained FCOSR 

### ISSUE THREAD

**Issue by GeLeinjust** [PaddlePaddle/PaddleDetection#8877]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

 I want to know the resolution of pretrained FCOSR, 640 or 1024 or others? 
Thanks in advance.

**Comment by lyuwenyu** [comment]
> 1024

this
