### ISSUE TITLE
训练自己数据集的问题

### ISSUE THREAD

**Issue by 11075225** [PaddlePaddle/PaddleDetection#8882]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

不使用预训练权重训练自己的数据集能否训练，如何在训练时不加载预训练权重

**Comment by lyuwenyu** [comment]
在config里注释掉 `pretrain: xxx`
