### ISSUE TITLE
pp-vehicle测试实时视频流报错VOL Header truncated是什么问题呢，如何解决呢

### ISSUE THREAD

**Issue by uniquecdmx** [PaddlePaddle/PaddleDetection#8885]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

pp-vehicle测试实时视频流报错VOL Header truncated是什么问题呢，如何解决呢
![img_v3_0295_5b347db0-8e67-41d3-9560-31ac518a739g](https://github.com/PaddlePaddle/PaddleDetection/assets/40234724/331059e7-f370-48cc-a775-c71ba3e1bea8)

环境：window11、nvidia 3060 laptop GPU
CUDA 12.0  paddlepaddle 2.6.0.post120  python 3.8.1

**Comment by lyuwenyu** [comment]
检测下视频源本身是否正确

**Comment by uniquecdmx** [comment]
![img_v3_0295_5ac334e7-2891-4bb9-be10-e74d5cb590cg](https://github.com/PaddlePaddle/PaddleDetection/assets/40234724/51e4e0d6-ae61-4856-82fd-bf6439f0b346)
测试推流会报如下错误

**Comment by uniquecdmx** [comment]
> 检测下视频源本身是否正确

请问如何检查呢  用vlc播放器也播放不了 显示无法打开MRL 详情请检查日志，和FFmpeg有关系吗 推流也会报错，都指向了头文件的问题

**Comment by lyuwenyu** [comment]
> 用vlc播放器也播放不了

应该是数据源有问题   不是ppdet导致的问题   建议使用搜索引擎查相关问题

**Comment by uniquecdmx** [comment]
> > 用vlc播放器也播放不了
> 
> 应该是数据源有问题 不是ppdet导致的问题 建议使用搜索引擎查相关问题

嗯嗯  我再排查下数据流  您知道推流的报错原因吗，这个和实时流没关系，我用本地的mp4文件去做的推流，提示也是无法写入头文件这种

**Comment by uniquecdmx** [comment]
确实是视频流本身问题，海康卫视实时流获取rtsp时缺少某个参数传参导致此情况
