### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by gzxy0102** [PaddlePaddle/PaddleDetection#8888]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

github release已经2.7了 pypi得还在2.6版本 能不能更新一下pypi的版本

**Comment by lyuwenyu** [comment]
可以，但是建议下载源码安装（会有不定期的bug修复
