### ISSUE TITLE
尝试自己实现data模块的loader，请问loader返回的dict里的字段，是写死的吗

### ISSUE THREAD

**Issue by FibonacciSun** [PaddlePaddle/PaddleDetection#89]
命名必须按照代码里的其他模块命名吗？ 如果有既有命名字段之外的想要添加，是不是改动会比较大？
建议在doc里说一下，避免走错路

**Comment by jerrywgz** [comment]
改动不会太大，可以参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.1/ppdet/data/source 里面的几个loader即可

**Comment by FibonacciSun** [comment]
参考了，实现loader。不明白的是是否要对应地添加metric定义---我看到现在metric只支持COCO，VOC，WIDER几种。按我的理解，yaml config里的metric定义, 决定了选择哪个loader。
换句话说，config 里metric的配置和source选择是如何关联的？ 感谢解答

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/models/pull/3436/files?file-filters%5B%5D=.py 
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/docs/DATA_cn.md
可以参考这两个链接，第一个是加入widerface数据集的pr，第二个是自定义数据集的文档。loader的实现会依赖dataset中anno_file的命名来选择对应的loader进行数据加载，你提到的metric是影响每种数据集对应网络的输出部分，例如coco数据集的im_info, im_id等，这些会用于网络run完之后后续的计算

**Comment by qingqing01** [comment]
后续已重构了关于自定义数据的文档: https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/advanced_tutorials/READER.md
