### ISSUE TITLE
关于CompiledProgram API

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#890]
fluid.compiler.CompiledProgram和 fluid.CompiledProgram两者是一样的吗？
发现一般是下面这两种组合方式
fluid.CompiledProgram(train_prog) 
fluid.compiler.CompiledProgram(eval_prog)

**Comment by qingqing01** [comment]
@JensenHJS 一样的。

**Comment by qingqing01** [comment]
@JensenHJS Updated in https://github.com/PaddlePaddle/PaddleDetection/pull/891
