### ISSUE TITLE
Training MOT Models

### ISSUE THREAD

**Issue by caarmeecoorbii** [PaddlePaddle/PaddleDetection#8905]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi,

I've been exploring various Multiple Object Tracking (MOT) models like DeepSORT and ByteTrack in your GitHub. I'm curious to know if it's possible to train these models with my own dataset. Could you please provide some insights on whether training these models with custom data is feasible? Also, if it is, could you kindly guide me on what command I should execute to initiate the training process?

Thanks in advance!

Carme Corbi

**Comment by lyuwenyu** [comment]
You can train with your own data. 

check docs in https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.7/docs/tutorials/data
