### ISSUE TITLE
SmallDet model GFLOPs

### ISSUE THREAD

**Issue by highquanglity** [PaddlePaddle/PaddleDetection#8906]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi, I am very interested in your research on small object detection. Can you tell me the flops and number parameters of each model? I need help finding them. Thank sir !!! 

![image](https://github.com/PaddlePaddle/PaddleDetection/assets/91304338/31ef3f12-5d96-490a-9cbf-de75f3ab5081)

**Comment by lyuwenyu** [comment]
try to set these two var to `true`
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/configs/runtime.yml#L8-L9
