### ISSUE TITLE
旋转框检测的切图预测

### ISSUE THREAD

**Issue by rsj123** [PaddlePaddle/PaddleDetection#8908]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在旋转框检测中，使用了切图的方式进行训练。
在预测中发现原图的检测效果不佳，希望使用切图方式预测。
使用deploy/python/infer.py预测，使用参数--slice_infer，但结果的标注框出现异常（见下图）
是否存在已有脚本可实现对旋转框进行切图检测，或在不切图的情况下进行数据集转换与训练
![图片](https://github.com/PaddlePaddle/PaddleDetection/assets/16500070/cd8b7088-d738-43de-a4e9-112c565dbdb8)

**Comment by lyuwenyu** [comment]
切图暂时不支持旋转框的
