### ISSUE TITLE
部署方面的问题

### ISSUE THREAD

**Issue by gzxy0102** [PaddlePaddle/PaddleDetection#8910]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

现在用FasyDeploy部署感觉还是差点意思 不能一键生成部署所用到的配置文件 而且每个模型的输入输出都不一样 我觉得可以参考mmdetection和torchserve那样 

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by gzxy0102** [comment]
而且deploy目录下的fastdeploy我跑不通。。。
ppdet和fastdeploy都不维护了么，很久没有更新了

**Comment by lyuwenyu** [comment]
ppdet在维护的 ， fastdeploy有什么问题可以在提问 https://github.com/PaddlePaddle/FastDeploy/issues
