### ISSUE TITLE
fine-tune人脸口罩模型？

### ISSUE THREAD

**Issue by DavidFangx** [PaddlePaddle/PaddleDetection#893]
需求：飞桨的人脸口罩模型应用效果很好。但偏重于识别我们日常佩戴的口罩，有的些口罩是透明类型的，如我们去熟食店或卤菜店或食堂，要求工作人员佩戴透明口罩，若没有佩戴需要预警。我们希望能基于飞桨的人脸口罩模型训练自己的模型，请提供帮助，谢谢！
https://detail.tmall.com/item.htm?spm=a220m.1000858.1000725.144.23a3603dY1ihCn&id=562234066040&skuId=4240902433288&user_id=2049340132&cat_id=2&is_b=1&rn=f4b0c5545a57a909585bb58925b9c7ac

如何制作数据集？ 先标注人脸，再标注透明口罩？

**Comment by qingqing01** [comment]
@DavidFangx  飞桨的人脸口罩是通过检测人脸，在通过分类模型判断是否戴口罩。  如果和这个相同的流畅，是先标注人脸框，同时标注是否带透明口罩。

**Comment by XYZ-916** [comment]
> @DavidFangx 飞桨的人脸口罩是通过检测人脸，再通过分类模型判断是否戴口罩。 如果和这个相同的流畅，是先标注人脸框，同时标注是否带透明口罩。

请问检测人脸和人脸是否戴口罩分类是一个模型吗？如现在的目标检测模型可以同时完成检测和分类两个任务。
