### ISSUE TITLE
我想问一下 【智慧安防】毫秒级打架识别 中的 pptsm_fight_frames_dense.yaml  在哪

### ISSUE THREAD

**Issue by muuda** [PaddlePaddle/PaddleDetection#8931]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我想问一下 [【智慧安防】毫秒级打架识别](https://aistudio.baidu.com/projectdetail/4512242) 中的 pptsm_fight_frames_dense.yaml  在哪

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleVideo/blob/develop/applications/FightRecognition/pptsm_fight_frames_dense.yaml
