### ISSUE TITLE
目标跟踪，超出时常预警

### ISSUE THREAD

**Issue by DavidFangx** [PaddlePaddle/PaddleDetection#894]
一个需求：无需识别出目标是何物，若跟踪到某个运动物体，在指定区域内长时间静止不到，则预警。基于飞桨框架可有好的解决思路？

**Comment by qingqing01** [comment]
@DavidFangx  如果是单目标跟踪的话，可以考虑跟踪模型: https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleCV/tracking
