### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by 11075225** [PaddlePaddle/PaddleDetection#8945]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

memory_mask_tiled = memory_mask.tile([fakesetsize, 1])运行这行代码报错显示

'NoneType' object has no attribute 'tile'

**Comment by lyuwenyu** [comment]
什么模型，自己的数据嘛？

**Comment by 11075225** [comment]
用的是rtdetr 数据集是自己的数据

**Comment by lyuwenyu** [comment]
没道理啊 我用coco跑起来没问题  你再check下数据  另外用的什么版本的`paddle`

**Comment by 11075225** [comment]
这行代码我在Deformable DETR网络模型中运行没问题，但是将它换到rtdetr中就会出现上述问题，  我用的paddle版本是2.6.0

**Comment by 11075225** [comment]
我感觉我的数据集应该是没问题的

**Comment by lyuwenyu** [comment]
再debug下 什么情况下导致的`memory_mask`为None  还是说一开始就这样

**Comment by 11075225** [comment]
![图片1](https://github.com/PaddlePaddle/PaddleDetection/assets/153064040/9317d0ea-0f7b-4333-b93e-f2a705882f36)
我看代码报错显示好像是前向传播这里把 memory_mask设为None 但是我看QRDeformableDETR网络中好像也是设置为None的

**Comment by lyuwenyu** [comment]
你用的那个分支

**Comment by 11075225** [comment]
我这里没动过 我只是重写了Decoder里面的方法然后重写了self.decoedr=我重写的decoder 其他都没动，分支应该就是原来的分支

**Comment by lyuwenyu** [comment]
试一下原来的代码还能跑嘛

**Comment by 11075225** [comment]
原来的代码是可以跑的

**Comment by 11075225** [comment]
我想知道这个memory_mask参数可以自己设置一个数值初始化吗  它的shape是什么样子的

**Comment by lyuwenyu** [comment]
> 原来的代码是可以跑的

> 我想知道这个memory_mask参数可以自己设置一个数值初始化吗 它的shape是什么样子的


和输入的size有关系，check下你修改的代码的问题吧
