### ISSUE TITLE
模型使用 训练问题

### ISSUE THREAD

**Issue by WANGYong-NJ** [PaddlePaddle/PaddleDetection#8953]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问paddledetection中如何实现多模态目标检测功能，是否有相应的教学例子或教程供参考，或者能否给个思路步骤。感谢

**Comment by lyuwenyu** [comment]
> 多模态目标检测

指`grounding refering`相关的嘛  暂时没有相关的例子
