### ISSUE TITLE
关于InstanceSegment

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleDetection#8960]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

你好，请问一下，实例分割是不是无法支持训练OK样本的功能（无目标图像样本）？

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
用的什么模型？

**Comment by Hold-on-li** [comment]
> 用的什么模型？

您好，用的是MaskRcnn

**Comment by lyuwenyu** [comment]
估计不太行 没专门适配过
