### ISSUE TITLE
PP-YOLOE的前置处理如何做？有无Python示例Code

### ISSUE THREAD

**Issue by TommysLee** [PaddlePaddle/PaddleDetection#8979]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PP-YOLOE的前置处理如何写？有没有Python或Java的示例Code呢？
搞清楚这个事情，我准备基于DJL实现PP-YOLOE的模型加载与调用。

**Comment by lyuwenyu** [comment]
按照config里的名字 可以在这里找到对应的实现 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/deploy/python/preprocess.py
