### ISSUE TITLE
为什么Cascade-SENet154-dcnv2的权重只有4个bboxhead卷积？

### ISSUE THREAD

**Issue by greathope** [PaddlePaddle/PaddleDetection#899]
这个[配置](https://github.com/PaddlePaddle/PaddleDetection/blob/master/configs/dcn/cascade_mask_rcnn_dcnv2_se154_vd_fpn_gn_s1x.yml)
我发现权重里只有 "'bbox_head_conv0_weights', 'bbox_head_conv0_scale', 'bbox_head_conv0_offset', 'bbox_head_conv1_weights', 'bbox_head_conv1_scale', 'bbox_head_conv1_offset', 'bbox_head_conv2_weights', 'bbox_head_conv2_scale', 'bbox_head_conv2_offset', 'bbox_head_conv3_weights', 'bbox_head_conv3_scale', 'bbox_head_conv3_offset'" 4个bboxhead卷积层，理论上应该是4x3个卷积才对，是我哪里理解有问题吗

**Comment by FDInSky** [comment]
![image](https://user-images.githubusercontent.com/48318485/84099941-5ee4c780-aa3d-11ea-8ecc-64d1807754ea.png)

![Uploading image.png…]()

cascade head在解码box之前通过XConvNormHead进一步学习特征，这里就是四个conv的name在每个阶段是一样的，所以三个阶段是共享的

**Comment by greathope** [comment]
@FDInSky 为什么 CascadeTwoFCHead 是不共享的呢？而且在mmdetection的实现里Convhead也是不共享的

**Comment by FDInSky** [comment]
@greathope 共享可以加速，可以防止过拟合等，但具体是否选择共享，可以根据实验情况来决定，这个不是固定的。可以参考原作者实现https://github.com/zhaoweicai/Detectron-Cascade-RCNN/blob/master/detectron/modeling/cascade_rcnn_heads.py
