### ISSUE TITLE
Could you tell me how to change an inference model to a trained model?

### ISSUE THREAD

**Issue by michael-selvas** [PaddlePaddle/PaddleDetection#8990]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

I accidentally deleted the trained model.
I want to restore the remaining inference model to the trained model.

**Comment by lyuwenyu** [comment]
I don't think this can be fully restored, so you can only use the inference model to initialize the parameters
