### ISSUE TITLE
mot的JDE如何将原始detector换成yolov5或者yolov8

### ISSUE THREAD

**Issue by plotnine1219** [PaddlePaddle/PaddleDetection#8991]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

mot的JDE如何将原始detector换成yolov5或者yolov8，需要改那些配置文件

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/configs/mot/jde/_base_/jde_darknet53.yml#L6
把里面的`detector`改成`yolov5`或者`yolov8`的配置

**Comment by plotnine1219** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/configs/mot/jde/_base_/jde_darknet53.yml#L6 把里面的`detector`改成`yolov5`或者`yolov8`的配置

请问，只需要改这个配置文件就可以吗？

**Comment by lyuwenyu** [comment]
是的  但是这个仓库里没有yolov5或者yolov8的实现 你得配合paddleyolo一起使用
