### ISSUE TITLE
模型训练完了，我想在python脚本里单独对某张影像或者某个文件夹影像做一下检测，拿到检测结果，请问有相关的接口吗

### ISSUE THREAD

**Issue by lyf6** [PaddlePaddle/PaddleDetection#8993]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

模型训练完了，我想在python脚本里单独对某张影像或者某个文件夹影像做一下检测，拿到检测结果，请问有相关的接口吗

**Comment by lyuwenyu** [comment]
可以的 使用
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/tools/infer.py
