### ISSUE TITLE
data模块的x2coco.py工具，在val和test逻辑分支调用deal_json函数时少传了一个参数导致调用错误

### ISSUE THREAD

**Issue by FibonacciSun** [PaddlePaddle/PaddleDetection#90]
v0.1.0

if args.val_proportion != 0:
  val_data_coco = deal_json(args.output_dir + '/val', args.json_input_dir)

 if args.test_proportion != 0:
        test_data_coco = deal_json(args.output_dir + '/test', ...)

如上代码段，少了给deal_json一个参数，跑到报错

**Comment by FibonacciSun** [comment]
if args.val_proportion != 0:
-        val_data_coco = deal_json(args.output_dir + '/val', args.json_input_dir)
+        val_data_coco = deal_json(args.dataset_type, args.output_dir + '/val', args.json_input_dir)
         val_json_path = osp.join(args.output_dir + '/annotations',
                                  'instance_val.json')
         json.dump(
             val_data_coco, open(val_json_path, 'w'), indent=4, cls=MyEncoder)
     if args.test_proportion != 0:
-        test_data_coco = deal_json(args.output_dir + '/test',
+        test_data_coco = deal_json(args.dataset_type, args.output_dir + '/test',
                                    args.json_input_dir)
         test_json_path = osp.join(args.output_dir + '/annotations',
                                   'instance_test.json')

**Comment by SunAhong1993** [comment]
> v0.1.0
> 
> if args.val_proportion != 0:
> val_data_coco = deal_json(args.output_dir + '/val', args.json_input_dir)
> 
> if args.test_proportion != 0:
> test_data_coco = deal_json(args.output_dir + '/test', ...)
> 
> 如上代码段，少了给deal_json一个参数，跑到报错

您好，针对该问题我们已进行了修复，详见https://github.com/PaddlePaddle/PaddleDetection/pull/94。
