### ISSUE TITLE
萌新请教，为何报错，需要13EB内存？

### ISSUE THREAD

**Issue by kiddkyd2** [PaddlePaddle/PaddleDetection#9005]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

数据集是我自己拉框的40几张图片。已经导出coco格式的json。

按照网上教程，执行了这个命令： python tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml --eval

报错：
Out of memory error on GPU 0. Cannot allocate 13.906031EB memory on GPU 0, 5.367256GB memory has been allocated and available memory is only 647.804688MB.

这个内存要求13EB也太高了吧？我显卡是GTX 1060，6G显存。支持CUDA 12.2，安装的CUDA Tookit 12.2.0。

有什么办法可以简单的跑一下图像分类吗？想用yolo的，但是yolov3，yolov8，都不行，要么说内存不够，要么说CUDA没有符合的内核。

**Comment by lyuwenyu** [comment]
你卡的显存多大，可以把`data reader`config里的`batch size`改小点

**Comment by kiddkyd2** [comment]
> 你卡的显存多大，可以把`data reader`config里的`batch size`改小点

把worker_num: 1  和batch_size: 1后，还是提示要196.187500TB memory

**Comment by lyuwenyu** [comment]
改啥了没？ 除了上面的其他的是默认的配置嘛

**Comment by kiddkyd2** [comment]
> 改啥了没？ 除了上面的其他的是默认的配置嘛

萌新哪敢乱改啊。。。。就是改了指向训练集的yml配置路径而已。。。话说，你们什么配置，都没遇到这个问题吗？我跑ultralytics框架，用batch=1，workers=0都可以成功跑完训练。

**Comment by lyuwenyu** [comment]
没遇到过这个问题，刚测了下 可以跑的..
