### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by alanOO7** [PaddlePaddle/PaddleDetection#9016]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Using cached motmetrics-1.4.0-py3-none-any.whl (161 kB)
Using cached xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Building wheels for collected packages: lap
  Building wheel for lap (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [134 lines of output]
      C:\Users\mcnalwan\AppData\Local\Temp\pip-install-8w2g_s5i\lap_ffe84e5364ea443bbb4ddab87c6953a3\setup.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Partial import of lap during the build process.
      C:\Users\mcnalwan\AppData\Local\Temp\pip-install-8w2g_s5i\lap_ffe84e5364ea443bbb4ddab87c6953a3\setup.py:223: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html

        from numpy.distutils.core import setup
      Generating cython files
      running bdist_wheel
      running build
      running config_cc
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      INFO: build_src
      INFO: building extension "lap._lapjv" sources
      INFO: building data_files sources
      INFO: build_src: building npy-pkg config files
      C:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\lap
      copying lap\lapmod.py -> build\lib.win-amd64-cpython-39\lap
      copying lap\__init__.py -> build\lib.win-amd64-cpython-39\lap
      running build_ext
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO: customize MSVCCompiler using build_ext
      INFO: CCompilerOpt.cc_test_flags[1086] : testing flags (/O2)
      creating C:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users
      creating C:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan
      creating C:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData
      creating C:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData\Local
      creating C:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData\Local\anaconda3
      creating C:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData\Local\anaconda3\envs
      creating C:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env
      creating C:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib
      creating C:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib\site-packages
      creating C:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib\site-packages\numpy
      creating C:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib\site-packages\numpy\distutils
      creating C:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib\site-packages\numpy\distutils\checks
      INFO: CCompilerOpt.cc_test_flags[1086] : testing flags (/WX)
      WARN: CCompilerOpt.__init__[1253] : feature 'AVX512_KNL' is disabled, MSVC compiler doesn't support it
      WARN: CCompilerOpt.__init__[1253] : feature 'AVX512_KNM' is disabled, MSVC compiler doesn't support it
      WARN: CCompilerOpt.__init__[1253] : feature 'AVX512_SPR' is disabled, MSVC compiler doesn't support it
      INFO: CCompilerOpt.__init__[1795] : check requested baseline
      INFO: CCompilerOpt.feature_test[1560] : testing feature 'SSE2' with flags ()
      WARN: CCompilerOpt.dist_test[637] : CCompilerOpt._dist_test_spawn[771] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\include -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um /TcC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib\site-packages\numpy\distutils\checks\cpu_sse2.c /FoC:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib\site-packages\numpy\distutils\checks\cpu_sse2.obj /WX) failed with exit status 2 output ->
      cpu_sse2.c
      C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\xmmintrin.h(79): fatal error C1083: Cannot open include file: 'malloc.h': No such file or directory

      WARN: CCompilerOpt.feature_test[1576] : testing failed
      INFO: CCompilerOpt.feature_test[1560] : testing feature 'SSE' with flags ()
      WARN: CCompilerOpt.dist_test[637] : CCompilerOpt._dist_test_spawn[771] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\include -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um /TcC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib\site-packages\numpy\distutils\checks\cpu_sse.c /FoC:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib\site-packages\numpy\distutils\checks\cpu_sse.obj /WX) failed with exit status 2 output ->
      cpu_sse.c
      C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\xmmintrin.h(79): fatal error C1083: Cannot open include file: 'malloc.h': No such file or directory

      WARN: CCompilerOpt.feature_test[1576] : testing failed
      INFO: CCompilerOpt.__init__[1804] : check requested dispatch-able features
      INFO: CCompilerOpt.feature_test[1560] : testing feature 'SSSE3' with flags ()
      WARN: CCompilerOpt.dist_test[637] : CCompilerOpt._dist_test_spawn[771] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\include -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um /TcC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib\site-packages\numpy\distutils\checks\cpu_ssse3.c /FoC:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib\site-packages\numpy\distutils\checks\cpu_ssse3.obj /WX) failed with exit status 2 output ->
      cpu_ssse3.c
      C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\xmmintrin.h(79): fatal error C1083: Cannot open include file: 'malloc.h': No such file or directory

      WARN: CCompilerOpt.feature_test[1576] : testing failed
      INFO: CCompilerOpt.feature_test[1560] : testing feature 'SSE41' with flags ()
      WARN: CCompilerOpt.dist_test[637] : CCompilerOpt._dist_test_spawn[771] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\include -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um /TcC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib\site-packages\numpy\distutils\checks\cpu_sse41.c /FoC:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib\site-packages\numpy\distutils\checks\cpu_sse41.obj /WX) failed with exit status 2 output ->
      cpu_sse41.c
      C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\xmmintrin.h(79): fatal error C1083: Cannot open include file: 'malloc.h': No such file or directory

      WARN: CCompilerOpt.feature_test[1576] : testing failed
      INFO: CCompilerOpt.cc_test_flags[1086] : testing flags (/arch:AVX)
      INFO: CCompilerOpt.cc_test_flags[1086] : testing flags (/arch:AVX2)
      INFO: CCompilerOpt.cc_test_flags[1086] : testing flags (/arch:AVX512)
      INFO: CCompilerOpt.feature_test[1560] : testing feature 'AVX512_CLX' with flags (/arch:AVX512)
      WARN: CCompilerOpt.dist_test[637] : CCompilerOpt._dist_test_spawn[771] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\include -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um /TcC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib\site-packages\numpy\distutils\checks\cpu_avx512_clx.c /FoC:\Users\mcnalwan\AppData\Local\Temp\tmp5wegyphv\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Lib\site-packages\numpy\distutils\checks\cpu_avx512_clx.obj /arch:AVX512 /WX) failed with exit status 2 output ->
      cpu_avx512_clx.c
      C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\xmmintrin.h(79): fatal error C1083: Cannot open include file: 'malloc.h': No such file or directory

      WARN: CCompilerOpt.feature_test[1576] : testing failed
      INFO: CCompilerOpt.__init__[1820] : initialize targets groups
      INFO: CCompilerOpt.__init__[1822] : parse target group simd_test
      INFO: CCompilerOpt._parse_target_tokens[2033] : skip targets (VX NEON SSE42 VSX SSE2 XOP AVX512_SKX ASIMD VSX2 VXE2 FMA4 AVX512F VSX4 (AVX2 FMA3) VSX3 VXE) not part of baseline or dispatch-able features       
      INFO: CCompilerOpt.generate_dispatch_header[2366] : generate CPU dispatch header: (build\src.win-amd64-3.9\numpy\distutils\include\npy_cpu_dispatch_config.h)
      WARN: CCompilerOpt.generate_dispatch_header[2375] : dispatch header dir build\src.win-amd64-3.9\numpy\distutils\include does not exist, creating it
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      WARN: Missing compiler_cxx fix for MSVCCompiler
      INFO: customize MSVCCompiler using build_ext
      INFO: building 'lap._lapjv' extension
      INFO: compiling C sources
      creating build\temp.win-amd64-cpython-39\Release\lap
      INFO: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\lib\site-packages\numpy\core\include -Ilap -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.9\numpy\distutils\include -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\include -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um /EHsc /Tplap\_lapjv.cpp /Fobuild\temp.win-amd64-cpython-39\Release\lap\_lapjv.obj /Zm1000
      _lapjv.cpp
      c:\users\mcnalwan\appdata\local\anaconda3\envs\paddle_env\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
      error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\lib\site-packages\numpy\core\include -Ilap -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.9\numpy\distutils\include -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\include -IC:\Users\mcnalwan\AppData\Local\anaconda3\envs\paddle_env\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um /EHsc /Tplap\_lapjv.cpp /Fobuild\temp.win-amd64-cpython-39\Release\lap\_lapjv.obj /Zm1000" failed with exit status 2
      INFO:
      ########### EXT COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : msvc

      CPU baseline  :
        Requested   : 'min'
        Enabled     : none
        Flags       : none
        Extra checks: none

      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : none
        Generated   : none
      INFO: CCompilerOpt.cache_flush[864] : write cache to path -> C:\Users\mcnalwan\AppData\Local\Temp\pip-install-8w2g_s5i\lap_ffe84e5364ea443bbb4ddab87c6953a3\build\temp.win-amd64-cpython-39\Release\ccompiler_opt_cache_ext.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lap
  Running setup.py clean for lap
Failed to build lap
ERROR: Could not build wheels for lap, which is required to install pyproject.toml-based projects

安装报错，这是啥原因啊

**Comment by alanOO7** [comment]
先注释 lap ，再重新进行require安装。再进行lap安装: conda install -c conda-forge lap 以上问题基本可解决。

**Comment by xiaoc57** [comment]
虽然这个问题解决了，但是这个问题好像是因为numpy版本的问题
