### ISSUE TITLE
关于修改网络结构

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#903]
在代码中修改某些卷积层，并修改相应的name，那么加载预训练模型的时候，会自动跳过修改的的卷积层吧？
但是发现修改之后map明显比之前不好，是否可能跟某些层没有使用预训练权重有关？如果网络结构不改变，修改某些卷积层的name，使得某些层不加载预训练，训得的map会不会也差得很远？

**Comment by jerrywgz** [comment]
通常来说如果修改了某一层的网络结构或是名称使得该层的预训练权重没有加载，那么该层之后的权重也不应该加载
