### ISSUE TITLE
怎样得到coco数据集测试的json结果

### ISSUE THREAD

**Issue by PP-dog** [PaddlePaddle/PaddleDetection#904]
想要得到coco数据集测试结果的json文件提交到codalab，但是infer.py是不是只保存图片结果，不保存json文件

**Comment by jerrywgz** [comment]
可以参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/configs/yolov4/yolov4_cspdarknet.yml 这里的配置，在配置文件中增加save_prediction_only: True，同时使用coco_test数据集，使用eval.py就会将结果自动保存
