### ISSUE TITLE
通过下载blazeface模型，进行服务端部署，客户端报错，请问是什么问题？

### ISSUE THREAD

**Issue by vinceyzw** [PaddlePaddle/PaddleDetection#907]
1、下载blazeface模型
https://paddlemodels.bj.bcebos.com/object_detection/blazeface_original.tar
2、Paddle Serving部署模型导出
python tools/export_serving_model.py
3、启动服务端服务
python -m paddle_serving_server.serve --model serving_model --thread 2 --port 9000 --name detect
4、客户端运行报错
def cv2_to_base64(image):
    data = cv2.imencode('.jpg', image)[1]
    return base64.b64encode(data.tostring()).decode('utf8')
input_path = "../../work/test3.jpg"
data = {'images':[cv2_to_base64(cv2.imread(str(input_path)))]}
headers = {"Content-type": "application/json"}
url = "http://127.0.0.1:9000/predict/detect"
r = requests.post(url=url, headers=headers, data=json.dumps(data))

================
Traceback (most recent call last):
  File "blazeface.py", line 14, in <module>
    r = requests.post(url=url, headers=headers, data=json.dumps(data), timeout=None)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9000): Max retries exceeded with url: /predict/detect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa88667c410>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by vinceyzw** [comment]
@wangjiawei04 大佬帮忙看看

**Comment by cqzhao** [comment]
你的这个怎么跟我的一样？是不是fork我的AIStudio了？嘿嘿。

**Comment by wangjiawei04** [comment]
> 1、下载blazeface模型
> https://paddlemodels.bj.bcebos.com/object_detection/blazeface_original.tar
> 2、Paddle Serving部署模型导出
> python tools/export_serving_model.py
> 3、启动服务端服务
> python -m paddle_serving_server.serve --model serving_model --thread 2 --port 9000 --name detect
> 4、客户端运行报错
> def cv2_to_base64(image):
> data = cv2.imencode('.jpg', image)[1]
> return base64.b64encode(data.tostring()).decode('utf8')
> input_path = "../../work/test3.jpg"
> data = {'images':[cv2_to_base64(cv2.imread(str(input_path)))]}
> headers = {"Content-type": "application/json"}
> url = "http://127.0.0.1:9000/predict/detect"
> r = requests.post(url=url, headers=headers, data=json.dumps(data))
> 
> ================
> Traceback (most recent call last):
> File "blazeface.py", line 14, in
> r = requests.post(url=url, headers=headers, data=json.dumps(data), timeout=None)
> File "/usr/lib/python2.7/site-packages/requests/api.py", line 119, in post
> return request('post', url, data=data, json=json, **kwargs)
> File "/usr/lib/python2.7/site-packages/requests/api.py", line 61, in request
> return session.request(method=method, url=url, **kwargs)
> File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
> resp = self.send(prep, **send_kwargs)
> File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
> r = adapter.send(request, **kwargs)
> File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
> raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9000): Max retries exceeded with url: /predict/detect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa88667c410>: Failed to establish a new connection: [Errno 111] Connection refused',))

serving端有成功启动了吗

**Comment by vinceyzw** [comment]
> > 1、下载blazeface模型
> > https://paddlemodels.bj.bcebos.com/object_detection/blazeface_original.tar
> > 2、Paddle Serving部署模型导出
> > python tools/export_serving_model.py
> > 3、启动服务端服务
> > python -m paddle_serving_server.serve --model serving_model --thread 2 --port 9000 --name detect
> > 4、客户端运行报错
> > def cv2_to_base64(image):
> > data = cv2.imencode('.jpg', image)[1]
> > return base64.b64encode(data.tostring()).decode('utf8')
> > input_path = "../../work/test3.jpg"
> > data = {'images':[cv2_to_base64(cv2.imread(str(input_path)))]}
> > headers = {"Content-type": "application/json"}
> > url = "http://127.0.0.1:9000/predict/detect"
> > r = requests.post(url=url, headers=headers, data=json.dumps(data))
> > ================
> > Traceback (most recent call last):
> > File "blazeface.py", line 14, in
> > r = requests.post(url=url, headers=headers, data=json.dumps(data), timeout=None)
> > File "/usr/lib/python2.7/site-packages/requests/api.py", line 119, in post
> > return request('post', url, data=data, json=json, **kwargs)
> > File "/usr/lib/python2.7/site-packages/requests/api.py", line 61, in request
> > return session.request(method=method, url=url, **kwargs)
> > File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
> > resp = self.send(prep, **send_kwargs)
> > File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
> > r = adapter.send(request, **kwargs)
> > File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
> > raise ConnectionError(e, request=request)
> > requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9000): Max retries exceeded with url: /predict/detect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa88667c410>: Failed to establish a new connection: [Errno 111] Connection refused',))
> 
> serving端有成功启动了吗

serving端没有报错

**Comment by vinceyzw** [comment]
> 你的这个怎么跟我的一样？是不是fork我的AIStudio了？嘿嘿。

对的，我以为这个是飞桨提供的案例。你问题解决了吗

**Comment by cqzhao** [comment]
我算是解决了吧。已经能够成功部署和返回结果。问题是返回的结果很诡异，应该是有问题的。你可以去我的AIStudio上看一下。

**Comment by cqzhao** [comment]
> > 我算是解决了吧。已经能够成功部署和返回结果。问题是返回的结果很诡异，应该是有问题的。你可以去我的AIStudio上看一下。
> 
> 用你的aistudio返回结果在哪里看到？
> r = requests.post(url=url, headers=headers, data=json.dumps(data))
> 这个只能返回状态码吧。
> 有办法返回人脸坐标吗
> @cqzhao

你可以看一下我的AIStudio，里面有返回数据的处理。
但是，这个返回的数据非常诡异。我画到图上基本都不是脸的位置。
也在等@wangjiawei04来解决一下
