### ISSUE TITLE
请问现在移动端sota的模型还是pico-det么

### ISSUE THREAD

**Issue by kkpssr** [PaddlePaddle/PaddleDetection#9082]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问现在移动端sota的模型还是pico-det么

**Comment by Bobholamovic** [comment]
你好，是的哈～

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
