### ISSUE TITLE
如何部署寒武纪mlu设备的Python端预测

### ISSUE THREAD

**Issue by xiaolongking** [PaddlePaddle/PaddleDetection#9087]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

使用deploy/python/下的示例代码尝试部署，device 配置了mlu，提示不支持mlu设备。

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by cuicheng01** [comment]
您好，使用MLU推荐使用PaddleX，打通了很多的硬件训练和推理预测
```
from pathlib import Path
from paddlex import DetPipeline
from paddlex import PaddleInferenceOption

# 实例化 PaddleInferenceOption 设置推理配置
kernel_option = PaddleInferenceOption()
kernel_option.set_device("gpu:0")

model_name =  "RT-DETR-L"
output_base = Path("output")
output = output_base / model_name

pipeline = DetPipeline(model_name, output=output, kernel_option=kernel_option)
result = pipeline.predict(
        {"input_path": "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_object_detection_002.png"})
print(result["boxes"])
```
上述内容中，将`kernel_option.set_device("gpu:0")`换成`kernel_option.set_device("mlu:0")`即可。
寒武纪的安装方式可以参考：[安装](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta/docs/tutorials/INSTALL_OTHER_DEVICES.md)，支持的模型可以参考：[寒武纪支持列表](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta/docs/tutorials/models/support_mlu_model_list.md)，支持列表还在持续更新中...

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
