### ISSUE TITLE
哪里可以找到“数据增强”算子的具体使用说明文档

### ISSUE THREAD

**Issue by CashBai** [PaddlePaddle/PaddleDetection#9088]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如题，没有找到数据增强算子对应的输入参数说明及文档

**Comment by cuicheng01** [comment]
您好，可以看这里～docs/advanced_tutorials/READER.md

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
