### ISSUE TITLE
BOT_SORT 利用自己数据集进行多目标追踪训练后如何进行验证

### ISSUE THREAD

**Issue by C-rawler** [PaddlePaddle/PaddleDetection#9089]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

#Single gpu
CUDA_VISIBLE_DEVICES=0 python tools/train.py -c configs/mot/bytetrack/detector/ppyoloe_crn_l_36e_640x640_mot17half.yml --eval --amp
我参照官方文档利用此命令进行模型训练之后，如何使用自己训练出来的checkpoint进行推理验证？

官方给出来的mot验证命令里没看到配置weights的参数
mot
CUDA_VISIBLE_DEVICES=0 python tools/eval_mot.py -c configs/mot/botsort/botsort_ppyoloe.yml --scaled=True

查找botsort_ppyoloe.yml 配置文件发现内部有
det_weights: https://bj.bcebos.com/v1/paddledet/models/mot/ppyoloe_crn_l_36e_640x640_mot17half.pdparams
reid_weights: None
两个配置，请问前面训练出来的checkpoint是替换det_weights还是reid_weights进行验证？

**Comment by lyuwenyu** [comment]
换检测的权重 det_weights

**Comment by C-rawler** [comment]
> 换检测的权重 det_weights

感谢解答，我看我训练出来的checkpoint大小和官方的不一致，预训练出来的ppyoloe_crn_l_36e_640x640_mot17half.pdparams大小是204M，我自己训练出来的大小都是214M，其他的模型比如centernet_dla34_140e_coco.pdparams自己训练出来的和官方大小都是一致的，而且替换权重进行验证的时候报没检测出目标的警告，请问这可能是什么原因呢？

**Comment by cuicheng01** [comment]
可能是类别数量不一样导致检测头大小不一样？

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
