### ISSUE TITLE
使用paddle2.6训练的ppyoloe模型在paddl2.3.2虚拟环境下运行不了，也不报错

### ISSUE THREAD

**Issue by stephen-TT** [PaddlePaddle/PaddleDetection#9091]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference, Deploy

### Bug描述 Describe the Bug

我在linux下conda环境中使用 paddlepaddle-gpu    2.6.1.post112 + paddleDetection2.7.0 仓库训练了一个ppyoloe的检测模型，导出后在Windows下的paddlepaddle-gpu   2.3.2.post112环境中运行不了

### 复现环境 Environment

- OS: Windows
- -PaddlePaddle: paddlepaddle-gpu   2.3.2.post112
- -PaddleDetection: release/2.7.0
- -Python: 3.10.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by stephen-TT** [comment]
补充信息-1：
下面是使用 paddlepaddle-gpu 2.3.2.post112 包的运行日志：
```
   我的运行命令：python deploy/python/infer.py --model_dir=output_inference/ppyoloe_plus_crn_l_30e_voc_gesture --camera_id=0 --device=gpu
```
![image](https://github.com/user-attachments/assets/9227a57a-88a2-43a3-8153-3224167d8888)

**Comment by liuhongen1234567** [comment]
您好，paddle2.6 中的某些算子在paddle 2.3.2 不一定支持，建议您在Windows下的 paddlepaddle-gpu 2.6.1.post112 运行一下试试。

**Comment by stephen-TT** [comment]
> 您好，paddle2.6 中的某些算子在paddle 2.3.2 不一定支持，建议您在Windows下的 paddlepaddle-gpu 2.6.1.post112 运行一下试试。

试过了，可以正常推理，有什么办法能让这个模型在paddle 2.3.2下运行吗，不想重新训练

**Comment by liuhongen1234567** [comment]
你可以在linux paddle 2.3.2环境下导出试试。paddle 动态图变化应该不大。

**Comment by stephen-TT** [comment]
> 你可以在linux paddle 2.3.2环境下导出试试。paddle 动态图变化应该不大。

这个可以，神奇。

**Comment by stephen-TT** [comment]
1、使用paddle2.6环境导出的inference模型和使用paddle2.3环境导出的inference模型，他们在使用trt加速的时候（基于paddleetection2.3代码），性能差异大吗？

2、同一个paddle2.3版本的inference模型（paddle2.6训练，paddle2.3导出），在1050ti（CUDA 10.2\CUDNN 7.6.5\trt7.0.0.11）上面和3070（CUDA 11.2\CUDNN 8.2.1\TENSORRT 8.0.1.6）上面使用trt加速（基于paddleetection2.3代码），我测试出加速效果没有明显的差异，这是什么原因。
