### ISSUE TITLE
海思SD3403/SS928

### ISSUE THREAD

**Issue by whxuexi** [PaddlePaddle/PaddleDetection#9093]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问最新的RT-DETR:等算法，支持在海思SD3403/SS928芯片上部署嘛

**Comment by changdazhou** [comment]
暂不支持哈

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
