### ISSUE TITLE
yolov3_r50vd_dcn 导出后在PaddleDetection工程之外基本无法使用

### ISSUE THREAD

**Issue by aixier** [PaddlePaddle/PaddleDetection#91]
fetch_list的传入方法异常复杂，没有完整学完paddle是用不了的
@qingqing01 
yolov3_r50vd_dcn训练完成 导出后在PaddleDetection工程之外基本无法使用

**Comment by aixier** [comment]
@qingqing01

**Comment by jerrywgz** [comment]
-> fetch_list的传入方法异常复杂，没有完整学完paddle是用不了的 
你这边是希望实现什么功能呢，paddle保存的中间模型也是可以使用的

-> 导出后在PaddleDetection工程之外基本无法使用
这里具体是如何操作的？报错信息是什么呢？

**Comment by aixier** [comment]
先[inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model()得到三个参数
然后
 exe.run(inference_program,
                            feed={feed_target_names[0]: tensor_img,
                                  feed_target_names[1]: im_size[np.newaxis, :]
                           },
                            fetch_list=fetch_targets,
                            return_numpy=False) 
预测结果不对。
经过print检测：官方infer （https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/tools/infer.py）
fetch_list 的内容是['multiclass_nms_0.tmp_0', 'im_id']
而我load后print(fetch_targets)内容是
 [name: "save_infer_model/scale_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: 22743
      dims: 6
    }
    lod_level: 0
  }
}
persistable: false
]
不一致。
然后我想改成一致，发现infer文件里面的fetch_list生成过程复杂，移植不出来

**Comment by aixier** [comment]
不报错，但是我的 exe.run返回和PaddleDetection里面的exe.run返回明显不一样。
PaddleDetection预测是正确的
我的exe.run预测是错误的，同一个模型

**Comment by jerrywgz** [comment]
你需要先将训练得到的模型保存为inference_model再使用，可以参考这个文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/docs/EXPORT_MODEL.md

**Comment by aixier** [comment]
就是参考的这个文档 python tools/export_model.py -c configs/dcn/yolov3_r50vd_dcn.yml   --output_dir=./inference_model_2

**Comment by aixier** [comment]
经过print("label==\n",np.array(outs[0][:, 0]))
我的exe.run返回label是labels=======
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
PaddleDetection 的exe.run 返回的label是
label========================
 [[ 0.] [ 0.][ 0.] [ 0.] [ 1.].........[2]....[25][26]]
我总共27个类别

**Comment by aixier** [comment]
origin, tensor_img, resized_img = ImgToOne(infeimg)
    input_w, input_h,cw = origin.size[0], origin.size[1],1
    image_shape = np.array([input_h, input_w,cw], dtype='float32')
    im_id= np.array([0], dtype='int')
    im_info= np.array([800.,800.,1], dtype='float32')
    im_size=np.array([input_h,input_w], dtype='int')
    im_id_lod= fluid.create_lod_tensor(im_id[np.newaxis, :], [],fluid.CPUPlace())
    im_info_lod= fluid.create_lod_tensor(im_info[np.newaxis, :], [],fluid.CPUPlace())
    image_shape_lod= fluid.create_lod_tensor(image_shape[np.newaxis, :], [],fluid.CPUPlace())
    im_size_lod= fluid.create_lod_tensor(im_size[np.newaxis, :], [],fluid.CPUPlace())

    t1 = time.time()

    #yolodcn
    batch_outputs = exe.run(inference_program,
                            feed={feed_target_names[0]: tensor_img,
                                  feed_target_names[1]: im_size[np.newaxis, :]
                           },
                            fetch_list=fetch_targets,
                            return_numpy=False) ``

**Comment by qingqing01** [comment]
> fetch_list 的内容是['multiclass_nms_0.tmp_0', 'im_id']
> 而我load后print(fetch_targets)内容是
[name: "save_infer_model/scale_0"

先解释下， `save_infer_model/scale_0` 这个是导出模型时PaddlePaddle框架给加进来的，这个不影响结果的正确性，如果，print(inference_program) 保存到一个文件，你会发现，这个op之前的op就是输出为`multiclass_nms_0.tmp_0`的op。

**Comment by jerrywgz** [comment]
你在外部使用的数据预处理需要和PaddleDetection中https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/ppdet/data/data_feed.py#L1009 的处理结果相同，看使用上没什么问题。
另外关于fetch_list，tool/export_model.py会将test model进行裁剪，所以im_id不在保存的inference_model中

**Comment by aixier** [comment]
您的意思是我feed的图片数据不对而不是fetch_list数据不对是么？

**Comment by aixier** [comment]
我用cascade_rcnn_dcn_r50_fpn_1x可以正确预测，图片预处理应该没有问题。是同一个预处理函数
```
def ImgToOne(infeimg):
    """
    读取图片归一
    :param img_path:
    :return:
    """
#    origin = Image.open(img_path)
    origin = infeimg

    img = resize_img(origin, target_size)
    resized_img = img.copy()
    if img.mode != 'RGB':
        img = img.convert('RGB')
    img = np.array(img).astype('float32').transpose((2, 0, 1))  # HWC to CHW
    img -= 127.5
    img *= 0.007843
    img = img[np.newaxis, :]
    return origin, img, resized_img
```

**Comment by aixier** [comment]
您在外部用 exe.run试试看

**Comment by aixier** [comment]
@qingqing01

**Comment by qingqing01** [comment]
@aixier  参考  https://github.com/PaddlePaddle/PaddleDetection/issues/98   ，在这里提供了完整的YOLOv3中Python 使用 load_inference_model 的预测示例，我测试可以可视化正确。

**Comment by qingqing01** [comment]
closed due to https://github.com/PaddlePaddle/PaddleDetection/issues

**Comment by aixier** [comment]
用这个模型试试链接：https://pan.baidu.com/s/1aboMGI1uiax4yZLcnCd-3Q 
提取码：tpig
