### ISSUE TITLE
版面分析CDLA训练集训练后导出的inference 模型结构化文件大小的影响因素是什么？

### ISSUE THREAD

**Issue by BotAndyGao** [PaddlePaddle/PaddleDetection#9102]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

# 问题
我自己训练的导出的inference 模型中的模型结构文件model.pdmodel的大小与Paddle提供的picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar包中模型结构文件大小相差很大，想请教一下是什么原因？这个模型结构文件的大小与哪些因素有关？需要配置哪些参数？

我训练导出的模型结构文件大小213k，Paddle给出的picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar包中的模型结构文件大小为2.7M。

# 以下是训练环境及配置

## 运行硬件信息
- OS: Ubuntu 20.04
- Memory: 256GB
- Python: 3.10.12
- CUDA Version: 12.1
- NVIDIA GeForce RTX 3090-24GB * 6

## 飞浆官方软件信息
- Paddle版本：2.5.2， 安装方式：Docker
- PaddleDetection版本： release/2.7， 安装方式：源码

## 采用CDLA训练集
5000张中文论文类训练图片，1000张验证图片

## 训练配置
- 普通训练（未使用FGD蒸馏方式）
- 2块3090卡
- 100轮
- base_lr=0.1
- 模型导出配置
export:
  post_process: False  
  nms: True     
  benchmark: False   
  fuse_conv_bn: False
## 训练情况
训练完成，checkpoints模型预测、inference 模型预测均正常。

## 附件是更详细的信息
[模型结构化文件的大小问题.docx](https://github.com/user-attachments/files/16687727/default.docx)

**Comment by zhangyubo0722** [comment]
pdmodel文件存储的是静态图模型结构，有两个原因可能导致文件大小不一致。首先是模型结构有差异，这点可以通过 https://netron.app/ 这个工具可视化看一下，把pdmodel文件直接拖进去就好，看自己导出的模型和官方提供的模型在结构上是否有diff；其次，如果模型结构一致的话，也可能因为PaddleDetection套件所提供的静态图模型是基于较早版本的paddle导出的，而使用较新版本的paddle导出的静态图存储方式可能有些差异，所以导致文件大小不同。

**Comment by BotAndyGao** [comment]
## 非常感谢您的解答
1、两个模型结构确实存在了许多diff，大概6处。
2、两个模型结构化文件确实不是在一个版本下导出的，官方是PaddleDetection-V2.2.2，我们训练的是在V2.5.2导出的。
## 另一个疑问
可不可以这样理解，这个模型结构的大小和版面识别分析的准确度没有必然的联系？

**Comment by cuicheng01** [comment]
还有一个原因哈，就是pdmodel会存储导出的路径，所以如果导出时的目录路径特别长，可能会使pdmodel的存储变大，但是不影响精度哈

**Comment by zhangyubo0722** [comment]
如果是可视化出来的模型结构有差异，那对模型的精度就会有一定的影响，其他原因则不影响精度。

**Comment by BotAndyGao** [comment]
感谢两位同学，通过实测精度确实没有损失，我们训练后导出的文件小了好多，心里不踏实啊！

**Comment by michaelowenliu** [comment]
> 感谢两位同学，通过实测精度确实没有损失，我们训练后导出的文件小了好多，心里不踏实啊！

你好，问题已经解决了吗？

**Comment by BotAndyGao** [comment]
> > 感谢两位同学，通过实测精度确实没有损失，我们训练后导出的文件小了好多，心里不踏实啊！
> 
> 你好，问题已经解决了吗？

已经解决
