### ISSUE TITLE
支持pip安装吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleDetection#911]
请问支持`pip`或者`python setup.py install`安装吗？
因为太多的代码不方便项目维护。

**Comment by jerrywgz** [comment]
暂时还不支持pip安装

**Comment by yeyupiaoling** [comment]
@jerrywgz 有计划支持吗？

**Comment by jerrywgz** [comment]
先前有讨论过这个需求，近期可能还没有这个计划

**Comment by yeyupiaoling** [comment]
@jerrywgz 有知道这个需求就好，因为我们在实际项目中不可能把整个PaddleDetection项目的代码放在我们的项目中的，如果可以使用pip或者python setup.py install安装，可以省去很多必要而且不能修改的代码。
我们之前是使用Tensorflow 的object Detection，他们就是支持python setup.py install。
