### ISSUE TITLE
ppyoloe使用deploy/python/infer.py推理出错；

### ISSUE THREAD

**Issue by sg-goldrush** [PaddlePaddle/PaddleDetection#9110]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用ppyoloe网络，ppyoloe_plus_crn。能正常训练导出模型，但使用deploy/python/infer.py推理报错；

环境 paddlepaddle2.4.1. ppdet2.6 python3.8 CUDA12.4 

Traceback (most recent call last):
  File "deploy/python/infer.py", line 1084, in <module>
    main()
  File "deploy/python/infer.py", line 1052, in main
    detector.predict_image(
  File "deploy/python/infer.py", line 406, in predict_image
    result = self.predict()
  File "deploy/python/infer.py", line 206, in predict
    self.predictor.run()
OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED. 
  [Hint: Please search for the error code(9) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /opt/paddle/paddle/paddle/fluid/operators/fused/conv_fusion_op.cu:500)
  [operator < conv2d_fusion > error]
  
  其他网络能正常推理，但ppyoloe不能。

**Comment by liu-jiaxuan** [comment]
您好，可以试一下使用PaddleX的推理命令，请参考[使用文档](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta/docs/tutorials/models/model_develop_tools.md#3-%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86)~
