### ISSUE TITLE
MOT跟踪预测和评估是否支持检测器的小目标切图拼图预测？

### ISSUE THREAD

**Issue by bang2003er** [PaddlePaddle/PaddleDetection#9112]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

任务目标：
小目标的MOT跟踪，使用切图拼图预测并跟踪轨迹

需求场景：
连续帧中物体很小

功能描述：
在`tools/infer_mot.py`和`tools/eval_mot.py`中支持`--slice_infer`等一系列参数

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by cuicheng01** [comment]
这个建议自己改下代码来实现呢？

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
