### ISSUE TITLE
mcmot对于不同的方式sde和jde，如何在训练的过程中一边训练一边eval？

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleDetection#9113]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

首先是sde，我看教程是直接使用detection的数据格式，那如何在训练过程中实现跟踪相关指数MOTA ， IDF1 ， HOTA之类的校验？
另外jde，教程里面[https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/docs/tutorials/data/PrepareMOTDataSet.md](url)
没有切分出eval数据，如何边训练边eval？

**Comment by changdazhou** [comment]
不支持边训练边eval的哈

**Comment by zouhan6806504** [comment]
> 不支持边训练边eval的哈

那这个如何选择好的模型？不怕overfitting？

**Comment by changdazhou** [comment]
MOT一般都是微调训练，通常选择最后一个模型来评估，如果担心漏掉最佳权重，可以使用脚本刷一下
