### ISSUE TITLE
https://github.com/PaddlePaddle/PaddleDetection.git，2.7，支持mlu配置吗？

### ISSUE THREAD

**Issue by fightingshao** [PaddlePaddle/PaddleDetection#9118]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

https://github.com/PaddlePaddle/PaddleDetection.git，2.7，支持mlu配置吗？具体是应用其中的ppyoloe模型，进行人体跟踪识别

**Comment by zhang-prog** [comment]
可以参考PaddleX模型列表（寒武纪），[链接](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta/docs/tutorials/models/support_mlu_model_list.md)，是支持 PP-YOLOE_plus 系列的

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
