### ISSUE TITLE
ppyoloe_seg 模型训练报错

### ISSUE THREAD

**Issue by zhangyubo0722** [PaddlePaddle/PaddleDetection#9120]
### 问题确认 Search before asking

- [ ] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

运行命令
python -m paddle.distributed.launch --gpus 0 tools/train.py -c configs/ppyoloe_seg/ppyoloe_seg_l_80e_coco.yml --eval
报错信息
![f55eaf9f44c26618fd57f19d426b4ba2](https://github.com/user-attachments/assets/2af481b2-9e1c-4e4d-b3fa-4c50d8ff0f68)

### 复现环境 Environment

-PaddlePaddle: 3.0.0b1
-CUDA: 11.8
-python: 3.10

### Bug描述确认 Bug description confirmation

- [ ] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/9121

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
