### ISSUE TITLE
飞桨产业模型选型工具数据上传报错

### ISSUE THREAD

**Issue by caopeizhi2** [PaddlePaddle/PaddleDetection#9126]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

https://www.paddlepaddle.org.cn/smrt
网页版，选择数据上传时，报错提示如下：
![Snipaste_2024-09-02_15-34-29](https://github.com/user-attachments/assets/c306d9fa-8ed1-4822-abc1-334c408a8cec)

cannot post /eda/upload 502'

### 复现环境 Environment

网页版链接
https://www.paddlepaddle.org.cn/smrt

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by TingquanGao** [comment]
收到，我找一下相关负责人

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by Tq-1** [comment]
请问解决了吗，现在还是有这个问题
