### ISSUE TITLE
安卓yolov8

### ISSUE THREAD

**Issue by wangqingpen** [PaddlePaddle/PaddleDetection#9128]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

现在框架在安卓可以部署yolov8吗

**Comment by zhangyubo0722** [comment]
PaddleSlim套件已经支持了yolov8的模型压缩，可以根据文档docs/zh_cn/deploy/deploy_cls_model_on_mobile_device.md尝试进行端侧部署

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
