### ISSUE TITLE
paddle detection 训练完layout_analysis 模型后无法是由 python tools/infer.py 推理

### ISSUE THREAD

**Issue by GoPark1995** [PaddlePaddle/PaddleDetection#9132]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

利用 cdla 数据微调了 picodet 中的 layout模型，训练结束后，
python tools/infer.py -c configs/picodet/legacy_model/application/layout_analysis/piao_picodet_lcnet_x1_0_layout.yml -o weights='output/best_model/model.pdparams' --output_dir=output_dir --draw_threshold=0.5 --infer_img='pptest/data/images/images_0_0.jpeg'
执行以上命令的时候出现，以下错误，
Traceback (most recent call last):
  File "/paddle/PaddleDetection/tools/infer.py", line 239, in <module>
    main()
  File "/paddle/PaddleDetection/tools/infer.py", line 235, in main
    run(FLAGS, cfg)
  File "/paddle/PaddleDetection/tools/infer.py", line 183, in run
    trainer.predict(
  File "/paddle/PaddleDetection/ppdet/engine/trainer.py", line 1026, in predict
    outs = self.model(data)
  File "/usr/local/lib/python3.10/dist-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/paddle/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 76, in forward
    outs.append(self.get_pred())
  File "/paddle/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 93, in get_pred
    bbox_pred, bbox_num = self._forward()
  File "/paddle/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 67, in _forward
    head_outs = self.head(fpn_feats, self.export_post_process)
  File "/usr/local/lib/python3.10/dist-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/paddle/PaddleDetection/ppdet/modeling/heads/pico_head.py", line 301, in forward
    return self.forward_eval(
  File "/paddle/PaddleDetection/ppdet/modeling/heads/pico_head.py", line 374, in forward_eval
    bboxes_reg_list = batch_distance2bbox(anchor_points,
  File "/paddle/PaddleDetection/ppdet/modeling/bbox_utils.py", line 573, in batch_distance2bbox
    x1y1 = -lt + points
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 8500, 2] and the shape of Y = [10105, 2]. Received [8500] in X is not equal to [10105] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ../paddle/phi/kernels/funcs/common_shape.h:73)
怎么解决这个问题呢？

### 复现环境 Environment

Linux
paddle detection realse/2.7
CUDA 12.4， cudnn 8.9

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by liuhongen1234567** [comment]
您好，可以提供一下具体的配置文件吗？另外，我下载了picodet 中的 预训练模型进行推理并没有报错，您那边用官方预训练模型进行推理也会报错吗？

**Comment by GoPark1995** [comment]
_BASE_: [
  '../../../../runtime.yml',
  '../../_base_/picodet_esnet.yml',
  '../../_base_/optimizer_100e.yml',
  '../../_base_/picodet_640_reader.yml',
]

pretrain_weights: /paddle/PaddleDetection/pptest/models/pretrained/picodet_lcnet_x1_0_fgd_layout_cdla.pdparams
weights: #output/picodet_lcnet_x1_0_layout/model_final
find_unused_parameters: True
use_ema: true
cycle_epoch: 10
snapshot_epoch: 10
epoch: 100

PicoDet:
  backbone: LCNet
  neck: CSPPAN
  head: PicoHead

LCNet:
  scale: 1.0
  feature_maps: [3, 4, 5]

metric: COCO
num_classes: 10

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: train.json
    dataset_dir: ./dataset/resume/
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: val.json
    dataset_dir: ./dataset/resume/

TestDataset:
  !ImageFolder
    anno_path: ./dataset/resume/val.json

worker_num: 8
eval_height: &eval_height 800
eval_width: &eval_width 608
eval_size: &eval_size [*eval_height, *eval_width]

TrainReader:
  sample_transforms:
  - Decode: {}
  - RandomCrop: {}
  - RandomFlip: {prob: 0.5}
  - RandomDistort: {}
  batch_transforms:
  - BatchRandomResize: {target_size: [[768, 576], [800, 608], [832, 640]], random_size: True, random_interp: True, keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_size: 48
  shuffle: true
  drop_last: true
  collate_batch: false

EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [800, 608], keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 8
  shuffle: false


TestReader:
  inputs_def:
    image_shape: [1, 3, 800, 608]
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [800, 608], keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: false
这是我在训练的时候使用的yaml
现在我重新拉下来 2.6/release 分支, 在这个分支执行相同的命令没有报错

**Comment by liuhongen1234567** [comment]
您好，可以pico_head.py文件中加入这几行，打印一下维度吗？需要修改的位置大概在360行左右
看上去像是预测框的维度没有对上，应该总和是10105。
![image](https://github.com/user-attachments/assets/2401ca1a-cda6-4383-87e0-056952424a30)
我这边输出结果是这样的。
![image](https://github.com/user-attachments/assets/a249a6a8-eb5f-4b9d-b319-a989a92b530d)

我在Paddle 2.7 上预测并没有出现这个问题，需要看一下8500 具体是怎么来的

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
