### ISSUE TITLE
量化yolov5

### ISSUE THREAD

**Issue by wangqingpen** [PaddlePaddle/PaddleDetection#9133]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如何使用PaddleYOLO/tools/post_quant.py对yolov5进行量化，没有找到其silm文件

**Comment by Sunting78** [comment]
您好 暂不支持

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
