### ISSUE TITLE
请问部署picodet到rv1126 npu平台必须要用picodet-npu那个模型吗

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#9135]
### 问题描述 Please describe your issue

请问部署picodet到rv1126 npu平台必须要用picodet-npu那个模型吗，使用通用的picodet模型会有什么问题吗

**Comment by LielinJiang** [comment]
可以试试用通用的 picodet 模型，在910B芯片上测试过。不过不确定rv1126 npu是否有问题

**Comment by Sunting78** [comment]
已回复

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
