### ISSUE TITLE
YOLOV3的下载路径与配置文件所给路径不同

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleDetection#914]
请问model zoo的文档中，YOLOV3的最后一个模型，模型链接为

> https://paddlemodels.bj.bcebos.com/object_detection/yolov3_r50vd_dcn_obj365_pretrained_coco.tar

但是后面给的配置文件中的模型链接为

> https://paddlemodels.bj.bcebos.com/object_detection/ResNet50_vd_dcn_db_obj365_pretrained.tar

请问这两个模型有什么区别么？如果是使用迁移学习，我应该使用哪个链接的模型呢？

**Comment by jerrywgz** [comment]
model zoo中的模型链接是根据配置文件在coco数据集上训练得到的结果，而配置文件中的模型链接是backbone在imagenet上的预训练模型用于coco上训练的。如果使用迁移学习建议直接使用model zoo中给出的coco数据集上模型，会有更好的效果
