### ISSUE TITLE
pp-shituv2主体检测模型运行到predictor_->Run()处导致arm64 Debian11板子重启

### ISSUE THREAD

**Issue by wenzhu2018** [PaddlePaddle/PaddleDetection#9141]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

PP-ShiTuv2的主体检测模型picodet的inference模型通过paddlelite opt工具转成nb模型放到RK3588 arm64板子上运行，运行时直接导致RK3588 Debian11系统重启；
用官方文档的量化nb模型运行正常，官方的量化是ppshituv2_lite_models_v1.0/mainbody_PPLCNet_x2_5_640_quant_v1.0_lite.nb 和general_PPLCNetV2_base_quant_v1.0_lite.nb，官方的文档里也只讲把export_model导出的inference模型用opt转换，并未涉及到主体检测模型的量化，查看代码也未看见主体检测的量化配置文件

### 复现环境 Environment

OS debian11
PaddleDetection: 2.7
PaddleClas-2.5.2
cuda 12.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by liu-jiaxuan** [comment]
您好，请确认一下ndk、paddle-lite版本是否都和文档要求的一致，以及文档中是否提到支持这个设备~

**Comment by wenzhu2018** [comment]
1、我是在RK3588 Debian11上运行的，paddle-lite试过V2.10rc、V2.12、V2.13rc，还自己在RK3588 Debian特意编译了预测库也不行，按照文档一步一凑的使用v2.10rc也不行，除了使用文档提供的量化模型，其它怎么操作都不行
2、我使用RK3588 的CPU，不涉及到它的NPU

**Comment by wenzhu2018** [comment]
代码运行到predictor_->Run() 系统重启

**Comment by wenzhu2018** [comment]
我两端的版本是一致的，PC机opt转换端和RK3588端的预测库是一致的，并且还试过直接在RK3588上使用opt-v2.13rc工具转换nb模型，使用v2.13rc的预测库，都一样的结果

**Comment by wenzhu2018** [comment]
我使用Deploy中的lite代码，在RK3588 Debian11上编译成可执行文件；模型使用picodet_s_320_coco_lcnet.pdparams，模型通过export_model.py、opt模型转换nb、convert_yml_to_json.py转换JSON，最后在板子上运行没有问题，并且图片能够被检测出结果

**Comment by wenzhu2018** [comment]
我看法是跟opt工具转换是不是没有关系，当然也有个奇怪地方，我自己inference模型在x86-64服务器上运行没有问题，但使用opt转换后就发生重启？这是什么问题？难道是预训练模型xxxxxxx.pdparams的问题？想不通

**Comment by liu-jiaxuan** [comment]
Hi，我们定位了下，这个应该不是paddleDetection的问题，应该是Paddle-Lite的问题，辛苦在那边提交一下issue~

**Comment by wenzhu2018** [comment]
Issue: 模型转换/使用（Model Issue）
您可以提问模型转换的使用报错等问题。You could use this template for reporting a model issue. If this doesn't look right, [choose a different type.](https://github.com/PaddlePaddle/Paddle-Lite/issues/new/choose)

@wenzhu2018
An owner of this repository has limited the ability to open an issue to users that are collaborators on this repository.
Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).

![b7a8b89f9800e1f67e243b2ef1f0cce](https://github.com/user-attachments/assets/eee1cd19-305d-47c4-a781-c753be348ea1)
