### ISSUE TITLE
人体mtmct保存结果时camera_ids越界

### ISSUE THREAD

**Issue by columbia617** [PaddlePaddle/PaddleDetection#9142]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

进行pphuman下的mtmct推理过程时，再save_mtmct_vis_results函数中出现越界问题
![image](https://github.com/user-attachments/assets/93f7436f-187a-46c4-b883-b7a67b6e7f24)
运行命令为： python3 deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_pphuman.yml --video_dir=/home/bml/storage/store_project/PaddleDetection/videos/phonecall --device=gpu
文件夹中共包含两个视频。
paddlepaddle-gpu 版本为2.3.2

**Comment by cuicheng01** [comment]
所有视频都会有这个问题吗？

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
