### ISSUE TITLE
接口文档

### ISSUE THREAD

**Issue by wangqingpen** [PaddlePaddle/PaddleDetection#9144]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

ppdet.engine 有没有接口文档，我想对视频流抽帧推理如何使用

**Comment by liuhongen1234567** [comment]
您好，您可以参考 tools\infer_mot.py 这个文件对视频流进行推理，或者直接将视频每一帧存储为图片。

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
