### ISSUE TITLE
Help on finding the config file of inference model ppyolov2_r50vd_dcn_365e_publaynet

### ISSUE THREAD

**Issue by WYY220062** [PaddlePaddle/PaddleDetection#9151]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi!
I would like to run the inference of model ppyolov2_r50vd_dcn_365e_publaynet to do document layout detection.
Find the inference model here https://github.com/PaddlePaddle/PaddleOCR/blob/main/ppstructure/docs/models_list.md
Can you point me the config file and corresponding sample code?
Thank you!

**Comment by zhangyubo0722** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/55bad87fffee251ae19592a1ac3df42906299e28/configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
