### ISSUE TITLE
ImportError: cannot import name 'in_dynamic_or_pir_mode' from 'paddle.framework'

### ISSUE THREAD

**Issue by SummerLam** [PaddlePaddle/PaddleDetection#9157]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://github.com/user-attachments/assets/bee60c89-fa5e-4b03-a87e-3e62c654dbff)
after executing the training process of rtdetrv2, i got the import error stating that 'in_dynamic_or_pir_mode' can not be imported from 'paddle.framework' , i tried to downgrade and upgrade paddle versions, but it didnt help. May i know how can i resolve the issue?

**Comment by cuicheng01** [comment]
Could you please tell me the versions of Paddle and PaddleDetection you are using?

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
