### ISSUE TITLE
关于怎样实现在Ai Studio 上公开的“基于关键点检测的摔倒识别”的实时在线监测。

### ISSUE THREAD

**Issue by LiyangFang3303** [PaddlePaddle/PaddleDetection#9159]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我用公开项目中的命令实现了对于视频文件的摔倒检测，但是试了很多方法也没有找到用摄像头的实时检测方法。
想问一下怎样实现，谢谢！

我注意到有人提过相同的issue,但是解决方法没有被公开。
这个是相似issue的链接：
https://github.com/PaddlePaddle/PaddleDetection/issues/5119

**Comment by liuhongen1234567** [comment]
您好，解决方案就在这个det_keypoint_unite_infer.py文件里面呀
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/python/det_keypoint_unite_infer.py#L193-L223
调用摄像头的话，就是在 cv2.VideoCapture()里面传 camera_id， 而不是传视频文件路径就可以了。
![image](https://github.com/user-attachments/assets/815c1b02-b8da-4f94-b5c8-a98ad1c25f31)

**Comment by LiyangFang3303** [comment]
@liuhongen1234567 
非常感谢您的回复，但是我试过之后还是不行。
如果单单是骨骼识别的话，确实是命令行里面改camera_id=0 就可以实时检测（用您提到的det_keypoint_unite_infer.py 或者是同一路径下的 keypoint_infer.py）。

但是用到动作识别的时候会有相机影像的弹窗不显示的现象，导致无法确认监测情况以及无法正常关闭摄像头。
我用到的命令如下：
`
python deploy/pipeline/pipeline.py --config deploy/pipeline/config/examples/infer_cfg_fall_down.yml --camera_id=0 --device=gpu
`

运行环境如下：
CUDA == 12.1
cuDNN == 8.9.6
python == 3.10
paddlepaddle-gpu == 2.6.1.post120 

非常感谢🙏

**Comment by liuhongen1234567** [comment]
您好，我重写了pipeline.py 这个脚本，您把原始的pipeline.py替换成我重写的应该就可以了。github 不支持上传py文件，我把脚本压缩成zip包了
[pipeline.zip](https://github.com/user-attachments/files/17406849/pipeline.zip)

**Comment by liuhongen1234567** [comment]
原始的pipeline文件为了加速视频的推理，会把视频读取到队列里，并启动多个进程，而摄像头不手动终止永远读不完，所有会一直卡在视频读取这个地方，所以不会显示摄像头影像。
![image](https://github.com/user-attachments/assets/68c469a0-60b6-4066-ad99-208cf317b290)

**Comment by LiyangFang3303** [comment]
@liuhongen1234567 感谢大神，试了一下可以正常显示和保存了。

多谢！🙏
