### ISSUE TITLE
请复现yolo10

### ISSUE THREAD

**Issue by cloudsurging** [PaddlePaddle/PaddleDetection#9161]
请复现yolo10，感觉是比较好的模型

**Comment by changdazhou** [comment]
在PaddleYOLO里边已经有了哈，因为一些协议的问题，不便放到DET套件中，可以移步PaddleYOLO仓库看下哈

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
