### ISSUE TITLE
PP-Vehicle不推理视频帧

### ISSUE THREAD

**Issue by CinnDeveloper** [PaddlePaddle/PaddleDetection#9165]
### 问题确认 Search before asking

- [ ] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

<img width="726" alt="微信图片_20241012125506" src="https://github.com/user-attachments/assets/30a0f87c-5acb-4535-901c-3e7ba4f9b472">
使用PaddleDetection 2.6.0 以及 PaddleDecetion 2.7.0都会出现同样的问题

**Comment by Sunting78** [comment]
您好，请提供一下具体的命令和环境信息，便于排查

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
