### ISSUE TITLE
混淆矩阵中错误的分类的缺陷如何确定是哪些图片贡献的特征

### ISSUE THREAD

**Issue by xillee** [PaddlePaddle/PaddleDetection#9166]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我有6个检出类别，其中有两个类别比较近似，相互之间有误检，且置信度比较低，因此我想确认图片的缺陷的检出置信度是由哪些图片贡献的，为什么会置信度比较低。

**Comment by Sunting78** [comment]
您好， 可以保存结果再过滤下低分框。--save_results=True

**Comment by xillee** [comment]
请问保存的低分框怎么用？低分框即为误检图片的贡献框吗？

**Comment by Sunting78** [comment]
不一定 可以把预测结果框和这张图的GT在进行同类iou的匹配 如果没有匹配到就是误检

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
