### ISSUE TITLE
训练过程中如何查看每个类别的Ap,混淆矩阵等验证数据

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleDetection#9168]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

训练过程中如何查看每个类别的Ap,混淆矩阵等验证数据

**Comment by Sunting78** [comment]
eval时加上--classwise

**Comment by xillee** [comment]
eval时加上--classwise 只能生成ap，混淆矩阵怎么生成？

**Comment by Sunting78** [comment]
目前不支持

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
