### ISSUE TITLE
请问一下，是不是在ImageNet上面准确率高的主干网络替换到PaddleDetection里面的模型中去，准确率一定会变高呀？

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PaddleDetection#917]
尊敬的开发者：
你好！
请问一下，是不是在ImageNet上面准确率高的主干网络替换到PaddleDetection里面的模型中去，准确率一定会变高呀？

期待你的回复！

**Comment by willthefrog** [comment]
原则上是这样，一般会有一定的收益，但是也要看模型。
