### ISSUE TITLE
量化训练时一大堆算子对不上

### ISSUE THREAD

**Issue by qiuzhewei** [PaddlePaddle/PaddleDetection#9173]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，
我正常训练picodet，一切都是正常的。
然后我想着量化训练一下，用的命令如下
`tools/train.py -c configs/picodet/picodet_s_320_coco_lcnet.yml --slim_config configs/slim/quant/picodet_s_quant.yml --eval`
出现了一大堆对不上的算子
<img width="1038" alt="截屏2024-10-17 11 31 58" src="https://github.com/user-attachments/assets/f1cd5d8e-7ca8-4f68-88b2-b5531d5bd5d5">

感觉像是权重对不上，我用文档中命令时，只有一些权重对不上，
`python tools/train.py -c configs/picodet/picodet_s_416_coco_lcnet.yml \
          --slim_config configs/slim/quant/picodet_s_416_lcnet_quant.yml --eval`
<img width="1086" alt="截屏2024-10-17 11 34 57" src="https://github.com/user-attachments/assets/ecdf41ed-21da-465a-948e-8029c9932171">
如果我想用320的small model的量化训练，该怎么改呢？

**Comment by zhangyubo0722** [comment]
将量化所使用的配置文件configs/slim/quant/picodet_s_416_lcnet_quant.yml，中的pretrain_weights模型权重为320的权重

**Comment by qiuzhewei** [comment]
谢谢解答，还有为什么量化得到的模型大小和不量化得到的模型大小差不多，都是4.5M左右？

**Comment by zhangyubo0722** [comment]
请问怎么看的是否使用量化训练得到的不同权重大小呢，可以截下图

**Comment by qiuzhewei** [comment]
不是权重大小，是看得到的模型在硬盘上所占空间的大小。`int8`得到的模型不是应该是`float16`的一半嘛？但是我看得到的模型基本大小一样

**Comment by zhangyubo0722** [comment]
量化训练模型大小和存储类型有关系，和是不是量化不一定一样的，如果需要对模型进行压缩，参考这个文档https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/auto_compression

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
