### ISSUE TITLE
请问使用VOC数据如何获取precision和recall，我已经查遍所有issue，没有理想结果

### ISSUE THREAD

**Issue by TheQYQ** [PaddlePaddle/PaddleDetection#9183]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

请问使用VOC数据如何获取precision和recall，我已经查遍所有issue，没有理想结果

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by QianYing-LYG** [comment]
类似于加--classwise会报错

**Comment by QianYing-LYG** [comment]
更改pr曲线打印也没结果显示

**Comment by QianYing-LYG** [comment]
我是真的麻了

**Comment by QianYing-LYG** [comment]
最麻的一点是21年就有人反馈想看precision和recall数值了，为何现在还没集成

**Comment by QianYing-LYG** [comment]
我还搞不懂一点，非要把rtdetr的v2版本强行绑定在这里干嘛呢，不如直接单独放在RTDETR里，就是为了哪个才走上这个不归路🤷‍♂️

**Comment by liuhongen1234567** [comment]
您好，您的issue和这个issue很相似，可以参考一下它的解决方案。https://github.com/PaddlePaddle/PaddleDetection/issues/7258

**Comment by QianYing-LYG** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/8913#issuecomment-2425404408，问题已经解决，这是我的一个处理方案

**Comment by TheQYQ** [comment]
> 您好，您的issue和这个issue很相似，可以参考一下它的解决方案。#7258
你好，问题已解决，欢迎引用我的这个回答去教他们如何获取理想的Precision和Recall😊
https://github.com/PaddlePaddle/PaddleDetection/issues/8913#issuecomment-2425404408
