### ISSUE TITLE
PaddleDetection报错：FatalError: `Segmentation fault` is detected by the operating system.

### ISSUE THREAD

**Issue by doubleEfourier** [PaddlePaddle/PaddleDetection#9186]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在使用PaddleDetection的过程中遇到过好多次
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   deflateReset

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1728999528 (unix time) try "date -d @1728999528" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x79f100000000) received by PID 2417453 (TID 0x79f2a9006600) from PID 0 ***]

段错误 (核心已转储)

使用Paddledetection提供的多目标追踪测试代码时报错，之前将ppyoloe的backbone替换为swin后也报这个错。其他大部分代码正常使用时，均不会产生此问题。

请问我的问题在哪儿？在网络上实在没找到该问题的解答。

我的Paddle版本2.6   PaddleDetection2.7  CUDA11.3

**Comment by Sunting78** [comment]
您好 请给出具体的执行命令 便于复现

**Comment by doubleEfourier** [comment]
报错的情况有点多，这也是今天发现的情况。
在github上的报错，按照官方提供的教程https://aistudio.baidu.com/projectdetail/3022582，执行到这一步时（没有训练，直接下载的训练权重进行测试）python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=output/fairmot_dla34_30e_1088x608.pdparams --image_dir=dataset/mot/MOT16/images/test/MOT16-01/img1  --save_videos 报错上述错误。这个问题已经得到了解决，将2.7版本的ppdetection转为2.5版本后可正常使用。
最后，如果将ppyoloe的backbone替换为swin也报上述错误，具体执行代码，参照ppyoloe-develop configs下的swin文件
运行&nbsp; ubuntu20.04&nbsp; &nbsp;paddle2.6&nbsp; cuda11.2







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月23日(星期三) 晚上8:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] PaddleDetection报错：FatalError: `Segmentation fault` is detected by the operating system. (Issue #9186)





 
您好 请给出具体的执行命令 便于复现

**Comment by Sunting78** [comment]
您好，我们跟进下，同时可以在框架提下issue，推理报错应该是底层算子的问题。

**Comment by doubleEfourier** [comment]
收到，感谢！所以这个问题能否解决，以后又该如何避免。还是只能通过更换旧版本回避？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月28日(周一) 中午11:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] PaddleDetection报错：FatalError: `Segmentation fault` is detected by the operating system. (Issue #9186)




 
您好，我们跟进下，同时可以在框架提下issue，推理报错应该是底层算子的问题。

**Comment by Sunting78** [comment]
暂时可以使用旧版本。因为目前框架为beta版，发布稳定版本会修复。

**Comment by doubleEfourier** [comment]
谢谢，最后再请问您这里提到的旧版本。是指使用旧的PaddlePaddle深度学习框架，还是使用旧的PaddleDetection等开发套件？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月28日(周一) 下午2:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] PaddleDetection报错：FatalError: `Segmentation fault` is detected by the operating system. (Issue #9186)




 
暂时可以使用旧版本。因为目前框架为beta版，发布稳定版本会修复。

**Comment by Sunting78** [comment]
框架

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
