### ISSUE TITLE
paddleDetection如何与yolov8进行整合

### ISSUE THREAD

**Issue by kenvinsuxun** [PaddlePaddle/PaddleDetection#9187]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

paddleDetection如何与yolov8进行整合？请专家写出详细的整合过程，谢谢

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by kenvinsuxun** [comment]
paddleDetection如何与yolov8进行整合？请专家写出详细的整合过程，谢谢

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/tree/develop/configs/yolov8

**Comment by Sunting78** [comment]
您好 YOLOv8在 https://github.com/PaddlePaddle/PaddleYOLO 仓库

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
