### ISSUE TITLE
PaddleDetection车辆逆行检测模块cudnn版本兼容问题

### ISSUE THREAD

**Issue by 15621008556** [PaddlePaddle/PaddleDetection#9189]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

想问一下这个使用cudnn哪个版本能运行？
<img width="884" alt="05d1015de2124c77fcd990113e5789b" src="https://github.com/user-attachments/assets/805098b3-f0dd-4b88-bea8-f2266cbc9094">
我现在使用的是cuda11.8 cudnn8.9.7.29 paddlepaddle-gpu==3.0.0b1
<img width="1198" alt="ca2190a5f7fecf7fd06a58a45e1687b" src="https://github.com/user-attachments/assets/acd55d52-d12b-431d-aa87-e2e9ca7a07a7">

**Comment by Bobholamovic** [comment]
建议使用cuDNN 8.6～

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
