### ISSUE TITLE
picodet_xs包含后处理的脚本

### ISSUE THREAD

**Issue by qiuzhewei** [PaddlePaddle/PaddleDetection#9195]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，
我在使用picodet_xs模型，已经成功转成mnn模型（不包含后处理的），一致性也初步校验成功，按照[教程](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/third_engine/demo_mnn/README.md)编译了可执行文件picodet-mnn，但是用picodet-mnn推理发现结果和我用./ModuleBasic.out出来的结果对不上（./ModuleBasic.out出来的结果和onnx出来的结果能对得上），想问下是为什么呢？
或者有计划推出包含后处理的mnn c++代码吗？可能会更方便一点

**Comment by TingquanGao** [comment]
目前没有计划。想问下为什么想使用mnn模型呢？也建议了解下[PaddleX](https://github.com/paddlepaddle/paddlex)，支持多种预测部署方式，[目标检测模型](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/module_usage/tutorials/cv_modules/object_detection.md)

**Comment by qiuzhewei** [comment]
因为以前版本的原因，目前大概只支持端侧mnn部署。我设置导出MNS的时候，发现推理所得的bbox数值都为nan，感觉问题好像出在paddle2onnx脚本默认执行了multiclass_nms3这个函数，但是我自己重写NMS的方法也不行，有什么方法可以解决这个问题吗？

**Comment by TingquanGao** [comment]
paddlex2onnx目前是存在兼容性问题，我们也在计划对paddlex2onnx进行适配性升级。

**Comment by qiuzhewei** [comment]
好的，谢谢。目前通过不导出MNS但是导出后处理，然后自己C++实现MNS，可以正常用MNN推理。

**Comment by TingquanGao** [comment]
好的，那该issue先关闭了，我们也会尽快启动paddlex2onnx的升级适配。如仍有问题，可以reopen或new issue。
