### ISSUE TITLE
RTDETR - RBox

### ISSUE THREAD

**Issue by shreejalt** [PaddlePaddle/PaddleDetection#9196]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi, 
i want to ask that does this repository support oriented bounding box (rotated box) training with RTDETR?

**Comment by zhangyubo0722** [comment]
This repository does not support the rotated bounding box detection task based on RTDETR.

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
