### ISSUE TITLE
ppyolo+s转onnx

### ISSUE THREAD

**Issue by qiuzhewei** [PaddlePaddle/PaddleDetection#9198]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，
我训练了一个ppyolo+s的模型，准备把模型转成onnx格式，在使用export_model.py的时候我显示指定了export.nms=False，但是用生成的模型转onnx的时候还是提示
` multiclass_nms3_0.tmp_1] [WARNING] Due to the operator multiclass_nms3, the exported ONNX model will only supports inference with input batch_size == 1.`
另外我在runtime.yml里面手动改了也没用，NMS模型还是包含了。但是之前转picodet的时候就没这个问题，是转onnx的时候只能用batchsize=1进行推理吗？

**Comment by qiuzhewei** [comment]
solved

**Comment by myrainbowliuying** [comment]
> solved

请问怎么解决的，我也遇到了

**Comment by qiuzhewei** [comment]
> > solved
> 
> 请问怎么解决的，我也遇到了

转模型时配置文件中的PPYOLOEHead下面加一行
`exclude_nms: True`
