### ISSUE TITLE
PP-YOLOE训练voc格式数据集

### ISSUE THREAD

**Issue by stephen-TT** [PaddlePaddle/PaddleDetection#9200]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PP-YOLOE训练voc格式数据集咋没有配置文件，全是coco数据集的配置文件
![image](https://github.com/user-attachments/assets/0b709e13-8b6f-4f7a-a2f7-d0cb31767222)

**Comment by TingquanGao** [comment]
暂未提供VOC格式的配置文件。建议尝试使用PaddleX，PaddleX支持VOC格式数据集转COCO格式，相关[文档](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/module_usage/tutorials/cv_modules/object_detection.md#413-%E6%95%B0%E6%8D%AE%E9%9B%86%E6%A0%BC%E5%BC%8F%E8%BD%AC%E6%8D%A2%E6%95%B0%E6%8D%AE%E9%9B%86%E5%88%92%E5%88%86%E5%8F%AF%E9%80%89)，同时PaddleX支持丰富的目标检测模型，可以更简单地完成模型开发。

**Comment by stephen-TT** [comment]
好的，明白，谢谢
