### ISSUE TITLE
为啥感觉NMS不起作用

### ISSUE THREAD

**Issue by leslie2046** [PaddlePaddle/PaddleDetection#9201]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference

### Bug描述 Describe the Bug

CUDA_VISIBLE_DEVICES=0 python tools/infer.py -c ${config} -o weights=${weights} --infer_img=demo_coco1/r65172_20240611104609.png --draw_threshold=0.1
![r65172_20240611104609 (4)](https://github.com/user-attachments/assets/5bb460e1-e90a-49a9-b7f8-8bd1b3dd282d)
如图所示，左边这个人有重复框，应该可以被NMS消除掉
使用的模型：https://paddledet.bj.bcebos.com/models/ppyoloe_plus_crn_s_80e_coco.pdparams
配置文件：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/ppyoloe/_base_/ppyoloe_plus_crn.yml

### 复现环境 Environment

- paddle:paddlepaddle-gpu         2.4.2
- OS:centos 7.9
- python:3.9.19
- PaddleDetection: 2.6.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by TingquanGao** [comment]
nms只会合并同一类别的重复检测框，你这个case看起来不是同一类别，因为框线的颜色是和类别一致的，你这里看起来是黄色和蓝色。

**Comment by leslie2046** [comment]
那么我这种一个人出现两个不同类别的框是正常的吗，如何消除呢

**Comment by TingquanGao** [comment]
可以将预测结果打印出来看下，蓝色框这个是什么类别。另外你用的权重是官方提供的吗？还是自己训练的，是不是模型训练的时候类别有问题。

**Comment by leslie2046** [comment]
确实是不同类别，这是用官方的权重https://paddledet.bj.bcebos.com/models/ppyoloe_plus_crn_s_80e_coco.pdparams，在我自己的数据集上微调的。
所以如果是不同类别的重复框，应该是用score阈值来尝试消除是吗

**Comment by TingquanGao** [comment]
是的，可以用设置score阈值屏蔽
