### ISSUE TITLE
请问ppyoloe支持多少并发呢？为什么我python部署模型之后三个并发就容易出错呢？

### ISSUE THREAD

**Issue by yuluzhong** [PaddlePaddle/PaddleDetection#9206]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问ppyoloe支持多少并发呢？为什么我python部署模型之后三个并发就容易出错呢？

**Comment by cuicheng01** [comment]
请问你是怎么部署的呢？

**Comment by yuluzhong** [comment]
使用flask python接口，调用deploy/python/infer.py内的predict_image函数

**Comment by cuicheng01** [comment]
哦哦，所以是出的什么错呢？

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
