### ISSUE TITLE
如何修改PaddleDetection模型默认缓存目录

### ISSUE THREAD

**Issue by chccc1994** [PaddlePaddle/PaddleDetection#9209]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

默认缓存目录为C:\Users\用户名\.cache\paddle，应为包含中文一直保存，如何修改PaddleDetection模型默认缓存目录?

试过以下图上的方法，无效。
![image](https://github.com/user-attachments/assets/2ca083b8-8b15-4cb3-b643-6a9dcc036dd1)

**Comment by Sunting78** [comment]
import tempfile
tempfile.tempdir = ‘/path/to/your/tmp’
