### ISSUE TITLE
在分析待剪枝参数敏感度时，精度损失的比例应该如何确定？

### ISSUE THREAD

**Issue by llzhaoshuo** [PaddlePaddle/PaddleDetection#921]
官方解释如下：
sen={"weight_0":
   {0.1: 0.22,
    0.2: 0.33
   },
 "weight_1":
   {0.1: 0.21,
    0.2: 0.4
   }
}
其中，weight_0是卷积层参数的名称，sensitivities['weight_0']的value为剪裁比例，value为精度损失的比例。
我的问题是：应该如何确定精度损失的比例？根据什么确定？
（目前敏感度信息已经分析完毕，生成了.data文件和nohup.out文件）

**Comment by willthefrog** [comment]
呃，这个是根据你的需求定的吧，你可以接受多少精度损失就按照相应的比例剪裁。

**Comment by llzhaoshuo** [comment]
> 呃，这个是根据你的需求定的吧，你可以接受多少精度损失就按照相应的比例剪裁。

通过load_sensitivities(sensitive.data)函数输出如下内容：
{'yolo_block.0.0.0.conv.weights': {0.1: -0.0005453223663611001, 0.2: -0.003282504558881373, 0.3: -0.0036650633988198813, 0.4: -0.003568146887477337, 0.5: -0.005240778256436158, 0.6: -0.006350744553538829, 0.7: -0.007947089794412294, 0.8: -0.007368732393329922, 0.9: -0.0061676859674113784}, 'yolo_block.0.0.1.conv.weights': {0.1: -0.0008443315888817694, 0.2: -0.0009101529463672893, 0.3: -0.00134855980339212, 0.4: -0.003330728682603868, 0.5: -0.002924768381053371, 0.6: -0.004994257730027242, 0.7: -0.007581739868061786, 0.8: -0.011011113661661966, 0.9: -0.013684957317764554}, 'yolo_block.0.1.0.conv.weights': {0.1: 0.00031357337849815143, 0.2: -0.0006176809907746786, 0.3: -0.0009978879372712825, 0.4: -0.002285549703484568, 0.5: -0.0042006747756593976, 0.6: -0.005108572020809096, 0.7: -0.004622393060949869, 0.8: -0.006189649400064672, 0.9: -0.008340713923637838}, 'yolo_block.0.1.1.conv.weights': {0.1: -0.00025776406307472096, 0.2: -0.0009111631368757175, 0.3: -0.002385535036478402, 0.4: -0.004598569810020172, 0.5: -0.0048639831704595385, 0.6: -0.007118798847679349, 0.7: -0.007969538884155122, 0.8: -0.008322225685413352, 0.9: -0.00962987604986765}, 'yolo_block.0.2.conv.weights': {0.1: 0.0005167088176566017, 0.2: 0.019781054160898464, 0.3: 0.024414504922905412, 0.4: 0.1271608053399353, 0.5: 0.0671295750860453, 0.6: 0.00420357658898771, 0.7: 8.629408254211854e-06, 0.8: -0.002600958443826056, 0.9: 0.0186174387665794}, 'yolo_block.0.tip.conv.weights': {0.1: -2.297806792594254e-05, 0.2: -5.9266542141139197e-05, 0.3: -0.00010707479725553337, 0.4: -0.00022241813908087575, 0.5: -0.0002119666362238675, 0.6: -0.00011798700882354517, 0.7: 0.0007122974281265763, 0.8: 0.004586086866361084, 0.9: 0.017196654916911882}, 'yolo_block.1.0.0.conv.weights': {0.1: 0.002311647237875514, 0.2: 0.005760003212025428, 0.3: 0.024031977306313936, 0.4: 0.06547719642810411, 0.5: 0.12740189468589058, 0.6: 0.1636962068044752, 0.7: 0.44742852734077637, 0.8: 0.5468770373231642, 0.9: 0.5151381662651678}, 'yolo_block.1.0.1.conv.weights': {0.1: 0.00027028863408646534, 0.2: 0.0016859656351768167, 0.3: 0.005967328154611801, 0.4: 0.009244050756856277, 0.5: 0.023790114288853435, 0.6: 0.03900230496633352, 0.7: 0.06358574437996516, 0.8: 0.29086611865803, 0.9: 0.5520129182580619}, 'yolo_block.1.1.0.conv.weights': {0.1: -0.002205313447156915, 0.2: -0.0005367238036239038, 0.3: 0.0003093945816126907, 0.4: 0.0067767573720166245, 0.5: 0.02063925816549448, 0.6: 0.04648277751353269, 0.7: 0.08734967042671504, 0.8: 0.15360019131758898, 0.9: 0.5211196066107244}, 'yolo_block.1.1.1.conv.weights': {0.1: 6.81523147745025e-05, 0.2: 0.0007950845389860326, 0.3: 0.0011297154990710589, 0.4: 0.0012785861190966578, 0.5: 0.0011575300195564857, 0.6: 0.001481856382649666, 0.7: 0.012818692218413818, 0.8: 0.3152825566300907, 0.9: 0.6812629768944739}, 'yolo_block.1.2.conv.weights': {0.1: 0.00033593404396524315, 0.2: -0.0004877316687863055, 0.3: 0.01164157631646938, 0.4: 0.009731658824310336, 0.5: 0.011920560198939084, 0.6: 0.013547201363572018, 0.7: 0.02724717581540607, 0.8: 0.170275998619336, 0.9: 0.5896570665781601}, 'yolo_block.1.tip.conv.weights': {0.1: -5.099977669057084e-05, 0.2: 0.004086115459573943, 0.3: 0.007729517819311687, 0.4: 0.02044031688239392, 0.5: 0.03728456103021912, 0.6: 0.07418786071462258, 0.7: 0.1184479728853756, 0.8: 0.18486174162696153, 0.9: 0.25686620033157487}, 'yolo_block.2.0.0.conv.weights': {0.1: 0.0008953875637137447, 0.2: 0.0010460969429742252, 0.3: 0.001150611635794141, 0.4: 0.001607990246066146, 0.5: 0.0015218590207464048, 0.6: 0.0011135280767458732, 0.7: 0.0013739442969559063, 0.8: 0.0010562495546561721, 0.9: 0.0008326186055371164}, 'yolo_block.2.0.1.conv.weights': {0.1: -2.210346285150042e-07, 0.2: -2.210346285150042e-07, 0.3: -2.210346285150042e-07, 0.4: -4.5015581274557153e-07, 0.5: -4.5015581274557153e-07, 0.6: -4.5015581274557153e-07, 0.7: -4.5015581274557153e-07, 0.8: -6.793693286561221e-07, 0.9: -6.793693286561221e-07}, 'yolo_block.2.1.0.conv.weights': {0.1: 3.162419684963165e-05, 0.2: 5.698184160941372e-06, 0.3: 4.11479876071719e-06, 0.4: 0.0001563728253979323, 0.5: 0.0001783681766978109, 0.6: 4.445458154426689e-05, 0.7: -4.5015581274557153e-07, 0.8: -6.793693286561221e-07, 0.9: -6.793693286561221e-07}, 'yolo_block.2.1.1.conv.weights': {0.1: 0.00176741150151977, 0.2: 0.0020242363467028, 0.3: 0.0015844190881157065, 0.4: 0.001762125677222056, 0.5: 0.002234399339396509, 0.6: 0.001736790871885124, 0.7: 0.0016887421293458114, 0.8: 0.0015936660557577342, 0.9: 0.0010936001098096858}, 'yolo_block.2.2.conv.weights': {0.1: -2.210346285150042e-07, 0.2: -2.210346285150042e-07, 0.3: -2.210346285150042e-07, 0.4: -2.210346285150042e-07, 0.5: -2.210346285150042e-07, 0.6: -4.5015581274557153e-07, 0.7: 0.0007550906804864384, 0.8: 0.001080045707460552, 0.9: 0.0010711045335488605}, 'yolo_block.2.tip.conv.weights': {0.1: -2.210346285150042e-07, 0.2: 7.99427971395138e-09, 0.3: 7.99427971395138e-09, 0.4: 2.3693096788230065e-07, 0.5: 6.945279060940821e-07, 0.6: 9.231882673629405e-07, 0.7: 8.848651868274857e-05, 0.8: 0.0010798933660547685, 0.9: 0.001137136523898193}}
这里的负数知道是啥意思吗

**Comment by willthefrog** [comment]
负数代表mAP提升了

**Comment by llzhaoshuo** [comment]
> 负数代表mAP提升了

那是应该越小越好吗

**Comment by llzhaoshuo** [comment]
> 负数代表mAP提升了

以第一个卷积层为例，{'yolo_block.0.0.0.conv.weights': {0.1: -0.0005453223663611001, 0.2: -0.003282504558881373, 0.3: -0.0036650633988198813, 0.4: -0.003568146887477337, 0.5: -0.005240778256436158, 0.6: -0.006350744553538829, 0.7: -0.007947089794412294, 0.8: -0.007368732393329922, 0.9: -0.0061676859674113784}，剪枝率设为多少比较好？

又有正数又有负数的情况下，比如yolo_block.2.2.conv.weights': {0.1: -2.210346285150042e-07, 0.2: -2.210346285150042e-07, 0.3: -2.210346285150042e-07, 0.4: -2.210346285150042e-07, 0.5: -2.210346285150042e-07, 0.6: -4.5015581274557153e-07, 0.7: 0.0007550906804864384, 0.8: 0.001080045707460552, 0.9: 0.0010711045335488605}剪枝率设为多少比较合理呢？
