### ISSUE TITLE
作者您好，咨询pphuman的使用问题

### ISSUE THREAD

**Issue by funny000** [PaddlePaddle/PaddleDetection#9215]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在使用pphuman做人流检测，请问怎么从paddleDetecttion中把pphuman单独抽出来封装成服务，返回一个推流的地址？

**Comment by TingquanGao** [comment]
抱歉，目前尚不支持。可以详细说下您的需求吗？我们会评估是否安排在后续支持。

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
