### ISSUE TITLE
如何基于K8S paddlejob分布式训练？有相关脚本可以参考吗

### ISSUE THREAD

**Issue by njflove** [PaddlePaddle/PaddleDetection#9216]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如何基于kubeflow paddlejob训练 paddleDetection，有没有可以参考的脚本？fleetrun命令中--ips因为pod是实时创建的，无法获取到。

**Comment by TingquanGao** [comment]
目前没有相关示例代码

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
