### ISSUE TITLE
ValueError: (InvalidArgument) Each dimension value of 'shape' in ReshapeOp must not be negative except one unknown dimension. 

### ISSUE THREAD

**Issue by UsersNGT** [PaddlePaddle/PaddleDetection#9219]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

用2.6版本的paddleDection代码，训练picodet，用自己数据集，分类为7，只修改了coco_dataset.yaml 中路径和picodet_m_416_coco_lcnet.yml中的numclasses 

### 复现环境 Environment

-OS:Ubantu
-paddlepaddle:2.3.2
-paddleDection:2.6
-cudnn:cuDNN Version: 8.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by UsersNGT** [comment]
![image](https://github.com/user-attachments/assets/5dcc0deb-91c2-44cb-9477-f3081e021fb5)
我现在解决这个问题了，将paddlepaddle重装成2.5.1就能运行了 ，不知道哪里出现的问题，反正能运行了。

**Comment by zhangyubo0722** [comment]
高版本的paddlepaddle会对模型数据类型和形状做检查，此类问题在高版本PaddleDetection分支已修复，也可以切换到2.8分支
