### ISSUE TITLE
请问一下，object detection的fine_grained_loss是什么？

### ISSUE THREAD

**Issue by whjdark** [PaddlePaddle/PaddleDetection#922]
细粒度损失吗？能否提供一下论文出处。

**Comment by FDInSky** [comment]
这是ppdet提供的loss吗？@whjdark

**Comment by heavengate** [comment]
`fine_grained_loss`是ppdet提供的一个用paddle op，如`slice` `abs` `sigmoid_cross_entropy`等同用op组装实现的YOLOv3模型的loss，对应是的Paddle有提供`paddle.fluid.layers.yolov3_loss`这个OP直接封装实现了YOLOv3模型的loss，二者底层计算逻辑和运算精度是一致的，只不过`paddle.fluid.layers.yolov3_loss`调用方便，内部实现也深度优化过，而`fine_grained_loss`则便于用户学习或者修改loss
用法可见文档：https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/tutorials/GETTING_STARTED_cn.md
里“使用Paddle OP组建的YOLOv3损失函数训练YOLOv3”小节
