### ISSUE TITLE
按照安装说明中的步骤已经安装好并提示安装成功，但是执行代码时又提示未安装该模块，具体看截图

### ISSUE THREAD

**Issue by kyzhouxu** [PaddlePaddle/PaddleDetection#9223]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

![123](https://github.com/user-attachments/assets/f556e10c-bdc7-4315-b57f-82d3d9522010)

### 复现环境 Environment

win10  conda安装的paddle2.6，Python版本为3.9.20

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by liu-jiaxuan** [comment]
您可以使用[PaddleX](https://github.com/PaddlePaddle/PaddleX)来使用PaddleDetection，安装和使用都更快捷方便~

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
