### ISSUE TITLE
paddledetection C++端部署deepsort

### ISSUE THREAD

**Issue by 18325391772** [PaddlePaddle/PaddleDetection#9224]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

sde的cpp中加载模型部分未实现，请问在哪里能下载图片中这部分内容
![20241126181741](https://github.com/user-attachments/assets/436d397d-8f88-4d7d-875a-37577ada687d)

**Comment by liu-jiaxuan** [comment]
Hi，请试下[PaddleX](https://github.com/PaddlePaddle/PaddleX)

**Comment by 18325391772** [comment]
嗯嗯，paddleX没看到目标跟踪模块

**Comment by 18325391772** [comment]
> Hi，请试下[PaddleX](https://github.com/PaddlePaddle/PaddleX)
嗯嗯，paddlex没看到deepsort跟踪算法模块。

**Comment by liu-jiaxuan** [comment]
Hi，我跟负责开发的同学确认了一下，这部分确实暂未支持，可以先使用下其他跟踪模块（例如卡尔曼滤波）

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
