### ISSUE TITLE
计算模型参数量和计算量

### ISSUE THREAD

**Issue by butn345** [PaddlePaddle/PaddleDetection#9226]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问怎么计算rt-detr的参数量和计算量。您在README中提到的方法无法正确执行，我想详细了解一下计算过程。

**Comment by lyuwenyu** [comment]
具体啥问题呢？

**Comment by butn345** [comment]
您给出的代码中使用`paddle.flops(model, None, blob, custom_ops=None, print_detail=False)`来统计计算量，但是在paddle的API文档中给出的flops有4个参数`paddle.flops(net, input_size, custom_ops=None, print_detail=False)`。直接使用您给的代码会报参数
数量错误。

**Comment by lyuwenyu** [comment]
在你本地安装的paddle源码里找到这个flops的函数；然后修改成下面
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/hapi/dynamic_flops.py#L40

```python

def flops(
    net: Layer | Program,
    input_size: list[int],
    blob=None,
    custom_ops: _CustomOpsAlias | None = None,
    print_detail: bool = False,
) -> int:
    if isinstance(net, nn.Layer):
        # If net is a dy2stat model, net.forward is StaticFunction instance,
        # we set net.forward to original forward function.
        _, net.forward = unwrap_decorators(net.forward)
        if blob is None:
            inputs = paddle.randn(input_size)
        else:
            inputs = blob
        return dynamic_flops(
            net, inputs=inputs, custom_ops=custom_ops, print_detail=print_detail
        )
    elif isinstance(net, paddle.static.Program):
        return static_flops(net, print_detail=print_detail)
    else:
        warnings.warn(
            "Your model must be an instance of paddle.nn.Layer or paddle.static.Program."
        )
        return -1
```

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
