### ISSUE TITLE
在预测部署的时候，为什么我打开Cmakelist 就这样报错?而且进行了后续操作也无用

### ISSUE THREAD

**Issue by Stillremains** [PaddlePaddle/PaddleDetection#923]
![image](https://user-images.githubusercontent.com/48147367/84362018-20970600-abff-11ea-903c-e01e0f9bc2ac.png)

**Comment by Stillremains** [comment]
![image](https://user-images.githubusercontent.com/48147367/84362432-d19da080-abff-11ea-93b1-e1975f706e44.png)
进行库的添加 全部生成后

**Comment by Channingss** [comment]
@Stillremains cudnnn.lib需要copy到cuda的lib路径下面

**Comment by Stillremains** [comment]
> @Stillremains cudnnn.lib需要copy到cuda的lib路径下面

![image](https://user-images.githubusercontent.com/48147367/84366364-4c1cef00-ac05-11ea-81e4-23fc1ced1028.png)
这个步骤肯定是做了的 还用GPU训练过呢 你看看我这样对不对啊
![image](https://user-images.githubusercontent.com/48147367/84366578-98682f00-ac05-11ea-92e4-3e90c1f75a61.png)

**Comment by Channingss** [comment]
@Stillremains 现在报错是cudart了。

**Comment by Channingss** [comment]
@Stillremains 路径需要指定到lib所在的根目录，还差一级x64

**Comment by Stillremains** [comment]
> @Stillremains 路径需要指定到lib所在的根目录，还差一级x64

没用的 我刚开始也是指定了X64 现在换回来 重新 加载 生成 同样的结果 
![image](https://user-images.githubusercontent.com/48147367/84369859-10d0ef00-ac0a-11ea-8a55-e6a5a1abe170.png)

**Comment by Channingss** [comment]
@Stillremains 配置选项下面是不是有CUDNN_LIB，到这里指定cudnn.lib吧

**Comment by Stillremains** [comment]
> @Stillremains 配置选项下面是不是有CUDNN_LIB，到这里指定cudnn.lib吧

没有的 
![image](https://user-images.githubusercontent.com/48147367/84389731-17229380-ac29-11ea-8309-c8aa7ccb737b.png)
![image](https://user-images.githubusercontent.com/48147367/84389760-21dd2880-ac29-11ea-837f-f307bd482f60.png)
我在想会不会是这个有问题呢
![image](https://user-images.githubusercontent.com/48147367/84389798-2f92ae00-ac29-11ea-90b0-01c75049dd7b.png)

**Comment by Channingss** [comment]
请问是拉的哪个分支，建议使用release/0.3

**Comment by Stillremains** [comment]
> 请问是拉的哪个分支，建议使用release/0.3

0.3  +VS2019

**Comment by Channingss** [comment]
CmakeList里面确认下是否有CUDNN_LIB变量？

**Comment by Stillremains** [comment]
> CUDNN_LIB

![image](https://user-images.githubusercontent.com/48147367/84460091-99e43680-ac9b-11ea-9cb7-1bf5f8fd5ed2.png)

**Comment by Stillremains** [comment]
我是CUDA10.0+CUDNN7.65

**Comment by Channingss** [comment]
看下https://github.com/PaddlePaddle/PaddleDetection/blob/fe23f0dcf3db7e91eb068101eca8b2f99b01971c/deploy/cpp/CMakeLists.txt#L12，在这里手动设置下cudnn的路径看

**Comment by Stillremains** [comment]
手动设置了下  出现了新错误 说几个文件没找到 
![image](https://user-images.githubusercontent.com/48147367/84460619-fe53c580-ac9c-11ea-8d91-6a957565cf93.png)
![image](https://user-images.githubusercontent.com/48147367/84460661-1aeffd80-ac9d-11ea-9d55-711e98737844.png)

**Comment by Stillremains** [comment]
加个qq也不错吧 好久没解决这个问题有点焦灼/，，，，，，，我qq32488484

**Comment by xiegegege** [comment]
@Stillremains 请问你有解决这个问题吗？给你我这的参数设置参考下吧
<img width="873" alt="7953c26e619754eea57e0a5b40e27ff3" src="https://user-images.githubusercontent.com/46314656/84485392-aafa6b00-acce-11ea-95a4-e851ff79f3f4.png">
<img width="868" alt="dfae98ae0bc12b122291460da7565f2e" src="https://user-images.githubusercontent.com/46314656/84485444-bc437780-acce-11ea-8f24-f2265ac58a0c.png">
就用release/0.3分支代码，不用改代码，直接这样设置下可以成功生成的。

**Comment by Stillremains** [comment]
> @Stillremains 请问你有解决这个问题吗？给你我这的参数设置参考下吧
> <img alt="7953c26e619754eea57e0a5b40e27ff3" width="873" src="https://user-images.githubusercontent.com/46314656/84485392-aafa6b00-acce-11ea-95a4-e851ff79f3f4.png">
> <img alt="dfae98ae0bc12b122291460da7565f2e" width="868" src="https://user-images.githubusercontent.com/46314656/84485444-bc437780-acce-11ea-8f24-f2265ac58a0c.png">
> 就用release/0.3分支，不用改代码，直接这样设置下可以成功生成的。

设置是一样的 也是用的0.3 我到时候换台电脑试试看把

**Comment by xiegegege** [comment]
还有那个保存到JSON的选择也是一样的吗？报错是多次定义了CMAKE_BUILD_TYPE，你把那个对勾去掉试试呢？

**Comment by Stillremains** [comment]
> 还有那个保存到JSON的选择也是一样的吗？报错是多次定义了CMAKE_BUILD_TYPE，你把那个对勾去掉试试呢？
我把了那个对勾去了  那个错误消失了 就是现在剩下的这个问题 
![image](https://user-images.githubusercontent.com/48147367/84487427-50164300-acd1-11ea-8d36-0cd3e11e5a87.png)

**Comment by Stillremains** [comment]
> > 还有那个保存到JSON的选择也是一样的吗？报错是多次定义了CMAKE_BUILD_TYPE，你把那个对勾去掉试试呢？
> > 我把了那个对勾去了  那个错误消失了 就是现在剩下的这个问题
> > ![image](https://user-images.githubusercontent.com/48147367/84487427-50164300-acd1-11ea-8d36-0cd3e11e5a87.png)

严重性	代码	说明	项目	路径	文件	行	禁止显示状态
错误		/DWIN32: No such file or directory	G:\Microsoft Visual Studio\Paddleinference\PaddleDetection\deploy\cpp\out\build\x64-Release\cpp	G:\Microsoft Visual Studio\Paddleinference\PaddleDetection\deploy\cpp\out\build\x64-Release	G:\Microsoft Visual Studio\Paddleinference\PaddleDetection\deploy\cpp\out\build\x64-Release\C__~1.EXE	1	
这是其中一个报错的具体信息 是没生成某文件夹还是啥

**Comment by xiegegege** [comment]
这是生成可执行文件的路径，但是没找到这个路径，你本地的代码是不是有改动？或者你重新下份代码配置下？

**Comment by Stillremains** [comment]
> 这是生成可执行文件的路径，但是没找到这个路径，你本地的代码是不是有改动？或者你重新下份代码配置下？

你指relase-0.3？  刚下载放进去的文件 我每次弄都重新放进去原始的文件

**Comment by xiegegege** [comment]
对的，如果代码没有改动的话，那感觉就是环境问题了。https://developercommunity.visualstudio.com/content/problem/955973/cmake-clangexe-is-no-able-to-compile-a-simple-test.html 这有看到类似的报错，麻烦问下你的cmake版本是什么呢？

**Comment by Stillremains** [comment]
> 对的，如果代码没有改动的话，那感觉就是环境问题了。https://developercommunity.visualstudio.com/content/problem/955973/cmake-clangexe-is-no-able-to-compile-a-simple-test.html 这有看到类似的报错，麻烦问下你的cmake版本是什么呢？

3.6 
![image](https://user-images.githubusercontent.com/48147367/84623415-ca350a80-af11-11ea-8989-5df06a86d33a.png)

**Comment by Stillremains** [comment]
> > 对的，如果代码没有改动的话，那感觉就是环境问题了。https://developercommunity.visualstudio.com/content/problem/955973/cmake-clangexe-is-no-able-to-compile-a-simple-test.html 这有看到类似的报错，麻烦问下你的cmake版本是什么呢？
> 
> 3.6
> ![image](https://user-images.githubusercontent.com/48147367/84623415-ca350a80-af11-11ea-8989-5df06a86d33a.png)

vs我正在升级16.6.2看看  原来版本是16.6.1

**Comment by Stillremains** [comment]
> 对的，如果代码没有改动的话，那感觉就是环境问题了。https://developercommunity.visualstudio.com/content/problem/955973/cmake-clangexe-is-no-able-to-compile-a-simple-test.html 这有看到类似的报错，麻烦问下你的cmake版本是什么呢？

对了 我安装了  Cmake 后 怎么体现在项目中？ 会自动调用吗 还是需要在哪里设置

**Comment by xiegegege** [comment]
会自动调用，不用设置，正常的话按照文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/deploy/cpp/docs/windows_vs2019_build.md 执行就可以了。

**Comment by Stillremains** [comment]
> 会自动调用，不用设置，正常的话按照文档https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/deploy/cpp/docs/windows_vs2019_build.md 执行就可以了。

我这些步骤都做了 还是那样 奇葩 版本也跟新了  我无语了

**Comment by Channingss** [comment]
@Stillremains 要不你试试在win的菜单里面找到visual studio developer command prompt，然后到项目的根目录下面创建文件夹build，进去后手动编译下。
![image](https://user-images.githubusercontent.com/12471701/84870249-a7415c80-b0b1-11ea-9346-d97e4bda74dd.png)
