### ISSUE TITLE
faster rcnn使用paddle2onnx时出错

### ISSUE THREAD

**Issue by marsbzp** [PaddlePaddle/PaddleDetection#9233]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

faster rcnn使用paddle2onnx时出错
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: /share/disk1/bzp/x2bin/models/paddle/faster_rcnn_static_model/model.pdmodel
[Paddle2ONNX] Parameters file path: /share/disk1/bzp/x2bin/models/paddle/faster_rcnn_static_model/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] DenseTensorArray is not supported.
[Paddle2ONNX] DenseTensorArray is not supported.
[Paddle2ONNX] DenseTensorArray is not supported.
[Paddle2ONNX] Cannot find output:scale_0 in input tensors while converting operator 'while', Paddle2ONNX doesn't support this situation now.
[Paddle2ONNX] Oops, there are some operators not supported yet, including generate_proposals_v2,lod_array_length,tensor_array_to_tensor,while,write_to_array,
[ERROR] Due to the unsupported operators, the conversion is aborted.

### 复现环境 Environment

将faster rcnn导成静态图再paddle2onnx会出错

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Bobholamovic** [comment]
看起来是因为模型中包含了不支持的算子，请移步[Paddle2ONNX仓库](https://github.com/PaddlePaddle/Paddle2ONNX/issues)提issue～
