### ISSUE TITLE
使用pphuman吸烟检测模型检测时检测结果的score有问题

### ISSUE THREAD

**Issue by cskkx1** [PaddlePaddle/PaddleDetection#9237]
### 问题描述 Please describe your issue

我在使用pphuman的吸烟检测模型时出现了视频中的人已经不吸烟好久了，但还是显示smoking，然后我去print了一下每帧的检测结果（在deploy/pipeline/pipeline.py的visualize_video方法中）：
 det_action_res = result.get('det_action')
        print('second',det_action_res)
        if det_action_res is not None:
            visual_helper_for_display.append(self.det_action_visual_helper)
            action_to_display.append("Smoking")
然后发现输出的结果score一直在-1和最后一帧有score的数值之间来回变换
<img width="522" alt="issue" src="https://github.com/user-attachments/assets/d0c935cc-c979-4af8-b736-e20b8e9a1fd2">
这就导致一直显示为吸烟

**Comment by cskkx1** [comment]
好像解决了，应该是因为display_frames设置的太高了

**Comment by Sunting78** [comment]
好的 那我们关闭问题，如果后续有其他问题欢迎提问。
