### ISSUE TITLE
请问文档中的模型大小如何得到的？

### ISSUE THREAD

**Issue by mayun123** [PaddlePaddle/PaddleDetection#9240]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

想请问下模型的大小，文档中写的RT-DETR-R50的模型大小是42M，但是预训练模型大小是164M，导出后是161M，请问文档中的42M应该怎么看，谢谢~
<img width="533" alt="rtdetr" src="https://github.com/user-attachments/assets/5c644841-b3b5-4c1a-acc8-657e11cb1267" />

**Comment by zhang-prog** [comment]
`Params 42M` 是模型参数量，并不是模型文件大小哈，可以多了解一下相关知识～
