### ISSUE TITLE
在启动剪裁时，报错AssertionError: only support yaml files for now

### ISSUE THREAD

**Issue by llzhaoshuo** [PaddlePaddle/PaddleDetection#925]
```
 python slim/prune/prune.py -c slim/prune/yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.yaml  --pruned_params "yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights,yolo_block.0.1.1.conv.weights,yolo_block.0.2.conv.weights,yolo_block.0.tip.conv.weights,yolo_block.1.0.0.conv.weights,yolo_block.1.0.1.conv.weights,yolo_block.1.1.0.conv.weights,yolo_block.1.1.1.conv.weights,yolo_block.1.2.conv.weights,yolo_block.1.tip.conv.weights,yolo_block.2.0.0.conv.weights,yolo_block.2.0.1.conv.weights,yolo_block.2.1.0.conv.weights,yolo_block.2.1.1.conv.weights,yolo_block.2.2.conv.weights,yolo_block.2.tip.conv.weights"  --pruned_ratios="0.9,0.9,0.9,0.9,0.1,0.6,0.1,0.1,0.3,0.2,0.2,0.1,0.1,0.9,0.9,0.1,0.6,0.7"
2020-06-11 16:41:02,575-WARNING: If you want to use DDPG in RLNAS, please pip install parl first. Now states: No module named 'parl'
2020-06-11 16:41:02,584-WARNING: If you want to use training-aware and post-training quantization, please use Paddle >= 1.8.0 or develop version
Traceback (most recent call last):
  File "slim/prune/prune.py", line 412, in <module>
    main()
  File "slim/prune/prune.py", line 60, in main
    cfg = load_config(FLAGS.config)
  File "/home/lzs/PaddleDetection/ppdet/core/workspace.py", line 82, in load_config
    assert ext in ['.yml', '.yaml'], "only support yaml files for now"
AssertionError: only support yaml files for now
```
我试了.yml和.yaml都会报这个错误，是什么原因呢

**Comment by heavengate** [comment]
您好，请问PadleDetection是哪个版本呢

**Comment by llzhaoshuo** [comment]
> 您好，请问PadleDetection是哪个版本呢

1.7.2，是版本的问题吗

**Comment by heavengate** [comment]
1.7.2是Paddle版本吧，PaddleDetection版本呢，就是你用的分支

**Comment by llzhaoshuo** [comment]
> 1.7.2是Paddle版本吧，PaddleDetection版本呢，就是你用的分支

请问PaddleDetection的版本应该如何查看呢？

**Comment by heavengate** [comment]
```
git branch
git log -3
```

**Comment by llzhaoshuo** [comment]
$ git branch
* release/0.3

$ git log -3
commit 5a44480f588d172bc86498d0acf1ebe1b10e554c
Author: flishwnag <flish_wang@sina.com>
Date:   Wed May 27 11:37:00 2020 +0800

    Update map_utils.py (#788)
    
    * Update map_utils.py
    
    The calculation may be not correct when the input bbox is not ordered by prob.
    This commit fixes the problem.

commit be72f831e244dabfbdbb86b4e80c64f44df7c8f5
Author: Guanghua Yu <742925032@qq.com>
Date:   Wed May 27 10:52:00 2020 +0800

    fix debug log (#772)

commit 095b03d21befee5d6b0239ce1e13707895ea75e9
Author: qingqing01 <dangqingqing@baidu.com>
Date:   Thu May 21 10:34:22 2020 -0500

    Fix deploy/cpp/src/object_detector.cc (#756)

**Comment by heavengate** [comment]
本地试了下没有复现这个问题，麻烦问下方便在
``
File "/home/lzs/PaddleDetection/ppdet/core/workspace.py", line 82, in load_config
``
这行上面打印一下`ext`的值么，还有麻烦提供一下python的版本信息

**Comment by mmglove** [comment]
@llzhaoshuo 您好，
1、从运行命令中看到您移动了配置文件到prune目录下， -c slim/prune/yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.yaml ，该配置文件源目录是在https://github.com/PaddlePaddle/PaddleDetection/blob/master/configs/dcn/yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.yml，这个配置文件中包含了reader的配置文件路径yolov3_enhance_reader.yml，请确认下您是否一同移动reader.yml到prune路径下
2、建议使用新版paddle=1.8.1版本（pip install -U paddlepaddle-gpu）
paddleslim1.1.1版本( pip install -U paddleslim)
PaddleDetection使用release/0.3分支（您现在的分支就是）
我这边复现上述环境跑该模型未报上面的错误

**Comment by qingqing01** [comment]
@llzhaoshuo 由于时间较久了，关闭了此issue，有问题可以再新开issue。
