### ISSUE TITLE
paddle-detection 量化

### ISSUE THREAD

**Issue by liangruofei** [PaddlePaddle/PaddleDetection#928]
1、要对模型量化，我是就基于原来的精度进行训练，然后再对训练结果模型参数量化，还是训练的时候就要选择量化模式训练？
2、预训练模型，我是利用贵方提供的量化的骨干模型还是原来的高精度模型就可以，如果都可以，这两种有什么区别，哪种更好？
非常感谢回答

**Comment by FDInSky** [comment]
建议backbone是大模型时，可以先训练再量化，而小的backbone时，建议边训练边量化。
而预训练的backbone建议直接选择原来高精度的。
参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/slim/quantization

**Comment by liangruofei** [comment]
收到，非常感谢您的解答😃🤝


在2020年6月12日 10:03，FDInSky<notifications@github.com> 写道：

建议backbone是大模型时，可以先训练再量化，而小的backbone时，建议边训练边量化。
而预训练的backbone建议直接选择原来高精度的。
参考https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/slim/quantization

**Comment by still-wait** [comment]
@liangruofei 
- 在YOLOv3中量化是先训练模型，再将训练好的模型作为量化训练的预训练模型，调小学习率和`max_iter`进行微调(fine-tuning)训练；
- 在MobileNetV3-SSD模型中，我们采用完整量化训练，使用ImageNet上的预训练模型，从头开始量化训练。
至于如何选择fine-tuning量化训练还是完整量化训练，可以参考@FDInSky 给你的建议，也可以都做尝试，选择效果更优的即可。

**Comment by liangruofei** [comment]
收到，感谢您的建议


在2020年6月12日 17:20，Guanghua Yu<notifications@github.com> 写道：

@liangruofei

在YOLOv3中量化是先训练模型，再将训练好的模型作为量化训练的预训练模型，调小学习率和max_iter进行微调(fine-tuning)训练；
在MobileNetV3-SSD模型中，我们采用完整量化训练，使用ImageNet上的预训练模型，从头开始量化训练。

至于如何选择fine-tuning量化训练还是完整量化训练，可以参考@FDInSky 给你的建议，也可以都做尝试，选择效果更优的即可。
