### ISSUE TITLE
请问 yolov3 是否同时支持 ResNet 和 ResNet-vd ？为什么md文件中ResNet-vd 是 X

### ISSUE THREAD

**Issue by clw5180** [PaddlePaddle/PaddleDetection#929]
另外我把backbone改成ResNet训练，但感觉收敛很慢，是正常现象么 ？

**Comment by heavengate** [comment]
1. yolov3支持ResNet-vd的，这里有yolov3 ResNet50vd的配置文件
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/configs/dcn/yolov3_r50vd_dcn.yml
2. 收敛慢是多慢，yolov3模型是单阶段的，本身收敛很慢的，yolov3作者采用在COCO数据集上训练50w轮，约270epoch
