### ISSUE TITLE
Ubuntu 16.04 下调用c++预测库问题

### ISSUE THREAD

**Issue by baigang666** [PaddlePaddle/PaddleDetection#932]
系统环境：
ubuntu：16.04
cuda:10.0
cudnn:7.6.5
下载的预测库是ubuntu14.04_cuda10.0_cudnn7_avx_mkl
我再ubuntu下调用paddle C++预测库  出现以下错误
/usr/bin/ld: /home/caffe/Documents/bg_file/C++File/BaiduPaddle0518/fluid_inference/paddle/lib/libpaddle_fluid.a(analysis_predictor.cc.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
这是不是预测库版本不符合当前环境？
求大神帮忙看一下

**Comment by heavengate** [comment]
编译的时候加下` -ldl`试下呢
https://blog.csdn.net/quantum7/article/details/103189384

**Comment by baigang666** [comment]
@heavengate  那个-ldl加在啥地方呀？  我再ubuntu下使用kdevelop  集成环境开发，直接再cmakeList.txt文件中使用target_link_librarys(main libpaddlefluid.a)链接

如果我不链接这个静态库，只链接动态库，可以编译成功，但是当我调用
paddle::AnalysisiConfig 中函数setModel(pro_file,params_file)时候  提示 ******Program recevied signal SIGSEGV (Segmentation fault)****


请帮忙解答以下上述两个问题  谢谢

**Comment by baigang666** [comment]
@heavengate 我所使用的gcc g++ 版本都是4.9.3   cmake版本：3.10.2

**Comment by heavengate** [comment]
可以参考下这个https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/c%2B%2B/resnet50/CMakeLists.txt
也可以参考Detection下面的demo：https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/deploy/cpp/CMakeLists.txt
