### ISSUE TITLE
深度可分离卷积支持裁剪吗

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#939]
修改yolo_head部分卷积为深度可分离卷积，发现prune训练还是加载的原始预训练权重，而且前面几轮训练，filter个数没有变化。所以，深度可分离卷积支持裁剪吗？

**Comment by heavengate** [comment]
支持，但是不能直接剪裁。需要通过剪裁可分离卷积的前一个卷积来达到剪裁可分离卷积的目的。

**Comment by JensenHJS** [comment]
我的理解是剪了深度可分离卷积前一个卷积，然后深度卷积的组数就自然剪少了，达到了剪深度卷积的目的？然后逐点卷积的裁剪就正常剪？

**Comment by JensenHJS** [comment]
我的理解是剪了深度可分离卷积前一个卷积，然后深度卷积的组数就自然剪少了，达到了剪深度卷积的目的？然后逐点卷积的裁剪就正常剪？ 就是裁剪参数里不能给出深度卷积这个参数吧

**Comment by heavengate** [comment]
是的
