### ISSUE TITLE
yolov3训练，已经有coco数据集了，为什么他还是要下载呢？而且还是好几十个G

### ISSUE THREAD

**Issue by Attackzzw** [PaddlePaddle/PaddleDetection#942]
! python tools/train.py -c configs/yolov3_darknet.yml --eval
已经有coco数据集，train2017数据集，但还是下载，问什么呢?

/home/aistudio/data/PaddleDetection
2020-06-14 09:20:06,808-INFO: Dataset /home/aistudio/data/PaddleDetection/dataset/coco is not valid for reason above, try searching /home/aistudio/.cache/paddle/dataset or downloading dataset...
2020-06-14 09:20:06,809-INFO: Downloading train2017.zip from http://images.cocodataset.org/zips/train2017.zip
  0%|                               | 4543/18883655 [04:00<448:52:53, 11.68KB/s]^C
2020-06-14 09:24:08,131-INFO: KeyboardInterrupt: main proc 200 exit, kill subprocess []
  0%|                               | 4543/18883655 [04:00<277:38:59, 18.89KB/s]

**Comment by jerrywgz** [comment]
默认数据集是放在PaddleDetection/dataset/coco 这个路径下的，可以检查下数据路径

**Comment by Attackzzw** [comment]
谢谢，这个已经好了，是数据集不全，都解压就好了，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wangguanzhong"<notifications@github.com&gt;; 
发送时间: 2020年6月15日(星期一) 上午10:08
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 
抄送: "绝大多数人"<840335286@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] yolov3训练，已经有coco数据集了，为什么他还是要下载呢？而且还是好几十个G (#942)





 
默认数据集是放在PaddleDetection/dataset/coco 这个路径下的，可以检查下数据路径

**Comment by jerrywgz** [comment]
好的，如果问题解决就请关闭issue吧～

**Comment by yyyssq** [comment]
@Attackzzw 大佬，我也是用的coco数据集，就开始自动下载train2017那个数据集，目测是路径有些问题。可以了解以下您的dataset Tree和yml文件是如何配置的吗

**Comment by Attackzzw** [comment]
不好意思，时间有点长，我也忘了那个放哪了，不过你可以检查下你的yml配置，我当初好像就是解压路径问题
