### ISSUE TITLE
paddledetection/slim/quantization

### ISSUE THREAD

**Issue by justinmeibi** [PaddlePaddle/PaddleDetection#947]
yolo_darknet_voc.做量化推断时这个warning ,推断出是没有目标的,这个应该是不能加载量化参数,但是在服务器上不存在这个问题,
一)python/site-packages/paddle/fluid/io.py:1997: UserWarning: This list is not set, Because of Paramerter not found in program. There are: elementwise_add_15.scale elementwise_add_2.scale elementwise_add_11.scale elementwise_add_12.scale elementwise_add_10.scale elementwise_add_17.scale elementwise_add_21.scale elementwise_add_1.scale elementwise_add_9.scale elementwise_add_6.scale @LR_DECAY_COUNTER@ elementwise_add_7.scale elementwise_add_19.scale elementwise_add_14.scale elementwise_add_0.scale elementwise_add_20.scale elementwise_add_16.scale elementwise_add_4.scale elementwise_add_18.scale elementwise_add_5.scale elementwise_add_13.scale elementwise_add_3.scale elementwise_add_8.scale elementwise_add_22.scale

二)建立voc 数据链接,但是每次还都是从~/.cache/下读取数据集

**Comment by qingqing01** [comment]
@justinmeibi  

1).  做量化推断使用的那个脚本呢？以及eval的评估mAP如何？
2). VOC的数据组织是咋样的?  可以正常加载的格式是：

```
dataset/voc/VOCdevkit
|-- VOC2007
|   |-- Annotations
|   |-- ImageSets
|   |-- JPEGImages
|   |-- SegmentationClass
|   `-- SegmentationObject
`-- VOC2012
    |-- Annotations
    |-- ImageSets
    |-- JPEGImages
    |-- SegmentationClass
    `-- SegmentationObject
```

**Comment by justinmeibi** [comment]
quantization/infer.py  eval.py 为map:0
相同代码,服务器上正常,为排除在本地对代码做修改原因,又重新拉了代码,量化评估和推断还是有上述问题.

**Comment by justinmeibi** [comment]
voc 数据集格式一致,命令如下:
ln -sf  /**/**/voc/  /**/paddledetection/datasets/voc/

**Comment by qingqing01** [comment]
@juncaipeng 额， 服务器和本地的环境差异是什么？ 是否还有其他的差异？

**Comment by qingqing01** [comment]
线下沟通，是因为服务器和本地的Paddle版本、PaddleSlim版本不一致导致的。

**Comment by justinmeibi** [comment]
环境不同导致的问题，感谢回答
