### ISSUE TITLE
关于 --eval评价指标

### ISSUE THREAD

**Issue by chengxurensheng666** [PaddlePaddle/PaddleDetection#953]
![image](https://user-images.githubusercontent.com/48110081/84879336-a7dff000-b0bd-11ea-84a2-261112e7701f.png)
![image](https://user-images.githubusercontent.com/48110081/84879357-b1695800-b0bd-11ea-9c57-ba6fc397589b.png)
i--eval 打印出的日志 Best test box ap: 0.8261213954124944。Best test box ap的满分是1.0还是100.0

**Comment by zhhsplendid** [comment]
AP (Average Precision) 一般是指1.0分制，满分是1.0
