### ISSUE TITLE
利用模型库中的model，运行eval.py遇到的问题

### ISSUE THREAD

**Issue by hujinda** [PaddlePaddle/PaddleDetection#955]
paddle版本1.7，用的代码是release0.3
利用https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet.tar  这个模型来eval的时候。
![image](https://user-images.githubusercontent.com/49420402/84901346-ef767400-b0dd-11ea-8e94-4adf6ef9b2e7.png)

大概50分钟运行完100iter，这个速度比我自己训练的模型eval要慢很多。
请问是不是这个warning的问题，eval的时候会用到yolo_output这几个参数嘛？

**Comment by willthefrog** [comment]
这个warning说明你的模型和保存权重的模型结构有差异。另外，建议升级paddle及cudnn。

**Comment by hujinda** [comment]
> 这个warning说明你的模型和保存权重的模型结构有差异。另外，建议升级paddle及cudnn。

请问release0.3的代码可以评估paddle1.7之前版本的模型嘛。
