### ISSUE TITLE
请问paddledetection画出的预测框的标签太小，相对于整张图来说小的看不见，怎样改动能够使标签放大呢？

### ISSUE THREAD

**Issue by LongLivecn** [PaddlePaddle/PaddleDetection#956]
请问paddledetection画出的预测框的标签太小，相对于整张图来说小的看不见，怎样改动能够使标签放大呢？

**Comment by FDInSky** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/d59c29935d04b2f7b74cf34cc504111deb741438/ppdet/utils/visualizer.py#L106 
在这里，可以参考ImageDraw.Draw的参数

**Comment by LongLivecn** [comment]
@FDInSky
我之前就找到这里了，改过但是没用，后来追溯到 text = "{} {:.2f}".format(catid2name[catid], score)
它这里是不是已经把文字大小设置成固定的了啊？

**Comment by LongLivecn** [comment]
@FDInSky 
好了我已经解决了，找到font的路径下字体文件然后在visualizer下面ft = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-Bold.ttf",40)
改了字体和大小

**Comment by atomrun39** [comment]
> @FDInSky
> 好了我已经解决了，找到font的路径下字体文件然后在visualizer下面ft = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-Bold.ttf",40)
> 改了字体和大小

请问怎么找到font的路径下字体文件呀？

**Comment by atomrun39** [comment]
> > @FDInSky
> > 好了我已经解决了，找到font的路径下字体文件然后在visualizer下面ft = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-Bold.ttf",40)
> > 改了字体和大小
> 
> 请问怎么找到font的路径下字体文件呀？

已经解决了

**Comment by LongLivecn** [comment]
在paddledetection中的ppdet文件夹里找到visualizer.py这个文件
找到这一行代码：ft = ImageFont.truetype
括号里逗号左边是 字体文件的地址（至于怎么找到的我忘了，百度了好久），逗号右边是文字大小（可自行调整） ft = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-Bold.ttf",40)
然后，draw.text((xmin + 1, ymin - th-30),text ,font = ft, fill=(255, 255, 255))里面 （x，y）调标签框的大小

自己慢慢调一下，时间隔太长我也记不大清了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "atomrun39"<notifications@github.com&gt;; 
发送时间: 2020年8月24日(星期一) 晚上8:33
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;; 
抄送: "红色警戒"<627997400@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/PaddleDetection] 请问paddledetection画出的预测框的标签太小，相对于整张图来说小的看不见，怎样改动能够使标签放大呢？ (#956)





   
@FDInSky
 好了我已经解决了，找到font的路径下字体文件然后在visualizer下面ft = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-Bold.ttf",40)
 改了字体和大小
  
请问怎么找到font的路径下字体文件呀？
  
已经解决了
