### ISSUE TITLE
paddledetection yolov3做训练

### ISSUE THREAD

**Issue by AIpioneer** [PaddlePaddle/PaddleDetection#960]
咨询下我用paddledetection yolov3做训练，配置文件dataset_dir: dataset/voc/VOCdevkit/VOC2007
    annotation: trainval.txt
应该填什么地址？

**Comment by heavengate** [comment]
`dataset/voc`目录下有个`create_list.py` 用于生成VOC数据集的`trainval.txt`和`test.txt`对应训练和评估的标注文件，如果你的数据集是在`dataset/voc`下或者软连接到`dataset/voc`下，不需要修改路径配置，如果不是，需要`dataset_dir`+`annotation`指向上面说的生成的两个标注文件，`dataset_dir`+`image_dir`指向图片所在文件夹
