### ISSUE TITLE
RCNN Context

### ISSUE THREAD

**Issue by KooSung** [PaddlePaddle/PaddleDetection#963]
我想将原始roi长宽两倍大小的rois经过roi align后concat到之前的roi feature上。
在[roi_extractor.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/ppdet/modeling/roi_extractors/roi_extractor.py) 中， https://github.com/PaddlePaddle/PaddleDetection/blob/e47e826ed1e4cefcbe4b6bdb1f976c68faa91799/ppdet/modeling/roi_extractors/roi_extractor.py#L75
[distribute_fpn_proposals](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/distribute_fpn_proposals_cn.html#distribute-fpn-proposals)返回的是：
>  - multi_rois（List）- 长度为（max_level-min_level+1）的列表，其中元素为Variable，维度为[M, 4]的2-D LoDTensor，M为每个级别proposal的个数，数据类型为float32或float64。表示每个FPN级别包含的proposals。
> - restore_ind（Variable）- 维度为[N，1]的Tensor，N是总rois的数量。数据类型为int32。 它用于恢复fpn_rois的顺序。

我想问一下multi_rois维度中的4代表的是proposal的坐标吗？

**Comment by FDInSky** [comment]
@KooSung  是每个bbox，左上角和右下角两个点的x，y坐标
