### ISSUE TITLE
demo和deploy/cpp下代码，在vs2019下编译提示如下错误

### ISSUE THREAD

**Issue by xianbinzhang** [PaddlePaddle/PaddleDetection#964]
无法解析的外部符号 "__declspec(dllimport) public: __cdecl std::basic_ostream<char,struct std::char_traits<char> >::basic_ostream<char,struct std::char_traits<char> >(enum std::_Uninitialized,bool)" (__imp_??0?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@W4_Uninitialized@1@_N@Z)

error LNK2001: 无法解析的外部符号 "__declspec(dllimport) protected: void __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::setp(char *,char *,char *)" (__imp_?setp@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAXPEAD00@Z)

error LNK2001: 无法解析的外部符号 "__declspec(dllimport) protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::pbase(void)const " (__imp_?pbase@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEBAPEADXZ)

**Comment by xianbinzhang** [comment]
win 10系统，编译release 64 版本 
yaml 库从：https://bj.bcebos.com/paddlex/deploy/deps/yaml-cpp.zip 下载  使用CMake 编译64位静态库，Boost库使用版本是：1.69

**Comment by Channingss** [comment]
请问是在vs2019的环境下编译吗

**Comment by xianbinzhang** [comment]
是的，VS2019下  自建工程，添加了所有依赖库和头文件

**Comment by Channingss** [comment]
完全按照教程来操作的吗？能把Cmake**.json配置参数截图看下？

**Comment by xianbinzhang** [comment]
按windows_vs2019_build.md 这个教程，最后我的第五步没有全部生成选项，所以自己创建一个win32控制台工程，添加了paddle 1.8 win64 的库和third_party 下的所有库，因是VS2019 创建的win32 工程里面没有Cmake*****.json 需要把工程上传 你看下吗？

**Comment by xianbinzhang** [comment]
#include <glog/logging.h> 
自建控制台程序 不导入这个文件就看可以就不会报上面错误了，真正原因还未找到
