### ISSUE TITLE
deploy目录下infer.py代码的detector.predict()函数遇到问题

### ISSUE THREAD

**Issue by xmy0916** [PaddlePaddle/PaddleDetection#969]
代码一：
mat = cv2.imread("test2.jpg")
results = detector.predict(mat, FLAGS.threshold)
代码二：
results = detector.predict("test2.jpg", FLAGS.threshold)
两个代码都可以运行但是输出结果不一样：
![image](https://user-images.githubusercontent.com/43675899/85196712-af4a0800-b30e-11ea-9653-bc5175a490df.png)
我觉得可能是我直接传Mat类型作为参数的问题，但是我看了官方给的def predict_video():函数里面也是直接传Mat类型的呀，是不是存在问题呢
predict_video里面部分代码：
capture = cv2.VideoCapture(FLAGS.video_file)
ret, frame = capture.read()
results = detector.predict(frame, FLAGS.threshold)

**Comment by qingqing01** [comment]
@xmy0916  

predict()函数输入图片路径、numpy.array都支持。


代码：

predict():

https://github.com/PaddlePaddle/PaddleDetection/blob/e47e826ed1e4cefcbe4b6bdb1f976c68faa91799/deploy/python/infer.py#L466-L477

-> preprocess()函数:


https://github.com/PaddlePaddle/PaddleDetection/blob/e47e826ed1e4cefcbe4b6bdb1f976c68faa91799/deploy/python/infer.py#L430-L442


-> decode_image()函数:


https://github.com/PaddlePaddle/PaddleDetection/blob/e47e826ed1e4cefcbe4b6bdb1f976c68faa91799/deploy/python/infer.py#L29-L50

即可以是图片路径，也可以是numpy.array。

如果是代码一的形式，注意读完之后需要，和上面decode_image保持一致，转换为RGB模式: ` im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)`

**Comment by xmy0916** [comment]
@qingqing01 感谢，但是我看predict_vedio函数也没做这些处理直接传mat进去了所以就提了下是否存在问题
