### ISSUE TITLE
有一个小细节关于路径想分享一下

### ISSUE THREAD

**Issue by chengxurensheng666** [PaddlePaddle/PaddleDetection#970]
![image](https://user-images.githubusercontent.com/48110081/85196804-49aa4b80-b30f-11ea-8193-a99c831b8fbe.png)
参照这个路径，预测出来的是coco数据集的标签（person，bicycle），如果使用自定义数据集按照这样类似的路径配置也会是coco数据集的默认标签。
如果将这个换成绝对路径就可以变成自定义数据的标签
![image](https://user-images.githubusercontent.com/48110081/85196857-ab6ab580-b30f-11ea-9908-5db5f688f1c8.png)

**Comment by qingqing01** [comment]
@chengxurensheng666  Thanks very much!
