### ISSUE TITLE
模型导出

### ISSUE THREAD

**Issue by HelloAI-twj** [PaddlePaddle/PaddleDetection#971]
请问一下，voc格式数据集训练的模型导出的时候为什么只有两个文件，没有.yml文件

**Comment by still-wait** [comment]
@HelloAI-twj 请问是哪个模型？使用的是release/0.3分支的代码吗？

**Comment by HelloAI-twj** [comment]
> @HelloAI-twj 请问是哪个模型？使用的是release/0.3分支的代码吗？

我训练用的权重文件是yolov3_darknet_voc.yml,这个0.3分支的代码是什么呀，初学者不是很了解

**Comment by qingqing01** [comment]
@HelloAI-twj 我是用最新的稳定版本release/0.3分支测试，没有问题：

```
python tools/export_model.py -c configs/yolov3_darknet_voc.yml \
        --output_dir=./inference_model \
        -o weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet_voc.tar \
```


```
2020-06-22 02:31:38,610-INFO: Downloading yolov3_darknet_voc.tar from https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet_voc.tar
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 241300/241300 [01:00<00:00, 3983.86KB/s]
2020-06-22 02:32:42,349-INFO: Decompressing /root/.cache/paddle/weights/yolov3_darknet_voc.tar...
2020-06-22 02:32:46,654-WARNING: /root/.cache/paddle/weights/yolov3_darknet_voc.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-06-22 02:32:54,412-INFO: save_inference_model pruned unused feed variables im_id
2020-06-22 02:32:54,412-INFO: Export inference model to ./inference_model/yolov3_darknet_voc, input: ['image', 'im_size'], output: ['multiclass_nms_0.tmp_0']...
2020-06-22 02:32:58,222-INFO: Not found annotation file None, load voc2012 categories.
2020-06-22 02:32:58,225-INFO: Export inference config file to ./inference_model/yolov3_darknet_voc/infer_cfg.yml
```


 tree ./inference_model/yolov3_darknet_voc/

```
./inference_model/yolov3_darknet_voc/
|-- __model__
|-- __params__
`-- infer_cfg.yml
```

是有infer_cfg.yml文件的

**Comment by qingqing01** [comment]
@HelloAI-twj  

release/0.3分支是:

<img width="636" alt="图片" src="https://user-images.githubusercontent.com/7845005/85243516-a8d5a080-b474-11ea-8189-52628207b6f6.png">


```
git branch
```
看下代码分支是否正确？

**Comment by HelloAI-twj** [comment]
> @HelloAI-twj 我是用最新的稳定版本release/0.3分支测试，没有问题：
> 
> ```
> python tools/export_model.py -c configs/yolov3_darknet_voc.yml \
>         --output_dir=./inference_model \
>         -o weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet_voc.tar \
> ```
> 
> ```
> 2020-06-22 02:31:38,610-INFO: Downloading yolov3_darknet_voc.tar from https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet_voc.tar
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 241300/241300 [01:00<00:00, 3983.86KB/s]
> 2020-06-22 02:32:42,349-INFO: Decompressing /root/.cache/paddle/weights/yolov3_darknet_voc.tar...
> 2020-06-22 02:32:46,654-WARNING: /root/.cache/paddle/weights/yolov3_darknet_voc.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
> 2020-06-22 02:32:54,412-INFO: save_inference_model pruned unused feed variables im_id
> 2020-06-22 02:32:54,412-INFO: Export inference model to ./inference_model/yolov3_darknet_voc, input: ['image', 'im_size'], output: ['multiclass_nms_0.tmp_0']...
> 2020-06-22 02:32:58,222-INFO: Not found annotation file None, load voc2012 categories.
> 2020-06-22 02:32:58,225-INFO: Export inference config file to ./inference_model/yolov3_darknet_voc/infer_cfg.yml
> ```
> 
> tree ./inference_model/yolov3_darknet_voc/
> 
> ```
> ./inference_model/yolov3_darknet_voc/
> |-- __model__
> |-- __params__
> `-- infer_cfg.yml
> ```
> 
> 是有infer_cfg.yml文件的

我用的weights是自己训练出来的model_final,结果没有那个yml文件，是我用的weights不对吗

**Comment by qingqing01** [comment]
@HelloAI-twj 先看下你PaddleDetection是哪个版本。

**Comment by HelloAI-twj** [comment]
> @HelloAI-twj 先看下你PaddleDetection是哪个版本。

我是在AIStudio平台数据集里找的一个PaddleDetection代码包，解压后直接用的，不知道它的版本是多少，有什么方法查看吗

**Comment by qingqing01** [comment]
@HelloAI-twj  见上面的回复：

`git branch` 查看下，很大可能是代码分支不是release/0.3分支。

**Comment by HelloAI-twj** [comment]
> @HelloAI-twj 见上面的回复：
> 
> `git branch` 查看下，很大可能是代码分支不是release/0.3分支。

我输入git  branch后没有结果
![git](https://user-images.githubusercontent.com/64730376/85266754-e8b57b80-b4a6-11ea-929e-0910055fea39.png)

**Comment by qingqing01** [comment]
@HelloAI-twj  注意在PaddleDetection代码中查看。 你上面的问题，就是版本问题，建议拉取最新的代码，对模型导出。
