### ISSUE TITLE
paddle inference推理时报错

### ISSUE THREAD

**Issue by whjdark** [PaddlePaddle/PaddleDetection#972]
**output_data = output_tensor.copy_to_cpu()**
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
**Error: Tensor holds the wrong type, it holds ::paddle::platform::float16, but desires to be float at** (D:\1.8.0\paddle\paddle/fluid/framework/tensor_impl.h:48)

代码：
config = AnalysisConfig("infer_model.model") # 加载non-combined 模型格式

config.switch_use_feed_fetch_ops(False)
config.enable_memory_optim()
config.enable_use_gpu(100, 0)

predictor = create_paddle_predictor(config)

img = np.ones((1, 3, 224, 224)).astype(np.float)

input_names = predictor.get_input_names()
input_tensor = predictor.get_input_tensor(input_names[0])
input_tensor.copy_from_cpu(img.copy())

predictor.zero_copy_run()

output_names = predictor.get_output_names()
output_tensor = predictor.get_output_tensor(output_names[0])
output_data = output_tensor.copy_to_cpu()

print (output_data)

**训练时用的是fp16混合精度训练**

**Comment by qingqing01** [comment]
@whjdark    你是在什么机器上做预测？是否有TensorRT呢？如果支持TensorRT，可以试试用

https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/deploy/python

这里的Python预测脚本，设置run_mode是trt_fp16。

**Comment by whjdark** [comment]
>     1. FP32

FP32预测，把混合精度训练关了重新训练就不报错了。
