### ISSUE TITLE
如何修改脚本使用自定义评估指标

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/PaddleDetection#973]
单类检测器想使用其他的指标，需要修改哪些脚本

**Comment by zhengzhe97** [comment]
想要返回TP/（TP+FN+FP）在iou在0.5到0.75步长为0.05的结果，需要怎么修改

**Comment by qingqing01** [comment]
@zhengzhe97 

可以参考VOC的Python评估脚本，进行修改，

1. 拿到所有检测bbox的结果，计算mAP的入口:

 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/ppdet/utils/eval_utils.py#L232

2.  计算mAP函数:

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/ppdet/utils/voc_eval.py#L34

可以在这些相应的函数里修改，或添加新的评估函数。

**Comment by zhengzhe97** [comment]
谢谢回复，已解决
