### ISSUE TITLE
deploy文件下的c++推理

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#974]
deploy文件下的c++推理是用cmake来管理c++代码的。在源文件里我想找到使用的某个函数或者某个命名空间在哪里定义的，怎样快速找到定义，类似pycharm中ctrl+b这样的功能。请问你们一般是在什么ide管理cmake的工程的？我在tx2上装了clion，但是无法使用clion的终端，所以感觉并不能真正在clion中运行c++的例子，同样也无法找到某个函数或者类在哪里定义的。

**Comment by JensenHJS** [comment]
现在我可以在clion里通过终端运行deploy/c++例子了，但是比如src/main.cc第一行代码google命名空间的parsecommand函数，快捷键ctrl+b查找函数定义找不到，但如果fgrep查找关键字parsecommand，又出来一大堆。所以有什么办法可以快速找到某个函数在哪里定义的？

**Comment by qingqing01** [comment]
@JensenHJS  个人一般是直接使用Linux终端运行，没有使用IDE。  [deploy/C++](https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/deploy/cpp)代码不多，主要是`include`和`src`文件夹下，可以直接文件里找下：

```
|-- include
|   |-- config_parser.h
|   |-- object_detector.h
|   `-- preprocess_op.h
`-- src
    |-- main.cc
    |-- object_detector.cc
    `-- preprocess_op.cc
```

仅仅查看源码的话Sublime/Clion都可以查看，并跳转函数。
