### ISSUE TITLE
请问一下这个数据增强的中32指的是什么含义pading=32 or stride=32

### ISSUE THREAD

**Issue by chengxurensheng666** [PaddlePaddle/PaddleDetection#978]
![image](https://user-images.githubusercontent.com/48110081/85254496-0b3d9980-b493-11ea-8621-d7586d2eceb5.png)
![image](https://user-images.githubusercontent.com/48110081/85254510-14c70180-b493-11ea-80c8-d0518b0092e3.png)
我使用paddedetection infer推理模型能够正常预测，但是换到inference后预测就出错了，我查看了我代码的预处理算子，打勾的是写了代码的，但是预测出错，我怀疑是
![image](https://user-images.githubusercontent.com/48110081/85254706-78512f00-b493-11ea-9cf2-a7203621fc08.png)
![image](https://user-images.githubusercontent.com/48110081/85254738-8b63ff00-b493-11ea-9c09-88c36173c01c.png)

**Comment by qingqing01** [comment]
这个含义是将height, width的长度padding到32的整数倍。对于含有FPN的模型需要这个操作，使得feature-map的height, width变化时，对于奇数、偶数图片取整都可以做到相同的尺度。
