### ISSUE TITLE
deploy/c++推理

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#979]
deploy/c++推理可以正确预测图片,但预测视频报错,视频是mp4格式
报错如下:
OpenCV: FFMPEG: tag 0x00000021/'!???' is not found (format 'mp4 / MP4 (MPEG-4 Part 14)')'
OpenCV Error: Unsupported format or combination of formats (Gstreamer Opencv backend does not support this codec.) in CvVideoWriter_GStreamer::open, file /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp, line 1528
VIDEOIO(cvCreateVideoWriter_GStreamer (filename, fourcc, fps, frameSize, is_color)): raised OpenCV exception:

/home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp:1528: error: (-210) Gstreamer Opencv backend does not support this codec. in function CvVideoWriter_GStreamer::open

create video writer failed!

**Comment by hong19860320** [comment]
所使用的OpenCV携带的ffmpeg不包含'mp4 / MP4 (MPEG-4 Part 14)'的codec，建议重新编译带有相应codec的OpenCV https://www.learnopencv.com/install-opencv3-on-ubuntu/
