### ISSUE TITLE
ai studio上运行paddleDetection出现错误？

### ISSUE THREAD

**Issue by ZhiXianZ** [PaddlePaddle/PaddleDetection#980]
![069SG)SWQCI1`Y}M0$656K4](https://user-images.githubusercontent.com/57262617/85373430-d2222980-b565-11ea-8cc4-2da779cb33e3.png)
![8{MZ421 LUHM5L(9EB%7N7L](https://user-images.githubusercontent.com/57262617/85373451-d8180a80-b565-11ea-9b28-299033010d65.png)
batch-size=1

**Comment by jerrywgz** [comment]
想问下你的启动命令和paddle版本分别是多少呢

**Comment by ZhiXianZ** [comment]
> 想问下你的启动命令和paddle版本分别是多少呢

python -u tools/train.py -c configs/faster_rcnn_r101_1x.yml --use_vdl=True  --vdl_log_dir=vdl_faster_rcnn_r101_1x/scalar   --eval 
版本是1.7.1

**Comment by jerrywgz** [comment]
想起来visualdl要求python3才能正常运行，python2的版本已经不再维护了

**Comment by ZhiXianZ** [comment]
> 想起来visualdl要求python3才能正常运行，python2的版本已经不再维护了

我确实是python3的环境呀

**Comment by jerrywgz** [comment]
已复现该问题，可以使用 pip install --upgrade --pre visualdl 升级visualdl至最新版即可

**Comment by ZhiXianZ** [comment]
> 已复现该问题，可以使用 pip install --upgrade --pre visualdl 升级visualdl至最新版即可
![QQ截图20200624214208](https://user-images.githubusercontent.com/57262617/85567707-abe2b380-b663-11ea-84d1-50e2a1f15796.png)
不行呢，还是这个错误

**Comment by May52** [comment]
> > 已复现该问题，可以使用 pip install --upgrade --pre visualdl 升级visualdl至最新版即可
> > ![QQ截图20200624214208](https://user-images.githubusercontent.com/57262617/85567707-abe2b380-b663-11ea-84d1-50e2a1f15796.png)
> > 不行呢，还是这个错误

你是不是改了faster_rcnn_r101_1x.yml的batch_size: 1？我之前用faster_rcnn_r50的时候将batch_size改为4就出现了你上图的错，后来恢复为1就没错了。

**Comment by qingqing01** [comment]
@ZhiXianZ  出错信息看着是out of memory，你nvidia-smi看下，有没有已经死掉的进程，显存还没释放，被占用的。如果不是，减少batch-size看下。

**Comment by ZhiXianZ** [comment]
> @ZhiXianZ 出错信息看着是out of memory，你nvidia-smi看下，有没有已经死掉的进程，显存还没释放，被占用的。如果不是，减少batch-size看下。

好的，我再看看
