### ISSUE TITLE
ssd_mobilenet_v1_voc.yml 配置文件问题

### ISSUE THREAD

**Issue by yangyang117** [PaddlePaddle/PaddleDetection#981]
请问有没有配置文件的详细说明。
如果想根据自己的实际任务进行修改，可以修改哪些参数呢？
如果想修改anchors的比例和大小，怎么修改呢？MultiBoxHead是怎么生成的？在ssd.py文件里面看不到是怎么生成的。

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/ppdet/modeling/ops.py#L1287  MultiBoxHead是通过注册的方式加到architecture中，该类中的初始化参数均可以通过配置文件的方式传入, https://www.paddlepaddle.org.cn/documentation/docs/zh/1.7/api_cn/layers_cn/multi_box_head_cn.html#multi-box-head 这里是相关参数的解释，包括aspect_ratios为anchor的宽高比
