### ISSUE TITLE
deploy/c++推理

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#983]
deploy/c++代码好像没有看到网络结构部分的代码，我之前c++推理用的mobilenet_yolo，改了部分网络结构并剪枝后，在c++推理时直接替换之前的权重和yml文件，代码不需修改都能直接用。感觉是所有检测算法都通用这一个detection c++推理的代码？

**Comment by chenwhql** [comment]
您稍等，我找负责的同学帮您解答下

**Comment by willthefrog** [comment]
c++ infer用的是导出的inference model，本身已经包含了网络结构信息。

**Comment by JensenHJS** [comment]
意思是只要导出为infer model和yml文件，无论什么检测算法，或者改了网络结构，都可以用这个c++推理代码，代码不需要修改？

**Comment by willthefrog** [comment]
原则上是。

**Comment by gxqnba** [comment]
@JensenHJS 请问你在deploy/c++推理 成功了吗？我遇到了一些问题，想咨询一下你。

**Comment by JensenHJS** [comment]
有问题，直接提issue，有官方技术支持帮你解决的。而且有问题直接说问题，不要什么我可以问你个问题吗
