### ISSUE TITLE
如何找到所需要的模型及相关文件

### ISSUE THREAD

**Issue by lao-xu** [PaddlePaddle/PaddleDetection#984]
不太搞得清detection是怎么组织文件的，比如现在我需要ssd检测系统，哪些是和ssd相关的模型文件、训练文件、数据文件、数据预处理文件、辅助文件、评估文件？要自己到里面逐个去找吗？

**Comment by willthefrog** [comment]
paddledetection已经将这些都流程都抽象统一了，使用的话只需要在`configs`文件找到目标模型的配置配置文件，根据需求做相应修改就好了。文件不是按模型组织的，而是按通用流程组织的，训练，数据集，评估这些基本是一致的，不同模型主要是组网和数据预处理有不同，可以参看`data`和`modeling`文件夹的内容。
