### ISSUE TITLE
边缘设备小目标检测网络

### ISSUE THREAD

**Issue by yyqgood** [PaddlePaddle/PaddleDetection#986]
你好, 请问: 边缘设备小目标检测网络有什么推荐?谢谢!

**Comment by qingqing01** [comment]
@yyqgood  能问下具体是什么设备吗？ 对速度要求的话，可以参考这些模型： https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/configs/mobile

**Comment by yyqgood** [comment]
arm平台(你可以看成手机端); 这几个网络, 那个对小目标检测比较友好?

**Comment by qingqing01** [comment]
建议实际评测下看看，YOLOv3也在一些质检的小目标上用过，也还可以。

**Comment by yyqgood** [comment]
你好, 我看了你们对这几个网络的评测和下载模型查看模型大小, 原则上都符合我的项目需求; 我现在主要关注的事: 我需要检测两类,一类为大目标,一类为小目标, yolov3还是最好的选择吗?

**Comment by qingqing01** [comment]
@yyqgood 可以先使用YOLOv3看下效果如何。
