### ISSUE TITLE
vs2019 cmake问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleDetection#987]
按照该文档（https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/deploy/cpp/docs/windows_vs2019_build.md ） 进行编译，但是最后在cmd中没有报错，但是也没有生成output.jpg

**Comment by qingqing01** [comment]
@gxqnba  那执行预测期间，还有其他log吗？

**Comment by AN-ZE** [comment]
一样没有生成结果，和报错信息。

**Comment by qingqing01** [comment]
@AN-ZE  @gxqnba 我们再测试下看下。

**Comment by AN-ZE** [comment]
> 
> 
> @AN-ZE @gxqnba 我们再测试下看下。

模型是v0.2版本生成的模型，会不会是这个原因。

**Comment by Channingss** [comment]
在菜单里面找到vs 2019 的CMD工具：Developer Command Prompt，在这里面试试执行看 @AN-ZE

**Comment by AN-ZE** [comment]
> 
> 
> 在菜单里面找到vs 2019 的CMD工具：Developer Command Prompt，在这里面试试执行看 @AN-ZE

不行，还是没有反应。

`main.exe --model_dir=C:/ANZE/PaddleDetection/deploy/python/fruit_cascade_frcnn_r50vd_dcn_fpn --image_path=C:/ANZE/PaddleDetection/deploy/python/1.png`

**Comment by Channingss** [comment]
@AN-ZE 我看这个路径分隔符应该用\\

**Comment by AN-ZE** [comment]
> 
> 
> @AN-ZE 我看这个路径分隔符应该用\

'\\'  '\\\\'  '/'  都试过

**Comment by xiegegege** [comment]
@AN-ZE hi~我这里测试了下是能输出output文件的
<img width="725" alt="165e26d8f86182e9873e1d70216bec75" src="https://user-images.githubusercontent.com/46314656/86096639-1cffec00-bae6-11ea-8825-7bc64fab4bc5.png">
我感觉是你这里用的模型不对，麻烦确认下模型是不是先导出了。
<img width="769" alt="32e1a16f5ec60898f769dc2418c2f2fd" src="https://user-images.githubusercontent.com/46314656/86097447-3fded000-bae7-11ea-9556-e6ae2c5f5d82.png">
如果你跑的是fruit那个模型的话，需要先运行下
python tools/export_model.py -c configs/yolov3_mobilenet_v1_fruit.yml --output_dir=./inference_model -o weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_mobilenet_v1_fruit.tar

**Comment by AN-ZE** [comment]
@xiegegege 模型应该是导出成功的，使用python预测导出模型是正常的。我试一下你发的这个。

**Comment by AN-ZE** [comment]
@xiegegege  用你发的这个yolov3，python版和c++都是有输出的。

**Comment by xiegegege** [comment]
@AN-ZE 那麻烦问下是哪个模型没有输出呢？是提供的模型吗？我们检查下哪有问题

**Comment by AN-ZE** [comment]
@xiegegege  使用的模型是cascade_frcnn_r50vd_dcn_fpn，自己训练的水果，testreader的处理方式没有进行修改过。

**Comment by xiegegege** [comment]
@AN-ZE 在导出模型的时候加个参数-o TestReader.inputs_def.image_shape=[3,640,640]（图片大小可以随意设），应该就可以了

**Comment by AN-ZE** [comment]
> 
> 
> @AN-ZE 在导出模型的时候加个参数-o TestReader.inputs_def.image_shape=[3,640,640]（图片大小可以随意设），应该就可以了

@xiegegege 添加之后有输出结果了，不过输出的结果回框不对。python版是正常的。
![图片](https://user-images.githubusercontent.com/29450812/86196922-d0b8b880-bb86-11ea-8e15-c9c08de51799.png)

**Comment by xiegegege** [comment]
@AN-ZE 我用默认的coco数据集测是没问题的，你方便发下用的模型和图片吗？

**Comment by AN-ZE** [comment]
@xiegegege  我使用的是自制voc，c++输出总有越界边界框出现。image_shape参数设置发现，与原图接近，效果越好。不过python版的与不设置的结果还是有差距的。

![图片](https://user-images.githubusercontent.com/29450812/86202822-eda8b800-bb95-11ea-902b-1d1578e15c56.png)

**Comment by xiegegege** [comment]
嗯嗯， #1003 这个pr合入后deploy/cpp就不用设置image_shape了

**Comment by AN-ZE** [comment]
@xiegegege  好的，谢谢。另外发现训练单卡和8卡是没有问题的，但训练2卡是不行的。是哪里我需要修改吗？我目前的gpu设置方式是通过export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7，选择一个或者8个。

**Comment by xiegegege** [comment]
对的，是这样设置的，2卡应该是可以训练的，注意下输入命令nvidia-smi看下选择的两个卡的剩余显存是不是够的，还有就是提供的配置文件默认是8卡的，2卡需要调整下学习率 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/FAQ.md

**Comment by AN-ZE** [comment]
> 
> 
> 嗯嗯， #1003 这个pr合入后deploy/cpp不设置image_shape也可以了
关于这个问题，如果在导出模型时，没有设置image_shape参数，python版infer.py 输出结果也会有如图相应的异常结果（输出框异常）。相应的python版infer也需要进行修改。

**Comment by xiegegege** [comment]
@AN-ZE 这个是不是因为模型没训好？我看提供的coco训的模型预测的挺正常的

**Comment by AN-ZE** [comment]
@xiegegege 是还没训完呢，不过不应该导出的模型和用tool/infer.py预测结果不一样把。
另外发现，导出模型的c++和python版预测，resize预处理会将图片固定到固定尺寸，不是说不使用rt预测是不需要固定尺寸吗。配置文件没有设置image_shape参数，按理是默认参数None，不会进行padding到固定尺寸吧，昨天测试发现会进入padding操作，c++和python都有这个问题。
麻烦帮忙看下这里是不是存在问题。

**Comment by AN-ZE** [comment]
@xiegegege  找到问题了，这条代码存在问题，按照代码逻辑，不应该进行padding的。造成两次的输入图像是不一样的。修改之后正常了，c++预测也同样情况。
![图片](https://user-images.githubusercontent.com/29450812/86995997-09870c00-c1dd-11ea-9e66-116173f21241.png)

![图片](https://user-images.githubusercontent.com/29450812/86996022-1e639f80-c1dd-11ea-8f18-f71a08685097.png)
