### ISSUE TITLE
host_id 问题

### ISSUE THREAD

**Issue by yangyang117** [PaddlePaddle/PaddleDetection#988]
请问我在aistudio上进行一个项目的训练，怎么查看自己项目的 host_id呢？以及自己的port_num?
具体命令如下行：
visualdl --logdir vdl_fruit_dir/scalar/ --host <host_IP> --port <port_num>

**Comment by ShenYuhan** [comment]
您好，由于AiStuidio的特殊性，打开VisualDL面板的方式和本地略有不同：
 - 复制项目网址，并将网址中'notebooks'后的内容替换为'visualdl'（包含'notebook'），例如：
  将'https://aistudio.baidu.com/bdvgpu/user/220109/502834/notebooks/502834.ipynb?redirects=1'更改为'https://aistudio.baidu.com/bdvgpu/user/220109/502834/visualdl'
 - 打开浏览器输入网址即可启动VisualDL实现可视化
具体请参照[AiStudio使用VisualDL](https://aistudio.baidu.com/aistudio/projectdetail/502834)
欢迎在VisualDL的Issue进行更多交流[VisualDL](https://github.com/PaddlePaddle/VisualDL)
