### ISSUE TITLE
如何导出模型大小和参数量大小

### ISSUE THREAD

**Issue by May52** [PaddlePaddle/PaddleDetection#989]
使用PaddleDetection训练YOLOv3模型后，保存了.pdmodel文件和.pdparams文件，如果要得到一般论文里面提到的模型大小（MB）和参数量Params（M），该如何操作呢？模型大小与加载的目标检测预训练模型大小相关吗？

**Comment by qingqing01** [comment]
@May52  

粗略的查看：

模型大小（MB）:  可以通过 `du -h .pdparams`文件查看。
参数量Params（M）：  模型大小除以4。 (float类型是4个字节)


精细的查看：

可以参考: (paddle.fluid.io.get_program_parameter)[https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/get_program_parameter_cn.html#get-program-parameter] 接口，在tools/infer.py 或 tools/export_model.py 中，对infer_prog，使用得到所有parameters，挨个计算shape， 累加个数，统计大小。

**Comment by qingqing01** [comment]
@May52 做了一些更正：

参考： https://github.com/PaddlePaddle/PaddleDetection/issues/1024#issuecomment-654766401

我们后续加个工具统计Params数吧。 您也可以参考我上面提供的方法。
