### ISSUE TITLE
Python端预测部署trt错误。

### ISSUE THREAD

**Issue by lwbmowgli** [PaddlePaddle/PaddleDetection#991]
使用release0.3以及master均出现trt错误。命令如下：
python3.7 deploy/python/infer.py --model_dir=/paddle/inference_model/yolov3_darknet --image_file=/paddle/images/test.jpg --use_gpu=True --run_mode=trt_fp16
![image](https://user-images.githubusercontent.com/32731935/85945233-f8cdcf00-b96e-11ea-9239-089da634d293.png)
我分别尝试了paddle1.8.1和paddle2.0.0.报错信息是一样的，当我的run_mode=fluid时，不会报错。
另外，如果我自己训练了模型的时候，在导出模型的时候会报错。
python -u tools/train.py -c configs/yolov3_mobilenet_v1_fruit.yml --eval 迭代了20次。
模型保存形式如下：
![image](https://user-images.githubusercontent.com/32731935/85945300-7e517f00-b96f-11ea-975f-24078305e1c0.png)
报错信息如下：
![image](https://user-images.githubusercontent.com/32731935/85945529-1308ac80-b971-11ea-83f9-fa04ca1209b3.png)
![image](https://user-images.githubusercontent.com/32731935/85945537-20259b80-b971-11ea-802b-b6949c2c7872.png)

**Comment by qingqing01** [comment]
@lwbmowgli  默认按照官网安装的Python whl包编译时没有包含TensorRT，后续发布的版本才会包含。 当前，要使用TensorRT的话，得重新带TensorRT的包。

**Comment by thunder95** [comment]
我遇到了同样的问题,对paddle进行源码编译安装是否可以解决这个问题?

> @lwbmowgli 默认按照官网安装的Python whl包编译时没有包含TensorRT，后续发布的版本才会包含。 当前，要使用TensorRT的话，得重新带TensorRT的包。

**Comment by qingqing01** [comment]
@thunder95 编码编译时包含TensorRT可以解决这个问题。
