### ISSUE TITLE
如何设置全局的random seed?

### ISSUE THREAD

**Issue by nihuizhidao** [PaddlePaddle/PaddleDetection#993]
问一个关于复现的问题，在做实验的时候，想要保持随即条件不变，但是不知道PaddleDetection目前如何设置全局的random seed呢？是否可以在配置文件中设置呢？如果官方没有提供这个功能，自己可以如何设置呢？比如在 `tools/train.py`  的开头就使用 `paddle.framework.manual_seed`  来设置可以么？谢谢！

**Comment by qingqing01** [comment]
@nihuizhidao 

Python中的random和numpy的种子设置：

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/tools/train.py#L63

Paddle中的参数初始化等种子设置:

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/tools/train.py#L99

tools/train.py有个`enable_ce`的开关。

**Comment by nihuizhidao** [comment]
好的，多谢！
