### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by AN-ZE** [PaddlePaddle/PaddleDetection#994]
v0.2和v0.3区别大吗?
之前的训练一直是用0.2训练的，并用0.2的方式进行预测的。
0.3好像不能使用0.2的模型，预测没有反应。

**Comment by still-wait** [comment]
@AN-ZE 版本更新信息请参考[更新日志](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/CHANGELOG.md#v030052020)，是什么模型预测出现问题？

**Comment by still-wait** [comment]
@AN-ZE v0.3对预测做了更新，请使用0.3分支重新导出模型，会生成预测用的yaml配置文件`infer_cfg.yml`，再进行预测。

**Comment by AN-ZE** [comment]
> 
> 
> @AN-ZE v0.3对预测做了更新，请使用0.3分支重新导出模型([导出模型教程](https://paddledetection.readthedocs.io/advanced_tutorials/deploy/EXPORT_MODEL.html))，此时会生成预测用的yaml配置文件`infer_cfg.yml`，再进行预测。

模型不需要重新训练把，直接导出就可以把，我中午试试。

**Comment by still-wait** [comment]
@AN-ZE 不需要重新训练。
